### ISSUE TITLE
`comptime_int` exported constants are silently dropped

### ISSUE THREAD

**Issue by CrystalGamma** [ziglang/zig#10004]
### Zig Version

0.8.1

### Steps to Reproduce

Write a source file like this:

```zig
export const my_const = 42;
```

Build it, using e. g. `zig build-obj`. Inspect the resulting object file or assembly.

### Expected Behavior

Either a compiler error, or the value to be emitted using a default representation (though which one would be unclear, with `comptime_int` type).

### Actual Behavior

The constant is silently dropped.

**Comment by Vexu** [comment]
Fixed by #12075
