### ISSUE TITLE
failing CI

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#10008]
The CI has been especially unreliable lately. Apologies to everyone who has been opening pull requests and seen false negatives.

I'm in the process of acquiring our own hardware to run the CI stuff on, to increase reliability and make it easier to troubleshoot when a flaky test failure happens.

It's going to be annoying for another week or so and then hopefully we will have something sorted out.

Thanks for understanding, I know it's been really annoying lately for everyone.

**Comment by andrewrk** [comment]
Update: CI is getting closer to ready. Meanwhile, I rebooted the [gotta-go-fast](https://github.com/ziglang/gotta-go-fast/) repository and added some `zig ast-check` benchmarks. Have a look at the README to see the changes of how it works now. The next steps will be:

 * Backfilling some performance measurements
 * Adding html/javascript to ziglang.org/perf which download the data and display interactive graphs
 * Integrating with the new CI system so that performance measurements happen with every commit

**Comment by andrewrk** [comment]
[we have our first self-hosted CI run](https://ci.ziglang.org/ziglang/zig/1)

**Comment by andrewrk** [comment]
x86_64 Linux has now been moved over to ci.ziglang.org. This should already improve stability of the CI and we are still planning on moving more over.

Meanwhile, https://ziglang.org/perf is live. Adjustments are still being made to integrate the page with the rest of the website as well as to the graphs.

**Comment by RossSmyth** [comment]
Having a Zig [Bors](https://github.com/graydon/bors)/[Homu](https://github.com/barosl/homu) may be a good idea so that all PR's are tested as the head of master before merging.

**Comment by matu3ba** [comment]
@RossSmyth The Azure build jobs on Windows are (yet) too unstable to do that unless Windows is excluded, lol. For example [10172](https://dev.azure.com/ziglang/zig/_build/results?buildId=17960&view=results) [10168](https://dev.azure.com/ziglang/zig/_build/results?buildId=17959&view=results) [10161](https://dev.azure.com/ziglang/zig/_build/results?buildId=17959&view=results) [10151](https://dev.azure.com/ziglang/zig/_build/results?buildId=17885&view=results) all failed due to Windows timing out after 6 hours.

**Comment by andrewrk** [comment]
This particular issue is resolved. We have moved some things over to our self-hosted CI, reduced memory usage, and disabled flaky tests, and now CI is in an OK state.

**Comment by andrewrk** [comment]
Reopening - I'm seeing the aarch64 drone CI failing due to timeouts sometimes.

**Comment by andrewrk** [comment]
Solved in b095aa6986badc3b8c2255ad2c824ca4ea9959d9
