### ISSUE TITLE
inline/comptime loop closure naively captures the last value for all iterations

### ISSUE THREAD

**Issue by fengb** [ziglang/zig#10029]
### Remember to search before filing a new report

- [X] I searched for this bug and did not find it in the issue tracker, and furthermore, the title I used above will make this new bug report turn up in the search results for my query.

### Zig Version

0.9.0-dev.1441+3b2e25ed8

### Steps to Reproduce

When using an inline loop, the captured variables "mutate" in-place. If we create a closure function inside the body, this value always converts to the last iteration value (this is the same ~~bug~~ design quirk that occurs in [Golang](https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable)):

```zig
comptime var prints: [3]fn () void = undefined;
inline for (.{ .foo, .foobar, .bar }) |literal, i| {
    prints[i] = struct {
        fn closure() void {
            std.debug.print("{} {}\n", .{i, literal});
        }
    }.closure;
}

inline for (prints) |print| {
    print();
}
```

### Expected Behavior

```
0 .foo
1 .foobar
2 .bar
```

### Actual Behavior

```
3 .bar
3 .bar
3 .bar
```

**Comment by Validark** [comment]
Fun fact: I fixed this bug in a TypeScript to Lua compiler. This must be a pretty common oversight in new compilers.
Bug report: https://github.com/roblox-ts/roblox-ts/issues/176

**Comment by Vexu** [comment]
Fixed in master.
