### ISSUE TITLE
Allocgate

### ISSUE THREAD

**Issue by leecannon** [ziglang/zig#10052]
It was noticed in #10037 that LLVM is not able to properly optimize interfaces that use `@fieldParentPtr` as per @SpexGuy's [comment](https://github.com/ziglang/zig/issues/10037#issuecomment-952205513).

The `Random` interface was changed in #10045 to instead use a type erased pointer in place of `@fieldParentPointer` resulting in significant performance improvement.

This issue is to track applying the same change to `Allocator`, however due to this interface being much more widely used it is planned to be merged just before the 0.9.0 release.

Soon I will open a draft PR to begin working on this.

**Comment by locriacyber** [comment]
I think we should add a unified way for implementing polymorphism. #10184
