### ISSUE TITLE
Pointers for NVPTX support

### ISSUE THREAD

**Issue by gwenzek** [ziglang/zig#10064]
NVPTX backend is currently Tier 4 in Zig, 
yet there still might be people interested in improving support for it (like myself)
Here I'm sharing a few pointers provided by @Snektron to get started, complemented by information I've glanned from LLVM and Nvidia documentation.

I've also started a branch with an ongoing implementation.
I'm learning both about the Zig compiler and LLVM at the same time so beware ! https://github.com/gwenzek/zig/pull/1

# Adress spaces

PTX format defines a VM for the GPU and an ISA. The VM make uses of different memory spaces.
Address space support has been added to Stage 2, so you'll need to use stage 2.
Only a few generic adress spaces have been defined, but more should be added for Nvidia GPU:

https://github.com/ziglang/zig/blob/70ef9bc75c42ec00e9d4231a2e1f1dca84144748/lib/std/builtin.zig#L172-L177

And defaults here:

https://github.com/ziglang/zig/blob/70ef9bc75c42ec00e9d4231a2e1f1dca84144748/src/target.zig#L573-L577 

(for nvptx you probably want the .constant addrspace for constants for example, also .local for locals, etc
Then convert Zig address spaces to llvm address spaces here:

https://github.com/ziglang/zig/blob/70ef9bc75c42ec00e9d4231a2e1f1dca84144748/src/codegen/llvm.zig#L717

The Zig bindings already have definition for Nvidia memory spaces:
https://github.com/ziglang/zig/blob/70ef9bc75c42ec00e9d4231a2e1f1dca84144748/src/codegen/llvm/bindings.zig#L1283-L1290

To better understand what Zig needs to do you can look at a sample kernel written in LLVM IR:
https://llvm.org/docs/NVPTXUsage.html#the-kernel
_I guess it would also be helpful to be able to generate LLVM IR from an arbitrary kernel 
apparently Clang can do so: https://www.llvm.org/docs/CompileCudaWithLLVM.html

Also one would need to implement support for Cuda special variables gridDim, gridIdx, ... which are stored in specials registers:
https://llvm.org/docs/NVPTXUsage.html#id7
as well as the intrinsic for the block barrier `__syncthreads`

I'm not sure how to do that yet.

**Comment by Snektron** [comment]
Intrinsics can be added by `CreateBinaryIntrinsic`, `CreateUnaryIntrinsic` and `CreateIntrinsic` functions provided by LLVM. See for an example how the `Intrinsic::umax` intrinsic is emitted in Zig:
https://github.com/ziglang/zig/blob/969bcb6a59eadb2ef46a9784286728a25d275c24/src/zig_llvm.cpp#L472-L475

According to the [LLVM NVPTX page](https://llvm.org/docs/NVPTXUsage.html#llvm-nvvm-barrier0), `__syncthreads` is `‘@llvm.nvvm.barrier0()’`. After some digging (opening `build/include/llvm/IR/IntrinsicEnums.inc` where `build` is the LLVM build directory), we can see that this translates to `Intrinsic::nvvm_barrier0`. Note that there is no C api call for `CreateIntrinsic`, so a shim would need to be added to `zig_llvm.cpp` in order to use this, similar to the other `Intrinsic` usages.

**Comment by daurnimator** [comment]
@gwenzek FYI on github you can press `y` to turn the URL into a specific commit; that way your links with line numbers won't move around.

**Comment by gwenzek** [comment]
I've started a prototype on https://github.com/gwenzek/zig/pull/1
I've added some glue code so that I can run:

```
.../stage2/bin/zig build-obj kernel.zig -target nvptx64-cuda -O ReleaseSafe -femit-llvm-ir
```

This will generate an invalid `kernel.ptx` which doesn't contain ptx code. I need to dig into LLVM documentation to understand how to make it generate PTX.

The main thing I was surprised is I had to modify [codegen.zig](https://github.com/gwenzek/zig/pull/1/files#diff-2827ae92d526f0e39d86ed72305129b25b895a99030b36a42fa220aed48606a1) even if I don't want to implement PTX generation
from Stage2, and only want to use LLVM for that. Is there a way of having an architecture that is only supported by LLVM and not by Zig itself ?

I've also created a new output format ".ptx" for the linker, as done for sprV or asm architectures.

**Comment by Snektron** [comment]
The path youre going now with https://github.com/gwenzek/zig/pull/1 is implementing your own code generation with nvptx in stage 2. You shouldn't need to create an entire custom link format, or enable nvptx in codegen.zig. In fact, can you try just running `zig build-obj -target nvptx-cuda -fLLVM -fno-stage1 kernel.zig` with an upstream build of stage 2? I think most of the llvm target definitions are already present, and the main thing to figure out is if we need to get llvm to emit bitcode instead of elf files.

**Comment by gwenzek** [comment]
@Snektron just retried without the change in codegen.zig, and it works, I must have used the wrong command at the begining.
The main thing I need to change to output PTX is that I need to ask LLVM to output assembly instead of an object.
For that I need to modify the `flushModule` to ask for a assembly.
Also I don't want to link the ".ptx" file I obtain so I think I need to create a `link/NvPtx.zig` if I'm not mistaken to disable that. 

I think a refactoring could make this cleaner, by having `Compilation.zig` check the architecture and enabling/disabling some options in there. Also it could be a good place to add the architecture specific validation that you put at https://github.com/ziglang/zig/blob/310f3dfe8ad60a942c37c74dbdf5828b94821f81/src/link/SpirV.zig#L73-L76

**Comment by gwenzek** [comment]
I've started looking into how to add support for the PTX intrinsics mentionned above. The default way seems to add an `@ptxSyncThreads` and `@ptxThreadId`, ... to Zig throught the various stage of the compiler. (Like `@wasmMemoryGrow` is implemented). 

Other approaches have been discussed in #7702, #4466.
But by looking in the issue backlog I also found #2291 that says that the `@"identifier"` syntax can be abused to generate LLVM intrinsic. 
I've tried it and the following snippet compiles with nvptx backend:

```zig
export fn hello(out: [*c]u8) void {
    out.* = 72 + @intCast(u8, threadIdX());
    __syncthreads();
}

extern fn @"llvm.nvvm.barrier0"() void;
inline fn __syncthreads() void {
    @"llvm.nvvm.barrier0"();
}
```

But for some reason LLVM called from Zig crashes when doing something similar for reading the special registers

```zig
extern fn @"llvm.nvvm.read.ptx.sreg.tid.x"() i32;
inline fn threadIdX() i32 {
    return @"llvm.nvvm.read.ptx.sreg.tid.x"();
}

export fn hello(out: [*c]u8) void {
    out.* = 72 + @intCast(u8, threadIdX());
}
```

the error message:

```
~/github/zig/stage2/bin/zig build-obj cudaz/kernel.zig -target nvptx64-cuda -O ReleaseSafe --verbose-llvm-ir 
info(link): Creatinsg .ptx target kernel.ptx.ptx
info(link): Updating function: 3:3
info(link): Updating function: 41:46
info(link): Flush kernel.ptx.ptx
; ModuleID = 'kernel'
source_filename = "kernel"
target datalayout = "e-i64:64-i128:128-v16:16-v32:32-n16:32:64"

; Function Attrs: noredzone nounwind
define dso_local void @entry() #0 {
Entry:
  ret void
}

; Function Attrs: noredzone nounwind
define dso_local void @hello(i8* %0) #0 {
Entry:
  %1 = alloca i32, align 4
  %2 = alloca i8*, align 8
  store i8* %0, i8** %2, align 8
  %3 = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
  store i32 %3, i32* %1, align 4
  %4 = load i32, i32* %1, align 4
  %5 = trunc i32 %4 to i8
  %6 = add nuw i8 72, %5
  store i8 %6, i8* %0, align 1
  ret void
}

; Function Attrs: noredzone nounwind
declare i32 @llvm.nvvm.read.ptx.sreg.tid.x() #0

attributes #0 = { noredzone nounwind "frame-pointer"="none" }
info(codegen): emit LLVM object to kernel.ptx.ptx
LLVM ERROR: Cannot select: intrinsic %llvm.nvvm.read.ptx.sreg.tid.x
zsh: IOT instruction (core dumped)  ~/github/zig/stage2/bin/zig build-obj cudaz/kernel.zig -target  -O  
134
```

Interestingly pasting the debug output into a `.ll` and calling directly `llc` on it works, and generate the following .ptx file:
So there must be something special in how we calling LLVM from Zig. I've tried changing some options, but without success.
I'm not familiar enough with LLVM to understand what could lead to a [Cannot select error](https://github.com/ziglang/zig-bootstrap/blob/4ed79aefb7a58a6d642f47a81e1ef04fd164042b/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp#L3797-L3797).

`~/local/llvm13-release/bin/llc  -mcpu=sm_20 --mtriple=nvptx64-nvidia-cuda kernel.ll -o kernel.ll.ptx`

```zig
	// .globl	hello                   // -- Begin function hello
.visible .func hello(
	.param .b64 hello_param_0
)                                       // @hello
{
	.reg .b16 	%rs<3>;
	.reg .b32 	%r<2>;
	.reg .b64 	%rd<2>;

// %bb.0:                               // %Entry
	ld.param.u64 	%rd1, [hello_param_0];
	mov.u32 	%r1, %tid.x;
	cvt.u16.u32 	%rs1, %r1;
	add.s16 	%rs2, %rs1, 72;
	st.u8 	[%rd1], %rs2;
	ret;
                                        // -- End function
}
```

Anyway given that the "assembly" corresponding to reading from a register is pretty simple I also tried to 
generate the corresponding assembly directly using `asm` keyword which seems to have seen some recent improvement in Stage 2.

So to generate `mov.u32 	%r1, %tid.x;` in PTX it seems I need 
`call i32 asm sideeffect "mov.u32 \09$0, %tid.x;", "=r"()` in LLVM, which can be generated by

```zig
asm volatile ("mov.u32 \t$0, %tid.x;"
        : [ret] "=r" (-> i32)
    );
```
 
So stay tuned, because I feel I'm making progress ^^ 
I still need to test the generated ptx, but I feel l'll be able to make some progress without having to poke too much into stage2 internals (which I appreciate)

**Comment by gwenzek** [comment]
Since my presentation at last [Zig Rush](https://youtu.be/rvfsWm6TckA?t=5351) I removed the worst hacks,
and made PR #10189

**Comment by gwenzek** [comment]
I've opened #12878 to update the backend to 0.10. I feel we are in a good place now, I'll close this issue.

Thanks to the progress of self hosted, we can now generate debug information in the PTX files. Also the assembly syntax now works as documented, so it's simpler to use special ptx registers. And I can use the same zig binary for building the device and host code, so it's pretty exciting.

See https://github.com/gwenzek/cudaz/tree/e8895596009c689300fe7c7193fa2dbf7db07629 for user code using this Zig branch.

**Comment by classner** [comment]
@gwenzek Is it possible to experiment with this on the latest zig (since it looks like all PRs have been merged)? I'm just curious, since Andrew added it to the 0.12.0 milestone - so is it not on main yet?

**Comment by nektro** [comment]
its in the 0.10 milestone

**Comment by Snektron** [comment]
Support for the ptx backend is kind of a work in progress, but it should work for some programs already. You can check out [this](https://github.com/gwenzek/cudaz) repository for some pointers on how to get started, but I think the Zig parts are a little bit out of date. In general it should mostly work.

**Comment by integer-arithmeticone-ma** [comment]
> [@gwenzek](https://github.com/gwenzek) Is it possible to experiment with this on the latest zig (since it looks like all PRs have been merged)? I'm just curious, since Andrew added it to the 0.12.0 milestone - so is it not on main yet?





https://stackdev.space/questions/what-is-the-mechanism-behind-unary-addition-on-c-pointers
