### ISSUE TITLE
use of undeclared identifier 'expect'

### ISSUE THREAD

**Issue by omd24** [ziglang/zig#10072]
### Remember to search before filing a new report

- [X] I searched for this bug and did not find it in the issue tracker, and furthermore, the title I used above will make this new bug report turn up in the search results for my query.

### Zig Version

0.9.0-dev.1444+e2a2e6c14

### Steps to Reproduce

I used the following code from ziglearn.org and got `error: use of undeclared identifier 'expect'` 
`
fn fibonacci(n: u16) u16 {
    if (n == 0 or n == 1) return n;
    return fibonacci(n - 1) + fibonacci(n - 2);
}

test "function recursion" {
    const x = fibonacci(10);
    try expect(x == 55);
}
`

### Expected Behavior

I didn't have any problem so far running other examples from ziglearn but all of a sudden encountered this issue with `expect` 

### Actual Behavior

`
error: use of undeclared identifier 'expect'
    try expect(x == 55);
        ^
`

**Comment by VesperQuartz** [comment]
Did you fix this?

**Comment by jrfondren** [comment]
zig.guide uses abbreviated code examples. The code in https://zig.guide/language-basics/functions works with these additional lines:

```zig
const std = @import("std");
const expect = std.testing.expect;
```

You can suggest that this change at https://github.com/Sobeston/zig.guide/issues
