### ISSUE TITLE
zig cc Illegal Instruction on left-shifting s32 = u16 << 16

### ISSUE THREAD

**Issue by vvrbanc** [ziglang/zig#10078]
### Remember to search before filing a new report

- [X] I searched for this bug and did not find it in the issue tracker, and furthermore, the title I used above will make this new bug report turn up in the search results for my query.

### Zig Version

0.8.1

### Steps to Reproduce

The following C program produces an illegal instruction error at runtime after being compiled with zig cc. 
It does not do this with gcc and clang.

#include <stdio.h>
int main() {
    int a;
    unsigned short b = 33000;
    a = b << 16;
    printf("%i\n", a);
}

Tested on amd64 linux on 0.7.1, 0.8.1 and 0.9.0-dev.1551

### Expected Behavior

gcc and clang give the result -2132279296.

I suppose it is undefined behavior. The highest bit of uint16 becomes sign bit of sint32 and in this case produces a negative number.

I think zig should do what gcc and clag do, I.E. shl by 16 and assume the programmer knows or does not care what happens.

When compiled with "gcc -fsanitize=undefined", at runtime it produces this warning:
"runtime error: left shift of 33000 by 16 places cannot be represented in type 'int'"

### Actual Behavior

zig cc produces an illegal instruction

**Comment by leecannon** [comment]
Zig compiles c code with undefined behaviour sanitizer on for safe modes, you have to pass `-fnosanitize=undefined` to disable it or compile with `-OReleaseFast`

The reason it doesn't give a message regarding what the ub is like clang does is because there is more work needed to be done on zigs side to provide that all it does currently is emit an illegal instruction .

**Comment by g-w1** [comment]
This is not a bug: https://github.com/ziglang/zig/wiki/FAQ#why-do-i-get-illegal-instruction-when-using-with-zig-cc-to-build-c-code
