### ISSUE TITLE
compiler-rt does not define aarch64 outline atomics

### ISSUE THREAD

**Issue by nitsky** [ziglang/zig#10086]
### Zig Version

0.9.0-dev.1551+8346e011c

### Steps to Reproduce

On aarch64 linux:

```c
#include <stdatomic.h>
#include <stdio.h>

int main() {
  atomic_int atomic_counter = 0;
  atomic_counter++;
  printf("%u\n", atomic_counter);
}
```

1. `gcc main.c`
2. `zig cc main.c`
3. `gcc -moutline-atomics main.c`
4. `zig cc -moutline-atomics main.c`

### Expected Behavior

I expect all variations to compile and run correctly.

### Actual Behavior

`zig cc -moutline-atomics main.c` fails to compile:

```
ld.lld: error: undefined symbol: __aarch64_ldadd4_acq_rel
```

I discovered this issue while attempting to cross compile Rust to aarch64-linux with `zig cc`. Rust enables outline atomics by default on aarch64-linux and currently [prohibits disabling them](https://github.com/rust-lang/rust/blob/56694b04532cc0dec6e2f577135da3513e856923/compiler/rustc_codegen_llvm/src/llvm_util.rs#L405-L411).

**Comment by andrewrk** [comment]
Thanks for the report. How is the `__aarch64_ldadd4_acq_rel` symbol expected to be provided? It does not appear to be included in LLVM's compiler-rt. Is that a gcc extension?

**Comment by nitsky** [comment]
@andrewrk I see that outline atomics were added to compiler-rt a year ago: https://reviews.llvm.org/D91156.

**Comment by andrewrk** [comment]
Ah, I see the symbol names are constructed with string concatenation. Missed that in my grepping. Thanks! So the next step to resolve this issue is to port more of LLVM's compiler-rt into zig's.

**Comment by nitsky** [comment]
Great, thanks. For those running into this issue with Rust, https://github.com/rust-lang/rust/pull/90623 was recently merged which allows you to disable outline atomics with `-C target-feature=-outline-atomics`.

**Comment by irishgreencitrus** [comment]
I have this issue compiling https://github.com/mattnite/gyro on aarch64 Raspberry Pi OS, with just normal `zig build`

**Comment by PiotrSikora** [comment]
`zig c++` seems to be completely broken when cross-compiling to `aarch64-linux-*`, because `libc++` relies on atomics.
```
$ cat hello.cpp
```
```
#include <iostream>

int main() {
    std::cout << "Hello, World!" << std::endl;
    return 0;
}
```
```
$ zig c++ -target aarch64-linux-musl hello.cpp
```
```
ld.lld: error: undefined symbol: __aarch64_ldadd8_acq_rel
>>> referenced by cxa_exception.cpp
[...]
ld.lld: error: undefined symbol: __aarch64_swp8_acq_rel
>>> referenced by cxa_handlers.cpp
[...]
ld.lld: error: undefined symbol: __aarch64_ldadd4_acq_rel
>>> referenced by ios.cpp
[...]
ld.lld: error: undefined symbol: __aarch64_ldadd8_relax
>>> referenced by memory.cpp
[...]
ld.lld: error: undefined symbol: __aarch64_cas8_acq_rel
>>> referenced by memory.cpp
```

**Comment by PiotrSikora** [comment]
My issue above results in the same errors, but it's actually unrelated. I filed a new issue: https://github.com/ziglang/zig/issues/10777.

**Comment by prenex** [comment]
I tried to use zig to cross-compile my codebase easier so that I can develop on my pinephone while walking but have parts of the project pre-cross-compiled on a stronger machine.

Sadly these kind of errors still crop up for me when the code uses std::shared_ptr. Are there any workarounds for a real c++ codebase or some things that I can turn off so some simpler code is generated or anything?

**Comment by andrewrk** [comment]
I suspect that many people running into this issue are running into it because native CPU detection for aarch64 is failing to correctly identify the CPU features available in some cases. Here I have a Neoverse-N1 CPU:

```
andy@Debian-bullseye-latest-arm64-base:~/zig/build-release$ lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          80
On-line CPU(s) list:             0-79
Thread(s) per core:              1
Core(s) per socket:              80
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       ARM
Model:                           1
Model name:                      Neoverse-N1
Stepping:                        r3p1
Frequency boost:                 disabled
CPU max MHz:                     3000.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        50.00
L1d cache:                       5 MiB
L1i cache:                       5 MiB
L2 cache:                        80 MiB
NUMA node0 CPU(s):               0-79
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; CSV2, BHB
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid 
                                 asimdrdm lrcpc dcpop asimddp ssbs
```

You can see that it is Neoverse-N1, and that it has the `atomics` flag which I believe corresponds to `lse`. Zig does have awareness of this cpu:

https://github.com/ziglang/zig/blob/master/lib/std/target/aarch64.zig#L2091-L2106

However, `zig build-exe --show-builtin` does not pick it up:

```
pub const cpu: std.Target.Cpu = .{
    .arch = .aarch64,
    .model = &std.Target.aarch64.cpu.generic,
    .features = std.Target.aarch64.featureSet(&[_]std.Target.aarch64.Feature{
        .ete,
        .fp_armv8,
        .fuse_adrp_add,
        .fuse_aes,
        .neon,
        .trbe,
        .use_postra_scheduler,
    }),
};
```

It is precisely because it sees the CPU as "generic" that it does not enable atomics, causing this issue.

To be clear, compiler_rt still needs to be augmented with these functions. However, there is a second, perhaps more important issue, which is that native CPU detection is not working.

Another clue here is that `/proc/cpuinfo` is missing the model name, even though `lscpu` is producing it:

```
processor	: 76
BogoMIPS	: 50.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1
```

This is perhaps an indicator that the implementation of `lscpu` does something different than looking at `/proc/cpuinfo` and we should read its source code to see what that logic is.

**Comment by LemonBoy** [comment]
Add `.m64 = &A64.neoverse_n1` [here](https://github.com/ziglang/zig/blob/476b946802e8a5500ece44822c8f6d103a71bbb5/lib/std/zig/system/linux.zig#L207), checking if there are any other missing entries is left as an exercise for the reader.

**Comment by andrewrk** [comment]
I'm confused why [zig-bootstrap](https://github.com/ziglang/zig-bootstrap) is able to produce aarch64-linux binaries without running into this issue. In this case, it targets the generic cpu, which, as noted in https://github.com/ziglang/zig/issues/10086#issuecomment-1321036345, is missing the `lse` feature. I would therefore expect to see undefined symbol errors when linking.

**Comment by tmm1** [comment]
Thanks for implementing these!

When cross compiling (with `zig cc -target aarch64-linux-gnu`), how can I force the wrappers (such as `__aarch64_ldadd4_acq_rel`) to be included in my binary regardless of if they're being used? My program uses `dlopen` on a .so file during runtime and that shared library expects these symbols to be present.
