### ISSUE TITLE
Error: cannot resolve inferred error set '@typeInfo(@typeInfo(@TypeOf(avl_tree.Node.insert)).Fn.return_type.?).ErrorUnion.error_set': function 'avl_tree.Node.insert' not fully analyzed yet

### ISSUE THREAD

**Issue by byte911** [ziglang/zig#10099]
### Remember to search before filing a new report

- [X] I searched for this bug and did not find it in the issue tracker, and furthermore, the title I used above will make this new bug report turn up in the search results for my query.

### Zig Version

0.9.0-dev.1444+e2a2e6c14

### Steps to Reproduce

> zig test [avl_tree.test.zig](https://gist.github.com/byte911/624055af61e673fe94fa37497a5fd4ca)

### Expected Behavior

Build successfully

### Actual Behavior

cannot resolve inferred error set

**Comment by leecannon** [comment]
This is a known issue with infering a recursive function's error set in the stage1 compiler to work around it the recursive function needs to have a concrete error set

change the signature of `insert` to:
```zig
fn insert(self: ?*N, value: T, gpa: *Allocator) Allocator.Error!*N
```

**Comment by byte911** [comment]
> This is a known issue with infering a recursive function's error set in the stage1 compiler, to work around it the recursive function needs to have a concrete error set.
> 
> change the signature of `insert` to:
> 
> ```zig
> fn insert(self: ?*N, value: T, gpa: *Allocator) Allocator.Error!*N
> ```
> 
> see #2971

Thanks

**Comment by byte911** [comment]
Duplicated with #2971
