### ISSUE TITLE
stage2 fails to build on macOS w/ llvm13 from source because of missing terminfo symbols

### ISSUE THREAD

**Issue by toffaletti** [ziglang/zig#10095]
### Remember to search before filing a new report

- [X] I searched for this bug and did not find it in the issue tracker, and furthermore, the title I used above will make this new bug report turn up in the search results for my query.

### Zig Version

0.9.0-dev.1573+a55dc4a3b

### Steps to Reproduce

On an M1 Mac I followed the instructions for [building zig from source](https://github.com/ziglang/zig/wiki/Building-Zig-From-Source). I chose the path of [building LLVM from source](https://github.com/ziglang/zig/wiki/How-to-build-LLVM,-libclang,-and-liblld-from-source#posix) in release mode.

I built stage1 and from there continued to stage2, which is where I ran into an issue.

### Expected Behavior

I expected to be able to build stage2.

### Actual Behavior

```
❯ ~/local/zig/bin/zig build --zig-lib-dir lib --prefix (pwd)/stage2 --search-prefix $HOME/local/llvm13-release -Denable-llvm=true -Dstatic-llvm=true
warning(link): directory not found for '-L/usr/local/lib'
error(link): undefined reference to symbol '_del_curterm'
error(link):   first referenced in '/Users/jason/local/llvm13-release/lib/libLLVMSupport.a(Process.cpp.o)'
error(link): undefined reference to symbol '_setupterm'
error(link):   first referenced in '/Users/jason/local/llvm13-release/lib/libLLVMSupport.a(Process.cpp.o)'
error(link): undefined reference to symbol '_tigetnum'
error(link):   first referenced in '/Users/jason/local/llvm13-release/lib/libLLVMSupport.a(Process.cpp.o)'
error(link): undefined reference to symbol '_set_curterm'
error(link):   first referenced in '/Users/jason/local/llvm13-release/lib/libLLVMSupport.a(Process.cpp.o)'
thread 334257 panic: attempt to unwrap error: UndefinedSymbolReference
```

It looks like there are two possible solutions to this:
1. Disabled terminfo when building LLVM: `-DLLVM_ENABLE_TERMINFO=OFF`
2. Teaching stage2 where to get these symbols.

I chose 2, but just a quick and dirty fix:
```
diff --git a/build.zig b/build.zig
index 56abec9e2..69c59e656 100644
--- a/build.zig
+++ b/build.zig
@@ -532,6 +532,7 @@ fn addStaticLlvmOptionsToExe(
     }
 
     exe.linkSystemLibrary("z");
+    exe.linkSystemLibrary("curses");
 
     // This means we rely on clang-or-zig-built LLVM, Clang, LLD libraries.
     exe.linkSystemLibrary("c++");
```

It seems like what I'm really doing here is working around a bug in `llvm-config` in that it doesn't list libcurses as a requirement?

**Comment by andrewrk** [comment]
> It seems like what I'm really doing here is working around a bug in `llvm-config` in that it doesn't list libcurses as a requirement?

Yes that is correct.

Thanks for the report. I updated the wiki instructions to include `-DLLVM_ENABLE_TERMINFO=OFF`.
