### ISSUE TITLE
@sizeOf() packed struct changes depending on relative sizes of members

### ISSUE THREAD

**Issue by mirrexagon** [ziglang/zig#10104]
### Remember to search before filing a new report

- [X] I searched for this bug and did not find it in the issue tracker, and furthermore, the title I used above will make this new bug report turn up in the search results for my query.

### Zig Version

0.9.0 (built with Nix from master commit e97feb96e4daf7d53538c9c8773d50459a59e5ee)

### Steps to Reproduce

```zig
const std = @import("std");

const txdata = packed struct {
    /// Transmit data (RW)
    data: u8,
    _reserved_8: u23,
    /// Transmit FIFO full (RO)
    full: bool = false,
};

const txdata_passes = packed struct {
    /// Transmit data (RW)
    data: u9, // Changed to u9
    _reserved_8: u22, // Changed to u22
    /// Transmit FIFO full (RO)
    full: bool = false,
};

const register_size_bits = 32;
const register_size_bytes = register_size_bits / 8;

test "txdata size correct but fails" {
    try std.testing.expectEqual(register_size_bits, @bitSizeOf(txdata));
    try std.testing.expectEqual(register_size_bytes, @sizeOf(txdata));
}

test "txdata size adjusted to pass" {
    try std.testing.expectEqual(register_size_bits, @bitSizeOf(txdata_passes));
    try std.testing.expectEqual(register_size_bytes, @sizeOf(txdata_passes));
}
```

Run `zig test` on the above.

### Expected Behavior

 `@bitSizeOf(txdata)` and `@bitSizeOf(txdata_passes)` should be 32, and `@sizeOf(txdata)` and  `@sizeOf(txdata_passes)` should be 4.

### Actual Behavior

`@sizeOf(txdata)` is 5.

---

This came up when implementing MMIO registers here: https://github.com/mirrexagon/luxos/blob/a0d46e992ac256685ee36a85f9f255299f0fbe7d/src/target/soc/fe310-g002/uart.zig#L50

Trying to `@bitCast()` between `txdata` and `usize` (32 bits on `riscv32`) failed due to this. I can work around this by increasing the size of the `data` member from `u8` to `u9`, and decreasing the size of the next member by one bit (`u23` to `u22`) - doing that makes the sizes match up.

Also affects this register: https://github.com/mirrexagon/luxos/blob/a0d46e992ac256685ee36a85f9f255299f0fbe7d/src/target/arch/riscv/mcsr.zig#L17

Is this something that should work? My understanding is that packed structs that fit exactly into a whole number of bytes should not have any padding.

I'm unsure if this is related to or would be fixed by #8102.

**Comment by igor84** [comment]
I just noticed that this code:
```zig
export fn run() u8 {
    const TestStruct = packed struct {
        a: u32,
        b: [3]u8,
    };
    return @sizeOf(TestStruct);
}
```
returns 8 instead of 7, but if I change b array to have 2 elements it returns correct 6.

**Comment by mirrexagon** [comment]
#11279 appears to fix my use case! Thanks @igor84 for your work!
