### ISSUE TITLE
Make std.fmt.parseInt() accept the prefix even if radix is specified

### ISSUE THREAD

**Issue by LewisGaul** [ziglang/zig#10144]
### Zig Version

0.9.0-dev.1626+1d55705fa

### Steps to Reproduce

```zig
const std = @import("std");

test {
    _ = try std.fmt.parseInt(i32, "0x12", 0);
    _ = try std.fmt.parseInt(i32, "0x12", 16);
}
```
This testcase fails on the second line, where radix is given explicitly as 16, but the first line succeeds where radix is determined from the prefix.

### Expected Behavior

Should still be valid to include the prefix corresponding to (and of course matching!) a specified radix.

### Actual Behavior

Error returned when a prefix is included when radix is specified.

**Comment by LewisGaul** [comment]
I'm happy to fix this if it's agreed this should be fixed. Maybe worth noting that `strtoul("0x12", NULL, 16)` is valid in C.

**Comment by andrewrk** [comment]
I don't agree with this, if the radix is specified, then it should *not* accept the prefix.
