### ISSUE TITLE
Stage 2 segfaults in `_start`, tries to write to `__libc_single_threaded`. Mislinkage?

### ISSUE THREAD

**Issue by Freakness109** [ziglang/zig#10154]
### Zig Version

0.9.0-dev.1626+1d55705fa

### Steps to Reproduce

Build stage 1 with cmake:
`mkdir build-release && cd build-release && cmake ..`
Turn on `ZIG_PREFER_CLANG_CPP_DYLIB` via ccmake
Compile with `make`

Compile stage 2 with: `./build-release/zig build --zig-lib-dir lib --prefix $(pwd)/stage2 -Denable-llvm -Dstatic-llvm=false`
Try to run zig stage 2: `stage2/zig`

### Expected Behavior

No segfaults, stage 2 prints the help menu.

### Actual Behavior

Program segfaults.

Looking at the executable with gdb, it seems that the issue happens during libc initialisation: in `__libc_early_init`, `__libc_single_threaded` is assigned. This segfaults the process. It seems as if the symbol is not treated as external variable, but as an external function, as disassembling the location of `__libc_single_threaded@plt` in gdb gives:
```asm
jmp    QWORD PTR [rip+0xc7922]        # 0x176f068 <__libc_single_threaded@got.plt>
push   0x145
jmp    0x16a62e0
```
Jumping over the write to `__libc_single_threaded` makes the menu appear as expected.

**Comment by andrewrk** [comment]
This points to a problem with the .so file that you have on your system or something having to do with the LLVM/clang/lld package that your system is providing. It's not something we can solve on our end.

Suggest building zig from source instead, since the system packages are broken.
