### ISSUE TITLE
Compiler crashes when passing optional optional to std.mem.span

### ISSUE THREAD

**Issue by InKryption** [ziglang/zig#10169]
### Remember to search before filing a new report

- [X] I searched for this bug and did not find it in the issue tracker, and furthermore, the title I used above will make this new bug report turn up in the search results for my query.

### Zig Version

0.9.0-dev.1675+3d528161c

### Steps to Reproduce

Exact, minimal snippet that causes the crash when evaluated (whether in `main` or in a `test`, on any optimization level, but not if wrapped in a `comptime` block):
```
_ = @import("std").mem.span(@as(??[]const u8, &.{ 0, 1, 2 }));
/// _ = @import("std").mem.span(@as(??[]const u8, null));
```

### Expected Behavior

The  `span` function to returns a value of type `@import("std").mem.Span(??[]u8)` (which is equal to `??[]u8`). 

### Actual Behavior

```
Semantic Analysis [1300/1767] when analyzing C:\Users\InK\zig-lang\zig\lib\std\mem.zig:625:24 in compiler source at D:\a\1\s\src\stage1\codegen.cpp:1870: thread 29724 panic: assertion failed. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
The following command exited with error code 3:
C:\Users\InK\zig-lang\zig\zig.exe test C:\Users\InK\dev\zig\ecs\src\main.zig --cache-dir C:\Users\InK\dev\zig\ecs\zig-cache --global-cache-dir C:\Users\InK\AppData\Local\zig --name test
error: the following build command failed with exit code 1:
C:\Users\InK\dev\zig\ecs\zig-cache\o\a26a8226c0ea7c46b5f8259a81655c63\build.exe C:\Users\InK\zig-lang\zig\zig.exe C:\Users\InK\dev\zig\ecs C:\Users\InK\dev\zig\ecs\zig-cache C:\Users\InK\AppData\Local\zig test
```

**Comment by Vexu** [comment]
Not reproducible with `std.mem.span` changes, assuming fixed in master.
