### ISSUE TITLE
Symbols are not correctly exported from another imported file

### ISSUE THREAD

**Issue by Pilzschaf** [ziglang/zig#10174]
### Remember to search before filing a new report

- [X] I searched for this bug and did not find it in the issue tracker, and furthermore, the title I used above will make this new bug report turn up in the search results for my query.

### Zig Version

0.9.0-dev.1635+590880158

### Steps to Reproduce

I have a main.zig file and a other.zig file. Additionally I have a .c file which tries to call the function functionToExport(). It is defined in the other.zig file with pub export fn functionToExport() void {}. The main.zig file includes other.zig as follows: const other = @import("other.zig"); main.zig and the .c file are compiled into an executable.

### Expected Behavior

I expected that the program would link correctly as functionToExport is exported with pub export in other.zig. 

### Actual Behavior

What actually happens is I get a linking error: ld.lld: error: undefined symbol: functionToExport
 referenced by test.c:4 (src/test.c:4)
Copying the function definition from other.zig to main.zig results in successful linkage.
Another workaround that works is to define pub fn functionToExport() callconv(.C) void {} in other.zig and to export in main.zig with comptime {@export(other.functionToExport, .{.name = "functionToExport", .linkage=.Strong});}
Interestingly, if the function is still decorated with export in other.zig I get a duplicated symbol error: error: exported symbol collision: 'functionToExport'
comptime {@export(other.functionToExport, .{.name = "functionToExport", .linkage=.Strong});}
Which seems to suggest that the symbol is actually exported in some way but it can not be resolved in the .c file.
I would have expected that putting the export function into a different file would not have any effect on the exported symbols. Am I doing something wrong or is this an actual bug? If it helps I can also upload the code to reproduce into a repository.

**Comment by leecannon** [comment]
This is due to zig's lazy nature, doing `const other = @import("other.zig");` in main without referencing it means it is not included in the build, this is a fundamental part of how cross compilation is implemented.

The recommended way of referencing a seperate file in cases like this is:
```zig
const other = @import("other.zig");

comptime {
   _ = other;
}
```

**Comment by Pilzschaf** [comment]
Ok, makes sense. Thank you
