### ISSUE TITLE
Segfault adding two 128-bit floats on i386-linux-gnu

### ISSUE THREAD

**Issue by LewisGaul** [ziglang/zig#10199]
### Zig Version

0.9.0-dev.1717+29d5b8aac

### Steps to Reproduce

```zig
// Note: unable to confirm this as I don't have access to an i386 machine - trying to reproduce in QEMU...
test {
    const x: f128 = 1;
    _ = x + x;
}
```

This was seen in the CI for https://github.com/ziglang/zig/pull/10046 and https://github.com/ziglang/zig/pull/10149, where this presumably adds the first instance of test coverage for adding two 128-bit floats.

The line that hits this is https://github.com/ziglang/zig/pull/10046/files#diff-34c73d0935947f2ddbdee68a934144ae32c69f3cc538995826d6bb5c1ddf286aR760, which roughly simplifies down to:
```zig
fn exp2_128(x: f128) f128 {
    const tblsiz: u32 = @intCast(u32, exp2_128_table.len);
    const redux: f128 = 0x1.8p112 / @intToFloat(f128, tblsiz);
    var u_f: f128 = x + redux;
    ...
}
```

### Expected Behavior

Should successfully add 128-bit floats.

### Actual Behavior

As seen in https://ci.ziglang.org/ziglang/zig/332/1/4:
```
Test [697/2084] math.exp2.test "std-i386-linux-gnu-Debug-c-multi math.exp2() delegation"... Segmentation fault at address 0x0
???:?:?: 0x1521bc3 in ??? (???)
/workspace/lib/std/math/exp2.zig:760:23: 0x83c7cd in math.exp2.exp2_128 (test)
    var u_f: f128 = x + redux;
                      ^
```

**Comment by topolarity** [comment]
I believe this is resolved now thanks to https://github.com/ziglang/zig/pull/11532 :+1:

**Comment by matu3ba** [comment]
I can confirm that this works at least with qemu-user. Closing?

@topolarity You can quickly test this yourself with `qemu-user` [some related blogpost](https://ownyourbits.com/2018/06/13/transparently-running-binaries-from-any-architecture-in-linux-with-qemu-and-binfmt_misc/):
```sh
#install qemu-user, ie with sudo pacman -S qemu-user
zig test --test-no-exec -target i386-linux-gnu file.zig
qemu-i386 ./zig-cache/o/64048d34f37912560af100ae7504a955/test ~/dev/git/zig/zig/master/build/zig
```
output:
All 1 tests passed.
