### ISSUE TITLE
`zig fmt` takes exponential time to render nested arrays/tuples with trailing commas

### ISSUE THREAD

**Issue by chwayne** [ziglang/zig#10194]
### Zig Version

0.9.0-dev.1678+7747bf07c

### Steps to Reproduce

Run `zig fmt` on this sequence of inputs.

- `const x = .{.{},};`
- `const x = .{.{.{},},};`
- `const x = .{.{.{.{},},},};`

or

- `const x = T{T{},};`
- `const x = T{T{T{},},};`
- `const x = T{T{T{T{},},},};`
- `And so on...`

### Expected Behavior

Formatter goes fast

### Actual Behavior

Each iteration takes twice as long as the previous. It takes about 20 iterations to get to 1 second execution time. Deleting the commas fixes this problem.

**Comment by maxxnino** [comment]
mine pretty fast
https://user-images.githubusercontent.com/34153891/142751701-af76a3a5-15aa-4e23-b186-2b3288e4fa44.mp4

**Comment by maxxnino** [comment]
https://user-images.githubusercontent.com/34153891/142751701-af76a3a5-15aa-4e23-b186-2b3288e4fa44.mp4

mine pretty fast

**Comment by tauoverpi** [comment]
@maxxnino it depends on your machine but even on a decent one it ends up taking almost [20 minutes](https://github.com/ziglang/zig/files/7576332/fmt.txt) with enough nesting with comma.

**Comment by maxxnino** [comment]
@tauoverpi I took some of your example and it's really long 😕

**Comment by Ersikan** [comment]
I started working on it. Is there any way to profile the `zig fmt` command for now ? I tracked down the bug to the AST rendering code.

**Comment by andrewrk** [comment]
> I started working on it. Is there any way to profile the `zig fmt` command for now ? I tracked down the bug to the AST rendering code.

Check out https://ziglang.org/perf/

You can add a new benchmark to https://github.com/ziglang/gotta-go-fast/ which will add a graph and then you can watch the line go down with your fix (once it lands in master).

**Comment by Ersikan** [comment]
@andrewrk I meant how to measure the performance of each function in `zig fmt`, not how to measure the overall performance.

I know that the compiler is using Tracy. Would it be possible to use tracy in `zig fmt` ?
