### ISSUE TITLE
May need to pass to clang: -mmacosx-version-min, -miphoneos-version-min, etc

### ISSUE THREAD

**Issue by slimsag** [ziglang/zig#10231]
Once #10227 is fixed, we will have support for `@available` checks in Objective C code. However, upon researching the topic I found that clang leverages four CLI flags and env vars in order to determine the "minimum" OS version it should be targeting:

https://github.com/llvm/llvm-project/blob/6fa8f7beb1928dfad291314c8baf16374a1cc145/clang/lib/Driver/ToolChains/Darwin.cpp#L1696-L1699

https://github.com/llvm/llvm-project/blob/6fa8f7beb1928dfad291314c8baf16374a1cc145/clang/lib/Driver/ToolChains/Darwin.cpp#L2023-L2024

From `man clang`:

>       -mmacosx-version-min=<version>
>              When building for macOS, specify the minimum version supported by your application.
>
>       -miphoneos-version-min
>              When building for iPhone OS, specify the minimum version supported by your application.

I'm not sure what all side effects this has in clang, but allegedly at least one side effect is that:

If we do not specify these flags then clang will derive this information from the target arch and host OS (let's say macOS 12.0) and an Objective-C `@available` check for say macOS 10.15 _will be treated as a compile time conditional_, never emitting a call to `__isPlatformVersionAtLeast` to be executed at runtime ("because the target is macOS 12.0").

We could possibly hard-code such flags to the lowest-supported version by Zig (e.g. macOS 10 currently) if that is the only effect, but otherwise we should probably look at deriving these flags from the target triple (since it includes the macOS version now) cc @kubkon for thoughts

**Comment by andrewrk** [comment]
Already done based on the `-target` OS minimum version:

https://github.com/ziglang/zig/blob/b097545a5f2b01392c60014e1caded9dccc4b34d/src/Compilation.zig#L3405-L3428

Note that you can see what flags zig passes to clang with `--verbose-cc` or `ZIG_VERBOSE_CC=1` env var.
