### ISSUE TITLE
Best approach to type constraints

### ISSUE THREAD

**Issue by divinusdracodominus** [ziglang/zig#10250]
This is just a means of asking the best way to do something, in C++ a concept, or static assertion, in rust a constraint on a generic, I'm curious how zig handles type constraints, specifically, how do I articulate to the compiler that I want a generic to be some integer type (preferable extensible) 

I was thinking one potential method would be, though I'm not sure the syntax, to check if a function with a given name and given signature exist.

**Comment by andrewrk** [comment]
Hi @divinusdracodominus, welcome. Please take questions to one of the [community spaces.](https://github.com/ziglang/zig/wiki/Community)

This issue tracker is for actionable things such as bugs and enhancements.
