### ISSUE TITLE
Packed struct with bit fields has alignment issues

### ISSUE THREAD

**Issue by ayende** [ziglang/zig#10260]
### Zig Version

trunk

### Steps to Reproduce

Run the following code (see link here: https://godbolt.org/z/rer6eEYq7 )

```
std.log.debug("16 first  has size of {}", .{@sizeOf(packed struct {
    version: u16,
    references: u19,
    tag: enum(u2) {
        Empty = 0b00,
        Error = 0b01,
        Loading = 0b10,
        Value = 0b11,
    },
    value: u27
})});

std.log.debug("16 second has size of {}", .{@sizeOf(packed struct {
    references: u19,
    version: u16,
    tag: enum(u2) {
        Empty = 0b00,
        Error = 0b01,
        Loading = 0b10,
        Value = 0b11,
    },
    value: u27
})});
```

You'll see that for the first version, we are getting that the size is `10` bytes, but for the second, the size is `8` bytes, as expected. My guess is that there is probably some alignment issue going on here, but given `packed struct`, I would expect to see the same size in both cases

### Expected Behavior

Both structs should have the same size

### Actual Behavior

They are of different sizes

**Comment by N00byEdge** [comment]
This is just #2627
