### ISSUE TITLE
Proposal: language restrictions per project

### ISSUE THREAD

**Issue by PavelVozenilek** [ziglang/zig#1027]
Some language features may became undesirable, for whatever reason.  In C++ many projects turn off exceptions and RTTI. As Zig is becoming large, it may anticipate and accommodate this behavior.

My proposal: allow projects to specify features which are _not_ permitted in the project. Build system is probably the right place to specify such restrictions.

Non-exhaustive list of features some may want to be disabled:
1. Invocation of C code, using C sources in the project. (With possible exception of stdlib.) This may be for security reasons.
2. Full Unicode in source code. (Strings and comments being possible exceptions.) Security reasons, readability. Unicode has some guideline for identifiers, but it probably only makes complex situation even more complicated.
3. Compile time execution. Some projects may not like it for security reasons. It could be more fine grained, like no access to C code, I/O, sockets, OS API.
4. Errors.  Some may prefer everything being completely explicit.
5. Assembler. Security, code understandability.

If project finds a forbidden language feature, it would not compile. Libraries (including stdlib) which use forbidden feature won't be allowed in project. (Projects do write their own variants of standard libraries to fit their specific requirements, like EaSTL). 

If some code wants to be universal, to handle even such situations, it may use "does-it-compile-if", which would check if something fails due to a restriction, and ignore that part.

Possible syntax:

```
if? {
   ... // use this code if it compiles
} else {
  ...  // use this when the if branch doesn't compile due to some restriction
}
```

I personally would also like to be able to disable unorthodox language constructs, as:
* loop continuation expression
* control flow for blocks
* non-nullable whatever (I think it is no-problem, and disabling it would make cleaner code.)

**Comment by andrewrk** [comment]
> As Zig is becoming large...

Zig is not large and will not become large. 

One of the ways we will avoid becoming large is by not having a way to opt out of part of the language and also not having does-it-compile-if.

**Comment by 0joshuaolson1** [comment]
> Compile time execution. Some projects may not like it for security reasons. It could be more fine grained, like no access to C code, I/O, sockets, OS API.

Compile time code can't do all that, don't worry.
