### ISSUE TITLE
wasm miscompilation, possibly related to build modes

### ISSUE THREAD

**Issue by Apppppppple** [ziglang/zig#10286]
### Zig Version

0.9.0-dev.1635+590880158

### Steps to Reproduce

Using this source code:
```zig
const std = @import("std");
const w4 = struct {
    pub const PALETTE: *[4]u32 = @intToPtr(*[4]u32, 0x04);
    pub const DRAW_COLORS: *u16 = @intToPtr(*u16, 0x14);
    pub extern fn rect(x: i32, y: i32, width: u32, height: u32) void;
    pub extern fn trace(x: [*:0]const u8) void;
};
const mw4 = struct {
    pub fn rect(color: u16, x: i32, y: i32, width: u32, height: u32) void {
        w4.DRAW_COLORS.* = color;
        w4.rect(x, y, width, height);
    }
};

pub fn log(
    comptime message_level: std.log.Level,
    comptime scope: @Type(.EnumLiteral),
    comptime format: []const u8,
    args: anytype,
) void {
    const level_txt = comptime message_level.asText();
    const prefix2 = if (scope == .default) ": " else "(" ++ @tagName(scope) ++ "): ";
    var buf: [256]u8 = undefined;
    const text = std.fmt.bufPrint(&buf, level_txt ++ prefix2 ++ format ++ [_]u8{0}, args) catch return;
    w4.trace(@ptrCast([*:0]const u8, text.ptr));
}
var frame_count: u32 = 0;

export fn update() void {
    frame_count += 1;
    const blank_color: u32 = 0x39425c;

    if (frame_count % 2 == 0) {
        w4.PALETTE.* = .{ 0x39425c, fixColor(0x3c4c63, blank_color), fixColor(0x3f5b69, blank_color), fixColor(0x417070, blank_color) };
        mw4.rect(0x01, 0, 160 - (1 * 23), 160, 23);
        mw4.rect(0x02, 0, 160 - (2 * 23), 160, 23);
        mw4.rect(0x03, 0, 160 - (3 * 23), 160, 23);
        mw4.rect(0x04, 0, 160 - (4 * 23), 160, 23);
        std.log.info("hi2", .{});
    } else {
        std.log.info("hi", .{});
        w4.PALETTE.* = .{ blank_color, fixColor(0x3a875e, blank_color), fixColor(0x469c58, blank_color), fixColor(0xff0000, blank_color) };
        mw4.rect(0x02, 0, 160 - (5 * 23), 160, 23);
        mw4.rect(0x03, 0, 160 - (6 * 23), 160, 23);
        mw4.rect(0x04, 0, 0, 160, 22);
    }
}

fn fixColor(original: u32, blank_color: u32) u32 {
    const r1 = original >> 16;
    const r2 = blank_color >> 16;
    const g1 = (original >> 8) - (r1 << 8);
    const g2 = (blank_color >> 8) - (r2 << 8);
    const b1 = original - (r1 << 16) - (g1 << 8);
    const b2 = blank_color - (r2 << 16) - (g2 << 8);
    const fixed_r = std.math.min((2 * r1) - r2, 0xff);
    const fixed_g = std.math.min((2 * g1) - g2, 0xff);
    const fixed_b = std.math.min((2 * b1) - b2, 0xff);
    return (fixed_r << 16) + (fixed_g << 8) + (fixed_b << 0);
}

```
and this build.zig:
```zig
const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    const mode = b.standardReleaseOptions();

    const lib = b.addSharedLibrary("cart", "main.zig", .unversioned);
    lib.setBuildMode(mode);
    lib.setTarget(.{ .cpu_arch = .wasm32, .os_tag = .freestanding });
    lib.import_memory = true;
    lib.initial_memory = 65536;
    lib.max_memory = 65536;
    lib.global_base = 6560;
    lib.stack_size = 8192;
    lib.install();
}
```
Run with `w4 run zig-out/lib/cart.wasm` (from [wasm4.org](https://wasm4.org)) a version from `zig build` and a version from `zig build -Drelease-small`

### Expected Behavior

The behavior should be the same regardless of the compilation mode.

### Actual Behavior

With `zig build`, the log messages work but the rendering is incorrect. With `zig build -Drelease-safe`, the rendering is correct, but nothing is logged. Through inspecting the output from wasm2wat, it seems like the calls to `std.log.info` just do not exist in the release-safe version, but I'm not that experienced with wat.

**Comment by Luukdegram** [comment]
I believe this is intentional, rather than a miscompilation.
The default log level of `release-safe` is `.err` as can be found here:
https://github.com/ziglang/zig/blob/master/lib/std/log.zig#L104-L108

Note that it will still call std's log function (which checks for level) and then either uses the default log function, or the overwritten version as defined here: https://github.com/ziglang/zig/blob/master/lib/std/log.zig#L140-L148

There are two options you could apply:
1. Change the logging level by declaring it in the root scope of your project using `pub const level = .info;`
2. Use higher-order logging methods (such as `std.log.err`). However, this probably conveys the wrong information to the caller.

**Comment by Apppppppple** [comment]
My apologies, the logging inconsistencies were due to me misreading std.log's default_level, and the graphical errors were due to the runtime I was using silencing panics (`(2 * g1) - g2` overflowed, causing a panic, which aborted the function but was otherwise invisible).
