### ISSUE TITLE
have zig fmt notice a special comment that tells it to skip a source file

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1030]
Currently zig has 3 files that we want to always skip formatting:

* std/special/compiler_rt/udivmodti4_test.zig
  - it's 1.8MiB so we want to only update the syntax when necessary
* std/special/compiler_rt/udivmoddi4_test.zig
  - it's 9.8MiB so we want to only update the syntax when necessary
* test/cases/syntax.zig
  - it's testing parsing edge cases, so running zig fmt would defeat the purpose of the tests

Here's my idea:

```zig
// zig fmt: skip

... normal code ...

```

If the first token in the file is a line comment that has the contents `zig fmt: skip` then zig fmt skips the file.

**Comment by monouser7dig** [comment]
// clang-format off
Some code 
// clang-format on

Works well for cpp, maybe this would be a good fit for zig fmt as well.

Just 
// zig-format off
Would disable it for the whole file 

Only downside I can think of is that people use it more frequently and code does not get formatted uniquely everywhere.

**Comment by bronze1man** [comment]
`go fmt` in the golang can create some git merge conflicts. 
So I do not use it any more.

Our team have an rule about format code with ide or tool:
Only format the code your just write,  do not format the old code. Do not format all the code in the project.

**Comment by monouser7dig** [comment]
> What about the git merge conflicts problem?

https://git-scm.com/docs/merge-strategies

and https://github.com/ziglang/zig/issues/1037#issuecomment-394113649

> Do not format the old code.

formatting is idempotent, applying formatting to old code over and over does thus not change anything

> Do not format all the code in the project.

for special cases there will be https://github.com/ziglang/zig/issues/1030#issuecomment-393336029 `zig-fmt off`

**Comment by bronze1man** [comment]
It is strange that golang format actually increase the number of git conflicts in the long term in my experience.

If you add a field into a golang struct in one place, and `go fmt` it. All the line of that struct changed. So it will conflicts when another guy add a field into this struct in another place.
If you do not use the `go fmt` in that case. The code looks ugly, but it only add 1 line.Other line of struct do not change. So it will not conflicts in above example.

**Comment by andrewrk** [comment]
> It is strange that go fmt actually increase the number of git conflicts in the long term in my experience.

One reason for this is that `go fmt` aligns everything. Meanwhile `zig fmt` does not align everything, so it is more diff friendly.
