### ISSUE TITLE
comptime computation breaks @divFloor

### ISSUE THREAD

**Issue by matu3ba** [ziglang/zig#10313]
### Zig Version

0.9.0-dev.1945+efdb94486

### Steps to Reproduce

```zig
test {
    const std = @import("std");
    const math = std.math;
    const print = @import("std").debug.print;
    const min_usable = math.minInt(i32) + 1;
    const max_usable = math.maxInt(i32);
    print("\n", .{});
    print("min_usable: {d}, {x}\n", .{ min_usable, min_usable });
    print("max_usable: {d}, {x}\n", .{ max_usable, max_usable });
    const min_use_half = @divFloor(min_usable, 2);
    const max_use_half = @divFloor(max_usable, 2);
    print("min_half_usable: {d}, {x}\n", .{ min_use_half, min_use_half });
    print("max_half_usable: {d}, {x}\n", .{ max_use_half, max_use_half });
}
```

### Expected Behavior

zig test issue_comptime_divFloor.zig
should return
Test [0/1] test ""...                                                                                     
min_usable: -2147483647, -7fffffff                                                                        
max_usable: 2147483647, 7fffffff                                                                          
min_half_usable: -1073741823, -40000000                                                                   
max_half_usable: 1073741823, 3fffffff                                                                     
                                                                                                          
All 1 tests passed.

Since **2147483647/2 = 1073741823.5**. However for somo weird reason it rounds up as `+1;` would have no effect for this specific operation.

### Actual Behavior

zig test issue_comptime_divFloor.zig
returns
Test [0/1] test ""...                                                                                     
min_usable: -2147483647, -7fffffff                                                                        
max_usable: 2147483647, 7fffffff                                                                          
min_half_usable: -1073741824, -40000000                                                                   
max_half_usable: 1073741823, 3fffffff                                                                     
                                                                                                          
All 1 tests passed.

### Comparison to not using maxInt

If one inserts
```zig
    const min_usable = -2147483647;
    const max_usable = 2147483647;
```
the result is for both as expected -1073741823 and 1073741823.

**Comment by LemonBoy** [comment]
> 2147483647/2 = 1073741823.5

Flooring rounds towards minus infinity therefore `@divFloor(2147483647, 2) = floor(2147483647 / 2) = floor(-1073741823.5) = -1073741824`.

**Comment by matu3ba** [comment]
My bad.
