### ISSUE TITLE
`std.fs.Dir.walk` only works once

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#10317]
### Zig Version

0.9.0-dev.1815+20e19e75f

### Steps to Reproduce

```
$ zig init-exe
```

place the following contents in `src/main.zig`

```zig
const std = @import("std");

test {
    const allocator = std.testing.allocator;
    var dir = try std.fs.cwd().openDir("src", .{ .iterate = true });
    defer dir.close();
    const expected = try dirEntryCount(allocator, dir);
    const actual = try dirEntryCount(allocator, dir);
    try std.testing.expectEqual(expected, actual);
}

fn dirEntryCount(allocator: *std.mem.Allocator, dir: std.fs.Dir) !usize {
    var count: usize = 0;
    var walker = try dir.walk(allocator);
    defer walker.deinit();
    while (try walker.next()) |_| {
        count += 1;
    }
    return count;
}
```

```
$ zig build
```

### Expected Behavior

```
All 1 tests passed.
```

### Actual Behavior

```
Test [1/1] test ""... expected 1, found 0
Test [2/1] test ""... FAIL (TestExpectedEqual)
/home/snuc/.local/share/zig/lib/std/testing.zig:79:17: 0x20c645 in std.testing.expectEqual (test)
                return error.TestExpectedEqual;
                ^
/home/snuc/dev/aquila/test.zig:9:5: 0x20b97a in test "" (test)
    try std.testing.expectEqual(expected, actual);
    ^
0 passed; 0 skipped; 1 failed.
```

**Comment by squeek502** [comment]
Can also reproduce this with the std lib `fs` tests with the following diff:

```diff
diff --git a/lib/std/fs/test.zig b/lib/std/fs/test.zig
index 3d1b0d779..8185cca38 100644
--- a/lib/std/fs/test.zig
+++ b/lib/std/fs/test.zig
@@ -933,22 +933,25 @@ test "walker" {
         try tmp.dir.makePath(kv.key);
     }
 
-    var walker = try tmp.dir.walk(testing.allocator);
-    defer walker.deinit();
-
-    var num_walked: usize = 0;
-    while (try walker.next()) |entry| {
-        testing.expect(expected_basenames.has(entry.basename)) catch |err| {
-            std.debug.print("found unexpected basename: {s}\n", .{std.fmt.fmtSliceEscapeLower(entry.basename)});
-            return err;
-        };
-        testing.expect(expected_paths.has(entry.path)) catch |err| {
-            std.debug.print("found unexpected path: {s}\n", .{std.fmt.fmtSliceEscapeLower(entry.path)});
-            return err;
-        };
-        num_walked += 1;
+    var i: usize = 0;
+    while (i < 2) : (i += 1) {
+        var walker = try tmp.dir.walk(testing.allocator);
+        defer walker.deinit();
+
+        var num_walked: usize = 0;
+        while (try walker.next()) |entry| {
+            testing.expect(expected_basenames.has(entry.basename)) catch |err| {
+                std.debug.print("found unexpected basename: {s}\n", .{std.fmt.fmtSliceEscapeLower(entry.basename)});
+                return err;
+            };
+            testing.expect(expected_paths.has(entry.path)) catch |err| {
+                std.debug.print("found unexpected path: {s}\n", .{std.fmt.fmtSliceEscapeLower(entry.path)});
+                return err;
+            };
+            num_walked += 1;
+        }
+        try testing.expectEqual(expected_paths.kvs.len, num_walked);
     }
-    try testing.expectEqual(expected_paths.kvs.len, num_walked);
 }
 
 test ". and .. in fs.Dir functions" {
```

**Comment by squeek502** [comment]
This is reproducible with just `getdents`:

```zig
const std = @import("std");

pub fn main() !void {
    var dir = try std.fs.cwd().openDir(".", .{ .iterate = true });
    defer dir.close();

    var buf: [8192]u8 align(@alignOf(std.os.linux.dirent64)) = undefined;

    var i: usize = 1;
    while (i <= 2) : (i += 1) {
        const rc = std.os.linux.getdents64(dir.fd, &buf, buf.len);
        std.debug.print("i: {} status: {} rc: {}\n", .{ i, std.os.linux.getErrno(rc), rc });
    }
}
```

```
i: 1 status: E.SUCCESS rc: 1136
i: 2 status: E.SUCCESS rc: 0
```

One solution is to call `lseek(dir.fd, 0, SEEK_SET)`, which is what `rewinddir` does for the `readdir` class of functions ([here's the musl rewinddir implementation](https://github.com/ziglang/zig/blob/master/lib/libc/musl/src/dirent/rewinddir.c)):

Adding:
```zig
try std.os.lseek_SET(dir.fd, 0);
```

to the top of the loop fixes it and gives:

```
i: 1 status: E.SUCCESS rc: 1136
i: 2 status: E.SUCCESS rc: 1136
```

**Comment by ominitay** [comment]
Isn't this an issue with `Dir.Iterator`, not `Dir.Walker`?

**Comment by ominitay** [comment]
> Isn't this an issue with `Dir.Iterator`, not `Dir.Walker`?

Just added a test, and that is indeed the case. Will look at implementing a `dir.Iterator.deinit` function to rewind.

**Comment by ominitay** [comment]
Since `seekTo` can fail and return an error, I don't think it'd make sense to return an error. Perhaps it would make sense to do `seekTo(0)` when initializing the `Iterator`.

**Comment by squeek502** [comment]
> Since `seekTo` can fail and return an error, I don't think it'd make sense to return an error. Perhaps it would make sense to do `seekTo(0)` when initializing the `Iterator`. But then that isn't necessary to do every single time, as it can often be assumed that we are at the beginning. Perhaps the best solution could be just to add `seekTo` to `fs.Dir`, and add to the docs that `fs.Dir.seekTo(0)` should be called before iterating twice...

Yeah, I've had the same thoughts, and haven't come to any conclusion about what I think would be best. Adding a `fs.Dir.seekTo` would be similar to how the POSIX API works (`readdir`, `rewinddir`).

It's also not clear if/how this affects non-Linux platforms.

**Comment by ominitay** [comment]
> Yeah, I've had the same thoughts, and haven't come to any conclusion about what I think would be best. Adding a fs.Dir.seekTo would be similar to how the POSIX API works (readdir, rewinddir).

I did this on my local repo, and it makes sense to me to add this regardless of how we address this.

> It's also not clear if/how this affects non-Linux platforms.

I'll make a PR to add a test so that we can determine this.

**Comment by squeek502** [comment]
I can't think of how this would work in terms of an implementation, but if we can somehow know that the `Dir` has been successfully iterated, then I think it's safe to do an `os.lseek_SET` with `catch unreachable`, as all the possible errors should be impossible:

- https://man7.org/linux/man-pages/man2/lseek.2.html#ERRORS
- WASI adds a possible `AccessDenied` but that should also be impossible if we know that the `Dir` was successfully iterated (could be wrong though)

**Comment by ominitay** [comment]
CI on the PR decided to not work with Windows again. I'll try testing it under wine on my system... Seems that all platforms are affected though.

**Comment by ominitay** [comment]
> I can't think of how this would work in terms of the possible implementations, but if we can somehow know that the `Dir` has been successfully iterated, then I think it's safe to do an `os.lseek_SET` with `catch unreachable`, as all the possible errors should be impossible:

The only point at which the iterator knows it has reached the end is when `getdents` returns zero. The issue is that we can't rewind at that point, or else calling next twice will bring us back to the start of the iterator...

**Comment by ominitay** [comment]
I feel that this should either be a feature, not a bug, or the directory should be rewound when the `Iterator` is initialized.

**Comment by ominitay** [comment]
> I can't think of how this would work in terms of the possible implementations, but if we can somehow know that the `Dir` has been successfully iterated, then I think it's safe to do an `os.lseek_SET` with `catch unreachable`, as all the possible errors should be impossible:

Yep, that seems reasonable.

>     * WASI adds a possible `AccessDenied` but that should also be impossible if we know that the `Dir` was successfully iterated (could be wrong though)

The directory couldn't be opened for iteration if that was the case, so we should error out before reaching that.

> EDIT: Another fairly gross possibility would be to unconditionally do a `lseek_SET` at the start of `fs.Dir.iterate` and just ignore any errors that may happen from it, as any 'real' errors would subsequently get triggered once the `Iterator` is attempted to be used.

I think we should do this -- there shouldn't be any possible errors here.

**Comment by squeek502** [comment]
No changes are necessary on Windows by the way:

```
C:\Users\Ryan\Programming\Zig\zig>zig test lib/std/fs/test.zig --zig-lib-dir lib --main-pkg-path lib/std --test-filter "Iterator twice"
Test [0/1] test "Dir.Iterator twice"... 1/1 test "Dir.Iterator twice"... OK
All 1 tests passed.
```

**Comment by ominitay** [comment]
Fantastic, that's one less thing to worry about!

**Comment by squeek502** [comment]
Adding the following to the top of `fs.Dir.iterate` fixes the normal test case:

```zig
        switch (builtin.os.tag) {
            .windows => {},
            else => {
                std.os.lseek_SET(self.fd, 0) catch {};
            },
        }
```

but the following test:

```zig
test "Dir.Iterator on non-iterable" {
    var tmp_dir = tmpDir(.{});
    defer tmp_dir.cleanup();

    var iter = tmp_dir.dir.iterate();
    while (try iter.next()) |_| {}
}
```

fails when `unreachable` is hit within `lseek_SET`:

```
Test [7/38] test "Dir.Iterator on non-iterables"... thread 1573069 panic: reached unreachable code
/home/ryan/Programming/zig/zig/lib/std/os.zig:4342:18: 0x230557 in std.os.lseek_SET (test)
        .BADF => unreachable, // always a race condition
                 ^
/home/ryan/Programming/zig/zig/lib/std/fs.zig:765:33: 0x2223d5 in std.fs.Dir.iterate (test)
                std.os.lseek_SET(self.fd, 0) catch {};
                                ^
/home/ryan/Programming/zig/zig/lib/std/fs/test.zig:224:35: 0x21825c in test "Dir.Iterator on non-iterables" (test)
    var iter = tmp_dir.dir.iterate();
                                  ^
```

Note, though, that without the `lseek_SET` call in `iterate`, it still hits unreachable (with a more relevant comment next to the unreachable):

```
Test [6/37] test "Dir.Iterator on non-iterable"... thread 1573410 panic: reached unreachable code
/home/ryan/Programming/zig/zig/lib/std/fs.zig:580:38: 0x221da4 in std.fs.Iterator.next (test)
                            .BADF => unreachable, // Dir is invalid or was opened without iteration ability
                                     ^
/home/ryan/Programming/zig/zig/lib/std/fs/test.zig:221:25: 0x217c54 in test "Dir.Iterator on non-iterable" (test)
    while (try iter.next()) |_| {}
                        ^
```

Not really sure what should be done about this (not sure how I feel about `BADF => unreachable` in general as well). Maybe a separate `seekTo` function + documentation about needing to call it before iterating twice might be the better/cleaner way to go?

**Comment by ominitay** [comment]
I think the big issue here is that calling it twice behaves differently on different platforms, which we can't allow.

**Comment by ominitay** [comment]
I have tried an approach with the Linux iterator, which seems to have worked. It adds a `bool`, called `first`, to the struct, and when doing `getdents64`, if `first` is true, it attempts to rewind the directory. Also makes sense to use `catch unreachable` here, since we know that this can't fail. The Windows iterator does a similar thing to this, storing `first`, with the Windows API providing an option to rewind. I'll implement this for other platforms and open a PR soon.
