### ISSUE TITLE
Allocgate missing runtime-known alignment functions

### ISSUE THREAD

**Issue by silversquirl** [ziglang/zig#10348]
To quote @andrewrk on #10112:

> [...] I agree that this use case will need to continue to be supported - runtime-known alignment.

However, the new allocator interface does not feature any high-level functions to support this. Ideally there would be a `reallocAdvancedWithRetAddrRuntimeAlignment` (though that name is rather unwieldy).

**Comment by andrewrk** [comment]
Hmm, looks like #9394 regressed with those changes.
