### ISSUE TITLE
resolve_llvm_types_struct when using an aligned field in a struct

### ISSUE THREAD

**Issue by bpeake13** [ziglang/zig#10369]
### Zig Version

0.9.0-dev.2010+e8b39960b

### Steps to Reproduce

Create a packed struct that has an aligned field like so:

`
const MyStruct = packed struct {
  v: u64 align(8),
};
`

Then from another package include that struct and use it, you will see a compiler crash.

### Expected Behavior

Compiler should not crash

### Actual Behavior

Compiler crashes

**Comment by Vexu** [comment]
`error: unable to override alignment of packed struct fields`
