### ISSUE TITLE
Dir.statFile panics when given a file that doesn't exist.

### ISSUE THREAD

**Issue by fubark** [ziglang/zig#10375]
### Zig Version

0.9.0

### Steps to Reproduce

Dir.statFile on file that doesn't exist. This is happening with the zig-linux-x86_64-0.9.0.tar.xz from the zig download page.

### Expected Behavior

Return an error.

### Actual Behavior

Panics.
/home/fubar/Downloads/zig-linux-x86_64-0.9.0/lib/std/os.zig:3709:18: 0x528aed in std.os.fstat (main)
        .BADF => unreachable, // Always a race condition.
                 ^
/home/fubar/Downloads/zig-linux-x86_64-0.9.0/lib/std/fs/file.zig:323:32: 0x51c6ba in std.fs.file.File.stat (main)
        const st = try os.fstat(self.handle);
                               ^
/home/fubar/Downloads/zig-linux-x86_64-0.9.0/lib/std/fs.zig:2180:25: 0x53369f in std.fs.Dir.statFile (main)
        return file.stat();

**Comment by fubark** [comment]
I noticed this issue is on master too and also faccessat syscall would return -1 but fetching with errno_location would return 0.

I traced it back to how I'm adding shared libraries in build.zig. Previously I had done builder.addSharedLibrary("stbi", "stbi.zig", .unversioned) with linkLibC where stbi.zig cImported headers. That worked. But now, the linker seems to tangle up the libc_nonshared.a in stbi.o and the one in main.o (also linking libc).

The solution I found was doing builder.addSharedLibrary("stbi", null, .unversioned) where there is no reference to a zig file. Not sure why it works. stbi.o and main.o are both still linking with libc_nonshared.a and all the syscalls are working again.

**Comment by andrewrk** [comment]
Cannot reproduce:

```zig
const std = @import("std");

test "example" {
    _ = try std.fs.cwd().statFile("aoeuaoeuoeu");
}
```

```
$ ./zig test test.zig 
Test [1/1] test "example"... FAIL (FileNotFound)
/home/andy/Downloads/zig/lib/std/os.zig:1472:23: 0x22826d in std.os.openatZ (test)
            .NOENT => return error.FileNotFound,
                      ^
/home/andy/Downloads/zig/lib/std/fs.zig:1000:13: 0x20ac3b in std.fs.Dir.openFileZ (test)
            try os.openatZ(self.fd, sub_path, os_flags, 0);
            ^
/home/andy/Downloads/zig/lib/std/fs.zig:933:9: 0x208f21 in std.fs.Dir.openFile (test)
        return self.openFileZ(&path_c, flags);
        ^
/home/andy/Downloads/zig/lib/std/fs.zig:2177:20: 0x207fc8 in std.fs.Dir.statFile (test)
        var file = try self.openFile(sub_path, .{});
                   ^
/home/andy/Downloads/zig/build-release/test.zig:4:9: 0x207a0e in test "example" (test)
    _ = try std.fs.cwd().statFile("aoeuaoeuoeu");
        ^
0 passed; 0 skipped; 1 failed.
error: the following test command failed with exit code 1:
zig-cache/o/501a954e898843c5a83959430a1ecb6a/test /home/andy/Downloads/zig/build-release/zig
```

Please provide example code to reproduce the issue and I'll re-open it.
