### ISSUE TITLE
Does zig have a build system to generate code before compile?

### ISSUE THREAD

**Issue by bronze1man** [ziglang/zig#1038]
Use case2-4 come from my big golang project. It is not open source.It may or may not work in zig.

## Use case1:
* I want to import a directory but I do not want to edit two files manually so that I can add 10 files easily into that directory. I want to get all my zig files in one a directory in one level and generate a `index.zig` file to include them all.
* I have `write.zig`, `read.zig`, `stat.zig` in the directory of `kmgFile`, I want to write a program that can generate a `index.zig` file look like this:
```
pub use @import("write.zig");
pub use @import("read.zig");
pub use @import("stat.zig");
```
* I can build and run the first program and then build and run my second program that import my directory with the generated `index.zig`. 
* I will call that first program as the `build function` in the follow message.
* This use case looks easy. But I have 33 `build functions` in my current work big project.

## Use case2:
* I want to make my function can be called from another process form the network. It is called rpc. There is a lot runtime reflect rpc framework. But I want my rpc have compiler type checked and name checked.
* I read my source code from ast to get the function input parameters and output parameters, and 
 generated the rpc client and the server source code. So I need a build function to write the output source code. I will import the output source code from another part of my project.
* This use case may be solved by compile-time feature of zig.

## Use case3:
* I want to cache a global configure of my server ip in my client program in the source code. 
* Reading a config file in the client program just make thing complex. I need to install more than one file into the client device. I need to cache the configure of my server ip duration the build process(it is already a `build function`). I need to manage the os filesystem path stuff in the client device.It is complex to do this stuff during serval planform. For example , planform ios,android,mac,windows need different code path to solve this path stuff.This complex is too big for a small configure infomation, so i decided to embed them in the source code.
* I need to write a `build function` to get the global configure from network before my big project compile. But the `get the global configure from network` use the rpc function from use case2. Before compile this  `build function`, I need the use case2 `build function` finish.

## Use case4:
* I want to reuse my `build functions` of my packages in two projects.
* I write a program that can search all the `build functions` in my project and put them all into one program. The program can automatic find all the `build functions`, so that I do not need to find the `build functions` myself. And this make the add and delete and rename package easily.

## I do not use the CMake tool.
  * It is not automatic about use case4. 
  * It is difficult to write the program correct. A missing space in one `if` statement can make me crazy.

I already have a full design and implement of this build system in golang. Is there similar one in zig?

**Comment by tiehuis** [comment]
The build system in zig is implemented in zig. This means you can write an arbitrary zig program to do things during the build-step so all of the above should be prefectly fine. The zig parser/ast is exposed as well in the stdlib so you can do more in-depth things if needed and operate on it directly (no guarantees just yet on stability here, though).

An example would be the main build script for the compiler: https://github.com/ziglang/zig/blob/master/build.zig. This generates documentation and checks paths and all that and gives an idea of how you would use it. If can extract common build functions here for step 4 as in a normal program and even provide unit tests for them if needed.
