### ISSUE TITLE
cInclude should search local path

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#1040]
Currently cInclude doesn't search local path and only searches system headers.

**Comment by andrewrk** [comment]
when you say local path, do you mean the same directory as the file that contains `@cImport`? or the directory of the root source file of the package? Or do you mean the current working directory?

you can use `-isystem` args:
`  -isystem [dir]               add additional search path for other .h files`

the zig build system has `artifact.addIncludeDir("path/to/dir");` which is relative to your `build.zig` file.

**Comment by GuiltyMasterpiece** [comment]
I mean the same directory as the file that contains @cImport

**Comment by tiehuis** [comment]
`#include <...h>` checks only the system path, `#include "..h"` first checks if a file exists locally, else checks the system path.

It shouldn't need to copy the header files at all. The output header is only generated when exporting a c library/object. The only thing to consider here is whether there would ever realistically be conflicts in normal zig code. This seems unlikely, and as long as this was documented reasonably it may be fine.

That being said, how common is it to need to import a local c file from zig where the `-isystem` flag is not good enough? For small embedded single-file c libraries?
