### ISSUE TITLE
Name `u32_2` wrongly collides with zig primitives

### ISSUE THREAD

**Issue by Ryp** [ziglang/zig#10421]
### Zig Version

0.9.0

### Steps to Reproduce

Clone `https://github.com/Ryp/raytracer-zig` and revert [commit](https://github.com/Ryp/raytracer-zig/commit/63099de776ee26d65ad4e29ea47092b44492e904) `63099de`
Then compile using `zig build`

### Expected Behavior

Compile without errors, `u32_2` is a user-defined type. This error started appearing as I upgraded from `0.8.0`, related to #6062.  AFAIK `u32_2` is not an existing primitive name, and should compile without issues.

### Actual Behavior

```bash
src/raytracer.zig|21 col 11| error: name shadows primitive 'u32_2'
src/raytracer.zig|21 col 11| note: consider using @"u32_2" to disambiguate
```

**Comment by Aransentin** [comment]
Underscores are visual separators in Zig numbers, for things like `const one_billion = 1_000_000_000;`.
`u32_2` would then presumably mean `u322`, which is a valid primitive.

**Comment by InKryption** [comment]
@Aransentin Interesting. I know that it's documented for integer literals, but it's never explicitly stated to apply to the bit number in integer types. Maybe this deserves a mention in the documentation under either [Integers](https://ziglang.org/documentation/master/#Integers) or [Primitive Types](https://ziglang.org/documentation/master/#Primitive-Types).

**Comment by andrewrk** [comment]
This is an oversight; a result of using parseInt for primitives and not realizing it would make it support underscores. Zig should reject underscores in integer type primitives.
