### ISSUE TITLE
readIntNative codegen is suboptimal when alignment is known

### ISSUE THREAD

**Issue by pithlessly** [ziglang/zig#10435]
### Zig Version

0.9.0

### Steps to Reproduce

Compile the following code ([Godbolt link](https://zig.godbolt.org/z/h74Yzd13P)) for an architecture where LLVM tries to avoid unaligned access, such as thumb or wasm32:

```zig
const std = @import("std");

export fn read_pa(x: *align(8) u64)   u64 { return x.*; }
export fn read_pu(x: *align(1) u64)   u64 { return x.*; }
export fn read_ca(x: *align(8) [8]u8) u64 { return @bitCast(u64, x.*); }
export fn read_cu(x: *align(1) [8]u8) u64 { return @bitCast(u64, x.*); }
export fn read_sa(x: *align(8) [8]u8) u64 { return std.mem.readIntNative(u64, x); }
export fn read_su(x: *align(1) [8]u8) u64 { return std.mem.readIntNative(u64, x); }
```

### Expected Behavior

The generated code for functions `read_pa`, `read_ca`, and `read_sa` all use code paths that assume the relevant data is aligned to 8 bytes. On thumb, this corresponds to the `ldrd` instruction; on wasm32, it corresponds to an unannotated `i64.load 0`.

The generated code for functions `read_pu`, `read_cu`, and `read_su` use different, potentially slower paths that work for arbitrarily aligned addresses (a pair of `ldr` instructions on thumb, and `i64.load 0:p2align=0` on wasm32).

### Actual Behavior

Only `read_pa` uses the fast code path, and every other function uses the slower version.

**Comment by cbilz** [comment]
This appears to be fixed: https://zig.godbolt.org/z/4P3vdE8a7
