### ISSUE TITLE
Unused parameter and unknown identifier errors are generated even for functions that are never called

### ISSUE THREAD

**Issue by wolfwood** [ziglang/zig#10447]
### Zig Version

0.9.0

### Steps to Reproduce

```zig
fn foo(i: u32) void {}

pub fn main() !void {}
```

```
 $ zig build-exe test.zig
test.zig:1:8: error: unused function parameter
fn foo(i: u32) void {}
       ^
```

```zig
fn foo(i: u32) void {
    gerber();
}

pub fn main() !void {}
```

```
 $ zig build-exe test.zig
test.zig:2:5: error: use of undeclared identifier 'gerber'
    gerber();
    ^
```

```zig
fn foo(i: u32) void {
    1 / 2;
}

pub fn main() !void {}
```

*no discarded value error*

### Expected Behavior

I expected the first two cases to compile successfully, as they did in Zig `0.8.1`, because my understanding was that uncalled functions are largely ignored (I understand that some syntax errors, such as missing semicolons cannot be tolerated in this way because they interfere with even deciding where the function ends) and as the 3rd case does, which contains an `expression value is ignored` error but the function is not checked as it is uncalled.

I know there were breaking changes around unused parameters in `0.9.0`, and perhaps even uncalled functions must be checked (though this is not obvious to me), but the second case seems to definitely be a regression from `0.8.1` behavior.

### Actual Behavior

compilation fails with errors:

`error: unused function parameter`

`error: use of undeclared identifier`

**Comment by Jarred-Sumner** [comment]
fwiw, this helped me find unused code that was safe to delete

**Comment by andrewrk** [comment]
this is working as designed
