### ISSUE TITLE
`zig fmt .` turns documented struct into crippled mess

### ISSUE THREAD

**Issue by r00ster91** [ziglang/zig#10443]
### Zig Version

0.10.0-dev.91+be5130ec5

### Steps to Reproduce

```zig
pub const Pos = struct {
    /// X-axis.
    x: u32,
    /// Y-axis.
    y: u32
};
```
```
zig fmt .
```

### Expected Behavior

```zig
pub const Pos = struct {
    /// X-axis.
    x: u32,
    /// Y-axis.
    y: u32
};
```

### Actual Behavior

```zig
pub const Pos = struct { /// X-axis.
x: u32, /// Y-axis.
y: u32 };
```
```
zig fmt .
```
```
./main.zig:1:26: error: same line documentation comment
pub const Pos = struct { /// X-axis.
                         ^
./main.zig:2:9: error: same line documentation comment
x: u32, /// Y-axis.
        ^
```

**Comment by SpexGuy** [comment]
The fix for now is to add a `,` after `y: u32`, but we should keep this issue open because zig fmt probably should do something else without the trailing comma.

**Comment by ifreund** [comment]
Looks like the fix in https://github.com/ziglang/zig/pull/10027 needs to be expanded slightly.

**Comment by LewisGaul** [comment]
FYI @tjohnes in case you were interested in working on this.
