### ISSUE TITLE
CI: make the static linux binary link return non-301 status code

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1046]
The [linux static build download link](https://ziglang.org/builds/zig-linux-x86_64-master.tar.xz) is getting cached in users' browsers.

Looks like it's possible using "Advanced Conditional Redirects" https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html#advanced-conditional-redirects

`HttpRedirectCode`

**Comment by mreiland** [comment]
I noticed that the last-modified header is incorrect and FF sent in the if-modified-since header with a date that matched the incorrect date-modified.

It looks like the server thinks the file hasn't been modified for some reason, most likely due to some interaction with amazon S3 (I think that's what you're using?).  If so, investigating how to fix the last-modified may fix the issue.

**Comment by mreiland** [comment]
I did some more investigation, here's the documentation from Amazon, if you do a search for 'last-modified' you'll see the relevant section.

https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html

This isn't technically for the http headers I think, but I would be surprised if they're not used directly for said headers.  Here's the relevant description of last-modified.

> Object creation date or the last modified date, whichever is the latest. 

I'm wondering if perhaps this is a caching issue on the server side?  I'm not really familiar with S3 so I'm guessing here, but I wonder if their systems are just caching the information and being slow to update?  Or if perhaps you're using something like cloudflare and it's caching?  If so, purging that cache when you push an update may fix the issue.

Something to consider.

**Comment by andrewrk** [comment]
Here's my plan to fix this: 
 * move travis & appveyor into azure pipelines
   - this also gives us more time, so we can re-enable release mode testing
 * have a job that gets triggered after any other (linux, macos, windows) build completes successfully. this job will update the URLs, file sizes, shasums, etc, on the download page directly. The redirect URL will be gone.

**Comment by andrewrk** [comment]
This exists now: https://ziglang.org/download/index.json
