### ISSUE TITLE
translate-c generates un-callable function definition.

### ISSUE THREAD

**Issue by TwoClocks** [ziglang/zig#10461]
### Zig Version

0.9.0

### Steps to Reproduce

The following C code
```c
struct one {
    int first:1;
    int second:4;
    short reserved; // reserved
};

struct second {
    int first;
    struct one second;
};
short simple_c_func(struct second *param);
```
generates the following zig
```zig
pub const struct_one = opaque {};
pub const struct_second = extern struct {
    first: c_int,
    second: struct_one,
};
pub extern fn simple_c_func(param: [*c]struct_second) c_short; // test.h:19:11: warning: struct demoted to opaque type - has bitfield
```

Bitfields are not currently supported. There are other open tickets about that.

The resulting `simple_c_func` is un-callable (I think) because whatever I try to pass gets cast to an opaque type, which isn't allowed, and the compiler errors.

I need to craft a zig version of `one` and `second` w/ the same layout. No bitfield support. understood. fine. But I also need to modify the method signature to not reference an opaque type.

`translate-c` should not allow function params to opaque types. Convert them to `*anyopaque` or something.

### Expected Behavior

`translate-c` should not reference opaque types in function signatures.

### Actual Behavior

`translate-c` generates an un-callable function.

**Comment by Vexu** [comment]
The issue isn't referencing opaque types in function signatures but having them as field types, and the fix is as simple as calling `qualTypeWasDemotedToOpaque` in `transRecordDecl`.

**Comment by TwoClocks** [comment]
If C expect an opaque type directly it generates this for the function `pub extern fn simple_c_func(param: ?*struct_second) c_short;`  which fixes the problem.

But you are think changing the definition of `second` is a better solution. What should `second` look like to you?

**Comment by hazeycode** [comment]
> But you are think changing the definition of `second` is a better solution. What should `second` look like to you?

`pub const struct_second = opaque {};`



> The issue isn't referencing opaque types in function signatures but having them as field types, and the fix is as simple as checking `qualTypeWasDemotedToOpaque` in `transRecordDecl` and demoting the containing record to opaque as well if needed.

Presumably then, passing `@ptrCast(*anyopaque, &foo)` to `simple_c_func` will still work because the arg type is `opaque {}`

If so, this is a better solution than modifying function signatures, as I suggested in the other issue. Nice! :+1:

**Comment by TwoClocks** [comment]
For an opaque type used directly, the function sig becomes `pub extern fn simple_c_func(param: ?*struct_second) c_short;` and you don't need to cast at all, you can just send a `&my_second`

In general, I'm not in favor of destroying information if it can be avoided. So if there is some complex hierarchy of structs, and some leaf node has a bit field in it, the entire branch just becomes `opaque`? That doesn't seem good to me. Especially as the end result is just changing the function signature. I think it'd be better to just "remember" that there is an opaque type in there somewhere, and change the function signature. The same end result, less destruction of data.

**Comment by TwoClocks** [comment]
That will not work.
```zig
const Second = opaque{};
pub extern fn c_func(sec: [*c]Second) void;
pub fn main() anyerror!void {
    var temp = Point{ .x=10, .y=20, };
    c_func( @ptrCast(*anyopaque, &temp));
}
```
This gives the error `C pointers cannot point to opaque types`. This is still an un-callable function.

The function signature must be changed. That is exactly what `translate-c` does if it sees the use of an opaque type directly. The param changes to `*?Second`, and now it's a callable function.

I don't think the fix is to make other structs opaque. The fix is to change the function signature for types that contain opaque types, exactly as it does now for direct use of opaque types.

This has the added benifit of not needlessly removing information. The hierarchy of structs remains useful if some leaf struct has a bitfield in it.

**Comment by Vexu** [comment]
With this patch applied:
```diff
diff --git a/src/translate_c.zig b/src/translate_c.zig
index 79d68ff51..9b5a268e4 100644
--- a/src/translate_c.zig
+++ b/src/translate_c.zig
@@ -1076,7 +1076,7 @@ fn transRecordDecl(c: *Context, scope: *Scope, record_decl: *const clang.RecordD
             const field_loc = field_decl.getLocation();
             const field_qt = field_decl.getType();
 
-            if (field_decl.isBitField()) {
+            if (field_decl.isBitField() or qualTypeWasDemotedToOpaque(c, field_qt)) {
                 try c.opaque_demotes.put(c.gpa, @ptrToInt(record_decl.getCanonicalDecl()), {});
                 try warn(c, scope, field_loc, "{s} demoted to opaque type - has bitfield", .{container_kind_name});
                 break :blk Tag.opaque_literal.init();
```
`translate-c` generates:
```zig
// a.c:2:9: warning: struct demoted to opaque type - has bitfield
pub const struct_one = opaque {}; // a.c:9:16: warning: struct demoted to opaque type - has bitfield
pub const struct_second = opaque {};
pub extern fn simple_c_func(param: ?*struct_second) c_short;
```
which is very much callable.

**Comment by TwoClocks** [comment]
Right. Because you changed the function argument to `*?struct_second`. You could have done the same, and left the defintion of `struct_second` the same as it was before 
```zig
pub const struct_second = extern struct {
    first: c_int,
    second: struct_one,
};
```
IMO, you have needlessly removed information that doesn't need to be removed.

Your fix works, because `translate-c` changes the function signature for opaque types used directly. The fix is the function signature, not changing the struct.

**Comment by TwoClocks** [comment]
I haven't gone though the work to compile zig yet. So I have no idea if this works or not, but it seems like this might just chnage the param def w/o making the struct `opaque`
```diff
index 79d68ff51..4fca6e661 100644
--- a/src/translate_c.zig
+++ b/src/translate_c.zig
@@ -4793,7 +4793,7 @@ fn qualTypeWasDemotedToOpaque(c: *Context, qt: clang.QualType) bool {
 
             const record_decl = record_ty.getDecl();
             const canonical = @ptrToInt(record_decl.getCanonicalDecl());
-            return c.opaque_demotes.contains(canonical);
+            return c.opaque_demotes.contains(canonical) or qualTypeWasDemotedToOpaque(c, canonical);
         },
         .Enum => {
             const enum_ty = @ptrCast(*const clang.EnumType, ty);
```

**Comment by TwoClocks** [comment]
I bit the bullet got an env where I can build zig.
This is the resulting code that's produced
```zig
pub const struct_one = opaque {};
pub const struct_second = extern struct {
    first: c_int,
    second: struct_one,
};
pub extern fn simple_c_func(param: ?*struct_second) c_short;
```

I think this is better. The function is callable, and `struct_second` still contains useful information.
Here is the patch:
```
index 79d68ff51..3940f7449 100644
--- a/src/translate_c.zig
+++ b/src/translate_c.zig
@@ -4793,7 +4793,16 @@ fn qualTypeWasDemotedToOpaque(c: *Context, qt: clang.QualType) bool {
 
             const record_decl = record_ty.getDecl();
             const canonical = @ptrToInt(record_decl.getCanonicalDecl());
-            return c.opaque_demotes.contains(canonical);
+            if(c.opaque_demotes.contains(canonical)) return true;
+            
+            // check all childern for opaque types. Recursion here. ok?
+            var it = record_decl.field_begin();
+            const end_it = record_decl.field_end();
+            while (it.neq(end_it)) : (it = it.next()) {
+                const field_decl = it.deref();
+                if (qualTypeWasDemotedToOpaque(c, field_decl.getType())) return true;
+            }
+            return false;
         },
         .Enum => {
             const enum_ty = @ptrCast(*const clang.EnumType, ty);
```
