### ISSUE TITLE
formatting seems to ignore width+precision in generic type

### ISSUE THREAD

**Issue by euclidianAce** [ziglang/zig#10472]
### Zig Version

0.10.0-dev.74+426679574

### Steps to Reproduce

Run the following program:
```zig
const std = @import("std");

pub fn Vec2(comptime T: type) type {
    return struct {
        x: T,
        y: T,

        pub const Child = T;
        const Self = @This();

        pub fn format(value: Self, comptime fmt: []const u8, options: std.fmt.FormatOptions, writer: anytype) !void {
            _ = options;
            return std.fmt.format(writer, "Vec2({}){{{" ++ fmt ++ "},{" ++ fmt ++ "}}}", .{ Child, value.x, value.y });
        }
    };
}
pub fn main() !void {
    std.log.info("{d:2.2} {d:2.2}", .{ 123.123123123, 890.123123123 });
    std.log.info("{d:2.2}", .{Vec2(f32){ .x = 123.123123123, .y = 890.123123123 }});
    std.log.info("{d:2.2}", .{Vec2(f64){ .x = 123.123123123, .y = 890.123123123 }});
}
```

### Expected Behavior

the following to be printed:
```
info: 123.12 890.12
info: Vec2(f32){123.12,890.12}
info: Vec2(f64){123.12,890.12}
```

### Actual Behavior

this is printed:
```
info: 123.12 890.12
info: Vec2(f32){123.12312316894531,890.1231079101562}
info: Vec2(f64){123.123123123,890.123123123}
```

**Comment by enkore** [comment]
This isn't a bug per se, because fmt is only the formatting character at this point, the "2.2" has been parsed into the FormatOptions precision and width.

However, because `options` is not comptime (shouldn't it be? They're derived from the comptime format string after all), you can't really do this with std.fmt.format.

What you can do is this:

```zig
const std = @import("std");

pub fn Vec2(comptime T: type) type {
    return struct {
        x: T,
        y: T,

        pub const Child = T;
        const Self = @This();

        pub fn format(value: Self, comptime fmt: []const u8, options: std.fmt.FormatOptions, writer: anytype) !void {
            try std.fmt.format(writer, "Vec2({}){{", .{Child});
            try std.fmt.formatType(value.x, fmt, options, writer, 1);
            try writer.writeAll(",");
            try std.fmt.formatType(value.y, fmt, options, writer, 1);
            try writer.writeAll("}");
        }
    };
}
pub fn main() !void {
    std.log.info("{d:2.2} {d:2.2}", .{ 123.123123123, 890.123123123 });
    std.log.info("{d:2.2}", .{Vec2(f32){ .x = 123.123123123, .y = 890.123123123 }});
    std.log.info("{d:2.2}", .{Vec2(f64){ .x = 123.123123123, .y = 890.123123123 }});
}
```

**Comment by enkore** [comment]
Ah, so the reason why FormatOptions isn't comptime is because **they aren't**: https://github.com/enkore/zig/blob/master/lib/std/fmt.zig#L310

format can pull the width and precision out of the args. This doesn't seem to be documented, but definitely makes comptiming this as-is impossible:

```zig
const std = @import("std");

pub fn main() !void {
    std.log.info("{d:.[1]}", .{ 123.123123123123, try std.fmt.parseInt(u32, std.mem.span(std.os.argv[1]), 10) });
}
```

->

```
$ zig run issue10472.zig -- 4
info: 123.1231
$ zig run issue10472.zig -- 6
info: 123.123123
```

**Comment by euclidianAce** [comment]
Ah, okay. This is more of a documentation issue then. To initially try and solve the problem, I tried to find a generic formatter that took the `FormatOptions` and skimming the docs, I thought that `formatType` was the implementation of how types were formatted (but now looking at the impl, it just uses `@typeName`). Personally I would expect something like `formatValue` (which appears to already be a private function for formatting numbers and bool?) or `formatAny`

Anyway, thanks for giving a working version!
