### ISSUE TITLE
Creating file doesn't compile

### ISSUE THREAD

**Issue by Sucuturdean** [ziglang/zig#10489]
### Zig Version

0.10.0-dev.80+042b770d6

### Steps to Reproduce

```zig
const std = @import("std");

var file: std.fs.File = std.fs.cwd().createFile(file_path, .{ .read = true }) catch |err| switch(err) {
                error.AccessDenied => {},
                error.BadPathName => {},
                error.IsDir => {},
                error.PathAlreadyExists => {},
                error.SystemResources => {},
                error.FileBusy => {},
                else => {},
};
```

### Expected Behavior

I expected no compile time errors.

### Actual Behavior

It couldn't compile.
Error:  error: expected type 'std.fs.file.File', found 'void'

**Comment by InKryption** [comment]
When you handle the error with `catch`, the following expression is used as the value of the expression. In every prong of your switch statement, you are assigning `{}` (which has type void) to a variable with a type `std.fs.File`.
You either want to give a pre-determined value to the variable in case of error (by making it the value of the expression for any branch that you handle), or change control flow to avoid having to do so, e.g. by `return`ing, `break`ing out of an outer loop, or breaking from an outer labelled block.
