### ISSUE TITLE
Sentinel-Terminated Pointers Bug

### ISSUE THREAD

**Issue by Prince213** [ziglang/zig#10493]
### Zig Version

0.10.0-dev.128+ae8d6fd7b

### Steps to Reproduce

test.zig:
```zig
fn func(_: [*:0]const i32) void {}

pub fn main() void {
    var slice: []i32 = &.{};
    func(slice[0..slice.len :0]);
}
```

The run `zig build-exe test.zig`.

### Expected Behavior

Build successfully finishes.

### Actual Behavior

```
$ zig build-exe test.zig
Semantic Analysis [710/888] when analyzing /path/to/test.zig:5:15 in compiler source at /path/to/zig/src/stage1/codegen.cpp:1888: thread 1234567 panic: assertion failed. This is a bug in the Zig compiler.
```

**Comment by Vexu** [comment]
Fixed in master, tested in `test/behavior/slice.zig:test "slice multi-pointer without end"`.
