### ISSUE TITLE
Slice syntax - allow omitting lower bound

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#1050]
Currently, we can omit the higher bound and for eg. write `"hello"[0..]`

The `0` provides no additional information or readability improvements and is pure noise, so it would be better to allow to write it as `"hello"[..]`

**Comment by andrewrk** [comment]
Since it's only 1 character, and it's semantically equivalent, I'm going to leave it as being required. Fewer ways to do things. Smaller language.
