### ISSUE TITLE
bug: zig fmt accepts while with bad continue expression 

### ISSUE THREAD

**Issue by mstrikes** [ziglang/zig#10511]
### Zig Version

0.9.0-dev.2025+ecf0050a9

### Steps to Reproduce

write a while loop with a continue expression without a colon and at the end of the while loop write a semicolon
```zig
pub fn main() void {
    const somevalue = true;
    while (true) (somevalue){};
}
```
and run `zig fmt`.
you can also instead of the semicolon write an else expression
```zig
pub fn main() void {
    const somevalue = true;
    while (true) (somevalue){} else false;
}
```

### Expected Behavior

the call to `zig fmt` would print an error mentioning the missing colon. something like
```
file.zig:4:1: error: expected ':' or '{', found '('
    while (true) (somevalue){};
                       ^
```

### Actual Behavior

considering the file
```zig
pub fn main() void {
    const somevalue = true;
    while (true) (somevalue){};
}
```
the call to `zig fmt` accepts the input and formats the document.
if calling `zig build-exe` with the same file, it compiles until it tries to analyze the loop and errors with this error
```
.\file.zig:5:19: error: expected type 'type', found 'bool'
    while (true) (somevalue){};
                  ^
.\file.zig:5:29: note: referenced here
    while (true) (somevalue){};
```
when removing the semicolon at the end of the loop
```
.\file.zig:4:1: error: expected ';' or 'else', found '}'
}
```

**Comment by Vexu** [comment]
As the error suggests the while loop is parsed as having an array initialization expression (`T{...}`) as its body. Accepting the syntax is not a bug but the error message should clarify what's happening.
