### ISSUE TITLE
zig build-exe fails silently if ` --library` argument is given a path to an invalid library

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#1051]
For eg. create a new empty file `abc.txt` alongside your main.zig.
Then `zig build-exe main.zig --library abc.txt` fails silently (no exe is created, no error is displayed).

**Comment by tiehuis** [comment]
I get the following error now when invoking with those arguments so am going to close. Correct me if I've missed something.

```
lld: error: unable to find library -labc.txt
```
