### ISSUE TITLE
Useless compile error for array literal and slice type mismatch (semantic unification fail during type analysis)

### ISSUE THREAD

**Issue by locriacyber** [ziglang/zig#10529]
### Zig Version

0.10.0-dev.40+303bad998

### Steps to Reproduce

If I try to compile this
```
fn satisfyme(_: []const []const u8) void {}

pub fn main() void {
    satisfyme(.{});
}
```
I get
```
> zig build-exe test.zig
./test.zig:4:14: error: array literal requires address-of operator to coerce to slice type '[]const []const u8'
    satisfyme(.{});
             ^
./test.zig:4:16: note: referenced here
    satisfyme(.{});
```

...which is not useful at all.

## Common "wrong" solutions

I'm pretty sure that's an array
```
./test.zig:4:18: error: slice of non-array type 'struct:4:16'
    satisfyme(.{}[0..]);
                 ^
```

Parser error (I'm sure all of the things inside `(...)` is left-binding)
```
test.zig:4:35: error: expected ',', found '['
    satisfyme([]const []const u8{}[0..]);
                                  ^
```

That's literally a slice literal with address-of operator
```
./test.zig:4:17: error: array literal requires address-of operator to coerce to slice type '[]const []const u8'
    satisfyme(&([]const []const u8{}));
                ^
./test.zig:4:35: note: referenced here
    satisfyme(&([]const []const u8{}));
                                  ^
```

Assign to variable doesn't work either?
```
./test.zig:4:19: error: array literal requires address-of operator to coerce to slice type '[]const []const u8'
    const args = ([]const []const u8{});
                  ^
./test.zig:4:37: note: referenced here
    const args = ([]const []const u8{});
                                    ^
```

This one I kind of understand, but then I don't
```
test.zig:4:21: error: pointer modifier 'const' not allowed on array child type
    const args = [_]const[]const u8 { };
                    ^
```

## Right solutions

```
fn satisfyme(_: []const []const u8) void {}

pub fn main() void {
    satisfyme(([_][]const u8 {})[0..]);
}
```

```
fn satisfyme(_: []const []const u8) void {}

pub fn main() void {
    satisfyme(&([_][]const u8 {}));
}
```

### Expected Behavior

The error message should be clearer as to what I should do.

### Actual Behavior

It no work

**Comment by lithdew** [comment]
Array literal (.{}) requires address-of operator (&) to coerce to slice type ‘[]const []const u8’.

The error message is telling me to prepend ‘&’ to ‘.{}’. Therefore, the following should work:

```zig
satisfyme(&.{});
```

**Comment by leecannon** [comment]
Ive noticed a few times where new zig users get confused by this message, maybe changing it to clarify what is meant by the address-of operator much like @lithdew did in the above comment.

In general an array literal could be arbitrarily large so including it in the error as per lithdew's comment is not scaleable, maybe something as simple as the below would help:
`array literal requires address-of operator (&) to coerce to slice type '[]const []const u8'`

**Comment by locriacyber** [comment]
How about this variant (where I first met this problem)?
```
fn satisfyme(_: [][]const u8) void {}

pub fn main() void {
        satisfyme(&.{"hello"});
}
```

```
./test.zig:4:21: error: expected type '[][]const u8', found '*const struct:4:21'
        satisfyme(&.{"hello"});
                    ^
```

**Comment by locriacyber** [comment]
So this is a semantic unification problem.
Unrelated: [Here's a paper](https://sci-hub.se/https://doi.org/10.1109%2FMIC.2005.107) I found about semantic unification of humans from different expertise.

**Comment by InKryption** [comment]
@locriacyber `[][]const u8` is a slice of mutable memory, and taking the address of a literal always results in a constant pointer, and thus, where `*const struct:line:col` is able to coerce to `[]const T`, it can never coerce to `[]T`, since that's trying to coerce a pointer to constant memory into a pointer to mutable memory. If you were to instead write:
```zig
fn satisfyme(_: [][]const u8) void {}

pub fn main() void {
    satisfyme(&[_][]const u8{"hello"});
}
```
Or any variant of this where you specify the literal type, you'll see it's just the fact that coercion doesn't work for `const` to non-`const`.

**Comment by matu3ba** [comment]
@locriacyber Please always put the paper title and authors in case the document gets removed etc.

> address-of operator to coerce

I disagree with the title, since it is accurate where to put the `&`. However, the fix to wording is rather small.

**Comment by locriacyber** [comment]
The type inference is still broken. The following code will not compile without ugly type in front of array literal.
```zig
const std = @import("std");

pub fn main() anyerror!void {
    const pid = try std.os.fork();
    if (pid == 0) {
        return std.os.execveZ("ls"[0..], &.{"-lha"}, &[_:null]?[*:0]const u8{});
    } else {
        std.debug.print("parent, child pid={}\n", .{pid});
    }
}
```
```
> zig run 4.zig
./4.zig:7:44: error: expected type '[*:null]const ?[*:0]const u8', found '*const struct:7:44'
        return std.os.execveZ("ls"[0..], &.{"lha"}, &[_:null]?[*:0]const u8{});
                                           ^
./4.zig:7:44: note: destination pointer requires a terminating 'null' sentinel
        return std.os.execveZ("ls"[0..], &.{"lha"}, &[_:null]?[*:0]const u8{});
                                           ^
```

**Comment by matu3ba** [comment]
> &.{...} works but with a &[]T{...} doesn't work, but still has an error message saying that it needs &.
it should say that both & and _ are required &[_]T{...}

Can you add new issue with example for this and make sure this does not already exist?
