### ISSUE TITLE
undefined is not a value, replace it by  fn @undefined(T: type) T. 

### ISSUE THREAD

**Issue by RogierBrussee** [ziglang/zig#10527]
### Please do not file a proposal to change the language

- [X] I understand, thank you. I will not submit a new proposal at this time

**Comment by RogierBrussee** [comment]
The undefined  value is strange: it breaks the invariant that if a is a value then 
const x:T = a ; const y:T = a  implies  x == y. 

However no such guarantee can be made for functions. Therefore replace

const x:i64 = undefined;

by 

const x = @undefined(i64);

**Comment by InKryption** [comment]
The purpose of `undefined` is to allow the programmer to signal to the compiler "I don't care about the value of this variable, and there should be no guarantees about its value until it is assigned one". This saves on things like unnecessary initialization, and when in debug mode, helps to ensure program correctness, and to catch invalid invariants, by making any code that tries to use an `undefined` value result in a panic.

It is meant to break that invariant.

**Comment by RogierBrussee** [comment]
@kristoff-it The practical benefit is that it simplifies program analysis both for the compiler or static analyser, and for humans because it removes a wart from the language and a rather subtle coercion that depends implicitly on the environment. IIUC the semantics of 

const undef = undefined;
const x:i32  = undef;
const y:i32  = undef;

SHOULD imply undef == undef and undef == undefined, but SHOULD NOT imply that x  == y while 

const undef_int:i32 = undefined;
const x = undef_int;
const y = undef_int;

SHOULD imply undef_int == undef_int and  x == y, but SHOULD NOT imply undef_int == undefined.


@InKryption  Yes I understand that it is _supposed_ to break the value == value invariant, but the point of the proposal is that while there is a need for indicating that a variable is not initialised there is no need to introduce this  breaking of value semantics. The function @undefined(i32) is a perfectly normal function that returns an i32 (albeit with some optimisation potential) and indicates that x is uninitialised just as well. It may depend on the state of the program and the environment (conceptually it returns whatever it finds on the stack) , and like for all such non pure functions there is no reason why  @undefined(i32) == @undefined(i32)

**Comment by InKryption** [comment]
> there is no need to introduce this breaking of value semantics

I don't really see what you mean by "breaking of value semantics" here, it's not as though this is the only case where this happens. For floating point numbers, if you compare a NaN and  a NaN for equality, it will evaluate to false, even if both values are identical in terms of their bytes. `undefined` exists only at `comptime`, same as `null`.

The only thing this proposal would change is that you'd now need to needlessly specify the type to which `undefined` should coerce, worsening the process of changing/refactoring code, and making it more verbose. This proposed `@undefined(T)` still returns a value, and `@undefined(T) == @undefined(T)` would still be undefined behavior.
Also, if you actually use `undefined == undefined` in control flow (e.g., anything that affects the state of the program, like using the boolean result in an `if` clause, or what have you), you'll get a compile error, so it's not as if this is actually a problem.

**Comment by SpexGuy** [comment]
This invariant doesn't hold for floats either.  If `a` is NaN then `==` will return false.
