### ISSUE TITLE
[Windows] Stage2 compiler - zig.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by nc-x** [ziglang/zig#1054]
Stage1 compiler built with vs2017.

Stage2 compiler built using `bin\zig build --build-file ..\build.zig --prefix stage2 install` in `powershell` 

![capture](https://user-images.githubusercontent.com/39912580/40951567-367b3fc2-6895-11e8-846c-139c39afdf8d.PNG)

**Comment by andrewrk** [comment]
Oops, my mistake:

https://github.com/ziglang/zig/blob/4fc601895b9f89bf0d3d3c1de1b0bbc959444298/std/os/windows/index.zig#L126

This is incorrect, because according to MSDN, it should be "shlwapi": https://msdn.microsoft.com/en-us/library/windows/desktop/bb773584(v=vs.85).aspx
