### ISSUE TITLE
Rename `const` to `con`

### ISSUE THREAD

**Issue by helloworldguy4** [ziglang/zig#10550]
Please hear me out.

Now with things like #1717 being on the horizon, there will easily be more `const` definitions on average in a file than `var` definitions. That, even though `const` should be the keyword that's faster to type than `var`, not the other way around. 

I feel like if we can get used to the fact that `fn hello() void {}` is going to be written as `const hello = fn() void {}` in the future, we can also get used to `const` being written as `con`.

I understand that this issue is very controversial but to me it seems like Zig is a language that doesn't fear breaking old traditions in order to improve on the past.

# Pros

* Especially in the future the three most common keywords on the top level of a file will be `const`, `var` and `pub`. With this change, they would all have the same length which could benefit the reader and writer both aesthetically and readability-wise.
* Consistency with `var`. `var` and `const` are closely related. With this change the way they are abbreviated is consistent: only the first 3 characters are kept of these 2 words that also happen to have the same length (coincidence?):
  ```
  constant
  variable
  
  con
  var
  ```
* Faster to type. This is especially important for `const` as I'm pretty sure this already is or will be the **most common keyword of all**.
  It is already used for so many things and will be used for even more in the future.
  Ultimately all this time will add up and we will have saved tons of time not typing those 2 characters.
* Faster to read.

# `con`s

* May feel unusual for people that are already familiar with Zig.
* I don't know of any other language that uses `con` to mean "constant".

  However I don't think this really matters because Zig is its own language and its definition of "constant" is different from other languages anyway. You can't do the same with Zig's `const` as you can do with JavaScript, C# or C++'s `const`, they are all different anyway.
  
  I believe if back then the people of the early languages with `const` had decided to name it `con` instead, writing `con` to mean "constant" would feel as natural to us as it does to write "const" for "constant". It's all about usage and we can be the first to bring it to usage, for the better. Things become natural as usage starts and grows.

# The future Zig

## Before

![image](https://user-images.githubusercontent.com/35064754/148679499-9d2bb1f9-5610-4153-807b-96dae41593a3.png)

## After

![image](https://user-images.githubusercontent.com/35064754/148679681-9fddf8de-5b30-4e55-800c-55ff922940ad.png)

Looks quite sleek and modern to my eyes.

# Migration

For one release both `con` and `const` are accepted and the formatter formats `const` to `con`. `const` is removed in the next release.

**Comment by jibal** [comment]
Other languages use `let` or `val` for this.

**Comment by CommoDor64** [comment]
I think the fact that it is grotesquely non-canonical makes the entire thing a neutral-mildly bad.

Not even mentioning how many applications will break because `con` used as variable name
