### ISSUE TITLE
Wasm targets should append lld --stack-first (again)

### ISSUE THREAD

**Issue by ZetaNumbers** [ziglang/zig#10567]
### Zig Version

0.9.0

### Steps to Reproduce

 - Copy source directory from https://github.com/aduros/wasm4/tree/3061bd7459d59cc5fdd97c2f71aace5caeaf2a7f/cli/assets/templates/zig;
 - Run `zig build -Drelease-small=true`;
 - Inspect output file via `wasm2wat ./zig-out/lib/cart.wasm`;
 - Find `$__stack_pointer` global.

### Expected Behavior

Stack should begin before globals on wasm targets according to #4496, i. e. 
```wat
(global $__stack_pointer (mut i32) (i32.const 8192))
```

### Actual Behavior

```wat
(global $__stack_pointer (mut i32) (i32.const 14816))
```

**Comment by sporksmith** [comment]
I see that this issue is marked closed, but it's assigned to the 0.9.1 milestone and afaict the fix isn't in the 0.9.x branch. Is this a mistake?

**Comment by andrewrk** [comment]
No mistake - I haven't cherry picked into the 0.9.x branch for a week or so. Will be sure to grab this one.

**Comment by andrewrk** [comment]
Pushed to 0.9.x branch. Let me know if you think I should cherry-pick an additional fix that did not make it.

**Comment by sporksmith** [comment]
> Pushed to 0.9.x branch. Let me know if you think I should cherry-pick an additional fix that did not make it.

Thanks, that simplifies our decision on what the zig 0.9.1 behavior should be in the next release of wasm4 :)

**Comment by andrewrk** [comment]
Worth noting is that this one made it in there too: #10517 (Thanks @Luukdegram!)

That should address binary bloat that I'm guessing many people were experiencing before.
