### ISSUE TITLE
`Builder.findProgram()` fails on Windows when env path is `Path` not `PATH`.

### ISSUE THREAD

**Issue by jagt** [ziglang/zig#10561]
### Zig Version

0.10.0-dev.207+c08b190c6

### Steps to Reproduce

Here's a repro on my box.

```
C:\tmp>cat findDir.zig
const std = @import("std");
const Builder = std.build.Builder;

test "builder.findProgram fails on windows" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var b = try Builder.create(
        arena.allocator(),
        "test",
        "test",
        "test",
        "test",
    );

    _ = try b.findProgram(&[_][]const u8{
        "calc",
    }, &[_][]const u8{});
}

C:\tmp>set | rg -i Path=
Path=C:\SDK\Conda;.......
```

Basically this happens when env is `Path` not `PATH` on windows. 

I can track down it's this particular line checking for `PATH`
<https://github.com/ziglang/zig/blob/master/lib/std/build.zig#L1140>

It's trivia to fix but not sure how should I do it though. Should I check for path case insensitive on windows?
Thanks in advance!

### Expected Behavior

`Builder.findProgram` should work when it's `Path` on Windows.

### Actual Behavior

`Builder.findProgram` failed to find when it's `Path` on Windows.

**Comment by marler8997** [comment]
> Should I check for path case insensitive on windows?

Probably.  I can confirm that like file paths, environment variables are also case-insensitive on Windows.

**Comment by squeek502** [comment]
This would be fixed by https://github.com/ziglang/zig/issues/4603#issuecomment-593637142. I'm currently working on it, should have a PR ready in the next few days.
