### ISSUE TITLE
BoundedArray slice corruption?

### ISSUE THREAD

**Issue by beanz** [ziglang/zig#10590]
### Zig Version

0.9.0

### Steps to Reproduce

I am testing the following code:

```
const std = @import("std");
const test1file =
    \\0,9 -> 5,9
    \\8,0 -> 0,8
    \\9,4 -> 3,4
    \\2,2 -> 2,1
    \\7,0 -> 7,4
    \\6,4 -> 2,0
;

pub fn main() anyerror!void {
    var ints = try BoundedInts(u16, 2024, test1file);
    std.debug.print("{any}\n", .{ints});
}

pub fn BoundedInts(comptime T: type, comptime expected: usize, inp: anytype) anyerror![]T {
    var ints = try std.BoundedArray(T, expected).init(0);
    var n: T = 0;
    var num = false;
    for (inp) |ch| {
        if ('0' <= ch and ch <= '9') {
            num = true;
            n = n * 10 + @as(T, ch - '0');
        } else if (num) {
            std.debug.print("{}, ", .{n});
            try ints.append(n);
            n = 0;
            num = false;
        }
    }
    if (num) {
        std.debug.print("{}", .{n});
        try ints.append(n);
    }
    std.debug.print("\n", .{});
    return ints.slice();
}
```

### Expected Behavior

I expect the output to be:
```
0, 9, 5, 9, 8, 0, 0, 8, 9, 4, 3, 4, 2, 2, 2, 1, 7, 0, 7, 4, 6, 4, 2, 0
{ 0, 9, 5, 9, 8, 0, 0, 8, 9, 4, 3, 4, 2, 2, 2, 1, 7, 0, 7, 4, 6, 4, 2, 0 }
```

Indicating that the input has been parsed correctly and the resulting slice matches and in ReleaseSafe mode this is what I see.

### Actual Behavior

In ReleaseFast mode the resulting slice is corrupted and the output shows:
```
0, 9, 5, 9, 8, 0, 0, 8, 9, 4, 3, 4, 2, 2, 2, 1, 7, 0, 7, 4, 6, 4, 2, 0
{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8194, 0, 0, 0, 6, 4, 2, 0 }
```

Perhaps I am misunderstanding something I am sacrificing by running in ReleaseFast mode?

I also tried zig 0.10.0-dev.260+c4681b488 but that gives the more subtly corrupt:

```
0, 9, 5, 9, 8, 0, 0, 8, 9, 4, 3, 4, 2, 2, 2, 1, 7, 0, 7, 4, 6, 4, 2, 0
{ 0, 9, 5, 9, 8, 0, 0, 8, 56, 4, 3, 4, 2, 2, 2, 1, 7, 0, 7, 4, 6, 4, 2, 0 }
```

Thanks in advance for any help resolving this issue.

**Comment by InKryption** [comment]
`BoundedArray` exists on the stack; when you 'return', the allocated stack associated with the array inside `BoundedArray` is destroyed, so you're returning a pointer to invalid memory.

**Comment by beanz** [comment]
Interesting. I had assumed reading the documentation that it was a buffer preallocated at compile time and that it would therefore be a singleton but that single threaded use would be safe. I guess I completely misunderstood. Thanks for enlightening me.
