### ISSUE TITLE
Better memory search algorithm

### ISSUE THREAD

**Issue by isaachier** [ziglang/zig#1060]
Just an idea for resolving this TODO: https://github.com/ziglang/zig/blob/652f4bdf6242462182005f4c7149f13beaaa3259/std/mem.zig#L283

* Look at musl for some really clever memory search algorithms like [memmem](https://git.musl-libc.org/cgit/musl/tree/src/string/memmem.c).
* There are a few Wikipedia articles on [string search algorithms](https://en.wikipedia.org/wiki/String_searching_algorithm).
* [the_silver_searcher](https://github.com/ggreer/the_silver_searcher) uses the [Boyer-Moore string search algorithm](https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore_string_search_algorithm) to achieve better performance.

**Comment by tiehuis** [comment]
This is pretty straight-forward to do, but one question:

What is the expectation regarding slices of nullable/errors? Is it valid to cast these directly to a byte representation and search on that? What about padding between non-power-of-two integers, is this consistent?

**Comment by andrewrk** [comment]
Hm these are important questions. I need to consult with @thejoshwolfe 

My first thought is that zig would not make guarantees about size or layout of nullables or error unions, and that integers would be guaranteed to be padded only to the next power of 2.

**Comment by andrewrk** [comment]
> What is the expectation regarding slices of nullable/errors?

opaque memory layout

> Is it valid to cast these directly to a byte representation and search on that?

no - this is valid only for types which have well-defined memory layout

> What about padding between non-power-of-two integers, is this consistent?

power-of-two integers with >= 8 bits have well-defined memory representation; non-power-of-two integers have opaque memory layout.
