### ISSUE TITLE
cache: does not take compiler itself into account.

### ISSUE THREAD

**Issue by TwoClocks** [ziglang/zig#10608]
### Zig Version

0.9.0

### Steps to Reproduce

1 - Use zig to build a project.
2 - Change something in the compiler, and re-compile zig.
3 - Build the project again w/ new compiler.

No new code is generated for the project, even though the compiler has changed. It will be pulled from `~/.cache/zig`. The changes you made to the compiler aren't used.

This only affects people working on the compiler, so maybe not worth fixing. But I spent a few hours pulling my hair out until I figured out what was going on.

I was making changes to `translate-c`, and had a local `test.c` to test my changes. But the compiler was just pulled the cached version of the translation. I even put `std.os.exit(1)` at the entry point to `translate-c`. The newly built compiler happily gave translated output for test.c. I thought I was going insane. 
This might only effect the self-hosted parts of the compiler. Or just `translate-c` Not sure.

### Expected Behavior

New code should be produced with a new compiler.

### Actual Behavior

cached code is used w/ a new compiler, as the cache code doesn't take the compiler "version" into account. At least it seems that way. I didn't check to see if this is actually the case.

**Comment by SpexGuy** [comment]
Fwiw it does take the version into account, but two local builds from working copies at the same head revision identify as the same "version", even though there may be local changes that differentiate them.

**Comment by andrewrk** [comment]
This is working as designed. Developers need to be able to test changes to the caching system.

**Comment by TwoClocks** [comment]
Makes sense.
Maybe a note about the cache behavior and local builds in this doc : 
https://github.com/ziglang/zig/blob/master/CONTRIBUTING.md
?
especially in the Translate-C section?
