### ISSUE TITLE
Is it possible to add gc into zig?

### ISSUE THREAD

**Issue by bronze1man** [ziglang/zig#1063]
I found that long running process and mulit-thread and manual memory management will make write correct code very slow.
I think it should be better only use manual memory management when I need less delay, less CPUs and less memory.
I can only use gc in the golang . Use gc and manual memory management at the same time should be better.

If it is possible to add gc into zig, is there a implement of gc in zig?

**Comment by thejoshwolfe** [comment]
We definitely don't want to force or encourage zig programmers to use a garbage collector. We also have no constructors/destructors to hook into to implement reference counting like you might do in C++.

It's theoretically possible to implement a heuristic-based type-unsafe general purpose garbage collector, which I've seen done for C/C++ programs. I've never used something like that, but the same thing would be possible in Zig. There is no plan to add anything like that to the standard library.

**Comment by bronze1man** [comment]
I think manual memory management in mulit-thread is like use sync.Pool in golang. 
Here is several rules, you must obey:
You must not free an object twice.
You must free an object as soon as the object is not used any more.
You must not use an object after it is free.

With all those rules, it make write correct code very slow.
With one human mistake, the program will data race, crash, undefined behavior or have a bug that can be hacked. (using sync.Pool in golang)

**Comment by isaachier** [comment]
Honestly a GC totally undermines the purpose of Zig's mission to replace C. If you want GC, use D.

**Comment by bronze1man** [comment]
Does zig have a tool that can prove my program do not have any mistake about manual memory management from source code?

Data race bug and dead-lock bug is the major problems for my golang project right now.
If I use zig, I need to solve another the manual memory management bug to my major problems list.
If zig do not have this kind of tool, I will prefer golang right now, because it only have two major problems.

**Comment by isaachier** [comment]
@bronze1man analysis tools are one thing, but GC affects the runtime.
