### ISSUE TITLE
std.mem.Allocator: reallocAtLeast should allow upper limit

### ISSUE THREAD

**Issue by ArborealAnole** [ziglang/zig#10647]
If we have a container that is growing exponentially due to unbounded insertions, extra memory in the allocation will be useful (as long as it does not change the effective growth rate to a harmful extent). But if `usize == u64`, and the container is restricted to, say `2^16` or `2^32` elements (for example, if the IDs are the indices and the IDs are stored as `u16` or `u32`, and the container is tasked with restricting the number of elements), then the container can only use `reallocAtLeast` if it tracks the obtained capacity separately from the operational capacity. That's because the `rawFree` function takes a slice of `u8` which includes the allocation size, and with no upper limit given to the allocator there is a possibility that the allocation size is larger than the maximum operational capacity. _This makes the container management object larger and more complex._

If `reallocAtLeast` accepts an upper limit, the allocator can easily handle the burden and may often not need to do anything differently under typical control flow (when the upper limit is not exceeded) except a single comparison per allocation. Even if the allocator now has to store an extra `usize` for actual capacity, that may have better locality there than in the container.

The allocators are already required to provide exact allocations; this only requires exact allocation instead if the upper limit is exceeded.

The version with upper limit could be a different function by name, or after `comptime` static dispatch.

This change may not be as useful if `rawFree` does not take the allocation size as a parameter. However, in that case it could still possibly save unusable memory (any memory above the upper limit that would be otherwise provided by the allocator and can be saved efficiently). 

The upper limit could be used to provide a cap on the maximum acceptable extra memory allocated at the current time during normal operation for performance reasons rather than for correctness, but the utility of this is unclear to me and depends on the allocator design.

**Comment by marler8997** [comment]
`reallocAtLeast` should only return more memory than requested if that memory would have "otherwise been wasted".  At least that's how I intended the behavior of `resize` to work when I first implemented it.  If you got more memory than you requested, then by definition that memory could not have been leveraged by any other allocation. In the case where you actually wanted more memory that you requested, then you can increase the request length.  This handles all use cases I can think of.

**Comment by ArborealAnole** [comment]
I feel like an allocator may be able to be more lazy and provide a huge excess with `reallocAtLeast` (depending on the user's choice of allocator), e.g. binary buddy block allocation dividing up a 1GiB page vs. assigning 2MiB pages to reach the allocation size.

I think that for the last thing I mentioned to cap the memory only for performance (specifically conserving memory space), you'd rather want to have a separate "upper hint" to mean "please try to stay below the upper hint; however, if the minimum you can allocate, that's greater than the allocation size, is more than the upper hint I'll take all of it". It's only useful if the allocator has the capability of being more or less restrictive with memory depending on request (i.e. there is multiple strategies, so that the reason more might be allocated in absence of a upper hint is for performance). I'm not sure how important it is to have that in the standard library.

If there _is_ some upper limit on the amount of memory that I can possibly use, it will be useful to provide as an upper limit rather than upper hint because it's stronger and doesn't come at the cost of possibly futilely wasting usable space (and only "upper limit" may be available). Similarly to the "upper hint" this allows the allocator to possibly decide that finding a lower allocation size that's above the nominal request size, than it would otherwise have given, would be optimal.

Regardless, the most important point is that I'd like to be able to get any memory that would have otherwise been wasted, but only if the allocator caps the size that it tells me the memory is, to the upper limit I provide. I will usually be able to use all of the extra space above my requested level, but if extra space is provided above the limit, then that is intrinsically bad for me. The main reason is that it may not be trivial to discard the extra space myself because of the `free` api taking the provided space as a parameter.

It's up to the allocator whether it change its strategy if there will then still be extra unusable space.

I don't think it would hurt to have the upper limit be arbitrary `usize` passed dynamically (at least nominally), but maybe it could be passed statically as comptime.

**Comment by marler8997** [comment]
I'm having a hard time translating your proposal into concrete items.  Could you give me a specific use case you're looking for?

**Comment by ArborealAnole** [comment]
This is a draft of a container that is limited in capacity to the input type `Limitalo`. It stores its capacity as a `usize` in the `ArrayList` even though it could store it as a `Limitalo`. It is still required to keep the capacity below the maximum size of a `Limitalo`. The line marked `// krizala` meaning 'critical' reduces the capacity stored in the `ArrayList` to the maximum size of a `Limitalo` if it is greater. Any alteration of the capacity from the actual allocated capacity will result in the allocator receiving a different `.len` field in the slice passed to `resize` or `free`, than expected, which is undefined behavior.

```zig
    /// Attempt to expand or shrink memory in place. `buf.len` must equal the most recent
    /// length returned by `alloc` or `resize` ...
```

The container is using an `ArrayList`, which uses `reallocAtLeast`, but the problem will be there even if I do not use that as an underlying container. It appears that there is no way to use an `Allocator` for this without either ignoring excess memory in an allocation by using `realloc`, or solving the problem similarly to:
The allocated capacity must be stored in the container separately from the operational capacity (note that the operational capacity is not the length), expanding the storage space by probably 1 `usize`. Every time there is an expansion, store the new capacity twice, and reduce the new operational capacity to the maximum capacity if it is greater.

I have thought of other ways to solve it while using an `Allocator`, with varying trade-offs, but they similarly require more instructions and space.

The extra `usize` and resultant padding could be significant overhead, if there is an array of containers for example. I think it could not be substantially more expensive to require the allocator to handle this.
```zig
pub fn Jurnalo(T: type, Limitalo_: type) type {
    const kreskalo_ = 4;
    const ii_L = @typeInfo(Limitalo_).Int;
    const bits_L = ii_L.bits;
    if (ii_L.signedness != .unsigned or bits_L >= @typeInfo(usize).Int.bits - std.math.log2_int_ceil(kreskalo_)) unreachable;

    return struct {
        const Co = @This();
        pub const Limitalo = Limitalo_;

        pub const inicialo = 1024;
        pub const kreskalo = kreskalo_;
        pub const maximo = std.math.maxInt(Limitalo);

        array_list: std.ArrayList(T) = undefined,

        pub fn aquirar(auto: *Co, atribuero: std.mem.Allocator) !void {
            auto.array_list = try std.ArrayList(T).initCapacity(atribuero, inicialo);
        }
        pub fn dispozar(auto: *Co) void {
            auto.array_list.deinit();
        }
        pub inline fn adjuntarLimite(auto: *Co, kozo: T) !void {
            if (auto.array_list.items.len == auto.array_list.capacity) { // se vera, pruvus ke 'better_capacity < new_capacity' en 'fn ensureTotalCapacity'
                // unlikely

                if (auto.array_list.capacity == maximo) {
                    return error.tromulta_kozi;
                }
                const nova_kapaceso = auto.array_list.capacity * kreskalo;
                if (nova_kapaceso > maximo) nova_kapaceso = maximo;
                try auto.array_list.ensureTotalCapacityPrecise(nova_kapaceso);
                if (auto.array_list.capacity > nova_kapaceso) auto.array_list.capacity = nova_kapaceso; // krizala!
            }

            auto.array_list.appendAssumeCapacity(kozo); // deziras 'inline'
        }
        pub inline fn longeso(auto: *Co) Limitalo {
            return @intCast(Limitalo, auto.array_list.items.len);
        }
    };
}
```
