### ISSUE TITLE
Debugging tests

### ISSUE THREAD

**Issue by ayende** [ziglang/zig#10667]
### Zig Version

0.9

### Steps to Reproduce

My usual Zig workflow is to run it from vs code, where I can use `gdb` to get really good debugging experience with Zig.
However, there is a really big disconnect when it comes to debugging tests. 

Let's assume that I have:

```
test "some test scenario" {
   try doSomethingNonObvious();
}
```

I run this using `zig build test` and it fails. I want to debug that, but there is no easy way to execute the _test case_ in question.

In some cases, the test is inside the same file, referencing private values. In order to actually debug it I have to copy & paste the code in the `main` method and run it that way.

### Expected Behavior

Provide a way to invoke the test manually.

I looked into https://github.com/ziglang/zig/issues/7620 and https://github.com/ziglang/zig/issues/6621 and they both seem to point out to the same underlying issue.

The `builtin.test_functions` is only available during tests. I tried to follow how that is done, but I got lost in the code.
I _think_ that it will be available in is `is_test` is set, but I can't figure out how to emit an executable that would also have this flag. 

I _think_ that I may be missing something in `build.zig`, but I'm not sure. 

My current workaround is to do the actual test in a standard function, and then call that from the test.
This is... ugly and I would really like to avoid it. 

### Actual Behavior

There is no way to do this that I'm aware of.

**Comment by guidorice** [comment]
@ayende there is one method of doing it (ymmv):

* Note that `zig build test` creates a test binary in `zig-cache`.

```shell
$ find zig-cache -name test
zig-cache/o/e237d9541ef16345a6b1342ba47b7e94/test
```
* edit vscode launch.json to run that binary, and also pass in your program's file as args:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Debug",
            "program": "${workspaceFolder}/zig-cache/o/e237d9541ef16345a6b1342ba47b7e94/test",
            "args": ["src/main.zig"],
            "cwd": "${workspaceFolder}"
        }
    ]
}
```
Using this vscode debugger extension: https://github.com/vadimcn/vscode-lldb

Originally mentioned here: https://zig.news/guidorice/comment/66

**Comment by ayende** [comment]
That is really nice. I'm using `WSL`, and the debugger experience (using `gdb)` is comparable to C, so I have nothing to complain about.

**Comment by EdAyers** [comment]
Also you can run tests for a particular file (or use `--test-filter ...`) with `zig test src/my_file.zig`, and then when it fails it will give you this output:

```
...
error: the following test command failed with exit code 1:
/Users/edward/my_project/.zig-cache/o/edcde99e60bc122ab792f92965d9de4f/test --seed=0xa8c32b06
```

which you can then point to in your launch config.
(Zig 0.14 at time of writing)
