### ISSUE TITLE
make std.fs absolute functions lower to the non-"at" variants of syscalls

### ISSUE THREAD

**Issue by synaptiko** [ziglang/zig#10678]
### Zig Version

0.9.0

### Steps to Reproduce

I have the following code:
```
const file = try std.fs.openFileAbsolute(list_path, .{ .read = true, .write = true });
defer file.close();
```

And the linux system has `tmpfs` enabled for `/tmp`.
```
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,nr_inodes=1048576,inode64)
```

The content of `list_path` is `/home/user/some-file`.

### Expected Behavior

Everything works fine, no need to worry about from where the command is being run.

### Actual Behavior

When the command which uses the above code is run from `/tmp` directory, it will end up with "rename: Invalid cross-device link" error and `/home/user/some-file` will disappear. The content can be recovered from `/tmp` itself, as there is some random file created.

IMHO this is quite unexpected behavior and it took me really long to figure out. I only realized what's going on when I checked the implementation of `std.fs.openFileAbsolute()` and saw that it in fact calls `cwd().openFile()`.

The workaround is to call `cd && command` instead.

**Comment by andrewrk** [comment]
`cwd().openFile()` is just doing this:

```
openat(AT_FDCWD, "/home/user/some-file", O_RDWR|O_NOCTTY|O_CLOEXEC) = 3
```

Does `openat` with `AT_FDCWD` not work with tmpfs? Seems like a bug in tmpfs.

That said, I think it would be reasonable to expect `openFileAbsolute` to lower to the `open` syscall instead of `openat`.

**Comment by I-mikan-I** [comment]
> FWIW glibc uses the -at functions all the time now (even the `open` libc function goes to `openat`)
> 
> Linux kernel developers (at one time at least) were saying that going forward, only `-at` variants would be available and to considered the non -at variants to be for compatibility only.

Thanks for the info, I tested if it makes a difference whether we use AT_FDCWD or not, and could not replicate the original issue myself.

Here's my application's source code, compiled with zig 0.9.0 in Debug and ReleaseFast:
```zig
pub fn main() anyerror!void {
    const file = try std.fs.openFileAbsolute("/home/mikan/test", .{.read = true, .write = true});
    defer file.close();
    try file.writeAll("Hello, World!\n");
}
```

Running it from /tmp/ works just as expected, it's mounted as follows: `tmpfs /tmp tmpfs rw,nosuid,nodev,size=16395112k,nr_inodes=1048576,inode64 0 0`.


Perhaps this issue is related to something else?

**Comment by ifreund** [comment]
To repeat my [comment](https://github.com/ziglang/zig/pull/11027#issuecomment-1056881037), in the linux kernel implementation open() and open_at(AT_FDCWD) are 100% identical.
```c
SYSCALL_DEFINE3(open, const char __user *, filename, int, flags, umode_t, mode)
{
	if (force_o_largefile())
		flags |= O_LARGEFILE;
	return do_sys_open(AT_FDCWD, filename, flags, mode);
}

SYSCALL_DEFINE4(openat, int, dfd, const char __user *, filename, int, flags,
		umode_t, mode)
{
	if (force_o_largefile())
		flags |= O_LARGEFILE;
	return do_sys_open(dfd, filename, flags, mode);
}
```
https://elixir.bootlin.com/linux/latest/source/fs/open.c#L1232

**Comment by synaptiko** [comment]
@I-mikan-I I tried to reproduce the issue again, I have the latest kernel & zig, recompiled my program and everything seems to work now. It's quite possible it wasn't really related to zig, as you mentioned. I think this issue can be closed.
