### ISSUE TITLE
Add `--verbose-zir` option to `build-exe` command, like AIR and MIR have.

### ISSUE THREAD

**Issue by mparadinha** [ziglang/zig#10687]
The current way to output the ZIR of a file is through the following `ast-check` command, like so:
```
zig ast-check -t <source file>
```
I think this was probably done during the early stages of stage2 when only the `ast-check` was working, which is no longer the case :).

Should the flag for `ast-check` also be removed, or just add a new `--verbose-zir` flag to `build-exe`?

Also, the ZIR debug output goes to `stdout` whereas both AIR and MIR output to `stderr`. Should I create a separate issue for this?

**Comment by andrewrk** [comment]
Why would you want this? `zig ast-check -t` is so much more convenient than a hypothetical `--verbose-zir` flag.

**Comment by mparadinha** [comment]
> Why would you want this? zig ast-check -t is so much more convenient than a hypothetical --verbose-zir flag.

When diagnosing the cause of bugs I found it very helpful to quickly switch between the AIR and MIR debug outputs to figure out in which part of the compiler the bug was. 
But when trying to get the ZIR output it always took me a while to remember which command/flag I needed to use.
(not really a problem anymore though, as I've gotten used to it now)
