### ISSUE TITLE
Miscompilation when taking address of @ptrCast()-ed pointer

### ISSUE THREAD

**Issue by dkareh** [ziglang/zig#10690]
### Zig Version

0.10.0-dev.369+12c2de6ee

### Steps to Reproduce

Run `zig test main.zig` where `main.zig` contains:
```zig
const std = @import("std");
var hidden_data: u32 = 1729;
fn cGimmeAPtr(ptr_to_ptr: **anyopaque) void {
    ptr_to_ptr.* = &hidden_data;
}
export fn wrongZigGimmeAPtr() *u32 {
    var ptr: *u32 = @intToPtr(*u32, 0x48); // Easy to recognize initial value.
    cGimmeAPtr(&@ptrCast(*anyopaque, ptr));
    return ptr;
}
export fn correctZigGimmeAPtr() *u32 {
    var ptr: *u32 = @intToPtr(*u32, 0x48);
    cGimmeAPtr(@ptrCast(**anyopaque, &ptr));
    return ptr;
}
test {
    try std.testing.expectEqual(wrongZigGimmeAPtr(), correctZigGimmeAPtr());
}
```

### Expected Behavior

I expect the position of `@ptrCast` to not affect the generated code, so the test should pass and the two returned pointers should be equal.

### Actual Behavior

```shell
$ zig test main.zig
Test [0/1] test ""... 1/1 test ""... expected u32@48, found u32@7ff745eb0000
Test [1/1] test ""... FAIL (TestExpectedEqual)
FAIL (TestExpectedEqual)
```
This issue confused me for a long time until I looked at the generated assembly code (https://godbolt.org/z/1Kz35PTEq). `wrongZigGimmeAPtr` passes the address to one location into `cGimmeAPtr` and then reads from a different location before returning. On the other hand, `correctZigGimmeAPtr` consistently uses the same location for `ptr`.

I assume that `@ptrCast` only affects type checking and doesn't generate a copy of some sort but maybe I misunderstand 😅

**Comment by Vexu** [comment]
The bug here is that `&@ptrCast(*anyopaque, ptr)` should result in a `*const *anyopaque` not `**anyopaque`.

**Comment by Vexu** [comment]
Works correctly in self-hosted, tested in `test/cases/compile_errors/reference_to_const_data.zig`.
