### ISSUE TITLE
JSON not working

### ISSUE THREAD

**Issue by Sucuturdean** [ziglang/zig#10726]
### Zig Version

0.10.0-dev.461+adea9a176

### Steps to Reproduce

```zig
const file = std.fs.cwd().createFile("Hello.txt", .{.read = true}) catch undefined;
defer file.close();
const stream = std.json.writeStream(std.fs.File.Writer, 5000);
_ = stream;
````

### Expected Behavior

I expected for this program to compile.

### Actual Behavior

It had a compiler error:  
```console
error: parameter of type 'type' must be declared comptime
        pub fn init(stream: OutStream) Self {
```

**Comment by squeek502** [comment]
This is not a bug. You'd be better served by asking questions like this in one of the community spaces: https://github.com/ziglang/zig/wiki/Community
