### ISSUE TITLE
noreturn with an error union causes compiler hang

### ISSUE THREAD

**Issue by e-mm-a** [ziglang/zig#10725]
### Zig Version

0.10.0-dev.62+5b171f446

### Steps to Reproduce

```zig
pub fn main() !noreturn {
    unreachable;
}

```

### Expected Behavior

Since `!noreturn` is invalid, the compiler should produce an error for any function with this return type.

### Actual Behavior

The compiler hangs, and quickly OOMs.

**Comment by Vexu** [comment]
Duplicate of #3461
