### ISSUE TITLE
CMake generates build files incorrectly with space in LLVM path

### ISSUE THREAD

**Issue by Exonorid** [ziglang/zig#10739]
I have my LLVM install (libraries and headers) at the path `C:\Program Files\LLVM`, but when generating the build files, CMake appears to split the path at the space, as visible in the following output:
```
Found llvm: C:\Program;Files\LLVM\lib\LLVMWindowsManifest.lib;C:\Program;Files\LLVM\lib\LLVMXRay.lib /* Truncated */
```

I'm not sure if this is a bug in Zig's CMakeLists or a bug in CMake itself. The problem can be mitigated by moving the LLVM install path or creating a junction so that LLVM is accessible from a path without space in it, but this seems more like a bandaid rather than an actual solution.

I am building on Windows 10 for x86_64 using the Visual Studio generator.

**Comment by andrewrk** [comment]
I'm aware of this issue and I believe it is a cmake bug. There's not really much we can do about it. We're stuck with cmake for bootstrapping the compiler.

**Comment by marler8997** [comment]
Time to write some conversion tools.  CMake/Make/MSBuild/... to "build.zig".  Then the zig toolchain can build any project with only 1 dependency, Zig.

**Comment by andrewrk** [comment]
Two problems with that:

 * we want the bootstrapping path to not include a dependency on zig, by definition.
 * llvm, clang, lld all depend on cmake for the build system, so for an llvm-enabled build of zig, we're still stuck with cmake.

**Comment by marler8997** [comment]
> we want the bootstrapping path to not include a dependency on zig, by definition

Shoot that's right, the bootstrapping path does make us kinda stuck here.

**Comment by andrewrk** [comment]
I'm sorry, I don't think this is a problem we can solve in the Zig project. Best we can do is document the issue in the instructions.
