### ISSUE TITLE
Allow pointers to any struct in extern/exported declarations

### ISSUE THREAD

**Issue by Hejsil** [ziglang/zig#1073]
Currently, the best way of sending none extern structs through a C interface is to use `@OpaqueType`, allocate the struct, and cast the pointers back and forth. I propose that pointers to none extern structs should be allowed in extern declarations:

```rust
pub const S = struct {
    a: u8,
    b: u8
};

pub const SE = extern struct {
    s: *const S,
};

export fn a(ptr: *const SE) u8 {
    return ptr.s.a;
}

export fn b(ptr: *const S) u8 {
    return ptr.b;
}
```

The generated header would look like this:
```c
struct SE {
    struct S *s;
};

export fn a(const struct SE *ptr);
export fn a(const struct S *ptr);
```

This would allow us to avoid `@OpaqueType` and `@ptrCast` in most cases making the interface safer.

**Comment by andrewrk** [comment]
In the generated header it would also have a forward decl of S right?

```c
struct S;
```

**Comment by Hejsil** [comment]
@andrewrk Ooh, yes. It was just as a short example.
