### ISSUE TITLE
Tricky enum leads to unclean exit

### ISSUE THREAD

**Issue by pianofingers** [ziglang/zig#1079]
```
pub const VkResult = extern enum {
    VK_ERROR_OUT_OF_POOL_MEMORY_KHR = VkResult.VK_ERROR_OUT_OF_POOL_MEMORY,
    VK_ERROR_INVALID_EXTERNAL_HANDLE_KHR = VK_ERROR_INVALID_EXTERNAL_HANDLE,
};

pub fn main() void {
    var s : VkResult = VkResult.VK_SUCCESS;
}
```
That's as much as I can reduce it, of course it looks very strange at this point. Note the "VkResult.VK.." in the enum. I'm not expecting the enum to work.

The specific error I get is:

> The following command terminated unexpectedly: .... error: UncleanExit

**Comment by isaachier** [comment]
The issue is an illegal access to a null `name` pointer, causing a segmentation fault. This is one of the cases where not null checking is the main issue (something clang-tidy is very vocal about).
