### ISSUE TITLE
WASM regression: indirect-function-table is not exported

### ISSUE THREAD

**Issue by Deins** [ziglang/zig#10817]
### Zig Version

0.10.0-dev.555+1b6a1e691

### Steps to Reproduce

Code compiled with `zig build -Dtarget=wasm32-freestanding -Drelease-fast`
```zig
// this is implemented in host (js/browser for example)
extern fn registerButtonCallback(callback: *const fn()callconv(.C) void  ) void;

pub export fn click() callconv(.C) void {
  // do stuff in regards of button press
}

// entry point 
pub export fn main() void {
    registerButtonCallback(&click);
 }
```

### Expected Behavior

Produces wasm that has exported indirect function table which can be used from host to call the callback pointer.
zig 9.0 was working and produced the wasm callback table like this:
```wasm
....
(export "__indirect_function_table" (table 0))
....
```
From js I could call the the function like this:
```js
var Module = {
  ptr = 0,
  imports: { env: {
    registerButtonCallback: function(ptr) { Module.ptr = ptr; } 
  }}
}
// fetch, compile and link wasm with given js Module / imports
// ...
Module.instance.exports.main(); // call wasm regular exported function
// ...
// some time later when button is pressed
const cb = Module.instance.exports.__indirect_function_table.get(Module.ptr); 
cb(); // this calls back the wasm part
```

### Actual Behavior

zig-10 generates wasm where the function table looks like this:
```wasm
(table $T0 24 24 funcref)
``` 
Because the table is not exported, it is not possible (as far as I know) to access it and call back from js to wasm.

**Comment by Luukdegram** [comment]
Exporting the indirect function table is no longer done implicitly.
If you desire to export it, you can either pass `--export-table` to `build-lib` or set `lib.export_table = true;` in your `build.zig` file.

**Comment by Deins** [comment]
Yess it works, thanks. 
And sorry, somehow missed this change in commit history.
