### ISSUE TITLE
usingnamespace @cImport gives "use of undeclared identifier" but also hides cImport/cInclude failure

### ISSUE THREAD

**Issue by heretique** [ziglang/zig#10821]
### Zig Version

0.9.0
Windows 11
Installed with Scoop

### Steps to Reproduce

While testing out Zig, I'm trying to use SDL2 and I have a simple `main.zig` file like the following:
```
usingnamespace @cImport({
    @cDefine("SDL_MAIN_HANDLED", {});
    @cInclude("SDL2/SDL.h");
});

pub fn main() !void {
    _ = SDL_Init(0);
    defer SDL_Quit();
}
```
This gives me an error `error: use of undeclared identifier 'SDL_Init'`.
If I did read and understood correctly the `usingnamespace` declaration than it means that I don't need to do something like:
```
const c= @cImport({
    @cDefine("SDL_MAIN_HANDLED", {});
    @cInclude("SDL2/SDL.h");
});

pub fn main() !void {
    _ = c.SDL_Init(0);
    defer c.SDL_Quit();
}
```
which compiles just fine.
But the most interesting behavior is when I try to include a non-existing C header file, for example a typo in the include ` @cInclude("SDL2/SL.h");` with the first code variant. Even if I try to include a wrong file it still give me an `error: use of undeclared identifier 'SDL_Init'`.
Only if I comment out the "problematic" code
```
usingnamespace @cImport({
    @cDefine("SDL_MAIN_HANDLED", {});
    @cInclude("SDL2/SL.h");
});

pub fn main() !void {
    // _ = SDL_Init(0);
    // defer SDL_Quit();
}
```
do I get an error
```
.\src\main.zig:1:16: error: C import failed
usingnamespace @cImport({
               ^
.\zig-cache\o\a5a09c4fce8c314a74669b6569f0f791\cimport.h:2:10: note: 'SDL2/SL.h' file not found
#include <SDL2/SL.h>
         ^
C:\Users\cata\scoop\apps\zig\current\lib\std\builtin.zig:715:5: note: referenced here
    default_panic;
    ^
```
Am I missing something? Is this related somehow to #9774?

### Expected Behavior

If using `usingnamespace` I would expect not need to use a prefix like `c.C_Function` when using imported C headers.
I would also expect to first get an error about file not found when including a C header that is not found before other undefined symbols errors.

### Actual Behavior

Getting undefined symbols error that hide file not found errors when including a C header file.
Also I cannot use C code without a `c.` prefix although I'm using `usingnamespace` when importing C code.

**Comment by ominitay** [comment]
Not a bug. This is not how `usingnamespace` works anymore: you would have to do `@This().SDL_Init(0)`. (I'd also recommend using @MasterQ32's SDL wrapper :)

Related: #9629

**Comment by heretique** [comment]
Thanks @ominitay , but for my understanding (coming from a C++ background), is it than safe to assume that the fact that I didn't got a "file not found" error with the typo in the include is because the imports are done lazily and because I was not using `@This().SDL_Init(0)` but instead  `_ = SDL_Init(0);` the compiler considered the identifier (SDL_Init) not part of the struct that corresponds to the current file so it thrown the "undeclared identifier" first as it didn't need to load the includes yet? 
What a mouthful, does that make sense? 😕

**Comment by ominitay** [comment]
Yep, I think you understand that correctly. My understanding is that `SDL_Init` was not in the current scope, so the compiler threw the undeclared identifier error. The compiler doesn't need to evaluate the `usingnamespace` expression before checking this, as it has no effect on the contents of the current scope.
