### ISSUE TITLE
Improve const-correctness

### ISSUE THREAD

**Issue by elfring** [ziglang/zig#1086]
I suggest to add the key word “const” to the type specifiers for parameters like the following.
- buf (function “[is_zig_keyword](https://github.com/ziglang/zig/blob/652f4bdf6242462182005f4c7149f13beaaa3259/src/tokenizer.hpp#L193)”)
- out_name (function “[codegen_set_out_name](https://github.com/ziglang/zig/blob/688ff2830d82ea36a9f022ecb7cf4c2bf2e4c586/src/codegen.hpp#L30)”)

Would you like to apply the advices from [an article](https://en.wikipedia.org/wiki/Const_%28computer_programming%29#Consequences "Description for const-correctness") to more places in your source files?

**Comment by andrewrk** [comment]
Feel free to create a pull request
