### ISSUE TITLE
Const variables can be left uninitialized

### ISSUE THREAD

**Issue by czrptr** [ziglang/zig#10867]
### Zig Version

0.9.0 (latest commit)

### Steps to Reproduce

This code compiles.
```zig
fn f() bool {
    const a: bool = undefined;
    return a;
}

pub fn main() u8 {
    if (f()) {
        return 0;
    } else {
        return 1;
    }
}
```

### Expected Behavior

The compiler shouldn't let you do this.

### Actual Behavior

It compiles with no errors.

**Comment by InKryption** [comment]
Doesn't really seem like an issue; making it an error to do this would probably just burden generic code. This is effectively just a way of making an alias for a coerced `undefined`.
