### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [ziglang/zig#1087]
I expect that exception handling is usually supported by a C++ program. I wonder why your function “[main](https://github.com/ziglang/zig/blob/688ff2830d82ea36a9f022ecb7cf4c2bf2e4c586/src/main.cpp#L259 "main() function")” does not contain [corresponding try and catch instructions](https://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](https://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://en.cppreference.com/w/cpp/language/try_catch "Description for exception handling")?

**Comment by andrewrk** [comment]
I'm not really interested in suggestions to improve the stage 1 compiler internals unless it's in the form of a pull request.

**Comment by andrewrk** [comment]
I'll repeat what I said in https://github.com/andrewrk/malcheck/issues/1

> Can you be more explicit with what you are suggesting? This Socratic Method thing is less efficient than direct arguments, and it comes off as a bit condescending.

**Comment by bnoordhuis** [comment]
I'm pretty sure @elfring is a bot.  Look at its comment history.  I remember it filing a bunch of similar issues over at libuv/libuv.
