### ISSUE TITLE
Windows build instructions fail if you have windows SDK 10 install

### ISSUE THREAD

**Issue by bheads** [ziglang/zig#1088]
CMAKE will fail to build the VS 2015 project if you also have VS2017 with SDK 10 install.
I add this to the cmake line -DCMAKE_SYSTEM_VERSION=8.1 I think you can add this to the CMakeLists file, or we should update the build wiki.  

Should also update the windows build wiki to note that you need to create a c++ project in VS2015 to get it to install the c++ build tools.

**Comment by andrewrk** [comment]
I'm pretty sure this is fixed now.
