### ISSUE TITLE
`comptime` struct segfaults LLDB

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#10903]
### Zig Version

0.10.0-dev.315+4d05f2ae5

### Steps to Reproduce

Repro repository: https://github.com/Jarred-Sumner/zig-comptime-debug-repro

When using lldb directly, passing a comptime struct to a function causes lldb to crash when a breakpoint is set in a function within the struct returned.

This example reproduces the segfault when used from VSCode LLDB. I'm still figuring out how to repro it with a smaller example outside of the popular [CodeLLDB VSCode extension](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb). In a larger project, it's consistent though (and in LLVM 12  too)

```zig
const std = @import("std");

const Options = struct { name: usize = 99 };

pub fn MyComptimeType(comptime opts: Options) type {
    return struct {
        foo: u32 = 0,
        pub fn print(this: @This()) void {
            _ = opts;
            // Stick the breakpoint on the line below:
            std.mem.doNotOptimizeAway(&this.foo);
        }
    };
}

pub fn main() anyerror!void {
    var ab = Comptime{};
    ab.print();

    var cd = Comptime2{};
    cd.print();
}

const Comptime = MyComptimeType(Options{});
const Comptime2 = MyComptimeType(Options{ .name = 100 });

```

[LLVM IR](https://gist.github.com/Jarred-Sumner/49940fba0f8df246c14a679ad967c6cd)

So that it's shorter, the LLVM IR was built with -OReleaseFast. It reproduces in both -OReleaseFast and debug

LLDB does not crash if there is only one version of the comptime type

### Expected Behavior

lldb works without segfaulting

### Actual Behavior

![Screen Recording 2022-02-15 at 7 04 45 PM](https://user-images.githubusercontent.com/709451/154188410-280b9f58-a12b-41c2-af11-ce9dfa8f44bc.gif)

Here is the crash report on lldb - https://gist.github.com/Jarred-Sumner/cabe5114e804bd1d7a907809af7dcadb

**Comment by Jarred-Sumner** [comment]
Here is an example of a workaround:

```zig
pub fn NewLexer(
    comptime json_options: JSONOptions,
) type {
    return NewLexer_(
        json_options.is_json,
        json_options.allow_comments,
        json_options.allow_trailing_commas,
        json_options.ignore_leading_escape_sequences,
        json_options.ignore_trailing_escape_sequences,
        json_options.json_warn_duplicate_keys,
        json_options.was_originally_macro,
    );
}

fn NewLexer_(
    comptime json_options_is_json: bool,
    comptime json_options_allow_comments: bool,
    comptime json_options_allow_trailing_commas: bool,
    comptime json_options_ignore_leading_escape_sequences: bool,
    comptime json_options_ignore_trailing_escape_sequences: bool,
    comptime json_options_json_warn_duplicate_keys: bool,
    comptime json_options_was_originally_macro: bool,
) type {
    const json_options = JSONOptions{
        .is_json = json_options_is_json,
        .allow_comments = json_options_allow_comments,
        .allow_trailing_commas = json_options_allow_trailing_commas,
        .ignore_leading_escape_sequences = json_options_ignore_leading_escape_sequences,
        .ignore_trailing_escape_sequences = json_options_ignore_trailing_escape_sequences,
        .json_warn_duplicate_keys = json_options_json_warn_duplicate_keys,
        .was_originally_macro = json_options_was_originally_macro,
    };
   return struct {
     // rest of code in here ...
   };
}

**Comment by Vexu** [comment]
Works in self-hosted.
