### ISSUE TITLE
stage1: Building Zig compiler using pre-built zig binary fails due to @bitCast error

### ISSUE THREAD

**Issue by ZapAnton** [ziglang/zig#10918]
### Zig Version

0.10.0-dev.2696+e1a535360

### Steps to Reproduce

```bash
$ git clone git@github.com:ziglang/zig-bootstrap.git
$ cd zig-bootstrap
$ ./build -j1 native-linux-gnu native
$ cd /path/to/zig/source
$ zig build -Dstage1 --zig-lib-dir ./lib/ --search-prefix /path/to/zig-bootstrap/llvm
```

### Expected Behavior

stage1 Zig compiler builds on master branch (ced958e8a) without errors

### Actual Behavior

Following errors interrupt the build process:
 
```bash
./lib/std/math.zig:1505:21: error: destination type 'f80' has 128 bits but source type 'u80' has 80 bits
    return @bitCast(f80, int);
                    ^
./lib/std/math.zig:101:30: note: called from here
pub const qnan_f80 = make_f80(F80{ .fraction = 0xC000000000000000, .exp = 0x7fff });
                             ^
./lib/std/math.zig:101:30: note: called from here
pub const qnan_f80 = make_f80(F80{ .fraction = 0xC000000000000000, .exp = 0x7fff });
                             ^
./lib/std/math.zig:1509:26: error: destination type 'u80' has 80 bits but source type 'f80' has 128 bits
    const int = @bitCast(u80, x);
                         ^
./lib/std/math.zig:1505:21: error: destination type 'f80' has 128 bits but source type 'u80' has 80 bits
    return @bitCast(f80, int);

```

**Comment by Vexu** [comment]
You can't build stage2 using a prebuilt stage1, you have to use whatever `./build` produced.

**Comment by ZapAnton** [comment]
I am actually building stage1, not stage2 using the following instructions:
https://github.com/ziglang/zig/wiki/Building-Zig-From-Source#option-b-use-a-pre-built-zig-binary
Using Zig `0.9.0` built via `./build` produces the same error

**Comment by Vexu** [comment]
Right, so this error happends using `zig` version 0.9.0 produced by `./build`? I have no idea what those directories in the instructions are supposed to be so I can't help regarding that but the error does look like something that would happen if your compiler and the standard library are out of sync.

**Comment by ZapAnton** [comment]
Rebuilding Zig from cpp source removed the above compile errors, thanks!
It still fails with ld errors, but I suspect it is not in scope of this issue.
Will close this one.
