### ISSUE TITLE
[meta] Is the wiki for this project supposed to be editable by anyone?

### ISSUE THREAD

**Issue by mrec** [ziglang/zig#1093]
It feels a bit like asking for trouble, given that you have things like Patreon and binary links, SHA hashes etc on there.

**Comment by andrewrk** [comment]
Yeah it's fine. I keep an eye on the history. Users are expected to use the typical caution they would when using any wiki, such as Wikipedia. Thanks for asking. Feel free to propose an alternative if you think something in particular should be different.
