### ISSUE TITLE
Sharing code across `build.zig` in sibling directories.

### ISSUE THREAD

**Issue by jagt** [ziglang/zig#10939]
### Zig Version

0.9.1

### Steps to Reproduce

I have a project layout roughly like this:

```
root/
├── project1/
│   └── build.zig
├── project2/
│   └── build.zig
└── build_utils.zig
```

Say I want to use `build_utils.zig` in any of the `build.zig`:

```zig
const utils = @import("../build_utils.zig")
```

It would fail with errors like this:

```
.\build.zig:9:15: error: import of file outside package path: '../build_utils.zig'
const utils = @import("../build_utils.zig");
```

Here's a related issue: #2024 . I think one can use `Pkg` to do relative import in zig projects. But I can't find a way to make this work in `build.zig` in a setup like this.

Any suggestions on this? The workaround I'm thinking of is to use `project.json` like stuff to store data and embed them from `build.zig`s. I think sharing code between multiple `build.zig` should be useful for larger projects.

Thanks in advance!

### Expected Behavior

- There should be a way to share code between `build.zig`.

### Actual Behavior

- ATM there's no way to share code between sibling `build.zig`s.

**Comment by ominitay** [comment]
Duplicate of #8025?

**Comment by jagt** [comment]
@ominitay points me to [Florence](https://github.com/FlorenceOS/Florence/blob/master/build.zig) and it has sub `build.zig` which are plain zig files that get imported by the root one. One can not `zig build` in sub projects.

I think this is a solution that I can get by. I think I'll leave this open here for a while to see if there's inputs from others.

**Comment by ominitay** [comment]
Should this be closed?

**Comment by jagt** [comment]
Later I found [zig-gamedev](https://github.com/michal-z/zig-gamedev)'s approach promising and I think I'll go with that. I'm closing this. Thanks for the info!

**Comment by ominitay** [comment]
Iirc a few of us in the discord were discussing this, causing this approach to be taken :)
