### ISSUE TITLE
`std.debug.assert` causes evaluation of expression in release modes

### ISSUE THREAD

**Issue by leecannon** [ziglang/zig#10942]
Rather than a bug this is a question of the intended use of `std.debug.assert`.

One of the things I use assert for is to do expensive validation of state in debug builds expecting it to have no cost in a release build.

However that is not true of `std.debug.assert` as even in release fast the expression is fully evaluated. This is not what `assert` does in c.

## Example in zig

```zig
const std = @import("std");

pub fn main() !void {
    std.debug.assert(expensiveFunction());
}

fn expensiveFunction() bool {
    std.io.getStdOut().writer().print("expensiveFunction ran\n", .{}) catch unreachable;
    return true;
}
```

```
$ zig run example.zig -ODebug
expensiveFunction ran
```

```
$ zig run example.zig -OReleaseFast
expensiveFunction ran
```

## Example in c

```c
#include <assert.h>
#include <stdbool.h>
#include <stdio.h>

bool expensiveFunction(void) {
    printf("expensiveFunction ran\n");
    return true;
}

void main(void) {
    assert(expensiveFunction());
}
```
```
$ zig run example.c -lc -ODebug
expensiveFunction ran
```

```
$ zig run example.c -lc -OReleaseFast
```

**Comment by leecannon** [comment]
Even when trying to force zig to have similar behaviour to c with something like the below it still causes the expression to be fully evaluated in release modes.

```zig
pub inline fn myAssert(ok: bool) void {
    if (builtin.mode != .Debug) return;
    if (!ok) unreachable; // assertion failure
}
```

I don't think there is anyway in the language to get this behaviour without wrapping the call site in a block:

```zig
if (builtin.mode == .Debug) {
    std.debug.assert(expensiveFunction());
}
```

**Comment by matu3ba** [comment]
@leecannon 
1. Your code does not compile for me. I used this one and can confirm the behavior for 1. ReleaseSafe, ReleaseSmall, ReleasFast and Debug independent of `@setRuntimeSafety(false)`
```zig
const std = @import("std");
pub fn main() !void {
    //@setRuntimeSafety(false);
    std.debug.assert(try expensiveFunction());
}
fn expensiveFunction() !bool {
    const stdout = std.io.getStdOut().writer();
    try stdout.writeAll("expensiveFunction ran\n");
    return true;
}
```
Shell:
```sh
zig build-exe -OReleaseSmall assert.zig && ./assert
zig build-exe -OReleaseFast assert.zig && ./assert
zig build-exe -OReleaseSafe assert.zig && ./assert
zig build-exe -ODebug assert.zig && ./assert
```

**Comment by leecannon** [comment]
Oh yea sorry about that I switched from `std.debug.print` to `getStdOut` to make the observed affect of the zig and c (writng to stdout instead of stderr) the same but forgot to handle the error. I've modifed the original code to `catch unreachable`

**Comment by matu3ba** [comment]
The behavior exists since at least 877a1f2a2986e02269c64a05456dff521da27ac1 (December 15th).

**Comment by matu3ba** [comment]
@leecannon I think the behavior is intended, as only the `false` branch is optimized away.
However, from a C developer perspective the behavior is unexpected, since `assert` is a conditional macro and no performance+safety annotation of `unreachability`.

From my point of view, it would be nice to mention this is in some sort of "surprisingly different than C" documentation.

**Comment by leecannon** [comment]
@Vexu even if assert is marked inline and a check of the build mode is added as my comment above, which should prevent zig from generating the llvm ir for the call to print completely, this still causes the expression to be fully evaluated.

Maybe stage2's inline implementation would do this differently but currently it seems that only a builtin could get the behaviour I would want.

**Comment by Vexu** [comment]
Only thing making assert inline does is move the inline the check which LLVM can already do, as I said, the issue is with LLVM not being able to remove syscalls and calls to extern functions which is where the builtin would step in.

**Comment by leecannon** [comment]
@Vexu yea sorry about that 😅. I walked away from the computer than realised that comment I made was dumb, the syscall isn't on assert so why would the check there change anything :sweat_smile:

**Comment by ifreund** [comment]
I think trying to mach C's assert is exactly what we should NOT do. I've seen many bugs caused by putting expressions with side affects inside the assert macro. Macros suck.

**Comment by ifreund** [comment]
As I understand things, this issue can be summarized as "I called a function with side effects (printing to stdout) and it worked even though I passed the return value to assert." I don't think there's anything Zig should change here.

**Comment by squeek502** [comment]
There's at least one place in the standard library that seems to rely on the current behavior (perhaps incorrectly?):

https://github.com/ziglang/zig/blob/e5c30eef1f338ed65325ddbfd4d631baef0d9b81/lib/std/unicode.zig#L559-L564
