### ISSUE TITLE
Optional "lib" prefixes on build.zig

### ISSUE THREAD

**Issue by lun-4** [ziglang/zig#10956]
The title is self-explanatory, but here's the real world use cases that led me to opening the issue:
 - [LÖVR](https://lovr.org)'s plugin loader does not account for lib prefixes by default, so I have to write `require "libsomething"` rather than `require "something"`, even though the latter is the "practical default" across the lua ecosystem of native libraries.
 - Counter-Strike 1.6 server plugins are also not using the lib prefix, requiring your configuration file to needlessly add it.
 - PAM uses a different prefix entirely: `pam_` (see `/lib/security`)

This can be done without a direct `build.zig` enhancement, as seen [here](https://github.com/ifreund/rundird/blob/ce7c8f85f92a737baf5cbe28e2355299c66d7a08/build.zig#L41-L63), but I think we could add this as a configuration parameter since it's a common thing to do.

I don't know which would be the most ergonomic way to set a different prefix inside the build script, my suggestion is some `setLibPrefix(prefix: []const u8)`. Here's an example:

```zig
    const lib = b.addSharedLibrary("rtsp", "src/main.zig", b.version(0, 0, 1));
    lib.setTarget(target);
    lib.setBuildMode(mode);
    lib.setLibPrefix("");
    lib.install();
```

Or, for a PAM library:

```zig
    const lib = b.addSharedLibrary("seven_factor_authentication", "src/main.zig", b.version(0, 0, 1));
    lib.setTarget(target);
    lib.setBuildMode(mode);
    lib.setLibPrefix("pam_");
    lib.install();
```

**Comment by daurnimator** [comment]
Duplicate of https://github.com/ziglang/zig/issues/2231 ?

**Comment by lun-4** [comment]
Oops, it is.
