### ISSUE TITLE
comptime field of struct cannot be set with literal constructor

### ISSUE THREAD

**Issue by locriacyber** [ziglang/zig#10960]
### Zig Version

0.10.0-dev.874+a4df443f9

### Steps to Reproduce

Compile the following code.
```
const std = @import("std");

const Foo = struct {
    comptime a: i32 = 42,
    b: i32,
};
pub fn main() anyerror!void {
    var foo: Foo = Foo{.a=10,.b=20};
    //foo.a = 30; // cannot assign to constant
    std.log.info("foo.a={}", .{foo.a});
}
```

### Expected Behavior

```
info: foo.a=10
```

or the above code shouldn't compile at all.

### Actual Behavior

```
info: foo.a=42
```

**Comment by Vexu** [comment]
Works in self-hosted, tested in `test/cases/compile_errors/invalid_store_to_comptime_field.zig`.
