### ISSUE TITLE
stage1 assertion failure in `analyze.cpp` in `get_llvm_di_type`

### ISSUE THREAD

**Issue by rohlem** [ziglang/zig#10987]
### Zig Version

0.10.0-dev.965+e06cb3165

### Steps to Reproduce

I've minimized the assertion failure to this `main.zig` code:
```zig
const used = struct {};
fn Recursive(comptime recur: bool) void {
    if (recur) {
        return Recursive(false);
    }
    const flag = false;
    _ = struct {
        field: if (flag) u32 else u32,
        const looked = (void == void);
        usingnamespace if (looked) used else used;
    };
}
comptime {
    Recursive(true);
}
pub fn main() void {}
```

It seems this incarnation of the bug depends on all three elements:
- The function must be recursive - putting the prologue into a proxy function solves the assertion failure.
- The field must have a type expression dependent on a constant (`flag`) declared within the recursive function,
  but outside of the struct to trigger the assertion failure.
  (actual result type doesn't matter, may be any sized type or `void`,
   though the compiler does complain about `undefined` in the taken branch)
- The `usingnamespace` statement must depend on a constant (`used`) declared within this struct that depends on
  a type expression (comparison, `@sizeOf`, or for container types `@hasDecl`, `@hasField`, or accessing a constant)
  to trigger the assertion failure.
  (Again, the particular result type doesn't matter, but invalid types and undefined are detected correctly.)

### Expected Behavior

I expected the code to either compile correctly, or the compiler to provide a sensible error message.

### Actual Behavior

The compiler crashes with the message
```
Assertion failed at D:\a\1\s\src\stage1\analyze.cpp:9941 in get_llvm_di_type. This is a bug in the Zig compiler.
```
(No stack trace since I'm using a build from `ziglang.org/download/`.)

---

The particular source code assertion is
```c++
assertNoError(type_resolve(g, type, ResolveStatusLLVMFull));
```

The original occurrence of the error was in a giant project, where I suspected that stage1 messed up lazy value semantics and failed to detect recursion somewhere.
Looking at the minimized example though, it seems more like it might confuse something between the first (`recur=true`) and second instantiation of the recursive function.

Either way, it'll probably work in stage2, but I would of course still appreciate if someone provided a fix before then.
(This was pretty nasty to track down, and I still haven't worked around it in the original project, although at least now I have a better idea of what to look for.)

**Comment by Vexu** [comment]
Works in self-hosted.
