### ISSUE TITLE
doc/langref: add an example of pointer arithmetic

### ISSUE THREAD

**Issue by perillo** [ziglang/zig#10995]
The language reference documents that `many-item pointer to unknown number of items` supports pointer arithmetic, but there are no examples.

This is a possible example, adapted from the "basic slices" test:
```zig
const expect = @import("std").testing.expect;

test "pointer arithmetic" {
    var array = [_]i32{ 1, 2, 3, 4 };
    var length: usize = 0;
    var slice = array[length..array.len];

    try expect(slice[0] == 1);
    slice.ptr += 1;
    try expect(slice[0] == 2);
}
```

Thanks.

**Comment by matu3ba** [comment]
@perillo Just add a PR.

**Comment by ehaas** [comment]
@perillo For the example it would be better to assign `slice.ptr` to a `[*]i32` variable and increment that - directly incrementing `slice.ptr` as you've done will corrupt the slice, since `slice.len` will no longer be correct.

```zig
const expect = @import("std").testing.expect;

test "pointer arithmetic" {
    const array = [_]i32{ 1, 2, 3, 4 };
    var pointer_to_many: [*]const i32 = &array;

    try expect(pointer_to_many[0] == 1);
    pointer_to_many += 1;
    try expect(pointer_to_many[0] == 2);
}
```

**Comment by perillo** [comment]
@ehaas Thank you for the advice.

Here is the updated example, using both a slice and a many-item pointer:

```zig
const std = @import("std");
const testing = std.testing;

test "pointer arithmetic with slices" {
    var array = [_]i32{ 1, 2, 3, 4 };
    var length: usize = 0;
    var slice = array[length..array.len];

    try testing.expect(slice[0] == 1);
    try testing.expect(slice.len == 4);

    slice.ptr += 1;
    // now the slice is in an bad state since len has not been updated

    try testing.expect(slice[0] == 2);
    try testing.expect(slice.len == 4);
}

test "pointer arithmetic with many-item pointer" {
    const array = [_]i32{ 1, 2, 3, 4 };
    var ptr: [*]const i32 = &array;

    try testing.expect(ptr[0] == 1);
    ptr += 1;
    try testing.expect(ptr[0] == 2);
}
```

The official documentation should also document the problem of pointer arithmetic with a slice.

**Comment by ehaas** [comment]
@perillo if you're able to, I'd recommend making a PR so the wider community can review it and give feedback. If you edit `langref.html.in` and then run `zig build docs` you'll get `zig-cache/langref.html`
