### ISSUE TITLE
stage2 doesn't actually analyze function on `ensureDeclAnalyzed` breaking inferred error sets

### ISSUE THREAD

**Issue by Vexu** [ziglang/zig#11046]
`resolveInferredErrorSet` calls `ensureDeclAnalyzed` assuming that it will analyze the function but that doesn't happen until later when the `codegen` job is run leaving the inferred error set empty.
```zig
fn foo() !void {
    var a = true;
    if (a) return error.Foo;
    return error.Bar;
}
fn bar() !void {
    try foo();
}
test {
    bar() catch |err| switch (err) {
        error.Foo => {}, // error: expected (inferred error set of bar), found error{Foo}
        error.Bar => {},
    };
}
```

**Comment by mitchellh** [comment]
Once this is fixed, behavior test in `error.zig` "return result loc as peer result..." should pass.
