### ISSUE TITLE
"no-entry" argument not recognized

### ISSUE THREAD

**Issue by danielchasehooper** [ziglang/zig#11045]
### Zig Version

0.10.0-dev.871+bb05a8a08

### Steps to Reproduce

run this:

```
echo "int add(int a,int b){return a+b;}" > main.c
zig cc main.c -target wasm32-freestanding-none -nostdlib -o binary.wasm -Wl,--no-entry
```

### Expected Behavior

should compile without issue

### Actual Behavior

output:
```
warning: unsupported linker arg: --no-entry
wasm-ld: error: entry symbol not defined (pass --no-entry to suppress): _start
```

similarly, if you run
`zig cc main.c -target wasm32-freestanding-none -nostdlib -o binary.wasm --no-entry`
you get
`error: Unknown Clang option: '--no-entry'`

so whether you pass the argument to zig cc with `--no-entry` or the linker with `-Wl,--no-entry`, it doesn't work

**Comment by matu3ba** [comment]
Note `--no-entry` is a wasm-specific option: https://github.com/llvm/llvm-project/blob/main/lld/docs/WebAssembly.rst#usage

**Comment by Luukdegram** [comment]
Linking my comment from the PR here for visibility:
https://github.com/ziglang/zig/issues/11742#issuecomment-1140243360

As mentioned, the solution is to build a library, rather than an executable.

**Comment by danielchasehooper** [comment]
@Luukdegram If the ship has sailed on flag compatibility with clang then it something must be done to address the usability of this situation.

Either 
1. `wasm-ld: error: entry symbol not defined (pass --no-entry to suppress): _start` should be changed to `wasm-ld: error: entry symbol not defined (pass -shared to suppress): _start`
2. or zig cc should detect the `--no-entry` linker flag and tell you it to use `-shared` instead. This way even if the wasm-ld error message isn't changed, people will get directed to do the right thing.

**Comment by williamstein** [comment]
I might have been stuck for hours on this exact problem if I had not found this ticket via Google, and learning that I just need to add the -shared option.  Thanks.

**Comment by theoparis** [comment]
I'm still stuck on this for compiling c **libraries** to wasm32-wasi, and with cmake there doesn't seem to be an easy fix because using wasm-ld  directly causes more issues. This argument is required to build libraries for wasm32-wasi because without it, it errors saying main isn't defined 😕 

It seems like this is where the error occurs: https://github.com/ziglang/zig/blob/6bc9c4f716afbb15465f79f84f61221f394fa5b6/src/main.zig#L2224

However I have no idea what the correct fix would be.
