### ISSUE TITLE
Proposal: std.meta package

### ISSUE THREAD

**Issue by alexnask** [ziglang/zig#1104]
This is a proposal for a standard library package that I originally intended to write along with the @typeInfo implementation.  

In my opinion, it should be introduced along with @reify/@makeType and the removal of the current metaprogramming builtins.  

It should be a high level interface that simplifies metaprogramming (especially reflection) by removing the need to manually use @typeInfo in metaprograms.  

All current builtins like @typeId, @ArgType, @memberCount, @memberName, @memberType, as well as special fields of types (.Child, .ReturnType  etc.) should be replaced by functions in this package.  

In addition to that, functions like 'type_has_self_method', 'type_has_method' should be available.  

Some kind of 'type builder' could also be provided to simplify the usage of @reify/@makeType.  

I will be proposing an API soon™ but I would love to see suggestions from anyone that uses metaprogramming features and/or may have written a similar package for use in their projects.

**Comment by Hejsil** [comment]
I've already done some work on this front on the [std-meta](https://github.com/ziglang/zig/blob/std-meta-rebased/std/meta.zig) branch. Sadly, I hit a roadblock when trying to remove `@typeId`, and haven't worked on it since.

**Comment by tgschultz** [comment]
Somewhat related, I think `TypeInfo` should be changed slightly, to accommodate the removal of `@typeName`:

```
pub const TypeInfo = union(TypeId) {
    Type: void,
    Void: void,
    Bool: void,
    NoReturn: void,
    Int: Int,
//.....
```
=>
```
pub const TypeInfo = struct
{
    Type: type,
    name: []const u8,
    info: Info,

    pub const Info = union(TypeId) {
        Type: void,
        Void: void,
        Bool: void,
        NoReturn: void,
        Int: Int,
//.....
```

**Comment by thejoshwolfe** [comment]
Everything in package `std` should be implemented in pure Zig. If `std.meta` would require special treatment from the Zig compiler, then `std` is the wrong place for it.

Zig uses `@` prefixed builtin functions for functionality that cannot be implemented in pure Zig.

**Comment by thejoshwolfe** [comment]
We could certainly reduce the number of builtins related to reflection, and maybe do everything through `@typeInfo()`, but the standard library is not the place for those functions.

For `@reify()`/`@makeType`, see #383.

**Comment by andrewrk** [comment]
@thejoshwolfe what are you responding to?

**Comment by thejoshwolfe** [comment]
Sorry. I misunderstood. The proposal is to remove redundant builtins and implement their functionality using `@typeInfo()`. That makes sense. I thought we were proposing implementing `@typeInfo()` in std.

**Comment by bheads** [comment]
[I have been working on some of this as well](https://gitlab.com/bheads/zig-util-lib/blob/master/src/meta.zig)
 but havn't gotten as far as I wanted. But I ran into issue with get signatures to generic functions. The type turns all comptimes in var, which makes it hard to do reflection.

**Comment by tgschultz** [comment]
I ran into that when implementing[ custom formatter support in std.fmt](https://github.com/ziglang/zig/pull/1029/commits/8fc52a94f46295ee821708c44a165803207e85a6#diff-c1352127287cefecf28b7ec2a2816838R151) too. 

It also seemed that even though `@compileLog(FnTypeFromTypeInfo)` and `@compileLog(TargetType)` produced identical output that `FnTypeFromTypeInfo != TargetType`. But I'm unsure if that isn't just because there's something I'm missing about how it should work.

**Comment by andrewrk** [comment]
I would recommend starting based on my rebase of @Hejsil's work: `std-meta-rebased`

The commit "tried to remove typeid builtin" (1e78b634b456bf25d17755ff5e9179116cc44cbf) has a mysterious bug that we haven't figured out, but if you remove that commit, I believe all tests pass, and most of the work proposed here is done.

**Comment by andrewrk** [comment]
This is done; we have std.meta now.
