### ISSUE TITLE
Disallow optional of optionals

### ISSUE THREAD

**Issue by PastMoments** [ziglang/zig#11051]
Godbolt: https://godbolt.org/z/7vfjYMfWP

```zig

const std = @import("std");

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    const a = 15;
    var one_optional: ?u32 = a;
    var two_optional: ??u32 = one_optional;
    var three_optional: ???u32 = two_optional;
    var four_optional: ????u32 = three_optional;
    
    var b: u32 = four_optional.?.?.?.?;

    try stdout.print("Hello, {d}!\n", .{b});
    try stdout.print("Hello, {d}!\n", .{four_optional});
}
```
The above code compiles and runs.
Note that `?T` coerces to `??T`, but `T` does not coerce to `??T`.

This is more of a toe-stub than a foot-gun, but there doesn't seem to be a use case for optional of optionals, so it makes sense to disallow it.

**Comment by andrewrk** [comment]
> Thank you for your interest in improving the Zig language. However, we are
> not accepting new proposals to change the language at this time.
