### ISSUE TITLE
Code following a `noreturn` function does not throw an "unreachable code" compile error

### ISSUE THREAD

**Issue by gpanders** [ziglang/zig#11073]
### Zig Version

0.10.0-dev.974+bf6540ce5

### Steps to Reproduce

Compile the following program:

```zig
const std = @import("std");

fn foo() noreturn {
    @panic("oops");
}

pub fn main() !void {
    foo();

    const x = 4;
    std.debug.print("x is {}\n", .{x});
}
```

### Expected Behavior

The compiler should throw an "unreachable code" error for the code following the call to `foo()`, since `foo` is labeled `noreturn`.

### Actual Behavior

The code compiles with no error.

**Comment by andrewrk** [comment]
Related: #10420

**Comment by nektro** [comment]
could this not be implemented in sema?
