### ISSUE TITLE
stage1: unclear error message of variables inside struct

### ISSUE THREAD

**Issue by matu3ba** [ziglang/zig#11075]
### Zig Version

0.10.0-dev.1166+c7e4c711f

### Steps to Reproduce

`zig build-exe struct.zig`

File `struct.zig`
```zig
const Flags123 = struct {
    var write_file: ?[]u8 = null;
};

pub fn main() !void {
    var flags = Flags123{};
    _ = flags;
}
```

### Expected Behavior

no successful compilation with parser error

### Actual Behavior

successful compilation

**Comment by Vexu** [comment]
What exactly is supposed to be wrong with this?

**Comment by matu3ba** [comment]
`var write_file: ?[]u8 = null;` is wrong. It must be `write_file: ?[]u8 = null;`.
`write_flag` is also not accessible, ie
```zig
const Flags123 = struct {
    var write_file: ?[]u8 = null;
};

pub fn main() !void {
    var flags = Flags123{};
    _ = flags;
    flags.write_file = null;
}
```
returns
```txt
!zig build-exe structs.zig
./structs.zig:8:10: error: no member named 'write_file' in struct 'Flags123'
    flags.write_file = null;
         ^
```

**Comment by Vexu** [comment]
You are allowed to have variables in structs, you can only access them through the type itself not instances of it.
```zig
const Flags123 = struct {
    var write_file: ?[]u8 = null; // namespaced variable
    write_file: ?[]u8 = null, // struct field
};
pub fn main() !void {
    var flags = Flags123{};
    Flags123.write_file = null; // setting the variable
    flags.write_file = null; // setting a field in an instance of the type
}
```

**Comment by matu3ba** [comment]
Ah, my bad then. Then only the error message could be seen as unclear, since it is not clarify the difference between struct instance or the namespace.

**Comment by ominitay** [comment]
The error message is correct and behaviour is correct. I don't see a problem here.
