### ISSUE TITLE
populate table with undeclared identifiers

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#111]
One of zig's goals is to solve the "only the first compile error is useful" problem. So when "undeclared identifier" error happens, put the identifier in a table with the type set to the poison value. So there should only be 1 "undeclared identifier" error for each undeclared identifier.

**Comment by PavelVozenilek** [comment]
Is this really worth the effort? I never watch past the first error in C++ implementations which have decades of code inside. Large number of errors actually annoys me, I need to scroll to find the first one and mentally separate it from the rest. 

Exception to this is the same error over and over, like renamed item not resolved in many places.

**Comment by andrewrk** [comment]
> Large number of errors actually annoys me, I need to scroll to find the first one and mentally separate it from the rest.

This is exactly the thing this would solve. So you would only get 1 instance of "use of undeclared identifier 'foo'". Then foo would be an identifier with the poison value, so anything that referenced it also got the poison value.

The poison value silences error messages.
