### ISSUE TITLE
2 spaces for `zig fmt` instead of 4 

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#11107]
When writing Zig, it's common to have deeply nested switch statements and/or scopes

With 4 spaces, that means you need a wide screen to read the code

```zig
        .fn_proto_simple,
        .fn_proto_multi,
        .fn_proto_one,
        .fn_proto,
        => {
            // Extern function prototypes are parsed as these tags.
            // Go back to the first token we should render here.
            const fn_token = main_tokens[decl];
            var i = fn_token;
            while (i > 0) {
                i -= 1;
                switch (token_tags[i]) {
                    .keyword_extern,
                    .keyword_export,
                    .keyword_pub,
                    .string_literal,
                    .keyword_inline,
                    .keyword_noinline,
                    => continue,

                    else => {
                        i += 1;
                        break;
                    },
                }
            }
            while (i < fn_token) : (i += 1) {
                try renderToken(ais, tree, i, .space);
            }
            try renderExpression(gpa, ais, tree, decl, .none);
            return renderToken(ais, tree, tree.lastToken(decl) + 1, space); // semicolon
        },
```

If `zig fmt` was modified to print 2 spaces instead of four, that now looks like this:

```zig
    .fn_proto_simple,
    .fn_proto_multi,
    .fn_proto_one,
    .fn_proto,
    => {
      // Extern function prototypes are parsed as these tags.
      // Go back to the first token we should render here.
      const fn_token = main_tokens[decl];
      var i = fn_token;
      while (i > 0) {
        i -= 1;
        switch (token_tags[i]) {
          .keyword_extern,
          .keyword_export,
          .keyword_pub,
          .string_literal,
          .keyword_inline,
          .keyword_noinline,
          => continue,

          else => {
            i += 1;
            break;
          },
        }
      }
      while (i < fn_token) : (i += 1) {
        try renderToken(ais, tree, i, .space);
      }
      try renderExpression(gpa, ais, tree, decl, .none);
      return renderToken(ais, tree, tree.lastToken(decl) + 1, space); // semicolon
    },
```

If anyone's curious to try themselves, this is (mostly) the line to change in `zig fmt`:
https://github.com/ziglang/zig/blob/3bbe6a28e069b03c8a9185dd14129517453e26d2/lib/std/zig/render.zig#L9

The above code is here https://github.com/ziglang/zig/blob/3bbe6a28e069b03c8a9185dd14129517453e26d2/lib/std/zig/render.zig#L102

If you don't think this is worth considering, feel free to just close the issue

**Comment by BanchouBoo** [comment]
I vote 3!

**Comment by tnodir** [comment]
When the Zig lang will be added to [CodeScene](https://codescene.io), then such deeply nested switch statements will be marked as low healthy code by CodeScene's metrics.

**Comment by deftclaw** [comment]
If the zig team is going to [dictate](https://ziggit.dev/t/zig-fmt-with-2-spaces-indentation/4431) a spec it should be tabs (which editors can change the view of) not 4 spaces, which no one wants. I consider 2 spaces sane (for reasons mentioned above) and nutjobs want 8 (linux kernel spec, if you can't tell 2 spaces is an indent... get some glasses or turn up your sizing)

only psycho pythonists want 4 spaces `\t` can at least be mapped to editor's default settings.

**Comment by andrewrk** [comment]
Zig core team may decide to change things in the future but we've heard everything under the sun there is to be said about this topic, no more input is needed
