### ISSUE TITLE
doc/langref: document void literals

### ISSUE THREAD

**Issue by perillo** [ziglang/zig#11112]
Looking at the `std` code, it seems that the void literal is `void{}`.

I think the documentation should have a `Void Literals` section, since this is not documented.
I found it when I was playing with the syntax and later found some examples in the `std`.

**Comment by perillo** [comment]
There is actually an example in the documentation, in https://ziglang.org/documentation/master/#Zero-Bit-Types

```zig
var x: void = {}
```

However
```zig
var x = u0{}
```
is not allowed.

**Comment by Vexu** [comment]
`{}` is an empty block which happens to have type `void`, `void{}` is a void literal.

**Comment by perillo** [comment]
@Vexu Thanks.

I think this should be documented in https://ziglang.org/documentation/master/#blocks, because the current documentation only says that:
Blocks are expressions. When labeled, break can be used to return a value from the block.

So, IMHO, it is not evident that a block happens to have type void (well, probably it is, since a block is an expression).
