### ISSUE TITLE
switch on an extern enum with negative value leads to OOM crash

### ISSUE THREAD

**Issue by pianofingers** [ziglang/zig#1111]
```
const Foo = extern enum {
    Bar = -1,
};

pub fn main() void {
    const v = Foo.Bar;

    switch(v) {
    Foo.Bar => return,
    else => return,
    }
}
```
This leads to an infinite loop and then an out of memory error ("allocation failure").

**Comment by isaachier** [comment]
It seems this line should check for greater than or equal to: https://github.com/ziglang/zig/blob/master/src/ir.cpp#L18450.
