### ISSUE TITLE
stage2: comptime-expected call is forcing runtime

### ISSUE THREAD

**Issue by mitchellh** [ziglang/zig#11124]
The code below runs at comptime in stage1, but forces runtime in stage2. If you wrap it in a `comptime` block it works fine.

This is causing `std.mem` failures in stage2.

@andrewrk I suspect this is also the cause of the runtime-not-comptime failures in the error behavior tests that I pointed out last week.

```zig
test {
    // note if call zeroPrim with `comptime zeroPrim`, this works.
    _ = [_]u8{zeroPrim(u8)} ** 4;
}

fn zeroPrim(comptime T: type) T {
    return @as(T, 0);
}
```

**Comment by Vexu** [comment]
It's not forced to be runtime, function calls by default are runtime unless they have to be run at comptime, which in this case they no longer have to in stage2 as per accepted proposal #7147.

**Comment by mitchellh** [comment]
Ah hah, thanks! :)

**Comment by Vexu** [comment]
> comptime-detection seemed to be a way the stage1 compiler made Zig code faster without programmer overhead, because if it could determine a function could run at comptime, it would do it. For stage2, is the expectation that it is now a programmer burden to label all calls with `comptime`?

Stage1 and stage2 both only run functions at comptime if they are explicitly market so, if the function type requires it or if the scope in which the function is in requires it (container-level, type expression, etc).
