### ISSUE TITLE
m68k backend is crashing with segfault

### ISSUE THREAD

**Issue by ikskuh** [ziglang/zig#11132]
### Zig Version

0.10.0-dev.1261+6f986298c

### Steps to Reproduce

```sh-session
[felix@denkplatte-v2 e45fca2d]$ touch empty.zig
[felix@denkplatte-v2 e45fca2d]$ zig build-obj -fno-emit-bin -target m68k-freestanding empty.zig
Segmentation fault
exit code: 139
[felix@denkplatte-v2 e45fca2d]$
```

### Expected Behavior

The code should've build an object file

### Actual Behavior

A segmentation fault happens

**Comment by mlarouche** [comment]
LLVM codebase only support m68k st the compilation stage at the moment, LLD does not support m68k in their ELF module, you should check again at next LLVM update

**Comment by MasterQ32** [comment]
I want to tackle that at one point. It should be a managable amount of work on the selfhosted compiler

**Comment by ziggekatten** [comment]
> 

Spent the afternoon trying to find the flag for building zig. My LLVM (15) is now built with m68k support, and can compile and run m68k code in qemu. I'm no LLLV/cmake/make/gcc wizard, and trying to find the various option is a pain really. Do i need to modify a cmake/makefile, or are there some cmake parameter here that I'm missing?

**Comment by nektro** [comment]
`./build/stage3/bin/zig build -Dllvm_has_m68k -Dno-lib`, there's no cmake option currently

**Comment by alexrp** [comment]
The original crash here no longer reproduces.
