### ISSUE TITLE
Function only called at comptime is emitted to binary

### ISSUE THREAD

**Issue by Vexu** [ziglang/zig#11152]
Both stage1 and stage2 will emit an error for `foo` because they try to emit is as a runtime function even though it is only ever used at comptime.
```zig
fn foo() void {
    var a = false;
    if (a) @compileError("analyzed as runtime");
}
comptime {
    _ = foo();
}
```

**Comment by andrewrk** [comment]
Duplicate of #6256.

Related:
 * #425
 * #7772
