### ISSUE TITLE
stage2: array-like tuple initialization gets LLVM verification panic

### ISSUE THREAD

**Issue by mitchellh** [ziglang/zig#11159]
```
test {
    const T = @TypeOf(.{ @as(i32, 0), @as(u32, 0) });
    var a: T = .{ -1234, 5678 };
    _ = a;
}
```

result:

```
Stored value type does not match pointer operand type!
  store i32 -1234, i8* getelementptr inbounds (i8, i8* inttoptr (i64 -6148914691236517206 to i8*), i64 1), align 4, !dbg !647
 i32Stored value type does not match pointer operand type!
  store i32 5678, i8* getelementptr inbounds (i8, i8* inttoptr (i64 -6148914691236517206 to i8*), i64 1), align 4, !dbg !647
 i32
thread 711227 panic: LLVM module verification failed
```

Works on stage1.

**Comment by topolarity** [comment]
Based on inspecting the AIR, looks like the bug here is that either Sema needs to avoid generating a store to a comptime field, or that the LLVM backend needs to not generate a store when the target has no runtime bits.

**Comment by mitchellh** [comment]
Note, as @topolarity pointed out, this doesn't actually _work_ on stage1, but it has no error.

In stage1, both `a[0]` and `a[1]` are set to 0. 

However, an LLVM module verification panic is probably not the desired outcome in stage2 regardless of correct behavior. :)

**Comment by topolarity** [comment]
That's me :-) 

This does actually work on stage1, but the test case above just happens to overlap with #11162. Here's one that doesn't:
```zig
test {
    const T = @TypeOf(.{ @as(i32, -1234), @as(u32, 5678) });
    var a: T = .{ -1234, 5678 };
    _ = a;
}
```
This works correctly on stage1 but panics on stage2, because of an AIR store to a comptime field:
```zig
  %16 = constant(i32, -1234)
...
  %10 = alloc(*tuple{comptime i32 = -1234, comptime u32 = 5678})
  %13 = struct_field_ptr_index_0(*i32, %10)
  %17!= store(%13!, %16!)
```

I think the bug is that Sema should not be generating that store of an `i32` to a `comptime` field.
