### ISSUE TITLE
stage2: `zig run hello.c -lc` spews a lot of errors about missing glibc headers

### ISSUE THREAD

**Issue by mitchellh** [ziglang/zig#11168]
### Zig Version

0.10.0-dev.1311+5ea94e771

### Steps to Reproduce

**`hello.c`**:

```c
void main {}
```

Then run `zig run hello.c -lc` with the stage2-built compiler.

### Expected Behavior

Exit code 0.

### Actual Behavior

A lot of errors about missing headers. See the full output below.

Potentially relevant details:
* I'm on aarch64_linux.
* Master-built stage1 `zig` does not have these same errors.

<details><summary>Toggle for full error output</summary>
<pre>
error(compilation): clang failed with stderr: In file included from <built-in>:370:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/sysdeps/aarch64/crti.S:1:1: unable to build C object: clang exited with code 1
error(compilation): clang failed with stderr: /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/sysdeps/aarch64/crtn.S:40:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/sysdep.h': No such file or directory

error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/sysdeps/aarch64/crtn.S:1:1: unable to build C object: clang exited with code 1
error(compilation): clang failed with stderr: /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/csu/abi-note.S:56:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/csu/config.h': No such file or directory

error(compilation): clang failed with stderr: In file included from <built-in>:372:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/csu/abi-note.S:1:1: unable to build C object: clang exited with code 1
error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/sysdeps/aarch64/start-2.33.S:1:1: unable to build C object: clang exited with code 1
error(compilation): clang failed with stderr: In file included from <built-in>:2:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): clang failed with stderr: In file included from <built-in>:2:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): clang failed with stderr: In file included from <built-in>:2:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): clang failed with stderr: In file included from <built-in>:2:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): clang failed with stderr: In file included from <built-in>:2:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): clang failed with stderr: In file included from <built-in>:2:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): clang failed with stderr: In file included from <built-in>:2:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): clang failed with stderr: In file included from <built-in>:2:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): clang failed with stderr: In file included from <built-in>:2:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): clang failed with stderr: In file included from <built-in>:2:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): clang failed with stderr: In file included from <built-in>:2:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): clang failed with stderr: In file included from <built-in>:2:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): clang failed with stderr: In file included from <built-in>:2:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): clang failed with stderr: In file included from <built-in>:2:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): clang failed with stderr: In file included from <built-in>:2:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): clang failed with stderr: In file included from <built-in>:2:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): clang failed with stderr: In file included from <built-in>:2:
/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symbols.h:88:10: fatal error: cannot open file '/home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/include/libc-symver.h': No such file or directory

error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/sysdeps/unix/sysv/linux/stat_t64_cp.c:1:1: unable to build C object: clang exited with code 1
error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/io/mknod.c:1:1: unable to build C object: clang exited with code 1
error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/sysdeps/unix/sysv/linux/mknodat.c:1:1: unable to build C object: clang exited with code 1
error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/sysdeps/unix/sysv/linux/fstatat.c:1:1: unable to build C object: clang exited with code 1
error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/sysdeps/unix/sysv/linux/fstatat64.c:1:1: unable to build C object: clang exited with code 1
error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/sysdeps/unix/sysv/linux/lstat64.c:1:1: unable to build C object: clang exited with code 1
error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/sysdeps/unix/sysv/linux/fstat64.c:1:1: unable to build C object: clang exited with code 1
error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/sysdeps/unix/sysv/linux/stat64.c:1:1: unable to build C object: clang exited with code 1
error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/sysdeps/unix/sysv/linux/fstat.c:1:1: unable to build C object: clang exited with code 1
error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/sysdeps/unix/sysv/linux/lstat.c:1:1: unable to build C object: clang exited with code 1
error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/csu/elf-init-2.33.c:1:1: unable to build C object: clang exited with code 1
error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/csu/errno.c:1:1: unable to build C object: clang exited with code 1
error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/sysdeps/unix/sysv/linux/stat.c:1:1: unable to build C object: clang exited with code 1
error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/debug/stack_chk_fail_local.c:1:1: unable to build C object: clang exited with code 1
error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/sysdeps/pthread/pthread_atfork.c:1:1: unable to build C object: clang exited with code 1
error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/stdlib/at_quick_exit.c:1:1: unable to build C object: clang exited with code 1
error(compilation): /home/mitchellh/code/go/src/github.com/ziglang/zig/build/stage2/lib/zig/libc/glibc/stdlib/atexit.c:1:1: unable to build C object: clang exited with code 1
error: unable to build glibc CRT file: BuildingLibCObjectFailed
</pre>
</details>

**Comment by topolarity** [comment]
I'm running into this trying to bring up the C ABI tests for stage 2. More direct repro:

```c
#include "stdint.h"

int main(void) {}
```

```zig
$ ./build/zig -cc1 ./hello.c -isystem ./lib/include -isystem ./lib/libc/include/x86_64-linux-gnu -isystem ./lib/libc/include/generic-glibc -isystem ./lib/libc/include/x86-linux-any -isystem ./lib/libc/include/any-linux-any
$ ./stage2/bin/zig -cc1 ./hello.c -isystem ./lib/include -isystem ./lib/libc/include/x86_64-linux-gnu -isystem ./lib/libc/include/generic-glibc -isystem ./lib/libc/include/x86-linux-any -isystem ./lib/libc/include/any-linux-any
./hello.c:1:10: fatal error: cannot open file './stdint.h': No such file or directory
#include "stdint.h"
         ^
1 error generated.
```

`zig -cc1` pipes its arguments directly into `ZigClang_main`, so there's very little Zig logic to interfere here. Must be a build or clang-introspection issue.

**Comment by topolarity** [comment]
Getting closer...
```bash
$ nm -C ./stage2/bin/zig | grep generic_category
0000000004572888 d (anonymous namespace)::generic_category_instance
0000000002121bb0 T std::_V2::generic_category()
$ nm -C ./build/zig | grep generic_category
                 U std::_V2::generic_category()@GLIBCXX_3.4.21
```

Looks like we end up with multiple `std::generic_category` instances in stage2

This causes `llvm::errc::no_such_file_or_directory` to compare unequal to the `ENOENT` expected by clang, leading it to bail upon the "surpising" error (https://github.com/llvm-mirror/clang/blob/aa231e4be75ac4759c236b755c57876f76e3cf05/lib/Lex/HeaderSearch.cpp#L330-L335)

**Comment by BratishkaErik** [comment]
> I'm running into this trying to bring up the C ABI tests for stage 2. More direct repro:
> 
> ```c
> // hello.c
> #include "stdint.h"
> int main(void) {}
> ```
> 
> ```zig
> $ ./build/zig -cc1 ./hello.c -isystem ./lib/include -isystem ./lib/libc/include/x86_64-linux-gnu -isystem ./lib/libc/include/generic-glibc -isystem ./lib/libc/include/x86-linux-any -isystem ./lib/libc/include/any-linux-any
> $ ./stage2/bin/zig -cc1 ./hello.c -isystem ./lib/include -isystem ./lib/libc/include/x86_64-linux-gnu -isystem ./lib/libc/include/generic-glibc -isystem ./lib/libc/include/x86-linux-any -isystem ./lib/libc/include/any-linux-any
> ./hello.c:2:10: fatal error: cannot open file './stdint.h': No such file or directory
> #include "stdint.h"
>          ^
> 1 error generated.
> ```
> 
> `zig -cc1` pipes its arguments directly into `ZigClang_main`, so there's very little Zig logic to interfere here. Must be a build or clang-introspection issue.

I can't reproduce this

**Comment by topolarity** [comment]
Does the original issue reproduce for you?

**Comment by BratishkaErik** [comment]
> Does the original issue reproduce for you?

`clang hello.c -lc`:

```cc
hello.c:1:6: error: variable has incomplete type 'void'
void main {}
     ^
hello.c:1:1: warning: variable named 'main' with external linkage has undefined behavior [-Wmain]
void main {}
^
hello.c:1:10: error: expected ';' after top level declarator
void main {}
         ^
         ;
1 warning and 2 errors generated.
```

`./build/zig run hello.c -lc`:

```
error(compilation): clang failed with stderr: hello.c:1:6: error: variable has incomplete type 'void'
hello.c:1:1: warning: variable named 'main' with external linkage has undefined behavior [-Wmain]
hello.c:1:10: error: expected ';' after top level declarator

hello.c:1:1: error: unable to build C object: clang exited with code 1
```


`./build/stage2/bin/zig run hello.c -lc`:

Same.

**Comment by topolarity** [comment]
Ah, I see your edit now. I think that is consistent with the problem identified in #12085

It will depend on your linking setup. In particular, it happens when the build mixes shared/static libs for Clang and LLVM.
