### ISSUE TITLE
stage1: All fields should be required in tuple initializers, including comptime fields

### ISSUE THREAD

**Issue by topolarity** [ziglang/zig#11163]
### Zig Version

0.10.0-dev.1246+5fbae9cd6

### Steps to Reproduce

cc @ifreund and @mitchellh, who contributed this test case

```zig
test {
    const T = @TypeOf(.{ @as(i32, 0), @as(u8, 123) });
    var a: T = .{0};
    try testing.expectEqual(@as(i32, 0), a[0]);
    try testing.expectEqual(@as(u8, 123), a[1]);
}
```

### Expected Behavior

This test should fail to compile - the initializer is missing the second field.

### Actual Behavior

The test passes.

**Comment by topolarity** [comment]
Related: #11162

**Comment by topolarity** [comment]
Initializing a tuple type with some comptime and some runtime fields also fails:

```zig
const std = @import("std");
const testing = std.testing;

test {
    var x: u32 = 15;
    const T = @TypeOf(.{ @as(i32, -1234), @as(u32, 5678), x });
    var a: T = .{ -1234, 5678, x + 1 };
    _ = a;
}
```

**Comment by Vexu** [comment]
Test passes as expected, `@TypeOf(T) == struct { comptime i32 = 0, comptime u8 = 123 }`.
