### ISSUE TITLE
asm in comptime blocks

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#11171]
### Zig Version

0.10.0-dev.1261+6f986298c

### Steps to Reproduce

```zig
const std = @import("std");
const builtin = @import("builtin");

const foo = blk: {
    const value = asm(
        \\foo:
        \\  ret
    );
    @compileLog(value);
    break :blk value;
};

comptime {
    @export(foo, .{ .name = "foo" });
}
```

### Expected Behavior

The code does not build (inline assembly is illegal in `comptime` scopes).

### Actual Behavior

Code builds.

**Comment by MasterQ32** [comment]
Note:
This will not compile when the assembly has inputs/outputs/clobbers. But the asm block should definitly not be allowed in a expression context and only as a standalone statement.

**Comment by N00byEdge** [comment]
Isn't non-volatile asm with no outputs allowed to be optimized away?

**Comment by MasterQ32** [comment]
> Isn't non-volatile asm with no outputs allowed to be optimized away? If it still happens with asm volatile, then it's definitely an issue.

This is a problem in sema, not codegen

**Comment by N00byEdge** [comment]
I don't see why that wouldn't be allowed in sema, but I guess you may be right.

**Comment by Vexu** [comment]
Module level asm works in master.
