### ISSUE TITLE
macOS build from master can't find libs when using symlinked zig binary

### ISSUE THREAD

**Issue by binary132** [ziglang/zig#1117]
## Platform

- macOS 10.13.5
- cmake 3.11.4

## Steps to build and link

I cloned and built Zig using ninja, via `cmake -G Ninja .. -DCMAKE_PREFIX_PATH=/usr/local/opt/llvm@6/`, `ninja build`, and `ninja install`.  This installed the zig libs into the build-local path.  I was also able to build stage2 zig using the newly built zig binary.

I then created a symlink to the newly built stage1 zig binary in my user's PATH.

## Unexpected output

When I run `zig build-exe hello.zig` on the sample Hello World, the following message appears:

```
Unable to find zig lib directory
```

## Workarounds

When I run `<build path>/bin/zig build-exe hello.zig` on the sample Hello World, it compiles successfully.

I can also use the Zig installed from Homebrew successfully, and I can use the Ubuntu build too.

I am also able to make this work by checking out, building, and installing 0.2.0, because it installs the libs to /usr/local/lib/zig.  However, linking the master build's `build/libs/zig` into `/usr/local/lib/zig` does not work.

**Comment by andrewrk** [comment]
I think this can be solved by calling `realpath` after `_NSGetExecutablePath` here: https://github.com/ziglang/zig/blob/b3a3e2094e8b88e40eecf65d29f39af10442bde4/src/os.cpp#L996

**Comment by binary132** [comment]
Ok, this pull request should do the trick.

**Comment by andrewrk** [comment]
Thanks for the PR!

**Comment by binary132** [comment]
@andrewrk this isn't fixed in the stage2 compiler.  Where should I start?
