### ISSUE TITLE
Compiler segfaults on M1 when accessing packed struct inside of packed union inside of packed struct

### ISSUE THREAD

**Issue by joedavis** [ziglang/zig#11190]
### Zig Version

0.10.0-dev.3381+8a43d67c3

### Steps to Reproduce

Minimal examples:

    // min-1.zig
    const std = @import("std");

    pub const Foo = packed struct {
        x: [1]u8,
        ext: packed union { bar: Bar },
    };

    pub const Bar = packed struct {
        empty: u8,
    };

    pub fn main() !void {
        var foo: Foo = undefined;
        std.debug.print("{}\n", .{foo.ext.bar});
    }

The above builds fine.

---

    // min-3.zig
    const std = @import("std");

    pub const Foo = packed struct {
        x: [3]u8,
        ext: packed union { bar: Bar },
    };

    pub const Bar = packed struct {
        empty: u8,
    };

    pub fn main() !void {
        var foo: Foo = undefined;
        std.debug.print("{}\n", .{foo.ext.bar});
    }

After changing the size of the `x` array from 1 to 3, the compiler fails to build with a seg fault.

> zig build-exe min-3.zig
fish: Job 1, 'zig build-exe min-3.zig' terminated by signal SIGSEGV (Address boundary error)

---

For context as to where the `packed struct > packed union > packed struct` arose, I'm working on a library for working with FAT volumes. The boot parameter block can contain a different structure embedded within it depending on whether or not the volume is FAT12/16 or FAT32.

All sizes of the `x` array other than 1, 2, 4, or any multiple of 8 fail.

### Expected Behavior

    > zig build-exe min-3.zig
    >

### Actual Behavior

    > zig build-exe min-3.zig
    fish: Job 1, 'zig build-exe min-3.zig' terminated by signal SIGSEGV (Address boundary error)

**Comment by fifty-six** [comment]
I think this might be the same as #10686, but I've encountered the same on x64. You can also work around it to some extent as follows:

This crashes:
```zig
var bar = foo.ext.bar;
```
but if you split it, I've found this doesn't
```zig
var ext = foo.ext;
var bar = ext.bar;
```

**Comment by Vexu** [comment]
Arrays are no longer allowed in packed structs.
