### ISSUE TITLE
Crash when using arrays with duplicate field names in anonymous struct

### ISSUE THREAD

**Issue by damienfir** [ziglang/zig#11215]
### Zig Version

0.9.0

### Steps to Reproduce

Compile the following code with `zig build-exe`:
```
fn f(x: anytype) void {
    _ = x.a;
}

pub fn main() !void {
    f(.{.a = [_]u8{1}, .a = [_]u8{1}});
}
```

### Expected Behavior

Compilation error because there are duplicate fields.

### Actual Behavior

```
Assertion failed at /build/zig/src/zig-0.9.0/src/stage1/ir.cpp:566 in const_ptr_pointee_unchecked_no_isf. This is a bug in the Zig compiler.thread 103414 panic: 
Unable to dump stack trace: debug info stripped
[1]    103414 IOT instruction (core dumped)  zig build-exe test.zig
```

Note that the compiler fails properly if the type of the fields `.a` is `u8` instead of `[_]u8`.

**Comment by Vexu** [comment]
Tested in `test/cases/compile_errors/duplicate_field_in_anonymous_struct_literal.zig`.
