### ISSUE TITLE
`unable to evaluate constant expression` should explain why the value has to be comptime known

### ISSUE THREAD

**Issue by danielchasehooper** [ziglang/zig#11221]
### Zig Version

0.10.0-dev.1393+291f5055f

### Steps to Reproduce

```
~/Developer/zigtests $ cat bad_const_expr_error.zig 

pub fn ldexp(x: anytype, n: i32) @TypeOf(x) {
    _ = n;
    return x;
}

test {
    var bits :i32= 4;
    _ = ldexp(1, 113-bits);
}


~/Developer/zigtests $ zig test bad_const_expr_error.zig 
./bad_const_expr_error.zig:9:21: error: unable to evaluate constant expression
    _ = ldexp(1, 113-bits);
                    ^
```

### Expected Behavior

should either
A. run with no error
B. point at the first param, since that seems to be the one that is causing the issue

### Actual Behavior

errors on the *second* parameter.

You can make the error go away by adding a type to the *first* param: `ldexp(@as(i32,1), 113-bits);`

I hit this and I messed with the second parameter for a while before realizing the issue was with the first param...was a annoying waste of time to have the compiler send me down the wrong path. The message itself doesn't seem correct either, at the very least it could be more helpful.

**Comment by Vexu** [comment]
`@TypeOf(1) == comptime_int` which when used in the return type makes the function comptime only, requiring all the arguments to also be comptime known.

What would be useful would be for the error have a note attached which states why it has to be comptime known.

**Comment by danielchasehooper** [comment]
@Vexu The parameters *are* known at comptime, are they not? They're 1, and 109 (aka 113 - 4).

**Comment by Vexu** [comment]
`bits` is a non-comptime `var` making it runtime only, if you want it to be comptime known change `bits` into a `const` or a `comptime var`.

**Comment by Vexu** [comment]
This is implemented in the self-hosted compiler.
```
a.zig:13:21: error: unable to resolve comptime value
    _ = ldexp(1, 113-bits);
                 ~~~^~~~~
a.zig:13:21: note: argument to function being called at comptime must be comptime-known
a.zig:6:34: note: generic function is instantiated with a comptime-only return type
pub fn ldexp(x: anytype, n: i32) @TypeOf(x) {
                                 ^~~~~~~~~~
```
