### ISSUE TITLE
Wrong size of c_<type> for 16 bit target

### ISSUE THREAD

**Issue by vegecode** [ziglang/zig#1125]
```asm
; Linker script provides the address for the WDTCTL register which
; then is used in the device specific header like so
;sfr_w(WDTCTL);                                /* Watchdog Timer Control */

; an iomacros.h file provides the macros below that declare a variable
; WDTCTL is declared as an unsigned int which on a 16 bit target I
; assumed would be 16 bits like it is in C
;#define sfr_b(x) extern volatile unsigned char x
;#define sfr_w(x) extern volatile unsigned int x
;#define sfr_a(x) extern volatile unsigned long int x
;#define sfr_l(x) extern volatile unsigned long int x

; Compiler is treating as 32 bit instead of 16 bit
main:
	push.w	r4
	mov.w	r1, r4
	mov.w	#0, &WDTCTL+2    ;<<<< This line should not be here.
	mov.w	#23168, &WDTCTL
	jmp	.LBB2_1
.LBB2_1:
	jmp	.LBB2_1
```

Changing the `sfr_x` definitions to char, short, and int respectively fix the problem for now.

In `zig/Target.cpp` in function `uint32_t target_c_type_size_in_bits(const ZigTarget *target, CIntType id)`, the sizes are defined based on the operating system type. Would it make more sense for them to be based on the architecture?

By the current logic, I think that on the msp430 a long is shorter than an int. A long would be 16 bit and an int would be 32 bit.

Perhaps compiler switches to override the default would be easiest for supporting architectures that deviate from whatever the most common Zig platform is.

**Comment by andrewrk** [comment]
The target is composed of:
  * architecture (msp430 for you)
  * OS (freestanding for you)
  * C environment

Between these things, we can figure out what sizes the C types should be.

I found this in clang:

```c++
  MSP430TargetInfo(const llvm::Triple &Triple, const TargetOptions &)
      : TargetInfo(Triple) {
    TLSSupported = false;
    IntWidth = 16;
    IntAlign = 16;
    LongWidth = 32;
    LongLongWidth = 64;
    LongAlign = LongLongAlign = 16;
    PointerWidth = 16;
    PointerAlign = 16;
    SuitableAlign = 16;
    SizeType = UnsignedInt;
    IntMaxType = SignedLongLong;
    IntPtrType = SignedInt;
    PtrDiffType = SignedInt;
    SigAtomicType = SignedLong;
```

So I think we can simply add this information to Zig.

**Comment by vegecode** [comment]
In e5956f2, a long is still 16 bits. It should be 32 bits, I believe.

**Comment by andrewrk** [comment]
Hmm. Looks like we should hard code it to 32 bits rather than pointer size.

**Comment by vegecode** [comment]
It appears so.
