### ISSUE TITLE
diagnostics before format

### ISSUE THREAD

**Issue by Prince213** [ziglang/zig#11261]
### Zig Version

0.10.0-dev.1463+0577069af

### Steps to Reproduce

t.zig:
```zig
fn f() void {
    while(_ <2){}
}
```
Then run `zig fmt t.zig`

### Expected Behavior

The file is successfully formatted to the following:
```zig
fn f() void {
    while (_ < 2) {}
}
```

### Actual Behavior

```
t.zig:2:13: error: binary operator `<` has whitespace on one side, but not the other.
    while(_ <2){}
            ^
```

**Comment by jibal** [comment]
This is intended behavior: https://github.com/ziglang/zig/issues/7399#issuecomment-743537724
