### ISSUE TITLE
macos CI test disabled: test/standalone/issue_339

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1126]
https://api.travis-ci.org/v3/job/393343970/log.txt

```
Build failed. The following command failed:

/Users/travis/build/ziglang/zig/test/standalone/issue_339/zig-cache/build build/zig /Users/travis/build/ziglang/zig/test/standalone/issue_339 /Users/travis/build/ziglang/zig/test/standalone/issue_339/zig-cache test

The following command exited with error code 255:

cd ./.. && build/zig build --build-file /Users/travis/build/ziglang/zig/test/standalone/issue_339/build.zig test 
```

I'm not able to reproduce the problem on my mac laptop. @bnoordhuis are you able to?

```
bin/zig build --build-file ../test/standalone/issue_339/build.zig test
```

**Comment by binary132** [comment]
I'm not sure this is the problem, but the hello world no longer builds for me on master, which makes it hard to test my patch:

```
~/tmp/zig/hello❯ zig build-exe main.zig
/Users/bodie/meta/build/zig/build/bin/zig:1:1: error: invalid character: '\xcf'
^
```

**Comment by bnoordhuis** [comment]
Doesn't fail for me locally either (with d52ef95 reverted.)  Not sure what to make of that stack trace.

**Comment by andrewrk** [comment]
The stack trace that has the makeDirPosix / makeDir functions in it is an error return trace where the errors were all handled. There isn't a useful stack trace in that output - it looks like the process `/Users/travis/build/ziglang/zig/test/standalone/issue_339/zig-cache/build` either segfaulted or was otherwise killed by the OS. The next step for me will be having a branch that only runs that test, and runs it in lldb and tries to get a back trace.
