### ISSUE TITLE
std.json can't parse to std.ArrayList?

### ISSUE THREAD

**Issue by WesleyAC** [ziglang/zig#11262]
### Zig Version

0.10.0-dev.1458+3d8d6c0a6

### Steps to Reproduce

```zig
const std = @import("std");

pub fn main() anyerror!void {
    _ = try std.json.parse(struct { foo: usize }, &std.json.TokenStream.init("{ \"foo\": 42 }"), .{});
    _ = try std.json.parse(std.ArrayList(usize), &std.json.TokenStream.init("[ 1, 2, 3 ]"), .{});
}
```

### Expected Behavior

The code compile successfully.

Looking at the std.json source, it seems to represent arrays as `std.ArrayList`, so my expectation is that this will work.

### Actual Behavior

The first line works, but the second one gives (context trimmed, since the error is very long):

```
/home/wesleyac/.zig/0.10.0-dev.1458+3d8d6c0a6/lib/std/json.zig:1848:27: error: cannot assign to constant
                    r.* = try parseInternal(ptrInfo.child, token, tokens, options);
                          ^
/home/wesleyac/.zig/0.10.0-dev.1458+3d8d6c0a6/lib/std/mem/Allocator.zig:295:47: error: slice of type 'anyopaque' not allowed
) Error![]align(alignment orelse @alignOf(T)) T {
                                              ^
/home/wesleyac/.zig/0.10.0-dev.1458+3d8d6c0a6/lib/std/json.zig:1908:17: error: Unable to parse into type 'anyopaque'
        else => @compileError("Unable to parse into type '" ++ @typeName(T) ++ "'"),
                ^
/home/wesleyac/.zig/0.10.0-dev.1458+3d8d6c0a6/lib/std/json.zig:1908:17: error: Unable to parse into type 'fn(*anyopaque, usize, u29, u29, usize) std.mem.Allocator.Error![]u8'
        else => @compileError("Unable to parse into type '" ++ @typeName(T) ++ "'"),
                ^
/home/wesleyac/.zig/0.10.0-dev.1458+3d8d6c0a6/lib/std/json.zig:1908:17: error: Unable to parse into type 'fn(*anyopaque, []u8, u29, usize, u29, usize) ?usize'
        else => @compileError("Unable to parse into type '" ++ @typeName(T) ++ "'"),
                ^
/home/wesleyac/.zig/0.10.0-dev.1458+3d8d6c0a6/lib/std/json.zig:1908:17: error: Unable to parse into type 'fn(*anyopaque, []u8, u29, usize) void'
        else => @compileError("Unable to parse into type '" ++ @typeName(T) ++ "'"),
                ^
```

**Comment by tauoverpi** [comment]
`std.json.parse` inspects the structure of the type passed when it's a container type and doesn't specialize for any particular variant (be it `ArrayList`, `HashMap`, and so on) so the above won't work as you expect even if it passed type checking as will try to parse the given string as a json object consisting of

https://github.com/ziglang/zig/blob/3701697a0a586e630a2452dea29951f0051a47fd/lib/std/array_list.zig#L30-L45

rather than parsing arrays to ArrayList. Even if it could, questions of "which allocator should it use?" and "what should it be aligned to?" come up.

Thus I don't think this is really a bug but the error could be clearer for anyopaque.

**Comment by WesleyAC** [comment]
Hmm, that makes sense.

Am I correctly understanding, then, that the only way to parse json that has arrays in it with `std.json` is by using the dynamic API, and then manually building the type I want from the dynamic result?

**Comment by tauoverpi** [comment]
You can still parse arrays within json with `std.json.parse` if you use slices:

```zig
const T = struct { example: []const u32 };
const string =
    \\{ "example": [ 1, 2, 3 ] }
;
var stream = std.json.TokenStream.init(string); // stack temporaries will be const in stage2 iirc so need to use a var
const result = try std.json.parse(T, &stream, .{ .allocator = gpa });
```

Also, do checkout https://github.com/ziglang/zig/wiki/Community

**Comment by WesleyAC** [comment]
Thanks, that did the trick!
