### ISSUE TITLE
printing float value causes fmt to panic

### ISSUE THREAD

**Issue by kristoff-it** [ziglang/zig#11283]
### Zig Version

0.10.0-dev.768+d811e03fb

### Steps to Reproduce

```zig
const std = @import("std");

pub fn main() void {
    const float: f64 = 1.000000e+37;
    std.debug.print("value: {}\n", .{float});
}
```

### Expected Behavior

Runs.

### Actual Behavior

```
value: thread 934843 panic: integer overflow
/home/kristoff/zig-master/lib/std/fmt/errol.zig:339:26: 0x24f1af in std.fmt.errol.errolInt (float)
        buffer[buf_index - 1] += @boolToInt(buffer[buf_index] >= '5');
                         ^
...
```

### Context
This error was encountered while trying to print values from a file in the standard library. 

https://github.com/ziglang/zig/blob/d29871977f97b50fe5e3f16cd9c68ebeba02a562/lib/std/fmt/errol/lookup.zig#L277 

The highlighted line corresponds to this precise value.

It might be worth testing the fix against the whole contents of `lookup_table`.

**Comment by andrewrk** [comment]
#1299 would be a nice solution to this. I think @tiehuis got pretty far on it but didn't quite finish it.
