### ISSUE TITLE
callsites lack result location types, causing unwanted compile errors when argument expressions make a runtime branch

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#11293]
```zig
test {
    foo(if (runtime) .a else .b);
}
var runtime = true;
const E = enum { a, b };
fn foo(e: E) void {
    _ = e;
}
```

Expected:

```
$ ./zig test test3.zig 
All 1 tests passed.
```

Actual:

```
$ ./zig-out/bin/zig test test3.zig 
test3.zig:2:9: error: value with comptime only type '@TypeOf(.enum_literal)' depends on runtime control flow
    foo(if (runtime) .a else .b);
        ^
test3.zig:2:13: note: runtime control flow here
    foo(if (runtime) .a else .b);
            ^
```

This did work before 1cc5d4e758a95be373756e7c32f9bb46d21633c9 which added method call syntax and in the process of it removed the result location type from function call arguments:

```diff
     for (call.ast.params) |param_node, i| {
-        const param_type = try gz.add(.{
-            .tag = .param_type,
-            .data = .{ .param_type = .{
-                .callee = lhs,
-                .param_index = @intCast(u32, i),
-            } },
-        });
-        args[i] = try expr(gz, scope, .{ .coerced_ty = param_type }, param_node);
+        // Parameters are always temporary values, they have no
+        // meaningful result location.  Sema will coerce them.
+        args[i] = try expr(gz, scope, .none, param_node);
     }
```

 @SpexGuy did you have a suggestion on how to make this work? Seems like we might need to restructure it so that it builds function calls one piece at a time.

This is the next bug to get the self-hosted parser working.

**Comment by SpexGuy** [comment]
My crazy idea was to insert special instructions at call sites and in parameter type evaluation that cause sema to ping-pong back and forth between the two contexts, evaluating a type in the signature and then a value at the call site.  Something like `%type = next_param_type %curr_param_value` and `%value = yield_param_type %type`.

**Comment by matu3ba** [comment]
@SpexGuy user andyjansson on twitch pointed to type system resolving, so I checked and found "Complete and Easy Bidirectional Typechecking for Higher-Rank Polymorphism" by Jana Dunfield and Neelakantan R. Krishnaswami
which explains tradeoffs in 9. Related Work and Discussion (whole thing is 91 pages).

This paper could be related as it claims to simplify annotations https://i.cs.hku.hk/~bruno/papers/arguments-esop18.pdf

HN also tells to use bidirectional typechecking, if type inference is needed https://news.ycombinator.com/item?id=15054752

As I understand it, runtime dependency on comptime stuff breaks things here and requires solving/evaluating the comptime stuff before the runtime stuff.

Further, user andyjansson claimed in chat that algorithms run for typical input in polynomial time and did not provide any complexity class when asked in chat. Also, the person did not provide links.
