### ISSUE TITLE
Linker error when using zig to compile a CGo program on a Mac

### ISSUE THREAD

**Issue by kaidaguerre** [ziglang/zig#11303]
### Zig Version

0.9.1

### Steps to Reproduce

I'm trying to compile a hello world CGO program using the zig toolchain.

I get an error when compiling with zig.

The program is
```
    package main
    
    import "C"
    import "fmt"
    
    func main() {
    	fmt.Println(C.int(10))
    }
```
My build command is
```
 CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 CC="zig cc -target x86_64-macos" CXX="zig c++ -target x86_64-macos" go build
```

My system:
- Macos Catalina 10.15.7 
- Apple clang version 12.0.0 
- zig 0.9.1 
- go version go1.18 darwin/amd64

### Expected Behavior

the program builds

### Actual Behavior

the build fails with a link error
```
warning: unsupported linker arg: -headerpad
warning: unsupported linker arg: 1144
warning: unsupported linker arg: -no_pie
warning: unsupported linker arg: -pagezero_size
warning: unsupported linker arg: 4000000
/usr/local/go/pkg/tool/darwin_amd64/link: /usr/local/go/pkg/tool/darwin_amd64/link: running dsymutil failed: exit status 1
LLVM ERROR: Malformed MachO file.


```

**Comment by motiejus** [comment]
Does this work?

```
CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 CC="zig cc -target x86_64-macos" CXX="zig c++ -target x86_64-macos" go build -a -buildmode=pie -ldflags "-s -w" main.g
```

Also see https://github.com/ziglang/zig/issues/9050#issuecomment-859939664 and https://git.sr.ht/~motiejus/bazel-zig-cc/tree/main/item/rules/rules_go.bzl#L14, where I maintain flags for cgo.

**Comment by kubkon** [comment]
CoreFoundation is linked against by Go for some reason, and as discussed and agreed with @motiejus we should make it a hard error when a linked framework is not found, hence why you need to spell out framework search dirs when using `zig cc` with cgo.

@kaidaguerre lemme know if the hints by @motiejus and @slimsag were helpfui and fixed your issue, so that we can close it, or further investigate it.

**Comment by kubkon** [comment]
Since there's not been any activity in this thread for quite some time, I'm closing the issue. If the problem persists or you feel it has not been properly handled @kaidaguerre, feel free to request it being re-opened, or file a new issue.

**Comment by motiejus** [comment]
I used @slimsag 's command with a recent Go and Zig versions and got a segfault. Created a new issue #14923.
