### ISSUE TITLE
std.mem.zeroInit fails to initialize a field

### ISSUE THREAD

**Issue by acarrico** [ziglang/zig#11323]
### Zig Version

0.9.0

### Steps to Reproduce

[This test case](https://gist.github.com/acarrico/ceced9788167c13a32e1992306a19ad7) illustrates a field initialization failure.

### Expected Behavior

All fields should be initialized to initializer, default value, or zero.

### Actual Behavior

A field with a default value is not being set to that value.

**Comment by ominitay** [comment]
Intended behaviour. Please read doc comments.
https://github.com/ziglang/zig/blob/d15bbebe2e6b8fcbfcd730a6c0d1be621b27045d/lib/std/mem.zig#L423-L426
```
/// Initializes all fields of the struct with their default value, or zero values if no default value is present.
```

**Comment by ominitay** [comment]
Can reproduce this on master (0.10.0-dev.1618+7ae22813e)

**Comment by acarrico** [comment]
I happened to test with a packed struct, but same thing with a plain struct.

**Comment by ominitay** [comment]
@Vexu This should be tagged as a std bug, not a stage1 bug, right?

**Comment by Vexu** [comment]
Looks like a packed struct bug to me.

**Comment by ominitay** [comment]
Can't be, since it occurs with regular structs as well, as @acarrico stated. I can repro on my system regarding this. Unless it's a bug with `@typeInfo`?

**Comment by acarrico** [comment]
@Vexu nope, same bug with regular structs.

**Comment by ominitay** [comment]
I remember actually encountering but overlooking this bug. For some reason, there isn't actually a test case covering this at all.

**Comment by Vexu** [comment]
Well the code in `zeroInit` seems to be doing the correct thing so it is still a stage1 bug.

**Comment by ominitay** [comment]
Nope it's not -- I've found the issue. `.{}` is a tuple. This causes `zeroInit` to branch here: https://github.com/ziglang/zig/blob/d15bbebe2e6b8fcbfcd730a6c0d1be621b27045d/lib/std/mem.zig#L435-L440, and so never returns with default values. There should be a check for whether this tuple is zero-length.

**Comment by ominitay** [comment]
There should also arguably be a check to determine whether the tuple has the correct number of fields, which currently is not implemented.

**Comment by Vexu** [comment]
Ah, I see I was looking at the struct path.

**Comment by acarrico** [comment]
I haven't done any compile time programming yet, but that seems like an easy mistake to make.

**Comment by acarrico** [comment]
@ominitay wrote,

> Should we even allow a tuple to be passed though? Probably for a separate issue to address...

Yes, because that is the way to zero memory with the just defaults and no additional field initialization.

**Comment by ominitay** [comment]
No I wasn't talking about your usecase there. I was thinking more generally about the use of tuples there, but I see the usecase for that too now.
