### ISSUE TITLE
zig cc: illegal instruction generated for trivial pointer arithmetic

### ISSUE THREAD

**Issue by qroq** [ziglang/zig#11324]
### Zig Version

0.10.0-dev.1617+dbbda0f41

### Steps to Reproduce

Linux penguin 5.10.92-14540-g0aec27ec0722 #1 SMP PREEMPT Thu Mar 17 19:07:50 PDT 2022 x86_64 GNU/Linux
(this is linux running in chromeOS)

zig cc of the following:

int main()
{
	int *should_be_0 = (int *)0 + 0;
	return should_be_0 != 0;
}

give an illegal instruction:

(gdb) r
Starting program: /home/raible/interpreters/zig-linux-x86_64-0.10.0-dev.1617+dbbda0f41/a.out 

Program received signal SIGILL, Illegal instruction.
main () at simple.c:3
3		int *should_be_0 = (int *)0 + 0;
(gdb) disassemble main
Dump of assembler code for function main:
   0x0000000000201450 <+0>:	push   %rbp
   0x0000000000201451 <+1>:	mov    %rsp,%rbp
=> 0x0000000000201454 <+4>:	ud1    0x13(%eax),%eax
End of assembler dump.
(gdb) 

### Expected Behavior

No illegal instruction

### Actual Behavior

Program crashes with an illegal instruction.

**Comment by Vexu** [comment]
That is undefined behavior, compiling with clang gives:
```
a.c:3:29: runtime error: applying zero offset to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior a.c:3:29 in 
```

See https://github.com/ziglang/zig/wiki/FAQ#why-do-i-get-illegal-instruction-when-using-with-zig-cc-to-build-c-code

**Comment by andrewrk** [comment]
Related:  #5163
