### ISSUE TITLE
CMake Error at CMakeLists.txt:24 (project):   Running     'nmake' '-?'

### ISSUE THREAD

**Issue by AnimalStudioOfficial** [ziglang/zig#11345]
### Zig Version

0.9.1

### Steps to Reproduce

I run the commmand:
mkdir build
cd build
cmake ..

### Expected Behavior

I want it to build the project

### Actual Behavior

the output:
-- Found ccache C:/ProgramData/chocolatey/bin/ccache.exe
CMake Error at CMakeLists.txt:24 (project):
  Running

   'nmake' '-?'

  failed with:

   The system cannot find the file specified

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "G:/Programing/Langs/zig-0.9.1/zig-0.9.1/build/CMakeFiles/CMakeOutput.log".

**Comment by matu3ba** [comment]
Look like your `CC` and `CXX` variable are not set. Those must hold the paths to C and C++ compiler.

**Comment by AnimalStudioOfficial** [comment]
> CXX

I

**Comment by AnimalStudioOfficial** [comment]
> Look like your `CC` and `CXX` variable are not set. Those must hold the paths to C and C++ compiler.

I do not know how to find CXX

**Comment by nektro** [comment]
referring to the environment variables

**Comment by AnimalStudioOfficial** [comment]
> referring to the environment variables

What do you Mean?

**Comment by matu3ba** [comment]
context https://github.com/vslavik/bakefile/issues/76 https://stackoverflow.com/questions/37787796/why-does-cmake-ignore-exported-cxx-and-cc-environment-variables

Environment variables are the things shown as `env` in your terminal (under Linux).
see for the error https://stackoverflow.com/a/70524204 and a workaround (under Linux)
```sh
export CC='pathtoyourccompiler'
export CXX='pathtoyourccompiler'
```

Did you follow instructions of https://github.com/ziglang/zig/wiki/Building-Zig-on-Windows ?

**Comment by AnimalStudioOfficial** [comment]
> context [vslavik/bakefile#76](https://github.com/vslavik/bakefile/issues/76) https://stackoverflow.com/questions/37787796/why-does-cmake-ignore-exported-cxx-and-cc-environment-variables
> 
> Environment variables are the things shown as `env` in your terminal (under Linux). see for the error https://stackoverflow.com/a/70524204 and a workaround (under Linux)
> 
> ```shell
> export CC='pathtoyourccompiler'
> export CXX='pathtoyourccompiler'
> ```
> 
> Did you follow instructions of https://github.com/ziglang/zig/wiki/Building-Zig-on-Windows ?

Nothing happens when i did    set( CMAKE_CXX_COMPILER "C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/g++" )
set( CMAKE_C_COMPILER "C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/gcc" )

**Comment by andrewrk** [comment]
Please ask for help in one of the [community spaces](https://github.com/ziglang/zig/wiki/Community).
