### ISSUE TITLE
Pointer offset doesn't match @offsetOf in packed struct containing array with odd number of elements and a union

### ISSUE THREAD

**Issue by fifty-six** [ziglang/zig#11347]
### Zig Version

0.10.0-dev.1107+7deadf430

### Steps to Reproduce

Have a struct containing an odd number of elements followed by a union.
```zig
const std = @import("std");

const T = packed struct {
    const Self = @This();

    _: [7]u8,

    info: extern union { a: u8 },
};

test "offset" {
    var among: T = undefined;

    try std.testing.expect(@ptrToInt(&among.info) == (@ptrToInt(&among) + @offsetOf(T, "info")));
}
```

### Expected Behavior

I expected `@offsetOf` to match the field offset obtained when getting the address of the field.

### Actual Behavior

`@offsetOf` gave the correct offset (7), while the pointer arithmetic gave (0). I've also had it happen with a bigger case, where the pointer was 9 while the offset was correctly reported as 16 by offsetOf.

**Comment by Vexu** [comment]
Arrays are no longer allowed in packed structs.
