### ISSUE TITLE
std.net.getAddressList segfaults when passed an invalid or unreachable hostname.

### ISSUE THREAD

**Issue by truemedian** [ziglang/zig#11358]
### Zig Version

0.10.0-dev.1669+c21f046a8

### Steps to Reproduce

* call `std.net.getAddressList` with any invalid/unreachable hostname

Code to reproduce:
```zig
const std = @import("std");

pub fn main() !void {
    // This breaks on windows too.
    if (@import("builtin").os.tag == .windows) _ = std.os.windows.WSAStartup(2, 2) catch unreachable;

    _ = try std.net.getAddressList(std.heap.page_allocator, "imaninvalidhostname.xd", 420);
}
```

### Expected Behavior

The error should be propagated upwards and memory allocated in std.net.getAddressList should be cleaned up.

### Actual Behavior

std.net.getAddressList's arena tries to deallocate itself while deinitializing, causing a segfault.

```
Segmentation fault at address 0xffffffffffffffff
H:\lib\zig\std\mem\Allocator.zig:505:17: 0x7ff67604ba88 in std.mem.Allocator.free (repro.obj)
    self.rawFree(non_const_ptr[0..bytes_len], Slice.alignment, @returnAddress());
                ^
???:?:?: 0xfff in ??? (???)
???:?:?: 0xaaaaaaaaaaaaaaa9 in ??? (???)
```

This is most likely caused by `result` being allocated with the arena and then storing the arena within itself. This causes `result.arena` to become undefined memory during the middle of `result.arena.deinit()`

**Comment by Vexu** [comment]
Fixed by #12066
