### ISSUE TITLE
Proposal: Add function pointer field to TypeInfo.Definition.Data.FnDef

### ISSUE THREAD

**Issue by alexnask** [ziglang/zig#1135]
Proposed structure:  

```zig
pub const FnDef = struct {
    fn_type: type,
    inline_type: Inline,
    calling_convention: CallingConvention,
    is_var_args: bool,
    is_extern: bool,
    is_export: bool,
    lib_name: ?[]const u8,
    return_type: type,
    arg_names: [][] const u8,
    ptr: *const u8, // <- New field, guaranteed to point to fn of type 'fn_type'

    pub const Inline = enum {
        Auto,
        Always,
        Never,
    };
};
```

With the current structure, if @reify/@makeType was implemented, there would be no way to generate methods for a type.  

This change would allow us to use the anonymous structure function trick or (eventually) function literals to generate methods for the types created.    

EDIT: 
Actually, this is just one of the changes that would need to be made to allow for method generation, the other issue being specifying the first argument type of the method when the type is not generated yet.

**Comment by andrewrk** [comment]
This is a bit tricky because the pointer type of the field would not be correct (`*u8` instead of fn proto) - or we would have to make `FnDef` generic. If we went with the "you have to cast the ptr field" approach, we might need to improve the comptime mechanism to support a comptime known pointer value that has the wrong type.

**Comment by andrewrk** [comment]
I think this is a reasonable approach. Let me have a discussion about `@reify` with @thejoshwolfe and see if we can come up with an accepted proposal.

**Comment by alexnask** [comment]
In addition to this, TypeInfo.Definition.Data.Var could be some type erased value (to allow reify-ing non type definitions)

**Comment by andrewrk** [comment]
We now have the ability to have fields of type `var` when the struct is comptime known. So the problem this issue tackles is solved. Whether to put function definitions into that struct is the same issue as #383.

**Comment by alexnask** [comment]
Great to see the comptime capabilities increasing, I'll have to catch up on the changes so I can maybe take a stab at #2907 :)
