### ISSUE TITLE
C backend cannot compile function calls with constant arrays as arguments

### ISSUE THREAD

**Issue by AnnikaCodes** [ziglang/zig#11368]
### Zig Version

0.10.0-dev.1693+243afdcdf

### Steps to Reproduce

To reproduce this bug, save the following Zig code to a file named `bug.zig`:
```zig
pub fn main() void {
    callee(.{1});
}

fn callee(x: [1]u8) void {
    _ = x;
}
```

Then, attempt to compile this with Zig's C backend:
```bash
zig build-exe bug.zig -fno-LLVM -ofmt=c
zig cc bug.c 
```

### Expected Behavior

It should compile successfully, as it does when using Zig's LLVM backend (`zig build-exe bug.zig`).

### Actual Behavior

What actually happens is that Zig emits C code seemingly without error, but the C code cannot be compiled by C compilers (`clang`, `gcc`, `zig cc`):
```
bug.c:841:13: error: expected expression
 bug_callee({1u});
            ^
1 error generated.
```

Here's the relevant snippet of Zig-emitted C code:
```c
static void bug_main(void) {
 /* file:2:5 */
 /* file:2:11 */
 bug_callee({1u});
 return;
}
```

I'm not very good with C, but I'm pretty sure this is supposed to be casted
```c
static void bug_main(void) {
 bug_callee((uint8_t[]){1u});
 return;
}
```
or declared as a variable first
```c
static void bug_main(void) {
 uint8_t a[] = {1u};
 bug_callee(a);
 return;
}
```

**Comment by viriuwu** [comment]
> I'm not very good with C, but I'm pretty sure this is supposed to be casted `bug_callee((uint8_t[]){1u});`

It should be noted that this *compound literal* syntax was added later in C99.
