### ISSUE TITLE
Proposal: `runtime` keyword

### ISSUE THREAD

**Issue by hollmmax** [ziglang/zig#11370]
# Motivation
> Zig places importance on the concept of whether an expression is known at compile-time. There are a few different places this concept is used, and these building blocks are used to keep the language small, readable, and powerful. 

This distinction however splits the language into 2 separate languages with different features, creating unnecessary mental burden. This proposal introduces the `runtime` keyword, which brings runtime Zig up to feature parity with comptime Zig.

# Proposal
> Runtime-time type parameters is how Zig should implement runtime generics. It is runtime-time duck typing.
```zig
fn max(runtime T: type, a: T, b: T) T {
    return if (a > b) a else b;
}
fn gimmeTheBiggerFloat(a: f32, b: f32) f32 {
    return max(f32, a, b);
}
fn gimmeTheBiggerInteger(a: u64, b: u64) u64 {
    return max(u64, a, b);
}
```
Calling `max` with `a` or `b` of type other than `T` results in a runtime error.

In Zig, types should be first-class citizens. They can be assigned to variables, passed as parameters to functions, and returned from functions. However, using a dynamic type must be known beforehand, which is why the parameter T in the above snippet must be marked with runtime.

With this proposal, it is now possible to write the following
```zig
const fmt = @import("std").fmt;

fn parse(str: []const u8) !struct {T: runtime type, val: T} {
    if (isInt(str)) {
        return .{.T = i64, .val = try fmt.parseInt(i64, str, 10)};
    } else if (isFloat(str)) {
        return .{.T = f32, .val = try fmt.parseFloat(f32, str)};
    } else {
        return error.invalidChar;
    }
}
```
As can be seen, the function can return different types depending on its input. The types are decided at runtime based on the argument runtime argument `str`. Furthermore, the possibly returned types don't have to have anything in common and can have different sizes as shown in the example. The value of `T` can even be a type returned from `@Type` called at runtime.

# Advantages
1. `runtime` allows for even more dynamic programs to be written in Zig, enabling it to truly become a general-purpose programming language.
2. `runtime` removes the unnecessary 2-language paradigm Zig currently struggles with by also allowing runtime to manipulate types. Anything that can be done at compile time can now also be done at run time.
4. `runtime` types do not have to be type-checked, improving compile times, which has recently become an important topic in the Zig community.

**Comment by nektro** [comment]
> Thank you for your interest in improving the Zig language. However, we are not accepting new proposals to change the language at this time.

**Comment by kubkon** [comment]
In light of #11371 and in particular:

> I am sorry to report this to you but by submitting this PR you are in violation of our Code of Conduct - you have created a PR which aims at deceiving the maintainers into landing this change which deletes all of Zig's implementation and instead introduce some random Python code. For this reason, I will bring this up to the lead maintainer, @andrewrk, immediately seeking to ban you from further interaction with this project and community.

I am closing this issue and reporting it as spam.
