### ISSUE TITLE
Segfault when adding `f128` on `i386-linux-gnu`

### ISSUE THREAD

**Issue by topolarity** [ziglang/zig#11383]
### Zig Version

0.10.0-dev.1724+51ef31a83

### Steps to Reproduce

Run the following test with `-target i386-linux-gnu`:
```zig
test {
    var x: f128 = 1.0;
    var y = x - 1.5;
    try expect(y == math.f64_max);
}
```

### Expected Behavior

Test should fail, not segfault.

### Actual Behavior

```bash
Test [1/1] test ""... Segmentation fault at address 0x0
???:?:?: 0x439e46 in ??? (???)
/home/topolarity/repos/zig/testme.zig:5:15: 0x40525c in test "" (test)
    var y = x - 1.5;
              ^
/home/topolarity/repos/zig/build/lib/zig/std/special/test_runner.zig:79:28: 0x420f73 in std.special.main (test)
        } else test_fn.func();
                           ^
/home/topolarity/repos/zig/build/lib/zig/std/start.zig:564:22: 0x41bf7a in std.start.callMain (test)
            root.main();
                     ^
/home/topolarity/repos/zig/build/lib/zig/std/start.zig:508:12: 0x406872 in std.start.callMainWithArgs (test)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/home/topolarity/repos/zig/build/lib/zig/std/start.zig:418:17: 0x405af2 in std.start.posixCallMainAndExit (test)
    std.os.exit(@call(.{ .modifier = .always_inline }, callMainWithArgs, .{ argc, argv, envp }));
                ^
/home/topolarity/repos/zig/build/lib/zig/std/start.zig:331:5: 0x40599d in std.start._start (test)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
error: the following test command crashed:
```

**Comment by topolarity** [comment]
It seems like the problem here is an ABI mismatch. LLVM lowers `fadd` to a call to `__addtf3`, which despite being intended to be a quadruple-precision operation, actually operates on long double. A [similar problem was fixed with the `fma` intrinsic](https://github.com/ziglang/zig/blob/b4bf3bdf7eac05c5e4ff887294385946f4dd5f3f/src/stage1/codegen.cpp#L842-L854), and we'll probably want to use the same solution:

We'll need to manually lower operations on f128 operations to full-precision softfloat routines on any platform whose long double is not f128.

What's not obvious to me is how the float types should be mapped to the function symbols in compiler-rt (`__addtf3`, `__addxf3`, etc.). Naively, we'd say that `__addtf3` is quadruple-precision and `__addxf3` is long double or f80, but clearly LLVM internally expects `__addtf3` to operate on long doubles

**Comment by matu3ba** [comment]
related #1481

**Comment by LewisGaul** [comment]
Dupe of https://github.com/ziglang/zig/issues/10199

**Comment by topolarity** [comment]
Thanks for the heads up @LewisGaul , missed that one
