### ISSUE TITLE
MinGW `-mwindows` flag support

### ISSUE THREAD

**Issue by wojtekmach** [ziglang/zig#11389]
I have this simple win32 program:

```cpp
#include <windows.h>

int WINAPI WinMain(HINSTANCE hInst, HINSTANCE hInstPrev, PSTR cmdline, int cmdshow)
{
    return MessageBox(NULL, "Hello, worl!", "Caption", 0);
}
```

Cross-compiling it from my Mac just works.

```
$ zig cc -o main.exe main.cpp -target x86_64-windows
```

(Which never ceases to amaze me.)

When starting the .exe from the Windows File Explorer, a terminal window shows up:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/76071/161837815-cb9211e0-e849-4f5d-b056-7d2d4f30f91f.png">

There are workarounds to make the terminal flash just briefly but that is still not ideal.

I found out there's a `-mwindows` flag I can pass when cross-compiling with MinGW:

```
$ x86_64-w64-mingw32-g++ -o main.exe main.cpp -mwindows
```

Without it, I have the same behaviour like with Zig, but _with_ it, there's no terminal window.

I wasn't able to determine what exactly that flag does. From little I was able to find it seems by default programs are built in the "console" mode and in this particular case we want the "GUI" mode.

Per:

```
$ x86_64-w64-mingw32-g++ --help | grep -- -m
Options starting with -g, -f, -m, -O, -W, or --param are automatically passed on to the various sub-processes invoked by x86_64-w64-mingw32-g++.
```

Perhaps it's:

```
$ x86_64-w64-mingw32-ld --help | grep -- -m
...
-m EMULATION                Set emulation
...
```

EDIT: it's not an ld flag. Possible options for `-m` are: `-mwindows`, `-mconsole`, and `-mdll`.

In any case, if it was desirable to expose this flag somehow, I'd be happy to look into it. If so, any pointers would be appreciated.

**Comment by wojtekmach** [comment]
Thank you. I did read this flag is another way to do it but I wasn’t sure where exactly to use it. For example folks where talking about linker properties file in msvc project but I’m not able to use that.

Could you show a `zig cc` invocation that uses this?

**Comment by Ristovski** [comment]
Clangs `lld` (in the case of targeting windows, `lld-link`) supports this:
```
$ lld-link -help | grep subsystem
  /subsystem:<value>      Specify subsystem
```

It appears that `zig cc` is unable to pass this to the linker (even with `-Xlinker`)

However, `zig build-exe` does support `--subsystem`: https://github.com/ziglang/zig/blob/master/src/main.zig#L430

**Comment by wojtekmach** [comment]
@Ristovski excellent, thank you.

Unfortunately I'm getting this error:

```
$ zig build-exe main.cpp -target x86_64-windows
error(compilation): clang failed with stderr: main.cpp:1:10: fatal error: 'windows.h' file not found

main.cpp:1:1: error: unable to build C object: clang exited with code 1
```

It looks like Zig is maybe not running in cross-compilation mode?

**Comment by leecannon** [comment]
@wojtekmach add `-lc`, zig will not link libc by default unless using `zig cc`

**Comment by Doekin** [comment]
Nice work! Both `zig build-exe -lc --subsystem windows` and `zig cc /SUBSYSTEM:WINDOWS` now successfully produce GUI programs. However, `zig cc -mwindows` does not work as expected, showing the following warning:  
```
zig: warning: argument unused during compilation: '-mwindows' [-Wunused-command-line-argument]
```

**Comment by Doekin** [comment]
Additionally, the `-mdll` flag is not functional. This flag, as defined by [GCC](https://gcc.gnu.org/onlinedocs/gcc/Cygwin-and-MinGW-Options.html#index-mdll) and [Clang](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-mdll-arg), is meant to generate dynamic link libraries. Attempting to use it results in an error:  
```
$ zig cc src/simple_dll.c -mdll
zig: warning: argument unused during compilation: '-mdll' [-Wunused-command-line-argument]
lld-link: error: undefined symbol: WinMain
>>> referenced by D:\Applications\Scoop\apps\zig\0.13.0\lib\libc\mingw\crt\crtexewin.c:67
>>>               mingw32.lib(crtexewin.obj):(main)
```

It would be helpful if support for these flags could be improved.
