### ISSUE TITLE
compiler panics when branching break on comptime

### ISSUE THREAD

**Issue by leesongun** [ziglang/zig#11424]
### Zig Version

0.10.0-dev.1741+d2681d253

### Steps to Reproduce

```Zig
export const a = init: {
    if (true)
        break :init true;
    break :init true;
};
```
[godbolt](https://godbolt.org/z/eo19McY9K)

checked locally with zig `0.10.0-dev.1741+d2681d253`, reproduced with godbolt.

### Expected Behavior

the program compiles

### Actual Behavior

```
when analyzing <source>:1:23 in compiler source at /workspace/src/stage1/ir.cpp:5626: thread 1 panic: assertion failed. This is a bug in the Zig compiler.
```

which is 
```cpp
static void ir_start_bb(IrAnalyze *ira, Stage1ZirBasicBlock *old_bb, Stage1ZirBasicBlock *const_predecessor_bb) {
    src_assert(!old_bb->suspended,
            (old_bb->instruction_list.length != 0) ?
            old_bb->instruction_list.at(0)->source_node : nullptr);
```

**Comment by leesongun** [comment]
duplicate of #7386

**Comment by jibal** [comment]
Why closed? I've encountered this panic. (Unfortunately I didn't note the code that caused it, but worked around it ... I hit several compiler bugs / day and have become sloppy about recording them.)

**Comment by leesongun** [comment]
duplicate of #7386?
