### ISSUE TITLE
Very confusing error missing context when type of `comptime T: type` differs from `var`'s type

### ISSUE THREAD

**Issue by r00ster91** [ziglang/zig#11436]
### Zig Version

0.9.1

### Steps to Reproduce

```zig
const std = @import("std");

pub fn main() void {
    var a: u32 = 1;
    var b: u32 = 2;
        
    std.mem.swap(u64, &a, &b);
}
```

### Expected Behavior

```
./x.zig:4:5: error: expected type '*u64', found '*u32'
    var a: u32 = 1;
    ^
./x.zig:4:5: note: pointer type child 'u32' cannot cast into pointer type child 'u64'
    var a: u32 = 1;
    ^
./x.zig:4:5: note: unsigned 64-bit int cannot represent all possible unsigned 32-bit values
    var a: u32 = 1;
    ^
./x.zig:7:5: note: type u64 differs from the types of `a` and `b`!
    std.mem.swap(u64, &a, &b);
    ^
```
The output should mention the `std.mem.swap` that caused the error. The error is that the type given for `std.mem.swap` differs from that of the operands. If `u64` is changed to `u32`, it works.

### Actual Behavior

```
./x.zig:4:5: error: expected type '*u64', found '*u32'
    var a: u32 = 1;
    ^
./x.zig:4:5: note: pointer type child 'u32' cannot cast into pointer type child 'u64'
    var a: u32 = 1;
    ^
./x.zig:4:5: note: unsigned 64-bit int cannot represent all possible unsigned 32-bit values
    var a: u32 = 1;
    ^
```
The error trace doesn't include the line that caused the error at all.

If you're unlucky and `std.mem.swap` is much further down somewhere in the scope, you're going to have a bad time.
In my case it was and I was extremely confused.

**Comment by viriuwu** [comment]
Side note, I think `swap` really should not have to take the type parameter as it can figure it out from the inputs, it's not a particularly crazy complicated function:
https://github.com/ziglang/zig/blob/2a00df9c091498268b58dd671f646a5590439b7a/lib/std/mem.zig#L2306-L2310
Similar to the change proposed by #5909.

**Comment by jibal** [comment]
It seems that some versions of zig reference the call site and some don't. From what I randomly have installed here,
yes: zig-linux-x86_64-0.9.0   zig-windows-x86_64-0.9.0 (windows) 0.10.0-dev.36+6fdf7ce0a
no: zig-linux-x86_64-0.10.0-dev.1699+8b5d5f44e

In any case,

"note: unsigned 64-bit int cannot represent all possible unsigned 32-bit values"

is factually false.

> I think `swap` really should not have to take the type parameter as it can figure it out from the inputs, it's not a particularly crazy complicated function:

This is true of most of the functions in std.mem. I've written my own wrappers that don't take a type parameter and pass the correct type to the corresponding std.mem function. In the case of `swap` I didn't bother to call out to `std.mem`:

```zig
pub inline fn swap(a: anytype, b: anytype) void {
    const tmp = a.*;
    a.* = b.*;
    b.* = tmp;
}
```

**Comment by r00ster91** [comment]
> It seems that some versions of zig reference the call site and some don't. From what I randomly have installed here,
yes: zig-linux-x86_64-0.9.0 zig-windows-x86_64-0.9.0 (windows) 0.10.0-dev.36+6fdf7ce0a
no: zig-linux-x86_64-0.10.0-dev.1699+8b5d5f44e

Interesting. So this is actually a regression and it used to work fine.
If you are saying that it worked at commit 6fdf7ce0a and stopped working before or at commit 8b5d5f44e,
`git log --oneline --ancestry-path 6fdf7ce0a~1..8b5d5f44e` should list the offending commit but that's a lot of commits so I'm not sure how useful it is.

In any case, when this is fixed, a test should be added to prevent this from happening again.

**Comment by jibal** [comment]
> So this is actually a regression and it used to work fine.

But your bug report says the call site isn't mentioned in 0.9.1 ... so it was ok in 0.9.0, not ok in 0.9.1, ok in  0.10.0-dev.36+6fdf7ce0a, not ok in 0.10.0-dev.1699+8b5d5f44e

**Comment by r00ster91** [comment]
Good point.

**Comment by Vexu** [comment]
The self-hosted compiler now gets this right with the nonsensical note removed in 0370006c1f5a23e5e2d0993fb71f825791d64957:
```
a.zig:10:23: error: expected type '*u64', found '*u32'
    std.mem.swap(u64, &a, &b);
                      ^~
a.zig:10:23: note: pointer type child 'u32' cannot cast into pointer type child 'u64'
```
