### ISSUE TITLE
Support Coercing an Anonymous Struct Literal to an Error Union

### ISSUE THREAD

**Issue by ominitay** [ziglang/zig#11443]
Disclaimer: This is kind-of a proposal and kind-of a bug, so I'm not sure how this should be labelled.

## The Problem
Presently, attempting to return a struct from a fallible function using an anonymous struct literal will fail, with the error: `type 'ErrorSet!StructType' does not support struct initialization syntax`. I believe this to be a deficiency in the current implementation of Zig, especially if #5038 were to be accepted and implemented. The current behaviour is an unnecessary implementation as far as I can tell, and makes code more verbose than necessary or desirable.

## The Solution
There are two possible solutions here. Firstly, to simply allow this coercion to be made. I don't see any fundamental contradictions here which would prevent this from working. Alternatively, #7812 would also address this, as `return`ing values would be separated from `throw`ing errors.

cc: @gracefuu 
related: #5038 #7812

**Comment by Vexu** [comment]
Something like this #10925?

**Comment by nektro** [comment]
yeah this is fixed in stage2. it was a limitation of the stage1 coercing checks but an easy fix since `.{ }` can never be an error value.

**Comment by ominitay** [comment]
Glad to see it's fixed in the self-hosted compiler! Apologies for opening this then, but GitHub's search feature isn't so helpful...
