### ISSUE TITLE
JSON stringify string setting affects keys

### ISSUE THREAD

**Issue by Sirius902** [ziglang/zig#11455]
### Zig Version

0.10.0-dev.1860+7b090df66

### Steps to Reproduce

```zig
const std = @import("std");

const Foo = struct {
    bar: []const u8,
};

pub fn main() !void {
    const foo = Foo{ .bar = "donuts" };
    const stdOut = std.io.getStdOut();
    try std.json.stringify(foo, .{ .string = .Array }, stdOut.writer());
}
```

### Expected Behavior

I would expect the output of the above program to be the following:
```
{"bar":[100,111,110,117,116,115]}
```

### Actual Behavior

The program outputs the following:
```
{[98,97,114]:[100,111,110,117,116,115]}
```
I would also like to note that  `std.json.parse` cannot parse the above string.

**Comment by OfekShochat** [comment]
I can try doing that as a first contribution! In ~12 hours I can start on this?

**Comment by OfekShochat** [comment]
lol building the compiler gives me a segfault

**Comment by OfekShochat** [comment]
wow Im embarrassed in how much time that took. though it wasnt in actually programming, but trying to first make the compiler compile (which wasnt necessary and doesnt work, some weird link errors) #11459 should close this

**Comment by andrewrk** [comment]
Would appreciate if you mentioned specifically a bug report that documents the compiler not compiling. There is nothing we can do about "it doesn't work" other than say, "it does work, actually". Bug reports need to have steps to reproduce, expected behavior, and actual behavior.

**Comment by OfekShochat** [comment]
Hello, didn't mean it like that, it's just that I have problems like this often on my machine and I should just check it, just explaining why it took so long.

**Comment by luehmann** [comment]
Hey @OfekShochat, I don't know if you are still working on it. I opened a pull-request with the solution I found. I hope that's fine for you. I'd be interested how you solved it
