### ISSUE TITLE
Add test case for every compiler fix

### ISSUE THREAD

**Issue by isaachier** [ziglang/zig#1146]
I think it is worthwhile to add a directory of code that at one point or another failed compilation. That way, regression can be easily detected by running the compiler on the inputs. For example, adding the code for #1111 to a file `issue1111.zig` can prevent it from ever occurring again. Also, it is a good way to verify a certain fix resolves the issue. In the example above, my fix #1145 should include the code `issue1111.zig` that could be run in a Travis CI build to show that the fix truly resolves the compilation error that existed previously.

**Comment by andrewrk** [comment]
We have this, and it's `test/behavior.zig`. This file imports a bunch of other test cases (including `test/cases/bugs`) and if you look through commit history you'll see that there is a new behavioral test for every bug fix.

This is the command you can run to make sure you don't regress any bugs:

`make install && ./zig test ../test/behavior.zig`

Of course the main test suite runs these, for every build mode and every operating system, as well as other classes of tests. 

It looks like you followed this practice in your pull request - thanks!

**Comment by isaachier** [comment]
Cool good to know. Thanks for the explanation.
