### ISSUE TITLE
 @setRuntimeSafety(false); not functioning as expected

### ISSUE THREAD

**Issue by jhenzie** [ziglang/zig#11473]
### Zig Version

0.9.1

### Steps to Reproduce

Following the examples at https://ziglearn.org/chapter-1/

Input the following:

test "out of bounds, runtime safety off" {
    @setRuntimeSafety(false);

    const a = [3]u8{ 1, 2, 3 };
    const index: u8 = 5;
    const b = a[index];
    _ = b;
}

### Expected Behavior

Expected the test to supress runtime bounds checking.

### Actual Behavior

zig test "d:/zig/learn/chapter_1/basics.zig" "-O" "Debug"

D:\zig\learn\chapter_1\basics.zig:211:16: error: index 5 outside array of size 3
    const b = a[index];
               ^

Compilation exited abnormally with code 1 at Tue Apr 19 13:21:03

**Comment by Vexu** [comment]
You're turning the runtime safety off but that array access is happening at comptime since all the values are comptime known.

**Comment by jhenzie** [comment]
Thank you for the information.  Does that not warrant a warning for the function? I'll close it but I think that this will be confusing for many newcomers.

**Comment by jibal** [comment]
What function? And Zig doesn't have warnings, only errors. How is this confusing? The out-of-bounds access is illegal and Zig says so. The only reason to turn off runtime safety is for performance when you know that no illegal operations will be performed.

**Comment by jhenzie** [comment]
@vexu Great example of a thoughtful and helpful response. Allowed me to submit a proposed, if naive, change to ziglearn to ensure the test functions as intended. Also introduced me to the realization that I need to be able to reason about what is comptime and runtime wrt to Zig.
