### ISSUE TITLE
Child process spawn on macos hangs with stdin, stdout behavior set to pipe

### ISSUE THREAD

**Issue by rabingaire** [ziglang/zig#11470]
### Zig Version

0.10.0-dev.3886+7b090df66

### Steps to Reproduce

The following program is trying to spawn a child process that receives its input piped to stdin and returns its output piped to stdout.

```zig
const std = @import("std");

pub fn main() anyerror!void {
  var allocator = std.heap.page_allocator;
  
  var process = try std.ChildProcess.init(&[_][]const u8{ "zig", "fmt", "--stdin" }, allocator);
  defer process.deinit();

  process.stdin_behavior = .Pipe;
  process.stdout_behavior = .Pipe;

  process.spawn() catch |err| {
    std.debug.print("{s}\n", .{err});
    return;
  };

  const string_value =
    \\ const std = @import("std");
    \\ pub fn main() void {
    \\ std.debug.print("Hello World", .{});
    \\ }
  ;

  try process.stdin.?.writer().writeAll(string_value);
  process.stdin.?.close();
  process.stdin = null;
  
  std.debug.print("My PID {d}\n", .{process.pid});

  const stdout_bytes = try process.stdout.?.reader().readAllAlloc(allocator, std.math.maxInt(usize));
  defer allocator.free(stdout_bytes);
  
  switch (try process.wait()) {
    .Exited => |code| if (code == 0) {
      std.debug.print("{s}\n", .{stdout_bytes});
    },
    else => {}
  }
}

```

**Machine Used:**
> Model Name: MacBook Pro
> Model Identifier: MacBookPro17,1
> Chip: Apple M1
> Total Number of Cores: 8 (4 performance and 4 efficiency)
> Memory: 16 GB
> System Firmware Version: 7459.101.3
> OS Loader Version: 7459.101.3

_Note: I ran this same program on Linux machine and it runs like expected._

### Expected Behavior

The program should exit and print the formatted source code on the screen.

### Actual Behavior

The program prints the PID successfully and hangs.

**Comment by matu3ba** [comment]
`process.stdin.?.close();` does invalidate the descriptor, so its not usable anymore:
```zig
    /// Upon success, the stream is in an uninitialized state. To continue using it,
    /// you must use the open() function.
    pub fn close(self: File) void {
```

**Comment by rabingaire** [comment]
> `process.stdin.?.close();` does invalidate the descriptor, so its not usable anymore:
> 
> ```zig
>     /// Upon success, the stream is in an uninitialized state. To continue using it,
>     /// you must use the open() function.
>     pub fn close(self: File) void {
> ```
> 
> You probably want to defer closing it.

I am confused, once I spawn a process and write to the stdin descriptor, I don't need it anymore It should be safe for me to close it. I tried the defer approach but still, it does not work. 

Here's something I looked at:
If you look at the `child_process.zig/spawn` function there is a code path that does mac-specific syscalls to spawn the child process. I commented it to force the compiler to use the posix code path and in doing so it worked. So I am guessing there is something wrong while spawning child process using mac specific (or FreeBSD) syscalls.

**Comment by matu3ba** [comment]
@rabingaire True, my bad.

> there is a code path that does mac-specific syscalls

The only Mac specific ones I see are
```zig
        var attr = try os.posix_spawn.Attr.init();
        defer attr.deinit();
        var flags: u16 = os.darwin.POSIX_SPAWN_SETSIGDEF | os.darwin.POSIX_SPAWN_SETSIGMASK;
        if (self.disable_aslr) {
            flags |= os.darwin._POSIX_SPAWN_DISABLE_ASLR;
        }
        try attr.set(flags);
```
1. This code path or which one?
2. Did you try `disable_aslr = true` ?

**Comment by rabingaire** [comment]
I tried `disable_aslr = true` and it still is stuck trying to read from the reader (it can't as there is no data yet).

Sorry, I was not clear but I meant the `spawnMacos` function inside `child_process.zig` it uses the `posix_spawnp` syscall. I am not that familiar with this stuff and could not figure out the issue.

One thing I did was 
I removed darwin specific code path from this
```zig
pub fn spawn(self: *ChildProcess) SpawnError!void {
        if (!std.process.can_spawn) {
            @compileError("the target operating system cannot spawn processes");
        }

        if (comptime builtin.target.isDarwin()) {
            return self.spawnMacos();
        }

        if (builtin.os.tag == .windows) {
            return self.spawnWindows();
        } else {
            return self.spawnPosix();
        }
    }
```
to this
```zig
pub fn spawn(self: *ChildProcess) SpawnError!void {
        if (!std.process.can_spawn) {
            @compileError("the target operating system cannot spawn processes");
        }

        if (builtin.os.tag == .windows) {
            return self.spawnWindows();
        } else {
            return self.spawnPosix();
        }
    }
```
now it uses `fork` syscall instead of `posix_spawnp` and it works. What I am assuming is there is something wrong with the setup we do leading that `posix_spawnp` syscall.

**Comment by matu3ba** [comment]
This was introduced in dd55b729 as one big commit without test coverage, so it is very likely it was not sufficiently tested.

**Comment by rabingaire** [comment]
Yeah I will look into this, let's see If I can figure this out
