### ISSUE TITLE
comparison between nullable values and void crashes compiler

### ISSUE THREAD

**Issue by Rekihyt** [ziglang/zig#11475]
### Zig Version

0.10.0-dev.1689+08565b23f

### Steps to Reproduce

Compare a variable of type `?void` initialized with `{}` to `{}`: 
```zig
    var x: ?void = {};
    _ = x == {};
```

### Expected Behavior

should compile and run.

### Actual Behavior

Semantic Analysis [1499/1554] Unreachable at /workspace/src/stage1/codegen.cpp:3561 in ir_render_bin_op. This is a bug in the Zig compiler.thread 36470 panic: 
Unable to dump stack trace: debug info stripped
test...The following command terminated unexpectedly:

**Comment by Rekihyt** [comment]
Possibly related or might be a new issue, adding a pointer and comparing with `null` instead of `&{}` creates a similar crash only on the first `zig build test` invocation, but not for any subsequent ones.
```zig
    var x: ?*void = {};
    _ = x == &{};
```

**Comment by Rekihyt** [comment]
messed up the tests, I think this is only for hashmaps.

**Comment by Vexu** [comment]
Fixed in master branch.
