### ISSUE TITLE
unaligned bitcast causes segfault

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1148]
notice the alignment of these:

```zig
test "aoeou" {
    @compileLog(@alignOf(u128));
    @compileLog(@alignOf(f128));
}
```
output:
```
| 8
| 16
```

when adding a compiler-rt function,  I got a segfault because I did `@bitCast(f128, result)`, where `result` was a stack variable that was only aligned to 8 bytes and not 16 bytes:

```
=> 0x00000000006a53b4 <+676>:	movaps -0xa8(%rbp),%xmm0
(gdb) p &result
$1 = (u128 *) 0x7fffffffa768
(gdb) p 0x7fffffffa768 % 16
$2 = 8
```

`@bitCast` needs to detect the alignment of its parameter and emit a compile error if it is not aligned enough.

**Comment by eduardosm** [comment]
```
export fn test_fn(x: *const u128) f128 {
    return @bitCast(f128, x.*) + 1;
}
```
produces the following LLVM IR (with `--release-fast`):
```llvm
; Function Attrs: nobuiltin nounwind readonly
define fp128 @test_fn(i128* nocapture nonnull readonly) local_unnamed_addr #0 !dbg !303 {
Entry:
  call void @llvm.dbg.value(metadata i128* %0, metadata !311, metadata !DIExpression()), !dbg !312
  %1 = bitcast i128* %0 to fp128*, !dbg !313
  %2 = load fp128, fp128* %1, align 8, !dbg !313
  %3 = fadd fast fp128 %2, 0xL00000000000000003FFF000000000000, !dbg !316
  ret fp128 %3, !dbg !317
}
```
and assembly:
```asm
test_fn:
	pushq	%rax
	movaps	(%rdi), %xmm0
	movaps	.LCPI0_0(%rip), %xmm1
	callq	__addtf3@PLT
	popq	%rax
	retq
```

The LLVM `load` instruction has an explicit `align 8`, but it emits a `movaps`, which expects a 16-byte alignment. It seems to be a LLVM bug.

**Comment by eduardosm** [comment]
I have submitted a LLVM bug report: https://bugs.llvm.org/show_bug.cgi?id=38001

**Comment by andrewrk** [comment]
Thanks for filing the LLVM bug report.

I'll leave this issue open so that after the LLVM bug is fixed, we can inspect the generated assembly code. If the optimizer does not figure out to align the variable so that the emitted instruction can be a simple `movaps` then zig should still have some type mechanism to make it hard to accidentally mess up this alignment and generate suboptimal code.

**Comment by andrewrk** [comment]
Wonderful. Thanks for the followup. In this case I think the issue is resolved.
