### ISSUE TITLE
Zig translate-c crashes with Illegal Instruction on some C files

### ISSUE THREAD

**Issue by tekktonic** [ziglang/zig#11481]
### Zig Version

0.10.0-dev.1888+e3cbea934

### Steps to Reproduce

Download an offending file (I ran into this while trying to compile unqlite. the files `jx9_builtin.c`, `jx9.h`, `jx9Int.h`, and `unqlite.h` from https://github.com/symisc/unqlite/tree/master/src should do.) `jx9_vm.c` will also work as a C input. I originally ran into it while trying to compile the bundled `unqlite.c` file at the top level.

Run `zig translate-c -lc jx9_builtin.c`

### Expected Behavior

The file is translated into zig

### Actual Behavior

The compiler crashes with `SIGILL`

**Comment by tekktonic** [comment]
This was generated using the linux-x86_64 nightly binary build. I also tried with the 0.9.1 linux-x86_64 build and it segfaulted.

**Comment by Vexu** [comment]
Reduction:
```c
static const char zUnit[] = {"KMGTPEZ"};
```

**Comment by ehaas** [comment]
Relevant rule from the C standard:

> An array of character type may be initialized by a character string literal, optionally enclosed in braces. Successive characters of the character string literal (including the terminating null character if there is room or if the array is of unknown size) initialize the elements of the array.

So it looks like a special case that needs to be handled in `transInitListExprArray`
