### ISSUE TITLE
`MultiArrayList` inefficient for types < 1 byte

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#11493]
### Zig Version

0.10.0-dev.1120+0ea51f7f4

### Steps to Reproduce

1. Run this code which allocates `[48]Foo` in a `MultiArrayList`
```zig
pub fn main() anyerror!void {}
const std = @import("std");

const Foo = struct {
    bar: bool = false,

    pub const List = std.MultiArrayList(Foo);
};

test "length" {
    var buf: [8096]u8 = undefined;
    var fixed = std.heap.FixedBufferAllocator.init(&buf);
    var list = Foo.List{};
    try list.ensureTotalCapacity(fixed.allocator(), 48);
    if (fixed.end_index > 24)
        std.debug.panic("Expected less than 1 byte per element (48), but allocated {d} bytes", .{fixed.end_index});
    try std.testing.expect(fixed.end_index < 48);
}

```
2. `zig test file.zig`

### Expected Behavior

Since `bool` is a 1 bit type, a `[48]bool` in a `std.MutliArrayList` should occupy around 6 bytes instead of 48 bytes + padding.

### Actual Behavior

This test allocates 65 bytes on macOS aarch64

```zig
Test [1/1] test "length"... thread 37118275 panic: Expected less than 1 byte per element (48), but allocated 65 bytes
/Users/jarred/Build/zig/lib/std/debug.zig:264:22: 0x104495977 in std.debug.panicExtra (test)
    std.builtin.panic(msg, trace);
                     ^
error: the following test command crashed:
/Users/jarred/Desktop/zig-cache/o/8a996ad62bb2f7bd80652fc0bb14c2fc/test /Users/jarred/Build/zig/zig
```

**Comment by leecannon** [comment]
`bool` is 1 byte not 1 bit in a non-packed struct
```zig
const Foo = struct {
    bar: bool,
};

comptime {
    @compileLog(@sizeOf(Foo), @bitSizeOf(Foo));
}
```
```
$ zig build
| 1, 8
./src/main.zig:10:5: error: found compile log statement
    @compileLog(@sizeOf(Foo), @bitSizeOf(Foo));
```

**Comment by Jarred-Sumner** [comment]
> bool is 1 byte not 1 bit in a non-packed struct, arrays in zig are not packed

Ah, I see.

I guess I expected `std.MultiArrayList` to behave similarly to `packed` structs due to this doc comment:
> Instead of storing a single list of items, MultiArrayList
> stores separate lists for each field of the struct.
>  This allows for memory savings if the struct has padding,
> and also improves cache usage if only some fields are needed
> for a computation.  The primary API for accessing fields is

**Comment by martinhath** [comment]
The problem is that `[8]bool` is still 8 bytes, and not one byte, and arrays of bools are not allowed in `packed struct`s. If you put all `bools` as fields instead, it works though. It's kinda confusing.

```zig
 const SingleBool = struct {
     bar: bool,
 };

 const EightBools = struct {
     bar: [8]bool,
 };

 const PackedEightBools = packed struct {
     bar: [8]bool,
 };

 const PackedEightBoolsInline = packed struct {
     b0: bool,
     b1: bool,
     b2: bool,
     b3: bool,
     b4: bool,
     b5: bool,
     b6: bool,
     b7: bool,
 };

 comptime {
     @compileLog(@sizeOf(SingleBool), @bitSizeOf(SingleBool));
     @compileLog(@sizeOf(EightBools), @bitSizeOf(EightBools));
     @compileLog(@sizeOf(PackedEightBoolsInline), @bitSizeOf(PackedEightBoolsInline));
     @compileLog(@sizeOf(PackedEightBools), @bitSizeOf(PackedEightBools));
 }
```

```
| 1, 8
| 8, 64
| 1, 8
| ./src/main.zig:60:5: error: found compile log statement
    @compileLog(@sizeOf(SingleBool), @bitSizeOf(SingleBool));
    ^
./src/main.zig:61:5: error: found compile log statement
    @compileLog(@sizeOf(EightBools), @bitSizeOf(EightBools));
    ^
./src/main.zig:62:5: error: found compile log statement
    @compileLog(@sizeOf(PackedEightBoolsInline), @bitSizeOf(PackedEightBoolsInline));
    ^
./src/main.zig:45:5: error: array of 'bool' not allowed in packed struct due to padding bits (must be padded from 8 to 64 bits)
    bar: [8]bool,
    ^
```

**Comment by squeek502** [comment]
Something else worth noting here is that `ensureTotalCapacity` will not give you the exact capacity that you ask for--it calculates a 'better capacity' and uses that instead (from the doc comment: "`Implements super-linear growth to achieve amortized O(1) append operations.`").

Relevant links:
- https://github.com/ziglang/zig/issues/9775
- https://github.com/ziglang/zig/pull/10077

It's possible that `MultiArrayList` would benefit from an `ensureTotalCapacityPrecise` as well, a la `ArrayList` in f49d42729a22846ec54b6610db415ac8cdaa31db

**Comment by andrewrk** [comment]
Working as designed
