### ISSUE TITLE
@alignCast bug

### ISSUE THREAD

**Issue by fubark** [ziglang/zig#11495]
### Zig Version

0.10.0-dev.1871+b03345f32

### Steps to Reproduce

```
test "@alignCast triggers runtime check when taking a comptime expression." {
    var aligned_addr: usize = 1;
    const ptr = @intToPtr(*align(1) u32, aligned_addr);
    const alignment = @typeInfo(*u32).Pointer.alignment;
    try t.expectEqual(alignment, 4);
    const unaligned_ptr = @alignCast(alignment, ptr);
    try t.expectEqual(std.mem.isAligned(@ptrToInt(unaligned_ptr), alignment), false);
}
```

### Expected Behavior

I expected a runtime error at the @alignCast and the last assert statement shouldn't have run.

### Actual Behavior

No runtime error and the test passes.

I noticed if I set the alignment var with `const alignment = 4;`, the test does trigger the runtime check and test fails.

**Comment by Vexu** [comment]
This now panics at runtime as expected.
