### ISSUE TITLE
zig 0.9.1 compiler crash at stage1/ir.cpp:23023 in buf_write_value_bytes

### ISSUE THREAD

**Issue by mewmew** [ziglang/zig#11496]
### Zig Version

0.9.1

### Steps to Reproduce

I was using `zig translate-c` and tried to compile the output Zig source code. This uncovered a crash in the Zig compiler. Below is a minimized example which crashes reproducibly on my computer.

Contents of `a.zig`:
```zig
pub const T = extern struct {
    field: [*c]u8,
};
pub export var v: T = @import("std").mem.zeroes(T);
```

Compile using Zig 0.9.1.

```bash
$ zig build-obj a.zig
Unreachable at /usr/src/debug/zig-0.9.1/src/stage1/ir.cpp:23023 in buf_write_value_bytes. This is a bug in the Zig compiler.

...
```

I'm using `zig` 0.9.1 from Arch Linux pacman (which unfortunately is stripped of debug symbols).

```
$ pacman -Q zig
zig 0.9.1-1
```

### Expected Behavior

Successful build.

### Actual Behavior

```bash
$ zig build-obj a.zig
Unreachable at /usr/src/debug/zig-0.9.1/src/stage1/ir.cpp:23023 in buf_write_value_bytes. This is a bug in the Zig compiler.thread 63163 panic: 
Unable to dump stack trace: debug info stripped
fish: Job 1, 'zig build-obj a.zig' terminated by signal SIGABRT (Abort)
```

**Comment by mewmew** [comment]
Note, removing `extern` from `extern struct T` results in a successful build (without crash). So does removing `export` from `export var v`.

**Comment by Namek** [comment]
I have a similar case:

```
TODO buf_write_value_bytes maybe typethread 12704 panic:
Unable to dump stack trace: debug info stripped
```

It seems that this exact line causes the issue: `set(u8, asBytes(&item), 0);`
https://github.com/ziglang/zig/blob/master/lib/std/mem.zig#L273

It's not even the `asBytes` call, it's the `set`. The original impl is:

```zig
for (dest) |*d|
    d.* = value;
```

So I even replaced the `set` call with:

```zig
for (bytes) |*b| {
    std.debug.print("{d}",b);
```

and it still happens, so I would suppose it's an issue of the foreach loop.

**Comment by baines** [comment]
I believe I'm hitting the same issue. Tested with both zig `0.9.1` and `0.10.0-dev.4060+61aaef0b0`.

main.zig:
```zig
const std = @import("std");

pub const Example = extern struct {
    name: [*c]const u8,
};

const thing = std.mem.zeroes(Example);

export fn entrypoint(output: **const Example) void {
    output.* = &thing;
}
```

build.zig:
```zig
const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    const mode = b.standardReleaseOptions();
    const lib = b.addSharedLibrary("mod_zig", "src/main.zig", b.version(0, 0, 1));
    lib.linkLibC();
    lib.setBuildMode(mode);
    lib.install();
}
```

Error from zig 0.9.1:
```
Unreachable at /home/andy/dev/bootstrap-zig/zig/src/stage1/ir.cpp:23023 in buf_write_value_bytes. This is a bug in the Zig compiler.thread 112722 panic: 
```

Error from zig 0.10.0-dev.4060+61aaef0b0:
```
thread 112922 panic: TODO implement readFromMemory for more types
Unable to dump stack trace: debug info stripped
```

Removing `extern` from the struct allows it to compile, but I need the struct to have C layout for compatibility with an external program's plugin system.

**Comment by Diegovsky** [comment]
I get this bug but I don't have any `extern` structs. I do, however, import some C code, specifically gobject introspection's `girepository.h`

**Comment by monomycelium** [comment]
I get a similar issue with compiler version `0.11.0-dev.3395+1e7dcaa3a`. When I try `std.mem.zeroes` to zero-out an `extern` struct (that I defined myself) in a `comptime` block:
``` zig
var request = comptime mem.zeroes(uapi.LineRequest);
```
I get this error (using the official build of the compiler):
``` text
thread 22584 panic: TODO implement readFromMemory for more types
Unable to dump stack trace: debug info stripped
```

I wanted to do that at compile-time since the ABI I am interfacing expects certain fields of the `struct` to be zeroed-out, but I wanted to avoid the runtime overhead.

**Comment by Vexu** [comment]
Fixed in master.
