### ISSUE TITLE
Malformed Wasm binaries with `@extern`'s `std.builtin.GlobalLinkage`

### ISSUE THREAD

**Issue by r00ster91** [ziglang/zig#11505]
Version is 0.10.0-dev.4176+6d7b0690a (stage2).

```zig
pub fn main() void {
    const a = @extern(*const fn ([*]const u8) void, .{
        .name = "a",
        .library_name = "b",
        .linkage = .Strong, // or `.Weak`
        .is_thread_local = false,
    });
    a("hello");
}
```
```
zig build-exe -target wasm32-freestanding-none -O ReleaseSmall x.zig
```
This seems to generate malformed Wasm?
```
$ wasm2wat x.wasm
x.wasm:0000048: error: type mismatch at end of function, expected [] but got [i32]
```

**Comment by r00ster91** [comment]
I've updated this for stage2 so the stage1 label can be removed.

**Comment by Luukdegram** [comment]
Thanks to #14102 this now generates the proper `undefined symbol 'a'` linker error as it does with other platforms such as ELF/MachO. When forced with `--import-symbols` it does however generate a proper Wasm binary:
```sh
> wasm-validate x.wasm
> $?
0
```

Note this imports a function pointer, not a function symbol, and therefore will not generate an `import` entry in the WebAssembly module.
