### ISSUE TITLE
cmake Build Error

### ISSUE THREAD

**Issue by AnimalStudioOfficial** [ziglang/zig#11500]
### Zig Version

0.10.0

### Steps to Reproduce

run: cmake ..

### Expected Behavior

I want to build the project

### Actual Behavior

Output:
# cmake ..
System is unknown to cmake, create:
Platform/MINGW64_NT-10.0-19043 to use this system, please post your config file on discourse.cmake.org so it can be added to cmake
Your CMakeCache.txt file was copied to CopyOfCMakeCache.txt. Please post that file on discourse.cmake.org.
-- Configuring zig version 0.10.0
CMake Error at cmake/Findllvm.cmake:96 (message):
  expected LLVM 13.x but found 14.0.0 using /clang64/bin/llvm-config.exe
Call Stack (most recent call first):
  CMakeLists.txt:107 (find_package)

-- Configuring incomplete, errors occurred!
See also "/c/zig-master/zig-master/build/CMakeFiles/CMakeOutput.log".

**Comment by Luukdegram** [comment]
> expected LLVM 13.x but found 14.0.0 using /clang64/bin/llvm-config.exe

Seems the fix is right in the error message ;)
The Zig toolchain is still using LLVM 13, rather than 14. You'll have to install LLVM 13 and point Cmake to its installation path using `-DCMAKE_PREFIX_PATH=<path>`

**Comment by AnimalStudioOfficial** [comment]
> > expected LLVM 13.x but found 14.0.0 using /clang64/bin/llvm-config.exe
> 
> Seems the fix is right in the error message ;) The Zig toolchain is still using LLVM 13, rather than 14. You'll have to install LLVM 13 and point Cmake to its installation path using `-DCMAKE_PREFIX_PATH=<path>`

I did that and got a Output:

$ cmake .. -DCMAKE_PREFIX_PATH=<C:\LLVM\bin>
-bash: syntax error near unexpected token `newline'

**Comment by matu3ba** [comment]
should be `cmake .. -DCMAKE_PREFIX_PATH=C:\LLVM\bin`, though not sure about amount of backslashes or slashes.

**Comment by AnimalStudioOfficial** [comment]
> cmake .. -DCMAKE_PREFIX_PATH=C:\LLVM\bin

I Did that and got:

$ cmake .. -DCMAKE_PREFIX_PATH=C:\LLVM\bin
-- Configuring zig version 0.10.0
CMake Error at cmake/Findllvm.cmake:80 (message):
  unable to find llvm-config
Call Stack (most recent call first):
  CMakeLists.txt:109 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/zig-master/zig-master/Build/CMakeFiles/CMakeOutput.log".

**Comment by andrewrk** [comment]
Please ask for help in one of the [community spaces](https://github.com/ziglang/zig/wiki/Community).
