### ISSUE TITLE
Compiler crashes (exit code 11) on certain padding lengths with packed structs

### ISSUE THREAD

**Issue by I-mikan-I** [ziglang/zig#11515]
### Zig Version

0.9.1

### Steps to Reproduce

Try to compile the following program:

```zig
pub const ObjType = enum(u8) {
    obj_string,
};

pub const Obj = packed struct {
    const Self = @This();
    t: ObjType,

    pub fn asString(self: *Self) *ObjString {
        const t = @ptrToInt(self);
        return @intToPtr(*ObjString, t);
    }

    pub fn print(self: *Self, writer: anytype) void {
        switch (self.t) {
            .obj_string => {
                writer.print("{s}", .{self.asString().chars[0..self.asString().length]}) catch unreachable;
            },
        }
    }
};

pub const ObjString = packed struct {
    obj: Obj,
    pad: [7]u8 = undefined,
    length: usize,
    chars: [*]u8,
};

pub fn main() anyerror!void {
    var o = Obj{.t = .obj_string};
    var p: *Obj = &o;
    p.print(std.io.getStdOut().writer());
    return;
}

```

### Expected Behavior

The code compiles or fails with an error message.

### Actual Behavior

On my machine, compiling the code with pad being [7]u8 fails with no error message:
```bash
$ zig build
..The following command terminated unexpectedly:
/usr/bin/zig build-exe /main.zig ...
error: the following build command failed with exit code 11:
/path-to-zig-cache/o/fbd17e15f366094c0fa0f9063167872f/build ...
```
But when i set the padding to other types, like [8]u8, it compiles with no issue.

**Comment by inkeliz** [comment]
I hit the same issue, but I manage to compile with `0.10.0-dev.2024+d127c1d59`, however it crashes on Zig 9.1.

**Comment by ominitay** [comment]
This affects stage1 as of `0.10.0-dev.3659+e5e6eb983`, but does not affect stage2, as packed structs cannot contain array fields. Could be a stage1 regression between `d127c1d59` and `e5e6eb983`? It's probably not worth fixing, considering that stage2 will be released in a month.

**Comment by inkeliz** [comment]
>  but does not affect stage2, as packed structs cannot contain array fields

So, the only way to create one struct with specific size (or specific padding) is creating a lot of `u64`, `u32`, `u16`, `u8` fields?

Considering something like:

```
pub const DataViewer = packed struct {
    _data: [11]u8,
}
```

Should I change to:

```
pub const DataViewer = packed struct {
    _1: u64,
    _2: u16,
    _3: u8,
}
```

The same will apply for padding, instead of `[3]u8`, will need to change to `u8` + `u16`?

**Comment by Vexu** [comment]
Arrays don't work with the new packed struct semantics https://github.com/ziglang/zig/issues/10113#issuecomment-1036713233

**Comment by ominitay** [comment]
> >  but does not affect stage2, as packed structs cannot contain array fields
> 
> So, the only way to create one struct with specific size (or specific padding) is creating a lot of `u64`, `u32`, `u16`, `u8` fields?
> 
> Considering something like:
> 
> ```
> pub const DataViewer = packed struct {
>     _data: [11]u8,
> }
> ```
> 
> Should I change to:
> 
> ```
> pub const DataViewer = packed struct {
>     _1: u64,
>     _2: u16,
>     _3: u8,
> }
> ```
> 
> The same will apply for padding, instead of `[3]u8`, will need to change to `u8` + `u16`? _I don't understand why the compiler can't do it._
> 
> 

Zig has arbitrary integer sizes. Use `u24` etc.

**Comment by Vexu** [comment]
Arrays are no longer allowed in packed structs.
