### ISSUE TITLE
Unable to get comptime pointer to struct field at fixed address

### ISSUE THREAD

**Issue by locriacyber** [ziglang/zig#11538]
This is useful for memory mapped IO where a struct has fixed layout.

### Zig Version

0.10.0-dev.1919+5da0e0355

### Steps to Reproduce

Compile and run the following code
```
const std = @import("std");

const Foo = struct {
    bar: i32,
};

const foo: *Foo = @intToPtr(*Foo, 0x08000000);
const bar = &foo.bar;

pub fn main() anyerror!void {
    std.debug.print("{}\n", .{bar});
}
```

### Expected Behavior

No compile error.

### Actual Behavior

```
./src/main.zig:8:13: error: cannot store runtime value in compile time variable
const bar = &foo.bar;
```

**Comment by Vexu** [comment]
Same root cause as #5344 and #6789 (and at least one issue that I can't find right now).
