### ISSUE TITLE
pass by value should perform a memcpy for async functions

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1155]
With existing semantics, this is too easy to do by accident:

```zig
const Point = struct {
    x: i32,
    y: i32,
};

test "aoeu" {
    const p = bar();
    resume p;
}

fn bar() promise {
    var pt = Point { .x = 1, .y = 2 };
    return (async<std.debug.global_allocator> foo(pt)) catch unreachable;
}

async fn foo(point: Point) i32 {
    suspend;
    return point.x; // dereference of invalid memory
}
```

Async functions should do a memcpy for their args when passed this way. Users can use explicit pointers when copying is not necessary.

An advanced optimization: zig can notice if the parameter is accessed after a suspend point; only then does it need to be copied.

**Comment by emekoi** [comment]
will this still apply after the coroutine rewrite?
