### ISSUE TITLE
unable to @bitCast from type 'comptime_int'

### ISSUE THREAD

**Issue by bnoordhuis** [ziglang/zig#1156]
```zig
test "comptime float @bitCast" {
    _ = @bitCast(f32, 0);
}

test "comptime int @bitCast" {
    _ = @bitCast(u32, 0.0);
}
```
Prints:
```
$ build/zig test t.zig 
/home/bnoordhuis/src/zig/t.zig:2:18: error: unable to @bitCast from type 'comptime_int'
    _ = @bitCast(f32, 0);
                 ^
/home/bnoordhuis/src/zig/t.zig:6:18: error: unable to @bitCast from type 'comptime_float'
    _ = @bitCast(u32, 0.0);
```
Has this not been implemented yet or is it unsupported?  I imagine complexities arise when cross-compiling?

**Comment by andrewrk** [comment]
`@bitCast` converts between two things which have the same number of bits. comptime ints and floats have an undefined number of bits. It's illegal to use `@sizeOf` on comptime_int and comptime_float.

For `@bitCast` to work you need the target value to have a type with a well-defined size:

```
test "float @bitCast" {
    _ = @bitCast(f32, u32(0));
}

test "int @bitCast" {
    _ = @bitCast(u32, f32(0.0));
}
```

**Comment by bnoordhuis** [comment]
> comptime ints and floats have an undefined number of bits

I see your point but, as lossless conversion is possible, I expected it to DWIM.

> It's illegal to use @sizeOf on comptime_int and comptime_float.

Yes, that makes perfect sense.

**Comment by andrewrk** [comment]
> I see your point but, as lossless conversion is possible, I expected it to DWIM.

I think that it's not 100% clear what the intent is, so that's why zig requires the bit counts to equal each other as a sanity check. I feel pretty confident about status quo being correct here, but feel free to make a case for changing the behavior and  I'll re-open.
