### ISSUE TITLE
Structs with anytype fields do not initialize correctly

### ISSUE THREAD

**Issue by bpeake13** [ziglang/zig#11576]
### Zig Version

0.9.1

### Steps to Reproduce

Example program can be found here: https://godbolt.org/z/fbvqE66vq

### Expected Behavior

Tuples that contain type fields should compile into fields that are marked as anytype

### Actual Behavior

If a struct is provided that has anytype fields, then providing a tuple that has a type to those fields will result in an invalid array access error.

**Comment by luehmann** [comment]
`anytype` fields got removed anyway. see #10705

**Comment by bpeake13** [comment]
@luehmann good to know, thanks!
