### ISSUE TITLE
Unreachable at stage1/analyze.cpp:5456 in handle_is_ptr

### ISSUE THREAD

**Issue by bibo38** [ziglang/zig#11588]
### Zig Version

0.10.0-dev.2061+080e870a7

### Steps to Reproduce

- Create a new project using `zig init-exe`
- Copy the json.zig from the Stdlib and apply the following patch (`patch json.zig < json.patch`, [already patched file I've used](https://gist.githubusercontent.com/bibo38/5d0482439d2f9314b6b0718514f9e4a5/raw/0edc1373fe8f11880ef2e10c4034d23d1b1117d8/json.zig)):
```patch
5c5
< const std = @import("std.zig");
---
> const std = @import("std");
12,13c12,13
< pub const WriteStream = @import("json/write_stream.zig").WriteStream;
< pub const writeStream = @import("json/write_stream.zig").writeStream;
---
> pub const WriteStream = @import("std/json/write_stream").WriteStream;
> pub const writeStream = @import("std/json/write_stream").writeStream;
1600,1601c1600,1605
<             for (structInfo.fields) |field| {
<                 errors = errors || ParseInternalErrorImpl(field.field_type, inferred_types ++ [_]type{T});
---
>             if (comptime isArrayHashMap(T)) {
>                 errors = errors || error{AllocatorRequired};
>             } else {
>                 for (structInfo.fields) |field| {
>                     errors = errors || ParseInternalErrorImpl(field.field_type, inferred_types ++ [_]type{T});
>                 }
1628a1633,1636
> const isArrayHashMap = std.meta.trait.multiTrait(.{
>     std.meta.trait.hasFn("init"),
>     std.meta.trait.hasFn("put"),
> });
1721a1730,1737
> 
>             if (comptime isArrayHashMap(T)) {
>                 // aquire value type
>                 const valTyp = comptime std.meta.fieldInfo(T.Unmanaged.KV, .value).field_type;
>                 var ret = std.StringArrayHashMap(valTyp).init(options.allocator orelse return error.AllocatorRequired);
>                 return ret;
>             }
> 
2733,2734c2749,2750
<     _ = @import("json/test.zig");
<     _ = @import("json/write_stream.zig");
---
>     _ = @import("std/json/test");
>     _ = @import("std/json/write_stream");
```
- Put the following code to access the JSON functionality into the `main.zig`:
```zig
const std = @import("std");
const json = @import("./json.zig");

pub fn main() anyerror!void {
    var ts = json.TokenStream.init("{\"foo\": \"bar\"}");
    _ = try json.parse(std.StringArrayHashMap([]u8), &ts, json.ParseOptions{
        .allocator = std.testing.allocator,
    });
}
```

### Expected Behavior

`zig build run` compiles (and runs) the code or produces a compilation error.

### Actual Behavior

The compiler crashed when trying to compile the code with the following output of `zig build run`:
```
Unreachable at /workspace/src/stage1/analyze.cpp:5456 in handle_is_ptr. This is a bug in the Zig compiler.thread 35304 panic: 
Unable to dump stack trace: debug info stripped
```

**Comment by zenspider** [comment]
I'm getting this in code that (I think) is reaching it via fairly different means.

Code: https://gist.github.com/zenspider/c9dd6c1690b250ac7385af1f619c5ec6/c657ac23d6d320367391fcf48abff29735c6c6ef

repro: `zig test zlox.zig`

Back up a revision to see it working or look at the diff here https://gist.github.com/zenspider/c9dd6c1690b250ac7385af1f619c5ec6/revisions that makes it hit this bug.

**Comment by zenspider** [comment]
The code in #12782 is standalone and only ~45 loc

**Comment by zenspider** [comment]
Unfortunately, I can't reasonably back up to 080e870a7 and bisect because this spans an llvm 14 vs 13 switch and for some reason the old cmake code can't find/verify that I've installed llvm@13 ...

**Comment by zenspider** [comment]
Here's what I was using to bisect:

```bash
#!/bin/bash
set -e
cd ~/Work/git/ziglang/zig/
mkdir -p build
cd build
cmake .. \
      -DCMAKE_PREFIX_PATH=$(brew --prefix llvm) \
      -DZIG_STATIC_LLVM=on
make install -j 12
zig version
zig test buggy2.zig 2>&1 | grep "Unreachable at" && exit 1 # FFS
```

**Comment by Vexu** [comment]
Closing as fixed in master since the repro in the duplicate issue doesn't crash.
