### ISSUE TITLE
Macro defines lose double-quotes if sum of all source filenames + macros exceed certain length

### ISSUE THREAD

**Issue by Ristovski** [ziglang/zig#11595]
Adding a `exe.defineCMacro("FOO", "\"BAR\"");` into a `build.zig` and compiling with `--verbose-cc` shows the expected definition as `-D FOO="BAR"`.

However, if the sum of C sources (filename strings) or macro definitions inside `build.zig` exceeds a certain amount, the definition loses the quotes and becomes `-D FOO=BAR`

I have created a simple repro repository for convenience at https://github.com/Ristovski/zig-macro-bug-repro, it contains the default `zig init-exe` code along with a single C file, in order to cause `error: use of undeclared identifier 'BAR'` when the bug gets hit.

The provided `build.zig` exposes a `trigger` option:
```Zig
const trigger = b.option(i32, "trigger", "Set number of loops to trigger mega cursed bug") orelse 100;

var i: i32 = 0;
while (i < trigger) {
    exe.defineCMacro("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    i = i+1;
}
```

The default value is not enough, but **running `zig build -Dtrigger=1000` triggers the bug**.

- - -

The specific value to cause the bug seems to differ across `0.10.0-dev` builds as well.

For `0.10.0-dev.2073+59905a62f` passing `-Dtrigger=442` triggers the bug, but `-Dtrigger=441` does not. The specific amount differs across versions _and_ architectures, I am sure someone with more time can figure out the exact amount with a more granular testing setup.

Zig version `0.9.1` does not seem to have this bug, as you can crank the value all the way up to `20000` and everything still works, meaning this is a **regression**.

Recreating the same bug, but this time by only surpassing the C source filename amount required to trigger it is harder but should be possible. I have only confirmed that increasing/decreasing either does it, as that's how I first encountered the bug anyway.

_Cue `Cursed` issue label :^)_

**Comment by LemonBoy** [comment]
Looks similar to #10881, what's the underlying OS? And in case it's not Windows, what's the output of `getconf ARG_MAX`?

**Comment by Ristovski** [comment]
@LemonBoy This is on Linux x86_64. `getconf ARG_MAX` returns `2097152`, however I don't think that issue is related, quoting author:
> Remarks: This happens because such an argument lists triggers a behavior in Clang to invoke subprograms with clang @/tmp/response-foobar.txt (Clang will actually read the argument list if a file is passed like this).

In my case, the argument list passed is normal and well within the limits of `ARG_MAX` (36054 characters in total). Also note that it does not happen on `0.9.1`.

Output of `zig build -Dtrigger=422 --verbose-cc`: https://bpa.st/raw/HCOGAF3AHORTZ6HFJQVO3WVVCE

**Comment by ehaas** [comment]
`build.zig` uses a clang response file regardless of platform if the sum of the lengths of the arguments exceeds 30,719 characters. So I suspect that the response file is being constructed incorrectly. It probably worked in `0.9.1` because that was released on February 15 and did not use response files; and the response file update was added on February 20 in 2bd10f4db98fd313c6743477ad36b139652a8dd5 - so perhaps it is being constructed incorrectly.
