### ISSUE TITLE
D-style (higher-order) (lazy) ranges

### ISSUE THREAD

**Issue by nordlow** [ziglang/zig#1160]
Are there any plans on adding [D-style](https://dlang.org/phobos/std_range.html) (higher-order) (lazy) ranges to Zig?

Preferrably with compile-time inference of capabilities such as:

- in-place sort algorithms (such as D's [sort](https://dlang.org/phobos/std_algorithm_sorting.html#sort)) require random access ranges via template restrictions (in this case `isRandomAccessRange`) returning a wrapper range exposing a sortedness property att compile-time.
- range property inference: multi-array in-place sort using: `sort(chain(a,b,c, ...))` works because `chain(a, b, c)` is random access iff `a`, `b` and `c` are all random access.
- and more

**Comment by BraedonWooding** [comment]
My lazy zig [library](https://github.com/BraedonWooding/Lazy-Zig) may be a good starting point :).

**Comment by nordlow** [comment]
If and when Zig decides to add ranges I suggest digging to both D's std.range and std.algorithm and C++'s [range-v3](https://github.com/ericniebler/range-v3) for inspirations. There are lots of details that have work in symphony to make higher-order lazy  ranges/iterators.

**Comment by andrewrk** [comment]
There is no plan for this feature.

However pay attention to the coroutine rewrite (#2377) because it's possible Zig may gain generators out of it.
