### ISSUE TITLE
Labeled break in while loop doesn't work

### ISSUE THREAD

**Issue by danielchasehooper** [ziglang/zig#11617]
### Zig Version

0.10.0-dev.2083+13d1798ea

### Steps to Reproduce

`infinite_loop.zig`:
```
test {
    while (true) blk: {
           break :blk;
    }
}
```

zig test infinite_loop.zig

### Expected Behavior

it should not be an infinite loop.

### Actual Behavior

it's an infinite loop.

I'm not sure if this is a bug, or a natural behavior resulting from the compiler rules, but either way, it is surprising and caused a bug in a zig project I'm working on. 

You can fix it by putting the label before the while, but it's annoying that there's a behavioral difference between before the block and before the while.

I think the compiler should either disallow labeling a while's block, or behave as it a block's label were written before the while.

**Comment by nektro** [comment]
not a bug

if you want the loop to exit write it as `blk: while (true)`

doing a labelled break with `while (true) blk:` is equivalent to `continue;`

**Comment by danielchasehooper** [comment]
I’m aware, I mentioned both of those. I think it *should* be a bug. Per @andrewrk’s preference,  it’s not good to be able write something two different ways (I.e. continue vs break :afterWhileLabel)
