### ISSUE TITLE
Wrong order of exe.strip = true and exe.install() causes weird errors.

### ISSUE THREAD

**Issue by eLeCtrOssSnake** [ziglang/zig#11625]
### Zig Version

0.10.0-dev.798+56e9575e8

### Steps to Reproduce

There's an issue I've found with build.zig build system. If you want to strip your exe at build time and you write:
```
    // ... ommited target and mode not related
    const exe = b.addExecutable("my_app", "src/main.zig");
    exe.setTarget(target);
    exe.setBuildMode(mode);
    // notice order of strip and install
    exe.install();
    exe.strip = true;
    // ... blah blah
```
The build system will go nuts and spew random-looking errors inside zig's code.

[zig build error log](https://paste.sr.ht/~electrosssnake/5d6d861212c642fe161a3ad291bff92c1a8285ba)
note: my zig is installed in a folder called mingw, it doesn't actually mean anything. This is place where I keep all compilers lol.

### Expected Behavior

Obviously setting exe.strip = true; before exe.install() intuitively seems more correct, but it is pretty hard to trace that issue if you've done it by mistake. So I would expect it to either work both ways or print an error that can be understood.

### Actual Behavior

You get gigantic error trace

However if you write:
```
    // ... ommited target and mode not related
    const exe = b.addExecutable("my_app", "src/main.zig");
    exe.setTarget(target);
    exe.setBuildMode(mode);
    exe.addPackagePath("win32", "deps/zigwin32/win32.zig");
    // notice order of strip and install
    exe.strip = true;
    exe.install();
    // ... blah blah
```
It will work perfectly.

**Comment by Vexu** [comment]
`exe.install()` no longer exists.
