### ISSUE TITLE
zig wasm passes function pointers a different way than clang wasm does. 

### ISSUE THREAD

**Issue by dominictarr** [ziglang/zig#11624]
### Zig Version

0.9.1

### Steps to Reproduce

I want to make a web assembly that registers a callback, and may then be called from javascript.
```
pub extern fn onReady(cb: *const fn () void) void;

fn cb () void { 
  onReady(&cb2);
}
fn cb2 () void { }

pub export fn init () void {
  onReady(&cb);
}
```
compile, building an object and then linking because zig doesn't support --export-table option yet
```
zig build-obj -target wasm32-freestanding -dynamic cb.zig -O ReleaseSmall
wasm-ld --allow-undefined --export-all --export-table --no-entry cb.o -o cb.wasm
```
(using the -O ReleaseSmall option makes the wasm2wat output much more readable)
javascript to call it:

```
const fs = require('fs');
const source = fs.readFileSync("./cb_c.wasm");
const typedArray = new Uint8Array(source);
var memory
var crypto = require('crypto')

;(async function () {
  var callback
  var buffer = Buffer.alloc(0)
  var result = await WebAssembly.instantiate(typedArray, {
    env: {
    onReady: function (fn_ptr) {
      var table = result.instance.exports.__indirect_function_table
      var memory = Buffer.from(result.instance.exports.memory.buffer)
      console.log('fn_ptr', fn_ptr)
      //in zig => fn_ptr 1024 (!!!) in c => 2
      //with wasm created from zig, the value passed to onReady is a pointer to the function table index
      callback = result.instance.exports.__indirect_function_table.get(memory.readUInt32LE(fn_ptr))
      //but with wasm created from C, the value passed to onReady is is the function table index directly!
      callback = result.instance.exports.__indirect_function_table.get(fn_ptr)
    },
  }})
  result.instance.exports.init(r)
  callback()
}())
```

looking at the output wasm:
`> wasm2wat cb.wasm --fold`
(I've added some comments `;;`)
```
(module
  (type (;0;) (func (param i32)))
  (type (;1;) (func))
  (import "env" "onReady" (func $onReady (type 0)))
  (func $__wasm_call_ctors (type 1))
  (func $init (type 1)
    (call $onReady
      (i32.const 1024))) ;;passes pointer into data section???
  (func $cb (type 1)
    (call $onReady
      (i32.const 1028)))
  (func $cb2 (type 1))
  (table (;0;) 3 3 funcref)
  (memory (;0;) 2)
  (global (;0;) (mut i32) (i32.const 66576))
  (global (;1;) i32 (i32.const 1024))
  (global (;2;) i32 (i32.const 1032))
  (global (;3;) i32 (i32.const 1024))
  (global (;4;) i32 (i32.const 66576))
  (global (;5;) i32 (i32.const 0))
  (global (;6;) i32 (i32.const 1))
  (export "memory" (memory 0))
  (export "__wasm_call_ctors" (func $__wasm_call_ctors))
  (export "init" (func $init))
  (export "__indirect_function_table" (table 0))
  (export "__dso_handle" (global 1))
  (export "__data_end" (global 2))
  (export "__global_base" (global 3))
  (export "__heap_base" (global 4))
  (export "__memory_base" (global 5))
  (export "__table_base" (global 6))
  (elem (;0;) (i32.const 1) func $cb $cb2)
  (data (;0;) (i32.const 1024) "\01\00\00\00\02\00\00\00")) ;;seems there is a function table in the data section
```
btw, here is the c code that I consider to be equivalent that zig
```
typedef void (*callback)();
void onReady (callback* cb);

void cb2 () { }
void cb () { 
  onReady(&cb2);
}

void init () {
  onReady(&cb);
}
```
and this is the code I'm using to build it: `clang --compile -w --target=wasm32 cb.c -Os
wasm-ld cb.o -o cb_c.wasm --no-entry --export-all --allow-undefined`

### Expected Behavior

when wasm passes a function pointer it should match the behavior of C. instead of passing a pointer to the function index number it should just pass the function index number. This also means that replicating the function table indexes in the data section will not be necessary.

### Actual Behavior

zig outputs wasm with that passes a pointer to the function table index, instead of just the function table index.

**Comment by Luukdegram** [comment]
The behavior here is different than clang because you're not passing a function pointer, but rather a pointer to a function pointer. That's also why the Wasm code represents the address of the function index, rather than the function index itself. The behavior you're seeing is correct, but the implementation of your Zig code is incorrect.

The correct Zig representation of your C code is:
```zig
extern fn onReady(cb: fn () void) void;

fn cb () void { 
  onReady(cb2);
}
fn cb2 () void { }

export fn init () void {
  onReady(cb);
}
```
Note how `fn() void` already represents the function pointer.
This syntax is only for the current compiler. In the self-hosted compiler the syntax will indeed be `*const fn() void` and act as a function pointer as you'd expect it.

**Comment by dominictarr** [comment]
thanks, I tried that, but I got an error (in both 0.9.1 and `zig-linux-x86_64-0.10.0-dev.2137+94b9bcd03`)

```
./cb.zig:1:23: error: parameter of type 'fn() void' not allowed in function with calling convention 'C'
extern fn onReady(cb: fn () void) void;
```
since I couldn't find an example in learnzig.org about specifically how to pass a function pointer I ended up trying the other way. which did actually compile

**Comment by Luukdegram** [comment]
Sorry, that's my bad. Since we're exporting and importing over the C-ABI here, we need to specify the calling convention.
This should work:
```zig
extern fn onReady(cb: fn () callconv(.C) void) void;

fn cb () callconv(.C) void { 
  onReady(cb2);
}
fn cb2 () callconv(.C) void { }

export fn init () void {
  onReady(cb);
}
```

**Comment by dominictarr** [comment]
yes that works! I had seen `callconv(.C)` in this issue: https://github.com/ziglang/zig/issues/10817 (which also confused me because it used function pointers as I was trying to). I tried that and with `*fn()` it worked both with and without `callconv(.C)` but it's necessary when just using `fn()...`
