### ISSUE TITLE
[*c] anyopaque is not compileable, needed for C interop

### ISSUE THREAD

**Issue by Trainraider** [ziglang/zig#11630]
Zig Version:
```
0.10.0-dev.1537+a9a91a5d4
```

Write out a function prototype for a c library function that is generically written to use void pointers, e.g. [timsort](https://github.com/patperry/timsort)

```zig
pub extern fn timsort(
    base: ?*anyopaque,
    nel: usize, 
    width: usize, 
    compar: ?fn ([*c] const anyopaque, [*c] const anyopaque) callconv(.C) c_int
) c_int;
```

Compiler output:
`error: C pointers cannot point to opaque types`

A c pointer to void (anyopaque) is so obviously needed. This type is used all over in C. Zig's pointer types are not sufficient because of strict alignment checking. `*anyopaque` is presumed to have an alignment of 1, and e.g. `*u64` with alignment 8 is not castable to it.  I could compile by using `*u64` or `*align(@alignOf(u64)) anyopaque` in the function declaration, but this ruins the genericness of the function.

A `[c*] anyopaque` type not being legal in Zig means proper interop with generic C functions is not possible. This type is so common in C, this type is needed in Zig.

Other ideas:
* A `@ptrCastForce` or something like that, that can cast in spite of alignment checks.
* A `noalign` type qualifier for pointers only to disable pointer alignment checks.
* `*align(0)` to disable pointer alignment checks.

The compiler really doesn't know anything about an anyopaque pointer in the first place, so maybe alignment checks aren't appropriate when really, alignment is unknown, not 1.

Thank you for your time and consideration. Let me know if I'm missing something obvious here.

**Comment by nektro** [comment]
would `[*c]u8` not be the proper type? if im reading correctly you want something that lets you write into arbitrary memory addresses based on some offset

**Comment by Vexu** [comment]
Writing `[*c]` by yourself is always incorrect see #2984, in this case it looks like the correct type would be `[*]const anyopaque`.

**Comment by ifreund** [comment]
looking at the timsort implementation, `*const anyopaque` is correct here. This is also exactly what `zig translate-c` spits out: 
```zig
pub extern fn timsort(base: ?*anyopaque, nel: usize, width: usize, compar: ?fn (?*const anyopaque, ?*const anyopaque) callconv(.C) c_int) c_int;
pub extern fn timsort_r(base: ?*anyopaque, nel: usize, width: usize, compar: ?fn (?*const anyopaque, ?*const anyopaque, ?*anyopaque) callconv(.C) c_int, context: ?*anyopaque) c_int;
```

**Comment by ifreund** [comment]
And to demonstrate how a compare function might be written:
```zig
fn compar(a: *const anyopaque, b: *const anyopaque) callconv(.C) c_int {
    const x = @ptrCast(*u64, @alignCast(@alignOf(u64), a));
    const y = @ptrCast(*u64, @alignCast(@alignOf(u64), b));
    
    if (x.* < y.*) return -1;
    if (x.* > y.*) return 1;
    return 0;
}
