### ISSUE TITLE
move zig.h to become an installation file that can be changed at runtime

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#11643]
Currently zig.h is embedded into the zig binary like this:

https://github.com/ziglang/zig/blob/974af5f29101ce8d000359b749f35a2b07c90a32/src/link/C.zig#L18

However, I think it would be more flexible and useful to be able to edit this file without needing to rebuild the compiler.

 * figure out a place to put it within lib/
 * integrate with the caching system
 * load at runtime instead of `@embedFile`

**Comment by matu3ba** [comment]
I am looking into this out of personal curiosity how the caching system works.

**Comment by matu3ba** [comment]
So far only the Zir of the Zig source file and builtin.zig of a file with c backend (`-ofmt=c`) are cached into the local cache.
Besides that, 447 files are added to the global cache into `z/` (Zir files).

Can you be more specific how you expect things to be cached?

**Comment by nektro** [comment]
it would be part of the global cache, he said he wanted it put inside `lib/`
