### ISSUE TITLE
when choosing a default local zig-cache directory, try to place it next to build.zig, falling back to global zig-cache

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#11672]
Currently, Zig will choose a default local zig-cache directory relative to the current working directory. This is not always desirable, and can lead to multiple unwanted zig-cache directories, and even drives some users to unconditionally override the local zig-cache directory.

Instead, the logic for choosing a default local zig-cache directory should be as follows:

 * Search upwards in parent directories from the cwd, looking for a `build.zig` file. If this is found, then choose that same directory containing that file with `zig-cache` as a sub-directory.
 * If no build.zig file is found, or other file system errors occur such as "access denied", then use the same path as the global zig-cache.

**Comment by matu3ba** [comment]
1. Does this also mean that `tmpDir(opts: std.fs.Dir.OpenDirOptions)`should use that path? As of now, `tmpDir` uses `cwd`, which feels odd.
2. Related: Should this go into `build.zig` or `testing.zig`?

related https://github.com/ziglang/zig/pull/11633/files
