### ISSUE TITLE
Grammatical error in Introduction Page

### ISSUE THREAD

**Issue by bsljth** [ziglang/zig#11675]
"The code then [declares](https://ziglang.org/documentation/master/#Container-Level-Variables) a [constant identifier](https://ziglang.org/documentation/master/#Assignment), named std, that gives access the features of the Zig Standard Library."

It should be "...access _to_ the features..."

**Comment by leecannon** [comment]
@bsljth https://github.com/ziglang/zig/blob/50a5ddecc54b88cf295fb97b47fecd2a29a1bf8e/doc/langref.html.in#L394-L395

**Comment by bsljth** [comment]
Thank you Lee!
