### ISSUE TITLE
`pub fn main() void { { return; } return; }` evades unreachable code error

### ISSUE THREAD

**Issue by r00ster91** [ziglang/zig#11686]
### Zig Version

0.10.0-dev.2315+dd6ac9a22

### Steps to Reproduce

```zig
pub fn main() void {
    {
        return;
    }
    return;
}
```

### Expected Behavior

```
main.zig:5:5: error: unreachable code
    return;
    ^
main.zig:3:5: note: control flow is diverted here
    return;
    ^
```

### Actual Behavior

A successful compilation.

**Comment by r00ster91** [comment]
The fix should probably go somewhere here:
* https://github.com/ziglang/zig/blob/master/src/AstGen.zig#L345
* https://github.com/ziglang/zig/blob/master/src/AstGen.zig#L2128

**Comment by nektro** [comment]
that's the bug
