### ISSUE TITLE
confusing error message on function prototype with inferred error set

### ISSUE THREAD

**Issue by matu3ba** [ziglang/zig#11700]
### Zig Version

0.10.0-dev.2353+8171972cb

### Steps to Reproduce

```zig
const builtin  = @import("builtin");
test "fnproto" {
        const FnProto = switch (builtin.zig_backend) {
        // workaround until we replace stage1 with stage2
        .stage1 => fn() !void,
        else => *fn() !void,
    };
}
```

### Expected Behavior

Error message "function prototype with inferred error set must be explicit".
Prefixing `!void` with `anyerror` works as intended:
```zig
const builtin = @import("builtin");
test "fnproto" {
    const FnProto = switch (builtin.zig_backend) {
        // workaround until we replace stage1 with stage2
        .stage1 => fn () anyerror!void,
        else => *fn () anyerror!void,
    };
    _ = FnProto;
}
```
with either `zig test fnproto.zig` or `./stage2/bin/zig test fnproto.zig`.

### Actual Behavior

```txt
fnproto.zig:6:23: error: function prototype may not have inferred error set
        else => *fn() !void,
                      ^
```

**Comment by nektro** [comment]
this is a nit and almost exactly what the error message already says. status quo is more clear

**Comment by Vexu** [comment]
I mistook the actual behavior for the expected behavior, the current message is indeed better.
