### ISSUE TITLE
arm-linux-musleabi mpcorenovfp target won't compile/bootstrap with zig 0.9.0

### ISSUE THREAD

**Issue by lancethepants** [ziglang/zig#11717]
Since zig 0.7.x I've been able to compile/bootstrap for `"-target arm-linux-musleabi -mcpu=mpcorenovfp"` (armv7 Cortex-A9 no fpu).
I seem to be getting an error while compilling musl.  I've attached the files from the zig diagnostic message.

[sqrtf-6046a3.zip](https://github.com/ziglang/zig-bootstrap/files/7790049/sqrtf-6046a3.zip)

**Comment by andrewrk** [comment]
This is a crash in clang 13. Next step to solving this issue is to repro the issue with clang master branch, then file an upstream LLVM bug.

**Comment by vesim987** [comment]
I think this issue is related to: https://github.com/ziglang/zig/issues/10961

**Comment by lancethepants** [comment]
Yes, I believe it is the same problem.  Pulling from that issue, if I compile with 
`"-target arm-linux-musleabi -mcpu=mpcorenovfp+soft_float"`
then I get a working  binary under zig 0.9.1.

I can also bootstrap 0.9.1 using `"./build -j4 arm-linux-musleabi mpcorenovfp+soft_float"`

When I try to bootstrap HEAD from https://github.com/ziglang/zig-bootstrap I get the following which mentions says `libc++ does not work on multi-threaded ARM yet.` and mentions https://github.com/ziglang/zig/issues/6573 .  HEAD seems to carry a patch mentions in that issue, so not sure why I'm seeing this error

```
-- Check for working CXX compiler: /home/lance/zig-bootstrap/out/host/bin/zig
-- Check for working CXX compiler: /home/lance/zig-bootstrap/out/host/bin/zig -- broken
CMake Error at /usr/share/cmake-3.13/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "/home/lance/zig-bootstrap/out/host/bin/zig"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/lance/zig-bootstrap/out/build-llvm-arm-linux-musleabi-mpcorenovfp+soft_float/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_ceb97/fast"
    /usr/bin/make -f CMakeFiles/cmTC_ceb97.dir/build.make CMakeFiles/cmTC_ceb97.dir/build
    make[1]: Entering directory '/home/lance/zig-bootstrap/out/build-llvm-arm-linux-musleabi-mpcorenovfp+soft_float/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_ceb97.dir/testCXXCompiler.cxx.o
    /home/lance/zig-bootstrap/out/host/bin/zig  c++ -fno-sanitize=all -s -target arm-linux-musleabi -mcpu=mpcorenovfp+soft_float     -o CMakeFiles/cmTC_ceb97.dir/testCXXCompiler.cxx.o -c /home/lance/zig-bootstrap/out/build-llvm-arm-linux-musleabi-mpcorenovfp+soft_float/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    warning(compilation): libc++ does not work on multi-threaded ARM yet.
    For more details: https://github.com/ziglang/zig/issues/6573
    error: unable to create compilation: TargetRequiresSingleThreaded
    make[1]: *** [CMakeFiles/cmTC_ceb97.dir/build.make:66: CMakeFiles/cmTC_ceb97.dir/testCXXCompiler.cxx.o] Error 1
    make[1]: Leaving directory '/home/lance/zig-bootstrap/out/build-llvm-arm-linux-musleabi-mpcorenovfp+soft_float/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_ceb97/fast] Error 2




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:49 (project)


-- Configuring incomplete, errors occurred!
See also "/home/lance/zig-bootstrap/out/build-llvm-arm-linux-musleabi-mpcorenovfp+soft_float/CMakeFiles/CMakeOutput.log".
See also "/home/lance/zig-bootstrap/out/build-llvm-arm-linux-musleabi-mpcorenovfp+soft_float/CMakeFiles/CMakeError.log".
```

**Comment by janko-js** [comment]
zig.exe c++ -target arm-linux-gnueabi -O1 hello.cpp

crashes during the build of the needed libraries (running on Windows)

I.e. last output on the console is e.g.:
Compile C Objects [12/19]   (the first number varies) 
and the crash is observed.

Tried with 
0.12.0-dev.817+54e7f58fc and 
0.11.0  

(Note: Without -O option there's no crash, i.e.:
zig c++ -target arm-linux-gnueabi  hello.cpp
compiles.
There's also no crash when C and not C++, i.e:
zig cc -target arm-linux-gnueabi -O1 hello.c 
compiles.)

(I don't know if this observation belongs here, I hope it does)

**Comment by alexrp** [comment]
This no longer reproduces for me.

**Comment by alexrp** [comment]
```
❯ ./build arm-linux-musleabi mpcorenovfp
❯ qemu-arm -cpu arm11mpcore,vfp=off ./out/zig-arm-linux-musleabi-mpcorenovfp/zig version
0.14.0-dev.1622+2ac543388
```
