### ISSUE TITLE
expected return type error is misleading

### ISSUE THREAD

**Issue by dominictarr** [ziglang/zig#11714]
### Zig Version

0.10.0-dev.2137+94b9bcd03

### Steps to Reproduce

some code that uses a `try` from a function defined as `void`

### Expected Behavior

an error message that clearly says that problem is the expression returns an error union from a function declared as void (or something else)

### Actual Behavior

```
./fs-dir.zig:129:21: error: expected type 'void', found 'std.mem.Allocator.Error'
    var buf: []u8 = try self.alloc.alloc(u8, aos.FsDir__encoding_length__openDir(file.len));
                    ^
 ``
it's not very clear that this is about the functions return type

**Comment by Vexu** [comment]
There should be a note saying that the function cannot return an error, are you not getting that?
```
./a.zig:15:9: error: expected type 'void', found 'anyerror'
    _ = try a;
        ^
./a.zig:13:10: note: function cannot return an error
fn foo() void {
         ^
```
