### ISSUE TITLE
Value numbering optimization missing

### ISSUE THREAD

**Issue by Avokadoen** [ziglang/zig#11748]
### Zig Version

0.10.0-dev.2024+d127c1d59

### Steps to Reproduce

Godbolt code:
https://godbolt.org/z/zc5bMzG99?fbclid=IwAR30q6wlHWdYjYR75vKHjvoel_dmUqrep8iy23hEXvGfYGHpRIAE5-mAlpc

### Expected Behavior

Compiler should use [value numbering](https://en.wikipedia.org/wiki/Value_numbering) to optimize instructions

Rust example:
https://godbolt.org/z/cGfc3dn7P?fbclid=IwAR3e-FGjMF5hs7_Xj563BjqittFQcwxUcvDMltjNww6roFIYLb0cEmzNq8g

C++ example:
https://godbolt.org/z/c9G3r8z9T?fbclid=IwAR2fbq_oRvll8EkFWMHjB1IGZ9SZuexen8xbO9yDpz5XVnKXgTyNcLZNBL4

### Actual Behavior

Compiler does not optimize using value numbering

Issue found by @chunnoo and @thaugdahl

**Comment by joachimschmidt557** [comment]
When adding the `-OReleaseFast` flag, the generated code seems to generate code of similar efficiency: https://godbolt.org/z/xdsW9zvbh

`-Drelease-fast=true` is mostly used in `zig build`, i.e. when using a `build.zig`. Godbolt just uses `zig build-exe` without a build file IIRC.
