### ISSUE TITLE
math.nan() compares equal to itself

### ISSUE THREAD

**Issue by bnoordhuis** [ziglang/zig#1174]
```zig
const assert = @import("std").debug.assert;
const math = @import("std").math;

test "nan != nan" {
    assert(math.nan(f32) != math.nan(f32)); // fails because LHS and RHS compare equal
}
```
This is unlike other languages where NaNs are unequal to everything, including themselves.

Setting `FloatMode.Strict` or `FloatMode.Optimized` with `@setFloatMode()` makes no difference.

**Comment by bnoordhuis** [comment]
I think this is an optimization gone wrong.  With `--release-small --emit llvm-ir`, it reduces to this:
```llvm
; Function Attrs: nobuiltin nounwind
define internal fastcc i16 @"nan != nan"() unnamed_addr #0 !dbg !620 {
Entry:
  call void @llvm.dbg.value(metadata i1 false, metadata !611, metadata !DIExpression()) #9, !dbg !623
  tail call fastcc void @panic() #9, !dbg !627
  unreachable, !dbg !627
}
```

**Comment by andrewrk** [comment]
Very interesting. It's definitely supposed to evaluate to false when float mode is strict. When float mode is optimized the user gives up ability to use NaNs. So in optimized mode, this operation produces an undefined value. I think we should add a runtime safety check (similar to how we handle integer overflow) for float operations to make sure undefined values don't creep up in code.

**Comment by numsim1415** [comment]
I just want to point out that this bug (dis-)appears depending on whether the comparison happens during `comptime` or not.
I tried a few different cases [here](https://godbolt.org/z/Srnyy-).

**Comment by andrewrk** [comment]
it was just the wrong predicate given to LLVM:

```diff
--- a/src/codegen.cpp
+++ b/src/codegen.cpp
@@ -1852,7 +1852,7 @@ static LLVMRealPredicate cmp_op_to_real_predicate(IrBinOp cmp_op) {
         case IrBinOpCmpEq:
             return LLVMRealOEQ;
         case IrBinOpCmpNotEq:
-            return LLVMRealONE;
+            return LLVMRealUNE;
         case IrBinOpCmpLessThan:
             return LLVMRealOLT;
         case IrBinOpCmpGreaterThan:
```

The comptime stuff is now fixed too.
