### ISSUE TITLE
Support `avr` target for `zig cc`

### ISSUE THREAD

**Issue by septatrix** [ziglang/zig#11758]
### Zig Version

0.9.1

### Steps to Reproduce

```c
// main.c
int main(void) { return 0; }
```

Compile the above using `zig cc -target avr-freestanding-none main.c`.

### Expected Behavior

The command should compile as AVR is a supported target and it does not even need OS functionality of libc files. Extra points however if avr-libc could be made to work.

### Actual Behavior

zig crashes with the following output

```
LLVM ERROR: Not supported instr: <MCInst 312 <MCOperand Reg:1> <MCOperand Imm:15> <MCOperand Reg:53>>
```

**Comment by kassane** [comment]
- https://github.com/ziglang/zig/issues/11758

**Comment by daurnimator** [comment]
Closing as duplicate

**Comment by septatrix** [comment]
The underlying issue does seem to be the same though merging this into the other sadly keeps open the issue with fever reactions/subscribers

**Comment by kassane** [comment]
> The underlying issue does seem to be the same though merging this into the other sadly keeps open the issue with fever reactions/subscribers

@septatrix 
Please, try with zig latest version. So the error no longer occurs.

```bash
zig cc -target avr-freestanding main.c -mcpu=avr5
#or
zig cc build-exe -target avr-freestanding main.c -mcpu=5
```
