### ISSUE TITLE
`std.fmt`: disallow implicitly formatting optional and error values

### ISSUE THREAD

**Issue by r00ster91** [ziglang/zig#11753]
On Discord we've discussed and agreed to that it is currently too easy to accidentally pass an optional value (`?T`) to a format specifier like `{s}`. It is a real footgun and reminds me a lot to `undefined` that you can find on JavaScript websites in many places because the developer forgot to handle it. We don't want Zig to be like that. It shouldn't happily print `null` like that.

@InKryption had the idea of only allowing an optional type to be formatted if there is `?` before the specifier type, so for `{s}` it would be `{?s}`.

Then @MasterQ32 asked about error unions and I proposed for example `{!?s}` to format `anyerror!?[]const u8`. I think this syntax looks really neat and it's consistent with the way the types look.

Here's what **cipharius** had to say:
> That would be definitely more intuitive, as I previously also expected a type error, since in other contexts Zig is pretty strict about type inference.

So the proposal is to change `std.fmt` formatting such that in a format string

* `{t}` can only format `T`,
* `{?t}` can only format `?T` (and `T` as that coerces to it),
* `{!?t}` can only format `anyerror!?T`.

where `t` is the respective specifier type. This affects all specifier types except for `any` which will retain current behavior.

CC @InKryption @viriuwu @MasterQ32

**Comment by r00ster91** [comment]
@daurnimator Yeah, I think you're right. Amended.

**Comment by MasterQ32** [comment]
I don't think this will work out in the proposed way, as this part of the format strings are type specific.

`t` could mean something else for integers as for custom structs or enums. What i'd propose is that formatting an optional requires the `fmt` string to be prefixed with `?` and formatting an error union must be prefixed with `!`, where these type formatters remove that prefix and then pass the `fmt` string down to the original type. 

This way, formatting a `?E1!(??E2!?u32)` must be formatted as `{?!??!?d}` for decimal formatting of the `u32`.

If the prefix is not present, this should be a compile error like

- `Formatting optional type ?… must have a '?'-Prefix in the format string: {?…}` where the first … is the actual type passed and the second … is the `fmt` of the original format message

same  goes for error unions

**Comment by LemonBoy** [comment]
The resulting symbol soup is quite ugly to read and hard to decypher. If I correctly understand the problem you're lamenting that fmt prints either `null` or the unwrapped value, an alternative approach would be to make the output "noisier" (eg. rust prints `Some(<unwrapped value>)` or `None`) thus forcing the user to properly handle the optional/error case when and if that matters.

**Comment by jibal** [comment]
This is about type checking, not about what gets printed. There really isn't any "symbol soup" because you only need to use the prefixes on those rare occasions when you're explicitly allowing "null" to be printed. Usually, you should take explicit action to check for null rather than naively printing it and leaking the internal implementation to the user.

**Comment by andrewrk** [comment]
Fix reverted in 7cbd586ace46a8e8cebab660ebca3cfc049305d9.
