### ISSUE TITLE
std.io.CountingWriter writes to stdout when it should be writing to a file

### ISSUE THREAD

**Issue by mkfoo** [ziglang/zig#11799]
### Zig Version

0.10.0-dev.2489+33826a6a2

### Steps to Reproduce

```zig
// main.zig
const std = @import("std");

const S = struct {
    w: std.io.CountingWriter(std.fs.File.Writer).Writer,

    pub fn new() !S {
        var f = try std.fs.cwd().createFile("file", .{});

        return S{
            .w = std.io.countingWriter(f.writer()).writer(),
        };  
    }   
    
    pub fn write_file(self: *S) !void {
        try self.w.writeByteNTimes(0x58, 16);
    }   
};  

pub fn main() !void {
    var s = try S.new();
    try s.write_file();
}   
```

### Expected Behavior

16 bytes are written into a file:

```
mkfoo@debian11:~/Zig$ zig build-exe main.zig && ./main && xxd file
00000000: 5858 5858 5858 5858 5858 5858 5858 5858  XXXXXXXXXXXXXXXX
```

### Actual Behavior

The bytes are written to stdout and the file remains empty:

```
mkfoo@debian11:~/Zig$ zig build-exe main.zig && ./main && xxd file
XXXXXXXXXXXXXXXXmkfoo@debian11:~/Zig$ 
```
----------
The issue does not appear if std.io.CountingWriter is replaced with plain std.fs.File.Writer in the above code.

Same behavior on 0.9.1

Edit: ReleaseFast and ReleaseSafe work as expected, but ReleaseSmall outputs `error: NotOpenForWriting`

**Comment by Vexu** [comment]
`new` is taking a pointer to a temporary stack value when you call `writer` on the result of `std.io.countingWriter`, in stage2 this will result in a compile error.  To fix this you need to store `w: std.io.CountingWriter(std.fs.File.Writer)` in the struct. 

I have no idea why it is writing to stdout.
