### ISSUE TITLE
Stage2: unreachable else prong

### ISSUE THREAD

**Issue by Vexu** [ziglang/zig#11798]
A common pattern in Zig code is to only partially handle errors and return the rest to the caller with something like:
```zig
foo() catch |err| switch (err) {
    error.TheOneICareAbout => // something
    else => |e| return e,
}
```
With stage2 this causes issues in generic code where `error.TheOneICareAbout` is sometimes the only error and results in an `error: unreachable else prong; all cases already handled`.

Stage1 deals with this by not having that error when switching on errors but I think it would be better to detect and allow this specific pattern.

**Comment by nektro** [comment]
hm? this is one of the main features of being able to switch on errors

**Comment by Vexu** [comment]
Reopening since this error still occurs when there are defers:
```zig
fn foo() error{TheOneICareAbout}!void {}
test {
    defer _ = 1;
    foo() catch |err| switch (err) {
        error.TheOneICareAbout => {},
        else => |e| return e,
    };
}
```
This is hard to detect with the way defers are currently implemented so I think this error should be removed in the meanwhile.
