### ISSUE TITLE
Segfault possibly related to `for` variable capture

### ISSUE THREAD

**Issue by samrat** [ziglang/zig#11840]
### Zig Version

0.9.1

### Steps to Reproduce

This seems to happen in `0.9.1` as well as the latest `0.10.0` build.

The following program segfaults the compiler:

```zig
const std = @import("std");
const ArrayList = std.ArrayList;

const FooKind = enum {
    afoo,
    bfoo,
};

const Foo = union(FooKind) {
    afoo: struct {
        aa: u32,
    },
    bfoo: struct {
        bb: u8,
    },
};

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    var allocator = gpa.allocator();

    var foos = ArrayList(*Foo).init(allocator);

    var f = try allocator.create(Foo);
    f.* = Foo { .afoo = .{ .aa = 32 }};
    try foos.append(f);

    for (foos.items) |p_foo| {
        _ = p_foo;
        // const foo = p_foo.*;
        // _ = foo;
    }
}
```

Strangely, uncommenting the commented out lines makes the segfault go away. (Thanks to @InKryption for coming up with a minimized version of the program on Discord).

### Expected Behavior

The compiler should not segfault.

### Actual Behavior

Compiler segfaults with error code 139

**Comment by InKryption** [comment]
The segfault also manifests given:
```
for (foos.items) |*p_foo| {
    const foo = p_foo.*;
    _ = foo;
}
```
unless you dereference the inner-most pointer (so `p_foo.*.*`).

**Comment by Vexu** [comment]
Works as expected with the self-hosted compiler.
