### ISSUE TITLE
useless asm code from release-small binary file

### ISSUE THREAD

**Issue by bronze1man** [ziglang/zig#1184]
I use nm to see what in a release-small binary file of zig hello world program on mac os:
```
const std = @import("std");

pub fn main() !void {
    // If this program is run without stdout attached, exit with an error.
    var stdout_file = try std.io.getStdOut();
    // If this program encounters pipe failure when printing to stdout, exit
    // with an error.
    try stdout_file.write("Hello, world!\n");
}
```

I found a lot of useless functions:
```
00000001000027d0 T ___udivdi3
00000001000027e0 T ___umoddi3
```

Then I use ida to check the reference of those functions, I can not find reference of those functions.
I also review the asm code of the main function, it do not call them. Please correct me if i am wrong. 
I think those functions should not include in the binary file since the user want the small binary file.

The binary file size of that zig hello world program is 25KB. It is much smaller than golang hello world program.

**Comment by andrewrk** [comment]
This is #54

Fairly straightforward to solve, just need to use llvm's API to turn
compiler_rt.o into compiler_rt.a before linking.

**Comment by andrewrk** [comment]
Closing since #54 has all the information. Linking this way will omit unused functions from the final binary.
