### ISSUE TITLE
Stage2 can't negate a NaN at runtime

### ISSUE THREAD

**Issue by Vexu** [ziglang/zig#11853]
In the AIR negation is implemented as `0 - val` which means that a NaN cannot be negated using the `-` operator. I'm not sure how desirable negative NaNs are but the behavior should be consistent at comptime and runtime.
```zig
test {
    std.debug.print("{d}\n", .{-math.nan(f32)}); // nan
    std.debug.print("{d}\n", .{-comptime math.nan(f32)}); // -nan
}
```

**Comment by andrewrk** [comment]
stage1 lowers to
```llvm
  %2 = fneg float %1
```

stage2 lowers to
```llvm
  %2 = fsub float 0.000000e+00, %1
```

stage1 is correct
