### ISSUE TITLE
Stage2 specific union segfaults test runner when used in error union or optional

### ISSUE THREAD

**Issue by Vexu** [ziglang/zig#11857]
```zig
test {
    const U = extern union {
        in6: extern struct {
            family: u16,
            port: u16,
            flowinfo: u32,
            addr: [20]u8,
        },
        un: [110]u8,

        fn foo() !@This() {
            return undefined;
        }
    };
    var a: ?U = .{ .un = [_]u8{0} ** 110 };
    _ = a.?;
}

```

**Comment by andrewrk** [comment]
AIR looks good:

```
  %10 = optional_payload_ptr_set(*test2.doTheTest.U, %8)
  %28!= store(%10!, %26!)
```

LLVM shows the `store` being lowered to a memcpy with 112 bytes where 110 is expected:

```llvm
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 %5, i8* align 4 getelementptr inbounds ({ [110 x i8] }, { [110 x i8] }* @0, i32 0, i32 0, i32 0), i64 112, i1 false), !dbg !86
```

I think the next step here is figuring out why the memcpy is copying 112 bytes (overwriting the non-null-byte) instead of the expected 110 (size of the union).

**Comment by andrewrk** [comment]
112 is computed based on taking 110 and then aligning it to 4 bytes (because of the u32). This is correct. It's actually the layout of the union llvm type that is missing 2 bytes of padding:

```llvm
%test2.doTheTest.U = type { <{ %test2.doTheTest.U.doTheTest.U__struct_222, [82 x i8] }> }
```

This comes out to 110 but it should be 84 x i8, making it 112.
