### ISSUE TITLE
Documentation of Methods in structs Incorrect and fails to compile.

### ISSUE THREAD

**Issue by jlwiza** [ziglang/zig#11879]
### Zig Version

0.9.1

### Steps to Reproduce

The code in the documentation is incorrect and fails to compile.
the documentation seems to need to be updated and include a comment about
every method needs the first parameter to be self and either the type the current struct or pointer to the current struct.

this is the struct copied and pasted from the documentation about methods

```
 const std = @import("std");
// Structs can have methods
// Struct methods are not special, they are only namespaced
// functions that you can call with dot syntax.
const Vec3 = struct {
    x: f32,
    y: f32,
    z: f32,
    pub fn init(x: f32, y: f32, z: f32) Vec3 {
        return Vec3 {
            .x = x,
            .y = y,
            .z = z,
        };
    }

    pub fn dot(self: Vec3, other: Vec3) f32 {
        return self.x * other.x + self.y * other.y + self.z * other.z;
    }
};
pub fn main() anyerror!void {
}

test "basic test" {
    var v3: Vec3 =  undefined;
    v3.init(1,2,3);
    try std.testing.expectEqual(v3.y, 2);
}
```

### Expected Behavior

The documentation seems to just be out of date, and should be updated.

### Actual Behavior

output is 
.\src\main.zig:33:12: error: expected 3 argument(s), found 4
    v3.init(1,2,3);
           ^
.\src\main.zig:12:9: note: declared here
    pub fn init(x: f32, y: f32, z: f32) Vec3 {
        ^

**Comment by mayerraphael** [comment]
Your usage in the test is wrong.
First, you define an uninitialized variable. Then you call a static method of the Vec3 struct via the variable. This cannot work.

You are mixing your struct "namespace" V3 with your variable v3.

What would work:
`
  var v3: Vec3 =  undefined;
  v3 = V3.init(1,2,3);
`
or better, like in the documentation:
`
 const v1 = Vec3.init(1.0, 0.0, 0.0);
`
