### ISSUE TITLE
adding linker script throws error on 0.10.0-dev.2431

### ISSUE THREAD

**Issue by EternalRisen** [ziglang/zig#11872]
### Zig Version

0.10.0-dev.2431+0e6285c8f

### Steps to Reproduce

1. create a program with a linker script
2. add the linker script with `setLinkerScriptPath()` in your `build.zig`
3. error

### Expected Behavior

add the linker script and then compile

### Actual Behavior

```
./build.zig:40:29: error: expected type 'std.build.FileSource', found '*const [16:0]u8'
    bin.setLinkerScriptPath("linker/linker.ld");
                            ^
/usr/lib/zig/lib/std/build.zig:1415:24: note: std.build.FileSource declared here
pub const FileSource = union(enum) {
                       ^
```

**Comment by EternalRisen** [comment]
I would also like to note that when I was using 0.9.1 I didn't have this issue, so I will fall back to that version for now

**Comment by EternalRisen** [comment]
okay so the fix to this was changing `.path` to be where the linker file was, as the argument for `path` was changed to `FileSource`

- bin.setLinkerScriptPath("linker/linker.ld");
+ bint.setLinkerScriptPath(.{.path = "linker/linker.ld"})

**Comment by nektro** [comment]
`bint.setLinkerScriptPath(.{.path = "linker/linker.ld"});` is correct

**Comment by EternalRisen** [comment]
yeah, just wasn't sure at first since I couldn't find any documentation on this before submitting an issue.
