### ISSUE TITLE
Pointer cast: incorrect alignment

### ISSUE THREAD

**Issue by renatoathaydes** [ziglang/zig#11887]
### Zig Version

0.10.0-dev.2577+5816d3eae

### Steps to Reproduce

Run `zig test a.zig` with this file:

```zig
const std = @import("std");

fn strToPtr(str: [:0]const u8) [*c]const usize {
    var s: [*c]const usize = @ptrCast([*c]const usize, @alignCast(std.meta.alignment(usize), str));
    return s;
}

test "can store data in hash table" {
    _ = strToPtr("foo-value");
}
```

### Expected Behavior

I believe this code should work.

If we pass a string literal to `strToPtr`, it does work:

```zig
const std = @import("std");

fn strToPtr(_: [:0]const u8) [*c]const usize {
    var s: [*c]const usize = @ptrCast([*c]const usize, @alignCast(std.meta.alignment(usize), "foo-value"));
    return s;
}

test "can store data in hash table" {
    _ = strToPtr("foo-value");
}
```

Result:

```
All 1 tests passed.
```

### Actual Behavior

Result:

```
Test [1/1] test "can store data in hash table"... thread 5406622 panic: incorrect alignment
src/zig-c/src/encoder_test.zig:15:94: 0x1032a3815 in strToPtr (test)
    var s: [*c]const usize = @ptrCast([*c]const usize, @alignCast(std.meta.alignment(usize), str));
                                                                                             ^
src/zig-c/src/encoder_test.zig:20:17: 0x1032a27a3 in test "can store data in hash table" (test)
    _ = strToPtr("foo-value");
                ^
/Users/renato/programming/apps/zig-macos-x86_64-0.10.0-dev.2577+5816d3eae/lib/zig/test_runner.zig:79:28: 0x1032a3c5b in (root).main (test)
        } else test_fn.func();
                           ^
/Users/renato/programming/apps/zig-macos-x86_64-0.10.0-dev.2577+5816d3eae/lib/zig/std/start.zig:571:22: 0x1032d223c in std.start.callMain (test)
            root.main();
                     ^
/Users/renato/programming/apps/zig-macos-x86_64-0.10.0-dev.2577+5816d3eae/lib/zig/std/start.zig:515:12: 0x1032a5627 in std.start.callMainWithArgs (test)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/Users/renato/programming/apps/zig-macos-x86_64-0.10.0-dev.2577+5816d3eae/lib/zig/std/start.zig:480:12: 0x1032a5565 in std.start.main (test)
    return @call(.{ .modifier = .always_inline }, callMainWithArgs, .{ @intCast(usize, c_argc), c_argv, envp });
           ^
???:?:?: 0x10ca5451d in ??? (???)
???:?:?: 0x0 in ??? (???)
error: the following test command crashed:
src/zig-cache/o/b14ed7269a36adbb9f2efb33141ebaf1/test /Users/renato/programming/apps/zig-macos-x86_64-0.10.0-dev.2577+5816d3eae/zig
```

If there is an easier way to pass to C something looking like a `const uintptr_t *`, do let me know :)!

**Comment by renatoathaydes** [comment]
Ok, I was being wrong again :( the non-literal was not a pointer... Fixed with:

```zig
@ptrCast([*c]const usize, @alignCast(std.meta.alignment(usize), &str));
```

If anything, maybe there could be a nicer error message in this case? Anyway, I suppose besides the error being difficult to understand, there's no bug here.

**Comment by leecannon** [comment]
`str` is not a pointer it is a slice (basically `struct { ptr: [*]u8, len: usize }` but the order and exact layout are not defined)

In your code you are taking a pointer to a slice then casting that to a pointer to a usize?

**Comment by renatoathaydes** [comment]
@leecannon I am probably messing up something... in C, it seems to need to look like this:

```c
  const uintptr_t * s = (const uintptr_t *)"hello zig";
  printf("S is '%s'\n", (const char *) s);
```

The code needs to use `uintptr` because it's going to store the pointer in a hash table that can keep pointers to anything.

What do you think?

**Comment by renatoathaydes** [comment]
BTW the hash table implementation in C is based on this: http://rosettacode.org/wiki/Associative_arrays/Creation/C#POSIX_hsearch.28.29

I want to put Zig strings (not literals , they come from a file or stream) into that table, then get them back as Zig strings again, of course. I am using C just to learn how it works, hoping later to use only Zig.

**Comment by leecannon** [comment]
The problem is a pointer to bytes is align 1 but a pointer to usize is align 8 (on 64 bit), zig will not let you cast any byte pointer to usize without an align cast which like you experienced will reject any that are not divisible by 8.

This is the type of thing `anyopaque` is for.

```zig
fn strToPtr(str: [:0]const u8) *const anyopaque {
    // we cast the `[*:0]const u8` multi-item pointer to `*const anyopaque`, and don't keep the length from the slice
    return @ptrCast(*const anyopaque, str.ptr); 
}

fn ptrToStr(ptr: *const anyopaque) [:0]const u8 {
    // in order to reconstruct the slice we use `std.mem.span` which uses the fact it is zero terminated to basically `strlen` it
    return std.mem.span(@ptrCast([*:0]const u8, ptr));
}
```

**Comment by renatoathaydes** [comment]
Oh, I see. But how to I got to/from opaque pointers when interoping with the C code?

Getting these errors now:

```
./src/encoder_test.zig:28:28: error: expected type '[*c]const usize', found '*const anyopaque'
    c.store("foo", strToPtr("foo-value"));
                           ^
./src/encoder_test.zig:28:28: note: pointer type child 'anyopaque' cannot cast into pointer type child 'usize'
    c.store("foo", strToPtr("foo-value"));
                           ^
```

Is this even possible with that C function type signature?

**Comment by renatoathaydes** [comment]
I had missed this from the Zig docs:
>  To interop with the C void type, use anyopaque. 
So, is it correct to assume a generic data structure should not use `uintptr_t`, just `void *`? I think that post I mentioned just messed up my understanding...

**Comment by leecannon** [comment]
It's fine to use `unitptr`/`usize` by using `@ptrToInt`/`@intToPtr` but your example doesnt use `uintptr` it uses a pointer to `uintptr`:
```c
const uintptr_t * s = (const uintptr_t *)"hello zig";
```
which implies a pointer that points at a `uintptr`

**Comment by renatoathaydes** [comment]
I need the pointer to a pointer to retrieve items:

```
void store(const char *key, const uintptr_t value)

int fetch(const char *key, uintptr_t *value)
```

`store` takes a normal pointer, `fetch` takes a pointer-pointer (where it will store the pointer to the result). This is messing with my head.

**Comment by renatoathaydes** [comment]
I wrote this C code which I  think illustrates the types correctly:

```c
#include <inttypes.h>
#include <stdio.h>

uintptr_t _p;

void store(const char *key, const uintptr_t value)
{
  _p = value;
}

int fetch(const char *key, uintptr_t *value)
{
  *value = _p;
  return 0;
}

int main() {
  char *s = "hello";
  store("foo", (uintptr_t) "goodbye");
  fetch("foo", (uintptr_t *) &s);
  printf("s is %s\n", s);
}
```

Then, I asked Zig to translate it and got this:

```zig
pub export var _p: usize = @import("std").mem.zeroes(usize);
pub export fn store(arg_key: [*c]const u8, value: usize) void {
    var key = arg_key;
    _ = key;
    _p = value;
}
pub export fn fetch(arg_key: [*c]const u8, arg_value: [*c]usize) c_int {
    var key = arg_key;
    _ = key;
    var value = arg_value;
    value.* = _p;
    return 0;
}
pub export fn main() c_int {
    var s: [*c]u8 = @intToPtr([*c]u8, @ptrToInt("hello"));
    store("foo", @intCast(usize, @ptrToInt("goodbye")));
    _ = fetch("foo", @ptrCast([*c]usize, @alignCast(@import("std").meta.alignment(usize), &s)));
    _ = printf("s is %s\n", s);
    return 0;
}
```

Should I try to simplify the Zig side of this using `anyopaque` or this is fine (I will try to bury this into a "adapt" layer somewhere very hidden, of course)?
