### ISSUE TITLE
Proposal: Add GitHub Issue/PR Templates

### ISSUE THREAD

**Issue by v1zix** [ziglang/zig#1189]
I've found having templates can help bug reports get more consistent information so that issues can be resolved faster. GitHub now supports having multiple templates (https://blog.github.com/2018-01-25-multiple-issue-and-pull-request-templates/) so starting with 1 and 2 would probably get the most value.
1. Bug Reports - Including information like OS, steps to reproduce, stack trace, etc.
2. Feature Requests - Maybe link to the Zen of Zig?
3. Chores - Documentation updates, updating tests, etc.
4. Questions - I'm not sure if questions should be directed here, so if not it can just link to something like the IRC channel or the subreddit

If you want to see an example of multiple issue templates in use here's vscode's repo: https://github.com/Microsoft/vscode/tree/master/.github/ISSUE_TEMPLATE

I can't think of a good PR template off the top of my head, but from what I've usually seen they have checklists of some kind.

**Comment by andrewrk** [comment]
Thanks for the suggestion. I don't feel the need for this (zig team feel free to speak up here) but I'll keep it in mind for the future if I think it will help.
