### ISSUE TITLE
doc: Please document what type can put in the while field

### ISSUE THREAD

**Issue by bronze1man** [ziglang/zig#1190]
The first time I see following code, i do not know what it means:
```
    while (eventuallyNullSequence()) |value| {
        sum2 += value;
    } else {
        assert(sum1 == 3);
    }
```

Then I see return type of `eventuallyNullSequence()` : 
```
fn eventuallyNullSequence() ?u32
```

Then Why not the return type of `eventuallyNullSequence()` is bool? 
So please tell me all the type that while can accept.

I am also afraid that zig language may fall into this kind of bad design:
https://stackoverflow.com/a/14536172/1586797

I do not know all picture of the syntax of the while stuff, so please tell me correctly.
Very complex syntax can force me to debug my knowledge of tool.

The bad design in js, php is that you can not easily predict weather `true==3` is true or false without read the lauguang document carefully.

**Comment by andrewrk** [comment]
Have a look now: https://ziglang.org/documentation/master/#while-with-Optionals

notably I added these lines:

>  When the `|x|` syntax is present on a while expression, the while condition must have an Optional Type. 

>  When the `else |x|` syntax is present on a while expression, the while condition must have an Error Union Type.

**Comment by bronze1man** [comment]
Thanks, you write the document so quickly.
It is clearly to me now. 
It is complex but it can be predicted easily base on the syntax and the type of while condition.
