### ISSUE TITLE
zig build error

### ISSUE THREAD

**Issue by AnimalStudioOfficial** [ziglang/zig#11911]
### Zig Version

0.10.0-dev.2675+6de0c622f

### Steps to Reproduce

I did:
mkdir build-release
cd build-release
"c:\Program Files\CMake\bin\cmake.exe" .. -Thost=x64 -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH=C:\zig+llvm+lld+clang-x86_64-windows-gnu-0.9.1-dev.9+64a2b14f2 -DCMAKE_BUILD_TYPE=Release

### Expected Behavior

Compile zig from source

### Actual Behavior

I got a output:
$ "c:\Program Files\CMake\bin\cmake.exe" .. -Thost=x64 -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH=C:\zig+llvm+lld+clang-x86_64-windows-gnu-0.9.1-dev.9+64a2b14f2 -DCMAKE_BUILD_TYPE=Release
-- Found ccache C:/ProgramData/chocolatey/bin/ccache.exe
-- The C compiler identification is MSVC 19.31.31104.0
-- The CXX compiler identification is MSVC 19.31.31104.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring zig version 0.10.0-dev.2675+6de0c622f
CMake Error at cmake/Findllvm.cmake:82 (message):
  unable to find llvm-config
Call Stack (most recent call first):
  CMakeLists.txt:107 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/zig/zig/build-release/CMakeFiles/CMakeOutput.log".

**Comment by andrewrk** [comment]
Please see [Building Zig on Windows](https://github.com/ziglang/zig/wiki/Building-Zig-on-Windows). You have mixed Option 2 with the dev kit from Option 1. You needed to get the other tarball from the Option 2 section.

If you need more help please take this question to one of the [community spaces](https://github.com/ziglang/zig/wiki/Community) and ask nicely.
