### ISSUE TITLE
Multiple char ranges not recognized in switch statements

### ISSUE THREAD

**Issue by ksqsf** [ziglang/zig#11927]
### Zig Version

0.10.0-dev.2670+ca9862578

### Steps to Reproduce

The following piece of code does not compile.

```
const x = switch('a') {
    '_', ('a'...'z'), ('A'...'Z') => {
    },
    else => unreachable,
};
```

### Expected Behavior

Char literals and ranges should probably work as if they are numbers in all contexts.

For example, the following code compiles just fine:

```
const x = switch(0) {
    0, 100...200, 1000...2000 => {
    },
    else => unreachable,
};
```

### Actual Behavior

```
a.zig:2:14: error: expected ')', found '...'
    '_', ('a'...'z'), ('A'...'Z') => {
             ^
```

**Comment by Luukdegram** [comment]
This doesn't work because the syntax is invalid. The syntax for numbers and character literals is identical.

The correct usage would be:
```zig
fn foo(char: u8) u32 {
    return switch(char) {
        '_', 'a'...'z' => 5,
        else => 10,
    };
}

const std = @import("std");
pub fn main () void {
    std.debug.print("Value: {d}\n", .{foo('c')});
}
// Value: 5
```

**Comment by ksqsf** [comment]
Thanks for the heads up. I forgot why I added the parentheses.
