### ISSUE TITLE
Weird compiler crash

### ISSUE THREAD

**Issue by Jack-Ji** [ziglang/zig#11922]
### Zig Version

0.10.0-dev.2710+7c87f9c82

### Steps to Reproduce

```
const std = @import("std");

pub const Foo = struct {
    const Self = @This();

    vs: std.ArrayList(u32),

    pub fn init(allocator: std.mem.Allocator) Self {
        return .{
            .vs = std.ArrayList(u32).init(allocator),
        };
    }

    pub fn func(self: *Self, res: u32) !void {
        const base_index = @intCast(u32, self.vs.items.len);
        try self.vs.appendSlice(&.{
            if (0 == res) base_index else base_index,
        });
    }
};

pub fn main() anyerror!void {
    var rd = Foo.init(std.testing.allocator);
    try rd.func(1);
}
```

`zig run` above code.

### Expected Behavior

Run without issue.

### Actual Behavior

```
broken LLVM module found: Instruction does not dominate all uses!
  %18 = getelementptr inbounds %"struct:16:35", %"struct:16:35"* %3, i32 0, i32 0, !dbg !20065
  store i32 %19, i32* %18, align 4, !dbg !20067

This is a bug in the Zig compiler.thread 16736 panic:
Unable to dump stack trace: debug info stripped
```

**Comment by ifreund** [comment]
The thing in your code that's causing this is branching inside of an anon list literal (the if expression inside the call to `appendSlice()`). It can be worked around by doing the branch outside of the anon list literal:

```zig
const x = if (0 == res) base_index else base_index;
try self.vs.appendSlice(&.{x});
```

This is a known issue with the stage1 compiler and there's probably already an open issue for this but I don't have a link handy.

**Comment by Jack-Ji** [comment]
Thanks! I did search the issues, but had no luck finding anything related. Perhaps it's not labeled as bug. I'll be happy to close it if someone can provide a link to the existing issue.

**Comment by ehaas** [comment]
There are a couple existing issues related to this: #5230 #3882

**Comment by ifreund** [comment]
Thanks for the links, I'll close this as a duplicate then.
