### ISSUE TITLE
@bitCast triggers a panic when casting a slice to [2]u64

### ISSUE THREAD

**Issue by MetaphysicianLeo** [ziglang/zig#11937]
### Zig Version

0.10.0-dev.2624+d506275a0

### Steps to Reproduce
```zig
const std = @import("std");
const print = std.debug.print;

pub fn main() !void {
    const x: [3]u8 = [3]u8{1, 2, 3};
    const y: []const u8 = x[0..3];  

    print("{x}\n", .{ @bitCast([2]u64, y)[1] });
}
```

### Expected Behavior

@bitCast return a [2]u64 value

### Actual Behavior

Unreachable at /workspace/src/stage1/ir.cpp:23151 in buf_write_value_bytes. This is a bug in the Zig compiler.thread 19331 panic: 
Unable to dump stack trace: debug info stripped
Aborted

**Comment by leecannon** [comment]
Its true that the compiler should not crash but what your trying to do does not make sense.

A slice is a pointer and a length (similar to `struct { ptr: [*]const, len: usize }`) and `[2]u64` is a value *not* a pointer.

**Comment by MetaphysicianLeo** [comment]
> Its true that the compiler should not crash but what your trying to do does not make sense.
> 
> A slice is a pointer and a length (similar to `struct { ptr: [*]const, len: usize }`) and `[2]u64` is a value _not_ a pointer.

Ok, I understood.
Is that means you can't convert a pointer into u64 value through bitcast?

**Comment by nektro** [comment]
the size of `[*]u8` and `usize` are both `8` on 64bit systems, so theoretically unless explicitly outlawed by the specification, this should work. and would be cross platform to be `[2]usize`

**Comment by leecannon** [comment]
Yea I was thinking the same thing almost immediately after looking back at it but as they already marked it as closed I didn't bother commenting.

With the teo current implementation's a slice has the same layout as `[2]usize` but as it has an undefined layout this is a accident of the implementations not guaranteed by the spec (if there were one)

**Comment by ominitay** [comment]
> the bit size of `[*]u8` and `usize` are both `64` on 64bit systems, so theoretically unless explicitly outlawed by the specification, this should work. and would be cross platform to be `[2]usize`

A slice currently doesn't have a defined layout, so can't be used with `@bitCast` iirc.

**Comment by ifreund** [comment]
> A slice currently doesn't have a defined layout, so can't be used with `@bitCast` iirc.

This is correct
