### ISSUE TITLE
c import errors building self-hosted compiler

### ISSUE THREAD

**Issue by oltdaniel** [ziglang/zig#1196]
> Full error message [here](https://gist.github.com/oltdaniel/41c72bfe7af3ceef06c7eb450dac1cde)

Somehow the `$ bin/zig build --build-file ../build.zig test` command files after a successful build of zig.

- [x] I installed the `clang`, `llvm`, `lld` and `cmake` libraries. 
- [x] `/usr/include/inttypes.h` exists

```
zig/src-self-hosted/c.zig:1:9: error: C import failed
pub use @cImport({
...
```

Any ideas for a solution?

**Comment by andrewrk** [comment]
what linux distro are you on?

**Comment by oltdaniel** [comment]
`Ubuntu 16.04`

**Comment by oltdaniel** [comment]
@andrewrk Final solution required to define `__STDC_CONSTANT_MACROS` and `__STDC_LIMIT_MACROS`:

```zig
pub use @cImport({
    @cDefine("__STDC_CONSTANT_MACROS", "");
    @cDefine("__STDC_LIMIT_MACROS", "");
    @cInclude("inttypes.h");
    @cInclude("config.h");
    @cInclude("zig_llvm.h");
});
```

**Comment by andrewrk** [comment]
Thanks for testing!

**Comment by pftbest** [comment]
I have a similar problem on mac
```
macbook:build vadzim$ bin/zig build --build-file ../build.zig test
/Users/vadzim/Downloads/zig/src-self-hosted/c.zig:1:9: error: C import failed
pub use @cImport({
        ^
/Users/vadzim/Downloads/zig/build/lib/zig/include/inttypes.h:30:15: note: 'inttypes.h' file not found
#include_next <inttypes.h>
              ^
```

What can i do?
