### ISSUE TITLE
weird block on `reader.readAllAlloc` when reader.context is a stream

### ISSUE THREAD

**Issue by haolian9** [ziglang/zig#11968]
### Zig Version

0.9.1

### Steps to Reproduce

```
const std = @import("std");
const linux = std.os.linux;

test "reader.readAllAlloc" {
    var fds: [2]i32 = undefined;
    switch (linux.getErrno(linux.pipe(&fds))) {
        .SUCCESS => {},
        else => unreachable,
    }

    const reader_side = fds[0];
    const writer_side = fds[1];

    var reader_stream = std.net.Stream{ .handle = reader_side };
    defer reader_stream.close();

    var writer_stream = std.net.Stream{ .handle = writer_side };
    defer writer_stream.close();

    const in = "abcde";

    try writer_stream.writer().writeAll(in);

    if (true) {
        const out = try reader_stream.reader().readAllAlloc(std.testing.allocator, 5);
        defer std.testing.allocator.free(out);

        try std.testing.expectEqualSlices(u8, in, out);
    } else {
        var buf: [5]u8 = undefined;
        const n = try reader_stream.reader().readAll(&buf);
        const out = buf[0..n];

        try std.testing.expectEqualSlices(u8, in, out);
    }
}
```

### Expected Behavior

reader.readAllAlloc() in the true branch returns `abcde` and does not block forever.

### Actual Behavior

the true branch will block forever.

**Comment by IntegratedQuantum** [comment]
This seems to be the intended behaviour. From the doc strings:
```
        /// Allocates enough memory to hold all the contents of the stream. If the allocated
        /// memory would be greater than `max_size`, returns `error.StreamTooLong`.
        /// Caller owns returned memory.
        /// If this function returns an error, the contents from the stream read so far are lost.
        pub fn readAllAlloc(self: Self, allocator: mem.Allocator, max_size: usize) ![]u8
```
And until the stream is closed `readAllAlloc` does not know if it should throw `error.StreamTooLong`.

The naming is a bit confusing in my opinion:
`readAllAlloc` → tries to read the entire stream until the end, fails if the stream is too long.
`readAll` → tries to read exactly `x` bytes determined by the input buffer, if the stream is closed before `x` bytes were read then it returns the actual number of bytes that it could read.

I think the existence of the `max_size` parameter is also a bit weird/confusing. When I want to read the entire stream I don't exactly have an upper bound for reading the data(apart from available memory, which is already handled by the allocator anyways).

**Comment by haolian9** [comment]
> readAllAlloc → tries to read the entire stream until the end, fails if the stream is too long.

with a shorter max_size, `const out = try reader_stream.reader().readAllAlloc(std.testing.allocator, in.len - 1);`, it still blocks.

**Comment by IntegratedQuantum** [comment]
Yeah. The problem seems to be that it always reads until the arraylist buffer is full, using `readAll`. So it only catches the problem if the input length is larger then the next step in the arraylist buffer size.
The arraylist buffer starts at 8, so if the input string is 9 characters long it correctly throws `error.StreamTooLong`.

This can be fixed by replacing `readAll` by `read`.

**Comment by haolian9** [comment]
as nobody cares, i'm closing this
