### ISSUE TITLE
Where can we see the finances for the Zig Software Foundation?

### ISSUE THREAD

**Issue by chris2860** [ziglang/zig#11993]
The only available page is missing data for 2020 and 2022:
https://docs.google.com/spreadsheets/d/14_ljFHGFXY5NhBhlfjgkO0RZHqeVv04fAmCxw3ZusYc/edit#gid=99104331

Where can we find a more comprehensive resource?

**Comment by andrewrk** [comment]
This is the issue tracker for the Zig compiler & toolchain. [ZSF web page is here](https://ziglang.org/zsf/)
