### ISSUE TITLE
broken LLVM module found: Invalid bitcast while using wuffs-v0.3.c

### ISSUE THREAD

**Issue by pierrec** [ziglang/zig#11995]
### Zig Version

0.10.0-dev.2836+2360f8c49

### Steps to Reproduce

1/ fetch the latest Wuffs version:
https://github.com/google/wuffs/blob/main/release/c/wuffs-v0.3.c

2/ translate it:
zig translate-c wuffs-v0.3.c > wuffs-v0.3.zig

3/ comment out the line 20894 (see #11994)

4/ run the following:
`const c = @import("wuffs-v0.3.zig");

test "broken LLVM module found: Invalid bitcast" {
    var buf = [_]u8{'h', 'i'};
    var s: []u8 = &buf;
    _ = c.wuffs_base__make_io_buffer(
        c.wuffs_base__make_slice_u8(s.ptr, s.len),
        c.wuffs_base__empty_io_buffer_meta(),
    );
}
`

### Expected Behavior

No tests to run.

### Actual Behavior

Code Generation [523/788] std.hash_map.HashMapUnmanaged([]const u8,u64,std.hash_map.StringContex... broken LLVM module found: Invalid bitcast
  %9 = bitcast i64 %2 to %wuffs-v0.3.struct_wuffs_base__io_buffer_meta__struct*, !dbg !2253

This is a bug in the Zig compiler.thread 7763739 panic: 
Unable to dump stack trace: debug info stripped
zsh: abort      zig test src/bug.zig

**Comment by Vexu** [comment]
Reduction:
```zig
pub fn wuffs_base__make_io_buffer(arg_data: wuffs_base__slice_u8, arg_meta: wuffs_base__io_buffer_meta) callconv(.C) void {
    _ = arg_data;
    _ = arg_meta;
}
pub const wuffs_base__io_buffer_meta = extern struct {
    wi: usize,
    ri: usize,
    pos: u64,
    closed: bool,
};
pub const wuffs_base__slice_u8 = extern struct {
    ptr: [*c]u8,
    len: usize,
};
test "broken LLVM module found: Invalid bitcast" {
    _ = wuffs_base__make_io_buffer(undefined, undefined);
}
```

Related #1481
