### ISSUE TITLE
Why File.write can not called on a *const File?

### ISSUE THREAD

**Issue by bronze1man** [ziglang/zig#1201]
I have following code:
```
const std = @import("std");

pub fn main() !void {
    const stdout_file = try std.io.getStdOut();
    try stdout_file.write("Hello, world!\n");
}
```

It is not work:
```
xxx/h.zig:5:9: error: expected type '*File', found '*const File'
    try stdout_file.write("Hello, world!\n");
        ^
```

I read the code of File.write, it do not change any thing in the File object.
I can not find the reason in the document in the section of `Functions` or `Assignment`.

By the way I think the error message should be(#1202):
```
expected type '*std.os.File', found '*const std.os.File'
```

**Comment by andrewrk** [comment]
It works now
