### ISSUE TITLE
ArgIterator.next() can be cross-platform without allocating on posix/wasi

### ISSUE THREAD

**Issue by pithlessly** [ziglang/zig#12034]
Currently the `std.Process.ArgIterator` API offers two ways of reading arguments:

- The `nextPosix` and `nextWasi` methods, which return the argument directly out of `std.os.argv` without allocating, but are obviously not usable on Windows;
- The `next(allocator)` method, which performs an allocation on every platform and requires the user to free it. 

As long as the API is committed to returning nul-terminated UTF8, allocation on Windows is unavoidable. But the allocation on posix/wasi is really only necessary to provide consistent ownership semantics for the returned buffer.

Many users might be interested in an API that avoids allocation on Unix systems by treating the buffer as borrowed on posix/wasi and owned in Windows. I can see two approaches to this:

1. Adding functions to `ArgIterator` which are used together for this functionality:

```zig
/// The buffer is `const` as a precaution against race conditions.
/// You must use `weakFreeArg` to deinitialize the returned memory when done.
pub fn weakNext(self: *ArgIterator, allocator: Allocator) ?(NextError![:0]const u8) {
    if (builtin.os.tag == .windows)
        return self.inner.next(allocator)
    else
        return self.inner.next() orelse return null;
}

pub fn weakFreeArg(allocator: Allocator, arg: [:0]const u8) void {
    if (builtin.os.tag == .windows)
        allocator.free(arg);
}
```

2. Creating a self-contained `Arg` struct which wraps the buffer and possibly the allocator:

```zig
pub const Arg = struct {
    data: []const u8,
    allocator: if (builtin.os.tag == .windows) Allocator else void,

    pub fn deinit(self: Arg) void {
        if (builtin.os.tag == .windows)
            self.allocator.free(self.data);
    }
};
```

**Comment by Hejsil** [comment]
I'd recommend having a look at the standard library on master. On system where it is possible, `ArgIterator.init` and `ArgIterator.next` allocates no memory:

```zig
pub fn initWithAllocator(allocator: mem.Allocator) InitError!ArgIterator {
    if (builtin.os.tag == .wasi and !builtin.link_libc) {
        return ArgIterator{ .inner = try InnerType.init(allocator) };
    }
    if (builtin.os.tag == .windows) {
        const cmd_line_w = os.windows.kernel32.GetCommandLineW();
        return ArgIterator{ .inner = try InnerType.initUtf16le(allocator, cmd_line_w) };
    }

    return ArgIterator{ .inner = InnerType.init() };
}

pub fn next(self: *ArgIterator) ?([:0]const u8) {
    return self.inner.next();
}
```
