### ISSUE TITLE
std.startgate aka stargate

### ISSUE THREAD

**Issue by leecannon** [ziglang/zig#12048]
I spent 40 seconds talking to @InKryption and @ominitay and they conviced me that removing `std.start` is a great move for the language.

# :crown: 
* The ultimate goal of most programs seems to be to call `exit`, `exit_group`, etc; currently this intent is hidden.
* More reading (:+1:) and more writing (:+1:), more code is more better :book: 
* I'm sure the current way is a local maximum :100: (I don't know what this means)
* Freestanding is a first class citizen :1st_place_medal: 
* I'm sure there will be 1000's of packages providing entry points available once we have a package manager, more :package:'s is more better. 

# :hankey: 
* It is not obvious at all how to get arguments, environment variables, etc especically on all the different OSes and arches it's basically guaranteed to be buggy :bug: 
* Similarity/Familiarity is going to tank, everyones entry point is going to be different :fire: 

I'm sure with these points it will be clear this is best choice going forward.

_I'm sorry InKryption made me do it_

**Comment by ominitay** [comment]
From Zig Zen: :rocket: :rocket:
:a: communictate intent :nerd_face: precisely

idk i can't think of anything about this one, but i think @InKryption knows a lot so i'll attribute this to them :eyeglasses:

L :trollface: memory is a resource :moneybag: :moneybag: 

as you all know, storage :floppy_disk: is a form of memory :brain:, which we should minimise :small_red_triangle_down: use of. `lib/std/start.zig` is 24KiB big :weight_lifting:! removing this from the drives of 1 million :people_holding_hands: users (a good scientist :lab_coat:  never reveals their sources :book:), which means a 24 gigabyte reduction :point_down: in hard drive use. this is equivalent to about £0.48 GBP :crown: cost saving according to amazon aws :cloud:! very beneficial for the economy :money_mouth_face:.

**Comment by andrewrk** [comment]
not sure what's going on here but I'm gonna ban you two for a month. nothing personal, please don't fuck with the issue tracker.
