### ISSUE TITLE
disallow variable declaration of `_`,  prevent `_` from shadowing itself, and prevent read access of `_`

### ISSUE THREAD

**Issue by Hejsil** [ziglang/zig#1204]
Currently, this is allowed:

```rust
test "" {
    var _: usize = 2;
    _ = false;
    var b = _;
}
```

This works because `_` can be declared and used, but when assigned it is treated as a discard variable. I propose that `_` should only work for discarding, and you shouldn't be able to declare it. Also, you should be able to discard payloads so that examples like these compile:
```rust
test "" {
    for ([]void{}) |_, i| {
        for ([]void{}) |_, j| { // error: redeclaration of variable '_'
            
        }
    }
}
```

**Comment by tiehuis** [comment]
What about when using `_` as a member name in a struct or enum?

Lately I wrote something like this, which isn't that bad really and displays the intent clearly. Reordering however is a small issue. I'd consider this more about the consistency here than wanting it for the reordering issue.

```
const S = enum {
    ...
    _reserved18,
    _reserved19,
    avx512_4vnniw,
    avx512_4fmaps,
    _reserved20,
    _reserved21,
    _reserved22,
    _reserved23,
    _reserved24,
    _reserved25,
    _reserved26,
    _reserved27,
    _reserved28,
    _reserved29,
    _reserved30,
    _reserved31,
    _reserved32,
    _reserved33,
    pconfig,
    ...
};
```

would become:

```
const S = enum {
    ...
    _,
    _,
    avx512_4vnniw,
    avx512_4fmaps,
    _,
    _,
    _,
    _,
    _,
    _,
    _,
    _,
    _,
    _,
    _,
    _,
    _,
    _,
    pconfig,
    ...
};
```

Slight concern that this is less clear in intent.

**Comment by Hejsil** [comment]
When I say disallow declaring `_`, I mean don't allow the name to be declared so it can be used. Your example would not declare 10 enum fields named `_` but would treat `_` as discard or padding (depending on how we look it this). #676 is related to this, right?

**Comment by tiehuis** [comment]
Yeah, it would be for padding. That issue is exactly it and has already been mentioned it seems.

**Comment by kristate** [comment]
@Hejsil could you please open another issue for `for` loops? Thanks.

```
test "" {
    for ([]void{}) |_, i| {
        for ([]void{}) |_, j| { // error: redeclaration of variable '_'
            
        }
    }
}
```

**Comment by BarabasGitHub** [comment]
@andrewrk What's wrong with the loop syntax? It's kinda neat. At least the `|variable|` part.

**Comment by monouser7dig** [comment]
` _ = false;` actually makes sende in the context of 
https://github.com/ziglang/zig/issues/1268#issue-343150538

>  custom_allocator actually implements the allocator interface, there can easily be added a small syntax to ensure this or a small hack like in golang using an anonymous variable

**Comment by andrewrk** [comment]
@BarabasGitHub what's wrong is that it doesn't compile, but it should. `error: redeclaration of variable '_'` is an incorrect compile error.
