### ISSUE TITLE
add @bswap and @bitReverse intrinsics

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1207]
* http://llvm.org/docs/LangRef.html#llvm-bitreverse-intrinsics
 * http://llvm.org/docs/LangRef.html#llvm-bswap-intrinsics

**Comment by emekoi** [comment]
@andrewrk close this?

**Comment by andrewrk** [comment]
landed in f6cd68386d76e4a9a489187c47f218b59e1734f3 and b883bc873df7f1a8fa3a13800402e1ec8da74328
