### ISSUE TITLE
Zig Build is not idempotent

### ISSUE THREAD

**Issue by yurivish** [ziglang/zig#12078]
### Zig Version

0.9.1 on macOS 12.4

### Steps to Reproduce

In an empty directory:

```shell
% echo 'export fn add(a: i32, b: i32) i32 { return a + b; }' > main.zig
% zig build-lib main.zig -target wasm32-freestanding -dynamic -OReleaseFast
% ls -l | grep wasm
total 16
-rwxr-xr-x@ 1 yurivish  staff   65 Jul 11 14:00 main.wasm
% zig build-lib main.zig -target wasm32-freestanding -dynamic -OReleaseFast
% ls -l | grep wasm
total 16
-rwxr-xr-x@ 1 yurivish  staff   35 Jul 11 14:01 main.wasm
```

### Expected Behavior

The output of the build should be the same both times.

### Actual Behavior

The output is different – the main.wasm file size has changed to 35 bytes from 56, and the exported function is gone from the compiled output.

Deleting the `zig-cache` directory before performing a rebuild causes the build to produce the right output, as it did the first time.

This doesn't happen with `-OReleaseSafe` (rebuilding works correctly).

**Comment by jedisct1** [comment]
Can you confirm that it still happens with the `master` branch?

That seems similar to #11637

**Comment by yurivish** [comment]
Just checked and it seems fixed on master! Curiously the safe binary is ~85x larger than it was previously (now 5kb, was 65b), and the fast one is ~70x larger than the previous safe binary.

**Comment by Luukdegram** [comment]
> Just checked and it seems fixed on master! Curiously the safe binary is ~85x larger than it was previously (now 5kb, was 65b), and the fast one is ~70x larger than the previous safe binary.

This is due to it containing debug info currently (regardless of build mode). I should have a fix for that soon.
