### ISSUE TITLE
doc: Will zig allow runtime init functions?

### ISSUE THREAD

**Issue by bronze1man** [ziglang/zig#1210]
What is runtime init functions:
* You can write a function with special flag, and that function will be run once before the main function.

Here is some examples in golang:
```
func init(){
  go func(){ // yes, you can even start a new thread in init function.
   select{
     ...
    }
   }
}
```

I do not like runtime init functions. 
* It is a hidden performance issue something.
* It is very bad for binary size if you use it a lot.The compiler will not remove any init function and all the function it depend.
* It sometimes make code difficult to read.

I just want a confirm that zig will not allow runtime init functions/any hidden code run before the entry function in the future.

If zig have one, please document how to use it.
If zig do not have one, please document it do not have runtime init functions.

**Comment by 0joshuaolson1** [comment]
Something so against Zig philosophy would be documented or go through the proposal process.

"No hidden initialization code" seems like a different issue though, i.e. what's the overhead on platform X if you use stdout, debug symbols, reflection, an async event loop, etc.

**Comment by PavelVozenilek** [comment]
I used runtime init functions in C (non-standard extension) to implement my own test framework. Without them it would be impossible to add tests so easily.

Zig should allow to customize/replace the testing mechanism, then one big use case for such feature will disappear.
