### ISSUE TITLE
fn(*u16) --> fn(*u32) error

### ISSUE THREAD

**Issue by htqx** [ziglang/zig#12146]
### Zig Version

0.10.0-dev.2751+08459ff1c

### Steps to Reproduce

> fn fxxx(a : *u32) void{
>     _ = a;
>     // print("{}\n", a);
> }
> 

```zig
var g:fn(*u16)void = fxxx;
```
error: expected type 'fn(*u16) void', found 'fn(*u32) void'
note: parameter 0: '*u32' cannot cast into '*u16'
note: pointer type child 'u16' cannot cast into pointer type child 'u32'
 note: unsigned 32-bit int cannot represent all possible unsigned 16-bit values

why?

### Expected Behavior

ok

### Actual Behavior

error

**Comment by Vexu** [comment]
> `note: unsigned 32-bit int cannot represent all possible unsigned 16-bit values`

That note is misleading and has been removed from the upcoming self hosted compiler in 0370006c1f5a23e5e2d0993fb71f825791d64957.

The error is correct and the only way around it is using `@ptrCast` but that'll likely lead to incorrect behavior.

**Comment by nektro** [comment]
`note: parameter 0: '*u32' cannot cast into '*u16'` is the much more accurate one
