### ISSUE TITLE
Are tuples shared?

### ISSUE THREAD

**Issue by htqx** [ziglang/zig#12159]
### Zig Version

0.10.0-dev.2977+7d2e14267

### Steps to Reproduce

```zig
var list = .{"sss", 1,2,3};
    var list2 = @TypeOf(list) {.@"0" = "xxx", .@"1" = 4, .@"2"=5,
        .@"3" = 6};
    if (&list == &list2) print("{}?\n",.{list2});

```
print ： { [3:0]u8@203ffa, 1, 2, 3 }?

Is this a bug or a mechanism?

### Expected Behavior

new tuple

### Actual Behavior

list2 = list

**Comment by batiati** [comment]
All fields are comptime values, so the tuple is zero len and unique. Try to initialize some field with a runtime value and it should work as expected.

I think it behaves correctly, but it should give a compiler error on the second initialization.

**Comment by yujiri8** [comment]
This makes no sense to me.

> All fields are comptime values, so the tuple is zero len and unique.

But why isn't the second one just another zero len and unique value?

**Comment by batiati** [comment]
The second one should not be possible to initialize, this current issue is the same case as [#5497](https://github.com/ziglang/zig/issues/6656#issuecomment-707462261) but using a tuple instead of a struct.

```zig
pub fn main() !void {

    const AllComptime = struct {
        comptime v0: []const u8 = "sss",
        comptime v1: u32 = 1,
        comptime v2: u32 = 2,
    };

    var allComptime = AllComptime { .v0 = "sss", .v1 = 1, .v2 = 2 };
    var allComptime2 = AllComptime { .v0 = "abc", .v1 = 2, .v2 = 3 };

    std.debug.print("SizeOf AllComptime = {}\n", .{ @sizeOf(AllComptime) });
    if (&allComptime == &allComptime2) std.debug.print("Same address\n", .{});
```
```bash
$ zig build run
SizeOf AllComptime = 0
Same address
```
