### ISSUE TITLE
[zig cc] Preprocessor not processing all #define statements

### ISSUE THREAD

**Issue by Sirius902** [ziglang/zig#12152]
### Zig Version

0.10.0-dev.3027+0e26c6149

### Steps to Reproduce

On Windows, with the Windows SDK installed, attempt to build the below C program with `zig cc`.
```c
#include <winerror.h>
#include <stdio.h>

int main(void) {
    printf("%ld\n", ERROR_DELETE_PENDING);
    printf("%ld\n", ERROR_INCOMPATIBLE_WITH_GLOBAL_SHORT_NAME_REGISTRY_SETTING);
    return 0;
}
```

### Expected Behavior

I would expect this program to compile and print the following when executed.
```
303
304
```

### Actual Behavior

If I compile using Clang installed from winget, then I get the expected output. However if I compile with `zig cc`, then I get the following compiler error.
```
.\src\main.c:6:21: error: use of undeclared identifier 'ERROR_INCOMPATIBLE_WITH_GLOBAL_SHORT_NAME_REGISTRY_SETTING'
    printf("%ld\n", ERROR_INCOMPATIBLE_WITH_GLOBAL_SHORT_NAME_REGISTRY_SETTING);
                    ^
1 error generated.
```

The odd thing is though, looking at the C program, the two error defines used are defined in `winerror.h` directly next to each other with no `#ifdef` statements or the like that could cause one to be defined and not the other. Here's what the two defines look like in the header.
```c
//
// MessageId: ERROR_DELETE_PENDING
//
// MessageText:
//
// The file cannot be opened because it is in the process of being deleted.
//
#define ERROR_DELETE_PENDING             303L

//
// MessageId: ERROR_INCOMPATIBLE_WITH_GLOBAL_SHORT_NAME_REGISTRY_SETTING
//
// MessageText:
//
// Short name settings may not be changed on this volume due to the global registry setting.
//
#define ERROR_INCOMPATIBLE_WITH_GLOBAL_SHORT_NAME_REGISTRY_SETTING 304L
```

It seems that every error define after `ERROR_INCOMPATIBLE_WITH_GLOBAL_SHORT_NAME_REGISTRY_SETTING` in the header is affected as well, as using them also generates a `use of undeclared identifier` compiler error.

Here are the versions of `clang` and `zig cc`.
```
> clang --version
clang version 14.0.6
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```
```
> zig cc --version
clang version 14.0.6 (git@github.com:ziglang/zig-bootstrap.git dbc902054739800b8c1656dc1fb29571bba074b9)
Target: x86_64-unknown-windows-gnu
Thread model: posix
InstalledDir: D:/Dev/zig/test-cc
```

**Comment by slimsag** [comment]
Zig uses MinGW headers by default, which don't currently define `ERROR_INCOMPATIBLE_WITH_GLOBAL_SHORT_NAME_REGISTRY_SETTING`

https://github.com/ziglang/zig/pull/12087 would upgrade us to MinGW 10.0 headers, but those unfortunately don't appear to define it either.

You can use the host OS headers, if you like, though - via the `x86_64-windows-msvc` target it should use the Windows SDK on your system.

Or (hack) `#define` it yourself for now:

```
#ifndef ERROR_INCOMPATIBLE_WITH_GLOBAL_SHORT_NAME_REGISTRY_SETTING
#define ERROR_INCOMPATIBLE_WITH_GLOBAL_SHORT_NAME_REGISTRY_SETTING 0x00000130
#endif
```

**Comment by Sirius902** [comment]
@slimsag Ah I didn't realize it wasn't using the Windows SDK headers, thanks. I'll update the issue accordingly.

**Comment by Sirius902** [comment]
Actually since this is an issue with the MinGW headers themselves I'm not sure if this should be kept open, I'll close it for now.
