### ISSUE TITLE
stage 2: AArch64 C ABI Incorrect

### ISSUE THREAD

**Issue by topolarity** [ziglang/zig#12185]
### Zig Version

0.10.0-dev.3041+de62bd064

### Steps to Reproduce

`zig test test.zig foo.c`

```zig
// test.zig
const std = @import("std");

const T = extern struct {
    a: i32,
    padding: [4]u8,
    b: i64
};
extern fn foo() T;

test {
    var x = foo();
    try std.testing.expect(x.a == 4);
    try std.testing.expect(x.b == 155);
}
```
```c
// foo.c
#include "stdint.h"

typedef struct {
    uint32_t a;
    uint8_t padding[4];
    uint64_t b;
} Foo;

Foo foo() {
    return (Foo) { 4, {}, 155 };
}
```

### Expected Behavior

Test should pass, as it does on stage 1

### Actual Behavior

Test fails, on both Darwin and Linux

```
error: TestUnexpectedResult
???:?:?: 0x21962f in ??? (???)
???:?:?: 0x219823 in ??? (???)
```

I believe this is the cause of the problem @kamidev is seeing at https://github.com/ziglang/zig/issues/11450#issuecomment-1189986998

Specifically, `ZigClangASTUnit_getLocalPreprocessingEntities_begin` returns a struct with this layout

**Comment by topolarity** [comment]
This is probably covered by the existing C ABI tests somewhere, but I wanted to file a separate bug since this impacts stage 3 on some platforms.

**Comment by kamidev** [comment]
Thank you! I was just wondering if I should file a separate issue. There is a lot going on in CI right now, so testing stage3 behavior on all platforms may be difficult.

**Comment by kamidev** [comment]
By the way, the originally reported error still occurs for zig 0.10.0-dev.3049. I'll look a bit more using your test case.

**Comment by Luukdegram** [comment]
For your information, implementing the C ABI for AArch64 is still todo: https://github.com/ziglang/zig/blob/master/src/codegen/llvm.zig#L9201-L9316
The current implementation for x86_64 is also not tested on the CI yet, as there's still some TODO's before it can handle all the cases specified in https://github.com/ziglang/zig/tree/master/test/stage1/c_abi

Just mentioning this so you're not spending your free time trying to build stage3 constantly and expecting it to work :)

**Comment by andrewrk** [comment]
> This is probably covered by the existing C ABI tests somewhere, but I wanted to file a separate bug since this impacts stage 3 on some platforms.

https://github.com/ziglang/zig/blob/ca3adb83b7aa0e5045b1e7e193a0db2a5a31b16b/test/standalone.zig#L37-L40

Only enabled for x86_64 at the moment.

**Comment by kamidev** [comment]
> For your information, implementing the C ABI for AArch64 is still todo: https://github.com/ziglang/zig/blob/master/src/codegen/llvm.zig#L9201-L9316 The current implementation for x86_64 is also not tested on the CI yet (for stage2), as there's still some TODO's before it can handle all the cases specified in https://github.com/ziglang/zig/tree/master/test/stage1/c_abi
> 
> Just mentioning this so you're not spending your free time trying to build stage3 constantly and expecting it to work :) (Having this issue is great tho, to keep track of the progress and ensure it will be done in time for 0.10)

Thanks @Luukdegram for heads-up and info! Building now and then doesn't take that long. Expecting stage3 to work right now would be extremely time-consuming, of course. :-) But paying attention to what breaks when things are getting close is an interesting way to learn and might even be useful. Looking forward to 0.10!

**Comment by pdoane** [comment]
Adding this one as a test case I'm hitting with floating point struct parameters:

```
struct Rect
{
    double x;
    double y;
    double width;
    double height;
};

void testAbi(struct Rect rect)
```

Does not work when invoked with this extern declaration:

```
const Rect = extern struct
{
    x : f64,
    y : f64,
    width : f64,
    height : f64
};

extern fn testAbi(_:Rect) callconv(.C) void;
```
