### ISSUE TITLE
binary output of simple wasm example significantly increased in size

### ISSUE THREAD

**Issue by garyemerson** [ziglang/zig#12181]
### Summary

Output of simple wasm example has jumped from ~400 bytes to ~6K bytes when using compiler versions `0.9.1` and `0.10.0-dev.3041+de62bd064`, respectively.

### Zig Version

0.10.0-dev.3041+de62bd064

### Steps to Reproduce

**using compiler version 0.10.0-dev.3041+de62bd064:**
1. clone git repo https://github.com/meheleventyone/zig-wasm-test
2. checkout version 3cf0d624c7039fa03e1e32ea02e1466f09a07c98
3. run `zig build`
4. check size of wasmtest.wasm file in zig-cache dir and observe size is ~6K (6020 bytes for me)

**using compiler version 0.9.1:**
Repeat steps 1-3 from above
4. check size of wasmtest.wasm file in zig-cache dir and observe size is less than 500 bytes (391 bytes for me)

### Expected Behavior

small and simple code should produce small wasm binary

### Actual Behavior

wasm binary is larger than expected for size of code

**Comment by r00ster91** [comment]
Can you try `zig build -Drelease-small` and add `lib.strip = true;` here? https://github.com/meheleventyone/zig-wasm-test/blob/master/build.zig#L8

**Comment by Luukdegram** [comment]
Since #11461 we provide debug information for the Wasm target. This was not yet implemented in 0.9.1, hence the binary size increase. As r00ster91 mentioned, if you do not want to include debug information, you'll either need to provide the `--strip` flag or set `strip` to true in your build.zig

**Comment by garyemerson** [comment]
Ah that makes sense. Those changes did the trick and the wasm output is now back to the smaller size. Thanks!

**Comment by williamstein** [comment]
On a related note, if you're mainly using `zig cc` to cross compile for Wasm, use the `-s` (and related options to llvm), as explained here: https://stackoverflow.com/questions/6085491/gcc-vs-clang-symbol-stripping
