### ISSUE TITLE
@atomicRmw - support bool and non-power-of-2 int types

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1220]
bool and non-power-of-2 int types are still power of 2 int types under the hood. We can do secret pointer casts on them before and after calling llvm's atomicrmw instruction (these pointer casts will be no-ops in machine code).

There are TODO comments in zig std lib and in the language reference once this is complete.

Same thing goes for `@cmpxchgWeak` and `@cmpxchgStrong`.

**Comment by BarabasGitHub** [comment]
How will that work when you have multiple of them in a struct?

**Comment by andrewrk** [comment]
Can you elaborate? It will work the same way that multiple non-power-of-2 int types work in a non-packed struct.
