### ISSUE TITLE
Install-relink error with recent Nix+CMake

### ISSUE THREAD

**Issue by zseri** [ziglang/zig#12218]
### Zig Version

a08b0fa706f79a506b219d59a0b58a6d5761dcd7

### Steps to Reproduce

This might be Nix (nix-2.10.0pre`20220722_2805439`) or CMake (3.23.1)-related, but I have no idea what exactly broke...
Checkout https://github.com/zseri/nixos-configs/tree/83bb0d9f949816016e9ff47e16c56157947f5ab2 (at the specified commit),
then try to build (requires a nix version with flake support, although it might be possible to get the same result via `flake-compat` adapter, or via a direct build in a similar environment)
```
nix build -v -L -j4 --cores 4 .#nixosConfigurations.orca.pkgs.zig
```

The derivation used is https://github.com/zseri/nixos-configs/blob/83bb0d9f949816016e9ff47e16c56157947f5ab2/pkgs/zig/default.nix (it patches the linker command line to additionally always include `-lz`, because otherwise linking fails, but the error doesn't seem to be related to that)

### Expected Behavior

Build succeeds.

### Actual Behavior

```
zig> installing
zig> install flags: SHELL=/nix/store/qm2lv1gpbyn0rsfai40cbvj3h4gz69yc-bash-5.1-p16/bin/bash install
zig> Consolidate compiler generated dependencies of target embedded_softfloat
zig> [ 81%] Built target embedded_softfloat
zig> Consolidate compiler generated dependencies of target zigcpp
zig> [ 85%] Built target zigcpp
zig> Consolidate compiler generated dependencies of target opt_c_util
zig> [ 86%] Built target opt_c_util
zig> Consolidate compiler generated dependencies of target zigstage1
zig> [ 97%] Built target zigstage1
zig> Consolidate compiler generated dependencies of target zig0
zig> [ 98%] Built target zig0
zig> Consolidate compiler generated dependencies of target zig
zig> [100%] Built target zig
zig> Install the project...
zig> -- Install configuration: "Release"
zig> -- Installing: /nix/store/6mnp8jkz2d2kcsamdfvhakjynirbgwfn-zig-0.10.0/bin/zig
zig> CMake Error at cmake_install.cmake:55 (file):
zig>   file RPATH_CHANGE could not write new RPATH:
zig>   to the file:
zig>     /nix/store/6mnp8jkz2d2kcsamdfvhakjynirbgwfn-zig-0.10.0/bin/zig
zig>   The current RUNPATH is:
zig>     /nix/store/6mnp8jkz2d2kcsamdfvhakjynirbgwfn-zig-0.10.0/lib64:/nix/store/6mnp8jkz2d2kcsamdfvhakjynirbgwfn-zig-0.10.0/lib:/nix/store/w25nadr7247krvg5nbxr9slnhq76dakc-zlib-1.2.12/lib:/nix/store/1lvp72nkrrhm79007ny0v2hcywbbmv3r-llvm-14.0.6-lib/lib:/nix/store/mhhlymrg2m70r8h94cwhv2d7a0c8l7g6-glibc-2.34-210/lib
zig>   which does not contain:
zig>     /lib:
zig>   as was expected.
zig> 
zig> make: *** [Makefile:100: install] Error 1
error: builder for '/nix/store/0v2dzb6rhbw4wwxi1jwip6wrpnsxf5jb-zig-0.10.0.drv' failed with exit code 2
```

**Comment by vesim987** [comment]
@zseri you can workaround both issues with:
`cmakeFlags = [ "-DZIG_STATIC_ZLIB=ON" "-DCMAKE_SKIP_BUILD_RPATH=ON" ];`
it looks like other packages in nix(https://github.com/NixOS/nixpkgs/search?q=%22-DCMAKE_SKIP_BUILD_RPATH%22&type=) are using `CMAKE_SKIP_BUILD_RPATH`, so i don't think that the issue is on zig side.
