### ISSUE TITLE
stage2 array access performance (boundchecks related?)

### ISSUE THREAD

**Issue by xxxbxxx** [ziglang/zig#12215]
### Zig Version

0.10.0-dev.3286+9ec3f611c

### Steps to Reproduce

```zig
const std = @import("std");

test {
    const array = try std.testing.allocator.create([10][10 * 10 * 10 * 10]u64);
    defer std.testing.allocator.destroy(array);
    array[1][1] = 0;

    var a: u32 = 1;
    var b: u32 = 1;

    var i: u32 = 0;
    while (i < 12345678) : (i += 1) {
        array[a][b] += array[a][b] * i;
    }

    try std.testing.expect(array[a][b] == 0);
}
```

### Expected Behavior

test passes in <1s
(and does with stage 1)

### Actual Behavior

test passes in > 20s (stage 2)

in _debug_ and _releasesafe_ modes.
seems to work fine in _releasefast_. (there's no memcpy in the llvmir)

**Comment by xxxbxxx** [comment]
Most of the time is spent in memcpy.

looks like `array[a][b]` first loads `array[a]` in a temp copy and then does [b]. array[a] is huge!

portion of the air:
```
          %156 = ptr_elem_ptr(%61, %145!)
          %158 = load([10000]u64, %156!)  // <<<<<
          %159 = load(u32, %87)
          %160 = intcast(usize, %159!)
          %162 = cmp_lt(%160, %161)
          %167!= block(void, {
            %168!= cond_br(%162!, {
              %161!
              %169!= br(%167, @Zir.Inst.Ref.void_value)
            }, {
              %166!= call(%123, [%160, %161!])
            })
          })
          %170 = array_elem_val(%158!, %160!)
          %171 = load(u32, %93)
          %172 = intcast(u64, %171!)
          %174 = mul_with_overflow(%170!, %172!)
          %175 = struct_field_val(%174, 1)
```
```

**Comment by IntegratedQuantum** [comment]
To everyone who is looking for a temporary solution:
`array[a][b]` → `(&array[a])[b]`
`strct.array[i]` → `(&strct.array)[i]`

This solves the performance issue because it seems to be storing a pointer to the array instead of the whole array:
`%5 = alloca [10000 x i64]` changed to `%5 = alloca ptr` in the llvm ir

**Comment by topolarity** [comment]
Reduction:

```zig
test {
  var array: [10][10_000]u64 = undefined;
  var a: usize = 1;
  _ = (array[a][a] == 0);
}
```

The LLVM IR generated for this by stage2 is:
```llvm
define internal fastcc i16 @test3.test_0() unnamed_addr #0 {
Entry:
  %0 = alloca i64, align 8
  %1 = alloca [10 x [10000 x i64]], align 8
  store i64 1, ptr %0, align 8
  %2 = load i64, ptr %0, align 8
  %3 = getelementptr inbounds [10 x [10000 x i64]], ptr %1, i32 0, i64 %2
  %4 = load i64, ptr %0, align 8
  %5 = getelementptr inbounds [10000 x i64], ptr %3, i32 0, i64 %4
  %6 = load i64, ptr %5, align 8
  ret i16 0
}
```

This is a missing Debug-mode optimization versus stage1. There is an intermediate load of the inner array element, which is very slow.

In Release mode, LLVM has no problem doing the optimization for us. In `-O ReleaseFast` the intermediate load is gone and the test passes in <1s, just like in stage1.

**Comment by topolarity** [comment]
The problem boils down to this optimization in `src/codegen/llvm.zig` (fn airLoad):
```zig
// It would be valid to fall back to the code below here that simply calls
// load(). However, as an optimization, we want to avoid unnecessary copies
// of isByRef=true types. Here, we scan forward in the current block,
// looking to see if this load dies before any side effects occur.
// In such case, we can safely return the operand without making a copy.
for (body[body_i..]) |body_inst| {
    switch (self.liveness.categorizeOperand(self.air, body_inst, inst)) {
        .none => continue,
        .write, .noret, .complex => break :elide,
        .tomb => return try self.resolveInst(ty_op.operand),
    }
} else unreachable;
```

The bounds check inserts a `block` between the load of the inner array and its last usage. Liveness conservatively decides this block has side effects without analyzing it, and the optimization is not applied.

**Comment by Vexu** [comment]
Note that the issue starts in AstGen where array and field access forces the lhs to be loaded even though the operation could just as well be done on a pointer.
