### ISSUE TITLE
stage2: can't override log with a declaration from `usingnamespace`

### ISSUE THREAD

**Issue by leecannon** [ziglang/zig#12238]
### Zig Version

0.10.0-dev.3300+7c13bdb1c

### Steps to Reproduce

```zig
const std = @import("std");

pub fn main() void {
    std.log.info("not printed", .{});
}

usingnamespace log_impl;

const log_impl = struct {
    pub fn log(
        comptime level: std.log.Level,
        comptime scope: @TypeOf(.EnumLiteral),
        comptime format: []const u8,
        args: anytype,
    ) void {
        _ = level;
        _ = scope;
        _ = format;
        _ = args;
        std.debug.print("log is overriden\n", .{});
    }
};
```
Run the code with both stage1 and stage2.

### Expected Behavior

```
$ zig_stage1 run main.zig
log is overriden
$ zig_stage2 run main.zig
log is overriden
```

### Actual Behavior

```
$ zig_stage1 run code.zig
log is overriden
$ zig_stage2 run code.zig
info: not printed
```

This `@hasDecl` is false in stage2 but true in stage 1.
https://github.com/ziglang/zig/blob/cff5d9c805aa3433cc2562c3cb29bd3201817214/lib/std/log.zig#L136

To test this more I changed the code in `std.log.log` to be just:
```zig
root.log(message_level, scope, format, args);
```
Which gives a _struct 'main.main' has no has no member named 'log'_ in stage 2 but works fine in stage 1, so it doesn't seem to be `@hasDecl` specifically.

**Comment by leecannon** [comment]
While this example is `std.log` I have the same issue with a BYOS package that is intended to be `usingnamespace`ed in the root file to provide an operating specific entry point, panic implementation, BYOS stuff, etc.

**Comment by zigazeljko** [comment]
Did you try using `pub usingnamespace`?

**Comment by yujiri8** [comment]
I don't get this. Shouldn't `usingnamespace` put your `log` implementation into the global namespace, to be called as just `log`, but you're calling std.log, so why would it override that?

**Comment by leecannon** [comment]
@zigazeljko looks like that's it
Is this an intended change with `usingnamespace`? In stage 1 it was not required to mark it as pub for the symbol to be pub, although I do prefer it.

**Comment by Vexu** [comment]
IMO stage2 behaves correctly here and it's stage1 with a bug.

**Comment by leecannon** [comment]
@yujiri8 you can override the logging functionality https://github.com/ziglang/zig/blob/cff5d9c805aa3433cc2562c3cb29bd3201817214/lib/std/log.zig#L24-L48

**Comment by leecannon** [comment]
I'm goign to close this as resolved as I do prefer stage2's functionality and I thought pub was necessary on `usingnamespace` until a few months ago anyway.
