### ISSUE TITLE
Compilation error with ordinary comment before test code.

### ISSUE THREAD

**Issue by mass10** [ziglang/zig#12233]
### Zig Version

0.10.0-dev.2859+0101a5f75

### Steps to Reproduce

```Zig
const std = @import("std");

/// safe
pub fn main() anyerror!void {
    // safe
    std.log.info("Ok.", .{});
}

/// THIS COMMENT CAUSES COMPILATION ERROR! > error: invalid token: 'test'
test "basic test" {
    try std.testing.expectEqual(10, 3 + 7);
}
```

### Expected Behavior

No compilation errors.

### Actual Behavior

Compilation error occured.
> error: invalid token: 'test'

So, `//` causes no errors.

```zig
// NO ERRORS.
test "basic test" {
    try std.testing.expectEqual(10, 3 + 7);
}
```

**Comment by Vexu** [comment]
`///` is a [doc comment](https://ziglang.org/documentation/master/#Doc-comments) and they are only allowed in certain places. 

Stage2 seems to be missing this error completely.

**Comment by mass10** [comment]
> /// is a doc comment

Oh! I see.

Thank you!
