### ISSUE TITLE
Syntax highlighting for KDE

### ISSUE THREAD

**Issue by eduardosm** [ziglang/zig#1224]
I have created a syntax highlighting definition for KDE. It is available here:
https://gist.github.com/eduardosm/4d0cbcc911c831b312a507b39970b036
It is probably far from perfect, but it is a start.

**Comment by eduardosm** [comment]
There are some missing features. For example, I just realized that it doesn't support multiline strings (`\\...`). I probably have missed some keywords tool. Maybe you can place it in a repository (like you did Vim or Emacs), and I'll make pulls requests with any improvements I make.

In order to test it, it has to be placed in `/usr/share/katepart5/syntax/` or `$HOME/.local/share/org.kde.syntax-highlighting/syntax/`. Then, Zig sources should be detected automatically by editors that uses KDE's text editor part.

**Comment by andrewrk** [comment]
I have created https://github.com/ziglang/kde-syntax-highlighting and given you collaborator access. Thanks for the contribution!
