### ISSUE TITLE
change the default floating point mode to strict

### ISSUE THREAD

**Issue by BarabasGitHub** [ziglang/zig#1227]
I saw in the [documentation](https://ziglang.org/documentation/master/#Floating-Point-Operations) that Zig currently uses the 'optimized' mode as a default for floating point calculations. I think this is a bad decision, because it will do unexpected things to your code. I think it'd be better if people explicitly have to ask for sloppy floating point math and keep the default at doing exactly what the code says it should do.

Floating point is confusing enough already as is, I think it's not helpful to make it worse by enabling optimizations that will reorder operations, fail to propagate infinity & nan etc. I also don't think it's worth it in the general case for the improved performance. If it really is in your hot path you can always enable the optimizations, but otherwise I think it violates the principle of least surprise.

**Comment by karlguy** [comment]
I agree with this. Correctness is more important than performance in floats. In C, -ffast-math is considered bad practice, and it should be the same in Zig.

Although the real solution is to just stay away from floats completely if possible.

**Comment by andrewrk** [comment]
Here's one data point in favor of strict by default: https://twitter.com/rygorous/status/1032074614619267073
Fabian Giesen says:
> I do use it, but explicitly choose whether I want it or not per file; I would be all over good facilities for turning it on/off in a more granular way than on the command line for full translation units; I think on by default is a bad idea.
This is the performance expert at RAD.

**Comment by numsim1415** [comment]
As [Fabian Giesen](https://twitter.com/rygorous/status/1032074614619267073) points out,  different floating point behaviour on a per-scope basis is useful.
Note, however, that `-ffast-math` can be too much. Instead, using  `-freciprocal-math -fno-signed-zeros -fno-trapping-math -fassociative-math` is often reasonable, in my opinion. 
Are there plans to enable the use of these settings?

See [gcc/Optimize-Options](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html)
