### ISSUE TITLE
Crash on windows wildcard

### ISSUE THREAD

**Issue by BarabasGitHub** [ziglang/zig#1228]
I build zig from master and invoked it as:
`zig test *.zig`
in an attempt to make it test the few .zig files I have in the folder, but it crashed and gave me this _unreachable: E:\Zig\src\os.cpp:os_fetch_file_path:632_

**Comment by andrewrk** [comment]
c59ce046a0ad468 fixed this (accidentally tagged the wrong issue in the commit message)
