### ISSUE TITLE
std.fmt: add `#` specifier to print raw bytes of the value (hex)

### ISSUE THREAD

**Issue by Vexu** [ziglang/zig#12313]
This was accepted as part of #1358 but never implemented. I'm opening this as a new proposal since it is of questionable usefulness:
> (NOTE: do we need this? how often is it used?)

**Comment by InKryption** [comment]
I don't think it's necessary, if one wants they can use `std.mem.asBytes` -> `std.fmt.fmtSliceHexLower`/`fmtSliceHexUpper`.

**Comment by matu3ba** [comment]
I do agree with @InKryption that it is semantically not necessary and at first would be simpler to do without another flag to `std.fmt`
- 1. However, it is poorly documented how to get the in-memory representation
- 2. Printing the raw bytes is common on analyzing padding + alignment issues on overlapping types besides bit logic things like int, float, deterministic bigint stuff in buffers etc.
- 3. If I want 5 values next to another like a csv table over time (say with file,line number + iteration), then writing those out will be annoying. How useful or common this is, would be the other question.
