### ISSUE TITLE
Unable to override alignment of packed struct

### ISSUE THREAD

**Issue by willruggiano** [ziglang/zig#12321]
### Zig Version

0.10.0

### Steps to Reproduce

```zig
test "alignOf" {
    packed struct {
        a: bool align(@alignOf(u32)),
    };
}
```

### Expected Behavior

I expect this to compile, but then again I am new to Zig and trying to make changes to zig-(wayland|wlroots) to get them working against master.

### Actual Behavior

```
/path/to/test.zig:19:23: error: unable to override alignment of packed struct fields
        a: bool align(@alignOf(u32)),
                      ^~~~~~~~~~~~~
```

**Comment by willruggiano** [comment]
I am on NixOS so 0.10.0 refers to [447a4cc115f5d105d49fcb3e970082b89e5a46dd](https://github.com/ziglang/zig/commit/447a4cc115f5d105d49fcb3e970082b89e5a46dd)

**Comment by ifreund** [comment]
This is intentional, see 6249a24e81b9b3df3d5ca99b57f22470b9ac486c.

zig-wayland and zig-wlroots are not compatible with zig's master branch, only 0.9.1. The will be updated to 0.10.0 when 0.10.0 is released.
