### ISSUE TITLE
Disallow runtime parameters in functions returning comptime-only types

### ISSUE THREAD

**Issue by InKryption** [ziglang/zig#12333]
### Steps to Reproduce

```
fn F(val: anytype) type {
    _ = val;
    return struct {};
}

test {
    _ = F(void{});
    _ = F(@as(i32, 0));
    // Compile error:
    // var i: i32 = 0;
    // _ = F(i);
}
```

### Expected Behavior

There ought to be a compile error for declaring a non-`comptime` parameter in a function returning a `comptime`-only type, such as `type`, `comptime_int`, or `comptime_float`, being that there is no way to compute any of them using runtime values. Allowing this only enables useless permutations of compile-able code.

### Actual Behavior

Compilation succeeds, unless you uncomment the last two lines of the test.

**Comment by rohlem** [comment]
I agree with the general idea of this proposal, in that a function returning a comptime-only type like `type` would be clearer expressed with exclusively comptime arguments.
However, I think conditional return types and comptime-logic / conditional compilation blur the line when this is applicable. Contrived example:

```zig
fn orelse_undefined(comptime T: type, value: ?T) T {
  return value orelse undefined;
}
// also consider (assume same body):
fn orelse_undefined2(comptime flag: bool, value: ?(if(flag) i32 else type)) (if(flag) i32 else type) {}
const X = if(target_os == .windows) i32 else type;
fn orelse_undefined3(value: ?X) X {}
```

IMO, `orelse_undefined(i32, 5)` and `orelse_undefined(type, i32)` are both valid usages, where the former may benefit from allowing `value` to be a runtime value.
Having to duplicate the function, just so the type-returning variant explicitly declares all its parameters as `comptime` seems non-helpful to me.

I think we may have to limit this diagnostic to provably-comptime-only types, such as builtin `type`, `comptime_int` etc. - at which point it would still improve readability.
At that point the question becomes whether we want a hard compile error for a style improvement suggestion.
(Didn't mean to sound overly negative towards this, just needs to be decided/clarified.)

**Comment by Vexu** [comment]
This error like the `parameter of type 'T' must be declared comptime` (which doesn't appear to work in stage2 for whatever reason) should not apply to dependent types #1383.

**Comment by rohlem** [comment]
@Vexu I'm not sure about the nomenclature, is `const X = if(target_os == .windows) i32 else type;` from my example considered a dependent type?

What about types declared in other packages, like `@import("mypackage").X`, where `mypackage` may be selected by `build.zig` according to build parameters?

**Comment by Vexu** [comment]
I don't know if the names for these things are decided but what I meant was that it wouldn't apply if the return type depended on a generic parameter.

`const X = if(target_os == .windows) i32 else type;` would trigger the error if used as the return type.

Similar thing already happens if you do:
```zig
const X = if(target_os == .windows) i32 else anyopaque;
fn foo(_: X) void {}
```
On windows this will compile and on any other target it will give an error about opaque parameters not being allowed.
