### ISSUE TITLE
Missing compiler error on signed integer division (stage2)

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#12339]
### Zig Version

0.10.0-dev.3445+18440cb23

### Steps to Reproduce

Run the following code with `zig run test.zig -fno-stage1`:
```
const std = @import("std");

pub fn main() void {
    var v1: i32 = -49;
    var v2: i32 = v1/2;
    std.log.info("Result: {}", .{v2});
}
```

### Expected Behavior

I expect a compiler error (like in stage 1):
```
./test.zig:5:21: error: division with 'i32' and 'comptime_int': signed integers must use @divTrunc, @divFloor, or @divExact
    var v2: i32 = v1/2;
                    ^
```

### Actual Behavior

In stage2 it compiles and prints
```
info: Result: -24
```
So apparently it automatically uses `@divTrunc` instead of giving a compiler error.

**Comment by yujiri8** [comment]
This seems like desirable behavior to me? I believe this is what every other language does, and not being allowed to use `/` with signed integers sounds cumbersome.

**Comment by Vexu** [comment]
> A variation of this remains undetected in stage2:

Handled in #13075
