### ISSUE TITLE
`#ifdef zig` when using `@cImport`

### ISSUE THREAD

**Issue by thechampagne** [ziglang/zig#12382]
like `#ifdef __cplusplus` e.g `#ifdef __zig`.
```c
// header.h
#ifdef __zig
#define FUNC_NAME getNumber // zig naming conventions
#else
#define FUNC_NAME get_number
#endif

int FUNC_NAME()
{
    return 20;
}
```

```zig
// main.zig
const std = @import("std");
const c = @cImport(@cInclude("header.h"));

pub fn main() !void {
    std.debug.print("{d}\n", .{c.getNumber()});
}
```

This is a simple use case.

**Comment by Vexu** [comment]
This is already possible with `@cDefine`:
```zig
// main.zig
const std = @import("std");
const c = @cImport({
    @cDefine("__zig", {});
    @cInclude("a.h");
});

pub fn main() !void {
    std.debug.print("{d}\n", .{c.getNumber()});
}
```

**Comment by thechampagne** [comment]
It should exist by default.

**Comment by nektro** [comment]
your C code should be using the C style guide, not Zig's

**Comment by thechampagne** [comment]
What part of "That c code will be imported in zig" do you not understand?

**Comment by tauoverpi** [comment]
I don't think C libraries should assume zig as a consumer of them and provide separate definitions. It doesn't matter if it's imported by zig or not.

Is there a stronger usecase for this than renaming?

**Comment by ominitay** [comment]
I feel that the use of `translate-c` should be transparent to C libraries. There isn't any reason I can see for this to exist.

**Comment by SanderMertens** [comment]
One potential reason for this to exist is that target headers provided by zig (e.g. https://github.com/ziglang/zig/blob/0.10.1/lib/libc/include/any-windows-any/winsock2.h) are in all lowercase, whereas the native headers use uppercase characters (e.g. `WinSock2.h`).

Some compilers/warning settings will throw a warning when you include a file with mismatching case, which in this case prevents you from writing warning-free portable code. This could have been addressed with a macro:

```c
#ifdef __zig
#include "winsock2.h"
#else
#include "WinSock2.h"
#endif
```

**Comment by booniepepper** [comment]
My two cents:

1. If you sign up for `-Wall` you are signing up to see and address issues like this
2. The solution should not be "detect the compiler" because then every C code out there needs yet one more flag to think and reason about. The solution should be that Zig should not change the casing of file names of the libcs that it bundles, and that will prevent everyone having a problem to mitigate.
