### ISSUE TITLE
unable to build compiler_rt: AccessDenied when running behavior tests

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#12408]
Zig Version: 933436dc52b9be0a3e5d81b014fba6df2124fe20

### Steps to reproduce:
1. download windows dev kit
2. `dev-kit\zig.exe build -p stage1 -Dstatic-llvm -Dstage1 --search-prefix dev-kit --zig-lib-dir lib`
3. `stage1\bin\zig.exe build test-behavior`

### Expected output:

All tests passed

### Actual output:

```
error: unable to build compiler_rt: AccessDenied
```

### Remarks

This is a blocker for #12381 / #12380

**Comment by hdorio** [comment]
This is the output I get
```
# dev-kit 3524 / Windows 8
$ ../dev-kit/bin/zig.exe build --prefix stage1 -Dstatic-llvm -Dstage1 --search-prefix ../dev-kit --zig-lib-dir lib
$ ./stage1/bin/zig.exe build test-behavior


error: unable to build compiler_rt: AccessDenied
error: test...
error: The following command exited with error code 1:
C:\work\zig\stage1\bin\zig.exe test -fno-stage1 -fno-LLVM C:\work\zig\test\behavior.zig --test-name-prefix behavior-aarch64-macos-none-Debug--multi-stage2_aarch64  --cache-dir C:\work\zig\zig-cache --global-cache-dir C:\Users\user\AppData\Local\zig --name test -fno-single-threaded -target aarch64-macos-none -mcpu generic --test-no-exec -I C:\work\zig\test --zig-lib-dir C:\work\zig\lib --enable-cache
error: the following build command failed with exit code 1:
C:\work\zig\zig-cache\o\45a532645d182ff7f7f94c3512bb340f\build.exe C:\work\zig\stage1\bin\zig.exe C:\work\zig C:\work\zig\zig-cache C:\Users\user\AppData\Local\zig test-behavior
```

Is it intended to run MacOS tests (`... --test-name-prefix behavior-aarch64-macos...`) from Windows?

Applying the following patch gets rid of the error `error: unable to build compiler_rt: AccessDenied`

```diff
diff --git a/test/tests.zig b/test/tests.zig
index dcc891f87..533c683d2 100644
--- a/test/tests.zig
+++ b/test/tests.zig
@@ -92,22 +92,6 @@ const test_targets = blk: {
             }) catch unreachable,
             .backend = .stage2_arm,
         },
-        .{
-            .target = .{
-                .cpu_arch = .aarch64,
-                .os_tag = .macos,
-                .abi = .none,
-            },
-            .backend = .stage2_aarch64,
-        },
-        .{
-            .target = .{
-                .cpu_arch = .x86_64,
-                .os_tag = .macos,
-                .abi = .none,
-            },
-            .backend = .stage2_x86_64,
-        },

         .{
             .target = .{
```

I'm not suggesting to apply the patch, it's just that it seems we should not try to execute these tests. Is there a mechanism to skip these tests on Windows?

**Comment by kubkon** [comment]
Yes it is. We cross-compile the binary without executing it unless an execution environment is available (native or darling on Linux for macOS). If you scroll down in the `test/tests.zig` you will see we have more macOS tests than just these two.

**Comment by hdorio** [comment]
> Yes it is. We cross-compile the binary without executing it unless an execution environment is available (native or darling on Linux for macOS). If you scroll down in the `test/tests.zig` you will see we have more macOS tests than just these two.

Thanks !
