### ISSUE TITLE
std: export `std.auto_hash`

### ISSUE THREAD

**Issue by LordMZTE** [ziglang/zig#12409]
This error message https://github.com/ziglang/zig/blob/master/lib/std/hash/auto_hash.zig#L196-L197 references the function `std.auto_hash.hash`, which isn't actually accessible, as `std` doesn't export the `auto_hash` module anywhere.

`zig version`: `0.10.0-dev.3480+396eb730e`

**Comment by Vexu** [comment]
The error message is incorrect, it should mention `std.hash.autoHash` and `std.hash.autoHashStrat`.
