### ISSUE TITLE
stage2: list of declarations returned from `@typeInfo` wrong when using `usingnamespace`

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#12403]
### Zig Version

0.10.0-dev.3494+50b36e84f

### Steps to Reproduce

```zig
const A = struct {
    const x = 5;
    const y = 34;
};

const B = struct {
    pub usingnamespace A;
    const z = 56;
};

const std = @import("std");

test {
    try std.testing.expectEqual(3, comptime std.meta.declarations(B).len);
}
```

### Expected Behavior

All tests pass

### Actual Behavior

```
Test [1/1] test_0... expected 3, found 2
```

decls returned are `usingnamespace_0`, `z` instead of `x`, `y`, `z`

**Comment by dweiller** [comment]
Some additional details I found:
  - the inplace of the decls of the included struct, the result of `@typeInfo` (and hence `std.meta.declarations`) has decls name "usingnamespace_N" where "N" is an index (you get one for each included namespace)
  - you can access/check the by doing `@typeInfo(@field(B, "usingnamespace_0"))`
  - there are clobbering issues if `B` were to contain an explicit field called "usingnamespace_0" in addition however, e.g.  I had `@hasDecl` cause an error saying there are ambiguous references.
