### ISSUE TITLE
zig fails for all existing C and C++ projects, which use the autotools build system 

### ISSUE THREAD

**Issue by winspool** [ziglang/zig#12413]
### Zig Version

0.10.0-dev.3475+b3d463c9e

### Steps to Reproduce

~~~
cd autotools_project
mkdir test_zig
cd test_zig
CC="zig" CFLAGS="c++ -target x86_64-linux-musl" ../configure
~~~

Failure output:
~~~
...
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... configure: error: in `/somewhere/on/disc/test_zig':
configure: error: cannot compute suffix of executables: cannot compile and link
See `config.log' for more details
Command exited with non-zero status 1
~~~

zig is called with this command line:
~~~
configure:4286: checking for suffix of executables
configure:4293: zig -o conftest c++ -target x86_64-linux-musl       conftest.c  >&5
info: Usage: zig [command] [options]
... (deleted)
~~~

and zig fail here with "unknown command: -o".

the same bug exists, when using 
~~~
CC="zig" CFLAGS="cc -target x86_64-linux-musl" ../configure
~~~

### Expected Behavior

zig should accept options in any order,
when using zig as a C or C++ Compiler

### Actual Behavior

zig fail with "unknown command: -o"
and configure exits

**Comment by judofyr** [comment]
`CC="zig cc"` is the way to use Zig as a C/C++ compiler.

**Comment by winspool** [comment]
> `CC="zig cc"` is the way to use Zig as a C/C++ compiler. 


This does not work everywhere.

I had issues, when the value in CC 
was not found in the path, 
but i can't  remember the projects.

It was more than 2 years ago, when i detected that while using "gcc  -g".

Regards, 
Detlef

**Comment by nektro** [comment]
then that's a bug in the other software, see https://github.com/ziglang/zig/issues/7342 for an example
