### ISSUE TITLE
compiling the behavior tests on windows with the C backend results in lld-link: error: undefined symbol: WinMain

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#12415]
Related issues:  #12381 #12380

The CI is failing with:

```
lld-link: error: undefined symbol: WinMain
>>> referenced by mingw32.lib(crt0_c.obj):(main)
error: the following command failed with 'InvalidName':
C:\Users\VssAdministrator\AppData\Local\zig\o\16e45379bd58d3a148ce664e2e02032b\test.exe
error: the following test command failed with exit code 1:
D:\a\1\s\build\dist\bin\zig.exe run -lc D:\a\1\s\zig-cache\o\a7d61f37c2d31a673bd2119a5791c079\test.c
error: test...
error: The following command exited with error code 1:
D:\a\1\s\build\dist\bin\zig.exe test -fno-stage1 -fno-LLVM -ofmt=c D:\a\1\s\test\behavior.zig -lc --test-name-prefix behavior-native-Debug-c-multi-stage2_c  --cache-dir D:\a\1\s\zig-cache --global-cache-dir C:\Users\VssAdministrator\AppData\Local\zig --name test -fno-single-threaded -I D:\a\1\s\test --zig-lib-dir D:\a\1\s\lib --enable-cache 
```

However, the command completes successfully for me locally. So I'm going to disable the test until we figure out wtf is going on.

**Comment by hdorio** [comment]
> However, the command completes successfully for me locally.

Removing `.\zig-cache\` and `~\AppData\Local\zig\` before compiling helps to display the error `undefined symbol: WinMain` for me.

---

It seems to me that there are 2 issues here.
The first is that `zig.exe test -fno-stage1` gives an error message  `undefined symbol: WinMain`
The second is that `zig build toolchain` calls  `zig.exe test -fno-stage1`.

I would like to introduce 4 definitions.

#### 2 errors
 - sadly_stage2
```
thread 3516 panic: sadly stage2 is omitted from this build to save memory on the CI server
Unable to dump stack trace: debug info stripped
```
 - undefined_symbol_WinMain
```
LLD Link... lld-link: error: undefined symbol: WinMain
>>> referenced by mingw32.lib(crt0_c.obj):(main)
error: LLDReportedFailure
error: the following test command failed with exit code 1:
C:\work\zig\build\dist\bin\zig.exe run -lc C:\work\zig\zig-cache\o\714b7a21ae6705cc7be0e45629b581b7\test.c
test...The following command exited with error code 1:
C:\work\zig\build\dist\bin\zig.exe test -fno-stage1 -fno-LLVM -ofmt=c C:\work\zig\test\behavior.zig -lc --test-name-prefix behavior-native-Debug-c-multi-stage2_c  --cache-dir C:\work\zig\zig-cache --global-cache-dir C:\Users\user\AppData\Local\zig --name test -fno-single-threaded -I C:\work\zig\test
 --zig-lib-dir C:\work\zig\lib --enable-cache
error: the following build command failed with exit code 1:
C:\work\zig\zig-cache\o\565fd5e52b576757243df16b25004fe3\build.exe C:\work\zig\build\dist\bin\zig.exe C:\work\zig C:\work\zig\zig-cache C:\Users\user\AppData\Local\zig test-toolchain -Dskip-non-native -Dskip-stage2-tests
```
#### 2 commands
 - build_toolchain
```
# & "$ZIGINSTALLDIR\bin\zig.exe" build test-toolchain -Dskip-non-native -Dskip-stage2-tests
```
 - add_pkg_tests_sub_command
```
& "$ZIGINSTALLDIR\bin\zig.exe" test -fno-stage1 -fno-LLVM -ofmt=c C:\work\zig\test\behavior.zig -lc --test-name-prefix behavior-native-Debug-c-multi-stage2_c  --cache-dir C:\work\zig\zig-cache --global-cache-dir C:\Users\user\AppData\Local\zig --name test -fno-single-threaded -I C:\work\zig\test
```

The command `build_toolchain` triggers `add_pkg_tests_sub_command`.
The command `add_pkg_tests_sub_command` triggers `sadly_stage2` or `undefined_symbol_WinMain`.

Executing the `add_pkg_tests_sub_command` on previous commits I found out that

`sadly_stage2` was done before                02902cc (2022-02-17)
`sadly_stage2` became `undefined_symbol_WinMain` from 2f9264d (2022-03-23)

But as a reminder, on 02902cc the `build_toolchain` command was executing on the CI pipeline without any error (no `sadly_stage2`).
Which begs the question: from which commit did `build_toolchain` begin to trigger the `add_pkg_tests_sub_command`?

I found out that 496eb69 (2022-04-21) is the first commit to trigger `add_pkg_tests_sub_command` on Windows.

So 2f9264d introduced the first issue.
And 496eb69 introduced the second issue.

---

For 2f9264d, it looks like `src/Compilation.zig` is the issue.
On Windows the `add_pkg_tests_sub_command` (`zig test -fno-stage1`) used to not use stage1 (`use_stage1 == false`) for the first call to update() and flush() from `src/Compilation.zig`.

**Comment by andrewrk** [comment]
Fixed in master branch; CI coverage enabled in 1310ef75777209f061bfd61473db75911538b5ff.
