### ISSUE TITLE
When running in a CI environment, have the build system warn when the target is underspecified

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#12424]
CI environments rarely have documented or stable choice of CPUs; this ends up causing people's build artifacts to (from their perspective) randomly change over time. e.g. https://github.com/coilhq/tigerbeetle-node/issues/13

I propose that when in a CI environment, we warn when the target is underspecified e.g.
  - uses native CPU features
  - doesn't specify minimum kernel version
  - doesn't specify minimum glibc version

---

## Implementation:

I think almost every CI platform sets the env var `CI=true`:
- https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
- https://docs.drone.io/pipeline/environment/reference/ci/
- https://circleci.com/docs/env-vars#built-in-environment-variables
- https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
- https://docs.semaphoreci.com/ci-cd-environment/environment-variables/#semaphore-related
- https://developer.apple.com/documentation/xcode/environment-variable-reference
- jenkins only added support relatively recently: https://github.com/jenkinsci/jenkins/pull/5370
- https://docs.travis-ci.com/user/environment-variables/#default-environment-variables

Which is all the CI systems I've used. @ifreund notes that it is currently missing from sourcehut.

But I think that should be sufficient to define "in a CI environment"

**Comment by nektro** [comment]
exhaustively checking requires a list akin to https://github.com/nektro/zig-ci-detect/blob/master/src/lib.zig

if folks are in a CI environment run into the issue they should add `-Dtarget` and family to their build invocation

**Comment by daurnimator** [comment]
> exhaustively checking requires a list akin to https://github.com/nektro/zig-ci-detect/blob/master/src/lib.zig

We don't need to know *which* CI environment we're in. As my post enumerates, almost all CI systems set the env var `CI=true`, we can use that.

**Comment by nektro** [comment]
the user is always going to know which CI environment they're in
