### ISSUE TITLE
@IntType silently wraps around on number of bits

### ISSUE THREAD

**Issue by BarabasGitHub** [ziglang/zig#1242]
Basically currently this is the case:
``` 
@IntType(false, @maxValue(u64)).bitcount == @maxValue(u32)
@IntType(false, @maxValue(u32) + 1).bit_count == 0
````

I'm guessing there should be a limit somewhere.

**Comment by andrewrk** [comment]
It looks like the current size of the parameter is u8: https://ziglang.org/documentation/master/#IntType

I think that's not actually correct though. I believe it should be changed to u32, which is the size of the parameter that llvm accepts for the bit count.

**Comment by andrewrk** [comment]
Turns out it was treated as a usize according to zig, but then the compiler internally stored it as a u32, which caused the wrapping. Pushing a fix shortly.
