### ISSUE TITLE
doc: name of anonymous struct is strange

### ISSUE THREAD

**Issue by bronze1man** [ziglang/zig#1243]
Please document how the name of anonymous struct is get.

```
const std = @import("std");

pub fn main() !void {
    var stdout_file = try std.io.getStdOut();
    std.debug.warn("{}\n",@typeName(struct{}) );
}
```
Above code return `main()`

The document may be come from https://github.com/ziglang/zig/issues/160

**Comment by andrewrk** [comment]
Your example now prints `(test.zig:5:38)` and I added docs: https://ziglang.org/documentation/master/#struct-naming
