### ISSUE TITLE
Zig 0.9.1 - build error on riscv64

### ISSUE THREAD

**Issue by kassane** [ziglang/zig#12432]
I'm testing on the single board D1 Nezha.

**OS**: Archlinux
**Arch**: rv64imacdfvx
**Zig version:** 0.9.1 (Unfortunately there is no master for riscv)

## Code

```zig
pub fn main() void{
  // Test
}
```

## Output

```bash
$> zig run -O ReleaseFast main.zig -fno-sanitize-c -target riscv64-linux -mcpu=baseline_rv64 -lc
Compile C Objects [375/1342] vfscanf.c... error(compilation): clang failed with stderr: zig: error: clang frontend command failed with exit code 132 (use -v to see invocation)
clang version 13.0.1 (git@github.com:ziglang/zig-bootstrap.git 81f0e6c5b902ead84753490db4f0007d08df964a)
Target: riscv64-unknown-linux-musl
Thread model: posix
InstalledDir: /home/sipeed
zig: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
zig: note: diagnostic msg: /tmp/vfprintf-93ac6e.c
zig: note: diagnostic msg: /tmp/vfprintf-93ac6e.sh
zig: note: diagnostic msg: 

********************
```

**Comment by nektro** [comment]
please include contents of `/tmp/vfprintf-93ac6e.c` and `/tmp/vfprintf-93ac6e.sh`

**Comment by kassane** [comment]
> please include contents of `/tmp/vfprintf-93ac6e.c` and `/tmp/vfprintf-93ac6e.sh`

No longer have access to the temporary files after crashing the board.
I restarted the board (**single core - 1 GB RAM DDR3**) and deleted the zig cache files (`zig-cache` & `~/.cache/zig`).
After a few minutes compiling... it happens:

```bash
/home/sipeed/.cache/zig/o/3a99b9ec4fd42048e073efa3a1e2d4d2/main: error while loading shared libraries: /usr/lib/libc.so: invalid ELF header

$> file /lib/libc.so.6
/lib/libc.so.6: ELF 64-bit LSB shared object, UCB RISC-V, RVC, double-float ABI, version 1 (GNU/Linux), dynamically linked, interpreter /usr/lib/ld-linux-riscv64-lp64d.so.1, BuildID[sha1]=205dbd70ceebe8d2813f19dfa3560423184189b8, for GNU/Linux 4.15.0, stripped

$> ldd --version      
ldd (GNU libc) 2.36
Copyright (C) 2022 Free Software Foundation, Inc.
```
but works with musl! And without linking the glibc it worked.

**Note:** Building any application on this board is a fairly exhaustive. Eternal loading... `LLVM Emit Object...`

**Comment by kassane** [comment]
I will close this topic!

Because regardless of the toolchain there must have been some instability of the device that caused some problem during compilation.
I will only keep mentioned another topic involving the same **single board**. In which it is used cross-compiled on the computer using the zig nightly version.

- https://github.com/ziglang/zig/issues/12106#issuecomment-1183638208
