### ISSUE TITLE
Compiler segfaults with explicit integer packed structs and `-femit-docs` when the struct contains a decl

### ISSUE THREAD

**Issue by tauoverpi** [ziglang/zig#12435]
### Zig Version

0.10.0-dev.3550+fa50e179f

### Steps to Reproduce

zig test -fno-stage1 -femit-docs

```zig
const Constant = packed struct(u32) {
    pub const Use = undefined;
};
```

### Expected Behavior

```
All 0 tests passed.
```

### Actual Behavior

```
fish: Job 1, 'zig test bug.zig -fno-stage1 -f…' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by kristoff-it** [comment]
Solved in [b392228](https://github.com/ziglang/zig/commit/b3922289be1ffaf194b55face332892280981356)
