### ISSUE TITLE
std.math.big.Rational.order and std.math.big.Rational.orderAbs Swap is_abs Argument

### ISSUE THREAD

**Issue by nsmryan** [ziglang/zig#12440]
It looks to me that the order and orderAbs functions in std.math.big.Rational have their 'is_abs' arguments swapped- order should give 'false' and orderAbs should give 'true' since it wants an absolute ordering.

order function:
https://github.com/ziglang/zig/blob/54454fd0102af8b25dbc85751d37fd265380d920/lib/std/math/big/rational.zig#L337

orderAbs:
https://github.com/ziglang/zig/blob/54454fd0102af8b25dbc85751d37fd265380d920/lib/std/math/big/rational.zig#L343

**Comment by matu3ba** [comment]
wold be nice, if you can add some smol tests.

**Comment by nsmryan** [comment]
I am working on a PR for this with new unit tests to catch this case.
I have it working with a zig-bootstrap build, but as I understand I will have to build zig from source from this repo, make the change there, test, and then I can submit something.

**Comment by matu3ba** [comment]
You need the CMAKE_PREFIX_PATH to zig bootstrap `host/`.

I do use `./build -j2 x86_64-linux-gnu native` within a worktree and
```sh
alias  zbuild='cd build/ && cmake .. -DCMAKE_PREFIX_PATH="$HOME/dev/git/bootstrap/zig-bootstrap/musl/out/host/" -GNinja && sed -i "s/-Werror //" build.ninja && /usr/bin/time -v ${HOME}/dev/git/cpp/mold/mold -run ninja install && cd ..'
```

to workaround some errors from `-Werror` for the LLVM 14.0.6 API.
You can remove the `time` and `mold -run` parts.

**Comment by matu3ba** [comment]
If you want to only test libstd non-C related things, you dont need to build from scratch.

You can also try using an old zig binary, but breaking zig build changes can prevent this.

**Comment by nsmryan** [comment]
It looks like #12720 addresses this issue.
