### ISSUE TITLE
std.testing.expectEqual to use expectEqualSlices on Pointer.Slice or add expectEqualDeep to do so?

### ISSUE THREAD

**Issue by zenspider** [ziglang/zig#12451]
### Zig Version

0.10.0-dev.3457+5c9826630

### Steps to Reproduce

```zig
const std = @import("std");

const T = struct { value: []const u8 };

const s1: []const u8 = "woot";
const s2: []const u8 = "XwootX";
const s3: []const u8 = s2[1..5]; // "woot" w/ different address

const t1: T = .{ .value = s1 };
const t2: T = .{ .value = s3 };

test "std.testing.expectEqual" {
    try std.testing.expectEqual(t1, t2); // expected slice ptr u8@1028ab8aa, found u8@1028ab8b0
}

test "expectEqualDeep" {
    try expectEqualDeep(t1, t2);
}
```

### Expected Behavior

preferably both tests would pass... I write a lot of tests. I'm getting constantly bitten by string literal (eg expected test values) addresses being different from constructed string addresses (eg, read from a file or subset/slice).

I get why that might not be the desired behavior for plain `expectEqual`, so I could also see a new function added that explicitly is a deep version. I don't think it needs to be foolproof (ie doesn't need to track "followed" to prevent cycle traversal) if it is opt in.

### Actual Behavior

see above

**Comment by zenspider** [comment]
```zig

**Comment by nektro** [comment]
use `std.testing.expectEqualSlices`

**Comment by zenspider** [comment]
@nektro please read original problem description again and then go look at my proposed solution.

**Comment by zenspider** [comment]
@nektro I forgot to incorporate the struct T into the problem... I've fixed my original description. Thank you.

**Comment by nektro** [comment]
`std.testing.expect(std.meta.eql(t1, t2));` might work too

**Comment by zenspider** [comment]
No:
> Compares two of any type for equality. Containers are compared on a field-by-field basis, where possible. Pointers are not followed.

**Comment by jiacai2050** [comment]
I get bited by this issue

> std.testing.expect(std.meta.eql(t1, t2));

This don't work also, I think it's `expectEqual` issue, it should test content, not ptr for slice.

**Comment by jiacai2050** [comment]
@Vexu Would you mind check if https://github.com/ziglang/zig/issues/12451#issuecomment-1214525610 is right solution?

For now, we couldn't compare two struct with `slice` fields directly, we have to compare all fields one by one, which is not convenient.
https://github.com/jiacai2050/simargs/blob/9440badce0e5438cea05c76b6d1bae381043d632/src/simargs.zig#L555

**Comment by Vexu** [comment]
`expectEqualSlices` will only work on types comparable with `==` so using it in an `expectEqualDeep` could be misleading but otherwise it looks fine. If you want more comments open a PR.
