### ISSUE TITLE
Stage 2: Wrong alignment for `c_longlong` on i386

### ISSUE THREAD

**Issue by ehaas** [ziglang/zig#12453]
### Zig Version

0.10.0-dev.3530+a82d7c206

### Steps to Reproduce

```zig
const std = @import("std");

test {
    comptime std.debug.assert(@alignOf(c_longlong) == 4);
}
```

run using `zig test -fno-stage1 -target i386-linux-gnu test.zig`

### Expected Behavior

Test successfully runs (or compiles but fails to run due to incorrect architecture). That is what happens with:
`zig test -fstage1 -target i386-linux-gnu test.zig`

### Actual Behavior

Compilation fails with:

```
~/source/zig/lib/std/debug.zig:281:14: error: reached unreachable code
    if (!ok) unreachable; // assertion failure
             ^~~~~~~~~~~
test.zig:4:30: note: called from here
    comptime std.debug.assert(@alignOf(c_longlong) == 4);
             ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Stage 2 thinks the alignment is 8.

**Comment by nektro** [comment]
C standard says `c_longlong` must be `i64`. things like compiler_rt will enable this to be true even on 32bit platforms

**Comment by ehaas** [comment]
The size must be at least 64 bits but on i386 the alignment is only required to be 4 bytes.
