### ISSUE TITLE
break from switch in loop bypasses unused value check

### ISSUE THREAD

**Issue by Vexu** [ziglang/zig#12455]
### Zig Version

0.10.0-dev.3577+b3922289b

### Steps to Reproduce

```zig
test {
    var a: u32 = 0;
    while (true) switch (a) {
        0 => 2,
        1 => a = 0,
        else => break,
    };
}
```

### Expected Behavior

A compile error complaining about types or unused value.

### Actual Behavior

Successful compile and an infinite loop.

**Comment by nektro** [comment]
behavior makes sense to me

**Comment by Vexu** [comment]
It's a foot gun and an error in stage1 and shouldn't be allowed

**Comment by nektro** [comment]
the code never hits the `else` thats why its looping. `a` alternates between being `0` and `1`. im lost on what the bug actually is here since the expected behavior written is so vague

**Comment by Vexu** [comment]
Typo in the example, `1` was supposed to be `2`, which was being ignored instead of being assigned to `a` causing the infinite loop.

**Comment by nektro** [comment]
stage1:

```
./test.zig:4:14: error: integer value 2 cannot be coerced to type 'void'
        0 => 2,
             ^
```

**Comment by kkHAIKE** [comment]
relate https://github.com/ziglang/zig/issues/11816

**Comment by Vexu** [comment]
It is a bug and the original example should cause a compile error.
