### ISSUE TITLE
mmap constants in stdlib

### ISSUE THREAD

**Issue by yujiri8** [ziglang/zig#12470]
Just ran into this while trying to interface with libwayland-client without bindings. `std.os.mmap` takes u32 for the `prot` and `flags` arguments. There are constants for these in C, such as `PROT_READ`, `PROT_WRITE`, and `MAP_SHARED`. Zig should have constants like that.

**Comment by nektro** [comment]
- `std.os.linux.PROT.READ`
- `std.os.linux.PROT.WRITE`
- `std.os.linux.MAP.SHARED`

**Comment by yujiri8** [comment]
Thank you, I didn't find them because of the naming convention.
