### ISSUE TITLE
get third party project "zigup" building successfully with self-hosted

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#12497]
### Zig Version

0.10.0-dev.3653+7152a58c1

### Steps to Reproduce

```
git clone git@github.com:marler8997/zigup.git
cd zigup
zig build
```

### Expected Behavior

This project compiles successfully with stage1, so it is expected to either build successfully or require minor code upgrades and then build successfully with self-hosted.

If there is a compile error, it is expected to point to the correct line.

### Actual Behavior

```
/home/andy/Downloads/zigup/GitRepoStep.zig:1:1: error: expected type '[]const u8', found '@TypeOf(null)'
//! Publish Date: 2022_05_05
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Note that the compile error is pointing to the incorrect line.

**Comment by Vexu** [comment]
This builds successfully on latest master.
