### ISSUE TITLE
Integer overflow when attempting to run build.zig with new stage3 compiler

### ISSUE THREAD

**Issue by truemedian** [ziglang/zig#12504]
### Zig Version

0.10.0-dev.3659+e5e6eb983

built with 0.10.0-dev.3633+be2bd5848 on archlinux

### Steps to Reproduce

- Build the newly merged stage3 compiler in debug mode.
- Clone <https://github.com/truemedian/hzzp>
- Run `zig build -h`

### Expected Behavior

The build.zig should have been executed successfully.

### Actual Behavior

Codegen had an integer overflow

Error: <https://hastebin.com/yafisiyize> (stack trace starts at line 3278)

**Comment by andrewrk** [comment]
Looks like you built from source and did not `-Denable-llvm` - meaning that this attempted to use the x86 backend which is not ready for primetime yet.

**Comment by truemedian** [comment]
Whoops, you are totally right, I thought I was passing that.
