### ISSUE TITLE
Master tarballs other than linux x86_64 have incorrect directory format

### ISSUE THREAD

**Issue by leecannon** [ziglang/zig#12516]
### Zig Version

3659+e5e6eb983

### Steps to Reproduce

Download any master tarballs from https://ziglang.org/download/ except linux x86_64 and extract.

### Expected Behavior

This is the expected directory structure (zig-linux-x86_64-0.10.0-dev.3659+e5e6eb983)
```
$ tree -L 2
.
├── docs
│   ├── langref.html
│   └── std
├── lib
│   ├── build_runner.zig
│   ├── compiler_rt
│   ├── compiler_rt.zig
│   ├── c.zig
│   ├── docs
│   ├── include
│   ├── init-exe
│   ├── init-lib
│   ├── libc
│   ├── libcxx
│   ├── libcxxabi
│   ├── libunwind
│   ├── ssp.zig
│   ├── std
│   ├── test_runner.zig
│   └── tsan
├── LICENSE
└── zig
```

### Actual Behavior

Actual structure (example is zig-linux-aarch64-0.10.0-dev.3659+e5e6eb983 but the rest have the same issue)
```
$ tree -L 2
.
├── langref.html
├── lib
│   └── zig
├── LICENSE
└── zig
```

Looking one directory lower shows everying there but one directory lower than expected for the libs and also the docs folder not in the root.
```
$ tree -L 3
.
├── langref.html
├── lib
│   └── zig
│       ├── build_runner.zig
│       ├── compiler_rt
│       ├── compiler_rt.zig
│       ├── c.zig
│       ├── docs
│       ├── include
│       ├── init-exe
│       ├── init-lib
│       ├── libc
│       ├── libcxx
│       ├── libcxxabi
│       ├── libunwind
│       ├── ssp.zig
│       ├── std
│       ├── test_runner.zig
│       └── tsan
├── LICENSE
└── zig

13 directories, 8 files
```

**Comment by Zzzen** [comment]
Any workaround? I've tried downgrade zig to 0.9.1 but got same result.

**Comment by nektro** [comment]
its regressed a couple times, not sure how it pops up

**Comment by BratishkaErik** [comment]
Duplicate of #9158 ?

**Comment by leecannon** [comment]
Closing as duplicate.
