### ISSUE TITLE
Stage2/3 Causes 10x Drop in Performance

### ISSUE THREAD

**Issue by ominitay** [ziglang/zig#12518]
### Zig Version

0.10.0-dev.3659+e5e6eb983

### Steps to Reproduce

Extract [https://0x0.st/o9zs.tar.xz](https://0x0.st/o9zs.tar.xz) into a subdirectory.
Build the attached project with stage1, and then with stage2/3, with the command `zig build -Drelease-fast`. Run each executable, and enter the command `go depth 7`. The number after `nps` indicates the speed of the program in nodes per second. 

### Expected Behavior

The values for nps would be roughly equal, or stage2/3 would produce a faster executable.

### Actual Behavior

Stage2/3 produces an executable approximately 10x slower than stage1 does.

**Comment by ominitay** [comment]
For reference, my output:
stage1
```
go depth 7
info depth 1 nodes 21 nps 21000 score cp 36 hashfull 0
...
info depth 7 nodes 516601 nps 210000 score cp 28 hashfull 588
```

stage2/3
```
go depth 7
info depth 1 nodes 21 nps 21000 score cp 36 hashfull 0
...
info depth 7 nodes 516557 nps 1666312 score cp 28 hashfull 574
```

**Comment by kubkon** [comment]
Could you also specify arch and os please?

**Comment by ominitay** [comment]
Linux x64

**Comment by ominitay** [comment]
If you have the patience to run `go depth 8`, the performance loss increases to just over 10x.

**Comment by notramo** [comment]
Linux aarch64 is also affected by this.
The stdlib Argon2 implementation is ≈13 times slower both on x86_64 and aarch64.

**Comment by andrewrk** [comment]
Can you please run your performance test again now that 892fb0fc8830007542381fe845e618dc47493622 has landed?

**Comment by notramo** [comment]
I ran these benchmarks on `0.11.0-dev.151+32b97df50`, which is newer than `892fb0f`. I don't know how slow it was before `892fb0f`, or if it improved Argon2 performance.

**Comment by notramo** [comment]
Probably worth mentioning that I was testing it with the `ReleaseSafe`, not the `ReleaseFast` mode. It's not recommended to compile with `ReleaseFast` when security is important.

**Comment by ominitay** [comment]
The 10x difference in performance is now gone, and stage2 is on the same order of magnitude of performance as stage1 for this. I'll need to perform some more thorough statistical tests to determine whether stage2 still produces slower binaries than stage1, but the main issue here is thankfully solved.

**Comment by matu3ba** [comment]
> The 10x difference in performance is now gone, and stage2 is on the same order of magnitude of performance as stage1 for this. I'll need to perform some more thorough statistical tests to determine whether stage2 still produces slower binaries than stage1, but the main issue here is thankfully solved.

Any updates on this?

**Comment by ominitay** [comment]
Nope, haven't been programming for a while now. Probably makes sense to close this issue.
