### ISSUE TITLE
Stage2 orelse type inference incorrect

### ISSUE THREAD

**Issue by Sirius902** [ziglang/zig#12537]
### Zig Version

0.10.0-dev.3659+e5e6eb983

### Steps to Reproduce

Compile the following zig program.

```zig
pub fn main() void {
    const foo: [*c]const u8 = "hey";
    const d = foo orelse return;
    @compileLog(@TypeOf(d));
}
```

### Expected Behavior

~~I expect the output of this compile log statement to indicate that the type of `d` is `[*c]const u8`, the same as `foo`.~~
After discussion it would seem `[*]const u8` would be a more reasonable type for `d`.

### Actual Behavior

On stage1 the compiler outputs the type `[*c]const u8` in the compiler log output, however stage2 reports the type of `d` to be `*const allowzero u8`.

**Comment by nektro** [comment]
type should prolly be `[*]const u8` but stage2 is the more correct one here

**Comment by Sirius902** [comment]
@nektro Right, I think `[*]const u8` would make more sense here. The main issue with stage2's current approach is that a multi pointer is becoming a single pointer, making `d` pretty much unusable.

**Comment by Vexu** [comment]
Related #6597
