### ISSUE TITLE
Transalte-c generates invalid zig (unescaped characters)

### ISSUE THREAD

**Issue by psnszsn** [ziglang/zig#12549]
### Zig Version

0.10.0-dev.3659+e5e6eb983

### Steps to Reproduce

- `asd.h` contains:

  ```c
  #define asd "ASD	"
  ```
  (the character after ASD is a tab)

- `asd.zig` contains:
  ```zig
  const std = @import("std");
  const c = @cImport({
      @cInclude("asd.h");
  });
  
  test{
      std.debug.print("{s}\n", .{c.asd});
  }
  ```
- run `zig test asd.zig -lc -I.`

### Expected Behavior

Compile successfully

### Actual Behavior

Compilation fails:
```
zig-cache/o/2ba70bf5d1fe5df47298c857c8beed71/cimport.zig:467:21: error: expected ';' after declaration
pub const asd = "ASD ";
                    ^~
zig-cache/o/2ba70bf5d1fe5df47298c857c8beed71/cimport.zig:467:23: note: invalid byte: ';'
pub const asd = "ASD ";
                      ^
asd.zig:2:15: error: C import failed: AnalysisFail
pub const c = @cImport({
              ^~~~~~~~
```

With `-fstage1` it compiles successfully, even though the offending tab character is still in the generated `cimport.zig` file.

**Comment by nektro** [comment]
`std.zig.fmtEscapes()` is the function you're looking for, for anyone taking this on
