### ISSUE TITLE
Get third party project "zig-gamedev" working successfully with self-hosted

### ISSUE THREAD

**Issue by michal-z** [ziglang/zig#12552]
### Zig Version

0.10.0-dev.3659+e5e6eb983

### Steps to Reproduce

The problem occurs only on macOS AArch64 with stage2 and stage3 (works correctly on Windows, Linux and macOS x86_64 with stage1/stage2/stage3).

1. `git clone https://github.com/michal-z/zig-gamedev`
2. `cd zig-gamedev`
3. `zig build audio_experiments_wgpu-run`
4. Crash in the sample application (looks like miscompilation)

### Expected Behavior

Sample application works correctly.

### Actual Behavior

```
[zgpu] High-performance device has been selected:
[zgpu]   Name: Apple M1 Max
[zgpu]   Driver: Metal driver on macOS Version 12.5 (Build 21G72)
[zgpu]   Adapter type: discrete_gpu
[zgpu]   Backend type: metal
Segmentation fault at address 0xbb1b259f81cd0091
???:?:?: 0x1028743d0 in _ma_waveform_config_init (???)
/Users/jonas/src/zig/zig-gamedev/samples/audio_experiments_wgpu/src/audio_experiments_wgpu.zig:358:35: 0x1023c9523 in create (audio_experiments_wgpu)
        audio.engine.getSampleRate(),
                                  ^
/Users/jonas/src/zig/zig-gamedev/samples/audio_experiments_wgpu/src/audio_experiments_wgpu.zig:1001:28: 0x1023d1d77 in main (audio_experiments_wgpu)
    const demo = try create(allocator, window);
                           ^
/Users/jonas/src/zig/zig/build/stage3/lib/zig/std/start.zig:574:37: 0x1023d62eb in main (audio_experiments_wgpu)
        },
                                    ^
???:?:?: 0x10364508b in ??? (???)
???:?:?: 0x1e1f7fffffffffff in ??? (???)
```

**Comment by michal-z** [comment]
Project is also affected by:
https://github.com/ziglang/zig/issues/12483
https://github.com/ziglang/zig/issues/12325

We currently employ workarounds for above issues.

**Comment by kamidev** [comment]
As part of current workarounds, we had to avoid using cImport on MacOS. It does work for other platforms, though. This issue might be relevant: 
#12185

**Comment by michal-z** [comment]
We have confirmed that the original issue is an AAarch C ABI problem. Returning a structure by value that is 32 bytes in size causes a crash. We now have a workaround for this.

In summary, all cross-platform sample application works correctly know. Project is affected by 3 above issues but we workaround them.

@andrewrk @Vexu Should we leave this issue open?
