### ISSUE TITLE
stage2: @sizeOf packed struct is not working as in stage1

### ISSUE THREAD

**Issue by igor84** [ziglang/zig#12565]
### Zig Version

0.10.0-dev.3664+02070ae26

### Steps to Reproduce

```zig
const Rgb24 = packed struct {
    r: u8,
    g: u8,
    b: u8,
};

test {
    try std.testing.expectEqual(@as(usize, 3), @sizeOf(Rgb24));
}
```

### Expected Behavior

The above test should pass.

Some time ago I fixed issues with packed struct in stage1 so that `@sizeOf(Rgb24)` would return `3` and if I have `pixels: []Rgb24` I could use `reader.readAll(std.mem.sliceAsBytes(pixels))` to load tightly packed Rgb24 data.

### Actual Behavior

Now in stage2 `@sizeOf(Rgb24)` returns `4` and the array also isn't tightly packed but has additional byte of padding for each element which breaks `readAll` code.

**Comment by nektro** [comment]
the issue still stands, but for your mentioned use case you likely want `extern struct` not `packed`

**Comment by nektro** [comment]
you can also do `packed struct(u24)` as zig is likely defaulting to u32

**Comment by Vexu** [comment]
Working as intended, the self-hosted compiler implements #5049

**Comment by igor84** [comment]
@Vexu  As far as I know stage1 doesn't compile with `packed struct(u24)` so is there a way to write code so it works with both stage1 and stage2?

@nektro I would say I need packed because I also have `Rgb565{u5, u6, u5}`  for example and extern will not work for that.

**Comment by Vexu** [comment]
> As far as I know stage1 doesn't compile with `packed struct(u24)` so is there a way to write code so it works with both stage1 and stage2?

You can use `@import("builtin").zig_backend` to check what you are using but I recommend sticking to either stage1 or stage2.
