### ISSUE TITLE
stage2: Optional pointers no longer accepted in packed structs

### ISSUE THREAD

**Issue by 17dec** [ziglang/zig#12572]
### Zig Version

0.10.0-dev.3665+9cf667a21

### Steps to Reproduce

```zig
const T = packed struct {
    ptr: ?*const u8,
};

pub fn main() void {
    const n: u8 = 0;
    const x = T{.ptr = &n};
    _ = x;
}
```

### Expected Behavior

I (ab)use packed structs quite a bit in [ncdu](https://dev.yorhel.nl/ncdu) and have some with optional pointers in them. While I *could* work around this limitation in stage2, it won't look very nice (probably involving `allowzero` pointers :cry: ).

### Actual Behavior

Fails on stage2.

**Comment by nektro** [comment]
you likely want `extern struct` instead
