### ISSUE TITLE
Assignment of non-byte-aligned field in packed struct overwrites wrong bits

### ISSUE THREAD

**Issue by veloscillator** [ziglang/zig#12571]
### Zig Version

0.10.0-dev.3551+92568a009

### Steps to Reproduce

Version `0.10.0-dev.3551+92568a009` x64 linux.

I realize using packed structs like this can be buggy. Apologies if I'm doing anything naive.

When I assign `frame` directly, it puts the 5 bytes in the wrong place (check the the bytes of the resulting u32). It's plopping `07FDE` into the lowest order, instead of highest order, bytes.

When I set the field directly, it's fine.

```
const Frame = packed struct {
    num: u20,
};

const Entry = packed struct {
    other: u12,
    frame: Frame,
};

pub fn main() !void {
    comptime std.debug.assert(@bitSizeOf(Entry) == 32);
    comptime std.debug.assert(@bitSizeOf(Frame) == 20);
    comptime std.debug.assert(@bitOffsetOf(Entry, "frame") == 12);

    const frame = Frame{ .num = 0x7FDE };
    std.log.debug("frame.num={x}", .{frame.num});

    var wrong = Entry{ .other = 0, .frame = .{ .num = 0xFFFFF } };
    wrong.frame = frame; // Boom!
    std.log.debug("wrong.frame.num={x} wrong.other={x} bytes={x}", .{wrong.frame.num, wrong.other, @ptrCast(*u32, @alignCast(4, &wrong)).*});

    var right = Entry{ .other = 0, .frame = .{ .num = 0xFFFFF } };
    right.frame.num = frame.num; // Works.
    std.log.debug("right.frame.num={x} right.other={x} bytes={x}", .{right.frame.num, right.other, @ptrCast(*u32, @alignCast(4, &right)).*});
}
```

### Expected Behavior

Expected Output:

debug: frame.num=7fde
debug: wrong.frame.num=7fde wrong.other=0 bytes=7fde000
debug: right.frame.num=7fde right.other=0 bytes=7fde000

### Actual Behavior

Actual Output:

debug: frame.num=7fde
debug: wrong.frame.num=ff007 wrong.other=fde bytes=ff007fde
debug: right.frame.num=7fde right.other=0 bytes=7fde000

**Comment by nektro** [comment]
using the self hosted compiler (`> 0.10.0-dev.3659+e5e6eb983`) the output is correct

```
[meghan@nixos]$ zig run test.zig 
debug: frame.num=7fde
debug: wrong.frame.num=7fde wrong.other=0 bytes=7fde000
debug: right.frame.num=7fde right.other=0 bytes=7fde000
```

**Comment by veloscillator** [comment]
From reading other issues, it looks like packed structs with weird sizes like this aren't supported. Not sure if that's the issue. But I'm getting the sense I shouldn't do this.
