### ISSUE TITLE
Get third party project "zig-clap" working successfully with self-hosted

### ISSUE THREAD

**Issue by Hejsil** [ziglang/zig#12595]
### Zig Version

0.10.0-dev.3702+583175dc1

### Steps to Reproduce

```
$ git clone https://github.com/Hejsil/zig-clap.git
$ cd zig-clap
$ zig build
```

### Expected Behavior

Compiles and pass all tests like stage 1

### Actual Behavior

```
zig-clap/clap.zig:903:31: error: expected type '?*const anyopaque', found '*const []const []const u8'
                    .slice => &@as([]const T, &[_]T{}),
                              ^~~~~~~~~~~~~~~~~~~~~~~~
zig-clap/clap.zig:903:31: note: pointer type child '[]const []const u8' cannot cast into pointer type child 'anyopaque'
zig-clap/clap.zig:680:24: note: called from here
        args: Arguments(Id, params, value_parsers, .slice),

```

**Comment by Vexu** [comment]
Seems like correct behavior, from #12042;
> The test case `dont_implicit_cast_double_pointer_to_anyopaque.zig` suggests that this is intentional.

**Comment by Hejsil** [comment]
Hmm I guess we consider a pointer to a slice a form of double pointer for this check

**Comment by andrewrk** [comment]
Related: https://github.com/kristoff-it/zig-doctest/commit/10049a218c4910695486b83ec61e23f964960a48

As far as I understand, none of these are working around bugs.

**Comment by Hejsil** [comment]
> Seems like correct behavior, from #12042;
> 
> > The test case `dont_implicit_cast_double_pointer_to_anyopaque.zig` suggests that this is intentional.

Yea, this seems to have been the only blocker and it is not even a bug, just an unclear error message. zig-clap now compiles with both stage1 and 2
