### ISSUE TITLE
Zig can't find root module on std

### ISSUE THREAD

**Issue by uwussimo** [ziglang/zig#12592]
### Zig Version

0.10.0-dev.3659+e5e6eb983 M1 ARM64 Homebrew HEAD

### Steps to Reproduce

Install indicated version of zig and write any program using std library.

Example:
```
const std = @import("std");

pub fn main() void {
    std.debug.print("Hello, {s}!\n", .{"World"});
}
```

### Expected Behavior

**Error like:**
```
/opt/homebrew/Cellar/zig/HEAD-e5e6eb9_1/lib/zig/std/start.zig:3:22: error: unable to load 'main.zig': FileNotFound
const root = @import("root");
                     ^~~~~~
```

### Actual Behavior

SImply go forward and print the hello word as it's shown in my example...

**Comment by andrewrk** [comment]
I cannot reproduce this on my M1. I do not have homebrew installed. I can only conclude it is an issue with Homebrew.

**Comment by chiumichael** [comment]
The example code runs successfully on 0.10.0-dev.3714+5696cc8ab M1 ARM64 Homebrew HEAD.

**Comment by uwussimo** [comment]
> The example code runs successfully on 0.10.0-dev.3714+5696cc8ab M1 ARM64 Homebrew HEAD.
Still facing the issue on `0.10.0-dev.3714+5696cc8ab`

```
❯ zig run main.zig
/opt/homebrew/Cellar/zig/HEAD-5696cc8_1/lib/zig/std/start.zig:3:22: error: unable to load 'main.zig': FileNotFound
const root = @import("root");
```

Tried to recompile zig from --HEAD, didn't work.

**Comment by uwussimo** [comment]
However, a few days ago it was working... I'm not that experienced on zig and I might be mistaken but as I checked, there is no root.zig in [std](https://github.com/ziglang/zig/tree/master/lib/std)

**Comment by uwussimo** [comment]
@andrewrk I'm so sorry for wasting your time for my stupidity. It was my fault that I ran `zig run main.zig` instead of `zig build run`. Forgive me please 🥲. Closing the issue.

**Comment by cztomsik** [comment]
I hit this with `zig run example.zig`, I just wanted to provide small example for my lib but since I am relying on `zig run` there is no root module. Maybe it would be nice if `zig run` implied that root_module is the file itself?

**Comment by nektro** [comment]
it does. please check out one of our great [Community](https://github.com/ziglang/zig/wiki/Community)s to ask for help debugging this.
