### ISSUE TITLE
zig fmt: module comments are removed when a container lacks a trailing comma on it's last field

### ISSUE THREAD

**Issue by tauoverpi** [ziglang/zig#12617]
### Zig Version

0.10.0-dev.3685+dae7aeb33

### Steps to Reproduce

zig fmt -stdin < bug.zig

```zig
const Signature = enum(u32) { //! this should stay
_ };
```

### Expected Behavior

```zig
const Signature = enum(u32) { 
    //! this should stay
    _,
};
```

### Actual Behavior

```zig
const Signature = enum(u32) { _ };
```

**Comment by nektro** [comment]
expected is compile error or

```zig
//! this should stay
const Signature = enum(u32) { 
    _,
};
```

module comments are required to be the first in a file. removing the `!` works as expected and produces

```zig
const Signature = enum(u32) { // this should stay
    _,
};
```

**Comment by ifreund** [comment]
> module comments are required to be the first in a file. removing the `!` works as expected and produces

ThIs is not correct according to the zig grammar: https://github.com/ziglang/zig-spec/blob/a55d08275e478418c26f367482582448617499b8/grammar/grammar.y

Changing the grammar to allow container doc comments only at the start of a file is certainly possible, but that would be a breaking change and is separate from this zig fmt bug.

**Comment by nektro** [comment]
> This is not correct according to the zig grammar

the first line says so `Root <- skip container_doc_comment? ContainerMembers eof`

**Comment by ifreund** [comment]
> > This is not correct according to the zig grammar
> 
> the first line says so `Root <- skip container_doc_comment? ContainerMembers eof`

`container_doc_comment` also appears elsewhere in the grammar.

**Comment by yujiri8** [comment]
I want to do this. Where is the zig fmt source code?

**Comment by yujiri8** [comment]
Found it

**Comment by yujiri8** [comment]
This is proving much more difficult than I expected, but I've found that the problem is not in the parser, but the renderer. The problem is that hasComment returns false when there isn't a trailing comma...

**Comment by yujiri8** [comment]
No wait, the problem is that hasComment returns false either way. It isn't called when there's a trailing comma
