### ISSUE TITLE
Regression from stage1: `func() ++ "foo"` string append fails without explicit `comptime { func() }`

### ISSUE THREAD

**Issue by Techcable** [ziglang/zig#12636]
### Zig Version

0.10.0-dev.3685+dae7aeb33

### Steps to Reproduce

The following code fails to compile on stage3, but works fine on stage1:
 
```zig
const std = @import("std");

fn sdk_root() []const u8 {
    return std.fs.path.dirname(@src().file) orelse ".";
}

fn dep_root_broken() []const u8 {
    return sdk_root() ++ "/deps/mpack";
}
```

Surrounding `sdk_root` with an explicit `comptime` block fixes the compilation errors:

```zig
fn dep_root_working() []const u8 {
    const sdk_root_val = comptime blk: { break :blk sdk_root(); };
    return sdk_root_val ++ "/deps/mpack";
}
```

Here is a complete file that reproduces the issue:

https://gist.github.com/Techcable/40e2be2d27e138012865155ab773e0bb

Executing it with `zig run minimized.zig` will trigger an error, but executing `zig run -fstage1 minimized.zig` will not.

### Expected Behavior

The compiler should behave like it did with stage1. The `comptime` should be inferred automatically instead of requiring it explicitly.

This is a problem in practice for my project which uses [zig-mpack](https://github.com/Techcable/zig-mpack)

### Actual Behavior

The stage3 compiler on nightly dae7aeb33 gives the following error for `zig run minimized.zig`:
```
minimized.zig:13:20: error: unable to resolve comptime value
    return sdk_root() ++ "/deps/mpack";
           ~~~~~~~~^~
minimized.zig:13:20: note: slice value being concatenated must be comptime known
```

Stage3 only gives this error on the second call to `dep_root_broken`, the first

Stage1 works fine for both implicit and explicit comptime.

Stage 3 still does *not* give the error, if I add an explicit `comptime` block around the call  (`dep_root_working`).

**Comment by kcbanner** [comment]
You don't need to use a block there, you can put a `comptime` in front of the function call, see https://github.com/ziglang/zig/wiki/Self-Hosted-Compiler-Upgrade-Guide#runtime-slice-concatenation--multiplication

**Comment by Vexu** [comment]
Working as intended, see #11773
