### ISSUE TITLE
Regression of comptime evaluation

### ISSUE THREAD

**Issue by NateDogg1232** [ziglang/zig#12635]
### Zig Version

0.10.0-dev.3740+d5233ee85

### Steps to Reproduce

Use `zig init-exe` to create a simple project, and in main.zig use this kind of code:
```zig
const std = @import("std");
pub const TestEnum = enum {
    test_value1,
    pub fn getStr(e: @This()) []const u8 {
        return switch (e) {
            .test_value1 => "A new test value",
        };
    }
};

pub fn main() anyerror!void {
    var new_string = "A test string with " ++ TestEnum.getStr(.test_value1);
    std.log.info("String: {s}", .{new_string});
}
```

### Expected Behavior

The program compiles successfully

### Actual Behavior

You will get the error:
```
main.zig:11:62: error: unable to resolve comptime value
    var new_string = "A test string with " ++ TestEnum.getStr(.test_value1);
                                              ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
main.zig:11:62: note: slice value being concatenated must be comptime known
```

Just some notes, I'm not quite sure when this regression occurred. I only tested master against the 0.9.1 release. I do suspect this has to do with stage2 comptime evaluation.

**Comment by nektro** [comment]
make method

```diff
-pub fn getStr(e: @This()) []const u8 {
+pub fn getStr(comptime e: @This()) []const u8 {
```

**Comment by NateDogg1232** [comment]
Same error even with that change.

**Comment by andrewrk** [comment]
This section explains the situation and gives you a 1-liner to fix it: https://github.com/ziglang/zig/wiki/Self-Hosted-Compiler-Upgrade-Guide#runtime-slice-concatenation--multiplication

When  #12108 is fixed you would have an additional option to solve the problem:

```diff
-    pub fn getStr(e: @This()) []const u8 {
+    pub inline fn getStr(e: @This()) []const u8 {
```

**Comment by NateDogg1232** [comment]
I'd like to reopen this, because even with the inlining of the function, the same problem occurs.

I rewrote it as `pub inline fn getStr(e: @This()) []const u8` and the error is still the same.

**Comment by NateDogg1232** [comment]
Ah actually never mind. That was my bad I only did the patch you showed I should've looked at the link you sent. It works great thank you!
