### ISSUE TITLE
Feature: Getting the Error in an errdefer

### ISSUE THREAD

**Issue by bheads** [ziglang/zig#1265]
Would be useful to get the error when an errdefer runs.

```C
errdefer |err|  logger("I got an {}", err);
```

With respect to coro's running the errdefer when canceled there could be an error.AsyncCanceled that only the async function sees.  This could be useful to help the async fn to clean up

**Comment by Bekwnn** [comment]
Additionally once errdefer is able to get the error, it would be nice if errdefer has the choice on whether or not to return it higher up. I'm finding you _have_ to create a separate function if you have a chunk of code which has multiple places it may throw an error, but which you don't care if the process fails. Example from a build.zig:

_(In this example it actually breaks out into its own function pretty cleanly, but it's easy to imagine a version where it doesn't and you have to pass several 'Dir's, an allocator, or other parameters to the function and it generally gets messier than you'd like it to.)_

```
fn deleteOldLib() !void {
    const workingDir = fs.cwd();
    var binDir = try workingDir.openDirTraverse("zig-cache");
    binDir = try binDir.openDirTraverse("bin");
    try binDir.deleteFile("something.dll");
}

fn copyLib() !void {
    deleteOldSDLLib() catch |e| {
        std.debug.warn("Unable to find old something.dll in zig-cache/bin\n", .{});
    }; // don't care if this fails

    // Copy dll to zig-cache/bin
    const dllName = "something.dll";

    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = &arena.allocator;

    const srcPath = fs.path.resolve(allocator, &[_][]const u8{ "dependency", "something", "lib", "x64", dllName }) catch |e| {
        std.debug.warn("Unable to resolve src path\n", .{});
        return e;
    };
    const dstPath = fs.path.resolve(allocator, &[_][]const u8{ "zig-cache", "bin", dllName }) catch |e| {
        std.debug.warn("Unable to resolve dst path\n", .{});
        return e;
    };
    try fs.copyFile(srcPath, dstPath) catch |e| {
        std.debug.warn("Unable to copy file from {} to {}\n", .{ srcPath, dstPath });
        return e;
    };
}
```
I'd have preferred to have the deleteOldLib() function just exist in the copyLib one given how short it is. If it were possible to do this instead I'd prefer it to work like the following, where the 'try' statements forward the error to the errdefer for handling:
```
fn copyLib() !void {
    {
        // code from deleteOldLib(). . .

        // don't care if this fails
        // given there's no 'return e;', would hope the 'try' code doesn't return all the way out of copyLib
        errdefer |e| std.debug.warn("Unable to find old something.dll in zig-cache/bin\n", .{}); 
    }
    
    // . . .
}
```
I don't really think having errdefer work that way is necessarily that great either, but it does currently strike me as a bit weird that you can't perform error handling on a section of code within a function in the same way you could if you were to break that code out into its own function.

**Comment by Bekwnn** [comment]
After a little bit of thought maybe errdefer is the wrong feature for this case. Maybe it's the ability to have something like:
```
fn copyLib() !void {
    {
        // deleteOldLib code with multiple Dir-related 'try' function calls . . .
    } catch |e| {} // it's fine if we don't find an old lib file to delete before copying the new one

    // rest of copyLib process . . .
}
```

**Comment by andrewrk** [comment]
> Maybe it's the ability to have something like:

This is the closest you can get in status quo zig: 

```zig
const value = b: {
    a() catch |e| break :b e;
    b() catch |e| break :b e;
    c() catch |e| break :b e;
    d() catch |e| break :b e;
} catch |e| {
    // deal with it
};
```

It's unlikely to add a language feature to address this use case further. My suggestion would be to break the code into a function if you want to take advantage of `try`. Or, just type out the `catch |e| break :b e` stuff and call it a day.
