### ISSUE TITLE
LLVM error when using extern functions

### ISSUE THREAD

**Issue by NateDogg1232** [ziglang/zig#12680]
### Zig Version

0.10.0-dev.3780+56bdd0127

### Steps to Reproduce

Initialize a folder with `zig init-exe`
Have two files. A c.o file from the c file as follows:
```c
extern void test_func();
void c_func() {
    test_func();
}
```
I compiled this using
```bash
clang -c c.c -o c.o
```

With the zig code as follows
```zig
const std = @import("std");
pub extern c_func() callconv(.C) void;
pub fn main() anyerror!void {
    c_func();
}
pub export fn testFunc() callconv(.C) void {
   std.debug.print("func", .{});
}
comptime {
    @export(testFunc, .{ name = "test_func", .linkage = .Strong});
}
```

In the build.zig, add this:
```zig
/// ...
exe.setBuildMode(mode);
exe.addObjectFile("c.o");
exe.install();
```

Then run `zig build`.

### Expected Behavior

The program runs and compiles. This works in 0.9.1.

### Actual Behavior

An error occurs
```
LLVM Emit Object...                                                                                       
Alias and aliasee types should match!                                                                     
void ()** @test_func                                                                                      
                                                                                                          
thread 296040 panic: LLVM module verification failed
```

**Comment by NateDogg1232** [comment]
For some additional context of how I came across this. I have some assembly stubs for a hobby OS I am making for interrupt handlers, and I came across this in my migration to nightly and self-hosted Zig, since it's just a pet project and I'm okay with taking a detour to find some bugs that have to do with things I think are used commonly in freestanding environments.

**Comment by NateDogg1232** [comment]
Here's the git repo of how I did this test
https://github.com/NateDogg1232/zig-issue-12680

**Comment by Vexu** [comment]
Minimal rerproduction:
```zig
// zig build-obj repr.zig
pub export fn testFunc() callconv(.C) void {}
comptime {
    @export(testFunc, .{ .name = "test_func", .linkage = .Strong });
}
```
Issue seems to be that we emit
```llvm
@test_func = alias void ()*, void ()* @testFunc
```
instead of
```llvm
@test_func = alias void (), void ()* @testFunc
```
