### ISSUE TITLE
Autodoc: View Function Source 403 Forbidden

### ISSUE THREAD

**Issue by jcalabro** [ziglang/zig#12688]
Hello, hope things are going well with you!

I can't seem to be able to click the `[src]` button on function definitions in autodoc. When I do, I get a 403 Forbidden.

For instance, I've been trying to click the `[src]` button of `json.encodeJsonString` ([docs page](https://ziglang.org/documentation/master/std/#root;json)), which brings me to [this src page](https://ziglang.org/documentation/master/std/src/json.zig#L2236).

Here is a curl:

<details>

```
curl 'https://ziglang.org/documentation/master/std/src/json.zig#L2236' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: https://ziglang.org/documentation/master/std/' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'Sec-Fetch-Dest: document' -H 'Sec-Fetch-Mode: navigate' -H 'Sec-Fetch-Site: same-origin' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: trailers'
```

</details>

And [here is a .har file](https://github.com/ziglang/zig/files/9454876/forbidden-src.har.zip).

I see that you're using S3 to host these files, I've worked quite a bit w/ AWS, happy to help debug further if needed.

Thanks!
- Jim

**Comment by kristoff-it** [comment]
Hi Jim,
the CI script that deploys the stdlib autodocs was not updated yet to also deploy src file listings when the feature was first implemented. It was fixed soon after, but we're currently in the middle of a big breakage in the master branch causing the CI to be constantly red. Once the master branch returns to green the docs will be updated and the listings should finally become available.

**Comment by jcalabro** [comment]
Perfect, thank you!

**Comment by jcalabro** [comment]
Hi again, following up to say that this is working now. Thanks! 👍 

<img width="1582" alt="Screen Shot 2022-09-06 at 8 49 37 PM" src="https://user-images.githubusercontent.com/8205547/188764786-8c726ef1-6ac7-4f8b-a5b1-7dd65c61e0fe.png">
