### ISSUE TITLE
Changes about const quolifier

### ISSUE THREAD

**Issue by mattn** [ziglang/zig#12696]
### Zig Version

0.10.0-dev.3685+dae7aeb33

### Steps to Reproduce

I'm using this idiom to get commonly seekable reader interfaces.

```zig
fn reader(r: anytype) bufReader(@TypeOf(r)) {
    return std.io.peekStream(2, r);
}

fn bufReader(r: anytype) type {
    return std.io.PeekStream(std.fifo.LinearFifoBufferType{ .Static = 2 }, r);
}
```

```zig
var in1 = reader(std.io.fixedBufferStream(t.input).reader());

var f = try std.fs.cwd().openFile(arg, .{});
defer f.close();
var in2 = reader(f.reader());
```

But recent commits, this makes error.

```
/home/mattn/dev/zig-lisp/src/main.zig:755:58: error: expected type '*io.fixed_buffer_stream.FixedBufferStream([]const u8)', found '*const io.fixed_buffer_stream.FixedBufferStream([]const u8)'
        var br = reader(std.io.fixedBufferStream(t.input).reader());
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/mattn/dev/zig-lisp/src/main.zig:755:58: note: cast discards const qualifier
```

What is wrong?

### Expected Behavior

Compilation successfully

### Actual Behavior

Compilation error

**Comment by haze** [comment]
This is intended now https://github.com/ziglang/zig/wiki/Self-Hosted-Compiler-Upgrade-Guide#address-of-temporaries-now-produces-const-pointers

**Comment by mattn** [comment]
Could you or anyone provide what is the best way to get commonly seekable interfaces for file or bytes?

**Comment by haze** [comment]
file: https://github.com/ziglang/zig/blob/59e33b447b0502bdfa18909f4381360bb8f49b70/lib/std/fs/file.zig#L1384

bytes: https://github.com/ziglang/zig/blob/59e33b447b0502bdfa18909f4381360bb8f49b70/lib/std/io/fixed_buffer_stream.zig#L43

the zig issue tracker is meant for bug reports, questions should be directed at one of the helpful [communities](https://github.com/ziglang/zig/wiki/Community)

**Comment by mattn** [comment]
Ah, Sorry. I did not know the functions. So I thought this might be a bug.

**Comment by mattn** [comment]
Hmm, what I want was PeekStream not SeekableStream. ( But I don't know commonly way to get them )

**Comment by mattn** [comment]
Recent version, I could avoid compilation error with put temporary variable for stream. But in the last commit, I couldn't compile it anymore.
