### ISSUE TITLE
POSIX & Networking Support

### ISSUE THREAD

**Issue by kristate** [ziglang/zig#1271]
Tracking issue for building-out `std.os.posix.*` and friends.

**OS Support**
* [ ] Darwin *(macOS, iOS, tvOS)*
  *tracking PR: #1272*
* [ ] Windows
* [ ] BSD? 

**Async API**
* [ ] Berkeley Sockets
* [ ] TCP
* [ ] UDP
  *tracking PR: #1331*

**Memos**

https://github.com/ziglang/zig/blob/b6eb404831e44a92b4841459068f4fbe9c753541/std/event/tcp.zig#L127

**Comment by cup** [comment]
https://github.com/ziglang/zig/issues/2007

**Comment by cup** [comment]
looks like sockets are already available?

https://github.com/ziglang/zig/blob/5026db1d311e94c59e96aa4a11b33aee7b6a9925/lib/std/net.zig#L219-L247

https://github.com/ziglang/zig/blob/5026db1d311e94c59e96aa4a11b33aee7b6a9925/lib/std/os.zig#L1724-L1748

**Comment by shawnl** [comment]
@cup But that is not asynchronous.

**Comment by cup** [comment]
then title should read "... & async networking"

**Comment by cup** [comment]
@shawnl 

https://github.com/ziglang/zig/blob/5026db1d311e94c59e96aa4a11b33aee7b6a9925/lib/std/os.zig#L1752-L1776
