### ISSUE TITLE
illegal instruction

### ISSUE THREAD

**Issue by sundq** [ziglang/zig#12719]
### Zig Version

0.10.0-dev.3838+77f31ebbb

### Steps to Reproduce

my os is linux:Linux sundaqing 5.10.29-amd64-desktop #2 SMP Mon Apr 26 09:48:13 CST 2021 x86_64 GNU/Linux
```
#include <stdio.h>
#include <stdint.h>


/// type of racoon_message_obersver_s
typedef struct racoon_message_obersver_s racoon_message_obersver_t;

struct racoon_message_obersver_s
{
    const char *name;


    uint32_t ob_msgid;

    int link;
};

int main(int argc, const char *argv[])
{
	int x = &(((racoon_message_obersver_t *)0)->link); /// dump
	return 0;
}
```

### Expected Behavior

run normal

### Actual Behavior

compile with 'zig cc' and dump for illegal instruction

**Comment by leecannon** [comment]
https://github.com/ziglang/zig/wiki/zig-cc-compatibility-with-clang#ubsan-and-sigill-illegal-instruction

Yoru program has UB, if you build it with clang with the `-fsanitize=undefined` flag the same thing will happen, although a better error will be displayed.

**Comment by Vexu** [comment]
Related #5163
