### ISSUE TITLE
Confusing error when calling `zig build` in directory without build.zig

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#12711]
### Zig Version

0.10.0-dev.3840+2b92c5a23

### Steps to Reproduce

Enter a directory that does not contain a `build.zig` file and run `zig build`.

### Expected Behavior

I'd expect to see something along the lines of
```
Couldn't find build.zig.
To initialize a project, please call zig init-exe...
```

### Actual Behavior

Instead it outputs FileNotFound along with a lot of gibberish:
```
error: FileNotFound
error: mint...
error: The following command exited with error code 1:
/home/mint/Downloads/zig/zig build-exe /home/mint/src/main.zig --cache-dir /home/mint/zig-cache --global-cache-dir /home/mint/.cache/zig --name mint --enable-cache 
error: the following build command failed with exit code 1:
/home/mint/zig-cache/o/7270a7c68dc41557a5d091b4dcfd41f2/build /home/mint/Downloads/zig/zig /home/mint /home/mint/zig-cache /home/mint/.cache/zig
```
​

​

#### Backstory
I'm rewriting an old project in zig and because of that I have 2 very similar folders. And out of habit I `cd`ed into the old one which has no `build.zig`.
It took me around 10 minutes to figure out that I'm in the wrong folder. I would have noticed immediately if the error message was better.

**Comment by johnaoss** [comment]
Looks like this is done, although I'm not sure as of when. As of `0.10.0-dev.4560+828735ac0` it prints the following:

```
info: Initialize a 'build.zig' template file with `zig init-lib` or `zig init-exe`,
or see `zig --help` for more options.
error: No 'build.zig' file found, in the current directory or any parent directories.
```

**Comment by nektro** [comment]
appears you called `zig init-exe` in your home directory
