### ISSUE TITLE
Compile error when trying to perform boolean operations on results of inlined functions

### ISSUE THREAD

**Issue by zxubian** [ziglang/zig#12734]
### Zig Version

0.9.1 (windows, chocolatey)

### Steps to Reproduce

``` zig
fn test_fn() bool{
    if(return_bool() && return_bool()){
        return true;
    }
    return false;
}


fn return_bool() bool{
    return true;
}

```

### Expected Behavior

Test code above compiles. (and test_fn should return ` true`)

### Actual Behavior

The following error is produced:

```
error: `&&` is invalid; note that `and` is boolean AND
    if(return_bool() && return_bool()){
                     ^
```

Similar errors are produced when trying to use ``if(return_bool() || return_bool())``.

**Comment by leecannon** [comment]
Boolean and is `and` not `&&`

**Comment by zxubian** [comment]
Thanks, I completely missed it. Now that I re-read the message, it makes more sense...
I'll close this issue!
