### ISSUE TITLE
Link errors when building stage3 for aarch64-linux

### ISSUE THREAD

**Issue by The-King-of-Toasters** [ziglang/zig#12746]
### Zig Version

0.10.0-dev.3877+3deb33fff

### Steps to Reproduce

Build from source as per the wiki. I'm currently using an Arch Linux ARM vm with the LLVM/Clang/LLD packages installed, but the problem also manifests when I compiled these libraries myself

### Expected Behavior

Stage 3 `zig` to be linked without any issues.

### Actual Behavior

The `stage3` target fails due to [LLD link errors](https://zigbin.io/5ca5be).

**Comment by The-King-of-Toasters** [comment]
Bisecting this shows that the problem always occured when #12508 was merged.

**Comment by The-King-of-Toasters** [comment]
The situation seems to be a bit better with LLVM 15, as only one identifier is missing:
```
[195/195] Building stage3
FAILED: CMakeFiles/stage3 /home/stephen/gits/zig/build/CMakeFiles/stage3
cd /home/stephen/gits/zig && /home/stephen/gits/zig/build/zig2 build --zig-lib-dir /home/stephen/gits/zig/lib --prefix /home/stephen/gits/zig/build/
stage3 -Dconfig_h=/home/stephen/gits/zig/build/config.h -Denable-llvm -Denable-stage1 -Drelease -Dstrip -Dskip-install-lib-files=false -Dtarget=nati
ve -Dcpu=baseline -Dversion-string=0.10.0-dev.4095+afba53f0f
error(compilation): clang failed with stderr: /home/stephen/gits/zig/src/stage1/codegen.cpp:4826:17: error: use of undeclared identifier 'LLVMPointe
rTypeInContext'
/home/stephen/gits/zig/src/stage1/codegen.cpp:5171:17: error: use of undeclared identifier 'LLVMPointerTypeInContext'
```

**Comment by matu3ba** [comment]
Does https://github.com/ziglang/zig/pull/12898 fix this issue?

**Comment by The-King-of-Toasters** [comment]
> Does #12898 fix this issue?

Nej :(.

**Comment by andrewrk** [comment]
> Nej :(.

Can you verify that you deleted your cmake cache when testing to see if #12898 solved the issue?

**Comment by The-King-of-Toasters** [comment]
Yes. And I'm also experiencing this using zig-bootstrap too. Although from your response, it sounds like it's just a me problem?
