### ISSUE TITLE
aarch64-macos: Link time MissingMainEntrypoint error

### ISSUE THREAD

**Issue by ThanHenderson** [ziglang/zig#12744]
### Zig Version

0.9.1

### Steps to Reproduce

In main.zig
```
const std = @import("std");
const macos = std.os.darwin;

pub export fn _start() callconv(.Naked) noreturn {
    _ = macos.write(1, "Hello", 5);
    macos.exit(0);
}
```
zig build-exe main.zig --strip -OReleaseSmall -target aarch64-macos

Note: Building from an aarch64 Mac.

### Expected Behavior

"Hello" output to stdout.

### Actual Behavior

error(link): '_main' export not found
error: MissingMainEntrypoint

**Comment by kubkon** [comment]
You need to overwrite the default entry point (`_main`) with your actual entry point of `__start` (note the double `_` character), like so:

```
$ cat main.zig 
const std = @import("std");
const macos = std.os.darwin;

pub export fn _start() callconv(.Naked) noreturn {
    _ = macos.write(1, "Hello", 5);
    macos.exit(0);
}

$ zig build-exe main.zig --entry __start
$ ./main
Hello%                                                                                                                                                                                                                                                                                                                                               
```

I've tested it with latest release `0.10` and it works fine for me.

**Comment by kubkon** [comment]
In light of the above, I will close the issue as resolved, but if you think otherwise then feel free to reopen it.
