### ISSUE TITLE
Autodoc: function pages should have src link

### ISSUE THREAD

**Issue by 89z** [ziglang/zig#12759]
This page:

https://ziglang.org/documentation/master/std#root;json

has helpful `src` links, such as:

https://ziglang.org/documentation/master/std/src/json.zig#L1712

however if you browse to a specific function:

https://ziglang.org/documentation/master/std#root;json.parse

you lose the `src` link for some reason. That is to say, on the page for an individual function, you dont have any link to see the source for that function, so you have to go back to the previous page.

**Comment by kristoff-it** [comment]
I believe the (now merged) PR addresses the topic of this issue, so I'm closing it.

**Comment by jcalabro** [comment]
Thanks! Was this deployed to production, i.e. at https://ziglang.org/documentation/master/std/#root;json?

I see double `[src]` tags in there now...seems like a recent regression, almost certainly related to my fix above? I can walk that out and work on getting it to work without impacting any other pages. Sorry, just noticed that issue, didn't catch it while I was developing

![image](https://user-images.githubusercontent.com/8205547/196999593-511def0d-6d97-4fb1-9697-67509c091aa3.png)

**Comment by jcalabro** [comment]
https://github.com/ziglang/zig/pull/13300 was merged, the above bug is solved in 0.10.0 in favor of links in the function name (for now).
