### ISSUE TITLE
Self-Hosted Compiler: "Assembly Code Must Use String Literal Syntax" 

### ISSUE THREAD

**Issue by IridescentRose** [ziglang/zig#12756]
### Zig Version

0.10.0-dev.3871+b7d5582de

### Steps to Reproduce

Using mipsel-freestanding-mips2 the following code should work. 

```zig
pub fn import_module_start(comptime module: []const u8, comptime flags_ver: []const u8, comptime count: []const u8) []const u8 {
    return (
        \\.set push
        \\.set noreorder
        \\.section .rodata.sceResident, "a"
        \\__stub_modulestr_
        ++ module ++ ":\n" ++
        \\.asciz  "
        ++ module ++ "\"\n" ++
        \\.align  2
        \\.section .lib.stub, "a", @progbits
        \\.global __stub_module_
        ++ module ++ "\n" ++
        \\__stub_module_
        ++ module ++ ":\n" ++
        \\.word   __stub_modulestr_
        ++ module ++ "\n" ++
        \\.word   
        ++ flags_ver ++ "\n" ++
        \\.hword   0x5
        \\.hword 
        ++ count ++ "\n" ++
        \\.word   __stub_idtable_
        ++ module ++ "\n" ++
        \\.word   __stub_text_
        ++ module ++ "\n" ++
        \\.section .rodata.sceNid, "a"
        \\__stub_idtable_
        ++ module ++ ":\n" ++
        \\.section .sceStub.text, "ax", @progbits
        \\__stub_text_
        ++ module ++ ":\n" ++
        \\.set pop
    );
}

comptime {
    asm ( import_module_start("sceAtrac3plus", "0x00090000", "25") );
}
```

### Expected Behavior

It compiles successfully in v0.9 & below and in v0.10 -fstage1 because asm() blocks require a comptime known string as per the documentation. This means that generating a comptime known expression into a string and placing that string into the asm() works as you would expect.

### Actual Behavior

In v0.10 in self-hosted mode you can no longer do so in asm() which greatly harms your ability to auto-generate some necessary assembly code. I would argue that this goes against Zig's promise that everything is an expression and reduces the nuance of what you can do with comptime.

**Comment by devins2518** [comment]
For an example use case within the compiler, my pr to add aarch64 outlined atomics in #11828 needed to use a separate generation script and a bunch of nasty comptime expressions to create small differences between linux and Darwin aarch64 platforms which might not have lse. The result is a 11k line pr with a 10.5k line generated file instead of an (iirc) around 2k line file with self contained comptime expressions.

**Comment by Vexu** [comment]
Error removed in a1486e1e1e52175d3e1b26049ea960b9c00edeb7

**Comment by IridescentRose** [comment]
Nice
