### ISSUE TITLE
zig cc does not accept -mtune=generic

### ISSUE THREAD

**Issue by orent** [ziglang/zig#12767]
### Zig Version

0.9.1

### Steps to Reproduce

Compile c code with -mtune=generic

This option is frequently passed by some makefiles and build scripts and is frequently the only thing preventing zig cc from being an otherwise drop-in replacement. It should be safe to just ignore it.

### Expected Behavior

Accept this gcc-ism

### Actual Behavior

error: unknown target CPU 'generic'

**Comment by kassane** [comment]
This was already proposed in [#4911](https://github.com/ziglang/zig/issues/4911)

**Comment by orent** [comment]
This is not the same as #4911 which makes no mention of 'generic'

This proposal is specifically about value 'generic' which exists in gcc but not in llvm. It means a "a fairly old but not really ancient CPU target we will update from time".

Please reopen

**Comment by Vexu** [comment]
Clang does accept `-mtune=generic`, are you saying that it handles it differently?

**Comment by orent** [comment]
Oh, you're right. 
"zig cc" does not accept it, but "zig clang" does 

Targets accepted by zig clang but not zig cc are:
generic
goldmont-plus
core-avx-i
core-avx2
skylake-avx512
icelake-client
icelake-server
athlon-fx
x86-64

Neither accepts x86-64-v2, x86-64-v3, x86-64-v4

So is this included in  #4911, after all?

**Comment by Vexu** [comment]
Sounds like it but feel free to mention it there too.
