### ISSUE TITLE
How to support some std library function on freestanding target ?

### ISSUE THREAD

**Issue by no1wudi** [ziglang/zig#12804]
Hello, I'm new to Zig, and I'm a embedded software developer.

I'm trying to run zig on some real time operate system such as apache nuttx.

I find it seems some useful function like std.debug.print is not available on freestanding system, is there any way to let them works ?

Or, if no such way, can we leave some stub syscall in freestanding.zig (like newlibc does) to allow user implement these syscall in there systems instead of in Zig's std library ?

Thanks.

**Comment by nektro** [comment]
you can implement the cross platform abstractions by defining `root.os`

**Comment by no1wudi** [comment]
@nektro Thanks, I'll try it

**Comment by no1wudi** [comment]
@nektro Could you please show me some examples for it ? Such as where to define the `root.os` and where to import it ? Thanks
