### ISSUE TITLE
`std.testing.refAllDecls` references `pub` decls only, private ones are ignored

### ISSUE THREAD

**Issue by magurotuna** [ziglang/zig#12838]
### Zig Version

0.10.0-dev.3999+fda6d4477

### Steps to Reproduce

```zig
const std = @import("std");
const expect = std.testing.expect;

test {
    std.testing.refAllDecls(@This());
}

const S = struct {
    test "Should fail" {
        try expect(false);
    }
};
```

Suppose we have a file that looks like the above, named `foo.zig`, and run `zig test foo.zig`.

### Expected Behavior

Obviously it should fail since it has `expect(false)` in the test.

### Actual Behavior

The test is successfully done. To be more precise, the test case located in `S` is just ignored just because `S` is not `pub`ed.
In Zig v0.9.1 it fails as expected. Plus the official doc introduces this technique as well: https://ziglang.org/documentation/master/#toc-Nested-Container-Tests, where we can see the test case in `S` is supposed to be executed even if `S` is private. In other words, the technique shown in the doc works fine in v0.9.1, not in the nightly.

I'm pretty sure that this behavior change has come from https://github.com/ziglang/zig/pull/10909. Given that `refAllDecls` resides in the `testing` module, it would make much more sense to allow private declarations to be referenced as well. It can be useless for us to annotate structs that we create just for organizing test cases with `pub` in my opinion.

**Comment by magurotuna** [comment]
`refAllDecls` uses `@field` internally, which only supports public declarations. Given that, it seems like it'd be better to keep the current behavior of `refAllDecls`. So the way to go would be to revise the doc so that it will be aligned with the actual behavior.

**Comment by leecannon** [comment]
Because of this limitation that `@field` places on `refAllDecls` and `refAllDeclsRecursive` I have started including a copy of  `refAllDeclsRecursive` in every zig file like the below.

```zig
comptime {
    refAllDeclsRecursive(@This());
}

/// This is a copy of `std.testing.refAllDeclsRecursive` but as it is in the file it can access private decls
fn refAllDeclsRecursive(comptime T: type) void {
    // impl
}
```

**Comment by andrewrk** [comment]
`refAllDecls` is a hack that will almost certainly be removed from the standard library, and reflection will never inspect private declarations.
