### ISSUE TITLE
stage1 and stage3 behave differently in regard to function pointer

### ISSUE THREAD

**Issue by dee0xeed** [ziglang/zig#12842]
### Zig Version

0.10.0-dev.3900+ab4b26d8a

### Steps to Reproduce

1. Create file containing this code
```zig
// fp.zig
const std = @import("std");
const print = std.debug.print;

const FuncPtr = *const fn () void;

fn hello() void {
    print("hello\n", .{});
}

pub fn main() void {
    const func: ?FuncPtr = &hello;

    if (func) |f| {
        f();
    }
}
```
2. Compile with `zig build-exe fp.zig`
3. Compile with `zig build-exe fp.zig -fstage1`

### Expected Behavior

stage1 and stage3 compilers should behave the same way

### Actual Behavior

stage3: successful compilation (and the program works)

stage1: compilation error:

```
$ /opt/zig/zig build-exe fp.zig -fstage1
./fp.zig:16:9: error: type '*const fn() void' not a function
        f();
        ^
```

**Comment by andrewrk** [comment]
https://github.com/ziglang/zig/wiki/Self-Hosted-Compiler-Upgrade-Guide#function-pointers

**Comment by dee0xeed** [comment]
@andrewrk thanx!

**Comment by andrewrk** [comment]
Happy hacking!

**Comment by dee0xeed** [comment]
@andrewrk kinda forgot to ask - does that mean that zig compiler written in C++ is 'frozen' forever?
