### ISSUE TITLE
[Question] controlling pointers which go to epoll_event.data.ptr

### ISSUE THREAD

**Issue by dee0xeed** [ziglang/zig#12853]
While doing some exercises with Linux epoll facility, I made stupid mistake:

```zig
var tm0: EventSource = me.timers.items[0];
tm0.start(&me.md.eq, 1000) catch unreachable;
```

`timers` is `ArrayList` from zig stdlib.
Deep inside `start()` the address of 'tm0' (which is a **local var**, **copy** of the first element of the list)
 is assigned to `epoll_event.data.ptr` field. Upon returning from `epoll_wait()` I am using this pointer and
since it is obviously invalid, program gets `SIGSEGV` inevitably.

It was not hard to fix the code:
```zig
var tm0: *EventSource = &me.timers.items[0];
tm0.start(&me.md.eq, 1000) catch unreachable;
```
But I am wondering - is it ever possible for zig compiler to detect errors similar to that?
Or is it up to the programmer? Hello, C, so to say ;)

**Comment by dee0xeed** [comment]
Some thinking...

This is a sort of special case of interaction with OS kernel.
* we allocate something on the heap and have a pointer to that something
* then we **put this pointer to kernel space** via epoll/kqueue/whatever,
and we can even loose this pointer in user space (hello, garbage collection), because 
* OS kernel will return it to us with epoll_wait()/kevent()/etc

Saving user space pointers in kernel space is very-very convenient!
So the real question is - are there any programming languages that can control such out-of-any-**scope** pointers?

**Comment by andrewrk** [comment]
Hi @dee0xeed - I'm reserving the issue tracker for actionable items. Please take this question to [one of the discussion forums](https://github.com/ziglang/zig/wiki/Community). In particular for this question I would recommend [this one](https://ziggit.dev/).

**Comment by dee0xeed** [comment]
@andrewrk nevermind
