### ISSUE TITLE
Conditionally calling @clz() (built-in function) with different number of arguments doesn't wokr

### ISSUE THREAD

**Issue by hdante** [ziglang/zig#12856]
### Zig Version

0.9.1

### Steps to Reproduce

```zig
const std = @import("std");

pub fn main() !u8 {
        if (false) {
                std.debug.print("Hello");
        }
        else {
                std.debug.print("Hello", .{});
        }

        if (false) {
                return @clz(10);
        }
        else {
                return @clz(u8, 10);
        }

        return 0;
}
```

```
$ zig build-exe clz_err.zig 
clz_err.zig:12:24: error: expected 2 arguments, found 1
                return @clz(10);
                       ^
```

### Expected Behavior

Code successfully compiled.

### Actual Behavior

Switching the condition between `true` and `false` should make the error appear or go away, depending on the Zig version. However the error always appears. (Note: switching the first condition that calls std.debug.print() shows the expected behavior):

```zig
const std = @import("std");

pub fn main() !u8 {
        if (false) {
                std.debug.print("Hello");
        }
        else {
                std.debug.print("Hello", .{});
        }

//        if (false) {
//                return @clz(10);
//        }
//        else {
//                return @clz(u8, 10);
//        }

        return 0;
}
```

```
$ zig build-exe clz_err.zig
$
```

**Comment by Vexu** [comment]
Working as intended.

**Comment by hdante** [comment]
Hello, if it's working as intended I think there's an inconsistency when comparing the behavior of conditional code during compilation time (it behaves differently if there are function calls versus calls to built-in functions). My suggestion is to reconsider this inconsistency as a bug.

Anyway, I currently need to write code that supports both Zig 0.9.1 and Zig 0.10.0 and will need a way to call @clz() on each of these versions with a different signature. How can I do it ?

**Comment by hdante** [comment]
Hello ?

**Comment by nektro** [comment]
some differences in versions can be worked around using `builtin.zig_version` or `builtin.zig_backend`. however this is best effort and not a main use case. being able to workaround the changes in the signature of builtins across versions is not supported as stated above. please tell your users to stick to one version or the other
