### ISSUE TITLE
sigemptyset is missing in lib/std/os/linux.zig

### ISSUE THREAD

**Issue by dee0xeed** [ziglang/zig#12859]
I am trying to compile some code containing

```zig
    pub fn getSignalId(signo: u6) !i32 {
        var sset: SigSet = undefined;

        // block the signal
        std.os.linux.sigemptyset(&sset); // error here
        std.os.linux.sigaddset(&sset, signo);
        sigProcMask(SIG.BLOCK, &sset, null);

        return signalFd(-1, &sset, signo);
    }
```

compilation fails with

```
$ /opt/zig/zig build-exe 2-test.zig 
event-sources.zig:93:21: error: struct 'os.linux.os.linux' has no member named 'sigemptyset'
        std.os.linux.sigemptyset(&sset);
        ~~~~~~~~~~~~^~~~~~~~~~~~
```

grepping shows that

1. `sigaddset` is present

```
$ grep -rIi "pub fn sigadd" /opt/zig/lib
/opt/zig/lib/std/os/linux.zig:pub fn sigaddset(set: *sigset_t, sig: u6) void {
/opt/zig/lib/std/c/darwin.zig:pub fn sigaddset(set: *sigset_t, signo: u5) void {
```

2. `sigemptyset` is absent

```
$ grep -rIi "pub fn sigemp" /opt/zig/lib
$ 
```

Is it some incompleteness in the library?
Or maybe I do not understand something?

**Comment by matu3ba** [comment]
> Or maybe I do not understand something?

Zig provides code or itself, if it lowers the maintenance burden. See `pub const empty_sigset = system.empty_sigset;` in `lib/std/os.zig` that invokes on Linux `lib/std/os/linux.zig`.

Please ask next time in one of the community spaces for questions:
```
 Question
Please use one of the community spaces for questions or general discussions.
```

**Comment by dee0xeed** [comment]
> > Or maybe I do not understand something?
> 
> Zig provides code itself, if it lowers the maintenance burden. See `pub const empty_sigset = system.empty_sigset;` in `lib/std/os.zig` that invokes on Linux `lib/std/os/linux.zig`.

Thank you.
 
> Please ask next time in one of the community spaces for questions:

I actually did so before posting here:
https://ziggit.dev/t/how-to-use-sigemptyset-sigaddset-and-alike/324
