### ISSUE TITLE
error on unused struct fields?

### ISSUE THREAD

**Issue by dee0xeed** [ziglang/zig#12854]
Currently Zig allows structs to have fields which are never used in a program, for example:

```zig
// usf.zig
const std = @import("std");
const print = std.debug.print;

const Object = struct {
    a: i32 = 1,
    b: i32 = 2,
};

pub fn main() void {
    const o = Object{};
    print("{}\n", .{o.a});
}
``` 

It would be nice if Zig could detect this and generate an error similar to the error about unused function arguments.
P.S. I always wanted to have such a feature in C.

**Comment by leecannon** [comment]
This won't work if the layout/contents of a struct are not under the control of the programmer.

For example when implementing a device driver you might need a struct like:
```zig
const SomeDeviceThing = extern struct {
    flags: u8,
    id: u8,
    enabled: u8,
};
```

If you only use `flags` and `enabled` a compile error for `id` being unused as its mere existence is "using" it as is affects the size/alignment of the struct and the offset of fields following it.

So some discard syntax will have to be provided that is analogous to `_ = variable;`

**Comment by marler8997** [comment]
@leecanon I was also thinking of that use case.  What about non extern structs?

**Comment by nektro** [comment]
all fields are public so this feels like a non-starter. a field might not be being used by me, but it might be needed for someone else

**Comment by dee0xeed** [comment]
> This won't work if the layout/contents of a struct are not under the control of the programmer.

I thought about "my own" structs, not extern.

> If you only use `flags` and `enabled` a compile error for `id` being unused is unwanted

No doubt! But fields unused "by me" may be used outside of "my code" and if there is a field which is "globally" unused then it is not needed.

**Comment by nektro** [comment]
"my code" here refers to my entire program, not my library. if me and you are writing our own completely separate programs and you use all the fields of libFoo but I don't, I don't want program to not compile simply because I don't touch the entire api surface

**Comment by dee0xeed** [comment]
> "my code" here refers to my entire program, not my library. if me and you are writing our own completely separate programs and you use all the fields of libFoo but I don't

but field unused by you is for sure used in the libFoo itself...

**Comment by yujiri8** [comment]
https://github.com/ziglang/zig/wiki/Language-Proposals

**Comment by dee0xeed** [comment]
If a struct is imported from "my project directory" it is definitely "my struct" and detecting unused fields won't hurt nobody.
If a struct is imported somewhere from <path-to-zig/lib> then of course there is no reason to detect fields unused "by me".

**Comment by dee0xeed** [comment]
> https://github.com/ziglang/zig/wiki/Language-Proposals

this issue is not about "changing the language"

**Comment by tauoverpi** [comment]
Would work as long as the structs themselves are private and not `extern`/`packed`. `pub` structs can't fall under this rule but anything local to a file should be fine given they're not reachable outside anyway.

**Comment by dee0xeed** [comment]
> Would work as long as the structs themselves are private and not `extern`/`packed`. `pub` structs can't fall under this rule but anything local to a file should be fine given they're not reachable outside anyway.

I would extend this up to "anything local to a **project**", not just a file.

**Comment by Jarred-Sumner** [comment]
Alternate idea

When a non-packed, non-extern struct field has no usages with side effects (including no `@bitCast`, no `@sizeOf`, and no `@bitSizeOf`) on the parent struct (i.e. the size is not observable), automatically convert the type into a zero-width type. Since the memory layout of non-packed, non-extern structs are not guaranteed, an optimization like this should be fine?

**Comment by andrewrk** [comment]
I would love to do this, but it is not possible since whether a field is used can depend on semantic analysis, which depends on conditional compilation, which means the compiler does not know whether a field is truly unused.

Related:
 * #3028
 * #21010

**Comment by dee0xeed** [comment]
> which means the compiler does not know whether a field is truly unused

ok, a man is the king in his house.
even if he "does not know whether a field is truly unused" :-)

so rubble detection should be implemented
in some external tool I guess.
