### ISSUE TITLE
remove either `std.builtin.Version` or `std.SemanticVersion`

### ISSUE THREAD

**Issue by noiryuh** [ziglang/zig#12862]
Probably because `std.SemanticVersion` is the rewritten version of `std.builtin.Version`. But for now, we have 2 structs served for the same purpose (e.g. in `build.zig` and more)
```zig
const zig_version = std.builtin.Version{ .major = 0, .minor = 10, .patch = 0 };
const stack_size = 32 * 1024 * 1024;

pub fn build() !void {
    // ....
    const semver = try std.SemanticVersion.parse(version); // 'version' here is '-Dversion-string'
}
```

Maybe we can migrate to `std.SemanticVersion` and deprecate `std.builtin.Version` to avoid confusing and de-duplicate code.

**Comment by nektro** [comment]
`3.10` should set `.patch` to `0`

**Comment by r00ster91** [comment]
That's clear. That's not what I was asking. I will probably pick it up later again though and just reimplement version parsing on a per-case basis where Semantic Versioning doesn't exactly apply.

**Comment by r00ster91** [comment]
Reopened #13998. Maybe I came up with something somewhat satisfactory. @nektro indeed, in the cases I encountered so far it's really just about the patch component that is sometimes omitted in input and sometimes has to be omitted (if zero) on output.
I did a lot of local testing so I'm reasonably confident that at least the std tests might pass in that PR.
