### ISSUE TITLE
JAI style "context" for allocators etc.

### ISSUE THREAD

**Issue by lerno** [ziglang/zig#1286]
JAI uses a context which contains things like default allocators. The context is a hidden variable that's passed into every call. In addition, it's possible to push / pop the context.

The advantage of this is primarily for allocators when used with library functions, but can be used for other things as well. This allows fine grained settings to be implicitly passed on.

In JAI, this is explicit style: 

    a: [..] u8; // variable sized arrays.
    b: [..] u8;

    pool: Pool;
    set_allocators(*pool);
    defer release(*pool);

    // Switch b to a custom allocator, a will keep using the heap allocator.
    b.allocator = pool_allocator;
    b.allocator_data = *pool;

    N :: 20;
    for 1..N {
        array_add(*a, cast(u8) it);
        array_add(*b, cast(u8) it);
    }

Using implicit contexts:

    pool: Pool;
    pool.alignment = 1;

    new_context := context;
    new_context.allocator      = pool_allocator;
    new_context.allocator_data = *pool;

    c2 : string;
    push_context new_context {
        c2 = concat(a, b);
    }

In this example, the allocation  of c2 uses the pool_allocator, while everything outside will use the default allocator.

In JAI (I don't know if this suitable for Zig) it's also possible to add even more data to the context:

    new_context.user_index = 13539;
    new_context.user_data  = cast(*void) debug_log;

    push_context new_context {
        do_some_work();
    }

The call here will propagate the data in the context:

    do_some_other_work :: () {
        if context.user_data {
           hook := cast(Debug_Hook) context.user_data;
           hook(context.user_index);
        }
    }

    do_some_work :: () {
        print("I am doing some work.\n");
        do_some_other_work();
    }

So the context here basically works like a thread local set of variables. However, it should not incur the cost that thread local variables have.

**Comment by tgschultz** [comment]
I'm having trouble seeing how this is more useful than the current idiom of simply passing in an allocator to anything requiring allocation. You get all the same benefits, but without any non-obvious action taking place. If we used a context as Jai does, then we have no idea if any given function call will allocate since it can use whatever is in the current context behind our back.

**Comment by lerno** [comment]
@tgschultz The point is to avoid all explicit allocators in all function profiles. Let's say you have written a library method `foo( ... )` that does a fair bit of allocation.

These are then the options:

1. Make the function `foo( allocator, ... )` and require an allocator always, even though people 99% of the cases wants to use a normal heap allocator.
2. Create two functions: `foo_with_allocator(allocator, ...)` and `foo(...)` where the latter uses the default allocator. This effectively doubles all non-trivial functions.
3. Ignore the whole thing and just use `foo( ... )` with a heap allocator.

In JAI the default allocator is the one provided in the context, so if I call on foo( ... ) which in turn calls bar( ... ) which calls baz( ... ), then I don't need to worry if bar / baz support using the custom allocator passed into foo.

Even more interesting. Let's say foo ( ... ) is originally implemented without needing any allocation. Later on, a new, more efficient way of implementing foo surfaces. Only it requires some allocation. Now the name and parameters need to change.

The context means stackable global state. Which essentially is the good things with globals without the bad.

Relevant video: https://www.youtube.com/watch?v=ciGQCP6HgqI

**Comment by andrewrk** [comment]
> Make the function foo( allocator, ... ) and require an allocator always, even though people 99% of the cases wants to use a normal heap allocator.

This is the option we currently go with, and in practice it's fine.

I think this is a major design difference between jblow's lang and zig. I'm happy with zig's approach.

**Comment by lerno** [comment]
@andrewrk note that the context here is not just used for the allocator. Similarly passing in the a logger, certain global values etc. In the initial version I think he hooked up the logger, a logging context, the thread id and some more things. This is essentially having `foo( Context*, ...)` for any call, since it's bundled implicitly.

You could do most of the things he does today in C by having a thread local object that's accessed. However the access here is expensive – at least in C. For a low-level webserver with a DB connection you could push the connection to the context and use it everywhere etc.

**Comment by BarabasGitHub** [comment]
It's sounds like a global variable, which is the worst thing ever imo. It's better to be explicit about all the things you want, such that there are no surprises. If something needs to log I'd rather see that it takes a log module than everything having a context so you never know what it will use from it.

**Comment by lerno** [comment]
@BarabasGitHub you misunderstand the functionality completely. Please watch the video.

Also, note that a logger needs to be global, thread local or passed in explicitly in order to be shared across all functions you write.

Explicit sharing is fine for your own code, but is difficult for spanning shared code.
