### ISSUE TITLE
stage2: mutating slice len through pointer requires explicit dereference

### ISSUE THREAD

**Issue by silversquirl** [ziglang/zig#12870]
### Zig Version

0.10.0-dev.4060+61aaef0b0

### Steps to Reproduce

```zig
const std = @import("std");

pub fn main() !void {
    var x: []const u8 = "Hello, world!";
    truncate(&x);
    std.debug.print("{s}\n", .{x});
}
fn truncate(x: *[]const u8) void {
    x.len = 5;
}
```

### Expected Behavior

Print `Hello`

### Actual Behavior

```
test.zig:9:13: error: cannot assign to constant
    x.len = 5;
            ^
```

Changing `x.len = 5` to `x.*.len = 5` works around the issue.

**Comment by nektro** [comment]
`[]T` is a slice which is already a pointer-like type. Zig only automatically provides one level of automatic dereference and all paramaters are const by default. working as intended.

**Comment by silversquirl** [comment]
@nektro `slice.len` does not do pointer indirection, it directly accesses a property of the slice itself. There is no implicit dereference.

You'll also notice that reading through a pointer works; it's just writing that doesn't. There's also a few cases where writing works too, which is why I put the write in a separate function for my test case.
