### ISSUE TITLE
function with !<sometype> return type but never returning an error

### ISSUE THREAD

**Issue by dee0xeed** [ziglang/zig#12871]
### Zig Version

0.10.0-dev.3900+ab4b26d8a

### Steps to Reproduce

1. Create a file containing
```zig
// 1-ef.zig
const std = @import("std");
const print = std.debug.print;

fn func() !i32 {
    return 7;
}

pub fn main() void {
    const n = try func();
    print("{}\n", .{n});
}
```
2. Compile with `/opt/zig/zig build-exe 1-ef.zig`

### Expected Behavior

I am not quite sure this is actually a bug, but I would expect some compilation error because `func` is defined as returning eror or `i32` but it never returns an error.

### Actual Behavior

Successful compilation

**Comment by cod1r** [comment]
This shouldn't be a bug. Testing with 0.9.1, and it works just like 0.10.x. I also tried 
```
// 1-ef.zig
const std = @import("std");
const print = std.debug.print;

const RandErr = error{
    URMOM
};

fn func() !i32 {
    return RandErr.URMOM;
}

pub fn main() !void {
    const n = try func();
    print("{}\n", .{n});
}
```
And 0.10.x returns an error just like 0.9.1.

**Comment by rohlem** [comment]
The compiler-inferred error set in this case will be empty: `error{}`
Note that all of Zig's error sets are ABI compatible, as they all have the same size and use the same enumeration as the global error set `anyerror`.
This means `error{}!T` is ABI-compatible with `anyerror!T`, and so a function pointer `*const fn(u8) error{}!u8` can be coerced to a function pointer returning a more general error set, up to `*const fn(u8) anyerror!u8`.

The only question is whether we want to allow automatic error set deduction (`!T` syntax) for functions that provably never return an error value.
For functions with any `comptime` argument, I'd say certainly, so we don't have to explore all possible instantiations.
Whether we want it for singly-instantiated functions may be up to preference.

**Comment by nektro** [comment]
sometimes a function needs to have an error set to adhere to an api signature. as mentioned above, if you'd like to assert that the function will not error, then you can explicitly define the function with the empty set (`error{}!T`)

**Comment by dee0xeed** [comment]
> The compiler-inferred error set in this case will be empty: error{}
> sometimes a function needs to have an error set to adhere to an api signature

understood, thanks!
