### ISSUE TITLE
Operator precedence for bitshift operators

### ISSUE THREAD

**Issue by lerno** [ziglang/zig#1287]
The operator precedence rules for C regarding bitshift are often considered problematic. Some languages have revisited those rules, making the precedence more sane.

Today `1 + 2 >> 3 + 4` means `(1 + 2) >> (3 + 4)`. If precedence is raised above addition, then a more natural `1 + (2 >> 3) + 4` would appear. The suggestion is to move it to the same level as multiplication (like Go or Nim). 

One could also consider moving it above multiplication, mirroring Algol W.

**Comment by andrewrk** [comment]
This will be solved by #114, where the above ambiguity will be a compile error, and must be resolved with parentheses.
