### ISSUE TITLE
Some improvement to syntax for error handling

### ISSUE THREAD

**Issue by lerno** [ziglang/zig#1288]
I think the error handling in Zig is near perfect. It avoids the exceptions and has more sane error channel than languages with result types.

That said, the syntax for it is very uneven right. On one hand we have the special syntax of try / catch / errdefer – but then we still just return things using `return error.SomeError` the "error." here is just persistent visual noise.

I propose the syntactic sugar of `exit(SomeError)`, alternatively `exit SomeError` as equal to `return error.SomeError`. The explicit return would still be available of course.

```
// Original
fn createFoo(param: i32) !Foo {

    const foo = try tryToAllocateFoo();
    errdefer deallocateFoo(foo);

    const tmp_buf = allocateTmpBuffer() orelse return error.OutOfMemory;
    defer deallocateTmpBuffer(tmp_buf);

    if (param > 1337) return error.InvalidParam;
    return foo;
}

// exit(SomeError)
fn createFoo(param: i32) !Foo {

    const foo = try tryToAllocateFoo();
    errdefer deallocateFoo(foo);

    const tmp_buf = allocateTmpBuffer() orelse exit(OutOfMemory);
    defer deallocateTmpBuffer(tmp_buf);

    if (param > 1337) exit(InvalidParam);
    return foo;
}

// exit SomeError
fn createFoo(param: i32) !Foo {

    const foo = try tryToAllocateFoo();
    errdefer deallocateFoo(foo);

    const tmp_buf = allocateTmpBuffer() orelse exit OutOfMemory;
    defer deallocateTmpBuffer(tmp_buf);

    if (param > 1337) exit InvalidParam;
    return foo;
}

```

Moving further on, the combination with try as a prefix and catch as suffix is difficult visually. Unlike in exception handling blocks like java, where the prefix position of "try" is more or less forced by the syntax, there is no real need to have it as a prefix. Also the use of "try" here is a bit weird since there is no actual "try" mechanism, just an automatic catch-throw.  Catch, however, can only be expressed as suffix. Consequently I suggest dropping the prefixed "try" and use another keyword as suffix that expresses the same as `try` does today, for example `rethrow`. Note the visual consistency of using a suffix for all cases:

```
// Now:
const number = parseU64(str, 10) catch 13;
const number = parseU64(str, 10) catch |err| return err;
const number = try parseU64(str, 10);

// Suggested change:
const number = parseU64(str, 10) catch 13;
const number = parseU64(str, 10) catch |err| return err;
const number = parseU64(str, 10) rethrow;
```

**Comment by andrewrk** [comment]
I'm going to make the judgement call that the status quo syntax and semantics are preferable to this proposal, as they follow existing semantics and patterns of type casting and expression evaluation. `exit(foo)` would not work with Zig's IR system since Zig could not know if `foo` was supposed to be a new error value, or an expression.
