### ISSUE TITLE
Compiler says types of readIntForeign and readIntNative are different, but error message shows they are the same

### ISSUE THREAD

**Issue by zxubian** [ziglang/zig#12892]
### Zig Version

0.9.1 (windows, chocolatey)

### Steps to Reproduce

1. create file repro.zig with following code:

``` zig
const std = @import("std");
pub fn main() anyerror!void {
    const file = try std.fs.cwd().openFile("repro.zig", .{});
    const reader = file.reader();
    const byte = try reader.readByte();
    // this is just so that same_endianness is not known at comptime
    const same_endianness = byte > 16;
    const read_function = if (same_endianness) reader.readIntNative else reader.readIntForeign;
    _ = read_function;
}
```
2.  `zig build repro.zig`

### Expected Behavior

File should compile with no errors.
Further code should be able to use `read_function` and expect it to either be reader.readIntForeign or reader.readIntNative.

If compiler lacks the necessary information to correctly determine that the function types are compatible, then a more explicit error should be shown. Currently, the error states that the types are incompatible, but prints out the same types for both functions, so it is unclear why they are incompatible.

### Actual Behavior

The following compile error occurs:
```
.\repro.zig:7:27: error: incompatible types: '(bound fn(std.io.reader.Reader(std.fs.file.File,std.os.ReadError,std.fs.file.File.read),type) anytype)' and '(bound fn(std.io.reader.Reader(std.fs.file.File,std.os.ReadError,std.fs.file.File.read),type) anytype)'
    const read_function = if (same_endianness) reader.readIntNative else reader.readIntForeign;
                          ^
.\repro.zig:7:54: note: type '(bound fn(std.io.reader.Reader(std.fs.file.File,std.os.ReadError,std.fs.file.File.read),type) anytype)' here
    const read_function = if (same_endianness) reader.readIntNative else reader.readIntForeign;
                                                     ^
.\repro.zig:7:80: note: type '(bound fn(std.io.reader.Reader(std.fs.file.File,std.os.ReadError,std.fs.file.File.read),type) anytype)' here
    const read_function = if (same_endianness) reader.readIntNative else reader.readIntForeign;
```

**Comment by Vexu** [comment]
Runtime coercion of bound functions is not possible and won't be a problem in the future since they have been removed from the language #9484

**Comment by zxubian** [comment]
@Vexu 
Thanks for taking a look at the issue!
Could you please clarify: does this mean that the error above will be fixed once the proposal you linked to is implemented?
Or was I fundamentally using the language incorrectly in some way?
(Sorry, I'm new to zig and not sure what bound functions are in the first place)

**Comment by Vexu** [comment]
Your example will now result in a big compile error
```zig
:8:55: error: no field named 'readIntNative' in struct 'io.reader.Reader(fs.file.File,error{AccessDenied,BrokenPipe,ConnectionResetByPeer,ConnectionTimedOut,InputOutput,IsDir,NotOpenForReading,OperationAborted,SystemResources,Unexpected,WouldBlock},(function 'read'))'
```
And since the function is a comptime only type you can't avoid it with `@TypeOf(reader).readIntNative` so you'll just have to do the call separately:
```zig
    if (same_endianness) {
        _ = reader.readIntNative;
    } else {
        _ = reader.readIntForeign;
    }
```
But if you know whether the number is going to be big or little endian you'll want to use `readIntBig` or `readIntLittle` which will handle this for you.

**Comment by zxubian** [comment]
I see! Thank you for your detailed explanation, this was very helpful!
