### ISSUE TITLE
make std.heap.GeneralPurposeAllocator.deinit return an enum rather than a boolean

### ISSUE THREAD

**Issue by clebs** [ziglang/zig#12906]
**Description**
The current `deinit` method for the general purpose allocator returns a boolean, being true when there is a leak and false otherwise.
This is confusing since one would expect a boolean function to return `true` when successful, unless its name clearly conveys that `true` equals failure.

**Proposal**
Change deinit to return a new error type `std.heap.LeakError!void`, which could be used across the whole stdlib to signal a leak and would benefit from error handling language features.

Also existing `deinit` methods in all other types already have return type `void` and would only need a union should they in the future have possibility for failure.

**Comment by nektro** [comment]
this is in line with programs exiting `0` when there is no error

additionally, `deinit` methods are never allowed to return an error union

**Comment by clebs** [comment]
Yes, @andrewrk mentioned the convention for exit codes in the linked PR. Nevertheless, in my experience this is usually not the case for booleans.

What is the reason to not being allowed to return an error and how is it worse than the current return boolean?

**Comment by nektro** [comment]
from the https://ziglang.org/documentation/master/#Zen

> * Resource allocation may fail; resource deallocation must succeed.

**Comment by nektro** [comment]
`defer std.debug.assert(!gpa.deinit());` is a very nice way to always catch the gpa's warnings

**Comment by InKryption** [comment]
> Resource allocation may fail; resource deallocation must succeed.

An error does not always indicate that a failure to deallocate a resource has occurred, and it certainly would not in this case. All this is, is a debugging tool, and the idea to return an error union to signal a message about something your tool found out is not unthinkable - it just happens that it doesn't work very well with the intended use-case here.

**Comment by tauoverpi** [comment]
> `defer std.debug.assert(!gpa.deinit());` is a very nice way to always catch the gpa's warnings

It does however mean you need to check the doc-comment just to make sure it does what you think it does compared to `gpa.deinit() != .leak`.

This is more to do with bools communicating less than an enum with two states would when the return value isn'tfrom a test such as `contains()` or `isX()`.

**Comment by clebs** [comment]
Very interesting discussion!

Great point with the deferred use. It is the preferred use case for this kind of function, so the way of communicating leaks should be geared towards making deferred `deinit` calls as ergonomic as possible.

In the case of returning error we could catch the error inside the defer as long as we do not return something:
```
// crash if there is a leak
defer gpa.deinit() catch unreachable;

// do something when leak is detected (e.g. test_runner counts leaks)
defer gpa.deinit() catch {
   leaks += 1;
   std.debug.print("Leak detected!");
};

```

**Comment by clebs** [comment]
Hi @andrewrk,

Can I start working on this or do we need to agree on a solution?

As mentioned above, IMHO  the error return proposal is the safest and most idiomatic option.

**Comment by clebs** [comment]
Hi @andrewrk,
being this accepted now, is it ok if I go ahead and work on the proposed solution?

> Very interesting discussion!
> 
> Great point with the deferred use. It is the preferred use case for this kind of function, so the way of communicating leaks should be geared towards making deferred `deinit` calls as ergonomic as possible.
> 
> In the case of returning error we must catch the error inside the defer:
> 
> ```
> // crash if there is a leak
> defer gpa.deinit() catch unreachable;
> 
> // do something when leak is detected (e.g. test_runner counts leaks)
> defer gpa.deinit() catch {
>    std.debug.print("Leak detected!");
> };
> ```
> 
> Only caveat here is that the catch statement/block can not return anything that is not `noreturn`.
> 
> I really like this solution, but the enum approach is also quite good and I would be up for contributing if approved.
