### ISSUE TITLE
Unable to use `undefined` with `struct` instead of primitive

### ISSUE THREAD

**Issue by r00ster91** [ziglang/zig#12911]
### Zig Version

0.10.0-dev.4060+61aaef0b0

### Steps to Reproduce

```zig
//! it shouldn't point here
const Item = struct { field: u8 };

const Thing = struct {
    array: [1]Item,
};

pub fn main() void {
    _ = Thing{ .array = undefined };
}
```

### Expected Behavior

It compiles and runs.

### Actual Behavior

```
$ zig run x.zig
x.zig:9:17: error: value stored in comptime field does not match the default value of the field
    _ = Thing{ .array = undefined };
               ~^~~~~~~~~~~~~~~~~
x.zig:1:1: note: default value set here
//! it shouldn't point here
^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This one might not be a bug and just me misunderstanding something but if I have `Item` set to `u8`, it works, but if I use a `struct` as `Item`, it no longer works and gives me this error, which I find very confusing. Why would I not be able to use `undefined` like this?

There is at least one of these problems here:
1. The note points at the wrong line.
2. The error shouldn't happen.
3. The error should be made more clear. What comptime field is it talking about? Why would this not work? And if I change `array: [1]Item,` to `array: [1]Item = undefined,`, it works. But why can I not do the same from outside? Why do I need to use a default value within the `struct` definition for this to work?

**Comment by nektro** [comment]
`error: value stored in comptime field does not match the default value of the field` doesnt make sense so it seems confused on whats even going on

dont know the issue number but i think there's been others rooted at one-item arrays like you have: `[1]Item` which could be the source of the compiler's confusion in this case

**Comment by nektro** [comment]
for sure 👍
