### ISSUE TITLE
Building Zig from source on windows crashes the compiler

### ISSUE THREAD

**Issue by bpeake13** [ziglang/zig#12925]
### Zig Version

0.10.0-dev.61+9be8396b7

### Steps to Reproduce

Followed instructions for building zig with an older version of zig. Ran this command:
```
..\..\zig+llvm+lld+clang-x86_64-windows-gnu-0.10.0-dev.61+9be8396b7\bin\zig.exe build -p stage3 --search-prefix ..\..\zig+llvm+lld+clang-x86_64-windows-gnu-0.10.0-dev.61+9be8396b7 --zig-lib-dir lib -Denable-stage1 -Dstatic-llvm -Duse-zig-libcxx -Dtarget=x86_64-windows-gnu
```

### Expected Behavior

Compiles zig

### Actual Behavior

Get the following error:
```
Semantic Analysis... comptime_0... thread 14772 panic: zig compiler bug: NeededSourceLocation
Unable to dump stack trace: debug info stripped
```

**Comment by Vexu** [comment]
This is due to #12889, if removing `--zig-lib-dir lib` doesn't fix it then you need to use a newer version.

**Comment by andrewrk** [comment]
@Vexu I observed this crash with a panic handler provided in the root source file that is missing the new parameter

**Comment by Vexu** [comment]
It's probably because of `Sema.addSafetyCheck`.
