### ISSUE TITLE
stage2: error coercing slice to anyopaque

### ISSUE THREAD

**Issue by jacobly0** [ziglang/zig#12957]
### Zig Version

0.10.0-dev.4166+cae76d829

### Steps to Reproduce

```zig
test {
    const slice: []const u8 = "test";
    const pointer: *const anyopaque = &slice;
    _ = pointer;
}
```

### Expected Behavior

As with stage1:
```
All 1 tests passed.
```

### Actual Behavior

```
repro.zig:3:39: error: expected type '*const anyopaque', found '*const []const u8'
    const pointer: *const anyopaque = &slice;
                                      ^~~~~~
repro.zig:3:39: note: pointer type child '[]const u8' cannot cast into pointer type child 'anyopaque'
```

### Use case

This is preventing me from using `std.builtin.Type.StructField.default_value` for a field with a slice type, which in turn is preventing me from using `std.enums.directEnumArrayDefault` with `Data` being a slice.  As a workaround, I can use a struct containing a single slice for `Data` instead.

**Comment by ryoppippi** [comment]
same

**Comment by nektro** [comment]
this should work

```zig
test {
    const slice: []const u8 = "test";
    const pointer: *const anyopaque = slice.ptr;
    _ = pointer;
}
```

zig explicitly disallows implicitly casting double pointers to anyopaque. also slices can be thought of as a pointer but the layout of them is more like a struct that contains a pointer

**Comment by nektro** [comment]
this should also work

```zig
test {
    const slice = "test";
    const pointer: *const anyopaque = slice;
    _ = pointer;
}
```

the default type of `"test"` is `*const [4:0]u8` and so it would coerce just fine

**Comment by jacobly0** [comment]
To expand on the use case, this code triggers the same error
```zig
test {
    const s: @Type(.{ .Struct = .{
        .layout = .Auto,
        .backing_integer = null,
        .fields = &.{.{
            .name = "field",
            .field_type = []const u8,
            .default_value = &"default",
            .is_comptime = false,
            .alignment = @alignOf([]const u8),
        }},
        .decls = &.{},
        .is_tuple = false,
    } }) = .{};
    _ = s;
}
```
And removing the `&`, or trying to set it to various other incorrect things triggers errors similar to #12963.

**Comment by Vexu** [comment]
I think this is working properly and is yet another downside to using `*const anyopaque` to replace `anytype` fields, https://github.com/ziglang/zig/pull/12904#issuecomment-1253114661

You should be able to workaround this with explicit `@ptrCast`s.

**Comment by jacobly0** [comment]
Yeah I was missing the part where it just needs an explicit cast, opened a PR to address how I originally encountered this issue.

**Comment by nektro** [comment]
`error: expected type '*const anyopaque', found '*const []const u8'` is this not an incorrect error?

**Comment by jacobly0** [comment]
Closing as working as intended with #12975 addressing my issue with `std.enums.directEnumArrayDefault`.
