### ISSUE TITLE
LLVM backend hits `unreachable` lowering pointer to comptime field

### ISSUE THREAD

**Issue by omaraaa** [ziglang/zig#12963]
### Zig Version

0.10.0-dev.4060+61aaef0b0

### Steps to Reproduce
```zig
const std = @import("std");

test {
    const T = std.meta.Tuple(&.{struct {}});
    var t: T = undefined;
    inline for (std.meta.fields(T)) |f| {
        var ptr = &@field(t, f.name);
        _ = ptr;
    }
}
```
### Expected Behavior
```
All 1 tests passed.
```
### Actual Behavior
```
error: TODO (LLVM): implement const of pointer type '[TODO fix internal compiler bug regarding dump]' (value.Value.Tag.comptime_field_ptr)
```

**Comment by nektro** [comment]
expected behavior is multiple compile errors

**Comment by omaraaa** [comment]
> expected behavior is multiple compile errors

What would the compile errors be? The code compiles and passes in stage 1.

**Comment by omaraaa** [comment]
Another variation:
```zig
const std = @import("std");

test {
    const T = std.meta.Tuple(&[_]type{struct {}});
    var t: T = undefined;
    inline for (std.meta.fields(T)) |_| {
        var ptr = &t.@"0";
        _ = ptr;
    }
}
```

**Comment by Vexu** [comment]
This is not specific to tuples:
```zig
const std = @import("std");

test {
    const T = struct {
        comptime a: struct{} = .{},
    };
    var t: T = undefined;
    inline for (std.meta.fields(T)) |f| {
        var ptr = &@field(t, f.name);
        _ = ptr;
    }
}
```

**Comment by omaraaa** [comment]
> This is not specific to tuples:
> 
> ```zig
> const std = @import("std");
> 
> test {
>     const T = struct {
>         comptime a: struct{} = .{},
>     };
>     var t: T = undefined;
>     inline for (std.meta.fields(T)) |f| {
>         var ptr = &@field(t, f.name);
>         _ = ptr;
>     }
> }
> ```
This seems like a separate issue that is hitting the same TODO. It should produce a compile error that you can't use T in a runtime context...but it doesn't.

The main issue with tuples/anonStructs is that the logic for zero-sized field pointers in sema is flawed. In `tupleFieldPtr`:
- It checks if the value of a field is comptime.
- Zero-sized fields are comptime since they have zero runtime bits
- Thus it outputs a `comptime_field_ptr` for zero-sized field pointers!

#12977 fixed tuples/@Type structs  zero-sized field pointers for me.

**Comment by Vexu** [comment]
> It should produce a compile error that you can't use T in a runtime context...but it doesn't.

Sure you can, all the operations on them just end up being comptime known since they can only have one possible value.

> * Zero-sized fields are comptime since they have zero runtime bits

Zero-sized fields are comptime since they have only one possible value which is know at comptime.

I think the correct solution is to generate `comptime_field_ptr`s as `undefined` pointers.

**Comment by omaraaa** [comment]
> Zero-sized fields are comptime since they have only one possible value which is know at comptime.

 Yes, for values. But shouldn't a pointer to field have a runtime value, even if it's zero-sized?

```zig
const Foo = struct {
  a: struct{} = .{},
};

// This is fine in stage1 and stage2, no comptime_field_ptr
var foo: Foo = .{};
var ptr = &foo.a;
_ = ptr;

//This doesn't work in stage2, produces comptime_field_ptr
const T = std.meta.Tuple(&[_]type{struct {}});
var t: T = .{};
var ptr2 = &t.@"0";
_ = ptr2;
```

Both are essentially the same, but works while the other doesn't. 

> I think the correct solution is to generate comptime_field_ptrs as undefined pointers.

From what I understood, comptime_field_ptrs should never reach llvm. If is does then there is something wrong in sema.
But I'm not familiar with Zig's codebase, so I might be wrong.

**Comment by Vexu** [comment]
This is also not specific to zero-bit types:
```zig
test {
    const T = struct {
        comptime a: u32 = 2,
    };
    var t: T = undefined;
    var ptr = &t.a;
    _ = ptr;
}
```

> From what I understood, comptime_field_ptrs should never reach llvm.

Pointers to comptime fields should behave same as pointers to container-level variables so that above example should behave same as:
```zig
test {
    const T = struct {
        var a: u32 = 2;
    };
    var ptr = &T.a;
    _ = ptr;
}
```

**Comment by omaraaa** [comment]
Oh, so stage2 allows structs with comptime fields to be a runtime variable. Didn't know that.

> I think the correct solution is to generate comptime_field_ptrs as undefined pointers.

Will this mean that `@fieldParentPtr` will not work for zero-sized fields?

**Comment by Vexu** [comment]
> Oh, so stage2 allows structs with comptime fields to be a runtime variable. Didn't know that.

That has always been allowed, I think you might be confusing comptime fields with fields with comptime only types:
```zig
const S = struct {
    // comptime field
    comptime a: i32 = 2,
    // field with a comptime only type
    b: comptime_int,
};
```
The key difference is that comptime fields are tied to the type while fields with comptime only types are tied to an instance.

> Will this mean that `@fieldParentPtr` will not work for zero-sized fields?

No, but it does mean that `@fieldParentPtr` should disallow comptime fields which is a missing compile error, and that for tuples you'll have to construct the type using `@Type` since the regular syntax does not support making runtime zero-bit fields.

**Comment by Jarred-Sumner** [comment]
Running into this in Bun

**Comment by omaraaa** [comment]
Hi, just an update on this issue.

I tested this issue again on version 0.11.0-dev.3654+2d6d2a1d1 and the TODO is now gone; however, now Zig just crashes without any errors.

I also tried this code:
```zig
const std = @import("std");

test {
    const T = struct {struct {}};
    var t: T = undefined;
    inline for (std.meta.fields(T)) |f| {
        var ptr = &@field(t, f.name);
        _ = ptr;
    }
}

```

Same thing. The compiler just crashes.

**Comment by andrewrk** [comment]
Current status as of `0.11.0-dev.4173+8924f81d8`:

```
thread 727898 panic: reached unreachable code
/home/andy/Downloads/zig/src/codegen/llvm.zig:3697:40: 0x5cbbd28 in lowerValue (zig)
                    .comptime_field => unreachable,
                                       ^
/home/andy/Downloads/zig/src/codegen/llvm.zig:4650:42: 0x665dfe8 in resolveValue (zig)
        const llvm_val = try o.lowerValue(tv.val.toIntern());
                                         ^
/home/andy/Downloads/zig/src/codegen/llvm.zig:4639:47: 0x665dca0 in resolveInst (zig)
        const llvm_val = try self.resolveValue(.{
                                              ^
/home/andy/Downloads/zig/src/codegen/llvm.zig:8612:49: 0x66a03ff in airStore (zig)
        const src_operand = try self.resolveInst(bin_op.rhs);
                                                ^
/home/andy/Downloads/zig/src/codegen/llvm.zig:4838:53: 0x6120bac in genBody (zig)
                .store          => try self.airStore(inst, false),
                                                    ^
/home/andy/Downloads/zig/src/codegen/llvm.zig:1543:19: 0x611aa05 in updateFunc (zig)
        fg.genBody(air.getMainBody()) catch |err| switch (err) {
                  ^
/home/andy/Downloads/zig/src/link/Elf.zig:2583:74: 0x6125289 in updateFunc (zig)
        if (self.llvm_object) |llvm_object| return llvm_object.updateFunc(mod, func_index, air, liveness);
                                                                         ^
/home/andy/Downloads/zig/src/link.zig:575:77: 0x5e8e993 in updateFunc (zig)
            .elf   => return @fieldParentPtr(Elf,   "base", base).updateFunc(module, func_index, air, liveness),
                                                                            ^
/home/andy/Downloads/zig/src/Module.zig:3988:37: 0x5c73e02 in ensureFuncBodyAnalyzed (zig)
            comp.bin_file.updateFunc(mod, func_index, air, liveness) catch |err| switch (err) {
                                    ^
/home/andy/Downloads/zig/src/Compilation.zig:3137:42: 0x5c714b0 in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/andy/Downloads/zig/src/Compilation.zig:3074:30: 0x5ad3973 in performAllTheWork (zig)
            try processOneJob(comp, work_item, main_progress_node);
                             ^
/home/andy/Downloads/zig/src/Compilation.zig:2028:31: 0x5acf6bb in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/andy/Downloads/zig/src/main.zig:3870:24: 0x5afed6e in updateModule (zig)
        try comp.update(main_progress_node);
                       ^
/home/andy/Downloads/zig/src/main.zig:3305:17: 0x5b2e80b in buildOutputType (zig)
    updateModule(comp) catch |err| switch (err) {
                ^
/home/andy/Downloads/zig/src/main.zig:275:31: 0x598ea44 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/home/andy/Downloads/zig/src/main.zig:213:20: 0x598bbc5 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/andy/Downloads/zig/lib/std/start.zig:608:37: 0x598b61e in main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x7fb453f6b24d in ??? (libc.so.6)
Unwind information for `libc.so.6:0x7fb453f6b24d` was not available (error.MissingDebugInfo), trace may be incomplete

???:?:?: 0x7ffd8d1e78df in ??? (???)
Aborted (core dumped)
```

**Comment by perillo** [comment]
Interesting that the compiler crashes with `terminated by signal SIGSEGV (Address boundary error)` when using `llvm` backend and `terminated by signal SIGTRAP (Trace or breakpoint trap)` when using `x86_64` and `c` backends.

**Comment by Vexu** [comment]
This is now an error:
```
a.zig:13:19: error: runtime value contains reference to comptime var
        var ptr = &@field(t, f.name);
                  ^~~~~~~~~~~~~~~~~~
a.zig:13:19: note: comptime var pointers are not available at runtime
```
