### ISSUE TITLE
@alignOf(f64) incorrect on i386

### ISSUE THREAD

**Issue by mlugg** [ziglang/zig#12987]
### Zig Version

0.10.0-dev.4176+6d7b0690a

### Steps to Reproduce

[EDITED - I had a misconception before that the alignment was only 4 in aggregates]

The alignment of `f64` on at least i386 on Linux (possibly other 32-bit platforms too) is 4 bytes, despite having an 8-byte "preferred alignment".

This causes extern structs to be laid out incorrectly in some cases:

`main.zig`:
```zig
const std = @import("std");

const Thing = extern struct {
    x: u32,
    d: f64,
};

extern fn init_thing() Thing;

pub fn main() void {
    const val = init_thing();
    std.log.info("{}", .{val});
}
```

`test.c`:
```c
#include <stdint.h>

struct thing {
  int32_t x;
  double d;
};

struct thing init_thing() {
  return (struct thing){ .x = 0, .d = 1.0 };
}
```

### Expected Behavior

The output is `info: main.Thing{ .x = 0, .d = 1.0e+00 }`, which does happen when built for amd64.

### Actual Behavior

`info: main.Thing{ .x = 0, .d = 5.299808824e-315 }`

**Comment by mlugg** [comment]
Note that one possible workaround for this would be to make translate-c emit `x: f64 align(4)` for `double` fields - this would solve the issue in a way that doesn't require special-casing within the language itself, but is likely to be confusing for people writing their own `extern struct`/`extern union` declarations.

**Comment by ehaas** [comment]
Are you sure `f64` is 8-byte aligned by itself? I believe it should be 4-byte aligned on i386: https://godbolt.org/z/YWM1Mdff7

GCC has a flag `-malign-double` that allows 8-byte alignment for doubles but it breaks ABI compatibility on 32 bit systems: https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html

There's a related issue for incorrect alignment of `long long` on `i386`: https://github.com/ziglang/zig/issues/12453

**Comment by mlugg** [comment]
C11 `_Alignof` is distinct from the `alignof` (GCC) or `__alignof__` (Clang) provided as a compiler extension. The former, by C spec, has to match (or rather, be at least) the required alignment when used in a struct, whereas the latter will give the alignment of the type by itself: https://godbolt.org/z/KaMj1bcqs.

It may actually work okay to just say `@alignOf(double) == 4` anyway - I can't think of any case where this would break. But the reality is definitely at least somewhat more complicated than that.

**Comment by ehaas** [comment]
I think `__alignof__` gives the "preferred" alignment (since Pentium can load a double faster if it's 8-byte aligned) but the ABI alignment is 4 according to this: https://www.uclibc.org/docs/psABI-i386.pdf (table 2.1 on page 8 of the PDF).

**Comment by mlugg** [comment]
Ah, okay, I guess I was mistaken about the purpose of `__alignof__`. In that case, yeah, just having `@alignOf(f64) == 4` would be correct here.
