### ISSUE TITLE
std.testing: make sure decls are inside `test` block

### ISSUE THREAD

**Issue by r00ster91** [ziglang/zig#12998]
I propose making sure that all `pub`lic decls in `std.testing` are made sure of being inside `test` blocks.
The status-quo is that in the docs of the decls in `std.testing` we say "this X is intended to be used only in tests". Why don't we enforce it as well?

The purpose of enforcing it is to prevent mistakes and misuse of `std.testing`'s functionality and utilities in places where you shouldn't use it.
You should never use anything inside `std.testing` as part of your regular app, so why don't we enforce that? We can do that by checking `std.builtin.is_test`.

For example when I was a beginner in Zig I remember I struggled a little between the difference of `std.testing.expect()` and `std.debug.assert()`, so maybe back then I actually used `std.testing.expect()` where I should've actually use `std.debug.assert()`. This would've prevented that.

`std.testing`'s "expect" functions like `expectEqual` or `expect` or `expectEqualStrings` etc. all return test-specific errors like `error.TestExpectedEqual` or `error.TestUnexpectedResult` that shouldn't leak out into regular apps. They should stay within environment of `test` blocks.

Now of course this might actually just end up being too restrictive so that's why I'm collecting feedback here.

## Approach 1

Check that `std.builtin.is_test` inside each function and for every struct (by using `break` and blocks)

Pros: possibly better traces and errors that are easier for the user to understand.
Cons: more internal complexity.

## Approach 2

Change https://github.com/ziglang/zig/blob/9a2f17f9f9dfde9c5438ccb439b727e1e814c4f5/lib/std/std.zig#L87 to
```zig
pub const testing = testing: {
    if (!builtin.is_test)
        @compileError("std.testing can only be used inside `test` blocks");
    break :testing @import("testing.zig");
};
```

Pros: very simple solution.
Cons: traces might be pretty bad. Should we wait for the compiler to improve?

See #12997 for more context, a potential implementation, and some discussions.

**Comment by squeek502** [comment]
I don't think the supposed benefit here is worth it; I think `std.testing` has some legitimate use cases outside of test blocks.

The primary use case I currently use `std.testing` outside of test blocks for is fuzz testing, in which fuzzers use the `main` entrypoint ([example here](https://github.com/squeek502/zig-fuzzing-example/blob/master/test/fuzz.zig), article [here](https://www.ryanliptak.com/blog/fuzzing-zig-code/)). Something like `std.testing.checkAllAllocationFailures` is especially useful for fuzzing ([example here](https://github.com/squeek502/zig-checkAllAllocationFailures-example/blob/master/src/fuzz.zig), article [here, see the *Integrating with fuzz testing* section](https://www.ryanliptak.com/blog/zig-intro-to-check-all-allocation-failures/)).

**Comment by r00ster91** [comment]
Ah, I see. Sure enough! Seems like a pretty good reason to not do this. It is after all too restrictive. I will instead make a PR that extracts some of the other improvements of #12997.

However, what about this?
https://github.com/ziglang/zig/blob/9a2f17f9f9dfde9c5438ccb439b727e1e814c4f5/lib/std/testing.zig#L724
I still don't quite understand why silently returning is a good solution there. Can we remove that? `refAllDeclsRecursive` doesn't do it either.

**Comment by squeek502** [comment]
Unsure about that, my only real opinion is "this shouldn't apply to all of `std.testing`." Certain things being restricted may or may not make sense on a case-by-case basis (i.e. `std.testing.allocator` being restricted makes sense).
