### ISSUE TITLE
@src().file contains "*" on Windows

### ISSUE THREAD

**Issue by mattn** [ziglang/zig#13019]
### Zig Version

0.10.0-dev.4060+61aaef0b0

### Steps to Reproduce

```zig
const std = @import("std");

pub fn main() !void {
    std.debug.print("{s}\n", .{@src().file});
}
```

### Expected Behavior

```
C:\dev\zig-sandbox\test\src\main.zig 
```

### Actual Behavior

```
*:\dev\zig-sandbox\test\src\main.zig 
```

**Comment by mattn** [comment]
Thirdparty libraries using C always fail on build by this issue.
![image](https://user-images.githubusercontent.com/10111/194754044-48a89303-5ff1-4e10-95a1-ddf6275537ed.png)

**Comment by ryoppippi** [comment]
I tested today on `zig-windows-x86_64-0.10.0-dev.4634+c36eb4ede`, and it works fine.

``` sh
C:\Users\ryoppippi\zig-windows-x86_64-0.10.0-dev.4634+c36eb4ede>zig.exe run  ../main.zig
C:\Users\ryoppippi\main.zig
```

**Comment by mattn** [comment]
I tried latest version of zig. Unfortunately, I can't build zigcv yet.

![image](https://user-images.githubusercontent.com/10111/198837343-5ccb17a0-5c35-441d-818c-1a7f5c0878bc.png)

**Comment by kcbanner** [comment]
This seems resolved now that `@src` returns relative paths?

```
>zig run 13019.zig
13019.zig
```
