### ISSUE TITLE
zig c++ does not link installed library properly

### ISSUE THREAD

**Issue by ryoppippi** [ziglang/zig#13018]
### Zig Version

0.10.0-dev.4198+5e0d8a435

### Steps to Reproduce

```a.cpp
#include <iostream>
#include <opencv2/features2d.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/imgproc.hpp>

using namespace std;
using namespace cv;

int main(int argc, char *argv[]) {
  Mat img = imread("test_image.jpg", IMREAD_GRAYSCALE);

  Ptr<BRISK> detector = BRISK::create();
  std::vector<KeyPoint> keypoints;
  detector->detect(img, keypoints);

  return EXIT_SUCCESS;
}
```
```sh
docker run -it --rm -v $(pwd):/data -w /data    gocv/opencv:4.6.0-arm64 bash
root@93dcd40c60b9:/data# ./zig-linux-aarch64-0.10.0-dev.4198+5e0d8a435/zig c++ a.cpp  -I/usr/local/include/opencv4 `pkg-config --libs opencv4`
```

### Expected Behavior

We can compile it like we use g++ command
```sh
root@93dcd40c60b9:/data# g++ a.cpp  -I/usr/local/include/opencv4 `pkg-config --libs opencv4`
root@93dcd40c60b9:/data#
```

### Actual Behavior

```
LLD Link... ld.lld: error: undefined symbol: cv::imread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int)
>>> referenced by a.cpp:11
>>>               /root/.cache/zig/o/808fdce8146e12957fef27045d20a1c4/a.o:(main)
```

**Comment by ryoppippi** [comment]
I tested on x86_64 and got same result

**Comment by kassane** [comment]
Have you tried adding the `-lc` flag?

**Comment by ryoppippi** [comment]
@kassane 
Thank you for your advice.
Actually, it still does not work.
```sh
root@4730085a2cb3:/data# ./zig-linux-aarch64-0.10.0-dev.4198+5e0d8a435/zig c++ a.cpp  -I/usr/local/include/opencv4 `pkg-config --libs opencv4` -lc -lc++
LLD Link... ld.lld: error: undefined symbol: cv::imread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int)
>>> referenced by a.cpp:11
>>>               /root/.cache/zig/o/808fdce8146e12957fef27045d20a1c4/a.o:(main)
```

**Comment by kassane** [comment]
>Thank you for your advice.
>Actually, it still does not work. 

Hi @ryoppippi , thanks!

I have run some more tests today.
The error is not caused by zig, but by incompatibility with libc++ (llvm). Had the same error with conventional clang using libc++ but all ok with libstdc++.

I suggest, maybe recompile opencv and its dependencies using libc++.

```bash
clang++ a.cpp -Wall -Oz `pkg-config --libs opencv4` `pkg-config --cflags opencv4` -stdlib=libc++ -o ocv_test
/usr/bin/ld: /tmp/opencv2_test-095360.o: na função "main":
opencv2_test.cpp:(.text+0x3d): referência não definida para "cv::imread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)"
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

### More info
https://github.com/ziglang/zig/wiki/Troubleshooting-Build-Issues#dual-abi-linking

**Comment by ryoppippi** [comment]
@kassane 
Thank you for your investigation.
 I may try to recompile opencv with zig c++

**Comment by kassane** [comment]
> When I compile opencv with zig compiler, the opencv binary is toooo slow so the test programs do not finish

Wow! During the build did you disable the `zig cc` sanitizers?
e.g.: `fno-sanitize=all`

You didn't need to rebuild hdf5, right?

**Comment by ryoppippi** [comment]
@kassane 
idk why but when I tried to rebuild with `make` instead of `ninja`, it works!
maybe the zigcv CI will work fine soon

**Comment by ryoppippi** [comment]
Finally, all CI works! Thank you so much!!!!!
@kassane 
https://github.com/ryoppippi/zigcv
