### ISSUE TITLE
Wrong caret location on `@panic()` and `@errorReturnTrace()`

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#13020]
### Zig Version

0.10.0-dev.4192+c75e8f361

### Steps to Reproduce

Write some code that produces a runtime error or panic in a line with tabs, like so:
```zig
pub fn main() void {
	@panic("");
}
```
```zig
const std = @import("std");

pub fn someFunction() !void {
	_ = try std.math.mul(u32, std.math.maxInt(u32), 2);
}

pub fn main() void {
	 someFunction() catch {
		if(@errorReturnTrace()) |trace| {
			std.log.err("Trace: {}", .{trace});
		}
	};
}
```

### Expected Behavior

The caret should be at the location of the error, which is correctly handled for compiler errors(the tabs are converted to spaces while printing the source line which is good solution):
```zig
pub fn main() void {
	.
}
```
```
$ zig run test.zig
test.zig:2:2: error: expected statement, found '.'
 .
 ^
```

### Actual Behavior

The caret is pointing at the location where the error would be, if the tab was a space.

First example output:
```
thread 7137 panic: 
./test.zig:2:2: 0x210093 in main (test)
	@panic("");
 ^
```
Second example output:
```
error: Trace: 
[...]
./test.zig:4:6: 0x211ce9 in someFunction (test)
	_ = try std.math.mul(u32, std.math.maxInt(u32), 2);
     ^
```

**Comment by Vexu** [comment]
As far as I know there is no good way to get the desired tab width without an environment variable or something.

~~Solution: don't use tabs.~~

**Comment by IntegratedQuantum** [comment]
> As far as I know there is no good way to get the desired tab width without an environment variable or something.
> 
> ~Solution: don't use tabs.~

I don't care about whether the number of spaces matches the tab width. All I care about is that the caret matches with the line printed above.
And there are two solutions for that
- Print tabs in the caret line, replacing some spaces
- Replace all tabs from the source line with spaces

The later is already being used in zig for regular compiler errors by the way:
https://github.com/ziglang/zig/blob/34835bbbcfe81cc87e823d14dc9b25e698ad5edc/src/Compilation.zig#L434-L437

**Comment by nektro** [comment]
option 2 is expected to be done by automatic use of `zig fmt`

**Comment by IntegratedQuantum** [comment]
> option 2 is expected to be done by automatic use of `zig fmt`

I think you misunderstood me. When I said
> Replace all tabs from the "source line" with spaces

I was refering to
​ ​ ​ ​ "the line that comes from the source code and gets printed above the line containing the caret"
and **not**
​ ​ ​ ​ "the line of code inside the actual source file"

I thought this was obvious from the context.
If I really just wanted tabs to be replaced in my source file, I wouldn't use tabs in the first place and wouldn't have found this issue.
