### ISSUE TITLE
stage2: `if` allows `usize` in condition, if the payload is discarded

### ISSUE THREAD

**Issue by topolarity** [ziglang/zig#13023]
### Zig Version

0.10.0-dev.4189+17eea918a

### Steps to Reproduce

```zig
test {
    if (@as(usize, 5)) |_| {}
}
```

### Expected Behavior

Stage 1 does the right thing:
```zig
./test.zig:3:9: error: expected optional type, found 'usize'
    if (@as(usize, 5)) |_| {
        ^
```

### Actual Behavior

```
All 1 tests passed.
```

**Comment by nektro** [comment]
this is because of the `@as` not `usize`

**Comment by Vexu** [comment]
This issue also applies to error union conditions and while loops and has nothing to do with builtin functions and everything to do with `is_non_err` and `is_non_null` being valid for all types.
