### ISSUE TITLE
Allow assert() with custom error message

### ISSUE THREAD

**Issue by mdsteele** [ziglang/zig#1303]
Many other languages allow adding a custom error message to assertions, to provide better context if the assertion fails.  For example:

```zig
assert(x > 0, "x must be positive, but it was {} instead", x);
```

I've been finding myself missing this in Zig.  I don't know whether it's possible to support both `assert(cond)` and `assert(cond, fmt, ...)` with the same function name, but if not, then we could have, say, `assert(cond)` and `assertMsg(cond, fmt, ...)`.

**Comment by andrewrk** [comment]
I believe this is related to #1304. One consideration here is whether the assert is going to invoke `unreachable` or `@panic`. They're the same thing in Debug and ReleaseSafe mode, but in ReleaseFast and ReleaseSmall modes, `unreachable` is a hint to the optimizer (because it invokes undefined behavior) and `@panic` is guaranteed to abort.

**Comment by PavelVozenilek** [comment]
There's precedent for such desirable feature. Long, long ago someone came up with idea of advanced assert in C++. Basically, when assert fires, it could _also_ print multiple interesting values.
http://www.drdobbs.com/cpp/enhancing-assertions/184403745

It was very clever, but unfortunately, it severely impacted compilation time, so an effort to get it into Boost was abandoned.

Some notes about Zig implementation:

1. Such assert should evaluate its second and next parameters lazily, to avoid performance/memory impact. 

    `   assert(x > 0, "foo = {}", foo());
    `   

   would became (in C like-code):

    ```
   #if ASSERTS_ENABLED
    if (x <= 0) {
      assert(false, "foo = {}", foo());
    }
   #endif

   ```






2. Tested values should print out implicitly:

    `assert(foo() < bar()); 
    `

    would be  equivalent of:

    ```
   #if ASSERTS_ENABLED
    int  foo_result, bar_result;
    foo_result = foo();
    bar_result = bar();
    assert(foo_result < bar_result, "foo = {}, bar = {}", foo_result, bar_result);
   #endif

   ```


3. If some function is called twice, the compiler should rearrange the code to call it only once:

    `assert(foo() > 0, "foo() returned ", foo()); 
    `


    should became:

    ```
   #if ASSERTS_ENABLED
    int  foo_result;
    foo_result = foo();
    assert(foo_result > 0, "foo returned", foo_result);
   #endif


4. It should be possible to omit the formatting string altogether:

    `assert(x > 0, y, z); 
    `

    should  automagically transform itself into:

    `assert(x > 0, "x = {}, y = {}, z = {}", x, y, z);
    `

**Comment by andrewrk** [comment]
This is solved in c2db077574be841da586fa62d67619c901dd535d which makes the distinction between `std.debug.assert` and `std.testing.expect`. The `testing` module can have any number of handy functions, including ones that do var args printing.

**Comment by cmpute** [comment]
> I believe this is related to [#1304](https://github.com/ziglang/zig/issues/1304). One consideration here is whether the assert is going to invoke `unreachable` or `@panic`. They're the same thing in Debug and ReleaseSafe mode, but in ReleaseFast and ReleaseSmall modes, `unreachable` is a hint to the optimizer (because it invokes undefined behavior) and `@panic` is guaranteed to abort.

If this is the concern, what about an abort implementation that print error message in Debug and ReleaseSafe mode, and ignore the error message in other modes? This still makes the assert function much more useful without changing the actual behavior in release modes.

**Comment by cmpute** [comment]
implementation like this:
```zig
pub fn assertEx(ok: bool, comptime message: []const u8, args: anytype) void {
    if (!ok) {
        // assertion failure
        if (runtime_safety) {
            panicExtra(@returnAddress(), message, args);
        } else {
            unreachable;
        }
    }
}
```
