### ISSUE TITLE
stage2 crash with global ArrayList

### ISSUE THREAD

**Issue by billzez** [ziglang/zig#13068]
### Zig Version

0.10.0-dev.4217+9d8cdb855

### Steps to Reproduce

```
const std = @import("std");

pub const allocator = std.heap.page_allocator;
var list = std.ArrayList(u32).init(allocator);

pub fn main() void {
    list.items.len = 0;
}
```

### Expected Behavior

Does not crash.

### Actual Behavior

Compiles fine with stage1, but not stage2:

```
$ zig build-exe main.zig 
Trace/breakpoint trap
```

Crash disappears if `list.items.len = 0` is replaced with `list.shrinkRetainingCapacity(0)`.

**Comment by schmee** [comment]
Reduced test case:

```zig
const S = struct {
    slice: []u8,
};

var s = S{
    .slice = &[_]u8{}
};

pub fn main() void {
    s.slice.len = 0;
}
```
