### ISSUE TITLE
Add zig to linguist

### ISSUE THREAD

**Issue by thedrow** [ziglang/zig#1308]
[linguist](https://github.com/github/linguist)  is used on GitHub.com to detect blob languages, ignore binary or vendored files, suppress generated files in diffs, and generate language breakdown graphs.

Having Zig as a known language for Github will help it get more publicity if someone develops a project in zig.

**Comment by isaachier** [comment]
Already done: https://github.com/github/linguist/pull/4005.

**Comment by andrewrk** [comment]
let me know how many zig github repositories there are if you do the "harvester" thing mentioned in https://github.com/github/linguist/pull/4005#issuecomment-393824080
