### ISSUE TITLE
`cannot assign to constant` for zero-sized top-level `var`

### ISSUE THREAD

**Issue by r00ster91** [ziglang/zig#13092]
### Zig Version

0.10.0-dev.4247+3234e8de3

### Steps to Reproduce

```zig
const Thing = struct {};

var thing: Thing = undefined;

pub fn main() void {
    thing = Thing{};
}
```

### Expected Behavior

Successful compile.

### Actual Behavior

```
$ zig run x.zig
x.zig:25:18: error: cannot assign to constant
    thing = Thing{};
            ~~~~~^~
```

~~This looks like a regression.~~
Looks less severe now considering that it only happens with zero-sized types.

**Comment by leecannon** [comment]
I think this might be another problem with the same underlying cause as #12275

**Comment by r00ster91** [comment]
Not sure if I should close this as a duplicate so I'll just leave it open for now. My code looks a bit more simplified.

**Comment by r00ster91** [comment]
Seems better to close.
