### ISSUE TITLE
stage2: `const` @Vector initialized with literal is not `comptime`

### ISSUE THREAD

**Issue by topolarity** [ziglang/zig#13106]
### Zig Version

0.10.0-dev.4254+7f508480f

### Steps to Reproduce

```zig
test {
    const vec: @Vector(2, f16) = [2]f16{ 1.5, 3.5 };
    if (vec[0] != 1.5)
        @compileError("vec should be comptime");
}
```

### Expected Behavior

Test should pass in stage2.

### Actual Behavior

Passes with `-fstage1`. Fails with `-fno-stage1`.

**Comment by Vexu** [comment]
Works for me with a slightly older version.

**Comment by topolarity** [comment]
Updated the test. This one reproduces for me on current master (7f508480f)

**Comment by kkHAIKE** [comment]
another case cause same issue:
```zig
const vec: [2]f16 = [2]f16{ 1.5, 3.5 };
if (vec[0] != 1.5)
   @compileError("vec should be comptime");
```

this form ok
```
const vec = [2]f16{ 1.5, 3.5 };
if (vec[0] != 1.5)
    @compileError("vec should be comptime");
```

**Comment by nektro** [comment]
passes for me on `0.12.0-dev.1836+dd189a354`
