### ISSUE TITLE
powerpcle build fails

### ISSUE THREAD

**Issue by andreiw** [ziglang/zig#13110]
### Zig Version

0.9.1_2 (via home-brew)

### Steps to Reproduce

src/main.zig:

pub fn _start() anyerror!void {
}

build.zig:

const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    // Standard target options allows the person running `zig build` to choose
    // what target to build for. Here we do not override the defaults, which
    // means any target is allowed, and the default is native. Other options
    // for restricting supported target set are available.
    const target = b.standardTargetOptions(.{});

    // Standard release options allow the person running `zig build` to select
    // between Debug, ReleaseSafe, ReleaseFast, and ReleaseSmall.
    const mode = b.standardReleaseOptions();

    const exe = b.addExecutable("ppcle_text", "src/main.zig");
    exe.setTarget(target);
    exe.setBuildMode(mode);
    exe.install();
    exe.setTarget(.{
        //
        // build fine if cpu_arch is powerpc
        //
        .cpu_arch = .powerpcle,
        .os_tag = .freestanding,
        .abi = .none,
        .cpu_model = .{ .explicit = &std.Target.powerpc.cpu.@"604e" },
    });

    const run_cmd = exe.run();
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| {
        run_cmd.addArgs(args);
    }

    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);

    const exe_tests = b.addTest("src/main.zig");
    exe_tests.setTarget(target);
    exe_tests.setBuildMode(mode);

    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&exe_tests.step);
}

### Expected Behavior

I expect build to succeed when cpu_arch = .powerpcle, just as it succeeds for the big-endian .powerpc

### Actual Behavior

andreiw@andreiw-m1 ppcle_text % zig build
TODO implement mapping for c_longdoublethread 1261268 panic: 
Unable to dump stack trace: debug info stripped
ppcle_text...The following command terminated unexpectedly:
/opt/homebrew/Cellar/zig/0.9.1_2/bin/zig build-exe /Users/andreiw/src/ppcle_text/src/main.zig --cache-dir /Users/andreiw/src/ppcle_text/zig-cache --global-cache-dir /Users/andreiw/.cache/zig --name ppcle_text -target powerpcle-freestanding-none -mcpu 604e --enable-cache 
error: the following build command failed with exit code 6:
/Users/andreiw/src/ppcle_text/zig-cache/o/224f454c023223d989de9647b4b5e7eb/build /opt/homebrew/Cellar/zig/0.9.1_2/bin/zig /Users/andreiw/src/ppcle_text /Users/andreiw/src/ppcle_text/zig-cache /Users/andreiw/.cache/zig
andreiw@andreiw-m1 ppcle_text %

**Comment by nektro** [comment]
do you get the same result with master?

**Comment by andrewrk** [comment]
I believe @topolarity fixed this recently. Leaving open until confirmation.
