### ISSUE TITLE
Segmentation fault using @panic in an expression

### ISSUE THREAD

**Issue by DomWilliams0** [ziglang/zig#13112]
### Zig Version

0.10.0-dev.4253+fa9327ac0

### Steps to Reproduce

```zig
fn nice(a: u32, b: u32) bool {
    return a == 5 or b == 2 or @panic("oh no");
}

test "crash" {
    _ = nice(2, 3);
}
```

### Expected Behavior

Should compile fine.

### Actual Behavior

Compiler segfaults with stage2
```
$ zig test src/main.zig --test-no-exec -fstage1
$ zig test src/main.zig --test-no-exec -fno-stage1
LLVM Emit Object... zsh: segmentation fault (core dumped)  zig test src/main.zig --test-no-exec -fno-stage1
```

**Comment by mov-rax** [comment]
After running the code above using version `0.10.0-dev.4423+5127dae7a` I have found additional information printed by the compiler: 
```
Terminator found in the middle of a basic block!
label %Else2
PHINode should have one entry for each predecessor of its parent basic block!
  %5 = phi i1 [ true, %Then1 ], !dbg !4203
```

After looking at the `--verbose-llvm-ir` with and without `-fstage1` I have found the following difference that seems to cause this issue in stage2 but not in stage1 in the block that triggers a panic:

stage1:
```llvm
BoolOrFalse1:                                     ; preds = %BoolOrTrue
  %ret_addr = alloca %"?usize", align 8, !dbg !18337
  store %"?usize" { i64 undef, i1 false }, ptr %ret_addr, align 8, !dbg !18337
  call fastcc void @std.builtin.default_panic(ptr @373, ptr null, ptr %ret_addr), !dbg !18337
  unreachable, !dbg !18337
```
stage2:
```llvm
Else2:                                            ; preds = %Block
  call fastcc void @builtin.default_panic(ptr @main.nice__anon_3845, i64 5, ptr null, ptr @19), !dbg !4203
  unreachable, !dbg !4203
  br label %Block3, !dbg !4203
```
In the stage2 block it adds in an unneeded branch to `Block3` which creates a new predecessor that is not accounted for in its `phi` instruction (while it is noted in a generated comment):
```llvm
Block3:                                           ; preds = %Else2, %Then1
  %5 = phi i1 [ true, %Then1 ], !dbg !4203
  ret i1 %5, !dbg !4201
```

The most obvious fix to me would be to find out where that branch gets inserted, which should fix the issue.
