### ISSUE TITLE
`std.mem.copy` is significantly slower than `@memcpy`/`c.memcpy`

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#13146]
### Zig Version

0.10.0-dev.4217+9d8cdb855

### Steps to Reproduce

`zig init-exe`
Add `exe.linkLibC();` to `build.zig`
Replace `main.zig` with:
```
const std = @import("std");

const c = @cImport({
    @cInclude("string.h");
});

pub noinline fn copy(dest: []u8, src: []const u8) void {
    std.mem.copy(u8, dest, src);
    //_ = c.memcpy(dest.ptr, src.ptr, dest.len);
    //@memcpy(dest.ptr, src.ptr, dest.len);
}

pub fn main() !void {
    var testArray1: []u8 = try std.heap.page_allocator.alloc(u8, 1 << 30); // 1 GiB
    var testArray2: []u8 = try std.heap.page_allocator.alloc(u8, 1 << 30); // 1 GiB
    var t1 = std.time.milliTimestamp();
    copy(testArray1, testArray2);
    var t2 = std.time.milliTimestamp();
    std.log.err("Time: {}", .{t2-t1});
}
```
Run the thing with `zig build run -Drelease-fast=true` while testing the 3 implementations in the `copy()` function by uncommenting the corresponding line.

### Expected Behavior

All 3 variants should be equally fast.

### Actual Behavior

`std.mem.copy` is about 2 times slower.
```
$ zig build run -Drelease-fast=true
error: Time: 103                                 ← @memcpy
$ zig build run -Drelease-fast=true
error: Time: 103                                 ← c.memcpy
$ zig build run -Drelease-fast=true
error: Time: 207                                 ← std.mem.copy
```
This is even worse in debug:
```
$ zig build run
error: Time: 98                        ← @memcpy
$ zig build run
error: Time: 98                        ← c.memcpy
$ zig build run
error: Time: 4924                      ← std.mem.copy
```
In stage1 it's behaving a bit weird:
```
$ zig build run -Drelease-fast=true -fstage1
error: Time: 533                  ← @memcpy
t$ zig build run -fstage1
error: Time: 105                  ← @memcpy somehow faster in debug?
$ zig build run -Drelease-fast=true -fstage1
error: Time: 2132                 ← std.mem.copy is also significantly slower than in stage2
```

​

Are there any particular reasons why `std.mem.copy` isn't just calling `@memcpy` in the background?

**Comment by nektro** [comment]
the source explains why that might be. not sure if thats the only reason

https://github.com/ziglang/zig/blob/0b47e69/lib/std/mem.zig#L211-L222

**Comment by IntegratedQuantum** [comment]
If this is just about overlapping memory there could also just be an if statement that checks if the memory overlaps and only use @​memcpy when that's not the case.
Or it could be split into two functions `copyWithOverlap()/copyWithOverlapBackwards()` and `copyWithoutOverlap()`.

**Comment by sus-impost0r** [comment]
In C, `memcpy` does not allow its arguments to overlap, while `memmove` does.
Would the equivalent change (`mem.copy` disallows overlap, `mem.move` is introduced and allows overlap) be welcome in the standard library?
In addition, the current `copy` implementation could be optimized by copying larger integers without compromising overlap safety, as far as I understand.

**Comment by IntegratedQuantum** [comment]
> In addition, the current `copy` implementation could be optimized by copying larger integers as opposed to bytes without compromising overlap safety, as far as I understand.

I tried a hacky implementation of that and it doesn't seem to make a difference:
```zig
pub fn mem_copy_bigger_int(comptime T: type, dest: []T, source: []const T) void {
    std.mem.copy(u64, @ptrCast([*]u64, @alignCast(@alignOf(u64), dest.ptr))[0..dest.len/8], @ptrCast([*]const u64, @alignCast(@alignOf(u64), source.ptr))[0..source.len/8]);
}
```

```
Time: 176     ← std.mem.copy
Time: 177     ← mem_copy_bigger_int
```
I also tried different integer sizes(u32, u128, u256), but the results stay the same.

This does increase debug performance though, but that's not the main issue here.

**Comment by Vexu** [comment]
With the new for loop syntax all three perform similarly on my machine:
```
error: Time: 206 # std.mem.copy
error: Time: 203 # c.mempcy
error: Time: 204 # @memcpy
```
