### ISSUE TITLE
Packed union inside of a packed struct causes LLVM error

### ISSUE THREAD

**Issue by WiseroOrb** [ziglang/zig#13149]
### Zig Version

0.10.0-dev.4324+c23b3e6fd

### Steps to Reproduce

Simply define a packed struct with a packed union as a field like this.
```zig
const std = @import("std");

const TestStruct =  packed struct {
    a: u32,
    b:  packed union {
        b1: u32,
        b2: i32,
    }
};

pub fn main() void{
    const c = TestStruct{.a = 10, .b = .{.b2= -10}};
    std.debug.print("{}\n", .{c.b.b2});
}
``` 
[main.zip](https://github.com/ziglang/zig/files/9780575/main.zip)

### Expected Behavior

It compiles correctly in release fast, with `zig build-exe src/main.zig -O ReleaseFast` 

### Actual Behavior

However I get the following error when compiling simply with `zig build-exe src/main.zig` 

`LLVM Emit Object... LLVM ERROR: Unsupported expression in static initializer: or (i64 shl (i64 zext (i32 bitcast ({ i32 } { i32 -10 } to i32) to i64), i64 32), i64 10)
`

**Comment by Vexu** [comment]
Fixed by #13479
