### ISSUE TITLE
Deflate compressor implementation bug

### ISSUE THREAD

**Issue by Guigui220D** [ziglang/zig#13144]
### Zig Version

0.10.0-dev.4280+c3d67c5c4

### Steps to Reproduce

Hello! 
I have a set of data that gets incorrectly compressed by the deflate implementation of the std. 
I think this is an implementation bug because it happens in both stage1 and 2.

I made this test to minimalize after a lot of investigation in my png encoder. It compresses the file then decompresses it.
```zig
test "custom test" {
    const deflate = std.compress.deflate;

    var alloc = std.heap.page_allocator;

    var file = @embedFile("filtered.bin");

    var fifo = std.fifo.LinearFifo(u8, .Dynamic).init(alloc);

    {   // Compress all of "file" into fifo
        var compressor = try deflate.compressor(alloc, fifo.writer(), .{});
        defer compressor.deinit();
        
        try compressor.writer().writeAll(file);
        try compressor.flush();
    }

    {
        var decompressor = try deflate.decompressor(alloc, fifo.reader(), null);
        defer decompressor.deinit();

        // Unexpected end of stream
        var buf = try decompressor.reader().readAllAlloc(alloc, std.math.maxInt(usize));
        defer alloc.free(buf);
    }
}
``` 

I really hope this can get fixed fast because zigimg's png capabilities depend on it :pray:
You will find the data that fails this test, "filtered.bin" inside this zip: [filtered.zip](https://github.com/ziglang/zig/files/9766753/filtered.zip). Btw this is data from a real case, I didn't try to reduce it.

### Expected Behavior

Data should be read correctly by the decompressor

### Actual Behavior

The encountered error is 
```
Test [1/1] test.custom test... FAIL (UnexpectedEndOfStream)
/snap/zig/5778/lib/std/io/reader.zig:233:31: 0x4d683a in readByte (test)
            if (amt_read < 1) return error.EndOfStream;
```
And it happens when reading all from the decompressor, but I know it's not a decompressor bug because all zlib decompressors/deflate decompressors/png decoders i've tried say the same thing: incomplete data, truncated data, unexpected end of stream...

**Comment by squeek502** [comment]
Thanks for reporting this! I should have found this via fuzzing (https://github.com/ziglang/zig/pull/10552#issuecomment-1019922257) but only just now realized that I was throwing away the error when decompressing in the 'roundtrip' fuzzer:

https://github.com/squeek502/zig-std-lib-fuzzing/blob/master/fuzzers/deflate-roundtrip.zig#L38-L40

Whoops!

Will fix that and re-run the fuzzer and will almost certainly be able to get a minimized reproduction of this bug (and possibly find others that were missed).

**Comment by squeek502** [comment]
Okay, I figured out the issue. The bug is present in your test case because you are not calling [`compressor.close()`](). Adding:

```zig
        try compressor.close();
```

after `try compressor.flush();` fixes your test case.

Whether or not `close()` *should* be required here is something I don't have an answer for. At the very least it's poorly documented (none of the doc comments mention `close` at all), and it's especially unclear if `close` being required here is a bug or if it's part of the design of Compressor.

cc @hdorio

**Comment by nektro** [comment]
odd, the only difference between `.flush()` and `.close()` is the call to `self.hm_bw.writeStoredHeader` which sends false and true respectively

**Comment by hdorio** [comment]
@Guigui220D you can see an example of how to use the compressor in the tests here:

https://github.com/ziglang/zig/blob/f5f28e0d2c49d5c62914edf0bff8f1941eef721f/lib/std/compress/deflate/compressor.zig#L1077-L1080

> after `try compressor.flush();` fixes your test case (and I believe makes the `flush` redundant).

`flush` is not necessary.

> Whether or not `close()` _should_ be required here is something I don't have an answer for. At the very least it's poorly documented (none of the doc comments mention `close` at all), and it's especially unclear if `close` being required here is a bug or if it's part of the design of Compressor.

`close()` is required when you have no more data to feed the compressor and want to end the compressed stream.

Adding notes about `close()` and `deinit()` in the doc is a good idea (or adding some usage examples)

**Comment by Guigui220D** [comment]
Thanks @hdorio @squeek502 that was the problem and it fixed my test and the png encoder ^^ i was really convinced flush and deinit were enough
Should I close this issue or leave it open for the documentation issue?

**Comment by squeek502** [comment]
Leave it open, the documentation definitely needs to be improved here.

**Comment by nektro** [comment]
`.flush()` is used as the 'final' function in many other similar apis across the stdlib. perhaps it should be made private and/or renamed so that `.close` can be called flush

**Comment by ianic** [comment]
In the current implementation I tried to explain difference between `flush` and `finish` (previously `close`). They both have their usage although `flush` only in special cases. 

`close`
> Completes deflate bit stream by writing any pending data as deflate
> final deflate block. HAS to be called once all data are written to
> the compressor as a signal that next block has to have final bit
> set.
>

`flush`
> Flushes internal buffers to the output writer. Outputs empty stored
> block to sync bit stream to the byte boundary, so that the
> decompressor can get all input data available so far.
>
> It is useful mainly in compressed network protocols, to ensure that
> deflate bit stream can be used as byte stream. May degrade
> compression so it should be used only when necessary.
>
> Completes the current deflate block and follows it with an empty
> stored block that is three zero bits plus filler bits to the next
> byte, followed by four bytes (00 00 ff ff).
>

Hopefully this can be closed now.

**Comment by hdorio** [comment]
> Leave it open, the documentation definitely needs to be improved here.

@Vexu @Guigui220D This can be closed now that the new Standard Library Documentation shows the documentation for the [flush function](https://ziglang.org/documentation/master/std/#std.compress.flate.deflate.Deflate.flush).

![flush-doc](https://github.com/ziglang/zig/assets/110615/37b09403-1d95-44b2-9de8-c9100c434d02)

**Comment by Vexu** [comment]
`close` was removed in #18923
