### ISSUE TITLE
ability to set enum(union) active field based on comptime known field name

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1315]
Currently we have [@field](https://ziglang.org/documentation/master/#field) for doing field access expressions when the field name is a comptime known slice of bytes. However this cannot be used to set the active field of a tagged union, because the syntax to choose the active union field is:
`x = UnionName { .FieldName = value };`
This is not a field access expression, so it cannot be done based on a comptime `field_name` slice.

I propose `@unionInit` for this purpose:
`fn @unionInit(comptime Union: type, comptime active_field_name: []const u8, value: var) Union`
`x = @unionInit(UnionName, field_name, value);`

**Comment by bheads** [comment]
Why cant you just say:
```C
var x: UnionName = value;
```

**Comment by andrewrk** [comment]
Because there could be multiple union fields with the same type as `value`. However we do have this related proposal: #995

**Comment by andrewrk** [comment]
I marked this as "help wanted" for people who were asking for smaller, well-defined contribution tasks.

**Comment by rbscott** [comment]
@andrewrk Any chance you can point me in the right direction to start looking at this? I would like to contribute, especially if it is a smaller, well-defined contribution task.

**Comment by andrewrk** [comment]
Thanks @rbscott for the pull request. I know it took a long time for me to get to it.

I added documentation and integrated it with result location semantics, and then merged it into master.

Here's an example where you can see it participating in result location semantics:

```zig
export fn entry() void {
    var x = @unionInit(U, "Two", [_]Foo{ foo(), foo() });
}

fn foo() Foo {
    return Foo{ .a = 1 };
}

const U = union(enum) {
    One: i32,
    Two: [2]Foo,
};

const Foo = struct {
    a: i32,
};
```

```llvm
define void @entry() #2 !dbg !40 {
Entry:
  %x = alloca %U, align 4
  %0 = getelementptr inbounds %U, %U* %x, i32 0, i32 1, !dbg !61
  store i1 true, i1* %0, !dbg !61
  %1 = getelementptr inbounds %U, %U* %x, i32 0, i32 0, !dbg !61
  %2 = bitcast { i32, [4 x i8] }* %1 to [2 x %Foo]*, !dbg !61
  %3 = getelementptr inbounds [2 x %Foo], [2 x %Foo]* %2, i64 0, i64 0, !dbg !62
  call fastcc void @foo(%Foo* sret %3), !dbg !62
  %4 = getelementptr inbounds [2 x %Foo], [2 x %Foo]* %2, i64 0, i64 1, !dbg !63
  call fastcc void @foo(%Foo* sret %4), !dbg !63
  call void @llvm.dbg.declare(metadata %U* %x, metadata !44, metadata !DIExpression()), !dbg !64
  ret void, !dbg !65
```

You can see that the `foo()` function calls directly write their result directly into the result location.

**Comment by s-ol** [comment]
Using `inline else` in switch statements its easy to obtain a comptime tag value (as enum value, not name slice). How are these supposed to be used in contexts like this?

It's probably ok (because comptime) but rather unsightly to use `@unionInit(U, @tagName(tag))` or `@field(u, @tagName(tag))` to instantiate / index a union by a comptime-known tag value.
