### ISSUE TITLE
`@addWithOverflow` with vectors doesn't work when they are from functions arguments

### ISSUE THREAD

**Issue by DiskPoppy** [ziglang/zig#13201]
### Zig Version

0.10.0-dev.4418+99c3578f6

### Steps to Reproduce

To illustrate something like this:
```zig
const V = @Vector(2, u8);
fn addVec(_: V, _: V) @Vector(2, bool) {
    var result: V = undefined;
    return @addWithOverflow(V, V{ 2, 4 }, V { 6, 7 }, &result);
}
```
works fine,
while the following:
```zig
const V = @Vector(2, u8);
fn addVec2(x: V, y: V) @Vector(2, bool) {
    var result: V = undefined;
    return @addWithOverflow(V, x, y, &result);
}
```
behaves very oddly

### Expected Behavior

For it to compile normally

### Actual Behavior

There is this following message:
`error: expected type 'bool', found 'u1'`
```
    return @addWithOverflow(V, x, y, &result);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
The following code (the equality test specifically):
```zig
fn addVec3(x: V, y: V) bool {
    var result: V = undefined;
    return @reduce(.Or, @addWithOverflow(V, x, y, &result)) == 1;
}
```
crashes the compiler with illegal hardware instruction.

**Comment by andrewrk** [comment]
not solved yet, there is still:

https://github.com/ziglang/zig/blob/d1f61f2d6801240c593bcf5a3219020ecae0e736/test/behavior/bitcast.zig#L362

**Comment by Vexu** [comment]
That looks completely unrelated? Maybe it's linking the wrong issue by accident?
