### ISSUE TITLE
Strange error message when using explicit array length in array initializer

### ISSUE THREAD

**Issue by dee0xeed** [ziglang/zig#13208]
### Zig Version

0.10.0-dev.4212+34835bbbc

### Steps to Reproduce

Compile this code:

```zig
const std = @import("std");

const Object = struct {
    a: i32 = 7,
    b: i32 = 8,
};

pub fn main() void {
    const len = 3;
    var arr: [len]Object = [len]Object{.{}} ** len;
    std.debug.print("\n{any}\n", .{arr});
}
```

### Expected Behavior

Should be compiled as code without explicit `len`, i.e.

```zig
const std = @import("std");
const Object = struct {
    a: i32 = 7,
    b: i32 = 8,
};
pub fn main() void {
    const len = 3;
    var arr: [len]Object = [_]Object{.{}} ** len;
    std.debug.print("\n{any}\n", .{arr});
}
```

### Actual Behavior

Compiler error:

```
$ /opt/zig/zig build-exe p1.zig 
p1.zig:11:39: error: expected 3 array elements; found 1
    var arr: [len]Object = [len]Object{.{}} ** len;
                           ~~~~~~~~~~~^~~~~
```

**Comment by Vexu** [comment]
The error message is correct, you are trying to initiate a three element array but you only give one element value.

**Comment by dee0xeed** [comment]
> but you only give one element value
But where did duplicator go?

**Comment by dee0xeed** [comment]
The source of my confusion is ... "visual/syntactic similarity" of these two initializers:

```zig
... = [_] Object{.{}} ** 3;
... = [3] Object{.{}} ** 3;
```
But semantically they are different, aren't they?
The first one is something like "an array with some length (which will be known later from the duplicator), then some element duplicated 3 times", but the second one is "an array with length 3, then one object" ... and here parser stops.

**Comment by ominitay** [comment]
No, `[_] Object{.{}}.len == 1`.

**Comment by dee0xeed** [comment]
In other words, `_` in array initializers is the substitute for `1`  only?..

**Comment by nektro** [comment]
yep

**Comment by nektro** [comment]
`**` a binary operator. `[_]Object{.{}}` is the left hand side, `len` is the right hand side.

**Comment by dee0xeed** [comment]
Whew! :) I got the logic, thanks.
We have an 1-element array, duplicate it with `**` and get 3-element array. A bit strange, but Ok.
I mean that duplicating single item (not an 1-element array) seems more natural to me, like

```
var arr: [3]Object = Object{} ** 3;
```

**Comment by nektro** [comment]
them needing to be an array keeps the types consistent and is more generalized to multi item operations, eg:

`[_]u8{ 0, 1, 2 } ** 3 === [_]u8{ 0, 1, 2, 0, 1, 2, 0, 1, 2 }`

**Comment by dee0xeed** [comment]
ok, so `[_]Object{.{}} ** len` is `([1]Object{.{}}) ** len`
good to know, thanks once more for explanations!
