### ISSUE TITLE
Zig can no longer debug C files compiled in

### ISSUE THREAD

**Issue by bpeake13** [ziglang/zig#13204]
### Zig Version

0.10.0-dev.4341+e4e1c21e1

### Steps to Reproduce

Have a program that calls a native C function that was built with the zig application using addCSource. Attach a debug and try to step into the C function. The debugger will say there is no source available for the C functions.

This was produced on windows, using the VSCode cpp debugging.

### Expected Behavior

When in debug builds C source should be debugable along with the zig source

### Actual Behavior

C debug info appears ommited.

**Comment by bpeake13** [comment]
NOTE: Manually adding -g and -O0 to the c compilation fixes the issue.

**Comment by Vexu** [comment]
Cannot reproduce on Linux.

**Comment by bpeake13** [comment]
Should maybe note I'm using stage1, that might cause a difference

**Comment by Vexu** [comment]
Stage1 also works as expected on Linux.

**Comment by michal-z** [comment]
This may be Windows specific issue - I can see this problem on Windows 11 with stage3.

**Comment by kcbanner** [comment]
This was resolved by https://github.com/ziglang/zig/pull/15354
