### ISSUE TITLE
`>>` gives incorrect result at comptime when x < 0 and shift > log2(x)

### ISSUE THREAD

**Issue by topolarity** [ziglang/zig#13209]
### Zig Version

0.10.0-dev.4430+f39f0fcac

### Steps to Reproduce

```zig
const std = @import("std");
const expect = std.testing.expect;
test {
    var i: i8 = -3;
    try expect(i >> 2 == @as(i8, -3) >> 2);
}
```

### Expected Behavior

Test should pass.

### Actual Behavior

Test fails.

**Comment by nektro** [comment]
what's the output if you use `expectEqual` ?

**Comment by topolarity** [comment]
At comptime `@as(i8, -3) >> 2) == 0` but at runtime `i >> 2 == -1`
