### ISSUE TITLE
using Zig to cross compiler for GoLang on Mac M1 chip 

### ISSUE THREAD

**Issue by rohit21agrawal** [ziglang/zig#13222]
Even though I am running ```go build``` without the ```-s -w``` flags, using Zig as the cc with CGO_ENABLED is resulting in a binary that is stripped off symbolic information

```
/Users/rohit/root-x64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.0.0, Go BuildID=CQDwQCpplcXZDbokkgFr/ob0TG9z-hhB0lioGXmhX/B2jNH9OrTCh4fRMcX11T/XL5bAkpFwZger_7WxZPv, stripped
```

**Comment by andrewrk** [comment]
Happy to reopen if you provide more information. See the bug report issue template for example.

**Comment by rohit21agrawal** [comment]
@nullptrdevs that worked beautifully , thanks!!
