### ISSUE TITLE
add support for `~` in paths to std.fs

### ISSUE THREAD

**Issue by ssteinbach** [ziglang/zig#13228]
### Zig Version

0.10.0-dev.4217+9d8cdb855

### Steps to Reproduce

```zig
const std = @import("std");

test "tilde_in_path" {
    const result = try std.fs.realpathAlloc(std.testing.allocator, "~");
    try std.testing.expectEqual(
        result,
        try std.process.getEnvVarOwned(std.testing.allocator, "HOMEDIR")
    );
}
```

### Expected Behavior

The test pass (or pass by swapping out the call for `std.fs.realpathAlloc` for some other function that can resolve the `~`).

I expected there to be some kind of filesystem/path library (maybe not in std.fs, but std.process or std.os) that could resolve paths including the `~` character.

### Actual Behavior

```
❯ zig test testfs.zig
Test [1/1] test.tilde_in_path... FAIL (FileNotFound)
.../zig/zig-macos-aarch64-0.10.0-dev.4217+9d8cdb855/lib/std/os.zig:5130:19: 0x1002a5527 in realpathZ (test)
        .NOENT => return error.FileNotFound,
                  ^
.../zig/zig-macos-aarch64-0.10.0-dev.4217+9d8cdb855/lib/std/os.zig:5100:5: 0x10029d8df in realpath (test)
    return realpathZ(&pathname_c, out_buffer);
    ^
.../zig/zig-macos-aarch64-0.10.0-dev.4217+9d8cdb855/lib/std/fs.zig:2778:31: 0x10029d663 in realpathAlloc (test)
    return allocator.dupe(u8, try os.realpath(pathname, &buf));
                              ^
./testfs.zig:4:20: 0x10029e09b in test.tilde_in_path (test)
    const result = try std.fs.realpathAlloc(std.testing.allocator, "~");
                   ^
0 passed; 0 skipped; 1 failed.
error: the following test command failed with exit code 1:
.../zig-cache/o/8b3c784bc7f7b123900341042e48b2d0/test
```

Discussion on the zig discord: 
https://discord.com/channels/605571803288698900/1032011174612586496 

Thanks for taking a look!

**Comment by meshula** [comment]
That would be nice to have.

**Comment by leecannon** [comment]
I'm not 100% sure about this, tilde expansion is shell functionality (that isn't even done by all of them).

Linux for example will hapily create/open a file called `~` as other than rejecting disallowed characters syscalls act on the paths as given, for zig to replace a path with a completely different path is surprising behaviour.

A function like pythons [expanduser](https://docs.python.org/3/library/os.path.html#os.path.expanduser) might be a better idea.

**Comment by nektro** [comment]
`~` is a bash expansion and never seen by user programs. check out https://github.com/ziglibs/known-folders

**Comment by ssteinbach** [comment]
Just to round out the conversation for future folks who land here from search engines, 

* `~` is seen by user programs via user authored input (for example in the original case: a path written into a configuration file).
* someone in discord pointed at the ["homedir.go"](https://github.com/mitchellh/go-homedir/blob/main/homedir.go) module for go, which (similar to python's built in `os.path.expanduser` function) has an `Expand` function 
* it looks like at present [ziglibs/known-folders](https://github.com/ziglibs/known-folders) can give you the path of or handle to the home directory (or other useful known folders, as the name suggests) but doesn't have an expand path function that takes a string that may be prefixed by a `~` and returns the expanded form of that path

**Comment by meshula** [comment]
I see this was closed pretty quickly. Anyway, I think there's value in a path normalizer with consistent behavior, as opposed to everyone goes off and implements their own idea of a best practice. 

I think Python's `normpath` is an example of that sort of thing. Basically, conform all the slashes, collapse dot-dots, and slash-slashes, and beyond normpath, also do the tilde expand.

https://www.geeksforgeeks.org/python-os-path-normpath-method/

Perhaps such a utility belongs in `known-folders` but it does seem to go beyond the extremely narrow mandate of `known-folders`.

**Comment by nektro** [comment]
as mentioned above, there's multiple OS and FS that allow `~` as a valid filename as well. the issue being closed doesnt mean that the functionality shouldnt exist, only that its not fit for the standard library
