### ISSUE TITLE
How can I set binary output dir from CLI?

### ISSUE THREAD

**Issue by initdc** [ziglang/zig#13226]
### Zig Version

0.9.1

### Steps to Reproduce

`zig build -o output-dir`

### Expected Behavior

```
target
├── darwin
│   ├── amd64
│   │   └── demo
│   └── arm64
│       └── demo
├── linux
│   ├── 386
│   │   └── demo
│   ├── amd64
│   │   └── demo
│   ├── arm
│   │   ├── v5
│   │   │   └── demo
│   │   ├── v6
│   │   │   └── demo
│   │   └── v7
│   │       └── demo
│   ├── arm64
│   │   └── demo
│   └── riscv64
│       └── demo
└── windows
    ├── 386
    │   └── demo.exe
    ├── amd64
    │   └── demo.exe
    └── arm64
        └── demo.exe

16 directories, 12 files
```
https://github.com/initdc/golang-project-workflow/actions/runs/3272226073/jobs/5382978353#step:4:96

I am currently working project workflow template, and adapting my golang template to zig, I reached the problem.

I know the `exe.setOutputDir("output_dir")`, but I still need runing CMD from CLI.
I am new to zig, I have no idea how to parse arg from `zig build -- -o`.

Any way to sovle this problem easily?

BTW:
I saw the log of  `zig build --verbose --verbose-link` with `exe.setOutputDir("output_dir")`
got `cp target/zig-demo /workspaces/zig-project-workflow/zig-out/bin/zig-demo # installed`

It's better way using `ln` to reduce space occupation, like
https://github.com/initdc/golang-project-workflow/blob/master/build.rb#L166

### Actual Behavior

`Unrecognized argument: -o`

**Comment by nektro** [comment]
`--prefix`

**Comment by fwcd** [comment]
This is something that tripped me up too. `-o` or some form of `--output*` flag is such a widely known flag, why can't the Zig compiler provide it?

My usecase is about as simple as it can be: Take a `.zig` file and compile it to an executable at a custom output path. `zig build-exe` seems like the right command, but what is the flag called?

`-o`/`--output`? Nope.
`--output-dir`? Nope.
`--target-dir`? Nope.
`--prefix`? Nope.

Browsing `--help` didn't yield anything useful either. It makes sense that most Zig projects will use `build.zig` or its other high-level build infrastructure, but for anyone seeking to integrate Zig into another build system (maybe even something as simple as a Makefile), this feels like a major stumbling block.
