### ISSUE TITLE
.gitignore: Ignore .DS_Store files created by macOS

### ISSUE THREAD

**Issue by kristate** [ziglang/zig#1323]
placeholder issue

**Comment by tiehuis** [comment]
I think it is more appropriate to put this in your global gitignore instead.

**Comment by kristate** [comment]
@tiehuis I generally agree so -- looks like this was already commented on in #888

I suppose we are all clean enough committers not to allow it into the repo.

**Comment by andrewrk** [comment]
Copying this content here, hoping that people using search engines become more aware of this:

I recommend putting `.DS_Store` in your `~/.gitignore` file and adding this to your `~/.gitconfig`:

```
[core]
	excludesfile = ~/.gitignore
```

This goes for OS-specific files and editor-specific files. What belongs in a project-specific .gitignore file is build artifacts specific to that project.
