### ISSUE TITLE
test-compare fails with stage3 on x86_64 linux

### ISSUE THREAD

**Issue by g-w1** [ziglang/zig#13231]
### Zig Version

0.10.0-dev.4470+8a344fab3

### Steps to Reproduce

In the zig main repository on commit `a4eb221b9ef7dab8fa1c6cc07c7891e25d98d2b6`
```sh
rm -rf zig-out/ zig-cache/
zig build # this zig is downloaded from the website
./zig-out/bin/zig test-compare
```

### Expected Behavior

Tests to pass

### Actual Behavior

Tests fail:
Error message here: https://paste.rs/cPY

This is the exact same error I am experiencing in the CI of #13082

**Comment by topolarity** [comment]
Is this with LLVM enabled, or does this only happen with self-hosted backend?

**Comment by jacobly0** [comment]
I'm not even sure what `zig test-compare` was referring to.  The closest thing I can find is `zig build test-compare-output` which works fine on master.
