### ISSUE TITLE
SIGILL for zig cc compiled program that bit shifts outside of type width

### ISSUE THREAD

**Issue by plajjan** [ziglang/zig#13246]
### Zig Version

0.10.0-dev.4425+f36aee93c

### Steps to Reproduce

Compile and run the following C program
```c
void main(int argc, char **argv) {
	long a = (1 << 100);
}
```

```
zig cc test.c
./a.out
Illegal instruction (core dumped)
```

### Expected Behavior

Not SIGILL!

Do the same thing that a gcc compiled program does!?

I'm not sure what is valid C code but both gcc and clang allows the test programs and do not crash. Not crashing is good.

### Actual Behavior

SIGILL!

```
Illegal instruction (core dumped)
```

gdb
```c
#0  0x00000000002014f2 in main (argc=1, argv=0x7ffd3bb813f8) at z.c:3
3		long a = (1 << 100);
(gdb) 
```

**Comment by Vexu** [comment]
`zig cc` by default sets `-fsanitize-undefined`, use `-fno-sanitize=undefined` to turn it off.

[Why do I get illegal instruction when using with zig cc to build C code?](https://github.com/ziglang/zig/wiki/FAQ#why-do-i-get-illegal-instruction-when-using-with-zig-cc-to-build-c-code)

**Comment by plajjan** [comment]
@Vexu thanks!!
