### ISSUE TITLE
brew install --HEAD zig fails on macOS arm64 due to not finding libzstd

### ISSUE THREAD

**Issue by lordnoriyuki** [ziglang/zig#13242]
### Zig Version

0.10.0-dev.4476+0f0076666

### Steps to Reproduce

Run ```brew install --HEAD zig``` on macOS (arm64)

### Expected Behavior

Expected it to fail later due to https://github.com/ziglang/zig/issues/9764.

### Actual Behavior

Fails due to not being able to link libzstd.
```
warning(link): library not found for '-lzstd'
warning(link): Library search paths:
warning(link):   /opt/homebrew/Cellar/llvm/15.0.3/lib
warning(link):   /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
error(link): undefined reference to symbol '_ZSTD_compress'
error(link):   first referenced in '/opt/homebrew/Cellar/llvm/15.0.3/lib/libLLVMSupport.a(Compression.cpp.o)
```

According to https://github.com/Homebrew/homebrew-core/issues/113650 this looks like its related to this change https://github.com/ziglang/zig/pull/13108 which seems to have a macOS versus Windows difference according to https://github.com/Homebrew/homebrew-core/issues/113650#issuecomment-1286366894

**Comment by andrewrk** [comment]
Could you please give https://github.com/ziglang/zig/pull/13268 a try?

**Comment by lordnoriyuki** [comment]
Confirmed - if I change the homebrew formula locally to pull from [fix-cmake-prefix-path](https://github.com/ziglang/zig/tree/fix-cmake-prefix-path) instead of ```master``` then brew installs zig successfully.

**Comment by sgulgas** [comment]
+1 - just tried It on my system and zig compiled is working fine
