### ISSUE TITLE
'_arg' along with '_' for unused function arguments?

### ISSUE THREAD

**Issue by dee0xeed** [ziglang/zig#13248]
Compare these two function signatures:

```zig
fn func(arg1: T1, _: T2) T3 {...}
fn func(arg1: T1, _some_fancy_argument_name: T2) T3 {...}
```
Suppose, second argument is not used currently,
but I want to preserve that `some_fancy_argument_name` for the future - 
it may happen that I will rethink function body and unused argument will become used.
In this case just removing leading underscore would be a bit mentally easier
than "reinventing" `some_fancy_argument_name` again.

Same idea can be applied for unused vars (or names in || "captures") as well.
The only thing I am afraid of is that this may break C interop.

**Comment by dee0xeed** [comment]
> although I'd prefer just allowing `_ arg: T`

did not think about this, it'd be more consistent with unused vars way.

**Comment by dee0xeed** [comment]
currently one can ignore unused function arguments by **two** ways

```
fn func(_: T)
fn func(arg: T) {_ = arg;}
```

Which one is the right one? ;)

**Comment by nektro** [comment]
prefer the latter unless its otherwise very clear, its better to preserve the name in case you end up needing it later

**Comment by andrewrk** [comment]
No
