### ISSUE TITLE
referenced-by call stacks are not greyed out in the language reference

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#13280]
### Zig Version

0.10.0-dev.4559+04472af32

### Steps to Reproduce

Look at the [language reference](https://ziglang.org/documentation/master/). Observe that referenced-by call stacks are not greyed out like they are in the terminal.

### Expected Behavior

Referenced-by call stack is greyed out like this

![image](https://user-images.githubusercontent.com/106511/197425073-65f2c302-c83c-47c2-a998-3e3b7b97ed40.png)

### Actual Behavior

Referenced-by call stack is not greyed out, like this

![image](https://user-images.githubusercontent.com/106511/197425052-65106429-2c24-4883-bcc2-8384515e6028.png)

----

Some clues:

 * The relevant file is doc/docgen.zig. 
 * Delete the `printShell` function.
 * Delete `shell_buffer`.

**Comment by rdimas-ut** [comment]
What I found is that printShell wraps every line with span tags so the color formatting doesn't carry over to the next line even though termColor wrapped the text block with span correctly. 

I added another switch statement under TermState. It adds ```</span>``` at the end of the line and begins the new line with a  ```<span class=\"t{d}_{d}\">```. This way the color formatting from the line, if any, is carried over to the new one.

Also had to set ```first_number``` and ```second_number``` to zero because otherwise empty spans would be created with invalid classes of the form ```t{some_large_number}```.

Could this be a possible fix?

```zig
fn termColor(allocator: Allocator, input: []const u8) ![]u8 {
    var buf = std.ArrayList(u8).init(allocator);
    defer buf.deinit();

    var out = buf.writer();
    var number_start_index: usize = undefined;
    var first_number: usize = 0;
    var second_number: usize = 0;
    var i: usize = 0;
    var state = TermState.Start;
    var open_span_count: usize = 0;
    while (i < input.len) : (i += 1) {
        const c = input[i];
        switch (state) {
            TermState.Start => switch (c) {
                '\x1b' => state = TermState.Escape,
                '\n' => {
                    if (first_number != 0 or second_number != 0) {
                        try out.writeAll("</span>");
                        try out.writeByte(c);
                        try out.print("<span class=\"t{d}_{d}\">", .{ first_number, second_number });
                    } else {
                        try out.writeByte(c);
                    }
                },
                else => try out.writeByte(c),
            },
```

**Comment by andrewrk** [comment]
> Could this be a possible fix?

Try it out by running `zig build docs` and have a look at `zig-cache/langref.html` and you'll have your answer :slightly_smiling_face:

**Comment by andrewrk** [comment]
I looked into this. The code as-is is done in a janky way making it need to be reworked rather than enhanced. The problem is that it collects escaped html into `shell_buffer `, then does `termColor()` into a buffer, *then* tries to parse the output html, adding spans for each line in `printShell()`. Instead it should have merged the logic of termColor() and printShell() into one function, resulting in everything being much simpler. That's my fault for merging #9614, in which `shell_buffer` was introduced, without noticing this problem.

To fix this problem, the `printShell` function should be deleted and `shell_buffer` deleted.

**Comment by perillo** [comment]
I also noticed that the CSS is missing support for the `1m` escape sequence (Bold or increased intensity).  Maybe it was added later in the compiler?
