### ISSUE TITLE
std.sort segmentation fault

### ISSUE THREAD

**Issue by Pyrolistical** [ziglang/zig#13293]
### Zig Version

0.10.0-dev.4560+828735ac0

### Steps to Reproduce

Given `repo.zig`
```
const std = @import("std");

fn bar(_: @TypeOf({}), lhs: u8, rhs: u8) bool {
    return lhs < rhs;
}

pub fn main() !void {
    const foo: []u8 = undefined;
    std.sort.sort(u8, foo, {}, bar);
}
```

Run `zig build-exe repo.zig`

### Expected Behavior

Compiles without error

### Actual Behavior

```
$ zig build-exe repo.zig
zsh: segmentation fault  zig build-exe repo.zig
```

**Comment by Pyrolistical** [comment]
This is recent as it didn't crash with `0.10.0-dev.4464+7d6596e97`

**Comment by InKryption** [comment]
The error here is that `foo` is an undefined pointer, meaning you're trying to sort the memory at some arbitrary location in memory. The fix here is to make it an array and pass a pointer to it, or allocate it from the heap.

**Comment by Vexu** [comment]
> The error here is that `foo` is an undefined pointer, meaning you're trying to sort the memory at some arbitrary location in memory. The fix here is to make it an array and pass a pointer to it, or allocate it from the heap.

Note that it's `zig build-exe` that is crashing so that undefined doesn't matter as it's not being executed.

Fixed by  #13288.

**Comment by nektro** [comment]
stack https://bpa.st/raw/YSIA

**Comment by Pyrolistical** [comment]
Thanks @nektro. How did does one get a stack trace like that? I would like to be more comprehensive next time.

**Comment by nektro** [comment]
np :) i keep a debug version of zig handy since i occasionally work on the compiler/stdlib here and there https://github.com/ziglang/zig/wiki/Building-Zig-From-Source

**Comment by Pyrolistical** [comment]
Fixed confirmed for my use case. Thank you.
