### ISSUE TITLE
stage2: false dependency loop with usingnamespace

### ISSUE THREAD

**Issue by zenith391** [ziglang/zig#13305]
### Zig Version

0.10.0-dev.4562+b3cd38ea4

### Steps to Reproduce

1. Write the following code to a file:
```zig
const backend = struct {
    const loaded = if (@hasDecl(@import("root"), "capyBackend"))
        @import("root").capyBackend
    else
        struct {};
    pub usingnamespace loaded;
};

const capy = struct {
    pub const cross_platform = if (@hasDecl(backend, "backendExport"))
        backend.backendExport
    else
        struct {};
};

pub usingnamespace capy.cross_platform;

test {
    @import("std").testing.refAllDeclsRecursive(@This());
}
```
2. Execute it using `zig run file.zig`

### Expected Behavior

This compiles successfully. (this does so on stage1)

### Actual Behavior

stage2 detects a false dependency loop and throws the following error message:
```
file.zig:16:5: error: dependency loop detected
pub usingnamespace capy.cross_platform;
~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    usingnamespace_0: file.zig:6:24
```

**Comment by zenith391** [comment]
One possible cause might be that stage2 tries to compute the entire type when using `@hasDecl` instead of just checking if it has that field.

**Comment by Vexu** [comment]
I think this error is actually correct and stage1 is wrong to allow it. The example given can be reduced to the following snippet where the `usingnamespace` gets all the declarations from `loaded` into `root`. `loaded` resolves into a struct containing `capyBackend` if `root` contains `capyBackend` which it does if `loaded` resolves to the first struct but not if it resolves to the second struct`. This is clearly a dependency loop but running it with stage1 passes just fine where as stage2 correctly gives a compile error.
```zig
const root = struct {
    const backend = struct {
        const loaded = if (@hasDecl(root, "capyBackend"))
            struct {
                const capyBackend = 1;
            }
        else
            struct {};
    };

    usingnamespace backend.loaded;
};

test {
    _ = root.backend;
}
```
