### ISSUE TITLE
Expression is considered constant (regression from stage1)

### ISSUE THREAD

**Issue by danielchasehooper** [ziglang/zig#13323]
### Zig Version

0.10.0-dev.4583+875e98a57

### Steps to Reproduce

on M1Pro MacOS 12.6.1 
```
echo '
const Thingy = struct  {
    i:i32=0,
    fn init() Thingy {
        return Thingy{};
    }

    fn next(t: *Thingy) i32 {
        t.i+=1;
        return t.i;
    }
};

test "Const Expr" {
    Thingy.init().next();
}' > bug.zig && zig test bug.zig
```

### Expected Behavior

should compile

### Actual Behavior

```
../zigtests/bug.zig:15:18: error: expected type '*bug.Thingy', found '*const bug.Thingy'
    Thingy.init().next();
    ~~~~~~~~~~~~~^~~~~
../zigtests/bug.zig:15:18: note: cast discards const qualifier
```

I don't think `Thingy.init()` should be const. I realize you can assign it to a var in order to call reference-taking functions on it, but I don't think that should be required.

this used to work in the stage1 compiler. I had code that used to compile, but no longer does.

**Comment by leecannon** [comment]
This is intended https://github.com/ziglang/zig/wiki/Self-Hosted-Compiler-Upgrade-Guide#address-of-temporaries-now-produces-const-pointers

**Comment by nektro** [comment]
^
