### ISSUE TITLE
Allow equality operator (== and !=) for ?T and T when equality operator is supported for T and T

### ISSUE THREAD

**Issue by mdsteele** [ziglang/zig#1332]
This test passes just fine:
```zig
test "compare optional with non-optional" {
    const foo: *i32 = @intToPtr(*i32, 4);
    const bar: ?*i32 = @intToPtr(*i32, 4);
    assert(foo == bar);
}
```

While this one fails to compile, with the error message `"error: operator not allowed for type '?i32'"`:
```zig
test "compare optional with non-optional" {
    const foo: i32 = 4;
    const bar: ?i32 = 4;
    assert(foo == bar);
}
```

At first, I assumed this was a bug, but reading #658, it sounds like this was a deliberate decision? 
 (Because ?i32 == i32 would have to do two comparisons behind the scenes, while ?*i32 == *i32 can just do one.)

Still, this seems like a surprising inconsistency -- in every other language I can think of with a generic option type, either (1) `Option<T>` supports `==` iff `T` supports `==`, or (2) `Option<T>` doesn't support `==` at all.  Here, we have `?T` supporting `==` for one primitive type (pointers) but not for an even more primitive type (`i32`).

**Comment by andrewrk** [comment]
I think this makes sense especially considering #1953 which would create a scenario where pointer types could be in the second category.

**Comment by thejoshwolfe** [comment]
I'd like this feature here: https://github.com/thejoshwolfe/legend-of-swarkland/blob/8a90a00847cd20e11d761be9399633a9a1e17cf6/src/server/game_engine.zig#L412

**Comment by theInkSquid** [comment]
What should happen if one side is `T`, while the other is `?T` ?

Should `fn_returning_i32() == null` be allowed?

**Comment by thejoshwolfe** [comment]
> Should `fn_returning_i32_not_an_option() == null` be allowed?

A similar question is whether `0 == null` should be a compile error. I think there's no good reason for `0 == null`, but `@as(?i32, 0) == null` should be allowed.

**Comment by andrewrk** [comment]
> A similar question is whether `0 == null` should be a compile error.

It's a bug if not.

**Comment by theInkSquid** [comment]
For example, when comparing two distinct optional values:
```rust
const x: ?i32 = createAnOptional();
const y: ?i32 = createAnOptional();
if (x == y) { 
    debug.warn("equal", .{});
}
```
It would be necessary to turn the `x == y` into something like the following (under the hood):
```d
((x == null) == (y == null)) and (x == null or x.? == y.?)
```

But if one were to write this instead:
```rust
if (x == 10) { ... }
```
What should that expand to? Should the `10` be implicitly cast to an optional, or should comparing `?T` with `T` be a special case, where it turns into something closer to this:

```d
(lhs == null) or (lhs.? == rhs)
```
Which is likely a lot more efficient.
Would it be worth it to make this optimization? Or could LLVM just do this on its own?

**Comment by thejoshwolfe** [comment]
@theInkSquid this proposal is for comparing `?T` and `T`. If we want to support comparing `?T` and `?T`, that's a separate proposal.

This proposal is to expand `@as(?T, foo) == @as(T, bar)` to `foo != null and foo.? == bar`.

What you're proposing for `?T` and `?T` might also be valuable, but it needs its own proposal.

**Comment by theInkSquid** [comment]
I see, thank you. Would it be appropriate to short-circuit evaluating the non-optional parameter? For example:

```rust
const x: ?i32 = null;
if (x == @compileError("err")) {...}
```
Should this be a compile error? Or, since it can be determined that because `x` is null (and in no case will it be equal to the right hand side), should it just evaluate to `false`?
@andrewrk

**Comment by thejoshwolfe** [comment]
@theInkSquid that's an insightful question. There are two options.

For the expression `lhs == rhs` where `lhs` is of type `?T` and `rhs` is of type `T`, the semantics should either be:

Option 1: no short circuit.

```
$lhs_value = evaluate lhs;
$rhs_value = evaluate rhs;
if $lhs_value == null {
    result = false;
} else {
    result = $lhs_value.? == $rhs_value;
}
```

Option 2: short circuit:

```
$lhs_value = evaluate lhs;
if $lhs_value == null {
    result = false;
} else {
    $rhs_value = evaluate rhs;
    result = $lhs_value.? == $rhs_value;
}
```

The OP posted an important motivation for this issue: the inconsistency of the `==` operator for optional pointers and optional everything-else. Following this logic, we should do option 1 with no short circuit, since we don't do that pointer types.

**Comment by mikdusan** [comment]
> This proposal is to expand `@as(?T, foo) == @as(T, bar)` to `foo != null and foo.? == bar`.

to clarify, `??T == T` is to be a compile-error?

**Comment by andrewrk** [comment]
Yes

**Comment by theInkSquid** [comment]
How about when `?T == U` when T and U coerce to the same type?

Like could I do this?```rust
x: ?i32 = ...;
y: i16 = ...;
x == y
```

**Comment by theInkSquid** [comment]
Also, what about for special cases where a type is comparable with some other type? For example, you can compare a tagged union with an enum literal to check if that is the current value. Should an optional tagged union be comparable with an enum literal? That doesn't fall into the rigid `?T ==/!= T` that was specified, but would make a lot of sense to have.

**Comment by theInkSquid** [comment]
Another thing I just realized: there is a guarantee that only keywords will affect control-flow, but comparing `?T` with another `T` requires generating a branch. Is this ok? Also, the only way of doing this that I can think of (reasonably) is putting in a possibly-used branch on the first pass, every time `==` or `!=` is seen, which may or may not be discarded depending on the types. I am not even sure if that would work, but the "invisible control flow" that has to happen with `?T == T` is notable, and also difficult to implement. 

Maybe optional pointers should just be special?  Or there should be a std library feature for this:

```zig
const optEqualsNonOpt = fn(comptime T: type, opt: ?T, non_opt: T) bool {
    if (opt) |x| {
        return x == non_opt;
    } else {
        return false;
    }
}```
