### ISSUE TITLE
Remove \" escape sequences to make zig grammer even more regex friendly

### ISSUE THREAD

**Issue by thejoshwolfe** [ziglang/zig#1336]
this may be a bad idea.

## Background

Everyone wants to parse things with regex. Many programming languages are almost possible to parse with regex, and naive programmers will end up writing incorrect code that mostly works.

Parsing can mean lots of different things, but the step I want to focus on here is the part where you distinguish between actual code and not code. For example, if you wanted to count the number of `try` tokens in your code, you can't just count the matches for `/\btry\b/`, because that would include the word showing up in comments. So the first step when you want to parse the code should be a preprocessing step that removes comments and other non-code, or even better, remove the content of them and leave empty quotes and empty comments.

Here's a perl program to do this today:

```
s/(["'])([^\\]|\\.)*?\1/$1$1/g;
s/(\/\/|\\\\).*/$1/g;
```

(I was not able to describe this regex in the `sed` dialect of regex, but maybe someone with more wizardry than i could do it.) Even though the above code is correct (afaict), it's still really complicated, and we could make it simpler by modifying the string and character literal syntax. After this proposal, you can do this perl code to strip all comments and text literals:

```
s/".*?"/""/g;
/'.*?'/''/g;
/\/\/.*/\/\//g;
/\\\\.*/\\\\/g;
```

In english, this perl code simply does the following four things in order: remove all the text between "double quotes", remove all the text between 'single quotes', remove everything after a `//`, remove everything after a `\\`. That's very easy to understand and describe in regex, but it's incorrect with status quo zig.

This proposal is to restrict the zig language so that the above four steps are sufficient to remove all non-language text for zig sourcecode.

### Alternate background

Another completely different approach to this problem is if you try to make the most lexically confusing and obfuscated zig code you can (lexically, meaning it's confusing where one token starts and another one ends), the best I can come up with today is putting a long chain of `\` characters in a row in a string literal followed by a `"`. The reader has to count if there's an even or odd number of `\`s in order to know if the string literal ends at the `"` or if the `"` is escaped and what follows is still part of the string literal. If we remove the `\"` escape sequence, then the next `"` character ends the string literal, regardless of what's before it.

## Proposal

* Remove the `'\''` escape sequence in character literals.
* Remove the `"\""` escape sequence in string literals.
* Make `'"'` illegal.

We'll need new ways to encode quote marks in these literals.

* Add an escape sequence `\q` which encodes the `"` character in "string literals" and 'character literals'.
* Add an escape sequence `\a` which encodes the `'` character in 'character literals'.

I'm not super happy about `\a`. It's not clear what it means (the answer is "apostrophe"), and it directly contradicts `\a` in C where it encodes the ascii bell character. I don't like `\s` (for "single quote") since it directly contradicts `\s` in regex where it denotes the whitespace character class.

If we left `'\''` as valid zig, then we'd need to add an extra step to the regex. Maybe this isn't so bad:

```
s/".*?"/""/g;
/'\\''/''/g;
/'.*?'/''/g;
/\/\/.*/\/\//g;
/\\\\.*/\\\\/g;
```

Since character literals must only encode a single character, then we can just check for the exact text `'\''` before checking for "anything between single quotes".

**Comment by bronze1man** [comment]
A "for" parser or a normal token parser or a plain string search may be much easier then regex to write it correctly.
I hate the syntax of regex, it is difficult to understand the mean of the regex character encoding.

**Comment by iology** [comment]
Given the "crude" regexps, may I imagine you may also want to count the "try" tokens that are not considered at compile-time? Also the regexps do not check if the source code is well-formed.

**Comment by phase** [comment]
>    * Add an escape sequence \q which encodes the " character in "string literals" and 'character literals'.
>    * Add an escape sequence \a which encodes the ' character in 'character literals'.

These are rather confusing at a first glance. Maybe `\sq` and `\dq` for _single quote_ and _double quote_?

**Comment by thejoshwolfe** [comment]
yeah, i don't like this idea.

**Comment by shawnl** [comment]
> (I was not able to describe this regex in the sed dialect of regex, but maybe someone with more wizardry than i could do it.)

sed lacks non-greedy matching and thus only matches a subset of regular languages.
