### ISSUE TITLE
Allow kebab-case in identifiers?

### ISSUE THREAD

**Issue by dee0xeed** [ziglang/zig#13387]
```zig
const sofa-constant = 2.8284;
var is-complete: bool = false;
```

Rationale

1. Most (if not all) programmers surround binary operators with spaces
2. Zig already has some premises for this, I mean

```
minus.zig:7:16: error: binary operator `-` has whitespace on one side, but not the other.
    const z = x- y;
               ^
```

However, unary minus is a hindrance.

**Comment by jedisct1** [comment]
Not sure this is a good idea.

It would actually hurt consistency (code would end up with a mix of kabab case and snake case to represent the same class of variables), without bringing any benefits. The ability to have `is-complete` and `is_complete` in the same scope would a source of bugs.

`x-y` not being the same as `x - y` would also hurt readability, and would also another source of bugs.

Also, programmers are not expected to surround binary operators with spaces. `zig fmt` does it for you :)

**Comment by wooster0** [comment]
Don't forget that you can always use `@"this identifier syntax"` so you could do `@"kebab-syntax"`. While probably not ideal for people that want to use kebab syntax, maybe it's somewhat of a solution.

**Comment by ElementW** [comment]
This proposal cannot exist if the language allows the use of the `-` binary operator without surrounding whitespace, as it would otherwise mean the syntax would be ambiguous and parsing Zig code would require context (here, semantic analysis and variable name disambiguation), which AFAIK is an explicit non-starter; this is also why `/* block comments */` are not a thing.

**Comment by mlugg** [comment]
In addition, Zig has fairly well-established naming conventions at this point, and it's not clear where or for what reason `kebab-case` would fit into them. This feels somewhat like a feature for features' sake, since there's effectively no practical advantage as far as I can see

**Comment by ifreund** [comment]
This exactly the kind of thing that the issue templates are supposed to discourage.
