### ISSUE TITLE
Stage2 compiler on macOS can't find stdlib.

### ISSUE THREAD

**Issue by binary132** [ziglang/zig#1340]
Identical to https://github.com/ziglang/zig/issues/1117.

Built from latest master using:

```
# from within zig/build after ninja build && ninja install:
./bin/zig build --build-file ../build.zig --prefix $(pwd)/stage2 install
```

Unexpected behavior: 
```
~/tmp/zig/hello❯ zig2 build-exe main.zig
Unable to find zig lib directory: FileNotFound.
Reinstall Zig or use --zig-install-prefix.
```

**Comment by kubkon** [comment]
I think this issue has been fixed somewhere along the way for stage2 as it is now possible to build simple Mach-O executables with explicit `_start` entrypoint (weakly linked `main` symbol from `libSystem` is in the works), so closing. Feel free to reopen if the issue persists though!
