### ISSUE TITLE
likely/unlikely for if ()

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#1342]
```
likely if (a < 0)
    foo;

unlikely if (b < 0)
    bar;
```

like in linux https://github.com/torvalds/linux/blob/master/include/linux/compiler.h#L39

**Comment by PavelVozenilek** [comment]
I'd proposed this in #489, with `if+` and `if-`. More wordy or complicated syntax wouldn't be worth the trouble.

**Comment by shawnl** [comment]
`if+` and `if-` is nice, especially as it corresponds to "closing" and "expanding" symbols. Closing

**Comment by BarabasGitHub** [comment]
I think I actually like the wordy ones better because it is in no way clear
what if+ is supposed to do imo.

Op di 7 aug. 2018 01:05 schreef Shawn Landden <notifications@github.com>:

**Comment by PavelVozenilek** [comment]
@BarabasGitHub: if `likely`/`unlikely `functionality is expected to have measurable effect on performance, it should be used frequently.  `if+`/`if-` doesn't clutter visually the code, unlike the alternatives. If they are used frequently, people will internalize their meaning quickly.

**Comment by shawnl** [comment]
yeah but `likely`/`unlikely` would work the same as `comptime`, which is nice
