### ISSUE TITLE
comptime on if()

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#1343]
allow attaching `comptime` to if clauses:
```
comptime if (big_endian) {
    foo();
} else {
    bar();
}
```
as a replacement of C's magic includes
```
#ifdef HAVE_FOO
#else
#endif
```

The compiler is already free to do this, but by attaching comptime makes it a compile error if not comptime, and makes the code easier to read.

**Comment by thejoshwolfe** [comment]
```zig
if (comptime big_endian) {
    foo();
} else {
    bat();
}
```

`comptime` is a prefix operator you can put in front of any expression to assert that its value is comptime known.
