### ISSUE TITLE
the stage1 zig-cache directory has name collision problems and race conditions

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#1344]
i'm littering all over these zig-cache folders.

**Comment by shawnl** [comment]
That is kinda racey however....

**Comment by andrewrk** [comment]
Note that stage2 (the self hosted compiler) does not (and will not) have this problem. Note also that the self hosted compiler cannot build itself yet.

**Comment by andrewrk** [comment]
self-hosted caching landed with the merge of #6250
