### ISSUE TITLE
if () else

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#1347]
else can't trail an if without using braces `{}`, like in C. I don't see a good reason for rejecting this syntax, like so:

```
if (condition)
    foo;
else
    bar;
```

Yes, it is confusing where there is nested ifs, but then we can issue a warning asking for clarifying brackets like gcc does.

**Comment by thejoshwolfe** [comment]
the reason for this is more clear when you write it all on one line.

```zig
if (condition) foo else bar;
```

`if` (and `while` and `for`) are more like expressions than compound statements.

> Yes, it is confusing where there is nested ifs

this is still an issue with `if` (and `while` and `for`).

```zig
if (condition) if (other) foo else bar;
```

I don't think that's confusing enough to warrant an error (zig has no warnings), but I'm open to the idea.
