### ISSUE TITLE
wiki should be switched to contributors only

### ISSUE THREAD

**Issue by leecannon** [ziglang/zig#13470]
It is annoying but necessary as people modifying the links has become rather regular. 
In the below cases it is only an ip logger but it could easily link to something much more damaging.

https://github.com/ziglang/zig/wiki/How-to-build-LLVM,-libclang,-and-liblld-from-source/_compare/042067b%5E...042067b
https://github.com/ziglang/zig/wiki/Building-Zig-From-Source/_compare/34a274e%5E...34a274e
https://github.com/ziglang/zig/wiki/Building-Zig-on-Windows/_compare/02c72b7%5E...02c72b7
https://github.com/ziglang/zig/wiki/Install-Zig-from-a-Package-Manager/_compare/297a1f2%5E...297a1f2

**Comment by andrewrk** [comment]
Done. thanks, I didn't know that was a setting.
