### ISSUE TITLE
@typeOf should presumably be called @TypeOf

### ISSUE THREAD

**Issue by mdsteele** [ziglang/zig#1348]
All the other builtin functions that return types (e.g. `@ArgType`, `@OpaqueType`, `@TagType`) are capitalized, matching the guidance in https://ziglang.org/documentation/master/#Names.

**Comment by thejoshwolfe** [comment]
agreed. this rename is planned; i think just nobody's gotten around to doing it yet.

**Comment by andrewrk** [comment]
Just to make this one easier on everyone, I'll wait until we're distributing zig fmt (e.g self hosted is done) and then I'll tag a commit where zig fmt will automatically fix this. I don't see a reason to do the rename before then.

**Comment by andrewrk** [comment]
OK so the current plan for these builtin renames (see also #2120) is:
 1. Make `zig fmt` allow both names but render to the canonical name
 2. After about 1 release cycle not even `zig fmt` will support the old name.

**Comment by andrewrk** [comment]
Gonna re-open this, just to track when we can remove support for auto-conversion. As soon as 0.6.0 is released, it's fair game to remove the legacy `@typeOf` support.
