### ISSUE TITLE
Incorrect Results for `@sizeOf()` with Optional Types

### ISSUE THREAD

**Issue by sno2** [ziglang/zig#13511]
### Zig Version

0.10.0-dev.4418+99c3578f6

### Steps to Reproduce and Observed Behavior

Create any basic struct and log the regular `@sizeOf(T)` and `@sizeOf(?T)`.

```zig
const std = @import("std");

pub fn main() void {
    const V = struct {
        ptr: u32,
        value: bool,
        asdf: u64,
    };
    std.debug.print("normal: {}\n", .{@sizeOf(V)});
    std.debug.print("optional: {}\n", .{@sizeOf(?V)});
}

```

If you run the above program, then you will see the following:
```
normal: 16
optional: 1
```

### Expected Behavior

The `@sizeOf(T)` should add the bytes of the inner type when computing the total size of an optional type.

**Comment by nektro** [comment]
issue is not present on 0.10.0

```
normal: 16
optional: 24
```

**Comment by sno2** [comment]
Hmm, just updated to master and it's working so I guess it's already fixed.
