### ISSUE TITLE
cannot format optional without a specifier

### ISSUE THREAD

**Issue by gertcuykens** [ziglang/zig#13529]
### Zig Version

0.10.0

### Steps to Reproduce and Observed Output

```zig 
var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
defer arena.deinit();

var arg_it = try std.process.argsWithAllocator(arena.allocator());
const stdout = std.io.getStdOut().writer();
// try stdout.print("{s}\n", .{arg_it.next() orelse ""});
try stdout.print("{s}\n", .{arg_it.next() });

```

### Expected Output

the current `build run` err message doesn't include which statement it refering to so you have no idea where to look in your code
```zig
zig/lib/std/fmt.zig:498:17: error: cannot format optional without a specifier (i.e. {?} or {any})
                @compileError("cannot format optional without a specifier (i.e. {?} or {any})");
```
 
<img width="840" alt="image" src="https://user-images.githubusercontent.com/863731/201451049-c3e37a74-e988-4222-9cc7-241dc06ea0bb.png">

**Comment by vjpr** [comment]
`-freference-trace`
