### ISSUE TITLE
comptime required when concatenatting builtin.target.exeFileExt

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#13520]
### Zig Version

0.11.0-dev.86+b83e4d965

### Steps to Reproduce and Observed Behavior

`bug.zig`:
```zig
const builtin = @import("builtin");

pub fn main() void {
    const s = "foo" ++ builtin.target.exeFileExt();
    @import("std").log.info("s is '{s}'", .{s});
}
```
```sh
$ zig build-exe bug.zig
bug.zig:4:49: error: unable to resolve comptime value
    const s = "foo" ++ builtin.target.exeFileExt();
                       ~~~~~~~~~~~~~~~~~~~~~~~~~^~
bug.zig:4:49: note: slice value being concatenated must be comptime-known
```

### Expected Behavior

Compiles successfully.

Note that adding `comptime` in front of the expression, i.e. `comptime "foo" ++ builtin.target.exeFileExt();` allows it to compile, however, I wasn't expecting needing to add that.  I'm not certain that this is a bug, but seemed like it *might* be.

**Comment by Vexu** [comment]
Not a bug, concatenation works at runtime so the operands are not in implicit comptime scopes.
