### ISSUE TITLE
intentional @compileError limits zig to a very narrow band of posix systems

### ISSUE THREAD

**Issue by jrmarino** [ziglang/zig#13565]
https://github.com/ziglang/zig/blob/aea617c60be848ed372343e08465bb0ac6cb7b85/lib/std/os.zig#L5284-L5300

so zig 10.0.0 will intentionally does not compile on < FreeBSD 13 and not at all on DragonFly or NetBSD?

There wouldn't be a reason to leave it in Ravenports if that's the case.

**Comment by nektro** [comment]
`.netbsd` and `.dragonfly` get their own OS values respectively

**Comment by leecannon** [comment]
Also this compile error is only hit *if* someone calls `getFdPath` on < FreeBSD 13, if they don't try to get the path of an fd then no compile error.

**Comment by jrmarino** [comment]
I understand the code.  The point is that they don't have it now, which means it doesn't build now.
And @leecannon  is incorrect.  It doesn't compile.  I assume that's the point of @compilError

More to the point, there should be code to fallback on, not a compile error.

What other projects have done in cases like this is return nothing, perhaps with some kind of emitted notice.

Unless zig is intentionally supporting ONLY FreeBSD (and linux, macos, windows) the current state shouldn't be acceptable.

**Comment by yujiri8** [comment]
`@compileError` only triggers a compile error if it is semantically analyzed. If getFdPath is never called, its body is never semantically analyzed, so the program will compile.

> What other projects have done in cases like this is return nothing, perhaps with some kind of emitted notice.

I think this is very much a bad idea and contrary to Zig's values. If you're calling an API that doesn't exist on your platform, you should find out about that as soon as possible. If you really want it to fall back on returning null, you could branch on `builtin.os.tag` yourself and use null instead of calling the function on FreeBSD < 13. It should be explicit. And Zig does not have warnings, so it's either a compile error or quietly doing something incorrect at runtime.

**Comment by jrmarino** [comment]
I'm not sure what your point is.
I found it because zig 9 compiles on DragonFly and trying to update to zig 10 failed to compile on DragonFly.
Ravenports is still using FreeBSD 12.1 as the basis of FreeBSD ports.  I have not attempted to compile it there, but I fully expect it to also fail to compile, because it will be semantically analyzed.

The bottom is at least 2 platforms stopped building between zig 9 and zig 10.  I cannot remember if our netbsd packages including zig yet or not, so that could be 3 platforms.

so you are leaving me with 3 choices:
1) stay at zig 9
2) move to zig 10 and remove support for dragonfly, freebsd, and netbsd (at least until RP moves to base packages on FreeBSD 13 or later)
3) just remove the port completely

Obviously I'm not going to try to implement the missing functionality

**Comment by nektro** [comment]
if you're on dragonfly and zig is detecting it as freebsd, that's a different issue, and a valid one for sure

**Comment by mikdusan** [comment]
Unfortunately, it seems `os.getFdPath()` is referenced in the normal course of building zig. I think it's indirect via `os.realpath()` implementation.

At a quick glance, perhaps on platforms where libc is used, the impl be changed to use libc's `realpath()` instead of `getFdPath()` .

**Comment by jrmarino** [comment]
@nektro no it's not a case of dragonfly being identified as freebsd.  I was just saying that I was building on Dragonfly, but I expect to hit the same issue on FreeBSD 12.2.

**Comment by semarie** [comment]
My digging is it comes from realpathAlloc() call from [src/Compilation.zig](https://github.com/ziglang/zig/blob/88a0f3d0e55691aa2b341cfa6efc53f2540b22f9/src/Compilation.zig#L4019), which call `Dir.realpath()`, which call `Dir.realpathZ()`, which call `getFdPath()`

**Comment by squeek502** [comment]
> Unless zig is intentionally supporting ONLY FreeBSD (and linux, macos, windows) the current state shouldn't be acceptable.

This is an unintentional regression. Looks like it was introduced in https://github.com/ziglang/zig/commit/9db293492bbbc5b8d70638bd9c59dea19d13596c

**Comment by mikdusan** [comment]
I have setup quite a few VMs to work this issue and confirmed the following status re: obtaining a path via filehandle and `std.getFdPath()`:

✅ Linux has an adequate `/proc/self` implementation.

✅ macOs has a good `F_GETPATH` implementation; caveat: it currently misses handling too-big pathnames. It is undocumented, but xnu will use `E_NOSPC` for this condition.

✅ Solaris appears to have a similar `/proc/self` implementation.

✅ FreeBSD has a `F_KINFO` implementation which only works for the most recent `13.1` version. I do have a fallback `systctl` based implementation which works for `< 13.1` (tested against `12.3`). The fallback solution isn't very efficient (has to loop through each fd for current proc and match).

✅ DragonFly BSD has `F_GETPATH` support and I have a working implementation tested on latest `6.2.2`

 ✅ OpenBSD has `kvm_openfiles()` and `kvm_getfiles()` but they require linking `-lkvm` for any executable (including `zig.exe`) that uses `std.getFdPath()`. The kvm interface does seem to work. It's efficiency is about par with FreeBSD `< 13.1` solution. We can overcome most of the linking pain with `-lkvm` thanks to zig's `export` syntax:
```rust
export "kvm" kvm_getfiles(...) ...;
export "kvm" kvm_openfiles(...) ...;
```

❌ NetBSD has `kvm_openfiles()` and `kvm_getfiles()` and like OpenBSD, it requires `-lkvm` but unfortunately it also requires to run as root. This is a show-stopper for that platform. I haven't found another viable solution. Note, that walking a filesystem and matching for inode is not an acceptable solution.

Usage of `std.getFdPath()` has permeated stage1 and stage2 compilers. In other words, we cannot build a compiler without `std.getFdPath()` implemented on that platform.

### MY CONCLUSION

- remove `zig.exe` dependency on `std.getFdPath()`
- keep `std.getFdPath()` and improve docs to indicate platform support

cc: @andrewrk, @daurnimator

**Comment by semarie** [comment]
Regarding OpenBSD and kvm, you should be able to get some informations about the descriptor (like inode `va_fileid` and device `va_fsid`), but the filepath isn't part of that.

**Comment by The-King-of-Toasters** [comment]
Since I created this problem (re: FreeBSD impl.), I may be of help for the NetBSD fix. I remember a WIP patch on the FreeBSD phabricator that referenced implemented a NetBSD function that IIRC did what getFdPath does.

Here it is: [`fcntl(F_GETPATH)`](https://man.netbsd.org/fcntl.2)

**Comment by mikdusan** [comment]
Now that I have patch to remove zig compiler dependency on `getFdPath()`, we can add platforms with bonafide F_GETPATH/similar support and not worry about older versions that don't have it.

Great news about netbsd 9.4 support! Probably about a year away.

**Comment by NikitaRonja-QuoInt** [comment]
NetBSD 10.0 should be out soon, not a year from now.

**Comment by andrewrk** [comment]
The compiler is not supposed to call realpath under any circumstances. I apologize for not noticing this earlier. Problematic commit reverted in 9bcd48e40e272408879a442b21099ea5ab6b85b4.
