### ISSUE TITLE
C backend: generate MSVC-compatible code 

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#13574]
This issue can be closed when we add CI test coverage that compiles the behavior tests with `-ofmt=c` and then compiles & runs them with MSVC.

This command can be used to produce a test.c file for testing with MSVC:

```
> stage3\bin\zig.exe test ..\test\behavior.zig -I..\test -ofmt=c -femit-bin=test.c
```

**Comment by kcbanner** [comment]
I've started working on this here: https://github.com/kcbanner/zig/tree/cbe_msvc_compatibility

**Comment by kcbanner** [comment]
I think this can be closed with https://github.com/ziglang/zig/pull/14002 merged
