### ISSUE TITLE
Bootstrap WASM interpreter doesn't implement flock

### ISSUE THREAD

**Issue by kprotty** [ziglang/zig#13589]
### Zig Version

9f317bf94

### Steps to Reproduce and Observed Behavior

- `git checkout wasi-bootstrap`
- `mkdir build && cd build && cmake .. [stuff]`
- `make -j$N # where N > 1`

### Expected Behavior

The WASM interpreter should run normally.

Having make/ninja do parallel jobs runs the zig wasi interpreter simultaneously: 
```bash
[ 84%] Interpreting zig1.wasm to produce /Users/king/ziglang/build/compiler_rt.c
[ 84%] Interpreting zig1.wasm to produce /Users/king/ziglang/build/zig2.c
```

Each build interacts with the zig cache which does flock() when working on build artifacts to wait for a winning process to build/write shared file. The `flock()` path is [skipped on WASI](https://github.com/ziglang/zig/blob/30b8b29f88362d18ea6523a859b29f7bc6dec622/src/Cache.zig#L779-L781) so the zig wasi interpreter crashes with `attempt to unwrap error: FileNotFoundunreachable reached`.

The zig wasi interpreter should implement flock and that code path should be enabled again by checking builtin to know if being built as the WASM blob instead of targeting a standard wasi interpreter.

**Comment by Vexu** [comment]
The current version of wasi-bootstrap doesn't use a wasm interpreter.
