### ISSUE TITLE
Compiler crash with double-free in malloc in 0.11.0 self-hosted

### ISSUE THREAD

**Issue by dvmason** [ziglang/zig#13590]
### Zig Version

0.11.0-dev.203+58d9004ce,  0.11.0-dev.226+ea590ece4 and 0.11.0-dev.227+0697883d0

### Steps to Reproduce and Observed Behavior

Clone https://github.com/dvmason/Zag-Smalltalk/commit/d5a32d170120b0c282221ebd37cd956f7defa311
cd zig/zag
zig test arenas.zig

with dev-203 and dev-227 (though the constants are different) produces:

-------
zig(26898,0x20ceae500) malloc: Double free of object 0x14fe51ab0
zig(26898,0x20ceae500) malloc: *** set a breakpoint in malloc_error_break to debug
-------

with dev-226 produces:

-------
zig(29104,0x20ceae500) malloc: Heap corruption detected, free list is damaged at 0x600002a4a370
*** Incorrect guard value: 18446462627365956102
zig(29104,0x20ceae500) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
-------

This on MacOs Ventura M1

### Expected Behavior

There are errors that should be reported

**Comment by dvmason** [comment]
Changing usize to Age in line 203 of arenas.zig will (correctly) cause compilation errors instead, but once that line isn't an error, it crashes. In fact, you can remove line 203, and the reference to `self.vtable.createAge` a few lines later doesn't cause an error, but a crash.

**Comment by dvmason** [comment]
It would be really convenient to have a `-ftrace-compilation` or something that showed what it was trying to do so I could work around bugs. I love zig and really appreciate what you people are doing, but working on the bleeding edge is a bit frustrating. Although I can alternate with 0.10 and make progress.

Thanks!

**Comment by Vexu** [comment]
Reduction:
```zig
const S = struct {
    a: u32,
    b: u32,
    fn init() S {
        return .{
            .a = 1,
        };
    }
};
var foo = S.init();

comptime {
    _ = foo;
}
```

Fix for your project:
```diff
diff --git a/zig/zag/arenas.zig b/zig/zag/arenas.zig
index 9f39925..dbfcb00 100644
--- a/zig/zag/arenas.zig
+++ b/zig/zag/arenas.zig
@@ -151,6 +151,8 @@ pub const GlobalArena = struct {
         var result = GlobalArena {
             .vtable = Arena.Vtable {
                 .alloc = alloc,
+                .maxSize = undefined,
+                .createAge = undefined,
             },
             .freeLists = [_]FreeListPtr{null}**nFreeLists,
         };
```

**Comment by dvmason** [comment]
Thanks!
