### ISSUE TITLE
`std.ChildProcess.kill` should expose errors from racing with the process exiting cleanly

### ISSUE THREAD

**Issue by bcrist** [ziglang/zig#13608]
### Zig Version

0.10.0

### Steps to Reproduce and Observed Behavior

Spawn a child process using `std.ChildProcess`, then wait some time and call `child.kill()`, after the process has exited normally.  On Windows, `error.Unexpected` will be returned.  On Posix, the program will crash, because `kill` returns ESRCH in this case, which is noted in os.zig's kill wrapper as:
```
        .SRCH => unreachable, // always a race condition
```
It's true that this is a race condition, but it's sometimes an unavoidable one, and crashing here isn't appropriate IMO.

Use case: You need to run a buggy program that you don't control, which sometimes goes into an infinite loop.  Calling `child.wait()` will block forever if that happens, so you need to kill the process after some timeout, but it's impossible to know if the process is really hung, or just taking a long time and about to exit normally.

### Expected Behavior

`std.ChildProcess.kill` should return an error if the process has already terminated normally (perhaps `error.AlreadyTerminated`?).  Then in cases where the program just wants the child to stop, and doesn't care whether it's a normal or forced exit, it can handle that error and call `std.ChildProcess.wait` instead.

On the command line, killing a process by PID is always somewhat dangerous, since it's theoretically possible for it to exit normally, and then another process could start and be assigned the same PID before you kill it.  But in the case of a program working with its own child processes, I don't believe this is ever dangerous.  On Windows, `TerminateProcess` works on a process handle, not a PID, so it can never accidentally terminate the wrong process.  On posix, I believe it's required that a PID be marked as a zombie until `wait` is called on it, or the parent exits itself, so it shouldn't be possible for a child process PID to be reused in this case.

**Comment by matu3ba** [comment]
Using pkill doesn't work in all cases as shown here, which also explains the proper solution: https://lwn.net/Articles/754980/

**Comment by bcrist** [comment]
@matu3ba Unless I'm mistaken, in the case of a process that forks, `std.ChildProcess.wait()` will also only wait for the directly created process to exit.  I don't think it makes sense to expand the scope of `kill` to include sub-sub-processes as well.  Also as mentioned in that article, `setresuid` is not available on all platforms.

**Comment by matu3ba** [comment]
>  I don't think it makes sense to expand the scope of kill to include sub-sub-processes as well

As of now, we have Zig process spawning test runner and its relative likely some folks will spawn things inside the test runner (which in turn spawn stuff) for integration tests.

I'm not in the core team, so I can not make a decision on this.

**Comment by bcrist** [comment]
@daurnimator can you elaborate how/why using pidfds would help in this case?

I think there might be some confusion here in that there's actually two different races:
1. The other process is running concurrently, and it can exit at any time, so attempting to kill it is always a race with it already having exited normally.
2. If the other process exits and the OS releases its pid, then trying to kill it also races with the OS reusing that PID for another process, and accidentally killing that instead, which would be very bad.

As far as I understand it, pidfds are meant to address the latter, but in the case of your own child process, the OS already guarantees that it won't reuse the pid if you haven't waited on it yet.

**Comment by daurnimator** [comment]
> @daurnimator can you elaborate how/why using pidfds would help in this case?

> Use case: You need to run a buggy program that you don't control, which sometimes goes into an infinite loop. Calling `child.wait()` will block forever if that happens, so you need to kill the process after some timeout, but it's impossible to know if the process is really hung, or just taking a long time and about to exit normally.

1. use `pidfd_wait` with `WNOHANG` or `poll` the pidfd to know if the pid has exited; if not:
2. use `pidfd_send_signal` to kill it
3. goto 1

**Comment by bcrist** [comment]
> 1. use `wait` with `WNOHANG`+`P_PIDFD` or `poll` the pidfd to know if the pid has exited; if not:
> 2. use `pidfd_send_signal` to kill it
> 3. goto 1

Ah, gotcha, you meant using it as a workaround for the standard library not handling this case cleanly.  That seems reasonable, though in my particular case that motivated this, it's a windows-only program so I'm working around it by calling `TerminateProcess` manually before calling `ChildProcess.wait` when I want to kill it.

It just seemed to me that this aught to be something that the standard library handles.  `ChildProcess.kill` is currently only safe if you can guarantee that the child process is still running, and even for something like a server where 99.99% of the time you might be right, there's always a chance it could crash or be killed externally at just the wrong time.

**Comment by daurnimator** [comment]
> so I'm working around it by calling `TerminateProcess` manually before calling `ChildProcess.wait` when I want to kill it.

That would be the same as:
1. call `pidfd_send_signal`
2. use `wait`

Where that is safer than using `kill` in step 1 as the pid *cannot* have been reused.




> `ChildProcess.kill` is currently only safe if you can guarantee that the child process is still running,

That is correct.
Consider my reply to be a suggestion that the standard library uses pidfds rather than pids. The main reason not to is they aren't supported on e.g. BSDs.
