### ISSUE TITLE
defer can be confusing sometimes

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#1361]
The fallowing doesn't do what the programmer expects:
```
        node.lock();
        defer node.unlock();
        node = othernode;
```
For this reason, I think it makes more sense if stack-cleanup is defined with the variable, (like gcc's attribute(cleanup)[1] rather than through `defer`)

[1] http://echorand.me/site/notes/articles/c_cleanup/cleanup_attribute_c.html

**Comment by shawnl** [comment]
I guess that would require zero-initilizing memory however....

**Comment by isaachier** [comment]
Relates to #782.
