### ISSUE TITLE
coroutine semantics are unsound. proposal to fix them

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1363]
Currently there is a race condition when using multithreaded coroutines. Consider the following scenario:

1. Thread 1 does `epoll_wait`/`kevent`/`GetQueuedCompletionStatus`, blocking until some work can be done. The thread wakes up, and it is about to execute `resume coroutine_handle`.
2. Thread 2 is executing the coroutine, which reaches a suspend point, and then reads its atomic state and learns that it is scheduled to be canceled (destroyed). It runs the defers and errdefers, which dutifully remove the coroutine from the epoll set. However because of (1) it isn't even in the epoll set/kqueue/iocp. (1) is about to `resume` the coroutine and there's nothing (2) can do to stop it. (2) proceeds to destroy the coroutine frame. The memory is gone.
3. Thread 1 does `resume coroutine_handle` which now points to invalid memory. Boom.

In order to fix this, we need to introduce new syntax and semantics. Current semantics are:

 * `async` creates a `promise` which must be consumed with  `cancel` or `await`.
 * `suspend` must be consumed with a `resume`.

The problem here described above - `resume` and `cancel` racing with each other. When a suspended coroutine is canceled, the memory must not be destroyed until the `suspend` is canceled or resumed. Proposal for new semantics:

 * `async` creates a `promise` which must be consumed with  `cancelasync` or `await`.
 * `suspend` must be consumed with a `cancelsuspend` or `resume`.

With these semantics, each coroutine essentially has 0, 1, or 2 references, and when the reference count reaches 0 it is destroyed. There is the "async reference", which is the main one, and the "suspend reference", which might never exist.

Therefore it is crucial that when a coroutine uses `suspend` - which is a low level feature intended mainly for low level library implementations of concurrency primitives - that it ensures it will be consumed with either `resume` or `cancelsuspend`.

`defer` and `errdefer` will both run when a coroutine's cancellation process begins. This means that the first `cancelasync` or `cancelsuspend` will run the defers of the coroutine. When the other reference drops, the memory will be destroyed.

**Comment by shawnl** [comment]
The existing syntax is fine. What you describe has the same race condition but between `cancelsuspend` and `resume`.

The way I see to fix this is to wrap the `epoll_wait()` with a semaphore, and use the same semaphore to cancel the thread. To prevent deadlock, the cancel thread has to 
1. increment the semaphore. If it is 1, we have acquired the mutex and can cancel the thread, if 2, thread 1 is still in `epoll_wait()`. go to 2
2. deliver an event that will wake up the `epoll_wait()` thread
3. wait for the epoll thread to decrement the semaphore to 1
4. cancel the thread

**Comment by shawnl** [comment]
My proposal requires adding a `suspendnocancel` to the compiler. Everything else is user space. Also, what does promise point to, exactly? Can its' alignment be increased to 8 to allow stuff in that additional bit?

**Comment by shawnl** [comment]
Oh, I need 16-byte alignment, for 4 bits.

**Comment by shawnl** [comment]
this is blocked on `futex` support (and equivalent on other oses:`WaitOnAddress` on Windows,.)

**Comment by shawnl** [comment]
> The epoll loop will always call resume on its promises,

No it doesn't. If no events come it they never get resumed. And changing the loop to guarantee this is the same logic as knowing when to call `destroy`. The `cancel` part can be taken out of the promise type and become part of the loop: `.scheduleCancellation()`.

**Comment by andrewrk** [comment]
I think the scenario I outlined above is not actually a problem, because a coroutine couldn't be in the epoll set and executing at the same time. But here's a problem scenario:
1. Thread 1 does `epoll_wait`/`kevent`/`GetQueuedCompletionStatus`, blocking until some work can be done. The thread wakes up, and it is about to execute `resume coroutine_handle`.
2. Thread 2 does a `cancel` on the coroutine. Since it's at a suspend point, it runs the defers and errdefers, which dutifully remove the coroutine from the epoll set. However because of (1) it isn't even in the epoll set/kqueue/iocp. (1) is about to `resume` the coroutine and there's nothing (2) can do to stop it. (2) proceeds to destroy the coroutine frame. The memory is gone.
3. Thread 1 does `resume coroutine_handle` which now points to invalid memory. Boom.

With the proposed semantics:

1. Thread 1 does `epoll_wait`/`kevent`/`GetQueuedCompletionStatus`, blocking until some work can be done. The thread wakes up, and it is about to execute `resume coroutine_handle`.
2. Thread 2 does a `cancelasync` on the coroutine. Since it's at a suspend point, it runs the defers and errdefers, which dutifully remove the coroutine from the epoll set. However because of (1) it isn't even in the epoll set/kqueue/iocp. (1) is about to `resume` the coroutine and there's nothing (2) can do to stop it. However (2) does not destroy the coroutine frame because the `suspend` reference is present. The memory is still there.
3. Thread 1 does `resume coroutine_handle` which finds out that the thread has been canceled. So instead of resuming, it frees the memory.

**Comment by monouser7dig** [comment]
I think it would be best if Andrew were to implement his proposal and we could **test it/ fuzz it**.
I tried to think through this discussion and while Andrews explanation makes sense to me, I've made just enough concurrency bugs myself to know that this does not proof the correctness.

Testing the implementation does not give a proof either of course but I think its the best we can currently do until maybe zig attract some (other) domain expert that thinks it through.

I'd certainly be willing to run some test suit for an extensive time, compared to peoples time, hardware is cheap 😆

**Comment by kristate** [comment]
When I get some time later tonight, I will try to make another ASCII chart trying to clarify things. It's an area where we should be documenting.

**Comment by monouser7dig** [comment]
rather than ascii chart we'd need a formal state diagram/ automata with a formal proof, but I've seen a professor attempting the same and still failing (false positive actually) so...brute force is the best we have although its still no good.

**Comment by kristate** [comment]
@monouser7dig yes, I agree. An ASCII chart is no replacement for a formal proof. Baby steps.

**Comment by shawnl** [comment]
I think Andrew's proposal will work, but it had a memory leak.

**Comment by shawnl** [comment]
The bug as described could be fixed with a is_destroyed bit that is
atomically set. But I suspect that there are other bugs, and have been
trying to think the whole thing through.

**Comment by monouser7dig** [comment]
so after 0.3.0 is this the first major thing on the list?
like get async working, because the self hosted compiler needs it, network needs it (sort of?) and thus
- async (rewrite coroutines)
- self hosted + comptime allocator/ bugs + tooling 
- docs
- ??? lots of things

@andrewrk is this roughly accurate or what is to be expected?

**Comment by andrewrk** [comment]
Yes, this is accurate. Reworking coroutines is the first major thing on my list. That, plus something like one bug fix + one documentation improvement per day. [roadmap](https://ziglang.org/download/0.3.0/release-notes.html#roadmap)

**Comment by Matthias247** [comment]
Maybe related to this: I've written a few lines in Rust's `futures` repository why synchronous cancellation might not work out well for all use-cases: https://github.com/rust-lang-nursery/futures-rs/issues/1278

I guess similar things would apply to zig's coroutines as well, and it might in some cases be favorable to force them to run to completion (or at least to a safe exit point).

**Comment by andrewrk** [comment]
This issue is obsoleted with the merge of #3033.
