### ISSUE TITLE
Switch branch of noreturn union field with mutable capture is incorrectly semantically analyzed

### ISSUE THREAD

**Issue by ifreund** [ziglang/zig#13655]
### Zig Version

0.11.0-dev.168+b2ffe113d

### Steps to Reproduce and Observed Behavior

This test should pass, but it fails due to the `@compileError()` being triggered.
```zig
test "mutable capture of noreturn union field" {
    const U = union(enum) {
        a: u32,
        b: noreturn,
    };
    var a = U{ .a = 1 };
    switch (a) {
        .a => {},
        .b => |*val| {
            _ = val;
            @compileError("Shouldn't be triggered");
        },
    }
}
```

### Expected Behavior

The test should pass. Note that we have test coverage in place for immutable captures and the given test passes if `|val|` is used instead of `|*val|`.

**Comment by nektro** [comment]
should the compile error instead then be that a `.b` case was added since the compiler can know it should be unreachable in this case? related #12863

**Comment by ifreund** [comment]
No, there should be no compile error. See the existing noreturn union field behavior tests.

This example doesn't demonstrate the motivating use-case for this behavior, namely "disabling" a tagged union field based on a comptime-known value. For example

```zig
const View = union(enum) {
   xdg_toplevel: XdgToplevel,
   xwayland_view: if (build_options.xwayland) XwaylandView else noreturn,
}
```
