### ISSUE TITLE
slice memory corruption on method call

### ISSUE THREAD

**Issue by hundredwatt** [ziglang/zig#13663]
### Zig Version

0.11.0-dev.251+7c527c6df

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

fn unwrap(slice: []i32) i32 {
    // Commenting out this line fixes the output on Line 25:
    // std.debug.print("\n eval arg: {any}\n", .{slice[0]});
    return slice[0];
}

fn wrap(value: i32) []i32 {
    var arr: [1]i32 = undefined;
    arr[0] = value;

    // return arr[0..]; // same output
    return &arr;
}

pub fn main() void {
    var original: i32 = 255;
    var wrapped = wrap(original);

    std.debug.print("{}, {}\n", .{ original, wrapped[0] }); // prints '255, 255' as expected

    var unwrapped = unwrap(wrapped);

    std.debug.print("{}, {}\n", .{ original, unwrapped }); // prints '255, 3' unless Line 5 is commented out
}
```

```sh
$ zig run src/main.zig
255, 255
255, 3
```

### Expected Behavior

A compiler error to prevent dangling pointer

**Comment by InKryption** [comment]
The result of `wrap` is a dangling pointer to `arr`. That is to say, after the function returns, `arr` is popped off the stack, and gets overwritten by other memory e.g. variables declared in later functions using the same stack. This is undefined behavior, not a bug.

**Comment by hundredwatt** [comment]
Should this have been prevented with a compiler error?

**Comment by InKryption** [comment]
There is ongoing discussion about that. There was a pull request adding such a compile error, but it wasn't merged as it is unclear how to write it into the spec for now.
Related: #5725

**Comment by hundredwatt** [comment]
Closing as dup of #5725. Thank you @InKryption
