### ISSUE TITLE
Comment is not ignored through compiler if "@import" is in the line.

### ISSUE THREAD

**Issue by chrboesch** [ziglang/zig#13676]
### Zig Version

0.10.0

### Steps to Reproduce and Observed Behavior

When I have commented out this line:
```
// const impl = @import("aes/aesni.zig");
```
the compiler should ignore it. But I get the following error:
```
 error: unable to load 'aes/aesni.zig': FileNotFound const impl = @import("aes/aesni.zig");
```

### Expected Behavior

No error message.

**Comment by Vexu** [comment]
This looks like a caching issue, can you try deleting `zig-cache` to confirm?

**Comment by chrboesch** [comment]
After I cleared the cache, the error had actually disappeared. :+1:
