### ISSUE TITLE
Undescriptive traceback for structure/union/enum for inexistent field

### ISSUE THREAD

**Issue by rigobert9** [ziglang/zig#13688]
### Zig Version

0.11.0-dev.251+7c527c6df

### Steps to Reproduce and Observed Output

We can witness this compile error for any code that tries to access a nonexistent, and the LSP (zls) sometimes fails to provide the fields in the case of built-in objects (such as slices) (I will open an issue to them later).

I can nevertheless understand if this kind of feature is not welcome for the compiler : I think this kind of information should be up to the LSP. In this case, I will only verify the various problems I had with setting up the LSP.

Examples and output :
- For unions, pointing to the declaration without any more information :
  ```zig
  const Types = union {
      Array: [*]u8,
      Int: i8,
      Unsigned: u8,
      Type: type,
  };
  
  pub fn main() !void {
      const object = Types{ .Int = 8 };
      @import("std").log.debug("{}", .{object.List});
  }
  ```
  ```
  content-issue.zig:10:45: error: no field named 'List' in union 'content-issue.Types'
      @import("std").log.debug("{}", .{object.List});
                                              ^~~~
  content-issue.zig:1:15: note: union declared here
  const Types = union {
                ^~~~~
  ```
- Pretty much the same for enums
  ```zig
  const Types = enum {
      array,
      int,
      unsigned,
      sometype,
  };
  
  pub fn main() !void {
      const object: Types = .list;
      @import("std").log.debug("{}", .{object});
  }
  ```
  ```
  content-issue.zig:9:28: error: no field named 'list' in enum 'content-issue.Types'
      const object: Types = .list;
                            ~^~~~
  content-issue.zig:1:15: note: enum declared here
  const Types = enum {
                ^~~~
  ```
- The worst of all, not having any feedback
  ```zig
  pub fn main() !void {
    const array = [_]u8{ 8, 4, 3, 6, 5 };
    var length = array.len;
    const slice = array[0..length];
    @import("std").log.debug("{*}", .{slice.length}); }
  ```
  
  Which returns :
  ```
  content-issue.zig:7:34: error: no member named 'length' in '[]const u8'
  std.log.debug("{*}", .{slice.length});
                              ^~~~~~
  ```

### Expected Output

I would like this error to display the whole body/view of fields of the said enum/struct/union, especially when coming from the standard lib/builtins.

An exemple from the first case, what I ideally would like to see :
```
content-issue.zig:10:45: error: no field named 'List' in union 'content-issue.Types'
    @import("std").log.debug("{}", .{object.List});
                                            ^~~~
content-issue.zig:1:15: note: union declared here, containing
const Types = union { Array, Int, Unsigned, Type }
```

Thanks for your review, have a great day !

**Comment by Vexu** [comment]
I don't think there is a way to do this that would be viable for bigger containers. The `declared here` note is also all that is needed for those who can just clicking the path to make their editor open it at the right line.
