### ISSUE TITLE
Compiler panic when passing type as parameter in place of function

### ISSUE THREAD

**Issue by yujiri8** [ziglang/zig#13712]
### Zig Version

0.11.0-dev.375+648579b33

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");
const Random = std.rand.Random;
const DefaultPrng = std.rand.DefaultPrng;
pub fn main() void {
    var prng = DefaultPrng.init(0);
    var rng = prng.random();
    rng.init(u32);
}
```
I found this while trying to call `rng.int` and mispelling it.

### Expected Behavior

Type error but no compiler crash, as in stage1.

**Comment by Vexu** [comment]
> `panic: Zig compiler bug: attempted to destroy declaration with an attached error`

This issue is well known, here's one attempt at fixing it #13017
