### ISSUE TITLE
--emit asm/llvm-ir fails on windows

### ISSUE THREAD

**Issue by BarabasGitHub** [ziglang/zig#1371]
When I do `build-exe --emit asm` I get:
```
lld: error: <root>: undefined symbol: WinMainCRTStartup
```

When I do `build-lib --emit asm` I get:
```
lld: error: <root>: undefined symbol: _DllMainCRTStartup
```

Same for `--emit llvm-ir`

Without --emit it seems to work. At least it doesn't return an error.

**Comment by Sahnvour** [comment]
I looked a bit at this and figured that at [zig_llvm_emit_output](https://github.com/ziglang/zig/blob/780e5674467ebac4534cd3d3f2199ccaf1d0922c/src/codegen.cpp#L6418) adding `g->link_objects.append(output_path);` fixes the issue, and emitting asm/llvm-ir works again.
I can make a PR but I'm not sure this is a correct fix. @andrewrk your thoughts ?

**Comment by andrewrk** [comment]
I think we probably just want to not call codegen_link here: https://github.com/ziglang/zig/blob/780e5674467ebac4534cd3d3f2199ccaf1d0922c/src/codegen.cpp#L8237

if we are not emitting a binary.

Does that solve it?

**Comment by Sahnvour** [comment]
Yeah, makes more sense and works.
As it seems the `--emit` flag only wants what's specified as output and nothing more, I assume when doing `build-lib --emit [asm|llvm-ir]` we do not want the C header file generated ?

**Comment by Sahnvour** [comment]
If I understand correctly, the header is needed in case one wants to:
- distribute the library in binary form
- use the library inside a non-zig build system
and at this point, it does not seem like primary use cases (especially given that the second one is the contrary of your goal to make Zig the default build system).
I don't really see cons against this small change, but I haven't used Zig much yet.
