### ISSUE TITLE
flaky test: std.os timerfd

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#13721]
Observed test failure in the CI:

```
2022-11-30T20:12:00.5744629Z 1518/2238 test.timerfd... expected 1, found 0
```

https://github.com/ziglang/zig/blob/34f96c5fd068aeadfdbd1630fdea44fda2af1fdf/lib/std/os/test.zig#L1056-L1074

cc @thiagotps

**Comment by matu3ba** [comment]
The offending code is `try expectEqual(try os.poll(&fds, -1), 1); `, but -1 indicates no timeout.
From the [man page](https://man7.org/linux/man-pages/man2/poll.2.html):
```
The call will block until either:
       • a file descriptor becomes ready;
       • the call is interrupted by a signal handler; or
       • the timeout expires.
```

The usage also looks correct like in https://sites.google.com/site/rajboston1051/select/select-and-poll and handling of `EINTR` looks correct https://unix.stackexchange.com/a/509644
Linux Kernel docs also dont give a hint not to use timer events https://www.kernel.org/doc/html/v5.0/media/uapi/v4l/func-poll.html.

So after staring on this way too long, I have no clue what is going on.
