### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by kassane** [ziglang/zig#13731]
**Zig version:** 0.10.0 or master

I've been reviewing @MasterQ32 src looking to learn something about shunting-yard in a solution with comptime value.
However, even updating the code to the latest version of zig, I couldn't solve this last problem.

## Source test

https://godbolt.org/z/rz3c6PY9G

## Expected

Build and run.

## Result

```bash
/opt/compiler-explorer/zig-master/lib/std/builtin.zig:189:22: error: deprecated; use Type
pub const TypeInfo = @compileError("deprecated; use Type");
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Luukdegram** [comment]
Hi! We'd like to reserve the issue tracker for enhancements and bugs in the Zig toolchain. If you have any questions, I'd recommend joining one of the communities found on the wiki: https://github.com/ziglang/zig/wiki/Community

As for the issue you're having. As told by the compile error, change all occurrences of `std.builtin.TypeInfo` to `std.builtin.Type`.

**Comment by kassane** [comment]
Hi, @Luukdegram

I'm already part of the Zig discord community.
Ok, thank you. I saw the error!
I just found it strange that the compiler does not explicitly display the error lines.
