### ISSUE TITLE
Unable to download file on https://ziglang.org/download/

### ISSUE THREAD

**Issue by coffnix** [ziglang/zig#13734]
### Zig Version

riscv64-0.11.0-dev.426+fc3142aa9

### Steps to Reproduce and Observed Behavior

I'm having trouble downloading the source code directly from the download page on https://ziglang.org/download/

This file return 403 error:

https://ziglang.org/download/0.10.0/zig-linux-riscv64-0.11.0-dev.426+fc3142aa9.tar.xz

### Expected Behavior

it is impossible to download the file

**Comment by nektro** [comment]
workaround: url is here https://ziglang.org/builds/zig-linux-riscv64-0.11.0-dev.426+fc3142aa9.tar.xz

**Comment by leecannon** [comment]
Looks like the link is incorrect all the other master downloads are of the form:
`https://ziglang.org/builds/zig-TARGET-0.11.0-dev.426+fc3142aa9.tar.xz`

But riscv is :
`https://ziglang.org/download/0.10.0/zig-linux-riscv64-0.11.0-dev.426+fc3142aa9.tar.xz`

**Comment by nektro** [comment]
https://github.com/ziglang/www.ziglang.org/blob/9e9a0706/.github/workflows/index.json#L43 issue is here

**Comment by andrewrk** [comment]
Fixed in https://github.com/ziglang/www.ziglang.org/commit/af7063597c45a3fd6e0cc3e67275032d3fdc174c - thanks for the report.

**Comment by andrewrk** [comment]
Yes; the job that updates that file as well as the download page runs every 6 hours.
