### ISSUE TITLE
Typechecker incorrectly infers `u64` as `u6` in bitshift

### ISSUE THREAD

**Issue by fwcd** [ziglang/zig#13755]
### Zig Version

0.10.0

### Steps to Reproduce and Observed Behavior

Compile

```zig
const std = @import("std");

pub fn charToIndex(c: u8) usize {
    if (c >= 'a' and c <= 'z') {
        return @as(usize, c - 'a');
    } else {
        return @as(usize, c - 'A') + 26;
    }
}

pub fn toSet(s: []u8) u64 {
    var set: u64 = 0;
    for (s) |c| {
        const i = @as(u64, charToIndex(c));
        const one: u64 = @as(u64, 1);
        set |= one << i;
    }
    return set;
}

pub fn main() !void {
    var s = std.mem.zeroes([1024]u8);
    std.debug.print("{d}\n", .{toSet(&s)});
}
```

with `zig run <file.zig>`:

```
test.zig:16:23: error: expected type 'u6', found 'u64'
        set |= one << i;
                      ^
test.zig:16:23: note: unsigned 6-bit int cannot represent all possible unsigned 64-bit values
referenced by:
    main: test.zig:23:32
    callMain: /opt/homebrew/Cellar/zig/0.10.0/lib/zig/std/start.zig:606:32
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

### Expected Behavior

Not getting this error message. Perhaps there is some off-by-one string slicing somewhere in the typechecker that causes this strange `u64` -> `u6` coercion?

**Comment by travisstaloch** [comment]
this is not a bug. its a feature. the rhs of a `<<` must be a 'log2 int' type of the lhs. here the lhs is u64 so the rhs must be a u6. by 'log2 int' i mean that  (64 == 2 ^ 6).  i encourage you next time if you're not certain something is a bug to ask in one of the communities (https://github.com/ziglang/zig/wiki/Community) before opening an issue.

**Comment by fwcd** [comment]
Interesting, non-power-of-two int types just looked too strange to me to not be a bug 😄 Thanks for the pointers and sorry for not researching this more extensively!
