### ISSUE TITLE
Assertion passes in stage1, fails in stage2

### ISSUE THREAD

**Issue by axgdev** [ziglang/zig#13769]
### Zig Version

0.11.0-dev.479+f68bfe2eb

### Steps to Reproduce and Observed Behavior

I didn't manage to shorten it to the minimum code but here it goes:

```zig
const std = @import("std");
const bcrypt = std.crypto.pwhash.bcrypt;

const ArrayList = std.ArrayList;
var gpa = std.heap.GeneralPurposeAllocator(.{}){};
const test_allocator = gpa.allocator();

pub const User = struct {
    username: []const u8,
    passwordHash: []const u8,
    followedUsers: ArrayList([]const u8),
};

pub var users = std.StringHashMap(User).init(test_allocator);

const hash_options = bcrypt.HashOptions {
        .params = .{ .rounds_log = 5 },
        .encoding = .crypt,
    };

pub fn checkLogin(username: []const u8, password: []const u8) bool {
    var user = users.get(username);
    if (user == null) return false;

    bcrypt.strVerify(user.?.passwordHash, password, .{}) catch return false;
    return true;
}

pub fn addUser(username: []const u8, password: []const u8) !void {
    var buf: [bcrypt.hash_length]u8 = undefined;
    var passwordHash = try bcrypt.strHash(password, hash_options, &buf);

    var user = User{
        .username = username,
        .passwordHash = passwordHash,
        .followedUsers = ArrayList([]const u8).init(test_allocator),
    };
    try users.put(username, user);
}

pub fn main() !void {
    const username1 = "user1";
    const password1 = "password1";
    try addUser(username1, password1);
    var loginSuccess = checkLogin(username1, password1);
    std.debug.assert(loginSuccess == true);
}
```

The assertion in main fails under stage2 (zig build run) but passes on stage1 (zig build -fstage1)

### Expected Behavior

I would expect this to pass for stage2. An interesting fact is that if I change the `checkLogin` function to:
```zig
pub fn checkLogin(username: []const u8, password: []const u8) bool {
    var user = users.get(username) orelse return false;

    bcrypt.strVerify(user.passwordHash, password, .{}) catch return false;
    return true;
}
```

It passes the assertion in stage2 as well.

**Comment by Vexu** [comment]
> ```zig
>     var user = User{
>         .username = username,
>         .passwordHash = passwordHash,
>         .followedUsers = ArrayList([]const u8).init(test_allocator),
>     };
>     try users.put(username, user);
> ```

You're storing a pointer to a stack local variable `buf` in `users` and then immediately invalidating that pointer by returning.

**Comment by axgdev** [comment]
Hey, thanks for the quick reply, indeed that is a problem. It is still strange that it passes stage2 when I make the modification for `checkLogin`... I guess it is some weird pointer magic going on undetected
