### ISSUE TITLE
Importing a non-existing package should fail

### ISSUE THREAD

**Issue by clebs** [ziglang/zig#13778]
### Zig Version

0.11.0-dev.231+476b94680

### Steps to Reproduce and Observed Behavior

Compile an executable with this `main.zig`:
```zig
const std = @import("std");
const x = @import("blablabla"); // this package does not exist and is not added to build.zig

pub fn main() !void {
    std.debug.print("Somehow this compiles\n", .{});
}
```

### Expected Behavior

The compilation fails as the package does not exist.

I noticed that this does fail when trying to do something with `const x`. If trying to use the package then the right error shows up:
```
error: no package named 'blablabla' available within package 'root'
const x = @import("blablabla");
                  ^~~~~~~~~~~
```

Maybe a solution to avoid this case is detecting unused imports.

**Comment by clebs** [comment]
Thanks for the info! I might be misunderstanding, but shouldn't this work according to this comment?
https://github.com/ziglang/zig/issues/7867#issuecomment-843742710

**Comment by Vexu** [comment]
`"blablabla"` is not a file, it's a package and AstGen cannot know if it exists or not.
