### ISSUE TITLE
behavior tests are tripping an LLVM assertion on mips-linux: Invalid shift amount

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#13782]
### Zig Version

0.11.0-dev.526+9e74e4c1f

### Steps to Reproduce and Observed Behavior

Reproduction requires an LLVM built with assertions enabled. This is [documented in the wiki](https://github.com/ziglang/zig/wiki/How-to-build-LLVM,-libclang,-and-liblld-from-source#posix) and these assertions are one of the reasons it is recommended to work on the Zig compiler with an LLVM source build rather than the one provided by a system package.

```
$ stage4/bin/zig test ../test/behavior.zig -I../test -target mips-linux-none
LLVM Emit Object... zig: /home/andy/Downloads/llvm-project-15/llvm/include/llvm/ADT/APInt.h:840: void llvm::APInt::lshrInPlace(unsigned int): Assertion `ShiftAmt <= BitWidth && "Invalid shift amount"' failed.
```

### Expected Behavior

Expected the behavior tests to pass.

**Comment by jacobly0** [comment]
This appears to be an upstream llvm bug with global vectors that aren't a multiple of a byte on big-endian targets: https://godbolt.org/z/M7WzYYq6f

**Comment by nektro** [comment]
nice find, upstream https://github.com/llvm/llvm-project/issues/59055
