### ISSUE TITLE
@max always evaluates to first argument

### ISSUE THREAD

**Issue by gavinbeatty** [ziglang/zig#13797]
### Zig Version

0.10.0

### Steps to Reproduce and Observed Behavior

* Using `https://ziglang.org/download/0.10.0/zig-linux-aarch64-0.10.0.tar.xz` (also observed same behavior with `0.11.0-dev.537+36da3000c` from `zig-linux-aarch64-0.11.0-dev.537+36da3000c.tar.xz`)
* `mkdir zigrepro && cd zigrepro && zig init-exe`
* replace src/main.zig with the following:

```
const std = @import("std");

pub fn main() !void {
    const size = @max(@sizeOf(A), @sizeOf(B));
    const alignment = @max(@alignOf(A), @alignOf(B));
    //const size = std.math.max(@sizeOf(A), @sizeOf(B));
    //const alignment = std.math.max(@alignOf(A), @alignOf(B));
    var buf: [size]u8 align(alignment) = undefined;
    buf[0] = 1;
    std.debug.print("buf: [{}]u8 align({})\n", .{ size, alignment });
}

const A = extern struct {
    u32s: u32,
    u8_4: [4]u8,
    int: c_int,
};

const B = extern struct {
    u64s: u64,
    u8_16: [16]u8,
    int: c_int,
};

test "simple test" {
    const size = @max(@sizeOf(A), @sizeOf(B));
    const alignment = @max(@alignOf(A), @alignOf(B));
    //const size = std.math.max(@sizeOf(A), @sizeOf(B));
    //const alignment = std.math.max(@alignOf(A), @alignOf(B));
    std.debug.print("buf: [{}]u8 align({})\n", .{ size, alignment });
    var buf: [size]u8 align(alignment) = undefined;
    buf[0] = 1;
    try std.testing.expectEqual(@sizeOf(B), size);
    try std.testing.expectEqual(@alignOf(B), alignment);
}
```

* `zig build && { zig build test ; ./zig-out/bin/zigrepro ; }`

Observed the following output:

```
Test [1/1] test.simple test... buf: [12]u8 align(4)
expected 32, found 12
Test [1/1] test.simple test... FAIL (TestExpectedEqual)
/home/alarm/work/zigrepro/src/main.zig:33:5: 0x21fee7 in test.simple test (test)
    try std.testing.expectEqual(@sizeOf(B), size);
    ^
0 passed; 0 skipped; 1 failed.
error: the following test command failed with exit code 1:
/home/alarm/work/zigrepro/zig-cache/o/718e43fc5203c4e28e5fe01605f5f677/test
error: test...
error: The following command exited with error code 1:
/usr/lib/zig/zig test /home/alarm/work/zigrepro/src/main.zig --cache-dir /home/alarm/work/zigrepro/zig-cache --global-cache-dir /home/alarm/.cache/zig --name test --enable-cache
error: the following build command failed with exit code 1:
/home/alarm/work/zigrepro/zig-cache/o/26244de130306ca74f8349f94599cc81/build /usr/lib/zig/zig /home/alarm/work/zigrepro /home/alarm/work/zigrepro/zig-cache /home/alarm/.cache/zig test
buf: [12]u8 align(4)
```

### Expected Behavior

Expected the following output:

```
Test [1/1] test.simple test... buf: [32]u8 align(8)
All 1 tests passed.
buf: [32]u8 align(8)
```

If you replace the `@max` calls with `std.math.max`, the output is correct.

It's almost certainly possible to reduce the example further, but the above is pretty close to what I was working on when I found the issue (A and B are quite close to the `ip_mreqn` and `ipv6_mreq` structures for multicast membership operations).

**Comment by gavinbeatty** [comment]
I forgot to add, swapping the arguments so it is `@max(@sizeOf(B), @sizeOf(A))` evaluates to `@sizeOf(B)` which is correct, so it appears to just always evaluate to the first argument.

**Comment by matu3ba** [comment]
Interesting, because the [lang doc on max says](https://ziglang.org/documentation/master/#max) "This builtin accepts integers, floats, and vectors of either. In the latter case, the operation is performed element wise. "

Thus as I understand it, `@max` should return a compilation error.
