### ISSUE TITLE
Null character in source code can be used to mislead

### ISSUE THREAD

**Issue by r00ster91** [ziglang/zig#13811]
### Zig Version

0.11.0-dev.610+e7d28344f

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() void {
    std.debug.print("hello\n", .{});
}

    std.debug.print("...world?", .{});
}
```
```
$ zig run x.zig
hello
```
Note that you can't just copy-paste the code from here to reproduce because the null isn't included.

In Vim, to insert the null character, go to line 6, go into insert mode, press Ctrl+V, and then press the zero key three times.
Then it'll show up like this:
```
const std = @import("std");

pub fn main() void {
    std.debug.print("hello\n", .{});
}
^@
    std.debug.print("...world?", .{});
}
```
Now you should be able to reproduce this.

The null causes the file to stop being parsed at that point even though there is still (invalid in this case) source code coming after it.

We use this null to quickly check whether we're at the end of the file that we're tokenizing:
https://github.com/ziglang/zig/blob/096d3efae5fcaa5640f4acb2f9be2d7f93f7fdb2/lib/std/zig/tokenizer.zig#L428

The null character can be hard to see (maybe your text viewer doesn't highlight it) and it's easy to assume the above code would fail because of the code after the brace.

### Expected Behavior

Maybe an error that disallows any more characters after the terminating null character of the file?
I don't think we need to change the tokenizer for this but rather we can add such a check wherever we're reading in the file up to the null character in the compiler.

**Comment by r00ster91** [comment]
@Vexu what do you think of this solution alternatively?
```diff
+++ b/lib/std/zig/tokenizer.zig
@@ -1201,6 +1201,14 @@ pub const Tokenizer = struct {
                 return token;
             }
             result.loc.start = self.index;
+
+            if (self.index != self.buffer.len) {
+                // this happens if we have more than one null character in a file
+                result.tag = .invalid;
+                result.loc.end = self.index;
+                self.index += 1;
+                return result;
+            }
         }

         result.loc.end = self.index;
         return result;
     }
```
It passes these tests too:
```zig
test "null byte before eof" {
    try testTokenize("123 \x00 456", &.{ .number_literal, .invalid, .number_literal });
    try testTokenize("//\x00", &.{ .invalid });
    try testTokenize("\\\\\x00", &.{ .multiline_string_literal_line, .invalid });
    try testTokenize("\x00", &.{ .invalid });
}
```

**Comment by Vexu** [comment]
I'd prefer to keep the check where it's relevant.
