### ISSUE TITLE
langref: incorrect use of the term "enum variant" in enums.zig

### ISSUE THREAD

**Issue by perillo** [ziglang/zig#13838]
The doctest `enums.zig` in the `#enum` section has this example:
```zig
// An enum variant of different types can be switched upon.
const Foo = enum {
    string,
    number,
    none,
};
test "enum variant switch" {
    const p = Foo.number;
    const what_is_it = switch (p) {
        Foo.string => "this is a string",
        Foo.number => "this is a number",
        Foo.none => "this is a none",
    };
    try expect(mem.eql(u8, what_is_it, "this is a number"));
}
```

However, IMHO, the term *enum invariant* is used incorrectly; this term can be used in Rust, but not in Zig.  Also, the enum fields all have the same type.

NOTE: the term *enum invariant* is also used in #12186.

**Comment by gettsu** [comment]
I am looking to address this issue.
I'm thinking to modify
1.  "// An enum variant of different types can be switched upon." to "// enum can be switched upon"
2. "enum variant switch" to " enum switch"
I'll submit a pull request if this is okay.
