### ISSUE TITLE
langref: document tuple type declarations

### ISSUE THREAD

**Issue by perillo** [ziglang/zig#13837]
Document the new *tuple type declarations* (#4335).

Here is a possible example:
```zig
const std = @import("std");

pub fn main() void {
    const KV = struct { usize, []const u8 };
    const map = [_]KV{
        .{ 1, "1" },
        .{ 2, "2" },
        .{ 3, "3" },
    };

    std.debug.print("map: {any}\n", .{map});
}
```

**Comment by perillo** [comment]
The wording used in section `#Anonymous-List-Literals` should also be changed or should be removed completely in favor of the new `#tuples` section.

**Comment by yujiri8** [comment]
I'm going to take a stab at this

**Comment by perillo** [comment]
Not sure, but I think the *Type Coercion* section should be updated, since it is possible to coerce a tuple to an array (but not vice versa).

This had always be possible (see `tuple.zig` and `anon_list.zig`), however, as an example,  the tuple `.{1, 2, 3}` was both called *struct literal* **and** *array literal*.

**Comment by yujiri8** [comment]
I think you're right. I'm adding a section on it to the pull request. But while we're at it, what do you think of this? I'm able to do:
```zig
    const V = struct { u8, u8 };
    const v: V = .{ 6, 4 };
```
But this:
```zig
    const V = struct { u8, u8 };
    const v = V{ 6, 4 };
```
Fails with:
```
t.zig:4:16: error: expected at most 0 tuple fields; found 2
    const v = V{ 6, 4 };
              ~^~~~~~~~
```

Is this a bug?

**Comment by perillo** [comment]
> But this:
> 
> ```zig
>     const V = struct { u8, u8 };
>     const v = V{ 6, 4 };
> ```
> 
> Fails with:
> 
> ```
> t.zig:4:16: error: expected at most 0 tuple fields; found 2
>     const v = V{ 6, 4 };
>               ~^~~~~~~~
> ```
> 
> Is this a bug?

I don't know if `V{6, 4}` is supposed to be valid syntax, but the error message should be improved, because 0 tuple fields will cause a compiler error.

**Comment by perillo** [comment]
> Not sure, but I think the _Type Coercion_ section should be updated, since it is possible to coerce a tuple to an array (but not vice versa).
> 

Looking at the commit log, I found:

  - 4758752e5 Sema: implement coercion from tuples to tuples
  - b66247c97 stage2: coerce tuple to vector
  - 51ef31a83 Sema: add empty tuple to mutable slice coercion
  - f736cde39 Sema: implement pointer to tuple to pointer to array coercion
  - f32a77b30 Sema: implement pointer-to-tuple coercion to slice and struct
  - bb73775d4 Sema: implement coercion of tuples to structs

Here is a test:
```zig
const Triple = struct { u8, u8, u8 };
var triple: Triple = .{ 1, 2, 3 };

test "coerce tuple to struct" {
    const S = struct {
        @"0": u8,
        @"1": u8,
        @"2": u8,
    };

    var s: S = triple;
    _ = s;
}

test "coerce pointer to tuple to slice" {
    // note: pointers to tuples can only coerce to constant pointers
    const slice: []const u8 = &triple;
    _ = slice;
}

test "coerce pointer to tuple to pointer to array" {
    var array: *[3]u8 = &triple;
    _ = array;
}

test "coerce empty tuple to mutable slice" {
    // NOTE: This is an empty struct, not a tuple.
    var slice: []u8 = &.{};
    _ = slice;
}

test "coerce tuple to Vector" {
    const Vec3 = @Vector(3, u8);

    var v: Vec3 = triple;
    _ = v;
}

test "coerce tuple to tuple" {
    const Triple2 = struct { u32, u32, u32 };

    var tuple: Triple2 = triple;
    _ = tuple;
}
```
