### ISSUE TITLE
no error for undeclared struct fields usage inside `errdefer`

### ISSUE THREAD

**Issue by alichraghi** [ziglang/zig#13844]
### Zig Version

0.11.0-dev.368+1829b6eab

### Steps to Reproduce and Observed Behavior

```zig
const S = struct {};
test {
    var s = S{};
    errdefer s.whatever_u_want = "zzzzzzzzzz";
}
```
```
$ zig test z.zig
All 1 tests passed.
```

### Expected Behavior

undeclared identifier error

**Comment by Vexu** [comment]
This is working as intended, the errdefer is never analyzed since no error is ever returned.
