### ISSUE TITLE
Document how to build the language reference

### ISSUE THREAD

**Issue by yujiri8** [ziglang/zig#13863]
### Zig Version

0.11.0-dev.612+8ccb9a6ad

### Steps to Reproduce and Observed Behavior

No documentation on how to build the language reference, making it difficult to contribute to it.

I tried running doc/docgen.zig with the three arguments it requests (path to zig build, langref input, and output html filename), but it just generated a giant code file instead of an html page, so I assume this is the wrong process.

### Expected Behavior

This process should be documented in the repository readme or wiki.

**Comment by andrewrk** [comment]
`zig build docs`

**Comment by yujiri8** [comment]
This command appeared to succeed but I don't see the generated file anywhere. It's not in `doc/`, `build/` or `zig-out/`.

Also, I asked this question in `#zig:matrix.org` and experienced Zig community members told me they didn't know how to do it either. I think that makes it pretty clear this process needs to be better documented.

**Comment by andrewrk** [comment]
currently it is hard-coded to go into `zig-cache/langref.html`. you are welcome to make changes to the wiki or submit a pull request to CONTRIBUTING.md.
