### ISSUE TITLE
Document new build process

### ISSUE THREAD

**Issue by yujiri8** [ziglang/zig#13861]
### Zig Version

0.11.0-dev.612+8ccb9a6ad

### Steps to Reproduce and Observed Behavior

My understanding is that zig's build process changed after the [death of stage1](https://ziglang.org/news/goodbye-cpp/), but I can't find any documentation about it. [The wiki page](https://github.com/ziglang/zig/wiki/Building-Zig-From-Source) still reflects the old one.

### Expected Behavior

The wiki should describe the new build process.

**Comment by andrewrk** [comment]
The wiki page is still correct.
