### ISSUE TITLE
Missing Debug Information from Runtime Variable in Debug Build

### ISSUE THREAD

**Issue by paoda** [ziglang/zig#13868]
### Zig Version

0.11.0-dev.664+c49e4d534

### Steps to Reproduce and Observed Behavior

See the following program: 
```zig
pub fn main() !void {
    const limit: usize = 10;

    {
        var i: usize = 0;
        while (i < limit) : (i += 1) {
            _ = square(usize, i);
        }
    }
}

fn square(comptime T: type, left: T) T {
    const right = left;

    @breakpoint();
    return left * right;
}
```

Build with `zig init-exe main.zig` and run gdb using `gdb main` in the same folder.

![image](https://user-images.githubusercontent.com/22038970/206844008-f42bd7a0-376a-42fc-80f0-42d0da9c8114.png)

### Expected Behavior

`p/x left` in the GDB console should display the symbol's contents. However, nothing happens.

**Comment by paoda** [comment]
Perhaps it's worth mentioning that in the above example, `T` happens to have a runtime value 
![image](https://user-images.githubusercontent.com/22038970/206844572-6d6dfa41-2a1d-4e18-bfc9-86cf74bceb4d.png)

**Comment by matu3ba** [comment]
Not sure, if related. Debug symbols also look incomplete here: #13571
