### ISSUE TITLE
Enable CI coverage for ARM64 Windows

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#13862]
I have purchased a Microsoft Windows ARM64 dev kit and ready to donate it to the CI.

It's almost working. Here is where I left off on this (in the `ci-test` branch):

 * [x] add one more GitHub Actions runner to the box
 * [x] relocate the machine to somewhere in my house that it can be long term
 * [x] use the previous run's tarball instead of downloading a new one every time
 * [x] install system stuff such as CMake, Ninja, and Git
 * [x] [document the setup process on the Wiki](https://github.com/ziglang/zig/wiki/Setting-up-an-ARM64-Windows-Dev-Kit-to-be-a-CI-Runner) so that it is repeatable
 * [x] fixes to the CI script to make it build
 * [x] solve the crash that is happening below

```
[26/31] Running zig1.wasm to produce C:/actions-runner/_work/zig/zig/build-release/zig2.c
FAILED: zig2.c C:/actions-runner/_work/zig/zig/build-release/zig2.c 
cmd.exe /C "cd /D C:\actions-runner\_work\zig\zig && C:\actions-runner\_work\zig\zig\build-release\zig1.exe C:/actions-runner/_work/zig/zig/lib build-exe src/main.zig -ofmt=c -lc -OReleaseSmall --name zig2 -femit-bin="C:/actions-runner/_work/zig/zig/build-release/zig2.c" --pkg-begin build_options C:/actions-runner/_work/zig/zig/build-release/config.zig --pkg-end -target aarch64-windows"
ninja: build stopped: subcommand failed.
```

Looks like a crash when running the interpreted wasm binary. The next step here is probably to do the following:
 * Produce a debug build of zig1.wasm which has safety checks enabled and will e.g. print "attempted to unwrap null" instead of segfaulting.
 * Patch CMakeLists.txt to disable optimizations for zig1.c and enable debug info
 * Run the build process in a debugger and look at a stack trace

**Comment by jacobly0** [comment]
For reference, the zig1 crash was fixed by #13867.
