### ISSUE TITLE
Futex premature/over optimization

### ISSUE THREAD

**Issue by kristate** [ziglang/zig#1388]
@andrewrk @tiehuis I was talking to @winksaville in IRC and he said that he was experiencing zig over optimizing (cutting code that is valuable to operation), so I asked him to do a write-up, and he graciously did such a thing. Please check it out:

https://github.com/winksaville/zig-futex-over-optimization

Thank-you!

**Comment by winksaville** [comment]
It should be noted that I failed to make a "simple" example, as I stated in the last sentence which people might miss, so I thought I'd state it here.

Also, AFAICT, from a neophytes look at llvm-ir the "over" optimization was done not by zig but by llvm. But, I'm guessing there is information zig should add to the llvm-ir so the backend won't "over" optimize.

**Comment by andrewrk** [comment]
@winksaville thank you for the detailed writeup - this is wonderfully helpful.

**Comment by winksaville** [comment]
Note, there is an easy solution that I'm using in my ActorModel test for futex, use [fn's for the stall code](https://github.com/winksaville/zig-futex-over-optimization/tree/solution1-fn-stall). The code is better with the fn's, but I'd say you shouldn't have to do that.

**Comment by winksaville** [comment]
I decided to rename the branch to [workaround1-fn-stall](https://github.com/winksaville/zig-futex-over-optimization/tree/workaround1-fn-stall).

**Comment by andrewrk** [comment]
I believe this was addressed by @kprotty's work. Please re-open if not.
