### ISSUE TITLE
Perf improvement idea for HashMap.Iterator.next()

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#13899]
The `Metadata.isUsed` function checks a u1:

https://github.com/ziglang/zig/blob/5238f9c409cdf40db6a1484ab79a7bc518f8f6ad/lib/std/hash_map.zig#L777-L785

`Iterator.next()`:

https://github.com/ziglang/zig/blob/5238f9c409cdf40db6a1484ab79a7bc518f8f6ad/lib/std/hash_map.zig#L823-L843

We could load the `Metadata` as an `@Vector(u8, 16)` and then find the first index of the element with the final bit set

**Comment by andrewrk** [comment]
Please see https://github.com/ziglang/zig/pull/14047#issuecomment-1877807675
