### ISSUE TITLE
langref: document the extern keyword optional string

### ISSUE THREAD

**Issue by perillo** [ziglang/zig#13906]
In the *C* language, the optional string of the `extern` keyword determines the call convention, as with
```C
extern "C" ...
```

In Zig, however, the calling convention is determined by the `callconv` keyword, and the optional string value of the `extern` keyword is only used to link to the specified lib. As an example:

```zig
extern "c" fn atan2(...
```
will link to `libc.so`

and
```zig
extern "kernel32" fn ExitProcess(...
```
will link to `kernel32.dll`.

However this is not documented in the Zig Language Reference, and I'm not sure it is correct.

**Comment by Arnau478** [comment]
From the docs, https://ziglang.org/documentation/0.10.1/#Sentinel-Terminated-Pointers
```zig
// This is also available as `std.c.printf`.
pub extern "c" fn printf(format: [*:0]const u8, ...) c_int;
```

This suggests that `extern "..."` works that way. It's just a little bit weird that it's only suggested in [Sentinel-Terminated Pointers](https://ziglang.org/documentation/0.10.1/#Sentinel-Terminated-Pointers). Maybe this should be improved. But the thing is that there's not even a place for documentating `extern` alone...
