### ISSUE TITLE
`zig build --zig-lib-dir lib` in the zig repo segfaults

### ISSUE THREAD

**Issue by r00ster91** [ziglang/zig#13929]
### Zig Version

0.11.0-dev.638+5c67f9ce7

### Steps to Reproduce and Observed Behavior

```
/zig$ zig build --zig-lib-dir lib
Segmentation fault (core dumped)
```

### Expected Behavior

```
/zig$ zig build --zig-lib-dir lib
/zig$
```

**Comment by Vexu** [comment]
Your Zig binary and standard library are likely different versions. #13821 broke compatibility in a way that is only noticeable with safety checks.

**Comment by r00ster91** [comment]
You're right! Works now.
