### ISSUE TITLE
std.Thread: Recursive mutex

### ISSUE THREAD

**Issue by Maetveis** [ziglang/zig#13920]
A recursive mutex is a commonly used locking primitive, where re-locking from the same thread is allowed, and the lock is held until a matching number of locks/unlocks are called.

Recursive mutexes can be safely used in functions with foreign callbacks (where it cannot be guaranteed that the called function does not itself transitively lock the mutex).

The current `std.Thread.Mutex` is not recursive per its documentation:
> ## pub fn lock(self: *Mutex) void
> It is undefined behavior if the mutex is already held by the caller's thread.

Implementation should be possible using `std.Thread.Futex` and `std.Thread.getCurrentId()` (altough one problem is that Futex can only wait on `u32` while `std.Thread.getCurrentId()` returns `u64`).

**Comment by matu3ba** [comment]
What is the use case for recursive mutexes? Take note, that recursion is only supported up to a certain limit.
The last one I have seen in glibc for the exit code is a rather aweful hack to work around poorly designed user code and musl doesnt use it.

**Comment by Maetveis** [comment]
> What is the use case for recursive mutexes?

My use case was using [libevent](https://libevent.org/) without pthread, it [requires recursive locks](https://libevent.org/doc/structevthread__lock__callbacks.html#afebbd92f9fc12e5852b0c008b423f948).

One similar use case we came across with a collague on [OpenCL-Layers](https://github.com/KhronosGroup/OpenCL-Layers/search?q=recursive_mutex). This will be a long explanation but bear with me:

The OpenCL API has a concept of _layers_, a _layer_ is a library which intercepts calls into the OpenCL runtime. Layers form a hiearchy between the application and the underlying runtime, i.e. a layer might call into the layers below it finally ending up in the runtime at the last layer.

When an OpenCL api call is made the loader calls the topmost layer which implements that function or the runtime of no such layer exists.

Layers _can_ call OpenCL APIs directly (this can be useful for e.g. emulating new APIs with existing ones), in which case the call might end up in the same layer. If locking is required in this scenario (OpenCL is an implicitly thread safe API as in no external locking is required to use it), then recursive locks are a good option to avoid deadlocks.

 > Take note, that recursion is only supported up to a certain limit.
 
 That's not a problem from a recursive locks perspective it could even have the same limit as the language itself for maximum depth of locking.

> The last one I have seen in glibc for the exit code is a rather aweful hack

Yes in fact looking this up I found this [writeup by David Butenhof on recursive locks](http://www.zaval.org/resources/library/butenhof1.html).

**Comment by zxubian** [comment]
I was actually researching recursive mutexes recently, so I took a crack at implementing them in the following PR: https://github.com/ziglang/zig/pull/14103

**Comment by zxubian** [comment]
Re-posting some discussion points from the PR here:

1. biggest one: should recursive/reentrant mutexes be included into the standard library in the first place?
2. if so, should they be given their own type, or integrated into `std.Thread.Mutex`?  (the latter would be similar to[ how pthread mutexes work](https://www.ibm.com/docs/en/zos/2.2.0?topic=lf-pthread-mutexattr-settype-set-type-mutex-attribute-object))
3. is `usize `a suitable size for the recursion depth (i.e. # of allowed re-entries)? Perhaps it's worth making RecursiveMutex generic and take an integer size as a parameter?

**Comment by kprotty** [comment]
One could build recursive mutexes on top of normal mutexes. Something like this
```py
mutex: Mutex = .{}
tid: Thread.Id = undef
depth: usize = 0

lock():
  t = gettid()
  if LOAD(&depth) > 0 and LOAD(&tid) == t:
    return STORE(&depth, depth + 1)
  mutex.lock()
  STORE(&depth, 1)
  STORE(&tid, t)
  
unlock():
  STORE(&depth, depth - 1)
  if depth == 0:
    mutex.unlock()
```

Given how 1) recursive locking is rare and 2) locking to synchronize data structures without tiny critical sections is an anti-pattern, I don't think a RecursiveMutex should be in the standard library. If it were to, it should be a separate type from `Mutex` to avoid adding overhead for the latter.

**Comment by Rexicon226** [comment]
this can be closed after https://github.com/ziglang/zig/pull/20268
