### ISSUE TITLE
Setting an individual element of a vector of u1 sets all elements

### ISSUE THREAD

**Issue by notcancername** [ziglang/zig#13925]
### Zig Version

0.11.0-dev.672+e94504543

### Steps to Reproduce and Observed Behavior

1. Compile this code with `zig build-exe` on x86_64 
```zig
const std = @import("std");

pub fn main() void {
    var v = @Vector(4, u1){1, 1, 1, 1};
    std.debug.print("{any}\n", .{v}); // { 1, 1, 1, 1 }
    v[0] = 0;
    std.debug.print("{any}\n", .{v}); // expected { 0, 1, 1, 1}, got {0, 0, 0, 0}
}
```
2. Run the generated executable. Observe that the output does not match the expected output.

### Expected Behavior

I expected the generated executable to print
```
{ 1, 1, 1, 1 }
{ 1, 1, 1, 1}
```
, but it printed
```
{ 1, 1, 1, 1 }
{ 0, 0, 0, 0 }
```
.

**Comment by nektro** [comment]
different but related: https://github.com/ziglang/zig/issues/13279
