### ISSUE TITLE
Expected ArrayList.clone() to work on a `*const Self`

### ISSUE THREAD

**Issue by jcorbin** [ziglang/zig#13927]
### Zig Version

0.10.0-dev.3880+e2bb92b2e2

### Steps to Reproduce and Observed Behavior

While writing a struct with an array list field, and implementing its clone method:
```zig

const SomeType = struct {
    const Self = @This();

    const Path = std.ArrayListUnmanaged(struct {
        // item fields...
    });

    allocator: Allocator,
    path: Path,
    // other fields...

    // other typical methods here like init()/deinit() etc...

    pub fn clone(self: *const Self) !*Self {
        var copy = try self.allocator.create(Self);
        errdefer self.allocator.destroy(copy);

        var path = try self.path.clone(self.allocator);
        errdefer path.deinit(self.allocator);

        // copying of other fields here...

        copy.* = .{
            .allocator = self.allocator,
            .path = path,
            // etc...
        };
        return copy;
    }
};
```

I'd expected to be able to "clone a const self", but the `path.clone()` line prevented it due to ArrayList.clone having a mere `self: *Self` parameter.

Conversely `std.DynamicBitSetUnmanaged.clone()` does take a `*const Self` ( one of my "other fields" ).

### Expected Behavior

To be able to clone a `*const std.ArrayList(T)`

**Comment by yujiri8** [comment]
I'm confused why this doesn't already work. ArrayList.clone's parameter type is `Self`, not `*Self`.

**Comment by Vexu** [comment]
It's because they're using an old version #13773
