### ISSUE TITLE
broken array

### ISSUE THREAD

**Issue by 20kano** [ziglang/zig#13934]
### Zig Version

0.11.0-dev.753+331861161

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");
const print = std.debug.print;

pub fn main() !void {
	var w = Window.init();
	w.run();
}

pub const Window = struct {
    _layout: Layout = undefined,
    pub fn init() Window {
        var w = Window{};
        w._layout = Layout.init(&w);
        return w;
    }
    pub fn run(self: *Window) void {
		self._layout.draw();
    }
};

pub const Layout = struct{
    _view: ViewBase,
    _views: []IView = undefined,

    pub fn init(win: *Window) Layout{
        return Layout{
			._view = ViewBase.init(win)
        };
    }
    pub fn draw(self: Layout) void{
		print("{}\n", .{self._views.len});
		for (self._views)|v, i|{
			print("{},{}\n", .{v, i});
		}
    }
};

pub const ViewBase = struct {
    _window: *Window,
    pub fn init(win: *Window) ViewBase{
        return ViewBase{
			._window = win
		};
    }
};

pub const IView = struct {
    impl: *anyopaque,
    drawFn: *const fn (*anyopaque) void,
    pub fn draw(iface: *const IView) void {
        return iface.drawFn(iface.impl);
    }
};
```
```
> zig build run
12297829382473034410
Segmentation fault at address 0x0
/zigprojects/tradeapp/src/bug.zig:33:9: 0x20d6c5 in draw (tradeapp)
                        print("{},{}\n", .{v, i});
        ^
/zigprojects/tradeapp/src/bug.zig:17:20: 0x20c998 in run (tradeapp)
                self._layout.draw();
                   ^
/zigprojects/tradeapp/src/bug.zig:6:7: 0x20c8c8 in main (tradeapp)
        w.run();
      ^
/lang/zig/lib/std/start.zig:614:37: 0x20cdb9 in main (tradeapp)
            const result = root.main() catch |err| {
                                    ^
```

### Expected Behavior

expected it prints like this
```
> zig build run
0
```

This works.
```zig
const std = @import("std");
const print = std.debug.print;

pub fn main() !void {
	var w = Window.init();
	w.run();
}

pub const Window = struct {
    _layout: Layout = undefined,
    pub fn init() Window {
        var w = Window{};
        w._layout = Layout.init(&w);
        return w;
    }
    pub fn run(self: *Window) void {
		self._layout.draw();
    }
};

pub const Layout = struct{
    _view: ViewBase,
    _views: []IView = undefined,

    pub fn init(win: *Window) Layout{
        return Layout{
			._view = ViewBase.init(win)
        };
    }
    pub fn draw(self: Layout) void{
		print("{}\n", .{self._views.len});
		for (self._views)|v, i|{
			print("{},{}\n", .{v, i});
		}
    }
};

pub const ViewBase = struct {
    // _window: *Window,
    pub fn init(win: *Window) ViewBase{
		_ = win;
        return ViewBase{
			// ._window = win
		};
    }
};

pub const IView = struct {
    impl: *anyopaque,
    drawFn: *const fn (*anyopaque) void,
    pub fn draw(iface: *const IView) void {
        return iface.drawFn(iface.impl);
    }
};
```
Also this.
```zig
const std = @import("std");
const print = std.debug.print;

pub fn main() !void {
	var w = Window.init();
	w.run();
}

pub const Window = struct {
    _layout: Layout = undefined,
    pub fn init() Window {
        var w = Window{};
        w._layout = Layout.init(&w);
        return w;
    }
    pub fn run(self: *Window) void {
		self._layout.draw();
    }
};

pub const Layout = struct{
    // _view: ViewBase,
    _views: []IView = undefined,

    pub fn init(win: *Window) Layout{
		_ = win;
        return Layout{
			// ._view = ViewBase.init(win)
        };
    }
    pub fn draw(self: Layout) void{
		print("{}\n", .{self._views.len});
		for (self._views)|v, i|{
			print("{},{}\n", .{v, i});
		}
    }
};

pub const ViewBase = struct {
    _window: *Window,
    pub fn init(win: *Window) ViewBase{
        return ViewBase{
			._window = win
		};
    }
};

pub const IView = struct {
    impl: *anyopaque,
    drawFn: *const fn (*anyopaque) void,
    pub fn draw(iface: *const IView) void {
        return iface.drawFn(iface.impl);
    }
};
```

**Comment by IntegratedQuantum** [comment]
Setting something to [undefined](https://ziglang.org/documentation/master/#undefined) means that the value can be absolutely anything.
In this case `_views.len` just so happens to be `12297829382473034410`.

If you want `_views.len` to be `0` then you need to explicitely set it to zero.
This can for example be done in the `init` function like this:
```zig
    pub fn init(win: *Window) Layout{
        var result = Layout{
			._view = ViewBase.init(win)
        };
        result._views.len = 0;
        return result;
    }
```

**Comment by squeek502** [comment]
Or, even better, set it to a real zero length slice. This is what, for example, `std.ArrayList` does:

https://github.com/ziglang/zig/blob/0b4461d97b5d315e71302f96076c54bbdffb7717/lib/std/array_list.zig#L57

In your case, you'd want:

```zig
    _views: []IView = &[_]IView{},
```

In the future, it'd be better to seek help with problems like this in one of the community spaces first: https://github.com/ziglang/zig/wiki/Community

**Comment by 20kano** [comment]
Thanks, since this works as expected, then I thought this is just a bug.
```zig
const Foo = struct {
    arr: []u8 = undefined,
    fn foo(self: Foo) void {
        print("undefined arr.len = {}\n", .{self.arr.len});
        for (self.arr)|a|{
            print("{}\n", .{a});
        }
    }
};

test "array undefined" {
    const f= Foo{};
    f.foo();
}
```

**Comment by 20kano** [comment]
> If you want `_views.len` to be `0` then you need to explicitely set it to zero.

My problem was not that I wanted len==0.
Commenting out the part that has nothing to do with it works correctly, as in the two examples below.
I considered this inconsistency to be a bug.

**Comment by tato** [comment]
Setting `_views` to undefined can make it be anything, even a zero-length slice. That makes your examples work, but only as a coincidence.

**Comment by mlugg** [comment]
> The for loop should exit without executing the loop if the given variable is undefined, or should throw an error.

`undefined` values can't be detected by the language at runtime: that's pretty much the whole point, it tells the language that you don't care what the value is for now. It's unrelated to `undefined` in languages like JS, where it's a distinct value you can detect. It should only be used when you're not going to use that value at all before later assigning it.

**Comment by 20kano** [comment]
Thanks for the explanation.
I had seen this explanation and thought it was technically detectable.

> In [Debug](https://ziglang.org/documentation/master/#Debug) mode, Zig writes 0xaa bytes to undefined memory. This is to catch bugs early, and to help detect use of undefined memory in a debugger.

**Comment by 20kano** [comment]
I'm sorry, I may have misunderstood. Is it a for loop you are talking about?

**Comment by mlugg** [comment]
I'm just talking about `undefined` values in general. In debug builds, Zig initializes all bytes of `undefined` memory to `0xAA` - that's not so it can be accurately detected at runtime (because it can't! it's indistinguishable from an actual value of `0xAA`), but instead so that if you're looking at values in a debugger, you'll notice this value in places you wouldn't expect it to be and find whatever bug you're looking for.
`for` loops aren't involved here - looping over an undefined slice is undefined behaviour. In a debug build, it'll try to iterate over `0xAAAAAAAAAAAAAAAA` elements starting at the address `0xAAAAAAAAAAAAAAAA`, normally resulting in either a segfault (if you try to deref the pointer) or a seemingly-infinite loop (since that's a ridiculously large number of elements).

**Comment by Jarred-Sumner** [comment]
Wouldn't this be a useful safety check in debug mode? Is there a situation where a `for` loop on an undefined value is desirable?

**Comment by Vexu** [comment]
> Wouldn't this be a useful safety check in debug mode? Is there a situation where a `for` loop on an undefined value is desirable?

It would be, that's why #211 exists.

**Comment by 20kano** [comment]
```v
    pub fn draw(self: Layout) void {
        for (self._views) |i| {
            _ = i;
        }
    }
```
```zig
pub const IView = packed struct {
```
btw, with `packed`, soon Segmentation fault, but without `packed`,  infinite.
