### ISSUE TITLE
Automatic memory management

### ISSUE THREAD

**Issue by nordlow** [ziglang/zig#1393]
Are there any plans for adding (optional) automatic memory management in Zig? Typically as a mark-and-sweep garbage collector or similar?

**Comment by Ilariel** [comment]
There have been discussions about this before (e.g. issue #1063) and GC doesn't exactly fall into goals of zig. So no, there are no plans to add a garbage collector to the runtime/language.

However anyone who is willing to do so could implement an allocator that uses conservative garbage collector behind the scenes.

**Comment by nordlow** [comment]
I was mainly interested in getting automatic memory management into Zig in a more memory-safe way than what is possible in a library solution. Has there been any thoughs in this direction in the Zig community?

Thanks, anyway.

**Comment by RaphiJS6-13** [comment]
_Automatic_ memory management? Nothing is automatic in Zig; there's no hidden control flow.
