### ISSUE TITLE
Package path resolution with custom test runners

### ISSUE THREAD

**Issue by dweiller** [ziglang/zig#13970]
### Zig Version

0.11.0-dev.286+58d3ee2a0 (the changes in the commit before this are the relevant ones, but that commit doesn't compile)

### Steps to Reproduce and Observed Behavior

Make a source tree like:
```
root/
    src/
        main.zig
        package.zig
    example/
        empty.zig
```
Where `empty.zig` is an empty file and `main.zig` is:
```zig
const package = @import("package.zig");

pub fn main() void {
    _ = package.decl;
}
```
and `package.zig` is:
```zig
pub decl = 0;
```
Then run `zig test --test-no-exec --test-runner src/main.zig example/empty.zig`. The error is:
```
src/main.zig:2:25: error: import of file outside package path: 'package.zig'
const package = @import("package.zig");
                        ^~~~~~~~~~~~~
```
The issue seems to be some change in how packages are resolved relative to the main pkg vs root pkg when using custom test runners (test compilations are the only situation where the main and root packages differ).

### Expected Behavior

The (test) executable should compile (it did for previous zig versions since custom test-runners were introduced).

If this isn't considered a bug, this issue could be subsumed by a more general rework of importing in test builds, which could include #12201, though I'd guess this is an easier use-case to solve.

**Comment by squeek502** [comment]
FYI, your example needs a few fixes:
- `package.zig` is not in your source tree (I assume `decl.zig` is meant to be `package.zig`)
- Your `main.zig` is missing quotes around `package.zig`

**Comment by dweiller** [comment]
> FYI, your example needs a few fixes[...]

Whoops, fixed.

**Comment by davidgm94** [comment]
The issue seems to be happening in `Module.importModule`

If you take the function

```zig
pub fn importFile(
    mod: *Module,
    cur_file: *File,
    import_string: []const u8,
) !ImportFileResult {
    if (std.mem.eql(u8, import_string, "std")) {
        return mod.importPkg(mod.main_pkg.table.get("std").?);
    }
    if (std.mem.eql(u8, import_string, "builtin")) {
        return mod.importPkg(mod.main_pkg.table.get("builtin").?);
    }
    if (std.mem.eql(u8, import_string, "root")) {
        return mod.importPkg(mod.root_pkg);
    }
    if (cur_file.pkg.table.get(import_string)) |pkg| {
        return mod.importPkg(pkg);
    }
    if (!mem.endsWith(u8, import_string, ".zig")) {
        return error.PackageNotFound;
    }
    const gpa = mod.gpa;

    // The resolved path is used as the key in the import table, to detect if
    // an import refers to the same as another, despite different relative paths
    // or differently mapped package names.
    const cur_pkg_dir_path = cur_file.pkg.root_src_directory.path orelse ".";
    const resolved_path = try std.fs.path.resolve(gpa, &[_][]const u8{
        cur_pkg_dir_path, cur_file.sub_file_path, "..", import_string,
    });
    var keep_resolved_path = false;
    defer if (!keep_resolved_path) gpa.free(resolved_path);

    const gop = try mod.import_table.getOrPut(gpa, resolved_path);
    errdefer _ = mod.import_table.pop();
    if (gop.found_existing) return ImportFileResult{
        .file = gop.value_ptr.*,
        .is_new = false,
        .is_pkg = false,
    };

    const new_file = try gpa.create(File);
    errdefer gpa.destroy(new_file);

    const resolved_root_path = try std.fs.path.resolve(gpa, &[_][]const u8{cur_pkg_dir_path});
    defer gpa.free(resolved_root_path);

    const sub_file_path = p: {
        if (mem.startsWith(u8, resolved_path, resolved_root_path)) {
            // +1 for the directory separator here.
            break :p try gpa.dupe(u8, resolved_path[resolved_root_path.len + 1 ..]);
        }
        if (mem.eql(u8, resolved_root_path, ".") and
            !isUpDir(resolved_path) and
            !std.fs.path.isAbsolute(resolved_path))
        {
            break :p try gpa.dupe(u8, resolved_path);
        }
        return error.ImportOutsidePkgPath;
    };
    errdefer gpa.free(sub_file_path);

    log.debug("new importFile. resolved_root_path={s}, resolved_path={s}, sub_file_path={s}, import_string={s}", .{
        resolved_root_path, resolved_path, sub_file_path, import_string,
    });

    keep_resolved_path = true; // It's now owned by import_table.
    gop.value_ptr.* = new_file;
    new_file.* = .{
        .sub_file_path = sub_file_path,
        .source = undefined,
        .source_loaded = false,
        .tree_loaded = false,
        .zir_loaded = false,
        .stat = undefined,
        .tree = undefined,
        .zir = undefined,
        .status = .never_loaded,
        .pkg = cur_file.pkg,
        .root_decl = .none,
    };
    return ImportFileResult{
        .file = new_file,
        .is_new = true,
        .is_pkg = false,
    };
}
```

I have debugged the compiler code and when it errors:
- `cur_pkg_dir_path` seems to be "." because `cur_file.pkg.root_src_directory.path` appears to be null.
- `resolved_path` seems to be fine, I mean it is an absolute path to the file to be imported.
- `resolved_root_path` seems to be wrong (or at least it is not resolved, since it's "." as well).

Then it gets to the `sub_file_path` block, none of the ifs are taken. The second if fails to be true due to the last condition (`resolved_path` is actually absolute).

I hope this helps core team developers or more avid contributors find a solution to the problem. I don't feel comfortable enough with this code because I don't know where the error is coming from. I would love to see this fixed soon since currently custom test runners are unusable (at least for freestanding) since you are not able to use imports in them.

**Comment by matu3ba** [comment]
Appendum to @davidgm94's post: "add an import inside a custom test runner file and it errors".

**Comment by dweiller** [comment]
I'm pretty sure there has actually been a change that has (unintentionally?) fixed this; the repro case in the OP has no issues. However, there is a bug/footgun which means that the test runner path has to be passed on the CLI as a path relative to the current working directory, which means that it does not work with `std.Build` as that is currently passing the test runner path as an absolute path.

**Comment by davidgm94** [comment]
I can confirm I was trying with `zig build`. Hopefully it is fixed soon, it must be a more or less easy change for people who know this part of the codebase.

**Comment by dweiller** [comment]
I think I probably have a fix (not that I'm familiar with the package loading code) -  just testing now.

**Comment by davidgm94** [comment]
Great! Thank you a lot

**Comment by dweiller** [comment]
I made a PR #14588 - also added the ability to import modules in a test runner.
