### ISSUE TITLE
Add Zig support to Godbolt compiler explorer

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1399]
https://github.com/mattgodbolt/compiler-explorer/issues/1060

**Comment by tiehuis** [comment]
https://github.com/mattgodbolt/compiler-explorer/pull/1069

**Comment by tiehuis** [comment]
As mentioned earlier, when merged we should add a test case ensuring we don't break compatibility for the used command-line arguments and the panic handler stub implementation unknowingly.

**Comment by andrewrk** [comment]
I added this file https://github.com/ziglang/zig/blob/master/test/cli.zig which is used to test `init-lib` and `init-exe`. This would be a good place to start for adding this test case for the interface that godbolt will be relying on.

**Comment by tiehuis** [comment]
This is now merged upstream. What remains for this issue is the above cli tests.

**Comment by andrewrk** [comment]
Exciting work, @tiehuis. Thanks for doing that!

Command line is `zig build-obj --cache-dir path --output path --emit asm -mllvm --x86-asm-syntax=intel`

Source should have this in it:

```zig
extern fn zig_panic() noreturn;
pub inline fn panic(msg: []const u8, error_return_trace: ?*@import("builtin").StackTrace) noreturn {
    zig_panic();
}
```

And then we should probably check that it creates the file and maybe that it contains some expected string.

I don't mind writing this test; I'll do it within the next couple days.
