### ISSUE TITLE
unoptimized .rodata

### ISSUE THREAD

**Issue by sergey6661313** [ziglang/zig#14003]
i open compiled elf binary file from zig-out (ver 0.10.0) with notepad and see this: many "integer overflow" strings....
it's const data - couldn't it have been declared only once?
![изображение](https://user-images.githubusercontent.com/16412693/208376023-b1d71023-9089-47e6-a177-c938d81eca49.png)
I am not a native speaker. Sorry if text is disrespectful. I don't know how to write it correctly.

**Comment by r00ster91** [comment]
See also: https://github.com/ziglang/zig/issues/13111

**Comment by Vexu** [comment]
That particular issue was solved by #13636
