### ISSUE TITLE
Incorrect dependency loop from struct default value

### ISSUE THREAD

**Issue by Vexu** [ziglang/zig#14005]
Found in bun:
```zig
const S = struct {
    s: *S = &S.instance,
    var instance: S = undefined;
};
comptime {
    _ = S.instance;
}
```

**Comment by ianprime0509** [comment]
It looks like this should have been closed with #17692, since it was added as a behavior test in that PR: https://github.com/ziglang/zig/pull/17692/files#diff-e88bfbf758018704fbee1f67030cab3ba987e51e7c1516fe2cbf5bccf0dbfbf5R1809-R1824
