### ISSUE TITLE
Path does not resolve correctly

### ISSUE THREAD

**Issue by zxubian** [ziglang/zig#14010]
### Zig Version

0.11.0-dev.892+3db8cffa3 (windows)

### Steps to Reproduce and Observed Behavior

```zig
// repro.zig
const std = @import("std");

test "Path resolution" {
    const input_path = "./input/net.cap";
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    const allocator = gpa.allocator();
    defer {
        const leaked = gpa.deinit();
        if (leaked) {
            std.log.err("Leaking memory!", .{});
        }
    }
    const input_path_resolved = std.fs.path.resolve(allocator, &.{input_path}) catch |e| {
        std.log.err("Could not resolve input path = {s}\n{}", .{ input_path, e });
        return;
    };
    defer allocator.free(input_path_resolved);
    std.testing.expect(std.mem.eql(
        u8,
        input_path_resolved[0..1],
        "C:",
    )) catch {
        std.log.err("{s} -> {s}", .{ input_path, input_path_resolved });
    };
}
```

directory structure:
```
C:/
Project/
├─ input/
│  ├─ net.cap
├─ repro.zig
├─ zig.exe
├─ lib/
│  ├─ ...
```

run with 
`./zig test ./repro.zig --zig-lib-dir ./lib`

### Actual Behaviour
Test fails, `./input/net.cap` gets resolved to  `input\net.cap`

### Expected Behavior

Expected behaviour:
- path `./input/net.cap` should be resolved to `C:\Project\input\net.cap` and therefore test should pass

**Comment by Prince213** [comment]
https://github.com/ziglang/zig/blob/d24aaf8847336e12b6571e13d57f6d112452d97d/lib/std/fs/path.zig#L751-L752

**Comment by zxubian** [comment]
@Prince213 
Sorry, I'm afraid I don't quite get your point. Do you meant to say that the behaviour is expected because the input path is relative?

The resolve function states it resolves `.` and `..`, and my input path contains `.`, so I would expect that to be resolved to the current working directory. Is my understanding wrong somehow?
Thanks.

https://github.com/ziglang/zig/blob/d24aaf8847336e12b6571e13d57f6d112452d97d/lib/std/fs/path.zig#L641

**Comment by Prince213** [comment]
> Do you meant to say that the behaviour is expected because the input path is relative?

@zxubian Yes, if I understand the thing correctly. As mentioned in the commit message of https://github.com/ziglang/zig/commit/d24aaf8847336e12b6571e13d57f6d112452d97d, std.fs.path.resolve doesn't make system calls, thus the function is agnostic to the actual file system.

**Comment by zxubian** [comment]
@Prince213 
Thanks for the explanation! I was not aware of this breaking change...
I managed to get my code working by using `std.fs.realpath` instead of `std.fs.path.resolve`.
I think the naming is confusing, but I'm not sure what the usecase for `resolve` is so I'm not sure how to improve it.
I'll close the issue now, because it's not a bug.

**Comment by nektro** [comment]
resolve afaik is for turning paths like `/home/me/path/to/.../other` into `/home/me/path/other`

**Comment by Prince213** [comment]
To me it's more like "resolve . and ..", not sure tho
