### ISSUE TITLE
`undefined` is a valid target for comparisons

### ISSUE THREAD

**Issue by zxubian** [ziglang/zig#14019]
### Zig Version

0.11.0-dev.892+3db8cffa3

### Steps to Reproduce and Observed Behavior

```zig
test "undefined should not be used in comparisons" {
    var a: u8 = undefined;
    while (a == undefined) {}
    @panic("unreachable");
}
```

### Actual Behaviour
test compiles and when run reaches the `panic`.

### Expected Behavior

According to the [language reference](https://ziglang.org/documentation/master/#undefined),

> `undefined `means the value could be anything, even something that is nonsense according to the type. Translated into English, `undefined `means "Not a meaningful value. Using this value would be a bug. The value will be unused, or overwritten before being used." 

Thus, the expected behaviour for the above test is to return a compile message along the lines of:
```
Cannot use `undefined` in a comparison. Consider using an optional type instead.
```

**Comment by squeek502** [comment]
Possible duplicate of https://github.com/ziglang/zig/issues/597

**Comment by zxubian** [comment]
Thanks @squeek502 !
After digging a bit more, I think this is a duplicate of 
https://github.com/ziglang/zig/issues/63, and will be considered in https://github.com/ziglang/zig/issues/1947 also.

I'll close this issue now.
