### ISSUE TITLE
Footgun: @hasDecl returns false for non-visible declarations

### ISSUE THREAD

**Issue by mlugg** [ziglang/zig#14026]
### Zig Version

0.11.0-dev.922+471f3c470

### Steps to Reproduce and Observed Behavior

`main.zig`:
```
comptime {
    const foo = @import("foo.zig");
    @compileLog(@hasDecl(foo, "priv"));
}
```
`foo.zig`:
```
const priv = 42;
```
Output:
```
Compile Log Output:
@as(bool, false)
```

### Expected Behavior

`@hasDecl` should return `true`. The current behaviour is intended, but is a footgun in almost any practical case.

Let's look at `std` for examples. Most uses of `@hasDecl` in `std` can be split into two categories:
- checking we have various required decls on a container, and providing nice errors if not; e.g. `std.hash_map.verifyContext`
- overriding default behaviour from `root` or similar; e.g. `builtin.zig`, `start.zig`, `log.zig`

The second use case here is *much* more common when the first, and this is where the footgun presents itself. As an example, writing `const log_level = ...` in your root file is incorrect, but currently the code will compile without issue. In many cases, the issue may not become obvious for a while - in this instance, you'll only notice a problem when compiling in a release mode. If `@hasDecl` instead returned `true`, you would instead get a helpful error when `log.zig` tried to access the decl that it was not `pub`.

The first use case is much rarer, but this change doesn't really regress it much. In the example of `std.hash_map.verifyContext`, all it means is you'll get a slightly less readable error. If we want, we could even modify that function to use `@typeInfo` (or a new helper in `std.meta`) to check the decl is `pub` and provide a *more* helpful error if not.

Information about private decls on containers is already accessible (regardless of whether visible to the current file) through `@typeInfo` reflection, so it makes sense for `@hasDecl` to reflect the needs of the most common use case - if the alternative is needed, that can just be added as a `std.meta.hasPubDecl` or similar. As detailed above, it makes sense for the vast majority of use cases for `@hasDecl` to ignore access control.

**Comment by nektro** [comment]
> Information about private decls on containers is already accessible (regardless of whether visible to the current file) through `@typeInfo` reflection

this is an open issue

**Comment by andrewrk** [comment]
This is working as designed, and I think you have it precisely backwards. The footgun would be exposing private declarations.

**Comment by mlugg** [comment]
Intuitively I agree with you, but when writing this issue I couldn't think of any case where exposing the existence (not values!) of private decls causes an issue in *practice*. Do you have an example?

**Comment by swarnimarun** [comment]
> Intuitively I agree with you, but when writing this issue I couldn't think of any case where exposing the existence (not values!) of private decls causes an issue in _practice_. Do you have an example?

Trying to use what you find with `hasDecl` seems like an obvious issue to me. Perhaps I am understanding your intent here incorrectly.

**Comment by mlugg** [comment]
The fact that trying to use what you find would be a compile error is the *point*! Currently, if you have a decl that tries to override some behaviour, but which you forgot to mark `pub`, it silently fails. That can be hard to notice in some cases - e.g. overriding `logFn`. If instead `@hasDecl` succeeded, but attempting to access the decl raised a compilation error, you would immediately see something trying to access a non-`pub` decl and know what you did wrong.

**Comment by swarnimarun** [comment]
@mlugg why not use [`@typeInfo`](https://ziglang.org/documentation/master/#typeInfo) in those cases?

**Comment by mlugg** [comment]
1: The fact that `@typeInfo` exposes non-`pub` decls is potentially considered a bug, and may get changed.
2: You shouldn't have to do complex reflection to get the best behavior for `@hasDecl`'s most common use case. As mentioned in the original issue, the majority of use cases of `@hasDecl` are for overriding behavior, which is where the footgun manifests itself. Expecting people to use `@typeInfo` in the *common* case seems counterproductive (and just a footgun in and of itself, because people won't realise that they should do that).

**Comment by andrewrk** [comment]
Type info is not supposed to return private decls
