### ISSUE TITLE
`@min` and `@max` should allow any number of arguments and notice integer bounds

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#14039]
```zig
const std = @import("std");

test "three arguments to @min" {
    var runtime1: usize = 1 << 17;
    const max_ciphertext_len = (1 << 14) + 256;
    var runtime2: u64 = 1 << 33;
    const ciphertext_len: u16 = @min(runtime1, max_ciphertext_len, runtime2);
    try std.testing.expect(ciphertext_len == max_ciphertext_len);
}
```

This test is expected to pass. Note that there should be no compile error due to coercion to `u16` despite the use of runtime-known `u64` and `usize`, because one of the arguments to `@min` is compile-time known to be within range of `u16`.

**Comment by Jarred-Sumner** [comment]
will there be other variadic functions or a way to define variadic functions (of comptime-known length, unlike in C)?

**Comment by andrewrk** [comment]
No. Language builtins are special.

**Comment by Snektron** [comment]
There are archs with instructions for 3-way min, so this is a good call 👍

> No. Language builtins are special.

I guess there could be other builtins, but i can think of none where this applies

**Comment by andrewrk** [comment]
`@TypeOf` accepts any number of arguments
