### ISSUE TITLE
Symbol collision with comptime type segfaults compiler

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#14042]
### Zig Version

0.11.0-dev.926+266e2e9a3

### Steps to Reproduce and Observed Behavior

1. Paste `file.zig`:
```zig
const std = @import("std");

test "segfaulty" {
    const Foo = struct {
        pub fn sliceAsBytesWithType(comptime Slice: type, slice: Slice) SliceAsBytesReturnType(@TypeOf(slice)) {
            const Slice = @TypeOf(slice);
            std.mem.doNotOptimizeAway(Slice);
        }
    };

    Foo.sliceAsBytesWithType([*]u8, "hello");
}
```

2. zig test file.zig

### Expected Behavior

no segfault, symbol collision error instead

**Comment by Vexu** [comment]
Cannot reproduce, I get an error about undeclared identifier `SliceAsBytesReturnType` and if I prefix that with `std.mem.` then I get an error about local shadowing a parameter.

**Comment by Vexu** [comment]
Not reproducible.
