### ISSUE TITLE
Observable address of objects is different in runtime and comptime

### ISSUE THREAD

**Issue by drYEETs** [ziglang/zig#14048]
### Zig Version

0.11.0-dev.931+f211c1559

### Steps to Reproduce and Observed Behavior

If you do runtime reflection stuff, you often find yourself wanting to get a unique ID for a unique type, and the commonly advised way to do that is by writing a comptime function with a local struct decl which contains a var decl of a small object. That object's address becomes the typeId.

This works if you only call the typeId function at runtime, however if you start doing stuff such as making some const declarations of some extended runtime type info and store the typdId in those objects, then you'll get different results for your typeId. 

```zig
const std = @import("std");

const TypeId = *const TypeHandle;
const TypeHandle = opaque {
    pub inline fn idOf(comptime T: type) *const TypeHandle {
        _ = T;
        const static = struct {
            //const id: u1 = undefined; // if you declare this const instead of var, it all collapses to one object/one address, so it's not workable for a typeid mechanism
            var id: u1 = undefined;
        };
        comptime return @ptrCast(TypeId, &static.id);
    }
};

const TypeData = struct {
    tid: TypeId,
};

pub inline fn getTypeData(comptime T: type) *const TypeData {
    const Static = struct {
        const type_data = TypeData {
            .tid = TypeHandle.idOf(T),
        };
    };
    comptime return &Static.type_data;
}

const SomeType = struct {};

const SomeOtherType = enum(i32){_};

pub fn main() void {
    const tid = TypeHandle.idOf(SomeType);
    const type_data = getTypeData(SomeType);
    std.debug.print("          tid: {}\ntype_data.tid: {}\n\n", .{tid, type_data.tid});


    const tid2 = TypeHandle.idOf(SomeOtherType);
    const type_data2 = getTypeData(SomeOtherType);
    std.debug.print("          tid: {}\ntype_data.tid: {}\n\n", .{tid2, type_data2.tid});
}
```

This prints out:

```
          tid: main.TypeHandle@7ff633d39100
type_data.tid: main.TypeHandle@7ff633d39118

          tid: main.TypeHandle@7ff633d39101
type_data.tid: main.TypeHandle@7ff633d39128
```

Also repros in 0.10.0 and older 0.10.0 dev releases using stage1.

### Expected Behavior

Expected the address of TypeHandle.idOf/Static.id to be the same regardless of whether accessed at runtime or stored in a const object at comptime.

Or, alternatively, there could just be a `@typeId(comptime T: type)` builtin. This is what I'm really aiming for, but was encouraged to report the inconsistency in addresses at the behest of @InKryption

Ink also pointed out a case where this works as we'd expect (although does not go indirect through a type function) is using the address of a decl as a sentinel value:

```zig
const std = @import("std");

var val: u8 = 0;

pub fn main() void {
    const ValTermPtr = [*:&val]?*u8;
    var val_term = [_:&val]?*u8{ null, null };
    const vtp: ValTermPtr = &val_term;

    var it = vtp;
    while (it[0] != &val) : (it += 1) {
        //
    }
}
```

**Comment by Vexu** [comment]
I get a different address for both var and const.
```sh-session
$ zig run a.zig #var
          tid: a.TypeHandle@257100
type_data.tid: a.TypeHandle@257140

          tid: a.TypeHandle@257101
type_data.tid: a.TypeHandle@257148

$ zig run a.zig #const
          tid: a.TypeHandle@20188a
type_data.tid: a.TypeHandle@202ca0

          tid: a.TypeHandle@201898
type_data.tid: a.TypeHandle@202ca1

```

**Comment by drYEETs** [comment]
Oh interesting, yeah just fetched latest master and got similar result.

On the 0.10.0 release the addresses are identical:

https://godbolt.org/z/3jo84PrGz

The latest behavior seems more consistent, as I'd expect them to be separate types coming from different instantiations of a type function. Changing addresses between comptime and runtime is still an issue though. :(

**Comment by Vexu** [comment]
> Changing addresses between comptime and runtime is still an issue though. :(

Can you give an example of that?

**Comment by drYEETs** [comment]
Well there's the initial example I posted, in which you aren't able to use address-of a var declaration as a type ID if you are generating some type metadata declarations during comptime that you want to make available at runtime and want to use this type ID as a lookup key at runtime.

Using address-of-a-decl for a type ID is kinda weird, but that is the most commonly recommended approach. Others have suggested using address of the @typeInfo which appears to always be consistent between comptime and runtime, but std.builtin.Type objects can be shared between distinct type declarations.

There's also the example provided by @InKryption unrelated to type IDs that uses a pointer as an array sentinel under the "Expected Behavior" section, code reproduced again below:

```zig
const std = @import("std");

var val: u8 = 0;

pub fn main() void {
    const ValTermPtr = [*:&val]?*u8;
    var val_term = [_:&val]?*u8{ null, null };
    const vtp: ValTermPtr = &val_term;

    var it = vtp;
    while (it[0] != &val) : (it += 1) {
        //
    }
}
```

The above compiles and runs as you'd expect, but the following does not:

```zig
const std = @import("std");

fn TerminatorForType(comptime T: type) *u8 {
    _ = T;
    const Static = struct {
        var val: u8 = 0;
    };
    return &Static.val;
}

const SomeDistinctType = opaque{};

pub fn main() void {
    const ValTermPtr = [*:TerminatorForType(SomeDistinctType)]?*u8;
    var val_term = [_:&TerminatorForType(SomeDistinctType)]?*u8{ null, null };
    const vtp: ValTermPtr = &val_term;

    var it = vtp;
    while (it[0] != &TerminatorForType(SomeDistinctType)) : (it += 1) {
        //
    }
}
```

https://godbolt.org/z/jcvYEYGK4

The pragmatic use case here is less obvious, maybe someone would want to use this in some kind of declarative lib or in some embedded programming where particular addresses have special meaning such that it makes sense to use them as terminators, but those addresses are determined by comptime functions.

But this feels like an inconsistency that should be shored up--either make pointers to decls have a consistent address in the final executable or explicitly bar addresses from traveling across the comptime->runtime boundary in this fashion. But in that case I think a `@typeId` builtin would be needed to satisfy many common use cases (e.g. already mentioned RTTI, but also type-segregated storage where a typeID is the key (e.g. `AutoHashMap(TypeId, Allocator`). Some of these cases may incidentally work, but it seems like it's easy to unintentionally cut the cord if you put these typeIds behind a comptime function.

**Comment by Vexu** [comment]
In the initial example the different addresses are caused by the function being inlined and the second example gives a correct error: `expected type '?*u8', found '*const *u8'`.

**Comment by drYEETs** [comment]
Why does inlining cause the address to change in comptime vs runtime?

From the perspective of an end-user, I'd expect the result of a comptime function like `TypeHandle.idOf` to be cached at comptime and local environments of comptime functions to be frozen & stripped--any decls existing in there and stored as constants to be accessible to runtime would be tracked with address values fixed up in the final executable/lib. Otherwise how do all the various comptime solutions for generating vtables or comptime-computed caches work if object addresses aren't guaranteed to be consistent?

**Comment by Vexu** [comment]
Inlining works by copying the body of the function to the body of the caller, the result cannot be memoized and everything is analyzed twice.

**Comment by drYEETs** [comment]
Okay, that make sense. So why would it inline this? I'd have thought because the semantics of comptime functions from the end-user's perspective is that they get memoized, that comptime functions would be excluded from inlining. Otherwise, how can folks rely on current metaprogramming idioms?

**Comment by Vexu** [comment]
> So why would it inline this?

Because you used the `inline` keyword.

**Comment by drYEETs** [comment]
Ah that's my bad leaving the `inline` in, was playing around with the declarations to see if the behavior changed.

The addresses are different regardless of whether or not the functions are declared inline, here's a trunk godbolt repro: https://godbolt.org/z/n5319Gef6

**Comment by Vexu** [comment]
Now the results are not being memoized since the calls inside main are not happening at comptime. I'm unsure what the expected behavior here is but prefixing the calls in main with `comptime` results in the same address.

**Comment by drYEETs** [comment]
That makes sense since it's evaluating those in a comptime context. The behavior I expected was that the address values computed in both the runtime and comptime contexts would be the same when printing them at runtime.

**Comment by Vexu** [comment]
The addresses for the runtime and comptime calls are different since they are pointing to different decls. You likely want #1719
