### ISSUE TITLE
Expected error union type, found '...' points to wrong source location

### ISSUE THREAD

**Issue by pfgithub** [ziglang/zig#14053]
### Zig Version

0.11.0-dev.931+f211c1559

### Steps to Reproduce and Observed Output

```zig
pub fn main() u8 {
    var a: u8 = 5;
    errdefer a += 1;
    return a;
}
```

```zig
a.zig:4:5: error: expected error union type, found 'u8'
    return a;
    ^~~~~~~~
```

### Expected Output

```zig
a.zig:3:5: error: expected error union type, found 'u8'
    errdefer a += 1;
    ^~~~~~~~
```

**Comment by Vexu** [comment]
This shouldn't be an error at all.

**Comment by Vexu** [comment]
Oh, and it's my fault: 58caed1c71179f48c4e7bffadef0392fa8381e72. I checked that `is_non_null` is not used for anything but not `is_non_err`.
