### ISSUE TITLE
Compiler segfault when taking address of `HashMap.Iterator.next`

### ISSUE THREAD

**Issue by erikarvstedt** [ziglang/zig#14063]
### Zig Version

0.11.0-dev.5675+5bde627f9

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() !void {
    std.mem.doNotOptimizeAway(@ptrToInt(&std.AutoHashMap(u32, u32).Iterator.next));
}
```
Running the above results in:
`Segmentation fault (core dumped)`

## Details
`HashMap.init` works as expected:
```zig
std.mem.doNotOptimizeAway(@ptrToInt(&std.AutoHashMap(u32, u32).init));
```

**Comment by erikarvstedt** [comment]
This issue still persists.

- `0.11.0-dev.5683+cf822c6dd`
- Platform: `aarch64-linux`, LLVM `target-cpu`: `znver2`
- Built with:
   ```bash
   cmake $src -DCMAKE_BUILD_TYPE=Release
   make VERBOSE=1 -j 4 install
   ```

**Comment by jacobly0** [comment]
- [X] param of optional struct with one reference
- [ ] param of pointer to packed struct with one reference
