### ISSUE TITLE
`enum tag value already taken` when overriding some values.

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#14074]
### Zig Version

0.11.0-dev.931+f211c1559

### Steps to Reproduce and Observed Behavior

```zig
pub fn main() !void {
	_ = enum(u5) {
		a = 1,
		b = 0,
		c,
	};
}
```
When running this I get a compiler error:
```
$ zig run test.zig
test.zig:7:3: error: enum tag value 1 already taken
  c,
  ^
test.zig:5:3: note: other occurrence here
  a = 1,
  ^~~~~
```

It seems that zig, after encountering overriden values, just counts up from the last seen value.

### Expected Behavior

It should run without a problem.
For me it would make the most sense if the int value of `c` would be `2`, the next highest number that was not used yet.

**Comment by InKryption** [comment]
I think this is fine as is. The proposed behavior would be fine at a small scale, but given a much larger enum with non-consecutive values, it would become a lot less clear the implicit value. The rule "the subsequent value is implicitly the previous value plus one" is much simpler. I don't have to read every other enum value to figure out what the next value will be, only the one immediately before. Thus, I think that the obligation to write `c = 2` here makes sense.

**Comment by IntegratedQuantum** [comment]
Makes sense.

I think it should be mentioned clearly in the documentation then.
It only mentions counting up from zero, but it doesn't mention what happens when overriding a subset of the enum.
