### ISSUE TITLE
OffsetOf incorrect for fields in a packed struct that come after custom sized ints

### ISSUE THREAD

**Issue by raulgrell** [ziglang/zig#1408]
```
const std = @import("std");

const P = packed struct {
    a: u8,
    b: u32,
    c: u8,
    d: u3,
    e: u8,
    f: u16,
    g: u16,
};

test "byteOffsetOf" {
    const p: P = undefined;
    std.debug.warn("\n");
    std.debug.warn("a: {}\n", (usize)(@offsetOf(P, "a")));
    std.debug.warn("b: {}\n", (usize)(@offsetOf(P, "b")));
    std.debug.warn("c: {}\n", (usize)(@offsetOf(P, "c")));
    std.debug.warn("d: {}\n", (usize)(@offsetOf(P, "d")));
    std.debug.warn("e: {}\n", (usize)(@offsetOf(P, "e")));
    std.debug.warn("f: {}\n", (usize)(@offsetOf(P, "f")));
    std.debug.warn("g: {}\n", (usize)(@offsetOf(P, "g")));
}
```

I was looking at #633 and happened across this bug. d, e, f and g all return 6.

**Comment by andrewrk** [comment]
This might be working as designed - let's discuss.

How it works for packed fields is:
 * The first field that is not byte-aligned is an integer that *is* byte-aligned, and holds all the fields following until the struct becomes byte-aligned again.
 * `@offsetOf` and pointers must be byte-aligned, so they point to this byte-aligned integer. Pointers have extra metadata to specify the bit offset. `@offsetOf` does not currently have a way to represent this information.

**Comment by raulgrell** [comment]
Makes perfect sense. I just changed e to u5, to align everything again and it behaved as expected. Thanks for the feedback
