### ISSUE TITLE
Zig compiler not working as expected on 601ab9a

### ISSUE THREAD

**Issue by lamersc** [ziglang/zig#14093]
### Zig Version

0.11.0-dev.980+601ab9a25

### Steps to Reproduce and Observed Behavior

System: Apple M1 Pro

Installation:
> brew install zig --HEAD
<br>

Commands & output:
> zig env
```
error: Zig was built/linked incorrectly: LLVM and Clang have separate copies of libc++
       If you are dynamically linking LLVM, make sure you dynamically link libc++ too
```
> zig libc
```
thread 85241 panic: Darwin is handled separately via std.zig.system.darwin module
Unable to dump stack trace: debug info stripped
zsh: abort      zig libc
```

### Expected Behavior

*Based on output of 0.10.0*.
*Earlier commit from yesterday was working well, I believe 81443fcde*.
> zig env
```json
{
 "zig_exe": "/opt/homebrew/Cellar/zig/0.10.0/bin/zig",
 "lib_dir": "/opt/homebrew/Cellar/zig/0.10.0/lib/zig",
 "std_dir": "/opt/homebrew/Cellar/zig/0.10.0/lib/zig/std",
 "global_cache_dir": "/Users/lamersc/.cache/zig",
 "version": "0.11.0",
 "target": "aarch64-macos.13.1...13.1-none"
}

```

**Comment by andrewrk** [comment]
> error: Zig was built/linked incorrectly: LLVM and Clang have separate copies of libc++
       If you are dynamically linking LLVM, make sure you dynamically link libc++ too

This indicates a problem with the way homebrew has packaged Zig, specifically with regards to the LLVM/Clang dependencies and/or the configuration flags provided to Zig.

Please file an issue on the homebrew issue tracker.

**Comment by andrewrk** [comment]
After I wrote the above message I remembered 55c3efcb58cc153fc3109a61c6949e470b57b81e which landed in master branch recently. Can you check if reverting this commit solves the problem?

**Comment by lamersc** [comment]
Will check once home 👍

**Comment by lamersc** [comment]
> Can you check if reverting this commit solves the problem?

Decided to test building without Homebrew. Building off 601ab9a gave same issues, but reverting 55c3efc seemed to fix `./zig env`.
```
{
 "zig_exe": "/Users/lamersc/Documents/zig/stage3/bin/zig",
 "lib_dir": "/Users/lamersc/Documents/zig/stage3/lib/zig",
 "std_dir": "/Users/lamersc/Documents/zig/stage3/lib/zig/std",
 "global_cache_dir": "/Users/lamersc/.cache/zig",
 "version": "0.11.0-dev.981+5da0d30da",
 "target": "aarch64-macos.13.1...13.1-none"
}

```
Running `./zig libc` meanwhile returned:
```
thread 38731 panic: Darwin is handled separately via std.zig.system.darwin module
/Users/lamersc/Documents/zig/src/libc_installation.zig:185:13: 0x10446a31f in findNative (zig)
            @panic("Darwin is handled separately via std.zig.system.darwin module");
            ^
/Users/lamersc/Documents/zig/src/main.zig:3698:47: 0x104412057 in cmdLibC (zig)
        var libc = LibCInstallation.findNative(.{
                                              ^
/Users/lamersc/Documents/zig/src/main.zig:294:23: 0x1043dfaab in mainArgs (zig)
        return cmdLibC(gpa, cmd_args);
                      ^
/Users/lamersc/Documents/zig/src/main.zig:201:20: 0x1043de45f in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/Users/lamersc/Documents/zig/lib/std/start.zig:614:37: 0x1043e08b3 in main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x19437be4f in ??? (???)
???:?:?: 0x645a7fffffffffff in ??? (???)
zsh: abort      ./zig libc
```

**Comment by andrewrk** [comment]
Thank you for checking. Reverted in b1207b3293968da4da12c26c85384f10ff4d1c06.
