### ISSUE TITLE
warning(compilation): failed to write cache manifest when compiling 'FILE.c': LockViolation

### ISSUE THREAD

**Issue by rockcavera** [ziglang/zig#14110]
### Zig Version

0.10.0 and 0.11.0-dev.987+a1d82352d

### Steps to Reproduce and Observed Behavior

I decided to test Zig as a C compiler for Nim. First I compiled a simple "Hello World!" in Nim and that's fine.

In this, I decided to compile the Nim compiler with Zig. The first build went well (at least so I believe). [Log here](https://gist.github.com/rockcavera/926b7705c8f0e0416b0a0e7b2c96b4ed#file-firstbuild-log)

I did a second build because I needed to update the Nim compiler devel and I started getting some "warning(compilation): failed to write cache manifest when compiling 'FILE.c': LockViolation" warnings. [Log here](https://gist.github.com/rockcavera/926b7705c8f0e0416b0a0e7b2c96b4ed#file-secondbuild-log)

The third time I needed to compile the Nim compiler the Zig compiler cache apparently got corrupted and I can no longer compile the Nim compiler until I delete the Zig cache. [Log here](https://gist.github.com/rockcavera/926b7705c8f0e0416b0a0e7b2c96b4ed#file-thirdbuild-log)

Comments:
1) Before every compilation or recompilation of the Nim compiler I deleted the nimcache (Nim cache). The same problem occurs if you pass -f (force rebuild) to the Nim compiler;

2) The problem always happens on the third recompilation. I managed to reproduce with Zig devel 0.11.0-dev.987+a1d82352d; [Log here](https://gist.github.com/rockcavera/926b7705c8f0e0416b0a0e7b2c96b4ed#file-parallelbuild1_zig-0-11-0-dev-987-a1d82352d-log)

3) With a simple `echo "Hello World!"` in Nim, I cannot corrupt the Zig cache, but I get "warning(compilation): failed to write cache manifest when compiling 'FILE.c': LockViolation" after new compilations with -f or deleting nimcache;

4) I found similar problems where I was informed that possible simultaneous zig calls could cause "warning(compilation): failed to write cache manifest when compiling 'FILE.c': LockViolation". Then I had the Nim compiler call "zig cc" one at a time with "--parallelBuild:1". I still get "warning(compilation): failed to write cache manifest when compiling 'FILE.c': LockViolation" and on the third compiler build the cache seems to corrupt; [Log here](https://gist.github.com/rockcavera/926b7705c8f0e0416b0a0e7b2c96b4ed#file-parallelbuild1_zig-0-10-0-log)

5) I set "ZIG_GLOBAL_CACHE_DIR" to "E:\compilers\zig\cache";

6) Operating system Windows 10 Pro 64-bit 21H2 19044.2364.

Sorry for the amount of log files.

Finally, congratulations on working with Zig.

### Expected Behavior

Compiles without problems.

**Comment by schmee** [comment]
Possibly related: https://github.com/ziglang/zig/issues/12718, https://github.com/ziglang/zig/pull/13591

**Comment by rockcavera** [comment]
I tested it now with zig 10.0.1 and the error did not happen.
