### ISSUE TITLE
Debug info for tagged unions is broken in stage2

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#14124]
### Zig Version

0.11.0-dev.971+19056cb68

### Steps to Reproduce and Observed Behavior

<img width="584" alt="image" src="https://user-images.githubusercontent.com/709451/210056161-aa25464b-ca49-417e-949c-80758697b2c2.png">

![image](https://user-images.githubusercontent.com/709451/210056142-18bafce7-5e35-46f7-81e6-9e28ac7b908f.png)

Code:
```zig
const std = @import("std");

const Union = union(Tag) {
    foo: u1,
    bar: u1,

    pub const Tag = enum { foo, bar };
};

pub fn main() anyerror!void {
    var hey = Union{ .foo = 1 };
    @breakpoint();
    std.debug.print("{any}", .{hey});
}
```

Build:
```bash
zig build-exe repro.zig
```

### Expected Behavior

1) It should show the selected tag name
2) It should show the value in payload.

Note that sometimes it does show a value depending on the value's type, but it never shows the tag. 

It is also missing labels for fields in certain cases - note the `:` with no letters before it:
<img width="212" alt="image" src="https://user-images.githubusercontent.com/709451/210056378-fe53f557-ce66-4d9f-a238-563df36c89c7.png">

This mostly worked fine in stage1.

**Comment by Vexu** [comment]
Works in gdb:
```
Program received signal SIGTRAP, Trace/breakpoint trap.
a.main () at a.zig:13
13          std.debug.print("{any}", .{hey});
(gdb) p hey
$1 = {tag = foo, payload = {foo = 0, bar = 0}}
```

**Comment by Jarred-Sumner** [comment]
Does not work in `lldb`:

```zig

❯ lldb repro
(lldb) target create "repro"
Current executable set to '/Users/jarred/Desktop/repro' (arm64).
(lldb) run
Process 34205 launched: '/Users/jarred/Desktop/repro' (arm64)
Process 34205 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=1, subcode=0x100000b64)
    frame #0: 0x0000000100000b68 repro`repro.main at repro.zig:13:20
   10   pub fn main() anyerror!void {
   11       var hey = Union{ .foo = 1 };
   12       @breakpoint();
-> 13       std.debug.print("{any}", .{hey});
   14   }
(lldb) p hey
(repro.Union) $0 = {
  payload = {}
}
```

**Comment by Vexu** [comment]
Same cause as #14124

**Comment by daurnimator** [comment]
> Same cause as #14124

huh? that *is* this issue.

**Comment by Vexu** [comment]
Meant #14122
