### ISSUE TITLE
std.fmt fails with enum values

### ISSUE THREAD

**Issue by cgag** [ziglang/zig#1412]
Sample code and output: https://gist.github.com/cgag/8e1d2289cfbb3c842d61ebdddf0316f7

Worked around it with @tagName(MyEnum.Value).

**Comment by tgschultz** [comment]
I've made a PR (#1413) to fix this specific issue. The current struct printing behavior is very simple, I'd expect it to do undesirable things in many cases currently.

**Comment by andrewrk** [comment]
Fixed by @tgschultz in 61c0c6d502b19a6aa232d91a201eba9d67aced5a
