### ISSUE TITLE
[wiki] update CI script link for Windows Dev Kit

### ISSUE THREAD

**Issue by hdorio** [ziglang/zig#14150]
A broken wiki link should be fixed as follows:

    diff --git a/Building-Zig-on-Windows.md b/Building-Zig-on-Windows.md
    index 047954d..b42ef0c 100644
    --- a/Building-Zig-on-Windows.md
    +++ b/Building-Zig-on-Windows.md
    @@ -6,7 +6,7 @@
     
     This one has the benefit that LLVM, LLD, and Clang are built in Release mode, while your Zig build has the option to be a Debug build. It also works completely independently from MSVC so you don't need it to be installed.
     
    -Determine the URL by [looking at the CI script](https://github.com/ziglang/zig/blob/master/ci/azure/pipelines.yml#L17-L20). It will look something like this (replace `$VERSION` with the one you see by following the above link):
    +Determine the URL by [looking at the CI script](https://github.com/ziglang/zig/blob/master/ci/x86_64-windows.ps1#L1-L4). It will look something like this (replace `$VERSION` with the one you see by following the above link):
     
     ```
     https://ziglang.org/deps/zig+llvm+lld+clang-x86_64-windows-gnu-$VERSION.zip


It seems I don't have permission to edit the wiki
going to https://github.com/ziglang/zig/wiki/Building-Zig-on-Windows/_edit gives
> You do not have permission to update this wiki.

**Comment by Luukdegram** [comment]
Thanks! I've updated the Wiki with the correct link.
