### ISSUE TITLE
make std.url / std.uri more complete and RFC-compliant

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#14176]
https://github.com/ziglang/zig/blob/c9ef277fa7e43f119a7f2896635b4fdf9c97edbe/lib/std/Url.zig#L6-L8

upstreaming @MasterQ32's [zig-uri](https://github.com/MasterQ32/zig-uri/) has been suggested

**Comment by MasterQ32** [comment]
> upstreaming @MasterQ32's [zig-uri](https://github.com/MasterQ32/zig-uri/) has been suggested

I obviously agree on that. `zig-uri` is well tested in several projects and has quite some unit tests as well. It should be fully spec compliant, as i've built it step-by-step from RFC3986.

**Comment by andrewrk** [comment]
Alright, good sir, I have cleared the runway for you to upstream the project by merging some of your PRs that have been patiently waiting to be merged for a long time.

**Comment by MasterQ32** [comment]
I guess this can be closed.

**Comment by andrewrk** [comment]
Landed in 87b223428a8953b6af9bea61ff4cc905821c0557
