### ISSUE TITLE
`fts.h` missing from macos headers

### ISSUE THREAD

**Issue by jvolkman** [ziglang/zig#14184]
### Zig Version

0.11.0-dev.1079+c1f404ad5

### Steps to Reproduce and Observed Behavior

Found when attempting to build cctools-port targeting macos. [This line](https://github.com/tpoechtrager/cctools-port/blob/master/cctools/libstuff/dylib_roots.c#L33) attempts to include `fts.h` which is missing from Zig's macos libc headers.

```
git clone https://github.com/tpoechtrager/cctools-port
cd cctools-port/cctools
CC='zig cc -target aarch64-macos' CXX='zig c++ -target aarch64-macos' ./configure --host=aarch64-darwin
cd libstuff
make
```

```
dylib_roots.c:33:10: fatal error: 'fts.h' file not found
#include <fts.h>
```

### Expected Behavior

Zig bundles `fts.h` for [glibc](https://github.com/ziglang/zig/blob/master/lib/libc/include/generic-glibc/fts.h). And it's [available](https://opensource.apple.com/source/Libc/Libc-1439.141.1/include/fts.h) from Apple. It seems simple enough to include. Simply dropping that linked file into `any-macos-any` on my local zig install resolved the problem for me.

**Comment by kubkon** [comment]
Fixed in https://github.com/ziglang/zig/commit/1b97881e38e56ae3bdfc4009265840b77fa9e325
