### ISSUE TITLE
A packed struct member of a struct isn't equal to itself.

### ISSUE THREAD

**Issue by DiskPoppy** [ziglang/zig#14200]
### Zig Version

0.11.0-dev.900+0fb53bd24

### Steps to Reproduce and Observed Behavior

```zig
const testing = @import("std").testing;

const DirectionalPad = packed struct {
    x: i2 = 0,
    y: i2 = 0,
};

const Input = struct {
    dir: DirectionalPad = DirectionalPad{},
};

fn testPositive(input: Input) bool {
    return input.dir.y == 1;
}

var t: bool = true;

pub fn createInput() Input {
    return Input{
        .dir = DirectionalPad{ .x = 0, .y = if (t) 1 else 0 },
    };
}

test "packed struct member equality" {
    const is_positive = testPositive(createInput());
    try testing.expectEqual(is_positive, true);
}

```
It is the most minimal reproduction of this bug I could make. The test fails, however when "printf debugging" input.dir.y is 1, but comparing it with 1 fails.

### Expected Behavior

That input.dir.y is 1 and testing equal to 1 results in 'true'.

**Comment by DiskPoppy** [comment]
x86_64-macos.11.6.4...11.6.4-none

**Comment by schmee** [comment]
I'm able to reproduce it on `0.11.0-dev.980+601ab9a25` / `x86_64-macos.12.6...12.6-none`.

**Comment by marler8997** [comment]
Well this is interesting.  I tested this on 3 machines, all with the given compiler version `0.11.0-dev.900+0fb53bd24`.  Here are the results:

* linux-x86_64: PASS (issue does not reproduce)
* macos-AARCH64: PASS (issue does not reproduce)
* macos-x86_64: FAIL (issue DOES reproduce)

So looks like this is specific to macos x86_64!?!

I've minifed the example a bit more and added a couple comments in places that make the issue disappear:

```zig
const PackedStruct = packed struct {
    y: i7 = 0, // i8 works
};
const Wrap = struct {
    pack: PackedStruct,
};

var t = true; // const works

test "packed struct member equality" {
    const wrap = Wrap{
        .pack = PackedStruct{ .y = if (t) 1 else 0 },
    };
    try @import("std").testing.expectEqual(true, wrap.pack.y == 1);
}
```

**Comment by IntegratedQuantum** [comment]
I was able to reproduce on my `x86_64-linux` machine on `0.11.0-dev.1182+fd0fb26ab`
I also managed to reproduce this on [godbolt](https://gcc.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:zig,selection:(endColumn:18,endLineNumber:19,positionColumn:18,positionLineNumber:19,selectionStartColumn:18,selectionStartLineNumber:19,startColumn:18,startLineNumber:19),source:'const+testing+%3D+@import(%22std%22).testing%3B%0A%0Aconst+DirectionalPad+%3D+packed+struct+%7B%0A++++x:+i2+%3D+0,%0A++++y:+i2+%3D+0,%0A%7D%3B%0A%0Aconst+Input+%3D+struct+%7B%0A++++dir:+DirectionalPad,%0A%7D%3B%0A%0Afn+testPositive(input:+Input)+bool+%7B%0A++++return+input.dir.y+%3D%3D+1%3B%0A%7D%0A%0Avar+t:+i2+%3D+1%3B%0A%0Apub+fn+createInput()+Input+%7B%0A++++return+Input%7B%0A++++++++.dir+%3D+DirectionalPad%7B+.x+%3D+0,+.y+%3D+t+%7D,%0A++++%7D%3B%0A%7D%0A%0Apub+fn+main()+!!void+%7B%0A++++const+is_positive+%3D+testPositive(createInput())%3B%0A++++try+testing.expectEqual(is_positive,+true)%3B%0A%7D'),l:'5',n:'0',o:'Zig+source+%231',t:'0')),k:52.44066278549037,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:output,i:(editorid:1,fontScale:14,fontUsePx:'0',j:2,wrap:'1'),l:'5',n:'0',o:'Output+of+zig+trunk+(Compiler+%232)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:ztrunk,deviceViewOpen:'1',filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'1',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:2,lang:zig,libs:!(),options:'',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+zig+trunk+(Editor+%231)',t:'0')),header:(),k:40.07981755986317,l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:47.55933721450963,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4) which also seems to use linux.

I was not able to reproduce the minified version of @marler8997 on linux. So we might have two different issues here.

**Comment by codethief** [comment]
I've run into the same issue and have been able to reproduce it with the following code, using [zig-linux-x86_64-0.11.0-dev.1605+abc9530a8](https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.1605+abc9530a8.tar.xz):

```
const std = @import("std");
const expect = std.testing.expect;

// Using the new tuple type declaration introduced in the upcoming [v0.11.x](https://github.com/ziglang/zig/issues/4335)
const BoardPosition = packed struct {  // <---- Remove `packed` and everything works fine
    u3, 
    u3,
};

/// index (values 0-63) enumerates the 64 squares of an 8x8 board, from top left to bottom right
fn u6toBoardPosition(index: u6) BoardPosition {
    const row = @intCast(u3, index / 8);
    const column = @intCast(u3, index % 8);

    std.debug.print("row:column (raw) = {}:{}\n", .{ index / 8, index % 8 }); // outputs "7:7"
    std.debug.print("row:column (cast) = {}:{}\n", .{ row, column }); // outputs "7:7"

    return .{ row, column };
}

test "MyTest" {
    const pos = u6toBoardPosition(@intCast(u6, 63));

    std.debug.print("row:column (packed) = {}:{}\n", pos); // outputs "7:0" on my machine when using the packed struct, otherwise "7:7".
    
    try expect(pos[0] == 7);
    try expect(pos[1] == 7);
}
```

**Comment by jacobly0** [comment]
Note that the test failure depends on the value of uninitialized bits on the stack, so the target-specificity is a red herring.
