### ISSUE TITLE
Stance on language conventions

### ISSUE THREAD

**Issue by kuon** [ziglang/zig#14228]
First, I apologize for using the bug tracker, but it is the best way to have something visible I can reference to in the future.

We are currently planning to invest in zig, with tooling, integration in our system but also money (sponsoring the zig project itself).

We really like the language, what it provides and how it is governed. We have been using it heavily for a year and are convinced it is the right tool for some of our applications.

But, being a language in development, there are things that are subject to change and that's fine, but we have to be sure that we will be able to adapt in the future and that no changes will mean "no no" for us.

While discussing with our team, I realized that there was one thing that was causing a problem much bigger than what I first anticipated, and this problem is coding style and convention.

Personally, I usually don't care, I use the style that make sense for the project I am working on with the tool I am working on, I have [a preference](https://github.com/ziglang/zig/issues/1097#issuecomment-1162608024) for not using `camelCase` but in the end, I can adapt. If a language forces a style, I might groan a little, but I can forget about it and just "follow along".

When working with a team, and most importantly large companies, this is another story. Many companies have style guide that are very strict (for good or bad reasons, that's not the point) and want their code to follow that style. That's why in the C ecosystem, there is a gazillion different styles. While having a language convention is absolutely fine for the language built-ins and stdlib (and again, I am not asking to change that, this is not a revival of https://github.com/ziglang/zig/issues/1097  ) enforcing that convention would be very detrimental to the use in enterprise/corporate environment where "stupid" rules have to be followed.

To be transparent, this issue did arise when some people on our managing team read https://github.com/ziglang/zig/issues/8288 and https://github.com/nim-lang/RFCs/issues/456 which could be scary changes for companies that invested in a technology. We also had a bad experience with the `elm` language, which we loved, and had to abandon because of some very strong stance against `kernel` code.

So what I am asking is very simple, we would like an "official" stance on that point, confirming that `zig` will always happily allow any style and keep the status quo. Keeping the style guide as a recommendation and not, for example, starting to refuse packages not following it (something `elm` did with kernel code).

We want to focus on writing quality code and help the language ecosystem evolve in a strong way. We really look forward in building awesome things with zig.

Cheers

**Comment by matu3ba** [comment]
Related: https://github.com/ziglang/zig/issues/35.

**Comment by andrewrk** [comment]
> So what I am asking is very simple, we would like an "official" stance on that point, confirming that `zig` will always happily allow any style and keep the status quo. Keeping the style guide as a recommendation and not, for example, starting to refuse packages not following it (something `elm` did with kernel code).

Here is what I can officially promise:

Zig will not enforce identifier naming conventions according to any style. The "style guide" will always be merely offered as a point of commonality for different groups to standardize on, but will not be any kind of rules or enforcement from the language or tooling.

Errors such as unused variables or misleading indentation are about *catching bugs*, not enforcing any particular style.

What I can't promise yet is that the naming conventions used in the standard library won't change. I think most people are happy with TitleCase for types and snake_case for identifiers. But camelCase has always been controversial, even within my own mind.

The one thing that has always been in the style guide from the start is this:

> if there is an established convention..., follow the established convention.

This advice has always proven salient.

Hope that helps.

**Comment by kuon** [comment]
Thanks you. This is very helpful and will help us invest in zig with a peace of mind. The important point being the freedom and being sure we won't someday get a compiler error because we use a specific style.

Again, thanks for your involvement in zig and all your efforts, we have six internal projects that use it at present, and I hope I'll be able to push more people towards it when it is the right tool for the job.
