### ISSUE TITLE
`Thread.Id` type is bigger than necessary on most operating systems.

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#14236]
## Use Case
Sometimes it may be useful to put the thread id into an atomic. See for example #14103 and #14117.
However on x86 (32 bit), there seems to be no support for 64 bit atomics.

## Description
Right now `Thread.Id` is hardcoded to a u64:
https://github.com/ziglang/zig/blob/08b2d491bcd8c79c68495267cc71967661caea1e/lib/std/Thread.zig#L259
On the other hand for most OS it is implement using a `u32`:

#### On windows a kernel32 function is called which returns a `DWORD` (aka `u32`)
https://github.com/ziglang/zig/blob/08b2d491bcd8c79c68495267cc71967661caea1e/lib/std/Thread.zig#L470
https://github.com/ziglang/zig/blob/08b2d491bcd8c79c68495267cc71967661caea1e/lib/std/os/windows/kernel32.zig#L170
https://github.com/ziglang/zig/blob/08b2d491bcd8c79c68495267cc71967661caea1e/lib/std/os/windows.zig#L2100

#### For linux and a bunch of other operating systems the result is explicitly cast to `u32`:
https://github.com/ziglang/zig/blob/08b2d491bcd8c79c68495267cc71967661caea1e/lib/std/Thread.zig#L731
https://github.com/ziglang/zig/blob/08b2d491bcd8c79c68495267cc71967661caea1e/lib/std/Thread.zig#L584-L598

#### On apple it seems to be a `u64`
https://github.com/ziglang/zig/blob/08b2d491bcd8c79c68495267cc71967661caea1e/lib/std/Thread.zig#L578-L583

#### And I was unable to figure out what the posix else case is returning:
https://github.com/ziglang/zig/blob/08b2d491bcd8c79c68495267cc71967661caea1e/lib/std/Thread.zig#L600

**Comment by r00ster91** [comment]
Wouldn't this work?
```diff
 /// Represents a unique ID per thread.
-pub const Id = u64;
+pub const Id = switch (target.os.tag) {
+    .linux => u32,
+    .macos, .ios, .watchos, .tvos => u64,
+    .dragonfly,
+    .netbsd,
+    .freebsd,
+    .openbsd,
+    .haiku,
+    => u32,
+    else => usize,
+};
```

**Comment by IntegratedQuantum** [comment]
> Wouldn't this work?

Yes.

**Comment by nektro** [comment]
should perhaps be the same as `std.os.pid_t`

**Comment by r00ster91** [comment]
But `std.Thread.Id` is the thread ID and not the process ID, right?
```
       pid_t

              This  type is used for storing process IDs, process group IDs, and session IDs.  According to POSIX, it shall be a signed integer type,
```
I would say a process contains threads, each of which has a unique ID.
Additionally, this type is signed, which also leads me to believe it is not the right type.

**Comment by nektro** [comment]
https://man7.org/linux/man-pages/man2/gettid.2.html

>        gettid - get thread identification

```c
       #define _GNU_SOURCE
       #include <unistd.h>

       pid_t gettid(void);
```

**Comment by r00ster91** [comment]
It's signed though. `@Type(.Int{.signedness = .unsigned, .bits = @bitSizeOf(std.os.pid_t))`? Is that worth it? Or should it be changed to be signed? Not sure if that makes sense.

**Comment by r00ster91** [comment]
And I suppose all other places should also be updated to use `@Type(.Int{.signedness = .unsigned, .bits = @bitSizeOf(std.os.pid_t))`. I think it's okay for it to be an explicit and specific unsigned integer type.
