### ISSUE TITLE
Spurious "TODO: Implement more pointer eql cases" in comptime

### ISSUE THREAD

**Issue by 17dec** [ziglang/zig#14234]
### Zig Version

0.11.0-dev.1186+83fd45d82

### Steps to Reproduce and Observed Behavior

```zig
const L = union(enum) {
    empty,
    next: *const L,
};

fn construct(n: usize) !L {
    return if (n == 0) L{.empty={}} else L{.next = &try construct(n-1)};
}

fn count(l: L) usize {
    return switch (l) {
        .empty => 0, 
        .next => |e| 1+count(e.*),
    };
}

test "x" {
    _ = comptime count(try construct(100));
}
```

Above code appears to sometimes succeed and sometimes fail with the following error:

```
thread 29046 panic: TODO: Implement more pointer eql cases
Analyzing t.zig: t.zig:count
      %83 = switch_capture(%76, 1)
      %86 = dbg_block_begin()
      %87 = dbg_var_val(%83, "e")
      %88 = decl_val("count") token_offset:13:24 to :13:29
      %89 = dbg_stmt(4, 29)
    > %90 = call(.auto, %88, [
        {
          %91 = validate_deref(%83) node_offset:13:30 to :13:33
          %92 = load(%83) node_offset:13:30 to :13:33
          %93 = break_inline(%90, %92)
        },
      ]) node_offset:13:24 to :13:34
      %94 = dbg_stmt(4, 23)
      %95 = add(@Zir.Inst.Ref.one, %90) node_offset:13:22 to :13:34
      %96 = store_node(%72, %95) node_offset:13:22 to :13:34
      %97 = dbg_block_end()
      %98 = break(%76, @Zir.Inst.Ref.void_value)
    For full context, use the command
      zig ast-check -t t.zig

[..]
```

May need several attempts, possibly with a clean cache, to trigger the error. It usually triggers for me within 1-5 attempts on Linux x86_64.

Given the spurious nature of the error, I suspect it's more likely a case of memory corruption than a case of "implementing more eql cases". The main trigger seems to be storing and later using the address of a `try function()`. No clue if that's even legal in comptime code.

### Expected Behavior

Either working code (i.e. `count()` returning 100) or a reliable compiler error.

**Comment by 17dec** [comment]
Huh, so this *was* a case of just implementing more eql cases. Interesting.

Thanks for the quick fix!

**Comment by Vexu** [comment]
I did notice the spurious nature of the error but running a debug build in a debugger made it crash 100% of the time so there wasn't much else I could do than implement it.
