### ISSUE TITLE
use C++ LLVM API rather than C API for array types to support 64 bits

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1424]
See #1422 

```zig
fn recur() [4294967397]u8 {
    return recur();
}

export fn entry() void {
    var loophole = recur();
}

const builtin = @import("builtin");
pub fn panic(msg: []const u8, error_return_trace: ?*builtin.StackTrace) noreturn {
    while (true) {}
}
```

the LLVM IR for this is:

```llvm
; Function Attrs: nobuiltin nounwind
define internal fastcc void @recur([101 x i8]* nonnull sret) unnamed_addr #2 !dbg !53 {
Entry:
```

The `101` is because it wrapped around 32 bits. This is because the LLVM C API uses `unsigned` but the C++ API uses uint64_t: `static ArrayType *get(Type *ElementType, uint64_t NumElements);`

So if we switch to the C++ API to make LLVM array types it fixes this bug.

**Comment by BarabasGitHub** [comment]
I seriously hope nobody will ever need a fixed size array larger than 4GB.

**Comment by thejoshwolfe** [comment]
> I seriously hope nobody will ever need a fixed size array larger than 4GB.

It's definitely possible, especially when you're not running in an OS.

**Comment by nektro** [comment]
I submitted a patch to enable the C api to take advantage of `u64` array lengths which has now landed as https://github.com/llvm/llvm-project/commit/35276f16e5a2cae0dfb49c0fbf874d4d2f177acc and will likely make it as part of LLVM 17

**Comment by nektro** [comment]
completed in https://github.com/ziglang/zig/commit/6a07b7024a33211f158f0c332267050955896918

**Comment by andrewrk** [comment]
Nice work @nektro!
