### ISSUE TITLE
.h file macro constant expr gets translated incorrectly

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1425]
```c
#define VK_SUBPASS_EXTERNAL               (~0U)
```

incorrectly gets translated as 

```zig
pub const VK_SUBPASS_EXTERNAL = if (@typeId(@typeOf(U)) == @import("builtin").TypeId.Pointer) @ptrCast(~0, U) else if (@typeId(@typeOf(U)) == @import("builtin").TypeId.Int) @intToPtr(~0, U) else (~0)(U);
```

expected:

```zig
pub const VK_SUBPASS_EXTERNAL = ~c_uint(0);
```

**Comment by andrewrk** [comment]
Reopening because we don't have a test case for `(~0U)` yet.

**Comment by Sahnvour** [comment]
The issue was only related to the suffix, that's why I did not add `(~0U)` in the tests, but I checked that it gave the expected result. I can add it if you still want it.

**Comment by andrewrk** [comment]
Would you? I foresee translate-c going though some big reworking soon, so the more coverage we have the better.

**Comment by andrewrk** [comment]
Thanks for the follow up in https://github.com/ziglang/zig/pull/2053
