### ISSUE TITLE
ability to `@import` dependencies directly in build.zig scripts

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#14279]
Extracted from #14265.

Within a build.zig file, `@import` should be allowed, and it should refer to the build.zig file of any dependencies listed in the manifest file.

Example:

build.zig.zon

```zig
    .dependencies = .{
        .@"android-sdk" = .{
            .url = "...",
            .hash = "...",
        },
    },
```

build.zig

```zig
const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    const exe = b.addExecutable("app", "src/main.zig");

    @import("android-sdk").helperFunction(exe);
}
```

build.zig of android-sdk:

```zig
const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    // ...
}

pub fn helperFunction(artifact: *std.build.LibExeObjStep) void {
    // ...
}
```

cc @MasterQ32

**Comment by MasterQ32** [comment]
Yep that should be fully sufficient, as long as transitive dependencies work and will be properly deduplicated. So the following thing should work (assuming matching versions):

```
root_project
  -> library_a
  -> library_b
    -> library_c
      -> library_a
```

When `library_b` returns a type from `library_a`, those should be the same as the ones returned from the `root_project` dependency `library_a`.

**Comment by marler8997** [comment]
I implemented the ability to add recursive packages to `build.zig` in this PR: https://github.com/ziglang/zig/pull/8072

Also in that PR was an implementation for a proposal to add a `buildpkgs` builtin that `build.zig` could use to query optional dependencies.

That PR allowed you to do something like this:
```zig
const buildpkgs = @import("buildpkgs");
if (comptime buildpkgs.has("android-sdk")) {
    const android_sdk = @import("android-sdk");
    // code that handles having android-sdk
} else {
    // code that handles NOT having android-sdk
}
```
Looking back now it feels like there might be a slightly better interface.  `buildpkgs.zig` could maybe look something more like this:

```zig
// if android sdk is available
pub const android_sdk: ?type = @import("android-sdk");
// if android sdk is not available
pub const android_sdk: ?type = null;
```

Then in `build.zig`
```zig
const buildpkgs = @import("buildpkgs");
if (buildpkgs.android_sdk) |android_sdk| {
    // code that handles having android-sdk
} else {
    // code that handles NOT having android-sdk
}
```

Not familiar with the new package manager constructs yet so the same concept might look different.
