### ISSUE TITLE
a zig subcommand that fetches remote dependencies so that subsequent `zig build` executions are guaranteed to not attempt network access

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#14280]
Extracted from #14265.

I can think of two possibilities:

```
zig build --fetch
```

```
zig fetch
```

This is straightforward to implement; it would run this code, without actually running the build_runner:

https://github.com/ziglang/zig/blob/7cb2f9222da38d687e8708dd5d94d3175cc77995/src/main.zig#L4080-L4126

One thing to consider would be a slightly higher level abstraction of subcommand which would additionally build and install dev dependencies. For example, if there were a binary tool that should be available, it should get installed. But that can be a follow-up issue.

I think I like the `zig build --fetch` option better because `zig fetch` sounds like it might download a URL directly, which is not an outrageous idea considering the "Zig as Dependency Zero" motto.

**Comment by deflock** [comment]
Until the last sentence I thought there will be two separate commands: `zig fetch` for just downloading, and `zig build --fetch` for downloading+building.

**Comment by andrewrk** [comment]
`zig build` does everything, while avoiding redundant work if possible, such as accessing the network. See also #14283.

**Comment by kuon** [comment]
I like the elixir approach where you have to run `mix deps.get` at least once before you can compile. It makes it more explicit. Having `zig build` do everything is convenient, but it makes it further from `build` and would make it more complex.
