### ISSUE TITLE
support fetching dependencies bundled with `.tar.zst` extension

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#14299]
Extracted from #14265.
Depends on #14183.

`zig build` should support fetching via an URL like this:

```zig
    .url = "https://example.com/foo.tar.zst",
```

https://github.com/ziglang/zig/blob/7cb2f9222da38d687e8708dd5d94d3175cc77995/src/Package.zig#L357-L376

Related:
 * #14300

**Comment by andrewrk** [comment]
Typo, thank you

**Comment by dweiller** [comment]
I have a (mostly untested) branch that adds support for Zstandard compressed tarballs, but it first does some minor surgery on `std.compress` to make the high level decompession APIs more similar. I've opened https://github.com/ziglang/zig/issues/14739 to get some input on how `std.compress` could be made more consistent across formats.
