### ISSUE TITLE
Doc: Can Zig export a C-compatible shared-object API?

### ISSUE THREAD

**Issue by binary132** [ziglang/zig#1431]
For example in Rust (`extern "C"`):
https://doc.rust-lang.org/book/second-edition/ch19-01-unsafe-rust.html#calling-rust-functions-from-other-languages .

For example in C++ (`extern "C"`):

https://en.cppreference.com/w/cpp/language/language_linkage

This appears to be the extent of the documentation in Zig:

https://ziglang.org/documentation/master/#Mixing-Object-Files

Is this the full extent of documentation on the topic?  How is the header file generated, or does the build program need to use a special invocation to achieve that?  Must the library be used as a shared object, or can it be statically linked?  Is there any documentation available for the build system?

**Comment by andrewrk** [comment]
Yep, sure can, and it's one of the tests in the test suite.

Use the `export` keyword on functions, variables, and types:

`export fn foo() void`

Then

`zig build-lib foo.zig`

**Comment by binary132** [comment]
:clap: :clap:
