### ISSUE TITLE
compiler: incorrect handling of the NUL character

### ISSUE THREAD

**Issue by perillo** [ziglang/zig#14346]
### Zig Version

0.11.0-dev.1327+b42bd759a

### Steps to Reproduce and Observed Behavior

I used the program https://gist.github.com/perillo/2b7e8d2ad32b5bf140fdfc9d84f29e7c to check if the Zig compiler handles correctly all the invalid Ascii control characters as documented in https://ziglang.org/documentation/master/#Source-Encoding.

All invalid control characters are rejected, excluding the `NUL` character.
When at the start of the file, `NUL` is rejected (file `NUL-start.zig`), but when in the middle of the file it is ignored (file `NUL-middle.zig`).

Additionally, on my old Haswell processor, I noted that `zig test ACK-middle.zig` takes 0.236s, while `zig test NUL-middle.zig` takes 0.983s; a 4x increase.

`NUL-start.zig` contains the bytes `\x00// NUL\n`.
`NUL-middle.zig` contains the bytes `// NUL\x00\n`.

### Expected Behavior

The Zig compiler should always reject the NUL character.

**Comment by r00ster91** [comment]
It sounds related to #13811
