### ISSUE TITLE
wasm backend issues

### ISSUE THREAD

**Issue by star-tek-mb** [ziglang/zig#14349]
### Zig Version

0.11.0-dev.1313+bb15e4057

### Steps to Reproduce and Observed Behavior

I have a project:

https://github.com/star-tek-mb/Paradise

Run with and go to http://127.0.0.1:8080
```
zig build run
```

Everything works. Green background and sprite on screen.

Change build mode in `build.zig`:
```
exe.setBuildMode(.Debug);
```

Getting white screen and console errors.

If I build with Debug mode - i will get errors. I think it's a WASM backend issues.
If I build with Release Small mode - everything is OK, which uses LLVM.

Console log if helps:
```
RuntimeError: unreachable
    at builtin.default_panic (001025f2:0x3c8)
    at sysjs.Object.call (001025f2:0x3264)
    at platform.gl.createTexture (001025f2:0x1fb5)
    at paradise.Texture.loadImage (001025f2:0x1d5f)
    at paradise.Sprite.fromSubImage (001025f2:0x3851)
    at paradise.Sprite.fromImage (001025f2:0x3e22)
    at main.main (001025f2:0x419a)
    at _start (001025f2:0xbe7d)
    at (index):40:26
```

If anything I can provide (logs, wasm file, etc) - i would provide. But I cant reduce down example for now, i will investigate.

I think it is regression. My project worked in debug mode in zig 0.10.0-dev-2f3727854.

### Expected Behavior

Expect same working behaviour as Release small mode.

**Comment by Vexu** [comment]
Both debug and release small use the LLVM backend by default with the key difference being that ReleaseSmall doesn't include safety checks. By defining a simple panic handler I was able to see that the error is caused by a `cast causes pointer to be null` that were being added due to bad boolean logic. With that fixed I was able to build it in debug mode.

```zig
pub fn panic(msg: []const u8, _: ?*std.builtin.StackTrace, _: ?usize) noreturn {
    std.log.err("{s}", .{msg});
    @breakpoint();
    while (true) {}
}
```
