### ISSUE TITLE
Remove `std.mem.span` or disallow it on arrays and slices

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#14383]
### Zig Version

0.11.0-dev.1366+c70a3d902

### Steps to Reproduce and Observed Behavior

1. Paste code:
```zig
const std = @import("std");

test "whatami" {
    var outbuf: [128 + 1 + "BoringSSL error: ".len]u8 = undefined;
    @memset(&outbuf, 0, outbuf.len);
    outbuf[0.."BoringSSL error: ".len].* = "BoringSSL error: ".*;
    const error_message: []const u8 = std.mem.span(std.meta.assumeSentinel(&outbuf, 0));
    std.log.warn("\n\nerror_message len: {d}\n", .{error_message.len});
}
```
2. Panic

```zig
Test [1/1] test.whatami... thread 491655 panic: sentinel mismatch: expected 0, found 102
/Users/jarred/zig/0.11.0-dev.1366+c70a3d902/files/lib/std/mem.zig:715:19: 0x10079c967 in span__anon_1186 (test)
        return ptr[0..l :s];
                  ^
/Users/jarred/Desktop/repro.zig:21:75: 0x10079c753 in test.whatami (test)
    const error_message: []const u8 = std.mem.span(std.meta.assumeSentinel(&outbuf, 0));
                                                                          ^
/Users/jarred/zig/0.11.0-dev.1366+c70a3d902/files/lib/test_runner.zig:66:28: 0x10079d163 in main (test)
        } else test_fn.func();
                           ^
/Users/jarred/zig/0.11.0-dev.1366+c70a3d902/files/lib/std/start.zig:606:22: 0x10079ed3f in main (test)
            root.main();
                     ^
???:?:?: 0x1b022fe4f in ??? (???)
???:?:?: 0x1d3bffffffffffff in ??? (???)
error: the following test command crashed:
/Users/jarred/Code/bun/zig-cache/o/991baa9e11a9ec215298515b4db056f1/test
```

### Expected Behavior

Either:

option a):
```zig
error_message len: 0
```

option b): compiler error that assumeSentinel doesn't support a pointer to a fixed-size array, use sliceTo instead

**Comment by Vexu** [comment]
`std.mem.span` already documents this:
https://github.com/ziglang/zig/blob/fe6dcdba1407f00584725318404814571cdbd828/lib/std/mem.zig#L700-L702

**Comment by leecannon** [comment]
@Jarred-Sumner you want `std.mem.sliceTo(ptr, 0)` to guarantee scanning for the sentinel.

**Comment by Jarred-Sumner** [comment]
If I ran into this, other people will too and they will ship bugs to production because of it

**Comment by Vexu** [comment]
I would be in favor of disallowing `span` on arrays and slices or removing it entirely.

**Comment by InKryption** [comment]
I personally think it would make sense to remove it. What does it offer over `std.mem.sliceTo`?

**Comment by ifreund** [comment]
> I would be in favor of disallowing `span` on arrays and slices or removing it entirely.

I agree, I've got a WIP patch to do this locally which is coming along nicely.

I think it would make sense to first make `std.mem.span()` a compile error for everything except sentinel terminated pointers and C pointers. This should catch all the incorrect usages of it but won't be a breaking change for most code.

We can then consider removing it entirely after a full release cycle has gone by in favor of `std.mem.sliceTo`, at which point a simple find and replace could be used to do the more widely breaking upgrade without needing to worry about changing semantics.

**Comment by Jarred-Sumner** [comment]
I think it's good DX for std.mem.span to work on both slices and sentinel-terminated slices because you don't have to think as much & you can use it with anytype arguments. That part  means you're less likely to make a mistake 

imo the problem is just that std.mem.span returns the size of arrays as length instead of searching for a sentinel

**Comment by nektro** [comment]
`std.meta.trait.isSlice` can differentiate in the callee
