### ISSUE TITLE
unable to run compiler as it crashes

### ISSUE THREAD

**Issue by kamaaina** [ziglang/zig#14393]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

on arch linux install with package manager and try to create and executable and compile it

![zig-crash](https://user-images.githubusercontent.com/4704715/213847848-997dddf2-3fdd-4fc4-bed0-c4860b2c1ffe.png)

### Expected Behavior

the simple 'hello world' application would compile and run

**Comment by andrewrk** [comment]
Please file an issue with the maintainer of the arch linux package.

**Comment by daurnimator** [comment]
Arch's zig 0.10.1 was built without specifying `ZIG_TARGET_MCPU` which is meant to be `baseline`.
Is zig ignoring the cpu and using my native cpu features?

**Comment by daurnimator** [comment]
> without specifying `ZIG_TARGET_MCPU` which is meant to be `baseline`.

Looks like that was changed recently: https://github.com/ziglang/zig/commit/d27007cd7e66df8db72cfaa7e5dcd3de65857ac8#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR121
Will add `ZIG_TARGET_MCPU` and push a new package now

**Comment by uncomfyhalomacro** [comment]
> > without specifying `ZIG_TARGET_MCPU` which is meant to be `baseline`.
> 
> Looks like that was changed recently: [d27007c#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR121](https://github.com/ziglang/zig/commit/d27007cd7e66df8db72cfaa7e5dcd3de65857ac8#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR121) Will add `ZIG_TARGET_MCPU` and push a new package now

I noticed this change too and was about to send that diff. thanks for sharing that you noticed it too. I was planning to add zig in openSUSE before 0.11.x lands

**Comment by uncomfyhalomacro** [comment]
I can confirm that fixed it. 😀

**Comment by kamaaina** [comment]
thanks everyone, i can confirm it is working as well
