### ISSUE TITLE
GitHub Wiki: Packaging status shown twice for nixpkgs stable 22.11

### ISSUE THREAD

**Issue by salameme** [ziglang/zig#14408]
The Packaging Status shows `nixpkgs stable 22.11` twice with different versions:

![packaging status for nixpks, it shows both nixpkgs stable 22.11 twice, one with version 0.8.1 and the other with version 0.9.1](https://user-images.githubusercontent.com/60845989/213909710-70c2573b-4e23-4bbd-83d2-a7fa6cdab90a.png)

It also seems to be duplicated in Repology:

![Repology packaging status for nixpkgs, it shows both nixpkgs stable 22.11 and 22.05 twice, both versions of nixpkgs use zig versions 0.8.1 and 0.9.1](https://user-images.githubusercontent.com/60845989/213909781-7a5f5912-f198-4550-9512-e26f807fa81c.png)

**Comment by salameme** [comment]
Neither the `bug` nor the `autodoc` tags seemed fitting, but because it deals with docs I ended up settling for `autodoc`, for future refence; what should I do in this case?

**Comment by Vexu** [comment]
> The Packaging Status shows `nixpkgs stable 22.11` twice with different versions:

The first one is 21 not 22.

> for future refence; what should I do in this case?

At the bottom of the page there is a link to create a blank issue:
> Don’t see your issue here? [Open a blank issue. ](https://github.com/ziglang/zig/issues/new)

**Comment by salameme** [comment]
I seem to be blind
