### ISSUE TITLE
unsupported macos: Zig should not try linking against libc we provide and provide an error message

### ISSUE THREAD

**Issue by kubkon** [ziglang/zig#14407]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

When building natively on an unsupported macOS version, not explicitly overriding the target triple (aka assuming native), Zig should not try using libc for a newer macOS version as it appears to do https://github.com/ziglang/zig/issues/14405

tl;dr this should result in an error(s) that no sysroot was provided:

```
zig build
```

### Expected Behavior

We should flag the missing sysroot and libc stubs in some way.

**Comment by MoAlyousef** [comment]
Also updating a macos system doesn't necessarily update libSystem, so similar errors can arise with newer macOS version which have older toolchains:
https://github.com/ziglang/zig/issues/14230

**Comment by kubkon** [comment]
I believe https://github.com/ziglang/zig/pull/17152 fixes this.
