### ISSUE TITLE
Missing `libkern/OSCacheControl.h` header on macOS

### ISSUE THREAD

**Issue by alexrp** [ziglang/zig#14424]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

```c
#include <libkern/OSCacheControl.h>

int main() {}
```

`zig cc test.c -target aarch64-macos-none`

```text
test.c:1:10: fatal error: 'libkern/OSCacheControl.h' file not found
#include <libkern/OSCacheControl.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

### Expected Behavior

The program should compile successfully.

**Comment by andrewrk** [comment]
related: #14184

**Comment by kubkon** [comment]
Fixed in https://github.com/ziglang/zig/commit/1b97881e38e56ae3bdfc4009265840b77fa9e325
