### ISSUE TITLE
Update @src docs

### ISSUE THREAD

**Issue by BreadTom** [ziglang/zig#14425]
Document how [@src](https://ziglang.org/documentation/master/#src) is similar to C’s [\_\_func\_\_](https://en.cppreference.com/w/c/language/function_definition), [\_\_FILE\_\_, \_\_LINE\_\_](https://en.cppreference.com/w/c/preprocessor/replace) and [\#line](https://en.cppreference.com/w/c/preprocessor/line) along with more code examples.

**Comment by andrewrk** [comment]
`@src` is documented here: https://ziglang.org/documentation/0.10.1/#src
