### ISSUE TITLE
CONTRIBUTING: update to the new bootstrap method

### ISSUE THREAD

**Issue by perillo** [ziglang/zig#14427]
The "Editing Source Code" section seems to still use the old C++ bootstrap method.
As an example:

 - "First, build the Stage 1 compiler as described in Building Zig From Source" is incorrect, since it builds `zig1`, `zig2` and stage3 (in `stage3/bin/zig`, currently not working).

 - "$BUILD_DIR/bin/zig build test-std -Dskip-release" is incorrect, because "only build-exe or build-obj is supported in a -Donly-c build"

 - "./build/zig test lib/std/fmt.zig --zig-lib-dir lib --main-pkg-path lib/std" is also incorrect, and it should be `zig build test` instead of `zig test`.

**Comment by squeek502** [comment]
> it should be zig build test instead of zig test.

This part is incorrect. `zig test` is intentionally used here to only run the tests on *one file*, not the entire test suite. Only the path to `zig` should be updated.
