### ISSUE TITLE
bufPrintZ stop with a runtime  usize  argument  on  riscv64 freestanding

### ISSUE THREAD

**Issue by laohua2023** [ziglang/zig#14431]
### Zig Version

0.11.0-dev.1025+aadd1b252

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

const UART_REG_TXFIFO  = @intToPtr(*volatile u32, 0x10000000);
pub fn putc(ch:u8) void
{
	while (UART_REG_TXFIFO.* < 0) {}
	UART_REG_TXFIFO.* = ch;
}


export fn main() void {
	putc('A');
	putc('A');
	putc('A');

	var a:usize = 1;
	var b:usize = 666;
	var x:usize = @ptrToInt(&b) + a;


	var tmpBuff:[100:0]u8 = undefined;
	var tmpstr = std.fmt.bufPrintZ(&tmpBuff, "hello {} world!", .{x} ) catch "999";  // <=  HANG HERE!
	for(tmpstr) |c| {
		putc(c);
	}
	putc('B');
	putc('B');
	putc('B');


	while(true) {}
}

pub fn panic(msg: []const u8, error_return_trace: ?*std.builtin.StackTrace, ret_addr: ?usize) noreturn {
	putc('P');
	_ = msg;
	_ = error_return_trace;
	_ = ret_addr;
	while (true) {
		@breakpoint();
	}
}
```

problem is:
just "AAA" printed , no "BBB" output....

### Expected Behavior

want "BBB" output

**Comment by Vexu** [comment]
How are you building and running it?

**Comment by andrewrk** [comment]
Thank you for the report. Unfortunately, we need more information to troubleshoot it. I will re-open if enough information is provided.

**Comment by laohua2023** [comment]
@Vexu thanks for your reply
here is the full source  code, included "build.cmd" to build it
https://github.com/laohua2023/zig_bufPrintZ_freestanding_issues

**Comment by laohua2023** [comment]
same problem appears on ARM64 freestanding, and maybe all freestanding targets

**Comment by laohua2023** [comment]
**issue close request**

due to the bad target setting in my build.zig

by changing cpu_model form   generic_rv64   => to  baseline_rv64,  problem disappeared,  everything is ok


sorry about that.....
