### ISSUE TITLE
String should be an array

### ISSUE THREAD

**Issue by hwoy** [ziglang/zig#14442]
### Zig Version

0.10.0

### Steps to Reproduce and Observed Behavior

``` Zig
export const STR1="AAAAAAAAAA";
export const STR2="AAAAAAAAAA".*;
```

``` Asm
	.globl	STR1
	.p2align	3
STR1:
	.quad	a.STR1__anon_207

a.STR1__anon_207:
	.asciz	"AAAAAAAAAA"

	.globl	STR2
STR2:
	.asciz	"AAAAAAAAAA"
```

### Expected Behavior

**String should be an array instead of a pointer to array.**

**Comment by ifreund** [comment]
I'm not sure what the supposed problem is here, `@TypeOf("foo")` is `*const [3:0]u8` which is a pointer to an array

**Comment by tau-dev** [comment]
> String should be an array instead of a pointer to array.

*Why?*

String literals being pointers to arrays is exactly the behavior that is described by the [documentation](https://ziglang.org/documentation/master/#String-Literals-and-Unicode-Code-Point-Literals), that should be expected, that is done by most other systems programming languages, and that is useful in practice.

**Comment by rohlem** [comment]
Do you have a use case that would benefit from this change?
I think the main reason for it is that string literal syntax in C does (pretty much) the same thing.
Most current uses don't (immediately) dereference the pointer, so if we change the default they would have to add an addressof `&`.
