### ISSUE TITLE
Treat an allowzero pointer as a nullable pointer

### ISSUE THREAD

**Issue by hwoy** [ziglang/zig#14441]
### Zig Version

0.10.0

### Treat an allowzero pointer as a nullable pointer

```Zig
pub fn nullPtr(comptime T: type) *allowzero T {
    return @intToPtr(*allowzero T, 0);
}
pub fn nullPtrMany(comptime T: type) [*:0]allowzero T {
    return @intToPtr([*:0]allowzero T, 0);
}

pub fn main() !void {
    const std = @import("std");
    const w = std.io.getStdOut().writer();

    const LIST_NAME = [_][*c]const u8{ "Hwoy", "Sam", "Army", null };
    for (LIST_NAME) |name| {
        if (name) |str|
            try w.print("{s}\n", .{str});
    }

    const LIST = [_][*:0]allowzero const u8{ "Hwoy", "Sam", "Army", nullPtrMany(u8) };
    for (LIST) |name| {
        if (@ptrCast(?[*:0]const u8, name)) |str|
            try w.print("{s}\n", .{str});
    }
}

```

### Expected Behavior

# An ``` allowzero ``` pointer
* ``` *allowzero T``` can use ``` null ```  value
* ``` *allowzero T``` can be coerced to ```  ?* T ``` 
* ```  ?* T ``` can be coerced to ``` *allowzero T```

**Comment by rohlem** [comment]
I'm not sure whether you are only proposing the mentioned coercions, or something else/more.
("Treat _ as _" sounds like it suggests total equivalence to me.)

Do you have a particular use case which would benefit from these coercions?
In your example code, I don't see the benefit, or difference, between the `allowzero` variant and the optional pointer variant above.
Do you expect different behaviour? Or do you want to be able to write the same code both ways, and if so, why?

Note that `allowzero` is meant for _very_ niche use cases. It allows you to write code accessing address 0, even though most environments don't support this.
It is _deliberately_ a separate concept, and the combination `?* allowzero T` is also allowed in current semantics.

**Comment by r00ster91** [comment]
The question is, why not use `?*T`? The question mark indicates nullability whereas `*allowzero T` doesn't and it introduces another thing you have to remember. `*allowzero T` is quite niche and I wouldn't expect to see it in context with `null`. Associating `null` only with `?` types is simpler.

**Comment by ifreund** [comment]
https://github.com/ziglang/zig/wiki/Language-Proposals
