### ISSUE TITLE
Large array iteration on aarch64 segfaults.

### ISSUE THREAD

**Issue by fubark** [ziglang/zig#14457]
### Zig Version

0.11.0-dev.1438+5d46addd2

### Steps to Reproduce and Observed Behavior

```zig
pub fn main() !void {
    var insts: [9000000]u8 = undefined;
    insts[insts.len-1] = 255;
    var pc: [*]const u8 = &insts;
    while (true) {
        if (pc[0] == 255) {
            break;
        }
        pc += 1;
    }
}
```
```sh
zig run scratch.zig
zsh: segmentation fault  zig run scratch.zig
```

### Expected Behavior

It should work. I tested the same code on x86_64 and it works.

**Comment by fubark** [comment]
Looks like its just the large array declaration. This fails:
```zig
pub fn main() !void {
    var insts: [9000000]u8 = undefined;
    _ = insts;
}
```

**Comment by Vexu** [comment]
You're running out of stack space, either increase the stack size with `--stack` or allocate the array on heap.
