### ISSUE TITLE
Package manager dependency does not inherit build target and release mode

### ISSUE THREAD

**Issue by star-tek-mb** [ziglang/zig#14461]
### Zig Version

0.11.0-dev.1438+5d46addd2

### Steps to Reproduce and Observed Behavior

I know it's still MVP, but good to report this issue.

I have [project](https://github.com/star-tek-mb/migrator).

With `build.zig.ini`:
```ini
[package]
name=test-sqlite3
version=0.0.1

[dependency]
name=sqlite3
url=https://github.com/star-tek-mb/sqlite3-zig/archive/d0d9b6d414956c43d057142c91a820cfaeee86a2.tar.gz
hash=81d3b8285411e394fbfe6fa980a8b4fd425f075eb2ca50eea98ee6d53a9c1cac
```

When I'm trying to cross compile it to windows (from linux) i'm getting error:

```
error: lld-link: unknown file type: /home/noobtek/.cache/zig/p/81d3b8285411e394fbfe6fa980a8b4fd425f075eb2ca50eea98ee6d53a9c1cac/zig-cache/o/0d68b3673546a15e9d1e9e52011fb49f/sqlite3.o
error: migrator...
error: The following command exited with error code 1
```

File type is:
```
/home/noobtek/.cache/zig/p/81d3b8285411e394fbfe6fa980a8b4fd425f075eb2ca50eea98ee6d53a9c1cac/zig-cache/o/0d68b3673546a15e9d1e9e52011fb49f/sqlite3.o:
ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
```

So my **dependency** compiled for linux, but my **package** compiled for windows.

### Expected Behavior

Expected `zig build -Drelease-small -Dtarget=x86_64-windows-gnu` to succeed.

**Comment by andrewrk** [comment]
This is #14285.
