### ISSUE TITLE
ptrCast confusing error message

### ISSUE THREAD

**Issue by ryuukk** [ziglang/zig#14474]
### Zig Version

0.11.0-dev.6184+56493e205

### Steps to Reproduce and Observed Output

```zig
var hm = @ptrCast(*c.mg_http_message, ev_data);
```
I get:

```
projects\libs\rt\mongoose.zig:151:22: error: cast increases pointer alignment
            var hm = @ptrCast(*c.mg_http_message, ev_data);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
projects\libs\rt\mongoose.zig:151:51: note: '?*anyopaque' has alignment '1'
            var hm = @ptrCast(*c.mg_http_message, ev_data);
                                                  ^~~~~~~
projects\libs\rt\mongoose.zig:151:31: note: '*C:.dev.kdomz.zig-cache.o.7ff080740cfb0a9ac815e337e8658958.cimport.struct_mg_http_message' has alignment '8'
            var hm = @ptrCast(*c.mg_http_message, ev_data);
                              ^~~~~~~~~~~~~~~~~~
error: server...
```

Doesn't tell me what i should do, i ask to cast, why does it complain? then there are empty ``^~~~``

Doc doesn't say anything about aligment https://ziglang.org/documentation/master/#ptrCast

### Expected Output

Error message should tell me what is wrong

Doc should says what i should provide/call

**Comment by Vexu** [comment]
It only modifies the alignment so it only asks for the alignment, it is supposed to be used with `@ptrCast`. What would you expect the error to say?

**Comment by nektro** [comment]
`@alignOf` accepts a type and it should be the non-pointer version of the type you pass to `@ptrCast`
