### ISSUE TITLE
`zig build-lib -target wasm32-freestanding` does not produce a .wasm file

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#14501]
### Zig Version

0.11.0-dev.1393+38eebf3c4

### Steps to Reproduce and Observed Behavior

https://twitter.com/mlafeldt/status/1620367650223431680?s=46&t=ay2LyfUxVnch1jOgVO5Ykg

Code:
```zig

pub export fn myWasmLibIsNotWasm() i32 {
    return 42;
}

comptime {
    _ = myWasmLibIsNotWasm;
}

```

Run:
```bash
zig build-lib -target wasm32-freestanding hey-wasm.zig
```

You get two files:
- libhey-wasm.a
- libhey-wasm.a.o

Which one should you pick? My first guess was libhey-wasm.a.

<img width="257" alt="image" src="https://user-images.githubusercontent.com/709451/215738780-f1d7d2d1-d3c2-45b2-8f64-29c68e2bd730.png">

Nope. Guess it has to be the other one. Why is the file extension `.a.o` instead of `libhey.wasm`? or possibly the name should be `hey.wasm`
<img width="574" alt="image" src="https://user-images.githubusercontent.com/709451/215738838-c03b71b7-e28b-4461-b73a-803b60ce2193.png">

<img width="523" alt="image" src="https://user-images.githubusercontent.com/709451/215738549-3506b449-de9e-4870-8f55-0dacede30ed0.png">

### Expected Behavior

It should produce a single .wasm file

**Comment by Luukdegram** [comment]
The `.o` file is an artifact from LLVM that's used during compilation to generate the result. The default output of `build-lib` is a static library (the `.a` file). What you want is a shared library, which can be done by passing `-dynamic` as specified by the language reference.
