### ISSUE TITLE
Segmentation fault when writing to `*align(8) @Vector(4, f64)`

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#14527]
### Zig Version

0.11.0-dev.1457+cb9d00e1a

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() void {
	const Vec = @Vector(4, f64);
	std.log.info("{} {}", .{@sizeOf(Vec), @alignOf(Vec)});
	var arr: [6]f64 = undefined;
	std.log.info("{*}", .{&arr});
	
	var ptr = @ptrCast(*align(8) Vec, &arr[1]);
	std.log.info("{*}", .{ptr});
	std.log.info("{}", .{ptr.*});
	ptr.* = Vec{0, 0, 0, 0};
	std.log.info("{}", .{ptr.*});
}
```

output:
```
info: 32 32
info: [6]f64@7ffc0953eac0
info: @Vector(4, f64)@7ffc0953eac8      ←←←←← Note that the last digit needs to be 8 for this to work
info: { -3.7206620809969885e-103, -3.7206620809969885e-103, -3.7206620809969885e-103, -3.7206620809969885e-103 }  ←←←←← Note that reading the align(8) pointer works fine
Segmentation fault at address 0x0
/home/mint/Desktop/test2.zig:12:2: 0x22093b in main (test2)
 ptr.* = Vec{0, 0, 0, 0};
 ^
/home/mint/zig/stage3/lib/zig/std/start.zig:606:22: 0x21fd70 in posixCallMainAndExit (test2)
            root.main();
                     ^
/home/mint/zig/stage3/lib/zig/std/start.zig:376:5: 0x21f821 in _start (test2)
    @call(.never_inline, posixCallMainAndExit, .{});
    ^
Aborted (core dumped)
```

### Expected Behavior

Either it should work fine, like reading does,
or if this is not allowed then it should cause a compiler error.

**Comment by AssortedFantasy** [comment]
This probably can be related to the choice of instructions being emitted. Maybe create a Godbolt to add details and perhaps this could be fixed.

See: https://stackoverflow.com/questions/31089502/aligned-and-unaligned-memory-access-with-avx-avx2-intrinsics

It's also a possible avenue to consider choosing to purposefully emit the instructions demanding strict alignment when using naturally aligned vectors because it could intentionally crash when pointers are corrupted as a safety measure.

**Comment by IntegratedQuantum** [comment]
> This probably can be related to the choice of instructions being emitted. Maybe create a Godbolt to add details and perhaps this could be fixed.

You are right. It seems that zig outputs the aligned version `vmovapd` for writes instead of `vmovupd`:
https://godbolt.org/z/rxbT6f18Y

**Comment by IntegratedQuantum** [comment]
This appears to work now. I just tested it with version 0.12.0-dev.596+2adb932ad and double checked godbolt, where it is outputting `vmovupd` correctly now.
