### ISSUE TITLE
Autodoc: Search Not Working

### ISSUE THREAD

**Issue by jcalabro** [ziglang/zig#14526]
Hi! I was attempting to search through the stdlib documentation this morning and ran in to an issue where the `S` search box returns no results, regardless of what you type in. I'm not seeing any errors in the js console.

For instance: https://ziglang.org/documentation/master/std/#A;std?Array

![image](https://user-images.githubusercontent.com/8205547/216612746-188fc3e1-4ff6-4fe2-b4bf-0f86e5ad76ba.png)

Thanks!

**Comment by andrewrk** [comment]
likely fixed by 4c7f8286d53bf3df22b1a4596cfdd38d3736240e. It will take ~6-12 hours for the website to pick up this change.

**Comment by jcalabro** [comment]
Looks great now, thank you!

https://ziglang.org/documentation/master/std/#A;std?dwarf

![image](https://user-images.githubusercontent.com/8205547/216770779-6be757bb-6a59-4027-a760-a6ddc3aca1ab.png)
