### ISSUE TITLE
langref: improve @qualCast documentation

### ISSUE THREAD

**Issue by perillo** [ziglang/zig#14546]
The current documentation says:
"remove const or volatile qualifier from a pointer."

I think it may be confusing, since it also works on slices:
```zig
const std = @import("std");
const debug = std.debug;

pub fn main() void {
    var array = [_]u8{ 'h', 'e', 'l', 'l', 'o' };
    var start: usize = 0;
    var slice: []u8 = array[start..];

    var cslice: []const u8 = slice;
    var mslice = @qualCast([]u8, cslice);

    mslice[0] = 'H';
    debug.print("cslice: {s}\n", .{cslice});
}
```
```
cslice: Hello
```

**Comment by alichraghi** [comment]
an slice is a pointer with `len` field

**Comment by xdBronch** [comment]
i agree with ali in the sense that slices are pointers and youre probably expected to know that the docs imply slices as well but regardless, this issue should be either closed or renamed as `@qualCast` has been split into `@constCast` and `@volatileCast`
