### ISSUE TITLE
complete the implementation of std.mutex on all platforms

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#1455]
As threads can be suspended at any time (even kernel threads!), we need not just spinlocks, but blocking locks implemented with futexes and their equivalent. This is necessary to fix #1363

https://www.kernel.org/doc/Documentation/robust-futexes.txt
http://man7.org/linux/man-pages/man2/futex.2.html
http://man7.org/linux/man-pages/man7/futex.7.html
https://www.akkadia.org/drepper/futex.pdf

**Comment by kristate** [comment]
@andrewrk already uses futexes where available -- I'm confused with this post.

**Comment by shawnl** [comment]
Lock must be the same struct on all architectures so they can be shared between heterogeneous processes. Use-case: https://keithp.com/blogs/Shared_Memory_Fences/

**Comment by kristate** [comment]
WebKit guys have their [ParkingLot](https://webkit.org/blog/6161/locking-in-webkit/) implementation.

**Comment by shawnl** [comment]
ParkingLot appears to not handle out-of-memory.... https://github.com/WebKit/webkit/blob/master/Source/WTF/wtf/ParkingLot.cpp#L378

**Comment by shawnl** [comment]
I think this depends on #924

**Comment by shawnl** [comment]
I am wondering how much spin-lock contention a concurrent red-black tree has (which i tried to work on before, and once tried to work out all the race conditions), because that would eliminate the out-of-memory issue in ParkingLot as the the rb-node could be stored on the stack. I e-mailed the author of this paper asking for a reference implementation but got no response: https://www.cs.umanitoba.ca/~hacamero/Research/RBTreesKim.pdf there has since been this paper: https://www.sciencedirect.com/science/article/pii/S0743731512002912 (which i don't have access to) and this one based on transnational memory: http://transact2015.cse.lehigh.edu/siakavaras-transact-2015.pdf

**Comment by andrewrk** [comment]
I believe this is done now, thanks to @kprotty's work. If not, please open separate issues for each OS that is not supported.
