### ISSUE TITLE
zig build fails with 'error: AccessDenied' on macOS (M1 aarch64) when source is located on mounted smbfs share

### ISSUE THREAD

**Issue by terminar** [ziglang/zig#14570]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

- mount an smbfs share as user on macOS (//user@[ip]/[share] on /System/Volumes/Data/mnt/[share] (smbfs, nodev, nosuid, automounted, nobrowse, mounted by [user])
- put some zig source in a folder on that share
- call "zig build", after something happens (zig-cache with h,o,tmp,z folders and some content in it) zig throws 'error: AccessDenied'
- calling 'zig build' again (with existing zig-cache folder) throws 'error: AccessDenied' again immediately

Temp fix:
- create a symlink 'zig-cache' to a folder on the local storage so it's not on the smbfs share

### Expected Behavior

No 'error: AccessDenied' on remote / mounted (smbfs) filesystems or at least, a better more verbose error message to describe, what the problem may be.

**Comment by mikdusan** [comment]
@terminar,

Is the server for mount a macos host?

**Comment by terminar** [comment]
@mikdusan no, FreeBSD with Samba.

But: Problem seems to be solved with 0.11.0 - I can't reproduce it anymore, seems to run much better.
