### ISSUE TITLE
ability to declare package development dependencies

### ISSUE THREAD

**Issue by dweiller** [ziglang/zig#14591]
This is a competing proposal to #14597.

Currently in a `build.zig.zon` file you can declare dependencies for a project, which will be fetched transitively by dependees. Various projects might have dependencies that are only required by developers of the project itself and not for any exported artifacts (modules, executables, libraries, ...); an example could be benchmarking or testing tools. In this case dependees of the package have no need to fetch these development dependencies and they should be declare separately or have an extra flag indicating this.

For example `build.zig.zon` file of a package could look like:
```
.{
    .name = "optimised-package",
    .version = "1.0.0",

    .dependencies = .{
        .some_pkg = .{
            .url = "https://some.forge/some_pkg.tar.gz",
            .hash = "asdfasdf0",
        },
    },
    .dev_dependencies = .{
        .benchmarking = .{
            .url = "https://some.forge/benchmarking.tar.gz",
            .hash = "asdfasdf1",
        },
        .fuzz_tools = .{
            .url = "https://some.forge/fuzz_tools.tar.gz",
            .hash = "asdfasdf2",
    },
}
```
Alternately, this could be expressed as:
```
.{
    .name = "optimised-package",
    .version = "1.0.0",

    .dependencies = .{
        .some_pkg = .{
            .url = "https://some.forge/some_pkg.tar.gz",
            .hash = "asdfasdf0",
        },
        .benchmarking = .{
            .url = "https://some.forge/benchmarking.tar.gz",
            .hash = "asdfasdf1",
            .devel_only = true,
        },
        .fuzz_tools = .{
            .url = "https://some.forge/fuzz_tools.tar.gz",
            .hash = "asdfasdf2",
            .devel_only = true,
    },
}
```

Then these development dependencies can be skipped by the build runner of a dependee.

**Comment by star-tek-mb** [comment]
If it's all about download size, we could lazily fetch packages, if they are used. But i'm not sure..

```zig
const some_dep = b.dependency("foobar", .{}); // not fetched yet
some_dep.artifact("lib"); // fetched
some_dep.module("mod"); // also fetched
```

As far as I know, golang (go mod) doesn't have dev dependencies support.

**Comment by TUSF** [comment]
Lazily fetching packages would also be useful in cases where you only use a package for certain OS targets, or with certain build flags.

**Comment by andrewrk** [comment]
I opened a competing proposal:  #14597

**Comment by dweiller** [comment]
I think I agree that lazy fetching would be a good way to handle things - it would require less work on the part of package developers and dependees.

**Comment by praschke** [comment]
i think hardcoding two modes is overly limiting and inflexible.

**Comment by dweiller** [comment]
> "it won't preclude using arbitrary logic" means that you have to read build.zig anyway.

Nothing can every get around this - the build runner runs an arbitrary function. The goal of the original idea (lazy fetching which I think is probably nice way to handle this) is to simplify this process and remove complexity from dependees that don't need various optional/development dependencies.

**Comment by andrewrk** [comment]
Closing in favor of #14597
