### ISSUE TITLE
build.zig.zon: module hash mismatch error is different on Windows

### ISSUE THREAD

**Issue by Namek** [ziglang/zig#14602]
### Zig Version

0.11.0-dev.1580+a5b34a61a

### Steps to Reproduce and Observed Behavior

The test project [gettytestmodule.zip](https://github.com/ziglang/zig/files/10691521/gettytestmodule.zip) that was made with `zig init-exe` and not modified besides adding the `build.zig.zon` file behaves differently on 2 platforms:
1. on Windows x64, I think it calculates hashes wrong. However, when those are fixed then the `error: FileNotFound` output appears
2. on MacOS M1, the app just works when hashes are valid 

note: the zip project has "valid" hashes per Windows, not per Mac, I assume those are just invalid. 

The correct `build.zig.zon` should be:
```zig
.{
    .name = "app",
    .version = "1.0.0",
    .dependencies = .{
        .getty = .{
            .url = "https://github.com/getty-zig/getty/archive/f466b702f52895903248733ac0a304cc49d861f9.tar.gz",
            .hash = "1220f5207fb5410440310ead91178a430ea72293d4131ab0f990d75277723708d0ed",
        },
        .json = .{
           .url = "https://github.com/getty-zig/json/archive/78fbee0b35d9b0bec7070e571cbe5e26bfbd1cce.tar.gz",
           .hash = "1220de8cd947effd84308509e4896639f5fe248a8a497761d0af3c45f04d94764b2a",
        },
    },
}
```

#### 1. STR: On Windows

1. Unpack the project
2. `zig build run`
Observe the output: `error: FileNotFound` despite the wrong module hashes.

3. remove the file `build.zig.zon` and run again `zig build run`
Observe the issue is gone. Project runs fine.

The module hashes in the  `build.zig.zon` file are actually wrong. If those are replaced with correct ones (calculated using MacOS M1) then observe the error about the hash mismatch:

```
w:\dev\gettytestmodule\build.zig.zon:7:21: error: hash mismatch: expected: 1220f5207fb5410440310ead91178a430ea72293d4131ab0f990d75277723708d0ed, found: 1220748c2f35c4e2f213afacec95fa554082e891e356e995b5faf40eebca8dc4b82b
            .hash = "1220f5207fb5410440310ead91178a430ea72293d4131ab0f990d75277723708d0ed",
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

#### 2. STR: On MacOS M1

Running the project as is will result in the `error: hash mismatch` which is expected.
The module hashes in the  `build.zig.zon` file are wrong, so replace them with the correct ones. This will enable to run the project on MacOS.

### Expected Behavior

On Windows, the project build should:
1. not result in calculating wrong hashes on hash mismatch error
2. correctly build and run instead of resulting in `error: FileNotFound` when there is no hash mismatch error anymore

**Comment by veloscillator** [comment]
Looks like the issue is with https://github.com/ziglang/zig/blob/d3c9bfada64230ad17badb739f15a492b4c2c065/src/Package.zig#L630 On linux, `path` is something like `.github/ISSUE_TEMPLATE/bugs.yml`. On windows, `.github\ISSUE_TEMPLATE\bugs.yml`. Note the slashes.
### Proposed Solution
Add `fn normalizePath(path: []u8) void`. This can go in various places and do various things. Simplest is adding to `Package.zig` and just having it flip slashes. I guess that requires an alloc... Let me know if there are better ideas. I can implement this if y'all are cool with it.

Note: there's a fun new error on linux `0.11.0-dev.1783+436e99d13`
```
/home/ken/.cache/zig/p/1220f5207fb5410440310ead91178a430ea72293d4131ab0f990d75277723708d0ed/build.zig:1:1: error: file exists in multiple modules
/home/ken/.cache/zig/p/1220f5207fb5410440310ead91178a430ea72293d4131ab0f990d75277723708d0ed/build.zig:1:1: note: root of module root.@dependencies.json.getty
/home/ken/.cache/zig/p/1220f5207fb5410440310ead91178a430ea72293d4131ab0f990d75277723708d0ed/build.zig:1:1: note: root of module root.@dependencies.getty
```
