### ISSUE TITLE
error while make install

### ISSUE THREAD

**Issue by Overcraft90** [ziglang/zig#14604]
### Zig Version

0.11.0-dev.1584+9ccd8ed0a

### Steps to Reproduce and Observed Behavior

1. clone the repository
2. move to the folder and make the build directory
3.  `cmake ..`
4. make install (ERROR message at 95%)

### Expected Behavior

I would expect the process to run to completion and generate the installation files at the default directory for executable. Specifically, this is what I'm prompted with (see [error.log](https://github.com/ziglang/zig/files/10693788/error.log) for a complete description of the issue):

> [ 95%] Linking CXX executable zig2
.
.
.
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/zig2.dir/build.make:975: zig2] Error 1
> make[1]: *** [CMakeFiles/Makefile2:170: CMakeFiles/zig2.dir/all] Error 2
> make: *** [Makefile:136: all] Error 2

Sorry for the long block of text but I cannot easily interpret what's going on...

**Comment by ifreund** [comment]
where did you obtain the LLVM version you are linking against from? At a glance the issue seems to be there.

**Comment by Overcraft90** [comment]
Thanks @ifreund. I see, I got my LLVM from [here](https://apt.llvm.org/) and my LLD from [here](https://lld.llvm.org/), respectively. Let me know whether this help.

I had to do so because simply installing things from the LLVM website was giving me an error related to LLD, which was fixed when I installed the LLD as per the link I reported above.

**Comment by nektro** [comment]
how much ram is installed in your system?

**Comment by Overcraft90** [comment]
Hi @nektro I have 128GB, still I'm not sure how this can help. Please let me know. I'll be happy to run some test if needed.

**Comment by ifreund** [comment]
> Thanks @ifreund. I see, I got my LLVM from [here](https://apt.llvm.org/) and my LLD from [here](https://lld.llvm.org/), respectively. Let me know whether this help.
> 
> I had to do so because simply installing things from the LLVM website was giving me an error related to LLD, which was fixed when I installed the LLD as per the link I reported above.

Are you sure that you have matching versions of LLVM and LLD installed? Both should be version 16.

**Comment by BratishkaErik** [comment]
> Are you sure that you have matching versions of LLVM and LLD installed? Both should be version 16.

Shouldn't it be 15 version if using master branch?

**Comment by ifreund** [comment]
> Shouldn't it be 15 version if using master branch?

Indeed, whoops.

**Comment by Overcraft90** [comment]
@BratishkaErik & @ifreund  Thanks to both, I successfully installed LLVM version 15 (I can see it in `/usr/bin`); however, I'm not sure how to check the version for LLD... pretty sure to have version 15 though.

However, I get the exact same error when running the `make install` for `zig`. How can I specify the directory where LLVM 15 is installed, but most importantly to which one I have to point with the following `cmake` option
> CMAKE_PREFIX_PATH

as there are many folders with different extensions named LLVM 15.

Thanks in advance, if helpful I can attach a screenshot or tree command.
