### ISSUE TITLE
ld.lld: undefined symbol when taking pointer to extern function referenced through alias

### ISSUE THREAD

**Issue by ianprime0509** [ziglang/zig#14610]
### Zig Version

0.11.0-dev.1429+220020599

### Steps to Reproduce and Observed Behavior

For context, I'm working on creating Zig bindings to a library (GTK) and want to provide more idiomatic names for functions (e.g. `g_application_run` -> `gio.Application.run`). I ran into the following issue when trying what I figured was the simplest way to do this:

1. Put the following code in `lib.zig`:

```zig
const std = @import("std");

export fn printNumber(i: i32) void {
    std.debug.print("{}\n", .{i});
}
```

2. Build `lib.zig` as a library: `zig build-lib lib.zig`

3. Put the following code in `example.zig`:

```zig
pub fn main() void {
    const func = &printNumberAlias;
    func(123);
}

extern fn printNumber(i: i32) callconv(.C) void;

const printNumberAlias = printNumber;
```

4. Run `zig run example.zig liblib.a`

Output:
```
error: ld.lld: undefined symbol: example.printNumberAlias
    note: referenced by example.zig:2
    note:               /home/ian/.cache/zig/o/0d7abe13693542de4364c6a7511d2720/example.o:(example.main)
    note: referenced by example.zig:3
    note:               /home/ian/.cache/zig/o/0d7abe13693542de4364c6a7511d2720/example.o:(example.main)
```

### Expected Behavior

The number `123` should be printed.

The example works as expected if `&printNumberAlias` is replaced with `&printNumber`. It also works as expected if the definition of `printNumber` is moved into `example.zig`, as in the following:

```zig
const std = @import("std");

pub fn main() void {
    const func = &printNumberAlias;
    func(123);
}

fn printNumber(i: i32) void {
    std.debug.print("{}\n", .{i});
}

const printNumberAlias = printNumber;
```

**Comment by rohlem** [comment]
Haven't tested it, but I would expect that the calling convention on `printNumber` should always be specified, making the declaration in `lib.zig`:
```zig
export fn printNumber(i: i32) callconv(.C) void {
    std.debug.print("{}\n", .{i});
}
```

Not sure whether this fixes it, if yes better error reporting would be nice, if not then that is potentially a separate bug.

**Comment by ianprime0509** [comment]
According to the [language documentation on `export`](https://ziglang.org/documentation/0.10.1/#Functions), it's supposed to use the C calling convention by default, so that's why I didn't initially specify it on the export of `printNumber`. (In the project I'm working on that motivated this simplified example, I'm actually using an external C library; I just made `lib.zig` for this example to simulate a very simple library I can link against)

For what it's worth, adding `callconv(.C)` to the export, as you suggested, doesn't change the behavior: using the function pointer `&printNumberAlias` in `example.zig` still results in an "undefined symbol" linker error, and using the function pointer `&printNumber` still works correctly (links properly and prints the expected output).

I haven't been able to reproduce this except when using `extern fn` declarations (for example, even if I take my working single-file example and split `printNumber` off into a separate `other.zig` file which I then `@import` from `example.zig`).

**Comment by rohlem** [comment]
> According to the [language documentation on export](https://ziglang.org/documentation/0.10.1/#Functions), it's supposed to use the C calling convention by default

Ah, I was unaware of that. In that case I fully agree with your conclusions.
And it looks like resident bug hunter Vexu is already on the case, so the fix will probably be on master within a week. Thanks to both of you! :)
