### ISSUE TITLE
allow chained multi-pointer slicing to omit end value when last one does not

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#14611]
### Zig Version

0.11.0-dev.1584+9ccd8ed0a

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

test {
    const a = [_]u8{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
    const b = &a;
    const c: [*]const u8 = b;
    foo(c[2..][0..3]);
}

fn foo(x: []const u8) !void {
    try std.testing.expectEqualSlices(u8, &.{ 2, 3, 4 }, x);
}
```

```
test.zig:7:10: error: slice of pointer must include end value
    foo(c[2..][0..3]);
        ~^~~~~
```

### Expected Behavior

all tests passed

**Comment by mlugg** [comment]
If you want this why not just do `(c + 2)[0..3]`? It more accurately describes your intent anyway - `c[2..]` can't in any meaningful way be a slice, so it's pretty weird for it to be a slicing operation

**Comment by ifreund** [comment]
This is not a bug, but rather a language proposal.

https://github.com/ziglang/zig/wiki/Language-Proposals

**Comment by nektro** [comment]
> If you want this why not just do `(c + 2)[0..3]`?

thanks for the insight on this workaround! i do believe that if this was to be implemented it would make the intent more clear and imo "feel" safer, but thats generally based on a slight aversion to pointer math so i plenty accept if that ends up being a mark towards a denial

**Comment by ifreund** [comment]
> thanks for the insight on this workaround! i do believe that if this was to be implemented it would make the intent more clear and imo "feel" safer, but thats generally based on a slight aversion to pointer math so i plenty accept if that ends up being a mark towards a denial

The only real difference between slicing and pointer math currently is that slicing is bounds checked. I think adding sugar for writing pointer math as a slicing expression would blur this difference and be inconsistent.

**Comment by nektro** [comment]
> The only real difference between slicing and pointer math currently is that slicing is bounds checked.

this is also the case when performed on multi-item pointers, rather than pointers that are already slices?

**Comment by nektro** [comment]
feels "safer" might not be the right word to describe that I feel like pointer arithmetic (since they only support addition and subtraction) is moreso an artifact of a feature from before slicing syntax existed. and now that we have the latter it feels like this proposal fills in a missing gap that would (in conjunction with syntax that supported negative slice indexes on multi-pointers) render pointer arithmetic obsolete

**Comment by InKryption** [comment]
Would this essentially just boil down to making `x[a..]` equivalent to `x + a`?

**Comment by rohlem** [comment]
I don't think I've seen addition used for slice-offsetting (with proper length reduction) before.
`x[a..][..b]` looks more heterogenous and "nicer" to me than `(x + a)[..b]`, in part because of the required parentheses.
Now that I know about it, both options make sense in their own regard.

However, there is a difference in behavior, and opportunity for safety checks, with arrays and sentinel-terminated pointers.
Examples (where I took the liberty of allowing `x[a..]` as its own expression, which goes against the original proposal, but some cases apply either way):

```zig
const source: [50:0]u8 = getText();
const a = source[2..6]; //of type *const [4]u8
var b: []u8 = a;
const intermediate = @as([*:0]u8, source);

const new_syntax_c: [*:0]u8 = intermediate[2..]; //I believe the new syntax should check for the sentinel 0 in source[0..1] be illegal behavior if encountered.
const c: [*:0]u8 = intermediate + 2; //I'm actually not sure whether we do, or should, check for the sentinel with this syntax - imo writer's intent seems not to.

// addition syntax for offsetting:
std.debug.log("{s}", b + 1); //prints source[3..6]
std.debug.log("{s}", a + 1); //saved by type system: cannot offset pointer-to-single
std.debug.log("{s}", c + 1); //expression allowed, again not sure what it does though

// new syntax for offsetting:
std.debug.log("{s}", b[1..]); //prints source[3..6]
std.debug.log("{s}", a[1..]); //prints source[3..6]
std.debug.log("{s}", c[1..]); //checks for sentinel at c[0], then prints source[3..] until sentinel
```

**Comment by N00byEdge** [comment]
@InKryption :
> Would this essentially just boil down to making `x[a..]` equivalent to `x + a`?

I think so, and I genuinely think this is a good idea.

**Comment by xdBronch** [comment]
i believe this should be closed, no? #15519 implemented this behavior and the test nektro gave now passes

**Comment by rohlem** [comment]
Confirming - it seems this idea was incidentally re-invented in https://github.com/ziglang/zig/pull/15519#issuecomment-1532352304 and accepted in https://github.com/ziglang/zig/pull/15519#issuecomment-1532401475 .
The given test code works (once a missing `try` is inserted on calling `foo`) for me on Zig version `0.11.0-dev.3910+689f3163a`.

For reference (regarding my open question above),
the current behavior ignores sentinels in sentinel-terminated multi-pointers the same as operator `+` does for offsetting.
E.g. when changing `c` to `const c: [*:0]const u8 = @ptrCast(b);`,
the 0 at index 0 is simply skipped / ignored.
(IMO that point is still worth reconsidering, but it seems I'm alone on this.)

**Comment by nektro** [comment]
test coverage added here https://github.com/ziglang/zig/blob/fc48bbd/test/behavior/slice.zig#L185-L194
implemented and tested in https://github.com/ziglang/zig/pull/15519
