### ISSUE TITLE
C macro value needs to be escaped in `LibExeObjStep.defineCMacro`

### ISSUE THREAD

**Issue by terrablue** [ziglang/zig#14625]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

I'm building my C project with `zig build`.

When using `LibExeObjStep.defineCMacro` to define a macro to be passed to the preprocessor, the value (second parameter) needs to be escaped, otherwise clang doesn't see it.

If I use 

`s4.defineCMacro("CONFIG_VERSION", "2021-03-27");` (where `s4` is a `LibExeObjStep`)

Clang doesn't see the macro. I need to use

`s4.defineCMacro("CONFIG_VERSION", "\"2021-03-27\"");`

instead.

### Expected Behavior

Be able to use a value with `LibExeObjStep.defineCMacro` without escaping it.

Note: in Zig master, `LibExeObjStep` has been renamed to `CompileStep`.

**Comment by nektro** [comment]
not a bug imo

**Comment by mlugg** [comment]
C macros are direct text substitutions, so the existing semantics make sense. As an example use case, you want to be able to define macros as integer literals (e.g. `defineCMacro("VERSION_MAJOR", "1")`), but it also needs to be possible for that to be a string (`defineCMacro("VERSION_MAJOR_STRING", "\"1\"")`), so there's not really a good/consistent way this can work differently.

**Comment by terrablue** [comment]
Thanks for the explanation!
