### ISSUE TITLE
limits on absolute and relative paths include with @embedFile

### ISSUE THREAD

**Issue by thomas-mangin** [ziglang/zig#14637]
### Zig Version

0.11.0-dev.1606+3c2a43fdc

### Steps to Reproduce and Observed Behavior

While my exact setup is different, a way to reproduce the issue is already documented on https://github.com/ziglang/zig/issues/14088 

However, this issue is mostly to seek clarification on the current import / embedFile director restriction and present the issue it can present to zig programmers.

### Expected Behavior

The zig compiler places file location limitations when calling `@embedFile`.

I would like to include data with `@embdedFile`, which is located outside the source root folder, and I can not see a way to perform this task (but perhaps by cheating and creating a fake dependency on another package - but I also failed to do this).

Looking at past issues, I found two recent ones discussing the same problem.

On https://github.com/ziglang/zig/issues/14551 - @Vexu suggest that the solution should be to improve the error message (implying that the behaviour is by design), which would help but would still limit what a developer can do.

On https://github.com/ziglang/zig/issues/14088 - @andrewrk link to another issue, but it does not address including zig code from outside the repository.

This was also discussed on https://github.com/ziglang/zig/issues/10939

Zig's own use of `@embedFile` only accesses content from the local folders, where the `testdata` folders are located. It, therefore, does not attempt any relative include from the project's root or parent folders.

Considering a `build.zig` file containing the default `route_source_file`:
```
    const exe = b.addExecutable(.{
        .root_source_file = .{ .path = "src/main.zig" },
    });
```

Placed within this folder structure created by extending a `zig init-exe`:
```
.
├── build.zig
├── data1
│   └── include1.file
└── src
    ├── cmd
    │   ├── standalone1.zig
    │   └── standalone2.zig
    ├── data2
    │   └── include2.file
    ├── main.zig
    └── internallib
        └── useembed.zig
```

It is currently possible to include `data2/` files from `internallib/useembed.zig` with `@embedFile("../data/include2.file");`.

But it is impossible to access files from `data1`. Attempting to do so does result in zig reporting `error: embed of file outside package path`.

Running `zig build src/cmd/standalone1.zig` also sets the root folder in the `src/cmd` folder (by design), preventing any chance of importing any data not located in `cmd`.

Adding data to a binary to prevent the need to access the filesystem is very useful for immutable infrastructure or wasm binaries. This data is only "loosely" related to the code.

As my background is in C, Python and Go, I can not help a comparison with Go which does provide features to ship a virtual FS linked to an arbitrary data folder (https://lwn.net/Articles/827215/) which is very useful and my first thought on looking at `@embedFile` is that it could be used to replicate the feature.

Limiting the import of files to the project file structure makes sense and provides security benefits. I accept the implicit argument that embedded data can be seen as intrinsic to the code.

A new, optional root value for the project's root may be worth considering in `addExecutable`, keeping it as the folder of the `main.zig` file if it is unspecified.

It may also make sense to consider the dissociation of the project's root (for `@embedFile`) and the root of the code (for `@import`) and not link this source root to the location of the `main.zig` file, but the extra complexity may be an argument against it.

Also, my understanding is that `root_source_file` set the `root` of the import and that any attempt to include files outside this scope is not allowed, but I am unclear on why using `root` does not seem to work with `@embedFile`, like `@embedFile("root/data2/include2.file");` in my case.

**Comment by Vexu** [comment]
Did you look at #14553?

**Comment by thomas-mangin** [comment]
Hello @Vexu - thank you for taking time to answer, it is much appreciated.

Yes, I did. As https://github.com/ziglang/zig/issues/14088 had the same answer from @andrewrk. As the issue is still open, it may well be that the author of that issue and myself are both perplexed with the example provided and could not see how it related to our respective questions.

`bootloader` references a zig file which AFAIU will be compiled. I would like to include some text to be treated comptime and converted into zig structures. So this does not seems to be what I need.

```
    const bootloader = b.addExecutable(.{
        .name = "bootloader",
        .root_source_file = .{ .path = "bootloader.zig" },
        .target = .{
            .cpu_arch = .x86,
            .os_tag = .freestanding,
        },
        .optimize = .ReleaseSmall,
    });
```

I wish to access a folder and this seems to be to add a single file.
```
    exe.addAnonymousModule("bootloader.elf", .{
        .source_file = bootloader.getOutputSource(),
    });
    exe.install();
}
```

Was it that it is possible to use `exe.addAnonymousModule` to extend the scope of the compiler search path with an external folder?

If you think is possible to achieve, I would happily document the outcome of the work here with a example in view to help with the documentation.

**Comment by thomas-mangin** [comment]
with a file `data/include.me` in the root of the project, the following works:

```
    const data = std.build.FileSource.relative("data/include.me");
    exe.addAnonymousModule("include.me", .{
        .source_file = data,
    });
```

```
const std = @import("std");

pub fn main() !void {
    const data = @embedFile("include.me");
    std.debug.print("{s}\n", .{data});
}
```

**Comment by thomas-mangin** [comment]
Improved version (considering my lack of zig experience).

```zig
    addFiles(b, exe, "data") catch |err| {
        std.debug.panic("{any}", .{err});
    };
```

```zig
fn addFiles(b: *std.Build, exe: *std.Build.CompileStep, folder: []const u8) !void {
    var buffer = [_]u8{0} ** 1000;

    var dir = try std.fs.cwd().openIterableDir(folder, .{});
    var it = dir.iterate();

    while (try it.next()) |file| {
        const name = b.dupe(try std.fmt.bufPrint(&buffer, "{s}/{s}", .{ folder, file.name }));
        std.debug.print("adding for embeding {s}\n", .{name});
        switch (file.kind) {
            .File => {
                exe.addAnonymousModule(name, .{
                    .source_file = std.build.FileSource.relative(name),
                });
            },
            .Directory => {
                try addFiles(b, exe, name);
            },
            else => {},
        }
    }
}
```

**Comment by thomas-mangin** [comment]
How to pass the list of files to the main program, where at comptime the content could be placed into a ComptimeStringMap.

```zig
    addFilesWithOptions(b, exe, "data") catch |err| {
        std.debug.panic("{any}", .{err});
    };
```
```zig
var files = std.ArrayList([]const u8).init(std.heap.page_allocator);

fn addFilesWithOptions(b: *std.Build, exe: *std.Build.CompileStep, folder: []const u8) !void {
    try addFiles(b, exe, folder);

    var file = b.addOptions();
    file.addOption([]const []const u8, "names", files.items);
    exe.addOptions("embeded_file", file);
}

fn addFiles(b: *std.Build, exe: *std.Build.CompileStep, folder: []const u8) !void {
    var dir = try std.fs.cwd().openIterableDir(folder, .{});
    var it = dir.iterate();

    while (try it.next()) |file| {
        const name = try std.fmt.allocPrint(b.allocator, "{s}/{s}", .{ folder, file.name });
        std.debug.print("adding for embeding {s}\n", .{name});

        switch (file.kind) {
            .File => {
                try files.append(name);
                exe.addAnonymousModule(name, .{
                    .source_file = std.build.FileSource.relative(name),
                });
            },
            .Directory => {
                try addFiles(b, exe, name);
            },
            else => {},
        }
    }
}
```
```zig
const std = @import("std");
const file = @import("embeded_file");

pub fn main() !void {
    inline for (file.names) |name| {
        std.debug.print("file {s}\n---\n{s}\n---\n", .{ name, @embedFile(name) });
    }
}
```

**Comment by thomas-mangin** [comment]
and how to store it a comptime.
```zig
const std = @import("std");
const file = @import("embeded_file");

const file_map = std.ComptimeStringMap([]const u8, build_files: {
    var array: [file.names.len]struct {
        []const u8,
        []const u8,
    } = undefined;

    inline for (file.names) |name, i| {
        array[i] = .{ name, @embedFile(name) };
    }
    break :build_files array[0..];
});

pub fn main() !void {
    const name = "data/include.you";
    if (file_map.has(name)) {
        std.debug.print("{s}: {any}\n", .{name, file_map.get(name)});
    }
}
```

**Comment by thomas-mangin** [comment]
I would appreciate to be told if there is another better approach, otherwise I would be happy to close this issue.

**Comment by thomas-mangin** [comment]
A suggestion on discord suggested changing the root with `exe.setMainPkgPath(“.”)`

**Comment by Anton-4** [comment]
For future readers; `setMainPkgPath` no longer exists, in zig 14 you should add `exe.root_module.addAnonymousImport("license", .{.root_source_file = b.path("LICENSE")});` to your build.zig, then you can use `@embedFile("license");` in your code.
