### ISSUE TITLE
translate-c fails on macro with `assert(1 && "error message")`

### ISSUE THREAD

**Issue by travisstaloch** [ziglang/zig#14642]
### Zig Version

0.11.0-dev.1577+11cc1c16f

### Steps to Reproduce and Observed Behavior

Sorry if this is a duplicate issue. Seems like it might be.  I didn't find anything in a quick search. 

It is common in c to provide an error message like this:
```c
// /tmp/tmp.h
#include <assert.h>

#define FOO assert(1 && "error message")
```
a minimal `@cImport` in zig:
```zig
// /tmp/tmp.zig
const c = @cImport(@cInclude("tmp.h"));

test {
    _ = c;
}
```
Yields this error:
```console
$ zig test -lc /tmp/tmp.zig -I/tmp
/home/travis/.cache/zig/o/581a6a5a6944f09e8260e88f89c213da/cimport.zig:616:66: error: cannot compare strings with !=
pub const FOO = assert((@as(c_int, 1) != 0) and ("error message" != 0));
                                                 ~~~~~~~~~~~~~~~~^~~~
/tmp/tmp.zig:1:11: error: C import failed: AnalysisFail
const c = @cImport(@cInclude("tmp.h"));
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    test_0: /tmp/tmp.zig:4:9
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

### Expected Behavior

not sure what should happen. this _IS_ a hacky way to show error messages. i'm only reporting it because its common in c.

**Comment by rohlem** [comment]
> not sure what should happen.

IIUC pointers in boolean expressions in C are checked against 0 (= the null pointer constant).
I believe if the emitted Zig code was similarly `!= null` instead of `!= 0`, that would solve the issue.

**Comment by travisstaloch** [comment]
> I believe if the emitted Zig code was similarly `!= null` instead of `!= 0` for pointers (which string literals yield), that would solve the issue.

Its not possible to compare a string literal with null.  It would need to be first cast ie `@ptrCast([*c]const u8, "error message)`.  Perhaps another type of pointer would be better, not sure.  

Of course, this assumes that translate-c can detect when a string literal is being compared using an equality operator.  And I don't know that this is true.

**Comment by Vexu** [comment]
Yes, something like this should do it:
```diff
diff --git a/src/translate_c.zig b/src/translate_c.zig
index ab48ee1f5..c77576cb0 100644
--- a/src/translate_c.zig
+++ b/src/translate_c.zig
@@ -5969,6 +5969,9 @@ fn macroIntToBool(c: *Context, node: Node) !Node {
     if (isBoolRes(node)) {
         return node;
     }
+    if (node.tag() == .string_literal) {
+        return Tag.true_literal.init();
+    }
 
     return Tag.not_equal.create(c.arena, .{ .lhs = node, .rhs = Tag.zero_literal.init() });
 }
```

**Comment by VoilaNeighbor** [comment]
When is this going to be merged?

A real world example with cglm:

```c
/*!
 * @brief mupliply N mat4 matrices and store result in dest
 *
 * this function lets you multiply multiple (more than two or more...) matrices
 * <br><br>multiplication will be done in loop, this may reduce instructions
 * size but if <b>len</b> is too small then compiler may unroll whole loop,
 * usage:
 * @code
 * mat m1, m2, m3, m4, res;
 *
 * glm_mat4_mulN((mat4 *[]){&m1, &m2, &m3, &m4}, 4, res);
 * @endcode
 *
 * @warning matrices parameter is pointer array not mat4 array!
 *
 * @param[in]  matrices mat4 * array
 * @param[in]  len      matrices count
 * @param[out] dest     result
 */
CGLM_INLINE
void
glm_mat4_mulN(mat4 * __restrict matrices[], uint32_t len, mat4 dest) {
  uint32_t i;

#ifndef NDEBUG
  assert(len > 1 && "there must be least 2 matrices to go!");
#endif

  glm_mat4_mul(*matrices[0], *matrices[1], dest);

  for (i = 2; i < len; i++)
    glm_mat4_mul(dest, *matrices[i], dest);
}
```

Translated:

```zig
pub inline fn glm_mat4_mulN(arg_matrices: [*c][*c]mat4, arg_len: u32, arg_dest: [*c]vec4) void {
    var matrices = arg_matrices;
    _ = &matrices;
    var len = arg_len;
    _ = &len;
    var dest = arg_dest;
    _ = &dest;
    var i: u32 = undefined;
    _ = &i;
    _ = !!((len > @as(u32, @bitCast(@as(c_int, 1)))) and ("there must be least 2 matrices to go!" != null)) or ((blk: {
        _assert("len > 1 && \"there must be least 2 matrices to go!\"", "C:\\Users\\BaiDongJie\\Custom\\Project\\FIG-dual\\lib\\cglm-v0.9.4/mat4.h", @as(c_uint, @bitCast(@as(c_int, 380))));
        break :blk @as(c_int, 0);
    }) != 0);
    glm_mat4_mul(@as([*c]vec4, @ptrCast(@alignCast(&matrices[@as(c_uint, @intCast(@as(c_int, 0)))].*))), @as([*c]vec4, @ptrCast(@alignCast(&matrices[@as(c_uint, @intCast(@as(c_int, 1)))].*))), dest);
    {
        i = 2;
        while (i < len) : (i +%= 1) {
            glm_mat4_mul(dest, @as([*c]vec4, @ptrCast(@alignCast(&matrices[i].*))), dest);
        }
    }
}
```

**Comment by travisstaloch** [comment]
> Yes, something like this should do it:
> 
> ```diff
> diff --git a/src/translate_c.zig b/src/translate_c.zig
> index ab48ee1f5..c77576cb0 100644
> --- a/src/translate_c.zig
> +++ b/src/translate_c.zig
> @@ -5969,6 +5969,9 @@ fn macroIntToBool(c: *Context, node: Node) !Node {
>      if (isBoolRes(node)) {
>          return node;
>      }
> +    if (node.tag() == .string_literal) {
> +        return Tag.true_literal.init();
> +    }
>  
>      return Tag.not_equal.create(c.arena, .{ .lhs = node, .rhs = Tag.zero_literal.init() });
>  }
> ```

@Vexu I applied your patch and it does indeed work, producing the following
```zig
...
pub const FOO = assert((@as(c_int, 0) != 0) and true);
```
when given
```c
#include <assert.h>

#define FOO assert(0 && "error message")
```

As you can see, "error message" gets lost.  Do you think it would be better to preserve the string literal, maybe translating it as the following instead of `true`?
```zig
@intFromPtr("error message") != 0
```

**Comment by travisstaloch** [comment]
as mentioned by @rohlem above, I noticed that the following produces invalid zig code, comparing a str literal with null

```c
// /tmp/tmp.h
void foo() { if(0 && "error message") {} }
```

```console
$ zig translate-c /tmp/tmp.h
```

result:

```zig
pub export fn foo() void {
    if (false and ("error message" != null)) {}
}
```

Should be supported?  If so, any idea how to fix it?  I searched around in src/translate_c.zig a bit but not sure how this might be done.

**Comment by Vexu** [comment]
Try here: https://github.com/ziglang/zig/blob/f7a76bdfe3bc05034f895913261a743a83ca3c78/src/translate_c.zig#L2088-L2091

**Comment by travisstaloch** [comment]
thanks @Vexu will work on this tomorrow. will make a separate pr unless you think i should just add it #19610.

**Comment by travisstaloch** [comment]
> Try here:
> 
> https://github.com/ziglang/zig/blob/f7a76bdfe3bc05034f895913261a743a83ca3c78/src/translate_c.zig#L2088-L2091

just submitted #19625 with a fix at this location
