### ISSUE TITLE
test: standalone/issue_12588 is not testing anything

### ISSUE THREAD

**Issue by perillo** [ziglang/zig#14643]
The test `standalone/issue_12588` is supposed to check that the generated LLVM ir is valid and that (from #13167),

  - `--verbose-llvm-ir` should trigger analysis and codegen
  - `-femit-asm` etc should trigger codegen even with `-fno-emit-bin`

However, IMHO, the test it not testing anything and, additionally, the generated files are not in `.gitignore`.

**Comment by jacobly0** [comment]
This test (as can be determined by the name) is a regression test for an issue, not a behavior test for a feature.  Running the test without the fix results in a lot of output, including `thread 14604 panic: LLVM module verification failed`, indicating that the LLVM IR is not valid and failing the regression test.

**Comment by perillo** [comment]
> This test (as can be determined by the name) is a regression test for an issue, not a behavior test for a feature. Running the test with a debug compiler and without the fix results in a lot of output, including `panic: LLVM module verification failed`, indicating that the LLVM IR is not valid and failing the regression test.

Thanks for the clarification.  In the original issue, the step reproduce was to run `opt -S -verify file.ll`.

I'll close this issue.

**Comment by jacobly0** [comment]
> In the original issue, the step reproduce was to run `opt -S -verify file.ll`.

Ah, yeah, the debug zig compiler runs the equivalent of `opt -verify` through the LLVM api.
