### ISSUE TITLE
Nested-Container-Tests 

### ISSUE THREAD

**Issue by andrewdylanvianaamorim2** [ziglang/zig#14648]
### Zig Version

0.11.0-dev.1622+fc48467a9

### Steps to Reproduce and Observed Behavior

issue:
   the containerized test shoud run

minimal code to reproduce the issue: 
```zig
const std = @import("std");
test {
    _ = S;
}

const S = struct {
    t: T,
    const T = struct {
        test "should run" {
            try std.testing.expect(true);
        }
    };
};

```

how to test:
zig test test.zig

ouput:
All 1 tests passed.

### Expected Behavior

expected output:
All 2 tests passed.

**Comment by Vexu** [comment]
Working as designed, `T` is not referenced so it is not analyzed.

**Comment by andrewdylanvianaamorim2** [comment]
well it works 0.9.1 but ok

**Comment by nektro** [comment]
creating an instance of `S` runs both tests

```zig
const std = @import("std");
test {
    _ = S{};
}

const S = struct {
    t: T = .{},

    const T = struct {
        test "should run" {
            try std.testing.expect(true);
        }
    };
};
```
