### ISSUE TITLE
remove @maxValue and @minValue 

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1466]
Since they can be implemented easily in userland.

**Comment by bheads** [comment]
What about supporting  <type>.min and <type>.max ?

**Comment by thejoshwolfe** [comment]
I recommend adding userland implementations in the std library. This usecase is common enough that there should be one obvious implementation for you to use.

I agree that builtin functions are unnecessary. keep the language small.

.min and .max is not the right api. That would make it tightly integrated into the language. something more like `@import("srd").math.max(u32)` would be better.

**Comment by kristate** [comment]
hmm, we already have min and max in std.math[0][1]. `std.math.maxValue` sounds good through.

[0] `std.math.min`
```zig
pub fn min(x: var, y: var) @typeOf(x + y) {
    return if (x < y) x else y;
}

test "math.min" {
    assert(min(i32(-1), i32(2)) == -1);
}
```
[1] `std.math.max`
```zig
pub fn max(x: var, y: var) @typeOf(x + y) {
    return if (x > y) x else y;
}

test "math.max" {
    assert(max(i32(-1), i32(2)) == 2);
}
```

**Comment by tgschultz** [comment]
I think it should really be in `TypeInfo` under the hood, which would mean that the `maxValue` and `minValue` functions should be in `meta`.

**Comment by kristate** [comment]
Please add breaking tag.
