### ISSUE TITLE
compiler: taking the address of a captured loop range causes a segmentation fault

### ISSUE THREAD

**Issue by perillo** [ziglang/zig#14679]
### Zig Version

0.11.0-dev.6417+0bb178bbb

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");
const debug = std.debug;

pub fn main() void {
    for (0..10) |i| {
        debug.print("&i: {p}\n", .{&i});
    }
}
```

```sh
$ zig run for-loop.zig
```

```
zsh: segmentation fault (core dumped)  zig run for-loop.zig
```

NOTE: I have built stage3 with:
```
cd build
cmake -DCMAKE_BUILD_TYPE=Release -GNinja -DZIG_NO_LIB=ON ..
ninja
```

### Expected Behavior

If taking the address of a captured loop range is not allowed, the compiler should report an error, otherwise it should not crash.

**Comment by perillo** [comment]
@Vexu, I tried with `0.12.0-dev.2341+92211135` and works correctly:
```zig
&i: usize@7fffee01a4b8
&i: usize@7fffee01a4b8
&i: usize@7fffee01a4b8
&i: usize@7fffee01a4b8
&i: usize@7fffee01a4b8
&i: usize@7fffee01a4b8
&i: usize@7fffee01a4b8
&i: usize@7fffee01a4b8
&i: usize@7fffee01a4b8
&i: usize@7fffee01a4b8
```

I'm not closing it so that you can confirm that the issue has been solved.

Thanks.

**Comment by Vexu** [comment]
Test coverage added in #16537
