### ISSUE TITLE
`[64]u1` occupies 64 bytes instead of 8 bytes

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#14672]
### Zig Version

0.11.0-dev.1393+38eebf3c4

### Steps to Reproduce and Observed Behavior

Test:

```zig
const std = @import("std");
test {
    try std.testing.expectEqual(
        8,
        @sizeOf([64]u1),
    );
    try std.testing.expectEqual(
        64,
        @bitSizeOf([64]u1),
    );
}
```

Output:

```zig
Test [1/1] test_0... expected 64, found 8
Test [1/1] test_0... FAIL (TestExpectedEqual)
/Users/jarred/Desktop/repro.zig:3:5: 0x10018c6e3 in test_0 (test)
    try std.testing.expectEqual(
    ^
```

### Expected Behavior

Expected output:

```
All 1 tests passed.
```

**Comment by luehmann** [comment]
@Jarred-Sumner You can use a [PackedIntArray](https://github.com/ziglang/zig/blob/master/lib/std/packed_int_array.zig) from the str lib to get your expected behavior

**Comment by nektro** [comment]
`@Vector(64, u1)` will take 8 bytes btw
