### ISSUE TITLE
@ptrCast between real pointers and 0-sized pointers should be a compile error

### ISSUE THREAD

**Issue by thejoshwolfe** [ziglang/zig#1469]
This came up in #960.

```zig
test "*usize to *void" {
    var i = usize(0);
    var v = @ptrCast(*void, &i);
    v.* = {};
}
```

This should be a compile error. A `*void` has 0 size (just like `void` itself) so this cast makes no sense.

@Hejsil was there a usecase you were running into in #960 where you wanted to do this cast?

**Comment by Hejsil** [comment]
@thejoshwolfe I think I was implementing some vtable/interface stuff. Was trying to use `*void` as I would use `void *` in C, and hit this. So no, there wasn't really a usecase.

**Comment by tadeokondrak** [comment]
Casting from normal pointers to pointers to zero-length arrays seems to be reasonable code, which happens in std.heap.GeneralPurposeAllocator.

**Comment by SpexGuy** [comment]
In #6706 we've decided to remove 0-sized pointers, so this is no longer relevant.
