### ISSUE TITLE
possible Zstandard decompression improvements

### ISSUE THREAD

**Issue by dweiller** [ziglang/zig#14702]
There are a few things that were explicitly not done in the initial Zstandard decompression PR that may be desired improvements. This issue is to collect them (and others that pop up in between) for future reference in a pre-1.0 stdlib review or to list them incase someone to tackle them earlier.

  - The current implementation does not decode 4-stream literal sections in parallel in order to avoid memory allocations (or remove a need for an additional 128KiB of memory) in the non-allocating API. This presumably sacrifices decompression performance, but benchmarking may be needed to assess what the impact is in practice. This change would require re-working the block decoding in [`lib/std/compress/zstandard/decode/block.zig`](https://github.com/ziglang/zig/blob/master/lib/std/compress/zstandard/decode/block.zig) to eagerly decode literals into an extra internal buffer.
  - Reuse allocations between frames in `std.compress.zstd.decompress.decodeAlloc()` API). The frame window could be re-used between frames (provided it is large enough). The relevant allocation is [here](https://github.com/ziglang/zig/blob/master/lib/std/compress/zstandard/decompress.zig#L473).
  - a few issue we found may result in minor updates to the zstandard spec - https://github.com/facebook/zstd/issues/3508 is the main upstream issue that will hopefully link to any related changes that get made.
    + Check implementation against documentation changes in https://github.com/facebook/zstd/pull/3514

**Comment by andrewrk** [comment]
This is a meta-issue. The next step is to extract from it individual issues and then close this one.

**Comment by dweiller** [comment]
Extracted the list above into separate issues.
