### ISSUE TITLE
COFF linker does not observe linker_allow_shlib_undefined

### ISSUE THREAD

**Issue by hryx** [ziglang/zig#14718]
### Zig Version

0.11.0-dev.1635+d09e39aef

### Steps to Reproduce and Observed Behavior

build.zig for an example shared library "foo" that references symbols from other library "bar":

```zig
const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const foo_lib = b.addSharedLibrary(.{
        .name = "foo",
        .root_source_file = .{ .path = "src/foo.zig" },
        .target = target,
        .optimize = optimize,
    });
    foo_lib.linker_allow_shlib_undefined = true; // <--
    foo_lib.linkLibC();
    foo_lib.install();
}
```

On Windows, there are link errors about the undefined symbols. Linux and macOS succeed.

In the stage2-meeting call we found that the ELF and Mach-O linkers observe this option (passed as `allow_shlib_undefined`), but COFF does not.

### Expected Behavior

The flag should prevent undefined symbol link errors for all targets.

The workaround:

```zig
    // if bar_lib is part of this build process
    foo_lib.linkLibrary(bar_lib);
    // if libbar.so is on the system
    foo_lib.linkSystemLibrary("bar");
```

(This is actually the preferred approach because you can catch incorrect references at build time instead of at runtime.)

**Comment by kcbanner** [comment]
The windows linker flag to still create a binary even if there are unresolved symbols is `/FORCE:UNRESOLVED` (https://learn.microsoft.com/en-us/cpp/build/reference/force-force-file-output?view=msvc-170)
