### ISSUE TITLE
cannot compile with soft_float cpu feature in both x86 and x86_64 target

### ISSUE THREAD

**Issue by e0328eric** [ziglang/zig#14714]
### Zig Version

v0.11.0-dev.1796+c9e02d3e6

### Steps to Reproduce and Observed Behavior

I compile this in macos.

Using the canonical zig file, which is
```zig
const std = @import("std");

pub fn main() void {
    std.debug.print("Hello, World!", .{});
}
```
and enabling soft_float cpu feature
```console
zig build-exe -mcpu native+soft_float main.zig
```
Then it prints
```console
LLVM Emit Object... fish: Job 1, 'zig build-exe -mcpu baseline+so…' terminated by signal SIGILL (Illegal instruction)
```

### Expected Behavior

It should compile well.

**Comment by Vexu** [comment]
See #12227, you need to disable all hardware float features to use soft floats.
