### ISSUE TITLE
Compiler crash when struct field uses undeclared type (sometimes)

### ISSUE THREAD

**Issue by dbandstra** [ziglang/zig#1472]
This is something I ran into back at the end of July. I tried it again and it still crashes on current master.

I haven't yet been able to isolate it. Here is a commit that breaks my project with one added line of code:

https://gitlab.com/dbandstra/oxid/commit/4ebf7fd0323fcdea99c802d5460ebc96b5f63a9c

The added line is a struct field with an undeclared type. This is the output:

```zig: /home/dbandstra/zig/src/result.hpp:16: void assertNoError(Error): Assertion `err == ErrorNone' failed.```

The weird thing is that the crash only seems to happen if I add a bad field to a  struct in that one file (components.zig). It must have something to do with the particular way(s) those structs are used in my project.

See also: #1186 (another crash related to structs with fields of undeclared type)

**Comment by dbandstra** [comment]
Actually, I checked #1186 again, and it now produces the same error message as this one. So this is probably the same issue.

**Comment by andrewrk** [comment]
Confirmed, I checked out the commit of oxid and it was the same as #1186, which is now fixed.
