### ISSUE TITLE
`error: unbounded for loop` false positive

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#14732]
### Zig Version

0.11.0-dev.1711+dc1f50e50

### Steps to Reproduce and Observed Behavior

```zig
test {
    for (0..) |i| {
        _ = i;
        break;
    }
}
```

```
test.zig:2:5: error: unbounded for loop
    for (0..) |i| {
    ^~~
```

### Expected Behavior

all tests to pass. `while (true)` is not a compile error and this in theory should only go to `std.math.maxInt(usize)` anyways

**Comment by andrewrk** [comment]
This is working as designed. For loops are required by the language to terminate. Safety & optimizations take advantage of this semantic.
