### ISSUE TITLE
std.fs, std.io: confusion between fs.File.readToEndAlloc and io.Reader.readAllAlloc

### ISSUE THREAD

**Issue by perillo** [ziglang/zig#14735]
# Zig Version
0.11.0-dev.1782+b52be973d

# Description
Today I needed to read all the content of a file as a sentinel-terminated slice.
I found that `fs.File` has the `readToEndAllocOptions` and `readToEndAlloc` methods while `io.Reader` has the `readAllAlloc` method.

I think this is quite confusing, because

  1. `readToEndAllocOptions` should belong to Reader.  What is the reason why it was added to `File`?  Convenience?
  2. `readAllAlloc` does not support size hint and there is no support for sentinel-terminated slices.

Thanks.

**Comment by andrewrk** [comment]
[readFileAllocOptions](https://ziglang.org/documentation/master/std/#A;std:fs.Dir.readFileAllocOptions)
