### ISSUE TITLE
web frontpage example not outputting anything with -O ReleaseSmall or -O ReleaseFast

### ISSUE THREAD

**Issue by dufresnep** [ziglang/zig#14738]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

First reported on FreeBSD:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=269838
but reproduced on Ubuntu 22.10 with 0.10.1 as Snap.

Recopying here FreeBSD report:
```
hello works fine, whatever ReleaseFast or ReleaseSmall.
but no1 is problematic
(I am new to zig... might be me)
no1.zig is example on:
https://ziglang.org/

paul@dufresnep:~ $ cd myzig/
paul@dufresnep:~/myzig $ ls
hello		hello.zig	no1.o
hello.o		no1		no1.zig
paul@dufresnep:~/myzig $ zig version
0.10.1
paul@dufresnep:~/myzig $ zig build-exe -O ReleaseSafe no1.zig
paul@dufresnep:~/myzig $ ls -lh no1
-rwxr-xr-x  1 paul  paul   769K Feb 26 12:54 no1
paul@dufresnep:~/myzig $ ./no1
info: up=9999
paul@dufresnep:~/myzig $ zig build-exe -O ReleaseFast no1.zig
paul@dufresnep:~/myzig $ ls -lh no1
-rwxr-xr-x  1 paul  paul    53K Feb 26 12:54 no1
paul@dufresnep:~/myzig $ ./no1
paul@dufresnep:~/myzig $ zig build-exe -O ReleaseSmall no1.zig
paul@dufresnep:~/myzig $ ls -lh no1
-rwxr-xr-x  1 paul  paul   4.4K Feb 26 12:55 no1
paul@dufresnep:~/myzig $ ./no1
paul@dufresnep:~/myzig $ zig build-exe no1.zig
paul@dufresnep:~/myzig $ ls -lh no1
-rwxr-xr-x  1 paul  paul   1.0M Feb 26 12:55 no1
paul@dufresnep:~/myzig $ ./no1
info: up=9999
paul@dufresnep:~/myzig $ 



```

### Expected Behavior

Was expecting ReleaseFast and ReleaseSmall to show same as when no Release.

**Comment by nektro** [comment]
the default log level in release is warn, the homepage code uses `std.log.info()`. you would need to add the following to get it to work across modes:

```zig
pub const std_options = struct {
    pub const log_level = .info;
};

**Comment by dufresnep** [comment]
Your solution did not seems to work for me, but the one taken from:
https://stackoverflow.com/questions/72573442/zig-std-log-info-not-printing-anything-with-cross-compiled-to-aarch64-binary

that is adding at the end of the program:
pub const log_level: std.log.Level = .info;

worked for me.

Would it be possible to update the website with this?

**Comment by dufresnep** [comment]
Made a pull request: https://github.com/ziglang/www.ziglang.org/pull/238/
