### ISSUE TITLE
Function pointers on AVR are not pointing to word addresses

### ISSUE THREAD

**Issue by ekoeppen** [ziglang/zig#14733]
### Zig Version

0.11.0-dev.1711+dc1f50e50

### Steps to Reproduce and Observed Behavior

The code below uses function pointers for a command table, and calls the referenced functions in a loop. In a fully linked application, this causes an MCU reset because the final values for the function pointers are pointing at byte address, not word addresses as required on AVR:

```
const Cmd = extern struct {
    call: *const fn() void,
};

const cmds = [_]Cmd {
    .{ .call = help },
    .{ .call = echo },
};

extern fn marker(u8) void;

fn help() void { marker(0x11); }
fn echo() void { marker(0x22); }

export fn call() void {
    for(cmds) |cmd| {
        cmd.call();
    }
}
```

The relevant part of the the generated code shows that the function pointers are represented verbatim:

```
...
example.help:
        ldi     r24, 17
        rcall   marker
        ret

example.echo:
        ldi     r24, 34
        rcall   marker
        ret

__unnamed_1:
        .short  example.help
        .short  example.echo
```

### Expected Behavior

Function pointers on AVR need to point to word (16 bit) addresses, i.e. the values are simply the byte addresses divided by two. In compiled code, this look like:

```
...
__unnamed_1:
        .short  pm(example.help)
        .short  pm(example.echo)
```

**Comment by ekoeppen** [comment]
These two approaches seem to fix this:

1.  Place functions on AVR into the `.flash` address space. Since pointers to items follow the address space of the pointee, pointers to functions should have the correct alignment. The following changes emulate this fix and produce the correct output:

```
const Cmd = extern struct {
    call: *addrspace(.flash) const fn() void,
};

...
fn help() addrspace(.flash) void { marker(0x11); }
fn echo() addrspace(.flash) void { marker(0x22); }

```

Explicitly adding `addrspace` is however not very desirable, the code is not portable and gets pretty verbose. Having the compile chose `.flash` by default would be preferred.

2. Change the address space of pointers which point to function to `.flash`. This is what clang does: https://reviews.llvm.org/rG57fd86de879cf2b4c7001b6d0a09df60877ce24d

**Comment by Snektron** [comment]
Does the `align` keyword not apply to functions? If so, that could provide a temporary fix

**Comment by ekoeppen** [comment]
I think enforcing alignment will not help here, the problem is the actual value used for an absolute call or jump: Flash on AVR is an array of 16 bit cells, so if you want to jump to e.g. byte address 8, the value for the jump is 4.

**Comment by MasterQ32** [comment]
> Does the `align` keyword not apply to functions? If so, that could provide a temporary fix

Align does not solve this, as the address has to be relocated into a word address instead of a byte address. So: The linker has to divide by two

**Comment by ekoeppen** [comment]
Indeed, and the way to tell the linker is by generating the correct fixups. Right now they are `R_AVR_16`, but they need to be `R_AVR_16_PM`.
