### ISSUE TITLE
Freestanding code failing silently

### ISSUE THREAD

**Issue by kulkarniniraj** [ziglang/zig#14752]
### Zig Version

0.10.0

### Steps to Reproduce and Observed Behavior

I am trying to write a simple user mode code in xv6 OS. Following simple C code works perfectly

```
#include "types.h"
#include "stat.h"
#include "user.h"

int main(){
    int fd, out;
    struct stat st;
    fd = open(".", 0);
    printf(2, "fd: %d\n", fd);

    out = fstat(fd, &st);
    printf(2, "out: %d %d\n", out, st.type);

    exit();
    return 0;
}
```

But in zig equivalent I get trap-6 error and program is killed. 
```
const user = @cImport({
    @cInclude("types.h");
    @cInclude("stat.h");
    @cInclude("user.h");
});

export fn main() i32 {
    var fd: i32 = 0;
    fd = user.open(".", 0);
    user.printf(2, "fd: %d\n", fd);

    var st: user.struct_stat = undefined;
    var out: i32 = -1;

    out = user.fstat(fd, &st);

    user.printf(2, "out: %d\n", out);

    user.exit();            
    return 0;
}
```
Build commands:
```
zig build-obj  zig/scratchpad.zig -O ReleaseSafe -target i386-freestanding -I .
$(LD) $(LDFLAGS) -N -e main -Ttext 0 -o $@ scratchpad.o ulib.o usys.o printf.o umalloc.o 
```

This is especially frustrating since compiler does not give warning and I cannot use Debug mode (some error about zig probe stack not found)

### Expected Behavior

Program does not crash

**Comment by andrewrk** [comment]
> I cannot use Debug mode (some error about zig probe stack not found)

You can use `-fcompiler-rt` or `-fno-stack-check` to resolve this issue, or use Zig as the linker.

> But in zig equivalent I get trap-6 error and program is killed.

Can you share the difference in machine code?

**Comment by andrewrk** [comment]
I'm sorry but this is not enough information to confirm the bug. If you're still willing to give this a try, share more information about the generated machine code of Zig and why it is problematic, and I will re-open this.

**Comment by kulkarniniraj** [comment]
Sure, I have created C and Zig object files. Can't upload it here. But if you want me to run any command, let me know.
