### ISSUE TITLE
error: redeclaration of 'dependency' when using `build.zig.zon`

### ISSUE THREAD

**Issue by gaetschwartz** [ziglang/zig#14777]
### Zig Version

0.11.0-dev.1839+bb5006d72

### Steps to Reproduce and Observed Behavior

1. Clear global zig cache as well as `zig-cache`
2. Run `zig build`
3. Dependencies are duplicated in the cached build and build fails.

![image](https://user-images.githubusercontent.com/25441359/222708559-c6ad8e68-0096-4b72-9193-ccc45de58343.png)

This is definitely about cache, as the issue was not occuring on my machine but on the CI it was (https://github.com/gaetschwartz/zvm/actions/runs/4322526382/jobs/7545139725, https://github.com/zigtools/zls/actions/runs/4320865831/jobs/7541525443). 
After clearing the cache the issue occurs and it's not possible to build a project using `build.zig.zon` dependencies.

**Edit**: When `zig build` is ran a second time, the build succeeds although the cached `dependencies.zig` has still duplicated declarations.

### Expected Behavior

Should not duplicate the declaration.

**Comment by jiacai2050** [comment]
Do you have a minimal project to reproduce this issue?

**Comment by gaetschwartz** [comment]
@jiacai2050 as far as my observations go, any project using dependencies in the `build.zig.zon` file. Here are some of the prjects: https://github.com/gaetschwartz/zvm, https://github.com/zigtools/zls. I can't send a minimal yet, will later if it's still needed.

**Comment by jiacai2050** [comment]
@gaetschwartz Would you mind try [my patch](https://github.com/ziglang/zig/pull/14786)? It works as expected on my machine.

**Comment by ekoeppen** [comment]
I saw the same issue, but the patch fixes the problem for me.
