### ISSUE TITLE
concat (++) of anytype function parameter for runtime call

### ISSUE THREAD

**Issue by trgwii** [ziglang/zig#14817]
### Zig Version

0.11.0-dev.1863+a63134a4a

### Steps to Reproduce and Observed Behavior

Given the following code:

```zig
const std = @import("std");

fn concat(x: anytype) []const u8 {
    return x ++ " world";
}

pub fn main() !void {
    std.debug.print("comptime: {s}\n", .{comptime concat("hello")});
    std.debug.print("runtime : {s}\n", .{concat("hello")});
    std.debug.print("inline  : {s}\n", .{@call(.always_inline, concat, .{"hello"})});
}
```

`zig run concat.zig` produces:
```
comptime: hello world
runtime : hellrld
inline  : hello world
```

`zig run -O ReleaseFast concat.zig` produces:
```
comptime: hello world
runtime : 
inline  : hello world
```

### Expected Behavior

I would either expect a compile error complaining about ++ being used at runtime, or I would expect ++ to force comptime evaluation, and give the following output:
```
comptime: hello world
runtime : hello world
inline  : hello world
```

EDIT: I think the best option is ++ forcing comptime evaluation, so it'll compile error with "can't resolve comptime value" or whatever for actual runtime values, and just work if the value is comptime-known.

**Comment by jacobly0** [comment]
Runtime `++` produces a value on the stack which cannot be returned as a pointer.  This is invalid for the same reason the following function is:
```zig
fn f() *u32 {
    var x: u32 = 42;
    return &x;
}
```

**Comment by andrewrk** [comment]
related: #3180

**Comment by trgwii** [comment]
> Runtime `++` creates a value on the stack which cannot be returned as a pointer. This is invalid for the same reason that dereferencing the result of the following function is:
> 
> ```zig
> fn f() *u32 {
>     var x: u32 = 42;
>     return &x;
> }
> ```

But why is it a runtime ++ when both parameters are comptime-known?

**Comment by mlugg** [comment]
(they're also comptime-known if the function is marked `inline` and the parameter was comptime-known at the call site)

Note that the reason the operands don't have to be comptime-known here is that their lengths are known by their types, since the type passed in is e.g. `*const [5:0]u8`. That means the compiler can emit code to concatenate these into a local buffer at runtime, since the buffer length is known at compile time.
