### ISSUE TITLE
Zig reports wrong version

### ISSUE THREAD

**Issue by fgclue** [ziglang/zig#14836]
### Zig Version

0.11.0.1897+6218e4004

### Steps to Reproduce and Observed Behavior

This happens when you run the `zig version` command.

1. Download zig version 0.11.0.1897+6218e4004 for linux (x86_64)
2. Run `zig version`

It says 0.10.0, I download version 0.11.0.1897+6218e4004.

The link I download from is from `ziglang.org`.
https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.1897+6218e4004.tar.xz

### Expected Behavior

For it to say the actual version, 0.11.0.1897+6218e4004.

**Comment by locriacyber** [comment]
You probably used the wrong `zig`.

0.11.0-dev.1898+36d47dd19 is working fine

**Comment by fgclue** [comment]
I forgot to remove `zig` package from homebrew.
Thanks!
