### ISSUE TITLE
zig-mode: fill-region support with comments

### ISSUE THREAD

**Issue by eatonphil** [ziglang/zig#14847]
### Zig Version

0.9.1

### Steps to Reproduce and Observed Behavior

I start out with

```
//Hey this is a really really really really really really really long line. 
```

And run `fill-region` on the line and get

```
//Hey this is a really really really really really really really
long line.
```

The subsequent lines are incorrectly not commented.

Or another variation of it (before `fill-region`):

```
//Hey this is a really really really really really really really really really really
//long line.
```

And after fill-region

```
//Hey this is a really really really really really really really
really really really //long line.
```

It doesn't preserve the comment markers in the right place.

#### Tangent

It would also be great if this was supported for multiline strings. Emacs does the wrong thing in zig-mode if I have:

```
\\Hey this is a really really really really really really really really really really
\\long line. 
```

And I call `fill-region` on that:

```
\\Hey this is a really really really really really really really
really really really \\long line. 
```

I'd hope that it preserves the string like I'd hope it preserves the comment.

### Expected Behavior

In bash-mode if you do fill-region on a commented section, it fills the region keeping the comment prefix correctly.

(before fill-region)

```
#Hey this is a really really really really really really really really really really
#long line.
```

(after fill-region)

```
#Hey this is a really really really really really really really really
#really really long line.
```

**Comment by leecannon** [comment]
This should be reported [here](https://github.com/ziglang/zig-mode), zig does not provide this functionality.

**Comment by eatonphil** [comment]
Whoops, sorry mixed up the repos. Thanks @leecannon.
