### ISSUE TITLE
packed struct hidden padding issue

### ISSUE THREAD

**Issue by b0bleet** [ziglang/zig#14887]
### Zig Version

0.11.0-dev.1812+26196be34

### Steps to Reproduce and Observed Behavior

```
const std = @import("std");
const expect = std.testing.expect;

pub fn main() anyerror!void {
    const e820map = packed struct {
        addr: u64,
        size: u64,
        type: u32,
    };
    try expect(@sizeOf(e820map) == 20);
}
```
Output:
```
$ zig run check.zig
error: TestUnexpectedResult
/opt/zig/lib/std/testing.zig:509:14: 0x20d807 in expect (test)
    if (!ok) return error.TestUnexpectedResult;
             ^
/tmp/check.zig:30:5: 0x20b695 in main (test)
    try expect(@sizeOf(e820map) == 20);
    ^
```

### Expected Behavior

packed struct size should be 20 bytes.

**Comment by nektro** [comment]
is it `24` ? `packed struct`s create an integer that is in bits the sum of all the fields and primarily used for bit-packing non-power-of-two values into one. here your struct is lowered as a `u160` and likely padded to become either a `u192` or `u256` during codegen. also note you can still assert `20` with `@bitSizeOf(e820map)/8`.

if what you are trying to do is guarantee layout of fields of "normal" size you are likely looking for `extern struct` instead.

**Comment by b0bleet** [comment]
I expected 20 bytes so padding bytes should be ignored, I tried it with 0.9.0 version it works as expected:
[https://godbolt.org/z/rrb4WGxeK](https://godbolt.org/z/rrb4WGxeK)

**Comment by Vexu** [comment]
Packed structs were changed in 0.10.0, see #5049
