### ISSUE TITLE
CI on Windows timing out sometimes

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#14948]
Started happening after the merge of  #14647.

Example run: https://github.com/ziglang/zig/actions/runs/4439981911/jobs/7793180394

Unfortunately the output is completely unhelpful:

```
...
[20/21] Install the project...
-- Install configuration: "Debug"
0
Main test suite...
Error: The operation was canceled.
```

Unclear why this is happening. So far no one has reproduced the issue locally. If the issue happened locally we would be able to attach a debugger to the process and find out why it is stalled.

**Comment by jacobly0** [comment]
Since #15476 was merged, there has only been one master branch CI timeout on `aarch64-windows`, with the following suspicious output:

    Sat, 29 Apr 2023 13:20:45 GMT Main test suite...
    Sat, 29 Apr 2023 13:38:16 GMT run test std-native-ReleaseFast: error: 'test.listen on a unix socket, send bytes, receive bytes' failed
    Sat, 29 Apr 2023 13:38:16 GMT run test std-native-ReleaseFast: error: while executing test 'test.detect', the following test command failed:
    Sat, 29 Apr 2023 13:38:16 GMT C:\actions-runner\_work\zig\zig\build-release\zig-local-cache\oba762a194b2e04ec6d5cc639774700ca\test.exe --listen=- 
    Sat, 29 Apr 2023 18:32:41 GMT Error: The operation was canceled.

The fact that there is output suggests that this is very different from what this issue was created to track, and that the original issues(s) have been fixed.
