### ISSUE TITLE
accept a seed option to the build runner and shuffle the dependency order using it

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#14940]
Extracted from #14647.

Add a --seed option to the build runner and make the `zig build` subcommand always supply a random seed argument.

Use this seed to shuffle the dependency order of steps when -j1 is selected, and ideally also shuffle order of steps for dependency peers when concurrency is being used. Be sure not to disrupt the heuristics for starting leaf dependencies first when the number of threads in the thread pool is greater than one.

This will help protect build scripts from accumulating concurrency bugs.

**Comment by LAC-Tech** [comment]
Adding to what was discussed with Andrew on IRC:

It would also be very useful to expose this some how to tests. In [property-based testing](https://en.wikipedia.org/wiki/Software_testing#Property_testing), there's a different seed for each run of tests, the idea being that as you re-run tests you will randomly explore more of the state space.

**Comment by andrewrk** [comment]
@LAC-Tech I filed a proposal for that idea here: #17609
