### ISSUE TITLE
support G, M, GiB, MiB, GB, MB, etc. shorthands in --maxrss arg

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#14955]
Extracted from https://github.com/ziglang/zig/pull/14647.

https://github.com/ziglang/zig/blob/b4d58e93ea4d0bbfe674f80d301279d302fe8fc8/lib/build_runner.zig#L149-L160

https://github.com/ziglang/zig/blob/b4d58e93ea4d0bbfe674f80d301279d302fe8fc8/lib/build_runner.zig#L952

**Comment by yujiri8** [comment]
I am currently testing a commit for this.
