### ISSUE TITLE
eliminate warnings from the linker

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#14967]
Extracted from https://github.com/ziglang/zig/pull/14647.

In particular, the one I ran into was this one:

https://github.com/ziglang/zig/blob/b4d58e93ea4d0bbfe674f80d301279d302fe8fc8/src/link/MachO/zld.zig#L3808

https://github.com/ziglang/zig/blob/b4d58e93ea4d0bbfe674f80d301279d302fe8fc8/src/link/MachO/zld.zig#L3748

Linker code should not use std.log other than for debug messages, which are disabled in release builds. Instead, it should properly report errors back to the Compilation so that they can be dispatched accordingly. All warnings should become errors, and any such errors that users of the compiler wish to ignore must be addressed via a flag specifically choosing linker behavior to resolve the error. For example, in this case it could be `-fignore-empty-lib-directories`.

Another example:

https://github.com/ziglang/zig/blob/b4d58e93ea4d0bbfe674f80d301279d302fe8fc8/src/link/MachO/zld.zig#L1293-L1294

The corresponding flag could be `-ffloor-unaligned-segments`.

By default, all of the issues should be reported as errors via Compilation's error message API.

**Comment by kubkon** [comment]
Not sure about the flags but the error messages mirror what you get from the system linker on macOS. Totally agree we should use the Compilation error reporting mechanism though.

**Comment by kubkon** [comment]
Solved by #17020
