### ISSUE TITLE
support MSVC 2017

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1496]
* make sure it builds from source. switch the CI server to it
 * libc path detection at runtime

Here's some code Jonathan Blow wrote which looks like it's supposed to handle 2017:
https://gist.github.com/andrewrk/ffb272748448174e6cdb4958dae9f3d8

**Comment by andrewrk** [comment]
Does this work for you?

```
bin/zig.exe build-exe ..\example\hello_world\hello_libc.zig --library c
hello_libc.exe
```

**Comment by Sahnvour** [comment]
Yes, it builds and runs.

**Comment by andrewrk** [comment]
@Angr1st does the above example work for you? Would you two be willing to work together to find out what's different on your respective systems?

Meanwhile I'll go ahead and upgrade my windows laptop to use MSVC 2017.

**Comment by Sahnvour** [comment]
VS2017 can have multiple versions of the build tools installed side by side. This apparently introduced enough complexity for Microsoft to publish [vswhere](https://github.com/Microsoft/vswhere). I don't know how Zig does it, but that's probably related. I will upgrade my Visual Studio installation to the latest version to be on the same page.

**Comment by Angr1st** [comment]
Sure I will finally have some time on sunday to have a closer look at this. From my first peek at the gist you provided it seems like vswhere is huge and thats why the gist exists it is about solving the same problem with less code. I couldnt try it yet though.

**Comment by andrewrk** [comment]
Also noteworthy is that the llvm7 branch just passed the tests on the CI, using the MSVC 2017 AppVeyor image.

**Comment by andrewrk** [comment]
As far as I know this issue is now resolved. If Zig fails to detect MSVC 2015 or 2017 then that is a bug and we need a new issue with steps to reproduce.
