### ISSUE TITLE
More consistent way to add build options modules

### ISSUE THREAD

**Issue by hryx** [ziglang/zig#14979]
In the build system, `OptionsStep`s are a nice way to pass build variables to Zig code being built. But there is a small incongruity between how you do it for `CompileStep`s and for `Module`s.

```zig
pub fn build(b: *std.Build) void {
    // Get option values from the CLI and create options module
    const sideways = b.option(bool, "sideways", "you know what this means") orelse false;
    const shared_opts = b.addOptions();
    shared_opts.addOption("sideways", sideways);

    // For CompileStep, use addOptions()
    const exe = b.addExecutable("pigeon", .{});
    exe.addOptions(shared_opts); // <--

    // For Module, pass as a dependency
    const mod = b.addModule("chicken", .{
        .root_source_file = .{},
        .dependencies = &.{ shared_opts.createModule() }, // <--
    });
}
```

I think there could be a less confusing API. Possibilities:
1. Duplicate the `addOptions` method to Module.
2. Remove `addOptions` so that CompileStep and friends instead use `exe.addModule("options", my_opts.createModule())`, closing the discrepancy.
3. Something else?

**Comment by xdBronch** [comment]
i believe this can be closed after the modules rework, build options are done by adding it to a compile steps root_module now
