### ISSUE TITLE
take away EmitOption.emit_to option and make it give a FileSource

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#14971]
Extracted from https://github.com/ziglang/zig/pull/14647.

https://github.com/ziglang/zig/blob/68c7261e1daf7787dcbf0cd6f9b01e5678d20a93/lib/std/Build/CompileStep.zig#L55-L64

https://github.com/ziglang/zig/blob/68c7261e1daf7787dcbf0cd6f9b01e5678d20a93/lib/std/Build/CompileStep.zig#L295-L309

All of these, including `emit_h`, will no longer have the option to specify an output path, same as #14951. Instead, the two choices will be null, or providing a FileSource to interact with the rest of the build system. The zig compiler itself will only ever see -femit-foo or -fno-emit-foo. It will always put the artifact in the cache directory, and the build script must rely on other steps that interact with FileSource to do anything with the artifacts.

**Comment by RossComputerGuy** [comment]
Is there anything blocking this? If not, I'm willing to implement this in the same PR I am working on for #15156.
