### ISSUE TITLE
zig clang -emit-llvm does not work as intended with assembly and is not available in compile step

### ISSUE THREAD

**Issue by RossComputerGuy** [ziglang/zig#14977]
### Zig Version

0.11.0-dev.1969+d525ecb52

### Steps to Reproduce and Observed Behavior

Try compiling `src/x86/unix64.S` with `zig clang` in `libffi`, I have it integrated into my project and I discovered this error:

```
/home/ross/ExpidusOS/neutron/vendor/libs/libffi/src/x86/unix64.S:596:14: error: invalid variant 'rel'
 .long .LUW0@rel
             ^
/home/ross/ExpidusOS/neutron/vendor/libs/libffi/src/x86/unix64.S:615:14: error: invalid variant 'rel'
 .long .LUW5@rel
             ^
/home/ross/ExpidusOS/neutron/vendor/libs/libffi/src/x86/unix64.S:628:14: error: invalid variant 'rel'
 .long .LUW8@rel
             ^
/home/ross/ExpidusOS/neutron/vendor/libs/libffi/src/x86/unix64.S:642:15: error: invalid variant 'rel'
 .long .LUW12@rel
              ^
/home/ross/ExpidusOS/neutron/vendor/libs/libffi/src/x86/unix64.S:655:15: error: invalid variant 'rel'
 .long .LUW15@rel
```

I did some digging and `-emit-llvm` should fix that. I naturally tried `emit_llvm_ir` and `emit_llvm_br` in `std.Build.CompileStep` on one made from `std.Build.addAssembly()`. This however, does not solve this error. I noticed `emit_llvm_ir` and `emit_llvm_br` did not add the argument so I ran the command that was outputted with `zig build --verbose-cc` and it worked just fine. So we've got 2 problems here:

1. Currently, `std.Build` does not have a way to pass `emit-llvm` to `zig clang`
2. `zig clang`'s `-emit-llvm` argument does not function the same as `clang`'s `-emit-llvm`

### Expected Behavior

What we should have is:
1. `std.Build.CompileStep` should pass `-emit-llvm`, probably with a new `EmitOption` called `emit_llvm`, which is passed to `zig clang`
2. `zig clang -emit-llvm` should be functioning the same as `clang -emit-llvm` which would fix the assembly error

**Comment by andrewrk** [comment]
Related:  #14971

**Comment by RossComputerGuy** [comment]
This problem is kinda solved in libffi with defining `HAVE_AS_X86_PCREL` in the config file but on x86 (not x86_64), I run into #7935

**Comment by andrewrk** [comment]
`zig clang` is not a supported feature. Are you intending to use `zig cc` instead?
