### ISSUE TITLE
tests: wine is always used

### ISSUE THREAD

**Issue by perillo** [ziglang/zig#14988]
### Zig Version

0.11.0-dev.6888+cfcd6698c

### Steps to Reproduce and Observed Behavior

I have *wine* installed.

`$ zig build -fno-wine test-std`

When the test is running, I got several *Program Error dialog box* from Wine, meaning that wine is enabled, even though I have explicitly disabled it.

### Expected Behavior

*wine* should never be used during tests.

**Comment by andrewrk** [comment]
Zig does not invoke wine unless -fwine is enabled:

https://github.com/ziglang/zig/blob/2089b3f193beaef6debc5671ca6d1f6fc028db8d/lib/std/Build/RunStep.zig#L587-L592

However, it does try to execute the binary even if it might be a "foreign" binary. What I suspect is happening on your system, is that you have binfmt_misc set up to run executables with Wine. In this case, it is not up to Zig, but up to you, how your system is configured.

**Comment by perillo** [comment]
You were right.  Wine was registered to binfmt_misc automatically after installing the package (on Archlinux).

FYI, I disabled it with:
```sh
cd /etc/binfmt.d
sudo ln -s /dev/null wine.conf
sudo systemctl restart systemd-binfmt.service
```

See binfmt.d(5).
Thanks.

**Comment by andrewrk** [comment]
As a side note, zig's std lib tests currently trigger some bugs in Wine that we need to report upstream. For many users' projects, wine integration with binfmt_misc will actually work smoothly.

**Comment by perillo** [comment]
I noted that in `std/zig/system/NativeTargetInfo.zig` we have:
```zig
 pub const GetExternalExecutorOptions = struct {
    allow_darling: bool = true,
    allow_qemu: bool = true,
    allow_rosetta: bool = true,
    allow_wasmtime: bool = true,
    allow_wine: bool = true,
    qemu_fixes_dl: bool = false,
    link_libc: bool = false,
};
```

While rosetta being enabled seems the correct choice, I'm not sure about enabling wine, qemu, wasmtime and darling.
The problem is that with this config `RunStep.zig` will depend on how the system is configured, and this may be not under the user control.

As an example, on Archlinux wine is enabled in binfmt_misc by default, due to the file `usr/lib/binfmt.d/wine.conf` in the package but qemu is not.
