### ISSUE TITLE
Struct memory corruption or misload

### ISSUE THREAD

**Issue by ssedrick** [ziglang/zig#14990]
### Zig Version

0.11.0-dev.1987+a2c6ecd6d

### Steps to Reproduce and Observed Behavior

I'm hitting an issue with the struct values changing underneath me. The weird part is that the first time I call a method on a struct it works fine. Memory is loaded correctly, slices point to the correct spot, etc. But on a second run, the method is provided bad values for the `self` parameter.

I dived in with `lldb` and from what I can tell, the second time around, the values loaded into registers for `self` in `self.scanner.next()` call is loading the wrong memory, or the memory has been corrupted.

<details>
<summary>Minimal code reproduction</summary>

The second call to `parser.advance()` leads to a segfault on the `std.fmt.format` call. Somehow, the memory for the struct isn't being loaded correctly. 
```zig
const std = @import("std");

const Token = struct {
    name: []const u8,
    lexeme: []const u8,
};

const ScanError = error{UnexpectedEof};

const Scanner = struct {
    source: []const u8,
    start: u64 = 0,
    current: u64 = 0,

    pub fn next(self: *Scanner) !Token {
        if (self.current >= self.source.len) {
            return ScanError.UnexpectedEof;
        }
        self.start = self.current;
        while (self.current < self.source.len and self.source[self.current] != ' ') {
            self.current += 1;
        }
        return Token{
            .name = "identifier",
            .lexeme = self.source[self.start..self.current],
        };
    }
};

const Parser = struct {
    scanner: *Scanner,
    current: Token = undefined,

    pub fn advance(self: *Parser) !void {
        // Source is different on the second call.
        std.debug.print("Source: {s}\n", .{ .source = self.scanner.source });
        // @breakpoint();
        if (self.scanner.next()) |tok| {
            // Do somethign with tok
            std.debug.print("Got token: {any}\n", .{ .tok = tok });
            self.current = tok;
        } else |err| {
            std.debug.print("Got error: {any}\n", .{ .err = err });
        }
    }
};

const Compiler = struct {
    parser: Parser,
    scanner: Scanner,

    pub fn new(source: []const u8) Compiler {
        var scanner = Scanner{
            .source = source,
        };
        return Compiler{
            .parser = Parser{
                .scanner = &scanner,
            },
            .scanner = scanner,
        };
    }
    pub fn compile(self: *Compiler) !void {
        try self.parser.advance();
        try self.parser.advance();
    }
};

pub fn main() !void {
    var buf: [1024]u8 = .{0} ** 1024;
    const in = std.io.getStdIn();
    const out = std.io.getStdOut();

    while (true) {
        _ = try out.write("> ");
        var read = try in.read(&buf);
        var compiler = Compiler.new(buf[0..read]);
        try compiler.compile();
    }
}

```
</details>

### Expected Behavior

Subsequent calls to struct methods correctly load the values from memory into the registers.

**Comment by leecannon** [comment]
`scanner` is on the stack of `new` and becomes invalid the moment you return.

```zig
    pub fn new(source: []const u8) Compiler {
        var scanner = Scanner{
            .source = source,
        };
        return Compiler{
            .parser = Parser{
                .scanner = &scanner,
            },
            .scanner = scanner,
        };
    }
```

**Comment by ssedrick** [comment]
Ahh, rookie mistake. I've been in GCd languages too long.
So why does it work the first time around? The program hasn't run long enough to override that memory block?

**Comment by hryx** [comment]
@ssedrick It's probably something like that. It's hard to reason about what happens when you access invalidated stack memory, but when the stack depth is shallow at the time of access, sometimes you can see values that look valid simply because they haven't been overwritten yet.
