### ISSUE TITLE
zig libc panics on Apple M2 / Ventura

### ISSUE THREAD

**Issue by telekid** [ziglang/zig#15024]
### Zig Version

0.11.0-dev.2191+30427ff79

### Steps to Reproduce and Observed Behavior

Looks similar to [this (closed) issue](https://github.com/ziglang/zig/issues/10478).

1. Download the above zig version from the releases page.
2. Ensure zig is on $PATH
3. run `zig libc`

Output:
```
% zig libc
thread 4918749 panic: Darwin is handled separately via std.zig.system.darwin module
Unable to dump stack trace: debug info stripped
zsh: abort      zig libc
```

`zig env` works fine:
```json
{
 "zig_exe": "/Users/jake/.local/bin/zig/zig",
 "lib_dir": "/Users/jake/.local/bin/zig/lib",
 "std_dir": "/Users/jake/.local/bin/zig/lib/std",
 "global_cache_dir": "/Users/jake/.cache/zig",
 "version": "0.11.0-dev.2191+30427ff79",
 "target": "aarch64-macos.13.2...13.2-none"
}
```

### Expected Behavior

Normal output from `zig libc`.

macOS verison: 13.2 (22D49)
On Apple Silicon M2

**Comment by jiacai2050** [comment]
https://github.com/ziglang/zig/blob/bc0f246911a35324473f72b770cc5715902cc912/src/libc_installation.zig#L185

I found this was caused by this commit https://github.com/ziglang/zig/commit/4270f234db02d40da1507fe5cb20029aa320ee42
