### ISSUE TITLE
`std.math.lossyCast` panics on `nan`

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#15038]
### Zig Version

0.11.0-dev.1913+95f6a5935

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() !void {
	var nan: f32 = std.math.nan(f32);
	_ = std.math.lossyCast(i32, nan);
}
```

```
$ zig run test.zig
thread 46670 panic: integer part of floating point value out of bounds
/home/mint/Downloads/zig/lib/std/math.zig:1312:32: 0x20afd0 in lossyCast__anon_2960 (test)
                        return @floatToInt(T, value);
                               ^
/home/mint/Desktop/test.zig:5:24: 0x20af08 in main (test)
 _ = std.math.lossyCast(i32, nan);
                       ^
```

### Expected Behavior

According to the doc comment of `lossyCast` the float should be converted to the closest possible representation (whatever that would be for `nan`):
>  Cast a value to a different type. If the value doesn't fit in, or
can't be perfectly represented by, the new type, it will be
converted to the closest possible representation.

So either the doc comment needs to be adjusted to explicitly mention the panic on `nan` or the behavior needs to be changed to detect `nan` and convert it to `0` or whatever.

**Comment by candrewlee14** [comment]
This seems like it’d be best to allow the user to specify the behavior. Maybe return an error on nan rather than doing some conversion.

**Comment by RossComputerGuy** [comment]
Wouldn't it just be better to return nan if a nan is passed?

**Comment by IntegratedQuantum** [comment]
> Wouldn't it just be better to return nan if a nan is passed?

That's already happening for float to float casting.
The problem is float to int casting, and integer types don't have a defined `nan` value.

**Comment by RossComputerGuy** [comment]
I see, I wasn't aware of that. Well, it should return `0` instead since that's the closest thing integers have to nan.
