### ISSUE TITLE
wiki/Contributing: document that mono is required for -fwine and remove obsolete content

### ISSUE THREAD

**Issue by perillo** [ziglang/zig#15032]
## wine

When running tests with `-fwine` I got the error
`013c:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption`

After a search I found that `mono` needs to be installed to avoid the problem.  This should be documented in https://github.com/ziglang/zig/wiki/Contributing#testing-windows-from-a-linux-machine-with-wine.

## obsolete content

In https://github.com/ziglang/zig/wiki/Contributing#improving-translate-c there are still references to the old stage1 compiler:

"This feature is self-hosted, even though Zig is not fully self-hosted yet. In the Zig source repo, we maintain a C API on top of Clang's C++ API:"

**Comment by andrewrk** [comment]
I am going to delete this to avoid cluttering up issues search with noise.
