### ISSUE TITLE
unsupported linker arg -wrap

### ISSUE THREAD

**Issue by zachcheu** [ziglang/zig#15051]
### Zig Version

0.11.0-dev.1796+c9e02d3e6

### Steps to Reproduce and Observed Behavior

Attempted to build go_library bazel target depending on `org_kernel_pub_linux_libs_security_libcap_psx`

Resulted in 

> ERROR: /home/user/.cache/bazel/_bazel_zach.cheung/b97476d719d716accead0f2d5b93104f/external/org_kernel_pub_linux_libs_security_libcap_psx/BUILD.bazel:3:11: GoCompilePkg external/org_kernel_pub_linux_libs_security_libcap_psx/psx.a failed: (Exit 1): builder failed: error executing command (from target @org_kernel_pub_linux_libs_security_libcap_psx//:psx) bazel-out/k8-opt-exec-2B5CBBC6-ST-046b4a899367/bin/external/go_sdk/builder_reset/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src ... (remaining 47 arguments skipped)
> 
> Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
> error: unsupported linker arg: -wrap
> compilepkg: error running subcommand external/zig_sdk/tools/x86_64-linux-gnu.2.19/c++: exit status 1

### Expected Behavior

Expected `-wrap` flag to be supported and result in successful build.

**Comment by motiejus** [comment]
Note the exact linker flag was:
```
-Wl,-wrap,pthread_create
```
