### ISSUE TITLE
remove functions that do operations based on a stored Build object to prevent use as a dependency from being confusing

### ISSUE THREAD

**Issue by travisstaloch** [ziglang/zig#15079]
### Zig Version

0.11.0-dev.2213+515e1c93e

### Steps to Reproduce and Observed Behavior

The issue can be reproduced using https://github.com/travisstaloch/flatbufferz which is packaging a fork of google/flatbuffers in order to depend on flatc, a cpp artifact.

If you look [here](https://github.com/travisstaloch/flatbufferz/blob/209facf44af0b599bc9ab3b3a094f456a95db4a2/build.zig#L109), the flatc artifact is installed, by calling `flatc.install()`.  However, after running `zig build`, there is no `zig-out/bin/flatc` artifact.

```console
$ cd /tmp

$ git clone git@github.com:travisstaloch/flatbufferz.git
Cloning into 'flatbufferz'...
remote: Enumerating objects: 559, done.
remote: Counting objects: 100% (226/226), done.
remote: Compressing objects: 100% (109/109), done.
remote: Total 559 (delta 144), reused 180 (delta 107), pack-reused 333
Receiving objects: 100% (559/559), 309.64 KiB | 493.00 KiB/s, done.
Resolving deltas: 100% (338/338), done.

$ cd flatbufferz

$ zig build

$ ls zig-out/bin/
flatc-zig

$ find . -name flatc
./zig-cache/o/833a03ff5579567f09c3cc253daebf11/flatc
```

Here is the relevant part from the bottom of build.zig
```zig
// build.zig
const flatbuffers_dep = b.dependency("flatbuffers", .{
    .target = target,
    .optimize = optimize,
});
const flatc = flatbuffers_dep.artifact("flatc");
flatc.install(); // <-- doesn't do anything
build_options.addOptionArtifact("flatc_exe_path", flatc);
exe.step.dependOn(&flatc.step);

const flatc_run = b.addRunArtifact(flatc);
flatc_run.has_side_effects = true;
flatc_run.cwd = b.pathFromRoot(".");
if (b.args) |args| flatc_run.addArgs(args);
const flatc_run_step = b.step("flatc", "Run packaged flatc compiler");
flatc_run_step.dependOn(&flatc_run.step);
```

In this [discord help thread](https://discord.com/channels/605571803288698900/1089276581568053299) it was suggested to try the following, which may provide a clue about what is going wrong:
> 0p: I can trigger the install but it stays in cache; what I've tried:
```zig
    const install_flatc = b.addInstallArtifact(flatc);
    // flatc.install();
    build_options.addOptionArtifact("flatc_exe_path", flatc);
    exe.step.dependOn(&install_flatc.step);

    const flatc_run = b.addRunArtifact(install_flatc.artifact);
    flatc_run.step.dependOn(&install_flatc.step);
```

after applying these changes the artifact appears in `./zig-cache/i` too:
```console
$ find . -name flatc
./zig-cache/i/9de7449a03393bec5fd02bbd8bdffa7f/bin/flatc
./zig-cache/o/833a03ff5579567f09c3cc253daebf11/flatc
```

### Expected Behavior

I expected to see a `zig-out/bin/flatc` artifact after running `zig build`

**Comment by gitusel** [comment]
I do not know if related, but with the new parallel builds, I just observed that spawn processes were created regardless of the dependency chain. In my case I attached a RunStep after installation and sometimes it run before the installation was completed.

**Comment by kassane** [comment]
`zig-pkg` at the moment is focused on sharing only libraries as dependencies and not executables.

Recently, when carrying out the port of libVLCpp (header-only) to zig-pkg. It was then necessary to improvise by creating a fake library (empty.cpp) containing the headers and the other project to receive would finally be able to receive the hpp even without linking to the empty library.

https://github.com/kassane/libvlcpp/commit/fa380a53190f704db426d8f6dbd87e974e51d062

**Comment by andrewrk** [comment]
Instead of 

```zig
flatc.install(); // <-- doesn't do anything
```

you need to install it with the *current* Build object rather than the dependency Build object, like this:

```zig
b.installArtifact(flatc);
```

Similar problem as running a program from a dependency. I'll probably remove `CompileStep.install` since it can act as a red herring in this case.

**Comment by travisstaloch** [comment]
> you need to install it with the _current_ Build object rather than the dependency Build object, like this:
> 
> ```zig
> b.installArtifact(flatc);
> ```

I tried doing this and still not seeing the artifact get installed to zig-out/bin
```console
$ zig build

$ ls zig-out/bin/
flatc-zig  sample

$ find . -name flatc
./zig-cache/i/9de7449a03393bec5fd02bbd8bdffa7f/bin/flatc
./zig-cache/i/07f206fda4ec425333857492944cc969/bin/flatc
./zig-cache/o/833a03ff5579567f09c3cc253daebf11/flatc
./zig-cache/o/c5c714d421bcee82ffdb794065b5c296/flatc
```

**Comment by travisstaloch** [comment]
oh, i noticed that there IS a difference here. 

previously when doing `flatc.install();` there was no flatc file in `./zig-cache/i`.  however, doing `b.installArtifact(flatc);` results in a file there. so it seems like this is a step in the right direction?

**Comment by andrewrk** [comment]
Added the bug label back because I would expect to see `flatc` appear in zig-out/bin/flatc in this case.

**Comment by andrewrk** [comment]
```
andy@ark ~/D/flatbufferz (main)> ls zig-out/bin/
flatc-zig
```

**Comment by travisstaloch** [comment]
yes thats correct. i'm expecting to see 3 files in zig-out/bin: `flatc-zig` `sample` and `flatc`

**Comment by andrewrk** [comment]
I found the culprit:

https://github.com/ziglang/zig/blob/311d50f9dc96c3d397081a1afcc3b519ae1e973f/lib/std/Build/InstallArtifactStep.zig#L21

Some vestigial code, sabotaging everything! I'll have a fix up shortly.
