### ISSUE TITLE
Add multi-call behavior to zig binary for true drop-in replacement

### ISSUE THREAD

**Issue by dimaguy** [ziglang/zig#15084]
In order to make zig binary the ultimate drop-in replacement for it's targets(cc, ar, etc...), maybe it could act like busybox and, for example, act like 'zig cc' subcomand if called with the names cc/gcc/clang

**Comment by silversquirl** [comment]
What's the advantage over a simple shell script?

```sh
#!/bin/sh
zig cc "$@"
```

**Comment by squeek502** [comment]
Duplicate of https://github.com/ziglang/zig/issues/4787

**Comment by dimaguy** [comment]
> What's the advantage over a simple shell script?
> 
> ```sh
> #!/bin/sh
> zig cc "$@"
> ```

Programs that expect binaries won't accept shell scripts

**Comment by dimaguy** [comment]
> Duplicate of #4787 I believe

It seems indeed to be a duplicate of that, I should've paid more attention, sorry
