### ISSUE TITLE
zig doesn't produce global variable debug information 

### ISSUE THREAD

**Issue by ryuukk** [ziglang/zig#15095]
### Zig Version

zig-windows-x86_64-0.11.0-dev.2287+1de64dba2.zip

OS: Windows 10 x64

### Steps to Reproduce and Observed Behavior

```zig
var global: i32 = 0;

pub fn main() !void
{

}

```

break and try to inspect ``global``

vscode:

![image](https://user-images.githubusercontent.com/44361234/228101687-d846085b-602f-4ca6-aac5-2a175d628c45.png)

remedybg:

![image](https://user-images.githubusercontent.com/44361234/228101713-84e4530a-7b5f-4561-a1f3-768ce46a789f.png)

vscode launch config:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "windows: game",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/bin/game.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}/bin/",
            "environment": [],
            "externalConsole": false,
        },
    ]
}
```

### Expected Behavior

I should be able to inspect ``global`` in the debugger's watch menu

**Comment by squeek502** [comment]
Does adding `pub` to global change anything? I would guess that it is getting optimized out since it's unused and not `pub`.

**Comment by davidgm94** [comment]
Yeah, I think I was wrong and I apologize. Actually exporting the variable works for me on Linux, you could try that in the meantime. The problem seems to be with namespaced non-exported global variables... I can't get to inspect them with GDB.

**Comment by andrewrk** [comment]
Not fixed by #15349:

```zig
var global: i32 = 0;

pub fn main() !void {
    global += 124;
}
```

```
$ gdb ./test
(gdb) break test.main
Breakpoint 1 at 0x20af48: file test.zig, line 4.
(gdb) run
Starting program: /home/andy/Downloads/zig/build-release/test 

Breakpoint 1, test.main () at test.zig:4
4	    global += 124;
(gdb) p 'test.global'
$1 = <optimized out>
(gdb) 
```

**Comment by r1sc** [comment]
Is there any progress on this? I'd like to help but I'm not really familiar with the Zig compiler infrastructure yet..

**Comment by LaXiS96** [comment]
Can confirm this also happens while targeting thumb-freestanding-none and using the Cortex-Debug VSCode extension. At first I thought it could have been an extension issue but it's GDB that doesn't "see" the variable.

**Comment by Srekel** [comment]
This is not solved for me. 

![image](https://github.com/ziglang/zig/assets/1578924/d982b1b2-6ec4-4fee-b8cd-a64fb8314c3e)

This is using a default exe setup I think. Here is my tasks.json:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "zig build  --summary failures",
            "group": "build",
            "problemMatcher": [
                "$gcc"
            ],
            "presentation": {
                "clear": true
            }
        },
    ]
}
```

and here is launch.json

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/zig-out/bin/zigtesting.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "preLaunchTask": "build"
        },
    ]
}
```

Running on Windows 11 Home. `builtin.zig_version` prints `debug: 0.13.0`

**Comment by Srekel** [comment]
On a separate note, would it be possible to get a specific github label for bugs about missing debug information, or actually debug-related issues in general?

I would love to report more, as they are at the top of the list of Zig things we would like improved for Tides, but it's hard to know which ones are already reported (long list of issues to look through).

**Comment by Vexu** [comment]
Are you able to see the value of `hello` by hovering over it? For me using lldb `a.global` is showing up as a static variable (which is incorrect but a different issue).



> On a separate note, would it be possible to get a specific github label for bugs about missing debug information, or actually debug-related issues in general?

Sure!

**Comment by Srekel** [comment]
> Are you able to see the value of hello by hovering over it?

Yep!

![image](https://github.com/ziglang/zig/assets/1578924/16cc7195-0405-43f7-aa72-b4f23ebdc885)

Also it shows up if I add a watch for it. `lol` however doesn't.
