### ISSUE TITLE
wiki/Community: new uzbek community maintainer

### ISSUE THREAD

**Issue by katsuki-yuri** [ziglang/zig#15111]
with the old maintainer left the project, i became the new maintainer for the uzbek community of ziglang and currently working on localization part of docs & many resources with a team of enthusiasts. please, can we change the link of uzbek telegram chat owner to me [yuri](https://github.com/katsuki-yuri) at https://github.com/ziglang/zig/wiki/Community#telegram.

all localization progresses will be shared at: https://github.com/ziglanguz 

thanks a lot in advance! 🙏🏻☺️

**Comment by Vexu** [comment]
Done.

**Comment by katsuki-yuri** [comment]
Thank you very much! @Vexu
