### ISSUE TITLE
`zig build-exe` fail (or fail to run ) on MacOS M2

### ISSUE THREAD

**Issue by sbzi1020** [ziglang/zig#15141]
### Zig Version

0.11.0-dev.2322+83051b0cb

### Steps to Reproduce and Observed Behavior

I saw everyone can create a `.zig` file with a `main` function, then `zig build-exe` to generate an executable and run it, why it doesn't happen on MacOS?:)

<img width="913" alt="Screenshot 2023-04-01 at 10 13 45 PM" src="https://user-images.githubusercontent.com/18152761/229277355-6ff1f09c-6e86-465d-a79b-95cdc22e7ce8.png">

### Expected Behavior

`zig build-exe` should work as excepted.

**Comment by nullptrdevs** [comment]
Name collision — a directory by that name already exists. Use a different file name or provide one with `--name`.

**Comment by rohlem** [comment]
Explanation above seems very likely - in which case the compiler should definitely provide an error message.
See also #15116 - not duplicate, but the issue can maybe be repurposed as a follow-up or subtask.

**Comment by sbzi1020** [comment]
Thanks guys, problem solved:)
