### ISSUE TITLE
make the `addTest` silent breaking change not silent

### ISSUE THREAD

**Issue by leecannon** [ziglang/zig#15151]
The change to `addTest` to only compile the test but not run them is a silent breaking change that affects almost every project and most people have not realised it, how many CI are running "zig build test" now and it is only compiling the tests and not running them?

Even the zig project itself has been caught out by this change as the init-exe and init-lib templates don't run the tests currently and some of the standalone test are also not executed: embed_generated_file, extern, issue_794 and issue_9812.

### Proposal
To clarify this change `addTest` should be renamed to `addTestExecutable` with a compile error on `addTest` to direct people to `addTestExecutable`. 
Also there should be a doc comment on `addTestExecutable` saying something like "In order to run the test executable use addRunArtifact".

**Comment by matu3ba** [comment]
@leecannon Do you want to implement this? I'm wondering, why this has not been accepted yet.

**Comment by andrewrk** [comment]
I think it was a good idea and it should have happened but it's too late now. I'll make sure to mention this loudly in the release notes.
