### ISSUE TITLE
no file name or line numbers where compiler error occurred.  

### ISSUE THREAD

**Issue by IwateKyle** [ziglang/zig#15153]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Output

I'm going through the "Learn Zig" section of the website and plugging in some of the example code.  Trying to change the code to experiment I notice that the compiler doesn't give me much information that is relative to me.    In fact, I might even say that no information is related to me because I don't know where the error took place.  It would be nice if the line number and file name would be reported.

Example code and Example compiler output.
```

        │ File: string_literals.zig
   1   │ const print = @import("std").debug.print;
   2   │ const mem = @import("std").mem; // will be used to compare bytes
   3   │
   4   │ pub fn main() void {
   5   │     const bytes = "hello";
   6   │     print("{}\n", .{@TypeOf(bytes)}); // *const [5:0]u8
   7   │     print("{d}\n", .{bytes.len}); // 5
   8   │     print("{c}\n", .{bytes[1]}); // 'e'
   9   │     print("{d}\n", .{bytes[5]}); // 0
  10   │     print("{d}\n", .{bytes[3]}); // 0
  11   │     print("{d}\n", .{'e'}); // 0
  12   │     print("{}\n", .{'e' == '\x65'}); // true
  13   │     print("{}\n", .{'e' == 101}); // true
  14   │     print("{d}\n", .{'\u{1f4a9}'}); // 128169
  15   │     print("{d}\n", .{'💯'}); // 128175
  16   │     print("{c}\n", .{128175}); // 128175
  17   │     print("{u}\n", .{'⚡'});
  18   │     print("{}\n", .{mem.eql(u8, "hello", "h\x65llo")}); // true
  19   │     print("{}\n", .{mem.eql(u8, "💯", "\xf0\x9f\x92\xaf")}); // also true
  20   │     const invalid_utf8 = "\xff\xfe"; // non-UTF-8 strings are possible with \xNN notation.
  21   │     print("0x{x}\n", .{invalid_utf8[1]}); // indexing them returns individual bytes...
  22   │     print("0x{x}\n", .{"💯"[1]}); // ...as does indexing part-way through non-ASCII characters
  23   │ }
```
The code above includes a change I added that won't compile.  I know where the error is.  But, the compiler won't tell me.  Here is the compiler output.
```

file://........fmt.zig:768:13: error: cannot print integer that is larger than 8 bits as an ASCII character
            @compileError("cannot print integer that is larger than 8 bits as an ASCII character");
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    formatValue__anon_7562: /home/kyle/.asdf/installs/zig/0.10.1/lib/std/fmt.zig:741:38
    formatType__anon_7025: /home/kyle/.asdf/installs/zig/0.10.1/lib/std/fmt.zig:486:20
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

There is one line in the output that seems a bit informative, but I only know that because I deliberately put the error in the code and I know where it is.  But, the compiler is not telling me.   

Is there a reason why the compiler is reserving not give me this information?  "It could tell me but it would have to kill me..." sort of arrangement?  lol

### Expected Output

I was expecting to see A file name and the nearest line or fragment of offending code.

**Comment by Vexu** [comment]
Please read the entire error message:
```
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

With that flag added the output points to line 16 in the input file.
