### ISSUE TITLE
undelcared identifier `@"+"`

### ISSUE THREAD

**Issue by Radvendii** [ziglang/zig#15159]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

create a function that takes in another comptime function of the right type:
```
fn func(comptime op: fn (u32, u32) u32) u32 {
    return op(4, 5);
}
```
Then call it with `@"+"` as the argument
```
pub fn main !void {
    _ = func(@"+");
}
```
I get `use of undeclared identifier '+'`

---

Note that if you declare another function as so
```
fn _add(x: u32, y: u32) u32 {
    return x + y;
}
```
you can then call `func(_add)` no problem.

### Expected Behavior

I would expect `@"+"` to be a known identifier, since `+` is the addition function

**Comment by Radvendii** [comment]
Oh. Which I guess is a different namespace. Is there a way to do this without defining `_add`?

**Comment by silversquirl** [comment]
No. Operators are not functions, and Zig does not define any functions that map to operators

**Comment by silversquirl** [comment]
You could use a function in an anonymous struct though:
```zig
func(struct {
    fn add(x: u32, y: u32) u32 {
        return x + y;
    }
}.add);
```

**Comment by Radvendii** [comment]
Is there a reason this is made unnatural? Am I doing something that isn't idiomatic in zig, and I should be looking for another way?

**Comment by silversquirl** [comment]
Zig is primarily a procedural language, so higher order functions are a bit less common in Zig than they might be in a language that provides more support for functional programming. It's hard to say whether what you're trying to do is best done with higher order functions without more context, but this issue tracker isn't really the place for that.

If you want you could ask in the #zig-help channel on the [Zig Discord server](https://discord.gg/zig), or in one of the many other community spaces :)

**Comment by Radvendii** [comment]
Thanks
