### ISSUE TITLE
Package manager hash mismatch expected/found wrong

### ISSUE THREAD

**Issue by nahsheef** [ziglang/zig#15191]
### Zig Version

0.11.0-dev.2375+771d07268

### Steps to Reproduce and Observed Behavior

Giving the package manager a test run against https://github.com/capy-ui/capy, I hit what looks like a bug in hash mismatch reporting. The values for expected and found are switched.

```
error: hash mismatch:
expected: 1220cc01af945ce8eda22be2f46a31a6b0795bd4f6041257bcecd3863267550b49d9,
found: 122073720ea092164db2142b5e250ed01ae235ae364ec46647484d4bfb1f60f3d7b4
```

### Expected Behavior

```
error: hash mismatch:
expected: 122073720ea092164db2142b5e250ed01ae235ae364ec46647484d4bfb1f60f3d7b4,
found: 1220cc01af945ce8eda22be2f46a31a6b0795bd4f6041257bcecd3863267550b49d9
```

**Comment by andrewrk** [comment]
Check again, the behavior is correct.

**Comment by nahsheef** [comment]
Oh, I see. I was reading 'expected' as in 'expected to find 12.... in build.zig.zon', but it makes sense if I read it as 'you expected the hash to be, but what we fetched is ... found: ...'

**Comment by Arnau478** [comment]
This is confusing, and should be changed to make it clearer. It does make sense, but it's a bit unclear why at first... Maybe some rephrasing would help.

**Comment by copygirl** [comment]
This also confused me. "expected" could mean "this is the value we expected the computed value to be" or "this is the value we expect the hash provided for the package to be". Similarly "found" could be the computed value, or the value found in the `build.zig.zon`.

I would suggest replacing "found" with "actual" (as it's called in the code) or "computed".
I'm less sure about "expected" but perhaps "requested" would fit?
