### ISSUE TITLE
reproducibility regression in stage3/stage4 release builds in the llvm16 branch

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#15197]
This check regressed in the llvm16 branch:

https://github.com/ziglang/zig/blob/8853005672374ceac8760548027a03fa284bf2d1/ci/x86_64-macos-release.sh#L71-L74

This is likely not due to a problem with LLVM but due to exposing a latent bug. The bug is not occurring on Linux, suggesting a problem with macOS-specific logic such as the macho linking code.

**Comment by mikdusan** [comment]
### on my host
- does not reproduce with system-bootstrapping (system compiler used to build llvm, etc)
- reproduces with zig-bootstrap (zig+llvm+lld+clang-x86_64-macos-none-0.11.0-dev.2441+eb19f73af)

### notes
- eb19f73af was first relevant CI failure
- zig-bootstrap is based on same commit (eb19f73af , so far ok)
- but ef5afbf commit came after and it has an `f16` related fix for macos

Perhaps we need to roll a new zig1.wasm and zig-bootstrap on latest master.
If you could roll a new zig-bootstrap and post it, I can try it out locally here and try rolling zig1.wasm locally if needed .
