### ISSUE TITLE
Inline assembly with vectors appears to generate broken assembly on x86_64

### ISSUE THREAD

**Issue by notcancername** [ziglang/zig#15227]
### Zig Version

0.11.0-dev.2336+5b82b4004

### Steps to Reproduce and Observed Behavior

1. Create two files, `phaddw.zig` and `phaddw.c`.
2. Put the following in `phaddw.zig`:
```zig
export fn phaddw_zig(a: @Vector(4, i16), b: @Vector(4, i16)) @Vector(4, i16) {
    var tmp = a;
    asm volatile("phaddw %[b], %[a]" : [a] "+&y" (tmp) : [b] "y" (b));
    return tmp;
}
```
3. Put the following in `phaddw.c`:
```c
#include <immintrin.h>

__m64 phaddw_c(__m64 a, __m64 b) {
    asm volatile("phaddw %[b], %[a]" : [a] "+&y" (a) : [b] "y" (b));
    return a;
}
```
Observe that the templates and constraint specifiers are identical.
4. Run `zig build-obj phaddw.zig phaddw.c -lc -O ReleaseFast`
5. Dissassemble the generated object, `phaddw.o`. Observe the generated assembly:
```
<phaddw_c>:
        movdq2q mm0,xmm1
        movdq2q mm1,xmm0
        phaddw mm1,mm0
        movq2dq xmm0,mm1
        ret ;; extraneous int3 removed

<phaddw_zig>:
        movdq2q mm0,xmm1
        phaddw mm1,mm0
        movq2dq xmm0,mm1
        ret
```
Note that `phaddw_zig` generates different assembly and does not produce the desired results.

### Expected Behavior

The generated assembly should be identical in behavior.

**Comment by jacobly0** [comment]
Note that this feature provides no benefits to the optimizer over the following implementation, but I went ahead and implemented this feature anyway, to at least avoid the silent miscompile:
```zig
export fn phaddw_zig(lhs: @Vector(4, i16), rhs: @Vector(4, i16)) @Vector(4, i16) {
    return asm ("phaddw %[source], %[result]"
        : [result] "=y" (-> @Vector(4, i16)),
        : [_] "0" (lhs),
          [source] "y" (rhs),
    );
}
```
