### ISSUE TITLE
Invalid parsing of WASM linker flags

### ISSUE THREAD

**Issue by ncruces** [ziglang/zig#15258]
### Zig Version

0.11.0-dev.2546+cb54e9a3c

### Steps to Reproduce and Observed Behavior

Run:
```sh
zig cc main.c -Wl,--initial-memory=1048576
```

Output:
```
error: unsupported linker arg: --initial-memory
```

Run:
```sh
zig cc main.c -Wl,--shared-memory2
```

Output:
```
main.c:1:1: error: unable to build C object: FileNotFound
```

### Expected Behavior

The *first* linker flag, `--initial-memory`, is not recognized because an `=` is expected:
https://github.com/ziglang/zig/blob/602029bb2fb78048e46136784e717b57b8de8f2c/src/main.zig#L1962-L1973

But a previous step splits linker flags by `=`:
https://github.com/ziglang/zig/blob/602029bb2fb78048e46136784e717b57b8de8f2c/src/main.zig#L1675-L1690

Also suffering from this are: `--max-memory` and `--global-base`; `--export` works, because the alternative syntax is also accepted _here_ (there's another copy of this code where the alternative syntax is not explicitly accepted).

The *second* linker flag, `--shared-memory2`, is accepted and should be rejected. It's being compared with `mem.startsWith` and not `mem.eql`, not sure why.

**Comment by Luukdegram** [comment]
Seems the logic was copied from the `zig build-{exe/lib}` CLI frontend, which works a little differently than of `zig cc`. 

> This also similarly affects 0.10.1. Not sure what's your policy on back ports.

There will be no backport.
