### ISSUE TITLE
add a non-heap-allocating RSA implementation to the standard library

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#15274]
This code is needed for verifying real world TLS certificates:

https://github.com/ziglang/zig/blob/25e3851fe0f7fe254b48c2242ab8d4ef89165fd5/lib/std/crypto/Certificate.zig#L697-L776

https://github.com/ziglang/zig/blob/25e3851fe0f7fe254b48c2242ab8d4ef89165fd5/lib/std/crypto/Certificate.zig#L908-L915

The use of FixedBufferAllocator is a bit problematic here. Ideally we would have an implementation of this that does not heap allocate, but also does not use a giant stack slice like this one does.

Many thanks to @naoki9911 and 時雨堂 (shiguredo) for the implementation that we are borrowing for the time being :pray: 

@jedisct1 - you mentioned that you had started efforts on this. How's that proceeding? Would you like some assistance from any contributors or myself?

**Comment by jedisct1** [comment]
I have preliminary code for finite field arithmetic that doesn't allocate and is constant time. I'll do my best to finish it next week or right after Eurocrypt.

**Comment by andrewrk** [comment]
Solved in #15901.
