### ISSUE TITLE
std.json.parse unable to parse @Vector(2, f32)

### ISSUE THREAD

**Issue by nurpax** [ziglang/zig#15314]
### Zig Version

0.11.0-dev.1893+277015960

### Steps to Reproduce and Observed Behavior

std.json.parse is unable to parse @Vector fields:

```
test "json2" {
    const S = struct {
        pos: @Vector(2, f32),
        //pos: [2]f32, // this works
    };

    const s =
        \\ { "pos": [1, 2] }
    ;
    var stream = std.json.TokenStream.init(s);
    const parsedData = try std.json.parse(S, &stream, .{});
    _ = parsedData;
}
```

This issues a compile error: `error: Unable to parse into type '@Vector(2, f32)'`.  It works if I change the `pos` field to type `[2]f32`,

Maybe I'm overlooking a feature that'd allow to configure per-field parsing in the std.json library?

I can work-around by changing the field to use an f32 array, it's just that this is in a larger project where everything's using vector types.  This makes it hard to work with JSON serialization as I can't directly serialize my project's structures.

### Expected Behavior

I expected the test case to compile and run without errors.

**Comment by nurpax** [comment]
It works in the other direction, iow, there's no issue with stringify and @Vector:

```
test "json" {
    const S = struct {
        pos: @Vector(2, f32),
    };
    const e = S{ .pos = .{ 1, 2 } };

    var buf: [200]u8 = undefined;
    var fba = std.heap.FixedBufferAllocator.init(&buf);
    var string = std.ArrayList(u8).init(fba.allocator());

    try std.json.stringify(e, .{}, string.writer());
    std.debug.print("str: {s}\n", .{string.items});
}
```

**Comment by tiehuis** [comment]
This should be fairly simple to add. Here is a starting point to add support parsing arrays into vectors in json. It would be nice if the logic of parsing into slices could be shared between the two.

```diff
 lib/std/json.zig | 33 +++++++++++++++++++++++++++++++++
 1 file changed, 33 insertions(+)

diff --git a/lib/std/json.zig b/lib/std/json.zig
index 096bed8d0..3c27f5679 100644
--- a/lib/std/json.zig
+++ b/lib/std/json.zig
@@ -1389,6 +1389,11 @@ fn ParseInternalErrorImpl(comptime T: type, comptime inferred_types: []const typ
                 UnescapeValidStringError ||
                 ParseInternalErrorImpl(arrayInfo.child, inferred_types ++ [_]type{T});
         },
+        .Vector => |vecInfo| {
+            return error{ UnexpectedEndOfJson, UnexpectedToken, LengthMismatch } || TokenStream.Error ||
+                UnescapeValidStringError ||
+                ParseInternalErrorImpl(vecInfo.child, inferred_types ++ [_]type{T});
+        },
         .Pointer => |ptrInfo| {
             var errors = error{AllocatorRequired} || std.mem.Allocator.Error;
             switch (ptrInfo.size) {
@@ -1621,6 +1626,34 @@ fn parseInternal(
             }
             return r;
         },
+        .Vector => |vecInfo| {
+            switch (token) {
+                .ArrayBegin => {
+                    var r: T = undefined;
+                    var r_len: usize = @typeInfo(@TypeOf(r)).Vector.len;
+                    var i: usize = 0;
+                    var child_options = options;
+                    child_options.allow_trailing_data = true;
+                    errdefer {
+                        // Without the r.len check `r[i]` is not allowed
+                        if (r_len > 0) while (true) : (i -= 1) {
+                            parseFree(vecInfo.child, r[i], options);
+                            if (i == 0) break;
+                        };
+                    }
+                    while (i < r_len) : (i += 1) {
+                        r[i] = try parse(vecInfo.child, tokens, child_options);
+                    }
+                    const tok = (try tokens.next()) orelse return error.UnexpectedEndOfJson;
+                    switch (tok) {
+                        .ArrayEnd => {},
+                        else => return error.UnexpectedToken,
+                    }
+                    return r;
+                },
+                else => return error.UnexpectedToken,
+            }
+        },
         .Array => |arrayInfo| {
             switch (token) {
                 .ArrayBegin => {
```

**Comment by nurpax** [comment]
Thanks for help @tiehuis!

I sent a PR that uses the above change + adds parseFree path and a test.  I'm not sure in which situation `parseFree` would be called on a `@Vector` but according to docs they can contain pointers, so maybe it's possible.

I tried thinking of a way to merge the `.Array/.Vector` paths in the parse but all I could come up with was splitting this stuff into a separate function but IMO that'd make the code harder to read.  But I can explore that option if you think this change is worth making.

**Comment by daurnimator** [comment]
> I tried thinking of a way to merge the `.Array/.Vector` paths in the parse

Could you just turn the current `.Array` into `.Array, .Vector`?

**Comment by nurpax** [comment]
It's re-using the same array parsing code now: https://github.com/ziglang/zig/pull/15319/files - IMO it's pretty clean as it is.

I'm not sure what you mena by "turn current `.Array` to `.Array, .Vector`.  I'm not sure how to merge the switch-case as the capture group (`|arrayInfo|`, `|vecInfo|`) are not the same type.  In addition, the `.Array` path has handling for a `String` token whereas the `.Vector` path checks only `ArrayBegin`.
