### ISSUE TITLE
libc on mingw support

### ISSUE THREAD

**Issue by emekoi** [ziglang/zig#1532]
i'm on windows using mingw-w64. zig works fine until i try to link libc, then i get `unable to determine windows sdk path`. i'm building with `zig build-exe basic.zig --target-os windows --target-arch x86_64 --target-environ gnu --library c`.

**Comment by emekoi** [comment]
is the main in the hello_libc example the main in c or is it "wrapped" by the main in bootstrap.zig?

**Comment by andrewrk** [comment]
Zig supports both ways of doing it. `hello_libc` shows an example where libc main function is exported directly. If you use `pub fn main()` then zig puts the `extern fn main` in bootstrap and calls your pub fn main.

**Comment by emekoi** [comment]
okay i'm trying to add libc support, and i;m running into this error. zig can identify where the libc headers are but during linking (i think it's during linking) the compiler segfaults. when i run it in gdb zig panics [here](https://github.com/emekoi/zig/blob/7a8c96070bbe0bd8d909adbfbb7164837f61e06e/src/analyze.cpp#L4605) instead of printing out the search paths like it does outside gdb.

**Comment by andrewrk** [comment]
without gdb, try `--verbose-link`. Does it print the linker line it's using?

**Comment by emekoi** [comment]
no, it just segfaults.

**Comment by emekoi** [comment]
https://bugs.llvm.org/show_bug.cgi?id=40568
