### ISSUE TITLE
Building Zig From Source - Add minimum memory requirements

### ISSUE THREAD

**Issue by ltenfield** [ziglang/zig#15321]
### Zig Version

all

### Steps to Reproduce and Observed Behavior

within [Building Zig From Source](https://github.com/ziglang/zig/wiki/How-to-build-LLVM,-libclang,-and-liblld-from-source#posix) I would like to know minimum requirements to build on my own machine like architecture (x84_64) and physical memory required and possibly recommended or tested linux version like Ubuntu release.

Thanks

### Expected Behavior

Build not seg faulting due to lack of memory... a user was asking why build was seg faulting an he only had 6G of ram taken from https://discord.com/channels/605571803288698900/1097196156901138482

**Comment by ltenfield** [comment]
It turns out that the user requesting build help could build zig with only 8G of physical memory using downloaded LLVM binaries. I assumed you needed at least 16G of physical memory.... I learned something during the process :-)

**Comment by zhaozg** [comment]
16G is not enough, fail in my 16G MBP too

**Comment by andrewrk** [comment]
It's about 4G peak RSS.

This is not a bug tracker for the wiki.
