### ISSUE TITLE
x86_64 self-hosted backend behavior tests are failing on Windows

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#15324]
Zig Version: `0.11.0-dev.2634+b0186f310`

I apologize for misplacing the CI error logs for this bug report, but one can observe them by opening a pull request with these lines deleted:

https://github.com/ziglang/zig/blob/b0186f31002760c9940d8c06c2ac7baa9d52f404/test/tests.zig#L945-L951

Until this issue is resolved, the CI does not provide test coverage for the x86_64 self-hosted backend on Windows.

**Comment by jacobly0** [comment]
Reenabled in #15302 on the off chance that it fixes the issue, otherwise will investigate further.
