### ISSUE TITLE
std.zig.Client: add support code for parsing zig.Server messages

### ISSUE THREAD

**Issue by perillo** [ziglang/zig#15374]
Commit c96cb98ad says that: "This use case is now handled instead by the --listen option".

I just had to use the Zig IPC in https://github.com/ratfactor/ziglings/blob/main/build.zig, and I noted that parsing the server messages is not trivial.

I propose that `std.zig.Client` should define the parsing functions for all non trivial messages.

Currently Zig IPC is only used in the Build system; the use in the Ziglings project is probably a very special case.
However I still think that there should be more support in the standard library.

Thanks.

**Comment by andrewrk** [comment]
This issue is vague.
