### ISSUE TITLE
Proposal : get rid of null value

### ISSUE THREAD

**Issue by stefanusayudha** [ziglang/zig#15386]
I just thought about it, but if this sounds fools please be easy on it.

if null causing null pointer error why won't we just get rid of "null" and replace null value with "null exception"

there is some mathematic idea says that 0 supposed tobe not exist.. the theory is naturalism or constructivism.. but im talking about null, refer to this idea sounds similar to me.. 

in modern language some are using "?" as null safety operation..

what if we just get rid of null, replace it with unset exception, and use "?" for exception safety..

imagine how easy this world by not having null and have exception safety operation..

you can do like:

const number= getNumber() ?: { e -> do_something ; return 0 }

for whatever it throws..

**Comment by silversquirl** [comment]
`?` in zig means "optional" - it's not just "null safety", it's a way of saying "there might be something here, or not" and it applies to everything, not just pointers.
Zig doesn't have a concept of exceptions, so "exception safety" doesn't really make much sense.

**Comment by stefanusayudha** [comment]
sorry im new in this , i didn't know..

maybe this idea will make more senses with other nonsense languages 😂 ✌️

I'll try to up this in java 😂✌️
