### ISSUE TITLE
Why is target.os.tag not windows when building windows DLL?

### ISSUE THREAD

**Issue by neeraj9** [ziglang/zig#15396]
Looking at the change https://github.com/ziglang/zig/pull/15378, I wonder whether we did the right thing? If the issue was specifically for windows then target.os.tag != windows should have solved that because the target is indeed windows where the build failure happens. Shouldn't we be checking why `target.os.tag` not detected as `windows` for windows DLL in the first place (as per the change https://github.com/ziglang/zig/pull/15378)?

https://github.com/ziglang/zig/blob/4374ce51b0ffdaa317b6678d6622ecb88877f7f9/src/target.zig#L207

For reference, I noticed that there was a discussion on discord around the following issue on windows operating system.

```shell
zig cc --target=x86_64-uefi main.c
zig: error: unsupported option '-fPIC' for target 'x86_64-unknown-windows-msvc'
```

**Comment by neeraj9** [comment]
There is a similar discussion, which started in July 2020 - https://github.com/ziglang/zig/issues/5935. I don't see any action on that, while this change went it. There is a nice documentation around `*-unknown-uefi` targets on rust-lang (https://doc.rust-lang.org/rustc/platform-support/unknown-uefi.html).

**Comment by andrewrk** [comment]
target.os.tag is windows when building a Windows DLL. the code you linked to is whether or not clang accepts `-fPIC`:

```
/// This is not whether the target supports Position Independent Code, but whether the -fPIC
/// C compiler argument is valid to Clang.
pub fn supports_fpic(target: std.Target) bool {
```
