### ISSUE TITLE
build compiler on mingw

### ISSUE THREAD

**Issue by emekoi** [ziglang/zig#1540]
is zig tested regularly on mingw(-w64), or is it known to compile successfully there?

**Comment by andrewrk** [comment]
We used to test building for mingw in the CI, but the mingw llvm packages were outdated for too long, and I was unable to build LLVM and libclang from source with mingw. This will eventually be solved by #853

**Comment by emekoi** [comment]
i've gotten it to compile but is doesn't work in the console (exits with exit code 127) or gdb (exits with error code 0xc0000139 before main is even run); however it will open in cmd and git bash but it will segfault when i try to run the tests or compile anything.

**Comment by andrewrk** [comment]
Yeah. At this point, only builds with msvc are supported. It would be nice to add mingw support but it was too hard to test, since the packages didn't have the latest llvm version, and building llvm from source didn't work.

**Comment by monouser7dig** [comment]
if building llvm with mingw did not work because of timeouts we could fix this with 
https://github.com/ziglang/zig/issues/835#issuecomment-421419012 , if its because of some other issue then this would not help obviously (quick closed-issue search did not reveal anything).

**Comment by emekoi** [comment]
huzzah! the problem was that zig was loading the wrong dll (dlls from qemu) instead of the ones from mingw. now i can work on that segfault...

**Comment by emekoi** [comment]
ok this is weird but the first time i run the compiler it segfaults but after that it starts giving proper error messages...

**Comment by andrewrk** [comment]
I wonder if that's trying to compute the compiler id. Try wiping `~/.local/share/zig/stage1/` and then running `zig id`.

**Comment by emekoi** [comment]
that worked but now i have to rebuild because of *reasons*.

**Comment by emekoi** [comment]
it works!!! now i just need to run the test suite....

**Comment by andrewrk** [comment]
> which tests depend on linking to libc?

Here's an example to test libc detection:

```
$ ./zig build-exe ../example/hello_world/hello_libc.zig --library c
$ ./hello
Hello, world!
```

**Comment by emekoi** [comment]
no i mean which **don't** link to libc. as zig is now it doesn't support linking to libc on mingw so i **can't**  run these tests. or is there a way to keep the test harness running if some tests fail?

**Comment by andrewrk** [comment]
````
./zig test ../test/behavior.zig
./zig test ../std/index.zig
```

That covers most stuff without depending on libc. We could also add a flag to the main test command that would exclude libc stuff.

**Comment by emekoi** [comment]
does zig need to link to compiler-rt? or does it **only** link to libLLVM, libclang, and libLDD?

**Comment by andrewrk** [comment]
It only links to libLLVM and libclang.

 LDD is source-embedded in zig and compiler rt is built lazily from zig source for the target.

**Comment by emekoi** [comment]
so i **don't** need libssp, libcxx, etc.?

**Comment by andrewrk** [comment]
I'd be happy to look at a paste of errors that you're getting if you're having trouble. Zig only depends on a c++ compiler, libclang, and libllvm.

**Comment by emekoi** [comment]
it's not that i'm getting errors building zig, it's that i;m building the llvm 7 tool chain from scratch so i can use the most recent version on zig. i was having problems with getting compiler-rt to compile so i thought it best to ask if was actually needed.

**Comment by emekoi** [comment]
currently, elf format is chosen as the default on mingw if you built llvm from source.
