### ISSUE TITLE
Runtime chars allowed in comptime-only `++`, producing wrong result

### ISSUE THREAD

**Issue by erikarvstedt** [ziglang/zig#15429]
### Zig Version

0.11.0-dev.2725+4374ce51b

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

fn makeStr(char: u8) []const u8 {
    return "----" ++ .{char};
}

pub fn main() !void {
    std.debug.print("{s}\n", .{makeStr('a')});
}
```
Running this produces output `"\x00\x00--a"` (instead of `"----a"`).

### Expected Behavior

Zig should fail with an error.
When concatenating a runtime string (`[]const u8`) , Zig correctly fails with error `slice value being concatenated must be comptime-known`.

**Comment by mlugg** [comment]
Concatenations of runtime-known arrays are allowed provided the *lengths* are comptime-known (which they are here). The problem is, since the value is runtime-known, it's stored on the stack, so is clobbered when the function returns, meaning you print garbage data.
