### ISSUE TITLE
Compiler panic when allocating an enum with a single field

### ISSUE THREAD

**Issue by recursivetree** [ziglang/zig#15424]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

```zig
test "compiler crash"{
    const Enum = enum{A};
    const slice = try std.testing.allocator.alloc(Enum,10);
    defer std.testing.allocator.free(slice);
}
```
results in
```
/usr/local/Cellar/zig/0.10.1/lib/zig/std/mem/Allocator.zig:282:27: error: alignment must be >= 1
) Error![]align(alignment orelse @alignOf(T)) T {
                ~~~~~~~~~~^~~~~~~~~~~~~~~~~~
thread 10545316 panic: Zig compiler bug: attempted to destroy declaration with an attached error
Unable to dump stack trace: debug info stripped
error: test...
error: The following command terminated unexpectedly:
/usr/local/Cellar/zig/0.10.1/bin/zig test /Users/yuri/Documents/schule/maturacpu/movemachine/assembler2/src/main.zig --cache-dir /Users/yuri/Documents/schule/maturacpu/movemachine/assembler2/zig-cache --global-cache-dir /Users/yuri/.cache/zig --name test --enable-cache 
error: the following build command failed with exit code 6:
/Users/yuri/Documents/schule/maturacpu/movemachine/assembler2/zig-cache/o/0c6f026c6e653bb4bee08689f8029211/build /usr/local/Cellar/zig/0.10.1/bin/zig /Users/yuri/Documents/schule/maturacpu/movemachine/assembler2 /Users/yuri/Documents/schule/maturacpu/movemachine/assembler2/zig-cache /Users/yuri/.cache/zig test

```
it can also be reproduced in main using another allocator, so it isn't just limited to the testing allocator. Try to allocate `void` results in the same thing

### Expected Behavior

The error probably comes from `@sizeOf(Enum)` being 0. That makes sense, because an enum with just one possibility can be optimized away.

I expect it to at least throw a normal compiler error instead of just crashing. This could be if an enum has less than two possibilities or if we try to allocate a type with a size of 0.

**Comment by recursivetree** [comment]
I just installed a 0.11.0-dev compiler. It seems like the crash is fixed there, but the compiler error is still a bit confusing:
```
build/stage3/lib/zig/std/mem/Allocator.zig:202:27: error: alignment must be >= 1
) Error![]align(alignment orelse @alignOf(T)) T {
                ~~~~~~~~~~^~~~~~~~~~~~~~~~~~
build/stage3/lib/zig/std/mem/Allocator.zig:296:45: error: access of union field 'Pointer' while field 'ErrorUnion' is active
    const Slice = @typeInfo(@TypeOf(memory)).Pointer;
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
build/stage3/lib/zig/std/builtin.zig:203:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
```

**Comment by recursivetree** [comment]
My error, I forgot to insert `try`. That somehow fundamentally changes the reported error

**Comment by mlugg** [comment]
Allocating zero-bit types ought to work okay, and should just return `&.{}`. This is actually implemented, but the alignment stuff prematurely breaks it. The fix should be pretty trivial (replace `@alignOf(T)` with `@max(@alignOf(T), 1)`).

**Comment by recursivetree** [comment]
it is not as trivial as just using `@max(@alignOf(T), 1)` in the function where it crashes. There are more errors in std.mem that appear when doing it.

I've been wondering whether it even makes sense to have an align of 0. An alignment of 1 mean you can store it in every position, alignment 2 means every second position, etc. But what does alignment 0 mean? Without being an expert at it, types with a size of 0 should work with alignment 1 too.

**Comment by Vexu** [comment]
There is a proposal for changing that #7221
