### ISSUE TITLE
[MachO] requires dsymutil for DWARF symbols

### ISSUE THREAD

**Issue by motiejus** [ziglang/zig#15439]
Currently we cannot compile CGo programs to MacOS (at least x86_64) with default settings:

- linker arg `-no_pie` is discussed in #15438.
- DWARF generation: this issue.

### main.go

```
package main

// #include <stdio.h>
// char* hello() { return "hello, world"; }
// void phello() { printf("%s\n", hello()); }
import "C"

func main() {
        C.phello()
}

func Chello() string {
        return C.GoString(C.hello())
}
```

### Compile to MacOS

```
$ CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 CC="zig cc -target x86_64-macos-none" go build -ldflags=-buildmode=pie .
# example.com/x
/usr/local/go/pkg/tool/linux_amd64/link: /usr/local/go/pkg/tool/linux_amd64/link: running dsymutil failed: exec: "dsymutil": executable file not found in $PATH
```

We can make it work by adding `-w` to the linker flags:

```
$ go tool link -h |& grep -- -w
  -w    disable DWARF generation
$ CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 CC="zig cc -target x86_64-macos-none" go build -ldflags="-w -buildmode=pie" .
$ file ./x
./x: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
```

**Comment by kubkon** [comment]
This is a GO issue and not Zig's in assuming there is a `dsymutil` binary in the PATH which generally is not the case on non-native hosts.

**Comment by motiejus** [comment]
Oh wow, I was quite sure I saw zig exec'ing that command, not Go. Sorry!

**Comment by kubkon** [comment]
> Oh wow, I was quite sure I saw zig exec'ing that command, not Go. Sorry!

No problem. As a heads up, I want to implement `dsymutil`'s functionality as part of Zig's linker toolchain in the future.
