### ISSUE TITLE
Does exists zig build -h ?

### ISSUE THREAD

**Issue by miepian** [ziglang/zig#15432]
-h is General Options,Print command-specific usage
exists zig test -h, but zig build -h output :

info: Initialize a 'build.zig' template file with `zig init-lib` or `zig init-exe`,
or see `zig --help` for more options.
error: No 'build.zig' file found, in the current directory or any parent directories.

zig version:

0.11.0-dev.2750+c4a63389e

**Comment by mlugg** [comment]
The `zig build` help output is customized per-project to include the options and steps available in that `build.zig`; therefore, a valid `build.zig` is necessary for its `-h`/`--help` option to work.

**Comment by miepian** [comment]
That's true,thank you for your answer
