### ISSUE TITLE
Make switch support optional types

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#1545]
`switch` really should support optional types.

- [ ]  Make `switch` accept optional types, mapping `null` to `else`
- [ ] Allow mapping a `null` optional to `null` case, but defaulting to `else` if `null` is not specified

**Comment by monouser7dig** [comment]
can you do an example what it should look like vs what is currently required to do the same. e.g. If else? 
I don't really see how this is easier than if else at the moment, although the proposal in itself sounds as if it would not introduce complication and would make some sense maybe still.

**Comment by raulgrell** [comment]
Switch is a similar construct to `if` and `while` that already have support for this. The switch should either have to cover all cases including null, or have an else branch.

```
fn getPrintableChar(?u8) -> u8 {
    switch(maybe_byte) {
        0, 32...255 => | b | return b, // handle maybe_byte != null and printable
        else => return 32, // maybe_byte != null and non-printable
        null => return 0,    // handle maybe_byte == null
    }
}
```

On the other hand, when using nullables, those structures have a `|name|` to visually denote that it is unwrapping a null. With this in mind, the syntax I'd expect for this switch would be:

```
fn getPrintableChar(?u8) -> u8 {
    switch(maybe_byte) | b | {
        // handle maybe_byte != null
        0, 32...255 => return b,
        else => return 32, // print space instead of char
    } else {
        // handle maybe_byte == null
        return 0;   
    }
}
```

What about errors? 

```
fn getPrintableChar(?u8) -> !u8 {
    switch(tryReadByte()) | b | {
        0, 32...255 => return b,
        else => return 32,
    } else | err | {
        return error.IOError;   
    }
}
```

**Comment by shawnl** [comment]
@monouser7dig It is currently very hard to map null and the else of the switch to the same block, which this would fix.

@raulgrell I was thinking the first, and not having switch handle errors.

**Comment by raulgrell** [comment]
My only concern with the first method is if maybe_byte comes from a function, and you change its signature to return a nullable, the null will get silently handled by the switch's else clause and we might not address the nullable case properly.

With the alternative syntax, the compiler would report a missing else branch on the `switch`.

**Comment by binary132** [comment]
I like the Rust syntax where the optional type is not unpacked by the switch, and instead you need to match on the real value, such as `Some(0)` or `None`.

That syntax could also be usable for sum types if those are ever planned to be added by matching on, for instance, `Ok(val)` or `Err(msg)`.

**Comment by andrewrk** [comment]
I don't think this is compelling enough to increase the size of the language. I would definitely want to see some examples where the existing constructs are insufficient before reconsidering this.

**Comment by tcoratger** [comment]
Another example here, in order to replicate the following Rust pattern, it is quite cumbersome in terms of `if`/`else if`/`else`, which makes the Ziglang implementation quite confusing and difficult to debug:

```rust
match (
    get_segment(lhs.segment_index).and_then(|s| s.get(lhs.offset..)),
    get_segment(rhs.segment_index).and_then(|s| s.get(rhs.offset..)),
) {
    (Some(lhs), Some(rhs)) => {
        let (lhs_len, rhs_len) = (lhs.len().min(len), rhs.len().min(len));
        if lhs_len != rhs_len {
            return false;
        }
        lhs[..lhs_len] == rhs[..rhs_len]
    }
    (None, None) => true,
    _ => false,
}
```

**Comment by mlugg** [comment]
Here is equivalent code written in IMO a cleaner form:
```zig
const op = self.next_token().get_binary_operator() orelse return error.IllegalLetAssign;
if (op != .assign) return error.IllegalLetAssign;
_ = self.next_token();
return .{
    .alloc = allocator,
    .node = .{ .definition = .{
        .variable = .{
            .identifier = ident,
            .mutable = mut,
            .expression = try self.parse_expression(allocator, 0),
        },
    } },
};
```

**Comment by adabarx** [comment]
That does look better. This is my first Zig project. Thanks!

**Comment by tristanpemble** [comment]
with labeled switch continues, this might help increase readability for loops where the next discriminant is the result of an optional;

```zig
blk: if (stack.pop()) |s| {
    sw: switch (s) {
        .some_state => {
            continue :sw stack.pop() orelse break :blk;
        },
    }
}
```

or

```zig
if (stack.pop()) |s| sw: switch (s) {
    .some_state => {
        if (stack.pop()) |s| {
            continue :sw s
        }
    },
}
```

vs

```zig
sw: switch (stack.pop()) {
    .some_state => {
        continue :sw stack.pop();
    },
    null => {},
}
```

which might not seem like a huge deal except that you are going to be copying that conditional continue around quite a lot in VMs, parsers, etc.

of course I could create an `OptionalState` enum with a `.none`, but then I have to copy the full set of states in two places (I think?)

**Comment by tristanpemble** [comment]
responding to my past self with knowledge gained in the span of 8 hours.

> which might not seem like a huge deal except that you are going to be copying that conditional continue around quite a lot in VMs, parsers, etc.
>
>of course I could create an OptionalState enum with a .none, but then I have to copy the full set of states in two places (I think?)

`.none` might not make sense, but there is probably a value that does. in this case, refactor your state machine to support `.eof` or some other kind of terminating state, and return `.eof` when popping from an empty stack. I don't know if exists a case where this is non-ideal.
