### ISSUE TITLE
zig fmt does not handle shebang lines

### ISSUE THREAD

**Issue by tiehuis** [ziglang/zig#1546]
This should be handled at the parser level.

```
#!/bin/zig

pub fn main() void {
    const a = 5;
}
```

```
$ zig2 fmt t.zig 
t.zig:1:1: error: Expected variable declaration or function, found Invalid
#!/bin/zig
~
```

**Comment by andrewrk** [comment]
> This should be handled at the parser level.

I started looking at this, and it seemed easiest to create Token.ShebangLine. It would only show up if the first 2 bytes of the file were `#!`, and it could only be the first token, and would be guaranteed to only show up once total.

Do you think I shouldn't do it this way?

**Comment by andrewrk** [comment]
I went ahead and did it since this is better than status quo, but feel free to change the implementation if you have a better way.

**Comment by tiehuis** [comment]
This solution is good. Easy for external users when using `std/zig`.
