### ISSUE TITLE
Ability to inline a noinline function call

### ISSUE THREAD

**Issue by wrongnull** [ziglang/zig#15489]
### Zig Version

0.11.0-dev.2837+b55b8e774

### Steps to Reproduce and Observed Behavior

```zig
noinline fn dummy() u32 {
    return 0;
}

pub fn main() void {
    _ = @call(.always_inline, dummy, .{});
}
```

### Expected Behavior

Compiler error

**Comment by likern** [comment]
I'm wondering what is the reason to have inline/noinline in function declaration at all?

**Comment by mlugg** [comment]
> I'm wondering what is the reason to have inline/noinline in function declaration at all?

`inline` is important not just as a hint to the optimizer (although that is a good use case), but also as a semantic improvement: explicit inlining happens during semantic analysis, so comptime-known parameters to inline functions become comptime-known in the function body, which can be useful for better optimization and better errors. It's also how you write a fully comptime-only function:
```
inline fn comptimeOnly() u32 {
    comptime {
        var x: u32 = 0;
        // do some stuff
        return x;
    }
}
```

`noinline` is rarer to see, but is useful for debugging (to make sure LLVM doesn't make your life harder), and I imagine for some low-level stuff where you need to make sure a function stays separate.

**Comment by kcbanner** [comment]
`noinline` is also used in debug.zig in std, so that stack walking functions can reliably know how many frames to go back.
