### ISSUE TITLE
Add support for wasm32-wasi-threads

### ISSUE THREAD

**Issue by theoparis** [ziglang/zig#15484]
See https://github.com/WebAssembly/wasi-sdk/pull/274
![image](https://user-images.githubusercontent.com/11761863/234816209-f87538c6-0fbe-45d2-a6bd-181b347aac1f.png)

I tried building something that requires cmake and pthreads and it failed to compile with `zig;cc` as the compiler and wasm32-wasi. If I try to use the `wasm32-wasi-threads` target I get this:
```
error: UnknownApplicationBinaryInterface
```

**Comment by jakehemmerle** [comment]
> Are WebAssembly threads supported in browsers?

It looks like Wasm threads have been [supported in major browsers](https://webassembly.org/roadmap/) for a year or two now.

Be aware, there are two Wasm threading specs to be aware of: [Threads and Atomics] (which is in phase3/5 for the *core* Wasm spec), and [wasi-threads] (which is phase 1/5 for the WASI spec).

What's the difference? wasi-threads intro explains:

> That [Threads and Atomics] proposal provides the primitives necessary for shared memory, atomic operations, and wait/notify. This [wasi-threads] proposal solely provides a mechanism for spawning threads. Any other thread-like operations (thread joining, locking, etc.) will use primitives from the [Threads and Atomics] proposal.
>
> Some background: browsers already have a mechanism for spawning threads — [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) — and the [Threads and Atomics] proposal avoided specifying how thread spawning should occur. This allows other uses of WebAssembly — i.e., outside the browser — to specify their own mechanism for spawning threads.

---

Regarding support for wasi-threads: `wasmtime` seems to be the defacto Wasm runtime and it indicates both [full support for Threads and Atomics](https://docs.wasmtime.dev/stability-wasm-proposals-support.html) and [full support for wasm-threads](https://docs.wasmtime.dev/stability-wasi-proposals-support.html).

[Threads and Atomics]: https://github.com/WebAssembly/proposals#active-proposals
[wasi-threads]: https://github.com/WebAssembly/WASI/blob/main/Proposals.md

**Comment by andrewrk** [comment]
Done:
* #16207
* #16439
