### ISSUE TITLE
`@atomicRmw` on u0

### ISSUE THREAD

**Issue by Hejsil** [ziglang/zig#1549]
Under `@atomicRmw` we have "TODO right now bool is not accepted. Also I think we could make non powers of 2 work fine, maybe we can remove this restriction". If `@atomicRmw` where to work on `u0`, then one could write code that is optionally threadsafe without a lot of special casing.

```
const Lock = if (is_thread_safe) u1 else u0;
const Locked = if (is_thread_safe) 1 else 0;
const Unlocked = 0;

var lock: Lock = Unlocked;
...
// Do @atomicRmw on lock. @atomicRmw will be no-ops on `u0`
```

Idk if this is a good idea. Maybe `@atomicRmw` should never be no-op because that might be confusing with its description "This builtin function atomically modifies memory and then returns the previous value.". `u0` has no memory to modify.

Related: #1530

**Comment by BarabasGitHub** [comment]
I don't see the issue here. It'll write zero and read zero, so it doesn't
have to do anything. It just doesn't have any effect.

Op di 18 sep. 2018 08:24 schreef kristopher tate <notifications@github.com>:
