### ISSUE TITLE
Are we game/web yet sections in Readme/site

### ISSUE THREAD

**Issue by rishavs** [ziglang/zig#1550]
Can we consider adding a "Are we game yet" and a "Are we Web yet" sections in our readme and site.

This is something that Rust does and helps the occasional lurkers to better gauge the current state of language. 
eg.
https://www.arewewebyet.org/
http://arewegameyet.com/

It will also allow someone like me who is not following Zig development very closely, decide on the best time to try out the language seriously.

**Comment by kristate** [comment]
@rishavs Thank-you for your first post to the zig community! We are currently trying to get release 0.3.0 out the door by the end of this month. 0.3.0 has removed many bugs from the language, so gradually we will be able to onboard more users with content like *are we game yet*. Thanks!

**Comment by rishavs** [comment]
@kristate thanks! I will be keeping and eye out for the 3.0 release.

**Comment by andrewrk** [comment]
I moved this issue to www.ziglang.org repo
