### ISSUE TITLE
[question] std.mem.ArrayList.toOwnedSlice

### ISSUE THREAD

**Issue by emekoi** [ziglang/zig#1552]
is the slice obtained by `std.mem.ArrayList.toOwnedSlice` backed by the heap and not calling `std.mem.Allocator.free` on it a memory leak?

**Comment by BarabasGitHub** [comment]
Yes. That's why it's `Owned`.

**Comment by andrewrk** [comment]
In case you didn't see it, there is also `toSlice()` and `toSliceConst()` which do not obtain ownership.
