### ISSUE TITLE
mem.eql() crashes in ReleaseSafe if arg is 'undefined'

### ISSUE THREAD

**Issue by isrvoid** [ziglang/zig#15527]
### Zig Version

0.11.0-dev.2932+91b472996

### Steps to Reproduce and Observed Behavior

The minimized example crashes on x86_64 Linux in ReleaseSafe and ReleaseFast builds. Similar code snippets in a larger program seemed to corrupt local variables without crashing (not demonstrated here).
```
const std = @import("std");
const print = std.debug.print;

const Cache = struct {
    s: [1]u8 = undefined, // 'undefined' is required for the issue to occur
};

pub fn main() void {
    print("main() start\n", .{}); // when removed, changes error output in ReleaseSafe

    var last_processed = Cache{};
    const token = "a";
    if (!std.mem.eql(u8, &last_processed.s, token))
        print("using '{s}'\n", .{token});
}
```
steps:
copy example into `main.zig`
`$ zig build-exe -O ReleaseSafe main.zig`
`$ ./main`

output:
```
main() start
thread 4795 panic: reached unreachable code
Aborted (core dumped)
```

### Expected Behavior

Expected output:
```
main() start
using 'a'
```

**Comment by nektro** [comment]
comparing against a value that is `undefined` is illegal and considered [Undefined Behavior](https://ziglang.org/documentation/master/#Undefined-Behavior). You may instead be looking for [Optionals](https://ziglang.org/documentation/master/#Optionals)

**Comment by Vexu** [comment]
Strange stuff happening is the expected result of combining undefined and LLVM optimizations.

**Comment by isrvoid** [comment]
The ref kind of implied, the memory would still be there but contain whatever. The UB definition makes sense. Thank you!
