### ISSUE TITLE
std.fmt escape sequences do not include curly brackets

### ISSUE THREAD

**Issue by rseichter** [ziglang/zig#15532]
### Zig Version

0.11.0-dev.2892+fd6200eda

### Steps to Reproduce and Observed Behavior

This is not technically a bug, because the documented [escape sequences](https://ziglang.org/documentation/master/#Escape-Sequences) do not include curly brackets, so it works as designed. However, I see no convenient means for the user to include left curly bracket `{` (Unicode U+007B) and right curly bracket `}` (Unicode U+007D) in format string literals:
```
src/main.zig:19:34: error: invalid escape character: '{'
    std.debug.print("Usage: {s} \{verb\}\n", .{somestring});
                                 ^~~~~~~~~~
```
One can look up the necessary Unicode codes on the Internet, like I did, but that is cumbersome.

### Expected Behavior

I intuitively expected `\{` and `\}` to be included in the escape sequences set, but that is not the case.

**Comment by IntegratedQuantum** [comment]
> I see no convenient means for the user to include left curly bracket { (Unicode U+007B) and right curly bracket } (Unicode U+007D) in format string literals

You can escape them with `{{` or `}}`.

**Comment by rseichter** [comment]
@IntegratedQuantum Thank you. Is this documented somewhere, and have I just been too blind to find the reference?

**Comment by IntegratedQuantum** [comment]
It's not really mentioned in an obvious place.
All the formatting related information seems to be only available in this doc comment:
https://github.com/ziglang/zig/blob/35d82d31be3d2f2611049f41dc2616f898d70871/lib/std/fmt.zig#L29-L78

(You can also find this nicely formatted [in the std documentation](https://ziglang.org/documentation/master/std/#A;std:fmt.format) or when you hover over it with zls)

**Comment by rseichter** [comment]
@IntegratedQuantum The documentation includes the text "To print literal curly braces, escape them by writing them twice, e.g. {{ or }}.", so it _is_ documented at least. I wish I had found this mentioned earlier, so as not to cause unnecessary bother. Sorry.
