### ISSUE TITLE
zig fmt: Add test mode which does not modify files

### ISSUE THREAD

**Issue by xtian** [ziglang/zig#1555]
`zig fmt` should have a flag which causes the command to not modify the files in place and instead simply output which files are incorrectly formatted and exit with a non-zero return code.

If this flag is not provided, `zig fmt` should not produce any output when parsing and formatting complete successfully.

This is standard behavior in all the formatters that I have experience with and is needed to check formatting in a CI or test context:

* `elm-format --validate`
* `mix format --check-formatted`
* `prettier --list-different`
* `rustfmt --check`

Happy to work on a PR for these changes if you think they’re a good idea! :)

**Comment by andrewrk** [comment]
Makes sense. I think the implementation should be straightforward since we already detect changes and output which files end up being changed, so to implement this new mode shouldn't have to solve any new problems.

**Comment by binary132** [comment]
fwiw, the Go formatting tool defaults to output to stdout, and only edits files in-place if asked to.

**Comment by andrewrk** [comment]
`zig fmt --stdin` can be used to operate on stdin/stdout. By default there can be any number of positional arguments, and if any of them are directories then they are scanned recursively.
