### ISSUE TITLE
`use void;` crashes compiler

### ISSUE THREAD

**Issue by emekoi** [ziglang/zig#1557]
i had a struct with a function called `new` to create a new instance of it. the struct had a member that was of a type that didn't exist. the compiler would crash due to an assertion error in `assertNoError`.

**Comment by andrewrk** [comment]
Can you come up with a small test case to reproduce the behavior? Or is your project open source, and can you make a branch for me to check out with instructions on how to cause the crash?

**Comment by emekoi** [comment]
i'll see what i can do.

**Comment by andrewrk** [comment]
I have reduced your test case to 9 bytes :-)

```zig
use void;
```
