### ISSUE TITLE
zig build test doesn't run tests

### ISSUE THREAD

**Issue by tisonkun** [ziglang/zig#15586]
### Zig Version

0.11.0-dev.2969+855493bb8

### Steps to Reproduce and Observed Behavior

1. Check out branch https://github.com/korandoru/zig-uuid/pull/2
2. Run `zig build test`

No tests run. Even if I change assertion to false, the command exit with 0 silently.

### Expected Behavior

Run tests as 0.10.1.

**Comment by tisonkun** [comment]
@leecannon Thanks for your quick response! Now the test step is active.

Although, the manner is a bit different from before:

```
$ zig build test
All 4 tests passed.
```

.. while now

```
$ zig build test
# silent succeed
```

Its appearance doesn't differ from no test to run.

**Comment by leecannon** [comment]
That is another change that happened during the build runner re-write, on success it prints nothing.
You can output a summary with `zig build test -fsummary` which will show the number of successful tests.

**Comment by tisonkun** [comment]
That is what expected. Thank you :D

Closing...

**Comment by KilianHanich** [comment]
This actually makes me have one question: Why would one want to create test executables without also linking them up to a run step?

Or why would one want to create multiple run steps for a single test executable?

**Comment by alexrp** [comment]
> This actually makes me have one question: Why would one want to create test executables without also linking them up to a run step?

It's a reasonable thing to do if you have a `check` step or `-Dno-bin` option that only performs semantic analysis without doing codegen.
