### ISSUE TITLE
miss paths.h sys/paths.h for macos.

### ISSUE THREAD

**Issue by zhaozg** [ziglang/zig#15606]
### Zig Version

0.11.0-dev.3000+d71a43ec2

### Steps to Reproduce and Observed Behavior

user `zig cc --target=x86_64-macos-none` build libuv.
get error message

```
/Users/zhaozg/work/portable/libuv/src/unix/process.c:40:11: fatal error: 'paths.h' file not found
# include <paths.h>
          ^~~~~~~~~
1 error generated.
make[6]: *** [luv.dir/libuv/CMakeFiles/uv_a.dir/src/unix/process.c.o] Error 1
```

do `fd paths.h` in `/usr/local/lib/zig`, not found any paths.h for macos.

copy files `usr/include/paths.h` and `usr/include/sys/paths.h` in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk to `/usr/local/lib/zig/libc/include/any-macos-any`, build passed.

### Expected Behavior

Include missed `paths.h` file in zig libs for macos.

**Comment by nektro** [comment]
cc @kubkon
