### ISSUE TITLE
improve compile error for the mistake of using &&/|| instead of and/or

### ISSUE THREAD

**Issue by emekoi** [ziglang/zig#1560]
the title speaks for itself.

**Comment by thejoshwolfe** [comment]
what's the code that causes this error?

**Comment by emekoi** [comment]
[here](https://github.com/emekoi/ziglet/blob/master/src/input.zig#L216).

**Comment by emekoi** [comment]
yikes. i'll make sure to read the docs next time i get an issue like this.

**Comment by andrewrk** [comment]
If you don't mind, I do want to keep this open because I think I could improve the compile error, so at least you would have been unstuck by the compiler rather than having to wait for a response on github.

**Comment by emekoi** [comment]
no problem. thanks for the fast reply as well.

**Comment by vegai** [comment]
This looked like a potentially easy first contribution, so I dived in the code a bit. By a very first glance at zig source, `&&` could be trivially checked and disallowed at the tokenizer, but `||` is used for merging error sets, so that needs something cleverer.
