### ISSUE TITLE
zig build-exe -dynamic not work

### ISSUE THREAD

**Issue by yf13** [ziglang/zig#15618]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

Happened on both rpi4b w/ Alpine Linux and x86_64 Alpine Linux chroot:

```
$ uname -a 
Linux pi4 5.15.86-0-rpi4 #1-Alpine SMP PREEMPT Mon Jan 2 16:08:25 UTC 2023 aarch64 Linux
$ zig version
0.10.1
$ cat hello.zig
const std = @import("std");
pub fn main() !void{
   const stdout = std.io.getStdOut().writer();
   try stdout.print("Hello, {s}!\n", .{"world"});
}
$ zig build-exe hello.zig -dynamic
$ file hello
hello: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, with debug_info, not stripped
```

### Expected Behavior

the output ELF program shall be dynamically linked?

**Comment by andrewrk** [comment]
Dynamically linked against what? You have no library dependencies! If you add `-lc` then it will be dynamically linked against libc.
