### ISSUE TITLE
free vairables in different order may cause OutOfMemory error in FixedBufferAllocator

### ISSUE THREAD

**Issue by hronro** [ziglang/zig#15619]
### Zig Version

0.11.0-dev.2964+e9cbdb2cf

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

var buffer: [8]u8 = undefined;
var fba = std.heap.FixedBufferAllocator.init(buffer[0..]);
var allocator = fba.allocator();

for (0..10) |_| {
    var foo = try allocator.alloc(u8, 2);
    var bar = try allocator.alloc(u8, 2);
    allocator.free(foo);
    allocator.free(bar);
}
```

This would cause `OutOfMemory` error.

However, if we change the free order to:

```zig
var foo = try allocator.alloc(u8, 2);
var bar = try allocator.alloc(u8, 2);
allocator.free(bar);
allocator.free(foo);
```

And this will work without any issue.

### Expected Behavior

Any free order should work.

**Comment by schmee** [comment]
Not a bug, see https://github.com/ziglang/zig/pull/15008, and https://iamkroot.github.io/blog/zig-memleak for a more in-depth explanation.

**Comment by hronro** [comment]
BTW, does it means it's impossible to use FixedBufferAllocator with arena?

**Comment by trgwii** [comment]
See the implementation of FixedBufferAllocator in [std/heap.zig L459-L473](https://github.com/ziglang/zig/blob/94e30a756edc4c2182168dabd97d481b8aec0ff2/lib/std/heap.zig#L459-L473).

This indicates that FixedBufferAllocator is ONLY able to reclaim memory when the free order is exactly the reverse of the allocation order.

Additionally, see [std/heap.zig L410-L415](https://github.com/ziglang/zig/blob/94e30a756edc4c2182168dabd97d481b8aec0ff2/lib/std/heap.zig#L410-L415).

This implies that even if the allocation being freed is the last allocation, FixedBufferAllocator is not always able to free the memory associated.

FixedBufferAllocator is most often used in combination with [fba.reset()](https://github.com/ziglang/zig/blob/94e30a756edc4c2182168dabd97d481b8aec0ff2/lib/std/heap.zig#L490-L492), which will free everything allocated through it. With that, you don't need to combine it with ArenaAllocator at all, as FBA itself functions as an arena.

So rewriting your example with all this in mind, this will get you what you want:
```zig
const std = @import("std");

pub fn main() !void {
    var buffer: [8]u8 = undefined;
    var fba = std.heap.FixedBufferAllocator.init(buffer[0..]);
    const allocator = fba.allocator();

    for (0..10) |_| {
        defer fba.reset();
        var foo = try allocator.alloc(u8, 2);
        var bar = try allocator.alloc(u8, 2);
        allocator.free(foo);
        allocator.free(bar);
    }
}
```
