### ISSUE TITLE
Doc Comment of Structure EpochSeconds cites epoch start at Oct 1, 1970

### ISSUE THREAD

**Issue by MarkusXBoehm** [ziglang/zig#15624]
### Zig Version

0.11.0-dev.2680+a1aa55ebe

### Steps to Reproduce and Observed Behavior

The DocComment of structure EpochSeconds in epoch.zig says:
/// seconds since epoch Oct 1, 1970 at 12:00 AM

The Comment of structure EpochDay cites this start of epoch as well:
// days since epoch Oct 1, 1970.

### Expected Behavior

The according testEpoch confirms that the doc comments should be: 
/// seconds since epoch Jan 1, 1970
/// days since epoch Jan 1, 1970

P:S.: Then doc comments concerning start of epoch match in case of a sequence like:
const ts = time.timestamp();
const epoch_seconds = epoch.EpochSeconds{ .secs = @intCast(u64, ts) };

**Comment by andrewrk** [comment]
sooooo do you want to open a PR to fix it?
