### ISSUE TITLE
docgen fails to build if --zig-lib-dir value is a relative path

### ISSUE THREAD

**Issue by DraagrenKirneh** [ziglang/zig#15630]
### Zig Version

0.11.0-dev.2969+855493bb8

### Steps to Reproduce and Observed Behavior

This issue can be reproduced by running the following command:
`$DEVKIT\bin\zig.exe build -p stage3 --search-prefix $DEVKIT --zig-lib-dir lib -Dstatic-llvm -Duse-zig-libcxx -Dtarget=x86_64-windows-gnu`

Which is the command used by the building guide for windows (option 1b): https://github.com/ziglang/zig/wiki/Building-Zig-on-Windows#option-1b-zig-build 

Running the above command (with $DEVKIT replaced by the devkit path) will give the following error:
>run docgen (langref.html): error: error: unable to open zig lib directory 'lib': FileNotFound
>
>The following command exited with code 1:
>$DEVKIT\bin\zig.exe build-exe --name hello --color on hello.zig --zig-lib-dir lib
>$ZIGREPOSITORY\zig\doc\langref.html.in:402:31: error: example failed to compile
>      {#code_begin|exe|hello#}

Workaround:
Adding `-Dno-langref` to skip the lang ref generation or changing the `lib` option value used by "--zig-lib-dir" to `./lib` or using the full path to it `c:\some-path-to-zig\lib`. 

### Expected Behavior

docgen should have the same behavior on --zig-lib-dir paths as the rest of the build system.

**Comment by andrewrk** [comment]
Is this perhaps a duplicate of #12685?

**Comment by DraagrenKirneh** [comment]
> Is this perhaps a duplicate of https://github.com/ziglang/zig/issues/12685?
Yeah, I think it is.

**Comment by DraagrenKirneh** [comment]
duplicate of #12685
