### ISSUE TITLE
For consistency @offsetOf a u0 field should be allowed.

### ISSUE THREAD

**Issue by winksaville** [ziglang/zig#1564]
Below the test "sruct.S1field.u8" compiles, where as "struct.S1field.u0" does not:
```
fn S1field(comptime T1: type) type {
    return struct {
        f1: T1,
    };
}

test "struct.S1field.88" {
    const S1f = S1field(u8);
    var s1f = S1f { .f1 = 0,};
    assert(s1f.f1 == 0);
    assert(@sizeOf(S1f) == 1);
    assert(@offsetOf(S1f, "f1") == 0);
}

/// Compile fails
///
/// $ zig test ux-semantics.zig 
/// /home/wink/prgs/ziglang/zig-ux-semantics/ux-semantics.zig:226:27: error: zero-bit field 'f1' in struct 'S1field(u0)' has no offset
///     assert(@offsetOf(S1f, "f1") == 0); // error: zero-bit field ...
///                           ^
test "struct.S1field.u0" {
    const S1f = S1field(u0);
    var s1f = S1f { .f1 = 0,};
    assert(s1f.f1 == 0);
    assert(@sizeOf(S1f) == 0);
    assert(@offsetOf(S1f, "f1") == 0); // error: zero-bit field ...
}
```

**Comment by winksaville** [comment]
The code is available at [zig-ux-semantics](https://github.com/winksaville/zig-ux-semantics) although test "struct.S1field.u0" is currently commented out.

**Comment by BarabasGitHub** [comment]
But why? If it doesn't have an address and isn't anywhere in memory it can't have an offset either.

**Comment by winksaville** [comment]
They do have an address:
```
test "address.u0" {
    var val: u0 = 0;
    assert(val == 0);
    var pVal = &val;
    assert(pVal == &val);
    assert(pVal.* == 0);
    pVal.* = 0;
    assert(val == 0);
    assert(pVal.* == 0);
}
```
Although currently those addresses are compile time only, I believe they should be valid at runtime if the user wishes to use them that way.

As I see it, u0's are no different from u1..u128 and they should behave the same way. As can be seen in [zig-ux-semantics](https://github.com/winksaville/zig-ux-semantics) they mostly behave the same way, I can read, write and take their address. Why not have the address and offsets available at runtime? If the user chooses not to use any of these runtime operations, I believe there will be no cost.

The cost of not supporting runtime representations is the congnitive load of the exceptions, u0's are just like u1..u128 except ... as well as extra code within the application to work around those exceptions.

For instance, in the above code, maybe f1 is optional and so making it a u0 when its not used seems reasonable, as it won't take up any space. But there is likely code that may still want to use its address or offset at runtime, currently that code won't work, that seems a shame.

**Comment by thejoshwolfe** [comment]
What's the usecase for getting the offset of a u0 field? What are you going to do with the offset?

**Comment by winksaville** [comment]
@thejoshwolfe, the offset is useful in debugging to check layout of fields. Also I could see it being used in serialization protocols. But mostly, its a valid operation on u1..u128 and thus should be valid on u0, IMHO. I contend the same logic holds for addresses and any other valid u1..u128 operations.

**Comment by thejoshwolfe** [comment]
> the offset is useful in debugging to check layout of fields.

You can assert that the size of a field is 0 with comptime code. Fields of size 0 are not included in a struct's layout -- they are effectively deleted -- so there's nothing to debug at runtime.

> Also I could see it being used in serialization protocols.

Serializing and deserializing values of 0-size is literally the easiest thing conceivable; you do nothing. :P

But more seriously, I can imagine generic code that takes the offset of every field in a struct for some purpose. That hypothetical code would need to include an exception for fields of size 0 or else you get this compile error. I don't know if this is inconvenient or not; I think it depends on the hypothetical code. I can imagine that special-casing fields of size 0 is the right thing to do anyway, even without this compile error, so I'm not convinced there's any problem with status quo.

Again, I think a real usecase would be helpful in arguing that 0-sized fields should have any kind of location in a struct.

**Comment by tgschultz** [comment]
> But more seriously, I can imagine generic code that takes the offset of every field in a struct for some purpose. That hypothetical code would need to include an exception for fields of size 0 or else you get this compile error

Having written such code, I'm not sure this is actually true. Since the size of the field is also 0. For instance, I have generic reader/writer code that accepts any type and attempts to read/write data into it from/into an arbitrary source/destination. For structs it iterates through the fields and recursively calls itself on them until it gets to a primitive that is actually read/written. I have no special case for u0 and, compiler bugs aside, it works fine because `@sizeOf(u0)` is 0 so nothing is read/written.

**Comment by tgschultz** [comment]
For what it is worth, the arbitrary type read/write code I have doesn't special case `u0` and, compiler bugs aside, has no issues with it. If I had similar code that cared about offsets it would be a little annoying to have to special case something that shouldn't have any effect because it does nothing.

**Comment by winksaville** [comment]
> I think a real usecase would be helpful in arguing that 0-sized fields should have any kind of location in a struct.

@thejoshwolfe, how about this example added to [zig-ux-semantics](https://github.com/winksaville/zig-ux-semantics), I have a common routine that should work for any TypeId.Int, `displayF1ValOffsetAddr`:
```
fn displayF1ValOffsetAddr(s1: var) void {
    warn("s1.f1={} offset(s1.f1)={} &s1.f1={*}\n",
        s1.f1, @intCast(usize, @offsetOf(@typeOf(s1), "f1")), &s1.f1);
}

test "displayF1ValOffsetAddr.u1" {
    warn("\n");
    const S1f = S1field(u1);
    var s1f = S1f { .f1 = 0,};
    displayF1ValOffsetAddr(s1f);
}

test "displayF1ValOffsetAddr.u128" {
    warn("\n");
    const S1f = S1field(u128);
    var s1f = S1f { .f1 = 0,};
    displayF1ValOffsetAddr(s1f);
}
```
Both test "displayF1ValOffsetAddr.u1" and "displayF1ValOffsetAddr.i128" work fine
and I assume `u2..u128` and `i2..i127` TypeId.Int's work:
```
$ zig test ux-semantics.zig 
Test 1/13 undefined.u0.truncate.u0.literal.OK...OK
Test 2/13 undefined.u1...OK
Test 3/13 assignment.u0...OK
Test 4/13 assignment.u1...OK
Test 5/13 sizeof.u0...OK
Test 6/13 sizeof.u1...OK
Test 7/13 intCast.u0...OK
Test 8/13 intCast.u1...OK
Test 9/13 address.u0...OK
Test 10/13 address.u1...OK
Test 11/13 struct.S1field.u8...OK
Test 12/13 displayF1ValOffsetAddr.u1...
s1.f1=0 offset(s1.f1)=0 &s1.f1=u1@7fff2f5241b8
OK
Test 13/13 displayF1ValOffsetAddr.u128...
s1.f1=0 offset(s1.f1)=0 &s1.f1=u128@7fff2f5241b0
OK
All tests passed.
```
Only `u0` fails as can be seen by enabling test "displayF1ValuOffsetAddr.u0":
```
test "displayF1ValOffsetAddr.u0" {
    const S1f = S1field(u0);
    var s1f = S1f { .f1 = 0,};
    displayF1ValOffsetAddr(s1f);
}
```
It fails to compile:
```
$ zig test ux-semantics.zig 
/home/wink/prgs/ziglang/zig-ux-semantics/ux-semantics.zig:170:55: error: zero-bit field 'f1' in struct 'S1field(u0)' has no offset
        s1.f1, @intCast(usize, @offsetOf(@typeOf(s1), "f1")), &s1.f1);
                                                      ^
/home/wink/prgs/ziglang/zig-ux-semantics/ux-semantics.zig:198:27: note: called from here
    displayF1ValOffsetAddr(s1f);
                          ^
```

**Comment by winksaville** [comment]
@andrewrk, for a `struct` there are no guaranteed offsets, but they do have offsets.  Its my understanding that `packed structs` do have consistent offsets.

**Comment by winksaville** [comment]
Should truncate work, for example:
```
const std = @import("std");
const assert = std.debug.assert;

test "truncate.u0.literal" {
    var z = @truncate(u0, 0);
    assert(z == 0);
}

test "truncate.u0.const" {
    const c0: usize = 0;
    var z = @truncate(u0, c0);
    assert(z == 0);
}
```
These work fine:
```
$ zig test truncate-u0.zig 
Test 1/2 truncate.u0.literal...OK
Test 2/2 truncate.u0.const...OK
All tests passed.
```
But adding a test "truncate.u0.var" to truncate-u0.zig:
```
test "truncate.u0.var" {
    var d: u8 = 2;
    var z = @truncate(u0, d);
    assert(z == 0);
}
```
Causes a compile error:
```
$ zig test truncate-u0.zig 
Trunc only produces integer
  trunc i8 %1 to void, !dbg !664
LLVM ERROR: Broken module found, compilation aborted!
```

**Comment by thejoshwolfe** [comment]
any time you find a "LLVM ERROR: Broken module found", that's a compiler bug and you can open an issue for it. I think `@truncat(u0, x)` should work, and the result is always `u0(0)`.

**Comment by thejoshwolfe** [comment]
> how about this example added to zig-ux-semantics

I don't understand the objective of the example code. When would i use that code? What project would want that code? It looks more like a test case than a use case.

**Comment by winksaville** [comment]
@thejoshwolfe, I would consider tests valid use cases, but I use that type of code for debugging all the time.

Another similar example is generic code such as std.fmt.format.

**Comment by andrewrk** [comment]
`std.fmt.format` is a good use case. You can see it works fine:

```zig
const std = @import("std");

const Foo = struct {
    a: u0,
    b: u1,
};

test "struct with u0" {
    var foo = Foo{
        .a = 0,
        .b = 1,
    };
    std.debug.warn("{}\n", foo);
}
```

```
Test 1/1 struct with u0...Foo{ .a = 0, .b = 1 }
OK
```
