### ISSUE TITLE
@call on bound function reports incorrect number of expected arguments in error message

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#15642]
### Zig Version

0.11.0-dev.2571+31738de28

### Steps to Reproduce and Observed Output

Code:
```zig
const Blob = struct {
    pub fn getArrayBuffer(_: @This(), _: u32, _: u32) void {}
};

pub fn main() anyerror!void {
    const blob = Blob{};

    return @call(.always_inline, blob.getArrayBuffer, .{ blob, 1, 2 });
}
```

Output:
```zig
repro.zig:14:12: error: expected 3 argument(s), found 4
    return @call(.always_inline, blob.getArrayBuffer, .{ blob, 1, 2 });
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Note how it says there are 4 arguments but only 3 arguments were passed to the tuple.

### Expected Output

Either:
1) This should work because the meaning of `blob.getArrayBuffer` is unambiguously referring to the function declaration defined in the `Blob` struct.
2) The error message should say something like "expected 2 arguments in bound function call but received 3 arguments"

**Comment by mlugg** [comment]
`@call` on a bound function should not be allowed, particularly since bound functions are intended to be removed from the language. Once they're removed, the error will automatically make more sense here, since it'll be something like this:
```
error: no field named 'getArrayBuffer' in struct 'Blob'
note: 'getArrayBuffer' is a member function
note: add parentheses to call a member function
```

**Comment by mlugg** [comment]
Ah, I didn't know bound calls were intended to work with `@call` too, my bad.
