### ISSUE TITLE
Should compiler_rt.o be missing in static libraries by default?

### ISSUE THREAD

**Issue by trueFireblade** [ziglang/zig#15648]
### Zig Version

0.11.0-dev.2985+3f3b1a680

### Steps to Reproduce and Observed Behavior

Create a file test.zig with
```zig
export fn zig_hello() [*]const u8 {
    return "All your codebase are belong to us.\n";
}
```
Then create a file main.hs 
```haskell
module Main where

import Foreign.C ( CString, peekCString )

foreign import ccall "zig_hello" z_zig_hello :: IO CString

main :: IO ()
main = do
    c_res <- z_zig_hello
    res <- peekCString c_res
    putStrLn $ "Zig says: " <> res
```
run
```
$ zig build-lib test.zig
$ ghc main.hs -L./ -ltest
```
=> Linker error saying `__zig_probe_stack` is not defined, as per default `compiler_rt.o` is not put into the archive.

### Expected Behavior

`compiler_rt.o` would be expected to be put in the generated static archive.

Yes this is solvable by either `-fno-stack-check` or `-fcompiler-rt`, this issue is more so for considering whether the default behaviour should be adjusted to be more intuitive and was created because of @kubkon and @jacobly0 suggesting the creation of this issue on discord.

**Comment by rohlem** [comment]
`__zig_probe_stack` seems clearly a dependency introduced by Zig but not provided in the static archive.
Do you have a use case for including the rest of `compiler_rt.o`, or can this issue be reduced to strictly the symbols the library archive itself requires when used?
(Which would probably only be `__zig_probe_stack` if `-fno-stack-check` already fixes all issues in your example.)

**Comment by kubkon** [comment]
Including an entire `compiler_rt.o` in an archive should not be a problem from linking perspective. Firstly, all symbols are by default exported as weak globals so can easily be overwritten, plus `compiler_rt.o` is compiled with `-ffunction-sections` enabling garbage collection by the linker. The only drawback is slightly larger size of the archive.

**Comment by andrewrk** [comment]
* You can include compiler_rt in the static library with `-fcompiler_rt`.
* You can disable stack probing with `-fno-stack-check`.
* If you link with Zig you will get compiler_rt provided automatically.
