### ISSUE TITLE
Regression: `@min`/`@max` don't work with comptime int and runtime float

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#15644]
### Zig Version

0.11.0-dev.3041+8e9c9f6fd

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() !void {
	var x: f32 = 43829;
	x = @max(0, x);
}
```
Output:
```
$ zig run test.zig
test.zig:5:6: error: incompatible types: 'u0' and 'f32'
 x = @max(0, x);
     ^~~~~~~~~~
test.zig:5:11: note: type 'u0' here
 x = @max(0, x);
          ^
test.zig:5:14: note: type 'f32' here
 x = @max(0, x);
             ^
```

### Expected Behavior

`comptime_int` should coerce to any float type.

This does work as expected at compile time:
```zig
pub fn main() !void {
	comptime var x: f32 = 43829;
	x = @max(0, x);
}
```

**Comment by andrewrk** [comment]
cc @mlugg

**Comment by mlugg** [comment]
(working on this now, but the fix turned into a full rewrite of peer type resolution, so maybe take a bit of time)

**Comment by Jarred-Sumner** [comment]
Looking forward to a fix for this being merged, currently blocking us from upgrading to latest Zig on Bun
