### ISSUE TITLE
C binaries built with zig cc and `-Os` on macos and linux segfaults

### ISSUE THREAD

**Issue by cryi** [ziglang/zig#15662]
### Zig Version

zig-0.11.0-dev.3050+05ceac52c.tar.xz

### Steps to Reproduce and Observed Behavior

1. `git clone --recurse-submodules https://github.com/cryi/eli-zig-os`
2. build build container `podman build ./containers/build/ -t elibuild`
3. run build `podman run -w "/root/luabuild" -v $(pwd):"/root/luabuild" -v "$(pwd)/toolchains:/opt/cross" -e TOOLCHAINS='zig:x86_64-linux-musl' -it elibuild`

*It produces binary `release/eli-linux-x86_64`. It complains about some dependencies missing during the build but ignore that. This is stripped version just for this issue.*

Run produced binary:
4. `release/eli-linux-x86_64`
5. paste in: `hash.sha256sum("aa",true)` and hit enter to trigger segfault

Everything worked as expected with `0.11.0-dev.1928+3169f0529`. I am not sure when was issue introduced but yesterday build (`0.11.0-dev.3045+526065723`) was affected too.

Notes:
- if I remove -Os produced binary works as expected
- to change used compiler edit `containers/build/Dockerfile`
- to change compile flags edit [CMakeLists.txt#11](https://github.com/cryi/eli-zig-os/blob/main/CMakeLists.txt#L11)
- the code we use to trigger segfault is in [lua-mbed-hash module](https://github.com/alis-is/lua-mbed-hash/blob/0b7a251219fd04975b6286b62e296f4a0f52d3f2/src/hash.c#L24-L39)

### Expected Behavior

Binaries compiled with -Os and -Oz should not segfault.

**Comment by squeek502** [comment]
Just to be sure, does the segfault go away if you pass `-fno-sanitize=undefined`? Zig by default enables the undefined behavior sanitizer so it's possible that's what you're hitting.

**Comment by cryi** [comment]
Hi @squeek502 , no it does not go away. I would assume it is something more subtle as it was introduced somewhere between `0.11.0-dev.1928+3169f0529` and `0.11.0-dev.3045+526065723`

**Comment by cryi** [comment]
Ok I narrowed it down to `2401+348751462` which works and `2455+48f98494f` which does not. Major change between these is switch from clang 15.0.7 to 16.0.1.

**Comment by cryi** [comment]
Nvm this was actually issue with our code which just blew out when using Oz/Os with clang 16
