### ISSUE TITLE
undefined keyword for undefined values

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#1566]
Sometimes unreachable code can be limited to a `undefined` value, so the scope of undefined behavior is limited. The type would be automatically cast to the expected type. Not how how to elegently handle this in regards to enums and errors.

**Comment by thejoshwolfe** [comment]
Can you give a code example to illustrate your point?

**Comment by shawnl** [comment]
On second thought this is not a good idea. The original use case (we invoke undefined behavior when syscalls return unexpected errors https://github.com/ziglang/zig/issues/1396#issuecomment-423219118 ) can be fixed by reintroducing error.Unexpected .
