### ISSUE TITLE
koans to learn the zen of zig

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#1567]
there are koans for a bunch of languages, some better, some worse I guess

I did http://rubykoans.com at some point.

Maybe this is a worthwhile addition to zig towards 1.0 (certainly not a 0.3 and probably no 0.4 goal).
At least the wording would match perfectly and I think executed with care it can be a really good learning exercise, makes you think a bit compared to just reading.
The difficult thing to do is adding the right amount of necessary thinking/ hints. Its probably not possible to make it perfekt for everyone.

**Comment by monouser7dig** [comment]
this could very well be a community contribution, I can not think of any actionable thing right now, other than keeping it in mind until the language has stabilized a bit.

**Comment by binary132** [comment]
Koans could be used (with tests) to document language features in a doc tool.  Then that documentation would be kept up to date with compiler revisions, so koans would never go out of date as language features change.

**Comment by winksaville** [comment]
@monouser7dig, Koans sound like a great idea, I'd never heard of them before. I like learning something new everday, TXS!

**Comment by allochi** [comment]
Hey, I was just thinking about the same thing! I would like to give a hand.

I would also suggest to start on them even earlier than 1.1.0, and maintain them while the language is evolving.

**Comment by gunnarahlberg** [comment]
hi! @allochi, are you working this now? Seems like a great place for me to start contributing

**Comment by allochi** [comment]
@gunnarahlberg actually I am, I had to stop for a while, because of work pressure and lack of information, do you want to collaborate?

**Comment by gunnarahlberg** [comment]
HiYes I'd like to collaborate! I'm a novice on zig. I've done coding for 20 years and several trainings. So, if I get the code I'll be able to do the koans :)Den 18 feb. 2019 14:10 skrev Ali Anwar <notifications@github.com>:@gunnarahlberg actually I am, I had to stop for a while, because of work pressure and lack of information, do you want to collaborate?

**Comment by allochi** [comment]
@gunnarahlberg I think everyone is a novice at zig at the moment except its creator 😄 and few  
contributors.

Could you give me until the weekend? I need to wrap up work stuff, finish a blog I'm writing on zig, and then I will clean up and share the code.

**Comment by allochi** [comment]
Hi @gunnarahlberg, I'm sorry, I haven't touched zig for a while, and only recently trying to get back on track, I don't feel comfortable with the work I have done on this project, and I don't feel I'm on top of the language changes and new features, to actually write code that teaches people how to use it.

Please feel free to start your own Koans project.

This apology extends to anyone who was waiting for me to deliver on this.

**Comment by gunnarahlberg** [comment]
Hi Ali!No worries!  GunnarDen 5 apr. 2019 11:24 skrev Ali Anwar <notifications@github.com>:Hi @gunnarahlberg, I'm sorry, I haven't touched zig for a while, and only recently trying to get back on track, I don't feel comfortable with the work I have done on this project, and I don't feel I'm on top of the language changes and new features, to actually write code that teaches people how to use it.
Please feel free to start your own Koans project.
This apology extends to anyone who was waiting for me to deliver on this.

**Comment by jsutton** [comment]
I arrived here looking for something similar to http://rubykoans.com or https://github.com/gregmalcolm/python_koans for zig. I have since found https://github.com/ratfactor/ziglings and hope that it helps whoever comes after me to this place.

**Comment by ratfactor** [comment]
Cool, I hadn't seen this issue before.

@andrewrk Seems like Ziglings is pretty much exactly this. Perhaps this issue can be closed?
