### ISSUE TITLE
Suggestions: improving the friendly of zig‘s build system api, refer to xmake

### ISSUE THREAD

**Issue by sogwms** [ziglang/zig#15699]
xmake is a great build system with clear rules and intuitive, while Zig's API I personally find a bit confusing, I recommend learning from xmake to improve the build system

https://xmake.io/#/manual/specification
![image](https://github.com/ziglang/zig/assets/48476349/4e1985bb-c3d6-4639-a52f-4ea7de454aed)

**Comment by InKryption** [comment]
What components of the build system do you find confusing? What parts of xmake are you suggesting to take inspiration from?

**Comment by sogwms** [comment]
the following pictures are some examples that we can compare. from the view of users, it should be not hard to see zig's build system exposes too much that not necessary and some apis are not loyal to their names.   I think what should be learned here is the design idea of xmake that only require users to provide what are necessary for the build system and hide what can hide as much as possible (SOLID principles), and make the build-script be simple for a (simple) project (pareto principle?)
![image](https://github.com/ziglang/zig/assets/48476349/734b23a9-09ac-4a3e-aeed-f401e5428d4f)

![image](https://github.com/ziglang/zig/assets/48476349/4960af50-5de5-47b8-ab81-6df05f04ccd2)

**Comment by sogwms** [comment]
By the way, an unified API naming convention will also be more user-friendly (after all, if here are such naming conventions (/ intuition), and there are other naming conventions (/ intuition), which probably only adds more unnecessary burden and confusion) 

( •ᴗ• )How good it is to reuse a naming convention
