### ISSUE TITLE
`build-exe` creates an empty executable file on compilation errors

### ISSUE THREAD

**Issue by GreenRecycleBin** [ziglang/zig#15739]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

```console
$ cat <<EOF > stack_trace.zig
pub fn main() void {
    foo(0);
}

fn foo(x: i32) void {
    if (x >= 5) {
        bar();
    } else {
        bang2();
    }
}

fn bar() void {
    if (baz()) {
        quxx();
    } else {
        hello();
    }
}

fn baz() bool {
    bang1();
}

fn quxx() void {
    bang2();
}

fn hello() void {
    bang2();
}

fn bang1() bool {
    return false;
}

fn bang2() void {
    @panic("PermissionDenied");
}
EOF

$ file stack_trace
stack_trace: cannot open `stack_trace' (No such file or directory)

$ zig build-exe stack_trace.zig
stack_trace.zig:22:10: error: value of type 'bool' ignored
    bang1();
    ~~~~~^~
stack_trace.zig:22:10: note: all non-void values must be used
stack_trace.zig:22:10: note: this error can be suppressed by assigning the value to '_'
referenced by:
    bar: stack_trace.zig:14:9
    foo: stack_trace.zig:7:9
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

$ file stack_trace
stack_trace: empty

$ ls -l stack_trace
-rwxr-xr-x@ 1 me  staff  0 May 17 09:07 stack_trace
```

### Expected Behavior

`build-exe` does not create any files on compilation errors, similar to other compilers, e.g., GCC.

**Comment by GreenRecycleBin** [comment]
I tried to address this in https://github.com/ziglang/zig/pull/14804 but apparently didn't account for incremental compilation.

I stumbled upon Zig while researching novel programming languages, e.g., [Vale](https://vale.dev/), and was simply trying to learn the language by mucking with the compiler.
Are there resources that document Zig incremental compilation process at a high level? Or should I just read the code?

(Maybe I should start with [contributer-friendly tickets](https://github.com/ziglang/zig/labels/contributor%20friendly) instead.)

**Comment by andrewrk** [comment]
There is no such resource yet, I'm afraid. I will say one thing on the topic though, it is planned that you can still run a binary that has compilation errors in it. A compilation error will be emitted as a runtime panic in the executable file. The compiler will still return an error exit code by default when there are compilation errors. But if the programmer wishes to explore the application's behavior, knowing that it will crash at any function that contained compilation errors, they will be free to do so.

**Comment by andrewrk** [comment]
I'm going to call this working-as-designed.
