### ISSUE TITLE
wasm32-wasi ReleaseFast miscompilation?

### ISSUE THREAD

**Issue by candrewlee14** [ziglang/zig#15740]
### Zig Version

0.11.0-dev.3105+e46d7a369

### Steps to Reproduce and Observed Behavior

1. Clone https://github.com/candrewlee14/zgml (commit: 2ac12d450dbdc49818a99bfa66e908d40933a28a)
2. Run `zig build -Doptimize=ReleaseSafe -Dtarget=wasm32-wasi`
3. Run `wasmtime ./zig-out/bin/zgml-tests.wasm`
4. Observe `All 30 tests passed.`
5. Run `zig build -Doptimize=ReleaseFast -Dtarget=wasm32-wasi`
6. Run `wasmtime ./zig-out/bin/zgml-tests.wasm`
7. Observe `29 passed; 0 skipped; 1 failed.` `25/30 test.arange... expected 3.0e+01, found 3.2e+01 FAIL (TestExpectedEqual)`

This behavior difference doesn't occur when building for my native machine (linux, x86_64) with ReleaseSafe & ReleaseFast (both pass all tests).

This is the failing test:
```zig
test "arange" {
    const t = try Tensor(f32).initLinspace(tac, &.{5}, 0, 5); // printing t.data gives {0,1,2,3,4}
    t.setParam();
    try testing.expectEqual(@as(usize, 5), t.nElems());
    const expected = [_]f32{ 0, 1, 2, 3, 4 };
    try testing.expectEqualSlices(f32, &expected, t.data);

    const out = t.sqr().sumAll();
    var g = ComputeGraph(f32).init(tac);
    defer g.deinit();
    try g.buildForward(out);
    try g.buildBackward(true);
    out.grad.?.data[0] = 1;
    g.compute();

    // 0^2 + 1^2 + 2^2 + 3^2 + 4^2 = 0 + 1 + 4 + 9 + 16 = 30
    try testing.expectEqual(@as(f32, 30), out.data[0]); // out.data[0] is somehow 32
    try testing.expectEqualSlices(f32, &.{ 0, 2, 4, 6, 8 }, t.grad.?.data);
    const lr = try Tensor(f32).initScalar(tac, 0.01);
    defer lr.deinit();
    for (0..1000) |_| {
        g.reset();
        g.resetGrads();
        out.grad.?.data[0] = 1;
        g.compute();
        t.grad.?.computeMul(t.grad.?, lr);
        t.computeSub(t, t.grad.?);
    }
    try testing.expectApproxEqAbs(@as(f32, 0), out.data[0], 0.00001);
}
```

### Expected Behavior

When using `zig build -Doptimize=ReleaseFast -Dtarget=wasm32-wasi`, I'd expect to observe `All 30 tests passed` like when using `ReleaseSafe`.

**Comment by matu3ba** [comment]
Can you reduce this further? Things like `const t = try Tensor(f32).initLinspace(tac, &.{5}, 0, 5); // printing this gives {0,1,2,3,4}` should be reduced.

Making a branch where you delete code until you get something minimal or a repo including small script to execute and link it here would make things simpler.

**Comment by andrewrk** [comment]
I'm sorry we don't have any "zig-reduce" tool yet to help with the reduction, but I would like to see a reduction before confirming this as a miscompilation.

**Comment by candrewlee14** [comment]
Following those same steps now has all tests passing. So whatever has happened since then in Zig and/or wasmtime has resolved the issue. I'll close this, thanks for the great work!
