### ISSUE TITLE
Unable to install snap on Ubuntu riscv64

### ISSUE THREAD

**Issue by chrbayer** [ziglang/zig#15757]
### Zig Version

beta and edge

### Steps to Reproduce and Observed Behavior

sudo snap install --edge --classic zig
error: cannot perform the following tasks:
- Ensure prerequisites for "zig" are available (cannot install snap base "bare": no snap revision available as specified)

bare is not available for riscv64

### Expected Behavior

Installation is possible like on amd64 and arm64 Ubuntu

**Comment by squeek502** [comment]
As far as I'm aware, nothing snap related is officially supported/maintained by Zig. You might have better luck filing an issue here: https://github.com/jayschwa/snapcraft-zig

**Comment by chrbayer** [comment]
Yes, you are right, this is not the correct project for this report, thank you very much for letting me know!
