### ISSUE TITLE
nested @max intrinsic calls attempt to cast comptime_ints to u6

### ISSUE THREAD

**Issue by Validark** [ziglang/zig#15776]
### Zig Version

0.11.0-dev.3206+b9d2e0e30

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

const a = 12;
const b = 32;

pub fn main() void {
    const x = @max(std.math.maxInt(u8), @max(a, b));
    _ = x;
}
```

output:
```
src/a.zig:7:35: error: type 'u6' cannot represent integer value '255'
    const x = @max(std.math.maxInt(u8), @max(a, b));
                   ~~~~~~~~~~~~~~~^~~~
```

### Expected Behavior

`x` should be `@as(comptime_int, 255)`

**Comment by mlugg** [comment]
Caused by PTR of `uX` and `comptime_int` always returning `uX`, even if that type isn't large enough for the `comptime_int`. Smaller repro: `_ = @max(2, @as(u1, 1))` or even just `_ = 2 + @as(u1, 1)`. Adding PTR rule to fix in #15726
