### ISSUE TITLE
std: Naming inconsistency in 'from/to string' functions - radix vs base

### ISSUE THREAD

**Issue by linusg** [ziglang/zig#15789]
### Zig Version

0.11.0-dev.3198+ad20236e9

### Steps to Reproduce and Observed Behavior

Various parsing functions exist in the standard library, in some cases they accept a `radix` argument:

```console
$ git grep 'radix: u8' lib/std/
lib/std/fmt.zig:pub fn parseInt(comptime T: type, buf: []const u8, radix: u8) ParseIntError!T {
lib/std/fmt.zig:    radix: u8,
lib/std/fmt.zig:pub fn parseUnsigned(comptime T: type, buf: []const u8, radix: u8) ParseIntError!T {
lib/std/fmt.zig:pub fn parseIntSizeSuffix(buf: []const u8, radix: u8) ParseIntError!usize {
lib/std/fmt.zig:pub fn charToDigit(c: u8, radix: u8) (error{InvalidCharacter}!u8) {
```

However, in most cases this is called `base`:

```console
$ git grep 'base: u8' lib/std/
lib/std/c/freebsd.zig:        base: u8,
lib/std/fmt.zig:    base: u8,
lib/std/fmt.zig:pub fn formatIntBuf(out_buf: []u8, value: anytype, base: u8, case: Case, options: FormatOptions) usize {
lib/std/fmt.zig:pub fn bufPrintIntToSlice(buf: []u8, value: anytype, base: u8, case: Case, options: FormatOptions) []u8 {
lib/std/fmt/parse_float/FloatStream.zig:pub fn firstIsDigit(self: FloatStream, comptime base: u8) bool {
lib/std/fmt/parse_float/FloatStream.zig:pub fn scanDigit(self: *FloatStream, comptime base: u8) ?u8 {
lib/std/fmt/parse_float/common.zig:pub fn isDigit(c: u8, comptime base: u8) bool {
lib/std/fmt/parse_float/parse.zig:fn tryParseDigits(comptime T: type, stream: *FloatStream, x: *T, comptime base: u8) void {
lib/std/fmt/parse_float/parse.zig:fn tryParseNDigits(comptime T: type, stream: *FloatStream, x: *T, comptime base: u8, comptime n: usize) void {
lib/std/fmt/parse_float/parse.zig:    base: u8,
lib/std/fmt/parse_float/parse.zig:pub fn validUnderscores(s: []const u8, comptime base: u8) bool {
lib/std/math/big/int.zig:pub fn calcToStringLimbsBufferLen(a_len: usize, base: u8) usize {
lib/std/math/big/int.zig:pub fn calcSetStringLimbsBufferLen(base: u8, string_len: usize) usize {
lib/std/math/big/int.zig:pub fn calcSetStringLimbCount(base: u8, string_len: usize) usize {
lib/std/math/big/int.zig:        base: u8,
lib/std/math/big/int.zig:    pub fn toStringAlloc(self: Const, allocator: Allocator, base: u8, case: std.fmt.Case) Allocator.Error![]u8 {
lib/std/math/big/int.zig:    pub fn toString(self: Const, string: []u8, base: u8, case: std.fmt.Case, limbs_buffer: []Limb) usize {
lib/std/math/big/int.zig:    pub fn setString(self: *Managed, base: u8, value: []const u8) !void {
lib/std/math/big/int.zig:    pub fn toString(self: Managed, allocator: Allocator, base: u8, case: std.fmt.Case) ![]u8 {
lib/std/zig/number_literal.zig:    var base: u8 = 10;
```

### Expected Behavior

This doesn't immediately affect user code due to the absence of named parameters, but the name is shown in IDE's inlay hints, where the mixing of `base` and `radix` is distracting. Either name should be picked and used consistently.

**Comment by linusg** [comment]
(obviously not a bug, just the closest available template - feel free to relabel.)

**Comment by nektro** [comment]
prior art:

https://en.wikipedia.org/wiki/Radix wikipedia uses radix and base interchangeably but calls the page radix (newcomers to the term are more likely to know base but the proper term is radix)
php base https://www.php.net/manual/en/function.intval.php
rust radix https://doc.rust-lang.org/std/primitive.i64.html#method.from_str_radix
javascript radix https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt
python base https://docs.python.org/3/library/functions.html#int
go base https://pkg.go.dev/strconv#ParseInt
ruby base https://ruby-doc.org/core-3.1.0/Kernel.html#method-i-Integer
java radix https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#parseInt-java.lang.String-int-
odin base https://pkg.odin-lang.org/core/strconv/#parse_int

**Comment by nektro** [comment]
edit: funnily enough I came to Zig with quite a large java and javascript experience and so I came into this with a big preference for `radix` haha, really wasnt expecting to find as much `base` as I did
