### ISSUE TITLE
How to init and print zero terminate string

### ISSUE THREAD

**Issue by tisonkun** [ziglang/zig#15787]
### Zig Version

87de8212adac280780900f8a68c302c6bc127c47

### Steps to Reproduce and Observed Behavior

```zig
test "basic" {
    var buf: [1024:0]u8 = undefined;
    buf[0] = 0;
    try testing.expectFmt("", "{s}", .{buf});
}
```

### Expected Behavior

This test in my understanding should pass, but it fails with:

```
failed: ====== expected this output: =========

======== instead found this: =========
???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
======================================
```

How can I properly init an empty zero terminate string with fixed length then?

**Comment by rohlem** [comment]
The primary issue in your example is a particularity of the type system:
- `[n:0]u8` denotes a sentinel-terminated array type: It is a sequence of `n` `u8`, followed by a single sentinel `u8` of value `0`.
- What you instead expected is for the first `0` encountered to denote the end of the string.
  This would be a variable-sized type, which is not expressible in status-quo Zig today.
- What we **do** have however sentinel-terminated multi-element-pointers, in this example, you would want `[*:0]u8`.

The issue as it manifests in your example is that the format function is given the array value, which consists of a single `0` followed by 1023 `undefined` `u8` values, followed by another `0`,
and decides for the format specifier `{s}` to dump all of the array contents.
If you explicitly take the array's address, and cast it to the appropriate pointer type it like so:
```zig
const ptr_to_buf = @as([*:0]u8, &buf);
try testing.expectFmt("", "{s}", .{ptr_to_buf});
```
the test correctly succeeds.

---

IMHO the current implementation of the `{s}` format specifier in `std` is a footgun in this regard.
`s` is already a mnemonic specifically for "string", and it correctly understands sentinel-termination when given a many-pointer,
so passing a sentinel-terminated array or slice (which resulting in 2 ways to deduce length) will in most cases be a mistake.

However, to allow string literals, we probably want to allow sentinel-terminated array and slice values if they only contain the single terminator sentinel at their length.
Therefore a descriptive runtime panic (for both `[n:0]u8` and `[:0]u8`) for values with early termination would seem the most appropriate to me.

**Comment by tisonkun** [comment]
Thank @rohlem for your detailed answer.

Closed as `@as([*:0]const u8, &buf)` works.

> Therefore a descriptive runtime panic (for both [n:0]u8 and [:0]u8) for values with early termination would seem the most appropriate to me.

Runtime panic may be too strict to fatal exit user program?

**Comment by rohlem** [comment]
> Runtime panic may be too strict to fatal exit user program?

From `zig zen`: `Runtime crashes are better than bugs`. IMHO it would be exactly appropriate in this scenario.

> Closed as @as([*:0]const u8, &buf) works.

IMO it could remain open for discussion of improving the standard library (collecting opinions until someone opens a PR for it, or the idea is officially rejected).

**Comment by tisonkun** [comment]
OK. Left open for a while to see if further interest arrives :D

**Comment by squeek502** [comment]
The array is just not what you want to pass to `expectFmt` here, and instead you'd want to get a slice from the array using `std.mem.sliceTo(&buf, 0)` or manually create the appropriate slice via `buf[0..0 :0]` (this is safety checked to ensure the resulting slice is actually sentinel terminated).

> However, to allow string literals, we probably want to allow sentinel-terminated array and slice values if they only contain the single terminator sentinel at their length.

A sentinel within sentinel terminated slices is [explicitly allowed in the lang ref](https://ziglang.org/documentation/master/#Sentinel-Terminated-Slices):

> The syntax `[:x]T` is a slice which has a runtime-known length and also guarantees a sentinel value at the element indexed by the length. The type does not guarantee that there are no sentinel elements before that.

This is not made explicit in the sentinel-terminated array docs, but AFAIK it is also the case.

**Comment by rohlem** [comment]
@squeek502 I agree with you that sentinels are allowed in a sentinel-terminated array (and slice) before the final, terminating sentinel.
I still think it would be more user-friendly if the default string format specifier `{s}` in the standard library rejected this case (at runtime, as stated),
because in that case the user provided more info than necessary.

Do you have, as counterargument, a use case that benefits from the current behavior?
(Where removing the sentinel via `[0..]` slicing would be too convoluted?)

**Comment by squeek502** [comment]
My counter-argument would be that formatting code just seems like the wrong place for a 'correctness' (but not correctness from the language's perspective) check like that. Being able to pass a sentinel-terminated slice to formatted printing without worrying about panics is a use case worth preserving in my opinion.

Making passing a sentinel-terminated slice/array to a `{s}` format specifier a compile error instead would probably be better but I haven't thought through the ramifications of that.
