### ISSUE TITLE
Proposal: Promote `std.debug.TTY` to non-`debug` functionality

### ISSUE THREAD

**Issue by linusg** [ziglang/zig#15804]
I found this struct the other day and think it doesn't need to be hidden away in the `debug` namespace, potentially preventing people from using it for non-debugging purposes.

Notably, it contains cross-platform text coloring (at least supports ANSI escape sequences and the Windows API), including feature detection (is color output supported, respect `NO_COLOR`, etc) via `detectTTYConfig()`.

This proposal covers two things:

- Moving `TTY` and `detectTTYConfig()` from `std.debug` to `std.io`
- Adding missing colors (blue, magenta, bright variants, possibly more)

I'm happy to implement this once accepted.

**Comment by squeek502** [comment]
For some context, `TTY` was made more general purpose somewhat recently in https://github.com/ziglang/zig/pull/12298 and https://github.com/ziglang/zig/pull/13948
