### ISSUE TITLE
Allowing creating executable/library with only object files (no zig source file with main func)

### ISSUE THREAD

**Issue by DEC05EBA** [ziglang/zig#1581]
I'm creating a cargo like build system for c, c++ and zig and I don't specify the zig source file with main function so currently I run `zig build-obj file.zig` on all zig files and then use gcc/cl.exe (msvc linker) to create an executable/library from the object files.
Running `zig build-exe --object file.o` doesn't work because you need to include the zig source file with main function in the command.

It would be helpful if it was possible to create executable/library from object files only so I can build executable/library in a project with only zig files on a system with no linker - for example on windows if visual studio is not installed but you want to create a zig project.

Or perhaps there is a way to do this already in zig with build.zig file?

**Comment by tiehuis** [comment]
If you just want to use zig as a linker, you should just need to specify the name parameter for an executable. If using a C object you will need to link against the C runtime to ensure you have the correct entry point.

```
#include <stdio.h>

int main(void)
{
    printf("Hello, world!\n");
}
```

```
$ gcc -c main.c -o main.o
$ zig build-exe --name main --object main.o --library c
$ ./main
Hello, world!
```

Remember that if you want to build all zig files into object first, mimicking the C compilation model you will need to ensure you export the related functions appropriately so they are visible with a stable ABI.

**Comment by DEC05EBA** [comment]
Thank you, that solves my problem. I tried using --output instead, I missed that there was a --name argument
