### ISSUE TITLE
Add support for #embed in zig cc

### ISSUE THREAD

**Issue by skogshjort** [ziglang/zig#15836]
As of now, May 2023, no major compiler supports [the new #embed directive](https://thephd.dev/finally-embed-in-c23) that has been accepted into the C23 standard. I would love to see it implemented in zig cc.

**Comment by alichraghi** [comment]
`zig cc` uses clang

**Comment by Vexu** [comment]
Aro also has basic `#embed` support https://github.com/Vexu/arocc/pull/468, it just needs a backend to be added as an alternative for clang to `zig cc`.
