### ISSUE TITLE
Compiler exit with error code 5

### ISSUE THREAD

**Issue by CGQAQ** [ziglang/zig#15838]
### Zig Version

0.11.0-dev.3278+9d179a98f

### Steps to Reproduce and Observed Behavior

# struct itself
```zig
const DynBuf = struct {
    const Self = @This();
    allocator: std.mem.Allocator,

    buf: ?*u8,
    size: usize,
    allocated_size: usize,
    err: bool,
    realloc_func: ?*DynBufReallocFunc,
    opak: ?*anyopaque,
}
```

# trigger the bug
```zig
 pub fn put(self: *Self, data: []const u8) !void {
        if ((self.size + data.len) > self.allocated_size) {
            // @Cold()
            try self.realloc(self.size + data.len);
        }

        // var dest = @ptrCast([*]u8, self.buf.?)[self.size..self.allocated_size];
        var dest = @ptrCast([*]u8, self.buf.?) + self.size;  // this will trigger the bug
        @memcpy(dest, data);
        self.size += data.len;
}
test "__all_valid__" {
    std.testing.refAllDecls(DynBuf);
}
```

<details><summary>Details</summary>
<p>

$ zig build test
zig test Debug native: error: the following command exited with error code 5:
C:\Users\Administrator\scoop\apps\zig-dev\current\zig.exe test D:\personal\quickjs-zig\src\main.zig D:\personal\quickjs-zig\zig-cache\o\ebdc37df33f4fe7e1b984b3c4f952c0e\bf.lib -lc --cache-dir D:\personal\quickjs-zig\zig-cache --global-cache-dir C:\Users\Administrator\AppData\Local\zig --name test -I D:\personal\quickjs-zig\quickjs -I D:\personal\quickjs-zig\src --listen=- 
Build Summary: 1/4 steps succeeded; 1 failed (disable with -fno-summary)
test transitive failure
+- run test transitive failure
   +- zig test Debug native failure
      +- zig build-lib bf Debug native cached 14ms MaxRSS:15M
error: the following build command failed with exit code 1:
D:\personal\quickjs-zig\zig-cache\o\26dbc0dc505975dc2f21cb2719ea4744\build.exe C:\Users\Administrator\scoop\apps\zig-dev\current\zig.exe D:\personal\quickjs-zig D:\personal\quickjs-zig\zig-cache C:\Users\Administrator\AppData\Local\zig test
![image](https://github.com/ziglang/zig/assets/15936231/5017f2f3-13fe-46b6-84d3-7b12b7b89ee7)

</p>
</details> 

# working code

```zig
 pub fn put(self: *Self, data: []const u8) !void {
        if ((self.size + data.len) > self.allocated_size) {
            // @Cold()
            try self.realloc(self.size + data.len);
        }

        var dest = @ptrCast([*]u8, self.buf.?)[self.size..self.allocated_size]; // this is okey
        // var dest = @ptrCast([*]u8, self.buf.?) + self.size;  
        @memcpy(dest, data);
        self.size += data.len;
}

test "__all_valid__" {
    std.testing.refAllDecls(DynBuf);
}
```

### Expected Behavior

don't exit with code 5, and without any useful error message

**Comment by Vexu** [comment]
I'm unable to reproduce the crash with:
```zig
const std = @import("std");
const DynBuf = struct {
    const Self = @This();
    allocator: std.mem.Allocator,

    buf: ?*u8,
    size: usize,
    allocated_size: usize,
    err: bool,
    realloc_func: ?*usize,
    opak: ?*anyopaque,
};
pub fn put(self: *DynBuf, data: []const u8) !void {
    if ((self.size + data.len) > self.allocated_size) {
        // @Cold()
        try self.realloc(self.size + data.len);
    }

    // var dest = @ptrCast([*]u8, self.buf.?)[self.size..self.allocated_size];
    var dest = @ptrCast([*]u8, self.buf.?) + self.size; // this will trigger the bug
    @memcpy(dest, data);
    self.size += data.len;
}
test "__all_valid__" {
    std.testing.refAllDecls(DynBuf);
}
```
