### ISSUE TITLE
'zig cc' works, but 'zig build' does nothing 

### ISSUE THREAD

**Issue by senneh** [ziglang/zig#15833]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

So I'm trying to port the original DOOM source code to zig, starting by using zig as my build system.

After some slight modifications to the source files running the following command produces a "working" executable: `zig cc -o doomsparc -Wall -DNORMALUNIX -DLINUX -target i386-linux src/am_map.c src/d_items.c src/d_main.c src/d_net.c src/doomdef.c src/doomstat.c src/dstrings.c src/f_finale.c src/f_wipe.c src/g_game.c src/hu_lib.c src/hu_stuff.c src/i_main.c src/i_net.c src/info.c src/i_sound.c src/i_system.c src/i_video.c src/m_argv.c src/m_bbox.c src/m_cheat.c src/m_fixed.c src/m_menu.c src/m_misc.c src/m_random.c src/m_swap.c src/p_ceilng.c src/p_doors.c src/p_enemy.c src/p_floor.c src/p_inter.c src/p_lights.c src/p_map.c src/p_maputl.c src/p_mobj.c src/p_plats.c src/p_pspr.c src/p_saveg.c src/p_setup.c src/p_sight.c src/p_spec.c src/p_switch.c src/p_telept.c src/p_tick.c src/p_user.c src/r_bsp.c src/r_data.c src/r_draw.c src/r_main.c src/r_plane.c src/r_segs.c src/r_sky.c src/r_things.c src/sounds.c src/s_sound.c src/st_lib.c src/st_stuff.c src/tables.c src/v_video.c src/wi_stuff.c src/w_wad.c src/z_zone.c`

But when I create a build.zig file and run `zig build` absolutely nothing happens. No error, no messages and no executable. 
It does create a zig-cache directory, but it doesn't contain much.

My build file: 

```zig
const std = @import("std");

pub fn build(b: *std.build.Builder) void {
    const target = b.standardTargetOptions(.{});
    const mode = b.standardReleaseOptions();

    const doomspark = b.addExecutable("doomspark", null);
    doomspark.setTarget(target);
    doomspark.setBuildMode(mode);
    doomspark.linkLibC();
    doomspark.addCSourceFiles(&.{
        "src/am_map.c",
        "src/d_items.c",
        "src/d_main.c",
        "src/d_net.c",
        "src/doomdef.c",
        "src/doomstat.c",
        "src/dstrings.c",
        "src/f_finale.c",
        "src/f_wipe.c",
        "src/g_game.c",
        "src/hu_lib.c",
        "src/hu_stuff.c",
        "src/i_main.c",
        "src/i_net.c",
        "src/info.c",
        "src/i_sound.c",
        "src/i_system.c",
        "src/i_video.c",
        "src/m_argv.c",
        "src/m_bbox.c",
        "src/m_cheat.c",
        "src/m_fixed.c",
        "src/m_menu.c",
        "src/m_misc.c",
        "src/m_random.c",
        "src/m_swap.c",
        "src/p_ceilng.c",
        "src/p_doors.c",
        "src/p_enemy.c",
        "src/p_floor.c",
        "src/p_inter.c",
        "src/p_lights.c",
        "src/p_map.c",
        "src/p_maputl.c",
        "src/p_mobj.c",
        "src/p_plats.c",
        "src/p_pspr.c",
        "src/p_saveg.c",
        "src/p_setup.c",
        "src/p_sight.c",
        "src/p_spec.c",
        "src/p_switch.c",
        "src/p_telept.c",
        "src/p_tick.c",
        "src/p_user.c",
        "src/r_bsp.c",
        "src/r_data.c",
        "src/r_draw.c",
        "src/r_main.c",
        "src/r_plane.c",
        "src/r_segs.c",
        "src/r_sky.c",
        "src/r_things.c",
        "src/sounds.c",
        "src/s_sound.c",
        "src/st_lib.c",
        "src/st_stuff.c",
        "src/tables.c",
        "src/v_video.c",
        "src/wi_stuff.c",
        "src/w_wad.c",
        "src/z_zone.c",
    }, &.{
        "-Wall",
        "-DNORMALUNIX",
        "-DLINUX",
        "-target i386-linux",
    });
}

```

### Expected Behavior

To build, or at least give me some error message.

**Comment by andrewrk** [comment]
This is not a bug, it is working as designed. Also this issue tracker is for master branch, and much has changed in the build system since 0.10.1. I suggest to have a look at the template that zig init-exe gives you. You will need to ask follow up questions elsewhere, as GitHub issues is reserved for issues; it is not used for questions and onboarding.
