### ISSUE TITLE
Taking reference to `errdefer` capture payload crashes compiler

### ISSUE THREAD

**Issue by mlugg** [ziglang/zig#15861]
### Zig Version

0.11.0-dev.3289+16dbb960f

### Steps to Reproduce and Observed Behavior

```zig
test {
    errdefer |x| {
        @import("std").mem.doNotOptimizeAway(&x);
    }
    return error.Foo;
}
```
Segfaults.

### Expected Behavior

Successful compilation.

This is caused by AstGen not handling `ref_table` for the `errdefer_err_code` instruction created by `errdefer` captures; fix will be fairly simple, just filing this so I don't forget about it.

**Comment by iacore** [comment]
Can you modify `x`? Does that even make sense?

**Comment by mlugg** [comment]
You can't modify it, but that doesn't mean you can't take a pointer, it just has type `*const error{Foo}` or whatever
