### ISSUE TITLE
Autodoc: Zig tokenizer for the frontend

### ISSUE THREAD

**Issue by kristoff-it** [ziglang/zig#15863]
Autodoc is in need of a Zig source code tokenizer. The tokenizer would have two main duties:

- help highlight source code (code snippets in guides or doc comments, doctests, comptime expressions)
- support detection of variable identifiers in source code, so that we can then try to link them to a definition or source code

There are two ways of approaching this problem, each with its own set of downsides:

- Write one in JS
   - boring reinvention of the wheel (zig has already a tokenizer in the stdlib)
   - must be kept in sync manually with the language
- Compile the stdlib one to wasm
   - autodoc now requires wasm support in the browser
   - building autodoc now requires an implicit extra build step to create the wasm blob (and ensure it stays up to date)
 
@andrewrk we're always tried to be conservative with the requirements for running Autodoc, but we have never been really formal about it. I remember we wanted to keep Ladybird into consideration but at the same time it seems that now it's fast approaching state of the art support for JS feature etc. What's your take on this?

**Comment by rohlem** [comment]
Never tried it, but is support via `emscripten` worth considering? My (slightly outdated) `zig targets` includes it at least; I assume that should output fairly backwards-compatible javascript.

**Comment by kristoff-it** [comment]
This would not add wasm as a requirement and avoid some of the "pure JS" solution issues, but it would also add a dev dependency to the compiler that I don't think we'd want, and it would probably still require some work to clean up the output. 

Personally I would consider this a less desirable option than the initial two.

**Comment by tauoverpi** [comment]
Would generating one from the [official grammar](https://github.com/ziglang/zig-spec/tree/master/grammar) spec be worth it as an option? It would motivate keeping the working spec in sync with the compiler and an [Earley parser](https://en.m.wikipedia.org/wiki/Earley_parser) using that spec directly could be used to avoid having to update the javascript side.

**Comment by alwinb** [comment]
Oh this looks like something I can do!

**Comment by alwinb** [comment]
Tokenisation isn't hard, but now I'm kind of in the belly of the whale trying to turn the thing I made into a parser proper, using a bit of additional state for nested contexts and getting ready to apply the shunting yard for expression parsing.

I kind of want to keep working on that for while before I break my flow and spend time on touch ups and making a github repo. In any case, feel free to poke me if something is needed very soon, and I'll try my best.

By the way, @tauoverpi if you are interested in _general_ parsing algorithms there's a fairly recent paper "[Parsing with Pictures]" and a [talk] about it that is very neat (well, at least I think it is)!

[Parsing with Pictures]: https://www.semanticscholar.org/paper/Parsing-with-Pictures-Pingali/cdbce7872b7d5281c5dff391a2612772b1fa043d
[talk]: https://www.youtube.com/watch?v=eeZ3URxd8Wc

**Comment by alwinb** [comment]
He, you could have added something like, "thank you for taking an interest, but I'll close with this one instead".
I was quite hopeful and excited that I'd be able to do something really cool for this, so this is kind of disappointing.

**Comment by zimmi** [comment]
> He, you could have added something like, "thank you for taking an interest, but I'll close with this one instead". I was quite hopeful and excited that I'd be able to do something really cool for this, so this is kind of disappointing.

If it's any consolation, I'm watching the talk you referenced and it's very interesting, so thank you for that! I'm only following the zig project from a distance, but I'm sure that if you come up with a PR that improves on the status quo, it will be considered.

**Comment by kristoff-it** [comment]
> He, you could have added something like, "thank you for taking an interest, but I'll close with this one instead".
> I was quite hopeful and excited that I'd be able to do something really cool for this, so this is kind of disappointing.

Sorry @alwinb, development of Autodoc is still tied to real-time communication in the big Zig Discord server (which hosts a #autodoc channel). I'm still new to creating issues for people to take on and in this case I created this one mostly to get some help in breaking the stalemate between wasm and JS. In the end we came to a conclusion in voice chat and then went forward with an implementation right away, which means that we didn't even notice your comment where you stated you were working on a solution (also because this issue was not about doing any work directly but rather evaluating wasm vs js for this).

If you're still interested in contributing to Autodoc, pinging me to ask to be assigned an issue will ensure we don't have concurrency issues. I'm still new to the job of assigning issues to people so explicit communication will help in avoiding misunderstandings.

Alternatively you can wait for Autodoc to mature some more, at some point it won't need big strokes of paint anymore and you will most certainly find plenty of simple, well-packaged issues that don't require any coordination past a PR review.

**Comment by alwinb** [comment]
Thank you for your reply! It is all good. And it was/is a fun challenge and a really good way to learn the language much more deeply, so nothing lost, plenty gained.

I might come up with some remarks about the grammar and/ or specification things; that and helping out with autodoc should be a great fit for my skill-set. And I love this project, so it would be great to be a part of it.

I do need to find a bit of time to reorganise, after that I'll get in touch.
Is the #autodoc channel open for anyone to join? I guess it's time for me to finally try out discord ;)
