### ISSUE TITLE
Cannot use std.io.getStdOut() inside non-main function

### ISSUE THREAD

**Issue by odiferousmint** [ziglang/zig#1587]
I am using `zig 0.2.0`, and I cannot use `std.io.getStdOut()` inside a non-main function. I tried to pass it as a parameter to this function but it says:

```
/home/foo/zig/stdout.zig:3:25: error: 'File' is private
pub fn testfn(fd: std.io.File) void {
```

Example code:

```zig
const std = @import("std");

pub fn testfn(fd: std.io.File) void {
    try fd.write("Hello from testfn()!\n");
}

pub fn main() !void {
    var stdout = try std.io.getStdOut();
    try stdout.write("Hello, world!\n");
    testfn(stdout);
}
```

If I call `std.io.getStdOut()` from `testfn()`, I get:

```
/home/foo/zig/stdout.zig:4:23: error: expected type 'void', found 'WindowsGetStdHandleErrs'
    var stdout_file = try std.io.getStdOut();
                      ^
```

I tried to get the type through passing an incorrect type, it said `error: expected type 'i32', found 'File'`, but apparently `File` does not exist, hence why I tried to use `std.io.File`.

What I am trying to do is this:

```zig
while (i < 10) : (i += 1) {
  <somehow print i to stdout>
}
```

`warn` does not work because `i` is not a constant.

Older versions of `zig` had `std.io.printf`, but I am not exactly sure what I am supposed to use as a replacement. Ideas? Thanks in advance.

**Comment by tiehuis** [comment]
`File` is actually declared publically in `std.os.File`, not `std.io.File`. Unfortunately the error message isn't too helpful since it is imported in `std.io` so you get that visibility error.

Here is an example of using a stream in another function and passing stdout which may help.

```
const std = @import("std");

fn output(stream: *std.io.FileOutStream.Stream, s: []const u8) !void {
    return stream.print("your string is {}\n", s);
}

pub fn main() !void {
    var stdout_file = try std.io.getStdOut();
    var stdout_stream = std.io.FileOutStream.init(stdout_file);
    var stdout = &stdout_stream.stream;

    try output(stdout, "foo");
}
```

**Comment by Hejsil** [comment]
> If I call `std.io.getStdOut()` from `testfn()`, I get:
> 
> ```
> /home/foo/zig/stdout.zig:4:23: error: expected type 'void', found 'WindowsGetStdHandleErrs'
>     var stdout_file = try std.io.getStdOut();
>                       ^
> ```

This error message is really bad, but basically, you are trying to return the error `WindowsGetStdHandleErrs` (by using the `try` keyword), but your function is marked as not being able to fail (add `!` in front of `void` to allow returning errors).

**Comment by tiehuis** [comment]
Ahh, and this is for the latest master, and not 0.2.0. Would recommend using the pre-built master downloads on https://ziglang.org/download/ since we are at the tail-end of the release cycle (0.3.0 this week) so 0.2.0 is quite out of date.

**Comment by odiferousmint** [comment]
@tiehuis Thank you for that example!
@Hejsil It does work when I use `!void`, thank you!

`zig version` returns `0.2.0`, so I assume it is `0.2.0`. It has been a while but IIRC I downloaded it from either GitHub Releases or https://ziglang.org/download/. I will probably wait for `0.3.0`.

Thanks for the help!

**Comment by tiehuis** [comment]
Master will still specify the latest release plus the commit hash so you may be fine. Think there is an improvement here in versioning we can do but I'll leave that for another issue.
