### ISSUE TITLE
Union field pointers have incorrect alignment

### ISSUE THREAD

**Issue by mlugg** [ziglang/zig#15878]
### Zig Version

0.11.0-dev.3312+ab37ab33c

### Steps to Reproduce and Observed Behavior

```zig
test {
    const U = union { a: u32 };
    var u: U align(1) = .{ .a = 100 };
    @compileLog(@TypeOf(&u.a)); // @as(type, *u32)
}
```

### Expected Behavior

`@as(type, *align(1) u32)`

**Comment by i0bs** [comment]
I've been running into this issue lately, I was wondering if it was just me or not. Thanks for highlighting @mlugg

**Comment by andrewrk** [comment]
Reverted in 43c98dc11567eeb38be041c7dad179c53156f3df

**Comment by jacobly0** [comment]
Unreverted in 2282c278850e29af81e463d55c81fa08855823f8
