### ISSUE TITLE
LLVM assertion "Ptr must be a pointer to Val type!"

### ISSUE THREAD

**Issue by UniqueID1** [ziglang/zig#1588]
```
pub fn main() void {
    var a: u32 = 0;
    var ptr: *c_void = &a;
}
```

**Comment by andrewrk** [comment]
Wow, this is the first time anyone tried to do anything other than immediately `@ptrCast` a `*c_void`! Well, or at least the first time someone bothered to report about it :-)

**Comment by UniqueID1** [comment]
Haha, well I believe LLVM didn't catch this issue until now in version 7. So you've accidentally had an implicit cast feature for quiet a while which no one reported :)
