### ISSUE TITLE
How to force run tests ignore cache

### ISSUE THREAD

**Issue by tisonkun** [ziglang/zig#15882]
Is there an option to force run tests instead of hitting cached and skipped?

**Comment by r00ster91** [comment]
You could try clearing your cache `rm -rf zig-cache`.

There are also these options:
```
$ zig build -h | grep -i cache
  --cache-dir [path]           Override path to local Zig cache directory
  --global-cache-dir [path]    Override path to global Zig cache directory
```
So you could temporarily change your cache directory for one invocation to an empty one which means it will start with a cold cache.

**Comment by tisonkun** [comment]
@r00ster91 Thank you for sharing this information!

Although I may expect an option to force rerun tests, this workaround can work now.
