### ISSUE TITLE
How to ask zig build test to print all tests executed?

### ISSUE THREAD

**Issue by tisonkun** [ziglang/zig#15883]
> That is another change that happened during the build runner re-write, on success it prints nothing.
You can output a summary with `zig build test -fsummary` which will show the number of successful tests.
>
> _Originally posted by @leecannon in https://github.com/ziglang/zig/issues/15586#issuecomment-1536363342_
            

But it should be useful for report generating - I need to know what test cases are exactly run and do further analyze or report.

**Comment by DraagrenKirneh** [comment]
There is an open issue on this https://github.com/ziglang/zig/issues/15635 which describes the problem of -fsummary not listing all the tests run.

**Comment by tisonkun** [comment]
Thank you! Then I will close this in favor of #15635.
