### ISSUE TITLE
Test block doesn't run defer statement.

### ISSUE THREAD

**Issue by andrewCodeDev** [ziglang/zig#15890]
### Zig Version

0.11.0-dev.3312+ab37ab33c

### Steps to Reproduce and Observed Behavior

I was following the tutorials on the Zig documentation for the multiple defer statements and wrote the following:

```
const std = @import("std");

test "Defer Multiple" {

    std.debug.print("\n0...", .{ });
    
    defer {
        std.debug.print("\n3...", .{ });
    }
    defer {
        std.debug.print("\n2...", .{ });
    }
    defer {
        std.debug.print("\n1...", .{ });
    }
}
```
When running this block of code with zig test, the output was:

```
Test [1/1] test.Defer Multiple... 
0...
1...
2...
All 1 tests passed.
```

### Expected Behavior

```
Test [1/1] test.Defer Multiple... 
0...
1...
2...
3...
All 1 tests passed.
```

**Comment by mlugg** [comment]
Duplicate of #6856. In general, you shouldn't use stdio in tests

**Comment by andrewCodeDev** [comment]
Thanks for the quick response - I'll go look at that other issue and familiarize myself with it.

I see now that the expect function signals a failure through error handling which inadvertently answers my more fundamental question.

Much appreciated!
