### ISSUE TITLE
std.http.Client HTTP/1.1 req.wait() will hang when sending request to google oauth endpoints

### ISSUE THREAD

**Issue by edyu** [ziglang/zig#15902]
### Zig Version

0.11.0-dev.3312+ab37ab33c

### Steps to Reproduce and Observed Behavior

use the new std.http.Client, when calling req.wait() using HTTP/1.1 (which is the default btw) to either .POST (or the following .GET) to the Google OAuth endpoints, wait() will likely wait forever. In my test, if there is an error (such as wrong client_id or wrong redirect_uri), google will return right away. However, on a correctly formatted request, using HTTP/1.1, wait() will hang forever (well at least a long long time like a minute or more) until I kill it using kill -9 or something similar.
I've tried different things such as setting the Connection: close in the headers or appending extra "\r\n\r\n" to the end of the post body. There are occasional times (I'm guessing 5% of the requests) where the request would actually go through and then it would either hang at the next .GET request.
The .POST request goes to  `https://oauth2.googleapis.com/token`. The following .GET request goes to `https://www.googleapis.com/oauth2/v3/userinfo`. You can't call the .GET without getting the code returned by the first .POST.
Btw, using HTTP/1.1 with another oauth endpoint such as Github would work. And I know using HTTP/1.1 with google with another implementation such as using either `curl` or the Julia HTTP library would work.

### Expected Behavior

I would expect either there is a way to timeout and print out the bytes received so far so we can better debug the situation and ideally would just work. HTTP/1.1 vs HTTP/1.0 shouldn't be an issue and both should just work. I'm reporting this hopefully so we can get to the bottom of this and fix the underlying issue.

**Comment by edyu** [comment]
Here is some code to illustrate what I mean
[workaround](https://github.com/beachglasslabs/beachtube/blob/master/src/oauth2_provider.zig#L206) for setting to HTTP/1.0 as workaround.
[req.wait()](https://github.com/beachglasslabs/beachtube/blob/master/src/oauth2_provider.zig#L227)

**Comment by DraagrenKirneh** [comment]
> I would expect either there is a way to timeout

I updated https://github.com/ziglang/zig/pull/15500 to also include an option for a maximum wait timeout in Client.zig 
`var req = try http_client.request(.GET, uri, h, .{ .wait_timeout = ... });`

**Comment by edyu** [comment]
> > I would expect either there is a way to timeout
> 
> I updated #15500 to also include an option for a maximum wait timeout in Client.zig `var req = try http_client.request(.GET, uri, h, .{ .wait_timeout = ... });`

Having a timeout is great. Thank you. However, I still think it would be important (but sorry I don't know how) to figure out why would it hang in 1.1 but not in 1.0. It's most likely related to keepalive but I don't see where it could be making it hang. 
As per requested on the zig discord, I checked `req.response.status` in `std/http/Client.zig` before line 752 and the result is `http.status.ok`.

**Comment by DraagrenKirneh** [comment]
The infinite hang might be the same as https://github.com/ziglang/zig/issues/15710 where it looks like the issue is caused by some off by one error when reading/parsing chunked data, and I guess it works using http 1.0 because content is then sent with content-length instead of chunked.

**Comment by edyu** [comment]
So I tested using the latest zig version 0.11.0-dev.3771+128fd7dd0
And tried to do google oauth2 (which was the original reason for filing this bug and saw the following error:

```
thread 454124 panic: reached unreachable code
/snap/zig/7754/lib/std/debug.zig:258:14: 0x356e06 in assert (blocktube)
    if (!ok) unreachable; // assertion failure
             ^
/snap/zig/7754/lib/std/http/Client.zig:202:15: 0x51fbfb in readAtLeast (blocktube)
        assert(len <= buffer.len);
              ^
/snap/zig/7754/lib/std/http/Client.zig:238:32: 0x439ab7 in read (blocktube)
        return conn.readAtLeast(buffer, 1);
                               ^
/snap/zig/7754/lib/std/http/protocol.zig:586:52: 0x439553 in read__anon_17024 (blocktube)
                        const nread = try conn.read(buffer[out_index..][0..can_read]);
                                                   ^
/snap/zig/7754/lib/std/http/Client.zig:631:53: 0x41062e in transferRead (blocktube)
            const amt = try req.response.parser.read(&req.connection.?.data, buf[index..], req.response.skip);
                                                    ^
/snap/zig/7754/lib/std/io/reader.zig:27:26: 0x5733c8 in read (blocktube)
            return readFn(self.context, buffer);
                         ^
/snap/zig/7754/lib/std/compress.zig:23:51: 0x573f15 in read (blocktube)
            const amt = try self.child_reader.read(buf);
                                                  ^
/snap/zig/7754/lib/std/io/reader.zig:27:26: 0x523f48 in read (blocktube)
            return readFn(self.context, buffer);
                         ^
/snap/zig/7754/lib/std/io/reader.zig:46:42: 0x523df4 in readAtLeast (blocktube)
                const amt = try self.read(buffer[index..]);
                                         ^
/snap/zig/7754/lib/std/io/reader.zig:34:31: 0x43f16d in readAll (blocktube)
            return readAtLeast(self, buffer, buffer.len);
                              ^
/snap/zig/7754/lib/std/io/reader.zig:55:46: 0x40ebdc in readNoEof (blocktube)
            const amt_read = try self.readAll(buf);
                                             ^
/snap/zig/7754/lib/std/io/reader.zig:256:31: 0x40eae0 in readBytesNoEof__anon_16142 (blocktube)
            try self.readNoEof(&bytes);
                              ^
/snap/zig/7754/lib/std/compress/gzip.zig:48:60: 0x40d37e in init (blocktube)
            const header = try hashed_reader.readBytesNoEof(10);
                                                           ^
/snap/zig/7754/lib/std/compress/gzip.zig:155:44: 0x40d238 in decompress__anon_16099 (blocktube)
    return Decompress(@TypeOf(reader)).init(allocator, reader);
                                           ^
/snap/zig/7754/lib/std/http/Client.zig:731:65: 0x3e1a32 in wait (blocktube)
                            .gzip = std.compress.gzip.decompress(req.client.allocator, req.transferReader()) catch return error.CompressionInitializationFailed,
                                                                ^
/home/ed/ws/zig/blocktube/src/oauth2_provider.zig:223:25: 0x3dd3fe in getTokenInfo (blocktube)
            try req.wait();
                        ^
```

**Comment by truemedian** [comment]
All associated related issues have been closed/merged. Can you verify that this has been fixed for you?

**Comment by edyu** [comment]
Yes it has. HTTP/1.1 to google oauth works now. Thanks.
