### ISSUE TITLE
bug: tuple of `comptime_int`s allowed to be in a `var`

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#15923]
### Zig Version

0.11.0-dev.3332+76aa1fffb

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() !void {
    var buffer: [100]u8 = undefined;
    var numbers = .{ 1, 2, 3, 4, 5 };
    const slice = try std.fmt.bufPrint(buffer[0..], "{d}", .{numbers[0]});
    std.debug.print("{s}", .{slice});
}
```

```
[meghan@nixos]$ zig2 run test.zig 
1
```

### Expected Behavior

a compile error saying `numbers` needs to be `const`

similar to the error when you do `var numbers`
`error: variable of type 'comptime_int' must be const or comptime`
`note: to modify this variable at runtime, it must be given an explicit fixed-size number type`

**Comment by r00ster91** [comment]
```
z.zig:7:20: error: value stored in comptime field does not match the default value of the field
        numbers[0] += 1;
        ~~~~~~~~~~~^~~~
```
The compile error upon trying to mutate is also a bit weird. But it's saying that the value should be the same. `numbers[0] = 1` works.

**Comment by mlugg** [comment]
Not a bug, as implied by r00ster91's error message the fields are comptime (since the init values given are comptime-known) and thus can be of comptime-only types. (this means `@sizeOf(@TypeOf(numbers)) == 0` here)

**Comment by nektro** [comment]
opened this in the same spirit as https://github.com/ziglang/zig/issues/224
