### ISSUE TITLE
Match non-anon struct literal syntax with anon

### ISSUE THREAD

**Issue by bangseongbeom** [ziglang/zig#15922]
@andrewrk on https://github.com/ziglang/zig/issues/685#issuecomment-528047757 says that anonymous struct literal should be `.{.field = value}` instead of `{.field = value}` because it's like an anonymous enum literal, but for structs/unions.

Anonymous enum literal syntax is fairly seamless. It's just a removal of a type name. `.bar` is a removal of `Foo` in `Foo.bar`.

But this principle does not apply to anonymous struct literals. We need to add a new dot in front of curly braces after remove the type name. So `Foo {.bar = 123}` becomes `.{.bar = 123}`.

It may be worth to apply this 'non-anon to anon principle' to struct (and union, array). Like this:

|| non-anonymous | anonymous |
|---|---|---|
| struct literal | `Foo.{.bar = 123}` | `.{.bar = 123}` |
| enum literal | `Foo.bar` | `.bar` |

Or just remove `.` for struct literal only (this syntax is debated on https://github.com/ziglang/zig/issues/5039):

|| non-anonymous | anonymous |
|---|---|---|
| struct literal | `Foo {.bar = 123}` | `{.bar = 123}` |
| enum literal | `Foo.bar` | `.bar` |

**Comment by tauoverpi** [comment]
It may also be valuable to have a look at https://github.com/ziglang/zig/issues/5038 which would also solve this.

**Comment by Vexu** [comment]
`Foo.{.bar = 123}` was the syntax for a short period for another reason but was then reverted when a different solution was found because people didn't like that syntax: #760

**Comment by bangseongbeom** [comment]
Thanks for sharing the various syntax proposals! Helped me a lot.
