### ISSUE TITLE
String literal sentinel is 0xAA if it's dereferenced from a `const`

### ISSUE THREAD

**Issue by squeek502** [ziglang/zig#15944]
### Zig Version

0.11.0-dev.3332+76aa1fffb

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

test "var and const" {
    // The byte at [3] in the dereferenced array will be 0x00 (expected)
    var var_str = "abc";
    const var_derefed = var_str[0 .. var_str.len + 1].*;

    // The byte at [3] in the dereferenced array will be 0xAA (unexpected)
    const const_str = "abc";
    const const_derefed = const_str[0 .. const_str.len + 1].*;

    try std.testing.expectEqualSlices(u8, &var_derefed, &const_derefed);

    // Just to confirm that the sentinel is actually zero in the derefed vars
    try std.testing.expectEqual(@as(u8, 0), const_derefed[3]);
}
```
```
Test [1/1] test.var and const... slices differ. first difference occurs at index 3 (0x3)

============ expected this output: =============  len: 4 (0x4)

61 62 63 00                                       abc.

============= instead found this: ==============  len: 4 (0x4)

61 62 63 AA                                       abc.

================================================

Test [1/1] test.var and const... FAIL (TestExpectedEqual)
```

Note that this does pass for both `var` and `const`:

```zig
test "accessing the terminator" {
    var var_str = "abc";
    try std.testing.expectEqual(@as(u8, 0), var_str[var_str.len]);

    const const_str = "abc";
    try std.testing.expectEqual(@as(u8, 0), const_str[const_str.len]);
}
```
(it only reproduces when dereferencing the string literal and including the terminator)

### Expected Behavior

The test to pass with the `[3]` byte in both `_derefed` variables being `0x00`

**Comment by Avokadoen** [comment]
I was under the impression that this would only be defined for `[:0]const u8`?

**Comment by squeek502** [comment]
The type of a string literal is `*const [N:0]`, or from the language reference:

> String literals are constant single-item [Pointers](https://ziglang.org/documentation/master/#Pointers) to null-terminated byte arrays. The type of string literals encodes both the length, and the fact that they are null-terminated, and thus they can be [coerced](https://ziglang.org/documentation/master/#Type-Coercion) to both [Slices](https://ziglang.org/documentation/master/#Slices) and [Null-Terminated Pointers](https://ziglang.org/documentation/master/#Sentinel-Terminated-Pointers). Dereferencing string literals converts them to [Arrays](https://ziglang.org/documentation/master/#Arrays).

https://ziglang.org/documentation/master/#String-Literals-and-Unicode-Code-Point-Literals

**Comment by Avokadoen** [comment]
This is very good to know when converting between. Thanks for taking the time to clarify 🙏
