### ISSUE TITLE
Add option in `zig fmt` to set or customize max column length

### ISSUE THREAD

**Issue by bauripalash** [ziglang/zig#15964]
Currently, there is no option (at least I couldn't find one) in `zig fmt` to customize the max column length; personally, I prefer 80, but zig fmt is doing its own thing.

I would like to propose a command line flag in `zig fmt`  command to set max column width.

**Comment by nektro** [comment]
https://github.com/ziglang/zig/issues/1003#issuecomment-388524692 zig fmt so far has a policy of no options

commas can be used to explicitly delimit line breaks however,

```zig
var foo = [_]u8{ 0, 1, 2, 3, 4, 5, 6, };
```

will get subsequently transformed into:

```zig
var foo = [_]u8{
  0,
  1,
  2,
  3,
  4,
  5,
  6,
};
```

this works for array and struct initializers, function calls, function parameters, and more

specifically for arrays, grids are also possible. for instance the below is stable

```zig
var foo = [_]u8{
  0, 1, 2,
  3, 4, 5,
  6,
};
```

**Comment by bauripalash** [comment]
Thanks for the clarification.
