### ISSUE TITLE
document translate-c

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1596]
* [ ] the CLI API
 * [ ] mention `--verbose-cimport`
 * [ ] what happens when something can't be translated
 * [ ] macros
 * [ ] explain the concept of using translate-c instead of `@cImport`

**Comment by ehaas** [comment]
I'm willing to have a go at this - should it just get its own section in `langref.html.in`?

**Comment by Vexu** [comment]
> should it just get its own section in `langref.html.in`?

Somewhere near [the C section](https://ziglang.org/documentation/master/#C) would be good.
