### ISSUE TITLE
Pass pointer to builder when creating a Step struct

### ISSUE THREAD

**Issue by tomc1998** [ziglang/zig#1597]
Been poking around in build.zig to try and understand the build system. Here's what I want to accomplish:

* Create whatever additional directories need to be created
* Clone dependencies into directories
* Build with whatever (make / cmake)

So, I want to create a custom step for each of these, and execute arbitrary commands. I create a step with `b.step(<name>, <desc>);`. However, the step's makeFn takes a `*Step`, and the `Step` struct doesn't contain a reference to the `Builder`, so I can't use the `Builder.exec(...)` function to execute commands!

Unless there's another (undocumented?) way of running arbitrary commands in a portable manner, I'd have to resort to importing C into the build script - can I even do that?

What's the solution to this? I figured a decent workaround is to add a `*Builder` to the `Step` struct?

**Comment by andrewrk** [comment]
In case you didn't see the [IRC log](https://freenode.irclog.whitequark.org/zig/2018-09-27):

```
03:13 <andrewrk> tom1998, here's an example: https://github.com/andrewrk/tetris/blob/29f50a199d299fa95db5d923f2ac4891b7fa4c5a/build.zig#L27
03:14 <andrewrk> and yes if something isn't available in pure zig then libc is a good solution 
```

Doing something non-trivial in zig build system right now is a bit of a mess. The Zig Build System is an important feature of zig but we're just not quite to the point where it's high quality yet.

So you might consider, for now, using make / cmake as your build system and issuing `zig build-exe` or `zig build-lib` commands as you would for a C compiler.

If you still want to try to use zig build, I'd be happy to help you try to wrangle the API.

**Comment by tomc1998** [comment]
Ah, sorry! My client's pretty dodgy, sometimes it doesn't make a noise for a new message:P

After last night I poked around a bit more, and I've seen the tetris example already & read the source for the command step stuff. It's just a bit of a pain to make commands run in sequence - for example, `mkdir x`, `cd x`, `cmake ..`, `make`, `mv libsomething.a ..`, `cd ..`

Just either adding a `*Builder` to the `*Step` struct would help hugely - then we could define a make function like this

```
fn make(*Step step) !void {
    _ = try step.builder.exec([][]const u8{"mkdir", "x"});
    _ = try step.builder.exec([][]const u8{"cd", "x"});
    _ = try step.builder.exec([][]const u8{"cmake", ".."});
}
```

Obviously still a bit messy, but assuming you're against a DSL for the build system this is pretty much as good as it could be I reckon.

The other possibility would be to add a helper function that didn't require a builder, which I was surprised to see didn't exist already. Now I've had more of a look around it looks like it's because you need to allocate to capture the result of the process (?)

This is assuming I've understood the CommandStep stuff right? Lack of docs is pretty killer;) I'd be happy to contribute some docs about the build system if I ever get anything figured out:P
