### ISSUE TITLE
std.mem.readPackedIntLittle and std.mem.readPackedIntBig are not marked as pub

### ISSUE THREAD

**Issue by ABlobOfGarbage** [ziglang/zig#16048]
### Zig Version

0.11.0-dev.1635+d09e39aef

### Steps to Reproduce and Observed Behavior

Try to compile a program that uses those functions.

### Expected Behavior

I don't see a reason for them to be private and i needed to use them for a project i'm working on.
I modified the file on my system to make them public, i'm too lazy to do all the stuff needed to make a pull request so i just did it this way.

**Comment by jacobly0** [comment]
`std.mem.readPackedIntLittle(T, bytes,  bit_offset)` is the same as `std.mem.readPackedInt(T, bytes, bit_offset, .Little)` and `std.mem.readPackedIntBig(T, bytes,  bit_offset)` is the same as `std.mem.readPackedInt(T, bytes, bit_offset, .Big)`.

**Comment by ABlobOfGarbage** [comment]
Yes but std.mem.writePackedIntLittle and std.mem.writePackedIntBig are marked as pub so I don't see why the read functions should be private
