### ISSUE TITLE
excessive stage1 memory usage

### ISSUE THREAD

**Issue by tomc1998** [ziglang/zig#1606]
If I declare an array like so, the compiler memory usage rockets to about 2gb:

```
const std = @import("std");

pub fn main() error!void {
    var my_val = [][1024]?f32{
        []?f32{null} ** 1024
    } ** 1024;
    my_val[100][300] = 1.0;
}
```

I'm pretty sure this would overflow the stack in an actual example, BUT this issue persists for global variables.

Just a heads up to people allocating large amounts of memory at compile time (rather than with malloc), be warned! My computer became totally unresponsive as the compiler just ate up memory.

I remember somewhere it was mentioned that the stage 1 compiler was very memory inefficient, PLUS you'd realistically just dynamically allocate this amount of memory, that being said - 2gb memory is quite a lot;)

**Comment by andrewrk** [comment]
Duplicate of #471
