### ISSUE TITLE
Help: Is it secure or right to return a stack struct value in function at runtime

### ISSUE THREAD

**Issue by sogwms** [ziglang/zig#16068]
code like this:
```zig
const Pin = struct {
    xxx,
    xxx,

    pub fn foo(self:Self) void {
        xxx;
    }
};

fn foo(xxx) Pin {
    xxx;

    return Pin {xxx};
}

fn main() void {
    var tmp = foo();
    tmp.foo();
}

```

**Comment by sogwms** [comment]
sorry for asking questions here, but it will be very important for my projects, 🙏

**Comment by yujiri8** [comment]
Yes, it's fine to return structs by value on the stack.

You should ask in one of the community spaces next time. You might get an answer faster than by abusing the issue tracker

**Comment by yujiri8** [comment]
I recommend the zig matrix room. I use it whenever I have questions and usually get quick answers

**Comment by squeek502** [comment]
> You should ask in one of the community spaces next time

Just to make it easier, the list is here: https://github.com/ziglang/zig/wiki/Community

**Comment by sogwms** [comment]
thanks very much
