### ISSUE TITLE
allow slicing single-item pointer from comptime-known [0..1]

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#16075]
```zig
const std = @import("std");
const expect = std.testing.expect;
const assert = std.debug.assert;

test "slice single-item pointer with 0..1" {
    var x: i32 = 1234;
    const p = &x;
    const a = p[0..1];
    comptime assert(@TypeOf(a) == *[1]i32);
    try expect(a[0] == 1234);
}
```

This test should pass. If start or end is not compile-time known, it should continue to be a compilation error.

Related:
 * #3156
 * #14673

**Comment by mlugg** [comment]
This is ambiguous:
```zig
var a: [*]u8 = something;
_ = a[0..1]; // is this a *[1]u8 or a *[1][*]u8?
```
This comes up for any sliceable type. I do think there should be an explicit syntax for this, but I don't think this proposal makes a good choice. We could potentially introduce a completely new syntax instead - maybe `[&]x`?

**Comment by andrewrk** [comment]
Status quo already has the best answer to that question:

```
const std = @import("std");
const assert = std.debug.assert;

test "single-item ptr of array" {
    var a: *[10]u8 = undefined;
    const p = a[0..1];
    comptime assert(@TypeOf(p) == *[1]u8);
}
```

Slicing a single-item pointer to an array has well-defined semantics that take priority over this new `[0..1]` thing. You'd have to be waaay out in generic crazy land for this to have any chance of causing a bug. The failure mode for the confusion you are highlighting is a compile error. I think this is a no-brainer.

**Comment by Pyrolistical** [comment]
fyi the intermediate const isn't needed if you are willing to use parens:
```zig
var x: i32 = 1234;
const a = (&x)[0..1];
```
