### ISSUE TITLE
Compiler looses alignment information when taking a reference to an over-aligned field

### ISSUE THREAD

**Issue by matklad** [ziglang/zig#16134]
### Zig Version

0.11.0-dev.3731+c6e2e1ae4

### Steps to Reproduce and Observed Behavior

```zig
λ cat get-align.zig
const std = @import("std");

const S = extern struct {
    large: u64 = 0,
    small: [8]u8 = [_]u8{0} ** 8,
};

fn log_alignment(ptr: anytype) void {
    std.debug.print("{}\n", .{@typeInfo(@TypeOf(ptr)).Pointer.alignment});
}

pub fn main() void {
    const s = S{};
    log_alignment(&s.small);
}

λ zig run get-align.zig
1
```

### Expected Behavior

8

The struct is aligned, so we statically know that the field is overaligned.

**Comment by matklad** [comment]
Relevant code is here:

https://github.com/ziglang/zig/blob/5804f3f75716ee77382880954cf73cd4005f33f7/src/Sema.zig#L25929-L25932

**Comment by matklad** [comment]
This probably wants to be reopened, as the fix was reverted.

**Comment by andrewrk** [comment]
Oops, apologies for not doing that earlier.

**Comment by jacobly0** [comment]
Unreverted in f571438fc0010c0c45f79a2f709161a324c5a164
