### ISSUE TITLE
The new `std.process.exit` API

### ISSUE THREAD

**Issue by wooster0** [ziglang/zig#16135]
So in #16094 after some practical prototyping I've come up with a more solid plan on how to make the exit API as well as the `main` return type cross-platform. Here it is:

`u8` or `!u8` are no longer valid return types of `main`. If you want to return OS-dependent exit statuses, you need to use a union `std.process.ExitStatus`.
The whole API would roughly look like this:
```zig
const std = @import("std");

// x, y, and z are just some bools

pub fn main() !std.process.ExitStatus {
    if (z) a();

    if (x) {
        return .success;
    } else if (y) {
        return .failure;
    } else {
        return .{ .specific = 5 }; // assume we're on an OS which uses integers for exit status.
                                   // here we get to decide which OSs we want to support.
    }

    if (x and z and !y) return error.oh_no; // this continues to work as normal and prints
                                            // "error: oh_no"
}

fn a() void {
    // don't bother propagating to main
    std.process.exit(.success);
}
```
The most common case is to just exit or return from main with an indication success or failure, without a more specific exit status.
`ExitStatus` would look like this:
```zig
pub const ExitStatus = union(enum) {
    /// A general exit status indicating success.
    /// This can be used as a default or when details beyond the fact that execution succeeded are unavailable.
    success: void,
    /// A general exit status indicating failure.
    /// This can be used as a default or when details beyond the fact that execution failed are unavailable.
    failure: void,
    /// A specific operating system-dependent exit status.
    specific: switch (builtin.os.tag) {
        .plan9 => [:0]const u8,
        .uefi => std.os.uefi.Status,
        else => u8,
    },
};
```

Compared to the approach of making `ExitStatus` a different type depending on the OS (the original `pub const ExitStatus = switch (builtin.os.tag) {` approach from #16094), what's proposed here has the advantage that we will ultimately be writing less for cross-platform code.
Compare `std.process.exit(std.process.exit_status_success)` (#16094) and `std.process.exit(.success)` (this issue).

Alternatively, we could introduce yet another type to `std.process`: `std.process.ExitStatusSpecific` or something that would essentially be the PR #16094's current `std.os.ExitStatus`. That though is more complexity and takes kinda longer to understand too. In that case `main` would use direct type `std.process.ExitStatusSpecific` and `std.process.exit` would use union `std.os.ExitStatus`. **This alternative would keep breaking changes much smaller.**

**Long-term however** I believe what I proposed at the top of this issue is worth it even though it's going to break all code where `main` has a return type other than `void` or `!void`.

I would like to know if this would be accepted before I update everything to use this new API because it is certainly a breaking change and a lot of code needs to be adjusted.

**Comment by r00ster91** [comment]
There might also be a better word than "specific". I like "other" but it's not as specific.

**Comment by r00ster91** [comment]
I also have an idea how to make it easier to exhaustively provide a specific exit status for all OSs:
We could add
```zig
pub const ExitStatusSpecific = union(enum) {
    plan9: [:0]const u8,
    uefi: std.os.uefi.Status,
};
```
and use it like `specific: ExitStatusSpecific` in the definition of `std.process.ExitStatus` from above and then use it like this:
```zig
const std = @import("std");
const builtin = @import("builtin");

// x, y, and z are just some bools

pub fn main() !std.process.ExitStatus {
    if (z) a();

    if (x) {
        return .success;
    } else if (y) {
        return .failure;
    } else {
        return switch (builtin.os.tag) {
            .uefi => .{ .uefi = std.os.uefi.Status.WarnUnknownGlyph },
            .plan9 => .{ .plan9 = "hello" },
            .windows => .{ .windows = 5 }, // will compile error: just let the `else` prong handle this!
            else => 5,
        }
    }
}

fn a() void {
    // don't bother propagating to main
    std.process.exit(.success);
}
```
Maybe there's a better way for that though.

**Comment by natecraddock** [comment]
> There might also be a better word than "specific".

Maybe "status" or "code"? Using "status" might be redundant with the union name `ExitStatus`, but it still seems reasonable to me. Especially when using anonymous literals

```zig
std.process.exit(.{ .status = 2 });
```

**Comment by andrewrk** [comment]
Proposal lacks a compelling problem statement.

**Comment by wooster0** [comment]
I guess the main thing this was supposed to fix is that not all OSs use u8 as the data type for exit status, which is currently assumed. The point was then to unify the exit API and the main return type and not just change exit. See start of #16094
