### ISSUE TITLE
document @"identifier" syntax

### ISSUE THREAD

**Issue by thejoshwolfe** [ziglang/zig#1614]
I just checked, and the `@"asdf"` syntax for declaring identifiers doesn't seem to appear in the docs. And in the grammar definition, it doesn't look like `Symbol` is defined anywhere, which I think is where that would be defined.

**Comment by andrewrk** [comment]
The grammar documents the syntax, thanks to @Hejsil's work, and the above commit adds information to https://ziglang.org/documentation/master/#export
