### ISSUE TITLE
Stack usage spike in Debug / ReleaseSafe for large structs

### ISSUE THREAD

**Issue by trgwii** [ziglang/zig#16143]
### Zig Version

0.11.0-dev.3724+32cb9462f

### Steps to Reproduce and Observed Behavior

This is an issue from a user on a Zig Telegram group that does not have a GitHub account.

I believe this has something to do with Zig making way too many temporaries / copies on the stack when struct fields are naively accessed by value.

Compiles and runs fine on ReleaseFast / ReleaseSmall.

Swapping the 3 innermost lines in the nested loops for the commented-out lines make the program compile and run in all build modes, but that's not very ergonomic.

Given the following code:
```zig
const std = @import("std");

const A = struct { b: [128]B };
const B = struct { c: [1024]C };
const C = struct { data: [1024]u8 };

fn fail(a: *A) void {
    var tmp: u8 = 0;
    for (0..128) |i| {
        for (0..1024) |j| {
            for (0..1024) |k| {
                a.b[i].c[j].data[k] = 0;
                // (&(&(&a.b)[i].c)[j].data)[k] = 0;
                tmp = a.b[i].c[j].data[k];
                // tmp = (&(&(&a.b)[i].c)[j].data)[k];
                std.debug.print("{}", .{a.b[i].c[j].data[k]});
                // std.debug.print("{}", .{(&(&(&a.b)[i].c)[j].data)[k]});
            }
        }
    }
}

pub fn main() !void {
    std.debug.print("Size of StructA: {}\n", .{std.fmt.fmtIntSizeBin(@sizeOf(A))});

    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer std.debug.assert(gpa.deinit() == .ok);
    const allocator = gpa.allocator();

    var a = try allocator.create(A);
    defer allocator.destroy(a);

    fail(a);
}
```

```sh
$ zig run bug_report.zig
Size of StructA: 128MiB
Segmentation fault
$ zig run -O ReleaseSafe bug_report.zig
Segmentation fault
```

### Expected Behavior

I expect all build modes to not generate attempts to copy the entire struct / array onto the stack, and instead only access the final location of the rightmost array accessor.

**Comment by jacobly0** [comment]
Fixed by #16179
