### ISSUE TITLE
LLVM16 Assertion failed: EltSize * 8 == EltVT.getFixedSizeInBits() && "Converting bits to bytes lost precision" 

### ISSUE THREAD

**Issue by xxxbxxx** [ziglang/zig#16177]
### Zig Version

0.11.0-dev.3802+b086609de

### Steps to Reproduce and Observed Behavior

https://github.com/ziglang/zig/pull/16142
test "store vector with memset"  disabled for some architectures:
            .wasm32,
            .mips,
            .mipsel,
            .mips64,
            .mips64el,
            .riscv64,
            .powerpc,

because they trigger an assert when using a llvm debug build (during CI):

`Assertion failed: EltSize * 8 == EltVT.getFixedSizeInBits() && "Converting bits to bytes lost precision"`
`(/home/andy/dev/zig-bootstrap/llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp: getVectorSubVecPointer: 9410)`

(The tests  passes with a release llvm build.)

### Expected Behavior

 ```zig 

    var a: [5]@Vector(2, i1) = undefined;
    var b: [5]@Vector(2, u2) = undefined;
    var c: [5]@Vector(2, i4) = undefined;
    var d: [5]@Vector(2, u8) = undefined;
    var e: [5]@Vector(2, i9) = undefined;
    var ka = @Vector(2, i1){ -1, 0 };
    var kb = @Vector(2, u2){ 0, 1 };
    var kc = @Vector(2, i4){ 2, 3 };
    var kd = @Vector(2, u8){ 4, 5 };
    var ke = @Vector(2, i9){ 6, 7 };
    @memset(&a, ka);
    @memset(&b, kb);
    @memset(&c, kc);
    @memset(&d, kd);
    @memset(&e, ke);
    try std.testing.expectEqual(ka, a[0]);
    try std.testing.expectEqual(kb, b[1]);
    try std.testing.expectEqual(kc, c[2]);
    try std.testing.expectEqual(kd, d[3]);
    try std.testing.expectEqual(ke, e[4]);
```

**Comment by alexrp** [comment]
https://github.com/llvm/llvm-project/issues/106345

**Comment by alexrp** [comment]
This appears to be fixed in LLVM 19.
