### ISSUE TITLE
std.json.parseFromSlice docs missing information

### ISSUE THREAD

**Issue by yujiri8** [ziglang/zig#16259]
I thought the fact that it takes an `allocator` parameter meant that it would use that allocator, and so I tried `ArrayList.fromOwnedSlice` on it and got segfaults when trying to append. Seems like the allocations actually made with the ArenaAllocator stored on the Parsed object. parseFromSlice and its kin should document this.

**Comment by andrewrk** [comment]
This is too vague to be an issue. Please submit your suggested documentation enhancement as a pull request.

**Comment by yujiri8** [comment]
Ridiculous take.
