### ISSUE TITLE
Autodoc: enable light / dark theme override using user preferences

### ISSUE THREAD

**Issue by kristoff-it** [ziglang/zig#16257]
In #16251 persisted user preferences were implemented. This issue is about adding to that list also another setting: whether to follow system preferences (default) or to force a light or dark theme.

This will require cleaning up the CSS definitions and to move away from using `prefers-color-scheme`.

For the default case (ie follow system preferences), `window.matchMedia` is useful.

**It is strongly recommended to tackle this issue only after 0.11 is tagged and the new autodoc redesign in `autodoc-guides-sidebar` has been merged**

**Comment by andrewrk** [comment]
I am strongly against this. Prefers-color-scheme is how users declare their preference. Adding application code on top of this is unnecessary at best. The appropriate place for toggling color scheme overrides is at the browser layer.
