### ISSUE TITLE
Type Interference not working with @intFromFloat() and @floatFromInt() when used with Vectors

### ISSUE THREAD

**Issue by SimonLSchlee** [ziglang/zig#16267]
### Zig Version

0.11.0-dev.3859+88284c124

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() void {
    const a: @Vector(2, u32) = .{ 1, 2 };
    const b: @Vector(2, f32) = @floatFromInt(a);
    std.debug.print("{}\n", .{b});
}
```
Output:
```
test.zig:5:32: error: expected float type, found '@Vector(2, f32)'
    const b: @Vector(2, f32) = @floatFromInt(a);
                               ^~~~~~~~~~~~~~~~
```

### Expected Behavior

To convert the int vector to a float vector and infer the type.

**Comment by SimonLSchlee** [comment]
https://ziggit.dev/t/easier-conversion-of-vectors-between-int-and-float/980/2

**Comment by andrewrk** [comment]
cc @mlugg

**Comment by mlugg** [comment]
Note that this isn't a regression - the old logic didn't allow for this either. (But I will fix it up, and check related cast builtins while I'm at it.)

**Comment by mlugg** [comment]
@andrewrk are the following builtins also intended to work on vectors?
`@intToPtr`, `@ptrToInt`, `@boolToInt`

**Comment by lassade** [comment]
Hi, any updates on this issue?

**Comment by andrewrk** [comment]
Yes all three of those should support vector operations

**Comment by mlugg** [comment]
Cool - for the person asking for an update then, I'll try to get on this soon... probably Friday?
