### ISSUE TITLE
os.getRandomBytesDevURandom should check if /dev/urandom is a character device

### ISSUE THREAD

**Issue by euantorano** [ziglang/zig#1626]
Whilst looking at the Zig standard library to get a feel for the language, I noticed that [`os.getRandomBytesDevURandom`](https://github.com/ziglang/zig/blob/master/std/os.zig#L132) doesn't check whether `/dev/urandom` is a valid character device before reading it.

It may be worth looking at some other implementations of getting random data to see how it's done elsewhere:

- [PHP's `random_bytes()`](https://github.com/php/php-src/blob/master/ext/standard/random.c#L85)
- [libsodium's `sysrandom`](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c)

**Comment by andrewrk** [comment]
What does checking whether it's a character device accomplish? Is it just to make sure we're actually getting random data?

**Comment by euantorano** [comment]
Yes, it’s to make sure we’re not on a system that has been compromised in some way to replace the urandom file with some standard file or something
