### ISSUE TITLE
When the compiler is built without LLVM, use Aro to compile C code instead of Clang

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#16269]
After solving #16268 which is a prerequisite to this issue, this issue is to further reduce dependency on Clang by using Aro to compile .c files.

I suggest, at least at first, this happens by taking advantage of translate-c, and then passing the outputted .zig code through the full pipeline. I experimented a bit with upstreaming Aro in #10795 in which I attempted to lower C AST to AIR, and this was my conclusion:

> I'm starting to wonder... should we perhaps lower to ZIR instead of AIR? The integration would be a lot less messy, and it's much more obvious how to parallelize it. One .c file would produce exactly one corresponding ZIR file. 🤔🤔🤔

So the two options I think are worth exploring:
 1. C code => Aro C AST => Translate C AST => zig source code
 2. From there, potentially give an additional lowering to Translate C AST:
    - => zig source code
    - => ZIR 

Another possibility would be straight from Aro C AST to ZIR. There could be additional C-specific ZIR instructions added if necessary.

**Comment by ecstrema** [comment]
Just to be clear, what would be the benefits of using Aro instead of clang? Is it faster, is it because having everything in the same language is best for maintenance? Is it because Aro has some features Clang does not have?

Or is it for zig to become completely self-sufficient, and remove any dependency on code not written in zig?

**Comment by andrewrk** [comment]
The main benefit of using Aro instead of Clang is that it does not depend on Clang and LLVM, which are massive, problematic dependencies for many reasons. According to #16270, the plan is to depend on a third party package that *does* use LLVM and Clang for compiling C and C++ code in a fully clang-compatible manner, however, we still want a Zig binary that does *not* link against LLVM to be able to support, for example, `-target x86_64-linux-musl -lc`, which requires the ability to compile musl libc from source. For that we need a C compiler, but we do not need Clang.

**Comment by andrewrk** [comment]
Instead, we will pursue #2879, untangling the Zig compiler entirely from C/C++. Dealing with the C/C++ ecosystem will move fully to the build system. An Aro package can compete with a Clang package to provide equivalent functionality.
