### ISSUE TITLE
`std.mem.eql()` expects `[]u8` argument when it shouldn't + weird behaviour with `zig build` command

### ISSUE THREAD

**Issue by kamkow1** [ziglang/zig#16262]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

```
src/http.zig:41:43: error: expected type '[]u8', found '[]const u8'
                            } else if (eql(u8, word, "GET")) {
                                       ~~~^~~~~~~~~~~~~~~~~
```

Where `word` is `[]const u8`, but `std.mem.eql()` still expects `[]u8`
More on this bug can be found on a thread I made on ziggit: https://ziggit.dev/t/how-to-compare-strings/953
There's also another bug(?) that `zig build` and `zig build test` do not work the same.

### Expected Behavior

1. I can pass the variable to eql
2. `zig build` and `zig build test` are consistent - both commands should fail if there's an error, even if the error is a result of a bug. As I've mentioned in the ziggit thread, `zig build` passes without errors and warnings, but `zig build test` fails. To add, `zig build-exe` also fails with the same error message as `zig build test`

**Comment by nektro** [comment]
no it doesn't https://github.com/ziglang/zig/blob/master/lib/std/mem.zig#L643C1-L651
and didn't in 0.10 either https://github.com/ziglang/zig/blob/0.10.1/lib/std/mem.zig#L595-L603

**Comment by nektro** [comment]
as the recent comment on the thread suggests I'd try and post a fuller reproduction so that folks have more context to help you out

**Comment by luisricardorc** [comment]
The bug is where the compiler indicate the error.

To reproduce of the error:
`pub const Struct = struct {
    word: []u8,
};

const word: []const u8 = "word";

pub fn main() !void {
    var st: Struct = undefined;
    st.word = @as([]u8, word);
}
`
Error that show:
`pub const Struct = struct {
    word: []u8,
};

const word: []const u8 = "word";

pub fn main() !void {
    var st: Struct = undefined;
    st.word = @as([]u8, word);
}
`

**Comment by travisstaloch** [comment]
reproduces on recent zig version. 
```sh
$ zig version
0.11.0-dev.3834+d98147414

$ zig run /tmp/tmp.zig 
/tmp/tmp.zig:7:1: error: expected type '[]u8', found '[]const u8'
pub fn main() !void {
^~~
/tmp/tmp.zig:7:1: note: cast discards const qualifier
```

@luisricardorc i would recommend to edit the title.  maybe something like 'incorrect location for `cast discards const qualifier` error'.  the current title is misleading in my opinion.

**Comment by nektro** [comment]
you need `@constCast` to make `[]const T` go to `[]T`

but doing that in this case would lead to a segfault if you ever tried modifying `st.word`. in those cases you need to use `allocator.dupe()`

**Comment by kamkow1** [comment]
Hello,
Sorry if the title is misleading, I'll change it soon. Someone on the forum actually helped me solve this by telling me that the error message is the main problem

thanks!

**Comment by travisstaloch** [comment]
seems like this should be re-opened unless its a duplicate
