### ISSUE TITLE
erroneous `embed of file outside package path` error when using absolute path

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#16280]
### Zig Version

0.11.0-dev.3867+ff37ccd29

### Steps to Reproduce and Observed Behavior

Assuming from the path `/home/meghan/src` having a file `test.zig` and `hello.txt`

```zig
const std = @import("std");

pub fn main() !void {
    const x = @embedFile("./hello.txt");

    std.log.info("{s}", .{x});
}
```

```
info: lorem ipsum

```

```zig
const std = @import("std");

pub fn main() !void {
    const x = @embedFile("/home/meghan/src/hello.txt");

    std.log.info("{s}", .{x});
}
```

```
test.zig:4:26: error: embed of file outside package path: '/home/meghan/src/hello.txt'
    const x = @embedFile("/home/meghan/src/hello.txt");
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected Behavior

both samples to pass

**Comment by rohlem** [comment]
could be fixed by refreshing https://github.com/ziglang/zig/pull/15570 (/ redoing the work)

**Comment by nektro** [comment]
why would absolute paths be rejected outright so long as they reference something within the actual package path?

**Comment by rohlem** [comment]
@nektro Source of this seems to be #3393 .
Re-usable projects (aka not written and built on the same file system) definitely benefit from relative paths.
Even on the same file system the project is hardened against being moved / links to the project root changing etc., without having to change the code.
I also assume that with relative paths the compiler (/ build system) has an easier time verifying whether the path does indeed lie within a package's path.

Do you have use case that benefits from using absolute paths instead of relative ones?

**Comment by nektro** [comment]
i use absolute paths in some local-only zigmod-generated zig code. i can look into trying to not use them and report back

**Comment by nektro** [comment]
so i have good news and bad news

the good news is that I was able to get relative imports working
the bad news is that the error still triggers because the file is provided as a `self/files` package dependency and so it is always considered "outside the package path"

some examples:

![image](https://github.com/ziglang/zig/assets/5464072/2b858185-36af-4b15-adbe-29118cd4800d)

![image](https://github.com/ziglang/zig/assets/5464072/9a298726-573a-4ac5-8b8b-f951055707cc)

**Comment by nektro** [comment]
if anyone has suggestions on how I might be able to get around this I'm all ears because otherwise as far as I see this feature is dead in the water

**Comment by nektro** [comment]
this is now fixed in Zigmod as of https://github.com/nektro/zigmod/releases/tag/r88 and I've confirmed that my personal projects that used this feature now compile and run as expected on an unmodified Zig 0.11.0
