### ISSUE TITLE
All firmware API function pointers in `std.os.uefi` should be marked with `callconv(.Win64)`

### ISSUE THREAD

**Issue by oliver-giersch** [ziglang/zig#16309]
Example:

https://github.com/ziglang/zig/blob/de227ace14e09c7c17a60f716b88d2327fee201d/lib/std/os/uefi/tables/boot_services.zig#L25

should become:

```zig
pub const BootServices = extern struct {
    raiseTpl: *const fn (new_tpl: usize) callconv(.Win64) usize, 
    // ...
};
```
Using `callconv(.C)` works when compiling for an `uefi` target, but not in, e.g., in an EFI stub with a different ABI, like the Linux kernel with `CONFIG_EFI_STUB`.

From my understanding, using `callconv(.Win64)` would still be correct for the `uefi` target, but would allow also calling these functions in a strictly greater set of programs, such as EFI-stub OS kernels with no downsides, without having to use ABI conversion wrappers.

Am I correct in my assessment? If so, I would be willing to open a corresponding PR, I just wanted to make sure I am not missing something, first.

**Comment by billzez** [comment]
I also hit this issue.  I would like to compile my efi app with a different ABI.  There are too many libraries out there that expect LP64.

**Comment by r00ster91** [comment]
> I would like to compile my efi app with a different ABI. There are too many libraries out there that expect LP64.

Am I understanding correctly that sometimes the `.C` calling convention is desired but sometimes also the `.Win64` CC? In that case I think we might want to make the CC configurable using a standard library option: https://github.com/ziglang/zig/blob/78eb3c561746a4dd86a67f927d244a3e8f46ad00/lib/std/std.zig#L108
It might look like this:
```zig
    pub const uefi_cc: std.builtin.CallingConvention = if (@hasDecl(options_override, "uefi_cc"))
        options_override.uefi_cc
    else
        .Win64;
```

**Comment by oliver-giersch** [comment]
> Am I understanding correctly that sometimes the `.C` calling convention is desired but sometimes also the `.Win64` CC? In that case I think we might want to make the CC configurable using a standard library option:

Not quite I don't think. The UEFI spec requires all functions to adhere to the Win64 calling convention. It just happens to be that when compiling for the `uefi` target, the `.C` just happens to be the same as the `.Win64` callconv. At least that is my understanding. So `callconv(.Win64)` *should* always be the correct choice, whereas `callconv(.C)` only works when compiling for the `uefi` target.

**Comment by jayschwa** [comment]
From looking at the spec, I don't think `callconv(.Win64)` would apply universally. There are other platforms to support, including 32-bit x86.

https://uefi.org/specs/UEFI/2.10/02_Overview.html#calling-conventions

**Comment by oliver-giersch** [comment]
Ah, it is, of course, more complicated than I initially thought. And I also just saw `.Win64` is x86-64 only. So the combination of target `uefi` and callconv `.C` is trivially correct, but for other UEFI supported architectures it is not quite clear to me which calling convention applies, except for x86-64. I will try to look into this further to find out which zig calling convention maps to each platform in UEFI.

**Comment by oliver-giersch** [comment]
Ok so I've read up on the topic a bit and to me it seems that GCC's `regparm`, which LLVM also has, is indeed the correct calling convention for 32-bit x86 in UEFI, so I'd propose to add the following to `std.os.uefi` and use it for all UEFI function pointers:

```zig
pub const ueficc = switch (@import("builtin").target.cpu.arch) {
    .x86_64 => .Win64,
    .x86 => .regparm,
    else => .C,
};
```

Only problem is, zig's `std.builtin.CallingConvention` does not yet expose LLVM's `regparm`, so that would have to be added at the compiler level (and the stdlib), but that should not be too hard.

In the meantime, I've found a somewhat acceptable workaround for x86-64:

```zig
fn efiCall(fn_ptr: anytype) *const efiABI(@TypeOf(fn_ptr)) {
    return @ptrCast(*const efiABI(@TypeOf(fn_ptr)), fn_ptr);
}

fn efiABI(comptime fn_ptr: type) type {
    const fn_info = @typeInfo(fn_ptr);
    if (fn_info.Pointer) |_| {} else {
        @compileError("type parameter is not a function.");
    }

    var info = @typeInfo(fn_info.Pointer.child);
    if (info.Fn) |_| {} else {
        @compileError("type parameter is not a function.");
    }

    if (info.Fn.calling_convention == .Win64) {
        @compileError("function already has correct calling convention");
    }

    info.Fn.calling_convention = .Win64;
    return @Type(info);
}
```

(this allows casting any `callconv(.C)` function pointer to a `callconv(.Win64)` one)
