### ISSUE TITLE
packed struct endianness and ordering

### ISSUE THREAD

**Issue by tsedan** [ziglang/zig#16304]
### Zig Version

0.11.0-dev.3897+f571438fc

### Steps to Reproduce and Observed Behavior

Take some u32 packed data structure that looks like:
```
        | data1 | flag1 | data2 | flag2 |
bit #: 32      17      16       1       0
```
I *need* the in-memory representation of this struct to be exactly like this; my program relies on the order of the bits to be correct in order to work properly. Basically I need to be able to load the lower or upper 16 bits of the struct individually to get either data1+flag1 or data2+flag2.

### Expected Behavior

At first, I thought, "Okay, easy! Let's just do":
```
const thing = packed struct(u32) {
  data1: u15,
  flag1: bool,
  data2: u15,
  flag2: bool,
};
```
There are several things wrong here.

The first is that packed structs in Zig are defined from least significance to most significance. Meaning that, in the code I just wrote, flag2 would be at the top of the struct, then data2, then flag1, then data1. So already, my code is broken. This fix is not too bad, we just write:
```
const thing = packed struct(u32) {
  flag2: bool,
  data2: u15,
  flag1: bool,
  data1: u15,
};
```
That feels harder to read, but I get why it's this way. If you have two integers, putting one below the other in a C-like struct means it would come after it in memory. So, I get it, fine.

Anyways, there's a bigger issue:

**The reordering "fix" doesn't actually fix my program**. In little endian systems, the bytes are reversed. So in order to *actually* get the order I want, I have to write:
```
const thing = packed struct(u32) {
  flag1: bool,
  data1: u15,
  flag2: bool,
  data2: u15,
};
```
This feels silly. Now I need to have different struct declarations for different endianness-es, and it's annoyingly tedious to work backwards from the struct declaration to the memory order.

I could be missing something. Maybe this behavior is somehow desirable? Maybe this is a particularly hard problem to solve? I'm not sure. I just want my code to be as portable as possible, and I don't want to have to reorder my structs by hand like this. There's gotta be a better way, right?

**Comment by jakehffn** [comment]
> The first is that packed structs in Zig are defined from least significance to most significance...

This is the same as in C. The order of structs in memory is determined by the endian-ness of your system.

>  In little endian systems, the bytes are reversed

The bytes themselves are not reversed. Only representation of the entire struct in memory. Here you do not need to reverse the over of the bytes. In your example struct, the first byte stored in memory would be the first 7 bytes of `data1` and `flag1`. It's little endian, so `flag1` is the least significant bit. 

E.g. look at the following
```zig
const std = @import("std");

const Thing = packed struct(u32) {
  flag1: bool,
  data1: u15,
  flag2: bool,
  data2: u15,
};

pub fn main() !void {
    var thing: Thing = .{
        .flag1 = true, 
        .data1 = 0x1,
        .flag2 = true,
        .data2 = 0x1
    };
    std.debug.print("{X}", .{@as(u32, @bitCast(thing))});
}
```
This outputs `30003` which, in binary, is `00000000 00000011 00000000 00000011`

This is the expected result.
