### ISSUE TITLE
The zig lang hello world make sense: 

### ISSUE THREAD

**Issue by cnmade** [ziglang/zig#16319]
### Zig Version

master

### Steps to Reproduce and Observed Behavior

mkdir hello-world
cd hello-world
zig init-exe
This should output:

info: Created build.zig
info: Created src/main.zig
info: Next, try `zig build --help` or `zig build run`
Running zig build run should then compile the executable and run it, ultimately resulting in:

info: All your codebase are belong to us.
Congratulations, you have a working Zig installation!

### Expected Behavior

Is it dangerous to using zig lang ?

Every lines of code written with zig lang is belong to you?

fantastic.

It really scare me .

Is it offical announce that zig lang own all source code of each programmer ?

**Comment by cnmade** [comment]
This is about question about by law, is it safe to using zig lang?
No law conflict ?

**Comment by zraineri** [comment]
It's just a reference to a [meme](https://en.wikipedia.org/wiki/All_your_base_are_belong_to_us#:~:text=%22All%20your%20base%20are%20belong,the%201989%20Japanese%20arcade%20game.)

It has no legal implementations, nothing at all to worry about
