### ISSUE TITLE
UEFI std_err broken

### ISSUE THREAD

**Issue by xdBronch** [ziglang/zig#16328]
### Zig Version

0.11.0-dev.3905+309aacfc8

### Steps to Reproduce and Observed Behavior

```zig
// stderr.zig
const std = @import("std");
const L = std.unicode.utf8ToUtf16LeStringLiteral;

pub fn main() void {
    const con_out = std.os.uefi.system_table.con_out.?;
    const stderr = std.os.uefi.system_table.std_err.?;

    _ = stderr.outputString(L("this should work\r\n"));
    _ = con_out.outputString(L("this works\r\n"));
}
```
compile with `zig build-exe -target x86_64-uefi stderr.zig`

output using ovmf + qemu (`qemu-system-x86_64 -bios /usr/share/edk2-ovmf/x64/OVMF_CODE.fd -hdd fat:rw:. -net none`)
```
FS0:\> stderr.efi
this works

FS0:\>
```

it's for some reason outputting the newline's from stderr but none of the text. i believe this also breaks UEFI's panic function due to it using stderr

### Expected Behavior

should print the text from both functions
```
FS0:\> stderr.efi
this should work
this works
FS0:\>
```

**Comment by truemedian** [comment]
I'm going to guess this is *probably* an upstream issue. To zig `con_out` and `std_err` are the exact same thing, they're both an instance of the SimpleOutputProtocol.

**Comment by xdBronch** [comment]
iiuc this is apparently not meant to work since printing to stderr is not valid in the text mode console so not a zig issue or even necessarily an upstream issue. both newlines being printed is likely an upstream issue though

**Comment by truemedian** [comment]
As a further to the above: stderr is not guaranteed to be written to the graphical rendition of the text mode, from my experimenting I can safely say that OVMF definitely doesn't write stderr to the graphic window by default (how you would change that is also beyond me).

If you're using QEMU and still want to read stderr, use `-serial stdio` and watch for the result in your terminal, as stderr *is* written to the serial console.

If you're on hardware and the UEFI firmware doesn't display stderr in the text console, try attaching a serial device. If that doesn't work, you likely have no way to access stderr.
