### ISSUE TITLE
unreachable decl wrongly elevated to compile error through runtime value

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#16334]
### Zig Version

0.11.0-dev.3934+ba6e5e65a

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() !void {
    var x = foo() orelse y.bar;
    std.log.info("{d}", .{x});
}

fn foo() ?u32 {
    return 43;
}

const y = struct {
    const bar = unreachable;
};
```

```
test.zig:13:17: error: reached unreachable code
    const bar = unreachable;
                ^~~~~~~~~~~
referenced by:
    main: test.zig:4:27
```

converse this with when the unreachable is placed in-line and there is no error

```zig
const std = @import("std");

pub fn main() !void {
    var x = foo() orelse unreachable;
    std.log.info("{d}", .{x});
}

fn foo() ?u32 {
    return 43;
}
```

### Expected Behavior

```
info: 43
```

**Comment by IntegratedQuantum** [comment]
I don't think this would be a good idea. Allowing to rename `unreachable` seems like it could cause a lot of confusion.

Additionally if `unreachable` would behave like any other value then we wouldn't be able to catch `unreachable` code at compile time.
Consider the following code:
```zig
const bar = comptime throwError() catch unreachable;
```
If `unreachable` was handled like other values this would yield a constant `bar: noreturn` that contains `unreachable` and the error would be found at runtime (if found at all).

**Comment by nektro** [comment]
well that's being explicitly evaluated at comptime. conversely `throwError() catch unreachable` \*would\* only create a runtime error.

to go back to my example, i would expect `var x = comptime foo() orelse y.bar;` to yield the status quo error. but `var x = foo() orelse y.bar;` as written should not

**Comment by IntegratedQuantum** [comment]
Why do you think renaming `unreachable` to `bar` should be valid?

By the way in the documentation is mentioned that [unreachable expressions are compile errors.](https://ziglang.org/documentation/master/#At-Compile-Time)
So it seems to me that this is intended behavior.

**Comment by nektro** [comment]
> Why do you think renaming `unreachable` to `bar` should be valid?

what do you mean by this?

> By the way in the documentation it is mentioned that [unreachable expressions are compile errors.](https://ziglang.org/documentation/master/#At-Compile-Time) So it seems to me that this is intended behavior.

this is at comptime again

**Comment by IntegratedQuantum** [comment]
> what do you mean by this?

You are storing `unreachable` in a constant. I would call that renaming.
```zig
const bar = unreachable;
```

> this is at comptime again

Yeah, but so is `const bar = unreachable;` from your code.

**Comment by yujiri8** [comment]
> You are storing unreachable in a constant. I would call that renaming.

So if I write `const x = 5;`, am I renaming `5`? why should that be allowed but `const x = unreachable` not?
