### ISSUE TITLE
'wbnoinvdintrin.h' file not found when using @cImport

### ISSUE THREAD

**Issue by DEC05EBA** [ziglang/zig#1634]
System: Arch Linux
Zig version: 0.3.0 and master build from zig download page

Building and running https://github.com/andrewrk/sdl-zig-demo with `zig build run` results in error:
```
/home/dec05eba/git/sdl-zig-demo/src/main.zig:1:11: error: C import failed
const c = @cImport({
          ^
/usr/lib/zig/include/immintrin.h:351:10: note: 'wbnoinvdintrin.h' file not found
#include <wbnoinvdintrin.h>
         ^
```
I was able to build and run the project with master branch build sometime before 0.3.0 was released

**Comment by DEC05EBA** [comment]
These are the header files that are missing from zig/include directory in the zig 0.3.0 static release archive on zig download page:
```
cldemoteintrin.h
waitpkgintrin.h
movdirintrin.h
pconfigintrin.h
sgxintrin.h
ptwriteintrin.h
invpcidintrin.h
__clang_cuda_libdevice_declares.h
__clang_cuda_device_functions.h
arm_fp16.h
```
After copying the files from zig source code (master branch) to zig/include directory, the zig sdl demo builds and runs.

**Comment by andrewrk** [comment]
Looks like I forgot to add the necessary CMakeLists.txt changes.

**Comment by andrewrk** [comment]
Sorry for the trouble. The next static CI builds will have this fixed.
