### ISSUE TITLE
Unable to Compile C++ Code for iOS or iOS Simulator

### ISSUE THREAD

**Issue by jcalabro** [ziglang/zig#16352]
### Zig Version

0.11.0-dev.3944+2e424e019

### Steps to Reproduce and Observed Behavior

Hello! I'm trying to use Zig to build a large C++ lib for iOS. I am able to build the C++ project fine for macos arm, but when I try to cross compile the same code for `-Dtarget=aarch64-ios` or `-Dtarget=aarch64-ios-simulator`, I get compile errors when attempting to import and use C++ stdlib headers.

I've created a minimal repro which is available [in a gist](https://gist.github.com/jcalabro/a0568cffedf9fccfdb0bb985ca6775c7), complete with an error log. Here's a sample of that log:

```
error(compilation): clang failed with stderr: In file included from /Users/jcalabro/go/src/github.com/jcalabro/trunk/zig/libcpp_ios/mylib.cpp:1:
In file included from /Users/jcalabro/go/src/github.com/jcalabro/trunk/zig/libcpp_ios/mylib.h:3:
In file included from /Users/jcalabro/.bin/zig/lib/libcxx/include/iostream:43:
In file included from /Users/jcalabro/.bin/zig/lib/libcxx/include/ios:220:
In file included from /Users/jcalabro/.bin/zig/lib/libcxx/include/__ios/fpos.h:14:
In file included from /Users/jcalabro/.bin/zig/lib/libcxx/include/iosfwd:100:
In file included from /Users/jcalabro/.bin/zig/lib/libcxx/include/__mbstate_t.h:29:
/Users/jcalabro/.bin/zig/lib/libcxx/include/wchar.h:143:77: error: use of undeclared identifier 'wcschr'
/Users/jcalabro/.bin/zig/lib/libcxx/include/wchar.h:150:87: error: use of undeclared identifier 'wcspbrk'
/Users/jcalabro/.bin/zig/lib/libcxx/include/wchar.h:157:78: error: use of undeclared identifier 'wcsrchr'
/Users/jcalabro/.bin/zig/lib/libcxx/include/wchar.h:164:86: error: use of undeclared identifier 'wcsstr'
/Users/jcalabro/.bin/zig/lib/libcxx/include/wchar.h:171:90: error: use of undeclared identifier 'wmemchr'
```

Apologies if I'm missing something obvious, I've never done any work on iOS before. We've been able to build this code with an existing clang toolchain, but we're examining using Zig because it's `build.zig` system is awesome, esp. since this library ships for many platforms.

Thank you!

### Expected Behavior

I expect to be able to x-compile the above C++ minimal repro via `zig build -Dtarget=aarch64-ios`.

**Comment by kassane** [comment]
Have you tried configuring `build.zig` based on this example?
https://github.com/kubkon/zig-ios-example

cc: @kubkon

**Comment by jcalabro** [comment]
That project has been incredibly helpful, thank you so much! That got me going and I was able to compile the example, the minimal repro above, and the big C++ project I was originally trying.

Thank you so much for the pointer, and thank you @kubkon for all your work!
