### ISSUE TITLE
every `EmitOption` field in `std.Build.Step.Compile` (for example: `emit_docs`) lacks `FileSource` integration

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#16351]
https://github.com/ziglang/zig/blob/b9fc0d2908371dc4f7c95c03972d42e290d6e1e0/lib/std/Build/Step/Compile.zig#L49-L58

Instead of passing strings directly to the Zig CLI, the build system API should have a function for adding emission of each of these artifacts which returns a `FileSource` which can then be used as inputs in other parts of the build system API.

As an example, `getOutputSource` already does this for the CLI equivalent of `-femit-bin`.

As a bonus, the build system should pass `-fno-emit-bin` unless `getOutputSource()` is called on the Compile Step. This will happen automatically in the case of adding an install step for the build artifact, which passes the result of `getOutputSource()` to an Install Step.

**Comment by MasterQ32** [comment]
I'll try resolving this with a PR together with #16353

**Comment by andrewrk** [comment]
Duplicate of  #14971
