### ISSUE TITLE
Zig generates different (worse) instructions when a function from a different file is called

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#16368]
### Zig Version

tested with godbolt trunk and 0.10.0

### Steps to Reproduce and Observed Behavior

I made two function calls.
One to `std.io.fixedBufferStream(@as([]u8, &.{}));` from the standard library.
And the other one to an exact copy of said function, but in the main file.

Here is the godbolt link: https://godbolt.org/z/vvnc7qz3W
![Screenshot at 2023-07-09 18-51-37](https://github.com/ziglang/zig/assets/43880493/3235d93d-eb07-454a-93f7-5e3a14231f7b)

As you can see the call to the `std.io` version produces an unnecessary copy on the stack which the version from the same file avoids.

### Expected Behavior

The return value should be constructed in place on the stack in both cases without requiring extra copies.
This is slowing down debug code and increases compile time.

**Comment by andrewrk** [comment]
This is an interesting find, but your premise (that it has to do with which .zig source file the function resides in) is almost certainly wrong. More investigation needed to determine what is happening here.

Also note that when optimizations are on, it deletes 100% of your code in this example.

**Comment by andrewrk** [comment]
It's because you used `const` for one and `var` for the other. This is working as designed.

**Comment by IntegratedQuantum** [comment]
Oh I have been totally blind.
But I still don't understand, why it needs an extra copy. (it only makes sense to copy on re-assignment in my opinion, but not on first assignments)

**Comment by andrewrk** [comment]
To understand that, you should look at the ZIR for a function call that assigns the result into a variable. Then look at the AIR for it. Then look at the LLVM IR for it. Then you can try to think of a better lowering at one of those phases, then you can look at the corresponding logic and see if you can improve it.

**Comment by IntegratedQuantum** [comment]
The optimization for constants seems to be done in `AstGen` already.
However I could not find a good way to apply this optimization to variables as well.
