### ISSUE TITLE
integer support for std.math.pow 

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1637]
Right now std.math.pow only supports floating points. It should support integers too.

https://stackoverflow.com/a/101613/432

**Comment by emekoi** [comment]
is it okay to overflow, or do we need to check for that somehow?

**Comment by andrewrk** [comment]
The current pattern in `std.math` is to check for overflow. Idea being that callers that want to assert no overflow can happen would use `catch unreachable`. I don't think I've made a proposal for this yet, but one idea I had is that Zig could generate special versions of functions when `catch unreachable` is used - every instance of `return (error)` would be replaced with `unreachable`.  This special version of the function would be just as optimized as a function that didn't have the possibility of error - in fact - potentially even more optimized since the `unreachable` communicates information to the optimizer.

**Comment by emekoi** [comment]
when a possible overflow is detected what would be the proper response?

**Comment by andrewrk** [comment]
Return `error.Overflow`. For example:

https://github.com/ziglang/zig/blob/4640853d1b49ec17e1e997901c58c2294aca30d6/std/math/index.zig#L245-L267
