### ISSUE TITLE
builtin functions for composing / decomposing float values

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#164]
`@compose_float(inline T: type, is_signed: bool, exponent: @int_type(false, @sizeof(T)*8), mantissa: @int_type(false, @sizeof(T)*8)) -> T`

T must be f32, f64, or potentially another floating point type that we'll introduce to the language (see http://llvm.org/docs/LangRef.html#floating-point-types for inspiration). Any floating point type that Zig supports will work on any platform, with help from compiler-rt (which is compiled automatically for the target). We may have special floating point types that are guaranteed to be IEEE754 or another specific format, which may be slower on systems without native support. But we will also have generic floating point types, such as `f32` and `f64` which are only specified to be floating point types with a specific byte count. Using these builtin floating point functions one can write portable Zig code that does not depend on the memory layout of floating point types. If one needs a stronger guarantee about floating point precision or memory layout, one could use the specific floating point type that guarantees IEEE754 (or another format), with the understanding that this may come at a performance cost on some systems. This performance cost may make sense to pay, in the case of serialization and deserialization, since you would have to pay the cost anyway to have the correct input and output.

Note that C99 specifies `float` as IEEE 754 single precision, `double` as binary64, as specified by the IEEE 754 standard, `long double` is defined as IEEE 754 extended precision (e.g., Intel 80-bit double extended precision on x86 or x86-64 platforms), or some form of quad precision where available; otherwise, it is double precision.

So for C interop we would use the IEEE754-guaranteed type for float, IEEE754 double guaranteed type for double, and c_long_double for long double, since it is system dependent (like many int types in C).

One question is whether mantissa and exponent would have a safety check for if the value is too big to fit in the available bits, or if it would automatically mask and only use the lower bits.

`@float_mantissa_bit_count(inline T: type) -> usize`
returns number of bits in the mantissa of a floating point type

`@float_exponent_bit_count(inline T: type) -> usize`
returns number of bits in the exponent of a floating point type

`@decompose_float(value, is_signed: &bool, exponent: &@int_type(false, @sizeof(@typeof(value)) * 8), mantissa: &@int_type(false, @sizeof(@typeof(value)) * 8)`

value must have a floating point type. This function outputs is_signed, exponent, and mantissa.

Open questions:
- Should we have builtin functions to deal with NaN, positive infinity, and negative infinity? Do all floating point formats support such concepts?

**Comment by shawnl** [comment]
> We may have special floating point types that are guaranteed to be IEEE754 or another specific format, which may be slower on systems without native support.

I think we should only support IEEE754. The other interesting formats are f32decimal f64decimal and f128decimal. The [Mill CPU](https://millcomputing.com/), as its founder is a co-author of IEEE754, will have decimal floating point hardware. We also have f16 of course too, which has many important applications, but moreso inside GPUs.

> Should we have builtin functions to deal with NaN, positive infinity, and negative infinity? Do all floating point formats support such concepts?

IEEE754 does.

I don't think we need a built-in for this. We already have `@bitCast` and it is all well-defined. This stuff should be in the standard library. I also don't think we should really support 80-bit IEEE754, and neither does Intel or AMD. Also, x86_64 supports f128 now, and that is better and more cross-platform.
