### ISSUE TITLE
reader.readIntoBoundedBytes bug

### ISSUE THREAD

**Issue by lockbox** [ziglang/zig#16416]
### Zig Version

0.11.0-dev.4002+7dd1cf26f

### Steps to Reproduce and Observed Behavior

In this snippet:

https://github.com/ziglang/zig/blob/7dd1cf26f9b0cb104ada166a10ff356ca272577a/lib/std/io/reader.zig#L262-L272

line 268 `bytes_read` is type `Error!usize`. Line 270 adds that `usize` to an `IntFittingRange`:

https://github.com/ziglang/zig/blob/7dd1cf26f9b0cb104ada166a10ff356ca272577a/lib/std/bounded_array.zig#L35-L45

So if you create any bounded array say with size `10000`, `bounded.len` will have a type of `u17`, which the compiler correctly blocks and complains:

```
error: expected type 'u17', found 'usize'
note: unsigned 17-bit int cannot represent all possible unsigned 64-bit values
```

### Expected Behavior

`std.BoundedArrayAligned.Len` should be a `usize`, as opposed to `IntFittingRange`, just like all the other sizes in `std` (in this case the `read` call that returns a usize is the problem).

While the bounded array impl is cool because it only gets the smallest size necessary, the smol savings gains have *fun* side effects like this.

While the size storing of a min int is sus, its more sus that the reader is manipulating the slice and len directly in `readIntoBUfferedBytes` i can fix whichever one is decided is the buggy behavior if you want. but either way one of those should get changed

**Comment by squeek502** [comment]
Am I being silly or would this be a possible solution:

```zig
bounded.len += @intCast(bytes_read); 
```
or maybe
```zig
bounded.len += @as(@TypeOf(bounded.len), @intCast(bytes_read));
```
if the first one errors

**Comment by lockbox** [comment]
Yeah, it looks a little jank but is technically correct since the slice getting passed to `read` is guaranteed to limit the input. I can add a comment there and some tests so it gets picked up.
