### ISSUE TITLE
`struct { .x }` gives an error: expected type 'type', found '@TypeOf(.enum_literal)'

### ISSUE THREAD

**Issue by timfayz** [ziglang/zig#16418]
### Zig Version

0.11.0-dev.4002+7dd1cf26f

### Steps to Reproduce and Observed Behavior

While trying to explore some edge cases of using structs, I was able to construct the following type: 
```zig
const std = @import("std");

pub fn main() !void {
    const t = struct { .x };
    std.debug.print("{}\n", .{@TypeOf(t)});
    std.debug.print("{}\n", .{t});
}
```
Output:
```
type
tests.main.val
```
So it seems the `t` **is** a type. However, if I apply `@typeInfo` on it:
```zig
// main.zig
pub fn main() !void {
    const t = struct { .x };
    _ = @typeInfo(t);
}
```
Zig gives:
```
main.zig:3:31: error: expected type 'type', found '@TypeOf(.enum_literal)'
    const t = struct { .x };
```
Is that ok? 

### Expected Behavior

To be honest, I don't know what the proper behaviour is. I was expecting to get something similar to what you get from `struct { ... }`: 
```
builtin.Type{ .Struct = builtin.Type.Struct{ .layout = builtin.Type.ContainerLayout.Auto, .backing_integer = null, .fields = { ... }, .decls = { ... }, .is_tuple = false } }
```
(where `.x` goes either into `decls` or `fields` part)

**Comment by nektro** [comment]
not a bug imo. as the error states `.x` is an anonymous enum literal. if you would like to store that in a tuple you simply need to replace `struct` with `.` and it should work as expected.
`.{  }` creates a tuple value, but these can also be anonymously constructed
`struct { T... }` creates a tuple type

**Comment by timfayz** [comment]
>  as the error states .x is an anonymous enum literal.

Yes, I see but I applied `@typeInfo` to the entire construction, not just to `.x`.

>  if you would like to store that in a tuple you simply need to replace `struct` with `.`

The point of my issue is that I would like to have a language where I cannot construct a type which is a type at first but then it turns out it is not. If it isn't a valid type it should be said so because the error is so obscure that no newbie (like me) have a chance to comprehend it and it makes the feel of the language ill-designed and unrobust. But I would like Zig not to be a great language :)

**Comment by timfayz** [comment]
Also:
```
pub fn main() !void {
    const t = struct {
        x: u32,
    };
    std.debug.print("{}\n", .{@typeInfo(t)});
}
```
Throws:
```
/Users/timfayz/zig/lib/std/fmt.zig:662:22: error: values of type '[]const builtin.Type.StructField' must be comptime-known, but index value is runtime-known
                for (value, 0..) |elem, i| {
                     ^~~~~
/Users/timfayz/zig/lib/std/builtin.zig:318:15: note: struct requires comptime because of this field
        type: type,
              ^~~~
/Users/timfayz/zig/lib/std/builtin.zig:318:15: note: types are not available at runtime
        type: type,
              ^~~~
/Users/timfayz/zig/lib/std/builtin.zig:321:20: note: struct requires comptime because of this field
        alignment: comptime_int,
                   ^~~~~~~~~~~~
referenced by:
    formatType__anon_6668: /Users/timfayz/zig/lib/std/fmt.zig:596:21
    formatType__anon_3800: /Users/timfayz/zig/lib/std/fmt.zig:557:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

```
Probably this is not directly related to `@typeInfo` itself but rather to printing what it gives.
