### ISSUE TITLE
Lack of compilation options when compiling with zig cc

### ISSUE THREAD

**Issue by icls1337** [ziglang/zig#16411]
### Zig Version

0.11.0-dev.3997+546212ff7

### Steps to Reproduce and Observed Behavior

https://godbolt.org/z/59Y1768ac
Lack of compilation options when compiling with zig cc,for instance zig cc compiles the missing -ffast-math when using the -Ofast option.
clang docs:
https://clang.llvm.org/docs/CommandGuide/clang.html?highlight=ofast#cmdoption-o0

clang -Ofast:
Could not execute the program
Compiler returned: 0
Compiler stderr
clang version 17.0.0 (https://github.com/llvm/llvm-project.git a01d1831bc9068a0d9d9c5ee6ef2601c05aacc4b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/compiler-explorer/clang-trunk/bin
 "/opt/compiler-explorer/clang-trunk-20230714/bin/clang-17" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-emit-obj" "-dumpdir" "/app/output.s-" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "example.c" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=none" "-menable-no-infs" "-menable-no-nans" "-fapprox-func" "-funsafe-math-optimizations" "-fno-signed-zeros" "-mreassociate" "-freciprocal-math" "-fdenormal-fp-math=preserve-sign,preserve-sign" "-ffp-contract=fast" "-fno-rounding-math" "-ffast-math" "-ffinite-math-only" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-debug-info-kind=constructor" "-dwarf-version=4" "-debugger-tuning=gdb" "-fcoverage-compilation-dir=/app" "-resource-dir" "/opt/compiler-explorer/clang-trunk-20230714/lib/clang/17" "-internal-isystem" "/opt/compiler-explorer/clang-trunk-20230714/lib/clang/17/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0/../../../../x86_64-linux-gnu/include" "-internal-externc-isystem" "/usr/include/x86_64-linux-gnu" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-Ofast" "-fdebug-compilation-dir=/app" "-ferror-limit" "19" "-fgnuc-version=4.2.1" "-fcolor-diagnostics" "-vectorize-loops" "-vectorize-slp" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-o" "/tmp/example-e73566.o" "-x" "c" "<source>"
 "/opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0/../../../../x86_64-linux-gnu/bin/ld" "-pie" "--hash-style=gnu" "--eh-frame-hdr" "-m" "elf_x86_64" "-dynamic-linker" "/lib64/ld-linux-x86-64.so.2" "-o" "/app/output.s" "/lib/x86_64-linux-gnu/Scrt1.o" "/lib/x86_64-linux-gnu/crti.o" "/opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0/crtbeginS.o" "/opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0/crtfastmath.o" "-L./lib" "-L/opt/compiler-explorer/clang-trunk-20230714/bin/../lib/x86_64-unknown-linux-gnu" "-L/opt/compiler-explorer/clang-trunk-20230714/lib/clang/17/lib/x86_64-unknown-linux-gnu" "-L/opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0" "-L/opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0/../../../../lib64" "-L/lib/x86_64-linux-gnu" "-L/lib/../lib64" "-L/usr/lib/x86_64-linux-gnu" "-L/usr/lib/../lib64" "-L/opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0/../../../../x86_64-linux-gnu/lib" "-L/lib" "-L/usr/lib" "/tmp/example-e73566.o" "-rpath" "./lib" "-rpath" "/opt/compiler-explorer/gcc-9.2.0/lib64" "-rpath" "/opt/compiler-explorer/gcc-9.2.0/lib32" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "-lc" "-lgcc" "--as-needed" "-lgcc_s" "--no-as-needed" "/opt/compiler-explorer/gcc-9.2.0/lib/gcc/x86_64-linux-gnu/9.2.0/crtendS.o" "/lib/x86_64-linux-gnu/crtn.o"
Compiler did not produce an executable

zig cc -Ofast:
Could not execute the program
Compiler returned: 1
Compiler stderr
clang version 16.0.1 (https://github.com/ziglang/zig-bootstrap bf1b2cdb83141ad9336eec42160c9fe87f90198d)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /app
 (in-process)
 "/opt/compiler-explorer/zig-master/zig" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-emit-llvm-bc" "-flto=full" "-flto-unit" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "example.c" "-mrelocation-model" "pic" "-pic-level" "2" "-fhalf-no-semantic-interposition" "-mframe-pointer=none" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-mllvm" "-treat-scalable-fixed-error-as-warning" "-debug-info-kind=constructor" "-dwarf-version=4" "-debugger-tuning=gdb" "-fcoverage-compilation-dir=/app" "-nostdsysteminc" "-nobuiltininc" "-resource-dir" "/opt/compiler-explorer/lib/clang/16" "-isystem" "/opt/compiler-explorer/zig-master/lib/include" "-isystem" "/opt/compiler-explorer/zig-master/lib/libc/include/x86_64-linux-gnu" "-isystem" "/opt/compiler-explorer/zig-master/lib/libc/include/generic-glibc" "-isystem" "/opt/compiler-explorer/zig-master/lib/libc/include/x86-linux-any" "-isystem" "/opt/compiler-explorer/zig-master/lib/libc/include/any-linux-any" "-isystem" "/usr/local/include" "-isystem" "/usr/include/x86_64-linux-gnu" "-isystem" "/usr/include" "-D" "__GLIBC_MINOR__=19" "-D" "NDEBUG" "-O2" "-fdebug-compilation-dir=/app" "-ferror-limit" "19" "-fgnuc-version=4.2.1" "-fno-spell-checking" "-vectorize-loops" "-vectorize-slp" "-target-cpu" "skylake-avx512" "-target-feature" "-16bit-mode" "-target-feature" "-32bit-mode" "-target-feature" "-3dnow" "-target-feature" "-3dnowa" "-target-feature" "+64bit" "-target-feature" "+adx" "-target-feature" "+aes" "-target-feature" "+allow-light-256-bit" "-target-feature" "-amx-bf16" "-target-feature" "-amx-fp16" "-target-feature" "-amx-int8" "-target-feature" "-amx-tile" "-target-feature" "+avx" "-target-feature" "+avx2" "-target-feature" "-avx512bf16" "-target-feature" "-avx512bitalg" "-target-feature" "+avx512bw" "-target-feature" "+avx512cd" "-target-feature" "+avx512dq" "-target-feature" "-avx512er" "-target-feature" "+avx512f" "-target-feature" "-avx512fp16" "-target-feature" "-avx512ifma" "-target-feature" "-avx512pf" "-target-feature" "-avx512vbmi" "-target-feature" "-avx512vbmi2" "-target-feature" "+avx512vl" "-target-feature" "-avx512vnni" "-target-feature" "-avx512vp2intersect" "-target-feature" "-avx512vpopcntdq" "-target-feature" "-avxifma" "-target-feature" "-avxneconvert" "-target-feature" "-avxvnni" "-target-feature" "-avxvnniint8" "-target-feature" "+bmi" "-target-feature" "+bmi2" "-target-feature" "-branchfusion" "-target-feature" "-cldemote" "-target-feature" "+clflushopt" "-target-feature" "+clwb" "-target-feature" "-clzero" "-target-feature" "+cmov" "-target-feature" "-cmpccxadd" "-target-feature" "+crc32" "-target-feature" "+cx16" "-target-feature" "+cx8" "-target-feature" "-enqcmd" "-target-feature" "+ermsb" "-target-feature" "+f16c" "-target-feature" "-false-deps-getmant" "-target-feature" "-false-deps-lzcnt-tzcnt" "-target-feature" "-false-deps-mulc" "-target-feature" "-false-deps-mullq" "-target-feature" "-false-deps-perm" "-target-feature" "+false-deps-popcnt" "-target-feature" "-false-deps-range" "-target-feature" "-fast-11bytenop" "-target-feature" "+fast-15bytenop" "-target-feature" "-fast-7bytenop" "-target-feature" "-fast-bextr" "-target-feature" "+fast-gather" "-target-feature" "-fast-hops" "-target-feature" "-fast-lzcnt" "-target-feature" "-fast-movbe" "-target-feature" "+fast-scalar-fsqrt" "-target-feature" "-fast-scalar-shift-masks" "-target-feature" "+fast-shld-rotate" "-target-feature" "+fast-variable-crosslane-shuffle" "-target-feature" "+fast-variable-perlane-shuffle" "-target-feature" "+fast-vector-fsqrt" "-target-feature" "-fast-vector-shift-masks" "-target-feature" "+fma" "-target-feature" "-fma4" "-target-feature" "+fsgsbase" "-target-feature" "-fsrm" "-target-feature" "+fxsr" "-target-feature" "-gfni" "-target-feature" "-harden-sls-ijmp" "-target-feature" "-harden-sls-ret" "-target-feature" "-hreset" "-target-feature" "-idivl-to-divb" "-target-feature" "+idivq-to-divl" "-target-feature" "+invpcid" "-target-feature" "-kl" "-target-feature" "-lea-sp" "-target-feature" "-lea-uses-ag" "-target-feature" "-lvi-cfi" "-target-feature" "-lvi-load-hardening" "-target-feature" "-lwp" "-target-feature" "+lzcnt" "-target-feature" "+macrofusion" "-target-feature" "+mmx" "-target-feature" "+movbe" "-target-feature" "-movdir64b" "-target-feature" "-movdiri" "-target-feature" "-mwaitx" "-target-feature" "+nopl" "-target-feature" "-pad-short-functions" "-target-feature" "+pclmul" "-target-feature" "-pconfig" "-target-feature" "+pku" "-target-feature" "+popcnt" "-target-feature" "-prefer-128-bit" "-target-feature" "+prefer-256-bit" "-target-feature" "-prefer-mask-registers" "-target-feature" "-prefetchi" "-target-feature" "-prefetchwt1" "-target-feature" "+prfchw" "-target-feature" "-ptwrite" "-target-feature" "-raoint" "-target-feature" "-rdpid" "-target-feature" "-rdpru" "-target-feature" "+rdrnd" "-target-feature" "+rdseed" "-target-feature" "-retpoline" "-target-feature" "-retpoline-external-thunk" "-target-feature" "-retpoline-indirect-branches" "-target-feature" "-retpoline-indirect-calls" "-target-feature" "-rtm" "-target-feature" "+sahf" "-target-feature" "-sbb-dep-breaking" "-target-feature" "-serialize" "-target-feature" "-seses" "-target-feature" "-sgx" "-target-feature" "-sha" "-target-feature" "-shstk" "-target-feature" "+slow-3ops-lea" "-target-feature" "-slow-incdec" "-target-feature" "-slow-lea" "-target-feature" "-slow-pmaddwd" "-target-feature" "-slow-pmulld" "-target-feature" "-slow-shld" "-target-feature" "-slow-two-mem-ops" "-target-feature" "-slow-unaligned-mem-16" "-target-feature" "-slow-unaligned-mem-32" "-target-feature" "-soft-float" "-target-feature" "+sse" "-target-feature" "+sse2" "-target-feature" "+sse3" "-target-feature" "+sse4.1" "-target-feature" "+sse4.2" "-target-feature" "-sse4a" "-target-feature" "-sse-unaligned-mem" "-target-feature" "+ssse3" "-target-feature" "-tagged-globals" "-target-feature" "-tbm" "-target-feature" "-tsxldtrk" "-target-feature" "-uintr" "-target-feature" "-use-glm-div-sqrt-costs" "-target-feature" "-use-slm-arith-costs" "-target-feature" "-vaes" "-target-feature" "-vpclmulqdq" "-target-feature" "+vzeroupper" "-target-feature" "-waitpkg" "-target-feature" "-wbnoinvd" "-target-feature" "-widekl" "-target-feature" "+x87" "-target-feature" "-xop" "-target-feature" "+xsave" "-target-feature" "+xsavec" "-target-feature" "+xsaveopt" "-target-feature" "+xsaves" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-o" "/app/.cache/zig/tmp/53035c1566243c2b-example.o" "-x" "c" "<source>"
ld.lld -r --error-limit=0 -O3 -s -znow -m elf_x86_64 -static -o /app/.cache/zig/o/29a3342732fbfbb821785688e5135528/crti.o /app/.cache/zig/o/f9bfddb8c9104a3220c2dc0daaee457b/crti.o
ld.lld -r --error-limit=0 -O3 -s -znow -m elf_x86_64 -static -o /app/.cache/zig/o/6f8a8d0c8b67395330c3a9257354b74a/crtn.o /app/.cache/zig/o/6e2a79c7c35de1f0969ac3417cfbcd05/crtn.o
ld.lld -r --error-limit=0 -O3 -s -znow -m elf_x86_64 -static -o /app/.cache/zig/o/b53ec1d2076fb2911a37da7011f2648e/Scrt1.o /app/.cache/zig/o/a13669fc30d8c8c31f51cf58046b4f7f/start-2.33.o /app/.cache/zig/o/74591574b2673217b507d6b5139734a6/abi-note.o
ar rcs /app/.cache/zig/o/a1d59b056a0b4f0e6837d22a741648b4/libc_nonshared.a /app/.cache/zig/o/5ed4083af870e66a1e5bcf3a118af27d/atexit.o /app/.cache/zig/o/55f5c5689b6f798e5654976f828f8803/at_quick_exit.o /app/.cache/zig/o/44f2837b448ccae1862a48614619a143/pthread_atfork.o /app/.cache/zig/o/3ecac8d792b263a39c6988e3e210cb65/stack_chk_fail_local.o /app/.cache/zig/o/b350229202a8035ba512e8e742952337/errno.o /app/.cache/zig/o/3542150b6890d1ae7e6817c1aaebb1f5/elf-init-2.33.o /app/.cache/zig/o/e886104f209511871e0f2ab56320a368/stat.o /app/.cache/zig/o/50b00d3b36387641664a86f1a74e6ed1/fstat.o /app/.cache/zig/o/d05416aa0fc120eaa43ef15e20239a18/lstat.o /app/.cache/zig/o/bb2e946fbf9cece26006d726b004e7f8/stat64.o /app/.cache/zig/o/18303e2d74d4c4b2b621210b942f8b2e/fstat64.o /app/.cache/zig/o/e0b9da141e4725d5bc40d7329e4bce48/lstat64.o /app/.cache/zig/o/5cb4dca06ff846ecb2848bde00f174d6/fstatat.o /app/.cache/zig/o/4ea7177d6bbb7ef3e7a93e37ed240c50/fstatat64.o /app/.cache/zig/o/9a24134d55d19f19a7473ff809531c8f/mknodat.o /app/.cache/zig/o/0c7120d6bf505fc4f59a657796e702e5/mknod.o /app/.cache/zig/o/fb36fccae9cd095752127ad6a062e833/stat_t64_cp.o
ld.lld --error-limit=0 -O3 --gc-sections -s -znow -m elf_x86_64 -shared -o /app/.cache/zig/o/608ba47925fadf334034296e58afc348/libm.so.6 -soname libm.so.6 -version-script /app/.cache/zig/o/608ba47925fadf334034296e58afc348/all.map /app/.cache/zig/o/ac504f742db67b47f9eb5a703f592452/m.o --as-needed --allow-shlib-undefined
ld.lld --error-limit=0 -O3 --gc-sections -s -znow -m elf_x86_64 -shared -o /app/.cache/zig/o/608ba47925fadf334034296e58afc348/libpthread.so.0 -soname libpthread.so.0 -version-script /app/.cache/zig/o/608ba47925fadf334034296e58afc348/all.map /app/.cache/zig/o/7df085588c8781eb949ab633ada5f49f/pthread.o --as-needed --allow-shlib-undefined
ld.lld --error-limit=0 -O3 --gc-sections -s -znow -m elf_x86_64 -shared -o /app/.cache/zig/o/608ba47925fadf334034296e58afc348/libc.so.6 -soname libc.so.6 -version-script /app/.cache/zig/o/608ba47925fadf334034296e58afc348/all.map /app/.cache/zig/o/73b94c12698ec2fcb4e7d2c6074f4813/c.o --as-needed --allow-shlib-undefined
ld.lld --error-limit=0 -O3 --gc-sections -s -znow -m elf_x86_64 -shared -o /app/.cache/zig/o/608ba47925fadf334034296e58afc348/libdl.so.2 -soname libdl.so.2 -version-script /app/.cache/zig/o/608ba47925fadf334034296e58afc348/all.map /app/.cache/zig/o/dc01658b5ec4792de87c1135a047c871/dl.o --as-needed --allow-shlib-undefined
ld.lld --error-limit=0 -O3 --gc-sections -s -znow -m elf_x86_64 -shared -o /app/.cache/zig/o/608ba47925fadf334034296e58afc348/librt.so.1 -soname librt.so.1 -version-script /app/.cache/zig/o/608ba47925fadf334034296e58afc348/all.map /app/.cache/zig/o/6a5cd4581e22e7b829f608ddfecd4728/rt.o --as-needed --allow-shlib-undefined
ld.lld --error-limit=0 -O3 --gc-sections -s -znow -m elf_x86_64 -shared -o /app/.cache/zig/o/608ba47925fadf334034296e58afc348/libld.so.2 -soname ld-linux-x86-64.so.2 -version-script /app/.cache/zig/o/608ba47925fadf334034296e58afc348/all.map /app/.cache/zig/o/90c58e53da16b29cfbfce3facd58bd89/ld.o --as-needed --allow-shlib-undefined
ld.lld --error-limit=0 -O3 --gc-sections -s -znow -m elf_x86_64 -shared -o /app/.cache/zig/o/608ba47925fadf334034296e58afc348/libutil.so.1 -soname libutil.so.1 -version-script /app/.cache/zig/o/608ba47925fadf334034296e58afc348/all.map /app/.cache/zig/o/21ff3c913712615078831ea14be6d7c8/util.o --as-needed --allow-shlib-undefined
ld.lld --error-limit=0 -O3 --gc-sections -s -znow -m elf_x86_64 -shared -o /app/.cache/zig/o/608ba47925fadf334034296e58afc348/libresolv.so.2 -soname libresolv.so.2 -version-script /app/.cache/zig/o/608ba47925fadf334034296e58afc348/all.map /app/.cache/zig/o/4bc6aeabd762495c1c79eca224b6ef6e/resolv.o --as-needed --allow-shlib-undefined
ar rcs /app/.cache/zig/o/dc529c702ed5f0f52140c311bba17e6c/libcompiler_rt.a /app/.cache/zig/o/dc529c702ed5f0f52140c311bba17e6c/libcompiler_rt.a.o
<source>:1:1: error: unable to build C object: FileNotFound

### Expected Behavior

Same as clang -Ofast.

**Comment by andrewrk** [comment]
This bug report is not sufficient to remain open.

https://github.com/ziglang/zig/blob/7dd1cf26f9b0cb104ada166a10ff356ca272577a/src/main.zig#L1754-L1775

https://github.com/ziglang/zig/blob/7dd1cf26f9b0cb104ada166a10ff356ca272577a/tools/update_clang_options.zig#L219-L222
