### ISSUE TITLE
Inline assembly segfaults compiler

### ISSUE THREAD

**Issue by Validark** [ziglang/zig#16435]
### Zig Version

0.11.0-dev.4000+3022c525e and later

### Steps to Reproduce and Observed Behavior

It looks like inline assembly can segfault the latest versions of the compiler. It works on `0.11.0-dev.3946+b9fc0d290` but stopped working when I upgraded to `0.11.0-dev.4000+3022c525e`. [Godbolt link](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AAvPMFJL6yAngGVG6AMKpaAVxYM9DgDJ4GmADl3ACNMYhBpAAdUBUJbBmc3Dz1o2JsBX38gllDw6UtMa3ihAiZiAkT3Ty4LTCt0hhKygkzAkLCIi1LyyuSahW6WvzacjskASgtUV2Jkdg40BgGAagH0ZYBSAGYAEWWAATwWaPKIDYAmc7WL8/HtgCENjQBBRZXg1zobBk3dg6OTgQzpcPl8/Dc7ltHi8ns8qD8FK4qDRVAANADyACUIMFCCwmAoANYgZaGACeBDJkUw4wOABUqZh0VQcXiCYTaRsAOzQ57LfnLNDHGxsVYEdAAOiwH2AEoJSlOawl%2BIICAleAUylQAHcwsy6drUBB9rjhHhjEyWfsGdTmayCPiieNnZDebCBYKBCsEASAPrMGwAN0wvtExGIZPoCgUvpYrloNkitDJvz2JsIQnNluNNuzpsdHM5W0c2z2ADZJKSGOsFNrCMgEMscZ8E34JchIq45bMEJyee6PQKAPRD5Z0hBhTCrBDTWjrULLBioVauBvLVV%2BYDLOuq0nLSLEVBzaMkFeRQGb0mB1TLD4EReoe/IWhx2gSgeD5YS1QADjLvorVNtmwMVJTpMpgEwAhvz/CUqEwJgCBmTAhCggAJAlmzBBh207OCEKQ4hMAUUgv0iZ9X1pQx0A/T8BSVcDiEg6DfzLfDEOQ1CCAwhQsNbHCOy7eCOKIkivyYa9blIWiPTlMoG0A0tgNAiVGOYuSewrdjCJQ9DMNBfjcKEgjkLEuViMmGSBTqJQgK2ECqDEJRpJeD1uR2B5YVovAqCbQ4ElQYUjkwCBaVPMAwB9GMAzwYNQzKCMoxjV9E2TPteTo5ZAzKZYb1LW82SJTzXLovxaGGZZ%2BGIJsNAlCVjVNTMLTtJUVTVbxUGAc4AElBBzRk7XzdkXWdTYuUcPBuRLErMv5PKAFZsHyvLi22RxPSC0UIC4X4S2LZY8FdKz%2BSIwifgWkChqKqFaPcryZuWEdlnQZcmEFBLI2IhRlhSvAkxTYIUzEWhli4MAOBI2inqYdAmEiAhMHWKhDxYZZTGAIdyuCIc1iHZAI3h1Ah2AKKEF9aJk2yt90dot57xWtNMNcLhzh/Uj0wqAkgQ2eb7nOHmdlcCtuXuA4mYrUiro5UiNDGnZnWKvkBTp5YU3y/YmZZtmDgUJNEONJntY0VRkRdTZFtBxXaNOmYfg13jrQGlkpcmA4CGIVwGFEBGIFretGz474jO7Bt0uOr9WIAyslPs0kFFRs4HsynmS3m9bA3Il94wAR3QbPlgAEmNjQNFIi55p5%2B5VAFsvzgr3myRrzY68r6YCAF8OPRJVvXHb%2Ba9huUtq8uJsAFplP2AA1QoiGICBzlIoWJkspO6O73nq/75vzmH84/MwqeZ5IefF4rV2OccLmIFUF0XKV2aBUrxut5uXf94d6frGPhfliX8/TUvgMCAZJb7hxXs8cOGkFLR12MpAkCdO6PzTinfcr4Qblx7n3HYEouDZ1rvXKuAscHoHwU/IhXAaKr0/Ove4bcBbb1LNqG4Y8J6f1nifX%2BZ9wEP35DQzeA9LhMJHgbD%2BR854/z/uzABV8b7OjvjwpB9xn4CPOEIveIjjRsO/qfCYUjCCAKBCAuRYC77hxslOGOIFPZESYA2JgwR6DyMflyDyvMNACwVjdGELj7rPEwKoQElUfgFmwMGRoUF7iEF4qaAYxBNwkj/pw6O/YHo22ID8GJ7tLwXDLCuZEeA0RYntLEzcR1vE7A4JMWgnB5q8E8BwLQpBUCcAAFpmFWNMWYFjzhbB4KQAgmhKmTGJPNeaEpJB/kmRoLgXINB/jLAATn0JwSQdTBlNM4LwBQIBS4DIaZU0gcBYAwEQCgQKkQ6BhHIJQIUFz6DhGMO7T2hJSBYEDHgOYk88CYG1Oiak9S%2Bk0ATGEbZOJ1m4mYBGTgfSIVlDJOiYI2gZ7Qt4EKNggh0QMGTOs6UrhgCX1oLQbZ3BeBYHxEYcQ%2BzXl4CIkUYMxLGn%2BMKL3eYfS/AI2qVSrGxA4XOCwOsrJLAUWTCoAYYACgvk/L%2BYwFFMhBAiDEOwKQcr5BKDUOs3QC8DBGBAOjfQeBgjbMgJMVA8N4jEtHuiZYmI6gISUAAMS5rwVAwZwx4CwEa0KtR6jxHsNWXo1RSA%2BGGNkXIKQYhxAEAG8NaR4itFDR0fotqigCCaD0FwVQ9AFBTY0QY8b2jhH6IMaNRbmj5tGIWyYChOlzAkFUmpayqXNI4GjdpTyGCEibLgQgp4Li9PGLwPZWg5EThhh0L1xItg/glD%2BSQkgFlcC2PNLg80NALJ/OcGonLVmkCFfOiUXJ12SHmlyLkZYthchPce0g9TGnNq2Ts/pgzJhHNObcy5ZAKAQHffc3V7aXlvI%2BZgSVvz/myqBQjYgoLgjgr8HC2VsKIwIqRdYWVaLGAEExdiqluL8XA2JX0slhhgCUsafgWlQZiLrKZcgFlsr2V1HWdy3lGB5iNMFcKvgYqJXfNAzKklKqFXiGVfwQQigVDqCpboLdxHdVmH1Ya%2BAJqzVek4Ja61tqCSYEdSsUe3RmKknkggCso9yoMFcDeUeLBBKljhkmEMLA%2BkurCHEj1SnvUz19RABwJag3VnLWGmoqRI0BSSIG4LDQAuJo8zmtNFQM19Biw0OLUXC1dGaL5gYZaQ0FrrVMGYtauD1o4LUm96zm2tq3P%2Brt%2BBZ7N37YO59kxR1YHCF67dvAhWrolOcaZ81JCXC2GWc4A3RllabZsiwj6h1DNIMSOdEotgXp6RoCZp7V3zSWZyrYja72TZm3Izl5xdvOv2010grrYh2EkEAA)

```zig
const std = @import("std");
const builtin = @import("builtin");

fn suffixXOR(bitmask: anytype) @TypeOf(bitmask) {
    comptime std.debug.assert(std.math.isPowerOfTwo(@bitSizeOf(@TypeOf(bitmask))));

    const has_native_carryless_multiply = @bitSizeOf(@TypeOf(bitmask)) <= 64 and switch (builtin.cpu.arch) {
        // There should be no such thing with a processor supporting avx but not clmul.
        .x86_64 => std.Target.x86.featureSetHas(builtin.cpu.features, .pclmul) and
            std.Target.x86.featureSetHas(builtin.cpu.features, .avx2),
        .aarch64 => std.Target.aarch64.featureSetHas(builtin.cpu.features, .aes),
        else => false,
    };

    if (@inComptime() or !has_native_carryless_multiply) {
        var x = bitmask;
        inline for (0..(@bitSizeOf(std.math.Log2Int(@TypeOf(bitmask))))) |i|
            x ^= x << comptime (1 << i);
        return x ^ bitmask;
    }

    // do a carryless multiply by all 1's,
    // adapted from zig/lib/std/crypto/ghash_polyval.zig
    const x = @as(u128, @bitCast([2]u64{ @as(u64, bitmask), 0 }));
    const y = @as(u128, @splat(@as(u8, 0xff))) ^ 1;

    return @as(@TypeOf(bitmask), @truncate(switch (builtin.cpu.arch) {
        .x86_64 => asm (
            \\ vpclmulqdq $0x00, %[x], %[y], %[out]
            : [out] "=x" (-> @Vector(2, u64)),
            : [x] "x" (@as(@Vector(2, u64), @bitCast(x))),
              [y] "x" (@as(@Vector(2, u64), @bitCast(y))),
        ),

        .aarch64 => asm (
            \\ pmull %[out].1q, %[x].1d, %[y].1d
            : [out] "=w" (-> @Vector(2, u64)),
            : [x] "w" (@as(@Vector(2, u64), @bitCast(x))),
              [y] "w" (@as(@Vector(2, u64), @bitCast(y))),
        ),

        else => unreachable,
    }[0]));
}

export fn maskEvenSetBits(bitstring: u64) u64 {
    return bitstring & suffixXOR(bitstring);
}
```

### Expected Behavior

no segfault

**Comment by oliver-giersch** [comment]
I had observed this as well, but at least on Linux in the current build (actually since about a few days ago) this seems to be no longer the case.

**Comment by Validark** [comment]
I noticed some things started working again as well, however I tried to compile the code posted above and it still didn't work last time I checked. The godbolt link still doesn't work, though I don't know how often godbolt updates their Zig compiler.

**Comment by Validark** [comment]
Looks like this code now compiles properly (after updating to the new `@splat`/`@bitCast` semantics)! Thanks Zig team!
