### ISSUE TITLE
Why isn't using `*void` in a struct field an error?

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#16444]
### Zig Version

0.11.0-dev.4006+bf827d0b5

### Steps to Reproduce and Observed Behavior

Let's say you're writing some C/C++ and without noticing, you have this in your Zig:
```zig
pub const Struct = struct {
   // woops! this should be *anyopaque
   field: *void,
   trash: u32 = 0,
};

pub export fn Struct__exported(f: *Struct) *anyopaque {
    return f.field;
}

test {
   _ = Struct__exported(undefined);
}
```

`*void` was replaced by `*anyopaque` many months ago, but this code compiled successfully.

```bash
zig test repro.zig
All 1 tests passed.
```

Is `*void` a valid alternative to `*anyopaque`? If yes, why are there two (which goes against the philosophy of only one way to do things)? If no, why does this code compile successfully? 

### Expected Behavior

The code should not compile successfully

**Comment by nektro** [comment]
discussion in https://github.com/ziglang/zig/issues/6706

**Comment by nektro** [comment]
prior to that pointer-to-zero-sized were still valid but also zero-sized

**Comment by Jarred-Sumner** [comment]
I can see an argument to be made for allowing `*void` as an "indirect" type, like `pub fn MyType() { if (someCondition()) return void; return RealType; }` and then having functions with `fn function(arg: *MyType)` where `*MyType` conditionally evaluates to `*void` 

But are there any cases where writing `*void` as a type in a field isn't a mistake? I can't think of any reason (note that this implies a distinction between type literal names and type representations)

**Comment by Vexu** [comment]
More discussion in #12075.

**Comment by silversquirl** [comment]
`*anyopaque` did not replace `*void`. You're thinking of `*c_void`
