### ISSUE TITLE
Debug and ReleaseSafe different output

### ISSUE THREAD

**Issue by bmacho** [ziglang/zig#16467]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

The following code 

```
const std = @import("std");
const print = std.debug.print;

fn foo() fn() *u32 {
	
	const T = struct {

        fn bar() *u32 {
            var x: u32 = 123;
            return &x;
        }

	};
	
	return T.bar;
}

pub fn main() void {

    print("Result: {}", .{foo()().*});

}
```

gives different outputs with different build flags. It prints Result: 123 for 
```
zig build-exe example.zig & example.exe
```
and Result: 00 for 
```
zig build-exe example.zig -O ReleaseSafe & example.exe
```

It works for me locally also on godbolt: 
* debug [https://zig.godbolt.org/z/hbz39cP6M](https://zig.godbolt.org/z/hbz39cP6M)
* -O ReleaseSafe [https://zig.godbolt.org/z/6beca1vh3](https://zig.godbolt.org/z/6beca1vh3)

### Expected Behavior

I expected to have the same output, or the program to panic at runtime, or to not to compile at all.

**Comment by bmacho** [comment]
I have no idea about the expected behaviour, but this smells bad. 

The code is from the ziggit.dev thread [https://ziggit.dev/t/how-to-declare-local-functions-in-functions/1234/](https://ziggit.dev/t/how-to-declare-local-functions-in-functions/1234/)

**Comment by ifreund** [comment]
Dereferencing a pointer to the stack variable `x` after `bar()` has returned is illegal behavior.

See #2646 and #2301
