### ISSUE TITLE
add a progress bar when fetching packages

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#16463]
Zig is silent while it downloads third party packages from the Internet, which could take an arbitrarily long time.

Instead, it should report the progress, network speed, and which packages it is currently on, as expected by our esteemed users.

https://github.com/ziglang/zig/blob/8a18abfd60392a3adcfc4e6cfa712f63ecf2bf67/src/main.zig#L4449-L4462

**Comment by mlugg** [comment]
@VeroAsghar

I'd quite like to get a basic impl of this in for 0.11 - it'll save a lot of confusion over the next few months - so would it be possible for you to try and get it done in the next week or do? I'm happy to take it on if not, I just don't like nabbing contributor-friendly issues from people.

If you want to get started with this, you can take a look at the `std.Progress` API. It's not the prettiest, and maybe won't satisfy all the goals here, but is fairly easy to use and definitely works for a basic impl. You're welcome to ping me here or on Discord (@mlugg) if you've got any questions :)

**Comment by mlugg** [comment]
@VeroAsghar that's totally fine, I'm not trying to rush you, just wanna get it in before 0.11 :) good luck!

**Comment by truemedian** [comment]
A warning about this implementation: if you want to find the length of a http response you'll need to pull it from `request.response.content_length`, but this field will be null for chunked messages, so you'll also need a way to handle not knowing how long the response may be.

**Comment by VeroAsghar** [comment]
So far I'm able to increment the progress bar by the amount of packages in the .zon file. 
```
downloading packages... [1/5] libz [1/100]
```
The problem I currently have is getting the content-length from the request, as `fetchAndAddDependencies` (where the dependency names are held) calls `fetchAndUnpack` (where the request is actually made). The request data does not bubble back up to `fetchAndAddDependencies` from `fetchAndUnpack`. 
I'm currently trying to find a method around this.

**Comment by andrewrk** [comment]
> so you'll also need a way to handle not knowing how long the response may be.

Hmmmmmmmm I think we may have stumbled our way into a proposal: #16528
