### ISSUE TITLE
Verification tests for hash function implementations

### ISSUE THREAD

**Issue by dweiller** [ziglang/zig#16465]
This is extracted from some discussion of testing in #15947.

It may be a good idea to have comprehensive correctness tests for hash functions to help catch bugs in future refactors or performance work. This could be done by porting SMHashers verification test as suggested in the discussion [here](https://github.com/ziglang/zig/pull/15947#discussion_r1259246924_) or by porting tests from reference implementations.

**Comment by tiehuis** [comment]
See https://github.com/tiehuis/smhasher/blob/513a0a6d24f721eab793e574218418cd69a89d9c/KeysetTest.cpp#L16 for example implementation.

Example verification codes from smhasher are specified here: https://github.com/tiehuis/smhasher/blob/513a0a6d24f721eab793e574218418cd69a89d9c/main.cpp#L91

**Comment by tiehuis** [comment]
Note this is already implemented for mumur+cityhash: https://github.com/ziglang/zig/blob/e2ff486de5f3aceb21730e1feabbaf9b03432660/lib/std/hash/cityhash.zig#L345

You could pull this out into `std.hash` and make it available for all hash functions to use (or have a private internal import).

**Comment by tiehuis** [comment]
Will have a PR for this tomorrow.
