### ISSUE TITLE
Unable to create low-memory WASM binary

### ISSUE THREAD

**Issue by mattdesl** [ziglang/zig#16471]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

I'm trying to create a WASM binary with a small initial memory, that can (optionally) grow as needed. It's modifying a Float32Array of (width * height) so it may only need 1 or 2 pages of memory rather than the default 16. Here's my command:

```sh
zig build-lib test.zig -target wasm32-freestanding -dynamic -rdynamic -OReleaseSmall --import-memory
```

Here's my JS:

```js
  const arraySize = (width * height * Float32Array.BYTES_PER_ELEMENT) >>> 0;
  const nPages = ((arraySize + 0xffff) & ~0xffff) >>> 16;
  const memory = new WebAssembly.Memory({ initial: nPages });
  ... compile/instantiate WASM with memory ...
```

Here's the error when running with Node.js:

```
LinkError: WebAssembly.instantiate(): memory import 0 is smaller than initial 16, got 1
```

If I use 16 or higher `nPages`, it will instantiate properly. If I specify `--initial-memory` it will only allow 16 or more pages worth of bytes.

### Expected Behavior

Expect to be able to create WASM files that can import arbitrary number of pages worth of memory, and smaller than 16.

**Comment by Luukdegram** [comment]
The current default stack size is 1MB, hence the requirement of 16 pages. You can override the stack size by providing the flag `--stack [size]`.
