### ISSUE TITLE
self hosted wasm backend: incorrect casting of signed integers

### ISSUE THREAD

**Issue by antlilja** [ziglang/zig#16475]
### Zig Version

0.11.0-dev.4059+17255bed4

### Steps to Reproduce and Observed Behavior

`zig test test.zig -target wasm32-wasi -fno-LLVM --test-cmd wasmtime --test-cmd-bin`

```zig
// test.zig
const std = @import("std");

test "wasm" {
    var x: i8 = -5;
    try std.testing.expectEqual(@as(i32, -5), x);
}
```

Output
```
1/1 test.wasm... expected -5, found 251
FAIL (TestExpectedEqual)
```

### Expected Behavior

Test passes

**Comment by Luukdegram** [comment]
Sorry for this, I opened https://github.com/ziglang/zig/pull/16478, which should in turn unblock you for #16434.

**Comment by antlilja** [comment]
> Sorry for this, I opened #16478, which should in turn unblock you for #16434.

Thanks!
