### ISSUE TITLE
Autodoc: improve rendering of doctests

### ISSUE THREAD

**Issue by kristoff-it** [ziglang/zig#16550]
Given the current code:

```zig
pub fn Foo(comptime T: type) type {
    return struct {
        whatever: T,
        pub const MyDecl = struct {};

        test MyDecl {
            // Just testing my decl :^)
            _ = MyDecl;
        }
    };
}
```

The doctest corresponding to `MyDecl` renders with the wrong indentation because in the source code the test is defined in a nested scope which comes with some extra indentation.

Additionally, the comment doesn't render, presumably because the frontend tokenizer ignores them, since it's implemented according the stdlib zig tokenizer which does the same.

**Comment by der-teufel-programming** [comment]
I'll be working on this issue

**Comment by xdBronch** [comment]
this should be closed
