### ISSUE TITLE
Compiler crash in codegen for Zig without LLVM enabled

### ISSUE THREAD

**Issue by ianprime0509** [ziglang/zig#16586]
### Zig Version

0.11.0-dev.4295+282cb5ee5

### Steps to Reproduce and Observed Behavior

This issue only occurs with a build of Zig without LLVM enabled (don't pass `-Denable-llvm` to the build command).

Using the following `test.zig`:

```zig
const std = @import("std");

pub fn main() void {
    std.debug.print("Hello, world!\n", .{});
}
```

Run `zig build-exe test.zig`. The compilation crashes with an integer overflow in `codegen.zig`:

```
thread 150609 panic: integer overflow
/home/ian/src/zig/src/codegen.zig:540:75: 0xa1c983 in generateSymbol (zig)
                        const padding = math.cast(usize, padded_field_end - unpadded_field_end) orelse return error.Overflow;
                                                                          ^
/home/ian/src/zig/src/link/Elf.zig:2673:35: 0xa49f2b in updateDecl (zig)
        try codegen.generateSymbol(&self.base, decl.srcLoc(mod), .{
                                  ^
/home/ian/src/zig/src/link.zig:556:77: 0x862b97 in updateDecl (zig)
            .elf   => return @fieldParentPtr(Elf,   "base", base).updateDecl(module, decl_index),
                                                                            ^
/home/ian/src/zig/src/Module.zig:6281:29: 0x862834 in linkerUpdateDecl (zig)
    comp.bin_file.updateDecl(mod, decl_index) catch |err| switch (err) {
                            ^
/home/ian/src/zig/src/Compilation.zig:3191:52: 0x9d2aad in processOneJob (zig)
                        try module.linkerUpdateDecl(decl_index);
                                                   ^
/home/ian/src/zig/src/Compilation.zig:3144:30: 0x8a041e in performAllTheWork (zig)
            try processOneJob(comp, work_item, main_progress_node);
                             ^
/home/ian/src/zig/src/Compilation.zig:2067:31: 0x89c114 in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/ian/src/zig/src/main.zig:3864:24: 0x8c82af in updateModule (zig)
        try comp.update(main_progress_node);
                       ^
/home/ian/src/zig/src/main.zig:3285:17: 0x8f6ef5 in buildOutputType (zig)
    updateModule(comp) catch |err| switch (err) {
                ^
/home/ian/src/zig/src/main.zig:269:31: 0x7bcb6f in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
/home/ian/src/zig/src/main.zig:213:20: 0x7b904a in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/ian/src/zig/lib/std/start.zig:615:37: 0x7b874e in posixCallMainAndExit (zig)
            const result = root.main() catch |err| {
                                    ^
/home/ian/src/zig/lib/std/start.zig:367:5: 0x7b8231 in _start (zig)
    @call(.never_inline, posixCallMainAndExit, .{});
    ^
???:?:?: 0x2 in ??? (???)
Unwind information for `???:0x2` was not available, trace may be incomplete

Aborted (core dumped)
```

### Expected Behavior

The compilation should succeed. This works fine if the options `-fno-LLVM -fno-LLD` are passed to `zig build-exe` (there are  a lot of memory leak logs afterwards, but that's unrelated to this issue, and they can be avoided by using `-Dforce-link-libc` when building the compiler so `GeneralPurposeAllocator` doesn't get used).

As far as I can tell, this is a consequence of #16430 making `use_llvm` no longer false automatically when LLVM is not available: https://github.com/ziglang/zig/blob/282cb5ee5d75b4de2f215479b0c5531750908608/src/Compilation.zig#L756-L781 `getZigBackend` still results in one of the non-LLVM backends being chosen, because the `have_llvm` build option is false, but `backendSupportsFeature` is still only checking for `use_llvm`: https://github.com/ziglang/zig/blob/282cb5ee5d75b4de2f215479b0c5531750908608/src/Module.zig#L6421-L6435 This results in struct field reordering being applied in Sema even though the backend can't actually handle it.

I'm not entirely sure which part of all this needs to be changed, unfortunately. Maybe `use_lib_llvm` needs to be checked in more places, and this is just a consequence of the transition away from building with LLVM?

**Comment by wooster0** [comment]
Yeah, I've been seeing this one for a while now. I still often use `-fno-LLVM` when I make trivial changes in `Sema.zig` for example and don't need LLVM.
Note that this can be "fixed" with:
```diff
-                        const padding = math.cast(usize, padded_field_end - unpadded_field_end) orelse return error.Overflow;
+                        const padding = math.cast(usize, padded_field_end -| unpadded_field_end) orelse return error.Overflow;
```
This has worked fine for me so far to avoid this panic but I don't know how correct this fix actually is.
