### ISSUE TITLE
auto deployable docs

### ISSUE THREAD

**Issue by tolitius** [ziglang/zig#1660]
Would be great to have docs tracking the latest changes especially when it has to do with syntax.

## why it would help

#760 changes struct/enum/union/error containers syntax to have a `.` in "`<container>.<body>`", however docs were not updated when the change was pushed, hence making examples in the docs (that have to do with containers) fail to compile.

**Comment by andrewrk** [comment]
b9a53c261a4abe4cdeb74513ebef80907c6517c0 should do it. let's see what happens when it completes.

**Comment by andrewrk** [comment]
Great. Now begins a game of figure out what Amazon does not accept my access control configuration and then wait 30 minutes to test it every time.

**Comment by tolitius** [comment]
> _to test it every time_

bummer

would it make sense to push it (`langref.html`) out only when it changed? or maybe to have website server pull it once X hours instead?

**Comment by andrewrk** [comment]
Ok it's hooked up and working now. Thanks for the nudge.
