### ISSUE TITLE
Packed structs inside packed struct not initialized properly

### ISSUE THREAD

**Issue by jacobly0** [ziglang/zig#16609]
Extracted from https://github.com/ziglang/zig/issues/13480#issuecomment-1575669250
> Not sure if this is the same issue @Vexu but I just ran into this:
> 
> ```zig
> const std = @import("std");
> 
> const Node = packed struct {
>     const @"c/d" = packed struct(u40) {
>         c: u32 = 0,
>         d: u8 = 0,
>     };
> 
>     const @"a/b" = packed struct(u40) {
>         a: u32 = 0,
>         b: u8 = 0,
>     };
> 
>     @"a/b": @"a/b" = .{},
>     @"c/d": @"c/d" = .{},
> 
>     pub fn init(d: u8) Node {
>         return Node{
>             // These fields work okay
>             .@"a/b" = .{ .a = d, .b = d + 1 },
>             // Writing to either of these fields will not work:
>             .@"c/d" = .{ .c = d, .d = d + 1 },
>         };
>     }
> };
> 
> pub fn main() !void {
>     const node = Node.init(9);
>     std.debug.print("{any}\n", .{node});
> }
> ```

```llvm
; Function Attrs: nounwind uwtable
define internal fastcc i80 @repro.Node.init(i8 %0) unnamed_addr #0 {
  %2 = alloca i80, align 8
  %3 = zext i8 %0 to i32
  store i32 %3, ptr %2, align 8
  %4 = getelementptr inbounds i8, ptr %2, i64 4
  %5 = call fastcc { i8, i1 } @llvm.uadd.with.overflow.i8(i8 %0, i8 1)
  %6 = extractvalue { i8, i1 } %5, 1
  br i1 %6, label %7, label %8

7:                                                ; preds = %1
  call fastcc void @repro.panic(ptr @builtin.panic_messages.integer_overflow__anon_1020, i64 16, ptr null, ptr @0)
  unreachable

8:                                                ; preds = %1
  %9 = extractvalue { i8, i1 } %5, 0
  store i8 %9, ptr %4, align 4
  %10 = zext i8 %0 to i32
  store i32 %10, ptr %2, align 1
  %11 = getelementptr inbounds i8, ptr %2, i64 4
  %12 = call fastcc { i8, i1 } @llvm.uadd.with.overflow.i8(i8 %0, i8 1)
  %13 = extractvalue { i8, i1 } %12, 1
  br i1 %13, label %14, label %15

14:                                               ; preds = %8
  call fastcc void @repro.panic(ptr @builtin.panic_messages.integer_overflow__anon_1020, i64 16, ptr null, ptr @0)
  unreachable

15:                                               ; preds = %8
  %16 = extractvalue { i8, i1 } %12, 0
  store i8 %16, ptr %11, align 1
  %17 = load i80, ptr %2, align 8
  ret i80 %17
}
```

Note that all stores to `c/d` occur to `a/b` instead.

**Comment by Pyrolistical** [comment]
Seem related to https://github.com/ziglang/zig/issues/16581
