### ISSUE TITLE
compiler segfault when creating an opaque variable as `undefined`

### ISSUE THREAD

**Issue by xdBronch** [ziglang/zig#16617]
### Zig Version

0.11.0-dev.4308+417b92f08

### Steps to Reproduce and Observed Behavior

```zig
// opaque.zig
test {
    const ot = opaque {};
    const ov: ot = undefined;
    _ = ov;
}
```
`zig test opaque.zig`

output
`segmentation fault (core dumped)  zig test c.zig` in release build of compiler
https://gist.github.com/xdBronch/40a5fe215c1b63318998260cb6085d95 contents of this gist with a debug build

### Expected Behavior

successful build or compile error, im not entirely sure the semantics of opaque types so i dont know which is expected.

**Comment by fmaggi** [comment]
if `ov` is `var` instead of `const` I get a correct error I think
```zig
test {
    const ot = opaque {};
    var ov: ot = undefined;
    _ = &ov;
}
```
```
src/main.zig:67:13: error: non-extern variable with opaque type 'main.test_0.ot'
    var ov: ot = undefined;
            ^~
src/main.zig:66:16: note: opaque declared here
    const ot = opaque {};
               ^~~~~~~~~
```
Could it be a comptime bug?
