### ISSUE TITLE
Build fails without error message when taking the address of `extern anyopaque` value

### ISSUE THREAD

**Issue by bcrist** [ziglang/zig#16627]
### Zig Version

0.11.0-dev.4308+417b92f08

### Steps to Reproduce and Observed Behavior

repro.zig:
```
extern var something: anyopaque;

pub fn main() void {
    _ = &something;
}
```
Run `zig build-exe repro.zig`.
Note it exits with non-zero result code and does not produce a binary.

I believe this used to work in earlier versions of 0.11, though I'm not sure exactly when the last time it was working was.

Changing `var something` to `const something` has no effect.
Changing `anyopaque` to `u8` results in a working build.
Changing `var something: anyopaque` to `fn something() void` results in a working build.

The use case for this is in an embedded program, accessing untyped symbols defined in a custom linker script that represent the bounds of different memory regions.  As a workaround these can be declared as functions or `u8`, but `anyopaque` communicates intent better.

### Expected Behavior

`zig build-exe` should succeed and generate an executable, or report `undefined symbol: something` if the reference is not optimized away.

**Comment by perillo** [comment]
@bcrist I tried with 0.12.0-dev.2341+92211135f on Linux and it builds correctly.
Can you confirm?
