### ISSUE TITLE
`for` should work on *[N]T

### ISSUE THREAD

**Issue by tgschultz** [ziglang/zig#1663]
Given that a pointer to an array is indexable and has a comptime-known length, it should be able to be used in the same ways as an array or slice. This would mean giving it a `.len` and making it work in for loops.

Currently attempting to use an `*[N]T` with `for` throws these two errors:
```
error: expected array type, found '*const [N]u8'
error: type '*const [N]u8' has no field 'len'
```

**Comment by Hejsil** [comment]
Just a note. `.len` is already supported on `*[N]T`
```rust
test "" {
    var a: [2]u8 = undefined;
    var b = &a;
    @import("std").debug.assert(b.len == 2);
}
```

Idk why the for loop gives the error `error: type '*const [N]u8' has no field 'len'`
