### ISSUE TITLE
ability to construct a LazyPath out of any file from a dependency package

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#16643]
The idea here is that you can put an arbitrary file contents in your build.zig.zon, like this:

```zig
.{
    .dependencies = .{
        .foo = .{
            .url = "https://example.com/foobar.tar.gz",
            .hash = "12209e851f7e2c6ba2f01de3e11b1771f03e49666065320abd8414aac152bfa75fae",
        },
    },
}
```

Normally, at this point, one would activate the `build.zig` script of the dependency like this:

```zig
    const foo_dep = b.dependency("foo", .{
        .target = target,
        .optimize = optimize,
        // ...other options...
    });
```

However, this issue is about the use case where the dependency is not a zig package, but a bundle of arbitrary files.

The idea is that you can access arbitrary files as `std.Build.LazyPath` objects, like this:

```zig
pub fn build(b: *std.Build) !void {
    // ...

    const lazy_path = b.dependencyPath("foo", "path/inside/dependency.txt");

    // now you can pass it anywhere a lazy path is accepted:
    run_step.addFileArg(lazy_path);

    // or you can access the file directly from build script logic:
    const contents = try std.fs.readFileAlloc(lazy_path.resolve());

    // ...
}
```

Using it via the LazyPath API would help with #14597, because resolution of the path would force the package to be downloaded.

**Comment by mitchellh** [comment]
This feature would also allow build-only projects to depend on their upstream source blobs instead of having to fork/vendor. This may be obvious, but pointing it out as a solid use case to enable the Zig build system to be used with any project.

**Comment by pfgithub** [comment]
Right now, this is possible using `@import("root").dependencies.build_root.$PACKAGE_NAME`, but packages require a build.zig file so an empty build.zig needs to be added:

```zig
const std = @import("std");

pub fn build(_: *std.Build) !void {}
```

**Comment by mitchellh** [comment]
> but packages require a build.zig file so an empty build.zig needs to be added:

Thanks for pointing this out, but this is a key issue that I think this issue proposes to address! 😄
