### ISSUE TITLE
missing compile error for ignoring void value

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#16642]
### Zig Version

0.11.0-dev.4315+f5239677e

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() void {
    _ = foo();
}

fn foo() void {
    var x: u32 = 4;
    std.debug.assert(x == 4);
}
```

```
$ zig run test2.zig 

$ echo $?
0
```

### Expected Behavior

error about redundant ignore

**Comment by rohlem** [comment]
An error here would make generic code that discards conditionally `void` or non-`void` be a pain to write:
You'd have to write some general statement that uses the value but is tautological,
like `const x = foo(); assert(@TypeOf(@TypeOf(x)) == type)` (note: we can no longer discard `x` either),
essentially tricking the compiler.

**Comment by nektro** [comment]
I doubt that would be much of an issue in practice. `void` is already special cased in user code in areas such as field init because you can not initialize a `void ` as `.{}`

**Comment by rohlem** [comment]
@nektro I in fact use `void` quite transparently as one of several field types in generated unions, and would be bothered by needless complication of the usage sites.
