### ISSUE TITLE
[regression] unable to do comptime branching in naked functions

### ISSUE THREAD

**Issue by davidgm94** [ziglang/zig#16651]
### Zig Version

0.11.0-dev.4407+4d7dd1689

### Steps to Reproduce and Observed Behavior

```
git clone https://github.com/birth-software/birth.git
cd birth
git switch syscall-rework
zig build
```

You will see a lot of:

```zig
src/cpu/arch/x86/64/init.zig:483:17: error: runtime call not allowed in naked function
            if (!has_error_code) {
                ^~~~~~~~~~~~~~~
```

This has regressed, since the branching should be done at comptime, yet the error message says it's done at runtime.

### Expected Behavior

Compiling successfully

**Comment by davidgm94** [comment]
This also fails: https://github.com/birth-software/birth/blob/c8409664a3bb1cc6c0d933024d54ac256453cbf2/src/user/arch.zig#L16

```zig
src/user/arch/x86_64.zig:42:1: error: runtime call not allowed in naked function
pub fn _start() callconv(.Naked) noreturn {
^~~
referenced by:
    _start: src/user/arch.zig:16:27
```

The function itself does nothing at comptime:

```zig
pub fn _start() callconv(.Naked) noreturn {
    asm volatile (
        \\push %rbp
        \\jmp *%[startFunction]
        :
        : [startFunction] "r" (user.start),
    );

    unreachable;
}
```

**Comment by jacobly0** [comment]
Note that almost all of these can be fixed by deleting `unreachable;`.  Thanks for finding these horrible source locations, and I think adding a check for `unreachable` specifically could go a long way towards improving this.
