### ISSUE TITLE
Compiler crash when compiling recursive function

### ISSUE THREAD

**Issue by teoet6** [ziglang/zig#16664]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

When compiling the following code with `zig build-exe main.zig` the compiler segfaults.
```zig
fn f(comptime msg: []const u8) !void {
    try f("a");
    _ = msg;
}

pub fn main() !void {
    try f("a");
}
```

### Expected Behavior

The compiler not to segfault.

**Comment by alichraghi** [comment]
Duplicate of #13780
