### ISSUE TITLE
Zig CC: Missing libresolv symbols when building for macOS

### ISSUE THREAD

**Issue by danielslee** [ziglang/zig#16674]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

If I create the following `main.c` file:

```c
#import <stdio.h>
#import <resolv.h>

int main(int argc, const char **argv) {
    printf("res_query: %p\n", res_query);
    return 0;
}
```

and run the following command using the `MacOSX13.3.sdk` macOS SDK:
```sh
zig cc -target x86_64-macos --sysroot ${MACOS_SDK} -isysroot ${MACOS_SDK} -I${MACOS_SDK}/usr/include -Wno-nullability-completeness -L/usr/lib -lc main.c
```

I get the this error:
```
MachO Flush... error(link): undefined reference to symbol '_res_9_query'
error(link):   first referenced in '/var/home/daniel/.cache/zig/o/d25284910ce1a4477caed3f76f77f97a/main.o'
error: UndefinedSymbolReference
```

Adding `-lresolv` does nothing. I still get the same error:

```
$ zig cc -target x86_64-macos --sysroot ${MACOS_SDK} -isysroot ${MACOS_SDK} -I${MACOS_SDK}/usr/include -Wno-nullability-completeness -L/usr/lib -lc -lresolv main.c
MachO Flush... error(link): undefined reference to symbol '_res_9_query'
error(link):   first referenced in '/var/home/daniel/.cache/zig/o/d25284910ce1a4477caed3f76f77f97a/main.o'
error: UndefinedSymbolReference
```

I suspect this happens because `libresolv` is a ["libc name"](https://github.com/ziglang/zig/blob/9c05810be60756e07bd7fee09633671bbaa8cda6/src/target.zig#L392) and therefore it gets ignored.

I have been able to find a workaround -- specifying the exact library version like `-lresolv.9` seems to bypass the `is_libc_name` check and properly links the library:

This command works without any errors:
```sh
zig cc -target x86_64-macos --sysroot ${MACOS_SDK} -isysroot ${MACOS_SDK} -I${MACOS_SDK}/usr/include -Wno-nullability-completeness -L/usr/lib -lc -lresolv.9 main.c
```

I believe that removing libresolv from the list of maOS libc libraries should work, but I'm not familiar with the zig codebase and there may be more things to consider.

### Expected Behavior

The command should link libresolv if `-lresolv` is passed and build the program without errors.

**Comment by mikdusan** [comment]
yup "resolv" should be removed from macos list of libc libraries

In #17152 commit 1b08680dcd9cd57358292f33e8394bf0d5ef67df fixes this issue.

**Comment by kubkon** [comment]
Marking as fixed by https://github.com/ziglang/zig/pull/17152
