### ISSUE TITLE
v0.11.0 unbuildable on DragonFly due to missing ucontext_t definitions

### ISSUE THREAD

**Issue by jrmarino** [ziglang/zig#16675]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

zig-0.11.0/lib/std/os.zig:192:30: error: root struct of file 'c' has no member named 'ucontext_t'

caused by:
no ucontext_t definition in lib/std/c/dragonfly.zig
(this was defined in lib/std/c/freebsd.zig)

so this no longer builds without patching.

### Expected Behavior

os.zig is expected to compile.

**Comment by jrmarino** [comment]
[lib_std_c_dragonfly.zig.patch](https://github.com/ziglang/zig/files/12261690/lib_std_c_dragonfly.zig.patch)

Applying the attached patch allows it continue building.

**Comment by mikdusan** [comment]
e1216686f3b481eda5e0e6dd025711e0f1f1f2d0 landed in master a ways back.

fyi, I'm able to build zig/master on dragonfly and basic tests pass.
