### ISSUE TITLE
Windows: unable to find zig installation directory: FileNotFound

### ISSUE THREAD

**Issue by NogrTL** [ziglang/zig#16670]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

1. Install zig using `winget install -e --id zig.zig`
2. Open some folder that's not `zig`-itself
3. Try run `zig env` or `zig init-exe`

The odd things
1. Zig as itself is available in shell (powershell7 in my case)
2. If used with absolute path to `zig.exe` it works fine

### Expected Behavior

`zig env` or `zig init-exe` runs.

**Comment by kassane** [comment]
What's to report in wiget-pkgs?
- https://github.com/microsoft/winget-pkgs/pull/103849

cc: @thechampagne

**Comment by NogrTL** [comment]
> What's not report in winget-pkgs?
> 
> * [Add zig 0.10.1 microsoft/winget-pkgs#103849](https://github.com/microsoft/winget-pkgs/pull/103849)

The reason is - Zig.exe is launching but can't detect its location inside the commands. And because it worked with other things (like ffmpeg)

**Comment by lunacd** [comment]
It'd be nice if zig recognizes some sort of environment variable pointing to its installation directory. Like ZIG_PATH or ZIG_HOME or something.

**Comment by BratishkaErik** [comment]
> It'd be nice if zig recognizes some sort of environment variable pointing to its installation directory. Like ZIG_PATH or ZIG_HOME or something.

Why would you need it? If you want to specify location of standard library, there is already envvar `ZIG_LIB_DIR`.

**Comment by BratishkaErik** [comment]
See also https://github.com/ziglang/zig/blob/f3f554b9b89cc39cf00b4df68bd3455e8ef34984/src/main.zig#L886:

And https://github.com/ziglang/zig/blob/f3f554b9b89cc39cf00b4df68bd3455e8ef34984/src/main.zig#L2584:

**Comment by lunacd** [comment]
Sorry didn't know that. Thank you for the info!

**Comment by andrewrk** [comment]
Can you please file an issue with the winget package maintainers?

**Comment by lunacd** [comment]
I did: https://github.com/microsoft/winget-pkgs/issues/117075.

Seems to be blocked by: https://github.com/microsoft/winget-cli/issues/2711.

**Comment by andrewrk** [comment]
Perhaps this can be resolved upstream. I would expect Zig to search for its lib directory relative to where the zig.exe file resides, *not* relative to where a symlink to the binary resides. Can anyone on Windows confirm that this is problem is happening, and suggest a fix to `src/introspect.zig`?

**Comment by lunacd** [comment]
Good point. Should be a simple fix. However, I don't know zig std library well enough to know how to get the real location a symlink references. If somebody points me where I should look, I can file a PR.

**Comment by lunacd** [comment]
I did set ZIG_LIB_DIR as a workaround but I can't really understand what zig's doing rn.

The env var I set: `C:\Users\haowenl\AppData\Local\Microsoft\WinGet\Packages\zig.zig_Microsoft.Winget.Source_8wekyb3d8bbwe\zig-windows-x86_64-0.11.0\lib\`.

The file zig is looking for:

```
warning: FileNotFound: C:\Users\haowenl\AppData\Local\Microsoft\WinGet\Packages\zig.zig_Microsoft.Winget.Source_8wekyb3d8bbwe\zig-windows-x86_64-0.11.0\lib\ibc\mingw\crt\crt0_c.c
```

Is the env var too long and zig is somehow overwriting stuff in its buffer?

**Comment by andrewrk** [comment]
I don't know why this happened but I see a problem in the file path:

```
lib\ibc\mingw
    ^
```

it should be `lib/libc/mingw`.

**Comment by lunacd** [comment]
Idk what's happening either. But since the libc part is what zig should be appending to the root library path, it's definitely a zig bug.

**Comment by BratishkaErik** [comment]
> Idk what's happening either. But since the libc part is what zig should be appending to the root library path, it's definitely a zig bug.

It's simple — you need to omit last separator sk that it doesn't overwrite `l` symbol. I believe there is a corresponding bug somewhere in repository.

**Comment by lunacd** [comment]
> It's simple — you need to omit last separator \ so that it doesn't overwrite l symbol. I believe there is a corresponding bug somewhere in repository.

Ah I see. It works now. Thanks!

**Comment by huyhoang160593** [comment]
> Perhaps this can be resolved upstream. I would expect Zig to search for its lib directory relative to where the zig.exe file resides, _not_ relative to where a symlink to the binary resides. Can anyone on Windows confirm that this is problem is happening, and suggest a fix to `src/introspect.zig`?
I can confirm this bug is still persist in the winget version on window 11

**Comment by squeek502** [comment]
I have this fixed locally. Will make a PR soon.

**Comment by ntswamp** [comment]
Hey how this been closed? still got the same error to date.   zig 0.12 nightly build + windows 11 with `winget`

**Comment by squeek502** [comment]
> Hey how this been closed? still got the same error to date. zig 0.12 nightly build + windows 11 with `winget`

The nightly build in winget is old and does not include the fix (the winget "nightly" is 2 months old and only 3 commits past the 0.11.0 release tag):

https://github.com/microsoft/winget-pkgs/blob/800eb18f657d8e65d1831ebd3ac147c5939316c3/manifests/z/zig/zig/nightly/0.12.0/zig.zig.nightly.installer.yaml#L10

**Comment by ntswamp** [comment]
Too sad. do we have any workaround atm? another package manager on windows `choco` simply doesn't include nightly build

**Comment by thechampagne** [comment]
whoever made nightly package in winget is mistaken because the url needs to be changed everyday and that's not a thing in winget.

**Comment by andrewrk** [comment]
@ntswamp  Just use the zip file from the download page

**Comment by HeavySnowJakarta** [comment]
NA another solution is to generate the GitHub release with the same label "nightly" when a commit happens with GitHub Actions automatically. By doing so `winget` will always detects the newest version.

**Comment by hros** [comment]
> > What's not report in winget-pkgs?
> > 
> > * [Add zig 0.10.1 microsoft/winget-pkgs#103849](https://github.com/microsoft/winget-pkgs/pull/103849)
> 
> The reason is - Zig.exe is launching but can't detect its location inside the commands. And because it worked with other things (like ffmpeg)
> 
> _UPDATE:_ I dig a bit...Looks like **winget** makes links to portables inside `%LOCALAPPDATA%\Microsoft\WinGet\Links`, at least for me. So, if your installation checking something different (like PATH and etc.) it may fail.

have you been able to resolve this issue?
I am facing a similar issue, it happens when NeoVim tries to launch zig

**Comment by hros** [comment]
> @ntswamp Just use the zip file from the download page

does this method require manual updates (including updating the env variables)?
