### ISSUE TITLE
Get Ghostty on the Zig Package Manager

### ISSUE THREAD

**Issue by mitchellh** [ziglang/zig#16672]
## Zig Version

0.11.0-dev.4404+4f6013bf5

## Steps to Reproduce and Observed Behavior

You can close this if you want. I thought it might be useful to have a tracking issue of the issues that have blocked me from getting [my terminal emulator](https://twitter.com/mitchellh/status/1662217955424493570) using the Zig package manager in 0.11. It might be a good target for 0.11.1 (I mean, I'd love that).

I've just completed getting _as far as I can_. The good news is its... pretty close? Ghostty has dozens of dependencies with multiple layers of transitive shared dependencies so its a good stress test. I'm impressed I got as far as I did. And I'm very sorry I didn't do more testing before 0.11.0 (congrats!).

**Update 10/1/2023:** Ghostty is now able to use the package manager as of `0.12.0-dev.694+937e8cb70`! See the comment for more information. This list now has additional issues we've run into but have found workarounds.

### Full Blockers

These are actively preventing me from being able to use the package manager.

- [x] https://github.com/ziglang/zig/pull/16600
  - my comment: https://github.com/ziglang/zig/pull/16600#issuecomment-1665024484

### Major Issues

These are issues that have really nasty workarounds and that I hit very regularly.

- [x] https://github.com/ziglang/zig/issues/16354 
  - my comment: https://github.com/ziglang/zig/issues/16354#issuecomment-1664911414
- [x] https://github.com/ziglang/zig/issues/15342 
  - my comment: https://github.com/ziglang/zig/issues/15342#issuecomment-1665018218

### Minor

These are issues that are easy to work around but just muck up the experience.

- [x] https://github.com/ziglang/zig/issues/16678
- [ ] https://github.com/ziglang/zig/issues/14597 (so that dependencies with symlinks can be ignored on Windows)
- [ ] https://github.com/ziglang/zig/issues/17472

The Zig core team should all have access to Ghostty's source. If you don't have access let me know. Happy to provide any more details on Discord.

### Expected Behavior

Down with all Git submodules.

**Comment by mitchellh** [comment]
Update, as of https://github.com/mitchellh/ghostty/pull/603 (for those who have access to the repo), Ghostty is now able to use the package manager with 0.12.0-dev.694+937e8cb70! 

We can't remove all of our git submodules yet due to #16678. And even once that is fixed, we're starting to work on Windows so we'll need #14597 so that deps with symlinks are skipped on Windows.

This can potentially be closed now unless you want to keep this open until we have a workaround-free setup @andrewrk.

**Comment by andrewrk** [comment]
I'm happy to keep this open if there is a checkbox with an issue number for every workaround in your setup

**Comment by mitchellh** [comment]
Got it, the root comment is up to date on all the issues, with checkboxes.

**Comment by mitchellh** [comment]
Update: Ghostty no longer has to special-case tar files with symlinks, including the macOS SDK! 

The only issue now is that on Windows we want to filter out unused dependencies. This issue is tracked as a checkbox item in the root issue.

**Comment by mitchellh** [comment]
Added #17472. We've had the Zig package manager in "production" for only a week and I find myself having to restart failed jobs a few times per day. So far all of these failed jobs have been temporary network issues, not the result of real outages.

**Comment by andrewrk** [comment]
This issue was useful while figuring out what issues to include in the 0.12.0 milestone. Now that the release is approaching, I'm going to close this and declare it a success. All the follow-up issues are tracked and assigned appropriate milestones.

**Comment by arsalanmohseni** [comment]
# **Where i can download it for windows 11??**
