### ISSUE TITLE
build: installHeadersDirectoryOptions add option for "include_extensions"

### ISSUE THREAD

**Issue by mitchellh** [ziglang/zig#16687]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

The `installHeadersDirectoryOptions` function has an option to `exclude_extensions` but it'd be much more helpful while building build packages for upstream C projects to instead have an `include_extensions` that only includes files with the given extensions. 

Example:

```zig
    lib.installHeadersDirectoryOptions(.{
        .source_dir = .{ .path = "upstream" },
        .install_dir = .header,
        .install_subdir = "",
        .exclude_extensions = &.{ ".c", ".py", ".meson", ".in", ".txt" },
    });
```

### Expected Behavior

`include_extensions` option. It doesn't need to be mutually exclusive either, both can be present... it just has to satisfy both.

**Comment by der-teufel-programming** [comment]
Do you have a good example on which this could be tested?

**Comment by mitchellh** [comment]
Yes, Harfbuzz: https://github.com/harfbuzz/harfbuzz The header files I would want to include in a library build are in `src/` but there are a LOT of other extensions in there as well. The `exclude_extensions` list gets quite long/brittle, whereas for headers it'd be a simple ".h, .hh".
