### ISSUE TITLE
@intCast should be able to forward result type through negation

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#16706]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

```zig
test {
    var x: u32 = 4;
    foo(@intCast(x));
    foo(-@intCast(x));
}

fn foo(x: i32) void {
    _ = x;
}
```

```
test.zig:4:10: error: @intCast must have a known result type
    foo(-@intCast(x));
         ^~~~~~~~~~~
test.zig:4:10: note: use @as to provide explicit result type
```

### Expected Behavior

all tests passed. both cases should work

**Comment by nektro** [comment]
`    foo(@intCast(-x));` is a compile error and bug since `x` is still a `u32` at that point

`    foo(-@as(i32, @intCast(x)));` is the recommendation from the error but extremely clunky given its being directly passed to a parameter
and prone to same maintenance footguns that caused cast builtins to remove the type param in the first place

**Comment by nektro** [comment]
should also apply to `@floatFromInt` and `@intFrom*`

**Comment by mlugg** [comment]
This isn't safe at comptime. `@as(i8, -(128))` is fine, but 128 cannot be represented by an `i8` (in this case it's a `comptime_int`).

It's worth noting this one would actually be easy to handle under ranged ints: if `-x` has result type `@Int(a, b)`, then `x` can always fit in result type `@Int(-b+1, -a+1)`.

Note that something like that would also work decently for arithmetic binops: the LHS couldn't have a result type, but the RHS' result type could be computed from the LHS type. (You can't go the other way around: it would require analyzing the RHS first to determine its type, which breaks our ordering guarantees)

**Comment by nektro** [comment]
If it can't fit at runtime then it would panic, its a known safety checked undefined behavior. `-@as(i8, (128))` would result in a compile error.

**Comment by mlugg** [comment]
I'm confused about the point you're making - I'm not talking about runtime operations at all. And yes, that example would error, but that's not the point I'm making. `@as(i8, -(128))` is currently not a compilation error, because it's a `comptime_int` which is then coerced to an `i8`. Under this system, it would become a compilation error. If you think that's fine, then sure, but this is a proposal, not a bug.

**Comment by nektro** [comment]
ah looked again, now I fully understand the example you were showing. closing i dont think it should error
