### ISSUE TITLE
update to LLVM 17

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#16703]
They already tagged rc1.

**Comment by p7r0x7** [comment]
I could be wrong, but wasn't the plan to stick to LLVM 16 until the divorce from LLVM is complete?

**Comment by molecula451** [comment]
isn't LLVM deprecated a thing?

**Comment by mlugg** [comment]
> I could be wrong, but wasn't the plan to stick to LLVM 16 until the divorce from LLVM is complete?

No: removing our dependencies on LLVM's libraries is still a ways out, and we may as well get the improvements brought by newer versions in the meantime. Also, note that the proposal you're referring to won't prevent us from sometimes having to update our LLVM support when new versions release - it's only about removing our dependencies on the LLVM *libraries*, Zig will retain support for using LLVM by emitting bitcode files itself.

**Comment by p7r0x7** [comment]
> > I could be wrong, but wasn't the plan to stick to LLVM 16 until the divorce from LLVM is complete?
> 
> No: removing our dependencies on LLVM's libraries is still a ways out, and we may as well get the improvements brought by newer versions in the meantime. Also, note that the proposal you're referring to won't prevent us from sometimes having to update our LLVM support when new versions release - it's only about removing our dependencies on the LLVM _libraries_, Zig will retain support for using LLVM by emitting bitcode files itself.

That makes sense, thanks!

**Comment by jedisct1** [comment]
@ee7 The only change between 17.0.0 and 17.0.1 is that they forgot to remove "RC" from the version number.
