### ISSUE TITLE
Printing out function type with one or more parameters fails

### ISSUE THREAD

**Issue by giann** [ziglang/zig#16729]
### Zig Version

0.11.0-dev.4333+33e4cbb20

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

test "Printing out function type" {
    std.debug.print("{}\n", .{@typeInfo(fn (u64) void)});
}
```

```
→ zig test ~/tmp-code/zig-parser.zig
/Users/giann/zig/master/lib/std/fmt.zig:662:22: error: values of type '[]const builtin.Type.Fn.Param' must be comptime-known, but index value is runtime-known
                for (value, 0..) |elem, i| {
                     ^~~~~
/Users/giann/zig/master/lib/std/builtin.zig:407:19: note: struct requires comptime because of this field
            type: ?type,
                  ^~~~~
/Users/giann/zig/master/lib/std/builtin.zig:407:19: note: types are not available at runtime
            type: ?type,
```

### Expected Behavior

Should output type structure

**Comment by Rexicon226** [comment]
While I might not have a solution to your problem, I have a somewhat of a solution.

```
const std = @import("std");

fn exampleFunction(param1: f64) void {
    _ = param1;
}

test "Example Test" {
    const functionInfo = @typeInfo(@TypeOf(exampleFunction));
    try std.testing.expect(functionInfo.Fn.params.len == 1);
}

```

To actually print something in comptime, you would probably need to use something like `@compileLog`.

This here would work:
```
const std = @import("std");

fn exampleFunction(param1: f64) void {
    _ = param1;
}

test "Example Test" {
    const functionInfo = @typeInfo(@TypeOf(exampleFunction));
    @compileLog(functionInfo);
}
```

Resulting in:
```
Compile Log Output:
@as(builtin.Type, .{ .Fn = .{.calling_convention = .Unspecified, .alignment = 1, .is_generic = false, .is_var_args = false, .return_type = void, .params = .{ .{ ... } }} })
```

**Comment by Pyrolistical** [comment]
not a bug, types are only available at compile time. @jacobly0 why was stdlib tag added?

**Comment by nektro** [comment]
see `note: struct requires comptime because of this field` and `note: types are not available at runtime` from your trace for the answer. to view comp time-only values `@compileLog` must be used.

**Comment by Rexicon226** [comment]
Another way to do it is like this:
```zig
const std = @import("std");

pub fn main() !void {
    std.debug.print(@typeName(fn (u64) void), .{});
}
```

**Comment by htqx** [comment]
There are problems with the design of std.debug.print. It is strange that it cannot print the comptime value.
I feel that I should use "inline for" instead of "for".
Now the solution can be printed to std.fmt.comptimePrint  first
Then output this string.

**Comment by RetroDev256** [comment]
Just ran into this issue with latest nightly (0.15.0-dev.1218+bc8e1a74c) - I think the issue should be re-opened:
While `type` *is* only available at compile-time, I think information about it (such as the result of `@typeInfo`) should be available for printing...

```zig
const std = @import("std");
const Struct = struct { field: void };

pub fn main() !void {
    std.debug.print("{any}\n", .{@typeInfo(Struct)});

    // This works, but the above does not:
    // std.debug.print("{s}", .{
    //     std.fmt.comptimePrint("{any}\n", .{@typeInfo(Struct)}),
    // });
}
```

**Comment by nektro** [comment]
`std.builtin.Type.Struct` has fields of type `type` and comptime-only-ness is transitive
https://github.com/ziglang/zig/blob/master/lib/std/builtin.zig#L643
