### ISSUE TITLE
Your Zig version v0.11.0-dev.4234+dc2483516 does not meet the minimum build requirement of v0.11.0

### ISSUE THREAD

**Issue by xphoniex** [ziglang/zig#16723]
### Zig Version

v0.11.0-dev.4234+dc2483516

### Steps to Reproduce and Observed Output

Try to compile https://github.com/zigtools/zls/commit/d1d4e60d543812231e3afe977f32fc6846c83962

### Expected Output

What I got:
```
/github.com/ziglang/misc/zls/build.zig:12:13: error: Your Zig version v0.11.0-dev.4234+dc2483516 does not meet the minimum build requirement of v0.11.0
            @compileError(std.fmt.comptimePrint("Your Zig version v{} does not meet the minimum build requirement of v{}", .{ current_zig, min_zig }));
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    runBuild__anon_7140: /github.com/ziglang/zig/build/stage3/lib/zig/std/Build.zig:1601:37
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```    

I expected `zig build` to succeed, since minimum build requirement is v0.11.0 and I'm on v0.11.0-dev.4234+dc2483516.

Is this message trying to say I need v0.12.0? Because when I commented out `@compileError ..` line, I still couldn't compile:

```
/github.com/ziglang/misc/zls/build.zig:103:39: error: expected struct or union; found '[]const u8'
        exe.addIncludePath(.{ .path = "src/tracy" });
                                      ^~~~~~~~~~~
referenced by:
    runBuild__anon_7140: /github.com/ziglang/zig/build/stage3/lib/zig/std/Build.zig:1601:37
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

until I updated my zig to 0.12.0-dev.17+49244dc0c.

**Comment by travisstaloch** [comment]
i know its might be confusing, but v0.11.0-dev.... is pre 0.11. also, these errors are coming from zls so i think you should move the issue to https://github.com/zigtools/zls/issues/ is there is still any issue that needs to be resolved.  i suspect that the current version of zls will build w/ zig 0.11 since its just a few days old.

**Comment by xphoniex** [comment]
I thought this was the right place to post this since it's a `builtin` function:
```zig
    comptime {
        const current_zig = builtin.zig_version;
        const min_zig = std.SemanticVersion.parse("0.11.0") catch unreachable;
        if (current_zig.order(min_zig) == .lt) { // here
            @compileError(std.fmt.comptimePrint("Your Zig version v{} does not meet the minimum build requirement of v{}", .{ current_zig, min_zig }));
        }
    }
```    

I think a lot of people will make the same mistake as me, thinking v0.11.0-dev is gt 0.11. Maybe the `.order` fn should return an err?
