### ISSUE TITLE
error with for loop

### ISSUE THREAD

**Issue by tuanyh11** [ziglang/zig#16726]
### Zig Version

0.10.0

### Steps to Reproduce and Observed Behavior
test "labelled blocks" {
    outer: for ([_]i32{ 1, 2, 3, 4 }) |_| {
        for ([_]i32{ 1, 2, 3, 4 }, 0..) |value, i| {
            if (i == 0) {
                _ = value;
                std.debug.print("index: {}\n", .{i});
                continue :outer;
            }
        }
    }
}

<img width="507" alt="Screenshot 2023-08-07 at 16 58 36" src="https://github.com/ziglang/zig/assets/84113815/d9dbfd0e-5945-4353-af41-1fd8e9538100">

### Expected Behavior

<img width="390" alt="Screenshot 2023-08-07 at 16 57 50" src="https://github.com/ziglang/zig/assets/84113815/dcc25016-36b0-4acc-baa3-010db6647d2a">

**Comment by der-teufel-programming** [comment]
This is not a bug. Multi-Object for loops were introduced after 0.10, they are present in the new 0.11 release
