### ISSUE TITLE
HTTP server causing `error.MessageNotCompleted` with HEAD request and Content-Length

### ISSUE THREAD

**Issue by LordMZTE** [ziglang/zig#16731]
### Zig Version

0.12.0-dev.15+1c7798a3c

### Steps to Reproduce and Observed Behavior

1. Run this code:
```zig
const std = @import("std");

pub fn main() !void {
    var server = std.http.Server.init(std.heap.page_allocator, .{});
    defer server.deinit();

    try server.listen(std.net.Address.initIp4(.{ 127, 0, 0, 1 }, 42069));

    var con = try server.accept(.{ .allocator = std.heap.page_allocator });
    defer con.deinit();

    try con.wait();

    // HEAD request
    std.debug.assert(con.request.method == .HEAD);

    // Set Content-Length header for client.
    // Since this is a HEAD request, there will be no body.
    con.transfer_encoding = .{ .content_length = 42 };

    try con.do();
    try con.finish(); // error.MessageNotCompleted here
}
```

2. While the above code is waiting, run `curl --head http://127.0.0.1:42069` in a separate shell.

3. This error is thrown:
```
error: MessageNotCompleted
/home/lordmzte/.local/share/zupper/installs/master/lib/std/http/Server.zig:640:52: 0x231c11 in finish (test)
            .content_length => |len| if (len != 0) return error.MessageNotCompleted,
                                                   ^
/home/lordmzte/Downloads/test.zig:22:5: 0x230ccc in main (test)
    try con.finish();
    ^
```

### Expected Behavior

The code runs without an error.

This error happens as `std.http.Server` assumes that the amount of bytes written to the body must always correspond to the value in the `Content-Length` header, this does however not apply to `HEAD` requests, which may include the header while having a 0-length body as per [this paragraph](https://www.rfc-editor.org/rfc/rfc9110#section-8.6-6) in RFC 9110.

**Comment by The-flaSK** [comment]
I didnt got any errors . Except i got 
```array_list.ArrayListAligned(main.Block,null){ .items = { main.Block{ .user = main.block_state.none, .filled = false, .index = 1 }, main.Block{ .user = main.block_state.none, .filled = false, .index = 2 }, main.Block{ .user = main.block_state.none, .filled = false, .index = 3 }, main.Block{ .user = main.block_state.none, .filled = false, .index = 4 }, main.Block{ .user = main.block_state.none, .filled = false, .index = 5 }, main.Block{ .user = main.block_state.none, .filled = false, .index = 6 }, main.Block{ .user = main.block_state.none, .filled = false, .index = 7 }, main.Block{ .user = main.block_state.none, .filled = false, .index = 8 }, main.Block{ .user = main.block_state.none, .filled = false, .index = 9 } }, .capacity = 20, .allocator = mem.Allocator{ .ptr = anyopaque@0, .vtable = mem.Allocator.VTable{ .alloc = fn(*anyopaque, usize, u8, usize) ?[*]u8@222710, .resize = fn(*anyopaque, []u8, u8, usize, usize) bool@222900, .free = fn(*anyopaque, []u8, u8, usize) void@222b80 } } }⏎```
