### ISSUE TITLE
Syntax flaw: Async calls

### ISSUE THREAD

**Issue by Hejsil** [ziglang/zig#1676]
While trying to come up with a better solution for #760, I found this nice little syntactic ambiguity:
```rust
_ = async fn()void ();
// Two options:
// async (fn()void) ()
// (async fn()void) ()
```

**Comment by Hejsil** [comment]
This is not ambiguous as of #1685, but the rule for parsing this is a hack.

> > Just another note here. [C# doesn't' use an async prefix to call async functions](https://docs.microsoft.com/en-us/dotnet/csharp/async). What do we gain from having this prefix, once coroutines change?
> 
> I think it's a reasonable idea to not require special syntax at the callsite for async functions. The only thing it would do is document the calling convention at the callsite. However, I am now convinced that isn't useful. Because in order to know the return type of the function call, you need to look at the function prototype, which has the calling convention as well as the return type.
> 
> So  from me to deleting `async` at the callsite.

**Comment by andrewrk** [comment]
The async function rewrite is complete but I believe this parsing hack still exists.

It's not clear to me why `(async fn()void) ()` is an option. The syntax after `async` must be a function *call*.

In response to the previous comment, async functions can now be called with no async prefix. But they can also be called with an async prefix, which has different meaning.

**Comment by SpexGuy** [comment]
Since `async` is now a calling convention on function declarations, and not allowed as a prefix, this is no longer ambiguous.
