### ISSUE TITLE
wasm outputs has no exports

### ISSUE THREAD

**Issue by hronro** [ziglang/zig#16772]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

- `zig init-lib`
- Change `b.addStaticLibrary` to `b.addSharedLibrary` in `build.zig`
- Run `zig build -Dtarget=wasm32-freestanding`

`zig-out/lib/mylib.wasm` doesn't contains any exports.

### Expected Behavior

The wasm file should contains the `add` function, which is defined in the `src/main.zig` which is generated by `zig init-lib`.

**Comment by schmee** [comment]
You need to add the `--export` flag, see https://github.com/ziglang/zig/issues/14139 and https://github.com/ziglang/zig/pull/14102 for more explanation.

**Comment by Luukdegram** [comment]
See also the [language reference](https://ziglang.org/documentation/0.11.0/#WebAssembly) and the [release-notes](https://ziglang.org/download/0.11.0/release-notes.html#WebAssembly) that document this change.

**Comment by hronro** [comment]
But is there a way to add `--export` flag in `build.zig`?
