### ISSUE TITLE
Incorrect translate-c result when importing both unistd.h and stdlib.h on OSX

### ISSUE THREAD

**Issue by tomc1998** [ziglang/zig#1678]
Hey!

A while back on IRC I mentioned I couldn't import enet.h (a network abstraction library) on OSX because of an incorrect (?) translation. Today I realised that this issue isn't that isolated, and will in fact occur when importing both unistd.h and stdlib.h. Here is an example:

```
const c = @cImport({
  @cInclude("stdlib.h");
  @cInclude("unistd.h");
});


pub fn main() void {
  c.sleep(1); // Only here to make sure zig evaluates the @cImport
}
```

This generates the following error:

```
foo/main.zig:1:11: error: compiler bug: @cImport generated invalid zig code
const c = @cImport({
          ^
?.c:1:1: note: redefinition of 'suboptarg'
TODO: remember C source location to display here
^
?.c:1:1: note: previous definition is here
TODO: remember C source location to display here
^
```

Interestingly, this issue doesn't persist if you separate out the @cImport:

```
const unistd = @cImport({
  @cInclude("unistd.h");
});

const stdlib = @cImport({
  @cInclude("stdlib.h");
});



pub fn main() void {
  // Again, this is only here to make sure zig processes BOTH @cImports.
  _ = unistd.sleep(1);
  const buf = stdlib.malloc(8).?;
  stdlib.free(buf);
}
```

The above code compiles fine.

The issue also occurs whenever you import another .h file which imports both stdlib.h and unistd.h (for example, enet.h from the enet library).

**Comment by ul** [comment]
I hit the same issue having libuv included as a transitive dependency, which, in its own turn, includes both stdlib and unistd.

**Comment by daurnimator** [comment]
@tomc1998 this should be fixed on master; could you check?

**Comment by tomc1998** [comment]
@daurnimator Don't have access to OSX anymore, sorry!

**Comment by ul** [comment]
I just tested on macOS 10.15.2, it's fixed.
