### ISSUE TITLE
Can I somehow ignore compiler errors later, and print some info to fix the first compile time error that the zig compiler gives me

### ISSUE THREAD

**Issue by CGQAQ** [ziglang/zig#16809]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Output

Let's say I have a project that upgrades from zig `0.10` to `0.11`, of course, I will have a lot of compiler errors. the first error that Compiler gives me is
```
src/resolver/resolver.zig:2450:48: error: no field named 'dir_info_uncached_path' in enum 'meta.DeclEnum(src.resolver.resolver.bufs__struct_47531)'
        var dir_info_uncached_path_buf = bufs(.dir_info_uncached_path);
```

the code looks like this 
```zig
const bufs = struct {
    // .............
    threadlocal var dir_info_uncached_path: [bun.MAX_PATH_BYTES]u8 = undefined;
    // .............
    pub inline fn bufs(comptime field: std.meta.DeclEnum(@This())) *@TypeOf(@field(@This(), @tagName(field))) {
        return &@field(@This(), @tagName(field));
    }
}.bufs;
```

I want to print out some info about the field to figure out why this error is emitted, BUT, I cannot log out anything(I think it's because there are other compile errors I need to solve first?), which is really annoying and make it harder to debug comptime code IMO

The point is in runtime code, I can log something although I may have runtime errors later, why I can not do the same thing in comptime

Is there any way I can somehow achieve this?

P.S. I tried `@compileLog`, and tried intentionally introducing  compile time error, but it didn't work

**Comment by nektro** [comment]
the error is happening because `dir_info_uncached_path` isn't `pub`.

zig will by default print as many compile errors as it can (at least one per decl it's analyzing) but its lazy analysis prevents this depending on how early in your codebase it occurs (think how many branches a tree has as it reaches more depth)

**Comment by CGQAQ** [comment]
Thanks! @nektro . I know it's lazy and has all kinds of fancy stuff, but at least print out `@compileLog`s, so it is easier to debug compile-time errors

**Comment by CGQAQ** [comment]
Thanks! @nektro . I know it's lazy and has all kinds of fancy stuff, but at least print out `@compileLog`s, so it is easier to debug compile-time errors

**Comment by CGQAQ** [comment]
At this point, we can write compile-time code just like runtime code(same syntax, same mental model), I think it would be great to have abilities to debug like normal zig code(logging for example)

**Comment by wooster0** [comment]
> at least print out `@compileLog`s, so it is easier to debug compile-time errors

I agree. That is #14711.

**Comment by mlugg** [comment]
@wooster0, that proposal is unrelated - that's to do with debugging compiler *crashes*.

@CGQAQ, I'm having trouble replicating your issue with `@compileLog`:
```zig
test {
    @compileLog("a"); // this log shows up
    @compileLog("b"); // as does this one
    _ = error.Foo; // this line will emit a compile error
    @compileLog("c"); // this line is not expected to show, as it comes after the compile error
}
```
```
$ zig test bar.zig
bar.zig:4:9: error: error is discarded
    _ = error.Foo; // this line will emit a compile error
        ^~~~~~~~~
bar.zig:4:9: note: consider using 'try', 'catch', or 'if'

Compile Log Output:
@as(*const [1:0]u8, "a")
@as(*const [1:0]u8, "b")
```
What exactly did you try?

**Comment by CGQAQ** [comment]
Oh! I see, sorry, didn't notice, it was at the very end, I thought the compile log will be at just before the compiler error
