### ISSUE TITLE
@enumFromInt missing result type for casts when result enum has explicit backing integer

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#16814]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() !void {
    var x: i8 = 2;
    var y: E = @enumFromInt(@intCast(x));
    std.debug.assert(y == .c);
}

const E = enum(u8) {
    a,
    b,
    c,
    d,
};
```

```
test.zig:5:29: error: @intCast must have a known result type
    var y: E = @enumFromInt(@intCast(x));
                            ^~~~~~~~~~~
test.zig:5:29: note: use @as to provide explicit result type
```

### Expected Behavior

`@intCast` should be able to get the result type of `u8` from the `@enumFromInt` call

**Comment by mlugg** [comment]
Turns out `@enumFromInt` (intentionally) allows the int value to be a larger type than the backing int, and implicitly `@intCast`s it down. That means a result type would be incorrect here.
