### ISSUE TITLE
unsupported linker arg: --no-undefined-version

### ISSUE THREAD

**Issue by DavidZbarsky-at** [ziglang/zig#16855]
### Zig Version

0.11.0-dev.3886+0c1bfe271 

### Steps to Reproduce and Observed Behavior

I am using zig as a hermetic toolchain when building C and Rust code (https://github.com/uber/hermetic_cc_toolchain)

It looks as of https://github.com/rust-lang/rust/pull/108017, upstream llvm defaults to passing `-undefined-version` when it detect lld, which Rustc overrides with `--no-undefined-version`, which Zig doesn't know about yet. (See https://reviews.llvm.org/D135402 for more details)

Could these two flag be implemented (or at least turn --no-undefined-version into a no-op for now)?

It's a bit complicated to get a reduced repro case so hopefully this is clear enough, but let me know if you really need one.

### Expected Behavior

Link my object

**Comment by DavidZbarsky-at** [comment]
If ignoring `--no-undefined-version` for now is an acceptable fix, I'm happy to send a PR, should be trivial.

**Comment by DhashS** [comment]
I've also run into this issue, but the solution proposed by @dbanetto isn't going to work for me, as some dependent libraries require `rust_version >= 1.70.0`.

Couple additional notes:
- This does not occur when using `cargo zigbuild`, just with the hermetic bazel toolchain thing

As a result, I've opened up a PR https://github.com/ziglang/zig/pull/17326 adding this, but would really welcome a second set of eyes (it feels wrong/incomplete to me) to make sure that i'm parsing / passing the flag around correctly from the `zig cc` invocation to actual LLVM. I'm happy to flesh this out more and I hope this can land in zig-next to unbreak that toolchain :)

**Comment by atoav** [comment]
I am not sure if this is the right place, but I had a Rust/Python project that was broken by this. I build python wheels using maturin:

```bash
maturin build --release --interpreter python3.9 --target x86_64-unknown-linux-gnu --zig
```

Using a rustc 1.74 this failed with the mentioned error.
I could get it to build again by reverting back to 1.69 as mentioned above:

```bash
rustup default 1.69
```

Is this issue still looked into? I'd love to be able to use a newer rustc version.
