### ISSUE TITLE
JSON parsing with `std.json.Value.jsonParse` fails oddly after certain input sizes

### ISSUE THREAD

**Issue by drunderscore** [ziglang/zig#16861]
### Zig Version

0.12.0-dev.98+3e228bdf4

### Steps to Reproduce and Observed Behavior

With the following code:
```zig
const std = @import("std");
const network_dump_embedded = @embedFile("test.json");

test "does this json parse" {
    var arena_allocator = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_allocator.deinit();

    const allocator = arena_allocator.allocator();

    var json_embedded_stream = std.io.fixedBufferStream(network_dump_embedded);
    var json_embedded_reader = json_embedded_stream.reader();

    var json_reader = std.json.reader(allocator, json_embedded_reader);

    var parsed_json = try std.json.Value.jsonParse(allocator, &json_reader, .{});

    std.debug.print("-----\n", .{});

    var iterator = parsed_json.object.iterator();
    while (iterator.next()) |kv|
        std.debug.print("{s}\n", .{kv.key_ptr.*});

    std.debug.print("-----\n", .{});
}
```

And using the attached `test.json` file, the nonsensical output below is generated:
```
iiii
```

I've attached a secondary reproduction file named `network_dump_minimized.json` that produces equally-nonsensical output.

It is noteworthy that this previously worked with Zig using the older dynamic JSON parsing API.

### Expected Behavior

The output should be the keys listed, such as in `test.json`:
```
test
```

Or as in `network_dump_minimized.json`:
```
client_class_name_for_client_class_id
```

Files for reproduction, with the `.txt` extension so GitHub will accept them (these cannot be uploaded in the above reproduction steps unfortunately):

[network_dump_minimized.json.txt](https://github.com/ziglang/zig/files/12364163/network_dump_minimized.json.txt)
[test.json.txt](https://github.com/ziglang/zig/files/12364164/test.json.txt)

**Comment by dec05eba** [comment]
It seems to happen when the string is around 4096 characters long or something like that. Is there a fixed buffer with size 4096 somewhere in the code or something like that?

**Comment by drunderscore** [comment]
Agreed, did the same thing just now and issues disappeared. Using `network_dump_embedded.len` as the buffer size seems like a working stop-gap (if you know the length of your input.)

I assume this is still a real issue, or am I misusing the JSON reader in some way?

**Comment by dec05eba** [comment]
I'm pretty sure it's a bug.

**Comment by dec05eba** [comment]
Actually.. I dont think applications are supposed to use Value.jsonParse directly, especially like this.

**Comment by dec05eba** [comment]
I tested json.parseFromTokenSource with std.json.Reader and it has the same issue on that test file. When a string is around the size of the reader buffer size the reader stops working correctly when it reaches that end.

**Comment by ianprime0509** [comment]
This doesn't seem right, at least from what I can tell: https://github.com/ziglang/zig/blob/f1992a39a59b941f397b8501a525b38e5863a527/lib/std/json/dynamic.zig#L109-L118 In the case of `string` (rather than `allocated_string`), the resulting `key` may not be valid after the buffer gets refilled later on (e.g. in this case of a value larger than the buffer size).

Changing `.alloc_if_needed` to `.alloc_always` on line 109 makes the example work as expected, supporting the theory that that's what's happening here. But maybe there's something I'm missing in terms of the design. If this is the real reason, there are several other `.alloc_if_needed`s elsewhere in this file which might result in similar issues.
