### ISSUE TITLE
corrupted slice return value

### ISSUE THREAD

**Issue by emekoi** [ziglang/zig#1687]
i have a function for turning a utf8 string into a utf16 one. it looks like this:
```
pub fn L(str: []const u8) []u16 {
    var result = []u16.{0} ** 512;
    const last = std.unicode.utf8ToUtf16Le(result[0..], str) catch unreachable;
    result[last] = 0;
    return result[0..last];
}
```
each time i run on the string "hello_world" the first four bytes are correct but then i have four null bytes, then last 2 bits that are different each time and another null byte. (`[]u16{104,101,108,108,0,0,0,0,*,*,0,}`). but if change the function to 
```
pub fn L(str: []const u8) [512]u16 {
    var result = []u16.{0} ** 512;
    const last = std.unicode.utf8ToUtf16Le(result[0..], str) catch unreachable;
    result[last] = 0;
    return result;
}
```
i get the right result every time. does this have something to do with returning a stack variable?

**Comment by BarabasGitHub** [comment]
Probably, as you're returning a slice to an array which is on the stack.

**Comment by emekoi** [comment]
hmm, i thought so.
