### ISSUE TITLE
mixed zig build-obj and zig build-exe with c object cause duplicate symbol: _start on Linux

### ISSUE THREAD

**Issue by taikoo** [ziglang/zig#16871]
### Zig Version

0.12.0-dev.109+f3f554b9b, Linux, aarch64

### Steps to Reproduce and Observed Behavior

main.zig
```zig
const std = @import("std");

extern fn say() void;

pub fn main() void {
    std.debug.print("hello\n", .{});
    say();
}
```

say.c
```c
#include <stdio.h>

void say() {
    printf("hello from c\n");
}
```

## build 1
```
$ zig build-exe --name hello main.zig say.c --library c
```
or 
```
$ gcc -c -o say.o say.c
$ zig build-exe --name hello main.zig say.o --library c
```
all fine.

## build 2
```
$ gcc -c -o say.o say.c
$ zig build-obj main.zig
$ zig build-exe --name hello main.o say.o --library c
error: ld.lld: duplicate symbol: _start
    note: defined at /usr/lib/gcc/aarch64-linux-gnu/11/../../../aarch64-linux-gnu/crt1.o:(_start)
    note: defined at start.zig:243 (/home/ubuntu/.zig/toolchains/0.12.0-dev.109+f3f554b9b/lib/std/start.zig:243)
    note:            main.o:(.text+0x0)
```

## build 3 on macOS

repeat build 2 on macOS, works.

### Expected Behavior

`zig build-obj` works with `zig build-exe` on all platforms.

just like:

```
$ gcc -c -o main.c
$ gcc -c -o say.c
$ gcc -o hello main.o say.o
```
it seems `zig build-obj` behave differently when there's a `pub fn main() ...`.

**Comment by mikdusan** [comment]
I don't think this is a bug. On linux try adding `-lc` (or `--library c`) while building .o ... otherwise zig thinks it needs to supply additional startup code.

```sh
$ gcc -c -o say.o say.c
$ zig build-obj main.zig -lc
$ zig build-exe --name hello main.o say.o -lc
```

**Comment by taikoo** [comment]
> 
> ```shell
> $ gcc -c -o say.o say.c
> $ zig build-obj main.zig -lc
> $ zig build-exe --name hello main.o say.o -lc
> ```
Yes, I can do that.
Maybe I just misunderstanding `zig build-obj`' s purpose and design.
I'm expecting the way as `gcc -c -o`: just compile, no linking information needed, 
and hoping they can behave the same on Linux and macOS: no `-lc` needed on macOS.

**Comment by mikdusan** [comment]
Zig linux targets by default do not use libc. Other targets such as macos and BSDs, do use libc by default, which is why macos does not need `-lc`.

**Comment by taikoo** [comment]
> Zig linux targets by default do not use libc. Other targets such as macos and BSDs, do use libc by default, which is why macos does not need `-lc`.

Thanks for the information.
