### ISSUE TITLE
Cannot compile for iOS target (static lib or executable)

### ISSUE THREAD

**Issue by jmrico01** [ziglang/zig#16880]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

Running on macOS, and tested in both an Intel and M1 Macbook.

1. Start with a fresh directory, `mkdir ios-test`
2. `zig init-lib`
3. `zig build -Dtarget=aarch64-ios`

I get the following error:
```
ios-test legionmac$ zig-0.11.0 build -Dtarget=aarch64-ios
zig build-lib ios-test Debug aarch64-ios: error: the following command failed with 1 compilation errors:
/Users/legionmac/zig-macos-x86_64-0.11.0/zig build-lib /Users/legionmac/Documents/ios-test/src/main.zig --cache-dir /Users/legionmac/Documents/ios-test/zig-cache --global-cache-dir /Users/legionmac/.cache/zig --name ios-test -static -fno-stack-check -target aarch64-ios -mcpu generic --listen=- 
Build Summary: 0/3 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install ios-test transitive failure
   └─ zig build-lib ios-test Debug aarch64-ios 1 errors
/Users/legionmac/zig-macos-x86_64-0.11.0/lib/std/dwarf/abi.zig:371:58: error: no field named 'sp' in struct 'c.darwin.aarch64.mcontext_t'
                31 => mem.asBytes(&ucontext_ptr.mcontext.sp),
                                                         ^~
/Users/legionmac/zig-macos-x86_64-0.11.0/lib/std/c/darwin/aarch64.zig:5:31: note: struct declared here
pub const mcontext_t = extern struct {
                       ~~~~~~~^~~~~~
```

I don't get this error when building for `-Dtarget=native-ios-simulator` on the Intel Macbook, AKA for `x86_64-ios-simulator`, which suggests this is an issue for `aarch64-ios` specifically.

#### Workaround
Provide a custom panic override in your `main.zig` file such that the default `std.debug.panicImpl` doesn't get called, so these stack-unwinding functions are not compiled. A basic no-op panic override looks like
```zig
pub fn panic(msg: []const u8, error_return_trace: ?*std.builtin.StackTrace, ret_addr: ?usize) noreturn
{
    _ = msg; _ = error_return_trace; _ = ret_addr;
    std.os.abort();
}
```
*EDIT:* This workaround is not 100% guaranteed. Tried in a larger codebase and it seems like sometimes the stack-unwind code is compiled anyway and I get the compile error, even though I'm pretty sure I'm not using it anywhere 😢 

### Expected Behavior

Expected the static library to build and produce a `libios-test.a` binary.

**Comment by kubkon** [comment]
This was fixed in https://github.com/ziglang/zig/pull/16839/commits/bbe82ef44eb81b5593ca2e8e86db0ddaab7a830a
