### ISSUE TITLE
changing pointers

### ISSUE THREAD

**Issue by emekoi** [ziglang/zig#1688]
in my code i pass a pointer to a struct to one of it's method but the pointer's address differs from the address of the actual struct by 20. the address of the actual struct also differs from the address of the struct i return in the initializer by 4 as well. the code in question is [here](https://github.com/emekoi/ziglet/blob/total-rewrite/examples/basic.zig). running the code on windows will produce 3 different values for the address of the window. an anyone tell me why the pointers are all different?

**Comment by winksaville** [comment]
Supplying an a code sample of the failure would be helpful.

**Comment by emekoi** [comment]
here's an example that's just produces different random pointer values:
```
const std = @import("std");

pub fn main() void {
    const opts = Window.Options.{ .title = "hello_world" };
    var window = Window.init(opts);
    std.debug.warn("main: {}\n", @ptrToInt(&window));
    window.info();
}

pub const Window = struct.{
    const Self = @This();

    pub const Options = struct.{ title: []const u8 };

    title: []const u8,

    pub fn init(options: Options) Self {
        var result = Self.{ .title = options.title };
        std.debug.warn("init: {}\n", @ptrToInt(&result));
        return result;
    }

    pub fn info(self: *Self) void {
        std.debug.warn("info: {}\n", @ptrToInt(&self));
    }

};

```

**Comment by tgschultz** [comment]
```
    pub fn init(options: Options) Self {
        var result = Self.{ .title = options.title };
        std.debug.warn("init: {}\n", @ptrToInt(&result));
        return result;
    }
```
copy elision isn't in yet (see #287, #1682), so the result struct created in this function body is copied on return.


```
    pub fn info(self: *Self) void {
        std.debug.warn("info: {}\n", @ptrToInt(&self));
    }
```
`self` is a pointer, so `&self` is a pointer to a pointer.


```
pub fn main() void {
    const opts = Window.Options.{ .title = "hello_world" };
    var window = Window.init(opts);
    std.debug.warn("main: {}\n", @ptrToInt(&window));
    window.info();
}
```
This is the struct that was copied from the struct created in `Window.init`.

**Comment by emekoi** [comment]
thanks! this was really messing me up.
