### ISSUE TITLE
Literal `-0` does not resolve to floating-point signed zero

### ISSUE THREAD

**Issue by castholm** [ziglang/zig#16890]
`@as(f32, -0)` returns `0.0` and not `-0.0`. This is probably not what the user expects and could result in subtle bugs in code that explicitly depends on the signed zero, such as in math library functions and tests for said functions.

Consider this sample program:
```zig
const std = @import("std");

pub fn main() void {
    const a: f32 = -0;
    std.debug.print("{}\n", .{a});
    std.debug.print("0x{x:0>8}\n", .{floatBits(a)});

    const b: f32 = -0.0;
    std.debug.print("{}\n", .{b});
    std.debug.print("0x{x:0>8}\n", .{floatBits(b)});
}

fn floatBits(x: anytype) std.meta.Int(.unsigned, @typeInfo(@TypeOf(x)).Float.bits) {
    return @bitCast(x);
}
```
This program prints
```
0.0e+00
0x00000000
-0.0e+00
0x80000000
```
instead of the expected `-0.0e+00`/`0x80000000` for both variables.

It would probably be better if the literal `-0` either

- always resolved to the value `-0.0` of type `comptime_float`, or
- always resulted in a compile error prompting the user to rewrite it as either `0` or `-0.0` to clarify intent.

The same should also hold true for other variants of the integer literal `-0` such as `-0x0`, `-0o0` and `-0b0`.

**Comment by mlugg** [comment]
I like the idea of emitting a compile error for the integer literal `-0`. As you suggest, it's a problem of ambiguous intent - if you wanted an integer literal then it's odd that you're writing it like that, and if you wanted a signed float zero you should write it as a float literal for clarity (since in this context the specific type of the value is clearly very important).

**Comment by castholm** [comment]
@nektro Why the drive-by thumbs down? It would be more constructive if you explained why you think this is either not a problem worth solving or why neither proposed solution is sufficient.

**Comment by andrewrk** [comment]
@mlugg I agree, feel free to make this change
