### ISSUE TITLE
Strange behavior when printing to the console (during test)

### ISSUE THREAD

**Issue by Lking03x** [ziglang/zig#16916]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

When printing during test, the output may be truncated and appears as if entire instructions after a output have been dismissed.

Example for truncating:
```zig
const std = @import("std");

fn agreement() void {
    std.debug.print("1 + 1 is 2, thus, Adamantly, Love is a Hurricane!", .{});
}

test "This is a test." {
    std.debug.print("Love is a hurricane!", .{});
    std.debug.print("Love is a hurricane!", .{});
    std.debug.print("Love is a hurricane!", .{});
    std.debug.print("Love is a hurricane!", .{});
    // agreement();
}
```
- without calling *agreement* it print: ```Test [1/1] test.This is a test.... Love is a hurricane!Love is a hurricane!Love All 1 tests passed.```
- with agreement: ```Test [1/1] test.This is a test.... Love is a hurricane!Love is a hurricane!Love is a hurricane!Love is a hurricane!1 + 1 is 2, thAll 1 tests passed.```
- With a single print and without *agreement*: ```Test [1/1] test.ThisAll 1 tests passed.```

### Expected Behavior

Output all the printed texts
I'm using the test system to explore behavior of some functions and wanting to print/show the results but it just look like nothing is happening.

Thanks in advance.

**Comment by ProkopRandacek** [comment]
You probably want to add a newline at the end of each format string.

but I agree that the current test runner output is often mixing with the program output confusingly

**Comment by nektro** [comment]
yes `std.debug.print` does not append its own newline

and the test runner is built under the current assumption you will not print to stdout, see https://github.com/ziglang/zig/issues/15091 for discussion

its best to use `pub fn main()` for when you're building and `test {` for when you're actually unit testing known behavior

**Comment by Lking03x** [comment]
Thanks for the responses.
I will just use ```main``` instead.
