### ISSUE TITLE
Got a lot of comptime related errors after update to zig 0.11

### ISSUE THREAD

**Issue by CGQAQ** [ziglang/zig#16920]
### Zig Version

0.11

### Steps to Reproduce and Observed Behavior

compile bun with `0.11.0` or `0.12.0`

compiler errors emitted: 
[0.11.0](https://pastebin.ubuntu.com/p/GrVdMVx3Ph/)
[0.12.0-dev.157+8e96be008](https://pastebin.ubuntu.com/p/K6Y9dGgfDt/)

I think it's related to https://ziglang.org/download/0.11.0/release-notes.html#Forbid-Runtime-Operations-in-comptime-Blocks-

see https://github.com/oven-sh/bun/pull/4233#issuecomment-1687293766 for context

An example in these errors:

```
src/bun.js/api/bun/dns_resolver.zig:1144:31: note: struct requires comptime because of this field
    pending_host_cache_cares: PendingCache = PendingCache.init(),
```

```zig
pub const DNSResolver = struct {
    pending_host_cache_cares: PendingCache = PendingCache.init(),
    //  ^ I don't think this will force DNSResolver to be comptime
};
const PendingCache = bun.HiveArray(GetAddrInfoRequest.PendingCacheKey, 32);
pub fn HiveArray(comptime T: type, comptime capacity: u16) type {
      return struct {
           const Self = @This();
           buffer: [capacity]T = undefined,
           available: std.bit_set.IntegerBitSet(capacity) = std.bit_set.IntegerBitSet(capacity).initFull(),
           pub const size = capacity;

           pub fn init() Self {
               return .{};
           }
     };
}
```

### Expected Behavior

Maybe should've not got these errors? not very sure.

**Comment by CGQAQ** [comment]
caused by 
> pub const WriterType: type = @TypeOf(WriteStream(Source.StreamType, undefined));

I accidentally `@TypeOf`ed a type, but the compiler error is not correct at all IMO



https://github.com/oven-sh/bun/pull/4233#issuecomment-1687436225

**Comment by rohlem** [comment]
> the compiler errors is not correct at all IMO

Not sure I agree (`@TypeOf(type)` is perfectly legal), but at least a trace from `PendingCache` through its members to list the member (or all members) causing this (and writing out its type being `type` / their types) would be helpful, if isn't produced currently.
