### ISSUE TITLE
std.DynamicBitSet: add `clear` function

### ISSUE THREAD

**Issue by silversquirl** [ziglang/zig#16925]
It's useful to be able to reuse the allocated memory while resetting the bitset to an empty state. Currently, the only way to do that is `setRangeValue`, however this [does not generate good code][godbolt]. A much better option is to simply `@memset` the whole allocated array to zero.

An equivalent for setting to full could also be useful, so perhaps naming them `setAll` and `unsetAll` would be better.

Equivalents for `StaticBitSet` are less necessary as that type can be reset by reassigning to one of its init functions, but could be useful for API symmetry.

[godbolt]: https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:zig,selection:(endColumn:1,endLineNumber:7,positionColumn:1,positionLineNumber:7,selectionStartColumn:1,selectionStartLineNumber:6,startColumn:1,startLineNumber:6),source:'const+std+%3D+@import(%22std%22)%3B%0A%0Aexport+fn+clearWithSetRangeValue(set:+*std.DynamicBitSet)+void+%7B%0A++++set.setRangeValue(.%7B+.start+%3D+0,+.end+%3D+set.capacity()+%7D,+false)%3B%0A%7D%0A%0Aexport+fn+clearDirect(set:+*std.DynamicBitSet)+void+%7B%0A++++@memset(set.unmanaged.masks%5B0..numMasks(set.capacity())%5D,+0)%3B%0A%7D%0A//+Copied+from+std.DynamicBitSet%0Afn+numMasks(bit_length:+usize)+usize+%7B%0A++++return+(bit_length+%2B+(@bitSizeOf(std.DynamicBitSet.MaskInt)+-+1))+/+@bitSizeOf(std.DynamicBitSet.MaskInt)%3B%0A%7D%0A'),l:'5',n:'0',o:'Zig+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:ztrunk,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:zig,libs:!(),options:'-OReleaseFast',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+zig+trunk+(Editor+%231)',t:'0')),k:50,l:'4',m:85.8195211786372,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'zig+trunk',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+zig+trunk+(Compiler+%231)',t:'0')),header:(),l:'4',m:14.180478821362797,n:'0',o:'',s:0,t:'0')),k:50,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

**Comment by sagehane** [comment]
Looks like https://github.com/ziglang/zig/commit/09d13104bee07099c53f6df75e6c619793f43f18 resolved this.

**Comment by jar2333** [comment]
What happened to these methods? Making use of std.bitset rn in an algorithm and it being gone is unfortunate...

**Comment by nektro** [comment]
Please check out one of our great [Community](https://github.com/ziglang/zig/wiki/Community)s for help :)
