### ISSUE TITLE
zig fmt: empty test name

### ISSUE THREAD

**Issue by Arnau478** [ziglang/zig#16927]
`zig fmt` should replace
```zig
test "" {
    // ...
}
```
with
```zig
test {
    // ...
}
```

**Comment by silversquirl** [comment]
zig fmt is not supposed to fix errors automatically, it only formats and updates already-valid code (or, in the case of updates, code that used to be valid but isn't any more).

**Comment by Arnau478** [comment]
Wasn't an empty test name valid like on 0.8.0 or something like that?

**Comment by silversquirl** [comment]
`zig fmt` only upgrades code from one release to the next; maintaining infinite backwards compatiblity would be very impractical given how much zig changes over time :)

**Comment by Arnau478** [comment]
Oh okay... So every development cycle starts a "new" `zig fmt`, right? Didn't know that, sorry. Closing this issue then.
