### ISSUE TITLE
streamUntilDelimiter should take an ?u8 as its delimiter

### ISSUE THREAD

**Issue by cactusbento** [ziglang/zig#16941]
As it currently stands, [`std.io.Reader.streamUntilDelimiter`](https://github.com/ziglang/zig/blob/6780a6bbfa7bbd44036de3b1338011d1e5bb43f3/lib/std/io/reader.zig#L208-L224) takes an `u8` as a delimiter. This limits its usability when reading input streams that utilizes the full range of possible `u8` values (0..255).

This prevents the user of `streamUntilDelimiter` from reading streams of unknown length, stopping reads prematurely (think reading a binary file). The programmer must instead re-implement most of `streamUntilDelimiter` like so:

```zig
while (true) {
    const byte = source.reader().readByte() catch |err| switch (err) {
        error. EndOfStream => break,
        else => |e| return e,
    };
    try destination.writer().writeByte(byte);
}
```
`streamUntilDelimiter` should instead should allow parameter `delimiter` to be null, so that it will continuously read until it throws `error.EndOfStream`. This will change the above code to:

```zig
source.reader().streamUntilDelimiter(desitnation.writer(), null, null) catch |err| switch (err) {
    error.EndOfStream => {},
    else => |e| return e, 
};
```
Reaching `error.EndOfStream` may be intentional in some programs, so letting the programmer handle what to do should be best.

There is some prior discussion at [ziggit.dev](https://ziggit.dev/t/a-less-limited-streamuntildelimiter/1523/4).

Note: This is useful when downloading things from the internet (files and web pages) using `std.http` since common web pages don't return "content-length" on random GET requests (Some return a "content-length" that does not cover the whole page).

**Comment by mlugg** [comment]
You can achieve this more efficiently using a `std.LinearFifo`:
```zig
var fifo = std.LinearFifo(u8, .{ .Static = 4096 }).init();
try fifo.pump(source.reader(), destination.writer());
```
This reads and writes bytes in 4k chunks, which is more efficient than working byte-by-byte so is better when you don't need to check for a delimiter.

**Comment by cactusbento** [comment]
That actually did slip from my mind during this whole process. 

Since this is the case, instead of changing code, the documentation of `streamUntilDelimiter` could point to `std.fifo.LinearFifo` as a potential alternative. In fact, some parts of the standard library could use documentation like this.

Thanks @mlugg. I'll think about this more.
