### ISSUE TITLE
Build test runner: Tests failures due to log errors are ignored

### ISSUE THREAD

**Issue by erikarvstedt** [ziglang/zig#16954]
### Zig Version

0.12.0 (rev dd6a9ca)

### Steps to Reproduce and Observed Behavior

Consider test file `test.zig`:
```zig
const std = @import("std");

test {
    std.log.err("foo", .{});
}
```

`zig test test.zig` correctly fails with exit code 1. Output:
```
Test [1/1] test_0... [default] (err): foo
All 1 tests passed.
1 errors were logged.
```

When running the same test via the build system (`b.addTest`), the log error is ignored and the build succeeds with exit code 0:
```
$ zig build test --summary all
run test: error: [default] (err): foo
Build Summary: 1/1 steps succeeded; 1/1 tests passed
```

### Expected Behavior

`zig build test` should fail like `zig test`.

**Comment by nektro** [comment]
duplicate https://github.com/ziglang/zig/issues/15091

**Comment by jacobly0** [comment]
This is not a bug.  The `addTest` step only compiles a test executable, you need to use `addRunArtifact` to create a step that run the test executable.  See `zig init-exe` for an example.

**Comment by leecannon** [comment]
@jacobly0 this issue can be replicated using the build.zig created by `init-exe`

```
$ zig version
0.12.0-dev.167+dd6a9caea

$ zig init-exe
info: Created build.zig
info: Created src/main.zig
info: Next, try `zig build --help` or `zig build run`

$ modfiy src/main.zig to match

$ zig build test --summary all
run test: error: [default] (err): foo
Build Summary: 3/3 steps succeeded; 1/1 tests passed
test success
└─ run test 1 passed 869us MaxRSS:1M
   └─ zig test Debug native success 1s MaxRSS:183M

$ echo $?
0

$ zig test src/main.zig
Test [1/1] test_0... [default] (err): foo
All 1 tests passed.
1 errors were logged.
error: the following test command failed with exit code 1:
/home/lee/src/fff/zig-cache/o/1c5f40c18807d64bdc89a6ae0ce9d4d3/test

$ echo $?
1
```
