### ISSUE TITLE
ArrayList performance issues.

### ISSUE THREAD

**Issue by Rexicon226** [ziglang/zig#16982]
### Zig Version

0.12.0-dev.167+dd6a9caea

### Steps to Reproduce and Observed Behavior

Pretty simple to reproduce I think, something like this:

```cpp
test "AppendList test" {
    std.debug.print("\n", .{}); // https://github.com/ziglang/zig/pull/16716

    // Start debug timer.
    var timer = try std.time.Timer.start();
    var timerResult: u64 = 0;

    // Issues arrise when using ArrayList millions of times.
    const iters = 1000000;
    for (0..iters) |_| {
        var list = std.ArrayList(u8).init(std.testing.allocator);
        defer list.deinit();

        // Attempt to append a couple times.
        const appendCount = 1;
        for (0..appendCount) |_| {
            try list.append(0);
        }

        timerResult += timer.lap();
    }

    std.debug.print("Average Loop Time: {}ns\n", .{timerResult / iters});
}

test "Basic List test" {
    std.debug.print("\n", .{});

    var timer = try std.time.Timer.start();
    var timerResult: u64 = 0;

    // Issues arrise when using ArrayList millions of times.
    const iters = 1000000;
    for (0..iters) |_| {
        var list: [64]u8 = undefined;

        // Attempt to append a couple times.
        const appendCount = 1;
        for (0..appendCount) |i| {
            list[i] = 0;
        }

        timerResult += timer.lap();
    }

    std.debug.print("Average Loop Time: {}ns\n", .{timerResult / iters});
}
```
Result:
```
Test [1/2] test.AppendList test...
Average Loop Time: 38882ns
Test [2/2] test.Basic List test...
Average Loop Time: 83ns
```

### Expected Behavior

While of course in testing mode, this will run slower, further testing in `ReleaseFast` shows that it gets down to about 3000ns for the AppendList. While obviously the AppendList is slower than pure arrays, I don't believe it should be it should be on these orders of magnitude. I feel like there might be something wrong with the code itself. Unfortunately I don't understand the system enough to try to fix it.

**Comment by nektro** [comment]
this is likely due to `ArrayList` as a structure having two properties being 1) that its data is stored on the heap and 2) that its data is stored contiguously in memory. the resize function is already using `@memcpy` and OP states this only is noticeable with millions of items so its likely `@memcpy` performance at that scale which may have room for improvement or be hitting a scalar limit

relevant code: https://github.com/ziglang/zig/blob/master/lib/std/array_list.zig#L891-L914

https://github.com/rdunnington/zig-stable-array might be of interest to you as well

**Comment by Rexicon226** [comment]
Thanks for the suggestion, I just tried it out. Unfortunately, it's the same speed as ArrayList in my application. I think you're idea about @memcpy being the issue is likely right.

**Comment by andrewrk** [comment]
Do you realize that you are measuring the performance of `std.testing.allocator`?

**Comment by squeek502** [comment]
This is not a flaw of ArrayList, you're just comparing wildly different things.

The Basic List test uses a single, shared stack-allocated buffer for all iterations.

The AppendList test re-allocates a new slice on the heap for every iteration of the loop. That means that it's doing `1000000` separate heap allocations. Note that resize that @nektro mentioned doesn't enter into it because the test cases only ever append one time; if multiple appends were done in the tests then the results would be even more lopsided because you'd just be multiplying the number of heap allocations being done in the ArrayList version.

Here are some fairer benchmarks:

Stack-allocated buffer vs a shared `ArrayList` outside the loop, `clearRetainingCapacity` in the loop, `appendAssumeCapacity` used instead of `append`
```
const std = @import("std");

test "AppendList test" {
    std.debug.print("\n", .{}); // https://github.com/ziglang/zig/pull/16716

    // Start debug timer.
    var timer = try std.time.Timer.start();
    var timerResult: u64 = 0;

    var list = try std.ArrayList(u8).initCapacity(std.testing.allocator, 64);
    defer list.deinit();

    // Issues arrise when using ArrayList millions of times.
    const iters = 1000000;
    for (0..iters) |_| {
        list.clearRetainingCapacity();

        // Attempt to append a couple times.
        const appendCount = 1;
        for (0..appendCount) |_| {
            list.appendAssumeCapacity(0);
        }

        timerResult += timer.lap();
    }

    std.debug.print("Average Loop Time: {}ns\n", .{timerResult / iters});
}

test "Basic List test" {
    std.debug.print("\n", .{});

    var timer = try std.time.Timer.start();
    var timerResult: u64 = 0;

    // Issues arrise when using ArrayList millions of times.
    const iters = 1000000;
    for (0..iters) |_| {
        var list: [64]u8 = undefined;

        // Attempt to append a couple times.
        const appendCount = 1;
        for (0..appendCount) |i| {
            list[i] = 0;
        }

        timerResult += timer.lap();
    }

    std.debug.print("Average Loop Time: {}ns\n", .{timerResult / iters});
}
```

```
> zig test 16982_vs_array.zig
Test [1/2] test.AppendList test...
Average Loop Time: 51ns
Test [2/2] test.Basic List test...
Average Loop Time: 51ns
All 2 tests passed.

> zig test 16982_vs_array.zig -OReleaseFast
Test [1/2] test.AppendList test...
Average Loop Time: 22ns
Test [2/2] test.Basic List test...
Average Loop Time: 22ns
All 2 tests passed.
```

Heap allocated buffer every loop iteration vs ArrayList re-allocated every loop iteration:

```zig
const std = @import("std");

test "AppendList test" {
    std.debug.print("\n", .{}); // https://github.com/ziglang/zig/pull/16716

    // Start debug timer.
    var timer = try std.time.Timer.start();
    var timerResult: u64 = 0;

    // Issues arrise when using ArrayList millions of times.
    const iters = 1000000;
    for (0..iters) |_| {
        var list = try std.ArrayList(u8).initCapacity(std.testing.allocator, 64);
        defer list.deinit();

        // Attempt to append a couple times.
        const appendCount = 1;
        for (0..appendCount) |_| {
            list.appendAssumeCapacity(0);
        }

        timerResult += timer.lap();
    }

    std.debug.print("Average Loop Time: {}ns\n", .{timerResult / iters});
}

test "Basic List test" {
    std.debug.print("\n", .{});

    var timer = try std.time.Timer.start();
    var timerResult: u64 = 0;

    // Issues arrise when using ArrayList millions of times.
    const iters = 1000000;
    for (0..iters) |_| {
        var list = try std.testing.allocator.alloc(u8, 64);
        defer std.testing.allocator.free(list);

        // Attempt to append a couple times.
        const appendCount = 1;
        for (0..appendCount) |i| {
            list[i] = 0;
        }

        timerResult += timer.lap();
    }

    std.debug.print("Average Loop Time: {}ns\n", .{timerResult / iters});
}
```

```
> zig test 16982_vs_heap.zig
Test [1/2] test.AppendList test...
Average Loop Time: 14587ns
Test [2/2] test.Basic List test...
Average Loop Time: 14220ns
All 2 tests passed.

> zig test 16982_vs_heap.zig -OReleaseFast
Test [1/2] test.AppendList test...
Average Loop Time: 6244ns
Test [2/2] test.Basic List test...
Average Loop Time: 6176ns
All 2 tests passed.
```

**Comment by Rexicon226** [comment]
As I stated before, I just quickly made these tests to demonstrate. My issues were when using the GPA and compiling in ReleaseFast. I **know** that ArrayList will be slower, I just feel like it might be too slow. These are extremely specific circumstances.

**Comment by squeek502** [comment]
If the issue is the performance of `GeneralPurposeAllocator` in ReleaseFast mode , then the relevant issue would be https://github.com/ziglang/zig/issues/12484

That is unrelated to `ArrayList`, though.
