### ISSUE TITLE
build.zig.zon: address URL/hash mismatch footgun

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#16998]
The `build.zig.zon` file currently has a footgun that occurs when a dependency's URL is updated without updating the associated hash.  This will cause Zig to use the previous URL contents rather than the new one, but only on machines that have already downloaded the previous URL.  This will cause the user who updated the URL to erroneously build with the old contents.  This change will even make it through a CI that maintains a persistent global zig cache across runs.

This being said, Zig gains a benefit by trusting the hash in `build.zig.zon` is correct, namely, it enables it to verify dependencies without needing to access the network and/or recalculate a hash it's already done.  Luckily there's a solution that allows us to keep this benefit while also removing the footgun.  Namely, zig can maintain a store of verified URL/hash pairings it's calculated.  If a user updates the url in their `build.zig.zon` file and forgets to update the hash, zig will see this as a new URL/hash pairing that it hasn't "verified" yet.  Zig will proceed to calculate the hash (download the URL if it hasn't been done yet) and see that it doesn't match and report the error to the user. This allows us to maintain the benefit of "trusted hashes", but, zig doesn't trust any hash until after it's been verified locally.  Getting into a state where the trusted hashes are invalid now requires a user to muck with zig's internal "trusted URL/hash pairing store" rather than just making a mistake in updating their `build.zig.zon` file.

**Comment by rohlem** [comment]
related to (I think would solve) https://github.com/ziglang/zig/issues/16679

**Comment by andrewrk** [comment]
Duplicate of #16679
