### ISSUE TITLE
Outdated documentation: std only supports x86_64?

### ISSUE THREAD

**Issue by iacore** [ziglang/zig#17032]
### Zig Version

N/A

### Steps to Reproduce and Observed Behavior

https://ziglang.org/documentation/master/
At the end of 48.

![image](https://github.com/ziglang/zig/assets/74560659/f039300b-679b-494c-b068-2a3109eb26f7)

It reads

> The current list of targets supported by the Zig Standard Library is:
> -    Linux x86_64
> -    Windows x86_64
> -    macOS x86_64

### Expected Behavior

i don't know what to put there instead

**Comment by nektro** [comment]
I'd personally opt to remove that paragraph but if we keep it, it should link to https://ziglang.org/download/0.11.0/release-notes.html#Support-Table
