### ISSUE TITLE
Interaction between comptime var and runtime struct creation

### ISSUE THREAD

**Issue by justin-geopipe** [ziglang/zig#17063]
### Zig Version

0.11.0 (playground)

### Steps to Reproduce and Observed Behavior

This code runs without error:

```zig
pub fn main() !void {
    comptime var MyType: type = i32;
    const MyStruct = struct { v: MyType };

    //_ = MyStruct { .v = 5 }; // line A

    MyType = [2]f32;
    _ = MyStruct { .v = [2]f32 {1.4, 2.4} }; // line B
}
```

However, if you uncomment "line A", then "line B" errors. That is, the introduction of the _runtime_ code `_ = MyStruct { .v = 5 };` changes the _type_ of `MyStruct`.

### Expected Behavior

My guess as to what's going on is that this is an interaction between mutation (`comptime var`) and laziness. Mutation and laziness should never mix, so I'd expect either:

- Prevent the laziness: the above code (with line A still commented out) produces a type error on line B, because `MyStruct` contains an `i32` at the time it is defined.
- Prevent the mutation: the above code (with line A still commented out) produces an error saying that `comptime var` is not allowed in type definitions.

Related to https://github.com/ziglang/zig/issues/7396, though so far as I've seen this isn't exactly covered by any of the other issues it cites. For example, there are no closures involved.

**Comment by mlugg** [comment]
This design issue is solved on master. The value of `MyType` is resolved eagerly at the point of the struct declaration, so the same error occurs regardless of whether line A is commented.
