### ISSUE TITLE
cInclude-ing libarchive fails

### ISSUE THREAD

**Issue by theoparis** [ziglang/zig#17075]
### Zig Version

0.12.0-dev.278+0e8f130ae

### Steps to Reproduce and Observed Behavior

Import libarchive and the archive_entry.h header with cImport and use the following on a archive entry:

```
        libarchive.archive_entry_set_filetype(e, libarchive.AE_IFREG);
```

## Observed behavior:

```
/root/dev/package-server/zig-cache/o/7ffbf272199db074436a5d93983acd93/cimport.zig:1541:22: error: unable to translate C expr: expected ')' instead got 'IntegerLiteral'
pub const AE_IFREG = @compileError("unable to translate C expr: expected ')' instead got 'IntegerLiteral'"); // /usr/include/archive_entry.h:187:9
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    handleRequest: src/main.zig:59:60
    main: src/main.zig:20:39
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

It seems that the following code is causing the issue:
```c
/* Get a suitable definition for mode_t */
#if ARCHIVE_VERSION_NUMBER >= 3999000
/* Switch to plain 'int' for libarchive 4.0.  It's less broken than 'mode
_t' */
# define        __LA_MODE_T     int
#elif defined(_WIN32) && !defined(__CYGWIN__) && !defined(__BORLANDC__) && !defined(__WATCOMC__)
# define        __LA_MODE_T     unsigned short
#else
# define        __LA_MODE_T     mode_t
#endif

// ...

#define AE_IFREG        ((__LA_MODE_T)0100000)
```

### Expected Behavior

translate c expr should not fail

EDIT: the following diff on the archive_entry.h seems to fix it temporarily.
```diff
-#define AE_IFREG        ((__LA_MODE_T)0100000)
+#define AE_IFREG        ((int)0100000)
```

**Comment by TiranexDev** [comment]
I can confirm this is actually true, and it's impacting me because I have to use libarchive in my project ([zigd](https://github.com/TiranexDev/zigd))

But it's not just libarchive, if I check cimport.zig I can see this ([Link to file](https://hastebin.skyra.pw/pagiyisike.kotlin)):
![image](https://github.com/ziglang/zig/assets/94789999/7134136a-65a4-448c-bf79-c1a6a660b57f)

**Comment by TiranexDev** [comment]
Related?

https://github.com/ziglang/zig/issues/13968 (Especially https://github.com/ziglang/zig/issues/13968#issuecomment-1668347660)
https://github.com/ziglang/zig/issues/10136
