### ISSUE TITLE
parameter expressions should be generated with comptime at the callsite when the params are declared comptime

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1708]
```zig
export fn entry() void {
    foo(fortyTwo());
}

fn fortyTwo() i32 {
    return 42;
}

fn foo(comptime x: i32) void { }
```

```
[nix-shell:~/downloads/zig/build]$ ./zig build-obj test.zig 
/home/andy/downloads/zig/build/test.zig:2:17: error: unable to evaluate constant expression
    foo(fortyTwo());
                ^
```

If you put `comptime` at the callsite, it works:

```zig
export fn entry() void {
    foo(comptime fortyTwo());
}
```

But this is redundant. It's already declared `comptime` in the parameter. We should generate the expression with implied `comptime` at the callsite.

**Comment by andrewrk** [comment]
This should be pretty straightforward to implement - you can follow the example set by the array length, which already does this. The implementation has to do with introducing a new "comptime scope" and then using that new scope in the sub-expression.

**Comment by arBmind** [comment]
For me this seems to be a bit more tricky than described by @andrewrk.
Array length on type expressions have a special parser state. So we can easily deduce that comptime scope is required to late evaluate at comptime.
For function calls that is not possible. In astgen we lack the concrete argument types of the actual invoked function.
Or at least I found no way to check if an argument has the comptime flag.

**Comment by nektro** [comment]
it likely wouldnt be implemented in AstGen
