### ISSUE TITLE
Using Zig-Tracy from zon file

### ISSUE THREAD

**Issue by voroskoi** [ziglang/zig#17099]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

I have asked this question on ziggit.dev, but nobody was able to answer it in three weeks, so I think there is a bug somewhere here.

Here is a minimal zig project with Zig-Tracy dependency in the [build.zig.zon](https://git.sr.ht/~voroskoi/tracy-wtf/tree/master/item/build.zig.zon) and [build.zig](https://git.sr.ht/~voroskoi/tracy-wtf/tree/master/item/build.zig) files.

The Zig-Tracy build.zig file is [this](https://github.com/voroskoi/Zig-Tracy/blob/main/build.zig).

I have no issue using Zig-Tracy as a git submodule, but building this executable with `zig build run -Dtracy_enabled` gives the following result:
```
false
true true
true
```

My issues:
- If I do not comment out line 29-33 in main.zig it gives a compile error even when both value is true.
- I have copy-pasted the enabled expression from Zig-Tracy ([here](https://github.com/voroskoi/Zig-Tracy/blob/bc8488f09e24ab2fe51a3c4560abdfab2ff3eb5f/tracy.zig#L6-L30)), but it gives me different results.
- I have no idea how to make tracy.enabled true.

What am i doing wrong here?

### Expected Behavior

I would like to use Zig-Tracy imported from zon file.

**Comment by Vexu** [comment]
> What am i doing wrong here?

`@hasDecl` returns false for non-`pub` decls, to make `tracy` see your `tracy_enabled` you need to make it `pub`.

**Comment by voroskoi** [comment]
Hi,

Thanks for Your answer, this helps, but still does not work:
After making `tracy_enabled` `pub` zig build complains because `options.zig` exists in multiple modules.

tracy-wtf's `build.zig` have these lines:
```zig
const tracy_option = b.option(bool, "tracy_enabled", "Enable tracy profiler") orelse false;
const options = b.addOptions();
options.addOption(bool, "tracy_enabled", tracy_option);
exe.addModule("build_options", options.createModule());
```

This is probably wrong, because it recreates options with b.addOptions() and I would like to set Zig-Tracy's build_options somehow, but I can not figure out that part.
Now it fails on [this](https://github.com/voroskoi/Zig-Tracy/blob/bc8488f09e24ab2fe51a3c4560abdfab2ff3eb5f/tracy.zig#L25) line.

How can I send `-Dtracy_enabled` to Zig-Tracy? And how can I make Zig-Tracy's `build_options` module available in my root package?

**Comment by Vexu** [comment]
> How can I send `-Dtracy_enabled` to Zig-Tracy?

I'm don't think that's possible yet.

> And how can I make Zig-Tracy's `build_options` module available in my root package?

How do I reproduce this?

**Comment by voroskoi** [comment]
1. git clone https://git.sr.ht/~voroskoi/tracy-wtf
2. zig build run (zig version: 0.11.0)

```
voroskoi ~/code/tracy-wtf  master via ↯ v0.11.0 ❯ zig build run
zig build-exe tracy-wtf Debug native: error: the following command failed with 1 compilation errors:
/home/voroskoi/.zig-linux-aarch64-0.11.0/zig build-exe /home/voroskoi/code/tracy-wtf/src/main.zig --cache-dir /home/voroskoi/code/tracy-wtf/zig-cache --global-cache-dir /home/voroskoi/.cache/zig --name tracy-wtf --mod build_options::/home/voroskoi/code/tracy-wtf/zig-cache/c/4e61b46f3a0b9f4a76bc9cb6c8d455ea/options.zig --mod tracy:build_options:/home/voroskoi/.cache/zig/p/12205324ed1a6462cad92655e8c33aecdc5aa1677fa26e97c28ac7ba63f7a16250d1/tracy.zig --deps tracy --listen=-
Build Summary: 1/6 steps succeeded; 1 failed (disable with --summary none)
run transitive failure
mq run tracy-wtf transitive failure
   tq zig build-exe tracy-wtf Debug native 1 errors
   mq install transitive failure
      mq install tracy-wtf transitive failure
         mq zig build-exe tracy-wtf Debug native (+1 more reused dependencies)
/home/voroskoi/.cache/zig/p/12205324ed1a6462cad92655e8c33aecdc5aa1677fa26e97c28ac7ba63f7a16250d1/tracy.zig:25:13: error: root.tracy_enabled disagrees with build_options.tracy_enabled! Please remove one or make them match.
            @compileError("root.tracy_enabled disagrees with build_options.tracy_enabled! Please remove one or make them match.");
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    usingnamespace_0: /home/voroskoi/.cache/zig/p/12205324ed1a6462cad92655e8c33aecdc5aa1677fa26e97c28ac7ba63f7a16250d1/tracy.zig:34:24
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

**Comment by Vexu** [comment]
I'm not entirely sure but it seems like that stems from not being able to pass options to dependencies.
