### ISSUE TITLE
zig @cImport crash when include a C header with  BUILD_ASSERT macro definition

### ISSUE THREAD

**Issue by xnhp0320** [ziglang/zig#17098]
### Zig Version

0.12.0-dev.293+f33bb0228

### Steps to Reproduce and Observed Behavior

the header file:
```C
 #include <stdint.h>
 #include <limits.h>

 #ifdef __CHECKER__
 #define BUILD_ASSERT(EXPR) ((void) 0)
 #define BUILD_ASSERT_DECL(EXPR) extern int (*build_assert(void))[1]
 #elif defined(__cplusplus) && __cplusplus >= 201103L
 #define BUILD_ASSERT(EXPR) static_assert(EXPR, "assertion failed")
 #define BUILD_ASSERT_DECL(EXPR) static_assert(EXPR, "assertion failed")
 #elif defined(__cplusplus) && __cplusplus < 201103L
 #include <boost/static_assert.hpp>
 #define BUILD_ASSERT BOOST_STATIC_ASSERT
 #define BUILD_ASSERT_DECL BOOST_STATIC_ASSERT
 #elif (__GNUC__ * 256 + __GNUC_MINOR__ >= 0x403 \
        || __has_extension(c_static_assert))
 #define BUILD_ASSERT_DECL(EXPR) _Static_assert(EXPR, #EXPR)
 #define BUILD_ASSERT(EXPR) (void) ({ _Static_assert(EXPR, #EXPR); })
 #else
 #define BUILD_ASSERT__(EXPR) \
         sizeof(struct { unsigned int build_assert_failed : (EXPR) ? 1 : -1; })
 #define BUILD_ASSERT(EXPR) (void) BUILD_ASSERT__(EXPR)
 #define BUILD_ASSERT_DECL(EXPR) \
         extern int (*build_assert(void))[BUILD_ASSERT__(EXPR)]
 #endif



 static inline void somefunc(void) {
     BUILD_ASSERT(ULONG_MAX <= UINT64_MAX);
 }
 ```

It seems zig chooses the definition of BUILD_ASSERT:

```C
 #define BUILD_ASSERT_DECL(EXPR) _Static_assert(EXPR, #EXPR)
 #define BUILD_ASSERT(EXPR) (void) ({ _Static_assert(EXPR, #EXPR); })
```
and crashes.

the zig code:
```zig
const c = @cImport({
      @cInclude("a.h");
});

pub fn main() void {
      _ = c;
}
```

zig build-exe -I. -lc main.zig
Segmentation fault (core dumped)

my gcc version is:
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### Expected Behavior

it compiles.

**Comment by Vexu** [comment]
Reduction:
```zig
void somefunc(void) {
    (void)({
        _Static_assert(1);
    });
}
```

**Comment by xnhp0320** [comment]
The backtrace:

thread 13679677 panic: reached unreachable code
/Users/penghe/src/zig/src/translate_c/ast.zig:875:25: 0x1100bb8cf in renderNode (zig)
        .declaration => unreachable,
                        ^
/Users/penghe/src/zig/src/translate_c/ast.zig:1010:42: 0x1100bdd72 in renderNode (zig)
                    .rhs = try renderNode(c, payload.val),
                                         ^
/Users/penghe/src/zig/src/translate_c/ast.zig:1596:43: 0x1100c6e9e in renderNode (zig)
                const res = try renderNode(c, stmt);
                                          ^
/Users/penghe/src/zig/src/translate_c/ast.zig:1642:46: 0x1100c7836 in renderNode (zig)
                        .rhs = try renderNode(c, payload.value),
                                             ^
/Users/penghe/src/zig/src/translate_c/ast.zig:1596:43: 0x1100c6e9e in renderNode (zig)
                const res = try renderNode(c, stmt);
                                          ^
/Users/penghe/src/zig/src/translate_c/ast.zig:2842:32: 0x11031c293 in renderFunc (zig)
    const body = try renderNode(c, payload_body);
                               ^
/Users/penghe/src/zig/src/translate_c/ast.zig:1614:35: 0x1100c7381 in renderNode (zig)
        .func => return renderFunc(c, node),
                                  ^
/Users/penghe/src/zig/src/translate_c/ast.zig:774:39: 0x1100bad8d in render (zig)
            const res = try renderNode(&ctx, node);
                                      ^
/Users/penghe/src/zig/src/translate_c.zig:188:22: 0x1100ff3e5 in translate (zig)
    return ast.render(gpa, context.global_scope.nodes.items);
                     ^
/Users/penghe/src/zig/src/main.zig:4284:50: 0x1101061b8 in cmdTranslateC (zig)
                break :tree translate_c.translate(
                                                 ^
/Users/penghe/src/zig/src/main.zig:3593:29: 0x1101ad05e in buildOutputType (zig)
        return cmdTranslateC(comp, arena, null);
                            ^
/Users/penghe/src/zig/src/main.zig:301:31: 0x10ffd33fa in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .translate_c);
                              ^
/Users/penghe/src/zig/src/main.zig:212:20: 0x10ffcff77 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/Users/penghe/src/zig/lib/std/start.zig:486:37: 0x10ffcfb90 in main (zig)
    std.os.argv = @as([*][*:0]u8, @ptrCast(c_argv))[0..@as(usize, @intCast(c_argc))];
                                    ^
???:?:?: 0x7ff80157641e in ??? (???)
Unwind information for `???:0x7ff80157641e` was not available, trace may be incomplete

???:?:?: 0x0 in ??? (???)
[1]    94112 abort      ../zig/build/stage3/bin/zig translate-c crash.c

**Comment by xnhp0320** [comment]
It's interesting that if the statement expression has two statements, zig will not panic:

like:

```zig
   void somefunc(void) {
       int y;
 >>    (void)({y=1;_Static_assert(1);});
   }
```

or:

```zig
   void somefunc(void) {
       int y;
 >>    (void)({_Static_assert(1);y = 1;});
   }

```

**Comment by Vexu** [comment]
It looks correct, opening a PR and adding a test will show if it works.
