### ISSUE TITLE
Compiler produces a segfaulting binary when `assert`ing in a `for` loop

### ISSUE THREAD

**Issue by cheeze42** [ziglang/zig#17096]
### Zig Version

0.12.0-dev.278+0e8f130ae

### Steps to Reproduce and Observed Behavior

Compile and run the following snippet with a stock `build.zig` and with `Doptimize=ReleaseFast`:
```zig
const std = @import("std");

pub fn main() !void {
    var foo: std.meta.Tuple(&[_]type{[1]f64}) = undefined;
    for (0..1) |idx| {
        std.debug.assert(!std.math.isNan(foo[0][idx]));
    }
}
```
The resulting binary, when run, segfaults:
```
cheeze42@pop-os:~/Documents/testing$ zig build -Doptimize=ReleaseFast run
run testing: error: the following command terminated unexpectedly:
/home/cheeze42/Documents/testing/zig-out/bin/testing 
Build Summary: 3/5 steps succeeded; 1 failed (disable with --summary none)
run transitive failure
└─ run testing failure
error: the following build command failed with exit code 1:
/home/cheeze42/Documents/testing/zig-cache/o/61ec19e5697d0131e4997bb9a2ad05d8/build /opt/zig/zig /home/cheeze42/Documents/testing /home/cheeze42/Documents/testing/zig-cache /home/cheeze42/.cache/zig -Doptimize=ReleaseFast run
```

### Expected Behavior

Since the given code isn't actually doing anything, the compiler should just emit a no-op binary.

**Comment by squeek502** [comment]
What do you mean "isn't doing anything"? If you're expecting the code within the `assert` to be omitted in release modes, that's not how `std.debug.assert` works: https://github.com/ziglang/zig/issues/10942

You also might want to double check that you actually want to use `undefined` here, since that's very likely what's causing the segfault: https://ziglang.org/documentation/master/#undefined

**Comment by cheeze42** [comment]
Got. The original bug that caused this was indeed a problem of `undefined` leaking into an `assert` statement.

I still see two issues/bugs with this:
1. The commented documentation on `std.debug.assert` might be wrong: `In ReleaseFast and ReleaseSmall modes, calls to this function are optimized away` isn't true, at least with a reasonable interpretation of "optimizing calls away".
2. This isn't caught in Debug, but that's the point of #211.

But the issue itself is resolved, so I'll close the thread.
