### ISSUE TITLE
zig build fails with "fatal error: 'pthread.h' file not found"

### ISSUE THREAD

**Issue by DaQueenJodi** [ziglang/zig#17100]
### Zig Version

0.12.0-dev.244+f4c9e19bc

### Steps to Reproduce and Observed Behavior

Here's a GitHub repo I made to reproduce the issue: https://github.com/daqueenJodi/troubleshooting-something
the issue seemingly has to do with me using NixOS, but what is weird to me is that `zig cc test.c` works  as expected; it finds pthreads and successfully compiles
but when I use `zig build` after adding test.c as a source file via `exe.addCSourceFile`, it fails with this message:
`zig build-exe template Debug native: error: error(compilation): clang failed with stderr: /hdd/Documents/Programming/Zig/template/test.c:1:10: fatal error: 'pthread.h' file not found`

### Expected Behavior

zig build should be able to find the pthread.h file and successfully compile test.c, just like zig cc does

**Comment by xdBronch** [comment]
you need to link libc for it to find the libc headers, add `.link_libc = true,` in your exe's init options or `exe.linkLibC();` afterwards

**Comment by DaQueenJodi** [comment]
thank you! that worked
I have no idea why I thought I could use a c library without libc

**Comment by xdBronch** [comment]
fwiw you can use C libraries/headers without libc so long as they dont include anything from libc
