### ISSUE TITLE
linksection works on macOS but not linux?

### ISSUE THREAD

**Issue by JCash** [ziglang/zig#17102]
### Zig Version

0.11

### Steps to Reproduce and Observed Behavior

I have my linksection test working on macOS, but when I test it on Ubuntu 20 (x86_64) (albeit in a Docker container), I couldn't get it to work.

I'm using linksection like so:

```
export const mod_init_func_ptr linksection("__DATA,__mod_init_func") = &PluginZIG;
```

Anyone knows what I'm doing wrong here?
Or is it a zig bug?

* Download project from: https://github.com/JCash/zig-plugin-test/tree/linux-linksection
* Build with `./compile_exe.sh`
* Run with `./zig-out/bin/testzig`

### Expected Behavior

I expected the linksection code to get called on linux platform.

_Update_ Expected output:

```
Registered plugin 'PluginCPP'
Registered plugin 'PluginZIG'
main.cpp: Entering
  Creating plugins:
    PluginZIG: PluginCreate PluginZIG
    PluginCPP: PluginCreate: PluginCPP 0x600002604010 0
  Updating plugins:
    PluginZIG: PluginUpdate 1
    PluginCPP: PluginUpdate: 0x600002604010 1
  Updating plugins:
    PluginZIG: PluginUpdate 2
    PluginCPP: PluginUpdate: 0x600002604010 2
  Destroying plugins:
    PluginZIG: PluginDestroy plugin.ZigPluginContext@600002604000
    PluginCPP: PluginDestroy: 0x600002604010 2
main.cpp: Exiting
```

**Comment by Vexu** [comment]
Can you try updating to Zig 0.12.0 first? The symbol seems to appear for me when compiling a reduced version of your zig code.

**Comment by JCash** [comment]
I've tested with 0.12 now, but it didn't improve the result.

**Comment by JCash** [comment]
Thanks @Vexu , but it's missing the PluginZIG output.
I've updated the OP with the expected output.

**Comment by Vexu** [comment]
It looks like you're trying to emulate `__attribute__((constructor))`, Linux uses `.data` instead of `__DATA` so you'll probably need to look more into how that attribute works on different targets.

**Comment by JCash** [comment]
Yeah, it makes sense I guess.
I wish we had an easier-to-use linksection, as now it feels very tricky to use.

**Comment by Vexu** [comment]
I'm not sure what you mean by that, the `linksection` is working exactly as supposed to.

**Comment by JCash** [comment]
I'm sure you're right.
What I meant is that I find it hard to work with given my use case which, to be honest, may not be fair to linksection.
My main goal is to have something work like a global constructor in C++.

I'm continuing exploring how to do this with on linux, but still no luck.
