### ISSUE TITLE
Langref: Floating point conversion methods outdated

### ISSUE THREAD

**Issue by anoushk1234** [ziglang/zig#17118]
The master branch of Zig now uses `@floatFromInt` and `@intFromFloat` instead of the previously used `@intToFloat` and `@floatToInt`. However the [docs on master branch](https://ziglang.org/documentation/master/#intFromFloat) still uses the outdated methods.

Here's an image of the same:
![image](https://github.com/ziglang/zig/assets/32778608/85e3be1a-c1a1-4fbe-9358-d005b7e94505)

**Comment by xdBronch** [comment]
ive read over this issue 15 times at this point and im feeling very confused. is this not just wrong? it says `intFromFloat` right there in the screenshot which is the new form

**Comment by anoushk1234** [comment]
> ive read over this issue 15 times at this point and im feeling very confused. is this not just wrong? it says `intFromFloat` right there in the screenshot which is the new form, what am i missing?

@xdBronch My sincere apologies, you are right, this was however not the case with zig learn which is still using the old methods and I misread the reference docs which led me to believe they were also using the wrong methods. I apologise again for taking up your time. Thank you for taking a look at this.
