### ISSUE TITLE
std.math: cbrt(-0) incorrectly returns +0 for f64

### ISSUE THREAD

**Issue by linusg** [ziglang/zig#17112]
### Zig Version

0.12.0-dev.297+d2014fe97

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() !void {
    // Sanity check to ensure formatting -0 works as expected
    std.debug.print("{d}\n", .{@as(f32, -0.0)});
    std.debug.print("{d}\n", .{@as(f64, -0.0)});

    // Demonstrate the bug
    std.debug.print("{d}\n", .{std.math.cbrt(@as(f32, -0.0))});
    std.debug.print("{d}\n", .{std.math.cbrt(@as(f64, -0.0))});
}
```

On a x86_64 Linux machine this outputs the following for me, regardless of the optimization mode:

```
-0
-0
-0
0
```

### Expected Behavior

The doc comment claims:

```zig
/// Returns the cube root of x.
///
/// Special Cases:
///  - cbrt(+-0)   = +-0
///  - cbrt(+-inf) = +-inf
///  - cbrt(nan)   = nan
pub fn cbrt(x: anytype) @TypeOf(x) { ... }
```

Therefore `cbrt(-0)` should return `-0` but only does so for the `f32` type.

---

Related issue: #17111

**Comment by linusg** [comment]
Like in #17111 this has broken tests:

https://github.com/ziglang/zig/blob/acc9471915d74fc2cb475ea3220a249d81e3036e/lib/std/math/cbrt.zig#L151

https://github.com/ziglang/zig/blob/acc9471915d74fc2cb475ea3220a249d81e3036e/lib/std/math/cbrt.zig#L159

**Comment by lsculv** [comment]
This should be a simple one line change:
https://github.com/ziglang/zig/blob/7827265ea81c72e44da9b7d9b91e68d557e4db6d/lib/std/math/cbrt.zig#L90C8-L93C10

Should go to:
```zig
// cbrt(0) is itself
if (hx == 0) {
    return x;
}
```

This is what the musl libc implementation does, which the zig std lib implementation is based on so I see no reason we shouldn't too.
