### ISSUE TITLE
`zig cc`: macOS: Extraneous `0` in dynamicaly linked library version

### ISSUE THREAD

**Issue by danielslee** [ziglang/zig#17122]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

Create a simple C program:
```shell
$ echo "int main() {}" > test.c
```

Compile it for macOS with `zig cc`.
```shell
$ zig cc --target=x86_64-macos.12.0 --sysroot=$macos_sdk -F/System/Library/Frameworks -framework CoreVideo test.c
```

Check the linked libraries with `otool`:
```
$ otool -L a.out
a.out:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.20.0, current version 1.50.0)
```

The CoreVideo versions are incorrect:
> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version **1.20.0**, current version **1.50.0**)

### Expected Behavior

I expect to see the versions that Apple's clang outputs.

compile with clang:
```shell
$ clang test.c -framework CoreVideo
````

run otool:
```shell
$ otool -L a.out
a.out:
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
```

The CoreVideo versions are correct:
> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version **1.2.0**, current version **1.5.0**)

----
### Workaround

I have discovered a workaround -- patching the version in the SDK as follows seems to fix the issue:
```shell
$ sed -i 's/current-version: 1\.5/current-version: 1.5.0/g' $macos_sdk/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo.tbd
$ sed -i 's/compatibility-version: 1\.2/compatibility-version: 1.2.0/g' $macos_sdk/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo.tbd
```
----
### Resulting Issues

This bug prevents the resulting binary from running on 10.13 (High Sierra):

```shell
$ ./a.out
dyld: Library not loaded: /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
  Referenced from: //./a.out
  Reason: Incompatible library version: a.out requires version 1.20.0 or later, but CoreVideo provides version 1.2.0
Abort trap: 6
```

macOS versions higher than that (10.14 Mojave and later) seem to somehow work around the wrong version and the resulting binary does run.

---
I'm not too familiar with the Zig codebase, so I may be totally wrong, but I suspect that this code line may have something to do with it:
https://github.com/ziglang/zig/blob/402468b2109929779fc0fb59eeb5481cfb5ed44d/src/link/MachO/Dylib.zig#L68

**Comment by kubkon** [comment]
I think this issue may be related to https://github.com/ziglang/zig/issues/16822
