### ISSUE TITLE
Incorrect location on array initialization error

### ISSUE THREAD

**Issue by acgaudette** [ziglang/zig#17127]
### Zig Version

0.12.0-dev.307+7827265ea

### Steps to Reproduce and Observed Behavior

(1) it appears that something changed in the compiler very recently, preventing tuples from coercing to structs that 'look like' tuples.

(2) it is possible that this behavior was never intended to begin with. in that case, the relevant error message seems incorrect.

the following code _compiled without errors_ in previous versions of the compiler:

```zig
const std = @import("std");                                                      
                                                                                 
fn function(param: struct { a: []const u8, b: []const u8 }) void                 
{                                                                                
        _ = param;                                                               
}                                                                                
                                                                                 
pub fn main() void                                                               
{                                                                                
        function(.{ "A", "B" });                                                 
}
```

this now results in the following error, which always points to line 1 column 1 in the file:

```
main.zig:1:1: error: type 'main.function__struct_3493' does not support array initialization syntax
const std = @import("std");
^~~~~
referenced by:
    callMain: /home/acg/zig/0.12.0-dev.307+7827265ea/files/lib/std/start.zig:564:17
    initEventLoopAndCallMain: /home/acg/zig/0.12.0-dev.307+7827265ea/files/lib/std/start.zig:508:34
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

### Expected Behavior

(1) tuples coerce to structs coercible to tuples [when passed as arguments] (regression)
(2) some error message that doesn't point to the first character in the file

**Comment by nektro** [comment]
the error message source location is definitely wrong but the compile error is not since `param` is not a tuple, it is an unnamed regular struct

it should say:
`main.zig:10:18: error: type 'main.function__struct_3493' does not support array initialization syntax`
`main.zig:3:20: note: type 'main.function__struct_3493' defined here`

**Comment by acgaudette** [comment]
that makes sense -- I was relying on this behavior implicitly to simplify initialization of various structs (some generated by translate-c) and have since updated my code.

I would be curious to learn if this was a prior regression or if this case was just never covered by the compiler.

**Comment by Vexu** [comment]
It used to be checked before the intern pool changes, in 0.10.0 it resulted in:
```
<source>:10:19: error: no field named '0' in struct 'example.function__struct_3376'
        function(.{ "A", "B" });                                                 
                 ~^~~~~~~~~~~~
<source>:3:20: note: struct declared here
fn function(param: struct { a: []const u8, b: []const u8 }) void                 
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    callMain: /opt/compiler-explorer/zig-0.10.0/lib/std/start.zig:596:17
    initEventLoopAndCallMain: /opt/compiler-explorer/zig-0.10.0/lib/std/start.zig:540:51
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```
and in 0.9.0 in:
```
./example.zig:10:21: error: array access of non-array type 'struct:3:20'
        function(.{ "A", "B" });                                                 
                    ^
```
This bug was also noticed in https://github.com/ziglang/zig/issues/16914#issuecomment-1711576525

**Comment by IntegratedQuantum** [comment]
The same wrong error location also appears when initializing global variables:
```zig
const std = @import("std");

const x: struct {a: u32} = .{0};

pub fn main() void {
	_ = x;
}
```
It does appear to work correctly for local variables.
