### ISSUE TITLE
-fsanitize=cfi crashes zig (and zig should provide a ignorelist)

### ISSUE THREAD

**Issue by theoparis** [ziglang/zig#17137]
### Zig Version

0.12.0-dev.297+d2014fe97

### Steps to Reproduce and Observed Behavior

Add of the following file to the parent directory of the zig binary at `./lib/clang/16/share/cfi_ignorelist.txt` and then use `-fsanitize=cfi -fvisibility=default -flto=thin` with a build.zig.

 ```
[cfi-unrelated-cast]
# The specification of std::get_temporary_buffer mandates a cast to
# uninitialized T* (libstdc++, MSVC stdlib).
fun:_ZSt20get_temporary_buffer*
fun:*get_temporary_buffer@.*@std@@*

# STL address-of magic (libstdc++).
fun:*__addressof*

# Windows C++ stdlib headers that contain bad unrelated casts.
src:*xmemory0
src:*xstddef

# std::_Sp_counted_ptr_inplace::_Sp_counted_ptr_inplace() (libstdc++).
# This ctor is used by std::make_shared and needs to cast to uninitialized T*
# in order to call std::allocator_traits<T>::construct.
fun:_ZNSt23_Sp_counted_ptr_inplace*
```

Unfortunately zig does not provide this file in the tarballs but clang does.

### Expected Behavior

Successful zig build with the CFI sanitizer.

**Comment by theoparis** [comment]
I just realized [fsanitize=address doesn't even work](#11403 ). That issue is more important than getting CFI to work...

**Comment by kassane** [comment]
Try add `-fno-sanitize-ignorelist`!

## Another issue related on LLVM-CFI

Based on: https://bughunters.google.com/blog/4805571163848704/llvm-cfi-and-cross-language-llvm-cfi-support-for-rust

```bash
$> zig cc -c -Wall -flto -fsanitize=cfi -fsanitize-cfi-icall-experimental-normalize-integers -fno-sanitize-ignorelist -fvisibility=hidden libfoo.c -emit-llvm -o libfoo.bc
$> zig ar rcs libfoo.a libfoo.bc
```

Get same error:
```bash
$> zig cc -o zig_cfi main.zig -flto -fsanitize=cfi -fsanitize-cfi-icall-experimental-normalize-integers -fno-sanitize-ignorelist libfoo.a
# or
$> zig run -lc main.zig libfoo.a -flto

error: ld.lld: inconsistent LTO Unit splitting (recompile with -fsplit-lto-unit)
```

No have `split-lto-unit` on zig `build-{obj|exe|lib}`:
```bash
 zig build-exe --help | grep lto
  -flto                     Force-enable Link Time Optimization (requires LLVM extensions)
  -fno-lto                  Force-disable Link Time Optimization
 ```
