### ISSUE TITLE
JSON Parser fails to parse objects in arrays

### ISSUE THREAD

**Issue by StephenStrickland** [ziglang/zig#1715]
### Description
JSON Parser fails to parse an object nested within an array.

Zig Version: 0.3.0
OS: macOS 10.12.6

#### Code
```kotlin
// modified version of std.json test "json parser dynamic"
// init Parser
var p = Parser.init(debug.global_allocator, false);
defer p.deinit();

// json to parse
const s =
   \\{
   \\  "ArrayStuff": [1234, "stuff", { "something": "else"}, 98765]
   \\}
;  // tried both inline strings and reading from .json file

// parse
var tree = try p.parse(s);
defer tree.deinit();

tree.root.dump();
```
#### Expected
```json
{
    "ArrayStuff": [
        1234,
        "stuff",
        {
            "something": "else"
        },
        98765
    ]
}
```
#### Actual
```json
{
    "ArrayStuff": [
        1234,
        "stuff",
        98765
    ]
}
```
It appears that the Parser is successfully parsing the nested object structure. But something is failing during `pushToParent()`. I haven't gotten `gdb` to work yet, but from debug statements it appears that `pushToParent()` appends to `array` but the appended object is not reflected in `p.stack`. Not too familiar with the syntax for Zig, might be a reference/value issue, syntax issue with how `array` is referenced, or maybe the underlying IR is incorrect. I need someone a bit more familiar with the Zig to take a look.

**Comment by andrewrk** [comment]
Thanks for the nice test case.

**Comment by StephenStrickland** [comment]
After further investigation it appears to be an issue with the switch statement. I think the captured pointer is referencing a copy or by value and not actually referencing the switched value.
```rust
pub const Test = struct {
    
    list: ArrayList(Value),

    pub fn init() Test {
        return Test { .list = ArrayList(Value).init(debug.global_allocator)};
    }
};

fn testSwitchCapturePtrEnum(enumPtr: *Test, valueToSet: *const Value) void {
    // grab the last Value on the list
    switch(enumPtr.list.at(0)) {
        // match on Array and capture pointer
        Value.Array => |*array| {
            // append to the captured pointer
            array.*.append(valueToSet.*) catch unreachable;
            // iterate and dump to view entire list
            var it  =  array.iterator();
            debug.warn("\ndumping array after set");
            while (it.next()) |next| {
                debug.warn("\n--value--\n");
                next.dump();
                debug.warn("\n--value--\n");
            }
            debug.warn("\nfinished\n");
        },
        else => unreachable,
    }
    // match and iterate over Array again
    switch(enumPtr.list.at(0)) {
        Value.Array => |array| {
            var it  =  array.iterator();
            debug.warn("\ndumping list");
            while (it.next()) |next| {
                debug.warn("\n--value--\n");
                next.dump();
                debug.warn("\n--value--\n");
            }
            debug.warn("\nfinished\n");
        },
        else => unreachable,
    }
}
```

#### Expected Output
```
dumping array after set
--value--
123
--value--

finished

dumping list
--value--
123
--value--

finished
```
 #### Actual Output
```
dumping array after set
--value--
123
--value--

finished

dumping list
finished
```

**Comment by andrewrk** [comment]
If this is the problem then, two things:
* This will be fixed by the copy elision PR that is still work in progress
* As a workaround, you can put a * in front of the switch var to get a reference.

**Comment by StephenStrickland** [comment]
@andrewrk for the second option can you give me an example? Unless you mean something different than `Value.Array => |*array| {}` that's the problem. I'm matching on the type that using `|*switch_var|`, but it doesn't work when the `switch_var` is an `ArrayList`.

**Comment by StephenStrickland** [comment]
Something weird is happening with addresses, see the following code.
```rust
var arr = &p.stack.at(p.stack.len - 1).Array;
debug.warn("addresses?: \n{} \n{}\n", @ptrToInt(arr), @ptrToInt(&p.stack.at(p.stack.len - 1).Array));
debug.warn("addresses?: \n{} \n{}\n", @ptrToInt(arr), @ptrToInt(&p.stack.at(p.stack.len - 1).Array));
```

#### Expected
```
before addresses?:
140734795328072
140734795328072
before addresses?:
140734795328072
140734795328072
```
#### Actual
```
before addresses?:
140734795328072  # pointer reference
140734795327960  # pointer from ArrayList(Value)
before addresses?:
140734795328072  # pointer reference
140734795327848  # pointer from ArrayList(Value)
```
It seems that when getting the reference for `&p.stack.at(p.stack.len - 1).Array` it returns a different address each time (probably a copy). This behavior is not noticed with any other `std.json.Value` case.

@andrewrk will this be fixed under copy elision?

**Comment by tiehuis** [comment]
The first case now produces the expected result. Have yet to test that final case with the addresses.

**Comment by daurnimator** [comment]
This appears to now be fixed.

Found + fixed https://github.com/ziglang/zig/pull/5607 while replicating.

**Comment by StephenStrickland** [comment]
perfect, thanks @daurnimator!
