### ISSUE TITLE
Unintuitive behavior when combining global variables with defer

### ISSUE THREAD

**Issue by DhruvPatel01** [ziglang/zig#17173]
### Zig Version

0.12.0-dev.381+1a0e6bcdb

### Steps to Reproduce and Observed Behavior

In the following code, the function `f` modifies global variable using defer. 

```zig
const std = @import("std");

var global: u8 = 0;

fn f() u8 {
    defer global += 1;
    return global;
}

pub fn main() void {
    _ = f();
    std.debug.print("global => Expected: {}, Actual: {}\n", .{ 1, global });
    global += f();
    std.debug.print("global => Expected: {}, Actual: {}\n", .{ 3, global });
}
```

### Expected Behavior

After the first invocation to `f`, the actual value of global and expected value of global variable match. But it doesn't when I do `global += f()`. `f` should increase the value by 1, and the expression itself should have increased the value by 1 more.

Apologies if this is an expected behavior and I missed something in the documentation.

**Comment by IntegratedQuantum** [comment]
This is unrelated to defer or global variables:
```
pub fn main() void {
	var local: u8 = 1;
	local += blk: {
		local += 1;
		break :blk 1;
	};
	std.log.info("{}", .{local});
}
```

When doing `+=` it seems that zig loads the left hand side before computing the right hand side.
I don't know if this is intended behavior though.

**Comment by DhruvPatel01** [comment]
Thanks for simplifying @IntegratedQuantum. Now, it is easier to see that this may not be actually a bug. What I was expecting would be the behavior if arguments are evaluated right to left, but there is no reason to believe that needs to be the case. 

I am not sure what should be the behavior in this simple case. But in case like `x += f() + g()` and where both `f` and `g` has effect on `x`, I don't think there is a right way to implement it.

**Comment by rohlem** [comment]
IMO the code's behavior is ambiguous.
Therefore the language should 
- either define the behavior to expect,
- or it should state that the construct is illegal.
  (In this case ideally generate a compile error, or a runtime safety-check.
  I assume we won't cover all cases, but some cases are better than none.)

**Comment by andrewrk** [comment]
There is no ambiguity here. The language is defined to evaluate the LHS first.
