### ISSUE TITLE
Optional collapse

### ISSUE THREAD

**Issue by Arnau478** [ziglang/zig#17184]
We should implement a way to "collapse" optional types. That would turn `??T` into `?T`. This would be useful, for instance, when accessing fields of a hashmap that has optional values (something like `StringHashMap(?u64)`, if we called `.get()`, that would return a `??T`).

Making it coerce doesn't seem right to me, I think it would make more sense to either have a builtin (`@collapseOptional`) or a function in `std`. I think the builtin makes more sense, though.

If it was implemented in the `std`, the implementation could be something like this:
```zig
pub fn collapseOptional(comptime T: type, opt: ??T) ?T {
    if(opt) |inner| return inner;
    return null;
}
```

To illustrate this further, let's take a type `??bool`, and see how this would be collapsed:
- an optional with no value (`null`) ==> an optional with no value (`null`)
- an optional that has a value of an optional with no value (`null`) ==> an optional with no value (`null`)
- an optional that has a value of an optional that a value of `true` ==> an optional that has a value of `true`
- an optional that has a value of an optional that a value of `true` ==> an optional that has a value of `false`

It would basically collapse both `null`s.

**Comment by mlugg** [comment]
This seems very rarely useful (I can't say I've *ever* needed it in my years of writing Zig so far), and if you do want it, you can trivially implement it in userspace even more simply than you thought:
```zig
pub fn collapseOptional(comptime T: type, opt: ??T) ?T {
    return opt orelse null;
}
// or, if you don't want to have to pass the type:
pub fn collapseOptional(opt: anytype) std.meta.Child(@TypeOf(opt)) {
    return opt orelse null;
}
```
What's your justification for why this should be a builtin, or why it should exist at all when you can just write `const foo: ?u32 = my_hash_map.get(foo) orelse null;`?

**Comment by Arnau478** [comment]
> What's your justification for why this should be a builtin, or why it should exist at all when you can just write const foo: ?u32 = my_hash_map.get(foo) orelse null;?

Okay, sorry, I didn't think of `orelse null`, that would work I guess... Given that, it really doesn't make much sense to have a builtin or std function. Thus, I will close this issue.
