### ISSUE TITLE
AtomicRmw does not accept relaxed ordering

### ISSUE THREAD

**Issue by lovely-error** [ziglang/zig#17183]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

Ahoy, this code does not work in zig, but does in rust.
```
pub fn main() !void {
    var item: u32 = 0;
    @atomicRmw(u32, &item, std.builtin.AtomicRmwOp.Add, 1, std.builtin.AtomicOrder.Unordered);
}
```
The error I get is this
```
error: @atomicRmw atomic ordering must not be Unordered
```
I am assuming unordered is same as relaxed, in which case this must be compiled ok 😕

### Expected Behavior

AtomicRwm should accept unordered ordering

**Comment by mlugg** [comment]
`.Unordered` is not equivalent to relaxed - you're looking for `.Monotonic`.

**Comment by lovely-error** [comment]
Oh, I thought Unordered meant Relaxed and Monotonic meant Consume. Haven't found proper description of it in docs. Thx.

**Comment by mlugg** [comment]
The atomic orderings correspond exactly to those in LLVM, which are documented here: https://llvm.org/docs/Atomics.html#atomic-orderings
