### ISSUE TITLE
lower pointer alignment safety checks using log2 alignment operand

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#17197]
```zig
extern fn panic_unaligned_addr() void;

export fn safety_check_byte_units(addr: u64, alignment: u64) void {
    if (addr % (alignment - 1) != 0)
        panic_unaligned_addr();
}
export fn safety_check_log2_units(addr: u64, alignment: u8) void {
    if (@ctz(addr) < alignment)
        panic_unaligned_addr();
}
```

x86_64:

```
safety_check_byte_units:
        mov     rax, rdi
        dec     rsi
        mov     rcx, rdi
        or      rcx, rsi
        shr     rcx, 32
        je      .LBB0_1
        xor     edx, edx
        div     rsi
        test    rdx, rdx
        je      .LBB0_4
.LBB0_5:
        jmp     panic_unaligned_addr@PLT
.LBB0_1:
        xor     edx, edx
        div     esi
        test    rdx, rdx
        jne     .LBB0_5
.LBB0_4:
        ret

safety_check_log2_units:
        tzcnt   rax, rdi
        cmp     al, sil
        jae     .LBB1_1
        jmp     panic_unaligned_addr@PLT
.LBB1_1:
        ret
```

aarch64:

```
safety_check_byte_units:
        sub     x8, x1, #1
        udiv    x9, x0, x8
        msub    x8, x9, x8, x0
        cbz     x8, .LBB0_2
        b       panic_unaligned_addr
.LBB0_2:
        ret

safety_check_log2_units:
        rbit    x8, x0
        clz     x8, x8
        cmp     w8, w1
        b.hs    .LBB1_2
        b       panic_unaligned_addr
.LBB1_2:
        ret
```

[godbolt link](https://godbolt.org/z/7bcTx9P93)

Currently, zig does the former:

https://github.com/ziglang/zig/blob/5af5d87ad2227b6a7b5347c7217312ef8a83de12/src/Sema.zig#L21462-L21465

Instead it should do the latter.

**Comment by IntegratedQuantum** [comment]
How about this?
```zig
export fn safety_check_log2_units2(addr: u64, alignment: u8) void {
    if (addr & (@as(u64, 1) << @intCast(alignment)) - 1 != 0)
        panic_unaligned_addr();
}
```
```asm
safety_check_log2_units2:
        and     sil, 63
        bzhi    rax, rdi, rsi
        je      .LBB3_1
        jmp     panic_unaligned_addr@PLT
.LBB3_1:
        ret
```
I looked it up and `bzhi` seems to have lower or equal latency than `tzcnt` on most processors. For example on intel skylake `bzhi` has a latency of 1, whereas `tzcnt` has a latency of 3 cycles.

Additionally the `and` with `63` comes from the `intCast` which would disappear when using a `u6` for alignment.

Also I think the `byte_units` version is wrong: `% (alignment - 1)` would mod by odd, non-power-of-2 numbers which is not the way to go when you want to check last x bits.
I think you meant to use `% alignment` or `& (alignment - 1)` if we can assert that it's a power of 2.

**Comment by andrewrk** [comment]
Oops, you're right. I also realized that the alignment would always be a compile-time known constant too. Because of this, [nothing matters](https://godbolt.org/z/je6Ts5q6q) and this issue can simply be closed as invalid.

Thanks for the discussion :sweat_smile:
