### ISSUE TITLE
`GetMessagePos`, `GetMessageTime`, and `GetMessageExtraInfo` should be added to std.os.windows.user32

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#17228]
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmessagepos
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmessagetime
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmessageextrainfo

Even though they're relative obscure, they are a part of the standard message loop toolkit and is not tied to any specific functionality.

**Comment by nektro** [comment]
they're readily available in zig through https://github.com/marlersoft/zigwin32 if you're open to using a package

**Comment by squeek502** [comment]
The standard library is not intending on including complete Windows API bindings. See https://github.com/ziglang/zig/issues/4426

Note that you can define these functions as `extern` in your program and they will work fine.

**Comment by squeek502** [comment]
I'm saying that it's much more likely that the `GetMessage`/`PeekMessage` bindings will be removed from the standard library than a PR that adds `GetMessagePos`, `GetMessageTime`, etc will be accepted (unless the compiler needs those bindings).

- https://github.com/ziglang/zig/issues/4426#issuecomment-858820245
- https://github.com/ziglang/zig/issues/1840

**Comment by squeek502** [comment]
I like the organization of the std lib bindings, too. A standalone library focused on "std lib"-like bindings sounds like a good idea.

Just FYI, `zigwin32`'s namespacing is based on Microsoft's [win32metadata](https://github.com/microsoft/win32metadata). There's a note about that in relation to `zigwin32` here: https://github.com/marlersoft/zigwin32gen#win32json-vs-cc-win32-sdk
