### ISSUE TITLE
Proposal: remove anonymousDependency once relative paths are supported in build.zig.zon

### ISSUE THREAD

**Issue by mlugg** [ziglang/zig#17238]
Once #14603 or similar is merged, `std.Build.anonymousDependency` is redundant: its use cases can be instead handled by specifying a local path in `build.zig.zon` and calling `std.Build.dependency` as you would for a remote dependency.

In fact, `anonymousDependency` is strictly *less* useful. Here are some key use cases it does not support:
* Temporarily overriding a dependency path for a package to refer to a local development copy. This will be particularly useful once #14292 is implemented.
* Referencing a vendored dependency which in turn has remote dependencies. This is impossible via `anonymousDependency` because the build system cannot call into the actual package manager (which is integrated into the compiler).

As such, `std.Build.anonymousDependency` should be removed, giving one obvious and straightforward way to reference local dependencies.

**Comment by binarycraft007** [comment]
> Once #14603 or similar is merged, `std.Build.anonymousDependency` is redundant: its use cases can be instead handled by specifying a local path in `build.zig.zon` and calling `std.Build.dependency` as you would for a remote dependency.
> 
> In fact, `anonymousDependency` is strictly _less_ useful. Here are some key use cases it does not support:
> 
>     * Temporarily overriding a dependency path for a package to refer to a local development copy. This will be particularly useful once [ability to specify additional build dependency mirrors that affect any package in the full dependency tree #14292](https://github.com/ziglang/zig/issues/14292) is implemented.
> 
>     * Referencing a vendored dependency which in turn has remote dependencies. This is impossible via `anonymousDependency` because the build system cannot call into the actual package manager (which is integrated into the compiler).
> 
> 
> As such, `std.Build.anonymousDependency` should be removed, giving one obvious and straightforward way to reference local dependencies.

what about the use case where Ineed to embed artifact in one build step to another:
https://github.com/binarycraft007/wechat-hook/blob/main/build.zig#L34
https://github.com/binarycraft007/wechat-hook/blob/main/src/main.zig#L14

**Comment by mlugg** [comment]
This issue is about dependencies between packages (in the sense of the package manager), not about Zig modules. The code you reference is not using `anonymousDependency`.

**Comment by binarycraft007** [comment]
> This issue is about dependencies between packages (in the sense of the package manager), not about Zig modules. The code you reference is not using `anonymousDependency`.

sorry, I misunderstood it, thanks for the clarification.
