### ISSUE TITLE
Standard library documentation is unreadable with Firefox

### ISSUE THREAD

**Issue by bortzmeyer** [ziglang/zig#17251]
A page like https://ziglang.org/documentation/master/std/ is unreadable with Firefox. The Zig logo takes almost all the page, leaving only a few lines for the information. No such problem with Google Chrome.

Firefox 105.0.2 (64-bits) running on Ubuntu over a regular desktop PC.

**Comment by kristoff-it** [comment]
FYI this indeed a bug in that version of firefox, I recommend upgrading to a newer version whenever you can.

**Comment by bortzmeyer** [comment]
This is the Firefox version in the current stable version of the OS I'm using. I'm not a full-time Zig developer and won't upgrade just for Zig.

**Comment by nektro** [comment]
the new version hasnt deployed yet but should hopefully fix the issue even for older versions
