### ISSUE TITLE
packed struct

### ISSUE THREAD

**Issue by User65-87-11** [ziglang/zig#17257]
### Zig Version

0.12.0-dev.278+0e8f130ae

### Steps to Reproduce and Observed Behavior

earlier i had this issue. Got explanation that it's expected behavior. But then i tested packed struct int C and it turns out that C compiles packed structs to find individual type sizes. Which is very convenient to use with **readStruct()**.

The original issue was that when i try to use a packed struct to read file with it reads extra.

there is also 

**5.13 Packed struct** 
_Unlike normal structs, packed structs have guaranteed in-memory layout:

Fields remain in the order declared, least to most significant.
There is no padding between fields._

```
test "Hello @Sizeof" {
    const s1 = packed struct {
        a: u32,
        b: u16,
    };

    const s2 = packed struct {
        a: u8,
        b: u16,
    };
    print("sizeof : s1:{d}, s2:{d}\n", .{ @sizeOf(s1), @sizeOf(s2) });
    
       try std.testing.expect(@sizeOf(s1) == @sizeOf(u32) + @sizeOf(u16));
    try std.testing.expect(@sizeOf(s2) == @sizeOf(u8) + @sizeOf(u16));
}
```

// @sizeof... sizeof : s1:**8**, s2:**4**

### Expected Behavior

```

#include <stdio.h>

struct MyStructure {   
  int myNum;            
  char myLetter;        
}__attribute__((packed));

int main(int argc, char **argv) {
    struct MyStructure s1;
    fprintf(stderr, "%lu\n",sizeof(s1));
    return 0;
}
```

this c code returns **5** and **8** if unpacked. Expected to get same outcome as in C.

**Comment by menduz** [comment]
packed structs are only significant to zig internals. Even though the layout is stable and works as expected, the datatype of the packed struct still needs to be aligned. That's the reason why you are not seeing it as `sizeof==5`. What you are looking for is 

```zig
const s2 = extern struct {
    a: u8 align(1),
    b: u16 align(1),
};
```
```
