### ISSUE TITLE
Cannot capture pointer to elements of const array in for loop

### ISSUE THREAD

**Issue by Hejsil** [ziglang/zig#1726]
```rust
test "" {
    const a = "111";
    for (a) |*c, i| // error: expected type '*u8', found '*const u8'
        @import("std").debug.assert(c.* == a[i]);
}
```

**Comment by thejoshwolfe** [comment]
Why do you want `*c` instead of just `c` there? At first glance, this doesn't seem like a problem. Maybe take `&c` in the body of the loop if you want a `*const u8`, but you shouldn't be able to modify the elements of `a` in your example, so the error seems right to me.

**Comment by Hejsil** [comment]
@thejoshwolfe This is just a simple example. There are plenty of reason to take const pointers over values (especially if you wanna store that pointer and avoid a copy). I'd say, either `[]const T` should also generate this error, or this should work.

**Comment by andrewrk** [comment]
I believe @Hejsil found the bug while implementing another bug fix in #1725, and this is some extra effort to fix this new found bug.

The expected output from this test case is that `@typeOf(c) == *const u8`.

**Comment by andrewrk** [comment]
I think the solution to this would clobber my copy-elision-2 branch, so unless there's a pressing need to have this solved, I'd recommend waiting until that lands.

**Comment by kristate** [comment]
Maybe we can create a milestone for after copy-elision-2 to separate tasks into two buckets? 4.0.1 ?
