### ISSUE TITLE
Autodoc: function page source link and member function source link differ

### ISSUE THREAD

**Issue by Vexu** [ziglang/zig#17279]
![image](https://github.com/ziglang/zig/assets/15308111/f53d4d88-e26c-41d3-a2d6-91c01595a401)

Note the different font and the brackets being part of the link.

**Comment by andrewrk** [comment]
As of https://github.com/ziglang/zig/commit/d0c06ca7127110a8afeb0ef524a197049892db21, there is only 1 source link and it is at the top of every page.
