### ISSUE TITLE
rewrite the stage2 parser to be recursive and adhere to the official grammar

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1729]
I'm creating this issue in case any contributors want to take a stab at it.

Now that @Hejsil created the [formal grammar](https://github.com/Hejsil/zig-grammar2), and now that we know [recursion is OK](https://ziglang.org/download/0.3.0/release-notes.html#recursion), there are 2 things that need to happen to `std/zig/parse.zig`:

 * rewrite it in recursive style so that it is easier to maintain
 * adhere to the formal grammar

It's a fairly large project, that will probably take a couple weeks for someone who isn't already familiar with the parser to do. You can look at `src/parser.cpp` and almost directly port the code.

**Comment by rayonix** [comment]
Has anyone started working on this rewrite? I have started looking at it but wanted to check. I'm new to Zig and thought this might be a good way to understand the compiler and language.

Also, is there any new information that would be helpful or important to know?

**Comment by hryx** [comment]
Hi @rayonix,

I already have a branch for this change with significant progress: https://github.com/ziglang/zig/compare/master...hryx:stage2-recursive-parser

It's close to done, though I haven't opened a pull request yet; I'm aiming to do so by tomorrow or next week. If you want to take a look, comments are welcome, even before the PR is ready!

There are several other issues which would be good for newcomers, though I don't have any particular recommendations — someone else might.
