### ISSUE TITLE
zig not linking macos frameworks

### ISSUE THREAD

**Issue by nogira** [ziglang/zig#17294]
### Zig Version

0.12.0-dev.596+2adb932ad

### Steps to Reproduce and Observed Behavior

- macos14, aarch/m1 cpu

---

```c
/* main.c */
#include <SDL2/SDL.h>

int main() {
    SDL_Init(SDL_INIT_VIDEO);
    SDL_Quit();
    printf("success\n");
    return 0;
}
```
- compiles fine with `cc`
```shell
cc -o main main.c -I/opt/homebrew/include -L/opt/homebrew/lib \
  /opt/homebrew/lib/libSDL2.a \
  -l z -l bz2 -l iconv \
  -framework Foundation -framework Cocoa -framework CoreGraphics -framework IOKit \
  -framework Metal -framework Carbon -framework CoreServices \
  -framework GameController -framework CoreHaptics -framework ForceFeedback \
  -framework CoreVideo -framework AudioToolbox -framework CoreAudio
./main
```
- but, use `zig cc` instead and it fails to find symbols from macos frameworks
```shell
zig cc -o main main.c -I/opt/homebrew/include -L/opt/homebrew/lib \
  /opt/homebrew/lib/libSDL2.a \
  -l z -l bz2 -l iconv \
  -framework Foundation -framework Cocoa -framework CoreGraphics -framework IOKit \
  -framework Metal -framework Carbon -framework CoreServices \
  -framework GameController -framework CoreHaptics -framework ForceFeedback \
  -framework CoreVideo -framework AudioToolbox -framework CoreAudio
./main
```

- similarly, converting the cmd to a `build.zig`, and the `main.c` to a `main.zig` fails in the same way

---

- **repo with all the minimal code examples here:** [🔗](https://github.com/nogira/minimum-viable-zig-static-linking-bug)

---

some of the countless missing symbol errors:
```shell
error: undefined reference to symbol _objc_msgSend$initWithContentRect:styleMask:backing:defer:screen:
    note: referenced in /opt/homebrew/Cellar/sdl2/2.28.3/lib/libSDL2.a(SDL_cocoawindow.o)
error: undefined reference to symbol _objc_msgSend$windowDidExitFullScreen:
    note: referenced in /opt/homebrew/Cellar/sdl2/2.28.3/lib/libSDL2.a(SDL_cocoawindow.o)
error: undefined reference to symbol _objc_msgSend$addItem:
    note: referenced in /opt/homebrew/Cellar/sdl2/2.28.3/lib/libSDL2.a(SDL_cocoaevents.o)
error: undefined reference to symbol _objc_msgSend$activateIgnoringOtherApps:
    note: referenced in /opt/homebrew/Cellar/sdl2/2.28.3/lib/libSDL2.a(SDL_cocoawindow.o)
error: undefined reference to symbol _objc_msgSend$finishLaunching
    note: referenced in /opt/homebrew/Cellar/sdl2/2.28.3/lib/libSDL2.a(SDL_cocoaevents.o)
```

### Expected Behavior

expected successful compilation

**Comment by nogira** [comment]
note: it's not that frameworks fail to link in general, because i just got zig to compile a static sdl3 lib from the sdl3 c files [here](https://github.com/nogira/SDL3.zig), and this static library is able to be used by a zig exe, with frameworks linking fine

**Comment by luizberti** [comment]
Seems to be restricted to `zig cc`, given that I just tested this on the latest nightly and it builds:

#### `main.zig`
```zig
const std = @import("std");
const hyp = @cImport({
    @cInclude("Hypervisor/Hypervisor.h");
});

pub fn main() !void {
    _ = hyp.hv_vm_config_create();
}
```

#### `build.zig`
```zig
const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const lib = b.addStaticLibrary(.{
        .name = "foo",
        .target = target,
        .optimize = optimize,
        .root_source_file = .{ .path = "src/main.zig" },
    });
    lib.linkFramework("Hypervisor");
    b.installArtifact(lib);
}
```

**Comment by moosichu** [comment]
﻿I figured out part the issue, SDL ships a framework that just contains a file called "SDL" - renaming it to SDL.tbd fixes it. The errors I got reported indicated that when it comes to linking symbols, zld is only looking for .tbd and .dylib files:
﻿```
﻿zig build-exe Debug_macos_aarch64 Debug native: error: error: unable to find framework 'SDL2'. searched paths: 
libraries/SDL2/macOS/SDL2.framework/SDL2.tbd
libraries/SDL2/macOS/SDL2.framework/SDL2.dylib
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/SDL2.framework/SDL2.tbd
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/SDL2.framework/SDL2.dylib
 ```

**Comment by moosichu** [comment]
I've created a PR that *should* fix the issue (at least it did for me).
