### ISSUE TITLE
error occurs only with runtime safety

### ISSUE THREAD

**Issue by orvitpng** [ziglang/zig#17306]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

Using the following code:
```zig
const std = @import("std");

test "read bytes to enum" {
    var value: []u8 = @constCast("BBBBB");
    var letter: Letter = undefined;
    @memcpy(std.mem.asBytes(&letter), value);

    try std.testing.expect(letter == .B);
}

const Letter = enum(u40) {
    A = strToInt("AAAAA"),
    B = strToInt("BBBBB"),
    C = strToInt("CCCCC"),

    fn strToInt(str: *const [5]u8) u40 {
        return @byteSwap(@as(u40, @bitCast(str.*)));
    }
};
```
An attempt is made to convert raw bytes to an enum under the assumption that these bytes will always be of a set list of values. This is useful for a wide range of things, the one I'm mainly interested being reading a file into a struct.

### Expected Behavior

It is expected that under all conditions where the input matches an enum value, the test will pass. However, only when optimized for ReleaseFast and ReleaseSmall will this this work. With runtime safety, there will be a panic of either
```
panic: @memcpy arguments have non-equal lengths
```
or
```
panic: invalid enum value
```
I am not aware of why this happens and am generally uneducated in terms of how the compiler works its magic, but I assume this falls under the category of unexpected behavior.

**Comment by IntegratedQuantum** [comment]
Well `@sizeOf(Letter)` would be 8(due to alignment), so `std.mem.asBytes(&letter)` returns a `*align(8) [8]u8`.
So you are giving `@memcpy` one 8 byte array, and one 5 byte slice "BBBBB". Hence the runtime error.

Now why don't you just use your `strToInt` function?
```zig
letter = @enumFromInt(Letter.strToInt(value[0..5]));
```
This has the advantage of not using `@memcpy` which is slow for small arrays.

​
Also that `@constCast` there is just waiting to cause undefined behavior. You can and should never try to modify the content of string literals! Only use `@constCast` if some bad API forgot to add a `const` on some input parameter.
```zig
var value: []const u8 = "BBBBB";
```

**Comment by orvitpng** [comment]
The suggestions you are describing are merely for this example/test. I cannot use the @enumFromInt as my use case is reading a file to a struct.
```
            var vsd: osta_udf.VolumeStructureDescriptor = undefined;
            _ = file.pread(
                std.mem.asBytes(&vsd),
                start_block * bs + i * vsd_len + 32768,
            ) catch continue;
```
I am trying to avoid any logic and be able to just take the file that I know starts with a specific sequence of bytes and structurize it. This structure includes an enum of 6 different possible values, the function allows the bits from the file to be converted into the enum without logic or any further code! I'm not sure there is an alternative to what I am doing, but this is the best I was able to come up with. The test is because it is the same issue and is much more intuitive than showing an example where I read from a mysterious file.

**Comment by IntegratedQuantum** [comment]
First of all you should use a `packed struct`s for your `VolumeStructureDescriptor`, regular structs don't have a guaranteed memory layout and the compiler might reorder fields.
Then you can you can just slice off the final alignment bytes:
```zig
file.pread(
    asBytes(&vsd)[0..len]
    ...
)
```
Or in the context of your test case:
```zig
@memcpy(std.mem.asBytes(&letter)[0..5], value);
```

**Comment by orvitpng** [comment]
> First of all you should use a `packed struct`s for your `VolumeStructureDescriptor`, regular structs don't have a guaranteed memory layout and the compiler might reorder fields. Then you can you can just slice off the final alignment bytes:
> 
> ```zig
> file.pread(
>     asBytes(&vsd)[0..len]
>     ...
> )
> ```
> 
> Or in the context of your test case:
> 
> ```zig
> @memcpy(std.mem.asBytes(&letter)[0..5], value);
> ```

packed structs cannot contain arrays and I have seen none of this mentioned reordering of fields in my project

**Comment by IntegratedQuantum** [comment]
> I have seen none of this mentioned reordering of fields in my project

It might not happen now, but this could break your code in the future. Here from the [documentation](https://ziglang.org/documentation/master/#struct):
> Zig gives no guarantees about the order of fields and the size of
the struct but the fields are guaranteed to be ABI-aligned.

`extern struct`s or structs parsed from C code also have a guaranteed order, in case you are using those.
The choice between `extern` and `packed` depends on what you want to parse. If everything is packed in your file (no alignment between fields), then you should use a packed struct, otherwise use an extern struct which does support arrays.

> packed structs cannot contain arrays

Not natively, but you can add them with `std.PackedIntArray`. This does make access more complicated though.

**Comment by orvitpng** [comment]
> > I have seen none of this mentioned reordering of fields in my project
> 
> It might not happen yet, but this could break your code in the future. Here from the [documentation](https://ziglang.org/documentation/master/#struct):
> 
> > Zig gives no guarantees about the order of fields and the size of
> > the struct but the fields are guaranteed to be ABI-aligned.
> 
> `extern struct`s or structs parsed from C code also have a guaranteed order, in case you are using those. The choice between `extern` and `packed` depends on what you want to parse. If everything is packed in your file (no alignment between fields), then you should use a packed struct, otherwise use an extern struct which does support arrays.
> 
> > packed structs cannot contain arrays
> 
> Not natively, but you can add them with `std.PackedIntArray`. This does make access more complicated though.

Thank you for this, however my problem still stands. I'm not sure if this is my fault or what, but I cannot use Debug for my application and the performance of doing this is so unbelievably high that a parser seems like it isn't an option.

**Comment by IntegratedQuantum** [comment]
I think I need to see more of your code, to be able to help you further.

**Comment by orvitpng** [comment]
> I think I need to see more of your code, to be able to help you further.

Currently working with the following. Keep in mind no `packed struct` because they cannot contain int arrays and I'm also getting that they cannot contain `std.PackedIntArrayEndian`; no `extern struct` because that cannot contain a u40.
```
const std = @import("std");

const Filesystem = @import("../Filesystem.zig");

pub fn detect(file: std.fs.File, fs: *Filesystem) bool {
    // some code in between that is not related
    var vsd: osta_udf.VolumeStructureDescriptor = undefined;
    _ = file.pread(
        std.mem.asBytes(&vsd),
        start_block * bs + i * vsd_len + 32768,
    ) catch continue;

    std.debug.print("{any}\n", .{vsd.StandardIdentifier});

    return true;
}

// OSTA UDF | Version 2.60
const osta_udf = struct {
    const VolumeStructureDescriptor = ecma_167.VolumeStructureDescriptor(
        [2041]u8,
    );
};

// ECMA 167 | Edition 3
const ecma_167 = struct {
    // 2/4 (9.1)
    fn VolumeStructureDescriptor(comptime T: type) type {
        std.debug.assert(@sizeOf(T) == 2041);
        return struct {
            StructureType: u8,
            // TODO(@orvit): fix runtime safety issues
            StandardIdentifier: enum(u40) {
                BEA01 = strToInt("BEA01"),
                BOOT2 = strToInt("BOOT2"),
                CD001 = strToInt("CD001"),
                CDW02 = strToInt("CDW02"),
                NSR02 = strToInt("NSR02"),
                NSR03 = strToInt("NSR03"),
                TEA01 = strToInt("TEA01"),

                fn strToInt(str: *const [5]u8) u40 {
                    return @byteSwap(@as(u40, @bitCast(str.*)));
                }
            },
            StructureVersion: u8,
            StructureData: T,
        };
    }
};
```

**Comment by IntegratedQuantum** [comment]
Ok, I would do the following:
First of all I assume that there is no padding in the header.
So I would go with a packed struct for the header, keeping the rest as is:
```zig
const Header = packed struct {
    StructureType: u8,
    StandardIdentifier: enum(u40)...
    StructureVersion: u8,
};
// Note that I always get this endianness wrong, so you may need to try:
const Header = packed struct {
    StructureVersion: u8,
    StandardIdentifier: enum(u40)...
    StructureType: u8,
};
fn VolumeStructureDescriptor(comptime T: type) type {
        std.debug.assert(@sizeOf(T) == 2041);
        return struct {
            header: Header,
            StructureData: T,
        };
}
```
Then you can read header and data separately:
```zig
    _ = try file.pread(
        std.mem.asBytes(&vsd.header)[0..7],
        start_block * bs + i * vsd_len + 32768,
    );
    _ = try file.pread(
        &vsd.StructureData,
        start_block * bs + i * vsd_len + 32768 + 7,
    );
```
Or if you want to save syscalls, you should probably read everything to a `[2048]u8` first and then copy it over to the header and body.

**Comment by orvitpng** [comment]
> Ok, I would do the following: First of all I assume that there is no padding in the header. So I would go with a packed struct for the header, keeping the rest as is:
> 
> ```zig
> const Header = packed struct {
>     StructureType: u8,
>     StandardIdentifier: enum(u40)...
>     StructureVersion: u8,
> };
> // Note that I always get this endianness wrong, so you may need to try:
> const Header = packed struct {
>     StructureVersion: u8,
>     StandardIdentifier: enum(u40)...
>     StructureType: u8,
> };
> fn VolumeStructureDescriptor(comptime T: type) type {
>         std.debug.assert(@sizeOf(T) == 2041);
>         return struct {
>             header: Header,
>             StructureData: T,
>         };
> }
> ```
> 
> Then you can read header and data separately:
> 
> ```zig
>     _ = try file.pread(
>         std.mem.asBytes(&vsd.header)[0..7],
>         start_block * bs + i * vsd_len + 32768,
>     );
>     _ = try file.pread(
>         &vsd.StructureData,
>         start_block * bs + i * vsd_len + 32768 + 7,
>     );
> ```
> 
> Or if you want to save syscalls, you should probably read everything to a `[2048]u8` first and then copy it over to the header and body.

I see this is redundant and, also, doesn't solve the problem of my enum issue.

**Comment by IntegratedQuantum** [comment]
I don't think I understand your issue then.
I thought the issue was that `std.mem.asBytes(&vsd)` was too long due to unexpected size and alignment of the enum.

**Comment by orvitpng** [comment]
> I don't think I understand your issue then. I thought the issue was that `std.mem.asBytes(&vsd)` was too long due to unexpected size and alignment of the enum.

Even if I do pack the struct, I still will get `panic: invalid enum value`. I have checked, the read bytes for the identifier are "CD001", which matches with my enum. Again, in ReleaseFast, this is not a problem. Alignment is not the problem, the problem is that Zig is somehow taking the bytes and not matching it with an enum.

**Comment by IntegratedQuantum** [comment]
I think this might be due to endianness. You should try to remove the `@byteSwap` in `strToInt`.

**Comment by orvitpng** [comment]
> I think this might be due to endianness. You should try to remove the `@byteSwap` in `strToInt`.

@byteSwap is necessary to fix endianness. As I said, runtime safety is the problem. ReleaseFast/ReleaseSmall works fine.

**Comment by IntegratedQuantum** [comment]
> ReleaseFast/ReleaseSmall works fine.

Can you share the code and data for the test case that works in Release but fails in debug, please. Without that I can only speculate.

**Comment by orvitpng** [comment]
> > ReleaseFast/ReleaseSmall works fine.
> 
> Can you share the code and data for the test case that works in Release but fails in debug, please. Without that I can only speculate.

What I've shared above highlights the question. No matter what I do, when reading raw bytes no an enum I get the `invalid_enum_value` panic. If it told me what it was trying I would more easily be able to debug this but I'm not given any related information.

**Comment by IntegratedQuantum** [comment]
Yeah, but what you've shared above sadly isn't enough to reproduce your issue.
Like I don't even know how the data looks you are trying to parse. It would help a lot if you shared an example, with like the first few bytes of the data.

For the time being, if you really think this is a compiler bug in the safety checks, then you can try `@setRuntimeSafety(false)` as a temporary solution.
But honestly, I believe this will just give you a more obscure error somewhere else.

**Comment by Vexu** [comment]
The safety check on `@memcpy` is correctly triggering because you are violating its conditions.
```zig
@compileLog(@TypeOf(std.mem.asBytes(&letter)), @sizeOf(Letter));
// @as(type, *align(8) [8]u8), @as(comptime_int, 8)
```
