### ISSUE TITLE
zig fmt: split function call arguments onto new lines

### ISSUE THREAD

**Issue by Ocrap7** [ziglang/zig#17324]
### Zig Version

0.12.0-dev.76+14f03d9

### Steps to Reproduce and Observed Behavior

If I call a function that has many parameters, the argument list (when calling) is unreadable:

```zig
const window = win32.CreateWindowExA(.LEFT, WINDOW_CLASS, window_name, @enumFromInt(windows.user32.WS_OVERLAPPEDWINDOW), windows.user32.CW_USEDEFAULT, windows.user32.CW_USEDEFAULT, windows.user32.CW_USEDEFAULT, windows.user32.CW_USEDEFAULT, null, null, null, null);
```

### Expected Behavior

It would be nice for zig fmt to produce the following:

```zig
const window = win32.CreateWindowExA(
    .LEFT,
    WINDOW_CLASS,
    window_name, 
    @enumFromInt(windows.user32.WS_OVERLAPPEDWINDOW), 
    windows.user32.CW_USEDEFAULT, 
    windows.user32.CW_USEDEFAULT, 
    windows.user32.CW_USEDEFAULT, 
    windows.user32.CW_USEDEFAULT, 
    null, 
    null, 
    null, 
    null,
);
```

**Comment by Luukdegram** [comment]
Zig fmt already does this when a trailing comma to the last argument exists.

**Comment by Ocrap7** [comment]
@Luukdegram it would be nice if zig fmt could do this automatically if it detects the line is too long, inserting a trailing comma while it’s at it.
