### ISSUE TITLE
Segmentation fault compiling builtin operation with overflow under certain conditions

### ISSUE THREAD

**Issue by amp-59** [ziglang/zig#17335]
### Zig Version

0.12.0-dev.669+e919fbea9

### Steps to Reproduce and Observed Behavior

Compile example program with `zig build-obj op_with_overflow_error.zig`
`op_with_overflow_error.zig`:
```zig
const Overflow = struct {
    usize,
    u1,
};
inline fn _subWithOverflow(comptime T: type, arg1: T, arg2: T) Overflow {
    return @subWithOverflow(arg1, arg2);
}
export fn subWithOverflow(x: usize, y: usize) usize {
    return _subWithOverflow(usize, x, y)[0];
}
```
Actual result:
```
zig build-obj op_with_overflow_error.zig
Segmentation fault
```

I have encountered a similar fault--in a different context--compiling `@shlWithOverflow`. However unable to create a minimal example and suspect the roots of both faults to be identical.

### Expected Behavior

-

**Comment by xdBronch** [comment]
this compiles successfully as of `0.12.0-dev.3245+4f782d1e8`
