### ISSUE TITLE
`@memset` on packed unions with over-aligned fields behaves differently under Debug vs Release

### ISSUE THREAD

**Issue by kcbanner** [ziglang/zig#17362]
### Zig Version

0.12.0-dev.700+376242e58

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");
const testing = std.testing;

test "memset packed union" {
    const U = packed union {
        a: u32,
        b: u8 align(8),
    };

    var u: U = undefined;
    @memset(std.mem.asBytes(&u), 0x2a);
    try testing.expectEqual(@as(u32, 0x2a2a2a2a), u.a);
    try testing.expectEqual(@as(u8, 0x2a), u.b);
}
```

```
$ zig test memset_packed.zig -O ReleaseFast
Test [1/1] test.memset packed union... expected 707406378, found 00
$ zig test memset_packed.zig
All 1 tests passed.
```

A few things seem to be required for this to happen:
- The `@memset`. Replacing it with `var u: U = .{ .a = 0x2a2a2a2a };` resolves the issue.
- The alignment of the over-aligned field must be greater than the size of any other field. If you change the `align(8)` to `align(4)`, or if you add a `u64` field, the issue is resolved.

### Expected Behavior

Consistent behaviour between Debug and Release*.

**Comment by xdBronch** [comment]
#16392 related? your test case passes on 0.10.1 in releasesafe and debug but fails in releasefast and releasesmall so slightly different behavior than the other issue.

**Comment by kcbanner** [comment]
Yes, that does seem related. However, I also saw the issue in the x86_64 non-llvm backend.

**Comment by kcbanner** [comment]
I retested this, and it passes in all release modes. 

Possibly solved by https://github.com/ziglang/zig/pull/17963
