### ISSUE TITLE
zig misidentifies CPU type as `generic` in Apple MacBook Air M2

### ISSUE THREAD

**Issue by plajjan** [ziglang/zig#17372]
### Zig Version

0.12.0-dev.701+d8bfbbbf2

### Steps to Reproduce and Observed Behavior

On an Apple MacBook Air M2 the native CPU is identified as a `generic` CPU. This has the consequence that very few CPU feature are enabled.

```
kll@mba2 % zig targets
...
 "native": {
  "triple": "aarch64-macos.12.7...12.7-none",
  "cpu": {
   "arch": "aarch64",
   "name": "generic",
   "features": [
    "enable_select_opt",
    "ete",
    "fp_armv8",
    "fuse_adrp_add",
    "fuse_aes",
    "neon",
    "trbe",
    "use_postra_scheduler"
   ]
  },
  "os": "macos",
  "abi": "none"
 }
}
kll@mba2 % uname -mprs
Darwin 21.6.0 arm64 arm
```

I noticed this when attempting to compile `mbedtls` which depend on the `aes` feature that's now lacking and thus it errors out.

An older MacBook Air M1 gets identified as having an `apple_a14` CPU. It's running a new MacOS but I don't think that matters in the identification process, no?
```
acton> zig targets | grep -A30 native
 "native": {
  "triple": "aarch64-macos.13.5.2...13.5.2-none",
  "cpu": {
   "arch": "aarch64",
   "name": "apple_a14",
   "features": [
    "aes",
    "aggressive_fma",
    "alternate_sextload_cvt_f32_pattern",
    "altnzcv",
    "am",
    "arith_bcc_fusion",
    "arith_cbz_fusion",
    "ccdp",
    "ccidx",
    "ccpp",
    "complxnum",
    "contextidr_el2",
    "crc",
    "crypto",
    "disable_latency_sched_heuristic",
    "dit",
    "dotprod",
    "el2vmsa",
    "el3",
    "flagm",
    "fp16fml",
    "fp_armv8",
    "fptoint",
    "fullfp16",
    "fuse_address",
...
```

Not sure 

### Expected Behavior

Identifying the native CPU types as something more specific which supports features like `aes`.

**Comment by andrewrk** [comment]
Logic is here:

https://github.com/ziglang/zig/blob/53775b0999527ced0550f3abb32c4a4a715af74e/lib/std/zig/system/darwin/macos.zig#L416-L452

**Comment by xdBronch** [comment]
could you tell me if this patch works?
```diff
diff --git a/lib/std/c/darwin.zig b/lib/std/c/darwin.zig
index fa121c49c..c0a5a0c93 100644
--- a/lib/std/c/darwin.zig
+++ b/lib/std/c/darwin.zig
@@ -3028,6 +3028,7 @@ pub const CPUFAMILY = enum(u32) {
     ARM_VORTEX_TEMPEST = 0x07d34b9f,
     ARM_LIGHTNING_THUNDER = 0x462504d2,
     ARM_FIRESTORM_ICESTORM = 0x1b588bb3,
+    ARM_AVALANCHE_BLIZZARD = 0xda33d83d,
     _,
 };
 
diff --git a/lib/std/zig/system/darwin/macos.zig b/lib/std/zig/system/darwin/macos.zig
index 6717b1319..24aa3de78 100644
--- a/lib/std/zig/system/darwin/macos.zig
+++ b/lib/std/zig/system/darwin/macos.zig
@@ -428,6 +428,7 @@ pub fn detectNativeCpuAndFeatures() ?Target.Cpu {
     switch (current_arch) {
         .aarch64, .aarch64_be, .aarch64_32 => {
             const model = switch (cpu_family) {
+                .ARM_AVALANCHE_BLIZZARD => &Target.aarch64.cpu.apple_a15,
                 .ARM_FIRESTORM_ICESTORM => &Target.aarch64.cpu.apple_a14,
                 .ARM_LIGHTNING_THUNDER => &Target.aarch64.cpu.apple_a13,
                 .ARM_VORTEX_TEMPEST => &Target.aarch64.cpu.apple_a12,
```

**Comment by owend** [comment]
I have an M2 Mac and applying this patch, 'zig native' returns:

```json
 "native": {
  "triple": "aarch64-macos.13.6...13.6-none",
  "cpu": {
   "arch": "aarch64",
   "name": "apple_a15",
   "features": [
    "aes",
    "alternate_sextload_cvt_f32_pattern",
    "altnzcv",
    "am",
    "amvs",
    "arith_bcc_fusion",
    "arith_cbz_fusion",
    "bf16",
    "bti",
    (etc)
```

**Comment by xdBronch** [comment]
nice, that certainly looks like an improvement. can you confirm that binaries built with this patch still work properly? unless anyone else has notes, PR incoming

**Comment by mikdusan** [comment]
small nit; please use name `ARM_BLIZZARD_AVALANCHE`, I'd still like to see us following SDK naming even though they goofed and are inconsistent.

From SDK 14.0 `/usr/include/mach/machine.h`:
```
[snip]
#define CPUFAMILY_ARM_FIRESTORM_ICESTORM 0x1b588bb3
#define CPUFAMILY_ARM_BLIZZARD_AVALANCHE 0xda33d83d
#define CPUFAMILY_ARM_EVEREST_SAWTOOTH  0x8765edea
```

also we might as well map `ARM_EVEREST_SAWTOOTH` can be mapped to `apple_a16`

**Comment by xdBronch** [comment]
yea i noticed my typo after i posted the comment, that + a16 are already in my commit :+1:

**Comment by plajjan** [comment]
I notice that there is a target called `apple_m1` and `apple_m2`. Is the CPU family id identical for a14 and m1 so we can't disambiguate or why aren't we using the mX variants?

**Comment by xdBronch** [comment]
you can differentiate the 2 but it would require a bit more work than what is currently done for the target detection. not sure if this part is necessarily correct but the feature sets are identical, same for a15/m2, im guessing theyre separate targets to avoid confusion
https://github.com/ziglang/zig/blob/412d863ba5801c1376af7ab8f04a71b839a820a6/lib/std/target/aarch64.zig#L1616-L1647
https://github.com/ziglang/zig/blob/412d863ba5801c1376af7ab8f04a71b839a820a6/lib/std/target/aarch64.zig#L1773-L1804
