### ISSUE TITLE
[discussion] Designing a crash-resistant library in Zig

### ISSUE THREAD

**Issue by thejoshwolfe** [ziglang/zig#1740]
I want to make a library that an IDE links against. It would be unacceptable if a bug in the library crashed the IDE process. Obviously perfect crash-proofness is unattainable (halting problem), but there's a lot of bugs that can be checked with Zig's runtime safety checks.

Is it possible to install a panic handler in my library so that if anything in the library panics, my library functions return with an error instead of bringing down the host application? Possibly something with setjmp/longjmp?

(This might be outside the scope of Zig) Is it possible to install a segfault handler that does something similar?

The library's API would all be mostly stateless functions, possibly doing IO, but not spawning extra threads or anything. The library would not call any non-zig library, so the whole library should be statically linked, I think.

**Comment by emekoi** [comment]
you can define your own panic function. it just has to go in your root project file.

**Comment by andrewrk** [comment]
Related: #426

**Comment by emekoi** [comment]
[here](https://github.com/nim-lang/Nim/blob/devel/lib/pure/segfaults.nim) is a custom segfault handler for posix and windows that might point you in the right direction. i'm not sure if you know nim but i imagine you can understand whats going on.

**Comment by andrewrk** [comment]
Crash resisting should be solved using appropriate OS features, e.g. threads or processes.
