### ISSUE TITLE
Support for embedding Windows Manifest XML to the compiled exe

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#17406]
I don't see anything in the documentation (or any Google Search results) about how to embed an [application manifest](https://learn.microsoft.com/en-us/windows/win32/sbscs/application-manifests) XML when compiling for Windows (or any info regarding embedding resources of any kind like icons and cursors, for that matter).

Would be nice to support this functionality so that you can actually build Windows apps with hidpi support.

**Comment by squeek502** [comment]
> (or any info regarding embedding resources of any kind like icons and cursors, for that matter).

Zig recently got full support for compiling `.rc` files. See https://github.com/ziglang/zig/pull/17069 for how to use it.

Will look into manifest files to see what would be involved in supporting them (does LLD handle them?)

**Comment by mlarouche** [comment]
Also useful to force UTF-8 codepage in a application when using the ASCII version of the API: https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/system/overviews/utf-8

**Comment by squeek502** [comment]
Looked into this a bit. Some notes:

- An embedded manifest file is really just XML data embedded as a RT_MANIFEST resource (ID = 24)
- The MSVC tool `mt.exe` is what's used to handle manifest files. The stuff it seems to do:
  + Convert manifest files to UTF-8 before embedding
  + Add and modify some stuff in the XML before embedding
  + Remove whitespace before embedding

For example, this manifest (encoded as UTF-16 LE with BOM):

```xml
<?xml version="1.0" encoding="UTF-16"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <assemblyIdentity type="win32" name="..." version="6.0.0.0"/>
  <application>
    <windowsSettings>
      <activeCodePage xmlns="https://schemas.microsoft.com/SMI/2019/WindowsSettings">UTF-8</activeCodePage>
    </windowsSettings>
  </application>
</assembly>
```

ends up as this when embedded in the `.exe` (note: `mt.exe` always includes a BOM encoded as UTF-8 at the start regardless of the input encoding):

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1"><assemblyIdentity type="win32" name="..." version="6.0.0.0"></assemblyIdentity><trustInfo xmlns="urn:schemas-microsoft-com:asm.v3"><security><requestedPrivileges><requestedExecutionLevel level="asInvoker" uiAccess="false"></requestedExecutionLevel></requestedPrivileges></security></trustInfo><ms_asmv1:application xmlns:ms_asmv1="urn:schemas-microsoft-com:asm.v1"><ms_asmv1:windowsSettings xmlns:ms_asmv1="urn:schemas-microsoft-com:asm.v1"><activeCodePage xmlns="https://schemas.microsoft.com/SMI/2019/WindowsSettings">UTF-8</activeCodePage></ms_asmv1:windowsSettings></ms_asmv1:application></assembly>
```

- The modifications `mt.exe` makes do not seem to actually be necessary for the embedded manifest to work as intended. The UTF-16 encoded manifest embedded directly as a resource (via an `.rc` file with the contents `1 24 test.manifest`) still has the intended effect on the compiled program.
- `clang` seems to want to call `mt.exe` for manifest embedding if the host is Windows.
  ```
  > clang test.c -Xlinker /manifest:embed -Xlinker /manifestinput:test.manifest -o test.exe
  LINK : fatal error LNK1158: cannot run 'mt.exe'
  ```
- LLVM has `llvm-mt` but it seems to not support most options (only `.manifest` to `.manifest` conversion?), and I'm unsure how/if it's used by clang. That is, I haven't yet figured out if LLVM supports embedding manifest files when cross-compiling from non-Windows hosts.

---

How I am testing things:

- The "Fusion manifest for an unpackaged Win32 app" from [here](https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page#set-a-process-code-page-to-utf-8) saved as `test.manifest`
- `test.c` (encoded as UTF-8):
  ```c
  #include <windows.h>

  int main() {
      return MessageBoxA(NULL, "кириллица", "hello", MB_OK);
  }
  ```
- `test.rc`:
  ```
  1 24 "test.manifest"
  ```

Compiling with clang:
```
clang test.c -luser32 -Wl,/manifest:embed -Wl,/manifestinput:test.manifest -o test-clang.exe
```
Compiling with zig + `mt.exe`
```
zig build-exe test.c -lc -femit-bin=test-mt.exe
mt.exe -manifest test.manifest -outputresource:test-mt.exe
```
Compiling with zig only:
```
zig build-exe test.c test.rc -lc -femit-bin=test-zig.exe
```

All 3 produce this (expected) result:

![messagebox-utf8](https://github.com/ziglang/zig/assets/2389051/8b4e1202-159c-43a0-8abb-794443626622)

If the manifest was not included, the message box would instead show up like this:

![messagebox-nomanifest](https://github.com/ziglang/zig/assets/2389051/581b4d19-9a7e-4c69-9590-973ddc1b0e5e)

---

So, the options as I see them currently:

1. Go down the rabbit-hole and create a full cross-platform `mt.exe` alternative. This would involve at minimum an XML parser.
2. Investigate LLVM more and see if passing `/manifest:embed /manifestinput:test.manifest` linker flags would be enough to get cross-compilation of manifest files working
3. Auto-generate `.rc` files for `.manifest` files and just embed the XML verbatim. This would get us support for manifest files really quickly almost for free, but may not support all possible manifests, as there may be something about the transformations `mt.exe` do that actually matter.

**Comment by squeek502** [comment]
Implemented option 3 here: https://github.com/ziglang/zig/issues/17406. Still figuring out how viable it'll be.

**Comment by squeek502** [comment]
@expikr, that sort of thing was discussed in https://github.com/ziglang/zig/pull/17069#issuecomment-1730809776

My position is basically the same as it was then:

> My position is that the clunky RC language is necessary for use cases that I think Zig cares about (compiling existing `.rc` files, people that know how to write RC files not needing to learn something new), and that Zig making its own better "compiles to `.res`" language/build system would not be able to enable the same use cases. It would be nicer to use for sure, but I think the potential benefit is small enough that it's not worth the effort.
