### ISSUE TITLE
change `addCSourceFiles` to be future proof by taking an options struct and add dependency option

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#17410]
```zig
pub const AddCSourceFilesOptions = struct {
    /// When provided, `files` are relative to `dependency` rather than the package that owns the `Compile` step.
    dependency: ?*std.Build.Dependency = null,
    files: []const []const u8,
    flags: []const []const u8 = &.{},
};

/// Handy when you have many C/C++ source files and want them all to have the same flags.
pub fn addCSourceFiles(self: *Compile, options: AddCSourceFilesOptions) void {
    // ...
}
```

Make it not repeat the C flags on the command line for every file even when a `dependency` is provided.

https://github.com/ziglang/zig/blob/e6590fea19e3eab94b35bfd3c36e29b53cefcaaf/lib/std/Build/Step/Compile.zig#L925

**Comment by Parzival-3141** [comment]
> Make it not repeat the C flags on the command line for every file even when a dependency is provided.

Just to confirm, are you talking about removing these empty `-cflags --` when appending a file? Using `addAssemblyFile()` (which doesn't take any flags) as an example:
https://github.com/ziglang/zig/blob/e6590fea19e3eab94b35bfd3c36e29b53cefcaaf/lib/std/Build/Step/Compile.zig#L1510-L1515
