### ISSUE TITLE
musl: add support for large code model if requested

### ISSUE THREAD

**Issue by kubkon** [ziglang/zig#17449]
### Zig Version

0.12.0-dev.869+42230803b

### Steps to Reproduce and Observed Behavior

I think we should be able to make the following work:

```
$ cat main.c
char arr[0x100000000];
int main() {
  return arr[2000];
}
$ zig build-exe main.c -target x86_64-linux-musl -mcmodel=large
...
 error: ld.lld: /home/kubkon/.cache/zig/o/7c2fea501037d8b828d62ed8c402e4ee/libc.a(/home/kubkon/.cache/zig/o/0f1ebc8024e8cd53d64d4556d4d7f2c7/__init_tls.o):(function static_init_tls: .text.static_init_tls+0x163): relocation R_X86_64_PC32 out of range: 4294975996 is not in [-2147483648, 2147483647]; references section '.bss.builtin_tls'
    note: referenced by syscall_arch.h:0 (/home/kubkon/dev/zig/build/stage4/lib/zig/libc/musl/arch/x86_64/syscall_arch.h:0)
```

The reason this fails is because `libc.a` was not built with `-mcmodel=large`. I think we should detect this option and forward it to any dependencies such as libc.

### Expected Behavior

Compiles successfully.

**Comment by alexrp** [comment]
The example in the issue fails with linker errors by default as expected, but works with `-mcmodel=large`. I'm not exactly sure when it was fixed, but the code model seems to be passed along when building musl now.
