### ISSUE TITLE
Segmentation fault compiling `comptime` field type `*@This()`

### ISSUE THREAD

**Issue by amp-59** [ziglang/zig#17456]
### Zig Version

0.12.0-dev.669+e919fbea9

### Steps to Reproduce and Observed Behavior

Compile example program with `zig build-obj comptime_field_this_ptr_error.zig`
`comptime_field_this_ptr_error.zig`:
```zig
comptime field: *@This() = blk: {
    var this: @This() = .{ .field = @ptrFromInt(8) };
    break :blk &this;
},
export fn entry(_: @This()) void {}
```
Actual result:
```
zig build-obj comptime_field_this_ptr_error.zig
Segmentation fault
```

### Expected Behavior

-

**Comment by wrongnull** [comment]
cannot reproduce on ```0.12.0-dev.6028+03adafd80```
```
comptime_field_this_ptr_error.zig:1:1: error: struct 'comptime_field_this_ptr_error' depends on itself
