### ISSUE TITLE
Segmentation fault compiling tuple default initializer

### ISSUE THREAD

**Issue by amp-59** [ziglang/zig#17475]
### Zig Version

0.12.0-dev.817+54e7f58fc

### Steps to Reproduce and Observed Behavior

Compile example program with `zig build-obj default_tuple_error.zig`
`default_tuple_error.zig`:
```zig
comptime {
    @as(struct { u8, u8 }, .{});
}
```
Actual result:
```
zig build-obj default_tuple_error.zig
Segmentation fault
```
The first compiler version exhibiting the bug (that I have observed) is `0.12.0-dev.654+599641357`.

### Expected Behavior

From `0.12.0-dev.467+0345d7866`:
```
zig build-obj default_tuple_error.zig
default_tuple_error.zig:2:29: error: missing struct field: 0
    @as(struct { u8, u8 }, .{});
                           ~^~
default_tuple_error.zig:2:29: note: missing struct field: 1
default_tuple_error.zig:2:9: note: struct 'default_tuple_error.comptime_0__struct_964' declared here
    @as(struct { u8, u8 }, .{});
        ^~~~~~~~~~~~~~~~~
```

**Comment by slonik-az** [comment]
possibly related #17349
