### ISSUE TITLE
linker identification issues when using zig as C compiler for meson based projects

### ISSUE THREAD

**Issue by bo-nemk** [ziglang/zig#17480]
### Zig Version

0.12.0-dev.414+461036069

### Steps to Reproduce and Observed Behavior

In my understanding, meson build system has limited support for linkers. It seems to check what linker you are using with:
```
CC -Wl,--version
```
If it cannot find a supported linker, it will not build. As of now, it does not support the zig linker:
```
$ zig cc -Wl,--version
zig ld 0.12.0-dev.414+461036069
```
This is problematic, as meson can't handle this.

A typical workaround would be as follows.
When running this with `clang` (the zig compiler backend as I understand it), I obtain:
```
$ clang -Wl,--version
GNU ld (GNU Binutils for Debian) 2.40
```

Apparently, it's using `ld`. If hypothetically this is undesirable, this can be changed by specifying the linker directly:
```
$ clang -fuse-ld=lld -Wl,--version
Debian LLD 14.0.6 (compatible with GNU linkers) 
```

This trick doesn't work with zig, however:
```
$ zig cc -fuse-ld=lld -Wl,--version
zig ld 0.12.0-dev.414+461036069
```

### Expected Behavior

For interop with meson, it would be nice if zig acted as clang does, i.e.:
```
$ zig cc -fuse-ld=lld -Wl,--version
Debian LLD 14.0.6 (compatible with GNU linkers) 
```

**Comment by bo-nemk** [comment]
Update: this is a duplicate of [this issue](https://github.com/ziglang/zig/issues/15549).

**Comment by bo-nemk** [comment]
Update: this is a duplicate of [this issue](https://github.com/ziglang/zig/issues/15549).

**Comment by zpon** [comment]
@bo-nemk this issue is not resolved by 15549, as that doesn't add `-fuse-ld` AFAIK. This is particularly problematic when using zig in combination with cgo which requires the `gold` linker to be used: https://github.com/golang/go/blob/master/src/cmd/link/internal/ld/lib.go#L1624
Can this issue be reopened?

**Comment by jiridanek** [comment]
AFAIK the original problem leading to the bug report was indeed resolved, so reopening would not be appropriate. I'm instead going to open a new issue for `-fuse-ld`

*  https://github.com/ziglang/zig/issues/18357
