### ISSUE TITLE
unhelpful error on empty .paths tuple in zon file

### ISSUE THREAD

**Issue by travisstaloch** [ziglang/zig#17491]
### Zig Version

0.12.0-dev.881+42998e637

### Steps to Reproduce and Observed Output

I made this same mistake as another person who i helped in discord #zig-help.

Firstly, when the .paths field is missing this is the error message:
```console
$ zig build
/tmp/issue-repro/build.zig.zon:1:2: error: missing top-level 'paths' field
.{
 ^
```

This lead me to guess that perhaps an empty tuple would suffice:
```console
/tmp/issue-repro $ zig build
/tmp/issue-repro/build.zig.zon:4:15: error: expected paths expression to be a struct
    .paths = .{},
              ^
```

The error can be silenced by replacing the tuple with `.{""}`.  However, this will only lead to the creation of an empty package which isn't likely what most users would want to do.

I've made a repro repo incase its helpful:

```console
/tmp $ cd /tmp
/tmp $ git clone git@github.com:travisstaloch/issue-repro.git
Cloning into 'issue-repro'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7 (delta 0), reused 7 (delta 0), pack-reused 0
Receiving objects: 100% (7/7), done.
/tmp $ cd issue-repro/
/tmp/issue-repro $ zig build
/tmp/issue-repro/build.zig.zon:4:15: error: expected paths expression to be a struct
    .paths = .{},
              ^
```

### Expected Output

I think a more helpful error message might be something like

```
expected an array of strings
```

rather than 
```
 expected paths expression to be a struct
```

**Comment by andrewrk** [comment]
Please see https://github.com/ziglang/zig/blob/master/doc/build.zig.zon.md#paths  

> The error can be silenced by replacing the tuple with `.{""}`. However, this will only lead to the creation of an empty package which isn't likely what most users would want to do.

This is intended to tell the package manager to include all paths. Fixed by #17498
