### ISSUE TITLE
Index out of bound when for (items, x..) |value, i| and x is not 0

### ISSUE THREAD

**Issue by ross96D** [ziglang/zig#17543]
### Zig Version

0.12.0-dev.906+2d7d037c4

### Steps to Reproduce and Observed Behavior

```Zig
    test "for basics" {
       const items = [_]i32{ 4, 5, 3, 4, 0 };

       for (items, 1..) |value, i| {
           std.debug.print("{}:{}:{}\n", .{ i, value, items[i] });
       }
}
```
output:

zig build test
run test: error: 1:4:5
2:5:3
3:3:4
4:4:0
thread 82483 panic: index out of bounds: index 5, len 5

### Expected Behavior

test is passed

**Comment by andrewrk** [comment]
Not a bug, please ask your question in one of the [communities](https://github.com/ziglang/zig/wiki/Community)
