### ISSUE TITLE
error: invalid builtin function "@abs"

### ISSUE THREAD

**Issue by n8an** [ziglang/zig#17559]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

ball is a struct
ball.direction is a Vector2 from raylib-zig
ball.direction.x is f32

Everything works fine, I used other builtin functions just fine, like "@floatFromInt".
But when I use "@abs", I get this error, without much usefull info.

```
zig build run
zig build-exe Project Debug native: error: the following command failed with 1 compilation errors:
C:\ProgramData\chocolatey\lib\zig\tools\zig-windows-x86_64-0.11.0\zig.exe build-exe C:\Users\Admin\Desktop\zig\project\src\main.zig -lwinmm -lgdi32 -lopengl32 C:\Users\Admin\Desktop\zig\project\zig-cache\o\0f10772180e328ad1df1cb1c782210d1\raylib.lib -lwinmm -lgdi32 -lopengl32 -lc --cache-dir C:\Users\Admin\Desktop\zig\project\zig-cache --global-cache-dir C:\Users\Admin\AppData\Local\zig --name Project --mod raylib-zig::C:\Users\Admin\Desktop\zig\project\raylib-zig\lib\raylib-zig.zig --mod raylib-math:raylib-zig:C:\Users\Admin\Desktop\zig\project\raylib-zig\lib\raylib-zig-math.zig --deps raylib=raylib-zig,raylib-math -I C:\Users\Admin\Desktop\zig\project\zig-cache\i\5c690dd0957aad475dd4f0b41919d0db\include --listen=-
Build Summary: 5/8 steps succeeded; 1 failed (disable with --summary none)
run transitive failure
└─ run Project transitive failure
   └─ zig build-exe Project Debug native 1 errors
src\main.zig:108:38: error: invalid builtin function: '@abs'
                ball.direction.x = @abs(ball.direction.x);
                                     ^~~~~~~~~~~~~~~~~~~~~~
```

### Expected Behavior

Everything compiling, and the ABS builting function working, then the result being used as usual.

**Comment by andrewrk** [comment]
There is no `@abs` in 0.11.0: https://ziglang.org/documentation/0.11.0/

This is a breaking change that happened in the master branch of zig, which is not released yet.

**Comment by n8an** [comment]
> There is no `@abs` in 0.11.0: https://ziglang.org/documentation/0.11.0/
> 
> This is a breaking change that happened in the master branch of zig, which is not released yet.

My bad, ZLS suggested it as if it existed, and seems like I was looking at "master" documentation to find it.

**Comment by andrewrk** [comment]
no problem!
