### ISSUE TITLE
flaky linker tests report FileBusy

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#17576]
Zig Version: `0.12.0-dev.1100+364c54460f`

This is happening occasionally, for example in [this run](https://github.com/ziglang/zig/actions/runs/6551410014/job/17792522470).
```
test.link.run main: error: unable to spawn /home/ci/actions-runner1/_work/zig/zig/build-debug/zig-local-cache/o/1c7ed4403ba284f0f190bde4250dadf7/main: FileBusy
test.link.run main: error: unable to spawn /home/ci/actions-runner1/_work/zig/zig/build-debug/zig-local-cache/o/ee4325c7972452d31f85bc83d5b41a19/main: FileBusy
Build Summary: 5272/5428 steps succeeded; 149 skipped; 2 failed; 136560/142695 tests passed; 6135 skipped (disable with --summary none)
test transitive failure
+- test-link transitive failure
   +- link.test-elf transitive failure
      +- test-elf-tls-gd-to-ie-x86_64-linux-gnu-Debug-llvm transitive failure
      |  +- run main failure
      +- test-elf-tls-ld-x86_64-linux-gnu-Debug-llvm transitive failure
         +- run main failure
error: the following build command failed with exit code 1:
```

**Comment by andrewrk** [comment]
[another](https://github.com/ziglang/zig/actions/runs/6553826657/job/17799824723)
```
test.link.run main: error: unable to spawn /home/ci/actions-runner11/_work/zig/zig/build-release/zig-local-cache/o/b1f89ba413d72658af95ffa27c5dec17/main: FileBusy
Build Summary: 5256/5410 steps succeeded; 149 skipped; 1 failed; 136649/142783 tests passed; 6134 skipped (disable with --summary none)
test transitive failure
+- test-link transitive failure
   +- link.test-elf transitive failure
      +- test-elf-tls-ld-no-plt-x86_64-linux-gnu-Debug-llvm transitive failure
         +- run main failure
```

**Comment by kubkon** [comment]
Any clue what can cause this? Are we maybe not closing the file before trying to run it? It'd be nice to get it resolved rather than disabling tests which are there to uncover potential linker regressions.

**Comment by andrewrk** [comment]
Yes I agree, and I'm happy to help search for a proper resolution. First priority however is unblocking everybody from landing changes in master branch.

I think it's this:

```
       ETXTBSY
              The specified executable was open for writing  by  one  or  more
              processes.
```

**Comment by kubkon** [comment]
I think I know what's up. If you look closely, in the same test that is failing we are effectively re-running the same set of steps twice potentially causing the compiler to try and overwrite the file while running it. First occurrence https://github.com/ziglang/zig/blob/aeadcb3918f7e6bc7abb08e70ffe3b3c25fb9c22/test/link/elf.zig#L2115-L2127 and then https://github.com/ziglang/zig/blob/aeadcb3918f7e6bc7abb08e70ffe3b3c25fb9c22/test/link/elf.zig#L2129-L2142. If we ever expose the missing linker flag this was meant to use for testing (`--no-relax`), it will make way more sense. For now I believe commenting out oone instance of steps should get rid of the flakiness. Thoughts @andrewrk?

**Comment by andrewrk** [comment]
Aha, I think that is exactly it. Another possible workaround would be to change the root name for each test so that the cache hash puts them in different namespaces. Currently it essentially thinks that you're trying to incrementally compile it while the first compilation is still running.

**Comment by kubkon** [comment]
Ah good idea! Lemme do that then!
