### ISSUE TITLE
Initializing an array with runtime value takes very long (or freezes) for larger array sizes

### ISSUE THREAD

**Issue by aquamorta** [ziglang/zig#17586]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior
```zig
// run with this zig build test

const std = @import("std");

const Self = @This();

pub fn main() !void {}

//const size = 100; runs with acceptable time

// takes a very loooong time
const size = 65536;

data: [size]u8 = undefined,

pub fn init(value: u8) Self {
    //return Self{ .data = .{0} ** size }; this  works with any constant
    return Self{ .data = .{value} ** size };
}

test "simple test" {
    var data = init(77);
    _ = data;
}

```
### Expected Behavior

Acceptable run/testing time behaviour

**Comment by Vexu** [comment]
Sema is generating a very big tuple and some extremely inefficient code for it, a workaround is to explicitly type the array `[_]u8{value} ** size`.

**Comment by mlugg** [comment]
We could handle this in the compiler by having `**` store its result type so that it knows to coerce the operand appropriately before expansion - I'll try that out later.
