### ISSUE TITLE
Build: issues with using `usize` to represent memory sizes

### ISSUE THREAD

**Issue by jacobly0** [ziglang/zig#17596]
When using QEMU's user mode to run a 32-bit program on a 64-bit host, `std.process.totalSystemMemoryLinux` reads the `/proc/meminfo` of the host system, meaning that trying to parse the contents as a `usize` can overflow.
```
$ qemu-arm zig build
thread 10641 panic: integer overflow
lib/std/process.zig:1233:22: 0x96c27 in totalSystemMemoryLinux (build)
    return kilobytes * 1024;
                     ^
lib/std/process.zig:1175:42: 0x84fa7 in totalSystemMemory (build)
            return totalSystemMemoryLinux() catch return error.UnknownTotalSystemMemory;
                                         ^
lib/build_runner.zig:321:48: 0x815ab in main (build)
        run.max_rss = process.totalSystemMemory() catch std.math.maxInt(usize);
                                               ^
lib/std/start.zig:583:37: 0x6f7eb in posixCallMainAndExit (build)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x0 in ??? (???)
```

Also a similar issue with using `usize` to represent `max_rss` in `build.zig`:
```
$ qemu-arm zig build
build.zig:516:10: error: type 'usize' cannot represent integer value '5029889638'
        .max_rss = 5029889638,
        ~^~~~~~~~~~~~~~~~~~~~
```

**Comment by andrewrk** [comment]
What an interesting problem to encounter. I suppose the fix of using a `u64` is straightforward enough.

**Comment by rootbeer** [comment]
Also, 32-bit x86 hosts (at least) can use PAE mode (https://serverfault.com/questions/3342/how-does-a-32-bit-machine-support-more-than-4-gb-of-ram) to take advantage of more than 32-bits (4GB) of physical memory.  For those hosts, the total physical memory can be up to 64GB (36-bits).

**Comment by RossComputerGuy** [comment]
I've come up with a simple PR, I wasn't sure what I should do about the max rss stuff so I truncated it.
