### ISSUE TITLE
[zig cc] Illegal Instruction via ud1l code generation

### ISSUE THREAD

**Issue by jkbonfield** [ziglang/zig#17591]
### Zig Version

0.10.0-dev.3523+4d7f5a191

### Steps to Reproduce and Observed Behavior

Platform is an Ubuntu linux running on Intel hardware.

A zig build of htscodecs without optimisation generates a ud1l instruction in the assembly, which then leads to illegal instruction errors.

```
git clone https://github.com/samtools/htscodecs
cd htscodecs
autoreconf -i
./configure CC="zig cc -mpopcnt" CFLAGS="-g" --disable-shared
make
./tests/rans4x16pr -t -o5 -c 0x0101 tests/dat/q8

Testing 1 blocks
Illegal instruction
```

In gdb we can see this:

```
(gdb) x/10ai $pc-14
   0x272f5f <transpose_and_copy+4655>:	add    %cl,(%rdi)
   0x272f61 <transpose_and_copy+4657>:	xchg   %eax,%esp
   0x272f62 <transpose_and_copy+4658>:	shll   $0xc8,(%rax)
   0x272f65 <transpose_and_copy+4661>:	test   $0x1,%al
   0x272f67 <transpose_and_copy+4663>:	jne    0x272f72 <transpose_and_copy+4674>
=> 0x272f6d <transpose_and_copy+4669>:	ud1    0x16(%eax),%eax
   0x272f72 <transpose_and_copy+4674>:	mov    -0x2f0(%rbp),%rax
   0x272f79 <transpose_and_copy+4681>:	mov    -0x2d8(%rbp),%rcx
   0x272f80 <transpose_and_copy+4688>:	mov    %rcx,(%rax)
   0x272f83 <transpose_and_copy+4691>:	mov    -0x18(%rbp),%rax
```

We can see this in the assembly created if we compile that one file:

```
$ cd htscodecs
# Without optimisation
$ zig cc -DHAVE_CONFIG_H -I. -I.. -msse4.1 -mssse3  -mpopcnt -Wall -g -O0 -S rANS_static32x16pr_sse4.c;grep -c ud1 rANS_static32x16pr_sse4.s
1739

# With optimisation
$ zig cc -DHAVE_CONFIG_H -I. -I.. -msse4.1 -mssse3  -mpopcnt -Wall -g -O1 -S rANS_static32x16pr_sse4.c;grep -c ud1 rANS_static32x16pr_sse4.s
0
```

I think it's something specific to the mix of -m options used in this code, maybe a mix up between front end code generation and backend conversion to native assembly.

I haven't yet been able to reproduce this on a smaller test case.

### Expected Behavior

I'd expect no explicit undefined instructions to be in the assembly output for the executed code path.

I am assuming these are generated as debugging traps, for the equivalent of compiler assert statements.  Ie "we should never get here, so a ud1 will report if it happens".  Unfortunately we are getting here.

**Comment by nektro** [comment]
https://github.com/ziglang/zig/wiki/FAQ#why-do-i-get-illegal-instruction-when-using-with-zig-cc-to-build-c-code

**Comment by jkbonfield** [comment]
Thank you.  I can confirm this is indeed undefined behaviour from a language perspective, but it is utilised for optimisation on this particular file given it's in an SSE4 specific file.  I'll close this as it's not a zig bug.
