### ISSUE TITLE
ld.lld error: undefined symbol: reallocarray

### ISSUE THREAD

**Issue by acarrico** [ziglang/zig#17607]
### Zig Version

0.12.0-dev.306+a0968be83

### Steps to Reproduce and Observed Behavior

```
]$ cat main.c
#define _DEFAULT_SOURCE 1
#define _GNU_SOURCE 1

#include <stdlib.h>

int main () {
  char* buffer = malloc(12);
  buffer = reallocarray(buffer, 1, 13);
  free(buffer);
}
```

This may or may not link, depending on the Zig version, etc:

```
$ ./zig-11 version
0.11.0

$ ./zig-12 version
0.12.0-dev.306+a0968be83

$ ./zig-12 cc -lc main.c
ld.lld: error: undefined symbol: reallocarray
>>> referenced by main.c:8
>>>               /home/acarrico/.cache/zig/o/3bc394cabb7b4314ac3135fa11f380c2/main.o:(main)

$ ./zig-11 cc -lc main.c
ld.lld: error: undefined symbol: reallocarray
>>> referenced by main.c:8
>>>               /home/acarrico/.cache/zig/o/25067a08a7699e4e9c5a4ac69ebc8c85/main.o:(main)

$ ./zig-12 cc -lc main.c --target=x86_64-linux-gnu
ld.lld: error: undefined symbol: reallocarray
>>> referenced by main.c:8
>>>               /home/acarrico/.cache/zig/o/cbc6b9a81ea2a088144021ffd58635b5/main.o:(main)

$ ./zig-12 cc -lc main.c --target=x86_64-linux-musl

$ ./zig-11 cc -lc main.c --target=x86_64-linux-gnu
ld.lld: error: undefined symbol: reallocarray
>>> referenced by main.c:8
>>>               /home/acarrico/.cache/zig/o/e42380168d6a5487bca5dd7cac83b81f/main.o:(main)

$ ./zig-11 cc -lc main.c --target=x86_64-linux-musl

$ ln -s ~/no-backup/zig-linux-x86_64-0.11.0-dev.1366+c70a3d902/zig zig-11-dev

$ ./zig-11-dev cc -lc main.c

$ ./zig-11-dev cc -lc main.c --target=x86_64-linux-musl

$ ./zig-11-dev cc -lc main.c --target=x86_64-linux-gnu
ld.lld: error: undefined symbol: reallocarray
>>> referenced by main.c:8
>>>               /home/acarrico/.cache/zig/o/d37587f0b76e20739639ab1a898c73df/main.o:(main)

$ nix-shell -p zig

[nix-shell]$ zig version
0.10.1

[nix-shell]$ zig cc -lc main.c

[nix-shell]$ zig cc -lc main.c --target=x86_64-linux-gnu
ld.lld: error: undefined symbol: reallocarray
>>> referenced by main.c:8
>>>               /home/acarrico/.cache/zig/o/daa499687d5d9e4c86360cc7a0fd8e66/main.o:(main)

[nix-shell]$ zig cc -lc main.c --target=x86_64-linux-musl

[nix-shell]$
```

### Expected Behavior

reallocarray should be available with ```-lc```. It seems particularly strange that it is missing under gnu, since I believe it has been there longer than in musl. It seems to be available in older versions without specifying a target (perhaps this is linking the system's libc?).

**Comment by rootbeer** [comment]
Reproduced at a recent build with the nice test case and examples. 

The musl library has a relatively simple definition for reallocarray() in stdlib.h:
```
void *reallocarray (void *, size_t, size_t);
```

The glibc one is more decorated, but basically the same.  Its protected by more ifdef guards, but since this is a linker error, not a compiler error those are not the problem:
```
#ifdef __USE_MISC
/* Re-allocate the previously allocated block in PTR, making the new
   block large enough for NMEMB elements of SIZE bytes each.  */
/* __attribute_malloc__ is not used, because if reallocarray returns
   the same pointer that was passed to it, aliasing needs to be allowed
   between objects pointed by the old and new pointers.  */
extern void *reallocarray (void *__ptr, size_t __nmemb, size_t __size)
     __THROW __attribute_warn_unused_result__
     __attribute_alloc_size__ ((2, 3))
    __attr_dealloc_free;
```

So this symbol isn't getting aliased by these header files.  Running zig cc with the `--verbose` flag shows a lot of the paths, so I can see the musl C library, and that it contains reallocarray:
```
$ readelf -a /home/pat/.cache/zig/o/04be21da3d4303ad1eb66e50d2e5d681/libc.a | grep reallocarray
File: /home/pat/.cache/zig/o/04be21da3d4303ad1eb66e50d2e5d681/libc.a(/home/pat/.cache/zig/o/0ec9fada3726da1642fa4efeb2d27d72/reallocarray.o)
Relocation section '.rela.text.reallocarray' at offset 0x718 contains 2 entries:
00000000001e  000200000001 R_X86_64_64       0000000000000000 .text.reallocarray + 0
00000000002b  000200000001 R_X86_64_64       0000000000000000 .text.reallocarray + 0
000000000075  000200000001 R_X86_64_64       0000000000000000 .text.reallocarray + 16
000000000082  000200000001 R_X86_64_64       0000000000000000 .text.reallocarray + 2c
000000000020  000200000001 R_X86_64_64       0000000000000000 .text.reallocarray + 0
000000000106  000200000001 R_X86_64_64       0000000000000000 .text.reallocarray + 0
     1: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS reallocarray.c
     2: 0000000000000000     0 SECTION LOCAL  DEFAULT    3 .text.reallocarray
     8: 0000000000000000    44 FUNC    GLOBAL DEFAULT    3 reallocarray
``

But the glibc library doesn't contain a reallocarray:
```
$ readelf -a /home/pat/.cache/zig/o/b21177ef9f0d6733da63c544a2d9b2a8/libc.so.6 | grep reallocarray
```

My local Debian glibc does contain reallocarray:
```
$ readelf -a /usr/lib/x86_64-linux-gnu/libc.a | grep reallocarray
File: /usr/lib/x86_64-linux-gnu/libc.a(reallocarray.o)
     2: 0000000000000000    33 FUNC    GLOBAL HIDDEN     1 __libc_reallocarray
     6: 0000000000000000    33 FUNC    WEAK   DEFAULT    1 reallocarray
```

So, the Zig glibc probably should contain this symbol....

I'm guessing this is fallout from the recent glibc upgrade.  I'll see if I can figure out why its missing.

One other hint, the glibc man page for reallocarray does say:

```
   Feature Test Macro Requirements for glibc (see feature_test_macros(7)):

       reallocarray():
           Since glibc 2.29:
               _DEFAULT_SOURCE
           glibc 2.28 and earlier:
               _GNU_SOURCE
```

**Comment by rootbeer** [comment]
Oh, it only fails for some versions of glibc.  Pass `-target  x86-linux-gnu.2.36` for example, and `reallocarray` is found.  (BTW, the fact that one can easily compile against N versions of glibc is pretty spectacular!)

The entry in Zig's glibc-ABI-tool at https://github.com/ziglang/glibc-abi-tool/blob/aeae11fbfae155524fd18035892384ac0b024441/glibc/2.38/sysdeps/unix/sysv/linux/x86_64/64/libc.abilist contains:
```
GLIBC_2.26 reallocarray F
```

And, the v2.25 file does not mention reallocarray (https://github.com/ziglang/glibc-abi-tool/blob/aeae11fbfae155524fd18035892384ac0b024441/glibc/2.25/sysdeps/unix/sysv/linux/x86_64/64/libc.abilist).

So either the Zig glibc header files need to hide the `reallocarray` symbol when they're being used for an older version of glibc.  Or maybe reallocarray should be visible in older versions of glibc?  I'll see if I can confirm when glibc introduced this symbol.

As a related aside, I'm sort of surprised that the default glibc is one of the ones older than 2.26.

**Comment by rootbeer** [comment]
reallocarray is from glibc 2.26: https://sourceware.org/git/?p=glibc.git;a=commit;h=2e0bbbfbf95fc9e22692e93658a6fbdd2d4554da  Thankfully the diff that adds it includes an entry in the NEWS file with the version number.

**Comment by rootbeer** [comment]
My suggested fix in #17610 turns the link error into a compile time error:
```
$ zig  cc main.c -target x86-linux-gnu
main.c:8:12: error: call to undeclared function 'reallocarray'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    8 |   buffer = reallocarray(buffer, 1, 13);
      |            ^
main.c:8:10: error: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
    8 |   buffer = reallocarray(buffer, 1, 13);
      |          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

The fix for your code is to use an explicit, later version of glibc:
```
$ zig cc main.c -target x86-linux-gnu.2.38
```

**Comment by acarrico** [comment]
... or maybe older versions of Zig were using musl. Anyway, it would be nice to see what libc version is getting used.

**Comment by acarrico** [comment]
This issue is essentially solved, but I'm going to add a little more context anyway. I don't know if it is at all actionable, but it may be useful to someone:

I noticed that this goes a little deeper. For example, ```zig build test``` may fail with the undefined symbol, but adding ```-Dtarget=x86-linux-gnu.2.37``` will just replace it with a different problem:
```
$ ../zig build test -Dtarget=x86-linux-gnu.2.37
run test: error: the host system is unable to execute binaries from the target
  because the host dynamic linker is '/nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/ld-linux-x86-64.so.2',
  while the target dynamic linker is '\0\0\0\0\0\0\0\08)F\0\0\0'.
  consider setting the dynamic linker or enabling skip_foreign_checks in the Run step
Build Summary: 1/3 steps succeeded; 1 failed (disable with --summary none)
test transitive failure
+- run test failure
error: the following build command failed with exit code 1:
/home/acarrico/src/acarrico/test2/zig-cache/o/8943b4cd001a1e736078045b9a4dbbdc/build /home/acarrico/no-backup/zig-linux-x86_64-0.12.0-dev.306+a0968be83/zig /home/acarrico/src/acarrico/test2 /home/acarrico/src/acarrico/test2/zig-cache /home/acarrico/.cache/zig test -Dtarget=x86-linux-gnu.2.37
```

The suggested fix (adding   ```run_main_tests.skip_foreign_checks=true;``` in build.zig) does work.

Why is the dynamic linker needed for the test runner? Why is it garbage? I don't know.

I did discover that adding cc to my PATH resolves the issue without ```skip_foreign_checks```.

So my take away here is that **prepackaged zig binaries aren't really standalone, they have a context dependency on ```cc``` in some situations**.

For reference here are the files:

Build.zig:

```
const std = @import("std");

pub fn build(b: *std.Build) void {
    const main_tests = b.addTest(.{
        .root_source_file = .{ .path = "main.zig" },
        .target = b.standardTargetOptions(.{}),
        .optimize = b.standardOptimizeOption(.{}),
        .link_libc = true
    });
    const run_main_tests = b.addRunArtifact(main_tests);
    //run_main_tests.skip_foreign_checks = true;
    const test_step = b.step("test", "Run library tests and unit tests");
    test_step.dependOn(&run_main_tests.step);
}
```

main.zig:

```
const std = @import("std");
const testing = std.testing;

pub extern fn malloc(__size: c_ulong) ?*anyopaque;
pub extern fn reallocarray(__ptr: ?*anyopaque, __nmemb: usize, __size: usize) ?*anyopaque;
pub extern fn free(__ptr: ?*anyopaque) void;

pub export fn test_reallocarray_linkage() void {
    var buffer: [*c]u8 = @as([*c]u8, @ptrCast(@alignCast(malloc(@as(c_ulong, @bitCast(@as(c_long, @as(c_int, 12))))))));
    buffer = @as([*c]u8, @ptrCast(@alignCast(reallocarray(@as(?*anyopaque, @ptrCast(buffer)), @as(usize, @bitCast(@as(c_long, @as(c_int, 1)))), @as(usize, @bitCast(@as(c_long, @as(c_int, 13))))))));
    free(@as(?*anyopaque, @ptrCast(buffer)));
}

test "basic add functionality" {
    test_reallocarray_linkage();
}
```

And I brought cc into scope with ```$nix-shell -p gcc```

**Comment by andrewrk** [comment]
> Why is it garbage?

this bug was resolved somewhere between your zig version and `0.12.0-dev.1138+530dc0405`. For me it prints
```
warning: the host system does not appear to be capable of executing binaries from the target because the host dynamic linker is '/nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/ld-linux-x86-64.so.2', while the target dynamic linker is '/lib/ld-linux.so.2'. Consider using '--dynamic-linker'
error: the following command failed to execve with 'FileNotFound':
/home/andy/.cache/zig/o/0e60bdf974bf673d1346478fbb68a474/hello
```

I checked out commit `a0968be83` (from your zig version output) and I spot the bug, which is no longer present in master branch.

> Why is the dynamic linker needed for the test runner?

A dynamic linker is needed for a dynamically linked executable. When you specify the target as `x86-linux-gnu.2.37` you are communicating to the compiler that the executable you are building is not intended to be run only on this machine that you are currently running on, but on *any* x86-linux machine that has glibc 2.37 or later. The standard dynamic linker path for this is `/lib/ld-linux.so.2`.

You are using NixOS which does not use a standard dynamic linker path. So you cannot run a cross-compiled binary without `patchelf`. You have probably already noticed this before when you try to download dynamically linked applications from various projects on the Internet.

> I did discover that adding cc to my PATH resolves the issue without `skip_foreign_checks`.

I think you are mistaken. `cc` will not be executed unless you are targeting the host system, in which case Zig will attempt to integrate with your system's C installation by default.

> So my take away here is that **prepackaged zig binaries aren't really standalone, they have a context dependency on `cc` in some situations**.

Incorrect.

**Comment by acarrico** [comment]
Thanks for the additional info @andrewrk, perhaps it isn't cc, but some environment variable which comes along with the NixOS gcc (or zig) package.

**Comment by acarrico** [comment]
@andrewrk, also, thank you for clarifying that the target version was specifying the intent to dynamically link to that version on the target. I was a bit hazy on this point, and may have been assuming that when specifying a version, as @rootbeer suggested, that Zig would statically link the specified version from various libc versions distributed with Zig. I now understand that it is telling Zig what to expect when dynamically linking libc on the target machine.

**Comment by andrewrk** [comment]
You might want to explore static linking instead - in this case I suggest giving the musl C ABI a shot. `-Dtarget=x86-linux-musl`. Unlike glibc, this target defaults to static linking. By the way x86 is 32-bits, while x86_64 is 64-bits.

**Comment by acarrico** [comment]
Ah, ok, so I wasn't completely insane. Good to know.
