### ISSUE TITLE
add format option `{xs}`/`{Xs}` to print u8 arrays as bytes

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#17611]
currently, `[]u8` can only be printed as either `{s}` or `{any}`, the latter being base-10.

It would be better if you can specify that the byte array be printed in hexadecimal instead.

**Comment by tauoverpi** [comment]
This used to be the case but was changed in favour of using `std.fmt.fmtSliceHex{Upper,Lower}`:

```zig
std.fmt.format("{s}", .{std.fmt.fmtSliceHexLower(&[_]u8{1, 2, 3, 15, 13, 12 })});
