### ISSUE TITLE
Incorrect packing of certain packed structs

### ISSUE THREAD

**Issue by sareneFactorial** [ziglang/zig#17647]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

Here is example code, tested on both 32 bit freestanding x86, and x86_64 Linux:

```
const std = @import("std");
pub const MyPackedStruct = packed struct {
    unrelated: u8 = 0xcb,
    evil_bytes: u4 = 0xa,
    incorrect: u20,
};

var test_var: MyPackedStruct = undefined;

pub fn main() void {
    var a: u32 = 0xffffffff;
    std.debug.print("pre-truncate: 0x{x}\n", .{a});

    var b: u20 = @truncate(a >> 12);
    
    std.debug.print("post-truncate: 0x{x}\n", .{b});

    test_var = MyPackedStruct {
        .incorrect = b,
    };
    std.debug.print("saved value: 0x{x}\n", .{test_var.incorrect});

    var bitcast: u32 = @bitCast(test_var);

    std.debug.print("bitcast to u32: 0x{x}\n", .{bitcast});
}
```

Here is the output:

```
pre-truncate: 0xffffffff
post-truncate: 0xfffff
saved value: 0xfffaf
bitcast to u32: 0xfffaf0cb
```

It appears that `evil_bytes` was placed in the wrong location during creation of the struct, leaving a gap of 0 where it should be, and its intended value in a different area. The values can be anything, from testing.

The `unrelated` field can be anything of 8 bytes in size. My initial use case was a boolean bitfield.

I tested with different sizes of all three sections, and no other sizes worked within u32, although this was not extensive.

The truncate is unrelated, and is there just to see step-by-step what was happening and where it went wrong.

### Expected Behavior

The saved value should have been `0xfffff` instead of `0xfffaf`, and the bitcast should have been `0xfffffacb`.

**Comment by rohlem** [comment]
Still reproduces for me on `0.12.0-dev.297+d2014fe97` (which is almost 1k commits behind already, I should update soon).

Interesting (potentially important) detail in case it isn't yet fixed on `master`:
The bug is particular to initializing a global variable.
Initializing a local variable, or copying from the local variable into the global, does not exhibit the same issue:

```zig
const std = @import("std");
pub const MyPackedStruct = packed struct(u32) {
    unrelated: u8 = 0xcb,
    evil_bytes: u4 = 0xa,
    incorrect: u20,
};

var test_var: MyPackedStruct = undefined;

pub fn main() void {
    var a: u32 = 0xffffffff;
    std.debug.print("pre-truncate: 0x{x}\n", .{a});

    var b: u20 = 0xfffff;
    test_var = MyPackedStruct{ .incorrect = b };
    std.debug.print("global: 0x{x}\n", .{@as(u32, @bitCast(test_var))});
    var local: MyPackedStruct = .{ .incorrect = b };
    std.debug.print("local : 0x{x}\n", .{@as(u32, @bitCast(local))});
    test_var = local;
    std.debug.print("l -> g: 0x{x}\n", .{@as(u32, @bitCast(test_var))});
}
//output on 0.12.0-dev.297+d2014fe97:
// global: 0xfffaf0cb
// local : 0xfffffacb
// l -> g: 0xfffffacb
```

**Comment by Vexu** [comment]
Works with `0.12.0-dev.987+877393d17`:
```
pre-truncate: 0xffffffff
post-truncate: 0xfffff
saved value: 0xfffff
bitcast to u32: 0xfffffacb
```
