### ISSUE TITLE
Range usage is inconsistent between `switch` and `for`

### ISSUE THREAD

**Issue by icylace** [ziglang/zig#17677]
### Zig Version

0.12.0-dev.1184+3f4df8529

### Steps to Reproduce and Observed Behavior

Currently, integer ranges with an inclusive upper bound (`...`) work in `switch` but not in `for`, and integer ranges with an exclusive upper bound (`..`) work in `for` but not in `switch`.

You can run the following test and it will successfully pass:

```zig
const expect = @import("std").testing.expect;

test "exhibit A" {
    const a = switch (0) { 0...5 => true, else => false };
    const b = x: for (0..5) |_| {} else break :x true;
    try expect(a == b);
}
```

However, you cannot even compile the following test:

```zig
const expect = @import("std").testing.expect;

test "exhibit B" {
    const a = switch (0) { 0..5 => true, else => false };
    const b = x: for (0...5) |_| {} else break :x true;
    try expect(a == b);
}
```

### Expected Behavior

I expect to be able to successfully run the "exhibit B" test and for it to pass.

**Comment by andrewrk** [comment]
working as designed. not open for drive-by language proposals.

**Comment by icylace** [comment]
Oh, I honestly thought it was a bug.
