### ISSUE TITLE
Autodoc: {The comments displayed by @cInclude in the IDE are garbled.}

### ISSUE THREAD

**Issue by jingsupo** [ziglang/zig#17680]
@cInclude(comptime path: []u8) void 

 
This function can only occur inside @cImport.
 
This appends #include &lt;$path&gt;\nto the c_import temporary buffer.

![image](https://github.com/ziglang/zig/assets/7351235/dfb0f80c-b5a7-444a-94e2-b33cdcfad793)

**Comment by BratishkaErik** [comment]
I don't think that langref.html was migrated to autodoc yet or that autodoc has IDE integration, is it perhaps ZLS?
