### ISSUE TITLE
Add option to allow json comments to std.json.ParseOptions

### ISSUE THREAD

**Issue by VisenDev** [ziglang/zig#17684]
I know core language proposals aren't currently being accepted, but this is a slight change to the standard library

The idea is to add functionality to `std.json` which will allow the parsing of json files with comments. This could be accomplished either thru a `stripComments` function, or as an option to be passed into `std.json.ParseOptions`

**Comment by lsculv** [comment]
The [JSON standard](https://datatracker.ietf.org/doc/html/rfc8259) does not support comments, only certain extensions do, most notably [JSON5](https://json5.org/). It could be possible to add this as another json parser or in `std.json.ParseOptions`. It seems to me like the core json parser wants to stay compliant as far as possible to the RFC 8259 spec, as [noted in the top comment in `std.json.scanner`](https://github.com/ziglang/zig/blob/f30ab46306d7d137ed70bbcb3466c27846833ed3/lib/std/json/scanner.zig#L1)
