### ISSUE TITLE
`union( _ )` for inferred tagged union instead of `union(enum)`

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#17693]
Akin to how `[_]<type>{ <stuff> }` infers array size, since the bracket of `union(<type>)` would only ever be used to accept enum types, I think it makes more sense to continue the pattern with the inference symbol rather than the strange exception of having a keyword appear in where a concrete type is expected.

```zig
const tagged = union(_) {
    a: i32,
    b: bool,
    c: u8,
};
const arr = [_]u8{ '1' , '2' , '3' };
```

**Comment by rohlem** [comment]
Note that explicitly sizing the `enum` is also allowed, as in `union(enum(u4)) {...}`.
That would be less regular coming from `_`.
