### ISSUE TITLE
wrapping negation -% should work on unsigned ints

### ISSUE THREAD

**Issue by thejoshwolfe** [ziglang/zig#1770]
This is used in C in these algorithms: http://www.pcg-random.org/posts/bounded-rands.html (search for "-range").

Semantics:

```zig
const U = u32;
const I = i32;
var u: U = foo();
assert(-%u == @bitCast(U, -%@bitCast(I, u)));
assert(-%u == ~u +% 1);
```

I'm trying to port this code to Zig, and the workarounds with `@bitCast` or `~` obscure the origin and intent of the code.

**Comment by andrewrk** [comment]
I'm not convinced. Everywhere else in Zig, operations such as negation refer to the mathematical meaning, not a bitwise interpretation. Negation of an unsigned integer does not make sense mathematically. The `@bitCast` code above makes it clear.

I will re-open this issue if a counter-argument is provided.

**Comment by daurnimator** [comment]
> Negation of an unsigned integer does not make sense mathematically

`-%u` should be equivalent to `0 -% u`.

**Comment by andrewrk** [comment]
OK, when you put it that way, it makes sense, and I agree.
