### ISSUE TITLE
Unable to find 'test.zig' when testing std post-install

### ISSUE THREAD

**Issue by suirad** [ziglang/zig#1771]
While I was preparing to hack on my installed std for another issue, I decided to run tests on the std post-install to see if it could be used to check my work.

This was the error I received when running `zig test os/index.zig` from `std/`:
```rust
C:\Program Files\Zig\lib\zig\std\os\index.zig:18:9: error: unable to find 'test.zig'
    _ = @import("test.zig");
        ^
```

I tried changing `test.zig` to `test` and it had the same result.
 I was able to make it run all the tests by just commenting out that line.

---
This also lead me to try running `zig test index.zig` from std itself; which resulted in:
```rust
C:\Program Files\Zig\lib\zig\std\io.zig:682:13: error: unable to find 'io_test.zig'
        _ = @import("io_test.zig");
            ^
C:\Program Files\Zig\lib\zig\std\crypto\blake2.zig:6:15: error: unable to find 'test.zig'
const htest = @import("test.zig");
              ^
C:\Program Files\Zig\lib\zig\std\crypto\hmac.zig:72:15: error: unable to find 'test.zig'
const htest = @import("test.zig");
              ^
C:\Program Files\Zig\lib\zig\std\crypto\md5.zig:240:15: error: unable to find 'test.zig'
const htest = @import("test.zig");
              ^
C:\Program Files\Zig\lib\zig\std\crypto\sha1.zig:266:15: error: unable to find 'test.zig'
const htest = @import("test.zig");
              ^
C:\Program Files\Zig\lib\zig\std\crypto\sha2.zig:6:15: error: unable to find 'test.zig'
const htest = @import("test.zig");
              ^
C:\Program Files\Zig\lib\zig\std\crypto\sha3.zig:6:15: error: unable to find 'test.zig'
const htest = @import("test.zig");
              ^
C:\Program Files\Zig\lib\zig\std\zig\parse.zig:3461:9: error: unable to find 'parser_test.zig'
    _ = @import("parser_test.zig");
        ^
```
Just as before I tried commenting them all out and led me down a rabbit hole of trying to find `test.zig` and figuring out if `assertEqualHash` and `assertEqual` are part of the std.
I had a similar result on linux.

**Comment by andrewrk** [comment]
We don't ship std lib test files. You need a source checkout to run std lib tests.
