### ISSUE TITLE
investigate handling of windows file paths which are invalid utf-16le

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1774]
Thanks to @daurnimator for pointing this out on #1773 
According to https://simonsapin.github.io/wtf-8/, Windows file paths are not necessarily valid utf-16le. When using Windows APIs the zig standard library should not panic or return an encoding error when encountering such file paths.

Zig's cross platform file system abstractions must handle this, plus unix file paths which are null terminated byte arrays.

Potentially we could decode into WTF-8 rather than UTF-8 on Windows, however then it may become subtle to know what kind of operations are allowed on file paths. For example, the algorithm for concatenation is different for each encoding.

Related: #534

**Comment by daurnimator** [comment]
I wonder if we just need a type "FilePath" that is distinct from `[]u8` that way we don't do needless conversions if you're going from e.g. a directory iterator to opening files.
Though I'm afraid `FilePath` might end up being a middling solution that makes things more difficult while leaving some corner cases unhandled. e.g. I think different filesystems have different limitations: some are case insensitive, windows will blow up if you use the non \\??\ syntax and use filenames like NUL
