### ISSUE TITLE
Union payload PTR in switch clobbers data at runtime

### ISSUE THREAD

**Issue by xdBronch** [ziglang/zig#17754]
### Zig Version

0.12.0-dev.1261+bb0419599

### Steps to Reproduce and Observed Behavior

```zig
const Foo = union(enum) {
    a: u32,
    b: usize,
};
var list = std.MultiArrayList(Foo){};
try list.append(std.heap.page_allocator, .{ .a = 69 });
switch (list.get(0)) {
    .b, .a => |ab| std.debug.print("{}\n", .{ab}),
}
```
instead of printing 69 this prints a random massive number e.g. 140376711102533 because `@TypeOf(ab)` is usize so you get a bunch of random garbage before the 32 bits of `a` representing 69

### Expected Behavior

this should be a compile error without marking the switch case as `inline` due to the types being different

**Comment by mlugg** [comment]
This is meant to work by using PTR to unify the types whilst preserving the correct value - that is, this should compile and print `69`. I presume Sema is wrongly trying to use an in-memory coercion.
