### ISSUE TITLE
Windows handles -- `*anyopaque` or `*opaque{}` ?

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#17765]
https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types

There are some instances of certain handle types referring to not just an exclusive opaque type but rather a number of different ones.

For example [`HGDIOBJ` could be any of `HBITMAP`, `HBRUSH`, `HFONT`, `HPEN`, and `HRGN`.](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-selectobject)

In this case, should `HGDIOBJ` just be defined as `*anyopaque` while the specific ones each instantiate their own opaque type?

**Comment by Arnau478** [comment]
From https://ziglang.org/documentation/master/#opaque:
> `opaque {}` declares a new type with an unknown (but non-zero) size and alignment

In your case, if I understand correctly, you would want to use `opaque {}` to define the opaque types, and `*opaque{}` for a pointer to it. You could use `*anyopaque` for function parameters, but I don't think that would be necessary.

It's pretty hard to help you without any code, but I'm also thinking you may not need to define opaque types at all. You could just do something like this and let the C interop do it for you:
```zig
const c = @cImport({
    @cInclude("WinDef.h");
});

pub fn foo(bar: c.BYTE) void {
    // ...
}
```

**Comment by Arnau478** [comment]
> No no, what I meant is, should the std instantiate strongly typed opaques, or should it just *anyopaque any handles Willy-nilly?

I don't quite get what you mean. `*anyopaque` should only be used kind of like "this is a pointer to something, but I don't care nor depend on what that something is".

Sorry if that's not what you meant. Could you provide some code that has the issue you mentioned?

**Comment by Arnau478** [comment]
> how should the std handle cases where one handle type actually refers to a small set of multiple unique opaque types?

Well, by definition, an opaque is anything, so yeah, it could be done. But it would lead to bad code practices. The point of having multiple opaques is to have some constraints on what can and what cannot be that type. If you use an opaque to represent what could be multiple things, you're missing the point. For that you should use anyopaque. So yeah, I guess you could do it, but there's no point in doing so.

**Comment by Arnau478** [comment]
> or a union of opaques?

A union of opaques is not an opaque on it's own. I'm also pretty sure that you cannot create a union of opaques, as opaques are of unknown size. You could create a union of pointers to opaques, but that has a completely different meaning.

**Comment by Arnau478** [comment]
That would work, but I don't think that's what you want. That way, `HGDIOBJ` is not even a pointer. Maybe using `extern union` (as you're doing on that piece of code) would make it work, but it feels like an anti-pattern. Plus, what's the downside of just using `*anyopaque`s in that scenario?

**Comment by andrewrk** [comment]
It should be `opaque{}` and you should use pointer casts to get to the other types. The subclasses can have a method called `toHandle()` that relaxes the type.
