### ISSUE TITLE
error: unable to unpack tarball to temporary directory: TarComponentsOutsideStrippedPrefix

### ISSUE THREAD

**Issue by theoparis** [ziglang/zig#17779]
### Zig Version

0.12.0 (gentoo 9999 version)

### Steps to Reproduce and Observed Behavior

/home/theo/chromium/build.zig.zon:10:20: error: unable to unpack tarball to temporary directory: TarComponentsOutsideStrippedPrefix
            .url = "https://chromium.googlesource.com/chromium/tools/depot_tools.git/+archive/refs/heads/main.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

It seems like there may need to be some kind of way to set [strip_components](https://github.com/ziglang/zig/blob/fa022d1ecc148280a3b6e95312087b4e8c0c6166/src/Package/Fetch.zig#L1085) here.

### Expected Behavior

The zig package manager should succesfully download depot_tools.

**Comment by theoparis** [comment]
I'm not sure if this should be a separate issue but using a chromium source repository with `git+https` instead results in
![image](https://github.com/ziglang/zig/assets/11761863/c1dd029d-c20c-4873-9910-71c64a7a2bf5)

**Comment by ianprime0509** [comment]
Running `curl -H 'Git-Protocol: version=2' --output - https://boringssl.googlesource.com/boringssl/info/refs?service=git-upload-pack`, it looks like the Git server does actually support protocol v2, but the difference is it isn't including the LF characters which are indicated to appear at the end of certain packets in the [protocol v2 spec](https://git-scm.com/docs/protocol-v2#_capability_advertisement).

However, despite what the grammar in the protocol-v2 documentation suggests, this doesn't seem to be a bug in Google's Git server: in the [protocol-common documentation](https://git-scm.com/docs/protocol-common#_pkt_line_format) there is a note about this:

> A non-binary line SHOULD BE terminated by an LF, which if present MUST be included in the total length. Receivers MUST treat pkt-lines with non-binary data the same whether or not they contain the trailing LF (stripping the LF if present, and not complaining when it is missing).

That means that all pkt-line handling involving textual content should be updated to be tolerant of a missing LF at the end: https://github.com/ziglang/zig/blob/e72049bc61eedd2b7381b87b530428a83581cafe/src/Package/Fetch/git.zig#L557 This shouldn't be too difficult to fix.

In any case, though, this is definitely a distinct issue from your original (which has to do with `strip_components`, as you noted).

**Comment by ianprime0509** [comment]
I opened #17974 for the second issue reported here.

**Comment by hazeycode** [comment]
Also running into this with https://zig-gamedev-pkgs.ams3.cdn.digitaloceanspaces.com/zmath-0.9.6.tar.gz

Tarball created on macOS using `tar -czvf zmath-0.9.6.tar.gz -C libs/zmath .`

Zig version 0.12.0-dev.1871+e426ae43a
