### ISSUE TITLE
Function argument declarations are self-referencable but order-dependent

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#17787]
Tested on :
- 0.11.0
- 0.12.0-dev.1344+37295696e

 
This (somewhow) works:

```zig
const std = @import("std");

pub fn main() void {
    const vec = [_]f64{1,2,3,4,5};
    const res = add1(5,vec);
    std.log.debug("{any}",.{res});
}

fn add1(comptime n: usize, vec: [n]f64) [n+1]f64 {
    return vec ++ .{69};
}
```

This does not work:

```zig
const std = @import("std");

pub fn main() void {
    const vec = [_]f64{1,2,3,4,5};
    const res = add1_fail(vec,5);
    std.log.debug("{any}",.{res});
}

// n referenced before it's defined
fn add1_fail(vec: [n]f64, comptime n: usize) [n+1]f64 {
    return vec ++ .{69};
}
```

I don't think it's makes sense that one works while the other don't. They should either be both valid or both invalid

**Comment by mlugg** [comment]
Working as designed. Only parameters prior to the current one are in scope when evaluating a parameter's type. Changing this would introduce arbitrary dependencies between parameters, making the order of argument evaluation at call sites necessarily ambiguous (whereas it is currently simply left-to-right) and sometimes unresolvable (e.g. `fn f(a: @TypeOf(b), b: @TypeOf(a)) void`).
