### ISSUE TITLE
Change symbol for inclusive range (`...`) to keyword `to` to disambiguate from open range (`..`), and change ranged `for` to use inclusive ranges

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#17784]
current: 

|usage|`a..`|`a..b`|`a...b`|
|:-:|:-:|:-:|:-:|
|`switch`|no|no|yes|
|ranged `for`|no|yes|no|
|indexed `for`|yes|yes|no|
|slice|yes|yes|no|

proposed:

|usage|`a..`|`a..b`|(`a to b`)|
|:-:|:-:|:-:|:-:|
|`switch`|no|no|yes|
|ranged `for`|no|(no)|(yes)|
|indexed `for`|yes|(no)|no|
|`slice`|yes|yes|no|

Since ranged `for` do not permit unbounded ranges, there is no reason to use a syntax that allows it.

```zig
switch(a) {
    0 to 10 => {
        // top ten
    },
    69 => {
        // nice
    },
    else => {
        if(a<100} {
            // inside ranking
        } else {
            // outside ranking
        }
    },
}

for(0 to 10) {
    // 11 steps executed
}

for(items, 0..) |item, i| {
    // iterate all
}

for(items[2..9], 10..) |item, i| {
    // item[2] , 10
    // item[3] , 11
    // etc
}
```

**Comment by andrewrk** [comment]
Not interested in language proposals
