### ISSUE TITLE
Pakced Struct size mismatch

### ISSUE THREAD

**Issue by kingofknights** [ziglang/zig#17804]
### Zig Version

0.12.0-dev.1124+ec21da0d5

### Steps to Reproduce and Observed Behavior

https://godbolt.org/z/vTPKKfcWz

### Expected Behavior

One of them should have returned the size of 12
instead both are of 16

**Comment by IntegratedQuantum** [comment]
Try `@bitSizeOf` which should be 96 for both of them.
`@sizeOf` for your packed structs is 16 for the same reasons that `@sizeOf(u96)` is 16.

**Comment by rohlem** [comment]
`@sizeOf` returns the number of bytes of the "store size" / access size the compiler decides for a type (up to the backend & target configuration).
The backing type has been deduced as `u96` (= 12 bytes of 8 bits), and you can verify for yourself that the access size `@sizeOf(u96)` is also produced as `16` on `x86_64`.
(Note that you can also explicitly specify the backing type, f.e. `packed struct (u96) {...}`, to make sure this meets your expectations.)
If you're instead interested in the exact size, use `@bitSizeOf` (which returns 96 for both `u96` and both of your `packed struct`s.)

**Comment by kingofknights** [comment]
So how once can define pragma pack(1) so that it should retain 12bytes

**Comment by kcbanner** [comment]
You can use an extern struct, with align(1) fields to accomplish that:

```zig
pub const S = extern struct {
    first: u32 align(1),
    second: u64 align(1),
};

test {
    @compileLog(@sizeOf(S));
}
```

```
Compile Log Output:
@as(comptime_int, 12)
```

**Comment by kingofknights** [comment]
\closed
