### ISSUE TITLE
Unable to build latest master

### ISSUE THREAD

**Issue by tmlbl** [ziglang/zig#17823]
### Zig Version

master

### Steps to Reproduce and Observed Behavior

I have not been able to build from source on one of my machines since the move to llvm-17, not sure what is happening because the error doesn't really give any information
```
[ 94%] Built target zig2
[100%] Building stage3
zig build-exe zig Debug native: error: the following command terminated unexpectedly:
/home/tim/oss/zig/build/zig2 build-exe --stack 33554432 /home/tim/oss/zig/src/main.zig /home/tim/oss/zig/build/zigcpp/libzigcpp.a /home/tim/local/llvm17-release/lib/libclangFrontendTool.a /home/tim/local/llvm17-release/lib/libclangCodeGen.a /home/tim/local/llvm17-release/lib/libclangFrontend.a /home/tim/local/llvm17-release/lib/libclangDriver.a /home/tim/local/llvm17-release/lib/libclangSerialization.a /home/tim/local/llvm17-release/lib/libclangSema.a /home/tim/local/llvm17-release/lib/libclangStaticAnalyzerFrontend.a /home/tim/local/llvm17-release/lib/libclangStaticAnalyzerCheckers.a /home/tim/local/llvm17-release/lib/libclangStaticAnalyzerCore.a /home/tim/local/llvm17-release/lib/libclangAnalysis.a /home/tim/local/llvm17-release/lib/libclangASTMatchers.a /home/tim/local/llvm17-release/lib/libclangAST.a /home/tim/local/llvm17-release/lib/libclangParse.a /home/tim/local/llvm17-release/lib/libclangSema.a /home/tim/local/llvm17-release/lib/libclangBasic.a /home/tim/local/llvm17-release/lib/libclangEdit.a /home/tim/local/llvm17-release/lib/libclangLex.a /home/tim/local/llvm17-release/lib/libclangARCMigrate.a /home/tim/local/llvm17-release/lib/libclangRewriteFrontend.a /home/tim/local/llvm17-release/lib/libclangRewrite.a /home/tim/local/llvm17-release/lib/libclangCrossTU.a /home/tim/local/llvm17-release/lib/libclangIndex.a /home/tim/local/llvm17-release/lib/libclangToolingCore.a /home/tim/local/llvm17-release/lib/libclangExtractAPI.a /home/tim/local/llvm17-release/lib/libclangSupport.a /home/tim/local/llvm17-release/lib/liblldMinGW.a /home/tim/local/llvm17-release/lib/liblldELF.a /home/tim/local/llvm17-release/lib/liblldCOFF.a /home/tim/local/llvm17-release/lib/liblldWasm.a /home/tim/local/llvm17-release/lib/liblldMachO.a /home/tim/local/llvm17-release/lib/liblldCommon.a -lLLVMWindowsManifest -lLLVMXRay -lLLVMLibDriver -lLLVMDlltoolDriver -lLLVMCoverage -lLLVMLineEditor -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMX86TargetMCA -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMX86Desc -lLLVMX86Info -lLLVMWebAssemblyDisassembler -lLLVMWebAssemblyAsmParser -lLLVMWebAssemblyCodeGen -lLLVMWebAssemblyUtils -lLLVMWebAssemblyDesc -lLLVMWebAssemblyInfo -lLLVMVEDisassembler -lLLVMVEAsmParser -lLLVMVECodeGen -lLLVMVEDesc -lLLVMVEInfo -lLLVMSystemZDisassembler -lLLVMSystemZAsmParser -lLLVMSystemZCodeGen -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSparcDisassembler -lLLVMSparcAsmParser -lLLVMSparcCodeGen -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMRISCVTargetMCA -lLLVMRISCVDisassembler -lLLVMRISCVAsmParser -lLLVMRISCVCodeGen -lLLVMRISCVDesc -lLLVMRISCVInfo -lLLVMPowerPCDisassembler -lLLVMPowerPCAsmParser -lLLVMPowerPCCodeGen -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMMSP430Disassembler -lLLVMMSP430AsmParser -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMipsDisassembler -lLLVMMipsAsmParser -lLLVMMipsCodeGen -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMLoongArchDisassembler -lLLVMLoongArchAsmParser -lLLVMLoongArchCodeGen -lLLVMLoongArchDesc -lLLVMLoongArchInfo -lLLVMLanaiDisassembler -lLLVMLanaiCodeGen -lLLVMLanaiAsmParser -lLLVMLanaiDesc -lLLVMLanaiInfo -lLLVMHexagonDisassembler -lLLVMHexagonCodeGen -lLLVMHexagonAsmParser -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMBPFDisassembler -lLLVMBPFAsmParser -lLLVMBPFCodeGen -lLLVMBPFDesc -lLLVMBPFInfo -lLLVMAVRDisassembler -lLLVMAVRAsmParser -lLLVMAVRCodeGen -lLLVMAVRDesc -lLLVMAVRInfo -lLLVMARMDisassembler -lLLVMARMAsmParser -lLLVMARMCodeGen -lLLVMARMDesc -lLLVMARMUtils -lLLVMARMInfo -lLLVMAMDGPUTargetMCA -lLLVMAMDGPUDisassembler -lLLVMAMDGPUAsmParser -lLLVMAMDGPUCodeGen -lLLVMAMDGPUDesc -lLLVMAMDGPUUtils -lLLVMAMDGPUInfo -lLLVMAArch64Disassembler -lLLVMAArch64AsmParser -lLLVMAArch64CodeGen -lLLVMAArch64Desc -lLLVMAArch64Utils -lLLVMAArch64Info -lLLVMOrcJIT -lLLVMWindowsDriver -lLLVMMCJIT -lLLVMJITLink -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMOrcTargetProcess -lLLVMOrcShared -lLLVMDWP -lLLVMDebugInfoLogicalView -lLLVMDebugInfoGSYM -lLLVMOption -lLLVMObjectYAML -lLLVMObjCopy -lLLVMMCA -lLLVMMCDisassembler -lLLVMLTO -lLLVMPasses -lLLVMCFGuard -lLLVMCoroutines -lLLVMipo -lLLVMVectorize -lLLVMLinker -lLLVMInstrumentation -lLLVMFrontendOpenMP -lLLVMFrontendOpenACC -lLLVMFrontendHLSL -lLLVMExtensions -lLLVMDWARFLinkerParallel -lLLVMDWARFLinker -lLLVMGlobalISel -lLLVMMIRParser -lLLVMAsmPrinter -lLLVMSelectionDAG -lLLVMCodeGen -lLLVMTarget -lLLVMObjCARCOpts -lLLVMCodeGenTypes -lLLVMIRPrinter -lLLVMInterfaceStub -lLLVMFileCheck -lLLVMFuzzMutate -lLLVMScalarOpts -lLLVMInstCombine -lLLVMAggressiveInstCombine -lLLVMTransformUtils -lLLVMBitWriter -lLLVMAnalysis -lLLVMProfileData -lLLVMSymbolize -lLLVMDebugInfoBTF -lLLVMDebugInfoPDB -lLLVMDebugInfoMSF -lLLVMDebugInfoDWARF -lLLVMObject -lLLVMTextAPI -lLLVMMCParser -lLLVMIRReader -lLLVMAsmParser -lLLVMMC -lLLVMDebugInfoCodeView -lLLVMBitReader -lLLVMFuzzerCLI -lLLVMCore -lLLVMRemarks -lLLVMBitstreamReader -lLLVMBinaryFormat -lLLVMTargetParser -lLLVMTableGen -lLLVMSupport -lLLVMDemangle -lz /usr/lib/gcc/x86_64-linux-gnu/11/libstdc++.a -lunwind -lc --cache-dir /home/tim/oss/zig/zig-cache --global-cache-dir /home/tim/.cache/zig --name zig --mod aro::/home/tim/oss/zig/deps/aro/lib.zig --mod build_options::/home/tim/oss/zig/zig-cache/c/197acdda9a41bf83a98f96eb0ebf1440/options.zig --deps aro,build_options -I /home/tim/local/llvm17-release/include -I /home/tim/local/llvm17-release/include -L /home/tim/local/llvm17-release/lib -L /home/tim/local/llvm17-release/lib -I /home/tim/local/llvm17-release/include --zig-lib-dir /home/tim/oss/zig/lib --listen=- 
Build Summary: 2/5 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install zig transitive failure
   └─ zig build-exe zig Debug native failure
error: the following build command failed with exit code 1:
/home/tim/oss/zig/zig-cache/o/e7323d337e132c668fbb67dbb56748ec/build /home/tim/oss/zig/build/zig2 /home/tim/oss/zig /home/tim/oss/zig/zig-cache /home/tim/.cache/zig --seed 0xd498404d --prefix /home/tim/oss/zig/build/stage3 --zig-lib-dir /home/tim/oss/zig/lib -Dconfig_h=/home/tim/oss/zig/build/config.h -Denable-llvm -Dno-langref -Dno-autodocs -Dtarget=native -Dcpu=native -Dversion-string=0.12.0-dev.1383+7c5d01b95
make[2]: *** [CMakeFiles/stage3.dir/build.make:73: stage3/bin/zig] Error 1
make[1]: *** [CMakeFiles/Makefile2:196: CMakeFiles/stage3.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
I am on recent Ubuntu
```
tim@xps > uname -a
Linux xps 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
tim@xps > gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
```
I have tried cleaning out the build directory and zig-cache, but still have not been able to build

### Expected Behavior

stage3 build completes successfully

**Comment by andrewrk** [comment]
I will re-open if you provide steps to reproduce. You are missing the commands that you ran, and how you obtained LLVM.

**Comment by tmlbl** [comment]
Sorry, LLVM was built from source:

**Comment by nektro** [comment]
what do you get running `/home/tim/oss/zig/zig-cache/o/e7323d337e132c668fbb67dbb56748ec/build /home/tim/oss/zig/build/zig2 /home/tim/oss/zig /home/tim/oss/zig/zig-cache /home/tim/.cache/zig --seed 0xd498404d --prefix /home/tim/oss/zig/build/stage3 --zig-lib-dir /home/tim/oss/zig/lib -Dconfig_h=/home/tim/oss/zig/build/config.h -Denable-llvm -Dno-langref -Dno-autodocs -Dtarget=native -Dcpu=native -Dversion-string=0.12.0-dev.1383+7c5d01b95` outside of make?

**Comment by tmlbl** [comment]
I had tried that and got the same output, "the following command terminated unexpectedly" for the zig2 build-exe command

**Comment by andrewrk** [comment]
what happens if you run that following command in a debugger? can you get a stack trace?

**Comment by nektro** [comment]
sorry, `/home/tim/oss/zig/build/zig2 build-exe --stack 33554432 /home/tim/oss/zig/src/main.zig /home/tim/oss/zig/build/zigcpp/libzigcpp.a /home/tim/local/llvm17-release/lib/libclangFrontendTool.a /home/tim/local/llvm17-release/lib/libclangCodeGen.a /home/tim/local/llvm17-release/lib/libclangFrontend.a /home/tim/local/llvm17-release/lib/libclangDriver.a /home/tim/local/llvm17-release/lib/libclangSerialization.a /home/tim/local/llvm17-release/lib/libclangSema.a /home/tim/local/llvm17-release/lib/libclangStaticAnalyzerFrontend.a /home/tim/local/llvm17-release/lib/libclangStaticAnalyzerCheckers.a /home/tim/local/llvm17-release/lib/libclangStaticAnalyzerCore.a /home/tim/local/llvm17-release/lib/libclangAnalysis.a /home/tim/local/llvm17-release/lib/libclangASTMatchers.a /home/tim/local/llvm17-release/lib/libclangAST.a /home/tim/local/llvm17-release/lib/libclangParse.a /home/tim/local/llvm17-release/lib/libclangSema.a /home/tim/local/llvm17-release/lib/libclangBasic.a /home/tim/local/llvm17-release/lib/libclangEdit.a /home/tim/local/llvm17-release/lib/libclangLex.a /home/tim/local/llvm17-release/lib/libclangARCMigrate.a /home/tim/local/llvm17-release/lib/libclangRewriteFrontend.a /home/tim/local/llvm17-release/lib/libclangRewrite.a /home/tim/local/llvm17-release/lib/libclangCrossTU.a /home/tim/local/llvm17-release/lib/libclangIndex.a /home/tim/local/llvm17-release/lib/libclangToolingCore.a /home/tim/local/llvm17-release/lib/libclangExtractAPI.a /home/tim/local/llvm17-release/lib/libclangSupport.a /home/tim/local/llvm17-release/lib/liblldMinGW.a /home/tim/local/llvm17-release/lib/liblldELF.a /home/tim/local/llvm17-release/lib/liblldCOFF.a /home/tim/local/llvm17-release/lib/liblldWasm.a /home/tim/local/llvm17-release/lib/liblldMachO.a /home/tim/local/llvm17-release/lib/liblldCommon.a -lLLVMWindowsManifest -lLLVMXRay -lLLVMLibDriver -lLLVMDlltoolDriver -lLLVMCoverage -lLLVMLineEditor -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMX86TargetMCA -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMX86Desc -lLLVMX86Info -lLLVMWebAssemblyDisassembler -lLLVMWebAssemblyAsmParser -lLLVMWebAssemblyCodeGen -lLLVMWebAssemblyUtils -lLLVMWebAssemblyDesc -lLLVMWebAssemblyInfo -lLLVMVEDisassembler -lLLVMVEAsmParser -lLLVMVECodeGen -lLLVMVEDesc -lLLVMVEInfo -lLLVMSystemZDisassembler -lLLVMSystemZAsmParser -lLLVMSystemZCodeGen -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSparcDisassembler -lLLVMSparcAsmParser -lLLVMSparcCodeGen -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMRISCVTargetMCA -lLLVMRISCVDisassembler -lLLVMRISCVAsmParser -lLLVMRISCVCodeGen -lLLVMRISCVDesc -lLLVMRISCVInfo -lLLVMPowerPCDisassembler -lLLVMPowerPCAsmParser -lLLVMPowerPCCodeGen -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMMSP430Disassembler -lLLVMMSP430AsmParser -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMipsDisassembler -lLLVMMipsAsmParser -lLLVMMipsCodeGen -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMLoongArchDisassembler -lLLVMLoongArchAsmParser -lLLVMLoongArchCodeGen -lLLVMLoongArchDesc -lLLVMLoongArchInfo -lLLVMLanaiDisassembler -lLLVMLanaiCodeGen -lLLVMLanaiAsmParser -lLLVMLanaiDesc -lLLVMLanaiInfo -lLLVMHexagonDisassembler -lLLVMHexagonCodeGen -lLLVMHexagonAsmParser -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMBPFDisassembler -lLLVMBPFAsmParser -lLLVMBPFCodeGen -lLLVMBPFDesc -lLLVMBPFInfo -lLLVMAVRDisassembler -lLLVMAVRAsmParser -lLLVMAVRCodeGen -lLLVMAVRDesc -lLLVMAVRInfo -lLLVMARMDisassembler -lLLVMARMAsmParser -lLLVMARMCodeGen -lLLVMARMDesc -lLLVMARMUtils -lLLVMARMInfo -lLLVMAMDGPUTargetMCA -lLLVMAMDGPUDisassembler -lLLVMAMDGPUAsmParser -lLLVMAMDGPUCodeGen -lLLVMAMDGPUDesc -lLLVMAMDGPUUtils -lLLVMAMDGPUInfo -lLLVMAArch64Disassembler -lLLVMAArch64AsmParser -lLLVMAArch64CodeGen -lLLVMAArch64Desc -lLLVMAArch64Utils -lLLVMAArch64Info -lLLVMOrcJIT -lLLVMWindowsDriver -lLLVMMCJIT -lLLVMJITLink -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMOrcTargetProcess -lLLVMOrcShared -lLLVMDWP -lLLVMDebugInfoLogicalView -lLLVMDebugInfoGSYM -lLLVMOption -lLLVMObjectYAML -lLLVMObjCopy -lLLVMMCA -lLLVMMCDisassembler -lLLVMLTO -lLLVMPasses -lLLVMCFGuard -lLLVMCoroutines -lLLVMipo -lLLVMVectorize -lLLVMLinker -lLLVMInstrumentation -lLLVMFrontendOpenMP -lLLVMFrontendOpenACC -lLLVMFrontendHLSL -lLLVMExtensions -lLLVMDWARFLinkerParallel -lLLVMDWARFLinker -lLLVMGlobalISel -lLLVMMIRParser -lLLVMAsmPrinter -lLLVMSelectionDAG -lLLVMCodeGen -lLLVMTarget -lLLVMObjCARCOpts -lLLVMCodeGenTypes -lLLVMIRPrinter -lLLVMInterfaceStub -lLLVMFileCheck -lLLVMFuzzMutate -lLLVMScalarOpts -lLLVMInstCombine -lLLVMAggressiveInstCombine -lLLVMTransformUtils -lLLVMBitWriter -lLLVMAnalysis -lLLVMProfileData -lLLVMSymbolize -lLLVMDebugInfoBTF -lLLVMDebugInfoPDB -lLLVMDebugInfoMSF -lLLVMDebugInfoDWARF -lLLVMObject -lLLVMTextAPI -lLLVMMCParser -lLLVMIRReader -lLLVMAsmParser -lLLVMMC -lLLVMDebugInfoCodeView -lLLVMBitReader -lLLVMFuzzerCLI -lLLVMCore -lLLVMRemarks -lLLVMBitstreamReader -lLLVMBinaryFormat -lLLVMTargetParser -lLLVMTableGen -lLLVMSupport -lLLVMDemangle -lz /usr/lib/gcc/x86_64-linux-gnu/11/libstdc++.a -lunwind -lc --cache-dir /home/tim/oss/zig/zig-cache --global-cache-dir /home/tim/.cache/zig --name zig --mod aro::/home/tim/oss/zig/deps/aro/lib.zig --mod build_options::/home/tim/oss/zig/zig-cache/c/197acdda9a41bf83a98f96eb0ebf1440/options.zig --deps aro,build_options -I /home/tim/local/llvm17-release/include -I /home/tim/local/llvm17-release/include -L /home/tim/local/llvm17-release/lib -L /home/tim/local/llvm17-release/lib -I /home/tim/local/llvm17-release/include --zig-lib-dir /home/tim/oss/zig/lib` may be the one to try

**Comment by tmlbl** [comment]
Unfortunately just a `terminated by signal SIGSEGV (Address boundary error)`. I followed the same steps on another recent Ubuntu install and had no issues, so it appears to be some kind of environment issue

**Comment by andrewrk** [comment]
When a segfault happens in a debugger it will can tell you the stack trace, which can usually lead to spotting the problem

**Comment by tmlbl** [comment]
Thank you, having trouble getting it going in the debugger and the command has crashed this computer a couple of times. I will reopen if I'm able to debug and provide more detail.
