### ISSUE TITLE
LLVM Error:  "Instruction does not dominate all uses!" | -femit-asm in ReleaseFast mode

### ISSUE THREAD

**Issue by zraineri** [ziglang/zig#17838]
### Zig Version

0.12.0-dev.1372+8457439a8

### Steps to Reproduce and Observed Behavior

When utilizing `-femit-asm` and `-O ReleaseFast` I receive the following error:

```sh
LLVM Emit Object... Instruction does not dominate all uses!
  %317 = load <4 x i8>, ptr %316, align 1, !noalias !28
  %297 = shufflevector <4 x i8> %317, <4 x i8> %296, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
LLVM ERROR: Broken module found, compilation aborted!
```
 If I build with `-O Debug` it works just fine.

Building the code in any mode works if I remove `-femit-asm`. Running the code works as expected every time once I build without `-femit-asm`

Adding an assert is triggering the issue. Unfortunately I haven't been able to produce a minimal code example and cannot share my project. Any recommendations on how I can help further narrow this down?

### Expected Behavior

The code to build without error

**Comment by Vexu** [comment]
> Any recommendations on how I can help further narrow this down?

Compile with `--verbose-llvm-ir` and then grep for those lines in the output. It should lead you to the problematic function.

**Comment by zraineri** [comment]
It was an invalid assertion and I'm unable to provide a minimal reproducible example so closing out
