### ISSUE TITLE
std.ArrayList.appendNTimes allows '0' as a value of N

### ISSUE THREAD

**Issue by VisenDev** [ziglang/zig#17850]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

This code runs fine, I think it would help prevent bugs if compiling this produced some sort of warning that you are appending to the array 0 times, likely because you mixed up the order of the parameters

```
const std = @import("std");

test {
    const a = std.testing.allocator;

    var foo = std.ArrayList(u32).init(a);
    defer foo.deinit();

    const count = 128;
    const value = 0;

    //BUG: count and value are swapped
    try foo.appendNTimes(count, value);
}
```

This happened to me when trying to 0 initialize an array of `u8`s, causing a segmentation fault because I assumed the list had been initialized when it had not been.

### Expected Behavior

Some sort of compile warning if it is known at compile time that your are passing 0 to the appendNTimes();

Since appending a value 0 times is a no op, this might be something to enforce at runtime since it could cause bugs? Thoughts?

**Comment by mlugg** [comment]
I don't really see any advantage to this change - sure you can currently mess up the order of parameters here, but you can do that with non-zero values too. Passing the count as 0 makes perfect logical sense, and could be an entirely coherent thing to do in code where that count is a runtime-known value (say, you're padding a list to a fixed length, so do `foo.appendNTimes(pad_val, desired_len - foo.items.len)`).
