### ISSUE TITLE
comparing a runtime known integer with a comptime_int that is out of range should be a compiler error

### ISSUE THREAD

**Issue by paperdave** [ziglang/zig#17853]
### Zig Version

0.12.0-dev.1391+ae6df9e96

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() void {
  if (@as(u32, std.math.maxInt(u32)) == -1) {
    std.debug.print("true\n", .{});
  } else {
    std.debug.print("false\n", .{});
  }
}
```

The left hand side can be any runtime know integer, and the right side is a comptime_int that is out of range of the type you are comparing to. This expression is never true, and the comparison should not be a comptime false, but rather a compiler error similar to the error for doing `@as(u32, -1)`.

### Expected Behavior

I think the compiler error here should read `integer comparison is always because type 'u32' cannot represent integer value '-1'`. 

The specific use case I hit this footgun on was when using `GetFileAttributesW`, a function that which returns a u32, and I had the constant `INVALID_FILE_ATTRIBUTES` set to comptime_int `-1`. using == on the returned attributes caused the program to treat every file attribute as valid. It should have been a compiler error, as I was meant to compare it to `std.math.maxInt(u32)`, not `-1`.

Another example:

```ts
export fn main(i: u32) u64 {
  if (i == -1) {
    @compileError("i am not analyzed");
  } else {
    return 2;
  }
}
```

the i == -1 becomes a comptime known false, which stops the branch from being analyzed. Putting this into Compiler Explorer will yield assembly for `return 2` in all optimization modes.

**Comment by Vexu** [comment]
This is intended behavior #2146
