### ISSUE TITLE
The `>>=` operator coincides with the Haskell bind operator

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#17864]
The three/four-symbol long assignment operators like `>>=`, `<<=`, `<<|=`, `>>|=` look like FP symbols and seems to me adds undue visual noise contrary to Zig's focus on readability. 

Perhaps it would be wise to try to limit consecutive Ascii symbol operators to less than or equal to two?

Operators exceeding two consecutive symbols should instead prefer the explicit assignments over unary versions.

**Comment by exxjob** [comment]
[These are bitwise-assignment operators.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Left_shift_assignment) If it comes down to symbol count, try fonts with programming ligatures.
Keep in mind terseness doesn't directly translate to readability. Consistency is usually more important.

**Comment by mochalins** [comment]
Just to throw in another opinion; I'm somewhat used to a few ML-family FP languages, and even then these operators don't add any visual noise. Operators such as `>>=` mean exactly what I'd imagine them to mean, a natural extension of the `>>` bit shift operator. 

As an aside, I happen to use these particular operators precisely to reduce visual noise in quite a few embedded-interfacing applications where bit shift operators are extensively used.
