### ISSUE TITLE
`zig fmt` and column width

### ISSUE THREAD

**Issue by mataha** [ziglang/zig#17877]
What, if any, is the maximum column width in `zig fmt`?

Ideally I'd expect a long line like the following:

```zig
something.someFunction().someAnotherFunction().yetAnotherFunction().someFunctionWithAVeryLongName();
```

To be turned into:

```zig
something
    .someFunction()
    .someAnotherFunction()
    .yetAnotherFunction()
    .someFunctionWithAVeryLongName();
```

I don't expect a configuration option (as I know the policy is to have no options in the first place), but I would've thought there was an upper limit.

**Comment by nektro** [comment]
adding the first break, `zig fmt` will do the rest. changing your first line to the following will produce your expected output

```zig
something
    .someFunction().someAnotherFunction().yetAnotherFunction().someFunctionWithAVeryLongName();
```
