### ISSUE TITLE
linux CI is broken

### ISSUE THREAD

**Issue by kristate** [ziglang/zig#1788]
llvm 7.0.1 added a new OS (HermitCore) among other things -- this is a reference issue is for tracking changes.

**Comment by andrewrk** [comment]
No, it didn't. Here's a diff between the file that has the OS enums in 7.0.0 and 7.0.1:

```
andy@xps ~/downloads> diff -u llvm-7.0.0.src/include/llvm/ADT/Triple.h llvm_release_70/include/llvm/ADT/Triple.h
```

I believe what happened is that apt.llvm.org was incorrectly updated with a version of llvm that is not 7.0.0 or 7.0.1, and that's the problem.

I mentioned this on the llvm-dev mailing list. I'll give it a day or two to get fixed, otherwise we can consider manually caching binary artifacts for linux as we do for macos and windows.

**Comment by andrewrk** [comment]
http://lists.llvm.org/pipermail/llvm-dev/2018-November/127974.html

**Comment by kristate** [comment]
I thought as much at first too, but the llvm apt repo seems to update with SVN.
Last version was reported as 1:7.0.1~svn347285-1~exp1~20181124105320.40

Can we get some sort of fix out so that we can continue development via CI?
Btw, the #1789 patch that I made tracks the changes to 7.0.1

**Comment by kristate** [comment]
Trying to track-down the source of the build and got this log:

https://llvm-jenkins.debian.net/job/llvm-toolchain-xenial-7-source/40/consoleFull

It seems to be pulling source from http://llvm.org/svn/llvm-project/llvm/branches/release_70 -- but r347285 doesn't reflect the source that we were compiling.

**Comment by ibebrett** [comment]
What is the work around for building and running locally. Build/install llvm from source from a release like: http://releases.llvm.org/7.0.0/llvm-7.0.0.src.tar.xz ?

**Comment by andrewrk** [comment]
@ibebrett yes - the only thing that is different right now is that apt.llvm.org is broken.

**Comment by andrewrk** [comment]
If they don't fix it by Friday, I'll update zig's docker image to do all the tests, and we'll start using that instead of relying on apt.llvm.org.

**Comment by kristate** [comment]
Cross-posting from the list:

> It appears that there was an out-of-band patch from Samuel Thibault:
> https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/blob/7/debian/patches/D54378-hurd-triple.diff
> Although the patch was approved here https://reviews.llvm.org/D54378

http://lists.llvm.org/pipermail/llvm-dev/2018-November/128077.html

**Comment by andrewrk** [comment]
Nice find, @kristate. I'm going to try to convince them to revert. I don't think it's appropriate to make API breaking changes in a bugfix release.
