### ISSUE TITLE
Catch duplicate field names in AstGen rather than semantic analysis

### ISSUE THREAD

**Issue by mlugg** [ziglang/zig#17916]
When declaring a `struct`, `union`, etc, we want to report an error in the case where a field name is used more than once. Currently, this logic exists in Sema, when semantically analyzing the struct fields (you can easily find the corresponding logic for unions etc).

https://github.com/ziglang/zig/blob/81219586bc3d41cc462cd383269e06c069ab8004/src/Sema.zig#L35734-L35746

However, field names are known simply from the AST (we're not reifying types here!), so this check can actually be done sooner. Specifically, it could be performed in AstGen, within `AstGen.structDeclInner`. This would have two advantages:
* Avoid the need for this check in Sema, since this code path may be reached many more times than the corresponding AstGen path
* Report this error for all structs, even those which are unused

In a similar vein, for struct initialization expressions `.{ .x = 123, .y = 456 }`, we could also notice duplicate field names in AstGen. This logic currently exists in three separate places in Sema due to the different ways struct initializations can be lowered to ZIR: `Sema.validateStructInit`, `Sema.zirStructInit`, and `Sema.structInitAnon`. You can find it that logic by searching for the string `"duplicate field"`. The replacement AstGen logic would live in `AstGen.structInitExpr`.

This issue isn't trivial, but it's probably a relatively good first issue for someone interested in contributing to the actual compiler.

**Comment by Rexicon226** [comment]
@mlugg this can be closed now?

**Comment by mlugg** [comment]
No - this has been handled for struct init expressions, but not for struct (and union, and enum) declarations (i.e. `struct { x: u32, x: u32 }`). If you'd like to take that on, feel free.

**Comment by Rexicon226** [comment]
mmm another challenge. i like it :D 

will do this tomorrow 🫡
