### ISSUE TITLE
fast-path `@sgn` built-in that works for floats and ints

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#17911]
https://en.wikipedia.org/w/index.php?title=Signum_function

This is different from just extracting sign bits which would return positive even for zeros.

#### Unsigned
- zero: return 0
- nonzero: return 1 

#### Signed
- zero: return 0
- \>zero: return 1
- <zero: return -1 

#### Float
- NaN: return nan
- +/-zero: return 0
- \>zero: return 1
- <zero: return -1

**Comment by Vexu** [comment]
There already is [`std.math.sign`](https://ziglang.org/documentation/master/std/#A;std:math.sign).
