### ISSUE TITLE
Strange segfault issue relating to discards and static members variables

### ISSUE THREAD

**Issue by joadnacer** [ziglang/zig#17921]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

Encountered this bug while playing around with an allocator implementation. Have stripped it down a lot to only relevant functions but still 400 lines unfortunately, will take a while to narrow down more.
Full code is available here: https://gist.github.com/joadnacer/b9f0f544f42699def70fe135e71cda2e

Erroneous behavior is shown via these tests, following the comments shows strange behaviour:

```
// works if placed second
test "this has a segmentation fault if placed first" {
    var jdz = JdzAllocator(.{}){};
    defer jdz.deinit();
    var allocator = jdz.allocator();

    _ = try allocator.alloc(u8, 8); // or if this is commented out and below 2 lines are uncommented
    // var res = try allocator.alloc(u8, 8);
    // _ = res;
}

test "this doesnt have a segmentation fault if placed first" {
    var jdz = JdzAllocator(.{}){};
    defer jdz.deinit();
    var allocator = jdz.allocator();

    var res = try allocator.alloc(u8, 8);
    _ = res;
}
```
It  seems that changing
```
_ = try allocator.alloc(u8, 8);
```
to
```
var res = try allocator.alloc(u8, 8);
 _ = res;
```
changes behaviour of the code.
As res is not being used anywhere else, these 2 blocks should be identical in effect?
As the 2 tests should be identical, their order should not matter?

This is linked to the static struct variables (`heap` and `heap_init`), as replacing these with non-static member variables fixes the issue (found this as they were threadlocal in original code, made them normal vars to show that threadlocality is irrevalant). The deinit() method, which is what encounters the segfault (it does not use the `heap` static variable to access individual heaps, instead using the `heaps` member variable)

### Expected Behavior

Different discard patterns should not have different effects

**Comment by Vexu** [comment]
On line 152 you compare `undefined` to `null`
```zig
    span_list: [SIZE_CLASS_COUNT]?*Span = undefined,
...
            const span = heap.span_list[size_class.class_idx];

            if (span != null) return self.allocateFromSpan(span.?);
```

You also need to set `heap_init` to `false` in `deinit`.

**Comment by joadnacer** [comment]
setting heap_init to false does fix issue and I am aware of this (as I said, changing to non static member vars fixed issue)
comparing undefined optional array to null does seem really bad actually and thanks for pointing it out, but surprisingly has worked without issue, and is unrelated

regardless of fact that the bug in this particular code is easily fixed, the underlying issue here is that

```
_ = try allocator.alloc(u8, 8);
```
should produce equal behaviour to
```
var res = try allocator.alloc(u8, 8);
 _ = res;
```

but this is not the case?

**Comment by Vexu** [comment]
Omitting `heap_init` causes undefined behavior in `alloc`, the segmentation fault is probably caused by alignment somewhere.

**Comment by joadnacer** [comment]
I agree yes, this is not working code but I am not asking about fixing it - am I wrong in stating that the discard patterns should not produce identical effects?

```
{ _ = something(); }
```
vs
```
{
var res = something();
_ = res;
}
```
These two blocks should produce identical results as just discarding return value in both cases?

**Comment by Vexu** [comment]
Your program has undefined behavior, strange thins happening is the expected outcome.

**Comment by joadnacer** [comment]
UB means that many things can happen, not that anything can happen, and this does not seem to me to belong to the set of "things that should be able to happen". 

I'll play around with this more some other time to see if I can simplify the case/produce some effect without ub, can leave for now.
