### ISSUE TITLE
windows build failure

### ISSUE THREAD

**Issue by travisstaloch** [ziglang/zig#1792]
Because I wanted to get zig fmt working, I tried building zig from source on windows, following the instructions provided: https://github.com/ziglang/zig/wiki/Building-Zig-on-Windows

I updated visual studio to the most recent version along with msbuild tools and installed cmake 3.13.0.  

I tried following this https://github.com/ziglang/zig/issues/1088, adding the 8.1 flag like this too: 
```cmd
cmake.exe .. -Thost=x64 -G"Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=F:\bin\zig\build-release -DCMAKE_PREFIX_PATH=F:\bin\llvm+clang-7.0.0-win64-msvc-release -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_VERSION=8.1 && bin\zig.exe build --build-file ..\build.zig test
```

I keep getting this as the final error message
```
Configuring zig version 0.3.0+f6cd02b
The system cannot find the path specified.
```
Here is the full output I get from both commands (with and without -DCMAKE_SYSTEM_VERSION=8.1) : 
[stdout.txt](https://github.com/ziglang/zig/files/2615534/stdout.txt)

Can anyone tell whats going on or recommend a  workaround to allow me to use zig fmt?

**Comment by andrewrk** [comment]
The stdout.txt file you linked looks fine to me, and does not contain the text "The system cannot find the path specified."

What happens when you proceed with the msbuild step?

**Comment by travisstaloch** [comment]
The build just stops at this point.  I redirected to that file.  The message "The system cannot find the path specified." didn't make it into the file.  Maybe it was coming from stderr?  

I think you were correct and the first build command did succeed.  The problem was that it couldn't find bin\zig.exe from: 
```
 && bin\zig.exe build --build-file ..\build.zig test
```
Should a new zig.exe exist at this point?  If so, where is it?  I see there is a bunch new of stuff in build-release but no bin directory there or in the parent directory.

**Comment by travisstaloch** [comment]
I tried opening up zig.sln in visual studio and running Release build from there and it seemed to complete although there was a strange permissions error at the end related to ALL_BUILD.  Don't think that mattered.  I see: 
```
10>Generating Code...
10>zig.vcxproj -> F:\bin\zig\build-release\Release\zig.exe
10>Done building project "zig.vcxproj".
11>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------
11>Building Custom Rule F:/bin/zig/CMakeLists.txt
11>CMake does not need to re-run because F:/bin/zig/build-release/CMakeFiles/generate.stamp is up-to-date.
========== Build: 11 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
There is a zig.exe now in build-release\Release.  When I changed the command to 
```
Release\zig.exe build --build-file ..\build.zig test
```
I see the error: 
```
f:\bin\zig\build-release>Release\zig.exe build --build-file ..\build.zig test
Unable to find zig lib directory
```

**Comment by andrewrk** [comment]
I don't think you followed this step:

`msbuild -p:Configuration=Release INSTALL.vcxproj`

**Comment by travisstaloch** [comment]
DOH!  How did I leave that off?  Ha ha... so obvious.   Thank you!  Its working now, running the zig tests and so far all tests passing.  Going to try and run 
```
bin/zig build --build-file ../build.zig --prefix $(pwd)/stage2 install
```
when complete so that I can use zig fmt.  

... 
And that all worked!  I can use zig fmt from visual studio code after including the zig fmt command `F:\bin\zig\build-release\stage2\bin\zig.exe fmt` One thing I had to do to get the stage 2 compiler to build was substitute `F:\bin\zig\build-release\stage2` in for `$(pwd)/stage2` in the above command for the x64 Native Tools terminal doesn't understand `$(pwd)`.
