### ISSUE TITLE
Detected dependency loop error

### ISSUE THREAD

**Issue by David00154** [ziglang/zig#17932]
### Zig Version

0.11 and 0.12

### Steps to Reproduce and Observed Behavior

Zig complains about dependency loop

### Expected Behavior

It’s shouldn’t return error

**Comment by mlugg** [comment]
This bug report is not helpful - you have not included reproduction steps. There is no way to verify, debug, or resolve a compiler bug if you do not indicate how to trigger it. If you would like to report a bug, please open an issue with exact reproduction steps (likely a source file and the command needed to trigger the unexpected behavior).
