### ISSUE TITLE
zig fmt should column align when wrapping a list into rows

### ISSUE THREAD

**Issue by thejoshwolfe** [ziglang/zig#1793]
Inspired by https://github.com/ziglang/zig/issues/544#issuecomment-441525378 . This:

```zig
const transformed = []f32{
    1.25, 1.0, 1.0, 0.0,
    0.095, 1.0, 0.0, 1.0,
    1.05, 3.5, 10.24, 8.5,
    105.25, 35.2, 92.1, 1.0,
};
```

should be formatted as this:

```zig
const transformed = {
    1.25,   1.0,  1.0,   0.0,
    0.095,  1.0,  0.0,   1.0,
    1.05,   3.5,  10.24, 8.5,
    105.25, 35.2, 92.1,  1.0,
};
```

The proposal is that if we're doing more than 1 item per row, then the columns should be aligned.

**Comment by andrewrk** [comment]
I'm OK with accepting this. Any objections?

**Comment by hryx** [comment]
Thanks for opening this @thejoshwolfe. Beat me to it!

Having used Go (and Go fmt) in a team settings for a few years now, I will say:

- Yes, it does make certain diffs noisier, but this is alleviated by whitespace-aware diff engines. GitHub helps here a little these days.
- When not looking at a diff (reading code for the first time, or reviewing later) it makes struct definitions, multiline arrays, etc. far easier to grasp quickly. It also makes it easier to read while writing.

Overall I believe firmly it is a net gain in readability.

**Comment by thejoshwolfe** [comment]
This proposal is limited to lists, and so would not affect struct definitions.
