### ISSUE TITLE
zig doesn't support llvm target format fully

### ISSUE THREAD

**Issue by cathaysia** [ziglang/zig#17949]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

1. write a empty main.c
2. try cross compile by --target=thumbv7em-none-eabi
3. failed.

    ```console
    error: UnknownArchitecture
    ````

### Expected Behavior

zig cc supports the format described at https://clang.llvm.org/docs/CrossCompilation.html

**Comment by Vexu** [comment]
See #4911
