### ISSUE TITLE
@cInclude/@cImport generated invalid zig code

### ISSUE THREAD

**Issue by winduptoy** [ziglang/zig#1794]
I've looked through the other `@cImport generated invalid zig code` issues but didn't find one that had this error specifically caused by `use of undeclared identifier`.

I'm using GLFW to open a window (copied from [Tetris example](https://github.com/andrewrk/tetris/blob/master/build.zig)) and [Galogen](https://galogen.gpfault.net/galogen-web.html) `GL/3.3/CORE` to load OpenGL functions.

```
use @cImport({
    @cInclude("gl.h");
    @cInclude("GLFW/glfw3.h");
});
```

I've copied `gl.h` from the Galogen output to my build includes directory, and compiled `gl.c` from the Galogen output into `libglloader.a` with a bit of makefile like so:

```
build/obj/gl.o: gl.c
	mkdir -p $(@D)
	$(CC) -c -o $@ $<

build/lib/libglloader.a: build/obj/gl.o
	mkdir -p $(@D)
	$(AR) rcs $@ $<
```

Running `nm -g` on the `libglloader.a` output gives the expected output: lots of symbols starting with `_glptr_*`.

So I link the library in my `build.zig`:

```
... snip ...
b.addLibPath(glLoaderLibDir);
exe.linkSystemLibrary("glloader"); // <- my library compiled from Galogen
... snip ...
```

So far so good. GLFW is correctly opening a window so I know libraries are getting linked. However, when I try to use a function like `glGetError()`, I get the following error when building:

```
/home/matt/dev/isaac/src/main.zig:7:5: error: compiler bug: @cImport generated invalid zig code
use @cImport({
    ^
?.c:1:1: note: use of undeclared identifier '_glptr_glGetError'
TODO: remember C source location to display here
^
/home/matt/dev/isaac/src/main.zig:7:5: error: compiler bug: @cImport generated invalid zig code
use @cImport({
    ^
?.c:1:1: note: use of undeclared identifier '_glptr_glGetError'
TODO: remember C source location to display here
^
```

So I dig into the `gl.h` file and find these relevant bits:

```
typedef GLenum (GL_APIENTRY *PFN_glGetError)();
extern PFN_glGetError _glptr_glGetError;
#define glGetError _glptr_glGetError
```

And check the relevant Zig output with `zig translate-c`:

```
pub const glGetError = _glptr_glGetError;
pub inline fn glIsVertexArray(arg0: GLuint) GLboolean {
    return _glptr_glIsVertexArray.?(arg0);
}
```

So it seems to be upset about `use of undeclared identifier '_glptr_glGetError'`. Double checking the `nm` output shows what seems to be a valid symbol:

```
0000000000000988 D _glptr_glGetError
```

So to conclude what I've deduced:
- The C code from Galogen seems to be valid
- The Zig code generated from the C header seems to be valid
- My library definitely contains the symbol that it is complaining about
- My library is definitely getting linked

The error is stating "invalid generated zig code," but I'm not actually sure that's the case, it' just can't find a symbol?

If some part of my setup is in question, I can put together a full demo to reproduce.

**Comment by andrewrk** [comment]
Thanks for the report!

**Comment by winduptoy** [comment]
This issue appears again with `glCreateProgram()` in addition to `glGetError()`. Both `glCreateProgram()` and `glGetError()` take no arguments, whereas functions like `glCreateShader(GLenum)`, `glCompileShader(GLuint)`, `glGetProgramiv(GLuint, GLenum, GLint*)` that take arguments are compiling without error.

Could the lack of arguments be problem?

[Here's a gist](https://gist.github.com/winduptoy/e58b02b02e22bc605d54c2f965cb8a45) with the unmodified [Galogen](https://galogen.gpfault.net/galogen-web.html) header and translated Zig for reference.

zig v0.3.0+
