### ISSUE TITLE
SIGSEGV handler on by default in debug mode

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1796]
This would make invalid memory access produce a stack trace by default in zig when building in debug mode for POSIX systems. This could be disable-able by a root source file declaration.

Downside is that it makes a syscall before `main`, and makes debug/release modes have different syscall behavior, even for hello world. It would be surprising for anyone who was not aware it was happening.

Here are 2 alternate proposals:
 * Require a pub decl in root source file for build-exe applications that specifies whether to have the SIGSEGV handler. This makes "hello world" more complicated, but makes people aware that this is happening.
 * Do nothing by default, but have a simple standard library function one can call from main to set up this handler, such as `std.debug.enableSegfaultStackTracing();` If the main proposal is rejected, we should at least do this one.

**Comment by kristate** [comment]
Good idea. I think that we should first build-out `std.debug.enableSegfaultStackTracing()` and then circle-back to this issue.

**Comment by emekoi** [comment]
would it be possible to do the same for windows?

**Comment by andrewrk** [comment]
This is done
