### ISSUE TITLE
simplify the panic handler function to be only one function; remove `-fformatted-panics`

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#17969]
There should only be 1 panic handler function and it should be possible to override it by only providing one function. Furthermore, it should be the entry point from the language; there should be no other dependencies on the std lib such as formatted printing.

It should look something like this:

```zig
pub const PanicCause = union(enum) {
    unreach,
    unwrap_null,
    cast_to_null,
    incorrect_alignment,
    out_of_bounds: struct {
        index: usize,
        len: usize,
    },
    sentinel_mismatch_usize: usize,
    sentinel_mismatch_isize: isize,
    sentinel_mismatch_other,
    /// This one comes from a call to `@panic`.
    application_msg: []const u8,
    // ...
};

pub fn panic(cause: PanicCause, error_return_trace: ?*StackTrace, ret_addr: ?usize) noreturn {
    // ...
}
```

This provides complete flexibility to the application overriding the default handler, while keeping it to a single function to be overridden.

**Comment by amp-59** [comment]
If this is not what you want, then you have to say which features you are okay with losing, because reporting non-scalar sentinels can not work with the solution you have suggested.

Interface:
```zig
pub const PanicCause = union(enum) {
    message,
    corrupt_switch,
    discarded_error,
    returned_noreturn,
    reached_unreachable,

    accessed_out_of_bounds,
    accessed_out_of_order,
    accessed_inactive_field,
    accessed_null_value,

    memcpy_argument_aliasing,
    memcpy_argument_lengths_mismatched,
    for_loop_capture_lengths_mismatched,

    mismatched_sentinel: type,
    mismatched_non_scalar_sentinel: type,

    shl_overflowed: type,
    shr_overflowed: type,
    shift_amt_overflowed: type,
    div_with_remainder: type,

    mul_overflowed: type,
    add_overflowed: type,
    sub_overflowed: type,

    cast_truncated_data: struct {
        to: type,
        from: type,
    },
    cast_to_enum_from_invalid: type,
    cast_to_error_from_invalid: type,
    cast_to_pointer_from_invalid: type,
    cast_to_int_from_invalid: struct {
        to: type,
        from: type,
    },
    cast_to_unsigned_from_negative: struct {
        to: type,
        from: type,
    },
};
```
Payload type:
```zig
pub fn PanicData(comptime panic_extra_cause: PanicCause) type {
    switch (panic_extra_cause) {
        .message,
        .discarded_error,
        => {
            return []const u8;
        },
        .corrupt_switch,
        .returned_noreturn,
        .reached_unreachable,
        .accessed_null_value,
        => {
            return void;
        },
        .accessed_out_of_bounds => {
            return struct { index: usize, length: usize };
        },
        .accessed_out_of_order => {
            return struct { start: usize, finish: usize };
        },
        .accessed_inactive_field => {
            return struct { expected: []const u8, found: []const u8 };
        },
        .memcpy_argument_aliasing => {
            return struct { dest_start: usize, dest_len: usize, src_start: usize, src_len: usize };
        },
        .memcpy_argument_lengths_mismatched => {
            return struct { dest_len: usize, src_len: usize };
        },
        .for_loop_capture_lengths_mismatched => {
            return struct { prev_index: usize, prev_len: usize, next_len: usize };
        },
        .mismatched_sentinel,
        .mismatched_non_scalar_sentinel,
        => |child| {
            return struct { expected: child, found: child };
        },
        .mul_overflowed,
        .add_overflowed,
        .sub_overflowed,
        => |val_type| {
            return struct { lhs: val_type, rhs: val_type };
        },
        .div_with_remainder => |num_type| {
            return struct { numerator: num_type, denominator: num_type };
        },
        .shl_overflowed,
        .shr_overflowed,
        => |int_type| {
            return struct {
                value: int_type,
                shift_amt: builtin.ShiftAmount(int_type),
            };
        },
        .shift_amt_overflowed => |int_type| {
            return struct {
                bit_count: u16,
                shift_amt: builtin.ShiftAmount(int_type),
            };
        },
        .cast_to_int_from_invalid => |num_type| {
            return num_type.from;
        },
        .cast_truncated_data => |num_type| {
            return num_type.from;
        },
        .cast_to_unsigned_from_negative => |num_type| {
            return num_type.from;
        },
        .cast_to_pointer_from_invalid => {
            return usize;
        },
        .cast_to_enum_from_invalid => |tag_type| {
            return meta.Child(tag_type);
        },
        .cast_to_error_from_invalid => {
            return u16;
        },
    }
}
```

Potential usage:
```zig
pub inline fn panic(comptime cause: PanicCause, data: PanicData(cause), st: ?*builtin.StackTrace, ret_addr: usize) void {
    @setCold(true);
    @setRuntimeSafety(false);
    switch (cause) {
        .message => |message| builtin.alarm(message, st, ret_addr),
        .returned_noreturn => {
            builtin.alarm("function declared 'noreturn' returned", st, ret_addr);
        },
        .reached_unreachable => {
            builtin.alarm("reached unreachable code", st, ret_addr);
        },
        .corrupt_switch => {
            builtin.alarm("switch on corrupt value", st, ret_addr);
        },
        .accessed_null_value => {
            builtin.alarm("attempt to use null value", st, ret_addr);
        },
        .accessed_out_of_order => @call(.never_inline, panicAccessOutOfOrder, .{
            data.start, data.finish, st, ret_addr,
        }),
        .accessed_out_of_bounds => @call(.never_inline, panicAccessOutOfBounds, .{
            data.index, data.length, st, ret_addr,
        }),
        .accessed_inactive_field => @call(.never_inline, panicAccessInactiveField, .{
            data.expected, data.found, st, ret_addr,
        }),
        .discarded_error => @call(.never_inline, panicUnwrappedError, .{
            data, st, ret_addr,
        }),
        .memcpy_argument_aliasing => @call(.never_inline, panicMemcpyArgumentsAlias, .{
            data.dest_start, data.dest_len, data.src_start, data.src_len, st, ret_addr,
        }),
        .memcpy_argument_lengths_mismatched => @call(.never_inline, panicMismatchedMemcpyArgumentLengths, .{
            data.dest_len, data.src_len, st, ret_addr,
        }),
        .for_loop_capture_lengths_mismatched => @call(.never_inline, panicMismatchedForLoopCaptureLengths, .{
            data.prev_len, data.next_len, st, ret_addr,
        }),
        .cast_to_pointer_from_invalid => |child_type| @call(.never_inline, panicCastToPointerFromInvalid, .{
            @typeName(child_type), data, @alignOf(child_type), st, ret_addr,
        }),
        .mismatched_sentinel => |child_type| @call(.never_inline, panicSentinelMismatch, .{
            meta.BestNum(child_type), @typeName(child_type), data.expected, data.found, st, ret_addr,
        }),
        .cast_to_int_from_invalid => |num_types| @call(.never_inline, panicCastToIntFromInvalid, .{
            meta.BestFloat(num_types.from), @typeName(num_types.from), data, st, ret_addr,
        }),
        .cast_to_enum_from_invalid => |enum_type| @call(.never_inline, panicCastToTagFromInvalid, .{
            meta.BestInt(enum_type), @typeName(enum_type), data, st, ret_addr,
        }),
        .cast_to_error_from_invalid => |error_type| @call(.never_inline, panicCastToTagFromInvalid, .{
            meta.BestInt(error_type), @typeName(error_type), data, st, ret_addr,
        }),
        .mismatched_non_scalar_sentinel => |child_type| @call(.never_inline, panicNonScalarSentinelMismatch, .{
            child_type, data.expected, data.found, st, ret_addr,
        }),
        .mul_overflowed => |int_type| @call(.never_inline, panicArithOverflow(meta.BestInt(int_type)).mul, .{
            @typeName(int_type), math.bestExtrema(int_type), data.lhs, data.rhs, st, ret_addr,
        }),
        .add_overflowed => |int_type| @call(.never_inline, panicArithOverflow(meta.BestInt(int_type)).add, .{
            @typeName(int_type), math.bestExtrema(int_type), data.lhs, data.rhs, st, ret_addr,
        }),
        .sub_overflowed => |int_type| @call(.never_inline, panicArithOverflow(meta.BestInt(int_type)).sub, .{
            @typeName(int_type), math.bestExtrema(int_type), data.lhs, data.rhs, st, ret_addr,
        }),
        .shl_overflowed => |int_type| @call(.never_inline, panicArithOverflow(meta.BestInt(int_type)).shl, .{
            @typeName(int_type), data.value, data.shift_amt, ~@abs(@as(int_type, 0)), st, ret_addr,
        }),
        .shr_overflowed => |int_type| @call(.never_inline, panicArithOverflow(meta.BestInt(int_type)).shr, .{
            @typeName(int_type), data.value, data.shift_amt, ~@abs(@as(int_type, 0)), st, ret_addr,
        }),
        .shift_amt_overflowed => |int_type| @call(.never_inline, panicArithOverflow(meta.BestInt(int_type)).shiftRhs, .{
            @typeName(int_type), data.bit_count, data.shift_amt, st, ret_addr,
        }),
        .div_with_remainder => |num_type| @call(.never_inline, panicExactDivisionWithRemainder, .{
            meta.BestNum(num_type), @typeName(num_type), data.numerator, data.denominator, st, ret_addr,
        }),
        .cast_to_unsigned_from_negative => |int_types| @call(.never_inline, panicCastToUnsignedFromNegative, .{
            meta.BestNum(int_types.to),   @typeName(int_types.to),
            meta.BestNum(int_types.from), @typeName(int_types.from),
            data,                         st,
            ret_addr,
        }),
        .cast_truncated_data => |num_types| @call(.never_inline, panicCastTruncatedData, .{
            meta.BestNum(num_types.to),     @typeName(num_types.to),
            meta.BestNum(num_types.from),   @typeName(num_types.from),
            math.bestExtrema(num_types.to), data,
            st,                             ret_addr,
        }),
    }
}
```

**Comment by amp-59** [comment]
@andrewrk The incompatibility with non-scalar sentinels is this:
* The return type of the single function is `noreturn`.
* Non-scalar sentinels require generic test code (`meta.eql`) to be compiled within the panic function as with the existing function (`checkNonScalarSentinel`). If the expected and found values are equal the function returns, so the return type must be `void`.
* Non-scalar sentinels require an `anytype` renderer to represent the difference between found and expected values in case of a panic.

**Comment by AssortedFantasy** [comment]
How about also adding an argument containing the std.builtin.SourceLocation?
So a signature more like this:
```zig
pub fn panic(cause: PanicCause, error_return_trace: ?*StackTrace, ret_addr: ?usize, source: ?std.builtin.SourceLocation ) noreturn {
    // ...
}
```
This would let at least point to where the panic happened even if you don't want to get into std.debug.DebugInfo and std.debug.dumpStackTrace.

**Comment by amp-59** [comment]
> How about also adding an argument containing the std.builtin.SourceLocation?

That is a large additional cost for common checked arithmetic operations, such as addition, subtraction, and multiplication. Each occurrence of these operations in source would probably cost an additional 64 bytes in program segments; 16 in `.text`, 48 in `.rodata`:

```zig
fn useSrcLoc(src: ?zl.builtin.SourceLocation) void {
    if (src) |_| {}
}
pub fn main() void {}
```
![empty_main_like_this](https://github.com/ziglang/zig/assets/114923809/5a7bb31c-ffe1-4860-8ec1-88c08761d586)

Simulating just the call with `@src()`:
```zig
fn useSrcLoc(src: ?zl.builtin.SourceLocation) void {
    if (src) |_| {}
}
pub fn main() void {
    useSourceLoc(@src());
    useSourceLoc(@src());
    useSourceLoc(@src());
    useSourceLoc(@src());
    useSourceLoc(@src());
    useSourceLoc(@src());
    useSourceLoc(@src());
    useSourceLoc(@src());
    useSourceLoc(@src());
    useSourceLoc(@src());
}
```
![multiple_usage](https://github.com/ziglang/zig/assets/114923809/a9eabb06-ae36-4ff6-bf9e-e4d83980c94b)

In a real program the cost would be higher, as the strings for `fn_name` and `file` are reused in the example.

**Comment by AssortedFantasy** [comment]
Why wouldn't the function name and file be reused? Surely it could be done smartly so its only whatever bytes for the function name and the file name and then per each instance of a call to panic you only need the u32 for line and u32 for column?

**Comment by xdBronch** [comment]
> Why wouldn't the function name and file be reused?

because it wont always be called from the same function and file

**Comment by AssortedFantasy** [comment]
Here is an example of what I mean. This is roughly how the panic could work at the implementation level. Not embedding the full source struct in every panic location.
```
const std = @import("std");
const SourceLocation = std.builtin.SourceLocation;

fn panicImpl(src: SourceLocation) noreturn {
    _ = src;
    @panic("");
}

fn panic_zig_file(partial: SourceLocation) noreturn {
    panicImpl(.{
        .file = "main.zig", // One copy only
        .fn_name = partial.fn_name,
        .column = partial.column,
        .line = partial.line,
    });
}

fn panic_main_fn(line: u32, column: u32) noreturn {
    panic_zig_file(.{
        .file = undefined,
        .fn_name = "main", // One per function
        .column = column,
        .line = line,
    });
}

pub fn main() !void {
    panic_main_fn(30, 5);
    panic_main_fn(31, 5);
    panic_main_fn(32, 5);
    panic_main_fn(33, 5);
    panic_main_fn(34, 5);
    panic_main_fn(35, 5);
    panic_main_fn(36, 5);
    panic_main_fn(37, 5);
    panic_main_fn(38, 5);
    panic_main_fn(39, 5);
    panic_main_fn(40, 5);
    panic_main_fn(41, 5);
    panic_main_fn(42, 5);
    panic_main_fn(43, 5);
    panic_main_fn(44, 5);
    panic_main_fn(45, 5);
}
```

**Comment by amp-59** [comment]
@AssortedFantasy Yes, that is the current behaviour, and the reason why the cost implied by the example is not realistic. It only shows one `fn_name` and `file` being reused every time. However the difference is not great, because the 16 bytes required per slice is already large in proportion to the function name and file pathname.

But all things considered I think what you are describing is possible and could be useful to some users. But it can not be the default behaviour, because 99% of users rely on DWARF for runtime source locations, so all of the work required to generate the builtin source locations would be redundant.

**Comment by andrewrk** [comment]
I don't think non-scalar sentinels need to block progress on this issue. They can have a simple panic message with no formatted printing.

**Comment by trgwii** [comment]
If `checkNonScalarSentinel` remains un-overridable, that forces instances of `std.meta.eql` to be compiled into all safe builds, regardless of if `panic` was overridden.

This means that safe builds would still depend on the std lib when `panic` is overridden by the user.

**Comment by andrewrk** [comment]
`std.meta.eql` should not be compiled into safe builds. This was a mistake and never should have been done.

**Comment by trgwii** [comment]
Given that `std.meta.eql` is seemingly ONLY used by `checkNonScalarSentinel`, should a PR just make no equality comparison at all for non-scalar sentinels?

**Comment by amp-59** [comment]
Do we make panic return `void`, make `checkNonScalarSentinel` permit override, or remove non-scalar sentinels from the language?

**Comment by andrewrk** [comment]
remove non-scalar sentinels from the language

**Comment by wooster0** [comment]
I started working on this a bit here: https://github.com/wooster0/zig/commits/panic/
There is only one commit right now: https://github.com/wooster0/zig/commit/4ca31ee06db0571f52137e8af10077e7037db9cd

It's not finished yet.

I have some questions:
1. Should `std.debug.panic` be changed to accept `std.builtin.PanicCause` or should the signature stay `comptime format: []const u8, args: anytype`? See `lib/c.zig` and `lib/compiler_rt/common.zig` in the commit for examples of why it might be a problem to keep it `comptime format: []const u8, args: anytype`.
3. I tested it manually a bit and it seems to work fine so far (including panic causes that are non-`void`) but I haven't been able to run the test suite yet mainly because I can't really build from source and "builtin.zig is corrupt" errors are also causing me some problems so sometimes I resorted to copy-pasting `PanicCause` wherever it was needed in `src/` compiler files. Would it be fine to test my code with just the GitHub CI later when I'm reasonably confident about my changes? I assume in that case I don't need any of those workarounds.
4. Should `printPanicCause` in `lib/std/builtin.zig` not use `std.fmt.bufPrint`? Should it append to a local stack buffer?
5. I removed `StackTrace.format`. Do I need to do anything else?
6. Is a vector used as a sentinel a scalar sentinel? For now I removed support for vectors as sentinels as well. So you can only use non-vectors and non-array values as sentinels.
7. Doesn't there need to be another `sentinel_mismatch_float: struct { expected: f32, actual: f32 }` field in `PanicCause` in order to print out float sentinels properly? If so, would I use a usize-sized float type so that the size of the union stays `@sizeOf(usize) * 2` bytes?
8. Should there be another field added for pointer sentinels too?
9. All I did to remove non-scalar sentinels from the language is add "non-scalar sentinel '{}' not allowed" errors and I added a test (test/cases/compile_errors/non_scalar_sentinels.zig). Is there any code after that point that I can get rid of?

**Comment by amp-59** [comment]
@wooster0 I have already completed the implementation.

**Comment by castholm** [comment]
@amp-59 I was just wondering, what is the status on your implementation? Do you have any plans to open a PR with your changes? If you don't have any plans to continue working on this it might be a good idea to let us all know so that someone else can pick up where you left off.

**Comment by mlugg** [comment]
Note that the panic handler is not a single function at least in the initial implementation of this proposal; see the comments on #21520 for details.
