### ISSUE TITLE
thread 9499 panic: integer overflow

### ISSUE THREAD

**Issue by rezwanahmedsami** [ziglang/zig#17976]
### Zig Version

0.12.0-dev.706+62a0fbdae

### Steps to Reproduce and Observed Behavior

After Doing ```zig init-exe```

Its created a project with src/main.zig , build.zig

But when i was ran: ```zig build``` with default main.zig code, i got error:

```
rezwan@rezwan:~/devwork/zig_backend$ zig build
thread 9499 panic: integer overflow
/opt/zig/lib/std/process.zig:1222:22: 0x4c6e24 in totalSystemMemoryLinux (build)
    return kilobytes * 1024;
                     ^
/opt/zig/lib/std/process.zig:1164:42: 0x4b62d7 in totalSystemMemory (build)
            return totalSystemMemoryLinux() catch return error.UnknownTotalSystemMemory;
                                         ^
/opt/zig/lib/build_runner.zig:321:48: 0x4b2635 in main (build)
        run.max_rss = process.totalSystemMemory() catch std.math.maxInt(usize);
                                               ^
/opt/zig/lib/std/start.zig:379:37: 0x49fffa in posixCallMainAndExit (build)
            var i: usize = 0;
                                    ^
/opt/zig/lib/std/start.zig:251:5: 0x49fc0f in _start (build)
    asm volatile (switch (native_arch) {
    ^
???:?:?: 0x4 in ??? (???)
Unwind information for `???:0x4` was not available, trace may be incomplete

error: the following build command crashed:
/home/rezwan/devwork/zig_backend/zig-cache/o/df64b49bbed47b93fb94b57b1b1e0b9a/build /opt/zig/zig /home/rezwan/devwork/zig_backend /home/rezwan/devwork/zig_backend/zig-cache /home/rezwan/.cache/zig

```

### Expected Behavior

I expected the build executable bin file.

**Comment by Banacial** [comment]
Just out of curiosity, what is your /proc/meminfo MemTotal:  xxxx kB ? At a first glance thats where you are getting the number from thats causing the usize to overflow.

**Comment by Vexu** [comment]
Are you in a similar situation as #17596?

**Comment by rezwanahmedsami** [comment]
> /proc/meminfo

rezwan@rezwan:~$ cat /proc/meminfo
MemTotal:        7896448 kB
MemFree:          142768 kB
MemAvailable:    3291004 kB
Buffers:          104540 kB
Cached:          3862912 kB
SwapCached:          188 kB
Active:          1383148 kB
Inactive:        5517496 kB
Active(anon):     220224 kB
Inactive(anon):  3419504 kB
Active(file):    1162924 kB
Inactive(file):  2097992 kB
Unevictable:      174672 kB
Mlocked:              48 kB
SwapTotal:       8388604 kB
SwapFree:        8352252 kB
Zswap:                 0 kB
Zswapped:              0 kB
Dirty:             18004 kB
Writeback:             0 kB
AnonPages:       3107840 kB
Mapped:          1078452 kB
Shmem:            706480 kB
KReclaimable:     199724 kB
Slab:             419172 kB
SReclaimable:     199724 kB
SUnreclaim:       219448 kB
KernelStack:       15280 kB
PageTables:        43312 kB
SecPageTables:         0 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    12336828 kB
Committed_AS:   11395768 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       55764 kB
VmallocChunk:          0 kB
Percpu:             7808 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:   368640 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      270016 kB
DirectMap2M:     4747264 kB
DirectMap1G:     3145728 kB

**Comment by rezwanahmedsami** [comment]
> Are you in a similar situation as #17596?

Yes like this
