### ISSUE TITLE
Manipulating static variables and having a panic function causes the build to fail

### ISSUE THREAD

**Issue by bokuweb** [ziglang/zig#17973]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

please run `zig build` in following repo.

https://github.com/bokuweb/zig-panic-repro

### Expected Behavior

- Consistency in results regardless of the manipulation of static variables.
- Display of easily understandable errors.

**Comment by SuperAuguste** [comment]
This is the expected error and I believe it's relatively easy to read; it indicates that the panic function it found does not match the expected, correct signature of a panic function `fn([]const u8, ?*builtin.StackTrace, ?usize) noreturn`. :)

**Comment by mlugg** [comment]
Also note that the reason the build succeeds without the `i = i + 1` line is that without it, there do not exist any calls to the panic handler, so it is not analyzed.
