### ISSUE TITLE
Misleading or unneeded "expected type" compilation error

### ISSUE THREAD

**Issue by majorsopa** [ziglang/zig#17982]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Output

In `main.zig` enter:
```zig
pub fn main() void {
    var i: u32 = 1;
    var j: u64 = 0;
    var k: u8 = 8;
    _ = j << (k * i);
}
```
Run `zig build-exe main.zig`

What you will get as an error is something to the extent of
```
zig build-exe main.zig 
main.zig:5:17: error: expected type 'u6', found 'u32'
    _ = j << (k * i);
              ~~^~~
main.zig:5:17: note: unsigned 6-bit int cannot represent all possible unsigned 32-bit values
referenced by:
    callMain: C:\zig\lib\std\start.zig:564:17
    initEventLoopAndCallMain: C:\zig\lib\std\start.zig:508:34
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```
The important part to note is `main.zig:5:17: note: unsigned 6-bit int cannot represent all possible unsigned 32-bit values`. Changing the type of `j` from `u64` to `u65` will get you `src\main.zig:5:17: note: unsigned 7-bit int cannot represent all possible unsigned 32-bit values`.
In neither variation is there a `u6` or `u7`.

### Expected Output

I don't know exactly what should be the *desired* behavior, but I would expect there to either be no compilation error or a compilation error containing a type that is present in the relevant code.

**Comment by rohlem** [comment]
This is currently intended behavior.

`j`, the number you're shifting, has 64 bits.
An `n`-bit value can only be shifted from `0` up to `n-1` bits, shifting it by bits `>= n` is illegal behavior as per langref (note: currently [only documented at the builtin shifting functions](https://ziglang.org/documentation/master/#shlExact), not at the operator table; that may be an oversight.)
`u6` is the type representing numbers from `0` to `63`, so the exactly fitting type.
For `0` to `64`, `u7` is the smallest type still able to represent all valid values, though invalid values are still included.

The idea is that forcing user code to explicitly cast the argument reminds users to include checks for illegal values in the process / document why those values wouldn't appear at runtime.

**Comment by majorsopa** [comment]
That makes sense, thank you.

**Comment by Vexu** [comment]
Also duplicate of #13379
