### ISSUE TITLE
Add CI tests to check error traces output

### ISSUE THREAD

**Issue by Sahnvour** [ziglang/zig#1799]
From #1655 

This would be handy to catch any regressions, especially on less used platforms.
@andrewrk any particular guidelines on how to setup this for eg. Azure ?

**Comment by andrewrk** [comment]
It's not really related to CI - if you make the test suite run your tests, then it'll get tested by the CI. Here's one place to start looking: https://github.com/ziglang/zig/blob/3c4965a6162e50064d22bc1900584e74e2ef15ea/build.zig#L107-L121

Another idea would be to make them standard library tests to test debug info. If you manage to generate small objects for testing purposes you could commit them to the repository, and have normal unit tests.

I think trying to get high test coverage for this is going to be a nontrivial time investment.

**Comment by Sahnvour** [comment]
I was thinking of the easiest way to test this: compile small programs that output error traces and check the output, with a shell script.
Indeed, having the debug standard library tested is way better. They could even work on the test executable itself, no need of separate object files ?

**Comment by andrewrk** [comment]
@mikdusan added `zig build test-stack-traces` (source in `test/stack_traces.zig`) for this.
