### ISSUE TITLE
Improve Debugging `std.json` by Adding `std.log.Level` to `ParseOptions`

### ISSUE THREAD

**Issue by VisenDev** [ziglang/zig#17995]
### Zig Version

0.12.0-dev.1383+7c5d01b95

### Steps to Reproduce and Observed Output

Currently when parsing a json file, the only way errors are logged is thru the zig error system - which is fine for most applications - but it is not great for parsers since it makes it very unclear where the parsing failed and why. See #16936

One way to fix this would be this proposal #2647, however since this has been open for several years now, it is unlikely that any change like this will happen soon.

Alternatively an outparameter could be passed which records the location of an error in the input string. This sort of approach is very common in a lot of C codebases.

As a much simpler solution that doesn't involve any language level change would be to add a log level field to `std.json.ParseOptions` which would enable logging for the progress of parsing and what exactly caused the parser to fail.

A similar example of an approach like this in the standard library would be the `verbose_log` parameter of the `GeneralPurposeAllocator` [Config](https://ziglang.org/documentation/master/std/src/std/heap/general_purpose_allocator.zig.html#L115) which logs when memory allocations are happening. 

### Expected Output

The `std.json` parser would be able to log the cause and location of an error on the event that parsing fails. This would make it much easier to track down why parsing fails and make zig a more pleasant and robust language to use.

This use case comes from me doing a lot of json parsing [on my personal project in zig](https://github.com/VisenDev/ziggity). Debugging json parsing issues right now is not super pleasant

**Comment by Vexu** [comment]
I'd wait to hear @thejoshwolfe's opinion on how this could be done.

**Comment by thejoshwolfe** [comment]
Thanks for the ping @Vexu ! (I only have notifications setup for pull requests about the json code, not issues, so i would never have seen this without the ping. thank you!) And sorry for ignoring #16936 ; i didn't see that issue.

> Alternatively an outparameter could be passed which records the location of an error in the input string. This sort of approach is very common in a lot of C codebases.

There is a mechanism in place already that is basically this. https://ziglang.org/documentation/master/std/#A;std:json.Diagnostics 

If you're using `json.parseFromSlice()`, you'll need to switch to `parseFromTokenSource()`, but the implementation of the former makes it pretty clear how to switch to the latter.

Does this solve your problem?

**Comment by VisenDev** [comment]
I see, I was not aware that the stdlib had this functionality
