### ISSUE TITLE
Renaming `StackFallbackAllocator.get()` to `.allocator()`

### ISSUE THREAD

**Issue by Rexicon226** [ziglang/zig#18020]
## Why

Every other allocator uses the `.allocator()` function to "pull" the allocator from the instance. This would simply conform to that. 

## Problems

Unfortunately, as I understand it, there would be a problem doing this. Since Aro uses the "sfba", it would require a synchronized upstream PR to rectify this. Is this a real block? Is it worth it? I might just not understand how Aro relates to zig, since it isn't a submodule.

still I think it's something to consider, would make the code more consistent. might be implemented someday :D

**Comment by xdBronch** [comment]
the common `.allocator()` and SFBAs `.get()` are functionally different though. on most allocators its uncommon but perfectly valid to call `.allocator()` any number of times in place of creating a variable and using said variable, but `SFBA.get()` resets the internal FBA allocator state

**Comment by Rexicon226** [comment]
> the common `.allocator()` and SFBAs `.get()` are functionally different though. on most allocators its uncommon but perfectly valid to call `.allocator()` any number of times in place of creating a variable and using said variable, but `SFBA.get()` resets the internal FBA allocator state

this is a very good point.. i did not consider this. nvm then :D
i would argue towards adding a `.allocator()` function, however this is not the case where a vtable needs to be generated, hence it being unneeded.
