### ISSUE TITLE
fix inability to interact with C ABI symbols with underscore name (`_`) by making it a keyword

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1802]
In Zig one can use `@"this syntax"` to name an identifier any arbitrary sequence of bytes, including keywords. The purpose of this is to allow interoperability with any C ABI names, even names that conflict with Zig keywords.

However one cannot do this with `@"_"` because this is semantically equivalent to `_`, because `_` is an identifier, not a keyword. Meaning that Zig will treat `@"_"` just like `_`, not allowing variables and functions with this name. And thus it is impossible to have an external variable named `_` even though that is legal in C.

This proposal is to change `_` into a keyword. Although it's technically a breaking change, it shouldn't break anyone's code in practice, but it does require changes to the grammar and parser, e.g. to implement #1797.

**Comment by andrewrk** [comment]
One question I want to answer before deciding on this issue is whether the same should be done to all primitive types, including, for example, `i32`. It feels a bit strange, but I'm leaning towards yes. I'll note that this conflicts with #2926.

**Comment by Vexu** [comment]
An alternative solution would be to add a `linksymbol` property to variables. Then you could just do:
```zig
var c_underscore linksymbol("_") = ...
```

**Comment by Vexu** [comment]
After wasting a bunch of time coming up with alternatives to 'type' I'm starting to heavily lean in favor of turning `_` and all primitive types into keywords.

**Comment by andrewrk** [comment]
Accepted, `_` will become a keyword with `@"_"` to refer to it as an identifier.

For @Vexu's concern, this is addressed with  #678, in which we allow declarations (not locals) to shadow, however, references to declarations must unambiguously refer to one declaration.

For the case of referring to a primitive which is shadowed by a declaration, we will have a `@lang()` builtin that refers to a namespace which contains the primitives. This allows primitives to be referred to unambiguously in the presence of shadowing.

**Comment by andrewrk** [comment]
Closed in favor of #6062.

Even without `_` being a keyword, Zig has the ability to detect whether it is used via `@"_"` or via `_`. Using it via `@"_"` allows it to be used as an identifier whereas using it via `_` invokes its "discard" properties.

> For the case of referring to a primitive which is shadowed by a declaration, we will have a `@lang()` builtin that refers to a namespace which contains the primitives. This allows primitives to be referred to unambiguously in the presence of shadowing.

This is not needed. Instead, primitives always get precedence, and decls which have name collisions with primitives must be accessed via `a.b` syntax.
