### ISSUE TITLE
why do the posix functions return usize?

### ISSUE THREAD

**Issue by thejoshwolfe** [ziglang/zig#1804]
https://github.com/ziglang/zig/blob/57f44eb2bd17fc0c4e9d09b8c8621867f784d2f0/std/os/linux/index.zig#L862

but according to http://man7.org/linux/man-pages/man2/pipe.2.html the signature is:

```zig
int pipe(int pipefd[2]);
```

so shouldn't the zig signature be:

```zig
fn pipe(fd: *[2]c_int) c_int
```

The issue i'm getting is that i'm trying to check for `-1`, but it's not clear how i'm supposed to do that with a `usize`. maybe with `@truncate(c_int, @bitCast(ssize, x)) == -1`?

**Comment by andrewrk** [comment]
I think you're getting the libc API confused with the linux/posix API. The man pages you linked describe the libc API; the zig code you linked are linux-specific syscalls.

The libc API is problematic for several reasons, one of them being that it depends on errno which is unnecessary thread local storage.

We have a higher level abstraction for this here:
https://github.com/ziglang/zig/blob/57f44eb2bd17fc0c4e9d09b8c8621867f784d2f0/std/os/child_process.zig#L769-L784

this could be exposed as `std.os.posixMakePipe`, similar to other functions in this namespace.

If you trace this all the way to the kernel, you can see that it never makes use of the value `-1`, or thread local variables, like the libc API does. Instead the kernel reserves the last `4096` values of the range of `usize` for error codes, and when writing a zig API abstraction for this, we translate these error codes into zig errors.

**Comment by thejoshwolfe** [comment]
ok, that makes sense.

**Comment by thejoshwolfe** [comment]
are the linux syscalls documented? (i guess linux is open source)

**Comment by andrewrk** [comment]
Not really. The easiest way to learn about the linux syscall API is to read musl source code. https://www.musl-libc.org/

**Comment by thejoshwolfe** [comment]
So zig's `pipe()` function above is really not posix. :thinking:
