### ISSUE TITLE
`std.io.FixedBufferStream([]const u8)` has `write` function breaking `std.testing.refAllDeclsRecursive`

### ISSUE THREAD

**Issue by luehmann** [ziglang/zig#18045]
Running `zig test tmp.zig` on

```zig
const std = @import("std");

pub const FixedBufferStream = std.io.FixedBufferStream([]const u8);

test {
    _ = std.testing.refAllDeclsRecursive(@This());
}
```

fails with 
```
/Users/u/zig/0.12.0-dev.706+62a0fbdae/files/lib/std/io/fixed_buffer_stream.zig:70:44: error: cannot memcpy to constant pointer
            @memcpy(self.buffer[self.pos..][0..n], bytes[0..n]);
                    ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
referenced by:
    refAllDeclsRecursive__anon_1890: /Users/u/zig/0.12.0-dev.706+62a0fbdae/files/lib/std/testing.zig:1145:14
    refAllDeclsRecursive__anon_1044: /Users/u/zig/0.12.0-dev.706+62a0fbdae/files/lib/std/testing.zig:1141:72
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

since `FixedBufferStream.write`  obviously does not work on a constant slice.

The doc comment on `FixedBufferStream` claims

> If the supplied byte buffer is const, then `io.Writer` is not available.

although the current implementation does still have non-functional `Writer` and `write` available.

---

I think it would be useful if the example above actually works by not having `Writer` and `write` available in the constant case.

**Comment by Vexu** [comment]
The issue here is using `refAllDeclsRecursive`.
