### ISSUE TITLE
std.fmt on comptime_int fails to handle some decimal values

### ISSUE THREAD

**Issue by luca-i** [ziglang/zig#18046]
`comptimePrint` doesn't handle correctly some decimal values (such as 300.0, but other are fine, such as 300.5).

How to replicate the issue:

```zig
const std = @import("std");


pub fn main() void {
    const value = 30.0;
    const value_to_str = std.fmt.comptimePrint("{d}", .{value});
    std.debug.print("value = {s}\n", .{value_to_str});
}
```

Expected output:

```
value = 30.0
```

Retrieved output:

```
An error occurred:
/usr/local/bin/lib/std/fmt.zig:1367:47: error: overflow of integer type 'u1' with value '2'
/usr/local/bin/lib/std/fmt.zig:802:27: note: called from here
/usr/local/bin/lib/std/fmt.zig:732:58: note: called from here
/usr/local/bin/lib/std/fmt.zig:487:31: note: called from here
/usr/local/bin/lib/std/fmt.zig:184:23: note: called from here
/usr/local/bin/lib/std/fmt.zig:2008:11: note: called from here
/usr/local/bin/lib/std/fmt.zig:2052:83: note: called from here
```

Code that works:
```zig
const std = @import("std");


pub fn main() void {
    const value = 30.1;
    const value_to_str = std.fmt.comptimePrint("{d}", .{value});
    std.debug.print("value = {s}\n", .{value_to_str});
}
```

Output:

```
value = 30.1
```

**Comment by luca-i** [comment]
I think the offending line could be 1366 in lib.std.fmt.zig

```zig
    var i = num_digits_whole_no_pad;
```

I'm not an expert of Zig by no means, but it seems to me that `i` takes size 1 bit (`u1`).
Could somebody confirm this?

Changing the line to
```zig
    var i: u8 = num_digits_whole_no_pad;
```
compiles.

If I'm right, could somebody spend some time to mentor me (I'm absolutely a newbie) how to prove my solution has no side effects / regression and how to submit a pull request?

Thank you, Luca-

**Comment by Vexu** [comment]
That's correct but it needs to be a `usize` to also work for runtime known values.

> how to prove my solution has no side effects / regression

Add a new test to `fmt.zig` using `expectFmt` and as long as the new test and all old ones pass you're good.

> how to submit a pull request?

That depends on your setup, GitHub probably has tutorials for all the common ones.

**Comment by karlseguin** [comment]
I believe this has regressed (or maybe it was never fully fixed). Using the latest `0.12.0-dev.3428+d8bb139da` the original code works, but changing `value` to `0.05` gives an overflow:

```zig
const std = @import("std");
pub fn main() void {
    const value = 0.05;
    const value_to_str = std.fmt.comptimePrint("{d}", .{value});
    std.debug.print("value = {s}\n", .{value_to_str});
}
```

**Comment by Vexu** [comment]
Probably regressed with #19229
