### ISSUE TITLE
deflate/inflate implementations are ported rather than implemented from first principles

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#18062]
Global variables (unacceptable; warrants the "bug" label):

https://github.com/ziglang/zig/blob/ea4a07701e15f1417aa1229235db1ca80cbda4ef/lib/std/compress/deflate/decompressor.zig#L255

https://github.com/ziglang/zig/blob/ea4a07701e15f1417aa1229235db1ca80cbda4ef/lib/std/compress/deflate/decompressor.zig#L24

What the hell is this comment doing here?

https://github.com/ziglang/zig/blob/ea4a07701e15f1417aa1229235db1ca80cbda4ef/lib/std/compress/deflate/decompressor.zig#L841

Requiring an allocator:

https://github.com/ziglang/zig/blob/ea4a07701e15f1417aa1229235db1ca80cbda4ef/lib/std/compress/deflate/decompressor.zig#L76

This implementation is so problematic precisely because it was ported. We can do better by writing these functions from first principles, using Zig's guiding principles and it will be more robust, optimal, and reusable.

In order to close this issue:

1. Delete the existing deflate/inflate implementation
2. Make a new implementation that does not require passing an Allocator and is not based on porting existing code. It's ok to look at existing code for inspiration, however. It's fun, and not as hard as you would think. Think about how to do it from first principles and I promise you will make a better implementation than the Go std lib authors.
3. Suggestion: take advantage of Zig's SIMD features
4. Provide benchmarks that show the new implementation is significantly faster, better, etc.

Related:
* #17863

**Comment by sudw1n** [comment]
I would like to work on this, but I am absolutely a newbie in terms of the Zig project. It would be helpful if someone is willing to mentor me.

**Comment by sudw1n** [comment]
What is this [function](https://github.com/ziglang/zig/blob/ea4a07701e15f1417aa1229235db1ca80cbda4ef/lib/std/compress/deflate.zig#L19C9-L19C9) doing here? I can't find it being referenced anywhere else.

**Comment by andrewrk** [comment]
it's just copying memory awkwardly

**Comment by sudw1n** [comment]
can't we just remove it? I mean, since we already have `@memcpy()`?

**Comment by andrewrk** [comment]
Yes, I think that a better implementation would not need this function. The current implementation relies on it because it isn't careful about aliasing.  `@memcpy` asserts that the two memory regions do not overlap.

**Comment by nektro** [comment]
the best place for mentorship is one of the wonderful [Community](https://github.com/ziglang/zig/wiki/Community)s

**Comment by nektro** [comment]
for anyone coming across this later, deflate is defined by https://datatracker.ietf.org/doc/html/rfc1951 for reference

**Comment by hdorio** [comment]
The initial goal of porting the deflate implementation from the Go code was to advance the project of the package manager by addressing the issue mentioned in https://github.com/ziglang/zig/issues/213.
While it may not adhere to the Zig standard, it is fast and robust.
Moreover, it can be employed by the package manager, effectively achieving the primary goal.

That being said, I'll be happy to answer questions for anyone wanting to remove it and replace it with a pure Zig implementation.
To learn more about Deflate (https://www.hanshq.net/zip.html#deflate)

> What the hell is this comment doing here?
> decompressor.zig#L841

Every comment was faithfully copied (verbatim) from the Go code to facilitate tracking both sets of code easily and prevent any misinterpretation on my part.

> What is this function doing here? I can't find it being referenced anywhere else.

It is utilized here:
https://github.com/ziglang/zig/blob/ea4a07701e15f1417aa1229235db1ca80cbda4ef/lib/std/compress/deflate/compressor.zig#L330
It was my way to implement a `copy()` function that emulates the behavior of Go's built-in copy function (https://go.dev/ref/spec#Appending_and_copying_slices), ensuring copy from even when the source and destination memory overlaps.

**Comment by sudw1n** [comment]
I looked at the implementation and I feel like we could achieve the same thing with something like:
```zig
            // only copy the number of bytes required
            const n = @min(dest.len, b.len);
            std.mem.copyForwards(u8, dest[0..n], b[0..n]);
```
The ported `copy()` function still uses `memcpy` which (I think) **assumes** that the pointers don't overlap.

**Comment by igor84** [comment]
Also decompressor.zig claims to use up to 300KiB from provided allocator but that turned out to be a lie and png reader started failing for big files. I know original zlib claims not to use more than 35KiB of memory so there is room for improvement even there.

If this is reimplemented I would suggest wrapping the passed in allocator with a FixedBufferAllocator of that maximum size so that tests can fails if you accidentally allocate more than that amount.

**Comment by ianic** [comment]
[Here](https://github.com/ianic/flate/) is one implementation that hopefully ticks Andrew's requirements. 
Implemented from the first principles, don't require allocator. 
Current std is roughly 1.5 times slower in decompression, and 1.17 times slower in compression.

I'm planning to convert that to the PR in the following days. 
Any comments are highly appreciated.

**Comment by andrewrk** [comment]
It looks like great work! Thank you for taking the time to upstream it :-)
