### ISSUE TITLE
build.zig binary stripping inconsistencies

### ISSUE THREAD

**Issue by p7r0x7** [ziglang/zig#18084]
### Zig Version

0.12.0-dev.1664+8ca4a5240

### Steps to Reproduce and Observed Behavior

Using `exe.strip = true;` returns a differently-sized (smaller) binary than `exe.strip = @import("builtin").mode != .Debug;` when encoding using ReleaseFast.

### Expected Behavior

`exe.strip = true;` should produce identical results to `exe.strip = @import("builtin").mode != .Debug;` when using any build mode other than `.Debug`.

**Comment by xdBronch** [comment]
youre importing the `builtin` module of the build runner which is always run in debug mode, not your program. you're essentially setting strip to false unconditionally

**Comment by p7r0x7** [comment]
This is my build.zig; how do I fix this?
```ts
const std = @import("std");
const builtin = @import("builtin");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const exe = b.addExecutable(.{
        .name = "vpxl",
        .root_source_file = .{ .path = "src/main.zig" },
        .target = target,
        .optimize = optimize,
    });

    // Dependencies
    const cova = b.dependency("cova", .{ .target = target, .optimize = optimize });
    exe.addModule("cova", cova.module("cova"));

    exe.strip = builtin.mode != .Debug;
    b.installArtifact(exe);

    // Enable `zig build run`
    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_cmd.addArgs(args);
    b.step("run", "").dependOn(&run_cmd.step);

    // Enable `zig build test`
    const unit_tests = b.addTest(.{
        .root_source_file = .{ .path = "src/main.zig" },
        .target = target,
        .optimize = optimize,
    });
    const run_unit_tests = b.addRunArtifact(unit_tests);
    b.step("test", "").dependOn(&run_unit_tests.step);
}
```

**Comment by xdBronch** [comment]
```diff
- exe.strip = builtin.mode != .Debug;
+ exe.strip = optimize != .Debug;
```

**Comment by p7r0x7** [comment]
It does appear to be working, and it seems like ReleaseSmall is always stripped.

**Comment by andrewrk** [comment]
ReleaseSmall defaults to stripped but you can override this default

**Comment by p7r0x7** [comment]
> ReleaseSmall defaults to stripped but you can override this default 

So it is... guess I tested that incorrectly
