### ISSUE TITLE
Translate-C panics on static empty struct

### ISSUE THREAD

**Issue by garrettlennoxbeck** [ziglang/zig#18093]
### Zig Version

0.12.0-dev.1710+2bffd8101

### Steps to Reproduce and Observed Behavior

Run `zig translate-c header.h` on the following `header.h`:
```
struct empty_struct {};

static inline void foo() {
    static struct empty_struct bar = {};
}
```

### Expected Behavior

Translate-c should not panic.

**Comment by Vexu** [comment]
`translate-c` should use `struct_init_one` here since `struct_init_one_comma` requires at least one initializer.

https://github.com/ziglang/zig/blob/6f8c597fff01623668912255c3e37d3a4cb00a98/src/translate_c/ast.zig#L2051-L2053
