### ISSUE TITLE
"error: 'comptime const' is redundant" is misleading

### ISSUE THREAD

**Issue by bortzmeyer** [ziglang/zig#18094]
### Zig Version

0.12.0-dev.1685+994e19164

### Steps to Reproduce and Observed Output

```
pub fn main() void {
    comptime const a: u32 = 0;
    _ = a;
}
```

As far as I understand, `const` is not always known at compile-time (the language definition does not state it).

 ```
% zig build-exe tmp2.zig
tmp2.zig:2:5: error: 'comptime const' is redundant; instead wrap the initialization expression with 'comptime'
    comptime const a: u32 = 0;
    ^~~~~~~~
```

The message is strange. `comptime const` is not redundant, since constant can also  be known only at execution time.

### Expected Output

May be just "wrap the initialization expression with 'comptime'"?

**Comment by bortzmeyer** [comment]
Note that `const a: u32 = comptime 0;` is not seen as redundant (but it is).

**Comment by mlugg** [comment]
`comptime const x` is alwyas redundant regardless of the type or the initialization expression, because a `const` is always comptime-known if its initializer is comptime-known, hence all you need to do is ensure that the initializer is comptime-known. That's why it's telling you to wrap the initialization expression with `comptime` - if `comptime const x = foo` were allowed, it would always be precisely equivalent to `const x = comptime foo`, and hence would be redundant.

**Comment by Leonss23** [comment]
As far as I understand by reading the documentation, `comptime` is for **expressions** to be evaluated at compile time.

```zig
const x = comptime get_value(); // So you prefix the expression,

comptime const x = get_value(); // not the whole statement, as the `const` keyword is not an expression.
```

But, I agree that the warning may be misleading in that I don't really understand what is meant by "redundant".

**Comment by mlugg** [comment]
The logic is that `comptime var` exists, so if the analogous `comptime const` does not, we need a reason for that - and said reason is that permitting it would be redundant, since it would be equivalent to marking the init expression `comptime`.

**Comment by tisonkun** [comment]
I meet this issue also. It can be intuitive that `comptime const` being a counter part to `comptime var`. Can we make it an alias `comptime const foo = bar` to `const foo = comptime bar`?

Or at least suggest the alternative since it's not intuitive for this "correct syntax".

**Comment by bjxpen** [comment]
I am new to Zig and I was baffled by this too when I was thinking of `comptime var` and trying to see if `comptime const` is a thing.
Here is the reasoning so far from the thread that why `comptime const` is redundant.
> A `const` variable is comptime-known if its initializer is comptime-known
> If the initializer is not comptime-known, it can be forced to be evaluated at compile time using the `comptime` keyword

This is true
```zig
test "const becomes comptime" {
    const foo: i8 = comptime 42;
    comptime var bar = foo; // ok. foo is comptime resolvable
    bar = bar; // mutate
}
```

However, `var` is not comptime-known even its initializer is comptime-known.
```zig
test "var cant be comptime unless qualified" {
    const foo: i8 = comptime 42;
    var bar = comptime foo;  // ok
    comptime var baz = bar; // error. bar not resolvable at comptime.
    
    bar = bar;  // mutate
    baz = baz;  // mutate
}
```

And this is how `comptime var` comes in
```zig
test "var cant be comptime unless qualified" {
    const foo: i8 = comptime 42;
    comptime var bar = foo;  // ok. comptime before var
    comptime var baz = bar;  // ok
    bar = bar;  // mutate
    baz = baz; // mutate
}
```


## Conclusion
- `const` variables are implicitly `comptime` if their initializer is comptime-known. You don't need to explicitly declare it `comptime` in this case.
- `var` variables are never implicitly `comptime`, even if their initializer is comptime-known. You must use `comptime var` to declare a var variable that's accessible and modifiable at compile time
