### ISSUE TITLE
Making casting `callconv` more restricted.

### ISSUE THREAD

**Issue by Rexicon226** [ziglang/zig#18118]
This is a proposal that would limit what exact `callconvs` can be casted to/from. Similar to how constness cannot be casted away and upcasting alignment.

I can't construct an exact table of relationships of which ones should be allowed to cast to which, because of a lack of more concrete knowledge, but it's something that should be done.

Example:
```zig
inline fn a() void {}

pub fn main() void {
    const b: *const fn () void = @ptrCast(&a);
    _ = b;
}
```
this should *not* be allowed as the `Inline` convention only exists during compile time, while the default convention can exist both at runtime and at comptime. This can cause issues and bugs that can be very difficult to trace.

As pointed out by @mlugg on the discord, 
```
casting between any two callconvs is a bad idea in general
```

however there are places where it should be either legal because of how trivial the cast would be, or because it would be very simple to maintain cleanly. hence, more time should be spent examining exactly what combinations should be allowed, and which should be illegal.

**Comment by andrewrk** [comment]
The pointer cast is fine. Here is another example:

```zig
test {
    const T = i32;
    const ptr = &T;
    const ptr2: *align(1) const i32 = @ptrCast(ptr);
    var x: i32 = ptr2.*;
    x += 1;
}
```
```
test.zig:7:22: error: comptime dereference requires 'type' to have a well-defined layout, but it does not.
    var x: i32 = ptr2.*;
                 ~~~~^~
```

This is called type erasure. But if we casted it back to the correct type it's still usable:

```zig
test {
    const T = i32;
    const ptr = &T;
    const ptr2: *align(1) const i32 = @ptrCast(ptr);
    const ptr3: *const type = @ptrCast(ptr2);
    var x: ptr3.* = 1234;
    x += 1;
}
```

Works fine.

Pointers to inline functions are the same. Casting is well-defined, however, trying to call the function or dereference it should then discover that the type makes no sense, and fail with an appropriate error.

I don't think a language change is needed to solve the problem you have discovered, it's just a bug fix needed in Sema.zig.

**Comment by Rexicon226** [comment]
understood @andrewrk, thank you for the throughout reply.

> trying to call the function or dereference it should then discover that the type makes no sense, and fail with an appropriate error.

I'm just a bit confused about this sentence here. I'm more than happy to make this change in sema, I just need a little more clarification on what exactly. 

Yesterday I made this: #18117, which might or might not be what you are talking about 😄
it was still made in a time when I did not fully understand the issue I had found, so it might seem silly/stupid.

PS:
idk if you can even see replies to closed issues 🤔
