### ISSUE TITLE
proposal: functions that use inline while must be marked comptime at the start of the fn definition

### ISSUE THREAD

**Issue by kristate** [ziglang/zig#1811]
Advanced Zig programmers will realize that using `comptime` values with `inline while` can create tighter code, but in the case of #1807 , `os.path.join` was creating a new function for every call.

It may not be apparent to the programmer that multiple instances of a single function may exist in the program.

I propose that any use of `inline while` without the function marked as `comptime` should return an error with a helpful hint of how to correctly define the function.

```zig
pub fn join(allocator: *Allocator, sep: u8, strings: ...) ![]u8 {
    comptime assert(strings.len >= 1);
    var total_strings_len: usize = strings.len; // 1 sep per string
    {
        comptime var string_i = 0;
        inline while (string_i < strings.len) : (string_i += 1) {
            const arg = ([]const u8)(strings[string_i]);
            total_strings_len += arg.len;
        }
    }
}
```

would become:

```zig
pub comptime fn join(allocator: *Allocator, sep: u8, strings: ...) ![]u8 {
    comptime assert(strings.len >= 1);
    var total_strings_len: usize = strings.len; // 1 sep per string
    {
        comptime var string_i = 0;
        inline while (string_i < strings.len) : (string_i += 1) {
            const arg = ([]const u8)(strings[string_i]);
            total_strings_len += arg.len;
        }
    }
}
```

**Comment by thejoshwolfe** [comment]
This would break printf-style functions, like `std.debug.warn`, which rely on inline while to iterate over differently typed args (that have runtime values).

**Comment by kristate** [comment]
The idea of this proposal is not to make functions `comptime` only with `inline while`, but instead to signal that the function contains `comptime` expressions that will create multiple codegen blocks.

Perhaps instead of `comptime fn` it should be `poly fn`. Thoughts?

**Comment by thejoshwolfe** [comment]
Every function with a `...` parameter is a polymorphic function, unlike in C.
