### ISSUE TITLE
Compiler does not detect use of undefined when it is returned from a function

### ISSUE THREAD

**Issue by wrongnull** [ziglang/zig#18129]
### Zig Version

0.12.0-dev.6193+2252dcc50

### Steps to Reproduce and Observed Behavior

```zig
fn getUndef(comptime T: type) T {
	return undefined;
}

pub fn main() void {
	if (getUndef(bool))
		@compileLog(1);
	if (@as(bool, undefined)) // fails with use of undef, as expected
		@compileLog(2);
}
```

### Expected Behavior

Fail with use of undefined

**Comment by nektro** [comment]
functions are not eagerly evaluated at comptime and so the return value of `getUndef(bool)` is runtime known unless prefixed with the `comptime` operator
