### ISSUE TITLE
Missing trait module from standard library

### ISSUE THREAD

**Issue by hustLer2k** [ziglang/zig#18149]
### Zig Version

0.12.0-dev.1735+bece97ef2 

### Steps to Reproduce and Observed Behavior

I recently upgraded to the current 0.12.0-dev.1735+bece97ef2 release. After fixing a few “var” that should have been “const” issues, I’m getting an error,

error: root struct of file ‘meta’ has no member named ‘trait’
After poking around in the library files, the meta/trait.zig file is not there. I was unable to find it or anything like it. Any information about this would be appreciated

### Expected Behavior

No errors about missing struct field. Apparently trait.zig has been removed for some reason.

**Comment by nektro** [comment]
it was removed in https://github.com/ziglang/zig/pull/18061. the fix is to not use the functions anymore or copy the ones u need into your code
