### ISSUE TITLE
why allow target arm-linux-musl?

### ISSUE THREAD

**Issue by jimying** [ziglang/zig#18167]
### Zig Version

0.12.0-dev.1767+1e42a3de8

### Steps to Reproduce and Observed Behavior

maybe i'm wrong.  
confused that arm-linux-musl not exist in `zig targets`, 
but can build success.
```
zig build -target arm-linux-musl  foo.zig
```

arm only support abi 'musleabi' or 'musleabihf`? 

`zig targets` info:
```
# zig targets |grep arm |grep musl
 "armeb-linux-musleabi",
  "armeb-linux-musleabihf",
  "arm-linux-musleabi",
  "arm-linux-musleabihf",
```

### Expected Behavior

If arm only support abi  'musleabi' or 'musleabihf`.   

`zig build -target arm-linux-musl  foo.zig`  should be built fail.

**Comment by Vexu** [comment]
If you try to link libc you'll get an error that it isn't available:
```sh-session
$ zig build-exe foo.zig -target arm-linux-musl -lc
error: unable to find or provide libc for target 'arm-linux.4.19...6.5.7-musl'
info: zig can provide libc for related target arm-linux-gnueabi
info: zig can provide libc for related target arm-linux-gnueabihf
info: zig can provide libc for related target arm-linux-musleabi
info: zig can provide libc for related target arm-linux-musleabihf
```

**Comment by jimying** [comment]
@Vexu  I see,  but i think `-target arm-linux-musl` alone, should print the same error
