### ISSUE TITLE
stack corruption from PeekMessageW()

### ISSUE THREAD

**Issue by SpirosMakris** [ziglang/zig#1816]
Using PeekMessageW corrupts the stack.
e.g
```zig
  pub const MSG = extern struct {
    hwnd:     ?HWND,
    message:  UINT,
    wParam:   i32,
    LParam:   i32,
    time:     DWORD,
    pt:       POINT,
    lPrivate: DWORD,
  };

 // Window init code here ..... 
 
 if (WindowHandleOpt)  |WindowHandle| {
      debug.assert(@alignOf(MSG) == 8);

      var XOffset: u32 = 0;
      var YOffset: u32 = 0;
      
      G_Running = true;
      while (G_Running) {
        var Message: MSG = undefined;
        // handle_messages(WindowHandle);

         while (PeekMessageW(&Message, null, 0, 0, PM_REMOVE) == TRUE) {
           if (Message.message == WM_QUIT) { G_Running = false; }
           _ = TranslateMessage(&Message);
           _ = DispatchMessageW(&Message);
         }

       }
  }

  fn handle_messages(window_handle: HWND) void {
    var Message: MSG = undefined;

    while (PeekMessageW(&Message, window_handle, 0, 0, PM_REMOVE) == TRUE) {
      if (Message.message == WM_QUIT) {
        G_Running = false;
      }

      _ = TranslateMessage(&Message);
      _ = DispatchMessageW(&Message);
    }
  }
```
During debugging right after PeekMessageW() is executed the YOffset value is changed to random values (not 0). When the handle_message() function is used instead (it's just the content of the inner while loop) the YOffset variable is not corrupted, presumably because we changed scope into handle_message() and now some other stack bits are corrupted.

Also sizeof MSG is 40 and not 48 just like stated here:

https://stackoverflow.com/questions/32424089/getmessage-corrupting-my-stack

> I had this error on an x64 conversion of a project. Turned out to be that we had /Zp1 struct member alignment on our project and this was changing the size of the MSG struct from 48 bytes to 40 which then caused stack corruption (and likely other unrealized issues) on x64. Under Win32 it worked fine.

That reply suggests there may be a problem with struct MSG's alignment but the assertion never triggers so MSG should have an align of 8 as needed by windows SDK:

https://docs.microsoft.com/el-gr/cpp/build/reference/zp-struct-member-alignment?view=vs-2017

> C++ headers in the Windows SDK assume /Zp8 packing. Memory corruption may occur if the /Zp setting is changed when using Windows SDK headers.

**Comment by tgschultz** [comment]
How are you defining HWND?

**Comment by SpirosMakris** [comment]
It's just a HANDLE. 
```zig
pub const HWND = HANDLE;
```

**Comment by SpirosMakris** [comment]
Ooh, ok !
Tried it like this and it seems to work fine! 
```zig
wParam: u64,
lParam: c_long,
```
WinAPI types are a bit confusing for me ...
Thanks tgschultz!

**Comment by tgschultz** [comment]
If you want your code to work on both 32 and 64 bit Windows, you could use:

```
wParam: usize,
lParam: isize,
```

Something to get used to about WinAPI is that it does this sort of thing, where a parameter or handle could be a pointer or it could be an integer depending on context.

**Comment by SpirosMakris** [comment]
Yeah, that's much better with usize, isize.
That's what had me confused with it, glad at least I know now that it can be either.
Thanks again!
