### ISSUE TITLE
Test Failed message to include actual vs expected values

### ISSUE THREAD

**Issue by bekkibau** [ziglang/zig#18166]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Output

Improve the test fail output results / error message by including the actual versus expected value. It's hard to debug if the output lacks these values.

1. Write a failing test and save file 
2. Execute command `zig test filename.zig`
3. Observe output, should FAIL with details, but no actual vs expected value printed.

```
const expect = @import("std").testing.expect;

test "while with continue" {
    var sum: u8 = 0;
    var i: u8 = 0;
    while (i <= 3) : (i += 1) {
        if (i == 2) continue;
        sum += i;
    }
    try expect(sum==0);
}
```

<img width="623" alt="image" src="https://github.com/ziglang/zig/assets/109264271/80135016-673f-4d16-9917-0b92efe76c4d">

### Expected Output

I expected to see the actual and expected values both outputted when test failed.
```
Actual: 4 Expected: 0
```

**Comment by IntegratedQuantum** [comment]
You can use `testing.expectEqual` to get the desired behavior

**Comment by matu3ba** [comment]
The function description reads very clearly to me as it nowwhere states diagnostics are to be printed:
```
/// This function is intended to be used only in tests.
/// When `ok` is false, returns a test failure error.
pub fn expect(ok: bool) !void {
    if (!ok) return error.TestUnexpectedResult;
}
```

Maybe a hint like "For diagnostics on error use another function like `testing.expectEqual`." would be helpful.
