### ISSUE TITLE
zig fmt breaks with inline for loop inside switch case

### ISSUE THREAD

**Issue by paperdave** [ziglang/zig#18172]
### Zig Version

0.12.0-dev.1768+39a966b0a

### Steps to Reproduce and Observed Behavior

```zig
const a = switch (1) {
    inline for (1) |_| 1 => 1,
};
```
`zig fmt bug.zig`
```zig
const a = switch (1) {
    { inline for (1) |_| 1 => 1,
};
```

### Expected Behavior

the format result should be valid code

**Comment by Vexu** [comment]
Note that this is being parsed as:
```zig
const a = switch (1) {
    inline (for (1) |_| 1) => 1,
};
```

The `inline` for loops is redundant in a comptime scope and should become an error in `AstGen`.

**Comment by wooster0** [comment]
This is fixed:
```zig
const a = switch (1) {
    inline for (1) |_| 1 => 1,
};
```
```
error: redundant inline keyword in comptime scope
```
