### ISSUE TITLE
`std.debug.print` does not print slice contents when its size is comptime-known.

### ISSUE THREAD

**Issue by plaukiu** [ziglang/zig#18185]
### Zig Version

0.12.0-dev.1768+39a966b0a

### Steps to Reproduce and Observed Behavior

```zig
pub fn main() void {
    var buffer = [_]u8{1} ** 140;

    {   // A
        const len = 70;
        const b = buffer[0..len];
        std.debug.print("A {any}\n", .{b});
    }

    {    // B
        var len: usize = 0;
        len = 70;
        const b = buffer[0..len];
        std.debug.print("B {any}\n", .{b});
    }
}
```
variant A prints `A [70]u8@16dc973ec`.
variant B prints `B { 1, 1, 1, 1, ... }`.

The more explicit `{d}` placeholder does not compile.

### Expected Behavior

variants A and B print `{ 1, 1, 1, 1, ... }`.

**Comment by nektro** [comment]
> The more explicit `{d}` placeholder does not compile.

i think this is the real bug here. `{d}` and `{*}` should be be available and let you switch between the two representations
