### ISSUE TITLE
proposal: change `@This()` to be used without `()`

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#18196]
in generic code, while not the best pattern, it is common to see a line such as `const Self = @This();` which is then later used in method definitions such as `list: *Self` or `reader: Self`
while discussing this elsewhere I had a small realization (that got a few :+1:) that I would probably use that line a lot less if it could be referenced as a bare `@This`

while I wouldn't be particularly surprised if this was closed, it did get a positive reaction in the discussion so I wanted to open the conversation

**Comment by tauoverpi** [comment]
Having it be a function makes it clear that the result may differ depending on when/where it's called while `@This` doesn't communicate the same. Otherwise, not exactly the same but should `@src` also be changed given it's similar behaviour?

I feel that the current form is easier to explain as it's "less magic".

**Comment by Jarred-Sumner** [comment]
> Breaking the pattern of builtin _functions_ is almost certainly not worth it for such a small syntactic optimization. If the inconvenience of `const Self = @This();` is seen as a real problem (personally I don't think so), it would make more sense to introduce `Self` as a keyword.

`@This()` is extremely common and `const Self = @This()` always felt strange

<img width="286" alt="image" src="https://github.com/ziglang/zig/assets/709451/8f2cbe1a-1f74-4db4-83e9-5fc807d8a1b2">

**Comment by VisenDev** [comment]
I also usually use @This() as is, 
`const Self = @This()` seems a little unnecessary
