### ISSUE TITLE
make the language reference more beginner friendly

### ISSUE THREAD

**Issue by nacho00112** [ziglang/zig#18200]
As a python programmer, the language reference was quite hard to understand to me, specially the stuff about alignment
https://ziglang.org/documentation/master

**Comment by Vexu** [comment]
The language reference is not meant to be a beginner friendly introduction to systems programming. The other resources at https://ziglang.org/learn/ specifically the "Online learning resources section" might be more like what you're looking for.

**Comment by nacho00112** [comment]
I see, thank you for the link, it is very useful! even [ziglings](https://codeberg.org/ziglings/exercises/) has `beginner-friendly` tag

**Comment by nacho00112** [comment]
> The language reference is not meant to be a beginner friendly introduction to systems programming. The other resources at https://ziglang.org/learn/ specifically the "Online learning resources section" might be more like what you're looking for.

@Vexu after checking the resources they seem pretty good but when comparing to the language reference they are incomplete and maybe outdated due to fast change of zig.
I'm not gonna ask for a introduction for a complete beginner, my python knowledge makes me understand most things of the document,
but at least I want the language reference to add some more explanation about the low-level concepts, If it doesn't, who will do it, people like me could end up needing to learn about C to learn zig.
I'm stuck in the Alignment section.

**Comment by nektro** [comment]
please bring followup discussion to a [Community](https://github.com/ziglang/zig/wiki/Community)

**Comment by nacho00112** [comment]
> please bring followup discussion to a [Community](https://github.com/ziglang/zig/wiki/Community)

well I'll try it, although it would be everything easier if the language reference
doesn't seem like it is yelling me "learn C and come back!"
I wonder if I'm gonna finally understand Alignment and packed struct
if I do that
