### ISSUE TITLE
bug? integer widening doesn't happen during arithmetic

### ISSUE THREAD

**Issue by ryanschneider** [ziglang/zig#18214]
### Zig Version

0.11.0 (also just confirmed it happens still in `0.12.0-dev.1800+559e216f3`)

### Steps to Reproduce and Observed Behavior

```zig
test "widening" {
    const a: u16 = 1024;
    const b: u16 = 512;

    const c: u32 = a * b;
    try std.testing.expect(c == 1024 * 512);
}
```

Yields:

```
error: overflow of integer type 'u16' with value '524288'
    const c: u32 = a * b;
                   ~~^~~
```

I also get similar results with addition as well.

### Expected Behavior

I would expect this to work, since by definition a `u32` should always be able to contain any value produced by multiplying two `u16`.  I would also except a compile time error, but find it _very_ surprising that this code results in a _runtime_ panic (I just ran into this during AoC 2023).

**Comment by travisstaloch** [comment]
> using struct members? 

i'm certain it has nothing to do with the integers being struct members.

**Comment by Vexu** [comment]
See #7416
