### ISSUE TITLE
Windows error: 'debug' is private

### ISSUE THREAD

**Issue by jayschwa** [ziglang/zig#1822]
```
C:\Users\jay\OneDrive\Desktop>zig version
0.3.0+1b0f4d59

C:\Users\jay\OneDrive\Desktop>zig build-exe hello.zig
C:\Zig\lib\zig\std\special\panic.zig:18:16: error: 'debug' is private
            std.debug.panicExtra(error_return_trace, first_trace_addr, "{}", msg);
               ^
C:\Zig\lib\zig\std\index.zig:84:1: note: declared here
const debug = std.debug;
^
C:\Zig\lib\zig\std\special\panic.zig:9:82: error: expected type 'noreturn', found 'void'
pub fn panic(msg: []const u8, error_return_trace: ?*builtin.StackTrace) noreturn {
                                                                                 ^
C:\Zig\lib\zig\std\special\panic.zig:9:73: note: return type declared here
pub fn panic(msg: []const u8, error_return_trace: ?*builtin.StackTrace) noreturn {
                                                                        ^
```
Installation: The Windows build from the download page was unzipped to `C:\Zig`, which was then added to the system `Path` environment variable.

**Comment by emekoi** [comment]
i would suggest you try downloading the master version for now until someone fixes the 0.3.0 version.

**Comment by jayschwa** [comment]
This is master.

**Comment by andrewrk** [comment]
This isn't the correct contents of that file:

```
C:\Zig\lib\zig\std\index.zig:84:1: note: declared here
const debug = std.debug;
^
```

How did your standard library files get out of sync with the ones that come with Zig, either by source installation, or via the pre-built packages?

**Comment by andrewrk** [comment]
I just downloaded and looked at `zig-windows-x86_64-0.3.0+5f5364ad/lib/zig/std/index.zig` and it's correct. Can you double check your installation?

**Comment by jayschwa** [comment]
I removed `0.3.0+1b0f4d59` and replaced it with `0.3.0+5f5364ad`. It seems to work fine now 🤷‍♂️
