### ISSUE TITLE
Using the c allocator from within a test creates a slightly cryptic error message when not linking the c library

### ISSUE THREAD

**Issue by ibebrett** [ziglang/zig#1824]
I attempted to use the c_allocator within a test and didn't think to to link the C library in the test step. Instead of getting a link error about missing symbols for malloc or free, I got an error about having two _starts. I assume this is due to zig letting libc define _start when it is being used (somehow triggered by importing c_allocator). 

Not a bug, but the error message could be more friendly.

**Comment by emekoi** [comment]
duplicate: #1698.
