### ISSUE TITLE
unsupported linker arg: --enable-new-dtags

### ISSUE THREAD

**Issue by scalpel4k** [ziglang/zig#18249]
### Zig Version

0.12.0-dev.1807+d27002011

### Steps to Reproduce and Observed Behavior

Since version 1.74 `rustc` now adds `-Wl,--enable-new-dtags` when it thinks `ld` is used for linking c libraries.

this has been added with this MR: https://github.com/rust-lang/rust/pull/30394

I tried this doing `cargo install cargo-workspaces` for instance.

### Expected Behavior

....

**Comment by andrewrk** [comment]
What an unfortunate name the ld project has chosen for that flag. Wouldn't it be great if they could name the flag after what it actually does.

**Comment by andrewrk** [comment]
Landed in 377ecc6afb14a112a07c6d2c3570e2b77b12a116.
