### ISSUE TITLE
expectEqual silently ignores non-equal values

### ISSUE THREAD

**Issue by tko** [ziglang/zig#18251]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

const It = struct {
    it: usize,
};
fn it() It {
    return .{ .it = 10 };
}
test "it" {
    try std.testing.expectEqual(.{ .it = 20 }, it());
    try std.testing.expectEqual(.{ .it = "abc" }, it());
}
```

```
❯ zig test /tmp/test.zig
All 1 tests passed.
```

### Expected Behavior

On the first case
```
Test [1/1] test.it... expected 20, found 10
```

on the second, a compile error due to type mismatch.

FWIW both cases are reported properly if specifying the type explicitly as in `It{...}` instead of `.{...}`

**Comment by mlugg** [comment]
This should be a compile error with the current signature of `expectEqual`, since the type of `.{ .it = "abc" }` is `struct { comptime it: *const [3:0]u8 = "abc" }`, which `It` does not coerce to. In fact, the first call should also be a compile error, as `It` also does not coerce to `struct { comptime it: comptime_int = 20 }`.

**Comment by xdBronch** [comment]
this does compile error on master

**Comment by Vexu** [comment]
With `0.12.0-dev.1773+8a8fd47d21`:
```
a.zig:10:50: error: expected type 'struct{comptime it: comptime_int = 20}', found 'a.It'
    try std.testing.expectEqual(.{ .it = 20 }, it());
                                               ~~^~
a.zig:3:12: note: struct declared here
const It = struct {
           ^~~~~~
lib/std/testing.zig:56:47: note: parameter type declared here
pub fn expectEqual(expected: anytype, actual: @TypeOf(expected)) !void {
                                              ^~~~~~~~~~~~~~~~~
```
