### ISSUE TITLE
Strange memory corruption when calling function pointer

### ISSUE THREAD

**Issue by bluesillybeard** [ziglang/zig#18265]
### Zig Version

0.12.0-dev.1819+5c1428ea9

### Steps to Reproduce and Observed Behavior

I couldn't make a minimal reproduction case, because every time I tried the bug wouldn't show up. So, here is the full code: https://github.com/bluesillybeard/zig-interface

When running `zig build test`, it should work fine (It will say error, but that's not the issue)
Now, go into `src/tests.zig` and uncomment these two lines, like so
```zig
// comment out this line
std.debug.print("{*}, {*}\n", .{&Sub.dynamicFunction, self.vtable.dynamicFunction});
self.vtable.dynamicFunction(self.object, argument);
// and this line
std.debug.print("{*}, {*}\n", .{&Sub.dynamicFunction, self.vtable.dynamicFunction});
```

And mysteriously, there is a segmentation fault. Debugging the test reveals that the vtable gets corrupted at some point between lines 69 and 73

I'm not sure if I'm accidentally relying on undefined behavior, or if there is actually a bug in the compiler. Either way, a fix would be greatly appreciated.

### Expected Behavior

When the two debug.print lines are commented out, it shouldn't crash with a segmentation fault, but instead the test should pass.

**Comment by Vexu** [comment]
Looks like you're returning a pointer to a stack variable here:
https://github.com/bluesillybeard/zig-interface/blob/bc6e397607ade02d541b3bb6def51f6e3596e53f/src/interface.zig#L47

**Comment by bluesillybeard** [comment]
Good catch! It seems I need to practice looking out for dumb mistakes like that.
