### ISSUE TITLE
HTTP redirect removes trailing slash, which gives wrong redirect url

### ISSUE THREAD

**Issue by last-arg** [ziglang/zig#18291]
### Zig Version

0.12.0-dev.1828+225fe6ddb

### Steps to Reproduce and Observed Behavior

If HTTP request redirects and the header 'Location' has path with trailing slash, the slash gets removed. 

The problem is caused by 'Uri.resolve' which is called by 'std.http.Client.Request.wait` (where the HTTP redirect code is). 'Uri.resolve' uses 'std.fs.path.resolvePosix' to resolve paths which removes trailing slashes. 

1. Make request to 'https://www.tweag.io/blog'
2. Get back redirect request with header value 'Location: /blog/'
3. Make new request with new url which is same as step one's - 'https://www.tweag.io/blog'
4. In my case loop until get error 'TooManyHttpRedirects'

```zig
var gen = std.heap.GeneralPurposeAllocator(.{}){};
var arena = std.heap.ArenaAllocator.init(gen.allocator());
defer arena.deinit();
const options = .{ .location = .{.url = "https://www.tweag.io/blog"}, };
var client = Client{.allocator = arena.allocator()};
const result = try std.http.Client.fetch(&client, arena.allocator(), options);
_ = result;
```

### Expected Behavior

If redirect location contains trailing slash want the new url also to contain trailing slash.
Initial url: 'https://www.tweag.io/blog'
New url (with trailing slash): 'https://www.tweag.io/blog/'

**Comment by andrewrk** [comment]
Fixed by 832f6d8f7f7f7b10b86b109a8b26bb5eacc8d13e.
