### ISSUE TITLE
Declarations: Some mechanism to check for whether they are marked as ``const`` or ``var``.

### ISSUE THREAD

**Issue by nylvon** [ziglang/zig#18294]
``NOTE:`` *Since language proposal issues are disabled (from what I've seen), I thought I'd submit it as a blank issue to get everyone else's opinions on this.*

### What?

I'd like some mechanism to be added to the language to expose whether a public declaration has been declared as ``const`` or ``var``.

### Why?

I'm working on my own little library that aims to extend zig-ctc (zig contracts) and be more exhaustive, maybe even a bit too much. The jist of it is that it allows the user to ensure, at compile time, that a type matches a specific implementation (for instance, whether it's a struct, whether that struct has some fields, some declarations of some types, etc), so it can be used in the same way that zig-ctc is commonly used: essentially to implement interfaces.

I'm looking at exposing all forms of checking, including checking whether some field's type is ``const`` pointer, for instance, and of course, we can do this for declarations' types as well; but I'd also like to ensure that some declarations themselves are constant.

### More details.

Declarations have a bit more than just a type, they can also have a ``const`` and ``var`` keyword before them. I'd like some form of mechanism (be it a field ``is_const`` in ``std.builtin.Type.Declaration`` just like how it exists in ``std.builtin.Type.Pointer``, a builtin, or some other mechanism) in order to get whether a declaration is marked as ``const`` or ``var``.

I've looked through the standard library and the builtins, and I've not found any mechanism in order to check whether a declaration is marked as being ``const`` or ``var``. Before we get into *why* I'd want this information to be available, I'd like to stress that I am not interested in checking the visibility of declarations, I am aware that I will only be able to get declarations marked as ``pub``, visibility is beyond the scope of my proposal.

### Precedent

As mentioned earlier, the ``std.builtin.Type.Pointer`` type that we can extract with the ``@typeInfo()`` built-in already exposes the ``is_const`` field. 

## Why do I want this?

Firstly, let us consider the following scenario. Lighthearted but I think it gets the point across:
```zig
// This is the expected behavior of the `some_cow_type` type's `moo_quiet` function
pub fn moo_quiet() void {
  std.debug.print("moo");
}

// This is the expected behavior of the `some_cow_type` type's `moo_loud` function
pub fn moo_loud() void {
  std.debug.print("MOO!");
}

// Some cow type to check that it has some declarations that point to moo functions.
const some_cow_type = struct {
  // ...some other fields and declarations...
  pub const moo_quiet: *const fn() void = &moo_quiet;
  pub var moo_loud: *const fn() void = &moo_loud;
};

//...

// Not expected of any cows to bark.
pub fn bark_loud() void {
  std.debug.print("BARK!");
}

// ... 

// Suppose someone writes something like this in some other part of the code,
// I wrote it as a function here just to highlight the behaviour.
pub fn evil_function() void {
  // This is valid, since the declaration is marked as `var`
  some_cow_type.moo_loud = &bark_loud;
}

// ...

// Suppose this in some other part of the code that expects a consistent behavior.
pub fn do_cow_stuff(repeat: bool) void {
  // Some type checking here that ensures that the `some_cow_type` type has moo_quiet and moo_loud declarations with the desired `*const fn() void` function signatures.

  // This produces expected behavior.
  some_cow_type.moo_quiet();
  some_cow_type.moo_loud();
  
  // Someone calls `evil_function` somewhere and changes the behavior.
  evil_function();
  
  // If we enter this function again, such as when this `repeat` is set as true when entering this
  // scope, then `moo_loud` would not actually produce expected behavior (We'd see "moo" and then
  // "BARK!" instead of "moo" and then "MOO!", and that is because we're able to modify that
  // declaration. The type checking above doesn't have access to whether a declaration is const or
  // not, which would mean that this isn't preventable unless we entrust the user. We clearly don't,
  // since we use a type checking library.
  if (repeat) do_cow_stuff(false);
}
```

In the above example, we can use some functions or some libraries to do some compile-time type checking and ensure that the type has the declarations that we want (in this case we consider some aliases for some functions, but they could be anything else, so let's just consider this for now as it is easy to see my point), and we can check their types and everything, but we cannot check whether declarations are ``const`` or ``var``, which can lead to some mishaps.

We could define some interface and use it to type check types such that we can use duck typing and get some form of safety and nice errors or error messages that tell us whether a type implements our defined interface. Then, when we call ``some_cow_type.moo_loud();``, we'd expect some consistent behavior. But if the declaration can be changed, then we do not have that guarantee of consistent behavior. This can lead to harder to debug issues simply because we cannot mark some declarations in our interface as ``const`` (not its type, but the mutability of the declaration itself).

### Suggestions.

Introduce a field in ``std.builtin.Type.Declaration`` called ``is_const`` or something akin to that, or maybe a builtin (whichever works best), similar to how we have ``is_const`` in ``std.builtin.Type.Pointer``, such that we can treat these cases.

Furthermore, it feels like this information or a mechanism to get this information *should* be there, because it already is in ``std.builtin.Type.Pointer``, and it wouldn't lead to visibility issues, nor would it conflict with other mechanisms, as it would be a declaration specific mechanism. 

If a field is not desired, then maybe we could have a builtin like ``getDeclMut()``, ``getDeclMutability()``, ``isDeclConst()`` (or any other variant, proposals totally open), or some way of getting this information about declarations.

I think this would be a nice addition, not just because it would prevent situations like these (albeit admittedly possibly rare), but also because it would be consistent with the other parts of ``std.builtin.Type``, like ``Pointer``.

I'm all open for suggestions and discussion, please let me know what you think. If there's any errors, please let me know, too, and I hope that the idea behind my proposal was understood.

Thanks!

**Comment by jacobly0** [comment]
What's wrong with just doing this?
```zig
    inline for (@typeInfo(some_cow_type).Struct.decls) |decl| {
        if (!@typeInfo(@TypeOf(&@field(some_cow_type, decl.name))).Pointer.is_const) {
            @compileError("decl " ++ decl.name ++ " should be const");
        }
    }
```
```
repro.zig:61:13: error: decl moo_loud should be const
            @compileError("decl " ++ decl.name ++ " should be const");
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by nylvon** [comment]
> What's wrong with just doing this?
> 
> ```zig
>     inline for (@typeInfo(some_cow_type).Struct.decls) |decl| {
>         if (!@typeInfo(@TypeOf(&@field(some_cow_type, decl.name))).Pointer.is_const) {
>             @compileError("decl " ++ decl.name ++ " should be const");
>         }
>     }
> ```
> 
> ```
> repro.zig:61:13: error: decl moo_loud should be const
>             @compileError("decl " ++ decl.name ++ " should be const");
>             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

Oh, this actually does exactly what I wanted!

I did not know this was possible. I did not know ``&field(T, decl_name)`` would actually return a pointer to the declaration's details, I expected it would return the details of the type, but it makes sense now.

Thanks for elucdiating this. This can be closed.
