### ISSUE TITLE
Double freed pointer

### ISSUE THREAD

**Issue by CodeOfSomnath** [ziglang/zig#18299]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

```const std = @import("std");
const strings = @import("./strings.zig");

pub fn main() !void {
    var stdin = std.io.getStdIn().reader();
    var stdout = std.io.getStdOut().writer();
    var heap_allocater = std.heap.HeapAllocator.init();
    var allocater = heap_allocater.allocator();
    var buffer =  try allocater.alloc(u8, 1024);

    try stdout.print("Enter your name: ", .{});
    var readLen = try stdin.read(buffer);
    try stdout.print("Name is: {s}", .{buffer[0..readLen]});
    allocater.free(buffer);
    allocater.free(buffer);
    
}
```

In this code I have freed a buffer 2 times but there is not a compile time or runtime error. I think this double free can happen on huge codebase so please take a look to this problem.

### Expected Behavior

There should produce an  error on double free whether it will compile time or runtime , So we can know where the code is showing undefined behaviour.

**Comment by tauoverpi** [comment]
Have you tried the std.heap.GeneralPurposeAllocator? It catches this already.

**Comment by CodeOfSomnath** [comment]
Thank you for your advice. It is working.
