### ISSUE TITLE
Parsing null to optional opaque structs

### ISSUE THREAD

**Issue by Xyndra** [ziglang/zig#18307]
### Zig Version

0.12.0-dev.1828+225fe6ddb

### Steps to Reproduce and Observed Behavior

I am trying to use cinterop with glfw as following:
```zig
window = c.glfwCreateWindow(640, 480, "Hello World", null, null);
```
But I get the following error:
```
src\main.zig:24:32: error: expected type '*cimport.struct_GLFWwindow', found '?*cimport.struct_GLFWwindow'
    window = c.glfwCreateWindow(640, 480, "Hello World", null, null);
             ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src\main.zig:24:32: note: cannot convert optional to payload type
src\main.zig:24:32: note: consider using '.?', 'orelse', or 'if'
src\main.zig:24:32: note: '?*cimport.struct_GLFWwindow' could have null values which are illegal in type '*cimport.struct_GLFWwindow'
```

cimport.zig contains this:
```zig
pub extern fn glfwCreateWindow(width: c_int, height: c_int, title: [*c]const u8, monitor: ?*GLFWmonitor, share: ?*GLFWwindow) ?*GLFWwindow;
```
which according to my knowledge, should work.

### Expected Behavior

it working

**Comment by NewbLuck** [comment]
Something needs to be unwrapped in Zig-land to make sure C is not giving Zig a null pointer when the variable type it is being assigned to is not optional (which I am guessing `window` is in your Zig code, i.e. `window:*GLFWwindow` vs `window:?*GLFWwindow`).  If you opt to make window optional, it will still need to be unwrapped to be used.

**Comment by tauoverpi** [comment]
`window = c.glfwCreateWindow(640, 480, "Hello World", null, null) orelse return error.GlfwCannotCreateWindow` as it may fail to create a window which I assume is fatal.

This is a better question for other channels https://github.com/ziglang/zig/wiki/Community though.
