### ISSUE TITLE
Downloadable doc

### ISSUE THREAD

**Issue by 71GA** [ziglang/zig#18325]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

Download a `.html.in` documentation (https://github.com/ziglang/zig/blob/master/doc/langref.html.in)) on a local disk, rename it to `.html`, open it with a browser and click any hyperlink in the table of contents. Hyperlink will not point inside the same `.html` file but will point to the online documentation ([link](https://ziglang.org/documentation/0.11.0/)) somewhere.

### Expected Behavior

A lot of developers like to document their projects well. This also means archiving language reference documentation for a specific version of a language used in their projects on their computers. Zig language reference exists only as a `.html` page ([link](https://github.com/ziglang/zig/blob/master/doc/langref.html.in)). I tried archiving this `.html`document but document is not good, because hyperlinks of the downloaded `.html` document point to the website and not inside the downloaded document itself!

I also tried to <kbd>Ctrl</kbd> + <kbd>P</kbd> your web page ([link](https://ziglang.org/documentation/0.11.0/)) which had the similar outcome - hyperlinks pointing to the webpage.

Can you try to make documentation selfsuficient even if downloaded? It would be nice to also provide a `.pdf`format which can be annotated by users when learning the language etc...

This would greatly benefit the language.

**Comment by slonik-az** [comment]
Official Zig language distribution from the Zig's download page contains local version of documentation as a `html` file with all hyperlinks working. `html.in` template is meant to be processed by static html generator. Simply renaming it to a html file is a wrong thing to do. This is not a bug.

**Comment by Vexu** [comment]
That `.html.in` is is the input for `zig build docs` which produces the final `.html` file that you are looking for.
