### ISSUE TITLE
Compiling Mold with `zig c++` fails, likely due to `-x <language>` flag

### ISSUE THREAD

**Issue by absolutelynothinghere** [ziglang/zig#18343]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

Try compiling [Mold 2.4.0](https://github.com/rui314/mold/releases/tag/v2.4.0) using `zig c++` and it will return an error:

```plain
[ 24%] Building CXX object CMakeFiles/mold.dir/cmake_pch.hxx.pch
error: language 'h' is unsupported in this context
```

Removing all instances of `-x c++-header` from `mold-2.4.0/CMakeFiles/mold.dir/build.make` suppresses the error, so the problem might be because [`c++-header` does not map to `.hxx`](https://github.com/ziglang/zig/blob/master/src/Compilation.zig#L218) in the Zig compiler.

### Expected Behavior

Compilation should proceed normally.

**Comment by Vexu** [comment]
Related #17956
