### ISSUE TITLE
Building master on gentoo: QA Warnings

### ISSUE THREAD

**Issue by CaptainBloodz** [ziglang/zig#18345]
### Zig Version

0.12.0-dev.1840+d787b78d2

### Steps to Reproduce and Observed Behavior

```
 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * /var/no-tmpfs/portage/dev-lang/zig-9999/work/zig-9999/build/zig2.c:3378343: warning: assignment to 'const uint16_t (*)[16]' {aka 'const short unsigned int (*)[16]'} from incompatible pointer type 'const uint16_t *' {aka 'const short unsigned int *'} [-Wincompatible-pointer-types]
 * /var/no-tmpfs/portage/dev-lang/zig-9999/work/zig-9999/build/zig2.c:1493587: warning: 'memcpy' reading 16 bytes from a region of size 10 [-Wstringop-overread]
 * /var/no-tmpfs/portage/dev-lang/zig-9999/work/zig-9999/build/zig2.c:2744871: warning: 'memcpy' reading 16 bytes from a region of size 10 [-Wstringop-overread]
 * /var/no-tmpfs/portage/dev-lang/zig-9999/work/zig-9999/build/zig2.c:2744945: warning: 'memcpy' reading 16 bytes from a region of size 10 [-Wstringop-overread]

 * Please do not file a Gentoo bug and instead report the above QA
 * issues directly to the upstream developers of this software.
 * Homepage: https://ziglang.org/
```

My apologizes if totally meaningless.

 

### Expected Behavior

No QA warnings reported

**Comment by BratishkaErik** [comment]
Safe to ignore: this is an effect of https://github.com/ziglang/zig/pull/17802
and will disappear when or if the bootstrap seed is updated.

**Comment by CaptainBloodz** [comment]
QA warning remains here:

amd64 ~ # zig version
0.12.0-dev.1849+bb0f7d55e

amd64 ~ # gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/13/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/no-tmpfs/portage/sys-devel/gcc-13.2.1_p20231216/work/gcc-13-20231216/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/13 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/13/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/13 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/13/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/13/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13 --disable-silent-rules --disable-dependency-tracking --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/13/python --enable-languages=c,c++,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --disable-nls --disable-libunwind-exceptions --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 13.2.1_p20231216 p11' --with-gcc-major-version-only --enable-libstdcxx-time --enable-lto --disable-libstdcxx-pch --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libssp --disable-libada --disable-cet --disable-systemtap --disable-valgrind-annotations --enable-vtable-verify --with-zstd --with-isl --disable-isl-version-check --enable-default-pie --disable-default-ssp --with-build-config=bootstrap-lto
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.2.1 20231216 (Gentoo 13.2.1_p20231216 p11)

 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * /var/no-tmpfs/portage/dev-lang/zig-9999/work/zig-9999/build/zig2.c:3379292: warning: assignment to 'const uint16_t (*)[16]' {aka 'const short unsigned int (*)[16]'} from incompatible pointer type 'const uint16_t *' {aka 'const short unsigned int *'} [-Wincompatible-pointer-types]
 * /var/no-tmpfs/portage/dev-lang/zig-9999/work/zig-9999/build/zig2.c:1493823: warning: 'memcpy' reading 16 bytes from a region of size 10 [-Wstringop-overread]
 * /var/no-tmpfs/portage/dev-lang/zig-9999/work/zig-9999/build/zig2.c:2745134: warning: 'memcpy' reading 16 bytes from a region of size 10 [-Wstringop-overread]
 * /var/no-tmpfs/portage/dev-lang/zig-9999/work/zig-9999/build/zig2.c:2745208: warning: 'memcpy' reading 16 bytes from a region of size 10 [-Wstringop-overread]

**Comment by BratishkaErik** [comment]
Yes, it's normal, they will be gone after seed is updated. Final binary don't have them now.

(btw to disable formatting you can put logs into

```
\`\`\`
logs
\`\`\`
```

construction)
