### ISSUE TITLE
mem.readIntSliceLittle not working under comptime

### ISSUE THREAD

**Issue by kristate** [ziglang/zig#1835]
Porting some code over to latest trunk and ran into this problem. Tests failed and we just ran into it.

This is a showstopper for @connectfree so can we get a fix? @andrewrk 

https://godbolt.org/z/RnjL0Q

Thanks.

```zig
const std = @import("std");
const mem = std.mem;
const debug = std.debug;

const CONSTANT = "expand 32-byte k";
const CONSTANT_LE = comptime []u32{
    mem.readIntSliceLittle(u32, CONSTANT[0..4]),
    mem.readIntSliceLittle(u32, CONSTANT[4..8]),
    mem.readIntSliceLittle(u32, CONSTANT[8..12]),
    mem.readIntSliceLittle(u32, CONSTANT[12..16]),
};

export fn constant_test() bool {
    const expected = []u32{0x61707865, 0x3320646e, 0x79622d32, 0x6b206574};
    if (CONSTANT_LE[0] != expected[0]) return false;
    if (CONSTANT_LE[1] != expected[1]) return false;
    if (CONSTANT_LE[2] != expected[2]) return false;
    if (CONSTANT_LE[3] != expected[3]) return false;
    return true;
}
```

**Comment by kristate** [comment]
Thanks @andrewrk

**Comment by kristate** [comment]
This might not be fixed yet with `mem.readIntSliceLittle` -- double checking @andrewrk

**Comment by andrewrk** [comment]
Thanks for the extra test case - let me have a look.

**Comment by andrewrk** [comment]
When I implemented arrays in the comptime pointer reinterpretation code, I messed up non-zero indexes. I need to increase the amount of test coverage when adding new features. Thanks again for the test case.

**Comment by kristate** [comment]
Thank-you -- just got to test it and all tests pass.
