### ISSUE TITLE
Proposal: Make slices behave like array sections in Cilk Plus.

### ISSUE THREAD

**Issue by liampwll** [ziglang/zig#1838]
https://www.cilkplus.org/tutorial-array-notation

Additionally since Zig allows slices as function parameters we could determine whether to map a function over a slice or to pass the slice as a parameter based on the parameter type (this would require some changes for `var` parameters).

**Comment by andrewrk** [comment]
This is semi-related to #903

**Comment by daurnimator** [comment]
Related: https://github.com/ziglang/zig/issues/2255

**Comment by emekoi** [comment]
i think #2255 and this should be merged, allowing the stride of these "enhanced slices" to be accessed through `.stride`

**Comment by andrewrk** [comment]
closing in favor of the open proposal #2255
