### ISSUE TITLE
`formatFloatScientific` rounds f128s

### ISSUE THREAD

**Issue by MasonRemaley** [ziglang/zig#18385]
### Zig Version

0.12.0-dev.1811+df3516ee7

### Steps to Reproduce and Observed Behavior

`std.fmt.formatFloatScientific`'s documentation says that it can format floats without loss of precision, but it rounds all floats to f64s before formatting which will result in loss of precision for larger float types (e.g. f128s):
```zig
/// Print a float in scientific notation to the specified precision. Null uses full precision.
/// It should be the case that every full precision, printed value can be re-parsed back to the
/// same type unambiguously.
pub fn formatFloatScientific(
    value: anytype,
    options: FormatOptions,
    writer: anytype,
) !void {
    var x = @as(f64, @floatCast(value));
```

In contrast, `formatFloatDecimal`'s documentation also states that there will be no loss of precision by default, but is correct since it fails at comptime if given a float with more precision than an f64 since this cast would not be allowed:
```zig
/// Print a float of the format x.yyyyy where the number of y is specified by the precision argument.
/// By default floats are printed at full precision (no rounding).
pub fn formatFloatDecimal(
    value: anytype,
    options: FormatOptions,
    writer: anytype,
) !void {
    var x = @as(f64, value);
```

### Expected Behavior

I expected these functions to print floats supported by Zig without loss of precision.

In the meantime I'd be happy to update the docs to reflect the current behavior, but wanted to file an issue first to make sure I'm not missing any context.

**Comment by Vexu** [comment]
Duplicate of #1181

**Comment by MasonRemaley** [comment]
Whoops missed 1811--thanks!
