### ISSUE TITLE
Unchecked arithmetic operators `+%`, `-%`, and `*%` compile `panic` despite never calling it

### ISSUE THREAD

**Issue by amp-59** [ziglang/zig#18415]
### Zig Version

0.12.0-dev.1859+27d4bf753

### Steps to Reproduce and Observed Behavior

Compile example program with `zig build-obj no_compile_panic_for_arith_wrap.zig`
`no_compile_panic_for_arith_wrap.zig`:
```zig
pub const panic = @compileError("");

export fn entry() usize {
    var x: usize = 0;
    x +%= 1;
    x -%= 1;
    x *%= 1;
    return x;
}
```
Result:
```
zig build-obj no_compile_panic_for_arith_wrap.zig
no_compile_panic_for_arith_wrap.zig:1:19: error:
pub const panic = @compileError("");
                  ^~~~~~~~~~~~~~~~~
```

### Expected Behavior

anything

**Comment by trgwii** [comment]
Why 0.14.0? This seems like a very easy and tiny change

**Comment by Vexu** [comment]
Milestones in the Zig repo are not strict targets and issues may be closed earlier or later.
