### ISSUE TITLE
compiler crash when formatting optional allowzero slice

### ISSUE THREAD

**Issue by xdBronch** [ziglang/zig#18428]
### Zig Version

0.12.0-dev.1858+b0dba4680

### Steps to Reproduce and Observed Behavior

```zig
test {
    try @import("std").io.null_writer.print("{any}", .{@as(?[]allowzero u8, &.{})});
}
```
https://gist.github.com/xdBronch/4bf04d3534b0fc48343876830d702e88

### Expected Behavior

test pass

**Comment by Rexicon226** [comment]
The issue comes from `@field`.
Here is a repo:
```zig
test {
    @import("std").mem.doNotOptimizeAway(@field(.{@as(?[]allowzero u8, &.{})}, "0"));
}
```
