### ISSUE TITLE
error.AddressInUse after std.http.server.deinit()

### ISSUE THREAD

**Issue by qwelias** [ziglang/zig#18420]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

I've just started learning zig, so there's a good chance I'm just doing something wrong, but here are the steps:

1. Save [main.zig](https://gist.github.com/qwelias/363b826569a54a66b6edeaa6ed1205dc)
1. `$ zig run main.zig` in terminal 1
1. `$ curl -vvv http://0.0.0.0:3030/asd` in terminal 2
1. `Ctrl+C` in terminal 1
1. `$ zig run main.zig` in terminal 1

```
info: starting
error: server.listen failed
error: AddressInUse
/usr/lib/zig/std/os.zig:3488:27: 0x238670 in bind (main)
            .ADDRINUSE => return error.AddressInUse,
                          ^
/usr/lib/zig/std/net.zig:1938:9: 0x2381bc in listen (main)
        try os.bind(sockfd, &address.any, socklen);
        ^
/usr/lib/zig/std/http/Server.zig:661:5: 0x238a53 in listen (main)
    try server.socket.listen(address);
    ^
/home/me/my/tf-http-backend/main.zig:58:9: 0x239e4f in main (main)
        return err;
        ^
```

More confusingly neither `ss -lptn 'sport = :3030'` nor `lsof -i :3030` list any processes after step 4

### Expected Behavior

Able to listen on 0.0.0.0:3030 after step 4

**Comment by Vexu** [comment]
You need to init the server with `.reuse_address = true` (and maybe also `reuse_port`).
