### ISSUE TITLE
[windows, 0.12-dev] error: root struct of file 'zig.system' has no member named 'NativeTargetInfo'

### ISSUE THREAD

**Issue by kitsuniru** [ziglang/zig#18457]
### Zig Version

0.12.0-dev.2046+d3a163f86

### Steps to Reproduce and Observed Behavior

Windows 10 x64

install latest `zig` and `Zig Language` extension on vscode, open any project

logs from **Output** (_Zig Language Server_ tab):
```zig
D:\zig\zig.EXE build --build-runner C:\Users\Username\AppData\Local\Temp\zls\build_runner_master.zig
Error: C:\Users\Username\AppData\Local\Temp\zls\build_runner_master.zig:72:37: error: root struct of file 'zig.system' has no member named 'NativeTargetInfo'

D:\zig\lib\std\zig\system.zig:1:1: note: struct declared here
```

### Expected Behavior

There's should be no errors after extension initialization

**Comment by nullptrdevs** [comment]
A working version should be available shortly - it just got updated https://github.com/zigtools/zls/pull/1698

**Comment by Vexu** [comment]
Not a Zig bug and not the right place to report issues in [ZLS](https://github.com/zigtools/zls/issues) or the [vscode extension](https://github.com/ziglang/vscode-zig/issues).
