### ISSUE TITLE
build: a test that uses `std.log.warn` "fails" the test (regression)

### ISSUE THREAD

**Issue by mitchellh** [ziglang/zig#18473]
### Zig Version

0.12.0-dev.2059+42389cb9c

### Steps to Reproduce and Observed Behavior

Create a Zig file:

```
const std = @import("std");

test {
    std.log.warn("hello", .{});
}
```

Create a build.zig that runs this test. Run `zig build test`. Output:

```
test
└─ run test failure
```

If you run the test again with it cached or use `zig test` directly, everything succeeds.

### Expected Behavior

This should not show "failure" in `zig build`, because the tests themselves are passing. 

This previously (as of at least 0.12 build 1880 or so) did not fail.

One could make the argument that I should not be warn logging at all in a test. In my case, I have a test in the Ghostty project that tests scenarios that shouldn't happen in real life but I want to verify they're handled gracefully. Because they shouldn't happen, I log warnings in the code under test, but the tests exercise this code path.

**Comment by andrewrk** [comment]
This can be handled with a flag for whether any stderr output constitutes a failure. Currently this is effectively set to "yes, make any stderr output be considered a failure" but that should probably be a decision made by the user's build script.

However, I am keen to make the default continue to be an error, if only to make people pay more attention to the garbage that spews out of modern software...

**Comment by mitchellh** [comment]
> However, I am keen to make the default continue to be an error, if only to make people pay more attention to the garbage that spews out of modern software...

Another approach is to make `std.log` automatically speak the Zig build system protocol when run via the build system so that the build system doesn't consider it broken. I can think of a few options here.

Is there an env var or something my log function can inspect to determine its running via the build system? I think I can then do a comptime gate on `is_testing` (or w/e that flag was called) PLUS that env var to just swallow the output for now.

**Comment by andrewrk** [comment]
> Another approach is to make std.log automatically speak the Zig build system protocol when run via the build system so that the build system doesn't consider it broken.

Oh now that's an interesting idea! Neatly doable since the test runner already has the capability to override the logs and already is the one that speaks to the build runner.

**Comment by mitchellh** [comment]
My only stderr output is via `std.log`. I use a custom `root.std_options.logFn` that grabs stderr with `std.io.getStdErr().writer()`. So I think with that approach we'd just need to consider what changes I'd have to make to opt-in to that scenario (if it can't be fully automatic) and I'd be more than happy to do so.

**Comment by andrewrk** [comment]
Related: #5738

I think the flag is warranted either way. It should be a trivial change so I am happy to get that landed quickly to unblock your project.

**Comment by andrewrk** [comment]
Ah, I misdiagnosed this. What happened is that I introduced *context* for when stderr is printed. It incorrectly printed "failure" instead of "there was some stderr output and here it is". It actually still exits with code 0.

**Comment by mitchellh** [comment]
That's great. That's the main issue, lots of contributor folks confused that "tests are failing" when they're not. 😄

**Comment by Pbotsaris** [comment]
thanks for having this discussion. this was exactly what I was looking for :)
