### ISSUE TITLE
"zig ast-check" gets stuck when there are no parameters.

### ISSUE THREAD

**Issue by coalooball** [ziglang/zig#18479]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

When I enter `zig ast-check` in the terminal in which version of Zig is 0.11.0, it gets stuck. I think there should be a prompt indicating that parameters are missing.

### Expected Behavior

```bash
zig ast-check
error: expected a positional argument, -femit-bin=[path], --show-builtin, or --name [name]
```

**Comment by Rexicon226** [comment]
this is because ast-check reads from stdin if no file was provided. this is not a bug.

**Comment by coalooball** [comment]
> this is because ast-check reads from stdin if no file was provided. this is not a bug.

I understand. Thank you for your reply.
