### ISSUE TITLE
std.json: Parsing hex strings values with `Int` types results in error

### ISSUE THREAD

**Issue by Raiden1411** [ziglang/zig#18483]
### Zig Version

0.12.0-dev.2043+6ebeb85ab

### Steps to Reproduce and Observed Behavior

```zig
const slice = 
\\ {
\\   "foo": "0x1234"
\\ }
;

const Foo = struct { foo: usize };

_  = try std.json.parseFromSlice(Foo, std.testing.allocator, slice, .{});
```

This will produce and invalidCharacter error from `parseInt`.

### Expected Behavior

For it to parse.

I believe that the fix should be simple by just letting `std.fmt.parseInt` examine the given string since it's already capable of assuming that the prefix "0x" corresponds to base 16.

https://github.com/ziglang/zig/blob/8fd15c6ca8b93fa9888e2641ebec149f6d600643/lib/std/json/static.zig#L773

Would just need to replace it from 10 to 0.

**Comment by Vexu** [comment]
JSON standard doesn't include hex or octal numbers so you'll just have to define a custom `jsonParse` function.
