### ISSUE TITLE
ArrayList.ensureTotalCapacityPrecise wrong behavior

### ISSUE THREAD

**Issue by slonik-az** [ziglang/zig#18499]
### Zig Version

0.12.0-dev.1834+f36ac227b

### Steps to Reproduce and Observed Behavior

Documentation for `ArrayList.ensureTotalCapacityPrecise(new_capacity)` is very clear that the resulting capacity should be equal to `new_capacity`. From current master:
https://github.com/ziglang/zig/blob/60094cc3fc979df0928c412c9fded457172f2060/lib/std/array_list.zig#L437-L441

But the following repro shows failure to adjust the capacity:
```zig
const std = @import("std");
const expectEqual = std.testing.expectEqual;

test "expect ArrayList.ensureTotalCapacityPrecise" {
    const allocator = std.testing.allocator;
    var al = try std.ArrayList(i32).initCapacity(allocator, 16);
    defer al.deinit();

    try expectEqual(@as(usize, 16), al.capacity); // PASS
    try al.ensureTotalCapacityPrecise(5);
    try expectEqual(@as(usize, 5), al.capacity); // FAIL
}
```

### Expected Behavior

As documentation says the resulting capacity must be equal to the `new_capacity`.

The culprit seems to be the following line:

https://github.com/ziglang/zig/blob/60094cc3fc979df0928c412c9fded457172f2060/lib/std/array_list.zig#L447-L447

**Comment by mlugg** [comment]
There's definitely a problem here, but it's unclear whether this is a documentation or implementation issue (or both).

In general, we can't guarantee the *exact* capacity passed in: if it's less than the _length_ of the `ArrayList`, then we don't just want to drop elements silently. We could, of course, assert that the requested capacity is no less than the length.

Even so, I think it's questionable what the behaviour of this method should be when a decreased capacity is requested. The main usefor this function is probably to communicate something along the lines of "I don't expect any more memory to be required past this capacity, so don't bother growing any further". Given this interpretation, it wouldn't necessarily make sense to shrink the allocation if it's already oversized - that's just extra work, and if the user wants an exact-sized buffer later they can just use `toOwnedSlice`. For this reason, I am inclined to say that the status quo behaviour is reasonable, and that this is instead a problem with this function's documentation.

**Comment by slonik-az** [comment]
> We could, of course, assert that the requested capacity is no less than the length.

In my example the length is zero. Initial capacity of `16` and final capacity of `5` are larger than the length. In this case there should be no problem to adjust capacity down from 16 to 5. Resizing down to below `.len` is a totally different matter and it should fail with an appropriate error.

**Comment by squeek502** [comment]
This is not incorrect behavior IMO, the docs are just not as clear as they should be. `ensureTotalCapacity`/`ensureTotalCapacityPrecise` will never shrink the capacity, which should definitely be made explicit in the documentation. If you want to shrink the capacity, `shrinkAndFree` should be used instead.
