### ISSUE TITLE
[proposal] add level parameter to @frameAddress and @returnAddress

### ISSUE THREAD

**Issue by emekoi** [ziglang/zig#1849]
add a level parameter to `@returnAddress` and `@frameAddress` that indicates how far up the stack to go before returning the address. similar to gcc's `__builtin_return_address` and `__builtin_frame_address` ~~this would allow us to replace `@returnAddress` with `@frameAddress(1)` and `@frameAddress()` with `@frameAddress(0)`.~~

**Comment by Rocknest** [comment]
Aren't these two completely different things? frameAddress is the stack pointer and returnAddress is the function pointer?

**Comment by andrewrk** [comment]
LLVM has this level parameter for both functions, but we always set it to zero, because it says:

> The value returned by this intrinsic is likely to be incorrect or 0 for arguments other than zero, so it should only be used for debugging purposes.

That's the same with `__builtin_return_address` and `__builtin_frame_address` when you use clang, and likely the same when you use GCC. 

Can you elaborate on your use case for this proposal?

**Comment by andrewrk** [comment]
We already have `std.debug.dumpCurrentStackTrace`. I think you can call that.

**Comment by emekoi** [comment]
the problem is that the stack trace only goes as far as the signal handler, not up to the code that triggered the segfault.

**Comment by andrewrk** [comment]
I see. The LLVM level parameter of these built-in functions is not the solution. We will have to figure out where in memory the frame pointer gets stored in the case of a signal handler and write code to start dumping the stack trace starting from an arbitrary frame pointer.

**Comment by andrewrk** [comment]
I'm sure this problem has been solved before because, for example, gdb knows how to recover from a signal and then walk up the stack.

**Comment by emekoi** [comment]
i guess i should look at libunwind then.

**Comment by andrewrk** [comment]
I think this is a userland problem and we should continue to hard code the value 0 when using LLVM's return address / frame address intrinsic, for the reasoning mentioned in https://github.com/ziglang/zig/issues/1849#issuecomment-449445018
