### ISSUE TITLE
`defer` footgun with mutable variables

### ISSUE THREAD

**Issue by jonathanmarvens** [ziglang/zig#18490]
Zig, like Go, has the handy `defer` statement to allow a straightforward way to clean up after yourself and relinquish resources you no longer need.

If you take a look at the following example though, there's a subtle footgun that comes with certain uses of the `defer` statement that may not be immediately obvious. I think Zig should at least provide a warning for cases like this.

```zig
const std = @import("std");

// Caller owns the slice.
fn getText(allocator: std.mem.Allocator) ![]u8 {
    var buffer = std.ArrayList(u8).init(allocator);
    try buffer.appendSlice(" Hello, world!\n");
    return try buffer.toOwnedSlice();
}

fn footgun() !void {
    const allocator = std.heap.page_allocator;
    var text: []const u8 = try getText(allocator);
    defer allocator.free(text);                    // <--- Enter footgun...
    text = std.mem.trim(u8, text, " \t\n\r");
    std.debug.print("{s}\n", .{text});
}

pub fn main() !void {
  try footgun();
}
```

In case it's not clear, by the time `allocator.free(text)` is executed, the `text` slice is now a pointer to another address (in this case, just +1 byte). `std.mem.trim()` doesn't modify the underlying bytes but instead simply returns an adjusted pointer and length based on matches of the characters to trim (side note: other than the `[]const` serving as a hint, this behavior is also not immediately clear unless you read the `std.mem.trim()` implementation).

The pattern in my example code is very common, so I fully expect this type of mistake to be made. In Go, the same problem exists but can easily be solved by using `defer` with a closure that captures the value at that exact point via a parameter. Since Zig doesn't have closures, I think Zig should at least provide a warning when `defer` is used with mutable variables.

**Comment by mlugg** [comment]
I don't think it's reasonable to describe this as much of a footgun - I've never seen anybody hit it before, and I've also barely ever seen code which would be likely to be susceptible to this kind of issue. In general, when you acquire a resource, it's a reasonable expectation that you must retain a valid handle to that original resource (in this case, the original return value of`getText`) to release the resource. That Zig doesn't implicitly capture the current value seems completely in-line with the language.

In addition, accessing mutable variables from a `defer` can be an explicitly useful pattern; for instance, having a local flag indicating whether a resource is owned or not:
```zig
const buf = try allocator.alloc(u8, size);
var memory_is_owned = true;
defer if (memory_is_owned) allocator.free(buf);
// [...]
// pass off ownership of `buf`
something.setOwnedBuffer(buf);
memory_is_owned = false;
```

> Since Zig doesn't have closures, I think Zig should at least provide a warning when `defer` s used with mutable variables.

Zig does not have warnings.

**Comment by nektro** [comment]
yeah not losing access to the original allocation of an object is simply one of the few things that zig requires you to remember to do. this does not come up in practice once learned. perhaps a linter could detect this at some point if one wants to be sure.

**Comment by jonathanmarvens** [comment]
@mlugg
> I don't think it's reasonable to describe this as much of a footgun - I've never seen anybody hit it before, and I've also barely ever seen code which would be likely to be susceptible to this kind of issue.

I strongly disagree. I've encountered and written `text = std.mem.trim(u8, text, " \t\n\r")`-style code so many times across numerous languages and codebases. I fully expect programmers to bring the same pattern to Zig (I've done so myself).

> In general, when you acquire a resource, it's a reasonable expectation that you must retain a valid handle to that original resource (in this case, the original return value of`getText`) to release the resource.

I have a C background, so I fully understand this. The thing is though, once you do offer conveniences like `defer` and you have pointers, the likelihood of mistakes like this happening increases. In C, a principled programmer goes out of their way via error checks, `goto`s, *etc.* to make sure to clean up after themselves. I absolutely do consider this a footgun precisely because `defer`'s convenience makes it easier for a programmer to not realize their handle has been invalidated.

> That Zig doesn't implicitly capture the current value seems completely in-line with the language.
> 
> In addition, accessing mutable variables from a `defer` can be an explicitly useful pattern; for instance, having a local flag indicating whether a resource is owned or not:
> 
> ```zig
> const buf = try allocator.alloc(u8, size);
> var memory_is_owned = true;
> defer if (memory_is_owned) allocator.free(buf);
> // [...]
> // pass off ownership of `buf`
> something.setOwnedBuffer(buf);
> memory_is_owned = false;
> ```

To be clear, I'm not suggesting that the behavior should be changed. I agree with you that it works as expected and can be useful. I'm simply pointing out that Zig can, and in my opinion, should at least make this behavior clear to the programmer.

**Comment by Jarred-Sumner** [comment]
> I don't think it's reasonable to describe this as much of a footgun - I've never seen anybody hit it before, and I've also barely ever seen code which would be likely to be susceptible to this kind of issue.

I've definitely hit things like this before

**Comment by IntegratedQuantum** [comment]
> const allocator = std.heap.page_allocator;

This allocator should not be used by newcomers to the language.
Instead the `GeneralPurposeAllocator` should be used, which produces runtime errors for many common allocator misuses.
And it also catches this footgun already:
```zig
pub fn main() !void {
	var gpa = std.heap.GeneralPurposeAllocator(.{}){};
	const allocator = gpa.allocator();
	defer _ = gpa.deinit();
	
	var slice = try allocator.alloc(u8, 128);
	defer allocator.free(slice);
	slice = slice[0..127]; // Footgun
}
```
```
$ zig run test.zig
error(gpa): Allocation size 128 bytes does not match free size 127. Allocation: 
/home/mint/Desktop/test.zig:67:33: 0x220005 in main (test)
 var slice = try allocator.alloc(u8, 128);
                                ^
...
```

**Comment by jonathanmarvens** [comment]
@IntegratedQuantum Respectfully, the specific allocator being used isn't the important aspect of this.

**Comment by notcancername** [comment]
@jonathanmarvens I believe their claim is that catching this error is the responsibility of the allocator, not the language.

**Comment by jonathanmarvens** [comment]
@notcancername This issue applies to any scenario where the usage of a variable in a `defer` statement expects it to be a specific value, so even though my example to demonstrate the issue uses memory allocation, the scope is larger than that.

**Comment by IntegratedQuantum** [comment]
@jonathanmarvens There are many use cases in zig that rely on using variables in the defer statement. The most common example would be
```zig
var list = std.ArrayList(u8).init(allocator);
defer list.deinit();
try list.append(...);
```
A warning for this would just end up printing too many false positives, so everyone would just ignore it.

I think the best solution is to document how defer handles variables and verify the behavior in the respective API if possible, like it's done for the `GeneralPurposeAllocator`.

**Comment by jonathanmarvens** [comment]
@IntegratedQuantum
> A warning for this would just end up printing too many false positives, so everyone would just ignore it.
> 
> I think the best solution is to document how defer handles variables and verify the behavior in the respective API if possible, like it's done for the `GeneralPurposeAllocator`.

Yeah, I think I agree with you. That's probably the best solution. I'm just concerned for all of the folks who'll inevitably accidentally get bitten by the subtle implications of `defer`'s semantics.
