### ISSUE TITLE
Trace/breakpoint trap compiling `@TypeOf` with `undefined` argument

### ISSUE THREAD

**Issue by amp-59** [ziglang/zig#18506]
### Zig Version

0.12.0-dev.2063+804cee3b9

### Steps to Reproduce and Observed Behavior

Compile example program with `zig build-obj typeof_anyopaque_error.zig`
`typeof_anyopaque_error.zig`:
```zig
export fn entry() void {
    const any: anyopaque = undefined;
    _ = @TypeOf(any);
}
```
Result:
```
zig build-obj typeof_anyopaque_error.zig
Trace/breakpoint trap
```

### Expected Behavior

-

**Comment by Vexu** [comment]
Caused by `hasRuntimeBitsAdvanced` returning true for `.Opaque` types.

**Comment by Vexu** [comment]
Yes.
