### ISSUE TITLE
RFC: add @comptimeCast

### ISSUE THREAD

**Issue by perillo** [ziglang/zig#18519]
Consider this example from the language reference (`test_sentinel_mismatch.zig`):
```zig
const std = @import("std");
const expect = std.testing.expect;

test "sentinel mismatch" {
    var array = [_]u8{ 3, 2, 1, 0 };

    // Creating a sentinel-terminated slice from the array with a length of 2
    // will result in the value `1` occupying the sentinel element position.
    // This does not match the indicated sentinel value of `0` and will lead
    // to a runtime panic.
    var runtime_length: usize = 2;
    _ = &runtime_length;
    const slice = array[0..runtime_length :0];

    _ = slice;
}
```

Before the commit introducing the *var is never mutated error*, the user had to add an additional variable and give it a long name to make it visible.

Now, the user also have to add an additional statement, that may be cryptic to new users.

The proposal it to add a new `@comptimeCast` (or something better) builtin so that is is possible to do:
```zig
const slice = array[0..@comptimeCast(2) :0];
```

Not sure if it is possible.

Thanks.

**Comment by Vexu** [comment]
I don't understand what the new builtin you're proposing would do.

**Comment by perillo** [comment]
> I don't understand what the new builtin you're proposing would do.

Sorry, there was a typo in the original example.

The statement is:
```zig
const slice = array[0..@comptimeCast(2) :0];
```

The builtin should convert the *int literal* to the inferred result type, and the compiler should consider the value to be not comptime known.

Another possible name for the builtin is `@literal`.

Thanks.

**Comment by Rexicon226** [comment]
Literals are literals. Why not just use 0..2 ? What do you mean by “not consider the value comptime know”? By definition you cannot convert a runtime into a comptime. I am confused myself :/

**Comment by N00byEdge** [comment]
isn't `const slice = @as([]T, array[0..2:0]);` nicer than casting the bound?

**Comment by perillo** [comment]
> Literals are literals. Why not just use 0..2 ? What do you mean by “not consider the value comptime know”? By definition you cannot convert a runtime into a comptime. I am confused myself :/

Because using `0..2` will not return a slice but an array, since the literals are comptime know.

As an example:
```zig
const std = @import("std");
const debug = std.debug;

pub fn main() void {
    var array = [_]u8{ 3, 2, 1 };
    const slice = array[0..2];

    std.debug.print("typeof(slice): {}\n", .{@TypeOf(slice)});
}
```

will output
```console
*[2]u8
```
instead of
```console
[]u8
```

**Comment by perillo** [comment]
@N00byEdge: in the language reference there are some examples using an additional variable.
The problem is that people reading that code **will** assume that it is the only correct way to do it (I assumed it, as an example).

@InKryption: thanks for the examples.  I will close this issue.

**Comment by mlugg** [comment]
For the record, I did briefly think about this whilst implementing the "local variable is never mutated" error, but it's a bad idea: the only practical use for forcing a value to be runtime is to work around compiler bugs (which we certainly don't want a language built-in for), for documenting runtime behavior in the langref (the language should not be optimized for writing a language reference!), and for writing compiler behavior tests (an internal detail of the compiler so not something we should design the language around).
