### ISSUE TITLE
Wiki links for Vimeo forbid access

### ISSUE THREAD

**Issue by jakobarsement** [ziglang/zig#18514]
**On the ziglang/zig GitHub Community Wiki page [here](https://github.com/ziglang/zig/wiki/Community#individuals), these Vimeo links deny access:**
- https://vimeo.com/showcase/7818787/video/483929038
- https://vimeo.com/showcase/7818787/video/483928961
- https://vimeo.com/showcase/7818787/video/483928663
- https://vimeo.com/showcase/7818787/video/488250361

**Although this link is accessible:**
- https://vimeo.com/showcase/7818787

**Evidence for forbidden links seen below:**
- Browser: Google Chrome
- Not logged in
![broken_vimeos](https://github.com/ziglang/zig/assets/43357341/3e995978-029b-4536-87d6-994d52fa0374)

**Comment by andrewrk** [comment]
Thanks for helping out. However, this issue tracker is for code, not for the wiki. Let's not clog up the issues and send notifications to 330 people just for stuff like this. I edited the wiki to delete the links.
