### ISSUE TITLE
add visionOS os target

### ISSUE THREAD

**Issue by mitchellh** [ziglang/zig#18512]
I'm not sure what is involved to add this, but it'd be nice to be able to compile Zig libraries for Apple's new visionOS set to launch the end of this month. The SDK went final this past week. https://developer.apple.com/visionos/

**Comment by nektro** [comment]
cc @kubkon

**Comment by nektro** [comment]
we'll also get it with https://github.com/llvm/llvm-project/issues/77674

**Comment by andrewrk** [comment]
Is it still a Darwin kernel? Should be a pretty trivial enhancement if so.

**Comment by mitchellh** [comment]
> Is it still a Darwin kernel? Should be a pretty trivial enhancement if so.

Yes, I think it'll _probably_ have a different MachO object value (not sure what the right terminology it is), but don't expect other significant changes.

**Comment by kubkon** [comment]
Potentially blocked by https://github.com/ziglang/zig/pull/18576

**Comment by mitchellh** [comment]
LLVM merged visionOS support in the linker and clang: https://github.com/llvm/llvm-project/issues/77674#event-11520571506

**Comment by andrewrk** [comment]
so, do we call it `xros` like cowards, or `visionos` like lapdogs?

**Comment by mitchellh** [comment]
> so, do we call it `xros` like cowards, or `visionos` like lapdogs?

I recuse myself from this lmao.

**Comment by Rexicon226** [comment]
> so, do we call it `xros` like cowards, or `visionos` like lapdogs?

`xros` is vague and could apply to different things in the future; i think `visionos` is the way.

**Comment by kubkon** [comment]
> `xros` is the SDK name in Xcode, so it's unlikely to apply to something different in the future.
> 
> That being said, this is a terrible name, and I'd also prefer the more self-explanatory `visionos`.

Is it not the same with iOS though? I think it's referred to as `iphoneos` in Xcode (or `xcrun` at least) while LLVM and Zig refers to it as `.ios`.

**Comment by andrewrk** [comment]
Great point, let's proceed with `visionos`.

**Comment by kubkon** [comment]
Prelim support in a branch https://github.com/ziglang/zig/tree/visionos. Full support is currently blocked on Zig embracing LLVM 18 which added support for VisionOS as a target. Standalone `zld` can handle it however provided https://github.com/kubkon/zld/pull/129 and https://github.com/ziglang/zig/pull/19563 land.
