### ISSUE TITLE
zig debug build will cause trace trap while release build will not

### ISSUE THREAD

**Issue by liyu1981** [ziglang/zig#18521]
### Zig Version

0.12.0-dev.1828+225fe6ddb

### Steps to Reproduce and Observed Behavior

Found this when I try to build kcov with build.zig

Following steps can be repeated with my repo: https://github.com/liyu1981/kcov/tree/build-zig-exp
**But sorry this can only be repeated in macos with M1/M2/M3 chip.**

after clone to <lcoal_kcov>

first, build the test program
```bash
cd zig-tests/helloworld
zig build
```

then build kcov with build.zig like follows
```bash
cd <local_kcov>
zig build sign-kcov
```

then if try use the built debug version kcov will get trace trap
```bash
cd <local_kcov>
./zig-out/bin/kcov ./cov zig-tests/helloworld/zig-out/bin/helloworld
.... (lots of output)
zsh: trace trap  ./zig-out/bin/kcov ./cov zig-tests/helloworld/zig-out/bin/helloworld
```

on the other side, if build a release version, there will not be problem
```bash
cd <local_kcov>
zig build -Doptimize=ReleaseFast sign-kcov
./zig-out/bin/kcov ./cov zig-tests/helloworld/zig-out/bin/helloworld
(will not see trace trap but finish normally)
```

I did another interesting try is that using the original CMakeList.txt with DEBUG info, will not have problem, like below
```bash
cd <local_kcov>
mkdir build
cd build
CC="clang" CXX="clang++" cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja ..
ninja
cd ..
./build/src/kcov ./cov zig-tests/helloworld/zig-out/bin/helloworld
(will not see trace trap but finish normally)
```

So generally what I am wondering is: what zig has done in debug phase make the code broken?

Understand this could help me to continue work on build.zig for kcov (otherwise it will be not very meaningful as whenever need a debug version has to go back to CMake).

### Expected Behavior

Not a very urgent case, but would expect even in Zig debug build, kcov can continue to work as it is.

**Comment by Vexu** [comment]
Could it be because of UBSAN? https://github.com/ziglang/zig/wiki/FAQ#why-do-i-get-illegal-instruction-when-using-with-zig-cc-to-build-c-code

**Comment by liyu1981** [comment]
@Vexu thanks, right in the spot. 

After I added 
`"-fno-sanitize=undefined"` to c-flags/cpp-flags pass to Zig, the debug mode works too!
