### ISSUE TITLE
Langref: Are typedefs "Containers" or "Namespaces"?

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#18529]
see https://github.com/ziglang/zig/wiki/Glossary#container vs https://ziglang.org/documentation/master/#Containers

**Comment by nektro** [comment]
namesapces

**Comment by p7r0x7** [comment]
Can this be closed @expikr?

**Comment by Vexu** [comment]
There are no "typedefs" in Zig. If you're talking about putting something like `const ArrayList = std.ArrayList` in your file then I think those are usually referred to as imports.

**Comment by Vexu** [comment]
The wiki seems to list kinds of containers rather than giving a different definition.
