### ISSUE TITLE
Proposal: slice first() and last() methods

### ISSUE THREAD

**Issue by DutchGhost** [ziglang/zig#1852]
Currently, to acces the last element of a slice, you might write something like `slice[slice.len - 1]`. However this puts responsability on the programmer to ensure no overflow happens when the slice's length is 0.

This proposes 2 new methods on slices (if there is a `last()`, there should be a `first()`):

- first() ?*T
- last() ?*T

`first` would return an optional pointer to the first element, null if the slice is empty.
`last` would return an optional pointer the the last element, null if the slice is empty.

Using these functions, std's ArrayList could verry easily implement such functionality as well.
This would also effect all array's, since an array can be converted into a slicy easily.

**Comment by thejoshwolfe** [comment]
These can be implemented in userland. It would look something like this:

```zig
fn first(slice: var) ?std.meta.sliceToPointer(@typeOf(slice)) {
    if (slice.len == 0) return null;
    return &slice[0];
}
```

The function `std.meta.sliceToPointer()` doesn't exist (yet?), but the point is to preserve the const/volatile properties of the slice when translating into a pointer. I'm not too familiar with the `std.meta` package yet, but some utility method like this should probably be in there.

**Comment by DutchGhost** [comment]
I didn't propose a new syntax? These methods would be added to the `[]T` struct.
