### ISSUE TITLE
Meta: move the wiki to a dedicated repository

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#18532]
GitHub's wiki UI sucks

* title is filename, so special symbols in the title messes everything up
* commit history is tied to filename, so renaming an article nukes its history
* no permissions control to prevent vandalism, and the commit history UI makes it hard to detect.
* reverting mistakes clutters up commit history with no way to clean up
* no way to discuss edits collaboratively before committing them

Moving it into its own ziglang/wiki repository means that you can use the Pull Request workflow for better collaboration.

**Comment by andrewrk** [comment]
This issue tracker does not track meta issues.
