### ISSUE TITLE
segfault when accidentally calling a tagged union field

### ISSUE THREAD

**Issue by travisstaloch** [ziglang/zig#18546]
### Zig Version

0.12.0-dev.2158+4f2009de1

### Steps to Reproduce and Observed Behavior

When I accidentally used a field name as a method it caused the compiler to segfault:
```zig
// /tmp/tmp.zig
const U = union(enum) {
    int: isize,
    float: f64,
};
test {
    const f = U{ .float = 20 };
    std.debug.print("{}\n", .{f.int()});
}
```

```console
/tmp $ zig test /tmp/tmp.zig
Segmentation fault (core dumped)
```

### Expected Behavior

some kind of error message and no segfault

**Comment by Rexicon226** [comment]
```thread 515603 panic: InternPool.getCoerced of float not implemented from simple_type to simple_type```
