### ISSUE TITLE
undefined symbol: lib.malloc

### ISSUE THREAD

**Issue by DerryAlex** [ziglang/zig#18550]
### Zig Version

0.12.0-dev.2139+e025ad7b4

### Steps to Reproduce and Observed Behavior

```zig
// lib.zig
pub fn malloc(size: usize) ?[]const u8 {
    const c_fn = @extern(*const fn (usize) callconv(.C) ?[*]u8, .{ .name = "malloc" });
    const raw_ptr = c_fn(size);
    return if (raw_ptr) |ptr| ptr[0..size] else null;
}

// main.zig
const lib = @import("lib.zig");

pub fn main() !void {
    const buf = lib.malloc(256);
    _ = buf;
}
```

```
error: ld.lld: undefined symbol: lib.malloc.2
    note: referenced by lib.zig:2
    note:               main.o:(lib.malloc)
    note: referenced by lib.zig:3
    note:               main.o:(lib.malloc)
```

### Expected Behavior

```
undefined symbol: malloc
```

**Comment by Rexicon226** [comment]
Hmm, interesting.

An easier repo would be this I think:
```zig
extern fn malloc(usize) callconv(.C) ?[*]u8; // Works
// const malloc = @extern(*const fn (usize) callconv(.C) ?[*]u8, .{ .name = "malloc" }); // Doesn't work

pub fn main() !void {
    _ = malloc(10);
}
```

cc @kubkon some insight? The behavior should be identical no?

**Comment by kubkon** [comment]
I would need to properly investigate this but what immediately strikes me as odd is the name of the missing symbol: `lib.malloc.2` when it clearly ought to be just `malloc`. I think we may have a bug in namespacing externs in Sema or something like that.

**Comment by kubkon** [comment]
If I were to investigate this, I would start here https://github.com/ziglang/zig/blob/89d4ac628959fe301ee93b88fdc66ab1988d5f33/src/Sema.zig#L25664

**Comment by Rexicon226** [comment]
Thanks @kubkon, I will investigate in a bit :)
The issue seems serious, this is some pretty core functionality 👀
