### ISSUE TITLE
std.math.pow panics with 'integer part of floating point value out of bounds' when given arguments 0, std.math.maxInt(i64)

### ISSUE THREAD

**Issue by hdert** [ziglang/zig#18553]
### Zig Version

0.12.0-dev.1773+8a8fd47d2

### Steps to Reproduce and Observed Behavior

Compile and run the example program:
```zig
const pow = @import("std").math.pow;

pub fn main() !void {
    // Works fine, within the bounds of an i64
    _ = pow(f64, 0, 9223372036854774784);
    _ = pow(f64, 0, -9223372036854775808);
    // Crashes in std.math.pow's isOddInteger as are outside of the bounds of an i64
    _ = pow(f64, 0, 9223372036854775808);
    _ = pow(f64, 0, -9223372036854785808);
}

```
Program panics with:
```
thread 1383248 panic: integer part of floating point value out of bounds
/usr/lib/zig/lib/std/math/pow.zig:182:40: 0x220edd in isOddInteger (crash_reproduction)
    return r.fpart == 0.0 and @as(i64, @intFromFloat(r.ipart)) & 1 == 1;
                                       ^
/usr/lib/zig/lib/std/math/pow.zig:70:29: 0x21e3f4 in pow__anon_3006 (crash_reproduction)
            if (isOddInteger(y)) {
                            ^
/src/crash_reproduction.zig:8:12: 0x21e226 in main (crash_reproduction)
    _ = pow(f64, 0, 9223372036854775808);
```
This seems to happen because std.math.pow.isOddInteger expects an exponent within the bounds of an i64

### Expected Behavior

Return 0 or -0 as expected. If not possible to find the parity of a number outside the bounds of an i64, return +0, given no problematic side effects could occur.

**Comment by slonik-az** [comment]
Based on the original Golang implementation of `isOddInteger` its argument (pow's exponent) should fit into 53 bits which is the maximum integer range represented by f64 floats as a sequential set (no holes).

**Comment by slonik-az** [comment]
BTW, the most useful in practice of all three IEEE-754-2019 power functions is `powr(x,y)` which is by definition `exp(y*log(x))` and is defined for all floating `x>0`.

**Comment by nektro** [comment]
I believe this panic is happening because the value is NaN

**Comment by hdert** [comment]
> Based on the original Golang implementation of `isOddInteger` its argument (pow's exponent) should fit into 53 bits which is the maximum integer range represented by f64 floats as a sequential set (no holes).
I agree, it seems like [Go's behaviour](https://go.googlesource.com/go/+/refs/heads/master/src/math/pow.go) here is to just return false, as all numbers above that limit are even
```go
if Abs(x) >= (1 << 53) {
	// 1 << 53 is the largest exact integer in the float64 format.
	// Any number outside this range will be truncated before the decimal point and therefore will always be
	// an even integer.
	// Without this check and if x overflows int64 the int64(xi) conversion below may produce incorrect results
	// on some architectures (and does so on arm64). See issue #57465.
	return false
}
```
