### ISSUE TITLE
@hasDecl failed to resolve declaration when located in different source file

### ISSUE THREAD

**Issue by cclin0816** [ziglang/zig#18588]
### Zig Version

0.11.0, 0.12.0

### Steps to Reproduce and Observed Behavior

main.zig:
```zig
const std = @import("std");
const meta = @import("meta.zig");

pub fn hasDecl(comptime Tp: type, comptime name: []const u8) bool {
    return @hasDecl(Tp, name);
}

pub fn main() !void {
    const Closure = struct {
        fn invoke() void {}
    };
    std.debug.print("{} {}", .{ hasDecl(Closure, "invoke"), meta.hasDecl(Closure, "invoke") });
}
```

meta.zig:
```zig
pub fn hasDecl(comptime Tp: type, comptime name: []const u8) bool {
    return @hasDecl(Tp, name);
}
```

zig run main.zig

`true false`

=> the one in main.zig sees the invoke declaration but the one in meta.zig  doesn't
=> also `std.meta.hasFn` in 0.12.0 doesn't work too, which I think is caused by same problem

### Expected Behavior

`true true`

**Comment by jacobly0** [comment]
`@hasDecl` returns false for non-`pub` decls in another file

**Comment by marler8997** [comment]
Maybe `@hasPubDecl` is a better name?

**Comment by jacobly0** [comment]
> Maybe `@hasPubDecl` is a better name?

It doesn't check for `pub` decls, it checks for _accessible_ decls.  Another way to think about it is `@hasDecl(T, "name")` returns whether `T.name` is valid.  If `true` were returned for non-`pub` decls, then tons of generic code would see that `@hasDecl` returned `true`, and then proceed to try to call `@field(T, "name")` which would produce an unrecoverable syntax error.
