### ISSUE TITLE
better standard library abort() and panic() implementations for UEFI

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1858]
abort:
https://github.com/ziglang/zig/blob/2b7e29f791146e901e0479d2af20f1a91ec7165b/std/os/index.zig#L194-L197

panic:
https://github.com/ziglang/zig/blob/2b7e29f791146e901e0479d2af20f1a91ec7165b/std/special/panic.zig#L16-L19

**Comment by kroepke** [comment]
I believe this has been fixed by #2944, maybe close this one?

**Comment by fifty-six** [comment]
panic was handled in 649b872450689511ac3c5526d063c89fff7d898a

and abort was handled in b979fc1bcd6d1bdc19b7f518498fb8c9740d6dea
