### ISSUE TITLE
[Windows] failed to rename compilation results AccessDenied

### ISSUE THREAD

**Issue by ndbn** [ziglang/zig#18594]
### Zig Version

0.12.0-dev.2208+4debd4338

### Steps to Reproduce and Observed Behavior

Windows 10 x64 1709
I have used version `0.12.0-dev.1856+94c63f31f` with no problems.
Then updated to `dev.2150+63de8a598` and start getting errors like:
```
error: failed to rename compilation results ('C:\!WORK\Projects\Zig\Projectname\zig-cache\tmp\303670f556cf6bdf') 
into local cache ('C:\!WORK\Projects\Zig\Projectname\zig-cache\o\8ab6d061e71450d76ff705740ecca5f7'): AccessDenied
```
First suggestion was - long build(`linkLibC` used) with "Build On Save" feature of ZLS, so I disable it (I run `zig build run` in CMD after saving).

But problem returns and I update to `0.12.0-dev.2208+4debd4338`.

Now got similar, but now equal message:
```
error: sub-compilation of compiler_rt failed
    note: failed to rename compilation results ('C:\Users\Username\AppData\Local\zig\tmp\a77a5b22cdd3d525') 
into local cache ('C:\Users\Username\AppData\Local\zig\o\64d7671beb08ddb089ab5b776f523a20'): AccessDenied
```

There are no understandable steps to reproduce, it can happen after second rebuild or tenth.

I think it related to "Compilation: ***" commits 2 weeks ago.

For dev.2150 was need to delete local zig-cache to fix it, for dev.2208 need to delete AppData\Local\zig to fix and it sad.

upd: Seems It can be reproduced, after cleaning both caches and one successful build I've got this message after renaming variable or use by_pointer instead by_value for variable,

upd2: Updated to `0.12.0-dev.2250+7116b0221`, cleaned both caches, got access denied with local cache at 4th rebuild.

### Expected Behavior

Successful build

**Comment by ndbn** [comment]
Some research.
Error message: `error: failed to rename compilation results ('zig-cache\tmp\a32315791adcaca9') into local cache ('zig-cache\o\eb0460814e6808eb3ee9ecbf8737b0d6'): AccessDenied`
`tmp\a32315791adcaca9` and `o\eb0460814e6808eb3ee9ecbf8737b0d6` both are folders and both exists.

As I can understand called std.os.windows.renameatW, then it call NtSetInformationFile and as I see in ProcMon with `ReplaceIfExists=True`.

Quote from [this](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_file_rename_information)
> Even if ReplaceIfExists is set to TRUE, the rename operation will still fail if a file with the same name already exists and is a directory, a read-only file, or a currently executing file.

**Comment by ndbn** [comment]
Error logic [here](https://github.com/ziglang/zig/blob/master/src/Compilation.zig#L2374)
Or need `var seen_eaccess = true;` or check must be like `if (seen_eaccess) return error.AccessDenied;`

**Comment by matu3ba** [comment]
Did you maybe modify build.zig while compiling? I don't understand your reproduction steps. This could be #18459 or related.

**Comment by ndbn** [comment]
> Did you maybe modify build.zig while compiling? I don't understand your reproduction steps. This could be #18459 or related.
I point to a bug in above comment, at line https://github.com/ziglang/zig/blob/master/src/Compilation.zig#L2374
`seen_eaccess` is initialised with false `var seen_eaccess = false;` and this check `if (!seen_eaccess) return error.AccessDenied;` is always executed, but obviosly it must happen only at second iteration after `seen_eaccess = true;`
This is very often mistake, branch `if` always true because value never mutated before `if` and have init value that make this `if` always true
