### ISSUE TITLE
segfault and bogus error message when initializing tuple with missing fields

### ISSUE THREAD

**Issue by xdBronch** [ziglang/zig#18609]
### Zig Version

0.12.0-dev.2271+14efbbfd8

### Steps to Reproduce and Observed Behavior

```zig
test {
    _ = @as(struct { u32 }, .{});
}
```
release build gives `b.zig:2:30: error: missing struct field: d` but if there are more fields
```zig
test {
    _ = @as(struct { u32, u32 }, .{});
}
```
it segfaults
a debug build hits an OOB in both cases with this stack trace
<https://gist.github.com/xdBronch/55ceaa14b76eb8cecc32cf7c742ce07c>

### Expected Behavior

no crash and proper error message in both cases, probably `error: missing struct field: 0`

**Comment by slonik-az** [comment]
possibly related to #17349

**Comment by Vexu** [comment]
Both examples panic in the same place where `finishStructInit` is trying to use the `field_names` of a tuple which doesn't have them.

**Comment by xdBronch** [comment]
looking at 17349 and the pr that was meant to solve it there seem to be quite a few issues about this bug but i noticed the bad error message seems to be exclusive to when the tuple type only has 1 field with an empty init, anything else seems to crash or give a correct error message. very strange

**Comment by Vexu** [comment]
> very strange

That is to be expected when dealing with UB.
