### ISSUE TITLE
stdlib proposal: replace `Reader.readStructbig` with a function taking the endianness as a parameter

### ISSUE THREAD

**Issue by Khitiara** [ziglang/zig#18603]
Currently, `Reader` (and `AnyReader` and `GenericReader`) currently have two functions for marshalling an `extern struct`, `readStruct` and `readStructBig` which read native- and big-endian structs respectively. This leaves no option for the (albeit niche) case of reading a struct from a little-endian bytestream on a native big-endian system (apart from reimplementing `readStructBig` with the opposite check in user code). Id like to propose the following function to alleviate this situation, with a basic implementation included here:

```zig
pub fn readStructEndian(self: Self, comptime T: type, endian: std.builtin.Endian) anyerror!T {
    var res = try self.readStruct(T);
    if (native_endian != endian) {
        mem.byteSwapAllFields(T, &res);
    }
    return res;
}
```

**Comment by RossComputerGuy** [comment]
If anyone isn't already on this, I'll take a look at implementing this. Consistency will be nice and I could use this in a couple of my own packages.
