### ISSUE TITLE
Unused bad pointer in comptime expression, crashes the compiler

### ISSUE THREAD

**Issue by uben0** [ziglang/zig#18625]
### Zig Version

0.12.0-dev.2063+804cee3b9

### Steps to Reproduce and Observed Output

Imagine you have a tree like data structure. And you naively named one of its method the same as one of its field.

```zig
const Hello = union(enum) {
    foo: []const Hello,
    bar: *const Hello,

    // fn bar(self: Hello) Hello {
    //     return self;
    // }
};

pub fn main() !void {
    _ = (Hello{ .foo = &.{} }).bar();
}
```

When trying to call the method, the following error message will be emitted at compilation:

```
src/main.zig:11:31: error: type '*const main.Hello' not a function
    _ = (Hello{ .foo = &.{} }).bar();
        ~~~~~~~~~~~~~~~~~~~~~~^~~~
```

The `.bar` notation did not refer to the method, but to the field. This can be understood even without a hint about the ambiguity (which would be by the way a good thing to add).

But this error message is not always emitted (non deterministic). Because, as far as I understand it, the compiler is performing compile time optimization, thus tries to access the `bar` field and crashes as it is not the active field of the union (statically casting `[]const Hello` to `*const Hello`, which gives a bad pointer).

In some sens, I don't really consider this a bug, as a bad union access is performed by the user (the user is creating the bug, not the compiler). But in the other hand, it took me time to understand what was going on, because in my case, the error message never showed up. It only showed up when I made a minimal reproducible example.

I don't understand why the compiler is crashing here, because the bad pointer is actually never explicitly used.

I don't know how Zig is doing compile time internally, but let me guess:

- In comptime, values are living on the heap and uses reference counting.
- In comptime, values are dynamically typed and store there own type info along there value.
- When the `Hello` value is created, an empty slice is created.
- When `.bar` is accessed, the compiler tries to access the type info of the `.bar` field, thus tries to dereferenced a value that doesn't exist.

**Comment by mlugg** [comment]
Any compiler crash is a bug. What would be UB at runtime must be a compile error at comptime.
