### ISSUE TITLE
Win32Error number 258 name typo.

### ISSUE THREAD

**Issue by Trevor-Strong** [ziglang/zig#18629]
### Zig Version

0.12.0-dev.2139+e025ad7b4

### Steps to Reproduce and Observed Behavior

The name of the Win32 error code 258 is named `IMEOUT` in the `Win32Error` enum, instead of `WAIT_TIMEOUT`

### Expected Behavior

The error code enum name to match the C-macro name, in this case `WAIT_TIMEOUT`. 

See [here](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-)

**Comment by Rexicon226** [comment]
I agree that this is something to be fixed. 
If you'd like you can just open a PR and fix it, easy first contribution :)

(Note I am not a core member, and merely a frequent contributor)

**Comment by paperdave** [comment]
this issue can be closed now, right?
