### ISSUE TITLE
analyze.cpp:type_requires_comptime:5127

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#1862]
I'd like to add methods to an opaque type. I attempted to do so by wrapping it in a struct. However am getting this failure:

bug.zig:
```
const c_ptr = @OpaqueType();

pub const State = struct {
    ptr: c_ptr,
};

extern var foo: c_ptr;

pub fn main() !void {
    const p = State { .ptr = foo };
}
```
```
$ zig build-exe bug.zig 
unreachable: zig/src/analyze.cpp:type_requires_comptime:5127
Aborted (core dumped)
```

**Comment by andrewrk** [comment]
Correct behavior is `error: opaque type has unknown size and therefore not allowed in struct`.

Recommended pattern is to name the type after the opaque type, not the pointer. So it would be `const Foo = @OpaqueType();` and then your field would be `ptr: *Foo`.

**Comment by daurnimator** [comment]
The goal of this snippet was to be able to add methods to an opaque type by wrapping it in a struct. Is there a reason that *shouldn't* be allowed?

**Comment by andrewrk** [comment]
There is a very good reason: structs must have known size.
