### ISSUE TITLE
False dependency loop in tagged union with member of type `@typeInfo().Union.tag_type`

### ISSUE THREAD

**Issue by abachrati** [ziglang/zig#18630]
### Zig Version

0.12.0-dev.2296+46d592e48

### Steps to Reproduce and Observed Behavior

I'm not sure if this is considered 'correct' zig code, but the following does not compile:
```zig
const Tag = @typeInfo(Foo).Union.tag_type.?;

const Foo = union(enum) {
    a: Tag,
};

pub fn main() void {
    _ = Foo{ .a = .a };
}
```
Gives the error
```
t.zig:3:13: error: union 't.Foo' depends on itself
const Foo = union(enum) {
            ^~~~~
```

### Expected Behavior

The code should compile like the following; without any error.
```zig
const Tag = enum {
    a,
};

const Foo = union(enum) {
    a: Tag,
};

pub fn main() void {
    _ = Foo{ .a = .a };
}
```

**Comment by nektro** [comment]
not a bug imo. calling `@typeInfo` requires the type info to be fully resolved. one of the fields needing a result of that is unresolvable.

**Comment by abachrati** [comment]
> not a bug imo. calling `@typeInfo` requires the type info to be fully resolved. one of the fields needing a result of that is unresolvable.

That's fair enough, I thought it might not be correct. Should I close this issue then?

**Comment by nektro** [comment]
I'm not a core team member, just avid contributor. you're welcome to close or u can wait for their say on it
