### ISSUE TITLE
Distributed builds (similar to distcc + ccache)

### ISSUE THREAD

**Issue by theoparis** [ziglang/zig#18645]
This would involve creating a distributed cache system and distributing the compilation load across multiple machines. I'm not sure what the best way of implementing this kind of change would be. However, it sounds like it could benefit both the zig CI and other zig projects.  For example, I have been trying to make a zig-based linux distribution and this would hopefully speed up compilation times.

**Comment by nektro** [comment]
`zig build` steps could potentially become distributed but zig code is compiled in a single compilation unit and can't be. imo im not sure if this is worth the effort in the build system directly since zig already makes use of host resources much more efficiently than the compilers employed by distcc. for a zig-powered linux distro you could distribute the building at the package level instead of the single compilation level.

**Comment by RossComputerGuy** [comment]
Yeah, this is something I would be interested in but with the state of the compiler right now, it would take a massive effort. Maybe this could be slowly worked on over time, adapting the compiler to support the behaviors needed and then adding the actual distribution part. The other problem is figuring out how to distribute the actual workloads. You wouldn't want to have too many workloads on a single system, you'd want to evenly distribute the workload across. The easiest part would be is synchronizing the cache imo.

**Comment by matu3ba** [comment]
> distributed cache system and distributing the compilation load across multiple machines

Personally I find the complete absence of security not great (kernels + browsers reasonably solved this use case via various sandboxing techniques) and the existence of a separate tool hints to me the not good state of art regarding ci libraries.

To me only having a solution for distributed execution sounds like a potential local design maximum, if [you might want to configure and scale things up and probably do not want to learn yet another tool for the same thing](https://gregoryszorc.com/blog/2021/04/07/modern-ci-is-too-complex-and-misdirected/).
