### ISSUE TITLE
build.zig.zon or `zig fetch` proxy error

### ISSUE THREAD

**Issue by Ziqi-Yang** [ziglang/zig#18679]
### Zig Version

0.12.0-dev.2313+bf7ebfa67

### Steps to Reproduce and Observed Behavior

with this `build.zig.zon` file:
```zig
.{
    .name = "raygreet",
    .version = "0.1.0",

    .dependencies = .{
        .zap = .{
            .url = "https://github.com/zigzap/zap/archive/refs/tags/v0.1.7-pre.tar.gz",
            .hash = "1220002d24d73672fe8b1e39717c0671598acc8ec27b8af2e1caf623a4fd0ce0d1bd",
        },
    },

    .paths = .{
        "",
    },
}
```
Run command (assuming that you have a socks proxy at `127.0.0.1:7890`:
`env all_proxy=http://127.0.0.1:7890 zig build`, it produces an error:
```
Fetch Packages [2/1] zap... /home/zarkli/proj/raygreet/raygreet/build.zig.zon:7:20: error: invalid HTTP response: EndOfStream
            .url = "https://github.com/zigzap/zap/archive/refs/tags/v0.1.7-pre.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Same issue for `zig fetch`.   
Note that it seems that zig won't be affected by `env http_proxy=http://127.0.0.1 zig build`  or `env all_proxy=socks5://127.0.0.1:7890 zig build`, it just cannot process (due to my network issue, I cannot connect to Github directly).

### Expected Behavior

run correctly

**Comment by Ziqi-Yang** [comment]
use [graftcp](https://github.com/hmgle/graftcp) to solve the problem.

**Comment by Hailaylin** [comment]
In my machine, with WSL2 ubuntu open mirror network , and use local proxy like ``127.0.0.1:7899``，[graftcp](https://github.com/hmgle/graftcp) can`n fix it too.

problem like this:

```bash
$ graftcp -p 3333 zig build
~/microzig/tools/regz/build.zig.zon:15:20: error: invalid HTTP response: EndOfStream
            .url = "https://github.com/mattnite/zig-build-libxml2/archive/fab68b5fb06704ef4bdaa221726493a4b6af04b5.tar.gz",
```

have any methor?

**Comment by Hailaylin** [comment]
> In my machine, with WSL2 ubuntu open mirror network , and use local proxy like `127.0.0.1:7899`，[graftcp](https://github.com/hmgle/graftcp) can`n fix it too.在我的机器中，使用 WSL2 ubuntu 打开镜像网络，并使用像 `127.0.0.1：7899` 这样的本地代理，[graftcp](https://github.com/hmgle/graftcp) 也无法修复它。
> 
> problem like this: 像这样的问题：
> 
> ```shell
> $ graftcp -p 3333 zig build
> ~/microzig/tools/regz/build.zig.zon:15:20: error: invalid HTTP response: EndOfStream
>             .url = "https://github.com/mattnite/zig-build-libxml2/archive/fab68b5fb06704ef4bdaa221726493a4b6af04b5.tar.gz",
> ```
> 
> have any method? 有什么方法吗？

I find a method : disable all env about proxy and run

```bash
env -u https_proxy -u http_proxy -u HTTP_PROXY -u HTTPS_PROXY zig build
```

and **it work** in my wsl2 ubuntu terminal! Hopefully i can help somebody.
