### ISSUE TITLE
stage3: Can't build compiler on 8GB machine

### ISSUE THREAD

**Issue by ominitay** [ziglang/zig#18675]
### Zig Version

master branch commit dcaf43674e

### Steps to Reproduce and Observed Behavior

Attempting to build Zig from source fails on my laptop, which has 8GB of RAM (of which 5.7GiB is usable according to `free -h`). A further 8GiB of swap is available to the system. An error is produced, which stops the build process at stage3:
```
zig build-exe zig Debug native: this step declares an upper bound of 8000000000 bytes of memory, exceeding the available 6147563520 bytes of memory
note: use --maxrss to override the default
```
The following commands were used to build the compiler:
```
cmake -B build -G Ninja -DZIG_STATIC_LLVM=ON -DCMAKE_PREFIX_PATH="$(~/llvm17/bin/llvm-config --prefix)"
cmake --build build
```

### Expected Behavior

The expected behaviour would be for Zig to build successfully, or to at least attempt to do so. Even if there is good reason for Zig to not at all attempt to build on a system with less memory than 8GB, it is clearly not considering the amount of swap available, which should be accounted for at the very least. When manually invoking zig to apply the maxrss flag, outside of the cmake compilation process, the stage3 compiler builds successfully: `./build/zig2 build --prefix ./build/stage3 --zig-lib-dir ./lib -Dconfig_h=./build/config.h -Denable-llvm -Dno-langref -Dno-autodocs -Dtarget=native -Dcpu=native -Dversion-string=0.12.0-dev.2475+dcaf43674 --maxrss 8000000000`

**Comment by kubkon** [comment]
Also, apologies for accidentally closing the issue - mistap on a phone!

**Comment by kubkon** [comment]
For the record, you should be able to reduce the hard limit here https://github.com/ziglang/zig/blob/dcaf43674e35372e1d28ab12c4c4ff9af9f3d646/build.zig#L626 if you are not trying to build on an 8GB macbook. Sadly I had to temporarily bump it fron 7 to 8GB when upstreaming the latest MachO rewrite but will do my best to bring it back down as much as I can.

**Comment by ominitay** [comment]
Thanks, it's nice to have a way to work around it, but perhaps there should be a flag available to the cmake command to override this? Or otherwise shouldn't the compiler take into account swap size?

**Comment by kubkon** [comment]
I will defer this to @andrewrk as he's the mastermind behind this config option as far as I remember. Either way, none is the excuse for me bumping the peak usage but that much. In my defence, I wanted to merge a working new MachO driver and start optimising afterwards so that we would avoid potential nasty merge conflicts in the near future.

**Comment by alberic89** [comment]
You can try to “compress” your RAM.
I add done it with this script : https://github.com/Botspot/pi-apps/blob/master/apps/More%20RAM/install
It is really working, and I don't had problem to compile Zig on an 8 GB RAM machine.

**Comment by ominitay** [comment]
That's unrelated to the issue, please read the comment about swap space. ZRAM acts as a swap device, and so wouldn't work around this issue.

**Comment by ominitay** [comment]
As-in, even if I were to allocate 4GB to ZRAM, Zig would think that I have *even less* memory available.
