### ISSUE TITLE
values.zig from documentation throws errors.

### ISSUE THREAD

**Issue by TheAnonymous** [ziglang/zig#1867]
When I tried to compile the values.zig file from the [documentation](https://ziglang.org/documentation/master/#Values) it throws some errors.

```
~/learning_zig/values.zig:35:26: error: use of undeclared identifier 'anyerror'
    var number_or_error: anyerror!i32 = error.ArgNotFound;

~/learning_zig/values.zig:38:27: error: use of undeclared identifier 'number_or_error'
        @typeName(@typeOf(number_or_error)), number_or_error);

~/learning_zig/values.zig:40:5: error: use of undeclared identifier 'number_or_error'
    number_or_error = 1234;

~/learning_zig/values.zig:43:27: error: use of undeclared identifier 'number_or_error'
        @typeName(@typeOf(number_or_error)), number_or_error);

```

tested on mac os 10.14.2 with zig 0.3.0+

**Comment by andrewrk** [comment]
You're looking at master branch of documentation, so you'll have to use master branch of Zig. I'm not sure what `0.3.0+` is. Examples of a version number would be `0.3.0+f6cd6838` or `0.3.0`.

**Comment by TheAnonymous** [comment]
You are right thx

**Comment by achou11** [comment]
Ran into this issue too, and it seems that the installation via homebrew installs version `0.3.0+`. Might want to look into it and see what's happening there.
