### ISSUE TITLE
Incorrect Loop Optimization with Atomic

### ISSUE THREAD

**Issue by toziegler** [ziglang/zig#18698]
### Zig Version

0.12.0-dev.2271+14efbbfd8

### Steps to Reproduce and Observed Behavior

godbolt link: https://godbolt.org/z/YaazKPfM9

```zig
const std = @import("std");
const Atomic = std.atomic.Value;

pub fn set_true_after_sleep(atomic: *Atomic(bool)) void {
    std.debug.print("set true\n", .{});
    atomic.store(true, .SeqCst);
}

pub fn main() !void {
    var atomics: [1]Atomic(bool) = .{Atomic(bool).init(false)};
    // start handle thread
    var handle = try std.Thread.spawn(.{}, set_true_after_sleep, .{&atomics[0]});
    while (true) {
        for (atomics) |atomic| { // optimized away despite side-effect
            if (atomic.load(.SeqCst)) {
                std.debug.print("hello world\n", .{});
                return;
            }
        }
    }
    handle.join();
}

```
It seems that the body of the `for loop` is optimized away. The code does never terminate despite the fact that the `handle` thread sets the atomic variable to true (the print of the handle thread is observed).

### Expected Behavior

The minimal example terminates and prints `hello world` as the side-effect of the handle thread is correctly observed.

**Comment by leecannon** [comment]
`|atomic|` is a copy try `|*atomic|`

**Comment by toziegler** [comment]
Thanks, that works indeed for this minimal example. I have another problem in a much more complex project where it boils down to this effect (at least I thought and there I actually use `|*atomic|`). I will close this issue for now until I can provide a better minimal example.
