### ISSUE TITLE
fs tests hangs on FreeBSD

### ISSUE THREAD

**Issue by mgxm** [ziglang/zig#1870]
```
./bin/zig test ../std/index.zig
Test 1/703 std...OK
Test 2/703 std.ArrayList.init...OK
Test 3/703 std.ArrayList.basic...OK
......
Test 208/703 write a file, watch it, write it again...
```

**Comment by andrewrk** [comment]
Please disable this particular test for now. I believe it is already disabled for Windows. There are several problems with coroutines right now which I am tackling in a big coroutine rewriting project, which is currently blocking on copy-elision branch.

**Comment by andrewrk** [comment]
This test is disabled. I will be sure to test it carefully on freebsd before re-enabling the test.
