### ISSUE TITLE
RFC: Interest in a Sparse Set datastructure in the stdlib?

### ISSUE THREAD

**Issue by VisenDev** [ziglang/zig#18710]
A sparse set is useful for when there is a large range of possible elements, but only a few of those elements will be filled. It has much less memory use than would otherwise be required to store a large array.

It is very commonly used to implement entity component systems.

Would this be useful to have alongside other data structures present in the stdlib?

**Comment by slonik-az** [comment]
TL;DR: I am against having Sparse Sets in `stdlib`

Don't get me wrong. Sparse sets are useful and there should be implementations in Zig, but outside of `std` for the following reasons:

1. They are niche and are used in special circumstances.
2. Different implementations are used depending on specifics of the problem and performance tradeoffs. It is had to agree on one canonical implementation that rules them all.

Just my two cents.

**Comment by InKryption** [comment]
We already have `std.bit_set` and `std.AutoHashMap(V, void)` for these use cases.
