### ISSUE TITLE
0.11.0 HTTP Server response chunked transfer-encoding and content-length header

### ISSUE THREAD

**Issue by peteyycz** [ziglang/zig#18724]
https://github.com/ziglang/zig/blob/67709b638224ac03820226c6744d8b6ead59184c/lib/std/http/Server.zig#L444

I was wondering why `response.do()` function reads the `content-length` header in case there is a `transfer-encoding` header present in response headers, according to the [spec](https://greenbytes.de/tech/webdav/rfc2616.html#rfc.section.4.4):
> Messages MUST NOT include both a Content-Length header field and a non-identity transfer-coding. If the message does include a non-identity transfer-coding, the Content-Length MUST be ignored.

In case the client doesn't send a content-encoding header (in my case) the server breaks because it's trying to unwrap a null value.

**Comment by nektro** [comment]
if this is a bug please fill out the template as directed on the new issue page. if this is a question please ask in one of the great [Community](https://github.com/ziglang/zig/wiki/Community)s.

**Comment by peteyycz** [comment]
I'll submit to communities then. In case it turns out to be a bug I'll submit a proper issue here. Sorry

**Comment by ianprime0509** [comment]
The line you linked was in fact a bug (it's a typo, it should have been getting the value of the Transfer-Encoding header), but it has since been fixed in #16761, which is unfortunately not part of 0.11.0 (only master for now).
