### ISSUE TITLE
for loop error

### ISSUE THREAD

**Issue by tylitianrui** [ziglang/zig#18734]
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

- file name  `x.zig`  content:
```
 test "for" {
    const string = [_]u8{ 'a', 'b', 'c' };
    for (string, 0..) |character, index| {
        _ = character;
        _ = index;
    }
}

```
- execute command 
```
zig  test   x.zig
```
- error message
```
x.zig:5:16: error: expected ')', found ','
    for (string, 0..) |character, index| {
               ^
```

### Expected Behavior

test  pass

**Comment by Vexu** [comment]
Multi-object for loops were added in 0.11.0
https://ziglang.org/download/0.11.0/release-notes.html#Multi-Object-For-Loops
