### ISSUE TITLE
undefined symbols when cross-compiling Windows from Linux and linking LLVM (user project)

### ISSUE THREAD

**Issue by davidgm94** [ziglang/zig#18737]
### Zig Version

0.12.0-dev.2500+c085c6ecd

### Steps to Reproduce and Observed Behavior

I am getting some errors when trying to link LLVM built with zig-bootstrap in my own project. I can't get to link some symbols. It could have to do to some error on my own, but I am not convinced. You can easily specify a custom LLVM path with `-Dllvm_path`

```
git clone https://github.com/birth-software/nativity
cd nativity
 zig build -Dtarget=x86_64-windows-gnu -Dcpu=x86_64_v3 --verbose --verbose-link
```

[Detailed output ](https://zigbin.io/f2f72a)

Simplified output:

```
install transitive failure
└─ install nat transitive failure
   └─ zig build-exe nat Debug x86_64-windows-gnu 2 errors
error: lld-link: undefined symbol: std::__1::codecvt<char, char, int>::id
    note: referenced by libclangFrontend.a(CompilerInvocation.cpp.obj):(.refptr._ZNSt3__17codecvtIcciE2idE)
    note: referenced by libclangFrontend.a(LayoutOverrideSource.cpp.obj)
    note: referenced by libclangCrossTU.a(CrossTranslationUnit.cpp.obj)
error: lld-link: undefined symbol: _setjmp
    note: referenced by libLLVMSupport.a(CrashRecoveryContext.cpp.obj):(llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>))
```

### Expected Behavior

Compilation success

**Comment by ypsvlq** [comment]
this is because https://github.com/ziglang/zig-bootstrap is using a version from before the switch to UCRT

**Comment by davidgm94** [comment]
I can confirm the issue was caused by the reason @ypsvlq gave, so I am closing because it's not related to the Zig repository.
