### ISSUE TITLE
Erroneous `local variable is never mutated` error when assiging to dereference

### ISSUE THREAD

**Issue by Vexu** [ziglang/zig#18751]
### Zig Version

0.12.0-dev.2508+18c49ce17

### Steps to Reproduce and Observed Behavior

```zig
comptime {
    var y: *u64 = undefined;
    y.* = 0;
}
```

### Expected Behavior

No error.

**Comment by nektro** [comment]
I don't think this is a bug because the address the backs the `*u64` never changes, even if the pointed-to value does.

**Comment by Vexu** [comment]
Ah right, my mistake.
