### ISSUE TITLE
occasional error:FileNotFound with empty zig cache on MacOS

### ISSUE THREAD

**Issue by motiejus** [ziglang/zig#18763]
[`hermetic_cc_toolchain`](https://github.com/uber/hermetic_cc_toolchain/) MacOS occasionally see `error: FileNotFound` when compiling a zig program for the first time:

```bash
$ ZIG_LOCAL_CACHE_DIR=/tmp/zig-cache ZIG_GLOBAL_CACHE_DIR=/tmp/zig-cache zig build-exe -target x86_64-macos-none -mcpu=baseline -fstrip -OReleaseSafe zig-wrapper.zig
error: FileNotFound
```

If the user receives such error, subsequent runs of `zig build` fail with the same error. The only known mitigation is to wipe zig cache and try again, then it always succeeds.

A few comments:
* I wasn't able to reproduce this in a "lab" no matter how much I tried.
* Only MacOS users are known to be affected. This report has details about x86_64, I am not sure if I received reports on aarch64.
* These reports spike after a MacOS system upgrade. Users have learned to remove the zig cache directory and move on, which made it quite difficult to get it (which we do have now!).

Attaching an archive of `/tmp/zig-cache` from the machine that *just* got this error.

If there is anything more I can provide, let me know, I will do my best to instruct the users to do so.

### Files and versions

- zig `0.12.0-dev.2127+fcc0c5ddc`
- Specific version of `zig-wrapper.zig` is [this](https://github.com/uber/hermetic_cc_toolchain/blob/v2.2.1/toolchain/zig-wrapper.zig).
- [zig-cache.tar.gz](https://github.com/ziglang/zig/files/14110438/zig-cache.tar.gz) provided by @nadavwe.

cc @jacobly0 to whom this might be of interest, he worked on cache races before.

**Comment by jacobly0** [comment]
I'd be curious what the stderr output will be on version `0.12.0-dev.2475+dcaf43674` or later, which is expected to be a bit more descriptive.  Also, can you confirm whether any other zig processes might be accessing `/tmp/zig-cache` at the same time as this failed command?

**Comment by jacobly0** [comment]
I have written a workaround that, while it is not expected to prevent this error from occurring, which would require actually knowing how it is happening, should at least change the mitigation to "try again" with no cache wipe required.

**Comment by motiejus** [comment]
> Also, can you confirm whether any other zig processes might be accessing `/tmp/zig-cache` at the same time as this failed command?

It is very unlikely that there were multiple invocations of `zig build-exe` when this failed. I.e. the toolchain does this single action before doing any parallel work. When I say unlikely, I mean the users should go out of their way to do it; but not impossible.

> I have written a [workaround](https://github.com/ziglang/zig/pull/18792) that, while it is not expected to prevent this error from occurring, which would require actually knowing how it is even happening, should at least change the mitigation to simply "try again" with no cache wipe required.

I suggest I reword the error message to instruct the user to:
- paste the full output to this issue.
- retry the command (with your workaround when landed, but no clearing of the cache).

... and then we wait for an undetermined amount of time.

How does that sound?

**Comment by mikdusan** [comment]
On the assumption that this only happens when zig-cache is in `/tmp`, is it possible the systems have been customized and are cleaning `/tmp` on a daily schedule? macos can be tweaked with `/etc/periodic.conf` or `/etc/periodic.conf.local`. See `man periodic.conf`.

**Comment by motiejus** [comment]
> On the assumption that this only happens when zig-cache is in `/tmp`, is it possible the systems have been customized and are cleaning `/tmp` on a daily schedule? macos can be tweaked with `/etc/periodic.conf` or `/etc/periodic.conf.local`. See `man periodic.conf`.

That could be. We don't control when users clean their cache.

**Comment by mikdusan** [comment]
A detail question; is the error _message_ `error: FileNotFound` or something with some text like this:

```
error: unexpected error: parsing input file failed with error FileNotFound
```

**Comment by jacobly0** [comment]
@mikdusan On the version of zig that the reproduction happened the output was just `error: FileNotFound`, but on master the error is expected to be something like `error: unexpected error: parsing input file failed with error FileNotFound`.

**Comment by mikdusan** [comment]
I'm speculating that an external event such as factory macos cleaning /tmp periodically. Unfortunately latest macos has changed from scripts to a binary doing the work so I don't have all the details but I will assume that removal is by some kind of date. And in `zig-cache` one of the oldest hits is `libcompiler_rt.a` so it's not a stretch to see that the `zig-cache/o` entry can be removed at some unpredictable time (my current best guess is APPROX every 3 days, and not on some absolute hour, but a jittered time so we can't assume midnight, etc).

To simulate this:

1. nuke the cache
2. create a bare bone exe `pub fn main() void {}`
3. build the exe and populate cache
```
zig build-exe z0.zig`
```

**Comment by motiejus** [comment]
I am planning to release `hermetic_cc_toolchain` tomorrow which will include the updated Zig SDK and instructions to paste the error message here. Hopefully we will get a meaningful report.

> I'm speculating that an external event such as factory macos cleaning /tmp periodically is the culprit. Unfortunately latest macos has changed from scripts to a binary doing the work so I don't have all the details but I will assume that removal is by some kind of date.

Could be. If you can help me with instructions on how to check it, I would pass it on to affected-colleagues-of-the-past to confirm or deny that this exists on their machine.

**Comment by mikdusan** [comment]
> Could be. If you can help me with instructions on how to check it, I would pass it on to affected-colleagues-of-the-past to confirm or deny that this exists on their machine.

I checked on macos 11 and macos 14, tmp cleanup is enabled by default.

**Comment by andrewrk** [comment]
Zig doesn't implement GC on the cache yet, so I understand the desire to use /tmp, but the bottom line is that it's not supported to race file deletion from the zig cache while using the compiler.

As it stands, the user must only delete the zig-cache directory when they have independently ensured that no compiler processes will run from start to finish of the deletion operation. Also they must fully delete the directory; running the compiler after a partial deletion is not supported.

**Comment by motiejus** [comment]
Cache purging by MacOS sounds like a more and more plausible explanation.

Any tips on what would be a better place to store zig cache on MacOS? It needs to be an absolute path, because of bazel limitations.

**Comment by mikdusan** [comment]
I understand a goal is to set _both_ local/global cache to the same value.
Perhaps simply set them both to what the default global cache likes to be:

```
export ZIG_GLOBAL_CACHE_DIR=$HOME/.cache/zig
export ZIG_LOCAL_CACHE=$ZIG_GLOBAL_CACHE_DIR
```

**Comment by jacobly0** [comment]
`/var/tmp` is marginally better, although it won't be cleared every reboot on mac like `/tmp` was.

**Comment by mikdusan** [comment]
here's a find:

```
man confstr
getconf DARWIN_USER_CACHE_DIR
```

```
_CS_DARWIN_USER_TEMP_DIR
  Provides the path to a user's temporary items directory. The directory will be created it if does not
  already exist. This directory is created with access permissions of 0700 and restricted by the
  umask(2) of the calling process and is a good location for temporary files.

  By default, files in this location may be cleaned (removed) by the system if they are not accessed in
  3 days.

_CS_DARWIN_USER_CACHE_DIR
  Provides the path to the user's cache directory. The directory will be created if it does not already
  exist. This directory is created with access permissions of 0700 and restricted by the umask(2) of
  the calling process and is a good location for user cache data as it will not be automatically
  cleaned by the system.

  Files in this location will be removed during safe boot.
```

`DARWIN_USER_TEMP_DIR` looks like `/var/folders/pv/rrs7y6q14q11zz5hg2sqxj0m0000gn/T/` and is basically a private-`/tmp`. Same default cleanup policy 3+ days, but it only deletes regular files so dirs are left behind. Also on reboot, everything is removed. Getting this value is probably easier because `$TMPDIR` is defined as such.

`DARWIN_USER_CACHE_DIR` looks like `/var/folders/pv/rrs7y6q14q11zz5hg2sqxj0m0000gn/C/` (notice `C` for cache instead of `T` for temp) and is private to each user. This is a decent fit if you want all of:

1. private to user
2. cleanup everything on boot
3. no periodic cleanup of any kind

but getting this value would require adding `confstr` to `std.c` or shelling out to `getconf`. Obviously this would need to be macos-conditional.

**Comment by motiejus** [comment]
> I understand the wrapper goal is to set _both_ local/global cache to the same value. Perhaps simply set them both to what the default global cache likes to be:
> 
> ```
> export ZIG_GLOBAL_CACHE_DIR=$HOME/.cache/zig
> export ZIG_LOCAL_CACHE_DIR=$ZIG_GLOBAL_CACHE_DIR
> ```

This path will need to appear in `--sandbox_mount_pair` bazel arguments: https://github.com/uber/hermetic_cc_toolchain/?tab=readme-ov-file#usage

This option only accepts full paths, without variable expansion. Since this option violates hermeticity, Bazel treats it quite strictly (and I don't presume any PRs would be accepted to, say, allow environment variables there).

> `/var/tmp` is a marginally better place to store a cache, although it won't be cleared every reboot on mac like `/tmp` was. At least on my linux machine, the only actual difference is that `/var/tmp` is bigger, and so it is where the package manager compiles code from.

I don't need the cache to be cleared on every reboot. `/var/tmp` seems like an excellent choice, provided:
1. it's writable.
2. it doesn't get cleared automatically.

I will confirm both today and, viola, we may have a resolution to this.

> The correct place to put a non-user cache is `/var/cache` of course, but there won't be any writable directories in there unless created during a package installation.

Ideally it should be in `~/.cache/zig`, but it's been rejected due to the reasons above.

**Comment by motiejus** [comment]
Thanks everyone and sorry for such an alarm. I now have high confidence that moving cache to `/var/tmp` will fix this.

This was truly a long-time and multi-person effort to find!

**Comment by andrewrk** [comment]
No need to apologize. 

Maybe there is still room for improving the error message here- it could have saved time if it clearly indicated the problem occurred due to files missing from the global cache directory. I want to be careful not to offer misleading hints but, any clarifications that could have more quickly led to the diagnosis would make sense to make in the error reporting.

**Comment by jacobly0** [comment]
> t could have saved time if it clearly indicated the problem occurred due to files missing from the global cache directory.

Note that after the recent linker changes, the status quo with lld and the self-hosted linker on master is:
```
error: ld.lld: cannot open ~/.cache/zig/o/7a704696d970e90cbff9db1a66fc9583/libc.a: No such file or directory

error: unexpected error: parsing input file failed with error FileNotFound
    note: while parsing ~/.cache/zig//o/7a704696d970e90cbff9db1a66fc9583/libc.a
```

**Comment by andrewrk** [comment]
My only suggestion would be
```diff
-error: unexpected error: parsing input file failed with error FileNotFound
+error: parsing input file failed with error FileNotFound
    note: while parsing ~/.cache/zig/o/7a704696d970e90cbff9db1a66fc9583/libc.a
```
but that has nothing to do with this issue. So I think there is nothing else to do.

**Comment by michael-weigelt** [comment]
Hi, I got
```
You stumbled into a problem with Zig SDK that hermetic_cc_toolchain was not
able to fix. This is most likely a long-standing problem mostly (only?)
observed in OSX. Please please add a comment to
https://github.com/ziglang/zig/issues/18763 with:
- Output of `bazel run @zig_sdk//:zig version`
- Full output of this Bazel run, including the Bazel command.
- Full OS version and hardware revision (e.g. aarch64 or x86_64?).
```
So here are the pieces in order:
```
bazel run @zig_sdk//:zig version
Another command (pid=4106315) is running. Waiting for it to complete on the server (server_pid=3849274)...
INFO: Invocation ID: 262fdbb0-5aba-4a8b-be1f-e82592209829
INFO: Analyzed target @@hermetic_cc_toolchain~~toolchains~zig_sdk//:zig (0 packages loaded, 0 targets configured).
WARNING: /home/mwe/.cache/bazel/_bazel_mwe/5b9198f63b2a5b333a0123474d86a410/external/hermetic_cc_toolchain~/toolchain/defs.bzl:251:25: @@hermetic_cc_toolchain~~toolchains~zig_sdk//:zig is a source file, nothing will be built for it. If you want to build a target that consumes this file, try --compile_one_dependency
INFO: Found 1 target...
INFO: Elapsed time: 2.717s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: /home/mwe/.cache/bazel/_bazel_mwe/5b9198f63b2a5b333a0123474d86a410/external/hermetic_cc_toolchain~~toolchains~zig_sdk/zig version
0.12.0
```

```
bazel build //rs/execution_environment
INFO: Invocation ID: a7f69b6a-31cc-4aed-ae63-1f1e6918a63e
DEBUG: /home/mwe/.cache/bazel/_bazel_mwe/5b9198f63b2a5b333a0123474d86a410/external/hermetic_cc_toolchain~/toolchain/defs.bzl:196:18: Launcher compilation failed. Retrying build
DEBUG: /home/mwe/.cache/bazel/_bazel_mwe/5b9198f63b2a5b333a0123474d86a410/external/hermetic_cc_toolchain~/toolchain/defs.bzl:196:18: Launcher compilation failed. Retrying build
INFO: Repository hermetic_cc_toolchain~~toolchains~zig_sdk instantiated at:
  <builtin>: in <toplevel>
Repository rule zig_repository defined at:
  /home/mwe/.cache/bazel/_bazel_mwe/5b9198f63b2a5b333a0123474d86a410/external/hermetic_cc_toolchain~/toolchain/defs.bzl:232:33: in <toplevel>
ERROR: /home/mwe/.cache/bazel/_bazel_mwe/5b9198f63b2a5b333a0123474d86a410/external/hermetic_cc_toolchain~/toolchain/defs.bzl:219:13: An error occurred during the fetch of repository 'hermetic_cc_toolchain~~toolchains~zig_sdk':
   Traceback (most recent call last):
        File "/home/mwe/.cache/bazel/_bazel_mwe/5b9198f63b2a5b333a0123474d86a410/external/hermetic_cc_toolchain~/toolchain/defs.bzl", line 219, column 13, in _zig_repository_impl
                fail(zig_wrapper_err_msg)
Error in fail: 
Compilation of zig-wrapper.zig failed:
command=ZIG_LOCAL_CACHE_DIR=/tmp/zig-cache ZIG_GLOBAL_CACHE_DIR=/tmp/zig-cache ../zig build-exe -target x86_64-linux-musl -mcpu=baseline -fstrip -OReleaseSafe zig-wrapper.zig
return_code=1
stderr=error: unable to build zig's multitarget libc: AccessDenied
error: unable to build compiler_rt: AccessDenied
/home/mwe/.cache/bazel/_bazel_mwe/5b9198f63b2a5b333a0123474d86a410/external/hermetic_cc_toolchain~~toolchains~zig_sdk/lib/std/std.zig:1:1: error: unable to load '/home/mwe/.cache/bazel/_bazel_mwe/5b9198f63b2a5b333a0123474d86a410/external/hermetic_cc_toolchain~~toolchains~zig_sdk/lib/std/std.zig': AccessDenied
```

```
uname -a 
Linux [...] 5.15.0-124-generic #134~20.04.1-Ubuntu SMP Tue Oct 1 15:27:33 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

Clearing the cache worked for me, but it did not for another user on the same machine.

**Comment by max-dfinity** [comment]
I just got 
```
You stumbled into a problem with Zig SDK that hermetic_cc_toolchain was not
able to fix. This is most likely a long-standing problem mostly (only?)
observed in OSX. Please please add a comment to
https://github.com/ziglang/zig/issues/18763 with:
- Output of `bazel run @zig_sdk//:zig version`
- Full output of this Bazel run, including the Bazel command.
- Full OS version and hardware revision (e.g. aarch64 or x86_64?).
```

Running `bazel run @zig_sdk//:zig version` got me the same error again

```
INFO: Invocation ID: a4a72208-106b-405a-adc1-a9543a1cec5b
Computing main repo mapping: 
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
DEBUG: /private/var/tmp/_bazel_maximiliansumme/e7514bc0e1225dccf286baa6a848f44f/external/hermetic_cc_toolchain~/toolchain/defs.bzl:200:18: Launcher compilation failed. Retrying build
DEBUG: /private/var/tmp/_bazel_maximiliansumme/e7514bc0e1225dccf286baa6a848f44f/external/hermetic_cc_toolchain~/toolchain/defs.bzl:200:18: Launcher compilation failed. Retrying build
INFO: Repository hermetic_cc_toolchain~~toolchains~zig_sdk instantiated at:
  <builtin>: in <toplevel>
Repository rule zig_repository defined at:
  /private/var/tmp/_bazel_maximiliansumme/e7514bc0e1225dccf286baa6a848f44f/external/hermetic_cc_toolchain~/toolchain/defs.bzl:236:33: in <toplevel>
INFO: repository @@hermetic_cc_toolchain~~toolchains~zig_sdk' used the following cache hits instead of downloading the corresponding file.
 * Hash '294e224c14fd0822cfb15a35cf39aa14bd9967867999bf8bdfe3db7ddec2a27f' for https://mirror.bazel.build/ziglang.org/download/0.12.0/zig-macos-aarch64-0.12.0.tar.xz
If the definition of 'repository @@hermetic_cc_toolchain~~toolchains~zig_sdk' was updated, verify that the hashes were also updated.
ERROR: /private/var/tmp/_bazel_maximiliansumme/e7514bc0e1225dccf286baa6a848f44f/external/hermetic_cc_toolchain~/toolchain/defs.bzl:223:13: An error occurred during the fetch of repository 'hermetic_cc_toolchain~~toolchains~zig_sdk':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_maximiliansumme/e7514bc0e1225dccf286baa6a848f44f/external/hermetic_cc_toolchain~/toolchain/defs.bzl", line 223, column 13, in _zig_repository_impl
		fail(zig_wrapper_err_msg)
Error in fail: 
Compilation of zig-wrapper.zig failed:
command=ZIG_LOCAL_CACHE_DIR=/tmp/zig-cache/config-catchall ZIG_GLOBAL_CACHE_DIR=/tmp/zig-cache/config-catchall ../zig build-exe -target aarch64-macos-none -mcpu=apple_a14 -fstrip -OReleaseSafe zig-wrapper.zig
return_code=1
stderr=error: AccessDenied

stdout=

You stumbled into a problem with Zig SDK that hermetic_cc_toolchain was not
able to fix. This is most likely a long-standing problem mostly (only?)
observed in OSX. Please please add a comment to
https://github.com/ziglang/zig/issues/18763 with:
- Output of `bazel run @zig_sdk//:zig version`
- Full output of this Bazel run, including the Bazel command.
- Full OS version and hardware revision (e.g. aarch64 or x86_64?).

Zig and hermetic_cc_toolchain maintainers aren't able to reproduce it, but you
are. Thus we need a bit of your collaboration to get to the bottom of it.

After commenting on the issue, `rm -fr /tmp/zig-cache/config-catchall` and re-run your command.
ERROR: 
Compilation of zig-wrapper.zig failed:
command=ZIG_LOCAL_CACHE_DIR=/tmp/zig-cache/config-catchall ZIG_GLOBAL_CACHE_DIR=/tmp/zig-cache/config-catchall ../zig build-exe -target aarch64-macos-none -mcpu=apple_a14 -fstrip -OReleaseSafe zig-wrapper.zig
return_code=1
stderr=error: AccessDenied

stdout=

You stumbled into a problem with Zig SDK that hermetic_cc_toolchain was not
able to fix. This is most likely a long-standing problem mostly (only?)
observed in OSX. Please please add a comment to
https://github.com/ziglang/zig/issues/18763 with:
- Output of `bazel run @zig_sdk//:zig version`
- Full output of this Bazel run, including the Bazel command.
- Full OS version and hardware revision (e.g. aarch64 or x86_64?).

Zig and hermetic_cc_toolchain maintainers aren't able to reproduce it, but you
are. Thus we need a bit of your collaboration to get to the bottom of it.

After commenting on the issue, `rm -fr /tmp/zig-cache/config-catchall` and re-run your command.
INFO: Elapsed time: 9.533s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target
```
So that's not encouraging...

Original command:
```
% bazel run :release-runscript          
INFO: Invocation ID: f3bf05cd-8d14-4134-9f6a-bc96c86b2baa
DEBUG: /private/var/tmp/_bazel_maximiliansumme/e7514bc0e1225dccf286baa6a848f44f/external/hermetic_cc_toolchain~/toolchain/defs.bzl:200:18: Launcher compilation failed. Retrying build
DEBUG: /private/var/tmp/_bazel_maximiliansumme/e7514bc0e1225dccf286baa6a848f44f/external/hermetic_cc_toolchain~/toolchain/defs.bzl:200:18: Launcher compilation failed. Retrying build
INFO: Repository hermetic_cc_toolchain~~toolchains~zig_sdk instantiated at:
  <builtin>: in <toplevel>
Repository rule zig_repository defined at:
  /private/var/tmp/_bazel_maximiliansumme/e7514bc0e1225dccf286baa6a848f44f/external/hermetic_cc_toolchain~/toolchain/defs.bzl:236:33: in <toplevel>
INFO: repository @@hermetic_cc_toolchain~~toolchains~zig_sdk' used the following cache hits instead of downloading the corresponding file.
 * Hash '294e224c14fd0822cfb15a35cf39aa14bd9967867999bf8bdfe3db7ddec2a27f' for https://mirror.bazel.build/ziglang.org/download/0.12.0/zig-macos-aarch64-0.12.0.tar.xz
If the definition of 'repository @@hermetic_cc_toolchain~~toolchains~zig_sdk' was updated, verify that the hashes were also updated.
ERROR: /private/var/tmp/_bazel_maximiliansumme/e7514bc0e1225dccf286baa6a848f44f/external/hermetic_cc_toolchain~/toolchain/defs.bzl:223:13: An error occurred during the fetch of repository 'hermetic_cc_toolchain~~toolchains~zig_sdk':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_maximiliansumme/e7514bc0e1225dccf286baa6a848f44f/external/hermetic_cc_toolchain~/toolchain/defs.bzl", line 223, column 13, in _zig_repository_impl
                fail(zig_wrapper_err_msg)
Error in fail: 
Compilation of zig-wrapper.zig failed:
command=ZIG_LOCAL_CACHE_DIR=/tmp/zig-cache/config-catchall ZIG_GLOBAL_CACHE_DIR=/tmp/zig-cache/config-catchall ../zig build-exe -target aarch64-macos-none -mcpu=apple_a14 -fstrip -OReleaseSafe zig-wrapper.zig
return_code=1
stderr=error: AccessDenied

stdout=

You stumbled into a problem with Zig SDK that hermetic_cc_toolchain was not
able to fix. This is most likely a long-standing problem mostly (only?)
observed in OSX. Please please add a comment to
https://github.com/ziglang/zig/issues/18763 with:
- Output of `bazel run @zig_sdk//:zig version`
- Full output of this Bazel run, including the Bazel command.
- Full OS version and hardware revision (e.g. aarch64 or x86_64?).

Zig and hermetic_cc_toolchain maintainers aren't able to reproduce it, but you
are. Thus we need a bit of your collaboration to get to the bottom of it.

After commenting on the issue, `rm -fr /tmp/zig-cache/config-catchall` and re-run your command.
ERROR: Analysis of target '//rs/nervous_system/tools/release-runscript:release-runscript' failed; build aborted: 
Compilation of zig-wrapper.zig failed:
command=ZIG_LOCAL_CACHE_DIR=/tmp/zig-cache/config-catchall ZIG_GLOBAL_CACHE_DIR=/tmp/zig-cache/config-catchall ../zig build-exe -target aarch64-macos-none -mcpu=apple_a14 -fstrip -OReleaseSafe zig-wrapper.zig
return_code=1
stderr=error: AccessDenied

stdout=

You stumbled into a problem with Zig SDK that hermetic_cc_toolchain was not
able to fix. This is most likely a long-standing problem mostly (only?)
observed in OSX. Please please add a comment to
https://github.com/ziglang/zig/issues/18763 with:
- Output of `bazel run @zig_sdk//:zig version`
- Full output of this Bazel run, including the Bazel command.
- Full OS version and hardware revision (e.g. aarch64 or x86_64?).

Zig and hermetic_cc_toolchain maintainers aren't able to reproduce it, but you
are. Thus we need a bit of your collaboration to get to the bottom of it.

After commenting on the issue, `rm -fr /tmp/zig-cache/config-catchall` and re-run your command.
INFO: Elapsed time: 9.624s, Critical Path: 0.04s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target

```

```
% uname -a
Darwin Maximilian-Summe-VGCWMH9F7N 24.5.0 Darwin Kernel Version 24.5.0: Tue Apr 22 19:54:49 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T6000 arm64
```

```
% sw_vers
ProductName:            macOS
ProductVersion:         15.5
BuildVersion:           24F74
```

**Comment by motiejus** [comment]
Everyone still affected, see https://github.com/ziglang/zig/issues/18763#issuecomment-1944548520
