### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by l3r8yJ** [ziglang/zig#18766]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Output

zig code with constant:
```zig
pub fn main() !void {
    const x: u8 = 255;
    x += 1;
}
```
will produce a message:
```bash
src/main.zig:3:7: error: overflow of integer type 'u8' with value '256'
    x += 1;
    ~~^~~~
referenced by:
    callMain: /opt/homebrew/Cellar/zig/0.11.0/lib/zig/std/start.zig:574:32
    initEventLoopAndCallMain: /opt/homebrew/Cellar/zig/0.11.0/lib/zig/std/start.zig:508:34
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

### Expected Output

But i would expect to see this error message:
```bash
src/main.zig:3:7: error: cannot assign to constant
    x += 1;
    ~~^~~~
```
I think the mutability check should come first

**Comment by l3r8yJ** [comment]
If it is possible, I can try to contribute and fix this issue myself

**Comment by l3r8yJ** [comment]
sure, I think i need to wait until some contributor approves this issue before I fix it

**Comment by Rexicon226** [comment]
This is simply a byproduct of the order of analyzes. The right-hand side of assignments is analyzed first. I don't think this is an issue, and the error message *is* correct.

**Comment by l3r8yJ** [comment]
In my opinion, it looks like bad design when we analyze something that cannot be done by definition, in this case we are trying to mutate a constant

**Comment by Rexicon226** [comment]
As well as increase a u8 past its max value? They are both wrong, and the analysis order is the RHS first for good reason.
