### ISSUE TITLE
possible `zig fmt` malfunction

### ISSUE THREAD

**Issue by p7r0x7** [ziglang/zig#18790]
### Zig Version

0.12.0-dev.2542+5a3ae38f3

### Steps to Reproduce and Observed Behavior

I believe lines after `// zig fmt: off` are not linted by zig fmt even if `// zig fmt: on` is additionally specified to resume formatting.

### Expected Behavior

I expected formatting to resume for proceeding characters.

**Comment by nektro** [comment]
you didn't post any code but this is likely a duplicate of https://github.com/ziglang/zig/issues/10418

**Comment by p7r0x7** [comment]
yeah lol
<img width="470" alt="Screenshot 2024-02-02 at 7 32 25 PM" src="https://github.com/ziglang/zig/assets/54943589/1c74d699-f01f-4178-a80c-49c10a63ad7e">
