### ISSUE TITLE
How to use the registry

### ISSUE THREAD

**Issue by qcjxberin** [ziglang/zig#18809]
How to use the registry

**Comment by squeek502** [comment]
This type of question should be directed to [one of the community spaces](https://github.com/ziglang/zig/wiki/Community), not the issue tracker.

---

Assuming you mean the Windows registry, there are some minimal bindings in the standard library:

- https://github.com/ziglang/zig/blob/master/lib/std/os/windows/advapi32.zig

Example usage can be seen here:

- https://github.com/ziglang/zig/blob/master/src/windows_sdk.zig

If you need more than the standard library, it is easy to write bindings for whatever you need:

- https://github.com/squeek502/watchedoverlay/blob/master/src/registry.zig

or you can use https://github.com/marlersoft/zigwin32/ to get complete bindings.
