### ISSUE TITLE
A Small Error In std.os.uefi

### ISSUE THREAD

**Issue by zzjrabbit** [ziglang/zig#18832]
### Zig Version

0.12.0-dev.2586+3c7970dc4

### Steps to Reproduce and Observed Behavior

I am writing a UEFI bootloader, and when I tried to compile using the Nightly version of Zig, I found that it output the following error:
```
/Home/xxx/zig bin/lib/std/os/uefi/tables/runtime_ Services. zig: 11:39: error: 'EffPhysicalAddress' is not marketed as' pub'

Const EfiPhysicalAddress=uefi. tables. EfiPhysicalAddress;

~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~

/Home/xxx/zig bin/lib/std/os/uefi/tables. zig: 95:1: note: declared here

Const EfiPhysicalAddress=u64;

^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
The problem was solved by adding the keyword pub before `const EfiPhysicalAddress=u64; `.

I hope this error can be fixed!

### Expected Behavior

Compile normally

**Comment by nektro** [comment]
fixed by https://github.com/ziglang/zig/pull/18783
