### ISSUE TITLE
new system integration options broke shell completions

### ISSUE THREAD

**Issue by xdBronch** [ziglang/zig#18866]
### Zig Version

0.12.0-dev.2640+b3aed4e2c

### Steps to Reproduce and Observed Behavior

in a zig project with no system integrations options ask for shell completions with the prompt `zig build -`
rather than completing options like before it will print out 
```
_arguments:comparguments:327: invalid argument: (none)[-]:
_arguments:comparguments:327: invalid argument: (none)[-]:
_arguments:comparguments:327: invalid argument: (none)[-]:
```
this is due to the new section from #18778 
```
Available System Integrations:                Enabled:
(none)                                        -
```
if there are any system integration options the completions will work again

this is on zsh, i dont have shell completions setup for anything else so im not sure if it happens for those, sorry.

im not sure if this can/should be worked around in the shell completions but if so i can move this issue to https://github.com/ziglang/shell-completions

### Expected Behavior

give completions for build options

**Comment by ifreund** [comment]
Yeah, this issue belongs on the shell completions repository.

**Comment by xdBronch** [comment]
moved to the other repo
