### ISSUE TITLE
ld.ldd: undefined symbol errors when trying to include stb_truetype.h

### ISSUE THREAD

**Issue by illis** [ziglang/zig#18862]
### Zig Version

0.12.0-dev.2638+38c2a2573

### Steps to Reproduce and Observed Behavior

When trying to use stb_truetype.h I keep getting a bunch of ld.ldd undefined symbol errors when trying to build.

output of `zig build`:
```
error: ld.lld: undefined symbol: stbtt_FlattenCurves
    note: referenced by cimport.zig:2695 (/home/illis/ztmp/zig-cache/o/e0b1eae6cb7617155972d0607e1a756a/cimport.zig:2695)
    note:               /home/illis/ztmp/zig-cache/o/cfdd47cbfb6c3d5ba153322fdb210cf3/zig-stbtt_test.o:(cimport.stbtt_Rasterize)
error: ld.lld: undefined symbol: stbtt__run_charstring
    note: referenced by cimport.zig:3893 (/home/illis/ztmp/zig-cache/o/e0b1eae6cb7617155972d0607e1a756a/cimport.zig:3893)
    note:               /home/illis/ztmp/zig-cache/o/cfdd47cbfb6c3d5ba153322fdb210cf3/zig-stbtt_test.o:(cimport.stbtt__GetGlyphInfoT2)
    note: referenced by cimport.zig:4667 (/home/illis/ztmp/zig-cache/o/e0b1eae6cb7617155972d0607e1a756a/cimport.zig:4667)
    note:               /home/illis/ztmp/zig-cache/o/cfdd47cbfb6c3d5ba153322fdb210cf3/zig-stbtt_test.o:(cimport.stbtt__GetGlyphShapeT2)
    note: referenced by cimport.zig:4673 (/home/illis/ztmp/zig-cache/o/e0b1eae6cb7617155972d0607e1a756a/cimport.zig:4673)
    note:               /home/illis/ztmp/zig-cache/o/cfdd47cbfb6c3d5ba153322fdb210cf3/zig-stbtt_test.o:(cimport.stbtt__GetGlyphShapeT2)
... 
```

To reproduce:
```
git clone https://github.com/illis/zig-stbtt_test
cd zig-stbtt_test
zig build
```

Not sure its an issue with the way I imported the header file? or maybe some bug in cImport?

### Expected Behavior

Compile and produce an executable.

**Comment by f-cozzocrea** [comment]
I'm not familiar with the header you're importing, but your build.zig doesn't appear to link the stb_tt library.

**Comment by illis** [comment]
@f-cozzocrea Thanks for looking. 
Library is from here: https://github.com/nothings/stb/
Everything is supposed to be included in the header file including stb_FlattenCurves & stbtt__run_charstring

I did a bit more digging and found this in the zig-cache/../cimport.zig file:
```
zig-stbtt_test/include/stb_truetype.h:3618:22: warning: unable to translate function, demoted to extern
pub extern fn stbtt_FlattenCurves(arg_vertices: [*c]stbtt_vertex, arg_num_verts: c_int, arg_objspace_flatness: f32, arg_contour_lengths: [*c][*c]c_int, arg_num_contours: [*c]c_int, arg_userdata: ?*anyopaque) callconv(.C) [*c]stbtt__point;

```
and similar for stbtt__run_charstring:
```
zig-stbtt_test/include/stb_truetype.h:2010:12: warning: unable to translate function, demoted to extern
pub extern fn stbtt__run_charstring(arg_info: [*c]const stbtt_fontinfo, arg_glyph_index: c_int, arg_c: [*c]stbtt__csctx) callconv(.C) c_int;

```

So I'm guessing these may be known c_translate issues?

**Comment by f-cozzocrea** [comment]
Yes, there's a couple C features that translate-c doesn't support yet. The function is demoted to extern in those cases.

**Comment by travisstaloch** [comment]
> Not sure its an issue with the way I imported the header file? or maybe some bug in cImport?
> ###

No this isn't a bug.  translate-c isn't really meant to translate c implementations.  Its meant for translating headers.  And while this is called a 'single header library', when you define the IMPL #define, it becomes an implementation AND a header in one file.  There are some instructions here for how to use such single header libs from zig: https://ziggit.dev/t/using-a-single-header-c-library-from-zig/1913/2

Make sure to ask in one of the communities before posting here next time https://github.com/ziglang/zig/wiki/Community.  There are lots of helpful people who can tell if something is a bug and help point you in the right direction.  The issue tracker is not the place for that.

**Comment by illis** [comment]
Found a workaround: https://github.com/ziglang/zig/issues/15408#issuecomment-1705560635

https://github.com/illis/zig-stbtt_test/tree/workaround

**Comment by illis** [comment]
Ok thanks @travisstaloch . I'll close this then.

**Comment by travisstaloch** [comment]
> Found a workaround: [#15408 (comment)](https://github.com/ziglang/zig/issues/15408#issuecomment-1705560635)

:+1: To be clear, this isn't a workaround.  That's the recommended way to use single header libs.
