### ISSUE TITLE
Volatile read in while loop gets optimized out

### ISSUE THREAD

**Issue by ii8** [ziglang/zig#18879]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

This while loop is eliminated:
```zig
const wait4me: *volatile u32 = @ptrFromInt(0x40004C00 + 0x1C);
while ((wait4me.* & (1 << 7)) == 0) { }
```

This one remains:
```zig
const wait4me: *volatile u32 = @ptrFromInt(0x40004C00 + 0x1C);
while ((wait4me.* & (1 << 7)) == 0) { asm volatile("nop"); }
```

Target is cortex-m7 thumb freestanding, -Doptimize=ReleaseSmall

### Expected Behavior

Neither should be optimized out. Even though the result of the while loop isn't used, the time delay caused by reading from the location until a condition holds is a side-effect that volatile should make sure is produced.

**Comment by Vexu** [comment]
Seems to be fixed in master https://zig.godbolt.org/z/7WfjrKjGv
