### ISSUE TITLE
bsd CI does not seem to be running a complete test

### ISSUE THREAD

**Issue by kristate** [ziglang/zig#1887]
The bsd CI for #1886 completed faster than I expected and upon viewing the log, I discovered that it seems to be only running the behavior tests. Can someone confirm? Thanks.
/cc @andrewrk 

https://builds.sr.ht/~andrewrk/job/22609#task-test

**Comment by andrewrk** [comment]
That's correct. See #1759. FreeBSD does not have all tests passing yet - we're adding more test coverage to the CI as we get more passing. The behavior tests are actually relatively new - @mgxm just got them passing.

**Comment by mgxm** [comment]
indeed @kristate , for now, we're doing this [manually](https://github.com/ziglang/zig/blob/master/.builds/freebsd.yml#L15).
There is still some work to be done on that side, finish the std library and the cross compilation to BSD from non-BSD is one of them
