### ISSUE TITLE
std.fs.Dir.readFile "succeeds" when the buffer is too small

### ISSUE THREAD

**Issue by iacore** [ziglang/zig#18880]
### Zig Version

0aff1f9ce51fd1b0df5cb5a6a06c5d6c744749fe (latest)

### Steps to Reproduce

https://github.com/ziglang/zig/blob/0aff1f9ce51fd1b0df5cb5a6a06c5d6c744749fe/lib/std/fs/Dir.zig#L1758-L1769

I have been shot by this footgun.

The first line of the comment of this function says

```
/// Read all of file contents using a preallocated buffer.
```

This has mislead me to believe that this is actually the case.

### Expected Behavior

I had assumed that the call to this function should fail if the provided buffer is not big enough. i.e., it would read the whole file, or fail.

### Observed Behavior

As it turned out, the call "succeeds" silently, returning a buffer only holding the beginning of the file.

**Comment by squeek502** [comment]
Am I wrong to think this is a documentation problem, not a bug? The first line of the doc comment is wrong/misleading, but the rest seems pretty clear that succeeding is the intended behavior.

Perhaps instead the first line should be something like:

```
/// Read a maximum of `buffer.len` bytes from the file at `file_path`.
```

**Comment by iacore** [comment]
I would think the `readFile` function either reads the whole file, or it doesn't, unless its name would suggest otherwise.

**Comment by loftafi** [comment]
The solution to getting "tripped up" by this, is to check the file size before you start reading it. Just "try to read it" to see how long it is feels a little error prone.
