### ISSUE TITLE
HashMap with string keys strange behavior on Windows

### ISSUE THREAD

**Issue by travisstaloch** [ziglang/zig#1888]
Using the most current version of zig, literally just pulled and rebuilt: 
```
> zig version
0.3.0+c968d87
````
Still pretty new to zig doing some of last years advent of code problems.  On day 16, I encountered this issue.  The strings in the challenge are just permutations of the first: " abcdefghijklmnop".  The second test below shows that the HashMap isn't correctly storing the string keys on the 5th insertion.  .contains() and get() are showing that it contains a string which hasn't been inserted and count() == 4 at that point when it should be 5.  

The two tests create a `std.HashMap([]const u8, usize, mem.hash_slice_u8, mem.eql_slice_u8)` and init with heap.DirectAllocator.  The first works as expected using 5 constant string literals.  The second fails.  It uses a same values but they are assigned to a var before inserting.  I believe this is the only difference.  

I don't believe the problem is the hash_slice_u8 function as I worked around this by calling it in my own code and the hashes look fine.  I looked for similar issues and the closest I could find was [#879](https://github.com/ziglang/zig/issues/879 ).  

Any ideas?

```zig 
test "HashMap with string keys works" {
    var da = std.heap.DirectAllocator.init();
    defer da.deinit();
    var map = std.HashMap([]const u8, usize, mem.hash_slice_u8, mem.eql_slice_u8).init(&da.allocator);
    defer map.deinit();
    _ = map.put("abcdefghijklmnop", 0);
    _ = map.put("fgmobeaijhdpkcln", 1);
    _ = map.put("hjbagmnplkcfiedo", 2);
    _ = map.put("chadeplfgojnmikb", 3);
    _ = map.put("lgmknhfibepodacj", 4);
    warn("\ncount {}", map.count());
    assert(map.count() == 5);
}

test "HashMap with string keys doesn't work" {
    var da = std.heap.DirectAllocator.init();
    defer da.deinit();
    var map = std.HashMap([]const u8, usize, mem.hash_slice_u8, mem.eql_slice_u8).init(&da.allocator);
    defer map.deinit();
    var s = "abcdefghijklmnop";
    _ = map.put(s, 0);
    s = "fgmobeaijhdpkcln";
    _ = map.put(s, 1);
    s = "hjbagmnplkcfiedo";
    _ = map.put(s, 2);
    s = "chadeplfgojnmikb";
    _ = map.put(s, 3);
    s = "lgmknhfibepodacj";
    assert(!map.contains(s));
    _ = map.put(s, 4);
    warn("\ncount {}", map.count());
    assert(map.count() == 5);
}
```

**Comment by Hejsil** [comment]
Here is the problem. `s` in your second test is of type `[16]u8`. That means, that it stores your string on the stack. `[]const u8` is a slice (aka and pointer an a length). When you assign something new to `s`, that string is copied into `s`s memory, so you override the string, and the pointers in the hashmap now point to the wrong thing.

The reason why the first example works, is that string literals are stored globally, so your pointer will always point to the right thing.

**Comment by travisstaloch** [comment]
I see what you're saying, the map is storing pointers which get invalidated and the memory left dangling as `s` is reassigned.  

It must be the case that the stack gets recycled after the 4th string is put into the map.  That would explain why the assertions aren't triggered until the last one.  

I added more asserts to each put and a comment at the failure point.  

```zig
test "HashMap with string keys doesn't work" {
    var da = std.heap.DirectAllocator.init();
    defer da.deinit();
    var map = std.HashMap([]const u8, usize, mem.hash_slice_u8, mem.eql_slice_u8).init(&da.allocator);
    defer map.deinit();
    var s = "abcdefghijklmnop";
    assert(map.count() == 0);
    _ = map.put(s, 1);
    s = "fgmobeaijhdpkcln";
    assert(map.count() == 1);
    assert(!map.contains(s));
    _ = map.put(s, 2);
    assert(map.count() == 2);
    s = "hjbagmnplkcfiedo";
    assert(!map.contains(s));
    _ = map.put(s, 3);
    assert(map.count() == 3);
    s = "chadeplfgojnmikb";
    assert(!map.contains(s));
    _ = map.put(s, 4);
    assert(map.count() == 4);
    s = "lgmknhfibepodacj";
    assert(!map.contains(s));        // <<-- This is the first assertion failure.
    _ = map.put(s, 5);
    assert(map.count() == 5);
}
```

**Comment by kristate** [comment]
No, the stack is not being recycled. `[]const u8` is just a fancy way to cast the memory `s` points to as a slice. `s` just happens to be on the stack, but the same would be true if the memory was on heap and you were to change it: you continue to reassign the memory that is pointed to by `s`. In `var s = "abc"`, `s` is not a pointer to "abc", rather as @Hejsil points out, you are copying "abc" to a byte-array of length 3 labeled `s`. If you meant to assign static memory "abc" to a variable labeled `s`, try `var s: []const u8 = "abc";`

In future versions of Zig, to make common mistakes impossible, we are working on disallowing the assignment of stack memory pointers and slices to structs.

try this:

```zig
test "HashMap with string keys doesn't work" {
    var da = std.heap.DirectAllocator.init();
    defer da.deinit();
    var map = std.HashMap([]const u8, usize, mem.hash_slice_u8, mem.eql_slice_u8).init(&da.allocator);
    defer map.deinit();
    // Notice that var s is now of type []const u8
    // It was inferred to be of type [16]u8 before
    var s: []const u8 = "abcdefghijklmnop";
    assert(map.count() == 0);
    _ = map.put(s, 1);
    s = "fgmobeaijhdpkcln";
    assert(map.count() == 1);
    assert(!map.contains(s));
    _ = map.put(s, 2);
    assert(map.count() == 2);
    s = "hjbagmnplkcfiedo";
    assert(!map.contains(s));
    _ = map.put(s, 3);
    assert(map.count() == 3);
    s = "chadeplfgojnmikb";
    assert(!map.contains(s));
    _ = map.put(s, 4);
    assert(map.count() == 4);
    s = "lgmknhfibepodacj";
    assert(!map.contains(s));
    _ = map.put(s, 5);
    assert(map.count() == 5);
}
```

**Comment by travisstaloch** [comment]
Thank you guys for helping to clear up for me what is happening.  I think this makes a lot more sense now.  Is it correct then that the HashMap is storing slice references, not copies of the slices to which s pointed?  

In the problem I was using `std.mem.copy(u8, s[0..], s2);` between two `[]u8` and then storing in a HashMap to keep track of which have been seen previously.  This wouldn't work if `s` is a `[]const u8` =>  error: expected type '[]u8', found '[]const u8'.  Neither does index assignment `s[0] = 'b'`.  => error: cannot assign to constant

So what to do in the case where you need to mutate the slices and then store in a HashMap?  

I really like the idea of making this type of thing impossible like you said.  Really appreciate all the work going on here.  I really enjoy zig as a systems language.

**Comment by travisstaloch** [comment]
I see that buf_map is using mem.dupe to make copies of the key and value.  Thats good to know.  Thanks again for the help.

**Comment by kristate** [comment]
@travisstaloch great to see you are on your way to writing more code in Zig -- please close the issue if you feel we have solved your problem.
