### ISSUE TITLE
zig fmt: reorder struct initialization to be consistent with the struct definition

### ISSUE THREAD

**Issue by anyputer** [ziglang/zig#18896]
I always reorder struct field initialization order to be consistent with the order of the fields in the type. It would be nice if zig fmt could automatically do this so I don't have to.
For instance:
```zig
const Foo = struct { y: u8, a: u8, x: u8 };
const foo = Foo { .a = 42, .x = 69, .y = 32 };
```
would get formatted as:
```zig
const Foo = struct { y: u8, a: u8, x: u8 };
const foo = Foo { .y = 32, .a = 42, .x = 69 };
```

**Comment by nektro** [comment]
if zig fmt were to make this change it could semantically change the output of the program and for that reason it should not do this. this is a job imo for ancillary editor tooling.

**Comment by onthebusiness** [comment]
good idea as an option feature

**Comment by mlugg** [comment]
This could be nice for third-party tooling as mentioned above (but only ever at explicit request since it changes program semantics), but I would just like to note that it's by no means always possible:
```zig
const A = struct { a: u32, b: u32 };
const B = struct { b: u32, a: u32 };
fn f() void {
    const S = if (some_comptime_thing) A else B;
    const x: S = .{ .a = 123, .b = 456 };
    _ = x;
}
```
