### ISSUE TITLE
comptime_float literal allowed in int array init

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#18904]
### Zig Version

0.12.0-dev.1828+225fe6ddb

### Steps to Reproduce and Observed Behavior

```zig
test {
    const ints = [_]u32{
        0.0, 0.0,
        1.2, 0.0,
        1.0, 1.0,
        0.0, 1.0,
    };
    _ = ints;
}
```

```
❯ zig test ./test.zig 
All 1 tests passed.
```

### Expected Behavior

an error saying to not use `.0` when the result type is an int

### Notes

this exists in 0.11 as well

changing one of the values to 1.2 for example does trip a compile error so this shouldn't have caused any wrong behavior thus far

```
❯ zig test ./test.zig
test.zig:4:9: error: fractional component prevents float value '1.2' from coercion to type 'u32'
        1.2, 0.0,
        ^~~
```

**Comment by mlugg** [comment]
Not a bug. Comptime-known floats with no fractional part are permitted to coerce to integers. If you think this should be changed, please file a proposal.

**Comment by nektro** [comment]
> If you think this should be changed, please file a proposal.

can that be this?

**Comment by mlugg** [comment]
A proposal must detail the exact proposed change, and most importantly, the reasoning behind the change (what is the problem with status quo behaviour, and how does the change resolve it?). Best to just open a new issue.
