### ISSUE TITLE
zig fmt reformats everything into the same line even with a trailing comma

### ISSUE THREAD

**Issue by GoWind** [ziglang/zig#18902]
### Zig Version

0.12.0-dev.1830+779b8e259

### Steps to Reproduce and Observed Behavior

Using `zig fmt file.zig` or the vscode zig plugin with `zls`, even with a trailing comma, when a struct is returned from a fn and the fields are ordered in a new line each, `zig fmt` concatenates them into one single long line 
The code can be found [here](https://github.com/GoWind/algorithms/blob/master/zig_mac_perf_events/src/lib.zig#L58)
  
<img width="1395" alt="Screenshot 2024-02-12 at 13 05 46" src="https://github.com/ziglang/zig/assets/1331774/afdb0c09-470b-4dce-8ab8-95be92fe8ba6">

```
return Self{ .dynlib = d, .kpep_db_create = libPerfData.lookup(*const fn (?[*:0]const u8, **kpep_db) callconv(.C) i32, "kpep_db_create").?, .kpep_db_events_count = libPerfData.lookup(*const fn (*kpep_db, *usize) callconv(.C) i32, "kpep_db_events_count").?, .kpep_db_events = libPerfData.lookup(*const fn (*kpep_db, [*]*kpep_event, usize) callconv(.C) i32, "kpep_db_events").?, .kpep_config_create = libPerfData.lookup(*const fn (*kpep_db, **kpep_config) callconv(.C) i32, "kpep_config_create").?, .kpep_config_force_counters = libPerfData.lookup(*const fn (*kpep_config) callconv(.C) i32, "kpep_config_force_counters").?, .kpep_config_add_event = libPerfData.lookup(*const fn (*kpep_config, **kpep_event, u32, ?*u32) callconv(.C) i32, "kpep_config_add_event").?, .kpep_config_kpc_classes = libPerfData.lookup(*const fn (*kpep_config, *u32) callconv(.C) i32, "kpep_config_kpc_classes").?, .kpep_config_kpc_count = libPerfData.lookup(*const fn (*kpep_config, *usize) callconv(.C) i32, "kpep_config_kpc_count").?, .kpep_config_kpc_map = libPerfData.lookup(*const fn (*kpep_config, *usize, usize) callconv(.C) i32, "kpep_config_kpc_map").?, .kpep_config_kpc = libPerfData.lookup(*const fn (*kpep_config, *kpc_config, usize) callconv(.C) i32, "kpep_config_kpc").?, .kpep_db_event = libPerfData.lookup(*const fn (*kpep_db, [*:0]const u8, **kpep_event) callconv(.C) i32, "kpep_db_event").? };

```

### Expected Behavior

I read the related issue in [zls](https://github.com/zigtools/zls/issues/1132) and it says zls uses `zig fmt` to format the file and adding a trailing comma should be enough to move the subsequent struct fields to a new line, but it seems to be not the case.

**Comment by Vexu** [comment]
Cannot reproduce with `0.12.0-dev.2475+dcaf43674`, adding a trailing comma turns one line into 14.

**Comment by nektro** [comment]
given the off color it appears the zls extension or the zls server is not properly configured/crashed. try restarting it and saving the file again. also make sure you have `editor.formatOnSave` enabled in vscode

**Comment by leecannon** [comment]
The line ends with `"kpep_db_event").? };` no trailing comma, you want `"kpep_db_event").?, };`

**Comment by GoWind** [comment]
@leecannon , your suggestion worked. Turns out there has to be a trailing comma after the last member assignment in the struct. 
Thanks ! Closing this issue as PEBKAC.
