### ISSUE TITLE
Zig emits malformed load for struct of two fields in 6th parameter position for C ABI

### ISSUE THREAD

**Issue by mpfaff** [ziglang/zig#18916]
### Zig Version

0.9.0, 0.10.0, 0.11.0, trunk, 0.12.0-dev.2710+c3eb592a3

### Steps to Reproduce and Observed Behavior

View [this reproduction](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyagA%2BudTkVjVEQJDqzTAGF09AK5smUgGzknADIETNgAcp4ARtikUgCs5AAO6ErE9kyuHl6%2BicmpQkEh4WxRMTzx1ti2aSJELKREGZ7ePH4VVUI1dUQFYZHRcVa19Y1ZLYNdPUUlcQCUVujupKicXACkAEwAzMGoHjgA1KubzkpEhMIAdEhHuKtaAIJ390QAngnYODT7p6TutocAdgAQk99mD9u5gkQEkRSKYiPsWEcQQ9wRCoTC4QiIsinqsAQARfYAMXQ6FxDyeADd0ARMBCVKYaBBSeh9jQZhTHg8aXT9mwXkz3ExUBBQeDIcJMfDEeRxWDJdDYTKInLURKMcqEZZ5eipVr9pg1fc0YrpQjsMa0az2U8ZoCUSaJYzmRyufiCU8uHN6NxYvxvFwdOR0NxnN8FktsIctnxyERtN65gBrECbTYXdNZ7M5vy%2BrjSAOJkPcfhKEBaeOJuZwWAoDA4fDEMiUah0RisDjcOOCYRiCScGRyYTKNSaIN6EDrQzGUAALwIwCs2BsdgcECcI2808CwV6xX6Q6SKTX6TcTSnORPaUmfVKsjap86w3PWWnj%2BqQ26e6mh4fX63S9TgmH87ykaQ5iUSNlm4DAmFOEkyUOTYiWwdQiGiJhvlhP4iHxIEWBABkCDnS19giIj3BSUiPXdB40Iw0gsJoLCqOwJlaCI1l7V5TA6PuNCknqdksIFIURTFdUwVMSjqMtXUZOI0irXBRSqJI%2BSpP2NS5JU6TZI0vT2S4sljR42l6Xw3U2I4t1NkdD1vUMP0iwnEsuAALUXCNFmWGNNnWfgEwnGYUzTDMc0irM824QtyEDYNQy4MsKyrELyFrZA0CwPBCBICgqFoBhmHYFYe3kftJCHXtFBUDRi30TYZxMEBflOZdVzSRwmBcV9mlkXdCjAsZjzyM9Mn6q8xtvA9SlaFdKifAC%2BvAjrFs/EChtm7JgJfCbVt278tumFpIOglYNk2VZYiBUhsASUgIGcTlYk9B4EncCJsN%2Bf4bSsrTCKUzSnTBCigeNWjKXo9DMJjdZnA2dYHV1FiGXYmgjmcMAuCRTZcE4xD0E5ey8UJPF3s%2B/YGNhxGEfWJHUbEmhhVQTHsdx/GFIM5SufB3n1J5rSdMM/ndJRkz0DM/YAFobn2CB7X%2BkGIXglgaGjfC0dsxWyZJylCSc/N/Xi4skoAJSohEoN8jWtk2ILqzC9NMyiyLnILVzEtLKxUuCnRQvdwLyDYEBpAATguWItFjWIAQADh8OPYmkJqEv4JKHfSzKIHrdA2ASYqCuoDB88LtBgB4AKBAYRjywgCi3IiYI6hebt%2BCb1hSBeAB5CJdEWtvyBLjhhG7ph6FbtycAidxgGcCR6HLXh%2BBwNhZ0kKeCDuqoqWwJfgzQyp3AwweoRXYt6AICJSBb1wcGLWECBD5e5hoIxgCUAA1AhsAAd2794gZyp9nEFVWQNVRz1TcvoacRgWrmFMJYS%2BERyyQDmOgGEaQl7S27kHdAu9SCkDpHveAkEFrtG8BuHqgEeD%2BB6jNE6U1Tw0KYTeUC21aEfg6MtfanDyFLU2vuRhh0WGHQYYeM6NspA%2BhcibNySV9jqATtLHw0h9jAFQKgfYlcLhIwgE2fK/keAzEzv7DKudS6MCLhAEuBcrFoF2LOHgAItC0PbLXagDdgwdxboPHxXde791sIPYezAiBjwnsWaes9570EXoPVe68VjBkINvOwu9978EPqgY%2BZV%2BBn3zMGZBN8u532SUFIhz8%2BCv3fl/H%2B/9AGDxqpVQc4D5CQPHMGfQsg4FmAsIYK%2BqCFYhkwUIbBuD04EKITgIZZDOrrk3CtWhg0hGHlYUIFho1TziNKGtChz4GhLL2QI%2BoOyDAiKOWI9hJ1JFRmke7Y2ad3KKOUao/YjiTDaIBBcLQFweDywMWQIxJi0pmJztlSx0RWw2LznY/oc4cJMGTNXegHj67Fn8ZPbxzcAl9wHsvIeecR7hPHlile2AZ5zwXkvOMiSTAbxSVvdaGTizZNyafYQ583LFNvjlB%2BlS241JYB/b%2Bf8AHMCaRVUBrThy1THA1NMzV5yLgGSg0hIzTzjLNgtFgKhiS6qIJM6I0ySFoOOV1KhvVeF0MwGc2hWy0ibNyNs65ayuFMAOaI/hG1Tmut2Rc61VzjoSPmFI9YMiuCPNNtwfYC5gD7ERcmAFeUgWXXDaYpy4LbGF2hdm%2BxTBFxICIBPFFaKvHtxxZPOMmLAn4rjKE0epKokUpidShJ2A170vKeQVJzKSFuTZSfAlBSL5XxKS8Mp/Kn6CoELU0VDSJUEuadK1aEC6qdMnLQ3prVLaqtmRqrB3BpauBhNLRgu96BHAJHgqZxChkQE7JwD4Y1yBUgkO4FY6xo7VLmetBZ1CjkrN/Lsh1GyjmgaYHa813CuhevmR6r8UGA0Xk4Yhv19zrZ3M2BGqN8iY1tSIFogtwAi0T2Tc2Ug/lsMZoDkgbALAcAxGGfmOKIco4XHDgCRO0h1iVxkLHacTyM4%2Byan7JM7t7ZyK9slUF4mCEpAcNIIAA) on Godbolt/Compiler Explorer. It has equivalent code in C (GCC and Clang), Zig, and Rust.
The Zig compiler produces a different load for the `f` parameter than the other compilers. I have not checked the spec to confirm, but it seems likely that Zig, being the outlier, is the one emitting the incorrect load.

In my testing (positions in the range [1, 8]), it is critical for the `f` parameter to be in the 6th position. Any higher or lower and the issue goes away.

This issue does not present itself when testing with a `usize` parameter type in either the 6th or 7th parameter positions. Interestingly, from that testing, it looks like Zig might be trying to decompose `Foo` to its components (`usize, usize`) and treat each as its own parameter with respect to the ABI:

<details><summary>Foo (2 usize fields) as 6th parameter (differs from GCC)</summary>

Zig output (you may notice that these loads line up with the loads emitted for a `usize` 6th and 7th parameter, shown in the other spoilers):
```
my_func:
 mov    rsi,QWORD PTR [rsp+0x8]
 mov    rdi,r9
 jmp    d <my_func+0xd>
```

GCC output:
```
my_func:
        mov     rdi, QWORD PTR [rsp+8]
        mov     rsi, QWORD PTR [rsp+16]
        jmp     use_f
```
</details>

<details><summary>Foo (1 usize field) as 6th parameter (same as GCC)</summary>

Zig output:
```
my_func:
 mov    rdi,r9
 jmp    8 <my_func+0x8>
```

GCC output:
```
my_func:
        mov     rdi, r9
        jmp     use_f
```
</details>

<details><summary>Foo (1 usize field) as 7th parameter (same as GCC)</summary>

Zig output:
```
my_func:
 mov    rdi,QWORD PTR [rsp+0x8]
 jmp    a <my_func+0xa>
```

GCC output:
```
my_func:
        mov     rdi, QWORD PTR [rsp+8]
        jmp     use_f
```
</details>

### Expected Behavior

Zig emits a correct load.

If you require more information, or if there is anything I can do to help investigate the cause, I would be happy to help.

**Comment by mpfaff** [comment]
I just checked the [SystemV ABI spec](https://gitlab.com/x86-psABIs/x86-64-ABI/-/jobs/6107675713/artifacts/raw/x86-64-ABI/abi.pdf#subsection.3.2.3), and this section stood out to me:

> The classification of aggregate (structures and arrays) and union types works as fol-
lows:
> ...
> 4. Each field of an object is classified recursively so that always two fields 18 are con-
sidered. The resulting class is calculated according to the classes of the fields in the
eightbyte:
> ...
> 5. Then a post merger cleanup is done:
>   (a) If one of the classes is MEMORY, the whole argument is passed in memory

It sounds to me like Zig is not following step 5, while the other compilers are.

**Comment by Vexu** [comment]
Clang LLVM IR:
```llvm
; Function Attrs: noinline nounwind optnone sspstrong uwtable
define dso_local void @my_func(i64 noundef %0, i64 noundef %1, i64 noundef %2, i64 noundef %3, i64 noundef %4, ptr noundef byval(%struct.Foo) align 8 %5) #0 {
  ...
  %12 = getelementptr inbounds { i64, i64 }, ptr %5, i32 0, i32 0
  %13 = load i64, ptr %12, align 8
  %14 = getelementptr inbounds { i64, i64 }, ptr %5, i32 0, i32 1
  %15 = load i64, ptr %14, align 8
  call void @use_f(i64 %13, i64 %15)
  ret void
}
```
Zig LLVM IR:
```llvm
; Function Attrs: nounwind uwtable
define dso_local void @my_func(i64 %0, i64 %1, i64 %2, i64 %3, i64 %4, i64 %5, i64 %6) #0 {
  %8 = alloca %a.Foo, align 8
  ...
  call void @use_f(i64 %12, i64 %14)
  ret void
}
```

Zig should not split structs into fields after a certain amount of fields.
