### ISSUE TITLE
Issue when making use of dynamic library generated from Zig

### ISSUE THREAD

**Issue by MoinMoinCode** [ziglang/zig#18930]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

- Write zig code with exported functions to use in C for interop. To do this, include the `export` keyword infront of the function. For my code, I wanted to test C interop with Zig so I used a small function
```zig
export fn add(a: i32, b: i32) i32 {
    return a + b;
}
```
- Write a separate c or c++ file containing the function with an `extern` keyword. Since I was using c++, I also tried running with `extern "C"`.
```cpp
extern "C" int add(int a, int b);
```
- Build your project using cmake: For this project, I used cmake to generate the dynamic library using the zig compiler, then link the library to the executable. (P.S. This is only sections of the CMakeLists.txt file. This is not the full code in the file, but the part regarding the zig code).
```cmake
execute_process(COMMAND bash -c "zig build-lib ${PROJECT_SOURCE_DIR}/file.zig -dynamic --name ${ZIG_LIBRARY_NAME} 2> ${CMAKE_CURRENT_BINARY_DIR}/errors.log")

target_link_libraries(testziggy ${ZIG_LIBRARY_DIR})
configure_file(${ZIG_LIBRARY_DIR} "${CMAKE_CURRENT_BINARY_DIR}/lib${ZIG_LIBRARY_NAME}.dylib" COPYONLY)
```
When I ran `cmake ..` in the build directory, it worked as expected, but when I ran `make`, I received the following error:
```log
Consolidate compiler generated dependencies of target testziggy
[ 50%] Building CXX object CMakeFiles/testziggy.dir/main.cc.o
[100%] Linking CXX executable testziggy
ld: __DATA_CONST segment missing SG_READ_ONLY flag in '/.../libzig.dylib'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [testziggy] Error 1
make[1]: *** [CMakeFiles/testziggy.dir/all] Error 2
make: *** [all] Error 2
```

### Expected Behavior

I expected that the code explained would build, and produce the desired executable. Meaning that the zig function was exported to c, and was succesful in this case.

**Comment by mikdusan** [comment]
would you be able to try zig master or nightly? This may have been fixed by 0fd0b765fa84a40446663928db1d3f9a63b7a98d .

**Comment by MoinMoinCode** [comment]
Thanks @mikdusan !

Tried using the master branch, but `make install` didn't complete. Could I get some assistance?

```log
ld: library 'zstd' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [zig2] Error 1
make[1]: *** [CMakeFiles/zig2.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by kubkon** [comment]
Given that #19067 has landed, I assume this has now been fixed and I am proceeding to close the issue. Feel free to submit a new issue or comment on this one if this is not the case.
