### ISSUE TITLE
build-lib build-exe missing -nostdinc -nostdlib

### ISSUE THREAD

**Issue by rsepassi** [ziglang/zig#18950]
### Zig Version

0.12.0-dev.2750+5f9255829

### Steps to Reproduce and Observed Behavior

Using -nostdinc -nostdlib is helpful when trying to build ~hermetically, keeping everything as explicit as possible. Could of course drop down to using zig cc directly, or go up to build.zig, but build-lib/build-exe are nice and easy ways of getting parallelism and a few other niceties. Note that there exists -rcincludes=none, which applies to rc files.

### Expected Behavior

To be able to use -nostdinc -nostdlib (or equivalents).

**Comment by xdBronch** [comment]
is this not the default behavior when you dont pass `-lc`? 
```c
int main() {}
```
compiling this with gcc/clang and passing `-nostdlib -nostdinc` will give a linking error about not finding `_start` and segfaults if you try to run the program. the exact same thing happens when running `zig build-exe` with no additional flags.
is the difference something to do with different platforms?

**Comment by rsepassi** [comment]
So it was my understanding (and I believe observation, though I don't have a neatly packaged test, so the observation could be suspect) that nostdinc and nostdlib also removed default search paths for includes and libraries, e.g. /usr/include /usr/lib etc.

**Comment by xdBronch** [comment]
thats my understanding as well which as far as im aware is the same behavior for zig unless youre linking libc. though interestingly i just tested and gcc seems to keep the library search paths, if i do e.g. `gcc a.c -nostdinc -nostdlib -lraylib` it is still able to link raylib as well as libc and libm etc.

**Comment by rsepassi** [comment]
hmm..so in my use case I am often linking libc, but I don't want zig to go searching /usr for headers and libraries for other things (headers mostly; libraries I have more control over because I'm often building static archives and explictly passing the .a instead of using -l, though sometimes it'd be nice to pass a command-line to CC= somewhere and know that it will only look where I told it to). I think if I explicitly specify -target (even if it is for the current host platform) it won't go looking, is that right?

**Comment by kassane** [comment]
Try:

```bash
zig build-lib -cflags -nostdlib -- <zig-flags> -cflags -nostdinc -- file.zig
```

**Comment by rsepassi** [comment]
I think that works, thanks!
