### ISSUE TITLE
Missing PTR for `[N]*T` and `[N]*const T`

### ISSUE THREAD

**Issue by rohlem** [ziglang/zig#18985]
### Zig Version

0.12.0-dev.2763+7204eccf5

### Steps to Reproduce and Observed Behavior

Test code:
```zig
fn testPtr(comptime A: type, comptime B: type) void {
	_ = @TypeOf(@as(A, undefined), @as(B, undefined));
}
comptime {
	testPtr(*void, *const void); //works
	testPtr(@Vector(1, *void), @Vector(1, *const void)); //also works apparently
	testPtr([1]*void, [1]*const void); //compile error: incompatible types
}
```
`zig test main.zig` output:
```
main.zig:2:6: error: incompatible types: '[1]*void' and '[1]*const void'
 _ = @TypeOf(@as(A, undefined), @as(B, undefined));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.zig:2:14: note: type '[1]*void' here
 _ = @TypeOf(@as(A, undefined), @as(B, undefined));
             ^~~~~~~~~~~~~~~~~
main.zig:2:33: note: type '[1]*const void' here
 _ = @TypeOf(@as(A, undefined), @as(B, undefined));
                                ^~~~~~~~~~~~~~~~~
main.zig:7:9: note: called from here
 testPtr([1]*void, [1]*const void); //compile error: incompatible types
 ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected Behavior

Peer-type resolution of the types should result in the array of pointer-to-const elements,
in line with vector types and the element types themselves.

**Comment by garrisonhh** [comment]
It looks like the logic that produces the error is [here](https://github.com/ziglang/zig/blob/5c25ad0fda23eca4b98aad48d709b3b1b9caf2d6/src/Sema.zig#L34234-L34239). Basically peer resolution only checks if array types' inner elements are both equal, but not if they are coercible in memory
