### ISSUE TITLE
Lack of underflow safety checks in conditionals

### ISSUE THREAD

**Issue by MatthiasPortzel** [ziglang/zig#19012]
### Zig Version

0.11.0, although Discord users have reproduced on 0.12.0-dev.2811+3cafb9655

### Steps to Reproduce and Observed Behavior

```zig
const print = @import("std").debug.print;

pub fn main() !void {
    // Force runtime evaluation
    var x: usize = undefined;
    x = 0;
    if (x - 1 >= 0) {
        print("Okay then\n", .{});
    }
}
```

`zig run` prints "Okay then".

### Expected Behavior

It should throw a runtime error because of integer underflow. (I had messed up my condition in an if statement, and it errored on the next line when it wasn't in an condition.)

**Comment by nektro** [comment]
> an unsigned variable is always `>= 0`, so I suspect the whole check is being elided

yes, however in the original example `x` is runtime-known so the safety check should still be there but the if statement should be analyzed as if it was given a comptime-known `true`
