### ISSUE TITLE
Callable structs

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#19025]
Say you have a lot of platform-specific code (like for supporting windows and posix), which frequently have different return types based on the platform. You want to use the return type optimized for the platform (such as `[:0]const u16` on Windows and `[:0]const u8` on posix). Ideally, the platform-specific differences are handled by default by the platform-specific functions instead of the callers _of_ the functions (reducing complexity and making it more maintainable)

What are the options today?

#### Use the same type for all platforms

example: `std.os.open`
```zig
pub fn open(file_path: []const u8, flags: u32, perm: mode_t) OpenError!fd_t 
```

Then, when you want the more specific type, suffix the function with the type name at the end

```zig
pub fn openZ(file_path: [*:0]const u8, flags: u32, perm: mode_t) OpenError!fd_t 
pub fn openW(file_path_w: []const u16, flags: u32, perm: mode_t) OpenError!fd_t 
```

This means that on Windows, `open` must convert to `[]const u16` on every call to `open` - which is lossy (utf8 != utf16) + costs performance & memory, and it's ambiguous what exactly is the generic type in use without going through `@typeInfo` on the `open` fn

##### Use a wrapper struct

This might look something like:
```zig
pub const open = struct { 
  pub const T = if (isWindows) u16 else u8;

   pub fn path(file_path: []const T, flags: u32, perm: mode_t) OpenError!fd_t { // ... }
   pub fn Z(file_path: [*:0]const u8, flags: u32, perm: mode_t) OpenError!fd_t { // ... }
   pub fn W(file_path_w: []const u16, flags: u32, perm: mode_t) OpenError!fd_t  { // ... }
};

test {
   _ = try open.path("foo", 0, 0);
   _ = try open.Z("foo", 0, 0);
   _ = try open.W(&.{'f', 'o', 'o' }, 0, 0);
}
```

But, this doesn't make the code easier to read. `open.path` obscures the intent. Does that mean `Z` and `W` are not opening the path?

You could also use a `comptime fn` that returns a new `type`, but that ends up looking pretty similar to the wrapper struct approach

## Proposal: callable structs

One idea: if a struct defines a function called `call`, that struct becomes callable like a function

```zig
pub const open = struct  { 
  pub const T = if (isWindows) u16 else u8;
   
   // open(".", 0, 0) is the equivalent of open.call(".", 0, 0)
   pub fn call(file_path: []const T, flags: u32, perm: mode_t) OpenError!fd_t { 
          // ... 
   }

   pub fn Z(file_path: [*:0]const u8, flags: u32, perm: mode_t) OpenError!fd_t {  // ... }
   pub fn W(file_path_w: []const u16, flags: u32, perm: mode_t) OpenError!fd_t  { // ... }
};

test {
   // equivalent of open.call("foo", 0, 0);
   _ = try open("foo", 0, 0);
   _ = try open.Z("foo", 0, 0);
   _ = try open.W(&.{'f', 'o', 'o' }, 0, 0);
}
```

This lets us avoid expensive, buggy conversions without significantly complicating the codebase, and the expected type is unambiguous by convention: `open.T`.

##### Alternative syntax

Another idea: specify the function to call in the struct definition, similar to `packed struct` except when not packed, its the function to call:

```zig
pub const open = struct (myFnNameHere)  { 
  pub const T = if (isWindows) u16 else u8;
   
   // open(".", 0, 0) is the equivalent of open.myFnNameHere(".", 0, 0)
   fn myFnNameHere(file_path: []const T, flags: u32, perm: mode_t) OpenError!fd_t { 
          // ... 
   }

   pub fn Z(file_path: [*:0]const u8, flags: u32, perm: mode_t) OpenError!fd_t {  // ... }
   pub fn W(file_path_w: []const u16, flags: u32, perm: mode_t) OpenError!fd_t  { // ... }
};

test {
   // equivalent of open.myFnNameHere("foo", 0, 0);
   _ = try open.myFnNameHere("foo", 0, 0);
   _ = try open.Z("foo", 0, 0);
   _ = try open.W(&.{'f', 'o', 'o' }, 0, 0);
}
```

**Comment by squeek502** [comment]
Just so I understand, how is this:

```
   _ = try open.path("foo", 0, 0);
```
or this:
```
   _ = try open("foo", 0, 0);
```

not a compile error on Windows? `"foo"` doesn't coerce to `[]const u16`

**Comment by castholm** [comment]
Maybe I'm missing something, but I fail to see how the example use case motivates the need for callable structs. It seems like you want to expose a single function that takes/returns types that are optimal for the target OS. Wouldn't something like this accomplish what you are asking for?

```zig
pub const PathString = if (builtin.os.tag == .windows) PathStringW else PathStringZ;
pub const PathStringZ = [:0]const u8;
pub const PathStringW = [:0]const u16;

pub fn open(path: PathString, flags: u32, perm: mode_t) OpenError!fd_t {
    return if (builtin.os.tag == .windows)
        openW(path, flags, perm)
    else
        openZ(path, flags, perm);
}

pub fn openZ(path: PathStringZ, flags: u32, perm: mode_t) OpenError!fd_t {}
pub fn openW(path: PathStringW, flags: u32, perm: mode_t) OpenError!fd_t {}

test {
    _ = try open("foo", 0, 0); // ignoring that this doesn't work on Windows for the reasons outlined above
    _ = try openZ("foo", 0, 0);
    _ = try openW(&.{ 'f', 'o', 'o' }, 0, 0);
}
```

**Comment by VisenDev** [comment]
I think I would prefer the idea of this being implemented thru a keyword or a builtin function, eg

```zig
const open = struct{
   pub fn callOpen(file_path: []const T, flags: u32, perm: mode_t) OpenError!fd_t { 
          // ... 
   }
   
   @makeCallable(callOpen);
 }
 
   ```
