### ISSUE TITLE
Building zig fails under Linux Mint

### ISSUE THREAD

**Issue by ci4ic4** [ziglang/zig#19022]
### Zig Version

0.12.0-dev.2814+7775e46e8

### Steps to Reproduce and Observed Behavior

Last successful build is from 18th of February, version as above. 

Tested using cmake 3.29.0 rc1, ninja 1.11.1 and make. 

```
/home/xci/src/zig/build/zig2.c:469340:64: error: ‘memory_order_release’ undeclared (first use in this f
unction); did you mean ‘zig_memory_order_release’?
/home/xci/src/zig/stage1/zig.h:3648:72: error: non-integer memory model argument 3 of ‘__atomic_store’
/home/xci/src/zig/build/zig2.c:474237:94: error: ‘memory_order_relaxed’ undeclared (first use in this f
unction); did you mean ‘zig_memory_order_relaxed’?
/home/xci/src/zig/stage1/zig.h:3637:85: error: non-integer memory model argument 5 of ‘__atomic_compare
_exchange’
/home/xci/src/zig/build/zig2.c:525984:85: error: ‘memory_order_seq_cst’ undeclared (first use in this f
unction); did you mean ‘zig_memory_order_seq_cst’?
/home/xci/src/zig/build/zig2.c:550989:57: error: ‘memory_order_release’ undeclared (first use in this f
unction); did you mean ‘zig_memory_order_release’?
/home/xci/src/zig/stage1/zig.h:3639:72: error: non-integer memory model argument 4 of ‘__atomic_exchang
e’
/home/xci/src/zig/build/zig2.c:588344:52: error: ‘memory_order_relaxed’ undeclared (first use in this f
unction); did you mean ‘zig_memory_order_relaxed’?
/home/xci/src/zig/stage1/zig.h:3648:72: error: non-integer memory model argument 3 of ‘__atomic_store’
/home/xci/src/zig/build/zig2.c:588379:57: error: ‘memory_order_acquire’ undeclared (first use in this f
unction); did you mean ‘zig_memory_order_acquire’? 
```
About 70 error messages as above seen. 

Linux version - Mint 21.3, kernel: `Linux ... 6.7.5-1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 6.7-10ubuntu1~jammy (2024-02-17) x86_64 x86_64 x86_64 GNU/Linux`

### Expected Behavior

Successful completion of compiler build procedure.

**Comment by jacobly0** [comment]
Somehow you have replaced `stage1/zig.h` with `lib/zig.h` and yet are compiling with an old `stage1/zig1.wasm`.  The manual command `zig build update-zig1` updates both of these files, but it is not run by `cmake` or any other build command, so it's unclear how you got into this state of only one of those files being updated.  Since this is not the actual state of `7775e46e8`, it is not supported.

**Comment by ci4ic4** [comment]
Well, that's exactly what I did a couple of days ago, looking at 'zig build' various options. It never came to my mind that it may have such consequences. Sorry for the noise. Although perhaps a newbie-targeted message not to run this type of commands might be nice...

**Comment by jacobly0** [comment]
Alright, my guess is that you didn't have `wasm-opt` installed, and so the copy step succeeded and the wasm step failed, leaving the repository in an invalid state.
