### ISSUE TITLE
std.dynamic_library.DlDynLib does not give useful errors

### ISSUE THREAD

**Issue by dylanblokhuis** [ziglang/zig#19039]
Whenever loading libs using ``DlDynLib`` it will always return ``error.FileNotFound`` while there could be other errors happening.

https://github.com/ziglang/zig/blob/e60d66711185fa2e3164f5af92b9786e04c4fa19/lib/std/dynamic_library.zig#L380-L386

There's a way to get the error by using [dlerror](https://linux.die.net/man/3/dlerror), but I see no such function in ``c.zig``, is this not supported on all platforms?
https://github.com/ziglang/zig/blob/e60d66711185fa2e3164f5af92b9786e04c4fa19/lib/std/c.zig#L1836-L1840

**Comment by andrewrk** [comment]
Fixed in cbeab678a50e48ba55f39b391fcfe98823fe3c8c
