### ISSUE TITLE
error: unable to resolve inferred error set for a simple program

### ISSUE THREAD

**Issue by go101** [ziglang/zig#19036]
### Zig Version

0.12.0-dev.2824+0b7af2563

### Steps to Reproduce and Observed Behavior

This doesn't compile:

```zig
fn f() !void {
	return g(0);
}

fn g(n: u32) !void {
	if (n > 100) {
		try f(); // error: unable to resolve inferred error set
	}
}

pub fn main() void {
    try f();
}
```

But this compiles:

```zig
fn f() !void {
	return g(0);
}

fn g(n: u32) !void {
	if (n > 100) {
		return g(0);
	}
}

pub fn main() !void {
    try f();
}
```

### Expected Behavior

Maybe I haven't understood the error system in zig well, but I think both should compile.

**Comment by mlugg** [comment]
To simplify the language specification, inferred error set resolution does not support mutual recursion (two functions calling one another). Give either `f` or `g` (or both) an explicit error set.

**Comment by go101** [comment]
Thanks for the explanation. I still have some confusions.
Does it mean I need explicitly specify the error set for the function `g`?
If the function `g` will call many other functions, how to get the union of the error sets returned those functions?
