### ISSUE TITLE
Multiple integer overflow errors in std.hash_map

### ISSUE THREAD

**Issue by pwnfooj716** [ziglang/zig#19041]
### Zig Version

0.12.0-dev.2820+556db2ca3

### Steps to Reproduce and Observed Behavior

There are multiple issues with the way the capacity is handled in std.hash_map.zig as demonstrated below:
```
test "hashmap" {
    var map = std.AutoHashMap(i32, i32).init(std.testing.allocator);
    defer map.deinit();

    const full = std.math.maxInt(@TypeOf(map).Size);
    const half = full / 2;
    const quarter = full / 4;
    const buggy = 3435973837;

    // Problem 1
    // This is the worst of the problems because it causes silently incorrect behavior with the current implementation
    // This "works" when it should fail because the overflow is truncated in capacityForSize()
    try map.ensureTotalCapacity(buggy);
    try std.testing.expect(map.capacity() >= buggy); // map.capacity() is actually 8! it overflows to 1, but is set to 8 since that's the minimal_capacity

    // Problem 2
    // This fails simply because we use a variable of type Size(u32) instead of a usize for pointer calculations in allocate() and deallocate()
    try map.ensureTotalCapacity(quarter);

    // Problem 3
    // Even if we fix Problem 2, this fails because the hashmap can only grow in powers of 2
    // Therefore, any request to grow to capacity between (2^31)+1 and (2^32)-1 will fail
    // Once load factor is taken into account, this request puts it over (2^31)+1, so it fails
    try map.ensureTotalCapacity(half);

    // Problem 4 (combination of previous problems)
    // Fails due to Problem 2, but if we fix Problem 2, then it incorrectly succeeds due to Problem 1!
    try map.ensureTotalCapacity(full);
}

```

### Expected Behavior

In Problem 1, the call to ensureTotalCapacity() should fail because once the load factor is taken into account, it overflows the maximum Size. The current code just truncates it away and happily continues with much lower value.This can be solved by using @intCast() instead of @truncate() to correctly catch the overflow.

In Problem 2, this call should succeed since the hashmap can easily grow to the requested size if the variables used had enough room to perform the pointer calculations. This can be solved by using usize variables instead of Size(u32) to perform pointer calculations in allocate() and deallocate().

In Problem 3, in theory it should work given Problem 2 is solved. But, since the hashmap can only grow in powers of 2 it fails. I don't know the original reasoning behind only allowing to grow in exactly powers of 2. If it is simply to provide an exponential growth scale, then I don't see why std.math.maxInt(u32) can't be used for values between (2^31)+1 and (2^32)-1. Otherwise, huge amounts of growth is being wasted for no reason (half of the potential values!). Applying that fix breaks the assert that new_cap is a power of 2 in grow(), so is there a good reason for this, or can that assert be removed or changed?

In Problem 4, it should fail and it does, but for the wrong reason. It fails due to Problem 2, but if problem 2 is fixed, then it incorrectly succeeds due to Problem 1.

I have a patch to fix these issues. The only thing I am unsure about is how to handle the power of 2 growth issue. Is it ok to grow to std.math.maxInt(u32) even though it is not a power of 2?

**Comment by pwnfooj716** [comment]
Here is my tentative [patch](https://github.com/pwnfooj716/zig/commit/231c069ddea7bb55859256fb1f17573505ae7734). Once I have fully tested it, I will submit a PR.

**Comment by pwnfooj716** [comment]
Here is my tentative [patch](https://github.com/pwnfooj716/zig/commit/231c069ddea7bb55859256fb1f17573505ae7734). Once I have fully tested it, I will submit a PR.

**Comment by squeek502** [comment]
> I don't know the original reasoning behind only allowing to grow in exactly powers of 2

It's to enable using `hash & (capacity - 1)` to calculate an index instead of `hash % capacity`. Here's where it was originally introduced in the old `HashMap` implementation (now `ArrayHashMap`): https://github.com/ziglang/zig/pull/2630

It looks like the current `HashMap` also uses this:

https://github.com/ziglang/zig/blob/30f15e3afe38afb6b8c1a378c326d29d2ebab378/lib/std/hash_map.zig#L1029-L1031

(it does the same thing in a few other places as well)

so a non-power-of-two capacity will cause some problems.

**Comment by pwnfooj716** [comment]
I see. Had a feeling there was a specific reason. Well, even with capacity being limited to (2^32)/2 that still requires at least 8GB of RAM just to store the keys (if using perfectly optimal keys), so probably not an issue for must use-cases. I only discovered this limitation while investigating the other issues. 

Problems 1 and 2 are real issues though. The pointer math overflowing in particular was what lead me to digging into this in the first place. I'll make an update reverting the power of 2 changes and submit a PR.
