### ISSUE TITLE
About Windows named pipe APIs missing

### ISSUE THREAD

**Issue by jinzhongjia** [ziglang/zig#19047]
Named pipe is a commonly used solution for inter-process communication. For example, neovim uses named pipes by default on Windows, and unixsocket is used by default on Linux for RPC calls.According to Microsoft's [document](https://learn.microsoft.com/en-us/windows/win32/api/namedpipeapi/), windows provides some useful encapsulation functions.

## Existing APIs

I have read through the Windows API in the standard library and found that there are some named pipe APIs.
Like: [`CreateNamedPipeW`](https://ziglang.org/documentation/master/std/#A;std:posix.windows.kernel32.CreateNamedPipeW), [`CreatePipe`](https://ziglang.org/documentation/master/std/#A;std:posix.windows.CreatePipe).
But I didn't find more apis about namedpipe, maybe we need to improve this part?

For examples: 
- [CallNamedPipeW](https://learn.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-callnamedpipew)
- [ConnectNamedPipe](https://learn.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-connectnamedpipe)
- [DisconnectNamedPipe](https://learn.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-disconnectnamedpipe)
- [GetNamedPipeClientComputerNameW](https://learn.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-getnamedpipeclientcomputernamew)
- [GetNamedPipeHandleStateW](https://learn.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-getnamedpipehandlestatew)
- [GetNamedPipeInfo](https://learn.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-getnamedpipeinfo)
- [ImpersonateNamedPipeClient](https://learn.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-impersonatenamedpipeclient)
- [PeekNamedPipe](https://learn.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-peeknamedpipe)
- [SetNamedPipeHandleState](https://learn.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-setnamedpipehandlestate)
- [TransactNamedPipe](https://learn.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-transactnamedpipe)
- [WaitNamedPipeW](https://learn.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-waitnamedpipew)

**Comment by squeek502** [comment]
Zig is not intending on providing Windows API bindings that it does not use internally: https://github.com/ziglang/zig/issues/4426

See also:
- https://github.com/ziglang/zig/issues/1840
- https://github.com/ziglang/zig/issues/19037
