### ISSUE TITLE
dependency fetch hangs indefinitely 

### ISSUE THREAD

**Issue by leecannon** [ziglang/zig#19052]
### Zig Version

0.12.0-dev.2833+8802ec583

### Steps to Reproduce and Observed Behavior

Fetching the url `https://github.com/rust-osdev/ovmf-prebuilt/releases/download/edk2-stable202311-r2/edk2-stable202311-r2-bin.tar.xz` never completes.

Either using `zig fetch` or adding it to the `build.zig.zon` results in the fetch hanging indefinitely.

However using `std.http.Client` directly correctly fetches the file:
```zig
const std = @import("std");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    var client: std.http.Client = .{ .allocator = allocator };
    defer client.deinit();

    var fetch = try client.fetch(allocator, .{
        .location = .{
            .url = "https://github.com/rust-osdev/ovmf-prebuilt/releases/download/edk2-stable202311-r2/edk2-stable202311-r2-bin.tar.xz",
        },
    });
    defer fetch.deinit();

    std.debug.print("File size: {}\n", .{std.fmt.fmtIntSizeBin(fetch.body.?.len)});
}
```
```
$ zig build run
Got 4.326690673828125MiB bytes of data
```

### Expected Behavior

Fetch doesn't hang.

**Comment by ianic** [comment]
If I `wget` `unxz` file and then tray to untar it works fine:
```
    var dir = try std.fs.cwd().openDir(".", .{ .iterate = true });
    var file = try dir.openFile("edk2-stable202311-r2-bin.tar", .{});
    defer file.close();

    const out = try std.fs.cwd().openDir("./tmp", .{ .iterate = true });
    try std.tar.pipeToFileSystem(out, file.reader(), .{ .mode_mode = .ignore });
```

If I `wget` and than try to decompress it advances but very slowly
```
var dir = try std.fs.cwd().openDir(".", .{ .iterate = true });
    var file = try dir.openFile("edk2-stable202311-r2-bin.tar.xz", .{});
    defer file.close();

    const allocator = std.heap.page_allocator;
    var dcp = try std.compress.xz.decompress(allocator, file.reader());
    while (true) {
        var buf: [4096]u8 = undefined;
        const n = try dcp.read(&buf);
        std.debug.print("{d} ", .{n});
        if (n < buf.len) break;
    }
```

xz is spending lot of time in moving bytes and resizing 200MB buffer [here](https://github.com/ziglang/zig/blob/7230b68b350b16c637e84f3ff224be24d23214ce/lib/std/compress/xz/block.zig#L64-L65)
So I think that we can label this as compress.xz performance problem.

**Comment by squeek502** [comment]
cc @FnControlOption since they're the original author of `std.compress.xz`
