### ISSUE TITLE
@sliceToBytes should work on single-item pointers to arrays

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1905]
```
error: expected slice type, found '*const [32]u6'
     const asdf = @bytesToSlice([]const u5, @sliceToBytes(&p));
```

Even though it's not a slice, it's abundantly clear what should happen.

**Comment by emekoi** [comment]
possibly related: #421, #1821, #991.

**Comment by kristate** [comment]
@Hejsil and I ran into this on a live stream:
```zig
var s: Self = undefined;
// pub fn secureZero(comptime T: type, s: []T) void
mem.secureZero(Self, (*[1]Self)(&s));
```
this is ugly. It would be nice to just call:
```zig
var s: Self = undefined;
mem.secureZero(Self, &s);
```

**Comment by andrewrk** [comment]
Casting `*T` to `[]T` pointers to slices has not been proposed yet. This proposal is for `*[1]T` to `[]T`.

**Comment by andrewrk** [comment]
`@sliceToBytes` and `@bytesToSlice` were removed from the language in 1d06c82c3bc44e808a3d7b4fe07e5c9fc492e8c3. `std.mem.sliceAsBytes` and `std.mem.bytesAsSlice` are available to replace them.
