### ISSUE TITLE
Comptime-known block result with preceding runtime branch is permitted only when break is trailing

### ISSUE THREAD

**Issue by mlugg** [ziglang/zig#19060]
### Zig Version

0.12.0-dev.2763+7204eccf5

### Steps to Reproduce and Observed Behavior

Compare the following two tests:
```zig
test {
    var t: bool = undefined;
    t = true; // runtime-known

    const a: comptime_int = a: {
        if (t) return;
        break :a 123;
    };
    _ = a;
}

test {
    var t: bool = undefined;
    t = true; // runtime-known

    const a: comptime_int = a: {
        if (!t) break :a 123;
        return;
    };
    _ = a;
}
```
These are logically identical; we've just changed which way we wrote the runtime condition. However, the first compiles successfully, while the second triggers a compile error:
```shellsession
[mlugg@vega test]$ zig test foo.zig
foo.zig:16:32: error: value with comptime-only type 'comptime_int' depends on runtime control flow
    const a: comptime_int = a: {
                            ~~~^
foo.zig:17:13: note: runtime control flow here
        if (!t) break :a 123;
            ^~
```
This is caused by logic in `Sema.analyzeBlockBody`, which elides the AIR block - thereby skipping comptime-only type logic - only if the single result merge is the last instruction in the block:

https://github.com/ziglang/zig/blob/cfce81f7d5f11ab93b2d5fd26df41edf967f333b/src/Sema.zig#L6001-L6013

### Expected Behavior

Either these should both be compile errors, or both should compile successfully (i.e. the result being comptime-known is a sufficient condition even if the block itself may perform other runtime control flow).

**Comment by andrewrk** [comment]
Looks like `a` should indeed be comptime-known to me in both cases, since it truly has only one potential outcome.
