### ISSUE TITLE
I can't init a project on Windows

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [ziglang/zig#19078]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

Install Zig via winget or the zip file on the downloads page and try to init a project via `zig init`.

**Observed Behavior:** It shows the help panel and at the bottom stands: `error: unknown command: init`

### Expected Behavior

It sets up the project like it was explained in the documentation.

**Comment by nullptrdevs** [comment]
`zig init` is 0.12 only, 0.11 has two variations
https://ziglang.org/documentation/0.11.0/#Building-an-Executable
https://ziglang.org/documentation/0.11.0/#Building-a-Library
