### ISSUE TITLE
for loop as expression doesnt accept implicit break from value

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#19085]
### Zig Version

0.12.0-dev.2991+119b2030f

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

test {
    const x = for (0..28) |i| i;
    try std.testing.expect(x == 0);
}
```

```
test2.zig:4:31: error: value of type 'usize' ignored
    const x = for (0..28) |i| i;
                              ^
test2.zig:4:31: note: all non-void values must be used
test2.zig:4:31: note: this error can be suppressed by assigning the value to '_'
```

### Expected Behavior

all for loops should iterate up until the first block that doesn't evaluate to `void{}`. this is what regular blocks with labelled exits are long-handing

**Comment by mlugg** [comment]
> this is what regular blocks with labelled exits are long-handing

No, it isn't. It is perfectly valid to break from a loop with `void`, and in fact that is what a `break` without an operand does. The syntax forms `lbl: for (...) |...| { ... }` and `for (...) |...| lbl: { ... }` have entirely different meanings; `break :lbl` with the first exits the loop, whilst with the second it exits the block (continuing to the next loop iteration).

Treating this as a proposal, "iterate up until the first block that doesn't evaluate to `void{}`" kind of fundamentally breaks the type system - a block can't have type `void` *and* a different type.

If you would like the behavior of this syntax to be changed, please open a detailed proposal.
