### ISSUE TITLE
Printing zig build-exe's argv by default is unhelpful

### ISSUE THREAD

**Issue by zkburke** [ziglang/zig#19109]
Just so everyone understands what I'm referring to here, when I talk about a step's argv, I'm referring to the printing of the equivilent shell command for a step that is rendered after and below ```error: the following command failed with 1 compilation errors:``` when an error occurs. 

I completely understand why printing the argv for a step can be useful for debugging the build system, but in most cases this just adds significant unwanted noise when language error messages occur. It requires one to scroll up in most terminal windows to find the Zig errors (and when you have a project with large argvs, this is not insignificant). 

In environments like emacs and vscode, terminal windows are short strips at the bottom of the screen, and wasting valuable space printing what is essentially build system internal information is wasteful in my view. Instead, perhaps we could consider making an explicit opt-in flag for this, for when the args passed to a command are actually wanted by the user when debugging their build system (this would be a flag similar to -freference-trace such).

As for a reason or use-case, in my case, it doesn't take very long when working with generated files passed as modules for the argv to get ridiculous (```zig build-exe -M="some absolute path to the cache"``` in this case).

Of course, I'm just one person, so this may not be the default that most want. I'm happy to be proved very wrong on this issue.

**Comment by andrewrk** [comment]
slap `--prominent-compile-errors` onto your `zig build` command and I think it will be satisfactory. 

Or use an IDE with a proper error list.
