### ISSUE TITLE
is the parser broken?

### ISSUE THREAD

**Issue by TunifyBasic** [ziglang/zig#19164]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Output

```
const keywords: []u8 = {
        "random",
        "keyword",
        "example"
};

// got:
src/tok.zig:114:10: error: expected ';' after statement
 "random",
         ^
```

so i fixed it then trying to work with it like
```
for (0..keywords.len) |i| {
                if (std.mem.eql(u8, keywords[i], tok.ref)) {
                        return TokProp.Kw;
                }
        } 
// got:
tok.zig:113:26: error: value of type '*const [6:0]u8' ignored
const keywords: []u8 = { "random"; "keyword"; "example"; };
                         ^~~~~~~~
tok.zig:113:26: note: all non-void values must be used
tok.zig:113:26: note: this error can be suppressed by assigning the value to '_'
```

### Expected Output

i just expected it to work. :)

**Comment by omaraaa** [comment]
You forgot to add `[_]u8` before `{`.

**Comment by Trevor-Strong** [comment]
Two things:

1. `{ ... }` is a block, not a slice literal. To get a slice literal you have to use `&.{ ... }` (take the address of an array literal). 

2. The type of a string literal is `[]const u8`. If you want a slice of strings the type of `keywords` should be `[] const[] const u8` (slice of u8 slices).

**Comment by mlugg** [comment]
Your code is incorrect - exactly as said by Trevor-Strong.
If you haven't already, I'd encourage you to either read the language reference or closely read some actual Zig code before trying to write it!
