### ISSUE TITLE
allow multi/diffrent .zig file extensions

### ISSUE THREAD

**Issue by octanejohn** [ziglang/zig#19220]
allow the use of .zg, one less letter and it sounds like zig

ideas before 1.0 release

**Comment by tauoverpi** [comment]
This only makes things less clear. I'm not sure how this is an improvement? Such things are better to ask about in [community channels](https://github.com/ziglang/zig/wiki/Community) before making a ticket.

**Comment by mlugg** [comment]
Drive-by proposal; you have no public repositories using Zig, and this proposal has no justification and no clear benefits.
