### ISSUE TITLE
`usingnamespace opaque{};` now errors ("type [...] has no namespace")

### ISSUE THREAD

**Issue by rohlem** [ziglang/zig#19232]
### Zig Version

0.12.0-dev.3182+f3227598e

### Steps to Reproduce and Observed Behavior

I just updated from zig version `0.12.0-dev.3002+9d7082972` to `0.12.0-dev.3182+f3227598e`.
With this new version running `zig test` on a file containing `usingnamespace opaque{};` yields:

```
main.zig:1:16: error: type main.usingnamespace_0__opaque_145 has no namespace
usingnamespace opaque {};
               ^~~~~~~~~
main.zig:1:16: note: opaque declared here
```

In the previous version this works without issue.

Note that an argument `struct{}`, `union{}`, and `enum{}` to `usingnamespace` also passes without error, so `opaque{}` is the odd one out.
Adding any declaration (even just a semantical no-op `usingnamespace enum{};`) as the `opaque`'s contents also works around the error.

### Expected Behavior

I'd expect `usingnamespace` not to differentiate between the kinds of containers used.

While I haven't reduced to the change that introduced this difference, I would assume it happened unintentionally during https://github.com/ziglang/zig/pull/19190 .

**Comment by Vexu** [comment]
This seems to be intentional and also planned for structs, unions and enums if `@This()` is not used in fields:
```zig
const T = @Type(.{ .Struct = .{
    .layout = .auto,
    .fields = &.{},
    .decls = &.{},
    .is_tuple = false,
}});

usingnamespace T;
```
```zig
        .has_namespace = true or decls_len > 0, // TODO: see below

...

    // TODO: if AstGen tells us `@This` was not used in the fields, we can elide the namespace.
    const new_namespace_index: InternPool.OptionalNamespaceIndex =
```

**Comment by andrewrk** [comment]
It's a regression. All structs, unions, enums, and opaques have namespaces.

**Comment by mlugg** [comment]
Yep - the fact that the type doesn't have a namespace internally is an implementation detail for optimization purposes.
