### ISSUE TITLE
new autodoc system doesnt include stdlib files for 3rd party projects

### ISSUE THREAD

**Issue by xdBronch** [ziglang/zig#19259]
### Zig Version

0.12.0-dev.3245+4f782d1e8

### Steps to Reproduce and Observed Behavior

take any project/file that uses the stdlib and build with `-femit-docs` then open the generated docs. clicking any links referencing the stdlib will lead to a `Declaration not found.` page

### Expected Behavior

referenced modules should be included somehow. more discussion may be needed

**Comment by andrewrk** [comment]
If this was not solved by #19458, please clarify and I will reopen.

**Comment by xdBronch** [comment]
yep that fixed it, thanks for checking back and thank you @ianprime0509 for fixing this!
