### ISSUE TITLE
std.os.linux.mount return type is `usize`, but can only return 0 or -1 according to man

### ISSUE THREAD

**Issue by koiuo** [ziglang/zig#19251]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

```
const std = @import("std");

pub fn main() !void {
    const fstype = null;
    const data = 0;
    const flags = 0;

    const ret = std.os.linux.mount("/src", "/dst", fstype, flags, data);
    std.debug.print("{d}\n", .{ ret });
}
```

Running this code prints
```
18446744073709551615
```

However, the man says, 
> RETURN VALUE
>       On success, zero is returned.  On error, -1 is returned, and errno is set to indicate the error.

### Expected Behavior

The function should return a signed int and the code should print
```
-1
```

**Comment by andrewrk** [comment]
This is a syscall, however you are reading documentation for libc. Please have a look at how all the std.os functions make use of std.os.linux, in particular how they extract the error from the syscall without resorting to something ridiculous like a thread local variable.
