### ISSUE TITLE
Passing a string to `[]c_char` causes an error on x86 but not ARM

### ISSUE THREAD

**Issue by RossComputerGuy** [ziglang/zig#19256]
### Zig Version

0.12.0-dev.3193+4ba4f94c9

### Steps to Reproduce and Observed Behavior

1. Try to build a simple program which passes a string to a `[]c_char` (or a `[]const c_char`) and target x86_64-linux
2. Do the same thing but target for aarch64-linux

Discovered by @theoparis in https://github.com/PhantomUIx/display-xcb, occurs on GitHub Actions.

### Expected Behavior

Both targets should either error or accept the string as is

**Comment by Rexicon226** [comment]
This is *not* a bug. On ARM, `char` is unsigned, while on x86 `char` is signed. [See here](https://developer.arm.com/documentation/den0013/d/Porting/Miscellaneous-C-porting-issues/unsigned-char-and-signed-char)

**Comment by RossComputerGuy** [comment]
Oh, is there a more elegant solution to resolve this than to just use u8 or do a pointer cast?

**Comment by f-cozzocrea** [comment]
> Oh, is there a more elegant solution to resolve this than to just use u8 or do a pointer cast?

Those are probably the only ways to do it. Zig's type-safety requires that you be explicit about bitcasting values.

**Comment by RossComputerGuy** [comment]
Alright then I'll close this issue.
