### ISSUE TITLE
std.fmt.parseFloat: add f80 float parsing support

### ISSUE THREAD

**Issue by tiehuis** [ziglang/zig#19263]
f80 floats are not currently supported in the parseFloat routine.

https://github.com/ziglang/zig/blob/da5b16f9e2b76534b1cab9093566693482084360/lib/std/fmt/parse_float/parse_float.zig#L17-L19

This should be added and we should be able to round-trip against the formatting output. The below f80 exception in the float formatting tests should be able to be removed and should pass.

https://github.com/ziglang/zig/blob/da5b16f9e2b76534b1cab9093566693482084360/lib/std/fmt/ryu128.zig#L961-L980

**Comment by fla-t** [comment]
Would like to know more about this, my main question is that what differs in float80 that we can't do it through Eisel-Lemire algorithm?

Just like the rest?

**Comment by tiehuis** [comment]
As a first-pass I would ignore the eisel-lemire parsing algorithm. This is intended for 64-bit values and would be non-trivial to extend to 80-bit floats. The tables required I would expect to grow significantly as well in this case beyond what is reasonable.

I would start by implementing the fast-path `convert_fast.zig` and slow-path `convert_slow.zig` and ensuring this is correct and would consider this enough for now. This shouldn't require too much additional code, just need to ensure the explicit integer bit is handled and compute the constants in `FloatInfo.zig`.
