### ISSUE TITLE
std docs: url hash includes file slug

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#19262]
### Zig Version

0.12.0-dev.3212+40e64245f

### Steps to Reproduce and Observed Behavior

https://ziglang.org/documentation/master/std/#std.array_list.ArrayList

note the `#std.array_list.ArrayList`.

### Expected Behavior

`ArrayList` is only accessible in code through `std.ArrayList`, the url should reflect that.

**Comment by andrewrk** [comment]
Working as designed. This matches fully qualified type names chosen by the compiler, for example.

**Comment by nektro** [comment]
so that means this would automatically get resolved at the same time as https://github.com/ziglang/zig/issues/19010 ?
