### ISSUE TITLE
Cross compile to Windows fails with relative global cache directory path

### ISSUE THREAD

**Issue by aherrmann** [ziglang/zig#19284]
### Zig Version

0.12.0-dev.3282+da5b16f9e

### Steps to Reproduce and Observed Behavior

Configuring a global cache directory on the command line using a relative path causes cross compilation to Windows to fail. Tested on Ubuntu 22.04 x86_64.

**Steps to reproduce**

Download and unpack the Zig SDK.
```shell
$ curl -L https://ziglang.org/builds/zig-linux-x86_64-0.12.0-dev.3282+da5b16f9e.tar.xz -o zig-linux-x86_64-0.12.0-dev.3282+da5b16f9e.tar.xz
$ tar xvf zig-linux-x86_64-0.12.0-dev.3282+da5b16f9e.tar.xz
```

Create a simple hello world program.
```shell
$ cat <<EOF >main.zig
const std = @import("std");

pub fn main() !void {
    try std.io.getStdOut().writer().print("Hello world!\n", .{});
}
EOF
```

Try to cross-compile to Windows while specifying a global cache directory on the command line using a relative path.
```shell
$ zig-linux-x86_64-0.12.0-dev.3282+da5b16f9e/zig build-exe --global-cache-dir custom-zig-global-cache -target x86_64-windows-gnu main.zig
error: unable to generate DLL import .lib file for kernel32: FileNotFound
```
Observe how the build fails due to a missing `.lib` file for the `kernel32` library.

Run the same command, but use an absolute path for the global cache directory parameter.
```shell
$ zig-linux-x86_64-0.12.0-dev.3282+da5b16f9e/zig build-exe --global-cache-dir $PWD/custom-zig-global-cache -target x86_64-windows-gnu main.zig
$ wine64 ./main.exe
Hello world!
```
Observe how the build succeeds and the produced binary can run with Wine.

**Context**

This issue was initially observed in https://github.com/aherrmann/rules_zig when trying to update to Zig 0.12.0-dev. To ensure that builds are hermetic and reproducible, rules_zig controls the global and local cache directories. At the moment it [declares a global and local cache output](https://github.com/aherrmann/rules_zig/blob/0c4490cb3cd0440314b8144f904da50ec28b6b48/zig/private/common/zig_cache.bzl) for each build action that is managed by Bazel. Bazel operates on relative paths, so these cache directory paths are always configured using relative paths.

(Side note: Better cache handling is planned as a future improvement, see https://github.com/aherrmann/rules_zig/issues/87)

### Expected Behavior

Zig builds should succeed irrespective of whether the global (or local) cache paths are specified as relative or absolute paths.

**Comment by squeek502** [comment]
Could possibly be a regression introduced in https://github.com/ziglang/zig/pull/19173

**Comment by unnask** [comment]
Seems also related to the error I am getting from a basic raylib hello-world:

`error: unable to check cache: stat file '/Users/<user>/.cache/zig/p/1220218d3958e4b46293456abc189ec98e8a7e3add6a46550b852bc0952609805315/Users/<user>/.cache/zig/p/1220218d3958e4b46293456abc189ec98e8a7e3add6a46550b852bc0952609805315/src/rcore.c' failed: FileNotFound`

Seems the path up to the downloaded cache directory is being inserted twice.

**Comment by aherrmann** [comment]
git bisect identified https://github.com/ziglang/zig/commit/9f2cb920c055bc990cc9d593b8dc9eaa450d07b9 from https://github.com/ziglang/zig/pull/17771 as the culprit.
