### ISSUE TITLE
floatFromInt builtin doesn't preserve inf

### ISSUE THREAD

**Issue by andrewCodeDev** [ziglang/zig#19280]
### Zig Version

0.12.0-dev.3247+26e895e3d

### Steps to Reproduce and Observed Behavior

I have to cast to device compatible types and part of that process is reinterpreting f16 to u16. I noticed that inf doesn’t get carried over when using the builtin methods, but pointer casting does:
```Zig
pub fn main() !void {

    const x = std.math.inf(f16);

    const u: *const u16 = @ptrCast(&x);

    // @floatFromInt - doesn't preserve inf
    const y: f16 = @floatFromInt(u.*);
    
    // pointer casting - preserves inf
    const z: f16 = @as(*const f16, @ptrCast(u)).*;

    std.log.info("Original: {}", .{ x });
    std.log.info("Builtin Cast: {}", .{ y });
    std.log.info("Pointer Cast: {}", .{ z });
}
```
Output: 
```Zig
info: Original: inf
info: Builtin Cast: 3.1744e+04
info: Pointer Cast: inf
```

### Expected Behavior

Preserve inf from builtin casting operator:

```Zig
info: Original: inf
info: Builtin Cast: inf
info: Pointer Cast: inf
```

**Comment by ianprime0509** [comment]
[`@floatFromInt`](https://ziglang.org/documentation/master/#floatFromInt) doesn't do a bit-for-bit conversion of the value, it does a numerical conversion (take an int and return a float with the same numerical value). In this case, the numerical value of `u.*` happens to be 31744.

If you need a bit-for-bit cast, you can use [`@bitCast`](https://ziglang.org/documentation/master/#bitCast).

```zig
const std = @import("std");

pub fn main() !void {
    const x = std.math.inf(f16);

    const u: *const u16 = @ptrCast(&x);

    // @floatFromInt - doesn't preserve inf
    const y: f16 = @floatFromInt(u.*);

    // @bitCast
    const yy: f16 = @bitCast(u.*);

    // pointer casting - preserves inf
    const z: f16 = @as(*const f16, @ptrCast(u)).*;

    std.log.info("Original: {}", .{x});
    std.log.info("As u16: {}", .{u.*});
    std.log.info("Builtin Cast: {}", .{y});
    std.log.info("Bitcast: {}", .{yy});
    std.log.info("Pointer Cast: {}", .{z});
}
```

Output:

```
info: Original: inf
info: As u16: 31744
info: Builtin Cast: 3.1744e+04
info: Bitcast: inf
info: Pointer Cast: inf
```

**Comment by andrewCodeDev** [comment]
Thanks - this probably should be added to the official docs at some point. I can see a lot of accidental lossy conversions happening due to this:
```
@floatFromInt(int: anytype) anytype

Converts an integer to the closest floating point representation. The return type is the inferred result type. To convert the other way, use [@intFromFloat](https://ziglang.org/documentation/master/#intFromFloat). This operation is legal for all values of all integer types.
```
Probably just add "To preserve bit representation, use @bitCast"
