### ISSUE TITLE
windows build with zig-bootstrap generated binaries fails

### ISSUE THREAD

**Issue by neeraj9** [ziglang/zig#19290]
### Zig Version

0.11.0-dev.995+7350f0d9b

### Steps to Reproduce and Observed Behavior

```shell
git clone https://github.com/ziglang/zig-bootstrap
cd zig-bootstrap
build.bat x86_64-windows-gnu baseline
cd ..
git clone https://github.com/ziglang/zig
cd zig
..\zig-bootstrap\out-win\zig-x86_64-windows-gnu-baseline\zig.exe build -p stage3 --search-prefix ..\zig-bootstrap\out-win\x86_64-windows-gnu-baseline --zig-lib-dir lib -Dstatic-llvm
```

### Expected Behavior

Zig should build from binaries generated from zig-bootstrap, but I get the following error:

```
error: sub-compilation of zig_libc failed
    C:\Users\neera\AppData\Local\zig\b\731734966a7ad78f2b905fc1c41a5214\builtin.zig:9:44: note: enum 'builtin.LinkMode' has no member named 'Static'
pub const link_mode = std.builtin.LinkMode.Static;
                                           ^~~~~~
    I:\Work\git\ziglang\zig\lib\std\builtin.zig:502:22: note: enum declared here
pub const LinkMode = enum {
                     ^~~~
referenced by:
    enum 'builtin.LinkMode' has no member named 'Static': n.zig:1:2
    pilation of zig_libc failed: n.zig:1:2
error: sub-compilation of compiler_rt failed
    C:\Users\neera\AppData\Local\zig\b\731734966a7ad78f2b905fc1c41a5214\builtin.zig:9:44: note: enum 'builtin.LinkMode' has no member named 'Static'
pub const link_mode = std.builtin.LinkMode.Static;
                                           ^~~~~~
    I:\Work\git\ziglang\zig\lib\std\builtin.zig:502:22: note: enum declared here
pub const LinkMode = enum {
                     ^~~~
referenced by:
    enum 'builtin.LinkMode' has no member named 'Static': n.zig:1:2
    \Users\neera\AppData\Local\zig\b\731734966a7ad78f2b905fc1c41a5214\builtin.zig: n.zig:1:2
I:\Work\git\ziglang\zig\lib\std\dwarf.zig:970:106: error: value with comptime-only type 'comptime_int' depends on runtime control flow
            const base_address = compile_unit.die.getAttrAddr(di, AT.low_pc, compile_unit.*) catch |err| switch (err) {
                                                                                                         ^~~~~~
I:\Work\git\ziglang\zig\lib\std\dwarf.zig:970:94: note: runtime control flow here
            const base_address = compile_unit.die.getAttrAddr(di, AT.low_pc, compile_unit.*) catch |err| switch (err) {
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
referenced by:
    scanAllFunctions: I:\Work\git\ziglang\zig\lib\std\dwarf.zig:814:58
    openDwarfDebugInfo: I:\Work\git\ziglang\zig\lib\std\dwarf.zig:2184:11
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

**Comment by nektro** [comment]
this is neither of the options from https://github.com/ziglang/zig/wiki/Building-Zig-on-Windows

if using a zig from the website also fails then it will only be because master changed recently and the tarballs haven't finished updating yet. upstream change was made here https://github.com/ziglang/zig/commit/4f782d1e853accbe1c4bfab2617c3813d4b1e59f

**Comment by neeraj9** [comment]
I built the zig via zig-bootstrap. If the zig built with that cannot compile latest zig in this git repo then what will? Additionally, any pointers to debug the error will be of great help.
Isn't this command supposed to work irrespective of the platform?

```console
..\zig-bootstrap\out-win\zig-x86_64-windows-gnu-baseline\zig.exe build -p stage3 --search-prefix ..\zig-bootstrap\out-win\x86_64-windows-gnu-baseline --zig-lib-dir lib -Dstatic-llvm
```

**Comment by Vexu** [comment]
The first two errors are caused by #15803 but even if you fixed those you'd run into other issues since zig-bootstrap is ~1k commits behind master branch Zig. You need to either update the sources in zig-bootstrap to be able to build master branch Zig or just build Zig using this repo.

**Comment by neeraj9** [comment]
It is interesting that I tried to take the zig devkit [zig+llvm+lld+clang-x86_64-windows-gnu-0.12.0-dev.2073+402fe565a.zip](https://ziglang.org/deps/zig+llvm+lld+clang-x86_64-windows-gnu-0.12.0-dev.2073+402fe565a.zip) as per [1](https://github.com/ziglang/zig/wiki/Building-Zig-on-Windows) and [2](https://github.com/ziglang/zig/blob/master/ci/x86_64-windows-debug.ps1#L1-L4) and still the build failed.

The combination which worked was to use `zig.exe` from https://ziglang.org/builds/zig-windows-x86_64-0.12.0-dev.3304+bc5b09469.zip, while the llvm libraries from  [zig+llvm+lld+clang-x86_64-windows-gnu-0.12.0-dev.2073+402fe565a.zip](https://ziglang.org/deps/zig+llvm+lld+clang-x86_64-windows-gnu-0.12.0-dev.2073+402fe565a.zip) and that successfully built zig version `0.12.0-dev.3291+17bad9f88`.

It appears zig in this repo is very specific to zig and llvm library versions and break's if the versions dont match up correctly.

```console
D:\zig\zig.exe build -p stage3 --search-prefix D:\zig\devkit --zig-lib-dir I:\Work\git\ziglang\zig\lib -Dstatic-llvm -Duse-zig-libcxx -Dtarget=x86_64-windows-gnu
```
