### ISSUE TITLE
Tier 1 support for MacOS i386

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1930]
Here's the tracking issue.

I'm not even sure if this is wanted. Can you even get 32 bit MacOS hardware anymore?

**Comment by fibric** [comment]
32-bit apps are still supported, but Apple teaches us to find 64-bit alternatives.
https://support.apple.com/en-us/HT208436

**Comment by andrewrk** [comment]
Thanks for finding this. Quoting the linked article:

> About the transition to 64-bit technology and how it affects 32-bit apps.

> State-of-the-art technology is what makes a Mac a Mac. All modern Macs include powerful 64-bit processors, and macOS runs advanced 64-bit apps, which can access dramatically more memory and enable faster system performance. The technologies that define today's Mac experience—such as Metal graphics acceleration—work only with 64-bit apps. To ensure that the apps you purchase are as advanced as the Mac you run them on, all future Mac software will eventually be required to be 64-bit.

> Apple began the transition to 64-bit hardware and software technology for Mac over a decade ago, and is working with developers to transition their apps to 64-bit. At our Worldwide Developers Conference in 2018, Apple informed developers that macOS Mojave is the last version of macOS to run 32-bit apps.

> While developers optimize their apps for 64-bit compatibility, Apple is notifying customers when they are using an app based on 32-bit technology. This is done via a one-time alert that appears when you launch a 32-bit app. In macOS Mojave, this alert appears once every 30 days when launching the app.

Based on this, I am officially declaring **Zig will never support the MacOS i386 target.**
