### ISSUE TITLE
rsqrt as builtin

### ISSUE THREAD

**Issue by expikr** [ziglang/zig#19302]
for the hardware instructions where available

**Comment by nektro** [comment]
do you have docs on what this function is?

**Comment by nektro** [comment]
`1 / @sqrt(x)` should compile to what you seek

**Comment by nektro** [comment]
at a glance it looks like it should be using RSQRTPS instead

**Comment by castholm** [comment]
Somewhat related: #767
At a quick glance there doesn't appear to be an LLVM intrinsic for `rsqrt`, but I don't think that's necessarily an argument against adding `@rsqrt` and I can such a builtin being useful in certain cases.

> `1 / @sqrt(x)` should compile to what you seek

Unless `@setFloatMode(.optimized)` or equivalent compiler flags are in effect I would hope that `1 / @sqrt(x)` is never compiled to reciprocal square root, for the same reasons it is undesired for `a * b + c` to silently compile to fused multiply-adds, divisions to reciprocals, etc. that change the semantics of the expression.
