### ISSUE TITLE
Proposal: Substitute Char Literals With `utf8Decode`

### ISSUE THREAD

**Issue by exxjob** [ziglang/zig#19316]
*This proposal should be considered in unison with issues in #19283, this was extracted from comment: https://github.com/ziglang/zig/issues/19283#issuecomment-1999627620*

I peeked in the source and it seems char literals are an unnecessary pain point, I don't think they're particularly common outside handrolling scanners. This proposal is to substitute char literals with `utf8Decode` returning `u21`. The rationale is as follows:

Unlike `c_char`, Zig char literals do not promote C compatibility; they compel more escape sequences, and convolute parsing. More appropriate for the same function is `utf8Decode` from stdlib. Hence, the proposal benefits with:
- Improved code quality in affected source.
- Fewer ways of doing the same thing in Zig.
- Apostrophes don't need escaping in string literals.

**Comment by nektro** [comment]
interacting with byte slices is much more performant than always deferring to a u21 stream. in https://github.com/nektro/zig-xml/blob/master/Parser.zig I do this and read a u8 sequence for the vast majority of a document and promote to checking for/returning a u21 only when the grammar allows

**Comment by exxjob** [comment]
@nektro you will get byte slices for using string literals. The suggested substitution stays true to source:
https://github.com/ziglang/zig/blob/5cd7fef17faa2a40c8da23f0ef2485df0af39ed4/lib/std/zig/string_literal.zig#L11-L14
The suggestion is make a feature creep into an stdlib function.

**Comment by nektro** [comment]
my misunderstanding.

**Comment by exxjob** [comment]
```zig
const print = @import("std").debug.print;

pub inline fn u(bytes: []const u8) u21 {
    return comptime (@import("std").unicode.utf8Decode(bytes)) catch unreachable;
}

pub fn main() void {
    const char = "g";
    const codepoint = u(char);
    print("utf-8 codepoint value for char '{s}' in decimal is {}", .{char, codepoint});
    switch(codepoint){
        u("a")...u("z") => print("\nand it's a lowercase letter", .{}),
        u("A")...u("Z") => print("\nand it's an uppercase letter", .{}),
        u("0")...u("9") => print("\nand it's a decimal digit", .{}),
        u("'") => print("\nand it's an apostrophe", .{}),
        else => {}
    }
}

// utf-8 codepoint value for char 'g' in decimal is 103
// and it's a lowercase letter
```
Perhaps a naive take and a far stretch, but it does lend itself to non-ambiguity and format independence. Again, char literals are mostly facilitated in handrolling plain text scanners. I think escape sequences in char literals ought to be cleaned up anyhow.
