### ISSUE TITLE
Printing functions incorrectly round float values with precision 0

### ISSUE THREAD

**Issue by purrie** [ziglang/zig#19314]
### Zig Version

0.12.0-dev.3303+0103c4bf7

### Steps to Reproduce and Observed Behavior

When printing floats as decimals, the whole number parts get rounded.
```zig
    for (0..5) |down| {
        const f : f32 = @floatFromInt(down);
        std.log.info("{d} == {d:.0} == {d}", .{f, f, down});
    }
    for (5..10) |up| {
        const f : f32 = @floatFromInt(up);
        std.log.info("{d} != {d:.0} != {d}", .{f, f, up});
    }
```
This code produces the following output:
```console
info: 0 == 0 == 0
info: 1 == 1 == 1
info: 2 == 2 == 2
info: 3 == 3 == 3
info: 4 == 4 == 4
info: 5 != 10 != 5
info: 6 != 10 != 6
info: 7 != 10 != 7
info: 8 != 10 != 8
info: 9 != 10 != 9
```
If the float value has its decimal part then the output seems to be correct but whole number floats get rounded up.

### Expected Behavior

I would have expected the output to be consistent regardless of the formatted float and precision.

**Comment by tiehuis** [comment]
This will be an issue with the new float printing I added recently. Will take a look in the next few days if noone else gets to this.
