### ISSUE TITLE
Can not `@import` dependencies in build.zig scripts

### ISSUE THREAD

**Issue by urso** [ziglang/zig#19357]
### Zig Version

0.12.0-dev.3381+7057bffc1

### Steps to Reproduce and Observed Behavior

Unexpected error importing a package dependencie in build scripts.

`build.zig.zon`:

```
.{
    .name = "my_extension",
    .version = "0.1.0",
    .paths = .{
        "src",
    },
    .dependencies = .{
        .pgzx = .{
            .url = "https://github.com/xataio/pgzx/archive/main.tar.gz",
            .hash = "1220af8396f144d87259e959493e54d27f52006bab3905a349d2bc96130b437faaed",
        },
    },
}
```

`build.zig`:

```
const std = @import("std");
const pgzx = @import("pgzx");

pub fn build(b: *std.Build) void {
    _ = b;
    _ = pgzx;
}
```

Error message:

```
$ zig/build/stage3/bin/zig build
xxxx/build.zig:2:22: error: no module named 'pgzx' available within module root.@build
const pgzx = @import("pgzx");
```

### Expected Behavior

According to #14279 it seems that it shall be possible to import package dependencies in build scripts. This allows projects to share some common build utilities with downstream projects. We used that mechanism, but it seems to have been regressed recently.

Note: It is still possible to import a package that is referenced by path:

```
    .dependencies = .{
        .pgzx = .{
            .path = "./../pgzx",
        },
    },
```

**Comment by xdBronch** [comment]
the dependency [only has `src`](<https://github.com/xataio/pgzx/blob/main/build.zig.zon>) in the paths field which means everything else is discarded when it's fetched and importing a dependency requires it to have a build.zig

**Comment by urso** [comment]
Adding `build.zig` to `paths` did solve the issue.

I swear it used to work without before :)

Thank you!

**Comment by linusg** [comment]
Also started hitting this. How does one fix this if the dependency doesn't have a `build.zig.zon`?
