### ISSUE TITLE
`var x: ?SomeError = null` crashes the compiler

### ISSUE THREAD

**Issue by dbandstra** [ziglang/zig#1937]
I'm on a Mac, rebuilt Zig for the first time in a few months, now trying to upgrade my projects. Here is a minimal case of a problem I ran into.

```
const std = @import("std");

const SomeError = error{Hello};

test "" {
  var failed: ?SomeError = null;
}
```

The result is random. I've seen four different behaviours when running this.

This is the most common result:

```
Segmentation fault: 11
```

Sometimes I get this:

```
invalid type ref
!482 = !DILocalVariable(name: "failed", scope: !483, file: !480, line: 6, type: void <badref>)
void <badref>
LLVM ERROR: Broken module found, compilation aborted!
```

Sometimes zig simply hangs at 100% CPU usage (but steady memory usage).

The odd time, it actually runs fine and the test passes.

**Comment by emekoi** [comment]
possibly related: #1814.

**Comment by andrewrk** [comment]
I took the time to explain what happened in the commit message, which I will paste here for convenience:

    There's an unfortunate footgun in the current design of error sets.
    The debug info type for every error set is the same as the debug info
    type of the global error set, which is essentially an enum forward
    declaration. The problem is that when we "replace" the forward
    declaration with the final value, once we know all the possible errors,
    we have to update the pointers of every error set.
    
    So the footgun is that if you ever copy the debug info type of the
    global error set, you have to add the address of the pointer to a list
    of pointers that need to be updated once we "replace" the forward
    declaration. I activated the footgun when I introduced the optimization
    that `?anyerror` types are the same size as `anyerror` types (using 0 as
    the null value), because I introduced a pointer copy of the global error
    set debug info type, but forgot to add it to the list.
    
    I'm sure that there is a better way to code this, which does not have
    the footgun, but this commit contains only a fix, not a reworking of the
    logic.

**Comment by andrewrk** [comment]
Oh I remember how I want to fix this. It's part of a larger reworking of compiler internals that I intend to do at some point.

Right now, whenever we create a type in the Zig compiler, we go ahead and create the LLVM type as well as the debug info for the type. However in many cases this information is not needed, or as seen above, we actually don't have enough information to complete it anyway, and have to do some work later.

So what I plan to do at some point, is make all the LLVM type generation and debug info generation created lazily, in the codegen phase.
