### ISSUE TITLE
wrong type inference

### ISSUE THREAD

**Issue by dimdin** [ziglang/zig#19379]
### Zig Version

0.12.0-dev.3381+7057bffc1

### Steps to Reproduce and Observed Behavior

To reproduce run:
```zig
pub fn main() !void {
    const olength: u32 = 1;
    const precision: ?usize = null;
    const exponent: i32 = -1; 
    const req_bytes = 2 + @max(@abs(exponent) + olength, precision orelse 0);
    _ = req_bytes;
}
```

```
❯ zig run test.zig
test.zig:5:25: error: overflow of integer type 'u2' with value '4'
    const req_bytes = 2 + @max(@abs(exponent) + olength, precision orelse 0);
                      ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is an actual library line: 
https://github.com/ziglang/zig/blob/e831313b10c8c0f6c1984bb1704f3ca90105c416/lib/std/fmt/ryu128.zig#L275

It happens only in comptime

### Expected Behavior

result type must be `u32` or `usize` instead of `u2`

**Comment by xdBronch** [comment]
since all the arguments to `@max` are known at comptime it returns the smallest fitting integer type that can represent its value, that being a u2 in this case

**Comment by dimdin** [comment]
It behaves differently in comptime and in runtime.
Code that is perfect in runtime cannot be used in comptime.
I came to this while trying to format a float at comptime, and zig float format currently is broken.

**Comment by xdBronch** [comment]
i understand the problem statement. i believe the fix here is to provide an intermediate type coercion in the line that errors e.g. `2 + @as(u32, @max(@abs(f.exponent) + olength, precision orelse 0))`

**Comment by dimdin** [comment]
I agree. The line came from this merge: https://github.com/ziglang/zig/pull/19229
