### ISSUE TITLE
fmt shouldn't touch up hex escape sequences in zon and extern identifiers (`.@"\x0a"` => `.@"\n"`)

### ISSUE THREAD

**Issue by exxjob** [ziglang/zig#19381]
Input:
```js
.{
                      .@"\x01" = .{""}, .@"\x02" = .{""}, .@"\x03" = .{""},
    .@"\x04" = .{""}, .@"\x05" = .{""}, .@"\x06" = .{""}, .@"\x07" = .{""},
    .@"\x08" = .{""}, .@"\x09" = .{""}, .@"\x0A" = .{""}, .@"\x0B" = .{""},
}
```

Currently fmt outputs:
```js
.{
    .@"\x01" = .{""},
    .@"\x02" = .{""},
    .@"\x03" = .{""},
    .@"\x04" = .{""},
    .@"\x05" = .{""},
    .@"\x06" = .{""},
    .@"\x07" = .{""},
    .@"\x08" = .{""},
    .@"\t" = .{""},
    .@"\n" = .{""},
    .@"\x0b" = .{""},
}
```

Instead of:
```js
.{
    .@"\x01" = .{""},
    .@"\x02" = .{""},
    .@"\x03" = .{""},
    .@"\x04" = .{""},
    .@"\x05" = .{""},
    .@"\x06" = .{""},
    .@"\x07" = .{""},
    .@"\x08" = .{""},
    .@"\x09" = .{""},
    .@"\x0a" = .{""},
    .@"\x0b" = .{""},
}
```
#### Edit:
Most relevant for ZON and `extern`. Should it only apply to those? What I'm suggesting is fmt shouldn't perform *this* canonicalization on interchangable bytes representations where they're *known* to exchange *out* of Zig's realm.

**Comment by castholm** [comment]
Is there a strong motivation for this beyond a desire to align source code? Keep in mind that you can disable the auto-canonicalization with `// zig fmt: off`.
The original motivation for canonicalizing identifiers was greppability; see #166 and its linked pull request. ASCII bytes in identifiers currently have only one canonical representation each.

**Comment by exxjob** [comment]
@castholm The motivation as in my other issues is foremostly object notation. The desire is 8-bit cleanness, in situations where you're reaching outside of a vacuum. I don't think it serves anything to impose arbitrary canonicalization (or forbidding sequences for that matter) at the *data exchange layer*. Andrew's words https://github.com/ziglang/zig/issues/14534:
> Even JSON has the ability to represent null bytes in map keys. It would be a crime to introduce a new data exchange format and have it be worse than JSON at representing a mere map data structure.

**Comment by silversquirl** [comment]
Not really sure how Andrew's comment there is relevant here. Canonicalizing helps with searchability, as @castholm says, and if you really want to disable it you can turn off zig fmt for those lines

**Comment by exxjob** [comment]
Actually canonicalizing isn't a measure that helps with searchability, most certainly not in the example I gave in this issue @silversquirl. Andrew knows a crime when he sees one.

**Comment by silversquirl** [comment]
canonicalizing helps with searchability in the common case because it means you can search for `@"\t"` and find all the fields that are named a single tab character. Your usecase (non-textual field names) is uncommon, and not one that I think Zig should design around.

**Comment by exxjob** [comment]
@silversquirl It's **not** a non-textual use case. It's one that's agnostic to your preferred canonicalization, centered around ASCII, and is not about Zig as a whole, but specifically object notation - a mere map data structure. There also isn't a profound complexity to adding an or condition to your grep.

**Comment by exxjob** [comment]
@mnemnion can you explain why `\x` hex escseq, as opposed to `\u`, ***should*** be canonicalized the way it currently does, especially in scenarios with extern and ZON? Other than "greppability" which I think is as much an arguement for as it is against.

**Comment by mnemnion** [comment]
It is canonicalized. 

```zig
// before zig fmt
const @"\u{41}\u{42}\u{43}" = 5;
// after zig fmt
const ABC = 5;
```
