### ISSUE TITLE
Compile error when using EnumSet with non-exhaustive enum

### ISSUE THREAD

**Issue by sjb3d** [ziglang/zig#19418]
### Zig Version

0.12.0-dev.3433+640acf862

### Steps to Reproduce and Observed Behavior

`EnumIndexer` supports non-exhaustive enums, so I was expecting that `EnumSet` (and `EnumMap`) would support this too.

This can be useful to implement bitfields with sparse usage, which are common in external libraries.  For example, using an enum backed by `u5`, the `EnumSet` becomes a 32-bit bitfield.

The compile error can be reproduced using this:

```zig
const std = @import("std");

const BitIndices = enum(u5) {
    a = 0,
    b = 1,
    c = 4,
    _,
};

const BitField = std.enums.EnumSet(BitIndices);

export fn example() void {
    var flags = BitField.init(.{ .a = true, .b = true });

    flags.insert(.c);
    flags.remove(.a);

    std.debug.assert(flags.contains(.b));
}
```

Which produces an error from `EnumSet.init` as follows:

```
/opt/compiler-explorer/zig-master/lib/std/enums.zig:268:29: error: no field with value '@enumFromInt(2)' in enum 'BitIndices'
```

### Expected Behavior

Successful compile and test.

**Comment by castholm** [comment]
The failing test is the [`std_enums_big_enums` standalone test](https://github.com/ziglang/zig/blob/091aa54a3ed74b8a19f44ffb20e29c5f81de0c58/test/standalone/std_enums_big_enums.zig) which verifies that enums with thousands of fields can participate in `std.enums` data structures without requiring overriding the comptime branch eval quota. Now that there is an additional call to `Indexer.indexOf` at comptime there will be more backward branches, so you will need to comb through the `@setEvalBranchQuota` expressions in `std.enums` and increment them to the new required bare minimum as appropriate.

As a starting point I would suggest iteratively running `zig build-obj test/standalone/std_enums_big_enums.zig -fno-emit-bin` and modifying the `@setevalBranchQuota` expressions until you find the new minimum quotas.
