### ISSUE TITLE
error: Unexpected on zig build MacOS 14.4

### ISSUE THREAD

**Issue by JoshuaKeegan3** [ziglang/zig#19419]
### Zig Version

0.11.0 (homebrew)

### Steps to Reproduce and Observed Behavior

I updated my Mac from version 13.? to 14.4 and I can no longer run zig build.  I get error: Unexpected. I am unsure if the update is related. I uninstalled zig and reinstalled it using the following steps.

- brew uninstall zig
- brew install zig
- zig init-exe
- zig build

<img width="276" alt="image" src="https://github.com/ziglang/zig/assets/37237625/391fc3a7-33b1-4c38-adff-a866ecb57590">

As observed above zig run works. It doesn't create a executable though (idk if it should)

### Expected Behavior

I expect it to build and create an executable.

**Comment by JoshuaKeegan3** [comment]
Related?: https://github.com/Homebrew/homebrew-core/issues/134298

Note I didn't use -HEAD

**Comment by squeek502** [comment]
Likely a duplicate of https://github.com/ziglang/zig/issues/17342

You could try the workarounds mentioned in the later comments in that thread.

**Comment by JoshuaKeegan3** [comment]
This was a duplicate. Thanks for your help
