### ISSUE TITLE
Attempting to use non-existant 'ucontext_t' symbol on mipsel-linux-gnueabihf when linking libc, and likely other targets

### ISSUE THREAD

**Issue by joshua-software-dev** [ziglang/zig#19433]
### Zig Version

0.12.0-dev.3429+13a9d94a8

### Steps to Reproduce and Observed Behavior

```
mkdir temp
cd temp
zig init
// add exe.linkLibC(); to build.zig
zig build -Dtarget=mipsel-linux-gnueabihf
```

When compiling any zig executable for `mipsel-linux-gnueabihf` while linking libc/libc++, compilation will stop with the following error:
`error: root struct of file 'os.linux.mips' has no member named 'ucontext_t'`

A workaround to this error is to set `exe.root_module.strip = true;` as per:
https://github.com/ziglang/zig/blob/ef31d8f48fa1b7ff5bd4cd57e812fd9c91fd1bd9/lib/std/debug.zig#L180-L183

I have traced the problem back to this statement in `lib/std/debug.zig`:
https://github.com/ziglang/zig/blob/ef31d8f48fa1b7ff5bd4cd57e812fd9c91fd1bd9/lib/std/debug.zig#L231-L238

It seems like the intent was for this statement to be false on systems that don't have the symbol such as mips, however following the chain of where this is defined leads to:
https://github.com/ziglang/zig/blob/ef31d8f48fa1b7ff5bd4cd57e812fd9c91fd1bd9/lib/std/c.zig#L1898-L1905

Where this is defined unconditionally for non-android platforms, making the `@hasDecl` here redundant (More evidence for https://github.com/ziglang/zig/issues/19352). This was the case even before the std.os -> std.posix rework, it did not change or surface this problem. Compiling the `zig init` template set to link libc and/or libc++ on `0.12.0-dev.2817+7461309b7`, an old build prior to the rework I happened to still have on my machine, produces the same error.
https://github.com/ziglang/zig/blob/9b454a8ce241cf02e2869942c67a6d7871a52fb3/lib/std/debug.zig#L231-L238
https://github.com/ziglang/zig/blob/9b454a8ce241cf02e2869942c67a6d7871a52fb3/lib/std/os.zig#L62-L71
https://github.com/ziglang/zig/blob/9b454a8ce241cf02e2869942c67a6d7871a52fb3/lib/std/c.zig#L1905-L1912

### Expected Behavior

I believe the statement would probably look more like this if it was to match the intent before:
```zig
pub const have_getcontext = @hasDecl(std.posix, "ucontext_t") and
    native_os != .openbsd and
    (native_os != .linux or switch (builtin.cpu.arch) {
    .x86,
    .x86_64,
    => true,
    else => builtin.link_libc and !builtin.target.isMusl(),
});
```
However, this also does not work. Even though `std.posix.ucontext_t` points to a symbol that is only conditionally resolved, `@hasDecl` is `true` here. This feels like a weird behavior for `@hasDecl` to have, but given the above issue recommending removing usage of `@hasDecl` altogether, some other solution is likely prudent here.

**Comment by alexrp** [comment]
This works now.
