### ISSUE TITLE
Invalid Vector Length from LLVM when splating to an zero length vector type through wrapper function

### ISSUE THREAD

**Issue by Trevor-Strong** [ziglang/zig#19455]
### Zig Version

0.12.0-dev.3158+1e67f5021

### Steps to Reproduce and Observed Behavior

Running `zig test` on 

```zig
const std = @import("std");


fn splat(comptime n: comptime_int, value: anytype) @Vector(n, @TypeOf(value)) {
    return @splat(value);
}

test {
    _ = splat(0, @as(u8, 0));
}
```

Produces 

```shell
LLVM Emit Object... error: Invalid vector length (Producer: 'zig 0.12.0' Reader: 'LLVM 17.0.6')
```

### Expected Behavior

Tests should pass.

It's important to note that this happens *only* when splat is wrapped by a function call.
Inlining the function to

```zig
test {
    const value: u8 = 0;
    _ = @as(@Vector(0, u8), @splat(value))
}
```

makes the problem disappear. The test compiles fine and succeeds as expected.

**Comment by travisstaloch** [comment]
i noticed that the llvm error goes away if you `inline fn splat(...`

**Comment by Vexu** [comment]
`zirSplat` generates runtime instructions even if the `dest_ty` doesn't have runtime bits.
