### ISSUE TITLE
Comptime dereference bugs tracking issue

### ISSUE THREAD

**Issue by mlugg** [ziglang/zig#19452]
The Sema logic for accessing pointers at comptime is incredibly flawed and riddled with bugs. Recent changes in the frontend have exposed more of these bugs, such as those encountered in #19092.

I am actively working on a rewrite of this logic which will hopefully fix all of these issues, but in the meantime, workarounds are necessary.

This issue serves to track these bugs. Feel free to share workarounds here, and please link any PRs/commits - in the Zig project or otherwise - which work around the issue. When my rewrite is complete, I will test it on everything linked here to ensure there are no failing edge cases.

Resolution of this issue should likely block 0.12.0.

**Comment by paperdave** [comment]
Here is a simplified version of something I hit while trying to get bun to compile on the latest version of zig.

```zig
pub const hi = brk: {
    var buf: [4][]const u8 = undefined;

    for (0..2) |i| {
        buf[i] = "hello";
    }

    // error: comptime dereference requires '[2][]const u8' to have a well-defined layout, but it does not.
    const names = buf[0..2].*;
    break :brk names;
};

test {
    _ = &hi;
}
```

I think I can get a workaround by generating this code during zig build, like inlined `&.{ "string 1", "string 2", ... }`.

actually, while typing this, someone told me that the workaround is to ensure the definition `buf` has the correct size. so if line 2 is changed to include a `2`, the code compiles.

Besides this one, I've been pretty happy about the recent changes, as they've caught a lot of const/non-const issues across the codebase.

**Comment by Inve1951** [comment]
regarding above post: i've hit this in my build.zig where you can't move the logic to the build system. buffer size needs to be computed in my case. it was previously set to the known upper bound.

**Comment by akhildevelops** [comment]
I too faced similar issue while building enum from type information that slices 2 enum fields from an array:
```zig
const std = @import("std");
const Type = std.builtin.Type;
pub fn main() !void {
    const enum_fields: [3]Type.EnumField = .{ .{ .name = "field1", .value = 1 }, .{ .name = "field2", .value = 2 }, .{ .name = "field3", .value = 3 } };
    const custom_enum = @Type(Type{ .Enum = .{ .tag_type = u8, .is_exhaustive = true, .decls = &.{}, .fields = enum_fields[0..2] } });
    std.debug.print("{}", .{custom_enum.field1});
}
```

**Comment by mlugg** [comment]
Thanks for the examples, everyone. I'm getting my branch into a working state now, and will be testing the given examples shortly.

**Comment by clickingbuttons** [comment]
```zig
const std = @import("std");

const HashTag = enum {
    sha1,
    pub const map = std.ComptimeStringMap(@This(), .{
        .{ encode("1.3.14.3.2.26"), .sha1 },
    });
};

pub fn encode(comptime oid: []const u8) []const u8 {
    var res: [256]u8 = undefined;
    res[0] = @intCast(oid.len);
    @memcpy(res[1..][0..oid.len], oid);
    return res[0..oid.len + 1];
}

pub fn main() !void {
    std.debug.print("{?}\n", .{  HashTag.map.get("1.3.14.3.2.26asdf") });
}
```

Error in #19666, which I posted before finding this issue.
