### ISSUE TITLE
Improper Pluralization of stdout in `test_runner.zig`

### ISSUE THREAD

**Issue by camolechowski** [ziglang/zig#19464]
### Zig Version

0.11

### Steps to Reproduce and Observed Behavior

Super, super minor issue. More of a logging problem than a bug and its a matter of preference (my OCD drove me to opening this issue)

https://github.com/ziglang/zig/blob/c808e546a766192c4a9bd45190d4bcfae61d6f3b/lib/compiler/test_runner.zig#L179-L192

"All 1 tests passed." | "1 errors were logged." | "1 tests leaked"

These stdout messages are pluralized, even when the count stored is 1. In English, this would be grammatically incorrect.

### Expected Behavior

Expected Behavior:
"1 test was passed." | "1 error was logged" | "1 test leaked"

A couple suggested solutions to this very minor issue:

The slightly less grammatically correct but simpler solution would be replacing the highlighted lines in the permalink with the following:
```zig
if (ok_count == test_fn_list.len) {
    std.debug.print("All {d} test{} passed.\n", .{ok_count, ok_count == 1 ? "" : "s"});
 } else {
    std.debug.print("{d} passed; {d} skipped; {d} failed.\n", .{ok_count, skip_count, fail_count});
}
if (log_err_count != 0) {
    std.debug.print("{d} error{} logged.\n", .{log_err_count, log_err_count == 1 ? "" : "s"});
}
if (leaks != 0) {
    std.debug.print("{d} test{} leaked memory.\n", .{leaks, leaks == 1 ? "" : "s"});
}

if (leaks != 0 or log_err_count != 0 or fail_count != 0) {
    std.process.exit(1);
}
```

Or the slightly more complex and grammatically correct change:
```zig
if (ok_count == test_fn_list.len) {
    if (ok_count == 1) {
        std.debug.print("1 test passed.\n", .{});
    } else {
        std.debug.print("All {d} tests passed.\n", .{ok_count});
    }
} else {
    std.debug.print("{d} passed; {d} skipped; {d} failed.\n", .{ok_count, skip_count, fail_count});
}
if (log_err_count != 0) {
    std.debug.print("{d} error{} logged.\n", .{log_err_count, log_err_count == 1 ? "" : "s"});
}
if (leaks != 0) {
    std.debug.print("{d} test{} leaked memory.\n", .{leaks, leaks == 1 ? "" : "s"});
}
```

If either of these changes make sense (I assume this is very performance-sensitive code so I can imagine why you'd want to avoid adding the additional logic), I can open a PR with one of these changes. If this is not a change worth making, please close this and I'll be sure to take any constructive criticism or feedback before opening new issues.

**Comment by Vexu** [comment]
See https://github.com/ziglang/zig/issues/15049#issuecomment-1502087290, https://github.com/ziglang/zig/pull/18115#issuecomment-1891179949

If you want to improve it somehow change it to read `test(s)` in a PR.

**Comment by camolechowski** [comment]
Thanks @Vexu! I'll leave my subjectivity out of the repo :)
