### ISSUE TITLE
std.os.linux.sendfile incorrectly returns an unsigned type

### ISSUE THREAD

**Issue by dl-eric** [ziglang/zig#19481]
### Zig Version

0.12.0-dev.3439

### Steps to Reproduce and Observed Behavior

Linux's [sendfile](https://www.man7.org/linux/man-pages/man2/sendfile.2.html) function returns a signed value, with -1 indicating an error. Zig's std lib defines the return value as a `usize`. So when the syscall returns -1, Zig sees it as an underflowed `usize`. This is especially bad because if the function returns >= 0, documentation implies it completed successfully.

Note std.c.linux.sendfile64 returns the correct type `isize`.

Steps to reproduce:
- Call std.os.linux.sendfile
- Induce any error
- Observe the return value

### Expected Behavior

std.os.linux.sendfile to return signed values.

**Comment by nektro** [comment]
corroboration: https://git.musl-libc.org/cgit/musl/tree/src/linux/sendfile.c

**Comment by nektro** [comment]
this is typically handled at the higher level here https://github.com/ziglang/zig/blob/fb9673f/lib/std/posix.zig#L212-L225
