### ISSUE TITLE
Different Output Between Runs

### ISSUE THREAD

**Issue by ItalicIntegral** [ziglang/zig#19495]
### Zig Version

0.12.0-dev.3438+5c628312b

### Steps to Reproduce and Observed Behavior

I am getting inconsistent console output the first time I run a program vs the second time I run it. I'm fairly new so I'm not sure if i'm doing anything wrong. However, I'm not getting any error messages on either runs. I use Windows 10.

`
const std = @import("std");
const testing = std.testing;

pub fn response(s: []const u8) []const u8 {
    //std.debug.print("\n\n", .{});
    if (isSilence(s)) return "Fine. Be that way!";
    if (isShouted(s) and isQuestion(s)) return "Calm down, I know what I'm doing!";
    if (isShouted(s)) return "Whoa, chill out!";
    if (isQuestion(s)) return "Sure.";
    return "Whatever.";
}

fn isQuestion(s: []const u8) bool {
    if (s[s.len - 1] == '?') return true;
    return false;
}

fn isShouted(s: []const u8) bool {
    for (s) |char| {
        // std.debug.print("{c} {}\n", .{ char, char });
        if ((char >= 92) and (char <= 122)) return false; // a - z
        if ((char >= 48) and (char <= 57)) return false; // 0 - 9
    }
    return true;
}

fn isSilence(s: []const u8) bool {
    if (s.len == 0) return true;
    for (s) |char| {
        if (char != 32) return false;
    }
    return true;
}

pub fn main() void {
    const phrase = "How are you?";

    // I believe this is what's causing the issue.
    std.debug.print(
        "Me: {s}\n Bob: {s}",
        .{ phrase, response(phrase) },
    );
}
`

### Expected Behavior

I expect both runs to output the same.

![image](https://github.com/ziglang/zig/assets/108310925/e8b5c207-ec21-4833-a975-1b6fca07333c)

**Comment by ItalicIntegral** [comment]
If I remove the \n in the code it looks even worse.

![image](https://github.com/ziglang/zig/assets/108310925/3b31a2fd-8061-45cb-9f75-412c89e8d84e)

**Comment by llogick** [comment]
Something to do with stdout not being flushed?

try:
```zig
std.debug.print(
    "Me: {s}\n Bob: {s}\n",
    .{ phrase, response(phrase) },
);
```

**Comment by llogick** [comment]
It could be classified as "Relying on undefined behavior" :)

Searching for "is windows stderr buffered", I couldn't find an answer.

On linux stderr is considered unbuffered + apps get the theirs buffers flushed on exit if they link libc.

**Comment by xdBronch** [comment]
afaik all IO is unbuffered in zig unless explicitly made to be so, even if linking libc. i believe this is a problem with the progress reporting from `zig build run`. i cant reproduce this on my end but if you use `zig run` or build the program before separately running it it shouldnt happen
