### ISSUE TITLE
inline loop in a function called at comptime is checked against wrong eval branch quota

### ISSUE THREAD

**Issue by Hejsil** [ziglang/zig#1949]
```zig
comptime {
    @setEvalBranchQuota(1001);
    a();
}

fn a() void {
    inline for ([]void{{}} ** 1004) |_| {}
}
```

Notice the double 'evaluation exceeded X backwards branches' errors have different values
```
test.zig:7:12: error: evaluation exceeded 1001 backwards branches
    inline for ([]void{{}} ** 1004) |_| {}
           ^
test.zig:3:6: note: called from here
    a();
     ^
test.zig:1:10: note: called from here
comptime {
         ^
test.zig:7:12: error: evaluation exceeded 1000 backwards branches
    inline for ([]void{{}} ** 1004) |_| {}
```

**Comment by Hejsil** [comment]
Alright, I think i know what's going on.

The first error is thrown when `a` is evaluated in the `comptime` block. Here, the eval quota is `1001` because that was what it was set to in the comptime block.
The second error is thrown when `a` is being analyzed. Here, the eval quota is `1000`.

This seems like a design flaw. There is no way to extend the eval quota in `a`, as that would cause a compiler error.
```zig
comptime {
    @setEvalBranchQuota(1020);
    a();
}

fn a() void {
    @setEvalBranchQuota(1020);
    inline for ([]void{{}} ** 1004) |_| {}
}
```

```
test.zig:7:5: error: @setEvalBranchQuota must be called from the top of the comptime stack
    @setEvalBranchQuota(1020);
    ^
test.zig:3:6: note: called from here
    a();
     ^
test.zig:1:10: note: called from here
comptime {
```

**Comment by andrewrk** [comment]
I see what's happening here. I agree this is a design flaw. `a` is getting analyzed as a runtime function *and* as a comptime function call. The current design wants to have the branch quota for the comptime call to `a` happen in the comptime block, which is good, but then when we analyze `a`, that *is* the top of the comptime stack. So there's the design flaw.

**Comment by andrewrk** [comment]
This is related to another issue, which I'm not sure is filed on GitHub or not, which is that Zig really should not analyze a function and produce runtime code, if it is only called at comptime. It's actually pretty tricky to implement, and I believe might involve a comptime garbage collector to do correctly. However this would not solve this design flaw because you can still have a function called from both contexts and have this issue.

**Comment by Hejsil** [comment]
This is a blocking issue for me. Do we have any idea as to how to solve this? If not, then I'll just have a local branch that extends the default eval quota as a workaround.

**Comment by andrewrk** [comment]
I'll prioritize a fix, thanks for letting me know :+1:
