### ISSUE TITLE
zig build uninstall doesn't work

### ISSUE THREAD

**Issue by fprijate** [ziglang/zig#19491]
### Zig Version

platform: Win10
0.12.0-dev.3496+a2df84d0f

### Steps to Reproduce Observed Behavior

run: 
**zig build uninstall**

### Expected Behavior

To reverse result of **zig build install**  (delete zig-out directory)

**Comment by fprijate** [comment]
Platform: Win10

**Comment by Vexu** [comment]
Related #14943

**Comment by andrewrk** [comment]
duplicate of #14943
