### ISSUE TITLE
missing compile error: initializing global variable with the address of a threadlocal variable

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1950]
[LLVM IR verifier is missing detection for this](https://bugs.llvm.org/show_bug.cgi?id=40652) but it can be activated with this zig code:

```zig
threadlocal var x: i32 = 1234;
var y = &x;
```

The initial value of `y` will be bogus.

The equivalent C code gives a compile error in both clang and gcc:

```c
__thread int x = 1234;
int *y = &x;
```

```
<source>:2:10: error: initializer element is not a compile-time constant
int *y = &x;
         ^~
```

Related: 8e68d43ad373e643797209d59e6f10aa12b4c038

**Comment by nektro** [comment]
this no longer compile errors but fails at runtime

```zig
const assert = @import("std").debug.assert;

threadlocal var x: i32 = 1234;
var y = &x;

test {
    assert(y.* == 1234);
}
```

```
Test [1/1] test_0... Segmentation fault at address 0x0
./test.zig:7:11: 0x21268c in test_0 (test)
    assert(y.* == 1234);
          ^
```

**Comment by Vexu** [comment]
Works in self-hosted: https://github.com/ziglang/zig/blob/096d3efae5fcaa5640f4acb2f9be2d7f93f7fdb2/test/cases/compile_errors/address_of_threadlocal_not_comptime_known.zig
