### ISSUE TITLE
stop using the nonnull attribute on pointer parameters

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1952]
Currently Zig adds the LLVM `nonnull` attribute on pointer parameters, since they cannot be `null`. (Note that to LLVM, "null" means the address 0). However, this is incorrect. Zig pointers are actually allowed to have address 0. Here's a Real Actual Use Case: https://github.com/andrewrk/clashos/blob/e55b6a26a5c01566da14b5f1306822c8da6fc978/src/main.zig#L81

Here is LLVM's description of the `nonnull` attribute as well as a related one `dereferencable<n>`, from http://llvm.org/docs/LangRef.html#parameter-attributes:

> #### `nonnull`
>    This indicates that the parameter or return pointer is not null. This attribute may only be applied to pointer typed parameters. This is not checked or enforced by LLVM; if the parameter or return pointer is null, the behavior is undefined.
> #### `dereferenceable(<n>)`
>    This indicates that the parameter or return pointer is dereferenceable. This attribute may only be applied to pointer typed parameters. A pointer that is dereferenceable can be loaded from speculatively without a risk of trapping. The number of bytes known to be dereferenceable must be provided in parentheses. It is legal for the number of bytes to be less than the size of the pointee type. The nonnull attribute does not imply dereferenceability (consider a pointer to one element past the end of an array), however `dereferenceable(<n>)` does imply nonnull in addrspace(0) (which is the default address space).

These attributes apply to parameters as well as loads of pointers (See #1951). If we wanted to put either of these attributes on parameters and loads of pointers, it would mean that a pointer with address 0 invokes undefined behavior when passed to a function or loaded from memory

One option we have is to simply not use these attributes. It's unclear to me how beneficial they would be, given that if you have a non-optional zig pointer, there won't be any code *testing* for null anyway, so a `nonnull` attribute wouldn't contribute much.

Further, in Zig it's completely legal to pass `undefined` as a pointer parameter, which is certainly not `dereferencable<n>`. So it's unclear that we have something to gain from these attributes.

Here are 2 other possible proposals that this one does not explore:
 * #1953
 * A global build option which decides whether pointers are allowed to have the address of 0.

**Comment by andrewrk** [comment]
I have to say the more I think about it, the more I like the first bullet point alternative.

**Comment by kristate** [comment]
Sharing an [irc log from earlier](https://freenode.irclog.whitequark.org/zig/2019-02-13):
> [kristate] thinking aloud about #1953, but I always wondered why we allow undefined behavior in the first place (instead of using the error infrastructure). 
> [andrewrk] kristate, consider that the `+` operator can invoke undefined behavior 
> [kristate] andrewrk: right, for these things, at the moment, we would have to panic, but for function calls where we can catch such things, wouldn't it be best to use the error infrastructure? 
> [andrewrk] go on 
> [kristate] andrewrk: well, we already have the compiler infra in place for calling-out to panic, so I wonder why we couldn't simply return an error up the stack instead of generating code to panic? 
> [kristate] likewise, it might make sense to have a special builtin for `@intToPtr` when the int is zero, ala `@zeroPtr` and then make `@intToPtr` `try`-able, 
> [kristate] `try @intToPtr([*]const u8, 0)` would generate an `error.ZeroPointer` (for example) 
> [kristate] likewise, @intToPtr might be called with a runtime variable that is zero, or another address that might be out of bounds 
> [kristate] right now, if you use try in a function that does not handle errors, the compiler complains, and that gives visibility to the programmer 
> [andrewrk] that's an interesting idea 
> [kristate] think of it this way, I know that we want @intToPtr to map as close as possible to llvm intrinsics, but at the same time, you would check code anyway to see if it equals a nullptr or not. try `@intToPtr` provides a very zig-way to do it, without the tacky if statement 
> [andrewrk] what do you think should happen on implicit cast from C pointer to Zig pointer? e.g. `[*c]u8` to `*u8` 
> [kristate] well, I think that there should first be a built-in to do it. it shouldn't be something you can just cast-down to. second, coming from C-land, a nullptr is technically not defined as 0, but is implemented as zero, so I think that this should be impossible: it should only be down-castable to `?*u8`
> [kristate] andrewrk: this is debatable and something like bikeshedding, but perhaps ptr to zero should only be available as a `[*c]` ptr 
> [kristate] would we ever have to cast down to `*u8`? 
> [andrewrk] kristate, are you familiar with the motivation behind #1059? are you suggesting only that casting *to* zig pointers should not be implicit, or also *from*? 
> [andrewrk] also, I apologize - I am a bit past my bedtime and I'm sure that I am not speaking with as much clarity as normal 
> [kristate] andrewrk: please by all means, get some rest :-) about #1059, I am really glad that it is happening and fully supportive of it 
> [kristate] andrewrk: maybe we can talk later about this subject. I will post this log as a comment on #1952 
> [andrewrk] sounds good to me 
> [andrewrk] good night 
> [kristate] good night

**Comment by andrewrk** [comment]
Closing again, see https://github.com/ziglang/zig/issues/1953#issuecomment-463435397 and https://github.com/ziglang/zig/issues/1953#issuecomment-463438688
