### ISSUE TITLE
@cInclude linking error when using functions that contain a label

### ISSUE THREAD

**Issue by uniboi** [ziglang/zig#19526]
### Zig Version

0.12.0-dev.3438+5c628312b

### Steps to Reproduce and Observed Behavior

```c
// /path/to/test.c
void something(void) {
ret:
  return;
}
```

```zig
// main.zig
const c = @cImport({
  @cInclude("/path/to/test.c");
});

pub fn main() void {
  c.something(); // error: ld.lld: undefined symbol: something
}
```

### Expected Behavior

The code can be compiled and executed

**Comment by f-cozzocrea** [comment]
You're using a label in the function, and goto labels aren't supported by translate-c yet. The function is being demoted to extern, so you get a linker error.

**Comment by uniboi** [comment]
That's unfortunate, thanks for the quick reply though

**Comment by f-cozzocrea** [comment]
No problem. For now, as a workaround, you can compile and link the C code to get access to functions that can't currently be translated.
