### ISSUE TITLE
std.meta.eql :  missing inline in body the before array for loop?

### ISSUE THREAD

**Issue by fulverin** [ziglang/zig#19537]
### Zig Version

0.12.0-dev.3496+a2df84d0f

### Steps to Reproduce and Observed Behavior

Hi, just to be clear, I am out of my comfort zone here but I thought it would worth reporting what may be a bug but I am not sure.

zig version 
if I do :
```zig
fn AddOne(x: u8) u8 {
    return x + 1;
}
 try expect(std.meta.eql(comptime inputTypes(AddOne), .{u8}));
```
I have :
``` 
/lib/std/meta.zig:780:18: error: values of type '[1]type' must be comptime-known, but index value is runtime-known
            for (a, 0..) |e, i|
                 ^
: note: types are not available at runtime
referenced by:
    test.inputs types: node.zig:194:28
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```
but if copy paste what supposed to be the source code from documentation and add inline at the array level of the body:
from 
```zig
pub fn eql(a: anytype, b: @TypeOf(a)) bool {
...
        .Array => {
            if (a.len != b.len) return false;
            for (a, 0..) |e, i|
                if (!eql(e, b[i])) return false;
            return true;
        },
...
```
```zig
pub fn my_patched_meta_eql(a: anytype, b: @TypeOf(a)) bool {
...
        .Array => {
            if (a.len != b.len) return false;
            **inline** for (a, 0..) |e, i|
                if (!eql(e, b[i])) return false;
            return true;
        },
...
```
Then it works.
`try expect(my_patched_meta_eql(comptime inputTypes(AddOne), .{u8}));`
-> success !
but it seems to easy to be true.

### Expected Behavior

I expect the below code to pass the test :
```zig
fn AddOne(x: u8) u8 {
    return x + 1;
}
test "some test" {
    try expect(std.meta.eql(comptime inputTypes(AddOne), .{u8}));
}
```
------------ edit below is the inputTypes function
```zig
fn inputTypes(comptime a_function: anytype) @TypeOf(std.meta.ArgsTuple(@TypeOf(a_function))) {
    return std.meta.ArgsTuple(@TypeOf(a_function));
}```

**Comment by mjmlvp** [comment]
Could you provide complete (ready to run) code next time for others to reproduce?
I have been searching for some time for the function "inputTypes"... which library would that be?

I made  a minimal reproduction as follows:
`fn list () [1]type {
	return .{u8};
}
test "mytest" {
	try @import("std").testing.expect(@import("std").meta.eql(comptime list(), .{u8}));
}`

This one reproduces the error you mentioned.

When I hange it as follows, it compiles and tests succesfully:
`fn list () [1]type {
	return .{u8};
}
test "mytest" {
	try @import("std").testing.expect(comptime @import("std").meta.eql(list(), .{u8}));
}`

So you have to ask the compiler to actually run the eql function at comptime.

**Comment by mjmlvp** [comment]
Actually I would perhaps expect that when a function is called with only comptime-only arguments (like types or arrays of types), that then the function call itself would automatically be made comptime.

On the other hand it cannot be guaranteed that the function itself does not produce any runtime side-effects.
For that reason I think it is not possible for zig to do this automatically.

**Comment by fulverin** [comment]
My apologies, I have been sloppy; inputTypes is mostly same as std.meta.ArgsTuple:
```C
fn inputTypes(comptime a_function: anytype) @TypeOf(std.meta.ArgsTuple(@TypeOf(a_function))) {
    return std.meta.ArgsTuple(@TypeOf(a_function));
}
```

**Comment by andrewrk** [comment]
Please provide full steps to reproduce
