### ISSUE TITLE
Some CLI values are unconditionally parsed as hex

### ISSUE THREAD

**Issue by jedisct1** [ziglang/zig#19536]
### Zig Version

0.12.0-dev

### Steps to Reproduce and Observed Behavior

When using `zig cc`, linker options such as `--initial-memory` or `--max-memory` have their value unconditionally parsed as hexadecimal.

This is counterintuitive and confusing:

```sh
$ zig cc a.c --target=wasm32-freestanding -Wl,--max-memory=6553600
LLD Link... wasm-ld: error: maximum memory must be 65536-byte aligned
```

It's also at odds with `wasm-ld`, which parses these as decimal.

Affected options for WebAssembly are:

- `--initial-memory`
- `--shared-memory`
- `--max-memory`

And that doesn't seem to be intentional.

These other options are handled the same way, using `std.fmt.parseUnsigned(T, eatIntPrefix(next_arg, 16), 16)`, but maybe this is intentional:

- `-pagezero_size`
- `-headerpad`
- `-pagezero_size`

### Expected Behavior

Decode these values in decimal by default, even if other bases are supported.

**Comment by LucasMW** [comment]
Hello, does this only gets released in 0.14.0?
