### ISSUE TITLE
json: write objectField without escaping sequences

### ISSUE THREAD

**Issue by hwchen** [ziglang/zig#19552]
### Zig Version

0.12.0-dev.3518+d2be725e4

### Steps to Reproduce and Observed Behavior

I'd like to write an object field name `"one\""`.

When I receive the string, the double quote is already escaped. However, if I write this directly to `json.WriteStream` using `WriteStream.objectField()`, it will escape the escape sequence, resulting in `"one\\\""`.

### Expected Behavior

Instead, I'd like to be able to have `objectField` be able to write the exact string without further escaping. This way I don't need to un-escape the string first.

Using `WriteStream.print()` only does not work, as you need to indicate the start of the `objectField` and the next punctuation, as in the body of [`objectField`](https://ziglang.org/documentation/master/std/#std.json.stringify.WriteStream.objectField):

```zig
try self.objectFieldStart();
try encodeJsonString(key, self.options, self.stream);
self.next_punctuation = .colon;
```

Unfortunately, even if I wanted to just use this code snippet directly and replace `encodeJsonString` with print, `objectFieldStart` is not marked pub.

At the moment, my only option is to un-escape the object field name before feeding it to `objectField`. But I'd like either an option for `objectField` to not escape (whether as a parameter, or another method), or to have `objectFieldStart` marked pub so I can manually wrangle it.

If you'd like to see my usecase, I'm writing a port of [gron](https://github.com/tomnomnom/gron): https://github.com/hwchen/gorn . I'm transforming json to a more greppable format and back, and the field names are preserved as escaped since I don't need to process the field names.

@thejoshwolfe

**Comment by thejoshwolfe** [comment]
@hwchen do you have the surrounding `"` quotes in your string as well? It would save 2 calls to the underlying stream if those were required in the parameter to a new API that i'm sketching.

**Comment by hwchen** [comment]
I do have the surrounding quotes :). And I would expect anybody using this API to have the surrounding quotes, although I'm not 100% on this.

**Comment by thejoshwolfe** [comment]
> And I would expect anybody using this API to have the surrounding quotes, although I'm not 100% on this.

You are 100% of people using the API so far (once you start using it), so you can be sure for now.

Let me know if you have any issues with the new API. Thanks for providing the thorough writeup and compelling use case.

**Comment by hwchen** [comment]
Just tried it out, works great! Thanks for being responsive.
