### ISSUE TITLE
Shifting 1 left generates an error.

### ISSUE THREAD

**Issue by curuvar** [ziglang/zig#19588]
### Zig Version

0.12.0-dev.3480+9dac8db2d

### Steps to Reproduce and Observed Behavior

If I code something like "some_var = 1 << other_var;" I get: "error: LHS of shift must be a fixed-width integer type, or RHS must be comptime-known".  I can fix it by changing the 1 to "@as( u32, 1 )", but that's pretty clunky.

### Expected Behavior

I would expect that this would work.  Shouldn't the result type (the type of "some_var") be used to determine the bit-length of the value?

**Comment by RossComputerGuy** [comment]
This is expected behavior

**Comment by curuvar** [comment]
According to my reading of the Result Location Semantics section of the documentation, zig figures out what length to cast an int to when using @intCast based on the size of the variable the result is assigned to.  It seems to me that it should also be able to figure out what length to cast the 1 to when shifting.  Am I overlooking something fundamenal?

**Comment by RossComputerGuy** [comment]
`1` doesn't have a size and so it is a `comptime_int`, if everything was comptime in the shifting then it would likely work.

**Comment by mlugg** [comment]
Not a bug. The behavior you describe is a subtly breaking change, and is proposed [here](https://github.com/ziglang/zig/issues/16489).
