### ISSUE TITLE
Add support for glibc 2.39

### ISSUE THREAD

**Issue by theoparis** [ziglang/zig#19590]
Attempting to build with an arch linux machine using glibc now results in:

```
error: warning: zig cannot build new glibc version 2.39.0; providing instead 2.38.0
```

See https://sourceware.org/pipermail/libc-alpha/2024-January/154363.html

**Comment by rootbeer** [comment]
To be clear, the build still works, right?  You're just seeing this warning while building?

While I'm not on a host with a newer glibc, I can reproduce the problem by targeting the too-new glibc:

```
$ zig run -lc -target native-native-gnu.2.39 hello.zig
LLD Link... warning: zig cannot build new glibc version 2.39.0; providing instead 2.38.0
Hello, world!
```

(I don't have the `error` prefix on my line of output though ...)

Also, you should be able to suppress the warning message by targeting the glibc v2.38 ABI (the latest Zig supports at the moment): `-lc -target native-native-gnu.2.38`

**Comment by nektro** [comment]
why did you close this?

**Comment by andrewrk** [comment]
superseded by #20106
