### ISSUE TITLE
zig command-specific help only works with --help, not -h as it states in zig help output.

### ISSUE THREAD

**Issue by pjlover95** [ziglang/zig#19602]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

I'm on MacOS using nix-darwin and the 23.11 channel for updates, and I see zig version output as 0.11.0.  When I type in "zig help", the last set of lines says:

General Options:

  -h, --help       Print command-specific usage

I wanted to explore the options for "zig cc", so I went ahead and typed all four reasonable combinations:
zig cc -h
zig cc --help
zig -h cc
zig --help cc

Only one of those does what I was expecting ("zig cc --help", giving me the detailed options for zig cc).  I'm pretty sure the last two are bad expectations on my part, which is fair enough.  But the first two, based on the "zig help" output, I would've expected were equivalent.  They're not, though.  "zig cc -h" just spits out:

error: Unknown Clang option: '-h'

I'm filing this as a bug, but it's entirely possible it's intended behavior, or that I'm just mis-understanding something, which is totally fine (and likely).

### Expected Behavior

I would expect zig cc -h to return the same thing as zig cc --help (based on the output of "zig help").  That, or maybe worth changing the "zig help" output to not imply equivalence between the two, and be more specific.

**Comment by Vexu** [comment]
`zig cc` is based on Clang command line options so this behavior is inherited from there.

**Comment by pjlover95** [comment]
Fair enough, thanks @Vexu.  Closing.
