### ISSUE TITLE
FreeBSD PR CI does not checkout the correct pr branch

### ISSUE THREAD

**Issue by tiehuis** [ziglang/zig#1960]
The FreeBSD CI script does not appear to checkout the pr when being invoked by the github pr webhook. It instead pulls the current master and tests that instead.

For example, take this recent pr: https://github.com/ziglang/zig/pull/1958

The compiler version is reported as being [0.3.0+2911eb34](https://builds.sr.ht/~andrewrk/job/29291#task-build-18). However the pr latest commit is de7c55145aeb6687040254dedaef66eedf5328dd.

**Comment by andrewrk** [comment]
This sounds like a sr.ht bug which we'll have to report.

**Comment by andrewrk** [comment]
Reported upstream: https://todo.sr.ht/~sircmpwn/dispatch.sr.ht/24

**Comment by andrewrk** [comment]
I pushed a4e32d9fb143dbfb622a5097ea4a1e4bcad03463 which follows Drew's suggestion. Next pull request that is open we will find out if it fixed it.

**Comment by andrewrk** [comment]
Based on #1961, appears to be fixed.
