### ISSUE TITLE
Building on FreeBSD fails to find -lzstd

### ISSUE THREAD

**Issue by iacore** [ziglang/zig#19617]
### Zig Version

3d1652070acd01b7c871615702916425cd292a8a

### Steps to Reproduce and Observed Behavior

On FreeBSD 14.0, run:

```
git clone https://github.com/ziglang/zig
cd zig
cmake -B build -DCMAKE_BUILD_TYPE=Release -G 'Ninja'
cd build
ninja
```

Output:

```
> ninja
[1/2] Linking CXX executable zig2
FAILED: zig2 
: && /usr/bin/c++ -O3 -DNDEBUG -Wl,-z,stack-size=0x10000000 CMakeFiles/zig2.dir/zig2.c.o CMakeFiles/zig2.dir/compiler_rt.c.o -o zig2 -L/usr/local/llvm17/lib -Wl,-rpath,/usr/local/llvm17/lib  zigcpp/libzigcpp.a  /usr/local/llvm17/lib/libclang-cpp.so.17  /usr/local/llvm17/lib/liblldMinGW.a  /usr/local/llvm17/lib/liblldELF.a  /usr/local/llvm17/lib/liblldCOFF.a  /usr/local/llvm17/lib/liblldWasm.a  /usr/local/llvm17/lib/liblldMachO.a  /usr/local/llvm17/lib/liblldCommon.a  -lLLVM-17  -lrt  -lexecinfo  -lpthread  -lm  -lz  -lzstd  -lpthread  -lm  -lz  -lzstd && :
ld: error: unable to find library -lzstd
ld: error: unable to find library -lzstd
c++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

### Expected Behavior

It should build without problem.

### Additional Details

zstd is installed at /usr/local

```
> pkg list zstd
/usr/local/bin/unzstd
/usr/local/bin/zstd
/usr/local/bin/zstd-frugal
/usr/local/bin/zstdcat
/usr/local/bin/zstdgrep
/usr/local/bin/zstdless
/usr/local/bin/zstdmt
/usr/local/include/zdict.h
/usr/local/include/zstd.h
/usr/local/include/zstd_errors.h
/usr/local/lib/cmake/zstd/zstdConfig.cmake
/usr/local/lib/cmake/zstd/zstdConfigVersion.cmake
/usr/local/lib/cmake/zstd/zstdTargets-release.cmake
/usr/local/lib/cmake/zstd/zstdTargets.cmake
/usr/local/lib/libzstd.a
/usr/local/lib/libzstd.so
/usr/local/lib/libzstd.so.1
/usr/local/lib/libzstd.so.1.5.5
/usr/local/libdata/pkgconfig/libzstd.pc
/usr/local/man/man1/unzstd.1.gz
/usr/local/man/man1/zstd.1.gz
/usr/local/man/man1/zstdcat.1.gz
/usr/local/man/man1/zstdgrep.1.gz
/usr/local/man/man1/zstdless.1.gz
/usr/local/man/man1/zstdmt.1.gz
/usr/local/share/licenses/zstd-1.5.5/BSD3CLAUSE
/usr/local/share/licenses/zstd-1.5.5/GPLv2
/usr/local/share/licenses/zstd-1.5.5/LICENSE
/usr/local/share/licenses/zstd-1.5.5/catalog.mk
```

**Comment by iacore** [comment]
Workaround: edit `CMakeCache.txt` manually.

```
//Flags used by the CXX compiler during all build types.
CMAKE_CXX_FLAGS:STRING=-L/usr/local/lib 
```

**Comment by llogick** [comment]
> Workaround: edit `CMakeCache.txt` manually.
> 
> ```
> //Flags used by the CXX compiler during all build types.
> CMAKE_CXX_FLAGS:STRING=-L/usr/local/lib 
> ```

The [official guide](https://github.com/ziglang/zig/wiki/Building-Zig-From-Source#for-freebsd) recommends `-DCMAKE_PREFIX_PATH="/usr/local"`

**Comment by iacore** [comment]
I still think it's better to hard-code the library path for FreeBSD.

`pkgconf --libs libzstd` also works.

**Comment by andrewrk** [comment]
please file bug in LLVM project, the dependency is supposed to be communicated with llvm-config.

**Comment by sskras** [comment]
The **upstream** label could probably be added here.

**Comment by JanBeh** [comment]
Apparently the problem still exists. I tried building Zig (0cb558ba3abb0ac7b48c1a30c9a13c924f950172) on a FreeBSD `14.3-RELEASE-p1` with updated packages (2025-07-15) using

```
mkdir build
cd build
cmake ..
make
```

and got:

```
[ 94%] Linking CXX executable zig2
ld: error: unable to find library -lzstd
ld: error: unable to find library -lzstd
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1
```

Using `cmake .. -DZIG_STATIC_LLVM=ON -DCMAKE_PREFIX_PATH="/usr/local/llvm20;/usr/local"` as suggested in "Building Zig From Source", For FreeBSD ([revision as of writing this comment](https://github.com/ziglang/zig/wiki/Building-Zig-From-Source/0c6428fa323cb0ee7554ee7322f5f44c0a246824#for-freebsd)), didn't help either.

However, the following works (for me):

`cmake .. -DZIG_STATIC_ZSTD=ON -DCMAKE_PREFIX_PATH="/usr/local"`

(Note that I had to replace `LLVM` with `ZSTD` compared to the suggestions in the wiki.)
