### ISSUE TITLE
[Regression] Fetching dependency from codeberg.org causes it to return 503

### ISSUE THREAD

**Issue by linusg** [ziglang/zig#19624]
### Zig Version

0.12.0-dev.3633+f7a76bdfe

### Steps to Reproduce and Observed Behavior

Works with `0.12.0-dev.3610+9d27f34d0`, no longer works with `0.12.0-dev.3633+f7a76bdfe`. Possibly related to #19500? (cc @ianic) - it's unclear to me whether these changes are included in the working build - the GitHub UI lists them as before but the merge commit is after `9d27f34d0`.

Clone [kiesel](https://codeberg.org/kiesel-js/kiesel/) and try to build:

```
$ zig build run
/home/linus/Dev/kiesel/build.zig.zon:27:20: error: bad HTTP response code: '503 Service Unavailable'
            .url = "https://codeberg.org/linusg/zig-build-libregexp/archive/78f7445d7ccb5c8378d7fb883d3347d02850b6e5.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

...despite codeberg being alive and kicking (and this still working with a previous version).

### Expected Behavior

Should still work.

**Comment by ianic** [comment]
wget, then ` zig fetch 78f7445d7ccb5c8378d7fb883d3347d02850b6e5.tar.gz` works

**Comment by ianprime0509** [comment]
Observation: Codeberg responds with 503 with `Host: codeberg.org:443` but responds normally with 200 with `Host: codeberg.org`:

```
$ curl -v --http1.1 https://codeberg.org/linusg/zig-build-libregexp/archive/78f7445d7ccb5c8378d7fb883d3347d02850b6e5.tar.gz >/dev/null
...
> GET /linusg/zig-build-libregexp/archive/78f7445d7ccb5c8378d7fb883d3347d02850b6e5.tar.gz HTTP/1.1
> Host: codeberg.org
> User-Agent: curl/8.2.1
> Accept: */*
> 
...
< HTTP/1.1 200 OK
...
```

vs

```
$ curl -v --http1.1 -H 'Host: codeberg.org:443' https://codeberg.org/linusg/zig-build-libregexp/archive/78f7445d7ccb5c8378d7fb883d3347d02850b6e5.tar.gz >/dev/null
...
> GET /linusg/zig-build-libregexp/archive/78f7445d7ccb5c8378d7fb883d3347d02850b6e5.tar.gz HTTP/1.1
> Host: codeberg.org:443
> User-Agent: curl/8.2.1
> Accept: */*
> 
...
< HTTP/1.1 503 Service Unavailable
...
```

Zig's HTTP client is using `Host: codeberg.org:443` in the fetch process as of 0.12.0-dev.3639+9cfac4718, but in 0.12.0-dev.3630+215de3ee6 (before #19598), it was using `Host: codeberg.org` (as determined by strategically adding code [here](https://github.com/ziglang/zig/blob/9cfac4718d2a536fdd096320cc68664ae1ee2c68/lib/std/http/Client.zig#L849-L853) to also write the URI to stderr).

**Comment by andrewrk** [comment]
Nice find! Generally, I think it's a good rule of thumb to make computers talking to each other not waste bytes. So that would be a reason to omit the `:443` that is not based on it being a workaround. It might be considerate to file a bug on forgejo, however.
