### ISSUE TITLE
[zig cc] Initialization issue with thread local storage variables?

### ISSUE THREAD

**Issue by deweerdt** [ziglang/zig#19648]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

Seen on macos, Sonoma 14.4:
```
$ cat repro.c
#include <stdio.h>
#include <stdint.h>

struct containee {
    size_t member;
};

struct container {
    const struct containee *c;
};

static const struct containee containee = {.member = sizeof(uint8_t)};
__thread struct container container = {&containee};

int main(void)
{
    printf("%zu\n", container.c->member);
    return 0;
}
$ zig cc repro.c
$ ./a.out
zsh: segmentation fault  ./a.out
```

### Expected Behavior

```
$ clang --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
$ clang repro.c
$ ./a.out
1
```

**Comment by deweerdt** [comment]
I should have added that in the non-minimized program where I hit this, the issue wouldn't reproduce if the program is executed under lldb. Otoh, if one attaches lldb after startup, it shows that `container.c` is an invalid pointer.

**Comment by jedisct1** [comment]
Can you try with a 0.12 snapshot?

I wasn't able to reproduce this using Zig 0.12 (Sonoma / aarch64 and x86_64).

**Comment by deweerdt** [comment]
Ah, indeed, `0.12.0-dev.3653+e45bdc6bd` works as expected. Thank you @jedisct1 !
