### ISSUE TITLE
Declarations from destructuring tuple result of runtime-known value ignores immutability

### ISSUE THREAD

**Issue by sno2** [ziglang/zig#19677]
### Zig Version

0.12.0-dev.3667+77abd3a96

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

fn foo() struct { usize, usize } {
    return .{ 0, 0 };
}

pub fn main() !void {
    const a, const b = foo();

    // Uh oh! No errors!
    a += 2;
    b *= 3;
    a, b = .{ 1, 2 };

    std.log.info("a={}, b={}", .{ a, b });

    // None of these snippets work, as expected.

    // const c, const d = .{ @as(usize, 0), @as(usize, 0) };
    // c = 2;
    // d = 5;

    // const e: usize, const f: usize = .{ 0, 0 };
    // e = 2;
    // f = 5;
}
```

### Expected Behavior

An error because `a` and `b` are defined with `const`.

**Comment by mlugg** [comment]
Oops, this one's my fault. I don't have time to make a PR this second, but for reference for anyone coming to fix this: in `Sema.zirResolveInferredAlloc`, in the `ia1.is_const` case, we need to remap the ZIR index of the `alloc` to refer to `Sema.makePtrConst(ptr)` (bitcasting the pointer to a const version).

**Comment by Rexicon226** [comment]
I can take this if possible. Thanks for the hint :)
