### ISSUE TITLE
support `if`, `orelse`, `null`, and `.?` for C pointers

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1967]
We could make it easier to transition from auto-generated header file import declarations to more well specified Zig pointers by supporting the optional syntax for C pointers. It would do exactly what you expect.

```zig
if (c_pointer) |same_value| {
    // blah
}
const xyz = c_pointer orelse return;
const abc = c_pointer.?;
```

would be equivalent to:

```zig
if (c_pointer != 0) {
    const same_value = c_pointer;
    // blah
}
const xyz = if (c_pointer != 0) c_pointer else return;
const abc = if (c_pointer != 0) c_pointer else unreachable;
```

This is also helpful when you consider that forward declarations are translated as `*c_void`, and a header file could change to make the forward decl be an actual struct, and then the zig type would change but the C code would expect the type to stay the same. With this proposal it would be less surprising.

An argument for this is that given we want people to avoid C pointers, this syntax would help users transition away from translated code toward more zig-like code.

**Comment by SamTebbs33** [comment]
Would this be a good issue for a new contributor to take a look at? If so I'd give it a shot with a few pointers (pardon the pun).

**Comment by andrewrk** [comment]
Hi @SamTebbs33 - this might be a bit tricky, especially considering it's not "accepted" yet. I'd hate for you to do some work and then we end up deciding not to do this proposal.

Have you seen the "contributor friendly" issue label?

**Comment by SamTebbs33** [comment]
That makes sense. I have seen that label so I'll look through some of those issues to see if I find something intriguing.

**Comment by raulgrell** [comment]
I'm going to tackle this over the next couple of days. I assume it should also work with the while unwrapping as well.

**Comment by andrewrk** [comment]
That's correct

**Comment by andrewrk** [comment]
This issue is now resolved; see the above 4 linked commits.

**Comment by raulgrell** [comment]
Thanks for pointing out the changes, I had a tough time getting the codegen to work!

**Comment by miniBill** [comment]
The documentation at https://ziglang.org/#Integration-with-C-libraries-without-FFIbindings mentions that upon closing this issue the code can be made simpler.

Have you considered revising that part? Are you waiting for 0.5.0?
