### ISSUE TITLE
Inline assembly arguments ignored when rXX register is present

### ISSUE THREAD

**Issue by Arnau478** [ziglang/zig#19678]
### Zig Version

0.12.0-dev.3666+a2b834e8c

### Steps to Reproduce and Observed Behavior

Compile the following code:
```zig
export fn foo() void {
    asm volatile("nop" // can be anything
        :
        : [something] "r11" (0x12345),
    );
}
```
The produced assembly code does not include the operand passed to the r11 register:
```asm
foo:
    push rbp
    mov rbp, rsp
    nop ; the instruction is inserted, but nothing is moved into r11
    pop rbp
    ret
```
Experimenting with this, I've found two interesting things:
- Having a single `"rXX"` register parameter makes the compiler ignore **all** of them, even ones with registers like `"rax"`, which normally work fine.
- If the `"{rXX}"` syntax is used (with the curly braces), it works fine. From this, I am guessing it has to do with how it is parsed, as it starts with `r` (maybe it is parsed as `"r"`?)

### Expected Behavior

The produced assembly code for the example given should be similar to:
```asm
foo:
    push rbp
    mov rbp, rsp
    mov r11, 0x12345 ; (or some optimized equivalent instructions)
    nop
    pop rbp
    ret
```

**Comment by jacobly0** [comment]
In zig, `"r11"` is not a valid constraint, `"{r11}"`  is the correct constraint for a named register.

**Comment by Arnau478** [comment]
> In zig, `"r11"` is not a valid constraint, `"{r11}"` is the correct constraint for a named register.

Then it should report an error or something, not just quietly ignore it... I see a big inconsistency in how this is handled, `"rax"` works as expected.

**Comment by jacobly0** [comment]
It does report an error if you try to use that input.  And as you said, `r` mean register, so `rax` allows it to be put in a register which might happen to be `rax`, but typing other letters including `r` also puts it in `rax`, so that doesn't mean much. `rax` means something like any register or `ax` or any xmm register.
