### ISSUE TITLE
[0.12.0-dev] Relative paths for `zig run` broken

### ISSUE THREAD

**Issue by ThisAccountHasBeenSuspended** [ziglang/zig#19695]
### Zig Version

0.12.0-dev.3674+a0de07760

### Steps to Reproduce and Observed Behavior

With `v0.11.0` this command works without any problems: `zig run src/main.zig --deps mymod --mod mymod::../mymod/src/main.zig`

With `v0.12.0-dev` we get the following results:
- `zig run --dep mymod -Mroot=src/main.zig -Mmymod=../mymod/src/main.zig`
  - Error: `error: found another zig file '../mymod/src/main.zig' after root source file '.zig'`
- `zig run --dep mymod -Mroot=./src/main.zig -Mmymod=../mymod/src/main.zig`
- - `-Mroot=src/main.zig` changed to `-Mroot=./src/main.zig`.
  - Error: `error: found another zig file '../mymod/src/main.zig' after root source file './src/main.zig'`
- `zig run --dep mymod -Mroot=D:/GitHub/test/src/main.zig -Mmymod=D:/GitHub/mymod/src/main.zig`
- - Added full path to folder.
  - IT WORKS!

OS: Windows 11 Pro (22631.3447)

### Expected Behavior

Paths like `src/main.zig` should work as in `v0.11.0`.

**Comment by andrewrk** [comment]
That error message only happens when there is a positional argument after a `-M` argument.  Your example CLI does not have such a thing, however.

**Comment by ThisAccountHasBeenSuspended** [comment]
> That error message only happens when there is a positional argument after a `-M` argument. Your example CLI does not have such a thing, however.

I understand. Thank you very much!

Maybe it would be helpful to list it under `zig run --help`.
