### ISSUE TITLE
Translate-c fails to translate fn proto with empty args

### ISSUE THREAD

**Issue by suirad** [ziglang/zig#1970]
When calling `zig translate-c` on a `.c/.h` file with empty arguments, it doesn't produce a fn prototype.

Failing example: 
```c
void blah(){
}
```
Calling translate c on the above, the resulting zig file doesn't have a blah fn proto in it.

----
However changing it to this:
```c
void blah(void){
}
```
Results in a zig file with a correct fn prototype:
```zig
pub extern fn blah() void;
```

**Comment by andrewrk** [comment]
note if you use `--verbose-cimport` you'll get a nice warning explaining the problem
