### ISSUE TITLE
std.compress.deflate fails on particular input

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#19737]
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

Run this zig program below (i.e. `zig run deflatefail.zig`).  It will fail with `error: InvalidDynamicBlockHeader`.
```zig
const std = @import("std");

pub fn main() !void {
    var fbs = std.io.fixedBufferStream(&data);
    var total_uncompressed: usize = 0;
    var decompressor = std.compress.flate.decompressor(fbs.reader());
    while (try decompressor.next()) |chunk| {
        total_uncompressed += @intCast(chunk.len);
    }
    if (fbs.pos != data.len)
        return error.NotAllDecompressed;
    if (total_uncompressed != 32773)
        return error.UnexpectdUncompressSize;
}

// This data was generated with this command:
//     7z a -mm=Deflate64 -mx9 bad.zip bad.txt
// with the attached bad.txt file.
// Then the compressed contents were manually extracted.
const data = [_]u8 {
    0xe5, 0xde, 0xcb, 0x4d, 0xc3, 0x40, 0x10, 0x00, 0xd0, 0x33,
    0x54, 0xe1, 0x06, 0xb2, 0xfe, 0x05, 0x62, 0xe5, 0x44, 0x27,
    0xc8, 0xac, 0x36, 0xb2, 0x85, 0xb1, 0x93, 0x8d, 0x23, 0xda,
    0xc7, 0x39, 0x00, 0x07, 0x3a, 0xe0, 0x3d, 0xad, 0xb4, 0x9a,
    0x5f, 0x0d, 0x33, 0x55, 0xf5, 0xf8, 0x32, 0xc7, 0x5b, 0xce,
    0x69, 0x5e, 0x4f, 0xe3, 0xb4, 0xa6, 0xfc, 0x9e, 0xf2, 0x9c,
    0xa6, 0x30, 0x14, 0x21, 0x94, 0x71, 0xc9, 0x69, 0x1a, 0xdf,
    0xb6, 0xff, 0xbb, 0xa7, 0xbc, 0xac, 0xbf, 0xc1, 0xe9, 0x36,
    0xc7, 0x75, 0x5c, 0xe6, 0xcf, 0xdc, 0x9f, 0xcf, 0x29, 0x5f,
    0xff, 0x0e, 0xf5, 0x3c, 0x1e, 0x8f, 0xc7, 0xe3, 0xf1, 0x78,
    0x3c, 0x1e, 0x8f, 0xc7, 0xe3, 0xf1, 0x78, 0x3c, 0x1e, 0x8f,
    0xc7, 0xe3, 0xf1, 0x78, 0x3c, 0x1e, 0x8f, 0xc7, 0xe3, 0xf1,
    0x78, 0x3c, 0x1e, 0x8f, 0xc7, 0xe3, 0xf1, 0x78, 0x3c, 0x1e,
    0x8f, 0xc7, 0xe3, 0xf1, 0x78, 0x3c, 0x1e, 0x8f, 0xc7, 0xe3,
    0xf1, 0x78, 0x3c, 0x1e, 0x8f, 0xc7, 0xe3, 0xf1, 0x78, 0x3c,
    0x1e, 0x8f, 0xc7, 0xe3, 0xf1, 0x78, 0x3c, 0x1e, 0x8f, 0xc7,
    0xe3, 0xf1, 0x78, 0x3c, 0x1e, 0x8f, 0xc7, 0xe3, 0xf1, 0x78,
    0x3c, 0x1e, 0x8f, 0xc7, 0xe3, 0xf1, 0x78, 0x3c, 0x1e, 0x8f,
    0xc7, 0xe3, 0xf1, 0x78, 0x3c, 0x1e, 0x8f, 0xc7, 0xe3, 0xf1,
    0x78, 0x3c, 0x1e, 0x8f, 0xc7, 0xe3, 0xf1, 0x78, 0x3c, 0x1e,
    0x8f, 0xc7, 0xe3, 0xfd, 0x5b, 0x39, 0xee, 0xf6, 0xa1, 0x0b,
    0x87, 0xf2, 0x9a, 0xe3, 0xcf, 0xc2, 0xfd, 0x2d, 0x3b, 0x94,
    0x97, 0x7e, 0x5d, 0x3e, 0xc6, 0xf8, 0x7a, 0x0f, 0xc2, 0xf0,
    0xd0, 0x54, 0xf5, 0xd3, 0xae, 0xda, 0x5e, 0x57, 0x34, 0xf5,
    0x71, 0xdf, 0x1d, 0xdb, 0x36, 0x34, 0x87, 0xba, 0x7a, 0xae,
    0xab, 0xb6, 0x2e, 0xb6, 0xca, 0xfd, 0x00, 0x80, 0x2f,
};

```

### Expected Behavior

Program should run and finish with a successful exit code.

The given input should decompress to the contents of `bad.txt` attached below.  Note that the input was generated by compressing `bad.txt` using `7z` with the command-line seen above in the source code.

[bad.txt](https://github.com/ziglang/zig/files/15064742/bad.txt)

I've also included the contents of bad.txt here, note that it must not include any newlines (or the issue won't reproduce).

<details>
<pre>aabc_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________a_____a__dda___bee__f____g_________h_i_jklmn__________aabc</pre>
</details>

**Comment by squeek502** [comment]
cc @ianic

[puff](https://github.com/madler/zlib/tree/develop/contrib/puff) also fails on this with error code `-3` which is `dynamic block code description: too many length or distance codes`

**Comment by marler8997** [comment]
@squeek502 this input requires deflate64...I don't see deflate64 mentioned in puff so that might be why it fails?

**Comment by marler8997** [comment]
Ah I didn't realize the std lib doesn't support deflate64 :)  Closing, we could create a new issue to add support for deflate64.
