### ISSUE TITLE
zig fetch error: unrecognized 'Content-Type' header: 'application/zip'

### ISSUE THREAD

**Issue by sytranvn** [ziglang/zig#19748]
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

I think this is more like a feature request than a bug.

This works
```
zig fetch --save https://github.com/kubkon/zig-yaml/archive/refs/heads/main.tar.gz
```

But this does not.

```
zig fetch --save https://github.com/kubkon/zig-yaml/archive/refs/heads/main.zip
error: unrecognized 'Content-Type' header: 'application/zip'
```

### Expected Behavior

Zig can fetch zip archive without error since not every published packages are tar.gz 
<img width="407" alt="Screenshot 2024-04-23 at 17 53 11" src="https://github.com/ziglang/zig/assets/13009812/0a839fde-8c50-420a-9b9d-40b9dbf08c45">

**Comment by tauoverpi** [comment]
note https://github.com/ziglang/zig/pull/19729 implements this.

**Comment by sytranvn** [comment]
Thanks, closing this because duplicated
