### ISSUE TITLE
unable to evaluate constant expression

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#1977]
Can you help me understand why the compiler produces ‘unable to evaluate constant expression’ in this very small program?

https://github.com/markfirmware/zig-constant-expression/blob/master/zigconstexpr.zig

I’m trying to implement a function that takes a format string as an argument and passes it straight to std.fmt.bufPrint. I’ve tried all sorts of type declarations and casting but I have not been successful. The most straight-forward approach (in the link at the top of this post) produces ‘unable to evaluate constant expression.’ As far as I can tell the expression is just a string literal, so I am at a loss to understand what the problem is.

I am working to link zig with https://ultibo.org which is a raspberry pi unikernel.

Thanks,
Mark

**Comment by matthew-mcallister** [comment]
Try
```zig
fn msg(comptime fmt: []const u8, args: ...) void {
    var msgBuf: [1024]u8 = undefined;
    _ = std.fmt.bufPrint(&msgBuf, fmt, args);
}
```

**Comment by markfirmware** [comment]
Thank you!

**Comment by matthew-mcallister** [comment]
For the record, the `comptime` keyword used in type position is being interpreted as a comptime block by `ast_parse_primary_type_expr. Aren't types always computed at compile time? Should this be made an error as long as it's causing confusion?
