### ISSUE TITLE
Unexpected Destructuring Behaviour

### ISSUE THREAD

**Issue by KilianHanich** [ziglang/zig#19772]
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

    const assert = @import("std").debug.assert;
    
    test "swapping" {
        var x: u32 = 3;
        var y: u32 = 5;
        
        x, y = .{ y, x };
        
        assert(y == 3);
        assert(x == 5);
    }

This fails, `x` and `y` are both 5.

### Expected Behavior

The test does not fail or gives a compile error that swapping values this way (like in Python) doesn't work, even if the syntax suggests it.

**Comment by nektro** [comment]
Duplicate https://github.com/ziglang/zig/issues/12064

**Comment by nektro** [comment]
https://ziglang.org/documentation/master/std/#std.mem.swap is recommended for this use case

**Comment by KilianHanich** [comment]
Yeah ok, missed that issue.

**Comment by KilianHanich** [comment]
PS: While yes, std.mem.swap is better for this use case, I constructed a minimal example here. You should be able to use for this rotating multiple values (e.g. `x, y, z = .{y, z, x};`) too.
