### ISSUE TITLE
make it a compile error to use `comptime` in an expression that syntactically guarantees implicit comptime

### ISSUE THREAD

**Issue by matthew-mcallister** [ziglang/zig#1980]
See https://github.com/ziglang/zig/issues/1977.

Prefixing a type expression with `comptime` causes it to be interpreted as a single-expression comptime block. As far as I understand, this is useless, as types are always computed at compile time. However, it is evidently easy to confuse with the `comptime` annotation on a variable. Compare these two declarations:
```zig
var x: comptime usize;
comptime var x: usize;
```

Should this be made a syntax error? If it's of any value, the ability to explicitly create a comptime block could still be retained by adding braces, as in `x: comptime { <expr> }`, which seems much less easy to mistake for a comptime variable declaration.

**Comment by andrewrk** [comment]
I could see there being a special rule against a trivial expression `comptime` and then an identifier, in contexts that are implicitly comptime.  In every case this would be better written as just the identifier. 

Another idea is that `comptime` would always be a compile error if it was redundant.

**Comment by matthew-mcallister** [comment]
The former suggestion wouldn't actually cover the case that prompted the issue, which was a function prototype of the form
```zig
fn msg(fmt: comptime []const u8, args: ...) void {...}
```

The latter seems like the better solution considering.

**Comment by matthew-mcallister** [comment]
This could also be a warning instead of a hard error.

**Comment by andrewrk** [comment]
Zig intentionally has no warnings. If we ever wanted a warning-like message, it would be an error, that you had to explicitly silence.

**Comment by SpexGuy** [comment]
Oh we just did this with #8364. Closing this since that issue is tracking the work, but please feel free to reopen it if there is a distinct proposal here.
