### ISSUE TITLE
creating static libraries targeting macosx results in unusable .a files

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#1981]
```zig
export fn foo() void {}
```

```
zig build-lib foo.zig
```

```c
void foo(void);
int main() {foo(); return 0;}
```

```
cc -o test test.c foo.a
ld: warning: ignoring file foo.a, file was built for archive which is not the architecture being linked (x86_64): foo.a
```

The error message is bogus; the file is of course the correct architecture.

Suggestion here is to use `libtool -static -o libio.a io.o` rather than `ar`.:
https://stackoverflow.com/questions/30948807/static-library-link-issue-with-mac-os-x-symbols-not-found-for-architecture-x8

We will have to figure out how to do that using LLVM API.

A workaround for this bug is to use `build-obj` instead of `build-lib`. Indeed that's the workaround here:

https://github.com/ziglang/zig/blob/74a335c4ccd9eb4cfcc5cc6c01b633584c6bb6ba/src/link.cpp#L35-L42

Related issue regarding a new linker: #1535 
Related issue regarding dynamic libraries: #1982

**Comment by LemonBoy** [comment]
> // The Mach-O LLD code is not well maintained, and trips an assertion
> // when we link compiler_rt and builtin as libraries rather than objects. 

Is the assertion you get the same as #2421?

**Comment by andrewrk** [comment]
I believe I was tripping https://github.com/ziglang/zig/blob/1c73c08298fc3a19886038d935e45cf74ba152fb/deps/lld/lib/ReaderWriter/MachO/ArchHandler_x86_64.cpp#L442 and some of the other equivalent assertions in this file.
