### ISSUE TITLE
defineCMacro not respected in included header file

### ISSUE THREAD

**Issue by actondev** [ziglang/zig#19839]
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

if in build.zig you define something like `exe.defineCMacro("NOCPP",` "1");` and the header file the you `cImport` has something like
```
#ifndef NOCPP
namespace nsfoo {
  struct CppFoo{};
}
#endif
```
the compilation will fail. However, if before the `cImport` you use `@cDefine("NOCPP", "1");`, it works

### Expected Behavior

I'd expect the `defineCMacro` to be respected

**Comment by ianprime0509** [comment]
The [comment](https://github.com/ziglang/zig/issues/19840#issuecomment-2091891395) I left on #19840 applies here as well: `-D` is also a per-module option, so it needs to be passed to the module that needs it. In your example project, this means replacing `exe.defineCMacro("CFOO", "1");` with `binding.addCMacro("CFOO", "1");`

**Comment by actondev** [comment]
Thank you again! Still need to debug the compiler crashing on me though heh
