### ISSUE TITLE
github api client implementation

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#1983]
I did not see a c library for github at https://developer.github.com/v3/libraries/
Since it is a rest api, is there a recommended zig rest client, or a recommended c rest client library?

If it tuns out that zig is a good choice for working with github, I also expect to use https://libgit2.org for processing repositories. I don’t yet know if I will use zig for this. I’d like to collect my scattered repositories and build some kind of index that I can search across all my repos, branches, and commits.

Thanks,
Mark

**Comment by daurnimator** [comment]
> Since it is a rest api, is there a recommended zig rest client, or a recommended c rest client library?

See #910 

Which is blocked on the coroutine refactor. Which is blocked on copy elison.

i.e. this will be a while away yet.

**Comment by andrewrk** [comment]
Hi @markfirmware 

I think this is a good topic for one of the other community pages:
https://github.com/ziglang/zig/wiki/Community

@daurnimator is correct about the roadmap. Your best bet is probably relying on C libraries at this point until Zig's networking becomes ready for beta testing.
