### ISSUE TITLE
`addrspace(.gs)` does nothing

### ISSUE THREAD

**Issue by Khitiara** [ziglang/zig#19915]
### Zig Version

0.13.0-dev.75+5c9eb4081

### Steps to Reproduce and Observed Behavior

in the context of an x86 kernel in zig, set the value of MSR `0xC000_0101` GS_BASE to some nonzero value and compare the memory accessed by:
1: `asm("movq %gs:8, %[out]" : [out] "=r" (-> usize))`,
2: `@as(*const addrspace(.gs) usize, @ptrFromInt(8)).*`
3: `@as(*const usize, @ptrFromInt(8)).*`
and note that 2 and 3 access the same memory, at a different final address from what 1 accesses.

### Expected Behavior

in the above setup, 1 and 2 should access the same final memory address which should differ from 3 by the value written to the MSR

**Comment by Khitiara** [comment]
this behavior was first observed by me in [imaginarium](https://github.com/Khitiara/imaginarium/tree/381d802cbeaafdc3f3cac260b51dfe7a4f2335d7), noting specifically that in [`hal/arch/x86_64/smp.zig`](https://github.com/Khitiara/imaginarium/blob/381d802cbeaafdc3f3cac260b51dfe7a4f2335d7/src/hal/arch/x86_64/smp.zig#L16-L31) that the value pointed to by the `lcb` decl and the return value of the `lcb_ptr` function gave different behavior

**Comment by Vexu** [comment]
Fix:
```diff
diff --git a/src/codegen/llvm.zig b/src/codegen/llvm.zig
index 04a5af8bb0..8a67655106 100644
--- a/src/codegen/llvm.zig
+++ b/src/codegen/llvm.zig
@@ -4375,7 +4375,7 @@ pub const Object = struct {
             .int => try o.builder.castConst(
                 .inttoptr,
                 try o.builder.intConst(try o.lowerType(Type.usize), offset),
-                .ptr,
+                try o.lowerType(Type.fromInterned(ptr.ty)),
             ),
             .eu_payload => |eu_ptr| try o.lowerPtr(
                 eu_ptr,
```
