### ISSUE TITLE
Diff type errors to make them easier to read

### ISSUE THREAD

**Issue by silversquirl** [ziglang/zig#19916]
### Zig Version

0.12.0

### Steps to Reproduce and Observed Output

```zig
const T = std.AutoArrayHashMapUnmanaged(u32, u32);
const a: T = .{};
const b: *T = a;
_ = b;
```

This outputs the following, rather formidable, error message:

```
test.zig:4:19: error: expected type '*array_hash_map.ArrayHashMapUnmanaged(u32,u32,array_hash_map.AutoContext(u32),false)', found 'array_hash_map.ArrayHashMapUnmanaged(u32,u32,array_hash_map.AutoContext(u32),false)'
```

### Expected Output

By performing a tree diff, it would be possible to deduplicate the error message, producing this instead:

```
test.zig:4:19: error: expected type '*T0', found 'T0'
test.zig:4:19: note: 'T0' = 'array_hash_map.ArrayHashMapUnmanaged(u32,u32,array_hash_map.AutoContext(u32),false)'
```

This should probably only be attempted if the type names in the error message are both longer than some threshold, eg. 32 characters.

**Comment by nektro** [comment]
letting the human do the diff would be better imo

```
test.zig:4:19: error: expected type 'T0', found 'T1'
test.zig:4:19: note: 'T0' = '*array_hash_map.ArrayHashMapUnmanaged(u32,u32,array_hash_map.AutoContext(u32),false)'
test.zig:4:19: note: 'T1' = 'array_hash_map.ArrayHashMapUnmanaged(u32,u32,array_hash_map.AutoContext(u32),false)'
```

**Comment by silversquirl** [comment]
I don't see how that's helpful at all. The whole point is to be able to easily say "oh oops I need a pointer, silly me" without having to look at the whole type

**Comment by dweiller** [comment]
I've found that when I get type errors with long generic types that are hard to scan for the issue, the base generic type is correct and it's just an issue with needing a pointer or having a const pointer when a mutable one is needed. Another option would be to have compiler recognise simple patterns like these and say something like "expected a mutable pointer but got a const pointer to..."

**Comment by silversquirl** [comment]
I think that's useful - and the compiler does do this for some types, like the const pointer for example, it'll add a note saying "cast discards const qualifier" - but I think diffing is also useful for the general case, where the compiler sometimes *can't* figure this out.

One example is using the wrong generic container type, eg. `std.ArrayList(SomeComplexTypeName)` instead of `std.ArrayListUnmanaged(SomeComplexTypeName)`. It would be silly to special-case this in the compiler, but the diffing approach would handle it perfectly :)

**Comment by Vexu** [comment]
This issue is proposing a solution to #12401
