### ISSUE TITLE
C translation issue with downcasting pointer

### ISSUE THREAD

**Issue by eknkc** [ziglang/zig#19934]
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

While trying to embed quickjs in a zig application I observed an error that only happens during a wasm build. Basically quickjs does something like this:

```c
#include <stdint.h>

typedef uint64_t Bar;

void foo(Bar *v) {
  (void*)(intptr_t)v;
}
```

Which in turn gets translated to

```zig
_ = @as(?*anyopaque, @ptrFromInt(@as(isize, @intCast(@intFromPtr(v)))));
```

However this results in the following error:

```
error: expected type 'usize', found 'isize'
note: unsigned 64-bit int cannot represent all possible signed 64-bit values
```

Changing `isize` manually to `usize` resolves the compilation problem.

I've observed this issue in 

https://github.com/bellard/quickjs/blob/d378a9f3a583cb787c390456e27276d0ee377d23/quickjs.h#L652
https://github.com/bellard/quickjs/blob/d378a9f3a583cb787c390456e27276d0ee377d23/quickjs.h#L139C1-L139C50

How can I get this to work?

### Expected Behavior

Emit valid zig code from c header

**Comment by f-cozzocrea** [comment]
This is a known issue that should be fixed in a later version (currently milestoned for 0.14). If you have control over the translated code, this workaround should compile in the meantime:

```C
(void*)(uintptr_t)v;  // Change inptr_t to uintptr_t
```

**Comment by f-cozzocrea** [comment]
Related/duplicate issue: #18178

**Comment by eknkc** [comment]
Oh thanks a lot. 

Will maintain a patch file until this gets fixed. 

Closing in favor of original issue.
