### ISSUE TITLE
Support more hash algorithms in the package manager

### ISSUE THREAD

**Issue by theoparis** [ziglang/zig#19937]
I see that multihash is used, which supports blake3. However, the package manager [only supports SHA256 at the moment](https://github.com/ziglang/zig/blob/cb77bd672c3b398e3c5f6be80af03243bf8638e3/src/Package/Manifest.zig#L49). I didn't see an open issue to track this so that is why I am creating this one.

**Comment by nektro** [comment]
why did you close this?
