### ISSUE TITLE
Migrated code from std.ComptimeStringMap to std.StaticStringMap generates error `expected type`

### ISSUE THREAD

**Issue by MaciekLeks** [ziglang/zig#19993]
### Zig Version

0.13.0-dev.211+6a65561e3

### Steps to Reproduce and Observed Behavior

I have upgraded my zig-linux-x86_64-0.13.0-dev.28+3c5e84073 to the commit version mentioned above.
Here is the original code:

[return GenericInfo(HeaderDataInfo(h_info, std.ComptimeStringMap(GlyphNumber, codepoint_glyph_arr[0..uc_codes])));](https://github.com/MaciekLeks/bebok/blob/f11452863a40bab4798bb4921a8d703b797245cf/lib/terminal/psf/font.zig#L348)

I thought it could be migrated to:
```
return GenericInfo(HeaderDataInfo(h_info, std.StaticStringMap(GlyphNumber).initComptime(codepoint_glyph_arr[0..uc_codes])));
```

However, that's not true because I'm now getting these errors:
```
lib/terminal/psf/font.zig:350:101: error: expected type '?type', found 'static_string_map.StaticStringMapWithEql(u32,(function 'defaultEql'))'
            return GenericInfo(HeaderDataInfo(h_info,  std.StaticStringMap(GlyphNumber).initComptime(codepoint_glyph_arr[0..uc_codes])));
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/zig/zig-linux-x86_64-0.13.0-dev.211+6a65561e3/lib/std/static_string_map.zig:39:12: note: struct declared here
    return struct {
           ^~~~~~
lib/terminal/psf/font.zig:104:66: note: parameter type declared here
fn HeaderDataInfo(comptime h_info: HeaderInfo, comptime UTF8Map: ?type) type {
                                                                 ^~~~~
lib/terminal/psf/font.zig:363:28: note: called from here
        return Version1Info(file);
               ~~~~~~~~~~~~^~~~~~
lib/terminal/generic_terminal.zig:23:43: note: called from here
pub const FontPsf1Lat2Vga16 = psf.FontInfo("assets/Lat2vga16.psf");
```

So, isn't a bug?

### Expected Behavior

No error would nice.

**Comment by travisstaloch** [comment]
ComptimeStringMap() used to return a type.  but now StaticStringMap(T).initComptime() returns a StaticStringMap(T). 

I think this question could be better answered in one of the [communities](https://github.com/ziglang/zig/wiki/Community)

**Comment by MaciekLeks** [comment]
Thanks. I did not notice that simple fact ;)
