### ISSUE TITLE
`ArrayHashMap` confusing documentation

### ISSUE THREAD

**Issue by MrBrN197** [ziglang/zig#19990]
this documentation for `Context` in `ArrayHashMap`  seems to suggest the `eql` function takes 2 args but the compiler complains that it needs  3 arguments.
https://github.com/ziglang/zig/blob/6a65561e3e5f82f126ec4795e5cd9c07392b457b/lib/std/array_hash_map.zig#L70-L77

**Comment by squeek502** [comment]
Looks like it should be `pub fn eql(self, K, K, index) bool` judging from `array_hash_map.StringContext.eql`:

https://github.com/ziglang/zig/blob/6a65561e3e5f82f126ec4795e5cd9c07392b457b/lib/std/array_hash_map.zig#L41

**Comment by NicoElbers** [comment]
Introduced in cf88cf2657d721c68055a284e8c498a18639f74c
