### ISSUE TITLE
lld: error: undefined symbol: printf

### ISSUE THREAD

**Issue by agentpt5** [ziglang/zig#1999]
I am trying to compile that C printf example in the manual.  However, I am getting a lld error.  I'm not sure if this is a zig 0.3.0 bug or my nix-shell (on Nixos Linux x86_64) is incomplete.  Setting either llvm/clang/lld to 6 or 7 produces same failed result.  Thanks for your help.

Source Code -- just calling c.printf to print "hello."

const std = @import("std");
const warn = std.debug.warn;
const c = @cImport({
    @cDefine("_NO_CRT_STDIO_INLINE", "1");
    @cInclude("stdio.h");
});

pub fn main() void {
    warn ("Hello, world!\n");
    _ = c.printf(c"hello\n");
}

I compile with command:
zig build-exe --verbose-link --verbose-cimport hello.zig

My result:
Among the listing of C imports is
pub extern fn printf(__format: ?[*]const u8) c_int;
and ending with

lld --gc-sections -m elf_x86_64 -o hello -dynamic-linker /nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib/ld-linux-x86-64.so.2 zig-cache/hello.o /home/n/.local/share/zig/stage1/artifact/lVwQmZxTliJRSYS-E2ccaC5lIEDgyyskxf1YMvppDQPdoX1CjbLRDX-yPNBydg9b/builtin.o /home/n/.local/share/zig/stage1/artifact/3WO6S9fki2HHcCda8PTb3xLwr8Vc0ATZ6UcZL-HI2BELc3rnAXMgFCKxe-uSyMp8/compiler_rt.o
lld: error: undefined symbol: printf
>>> referenced by hello.zig:10 (/home/n/zig/hello.zig:10)
>>>               zig-cache/hello.o:(main)

The above seems to indicate that glibc-2.27 is dynamic-linked.  Here is my nix-shell default.nix.

with import <nixpkgs> {};
  stdenv.mkDerivation rec {
  name = "zig-env";
  hardeningDisable = [ "all" ];
  env = buildEnv { name = name; paths = buildInputs; };
  buildInputs = with pkgs; [
    (callPackage /etc/nixos/zig.nix {})
    cmake
    pkgconfig
    llvmPackages_7.clang-unwrapped
    llvm_7
    lld_7
    zlib
    libxml2
    kcov
    valgrind
    gdb
    ];
}

**Comment by agentpt5** [comment]
I found out the problem.  Basically, I am just an idiot.  The solution is on the manual.
I need to add --library c to the build-exe command.

zig build-exe hello.zig --library c

**Comment by andrewrk** [comment]
Don't worry you're not an idiot. There's an open issue to make this error better #1698
