### ISSUE TITLE
No error for sub-function cases

### ISSUE THREAD

**Issue by charlesrocket** [ziglang/zig#20003]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Output

```
pub fn main() !void {
    fn foo(bar: usize) void {};
}
```
-> 
```
src/main.zig:8:8: error: function type cannot have a name
    fn foo(bar: usize) void {};
       ^
```

### Expected Output

The error should describe an illegal sub-function declaration instead.

**Comment by Vexu** [comment]
Duplicate of #17440
