### ISSUE TITLE
std.io.fixedBufferStream not compatible with std.fmt.format

### ISSUE THREAD

**Issue by hans-tvs** [ziglang/zig#20028]
### Zig Version

0.12.0 (godbolt) and also 0.13.0-dev.31+5d745d94f

### Steps to Reproduce and Observed Behavior

```
const std = @import("std");

test {
    var buffer: [1024]u8 = undefined;
    const writer = std.io.fixedBufferStream(&buffer);
    try std.fmt.format(writer, "{s}", .{"Hello, World!"});
}
```

Observe that `std.fmt.format` expects the writer to have an `Error` public constant.

```
/opt/compiler-explorer/zig-0.12.0/lib/std/fmt.zig:480:18: error: struct 'io.fixed_buffer_stream.FixedBufferStream([]u8)' has no member named 'Error'
```

### Expected Behavior

The given test code should have no errors (especially not compile errors). From an outsider's perspective, it seems like fixedBufferStream has a notion of possible error types (e.g., `WriteError`), and those don't map to the way std.fmt.format wants to handle errors (requiring, e.g., `Error`). Whichever was updated out-of-sync with the other, it's a likely bug, hopefully obviated if/when Zig has proper interfaces in places where that will work in lieu of `anytype`, but definitely annoyingly buggy for now.

**Comment by Vexu** [comment]
You are using `fixedBufferStream` incorrectly, here's a fixed version of your example:
```zig
const std = @import("std");

test {
    var buffer: [1024]u8 = undefined;
    var fbs = std.io.fixedBufferStream(&buffer);
    try std.fmt.format(fbs.writer(), "{s}", .{"Hello, World!"});
}
```
