### ISSUE TITLE
Add `!noreturn` return type for `std.Thread.spawn`

### ISSUE THREAD

**Issue by Arnau478** [ziglang/zig#20024]
Allow `startFn` to return `!noreturn`. If both `noreturn` and `!void` are supported, why wouldn't `!noreturn` be?

Right now the error is `error: expected return type of startFn to be 'u8', 'noreturn', 'void', or '!void'`

**Comment by Vexu** [comment]
Related #18810

**Comment by GreyAerin** [comment]
This seems like a relatively simple extension of #4757. I'd like to take a crack at it. Could I get this issue assigned to me?
