### ISSUE TITLE
`addTest` and `findProgram` methods of `std.Build` use deprecated `host` field instead of `graph.host`

### ISSUE THREAD

**Issue by Trevor-Strong** [ziglang/zig#20035]
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

In #19684 the `host` field was deprecated; however, the `addTest` and `findProgam` methods of `std.Build` still use this field instead of the suggested replacement of `graph.host`. 

### Expected Behavior

I would expect the standard library to use the `graph.host` field instead of the deprecated `host` field.

I have also checked that these are the only two places under `std.Build` or the build runner that make this mistake, and that this is present on master at the time of writing.

**Comment by andrewrk** [comment]
Unobservable internal implementation details are not a bug and do not warrant an issue.

Notice that your "observed behavior" contains no observed behavior.
