### ISSUE TITLE
typeOf a bytesToSlice expression in return type of function fails to compile

### ISSUE THREAD

**Issue by Hejsil** [ziglang/zig#2004]
This worked 1 week ago, but something change in master and now it doesn't compile.

```zig
test "" {
    _ = a(""[0..]);   
}

fn a(bytes: var) @typeOf(@bytesToSlice(u64, bytes)) {
    return undefined;
}
```

```
test.zig:5:26: error: unable to evaluate constant expression
fn a(bytes: var) @typeOf(@bytesToSlice(u64, bytes)) {
                         ^
```

**Comment by andrewrk** [comment]
Hmm I might have to push back on this one. `@bytesToSlice` is marked as having side effects because you could do this for example:

```zig
test "" {
    var wrong_number_of_bytes: [3]u8 = undefined;
    _ = a(wrong_number_of_bytes[0..]);
}
fn a(bytes: var) []align(1) u64 {
    return @bytesToSlice(u64, bytes);
}
```

```
$ ./zig test test.zig 
Test 1/1 ...slice widening size mismatch
/home/andy/dev/zig/build/test.zig:6:12: 0x203328 in ??? (test)
    return @bytesToSlice(u64, bytes);
           ^
/home/andy/dev/zig/build/test.zig:3:10: 0x203163 in ??? (test)
    _ = a(wrong_number_of_bytes[0..]);
         ^
```

Is this from one of your projects? What's the real world code that ran into this problem?

**Comment by Hejsil** [comment]
I have wrappers for `@bytesToSlice` that:
* Checks for out of bounds and returns an error.
* Only `@byteToSlice` on the bytes that would fit into the slice `bytes[0 .. bytes.len - bytes.len % @sizeOf(Element)]`

https://github.com/Hejsil/fun-with-zig/blob/master/src/generic/slice.zig

**Comment by andrewrk** [comment]
I think I'll mentally categorize this as a bug in how `@typeOf`is implemented. Related: https://github.com/ziglang/zig/issues/1627#issuecomment-426810297

**Comment by andrewrk** [comment]
Prioritizing for 0.4.0 because @Hejsil is blocking on it.

**Comment by andrewrk** [comment]
This test passes now thanks to some recent improvements to `@TypeOf`. 

https://github.com/ziglang/zig/blob/f83411b0b1b857c7f8679e3b90d2093ba60621d4/test/stage1/behavior/sizeof_and_typeof.zig#L93-L104
