### ISSUE TITLE
x86-windows miscompilation after LLVM 18 upgrade

### ISSUE THREAD

**Issue by squeek502** [ziglang/zig#20047]
### Zig Version

0.13.0-dev.249+ed75f6256

### Steps to Reproduce and Observed Behavior

When running the standard library tests with `-target x86-windows` I hit:

```
> zig test lib\std\std.zig --zig-lib-dir lib -target x86-windows
Test [2/2716] debug.decltest.machoSearchSymbols... expected debug.MachoSymbol@2b13464, found debug.MachoSymbol@2b13468
Test [2/2716] debug.decltest.machoSearchSymbols... FAIL (TestExpectedEqual)
Segmentation fault at address 0x0
Segmentation fault at address 0x0
Segmentation fault at address 0x0
Segmentation fault at address 0x0
Panicked during a panic. Aborting.
error: the following test command failed with exit code 3:
C:\Users\Ryan\Programming\Zig\zig\zig-cache\o\6b0eda73b9d23fabe1b7288a523661d4\test.exe
```

After updating `resinator` to latest Zig I hit many similar problems when targeting 32-bit Windows: https://github.com/squeek502/resinator/actions/runs/9204915991/job/25319442772 (but 64-bit Windows and other OSes work fine, even 32-bit targets on other OSes)

There might be multiple bugs involved here, but here's an as-minimal-as-I-could-get-it reproduction of one manifestation of the problem:

```zig
const std = @import("std");

test "limitedWriter basic usage" {
    var buf: [4]u8 = undefined;
    const fbs = FixedBufferStream{ .buffer = &buf, .pos = 0 };
    var limited_stream = LimitedWriter{ .inner_writer = fbs, .bytes_left = 4 };
    try std.testing.expectEqual(4, limited_stream.bytes_left);

    std.mem.doNotOptimizeAway(&limited_stream);
}

const LimitedWriter = struct {
    inner_writer: FixedBufferStream,
    bytes_left: u64,
};

const FixedBufferStream = struct {
    buffer: []const u8,
    pos: usize,
};
```

This passes for me when targeting `x86_64-windows`:

```
> zig test limited_writer.zig -target x86_64-windows
All 1 tests passed.
```

But fails when targeting `x86-windows`:

```
> zig test limited_writer.zig -target x86-windows
expected 4, found 136223752605138948
FAIL (TestExpectedEqual)
Segmentation fault at address 0x0
Panicked during a panic. Aborting.
error: the following test command failed with exit code 3:
C:\Users\Ryan\Programming\Zig\tmp\zig-cache\o\5297f27c52f0325a3ca3d5ec831a5abb\test.exe
```

Importantly, note that `doNotOptimizeAway` is used here because `limited_stream` being `var` is necessary. If `limited_stream` is `const`, then the test passes.

### Expected Behavior

The reproduction test to pass on 32-bit Windows.

**Comment by squeek502** [comment]
By the way, this is not caught by the CI because it uses `-Dskip-non-native`:

https://github.com/ziglang/zig/blob/332fbb4b027a5529e58b1e46d785718a7faa75e6/ci/x86_64-windows-debug.ps1#L69

https://github.com/ziglang/zig/blob/332fbb4b027a5529e58b1e46d785718a7faa75e6/ci/x86_64-windows-release.ps1#L69

It seems that `-Dskip-non-native` has always been there, though, so did something change to make `x86-windows` considered non-native or has the `x86-windows` target never been tested in CI?

**Comment by andrewrk** [comment]
The x86-windows target has never been tested in CI because it was never passing the tests.

**Comment by squeek502** [comment]
Yeah, it's non-deterministic.

If it's helpful, here's [a Godbolt link](
https://zig.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AAvPMFJL6yAngGVG6AMKpaAVxYM9DgDJ4GmADl3ACNMYhAADlIAB1QFQlsGZzcPPVj4mwFffyCWUPCoy0xrRKECJmICZPdPLgtMK0yGMoqCbMCQsMiLcsrq1LqFXra/DryuiIBKC1RXYmR2DjQGIYBqIfRVgFIAZgARVYABPBZYyogtgCZLjavLyd2AIS2NAEEX18xVM4JVqgY/qhUBBJqsAG6oPCbLYAdmeb1WiPBFVWwVcVBA2wArI9JFssXtXBFtvtVq4GFgaP50E8PkjVss1lRggoSQcAGJ4VSYdCPdFUMJlYiYViwx6rAB0aKoAuIbO2lwAbNLSJL0vKNNsYXtaQikWCUbQToQeQB9IbC1jy3wsE3oADqxBNxDFkr8/mIpoA7k6CGF5cyFKqpQBPP0KU30Ki/XYHSRanU7eGvel4KirCBG21%2B9DmgiWlih8ORzDR1ZgMCx1aSUGHaKGPDIC7XVy/VAIO4PJMfOlIjYStiF9CoAKoAgAeWiNltxkwry9TBDzcVWbteYLXeTsJ1bw%2BjN%2BNrtjud8otrmsWuTqYYHu9vq6q053N5/MF%2BZFLFIvcRwTDmAjUYEJiriKtIPbarq7xvPuj5cjyfIym%2BBanvm54xnC36oq%2B4TYs8BIwUSX56oi6TAfEs5Ee8EFJhw0y0JwWK8J43C8KgnAAFpmOsszzJgCo7DwpBARwWiTNMADWICXFi%2BicJITGaKxnC8AoIAaEJinTHAsAwIgKCoKcdBhOQlBoIZ9DhMYGhcJc6k0LQfrEKpEDBIppDBH4FQhpwgkecwxAhuOwTaMUwmCWZbCCOODC0N5Im8FgaLAI4Yi0KpLGkFgLCGMA4jxZleDCiUYL/m5XzFK2iyCX4fr0flRrBMQXnOFgbn5icPm8CVxDBHEmB7Jg2VGEaRiaXwBjAAoABqeCYF6k6MJ1MiCCIYjsFIy3yEoahubodQGKNpjmA1qmQNMqBTok6UALS9MAmC/KoESKtdXp%2BMOXoKNdwAMK4rHdU6WCnSC9SNIk9gUv0tSkD4oy5PkaRxAkAhQ4jGSJO08NdIMDShaUwyozjYMCC0lSY504SDATLg1HoQytOT4yU9MCg8QsEh0QxCn5WxHCrEdqwaBKNkSpqEC4IQJD8Vwky8MJokSVJMl1fJpAsCAWLqcxWikLzKlqRp8VabpEBIIVJkQBw13/Kg134AoojEOg10Gm4mDXcwbAKBwblmdERnEAErCLALQsizrWU5fQ10KCGeQuOlOs8pLgN6PZjnXUwBDtWi4ZuenYTXRFjAEInvAF8QduYEl11%2BPw%2Bd0BnfhniUAjXWw5ToFnTD57Iq3iBt/CCIoKjqPle2g3jdgQA4hMwxSjMI3U6TI0kNMDDESNNIv2OT63zTUyk0NFPvpMjDkFN04ftNUwzcOXzLQnCpgUJqZzHCMaQ2tKRw3jeFNABZVYABJAASqsGac1/Sh2FpcUWGYJZEDlFcASqpnDmX9CgmWctNLTAQCKLA4QQYq14OrTWX83J6wsAbeWtFFbSVkhwHY3MdZUNocbeA2k9J%2BwDhbHhFkQDGFQgwcSfBG5hGcq5fKfkvJLRkQFIKIVrBLWLlFGKcUI7V1cMlVK6VBKR2GosCOhU8YlTLjDbkyBKpLRqg0NyDUmoBRakYuWTp1YZW6r1JQA0hq5T8KAI240mCTUgfNaIi0MpD2EKIAe0gokjx2uPKS%2BgcqCLMPoPALJ4DnUugIG6d0HqrCei9N6FJUCfW%2Br9f6YRAalTOnvJoEMnDr2hrDC%2BTM0arznivbe98OlEyngfVoc8T5NDPjvSmPRhktKvnfdpS8WZs3Wu/T%2B39dacH5lxYR4kEH4CQdLWWhsFakEkjsHYEozmXKudcxUjDVZkK1pQ5S1D1LsNIFw02IBzYUEttbBgtt7aO2dq7Vw7tPb/h9vlfhYQg5sE4ALbZCVBpR3drHeOaUyp7JIK/OoFdM7ZydLnUq%2BU8WqNLg3ByhdEraNrgweuJLxGV2bqhfe7cHpMC7uUXuK0YnrTibIBJY8da6EuA08GM9IYzLqG0sYS9N7oxRlK%2BVq8Jl01xqfa%2BG9Rn4zmbK3e9M%2BhKoNefPVzMn6YBfugN%2BjDVlPN/v/IBYCIGzS9NArZxByQ7PFli5BlxUGrHQf7Cy/F7g4KNngghXRiFyVIRrR5PNnmqVebgk5UkuAXMkJILEOwYQRC4FiGyioNDZsYcwihCaOBhtEu8k2SB8AygtlE/ufLNqCvsQgVS%2B0O31ujCGcJBtaAdq%2BPmJgF1GmVtIMQDtySp0KB7QQPt7B1KzuHU1Md4NK0rJYT/PYaZ0yhLdcAQWsD4FglZAij1Iiq10NTZcCIEpFRYixJIRUlwuAREkBEGEOwACcysY3ltYYmmhKa6qXG3esid7DpjdXiHYSQQA%3D%3D%3D) comparing 0.12.0 (which works) to trunk (which fails).

The assembly diff is in the link, but here's the LLVM IR diff:

<details>
<summary>LLVM IR diff</summary>

```diff
5c5
< %example.LimitedWriter = type { i64, %example.FixedBufferStream, [4 x i8] }
---
> %example.LimitedWriter = type { %example.FixedBufferStream, i64 }
7c7
< @builtin.zig_backend = internal unnamed_addr constant i64 2, align 8
---
> @builtin.zig_backend = internal unnamed_addr constant i64 2, align 4
9c9
< @Target.x86.cpu.pentium4 = internal unnamed_addr constant %Target.Cpu.Model { { ptr, i32 } { ptr @__anon_280, i32 8 }, { ptr, i32 } { ptr @__anon_280, i32 8 }, %Target.Cpu.Feature.Set { [9 x i32] [i32 0, i32 34816, i32 1073758208, i32 128, i32 1064960, i32 272, i32 0, i32 0, i32 0] } }, align 4
---
> @Target.x86.cpu.pentium4 = internal unnamed_addr constant %Target.Cpu.Model { { ptr, i32 } { ptr @__anon_280, i32 8 }, { ptr, i32 } { ptr @__anon_280, i32 8 }, %Target.Cpu.Feature.Set { [9 x i32] [i32 0, i32 557056, i32 1048576, i32 16400, i32 -2113929216, i32 1114112, i32 0, i32 0, i32 0] } }, align 4
11c11
< @builtin.cpu = internal unnamed_addr constant %Target.Cpu { ptr @Target.x86.cpu.pentium4, %Target.Cpu.Feature.Set { [9 x i32] [i32 2, i32 34816, i32 1073758208, i32 128, i32 1589248, i32 272, i32 0, i32 0, i32 0] }, i6 -28, [3 x i8] undef }, align 4
---
> @builtin.cpu = internal unnamed_addr constant %Target.Cpu { ptr @Target.x86.cpu.pentium4, %Target.Cpu.Feature.Set { [9 x i32] [i32 2, i32 557056, i32 1048576, i32 16400, i32 -1040187392, i32 1114112, i32 0, i32 0, i32 0] }, i6 -28, [3 x i8] undef }, align 4
14c14
< @__anon_940 = internal unnamed_addr global [6 x i8] c"ut oh\00", align 1
---
> @__anon_967 = internal unnamed_addr global [6 x i8] c"ut oh\00", align 1
16c16
< @__anon_984 = internal unnamed_addr global [29 x i8] c"'noreturn' function returned\00", align 1
---
> @__anon_1011 = internal unnamed_addr global [29 x i8] c"'noreturn' function returned\00", align 1
18c18
< @builtin.panic_messages.noreturn_returned = internal unnamed_addr constant ptr @__anon_984, align 4
---
> @builtin.panic_messages.noreturn_returned = internal unnamed_addr constant ptr @__anon_1011, align 4
22,23c22,23
<   %0 = alloca [24 x i8], align 8
<   %1 = alloca [24 x i8], align 8
---
>   %0 = alloca [20 x i8], align 4
>   %1 = alloca [20 x i8], align 4
50c50
<   %19 = getelementptr inbounds %example.LimitedWriter, ptr %0, i32 0, i32 1
---
>   %19 = getelementptr inbounds %example.LimitedWriter, ptr %0, i32 0, i32 0
52,56c52,56
<   %20 = getelementptr inbounds %example.LimitedWriter, ptr %0, i32 0, i32 0
<   store i64 4, ptr %20, align 8
<   call void @llvm.memcpy.p0.p0.i32(ptr align 8 %1, ptr align 8 %0, i32 24, i1 false)
<   %21 = getelementptr inbounds %example.LimitedWriter, ptr %1, i32 0, i32 0
<   %22 = load i64, ptr %21, align 8
---
>   %20 = getelementptr inbounds %example.LimitedWriter, ptr %0, i32 0, i32 1
>   store i64 4, ptr %20, align 4
>   call void @llvm.memcpy.p0.p0.i32(ptr align 4 %1, ptr align 4 %0, i32 20, i1 false)
>   %21 = getelementptr inbounds %example.LimitedWriter, ptr %1, i32 0, i32 1
>   %22 = load i64, ptr %21, align 4
61c61
<   call fastcc void @mem.doNotOptimizeAway__anon_1201(ptr nonnull align 8 %1)
---
>   call fastcc void @mem.doNotOptimizeAway__anon_1143(ptr nonnull align 4 %1)
65,66c65,66
<   %24 = extractvalue { ptr, i32 } { ptr @__anon_940, i32 5 }, 0
<   %25 = extractvalue { ptr, i32 } { ptr @__anon_940, i32 5 }, 1
---
>   %24 = extractvalue { ptr, i32 } { ptr @__anon_967, i32 5 }, 0
>   %25 = extractvalue { ptr, i32 } { ptr @__anon_967, i32 5 }, 1
89,90c89,90
<   %8 = extractvalue { ptr, i32 } { ptr @__anon_984, i32 28 }, 0
<   %9 = extractvalue { ptr, i32 } { ptr @__anon_984, i32 28 }, 1
---
>   %8 = extractvalue { ptr, i32 } { ptr @__anon_1011, i32 28 }, 0
>   %9 = extractvalue { ptr, i32 } { ptr @__anon_1011, i32 28 }, 1
95c95
< define internal fastcc void @mem.doNotOptimizeAway__anon_1201(ptr nonnull align 8 %0) unnamed_addr {
---
> define internal fastcc void @mem.doNotOptimizeAway__anon_1143(ptr nonnull align 4 %0) unnamed_addr {
```

</details>

Note, though, that the `x86-linux` target works correctly and it has identical LLVM IR as the failing `x86-windows` target.

Here's [another Godbolt link that compares the `x86-windows` assembly to `x86-linux`](https://zig.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AAvPMFJL6yAngGVG6AMKpaAVxYMQAZlIOAMngMmABy7gBGmMQgAEwapAAOqAqEtgzObh7eCUkpAgFBoSwRUbEWmFY2AkIETMQE6e6ePpaY1qnVtQT5IeGRMXEKNXUNmc1DXYE9RX2xAJQWqK7EyOwcaAyDANSD6JsApF4AIpsAAngsiXUQe9HROzfRswcAQnsaAIJv75iqlwSbVAYANQqAgs02ADdUHhdnsAOyvD6bZGQ2qbMKuKggfYAVmekj2OMOrgAHPsjptXAwsDQgugXl8UZt1lsqGEFOTjgAxPCqTDoZ6YqiRarETCseHPTYAOgxVGFxE5%2B2iADY5aQZYkOQdjhp9nDDgykSiIWjaOdCPyAPqDMWsJUBFiW9AAdWIluIkplgSCxCtAHd3QRIkq2QoNbKAJ7BhRW%2BhUf46zaSfWGryI95MvBUTYQc1O4PoG0EO0sKMxuOYBObMBgJOScEneKGPDIa63Vz/VAIB5PdNfRkonbSthl9CoYKoAgAeXiNidxkw739TEj7ZV%2BedxdLfYz8MNHy%2BLP%2Bjudbo9Sttrms%2BozWYYvoDQb6mx5fIFQpFJfFLFIg%2BRYTRpgsbxgQ2KuCq0gDgaRqfB8x6vry/KCvKX6lpeJbXomCL/uin5RLirxEghpJ/sayJauBySLmRnwwemHDzLQnA4rwnjcLwqCcAAWmY2yLMsmDKl4PCkGBHBaLM8wANYxCS0peHCXgqnCqpeF4GjRJIWk4vonCSGxmicZwvAKCAcTiZJpBwLAMCICgqAXHQkTkJQaBOfQUTGJhDDSXwdDBsQZkQGERmkGEgS1JGnCiRFzDEJG05hNorTiaJ7lsII04MLQ0USbwWAYsAjhiLQZkcaQWAsIYwDiPllV4GKbQQsBYU/K0narKJgTBsx9XmmExBRc4WBhSW5wxbwLXEGESSYIcmDVUY5pGEZ8xUAYwAKAAangmD%2BrOjCTTIggiGI7BSCd8hKGoYW6Fw%2Bg1SApjmANZmQPMqBzqk5UALRDMAmD/KoJIqr9K2uKov3AAwricdN7pYO9YJlBUqT2NSIyeA9/iTIUxR6FquRpC4jSEzklQMN0%2BN9A9LRtFU4xY3o9OUx0dTU70UR00zpOZDznSc9M3PzAoAkrBITEsYZ9VcRwmwvZsPnSbmuCECQwlcLMvCWYx1lII1rkQBwv2Aqgv34AoojEOgv2mm4mC/cwbAKBwYXufEznEMErCrIrysFYtNX0L9CiRkULjlVovj4EQiN6DQtCBb9TAEONGIxmFifJxljAEFHvDZ5EFuYEVv2BPwWcBcXgRXgzDC/WwNToKnTBZ7IZ3iJd/CCIoKjqPV92o6l6MQA4zM49SQsEw9ROUxP2TJJT0%2B08P9fs/UfPY2vbPjCv3MWLzGTb4Mgt41zktiWKmAwuZUscKxpDsdHct%2BH420ALKbAAkgASpsu19ohn9sQKkKsIBqzjprDUzgPIhhuCJbWYk1rzAQOKLAUQUayRxHEPqBlSAsBADgp%2BYU5amXMsg/K8wbL2Q9l7I2dDPLPWVv5JOkRgqhXqnFKKx1uEJSSilawx1c5ZRynlaOhVXDFVKuVUSVVg6rAkY1EeLUC6%2BD5MgTqx0erlDCgNIaCURqKJ1u6QhFVpqzSUAtJatVAigCoXwTaO09oHXiEdCqPdhCiC7tITxfdbqDxiI9VaL19B4HZPAT630BB/QBkDTYIMwb%2BkCOOf0Choaw3hpERGrUPo71HuPLeehcYFAvrPCmqQF5z1SPvFm5QR6M06AvVm7Q97n2FizI%2BZMBYc3aTPUW4sLr30fs/Yy8sQFgNVrHDWCCtY6zWvrEAhsKDG1Ngwc2ltra23tq4R2ztgJu3qowyIPs2CcAmb5QONiQ5hwjmVNq0z44PSLsQFOad3QZ1avVF5v0RH5yrmw15kjgDlwYJXb51dXm10wvXRuQMmAtxqO3U63iLq%2BNkP4ge0ddDRHyXYMemMimT3QLU8pS9KlEsXsTUleKGAb2afU9ebTSkdJ6ZvY%2BnSz4sv6VfTAN90B3z0g/GWL9OBv0/j/f%2BgD/TAL4srKZ6tFSzJgY5T2nlhKPHmVQ1B6C%2BgozwbwQhxDRmkDIRYChuspKkFkupaUKopBcA0AATjhEpZ1JJohwiFV4EVYytVWRoRAJA%2BB5RG08Z3NFV1MV6IQGZXFtBY0hoTJGNxFCE1KFUCWJgX1KYmVIMQWNegC0KCTQQFN7A4jFp%2BFmnN6MOB6z6iM0hnBDjZhzNK2VwAlagN8pCDkFzpL%2BsYjJbw8kNBcFuFwOEOInVeBJK6yQTqhX4JNWasyFkUFCuiL601ebLXzGmskOwkggA%3D%3D%3D)

**Comment by andrewrk** [comment]
oh, I have an idea. the interestingness check can be to compile the zig code to x86-linux and run it, and get the expected result (not exit 0, but something more difficult, like writing the expected value to stdout). then compile the same zig code to x86-windows and get the wrong answer, or a crash. The reduction could be performed on a Linux machine with Wine installed. This will require enhancements to `zig reduce`.

**Comment by andrewrk** [comment]
I'm not going to block the 0.13.0 release on this. I value other priorities higher than x86-windows support. Note that this doesn't even change the Tier category of this target since even in 0.12.0 this target is Tier 2.

**Comment by squeek502** [comment]
@andrewrk I think it would make sense to remove the `x86-windows` build of Zig from the downloads page for `0.13.0` and `master` until this is resolved, since this miscompilation affects the compiler itself so anyone trying to use the `x86-windows` build of the compiler will run into weird crashes/errors/strange behavior (see [this help thread in Discord for an example](https://discord.com/channels/605571803288698900/1242632879566098502/1242632879566098502)).

**Comment by andrewrk** [comment]
I agree

**Comment by squeek502** [comment]
The cause of this is likely to be https://github.com/ziglang/zig/issues/20469
