### ISSUE TITLE
Some calls to std.debug.print() don't produce output when running zig test

### ISSUE THREAD

**Issue by cottonears** [ziglang/zig#20053]
### Zig Version

0.13.0-dev.249+ed75f6256

### Steps to Reproduce and Observed Behavior

I wrote two unit tests to investigate a simplified version of a bug I found in my code. The complete code (including functions + unit tests) is below:
```
const std = @import("std");

pub fn func1(ext_buffer: []u8, x: i32) ![]u8 {
    return try std.fmt.bufPrint(ext_buffer[0..], "x = {}", .{x});
}

pub fn func2(x: i32) ![]u8 {
    var local_buff: [32]u8 = undefined; // probably causing a bug
    return try std.fmt.bufPrint(local_buff[0..], "x = {}", .{x}); 
}

test "test 1, 2" {
    var ext_buff: [32]u8 = undefined;
    const r1 = try func1(ext_buff[0..], 42);
    std.debug.print("\nresult 1: {s}", .{r1}); // APPEARS IN TERMINAL
    const r2 = try func2(42);
    std.debug.print("\nresult 2: {s}", .{r2}); // DOESN'T SHOW IN TERMINAL???
    try std.testing.expectEqualStrings(r1, r2);
}

test "test 2, 1" {
    var ext_buff: [32]u8 = undefined;
    const r2 = try func2(42);
    std.debug.print("\nresult 2: {s}", .{r2}); // APPEARS IN TERMINAL
    const r1 = try func1(ext_buff[0..], 42);
    std.debug.print("\nresult 1: {s}", .{r1}); // APPEARS IN TERMINAL
    try std.testing.expectEqualStrings(r1, r2);
}
```
When I test this on my system (amd64, Debian 12), the output for "test 1, 2" only contains one message. See below:
![image](https://github.com/ziglang/zig/assets/131612371/21f9ce5d-a50b-4ee6-8eb1-5d9f62763b32)
I think there is a bug in my func2 (resulting in a dangling pointer) that might be a factor in the weird behaviour.

### Expected Behavior

I expected to see two messages printed to the terminal for the first test.

**Comment by travisstaloch** [comment]
Not sure whats going on here but this line is returning a dangling pointer to a local.  
```zig
var local_buff: [32]u8 = undefined; // probably causing a bug
```

Questions like these don't belong here and should be directed to [one of the communities](https://github.com/ziglang/zig/wiki/Community)

**Comment by nektro** [comment]
Duplicate of https://github.com/ziglang/zig/issues/15091

**Comment by cottonears** [comment]
Thanks, I didn't find the existing issue. Will close this now.

**Comment by nektro** [comment]
(actually that issue is about `zig build test` not `zig test` so I was mistaken. apologies)
