### ISSUE TITLE
std.debug.bufPrintZ padding on the wrong side of output

### ISSUE THREAD

**Issue by Eken-beep** [ziglang/zig#20078]
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

With the following code:
```` zig
const int: u32 = 5;
var buf = [3:0]u8{'0', '0', '0'};
std.debug.print("{s}--", .{buf});
std.mem.copyForwards(u8, &buf, std.fmt.bufPrintZ(&buf, "{d:0>}", .{int}) catch blk: {
    break :blk &[3:0]u8{'9', '9', '9'};
});
std.debug.print("{s}", .{buf});
````
the output is:
`000--50`
and setting the restraint to 3 characters in the formatting options makes it overflow and output `999`

however with this code:
```` zig
var buf = [4:0]u8{'0', '0', '0', ' '};
std.debug.print("{s}--", .{buf});
std.mem.copyForwards(u8, &buf, std.fmt.bufPrintZ(&buf, "{d:0>3}", .{int}) catch blk: {
    break :blk &[3:0]u8{'9', '9', '9', ' '};
});
std.debug.print("{s}", .{buf});
````
the output is:
`000--005`
as it should be in the first one
No formatting options except {d} gives the same output

Setting the restraint to 2 character on the first code sample makes it work, but it eats one byte.

### Expected Behavior

```` zig
const int: u32 = 5;
var buf = [3:0]u8{'0', '0', '0'};
std.debug.print("{s}--", .{buf});
std.mem.copyForwards(u8, &buf, std.fmt.bufPrintZ(&buf, "{d:0>}", .{int}) catch blk: {
    break :blk &[3:0]u8{'9', '9', '9'};
});
std.debug.print("{s}", .{buf});
````
should output:
`000-005`

If this is intentional and I am doing something wrong, then I should be able to increase the format length with one without overflow. Also no restraint should not pad the number with a 0 to the right.

**Comment by Vexu** [comment]
`bufPrintZ` takes a `[]u8` not a `[:0]u8` it doesn't know your buffer already has a sentinel. Also you don't need to `copyForwards` the result of `bufPrint` since it already writing to the same buffer. I think you were going for something like this?
```zig
const int: u32 = 5;
var buf = [3:0]u8{ '0', '0', '0' };
std.debug.print("{s}--", .{buf});
std.debug.print("{s}", .{try std.fmt.bufPrint(&buf, "{d:0>3}", .{int})});
```
