### ISSUE TITLE
default local cache directory to `.zig-cache` instead of  `zig-cache`

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#20077]
This plays nicely with more tooling. For example, text editors will typically exclude this directory from "find in files" features. It communicates to new users of Zig that these files are ephemeral. I apologize for not getting this right the first time.

`zig-out` is unchanged.

**Comment by thejoshwolfe** [comment]
and `zig-out` is unchanged, right?

**Comment by AshishBhattarai** [comment]
Normally you would add zig-cache and zig-out to .gitignore and most editors automatically ignore anything in .gitignore, this change might not be necessary.
