### ISSUE TITLE
zig fetch -h should include examples

### ISSUE THREAD

**Issue by hippietrail** [ziglang/zig#20096]
`zig fetch -h` or `zig fetch --help` currently tells us:
```
% zig fetch -h    
Usage: zig fetch [options] <url>
Usage: zig fetch [options] <path>

    Copy a package into the global cache and print its hash.

Options:
  -h, --help                    Print this help and exit
  --global-cache-dir [path]     Override path to global Zig cache directory
  --debug-hash                  Print verbose hash information to stdout
  --save                        Add the fetched package to build.zig.zon
  --save=[name]                 Add the fetched package to build.zig.zon as name
  --save-exact                  Add the fetched package to build.zig.zon, storing the URL verbatim
  --save-exact=[name]           Add the fetched package to build.zig.zon as name, storing the URL verbatim
```

But should ideally provide examples:

Which formats are supported. Tar and more recently Zip (I believe gzipped Tar is also supported?)

But then there's git URLs, which I believe are supported. Maybe I'm the only one who doesn't know enough about Git but my naïve attempts are not working.

After trying a bunch of things I realized I made some dumb mistakes like doing `git fetch` instead of `zig fetch` sometimes or doing `zig fetch` with a plain `https` schema instead of a `git+https` schema. I've removed the specifics which are not really useful.

So I'm assuming an example will help others besides me. (And perhaps there are multiple kinds of Git URLs that work?)

**Comment by tisonkun** [comment]
Why was this issue closed as not planned? Is it tracked else where?

I hit a case that the zig package is a subpath of the repo/tarball ([here](https://github.com/apache/opendal/tree/main/bindings/zig)). And the build depends on another subpath to build the C lib.

Some document on zig fetch and the format of build.zig.zon file would be helpful ..

[This page](https://github.com/ziglang/zig/blob/master/doc/build.zig.zon.md) seems helpful to specify an alternative path to resolve the root path. But nothing about how zig fetch can work.

**Comment by mtlynch** [comment]
Any chance of reconsidering this issue? I just hit the same thing, and I couldn't figure out from the help output what URL I'm supposed to pass to `zig fetch`. A github HTTP URL? The .git URL?

This also is one of the top results when I search `zig fetch` in Kagi, so if anyone comes across this, I think the answer is that Zig fetch wants the path to the source tarball:

```bash
zig fetch --save https://github.com/JacobCrabill/zigdown/archive/refs/heads/main.tar.gz
```

**Comment by andrewrk** [comment]
No, zig will not endorse one version control system over another, nor one code hosting service over another, by including examples of them.

**Comment by mtlynch** [comment]
It doesn't even have to be a real vendor. This would be fine:

```
zig fetch --save https://example.com/andrewrk/fun-example-tool/archive/refs/heads/main.tar.gz
```

Possibly in addition, are you open to more specificity in the help output to let the user know that the URL is supposed to be to a source tarball? Because currently the help text just says "url" without specifying what kind of URL it should be.

**Comment by andrewrk** [comment]
Sure, that sounds like a nice enhancement 👍 

Feel free to submit a patch.
