### ISSUE TITLE
Unsure how to handle duplicate symbol linker error

### ISSUE THREAD

**Issue by ncoe** [ziglang/zig#20092]
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

Experimenting with using the zig compiler with a c project, I noticed that am not able to get the linker to ignore duplicate symbols errors. It looked like an argument such as "-muldefs" or "--allow-multiple-defintions" when passed to the linker should resolve this, except that this just changed the error to be about an unsupported linker extension flag.

### Expected Behavior

Passing the -zmuldefs option (or equivalent thereof) permits merging identical symbols together into a binary.

**Comment by andrewrk** [comment]
bug report without Steps To Reproduce
