### ISSUE TITLE
New progress goes in the way of interactive CLI apps

### ISSUE THREAD

**Issue by akarpovskii** [ziglang/zig#20128]
### Zig Version

0.13.0-dev.344+b2588de6c

### Steps to Reproduce and Observed Behavior

If you `zig build run` the following code, the output of the new progress bar will stay on the screen until the process ends.
```zig
const std = @import("std");

pub fn main() !void {
    const stdin_file = std.io.getStdIn().reader();
    _ = try stdin_file.readByte();
}
```
Output:
```sh
zig build run
[5/7] steps
└─ run zig_test
  # <- waiting for input here
```

It looks particularly bad with interactive CLI applications (see the screenshot):
<details>
<summary>Screenshot</summary>
<img width="942" alt="Screenshot 2024-05-30 at 21 22 36" src="https://github.com/ziglang/zig/assets/21952395/73d67e30-ea61-46c2-94ab-26fb183a7108">
</details>

### Expected Behavior

Progress is hidden when the application is running, as it was on zig-12.0

**Comment by akarpovskii** [comment]
Well, right as I posted this, I found an existing issue which I missed before creating the report - #20119, sorry about that :)

**Comment by andrewrk** [comment]
duplicate of #20119
