### ISSUE TITLE
zig run does not clear terminal progress before executing child

### ISSUE THREAD

**Issue by clickingbuttons** [ziglang/zig#20148]
### Zig Version

0.13.0-dev.351+64ef45eb0

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() !void {
    std.debug.print("hello world\n", .{});
}
```

```sh
~/src(master)$ zig run ./test.zig
hello worldbject
```

### Expected Behavior

Clear the `LLVM Emit Object` text before running the user program so it prints `hello world` instead of `hello worldbject`.

**Comment by ProkopRandacek** [comment]
interesting, can't reproduce using a non-llvm build. probably because it doesn't print the LLVM Emit Object/LLD Link messages.

**Comment by andrewrk** [comment]
> interesting, can't reproduce using a non-llvm build. probably because it doesn't print the LLVM Emit Object/LLD Link messages.

you couldn't reproduce because your computer built hello world within initial_delay_ns which defaults to 200ms (the amount of time before any progress display occurs on the terminal)
