### ISSUE TITLE
Compiletime evaluation is really slow

### ISSUE THREAD

**Issue by ItsMeSamey** [ziglang/zig#20163]
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

When compiling the following code, compiler takes `56m20.280s`.
```zig
const std = @import("std");
const print = std.debug.print;

const file = @embedFile("./data/words.txt"); // '\0' separated 333_333 words
// Takes forever
const offsets = init:{
  @setEvalBranchQuota(333333*10);
  var arr :[333333]u32 = undefined;
  arr[0] = 0;
  var at = @as(usize, 1);
  for (file, 0..) |c, i| {
    if (c == 0) {
      arr[at] = @intCast(i+1);
      at += 1;
    }
  }
  break: init arr;
};
// .
test {
  const str = file[offsets[offsets.len-1]..];
  print("|>{s}<|\n", .{str});
}
```
runtime equivalant on the other hand takes `2.187s`.
```zig
test {
  var arr :[333333]u32 = undefined;
  arr[0] = 0;
  var at = @as(usize, 1);
  for (file, @as(u32, 0)..) |c, i| {
    if (c == 0) {
      arr[at] = @intCast(i+1);
      at += 1;
    }
  }
  _ = &arr;
  const str = file[arr[arr.len-1]..];
  print("|>{s}<|\n", .{str});
}
```

also, this might be unrelated but memory usages kept rising (from ~150MiB at start upto 520 MiB).
command used: `time zig test words.zig`
file: [words.txt](https://github.com/user-attachments/files/15525039/words.txt)

### Expected Behavior

Program compiles in a reasonable amount of time ( < 1 minute).

**Comment by nektro** [comment]
Duplicate of https://github.com/ziglang/zig/issues/4055

**Comment by ItsMeSamey** [comment]
Closing as duplicate.
