### ISSUE TITLE
stale compiler id hash on windows

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2021]
I noticed that one time I did `git pull`, ran a build, and it used an old version of builtin.zig rather than build a new one.

Reproduction steps would be to make sure the compiler id hash is different after every rebuild.

`zig id` after a rebuild should be different.

**Comment by Sahnvour** [comment]
Can confirm it's very frequent to have compiler errors because of builtin when updating the repository.

**Comment by andrewrk** [comment]
I just played around with this on Windows. I believe I fixed this with the caching system improvements. Please alert me if you observe this behavior again.
