### ISSUE TITLE
std.Uri.percentDecodeInPlace causes panic in zig 0.13.0

### ISSUE THREAD

**Issue by softprops** [ziglang/zig#20225]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

In zig 0.12.0 this program prints  the string `percent decode me`

```zig
const std = @import("std");

pub fn main() !void {
    const str = "percent%20decode%20me";
    std.debug.print("{s}", .{std.Uri.percentDecodeInPlace(@constCast(str))});
}
```

In zig 0.13.0 this program panics with the error

```
Bus error at address 0x1025ee888
Panicked during a panic. Aborting.
```

### Expected Behavior

In zig 0.13.0 this program prints  the string `percent decode me`

```zig
const std = @import("std");

pub fn main() !void {
    const str = "percent%20decode%20me";
    std.debug.print("{s}", .{std.Uri.percentDecodeInPlace(@constCast(str))});
}
```

**Comment by xdBronch** [comment]
this working before was because of https://github.com/ziglang/zig/issues/18404 which is fixed now. the function accepts a mutable slice so the correct usage would be
```zig
const std = @import("std");

pub fn main() !void {
    var str = "percent%20decode%20me".*;
    std.debug.print("{s}", .{std.Uri.percentDecodeInPlace(&str)});
}
```

**Comment by softprops** [comment]
closing

mentioned this on zig's [discord](https://discord.com/channels/605571803288698900/1248652305851617322/1248652305851617322) and got a fast response. 

This makes sense to me.

you folks are great!
