### ISSUE TITLE
Crash when importing file from parent directory?

### ISSUE THREAD

**Issue by dbandstra** [ziglang/zig#2024]
I'm not sure if it's always this situation that fails, but I have a very minimal test case:

`main.zig`:
```
pub const i: i32 = 0;
```

`test/crashing_test.zig`:
```
const std = @import("std");
const main = @import("../main.zig");

test "" {
  _ = main.i;
}
```

Running `zig test test/crashing_test.zig` gives this:
```
Assertion failed: (mem_len != SIZE_MAX), function buf_append_mem, file /Users/dbandstra/zig/src/buffer.hpp, line 108.
Abort trap: 6
```

If `main.zig` is also in the `test` folder, it works. This is breaking my `zig-pcx` and `oxid` projects (they both die with this assertion error).

**Comment by mikdusan** [comment]
I think this might be the culprit. When `@import` uses a relative path `add_source()` gets confused and assumes `resolved_root_src_dir` is a parent (common string prefix) to `noextname`. In this case the pointer math/size is wrong.

Was going to try and patch but don't have the high level view of what namespace_name should be in cases of { std/builtin, absolute, relative and sub } and what happens if Tld.name ends up duplicated?

https://github.com/ziglang/zig/blob/764205ac13cc340ff6dcce74667c32dafe24e510/src/analyze.cpp#L4507-L4512

**Comment by andrewrk** [comment]
After the above commit:

```
[nix-shell:~/dev/zig/build]$ ./zig test foo/a.zig 
/home/andy/dev/zig/build/foo/a.zig:1:11: error: import of file outside package path: '../b.zig'
const b = @import("../b.zig");
          ^

[nix-shell:~/dev/zig/build]$ ./zig test foo/a.zig --main-pkg-path ../
Test 1/1 oaeu...OK
All tests passed.
```

So the idea here is that you'll have to map your packages in as packages, or you'll have to choose an explicit root directory for the main package. It's no longer supported to `@import` a file from the file system that does not belong to a package.

**Comment by likern** [comment]
> After the above commit:
> 
> ```
> [nix-shell:~/dev/zig/build]$ ./zig test foo/a.zig 
> /home/andy/dev/zig/build/foo/a.zig:1:11: error: import of file outside package path: '../b.zig'
> const b = @import("../b.zig");
>           ^
> 
> [nix-shell:~/dev/zig/build]$ ./zig test foo/a.zig --main-pkg-path ../
> Test 1/1 oaeu...OK
> All tests passed.
> ```
> 
> So the idea here is that you'll have to map your packages in as packages, or you'll have to choose an explicit root directory for the main package. It's no longer supported to `@import` a file from the file system that does not belong to a package.

@andrewrk How to fix this exact issue? Can't find a solution.

I want to test one file `zig test src/io/File.zig` which should import `src/helper/strings.zig`. And only in `test` section I call this `helper.generate_file_name()`.

**Comment by mikdusan** [comment]
> I want to test one file `zig test src/io/File.zig` which should import `src/helper/strings.zig`. And only in `test` section I call this `helper.generate_file_name()`.

`zig test src/io/File.zig` defaults the main package path to `src/io/.` . For your case, override with `src/.` which is the common parent dir →  `zig test --main-pkg-path src/. src/io/File.zig`

notes:
- I use `src/.` for illustrative purposes, it can just be `src`
- you can select _any_ common parent dir, and in this case `.` would work but making it reasonably confined is a good idea

**Comment by likern** [comment]
@mikdusan Thank you. I probably solved my problem with this code in `build.zig`. I asked how to do this automatically, so just `zig test <file>` kept working.

This code below worked for me.

```zig
    const main_tests = b.addTest("src/main.zig");
    main_tests.setBuildMode(mode);

    // added these 2 lines
    const utils_test = b.addTest("src/utils/Utils.zig");
    utils_test.setBuildMode(mode);

    const test_step = b.step("test", "Run library tests");
    test_step.dependOn(&main_tests.step);
    // added this line
    test_step.dependOn(&utils_test.step);
```
