### ISSUE TITLE
@typeName on slices segfaults

### ISSUE THREAD

**Issue by hcff** [ziglang/zig#2026]
```zig
pub fn main() void {
    @compileLog([]u8);
    _ = @typeName([]u8);
}
```

```
| []u8
Segmentation fault (core dumped)
```

This also happen with `[]bool`, but not with `[*]u8`.

From a quick look with gdb, it seems that `ir_analyze_instruction_type_name` calls `type_bare_name` to get the type name.
```c++
Buf *type_bare_name(ZigType *type_entry) {
    if (is_container(type_entry)) {
        return get_container_scope(type_entry)->bare_name;
    } else if (type_entry->id == ZigTypeIdOpaque) {
        return type_entry->data.opaque.bare_name;
    } else {
        return &type_entry->name;
    }
}
```

Slices have `ZigTypeIdStruct` as an id, so `is_container(type_entry)` is true, so instead of returning a perfectly valid `&type_entry->name`, it does`get_container_scope(type_entry)->bare_name`, when `type_entry->data.structure.decls_scope` is null.

**Comment by andrewrk** [comment]
Thanks for the report! Fixed
