### ISSUE TITLE
Idiosyncrasy with function argument

### ISSUE THREAD

**Issue by part1zano** [ziglang/zig#20264]
### Zig Version

0.14.0-dev.429+65a145755

### Steps to Reproduce and Observed Behavior

Suppose we're having a program like the following:
```
const std = @import("std");
const csignal = @cImport({
    @cInclude("signal.h");
});

const stdout = std.io.getStdOut().writer();

var run: bool = true;

pub fn sighandler(signum: c_int) callconv(.C) void {
    stdout.print("caught signal {d}\n", .{signum}) catch return;
    run = false;
}

pub fn main() !void {
    csignal.signal(csignal.SIGINT, sighandler.?);
/// what's next doesn't really matter
```

What if we run `zig build`? The following:

```
src/main.zig:16:46: error: expected optional type, found 'fn (c_int) callconv(.C) void'
    csignal.signal(csignal.SIGINT, sighandler.?);
                                   ~~~~~~~~~~^~
```

If I remove the `.?`, however, here's what I get:

```
src/main.zig:16:19: error: value of type '?*const fn (c_int) callconv(.C) void' ignored
    csignal.signal(csignal.SIGINT, &sighandler);
    ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.zig:16:19: note: all non-void values must be used
src/main.zig:16:19: note: to discard the value, assign it to '_'

```

What... is going on?

### Expected Behavior

There's a way to do this. Either this or that.

**Comment by rohlem** [comment]
I don't immediately see any relation between the first and the second error message.
The second error message tells you that the `signal` method call returns a non-void value.
You could assign this value to a variable, or use it in an expression:
`const signal_result = csignal.signal(csignal.SIGINT, &sighandler);`
If you don't care about the result, you should discard it:
`_ = csignal.signal(csignal.SIGINT, &sighandler);`

**Comment by Vexu** [comment]
The error message is telling you what to do. `csignal.signal` returns a non void value which must be used. To use the value you can discard it by assigning it to `_` like
```zig
_ = csignal.signal(csignal.SIGINT, &sighandler);
```

**Comment by part1zano** [comment]
I see, thank you for that!

That says a lot about that error message, doesn't it? Maybe add a note that says something like `Did you mean to use _ = ...?`

**Comment by Vexu** [comment]
That's what the second note is trying to tell you `note: to discard the value, assign it to '_'`.

**Comment by part1zano** [comment]
Yeah, no: it's not telling me that. A better one would be `to discard return value of <whatever I'm trying to call>, assign it to '_'`

**Comment by mlugg** [comment]
The error message here is definitely fine. It's underlining the exact problematic expression, explaining that you're ignoring its value, and specifying how you can discard it if you want.

**Comment by rohlem** [comment]
@part1zano The circumflex `^` and tildes / squiggly lines `~` underline the expression the error message is referring to (in this case the function call, which is the entire statement content).
```
src/main.zig:16:19: error: value of type '?*const fn (c_int) callconv(.C) void' ignored
    csignal.signal(csignal.SIGINT, &sighandler);
    ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

> `to discard return value of <whatever I'm trying to call>, assign it to '_'`

It sounds like you are suggesting to (A) special case compile error messages when to refer to return values, and (B) to repeat the underlined part within the note.
I can see how that would make this particular case even more clear, however it would also increase the length and specificity of this error message (and for consistency, all other error messages).

I assume the Zig project doesn't want to make that tradeoff currently (confirmed by the comment above while I was typing this one);
maybe you could try out tooling integration like [`ZLS`](https://github.com/zigtools/zls), and suggest a change there if you don't like the ergonomics currently offered.
