### ISSUE TITLE
LIBRARY_PATH is not considered by the build system on Windows

### ISSUE THREAD

**Issue by Guigui220D** [ziglang/zig#20295]
### Zig Version

0.14.0-dev.27+0cef727e5

### Steps to Reproduce and Observed Behavior

As far as I understand, the LIBRARY_PATH environment variable is what GCC uses and is supposed to work on Windows, but it doesn't. Apart from that there is really no standard environment variable for libraries for linkers, am I wrong?

My workaround was parsing the environment variable from my build.zig but absolute paths are discouraged.

### Expected Behavior

The linker should use the absolute paths present in the LIBRARY_PATH environment variable.

**Comment by rohlem** [comment]
I don't know whether Zig plans to support automatically reading library search paths from a `LIBRARY_PATH` environment variable. I think this would make the build process less reproducible, and easier for some unexpected interaction to happen.

Note that you can already specify library search paths using the `-L`/`--library-directory` CLI options (see `zig <command> --help` for whatever command you're using your build process).
With this it should already be possible to manually specify the value of any environment variable to the CLI.

**Comment by Guigui220D** [comment]
Some environment variables are already taken in account like C_INCLUDE_PATH, though

**Comment by Guigui220D** [comment]
@rohlem also that is already the case on linux: https://github.com/ziglang/zig/blob/82a934bb912241809ac8029e1fa5843092a7fdf6/lib/std/zig/system/NativePaths.zig#L161

**Comment by andrewrk** [comment]
This is not a planned feature.
