### ISSUE TITLE
New compiler crash in some typeInfo code

### ISSUE THREAD

**Issue by dbandstra** [ziglang/zig#2030]
Here is a reduced reproduction. This code was not crashing a week ago, I believe. Maybe something to do with typeInfo now using comptime_ints.
```
const std = @import("std");

const Struct = struct{
  cdOffset: u32,
};

test "" {
  const field = @typeInfo(Struct).Struct.fields[0];

  // this `orelse 0` seems to be the problem
  _ = field.offset orelse 0;
}
```
Error:
```
unreachable: /Users/dbandstra/zig/src/ir.cpp:buf_read_value_bytes:21196
```

**Comment by Sahnvour** [comment]
When switching to comptime_ints, I noticed that running the test suite with the debug build of the compiler triggered an assert, before my changes. I forgot to make an issue about it ; maybe the change interacts with it.
