### ISSUE TITLE
`@embedFile` adds carriage return `\r` when compiled on windows

### ISSUE THREAD

**Issue by IntegratedQuantum** [ziglang/zig#20316]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

Use `@embedFile` to embed a text file, [this contains the exact file that caused the behavior](https://github.com/user-attachments/files/15857146/unscii-16.hex.zip)
```zig
const rawFontData = @embedFile("unscii-16.hex");
std.log.info("{any}", .{rawFontData[0..1000});
```
The log output contains a carriage return character `13` before every newline `10`:
```
[info]: { 48, 48, 48, 48, 48, 58, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 13, 10, 48, 48, 48, 4...
```
Note that works fine when cross-compiling from linux to windows. The program must be compiled on a windows machine for this problem to occur.

### Expected Behavior

In my opinion `@embedFile` should reproduce the file exactly, without adding junk characters.
But if this is intended behavior then it should at least be documented and have the same behavior when cross-compiled.

**Comment by leecannon** [comment]
This could be caused by git's autocrlf, are you sure the file on windows does not actually have carriage returns?

**Comment by IntegratedQuantum** [comment]
Yeah, it seems you are correct. The file in question did contain carriage returns on windows. That's so stupid.
I guess I can close this then.
