### ISSUE TITLE
Unhelpful "Unexpected" on Windows + network drive

### ISSUE THREAD

**Issue by Pistahh** [ziglang/zig#20325]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Output

* Windows 10
* Linux Samba share mounted as D:
* Create and compile an empty project

```
D:\>mkdir wintest

D:\>cd wintest

D:\wintest>zig init
info: created build.zig
info: created build.zig.zon
info: created src\main.zig
info: created src\root.zig
info: see `zig build --help` for a menu of options

D:\wintest>zig build

D:\wintest>zig build run
error: Unexpected
```

### Expected Output

Something that actually tells what is wrong :)

**Comment by squeek502** [comment]
Might be a duplicate of https://github.com/ziglang/zig/issues/19785 which was fixed by https://github.com/ziglang/zig/pull/19804 but didn't make it in on time for 0.13.0. Could you try the latest master version of Zig to see if that fixes it for you?

**Comment by Pistahh** [comment]
bingo, it works with latest master. Thank you.
