### ISSUE TITLE
False sharing threadlocal variables 

### ISSUE THREAD

**Issue by Szwagi** [ziglang/zig#20333]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

Threadlocal variables get allocated on the same cache line as threadlocal variables on other threads causing false sharing.
Manually aligning a block of variables to the size of cache line can fix this, but it wastes memory if it's done in multiple files.

Zig version: 0.13.0
OS: Windows 10
Target: x86_64

### Expected Behavior

They should never be on the same cache line.

**Comment by andrewrk** [comment]
Please provide steps to reproduce. I remember implementing this such that TLS areas are on entirely separate pages.

**Comment by alexrp** [comment]
> I remember implementing this such that TLS areas are on entirely separate pages.

For context:

https://github.com/ziglang/zig/blob/b470d2a7de20f8036c8976ec18ed1fb16a15c662/lib/std/Thread.zig#L1255-L1297

Maybe @Szwagi is linking glibc or musl, thus getting their TLS implementation, and that has the problem? :shrug: If that's the case, there's not much for us to do about it.

**Comment by Szwagi** [comment]
> Maybe @Szwagi is linking glibc or musl, thus getting their TLS implementation, and that has the problem? 🤷 If that's the case, there's not much for us to do about it.

I retested and this is the case.

**Comment by andrewrk** [comment]
You're linking glibc or musl on Windows 10?

**Comment by Szwagi** [comment]
> You're linking glibc or musl on Windows 10?

I'm using `exe.linkLibC();` in my build script, which I'm assuming links LLVM's libc. 
When answering I assumed this has the same implications as glibc or musl.
