### ISSUE TITLE
[RFC] Primitive types should be in TitleCase

### ISSUE THREAD

**Issue by surajbarkale** [ziglang/zig#2034]
The style guide says that user defined types should be in TitleCase. However, all built-in types are snake_case. In my opinion, it would improve readability if *all* types were TitleCase.

There is precedence of Swift language which has TitleCase names for all types (Int32, Float80, CWideChar, etc). Swift is also interesting in this regard as the basic type is `struct` or `class` and all other types (even primitives) are derived from it.

Specifically this will change following definitions:

| Current Name | Proposed Name |
|--------------|---------------|
| i8 | I8 |
| u8 | U8 |
| i16 | I16 |
| u16 | U16 |
| i32 | I32 |
| u32 | U32 |
| i64 | I64 |
| u64 | U64 |
| i128 | I128 |
| u128 | U128 |
| isize | ISize |
| usize | USize |
| c_short | CShort |
| c_ushort | CSshort |
| c_int | CInt |
| c_uint | CUInt |
| c_long | CLong |
| c_ulong | CULong |
| c_longlong | CLongLong |
| c_ulonglong | CULongLong |
| c_longdouble | CLongDouble |
| c_void | CVoid |
| f16 | F16 |
| f32 | F32 |
| f64 | F64 |
| f128 | F128 |
| bool | Bool |
| void | Void |
| noreturn | NoReturn |
| type | Type |
| anyerror | AnyError |
| comptime_int | ComptimeInt |
| comptime_float | ComptimeFloat |

**Comment by emekoi** [comment]
what about `var` and function pointers like `fn(usize) void`?

**Comment by PavelVozenilek** [comment]
This would require switching to uppercase and then back every, while having no positive impact on readability.

**Comment by surajbarkale** [comment]
I guess we should remove `type` from the list since it is a keyword.

**Comment by tgschultz** [comment]
I get where this change is coming from, but I personally don't feel good about it. Maybe it is years of Java speaking, but built-in primitives are different than user constructed types and I think that should be reflected by the styling.

**Comment by andrewrk** [comment]
I'll note that primitive types are also special in that they are not namespaced with `@`.

**Comment by hryx** [comment]
Font dependent, the readability of I16 and I128 is particularly damning.

**Comment by andrewrk** [comment]
Thanks for the proposal. It's a reasonable proposal. I'm ambivalent, I think there are good arguments either way. I'm just going to make the call to stick with status quo, keep the primitives lowercase. When in doubt, I'll match C & Rust rather than Swift.
