### ISSUE TITLE
Structs are bigger when compiling with zig master vs 0.12.0

### ISSUE THREAD

**Issue by GiuseppeCesarano** [ziglang/zig#20425]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

I'm working on a little toy project and i have struct-file with the following fields.

Token.zig:
```zig
type: Type,
location: Location,
data: Data,

pub const Location = packed struct {
    line: u32,
    row: u32,
    len: u16,
};

pub const Data = union {
    number: u32,
    index: u32,
    byte: u8,
};

pub const Type = enum(u8) {
    // ...
}
```

When compiling with zig 0.12.0 this struct has a size of 192 bits, but when compiling with zig 0.13.0 (or even 0.14.0-dev.121+ab4c461b7) this struct has a size of 256 bits. This leads to this benchmark result:
```
Benchmark 1 (6 runs): ./zig-out/bin/old68 random_file.txt
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           873ms ± 2.21ms     871ms …  876ms          0 ( 0%)        0%
  peak_rss           1.94GB ± 3.08KB    1.94GB … 1.94GB          0 ( 0%)        0%
  cpu_cycles         3.43G  ± 5.63M     3.42G  … 3.44G           0 ( 0%)        0%
  instructions       7.11G  ± 1.17      7.11G  … 7.11G           0 ( 0%)        0%
  cache_references   66.1M  ± 77.5K     66.0M  … 66.2M           0 ( 0%)        0%
  cache_misses       10.3M  ± 22.6K     10.3M  … 10.3M           0 ( 0%)        0%
  branch_misses      47.3M  ± 88.8K     47.2M  … 47.4M           0 ( 0%)        0%
Benchmark 2 (6 runs): ./zig-out/bin/l68 random_file.txt
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           901ms ± 2.33ms     899ms …  904ms          0 ( 0%)        💩+  3.2% ±  0.3%
  peak_rss           2.45GB ± 3.08KB    2.45GB … 2.45GB          0 ( 0%)        💩+ 26.4% ±  0.0%
  cpu_cycles         3.42G  ± 10.8M     3.41G  … 3.43G           0 ( 0%)          -  0.3% ±  0.3%
  instructions       7.11G  ± 16.5      7.11G  … 7.11G           0 ( 0%)          +  0.1% ±  0.0%
  cache_references   83.2M  ± 56.5K     83.1M  … 83.3M           0 ( 0%)        💩+ 25.9% ±  0.1%
  cache_misses       10.6M  ± 46.7K     10.6M  … 10.7M           0 ( 0%)        💩+  3.2% ±  0.5%
  branch_misses      47.0M  ±  226K     46.8M  … 47.4M           0 ( 0%)          -  0.6% ±  0.5%
``` 
Note that `old68` is compiled with zig 0.12.0, `l68` with zig 0.13.0; there are no changes to the code. If more context is needed i can make the repository public.

### Expected Behavior

I think the newer zig versions should act as zig 0.12.0, giving the smaller size struct. If this is the expected outcome instead, it would be good to have an option for users to enable the old behavior.

**Comment by travisstaloch** [comment]
As a workaround to get the bit size back down to 192 in release small and fast builds, you could specify the alignment of the location field:

```zig
const std = @import("std");

type: Type,
location: Location align(8),
data: Data,

pub const Location = packed struct {
    line: u32,
    row: u32,
    len: u16,
};

pub const Data = union {
    number: u32,
    index: u32,
    byte: u8,
};

pub const Type = enum(u8) {
    // ...
};

test {
    try std.testing.expectEqual(192, @bitSizeOf(@This()));
}
```

**Comment by GiuseppeCesarano** [comment]
Thanks for the suggestion, I will do that! But I hope that some way of requiring a packed file-struct is added to the language, because playing with field's alignment to achieve that is counterintuitive.

**Comment by mlugg** [comment]
Not a bug. With the upgrade to LLVM 18 we had to slightly change the ABI for 128-bit integers, which hence also means that `u72` -- the backing type for `Location` -- has 128-bit (16-byte) alignment. This increased alignment requirement means that the file-level struct here cannot be 24 bytes; it must be increased to 32.

Making `Location` a `packed struct` definitely does not seem to be the right tool for the job here, because you aren't trying to bit-pack data. Use a `struct` or -- if you need well-defined memory layout -- an `extern struct`.

**Comment by GiuseppeCesarano** [comment]
You're right, the packed struct wasn't the right tool there, i was just trying to not make the compiler take the extra 2 bytes to align `Location` once removed the `packed` from the struct, the benchmark is actually crazy better

```Benchmark 1 (6 runs): ./zig-out/bin/old68 random_file.txt
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           907ms ± 8.83ms     900ms …  924ms          0 ( 0%)        0%
  peak_rss           2.45GB ± 52.8KB    2.45GB … 2.45GB          1 (17%)        0%
  cpu_cycles         3.43G  ± 11.5M     3.42G  … 3.45G           0 ( 0%)        0%
  instructions       7.02G  ± 15.4      7.02G  … 7.02G           0 ( 0%)        0%
  cache_references   85.8M  ± 1.86M     83.4M  … 87.2M           0 ( 0%)        0%
  cache_misses       10.7M  ± 23.1K     10.6M  … 10.7M           0 ( 0%)        0%
  branch_misses      47.1M  ±  214K     46.9M  … 47.4M           0 ( 0%)        0%
Benchmark 2 (6 runs): ./zig-out/bin/l68 random_file.txt
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           869ms ± 12.1ms     859ms …  892ms          0 ( 0%)        ⚡-  4.2% ±  1.5%
  peak_rss           1.68GB ± 51.6KB    1.68GB … 1.68GB          1 (17%)        ⚡- 31.3% ±  0.0%
  cpu_cycles         3.48G  ± 52.2M     3.45G  … 3.58G           0 ( 0%)          +  1.5% ±  1.4%
  instructions       6.97G  ± 24.9      6.97G  … 6.97G           0 ( 0%)          -  0.7% ±  0.0%
  cache_references   58.8M  ± 1.03M     57.6M  … 59.8M           0 ( 0%)        ⚡- 31.4% ±  2.3%
  cache_misses       10.0M  ± 20.7K     10.0M  … 10.1M           0 ( 0%)        ⚡-  6.1% ±  0.3%
  branch_misses      47.8M  ±  455K     47.4M  … 48.6M           0 ( 0%)          +  1.6% ±  1.0% 
  ```
  
  Both compiled with zig 0.13.0, the only difference is the removal of packed, now the struct is only 160 bit!
  Sorry if i wasted your time but for me was truly not expected behavior that the struct simply took more space.

**Comment by mlugg** [comment]
No problem. The use cases for `packed struct` are relatively few -- it's pretty much exclusively for bit-packing, with the most notable usage being bitflags.
