### ISSUE TITLE
It's unclear which minimum Linux kernel version the Zig standard library actually supports

### ISSUE THREAD

**Issue by alexrp** [ziglang/zig#20423]
https://github.com/ziglang/zig/blob/3e9ab6aa7b2d90c25cb906d425a148abf9da3dcb/lib/std/Target.zig#L369-L370
https://github.com/ziglang/zig/blob/3e9ab6aa7b2d90c25cb906d425a148abf9da3dcb/lib/std/Target.zig#L486-L494

Yet [the release notes say Linux 3.16+](https://ziglang.org/download/0.13.0/release-notes.html#Tier-1-Support).

Mainly bringing this up because I came across this code:

https://github.com/ziglang/zig/blob/3e9ab6aa7b2d90c25cb906d425a148abf9da3dcb/lib/std/fs/File.zig#L1020-L1037

And:

```console
❯ man statx|grep 'was added'
       statx() was added in Linux 4.11; library support was added in glibc 2.28.
```

**Comment by andrewrk** [comment]
https://github.com/ziglang/zig/commit/0d4d8dfc1583138a59147f1aab5eec803a23adb1

I neglected to update the release notes.

**Comment by alexrp** [comment]
Closing since this was cleared up in #20389. @andrewrk probably want to label this issue for release notes?
