### ISSUE TITLE
Test encapsulation and statics variables

### ISSUE THREAD

**Issue by kALLEBALIK** [ziglang/zig#20432]
### Zig Version

0.12.1

### Steps to Reproduce and Observed Behavior

Right now "static variables" live on between tests.
  
  This is is some simple test code to test the behaviour.
```zig
const std = @import("std");
pub fn static() u32 {
    const static_data = struct {
        var value: u32 = 0;
    };
    static_data.value += 1;
    return static_data.value;
}
const testing = std.testing;
test "test1" {
    const val1 = static();
    const val2 = static();
    try testing.expectEqual(1, val1);
    try testing.expectEqual(2, val2);
}
test "test2" {
    const val1 = static();
    const val2 = static();
    try testing.expectEqual(1, val1); // fails, expected 1, found 3
    try testing.expectEqual(2, val2);
}
```

### Expected Behavior

I would expect that "static variables" would be encapsulated, but right now they are set and then live on between tests. This is problematic when trying to validate test results. Maybe this is just the problematic nature of static variables, but they are  in the language and right now it's very hard to test code depending on it.

**Comment by andrewrk** [comment]
working as designed
