### ISSUE TITLE
Float convertion to string in std.debug.print seems to be broken

### ISSUE THREAD

**Issue by HaraldWik** [ziglang/zig#20437]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

**Disclaimer** I'm very new to Zig, but I think this might be a litle wrong
---
```
const std = @import("std");

const hello: f32 = 20.49;

pub fn main() !void {
    std.debug.print("the number is {}\n", .{hello});
}
```
And then I run 
`zig build && ./zig-out/bin/project_name`

and then it prints 
`the number is 2.049e1`

---
### INFO
I'm on _Linux Lite_ witch is **Debian** based

I'm using the **x86_64** version
---

### Expected Behavior

I thought it whould print "the number is 20.49" instead of "the number is 2.049e1"

**Comment by squeek502** [comment]
Not broken, `e` is just the default formatting for floats. Use `{d}` if you want it to be formatted as a decimal number.

https://github.com/ziglang/zig/blob/cb308ba3ac2d7e3735d1cb42ef085edb1e6db723/lib/std/fmt.zig#L59-L60

```const std = @import("std");

const hello: f32 = 20.49;

pub fn main() !void {
    std.debug.print("default: {}\n", .{hello});
    std.debug.print("      d: {d}\n", .{hello});
    std.debug.print("      e: {e}\n", .{hello});
}
```

outputs:

```
default: 2.049e1
      d: 20.49
      e: 2.049e1
```

**Comment by HaraldWik** [comment]
Ok thx!
