### ISSUE TITLE
improve caching system invalidation for file systems with weaker guarantees

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2045]
On modern file systems, mtime has nanoseconds as well as seconds, which is a pretty dang reliable method of determining whether a file's contents has changed, even if it's not technically correct (what if your code/OS was SO FAST that it did multiple things in a nanosecond). Zig uses this in the caching system to find out when we can rely on the saved file contents hash rather than recomputing it. (Of course it does an equality comparison and not a greater-than comparison.)

However we're not guaranteed to have nanoseconds (or even seconds, depending what file system!). Notably, on the macOS CI server, it uses HFS+ and not the newer APFS, which only has second resolution for modification times.

Here's a well-written blog post articulating everything that can go wrong, and explaining the author's approach in their own project: https://apenwarr.ca/log/20181113

In it I have found 3 suggestions that, together, fully solve the problem.

 * In addition to mtime, note the inode number. This will detect when a file is renamed into place.
 * When looking at a file that is a cache miss, after doing the fstat and looking at the mtime, also look at the clock time. If a modification at this instant would not change the mtime, then we consider the mtime as unreliable. The caching system will have to check the hash next time as well as this time. This requires being able to determine the resolution of the modification time. I think the most conservative solution to this would be to look for zeroes in the least significant digits of the time. (e.g. a nanoseconds value of 0 would mean we do not have nanoseconds available). This is a great solution because it means that on file systems that have higher resolution, we avoid expensive hash computation always. On file systems with lower resolution, we are forced to do the hash computation only within the time window of the file system resolution (e.g. 1 second on HFS+). Once a file becomes older than e.g. 1 second, then mtime based caching starts working. Also note this generalizes to nanoseconds too. So the "technically" thing above is also solved.

Finally, in addition to mtime and inode number, also note the file size. This shouldn't be necessary, but we basically get it for free with the same fstat call, and as the author of the above blog post notes:

> If your source files are in a braindead fuse filesystem, redo can use inode number and size to detect changes (although it still sucks and you should fix your fuse filesystem).

**Comment by kristate** [comment]
Thanks for writing this up.

After our talk on [IRC](https://freenode.irclog.whitequark.org/zig/2019-03-09), I also did some research and found [this article](http://www-cs-students.stanford.edu/~blynn/gg/race.html) about what [`git` does](https://github.com/git/git/blob/32038fef00b02fb52f362d1d0cf1c25c6c382abb/read-cache.c#L396-L411) in this scenario.

Also, it would be nice if you could give due credit from time-to-time :-)
We're all here to make zig great.

```
16:27 <kristate_> andrewrk: shouldn't we check hashes if mtime is the same? 
16:27 <andrewrk> kristate_, the whole point of mtime is to avoid the cost of hashing the file 
16:28 <kristate_> andrewrk: right -- if mtime is the same, then we could revert to hasing 
16:28 <kristate_> hashing 
16:30 <andrewrk> that doesn't avoid the cost of hashing the file on cache hit 
16:31 <kristate_> andrewrk: ah, to clarify, we could do it only if tv_nsec was 0 
16:31 <andrewrk> that's an interesting idea 
```

**Comment by andrewrk** [comment]
@kristate thank you for finding the article and the Git source code. It looks like Git does the approach outlined above.

If you had suggested this approach in the IRC conversation before, I certainly would have given you credit. But you didn't. Credit is actually due exactly to whom I credited it - the author of the blog post mentioned above.

Your comment contains off-topic and false information, and so I am hiding it. I am also hiding this comment, which is also off topic. So please do not respond to it. However, I invite you to repeat your very much on-topic sentence about the article you found and the git source code.
