### ISSUE TITLE
`zig version` on 0.13 built with MacPorts spits warning about incorrect linkage

### ISSUE THREAD

**Issue by i0ntempest** [ziglang/zig#20450]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

`zig version` gives
```
0.13.0
error: Zig was built/linked incorrectly: LLVM and Clang have separate copies of libc++
       If you are dynamically linking LLVM, make sure you dynamically link libc++ too
```
The binary is built from this portfile: https://github.com/macports/macports-ports/pull/24430

### Expected Behavior

The compiler seems to work fine, but I would expect a more useful warning message than this. I don't know if this is triggered by how MacPorts installs LLVM and Clang. What do I need to do to get rid of this warning?

**Comment by i0ntempest** [comment]
Hello? Anyone can help out here?

**Comment by alexrp** [comment]
Best guess is that they're linking libc++ into LLVM/Clang statically, but it's hard for us to really know. Bottom line is that you somehow have two libc++ libraries loaded into the Zig process.

**Comment by i0ntempest** [comment]
I noticed the `zig` binary has rpath style links to llvm libraries:
```
$ otool -L /opt/local/bin/zig 
/opt/local/bin/zig:
	@rpath/libclang-cpp.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libLLVM.dylib (compatibility version 1.0.0, current version 18.1.7)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.3.1)
	/opt/local/lib/libzstd.1.dylib (compatibility version 1.0.0, current version 1.5.6)
	/opt/local/lib/libncurses.6.dylib (compatibility version 6.0.0, current version 6.0.0)
	/opt/local/lib/libxml2.2.dylib (compatibility version 15.0.0, current version 15.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.100.2)
```
I have multiple llvm/clang versions on my system but the binary only has llvm18 in its rpaths:
```
otool -l /opt/local/bin/zig | grep -i path
          cmd LC_RPATH
         path /opt/local/libexec/llvm-18/lib (offset 12)
          cmd LC_RPATH
         path /opt/local/libexec/llvm-18/lib (offset 12)
          cmd LC_RPATH
         path /opt/local/libexec/llvm-18/lib (offset 12)
          cmd LC_RPATH
         path /opt/local/lib (offset 12)
         name @rpath/libclang-cpp.dylib (offset 24)
         name @rpath/libLLVM.dylib (offset 24)
```
Does this indicate possible linkage problems?

**Comment by alexrp** [comment]
You would need to find out if that `libLLVM.dylib` or `libclang-cpp.dylib` has its own statically-linked copy of libc++. (I'm not familiar enough with macOS to suggest how, unfortunately.)

**Comment by i0ntempest** [comment]
I've checked and both of them dynamically links to `/usr/lib/libc++.1.dylib` so I don't think they're statically linking libc++. @ryandesign @reneeotten Can you please take a look at this?

**Comment by alexrp** [comment]
At that point, it might be the Zig compiler itself that has statically linked libc++. That actually seems more likely, looking at the `otool` output above. I have no idea how that would have happened, though.

Maybe you can check if it has internal libc++ symbols or something?

**Comment by kencu** [comment]
this issue may have been fixed by

https://github.com/macports/macports-ports/commit/a1d4865220b53c446adbcb4856f80f46029e2e8d

macports previously built and installed a new copy of libc++.dylib in a default directory specified by llvm. 

This new copy of libc++.dylib was often found opportunistically.

The new copy of libc++.dylib is now tucked into a subdirectory, so it is found only if specifically added.

**Comment by i0ntempest** [comment]
I made sure I have only v18 of llvm and clang active on my system and rebuilt zig, but nope. The new binary still gives the error.

**Comment by andrewrk** [comment]
This must be fixed by macports. There is nothing for Zig project to do.

**Comment by cho-m** [comment]
> At that point, it might be the Zig compiler itself that has statically linked libc++. That actually seems more likely, looking at the `otool` output above. I have no idea how that would have happened, though.

This sounds right given bundled `libc++.a` and `libstdc++.a` is always used:

https://github.com/ziglang/zig/blob/4cefd1bd1bac7059f7e00162a579f659e5f59412/build.zig#L787-L788

https://github.com/ziglang/zig/blob/4cefd1bd1bac7059f7e00162a579f659e5f59412/src/link/MachO.zig#L450-L455

---

There doesn't seem to be an easy way of enabling shared LLVM on macOS that doesn't result in conflict warning.

The workaround would be patching build.zig to change above line and force linkage to correct libc++.

**Comment by onion108** [comment]
> Got the same message today on my Mac after `brew upgrade` updated `zig` from 0.13.0 to 0.14.0
> 
> > zig version
> 0.14.0
> error: Zig was built/linked incorrectly: LLVM and Clang have separate copies of libc++
>        If you are dynamically linking LLVM, make sure you dynamically link libc++ too

so do i

**Comment by carlocab** [comment]
Should be fixed by https://github.com/ziglang/zig/pull/23264. See discussion at https://github.com/Homebrew/homebrew-core/pull/210173.
