### ISSUE TITLE
Misaligned struct field on 32-bit Windows 

### ISSUE THREAD

**Issue by chung-leong** [ziglang/zig#20469]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

const S = struct {
    pointer: *u64,
    value: u64,
};

pub fn main() void {
    inline for (@typeInfo(S).Struct.fields) |field| {
        std.debug.print("{s}: {d}\n", .{ field.name, @offsetOf(S, field.name) });
    }
    var s: S = .{ .pointer = @ptrFromInt(0x1000), .value = 1234 };
    _ = &s;
    std.debug.print("{d}\n", .{@intFromPtr(&s)});
    std.debug.print("{d}\n", .{@intFromPtr(&s.value)});
}
```
```
$ zig run test.zig -target x86-windows
pointer: 0
value: 4
35650232
35650240
```
For some reason, `@alignOf(u64)` is now 4 on 32-bit Windows (0.12.0 reports 8). Elsewhere the compiler still thinks it's 8 apparently, so the pointer calculation is off.

### Expected Behavior

It depends on whether `@align(u64)` = 4 is actually correct. If that's intended behavior, then the expected result should be: 
```
pointer: 0
value: 4
35650232
35650236  <-- correct offset
```
If the alignment is supposed to be 8, then the expected result is:

```
pointer: 4
value: 0
35650232
35650232
```

**Comment by squeek502** [comment]
Seems likely to be related to (or the cause of) https://github.com/ziglang/zig/issues/20047

**Comment by squeek502** [comment]
Result for the `x86-linux` target:

```
pointer: 0
value: 4
4290740068
4290740072
```

**Comment by whatisaphone** [comment]
We're running into this and found an easy workaround: add `align(8)` after the u64 field.

Going deeper, it seems any alignment except 4 fixes it. I'd rather use 4 since that's the correct alignment to use on x86, but the compiler seems to ignore when you redundantly write `align()` with a type's natural alignment.

**Comment by squeek502** [comment]
From what I can tell, the relevant commits that made `@alignOf(u64)` change to 4 for `x86-windows` are:

- 7e1cba73fc5dce195af2c5cc6a2a1427710ed3ed
- 200e06b2399d605c8d183e55649e39ba2c6b56f6

And the mismatch comes from this switch case in `typeAlignment` from `codegen/llvm.zig`:

https://github.com/ziglang/zig/blob/ddcb7b1c11f88c4ae150b36807033060a469dcb5/src/codegen/llvm.zig#L580-L583
