### ISSUE TITLE
Support hex floating point format in fmt.parseFloat and fmt.print

### ISSUE THREAD

**Issue by tiehuis** [ziglang/zig#2047]
We should support hexadecimal floating point values in `fmt.format` and `fmt.parseFloat`.

For example, the following should hold true.

```
std.testing.expectEqual(std.fmt.parseFloat(""0x1.999999999999ap-4"), 0.1);
```

For print as a hexidecimal, a `"{x}"` format specifier seems most appropriate. Related to https://github.com/ziglang/zig/issues/1358 but can be done independently.

**Comment by shawnl** [comment]
Ahh, the compiler cheats by using strtod()

**Comment by corona10** [comment]
@tiehuis @shawnl 

Hi devs, Is there any progress? Or can I take a look at this issue if no one works on it?

**Comment by tiehuis** [comment]
No progress on my end, and I am not aware of anyone working this. I think it'll be fine for you to work on this.

**Comment by corona10** [comment]
@tiehuis
Great! I will take a look!

**Comment by daurnimator** [comment]
@corona10 did you get anywhere with this?

**Comment by corona10** [comment]
@daurnimator Currently not, I will ping you if I am not able to work on this issue. Thanks!

**Comment by corona10** [comment]
@daurnimator If you have any progress with this issue, please handle this issue.  For me, this issue might need times.

**Comment by shawnl** [comment]
@corona10  look at this: https://en.wikipedia.org/wiki/Double-precision_floating-point_format

This is a great project for a beginning programmer. Feel free to ask questions on `#zig` irc channel.

**Comment by arBmind** [comment]
Both fmt.format and fmt.parseFloat already support hex floats.

@daurnimator This issue can be closed I guess.
