### ISSUE TITLE
LLVM Triple has extra section "unknown" hard coded

### ISSUE THREAD

**Issue by MikeColeGuru** [ziglang/zig#20486]
I have been trying to update llvm and recompile zig for use with xtensa.  
I got everything compiled. 
However, when I attempted to compile zig code I ended up with an extra section in the triple "unknown".

`xtensa-freestanding-none` was converted to `xtensa-unknown-unknown-unknown` for llvm.

```
$ zig build -Dtarget=xtensa-freestanding-none
install
└─ install simple
   └─ zig build-exe simple Debug xtensa-freestanding-none failure
error: error(codegen): LLVM failed to parse 'xtensa-unknown-unknown-unknown': Unable to find target for this triple (no targets are registered)
thread 84531 panic: Invalid LLVM triple
Unable to dump stack trace: debug info stripped
```

I found the offending line.  It seems to be adding an extra `unknown` instead of just a dash.
https://github.com/ziglang/zig/blob/4870e002f213d7002ac1941c6a204aff79137d54/src/codegen/llvm.zig#L109

**Comment by nektro** [comment]
its not a bug. llvm triples have a fourth field named "vendor" which zig intentionally leaves as 'unknown'
https://llvm.org/doxygen/classllvm_1_1Triple.html

**Comment by MikeColeGuru** [comment]
Then this may be a bug in Espressif/LLVM.  I believe they expect `xtensa-unknown-unknown` or just `xtensa`.
Okay, not a bug.  Closing.
