### ISSUE TITLE
CMake fails to detect ABI info with Zig cc/c++.

### ISSUE THREAD

**Issue by aikawayataro** [ziglang/zig#20493]
### Zig Version

0.14.0-dev.144+a31fe8aa3

### Steps to Reproduce and Observed Behavior

CMake passes `-v` linker flag during ABI info check causing Zig to fail with an error:

```
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b0cec.dir/link.txt --verbose=1
/home/user/zig/master/zig c++   -v -Wl,-v CMakeFiles/cmTC_b0cec.dir/CMakeCXXCompilerABI.cpp.o -o cmTC_b0cec
error: unsupported linker arg: -v
make[1]: *** [CMakeFiles/cmTC_b0cec.dir/build.make:100: cmTC_b0cec] Error 1
make[1]: Leaving directory '/home/user/Projects/zig-test/build/CMakeFiles/CMakeScratch/TryCompile-rryASJ'
make: *** [Makefile:127: cmTC_b0cec/fast] Error 2
```

While clang has no problem with this:

```
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_505f3.dir/link.txt --verbose=1
/usr/bin/clang  -v -Wl,-v CMakeFiles/cmTC_505f3.dir/CMakeCXXCompilerABI.cpp.o -o cmTC_505f3
clang version 17.0.6
Target: x86_64-pc-linux-gnu
...
```

Steps to reproduce:

Try to configure this CMake project:

```
cmake_minimum_required(VERSION 3.19)

project(zig_test LANGUAGES CXX C)
```

With zig cc/c++: `cmake . -DCMAKE_CXX_COMPILER=zig -DCMAKE_CXX_FLAGS=c++ -DCMAKE_C_COMPILER=zig -DCMAKE_C_FLAGS=cc`

You will observe these status messages: `Detecting CXX compiler ABI info - failed` and `Detecting C compiler ABI info - failed`
While it's not an error, it's easy to ignore. But without ABI info, CMake loses a lot of information that projects can depend on (a notable example is GNUInstallDirs, which depends on generated info to detect the LIBDIR), such as `CMAKE_SIZEOF_VOID_P`, `CMAKE_C_COMPILER_ABI`, `CMAKE_C_BYTE_ORDER` and many others.

Interestingly, the plain `-v` works as intended, but linker one fails. 

### Expected Behavior

`zig c++ -Wl,-v` works.

**Comment by JamesParrott** [comment]
There's a general preference for zig.build files over CMake.

To use CMake with `zig c++` anyway, I found an additional CMake tool chain file was necessary, e.g.:

https://github.com/mrexodia/zig-cross

**Comment by aikawayataro** [comment]
> There's a general preference for zig.build files over CMake.

zig cc was described as a "Powerful Drop-In Replacement for GCC/Clang", so I guess it is worth fixing this mere problem.

> but to get it working I found an additional CMake tool chain file was necessary, e.g.:

It's not really that necessary, in my case I only use zig cc.

> The way I'm running CMake, I can't see the zig command to check for the -v flag, but this is the output from the ABI checking stage, using Zig 0.14.0. I don't know what those failures are for, but whatever it does after that, CMake and zig c++ are able to build our project

As I said, this is not a fatal error. But a big problem if you use any of the variables mentioned, and many projects depend on it. It will compile programs, yes, until there's a dependency on those variables.

**Comment by aikawayataro** [comment]
There is already some "CMake awareness" in zig cc, so I believe having this fixed is good for Zig.

https://github.com/ziglang/zig/blob/bf588f67d8c6261105f81fd468c420d662541d2a/src/main.zig#L248-L250

https://github.com/ziglang/zig/blob/bf588f67d8c6261105f81fd468c420d662541d2a/src/main.zig#L2053-L2055

**Comment by JamesParrott** [comment]
That's great to know that CMake works for you a lot better with `zig cc`

> zig cc was described as a "Powerful Drop-In Replacement for GCC/Clang", so I guess it is worth fixing this mere problem.

That's a big claim, and I wouldn't have chosen that precise wording myself (as someone would inevitably be dissappointed).  I've still got things to figure out how to set up with it, so I don't think it's a batteries included drop-in.  But overall I was very impressed, and it really helped me port C++ from Visual Studio to gcc, going via `zig c++`.

The key thing to remember when reading "Powerful Drop-In Replacement for C++ compiler" is that a different C++ compiler is not even a drop in replacement for another one.  Testing on multiple compilers is a good way of ensuring code quality.  Even if a project uses Clang as the main compiler, `zig c++` might have different settings.

**Comment by rohlem** [comment]
> That's a big claim, and I wouldn't have chosen that precise wording myself (as someone would inevitably be dissappointed).

Well, `zig cc` and `zig c++` are a shim over `clang` under the hood.
The goal is to be an exact drop-in replacement for `clang`, so we want users to try it for their use cases in this way, so that they report issues for disparities that we can fix.

> The key thing to remember when reading "Powerful Drop-In Replacement for C++ compiler" is that a different C++ compiler is not even a drop in replacement for another one.

Right, that's why the exact wording talked about `clang` and `gcc`.
`clang` is itself aiming for compatibility with `gcc`, which is why so many of their CLI flags are the same, and so many gcc's features like language extensions are supported by `clang`.
Visual Studio / `cl.exe` on the other hand was developed in its own ecosystem, so there's plenty of differences.

**Comment by aikawayataro** [comment]
> I've still got things to figure out how to set up with it, so I don't think it's a batteries included drop-in. But overall I was very impressed, and it really helped me port C++ from Visual Studio to gcc, going via zig c++.

I think it might even be a different thing, but zig cc reports itself as Clang (since it's just a Clang wrapper, as @rohlem said). So I can expect it to support essential basic flags, like printing linker version (linker flags are different from compiler flags, but since Zig conveniently wraps not only a compiler but also a linker (lld), we can refer to it as a single tool). It is also worth mentioning that this flag (-v linker flag, which prints version without terminating linker) is somewhat "standard" (GNU ld behavior is followed by almost all other linkers, including LLVM's ld.lld which is used by Zig internally).
You can argue by opposing zig cc as something else, but why use a tool that can't be integrated into existing build systems? I (and many others, I believe) would expect compatibility with existing tooling and environments from "Powerful Drop-In Replacement".
I appreciate your way of thinking, but I think that "-v" was just missed. I can't see any real reason to oppose supporting a flag that prints the linker version (not to mention that there is already support for the "--version" flag).

**Comment by JamesParrott** [comment]
Me neither.  Perhaps no use was forseen for `-v` until now.
