### ISSUE TITLE
function locals should not count towards shadowing of container scoped function locals

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#20498]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

```zig
pub fn main() !void {
    const arguments = 0;
    _ = arguments;

    const S = struct {
        fn cb() void {
            const arguments = 0;
            _ = arguments;
        }
    };
    _ = S;
}
```

```
test.zig:7:19: error: local constant 'arguments' shadows local constant from outer scope
            const arguments = 0;
                  ^~~~~~~~~
test.zig:2:11: note: previous declaration here
    const arguments = 0;
          ^~~~~~~~~
```

### Expected Behavior

Zig does not have closures so all references here are unambiguous.

**Comment by mlugg** [comment]
Not a bug.

> Zig does not have closures so all references here are unambiguous.

Zig does not have *runtime* closures. If `arguments` is comptime-known, it can be closed over. Regardless of whether it is comptime-known, expressions like `@TypeOf(arguments)` can be closed over.
