### ISSUE TITLE
SIOCSIFFLAGS, SIOCGIFFLAGS missing from std.os.linux

### ISSUE THREAD

**Issue by kj4tmp** [ziglang/zig#20497]
### Zig Version

0.14.0-dev.66+1fdf13a14

### Steps to Reproduce and Observed Behavior

I am attempting to do some raw packet stuff with network interfaces, so I wanted to set promiscuous mode on a network interface.

In C, this would look like `ioctl(*psock, SIOCSIFFLAGS, &ifr)`. But the  `SIOCSIFFLAGS` constant is not currently available in the zig's `std.os.linux` to make this system call. 

I know the standard lib is a work in progress, just recording this ticket so it doesn't get lost.

### Expected Behavior

I expected std.os.linux to have these constants for working with `std.os.linux.ioctl`

**Comment by andrewrk** [comment]
those constants look gross, why can't they be named something more palatable

**Comment by kj4tmp** [comment]
fixed by 82b676ef798f8d7ae91af2f87dff0ffbfa0b4644
