### ISSUE TITLE
error unions are not namespaces

### ISSUE THREAD

**Issue by ityonemo** [ziglang/zig#20536]
unlike other types of containers, error unions are not namespaces, one can't embed a function into it.

For example, this works:

```
const Foo = enum {
  a, b,
  fn myfun() void {
    @import("std").debug.print("hey\n", .{});
  }
};

pub fn main() void {
   Foo.myfun();
}
```

but this does not:
```
const Foo = error {
  a, b,
  fn myfun() void {
    @import("std").debug.print("hey\n", .{});
  }
};

pub fn main() void {
   Foo.myfun();
}
```

Granted, error unions are special cases since they are compacted into a single type by the compiler at the end of compilation, so I doubt "first parameter is object method syntax" is viable for error unions, but the ability to at least have a namespace seems reasonable.

**Comment by mlugg** [comment]
Not a bug. If error *sets* (not unions!) were namespace types, we would lose a lot of type equivalences and would (due to things like error set merging and inferred error sets) hugely complicate the language for little to no gain. This will not happen.
