### ISSUE TITLE
Attempting to define a variable of anyopaque type shows no meaningful error

### ISSUE THREAD

**Issue by nothke** [ziglang/zig#20534]
### Zig Version

0.14.0-dev.144+a31fe8aa3

### Steps to Reproduce and Observed Output

Defining an anyopaque like
```
const a: anyopaque = undefined;
```
..clearly makes no sense, but the compiler doesn't show any error message for it except just failing.

https://godbolt.org/z/sx8c6zv4b

### Expected Output

Something like "Defining a constant/variable of anyopaque type is illegal"

**Comment by Rexicon226** [comment]
duplicate of #16617
