### ISSUE TITLE
How to determine zig type syntax for an imported type

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#2054]
I’m trying to annotate the var on this line with its correct type: https://github.com/andrewrk/tetris/blob/1fd392b5b70f4c471826222204c5dbb48ef535e8/src/png.zig#L21

So I tried :i32 to induce an error and the compiler reported that it was expecting

‘?*.cimport:1:9.struct_png_struct_def'

so the question is: what is the correct zig syntax to annotate this var with the correct type?

**Comment by andrewrk** [comment]
That does look a bit awkward. To answer your question though, you should be able to use `c.struct_png_struct_def`. You can build with `--verbose-cimport` and it will print something like this:

```
@cImport output: /home/andy/dev/tetris/zig-cache/o/h8hixClM-j7kEnBXKxdAHNv3sMrPVmdhM6ivX3FZQdZ9ijr0jnzgmNrBc0m8S-7H/cimport.zig
```

Which you can look at to determine what is in the file:

```zig
...
pub const struct_png_struct_def = @OpaqueType();
pub const png_struct = struct_png_struct_def;
pub const png_const_structp = ?*const png_struct;
pub const png_structp = ?*png_struct;
pub const png_structpp = [*c](?*png_struct);
...
```

**Comment by markfirmware** [comment]
Thank you - that works well.
