### ISSUE TITLE
std.json parses strings into numeric types

### ISSUE THREAD

**Issue by Rik-de-Kort** [ziglang/zig#20565]
### Zig Version

0.14.0-dev.32+4aa15440c

### Steps to Reproduce and Observed Behavior

```ts
const std = @import("std");

const PrimeInput = struct { method: *const [7]u8, number: i128 };

test "builtin json" {
    const any_string = "{\"method\":\"isPrime\",\"number\":\"hello\"}";
    try std.testing.expectError(error.InvalidCharacter, std.json.parseFromSlice(PrimeInput, std.testing.allocator, any_string, .{}));

    const illegal_quotes = "{\"method\":\"isPrime\",\"number\":\"1389564\"}";
    try std.testing.expectError(error.InvalidCharacter, try std.json.parseFromSlice(PrimeInput, std.testing.allocator, illegal_quotes, .{}));
}
```

### Expected Behavior

This test fails, but I don't think it should, since "1389564" is a string, not an integer.

**Comment by travisstaloch** [comment]
This is not a bug.  std.json intentionally supports 'number strings'.  I'm not sure where this is documented but you you can see [json.innerParse](https://ziglang.org/documentation/master/std/#std.json.innerParse) intentionally allows them for int, float and enum field types.

**Comment by kibels** [comment]
Strings are the only way to encode numbers that don't fit in u52 or f64 in json, if this were an error it would prevent a huge range of use cases, even i/u64.
