### ISSUE TITLE
std.Build.Step.WriteFile does not implement caching correctly for directories

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#20571]
### Zig Version

0.14.0-dev.208+854e86c56

### Steps to Reproduce and Observed Behavior

`zig init`

Add this code to `build.zig`:

```zig
    const wf = b.addWriteFiles();
    b.installDirectory(.{
        .source_dir = wf.addCopyDirectory(b.path("stuff"), "stuff", .{}),
        .install_dir = .prefix,
        .install_subdir = "",
    });
```

```console
$ mkdir stuff
$ touch stuff/1
$ zig build
$ ls zig-out/
1  bin  lib
$ touch stuff/2
$ zig build
$ ls zig-out
1  bin  lib
```

### Expected Behavior

When running `zig build` the second time, it should notice that a second file exists (`2`) and copy it to the WriteFile output directory, and then copy it to the installation prefix.

### Diagnosis

This happens because the implementation only adds the directory *name* to the cache hash, instead of marking the file and directory itself as part of the cache input.

https://github.com/ziglang/zig/blob/b3b923e51f53330403bd99a224c19bc3f01005c4/lib/std/Build/Step/WriteFile.zig#L271-L276

This is insufficient and results in false positive cache hits. False positives in the cache system are not allowed; this must be fixed to work perfectly or the feature reverted.

**Comment by bryanjhv** [comment]
I faced this issue today, as `addCopyDirectory` does not handle changes in files either (as of `0.13.0`).

Solving it temporarily by setting `options.exclude_extensions` to some cache-busting value, like so:

```zig
    const wf = b.addWriteFiles();
    b.installDirectory(.{
        .source_dir = wf.addCopyDirectory(b.path("stuff"), "stuff", .{
            .exclude_extensions = &.{
                b.fmt(".tmp.{d}", .{std.time.timestamp()}),
            },
        }),
        .install_dir = .prefix,
        .install_subdir = "",
    });
```
