### ISSUE TITLE
 CreateFile Permissions do not match mode parameter

### ISSUE THREAD

**Issue by SpinTensor** [ziglang/zig#20594]
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

run the following code and check the permissions of `sample.txt` with `ls -l`

```zig
const std = @import("std");

pub fn main() !void {
    const permissions = 0o666;
    var file = try std.fs.cwd().createFile("sample.txt", .{ .mode = permissions }); 
    defer file.close();
}
```
```
-rw-rw-r-- 1 fuhl fuhl    0 Jul 11 20:32 sample.txt
```
Although the permissions are specified as 0o666 the resulting permissions of `sample.txt` match `0o664`. no matter what I tried the `createFile` function would not set the world-writable flag. The default parameter is supposed to be `0o666`, but when omitting the `.mode` parameter the world-readable flag is still not set.

### Expected Behavior

The `createFile` function should set the world-writable flag for a newly created file if it is specified. Also the default value should work.

**Comment by squeek502** [comment]
Not a bug, see https://ziggit.dev/t/createfile-permissions-do-not-match-mode-parameter/5096/5

> I can reproduce the behavior locally, but it is not Zig-caused.
> 
> ```shellsession
> $ zig build-exe createfileperms.zig
> $ strace ./createfileperms
> openat(AT_FDCWD, "sample.txt", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 3
> ```
> 
> So `0666` *is* being passed to the `openat` syscall by Zig.
> 
> `umask` seems to be the answer.
> 
> ```shellsession
> $ umask
> 0002
> $ umask 0
> $ zig run createfileperms.zig
> $ ls -la sample.txt
> -rw-rw-rw- 1 ryan ryan 0 Jul 12 05:15 sample.txt
> ```

**Comment by SpinTensor** [comment]
Sorry, this seems to be a problem of my OS, where the umask is set such that world does not get write access.
