### ISSUE TITLE
Build Runner: Implement File System Watching for kqueue

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#20599]
Extracted from #20580.

Most of the file system watching mechanism is abstracted across operating systems, however, the parts that deal with receiving events from file system changes require OS-specific implementations.

https://github.com/ziglang/zig/blob/1d20ff11d7efc1f07de9a300abc15ad6ae9d6d6f/lib/std/Build/Watch.zig#L324

This issue is for the [kqueue](https://man.freebsd.org/cgi/man.cgi?kqueue) implementation, which covers most of the BSDs, including macOS.

Related:
* #20598

**Comment by tiehuis** [comment]
Based on some initial reading, kqueue requires a fd for each file being watched and not simply on the parent fd like can be done with inotify which will cause issues if many files need to be watched individually.

An alternative for Mac is to use [FSEvents](https://developer.apple.com/documentation/coreservices/file_system_events) which looks to be suitable for the workflow. I am not sure if this included by default in the core libraries available to use from zig.

**Comment by andrewrk** [comment]
I heard from @Jarred-Sumner today that you can dlopen frameworks such as FSEvents. That might be an option to explore.

I'll double check the kqueue API too. We really need directory events, it's not really possible to implement correct behavior by only watching files.

**Comment by ghostiam** [comment]
I found the implementation on kqueue.
Think this can help us in implementation.
`freebsd || openbsd || netbsd || dragonfly || darwin`
https://github.com/fsnotify/fsnotify/blob/main/backend_kqueue.go

**Comment by andrewrk** [comment]
Based on that Go code, kqueue indeed allows watching directories, however those events do not provide the names of changed files within the watched directory.

https://github.com/fsnotify/fsnotify/blob/c1467c02fba575afdb5f4201072ab8403bbf00f4/backend_kqueue.go#L524-L525

This is fine four our purposes here. It will just trigger a rebuild if any files are changed when any sibling files are watched. The Go code noted above simulates file system watching by scanning watched directories when their events fire. The Zig code will not need that hack since the rebuild will already do such a scan.

This is a pretty straightforward patch.
