### ISSUE TITLE
Zig fetch save-exact parses name incorrectly

### ISSUE THREAD

**Issue by kibels** [ziglang/zig#20616]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

Run `zig fetch --save-exact=poop https://github.com/andrewrk/poop/archive/refs/tags/0.4.0.tar.gz`

Results in a build.zig.zon entry like
```ts
        .@"exact=poop" = .{
            .url = "https://github.com/andrewrk/poop/archive/refs/tags/0.4.0.tar.gz",
            .hash = "1220b65ce060a1053d596706affd7c918bddc711686e1794c0ae79625f8541f7c6a3",
        },
```

Platform: aarch64 macOS 13.6.6

### Expected Behavior

Expected less exact
```ts
        .@"poop" = .{
            .url = "https://github.com/andrewrk/poop/archive/refs/tags/0.4.0.tar.gz",
            .hash = "1220b65ce060a1053d596706affd7c918bddc711686e1794c0ae79625f8541f7c6a3",
        },
```

**Comment by rohlem** [comment]
still reproduces for me on zig version `0.14.0-dev.186+8f20e81b8`
