### ISSUE TITLE
File duplicated when imports twice with differing case

### ISSUE THREAD

**Issue by amusingimpala75** [ziglang/zig#20668]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

In one file, declare an `export var`.

In macOS, whose file system is case-insensitive, import that file, once capitalized, once not.

```zig
// In Foo.zig
export var foo: size = 0;

// In main.zig
const Foo = @import("Foo.zig");
const foo = @import("foo.zig");

comptime {
    _ = Foo;
    _ = foo;
}
```

This results in a symbol collision, presumably because the contents of the one file is being duplicated. 

### Expected Behavior

Zig should complain about the import not matching the case of the filesystem, and consider the second import as invalid.

**Comment by nektro** [comment]
Duplicate https://github.com/ziglang/zig/issues/9786
