### ISSUE TITLE
avoid file system watches on read-only mounts

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#20669]
Follow-up from https://github.com/ziglang/zig/pull/20580.

`name_to_handle_at` gives us a mount ID here:

https://github.com/ziglang/zig/blob/8ab70f80cb8943dde41a5e4a8ca73631d44643a2/lib/std/Build/Watch.zig#L101

If this mount is read-only then the watch system should not waste any resources placing a mark on any directories within because they will never change!

Related:
* #20670

**Comment by rohlem** [comment]
No insight on the particulars of read-only mounts, but I assume they could be re-mounted with different data while the program is running?
That could either be considered an error and explicitly unsupported, or supported by a "mount watch" mechanism spanning all files within (maybe by only watching the first file on it).

**Comment by andrewrk** [comment]
ehh if that's possible and it doesn't even change the mount id then this should be closed
