### ISSUE TITLE
When linked against windows' libc, calling abort opens a popup

### ISSUE THREAD

**Issue by Sahnvour** [ziglang/zig#2071]
At least that's the default behaviour on windows.
It can be disabled programatically, or OS-wide in the registry it seems. https://stackoverflow.com/questions/735170/can-the-application-error-dialog-box-be-disabled

What should Zig's default behaviour be ? Can it be problematic if some tests are expected to abort on the CI for example ?

**Comment by andrewrk** [comment]
That's a good question. What is your preference @Sahnvour?

**Comment by Sahnvour** [comment]
I haven't dealt much with them, but my preference usually go to:
- when in debugger, only breakpoint
- in a graphical application, it seems OK to have a (eventually custom) pop up
- otherwise, no pop up, to match the behaviour of other environments (I find them super annoying for a CLI application)

**Comment by emekoi** [comment]
one solution would be disabling the pop-up unless the windows subsystem is selected; however i don't think that information is available too zig programs.

**Comment by andrewrk** [comment]
If this is what Windows has chosen to do, should we not respect the choice?

**Comment by emekoi** [comment]
according to the windows [documentation](https://msdn.microsoft.com/en-us/library/ms680621(VS.85).aspx),
> Best practice is that all applications call the process-wide SetErrorMode function with a parameter of SEM_FAILCRITICALERRORS at startup. This is to prevent error mode dialogs from hanging the application.

where SEM_FAILCRITICALERRORS means that
> The system does not display the critical-error-handler message box. Instead, the system sends the error to the calling process.

**Comment by andrewrk** [comment]
There's another option here, if we don't like msvcrt's behavior. Don't call msvc's abort():

https://github.com/ziglang/zig/blob/79e1fcfddac681128698acd2ef5667b233015c58/std/os.zig#L141-L143

We can just move that 6 lines down and have our own abort implementation always be what gets run.

**Comment by emekoi** [comment]
perhaps rather than changing the error mode at run time we can export this functionality in a function that changes the error mode. or we could just leave that up to those who want the error mode changed to do it themselves.
