### ISSUE TITLE
zig fmt incorrectly allows extra newlines at end of file

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2074]
Here's a (currently failing) test to go in `std/zig/parser_test.zig`:

```zig
test "zig fmt: extra newlines at the end" {
    try testTransform(
        \\const a = b;
        \\
        \\
        \\
    ,
        \\const a = b;
        \\
    );
}
```

**Comment by shawnl** [comment]
How should zig fmt handle extra newlines inside the file? Should reduce more than two adjacent newlines to two, except at the end, where only one is allowed?

**Comment by andrewrk** [comment]
> Should reduce more than two adjacent newlines to two, except at the end, where only one is allowed?

Correct. This behavior is already implemented, except for the end. I believe the problem is actually in the detection of changes:

https://github.com/ziglang/zig/blob/b5cc92f16391b1ff5d75e5e6b072b8338b3e8218/std/zig/render.zig#L36-L47

I think this logic is simply missing a check for `source_index` not matching `source.len` and marking `anything_changed` as `true` in this case.
