### ISSUE TITLE
Proposal: Add setup teardown functionality to tests

### ISSUE THREAD

**Issue by g41797** [ziglang/zig#20785]
Inspired by [Stephen Gutekanst's dreams](https://zig.news/slimsag/my-hopes-and-dreams-for-zig-test-2pkh) and own experience

Definition stollen from Python (_nothing personal - google shows it first during search_):

> "The **setUp**() and **tearDown**() methods allow you to define _instructions_ that will be executed before and after each test method."

So I'd like to define own _instructions_:

- _setuponce_ - executed once before run of the tests
- _teardownonce_ - executed once after run of the tests
- _setup_ - executed  before every test
- _teardown_ - executed after every test

We can discuss all edge cases (e.g. should _teardownonce_ be called for failed _setuponce_) later.

Do you remember [Test declarations](https://ziglang.org/documentation/master/#Test-Declarations)?
> Test declarations contain the [keyword](https://ziglang.org/documentation/master/#Keyword-Reference) test, followed by an optional name written as a [string literal](https://ziglang.org/documentation/master/#String-Literals-and-Unicode-Code-Point-Literals)...

```zig
test "setuponce" {
    try ...............;
}

test "teardownonce" {
    try ...............;
}

test "setup" {
    try ...............;
}

test "teardown" {
    try ...............;
}
```

Got the point?

All required "instructions" may be declared as standard Zig tests: via reserved string literals:
- "setuponce"
- "teardownonce"
- "setup"
- "teardown"

Please take a look at [default test_runner](https://github.com/ziglang/zig/blob/master/lib/compiler/test_runner.zig)

Simplified flow
- test_runner sends information about tests to zls (actually indexes in tests array)
- zls (in loop) sends index of the test to test_runner
- test_runner runs the test and inform zls about result

Simple change ( at least for not responsible for test_runner):
- test_runner does not send indexes for 4 mentioned above tests
- upon receive of test index runs
  -  setup test
  -  test in question
  -  teardown test 

I hope test_runner also doesn't forget to run
- setuponce test before first test
- teardown test before exit

And please "**Don't shoot the pianist**"

It my second day in Zig ...

**Comment by rohlem** [comment]
> `test "teardownonce" {...}`

It would be highly unintuitive for me if Zig changed the behavior of tests based on the string literal used to name the test case.
If such a feature were introduced, it should imo be specially marked in the source code in some other way.

I also don't think the benefit of the per-test `setup` and `teardown` is worth this special-casing.
You can already declare them as normal functions and start your test blocks with `setup(); defer teardown();` for the same effect.

It's also not at all clear which scope these special constructs should apply to.
Currently `zig test` collects all test declarations found, starting with analysis of the root source file, and may include the entire source tree.
I doubt you need/want the same `setup` and `teardown` procedure for every test in your source code. This work is overhead for tests that don't need it.

Also note `zig test` CLI option `--test-runner` can already be used to specify a custom (modified) test runner.
You could use that to implement the `setuponce` and `teardownonce` behavior in userland in status-quo.

> my second day in Zig ...

Feel free to discuss and share your experiences in [one of the Community spaces](https://github.com/ziglang/zig/wiki/Community).
This issue tracker tries to stay focused on technical discussion of bugs/deficiencies in Zig and core Zig toolchain development.
"X would be nice" feature requests are (in my experience) generally considered off-topic,
unless you can provide a use case that would directly benefit Zig toolchain development itself.

**Comment by g41797** [comment]
> Feel free to discuss and share your experiences in [one of the Community spaces](https://github.com/ziglang/zig/wiki/Community).

I added [r/Zig](https://www.reddit.com/r/Zig/) to Community
Thanks you
