### ISSUE TITLE
`tools/generate_linux_syscalls.zig` could be cleaned up to be table-driven

### ISSUE THREAD

**Issue by alexrp** [ziglang/zig#20801]
As I'm adding more architectures to this, it's starting to become a bit much to just copy/paste all the code for the old syscall table approach and the new C preprocessor approach.

If anyone feels like it, it should be fairly easy to clean this tool up to be table-driven, with only a few lines of special-casing for some architectures.

**Comment by ippsav** [comment]
I ll give this a go

**Comment by alexrp** [comment]
@ippsav thank you! Can you base your work on the version of the script in my [`linux-syscalls`](https://github.com/alexrp/zig/commits/linux-syscalls) branch? I won't be able to upstream it until #20389 is merged, but we can at least avoid merge conflicts this way.

**Comment by ippsav** [comment]
@alexrp lemme know what you think about this and if there is any changes you would like to add
https://github.com/ippsav/zig/blob/ippsav/rewrite-generate-linux-syscalls/tools/generate_linux_syscalls.zig

Though i need to spin up a linux vm to test it's behavior compared to the old one, or can i just do it directly from a mac ?

**Comment by alexrp** [comment]
This looks like a good direction to me so far.

You should be able to run it on macOS provided you have a clone of the Linux 6.7 tree to point it to. `git clone https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git linux && cd linux && git checkout v6.7` will get you that.

**Comment by ippsav** [comment]
@alexrp I've pushed some changes, tested it, works properly.

The only issue is with `hexagon` arch throws an error invalid target `generic`

**Comment by alexrp** [comment]
Yeah, the Hexagon support depends on #20798, so that's expected.

Will let you know once #20389 and my `linux-syscalls` branch are upstreamed so you can open a pull request w/o merge conflicts. Thanks for working on this!

**Comment by ippsav** [comment]
Thanks !

**Comment by alexrp** [comment]
@ippsav #20869 is merged, so you can go ahead and rebase your work on master and submit a PR. 🙂
