### ISSUE TITLE
Setting bad array sentinel not detected

### ISSUE THREAD

**Issue by Trevor-Strong** [ziglang/zig#20808]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

Run `zig test` on a file containing:

```zig
const std = @import("std");

test {
    var buf: [5:0]u8 = undefined;
    buf[0] = 'H';
    buf[1] = 'e';
    buf[2] = 'l';
    buf[3] = 'l';
    buf[4] = 'o';
    buf[5] = 1;

    try std.testing.expectEqualStrings("Hello", &buf);
    try std.testing.expectEqual(0, buf[5]);
    var i: usize = 5;
    _ = &i;
    try std.testing.expectEqual(1, buf[i]);
}
```

And the test will pass

### Expected Behavior

I would expect it to be a compile error for me to do `buf[5] = 1` since all the information for the compiler know that `buf[5] = 1` would set the sentinel value to something other than what it's type say it should be is `comptime` known, and perhaps this could degrade to a runtime panic when setting the sentinel to a non-`comptime` value.

At the very least, I would expect the test to fail at the `expectEqual(0, buf[5])`.

Interestingly, this problem does not occur with slices and using `slice.len` in place of the literal length.

It appears that when it is comptime known that you're accessing a sentinel value, the compiler forgoes indexing the array a just emits the type's sentinel value.

As a side-note, I only ran into this because I was testing to see if you could assign to the sentinel index without a panic in safe-mode (you can), as the documentation around sentinel terminated slices/arrays only says that you can *read* from the `len` index, and makes no mention of your ability to write to it.

**Comment by Vexu** [comment]
#9791 tracks adding a safety check (and compile error) for this.

**Comment by Trevor-Strong** [comment]
@Vexu thanks, I didn't see that. Closing as duplicate then.
