### ISSUE TITLE
invalid clockid default in std.os.linux

### ISSUE THREAD

**Issue by nahi-na-kyu-kisne-pucha** [ziglang/zig#20810]
### Zig Version

0.14.0-dev.591+1c35e73b6

### Steps to Reproduce and Observed Behavior

compile the project with the latest zig version.
```
https://github.com/andrewrk/poop/
cd poop
zig build. 
```
it errors out with 
```

std/os/linux.zig:7178:26: error: expected type 'os.linux.clockid_t', found 'comptime_int'
    clockid: clockid_t = 0,
                         ^
std/os/linux.zig:4058:23: note: enum declared here
pub const clockid_t = enum(u32) {
                      ^~~~
```

Changing `clockid:clockid_t=0` to `clockid:clockid_t=.REALTIME` fixes this. 

### Expected Behavior

Expected the program to compile and run.

**Comment by alexrp** [comment]
Ok, but this was a deliberate change in the standard library. There's nothing to do on the Zig end. You should file this issue here: https://github.com/andrewrk/poop/issues

**Comment by mlugg** [comment]
No, this is definitely an std bug. Look at the error -- it's an invalid field default in std.os.linux.

**Comment by alexrp** [comment]
Oops, you're right. I'll take a look at this.
