### ISSUE TITLE
Linux: inconsistent return types of `std.os.linux.inotify*`

### ISSUE THREAD

**Issue by Sh4pe** [ziglang/zig#20824]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

According to the man pages, [inotify_init](https://man7.org/linux/man-pages/man2/inotify_init.2.html) should return a file descriptor that can be used directly with [inotify_add_watch](https://man7.org/linux/man-pages/man2/inotify_add_watch.2.html). However, the code in `std.os.linux` has return types that do not support such a behavior. See the following short program:

```zig
const std = @import("std");
const linux = std.os.linux;

pub fn main() !void {
    const fd = linux.inotify_init1(0);
    _ = linux.inotify_add_watch(fd, "some_file.txt", 0x00000002 | 0x00000008);
}
```

Compiling it gives the following error:
```
[sh4pe@sh4peux:~/Documents/devel/zig/inotify_playground]$ zig run src/main2.zig
src/main2.zig:6:33: error: expected type 'i32', found 'usize'
    _ = linux.inotify_add_watch(fd, "some_file.txt", 0x00000002 | 0x00000008);
                                ^~
src/main2.zig:6:33: note: signed 32-bit int cannot represent all possible unsigned 64-bit values
/nix/store/a1iiismj2iw26m91l13kc3arr584ix44-zig-0.13.0/lib/zig/std/os/linux.zig:693:30: note: parameter type declared here
pub fn inotify_add_watch(fd: i32, pathname: [*:0]const u8, mask: u32) usize {
                             ^~~
referenced by:
    callMain: /nix/store/a1iiismj2iw26m91l13kc3arr584ix44-zig-0.13.0/lib/zig/std/start.zig:524:32
    callMainWithArgs: /nix/store/a1iiismj2iw26m91l13kc3arr584ix44-zig-0.13.0/lib/zig/std/start.zig:482:12
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

### Expected Behavior

I'd expect that `linux.inotify_init` returns a file descriptor that I'd be able to use directly with `inotify_add_watch` without an `@intCast`.

**Comment by alexrp** [comment]
You did not give the error; copy/paste mistake?

**Comment by Sh4pe** [comment]
OMG, yes. Sorry :/ Fixed it.

**Comment by alexrp** [comment]
It seems that, with only a few exceptions, we tend to return the result of syscalls directly in `std.os.linux`, and the result of a syscall is `usize`-typed. We only perform "Ziggification" of the results of `sched_setaffinity()` and `getpid()` (and friends) at the moment.

`inotify_init1()` returning `int` is a libc convenience/abstraction based on the expected range of the result, like with `getpid()` etc.

I think we should take an official stance on this, clarify it in the `std.os.linux` module docs, and then consistently stick to it. I personally lean towards having more accurate types based on the semantics of the syscalls, as suggested by this issue. cc @andrewrk

@Sh4pe in the meantime, you can safely `@intCast()` the result.

**Comment by Rexicon226** [comment]
The `std.os.linux` namespace is meant to provide a close to 1:1 interface with the syscalls and @alexrp correctly points out that they return `usize`-typed results.

The intended interface for this is to use `std.posix.inotify_init1`, which will ziggifiy the result into an `i32` and handle the potential errors it could have returned by turning them into a Zig error set.
