### ISSUE TITLE
Object Files have no standard installation procedure

### ISSUE THREAD

**Issue by Ben-Miller0** [ziglang/zig#20838]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

build.zig

    const std = @import("std");

    pub fn build(b: *std.Build) void {
        const obj = b.addObject(.{
            .name = "hello",
            .target = b.host,
            .optimize = .Debug,
        .root_source_file = .{ .src_path = .{ .sub_path = "src/main.zig", .owner = b } },
        });

    b.installArtifact(obj);
}

src/main.zig

    const std = @import("std");

    pub fn main() !void {
        std.debug.print("Hello, World!", .{});
    }

run command `zig build`
gives the error message `panic: object files have no standard installation procedure`

### Expected Behavior

I would expect the object file to be outputted to somewhere in zig-out

**Comment by alexrp** [comment]
The reason this is not supported is that there really is no sane place to put the object file. Ask yourself: Where would you install a `.o` file in, say, `/usr`?

**Comment by alexrp** [comment]
The Zig build system does not work like C build systems (to the extent that the latter is a meaningful term). Zig treats its build directory, `zig-out`, as a prefix. `zig build` (without any options) is basically like if you'd done `./configure --prefix=zig-out && make && make install` in an Autotools project.

**Comment by Ben-Miller0** [comment]
is there a way to get the `.o` file out for use with exernal commands

**Comment by alexrp** [comment]
`addObject()` returns a `*Step.Compile` just like `addStaticLibrary()`, `addExecutable()`, etc. On such a step, you can use `const built_obj = obj.getEmittedBin()` to get a `LazyPath` that represents the built artifact. If you create a system command step with `const sys_cmd = b.addSystemCommand(...)`, you can then feed the object file into it with something like `sys_cmd.addFileArg(built_obj)`.

**Comment by Ben-Miller0** [comment]
thank you
