### ISSUE TITLE
`.\x86-64-windows-*.ps1` scripts generate broken link that returns 403 forbidden

### ISSUE THREAD

**Issue by daninsky1** [ziglang/zig#20850]
### Zig Version

0.13.0-dev.130+98a30acad

### Steps to Reproduce and Observed Behavior

I'm trying to build the master branch on Windows following https://github.com/ziglang/zig/wiki/Building-Zig-on-Windows, but when I try to run the x86-64-windows-debug.ps1 or x86-64-windows-release.ps1 I'm receive 403 forbidden

### Expected Behavior

Download the zig dependencies for Windows.

**Comment by squeek502** [comment]
The instructions say:

> Determine the URL by looking at the CI script

Looking, not running. The URL to the zip is constructed by looking at:

```
https://ziglang.org/deps/$ZIG_LLVM_CLANG_LLD_NAME.zip
```

then replacing `$ZIG_LLVM_CLANG_LLD_NAME` with the value its set to, which gives you:

```
https://ziglang.org/deps/zig+llvm+lld+clang-$TARGET-0.13.0-dev.130+98a30acad.zip
```

and then replacing `$TARGET` with the value its set to, which is `$($Env:ARCH)-windows-gnu` which expands to `x86_64-windows-gnu`. Then you download that `.zip` file. The same steps to get the download URL are repeated if those dependencies need to change (usually only happens in accordance with LLVM upgrades).

---

In the future, please direct these sorts of questions to [one of the community spaces](https://github.com/ziglang/zig/wiki/Community) first

**Comment by daninsky1** [comment]
oh, my bad, got it. Thanks 🫡.
