### ISSUE TITLE
[Windows] Zig and N-API compilation fail, lld-link undefined symbols

### ISSUE THREAD

**Issue by osztenkurden** [ziglang/zig#20860]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

Windows 10

1. Clone https://github.com/osztenkurden/zig-nodejs-example repo
2. npm install
3. Download and unpack https://nodejs.org/download/release/v20.9.0/node-v20.9.0-headers.tar.gz so node_api.h is in REPO/deps/node-20.9.0/include/node
4. npm run build
5. node index.js

Currently on Windows on compilation I'm getting

```
warning(link): unexpected LLD stderr:
lld-link: warning: undefined symbol: napi_create_function
>>> referenced by F:\Repositories\zig\zig-nodejs-example\src\translate.zig:26
>>>               dist\lib.node.obj:(translate.register_function__anon_3078)

lld-link: warning: undefined symbol: napi_set_named_property
>>> referenced by F:\Repositories\zig\zig-nodejs-example\src\translate.zig:30
>>>               dist\lib.node.obj:(translate.register_function__anon_3078)

lld-link: warning: undefined symbol: napi_throw_error
>>> referenced by F:\Repositories\zig\zig-nodejs-example\src\translate.zig:37
>>>               dist\lib.node.obj:(translate.throw__anon_3080)
>>> referenced by F:\Repositories\zig\zig-nodejs-example\src\translate.zig:37
>>>               dist\lib.node.obj:(translate.throw__anon_3081)
>>> referenced by F:\Repositories\zig\zig-nodejs-example\src\translate.zig:37
>>>               dist\lib.node.obj:(translate.throw__anon_3082)

lld-link: warning: undefined symbol: napi_create_string_utf8
>>> referenced by F:\Repositories\zig\zig-nodejs-example\src\translate.zig:378
>>>               dist\lib.node.obj:(translate.create_string)
```
Executing `node index.js` shows nothing, silent crash.
On Mac, all works well. Compiling for Windows target on Mac also shows the error above

### Expected Behavior

lib.zig should be compiled, and after executing node index.js "world" should be logged out

**Comment by squeek502** [comment]
I believe for Windows you have to link against `node.lib`. For the version you're using I think that would be:

https://nodejs.org/download/release/v20.9.0/win-x64/node.lib

This seems like something that would be better directed to [one of the community spaces](https://github.com/ziglang/zig/wiki/Community) first. Please open a new issue if there ends up being a Zig bug involved here.
