### ISSUE TITLE
Error handling via if-else statement has some issues

### ISSUE THREAD

**Issue by likeMyCoffee** [ziglang/zig#20886]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

I'm porting some old C as a fun project to learn Zig.
From the perspective of porting some old C code I would like to note some issues that could help make it easier.

When processing a possible error I am using the if/else method as seen in below example code.

A few issues arrise that you should be aware of
1. I must consume |err| if it is specified on the else clause
2. I must specify the |err| or else clause or it won't compile.
3. I must use err and cannot discard it.
4. I cannot use the unreachable clause if I have unreachable code.

I understand you want to force the handling of errors however the catch {}; or catch unreachable; are allowed.

Below code works and is OK but i should not have to place unreachable code. It seems like a bug to me.

```
const std = @import("std");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    var home: []u8 = undefined;
    if (std.process.getEnvVarOwned(gpa.allocator(), "HOMEX")) |str| {
        home = str;
        defer gpa.allocator().free(home);
    }
    else |err| { // Else requires the |err| or else is invalid
        try myErrorExit("A generic error occured that we don't care about!");
        return err; // Unreachable
    }
}

fn myErrorExit(str: []const u8) !void {

    try std.io.getStdOut().writer().print("{s}", .{str});
    std.process.exit(1);
}
```

### Expected Behavior

So this should be possible
```
const std = @import("std");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    var home: []u8 = undefined;
    if (std.process.getEnvVarOwned(gpa.allocator(), "HOMEX")) |str| {
        home = str;
        defer gpa.allocator().free(home);
    }
    else { // Implicit |err|
        try myErrorExit("A generic error occured that we don't care about!");
        unreachable;
    }
}

fn myErrorExit(str: []const u8) !void {

    try std.io.getStdOut().writer().print("{s}", .{str});
    std.process.exit(1);
}
```

or even better

```
const std = @import("std");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    var home: []u8 = undefined;
    if (std.process.getEnvVarOwned(gpa.allocator(), "HOMEX")) |str| {
        home = str;
        defer gpa.allocator().free(home);
    }
    else |err| {
        _ = err; // Discard the error (currently causes compile error)
        try myErrorExit("A generic error occured that we don't care about!");
        unreachable;
    }
}

fn myErrorExit(str: []const u8) !void {

    try std.io.getStdOut().writer().print("{s}", .{str});
    std.process.exit(1);
}
```

**Comment by castholm** [comment]
You can use `else |_|` to ignore the error. The following code will compile and run:

```diff
 const std = @import("std");

 pub fn main() !void {
     var gpa = std.heap.GeneralPurposeAllocator(.{}){};
     var home: []u8 = undefined;
     if (std.process.getEnvVarOwned(gpa.allocator(), "HOMEX")) |str| {
         home = str;
         defer gpa.allocator().free(home);
-    } else |err| {
-        _ = err; // Discard the error (currently causes compile error)
+    } else |_| {
         try myErrorExit("Please set $HOME to your home directory");
         unreachable;
     }
 }

 fn myErrorExit(str: []const u8) !void {
     try std.io.getStdOut().writer().print("{s}", .{str});
     std.process.exit(1);
 }
```

So while this isn't really a bug, it's understandable that you didn't know that `else |_|` would work. It would probably be easier for users to discover it if the compiler hinted at it as an option,
i.e. something like `note: captured error in else branch can be explicitly ignored with '|_|'`.

**Comment by likeMyCoffee** [comment]
Dang! That is nice an elegant 🙈

Yes it would be nice if it was documented (or I didn't look enough) and even better if the compiler directed me to this,

Thanks! And you can close it unless you want to keep this as a placeholder for the compiler feedback😊
