### ISSUE TITLE
std.os.linux.access return type unfit for it's purpose

### ISSUE THREAD

**Issue by likeMyCoffee** [ziglang/zig#20889]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

The documentation of std.os.linux.access is lacking but I figured out it's like the C access method.
Testing has confirmed it acts like the C access method.

The function returns
0 if access is possible
-1 if access is not possible

However the return type is an usize which is an unsigned int that cannot represent -1

In Zig you currently need to check like this
```
if (ret == 0) {
  // Do stuff
}
else if (ret == 18446744073709551614) {  // -1 as an usize
  // Do stuff
}
else {
  // This is illegal
  unreachable;
}
```
Even worse is that usize as far as I know is dependent on the underlying architecture meaning -1 might have different representations.

Doing (ret == -1) doesn't see 18446744073709551614 as the usize representation of -1

Forcing the compiler to do the dirty work gives a very clear and correct error message :-)

error: type 'usize' cannot represent integer value '-1'
    if (x == @as(usize, -1)) {

The best workaround for now is doing (ret != 0) which makes it kind of acceptable.

P.S. There might be more functions that have this issue.

### Expected Behavior

The return type should be a bool since there are only true or false outcomes to my knowledge.

Preferable way to use return value
`if (ret) {
  // Do stuff
}
else {
  // Do stuff
}`

**Comment by alexrp** [comment]
This is a result of our current policy (that we mostly follow) of just returning what the syscall returns in `std.os.linux`. See #20824 for more discussion on this.

**Comment by rohlem** [comment]
> The best workaround for now is doing (ret != 0) which makes it kind of acceptable.

Note that you can use `@bitCast` to either cast the `-1` to `usize`, or cast `ret` to `isize` before the comparison; imo the latter is a bit more readable.

**Comment by likeMyCoffee** [comment]
Thanks for the reply!

The policy makes sense since you guys probably have a ton of work 😅 updating libraries is a ton of extra work...

@bitCast is something I will explore. Thanks!

**Comment by Rexicon226** [comment]
If @alexrp’s reply wasn’t clear the solution here is not to use `@bitCast`. It’s to use `std.posix.access` which does the wrapping and error conversion for you.

**Comment by likeMyCoffee** [comment]
His reply was clear to me. I just didn't know how to go from usize to isize. @as didn't work and I haven't found @bitCast yet 😊
