### ISSUE TITLE
documentation unclear about floats NaN, inf, and -inf

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2089]
All three of these should be mentioned here https://ziglang.org/documentation/master/#Float-Literals

Also, a negative NaN literal should be a compile error, as it doesn't exist in IEEE-754, and is equivalent to positive NaN.

**Comment by andrewrk** [comment]
Note that all number literals in Zig are positive. Putting a minus sign in front of a number literal is invoking comptime negation.
