### ISSUE TITLE
Proposal: `continue` in an `inline for` loop

### ISSUE THREAD

**Issue by edqx** [ziglang/zig#20897]
At some point runtime `break`s were implemented for `inline for` loops (or perhaps they always have been), but `continue`s never have been:
```zig
error: comptime control flow inside runtime block
```
For example:
```zig
const arr: [5]u8 = .{ 1, 2, 3, 4, 5 };

var a: usize = 0;
_ = &a;

inline for (arr) |num| {
    if (a == 2) continue; // error: comptime control flow inside runtime block
    if (a == 4) break;

    std.log.info("num: {}", .{num});
}
```

This seems to just be unimplemented rather than being some technical limitation, see:
```zig
inline for (iterand) |_| @"continue": {
    if (runtime_cond) break :@"continue";
}
```
as a way to implement it using other Zig syntax. (courtesy of @InKryption)

This proposal simply is to allow `continue` to be used according to runtime logic in an `inline for` loop

**Comment by linusg** [comment]
Related: #9524

**Comment by edqx** [comment]
This issue looks like a duplicate then

**Comment by Vexu** [comment]
Let's consider it a duplicate.
