### ISSUE TITLE
Add 'initialise to zero' argument to reallocFn 

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2090]
Some allocators can, in certain cases, cheaply provide memory initialised to zero:

  - a direct memory allocator can get zero-initialised memory from the kernel
  - a libc allocator can use calloc instead of malloc
  - a general purpose allocator might zero memory on free as a security feature

To take advantage of this, I propose a `zero: bool` argument to be added to the `reallocFn` interface. I chose a boolean here, as I can't think of any uses cases where you would want memory to be initialised to something other than `undefined` or `0`.

If an allocator cannot provide pre-zero-initialised memory, then it should perform `if (zero) @memset(new_mem.ptr, 0, new_mem.len);`

The `Allocator` library should verify that memory returned is actually zero when in safe modes.

**Comment by kyle-github** [comment]
I seem to recall that some memory checking libraries set memory to other values as a way to check for changes etc.

I would think a simple byte value would cover both the common case of zero and the less common cases of 0xaa etc.

**Comment by andrewrk** [comment]
I want to note that the Allocator API intentionally does not have a allocate-and-zero-initialize function, and likewise Zig itself does not have the concept of zero initialization. It was removed in 6a5e61acd117277eb2f943f5bc02ff7043542d4b.

**Comment by tgschultz** [comment]
Seems to me that you could just use a different allocator implementation when you want it to zero memory or memset it to a specific value, even if it calls the same system allocator behind the scenes. The advantage is that it leaves the decision about whether or not to do that sort of thing up to the programmer supplying the allocator instead of the function using it.

**Comment by andrewrk** [comment]
That wouldn't work with status quo Allocator interface, because of this:

https://github.com/ziglang/zig/blob/3e9697bb35267973554155cedc2e593bd4519dd8/std/mem.zig#L105-L110

**Comment by tgschultz** [comment]
I'm not saying implement it on the Zig end, I'm saying that feature of the system allocator or C allocator can be exposed through a separate allocator implementation. That way, the programmer can choose to use it or not for any arbitrary allocator-using function. If all allocators take a `zero: bool` parameter, then it is up to the function to decide (or it has to take yet another parameter).

**Comment by andrewrk** [comment]
This goes against the core language design that "zero initialization" isn't meaningful. This is one area where Go and Zig differ strongly.
