### ISSUE TITLE
[Proposal]: initialize multiple variables at once.

### ISSUE THREAD

**Issue by MubinMuhammad** [ziglang/zig#20917]
### Zig Version

0.14.0

### The Enhancement

In Zig, I would assume it can initialize multiple variables at once with the following syntax:
```zig
var i, j, k: u32 = 0;
```
I think it is an enhancement to the language.
Thanks.

**Comment by Luukdegram** [comment]
https://github.com/ziglang/zig/wiki/Language-Proposals

**Comment by mlugg** [comment]
Also, please see [Aggregate Destructuring](https://ziglang.org/download/0.12.0/release-notes.html#Aggregate-Destructuring).

**Comment by MubinMuhammad** [comment]
Thanks.
