### ISSUE TITLE
[Proposal] allow circular refer in a function scope

### ISSUE THREAD

**Issue by unisgn** [ziglang/zig#20924]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

fn main() void {
    const S = struct {
        s: *S,
    };
}

this kind of circular reference was allowed in a container scope, but not in a function scope.

### Expected Behavior

allow circular refer in a function scope too.

**Comment by lfanew** [comment]
I believe you can solve this using [@This](https://ziglang.org/documentation/0.13.0/#This)

```zig
pub fn main() void {
    const S = struct {
        const self = @This();
        s: *self,
    };
    _ = S;
}

// or

pub fn main() void {
    const S = struct {
        s: *@This(),
    };
    _ = S;
}
```

**Comment by mlugg** [comment]
Yes, `@This()` is the correct tool here.
