### ISSUE TITLE
Creating unions with .{} and const fails without error message

### ISSUE THREAD

**Issue by DataResearch** [ziglang/zig#20926]
### Zig Version

0.14.0-dev.302+d404d8a36

### Steps to Reproduce and Observed Behavior

I tried in my project to assign later in a function an union by using the anonymous struct syntax when the union was const. This caused the compiler to exit with code 3 or garbels the console without posting an error masseage. 

A small code for a repro is here:
```zig
const selector = union(enum) {
    int: i16,
    str: []const u8,
};

pub fn main() void {
    const uni: selector = undefined;
    uni = .{ .int = 0 };
}
```

I took an image of a project it occured in and building the repro with `zig build-exe ./errors.zig` in powershell:

Repro Build:

![grafik](https://github.com/user-attachments/assets/70126b11-479d-4b05-9e7f-5133cec40982)

Main Project the Error occured in:

![grafik](https://github.com/user-attachments/assets/5f5b6d55-f7de-4f6d-b744-90f05bca0a0a)

While posting some infos about the step failing there is no compiler error and mention of exit-code 3.

Environment: Using Powershell with Win11 - newest update.

### Expected Behavior

An error message to appear, that diagnoses the issue with my code.

**Comment by DataResearch** [comment]
After testing around a bit, I think it is clear to me now, that the .{} isn't the issue. But rather reassigning the const union.

**Comment by Vexu** [comment]
Crashes in the same place as #19832, probably caused by the same thing so I'll add this as another example there.
