### ISSUE TITLE
remove octal and binary float literals from the language

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2093]
Either document them or remove them from the language.

If they are removed from the language then the code in tokenizer.cpp that doesn't call `bigfloat_init_buf` can be deleted. If they stay in the language, zig should probably reformat the string to match hex float literals and still have the same float parsing code handle them.

**Comment by thejoshwolfe** [comment]
i vote for removal

**Comment by andrewrk** [comment]
This isn't quite solved yet, still needs to be removed from the grammar [[1]](https://ziglang.org/documentation/master/#Grammar) [[2]](https://github.com/ziglang/zig-spec/tree/master/grammar) and stage2 parser.

**Comment by andrewrk** [comment]
The grammar changes are done thanks to @mokulus.

As to the stage2 parser, I think the tokenizer can allow octal and binary float literals, and then semantic analysis can reject them as invalid format. So this can be considered closed.
