### ISSUE TITLE
Segfault if I don't print `ArgIterator`

### ISSUE THREAD

**Issue by Reokodoku** [ziglang/zig#20942]
### Zig Version

0.14.0-dev.839+a931bfada

### Steps to Reproduce and Observed Behavior

main.zig:
```zig
const std = @import("std");
const Allocator = std.mem.Allocator;

const Parser = struct {
    iter: *std.process.ArgIterator,

    pub fn init(allocator: Allocator) Parser {
        var iter = std.process.argsWithAllocator(allocator) catch @panic("OOM");
        std.debug.print("Iter: {any}\n", .{iter});
        return .{
            .iter = &iter,
        };
    }

    pub fn deinit(self: Parser) void {
        self.iter.deinit();
    }
};

pub fn main() void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer if (gpa.deinit() == .leak) @panic("MEMORY LEAK");

    const parser = Parser.init(gpa.allocator());
    defer parser.deinit();
}
```

If I remove `std.debug.print("Iter: {any}\n", .{iter});` in the init function, the executable crashes (tested on Windows 10 and Wine 9.14).

Screenshot:
![zig_bug](https://github.com/user-attachments/assets/36132356-d101-4219-8e79-215672321276)

### Expected Behavior

No segfault.

**Comment by alexrp** [comment]
You're returning the address of `iter`, a local variable, and then calling `.deinit()` through that pointer after returning.

**Comment by Reokodoku** [comment]
Now I understand. Thanks for the help!
