### ISSUE TITLE
`@src.file` file name collisions

### ISSUE THREAD

**Issue by leecannon** [ziglang/zig#20963]
### Zig Version

0.14.0-dev.850+ddcb7b1c1

### Steps to Reproduce and Observed Behavior

Files from different modules with the same relative path names from their respective root files have the same value for `@src().file` and therefore cannot be distinguished.

```zig
// build.zig
pub fn build(b: *std.Build) void {
    const exe = b.addExecutable(.{
        .name = "fff",
        .root_source_file = b.path("src/main.zig"),
        .target = b.standardTargetOptions(.{}),
        .optimize = b.standardOptimizeOption(.{}),
    });

    exe.root_module.addImport("dep1", b.createModule(.{
        .root_source_file = b.path("dep1/main.zig"),
    }));
    exe.root_module.addImport("dep2", b.createModule(.{
        .root_source_file = b.path("dep2/main.zig"),
    }));

    const run_cmd = b.addRunArtifact(exe);
    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);
}

// src/main.zig
pub fn main() void {
    std.debug.print("{s}\n", .{@src().file});
    @import("dep1").printSrcFile();
    @import("dep2").printSrcFile();
}

// both dep1/main.zig and dep2/main are identical
pub fn printSrcFile() void {
    std.debug.print("{s}\n", .{@src().file});
}
```

```
$ zig build run
main.zig
main.zig
main.zig
```

### Expected Behavior

In the context of a single compilation each file should have a unique `@src().file`.

**Comment by rohlem** [comment]
Related discussion in https://github.com/ziglang/zig/issues/19570 .
We could add an additional `.module` field to disambiguate, although iirc module names are currently local to the depender, and not unique across the build graph.
I feel like for every module that cares about this, a userland solution (defining a "module name" constant to include in a userland `Src` struct) should be possible.
I assume you have a use case for wanting to differentiate files across modules?

**Comment by leecannon** [comment]
One of the use cases of `@src` is for things like tracy.

With different files receiving the same path not only would tracy conflate traces from different source files it also has no way of locating the file from that path alone making it useless.

**Comment by VisenDev** [comment]
I believe this conflict was discussed on the discord. Especially in the case of projects like dvui that us @src for getting unique src locations. I believe andrew agreed to expand the capabilities of @src to include module information

<img width="773" alt="Screenshot 2024-08-07 at 10 45 41 AM" src="https://github.com/user-attachments/assets/c0956f2e-7566-4a11-a50d-b699da05cf7e">

**Comment by mnemnion** [comment]
I've made some comments in #20864 about this issue as well, which I'm linking to mostly because @andrewrk said the same thing there as in the screenshot.

To state what [ohsnap](https://github.com/mnemnion/ohsnap) needs in a goal-oriented way, it's the ability to use the output of `@src()` to find and open the source file. Any approach to that functionality works for me.

**Comment by zkburke** [comment]
> I believe this conflict was discussed on the discord. Especially in the case of projects like dvui that us @src for getting unique src locations. I believe andrew agreed to expand the capabilities of @src to include module information
> <img alt="Screenshot 2024-08-07 at 10 45 41 AM" width="773" src="https://private-user-images.githubusercontent.com/48253336/355886800-c0956f2e-7566-4a11-a50d-b699da05cf7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNTY2MzksIm5iZiI6MTcyMzA1NjMzOSwicGF0aCI6Ii80ODI1MzMzNi8zNTU4ODY4MDAtYzA5NTZmMmUtNzU2Ni00YTExLWE1MGQtYjY5OWRhMDVjZjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE4NDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZjI3Yzk5YjRiOWY1NGQ0MjAyNTQxM2JlMmVjNmU5NzIxNjZhNmYwYmUzZTQ3MmJhMDllYWQ2NGI5YmM0NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UU85K8ynwXvBtkNx6rlrMnv1o2Sqj8RMeNxtswfQ7w8">

Just commenting here to say I was the one who initiated this discussion on the discord as I also have a use case for this. Any instrumentation library will need this (like tracy) and most immediate mode uis will use this as well. The usefulness of `@src()` is significantly neutered by allowing these name conflicts to occur. I'd be totally happy with a module field in SourceLocation as a minimum, but I don't want to repeat myself as I've mentioned this in the discord discussion. Just leaving my thoughts here for posterity.

**Comment by andrewrk** [comment]
Play with that a little and let me know what you think.

**Comment by mnemnion** [comment]
Will do, having some trouble with the build (not a request for help, working the Discord angle there), but I'll try it out as soon as I can.
