### ISSUE TITLE
-0.0 literal is not negative

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2098]
When realizing that the documentation fix of #2089 should also mention negative zero, I discovered that negative zero is handled incorrectly in zig. The following test should pass:
```
test "negative zero" {
    var negative_zero: f32 = -0.0;
    std.debug.warn("{}", negative_zero);
    std.debug.assert(-5.0 == 5.0 * -0.0);
}
```

**Comment by daurnimator** [comment]
> `-5.0 == 5.0 * -0.0`

That is wrong... the result should be `-0.0`
