### ISSUE TITLE
[Feature Request/Bug] Make MultiArrayList behave like normal ArrayList

### ISSUE THREAD

**Issue by Xyndra** [ziglang/zig#21009]
Since MultiArrayList is nothing more than another way to store data, it should behave more like an ArrayList. I know that this is not possible ootb because of different pointer locations, however it should be realistically be implementable inside a wrapper and would greatly benifit the user experience. 

See points in Zig Zen:
 - Reduce the amount one must remember: someone would only have to remember the ways to do things in one way.
 - Only one obvious way to do things: make it way more obvious on how to handle things.
 - Incremental improvements & Avoid local maximums: this would be a certain improvement, even though it would need refactoring old code.
 - Communicate intent precisely: the intent was for MultiArrayList to be a five-letter fix for saving padding bytes, as said in a talk from @andrewrk. This is not the case since the code becomes a lot more complex when using MultiArrayList, for example in loops and not having the "indexOf" function.

**Comment by andrewrk** [comment]
too vague

**Comment by Xyndra** [comment]
what of "create a wrapper for MultiArrayList to make it behave like ArrayList" is vague?

**Comment by xdBronch** [comment]
how does it behave differently? what exactly would this wrapper do/look like?

**Comment by Xyndra** [comment]
It behaves differently in that it isn't iterable as a whole but only parts of the struct, and there is also no `indexOf` function

**Comment by xdBronch** [comment]
only iterating over parts of the struct is like, the entire point of multiarraylist, making it act like that wouldn't make sense and it's already possible by just calling `items()` multiple times. and the normal arraylist doesn't have an `indexOf` function so I'm not sure what you're talking about, that's all part of `std.mem` which is generic over any kind of slice
