### ISSUE TITLE
std.json: parsing: possibility for missing optional fields to not trigger an error

### ISSUE THREAD

**Issue by KilianHanich** [ziglang/zig#21013]
This is a standard library enhancement proposal. Some JSON schemas define missing fields to be equal to a field set to null (e.g. every JSON schema of the OCI container specification).

It would be good if one could specify that missing fields whose type is an optional do not trigger a MissingField error.

So the goal is that if you have a struct like `struct { a: i32, b: ?i32 }` one could parse it from both: `{ "a": 5, "b": null }` and `{ "a": 5 }` instead of just the first version.

**Comment by ianprime0509** [comment]
Previously proposed/discussed in #18000 and #18056; the current intended and supported way to do this is to give a default value to the field, as in `struct { a: i32, b: ?i32 = null }`: https://github.com/ziglang/zig/pull/18000#issuecomment-1812613182

**Comment by KilianHanich** [comment]
Hmm, I think this should be documented somewhere that the parsers behave like this then. Even if only to prevent this from coming up again, because I don't think this is really intuitive (mostly because I don't know of another language which does this).
