### ISSUE TITLE
@alignOf() returns incorrect alignment for structs containing multiple SIMD vectors

### ISSUE THREAD

**Issue by Charlcoal** [ziglang/zig#21014]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

I am running Linux Mint 21.3 x64 (Linux 5.15.0-117-generic kernel, i5-6600K cpu).
when the following code is run (debug mode):
```zig
const Vertex = struct {
    pos: @Vector(2, f32),
    data: @Vector(3, f32),
};

pub fn main() void {
    const ptr_align = @alignOf(*Vertex);
    var three: u32 align(ptr_align) = 3;
    const example: *align(ptr_align) u32 = &three;
    _ = @as(*Vertex, @ptrCast(example));
}
```
I get the error:
```bash
testing.zig:10:22: error: @ptrCast increases pointer alignment
    _ = @as(*Vertex, @ptrCast(example));
                     ^~~~~~~~~~~~~~~~~
testing.zig:10:31: note: '*align(8) u32' has alignment '8'
    _ = @as(*Vertex, @ptrCast(example));
                              ^~~~~~~
testing.zig:10:22: note: '*testing.Vertex' has alignment '16'
```

### Expected Behavior

Either ```@alignOf(*Vertex)``` should return 16 bytes, or ```Vertex``` should not have a 16 byte alignment.

**Comment by mlugg** [comment]
You want `@alignOf(Vertex)`, not `@alignOf(*Vertex)`. The latter is telling you the alignment of a pointer value, which is 8 bytes on your platform.

**Comment by Charlcoal** [comment]
Thanks, I was stuck thinking of alignment as an attribute of pointers and not a general concept of memory.
