### ISSUE TITLE
autodoc: mistakenly picks up decls inside decltests

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#21060]
### Zig Version

0.14.0-dev.1021+fc2924080

### Steps to Reproduce and Observed Behavior

https://ziglang.org/documentation/master/std/#std.meta

<img width="571" alt="image" src="https://github.com/user-attachments/assets/e74e87b2-c98d-4b73-81cf-90b9b3bd1c9f">

<img width="571" alt="image" src="https://github.com/user-attachments/assets/cef168e9-424c-468f-a7a5-66b0d566b27c">

<img width="569" alt="image" src="https://github.com/user-attachments/assets/ac9d10aa-c75b-43e9-bb8c-773cb565de3e">

### Expected Behavior

they should be skipped

**Comment by ianprime0509** [comment]
Duplicate of #19788

**Comment by nektro** [comment]
that it is
