### ISSUE TITLE
LLVM crashes on `aarch64_be-linux-*` for functions taking unusual vector types

### ISSUE THREAD

**Issue by alexrp** [ziglang/zig#21064]
### Zig Version

eadc0c0

### Steps to Reproduce and Observed Behavior

`zig test -target aarch64_be-linux-none test/behavior/math.zig --test-cmd qemu-aarch64_be --test-cmd-bin`

Upstream bug: https://github.com/llvm/llvm-project/issues/103032

This is just meant as a tracking issue on our side. I consider this bug a blocker for any meaningful `aarch64_be` progress with LLVM; I eventually gave up trying to disable affected behavior tests and std tests.

### Expected Behavior

No LLVM crash.

**Comment by alexrp** [comment]
Upstream bug has been fixed; I'll resume work on `aarch64_be` support once we upgrade to LLVM 19.

**Comment by andrewrk** [comment]
Fixed with the merge of LLVM 19 branch in c6ad4521c77372cb52adfb9a52b0854d830fed9c.
