### ISSUE TITLE
In 'run' mode, just warn about unchanged var and unused const

### ISSUE THREAD

**Issue by JoanaBLate** [ziglang/zig#21071]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Output

I understand and agree that Zig enforces good programming by *not compiling* code when some local var doesn't change and some local const is not used.

But during 'run' mode, which I use for writing code, this behavior is very annoying and unproductive:

1) I try to run the source code and receive error messages that are not clear to me (in part because I am new to Zig, in part because they are not clear and points the error somewhere else - like deep in the std library). 

2) Trying to isolate the error, I comment sections of the code, taking care to not break the logic.

3) Then Zig complains that some local variables should be constants because they don't change (the lines where they change were just commented).

4) I change their declarations to constants. Run the source code again and Zig complains that they are not used.

5) If I comment their lines, I may break the code or make another local variables/constants become rejected. Then I decide to discharge them (_ = myVar;).

6) Sometimes I uncomment a line then I got an error message saying that "_ = myVar;" is pointless.

7) Later I have to undo those editions. And sometimes I miss one or two undoings: more error messages.

It is a waste of time and patience. I lose a lot of time because of this lack of flexibility.

### Expected Output

During 'run' (development) mode, I would be very fine with just warnings.

Thanks.

**Comment by mlugg** [comment]
This has been rejected many times. Zig does not have warnings, by design. These are hard errors, by design.

See [here](https://ziggit.dev/t/error-local-variable-is-never-mutated/2238/42) for a detailed explanation of this decision.
