### ISSUE TITLE
builtin.TypeId has no member called 'EnumLiteral'

### ISSUE THREAD

**Issue by vegecode** [ziglang/zig#2113]
When compiling some code for armv7em freestanding eabihf in release safe mode, I recently get the error (latest master):
```
/home/alexander/Code/Docker/zig2/zig/build/output/install/lib/zig/std/hash_map.zig:493:23: error: con
tainer 'builtin.TypeId' has no member called 'EnumLiteral'
        builtin.TypeId.EnumLiteral,
                      ^
/home/alexander/Code/Docker/zig2/zig/build/output/install/lib/zig/std/hash_map.zig:446:28: note: call
ed from here
            return autoHash(key, &rng.random, u32);
```

I've just commented it out for now to keep moving.

Please let me know if there is any other information you need from me.

**Comment by andrewrk** [comment]
Did you update the standard library without updating the zig compiler?

d0551db5cd29e4c7f361ef40a37486138a4e8b1e introduced the enum literal type. You can see that builtin includes it here: https://ziglang.org/documentation/master/#Compile-Variables

**Comment by andrewrk** [comment]
Feel free to continue asking for help here, but I'm pretty sure there's no problem with zig.

**Comment by vegecode** [comment]
You're right, I was having problems with my build environment and so I'm using docker for the first time, which brings its own problems to resolve. I was having an issue with using the wrong binary from a previous compile. From now on I'll use 'zig version' to make sure it has the hash I expect.
