### ISSUE TITLE
Change SYS enum from usize to u8

### ISSUE THREAD

**Issue by LiamSwayne** [ziglang/zig#21163]
`usize` is unnecessarily large as it is highly unlikely that the SYS enum will require more than 255 items. Currently 7 out of 8 bytes are wasted, and it would make sense to change to a `u8`. ~14 files would need to be changed from what I can tell:

https://github.com/search?q=repo%3Aziglang%2Fzig+%22intFromEnum%28SYS%22&type=code

Plus the plan9 file would also need to be changed.

https://github.com/ziglang/zig/blob/5bf9dc3850117c85fb124cc481d4a284e2c8504d/lib/std/os/plan9.zig#L210

**Comment by LiamSwayne** [comment]
This would be a breaking change for uses of `@intFromEnum`.

**Comment by Rexicon226** [comment]
I encourage you to do a bit more research, and you will quickly find that the syscall numbers go larger than 255.

**Comment by nektro** [comment]
the size of the enum in this case is dictated by the kernel api; not how many tags there are
