### ISSUE TITLE
Consider removing T.bit_count and T.is_signed for @typeInfo(T).Int.bits and @typeInfo(T).Int.is_signed

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2117]
This is definitely breaking.

There are two ways to do the same thing when T is an integer:
```
T.bit_count
T.is_signed

@typeInfo(T).Int.bits
@typeInfo(T).Int.is_signed
```
The latter is a bit verbose, so I like the old syntax better. But if the old syntax stays it needs to be documented as part of the language, and the language would be simpler without the syntax, so I think it should go.

**Comment by tgschultz** [comment]
Replacing these builtins is one of the goals of the `meta` package, which contains:

```
pub fn bitCount(comptime T: type) comptime_int {
    return switch (@typeInfo(T)) {
        TypeId.Int => |info| info.bits,
        TypeId.Float => |info| info.bits,
        else => @compileError("Expected int or float type, found '" ++ @typeName(T) ++ "'"),
    };
}
```

and `meta.trait` contains:

```
pub fn isSignedInt(comptime T: type) bool {
    return switch (@typeId(T)) {
        builtin.TypeId.ComptimeInt => true,
        builtin.TypeId.Int => @typeInfo(T).Int.is_signed,
        else => false,
    };
}
```

related: #1104

Maybe we should make removing the builtins a 0.5.0 goal?

**Comment by andrewrk** [comment]
This issue is blocking on #425

**Comment by shawnl** [comment]
You are confusing this bug with #2128

**Comment by andrewrk** [comment]
No, I'm confirming what @tgschultz said and linking to the relevant issue which could potentially resolve it.
