### ISSUE TITLE
proposal: allow slicing single item pointers with runtime known u1

### ISSUE THREAD

**Issue by xdBronch** [ziglang/zig#21186]
i feel like i had seen this talked about before but cant find it so i apologize if this has been discussed before.

currently slicing a single item pointer requires both the start and end of the range to be comptime known, it must be `[0..0]`, `[0..1]`, or `[1..1]` but logically this isnt needed since the value of a u1 will always fit within these bounds.
```zig
const std = @import("std");
test {
    var t = true;
    _ = &t;
    var n: u32 = 1234;
    const a = (&n)[0..@intFromBool(t)];
    try std.testing.expect(a[0] == 1234);
}
```
this code fails
```
error: unable to resolve comptime value
    const a = (&n)[0..@intFromBool(t)];
                      ^~~~~~~~~~~~~~~
```
i propose that it should work when the start and/or end is a u1
one potential downside i see with this is that it causes the operation to return a slice `[]T` rather than the current array pointer `*[0]T`/`*[1]T`, i dont know if this would be considered a problem

**Comment by xdBronch** [comment]
not possible because of result types according to @mlugg :/

**Comment by nektro** [comment]
in discussion it was also mentioned you can do `(&n)[0..1][0..@intFromBool(t)];`
