### ISSUE TITLE
@bswap() and @bitreverse() should not implicitely cast

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2121]
These implicit casts change the results, which goes against the philosophy of implicit casts.
from the documentation:
```
Implicit casts are only allowed when it is completely unambiguous
how to get from one type to another, and the transformation is
guaranteed to be safe. <=====
```
See #2119 for more discussion.

Oh, we still need this implicit cast:
```
    // cast from typed number to integer or float literal.
    // works when the number is known at compile time
    if (instr_is_comptime(value) &&
        ((actual_type->id == ZigTypeIdInt && wanted_type->id == ZigTypeIdComptimeInt) ||
        (actual_type->id == ZigTypeIdFloat && wanted_type->id == ZigTypeIdComptimeFloat)))
    {
        return ir_analyze_number_to_literal(ira, source_instr, value, wanted_type);
    }
```
and this one:
```
    // cast from undefined to anything
    if (actual_type->id == ZigTypeIdUndefined) {
        return ir_analyze_undefined_to_anything(ira, source_instr, value, wanted_type);
    }
```

**Comment by andrewrk** [comment]
please elaborate

**Comment by shawnl** [comment]
For all the basic arithmetic operators (`*/+-` and more) up-casting does not effect the output, however:
```
shawn@shawn-ThinkPad-L420:~/projects/shared$ cat implicit.zig 
const std = @import("std");
pub fn main() void {
var i: u8 = 0b10101010;
std.debug.warn("{}\n", @bitreverse(u8, i));
std.debug.warn("{}\n", @bitreverse(u16, i));
std.debug.warn("{}\n", @bitreverse(u32, i));
std.debug.warn("{}\n", @bitreverse(u64, i));
std.debug.warn("{}\n", @bitreverse(u128, i));
var g: u16 = 0b1010101001010101;
std.debug.warn("{}\n", @bswap(u8, i));
std.debug.warn("{}\n", @bswap(u16, i));
std.debug.warn("{}\n", @bswap(u32, i));
std.debug.warn("{}\n", @bswap(u64, i));
std.debug.warn("{}\n", @bswap(u128, i));
}
shawn@shawn-ThinkPad-L420:~/projects/shared$ zig run implicit.zig 
85
21760
1426063360
6124895493223874560
112984379641717849196823600123829288960
170
43520
2852126720
12249790986447749120
225968759283435698393647200247658577920
```

**Comment by tgschultz** [comment]
What is our reasoning for taking a type? It seems to me that these functions should always return the type they were given. You can use comptime values by casting to the desired type: `@bitreverse(i8(-10));`. This reasoning should also apply to #2119.

**Comment by shawnl** [comment]
OK, remove all types from the bit functions. I can also get behind that. That is consistent.

**Comment by andrewrk** [comment]
I think the explicit type parameter is enough to make it clear to the callsite what is happening. This proposal sounds like you want to make there be a compile error if the integer type of the parameter does not match exactly the provided explicit type parameter. I don't think that makes sense. It would be the only function where the parameter at the callsite does not get implicitly casted to the parameter type of the function.

**Comment by shawnl** [comment]
> This proposal sounds like you want to make there be a compile error if the integer type of the parameter does not match exactly the provided explicit type parameter. It would be the only function where the parameter at the callsite does not get implicitly casted to the parameter type of the function.

You are missing the fact that these implicit cast are **unsafe**, and in the docs, 
```
 Zig has Implicit Casts for conversions that are known to be **completely safe** and unambiguous,
```
There is only one safe implicit cast we can do, and that is up-casting for `@popCount` when the argument is unsigned. I already have this code working and tested, with test cases.

**Comment by andrewrk** [comment]
Here's the proposal on the table, extracted from the open pull request:

```zig
comptime {
    var i: u8 = 3;
    _ = @bswap(u16, i);
}
```

Instead of casting i to u16, it would give: `"tmp.zig:3:9: error: upcasting 'u8' to 'u16' changes result"`.

To accomplish the implicit cast, the user would do:

```zig
comptime {
    var i: u8 = 3;
    _ = @bswap(u16, u16(i));
}
```

That seems a bit redundant to me. The first u16 already implies the width of the bswap that will happen. In both of these cases, numerical value `3` is bswapped with a width of u16, which has the same result.

The statement from the docs is true regardless; the implicit cast from u8 to u16 does not change the numerical value.

**Comment by shawnl** [comment]
> The statement from the docs is true regardless; the implicit cast from u8 to u16 does not change the numerical value.

But it changes the result of the `@bSwap` operation, while most operations (`* - / +`) are not changed by this cast, _especially_ because overflow is undefined. I read the docs as prohibiting an implicit cast here.

Not having this is a foot-gun.

That said, I am missing that with these functions you can safely cast from positive to negative and visa-versa, so I want to allow that implicit cast for these.

**Comment by shawnl** [comment]
> In both of these cases, numerical value 3 is bswapped with a width of u16, which has the same result.

No. the result to `@bSwap(u8, u8(3))` is 3, while the result of `@bSwap(u16, u16(3))` is 768. I think you just proved my point about the foot-gun.

**Comment by andrewrk** [comment]
Those are not the examples I used in my comment.

**Comment by shawnl** [comment]
I take it that you are saying that if it can implicitly cast elsewhere, why not here? I guess for `@bSwap` I can see that your case is a valid one (I can't think of any good ones for the other functions, except `@ctz` when you want the result on 0 to be differn't), but if the user wants to convert endianness they should probably use our std lib functions for that.

**Comment by shawnl** [comment]
On the other hand, by treating the bit manipulation function special regarding implicit casting, we can implicitly cast i32 -> u32 and u32 -> i32, which is something I have dealt with already, and is annoying.

**Comment by shawnl** [comment]
I am not too worried about these widening casts when the raw type is given to these functions. What I am worried about is when a named type is used.

**Comment by tgschultz** [comment]
```
comptime {
    var i: u8 = 3;
    _ = @bswap(u16, u16(i));
}
```
I agree that this is redundant, but I guess what I'm confused about is why we should solve it with implicit casting instead of simply removing the type paramter?

```
comptime {
    var i: u8 = 3;
    _ = @bswap(u16(i));
}
```
To me, this is slightly more clear that the upcast to u16 will occur before the byteswap. Consider also this code:

```
comptime {
    var i: u16 = 3;
    _ = @bswap(u16, i);
}
```
which is still redundant, vs:
```
comptime {
    var i: u16 = 3;
    _ = @bswap(i);
}
```

**Comment by shawnl** [comment]
Well, while I got these to accept a type, the implicit typing changes I want are not in there due to technical issues. Namely: I don't know how to get the (real) InstructionId and arg number in ir_analyze_cast(), which is only passed the IrInstruction of the argument, not of the operator.

**Comment by shawnl** [comment]
Also, `@memcopy` should implicitely cast from anything.
