### ISSUE TITLE
Avoid LLVM API for setting a module's code model and PIC/PIE levels

### ISSUE THREAD

**Issue by alexrp** [ziglang/zig#21238]
See: https://github.com/ziglang/zig/pull/21224/files#r1734518792

We should be able to do this with our own bitcode writer just fine as these are just module flags.

**Comment by jacobly0** [comment]
This is a bug because if you want to use the emitted bitcode it will have the incorrect module flags as `ZigLLVMSetModule*` won't have been called yet.
