### ISSUE TITLE
Wrong function path referenced in compiler error

### ISSUE THREAD

**Issue by Teln0** [ziglang/zig#21242]
I think I found an issue similar to #12409 here : https://github.com/ziglang/zig/blob/e9a00ba7f4ef2546cd0c98559002431c749374fe/lib/std/hash_map.zig#L18

I made sure this error message could be seen by the user (by doing)
```zig
comptime {
    _ = std.hash_map.getAutoHashFn([]const u8, struct {});
}
```

**Comment by mlugg** [comment]
Issue is missing observed and expected output. Please follow the issue template.

**Comment by Teln0** [comment]
Sorry, I created the issue by clicking "create issue referencing this line" on github, I didn't know there were templates, I'm making a new issue
