### ISSUE TITLE
Support importing <*mmintrin.h> <arm_neon.h> (and <altivec.h> for ppc64le)

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2124]
These are the Intel, Arm, and PPC SIMD intrinsic C language extensions, which gcc and clang support. This is an alternative to writing assembly or using generalized vector support, and will probably be quite useful to augment generalized vector support. While we have integrated clang, so C code can call these, if they are imported using `@cImport()` they will not work. These can obviously be hooked up to zig outside of `@cImport()` but they should be supported both ways.

**Comment by andrewrk** [comment]
not enough details
