### ISSUE TITLE
Can't cast variable length data to slice ([]u8 in this case).

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2126]
I should be able to do this:
```
var char: u21 = undefined;
var hex_escape_bytes: u2 = undefined;
...
                std.fmt.hexToBytes(@ptrCast(*[hex_escape_bytes]u8, &char).*[0..],
                    char_token[2...2 + hex_escape_bytes]) catch unreachable;
```
Its not a VLA because it is being cast to a slice.

I don't need to use `hexToBytes`, I can just use `charToDigit` directly (i also don't want to create the slice manually), but I wanted to note this.

**Comment by shawnl** [comment]
related to  #863

**Comment by shawnl** [comment]
It would be nice if this could be done in a way that preserved the bounds checking.

**Comment by andrewrk** [comment]
not a valid example because `hex_escape_bytes` is a runtime value.
