### ISSUE TITLE
`lld-link: error: undefined symbol: __declspec(dllimport) WSAGetLastError` while compile cpp-httplib

### ISSUE THREAD

**Issue by ImFl0wow** [ziglang/zig#21274]
### Zig Version

0.14.0-dev.1391+e084c46ed

### Steps to Reproduce and Observed Behavior

I forked a third party library [here](https://github.com/yhirose/cpp-httplib)

try to compile the example use

`zig c++ hello.cc --target=x86_64-windows-gnu`

and this happened

`lld-link: error: undefined symbol: __declspec(dllimport) WSAGetLastError`

### Expected Behavior

i tried to use mingw to compile `hello.cc`

it works well

**Comment by alexrp** [comment]
Did you try with `-l ws2_32`?

**Comment by ImFl0wow** [comment]
> Did you try with `-l ws2_32`?

it works, thanks
