### ISSUE TITLE
Format Error does not say which source code line was wrong

### ISSUE THREAD

**Issue by jonasdiemer** [ziglang/zig#21283]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

Clone https://github.com/jonasdiemer/zig-llm
Switch to commit 02836e22327565e0f5d4d4989d773c9ddba9c79f
cd into example
run `zig build run`

Zig exits with an error:
```
run
└─ run example
   └─ zig build-exe example Debug native 1 errors
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/fmt.zig:632:21: error: cannot format slice without a specifier (i.e. {s} or {any})
                    @compileError("cannot format slice without a specifier (i.e. {s} or {any})");
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    format__anon_9848: /opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/fmt.zig:185:23
    print__anon_5772: /opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/io/Writer.zig:24:26
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

```

### Expected Behavior

Error about formatting slice with pointer to `example/src/main.zig` line 21.

**Comment by jonasdiemer** [comment]
This seems to be the same as https://github.com/ziglang/zig/issues/16892, but it doesn't seem fixed (i.e. error occurs in 0.13.0).

**Comment by Vexu** [comment]
If you add `-freference-trace` to the command like the error message suggests it will show where the error is coming from:
```
run
└─ run example
   └─ install
      └─ install example
         └─ zig build-exe example Debug native 1 errors
/home/vexu/Documents/zig/zig/lib/std/fmt.zig:644:21: error: cannot format slice without a specifier (i.e. {s} or {any})
                    @compileError("cannot format slice without a specifier (i.e. {s} or {any})");
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    format__anon_8576: /home/vexu/Documents/zig/zig/lib/std/fmt.zig:188:23
    print__anon_4634: /home/vexu/Documents/zig/zig/lib/std/io/Writer.zig:24:26
    print__anon_1971: /home/vexu/Documents/zig/zig/lib/std/io.zig:324:47
    main: src/main.zig:21:20
    posixCallMainAndExit: /home/vexu/Documents/zig/zig/lib/std/start.zig:615:37
    _start: /home/vexu/Documents/zig/zig/lib/std/start.zig:422:40
    comptime: /home/vexu/Documents/zig/zig/lib/std/start.zig:92:63
    start: /home/vexu/Documents/zig/zig/lib/std/std.zig:101:27
    comptime: /home/vexu/Documents/zig/zig/lib/std/std.zig:160:9
```

**Comment by jonasdiemer** [comment]
Thanks @Vexu  for the response. I should have included that in the initial post. Tried it, didn't provide a meaningful pointer, i.e. all of the mentioned references are within zig codebase, not my project (or maybe I missed it?):

```
❯ zig build -freference-trace run
run
└─ run example
   └─ zig build-exe example Debug native 1 errors
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/fmt.zig:632:21: error: cannot format slice without a specifier (i.e. {s} or {any})
                    @compileError("cannot format slice without a specifier (i.e. {s} or {any})");
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    format__anon_9852: /opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/fmt.zig:185:23
    print__anon_5773: /opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/io/Writer.zig:24:26
    print: /opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/io.zig:324:47
    print__anon_10492: /opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/debug.zig:97:21
    unexpectedErrno: /opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/posix.zig:7319:24
    write: /opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/posix.zig:1235:34
    write: /opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/fs/File.zig:1281:17
    Writer: /opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/fs/File.zig:1543:48
    writer: /opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/fs/File.zig:1545:27

```

**Comment by Vexu** [comment]
Thats #16725, you should get similar output to mine with that master branch build you referenced.

**Comment by jonasdiemer** [comment]
Maybe an (obvious) comment: I assume this error is rather common (with noobs) - is the `-freference-trace` option a workaround? It would be better to "just" get the correct pointer to the error without the noise...

**Comment by castholm** [comment]
> Maybe an (obvious) comment: I assume this error is rather common (with noobs) - is the `-freference-trace` option a workaround? It would be better to "just" get the correct pointer to the error without the noise...

3c2a43fdcc2d9aeafafe7ef37c7b805e18fac351 (which reverted a fix to #14492), suggests the following future improvement:

> One thing that might be useful would be having the compiler be aware of
module boundaries and highlighting the boundaries of them. The first
reference note after crossing a module boundary is likely the most
interesting one.

I'm not aware of any issue that directly tracks that idea, but it would probably be useful if at least one reference to the user's code was included in the trace without needing to specify `-freference-trace`.

**Comment by MGilleronFJ** [comment]
I keep trying to find existing issues regarding this, but I'm using Zig 0.13 and every single time I get a formatting wrong, I can't get any useful information from the compiler. By default it doesn't say, so I use `-freference-trace`, which gives me trace**s**, but very often, none of them are correct, and that still doesn't tell me *which one exactly*, it's like the compiler is saying "maybe it's one of these" and I still have to find out. With a codebase getting large, it gets increasingly difficult to find.
So far the only way I reliably get out of this, is by modifying `fmt.zig` itself to add bunch of prints in the hopes of getting enough context.

**Comment by mlugg** [comment]
@MGilleronFJ

a) This should be fixed on master, yes.
b) If it were still a bug, your comment would be useless without a set of steps to reproduce.
