### ISSUE TITLE
change \uXXXX \UXXXXXX string literal escape syntax to \u{}

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2129]
Extracted from https://github.com/ziglang/zig/issues/2097#issuecomment-477824384

This matches (thanks @daurnimator for doing the research):
 * javascript (since ES6)
 * lua (since 5.3)
 * swift (who swapped from our current syntax!)
 * rust

**Comment by binary132** [comment]
Why are braces necessary for Unicode but not for hexadecimals?  This feels inconsistent.

**Comment by Hejsil** [comment]
@binary132 Probably because `\u` can be variable length, so we need a way to specify where the end of the escape sequence is. Is `\u000000` `\u{0000}00` or `\u{000000}`?

**Comment by andrewrk** [comment]
For this particular syntax, cross language consistency is more valuable than self consistency.

Hexadecimal escapes are always 2 digits. Unicode escapes used to always be 4 digits. But then 6 became possible with changes to Unicode. So here we are.
