### ISSUE TITLE
`@divExact` provides no safety guarantee for runtime-known float operands

### ISSUE THREAD

**Issue by amp-59** [ziglang/zig#21301]
### Zig Version

 0.14.0-dev.1411+a670f5519

### Steps to Reproduce and Observed Behavior

Compile and run example program with `zig run div_exact_runtime_float_error.zig`
`div_exact_runtime_float_error.zig`:
```zig
pub fn main() void {
    var f: f32 = 3.0;
    f = @divExact(f, 2.0);
}
```
Output:
```
zig run div_exact_runtime_float_error.zig

```

### Expected Behavior

The program above should panic at runtime with panic ID `exact_division_remainder`.

Running an equivalent program at compile time will yield the expected outcome.

Compile example program with `zig build-obj div_exact_comptime_float.zig`
`div_exact_comptime_float.zig`:
```zig
comptime {
    var f: f32 = 3.0;
    f = @divExact(f, 2.0);
}
```
Output:
```
zig build-obj div_exact_comptime_float.zig
div_exact_comptime_float.zig:3:9: error: exact division produced remainder
    f = @divExact(f, 2.0);
        ^~~~~~~~~~~~~~~~~
```

**Comment by chenzhekl** [comment]
This might be related to #19651, which in on track for 0.14.0
