### ISSUE TITLE
package manager can't download from bitbucket - Content-Type application/x-tar-gz

### ISSUE THREAD

**Issue by travisstaloch** [ziglang/zig#21314]
### Zig Version

0.14.0-dev.1398+c34cfe486

### Steps to Reproduce and Observed Behavior

Given a bitbucket url such as the following (which was found [here](https://bitbucket.org/archaistvolts2/zig-btree/downloads/?tab=branches)).
```zig
// build.zig.zon
.dependencies = .{
        .@"zig-btree" = .{
            .url = "https://bitbucket.org/archaistvolts2/zig-btree/get/66e663379847757077d2b38e622318a77e8aa44d.tar.gz",
```
This error is shown.
```console
$ zig version
0.14.0-dev.1398+c34cfe486
$ zig build
.../Code/zig/btreemapbuild.zig.zon:8:20: error: unrecognized 'Content-Type' header: 'application/x-tar-gz; charset=utf-8'
            .url = "https://bitbucket.org/archaistvolts2/zig-btree/get/66e663379847757077d2b38e622318a77e8aa44d.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is only an issue for the .tar.gz url and not for the .zip url.

This diagnostic message is also missing a final '/'.  I have omitted the beginning of the path.
```console
.../Code/zig/btreemapbuild.zig.zon:8:20:
```
But should be.
```console
.../Code/zig/btreemap/build.zig.zon:8:20:
```

### Expected Behavior

The package manager should be able to download the package.  And the diagnostic path should include a final '/'.

**Comment by truemedian** [comment]
This nonstandard mimetype should be added to the list of `.tar.gz` mime types in <https://github.com/ziglang/zig/blob/master/src/Package/Fetch.zig#L1068-L1070>

**Comment by travisstaloch** [comment]
Thanks!  I'll PR a patch which adds that line.

**Comment by travisstaloch** [comment]
I think this patch would solve the diagnostic missing trailing '/' issue.  But I'm not sure if there should be a runtime check that `f.parent_package_root` doesn't end with `std.fs.path.sep_str`.  Can anyone confirm this is correct?

```diff
diff --git a/src/Package/Fetch.zig b/src/Package/Fetch.zig
index 2540cf9922..4272a71733 100644
--- a/src/Package/Fetch.zig
+++ b/src/Package/Fetch.zig
@@ -770,7 +770,7 @@ fn srcLoc(
     const eb = &f.error_bundle;
     const token_starts = ast.tokens.items(.start);
     const start_loc = ast.tokenLocation(0, tok);
-    const src_path = try eb.printString("{}" ++ Manifest.basename, .{f.parent_package_root});
+    const src_path = try eb.printString("{}" ++ std.fs.path.sep_str ++ Manifest.basename, .{f.parent_package_root});
     const msg_off = 0;
     return eb.addSourceLocation(.{
         .src_path = src_path,
```
