### ISSUE TITLE
(WASM) std.mem.span(@ptrFromInt(ptr_usize)) returns 0 length slice unless I do std.mem.span(@ptrFromInt(ptr_usize+1-1))

### ISSUE THREAD

**Issue by Airtune** [ziglang/zig#21321]
### Zig Version

0.14.0-dev.1472+3929cac15

### Steps to Reproduce and Observed Behavior

I have this snippet that I compile to WASM:
`main.zig`
```zig
const std = @import("std");
const _string_param1_ptr: [256]u8 = .{0} ** 256;

pub fn parse_string_param1() []const u8 {
    const ptr: [*:0]u8 = @ptrFromInt(string_param1_ptr());
    const string_param1: []const u8 = std.mem.span(ptr);
    return string_param1;
}

export fn string_param1_ptr() usize {
    // std.mem.span above returns slice with len = 0 if I don't include `+ 1 - 1`
    return @intFromPtr(&_string_param1_ptr[0]) + 1 - 1;
}
```

Build wasm with the command:
`zig build-exe main.zig -target wasm32-freestanding -fno-entry -rdynamic -O ReleaseSmall`

```js
      // this.wasm_module = await WebAssembly.instantiateStreaming(fetch(wasm_url), { ... });
      const image_name = "hello";
      const string_param1_ptr = this.wasm_exports.string_param1_ptr();
      const string_param1_buffer = new Uint8ClampedArray(this.wasm_exports.memory.buffer, string_param1_ptr, 256);
      const encoded_image_name = new TextEncoder().encode(image_name);
      const trunc_encoded_image_name = encoded_image_name.subarray(0, 255);
      for (let i = 0; i  < trunc_encoded_image_name.length; i++) {
        string_param1_buffer[i] = trunc_encoded_image_name[i];
      }
      string_param1_buffer[trunc_encoded_image_name.length] = 0;
```

I see the bytes are being set correctly and I can read them correctly manually from both javascript/HTML and Zig/WASM

I also tested this on Zig v0.12.1 with the same result

### Expected Behavior

I expected `std.mem.span(ptr)` to return the same result, a slice with "hello" encoded, for both these functions:
```zig
export fn string_param1_ptr() usize {
    return @intFromPtr(&_string_param1_ptr[0]);
}
```

```zig
export fn string_param1_ptr() usize {
    return @intFromPtr(&_string_param1_ptr[0]) + 1 - 1;
}
```

**Comment by rohlem** [comment]
I'm confused why you're declaring `_string_param1_ptr` (which is the array, not a pointer) as `const`.
If you intend to modify it, it should be a `var`. (I also wouldn't name it `ptr` when it isn't one.)

The compiler probably sees that it's `const` and assumes that its memory won't change (will stay fully 0), which is a valid assumption to make imo.
The `+ 1 - 1` probably confuses it and leads it to believe it has to generate runtime code that delays checking the contents.

**Comment by Airtune** [comment]
Changing `const` to `var` solved my issue.

Also thanks for the feedback on naming.
