### ISSUE TITLE
Test names with spaces don't properly get wrapped in `@""` in type names

### ISSUE THREAD

**Issue by NicoElbers** [ziglang/zig#21346]
### Zig Version

0.14.0-dev.1509+fb81522e0

### Steps to Reproduce and Observed Behavior

`bar.zig`:
```zig
test "name with spaces" {
    const T = enum {};
    const name = @typeName(T);

    @import("std").debug.print("name: {s}\n", .{name});
}
```

Observe:
```
❯ zig test bar.zig
name: bar.test.name with spaces.T
All 1 tests passed.
```

### Expected Behavior

I would expect the identifier with spaces be wrapped in `@""` (`bar.test.@"name with spaces".T`). 

This already happens for buitin types for example `fn () @typeInfo(@typeInfo(@TypeOf(foo.foo)).@"fn".return_type.?).error_union.error_set!void)` (note the `.@"fn"`), so I see no reason why tests should be excluded

**Comment by nektro** [comment]
those test names are the symbol names in the binary, not pseudo zig identifiers

**Comment by NicoElbers** [comment]
I understand that in no way is this required, in fact it's just a very small stylistic error, but in my mind when I call `@typeName` whatever comes out is, well, a zig type. 

The main idea behind this issue is to get a little bit more coherence in general, but I fully understand this would be more of a pain to implement than it would help

**Comment by mlugg** [comment]
`@typeName` isn't necessarily meant to be a valid Zig expression -- as identified by nektro above, `test.@"name with spaces"` wouldn't make sense as this is not a symbol which actually exists within the `bar` namespace.
