### ISSUE TITLE
Autodoc: code block is rendered incorrectly

### ISSUE THREAD

**Issue by prajwalch** [ziglang/zig#21358]
### Zig Version

0.14.0-dev.1510+fb0028a0d

### Steps to Reproduce and Observed Behavior

I have a function like this:

```zig
/// Appends the new argument to the list of arguments.
///
/// **NOTE:** It returns an `error.DuplicatePositionalArgIndex` when attempting
/// to append two positional arguments with the same index. See the examples below.
///
/// ## Examples
///
/// ```zig
/// var app = App.init(allocator, "myapp", "My app description");
/// defer app.deinit();
///
/// var root = app.rootCommand();
/// try root.addArg(Arg.booleanOption("version", 'v', "Show version number"));
///
/// var test = app.createCommand("test", "Run test");
/// try test.addArg(Arg.positional("FILE", null, null));
/// ```
///
/// Appending two positional arguments with the same index.
///
/// ```zig
/// var app = App.init(allocator, "myapp", "My app description");
/// defer app.deinit();
///
/// var root = app.rootCommand();
/// try root.addArg(Arg.positional("FIRST", null, 1));
/// // Returns `error.DuplicatePositionalArgIndex`.
/// try root.addArg(Arg.positional("SECOND", null, 1));
/// ```
pub fn addArg(self: *Command, arg: Arg) !void { ... }
```

When I generate and look at the documentation page, I got:

![Screenshot 2024-09-09 at 12-30-24 test Command - Zig Documentation](https://github.com/user-attachments/assets/11c66ef2-0fff-4823-9624-7a9063a2b503)

## Another example

```zig
/// Appends multiple arguments to the list of arguments.
///
/// ## Examples
///
/// ```zig
/// var app = App.init(allocator, "myapp", "My app description");
/// defer app.deinit();
///
/// var root = app.rootCommand();
/// try root.addArgs(&[_]Arg {
///     Arg.singleValueOption("firstname", 'f', "First name"),
///     Arg.singleValueOption("lastname", 'l', "Last name"),
/// });
///
/// var address = app.createCommand("address", "Address");
/// try address.addArgs(&[_]Arg {
///     Arg.singleValueOption("street", 's', "Street name"),
///     Arg.singleValueOption("postal", 'p', "Postal code"),
/// });
/// ```
pub fn addArgs(self: *Command, args: []const Arg) !void {
    for (args) |arg| try self.addArg(arg);
}
```

![Screenshot 2024-09-09 at 12-36-20 test Command - Zig Documentation](https://github.com/user-attachments/assets/cf041789-3c3c-4b9f-becd-7aea4eb0b3a7)

### Expected Behavior

I expected correct rendering.

**Comment by rohlem** [comment]
Right now I couldn't find it, but I remember a comment from andrew that [doctests](https://ziglang.org/documentation/master/#Doctests) should be preferred to code blocks in doc comments, since they also appear in documentation but are additionally run as tests making them easier to stay in sync with changes in the implementation.
This also generates an "Example Usage" section designed specifically for this.

**Comment by prajwalch** [comment]
I am ok with the `doctests` but embedding the code block in the docstring is common and should be supported.
