### ISSUE TITLE
`zig build --help` should help with `build`, not build then help

### ISSUE THREAD

**Issue by mnemnion** [ziglang/zig#21351]
### Zig Version

0.14.0-dev.994+9f46abf59, 0.13.0

## Reproduce: A

Execute `zig build --help` in a directory with no `build.zig`

### Observe 

Outputs:

```sh
info: initialize build.zig template file with 'zig init'
info: see 'zig --help' for more options
error: no build.zig file found, in the current directory or any parent directories
````

## Reproduce: B

Execute `zig build --help` in a directory _with_ a `build.zig`.

### Observe

The project is built, then the help info is printed.

### Expected Behavior

Print help info, and quit, without attempting to build, or building, the project.

**Comment by Rexicon226** [comment]
This is impossible since the `--help` message includes the steps and options that are available.

**Comment by mnemnion** [comment]
It's definitely possible to print the generic parts of the help file when there's no build.zig. 

Point taken about building the script before printing the help for it, though.  It appears to just build the script, not the project, since making changes to the project does not retrigger a build for `zig build --help`, but does for plain `zig build`. 

I still think bailing without printing the help file when no `build.zig` is present is suboptimal behavior.

**Comment by mlugg** [comment]
Duplicate of rejected #7397, #15154.

**Comment by xdBronch** [comment]
https://github.com/ziglang/zig/blob/54b668f8a33e8466e4771e12f50069a068244640/lib/compiler/build_runner.zig#L1232-L1362
there is no "generic part", every piece of the help menu comes from something that has to be built first. the non build.zig related stuff is part of the build runner, the build runner depends on build.zig, and naturally the build.zig depends on itself working/existing

**Comment by mnemnion** [comment]
Right underneath that:

https://github.com/ziglang/zig/blob/54b668f8a33e8466e4771e12f50069a068244640/lib/compiler/build_runner.zig#L1241-L1289

It even says "General Options".  I maintain that it would be reasonable, more helpful, and also, easy, for Zig to print the general options along with the error message.  

That this is the more desirable behavior is fairly obvious from the fact that three people have seen what Zig does instead, and filed a bug about it.  There might be some sort of principled reason why these issues have been closed, but not one recorded in the issues themselves.

Enjoy closing the next one I guess.

**Comment by xdBronch** [comment]
the build runner can be swapped out, those general options may not be valid when using a different one

**Comment by mnemnion** [comment]
Point being? 

That only happens when the build runner is, in fact, swapped out. If the ENV variable is set, then yeah, the other build runner gets to deal with the arguments.

This has no bearing one way or the other on the behavior when that isn't the case.  A custom build runner should _also_ deal with `--help` in a useful way.

**Comment by andrewrk** [comment]
I reopened #15154 to track this.
