### ISSUE TITLE
Autodoc: empty lines are being rendered after the each docstring line in the source code page

### ISSUE THREAD

**Issue by prajwalch** [ziglang/zig#21360]
### Zig Version

0.14.0-dev.1510+fb0028a0d

### Steps to Reproduce and Observed Behavior

Given a function:

```zig
/// Appends the new subcommand to the list of subcommands.
///
/// ## Examples
///
/// ```zig
/// var app = App.init(allocator, "myapp", "My app description");
/// defer app.deinit();
///
/// var root = app.rootCommand();
///
/// var test = app.createCommand("test", "Run test");
/// try test.addArg(Arg.positional("FILE", null, null));
///
/// try root.addSubcommand(test);
/// ```
pub fn addSubcommand(self: *Command, new_subcommand: Command) !void { ... }
```

This is what the source code of it looks like in the source page:
![image](https://github.com/user-attachments/assets/8d280953-6d0f-4499-9193-7ff1d3b0efb2)

### Expected Behavior

I expected correct rendering :)

**Comment by Vexu** [comment]
Can't reproduce on `0.14.0-dev.1513+de8cece6e` with `zig build-exe a.zig -femit-docs`:
```zig
/// Appends the new subcommand to the list of subcommands.
///
/// ## Examples
///
/// ```zig
/// var app = App.init(allocator, "myapp", "My app description");
/// defer app.deinit();
///
/// var root = app.rootCommand();
///
/// var test = app.createCommand("test", "Run test");
/// try test.addArg(Arg.positional("FILE", null, null));
///
/// try root.addSubcommand(test);
/// ```
pub fn main() void {
}

```

![image](https://github.com/user-attachments/assets/af865466-3d51-4a6d-bf60-67087aab2b9b)

**Comment by Vexu** [comment]
Does it reproduce on the snippet I gave? And I'm on Linux.

**Comment by prajwalch** [comment]
> Does it reproduce on the snippet I gave? And I'm on Linux.

It doesn't.

**Comment by prajwalch** [comment]
Yes, changing the CRLF to LF solves the problem.
