### ISSUE TITLE
memory allocation after deinit results in strange behaviour

### ISSUE THREAD

**Issue by emar-kar** [ziglang/zig#21363]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    const allocator = gpa.allocator();
    _ = gpa.deinit();
    const memory = try allocator.create(u8);
    allocator.destroy(memory);
}
```

This code results in `trace trap` on MacOS arm64 and hangs on Linux aarch64

### Expected Behavior

Same `General protection exception (no address available)` error with trace which is printed on Linux x86_64

**Comment by xdBronch** [comment]
deiniting completely invalidates the entire allocator, what youre doing is very wrong and relying on undefined behavior, it shouldnt be expected to behave the same

**Comment by mocompute** [comment]
In my opinion, Zig will at some point want to enhance its static analysis and safety checks to help programmers catch errors like this (forgetting a defer).

For example, Debug and Safe builds could return an error on the allocator.create() if the allocator has been deinit'd.

It would be nice to collect examples like this somewhere for when that time comes.
