### ISSUE TITLE
Invalid code compiles in comptime

### ISSUE THREAD

**Issue by PanSashko** [ziglang/zig#21405]
### Zig Version

0.14.0-dev.1550+4fba7336a

### Steps to Reproduce and Observed Behavior

The following code compiles

```zig
test {
    const x: ?u32 = 10;
    _ = comptime if (x) x.f();
}
```

That might cause a confusing bug in more complex cases, when the function `f` actually exists in `x`.

### Expected Behavior

Like without `comptime` the compilation should fail with

```
error: expected type 'bool', found '?u32'
```

**Comment by mlugg** [comment]
Caused by `.condbr_inline` case (and equivalent code in the `.condbr` case) in `Sema.analyzeBodyInner` missing the required coercion to `bool`; see `Sema.zirCondbr` for the runtime context which performs the proper coercion.
