### ISSUE TITLE
error: unsupported linker arg: -x

### ISSUE THREAD

**Issue by cinemast** [ziglang/zig#21429]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

Cross compiling a CGO application from Windows to Mac OSX arm64

### Expected Behavior

Cross compilation works

**Comment by alexrp** [comment]
There is not enough information to go on here. I can guess from `man ld` that this might be referring to the short form of `--discard-all`, but without seeing the full `zig cc` invocation, it really is just a guess.

**Comment by mark-rushakoff** [comment]
Maybe close this in favor of #21721?
