### ISSUE TITLE
The example can't compiled

### ISSUE THREAD

**Issue by Clownsw** [ziglang/zig#21466]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() !void {
	const n65535: u65535 = 65534;
	std.debug.print("{}", .{ n65535 });
}
```

Compilation stuck on Windows

### Expected Behavior

to be compiled

**Comment by Rexicon226** [comment]
I think the right tracking issue for this is #20340.
