### ISSUE TITLE
Crash initializing a union

### ISSUE THREAD

**Issue by wooster0** [ziglang/zig#21462]
### Zig Version

0.14.0-dev.1588+2111f4c38

### Steps to Reproduce and Observed Behavior

```zig
var a: union { b: u32 } = undefined;
export fn x() void {
    a = .{ .b = 0 };
}
```
```
$ zig build-obj x.zig
Trace/breakpoint trap
```

### Expected Behavior

Successful compilation

**Comment by wooster0** [comment]
Doesn't seem to happen if the union is packed or extern

**Comment by wooster0** [comment]
This has to be a regression

**Comment by Vexu** [comment]
Duplicate of #19832
