### ISSUE TITLE
aarch64 bare metal uses FP&SIMD registers when neon and fp are disabled

### ISSUE THREAD

**Issue by gaosui** [ziglang/zig#21473]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

Code generated for aarch64-freestanding-none uses the FP register Q0 when neon, fullfp16 and fp_armv8 are disabled.

Build command:
```shell
 zig build-exe -target aarch64-freestanding-none -mcpu cortex_a76-neon-fp_armv8-fullfp16 -fentry=main -femit-llvm-ir example.zig
``` 

Example code:
```zig
const Object = struct {
    // At least two 64-bit fields are required to trigger this.
    a: u64,
    b: u64,

    // First function lets compiler to decide passing self by copy or pointer.
    fn func1(self: Object) void {
        // Just to make use of all fields on self.
        const sum = self.a + self.b;

        // !!!!! Assembly before calling func2 uses fp register q0.
        _ = self.func2(sum);
    }

    // Second function specifies passing self by pointer.
    fn func2(self: *const Object, val: u64) u64 {
        // Make use of self and the input val.
        const result = val + self.a + self.b;
        return result;
    }
};

// Export to make linker discover it as bare metal entry point.
export fn main() void {
    const obj = Object{
        .a = 1,
        .b = 2,
    };

    obj.func1();
}
``` 

Assembly before the call to func2 uses q0:
```assembly
ldr    q0, [x8]
sub    x0, x29, #0x10
stur   q0, [x29, #-16]
bl      10103c0 <example.Object.func2>
```
The use of FP register might have originated from llvm memcpy
```
call void @llvm.memcpy.p0.p0.i64(ptr align 8 %1, ptr align 8 %0, i64 16, i1 false), !dbg !280
%10 = call fastcc i64 @example.Object.func2(ptr nonnull readonly align 8 %1, i64 %9), !dbg !281
``` 

### Expected Behavior

Expected ARM FP registers Qn, Dn, Sn, Hn, Bn to be avoided when FP&SIMD features are excluded from the target CPU.  

However I cannot claim that the presence of FP registers is defined by these features. For example in #16957, a neon instruction is used regardless of the feature specification. In my case only FP registers are used, not instructions. It could be the intended behavior after all, that excluding these features don't forbit the use of FP registers in non-FP instructions.

**Comment by alexrp** [comment]
Just to be clear: Is this causing an actual problem?

The way I'm interpreting the Arm v8-A manual, the FP/SIMD registers are architecturally required even if `FEAT_FP`/`FEAT_AdvSIMD` aren't available.

**Comment by gaosui** [comment]
Thanks for replying Alex,

It's desirable for kernel development to be able to avoid FP registers all together. 
The example code is a simplified version of my bare metal device tree parser. 

My workarounds are:
1. Passing self by reference avoids the memcpy. However there's no guarantee that other code patterns don't have hidden memcpy.
2. Using release build optimizes the memcpy away. However that just makes debugging a lot harder when I need to.

Thanks for digging through the manual, I agree with your interpretation. Maybe that's why gcc and clang have `-mgeneral-regs-only` specifically for aarch64 to avoid FP registers, since excluding CPU features alone won't do it. Would zig support something like that as well?

**Comment by alexrp** [comment]
From a quick look through Clang/LLVM, it seems that `-mgeneral-regs-only` ultimately results in disabling the `fp_armv8` target feature (and by extension `neon`, etc). Nothing more, nothing less AFAICT.

So the question here is why `-neon-fp_armv8-fullfp16` doesn't achieve the same with Zig, I suppose.
