### ISSUE TITLE
std.mem.sortUnstable() sometimes alters data

### ISSUE THREAD

**Issue by michaelortmann** [ziglang/zig#21483]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

```
    var x: usize = 0;
    for (items) |item|
        x += item.count;

    std.mem.sortUnstable(Item, items, {}, cmp);

    var y: usize = 0;
    for (items) |item|
        y += item.count;

    try std.testing.expectEqual(x, y);
    std.debug.print("x == y == {}\n", .{x});
```

There is no magic in `Item` or `cmp()`:

```
const Item = struct { word: []const u8, count: u32 };

fn cmp(context: void, a: Item, b: Item) bool {
    _ = context;

    if (a.count == b.count)
        return std.mem.order(u8, a.word, b.word).compare(std.math.CompareOperator.lt);

    if (a.count < b.count)
        return false;

    return true;
}
```

snippet from build.zig:
```
    const exe_opt = b.addExecutable(.{
        .name = "wordcount_opt",
        .root_source_file = b.path("wordcount_opt.zig"),
        .target = target,
        .optimize = optimize,
        .single_threaded = true,
    });
```

build command:
`zig build -Doptimize=ReleaseFast`

input and output data are very huge. gigabytes. and the problem occurs only every once in a while, hard to repeat and come up with a slim repeatable demonstration sample.

i dont use ECC memory. Could it be a hardware bug instead?

### Expected Behavior

std.testing.expectEqual(x, y); should never fail

but calling the program containing this snippet in a loop shell script sometimes fails:

$ ./test.sh
expected 77599302808, found 77599827096
error: TestExpectedEqual
Command exited with non-zero status 1
x == y == 77599302808
x == y == 77599302808
x == y == 77599302808

**Comment by rohlem** [comment]
> Could it be a hardware bug instead?

Well, the difference `77599827096 - 77599302808` is exactly `0x8000`, which is the single 20th bit (bit 19 counting from 0) being flipped.
Are the numbers always the same when the error triggers? (Maybe printing the difference as hexadecimal or binary would make sense?)
Have you tried running some memory check utility?

**Comment by michaelortmann** [comment]
> I wouldn't rule out a bug in the standard library. Are the contents of `items` random every test, or do you repeat the test with the same data?

the contents/order of `items` should be identical if the StringHashMap/Interator is deterministic. I will all a checksum to the data feeded to the sort functtion.

But from what i saw looking at one diff of output, the resulting data after sort wasnt sorted. it should be sorted by count, then by word, but somehow in the middle of words with count 1, i saw a random count of 2049 that should not be there. Again, i cant repeat, but i still have the diff from that comparision:

```
--- out-zig.txt	2024-09-21 13:40:31.100897289 +0200
+++ out-zig-opt.txt	2024-09-21 20:12:47.177688184 +0200
@@ -40322986,6 +40322986,7 @@
 sha1="hur1hwenvmcpqu6sjmfoahlpd66kco3"	1
 sha1="hur1iybn7nz6r5nglvigmnhnmf89szl"	1
 sha1="hur2u40xo0zwz61g3akuxz634b5a1m3"	1
+translate(&quot;headoftable&quot;,1,womenrace_bool))	2049
 sha1="hur4drsb43cpj49ggasi3zlxjb8nclj"	1
 sha1="hur4jhvt01cheil43ap9q4qgcekhx7h"	1
 sha1="hur52ejutgwmycx9j3vw2dv0exnq21y"	1
@@ -41631024,7 +41631025,6 @@
 translatae''.	1
 translatam	1
 translate&lt;/small&gt;==	1
-translate(&quot;headoftable&quot;,1,womenrace_bool))	1
 translate(&quot;headoftableII&quot;,9,womenrace_bool),	1
 translate(&quot;headoftableIII&quot;,teamCats[CatID][1],	1
 translate(&quot;headoftableIII&quot;,teamCats[CatID][2],	1
@@ -43067720,6 +43067720,7 @@
 {{Kisbolygó-navigátor|oldalnév=1522	1
 {{Kisbolygó-navigátor|oldalnév=1523	1
 {{Kisbolygó-navigátor|oldalnév=15230	1
+{{Portálok|transparent}}	2049
 {{Kisbolygó-navigátor|oldalnév=15239	1
 {{Kisbolygó-navigátor|oldalnév=1524	1
 {{Kisbolygó-navigátor|oldalnév=1525	1
@@ -43106180,7 +43106181,6 @@
 {{Portálok|	1
 {{Portálok|#E8E7C4}}	1
 {{Portálok|#fff}}	1
-{{Portálok|transparent}}	1
 {{Portálok}}</text>	1
 {{Portál|1=Könnyűzene}}	1
 {{Portál|</comment>	1
```

> 
> > Could it be a hardware bug instead?
> 
> Well, now that you mention that option, the difference `77599827096 - 77599302808` is exactly `0x8000`, which is the single 20th bit (bit 19 counting from 0) being flipped. Are the numbers always the same when the error triggers? (Maybe printing the difference as hexadecimal or binary would make sense for finding flipped bits?) Have you tried / Can you try running some memory check utility?

no the numbers are not the same, but looking at my diff above... the diff there is `2048`, which also occurred as not random to me.

The idea of a hardware bug came to me, when i thought of those rowhammer attacks and how we could flip bits on purpose and my testprogram really feels like it hammers the system.

I will run the memcheck now. Hope it will point out the mem, and let our beloved zig std lib go free.

**Comment by michaelortmann** [comment]
memcheck indeed reported memory failure, so its a hardware bug, and zig is fine.
