### ISSUE TITLE
Failing test causes stack trace to print infinitely

### ISSUE THREAD

**Issue by hryx** [ziglang/zig#2151]
See for example:
- https://dev.azure.com/ziglang/zig/_build/results?buildId=1120
- https://dev.azure.com/ziglang/zig/_build/results?buildId=1132

Also confirmed locally on macOS and Linux. It can be easily reproduced by changing one of the strings in`std/zig/parser_test.zig` to make the test fail.

**Comment by andrewrk** [comment]
It's probably this logic:

https://github.com/ziglang/zig/blob/aa794eb621d328f8e96e3458602b926d610598ec/std/debug.zig#L216-L225

Related to this commit: 00d8f4a1bb634ec5b0569e6ff6c2679ade2bd6b0
