### ISSUE TITLE
fanotify_init failed due to old kernel; requires 5.17+

### ISSUE THREAD

**Issue by mocompute** [ziglang/zig#21543]
### Zig Version

0.14.0-dev.1671+085cc54aa

### Steps to Reproduce and Observed Behavior

I ran into this trying to diagnose a zls problem, where it is not recognizing any of my package dependencies. Watching the zls.log, I see it invokes my build executable, which generates some JSON output with deps_build_roots, packages, etc. Basically the metadata that zls needs.

However, immediately after the JSON, this error is printed, and it exits with status 1. So zls gives up and it won't navigate to types or declarations in my dependencies.

`fanotify_init failed due to old kernel; requires 5.17+`

My uname -a:

`Linux nixos 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 GNU/Linux`

### Expected Behavior

Possibly don't invoke file watcher if the linux kernel version is too old to support `fanotify_init`.

**Comment by Rexicon226** [comment]
This is an issue with ZLS, not Zig. 
Zig does not, (and probably will not?), support `std.Build.Watch` for linux kernels below `5.17`, since the file watching implementation uses `REPORT_TARGET_FID`.

**Comment by mocompute** [comment]
@Rexicon226 Unfortunately the error in zig is not recoverable:

https://github.com/ziglang/zig/blob/3b465ebec59ee942b6c490ada2f81902ec047d7f/lib/std/Build/Watch.zig#L528

Would it be possible to return an error from Watch.init() instead? Then zls could handle it gracefully: https://github.com/zigtools/zls/issues/2040#issuecomment-2381276938
