### ISSUE TITLE
syncronized circular buffer

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2155]
This is a feature proposal for a circular buffer that can be shared between processes. It will be used for streaming the utf8-validation to the tokenizer in the self-hosted. [I already have the utf8-validation lifted out of the tokenizer in a branch based on my utf8 work.](https://github.com/shawnl/zig/commit/5498a4fd5b31f4a27fda3e1af60970e25dadbe08)

It would only allow sizes which are powers of 2, up to 2**30 bytes (1 GiB) so that there is no special case when it wraps around. I still haven't figured out how to represent these wrapping load/stores in zig.

It would have two locks, which are u30 + a waiter flag in the high bit. The remaining bit is reversed for Linux's robust cross-process futexes. Using the high bit as a waiter bit is also compatible with Linux's "robust" API. The two locks are `read` and `written`. The buffer contains `u???(written) -% u???(read)` bytes, where `???` represents the size of the buffer.

I starting trying to explain the locks, but I think that can only be done through coding this up. This is what I have so far:
```
/// Circular buffer of power of 2 size, up to 2 ** 30 bytes or 1 GiB
/// Only having one writer and one reader makes this fairly simple,
/// and allows using solely AtomicOrder.SeqCst.
pub const CircBuf = struct {
    var buf: []u8,
    var size_log_2: u5,

    /// Initially read = written = 0. Reader spawns writer, then waits on
    /// 'writen'.
    /// The meanings below allow the buffer to completely fill.
    /// To signal EOF the writer marks "written" as having waiters.
    var read: i32, // This byte has not been read, but ones before it have
    var writen: i32, // This byte has been written, but not any after

    pub fn updateAsWriter(self: *CircBuf, comptime T: type, writen: T) T {
        assert(@typeInfo(T).Type == builtin.TypeId.Int);
        assert(@typeInfo(T).Int.bits == self.size_log_2);
        assert(@typeInfo(T).Int.is_signed == false);

        // Read this before unlocking
        var read = @atomicLoad(i32, &self.read, AtomicOrder.SeqCst)

        assert(@truncate(T, read) != writen); // This could only happen if writer called this function twice without making forward progress

        const old_writen = @atomicRmw(i32, &self.writen, AtomicRmwOp.Xchg, i32(writen), AtomicOrder.SeqCst);
        if (old_writen < 0) linux.futex_wake(&self.writen, linux.FUTEX_WAKE | linux.FUTEX_PRIVATE_FLAG, 1);
        if (writen + 1 == @truncate(T, read)) {
            // Buffer is full
            const new_read = @atomicRmw(i32, &self.writen, AtomicRmwOp.Or, math.minInt(i32), AtomicOrder.SeqCst);
            ....TBC
        }
    }
}
```

**Comment by andrewrk** [comment]
For this to be something that is shared between processes, doesn't it make sense for it to have some kind of specification and stable ABI which has its own versioning scheme, which is external to any specific programming language?

Are you implementing an existing standard, or inventing something new?

Btw you can do this now that we have anonymous enum literals:

```zig
        var read = @atomicLoad(i32, &self.read, .SeqCst)
```

**Comment by shawnl** [comment]
> Are you implementing an existing standard, or inventing something new?

Something new. The versioning has to happen when you negotiate the buffer and set up the shared memory. But yes, I agree that once all the falls into place, versioning is a must.
```
        var read = @atomicLoad(i32, &self.read, .SeqCst)
```
cool!

**Comment by andrewrk** [comment]
I don't think this needs to be part of the standard library. If you want to create something and add it for now, for the purposes of improving the test coverage for zig, then go for it. But I don't see this as an issue that the zig project is really responsible for making progress on.
