### ISSUE TITLE
type 'i8' cannot represent integer value '128'

### ISSUE THREAD

**Issue by KodinGoose** [ziglang/zig#21560]
### Zig Version

0.14.0-dev.1694+3b465ebec

### Steps to Reproduce and Observed Behavior

The following code works and outputs -128 as expected:
```
const std = @import("std");

pub fn main() !void {
    var b: i8 = 0;
    b -= 127;
    b -= 1;
    try std.io.getStdOut().writer().print("{d}\n", .{b});
}
```

However I am gobsmacked that the following code does not:
```
const std = @import("std");

pub fn main() !void {
    var b: i8 = 0;
    b -= 128;

    try std.io.getStdOut().writer().print("{d}\n", .{b});
}
```
The compiler returns this error message: type 'i8' cannot represent integer value '128'
I did see a couple bug reports with similar themes and error messages, but decided this looked unique enough to me. Sorry if it's a duplicate.

### Expected Behavior

Expected the value of b to be -128 and for both programs to build

**Comment by nektro** [comment]
`i8` can only fit integers from `-128` to `127`

**Comment by nektro** [comment]
interestingly, `b +%= -128` would probably work

**Comment by jedisct1** [comment]
```zig
b -= 128;
```

Yep, the literal value `128` must be the same type as `b`, and cannot be represented.

**Comment by KodinGoose** [comment]
> ```zig
> b -= 128;
> ```
> 
> Yep, the literal value `128` must be the same type as `b`, and cannot be represented.

Oh, I see now. That actually makes sense. Sorry for false bug report. Closing the issue.
