### ISSUE TITLE
`std.c.dlopen` does not allow C `NULL` pointer as path parameter

### ISSUE THREAD

**Issue by JanDeVisser** [ziglang/zig#21592]
### Zig Version

0.14.0-dev.1694+3b465ebec

### Steps to Reproduce and Observed Behavior

The libdl `dlopen` C function accepts a C `NULL` pointer as the path. This will open the current application image as a dynamic library. However, the extern declaration in `std/c.zig` does not mark the `path` parameter `?` so there is no way to actually pass a `NULL` or `null`.

### Expected Behavior

`std.c.dlopen(null, ...)` will actually work. 

I'm personally ambivalent about the `std.DynLib` layer above; if portability dictates that opening the application image isn't allowed that's fine with me and I'll just rawdog `dlopen`. Being able to use `DynLib` would be nice though.

**Comment by alexrp** [comment]
> I'm personally ambivalent about the `std.DynLib` layer above; if portability dictates that opening the application image isn't allowed that's fine with me and I'll just rawdog `dlopen`. Being able to use `DynLib` would be nice though.

Would you mind filing a separate issue for this? That's a slightly non-trivial feature request, I think, but seems useful.
