### ISSUE TITLE
allow while at the end of a block in addition to the beginning

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2159]
Has this been discussed?
```
var i: usize = 0;
{

} while (i < bytes.len) : (i += 1);
```
While this is not a good example of where it is needed, I have one right now. I think this should be allowed because:
* It is familiar from C
* the meaning of the syntax follows clearly from the existing syntax
* in the times that it is useful it avoids duplication, or using an ugly `while (true)`

**Comment by andrewrk** [comment]
It's a reasonable proposal to open. But I'm confident in leaving loops how they are. 

```zig
var i: usize = 0;
while (true) : (i += 1) {

    if (i < bytes.len) break;
}
```

I don't think `while (true)` should be considered ugly. It's a versatile and useful tool, and Zig understands that `while (anything_comptime_known_to_be_true)` means the result type of the loop is `noreturn`, which makes everything work together correctly.

The additional syntax does not provide any more semantic benefits. It makes the language bigger without providing any safety or pragmatic improvements. In general, syntax sugar is difficult to get into the language.

**Comment by hryx** [comment]
If you truly need to use a u8 for whatever reason, you can hardcode one iteration. I think it's a reasonable trade-off for a less common use case.

```zig
var i: u8 = 0;
doThing();
while (i < 256) : (i += 1) {
    doThing();
}
```

**Comment by emekoi** [comment]
perhaps we could make zig smarter about comptime as a way to remedy this. take the following code for example:
```zig
// create 8bit divide lookup table
comptime {
    @setEvalBranchQuota(257 * 257);
    var div8Table: [256][256]u8 = undefined;
    for (div8Table[1..]) |row, b| {
        for (row[0..]) |_, a| {
            div8Table[a][b] = @intCast(u8, usize(a) << 8, usize(b));

        }
    }
}
```
this code doesn't compile despite the fact that it is comptime known that `a` and `b` can never be 256.

**Comment by daurnimator** [comment]
@hryx sometimes `doThing()` is quite complex: I don't think repeating it is a good solution. It especially gets hard when the stop-condition is dynamic (e.g. if it is user-supplied `u8` to stop at)

Also, *usually* I need the iteration variable `i` as part of my code, in your example it is one off from the expected value.

**Comment by hryx** [comment]
> sometimes doThing() is quite complex

```zig
inline fn doThing() {
    // complex thing
}
doThing();
doThing();
```

> when the stop-condition is dynamic

```zig
if (i > 0) {
    doThing();
    while (i != 255) : (i += 1) {
        doThing();
    }
}
```

> usually I need the iteration variable i as part of my code

```zig
if (i > 0) {
    doThing(i);
    while (i != 255) : (i += 1) {
        doThing(i + 1);
    }
}
```

**Comment by daurnimator** [comment]
> ```zig
> inline fn doThing() {
>     // complex thing
> }
> doThing();
> doThing();
> ```

This doesn't work if you have state or returns in your body. e.g. a body of:
```zig
const x = allocator.create(foo);
errdefer allocator.destroy(x);
if (try bar(x, i)) |y| {
    if (y) return; // return early
}
```

> ```zig
> while (i + 1 < iterations)
> ```

That overflows. You'd have to write `i != iterations`

=======

Do you think that these messes are really worth the lack of `do while`?

**Comment by hryx** [comment]
> That overflows. You'd have to write i != iterations

Good catch! 😓 

> This doesn't work if you have state or returns in your body

Surely it can be updated to accommodate:

```zig
inline fn doThing(state: *SomeState, other_state: *OtherType) !?SomeResult {
     // ...
}
```

But anyway, no doubt I'm exhausting my position (🐴 🔨 💀 ) . And I see your position, this perhaps adds some overhead. In the end:

> Do you think that these messes are really worth the lack of do while?

Personally, yes, and I don't think they're messes. That's just my opinion. I consider grammatical additions heavy, especially those that offer new types of control flow.
