### ISSUE TITLE
zig targets,  error: unable to read libc/glibc/abilists: Unexpected

### ISSUE THREAD

**Issue by jimying** [ziglang/zig#21624]
### Zig Version

0.14.0-dev.1816+20e03beae

### Steps to Reproduce and Observed Behavior

run `zig targets`, get error :
```
error: unable to read libc/glibc/abilists: Unexpected
```

also, i test build simple hello.c,  `zig cc -target x86_64-linux-gnu hello.c` or 
 `zig cc -target x86_64-linux-musl hello.c`, get error:
```
hello.c:1:1: error: Unexpected
error: sub-compilation of glibc crti.o failed
    note: unable to check cache: stat file '/home/pi/bak/zig14/lib/libc/glibc/sysdeps/x86_64/crti.S' failed: Unexpected
error: sub-compilation of compiler_rt failed
    note: unable to check cache: stat file '/home/pi/bak/zig14/lib/compiler_rt.zig' failed: Unexpected
error: unable to build glibc CRT file: SubCompilationFailed
error: sub-compilation of glibc crtn.o failed
    note: unable to check cache: stat file '/home/pi/bak/zig14/lib/libc/glibc/sysdeps/x86_64/crtn.S' failed: Unexpected
error: sub-compilation of glibc Scrt1.o failed
    note: unable to check cache: stat file '/home/pi/bak/zig14/lib/libc/glibc/sysdeps/x86_64/start-2.33.S' failed: Unexpected
error: sub-compilation of glibc libc_nonshared.a failed
    note: unable to check cache: stat file '/home/pi/bak/zig14/lib/libc/glibc/stdlib/atexit.c' failed: Unexpected
error: unable to build glibc shared objects: Unexpected
```

### Expected Behavior

no error

**Comment by andrewrk** [comment]
I can't reproduce this. How did you obtain the zig binary? If you do a git pull you have to rerun make/ninja.

**Comment by andrewrk** [comment]
unplanned milestone while we wait for an answer to the question

**Comment by andrewrk** [comment]
Thank you, you have now answered the question, but I still cannot reproduce the problem.

**Comment by alexrp** [comment]
@jimying `uname -a`?

**Comment by alexrp** [comment]
That's quite an old kernel (from 2013). Zig [currently requires 4.19 (2018) or later](https://github.com/ziglang/zig/blob/10cb578e4e16bac44055f277cd06baaf99b159b6/lib/std/Target.zig#L508) for the standard library abstractions (and by extension the compiler) to work. The specific problem in this case is that your kernel lacks `statx()` which was added in 4.11 (2017).

**Comment by alexrp** [comment]
The switch to `statx()` happened after 0.13.0 in #20389.
