### ISSUE TITLE
Compiler hang when using --listen=- argument

### ISSUE THREAD

**Issue by murymi** [ziglang/zig#21620]
### Zig Version

0.14.0-dev.1504+5f3d9e0b7

### Steps to Reproduce and Observed Behavior

detected this command causing build to hang when building with this code
```zig
pub const Process = struct {
    a: u32,

    pub fn init() Process {
        const proc: Process = .{.a = 0};
        var a: u8 = 0;
        mapKernel(&a);
        return proc;
    }

    fn mapKernel(self: *u8) void {
        _ = self;
    }
};

pub fn main() !void {
    _ = Process.init();
}

```

```bash
zig run bug.zig --listen=-
```

### Expected Behavior

Not hang

**Comment by alexrp** [comment]
That's a flag used by the compiler. Use `--` to stop the compiler from interpreting arguments so they get passed to the program.

**Comment by murymi** [comment]
Thanks

**Comment by murymi** [comment]
> That's a flag used by the compiler. Use `--` to stop the compiler from interpreting arguments so they get passed to the program.

Thanks
