### ISSUE TITLE
root struct of file 'cimport' has no member named 'LoadImageFromMemeory'

### ISSUE THREAD

**Issue by gamezoid123** [ziglang/zig#21634]
### Zig Version

0.14.0-dev.1773+516cb5a5e and 0.13.0

### Steps to Reproduce and Observed Behavior

Follow the Ziglang.org snippet to add raylib, modify it with the following
```
    var datasize: c_int = 0;
    const filedata: [*]u8 = ray.LoadFileData("./test.png", &datasize);
    const img = ray.LoadImageFromMemeory(".png", filedata, datasize);
    const tex = ray.LoadTextureFromImage(img);
```
build with `zig build-exe src/main.zig -lc -lraylib`

Zig build fails with the following output

```
src/main.zig:15:20: error: root struct of file 'cimport' has no member named 'LoadImageFromMemeory'
    const img = ray.LoadImageFromMemeory(".png", filedata, datasize);
                ~~~^~~~~~~~~~~~~~~~~~~~~
/home/jacobc/Practice/Zig/test/.zig-cache/o/3c989ea31d301bc105ea81e74bfa8349/cimport.zig:1:1: note: struct declared here
pub const __builtin_bswap16 = @import("std").zig.c_builtins.__builtin_bswap16;
^~~
```

Workaround:

redefine `LoadImageFromMemeory` to `LdImgFrmMem` in raylib source

build raylib with this source. I used the following

```
#!/bin/sh
cc="clang"
build_opts="-std=c99 -nostartfiles -shared -g -O0"
linkflags="-fsanitize=address,undefined -fPIC -flto -lm -ldl -lpthread"
def="-D_GLFW_X11 -D_DEFAULT_SOURCE -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33"
src="src/raylib/*.c"
cmd="$cc $def $linkflags $build_opts $src -o liblibs.so "
echo $cmd
$cmd
```

use the changed name in your zig source, and rebuild in zig with `zig build-exe -L./ -I./src/raylib src/main.zig -lc -lrl` 

### Expected Behavior

Zig can import c function from source

**Comment by Rexicon226** [comment]
Did you mean to use `LoadImageFromMemory`?

**Comment by gamezoid123** [comment]
Yes, I could have sworn I had pulled the name from the header when I first got this issue. My bad.
