### ISSUE TITLE
error set code in stage1 compiler fragile

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2164]
My re-work of `unicode.zig` which uses error unions extensively ran into bugs regarding error unions.

stuff like:

```
zig: ../src/ir.cpp:20992: IrInstruction* ir_analyze_instruction_check_switch_prongs(IrAnalyze*, IrInstructionCheckSwitchProngs*): Assertion `start_value->value.type->id == ZigTypeIdErrorSet' failed.
```
and a TODO in comparing to see if equal.

**Comment by andrewrk** [comment]
you're not wrong, but this is also not an actionable issue.
