### ISSUE TITLE
Spelling error: psuedo

### ISSUE THREAD

**Issue by highvoltage** [ziglang/zig#21641]
### Zig Version

0.13.0 (local build)

### Steps to Reproduce and Observed Behavior

Very minor bug:

Seems like pseudo is mis-spelled as psuedo here:

src/arch/riscv64/Lower.zig:            else => return lower.fail("TODO lower: psuedo {s}", .{@tagName(inst.ops)}),
src/arch/aarch64/Mir.zig:        /// Psuedo-instruction: Push multiple registers                                  

### Expected Behavior

It should be spelt "pseudo".

**Comment by sfiedler0** [comment]
Somehow I can't find the first error (in src/arch/riscv64/Lower.zig), tried it with a `cat $(find src -name "*.zig") | grep psuedo` (uppercase too), but a pull request for second one will come in some seconds.

**Comment by andrewrk** [comment]
#21660

**Comment by andrewrk** [comment]
'It should be spelt "pseudo".' is not a behavior.
