### ISSUE TITLE
Is this way of casting a *c_void the best solution?

### ISSUE THREAD

**Issue by kterhorst** [ziglang/zig#2167]
Question:

In C
```
struct Api {
	void* (*get)(const char* api_name);
};
```

and in Zig

```
// TODO implement get_c_type for more types when directly using *c.Api
export fn zig_function(p: *c_void) void {
    const x = @ptrToInt(p);
    const y = @intToPtr(*c.Api, x);
    if (y.get) |get| {
        _ = get(c"some_api");
    }
}
```

Is this ugly ptrToInt -> intToPtr -> *c.Api the only way to accomplish this cast? Using @ptrCast directly results in a pointer alignment error.

**Comment by andrewrk** [comment]
Here's a slightly modified version using `@alignCast`. I also used the `.?` syntax which makes sense only if you want to assert that `y.get != null`.

```zig
export fn zig_function(p: *c_void) void {
    const y = @ptrCast(*c.Api, @alignCast(@alignOf(c.Api), p));
    _ = y.get.?(c"some_api");
}
```

**Comment by kterhorst** [comment]
Thanks :) Keep on working on that _great_ language!
