### ISSUE TITLE
Smaller floats don't coerce correctly to f128

### ISSUE THREAD

**Issue by Ratakor** [ziglang/zig#21683]
### Zig Version

0.14.0-dev.1860+2e2927735

### Steps to Reproduce and Observed Behavior

Example:
```zig
const std = @import("std");

pub fn main() !void {
    @setFloatMode(.strict);
    const float_number = try std.fmt.parseFloat(f128, "45.67");
    const smaller_float: f64 = @floatCast(float_number);
    const big_again: f128 = smaller_float;
    std.debug.print(
        \\float_number: {d}
        \\smaller_float: {d}
        \\bigger_again: {d}
        \\float_number == bigger_again: {}
        \\
    , .{ float_number, smaller_float, big_again, float_number == big_again });

}
```

Output:
```
float_number: 45.67
smaller_float: 45.67
bigger_again: 45.670000000000001705302565824240446
float_number == bigger_again: false
```

It's an issue here: https://github.com/ziglang/zig/blob/7e530c13b3ef9b61417a610c00fc1d37c11ff7ed/lib/std/zig/AstGen.zig#L8694

### Expected Behavior

```
float_number: 45.67
smaller_float: 45.67
bigger_again: 45.67
float_number == bigger_again: true
```

**Comment by rohlem** [comment]
I haven't investigated this, but my impression is that the `@floatCast` in the example loses information.

While printing `smaller_float` only writes 2 places after the comma, the float formatting code accounts for the precision of the input type (in this instance `f64`).
It probably recognizes that this is the `f64` representation closest to `45.67` and omits the rest, even though the value is not exactly represented.
So even though `float_number` is the closest `f128` to `45.67` and `smaller_float` is the closest `f64` to `45.67`, they are not equal.

If my thinking here is correct, then I believe the behavior of `==` here works as intended:
The original `f128` and the one extended from the less-precise `f64` don't hold exactly the same value, therefore they're unequal.
Analogously, I'm not sure that the [linked `if`](https://github.com/ziglang/zig/blob/7e530c13b3ef9b61417a610c00fc1d37c11ff7ed/lib/std/zig/AstGen.zig#L8694) exhibits incorrect behavior either: The value lost precision when downcast to `f64`, so it makes sense to store the original `f128` value instead.

**Comment by 87flowers** [comment]
@rohlem is correct.
If you print out the floating point values in hex, you can see that conversion to a f64 causes rounding to occur to fit the value in the smaller format, and thus results in a different value which is to be expected.
```
float_number: 40046d5c28f5c28f5c28f5c28f5c28f6
smaller_float: 4046d5c28f5c28f6
bigger_again: 40046d5c28f5c28f6000000000000000
```

Not a bug.
