### ISSUE TITLE
ability to initialize an optional from a boolean "non-null" value

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2169]
There appears to be now way to set the optional bit of a non-pointer optional, without using a branch to set it `null`.

**Comment by andrewrk** [comment]
```zig
var x: ?i32 = null;
var y: ?i32 = i32(undefined);
```

**Comment by shawnl** [comment]
I mean from a bool or a u1.

Something like this:
```
var valid: bool = true;
var size = foo(&valid);
if (!valid) return null else return size;

extern fn foo(valid: *bool) usize {
}
```
But why does it need the `if`?

**Comment by rohlem** [comment]
What comes to my mind:
Ideally it should work the same as `orelse` does for "unpacking" an optional, instead to "pack" a value into an optional (without new syntax or operator symbols).
The first similarly-structured name that I can think of would be `onlythen`:
```zig
u32? result = valid onlythen size;
```

**Comment by tgschultz** [comment]
Since an optional is a special case of union, this seems related to #1315.

**Comment by andrewrk** [comment]
Closing since the alternative is reasonable:

```zig
var result: ?u32 = if (valid) size else null;
```

Better to repeat this verbose syntax than to make the language bigger.
