### ISSUE TITLE
Proposal: add `@FieldType`

### ISSUE THREAD

**Issue by mlugg** [ziglang/zig#21702]
## Background

A quite common thing to need when doing certain kinds of metaprogramming is to know the type of a given aggregate field from its name. As an example, my [recent PR](https://github.com/ziglang/zig/pull/21697) needs to do this in an `inline else =>` prong in a few places:

https://github.com/ziglang/zig/blob/496316669ef75412ff20ba31a164a88ac546e3b9/src/Value.zig#L4555-L4561

For this purpose, we currently have `std.meta.FieldType`, with usage e.g. `std.meta.FieldType(struct { x: u32 }, .x) == u32` (originally [implemented by yours truly](https://github.com/ziglang/zig/pull/14027) in my first contribution!). However, one big problem with this function is that it uses a *lot* of eval branch quota due to its implementation. We could change its implementation to something simpler (more on this in a moment), although then it wouldn't align with the other functions in `std.meta`. More on this in a bit.

This function is one of two in `std.meta` which I regularly use, with the other being `activeTag`. @andrewrk has recently mentioned that he thinks removing `@unionTag` was a mistake, because while it *can* be implemented in userland with a coercion, it's a common enough operation that you shouldn't *need* to implement it in userspace. I think the same logic can be applied to `std.meta.FieldType`; it's a pretty common thing to want to do, so while it *can* be implemented in userspace, it makes sense for it to be a builtin.

In terms of userspace implementations of `FieldType`, there are simple ways to do it. `std.meta.FieldType` is currently quite overcomplicated, since it goes through `std.meta.fieldInfo`, which is doing a full iteration over `std.meta.fields`, and also the field name is given as an enum rather than a string, which requires evaluating `std.meta.FieldEnum`, which itself iterates all fields... there's a lot of unnecessary machinery. A much simpler implementation, which uses up no eval branch quota at all (except for the 1 for the inline/comptime call), is the following:

```zig
pub fn FieldType(comptime T: type, comptime field_name: []const u8) type {
    return @TypeOf(@field(@as(T, undefined), field_name));
}
```

This implementation works well, but it's quite messy! In fact, it's much *messier* than the implementation of `std.meta.activeTag`, which we are nonetheless considering replacing with a builtin. Therefore, I think it is justified to consider adding a builtin to implement `FieldType`.

**Note that if we don't accept this proposal, I'd definitely like to see the `std.meta.FieldType` implementation changed to something like the above. I had to set a truly ludicrous quota of `400_000` in my current PR due to a bunch of calls to `FieldType`, despite them being very cheap to compile in practice.**

## Proposal

Introduce `@FieldType(comptime T: type, comptime field_name: []const u8) type`.

A call `@FieldType(T, field_name)` is semantically identical to `@TypeOf(@field(@as(T, undefined), field_name))`, although the compiler will, of course, have a more efficient implementation.

## Closing Thoughts

death to std.meta

**Comment by Lzard** [comment]
Since fields and declarations cannot have duplicate names, an alternative that would avoid adding another builtin function is to allow `@field(x, name)` to refer to a field, whether `x` is a container type or container value. Accessing the value of `@field(Type, a_field_name)` would be a compiler error (unless it is a comptime field, maybe?).

**Comment by nektro** [comment]
super happy to see this, curious though if making `FieldEnum` a builtin instead would solve both situations?

**Comment by vadim-za** [comment]
It would be also quite helpful to see the version for pointers, _which propagates the constness_. The following implementation
```zig
pub fn FieldPtrType(comptime Ptr: type, comptime field: []const u8) type {
    return @TypeOf(&@field(@as(Ptr, undefined), field));
}
```
currently fails with
```error: use of undefined value here causes undefined behavior
    return @TypeOf(&@field(@as(Ptr, undefined), field));
```

**Comment by rohlem** [comment]
> I had to set a truly ludicrous quota of `400_000` in my current PR due to a bunch of calls to `FieldType`, despite them being very cheap to compile in practice.

Regarding fiddling with the eval quota, see also https://github.com/ziglang/zig/issues/16983 .
The efficiency of `comptime` code and making the eval quota more durable / less arbitrary are imo two separate issues that are both worth pursuing independently.

Bikeshedding: In my codebase I call the function `FieldTypeOf` to have it look closer to `@TypeOf` than `@Type`.

**Comment by mlugg** [comment]
I've just realised that the userspace solution I proposed doesn't quite work for auto-layout (tagged or not) unions, since accessing a field of an `undefined` auto-layout union will emit a compile error. It'd have to be this instead:
```zig
fn FieldType(comptime T: type, comptime field_name: []const u8) type {
    return switch (@typeInfo(T)) {
        .@"struct" => @TypeOf(@field(@as(T, undefined), field_name)),
        @"union" => @TypeOf(@field(
            @unionInit(T, field_name, undefined),
            field_name,
        )),
        else => unreachable,
    };
}
```
That's pretty bad, and I think a good argument in favour of this proposal.
