### ISSUE TITLE
langref: support both light & dark color schemes, adhering to user's preference

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2172]
This lets users set their light/dark color preference in their browser globally:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

Then pages can have light/dark themes with no UI needed to be exposed for users to choose, and everybody gets their way. No JavaScript needed.

**Comment by emekoi** [comment]
according to [this](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme#Browser_compatibility) this feature is barely supported in any of the major browsers.

**Comment by andrewrk** [comment]
I'm sure the others will catch up. Browsers that don't support it will get a default light theme.
