### ISSUE TITLE
Change Unions/Tagged Union initialization

### ISSUE THREAD

**Issue by CrazieNewb** [ziglang/zig#21737]
Current way
```zig
const foo = Type { .Int = .{
  .signedness = .signed,
  .bits = 32,
} };

const boo: Type = .{
  .Int = .{
    .signedness = .signed,
    .bits = 32,
  }
};
```
Proposed way
```zig
const foo = Type.Int {       //$1
  .signedness = .signed,
  .bits = 32,
};

const boo: Type = .Int {
  .signedness = .signed,
  .bits = 32,
};
```

Pros:
- Easier to read
- Fits capitalization of enum's (treats them as a type)
- Fits enum initialization syntax
- Treats void type union fields as an enum

Cons:
- New special syntax
- Union field may be confused with a type ($1)

Extra:
`const bar = Type.Int { ... }` syntax might be confusing
```zig
const foo: Foo = .{
  .x = 5,      // Could be optional, or not
  .y = .A {5}  // Is clearly a union + tuple
  .z = .X      // is an enum or void union
};

const bar = Type.Int {   // Could be a union or type
  .signedness = .signed,
  .bits = 32,
};
```

**Comment by tauoverpi** [comment]
See https://github.com/ziglang/zig/issues/10710 which solves this without changes to initialization for `@Type` where it's currently a major pain point.

**Comment by mlugg** [comment]
[Please do not file a proposal to change the language.](https://github.com/ziglang/zig/wiki/Language-Proposals)
