### ISSUE TITLE
Running without a proc mount fails with `FileNotFound`

### ISSUE THREAD

**Issue by arthurmelton** [ziglang/zig#21745]
### Zig Version

0.14.0-dev.1951+857383689

### Steps to Reproduce and Observed Behavior

The easiest way is to to chroot into an environment without any `/proc` mount. Fails trying to read `/proc/self/exe`, when trying to get the exe folder for finding the lib folder.

### Expected Behavior

I don't actually know if this should continue working this way and require the `/proc` mount, and give a better error message than just `error: FileNotFound`, or if this should try to do some funkiness if the `/proc` mount does not exist. `gcc` does not require the `/proc` mount, and its pretty nice for testing building in limited environments.

**Comment by rohlem** [comment]
> its pretty nice for testing building in limited environments.

There is already a flag for specifying the lib dir path explicitly, from `zig build-exe --help`:
`--zig-lib-dir [path]      Override path to Zig installation lib directory`

I assume this should work around that error to enable that usage scenario (not sure whether that correctly works though).
In that case the compiler should probably mention the flag in a bespoke error message rather emitting the plain `error: FileNotFound`.

**Comment by arthurmelton** [comment]
So, doing some looking it looks like you can't do `zig build --help`, as that gives the unhelpful error, but `zig build-exe --help` response as usual. If I try doing `zig build-exe --zig-lib-dir /lib/zig/ src/main.zig`, we are getting closer as it says a good error now `error: unable to find zig self exe path: FileNotFound`. I am confused if there is maybe another reason for it needing to know its own exe path, after being provided the lib dir. Providing the cache dir, gives the same error as if it was not provided.

**Comment by andrewrk** [comment]
Bug report is missing Steps To Reproduce. If provided I will re-open

**Comment by arthurmelton** [comment]
So for the Steps To Reproduce, I will show a more realistic example using an alpine linux mini rootfs. The main idea is to follow this idea.

- Make some `mnt` folder where a fake rootfs will be put into.
- Download the [alpine linux mini rootfs](https://alpinelinux.org/downloads/) and extract it into the `mnt` folder.
- Download and install Zig inside the `mnt` folder.
- Chroot into the `mnt` folder and attempt to use zig.

This is how we can setup what I described, except chrooting into the environment (shown for `x86_64`).
```sh
mkdir mnt
cd mnt
wget https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/x86_64/alpine-minirootfs-3.20.3-x86_64.tar.gz
tar -xzf alpine-minirootfs-3.20.3-x86_64.tar.gz
rm alpine-minirootfs-3.20.3-x86_64.tar.gz
wget https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.2097+d30e28754.tar.xz
tar -xf zig-linux-x86_64-0.14.0-dev.2097+d30e28754.tar.xz
rm zig-linux-x86_64-0.14.0-dev.2097+d30e28754.tar.xz
mv zig-linux-x86_64-0.14.0-dev.2097+d30e28754/lib usr/lib/zig
mv zig-linux-x86_64-0.14.0-dev.2097+d30e28754/zig usr/bin/
rm -r zig-linux-x86_64-0.14.0-dev.2097+d30e28754/
cd ..
```

After you have setup everything you can chroot into the environment
```sh
sudo chroot mnt/ /bin/sh
```

Once you are in you can attempt to init a project and it will fail
```sh
mkdir -p /root/project
cd /root/project
zig init # Fails
```

You can get out of the environment by just typing `exit`. To make zig work you have to do (don't forget to `umount mnt/proc`, after you exit the chroot, because if you try to `rm -rf mnt`, this will cause some problems on your system.)
```sh
sudo mount --types proc /proc mnt/proc
```

Now if we chroot into the environment again, the `zig init` command will not fail anymore.

**Comment by arthurmelton** [comment]
@andrewrk Could this get reopened with the new steps to reproduce, or do I need to edit the original message and put them there?
