### ISSUE TITLE
@cDefine not works correct

### ISSUE THREAD

**Issue by GrapeBaBa** [ziglang/zig#21759]
### Zig Version

0.14.0-dev.1694+3b465ebec

### Steps to Reproduce and Observed Behavior

Follow the step [here](https://github.com/herumi/bls/issues/112#issuecomment-2425662719)

### Expected Behavior

```zig
const bls = @cImport({
    @cDefine("BLS_ETH", "1");
    @cInclude("bls/bls384_256.h");
});
```
This code should set `BLS_ETH `is properly defined before including bls384_256.h

**Comment by trgwii** [comment]
test.zig:
```zig
const c = @cImport({
    @cDefine("BLS_ETH", "42");
    @cInclude("test.h");
});
const std = @import("std");

pub fn main() void {
    std.debug.print("{}\n", .{c.x});
}
```

test.h:
```c
int x = BLS_ETH;
```

Command:
```sh
zig run -lc -I. test.zig
```

Works on my machine
