### ISSUE TITLE
StringHashMap: error: access of union field 'pointer' while field 'struct' is active

### ISSUE THREAD

**Issue by richRemer** [ziglang/zig#21780]
### Zig Version

0.14.0-dev.1954+2d888a8e6

### Steps to Reproduce and Observed Output

A very simple attempt to use StringHashMap fails with un-helpful error:

```zig
const std = @import("std");
const StringHashMap = std.StringHashMap;

test "StringHashMap error" {
    var map = StringHashMap(u8).init(std.testing.allocator);
    defer std.testing.allocator.free(map);
    _ = &map;
}
```

This produces the following error:
```
/opt/zig/lib/std/mem/Allocator.zig:307:45: error: access of union field 'pointer' while field 'struct' is active
    const Slice = @typeInfo(@TypeOf(memory)).pointer;
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/opt/zig/lib/std/builtin.zig:268:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
```

If this is user error, I'm not sure what that error might be.  On the other hand, I can't imagine the standard library would work without StringHashMap, so at this time I'm assuming it is user error and not a compiler bug.

### Expected Output

If this is user error, the messaging should provide some indication of the cause.  As it stands, the only reason I think this might not be a bug is the standard library relies on this, so I can't imagine how anything would work.

**Comment by Rexicon226** [comment]
The `allocator.free` interface is intended for freeing slices of data. A `StringHashMap` is a struct, not a slice, as a error message points out.

You need to use `map.deinit()` in order to de-allocate the map properly.

**Comment by richRemer** [comment]
Oh, duh. 😮‍💨 I'm dumb.

**Comment by richRemer** [comment]
It might be nice if the error appeared with the .deinit call, but I'm not needy.

**Comment by Rexicon226** [comment]
> It might be nice if the error appeared with the .deinit call, but I'm not needy.

Zig error messages are strictly un-opinionated about what you're doing. The only way to reasonably implement such an error message would be to check if the input has a field called "deinit", which could potentially be unrelated. Hence, it's better to just not have it. Better be confused about this error once, and then understand how the interface works, than be mislead later on.
