### ISSUE TITLE
std.os.linux.fgetxattr tries to call lgetxattr(2) instead

### ISSUE THREAD

**Issue by tikatoo** [ziglang/zig#21785]
### Zig Version

0.14.0-dev.1983+6bf52b050

### Steps to Reproduce and Observed Behavior

Can pretty easily see from the code here: https://github.com/ziglang/zig/blob/c563ba6b15b65ecdc1cb538c9437e11dfb330453/lib/std/os/linux.zig#L2038

For completeness, `zig test` on the following file is failing with `EFAULT` (since `lgetattr(2)` expects the first argument to be a pointer, not a file descriptor):

```zig
const std = @import("std");

test "fgetxattr" {
    var buffer = [_]u8{0} ** 48;
    const value = ";as;enc;A ;SJGL";

    var tmp_dir = std.testing.tmpDir(.{});
    defer tmp_dir.cleanup();
    const dir = tmp_dir.dir;

    const fp = try dir.createFile("test_file", .{});
    defer fp.close();

    var rc = std.os.linux.fsetxattr(@intCast(fp.handle), "user.test_attr", @ptrCast(value.ptr), value.len, 0);
    switch (std.posix.errno(rc)) {
        .SUCCESS => {},
        else => |err| return std.posix.unexpectedErrno(err),
    }

    rc = std.os.linux.fgetxattr(@intCast(fp.handle), "user.test_attr", &buffer, 48);
    switch (std.posix.errno(rc)) {
        .SUCCESS => try std.testing.expectEqualStrings(value, buffer[0..rc]),
        .FAULT => return error.Oops,
        else => |err| return std.posix.unexpectedErrno(err),
    }
}
```

### Expected Behavior

Above test case ought to pass.

**Comment by tikatoo** [comment]
I assume that I'm the first ever person to call this function in Zig, since I've traced this bug back to the origin of this function in 2ec1cec92d018d25f720c43a7586a12eafd2cbeb. It has survived multiple refactors without detection.

(Note: I mean no shade or disrespect. I find this hilarious, but I'm laughing at the hypothetical me who would have made this exact mistake if I was doing something like that.)

**Comment by alexrp** [comment]
Seems like a typo. 🤔 Looks like it should be a trivial fix; would you like to try doing a PR? Otherwise I'll get to it later today.

**Comment by tikatoo** [comment]
I could do a PR. I also can't do it immediately, so if there's nothing pushed once I'm done with work, I'll put something together. Would this also be a good opportunity to fix up some of the types of these functions? (The `fd` arguments of the xattr functions are `usize` whereas e.g. `accept` uses `i32`, and `*setxattr` strangely uses a different pointer type for values.)

**Comment by alexrp** [comment]
Yeah, fixing that sounds reasonable.

**Comment by tikatoo** [comment]
Patch is basically ready. Just waiting on my poor laptop to finish compiling before I submit.
