### ISSUE TITLE
incorrect calling convention for exported variadic functions

### ISSUE THREAD

**Issue by snoire** [ziglang/zig#21794]
### Zig Version

0.14.0-dev.2034+56996a280

### Steps to Reproduce and Observed Behavior

```sh
$ cat callconv.zig
const std = @import("std");

export fn print(msg: [*:0]const u8, ...) void {
    std.debug.print("{s}\n", .{msg});
}

$ zig build-lib callconv.zig -target aarch64-linux
callconv.zig:1:1: error: calling convention 'x86_64_sysv' only available on architectures 'x86_64'
const std = @import("std");
^~~~~
referenced by:
    root: /root/lang/zig/ziglang/lib/std/start.zig:3:22
    comptime: /root/lang/zig/ziglang/lib/std/start.zig:28:9
    2 reference(s) hidden; use '-freference-trace=4' to see all references
```

The compiler fails to infer the correct calling convention for exported functions that accept variable arguments.

But if we manually specify the calling convention by adding `callconv(.c)` to the function declaration, the function compiles without any issues. For instance:
```zig
export fn print(msg: [*:0]const u8, ...) callconv(.c) void {
    std.debug.print("{s}\n", .{msg});
}
```

Also, the error message is vague and does not specify which line of the code is problematic.

### Expected Behavior

The compiler should correctly infer the calling convention without the need for manual intervention.

**Comment by Rexicon226** [comment]
This is an interesting problem. `std.builtin` is being analyzed under the host, which is causing it to select `x86_64_sysv`. 
@mlugg, maybe you could chime in here, what's the correct path forward? Should `std.builtin` be analyzed under the target `builtin`?

**Comment by Rexicon226** [comment]
OK, now I do understand what's happening.
https://github.com/ziglang/zig/blob/56996a2809421a7dfbb74f7533d40faf6c1482e3/src/Sema.zig#L26795-L26797
This is being resolved under whatever `Sema.zig` was compiled, not the target.
