### ISSUE TITLE
Warning `FileNotFound` when trying to link system libraries

### ISSUE THREAD

**Issue by arrufat** [ziglang/zig#21797]
### Zig Version

0.14.0-dev.2032+c563ba6b1

### Steps to Reproduce and Observed Behavior

Initialize a Zig project with `zig init`

Add these two lines to `build.zig` after the `const exe = b.addExecutable(...);`:
```zig
exe.linkLibC();
exe.linkSystemLibrary("glib-2.0");
```
Run `zig build`

This is the output:
```console
$ zig build
install
└─ install linkwarning
   └─ zig build-exe linkwarning Debug native failure
error: warning: unable to open library directory '/usr/local/lib64': FileNotFound
warning: unable to open library directory '/usr/lib/x86_64-linux-gnu': FileNotFound
warning: unable to open library directory '/lib/x86_64-linux-gnu': FileNotFound
```

However, the binaries are properly linked with the system libraries. I first noticed this issue  in this project, where I link with `libjxl`: https://github.com/arrufat/zjxl

The previous dev versions worked without warnings.

### Expected Behavior

No warnings if everything worked fine (which I think it has, but I might be missing something).

**Comment by arrufat** [comment]
Someone made me notice this doesn't happen if I use `exe.linkSystemLibrary("m");`, instead

**Comment by imclaren01** [comment]
Seeing this too

**Comment by arrufat** [comment]
Thank you! :)
