### ISSUE TITLE
backward enumeration and iteration

### ISSUE THREAD

**Issue by 0b-s3rv3r** [ziglang/zig#21814]
It wouldn't be more prettier to add something like backward iteration or at least backward enumeration. Why when I want to iterate backward I have to do extra code which affect on readability.

We could have something like this for iteration:
```zig
var arr: [4]u32 = .{ 0, 4, 5, 1 };
for (..arr) |a| {
    std.debug.print("{}", .{a});
}
```

```
output: 1540
```

or at least something like this for enumeration:
```zig
var arr: [4]u32 = .{ 0, 4, 5, 1 };
for (3..0) |i| { // with enumeration logic of current zig theoretically it should be 3..-1, but ...
    std.debug.print("{}", .{arr[i]});
}
```

I don't think it would affect on simplicity of zig.

**Comment by mlugg** [comment]
[Please do not file a proposal to change the language.](https://github.com/ziglang/zig/wiki/Language-Proposals)
