### ISSUE TITLE
Zig fmt is sensitive to trailing comma in a struct's last field

### ISSUE THREAD

**Issue by yonipeleg33** [ziglang/zig#21816]
### Zig Version

0.14.0-dev.1550+4fba7336a

### Steps to Reproduce and Observed Behavior

When there's no trailing comma after the last field, `zig fmt` will push everything into the same line:
- before:
  ```zig
  const Foo1 = struct {
      a: u8,
      b: u8
  };
  ```
- after:
   ```zig
   const Foo1 = struct { a: u8, b: u8 };
   ```

And when there is a trailing comma, `zig fmt` will format it as expected.
This code will not be changed when running `zig fmt`:
```zig
const Foo2 = struct {
    a: u8,
    b: u8,
};
```

This trailing comma behaviour also holds true in struct/array initialization, so for example:
```zig
const Foo = struct { a: u8, b: u8 };

const foos = [_]Foo{ Foo{
        .a = 1,
        .b = 1
    }, Foo{
        .a = 2,
        .b = 2
    }, Foo{
        .a = 3,
        .b = 3
    } };
``` 
Will be formatted to:
```zig
const foos = [_]Foo{ Foo{ .a = 1, .b = 1 }, Foo{ .a = 2, .b = 2 }, Foo{ .a = 3, .b = 3 } };
```

### Expected Behavior

1. `zig fmt` should produce the same formatting regardless of the trailing comma, and preferably it should default to the multi-line (vertical) formatting.
2. I suggest adding a trailing comma if not present, like other formatters do.

**Comment by mlugg** [comment]
This is by design. Trailing commas are used to communicate the intended layout to `zig fmt`.

**Comment by yonipeleg33** [comment]
@mlugg Thanks for the quick response!
I understand your decision, and I do not wish to reopen this issue, but may I offer my feedback as a developer who's new to Zig:
This behaviour was strange and confusing to me, and I spent too much time fighting with the formatter to get my code formatted properly until I pinpointed the trailing comma behaviour.
I'm very used to other languages' experience (like rust or typescript) of not paying attention to trailing commas and letting the formatter add them for me.
 
Regardless, Zig is an amazing project, and I'm enjoying my time learning the language and tooling. Thank you and your team for the hard work!

**Comment by xdBronch** [comment]
if you use zig more i think youll eventually find this behavior extremely pleasant (and yeah thats probably what everyone says about the thing they like :p but really). it makes it much easier to understand how your code will be formatted and youll spend less (probably 0) time mucking around to get something nice out of the formatter. zig fmt has no arbitrary rules, itll never cut you off because a line is too long or split up a list with too many items, you use the code itself to control the it. at worst this is underdocumented

**Comment by jrfondren** [comment]
I complained about something similar a while ago, in #3057, and got a similar response, and I've come to agree with the response.
Nowadays zig fmt's will even emit this formatting:
```zig
const mat: [16]u32 = .{
    1, 2, 3, 4,
    5, 6, 7, 8,
    9, 0, 1, 2,
    3, 4, 5, 6,
};
```
which is sensitive to the length of the first row. Put the first 4 on a new line by itself and zig fmt'll give you:
```zig
const mat: [16]u32 = .{
    1, 2, 3,
    4, 5, 6,
    7, 8, 9,
    0, 1, 2,
    3, 4, 5,
    6,
};
```
It's very nice but of course has to be learned. Maybe you can make an issue over in https://github.com/pedropark99/zig-book to help fix the documentation problem.

**Comment by yonipeleg33** [comment]
I can see how this makes a nice feature, thanks @xdBronch and @jrfondren!

> Maybe you can make an issue over in https://github.com/pedropark99/zig-book to help fix the documentation problem.

I haven't read the book myself yet, so I don't feel I'm in the best position to open an issue there.
Hoping confused folks like me will stumble upon this issue :smile:
