### ISSUE TITLE
HKDF based on SHA3-512 fails to build

### ISSUE THREAD

**Issue by bfreis** [ziglang/zig#21824]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

When trying to create an HKDF based on SHA3-512, code fails to build due to an assertion `assert(out.len <= prk_length * 255); // output size is too large for the Hkdf construction` that ends up overflowing an `u11` from `std.crypto.hash.sha3.Keccak`.

To reproduce, any code calling `expand` on such an HKDF instance will fail to build:

```
$ cat <<EOF > hkdf-issue.zig
const std = @import("std");
test "hkdf" {
    const sha3_512 = std.crypto.hash.sha3.Sha3_512;
    const hmac_sha3_512 = std.crypto.auth.hmac.Hmac(sha3_512);
    const hkdf = std.crypto.kdf.hkdf.Hkdf(hmac_sha3_512);
    const prk = hkdf.extract("", "");
    var out = [1]u8{0};
    hkdf.expand(out[0..], "", prk);
}
EOF

$ zig test hkdf-issue.zig
zig/zig-linux-aarch64-0.13.0/lib/std/crypto/hkdf.zig:42:42: error: overflow of integer type 'u11' with value '16320'
            assert(out.len <= prk_length * 255); // output size is too large for the Hkdf construction
                              ~~~~~~~~~~~^~~~~
referenced by:
    test.hkdf: hkdf-issue.zig:8:9
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

Changing the failed assertion to `assert(out.len <= @as(usize, prk_length) * 255);` seems to fix the issue.

### Expected Behavior

Expected behavior: I should be able to construct an HKDF with SHA3-512 and not encounter a build issue.

**Comment by jedisct1** [comment]
Sure, this is a generic construction, so it should work.

That being said, while it is totally safe, using HKDF is a little bit weird and not efficient with SHA-3, when there is KMAC (implemented in zig as `sha3.Kmac128` and `sha.Kmac256`).

**Comment by jedisct1** [comment]
Bubbling the error up, `Hmac.mac_length` should be `comptime_int` or `usize`, so `Hash.digest_length` should be  `comptime_int` or `usize`.

So the actual issue is in the definition of `sha3.digest_length`: `pub const digest_length = output_bits / 8;`

**Comment by bfreis** [comment]
@jedisct1 — agreed. I was trying to port some Rust code I was playing with to Zig, when I stumbled upon this issue. Thanks for taking a look at it! Also, updated the PR to hopefully now fix the actual underlying issue (i.e. digest_length of sha3.Keccak).
