### ISSUE TITLE
Wrong `callconv` windows thread function

### ISSUE THREAD

**Issue by Trevor-Strong** [ziglang/zig#21869]
### Zig Version

0.14.0-dev.1939+816dfca0b

### Steps to Reproduce and Observed Behavior

The calling convention of the `entryFn` used to spawn threads on windows is `.C` when it is documented as using the `WINAPI` calling convention. [MSDN Page](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms686736(v=vs.85))

This may not have been caught before as the only time where the `WINAPI` calling convention is not `.C`
is on x86, and the CC mismatch on that platform doesn't cause too many immediate issues.

The windows API might also have implemented a hack to fix the stack when given function using the C calling convention instead of stdcall. It seems they have even done this [before](https://devblogs.microsoft.com/oldnewthing/20040115-00/?p=41043).

### Expected Behavior

I would expect the correct calling convention to be used.

**Comment by alexrp** [comment]
I'll take a look at this in #21843.

**Comment by Trevor-Strong** [comment]
Also just noticed that definition for `PTHREAD_START_ROUTINE`/`LPTHREAD_START_ROUNTINE` also incorrectly uses the `C` calling convention, and so requires the same fix.
