### ISSUE TITLE
Constants for `flags` arguments of linux/POSIX system calls are missing from standard library.

### ISSUE THREAD

**Issue by kj4tmp** [ziglang/zig#21889]
Use case:

I need to use the MSG_TRUNC flag on `recv()` in linux.

I can currently write it like this:
```zig
const MSG_TRUNC = 0x20;
try std.posix.recv(socket, out, MSG_TRUNC);
```

But this requires me to google what MSG_TRUNC is after looking at the man page for `recv()`.

It would be nice to have some representation of these flags in the standard library.

**Comment by alexrp** [comment]
`std.os.linux.MSG`, `std.c.MSG`, `std.posix.MSG`?

**Comment by kj4tmp** [comment]
my bad, my grep skills need some work :)
