### ISSUE TITLE
expose the root source file with @import("root")

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2189]
We already rely on this behavior in bootstrap.zig but it is special magic:
https://github.com/ziglang/zig/blob/6cc2d3938e81f1c5db9cf94db90fda11b026422a/std/special/bootstrap.zig#L4

This proposal would make it always available and so the above code would not be special magic anymore.

It's reasonable for userland libraries to have global configuration and use the root source file for that. For example this would be a necessary component of #1778.

This, along with #1439 would allow us to move some of the global panic function magic to userland, and potentially even the startup code. `build-exe` would unconditionally include the startup code, which would have a `comptime` block which examines the root source file for `main`, `_start`, etc, and determines what it should export.

**Comment by Rocknest** [comment]
Do i understand this correctly: a file that was specified when invoking the zig compiler is the root source file (for example `zig build-exe main.zig` -> `main.zig`)?

**Comment by emekoi** [comment]
that is correct.

**Comment by shawnl** [comment]
There is a problem. If you `use @import("root")` you end up with infinite recursion.

**Comment by shawnl** [comment]
#1778 does not need this.

You just use a comptime global in a package's namespace (does that exist?), set from the root source file.

**Comment by emekoi** [comment]
@shawnl how would this introduce infinite recursion? due to zig's lazy nature that would be perfectly fine and is no different than:
```zig
pub const foo = @This();
```
for the root file. the following:
```zig
use @import("@root"); // or use @This();
```
would be an infinite loop but that is another issue (#2580) altogether.
