### ISSUE TITLE
Support exact matches for test filtering

### ISSUE THREAD

**Issue by icholy** [ziglang/zig#21901]
### Context

I wrote a little tool which compiles all tests in a source file into separate binaries and creates a `launch.json` file containing a configuration for each one. https://gist.github.com/icholy/722a8bcfbb80e63fc8380590c189ccf2

### Problem

Consider the following example:

``` zig
test "foo" {}
test "foobar" {}
```

I have no way of only running the "foo" test. `--test-filter foo` will run them both.

### Feature Request

Add a mechanism for performing exact match test filtering.

### Implementation Ideas

1. A new `--test-name` flag.
2. A special syntax for `--test-filter`
   -  `--test-filter '"foo"'` (quoted string means exact match)
   - `--test-filter "^foo$"` (support regex)

**Comment by xdBronch** [comment]
i may be mistaken but i dont believe this could really work, test names are fully qualified. for example this code inside a file `a.zig`
```zig
const Foo = struct {
    test "bar" {
        return error.fail;
    }
};

comptime {
    _ = Foo;
}
```
fails with the output `a.Foo.test.bar...FAIL (fail)`, i could add `--test-filter a` or `--test-filter Foo` and it still runs the same test because both of those are part of the fully qualified name

**Comment by icholy** [comment]
That's good to know. However, even if I updated my code to compute the FQN, but I'd still have the same problem:

 `--test-filter main.test.foo` would run both tests.

**Comment by xdBronch** [comment]
right yeah, i didnt mean that as a solution but to point out `--test-name foo` or `--test-filter "^foo$"` wouldnt work
i suppose `--test-filter "foo$"` would though

**Comment by icholy** [comment]
If `$` was supported then using `test.{name}$` would be relatively robust. It would also be pretty simple to implement.

``` diff
diff --git a/test/src/CompareOutput.zig b/test/src/CompareOutput.zig
index 58c1238705..6abc10aa62 100644
--- a/test/src/CompareOutput.zig
+++ b/test/src/CompareOutput.zig
@@ -93,7 +93,11 @@ pub fn addCase(self: *CompareOutput, case: TestCase) void {
                 case.name,
             }) catch @panic("OOM");
             for (self.test_filters) |test_filter| {
-                if (mem.indexOf(u8, annotated_case_name, test_filter)) |_| break;
+                if (mem.endsWith(u8, test_filter, "$")) {
+                    if (mem.endsWith(u8, annotated_case_name, test_filter)) |_| break;
+                } else {
+                    if (mem.indexOf(u8, annotated_case_name, test_filter)) |_| break;
+                }
             } else if (self.test_filters.len > 0) return;

             const exe = b.addExecutable(.{
```

**Comment by Vexu** [comment]
Related #13524

**Comment by icholy** [comment]
Closing in favor of https://github.com/ziglang/zig/issues/13524
