### ISSUE TITLE
`.field_access` AST nodes contain out-of-bounds indexes

### ISSUE THREAD

**Issue by DonIsaac** [ziglang/zig#21930]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

`.field_access` AST nodes store the [token index](https://github.com/ziglang/zig/blob/54d0ba418375a4665cf1b4ee876d6c750bb9c079/lib/std/zig/Parse.zig#L3577) of the accessed member's `.identifier` in their RHS. This token ID is often not a valid node id (though it seems like it is sometimes)? This causes basic AST traversal to fail.

```zig
const std = @import("std");
const Ast = std.zig.Ast;
const Node = Ast.Node;
const print = std.debug.print;

test "AST traversal over field access nodes" {
    const a = std.testing.allocator;
    const src = 
        \\const std = @import("std");
        \\const Allocator = std.mem.Allocator;
        \\const print = std.debug.print;
    ;
    const ast = try Ast.parse(a, src, .zig);


    for (ast.rootDecls()) |node_id| {
        try visit(&ast, node_id);
    }
}

fn visit(ast: *const Ast, node_id: Node.Index) !void {
    const tag: Node.Tag = ast.nodes.items(.tag)[node_id];
    const data: Node.Data = ast.nodes.items(.data)[node_id];
    print("tag: {any}\n", .{tag});

    if (data.lhs != 0) {
        try std.testing.expect(data.lhs < ast.nodes.len);
        try visit(ast, data.lhs);
    }
    if (data.rhs != 0) {
        try std.testing.expect(data.rhs < ast.nodes.len);
        try visit(ast, data.rhs); // <- panic
    }
}
```

### Expected Behavior

1. The above test case should not panic
2. Nodes should not store token IDs in `data.lhs` or `data.rhs` and advertise them as `Node.Index` _unless_ that index is also a correct node index (both in-bounds and pointing to the correct node)

**Comment by llogick** [comment]
https://github.com/ziglang/zig/blob/54d0ba418375a4665cf1b4ee876d6c750bb9c079/lib/std/zig/Ast.zig#L3050-L3051

clearly states that it is a token index, one cannot blindly index lhs and rhs as Node.Index as some of them are `SubRange`s or plain indexes into `extra_data`

**Comment by mlugg** [comment]
Yeah, this isn't a bug; `lhs` and `rhs` cannot be used without first checking the tag to determine how to interpret them. They may be node indices, token indices, indices into `extra_data`, or even unused/omitted (in which case they are generally given the value `0`).
