### ISSUE TITLE
Cannot use comptime if to call `dupe` vs `dupeZ`

### ISSUE THREAD

**Issue by DonIsaac** [ziglang/zig#21949]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

I have this function that inspects some type `T` to find the best way to clone its contents.

```zig
        pub fn borrowMut(self: *Self) Allocator.Error!*T {
            if (self.__repr.isOwned()) return self.__repr.ptr(T);

            if (comptime hasClone) {
              // omitted
            } else if (comptime slice_ty != null) { // < e.g u8 in `[]const u8` or `[:0] const u8`. `null` for non array/slice types
                // use dupeZ for sentinel-terminated arrays, or dupe for slices
                const is_sentinel = info == .Pointer and info.Pointer.sentinel != null;
                @compileLog(is_sentinel); // prints @as(bool, true)
                if (is_sentinel) {
                    const ptr = try self.alloc.dupeZ(slice_ty.?, self.__repr.ptr(T));
                    self.__repr = Repr.new(ptr, true);
                } else {

                    // this branch isn't getting called
                    const ptr = try self.alloc.dupe(slice_ty.?, self.__repr.ptr(T));
                    //                            error is here ^^^^^^^^^^^^^^^^^^
                    self.__repr = Repr.new(ptr, true);
                    @compileError("other branch should be getting hit");
                }
            } else {
                // omitted
            }

            return self.__repr.ptr(T);
        }
```

It produces the following obscure error:
```
zig build test
test
└─ run test
   └─ zig test Debug native 1 errors
src/Boo.zig:109:81: error: expected type '[]const u8', found '*[:0]const u8'
                    const ptr = try self.alloc.dupeZ(slice_ty.?, self.__repr.ptr(T));
                                                                 ~~~~~~~~~~~~~~~^~~
/home/linuxbrew/.linuxbrew/Cellar/zig/0.13.0/lib/zig/std/mem/Allocator.zig:325:57: note: parameter type declared here
pub fn dupeZ(allocator: Allocator, comptime T: type, m: []const T) Error![:0]T {
                                                        ^~~~~~~~~
referenced by:
    test.mutating a statically-initialized string Boo: src/Boo.zig:213:24
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

Compile Log Output:
@as(bool, true)
```

### Expected Behavior

Since `T` is a sentinel-terminated type, and branch handling slice types is not getting evaluated, no error should be produced.

**Comment by rohlem** [comment]
Two more notes to above comment:
- You can use `std.mem.span` for `[*:0]T` -> `[]T`
- Comments written inline show up in the error trace, so `const ptr = ...; //error is here` would show up in the error trace if you commented on the correct line.

**Comment by DonIsaac** [comment]
> - Comments written inline show up in the error trace, so `const ptr = ...; //error is here` would show up in the error trace if you commented on the line being referenced.

Yeah I added the comments afterwards to make it clearer in this issue. They're not part of the original code.

**Comment by mlugg** [comment]
This does not appear to be a bug, and even if it were, your reproduction is highly incomplete. The "Steps to Reproduce and Observed Behavior" should contain **all necessary steps**, so that someone who is not you can follow the steps and get precisely the same result as you. You have not provided your full source code, so this reproduction is not useful.
