### ISSUE TITLE
zig fmt: vertically align adjacent struct field decls

### ISSUE THREAD

**Issue by hryx** [ziglang/zig#2195]
Proposal: vertically align the type halves of struct field declarations. This should only be applied to adjacent lines; empty lines and comments end a group of aligned fields.

This is the policy in `go fmt` and I've found it significantly helps the readability of certain structs. I can tackle this before 0.4.0 but wanted to get approval first.

Before:

```zig
pub const FailingAllocator = struct {
    allocator: mem.Allocator,
    index: usize,
    fail_index: usize,
    // interrupted by comment or empty line
    internal_allocator: *mem.Allocator,
    allocated_bytes: usize,
    freed_bytes: usize,
    deallocations: usize,

    // pub fn init() ...
}
```

After:

```zig
pub const FailingAllocator = struct {
    allocator:  mem.Allocator,
    index:      usize,
    fail_index: usize,
    // interrupted by comment or empty line
    internal_allocator: *mem.Allocator,
    allocated_bytes:    usize,
    freed_bytes:        usize,
    deallocations:      usize,

    // pub fn init() ...
}
```

See also: https://github.com/ziglang/zig/issues/1793 , https://github.com/ziglang/zig/issues/2196

**Comment by andrewrk** [comment]
See https://github.com/ziglang/zig/issues/2196#issuecomment-482004553
