### ISSUE TITLE
cli: `zig fetch <url>` should accept a github repo url

### ISSUE THREAD

**Issue by DonIsaac** [ziglang/zig#21951]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

> NOTE: this should be an enhancement request but there's no corresponding issue template.

Instead of needing to provide an explicit link to a source tarball, I should be able to run `zig fetch https://github.com/user/some-package`

### Expected Behavior

Running this prints this error message:
![image](https://github.com/user-attachments/assets/394e7dec-9682-403f-9436-7102be567dcf)

In either case, what kind of URL `zig fetch` requires should be specified in `zig fetch --help`, and the error message should say something like "Please provide a url to a source tarball"

**Comment by zxcv05** [comment]
add `git+` to the start of your url

**Comment by bentheklutz** [comment]
As the other commenter suggested, you want `git fetch --save git+https://github.com/user/project`

Be aware though that this resolves the current head of that branch and saves exactly that in the cache. You won't get updates from the dependency's repository without re-fetching from the `git+` URL again as far as I understand.

**Comment by andrewrk** [comment]
not a bug

**Comment by scripturial** [comment]
Quick amendment to above, it's

     zig fetch --save git+https://github.com/user/project
 
 not 
 
    git fetch --save git+https://github.com/user/project
