### ISSUE TITLE
zig warmup

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#21966]
Zig has "sub programs" like `zig fmt` which are compiled on demand on the host machine. This can reduce the size of the zig installation archive and also allows these sub programs to be compiled with host-specific architecture flags. However, the initial compilation of these sub-programs can take a while. In the case of `zig fmt`, editors don't have much choice but to prevent a document from being edited while it waits for zig to compile the format tool.

An idea to mitigate this scenario is to have tools like `zigup` warmup the toolchain by pre-compiling these programs before considering zig "ready".  We can easily do this for `zig fmt` but I've seen talk of deploying other "sub programs" this way, so, it might be worth adding a generic `zig warmup` command that compiles all sub programs deployed in this manner.

**Comment by rohlem** [comment]
If I correctly understand, you propose `zig warmup` to build all subcommands.
That doesn't seem useful to me - no use case would ever want to use all subcommands.
If you know your use case uses subcommands x, y, z, then your tool can already run `zig x`, `zig y`, `zig z` in status-quo, and only take the time and space required for those subcommands.
Instead running the proposed `zig warmup` implies potentially building subcommands the user would never use.

**Comment by alexrp** [comment]
The syntax could be `zig warmup [subcommand]`, where leaving off `subcommand` means "build all subcommands". Then `zigup` could allow the user to configure which subcommands they care about.

**Comment by marler8997** [comment]
> That doesn't seem useful to me - I don't know a use case that would ever want to use all possible subcommands exhaustively.

You do bring up a good point here in that as zig may be adding more programs like this, it might be wasteful/undesirable to pre-compile all sub programs as some might never be needed.  Maybe for cases like zigup we just run `zig fmt --help` by default and call that good.  I can still think of use cases where one might still want a warmup command, for example say you have a CI system that is able to cache the system tools used for compilation, you might want to cache the system after zig has warmed up rather than before.

**Comment by andrewrk** [comment]
IMO, `zig fmt` is the only pain point here since the delay is unexpected and not obvious (can easily be misinterpreted as making the editor hang), where as the other subcommands display a progress indicator and there's no question about what's happening.

**Comment by marler8997** [comment]
Ok thanks for the feedback, sounds like a general warmup may not be all that useful after all.  Closing.
