### ISSUE TITLE
unreachable code error prevents idiomatic usage of defer

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2198]
```zig
const std = @import("std");
const assert = std.debug.assert;

pub fn main() void {
    const ptr = std.debug.global_allocator.create(i32);
    defer std.debug.global_allocator.destroy(ptr);

    std.os.exit(0);
}
```

Expected: this compiles.

Actual:

```
/home/andy/dev/zig/build/test.zig:6:11: error: unreachable code
    defer std.debug.global_allocator.destroy(ptr);
          ^
```

**Comment by tiehuis** [comment]
Existing example of this in the self-hosted compiler.

https://github.com/ziglang/zig/blob/master/src-self-hosted/main.zig#L65-L68

**Comment by andrewrk** [comment]
This might be solved with #283

**Comment by daurnimator** [comment]
oooo, this is really interesting, and infact a "good thing"!
If a `longjmp`-ing function is defined as `noreturn` then we correctly catch a skipped `defer` at compile time.

**Comment by Rocknest** [comment]
So `defer` should run before `std.os.exit()`?

**Comment by daurnimator** [comment]
> So `defer` should run before `std.os.exit()`?

I'm not sure that's useful in the general case. If I have a function annotated `noreturn` like `exit()` do you even *want* `defer` statements to run?
What about if it's a sometimes-`noreturn` function like `execve()` (which can return an error if e.g. the executable is invalid)? => in that case I would probably want `defer` to run on failure but other times not at all.

**Comment by andrewrk** [comment]
This is now a duplicate of accepted proposal #2654. See the explanation there. Preferred solution to the above code is:

```zig
defer unreachable;
```
