### ISSUE TITLE
std.crypto.core.keccak: do not overpermute the sponge

### ISSUE THREAD

**Issue by krutimyltan2** [ziglang/zig#22019]
### Zig Version

0.12.0+efe06c5f3

### Steps to Reproduce and Observed Behavior

The following code:

```zig
const std = @import("std");
const keccak = std.crypto.core.keccak;
const State = keccak.State;

pub fn main() !void {
    var k: State(1600, 512, 24) = .{ .delim = 0x01 };
    k.absorb(&[_]u8 { 0x13 } ** 136); // not important
    var out: [136]u8 = undefined;
    k.squeeze(out[0..]);

    std.debug.print("{any}", .{k.st.st});
}
```

results in

```
{ 7233668778566134865, 11592713930134003118, 15373517831437853021, 15608250416844938208, 11330810810757603158, 6337136767010511286, 1240513802066837974, 4881489601663522637, 1927467063577625972, 17630746601708290681, 12181661910834865096, 13184932669851834457, 11304855261261663641, 8294672726897056558, 8839467195840986991, 7083940663377158003, 11394419039461769406, 8921936926094339996, 2284247437489028585, 13015763828452273947, 15409054831738269266, 10463282502587619091, 600522821999583161, 7632801731005224094, 8117278901483848959 }
```

### Expected Behavior

The result of the above *should* be

```
{ 3064831273020639228, 13512604793548462962, 12805899729923228041, 6119062306464645338, 4536591997206582897, 14771343959304370689, 2013378616438251871, 14173905344357195255, 4698469717602941177, 5222380363174343544, 13163819436985973242, 4908270899219160089, 12120744815160992576, 13809031795350906813, 533294723529621938, 14014335485794523625, 17720142420523044394, 18278950936426394526, 15638265930130015358, 14236447863273458192, 16962296917699274481, 10248514880263995001, 1834222953400603767, 2439774991396631628, 8370602107368013381 }
```

The reason for this is that the `squeeze` function permutes the state even when the requested output length is not greater than the rate.

1. The current implementation does not follow the specification (e.g. Algorithm 4 in [CSF](https://keccak.team/files/CSF-0.1.pdf)). Which makes it hard to use the `squeeze` as a primitive.
2. The current implementation will permute the state one  more time than what is needed in for example `Sha3` since it permutes the state after the final `extractBytes` but never uses the permuted state.

Caveats; there may be some update to the specification of which I am unaware, but it is notable that also [XKCP the reference implementation in Python](https://github.com/XKCP/XKCP/blob/master/Standalone/CompactFIPS202/Python/CompactFIPS202.py) does not conform with the current Zig standard libray implementation. They do however not put the squeeze part in a separate function.

Finally; changing the [line 277](https://github.com/ziglang/zig/blob/master/lib/std/crypto/keccak_p.zig#L277) to include a condition (for example `if (i + rate < out.len)`) does not seem to change the result of any of the unit tests (in particular all the `Sha3` unit tests all still pass). It (presumably) only makes it faster.

**Comment by jedisct1** [comment]
Unconditionally performing a permutation after extracting bytes is intentional to mitigate the implications of misuse. Otherwise, calling `squeeze` multiple times could return the same output between calls. 

We can add an unsafe version of `final/squeeze` that would only be used where the state is not publicly accessible, such as in the `Keccak.hash()` function.  But in the general `squeeze` function, I'd rather keep favoring proactive security over trying to mimic what some other implementation does.

**Comment by jedisct1** [comment]
Alternatively, we can keep track of how many bytes have been squeezed and resume from there, similar to what `absorb()` does. That would  avoid unnecessary permutations without making the API a footgun.

**Comment by jedisct1** [comment]
The `squeeze-absorb-squeeze` pattern should not be possible. A permutation is required to transition from absorption to squeezing and the other way round.

Fun fact: at the End-Of-Escada workshop, Joan Daemen was one offered a dice game where the goal is to avoid such sequences. If you do, you lose the game :)

**Comment by jedisct1** [comment]
#22020 makes `squeeze()` permute the state only when required.

>  squeeze one block (without permuting the state), absorb back that block

That would be equivalent to zeroing the state 😕
