### ISSUE TITLE
Comparison with undefined has different behavior on Windows and Linux

### ISSUE THREAD

**Issue by buzmeg** [ziglang/zig#22010]
### Zig Version

0.14.0-dev.2126+e27b4647d

### Steps to Reproduce and Observed Behavior

I have the following code:
```
linfo("C: {} {}", .{foo == undefined, foo != undefined});
```

foo is a VkFence returned from vkCreateFence in Vulkan.

On Windows I get "false false" on Linux I got "true true".

### Expected Behavior

I guess, runtime crash?  We're clearly not supposed to be using "undefined" in runtime checks anymore.

**Comment by xdBronch** [comment]
afaik this is more or less expected and allowed. comparing to undefined is only an error and considered UB when branching on it e.g. `if (foo == undefined)`. simply observing the value is fine but the result isnt something to be relied on

**Comment by mlugg** [comment]
Not a bug; runtime safety for branching on `undefined` (which `std.fmt` ultimately does, making this example UB) is #63. (That said, `std.fmt` *could* be improved to emit a compile error when passed a comptime-known `undefined`, as it is in this case.)

**Comment by buzmeg** [comment]
This fell out of an assert(), actually.  The fmt was simply how I tracked it down.

**Comment by Beyley** [comment]
> This fell out of an assert(), actually. The fmt was simply how I tracked it down. The assert(foo != undefined) passed on Linux but failed on Windows.

You're not supposed to compare against `undefined`. That assert is undefined behaviour, as it's branching on `undefined`. `undefined` has no set value, and it does not make sense to compare against it anyway.
