### ISSUE TITLE
Implicit error types crash stage1

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2203]
If you use an implicit error in a switch
```
catch |err| switch (err) {
.MyError =>
}
``` 
it will crash with 
```
zig: ../src/ir.cpp:21037: IrInstruction* ir_analyze_instruction_check_switch_prongs(IrAnalyze*, IrInstructionCheckSwitchProngs*): Assertion `start_value->value.type->id == ZigTypeIdErrorSet' failed.
```

Glad I finially figured out what the bug was...so I can work around it and continue hacking.

**Comment by LemonBoy** [comment]
The parser recognizes `.MyError` as a ZigTypeIdEnumLiteral, we can either reject this with a proper error instead of an assertion or make it work by teaching the compiler how to cast it to a `ZigTypeIdErrorSet`.

**Comment by shawnl** [comment]
> or make it work by teaching the compiler how to cast it to a ZigTypeIdErrorSet.
+1

**Comment by andrewrk** [comment]
It's a compile error, because:

```zig
const Error = error {Bad};
const Enum = enum {Bad};
fn foo() Error!Enum {
    return .Bad; // what does this do?
}
```

Feel free to open a proposal to discuss more.
