### ISSUE TITLE
MacOS Homebrew: No head is defined for zig

### ISSUE THREAD

**Issue by eli-front** [ziglang/zig#22041]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

Running `brew install zig --HEAD` returns `Error: No head is defined for zig`

### Expected Behavior

Homebrew should allow you to install the most recent version. Currently only 13.0.0 is available on brew.

**Comment by vvvvv** [comment]
@eli-front I was also frustrated by this, so I created Homebrew tap for Zig nightly builds.

This is a cask, so Zig is not built from source. 
Instead the official nightly binaries are installed.  
I wanted to announce this to make macOS users in the Zig community aware, but I’m not entirely sure where the best place to announce it would be.

For now, simply run:
```
brew tap vvvvv/zig
brew install --cask zig@nightly
```

You can find the repository here https://github.com/vvvvv/homebrew-zig
