### ISSUE TITLE
Autodoc: embedding html in document comments causes rendering errors

### ISSUE THREAD

**Issue by MINGtoMING** [ziglang/zig#22043]
### Zig Version

0.14.0-dev.2270+a5d4ad17b

### Steps to Reproduce and Observed Behavior

- root.zig
```zig
//! By convention, root.zig is the root source file when making a library. If
//! you are making an executable, the convention is to delete this file and
//! start with `main.zig` instead.
const std = @import("std");
const testing = std.testing;

/// Add func.
/// <div style="display: flex; align-items: center;">
/// <div style="margin-right: 10px;">
/// </div>
/// <div style="background-color: rgb(0, 0, 255); width: 50px; height: 20px; border: 1px solid #ccc;"></div>
/// </div>
pub fn add(a: i32, b: i32) i32 {
    return a + b;
}

test add {
    try testing.expect(add(3, 7) == 10);
}
```

- current result:
![image](https://github.com/user-attachments/assets/e90542c0-980f-4315-ad9d-1f5779dbdf9d)

The corresponding html content is not rendered properly.

### Expected Behavior

- expected result:
![image](https://github.com/user-attachments/assets/49ee383c-c41c-4a90-bc91-9afc1fb61eb2)

**Comment by Beyley** [comment]
I believe this is intentional, not a bug.

Zig document comments are markdown, not HTML.

**Comment by MINGtoMING** [comment]
@Beyley Thanks, got it.
