### ISSUE TITLE
Regression in behaviour of @alignOf in zig=0.13

### ISSUE THREAD

**Issue by KAction** [ziglang/zig#22059]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

Following code:

```
const std = @import("std");

const Foo = packed struct { value: u56 };
const Bar = packed struct { value: u56 };

const My = packed struct { foo: Foo, bar: Bar };

pub fn main() !void {
    std.debug.print("@alignOf = {}\n", .{@alignOf(My)});
}
```

prints 8 under `zig=0.11` and `zig=0.12`, but 16 under `zig=0.13`.

### Expected Behavior

I expect the behaviour of `@alignOf` to be stable across versions of the compiler.

**Comment by nektro** [comment]
`My` gets lowered as a `u112` which in essence becomes a `u128`.
what was the target when you compiled and ran this?

**Comment by KAction** [comment]
```
zig run align.zig
```

on my x86-64 laptop.

**Comment by KAction** [comment]
> `My` gets lowered as a `u112` which in essence becomes a `u128`. what was the target when you compiled and ran this?

Sounds reasonable, but previously `My` was treated as two `u64`, which I believe is strictly better.

**Comment by nektro** [comment]
btw you can reproduce that behavior if you make `My` non-`packed`

**Comment by KAction** [comment]
I can, but I need it to be packed so I can serialize it to bytes via pointer casting:

```
Unlike normal structs, packed structs have guaranteed in-memory layout:
```

I read this that if I were able to map packed struct to some address using old version of binary, I should be able to do the same using new version compiled with a new version of compiler.

**Comment by KAction** [comment]
If that is not the case, I guess I can manually add padding to get my 8 alignment back.

```
const My = packed struct { foo: Foo, p1: u8, bar: Bar, p2: u8 };
```

That will be backward-incompatible change, though.

**Comment by xdBronch** [comment]
iiuc this is because of a bug that was in previous versions of llvm, the alignment of u128 was 8 when it shouldve been 16. not sure if theres any article on llvm itself but rust wrote about the problem https://blog.rust-lang.org/2024/03/30/i128-layout-update.html

**Comment by nektro** [comment]
`extern` structs also have a guaranteed memory layout

**Comment by KAction** [comment]
But they can't have u56. And the whole idea of u56 is that I can put it next to u8 and get something 8 bytes size. With extern structs I'd have to pack/unpack u8 and u56 part manually.

**Comment by KAction** [comment]
> iiuc this is because of a bug that was in previous versions of llvm, the alignment of u128 was 8 when it shouldve been 16. not sure if theres any article on llvm itself but rust wrote about the problem https://blog.rust-lang.org/2024/03/30/i128-layout-update.html

Thank you. Okay, I'll add padding manually then.
