### ISSUE TITLE
`__clzsi2_thumb1()` fails to link due to `R_ARM_ABS32` relocation error with PIC

### ISSUE THREAD

**Issue by ikskuh** [ziglang/zig#22050]
### Zig Version

0.14.0-dev.2271+f845fa04a

### Steps to Reproduce and Observed Behavior

Compile any file with

```sh-session
[user@host ~]$ zig build-exe -target thumb-freestanding-eabi -mcpu cortex_m0plus -fPIE stub.zig 
```

which results in

```sh-session
[user@host ~]$ zig build-exe -target thumb-freestanding-eabi -mcpu cortex_m0plus -fPIE src/main.zig 
error: ld.lld: relocation R_ARM_ABS32 cannot be used against local symbol; recompile with -fPIC
    note: defined in /home/user/.cache/zig/o/…/libcompiler_rt.a(/home/user/.cache/zig/o/…/libcompiler_rt.a.o)
    note: referenced by compiler_rt
    note:               /home/user/.cache/zig/o/…/libcompiler_rt.a.o:(__clzsi2) in archive /home/user/.cache/zig/o/…/libcompiler_rt.a
[user@host ~]$ 
```

`stub.zig` may look like this:
```zig
export fn _start() void {}
```

### Expected Behavior

`compiler_rt` should be compiled with -fPIC if the build artifact is built as position independent code (-fPIC, -fPIE)

### Related Issues

- potentially #16957

**Comment by ikskuh** [comment]
Ashet OS is currently kinda blocking on this as i want to add support for ARM systems and i need PIE executables to be able to load applications without virtual memory

**Comment by alexrp** [comment]
To clarify, is this a regression or does it also happen with 0.13.0?
