### ISSUE TITLE
Linking against system library does not actually link

### ISSUE THREAD

**Issue by Raff727** [ziglang/zig#22091]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

This is a continuation of [my issue on raylib-zig](https://github.com/Not-Nik/raylib-zig/issues/157) as it seems like this is a general zig problem.
To reproduce you should run Linux with a Wayland desktop, clone the raylib-zig repo and run zig build basic-window this should result in an error message that includes the line 
`WARNING: GLFW: Error: 65544 Description: Wayland: Failed to load libwayland-client`
This is the easiest way to try and reproduce this error, I of course have my own program setup which is basically just that basic window example, but I have tried to modify the standard `zig init` build.zig to get it to work, without success.
I have not been able to add any sort of options like linkSystemLibrary calls that result in this error disappearing.
I even tried compiling to an object file first and then linking, but this did not even get me to the original error.

### Expected Behavior

Expected was that the program runs and opens a small window with a white background. This can be observed by cloning and compiling the normal c raylib and running its core_basic_window program found in examples/core/ which works as intended.

**Comment by BratishkaErik** [comment]
Can't reproduce on `0.13.0` and `0.14.0-dev.2321+6cf01a679`:

```
INFO: Initializing raylib 5.5
INFO: Platform backend: DESKTOP (GLFW)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 2560 x 1600
INFO:     > Screen size:  800 x 450
INFO:     > Render size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 238
INFO: GL: OpenGL device information:
INFO:     > Vendor:   AMD
INFO:     > Renderer: AMD Radeon 760M (radeonsi, gfx1103_r1, LLVM 18.1.8, DRM 3.59, 6.11.10-gentoo-dist)
INFO:     > Version:  4.6 (Core Profile) Mesa 24.2.6
INFO:     > GLSL:     4.60
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: PLATFORM: DESKTOP (GLFW - X11): Initialized successfully
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: SYSTEM: Working Directory: /home/bratishkaerik/github.com/raylib-zig
INFO: TIMER: Target time per frame: 16.667 milliseconds
```

**Comment by Raff727** [comment]
You seem to be running X11 

> INFO: PLATFORM: DESKTOP (GLFW - X11): Initialized successfully

this issue refers to Wayland and that it doesn't link libwayland-client properly.

**Comment by BratishkaErik** [comment]
Sorry, here's new command, still can't reproduce:

```
zig build basic_window -Dlinux_display_backend=Wayland

INFO: Initializing raylib 5.5
INFO: Platform backend: DESKTOP (GLFW)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
WARNING: GLFW: Error: 65548 Description: Wayland: The platform does not provide the window position
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 2560 x 1600
INFO:     > Screen size:  800 x 450
INFO:     > Render size:  800 x 450
INFO:     > Viewport offsets: 0, 0
WARNING: GLFW: Error: 65548 Description: Wayland: The platform does not support setting the window position
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 238
INFO: GL: OpenGL device information:
INFO:     > Vendor:   AMD
INFO:     > Renderer: AMD Radeon 760M (radeonsi, gfx1103_r1, LLVM 18.1.8, DRM 3.59, 6.11.10-gentoo-dist)
INFO:     > Version:  4.6 (Core Profile) Mesa 24.2.6
INFO:     > GLSL:     4.60
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: PLATFORM: DESKTOP (GLFW - Wayland): Initialized successfully
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: SYSTEM: Working Directory: /home/bratishkaerik/github.com/raylib-zig
INFO: TIMER: Target time per frame: 16.667 milliseconds
```

**Comment by Raff727** [comment]
What wayland libraries do you have installed and where are they? Maybe I am missing something there, but I should have the dev package installed, and I do have these:
lib/x86_64-linux-gnu/libwayland-client.so.0.23.0
lib/x86_64-linux-gnu/libwayland-client.so.0
lib/x86_64-linux-gnu/libwayland-client.so

**Comment by BratishkaErik** [comment]
```
equery f wayland
 * Searching for wayland ...
 * Contents of dev-libs/wayland-1.23.1:
/usr
/usr/include
/usr/include/wayland-client-core.h
/usr/include/wayland-client-protocol.h
/usr/include/wayland-client.h
/usr/include/wayland-cursor.h
/usr/include/wayland-egl-backend.h
/usr/include/wayland-egl-core.h
/usr/include/wayland-egl.h
/usr/include/wayland-server-core.h
/usr/include/wayland-server-protocol.h
/usr/include/wayland-server.h
/usr/include/wayland-util.h
/usr/include/wayland-version.h
/usr/lib
/usr/lib/libwayland-client.so -> libwayland-client.so.0
/usr/lib/libwayland-client.so.0 -> libwayland-client.so.0.23.1
/usr/lib/libwayland-client.so.0.23.1
/usr/lib/libwayland-cursor.so -> libwayland-cursor.so.0
/usr/lib/libwayland-cursor.so.0 -> libwayland-cursor.so.0.23.1
/usr/lib/libwayland-cursor.so.0.23.1
/usr/lib/libwayland-egl.so -> libwayland-egl.so.1
/usr/lib/libwayland-egl.so.1 -> libwayland-egl.so.1.23.1
/usr/lib/libwayland-egl.so.1.23.1
/usr/lib/libwayland-server.so -> libwayland-server.so.0
/usr/lib/libwayland-server.so.0 -> libwayland-server.so.0.23.1
/usr/lib/libwayland-server.so.0.23.1
/usr/lib/pkgconfig
/usr/lib/pkgconfig/wayland-client.pc
/usr/lib/pkgconfig/wayland-cursor.pc
/usr/lib/pkgconfig/wayland-egl-backend.pc
/usr/lib/pkgconfig/wayland-egl.pc
/usr/lib/pkgconfig/wayland-server.pc
/usr/lib64
/usr/lib64/libwayland-client.so -> libwayland-client.so.0
/usr/lib64/libwayland-client.so.0 -> libwayland-client.so.0.23.1
/usr/lib64/libwayland-client.so.0.23.1
/usr/lib64/libwayland-cursor.so -> libwayland-cursor.so.0
/usr/lib64/libwayland-cursor.so.0 -> libwayland-cursor.so.0.23.1
/usr/lib64/libwayland-cursor.so.0.23.1
/usr/lib64/libwayland-egl.so -> libwayland-egl.so.1
/usr/lib64/libwayland-egl.so.1 -> libwayland-egl.so.1.23.1
/usr/lib64/libwayland-egl.so.1.23.1
/usr/lib64/libwayland-server.so -> libwayland-server.so.0
/usr/lib64/libwayland-server.so.0 -> libwayland-server.so.0.23.1
/usr/lib64/libwayland-server.so.0.23.1
/usr/lib64/pkgconfig
/usr/lib64/pkgconfig/wayland-client.pc
/usr/lib64/pkgconfig/wayland-cursor.pc
/usr/lib64/pkgconfig/wayland-egl-backend.pc
/usr/lib64/pkgconfig/wayland-egl.pc
/usr/lib64/pkgconfig/wayland-server.pc
/usr/share
/usr/share/doc
/usr/share/doc/wayland-1.23.1
/usr/share/doc/wayland-1.23.1/README.md.bz2
```

**Comment by Raff727** [comment]
ok I have the same files only as version 1.23.0/0.23.0 and copying or symlinking them into /usr/lib and /usr/lib64 does not make it work.

**Comment by BratishkaErik** [comment]
Can you show full output with `zig build basic_window [your args] --verbose --summary all --debug-pkg-config`?

**Comment by Raff727** [comment]
Command used: `zig build basic_window -Dlinux_display_backend=Wayland --verbose --summary all --debug-pkg-config`
inside a fresh folder made with `git clone https://github.com/Not-Nik/raylib-zig.git`


wayland-scanner private-code /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/viewporter.xml /home/raff/raylib-zig/.zig-cache/o/fb75af8258fe027345ea341a71f8be18/viewporter-client-protocol-code.h
wayland-scanner private-code /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/pointer-constraints-unstable-v1.xml /home/raff/raylib-zig/.zig-cache/o/4edca8d33703b33a1856534842c652df/pointer-constraints-unstable-v1-client-protocol-code.h
wayland-scanner private-code /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/xdg-activation-v1.xml /home/raff/raylib-zig/.zig-cache/o/2e03b0b633e360e5ce10248efaf48f8a/xdg-activation-v1-client-protocol-code.h
wayland-scanner client-header /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/wayland.xml /home/raff/raylib-zig/.zig-cache/o/df5697e76b0644e55f964d1132655b47/wayland-client-protocol.h
wayland-scanner client-header /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/xdg-decoration-unstable-v1.xml /home/raff/raylib-zig/.zig-cache/o/e3c48898a3219afe96fcade5ed7ba9dd/xdg-decoration-unstable-v1-client-protocol.h
wayland-scanner private-code /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/wayland.xml /home/raff/raylib-zig/.zig-cache/o/817e2166d7eb9a84868db6e1494f3565/wayland-client-protocol-code.h
wayland-scanner client-header /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/pointer-constraints-unstable-v1.xml /home/raff/raylib-zig/.zig-cache/o/8f5f476ffb1d4a8926ef3784500311a2/pointer-constraints-unstable-v1-client-protocol.h
wayland-scanner client-header /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/idle-inhibit-unstable-v1.xml /home/raff/raylib-zig/.zig-cache/o/e4d91397c2507661fb21b910a64f4278/idle-inhibit-unstable-v1-client-protocol.h
wayland-scanner private-code /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/xdg-shell.xml /home/raff/raylib-zig/.zig-cache/o/b0a1a5f571c50ba8cfb7412f4c7f138f/xdg-shell-client-protocol-code.h
wayland-scanner private-code /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/relative-pointer-unstable-v1.xml /home/raff/raylib-zig/.zig-cache/o/dfdb209bc916bb5cf1c6df59ec89b58a/relative-pointer-unstable-v1-client-protocol-code.h
wayland-scanner client-header /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/relative-pointer-unstable-v1.xml /home/raff/raylib-zig/.zig-cache/o/14913fc5e4486b29581a94d834272d9d/relative-pointer-unstable-v1-client-protocol.h
wayland-scanner private-code /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/xdg-decoration-unstable-v1.xml /home/raff/raylib-zig/.zig-cache/o/fc9d6c5950f66574276ea89b686cdc32/xdg-decoration-unstable-v1-client-protocol-code.h
wayland-scanner client-header /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/xdg-activation-v1.xml /home/raff/raylib-zig/.zig-cache/o/634b1dfe30269fd37f191ff8492ff269/xdg-activation-v1-client-protocol.h
wayland-scanner private-code /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/fractional-scale-v1.xml /home/raff/raylib-zig/.zig-cache/o/51058d14402cf6107c7b76980d8eff3f/fractional-scale-v1-client-protocol-code.h
wayland-scanner client-header /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/viewporter.xml /home/raff/raylib-zig/.zig-cache/o/b8472d5561ba8fd0c93a350e504bc017/viewporter-client-protocol.h
wayland-scanner private-code /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/idle-inhibit-unstable-v1.xml /home/raff/raylib-zig/.zig-cache/o/a7fb6458b92bf181d700089e7b281404/idle-inhibit-unstable-v1-client-protocol-code.h
wayland-scanner client-header /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/fractional-scale-v1.xml /home/raff/raylib-zig/.zig-cache/o/40a39149d826b24584f7809884f2879a/fractional-scale-v1-client-protocol.h
wayland-scanner client-header /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/deps/wayland/xdg-shell.xml /home/raff/raylib-zig/.zig-cache/o/09f3559798ef9b67dc172a04359ed068/xdg-shell-client-protocol.h
/nix/store/5yk32f31879lfsnyv0yhl0af0v2dz9dz-zig-0.13.0/bin/zig build-lib -lEGL -lwayland-client -lxkbcommon -cflags -std=gnu99 -D_GNU_SOURCE -DGL_SILENCE_DEPRECATION=199309L -fno-sanitize=undefined -- /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/rcore.c /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/utils.c /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/raudio.c /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/rmodels.c /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/rshapes.c /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/rtext.c /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/rtextures.c /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/rglfw.c -cflags -std=gnu99 -D_GNU_SOURCE -DGL_SILENCE_DEPRECATION=199309L -fno-sanitize=undefined -- /home/raff/raylib-zig/.zig-cache/o/ec6be00b9a4f00e4bc20631af1f78af7/raygui.c -ODebug -I /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src/external/glfw/include -I /home/raff/raylib-zig/.zig-cache/o/df5697e76b0644e55f964d1132655b47 -I /home/raff/raylib-zig/.zig-cache/o/817e2166d7eb9a84868db6e1494f3565 -I /home/raff/raylib-zig/.zig-cache/o/09f3559798ef9b67dc172a04359ed068 -I /home/raff/raylib-zig/.zig-cache/o/b0a1a5f571c50ba8cfb7412f4c7f138f -I /home/raff/raylib-zig/.zig-cache/o/e3c48898a3219afe96fcade5ed7ba9dd -I /home/raff/raylib-zig/.zig-cache/o/fc9d6c5950f66574276ea89b686cdc32 -I /home/raff/raylib-zig/.zig-cache/o/b8472d5561ba8fd0c93a350e504bc017 -I /home/raff/raylib-zig/.zig-cache/o/fb75af8258fe027345ea341a71f8be18 -I /home/raff/raylib-zig/.zig-cache/o/14913fc5e4486b29581a94d834272d9d -I /home/raff/raylib-zig/.zig-cache/o/dfdb209bc916bb5cf1c6df59ec89b58a -I /home/raff/raylib-zig/.zig-cache/o/8f5f476ffb1d4a8926ef3784500311a2 -I /home/raff/raylib-zig/.zig-cache/o/4edca8d33703b33a1856534842c652df -I /home/raff/raylib-zig/.zig-cache/o/40a39149d826b24584f7809884f2879a -I /home/raff/raylib-zig/.zig-cache/o/51058d14402cf6107c7b76980d8eff3f -I /home/raff/raylib-zig/.zig-cache/o/634b1dfe30269fd37f191ff8492ff269 -I /home/raff/raylib-zig/.zig-cache/o/2e03b0b633e360e5ce10248efaf48f8a -I /home/raff/raylib-zig/.zig-cache/o/e4d91397c2507661fb21b910a64f4278 -I /home/raff/raylib-zig/.zig-cache/o/a7fb6458b92bf181d700089e7b281404 -I /home/raff/.cache/zig/p/1220d93782859726c2c46a05450615b7edfc82b7319daac50cbc7c3345d660b022d7/src -I /home/raff/.cache/zig/p/122062b24f031e68f0d11c91dfc32aed5baf06caf26ed3c80ea1802f9e788ef1c358/src -D_GLFW_WAYLAND=1 -DPLATFORM_DESKTOP=1 -DPLATFORM_DESKTOP_GLFW=1 -Mroot -lc --cache-dir /home/raff/raylib-zig/.zig-cache --global-cache-dir /home/raff/.cache/zig --name raylib -static --listen=-
/nix/store/5yk32f31879lfsnyv0yhl0af0v2dz9dz-zig-0.13.0/bin/zig build-exe -lGL -lX11 /home/raff/raylib-zig/.zig-cache/o/0f6af8bd409e641987133dc891b87615/libraylib.a -ODebug -I /home/raff/raylib-zig/.zig-cache/o/306c444c9104ece73ec777b30aadbfcd --dep raylib --dep raygui -Mroot=/home/raff/raylib-zig/examples/core/basic_window.zig -ODebug -Mraylib=/home/raff/raylib-zig/lib/raylib.zig -ODebug --dep raylib-zig=raylib -Mraygui=/home/raff/raylib-zig/lib/raygui.zig -lEGL -lwayland-client -lxkbcommon -lc --cache-dir /home/raff/raylib-zig/.zig-cache --global-cache-dir /home/raff/.cache/zig --name basic_window --listen=-
/home/raff/raylib-zig/.zig-cache/o/60fb6baad1fd895fa3a4fcf9a347f2ed/basic_window
INFO: Initializing raylib 5.5
INFO: Platform backend: DESKTOP (GLFW)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
WARNING: GLFW: Error: 65544 Description: Wayland: Failed to load libwayland-client
WARNING: GLFW: Failed to initialize GLFW
Segmentation fault at address 0x0
???:?:?: 0x0 in ??? (???)
basic_window
└─ run basic_window failure
error: the following command terminated unexpectedly:
/home/raff/raylib-zig/.zig-cache/o/60fb6baad1fd895fa3a4fcf9a347f2ed/basic_window
Build Summary: 22/24 steps succeeded; 1 failed
basic_window transitive failure
└─ run basic_window failure
   └─ zig build-exe basic_window Debug native success 1s MaxRSS:185M
      ├─ zig build-lib raylib Debug native success 4s MaxRSS:226M
      │  ├─ run wayland-scanner (wayland-client-protocol.h) success 9ms MaxRSS:6M
      │  ├─ run wayland-scanner (wayland-client-protocol-code.h) success 6ms MaxRSS:6M
      │  ├─ run wayland-scanner (wayland-client-protocol.h) (reused)
      │  ├─ run wayland-scanner (wayland-client-protocol-code.h) (reused)
      │  ├─ run wayland-scanner (xdg-shell-client-protocol.h) success 4ms MaxRSS:6M
      │  ├─ run wayland-scanner (xdg-shell-client-protocol-code.h) success 4ms MaxRSS:6M
      │  ├─ run wayland-scanner (xdg-shell-client-protocol.h) (reused)
      │  ├─ run wayland-scanner (xdg-shell-client-protocol-code.h) (reused)
      │  ├─ run wayland-scanner (xdg-decoration-unstable-v1-client-protocol.h) success 4ms MaxRSS:6M
      │  ├─ run wayland-scanner (xdg-decoration-unstable-v1-client-protocol-code.h) success 2ms MaxRSS:6M
      │  ├─ run wayland-scanner (xdg-decoration-unstable-v1-client-protocol.h) (reused)
      │  ├─ run wayland-scanner (xdg-decoration-unstable-v1-client-protocol-code.h) (reused)
      │  ├─ run wayland-scanner (viewporter-client-protocol.h) success 2ms MaxRSS:6M
      │  ├─ run wayland-scanner (viewporter-client-protocol-code.h) success 3ms MaxRSS:6M
      │  ├─ run wayland-scanner (viewporter-client-protocol.h) (reused)
      │  ├─ run wayland-scanner (viewporter-client-protocol-code.h) (reused)
      │  ├─ run wayland-scanner (relative-pointer-unstable-v1-client-protocol.h) success 4ms MaxRSS:6M
      │  ├─ run wayland-scanner (relative-pointer-unstable-v1-client-protocol-code.h) success 3ms MaxRSS:6M
      │  ├─ run wayland-scanner (relative-pointer-unstable-v1-client-protocol.h) (reused)
      │  ├─ run wayland-scanner (relative-pointer-unstable-v1-client-protocol-code.h) (reused)
      │  ├─ run wayland-scanner (pointer-constraints-unstable-v1-client-protocol.h) success 8ms MaxRSS:6M
      │  ├─ run wayland-scanner (pointer-constraints-unstable-v1-client-protocol-code.h) success 3ms MaxRSS:6M
      │  ├─ run wayland-scanner (pointer-constraints-unstable-v1-client-protocol.h) (reused)
      │  ├─ run wayland-scanner (pointer-constraints-unstable-v1-client-protocol-code.h) (reused)
      │  ├─ run wayland-scanner (fractional-scale-v1-client-protocol.h) success 2ms MaxRSS:6M
      │  ├─ run wayland-scanner (fractional-scale-v1-client-protocol-code.h) success 1ms MaxRSS:6M
      │  ├─ run wayland-scanner (fractional-scale-v1-client-protocol.h) (reused)
      │  ├─ run wayland-scanner (fractional-scale-v1-client-protocol-code.h) (reused)
      │  ├─ run wayland-scanner (xdg-activation-v1-client-protocol.h) success 3ms MaxRSS:6M
      │  ├─ run wayland-scanner (xdg-activation-v1-client-protocol-code.h) success 3ms MaxRSS:6M
      │  ├─ run wayland-scanner (xdg-activation-v1-client-protocol.h) (reused)
      │  ├─ run wayland-scanner (xdg-activation-v1-client-protocol-code.h) (reused)
      │  ├─ run wayland-scanner (idle-inhibit-unstable-v1-client-protocol.h) success 2ms MaxRSS:6M
      │  ├─ run wayland-scanner (idle-inhibit-unstable-v1-client-protocol-code.h) success 1ms MaxRSS:6M
      │  ├─ run wayland-scanner (idle-inhibit-unstable-v1-client-protocol.h) (reused)
      │  ├─ run wayland-scanner (idle-inhibit-unstable-v1-client-protocol-code.h) (reused)
      │  ├─ WriteFile raygui.c success
      │  └─ WriteFile raygui.c (reused)
      └─ WriteFile raylib.h success
error: the following build command failed with exit code 1:
/home/raff/raylib-zig/.zig-cache/o/22c05e016f3d18beb97453d4d089793a/build /nix/store/5yk32f31879lfsnyv0yhl0af0v2dz9dz-zig-0.13.0/bin/zig /home/raff/raylib-zig /home/raff/raylib-zig/.zig-cache /home/raff/.cache/zig --seed 0x5ac3da82 -Zb3f34190acabd553 basic_window -Dlinux_display_backend=Wayland --verbose --summary all --debug-pkg-config

**Comment by BratishkaErik** [comment]
Can you retry with `-Dshared -Dlinux_display_backend=Wayland` too? And show result of `ldd /home/raff/raylib-zig/.zig-cache/o/60fb6baad1fd895fa3a4fcf9a347f2ed/basic_window` and `ldd [new binary]`

**Comment by Raff727** [comment]
the output of ldd /home/raff/raylib-zig/.zig-cache/o/60fb6baad1fd895fa3a4fcf9a347f2ed/basic_window is:
	linux-vdso.so.1 (0x00007fba47b8e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fba47a8b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fba47895000)
	/nix/store/0wydilnf1c9vznywsvxqnaing4wraaxp-glibc-2.39-52/lib/ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2 (0x00007fba47b90000)

and that /nix/store/... stuff got me thinking if it's causing problems having zig installed via nix. I originally did this because zig wasn't available on apt for some reason and nix seemed like it had a nice up-to-date version of zig and some other things. Turns out you don't try and mix package managers, at least not for compilers like zig. I feel so stupid and sorry for wasting your time. I installed zig via zigup now and everything worked perfectly fine.

lld output of final working basic_window
	linux-vdso.so.1 (0x00007f4a04a58000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4a04955000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4a0475f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4a04a5a000)
