### ISSUE TITLE
Rename "Debug" to "Development"

### ISSUE THREAD

**Issue by hryx** [ziglang/zig#2210]
The existing build modes are Debug, ReleaseFast, ReleaseSafe, and ReleaseSmall. The default is Debug. This is a good default because `unreachable`s and array bounds violations will alert developers reliably. But I think the word "debug" does not accurately describe this mode.

_Debugging_ is a special process you go through to find the source of a problem; it's something you hope you don't have to do, and only happens when something is wrong. The name of the entire, normal process up to the point of releasing is _development_.

I think we should rename _Debug_ mode to _Development_ (or _Develop_) to better reflect its usage and role in the software lifecycle and to avoid a negative connotation. Thoughts?

:thinking: <(hmmm)

**Comment by andrewrk** [comment]
Related: #978

**Comment by andrewrk** [comment]
One thing to consider is, say, if your main build mode is ReleaseFast, and then you want to troubleshoot a problem in one particular area so you use `@optimizeFor(.Development)`. It would be slightly weird to ship that to production, even though that's exactly what you want to do.

**Comment by andrewrk** [comment]
I don't have a terribly strong opinion on this, but I'm going to close it in favor of status quo. I think Debug and Development mean roughly the same thing in this context. I do like that when switching from Debug to Release, there is an implication that you fixed all the bugs. Which makes you think, when selecting:
 * ReleaseSafe
 * ReleaseSmall
 * ReleaseFast
With this implication that "Release" means you fixed the bugs, if you're not so sure the bugs are fixed, then you'll be more inclined to pick "Safe".
