### ISSUE TITLE
change --enable-pic and --disable-pic to -fPIC and -fno-PIC respectively

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2213]
Zig's Position Independent Code command line options correspond exactly to these other C compiler command line options. No sense in deviating.

In general, if there is a command line option that directly corresponds to a C compiler command line option, Zig should use the same syntax.

**Comment by corona10** [comment]
@andrewrk 

Hi Andrew, this issue looks good first issue for the first-contributor. Can I work on this issue?

**Comment by andrewrk** [comment]
Hi @corona10, go for it!
