### ISSUE TITLE
Slow `zig` CLI on macOS

### ISSUE THREAD

**Issue by mdwint** [ziglang/zig#22133]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

The `zig` CLI is slow to start on my machine. It's bad enough that I wonder if something is wrong with my environment.

Do you have any tips on how to debug this? I'm new to Zig so I'm not sure where to start looking.

All commands seem to be affected equally:

```console
$ time zig version
0.13.0

real    0m1.282s
user    0m0.031s
sys     0m0.022s

$ time zig --help
Usage: zig [command] [options]
...

real    0m1.265s
user    0m0.027s
sys     0m0.019s

$ time zig fmt main.zig

real    0m1.323s
user    0m0.032s
sys     0m0.036s
```

This may not seem like a lot, but it's noticeable during edit-compile-run cycles, particularly when my editor runs `zig fmt` every time I save a file.

Most tools I use in other languages (compilers, linters, formatters) feel more responsive. For comparison:

```console
$ time python -c 'print("Hello, world!")'
Hello, world!

real    0m0.396s
user    0m0.021s
sys     0m0.024s

$ time rustc --help
Usage: rustc [OPTIONS] INPUT
...

real    0m0.169s
user    0m0.044s
sys     0m0.020s
```

I downloaded Zig from https://ziglang.org/download/ (macOS aarch64), extracted it to `/opt/zig/` and added that to my `PATH`.

```console
$ which zig
/opt/zig/zig

$ file /opt/zig/zig
/opt/zig/zig: Mach-O 64-bit executable arm64

$ ls /opt/zig/
LICENSE         README.md       doc             lib             zig
```

System specs:
```
System Version: macOS 15.1.1 (24B91)
Chip: Apple M1 Pro
Memory: 32 GB
```

### Expected Behavior

GOTTA GO FAST

**Comment by andrewrk** [comment]
unable to reproduce

**Comment by mdwint** [comment]
This doesn't add much, but just to rule out resource hogging by other processes I tried the Linux version in Docker (on the same macOS host), and that's way faster.

```console
$ docker run -it alpine sh
/ # apk add curl
/ # curl https://ziglang.org/download/0.13.0/zig-linux-aarch64-0.13.0.tar.xz -o zig.tar.xz
/ # tar xf zig.tar.xz
/ # cd zig-linux-aarch64-0.13.0/
/zig-linux-aarch64-0.13.0 # time ./zig version
0.13.0
real    0m 0.03s
user    0m 0.00s
sys     0m 0.02s
```

**Comment by marler8997** [comment]
I've also got an M1 and mine seems to be running much faster, I'm using 0.13.0 downloaded via zigup:

```
% file $(which zig)
file $(which zig)
/Users/marler8997/bin/zig: Mach-O 64-bit executable arm64
marler8997@Jonathans-MacBook-Air vendor % time zig version
time zig version
0.13.0
zig version  0.02s user 0.01s system 90% cpu 0.032 total
marler8997@Jonathans-MacBook-Air vendor % system_profiler SPSoftwareDataType SPHardwareDataType
system_profiler SPSoftwareDataType SPHardwareDataType
Software:

    System Software Overview:

      System Version: macOS 14.7.1 (23H222)
      Kernel Version: Darwin 23.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Jonathan’s MacBook Air
      User Name: Jonathan Marler (marler8997)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 34 days, 20 hours, 21 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Air
      Model Identifier: MacBookAir10,1
      Model Number: Z125000G3FN/A
      Chip: Apple M1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 11881.41.5
      OS Loader Version: 10151.140.19.700.2
      Serial Number (system): C02H204CQ6LT
      Hardware UUID: E2417BA7-4A11-5381-955E-CCFE93576B8C
      Provisioning UDID: 00008103-0006690A2108801E
      Activation Lock Status: Enabled

```

**Comment by mdwint** [comment]
It's dawning on me that _everything_ I run on macOS is slower than it is on Linux in Docker.

Even Python isn't supposed to take 450ms to start, right?

```console
$ time python -c 'print("Hello, world!")'
Hello, world!
real    0m0.452s

$ docker run -it python:3.11-slim sh
# time python -c 'print("Hello, world!")'
Hello, world!
0.02user 0.00system 0:00.03elapsed 100%CPU 
```

Here's my current hypothesis:

This is a work laptop. It has mandatory antivirus on it. Supposedly every process I start gets scanned.
The zig executable is 168 MB. Usually that doesn't matter since it gets memory-mapped, but what if the entire thing gets slurped up by the antivirus before it's allowed to run?

I've asked a coworker to reproduce and he's seeing the same slowdown.

I'll close this issue since the slowness is not exclusive to zig.

**Comment by mdwint** [comment]
Confirmed! I've asked for the antivirus to be disabled and everything's fast again.

Apparently this had been active for 3 weeks already.

Opening a new shell and seeing the prompt appear instantly is _incredible_.

**Comment by alexrp** [comment]
Another one for the ever-growing list of reasons why antivirus software is horrible...
