### ISSUE TITLE
Switch: requires else pong

### ISSUE THREAD

**Issue by Cr0a3** [ziglang/zig#22145]
### Zig Version

0.14.0-dev.2340+182cdf74b

### Steps to Reproduce and Observed Behavior

I have this simple code:
```
pub fn print(self: *const IrNode) void {
        const opcode = switch (self.*) {
            .binary => |binary| switch (binary) {
                .add => "add",
                .sub => "sub",
            },
        };

		....
    }
```

When i compile it i get following error message:
```
lib\ir.zig:71:9: error: else prong required when switching on type '*const ir.IrNode'
        switch (self) {
        ^~~~~~
```

Okay, then i add the else pong:
```
lib\ir.zig:66:18: error: unreachable else prong; all cases already handled
            else => unreachable,
            ~~~~~^~~~~~~~~~~~~~
```

### Expected Behavior

I expected my code to compile

**Comment by Cr0a3** [comment]
**NOTE: it's my first day using zig**
If i'm doing something wrong please let me know

**Comment by kj4tmp** [comment]
Welcome! You may find some friendly helpers in one the zig communities! https://github.com/ziglang/zig/wiki/Community
