### ISSUE TITLE
Please add syntax examples

### ISSUE THREAD

**Issue by TomasHubelbauer** [ziglang/zig#2218]
There is no Zig code on the website nor in the GitHub readme. As someone interested in finding out more about a new programming language, that's the first thing I want to see. It feels like a big omission.

I think it would be suitable to add a code block beneath each bullet point in the features list. That way the code samples are associated with the major features of the language.

**Comment by vegecode** [comment]
https://ziglang.org/documentation/master/

There's a link to documentation at the top next to some other links like "Download", "Community", etc.

**Comment by vegecode** [comment]
Just woke up and think I misunderstood. Are you saying it would be nice to have code examples right there in the feature list in addition to the docs?

**Comment by TomasHubelbauer** [comment]
Thanks for the documentation link! I now see that it is in Documentation > master > Documentation. It should be pretty clear that this is a pretty buried resource, something which should have a lot more spotlight. I would love to see code examples on the home page and in the readme on GitHub and the Releases & Documentation link could be split into two: Releases, Documentation and the documentation one should take the user to the latest docs IMO. But I don't want to tell you how to design your site, I am sure there are multiple equally good designs to surface the docs link, my main point is that after visiting the Zig home page, it would be ideal to have to click zero times to see some syntax :-)

**Comment by haferburg** [comment]
The home page should be specifically targeted to newcomers. It has a "feature list". Call me jaded, but if I read a "feature list" on the home page of a new programming language, I read it as a list of claims and promises. Whether these promises are going to be kept is another matter. Working examples, possibly with links to an online compiler to run them, or at least further documentation, would go a long way towards convincing visitors that they're not just reading empty promises.

**Comment by haferburg** [comment]
Actually, jaded is not the right word. I'm not trying to say that such a feature list is misleading. It's just that if you're designing a new language and writing a compiler for it, there's going to be a lot of loose ends, and for a long time. Every new feature adds new loose ends. That's just the reality of it. The [tier system](https://ziglang.org/download/0.4.0/release-notes.html#Tier-System) is probably a good way of communicating that.

**Comment by andrewrk** [comment]
Good idea, I think you are correct. I'll do an update on the home page.

**Comment by andrewrk** [comment]
https://github.com/ziglang/www.ziglang.org/commit/d41d2a5ccc0639dd5b185631f01e7fd575b0778f

it's live: https://ziglang.org/
