### ISSUE TITLE
stage1 libraries for stage2 should not be part of stage1 install target

### ISSUE THREAD

**Issue by tiehuis** [ziglang/zig#2220]
When installing the stage1 compiler, the libraries that are to be linked as part of the stage2 build are also installed alongside everything. This is an issue when installing stage1 as the end goal (which is the current standard until stage2 is the default compiler) as it adds ~10MiB of unused artifacts. This also doesn't respect the CMAKE_INSTALL_PREFIX so the artifacts end up in the original build directory.

These artifacts probably should not be installed at all and the stage2 build could probably reasonably assume they will sit in the default out of source `build/` directory.

I'm applying this patch now when installing the aur package:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index bda57634..52599838 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -254,7 +254,6 @@ else()
         embedded_lld_wasm
         embedded_lld_lib
     )
-    install(TARGETS embedded_lld_elf embedded_lld_coff embedded_lld_mingw embedded_lld_wasm embedded_lld_lib DESTINATION "${ZIG_CPP_LIB_DIR}")
 endif()
 
 # No patches have been applied to SoftFloat-3e
@@ -775,7 +774,6 @@ if(MSVC OR MINGW)
     target_link_libraries(zig LINK_PUBLIC version)
 endif()
 install(TARGETS zig DESTINATION bin)
-install(TARGETS zig_cpp DESTINATION "${ZIG_CPP_LIB_DIR}")
 
 foreach(file ${ZIG_C_HEADER_FILES})
     get_filename_component(file_dir "${C_HEADERS_DEST}/${file}" DIRECTORY)
```

**Comment by andrewrk** [comment]
Wait, why is this a problem?

```cmake
set(ZIG_CPP_LIB_DIR "${CMAKE_BINARY_DIR}/zig_cpp")
```

ZIG_CPP_LIB_DIR is set to explicitly be in the build dir, not the install prefix. I just tested and when an install prefix is used, the libraries still get output into the build dir, and do not get installed to the install prefix.

How were they getting picked up by the AUR package?

**Comment by tiehuis** [comment]
makepkg installs into a temporary root so anything in the install target ends up in a mirrored location in the package.

**Comment by andrewrk** [comment]
Is the build directory in the temporary root? With `-DCMAKE_INSTALL_PREFIX=$TEMPORARY_ROOT` then the install step will not put these libraries into the temporary root. It will put the libraries into the cmake build directory, which I would expect to not be anywhere in the temporary root.

**Comment by andrewrk** [comment]
Is it perhaps the case that arch linux has patched cmake to have nonstandard behavior with regards to the 'install' command?

**Comment by tiehuis** [comment]
Actually looks like after CMake is invoked, make is run with the [DESTDIR](https://www.gnu.org/prep/standards/html_node/DESTDIR.html). We want to package to a specific directory since this is then tar'd into the resulting package. As a result, the build directory is prefixed and the stage1 artifacts are also placed inside.

We can probably work around this by avoiding DESTDIR and setting the install directory only in CMake.

**Comment by tiehuis** [comment]
@daurnimator 

Would modifying the PKGBUILD to the following work? I'll test later tonight otherwise.

```
    cmake \
        -DCMAKE_BUILD_TYPE=None \
        -DCMAKE_INSTALL_PREFIX="$pkgdir/usr" \
        -DZIG_FORCE_EXTERNAL_LLD=ON \
        ..
```

```
    make -C build install
```

**Comment by tiehuis** [comment]
I've tested the above and it works as expected. I can omit the original patch. I still feel like the install target to the build directory feels wrong, but it works in practice. We need to make a note of this detail when packaging if other systems do something similar with make.

Going to close, let me know if you think the above modifications work for you, @daurnimator.

**Comment by daurnimator** [comment]
Using the install prefix for this is wrong, that is prefixed to things like rpath

**Comment by tiehuis** [comment]
How about we add a cmake option to not install these artifacts if set. This can be configured to off by default?

**Comment by andrewrk** [comment]
I don't think that's a long term solution, because once we're shipping the self-hosted compiler, the build process includes building these libraries, putting them somewhere predictable, building the self-hosted compiler which needs to be able to find the libraries, and then installing the self-hosted compiler.

So if we want to get rid of the cmake install command for these libraries we need to solve the "putting them somewhere predictable" a different way. Maybe that looks like depending on cmake's behavior   and some per-OS logic. I'm OK with that.
