### ISSUE TITLE
std.crypto.pwhash.argon2: `argon2.kdf` accepts the invalid `m` parameter which is less than the minimum value

### ISSUE THREAD

**Issue by sorairolake** [ziglang/zig#22231]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

[RFC 9106](https://datatracker.ietf.org/doc/html/rfc9106#section-3.1) describes the `m` parameter as follows:

> Memory size `m` **MUST** be an integer number of kibibytes from $8 \times p$ to $2^{32} - 1$. The actual number of blocks is `m'`, which is m rounded down to the nearest multiple of $4 \times p$.

In the following example, `argon2.kdf` succeeds because `m` is greater than or equal to $8 \times p$:

```zig
var dk: [32]u8 = undefined;
const password = "passphrase";
const salt = "abcdefgh";
const params = argon2.Params{ .t = 3, .m = 32, .p = 4 };
const mode = argon2.Mode.argon2id;
const result = argon2.kdf(testing.allocator, &dk, password, salt, params, mode);
try testing.expect(!meta.isError(result));
```

In the following example, `argon2.kdf` is expected to return an error because `m` is less than $8 \times p$:

```zig
var dk: [32]u8 = undefined;
const password = "passphrase";
const salt = "abcdefgh";
const params = argon2.Params{ .t = 3, .m = 31, .p = 4 };
const mode = argon2.Mode.argon2id;
const result = argon2.kdf(testing.allocator, &dk, password, salt, params, mode);
try testing.expect(meta.isError(result));
```

But `argon2.kdf` actually succeeds, so this test fails.

### Expected Behavior

Returns an error if the `m` parameter is less than $8 \times p$.

**Comment by sorairolake** [comment]
cc @jedisct1

**Comment by jedisct1** [comment]
We should also probably note that anything < 8192 can be rejected by other implementations.

**Comment by jedisct1** [comment]
BTW, avoid ChaChaPoly with keys derived from low-entropy material, such as passwords, as it is vulnerable to [partitioning oracle attacks](https://eprint.iacr.org/2020/1491.pdf).
