### ISSUE TITLE
Accessing type decls from pointer types

### ISSUE THREAD

**Issue by RetroDev256** [ziglang/zig#22249]
### Zig Version

0.14.0-dev.2443+3f7b3daaa

### Steps to Reproduce and Observed Behavior

I ran into this just today - I have a set of functions that take anytype parameters. I then use `@TypeOf` on those parameters and pass them to a function to determine a function result type. The problem is that `@Typeof(the anytype parameter)` is somehow a pointer type, even though I never passed a pointer anywhere in this program, nor referenced anything.

```
src/main.zig:124:30: error: type '*const main.Ranged(1,2)' has no members
            return Ranged(Lhs.from() + Rhs.from(), Lhs.to() + Rhs.to());
```

### Expected Behavior

I expected this code to work as-is. I expect that the type `*const main.Ranged(1, 2)` should allow me to access functions and declarations, the same way as if this were not a type of a pointer to a variable. There may also be something further to say about how I got an unexpected pointer (when I passed none), but I consider that a different issue (and I think it is already covered).

If this change were to be made (such that I can access `from()` and `to()` directly from the type `Lhs` (which is apparently `*const main.Ranged(1,2)`)), would it break any existing code? Not to my knowledge, but I do know for sure that it would help my current situation.

**Comment by mlugg** [comment]
* Incomplete steps to reproduce.
* This seems to be a language proposal rather than a bug report; [do not file language proposals.](https://github.com/ziglang/zig/wiki/Language-Proposals)
