### ISSUE TITLE
switching on error unions.

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2228]
related to #1302

I found myself generalizing errors in my recent utf-8 patch

```
-    const end_index = start_index + try std.unicode.utf8ToUtf16Le(result[start_index..], s);
+    const end_index = start_index + std.unicode.utf8ToUtf16Le(result[start_index..], s) catch return error.InvalidUtf8;
```
I did this instead of a doing an error union with `std.unicode.Utf8Error` (which itsself inherits from `std.unicode.UnicodeError`), because I don't want users to have to handle each of these seperately in switch statements.

**Comment by andrewrk** [comment]
issue not detailed and clear enough
