### ISSUE TITLE
Unused `@import` from source file only checks file syntax, leaving everything else unchecked

### ISSUE THREAD

**Issue by ThatDreche** [ziglang/zig#22292]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

In a blank project (just created using `zig init`), add another file (e.g. `src/module.zig`) containing anything with valid syntax but which should not compile at all (like `const a: usize = "Something";` or a comptime invoking unreachable or similar).

Optionally, for checking, one may also add an exported function and a test which will fail when run.

Import this into `root.zig` using `pub const mod = @import("module.zig");` and it will compile. The output library will not contain the symbol for the exported function.

### Expected Behavior

The compilation should fail.

(And, while I accept there may be practical use to save time in not compiling that file, there should be an option for letting at least the tests run. But I think it is confusing enough that the exported function is not output in such files)

A current workaround is to include in `root.zig` a comptime block discarding a value taken from such a module (like `comptime { _ = module.func; }`).

**Comment by andrewrk** [comment]
working as designed

**Comment by ThatDreche** [comment]
Is this documented somewhere? I could find it neither in the language reference (like under `@import`) nor in the build system documentation, and I wouldn't expect it in the standard library documentation.

**Comment by mlugg** [comment]
The documentation for lazy analysis is currently missing; there's a TODO to add it to the langref [here](https://ziglang.org/documentation/master/#toc-Root-Source-File).
