### ISSUE TITLE
@intCast can't inferr result type when accessing .len

### ISSUE THREAD

**Issue by Niggi1105** [ziglang/zig#22298]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

The following does not compile and throws an error that @intCast must have a known result type.

```
const std = @import("std");
const Allocator = std.mem.Allocator;
const gpa = std.heap.GeneralPurposeAllocator(.{}){};

pub fn main()!void {
    const alloc = gpa.allocator();
    const slice = try alloc.alloc(u8,20);
    const offset: u32 = 10;
    std.debug.assert(slice.len == @intCast(offset+10));
}
```
but this compiles
```
const std = @import("std");

pub fn main()!void {
    const offset: u32 = 10;
    const a: usize = 10;
    std.debug.assert(a == @intCast(offset+10));
}
```

the easy fix is to use @as(usize, offset+10) instead, but in this case @intCast should be able to inferr it.

### Expected Behavior

the code should compile, because the result type can be inferred.

**Comment by mlugg** [comment]
> but this compiles

No it doesn't.

---

Working as intended: the RHS of `==` does not receive a result type because it does *not* have to match the LHS type (for instance, `my_union == .foo` would be invalid if the RHS received a result type matching the LHS type). When checking for integer equality, just don't cast anything; it's unnecessary, any two integer types can be compared.

**Comment by Niggi1105** [comment]
it does compile, just had a typo

**Comment by mlugg** [comment]
It does not compile.

```sh-session
[mlugg@nebula test]$ cat foo.zig
const std = @import("std");

pub fn main()!void {
    const offset: u32 = 10;
    const a: usize = 20;
    std.debug.assert(a == @intCast(offset+10));
}
[mlugg@nebula test]$ zig run foo.zig
foo.zig:6:27: error: @intCast must have a known result type
    std.debug.assert(a == @intCast(offset+10));
                          ^~~~~~~~~~~~~~~~~~~
foo.zig:6:27: note: use @as to provide explicit result type
[mlugg@nebula test]$ zig13 run foo.zig
foo.zig:6:27: error: @intCast must have a known result type
    std.debug.assert(a == @intCast(offset+10));
                          ^~~~~~~~~~~~~~~~~~~
foo.zig:6:27: note: use @as to provide explicit result type
[mlugg@nebula test]$
```

If this code compiles for you, that is a bug; please open an issue with a detailed reproduction (exact command, OS, etc).

**Comment by Niggi1105** [comment]
sorry to bother you again, but how did you get that clean terminal output into github?
