### ISSUE TITLE
Proposal: allow (`break`-able) labels on `if` (and `if`-`else`) expressions

### ISSUE THREAD

**Issue by rohlem** [ziglang/zig#22290]
Writing code, I noticed how with labeled `switch`
I can now replace `x = x: {break :x switch (...) {...};};`
with the shorter `x = x: switch (...) {...};`.

I think `if` / `if`-`else` expressions would benefit from the same:

```zig
comptime {
    // status-quo: label every block (or highest label-able expression) within an if-else expression
    const x0 = if (true) x: {
        // ...
        break :x {};
    } else if (true) x: switch(void) {
        // ...
        else => break :x {};
    } else x: {
        // ...
        break :x {};
    };
    // status-quo alternative: introduce explicit block just for a label, to reduce inner labels
    const x1 = x: {
        if (true) {
            // ...
            break :x {};
        } else if (true) switch(void) {
            // ...
            else => break :x {};
        } else {
            // ...
            break :x {};
        };
    };
    // proposed: label the if-else expression directly
    const x2 = x: if (true) {
        // ...
        break :x {};
    } else if (true) switch(void) {
        // ...
        else => break :x {};
    } else {
        // ...
        break :x {};
    };
}
```

This example is fairly minimized.
In real code, longer identifiers, more complex expressions (in conditions etc.), and longer blocks
make keeping track of labels and tracing them back to the destination more difficult.
In my general experience, the more you can share labels to a common destination, the less cluttered and more readable code becomes.

For regularity, we could even allow labels on arbitrary expressions,
however, while it may reduce typing, for now I haven't come up with an example besides `if`(-`else`) that ends up as more readable that way.
So while I think it would be logical, I'm not too vehemently for that generalization.

**Comment by andrewrk** [comment]
No proposals please
