### ISSUE TITLE
erroneous dependency loop for globals self/mutually referencing the addresses of fields

### ISSUE THREAD

**Issue by Fri3dNstuff** [ziglang/zig#22314]
### Zig Version

0.14.0-dev.2563+af5e73172

### Steps to Reproduce and Observed Behavior

run `zig test` on the following code:
```zig
test {
    _ = s;
}

const S = struct { x: *const u64, y: u64 };
const s: S = .{ .x = &s.y, .y = 0 };
```
compiler outputs:
```
$ zig test oops.zig 
oops.zig:6:1: error: dependency loop detected
const s: S = .{ .x = &s.y, .y = 0 };
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected Behavior

The code should compile and run without errors;
although #22303 resolved #131, the compiler still seemingly fails for more complex place expressions.

**Comment by mlugg** [comment]
Oh, sorry, I must have missed this the other day: your version is just one commit too old. This works fine on master.
