### ISSUE TITLE
compilation compile error traces don't print with an absolute path

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#22327]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

```
$ git clone https://github.com/nektro/monorepo-test
$ cd monorepo-test
$ ./cdand.sh zig build test --summary all
## this works as expected with no error
```

`cdand.sh` exists in the root and allows us to execute commands in a folder and will be instrumental in the experience going further

```sh
#!/bin/sh
cd foo
echo $@
$@
```

now let's try introducing a compile error and runtime panic in `build.zig`

```
[meghan@nixos:~/dev/test]$ ./cdand.sh zig build --summary all
zig build --summary all
/home/meghan/dev/test/foo/build.zig:15:9: error: unused local variable
    var foo: u32 = 5;
        ^~~
```

```
[meghan@nixos:~/dev/test]$ ./cdand.sh zig build --summary all
zig build --summary all
thread 21055 panic: oops
/home/meghan/dev/test/foo/build.zig:15:15: 0x110926c in build (build)
    if (true) @panic("oops");
              ^
```

this is perfect so far. an absolute path allows us to ctrl+click on it and open the file in our editor to quickly fix the issue.
app code otoh is a different story; let's try a compile error and runtime panic in foo

```
[meghan@nixos:~/dev/test]$ ./cdand.sh zig build run
zig build run
install
└─ install foo
   └─ zig build-exe foo Debug native 1 errors
src/main.zig:14:9: error: unused local variable
    var foo: u32 = 5;
        ^~~
error: the following command failed with 1 compilation errors:
```

```
[meghan@nixos:~/dev/test]$ ./cdand.sh zig build run
zig build run
All your codebase are belong to us.
Run `zig build test` to run the tests.
thread 21648 panic: oops
/home/meghan/dev/test/foo/src/main.zig:14:5: 0x103584f in main (foo)
    @panic("oops");
    ^
```

### Expected Behavior

```
[meghan@nixos:~/dev/test]$ ./cdand.sh zig build run
zig build run
install
└─ install foo
   └─ zig build-exe foo Debug native 1 errors
/home/meghan/dev/test/foo/src/main.zig:14:9: error: unused local variable
    var foo: u32 = 5;
        ^~~
error: the following command failed with 1 compilation errors:
```

termina context is in `/home/meghan/dev/test`
script execution is in `/home/meghan/dev/test/foo` since it `cd`s
having an absolute path here would enable clicking on the path and opening the file from anywhere

**Comment by mlugg** [comment]
I find the problem statement here to be dubious: it seems completely reasonable to me that the printed file path in a compile error should be relative to the cwd in cases like this. Your issue here seems to come purely from the fact that you're wrapping your build process in a shell script for no reason.

**Comment by andrewrk** [comment]
Working as designed.

**Comment by nektro** [comment]
> it seems completely reasonable to me that the printed file path in a compile error should be relative to the cwd in cases like this.

i raised the issue because the behavior of whether the compile error happens in build.zig or a subcompilation is not consistent

> Your issue here seems to come purely from the fact that you're wrapping your build process in a shell script for no reason.

this is a bit condescending imo. it's natural that once tooling reaches a level of stability so as to be dependable, that new things are built on top of it. in the event this isn't resolved, do you have a recommendation on what i should do instead?

**Comment by nektro** [comment]
i don't suspect many people beyond myself to need this but wanted to give an update for posterity since i managed to not need this change but still get the workflow i was after

https://github.com/nektro/ziginfra/commit/532e49e98d30c0fe33fd80a740225243416d8085
