### ISSUE TITLE
Inconsistent compiler behaviour with incorrect import statements.

### ISSUE THREAD

**Issue by JimTwn** [ziglang/zig#22330]
### Zig Version

0.14.0-dev.2293+6d781e095

### Steps to Reproduce and Observed Behavior

Create a new zig project:
```
$ mkdir test
$ cd test
$ zig init
info: created build.zig
info: created build.zig.zon
info: created src\main.zig
info: created src\root.zig
info: see `zig build --help` for a menu of options
```

Replace `src/main.zig` with the following:

```zig
const std = @import("std");
const foo = std.idontexist;  // This really does not exist.

test {
    std.testing.refAllDecls(@This());
}

pub fn main() void {
    std.debug.print("Hello, World!\n", .{});
}
```

Run the program:

```
$ zig build run
Hello, World!
```

Run the tests:

```
$ zig build test
<no output>
```

### Expected Behavior

I would expect both the `run` and `test` commands to fail with a compiler error. Both run to completion without problems.

If we replace:

* `const foo = std.idontexist;` with 
* `const foo = @import("idontexist.zig");`

and run the commands again, the following error is thrown in both cases:

```
src\main.zig:2:21: error: unable to load 'src/idontexist.zig': FileNotFound
const foo = @import("idontexist.zig"); // compile error
                    ^~~~~~~~~~~~~~~~
```

**Comment by mlugg** [comment]
Working as intended. Imported files are resolved eagerly; namespace accesses are subject to lazy analysis.
