### ISSUE TITLE
How can i build zig with just one target?

### ISSUE THREAD

**Issue by adcdam** [ziglang/zig#22336]
### Zig Version

0.14.0-dev.2571+01081cc8e

### Steps to Reproduce and Observed Behavior

i get this when trying to build with cmake 
CMake Error at cmake/Findllvm.cmake:30 (message):
  LLVM (according to /usr/bin/llvm-config) is missing target AArch64.  Zig
  requires LLVM to be built with all default targets enabled.

  LLVM (according to /usr/X11R6/bin/llvm-config) is missing target AArch64.
  Zig requires LLVM to be built with all default targets enabled.
Call Stack (most recent call first):
  CMakeLists.txt:135 (find_package)

### Expected Behavior

i only need to build for x86_64

**Comment by andrewrk** [comment]
unsupported use case
