### ISSUE TITLE
Allow passing a LazyPath to a build option

### ISSUE THREAD

**Issue by Snektron** [ziglang/zig#22347]
In vulkan-zig, users are expected to pass the registry for the bindings they want to generate with via a build parameter:
```zig
const vulkan = b.dependency("vulkan_zig", .{
    .registry = @as([]const u8, b.pathFromRoot("path/to/vk.xml")),
}).module("vulkan-zig");
exe.root_module.addImport("vulkan", vulkan);
```
However, this only works if `vk.xml` is _vendored_. I would prefer to pass a `vk.xml` obtained by adding the Vulkan-Headers repository to my dependencies, and then passing the file directly from there:
```zig
const registry = b.dependency("vulkan_headers", .{}).path("registry/vk.xml");
const vulkan = b.dependency("vulkan_zig", .{
    .registry = registry,
}).module("vulkan-zig");
exe.root_module.addImport("vulkan", vulkan);
```
This, however, does not work: `b.dependency(...).path()` returns a LazyPath, and build options only accept an absolute path!

There are currently ways to work around this, in my case by exposing the generator executable to the user directly. It would be nicer, though, if the above example could be made to work. I don't really know how this works internally, but one observation is that the `b.option()` in vulkan-zig currently accepts a simple `[]const u8` for the path. I would suggest that if this were to be implemented, users would simply have to write `b.option(LazyPath, "option", "help")` instead.

**Comment by castholm** [comment]
Support for `b.option(std.Build.LazyPath, "name", "description")` was already recently added to master in #21380

**Comment by Snektron** [comment]
Seems like it was added for this exact purpose too! Excellent, thanks for pointing that out to me ;) Let me just double check that it works...

**Comment by Snektron** [comment]
https://github.com/Snektron/vulkan-zig/commit/bb470f16dabd8195155ba9e3714dc62d7ad69add it works!
