### ISSUE TITLE
outdated/incorrect documentation for @truncate

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2234]
https://ziglang.org/documentation/master/#truncate says that `i8(my_c_longlong)`
> produces a crash in Debug mode and Undefined Behavior in ReleaseFast mode 

instead I get:

```
error: expected type 'i8', found 'c_longlong'
            return i8(result);
                     ^
```

**Comment by shawnl** [comment]
should these type of casts only allow implicit casts?  Do we need `@intCast` (and `@bitCast`). I like it the way things are, but the docs should be clarified to whatever is chosen.
