### ISSUE TITLE
File name output in zig AIR metadata dump

### ISSUE THREAD

**Issue by ityonemo** [ziglang/zig#22355]
### Zig Version

0.14.0-dev.2416+a221b2fbf

### Steps to Reproduce and Observed Output

perform a debug build of zig, then `zig run` any file.

Functions appear like so:

```
# Begin Function AIR: stack_ptr_escape.escaped_ptr:
# Total AIR+Liveness bytes: 487B
# AIR Instructions:         19 (171B)
# AIR Extra Data:           36 (144B)
# Liveness tomb_bits:       16B
# Liveness Extra Data:      7 (28B)
# Liveness special table:   3 (24B)
  %0!= dbg_stmt(2:3)
  %1 = alloc(*u32)
 ...
# End Function AIR: stack_ptr_escape.escaped_ptr
```

### Expected Output

If possible, it would be awesome to have "filename/lineno" metadata, for example like so:

```
# Begin Function AIR: stack_ptr_escape.escaped_ptr
# AIR Source: /path/to/stack_ptr_escape.zig:0
```

Anything consuming AIR (I know, I know, we're not supposed to really at this point) can then trace back `dbg_stmt(...)` directives.

- If those data are easily obtained, then it should be trivial to get them in there
- If those data are not easily obtained, it is a good forcing function to make those data available so that if something should want to consume AIR in the future they can have it.

Context:

I'm working on statically analyzing AIR to detect stack escapes, UAF, DF, data races, undefined escape, etc.

**Comment by mlugg** [comment]
AIR should not be consumed by any external tooling: it is an internal data format for use by the compiler only. `--verbose-air` in particular should not be used programmatically, because it is incomplete: printed comptime-known values may be truncated or not include important information.

**Comment by ityonemo** [comment]
Well, that sucks.
