### ISSUE TITLE
Error return traces don't have information when linking against libc

### ISSUE THREAD

**Issue by heidezomp** [ziglang/zig#2243]
Hi, I am trying out Zig. It's exciting! :smile: 

When playing around I found that error return traces don't work correctly when linking against libc. Normally they work fine:
```
heidezomp@raggel ~/C/foo> cat foo.zig
pub fn main() !void {
    return error.Foo;
}
heidezomp@raggel ~/C/foo> zig build-exe foo.zig
heidezomp@raggel ~/C/foo> ./foo
error: Foo
/home/heidezomp/Code/foo/foo.zig:2:5: 0x225989 in ??? (foo)
    return error.Foo;
    ^
```
But when I link against libc (which isn't useful in this example, but I'm trying to experiment with game stuff using SDL2, so linking against libc is required for my use case), all useful information disappears from the trace:
```
heidezomp@raggel ~/C/foo> zig build-exe --library c foo.zig
heidezomp@raggel ~/C/foo> ./foo
error: Foo
???:?:?: 0x227c89 in ??? (foo)


```
I am running on Arch Linux, using Zig 0.4.0 from the precompiled Linux binary.

**Comment by andrewrk** [comment]
This is probably a deficiency in `std/debug.zig`, in the ELF/DWARF code. With some improvements, this would fix this issue and in general make stack traces and error return traces work better when optimizations are on, or when object files are produced from third party sources.

**Comment by andrewrk** [comment]
I believe this was fixed by @LemonBoy

**Comment by heidezomp** [comment]
Works for me as well, this is going to make my error debugging experience so much better! Thank you so much @LemonBoy! :heart:
