### ISSUE TITLE
Use a better non-cryptographic hash function for the HashMap implementation

### ISSUE THREAD

**Issue by Sahnvour** [ziglang/zig#2244]
Current implementation is a simple xor with a constant. Very fast, but not very good quality.

There's been a lot of research recently on this topic, and this could be the occasion to go for state of the art hash functions.

I think a good starting point to choose the function we want is [this fork of smhasher](https://github.com/rurban/smhasher).

**Comment by ManDeJan** [comment]
I coincidentally made a Zig implementation of wyhash yesterday https://github.com/ManDeJan/zig-wyhash
according to that fork of smhasher it is the fastest non-cryptographic hash function without qualiy issues. I'm still learning Zig and my code could probably be improved but I think wyhash in general could be a good choice for a hashmap.

**Comment by AlexKotik** [comment]
What do you think of Jenkins hash function and FNV1/FNV1-a? Both of them are pretty performant.

https://en.m.wikipedia.org/wiki/Jenkins_hash_function
https://en.m.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function

**Comment by Sahnvour** [comment]
Those were pretty good back then, but time has passed since they were published and a lot of other hash functions and tests were created, giving better insights. The smhasher fork I mention in my first comment contains results for FNV1a and Jenkins hashes, and both fail many tests (with the exception of Perl's Jenkins version being a bit better).
They also are both pretty slow by nowadays' standards. The repository's readme has a table comparing speed and defects of many hashes.

I think wyhash is a very good candidate:
- it passes all smhasher tests, indicating pretty good quality (the author claims that the PRNG variant also passes BigCrush and PractRand which is good)
- it is the fastest hash function for small keys but is also really fast for large ones, meaning that we would not need to change the hash we choose based on input size
- it is portable
