### ISSUE TITLE
export nakedcc noreturn error

### ISSUE THREAD

**Issue by skyfex** [ziglang/zig#2245]
When trying to use `export nakedcc fn _start() noreturn { .. }` I get the following error:
```
hello.zig:12:37: error: expected type 'noreturn', found 'void'
export nakedcc fn _start() noreturn {
                                    ^
hello.zig:12:28: note: return type declared here
export nakedcc fn _start() noreturn {
```

Using void instead of noreturn avoids the error. Tested with 0.4.0 and zig-0.4.0+aff2e478

**Comment by vegecode** [comment]
What's inside of the braces? I had an asm function that tail called something else, so my function had the same signature as yours. I had to add `unreachable` after my tail calling block as that has a 'noreturn' type.

**Comment by vegecode** [comment]
https://ziglang.org/documentation/master/#noreturn

**Comment by emekoi** [comment]
that probably means that your function actually returns. putting `while (true) {}` or something similar should fix it.

**Comment by andrewrk** [comment]
>  I had to add `unreachable` after my tail calling block as that has a 'noreturn' type.

That's a bug, but the workaround is correct. `unreachable` tells zig control flow can never get there.

It's usually necessary after inline assembly because as far as zig is concerned inline assembly is a black box.

**Comment by skyfex** [comment]
`while (true) {}`  is reasonable for `_start` but I also have a nakedcc that I want to resolve to a single assembly instruction. But in that case `unreachable` is an acceptable workaround. I'm not so sure Zig should try to analyse asm blocks, so I'm not sure I'd consider it a bug. When I think about it this all makes sense.

Documentation can be a bit confusing, as it's not very explicit about what you need to end the function with for the function to be `noreturn`, or that the compiler actually does some analysis to verify it. Error message could also be better, maybe pointing to the last line of the function body in the first message would have clued me in.

**Comment by vegecode** [comment]
With some more information, maybe I can help you come up with a solution or understand the use case. 

Why is it being exported and what is the instruction you're looking for?

**Comment by skyfex** [comment]
So the usecase (not sure if this is the right approach though) is to define interrupt handlers in Zig, rather than in an external assembly file.

Something like this:
```export nakedcc fn isr_reset() linksection(".isr_handlers") noreturn {
  asm volatile ("B _start");
}```

**Comment by skyfex** [comment]
I was thinking about creating a seperate issue for this, but I can mention that I was thinking it would be nice if there was a function attribute which constrained the function to be located at a specific address. It doesn't necessarily have to be responsible for locating the function at that address when linking. That can be done in the linker script. But if it could be used to verify the symbol address after linking that would be great. It also helps with documentation for the reader.

**Comment by vegecode** [comment]
https://github.com/vegecode/msp432-tiva-zig

This is functioning on hardware right now for an example of how I did it. I'm at work, but I think I exported the table of vectors. I know I have some stuff locally, but I think it will still compile using Zig master branch.

**Comment by vegecode** [comment]
Important note, I haven't done more yet, because of the issue where unused builtins are being included, thus causing errors about missing compiler-rt functions. I have been adding those functions to Zig. They are only used in release fast and release safe mode. 

It will build and run fine in release small, right now.

**Comment by vegecode** [comment]
I can double check on it during lunch to make sure it still functions.

**Comment by vegecode** [comment]
Should I keep responding in this thread? After thinking some more, I realize you must be targeting a non-M profile arm chip. The extra instruction, if it's a branch to panic because of the unreachable statement, can be omitted I think if you put:

```zig
@setRuntimeSafety(false);
```
 at the top of your function.  Or you can build in a different release mode, (like release-small)

**Comment by skyfex** [comment]
@vegecode I realise now that I've been mixing up architectures, so the exact example doesn't make much sense. This is more of a feedback to Zig based on me playing around. More of a feedback-issue than a support-issue.

@setRuntimeSafety works. I think that's an acceptable solution if you want a single-instruction nakedcc function with noreturn

Thanks for the example, looks like the perfect solution for ARM

So in my opinion, it would be nice if this issue is used to follow up on improving documentation and/or error messages, but I don't mind if it's closed as it is either.

**Comment by vegecode** [comment]
Really a built-in calling convention for interrupts would be ideal, but that is a lot of work that I don't know how to do yet. The compiler is a type of beast I'm not used to working on. Good luck with your project.

**Comment by timonkruiper** [comment]
@skyfex For the use case you were showing this can be solved with the following zig and linker code:

Zig:
```
export const RESET_VECTOR linksection(".vector_table.reset_vector") = _start;

export nakedcc fn _start() noreturn {
    while(true) {}
}
```

Linker script:
```
MEMORY {
  FLASH (rx)      : ORIGIN = 0x08000000, LENGTH = 512K
  RAM (xrw)       : ORIGIN = 0x20000000, LENGTH = 128K
}

ENTRY(_start);

EXTERN(RESET_VECTOR);

SECTIONS {
	.vector_table ORIGIN(FLASH) : ALIGN(4) {
		LONG(ORIGIN(RAM) + LENGTH(RAM)); //

		KEEP(*(.vector_table.reset_vector));
	} > FLASH

	.text : {
	 	*(.text .text.*); 
	} > FLASH

etc....
```

**Comment by andrewrk** [comment]
Fixed in master branch:

```zig
export fn _start() callconv(.Naked) noreturn {
    unreachable;
}
```

```
$ ./zig build-obj test.zig 
$
```
