### ISSUE TITLE
Add std.ArrayList.sort

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2246]
Add a `ArrayList.sort` method that wraps `std.sort`

**Comment by andrewrk** [comment]
I think this might be worth thinking about first -

There's a balance between convenience and API bloat, and we need to be careful not to go to far in the latter direction.

`ArrayList.toSlice()` is public API and can easily be passed to `std.sort.sort`. Is it really necessary to add a method to ArrayList?

**Comment by daurnimator** [comment]
Ah I didn't connect the dots of using `.toSlice()` with `std.sort`. Happy to close.

**Comment by andrewrk** [comment]
Maybe we can make a note of this in the doc comments of both the toSlice function and the sort function, to try to make it more discoverable.

**Comment by mathieu-suen-sonarsource** [comment]
Now with late version I found using the toOwnSlice a bit more tricky to use.

```zig
        const alloc = self.array.allocator;
        const slice = try self.array.toOwnedSlice();
        std.mem.sort(u32, slice, {}, std.sort.asc(u32));
        self.array.deinit();
        self.array = std.ArrayList(u32).fromOwnedSlice(alloc, slice);
```

**Comment by ianprime0509** [comment]
@mathieu-suen-sonarsource you don't need to use `toOwnedSlice` for this use-case. The replacement of `toSlice` mentioned in this issue is just to use the `items` field of the array list directly (see #4000):

```zig
std.mem.sort(u32, self.array.items, {}, std.sort.asc(u32));
```
