### ISSUE TITLE
Add std.ArrayList.remove

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2247]
There should be a function `std.ArrayList.remove` that moves fields down to fill the empty space.

It may be useful to add a backwards iterator at the same time.

**Comment by andrewrk** [comment]
Hmm. That's not really advisable for a lot of use cases. It would at least have to have an awkward sounding name.

**Comment by daurnimator** [comment]
To be more specific, I need to filter an ArrayList to remove some values. In my case, I already know the indexes of the items to be removed.

We currently only have `ArrayList.swapRemove`, however I need to retain order.

**Comment by Tetralux** [comment]
Maybe `orderedRemove` or `orderedRemoveSlow`.
In Jai, this is called `array_ordered_remove` IIRC.

If you were gonna add `remove` though, I'd default it to `swapRemove`, for speed, personally.

Maybe that means that I wouldn't add it and just have `swapRemove` and `orderedRemove`.

**Comment by andrewrk** [comment]
I like `orderedRemove`.
