### ISSUE TITLE
Assertion `g->errors.length > 0' failed (in `analyze_fn_ir`)

### ISSUE THREAD

**Issue by dbandstra** [ziglang/zig#2261]
Something in the last week broke my game project.

I now get this error when compiling:
```
/home/dbandstra/oxid/src/common/gbe/gbe_main.zig:78:24: error: evaluation exceeded 1000 backwards branches
        if (std.mem.eql(u8, sfield.name, @typeName(T))) {
                       ^
```

If I put `@setEvalBranchQuota(10000);` at the top of the `getCapacity` function in `gbe_main.zig` ([here](https://github.com/dbandstra/oxid/blob/5670f17221b5161b2fc2b71dbb053c0169c62f35/src/common/gbe/gbe_main.zig#L76)), I get this:

```
zig: /home/dbandstra/zig/src/analyze.cpp:3648: void analyze_fn_ir(CodeGen*, ZigFn*, AstNode*): Assertion `g->errors.length > 0' failed.
```

This is the current latest commit in my project: https://github.com/dbandstra/oxid/tree/5670f17221b5161b2fc2b71dbb053c0169c62f35

**Comment by dbandstra** [comment]
I did a manual binary search and identified this as the commit that broke it: 627b52fe654a7506861d3cbefb705803bd0c5102

**Comment by andrewrk** [comment]
Thanks for doing the bisect. I'm looking into this now.

**Comment by andrewrk** [comment]
Sorry for the trouble. I tested Oxid after this fix but I did not get a high score
