### ISSUE TITLE
Clearly identify tests as such in debug info

### ISSUE THREAD

**Issue by Sahnvour** [ziglang/zig#2267]
```zig
test "this is a test" {
    unreachable;
}
```
```
test.zig:2:5: 0x7ff76d9e152a in this is a test (test.obj)
    unreachable;
```

I think it would be better to instead output:
```
test.zig:2:5: 0x7ff76d9e152a in test "this is a test" (test.obj)
    unreachable;
```
so that there is no risk of confusing between tests and possibly similarly named functions in the debug traces.

**Comment by andrewrk** [comment]
Zig is using the test name as the function symbol name. So this is as simple as prepending `test "` and appending `"`.
