### ISSUE TITLE
Mistakes in docs about mod&rem (+questions)

### ISSUE THREAD

**Issue by Rocknest** [ziglang/zig#2271]
`@mod` and `@rem` sections in the documentation mention these identities:
```zig
@divFloor(a, b) + @mod(a, b) == a
@divTrunc(a, b) + @rem(a, b) == a
```
However these are false, but they are true when the first term is multiplied by `b`.

Questions:

- why these operations do not allow negative denominator?
- in math _modulo_ operation is defined simply as _remainder_ of the division, so why in Zig there are two functions that only differ in behaviour when numerator is negative?

**Comment by mesbahamin** [comment]
There are multiple valid definitions of an operation that gets the remainder of an integer division: `x / y`. Such an operation must satisfy this equation:

    x == (quotient * y) + remainder

The value computed for `remainder` will differ (when `x` or `y` is negative) based on the method of computing `quotient`.

C's `%` operator is based on _truncated_ integer division. This operation is often called 'rem' in other languages.

Python's `%` operator is based on _floored_ integer division. This operation is often called 'mod' in other languages.

If you want to implement 'mod' in C, you can do:

```c
int32_t mod(int32_t x, int32_t y) {
    return ((x % y) + y) % y;
}
```

So it's useful to have both `@mod()` and `@rem()` and to explicitly choose which behavior you want. I think we just need to fix Zig's implementations to obey the identities.
