### ISSUE TITLE
Compiler segfault when generating WebAssembly

### ISSUE THREAD

**Issue by Xe** [ziglang/zig#2276]
```zig
export fn cwa_main() i32 {
    force_crash() catch unreachable;

    return 0;
}

extern fn random_i32() i32;
const ErrorStuff = error{
    Stuff,
};

fn force_crash() !void {
    if (@mod(random_i32(), 2) == 1) {
        return error.Stuff;
    }
}
```

Run:

```console
$ zig build-exe -target wasm32-freestanding-none src/mincrash.zig
Segmentation fault (core dumped)
```

@shritesh got a core backtrace in IRC:

![](https://i.imgur.com/NKMYyMp.png)

**Comment by justinclift** [comment]
Just to check... is this Zig compiled from the master branch, or one of the stable releases, or ? :smile:

**Comment by andrewrk** [comment]
This is a bug with master branch, and it has to do with the fact that error return traces are unavailable on the WebAssembly target.
