### ISSUE TITLE
File descriptor limits hit when linking against musl

### ISSUE THREAD

**Issue by vtduncan** [ziglang/zig#2280]
**What I tried:** Compiling a hello world C program with musl.

```
zig build-exe --c-source main.c --library c -target x86_64-linux-musl
```

(Zig version: 0.4.0+5cb18e9c)

**What I expected:** Compilation to succeed producing a statically linked executable.

**What happened:** After building for several minutes compilation failed with:

```
Unable to open /usr/lib/zig/libc/musl/src/math/finite.c: file system error
```

**What I found out with strace:** The compiler is keeping several thousand file descriptors open for cache files. e.g.

```
.local/share/zig/stage1/h/bHFPDAk_6mL1svuuFX8ZXpnagv7EzVWVNILO7sV6tjVSzmF-bxMxO_310JJnGEqv.txt
```

Eventually the operating refused to open any more files, returning `-1 EMFILE (Too many open files)`. I noticed this because on my system the soft limit for the number of files open was set relatively low at 1024.

I also checked whether the compiler was leaking file descriptors, which it didn't appear to be. The cache files got closed properly once Zig finished with them. It's just that musl has a lot of source files to build, which results in Zig opening enough cache files to hit the limit.

**Workaround:** Increase the file descriptor limit with `ulimit -n 4000` when linking against musl.

---

Thank you so much @andrewrk for making Zig! It's a pleasure to use and I'm having a great time trying out the 0.4 release.

I'm writing this issue up because it took me a while to figure out. Hopefully this will save somebody else some time, but I can see that it's not so much an issue with Zig, but rather the way the operating system is configured.

**Comment by daurnimator** [comment]
This probably brings up a good issue in that if EMFILE is hit then some cache files should be closed until needed again.

**Comment by bnoordhuis** [comment]
A complementary strategy is to raise the soft limit to the hard limit like I did in nodejs/node@6820054d2d4. Musl isn't the only environment with low soft limits, see the commit log. ^^

**Comment by andrewrk** [comment]
> This probably brings up a good issue in that if EMFILE is hit then some cache files should be closed until needed again.

The number of open files the cache system depends on is O(1) not O(N). This seems like a bug.

**Comment by andrewrk** [comment]
Thanks for the detailed writeup, @vtduncan

**Comment by bnoordhuis** [comment]
FWIW, I can reproduce. Reverting 93e89b3b7e doesn't make a difference. I'll try to figure out what's going on.

**Comment by LemonBoy** [comment]
Too many files and too many manifests open.
`codegen_build_and_link` tries to free them all once it's done with all the files but that's not a wise choice when you have so many files and such a low upper limit.

**Comment by andrewrk** [comment]
OK I just remembered why this is happening. This is actually a design flaw that needs to be addressed.

The cache system does no cache evicting yet, but it's planned to do that. So when doing a "child build", e.g. musl, the manifest file is used as a lock to prevent the corresponding build artifacts from being garbage collected. The link line of building musl is going to have N objects on it, and each object exists in the cache. Each object has its corresponding manifest file open and locked so that the object does not get evicted. Once the link of musl completes, the manifest files are all closed, and it wouldn't matter if the objects got evicted.

Unfortunately this does mean that the number of concurrent open files is O(N) where N is the number of objects on the linker command line.

**Comment by thmo** [comment]
On Fedora 30 x86_64, with a `ulimit -n 1024`, it segfaults for me (3c914c63)
```
./zig build-exe --c-source hello_world.c --library c -target x86_64-linux
posix_spawn failed: No file descriptors available
???:?:?: 0x7fa1092e0469 in ??? (???)


???:?:?: 0x7fa109126b73 in ??? (???)


???:?:?: 0x7ffd9bdd0d30 in ??? (???)


???:?:?: 0x6873646f6d5f4853 in ??? (???)


zsh: segmentation fault (core dumped)  ./zig build-exe --c-source hello_world.c --library c -target x86_64-linux

```

**Comment by marler8997** [comment]
Just letting you know I hit this today.  Running `ulimit -n 4000` allows it to work.

**Comment by andrewrk** [comment]
I added @bnoordhuis's patch in b564e7ca59818e4904fc421fc8b1914cefd79538. I think this is resolved. If we can get away with enough file descriptors to build musl, we should be good, and it'll simplify the cache garbage collection to not change it from status quo.
