### ISSUE TITLE
cInclude defines __STDC_HOSTED__ when compiling freestanding

### ISSUE THREAD

**Issue by tyler569** [ziglang/zig#2287]
I have a project where I check in a header file that `__STDC_HOSTED__` is not set to 1 as a warning against compiling the project without using the freestanding flag.  When I went to add a Zig module to the project, it was unable to include the header file due to `__STDC_HOSTED__` being defined to 1 even though the target for my build was `x86_64-freestanding-none` and no c library is linked in.

This macro is set to 0 by clang and gcc if you add -ffreestanding.

Love the work you're doing on zig, and this is super low priority, as I've just commented out the check for now.

Test case:
hosted.zig:
```zig
const c = @cImport({
    @cInclude("freestanding.h");
});

export fn main() c_int {
    return c.foobar;
}
```
freestanding.h:
```c
_Static_assert(__STDC_HOSTED__ == 0, "this can only be compiled freestanding");
int foobar = 10;
```
Compiled with: `zig build-exe -target x86_64-freestanding-none -isystem . hosted.zig`

Results in:
```
/home/tyler/projects/zig-test/hosted.zig:1:11: error: C import failed
const c = @cImport({
          ^
/home/tyler/projects/zig-test/hosted.zig:1:11: note: libc headers not available; compilation does not link against libc
const c = @cImport({
          ^
./freestanding.h:1:1: note: static_assert failed due to requirement '1 == 0' "this can only be compiled freestanding"
_Static_assert(__STDC_HOSTED__ == 0, "this can only be compiled freestanding");
^
```

**Comment by andrewrk** [comment]
Hi @tyler569, thanks for taking the time to file an issue. I think this is actually going to be a nice easy fix.

Zig needs to detect when the target is freestanding and then:
 * add `-ffreestanding` to the C args for building C objects in `codegen.cpp::gen_c_object`
 * add `-ffreestanding` to the C args used for translate-c in `translate_c.cpp::parse_h_file`
