### ISSUE TITLE
zig fmt fails to parse return values when missing parenthesis

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2305]
Running `zig fmt` on:
```zig
const mycond = true;
pub fn foo() if (mycond) i32 else void {
    if (mycond) {
        return 42;
    }
}
```

fails with: `fmt-fail.zig:7:1: error: Expected ';' or '{', found Eof`

This works okay though:
```zig
const mycond = true;
pub fn foo() (if (mycond) i32 else void) {
    if (mycond) {
        return 42;
    }
}
```

**Comment by andrewrk** [comment]
I just confirmed with [zig-spec](https://github.com/ziglang/zig-spec) that this grammar is supposed to be accepted.
