### ISSUE TITLE
DirectAllocator leaves unused pages mapped on large alignments

### ISSUE THREAD

**Issue by squeek502** [ziglang/zig#2306]
This is a bug that was found during last week's GeneralPurposeDebugAllocator stream that I figured I'd file a bug report for so that it doesn't slip through the cracks. @andrewrk said that the changes made in the GPDA should be copied into DirectAllocator (or at least looked into further), since the affected code was copied from the DirectAllocator.

As far as I understand it, the error happens when alignment is larger than page size and the allocation happens to be aligned, but the alignment is larger than the allocation size (so there are unused bytes at the end of the allocation). A secondary bug may exist in that any unused bytes at the end were not being `munmap`'d even if they should have been (i.e. if the aligned allocation has unused bytes at the start and at the end). The specific error is `integer overflow` stemming from [this line](https://github.com/ziglang/zig/blob/4c03746926562e4e9650eec7c4361836fabba5af/std/heap.zig#L79):
```zig
const unused_len = aligned_addr - 1 - unused_start;
```
*(note that my description has a decent chance of being wrong)*

---

- Debugging the issue in GPDA starts here on the stream VOD: https://youtu.be/L4TLeercPrc?t=2971
- Diff for the fix in GPDA: https://github.com/andrewrk/zig-general-purpose-allocator/commit/e7abd4ca7bd44f9eb134faedcfc400e7709a930c#diff-6b04986ec1c03bb0b2c30c92a206c339L255
- Relevant DirectAllocator code (that was copied into GPDA): https://github.com/ziglang/zig/blob/4c03746926562e4e9650eec7c4361836fabba5af/std/heap.zig#L65-L87

Unsure if this affects Windows.

**Comment by squeek502** [comment]
Attempted to reproduce this but wasn't able to with DirectAllocator, while GPDA fails every 3 or so runs without the changes linked in the OP.

Instead, I found that the real cause is that the GPDA uses `std.mem.alignForward` to set `aligned_addr`, while the DirectAllocator uses different code:

- `std.mem.alignForward`: `(addr + alignment - 1) & ~(alignment - 1);`
- `DirectAllocator`: `(addr & ~usize(alignment - 1)) + alignment;`

In the integer overflow case in GPDA, this is what's happening:
- Attempt to alloc with `alignment=8192`, `n=8292` (resulting in `alloc_size=16484`)
- mmap gives an address like: `140349712539648`
- `align_addr` is set to `140349712539648` by calling `std.mem.alignForward(addr, alignment)`
- `addr == aligned_addr` so `aligned_addr - 1 - unused_start` overflows (-1)

In the DirectAllocator, however, `align_addr` would be set to `140349712547840` from the `(addr & ~usize(alignment - 1)) + alignment` calculation (+8192 difference from the std.mem.alignForward result), and therefore avoid the overflow.

---

I don't know enough about this to know which one is doing something wrong, but one of them surely is. Hopefully that can serve as a starting point for someone that understands this better.

**Comment by squeek502** [comment]
Did some more investigating and think I understand a bit more now. DirectAllocator's functionality is safe from the integer overflow error and functions correctly. Here's what it's doing:

- `mmap`'s `n + alignment` bytes to ensure the result can be aligned
- sets `aligned_addr` to be aligned at the **end** of the allocation, i.e. any unused bytes are guaranteed to be *before* `aligned_addr`
- `munmap`'s the unused bytes from the start of the allocation to `aligned_addr - 1` (the comments say the -1 is to avoid munmap eating the aligned_addr's page too but that might not be true; the -1 doesn't hurt though, as the man says "All pages containing a part of the indicated range are unmapped").
- returns the slice from `aligned_addr` to the end of the allocation

The GPDA needed a different solution due to the (inadvertent) change to using `std.mem.alignForward`. I'll make an issue for that in the GPDA repo, though, since it doesn't affect DirectAllocator.

I'll leave this open for a bit if anyone has any input, otherwise it can be closed.

**Comment by andrewrk** [comment]
Thanks for the writeup!

**Comment by squeek502** [comment]
Ok, I think I finally have something concrete, and DirectAllocator is the one doing something wrong and the GPDR changes are necessary: the current DirectAllocator sometimes leaves pages mapped that should have been unmapped, as it only unmaps from the beginning of the allocation up to the aligned address, and does not unmap any unused pages *after* the aligned portion.

Here's an attempt at illustrating the possible situations (the following was also explained by @andrewrk in the GPDA stream linked in the OP):

```
page boundaries         |  |  |  |  |  |  |
intended alloc length   |###|
alignment (page_size*2) |.....|
alloc size (n+align)    |###|.....|

1) when actual alloc is not already aligned:

page boundaries         |  |  |  |  |  |  |
aligned addresses       |     |     |     |
actual alloc               |?????????|.|
aligned portion               |###|.|
unused pages (2)           |..|     |..|

2) when actual alloc is already aligned to the start:

page boundaries         |  |  |  |  |  |  |
aligned addresses       |     |     |     |
actual alloc                  |?????????|.|
aligned portion               |###|.|
unused pages (2)                    |..|..|

3) when actual alloc is already aligned to the end:

page boundaries         |  |  |  |  |  |  |
aligned addresses       |     |     |     |
actual alloc                  |?????????|.|
aligned portion                     |###|.|
unused pages (2)              |..|..|
```

In the above illustrations, every instance *should* end up with the same amount of pages unmapped and the same amount of pages mapped regardless of where the actual allocation happens to be. However, in the current DirectAllocator code, only the last possibility (actual alloc is already aligned to the end) ends up with the correct/maximum number of pages unmapped.

This was verified by the following test code (as well as lots of debug printing):
```zig
var slice = try allocator.alignedAlloc(slice, page_size * 2, page_size * 2 + 100);
const slice_end = @ptrToInt(slice.ptr) + slice.len;
const slice_end_page_boundary = std.mem.alignForward(slice_end, page_size);
const page_after_slice = @intToPtr([*]u8, slice_end_page_boundary)[0..page_size];

// this should segfault, as it should theoretically be in an unmapped page
page_after_slice[1] = 0x34;
```

When using DirectAllocator, it only segfaults every once in a while (when alloc is already aligned to the end as described above), but it segfaults every time in GPDA since the GPDA unmaps unused pages both before and after the aligned portion.

I will be making PR(s) to address this stuff in the next few days.

**Comment by squeek502** [comment]
Note: still unsure if this affected Windows. Will look into that when I have a chance.

**Comment by tgschultz** [comment]
I think there may be an issue with Windows DirectAllocator as well. Not sure if it is related yet, but I'm pretty sure I've ruled out my own code as a cause, and it seems to have to do with large alignments. Will post more if I can work it out.

**Comment by tgschultz** [comment]
DirectAllocator's Windows implementation was indeed affected by recent allocator API changes. Specifically, it never calls HeapFree and HeapReAlloc doesn't seem to function as free when passed dwBytes of zero.

PR incoming.

**Comment by squeek502** [comment]
Confirmed that this does not affect Windows, as Windows does not free the unused bytes of memory. This is because HeapFree can only free entire alloced chunks, not parts of an alloced chunk. So Windows allocs `n + alignment + @sizeOf(usize)` bytes to ensure alignment (and to store the root address of the alloc which is needed to free it later) and then the superfluous bytes are just kept around until its finally freed all at once.
