### ISSUE TITLE
Compiler segfault on while loop with no body

### ISSUE THREAD

**Issue by SamTebbs33** [ziglang/zig#2309]
I've encountered a situation where the compiler gets a segfault when compiling a while loop with no body.

```
pub fn main() void {
    while(true);
}
```

Tested on the snap build of v0.4.0. The full error, as well as the command used, is 

> “zig build-exe test.zig” terminated by signal SIGSEGV (Address boundary error)

**Comment by raulgrell** [comment]
Is `while(true);` equivalent to `while(true){}`? Should this be a parse error?

**Comment by raulgrell** [comment]
Surfaces in ir.cpp

```
static IrInstruction *ir_gen_while_expr(IrBuilder *irb, Scope *scope, AstNode *node) {
    ...
    IrInstruction *body_result = ir_gen_node(irb, node->data.while_expr.body, &loop_scope->base);
    ...
}
```

`node->data.while_expr.body` is null, can't generate node, segfaults a few frames deeper

**Comment by SamTebbs33** [comment]
> Is `while(true);` equivalent to `while(true){}`? Should this be a parse error?

I would say that it should be equivalent since adding the extra characters in `{}` just to make the parser happy feels unnecessary.

**Comment by rj00a** [comment]
This occurs with if expressions as well.
```zig
pub fn main() {
    if ("whatever");
}
```
```
$ zig build-exe main.zig
Segmentation fault (core dumped)
```

**Comment by hryx** [comment]
Note that the statements causing these crashes are currently illegal according to the [`WhileStatement`][while] and [`IfStatement`][if] grammar rules.

[while]: https://github.com/ziglang/zig-spec/blob/master/grammar/grammar.y#L51-L53
[if]: https://github.com/ziglang/zig-spec/blob/master/grammar/grammar.y#L39-L41

**Comment by SamTebbs33** [comment]
@hryx I will take a look at the parser and see what can be done to prevent the statement body from being null.
