### ISSUE TITLE
Asm block should disallow output to constant

### ISSUE THREAD

**Issue by tyler569** [ziglang/zig#2321]
Currently, if you compile this function:
```zig
export fn foo() i64 {
    const f: i64 = 1000;

    asm volatile (
        \\ movq $10, %[f]
        : [f] "=r" (f)
    );

    return f;
}
```

`foo` will always return `1000`.  This is because it goes through the effort to allocate a stack space for `f`, puts 10 there, then just unconditionally returns 1000.

```asm
0000000000000200 <foo>:
     200:       55                      push   rbp
     201:       48 89 e5                mov    rbp,rsp
     204:       48 c7 45 f8 00 10 00    mov    QWORD PTR [rbp-0x8],0x1000
     20b:       00 
     20c:       48 c7 c0 0a 00 00 00    mov    rax,0xa
     213:       48 89 45 f8             mov    QWORD PTR [rbp-0x8],rax
     217:       b8 00 10 00 00          mov    eax,0x1000
     21c:       5d                      pop    rbp
     21d:       c3                      ret
```

I assume this is happening because zig is short circuiting the return of a constant value, but it was still surprising.  Changing `const` to `var` does cause the code to behave as expected and return 10.

C compilers (except from gcc 8.3) solve this problem by disallowing asm blocks to output to `const` variables:
```
<source>: In function 'foobar':
<source>:5:5: error: read-only variable 'f' used as 'asm' output
     asm volatile (
     ^~~
```

**Comment by nektro** [comment]
currently this segfaults at runtime, so should likely be labeled miscompilation as well

```
Segmentation fault at address 0x20d938
./test.zig:4:5: 0x211cbb in foo (test)
    asm volatile (
    ^
```
