### ISSUE TITLE
Add CI job to check that repository passes zig fmt

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2322]
Inspired by https://github.com/ziglang/zig/commit/22f5e5fd3e7f4cf15c38c2b3be0b0e357854026a#r33253675

Add a CI job to the repository that runs `zig fmt --check` on zig files in `std/` and `src-self-hosted/`, and fails if anything isn't the correct formatting.

Future pull requests that modify `zig fmt` should be accompanied by a commit that reformats zig files in the repository to the new output.

**Comment by emekoi** [comment]
if the job is just running `zig fmt`, could we set up a bot that clones a pull request, formats it, and pushes that to the pull request branch when ci passes?

**Comment by andrewrk** [comment]
I'd be OK with something that *runs* zig fmt and commits the results. But I don't want to punish people for not running it. Also I would like to wait until we are shipping self-hosted before activating something like this.
