### ISSUE TITLE
Grammar allows for parenthetical expr after `struct`

### ISSUE THREAD

**Issue by hryx** [ziglang/zig#2330]
CC @Hejsil 

```
ContainerDeclType
    <- (KEYWORD_struct / KEYWORD_enum) (LPAREN Expr RPAREN)?
     / KEYWORD_union (LPAREN (KEYWORD_enum (LPAREN Expr RPAREN)? / Expr) RPAREN)?
```

If I understand, the `(LPAREN Expr RPAREN)?` is there to support an optional tag type on an enum. But it also allows for a similar expression suffixing on the `struct` keyword.

```zig
const E1 = enum {}; // ok
const E2 = enum(u8) {}; // ok
const S1 = struct {}; // ok
const S2 = struct(u8) {}; // wat?
```

I can't find any  usage of this in the compiler code base. Is this correct? If not, this should "fix" the rule:

```
ContainerDeclType
    <- KEYWORD_struct
     / KEYWORD_enum (LPAREN Expr RPAREN)?
     / KEYWORD_union (LPAREN (KEYWORD_enum (LPAREN Expr RPAREN)? / Expr) RPAREN)?
```

**Comment by Hejsil** [comment]
I might just have been lazy and reused a rule. I think your fix is correct. I'm home tomorrow to fix this in stage 1 and grammar if you don't want to :)

**Comment by hryx** [comment]
@Hejsil No worries, I gotta hot sec to patch this :hotdog:
