### ISSUE TITLE
Logging allocator wrapper

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2337]
For debugging, I'd love an allocator in the stdlib that wraps another allocator and logs all operations to e.g. stderr

**Comment by Sahnvour** [comment]
I think that's a great idea and it can be extended to overlap what @andrewrk is doing on his GPDA: collect allocation stacktraces and warn about leaks, double frees etc.

**Comment by daurnimator** [comment]
Closed via ad7927a7486123b61221746b43cb0936fa5c71c0
