### ISSUE TITLE
Make *WithOverflow builtins return an optional types

### ISSUE THREAD

**Issue by LemonBoy** [ziglang/zig#2362]
A few builtins return a `bool` value signaling whether the operation has overflown or not and return the result of the computation via a reference parameter.

* AddWithOverlow
* SubWithOverflow
* MulWithOverflow
* ShlWithOverflow

A quick review of the zig compiler codebase shows that we have only a few use-cases:
- Stand-alone `if` + `return` on overflow
```zig
            if (@addWithOverflow(u8, x, digit, &x)) {
                return error.Overflow;
            }
```
- Ignored result (heh)
```zig
    _ = @shlWithOverflow(usize, ~usize(0), USizeShift(@ctz(large_align)), &align_mask);
```
- Inline `if` + `return` error on overflow and the result otherwise
```zig
    return if (@mulWithOverflow(T, a, b, &answer)) error.Overflow else answer;
```
- Conversion to integral type
```zig
            carry = @boolToInt(@addWithOverflow(Limb, a[i], carry, &r[i]));
```

The proposal is pretty simple, the aforementioned builtin should change their prototype from:
```zig
(comptime T: type, a: T, b: T, result: *T) bool
```
to
```zig
(comptime T: type, a: T, b: T) ?T
```

With such a change the lines above could be rewritten as:

```zig
const x = @addWithOverflow(u8, x, digit, &x) orelse return error.Overflow;
return if (@mulWithOverflow(T, a, b, &answer)) |answer| answer else error.Overflow;
carry = if (@addWithOverflow(Limb, a[i], carry, &r[i])) |_| 0 else 1;
```

## Prior art
- [Rust](https://doc.rust-lang.org/std/primitive.u32.html#method.checked_add) - Returns an `option<T>` type
- [Swift](https://developer.apple.com/documentation/swift/uint64/2885895-addingreportingoverflow) - Returns a `(value, bool)` tuple

**Comment by andrewrk** [comment]
> [Rust](https://doc.rust-lang.org/std/primitive.u32.html#method.checked_add) - Returns an `option<T>` type

Note that this is the rust standard library, and Zig does have something equivalent: https://github.com/ziglang/zig/blob/28071ac637a73fea7db89cf9c041ca349554a437/std/math.zig#L266
https://github.com/ziglang/zig/blob/28071ac637a73fea7db89cf9c041ca349554a437/std/math.zig#L271
https://github.com/ziglang/zig/blob/28071ac637a73fea7db89cf9c041ca349554a437/std/math.zig#L261

**Comment by LemonBoy** [comment]
Oh, right. The [intrinsic](https://github.com/rust-lang/rust/blob/cfeb9171b11b0791059dbe3eeddbcfe017a4708a/src/libcore/intrinsics.rs#L1211) definition also returns a `(value, bool)` tuple.
