### ISSUE TITLE
audit the structs in std/os/netbsd.zig

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2382]
Noted in https://github.com/ziglang/zig/pull/2326#discussion_r279581790, it seems that these structs were copied from an incorrect source rather than the system header files.

**Comment by pcsx22** [comment]
I'll take up this one as my first issue.

**Comment by andrewrk** [comment]
Great! You can use `zig translate-c` to do most of the work for you.

**Comment by daurnimator** [comment]
@cryo
