### ISSUE TITLE
incorrect usage of mmap return value in the standard library

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2415]
```
../std/heap.zig:                if (addr == p.MAP_FAILED) return error.OutOfMemory;
../std/os.zig:    if (mmap_addr == posix.MAP_FAILED) return error.OutOfMemory;
```

These assume the libc API of mmap. However that is a libc thing. mmap returns an error in the normal syscall return code format and posix.getErrno() is needed to find out the error code.

Related: #2380

**Comment by pcsx22** [comment]
I will take this one. Just to be clear, the error returnType for these functions should be changed to generic errorType, right?

**Comment by pcsx22** [comment]
I introduced a error set (posixMmapError) which has all kinds of error to be thrown by mmap(). I merged posixMmapError error set with the already used error set in mem.zig->Allocator struct->reallocFn. Since, mem.allocator is used in tons of files(fmt.zig, child_process.zig), I'm merging posixMmapError set to the error set used in these files. Is this the correct approach ? @andrewrk

**Comment by andrewrk** [comment]
@pcsx22 it's hard to understand what you mean - can you open a draft PR to show what you mean?

**Comment by pcsx22** [comment]
@andrewrk Have a look at this commit: https://github.com/pcsx22/zig/commit/6885f717ca626bc6cf28a526330b0b8d882d13e7. I have put some comments regarding the code change; have a look at it

**Comment by andrewrk** [comment]
coincidentally musl just fixed an equivalent bug:

```diff
commit 77846800722914eeba170505c2e7f89e12a6beff
Author: Ilya Matveychikov <matvejchikov@gmail.com>
Date:   Sat Feb 9 18:56:17 2019 +0400

    fix the use of syscall result in dl_mmap

diff --git a/ldso/dynlink.c b/ldso/dynlink.c
index 206427fe..7cb66db9 100644
--- a/ldso/dynlink.c
+++ b/ldso/dynlink.c
@@ -920,7 +920,7 @@ static void *dl_mmap(size_t n)
 #else
        p = (void *)__syscall(SYS_mmap, 0, n, prot, flags, -1, 0);
 #endif
-       return p == MAP_FAILED ? 0 : p;
+       return (unsigned long)p > -4096UL ? 0 : p;
 }
 
 static void makefuncdescs(struct dso *p)

```
