### ISSUE TITLE
std.math.ceilPowerOfTwo

### ISSUE THREAD

**Issue by squeek502** [ziglang/zig#2426]
Split from https://github.com/ziglang/zig/pull/2404#discussion_r280643264

Figured I'd make an issue for this first instead of a PR because there are some things to work out in terms of how it should be implemented.

### Performance

Some articles talking about optimizing this type of function in C:
- https://graphics.stanford.edu/~seander/bithacks.html#RoundUpPowerOf2
- https://jameshfisher.com/2018/03/30/round-up-power-2/
- http://locklessinc.com/articles/next_pow2/

I tried 5 different zig implementations:

```zig
// naive implementation
// this can overflow (i.e. ceilPowerOfTwo(u4, 9))
pub fn ceilPowerOfTwo0(comptime T: type, value: T) T {
    if (value <= 2) return value;
    var power: T = 1;
    while (power < value)
        power *= 2;
    return power;
}

// using log2_int_ceil
// this can overflow (i.e. ceilPowerOfTwo(u4, 9))
pub fn ceilPowerOfTwo1(comptime T: type, value: T) T {
    if (value <= 2) return value;
    const log2_val = log2_int_ceil(T, value);
    return T(1) << log2_val;
}

// using bit shifting with special case for value <= 2
// this can overflow (i.e. ceilPowerOfTwo(u4, 9))
pub fn ceilPowerOfTwo2(comptime T: type, value: T) T {
    if (value <= 2) return value;

    var x = value - 1;

    comptime var i = 1;
    inline while (T.bit_count > i) : (i *= 2) {
        x |= (x >> i);
    }

    return x + 1;
}

// using bit shifting with wrapping arithmetic operators to avoid special case
// ceilPowerOfTwo(u4, 9) will erroneously return 0 due to wrapping
pub fn ceilPowerOfTwo3(comptime T: type, value: T) T {
    var x = value -% 1;

    comptime var i = 1;
    inline while (T.bit_count > i) : (i *= 2) {
        x |= (x >> i);
    }

    return x +% 1;
}

// using @clz
// this can overflow (i.e. ceilPowerOfTwo(u4, 9)) with "integer cast truncated bits"
pub fn ceilPowerOfTwo4(comptime T: type, value: T) T {
    if (value <= 2) return value;
    const Shift = comptime std.math.Log2Int(T);
    return T(1) << @intCast(Shift, T.bit_count - @clz(value - 1));
}
```

Benchmark results in seconds (all using `--release-fast`):

| Function | u64 | u32 |
| --- | ---: | ---: |
| ceilPowerOfTwo0 | 10.56990 | 10.41780 |
| ceilPowerOfTwo1 | 1.38367 | 1.38362 |
| ceilPowerOfTwo2 | 1.27046 | 0.55604 |
| ceilPowerOfTwo3 | 0.97806 | 0.41661 |
| ceilPowerOfTwo4 | 0.90958 | 0.90932 |

Benchmarks for versions of the above functions that `assert(value != 0)` instead of handling 0 as a special case:

| Function | u64 | u32 |
| --- | ---: | ---: |
| ceilPowerOfTwo0 | 10.42022 | 10.58582 |
| ceilPowerOfTwo1 | 1.32996 | 0.91351 |
| ceilPowerOfTwo2 | 1.03196 | 0.43847 |
| ceilPowerOfTwo3 | 1.07271 | 0.43243 |
| ceilPowerOfTwo4 | 0.77438 | 0.71446 |

Benchmark code:
<details>

```zig
const std = @import("std");
const math = std.math;
const time = std.os.time;
const Timer = time.Timer;

pub fn main() !void {
    const stdout_file = try std.io.getStdOut();
    const stdout = &stdout_file.outStream().stream;

    var timer = try Timer.start();
    const start = timer.lap();

    var x : u32 = 0;
    // y is just to stop the compiler from optimizing the loop out completely
    var y : u32 = 0;
    while( x < (1 << 30) ) : (x += 1) {
        y = y + math.ceilPowerOfTwo0(u32, x);
    }

    const end = timer.read();

    const elapsed_s = @intToFloat(f64, end - start) / time.ns_per_s;
    try stdout.print("{.5}\ny={}\n", elapsed_s, y);
}
```

Benchmark code to test all of them at the same time:

```zig
const std = @import("std");
const math = std.math;
const time = std.os.time;
const Timer = time.Timer;

const ALLOW_ZERO = false;

fn bench(comptime T: type, comptime func: fn (T: type, value: T) T, comptime name: []const u8, out: var) !void {
    var timer = try Timer.start();
    const start = timer.lap();

    var x : T = if (ALLOW_ZERO) 0 else 1;
    var y : T = 0;
    while( x < (1 << 30) ) : (x += 1) {
        y = y + func(T, x);
    }

    const end = timer.read();
    const elapsed_s = @intToFloat(f64, end - start) / time.ns_per_s;

    try out.print("{} {}: {.5}  y={}\n", @typeName(T), name, elapsed_s, y);
}

pub fn main() !void {
    const stdout_file = try std.io.getStdOut();
    const stdout = &stdout_file.outStream().stream;

    try bench(u64, math.ceilPowerOfTwo0, "ceilPowerOfTwo0", stdout);
    try bench(u32, math.ceilPowerOfTwo0, "ceilPowerOfTwo0", stdout);

    try bench(u64, math.ceilPowerOfTwo1, "ceilPowerOfTwo1", stdout);
    try bench(u32, math.ceilPowerOfTwo1, "ceilPowerOfTwo1", stdout);

    try bench(u64, math.ceilPowerOfTwo2, "ceilPowerOfTwo2", stdout);
    try bench(u32, math.ceilPowerOfTwo2, "ceilPowerOfTwo2", stdout);

    try bench(u64, math.ceilPowerOfTwo3, "ceilPowerOfTwo3", stdout);
    try bench(u32, math.ceilPowerOfTwo3, "ceilPowerOfTwo3", stdout);

    try bench(u64, math.ceilPowerOfTwo4, "ceilPowerOfTwo4", stdout);
    try bench(u32, math.ceilPowerOfTwo4, "ceilPowerOfTwo4", stdout);
}
```

</details>

### Handling overflows

This is something that I'd like input on how best to handle. Overflows can easily happen from things like `ceilPowerOfTwo(u4, 9)` since the correct answer is 16 but 4 bits isn't enough to store the value 16.

### Handling zero

Unsure if `ceilPowerOfTwo(0)` should return zero or just not allow zero as a valid input. `math.log2_int` and `math.log2_int_ceil`, for example, just do `assert(x != 0)`.

### Test code

Just for completeness, here are the test asserts I am using. Each of the functions above pass these tests:

```zig
fn testCeilPowerOfTwo() void {
    testing.expect(ceilPowerOfTwo(u32, 0) == 0); // should it allow zero as an input?
    testing.expect(ceilPowerOfTwo(u32, 1) == 1);
    testing.expect(ceilPowerOfTwo(u32, 2) == 2);
    testing.expect(ceilPowerOfTwo(u32, 63) == 64);
    testing.expect(ceilPowerOfTwo(u32, 64) == 64);
    testing.expect(ceilPowerOfTwo(u32, 65) == 128);
    testing.expect(ceilPowerOfTwo(u5, 7) == 8);
    testing.expect(ceilPowerOfTwo(u5, 8) == 8);
    testing.expect(ceilPowerOfTwo(u5, 9) == 16);
}
```

**Comment by daurnimator** [comment]
How about a `clz` based implementation?

```zig
1<<(T.bit_count-@clz(x-1))
```

**Comment by squeek502** [comment]
> How about a `clz` based implementation?
> 
> ```zig
> 1<<(T.bit_count-@clz(x-1))
> ```

I can't seem to get this to compile (running into things like `expected type 'u5', found 'u32'` that I don't know how to solve). Happy to test it if you can provide an implementation that compiles.

**Comment by tgschultz** [comment]
Simple enough to fix:
```
pub fn ceilPowerOfTwo(comptime T: type, x: T) T
{
    const Shift = comptime std.math.Log2Int(T);
    return T(1) << @intCast(Shift, T.bit_count - @clz(x - 1));
}
```
This would have to special case 0, however.

**Comment by squeek502** [comment]
Thanks @tgschultz, I was trying similar things to that but I guess not exactly that.

Benchmark results:

| Function | u64 | u32 |
| --- | ---: | ---: |
| ceilPowerOfTwo4 | 0.90958 | 0.90932 |

And here's a table of benchmarks when the functions don't handle 0 and instead `assert(value != 0)`:

| Function | u64 | u32 |
| --- | ---: | ---: |
| ceilPowerOfTwo0 | 10.42022 | 10.58582 |
| ceilPowerOfTwo1 | 1.32996 | 0.91351 |
| ceilPowerOfTwo2 | 1.03196 | 0.43847 |
| ceilPowerOfTwo3 | 1.07271 | 0.43243 |
| ceilPowerOfTwo4 | 0.77438 | 0.71446 |

Updated the OP to include this info.

**Comment by daurnimator** [comment]
> ceilPowerOfTwo3 	1.07271 	0.43243
> ceilPowerOfTwo4 	0.77438 	0.71446

Interesting that variant 3 is faster on 32bit; while variant 4 is faster on 64 bit.
I would dispatch to the fastest implementation based on integer size.

Could you share how you're benchmarking this?

**Comment by squeek502** [comment]
> Could you share how you're benchmarking this?

It's in the details block of the OP (under "Benchmark code:", click Details to expand it).

Here's a possible "best of both worlds" implementation:

```zig
pub fn ceilPowerOfTwo5(comptime T: type, value: T) T {
    comptime const func = if (T.bit_count <= 32) ceilPowerOfTwo3 else ceilPowerOfTwo4;
    return func(T, value);
}
```

With u128 added (and using implementations that do not handle the zero case):

| Function | u128 | u64 | u32 |
| -------- | ---: | --: | --: |
| ceilPowerOfTwo1 | 4.30125 | 1.33197 | 0.92395 |
| ceilPowerOfTwo2 | 3.93818 | 1.03101 | 0.44397 |
| ceilPowerOfTwo3 | 3.93815 | 1.02746 | 0.44368 |
| ceilPowerOfTwo4 | 1.93174 | 0.77424 | 0.71458 |
| **ceilPowerOfTwo5** | **1.93164** | **0.77430** | **0.43666** |

These results might be architecture-specific, though?

**Comment by daurnimator** [comment]
> These results might be architecture-specific, though?

Possibly: what is your architecture?

**Comment by squeek502** [comment]
Been running the benchmarks on Linux x86_64. Will also test using my Windows 7 64bit machine and see how they compare.

**Comment by squeek502** [comment]
Benchmarks on my Windows machine (uses a fairly old i5-2500):

| Function | u128 | u64 | u32 |
| -------- | ---: | --: | --: |
| ceilPowerOfTwo1 | 8.00723 | 3.05670 | 3.03319 |
| ceilPowerOfTwo2 | 6.39120 | 1.46631 | 0.64024 |
| ceilPowerOfTwo3 | 6.43039 | 1.46267 | 0.61936 |
| ceilPowerOfTwo4 | 4.15350 | 1.65389 | 1.65085 |
| ceilPowerOfTwo5 | 4.16159 | 1.65682 | 0.62337 |

**Comment by daurnimator** [comment]
> Been running the benchmarks on Linux x86_64. Will also test using my Windows 7 64bit machine and see how they compare.

I would expect all x86_64 to have similar behaviour. The interesting comparison would be other cpu architectures. x86 (32bit) would be good to check.... But otherwise: anyone got an ARM device handy?

**Comment by daurnimator** [comment]
> Benchmarks on my Windows machine (uses a fairly old i5-2500):

> ceilPowerOfTwo3 	6.43039 	1.46267 	0.61936
> ceilPowerOfTwo4 	4.15350 	1.65389 	1.65085

Interesting! u64 `@clz` is slower there.... Is the assembly the same? I would assume the difference is due to the CPU change rather than OS.

**Comment by squeek502** [comment]
Any input on how this function should handle overflow? Two options I can see:

- Return a type with 1 more bit than the input type (i.e. u32 returns u33).
- Add a possible error return and use `std.math.add`/`std.math.shlExact` to return `error.Overflow` on overflow.

Also unsure about the case of zero as an input. Should the function handle zero or just disallow zero as an input?

**Comment by andrewrk** [comment]
From an API perspective, my approach is use-case driven. If there's a use case for a function that handles 0, then there should be a function that handles 0. If there's not, then asserting the input is not equal to zero is reasonable (and should be clearly documented in the doc comments for the function). This is sort of the meaning of the "zen" philosophy of "communicate intent precisely". As long as the callsite is clear about how it expects zero to be handled whether by function name or how the errors are handled, then everybody is going to get what they want.

It's generally OK to have a function such as `std.math.add` which returns a possible error. In cases where the callsite asserts that errors cannot occur (with `catch unreachable`), it is always possible for zig to generate a special case version of that function where any code path that would return an error is `unreachable`. This is not currently implemented but it is allowed by the language semantics.

**Comment by Sahnvour** [comment]
> These results might be architecture-specific, though?

Very likely, and it can also vary between micro-architectures with the same asm code, for example different processor families inside x64.

**Comment by qdbp** [comment]
If this function is added, I suggest also adding `ceil(lg(x))` -- maybe call it `CeilLog2`. That one has been useful a number of times in numerical code for things like minimum height of a tree, etc.

Also I am not sure I agree with the proposed naming. It seems more natural to name the function something like `pow2CeilLog2` or `roundUpToPow2` which is more explicit. What `ceilPowerOfTwo` does is not very clear from the name.

**Comment by squeek502** [comment]
> If this function is added, I suggest also adding `ceil(lg(x))` -- maybe call it `ceilLog2`. That one has been useful a number of times in numerical code for things like minimum height of a tree, etc.

Is this different from `std.math.log2_int_ceil`? If not, that exists.

> Also I am not sure I agree with the proposed naming. It seems more natural to name the function something like `pow2CeilLog2` or `roundUpToPow2` which is more explicit. What `ceilPowerOfTwo` does is not very clear from the name.

The name was meant to match the existing `std.math.floorPowerOfTwo`.

**Comment by squeek502** [comment]
Tried versions that promote the type (to avoid overflow) or detect overflows:

```zig
// return e.g. u33 for u32 to avoid overflow
pub fn ceilPowerOfTwoPromote(comptime T: type, value: T) @IntType(T.is_signed, T.bit_count + 1) {
    comptime const promotedType = @IntType(T.is_signed, T.bit_count + 1);
    if (value == 0) return promotedType(0);
    var x = value - 1;

    comptime var i = 1;
    inline while (T.bit_count > i) : (i *= 2) {
        x |= (x >> i);
    }

    return promotedType(x) + 1;
}

// get the promoted result and detect overflow
pub fn ceilPowerOfTwoOverflow(comptime T: type, value: T) (error{Overflow}!T) {
    comptime const promotedType = @IntType(T.is_signed, T.bit_count + 1);
    comptime const overflowBit = promotedType(1) << T.bit_count;
    var x = ceilPowerOfTwoPromote(T, value);
    if (overflowBit & x != 0) {
        return error.Overflow;
    }
    return @intCast(T, x);
}

// use addWithOverflow to detect overflow
pub fn ceilPowerOfTwoAddOverflow(comptime T: type, value: T) (error{Overflow}!T) {
    if (value == 0) return T(0);
    var x = value - 1;
    comptime var i = 1;
    inline while (T.bit_count > i) : (i *= 2) {
        x |= (x >> i);
    }
    if (@addWithOverflow(T, x, 1, &x)) {
        return error.Overflow;
    }
    return x;
}

// use shlExact / shlWithOverflow to detect overflow
pub fn ceilPowerOfTwoClzOverflow(comptime T: type, value: T) (error{Overflow}!T) {
    if (value == 0) return T(0);
    const Shift = comptime std.math.Log2Int(T);
    const amt = @intCast(Shift, T.bit_count - @clz(value - 1));
    return shlExact(T, T(1), amt);
}
```

Benchmark results:

| Function | u128 | u64 | u32 |
| -------- | ---: | --: | --: |
| ceilPowerOfTwoPromote | 4.36401 | 1.87796 | 1.03311 |
| ceilPowerOfTwoOverflow | 4.86957 | 1.91341 | 1.62771 |
| ceilPowerOfTwoAddOverflow | 4.12360 | 1.74988 | 1.46501 |
| ceilPowerOfTwoClzOverflow | 4.40225 | 1.66842 | 6.26267 |

<details>
<summary>Benchmark code</summary>

```zig
const std = @import("std");
const math = std.math;
const time = std.os.time;
const Timer = time.Timer;

const ALLOW_ZERO = false;

fn bench(comptime T: type, comptime func: fn (T: type, value: T) (error{Overflow}!T)) !f64 {
    const promotedType = @IntType(T.is_signed, T.bit_count + 1);
    var timer = try Timer.start();
    const start = timer.lap();

    var x : T = if (ALLOW_ZERO) 0 else 1;
    var y : promotedType = 0;
    while( x < (1 << 30) ) : (x += 1) {
        y = y + try func(T, x);
    }

    const end = timer.read();
    const elapsed_s = @intToFloat(f64, end - start) / time.ns_per_s;

    if (y == 0) {
        @panic("");
    }
    return elapsed_s;
}

fn benchPromote(comptime T: type) !f64 {
    const promotedType = @IntType(T.is_signed, T.bit_count + 1);
    var timer = try Timer.start();
    const start = timer.lap();

    var x : T = if (ALLOW_ZERO) 0 else 1;
    var y : promotedType = 0;
    while( x < (1 << 30) ) : (x += 1) {
        y = y + math.ceilPowerOfTwoPromote(T, x);
    }

    const end = timer.read();
    const elapsed_s = @intToFloat(f64, end - start) / time.ns_per_s;

    if (y == 0) {
        @panic("");
    }
    return elapsed_s;
}

pub fn main() !void {
    const stdout_file = try std.io.getStdOut();
    const stdout = &stdout_file.outStream().stream;

    try stdout.print("| Function | u128 | u64 | u32 |\n");
    try stdout.print("| -------- | ---: | --: | --: |\n");

    var s128 = try benchPromote(u128);
    try stdout.print("\r{.5}", s128);
    var s64 = try benchPromote(u64);
    try stdout.print("\r{.5}", s64);
    var s32 = try benchPromote(u32);
    try stdout.print("\r{.5}", s32);
    try stdout.print("\r| {} | {.5} | {.5} | {.5} |\n", "ceilPowerOfTwoPromote", s128, s64, s32);

    s128 = try bench(u128, math.ceilPowerOfTwoOverflow);
    try stdout.print("\r{.5}", s128);
    s64 = try bench(u64, math.ceilPowerOfTwoOverflow);
    try stdout.print("\r{.5}", s64);
    s32 = try bench(u32, math.ceilPowerOfTwoOverflow);
    try stdout.print("\r{.5}", s32);
    try stdout.print("\r| {} | {.5} | {.5} | {.5} |\n", "ceilPowerOfTwoOverflow", s128, s64, s32);

    s128 = try bench(u128, math.ceilPowerOfTwoAddOverflow);
    try stdout.print("\r{.5}", s128);
    s64 = try bench(u64, math.ceilPowerOfTwoAddOverflow);
    try stdout.print("\r{.5}", s64);
    s32 = try bench(u32, math.ceilPowerOfTwoAddOverflow);
    try stdout.print("\r{.5}", s32);
    try stdout.print("\r| {} | {.5} | {.5} | {.5} |\n", "ceilPowerOfTwoAddOverflow", s128, s64, s32);

    s128 = try bench(u128, math.ceilPowerOfTwoClzOverflow);
    try stdout.print("\r{.5}", s128);
    s64 = try bench(u64, math.ceilPowerOfTwoClzOverflow);
    try stdout.print("\r{.5}", s64);
    s32 = try bench(u32, math.ceilPowerOfTwoClzOverflow);
    try stdout.print("\r{.5}", s32);
    try stdout.print("\r| {} | {.5} | {.5} | {.5} |\n", "ceilPowerOfTwoClzOverflow", s128, s64, s32);

}
```

</details>

Note that these results are comparable to eachother, but not necessarily directly comparable to past benchmarks. as the results include some extra overhead dealing with the promoted type variables (i.e. u33 instead of u32) to stop the benchmark loop getting optimized out of `release-fast`.

The `clz` version results are a bit weird, and comes from some strange performance issue with `shlExact`/`@shlWithOverflow` for certain int sizes (probably depends on CPU/architecture?):

| Type | `<<` | `shlExact` |
| ---- | ---: | ---: |
u4 | 0.99433 | 6.88703
... | |
u8 | 1.54627 | 6.99892
... | |
u31 | 0.97701 | 6.54927
u32 | 1.54861 | **7.00161**
u33 | 0.65103 | **2.69153**
u34 | 1.20040 | 3.17395
... | |
u47 | 1.07556 | 2.77584
u48 | 1.07585 | **2.57003**
u49 | 0.81499 | **9.11481**
u50 | 1.05492 | 9.11471
... | |
u55 | 1.12564 | **9.11473**
u56 | 1.49432 | **3.57231**
u57 | 0.83683 | 1.97347
... | |
u64 | 1.54644 | 2.49569

<details>
<summary>shlExact benchmark code</summary>

```zig
const std = @import("std");
const math = std.math;
const time = std.os.time;
const Timer = time.Timer;

const iterations = 1 << 30;

fn benchNoError(comptime T: type) !f64 {
    var timer = try Timer.start();
    const start = timer.lap();

    var x : usize = 0;
    var y : T = 0;
    while( x < iterations ) : (x += 1) {
        const amt: math.Log2Int(T) = @intCast(math.Log2Int(T), x % (T.bit_count-1));
        y += T(1) << amt;
    }

    const end = timer.read();
    const elapsed_s = @intToFloat(f64, end - start) / time.ns_per_s;

    std.debug.warn("\r{}", y);
    return elapsed_s;
}

fn benchError(comptime T: type) !f64 {
    var timer = try Timer.start();
    const start = timer.lap();

    var x : usize = 0;
    var y : T = 0;
    while( x < iterations ) : (x += 1) {
        const amt: math.Log2Int(T) = @intCast(math.Log2Int(T), x % (T.bit_count-1));
        y += try math.shlExact(T, T(1), amt);
    }

    const end = timer.read();
    const elapsed_s = @intToFloat(f64, end - start) / time.ns_per_s;

    std.debug.warn("\r{}", y);
    return elapsed_s;
}

pub fn main() !void {
    comptime var bit_count: usize = 4;
    inline while (bit_count <= 64) : (bit_count+=1) {
        const t = @IntType(false, bit_count);
        const res1 = try benchNoError(t);
        const res2 = try benchError(t);
        std.debug.warn("\ru{} {.5} {.5}\n", bit_count, res1, res2);
    }
}
```

</details>

**Comment by squeek502** [comment]
Whoops, forgot to try a promoting `clz` version, which ends up being the fastest:

```zig
pub fn ceilPowerOfTwoPromote(comptime T: type, value: T) @IntType(T.is_signed, T.bit_count + 1) {
    comptime const promotedType = @IntType(T.is_signed, T.bit_count + 1);
    if (value == 0) return promotedType(0);
    const Shift = comptime std.math.Log2Int(T);
    return promotedType(1) << @intCast(Shift, T.bit_count - @clz(value - 1));
}

pub fn ceilPowerOfTwoOverflow(comptime T: type, value: T) (error{Overflow}!T) {
    comptime const promotedType = @IntType(T.is_signed, T.bit_count + 1);
    comptime const overflowBit = promotedType(1) << T.bit_count;
    var x = ceilPowerOfTwoPromote(T, value);
    if (overflowBit & x != 0) {
        return error.Overflow;
    }
    return @intCast(T, x);
}
```

| Function | u128 | u64 | u32 |
| -------- | ---: | --: | --: |
| ceilPowerOfTwoPromote | 2.06402 | 0.84402 | 0.86550 |
| ceilPowerOfTwoOverflow | 2.06398 | 0.84504 | 0.92824 |
