### ISSUE TITLE
read() can return EAGAIN...it is not unreachable.

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2434]
If the file was opened non-blocking, `read` may return `EAGAIN` or `EWOULDBLOCK`. this is part of posix.

This shows the danger of #1396

I am working on cleaning up `posix` and noticed this.

**Comment by shawnl** [comment]
I see that `preadv` says "don't call this function for non-blocking", but why? What is wrong with using non-blocking IO?

**Comment by daurnimator** [comment]
> I see that `preadv` says "don't call this function for non-blocking", but why? What is wrong with using non-blocking IO?

Where do you see that?

**Comment by shawnl** [comment]
os.zig

**Comment by shawnl** [comment]
oh, this is purposeful.
