### ISSUE TITLE
WindowsDynLib lookup function should pass a C String to GetProcAddress

### ISSUE THREAD

**Issue by rivten** [ziglang/zig#2435]
In here : https://github.com/ziglang/zig/blob/master/std/dynamic_library.zig#L197 , the function lookup should either : receive a C String as an input (c"MyLookupName") or reformat the Zig String input to C String. This is because GetProcAddress expects a C String.

**Comment by emekoi** [comment]
this should be solved by #265, but in the mean time, i can't think of a correct solution that doesn't require a `comptime`, an allocator, of the user null-terminating the string themselves.

**Comment by andrewrk** [comment]
One thing you can do for now is have a buffer on the stack with, say, 512 bytes. If the length is too big for this return `error.NameTooLong` or similar. We can always improve this API later.

**Comment by andrewrk** [comment]
Solved with #265 and #2598
