### ISSUE TITLE
armv7-linux-musleabi: LLVM ERROR: Error parsing inline asm

### ISSUE THREAD

**Issue by akavel** [ziglang/zig#2437]
Trying to cross-compile for arm with musl:

```
c:> \dnload\android-etc\zig-nightly\zig.exe build-lib -dynamic --verbose-cc --verbose-link --c-source hello-jni.c --library c -fno-PIC -target armv7-linux-musleabi
...
...(several minutes of re-compilation of various musl files)...
...
zig cc -MD -MV -MF C:\Users\Mateusz\AppData\Local\zig\stage1\tmp\3zLACJAct1_9-mntent.o.d -nostdinc -fno-spell-checking -isystem C:\dnload\android-etc\zig-nightly\lib\zig\include -target armv7-unknown-linux-musleabi -g -D_DEBUG -fno-stack-protector -fno-omit-frame-pointer -o C:\Users\Mateusz\AppData\Local\zig\stage1\tmp\3zLACJAct1_9-mntent.o -c C:\dnload\android-etc\zig-nightly\lib\zig\libc\musl\src\misc\mntent.c -std=c99 -ffreestanding -Wa,--noexecstack -D_XOPEN_SOURCE=700 -I C:\dnload\android-etc\zig-nightly\lib\zig\libc\musl\arch\arm -I C:\dnload\android-etc\zig-nightly\lib\zig\libc\musl\arch\generic -I C:\dnload\android-etc\zig-nightly\lib\zig\libc\musl\src\internal -I C:\dnload\android-etc\zig-nightly\lib\zig\libc\musl\src\include -I C:\dnload\android-etc\zig-nightly\lib\zig\libc\include\arm-linux-musleabi -I C:\dnload\android-etc\zig-nightly\lib\zig\libc\include\generic-musl -Os -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -Qunused-arguments -w
<inline asm>:125:2: error: unexpected token at start of statement
 || __ARM_ARCH_7A__ || __ARM_ARCH_7R__ || __ARM_ARCH >= 7
 ^
<inline asm>:170:2: error: unexpected token at start of statement
 || __ARM_ARCH_7A__ || __ARM_ARCH_7R__ || __ARM_ARCH >= 7
 ^
LLVM ERROR: Error parsing inline asm
```

This was **zig nightly** (7a41af) with **armv7**.
Similar error for **zig 0.4**, and also for **armv7m** (haven't checked if the line numbers etc. exactly match, as it takes very long to reach this point, but I remember them looking very similar).
A nearly empty `hello-jni.c` file is enough to reproduce on my computer, i.e.:

```
void dummy() { }
```

*edit:* the `lib/zig/libc/musl/src/misc/mntent.c` file doesn't even seem to contain any inline assembly by itself, so I'm not really sure where this could be originating from O_o

*edit 2:* Some possible candidates:

```
C:\dnload\android-etc\zig-nightly\lib\zig\libc\musl>rg __ARM_ARCH_7A__
arch\arm\pthread_arch.h
2: || __ARM_ARCH_7A__ || __ARM_ARCH_7R__ || __ARM_ARCH >= 7

arch\arm\atomic_arch.h
12: || __ARM_ARCH_6T2__ || __ARM_ARCH_7A__ || __ARM_ARCH_7R__ || __ARM_ARCH >= 7
30:#if __ARM_ARCH_7A__ || __ARM_ARCH_7R__ ||  __ARM_ARCH >= 7
95:#if __ARM_ARCH_6T2__ || __ARM_ARCH_7A__ || __ARM_ARCH_7R__ || __ARM_ARCH >= 7

src\ldso\arm\tlsdesc.S
23: || __ARM_ARCH_7A__ || __ARM_ARCH_7R__ || __ARM_ARCH >= 7
68: || __ARM_ARCH_7A__ || __ARM_ARCH_7R__ || __ARM_ARCH >= 7

src\thread\arm\__set_thread_area.c
29:#if !__ARM_ARCH_7A__ && !__ARM_ARCH_7R__ && __ARM_ARCH < 7
```

*edit 3:* Excluding non-matching candidates, this seems to leave us with: `arch/arm/pthread_arch.h` or `src/ldso/arm/tlsdesc.S`.

*edit 4:* Given that the error message contains "inline asm" claim, and pthread_arch.h seems not especially asm-ish, it feels to me as if the `tlsdesc.S` got embedded somewhere as fake "inline assembly", and then as if LLVM had some more limited preprocessor for inline asm blocks, and bailed on this. But I don't seem to see any `#include "tlsdesc.S"` in musl nor zig sources, so maybe it's done on AST/LLVM level? Or I'm wrong and it's something else.

**Comment by andrewrk** [comment]
If I understand this correctly, this is actually an issue with musl, when built with clang for the armv7 target. The next step in solving this is to engage with the musl community and find out whether they are interested in supporting this use case and would be interested in a patch. And then of course improving the musl code base to solve this issue. Finally, the patch can be applied directly to Zig's bundled musl source, while we wait for a new upstream release.

**Comment by akavel** [comment]
@andrewrk @LemonBoy  Given #2477 was merged, should I expect this might be now fixed? If yes, is there some place where I could download a nightly build Nim packaged with CLang cross-compilers? Or do I have to wait till next Zig release? Or could I just build the zig binary from master (how?) and drop it in place of the old one and expect the result to work? TIA!

**Comment by andrewrk** [comment]
@akavel have you seen the download page? After the CI finishes a new build (about 2 hours) it will show up for you to download a .zip file.

**Comment by akavel** [comment]
🤦‍♂ Ahh, right, sorry & thanks! I felt I seen them somewhere, but somehow the downloads page confuses me again and again. Now I see they're there indeed. Thanks for patience! I'll try to retest the operation once I can find some time.

**Comment by akavel** [comment]
Yep, case closed! Awesome, huge thanks @LemonBoy !!! ❤️ 🎉
