### ISSUE TITLE
documentation for for loop with iterator

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2446]
There is no documentation that a for loop can be used with an iterator like so:
```
for (foo) |arg, i| {
  doStuff(arg, i);
}
```

**Comment by hryx** [comment]
Are you referring to the second capture argument (the index)? There is mention of it in the [`for` section](https://ziglang.org/documentation/master/#for) of the docs:

```zig
    // To access the index of iteration, specify a second capture value.
    // This is zero-indexed.
    var sum2: i32 = 0;
    for (items) |value, i| {
        assert(@typeOf(i) == usize);
        ...
```

**Comment by shawnl** [comment]
I was looking right at that and couldn't see it.

**Comment by hryx** [comment]
To be honest, I think this will be easier once there is actual prose for each topic. Some topics, like this, are only documented with code examples. Even though they have comments, the formatting is a bit of a barrier and visual strain.

**Comment by shawnl** [comment]
Nah, while I miss the side-bar, it is important that the documentation be short and too-the-point. That is why `K&R` C is such a great book.
