### ISSUE TITLE
breakpoint doesn't work in tests

### ISSUE THREAD

**Issue by emekoi** [ziglang/zig#2453]
when building the following as an executable, and running that executable in a debugger such as lldb, breakpoints work as expected:
```zig
// example.zig

pub fn main() void {
    var a: usize = 0;
    @breakpoint();
    var b = a;
}

test "@breakpoint in a test" {
    main();
}
```
however, running `zig test example.zig`, causes the test to fail.

**Comment by Sahnvour** [comment]
Breakpoints usually boil down to a trap instruction that triggers a hardware interrupt, eg. `int 3` on x86_64. The OS can have handlers for these, possibly installed by userland programs, such as debuggers. In your case it's likely that the first handler is the default one from the OS that aborts the program.
What would you expect it to do ?

**Comment by andrewrk** [comment]
This is working as intended. You'd have to run the test in a debugger to observe the breakpoint and continue the test to completion.
