### ISSUE TITLE
Refactoring - tetris as an example

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#2466]
https://github.com/markfirmware/tetris/tree/refactor-engine

I wrote a zig program that does part of the refactoring necessary to separate glfw from the rest of tetris so that it can be reused for example in an embedded system or wasm. It separates main.zig into main1 and main2 where main1 has the glfw and main2 has the rest. main1 utilizes the use statement to include main2. main1 can then be replaced with ncurses or wasm or whatever.

The engine does some work then uses compiler error messages to finish it (e.g. adding pub keywords as needed to expose what were internal functions in main so that main1 can get them from main2. 

This is the only part that I’ve implemented so far and before proceeding I wanted to check that there isn’t a third party grammar-driven refactoring engine that could be used, or that there were other plans that are in conflict with this approach.

My next step is to finish the rest of the refactoring steps and then move to using the ast instead of processing text lines.

Cheers, Mark.

**Comment by andrewrk** [comment]
I don't think there is anything actionable for the zig project from this issue
