### ISSUE TITLE
Compilation hangs instead of returning an error

### ISSUE THREAD

**Issue by kristoff-it** [ziglang/zig#2467]
Happens in both 0.4.0 and master:

```zig
export fn func() void {
    var strValue: [*c]u8 = undefined;
    strValue = strValue orelse c"";
}
```

Removing either `export` or  the `orelse` expression makes the compilation proceed successfully.
Assigning `c""` directly to `strValue` makes the compilation fail:
```
/Users/loriscro/Documents/GitHub/zig-redismodule/module.zig:3:16: error: cast discards const qualifier
    strValue = c"";
               ^
```

**Comment by andrewrk** [comment]
Thanks for the small test case. Bug fixed.

>  Assigning `c""` directly to `strValue` makes the compilation fail:

This makes sense since `strValue` is a mutable pointer, and a string literal is a constant pointer. Writes through the mutable reference could modify constant data.

**Comment by kristoff-it** [comment]
Removing `export` makes it compile, is that intended?

**Comment by andrewrk** [comment]
That's a side-effect of Zig's lazy analysis. You can read a little bit about that in the [Zig Test section of the docs](https://ziglang.org/documentation/master/#Zig-Test)

**Comment by Beefster09** [comment]
An interesting note about this bug is that passing --verbose-ir will cause an assertion error instead of hanging, but it seems this happens even on programs that compiled before.

**Comment by andrewrk** [comment]
if --verbose-ir causes an assertion error, it's likely a bug in ir_print.cpp - the code that renders ir to stderr.
