### ISSUE TITLE
Strange compile error

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#2470]
```zig
fn returnPtr() ?*c_void {
    return null;
}

var b = false;
export fn func() ?*c_void {
    if (b) {
        // Comment out and the code compiles
        return returnPtr();
    }
    var a: [*]u8 = undefined;
    return a;
}
```
```
/tmp/C/b.zig:6:18: error: incompatible types: '?*c_void' and '[*]u8'
export fn func() ?*c_void {
                 ^
/tmp/C/b.zig:9:25: note: type '?*c_void' here
        return returnPtr();
                        ^
/tmp/C/b.zig:12:12: note: type '[*]u8' here
    return a;
           ^
```

The addition of a second return statement inside func which returns the correct type causes the compiler to complain about mismatching types. Comment out the first return statement and then the code compiles. I don't know if both versions are supposed to compile or neither. I don't understand why the error message points out the two return statements instead of just one of them.

Edit: You can also replace "return returnPtr();" with "return null" and that makes the code compile, which makes zero sense as returnPtr returns the same thing.

**Comment by mikdusan** [comment]
when using an optional, i don't think implicit casting works down to payload:

```
fn f0() u32 {
    var i: u8 = 10;
    return i;
}

fn f1() ?u32 {
    var i: u8 = 10;
    return u32(i);
}

fn f2() ?u32 {
    var i: u8 = 10;
    return i; // u8 does not implicitly cast to u32 due to optional
}

test "" {
    _ = f0();
    _ = f1();
//  _ = f2(); // implicit.zig:13:12: error: expected type '?u32', found 'u8'
}
```

**Comment by gamester0** [comment]
```
export fn func() ?[*c]u8 {
var d: [*]u8 = undefined;
return d;
}
```
When I was looking into this bug yesterday I tested some variations. This one hits unreachable. I hesitated with reporting it because at this point I'm trying to annoy the first stage compiler and his job isn't to be perfect, but to get us to stage 2.

**Comment by andrewrk** [comment]
> at this point I'm trying to annoy the first stage compiler and his job isn't to be perfect, but to get us to stage 2.

This insight is spot-on, but of course feel free to report issues with stage1 when they block you from doing something. stage1 bug fixes result in more test coverage which will help stage2 as well.

**Comment by nektro** [comment]
```zig
fn returnPtr() ?*anyopaque {
    return null;
}
var b = false;
fn func() ?*anyopaque {
    if (b) {
        return returnPtr();
    }
    var a: [*]u8 = undefined;
    return a;
}
test {
    _ = func();
}
```

this passes on `0.10.0-dev.4369+1087e6776`

**Comment by andrewrk** [comment]
Test coverage here: https://github.com/ziglang/zig/blob/601ab9a251a7952026fa9c72427344126bf62730/test/behavior/cast.zig#L1097-L1106
