### ISSUE TITLE
Compiler segfault when parsing "\xN"

### ISSUE THREAD

**Issue by jzck** [ziglang/zig#2476]
When mistyping string literrals as `\xN` instead of `\xNN` I noticed a "bug in the compiler.

minimal example:
```
//main.zig
const A = "\x0";
```

```
$ zig build-exe main.zig
Assertion failed. This is a bug in the Zig compiler.
???:?:?: 0x7f2bf3d6b3b9 in ??? (???)


???:?:?: 0x7f2bf3d0e884 in ??? (???)


Segmentation fault (core dumped)
```

**Comment by SamTebbs33** [comment]
I'm taking a look at this, what's the intended outcome from using `"\x0"`? (tokenisation error etc.)?

**Comment by andrewrk** [comment]
Tokenization error, expected digit, found double quote
