### ISSUE TITLE
translate-c cannot find assert.h

### ISSUE THREAD

**Issue by bbodi** [ziglang/zig#2488]
Hi all,

I tried to translate this c code to zig: 
```c
#include <assert.h>
int main() {
    assert(1 <= 4);
    return 0;
}
```
But it can't find assert.h.
```
> zig translate-c test.c
test.c:1:10: error: 'assert.h' file not found
#include <assert.h>
```
I checked and I have assert.h installed in /usr/include.
What other steps do I have to make to make it work?
```
> zig version
0.4.0
```
```
> uname -ra
Linux sharp-VirtualBox 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Thanks!

**Comment by daurnimator** [comment]
> I have assert.h installed in /usr/include.
> What other steps do I have to make to make it work?

You need to pass `-isystem /usr/include`

**Comment by bbodi** [comment]
Thanks a lot!

**Comment by andrewrk** [comment]
Was there an error note saying to try linking libc? `--library c`

**Comment by bbodi** [comment]
No, the only output was this:
```
> zig translate-c test.c
test.c:1:10: error: 'assert.h' file not found
#include <assert.h>
```

**Comment by ykmnkmi** [comment]
@andrewrk there's no error note about linking to `libc`. 0.11.0.

**Comment by nektro** [comment]
`zig translate-c repro.c` works. please visit a [Community](https://github.com/ziglang/zig/wiki/Community) if you are having further troubles and we'd all be happy to help :)
