### ISSUE TITLE
segmentation fault with mem.Allocator = undefined

### ISSUE THREAD

**Issue by komuw** [ziglang/zig#2495]
**uname -ra:**
Darwin Kernel Version root:xnu-3789.73.27~1/RELEASE_X86_64 x86_64

**zig version:**
0.4.0+057a5d48

I wanted to know how allocators work so I created the following program;
```zig
const std = @import("std");
const warn = std.debug.warn;
const mem = std.mem;

// Taken from; https://github.com/ziglang/zig/blob/057a5d4898f70c6a8169c99375fbb8631e539051/test/standalone/brace_expansion/main.zig#L19
var global_allocator: *mem.Allocator = undefined;

pub fn main() !void {
    var list = std.ArrayList(i32).init(global_allocator);
    defer list.deinit();

    try list.append(1);
    // warn("list: {}", list);
}
```

**zig fmt . && zig build-exe main.zig && ./main**
```sh
[1]    26176 segmentation fault  ./main
```

I do not know if `var global_allocator: *mem.Allocator = undefined;` should work, but even if it shouldn't; I would expect a compile error instead of segfault

**Comment by andrewrk** [comment]
There is no plan to make this a compile error. How would the compiler know the global variable was undefined? It could have been changed anywhere.

On the other hand it is planned to have the runtime crash from branching on an undefined value easier to debug. #63
