### ISSUE TITLE
Freeing memory multiple times without error

### ISSUE THREAD

**Issue by ducdetronquito** [ziglang/zig#2498]
Hello !

Currently learning how to manage structures allocated on the heap with Zig, I just came across a behavior that feels weird to me: I can free memory multiples times without a warning/error.

```zig
const std = @import("std");
const warn = std.debug.warn;
const allocator = std.debug.global_allocator;

const Person = struct {
    name: []const u8,
};

pub fn main() !void {
    var person = try allocator.create(Person);
    person.name = "Donald Duck";
    warn("My name is {}\n", person.name);

    allocator.free(person.name);
    warn("My name is still {}\n", person.name);

    allocator.free(person.name);
    warn("My name is always {}\n", person.name);
}
```

This code is able to compile and run without any error:

```bash
$ zig run main.zig
My name is Donald Duck
My name is still Donald Duck
My name is always Donald Duck
```

Is this a normal behavior (which I have not understood yet), or is this really a bug ?

Have a good day ! 😉

**Comment by daurnimator** [comment]
One thing that *is* missing is that `.free` in debug mode should set the memory to `undefined`.

**Comment by ducdetronquito** [comment]
Hi @gamester0 !

I was trying to rebuild the code example available in the Zig documentation (Cf: https://ziglang.org/#Manual-memory-management) but without using `std.fmt.allocPrint`. That's why I tried to free my struct field instead of the struct itself.

I wasn't expected error at compile time, but I was definitely expecting one at runtime when freeing a second time. 


@daurnimator : Does this means that I should have printed something like `My name is still undefined` the second time I freed `person.name` ?

**Comment by gamester0** [comment]
My bad @ducdetronquito. Also, I'm realizing that allocator.create is paired with allocator.destroy. You'd get a compile error if you did allocator.free(person).

You're right that C would complain when using its general purpose allocator (malloc). Same with Zig but you'll get a much more detailed error. But std.debug.global_allocator is very simple, it's just a bit of static global memory IIRC meant for tests I believe.

**Comment by SamTebbs33** [comment]
You're trying to free something that is in in static memory (the constant string) within the binary itself so freeing it doesn't make any sense.

**Comment by daurnimator** [comment]
> @daurnimator : Does this means that I should have printed something like `My name is still undefined` the second time I freed `person.name` ?

You should be getting `My name is still \xaa\xaa\xaa\xaa\xaa\xaa\xaa`. And if you ran under `valgrind` it would yell at you and tell you where the issue is.
