### ISSUE TITLE
Imported `use @cImport` hangs forever

### ISSUE THREAD

**Issue by Beefster09** [ziglang/zig#2503]
OS: Windows 10 - 64-bit
Zig Version: pre-built master from today

I managed to isolate the problem I was having to a minimal piece of code that causes the bug:

main.zig

```
const c = @import("c.zig");
const warn = @import("std").warn;

pub fn main() !void {
    var x = c.thing(42);
    warn("Success!");
    warn(x);
}
```

c.zig

```
use @cImport({
    @cInclude("thing.h");
});
```

thing.h

```
int thing(int x) {
    return x * 69;
}
```

It's possible this is a windows-only bug

If the @cImport is inlined, the bug no longer occurs and errors are reported as expected, even if `use`d.

```
const c = @cImport({@cInclude("thing.h");});
const warn = @import("std").warn;

pub fn main() !void {
    var x = c.thing(42);
    warn("Success!");
    warn(x);
}
```

The bug also does not occur if you remove all of the `@cInclude`s in `c.zig`. The bug still occurs if the cInclude includes a file that does not exist.

**Comment by Beefster09** [comment]
I think I may be mistaken. Maybe the compiler is just much slower than I expected? Yay for the halting problem?

Are there options to see what's going on without dumping all the gory details of parsing/tokenization?

**Comment by wilsonk** [comment]
This example appears to work on Linux, Windows10 and Mac OSX Mojave with master branch as of today. Works whether inlined or not. Ok to close?
