### ISSUE TITLE
Adding include and library paths when using zig build

### ISSUE THREAD

**Issue by kavika13** [ziglang/zig#2536]
I'm trying to build the Tetris example on Windows. The dependencies (libpng, libepoxy, glfw, etc) are not installed globally on my box, nor do I want them to be.

Should I be modifying build.zig to include the library and header paths? That doesn't seem optimal (unless the tetris project gets modified to include the headers/libs for those inside the project dir, in which case that should be an upstream modification).

Normally you can add additional compiler flags in a build system, but I'm not seeing anything like that in Zig Build. I see `-isystem` on the compiler itself, but not a way to pass that flag on to it from zig build.

This seems like something that could also be "solved" by a package manager, but we're talking about generic C toolchain compatibility here, so I still think it would be important to support this mode, too.

Sorry if this is an existing ticket. Couldn't find one after like 15 minutes of looking :)

Edit: Seems like there's a lot of related conversation here: #2041

**Comment by merlynmg** [comment]
Seems like there's a lot of related conversation here: https://github.com/ziglang/zig/issues/2041

**Comment by andrewrk** [comment]
> I'm trying to build the Tetris example on Windows. The dependencies (libpng, libepoxy, glfw, etc) are not installed globally on my box, nor do I want them to be.

The honest answer here is to sit tight until the package manager (#943) is available.

I see that you mentioned this:

> This seems like something that could also be "solved" by a package manager, but we're talking about generic C toolchain compatibility here, so I still think it would be important to support this mode, too.

You can expose options to zig build like this:
https://github.com/ziglang/zig/blob/2c0280ba085893984007706fb40c7b291f43074d/build.zig#L86

This could be an include path for example.
