### ISSUE TITLE
[zig fmt] incorrect error reported for invalid line endings

### ISSUE THREAD

**Issue by emekoi** [ziglang/zig#2549]
`zig fmt` reports `error: Expected test, comptime, var decl, or container field, found Invalid` when it encounters a CRLF line ending. this error message isn't very clear and should be changed to a more specific error message. i'm not sure about special casing certain formatting errors though.

**Comment by andrewrk** [comment]
It's also planned to make `zig fmt` auto fix CRLF endings, tabs, source encodings other than UTF-8, etc. That would solve this problem as well.

**Comment by emekoi** [comment]
closed in 4f43a4b
