### ISSUE TITLE
zig langref command

### ISSUE THREAD

**Issue by bugabinga** [ziglang/zig#2550]
```sh
usage: zig langref
prints the zig language reference to std out
```

## Motivation

Zig ships a very useful `langref.html` document, but it needs a browser to view.
It would be neat to be able to pipe the langref to vim/less/grep...
I do not think this is a high priority issue.
But I do think this is a nice candidate for the self-hosted zig compiler part and an
easy issue for zig beginners to jump in.

## Alternatives

The langref could also be (at some point) distributed as part of the zig man pages.
Also, lynx/w3m might render the `langref.html` just fine. 

## Implementation

There are some open questions that need resolving:

- Should the command `zig langref` convert the shipped `langref.html` at run time to ANSI Escape Codes + Content?
- Or should the output of the command be compiled into the zig executable at build time?
- How to do ANSI Escape Codes on Windows?
- Automatically pipe to some pager?

**Comment by Hejsil** [comment]
Man page is probably the correct thing to ship with a compiler. Related #715
