### ISSUE TITLE
.a libraries do not include compiler_rt

### ISSUE THREAD

**Issue by LemonBoy** [ziglang/zig#2551]
Reported by @dm1try in #2526 

The use of `__zig_probe_stack` requires the `compiler_rt` otherwise trying to link the library with a non-Zig object will always fail.

**Comment by shawnl** [comment]
What if the compiler links against libgcc?

**Comment by andrewrk** [comment]
Here's the current way to do that:

```
  --bundle-compiler-rt [path]  for static libraries, include compiler-rt symbols
```

**Comment by andrewrk** [comment]
> What if the compiler links against libgcc?

zig's compiler_rt.a is compatible with libgcc. it exports weak symbols, allowing them to get overridden by libgcc, but the extra ones that libgcc is missing will be provided.

**Comment by andrewrk** [comment]
@LemonBoy do you think we should unconditionally ship .a libraries with compiler_rt? I think it would be fine. Even if libfoo.a and libbar.a both had compiler_rt in them, I think it should work fine. Maybe that can be the default and there could be an option to omit it?

**Comment by daurnimator** [comment]
Duplicate of #1993
