### ISSUE TITLE
Misleading unreachable code error

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#2558]
Through some awkward refactoring I ended up with something like the following:
```
const std = @import("std");
pub fn main() !void {
    defer std.debug.warn("text");
    return blk: {
        return error.Error;
    };
}
```
Normally the compiler would complain that the first return statement is unreachable, but in this case it gives this very confusing error message:

```
/tmp/D/main.zig:3:11: error: unreachable code
    defer std.debug.warn("text");
          ^
```
Only after removing the defer statement is the actual problem exposed:
```
/tmp/D/main.zig:4:5: error: unreachable code
    return blk: {
    ^
```

This is not an issue in the following code:
```
const std = @import("std");
pub fn main() void {
    defer std.debug.warn("defer");
    const a = blk: {
        return;
    };
}
```
```
/tmp/D/main.zig:4:5: error: unreachable code
    const a = blk: {
    ^
```

**Comment by nektro** [comment]
after fixing `error: unused block label` and `error: expected 2 argument(s), found 1` this now compiles and runs with the output

```
texterror: Error
/test.zig:6:9: 0x229a8f in main (test)
        return error.Error;
        ^
```
