### ISSUE TITLE
values of type 'comptime_int' must be comptime known

### ISSUE THREAD

**Issue by fen** [ziglang/zig#2559]
Hi, I'm new to zig and while porting some code I did something similar to this,

```zig
const Vec = struct {
    x: f32,
    y: f32,
    z: f32,
};

pub fn main() void {
    var o = Vec{ .x = 1, .y = 1, .z = 1 };
    var x = someMethod(o);
}

fn someMethod(o: Vec) f32 {
    return if (o.x == 0) 0 else if (o.y > 0) 2 else -2;
}
``` 

and got this error

```
C:\tmp\t4\main.zig:13:33: error: values of type 'comptime_int' must be comptime known
    return if (o.x == 0) 0 else if (o.y > 0) 2 else -2;
                                ^
```
Got confused why the expression is evaluated as comptime, and wanted some guidance on how this should be done instead.

zig (version: master 2019-05-25)

Regards

**Comment by tgschultz** [comment]
I think this is because the result of the `if` expressions are not explicitly typed. It's a known issue and can be worked around by casting the literals to `f32`:
```
const Vec = struct {
    x: f32,
    y: f32,
    z: f32,
};

pub fn main() void {
    var o = Vec{ .x = 1, .y = 1, .z = 1 };
    var x = someMethod(o);
}

fn someMethod(o: Vec) f32 {
    return if (o.x == 0) f32(0) else if (o.y > 0) f32(2) else f32(-2);
}
```

I will edit this response with the reference to the issue.

**Comment by fen** [comment]
Thank you for the response, the work around works great.
