### ISSUE TITLE
copy_file_range syscall support on Linux

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2563]
http://man7.org/linux/man-pages/man2/copy_file_range.2.html

**Comment by andrewrk** [comment]
Related: #1907

**Comment by shawnl** [comment]
Write up on implementing this (with WIP patch) https://github.com/ziglang/zig/pull/2592#issuecomment-500153387

**Comment by andrewrk** [comment]
Implemented by @LemonBoy in  #6516.
