### ISSUE TITLE
design flaw: operating system page size is not always comptime known, but std lib assumes it is

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2564]
There is no longer just one page size; "huge pages" are well supported by modern processors and operating systems.

_Originally posted by @daurnimator in https://github.com/ziglang/zig/pull/2527_

**Comment by shawnl** [comment]
Yes, but many systems make them transparent so they don't break things.

**Comment by LemonBoy** [comment]
> Yes, but many systems make them transparent so they don't break things.

It's [not really](https://git.musl-libc.org/cgit/musl/commit?id=b20760c02318fa6da228587c401a8b2bb22a1aab) transparent if you consider other architectures.

**Comment by andrewrk** [comment]
> user space can only know it at execution time from the aux vector

I was afraid of this being the case. This is so inconvenient that I might consider making the "page size" part of the target. I don't know yet. This will be an important decision for the limitations & capabilities of the standard library.

**Comment by shawnl** [comment]
@LemonBoy I just said that cause i'm using ppc64le and the large page sizes are automatic, but 4096 still works. That is the default config.

> user space can only know it at execution time from the aux vector

This could be used with symbol multi-versioning, but it definitely is a pain.

**Comment by daurnimator** [comment]
Maybe all we need is the minimum page size?

**Comment by andrewrk** [comment]
Solution: `std.mem.page_size` is the comptime-known minimum page size. Whether or not to rename it to "minimum_page_size" or not is a separate question.
