### ISSUE TITLE
while loop obscures return type in function

### ISSUE THREAD

**Issue by GreyDodger** [ziglang/zig#2574]
zig run this code...

```
const err = error{ errorBlah };

fn funcitonBlah(str: []const u8) ![]const u8 {
    var i = str.len - 1;
    while (i >= 0) : (i -= 1) {
        if(str[i] == '.') {
            return "sajdkflsdjfl";
        }
    }
    return err.errorBlah;
}

pub fn main() !void {
    _ = try funcitonBlah("sjdfklsdjfl");
}
```

and you get...

```
C:\prg\test_zig_bug\code.zig:3:35: error: function with inferred error set must return at least one possible error
fn funcitonBlah(str: []const u8) ![]const u8 {
```

zig is unable to see I am returning an error on the last line of functionBlah unless I take out the while loop

zig version
0.4.0+b660134a

**Comment by daurnimator** [comment]
> zig is unable to see I am returning an error on the last line of functionBlah unless I take out the while loop

Your while loop never ends. `i` is unsigned, so the condition of `i>=0` is always true: so the error return is unreachable.

**Comment by GreyDodger** [comment]
ah, thanks
