### ISSUE TITLE
Hard to debug link phase when the link is skipped because the result was cached

### ISSUE THREAD

**Issue by kavika13** [ziglang/zig#2577]
When debugging things like linker options, it can be annoying to have to repeatedly delete the cache each time just to get `--verbose-link` (and things like it) to output anything.

You can disable the caching with `--cache off`, but that alters the output command line so might not get you the same results that you were looking for. That option can also sometimes be blocked by buggy behavior (e.g. https://github.com/ziglang/zig/issues/2073#issuecomment-473727571).

It could be useful to have some way to force the link stage (and other stages?) to pretend to run, even if it isn't actually run due to caching.

Maybe adding a `--dry-run` flag would help resolve this? It would go through absolutely all the steps to construct the options, spit out the commands it will use, but skip the part where it does the actual work.

It might be useful to do this with more than just the linker step, if it is even applicable, and if it's not a huge refactoring pain. I'll leave it to someone else who knows the compiler better to decide if those parts would even make sense :)

**Edit**: It might make sense (and might be easier) not to build extra functionality for some `--dry-run` mode, and instead to just print out the following extra information when using `--verbose-link`:

```
Linking will not be run because the results were already in the cache at: <filename>
Linker command that that would have been run:
lld ... <command line here>
```

**Comment by kavika13** [comment]
I could also see that someone might want "dry run" to obey caching, so they could debug whether caching was working properly. Maybe it would make sense to have a `--dry-run` and `--cache ignore` combo? Or maybe not worry about it until someone files a ticket for an actual problem they're running into? :)

**Comment by kavika13** [comment]
I edited the title and added a second proposal. Making this ticket more problem oriented because there could be different solutions than the one I initially proposed.

**Comment by andrewrk** [comment]
I'm not planning to do this.
