### ISSUE TITLE
Any progress or information about networking?

### ISSUE THREAD

**Issue by ThatTonybo** [ziglang/zig#2590]
Does Zig have any implementation so far for http (client or server) or websockets?

I'm looking into building some projects than need to be able to have both accessible, I don't even mind if they're experimental or have to be imported from somewhere.

ps. Absolute beginner to Zig, still learning the ins and outs, are there any guides available?

**Comment by emekoi** [comment]
see #910 for info on networking and you can find a language reference [here](https://ziglang.org/download/) depending on you version of zig.

**Comment by daurnimator** [comment]
See #2007

**Comment by ThatTonybo** [comment]
> 
> 
> see #910 for info on networking and you can find a language reference [here](https://ziglang.org/download/) depending on you version of zig.



> 
> 
> See #2007


Neither of those really make any sense to me, is there any better information available?

**Comment by andrewrk** [comment]
This is a great question for the other community areas: https://github.com/ziglang/zig/wiki/Community
