### ISSUE TITLE
remove the deprecated `use` syntax from the language

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2591]
Now that #2014 is solved, and `zig fmt` is auto fixing everybody's code, we can wait 1 release cycle and then delete the `use` keyword.

**Comment by emekoi** [comment]
commenting here because the original issue was closed. is there a specific reason that we want to discourage the use of `use` in code?

**Comment by hryx** [comment]
`usingnamespace` (née`use`) is the only language feature which gives the author the power to introduce identifiers into the current scope without a visible declaration. This has invisible side effects, crowds the symbol namespace, and generally seems counter to Zig's clarity-over-brevity virtue. I think its use warrants discouragement and the uglier name is justified.

(I still don't quite grasp why it needs to exist at all ([see my unanswered question here](https://github.com/ziglang/zig/issues/2014#issuecomment-478285678)), but the issue has been settled and this ticket is for tracking work of an already-accepted change.)

**Comment by emekoi** [comment]
my main problem with this is that is makes #1214 seem uglier, which seems to imply that it's going to be not accepted.
