### ISSUE TITLE
Unable to use epoll_create1

### ISSUE THREAD

**Issue by jinankjain** [ziglang/zig#2596]
This might be stupid but I am trying to use epoll_create1 API from std.os and I keep getting this error. By briefly inspecting zig source code I can see that the API is defined in `std/os.zig` but then also I am not able to do function call. Can someone help me with that?

```sh
/home/jinank/learning/main.zig:73:26: error: container 'std.os' has no member called 'epoll_create1'
    var epoll_fd = try os.epoll_create1(0);
                                   ^
```

This might be some newbie mistake that I am doing.

**Comment by andrewrk** [comment]
can you make sure you're on the latest master build of zig? what's your `zig version`?

**Comment by jinankjain** [comment]
I did build zig yesterday 0.4.0+163a8e98

**Comment by andrewrk** [comment]
that's a version before std.os.epoll_create1 existed. I think this will be solved if you update

**Comment by jinankjain** [comment]
thanks that worked!
