### ISSUE TITLE
Can't import standard library modules

### ISSUE THREAD

**Issue by Tembocs** [ziglang/zig#2603]
I'm trying to compile and run the following.

```
const std = @import("std");
const File = std.fs.File;
const warn = std.debug.warn;
const path = std.fs.path;

pub fn main() void {
    warn("Reading here.");

    if (path.isAbsolute("../src")) {
        warn("Absolute.");
    } else {
        warn("Not absolute.");
    }
}
```

This give the following  error message: 

```
error: container 'std' has no member called 'fs'
const path = std.fs.path;
```
What am I missing?

**Comment by emekoi** [comment]
what version of zig are you using?

**Comment by Tembocs** [comment]
@emekoi version 0.4.0.

**Comment by emekoi** [comment]
`std.fs.*` and a lot of the newer modules are only available on development versions. if you're going to continue using v0.4.0 i would suggest looking at the `std` directory for the available modules as zig doesn't have docs for things like that right now.

**Comment by andrewrk** [comment]
You gotta look at the corresponding documentation and source code for the version you're using. Either use the 0.4.0 docs & std lib source code for reference, or switch to the master builds of zig.
