### ISSUE TITLE
CMake configuration problems

### ISSUE THREAD

**Issue by Tembocs** [ziglang/zig#2608]
I'm trying to build Zig on Ubuntu 19.04 x64 using LLVM/Clang 8.0.0 and get the following warning during CMake configuration.
```
WARNING: Target "zig" requests linking to directory "/home/~/clang+llvm-8.0.0-x86_64-ubuntu-18.04/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "zig0" requests linking to directory "/home/~/clang+llvm-8.0.0-x86_64-ubuntu-18.04/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "compiler" requests linking to directory "/home/~/clang+llvm-8.0.0-x86_64-ubuntu-18.04/lib".  Targets may link only to libraries.  CMake is dropping the item.
```

After this running ```make install``` gives a lot of errors in the lines of the following:

```
error: missing binary operator before token "(" 
#if !defined(_SIZE_T) || __has_feature(modules)

error: ‘size_t’ has not been declared
extern int strfromd (char *__dest, size_t __size, const char *__format,
```

What am I missing?

**Comment by andrewrk** [comment]
Hi, I'm closing this because I don't have any clue what's gone wrong for you, but I'm confident that Zig builds from source on Ubuntu because it's tested during every CI build.

Sorry it's not working for you, please let me know if you figure it out, and in the meantime consider using the prebuilt binaries available on ziglang.org.

**Comment by AidanWelch** [comment]
To people coming on this error later, I resolved it through install the packages(but for clang-19) listed in [Troubleshooting Build Issues](https://github.com/ziglang/zig/wiki/Troubleshooting-Build-Issues).  This was unexpected to me as I had run the script which should install all packages, but `liblld-19-dev` was not installed.
