### ISSUE TITLE
@cDefine with empty second argument fails

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2612]
From docs:

> To define without a value, like this:
> ```C
> #define _GNU_SOURCE
> ```
> Use the void value, like this:
> ```zig
> @cDefine("_GNU_SOURCE", {})
> ```

However trying this results in:

```
test.zig:2:21: error: expected type '[]const u8', found 'void'
    @cDefine("FOO", {});
                    ^
```

**Comment by timonkruiper** [comment]
Isn't this a typo in the docs? 

When doing `@cDefine("FOO", "")` we end up with `#define FOO` in the generated cimport.h file as expected.

**Comment by daurnimator** [comment]
I'm unsure if the docs are wrong or the compiler is wrong. I think @andrewrk needs to clarify.

**Comment by andrewrk** [comment]
I think it's a regression. `@cDefine` is generally supposed to support any type that could reasonably be translated into a `#define` and given to the C language.
