### ISSUE TITLE
Passing options to zig compiler

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2613]
With C, you can pass in constants to the build process via `-D` on command line. This can be used for configuring the build artifact in different ways.

I can't seem to find the equivalent in zig. e.g. I might expect that `zig build-lib -Dmyarg=foo` makes something show up in somewhere like `builtin.arguments`.

**Comment by emekoi** [comment]
another solution would be to have a file with the configuration defined in it. passing args would be the equivalent on changing values in the configuration file. you could then `@import` the file and use the values defined in it.

**Comment by Hejsil** [comment]
Related #226

**Comment by daurnimator** [comment]
Thanks @hejsil. Closing as dupe of #226
