### ISSUE TITLE
fastcc calling convetion does not support var args

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2619]
from https://llvm.org/docs/LangRef.html#calling-conventions

> This calling convention does not support varargs

and yet the zig compiler still uses fastcc for var args functions.

```
33344   call fastcc void @std.debug.warn.132(float %0), !dbg !12799
```

**Comment by andrewrk** [comment]
You're mixing up LLVM's notion of var args and zig's. The llvm function call you pasted above has exactly 1 llvm argument.
