### ISSUE TITLE
ability to convert between []u8 and packed structs at compile time

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#262]
packed structs have a well defined in-memory representation. therefore it should be possible to access the in-memory representation and modify it, and then read the values back out, like this:

```zig
const std = @import("std");
const assert = std.debug.assert;

const Foo = packed struct {
    a: u4,
    b: u4,
};

comptime {
    var foo: Foo = undefined;
    const slice = @sliceToBytes(((*[1]Foo)(&foo))[0..1]);
    slice[0] = 0x13;
    assert(foo.a == 0x1);
    assert(foo.b == 0x3);
}
```

**Comment by thejoshwolfe** [comment]
is there a compile-time endianness?

**Comment by andrewrk** [comment]
Ah right good point. I wonder if it makes sense to have packed structs specify endianness. I don't think we would specify a compile-time endianness.

**Comment by andrewrk** [comment]
Wait, actually this is not a problem. When you compile, you compile for a specific target, and that target has an endianness. The compile-time endianness will be the same as the target.
