### ISSUE TITLE
mingw support

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#2633]
Using this file:

https://github.com/ziglang/zig/blob/fb5e03b983f7a7a776b4f67f2426da6b7ecfdb0c/example/hello_world/hello_libc.zig#L1-L13

My LibC is here:

~~~
C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw
~~~

Trying these commands:

~~~sh
zig build -isystem 'C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw\include'
zig build -isystem /usr/x86_64-w64-mingw32/sys-root/mingw/include
~~~

Gives this result:

~~~
zig-windows-x86_64-0.4.0+ddfab40e\lib\zig\std\special\build_runner.zig:149:33:
error: container 'std.special' has no member called 'build'

zig-windows-x86_64-0.4.0+ddfab40e\build.zig:1:11: error: C import failed

zig-windows-x86_64-0.4.0+ddfab40e\build.zig:1:11: note: libc headers not
available; compilation does not link against libc

zig-windows-x86_64-0.4.0+ddfab40e\zig-cache\o\wV_ehfitres0zgXMEm3tGhqQZyUgY2EJ6y
Vfwa4tSGtH5_Z7pmbxBb9JCtoo1yhD\cimport.h:2:10: note: 'stdio.h' file not found
~~~

**Comment by daurnimator** [comment]
You need to pass `--library c`

**Comment by cup** [comment]
@daurnimator nope, no effect.

**Comment by daurnimator** [comment]
What target are you using?
I don't think we have support for mingw right now.

**Comment by cup** [comment]
https://github.com/ziglang/zig/pull/1542

**Comment by daurnimator** [comment]
I think #1542 was about getting the zig *compiler* to work on mingw. Not for targeting mingw with zig code?

**Comment by cup** [comment]
:|

**Comment by daurnimator** [comment]
Have you tried providing a libc file? (see `zig libc`)
Does mingw use gnu ABI? or msvc? or does it have its own?
I expect we'll need to add a new target (see `zig targets`) for mingw.

**Comment by andrewrk** [comment]
cygwin is not supported yet. see #751

**Comment by daurnimator** [comment]
cygwin != mingw.
https://stackoverflow.com/a/792142/282536

**Comment by cup** [comment]
@andrewrk yeah, @daurnimator is right. this should be reopened.

**Comment by cup** [comment]
@andrewrk yeah, @daurnimator is right. this should be reopened.

The compiler that produces Cygwin reliant executables is:

~~~
x86_64-pc-cygwin-gcc
~~~

the one Im using produces Windows native executables:

~~~
x86_64-w64-mingw32-gcc
~~~

**Comment by andrewrk** [comment]
> My LibC is here:
> 
> ```
> C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw
> ```

this has "cygwin" in the path, and it's not cygwin?

**Comment by cup** [comment]
@andrewrk nowadays Cygwin is just the environment itself, like Bash and so on.

Cygwin environment offers these compilers:

compiler                 | note
-------------------------|--------------
`x86_64-w64-mingw32-gcc` | 64-bit native
`i686-w64-mingw32-gcc`   | 32-bit native
`x86_64-pc-cygwin-gcc`   | 64-bit cygwin
`i686-pc-cygwin-gcc`     | 32-bit cygwin

**Comment by emekoi** [comment]
mingw works just fine. i build master using mingw64 on a regular basis.

**Comment by cup** [comment]
@emekoi we are talking about using `zig.exe` to compile `hello.zig`

**Comment by emekoi** [comment]
do you have CC defined or cc.exe in your path?

**Comment by cup** [comment]
@emekoi I am finding it difficult to interact with you because it seems you have skipped reading the previous comments and have only read the title.

**Comment by emekoi** [comment]
sorry GitHub wasn't showing your reply. we're talking about the same thing. when you build zig on master, part of the build process is building zig code that links to libc and linking to that. if zig can build from master on mingw that should mean that zig can target mingw just fine.

**Comment by cup** [comment]
@emekoi with all due respect, you just saying it works it a huge gaping chasm
from it actually working:

~~~
$ cat libc.txt
include_dir=C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw\include
sys_include_dir=C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw\include
crt_dir=C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw\lib
static_crt_dir=
kernel32_lib_dir=
msvc_lib_dir=

$ zig libc libc.txt
msvc_lib_dir may not be empty for windows
~~~

> The directory that contains `vcruntime.lib`. Only needed when targeting MSVC
> on Windows.

https://ziglang.org/download/0.4.0/release-notes.html#Libc-Detection

So unless you can provide some code examples I am not convinced.

**Comment by emekoi** [comment]
can you run `zig targets` and show what zig thinks your native target is?

**Comment by cup** [comment]
~~~
$ zig targets | grep native
  x86_64 (native)
  windows (native)
  msvc (native)
~~~

**Comment by emekoi** [comment]
are you using a zig compiler from the website or did you compile it yourself?

**Comment by cup** [comment]
https://ziglang.org/builds/zig-windows-x86_64-0.4.0+ddfab40e.zip

**Comment by daurnimator** [comment]
12:40:25 | <emekankurumeh[m]> | the target is "<arch>-windows-gnu"

@cup could you try passing `-target x86_64-windows-gnu`?

**Comment by cup** [comment]
@daurnimator nope. these all fail:

~~~
zig build-exe hello.zig -target  x86_64-windows-gnu --library c --libc libc.txt
zig build-exe hello.zig -target  x86_64-windows-gnu --library c
zig build-exe hello.zig -target  x86_64-windows-gnu
~~~

**Comment by emekoi** [comment]
can you try `zig build-exe -target x86_64-windows-gnu --libc libc.txt hello_libc.zig --library c -isystem $include_dir` where `include_dir` is the same one from your libc file?

**Comment by cup** [comment]
Ok this file:

~~~
crt_dir=C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw\lib
include_dir=C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw\include
static_crt_dir=C:\cygwin64\lib\gcc\x86_64-w64-mingw32\7.4.0
sys_include_dir=C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw\include
kernel32_lib_dir=
msvc_lib_dir=
~~~

with this command:

~~~sh
zig build-exe hello_libc.zig \
--library c \
--libc libc.txt \
-target x86_64-windows-gnu \
-isystem 'C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw\include'
~~~

works. perhaps a more graceful way is available to do this?

**Comment by emekoi** [comment]
the `isystem` flag shouldn't be needed. i'll try to come up with a patch to fix that.

**Comment by cup** [comment]
@emekoi any update?

**Comment by andrewrk** [comment]
Notable commit: 682a29aefde09e31247088144a7e543daefb63f4

> Zig supports both Linux and Windows natively. Those are the main use cases we are focusing on. Happy to accept mingw patches if they are non-invasive, but we will not be hampering progress on the main use cases with failing mingw CI builds.
