### ISSUE TITLE
multiple lvalues.

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2638]
I don't have strong opinions about this one way or another, but I think it is a syntax that should be considered, especially if multiple return values are ever considered:
```
export fn multiple_lvalues(num: i32) i32 {
    var f: i32 = undefined;
    var g: i32 = undefined;
    f = g = num;
    return f;
}
```

**Comment by daurnimator** [comment]
How is this related to multiple return values? If anything I'd say it's incompatible with them

**Comment by shawnl** [comment]
It isn't really related, but the code would be in the same place. They are compatible.

```
a1, a2 = b1, b2 = producer(call);
```

**Comment by shawnl** [comment]
It appears that this is a single line change, `BinOpChainOnce` => `BinOpChainInf` here:

https://github.com/ziglang/zig/blob/12b2950bf294b3cfda0616b2e71b739cbda684d9/src/parser.cpp#L1091

**Comment by daurnimator** [comment]
I don't think this is a good idea, reading code I always expect an expression on the right hand side of an equals `foo = `. As assignment doesn't return anything, I think it would be misleading to allow `foo = bar = `.
