### ISSUE TITLE
move the panic codegen to IR pass 2 rather than LLVM IR gen

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2649]
This is sort of an implementation detail, but I think this is going to be an important step towards advanced control flow analysis features - particularly safety check elision.

Currently some Zig IR instructions, such as ElemPtr, have safety checks which are implemented in codegen.cpp, directly in LLVM IR. For example, the call to the panic function has no corresponding Zig IR Call instruction; it's generated as part of the LLVM code for ElemPtr.

This makes the panic handler unconditionally compiled into zig build artifacts, because it's treated as a strong entry point. However if safety checks were moved to Zig IR pass 2, then it would integrate cleanly with zig's lazy analysis, and a build artifact which never panicked would not have a panic function.

One nice effect of this would be that simple test cases with build-obj, such as godbolt.org, would not unexpectedly have a bunch of code dealing with panics when no panics are possible.

The other thing that this paves the road for is safety check elision. Once all the safety checks are lowered into Zig IR instructions, a control flow analysis pass could identify dead branches and eliminate them. For example:

```zig
var array1: [10]u8 = something1();
var array2: [100]u8 = something2();
for (array1) |x, i| {
    array2[i] = x + 1;
}
```

In this example, it should be known that inside the loop body, `i < 10`, and therefore `i < 100` as well, and the array bounds check for accessing `array2` can be elided.

The other reason for doing this would be to support a backend besides LLVM.

**Comment by shawnl** [comment]
The DCE you speak of is totally independent, and already done: https://zig.godbolt.org/z/k0YcjR

That said, there are lot of examples like this where it would be nice to be able to remove unused code, such as the TLS startup code. We could also have feature gates, so that a program can explicitly ask that a feature not be used, and if a library asks for it, it would be a compile error.

**Comment by andrewrk** [comment]
I neglected to mention that the dead code elimination discussed in this issue is for debug builds. In these builds we want to compile fast so we skip LLVM optimizations. This godbolt example uses `--release-safe` which enables LLVM optimizations. Idea here would be to have some fast safety check elision code for debug builds to keep debug perf under control.

**Comment by shawnl** [comment]
>  Idea here would be to have some fast safety check elision code for debug builds to keep debug perf under control.

Why not just use `-Og`, (which i think is just `-O1`) for debug mode?

**Comment by andrewrk** [comment]
That's certainly something to try. My understanding is that would not do the optimization passes that would elide safety checks. Also this:
>The other reason for doing this would be to support a backend besides LLVM.

**Comment by andrewrk** [comment]
Done in ec4953504a07f3025d5f32344180dd9b6a4de8ae. Not planned for stage1.
