### ISSUE TITLE
Compiler error for a function missing a `return` is confusing

### ISSUE THREAD

**Issue by CurtisFenner** [ziglang/zig#2653]
When a function is missing a `return` on some path, like the following function `xy`, the error message is rather confusing: 
```zig
pub fn xy(n: u8) u8 {
    if (n == 1) {
        return 1;
    } else if (n == 2) {} else {
        return 2;
    }
}

pub fn main() void {
    _ = xy(1);
}
```

```
xy.zig:1:21: error: expected type 'u8', found 'void'
pub fn xy(n: u8) u8 {
                    ^
xy.zig:1:18: note: return type declared here
pub fn xy(n: u8) u8 {
                 ^
```

This is confusing because

* there are no `void`s in this program, so how did it "find" it
* the place the mistake was made is actually in the middle/end of the function, rather than anywhere near the beginning

I think a better error message would be something like

```
xy.zig:4:25: error: function with return type 'u8' does not always return
    } else if (n == 2) {} else {
                        ^

xy.zig:1:18: note: return type declared here
pub fn xy(n: u8) u8 {
                 ^
```

I think the blamed point in the program could be the earliest, deepest single point where inserting a `return` fixes the function.

ie, in a block `{x1; x2; ... ; xn;}` which doesn't definitely return, look for a place in `x1`, then `x2`, and so on. In a branch `c1 | c2 | ... | cn`, if all but one definitely return, blame that one.

However, as a very first step, I think just pointing to the end of the function would be an improvement over pointing to the beginning. (Since there necessarily isn't a `return` statement there, it at least shouldn't be misleading)

**Comment by hryx** [comment]
> error: function with return type 'u8' does not always return

Since there is such a thing as `noreturn`, it actually is more accurate to say the function returns `void` -- however, simply pointing to the offending line would help immensely.

Also, as an amendment to your example, since the `{}` is just an empty block, I think the actual place where a void return would be detected (and pointed out) is the end of the function.

```
xy.zig:7:1: error: returning 'void' from a function with return type 'u8'
}
^

xy.zig:1:18: note: return type declared here
pub fn xy(n: u8) u8 {
                 ^
```

**Comment by daurnimator** [comment]
One idea to add might be: if there is *any* `return` in a function, then *all* reachable code must end in a `return`.
