### ISSUE TITLE
zig fmt deletes comments in array literals

### ISSUE THREAD

**Issue by thejoshwolfe** [ziglang/zig#2658]
before:
```
                var individuals = try std.mem.dupe(allocator, Individual, [_]Individual{
                    Individual{ .species = Species.human, .abs_position = makeCoord(7, 14) },
                    // Individual{ .species = Species.orc, .abs_position = makeCoord(3, 2) },
                    // Individual{ .species = Species.orc, .abs_position = makeCoord(5, 2) },
                    // Individual{ .species = Species.orc, .abs_position = makeCoord(12, 2) },
                    // Individual{ .species = Species.orc, .abs_position = makeCoord(14, 2) },
                });
```
after:
```
var individuals = try std.mem.dupe(allocator, Individual, [_]Individual{Individual{ .species = Species.human, .abs_position = makeCoord(7, 14) }});
```

**Comment by hryx** [comment]
@thejoshwolfe Can you confirm that your "before" example in the description is also the desired output? I'm responding to the change in https://github.com/ziglang/zig/pull/2744 , which to me does not look like what I'd expect (but does solve the problem of comments being deleted).

**Comment by thejoshwolfe** [comment]
Well, except for the indentation, yes. I desire each of the commented out items to be on their own lines. It would be undesirable for the first comment to move up one line.

**Comment by thejoshwolfe** [comment]
The tests added in https://github.com/ziglang/zig/pull/2744/files/22194efe68a112d6d0688f49bf6340a8a952d47c..0063953d1634ce770ce88519c66e3956832ceb7e look like what i expect.
