### ISSUE TITLE
zig fmt reinterprets `a && b` as `a & &b`

### ISSUE THREAD

**Issue by fengb** [ziglang/zig#2660]
The zig compiler rejects the `&&` operator with a helpful hint:
```
error: `&&` is invalid. Note that `and` is boolean AND.
```

But if we run `zig fmt` on the code, it splits the operator into bitwise-and + addr-of and creates rather confusing error messages:
```
error: integer value 0 cannot be implicitly casted to type '*bool'
```

I think the better solution is:
1. Allow `&&` in the zig fmt parser — it's a common operator on many other languages, while `a & &b` is extremely rare and probably never formatted as `a&&b`
2. Reject `&&` in compiler (current behavior)

This should be similar to the handling of the `||` operator: there's no current ambiguity, `zig fmt` keeps it around without any parse errors, and the compiler helpfully rejects it.
```
error: expected error set type, found 'comptime_int'
note: `||` merges error sets; `or` performs boolean OR
```

**Comment by hryx** [comment]
@Hejsil would it be weird to have an "illegal token" rule in the grammar? That might be one way to address this (though I don't love it)

**Comment by Hejsil** [comment]
@hryx To keep the grammar as simple as possible I don't think we should encode special "error" syntax in it. `&&` is always invalid when we hit the type system (`@typeOf(&a)` is always a ptr, and `&` only works on ints) so I think this is better suited as an implementation detail, where we just detect this error earlier for more human friendly formatting. Stage 1 already rejects [`&&` at the tokenizer level](https://github.com/ziglang/zig/blob/fcc0728a35fe602ff8ad8c28370e901231550dea/src/tokenizer.cpp#L846).

**Comment by fengb** [comment]
I took a look at porting over to `tokenizer.zig` and it's easy enough to [convert to invalid](https://github.com/fengb/zig/commit/495655cdf737c5c92c274c3a815e2414c83cdb72). Unfortunately, the zig tokenizer doesn't have robust error messaging so it still looks rather odd:
```
error: expected Semicolon, found Invalid
```

**Comment by hryx** [comment]
@Hejsil I totally agree. This feels more like a hint this specific compiler can detect and help with, but not something to be formally specified and implemented. Should there be an early-stage linter to detect things like this before the later phase?
