### ISSUE TITLE
allow main to return `!u8`

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#2662]
I think it's common for a program's main function to want 3 types of returns:

1. return success
2. return error with no stacktrace
3. return error with stacktrace

For example, say you implement the program `ls`.  In cases where you detect bad command-line arguments, you may want to print an error message and return an error exit code, but not print a stacktrace, i.e.
```
> ls missing_file
Error: 'missing_file' does not exist
```

But if you got a more critical error, maybe one that represents a bug in the program or an assert failure, you probably do want a stacktrace:
```
> ls foo
ls.zig:123:3: 0x7ff79b7112e9 in main (ls.obj)
    return error.AssertFailed
```

These 3 use cases can be accomodated with a `main` function that has a return type of `!u8`.

```zig
pub fn main() !u8 {
    try allocate(); // causes a stack trace on failure
    if (someNormalError) {
        std.debug.warn("Error: you got some error here");
        return 1; // error exit-code
    }
    return 0; // success
}
```

> NOTE: it looks like the code to implement this will be an extra case in `callMain` in `std/bootstrap.zig`

**Comment by zimmi** [comment]
@marler8997 Can this be closed now that https://github.com/ziglang/zig/pull/2722 is merged?

**Comment by marler8997** [comment]
Yeah
