### ISSUE TITLE
sliceToBytes doesn't take an array as documented

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2670]
From docs:
> `@sliceToBytes(value: var) []u8`
> Converts a slice or array to a slice of u8. The resulting slice has the same pointer properties as the parameter. 

However attempting this I get:
```
error: expected slice, found '[48]u8'
    mem.writeIntLittle(u64, @sliceToBytes(state)[random_prefix.len+1..][0..8], out.len);
                                          ^
```

**Comment by Vexu** [comment]
`@sliceToBytes` was removed from the language in #4516.
