### ISSUE TITLE
InstallArtifact fails on Windows for Shared Libraries

### ISSUE THREAD

**Issue by ErikMcClure** [ziglang/zig#2675]
When buliding a shared library, the compilation works, but installation will fail after the DLL has been copied.

```
Unable to symlink .\lib\ -> feather.dll
error: Unexpected
D:\zig\lib\zig\std\os\windows.zig:401:37: 0x7ff7f4dbaa92 in std.os.windows.CreateDirectoryW (build.obj)
            ERROR.ALREADY_EXISTS => return error.PathAlreadyExists,
```

The problem is that the symlink step should be skipped on windows, and it is skipped [in the normal build process](https://github.com/ziglang/zig/blob/master/std/build.zig#L1599), but not when [calling installArtifact](https://github.com/ziglang/zig/blob/master/std/build.zig#L1772).

This fix for this should be pretty simple, but I have not actually tested to see if this compiles:
```diff
try builder.copyFileMode(self.artifact.getOutputPath(), self.dest_file, mode);
- if (self.artifact.isDynamicLibrary()) {
+ if (self.artifact.isDynamicLibrary() and !self.artifact.target.isWindows()) {
   try doAtomicSymLinks(builder.allocator, self.dest_file, self.artifact.major_only_filename, self.artifact.name_only_filename);
}
````

**Comment by andrewrk** [comment]
Thanks for the report. I added the 0.5.0 milestone which means that I'm going to try to get this issue solved by the next release.

**Comment by squeek502** [comment]
I believe this was fixed by https://github.com/ziglang/zig/pull/3781
