### ISSUE TITLE
Shadowing in C header files

### ISSUE THREAD

**Issue by NBonaparte** [ziglang/zig#2676]
Importing the Wayland client header file (`@cInclude("wayland-client.h")`) results in, among other errors, this:
```
error: redefinition of 'wl_display'
pub fn wl_display_get_registry(wl_display: ?*struct_wl_display) ?*struct_wl_registry {

note: previous definition is here
pub const wl_display = struct_wl_display;
```

This is because in `wayland-client-protocol.h` the argument name is the same as the type:
```
static inline struct wl_registry *
wl_display_get_registry(struct wl_display *wl_display)
```
Many of the inline functions included in the header also exhibit the same issue.

Should `translate-c` have some sort of renaming mechanism to work around this?

**Comment by andrewrk** [comment]
> Should `translate-c` have some sort of renaming mechanism to work around this?

It does have such a mechanism - it seems to not be detecting this situation properly.

**Comment by andrewrk** [comment]
Translate-c is in the middle of a transition from C++ to zig (see #1964), so even though this is a bug in the C++ version, I'm going to try to solve it by putting more effort towards the self-hosted version, which is why I gave it 0.6.0 milestone.

**Comment by daurnimator** [comment]
Fixed in master.
