### ISSUE TITLE
Missing implicit cast to [*c] pointer

### ISSUE THREAD

**Issue by gamester0** [ziglang/zig#2682]
I believe that the following should be made to work. This looks more like a bug than a missing feature to me:

```
pub fn main() void {
    var ptr: [*c]?*u32 = undefined;
    var ptr2: **u32 = undefined;

    ptr = ptr2;
}
```
```
/tmp/E/main.zig:5:11: error: expected type '[*c]?*u32', found '**u32'
    ptr = ptr2;
          ^
/tmp/E/main.zig:5:11: note: pointer type child '*u32' cannot cast into pointer type child '?*u32'
    ptr = ptr2;
          ^
/tmp/E/main.zig:5:11: note: mutable '?*u32' allows illegal null values stored to type '*u32'
    ptr = ptr2;
```

**Comment by andrewrk** [comment]
Did you see the explanation? `note: mutable '?*u32' allows illegal null values stored to type '*u32'`

The implicit casts where C pointers cast to Zig pointers have safety checks to make sure null is not given to a non-nullable pointer. But this implicit cast would lack such a safety check. You can still do an explicit `@ptrCast` however.

**Comment by andrewrk** [comment]
This is basically the same example as this:

```zig
pub fn main() void {
    var ptr: ?*u32 = undefined;
    var ptr2: *u32 = undefined;

    ptr2 = ptr;
}
```

```
/tmp/E/main.zig:5:12: error: expected type '*u32', found '?*u32'
    ptr2 = ptr;
           ^
/tmp/E/main.zig:5:12: note: '?*u32' could have null values which are illegal in type '*u32'
    ptr2 = ptr;
           ^
```

**Comment by gamester0** [comment]
Well this is an implicit cast from a stronger typed Zig pointer to a less strongly typed C pointer. I'm not entirely sure if you noticed that and I'm misunderstanding something, or if you didn't noticed that. Note that this does compile:

```
pub fn main() void {
    var ptr: [*c]*u32 = undefined;
    var ptr2: **u32 = undefined;

    ptr = ptr2;
}
```

**Comment by gamester0** [comment]
I just understood this now, heh. You're right!
