### ISSUE TITLE
gdb thinks bool is always false

### ISSUE THREAD

**Issue by thejoshwolfe** [ziglang/zig#2685]
a.zig:
```zig
pub fn main() void {
    var foo = true;
    @breakpoint();
    @import("std").debug.warn("{}\n", foo);
    foo = true;
}
```

build and gdb:
```
zig build-exe a.zig && gdb ./a -ex run
Reading symbols from ./a...
Starting program: /home/josh/tmp/a 

Program received signal SIGTRAP, Trace/breakpoint trap.
main () at /home/josh/tmp/a.zig:4
4	    @import("std").debug.warn("{}\n", foo);
(gdb) p foo
$1 = false
(gdb) n
true
5	    foo = true;
(gdb) p foo
$2 = false
```

the value is clearly `true`, but gdb reports it as `false`.

**Comment by cameris** [comment]
Could it be that bool has no size? Just thought it's worth mentioning.
```
Reading symbols from ./i2685...
Starting program: /tmp/i2685 

Program received signal SIGTRAP, Trace/breakpoint trap.
main () at /tmp/i2685.zig:4
4	    @import("std").debug.warn("{}\n", foo);
I:(gdb) p foo
$1 = false
I:(gdb) p sizeof(foo)
$2 = 0
I:(gdb) p &foo
$3 = (bool *) 0x7fffffffe15f
I:(gdb) p *(char *) 0x7fffffffe15f
$4 = 1 '\001'
```

**Comment by LemonBoy** [comment]
> Could it be that bool has no size?

gdb (and lldb) assumes all the DWARF-encoded sizes are expressed in multiple of 8 bits, that's why Zig's 1-bit `bool` (and any other weird-sized type) end up being zero-sized once the debugger evaluates its size in bytes.

**Comment by daurnimator** [comment]
> gdb (and lldb) assumes all the DWARF-encoded sizes are expressed in multiple of 8 bits

Should we file upstream bugs here? Or does DWARF support this notion?
