### ISSUE TITLE
Duplicate exe name with zig run on Windows

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#2686]
Use the following to reproduce the problem on windows:

main.zig:
```zig
const std = @import("std");
pub fn main() !void {
    var a = std.heap.DirectAllocator.init();
    var args = std.process.args();
    while (true) {
        var nextArg = args.next(&a.allocator) orelse break;
        var arg = nextArg catch |err| {
            std.debug.warn("Error: {}\n", err);
            return err;
        };
        std.debug.warn("ARG '{}'\n", arg);
    }
}
```

```
> zig run main.zig
C:\temp>zig run main.zig
ARG 'C:\Users\Jonathan\AppData\Local\zig\stage1\o\ePLZBKaa-ZjhPJIrTAJoZw_uiPT7vOO773DUOjRfgbJFcfGB0hdkTbCLBJwix4oh\run.exe'
ARG 'C:\Users\Jonathan\AppData\Local\zig\stage1\o\ePLZBKaa-ZjhPJIrTAJoZw_uiPT7vOO773DUOjRfgbJFcfGB0hdkTbCLBJwix4oh\run.exe'

> zig run main.zig -- a b c
ARG 'C:\Users\Jonathan\AppData\Local\zig\stage1\o\ePLZBKaa-ZjhPJIrTAJoZw_uiPT7vOO773DUOjRfgbJFcfGB0hdkTbCLBJwix4oh\run.exe'
ARG 'C:\Users\Jonathan\AppData\Local\zig\stage1\o\ePLZBKaa-ZjhPJIrTAJoZw_uiPT7vOO773DUOjRfgbJFcfGB0hdkTbCLBJwix4oh\run.exe'
ARG 'a'
ARG 'b'
ARG 'c'
```

The problem here is that the executable appears twice in the argument iterator.  This is due to an error in `src/main.cpp` where it includes the exe in the argument list twice. We can see it works as expected if we compile `main.zig` to an executable, and invoke it with `cmd.exe` without using `zig run`:

```
> zig build-exe main.zig

> main
ARG 'main'

> main a b c
ARG 'main'
ARG 'a'
ARG 'b'
ARG 'c'
```

This problem occurs in `main.cpp` when the `execve` call fails.   `main.cpp` will pass the same exe/args to `os_spawn_process` as it did to `execve`, however, `os_spawn_process` will add the exe in addition to the arguments which causes it to be duplicated.  This only happens on windows because `execve` only fails on windows.

**Comment by marler8997** [comment]
Fix here: https://github.com/ziglang/zig/pull/2665

**Comment by marler8997** [comment]
Fix integrated

**Comment by andrewrk** [comment]
Thanks @marler8997!
