### ISSUE TITLE
A new queue is not empty?

### ISSUE THREAD

**Issue by joachimschmidt557** [ziglang/zig#2693]
I'm using zig from the master branch. I encountered this problem when using `std.atomic.Queue` in my project (here a simple file to reproduce the issue):

```
const std = @import("std");

pub fn main() void {
    var q = std.atomic.Queue([]u8).init();

    if (!q.isEmpty())
        std.debug.warn("asdf");
}
```

```
$ zig build-exe test.zig
$ ./test
asdf
```

Am I doing something wrong?

**Comment by andrewrk** [comment]
Looks like a bug; I think the logic is exactly backwards:

```zig
        pub fn isEmpty(self: *Self) bool {
            const held = self.mutex.acquire();
            defer held.release();
            return self.head != null;
        }
```

**Comment by joachimschmidt557** [comment]
If it's ok, I can work on this. Do I just need to exchange the `!=` for `==` or do I need to also look at `.tail` ?

**Comment by joachimschmidt557** [comment]
Ok, I've changed the `!=` to `==` and checked, it should be working now.
