### ISSUE TITLE
compare against undef in a vector crashes the compiler

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2707]
```
5183	bool const_values_equal(CodeGen *g, ConstExprValue *a, ConstExprValue *b) {
5184	    assert(a->type->id == b->type->id);
5185	    assert(a->special == ConstValSpecialStatic);
5186	    assert(b->special == ConstValSpecialStatic);
```

ignoring `ConstValSpecialUndef`

**Comment by shawnl** [comment]
This was triggered by buggy code (usually the undef handler should catch this), but it is still a bug.

**Comment by andrewrk** [comment]
Do you have a test case or a stack trace?

**Comment by shawnl** [comment]
If you run the code in #2708 you will run into this.

Sorry for the low-quality bug reports.

**Comment by shawnl** [comment]
considering that I got float op vectors working I think this is fixed
