### ISSUE TITLE
vectors of floats have float type, not vector type

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2708]
```
$8 = {id = ZigTypeIdFloat, name = {list = {items = 0x555558195ed0 "f32", length = 4, capacity = 8}}, 
```
I'm not blocked on this so I am going to continue.

**Comment by andrewrk** [comment]
issue checklist:
 * [ ] test case
 * [ ] expected output
 * [x] actual output

plz?

**Comment by shawnl** [comment]
That is not actual output, it is in gdb. You see length 4, capacity 8 (this is AVX-256), and the type should be ZigTypeIdVector (while the items type, f32, is correct).

And this bug cannot really be tested until simd branching is implemeted #2698, because zig assumes that comparisons return bool, when vector comparisons return vectors of bool.

But here is the code I used to get that in gdb:

```

    {
        var T: @Vector(2, f32) = undefined;
        var a: T = [_]f32{2.5, 5.5};
        var b: T = [_]f32{5.5, 2.5};
        var c: T = [_]f32{6.25, 5.25};
        expect(@mulAdd(T, a, b, c) == [_]f32{20, 19});
    }
```

**Comment by shawnl** [comment]
considering that I got float op vectors working I think this is fixed
