### ISSUE TITLE
create a C,C++ to Zig transformation tool.

### ISSUE THREAD

**Issue by catastrop** [ziglang/zig#2717]
Like V language.

**Comment by daurnimator** [comment]
See `zig translate-c`. C++ will not be supported for the foreseeable future.

**Comment by XVilka** [comment]
You might be inspired by the amazing [c2rust](https://github.com/immunant/c2rust/) tool from Immunant. Obvious from the name it helps not only transform C source code into the Rust one but also provides means for cross-checking the resulting code with automated tests, along with automated and guided refactoring tool with Lua scripting capabiity.

![image](https://user-images.githubusercontent.com/203261/59862100-b6190480-93b4-11e9-9b7a-7d430148fd9c.png)

**Comment by andrewrk** [comment]
Please search through issues before creating a new one

https://github.com/ziglang/zig/issues?q=is%3Aopen+is%3Aissue+label%3Atranslate-c
