### ISSUE TITLE
in the language reference, make it clear which version it's for and link to the other versions

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2718]
People arrive at documentation from search engines and get confused about which version they should be looking at. Let's try to make that a bit more clear.

**Comment by daurnimator** [comment]
PostgreSQL's docs are probably the template to use here.
e.g. see https://www.postgresql.org/docs/current/sql-createtrigger.html along the top you have: 
> Supported Versions: Current (11) / 10 / 9.6 / 9.5 / 9.4
> Development Versions: 12 / devel
> Unsupported versions: 9.3 / 9.2 / 9.1 / 9.0 / 8.4 / 8.3 / 8.2 / 8.1 / 8.0 / 7.4 / 7.3 / 7.2 / 7.1

**Comment by joaoh82** [comment]
That is definitely a must. For example the #master is outdated in reference to the #0.4.0 on regards thread local variables.
Master: https://ziglang.org/documentation/master/#Thread-Local-Variables
https://ziglang.org/documentation/0.4.0/#Thread-Local-Variables
On 0.4.0 there is no `Thread.spawn` on `std` anymore and it is now called `os.spawnThread`

**Comment by andrewrk** [comment]
done in 04b32d6a8aa30cc894f3057581ffda28466e8ef2 and https://github.com/ziglang/www.ziglang.org/commit/3d393235bbcc0d2398c555d3567a543b95cd282f
