### ISSUE TITLE
Add compile error hint for explicit enum tag type

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#2719]
```
const Enum = enum {
    A,
    B = 2,
};
 
test "Test Enum" {
    _ = Enum;
}
 
/tmp/main.zig:3:9: error: integer value 2 cannot be implicitly casted to type 'u1'
    B = 2,
```

Error message can be improved by suggesting to make the tag type explicit.

**Comment by scheibo** [comment]
This error was updated in 3114115348e789ae4bab8844c7ebd0067185f1c4 and mentions tag types:

```
test.zig:3:9: error: value assigned to enum tag with inferred tag type
    B = 2,
        ^
 ```

Can this issue be closed as resolved? If not, what would the desired compiler error message be?
