### ISSUE TITLE
Command line argument --override-std-dir does not affect std/special

### ISSUE THREAD

**Issue by Sahnvour** [ziglang/zig#2729]
I'm making changes to the standard library, that also affect for example `std/special/build_runner.zig`. When running `zig build test --override-std-dir ./std`, it will fail with a compile error because zig tries to compile the installed `build_runner.zig` (that wasn't changed) with the overriden std lib.

**Comment by Vexu** [comment]
`--override-std-dir` has been replaced with `--zig-lib-dir`, `std/special` no longer exists but `--zig-lib-dir` correctly affects `build_runner.zig`.
