### ISSUE TITLE
Iterating over/accessing [3]f32 inside packed struct gives 'unable to evaluate constant expression'

### ISSUE THREAD

**Issue by fu5ha** [ziglang/zig#2731]
Example: https://godbolt.org/z/2uTYai

vec2 and vec4 work but vec3 does not

**Comment by termhn** [comment]
maybe related: #2627

**Comment by andrewrk** [comment]
Making a note to test this case when doing #3133.

**Comment by Vexu** [comment]
Arrays are no longer allowed in packed structs.
