### ISSUE TITLE
Allocator in global scope

### ISSUE THREAD

**Issue by tuket** [ziglang/zig#2732]
If I have an allocator in the scope of a function it's fine.

```zig
const std = @import("std");
const warn = std.debug.warn;
const fmt = std.fmt;

pub fn main() !void {
    var fixMemBuffer: [256]u8 = undefined;
    var fixMem = &std.heap.FixedBufferAllocator.init(&fixMemBuffer).allocator;
    const str = try fmt.allocPrint(fixMem, "hello {}", "world\n");
}
```

If I move the allocator to the global scope it crashes:

```zig
const std = @import("std");
const warn = std.debug.warn;
const fmt = std.fmt;

var fixMemBuffer: [256]u8 = undefined;
var fixMem = &std.heap.FixedBufferAllocator.init(&fixMemBuffer).allocator;

pub fn main() !void {
    const str = try fmt.allocPrint(fixMem, "hello {}", "world\n");
}
```

Am I doing something wrong?

**Comment by tuket** [comment]
I ended up doing this:

```zig
const std = @import("std");
const warn = std.debug.warn;
const fmt = std.fmt;

var memory: [128]u8 = undefined;
var alloc: *std.mem.Allocator = undefined;

pub fn main() !void {
    alloc = &std.heap.FixedBufferAllocator.init(memory[0..]).allocator;
    const str = try fmt.allocPrint(alloc, "hello {}", "world\n");
    warn("{}", str);
}
```

**Comment by tiehuis** [comment]
The issue you encountered was with respect to lifetimes and where the memory of
`FixedBufferAllocator` is stored. In your example you are only storing the address
of the value returned by `FixedBufferAllocator.init`. The actual value is discarded.
If you instead store this in memory and then take the address as another
variable you will get the expected result.

    const std = @import("std");

    var buffer: [256]u8 = undefined;
    var fixed = std.heap.FixedBufferAllocator.init(&buffer);
    var allocator = &fixed.allocator;

    pub fn main() !void {
        const s = try std.fmt.allocPrint(allocator, "Hello {}", "World\n");
    }

**Comment by tuket** [comment]
Ah, I see...
My solution only works because alloc is used only before main() returns
Thanks for your answer
