### ISSUE TITLE
build-exe for thumbv4t-freestanding fails with "instruction variant requires ARMv6 or later"

### ISSUE THREAD

**Issue by cartr** [ziglang/zig#2738]
I'd like to use Zig to write software for the Game Boy Advance. The GBA uses the ARMv4T instruction set, and it accesses the cartridge ROM using a 16-bit bus, so I'm thinking the best target to use is `thumbv4t-freestanding`. But attempting to run `zig build-exe` with that target results in the following error:

```
$ echo 'pub fn main() void {}' > trivial.zig
$ zig build-exe trivial.zig -target thumbv4t-freestanding
<inline asm>:1:3: error: instruction variant requires ARMv6 or later
         mov     r3, r1
         ^
<inline asm>:2:2: error: instruction variant requires ARMv6 or later
 mov     r1, r2
 ^
<inline asm>:3:2: error: instruction variant requires ARMv6 or later
 mov     r2, r3
 ^
LLVM ERROR: Error parsing inline asm

$
```

I suspect this message is referring to [the definition of `__aeabi_memset` in `compiler_rt.zig`](https://github.com/ziglang/zig/blob/24400d5882aa2b83a4aed3e4c1503d0393e1c541/std/special/compiler_rt.zig#L510). That function (along with `__aeabi_memclr`) has `mov` instructions where both the source and destination are low registers. [A "superseded" reference guide](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0204j/Cihcdbca.html) reveals that this is invalid prior to ARMv6:

> `MOV Rd, Rm`
>
>    In architectures before ARMv6, either Rd or Rm, or both, must be a Hi register. In ARMv6 and above, this restriction does not apply.

**Comment by SamTebbs33** [comment]
According to wikipedia, the GBA uses an ARM7 which uses the ARMv4 ISA, so a workaround could be to use `armv4t-freestanding` instead. However this is probably still a bug and an architecture version check might be needed in the memset definition.
