### ISSUE TITLE
userland windows build error

### ISSUE THREAD

**Issue by gettf** [ziglang/zig#2740]
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18922.
-- The C compiler identification is MSVC 19.22.27724.0
-- The CXX compiler identification is MSVC 19.22.27724.0

zig\std\io.zig(224,22): error GD01FD524: invalid builtin function: 'This'
zig\build-release\userland_target.vcxproj

**Comment by andrewrk** [comment]
Hi @gettf -

Building from source on Windows is tested by the CI on every commit, so we know it works. The information you provided is not enough to help troubleshoot this.
