### ISSUE TITLE
problems with `assert` in `release-safe` mode

### ISSUE THREAD

**Issue by Tetralux** [ziglang/zig#2745]
Possibly related to #398.

Currently, `release-safe` builds print `reached unreachable code` and nothing else, when an assert is triggered.
This is fine if in debug builds, but in `release-safe` there isn't much you can do to find what happens.

In my particular case, I tried debugging the program with VS and it just showed me it borking up while trying to print a stack trace and failing.
I could not navigate up the stack--it was almost all '???'s, and I don't think it even showed me that `assert` was being called at all.

I had to resort to IRC to help me figure it out - which wasn't too difficult fortunately, because it was a fairly simple program to begin with.

In my case, it turned out that it wasn't happening in debug mode because it was due to unitialized memory.

In a larger program however, it might be difficult to track that down.

**Comment by andrewrk** [comment]
> I could not navigate up the stack--it was almost all '???'s, and I don't think it even showed me that assert was being called at all.

Could you show an example of not being able to navigate up the stack? It works for me.

Other than that this seems to be the known issue that debug info parsing is not sophisticated enough to handle optimization yet.

**Comment by Tetralux** [comment]
Another way to help with this might be to allow you to set a switch that makes the value of `undefined` a realistically-uninitialized value rather than making it zero, in debug mode.

**Comment by andrewrk** [comment]
Not an actionable issue
