### ISSUE TITLE
request: Go style multiple constant declaration

### ISSUE THREAD

**Issue by catastrop** [ziglang/zig#2753]

**Comment by tiehuis** [comment]
Can you clarify?

Are you proposing for example the following declaration style?

```go
const (
    a = 5
    b = 7
    c = 3
)
```

On the face of it, this goes against one of the tenets of Zig, in that we should minimize having multiple ways of doing things. Also, perhaps a more compelling argument is that it doesn't offer anything that cannot be done now by doing separate statements. Unlike Go, too, there isn't as much of a concern over "brevity" in Zig compared to Go.

**Comment by catastrop** [comment]
the example you have given is easier to read than using `const` keyword every time.
