### ISSUE TITLE
Zig unexpectedly rejects `if` in `inline for` with "control flow attempts to use compile-time variable at runtime"

### ISSUE THREAD

**Issue by CurtisFenner** [ziglang/zig#2755]
Zig version 0.4.0+fcc0728 on Windows 10 x64.

The following code doesn't compile:

```zig
test "Test" {
    inline for ([_]usize{ 0, 1 }) |field, fi| {
        var count: usize = 0;
        const cond = count < field;
        if (cond) {
            return error.OutOfMemory;
        }
    }
}
```

with the following error:
```
rejects\grammar.zig:8:13: error: control flow attempts to use compile-time variable at runtime
        if (cond) {
            ^
rejects\grammar.zig:3:12: note: compile-time variable assigned here
    inline for ([_]usize{ 0, 1 }) |field, fi| {
           ^
```

However, if I change `const cond` to `var cond`, or if I change `var count` to `const count`, or I do both, it compiles successfully.

Also, if I change the constants in the array to either `{0, 0}`, `{1, 0}`, or `{1, 1}`, the code compiles successfully.

Expected behavior: The comptime variable `field` would simply be "inlined" as a constant and the branch would be executed at runtime (if not optimized away), rather than the code being rejected, regardless of the choice of `const` vs. `var` for `cond` and `count`.

**Comment by Vexu** [comment]
Fixed by 4618c41fa6ca70f06c7e65762d2f38d57b00818c
