### ISSUE TITLE
regression in peer type resolution

### ISSUE THREAD

**Issue by dbandstra** [ziglang/zig#2762]
First of all congrats on merging the result location branch... I'm not annoyed all about this breakage, I'm excited at the progress :) And anyway, "get this compiling in latest zig" is not a bad way to unwind in the evening.

Anyway there were just two errors in my oxid project. It seems to be peer type resolution. Here's a test case.

```zig
fn getSomething() ?u8 {
    return null;
}

test "" {
    if (switch (getSomething().?) {
        0 => true,
        else => null,
    }) |v| {

    }
}
```

Outputs:

```
/home/dbandstra/oxid/test.zig:6:9: error: incompatible types: '*(null)' and '*bool'
    if (switch (getSomething().?) {
        ^
/home/dbandstra/oxid/test.zig:8:17: note: type '*(null)' here
        else => null,
                ^
/home/dbandstra/oxid/test.zig:7:14: note: type '*bool' here
        0 => true,
             ^
```

There was one other place I got an error, but it looks like the same bug. I didn't bother to make a minimal test case here (test cases are sometimes more nonsensical and hard to read than real code anyway), but the code in oxid that failed was this:

```zig
            if (for (self.player.bullets) |*slot| {
                if (slot.*) |bullet_id| {
                    if (gs.find(bullet_id, c.Bullet) == null) {
                        break slot;
                    }
                } else {
                    break slot;
                }
            } else null) |slot| {
```

**Comment by andrewrk** [comment]
Thanks for the report. I should have remembered to test Oxid! I'll prioritize this regression, hopefully can get that fixed for you soon.

**Comment by andrewrk** [comment]
After 0a0c11685fd8faf73392d88dbdee7c744cc83386 Oxid builds and i can play it
