### ISSUE TITLE
build.exe crashes when a compile error happens

### ISSUE THREAD

**Issue by Flaminator** [ziglang/zig#2768]
On Windows when running `zig build` and the process generates a compile error the build.exe process crashes.
I can reproduce it on both the latest master [zig-windows-x86_64-0.4.0+3c914c63.zip](https://ziglang.org/builds/zig-windows-x86_64-0.4.0+3c914c63.zip) as on the 0.4.0 release [zig-windows-x86_64-0.4.0.zip](https://ziglang.org/download/0.4.0/zig-windows-x86_64-0.4.0.zip).

I included a [sample project](https://github.com/ziglang/zig/files/3334956/crash.zip) that crashes when you run `zig build`.

I am running Windows 8 x64.

**Comment by fengb** [comment]
https://github.com/ziglang/zig/blob/master/std/build.zig#L767

`zig build` always panics when it encounters a non-zero code from the underlying `build-exe`. For known failures, I think it should forward the error code instead of panicking.

**Comment by andrewrk** [comment]
> For known failures, I think it should forward the error code instead of panicking.

good idea :+1:
