### ISSUE TITLE
unnecessary usage of soft float library routines causing linking errors 

### ISSUE THREAD

**Issue by GreyDodger** [ziglang/zig#2771]
I have this zig code 
```
export fn foo() void {
    (@import("std").io.getStdOut() catch unreachable).outStream().stream.print("{}", @floatCast(f32, 0.1)) catch unreachable;
}
```
I compile that into a library
```
zig build-lib some_zig_code.zig
```
I have this cpp code
```
extern "C" void foo();

void main() {
	foo();
}
```
I compile that into an exe linking against the zig lib
```
cl some_cpp_code.cpp -link some_zig_code.lib
```
and I get these link errors
```
unresolved external symbol __fixunsdfti referenced in function std.fmt.errol.enum3.slab
unresolved external symbol __floatuntidf referenced in function std.fmt.errol.enum3.slab
unresolved external symbol __umodti3 referenced in function std.fmt.errol.enum3.slab
unresolved external symbol __udivti3 referenced in function std.fmt.errol.enum3.slab
```

using windows 10 and the lastest zig release (as of 6/27/19)

**Comment by andrewrk** [comment]
This is probably going to become the default in the future, but try adding `--bundle-compiler-rt` to your `build-lib` command.

They're not unnecessary; they're used by the float-printing code. However once #1299 is done I believe would be unnecessary for this particular use case.

All zig code depends on compiler_rt, but you only pay for what you use (at least after #2062 is solved, which I believe is going to be as simple as `-ffunction-sections`)

**Comment by GreyDodger** [comment]
ah, thanks!
