### ISSUE TITLE
alignBackward and alignForward cause integer underflow when called with 0

### ISSUE THREAD

**Issue by SamTebbs33** [ziglang/zig#2774]
`std.mem.alignBackward` and `alignForward` cause integer underflow when called with an alignment of 0 respectively.  This is a result of the implementation (the subtraction) that a programmer shouldn't be concerned about, so I propose that if they are called with an alignment of 0, they return 0. Otherwise it should be made clear in the doc comment that an alignment of 0 is not allowed.

**Comment by andrewrk** [comment]
I misread, thought this said address of zero. The underflow behavior is correct for align zero; that is effectively an assertion. The only change needed here is documentation.

**Comment by SamTebbs33** [comment]
> I misread, thought this said address of zero. The underflow behavior is correct for align zero; that is effectively an assertion. The only change needed here is documentation.

Yeah I miswrote it at first. I'll add to the doc comment saying that an alignment of 0 isn't allowed.
