### ISSUE TITLE
Asm inputs, outputs, and clobbers do not prevent reordering

### ISSUE THREAD

**Issue by liampwll** [ziglang/zig#2779]
```zig
const warn = @import("std").debug.warn;

pub fn main() void {
    var x = u64(0);
    warn("{}\n", x);
    asm (
        "addq $1, %[p]"
        : [_] "=m" (x)
        : [p] "m" (&x)
        : "memory"
    );
    warn("{}\n", x);
}
```
The assembly output of this code is as follows on x86_64-linux-gnu:
```asm
	movq	-8(%rbp), %rdi
	callq	std.debug.warn
	movq	-8(%rbp), %rdi
	callq	std.debug.warn
	addq	$16, %rsp
```

**Comment by SamTebbs33** [comment]
This could caused by instruction scheduling in LLVM, could you try adding `volatile` before `asm` and seeing if it still gets reordered?

**Comment by liampwll** [comment]
The order is correct when volatile is used, but that causes another issue (see #2778).

**Comment by SamTebbs33** [comment]
Ah good. Generally if you want to retain the ordering you need to add `volatile` otherwise the scheduler is free to reorder for optimisation purposes, so what you're observing here is correct behaviour.

**Comment by liampwll** [comment]
The output operands and the memory clobber should both prevent reordering.

**Comment by Vexu** [comment]
The non-volatile version is now removed as dead code and the volatile version worked originally.
