### ISSUE TITLE
Nested misaligned `packed struct` causes "Assertion failed. This is a bug in the Zig compiler."

### ISSUE THREAD

**Issue by fengb** [ziglang/zig#2784]
Inside a nested packed struct, if a field spans an alignment boundary (in x64 — 1B, 2B, 4B, or 8B, in wasm32 — 1B or 4B), Zig gets confused and throws an assertion error:

```zig
pub const Misaligned = packed struct {
    a: u8,
    _pad: [15]u8 = [_]u8{0} ** 15,
    // Manually aligning this data works
    // _pad1: [1]u8 = [_]u8{0} ** 1,
    // _pad2: [2]u8 = [_]u8{0} ** 2,
    // _pad3: [4]u8 = [_]u8{0} ** 4,
    // _pad4: [8]u8 = [_]u8{0} ** 8,
};  

// Removing `packed` also fixes this problem
pub const Wrapper = packed struct {
    m: Misaligned,
};

export fn trigger() *const Wrapper {
    const check = Wrapper{
        .m = Misaligned{ .a = 1 },
    };  
    return &check;
}
```

It would seem that Zig is trying to regroup the memory into proper boundaries, but the naive alignment doesn't make sense — e.g. the array started with an 8B chunk but aligned(1).

I'm not quite sure why removing `packed` from the wrapper struct resolves this problem.

**Comment by fengb** [comment]
Probably a different symptom of the problem occurring in https://github.com/ziglang/zig/issues/2627

**Comment by Vexu** [comment]
Arrays are no longer allowed in packed structs.
