### ISSUE TITLE
Proposal to allow assigning once to a `const` variable that was initialized to `undefined`

### ISSUE THREAD

**Issue by CurtisFenner** [ziglang/zig#2792]
The following is a bit of code that I wanted to write:

```zig
        const contradicting: []const usize = undefined;
        const satisfying: []const usize = undefined;
        if (literal.sign) {
            contradicting = term_info[literal.term].clauses_negative.toSlice();
            satisfying = term_info[literal.term].clauses_positive.toSlice();
        } else {
            contradicting = term_info[literal.term].clauses_positive.toSlice();
            satisfying = term_info[literal.term].clauses_negative.toSlice();
        }
```

However, the `const` prevents the assignment:
```
sat.zig:42:27: error: cannot assign to constant
            contradicting = term_info[literal.term].clauses_negative.toSlice();
                          ^
```

As a result, I have to use `var`, which means I lose the ability to indicate that these variables should not be changed from their initial state.

The only way to work around this would be to encapsulate all of the variables into a struct, and extra the initialization branches into a function, and pass all of the used in-scope names to that function (or otherwise use a closure feature that may be added to Zig), then extracting the variables from the returned struct. This is too much ceremony just to communicate that some variables shouldn't be mutable:

```zig
        const ClauseLists = struct {
            contradicting: []const usize,
            satisfying: []const usize,

            // parameters could possibly be omitted if closures are added to Zig
            fn getClauseLists(term_info: []const Meta, literal: Literal) ClauseLists {
                if (literal.sign) {
                    return ClauseLists{
                        .contradicting = term_info[literal.term].clauses_negative.toSlice(),
                        .satisfying = term_info[literal.term].clauses_positive.toSlice(),
                    };
                } else {
                    return ClauseLists{
                        .contradicting = term_info[literal.term].clauses_positive.toSlice(),
                        .satisfying = term_info[literal.term].clauses_negative.toSlice(),
                    };
                }
            }
        };

        const clause_lists = ClauseLists.getClauseLists(term_info, literal);
        const contradicting = clause_lists.contradicting;
        const satisfying = clause_lists.satisfying;
```

This leaves the only real alternative to give up on `const` (which, admittedly, is not too great of a problem)

I propose the following: An assignment to a `const` variable is allowed when

* the `const` variable was initialized to the literal `undefined` (and only the literal; for example, an initialization of a comptime function call that results in `undefined` would not be eligible)
* there are no previous references to the variable in any path possibly leading to the assignment. This includes
    * no previous reads of the variable
    * no previous addressing of the variable
    * no previous assignments of the variable
    * no references to the variable in `defer` or `errdefer`, if exiting from the function is possible before this use

These rules would make the initial snippet of code legal Zig code.

In addition, it may be useful to add an extra error for uses of a `const` variable initialized in this way that are possibly left uninitialized. That is, any use of a "re"-initialized `const` variable *must* be statically known to be initialized in every path leading to any use.

With this additional check, code like the following would be rejected:

```zig
const value: usize = undefined;
if (runtimeFunction()) {
    value = 3;
}
std.debug.warn("Value: {}\n", value); // ERROR: use of possibly uninitialized const variable `value`
```

In initializations with many possible branches, this would catch unintentionally missing branches. An explicit `value = undefined` could be added to those branches to satisfy the compiler (and, if the code cannot be structured so that this works, there's always falling back on a `var`):

```zig
const value: usize = undefined;
if (runtimeFunction()) {
    value = 3;
} else {
    value = undefined;
}
std.debug.warn("Value: {}\n", value); // OK
```

These rules are similar to the rules for `final` variables in Java; in Java, a variable may be declared without giving an initial value; all paths leading to uses of the variable must have an initialization, and `final` variables may not be initialized more than once.

There may be something that I have missed about the semantics of `const`-initialization in Zig that actually prevents re-assignment (perhaps at the inline-assembly level?), but since no references to the variable are allowed, I don't think this "re"-assignment would be detectable, or in cases like assembly, particularly problematic.

**Comment by hryx** [comment]
I've wanted this in the past, though I've since learned that Zig's expressive syntax makes it possible (and pleasant) to get around a lot of these cases. For example, your first snippet could be updated like this:

```zig
    const contradicting = if (literal.sign)
        term_info[literal.term].clauses_negative.toSlice()
    else
        term_info[literal.term].clauses_positive.toSlice();
    const satisfying = if (literal.sign)
        term_info[literal.term].clauses_positive.toSlice()
    else
        term_info[literal.term].clauses_negative.toSlice();
```

Here's an example where I used the local struct type workaround you mentioned:

https://github.com/hryx/zig/blob/173142b16a52b88e8175d1923bc97492499e875c/std/zig/parse.zig#L2360-L2387

Agreed that the extra ceremony feels a little clunky, but it will look better when we have [anonymous struct literals](https://github.com/ziglang/zig/issues/685) so that the type doesn't even need to be declared.

**Comment by CurtisFenner** [comment]
Anonymous struct literals with break with expressions seems like it might work well. The snippet you shared here with two `if`s is no good to me, because it obscures the fact that the two conditions are the same and creating confusing, obscuring repetition.

Still, I don't think that approach is obvious, and it does still obscure intent, compared to the direct alternative (of `var` / `const` via this proposal). Why does initializing a `const` require a block, `break`s, and an anonymous type when the version with `var`s would probably not do any of those things?

So, even though there is an idiom that makes this possible (thanks! I learn more about Zig every day!), I don't think it's pleasant enough for it to be reached for in most cases where programmers actually want a `const` but need branching in the initialization. Between choosing to introduce this complex idiom in my code and just opting for a `var`, I will usually be opting for a `var`, and I think many other programmers would as well. On the other hand, writing code with the proposed pattern doesn't involve learning/standardizing new idioms for a project, and makes opting into `const` not require any refactoring even when introducing branches.

**Comment by SamTebbs33** [comment]
I agree with this, but see an issue where the programmer intended for the variable to remain `undefined` (I can't think of an example but it is possible), and this would allow them to mistakenly re-assign it to something else.

**Comment by GoNZooo** [comment]
This seems like introducing very confusing semantics for little more than minor convenience. It's absolutely obvious what the `if` expression variant does and it keeps everything consistent and without any confusing behavior associated with it (having a `const` sometimes not be `const`, or having a special variant of `const` has none of those qualities, IMO). It's definitely something that will cause people to debug their language knowledge at one point or another.
