### ISSUE TITLE
proposal: remove comptime_float type

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2794]
I don't see any purpose of the `comptime_float` type. IEEE-754 float types are very stringlently defined, with deterministic rounding, and it is not clear how these definitions apply to `comptime_float`. Currently `comptime_float` is just `f128`, but in that case, why does it needs its own type?

**Comment by tiehuis** [comment]
The intent is for `comptime_float` to be arbitrary precision and for any operations performed on them to maintain full precision. While it is true the current compiler just uses a `f128`, we can use `big.Rational` in the self-hosted and maintain full precision for `comptime_float` then.

**Comment by shawnl** [comment]
> arbitrary precision 

But this isn't possible. What if you use a transcendental function?

Perhaps "best effort" is OK, but that results in it being far less useful than the f128 type in many cases.

**Comment by tiehuis** [comment]
My mistake, you are correct. I still think there is may be some usefulness in being able to compute at a higher precision (even if fixed) is useful. Similar to how GCC use MPFR for computation on constants.

**Comment by andrewrk** [comment]
one important purpose of comptime_float type is that it implicitly casts to the other float types even when that results in a loss of precision. If float literals were to always be f128, then they would only be able to implicitly cast to the other float types when no loss of precision occurred. Maybe that is desirable, and that's what this proposal explores.

**Comment by shawnl** [comment]
> comptime_float [...] implicitly casts to the other float types even when that results in a loss of precision.

Yes, the other float types certainly shouldn't do that. This may be reason enough to keep `comptime_float`.

**Comment by shawnl** [comment]
I think it was shown that `comptime_float` has a role, and should be kept.
