### ISSUE TITLE
ability to detect native libc from MSVC Community Edition 2015 (v14.0.25420.01 u3) on Windows 7

### ISSUE THREAD

**Issue by MilesVII** [ziglang/zig#2795]
Receiving an error when trying to compile hello world C code:
```
>zig build-exe --c-source hello.c --library c
Unable to determine libc include path: file not found
Unable to link against libc: Unable to find libc installation: file not found
See zig libc --help for more details.
```
I guess, it tries to find something in Visual Studio or something like this but fails.
Machine is running Windows 7 and M$ Visual Studio Community Edition 2015 (v14.0.25420.01 u3) is installed

**Comment by SamTebbs33** [comment]
Could you run `zig libc` and paste the output here?

**Comment by MilesVII** [comment]
```
>zig libc
Unable to determine libc include path: file not found
```

**Comment by joaoh82** [comment]
Have you tried `zig cc` command?

**Comment by MilesVII** [comment]
Just tried
```
>zig cc hello.c
```
and it worked

**Comment by andrewrk** [comment]
MSVC 2015 is getting pretty old. Even LLVM is [dropping support for it](http://lists.llvm.org/pipermail/llvm-dev/2019-June/133147.html). When revisiting this issue in the 0.6.0 release cycle, closing as wontfix might be what happens. However if somebody wanted to contribute a patch to detect it, that would be welcome.

**Comment by andrewrk** [comment]
I'm dropping support for this, especially in light of the fact that we might be transitioning in the future to no MSVC integration (since zig will provide its own libc, etc).
