### ISSUE TITLE
allow use of undefined as switch key value

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2798]
```
switch (foo) {
undefined => do_stuff(),
else => do_other_stuff(),
}
```
While would trim the undefined key branch as unreachable.

Why is this useful? you might ask. It allows more ways to disable code paths based on compile time variables. `undefined` here would generally be a const. Instead you currently get
```
    #1 with zig trunk
    zig trunk (Editor #1, Compiler #1) Zig

/home/ubuntu/example.zig:4:5: error: use of undefined value here causes undefined behavior

Compiler returned: 1
```
Which is bogus (however llvm won't take an undefined here either, IIUC, so it does have to be explicitly handled).

Related: #597

**Comment by shawnl** [comment]
I'm starting to have second thoughts about this proposal, as it muddles the concept of `undefined`. However I think my use case is sound. Any suggestions?

**Comment by daurnimator** [comment]
switching on undefined should immediately be an error: `undefined` means "any value could be here; it's an error to try read it"

**Comment by shawnl** [comment]
@daurnimator yeah, but it also turns into unreachable in a number of places in llvm, except that zig doesn't let it do that.

**Comment by shawnl** [comment]
Yeah, I'm going to close this as kinda sneaky, almost hidden control flow.
