### ISSUE TITLE
Issue with "Sponsor" button

### ISSUE THREAD

**Issue by steveno** [ziglang/zig#2804]
I don't know if you're aware of this, but there's error message when you click the "Sponsor" button for this project.

![image](https://user-images.githubusercontent.com/116258/60547862-c901d200-9cee-11e9-8f53-9022bfb2344c.png)

If I understand the documentation correctly, I think you need to apply signup for the sponsor beta, [here](https://github.com/users/steveno/sponsors/waitlist).

Please feel free to close this if you're aware and have already applied.

**Comment by andrewrk** [comment]
Thanks, I'm leaving that there hoping that GitHub gets enough errors in their logs that they'll roll their eyes and "fix it" by just picking my name from the waitlist already :pray:
