### ISSUE TITLE
rename keyword "error" to "err"

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2815]
Both are English and `err` is shorter to type.

"Too err is human."

**Comment by SamTebbs33** [comment]
`err` is kinda ugly IMO. `error` looks good and is clear.

**Comment by kristoff-it** [comment]
err is a good name for a variable of type error :)

**Comment by ManDeJan** [comment]
It would be more consistent with the `errdefer` keyword

**Comment by hryx** [comment]
> Both are English

If we are to consider that a factor: _err_ is a verb and _error_ is a noun. On those terms, the existing keyword makes more sense for its use case.

```
struct{} // noun
error{} // noun
err{} // verb
```

> It would be more consistent with the `errdefer` keyword

Yep, but we also have `anyerror`.

**Comment by bheads** [comment]
maybe errdefer should be **error_defer** or **error defer** since error is already a keyword.

**Comment by shawnl** [comment]
Yeah this was not productive.
