### ISSUE TITLE
zig fmt: fix whitespace

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2819]
* [ ] tabs -> spaces
 * [ ] CRLF -> LF

Tabs are not up for debate in this issue, you can post your comments in #544. Please respect the fact that many people have clicked "unsubscribe" on that issue, by exclusively using #544 to complain about tabs.

**Comment by nifker** [comment]
Why force people to convert their files if basically every programming language support both out-of-the-box?

**Comment by hryx** [comment]
@nifker Please see the linked discussion or this [FAQ](https://github.com/ziglang/zig/wiki/FAQ#why-does-zig-force-me-to-use-spaces-instead-of-tabs).

**Comment by nifker** [comment]
Yes I'm now going to read the whole discussion.
