### ISSUE TITLE
test: Set the working directory to the source directory of the test being executed

### ISSUE THREAD

**Issue by jayschwa** [ziglang/zig#2827]
Some types of projects may need a corpus of data for testing. Embedding the data in a `.zig` file may not be ideal for various reasons (e.g. ~binary format~, large size, etc). Ideally, it should be easy for test code to open and use a separate data file, relative to its own path.

Go does something similar when using `go test`.

**Comment by daurnimator** [comment]
`@embedFile`?

**Comment by jayschwa** [comment]
I wasn't aware of `@embedFile`, but it sounds handy. I suppose that solves the hypothetical "binary format" use-case.

**Comment by daurnimator** [comment]
Doesn't it solve all cases? You can parse the embedded file however you want; either at comptime or test-time.
