### ISSUE TITLE
Changing root folder name causes 'zig build' to fail

### ISSUE THREAD

**Issue by IanLilleyT** [ziglang/zig#2829]
I created a simple zig project with a `build.zig` and `main.zig` and compiled / ran successfully.
Then I changed the root folder name to something else and the `zig build` command failed with:

> $ zig build
> Unable to open C:\Users\...\new_name\build.zig
> : file not found

The zig-cache files still reference the old folder name, so that could have something to do with it. My workaround is to delete the zig-cache folder and rebuild.

My build.zig:
```
const Builder = @import("std").build.Builder;

pub fn build(b: *Builder) void 
{
    const exe = b.addExecutable("main", "main.zig");
    exe.setBuildMode(b.standardReleaseOptions());
    exe.install();

    const run = exe.run();
    run.step.dependOn(b.getInstallStep());

    const play = b.step("play", "Play");
    play.dependOn(&run.step);
}
```

**Comment by andrewrk** [comment]
Thanks for the report, and for mentioning the workaround.

**Comment by alexnask** [comment]
This is fixed in master, at least with bare `zig build` commands and when not passing absolute paths contained in the project directory to various compiler options
