### ISSUE TITLE
zig build system: filesystem and/or run shell scripts/batch files?

### ISSUE THREAD

**Issue by babelchips** [ziglang/zig#2839]
I am currently using a Bash script on macOS to run ```zig build``` as part of a larger build pipeline running other simple bash commands: ```cd```, ```rm```, ```zip``` plus various other tools and compilation steps (not Zig).

Ideally I'd like to use the Zig build system to do it all - which would make my build pipeline platform independent.

I understand the Zig build system is heading in this direction but I am curious to know how features like shell calls, accessing environment variables etc. will be implemented.

What is the current status of the Zig build system and what are its future goals?

**Comment by andrewrk** [comment]
Related: #1519

**Comment by tealsnow** [comment]
For anyone stumbling on this looking for a solution; it's in the docs: https://ziglang.org/learn/build-system/. Search for "Running System Tools"
