### ISSUE TITLE
Casting to bool

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2841]
I would expect `bool(0)` to be `false` and `bool(1)` to be `true`.

```zig
test "aaa" {
    @compileLog(@typeOf(bool(0)));
}
```
```
:29: error: expected type 'bool', found 'comptime_int'
    @compileLog(@typeOf(bool(0)));
```

**Comment by andrewrk** [comment]
For bool to int use [@boolToInt](https://ziglang.org/documentation/master/#boolToInt). For int to bool, use `x != 0`.

It's intentional that implicit casting an integer to boolean does not work, otherwise this would work:

```zig
test "aaa" {
    if (0) {
        // ...
    }
}
```

**Comment by Rexicon226** [comment]
> Hey, what happended to @boolToInt? Looks like it doesn't exist anymore, what should I use instaead?

It has been renamed to `@intFromBool`.

**Comment by tuket** [comment]
> > Hey, what happended to @boolToInt? Looks like it doesn't exist anymore, what should I use instaead?
> 
> It has been renamed to `@intFromBool`.

No, now you have to use [@bitCast](https://github.com/ziglang/zig/issues/15794)

**Comment by mlugg** [comment]
@tuket that is not true -- the comment you replied to is easily verified to be accurate. Please check before commenting incorrect information.

**Comment by tuket** [comment]
@mlugg You are right, sorry. I read somewhere else that you can use @bitCast (and it seems to work), but using @intFromBool seems more appropiate.
Thanks!
