### ISSUE TITLE
Compiling zig in folder with spaces fails

### ISSUE THREAD

**Issue by IanLilleyT** [ziglang/zig#2853]
So I'm compiling zig inside my Google Drive folder (contains spaces) and it messes up some of the llvm library names. The error is: `LINK : fatal error LNK1181: cannot open input file 'C:\Users\ian\Google.obj'`

I found out the culprit is `llvm-config --libfiles` (inside Findllvm.cmake, line 70), which separates paths by spaces alone, making it ambiguous. There's an llvm bug report, but it hasn't been fixed in three years! https://bugs.llvm.org/show_bug.cgi?id=27743

This other project fixes it by concatting `llvm-config --libpath` with all `llvm-config --libnames`:
https://github.com/simit-lang/simit/issues/30
https://github.com/gkanwar/simit-1/commit/4457e58cec9d209e25ed5c5c5173ce6de049a1fc

The main thing I want to clear up before fixing this is what to do with LLVM_LIBDIRS. llvm-config only has one libdir, but Findllvm.cmake assumes there's an array of libdirs, and so I'm not sure this concat approach is correct.

**Comment by andrewrk** [comment]
It look to me like `LLVM_LIBDIRS` can assume there will be only one, and that improvement would be welcome (let's rename it to `LLVM_LIBDIR`).
