### ISSUE TITLE
Zig Projects/Modules

### ISSUE THREAD

**Issue by user00e00** [ziglang/zig#2860]
Related to #943 

What will zig projects/modules look like?
- Folder structure? Project descriptor file? All in build.zig?
- If there will be a project descriptor file, which format: DSL? project.zig? XML? JSON?
- What should be the responsibilities of build.zig VS the zig project?

What purpose could projects/modules serve?
- Make it easier to use zig in IDEs?
- Define "public" interfaces/APIs? #130 #1669 #1829 
- Define all necessary information for the package manager?
- Support build.zig by defining dependencies?
- .... ?

What existing systems out there are the most interesting to compare with?
- Maven?
- Java 9 module system?
- IDE inspired, like Visual Studio Solutions
- ... ?

**Comment by MasterQ32** [comment]
I really like that we only have `build.zig` right now. To support IDEs supporting Zig projects, the `zig` executable could get a feature like

```
[user@device my-project] zig list-files
./main.zig
./src/color.zig
./src/radial.zig
./src/foobla.zig
```

that would list all files references in the project. This could even output a dependency tree so the project could be viewed hierarchical in the IDE.

**Comment by andrewrk** [comment]
Let's take this discussion to one of the other community areas: https://github.com/ziglang/zig/wiki/Community
