### ISSUE TITLE
Add Zig to BenchmarkGame and FrameworkBenchmark

### ISSUE THREAD

**Issue by kokizzu** [ziglang/zig#2862]
To raise the popularity of Zig

[BenchmarkGame](https://benchmarksgame-team.pages.debian.net/benchmarksgame/)

[FrameworkBenchmark](https://www.techempower.com/benchmarks/)

**Comment by andrewrk** [comment]
Hi @kokizzu,

That's a great idea.

Here's @tiehuis's project to do that: https://github.com/tiehuis/zig-benchmarks-game

I look forward to seeing BenchmarkGame and FrameworkBenchmark implementations, but they will not be an official part of the zig compiler project. Out of scope!
