### ISSUE TITLE
LLVM Error: cannot debug circular reference to unnamed type

### ISSUE THREAD

**Issue by DutchGhost** [ziglang/zig#2863]
I played around with file instantiation,
and then I tried to test this code:
```Zig
self: *@This(),

pub fn init() @This() {
    var this: @This() = undefined;
    this.self = &this;
    return this;
}

test "" {
    const s = @This().init();   
}
```

when running `zig test src/main.zig` I get an error: "LLVM ERROR: cannot debug circular reference to unnamed type".

Strangely I can only reproduce on Windows with zig 0.4.

**Comment by andrewrk** [comment]
With zig 0.4? If you can't reproduce it with master branch, then this should be closed.

**Comment by DutchGhost** [comment]
With 0.4.0 yup.
Also reproducable with `0.4.0+ae2345b7`, at least on Windows.

**Comment by andrewrk** [comment]
This test case works fine in master branch.
