### ISSUE TITLE
improve std.fs API to accept directory handle parameters

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2888]
To promote robust, correct code, the standard library file system abstractions must encourage the use of operations relative to an open directory handle. On posix this is [openat](https://pubs.opengroup.org/onlinepubs/9699919799/functions/open.html) and on Windows this can be done with [NtCreateFile](
https://docs.microsoft.com/en-us/windows/win32/api/winternl/nf-winternl-ntcreatefile).

In general it should be discouraged to use absolute paths, instead opting to pass an open directory handle and a relative path. In particular, `std.fs.Dir.open` should accept an open directory parameter. Otherwise a directory walker API would have unnecessary race conditions as well as be artificially limited to nesting determined by `PATH_MAX`.

Another motivation for these changes is that the WASI target does not even have the non *at() versions of the functions! It is always required to pass a directory parameter. At first this seems inconvenient, but if you think about it, it solves a lot of problems and is really the way that we should be writing code.

If the file system functions required a directory parameter, this could be a nice way to do this, and users could always explicitly pass the current working directory, should that be desired.

One thing to figure out to accomplish this is how to read a directory handle once we've opened it with NtCreateFile. I have not yet found this Windows API.

**Comment by daurnimator** [comment]
> One thing to figure out to accomplish this is how to read a directory handle once we've opened it with NtCreateFile. I have not yet found this Windows API.

[`NtQueryDirectoryFile`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-ntquerydirectoryfile)

**Comment by andrewrk** [comment]
Beautiful, thank you. I haven't tried calling one of these low level kernel functions yet but I think it's a good direction to go.

**Comment by MasterQ32** [comment]
This sounds rather useful!

I hate that some components modify my current working directory (e.g. windows file dialogs do that, even if you cancel) and then all my relative paths are broken and you have to save and restore the CWD when opening those dialogs…

It would be great to have some "default" directory handles available:

| Handle | Where does it point |
|-----------|------------------------------|
| `.current` | Current OS working directory |
| `.application` | Directory where the executable is in |
| `.userData` | Some writeable folder in the user directory (`%APPDATA%` on Windows or similar)
| `.temp` | Directory for temporary files

```zig
// Open a texture file besides the game executable
var f = try std.fs.File.openRead(std.fs.Dir.application, "textures/my_texture.png")
defer f.close();
```
