### ISSUE TITLE
Determine a "support core" for IDE support and document generation

### ISSUE THREAD

**Issue by user00e00** [ziglang/zig#2893]
Related: #21

I can think of a few things that both HTML document generation and IDE support have in common:
* Joining a block of doc comments to sections of code (I don't know if this is already done in the AST)
* Determining which sections of code to include in call tips and documentation
* Determining a dependency graph for a complete project
* ..

Maybe it's best to design a "support core" with both these use cases in mind, instead of working on those in separation.

**Comment by andrewrk** [comment]
I think this is better discussed on the mailing list since there is nothing actionable here.
