### ISSUE TITLE
Multidimensional Arrays

### ISSUE THREAD

**Issue by mosullivan** [ziglang/zig#2894]
I looked through the documentation etc. but I can't seem to find any reference on how to define and initialise multidimensional arrays (e.g. arrays of strings).  Is this supported and, if so, how would I do this?

**Comment by JohnathanFL** [comment]
Just keep reading each `[]` as "array of" and you already have it.

```
var arStr: [2][]const u8 = [_][]const u8{"Hello", "There"};

for(arStr) |str| {
    std.debug.warn("{}\n", str);
}
```

```
Hello
There
```

**Comment by mosullivan** [comment]
Apologies if this isn't the correct place, but how would you pass this to a C function that takes the an equivalent? 

For example:
```
var nameCount: usize = 4; //for example
var names: [*c][*c]const u8 = undefined;   
c_function(nameCount, &names);  // a c function that fills a const char** with data
```

**Comment by JohnathanFL** [comment]
This seems to compile at least:

```
// I believe the C function would be translated to something like this by zig
pub extern fn c_function(count: usize, data: [*c][*c]const u8) void;
...
var nameCount: usize = 4; //for example
var names: [4][]const u8 = undefined; 
c_function(nameCount, @ptrCast([*c][*c]const u8, &names));
```

If I'm understanding the [casts](https://ziglang.org/documentation/master/#Implicit-Cast-Arrays-and-Pointers) correctly here, &names gets implicitly cast from *[N]T to [*]T, which is then allowed to be cast to a C pointer.

**Comment by mosullivan** [comment]
Ah, I must have missed that in the casts section.  Thank you :)

**Comment by andrewrk** [comment]
`[]T` is a slice, not an array. A slice is a pointer and a length. A multi dimensional array looks like `[N][M]T`.

I'll leave this issue open to add a multidimensional array example to the docs.

**Comment by Gaai** [comment]
```
    var array1:  [8]u8             = .{ 1,2,3,4,5,6,7,8 };
    var array2d: [2][4]u8      = .{ .{1,2,3,4}, .{5,6,7,8} };
    var array3d: [2][2][2]u8 = .{ .{ .{1,2}, .{3,4} }, .{ .{5,6}, .{7,8} } };
```
Is kinda nice imho if know the lengths. Fits better with the other type definitions. Documentations has it like this: 
```
const mat4x4 = [4][4]f32{
    [_]f32{ 1.0, 0.0, 0.0, 0.0 },
    [_]f32{ 0.0, 1.0, 0.0, 1.0 },
    [_]f32{ 0.0, 0.0, 1.0, 0.0 },
    [_]f32{ 0.0, 0.0, 0.0, 1.0 },
};
```
Which is overly verbose if you ask me... But gives you the option to infer the length, although in the example it is given anyway.
