### ISSUE TITLE
"generating wrong code instead of compile error when loop using comptime var is not unrolled", again

### ISSUE THREAD

**Issue by lucascharlesmyers** [ziglang/zig#2895]
I seem to have stumbled on a new incarnation of #266. The following code compiles to an infinite loop in debug mode, and produces a runtime segfault in any of the release modes (Zig 0.4.0):

```zig
pub fn main() void {
    comptime var idx: u32 = 0;
    while (idx < 1) {
        const not_null: ?u32 = 1;
        _ = not_null orelse return;
        idx += 1;
    }
}
```

Without that `orelse return` line in there, we get the expected compile error:
```
infinite_loop.zig:3:5: error: control flow attempts to use compile-time variable at runtime
    while (idx < 1) {
    ^
infinite_loop.zig:6:13: note: compile-time variable assigned here
        idx += 1;
            ^
```

And of course, if the loop is `inline`, things work as expected. Something about the `orelse` seems to be tripping up `comptime` evaluation and in turn resulting in bad codegen, but I haven't investigated any further.

**Comment by helinwang** [comment]
One more case: https://github.com/ziglang/zig/issues/10578
