### ISSUE TITLE
Make primitive values not keywords

### ISSUE THREAD

**Issue by hryx** [ziglang/zig#2897]
#1803 was a grammatical cleanup that made all primitive types (`anyerror`, `void`, `bool`) into non-keywords. I think we could do the same for primitive values (`true`, `null`, `undefined`). Types and values are both just values, unlike keywords.

If it's anything like #1803 this will result in deleting code with no downside.

**Comment by andrewrk** [comment]
I realized there is a downside: #1802

Let's resolve these issues together.

**Comment by andrewrk** [comment]
Please see https://github.com/ziglang/zig/issues/1802#issuecomment-840196058 for more details here.

**Comment by hryx** [comment]
If I'm not mistaken, this is already done since 05cf449, right?

I back-ported this to C++ in #13343, for what it's worth (probably not much considering the focus on #6378).
