### ISSUE TITLE
I can not build example when I mix zig with C

### ISSUE THREAD

**Issue by heibor** [ziglang/zig#2905]
When I followed the example in the ziglang doc,  [Mixing Object Files](https://ziglang.org/documentation/0.4.0/#Mixing-Object-Files) , I run the `zig build` command, it show me that

`
zhen@mix$ zig build
/Users/zhen/works/zig/mix/build.zig:6:18: error: no member named 'addCExecutable' in struct 'std.build.Builder'
    const exe = b.addCExecutable("test");
                 ^
`

I am using MacOS + zig 0.4, are there some problems in the building system of zig 0.4?

**Comment by heibor** [comment]
It seems that there are many modifications in the std/build.zig, if so, who can give a working example for [Mixing Object Files](https://ziglang.org/documentation/0.4.0/#Mixing-Object-Files).

**Comment by dimenus** [comment]
@heibor the documentation is out of date, but the examples are up to date.

https://github.com/ziglang/zig/tree/master/example/mix_o_files

**Comment by andrewrk** [comment]
@heibor thank you for the report. I have updated the documentation and tested it to make sure it works. Please see 92e781baa147a7d07af4cb3c1f08c08bed8613e4 or wait a few hours until it goes live at https://ziglang.org/documentation/master/#Mixing-Object-Files. Note that the new documentation applies to master branch zig, not 0.4.0.

**Comment by heibor** [comment]
Thank you, I will try it.

**Comment by heibor** [comment]
There is no problem when I upgrade zig to the master. All things are OK. Thank you.
