### ISSUE TITLE
Programmatic type construction with @infoType

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#2906]
The ability to modify/infer types from other types is a key feature of generic programming.  It is proposed that the langauge add support to programmitcally create types from `comptime TypeInfo` structs with the `@infoType` function, i.e.

```zig
assert(u8 == @infoType(@import("builtin").TypeInfo.Int { .is_signed = false, .bits = 8, }));
```

The signature for `@infoType` would be:
```zig
@infoType(comptime info: @import("builtin").TypeInfo) type
```

The following comment describes how this feature can be used to implement the `SliceType` and `ArrayPointerType` functions which take an array/pointer type and return either the slice or array pointer variation of it while preserving the const/volatile/allowzero properties:

https://github.com/ziglang/zig/pull/2782#discussion_r304043243

The point being that without programmatic generation of types, the code requires `2^N` cases to return a type where `N` is the number of properties for that type (i.e. `const`/`volatile`/`allowzero`).  See the comment in the above link for further clarification.

**Comment by andrewrk** [comment]
This is #383
