### ISSUE TITLE
Support string interpolation 

### ISSUE THREAD

**Issue by catastrop** [ziglang/zig#2918]
Like JavaScript

**Comment by zimmi** [comment]
How should that work at runtime when the resulting size is not known in advance? Memory allocation must be explicit, so one must pass an allocator. Can you be more specific in your proposal?

You can already use `std.fmt` for this:
```zig
const std = @import("std");

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.direct_allocator);
    defer arena.deinit();

    const allocator = &arena.allocator;

    const greeting = "Hello";
    const name = "Inigo Montoya";
    const accusation = "killed my father";

    const message = try std.fmt.allocPrint(allocator, "{}. My name is {}. You {}. Prepare to die.\n", greeting, name, accusation);

    const stdout = try std.io.getStdOut();
    try stdout.write(message);
}
```

**Comment by catastrop** [comment]
My proposal is to write like this 

```zig
   const message = "{greeting}. My name is {name}. You {accusation}. Prepare to die.\n",
        
```

**Comment by zimmi** [comment]
Zig requires [Manual memory management](https://ziglang.org/#Manual-memory-management). Imagine that `greeting`, `name` and `accusation` are provided by the user of the program at runtime. How much memory do you need to allocate for the final `message`? It's only known at runtime, so you need to provide a memory allocator and handle the eventual failure.

There is an [open issue for Rust](https://github.com/rust-lang/rfcs/issues/1250) for the same thing, but it requires some serious compiler magic. Not sure this is a good fit for Zig, but that's not for me to judge.
