### ISSUE TITLE
libuserland dependencies are insufficient

### ISSUE THREAD

**Issue by Sahnvour** [ziglang/zig#2921]
In `CmakeLists.txt`, the target `libuserland` depends on some zig files used to provide the features implemented in zig.

The list is far from complete, because you can end up in a situation where a dependency of `libuserland`, say `build.zig`, depends on other zig files. If some of the other files are changed, one expects the code in `build.zig` to reflect that change, but the dependency is not propagated and `libuserland` is not recompiled.

I encountered this while trying to debug the stack traces code that's now also used in `libuserland`. We could instead make `libuserland` depend on the whole `std/`, and `zig0` will correctly handle the need for real recompilation.

**Comment by Sahnvour** [comment]
Nevermind, this seems irrelevant with the recent changes in the build process.

**Comment by andrewrk** [comment]
For what it's worth, this was issue #2585, which was solved by #2892.
