### ISSUE TITLE
error: use of undeclared identifier '_'

### ISSUE THREAD

**Issue by dawnarc** [ziglang/zig#2922]
Build [zig-vulkan-triangle](https://github.com/andrewrk/zig-vulkan-triangle) failed:

```
E:\Source\Git\zig-vulkan-triangle>zig build run
E:\Source\Git\zig-vulkan-triangle\build.zig:28:49: error: use of undeclared identifier '_'
    const full_in = try path.join(b.allocator, [_][]const u8{ dirname, in_file });
                                                ^
E:\Source\Git\zig-vulkan-triangle\build.zig:35:9: error: use of undeclared identifier 'full_in'
        full_in,
        ^
E:\Source\Git\zig-vulkan-triangle\build.zig:37:24: error: use of undeclared identifier 'run_cmd'
    exe.step.dependOn(&run_cmd.step);
```

**Comment by daurnimator** [comment]
Are you trying to build with latest master of zig? the `[_]` syntax is new since 0.4.0

**Comment by dawnarc** [comment]
> Are you trying to build with latest master of zig? the `[_]` syntax is newer than 0.4.0

I used 0.4.0 downloaded from release page: https://github.com/ziglang/zig/releases

**Comment by zimmi** [comment]
@dawnarc Can you try again with [master](https://ziglang.org/download/)? Zig is still evolving rapidly, so using the nightly master builds is your best bet.

**Comment by andrewrk** [comment]
I probably also need to update that example.

**Comment by dawnarc** [comment]
> I probably also need to update that example.

Thanks! I also tried again with master, but VS2019 cann't startup in may PC, and building with VS2017 failed.

**Comment by andrewrk** [comment]
> I probably also need to update that example.

actually it was already up to date and working with latest zig master
