### ISSUE TITLE
zig build: support the DESTDIR environment variable

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2929]
Extracted from #2928

When DESTDIR environment variable is defined, it should override where the install step puts files. When not defined, where to put files is determined by the installation prefix.

**Comment by daurnimator** [comment]
DESTDIR should not override, but get prefixed to the install dir.

**Comment by andrewrk** [comment]
d6d0bb054219da26a55f880f48f00902a4fbaf56
