### ISSUE TITLE
Clarify in docs that @field may be used as an lvalue

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#2941]
I was surprised (but happy) to find out that `@field` can be used as an lvalue (see https://github.com/ziglang/zig/issues/1099#issuecomment-514083951).
The docs currently say "access", which to me only implies readability.

As part of solving this issue, an example of using `@field` as an lvalue should be added to the documentation.

**Comment by vegai** [comment]
It seems to me that an example would highlight it the best. I'll make a PR soonish.
