### ISSUE TITLE
@bitCast of comptime_float

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#2949]
Should it be possible to use `@bitCast` on a comptime_float, if the bit size of the type being casted to (or maybe just signed and unsigned integers, or maybe just unsigned integers), is 16, 32, 64, or 128?

```
/home/shawn/git/zig-simd/build/float.zig:2:29: error: unable to @bitCast from type 'comptime_float'
 var f: u64 = @bitCast(u64, 512.0);
```

**Comment by daurnimator** [comment]
I would say no: `comptime_float`s have no defined layout, so bitcasting is ill-defined.

**Comment by shawnl** [comment]
@daurnimator  comptime_float *itsseslf* is ill defined. Look at #2794
