### ISSUE TITLE
Exit codes are casted to 64 bit?

### ISSUE THREAD

**Issue by Sobeston** [ziglang/zig#2950]
I recently messed up something and the binary I compiled (with zig build-exe) exited with error code -1,073,741,511 and upon searching for this error code I found nothing.   
-1,073,741,511 = 1111 1111 1111 1111 1111 1111 1111 1111 1100 0000 0000 0000 0000 0001 0011 1001
When I strip off the first 32 bits of the error code, I am left with error code C0000139 (entry point not found). 
This casting of error codes from 32 to 64 bits is bound to cause confusion.

Running zig 0.4.0 on windows 10 64 bit

P.S. I have yet single out what caused entry point not found to happen, but will create another issue when I do

**Comment by andrewrk** [comment]
Thanks for the issue @Sobeston. At this time, this issue tracker is for master branch zig issues only. There's also not enough information here to reproduce the problem.
