### ISSUE TITLE
Immutable struct instance fields

### ISSUE THREAD

**Issue by user00e00** [ziglang/zig#2952]
Is it currently possible to make a struct field immutable (constant) after the struct has been instantiated?

A quick test (zig 0.4) seems to indicate that the following is not allowed:
```zig
const S = struct{
  x : const f32,
}
```
Also, it should be considered how to deal with constant pointers to struct instances that are not immutable, e.g whether `y : const MutableStruct,` should be a compile error or not.

Related: #2479

**Comment by andrewrk** [comment]
> Is it currently possible to make a struct field immutable (constant) after the struct has been instantiated?

Nope that's not possible.
