### ISSUE TITLE
Compiler assertion when specifying alignment on empty struct

### ISSUE THREAD

**Issue by hryx** [ziglang/zig#2957]
I have no experience with alignment yet, so I don't know what's special about this or how to look into it. Apologies if it's a duplicate.

```zig
pub fn main() void {
    var s: struct {} align(4) = undefined;
}
```

```
Assertion failed. This is a bug in the Zig compiler.
???:?:?: 0x55d02c43a2c9 in ??? (???)
...
```

**Comment by fengb** [comment]
I'm pretty sure 0 sized variables can't have memory representation so it also cannot be aligned.

**Comment by hryx** [comment]
Makes sense, I figured my example was probably invalid. This can track the compiler bug at least.
