### ISSUE TITLE
Zig fs.File should expose a way to open a file for both reading and writing

### ISSUE THREAD

**Issue by CurtisFenner** [ziglang/zig#2959]
I want to be able to open a file for both reading and writing (seeking around the file while it is kept open). This is an operation supporting in Linux/Unix, and I believe also supported on Windows. However, Zig's `std.fs.File` only exposes a constructor for read-only and write-only.

The `std.fs.File.openHandle` could be used in combination with `os.open`, however there is no `open` for Windows in Zig.

If there were, the flag parameters aren't portable, so the flags that need to be passed depends on the operating system. Instead of pushing this onto the user, it should be encapsulated by the `std.fs.File` API, as it already is for read-only and write-only modes.

**Comment by Sobeston** [comment]
I believe this should be closed
