### ISSUE TITLE
Segmentation Fault when updating a global struct in an extern function

### ISSUE THREAD

**Issue by StephenCharles** [ziglang/zig#2960]
I just updated to version `0.4.0+74abc5ad` from `0.4.0+7c5ceb0c`. I believe I found a bug as this code worked in `0.4.0+7c5ceb0c`. This is on ArchLinux `5.1.15-arch1-1-ARCH`.

I define a var in global scope at top of main file:
```
const VIEWPORT_WIDTH = 1360.0;
const VIEWPORT_HEIGHT = 968.0;
var mouse_pos_last: Vec2 = Vec2.create([2]f32{ VIEWPORT_WIDTH / 2.0, VIEWPORT_HEIGHT / 2.0 });
```

Vec2 is a simple struct:
```
pub const Vec2 = struct {                                                                                                                                      
    data: [2]f32,
    pub fn create(verts: [2]f32) Vec2 {
        return Vec2{
            .data = verts,
        };
    }
    ... also has some functions defined in it
}
```

It is updated in an extern callback:
```
extern fn mouse_cursor_pos_callback(window: ?*c.GLFWwindow, x_pos: f64, y_pos: f64) void {
        const mouse_look_sensitivity: f32 = 0.02;
        const x_pos_32: f32 = @floatCast(f32, x_pos);
        const y_pos_32: f32 = @floatCast(f32, y_pos);
        var x_offset: f32 = x_pos_32 - mouse_pos_last.data[0];
        var y_offset: f32 = mouse_pos_last.data[1] - y_pos_32;
        mouse_pos_last.data[0] = x_pos_32; // this is where the segmentation fault is thrown
        mouse_pos_last.data[1] = y_pos_32;
       ...
}

pub fn main() !void {                                                                    
   ...                                                                      
    _ = c.glfwSetCursorPosCallback(window, mouse_cursor_pos_callback);          
   ...
}                                                                               
```

**Comment by daurnimator** [comment]
What is the implementation of `Vec2.create`?

**Comment by StephenCharles** [comment]
Updated description with `Vec2.create` implementation and added some constant definitions.

**Comment by andrewrk** [comment]
Hi @StephenCharles. Thanks for taking the time to file a bug report. Unfortunately, I'm going to have to throw the ball back in your court here - the next step for this issue is to provide a self-contained test case that demonstrates the problem. There's not enough information here to reproduce the issue. I'm happy to re-open once there is enough information.

**Comment by StephenCharles** [comment]
I updated my error branch to use the latest zig and the seg fault does not happen anymore. I guess we can consider this one solved. Thanks!
