### ISSUE TITLE
UEFI standard library support

### ISSUE THREAD

**Issue by nrdmn** [ziglang/zig#2967]
UEFI provides tables of pointers to the UEFI application's entry point which are used to access UEFI services. The tables look roughly like this (simplified):
```zig
const TableHeader = extern struct {
    // ...
    header_size: u32,
    // ...
};

const SystemTable = extern struct {
    hdr: TableHeader,
    con_in: ?*SimpleTextInputProtocol,
    con_out: ?*SimpleTextOutputProtocol,
    std_err: ?*SimpleTextOutputProtocol,
    boot_services: ?*BootServices,
    runtime_services: *RuntimeServices,
    // ... more attributes
};

const BootServices = extern struct {
    hdr: TableHeader,
    exit_boot_services: fn () void,
    // ... function pointers
};

const RuntimeServices = extern struct {
    hdr: TableHeader,
    // ... function pointers
    reset_system: fn () void,
    // ...
};

pub fn main(handle: *c_void, system_table: *SystemTable) {
    // ...
}
```
Attributes in SystemTable, BootServices, and RuntimeServices may or may not be implemented on the platform's firmware (depending on which version of UEFI it implements). To determine which are implemented, the UEFI specification urges to check the tables' length using TableHeader.header_size.

SystemTable.std_err provides a convenient way to output error messages.

BootServices may only be used during OS initialization while RuntimeServices can also be used during normal OS operation. UEFI applications are supposed to transition from initialization mode to normal operation mode using exit_boot_services(). After a successful call to exit_boot_services(), BootServices must not be used any more and SystemTable.con_in, .con_out, .std_err, and .boot_services should be set to NULL. This means after calling exit_boot_services() we can't use UEFI's std_err to write stack traces.

Certain RuntimeServices methods must not be called simultaneously.

What should access to these tables look like? Three proposals:
1. No wrappers. The user calls the methods from the tables directly and ensures their pointers are valid and no restricted runtime services are called simultaneously. This would mean panic and abort are not concurrency safe. The user would have to take care that after calling exit_boot_services() SystemTable.std_err and other attributes are set to null so that panic and abort don't attempt to access them.
1. Getters for methods that either return a pointer to the requested method or null if it is not available. Same issues as above.
1. Wrappers that check if function pointers are valid, if exit_boot_services() has been called yet, and that ensures certain methods aren't called simultaneously. On error, these would return an error value. We could probably write a concurrency safe standard library for uefi but the code would be littered with trys and catchs.

**Comment by andrewrk** [comment]
The null hypothesis is no wrappers. The programmer will manually provide their own panic handler and access the tables directly, ensuring correct behavior. This is reasonable to expect for a UEFI project. Any abstraction done in the standard library should not introduce overhead, or it should provide a way to opt out.

**Comment by nrdmn** [comment]
There are stuctures like SimpleTextOutputProtocol where its methods take a pointer to the struct. They look like this:

```zig
pub const SimpleTextOutputProtocol = extern struct {
    outputString: extern fn (*SimpleTextOutputProtocol, [*]u16) usize,
    // ... more function pointers
};
```
When I call outputString, I have to manually pass the pointer, like `uefi.con_out.?.outputString(uefi.con_out.?, &[_]u16{'H', 'e', 'l', 'l', 'o', 0});` Using wrappers would simplify this without introducing overhead:
```zig
pub const SimpleTextOutputProtocol = extern struct {
    _output_string: extern fn (*SimpleTextOutputProtocol, [*]u16) usize,

    pub fn outputString(self: *SimpleTextOutputProtocol, msg: [*]u16) usize {
        return self._output_string(self, msg);
    }
};

uefi.con_out.?.outputString(&[_]u16{'H', 'e', 'l', 'l', 'o', 0});
```

Would it be acceptable to use wrappers for SimpleTextOutputProtocol's methods?
