### ISSUE TITLE
Correct handling of address == 0

### ISSUE THREAD

**Issue by belse-de** [ziglang/zig#2983]
During embedded or kernel development some times you want to change the behaviour of interrupts at runtime by exchanging the interrupt service routines(ISR) for specific interrupts. For some systems the interrupt vector table (IVT) starts at address == 0. This is **not** a NULL pointer!

Atmel Atmega AVR Chips, 8086, z80, GameBoy and GameBoyColor are examples for this kind of this systems. 

In C/C++ this would be undefined behaviour. How does Zig handles this? Is this UB?
The below example compiles but feels like a hack. Especially since this uses the CPointer type
and C does not specifies this in a good manner. 

In addition I would like to specify this pointer as a pointer to an array of fixed length.
```
pub fn ISR_REST() void {
    // reset hardware to default values
}

pub fn main() void {
    var InterruptVectorStartPtr: [*c]*const fn()void = @intToPtr([*c]*const fn()void, 0);
    InterruptVectorStartPtr.* = &ISR_REST;    
}
```

**Comment by andrewrk** [comment]
are you aware of [the allowzero pointer attribute](https://ziglang.org/documentation/master/#allowzero)?

**Comment by belse-de** [comment]
Sorry I actually overlooked the _allowzero_ tag.
This was what I was looking for, 
but failed the FTFM part by looking for references to _NULL_ in the documentation.
Old habits die hard.

And yes, 
the linker script solution is the better one.

Thank you for help
You are doing great work here.
So far I like your language very much.
