### ISSUE TITLE
Badly formatted error message when cached imported file is deleted

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#2986]
If you have a project that imports a file, and you build it with caching enabled, and then you delete that file but forget to update the import, you get this (here main.zig is trying to import asdf.zig):

```
dbandstra@dbandstra-desktop:~/oxid/bugtest$ zig build-exe main.zig  --cache-dir blah --name dang --cache on
Unable to open /home/dbandstra/oxid/bugtest/asdf.zig
: file not founddbandstra@dbandstra-desktop:~/oxid/bugtest$ 
```

Whereas normally when a file is missing you get a nicer looking error with colors and stuff:
```
dbandstra@dbandstra-desktop:~/oxid/bugtest$ zig build-exe main.zig  --cache-dir blah --name dang --cache on
/home/dbandstra/oxid/bugtest/main.zig:2:14: error: unable to find 'asdf.zig'
const damn = @import("asdf.zig");
             ^
```

**Comment by Vexu** [comment]
This seems to work correctly in the self-hosted compiler but I'm not sure how to add a test for it.
