### ISSUE TITLE
os.getrandom on freebsd should use the `getrandom` C function

### ISSUE THREAD

**Issue by euantorano** [ziglang/zig#2993]
As of FreeBSD 12, FreeBSD now has a [`ssize_t getrandom(void *buf, size_t buflen, unsigned int flags);`](https://www.freebsd.org/cgi/man.cgi?query=getrandom&sektion=2&manpath=freebsd-release-ports) function that could be used by [`os.getrandom()`](https://github.com/ziglang/zig/blob/master/std/os.zig#L102) in the same way that `getrandom()` is used on Linux.

**Comment by andrewrk** [comment]
Since FreeBSD 12 is the minimum supported version, we can always use the libc version on FreeBSD. (The linux one has a libc version check)

**Comment by euantorano** [comment]
Awesome, that makes life easy. I'll see about creating a PR for this.
