### ISSUE TITLE
don't force enums with one member to have a tag type of comptime_int

### ISSUE THREAD

**Issue by dbandstra** [ziglang/zig#2997]
Apparently, this is intentional. I just saw it mentioned in the `@enumToInt` docs. But this makes it hard to use `@enumToInt` and `@intToEnum` at runtime. I have to work around it by initializing an enum value to undefined or something.

```zig
const T = enum { One };

pub fn main() void {
    var i = @enumToInt(T.One);
}
```

Error:
```
/home/dbandstra/oxid/test.zig:4:5: error: variable of type 'comptime_int' must be const or comptime
    var i = @enumToInt(T.One);
    ^
```

```zig
const std = @import("std");

const T = enum { One };

pub fn main() void {
    var i: @TagType(T) = 0;
    // would use this with @intToEnum
}
```

Same error.

Can tag type of one-element enums be changed to `u0`? Zero would be allowed as a value of `u0`, right? What's the use of being able to evaluate it at comptime?

Use case: I'm modelling game menus as enums (for the cursor position). I have some generic code to handle various common behaviours, and I just tried to make a menu with only one item.

**Comment by andrewrk** [comment]
Thanks for taking the time to describe this use case. I agree the behavior needs to be changed. It's pretty surprising that enums with one item break the pattern in this way, so I think in your example it should be u0 as you said, with zero as the value. However, the enum would allow the tag value to be overridden and set to any integer type including comptime_int, which solves the other use case. I can't remember what it was, but it seemed valid at the time. I'll be sure to describe it here when I refresh my memory.

**Comment by dbandstra** [comment]
It looks like something is going on with one-member enums even when you give an explicit tag type.

```zig
const T = enum(u2) { One };

pub fn main() void {
    var i = @enumToInt(T.One);
}
```
Output:
```
Assertion failed. This is a bug in the Zig compiler.
```
But it works if the first line is `const T = enum(u2) { One, Two };`.

`@compileError(@typeName(@TagType(T)));` prints `u2`.

**Comment by andrewrk** [comment]
That was a stray assert; I created a local commit which fixes this. After the tests pass locally I'll push it to master.

**Comment by andrewrk** [comment]
b87686dfa094770e96da33fb23a7d011a168157c
