### ISSUE TITLE
add function to std.json.Value that acts like dump on an std.io.OutStream

### ISSUE THREAD

**Issue by ntgraff** [ziglang/zig#3008]
I had to do this for a personal project, and it is essentially just copy-paste of `std.json.Value.dump/dumpIndent` but with `debug.warn` replaced with `OutStream.print`. This would allow for easy conversion of parsed json back to text. I propose that we add a function that prints to an `OutStream`, and then make `dump` and `dumpIndent` use those functions. If this is a desired thing, I can just move over my code and open a pull request.

**Comment by daurnimator** [comment]
#3155

**Comment by SebastianKeller** [comment]
That might be solved with the `emitJson` addition https://github.com/ziglang/zig/pull/3522
