### ISSUE TITLE
Should `os.getrandom()` fill the supplied buffer or should it be altered to return the number of bytes read?

### ISSUE THREAD

**Issue by euantorano** [ziglang/zig#3012]
Currently `os.getrandom` has the following signature: `pub fn getrandom(buf: []u8) GetRandomError!void`. However, it looks like the buffer may not always be filled fully (eg: Linux's `getrandom()` returns the number of bytes read which may be less than the amunt requested) - forgive me if I'm wrong, I'm still getting to grips with Zig's standard library.

I think the function signature should either be changed to `pub fn getrandom(buf: []u8) GetRandomError!usize` or the function should guarantee that the buffer is filled.

**Comment by andrewrk** [comment]
it should certainly fill the supplied buffer.

```zig
    stream.readNoEof(buf) catch return error.Unexpected;
```

docs for readNoEof:

```zig
        /// Same as `readFull` but end of stream returns `error.EndOfStream`.
        pub fn readNoEof(self: *Self, buf: []u8) !void {
```

docs for readFull

```zig
        /// Returns the number of bytes read. If the number read is smaller than buf.len, it
        /// means the stream reached the end. Reaching the end of a stream is not an error
        /// condition.
        pub fn readFull(self: *Self, buffer: []u8) Error!usize {
```

I do think there is an issue here though, because looking at the implementation of readNoEof the implementation does not match the documentation. My suggestion would be:

```diff
--- a/std/io.zig
+++ b/std/io.zig
@@ -146,7 +146,7 @@ pub fn InStream(comptime ReadError: type) type {
 
         /// Same as `readFull` but end of stream returns `error.EndOfStream`.
         pub fn readNoEof(self: *Self, buf: []u8) !void {
-            const amt_read = try self.read(buf);
+            const amt_read = try self.readFull(buf);
             if (amt_read < buf.len) return error.EndOfStream;
         }
```

If that passes the tests then I think it's a good fix to make.

**Comment by euantorano** [comment]
Ok, I’ll make a PR to update the documentation for getrandom. I’ve noticed a couple of other issues with it too, which I’ll open an issue for.

**Comment by andrewrk** [comment]
I agree with your comment here: 

> I think the function signature should either be changed to `pub fn getrandom(buf: []u8) GetRandomError!usize` or the function should guarantee that the buffer is filled.

This means that the function signature itself is successfully communicating that it will fill the entire buffer. I'm concerned that adding docs to clarify this point will only raise the question in someone's mind, "what, are there other places in the std lib where there's no way to find out a buffer has only been partially filled?"

I think we should simply fix the bug.

**Comment by euantorano** [comment]
Ok, will open a PR for that.
