### ISSUE TITLE
RtlGenRandom definition is incorrect

### ISSUE THREAD

**Issue by euantorano** [ziglang/zig#3015]
The definition for `RtlGenRandom` in `std/os/windows/advapi32.zig` is incorrect:

```
pub extern "advapi32" stdcallcc fn SystemFunction036(output: [*]u8, length: usize) BOOL;
pub const RtlGenRandom = SystemFunction036;
```

The actual definition is:

```
BOOLEAN RtlGenRandom(
  PVOID RandomBuffer,
  ULONG RandomBufferLength
);
```

Where `ULONG` is a 32 bit unsigned number.

Note that this will also require a change in `std/os/windows.zig` to handle calls to this function as `usize` is 64 bits on 64 bit systems.

**Comment by andrewrk** [comment]
> Note that this will also require a change in `std/os/windows.zig` to handle calls to this function as `usize` is 64 bits on 64 bit systems.

:+1:  I do believe this is the correct place for the loop to go: std/os.windows.zig can have the API with `usize`.
