### ISSUE TITLE
Proposal: support octal escape sequences

### ISSUE THREAD

**Issue by fengb** [ziglang/zig#3018]
We briefly discussed this in IRC and I think it was a weak "yes" for consistency with number literals.

Syntax: `"\oMNN"` where M <= 3

Rationale:
1. We already have octal literals. Matching literals and string escapes would be pretty natural, especially when hex already does.
2. C supports octal escapes.
3. Some things are historically encoded in octal — e.g. shell escape sequences `\033[31mRed`

Drawbacks:
1. Extra syntax to support
2. Octals are dumb. M <= 3 is especially silly.

**Comment by shawnl** [comment]
> Octals are dumb. M <= 3 is especially silly.

I think octals should be entirely removed. They just don't make sense with 8-bit bytes.

**Comment by andrewrk** [comment]
"consistency with number literals" is a good rationale. But I think that there's an even better rationale for not doing it, which is that we can easily get away with not doing it.

Also I don't think we need binary escape sequences inside string literals.
