### ISSUE TITLE
Proposal: async prefix syntax

### ISSUE THREAD

**Issue by andersfr** [ziglang/zig#3031]
The syntax specifies `async<PrefixExpr>` which is valid and non-ambiguous.

The problem is that it undermines parsing optimisations on expressions by terminating with a symbol that is also a legal infix operator (greater than). If you have seen c++ templates you understand the pain of parsing `>`.

Parsing strictly according to the grammar specification requires deep recursion on the most common constructs. This recursion/nesting can be optimised away but not if symbols are overloaded in this way.

I propose to use `async(PrefixExpr)` instead.

This is also consistent with how other function modifiers are used, e.g. `align(8)`, `linksection(".text")`

**Comment by daurnimator** [comment]
The allocator is being removed from `async` very very soon. See the `rewrite-coroutines` branch.

**Comment by andersfr** [comment]
If the allocator disappears then this proposal becomes obsolete.

**Comment by andrewrk** [comment]
I opened the draft PR #3033 so that it's more visible
