### ISSUE TITLE
Too restrictive return type in std.math.min

### ISSUE THREAD

**Issue by Ekdohibs** [ziglang/zig#3035]
Since https://github.com/ziglang/zig/commit/2cd5e555818583e77e5601d43d55339e8c4017b0, the return type of std.math.min is made more restrictive in some situations. However, it seems to me that it is made too restrictive: if `A` and `B` are both signed ints (for instance, `i16` and `i32`), then the most restrictive type able to contain the result is the widest of the two. Indeed, in the above case, the minimum might be as little as -2^31, which does not fit in an `i16`.
Likewise, floats are always signed and the return type should be the widest of the two.
I am not sure about comptime ints and floats: should the return type depend on the comptime value?

**Comment by andrewrk** [comment]
Thanks for the report. This is a good argument in favor of inferred return types (#447).
