### ISSUE TITLE
No compile error when returning incorrect aliased struct

### ISSUE THREAD

**Issue by Tetralux** [ziglang/zig#3039]
This should have been a compile error:

https://github.com/Tetralux/zig/blob/24aea24c22627c415d81339749e8a94a7239af1a/std/http/headers.zig#L173

`.iteratorConst` returns a completely different struct to `HttpList.Iterator`...

_Originally posted by @Tetralux in https://github.com/ziglang/zig/pull/3037#issuecomment-520158909_

**Comment by Tetralux** [comment]
Note that `iteratorConst` is defined here:

https://github.com/Tetralux/zig/blob/24aea24c22627c415d81339749e8a94a7239af1a/std/array_list.zig#L278

**Comment by andrewrk** [comment]
can you come up with a reduction?
