### ISSUE TITLE
Provide better hashing abstractions

### ISSUE THREAD

**Issue by Sahnvour** [ziglang/zig#3041]
@dimenus brought the point on IRC that `autoHash` has confusing behaviour for slices.

Current (and likely correct) behaviour is that pointers and slices are not followed.
However it can be confusing for slices especially, as people may expect `autoHash` to look at their content, for example in the case of `[]const u8` which are frequently used as strings.

The proposal is to change `autoHash` to emit a compile error when it is passed a slice type, and to advise using a more specific hashing strategy. I think that's a good way of getting read of possible confusion, and it touches other subjects:
1. The std lib should then offer an alternative to `autoHash`, being explicitely "shallow" or "deep" (but what about struct members and cycles when following pointers ?).
2. These abstractions should ideally work with any hashing algorithm present in the std lib, meaning it requires a common API.
3. The `HashMap` API should reflect these changes and make it easy to work with

**Comment by daurnimator** [comment]
I mentioned this in the original PR that changed it: https://github.com/ziglang/zig/pull/2797#discussion_r299272979

**Comment by Sahnvour** [comment]
Started a bit on this (barebones etc.), looking for feedback. Does this seem sensible ? https://github.com/Sahnvour/zig/commit/f15b8de4a76474550826bd681b538a8ad65c0a93

**Comment by daurnimator** [comment]
> Started a bit on this (barebones etc.), looking for feedback. Does this seem sensible ? [Sahnvour@f15b8de](https://github.com/Sahnvour/zig/commit/f15b8de4a76474550826bd681b538a8ad65c0a93)

Send a draft PR (when you send a PR use the drop down to select Draft) so that comments can be tracked?

**Comment by Sahnvour** [comment]
I'm not looking for review on the implementation details yet, more on the general idea and if it makes sense to go for it. But I will open a PR nonetheless.

**Comment by andrewrk** [comment]
I believe this is now resolved with #3060. Please re-open @Sahnvour if there is something else to do here.
