### ISSUE TITLE
-mllvm error messages don't emit valid commands in advice

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#3045]
`-mllvm` error messages don't emit valid commands in advice, e.g.

```
$ zig build-exe -mllvm --build-id=23 myfile.zig
zig (LLVM option parsing): Unknown command line argument '--build-id=23'.  Try: 'zig (LLVM option parsing) -help'
zig (LLVM option parsing): Did you mean '-print-mod=23'?
```

**Comment by andrewrk** [comment]
I've updated the CLI help text to note that the `-mllvm` feature is unsupported. Any desired use of this feature should explain the use case and ask for a supported way of solving the problem.
