### ISSUE TITLE
Compiler assertion (broken by assignment-result-loc)

### ISSUE THREAD

**Issue by dbandstra** [ziglang/zig#3046]
This broke when the `assignment-result-loc` branch was merged.

It seems to happen when setting a field of a global struct value, to a value returned by a function call with a catch handler

```zig
const SomeStruct = struct {
    field: i32,
};

fn couldFail() anyerror!i32 {
    return 1;
}

var some_struct: SomeStruct = undefined;

pub fn main() void {
    some_struct = SomeStruct {
        .field = couldFail() catch |_| i32(0),
    };
}
```

Output:

```
when analyzing /home/dbandstra/oxid/test.zig:13:9: assertion failed. This is a bug in the Zig compiler.
```

---

I'm also hitting it in my Oxid project. This line is hitting it ([link](https://github.com/dbandstra/oxid/blob/a7cafc30b0c219bbd2c158229ba0a176ce29ebfe/src/oxid.zig#L333)):

```zig
   g.audio_module = audio.MainModule.init(&hunk.low(), audio_buffer_size) catch |err| { ... };
```

But I think it goes away if I change it to this:

```zig
   const blah = audio.MainModule.init(&hunk.low(), audio_buffer_size) catch |err| { ... };
   g.audio_module = blah;
```

Definition of `audio.MainModule.init` [here](https://github.com/dbandstra/oxid/blob/a7cafc30b0c219bbd2c158229ba0a176ce29ebfe/src/oxid/audio.zig#L58). Like my example above it's doing error handling inside the struct value construction.

As for `g.audio_module`, `g` is a pointer to a global.

**Comment by FireFox317** [comment]
I had a look at this and changing the type of `some_struct` to `*SomeStruct` gets rid of the issue. 

In the function `ir_analyze_struct_field_ptr` in ir.cpp it checks if the `struct_ptr` is comptime known (ir.cpp:17064) and it thinks that `var some_struct: SomeStruct = undefined;` is actually comptime, but it shouldn't be comptime known right @andrewrk ?
