### ISSUE TITLE
FixedBufferAllocator does not seem to reclaim freed memory

### ISSUE THREAD

**Issue by jonathangjertsen** [ziglang/zig#3049]
See example below - I have a function where I ask the allocator for a byte and then immediately free it. Then I call it 1000 times. I would expect this to work fine since I always free up the memory used, but it returns error.OutOfMemory after buffer_size+1 iterations. Have I misunderstood something about the usage of the allocator?

---

```zig
const std = @import("std");
const warn = std.debug.warn;

const buffer_size = 10;

pub fn main() void {
    var buf = [_]u8{0} ** buffer_size;
    const allocator = &std.heap.FixedBufferAllocator.init(&buf).allocator;

    var i: usize = 1;
    while (i <= 1000) : ({
        i += 1;
    }) {
        useFixedAllocator(allocator) catch |err| {
            switch (err) {
                error.OutOfMemory => {
                    warn("Ran out of memory during call #{}\n", i);
                    break;
                },
            }
        };
    } else {
        warn("Everything went fine.\n");
    }
}

pub fn useFixedAllocator(allocator: *std.mem.Allocator) !void {
    var bytes: []u8 = try allocator.alloc(u8, 1);
    defer allocator.free(bytes);
}
```

Expected output

```
> zig build-exe oom.zig && oom
Everything went fine.
```

Actual output

```
> zig build-exe oom.zig && oom
Ran out of memory during call #11
```

**Comment by daurnimator** [comment]
> Have I misunderstood something about the usage of the allocator?

You need to keep the allocator itself around (it has internal state!).
```zig
var fixedBufferAllocator = std.heap.FixedBufferAllocator.init(&buf);
const allocator = &fixedBufferAllocator.allocator;
```

**Comment by jonathangjertsen** [comment]
> ```zig
> var fixedBufferAllocator = std.heap.FixedBufferAllocator.init(&buf);
> const allocator = &fixedBufferAllocator.allocator;
> ```

With this change, there is still an error.OutOfMemory during the 11th call.

**Comment by daurnimator** [comment]
Oh. yeah. `FixedBufferAllocator` doesn't re-use memory; this is expected.

**Comment by jonathangjertsen** [comment]
OK, interesting. That's not how I expected it to behave, but I suppose this will all become clearer when the standard lib has documentation 😅

**Comment by r4gus** [comment]
The fact that you're able to call `free` on an `Allocator` created with `std.heap.FixedBufferAllocator.init(&buf).allocator` is bad design. One should at least get a compiler warning when using the function with a fixed buffer.
