### ISSUE TITLE
Proposal: @inbounds builtin

### ISSUE THREAD

**Issue by andersfr** [ziglang/zig#3051]
After posting bug/proposal #3009 I thought that having a try before arithmetic was intended to give some sort of overflow/underflow runtime detection. This doesn't seem to be the case although it may be useful to detect without triggering panics.

Proposal is to have an `@inbounds(Expr)` builtin that raises and `error.Overflow` or `error.Underflow` if the contained expression at any point would panic in a safe build for the same reason. This does of course disable the normal safe behaviour for the contained expression because the programmer has opted in to deal with the error condition explicitly.

Trying to implement this without compiler support almost always results in the optimizer deciding that it is a noop because overflowing is considered undefined behaviour. LLVM has support for this already and I assume that is how the Zig safe builds implement the panic.

**Comment by daurnimator** [comment]
> Trying to implement this without compiler support almost always results in the optimizer deciding that it is a noop because overflowing is considered undefined behaviour.

You should be able to implement it with `@setRuntimeSafety`?

**Comment by andrewrk** [comment]
Have a look at the std.math functions. There's one for every operation that can overflow

**Comment by andersfr** [comment]
Somehow I missed those functions. That implementation is much better anyways.
