### ISSUE TITLE
Misleading compile error for missing library symbols

### ISSUE THREAD

**Issue by eagle2com** [ziglang/zig#3059]
Forgetting to link the library corresponding to the header file reports the header file as missing, instead of the symbols.
I'm using the master branch commit 98183e47436699f6e5eab200061c46eec342806e

```
// file: build.zig
const Builder = @import("std").build.Builder;

pub fn build(b: *Builder) void {
    const mode = b.standardReleaseOptions();
    const exe = b.addExecutable("issue_header", "src/main.zig");
    exe.setBuildMode(mode);
    exe.linkSystemLibrary("c");
    // --> Uncomment the following line for the error to disappear <--
    // exe.linkSystemLibrary("glfw");
    exe.install();

    const run_cmd = exe.run();
    run_cmd.step.dependOn(b.getInstallStep());

    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);
}
```

```
// file: main.zig 
const std = @import("std");
const c = @cImport({
    @cInclude("GLFW/glfw3.h");
});

pub fn main() anyerror!void {
    _ = c.glfwInit();
    defer c.glfwTerminate();
}
```

building:
```
$ zig build run
~/dev/zig/issue_header/src/main.zig:2:11: error: C import failed
const c = @cImport({
          ^
~/dev/zig/issue_header/zig-cache/o/FaEw-tNImB_Zk3zuBT7bqYfVVBxk5xAPJaOrbF7C5QAoMyPA0J1dHRH6MC5EBW3U/cimport.h:1:10: note: 'GLFW/glfw3.h' file not found
#include <GLFW/glfw3.h>
         ^
```

**Comment by andrewrk** [comment]
I believe this is working as designed. Idea being that until you choose to link a system library, zig is not even looking at your system (`/usr/include`) for header files. Note that libc is special; zig provides it and does not need to use your system libc.

**Comment by eagle2com** [comment]
Ah, I see. This behavior change (no longer looking at system header files) is indeed mentioned in the 0.4.0 release notes, my bad, I did not read them carefully enough. 
I'm quite new to zig (I absolutely love it, thank you for doing this) and the amount of changes and some of their consequences was a tad overwhelming at first.

This is such a particular situation (single linked library, forgot to link it), that it should probably not even need a note in the compile error. I guess a mention of this behavior will be in the documentation anyway (cannot find it right now).

I would say this issue can be closed then.
