### ISSUE TITLE
LLVM Error on @fence(.Monotonic) 

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#3082]
`@fence(.Monotonic)` results in: 
> fence instructions may only have acquire, release, acq_rel, or seq_cst ordering.
>   fence monotonic, !dbg !1458
> fence instructions may only have acquire, release, acq_rel, or seq_cst ordering.
>   fence monotonic, !dbg !1463
> LLVM ERROR: Broken module found, compilation aborted!

**Comment by andrewrk** [comment]
This should be a contributory friendly issue if anyone wants to take a crack at it. Here's the relevant code:

```c++
static IrInstruction *ir_analyze_instruction_fence(IrAnalyze *ira, IrInstructionFence *instruction) {
    IrInstruction *order_value = instruction->order_value->child;
    if (type_is_invalid(order_value->value.type))
        return ira->codegen->invalid_instruction;

    AtomicOrder order;
    if (!ir_resolve_atomic_order(ira, order_value, &order))
        return ira->codegen->invalid_instruction;

    IrInstruction *result = ir_build_fence(&ira->new_irb,
        instruction->base.scope, instruction->base.source_node, order_value, order);
    result->value.type = ira->codegen->builtin_types.entry_void;
    return result;
}
```

It should check for the wrong enum values and emit compile errors. One can look at nearby code to see how to do this.
