### ISSUE TITLE
Bad LLVM generated when asigning to struct or union fields that are not optionals with a function that returns an optional

### ISSUE THREAD

**Issue by ntgraff** [ziglang/zig#3097]
This code generates bad LLVM IR
```zig
// main.zig
fn maybe(is: bool) ?u8 {
    if (is) return u8(10) else return null;
}

const U = union {
    Ye: u8,
};

const S = struct {
    num: u8,
};

pub fn main() void {
    var u = U{ .Ye = maybe(false) };
    var s = S{ .num = maybe(false) };
}
```

This is outputed at compile time:
```
> zig build-exe main.zig
Call parameter type does not match function signature!
  %0 = getelementptr inbounds %U, %U* %u, i32 0, i32 0, !dbg !13400
 { i8, i1 }*  call fastcc void @maybe(i8* sret %0, i1 false), !dbg !13401
Call parameter type does not match function signature!
  %1 = getelementptr inbounds %S, %S* %s, i32 0, i32 0, !dbg !13403
 { i8, i1 }*  call fastcc void @maybe(i8* sret %1, i1 false), !dbg !13404
LLVM ERROR: Broken module found, compilation aborted!
```

**Comment by daurnimator** [comment]
This is a bug (any LLVM Broken module error is). However note that you're trying to assign an optional u8 to a non-optional u8.

**Comment by Vexu** [comment]
Fixed in master.
```
a.zig:55:27: error: expected type 'u8', found '?u8'
    var u = U{ .Ye = maybe(false) };
                          ^
```

**Comment by pixelherodev** [comment]
There's a lot of "compiler bugs" like this that are really just the compiler not detecting that your code is invalid (though as Vexu mentioned, this is rapidly improving).

The real concern I have is that my default assumption at this point when seeing "borked module" is "oops my code is bad," which isn't a good thing if I run into a real compiler bug.

**Comment by Vexu** [comment]
Currently the error would be "broken LLVM module found: Call parameter type does not match function signature! ..." but it could be made clearer by adding "This is a bug in the Zig compiler." to the end.
