### ISSUE TITLE
CC environment variable with multiple arguments

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#3100]
Zig seems to have issues if the `CC` environment variable has multiple arguments.  As I understand, tools generally allow the `CC` environment variable to contain not only the compiler but also default arguments for the compiler, i.e.
```bash
CC="cc -march=arm -g"
$CC hello.c
```

It looks like there are some places in the code where this mechanism isn't supported.  Look for `"CC"` in `libc_installation.cpp` and `libc_installation.zig`.

**Comment by nektro** [comment]
did you mean `zig cc` ? what error did you get?

**Comment by marler8997** [comment]
Apologies for the terse issue, I think I made this issue while I was in the middle of something else so it's missing some details.  In any case, I've taken a look at the Zig source code and based on the code I believe this issue has been fixed, see https://github.com/ziglang/zig/blob/83a668195526df745362b1174bfd643a0cdfb128/src/libc_installation.zig#L706
