### ISSUE TITLE
Absolute Paths not working with build-obj

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#3102]
Reproduce with:
```bash
$ touch foo.zig
$ zig build-obj --name /tmp/foo foo.zig
unable to write object file .//tmp/foo.o: No such file or directory
```

Zig is prefixing the `--name` argument with `./` for some reason?

**Comment by daurnimator** [comment]
it gets prefixed with the target directory. Note that `name` is used in a few places including e.g. the soname for a shared library.

**Comment by marler8997** [comment]
How would I direct the output file to /dev/null?

**Comment by andrewrk** [comment]
`--name` is not a path. Feel free to propose for it to work differently, but this is a misunderstanding of the CLI.

**Comment by marler8997** [comment]
Yes I don't have a good grasp on the reasoning behind each command-line option.  There doesn't seem to be a good source of documentation on it and it can be hard to understand the "spirit" behind each one from looking at the source.

Is one of you able to tell me how you would translate the `-o` option from C compilers to Zig?  Would you set `--output-dir` to an empty string and then set the path to `--name`?

Also, should it be an error if name contains slashes and/or backslashes then?  If it's not a path then would that be an error?

**Comment by andrewrk** [comment]
Let's discuss over in #3089. That's what you're actually trying to do, right?
