### ISSUE TITLE
Zig accepts wrong field name

### ISSUE THREAD

**Issue by PeyTy** [ziglang/zig#3185]
Moving from reddit to here. Just in case. Feel free to close if a duplicate or known bug (is this a bug?)

https://www.reddit.com/r/Zig/comments/cpquil/made_a_simple_paint_program_with_zig_and_sdl2/

https://gist.github.com/tuket/3b657d8ccadb54ca69a9c0ac4d387789

`.colorc` on line 32

**Comment by andrewrk** [comment]
The function is never called, so it is never analyzed

 #3028
