### ISSUE TITLE
Unexplained punishing slowdown due to error unions in return type

### ISSUE THREAD

**Issue by Tetralux** [ziglang/zig#3191]
[This code](https://p.teknik.io/Raw/qb07Y), compiled with `--release-fast`, now runs much slower than it did when first written, a couple of days ago.
It originally printed values of `12.5 ns` and `235 ns`; now it prints more like `144 ns` and `235 ns`.

It turns out that, with @mikdusan's help, changing `try parseFloat(...)` in `main` to `parseFloat(...) catch unreachable` fixes the problem.
This was not necessary before.

Maybe it's going out to main memory for every iteration of the loop, whereas before the error union's bool and inner value may have been optimized to be on the stack, and so remained either in the cache or registers?

Either way, this is a punishing slowdown.

**Comment by Tetralux** [comment]
Seems like 42cc4a406bd4d037f4203fa2ebca2853db33c780 caused the slowdown observed here.

**Comment by Tetralux** [comment]
To put it a different way, [this](a4ce10df8087e7051340e14e4acd018092f935f0) is the first bad commit.

**Comment by Tetralux** [comment]
Okay. Fun story.

Comment out this line
https://github.com/ziglang/zig/blob/071ca00574df355a76fd8e6b74f8fee65e934bdd/std/mem.zig#L342

The example runs 13.5 times faster.

**Comment by Tetralux** [comment]
So it turns out that if you pass string literals to `parseFloat` it's fast when you remove that line, and slow if you don't.

But if you randomly generate the string...
```zig
var rng = std.rand.DefaultPrng.init(time.timestamp());
const digits = "0123456789";
var N = rng.next() % 5 + 10;
var s = try std.debug.global_allocator.alloc(u8, N);
for (s) |*ch| {
    var n = rng.next() % digits.len;
    var c = digits[n];
    ch.* = c;
}
```
Now it's down to `30ns` - Not quite down to `12`, but a damn-sight closer.

BUT... removing the check from `mem.eql` AND using randomly generated strings gets you down to `27ns`.

Also note that all of these effects are worse for `std.fmt.parseFloat`.

**Comment by andrewrk** [comment]
It's not time to put effort into this yet. Once the language has stabilized enough that we have meaningful progress on self-hosted, performance tracking makes sense.  #3199

**Comment by Tetralux** [comment]
@andrewrk In that case I suggest we leave this open so we don't forget it's a problem until it's fixed in self-hosted.

**Comment by Tetralux** [comment]
.. especially considering how bad the performance ends up being.
