### ISSUE TITLE
@compileLog should resolve lazy values

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#3193]
```zig
    const S = packed struct {_1: u1, x: u7, _: u24};
    @compileLog(@sizeOf(S));
```

Gives me 
```
| (lazy value)
```

I can't see any reason for that value to be lazy: is there a way to force evaluation?

(Found while investigating https://github.com/ziglang/zig/issues/2627#issuecomment-529169434 )

**Comment by andrewrk** [comment]
I think `@compileLog` should force it.
