### ISSUE TITLE
format C/C++ code

### ISSUE THREAD

**Issue by ayazhafiz** [ziglang/zig#3205]
Does this project have a C/C++ formatting configuration? If not, will it accept one? I am investigating some issues and feel that it would be nice if a consistent style was enforced across the repo.

**Comment by andrewrk** [comment]
No. Generally, try to match the style around you, and it's OK if you change the style of lines to your preference that you modify for other reasons. But I'm not interested in spending any effort on style or  formatting, let's please focus on the more important stuff.
