### ISSUE TITLE
How to destroy the memory of the string field in JSON

### ISSUE THREAD

**Issue by heibor** [ziglang/zig#3208]
I wrote a test to use std.json, [the code is here](https://gist.github.com/heibor/49ca6b5455eeaeff18bd212730166840).

In the line 57, I want to destroy the memory for the path, butIt seems that the memory leaked.

Is there a way to destroy the momory for the variable `path`?

**Comment by tiehuis** [comment]
When the Parser is used to construct a tree of json objects, these are allocated using an arena allocator. It isn't possible to free memory for a single object in the tree with the current api.

I'm not particularly attached to any method of handling objects. My initial thought for using an arena was to speed up the allocation of many objects and simplify clean-up. Also, I considered that the use-case for a tree is typically as a query object and you want to keep all values in the tree around until you are done. Open to any suggestions to change if it makes sense.
