### ISSUE TITLE
Error message "assertion failed. This is a bug in the Zig compiler." in export fn

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#3214]
The compiler crashes while building a static library with the error "assertion failed. This is a bug in the Zig compiler." in this code:
```zig
export fn init(register_slice_size: usize, init_instructions: [*]u32, instructions_len: usize, init_ip: usize, init_callbacks: [*]InstructionCallback, callbacks_len: usize) u8 {
    instructions = heap.allocator.alloc(u32, instructions_len) catch return 1; // crashes at the beginning of this line
    instructions.ptr = init_instructions;
    ip = init_ip;
    callbacks = heap.allocator.alloc(InstructionCallback, callbacks_len) catch return 1;
    callbacks.ptr = init_callbacks;
    registers = heap.allocator.alloc(u32, register_slice_size) catch return 1;
    for(registers) |*r| {
        r.* = 0;
    }
    return 0;
}
```
Definition of `InstructionCallback`:
```zig
pub const InstructionCallback = fn(
    args: []u32,
    ip: *usize,
    registers: *[]u32
    ) void;
```
The full error message:
```
when analyzing C:\Users\Eashan\dev\zig\hopper\src\main.zig:16:5: assertion failed. This is a bug in the Zig compiler.
Unable to dump stack trace: Unable to open debug info: InvalidPEMagic
The following command exited with error code 2147483651:
C:\Program Files (x86)\zig\zig.exe build-lib C:\Users\Eashan\dev\zig\hopper\src\main.zig --cache-dir C:\Users\Eashan\dev\zig\hopper\zig-cache --name zig --cache on

Build failed. The following command failed:
C:\Users\Eashan\dev\zig\hopper\zig-cache\o\A0AMF_a3YROrqvGzskMarDL7J83h-LNeevTB_AEvpNeBUAhr-w4yBX4Xai-gSmyD\build.exe C:\Program Files (x86)\zig\zig.exe C:\Users\Eashan\dev\zig\hopper C:\Users\Eashan\dev\zig\hopper\zig-cache
```

The crash occurs at the beginning of the first line in `init`. Removing the `export` modifier allows the code to build successfully. Does anyone have a workaround I can use for now to fix this?

All the variables being set are global variables. The reason `heap` (which seems to be causing the crash) is global is that it is used in other functions.

**Comment by eashanhatti** [comment]
I found that the `init_callbacks` argument in `init` is causing the problem, specifically the `InstructionCallback` type.

**Comment by fengb** [comment]
Slices aren't ABI compatible (`args: []u32`). But the compiler should recognize it and correctly error out instead of crashing.

**Comment by eashanhatti** [comment]
Yeah, I changed them to unknown length pointers, but the compiler still crashes on `init_callbacks`.

**Comment by fengb** [comment]
Oops, I don't think function pointers are compatible yet: https://github.com/ziglang/zig/blob/master/src/codegen.cpp#L9604

**Comment by eashanhatti** [comment]
Yeah, although it only seems to crash if the function pointer is given a pointer type modifier (not sure if there's an official term). Like this:
```zig
export fn f1(cb: fn()void) void {} // compiler exits properly with an error on this

export fn f2(cb: [*]fn()void) void {} // compiler crashes on this

export fn f3(cb: *fn()void) void {} // also on this
```

**Comment by Vexu** [comment]
Function pointers now work differently and all single pointers to non-comptime types are considered C ABI compatible so this issue is no longer relevant.
