### ISSUE TITLE
better return type mismatch error message

### ISSUE THREAD

**Issue by Tetralux** [ziglang/zig#3230]
As mentioned in IRC:
```
<Tetralux> We should have a better error message if you attempt to 'try' from within a fn that 
<Tetralux> I was thinking of something like, "expected return type of []u8, got ![]u8`
<Tetralux> Or even just, "<function name> does not return an error"
<Tetralux> "note: function signature here"
<Tetralux> "fn blah() []u8 {"
<Tetralux> "          ^"
```
See https://github.com/ziglang/zig/issues/3230#issuecomment-532282140.

**Comment by andrewrk** [comment]
Can you improve this issue with a test case, actual output, and proposed output?

**Comment by Tetralux** [comment]
Proposed output you already have, but still. 

For this code:
```zig
fn f(allocator: *std.mem.Allocator) []u8 {
    var x = try allocator.alloc(u8, 1);
}

fn g(list: *std.ArrayList([]u8)) []u8 {
    var buf: []u8 = [_]u8{};
    try list.append(buf);
}
```

Actual output for `f`:
```
error: expected type '[]u8', found 'std.mem.Error'
    var x = try allocator.alloc(u8, 1);
            ^
```
Actual output for `g`:
```
error: expected type '[]u8', found '@typeOf(std.array_list.AlignedArrayList([]u8,null).append).ReturnType.ErrorSet'
    try list.append(buf);
    ^
```
In both cases, the problem is that you are using `try` in a function that returns `[]u8`, a non-error value, but you could be lead into thinking that's complaining that the expression that you are `try`ing returns an error when it wants a non-error, which makes no sense at all.

-----

I'd expect it to draw attention to the fact that this is a mismatch between _the return type_ and the error, point me at the `try`, and possibly also show me the signature of the enclosing procedure.

It would also avoid the need to print out the `@typeOf(std.array_list.AlignedArrayList([]u8,null).append).ReturnType.ErrorSet` business too.

Two decent options are:
```
error: enclosing function 'g' does not return an error
    try list.append(buf);
    ^

note: expected return type is here
    fn f() []u8 {
           ^
```
Or, a more general message:
```
error: mismatched return type; expected '[]u8', got '![]u8'
    try list.append(buf);
    ^
```
Notice how, rather than printing out the long unwiedly `@typeOf` expression, you just print the `!`.
You could also make this `error{...}![]u8` (the three dots are actually there) if you wanted to make it easier to spot it.

In either case, this makes sense since the error type is inferred anyway; if you were gonna print out the error set instead, then actually do so rather than printing out the expression to get it.

In this case, that might look something like:
```
error: mismatched return type; expected '[]u8', got 'error{OutOfMemory}![]u8'
    try list.append(buf);
    ^
```
Or, if the error had more possiblities, you could do something like this:
```
error: mismatched return type; expected '[]u8', got 'error{FirstError
                                                           SecondError,
                                                           ThirdError}![]u8'
    try list.append(buf);
    ^
```
Both of these are, IMHO, better than printing out the whole `@typeOf` expression.

**Comment by GavinRay97** [comment]
I ran into this tonight and got stuck for ~20 mins before finding this thread, this was the magic sentence for me:

> In both cases, the problem is that you are using `try` in a function that returns `[]u8`, a `non-error value`, but you could be lead into thinking that's complaining that `the expression that you are trying returns an error when it wants a non-error`, which makes no sense at all.

This was what I thought as well, was really confused. This was the mmessage, on master branch:
```sh
rayga@DESKTOP-88A51E5 MINGW64 ~/Projects/tmp/zig-rpp-parser
$ zig build
.\src\main.zig:35:53: error: expected error union type, found 'void'
            try tagQueue.append(Tag{ .name = tag }) catch return BAD_RESULT;
                                                    ^
.\src\main.zig:35:13: note: referenced here
            try tagQueue.append(Tag{ .name = tag }) catch return BAD_RESULT;
```

Code, for context below. I didn't understand that it had to do with the parent function not being marked as "potentially-throwing" (which makes sense the moment you think about it), so maybe a clue about `parent method XXX not marked with "!" to denote potential error`?

```zig
const Result = extern struct {
    error_code: c_int,
    ptr: [*]const u8,
    len: u64,
};

export fn parseRPP(rpp_text: [*]const u8, length: usize) Result {
 // ...
 // buried in function
 try tagQueue.append(Tag{ .name = tag }) catch return BAD_RESULT;
}
```

**Comment by Vexu** [comment]
The self-hosted compiler handles both cases correctly:
```
a.zig:7:13: error: expected type '[]u8', found 'error{OutOfMemory}'
    var x = try allocator.alloc(u8, 1);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vexu/Documents/zig/zig/lib/std/mem/Allocator.zig:10:19: note: error set declared here
pub const Error = error{OutOfMemory};
                  ^~~~~~~~~~~~~~~~~~
a.zig:6:37: note: function cannot return an error
fn f(allocator: *std.mem.Allocator) []u8 {
                                    ^~~~
a.zig:12:26: error: array literal requires address-of operator (&) to coerce to slice type '[]u8'
    var buf: []u8 = [_]u8{};
                    ~~~~~^~
```
