### ISSUE TITLE
passing alignment through to child allocator

### ISSUE THREAD

**Issue by Tetralux** [ziglang/zig#3231]
Given a custom allocator struct with a `child_allocator` field.
You cannot do this in the `realloc` implementation:
```zig
self.child_allocator.alignedAlloc(u8, new_align, count);
```
This is because `new_align` is non-comptime.

My usecase in particular is where `child_allocator` acts as a type of fallback allocator.

**Comment by andrewrk** [comment]
Call the `reallocFn` directly.
