### ISSUE TITLE
tagged union with only zero-size members has invalid value after assignment

### ISSUE THREAD

**Issue by Slaide** [ziglang/zig#3232]
i have created a tagged union with mutiple fields, each with its own corresponding type (a struct, that has no members, though a different struct for each union member).
i do have a variable of the enum type, which is initialized to undefined. after this, i assign to this variable a enum variant based on some value(inside a switch case). after this assignment, the variable is still undefined though.
if i change (at least) one of the member-types to not be zero-size, everything works, even the types still having a size of zero.

**Comment by andrewrk** [comment]
Hi @Slaide. Thank you for taking the time to report this issue. Given the beta nature of the zig project, and how fast things are changing, in order for a report like this to be actionable, it needs to have these 3 things:

 * example code
 * the output/behavior that you expect to get 
 * the output/behavior you are getting instead

Once you have provided these things, I'll re-open this issue.
