### ISSUE TITLE
compiler crash

### ISSUE THREAD

**Issue by xxxbxxx** [ziglang/zig#3233]
hello!

func1() compiles fine with 0.4.0 and trunk.
func2() compiles fine with 0.4.0 but crashes (SEGV)  on trunk.

```zig 
fn createStuff(comptime n: u32) [n*n]u32 {
    var array : [n*n]u32 = undefined;
    var i:u32=0;
    while (i<n*n) : (i+=1) { array[i] = i; }
    return array;
}

export fn func1(num: u32) u32 {
    const a1 = createStuff(1);
    const a2 = createStuff(2);
    const a = switch(num) {
        1 => a1,
        2 => a2,
        else => unreachable,
    };
    
    return a[num/2];
}

export fn func2(num: u32) u32 {
    const a = switch(num) {
        1 => createStuff(1),
        2 => createStuff(2),
        else => unreachable,
    };
    
    return a[num/2];
}
```

**Comment by LemonBoy** [comment]
The peer-resolved type between `[1]u32` and `[4]u32` is `[]const u32` so when `ir_render_slice` tries to slice the result variable as if it were an array LLVM goes legs up. Pro-tip, adding an the following assertion 

```c
assert(LLVMGetTypeKind(LLVMGetElementType(LLVMTypeOf(array_ptr))) == LLVMArrayTypeKind);
```

explains why `LLVMBuildInBoundsGEP` crashes and burns, the `array_ptr` value is a slice.

**Comment by xxxbxxx** [comment]
This seems fixed in trunk.
non longer compile as is, with helpfull error messages.
and when sprinkling '&' to get slices , both case do work fine.  

(although not quite sure if the second one should work, since it looks like is using a slice to an array declared inside a block after it is exited...)
