### ISSUE TITLE
Using Zig as C compiler for a shared library leads to undefined symbol: _DllMainCRTStartup

### ISSUE THREAD

**Issue by nxrighthere** [ziglang/zig#3237]
The command: `zig build-lib --c-source test.c --library c -dynamic -target x86_64-windows-gnu` leads to `lld: error: <root>: undefined symbol: _DllMainCRTStartup` error. Compilation of static library seems to work fine.

**Comment by FireFox317** [comment]
Looking at all the options that can be provided for lld-link (linker for windows), I think the option `-NOENTRY` has to be added to the linker. This is what the help mentions: 
```
-NOENTRY      Don't add reference to DllMainCRTStartup; only valid with /dll
```
Passing this option to the linker does indeed solve the issue.

**Comment by andrewrk** [comment]
@FireFox317 I think that's a good way to go. However I also think there is a regression. If you grep std lib for DllMainCRTStartup you can see there is something that was supposed to be provided. I think that mess can be removed in favor of comptime logic in std/special/start.zig.

**Comment by andrewrk** [comment]
Hmm I'm not sure if this is a bug actually. I think you're supposed to define `DllMainCRTStartup` in your C code.

**Comment by daurnimator** [comment]
Related: https://github.com/ziglang/zig/issues/3000

**Comment by nxrighthere** [comment]
@andersfr Isn't it against _using Zig as C compiler_ idea, if I don't need to do that with GCC/Clang/MSVC?

**Comment by alexnask** [comment]
@nxrighthere  
I believe `DllMainCRTStartup` is provided by libc (or more specifically the CRT MS libraries), if you try to compile a DLL with `-nostdlib` with clang, I think you get the same error.

**Comment by zhaozg** [comment]
ref: https://github.com/ziglang/zig/issues/6482
