### ISSUE TITLE
?[*c]u8 in an extern struct crashes the compiler

### ISSUE THREAD

**Issue by Aransentin** [ziglang/zig#3240]
E.g. this:

    const stroo = extern struct {
        moo: ?[*c]u8,
    };
    export fn testf(fluff: *stroo) void {}

Will cause the compiler to dump it's memory to the console and crash: https://godbolt.org/z/eg31qQ

Additionally, `@sizeOf(?[*c]u8)` is 16 on x86_64 even in an `extern struct` which is rather odd (I had assumed it to be usize).

Edit: Ah, `[*c]` is "optional" by default so `?` just adds another optional bit, that explains the 16-byte thing. Nevermind that..!

**Comment by FireFox317** [comment]
Citing the [zig docs](https://ziglang.org/documentation/master/#C-Pointers):
**"This type is to be avoided whenever possible. The only valid reason for using a C pointer is in auto-generated code from translating C code. "**

In this case you have to use a single-item pointer `*T` or unknown-length pointers `[*]T`. This should however still generate a compiler error and not crash the compiler. Related: #2984 

BTW, the memory dump is related to godbolt, on linux a backtrace is printed.

**Comment by Aransentin** [comment]
> The only valid reason for using a C pointer is in auto-generated code from translating C code

That's what I'm doing – I wrote a script to convert the Vulkan XML spec; it contains structs that have pointers to null-terminated strings which may also be null.
