### ISSUE TITLE
Zig miscompiles "ternary" assignment to struct members

### ISSUE THREAD

**Issue by Aransentin** [ziglang/zig#3244]
The following function always returns 0 though it should be 1. 

    const Structy = struct{
        bleh: i32,
    };

    export fn foo( arg: i32 ) i32 {
        const st = Structy{
            .bleh = if( arg == 1 ) 1 else 1,
        };

        if( st.bleh == 1 )
            return 1234;
        return 0;
    }

Check e.g. the assembly output of `foo2` in https://godbolt.org/z/S3WFXg as opposed to `foo1` which does not use `if-else` and works fine.

**Comment by andrewrk** [comment]
Thanks for the report. I created a new label for this kind of bug. Miscompilations are the highest priority issues. Even in stage1, I want to get down to 0 open miscompilation bug reports. I know there are a couple others and they need to get labeled.

I also have a fix for this undergoing local testing, which should be pushed shortly.
