### ISSUE TITLE
Miscompilation instead of error when trying modified test from documentation.

### ISSUE THREAD

**Issue by vi** [ziglang/zig#3259]
Taken from documentation about inline loops and modified:

```zig
const assert = @import("std").debug.assert;

//test "inline while loop" {
pub fn main() void {
    comptime var i = 0;
    //var sum: usize = 0;
    
    //inline
    while (i < 3) : (i += 1) {
        const T = switch (i) {
            0 => f32,
            1 => i8,
            2 => bool,
            else => unreachable,
        };
        //sum += typeNameLength(T);
    }
    //assert(sum == 9);
}

fn typeNameLength(comptime T: type) usize {
    return 0; // @typeName(T).len;
}
```

Expected:

`error: control flow attempts to use compile-time variable at runtime`. This is what I see if I also comment out `const T = ...`.

Actual:

Compilation succeeds, running the resulting executable busy-loops.

**Comment by nektro** [comment]
control flow is not attempting to use a compile-time variable at runtime though

**Comment by nektro** [comment]
the loop is a noop so it is likely being removed entirely
