### ISSUE TITLE
Invalid program (segfault) instead of compilation error with slice on compile time values

### ISSUE THREAD

**Issue by Hirezias** [ziglang/zig#3270]
With version 0.4.0+cf4bccf7 the following code compile but result in a segmentation fault.

```zig
const warn = @import("std").debug.warn;
 
const T = struct {
    value: []u8,
};
 
var t = T{
    .value = [1]u8{'a'},
};
 
pub fn main() void {
    t.value[0] = 'b';
    warn("Hello '{}'\n", t.value);
}
```
```
Segmentation fault at address 0x2013c1
main.zig:12:18: 0x228abd in main (run)
    t.value[0] = 'b';
                 ^
/snap/zig/835/lib/zig/std/special/start.zig:148:22: 0x227add in std.special.posixCallMainAndExit (run)
            root.main();
                     ^
/snap/zig/835/lib/zig/std/special/start.zig:56:5: 0x2279bf in std.special._start (run)
    @noInlineCall(posixCallMainAndExit);
    ^
[1]    17694 abort (core dumped)  zig run main.zig
```
I think the segmentation fault occures because t.value[0] is in read-only memory as compile time static constant.
It seems the right type of compile time [1]u8{'a'} would implicitely be [1]const u8 and it wouldn't be possible to take a slice on mutable with it.

**Comment by Slaide** [comment]
implicit casting is not the solution for this problem.
a const qualifier should be required on comptime arrays.

**Comment by Slaide** [comment]
accordingly, the better title here would probably be something regarding the const qualifier for arrays being allowed, only after which this problem can be solved.

**Comment by Hirezias** [comment]
I do'nt suggest to add implicit cast, but to fix the bug wich allow a runtime mutable slice to be taken over a comptime array.
Why I talk of type wich is written non const but should be const in backend is in a first hand that, for the few I understand to zig, the whole file namespace is implicitely comptime, and it could be inconsistant to create an exception for arrays, and in an other hand that such rules (I not really agree with it) exists with such code : 
```zig
fn foo() void {
    var a: u32 = 0;
    const b: u32 = 1;
    assert(@typeOf(a) == @typeOf(b)); // Ok !
    assert(@typeOf(&a) == @typeOf(b)); // not ok
}
```
But I think such beaviour is really strange and inconsistant, possibly it's a bug too ?

**Comment by Slaide** [comment]
which zig version do you use? because for 0.4.0+d60f9d0d the types actually differ (and are *u32 and *const u32).
these also are not arrays, whereby the const qualifier is explicitely forbidden for array types only.

**Comment by andrewrk** [comment]
You can work around this bug like this:

```zig
var value_data = [1]u8{'a'};
var t = T{
    .value = &value_data,
};
```

I bumped up the priority because this is a miscompilation.

**Comment by Hirezias** [comment]
Ok, thank you :)

**Comment by Vexu** [comment]
Coersing arrays to slices now requires address of operator which now gives a const pointer after #4971.
```
./build/a.zig:281:20: error: expected type '[]u8', found '*const [1]u8'
    .value = &[1]u8{'a'},
                   ^
./build/a.zig:285:5: note: referenced here
    t.value[0] = 'b';
    ^
```
