### ISSUE TITLE
Boolean AND doc example not working 

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ziglang/zig#3272]
Because == has a higher precendence than and:
assert(false and true == false);

also gives: 5/5 test "problems"...reached unreachable code
E:\Zig\compiler\lib\zig\std\debug.zig:206:14: 0x7ff7ea011029 in std.debug.assert (test.obj)
    if (!ok) unreachable; // assertion failure
             ^
E:\Zig\code_examples\operators\operators.zig:76:11: 0x7ff7ea011b51 in test "problems" (test.obj)
    assert(false and true == false);
          ^

The example should be changed into:  (false and true) == false

**Comment by andrewrk** [comment]
Thanks for the report.

This will eventually be caught by #114.
