### ISSUE TITLE
Attempting to use DECIMAL from Windows' "wtypes.h" fails

### ISSUE THREAD

**Issue by AnthonyYoManz** [ziglang/zig#3277]
DECIMAL's definition in "wtypes.h" is as follows:
```
typedef struct tagDEC {
    USHORT wReserved;
    union {
        struct {
            BYTE scale;
            BYTE sign;
        } DUMMYSTRUCTNAME;
        USHORT signscale;
    } DUMMYUNIONNAME;
    ULONG Hi32;
    union {
        struct {
            ULONG Lo32;
            ULONG Mid32;
        };
        ULONGLONG Lo64;
    } DUMMYUNIONNAME2;
} DECIMAL;
```

This is translated to the following in cimport.zig:
```
pub const struct_tagDEC = extern struct {
    wReserved: USHORT,
    @"": extern union {
        @"": extern struct {
            scale: BYTE,
            sign: BYTE,
        },
        signscale: USHORT,
    },
    Hi32: ULONG,
    @"": extern union {
        @"": extern struct {
            Lo32: ULONG,
            Mid32: ULONG,
        },
        Lo64: ULONGLONG,
    },
};
pub const DECIMAL = struct_tagDEC;
```

As you can see, the nested union and struct names are missing, and this results in the following error message: `error: duplicate struct field: ''`

Interestingly, when testing against a much smaller file than "wtypes.h", containing only a struct with identical definition (aside from different typedefs for ULONG and friends) the file is translated correctly, including the names of all nested structs and unions, and so building succeeds.

**Comment by AnthonyYoManz** [comment]
I've singled out DECIMAL here, but there are a number of other types in "wtypes.h" that Zig fails to determine names for. These problematic structs and unions are always nested.

**Comment by Vexu** [comment]
Works in master.
```zig 
pub const ULONGLONG = c_ulonglong;
pub const ULONG = c_ulong;
pub const BYTE = u8;
pub const USHORT = c_ushort;
const struct_unnamed_2 = extern struct {
    scale: BYTE,
    sign: BYTE,
};
const union_unnamed_1 = extern union {
    DUMMYSTRUCTNAME: struct_unnamed_2,
    signscale: USHORT,
};
const struct_unnamed_5 = extern struct {
    Lo32: ULONG,
    Mid32: ULONG,
};
const union_unnamed_3 = extern union {
    unnamed_4: struct_unnamed_5,
    Lo64: ULONGLONG,
};
pub const struct_tagDEC = extern struct {
    wReserved: USHORT,
    DUMMYUNIONNAME: union_unnamed_1,
    Hi32: ULONG,
    DUMMYUNIONNAME2: union_unnamed_3,
};
```

**Comment by daurnimator** [comment]
@Vexu `DUMMYUNIONNAME` is defined to the empty string or `u`.... how did that end up getting in there as the field name?

**Comment by Vexu** [comment]
I didn't know about such defines. It still works with those defines you just get mangled names which could be improved by #985.
