### ISSUE TITLE
Golang like standard library 

### ISSUE THREAD

**Issue by lithic** [ziglang/zig#3280]
Golang's standard library has many useful functionality in different categories. Software authors can write various kinds of programs in different fields without using third party libraries.

**Comment by daurnimator** [comment]
Please add descriptions to your issues with explanations of what you mean.

**Comment by daurnimator** [comment]
There is nothing actionable in this issue: if there is specific functionality missing, then please request that. Note that at the moment most things will be accepted for the standard library (as long as someone writes it): before 1.0.0 there will be a standard library review (#1629)
