### ISSUE TITLE
When targeting AArch64, unable to widen cast f16 to f128

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#3282]
```zig
export fn entry() bool {
    var x: f16 = 12.34;
    var y: f128 = x;
}
```

```
LLVM ERROR: Unsupported library call operation!
```

Note that it works if you do:

```zig
export fn entry() void {
    var x: f16 = 12.34;
    var y: f32 = x;
    var z: f128 = y;
}
```

This issue is to:
 * Work with upstream LLVM to get this working
 * In the mean time, work around the issue by generating f16 -> f128 casts by taking a brief detour through f32.

**Comment by shawnl** [comment]
I don't get it. This is not a difficult function. The widening float conversion you just move the bits and zero the rest.

**Comment by LemonBoy** [comment]
There's a [patch](https://reviews.llvm.org/D50685) for this that's stuck in the limbo.
