### ISSUE TITLE
Assertion failure in ir_render_slice

### ISSUE THREAD

**Issue by sometimes-i-send-pull-requests** [ziglang/zig#3299]
This source:

    fn compileShader(source: []const u8) void {
        const strings = [_][*]const u8{source[0..]};
    }

    pub fn main() void {
        compileShader(@embedFile("/dev/null"));
    }

Causes an assertion failure in the latest release of the Zig compiler at the time of writing, 35c1d8ce:

    Assertion failed at /deps/zig/src/codegen.cpp:5176 in ir_render_slice. This is a bug in the Zig compiler.
    Unable to dump stack trace: debug info stripped
    Aborted

There is a type mismatch in the code above, so it should not compile successfully (`source.ptr` was intended rather than `source[0..]`), but it shouldn't cause an assertion failure inside the compiler either.

**Comment by xackus** [comment]
I think this got fixed recently. Tested on 0a8835268915feab561bdb68adb17aed76b9708f.
```
./ignore/test.zig:2:42: error: expected type '[*]const u8', found '[]const u8'
    const strings = [_][*]const u8{source[0..]};
                                         ^
```
