### ISSUE TITLE
Compiler test segfault

### ISSUE THREAD

**Issue by Duckxz** [ziglang/zig#3302]
when i try to do `zig test` on this (godawful) code it segfaults the compiler with no further info.

code:
https://pastebin.com/jg09PyqD

**Comment by LemonBoy** [comment]
Workaround: Change `PixelError!Pixel` into `PixelError!RGBPixel` and you're good to go.

**Comment by Duckxz** [comment]
Thanks that helped

**Comment by Vexu** [comment]
Reduced test case:
```zig
test "" {
    _ = func();
}

fn func() func {}
```

Triggers this assertion in ir_analyze_decl_ref
```c++
        case TldIdFn: {
            TldFn *tld_fn = (TldFn *)tld;
            ZigFn *fn_entry = tld_fn->fn_entry;
            assert(fn_entry->type_entry);
```

I couldn't find a duplicate, so you should leave this open.

**Comment by xackus** [comment]
Seems to have been fixed. Tested on 0a8835268915feab561bdb68adb17aed76b9708f.
```
./ignore/test.zig:17:11: error: dependency loop detected
fn func() func {
          ^
./ignore/test.zig:14:9: note: referenced here
    _ = func();
        ^
```
