### ISSUE TITLE
a problem with std functions

### ISSUE THREAD

**Issue by gggin** [ziglang/zig#3304]
I read some  std library codes. I found that the zig standard library write sth like parse float parse number or unicode stream or utf8toUtf16 things, are only support []u8 things, but the cpp libraries usually implement that with a abstract with stream can support both memory string or file stream. So maybe we can change in future.

**Comment by andrewrk** [comment]
too vague

**Comment by gggin** [comment]
code from `unicode.zig`
```
pub const Utf8Iterator = struct {
    bytes: []const u8,
    i: usize,

    pub fn nextCodepointSlice(it: *Utf8Iterator) ?[]const u8 {
        if (it.i >= it.bytes.len) {
            return null;
        }

        const cp_len = utf8ByteSequenceLength(it.bytes[it.i]) catch unreachable;
        it.i += cp_len;
        return it.bytes[it.i - cp_len .. it.i];
    }

    pub fn nextCodepoint(it: *Utf8Iterator) ?u32 {
        const slice = it.nextCodepointSlice() orelse return null;

        switch (slice.len) {
            1 => return u32(slice[0]),
            2 => return utf8Decode2(slice) catch unreachable,
            3 => return utf8Decode3(slice) catch unreachable,
            4 => return utf8Decode4(slice) catch unreachable,
            else => unreachable,
        }
    }
};
```
the `Utf8Iterator` can only iterator within a memory array, but usually we use something like utf8Iterator is from a file stream, usually the library like these things are support both, to abstract a stream with same interface. The same problem is also with `base64.zig`, `fmt.zig`(parseFloat, parseNumber), `json.zig`. The library parse JSON(rapidjson ,jsoncpp) both have this feature.
