### ISSUE TITLE
zig build system: concurrent builds

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#331]
* [x] default to a concurrent build which uses number of cores that computer has
 * [x] ability to override and set the concurrency number

**Comment by slimsag** [comment]
@andrewrk can you tell me if this is still indeed an open issue, and specifically if it affects when `zig build` is compiling C/C++ sources too?

I'm looking at some slow-ish compile times for some C++ WebGPU code and, if this is still a valid issue, that's really great news for me

**Comment by slimsag** [comment]
Digging through the code, it seems like the answer is yes.

**Comment by andrewrk** [comment]
Done in #14647.
