### ISSUE TITLE
usingnamespace problem with imported const entries

### ISSUE THREAD

**Issue by LemonBoy** [ziglang/zig#3316]
```zig
usingnamespace struct {
    pub const foo = 42;
};

comptime {
    @compileLog(foo);
}
```

```
usens.zig:2:9: error: redefinition of 'foo'
    pub const foo = 42;
        ^
usens.zig:2:9: note: previous definition is here
    pub const foo = 42;
        ^
usens.zig:6:17: note: referenced here
    @compileLog(foo);
```

This blocks #3311 as I'm using this construct to conditionally define some constants.

**Comment by andrewrk** [comment]
I think it's fair to call this a bug because a declaration shadowing itself doesn't make any sense. I have a hunch that the fix could be a simple pointer comparison to see if the "previous definition" `Tld *` equals the "redefinition" `Tld *`.
