### ISSUE TITLE
armv7-freestanding-eabihf % operator produces undefined instruction

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#3322]
https://github.com/markfirmware/zig-bare-metal-raspberry-pi/blob/aeabi_uidivmod/asm.armv7-qemu#L6938-L6955

llvm-objdump was used to produce that listing.

The disassembler at http://armconverter.com/hextoarm/ produced this for these two instructions:

    02 0b dd ed
    VLDR    D16, [SP, #8]
    02 0b 4b ed
    VSTR    D16, [FP, #-8]

./test-qemu.sh then press ! to demonstrate the exception.

The exception is also taken on an rpi3b+

Thanks

**Comment by andrewrk** [comment]
Thanks for the report. The next step of solving this will be producing a reduction of LLVM IR code that demonstrates the problem, and filing an upstream bug report.

**Comment by LemonBoy** [comment]
WorksForMe

```asm
0001669c __aeabi_uidivmod:
   1669c: 00 48 2d e9                  	push	{r11, lr}
   166a0: 0d b0 a0 e1                  	mov	r11, sp
   166a4: 18 d0 4d e2                  	sub	sp, sp, #24
   166a8: 04 00 8d e5                  	str	r0, [sp, #4]
   166ac: 00 10 8d e5                  	str	r1, [sp]
   166b0: 04 00 9d e5                  	ldr	r0, [sp, #4]
   166b4: 00 10 9d e5                  	ldr	r1, [sp]
   166b8: 08 20 8d e2                  	add	r2, sp, #8
   166bc: 04 20 82 e2                  	add	r2, r2, #4
   166c0: e2 ff ff eb                  	bl	#-120 <__udivmodsi4>
   166c4: 08 00 8d e5                  	str	r0, [sp, #8]
   166c8: 08 00 9d e5                  	ldr	r0, [sp, #8]
   166cc: 0c 10 9d e5                  	ldr	r1, [sp, #12]
   166d0: 04 10 0b e5                  	str	r1, [r11, #-4]
   166d4: 08 00 0b e5                  	str	r0, [r11, #-8]
   166d8: 08 00 1b e5                  	ldr	r0, [r11, #-8]
   166dc: 04 10 1b e5                  	ldr	r1, [r11, #-4]
   166e0: 0b d0 a0 e1                  	mov	sp, r11
   166e4: 00 88 bd e8                  	pop	{r11, pc}
```

**Comment by markfirmware** [comment]
https://github.com/markfirmware/zig-bare-metal-raspberry-pi/tree/aeabi_uidivmod

Reduced to just calling the % operator, using zig-0.4.0+878aece8.tar.xz on an updated buster x64 linode:

    + zig build
    + llvm-objdump -x --source zig-cache/zig-bare-metal-raspberry-pi                                                
    + grep unknown asm.armv7-qemu
         27c:       02 0b dd ed  <unknown>
         280:       02 0b 4b ed  <unknown>
    + egrep '0b02 ed'
    + hexdump zig-bare-metal-raspberry-pi-armv7.img
    0000270 2004 e282 ffe2 ebff 0008 e58d 0b02 eddd
    0000280 0b02 ed4b 0008 e51b 1004 e51b d00b e1a0

**Comment by LemonBoy** [comment]
> What could be different in my environment?

I'm running the latest Zig version from git on a updated Buster x64 box and [LLVM 9 from here](https://apt.llvm.org/) and I can't get LLVM to emit a `vldr` + `vstr`.

What Zig/LLVM versions are you using?

**Comment by markfirmware** [comment]
https://github.com/markfirmware/zig-bare-metal-raspberry-pi/blob/aeabi_uidivmod/README.md

Vastly simplified.

zig 0.5+
llvm 7.01 but only for the objdump

**Comment by LemonBoy** [comment]
Well, for some reason the compiler from the Download page emits code with `.fpu neon` while my local build emits code with `.fpu vfpv3`.

Perhaps setting `target_specific_cpu_args` to `"generic"` when targeting ARM may help solve the problem.

**Comment by markfirmware** [comment]
bufPrint also elicits this.

I will now try compiling zig on buster/x64/linode since @LemonBoy reports that that works.

**Comment by markfirmware** [comment]
I tried ziglang/docker-zig and got the same results.

@LemonBoy do you have a script I can use to reproduce your environment?

**Comment by markfirmware** [comment]
target_specific_cpu_args

Is this part of the compiler or is it accessible to build.zig?

**Comment by markfirmware** [comment]
I refreshed the test case:

https://github.com/markfirmware/zig-bare-metal-raspberry-pi/tree/udivmodsi4

What can I next try?
@LemonBoy @andrewrk

**Comment by LemonBoy** [comment]
@markfirmware one of the latest commits should fix this problem, can you check and see if that's the case?

**Comment by markfirmware** [comment]
@LemonBoy the problem is fixed with %, but there are still unknown instructions produced when using fmt.bufPrint

https://github.com/markfirmware/zig-bare-metal-raspberry-pi/tree/bufprint-unknown

**Comment by LemonBoy** [comment]
> the problem is fixed with %, but there are still unknown instructions produced when using fmt.bufPrint

The problem here is that objdump plays dumb and doesn't seem to recognize many opcodes, including the NEON [ones in your example](http://shell-storm.org/online/Online-Assembler-and-Disassembler/?opcodes=00+0b+d2+ed++%0D%0A02+0b+4b+ed++%0D%0A00+0b+d1+ed+%0D%0A08+0b+cd+ed++%0D%0A00+0b+d0+ed++%0D%0A02+0b+4b+ed+%0D%0A00+0b+d0+ed%0D%0A06+0b+4b+ed%0D%0A00+0b+d1+ed%0D%0A08+0b+4b+ed&arch=arm&endianness=little&dis_with_addr=True&dis_with_raw=True&dis_with_ins=True#disassembly).

Since you're targeting an ARMv7-A and are using the hard-float ABI you get NEON instructions in your binary so that's not a problem. The problem with `udivmodsi4` was slightly different, we weren't playing by the rules specified by the AEABI standard, but there should be no more problems like that.

Does the `bufPrint` code cause an illegal instruction exception on your hardware? (I guess you're targeting a RPI3)

**Comment by markfirmware** [comment]
I’ll open another issue for the unknown instruction disassembly and if I get a hardware fault I’ll open a different issue. Thanks.

**Comment by LemonBoy** [comment]
> I’ll open another issue for the unknown instruction disassembly 

It's **not** a bug, either use `arm-linux-gnueabihf-objdump` or play with LLVM's objdump flags to let it know what revision are you targeting.
