### ISSUE TITLE
futimens() not provided on macos 10.11

### ISSUE THREAD

**Issue by iology** [ziglang/zig#3335]
I bumped right into this problem when I ran `zig build ...`.

https://github.com/ziglang/zig/blob/543e729398c2ae2a6fbae8ab54ce0737d35004a0/lib/std/os.zig#L2685

https://github.com/ziglang/zig/blob/543e729398c2ae2a6fbae8ab54ce0737d35004a0/lib/std/fs/file.zig#L272-L291

Is this a strict requirement, and btw what is the minimum version of macos supported by the zig toolchain?

I replaced it with futimes (microsecond precision) and all compiler tests passed.

(maybe related? #1907)

**Comment by andrewrk** [comment]
https://ziglang.org/#Support-Table

10.13 is the current minimum

**Comment by andrewrk** [comment]
I understand how unsatisfying it is to file your first issue and have it closed immediately.

Unfortunately, macOS has proven to be the most problematic operating system to support. It would be a difficult case to make to increase the supported version range on top of this. I also think it is unreasonable to support a version of the OS that Apple doesn't even support.

**Comment by iology** [comment]
No problem! Luckily by some little tweaks I can have fun with the latest zig while evaluating the latest osx. :)

Anyway, thanks for the hard work!!
