### ISSUE TITLE
Segfault accessing multiplied array in global struct

### ISSUE THREAD

**Issue by m-r-hunt** [ziglang/zig#3344]
Got this down to quite a small repro:

```zig

const MyStruct = struct {
    array: [1]u8,
};

var my_struct = MyStruct{ .array = [_]u8{0} ** 1 };

pub fn main() void {
    my_struct.array[0] = 12;
}

```

The `** 1` is necessary. Without it the program runs fine. Similarly it's fine if the struct is created on the stack. The array can be any size (originally I had quite a big array which I thought was the problem). With it as above I get this error:

```
Segmentation fault at address 0x7ff6f6219658
C:\Users\Max\devstuff\zigstuff\test.zig:26:0: 0x7ff6f61e0fa4 in main (run.obj)


C:\Users\Max\devstuff\zigstuff\zig-windows-x86_64\lib\zig\std\special\start.zig:113:49: 0x7ff6f61e0f38 in ??? (run.obj)


???:?:?: 0x7ff8a12e7bd4 in ??? (???)


???:?:?: 0x7ff8a17acee1 in ??? (???)
```

**Comment by andrewrk** [comment]
Thanks! The small repros are very much appreciated. (Also make your bug more likely to get fixed faster)

**Comment by xackus** [comment]
Valgrind reports no errors on 0a8835268915feab561bdb68adb17aed76b9708f.
However, i get two "Conditional jump or move depends on uninitialised value(s)" errors when building.
