### ISSUE TITLE
Crash when assigning null `[*c] u8` value to type `?[*] u8`

### ISSUE THREAD

**Issue by rjtobin** [ziglang/zig#3346]
When assigning the return value of a C function call to a variable of type `?[*]`, in recent builds of Zig I get a runtime crash if the C function returns a null pointer. A minimal example is here: https://gist.github.com/rjtobin/6b7779116485ca7efbb5d71b4ba013ed

For this example, I expected a successful execution with no output, but instead at runtime I get:
```
cast causes pointer to be null
/home/parallels/test/readline/cast.zig:7:20: 0x229b50 in main (cast)
    x = c.some_func(0);
                   ^
/home/parallels/Downloads/new_zig2/zig-linux-x86_64-0.4.0+543e7293/lib/zig/std/special/start.zig:194:22: 0x229a53 in std.special.main (cast)
            root.main();
```

The runtime crash occurs in the recent hash 543e7293, but not in the older hash 3c914c63.

The runtime crash disappears if I assign to the C function call return on the same line as the variable declaration: `var x:?[*]const u8 = c.some_func(0);`.  The crash also disappears if the `0` is replaced with `1`.

**Comment by Slaide** [comment]
0.4.0+543e7293 has this error message for me at compile time
```
/code/temp/main.zig:26:7: error: null pointer casted to type '[*]const u8'
  x = @intToPtr([*c]u8, 0);
```
when using build-exe without additional arguments.

**Comment by Vexu** [comment]
Fixed in master.
```zig
// All 2 tests passed.
pub export fn some_func(arg_a: c_int) [*c]const u8 {
    var a = arg_a;
    if (a == @as(c_int, 0)) return null;
    return "FOO";
}
test "" {
    var x:?[*]const u8 = null;
    x = some_func(0);
    std.debug.assert(x == null);
}
test "" {
    var x: ?[*]const u8 = null;
    x = @intToPtr([*c]u8, 0);
}
```
