### ISSUE TITLE
Compiler crash on if-expression with empty body followed by semicolon (`if (true);`)

### ISSUE THREAD

**Issue by fjallarefur** [ziglang/zig#3347]
Compiling this program:
```zig
pub fn main() void {
    if (true);
}
```
with Zig 0.4.0 results in `Segmentation fault (core dumped)`.

I wanted to see if Zig would yell at me for doing silly things. At least it didn't accept the program. :)

**Comment by Vexu** [comment]
Duplicate of #2309, fixed in master.
