### ISSUE TITLE
format function fails (at compile time) if there are fewer arguments than expected

### ISSUE THREAD

**Issue by Slaide** [ziglang/zig#3349]
for
`std.debug.warn("hi","not expected");`
there is an explicit error message("unused arguments"), but for
`std.debug.warn("{} {}","hi");`
there is not. instead
```
lib/zig/std/fmt.zig:132:29: error: index 1 outside argument list of size 1
                        args[arg_to_print],
```
is printed.

really minor issue, but if one case is handled, the other one should be as well.

**Comment by xackus** [comment]
Not all paths through the state machine are fixed. `debug.warn("{d}")` still prints index out of range.
Please reopen.
