### ISSUE TITLE
how the f is this possible

### ISSUE THREAD

**Issue by Slaide** [ziglang/zig#3350]
this code
```
std.debug.warn("start {}\n",self.device.instance.instance);
std.debug.warn("start {}\n",self.device.instance.instance);
    
std.debug.warn("start {}\n",self.device.device);
std.debug.warn("start {}\n",self.device.device);
```
produces this output
```
start struct_VkInstance_T@1728920
start struct_VkInstance_T@7
start struct_VkDevice_T@1bc76a0
start struct_VkDevice_T@1bc76a0
```
the program is strictly iterative, no threaded component whatsoever.

if did write a small loop, in case the output buffer has some effect, and flushing solves it, or if another access does further damage, and this happens:

```
    var r:usize=0;
    while(r<10):(r+=1){
      std.debug.warn("instance {}\n",self.device.instance.instance);
    }
    
    r=0;
    while(r<10):(r+=1){
      std.debug.warn("device {}\n",self.device.device);
    }
```
```
instance struct_VkInstance_T@ead920
instance struct_VkInstance_T@6
instance struct_VkInstance_T@1
instance struct_VkInstance_T@1
instance struct_VkInstance_T@1
instance struct_VkInstance_T@1
instance struct_VkInstance_T@1
instance struct_VkInstance_T@1
instance struct_VkInstance_T@1
instance struct_VkInstance_T@1
device struct_VkDevice_T@134c6a0
device struct_VkDevice_T@134c6a0
device struct_VkDevice_T@134c6a0
device struct_VkDevice_T@134c6a0
device struct_VkDevice_T@134c6a0
device struct_VkDevice_T@134c6a0
device struct_VkDevice_T@134c6a0
device struct_VkDevice_T@134c6a0
device struct_VkDevice_T@134c6a0
device struct_VkDevice_T@134c6a0
```
this is what the type looks like: (translated from the vulkan headers. the other type works the same way)
```
pub const struct_VkInstance_T = @OpaqueType();
pub const VkInstance = ?*struct_VkInstance_T;
```
repeated runs cause the same outcome. different adresses, but the first two reads from the instance adress change its value.

it may not be a compiler bug after all, but i do not understand how it could be something else. this only happens in a specific function as well, which seems very ominous, but since there is nothing happening in between the reads, i really have got no clue what the issues.

i also have not been able to reproduce it with other code, maybe someone can. i am also willing to send the whole source code with the built binary, if someone is willing to read through the generated code.

some more output:
```
    var r:usize=0;
    while(r<10):(r+=1){
      std.debug.warn("instance {} {}\n",self.device.instance.instance,self.device.instance.instance);
    }
```

```
instance struct_VkInstance_T@207e920 struct_VkInstance_T@207e920
instance struct_VkInstance_T@7 struct_VkInstance_T@7
instance struct_VkInstance_T@1 struct_VkInstance_T@1
instance struct_VkInstance_T@1 struct_VkInstance_T@1
....
```

**Comment by mikdusan** [comment]
a couple of hints:
- this looks like it's stack-related
- vkinstance looks to be different "memory" than vkdevice; ie. stack vs. heap
- is vkinstance based on escaped stack memory?
- if so that would explain the mutation

**Comment by Slaide** [comment]
whatever the relation may be, it should not change the pointer, should it? because this breaks my program. vulkan related function calls segfault if they use the mutated variable, which should not be the case.

**Comment by Slaide** [comment]
also this happens at multiple points in my program. i had an issue earlier where a function call did this, to a variable it should not mutate, as defined by the vulkan standard. it did anyway, and the workaround was to save the adress prior to the function call, and write it back after the function call changed the adress.
i cannot reproduce this situation though, because it then randomly started behaving that way at another point in the program.
i also cleaned the zig-cache, which did nothing.

**Comment by mikdusan** [comment]
>i am also willing to send the whole source code

if you can post or make a repo available of the source I'll take a peek

**Comment by Slaide** [comment]
i have completely rewritten the project, and still get the same error. i am absolutely blank on ideas right now. i did check the pointers to the struct that holds the opaque pointer, and those are all right, so something is really wrong with the opaque pointer, and i have not a single clue.

i uploaded the project to a repo here ( it is the only one on my profile ) for those interested. (vulkan lib needs to be installed to run the app though )

readme provides small info on breakpoints

**Comment by Slaide** [comment]
at that moment in the code i do already have two handles to other opaque pointers privided by the vulkan api, and both do not change throughout the code.

**Comment by mikdusan** [comment]
It looks to me `vkCreateDevice` and `vkCreateInstance` are c-functions. Usage is grouped together just for this post.

```zig
var res = vkCreateDevice(self.physicalDevice, &deviceCreateInfo, self.vkAllocators, &self.device);
var result = vkCreateInstance(&instanceCreateInfo, self.vkAllocators, &self.instance);
```

and `self.device` and `self.instance` turn out to be:

```zig
device: VkDevice,
instance: VkInstance,
```

and they are defined as:

```zig
pub const struct_VkDevice_T = @OpaqueType();
pub const VkDevice = ?*struct_VkDevice_T;

pub const struct_VkInstance_T = @OpaqueType();
pub const VkInstance = ?*struct_VkInstance_T;
```

so there is _an_ issue here. Try doing this instead:

```zig
var tmp_device = struct_VkDevice_T;
var res = vkCreateDevice(self.physicalDevice, &deviceCreateInfo, self.vkAllocators, &tmp_device);
self.device = tmp_device;

var tmp_instance = struct_VkInstance_T;
var result = vkCreateInstance(&instanceCreateInfo, self.vkAllocators, &tmp_instance);
self.instance = tmp_instance;
```

**Comment by Slaide** [comment]
this does not work, since the struct itself is an opaque type, and it is a type mismatch, because of the function definition
`pub extern fn vkCreateDevice(physicalDevice: VkPhysicalDevice, pCreateInfo: [*c]const VkDeviceCreateInfo, pAllocator: [*c]const VkAllocationCallbacks, pDevice: [*c]VkDevice) VkResult;`

**Comment by Slaide** [comment]
if you meant not-null pointers to those types, the program still behaves the same.

**Comment by Slaide** [comment]
sorry for wasting everyones time, i am just stupid...... 

(the function did behave correctly, i am simply passing an uninitialized variable to the function that is called afterwards..)
