### ISSUE TITLE
Unwrapped variables alias the original

### ISSUE THREAD

**Issue by BarabasGitHub** [ziglang/zig#3352]
In previous versions of Zig (pre 4.0) they used to be copies, but now they're an alias it seems. 

My linked list code which previously worked fine is now broken.

https://github.com/BarabasGitHub/ZigZag/blob/f76697ddcfb10d25e35bc4594db4e605ce871be8/containers/single_linked_list.zig#L20

```
            pub fn next(self: *Iterator) ?*Value {
                if (self.node) |node| {
                    self.node = node.next;
                    return &node.value;
                } else {
                    return null;
                }
            }
````

https://github.com/BarabasGitHub/ZigZag/blob/f76697ddcfb10d25e35bc4594db4e605ce871be8/containers/single_linked_list.zig#L47

```
        pub fn count(self: Self) usize {
            var i = usize(0);
            var node = self.head;
            while (node) |n| {
                node = n.next;
                i += 1;
            }
            return i;
        }
```

https://github.com/BarabasGitHub/ZigZag/blob/f76697ddcfb10d25e35bc4594db4e605ce871be8/containers/single_linked_list.zig#L88

```
        pub fn clear(self: *Self) void {
            var node = self.head;
            while (node) |n| {
                node = n.next;
                self.allocator.destroy(n);
            }
            self.head = null;
        }
```

Maybe this is how it's supposed to work, but it's not very intuitive. 

The fix was to make explicit copies, one way or another, see: https://github.com/BarabasGitHub/ZigZag/commit/42148fdbd475c73fc5bc556b07dc465396e17660#diff-fe4c994cb2028068ff82d5e173fd2bf9

**Comment by mikdusan** [comment]
duplicate of #2915
