### ISSUE TITLE
Compiler crash on return optional nested unions with void field

### ISSUE THREAD

**Issue by xash** [ziglang/zig#3360]
When porting a 0.4 project to 0.5 `zig build` crashed and still does in master. The minimal example I could find still has many parts in strange interplay, so that's where the issue title stems from. The central line is `return Outer{.Buggy = Inner{.Field = {} } };`, returning an `?Outer`.

`main.zig:`
```
// using another type, e.g. struct makes it work
const Inner = union(enum) {
    // using another type than void makes it work
    Field: void,
};

// using another type, e.g. struct makes it work
const Outer = union(enum) {
    // leaving out Other makes it work
    Other: u64,
    Buggy: Inner,
};

// leaving out ? in the return type makes it work
fn returnOuter() ?Outer {
    // separating the union creation and return makes it work
    //var t : ?Outer = Outer{.Buggy = Inner{.Field = {} } };
    //return t;

    return Outer{.Buggy = Inner{.Field = {} } };
}

pub fn main() void {
    @import("std").debug.warn("compiled\n");
    _ = returnOuter();
}
```
 
Running `zig run main.zig` there is a segfault on 0x0 in libLLVM-9.so while compiling. This code worked in 0.4 with LLVM 8.0. Skimming over to 0.5 release notes, this might be related to the Result Location Semantics.

**Comment by xackus** [comment]
Runs fine on 0a8835268915feab561bdb68adb17aed76b9708f.
