### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by SrMordred** [ziglang/zig#3363]
Hello gus, just an ideia:
There is the Hacktoberfest happening now, u could mark some "easy" issues with a "Hacktoberfest" tag, and promote in some places, so u give Zig some visibility and could potentially solve some problems as well :)

**Comment by andrewrk** [comment]
Thanks for the idea!

https://github.com/ziglang/zig/blob/master/CONTRIBUTING.md#finding-contributor-friendly-issues
