### ISSUE TITLE
Documentation for : var function parameters

### ISSUE THREAD

**Issue by m-r-hunt** [ziglang/zig#3366]
So as far as I can tell (and from people on Discord), you can declare a function parameter as `: var` and the type will be inferred at compile time. This isn't in the Zig documentation *except* incidentally where's it's used in the printf comptime example (in the `printValue()` function).

This is a very useful feature and should be documented properly I think (unless there's a reason why it's not documented like it's intended to be removed).

**Comment by andrewrk** [comment]
Thanks for taking care of this! https://ziglang.org/documentation/master/#Function-Parameter-Type-Inference
