### ISSUE TITLE
Best way of using variadic types .. ?

### ISSUE THREAD

**Issue by SrMordred** [ziglang/zig#3369]
```
//what I wanted
fn testing( comptime args: ... ) void{}
testing(i32, u32);
//compiles but don´t know how to get args[0], i get:
//error: index 0 outside argument list of size 0

//other attempt
fn testing( comptime args: var ) void{}
testing([_]type{i32, u32});

//work, but this is not what i want :)
```

I feel that the first code is more ergonomic with the way Zig do generics :)
(at least on the caller part)

**Comment by andrewrk** [comment]
var args was removed from the language in a3f6a58c7785e7958f9d0b96d54356944bf34e32

**Comment by marler8997** [comment]
I think the new equivalent to your original would be
```zig
testing(.{i32, u32});
```

However, I don't think inline structs support comptime yet.  @andrewrk is there a plan to support comptime values in structs like this in the future?

**Comment by andrewrk** [comment]
> However, I don't think inline structs support comptime yet.

What test case do you think is not working?

**Comment by marler8997** [comment]
No idea what test case this is, just asking if there is already a plan to support it. I'm guessing the answer is no then?

**Comment by andrewrk** [comment]
```zig
const std = @import("std");

test "it works" {
    testing(.{i32, u32});
}

fn testing(args: var) void {
    std.testing.expect(args.len == 2);
    std.testing.expect(args[0] == i32);
    std.testing.expect(args[1] == u32);
}
```

```
[nix-shell:~/tmp/zig/build-llvm9]$ ./zig test test.zig 
All 1 tests passed.
```

What are you asking about the support of?

**Comment by marler8997** [comment]
Oh it already works.  For some reason mine was failing but now my test code is gone so I'm not sure what I did wrong.  Thanks for the clarification.

**Comment by andrewrk** [comment]
Your code was probably fine - I fixed a lot of issues with anon struct/tuple literals in the efforts to remove var args from zig.
