### ISSUE TITLE
Self referencing struct using array of pointers does not compile

### ISSUE THREAD

**Issue by johan-bolmsjo** [ziglang/zig#3383]
A self referencing struct using an array of pointers does not compile.

    test "self referencing struct using array of pointers" {
        // Does not compile (zig 0.5.0):
        //   error: struct 'Node' depends on itself
        //
        // This is a common implementation technique for tree structures. Even for
        // trees only containing two links it can be used to reduce the code needed
        // to handle left and right rotation cases.
    
        const Node = struct {
            links: [2]?*@This(),
            // The following works as expected:
            //left:  ?*@This(),
            //right: ?*@This(),
        };
        
        var node: Node = undefined;
    }

**Comment by xackus** [comment]
Works on 0a8835268915feab561bdb68adb17aed76b9708f.
