### ISSUE TITLE
comptime initialization cause compiler crash with zig-linux-x86_64-0.5.0+dca6e74f

### ISSUE THREAD

**Issue by johan-bolmsjo** [ziglang/zig#3385]
comptime initialization cause compiler crash with zig-linux-x86_64-0.5.0+dca6e74f

    const std = @import("std");
    
    pub fn Elem(comptime T: type) type {
        return struct {
            next_: *@This(),
            prev_: *@This(),
            value: T,
    
            pub fn init(self: *@This(), value: T) void {
                self.next_ = self;
                self.prev_ = self;
                self.value = value;
            }
    
            pub inline fn next(self: *@This()) *@This() {
                return self.next_;
            }
        };
    }
    
    const debug = std.debug.warn;
    
    fn initTestElems(comptime T: type, comptime n: usize) [n]Elem(T) {
        var arr: [n]Elem(T) = undefined;
        for (arr) |*elem, i| {
            Elem(T).init(elem, @intCast(T, i));
        }
        return arr;
    }
    
    test "I don't know what I'm doing but it crash the compiler" {
        // I'm experimenting and don't really know if this is something that is
        // supposed to work. "var arr" is semantically on the stack of initTestElems
        // and Elem(T).init initializes next and prev pointers to elements in this
        // space. I don't know if zig guarantees that the elems variable below will
        // be the same memory for a lack of better wording as "var arr" in
        // initTestElems when using comptime initialization.
        //
        // ... Anyway it crash the compiler which is surely a bug.
        comptime var elems = initTestElems(i32, 1);
    
        // Variation of the above that also cause a crash.
        //var elems = comptime initTestElems(i32, 1);
        
        debug("\nelems[0].next = {*}\n", elems[0].next());
        debug("&nelems[0]    = {*}\n", &elems[0]);
    }

**Comment by mikdusan** [comment]
Well this code takes pointers on stack and lets it escape. The complicating factor here is forcing it to `comptime`. So the question becomes, if the above code is UB for runtime, what should comptime do with it? I'm not sure, maybe someone else can chime in here, comptime has ever been able to detect such UB.

also unrelated to crash, you can *clean* this up:
```zig
Elem(T).init(elem, @intCast(T, i));
```

to

```zig
elem.init(@intCast(T, i));
```

**Comment by Vexu** [comment]
This no longer crashes the compiler but I'm not sure what the original issue was and the example is not a suitable test case.
