### ISSUE TITLE
Compiler bug: enums with 1 value are considered 'void'

### ISSUE THREAD

**Issue by tomc1998** [ziglang/zig#3397]
```zig
const MyEnum = enum  { OnlyValue };

pub fn main() void {
  var my_enum = MyEnum.OnlyValue;
  std.debug.warn("{}\n", my_enum);
}
```

Errors with
```
error: compiler bug: var args can't handle void. https://github.com/ziglang/zig/issues/557
```

This results in slightly more insidious bugs when the code is more complex than this, especially when doing stuff with 1 value enums at comptime, this causes a segfault:

```zig
    comptime var my_enums : [1]MyEnum = [1]MyEnum { MyEnum.OnlyValue };
    comptime var appended : [2]MyEnum = my_enums ++ [1]MyEnum { MyEnum.OnlyValue };
```

Quick look in gdb shows this is because the array's data just contains a nullptr, where it should be a ConstExprValue.

**Comment by andrewrk** [comment]
solved by removing var args from the language in a3f6a58c7785e7958f9d0b96d54356944bf34e32

updated test case passes:

```zig
const std = @import("std");
const MyEnum = enum {
    OnlyValue,
};
  
pub fn main() void {
    var my_enum = MyEnum.OnlyValue;
    std.debug.warn("{}\n", .{my_enum});
}
```
