### ISSUE TITLE
add function parameter names to generated docs

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#3410]
std lib example: `file:///home/andy/dev/zig/build/zig-cache/docs/index.html#std;io.readFileAlloc` (I recognize this is a file:/// URL; we don't have #3402 done yet)

it shows:

```zig
fn readFileAlloc(*mem.Allocator, []const u8) ![]u8
```

but it should show:

```zig
fn readFileAlloc(allocator: *mem.Allocator, path: []const u8) ![]u8
```

I would also like to propose the following rule:

 * when a parameter name is its type name lower cased, the parameter name is omitted.

That would further adjust the expected docs to be:

```zig
fn readFileAlloc(*mem.Allocator, path: []const u8) ![]u8
```

**Comment by MasterQ32** [comment]
> when a parameter name is its type name lower cased, the parameter name is omitted.

This is a great idea! Sometimes the type is documentation enough about how to use a certain parameter. Especially for something like `*std.mem.Allocator` the use in the Zig language is quite clear and thus removes clutter from the documentation.

**Comment by andrewrk** [comment]
Thanks @FireFox317 for the implementation of this! I added the part about omitting parameter names that match the type.
