### ISSUE TITLE
Hello World cannot be compiled

### ISSUE THREAD

**Issue by mridulkrishnamishraeh** [ziglang/zig#3428]
I had recently installed zig on my laptop(ubuntu) but i was not able to compile the hello world program.
I had installed zig using snap. I have the beta version of it.
here is the error message i get..
```
zig build-exe hello.zig
/home/mridul/zig/hello.zig:3:21: error: expected token '}', found '%'
pub fn main() void {%%io.stdout.printf("Hello, world!\n");
                    ^
```

**Comment by CurtisFenner** [comment]
Zig's hello world hasn't looked like that for many versions. Make sure you're looking at the [up to date documentation](https://ziglang.org/documentation/0.5.0/#Hello-World):

```zig
const std = @import("std");

pub fn main() !void {
    // If this program is run without stdout attached, exit with an error.
    const stdout_file = try std.io.getStdOut();
    // If this program encounters pipe failure when printing to stdout, exit
    // with an error.
    try stdout_file.write("Hello, world!\n");
}```
