### ISSUE TITLE
"Why Zig" wiki page contains broken link

### ISSUE THREAD

**Issue by evertrol** [ziglang/zig#3452]
The link at the bottom of https://github.com/ziglang/zig/wiki/Why-Zig-When-There-is-Already-CPP%2C-D%2C-and-Rust%3F (the last of the three examples) is a broken link.
The correct link should be https://sjdh.us/posts/continuing-with-zig/

Also, this section could have a subsection header, something akin to "People having problems with Rust". Note that only that last project is about moving to Zig, while the others use Python or C instead of Rust. So perhaps the whole example link section should just be scratched.

**Comment by nrdmn** [comment]
I've changed the link.
