### ISSUE TITLE
zig run command line parameters are not handled correctly

### ISSUE THREAD

**Issue by timmyjose** [ziglang/zig#3475]
Note: I am opening this issue based on my understanding that `zig build-exe` and `zig run` should have similar semantics. If not, please close this as a non-issue.

Sample program: https://ziglang.org/documentation/master/#Import-from-C-Header-File

```zig
const c = @cImport({
    @cDefine("_NO_CRT_STDIO_INLINE", "1"); // Windows specific stuff
    @cInclude("stdio.h");
});

pub fn main() void {
    _ = c.printf(c"Hello, %s!\n", c"world");
}
```

Test run with `zig build-exe c_import.zig --library c`:

```
~/c/s/z/z/c (master|…) $ zig build-exe c_import.zig --library c
~/c/s/z/z/c (master|…) $ ./c_import
Hello, world!
```

Test run with `zig run c_import.zig --library c`:

```
~/c/s/z/z/c (master|…) $ zig run c_import.zig --library c
/Users/z0ltan/code/study/zig/zig_lang/c/c_import.zig:2:11: error: C import failed
const c = @cImport({
          ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdio.h:108:15: note: 'stdio.h' file not found
#include_next <stdio.h>
              ^
/Users/z0ltan/code/study/zig/zig_lang/c/c_import.zig:8:9: note: referenced here
    _ = c.printf(c"Hello, %s!\n", c"world");
        ^
```

System and Compiler details:

OS:

~/c/s/z/zig_lang (master|…) $ sw_vers
ProductName: Mac OS X
ProductVersion: 10.14.6
BuildVersion: 18G95

Compiler:

~/c/s/z/z/c (master|…) [1] $ zig version
0.5.0+8b459216

**Comment by andrewrk** [comment]
* [ ] ability to pass compiler args such as `--library c` to zig run. same args as `build-exe`.
 * [ ] ability to pass args to the binary, after `--`
