### ISSUE TITLE
trailing comma in functions

### ISSUE THREAD

**Issue by Slaide** [ziglang/zig#3496]
i do not know if there already has been a discussion about this, but the trailing comma exists in functions, meaning function definitions and calls, where i do not think that it is well placed.
```
pub fn A(r:i32)i32{
  var b=r+2;
  b+=2;
  return b;
}
pub fn B()i32{
  return 6;
}
pub fn C(r:i32,)i32{
  var b=r+2;
  b+=2;
  return b;
}

pub fn main()void{
  var a=A(2);
  var b=A(2,);
  var c=B();
  //var d=B(,); //uncomment me, i am a compilation error
  var e=C(3);
  var f=C(3,);
}
```
this code compiles. the question is, if this is a good idea (or a bad one, it may be neither).
having a trailing comma in argument lists by default is good, but placing that inside functions is dubious in my opinion. the only problem i see with it though is that it decreases readability a bit, because a comma inside a function call/def in every other language means that there should be something on its right side (sometimes if there is nothing there, the compiler will fill it with a default value, which is why a reader may have the assocation and wonder why the code compiles, which is excatly what i did)

is this even by design or by accident?

but to be honest, i do not have an issue with it that would mean it should be removed, i am just curious what others think.

**Comment by andrewrk** [comment]
It's intentional. `zig fmt` changes this to be multiline function call:

https://github.com/ziglang/zig/blob/ddb87237de60cb0feacc606d21c9dd48c5c3bd4b/lib/std/zig/parser_test.zig#L548-L558

**Comment by ifreund** [comment]
> Hello, just found out about this behavior today. Is this still intended?

yes
