### ISSUE TITLE
implement ".." (parent directory) for std.fs.Dir.openDir on Windows

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#3501]
https://github.com/ziglang/zig/blob/e839250c5156d438f76e7b08e7053e9087fae77c/lib/std/fs.zig#L768-L772

example zig code:

```zig
const std = @import("std");

pub fn main() anyerror!void {
    var it = try std.fs.walkPath(std.heap.direct_allocator, "..");
    while (try it.next()) |entry| {
        std.debug.warn("{}\n", entry.path);
    }
}
```

```
> zig.exe build-exe test.zig
> test.exe 
TODO opening '..' with a relative directory handle is not yet implemented on Windows
```

**Comment by Leguu** [comment]
Is it possible to evaluate just `.` as an absolute file path and then remove the final bit in order to get the directory of `..`? 

E.g; `.` is `C:\Users\Legu\`, and therefore stripping the last bit gives you `C:\Users` 

I'm new to contributing, so I hope this makes sense.

**Comment by Andoryuuta** [comment]
This appears to have been fixed by changes made in the last ~2 years.

I have just tested the following from the latest commit in the master branch (#5d14590), and can confirm it's working as expected:
```zig
const std = @import("std");

pub fn main() !void {
    const dir = try std.fs.cwd().openDir("..", .{.iterate = true});

    var walker = try dir.walk(std.heap.page_allocator);
    defer walker.deinit();

    while (try walker.next()) |entry| {
        std.debug.print("path: {s}\n", .{entry.path});
    }
}
```

**Comment by marler8997** [comment]
Yeah I believe this was implemented with https://github.com/ziglang/zig/pull/7664
