### ISSUE TITLE
Stack tracing fails when `catch` statement is present in main for i386-freestanding target

### ISSUE THREAD

**Issue by pixelherodev** [ziglang/zig#3507]
If no catch statement is present in the main function, I can get detailed stack traces. 

![thisisawesome](https://user-images.githubusercontent.com/10342579/67351601-e9fb6680-f51b-11e9-9f04-101dfbf5945f.png)

However, with any `catch` statement in `main` - *even ones that don't get triggered* - an `unreachable` assertion is hit somewhere within the backtracing code.

This is most likely a bug with the DWARF parser; I'll try and track it down myself tonight.

**Comment by pixelherodev** [comment]
While testing this requires more than a small snippet can show - GDT, heap, etc - a simple line of code that demonstrate the problem is this:

If this code is anywhere within main, when the kernel panics - usually at `attempted to return from main` - there's a second panic, with the normal "unreachable code" message
```zig
var serial = std.fs.File.openWrite("/dev/ttyS0") catch unreachable;
```

Note: the panic isn't *on that line*. It's later, after that code is executed without issue.

With a custom function like this:
```zig
fn get_serial() std.fs.File {
    return std.fs.File.openWrite("/dev/ttyS0") catch unreachable;
}
```

and then 
```zig
var serial = get_serial();
``` 
in main, everything works properly.

**Comment by andrewrk** [comment]
One strategy to solve this would be to target i386-linux instead of freestanding and slap a main() on there to try to trigger this behavior in non-freestanding mode. It would then be easier to debug and make a smaller reduction.

**Comment by LemonBoy** [comment]
Eh, I'd rate your instructions 3/10 :star:, I couldn't fully grasp what the problem is.

What I got so far is that you're sometimes hitting [this](https://github.com/pixelherodev/limnos/blob/cd7cc854fc745dc6a189f1711b18e586fa26e86d/src/zig/std/debug.zig#L105) line that then ends up [here](https://github.com/pixelherodev/limnos/blob/cd7cc854fc745dc6a189f1711b18e586fa26e86d/src/zig/std/os.zig#L1226).

**Comment by pixelherodev** [comment]
In my defense, I hadn't realized that at the time.

Thanks for the tip, I'm going to double check whether this is due to my modified standard lib and if so close this.

**Comment by andrewrk** [comment]
@pixelherodev can you also open an issue explaining your use case with regards to patching the zig std lib? There's a good possibility we can make changes to handle your use case such that you can accomplish your goals without having to modify the std lib. E.g. providing ability to override std.os functions in the root source file.

**Comment by pixelherodev** [comment]
I was literally just about to suggest using something like `usingnamespace @import("root")`.

Mainly, I'm just overriding a few specific functions - `std.os.{open,read,write}` etc.

**Comment by andrewrk** [comment]
I'd be interested to see your full std lib diff

**Comment by pixelherodev** [comment]
Shouldn't be that big at the moment. Biggest thing was adding the backtracing directly into std.debug instead of doing it as part of the main project.

**Comment by pixelherodev** [comment]
[changes.zip](https://github.com/ziglang/zig/files/3764696/changes.zip) That contains a diff file which should have all changes other than the limnos.zig files in std/os and std/os/bits

**Comment by andrewrk** [comment]
OK great, yes I have an idea to make some clean & simple std lib modifications which will entirely remove the need for you to patch it.

**Comment by pixelherodev** [comment]
Not sure why `catch` in main triggered this, but @LemonBoy was completely right.
