### ISSUE TITLE
zig output broken in emacs

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#3509]
It looks like the zig compiler is now printing status updates, however, in emacs this ends up looking this:
```
Semantic Analysis [983/1142] Semantic Analysis [1029/1205] Semantic Analysis [1070/1308] Semantic Analysis [1122/1351] Semantic Analysis [1196/1484] Semantic Analysis [1339/1579] Semantic Analysis [1435/1664] Semantic Analysis [1470/1716] Semantic Analysis [1519/1767] Semantic Analysis [1547/1804] Semantic Analysis [1592/1845] Semantic Analysis [1660/1886] Code Generation [129/1411] std.debug.getLineNumberInfoDwarf...Code Generation [461/1411] std.fs.path.resolvePosix...Code Generation [824/1411] std.hash_map.HashMap([]const u8,std.build.AvailableOp...Code Generation [1144/1411] std.mem.Allocator.free...LLVM Emit Output...Build Dependencies...
```

I know that emacs uses the environment variable `TERM=dumb` to indicate that it doesn't support certain terminal control sequences.  Zig should probably check the `TERM` variable to know how to handle things like this.

**Comment by andrewrk** [comment]
https://github.com/ziglang/zig/blob/e98e5dda52d8bcaa2e59861bbbd500b81edfde2d/lib/std/fs/file.zig#L175-L181

**Comment by marler8997** [comment]
This one may be more complex than I thought.  I think emacs supports ansi escape codes, it just looks like the shell doesn't support the lone-carriage return mechanism.  And I'm not sure that `TERM=dumb` necessarily implies that the terminal you are using does not support this either.  I'll have to look into this more.  Either I just need to configure emacs differently when I use Zig, or Zig needs some way to determine if the current shell environment supports lone-carriage returns.

**Comment by andrewrk** [comment]
If you need a quick workaround you can use `--color off`.

`TERM=dumb` [does seem to be some kind of standard](https://stackoverflow.com/questions/39001517/features-obligatory-for-term-dumb-terminal). On my setup right now:
```
andy@ark ~> env | grep TERM
COLORTERM=truecolor
TERM=xterm-256color
```

**Comment by marler8997** [comment]
Doing a bit of testing, it looks like emacs does support lone carriage-returns.  So it might just be that it doesn't support ansi escape sequences.  I'll create a patch to detect `TERM=dumb` and see if it fixes it.

**Comment by andrewrk** [comment]
Do you think it should check if the file is stderr, and only then look up the `TERM` variable? `TERM` is uncomfortably global.

**Comment by marler8997** [comment]
maybe we should check `isTty` first, then if that's true, confirm it by checking TERM

**Comment by andrewrk** [comment]
I think that plus if the file is stdout or stderr.

**Comment by marler8997** [comment]
https://github.com/ziglang/zig/pull/3510
