### ISSUE TITLE
init-exe fails to build with libc for native target on 'pentium-m' CPU (syslevel QEMU?)

### ISSUE THREAD

**Issue by rohlem** [ziglang/zig#3518]
**UPDATE**: I've since found out (`uname -r` > `3.10.0-1062.4.1.el7.x86_64`) that the system is running an unsupportedly old Linux kernel according to the support table; although this issue seems to be related to (reported) hardware configuration, so maybe it's still relevant?

Steps to reproduce on the system in question:
```
zig init-exe
< edit generated build.zig to include line: exe.linkSystemLibrary("c");
zig build
```
Output:
```
Link...Build Dependencies...error: unknown target CPU 'pentium-m'
note: valid target CPU values are: nocona, core2, ..., znver1, znver2, x86-64

The following command failed:
zig cc -MD -MV -MF ... -march=native -g ... 
```
(the zig cc command seems to me like it's compiling the zig-bundled libc)
I would have assumed that Zig gets these classifications directly from clang, but I guess this is some edge case that slipped through the cracks.

I encountered this on some (Linux) university server via ssh, so I can't say exactly what the system configuration looks like, however, `cat /proc/cpuinfo` shows 16 entries like the following:
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version (cpu64-rhel6)
stepping        : 3
microcode       : 0x1
(...)
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl eagerfpu pni cx16 hypervisor lahf_lm abm
(...)
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```
I guess `QEMU` tells us that at least some kind of system-shadowing layer is present (whether actual emulation (seems unlikely), hypervisor, ...); I don't know any specifics.

If this gets parsed from some intermediary file clang (zig cc) produces, I'd be happy to follow directions towards finding the culprit file/string.

EDIT: Forgot to add, the obvious fix for me was to explicitly cross-compile for the native system (`x86_64-linux-gnu`), so it falls back to a known default, which worked without issue.

**Comment by alexrp** [comment]
@rohlem does this still reproduce? (Assuming you even still have access to that machine.)

**Comment by rohlem** [comment]
@alexrp unfortunately it's been too long, I don't have access anymore and don't remember any details beyond what's written in the issue.
That other issue looks like a more recent duplicate, so as a tracking issue I assume either one is fine.

It seems like the issue used to be that Zig somehow deduces/passes `pentium-m`,
which is considered invalid in the context of the other flags,
while `-mcpu=pentium_m` explicitly supplied to Zig from the top level works correctly.

Whether that can still happen or has been fixed in the mean time (f.e. during one of the LLVM upgrades), I also can't say.

**Comment by alexrp** [comment]
Judging by the `std.zig.system` code, that CPU will still be detected as `pentium_m`.

But, I don't see us passing `-march=native` to Clang anywhere anymore. ad438a95c528c4a2013e3e7fb99ea9a260143eb3 made it conditional (a day after this issue, as it happens), but it seems to have since been removed entirely in some other commit.

**Comment by rohlem** [comment]
Feel free to close it.
It does look like it was a Zig-to-LLVM communication/configuration issue originally, and https://github.com/ziglang/zig/issues/11387 still reported something similar.
But if you say the respective code changed since then, I don't see much value in having the issue open until someone runs into it again and can provide a more up-to-date reproduction.
