### ISSUE TITLE
Proposal (zig build): when linking objects with different target configurations, either coerce or abort step

### ISSUE THREAD

**Issue by rohlem** [ziglang/zig#3521]
Half new, half follow-up to #3520 .
_Documentation, or a tutorial, on `std.build` would help (already in the master docs, but doesn't seem thoroughly tested, so many declarations are missing), but I think this is a sensible goal either way._
Originally, I (incorrectly) wrote a `build.zig fn build(*Builder) void` containing:
```[zig]
const sb = @import("std").build;
const exe = b.addExecutable("main", null);
const obj = b.addObject("main", "src/main.zig");
exe.addObject(obj);
exe.setTheTarget(sb.Target{.Cross = sb.CrossTarget{.arch = .x86_64, .os = .linux, .abi = .gnu}});
//obj is still compiled as native!
```
On windows, this leads to a link error `LLD: error: (local zig-cache)\o\...\main.obj: unknown file type`.
However, on an old Linux server (which had `x64_86-linux-gnu` reported as _native target_), native-cross-compiling only the executable and not the object made `@cImport` stop working (with an incorrect error message, see #3520 ).

So the question is: Are there _any supported use case_ for when linking objects compiled via _different target configurations (including native-native vs cross-native)_ leads to **sane behaviour**?
If not, `zig build` should look out for this and report it as error. Even if it is, it might be warranted to hide it behind an opt-in flag (`exe.allowDifferingTargets: bool`), since the error behaviour seems so unpredictable.

(The one scenario I could maybe think of would be compiling a library for different CPU features, and runtime switching to the correct implementation; but even there dynamic linking might be preferrable if available. Definitely exotic enough to have an opt-in switch, or a more sophisticated cutom build step.)

I also think it would make sense to propagate targets, so to make the target optional and auto-assume if null, based on the executable it is added to. This could even allow an object being added to several executables with different targets, and each exe then triggers a new compilation for its own target (since they're already being cached anyway).

**Comment by andrewrk** [comment]
Thanks, this is an important thing to fix.

> I also think it would make sense to propagate targets, so to make the target optional and auto-assume if null, based on the executable it is added to. This could even allow an object being added to several executables with different targets, and each exe then triggers a new compilation for its own target (since they're already being cached anyway).

I'm open to experimenting with this. But if it ends up making build scripts too difficult to reason about, then I think we should fall back to requiring explicitness and simply emitting an error if there is a conflict.

**Comment by he-la** [comment]
I am currently writing a very simple kernel in zig and have found that it would be helpful if there was a possibility to set targets on a per-file/library basis and link them together. For example the default x86 baseline target emits SSE instructions, but those need to first be enabled by setting the according bits in some CPU registers. To do this cleanly one would first need to check CPUID etc. It would be nice if I could have some "stage 0" code compiled for non-SSE targets (e.g. the first pentium) to set things up, and jump into a stage 1 compiled for an SSE target. This would require linking objects with different targets.

This is definitely an exotic scenario and not a priority, but some very low-level systems code will find good use for it.

**Comment by andrewrk** [comment]
The build system should just construct the CLI and the CLI should report the problem. The CLI needs to also report the problem anyway when the build system is not involved.

As that describes status quo, rejecting the proposal.
