### ISSUE TITLE
segfault when slicing with pointer start index

### ISSUE THREAD

**Issue by emekoi** [ziglang/zig#3529]
test case:
```zig
test "foo" {
    _ = blk: {
        var array = [_]u8{};
        var idx: *usize = undefined;
        break :blk array[idx.*..];
    };
}
```

**Comment by LemonBoy** [comment]
The result location madness strikes again. In `ir_render_slice` we have that `tmp_struct_ptr` is `nullptr` because the result is actually discarded and the result slot is typed as `*void`.

One should add something like this to 

```zig
    if (!type_has_bits(instruction->result_loc->value.type)) {
        return nullptr;
    }
```
just before the line:

```zig
LLVMValueRef tmp_struct_ptr = ir_llvm_value(g, instruction->result_loc);
```

**Comment by tuket** [comment]
What should be the expected output for this?

**Comment by emekoi** [comment]
this is a reduced test from somewhere else in my code. what it boils down to is that i was trying to index an array with a variable from a capture block in a loop.

**Comment by andrewrk** [comment]
This now gives:

```
./test2.zig:5:25: error: expected type 'void', found '[]u8'
        break :blk array[idx.*..];
                        ^
```

expected output is to compile successfully.
