### ISSUE TITLE
Undefined symbols in fmt with i386-uefi-msvc

### ISSUE THREAD

**Issue by JamesLupiani** [ziglang/zig#3530]
When compiling this program:
```zig
const fmt = @import("std").fmt;

pub fn main() void {
    var buf: [100]u8 = undefined;
    var a: u64 = 42;
    _ = fmt.bufPrint(buf[0..], "{}", a) catch unreachable;
}
```
I get linker errors when building for UEFI 32-bit:
```
zig build-exe -target i386-uefi-msvc minimal.zig

lld: error: undefined symbol: __aullrem
>>> referenced by /snap/zig/966/lib/zig/std/fmt.zig:950
>>>               ./minimal.obj:(_std.fmt.formatIntUnsigned)

lld: error: undefined symbol: __aulldiv
>>> referenced by /snap/zig/966/lib/zig/std/fmt.zig:953
>>>               ./minimal.obj:(_std.fmt.formatIntUnsigned)
```

It does work on x86_64-uefi-msvc and i386-windows-msvc, however.

**Comment by LemonBoy** [comment]
Changing [this](https://github.com/ziglang/zig/blob/3aeb1b115d5de3ebae6fdbbb8d2f87c875413f87/lib/std/special/compiler_rt.zig#L236) line to `if (builtin.os == .windows or builtin.os == .uefi) {` should fix the problem.

**Comment by nrdmn** [comment]
> Changing [this](https://github.com/ziglang/zig/blob/3aeb1b115d5de3ebae6fdbbb8d2f87c875413f87/lib/std/special/compiler_rt.zig#L236) line to `if (builtin.os == .windows or builtin.os == .uefi) {` should fix the problem.
But why would we want this code in an EFI application? Shouldn't we get llvm to not require these symbols?

**Comment by LemonBoy** [comment]
> But why would we want this code in an EFI application? Shouldn't we get llvm to not require these symbols?

For the same reason you want those in a standard Win32 non-EFI application, LLVM expects those to be defined by the Microsoft compiler runtime and so makes use of them.

**Comment by andrewrk** [comment]
I wrote a tiny bit about the purpose of compiler-rt here: https://ziglang.org/download/0.5.0/release-notes.html#compiler-rt

**Comment by nrdmn** [comment]
> LLVM expects those to be defined by the Microsoft compiler runtime

LLVM expects those because we're currently telling LLVM to compile EFI applications as Windows applications. [See here](https://github.com/ziglang/zig/blob/master/src/target.cpp#L301)
