### ISSUE TITLE
Make implicit cast of tagged unions to their enums easier to find in the docs

### ISSUE THREAD

**Issue by xackus** [ziglang/zig#3543]
I am implementing JSON-RPC. I am dealing with lots of tagged unions and optionals.
Currently ensuring a tagged union is of a particular type is quite verbose.
I can either do:
`@TagType(json.Value)(versionVal) == .String`
or:
```
switch(versionVal){
    .String => true,
    else => false
}
```
In this use case quite often you just need to check for a specific tag and return an error if it does not match.
It would be nice if there was at least a `@tagValue`:
`@tagValue(versionVal) == .String`
or maybe some kind of syntax for unwrapping, but I am not sure how it would look.
An if with two parameters?
And some kind of `orelse` equivalent would be nice too.

I hope I haven't missed any easier way, but I couldn't find anything in the documentation, github issues or looking through std library code.

**Comment by emekoi** [comment]
this might not be in the docs but, tagged unions implicitly cast to their tag type:
```zig
const Enum = union(enum) {
    A: isize,
    B: usize,
};

test "test" {
    var b = Enum{ .B = 2 };
    if (b == .A) {
        unreachable;
    }
}
```

**Comment by xackus** [comment]
Thank you!
I will add this to the docs.

**Comment by xackus** [comment]
Turns out this is in the docs under implicit casts. I will add a link to there from the union section.
