### ISSUE TITLE
Allow non-optional types to be "unwrapped"

### ISSUE THREAD

**Issue by oakes** [ziglang/zig#3549]
One nice advantage that Zig's (and Kotlin's) optional types have over monadic types like Rust's `Option` is that they avoid unnecessary breaking changes. Changing a function's argument from non-optional to optional (easing a requirement), or a function's return type from optional to non-optional (strengthening a guarantee), doesn't necessarily force callers of the function to change anything. However there is still a case where it does, and this proposal is to fix that.

If my library has a function that returns an optional value:

```zig
pub fn divide(num: f32, denom: f32) ?f32 {
    if (denom == 0) {
        return null;
    } else {
        return num / denom;
    }
}
```

...and later I decide I never need to return null:

```zig
pub fn divide(num: f32, denom: f32) f32 {
    return num / denom;
}
```

I have broken this consumer of my library:

```zig
pub fn main() anyerror!void {
    const optional_ret = divide(1, 2);
    if (optional_ret) |ret| { // error: expected optional type, found 'f32'
        std.debug.warn("{}\n", ret);
    }
}
```

This wouldn't break if the caller made the type explicit with `const optional_ret: ?f32 = divide(1, 2);` but most people will be relying on zig's type inference, so their code would break.

The obvious solution would be to just allow non-optional types to be "unwrapped" with Zig's `if` and `orelse`. I don't know enough about Zig's compiler but I imagine it could elide the branch entirely at compile time since it knows it's not an optional type.

It's easy to just say that library consumers should fix the breakage themselves, but as people write larger codebases in Zig I think it will be more important to encourage additive (non-breaking) changes, perhaps with a warning to encourage consumers to clean up the unnecessary unwrapping code.

As a reference see [Rich Hickey's coverage](https://youtu.be/YR5WdGrpoug?t=560) of this topic.

**Comment by andrewrk** [comment]
I don't recognize this as a valid use case. The compile errors in this example are a feature, alerting API users to places where assumptions have become invalidated. 

If the API maintainer wants to not break API then they need to make a new function name and note the old one as deprecated.

Internal to a package, certainly one should fix all the callsites as it will likely lead to other improvements and bug fixes.
