### ISSUE TITLE
Some DragonFlyBSD tests are disabled

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#3563]
```
[nix-shell:~/dev/zig/build]$ grep -RI 'dragonfly.*Skip' ../lib/std/ ../test/
../lib/std/os/test.zig:    if (builtin.os == .dragonfly) return error.SkipZigTest;
../lib/std/os/test.zig:    if (builtin.os == .dragonfly) return error.SkipZigTest;
../lib/std/os/test.zig:    if (builtin.os == .dragonfly) return error.SkipZigTest;
../lib/std/os/test.zig:    if (builtin.os == .dragonfly) return error.SkipZigTest;
../lib/std/statically_initialized_mutex.zig:    if (builtin.os == .dragonfly) return error.SkipZigTest;
../lib/std/event/channel.zig:    if (builtin.os == .dragonfly) return error.SkipZigTest;
../lib/std/event/lock.zig:    if (builtin.os == .dragonfly) return error.SkipZigTest;
../lib/std/event/group.zig:    if (builtin.os == .dragonfly) return error.SkipZigTest;
../lib/std/mutex.zig:    if (builtin.os == .dragonfly) return error.SkipZigTest;
../lib/std/atomic/queue.zig:    if (builtin.os == .dragonfly) return error.SkipZigTest;
../lib/std/atomic/stack.zig:    if (builtin.os == .dragonfly) return error.SkipZigTest;
../test/stage1/behavior/byteswap.zig:    if (builtin.os == .dragonfly) return error.SkipZigTest;
../test/stage1/behavior/vector.zig:    if (builtin.os == .dragonfly) return error.SkipZigTest;
```

Also grep for this issue number.

**Comment by tse-gratis** [comment]
../lib/std/.... errors are resolved in upcoming pull request

Remaining errors:
../test/stage1/behavior/byteswap.zig:    if (builtin.os == .dragonfly) return error.SkipZigTest;
../test/stage1/behavior/vector.zig:    if (builtin.os == .dragonfly) ret

Fail with:
>LLVM Emit Output...Assertion failed: (ActualSize >= (NumVecElements * ElementSize) && "Invalid vector size"), function hasVectorBeenPadded, file /construction/llvm/llvm-9.0.0.src/lib/CodeGen/AsmPrinter/DwarfUnit.cpp, line 1356.
The following command terminated unexpectedly:
/home/tse/Packages/zig-3/build/zig test /home/tse/Packages/zig-3/test/stage1/behavior.zig --test-name-prefix behavior-native-Debug-bare-multi  --cache-dir /home/tse/Packages/zig-3/zig-cache --name test --override-lib-dir /home/tse/Packages/zig-3/lib

**Comment by andrewrk** [comment]
> .Assertion failed: (ActualSize >= (NumVecElements * ElementSize) && "Invalid vector size"), function hasVectorBeenPadded, file /construction/llvm/llvm-9.0.0.src/lib/CodeGen/AsmPrinter/DwarfUnit.cpp, line 1356.

This is a bug in LLVM. Let's get a separate issue going for this to track, and this will require filing an upstream bug report.
