### ISSUE TITLE
Move user zig-cache under ~/.cache

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#3573]
> As of Zig 0.5.0 the build cache can be found in the following locations unless overridden with command-line options:
>
> TYPE | OS | DIRECTORY
> :-: | :-: | ---
> global | linux | $HOME/.local/share/zig

Instead, could we use `$XDG_CACHE_HOME/zig` and fall back to `$HOME/.cache/zig`?

On my systems, `~/.cache` is excluded from system snapshots/backups. I've recently realised that zig has been filling up my home partition :(

**Comment by andrewrk** [comment]
> I've recently realised that zig has been filling up my home partition :(

It's planned to have automatic LRU eviction, once the cache code moves to becoming self-hosted. For now, it's safe to delete it whenever you want to free space.

> Instead, could we use `$XDG_CACHE_HOME/zig` and fall back to `$HOME/.cache/zig`?

Sounds reasonable to me.
