### ISSUE TITLE
Zig execuatable for windows X64 crashes

### ISSUE THREAD

**Issue by Wilco-user** [ziglang/zig#3576]
Just down loaded the latest version,unzipped and test ran.After installing all the required missing dll's from microsoft I tried Zig.exe again.Crashed with error code 0xc000007b. Tried again after installing llvm and rebooting.No joy. Could someone please tell me how to fix this issue.
The actual error message was "The application was unable to start (0xc000007b). I am not sure if this a Windows stuff up or a bad binary.I downloaded the latest (as at 02/11/2019) Zig from the Zig website zigland.
Any help would be appreciated as I do not have the hard drive space on my note book to install CMAKE and I dont want to install Visual studio.(I use other tools)

**Comment by andrewrk** [comment]
> After installing all the required missing dll's from microsoft

Which dlls was this? it is supposed to be none.

**Comment by Wilco-user** [comment]
It complained that concrt140.dll , vcruntime140.dll and msvcp140.dll were missing.I am not sure whats going on here if Zig doesnt need dlls

**Comment by andrewrk** [comment]
I just looked at [zig-windows-x86_64-0.5.0+081c62fc.zip](https://ziglang.org/builds/zig-windows-x86_64-0.5.0+081c62fc.zip) and it seems the required DLLs do not include these. I know that there was a problem with 0.5.0 requiring vcruntime, but this has been fixed since then. Which download did you try?

**Comment by Wilco-user** [comment]
Sorry,my connection dropped out.I downloaded zig-windows-x86_64.05.0.zip

**Comment by Wilco-user** [comment]
Is there a later version and where can I get it from ?

**Comment by andrewrk** [comment]
Where did you get that version from? There is a later version linked on https://ziglang.org/download/.

This very issue is why I am considering releasing 5.0.1 which does nothing except remove the msvcrt.dll dependency.

**Comment by Wilco-user** [comment]
Oops,the filename downloaded was actually zig-windows-x86_64+081c62fc.zip. If that helps.

**Comment by Wilco-user** [comment]
Hang on sec, I'll type that name manually seeing as cut & pastes is dropping out details.
zig-windows-x86-64-0.5.0+081c62fc.zip
My appologies for the incorrect filename

**Comment by Wilco-user** [comment]
I will send you the zip file if you like...

**Comment by Wilco-user** [comment]
Ok,just used your link and it works fine.I dont know what happened earlier,but its running fine..Now I can  start trying this out.I really appreciate the help thanks a lot

**Comment by Wilco-user** [comment]
Help with this issu was excellent,great work !

**Comment by Wilco-user** [comment]
Thanks,used your link and everything works ok.I appreciate the effort 
and look forward to trying this.I intend to rewrite quiet a lot of C 
code into this once I have learned some more (after trying it).Once I 
can get my things working,I will post them on git-hub.

Regards,

  Ron (wilco-user on github)
