### ISSUE TITLE
Possible bug: f128 constant only has 16 decimals of precision when printed

### ISSUE THREAD

**Issue by bdezonia** [ziglang/zig#3612]
Using 0.5.0 the following code:

var z : f128 = 1.738954882048422195749048390299;
warn("{:.34}\n",z);

Shows this:

1.7389548820484222000000000000000000e+00

It's like the compile time constant is 64 bit rather than 128 bit. The documentation implies that floating constants are 128 bit.

Is this a bug? Or am I doing something wrong?

**Comment by LBEaston** [comment]
This is because the current float formatter internally works on 64bit floats. #1299 should fix this.

**Comment by Mouvedia** [comment]
dupe of #1181?
