### ISSUE TITLE
Ask for documentation in Indonesian

### ISSUE THREAD

**Issue by hadihammurabi** [ziglang/zig#3615]
Here, in Indonesia, there are a lot of developer that want to learn about new technology, including Zig. But, we have a problem. Mostly, we have limitation in foreign languages.

I think, it will help Indonesian developer to learn about Zig.

Thanks

**Comment by MasterQ32** [comment]
I don't think it's reasonable to maintain a second version of the docs as they change constantly and one has to update both the english and any non-english versions when changing things in the docs.

Imho this is something for post-1.0, when the language is stable

**Comment by dummyeuy** [comment]
> I don't think it's reasonable to maintain a second version of the docs as they change constantly and one has to update both the english and any non-english versions when changing things in the docs.
> 
> Imho this is something for post-1.0, when the language is stable

So in terms of translating into another language (e.g. translating into Bahasa Indonesia), we need to wait until the language (Zig itself) is stable, correct?

**Comment by haze** [comment]
Maybe this issue can serve as a starting point for brainstorming easy i18n?

**Comment by andrewrk** [comment]
An Indonesian translation of the documentation would be great. However, I think it will be a good project to be external to the Zig project. Maintaining a translation requires ongoing work, and until Zig Software Foundation is officially started, and has enough funding to pay for translations, this is something that would have to be done by volunteers.

If such translation projects exist however, I would be happy to update the canonical documentation with links to the translations.
