### ISSUE TITLE
Compiler crashes on recursive type

### ISSUE THREAD

**Issue by P1start** [ziglang/zig#3632]
The following code causes the compiler to segfault:
```zig
const Foo = struct {
    foo: Foo,
};

pub fn main() anyerror!void {
    var x: Foo = undefined;
}
```
Tested on master and 5.0.0. Obviously, this code shouldn't compile, but this should output the usual `struct 'Foo' depends on itself` error instead of crashing. The crash seems to only occur when the struct `Foo` only has the one recursive field – adding a second field of type `bool` prints the normal error message.

Running through gdb, the cause seems to be infinite recursion between `type_val_resolve_has_one_possible_value` and `type_has_one_possible_value` in src/analyze.cpp.

**Comment by P1start** [comment]
Another crash which may be related: this code
```zig
fn Bar(comptime T: type) type {
    return Bar(T);
    return struct { // both returns are needed for the abort
        field: Bar(T),
    };
}

pub fn main() anyerror!void {
    var x: Bar(bool) = undefined;
}
```
aborts with `Unreachable at /build/source/src/analyze.cpp:4842 in handle_is_ptr. This is a bug in the Zig compiler.`

**Comment by andrewrk** [comment]
Test case now gives:

```
./test2.zig:1:13: error: struct 'Foo' depends on itself
const Foo = struct {
            ^
./test2.zig:2:5: note: while checking this field
    foo: Foo,
    ^
./test2.zig:6:18: note: referenced here
    var x: Foo = undefined;
                 ^
```
