### ISSUE TITLE
Semantic Analysis [1519/1781] Killed

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#3633]
Compiler produces some progress then says “Killed”

https://github.com/markfirmware/zig-bare-metal-raspberry-pi

zig build

alpine aarch64 rpi3b+

**Comment by andrewrk** [comment]
This typically means that the compiler used too much memory and the OOM Killer reaped the process. 

I believe this is a duplicate issue to #471.

**Comment by markfirmware** [comment]
FYI I first saw this on 1GB x64 in the last few days. I have found that using zig build-exe instead of build.zig does work in both cases.
