### ISSUE TITLE
builtin_tld assert in codegen.cpp

### ISSUE THREAD

**Issue by Srekel** [ziglang/zig#3638]
[minimal reproducer](https://github.com/ziglang/zig/issues/3638#issuecomment-557108013)

-----

I tried my hands at some fancy comptime type stuff, and happened upon an assert in the zig compiler:

> Assertion failed at D:\a\1\s\src\codegen.cpp:9156 in gen_root_source. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
The terminal process terminated with exit code: 3

Should be reproable using this commit:
https://github.com/Srekel/zag/commit/946f528e591071ac89dd9e854d43ee430b4d2d69

Tested with latest downloaded master binaries: zig-windows-x86_64-0.5.0+d18b5f8b5.zip. 

It's the `fillContext `function in transform_system.zig that triggers it.

Seems to be this assert that fails:

        Tld *builtin_tld = find_decl(g, &get_container_scope(std_import)->base,
                buf_create_from_str("builtin"));
        assert(builtin_tld != nullptr);

**Comment by Srekel** [comment]
Actually, um... 

I just tried removing stuff until I could get it to compile, and I can't anymore, even after clearing the cache. As in, even with a build.zig that only builds main.zig and a main.zig whose main function only does a warn call, I get the same error. 

The compile error happened with old binaries (a few weeks old?) so it doesn't seem to be anything recent, and yet it has definitely managed to build *fairly* recently...

**Comment by Srekel** [comment]
Ok, I'm not sure what happened. When I upgraded to the newest zig, I simply overwrote the folder containing zig.exe. I now first removed it, then unpacked the zip clean into a new folder, and now the compile error is what you'd expect (i.e. I can get rid of it by commenting out stuff :) ).

It now states:

> E:\Projects\zag>zig build
> Unreachable at D:\a\1\s\src\codegen.cpp:6586 in gen_const_val_ptr. This is a bug in the Zig compiler.
> 

And it disappears if I comment out the @field line from here:

                    builtin.TypeInfo.Pointer.Size.One => {
                        @field(context, fieldName) = @ptrCast(typ, (params.getValue(fieldName) orelse unreachable).pvoid);
                    },

**Comment by Srekel** [comment]
(Sorry for the ramblyness of the report!)

I've written a "minimal" repo, attaching it. 
[3638.txt](https://github.com/ziglang/zig/files/3870112/3638.txt)

With downloaded master build from yesterday (I believe), this is the output:

> E:\Projects\zigtesting>zig build-exe 3638.zig
> Unreachable at D:\a\1\s\src\codegen.cpp:6623 in gen_const_val_ptr. This is a bug in the Zig compiler.
> Unable to dump stack trace: debug info stripped


It seems to be because I'm ptrCasting a *void, which I have since figured out isn't the right way to do what I want anyway, so it's not a high prio bug in any way for me, but I guess it's nice to fix anyway.

**Comment by LemonBoy** [comment]
Here's a minimal reproducer:

```zig
pub const S = struct {
    pvoid: *void,
};
fn foo(x: S) void {
    var ptr = @ptrCast(*usize, x.pvoid);
}
pub fn main() void {
    var x: S = undefined;
    var context = foo(x);
}
```

`render_const_val_ptr` chokes on the constant value created by `ir_analyze_struct_field_ptr` because `type_has_one_possible_value` for `*void` returns `OnePossibleValueYes` and the resulting `ConstExprValue` is zero'ed out.

**Comment by andrewrk** [comment]
This now gives:

```
./test2.zig:5:15: error: '*void' and '*usize' do not have the same in-memory representation
    var ptr = @ptrCast(*usize, x.pvoid);
              ^
./test2.zig:5:33: note: '*void' has no in-memory bits
    var ptr = @ptrCast(*usize, x.pvoid);
                                ^
./test2.zig:5:24: note: '*usize' has in-memory bits
    var ptr = @ptrCast(*usize, x.pvoid);
                       ^
```
