### ISSUE TITLE
@couldCoerce - check if a type will coerce to another

### ISSUE THREAD

**Issue by travisstaloch** [ziglang/zig#3641]
Sometimes its safe to assign a variable to a similar type when the types don't exactly match.  Such is the case with []const u8 and [3]u8.  Checking if the types match fails, but it IS safe to assign a []const u8 variable to a value of type  [3]u8.  I would like to be able to test if [3]u8 can be coerced into a []const u8.

I ran into this issue [trying to instantiate a tagged union from a runtime known tag](https://gist.github.com/travisstaloch/a8def7b20eda3e3b2046781f08ddc5c9), I check the union field type against `val: var` on [line 82](https://gist.github.com/travisstaloch/a8def7b20eda3e3b2046781f08ddc5c9#file-tagged_union_test-zig-L82) of the linked gist.  It would have been safe to assign the value, but because the types don't match control flow proceeds into the 'else unreachable' branch.  

A @couldCoerce method would eliminate the need for possibly complex type comparisons necessary to determine wether it is safe to perform this assignment. 

```zig
//            if (unionField.field_type == @typeOf(val)) {
            if (@couldCoerce(unionField.field_type, @typeOf(val))) {
                return @unionInit(Tagged, unionField.name, val);
...
```

Here is a condensed version of the gist:
 
```zig
const std = @import("std");

const Tag = {A, B,  C };
const Tagged = union(Tag) {
    A: bool,
    B: i32,
    C: []const u8,
};

pub fn main() anyerror!void {
    var tagged = Tagged{ .A = true };
    var tag = @as(Tag, tagged);
    tag = .C;

    tagged = try initTagged3(tag, "foo");
}

fn initTagged3(tag: Tag, val: var) !Tagged {
    const uT = @typeInfo(Tagged).Union;
    inline for (uT.fields) |unionField| {
        if (@intToEnum(Tag, unionField.enum_field.?.value) == tag) {
            if (unionField.field_type == @typeOf(val)) {
            // **********************************
            // Proposed change
            // if (@couldCoerce(unionField.field_type, @typeOf(val))) {
            // **********************************
                return @unionInit(Tagged, unionField.name, val);
            } else {
                unreachable;
            }
        }
    }
    return error.Invalid;
}
```

**Comment by billzez** [comment]
I would also find this useful. Can this be reopened?

**Comment by maxzhao** [comment]
please reopen, it's very useful for some case
