### ISSUE TITLE
Proposal: Add Iterator to SinglyLinkedList and TailQueue

### ISSUE THREAD

**Issue by joachimschmidt557** [ziglang/zig#3643]
`ArrayList`s have a convenient `Iterator` struct which iterates through an `ArrayList` and is resettable. Would it make sense to add such iterators to `SinglyLinkedList` and `TailQueue`?

If yes, I'd be happy to create the necessary code and tests.

**Comment by daurnimator** [comment]
`Node` can already be suitable as an iterator structure, would just need a `next()` method. I think this will also require renaming the current `next` field.

**Comment by joachimschmidt557** [comment]
Seeing the `Iterator` struct removed from `ArrayList`, a similar struct for `SinglyLinkedList` and `TailQueue` wouldn't make much sense. Iterating over such structures won't be more comfortable with `Iterators` I think:

With iterators:

```zig
var iter = list.iterator();
while (iter.next()) |itm| ...
```

Whereas without iterators:

```zig
var x = list.first;
while (x != null) : (x = x.next) ...
```

I don't have any interest anymore in this proposal and would therefore close it. If there is renewed interest, this issue can be reopened.
