### ISSUE TITLE
Bug: packed struct with array has invalid size

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#3651]
The following code produces the wrong sizes for arrays:
```zig
const T1 = packed struct {
    array: [3][3]u8, // also with align(1)
};

const T2 = packed struct {
    array: [9]u8,
};

comptime {
    @compileLog(@sizeOf(T1)); // => | 16
    @compileLog(@sizeOf(T2)); // => | 16
    @compileLog(@sizeOf([9]u8)); // => | 9
}
```

Tested with 0.5.0+891e2149b
Probably related: #2627

**Comment by ostylk** [comment]
I happened to stumble across a similar issue: Arrays inside of a packed struct don't seem to correctly fill the struct (zig version: 0.7.1).
```zig
const std = @import("std");

const Test = packed struct {
    sel: u8,
    pad: [15]u8,
    data: u32,
};

pub fn main() void {
    const data = Test { .sel = 8, .pad = [1]u8{1}**15, .data = 10 };
    std.debug.print("0x{x}, 0x{x}, 0x{x}, 0x{x}\n", .{ @ptrToInt(&data.sel), @ptrToInt(&data.pad), @ptrToInt(&data.data) });
}
```

This produced the following output:
```
0x202730, 0x202731, 0x202731
```
The `data` and `pad` members seem to be at the same memory address, even though they really shouldn't be.

Any ideas?

**Comment by Vexu** [comment]
Arrays are no longer allowed in packed structs.
