### ISSUE TITLE
Getting "invalid token: 'pub'" when importing tcl.h

### ISSUE THREAD

**Issue by FrankRuben** [ziglang/zig#3657]
Hi,

trying to import [tcl.h](https://github.com/tcltk/tcl/blob/d28c1ce4bbc57048c287e1ad62d56a43640da285/generic/tcl.h#L1900), I'm getting an error "error: invalid token: 'pub'" for the line referenced by the URL. When I'm commenting out the offending line, I'm getting a different error for a different line, saying "invalid token: 'pub' ... pub const __BIGGEST_ALIGNMENT__ = 16;",

I'm using zig version "0.5.0+98e37537d" from the binary release for Linux "zig-linux-x86_64-0.5.0+98e37537d".

My build.zig file is the one generated by `zig init-exe`.

Any pointers?

Thanks, Frank

**Comment by daurnimator** [comment]
Seems to be fixed in master.
```zig
const std = @import("std");

pub const tcl = @cImport({
    @cInclude("tcl.h");
});

pub fn main() void {
    std.debug.warn("{}\n", .{tcl.TCL_ENCODING_STOPONERROR});
}
```
```
$ zig run 3657.zig -I/usr/include
4
```
