### ISSUE TITLE
Executable is very big in Linux

### ISSUE THREAD

**Issue by tuket** [ziglang/zig#3660]
Looks like the executables Zig generates are quite large compared to C or C++.
Sorry if this has been already reported.

**Zig**
```
const std = @import("std");

pub fn main() !void {
    const out = try std.io.getStdOut();
    try out.write("hello\n");
}
```

```
zig build-exe --release-small hello.zig
du hello
416
```

**C**
```
#include <stdio.h>

int main()
{
    puts("hello");
}
```
```
clang++ hello.c -o hello
du hello
8
```

**C++**

```
#include <iostream>

using namespace std;

int main()
{
    cout << "hello" << endl;
}
```

```
g++ hello.cpp -o hello
du hello
12
```

**Comment by andrewrk** [comment]
try using the `ldd` tool on these binaries. If you want to compare these numbers you will need to also count the size of the shared libraries that are being linked.

**Comment by andrewrk** [comment]
Also your C and C++ binaries are not including debug info. To match this you will need to pass `--strip` to `zig build-exe`.

**Comment by tuket** [comment]
`--strip` did the job:

```
zig build-exe --release-small --strip hello.zig
du hello
12
```

I though it would be enough with `--release-small` but apparently it wasn't.
Thanks for your help!

**Comment by andrewrk** [comment]
you are still not understanding the situation if you did not inspect the output of all 3 binaries with `ldd`

**Comment by tuket** [comment]
For the zig executable it does not work:
```
ldd hello
	not a dynamic executable
```

For the C++ executable it does print stuff:
```
ldd hello
	linux-vdso.so.1 (0x00007ffc1b1f2000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8a1925b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8a18ebd000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8a18ca5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8a188b4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8a195e4000)
```

**Comment by andrewrk** [comment]
It does work :-)

your zig program is entirely self-contained; it does not depend on any external files.

If you want to know how many bytes your c++ program really is then you need to add together all the bytes of all these files:
 * /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 * /lib/x86_64-linux-gnu/libm.so.6
 * /lib/x86_64-linux-gnu/libgcc_s.so.1
 * /lib/x86_64-linux-gnu/libc.so.6
 * /lib64/ld-linux-x86-64.so.2

**Comment by tuket** [comment]
That's pretty cool :)

**Comment by GreenBeard** [comment]
@andrewrk I looked through the Github Issues, and I may have missed it, but I am curious to know if the Zig std can be dynamically linked. I believe that if one has dozens to hundreds of executables (as is common for a computer) it really is a far comparison to say that C is smaller than Zig if C can currently dynamically link it standard library, and Zig cannot.

**Comment by mgord9518** [comment]
@tuket I've been messing with it and a basic Zig hello world is just over 8k when compiled with `-Doptimize=ReleaseSmall`, so this must've been improved
