### ISSUE TITLE
Can't pass anonymous list literal as slice

### ISSUE THREAD

**Issue by dbandstra** [ziglang/zig#3678]
```zig
fn func(slice: []const u8) void {}
pub fn main() void {
    // works
    func([_]u8{1, 2, 3});

    // doesn't work
    func(.{1, 2, 3});
}
```

Output:
```
Semantic Analysis [671/691] /home/dbandstra/oxid/asdf.zig:7:9: error: expected array type or [_], found slice
    func(.{1, 2, 3});
        ^
/home/dbandstra/oxid/asdf.zig:7:12: note: referenced here
    func(.{1, 2, 3});
           ^
```

**Comment by dbandstra** [comment]
The error message is pretty bizarre too. It says "expected array, found slice" but actually I gave it an array where it wanted a slice.

And the second error, "referenced here" doesn't seem to make sense either, pointing to the inside of the literal?

**Comment by SpexGuy** [comment]
I think this can be considered fixed now.  Neither of the examples from the original issue work anymore, but both of these do:
```zig
func(&[_]u8{1, 2, 3});
func(&.{1, 2, 3});
```
