### ISSUE TITLE
Import a build.zig file as a build step

### ISSUE THREAD

**Issue by AndreaOrru** [ziglang/zig#368]
Kinda like this:
https://github.com/zig-lang/zig/blob/master/test/build_examples.zig

But included in the standard build system.

**Comment by andrewrk** [comment]
Why does it need to be a separate build file? In the example you linked, we're testing the zig build system itself which is the reason for running zig build in a subprocess.

In your case, can you not import the file and pass it the Builder reference?

**Comment by andrewrk** [comment]
Related: #353

**Comment by AndreaOrru** [comment]
Yeah it should work. It wouldn't be a step included in the dependency graph though, would it?

**Comment by AndreaOrru** [comment]
Related issue: if two executables are part of the same build, and you call `.setBuildMode(b.standardReleaseOptions())` on both, you get a `Option 'release-safe' declared twice`.

**Comment by andrewrk** [comment]
The `standardReleaseOptions` issue is resolved.
