### ISSUE TITLE
zig fmt can remove comments

### ISSUE THREAD

**Issue by Srekel** [ziglang/zig#3686]
Minimal repro case: Open a new file, fmttest.zig for example, add the following two lines of code:
```
/// test
// test
```

Format it using zig fmt. Afterwards, there's only a single blank line left. 
```

```
Tested on Windows using zig-windows-x86_64-0.5.0+d18b5f8b5.zip

**Comment by Vexu** [comment]
I have this solved for both variations of top-level doc comments I presented [here](https://github.com/ziglang/zig/issues/2288#issuecomment-541308774). Alternatively adding a compile error for unattached doc comment would be quite easy if we don't want top-level doc comments.
