### ISSUE TITLE
Bug: Anonymous enums can't be used with return type `type`

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#3707]
Okay, this is a weird one. Somehow zig messes up enum literals when the type is declared local as a function parameter instead of "standalone" type. This also only happens when the return type is `type`, other types seem to work well (`i32`, `void`, `[]const u8`):

```zig
const RetType = type; // replace with "void" and it compiles

pub fn foo(a: enum{a,b}) RetType { unreachable; }

pub fn main() void {
    foo(.a);
}
```

```
/tmp/fail.zig:7:9: error: expected type 'enum:4:15', found 'enum:4:15'
    foo(.a);
        ^
/tmp/fail.zig:4:15: note: enum:4:15 declared here
pub fn foo(a: enum{a,b}) RetType { unreachable; }
              ^
/tmp/fail.zig:4:15: note: enum:4:15 declared here
pub fn foo(a: enum{a,b}) RetType { unreachable; }
              ^
/tmp/fail.zig:7:8: note: referenced here
    foo(.a);
```

Zig Version: 0.5.0+a11da3773

**Comment by mikdusan** [comment]
>This also only happens when the return type is type

It seems `comptime` is the confounder:

```zig
fn foo(comptime a: enum{a,b}) void { unreachable; }

pub fn main() void {
    foo(.a);
}
```

**Comment by MasterQ32** [comment]
This bug still persists, but i could narrow it down a bit:
```zig
// making the parameter comptime enforces the error,
// making it runtime removes it.
pub fn foo(comptime a: enum{a,b}) void { unreachable; }

pub fn main() void {
    foo(.a);
}
```

Looks like the bug is somewhere in the comptime resolution of enum literals to enum type

**Comment by andrewrk** [comment]
I believe the solution to this is going to be auditing how the comptime evaluation of parameter types are cached. This is related to #846. I want anonymous enums to also work in generic functions, after a comptime parameter. So this will require examining what "dependencies" from comptime parameters are used, and using only those as the cache key. That makes #846 a prerequisite to solving this bug. It also means that `@typeInfo` on generic function parameters and return type will get more useful.

**Comment by Rocknest** [comment]
```zig
export fn entry() void {
    repro(.a, 1);
}

fn repro(msg: enum {a, b}, comptime here_a_bug: u8) void {
    switch (msg) {
        .a => {},
        .b => {},
    }
}
```

**Comment by dmitry-ant** [comment]
is there any reasonable expectancy to fix this? i am really close to talking my team into switching to zig from cpp, but i am stuck on this problem.  i ported almost all of our game engine to zig, but i cannot overcome this.

author of #9704 here

i am really sorry to bother core maintainers,  but i stand against four coders with collective experience of 95 years, and they won't even consider working with a new language before everything that they done is ported.

**Comment by Vexu** [comment]
This will work with in the self-hosted compiler which is expected to ship with 0.9.0. In the meanwhile you should be able to workaround this by putting the enum in a separate declaration instead of having it as the parameter type.

**Comment by dmitry-ant** [comment]
> This will work with in the self-hosted compiler which is expected to ship with 0.9.0. In the meanwhile you should be able to workaround this by putting the enum in a separate declaration instead of having it as the parameter type.

thank you very much for a reply, i will hope that that will be enough to talk my superiors into zig. I cannot say this enough, thank you very much.

**Comment by Vexu** [comment]
This worked earlier already but 2cfa7165e715321dffea21380d4fde0dd5079925 added a similar enough test.
