### ISSUE TITLE
pub const io_mode = .evented; does not compile when targeting windows

### ISSUE THREAD

**Issue by qbradley** [ziglang/zig#3717]
Example program:

```zig
const std = @import("std");
// comment out this line to successfully compile
pub const io_mode = std.io.Mode.evented;
pub fn main() void {
  std.debug.warn("Hello\n");
}
```

Example error when running `zig.exe build-exe events.zig`

```
broken LLVM module found: Instruction does not dominate all uses!
  %743 = load %std.pdb.MsfStream**, %std.pdb.MsfStream*** %92, align 8, !dbg !7527
  %501 = load %std.pdb.MsfStream*, %std.pdb.MsfStream** %743, align 8, !dbg !7549
Instruction does not dominate all uses!
  %743 = load %std.pdb.MsfStream**, %std.pdb.MsfStream*** %92, align 8, !dbg !7527
  %512 = load %std.pdb.MsfStream*, %std.pdb.MsfStream** %743, align 8, !dbg !7555
```

daurnimator indicates this is likely because OutputStream is not yet implemented as async and is required for windows format output

**Comment by daurnimator** [comment]
> daurnimator indicates this is likely because OutputStream is not yet implemented as async and is required for windows format output

That's why it doesn't work (I think).
However you've still stumbled across a compiler bug, which needs to be fixed in either way.

**Comment by andrewrk** [comment]
Async I/O is still a work in progress and still does not have test coverage on the CI, but this does now work.
