### ISSUE TITLE
"error: FileNotFound, reached unreachable code" during libuserland install on NetBSD

### ISSUE THREAD

**Issue by niacat** [ziglang/zig#3719]
This error appeared after going from 0.4.0 to 0.5.0.

~~~
===> Building for zig-0.5.0
[  1%] Built target embedded_lld_mingw
[ 47%] Built target embedded_softfloat
[ 52%] Built target embedded_lld_coff
[ 67%] Built target embedded_lld_lib
[ 70%] Built target zig_cpp
[ 71%] Built target opt_c_util
[ 85%] Built target embedded_lld_elf
[ 89%] Built target embedded_lld_wasm
[ 98%] Built target compiler
[ 99%] Built target zig0
error: FileNotFound
reached unreachable code

Build failed. The following command failed:
/home/nia/pkgsrc/lang/zig/work/zig-0.5.0/zig-cache/o/uLxjb-N9dhEqZjvaL6ElR8ig3kA4abaAjmfxB1KtMdUBdd9YwlsYtDxsyo5b_q8R/build /home/nia/pkgsrc/lang/zig/work/zig-0.5.0/zig0 /home/nia/pkgsrc/lang/zig/work/zig-0.5.0 /home/nia/pkgsrc/lang/zig/work/zig-0.5.0/zig-cache --override-lib-dir /home/nia/pkgsrc/lang/zig/work/zig-0.5.0/lib libuserland install -Doutput-dir=/home/nia/pkgsrc/lang/zig/work/zig-0.5.0 -Drelease=true -Dlib-files-only --prefix /usr/pkg
--- CMakeFiles/zig_build_libuserland ---
*** [CMakeFiles/zig_build_libuserland] Error code 255
~~~

All of the paths referenced in the command seem to exist.

@coypoop, can you help? :)

**Comment by coypoop** [comment]
There's a couple of failures I am still investigating.
the most apparent one is the "reached unreachable code".
This happens while trying to print a backtrace.

We open the self executable, fstat it (using compat fstat()), and get a bogus size.
this bogus size is fed to mmap, which returns EOVERFLOW.
[Zig doesn't think this codepath should be reachable.](https://github.com/ziglang/zig/blob/master/lib/std/os.zig#L2241)

**Comment by LemonBoy** [comment]
> and get a bogus size.

That happens when the `stat` structure definition is wrong, double-check the NetBSD one.
