### ISSUE TITLE
Documentation generation creates bullet point when dots are in line

### ISSUE THREAD

**Issue by Srekel** [ziglang/zig#3722]
See generated documentation here:

https://github.com/Srekel/zig-sparse-set/docs/index.html

sparse_set.zig looks like this:

```
//! Sparse Set
//!
//! Version 1.0.2
//!
//! See https://github.com/Srekel/zig-sparse-set for latest version and documentation.
//!
//! See unit tests for usage examples.
//!
//! Dual license: Unlicense / MIT
```
Output looks like this:
![image](https://user-images.githubusercontent.com/1578924/69184982-1c49b500-0b16-11ea-9e7b-323fc7431e7e.png)

**Note:** The documentation can be generated simply by running `zig build`.

**Comment by MasterQ32** [comment]
I hope i can find some time to look at the code why it does that.

`.` should not generate bullet points... :man_facepalming:

**Comment by Rocknest** [comment]
Can you test if this change fixes it? 

https://github.com/ziglang/zig/pull/3517/files#diff-e4bbc76e0f878f96c3076ba4c7042c72R1401
