### ISSUE TITLE
NoTailCall option

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#3732]
_Originally from https://github.com/ziglang/zig/pull/2598_

I just recalled something from https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66826
> Now dlsym (and other dl-functions) secretly take shadow parameter - return address on stack

We need a way to ensure that a given call is not a tail call.

[LLVM does have a `notail` option](https://llvm.org/docs/LangRef.html#call-instruction)

**Comment by daurnimator** [comment]
To avoid proliferation of `@inlineCall`/`@noInlineCall`/`@noTailCall`, etc.
I propose a `@call` builtin that takes a structure of options:
```zig
const Maybe = enum {
    Always,
    Default,
    Never,
};
@call(struct {
    tailCall: Maybe = .Default,
    inline: Maybe = .Default,
}, args: ...);
```

**Comment by emekoi** [comment]
perhaps `asyncCall` could be merged with this?

**Comment by dbandstra** [comment]
Your code example is missing the handle to the function itself, and if we are getting rid of var args (#208) then the `args` argument should be a `var` which is filled using anonymous literal syntax. That would end up looking like this:

```zig
const result = @call(myFunc, .{ .tailCall = false }, .{ false, 1, "three" });
```

**Comment by fengb** [comment]
How about just 1 argument?

```zig
 @call(.{
    .tailCall = false,
    .func = myFunc,
    .args = .{ false, 1, "three" })
});
```

**Comment by daurnimator** [comment]
> How about just 1 argument?

I think this looks harder to use. Also the call type needs to be comptime known, while the function and arguments can be runtime known.

**Comment by daurnimator** [comment]
> Your code example is missing the handle to the function itself, 

Fixed.

> and if we are getting rid of var args (#208) then the `args` argument should be a `var` which is filled using anonymous literal syntax. That would end up looking like this:
> 
> ```zig
> const result = @call(myFunc, .{ .tailCall = false }, .{ false, 1, "three" });
> ```

Builtins don't need to follow the rest of the language like this: they aren't normal functions. see e.g. `@field`
