### ISSUE TITLE
Trying to Port c code to Zig https://github.com/ggreer/the_silver_searcher

### ISSUE THREAD

**Issue by alialrahahleh** [ziglang/zig#3738]
Hi, 

I'm trying to backport ag code to Zig. is there anything I should look at first like a document to port C code?

**Comment by marler8997** [comment]
https://tiehu.is/blog/zig1

**Comment by andrewrk** [comment]
Welcome, @alialrahahleh!

This wiki page has links to the places where Zig community members hang out and help each other with questions like this:

https://github.com/ziglang/zig/wiki/Community
