### ISSUE TITLE
Dir.cwd doesn't support iteration

### ISSUE THREAD

**Issue by gereeter** [ziglang/zig#3741]
Calling `std.fs.Dir.cwd().iterate().next()` fails with `EBADF` on Linux: `getdents` and `getdents64` don't support `AT_FDCWD` (and can't, since they store iteration state in the file descriptor). I'm not certain of the behavior on BSDs and Windows, but I believe that the same problem shows up. Note that iterating over `Dir.open(".")` works fine.

I'd be happy to fix this, but I'm not certain of the correct approach. I see three possible answers:
- Normalize and document this behavior. This would make a distinction between files opened for reading (which can be iterated over) and files opened purely for sub-file operations (i.e. with `O_PATH` or `AT_FDCWD`). This would presumably also involve splitting `openDir` into two functions for opening in the two different ways, and possibly a `reopenForReading` function that is a shorthand for `self.openDirRead(".")`.
- Detect `Dir.cwd()` in `iterate` and replace the file descriptor with a newly opened handle to `.`. This would make `iterate` fallible where it currently isn't.
- Detect `Dir.cwd()` in `next` and replace the file descriptor with a newly opened handle to `.`. This would add at least `ProcessFdQuotaExceeded` and `SystemFdQuotaExceeded` and probably `SystemResources` to the `Iterator.Error` set.

The latter two answers still don't make `Dir.cwd()` act like `Dir.open(".")` with respect to iteration, but this is also an inconsistency between systems. On Linux, since the iteration state is stored by the operating system in the directory file descriptor, calling `iterate` multiple times won't actually produce distinct new iterators, but rather iterators that are both grabbing entries off of the same list and interfering with each other. On the BSDs, the iteration state is an offset stored user-side, and so different iterators will actually be independent. On Windows, I think you get BSD-style behavior if the iterations are done one after the other (due to the `RestartScan` argument), but an even messier version of the Linux behavior if the iterators are used concurrently. The special-casing of `Dir.cwd()` would produce BSD-like behavior just for that one special case, even on Linux.

I personally would favor the first approach, if for no other reason than liking exposing the `O_PATH` optimization.

**Comment by andrewrk** [comment]
Thanks for the write-up. I agree with you on the first approach.
