### ISSUE TITLE
translate-c fails silently when source code initializes a struct to zero

### ISSUE THREAD

**Issue by kavika13** [ziglang/zig#3752]
If you have a C function that initializes a struct instance to `{ 0 }` and run `translate-c` on it, then zig skips codegen for that function, and doesn't output any error messages.

This was confusing to me because the function didn't output at all. I only figured it out when I did a "binary chop" on the input file to figure out which particular line was keeping the function from being output.

Ideally this would just work, but if it fails to work it would be nice if a good error message was output.

**Repro steps:**
1. Create a C example file and save it as `main.c`:
```
typedef struct {
    int abc;
} SomeStruct;

int main() {
    SomeStruct blah;
    return 0;
}
```
2. `zig translate-c main.c > main.zig`
3. Change the line `SomeStruct blah;` to `SomeStruct blah = { 0 };` inside `main.c` and save it
4. `zig translate-c main.c > main.zig`

**Expected:**
The implementation of `fn main()` exists in `main.zig` after both step 2 and step 4
**or**
An error message is displayed after step 4 that says translate-c cannot cope

**Actual:**
The implementation of `fn main()` exists in `main.zig` after step 2, but disappears after step 4. No error message is displayed.

**Comment by andrewrk** [comment]
Are you aware of the `--verbose-cimport` flag? This will probably shed some light.

One of the improvements that the self-hosted translate-c implementation (#1964) does is make these comments rather than usually hidden warnings.

**Comment by kavika13** [comment]
From `--verbose-cimport`, seems this is semi-intentional since the work to emit this code just isn't done yet, and there's no compiler-side work around in place:
```
main.c:6:23: warning: TODO handle C InitListExprClass
main.c:5:5: warning: unable to translate function
```

It does raise the question: should "warnings" be hidden if you don't specify verbose?
