### ISSUE TITLE
eradicate C pointers from src-self-hosted/clang.zig

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#3765]
This file is manually maintained; no reason to use C pointer types. Once #2984 is implemented, clang.zig will be full of compile errors unless this issue is solved.

**Comment by kavika13** [comment]
I was looking though this to see if I could actually tackle this, and noticed a few gotchas.

I saw that at least one of the wrapper functions was ignoring the error results from Clang, and had some other odd things about the signature.

In https://github.com/ziglang/zig/blob/master/src-self-hosted/clang.zig#L714:
```
pub extern fn ZigClangSourceManager_getCharacterData(self: ?*const struct_ZigClangSourceManager, SL: struct_ZigClangSourceLocation) [*c]const u8;
```

In https://github.com/ziglang/zig/blob/master/src/zig_clang.cpp#L1496:
```
const char* ZigClangSourceManager_getCharacterData(const ZigClangSourceManager *self,
        ZigClangSourceLocation SL)
{
    return reinterpret_cast<const clang::SourceManager *>(self)->getCharacterData(bitcast(SL));
}
```

In the Clang API docs [SourceManager::getCharacterData](https://clang.llvm.org/doxygen/classclang_1_1SourceManager.html#a88ecde393b8281f7c0be5afdd0213624):
(didn't try to match versions, so maybe the signature changed?)
```
const char* SourceManager::getCharacterData(
    SourceLocation SL,
    bool* Invalid = nullptr
) const
```

1. It seems the impl of zig_clang.cpp blindly casts and de-references `self`. Wouldn't having `self` be a nullable pointer type in clang.zig be unsafe?

2. The Clang docs mention a `bool* Invalid` parameter for this function, but zig_clang.cpp doesn't do any error checking on it, and also seems to swallow any potential errors there. I'm not sure exactly what this does to the return value. It's possible that Zig's usage of the API might ensure there's no errors? If so, maybe some comments are in order in zig_clang.cpp?

**Comment by andrewrk** [comment]
Some of these have been auto-translated from C - for example fwd decls of structs are translated as `@OpaqueType()` and pointers to them are translated as `?*T` (which you can see in your example as `?*const struct_ZigClangSourceManager`). In reality this pointer is not optional; the `?` should be removed in clang.zig.

Exposing the `Invalid` parameter would be welcome, if you write the code at the callsite to deal with it. Currently the C API exposed for this does not allow providing a non-default (`nullptr`) value for that parameter.

BTW the return type can take advantage of the newly merged [sentinel-terminated pointers](https://ziglang.org/documentation/master/#Sentinel-Terminated-Pointers).
