### ISSUE TITLE
Additional backend to generate C code

### ISSUE THREAD

**Issue by uael** [ziglang/zig#3772]
I would like to known the position of the zig team on a C backend in addition to LLVM.

I known that not a lot of people will need such a backend, it's a very specific need which mostly target embedded system using custom architecture and C compiler. It's still the only missing step to stuck out from C, which would be very cool 👍

Thank you and keep the good work

**Comment by andrewrk** [comment]
I see it as one of many desirable targets. It's not provided by LLVM so this would be something provided by an alternate backend.

**Comment by uael** [comment]
There is one by the Julia team (resurrected llvm C backend) but not very usable on a work basis, and it's tied to llvm, which I don't see as a good solution. 
Since it's desirable I will start thinking about it, I'm open to any advice for where to start.

**Comment by andrewrk** [comment]
I don't think this project is startable yet; there are too many unfinished prerequisites.

 * self-hosted compiler (#89)
 * support for alternative backends besides LLVM in the self-hosted compiler

**Comment by uael** [comment]
Ok I will be patient then, thank you for enlightenment and quick answers :ok_hand:

**Comment by andrewchambers** [comment]
the closer the output is to human readable C, the better. For me it's like an insurance policy for the bus factor problem.

**Comment by uael** [comment]
Duplicate of #5107, closing

**Comment by andrewrk** [comment]
Thanks - I had forgotten about this one. Let's keep the earlier one.

**Comment by andrewrk** [comment]
One note here is that once we are shipping self-hosted as the main zig compiler, we can remove LLVM from the bootstrapping process by having the stage1 zig compiler emit C code rather than LLVM IR. That is a separate issue however, since this issue is for self-hosted.

**Comment by andrewrk** [comment]
This is now part of stage2, and further improvements can be their own issues.

**Comment by g-berthiaume** [comment]
> I known that not a lot of people will need such a backend, it's a very specific need which mostly target embedded system using custom architecture and C compiler. 

Thanks for thinking about embedded systems. 
Compiling to clean and safe C code would allow Zig to enter the bare-metal firmware ecosystem.
