### ISSUE TITLE
Container in comptime known false branch is evaluated.

### ISSUE THREAD

**Issue by Vexu** [ziglang/zig#3778]
```zig
pub fn panic(msg: []const u8, st: ?*@import("builtin").StackTrace) noreturn {
    while (true) {}
}

const comptime_const = 2;
pub fn some(comptime V: type) type {
    return struct {
        const OsData = switch (comptime_const) {
            4 => Donteval, // works
            3 => struct { // error: container 'OsData' has no member called 'Put'
                put: Put,

                const Put = struct {
                    putter_frame: @Frame(kqPutEvents),
                };
            },
            

            2 => struct {},

            else => unreachable,
        };

        const Donteval = struct {
            put: Put,

            const Put = struct {
                putter_frame: @Frame(kqPutEvents),
            };
        };

        fn kqPutEvents(put: *OsData.Put) void {}

        fn init(os: OsData) void {}
    };
}

pub export fn entry() void {
    const b = some(usize);
    b.init(.{});
}
```
Example taken from `std.event.fs.Watch`.

**Comment by nektro** [comment]
i get `error: container 'OsData' has no member called 'Put'`

how does this diverge from the behavior you expected?

**Comment by frmdstryr** [comment]
Bump...

**Comment by Vexu** [comment]
This is fixed in stage2.

**Comment by frmdstryr** [comment]
I've been digging around with gdb and it appears that [`semantic_analyze`](https://github.com/ziglang/zig/blob/master/src/stage1/analyze.cpp#L5313) just attempts to resolve every switch branch here as if they are all top level decls. 

It takes the same branch a in [resolve_decl_container](https://github.com/ziglang/zig/blob/master/src/stage1/analyze.cpp#L4435). I guess the actual switching is handled in a separate pass so it might make sense to do a lazy resolve of the enum fields if possible?
