### ISSUE TITLE
Strings from builtin functions should be null terminated if needed

### ISSUE THREAD

**Issue by Vexu** [ziglang/zig#3779]
`@embedFile`, `@errorName`, `@memberName`, `@tagName` and `@typeName` should be able to return null terminated slices so this would work:
```zig
const name: [*:0]u8 = @tagName(E.SomeEnum);
```

**Comment by andrewrk** [comment]
They should also be updated to return pointers to arrays rather than slices when the length is comptime known. It goes along with the same ideas behind #863.

**Comment by jmc-88** [comment]
For the record, `@memberName` was removed in https://github.com/ziglang/zig/commit/45da72c5b64069b7d5238465130a50f96678a148 and https://github.com/ziglang/zig/commit/3458fb891d8c7072a9bff6a32db9f3105ab72aa4, though there's still a reference to it in a commented out code block: https://github.com/ziglang/zig/blob/85755c51d529e7d9b406c6bdf69ce0a0f33f3353/lib/std/event/channel.zig#L142

**Comment by jmc-88** [comment]
Now that https://github.com/ziglang/zig/pull/9183 too has been merged, I think the only outstanding builtin would be `@typeInfo()`, which has been forked to https://github.com/ziglang/zig/issues/9182. Maybe this can be closed?
