### ISSUE TITLE
Nested list

### ISSUE THREAD

**Issue by FemtoEmacs** [ziglang/zig#3782]
I could not find an example of nested list, as in Lisp. Since zig has a sintax that is very different from C, I believe that examples of recursive processing of nested list are necessary. To make clear what I am talking about, I will provide an example in C. Basically, one needs to define s-expressions, cons, CAR and CDR. Here is my definition:

/* ============== */
//File: sexpr.h

#include<stdlib.h>
#include<stdio.h>

#define INTOBJ 11
#define STROBJ  13
#define LISTOBJ 16
#define CELLinum xpr.inum
#define CELLstr  xpr.str
#define ISint(p) ((p)->flag == INTOBJ)
#define ISstr(p) ((p)->flag == STROBJ)
#define ISlist(p) ((p)->flag == LISTOBJ)
#define CAR(p)    ((p)->xpr.pair.car)
#define CDR(p)    ((p)->xpr.pair.cdr)

typedef struct cell {
        int flag;
        union {
            int inum;
            char *str;
            struct {
                   struct cell *car;
                   struct cell *cdr;
         } pair;
     } xpr;
} *sexpr;

sexpr freshcell () {
    sexpr obj;
    obj = (sexpr) malloc(sizeof(struct cell));
    return obj;}
/* ================= */

/* ================ */
// cons.h
#include <string.h>

sexpr mkinum(int inum) {
    sexpr obj=  freshcell();
    obj->flag= INTOBJ;
    obj->CELLinum = inum;
    return(obj);}

sexpr mkstr(char *str) {
       sexpr obj= freshcell();
       char *newstr;
       int len= strlen(str);
       newstr= malloc(len+1);
       strcpy(newstr, str);
       *(newstr+len) = 0;
       obj->flag= STROBJ;
       obj->CELLstr= newstr;
       return obj;}

sexpr cons(sexpr head, sexpr tail) {
     sexpr obj= freshcell();
     obj->flag = LISTOBJ;
     CAR(obj) = head;
     CDR(obj) = tail;
     return obj;}
/* ================ */

/* =============== */
#include "sexpr.h"
#include "cons.h"

void prt(sexpr s) {
  if (ISint(s)) printf(" %d ", s->CELLinum);
  if (ISstr(s)) printf(" %s ", s->CELLstr);
  if (ISlist(s)) { printf("(");
  while (s != NULL) { prt(CAR(s)); s = CDR(s);}
  printf(")");}}

int main() { sexpr xs;
  int i;
  xs= cons(mkinum(33), NULL);
  xs= cons(mkinum(42), xs);
  xs= cons(mkstr("Rosa"), xs);
  xs= cons(cons( mkstr("Rosam"),
                 cons(mkstr("Rosae"), NULL)), xs);
  prt(xs);  printf("\n");}
/* =============== */

Here is how to compile and run this program:

~/sexpr/sexpr› gcc linkedList.c -o linkedList.x

~/sexpr/sexpr› ./linkedList.x
(( Rosam  Rosae ) Rosa  42  33 )

**Comment by andrewrk** [comment]
Welcome, @FemtoEmacs!

This wiki page has links to the places where Zig community members hang out and help each other with questions like this:

https://github.com/ziglang/zig/wiki/Community
