### ISSUE TITLE
no binaries for windows

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [ziglang/zig#3791]
i was recommended to test your language... but you have no binaries for windows... can you please fix that?

what kind of retarded language have binaries but none for windows... just for other junk 64bit oses

**Comment by daurnimator** [comment]
https://ziglang.org/download/  you'll see 

> zig-windows-x86_64-0.5.0+0f2a9af4a.zip | Binary | 43.6MiB | 93464616a7c6c4498c51b7037b10d678a839064748d422860f08d94aab3b0fc9

**Comment by andrewrk** [comment]
1. you are incorrect, there are windows binaries on the download page

2. you are banned
