### ISSUE TITLE
Proposal: Anonymous struct/list argument unpacking

### ISSUE THREAD

**Issue by SrMordred** [ziglang/zig#3805]
Following the recent anonymous struct/list stuff, just unpacking of arguments, like what u have with tuples in most compile time languages:

```
fn myfun(a : i32, b : i32, c : i32 ) void {}

myfunc( .{ 1 ,2 ,3}.unpack ); //or
myfunc( @unpack( .{ 1 ,2 ,3} ) ); // looks more like zig
myfunc( .{ 1, 2, 3 } );  // more convenient.

```
Maybe it can be extended to support variable unpacking also:

```
const a,b,c = .{ 1, "test", 10.5 }; // or
const a,b,c = @unpack(  .{ 1, "test", 10.5 } ); 
```

**Comment by andrewrk** [comment]
Please see #498 and then add a comment if you wish to re-open.
