### ISSUE TITLE
Compiler bug: Unreachable at /build/zig/src/zig-0.5.0/src/analyze.cpp:4842 in handle_is_ptr

### ISSUE THREAD

**Issue by Leguu** [ziglang/zig#3826]
I don't think this is very much of an issue, but the Zig compiler crashes when it detects this (wrong) code, instead of producing a proper error output:

```zig
// main.zig
pub fn main() anyerror!void {
    const zig_err = Point.new(0, 0);
}

const Point = struct {
    x_pos: i32,
    y_pos: i32,

    fn new(x: i32, y: i32) Point {
        // Mangled syntax causes crash
        return struct {
            x_pos: x,
            y_pos: y,
        };
    }
};
```

Running `zig build-exe main.zig` produces this output:
```
Unreachable at /build/zig/src/zig-0.5.0/src/analyze.cpp:4842 in handle_is_ptr. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
[1]    7261 abort (core dumped)  zig build-exe main.zig
```

Of course, the code doesn't make sense; `Point.new` returns a struct with mangled syntax, the proper format is this:

```zig
return Point {
    x_pos = x,
    y_pos = y,
};
```

I'm guessing the compiler should provide an actual error message than just crashing.

**Comment by daurnimator** [comment]
The syntax is not wrong, you're just returning a `type` where a `Point` is expected. Still a stage1 bug though.

**Comment by Leguu** [comment]
Looks like this bug has been fixed in the latest version of Zig.
