### ISSUE TITLE
Compiler Bug: Assertion failed at /Users/runner/runners/2.160.1/work/1/s/src/ir.cpp:11634 in ir_resolve_const_type

### ISSUE THREAD

**Issue by DanB91** [ziglang/zig#3833]
This bug seems to not have been reported, so reporting now. When I attempt to compile the following code:

```
    var type_n = @typeOf(n);
    var var_n = if (type_n == comptime_int) @as(Log2Int(type_n), n) else n;
```
I get this error:
```
Assertion failed at /Users/runner/runners/2.160.1/work/1/s/src/ir.cpp:11634 in ir_resolve_const_type. This is a bug in the Zig compiler.
```

I am using Zig version: `0.5.0+0f2a9af4a` on macOS Catalina.  Please let me know if you need anything else from me.

**Comment by nektro** [comment]
do you have more of this snippet that includes the definition for `n` ?

**Comment by Vexu** [comment]
Not reproducible.
