### ISSUE TITLE
os.preadv darwin implementation does not maintain guarantees

### ISSUE THREAD

**Issue by qbradley** [ziglang/zig#3836]
preadv on posix guarantees an atomic read.  The current os.preadv emulates preadv on OSX by looping pread() calls. This doesn't have the same guarantees as preadv and could be misleading.

I think I would suggest not exposing os.preadv at all and let it be an OS specific api.

ditto for pwritev

**Comment by andrewrk** [comment]
This is a good point, it would be a subtle cause of bugs. But consider the use case of code that is able to take advantage of such an API if it exists, but does not need the atomicity guarantees? Such code would want exactly this API interface.

So I would counter-propose by suggesting that we keep the emulation code, but clearly document which targets have atomicity guarantees and which do not.

A possible compromise API could be making `preadv` a compile error if it did not have the atomicity guarantee, and adding another function called `preadvNonAtomic` which is more portable and does the emulation code if necessary.

**Comment by qbradley** [comment]
The compromise seems very reasonable.  I'll put together a pull request.

**Comment by andrewrk** [comment]
It's now clearly documented in all those kind of functions when something is atomic or not. Here's one example:

https://github.com/ziglang/zig/blob/8aaab75af05c6066d8f952259d0d540f92c4772e/lib/std/fs/file.zig#L407-L411

pread example:

https://github.com/ziglang/zig/blob/8aaab75af05c6066d8f952259d0d540f92c4772e/lib/std/os.zig#L450-L453
