### ISSUE TITLE
Error when self-referencing with intermediate array

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#3843]
I discovered a bug yielding `error: struct 'T' depends on itself`:

```zig
const T = struct {
    children: [1]*T,
};
```

The code compiles when removing the array type:
```zig
const T = struct {
    children: *T,
};
```

I expect this is a bug in the lazy type resolver...
Zig version: `0.5.0+0f2a9af4a`

**Comment by Vexu** [comment]
Related of #3777. 
Both are caused by arrays not being lazy.
