### ISSUE TITLE
container 'std.os.system' has no member called 'exit'

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#3847]
Rebuilding with newest zig I get the following error for a freestanding project:

https://github.com/markfirmware/zig-bare-metal-microbit/commit/f2624a92ced709f4253cd52318cbd3128d3d2a71/checks?check_suite_id=342865280

    zig/lib/zig/std/os.zig:272:11: error: container 'std.os.system' has no member called 'exit'

    /home/runner/work/zig-bare-metal-microbit/zig-bare-metal-microbit/zig/lib/zig/std/special/start.zig:249:35: error: 'main' is private

I do not know how to correct this.

**Comment by andrewrk** [comment]
> error: 'main' is private

This can be solved by putting `pub` in front of `export fn main`.

As for the other thing, I'll take a look at your project. Thanks for the report

**Comment by markfirmware** [comment]
Thanks

**Comment by andrewrk** [comment]
What steps can I take to reproduce the problem? with `zig-0.5.0+1baaf9a50` your `build.sh` script completes successfully for me.

**Comment by andrewrk** [comment]
I'm guessing that 10e172b1d77619469653b0521d8f65604fa549c7 fixed the problem

**Comment by markfirmware** [comment]
8829b5316 works which is being delivered now.  1baaf9a50 was being delivered this morning and that works. Thanks so much.
