### ISSUE TITLE
UEFI SYSTEM_TABLE difinition

### ISSUE THREAD

**Issue by Heppokoyuki** [ziglang/zig#3866]
According to UEFI Specification version 2.8(https://uefi.org/specifications), ConIn that is the member of EFI_SYSTEM_TABLE is defined as EFI_SIMPLE_TEXT_INPUT_PROTOCOL(Section 4.3). 

But Zig's uefi api defines as **EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL**:
https://github.com/ziglang/zig/blob/05fc4d34a93d1e8fd4a107cb17c9d4fd7ffc29bc/lib/std/os/uefi/tables/system_table.zig#L18-L48

**EFI_SIMPLE_TEXT_INPUT_EX_PROTOCL** is not supported all uefi enviroment, so I think this is problem. Or is there some reasons to use **EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL**?

**Comment by andrewrk** [comment]
cc @nrdmn

**Comment by nrdmn** [comment]
You're right, ConIn should be a EFI_SIMPLE_TEXT_INPUT_PROTOCOL. I can fix it later this week. Thank you for your report!

**Comment by Heppokoyuki** [comment]
That's good. But I already wrote patch for this, may I send this?(Please note that I've never sent patch to OSS)

**Comment by nrdmn** [comment]
Sure, please do!

**Comment by Heppokoyuki** [comment]
Thank you! I sent!
