### ISSUE TITLE
Split language reference into smaller pages

### ISSUE THREAD

**Issue by xackus** [ziglang/zig#3870]
Currently the language reference page is excessively large.
Even with my changes in #3862 the mobile experience is poor. My Galaxy A5 2017 stutters very noticably.
I think most top level entries in the table of contents could have their own page.

**Comment by daurnimator** [comment]
I love having it on one page: I'm able to easily Ctrl+F and find a word/phrase in any section.

I'm curious why its slow on your mobile device: there isn't much fancy stuff happening. Lets try and fix that slowness. Do you get an equally slow experience for e.g. the large [lua manual](https://www.lua.org/manual/5.3/manual.html)?

**Comment by haze** [comment]
I've also had some issues where the docs would crash on safari stating that a problem repeatedly occurred, especially when trying to navigate using the table of contents

**Comment by xackus** [comment]
I've found the culprit. It's all the horizontally scrollable code.

**Comment by marler8997** [comment]
The single page is great for searchability.  I don't think we should remove the single page ref but I wouldn't be opposed to adding a multi-page ref in addition to the single page one.
