### ISSUE TITLE
Compiler bug: Assertion failed at D:\a\1\s\src\analyze.cpp:658 in get_optional_type.

### ISSUE THREAD

**Issue by ruffianeo** [ziglang/zig#3888]
Happens when compiling some possibly wrong source Zig source code.

Zig build used: zig-windows-x86_64-0.5.0+5874cb04b

**Comment by FireFox317** [comment]
How about showing that source? It's basically impossible to fix the bug without any source code. If possible please make the source as short as possible, that way it will be easier to fix for Zig developers.

**Comment by andrewrk** [comment]
Yep. I believe you @ruffianeo that you have found a bug in zig, however, based on the (lack of) information you have provided, this issue is not actionable.

**Comment by ruffianeo** [comment]
Here are the sources. 

Basically, only 4 lines are active. Rest is commented out.
In winallocator.zig only the (c)imports and the const expression is uncommented.
My guess is it is the const expression on a foreign function.
In main.zig I try to use the foreign function.
Check build.zig - maybe I messed up something there.

[hello.zip](https://github.com/ziglang/zig/files/3966062/hello.zip)

**Comment by daurnimator** [comment]
Simpler replicator (to save anyone else from downloading the .zip):
```zig
const std = @import("std");
const win = std.os.windows;
const k32 = win.kernel32;

pub const GetProcessHeap = k32.GetProcessHeap;

pub fn main() anyerror!void {
    const stdout = &std.io.getStdOut().outStream().stream;

    const pheap = GetProcessHeap();

    try stdout.print("pheap = {}\n", .{pheap});
}
```

And then try and run `zig build-exe src/main.zig  -l c`. I get the same segfault.
It appears to be coming from `@typeInfo()` on an optional.

**Comment by LemonBoy** [comment]
Here's a minimal reproducer and a big question:

```zig
pub fn main() void {
    const y = @typeInfo(*c_void);
}
```

The compiler is crashing because it tries to generate a `?c_void` type for the `sentinel` field of the typeinfo. Sooo, what's the correct type here? Using a non-optional one is going to need some more adjustments in the code built on that assumption.

**Comment by andrewrk** [comment]
Hm that's a bit awkward indeed.

The key insight here is that observing the `sentinel` field should never happen when the element type is an opaque type. So the type doesn't really matter. It can be `void`, for example. Or maybe the null type would be better (`@TypeOf(null)`).

**Comment by ruffianeo** [comment]
As an aside, from the little I did with the language so far, I have the hunch, that from the function syntax, with which types are being handled, it might be possible to express impossible or nonsensical or at least unexpected things - syntax wise. This might be just one example of something bigger.

**Comment by nmichaels** [comment]
I'm getting the same crash on the same line with this:

```
const std = @import("std");
const testing = std.testing;

test "zig bug" {
    const p: *c_void = @intToPtr(*c_void, 2);
    testing.expectEqual(p, @intToPtr(*c_void, 2));
}
```

**Comment by Sobeston** [comment]
Came across the same with:
```const std = @import("std");
usingnamespace std.os.windows;

pub extern "user32" stdcallcc fn FindWindowA(
    lpClassName: ?LPCSTR,
    lpWindowName: ?LPCSTR
) ?HANDLE;

pub fn main() void {
    std.debug.warn("hwnd: {}\n", .{FindWindowA(null, "abcdef")});
}```
