### ISSUE TITLE
@typeInfo forces unreferenced methods into existence

### ISSUE THREAD

**Issue by fengb** [ziglang/zig#3893]
Example: ([also on godbolt](https://godbolt.org/z/y9NR5c))
```zig
const std = @import("std");

const Foo = struct {
    bar: u8,

    pub fn broken() Foo {
        return .{ .bar = std.broken };
    }
};

export fn blah() void {
    // this line forces broken() into existence
    _ = @typeInfo(Foo);
}
```

**Comment by cshenton** [comment]
I've run into this as well and it's blocking me on some generic vector math stuff I'm implementing. If someone could point me in the general direction of the smoke I'd be happy to take a look.

**Comment by fengb** [comment]
andrewrk mentioned we could try converting `.decls` to be lazy. It wouldn’t be the permanent fix, but it would at least work around the major problems without introducing complex timing issues.

**Comment by andrewrk** [comment]
Same issue as #2584
