### ISSUE TITLE
sigprocmask (std.os.linux) questions

### ISSUE THREAD

**Issue by gakada** [ziglang/zig#3903]
Currenty [std.os.linux](https://github.com/ziglang/zig/blob/master/lib/std/os/linux.zig) has
```zig
pub fn sigprocmask(flags: u32, noalias set: *const sigset_t, noalias oldset: ?*sigset_t) usize;
pub fn blockAllSignals(set: *sigset_t) void;
pub fn blockAppSignals(set: *sigset_t) void;
pub fn restoreSignals(set: *sigset_t) void;
```
shouldn't it be
```zig
pub fn sigprocmask(flags: u32, noalias set: ?*const sigset_t, noalias oldset: ?*sigset_t) isize;
pub fn blockAllSignals(set: ?*sigset_t) isize;
pub fn blockAppSignals(set: ?*sigset_t) isize;
pub fn restoreSignals(set: ?*sigset_t) isize;
```
That is,
- Return `isize` (or maybe `i32`), kernel can return `-EFAULT` (`-14`, bad address) and `-EINVAL` (`-22`, invalid argument). In POSIX it is `-1` with `errno` set (for `EINVAL`).
- `set` and `oset` can be `NULL` to opt-out from changing/querying. Both in Linux and POSIX.

**Comment by daurnimator** [comment]
>     * Return `isize` (or maybe `i32`), kernel can return `-EFAULT` (`-14`, bad address) and `-EINVAL` (`-22`, invalid argument). In POSIX it is `-1` with `errno` set (for `EINVAL`).

The zig standard library assumes that `EINVAL` and `EFAULT` are unreachable in correct code, and hence do not need to be reflected in wrappers.

**Comment by gakada** [comment]
I see, but `sigprocmask` returns `usize` right now, so it should be all `void`? Then the suggestion is
```zig
pub fn sigprocmask(flags: u32, noalias set: ?*const sigset_t, noalias oldset: ?*sigset_t) void;
pub fn blockAllSignals(oldset: ?*sigset_t) void;
pub fn blockAppSignals(oldset: ?*sigset_t) void;
pub fn restoreSignals(oldset: ?*sigset_t) void;
```
Technically it is still [possible](https://github.com/torvalds/linux/blob/master/kernel/signal.c#L2947) to trigger `EINVAL` by something like `sigprocmask(42, &set, null)`.

**Comment by daurnimator** [comment]
> `sigprocmask` returns `usize` right now, so it should be all `void`?

The definition in `std.c` should return `usize` or `isize`; if there's a wrapper in `std.os` then it should return `void`.

**Comment by gakada** [comment]
[std.c](https://github.com/ziglang/zig/blob/master/lib/std/c.zig) has
```zig
pub extern "c" fn sigprocmask(how: c_int, noalias set: *const sigset_t, noalias oset: ?*sigset_t) c_int;
```
so I'd say that is also
```zig
pub extern "c" fn sigprocmask(how: c_int, noalias set: ?*const sigset_t, noalias oset: ?*sigset_t) c_int;
```
(optional `set`).

**Comment by gakada** [comment]
Somewhat loosely related, but why `std.os.linux.fork` return `usize`? Like `std.os.linux.sigprocmask` it can produce, e.g., `(usize)-EINVAL`.

**Comment by daurnimator** [comment]
> Somewhat loosely related, but why `std.os.linux.fork` return `usize`? Like `std.os.linux.sigprocmask` it can produce, e.g., `(usize)some negative number`.

We defined linux to have: `pub fn getErrno(r: usize) u12`
