### ISSUE TITLE
function argument type ... produces incorrect error message ‘undeclared’

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#3931]
https://github.com/markfirmware/zig-bare-metal-microbit/blob/be8dcb5372644e5196b04b55f51ce45b3381a2f6/main.zig#L45

build:
https://github.com/markfirmware/zig-bare-metal-microbit/commit/be8dcb5372644e5196b04b55f51ce45b3381a2f6/checks?check_suite_id=359829342#step:4:1

**Comment by markfirmware** [comment]
Reduced case:

    pub fn main() void {
        log("");
    }

    fn log(comptime format: []const u8, args: ...) void {
        @import("std").fmt.format({}, error{}, logBytes, format, args) catch |e| switch (e) {};
    }

    fn logBytes(context: void, bytes: []const u8) error{}!void {}

**Comment by frmdstryr** [comment]
Var args (...) has been replace with tuples, see https://github.com/ziglang/zig/pull/3873

**Comment by markfirmware** [comment]
Thanks - almost done testing the changes.

**Comment by andrewrk** [comment]
Expected behavior is a parse error:

```
error: expected expression, found `...`
```
