### ISSUE TITLE
Compiler Bug: Vector Store

### ISSUE THREAD

**Issue by cshenton** [ziglang/zig#3937]
Ran into a compiler bug while trying to do some SIMD stuff.

Minimal repro, fails on master, macOS:

```zig
// bug.zig
pub fn main() void {
    var src : [8]f32 = .{0, 0, 0, 0, 0, 0, 0, 0};
    var vec : @Vector(4, f32) = [4]f32{ src[0..4] };
}
```
Results in the following LLVM error propagated through zig.
```
$ zig build-exe src/bug.zig
broken LLVM module found: Stored value type does not match pointer operand type!
  store float* %4, float* %3, !dbg !1064
 floatStored value type does not match pointer operand type!
  store i64 4, float* %5, !dbg !1064
 float
This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
Abort trap: 6
```

**Comment by fengb** [comment]
`[4]f32{ src[0..4] }` — this is trying to make an array with the first element = to the slice `src[0..4]`. The compiler should really be catching this failed coercion.

https://github.com/ziglang/zig/issues/863 has the accepted proposal for converting slices back to arrays.

In the meantime here's some alternatives:
```zig
var vec: @Vector(4, f32) = [4]f32{ src[0], src[1], src[2], src[3] };

// This is so kludgy -- probably should wrap in a function
var array = @ptrCast(*const [4]f32, src[0..4].ptr);
var vec2: @Vector(4, f32) = array.*;
```

**Comment by fengb** [comment]
Compiler now spits out a usable error:
```
./testa.zig:3:42: error: expected type 'f32', found '*[4]f32'
```

And #863 is now done so this has a much more natural syntax:
```zig
var vec: @Vector(4, f32) = src[0..4].*;
```
