### ISSUE TITLE
Remove reference to @isInteger() and @isFloat() in Documentation

### ISSUE THREAD

**Issue by jajo-11** [ziglang/zig#3959]
In the section "Case Study: printf in Zig" in the Documentation the Function `printValue()` references `@isInteger` and `@isFloat` which don't exist since b483db486842c6d7d348b28ca09e56673e1bd800 and probably should be replaced by a `switch (@typeId(T))`.

**Comment by jajo-11** [comment]
I looked into making a Pull Request, but I am not sure how the implementation should look like since the methods of `OutStream` as used in the current example do not match the actual methods found in the standard library. So is the main focus of that example switching on the types, or accurate but stripped down representation of the `printf` function? I. e. should the example just pretend that these methods exist or should I replace them with actual methods found in `OutStream`. (More complicated since there are no methods handling floats)

**Comment by watzon** [comment]
It seems to me, and I could be wrong here, but that section seems pretty out of date. According to the git blame it hasn't been updated for 2 years, and a lot seems to have changed since then.
