### ISSUE TITLE
unable to pass `--eh-frame-hdr` to linker

### ISSUE THREAD

**Issue by dcao** [ziglang/zig#3965]
When attempting to use a C++ library which exposes a C API, if the library throws an exception anywhere, even if the exception is caught in the C++ library code (i.e. it isn't thrown in the C API), the binary will terminate.

This applies both when building Zig source files that include a C header and when building C files directly via Zig (i.e. `zig build-exe --c-source whatever.c`).

For instance, given the following files:

```cpp
// test.cpp
#include "test.h"

int etc() {
    try {
        throw 1;
    } catch (int x) {
        // No-op
    }
    return 0;
}
```

```cpp
// test.h
#ifdef __cplusplus
extern "C" {
#endif

int etc();

#ifdef __cplusplus
}
#endif
```

```c
// main.c
#include "test.h"

int main() {
    int x = etc();

    return x;
}
```

After building the executable, the binary terminates due to a thrown exception:

```shell
$ zig build-exe --c-source main.c --library c --object /nix/store/vgn1sxcj5ma9m5bhjps1q9jx3q2ab27c-gcc-8.3.0/lib64/libstdc++.a --object test.o --name main
$ ./main
terminate called after throwing an instance of 'int'
terminate called recursively
Aborted (core dumped)
```

This issue doesn't exist when building the C file with gcc or clang.

**Comment by dcao** [comment]
The cause of this problem is that the linker needs to command-line flag `--eh-frame-hdr`; there's no API to pass this to the linker.

**Comment by andrewrk** [comment]
Thanks for the patch to fix it!
