### ISSUE TITLE
when linking libc, expose libc version in builtin import, and only call c functions in std library when linking libc whose version is known to have the function

### ISSUE THREAD

**Issue by tiehuis** [ziglang/zig#397]
`getRandomBytes` uses `getrandom` from libc. This however is fairly new, requiring the `2.25` version of glibc to compiler. If not present, this will cause a link error.

https://github.com/andrewrk/tetris fails to compile for example using an older glibc `2.23`.

We could just use the syscall directly which would stop this glibc requirement. A fallback to /dev/urandom would probably be good as well. Would need to check some other source for a good set of fallback procedures.

**Comment by andrewrk** [comment]
Currently, ability to link against libc requires knowing all the various paths to libc runtime. When you cross compile and link against libc, you have to have a libc compiled for the target and give the paths to that via command line. So we should be able to determine the version of libc that we are linking against. Then we can expose this number to the source code via the builtin import.

Then the code can check the libc version number and fall back if the libc is too old.

At this point though, I think just doing the getrandom syscall with the /dev/urandom fallback is better than status quo, and we can do the fancy version number checking later.

**Comment by andrewrk** [comment]
Related: #1907 and #1018
