### ISSUE TITLE
`comptime` should not be allowed in type expressions: e.g. `var foo: comptime u64`

### ISSUE THREAD

**Issue by momumi** [ziglang/zig#3976]
A comptime variable in zig uses the syntax `comptime var foo: u64`, however the compiler also accepts `var foo: comptime u64`. The compiler seems treat the latter case as equivalent to `var foo: u64`, but I think it should be a syntax error.

For example this program will compile and run without errors:

```
const std = @import("std");

pub fn main() void {
    var x: comptime u64 = std.time.milliTimestamp();

    std.debug.warn("time: {}\n", .{x});
}
```

On a slightly related note, the [zig grammar in the docs](https://ziglang.org/documentation/master/#Grammar) seems to be very wrong/outdated (e.g. a `CHAR_LITERAL` would be a valid `TypeExpr`), but that's probably a separate issue.

**Comment by SpexGuy** [comment]
This was recently added as part of #8364.  Closing this in the interest of having only one issue to track the change.
