### ISSUE TITLE
stack traces should take into account DWARF stack unwinding info

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#398]
so that stack traces work well in release mode too.

**Comment by BratishkaErik** [comment]
IIUC this is resolved by https://github.com/ziglang/zig/pull/15823 ?

**Comment by andrewrk** [comment]
Yes, solved by @kcbanner in #15823, landed in 61d5b7c957e63239f1ebbdbfb94105d53f2dbaa4.
