### ISSUE TITLE
Remove std.mem.toSliceConst, have toSlice return the `const`-ness of its argument

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#3985]
@daurnimator
> It might make sense to remove `toSliceConst` entirely and have the return value have the `const`-ness of the argument?

@andrewrk
> I agree with this. I would even go so far as to say it's worth having the parameter accept a `var` type in general to accommodate this.

_Originally posted in https://github.com/ziglang/zig/pull/3972_

**Comment by andrewrk** [comment]
I opened a related proposal #4000. So far I'm leaning towards accepting both.

**Comment by andrewrk** [comment]
Done in 5b26128bacddf594dfe45958a236bfa2459f878b. Deleting deprecated functions will happen naturally, or as part of #1629.
