### ISSUE TITLE
Support bitfields in translate-c

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#4001]
Trying to use a `@cImport`-ed linux kernel header I got:
```
error: opaque types have unknown size and therefore cannot be directly embedded in structs
    kobj: struct_kobject,
          ^
```

Looking at the generated `cimport.zig` I found:
```
warning: struct demoted to opaque type - has bitfield
```

This issue tracks the implementation of bitfields in translate-c.

**Comment by andrewrk** [comment]
Duplicate of #1499
