### ISSUE TITLE
Printing whitespace characters with {c}

### ISSUE THREAD

**Issue by lukechampine** [ziglang/zig#4014]
https://github.com/ziglang/zig/commit/21bc3353b8812ea097afb52fef411a4fb32bfea9 changed the behavior of the `{c}` formatting directive:

```diff
-    return output(context, @as(*const [1]u8, &c)[0..]);
+    if (std.ascii.isPrint(c))
+        return output(context, @as(*const [1]u8, &c)[0..]);
+    return format(context, Errors, output, "\\x{x:0<2}", .{c});
```

The effect of this is:

```zig
fn printChars(s: []const u8) void {
    for (s) |c| {
        std.debug.warn("{c}", .{c});
    }
}
// old behavior:
// printChars("foo\tbar") -> foo    bar

// new behavior:
// printChars("foo\tbar") -> foo\x09bar
```
This is because `std.ascii.isPrint` returns false on whitespace other than 0x20 (` `).

This behavior does not match the behavior of the `%c` directive in C, Go, and other languages. Is this departure intentional? If so, what's the proper way to print a string character-by-character?

**Comment by andrewrk** [comment]
I labeled it as a bug, but then I checked the behavior of libc `isprint` and it agrees with `std.ascii.isPrint`, that `\t` is not printable. So I'm not yet sure how to resolve this.

**Comment by andrewrk** [comment]
cc @Vexu, curious about your thoughts on this.

**Comment by Vexu** [comment]
I think all whitespace with escape sequences (`\t` `\n`, `\r`) should be printed unescaped. I would've included them in the original change had I realized ascii doesn't consider them printable.

**Comment by andrewrk** [comment]
Hmm, how about this proposal:

Change \t, \n, \r to return `true` for `std.ascii.isPrint`. This would disagree with what these functions return in libc's isprint. But doesn't that seem like a bug, that they return `false`? https://en.cppreference.com/w/c/string/byte/isprint

**Comment by thejoshwolfe** [comment]
I can't find any specification on what the `%c` format is supposed to do in C or Go. All they say is "the character" or something similarly vague. To me, this means passing through the character without any escaping. There's no mention of "printable" in the `%c` specification, unless I'm not looking at the right document. Can someone point me to any specification for the behavior of `%c` more detailed than http://www.cplusplus.com/reference/cstdio/printf/ or https://golang.org/pkg/fmt/ ?

**Comment by hryx** [comment]
@thejoshwolfe From rummaging around the Go source and package documentation, `%c` means print everything unescaped, up to the [maximum supported codepoint](https://golang.org/pkg/unicode/utf8/#pkg-constants).

- [%c formatting in Go source](https://github.com/golang/go/blob/6f51082da77a1d4cafd5b7af0db69293943f4066/src/fmt/print.go#L388-L389), which [calls this](https://github.com/golang/go/blob/f376b8510ed7884c69a09fbcf61418f7285f2787/src/fmt/format.go#L461-L472)
- [change and discussion](https://go-review.googlesource.com/c/go/+/13821/) about not skipping space while scanning
- [printing behavior example](https://play.golang.org/p/FmaYyr9xH2q)

**Comment by TheZeus121** [comment]
%c in C outputs the "raw byte" with no checks on whether it's printable or not (which is why you can do terminal escapes with printf).

\t, \n, and \r are considered control characters instead of printable characters because instead of being one character, they do "magic" stuff with terminals usually--\t advances to the next tab stop, \n moves to the next line, \r moves to the beginning of the line.

I'd suggest adding some "raw string" and "raw character" formatting directives or remove the escaping behaviour altogether.
