### ISSUE TITLE
Segfault when reassigning to a const slice parameter

### ISSUE THREAD

**Issue by lukechampine** [ziglang/zig#4015]
The following test should result in a compile-time error, "cannot assign to constant":

```zig
pub fn reassign(s: []const u8) void {
    s = s[0..];
}

test "reassign slice" {
    const foo = "foo";
    reassign(foo);
}
```
Instead, it segfaults on Windows and Linux, and passes (erroneously) on MacOS.

If `foo` is declared as a `var`, or if `reassign` takes a `[]u8`, the test passes (erroneously) instead of segfaulting. Presumably this is because the string is no longer being stored in read-only memory. If the reassignment is changed to `s = s`, the compiler correctly emits an error. So my guess is that the slice expression is tripping up the "assign to constant" check.

**Comment by dbandstra** [comment]
Maybe related #3800
