### ISSUE TITLE
add test coverage for translating C code, compiling the resulting zig code, and running it

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#4018]
We already have translate-c tests which check that the given C code produces expected Zig source code.

The next step is to check the semantics of the translated code. We need tests that translate C code into Zig code, and then run the resulting Zig code, and make sure the output and behavior is correct.

**Comment by faraazahmad** [comment]
could it be done instead by comparing the LLVM IR generated by the zig compiler and clang?

**Comment by andrewrk** [comment]
We've had this for a while now: `./zig build test-run-translated-c`
