### ISSUE TITLE
update CI testing to use QEMU 4.2 to gain memfd_create support

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#4019]
This issue is to track the fact that we cannot test cross-compiled `memfd_create` until our CI server has an updated QEMU.

**Comment by LemonBoy** [comment]
This [blog article](http://logan.tw/posts/2018/02/18/build-qemu-user-static-from-source-code/) shows that it's pretty easy to build the usermode-emulation binaries as static binaries.
We could build those just once, upload the bins on S3 and have the CI jobs pull those if needed.

**Comment by andrewrk** [comment]
@mikdusan implemented this, we're now on qemu 5.1 in the CI script. repo: https://github.com/ziglang/qemu-static
