### ISSUE TITLE
translate-c subcommand fails with 'out of memory'

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#4028]
I accidentally ran `translate-c` on an empty .zig file:
```
$ touch foo.zig
$ zig translate-c foo.zig
unable to parse C file: out of memory
```

**Comment by LemonBoy** [comment]
#4003 made the error path not crash and burn, for some reason the clang frontend exits early without recording any diagnostic error.

**Comment by Vexu** [comment]
Running `translate-c` on a non-existing file with c file ending (c, h, hpp, cpp) prints garbage.
```bash
$ zig translate-c a.h
error: pa_4�U
```

**Comment by Sobeston** [comment]
I encountered the same error `unable to parse C file: out of memory`, but by using translate-c on a folder by mistake

**Comment by andrewrk** [comment]
#4455 is a duplicate of this, but I'm going to close this one instead since the diagnosis and related links are in the other issue
