### ISSUE TITLE
make translate-c translate "main" into something that start code will recognize properly

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#4029]
_Originally found by @daurnimator in https://github.com/ziglang/zig/issues/988#issuecomment-570120592_

When `zig translate-c` is run on a file that has an entrypoint (such as `main`), the signature does not match the one expected by zig's start code.

```
/home/daurnimator/src/zig/lib/std/start.zig:258:17: error: expected return type of main to be 'void', '!void', 'noreturn', 'u8', or '!u8'
                @compileError(bad_main_ret);
                ^
```

Should we add support for the traditional C entry point signatures?

**Comment by andrewrk** [comment]
This is actually already working fine - just need to pass `-lc` for the `build-exe` command.
