### ISSUE TITLE
Compiler error with float vectors

### ISSUE THREAD

**Issue by schmee** [ziglang/zig#4050]
`repro.zig`
```zig
pub fn main() void {
    @setFloatMode(.Optimized);
    var x: @Vector(3, f64) = undefined;
    const y = x / x;
}
```

Output: 
```
➜  zig-experiments git:(master) ✗ zig build-exe repro.zig
Code Generation [98/345] std.fs.path.joinSep...broken LLVM module found: Both operands to FCmp instruction are not of the same type!
  %13 = fcmp fast oeq <3 x double> %12, double 0.000000e+00, !dbg !1044
Branch condition is not 'i1' type!
  br <3 x i1> %13, label %DivZeroFail, label %DivZeroOk, !dbg !1044
  %13 = fcmp fast oeq <3 x double> %12, double 0.000000e+00, !dbg !1044

This is a bug in the Zig compiler.
Unable to dump stack trace: FileNotFound
```

Any of these changes makes the code compile:
- Change float mode to Strict
- Change `var x` to `const x`
- Change `const y` to `_`

Versions:
```
➜  zig-experiments git:(master) ✗ zig version
0.5.0+a90fa45ae
```
macOS Mojave 10.14.6

**Comment by travisstaloch** [comment]
I'm glad you reported this. I ran into the same thing a couple times in the past few days but then wasn't able to reproduce.

**Comment by travisstaloch** [comment]
Looks like using --release-fast or --release-small prevents this error.
Only seems to happen with debug or --relase-safe builds.

**Comment by LemonBoy** [comment]
There are a few checks (eg. divide by zero, overflow) for the `div`/`rem` ops that are not yet vector-aware.
