### ISSUE TITLE
failing assert(a | b & b == a | (b & b))

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#4051]
test "binary masking" {
        const a: u32 = 1;
        const b: u32 = 0;
        assert(a | b & b == a | (b & b));
    }

    const assert = @import("std").debug.assert;

targets linux aarch64, x64 and freestanding armv6m

zig version
0.5.0+a90fa45ae

**Comment by tiehuis** [comment]
Duplicate of #1902.
