### ISSUE TITLE
translate-c for loop missing non-declaration initializer

### ISSUE THREAD

**Issue by travisstaloch** [ziglang/zig#4067]
On master from today (0.5.0+f40b6b85f) this code is mis-translated, never assigning i = 0.  
```c
void foo() {
  int i;
  for (i = 0;;) {
  }
}
```
becomes: 
```zig
pub export fn foo() void {
    var i: c_int = undefined;
    {
        while (true) {}
    }
}
```

I created a case in test/translate-c.zig with what i believe to be the correct translation.  However, I am unsure how to fix it.  I would like to fix this myself but would need some guidance.  Explaining where to begin and an overview of which files need changes might help get me started. 

```diff
diff --git a/test/translate_c.zig b/test/translate_c.zig
index 0299da7b7..d56e2be95 100644
--- a/test/translate_c.zig
+++ b/test/translate_c.zig
@@ -1284,6 +1284,22 @@ pub fn addCases(cases: *tests.TranslateCContext) void {
         \\}
     });
 
+    cases.add("for loop initializer non-declaration",
+        \\void foo() {
+        \\  int i;
+        \\  for (i = 0;;) {
+        \\  }
+        \\}
+    , &[_][]const u8{
+        \\pub export fn foo() void {
+        \\    var i: c_int = undefined;
+        \\    {
+        \\        i = @as(c_int, 0);
+        \\        while (true) {}
+        \\    }
+        \\}
+    });
+
     cases.add("for loops",
         \\int foo() {
         \\    for (int i = 2, b = 4; i + 2; i = 2) {

```

**Comment by andrewrk** [comment]
> I created a case in test/translate-c.zig with what i believe to be the correct translation. However, I am unsure how to fix it. I like to fix myself but would need some guidance. Explaining where to begin and an overview of which files need changes might help get me started.

I think it would be nice to add a section to CONTRIBUTING.md with tips and guidance on how to contribute to translate-c. I'll see about creating this document over the next few days :-)

**Comment by travisstaloch** [comment]
Thanks @LemonBoy looks good!
