### ISSUE TITLE
Remove `proc_raise` from WASI

### ISSUE THREAD

**Issue by Swoogan** [ziglang/zig#4068]
Apparently `proc_raise` was removed from WASI: https://github.com/WebAssembly/WASI/commit/d07615f2c9b8f0761ccde71dbd13d8bb27551594

The zig generated reference to it was causing my wasm file to fail aot compilation with lucetc.

Looks like an easy fix, I'm just not sure what WASI should do when `std.os.raise` is called.

**Comment by andrewrk** [comment]
>  I'm just not sure what WASI should do when `std.os.raise` is called.

compile error. I'm pretty sure the fix is as simple as deleting those lines from `std.os.raise`.
