### ISSUE TITLE
`error: FileNotFound` during compile

### ISSUE THREAD

**Issue by Swoogan** [ziglang/zig#4069]
Occurs with 0.5.0+b91eaba38 x86_64 GNU/Linux. This is a regression from 0.5.0.

Repo @ https://github.com/Swoogan/toml4zig/tree/62a6cc16d93f317ba2225ff023f8f276933bd0f4
 
> error: FileNotFound
> /snap/zig/1111/lib/zig/std/os.zig:1308:19: 0x2434f7 in std.os.mkdirC (build)
>         EEXIST => return error.PathAlreadyExists,
>                   ^
> /snap/zig/1111/lib/zig/std/os.zig:1293:9: 0x24340f in std.os.mkdir (build)
>         return mkdirC(&dir_path_c, mode);
>         ^
> /snap/zig/1111/lib/zig/std/fs.zig:276:5: 0x243308 in std.fs.makeDir (build)
>     return os.mkdir(dir_path, default_new_dir_mode);
>     ^
> /snap/zig/1111/lib/zig/std/os.zig:730:23: 0x230dd0 in std.os.openatC (build)
>             ENOENT => return error.FileNotFound,
>                       ^
> /snap/zig/1111/lib/zig/std/fs.zig:718:20: 0x22bbf2 in std.fs.Dir.openFileC (build)
>         const fd = try os.openatC(self.fd, sub_path, os_flags, 0);
>                    ^
> /snap/zig/1111/lib/zig/std/fs.zig:702:9: 0x22b8aa in std.fs.Dir.openFile (build)
>         return self.openFileC(&path_c, flags);
>         ^
> /snap/zig/1111/lib/zig/std/fs.zig:91:20: 0x2718d7 in std.fs.updateFileMode (build)
>     var src_file = try my_cwd.openFile(source_path, .{});
>                    ^
> /snap/zig/1111/lib/zig/std/fs.zig:79:5: 0x271649 in std.fs.updateFile (build)
>     return updateFileMode(source_path, dest_path, null);
>     ^
> /snap/zig/1111/lib/zig/std/build.zig:801:29: 0x26ad36 in std.build.Builder.updateFile (build)
>         const prev_status = try fs.updateFile(source_path, dest_path);
>                             ^
> /snap/zig/1111/lib/zig/std/build.zig:2240:13: 0x26670d in std.build.InstallArtifactStep.make (build)
>             try builder.updateFile(self.artifact.getOutputHPath(), full_pdb_path);
>             ^
> /snap/zig/1111/lib/zig/std/build.zig:2420:9: 0x2442c3 in std.build.Step.make (build)
>         try self.makeFn(self);
>         ^
> /snap/zig/1111/lib/zig/std/build.zig:362:9: 0x242c5d in std.build.Builder.makeOneStep (build)
>         try s.make();
>         ^
> /snap/zig/1111/lib/zig/std/build.zig:356:17: 0x242c0a in std.build.Builder.makeOneStep (build)
>                 return err;
>                 ^
> /snap/zig/1111/lib/zig/std/build.zig:317:13: 0x2392c9 in std.build.Builder.make (build)
>             try self.makeOneStep(s);
>             ^
> /snap/zig/1111/lib/zig/std/special/build_runner.zig:122:21: 0x2326cb in main (build)
>             else => return err,

**Comment by LemonBoy** [comment]
`zig build --verbose` shows that the root cause is the absence of the generated header where the build system expects it to be. This patch fixes the problem but I don't know if it's correct for every other case:

```diff
diff --git a/src/codegen.cpp b/src/codegen.cpp
index 17ae34a1c..8f4402e71 100644
--- a/src/codegen.cpp
+++ b/src/codegen.cpp
@@ -10343,17 +10343,18 @@ void codegen_build_and_link(CodeGen *g) {
                         progress_name, strlen(progress_name), 0));
             }
             zig_llvm_emit_output(g);
+        }
 
-            if (!g->disable_gen_h && (g->out_type == OutTypeObj || g->out_type == OutTypeLib)) {
-                codegen_add_time_event(g, "Generate .h");
-                {
-                    const char *progress_name = "Generate .h";
-                    codegen_switch_sub_prog_node(g, stage2_progress_start(g->main_progress_node,
-                            progress_name, strlen(progress_name), 0));
-                }
-                gen_h_file(g);
+        if (!g->disable_gen_h && (g->out_type == OutTypeObj || g->out_type == OutTypeLib)) {
+            codegen_add_time_event(g, "Generate .h");
+            {
+                const char *progress_name = "Generate .h";
+                codegen_switch_sub_prog_node(g, stage2_progress_start(g->main_progress_node,
+                        progress_name, strlen(progress_name), 0));
             }
+            gen_h_file(g);
         }
+
         if (g->enable_dump_analysis) {
             const char *analysis_json_filename = buf_ptr(buf_sprintf("%s" OS_SEP "%s-analysis.json",
                         buf_ptr(g->output_dir), buf_ptr(g->root_out_name)));
```

**Comment by andrewrk** [comment]
I was hoping to get away with neglecting the generate .h files feature until self-hosted, so that we don't have to do the feature twice. I hope it will be reasonable to ask users to manually maintain .h files until the feature can be polished up in self-hosted land.

**Comment by andrewrk** [comment]
Oh, this looks more to do with the fact that the compilation has no zig code, so zig should figure out that there is no generated .h file.

**Comment by fengb** [comment]
I had the same underlying issue (no generated .h file) with recent versions of Zig: https://github.com/fengb/fundude/blob/388198e9652e409a64686e50b706ff2be8a2de1b/build.zig#L11

**Comment by SeekingMeaning** [comment]
Would this work?

https://github.com/ziglang/zig/blob/eff50abce68ffc69d236fcc0b919bc63fcd0e89a/lib/std/build.zig#L2294

```patch
-            .h_dir = if (artifact.kind == .Lib and !artifact.disable_gen_h) .Header else null,
+            .h_dir = if (artifact.kind == .Lib and artifact.root_src != null and !artifact.disable_gen_h) .Header else null,
```

**Comment by nmeum** [comment]
Hi, I am currently trying to add documentation [to the Alpine Linux Zig 0.6 package](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/6678). I am generating it using `./zig build` after make finished compilation.

Unfortunately, I always get the following error message on both x86_64 and aarch64:

```
/home/soeren/src/aports/testing/zig/src/zig-0.6.0/zig build-exe /home/soeren/src/aports/testing/zig/src/zig-0.6.0/doc/docgen.zig --cache-dir /home/soeren/src/aports/testing/zig/src/zig-0.6.0/zig-cache --name docgen --cache on 
error: FileNotFound
/home/soeren/src/aports/testing/zig/src/zig-0.6.0/lib/std/child_process.zig:235:9: 0x289a9b in std.child_process.ChildProcess.waitPosix (docgen)
        return self.term.?;
        ^
/home/soeren/src/aports/testing/zig/src/zig-0.6.0/lib/std/child_process.zig:168:13: 0x2888c7 in std.child_process.ChildProcess.wait (docgen)
            return self.waitPosix();
            ^
/home/soeren/src/aports/testing/zig/src/zig-0.6.0/lib/std/child_process.zig:212:21: 0x27f880 in std.child_process.ChildProcess.exec (docgen)
            .term = try child.wait(),
                    ^
/home/soeren/src/aports/testing/zig/src/zig-0.6.0/doc/docgen.zig:1519:20: 0x281045 in exec (docgen)
    const result = try ChildProcess.exec(.{
                   ^
/home/soeren/src/aports/testing/zig/src/zig-0.6.0/doc/docgen.zig:1549:20: 0x27b4ba in getBuiltinCode (docgen)
    const result = try exec(allocator, env_map, &[_][]const u8{
                   ^
/home/soeren/src/aports/testing/zig/src/zig-0.6.0/doc/docgen.zig:993:26: 0x2688f9 in genHtml (docgen)
    const builtin_code = try getBuiltinCode(allocator, &env_map, zig_exe);
                         ^
/home/soeren/src/aports/testing/zig/src/zig-0.6.0/lib/std/os.zig:1463:19: 0x2bb275 in std.os.unlinkatZ (docgen)
        EISDIR => return error.IsDir,
                  ^
/home/soeren/src/aports/testing/zig/src/zig-0.6.0/lib/std/os.zig:1445:5: 0x2aaa7b in std.os.unlinkat (docgen)
    return unlinkatZ(dirfd, &file_path_c, flags);
    ^
/home/soeren/src/aports/testing/zig/src/zig-0.6.0/lib/std/fs.zig:930:25: 0x29ad8b in std.fs.Dir.deleteFile (docgen)
            else => |e| return e,
                        ^
/home/soeren/src/aports/testing/zig/src/zig-0.6.0/doc/docgen.zig:53:5: 0x25fb46 in main (docgen)
    try genHtml(allocator, &tokenizer, &toc, buffered_out_stream.outStream(), zig_exe);
    ^
The following command exited with error code 1 (expected 0):
cd /home/soeren/src/aports/testing/zig/src/zig-0.6.0 && /home/soeren/src/aports/testing/zig/src/zig-0.6.0/zig-cache/o/d9YeqIjpFbSmxJ-MQLBA__hwc68xwX7QKNDMBBiOiTjVo4ZQU5miRHP_jBLTxUP0/docgen zig doc/langref.html.in zig-cache/langref.html 

Build failed. The following command failed:
/home/soeren/src/aports/testing/zig/src/zig-0.6.0/zig-cache/o/6x_DcNVcpux9EP2GGIaA6sD4EgYKjwSeR9RHnl79yUk49_c8r2Ck9DQCcFQBAkQB/build /home/soeren/src/aports/testing/zig/src/zig-0.6.0/zig /home/soeren/src/aports/testing/zig/src/zig-0.6.0 /home/soeren/src/aports/testing/zig/src/zig-0.6.0/zig-cache --verbose docs
```

Not sure if is related to this issue but the error message looks similar. Had the same issue with Zig 0.5 so it's not a (recent) regression. Just wanted to inform you about this, let me know if there is any way to work around this issue.

**Comment by andrewrk** [comment]
Issue no longer applicable with the new compiler implementation.
