### ISSUE TITLE
Segfault when switching on multiple cases from a pointer read with return

### ISSUE THREAD

**Issue by kprotty** [ziglang/zig#4074]
version: `0.5.0+6ea193946`

example code:
```zig
const ONE = @intToPtr(*u8, 1);
const TWO = @intToPtr(*u8, 2);

pub fn main() void {
    var ptr = &ONE;
    switch (ptr.*) {
        ONE => {},
        TWO => {},
        else => return,
    }
}
```

**Comment by LemonBoy** [comment]
LLVM doesn't like a `switch` over a non-integral type such as `i8*` in this case.
We may either:
* Reject this during the semantic checking phase
* Lower this with some `ptrToInt` sprinkled here and there
  * At the Zig IR level
  * At the LLVM IR level

@andrewrk pick your adventure heh

**Comment by daurnimator** [comment]
Converting the pointer to an integer at the LLVM IR level seems like the logical choice to me; as it sounds like an LLVM limitation that you can't switch on it

**Comment by andrewrk** [comment]
I second what @daurnimator said. Seems pretty straightforward, and I don't see it being a problem with a non-llvm backend either.

**Comment by frmdstryr** [comment]
That was fast, thanks!
