### ISSUE TITLE
Add @divCeil

### ISSUE THREAD

**Issue by momumi** [ziglang/zig#4095]
The `/` operator for unsigned integers rounds down, but it's also useful to have division that rounds up. You often see it done like this:

```
// div round up -> (numerator + (denominator - 1)) / denominator
const num_bytes = (bits + 7) / 8;
```

However, this will break if `(numerator + (denominator - 1))` overflows, so for the general case you need something like this:

```
fn divCeil(numerator: var, denominator: var) @TypeOf(numerator) {
    const quot = @divTrunc(numerator, denominator);
    const rem = @rem(numerator, denominator);
    const round_up = @intCast(@TypeOf(numerator), @boolToInt(rem > 0));
    return quot + round_up;
}
```

I'm not sure if you'd want it as a builtin `@divCeil` or under `std.math.divCeil`.

**Comment by daurnimator** [comment]
> I'm not sure if you'd want it as a builtin `@divCeil` or under `std.math.divCeil`.

It should only be a builtin if this is something that has a matching instruction on some CPU. Otherwise it just goes into the standard library.

**Comment by momumi** [comment]
In that case, I think we can move all of `@divFloor`, `@divTrunc`, `@divExact`, `@mod` and `@rem`  to the std library. I'm pretty sure all CPU division/remainder instructions performing rounding towards zero.  

Currently we have `/` and `%` to perform unsigned division remainder (`div`), and we need `@divTrunc` and `@mod` for the signed versions (`idiv`). But why can't we just use `/` and `%` for the signed versions as well?  With that you wouldn't need any of the other builtin functions I listed.

Thinking about it further, something that we currently don't have is unchecked signed integer division. The only way we can signed integer division is with `@divTrunc`, but it checks for overflow when dividing by `-1` `@as(i8, -128) / -1`

**Comment by shawnl** [comment]
> Also, there's no buitins for the ror and rol instructions 

There was once a patch for `@fshl` and `@fshr` that I wrote.

**Comment by schmee** [comment]
This was added to `std.math` in https://github.com/ziglang/zig/pull/6189, so I think this issue can be closed.
