### ISSUE TITLE
Compiler crashes on `lib/std/c/darwin.zig`

### ISSUE THREAD

**Issue by fengb** [ziglang/zig#4112]
```
$ zig test lib/std/c/darwin.zig --override-lib-dir lib
Assertion failed at ~/projects/zig/src/ir.cpp:852 in ir_ref_instruction. This is a bug in the Zig compiler.
Unable to dump stack trace: FileNotFound
Abort trap: 6
```

**Comment by LemonBoy** [comment]
Does it? I cannot get the compiler to crash no matter how bad I look at it :thinking:

**Comment by fengb** [comment]
I ran it with locally built and the latest master and got the same crash. Interestingly, `zig test lib/std/c.zig` on macOS works just fine even though the codepath should be nearly identical.

Bisect shows https://github.com/ziglang/zig/commit/6e635c64061dfc35b8178810bdd5bfc5452b9d28 as the originating offender, but reverting it doesn't solve the problem.
