### ISSUE TITLE
ChildProcess exec fileNotFound on Windows

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#4120]
Looks like the latest version of zig fails to find programs in the `PATH` on windows when running `ChildProcess.exec`
```zig
const std = @import("std");

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.direct_allocator);
    const args = [_][]const u8 {
        "ipconfig",
    };
    _ = try std.ChildProcess.exec(&arena.allocator, args[0..], null, null, std.math.maxInt(usize));
}
```

This will fail with `fileNotFound`.  I tried other programs as well, even though I can find with with `where <program>`, `ChildProcess` still fails to find them.

**Comment by daurnimator** [comment]
Could you share your PATH, PATHEXT and any other relevant environment variables, as well as where your executable is?

**Comment by marler8997** [comment]
```
C:\Users\Jonathan>where ipconfig
C:\Windows\System32\ipconfig.exe
```
As you can see, `ipconfig.exe` is in `C:\Windows\System32` which is in my `PATH` and `.EXE` is also in `PATHEXT`.  Did you try running the example?  Does it work for you?

> NOTE: it also fails with other executables, not just ipconfig, I"m just using that as an example.

**Comment by daurnimator** [comment]
Looks like it was a simple off-by-one error.

**Comment by jcs090218** [comment]
I've encountered this error on windows as well. Version `0.11.0` and `0.12.0-dev`.

**Comment by Beizbol** [comment]
Ran into this with `0.13.0` and `master` = `0.14.0-dev.2571+01081cc8e`

**Comment by nektro** [comment]
if u believe you've encountered buggy behavior please open a new issue with full reproduction steps
