### ISSUE TITLE
translate-c generates invalid zig when checking if pointers are null

### ISSUE THREAD

**Issue by pixelherodev** [ziglang/zig#4128]
With e.g. 
```c
void *a = blahblahblah;
if (a) {

}
```
the following is generated:

```zig
if (a) {

}
```

What should be generated is 
```zig
if (a != null) {

}
```
This happens for pointers to non-void also.

**Comment by pixelherodev** [comment]
For context, I was testing a static function in a header

**Comment by LemonBoy** [comment]
Hm? Can you give a complete test case exhibiting the problem?

```zig
    var a: ?*c_void = @intToPtr(?*c_void, @as(c_int, 0));
    if (a != null) {
```

**Comment by pixelherodev** [comment]
In checking again, I think I forgot to update Zig after updating LLVM yesterday as I had intended.

Apologies!
