### ISSUE TITLE
Compiler crash - "key not found"

### ISSUE THREAD

**Issue by Sobeston** [ziglang/zig#4134]
Small reproducible:
```zig
fn Hmm() type {
    return struct {
        pub usingnamespace if (@typeId(f32) == .Float) struct {
            fn x() void {}
        };
    };
}
usingnamespace Hmm();
```
Compiled with `zig build-exe main.zig`, latest windows build `0.5.0+e06a6b964`, this will result in:
```
key not found
Unable to dump stack trace: debug info stripped
```

The compiler behaves as expected if I replace:
- `@typeId(f32) == .Float` with `true`, `1 == 1` or similarly obvious true
- `@typeId(f32) == .Float` with `false`
- `fn Hmm() type {` with `fn Hmm() void {`
- `usingnamespace Hmm();` with `const z = Hmm();`
- `pub usingnamespace if` with `usingnamespace if`

The compiler continues crashing if I replace:
- `@typeId(f32) == .Float` with `@typeId(bool) == .Bool`
- `@typeId(f32) == .Float` with `@typeId(f32) == .Bool`
- `@typeId(f32) == .Float` with `@typeId(f32) == .OhNoItsAllBroken`

I believe this crash is triggered by a `zig_panic("key not found");` in `./src/hash_map.hpp`. Hope this helps.

**Comment by LemonBoy** [comment]
Reduced:
```zig
fn Hmm() type {
    _ = @typeId(f32);
    return struct {};
}
usingnamespace Hmm();
```

The `usingnamespace` is resolved by the compiler before the one in the compiler-generated `builtin.zig` is resolved.
