### ISSUE TITLE
show relative paths for compile errors when files are within cwd

### ISSUE THREAD

**Issue by mikdusan** [ziglang/zig#4138]
>It would be nice if the compile errors showed relative paths when the source files in question are in subdirectories of cwd

##### example cwd: `/Users/mike/project/zig/master`
```diff
! /Users/mike/project/zig/master/bug.zig:4:13: error: use of undeclared identifier 'a'
      var x = a + 1;
              ^
--- 1,3 ----
! bug.zig:4:13: error: use of undeclared identifier 'a'
      var x = a + 1;
              ^
```

**Comment by daurnimator** [comment]
I'd like it if it prefixed cwd-relative paths with `./` to make things easier to scan and identify as a path
