### ISSUE TITLE
zig.exe silently fails in pwsh on windows

### ISSUE THREAD

**Issue by gdoenlen** [ziglang/zig#4141]
Hi I freshly installed via scoop (https://github.com/ScoopInstaller/Main/blob/master/bucket/ziglang.json).  I'm not sure if it's a problem with the scoop installation or the exe itself, but it silently fails within pwsh 6 with a $LastExitCode of -1073741515, but when running from cmd it generates an error popup: 

![image](https://user-images.githubusercontent.com/17297466/72198648-a6344100-3428-11ea-91c1-d67b6ec7e562.png)

**Comment by daurnimator** [comment]
Looks like you're hitting https://github.com/ziglang/zig/issues/3391
This was a problem in the 0.5.0 release. Please use master instead for now.

**Comment by gdoenlen** [comment]
Thanks will do.
