### ISSUE TITLE
how to convert an integer to a string at comptime?

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#4142]
Something like

    fn missionName(comptime mission_number: u32) []const u8 {
        return std.fmt(“mission{:2}”, .{mission_number});
    }

**Comment by travisstaloch** [comment]
Here's one way to do it.  Not sure if its 'proper'. 

```zig
const std = @import("std");

fn intToString(comptime int: u32, comptime buf: []u8) ![]const u8 {
    return try std.fmt.bufPrint(buf, "{}", .{int});
}

test "comptime int to string" {
    const s = comptime blk: {
        var buf: [20]u8 = undefined;
        break :blk try intToString(42, &buf);
    };
    std.debug.warn("{}\n", .{s});
}
```

**Comment by travisstaloch** [comment]
This works too (without comptime params):

```zig
fn intToString(comptime int: u32, comptime buf: []u8) ![]const u8 {
    return try std.fmt.bufPrint(buf, "{}", .{int});
}
```

**Comment by markfirmware** [comment]
Thanks - seems to work - I guess I didn’t consider buf:[20] at comptime. Elegant.

**Comment by austinclem1** [comment]
For future searchers' benefit, now there's the `std.fmt.comptimePrint` function which calls `std.fmt.count` at compile time to figure out the exact buffer size needed the resulting string.
