### ISSUE TITLE
contributor-friendly zig-cache path defaults

### ISSUE THREAD

**Issue by mikdusan** [ziglang/zig#4173]
This is a proposal to change `zig-cache` locations for the Zig developers/contributors workflow. Developers tend to make changes that roll `zig id` and/or hashes for `std` sources. This in turn invalidates the cache unless the workflow reverts changes.

The zig driver computes `ZIG_LIB_DIR` by searching up the filesystem tree from the zig executable, for the following path suffixes:

1. `lib/zig/std/std.zig`
2. `lib/std/std.zig`

A match for `#1` indicates zig is running in an **installation** pattern and we can infer this is **not** a developer workflow. Nothing in this proposal effects this case and the rest of this proposal is not applicable.

A match for `#2` indicates zig is running in a **non-installation** pattern and we can infer this **is** a developer workflow and the rest of this proposal applies to this case.

Since we are in a non-installation pattern, zig executable is located inside a build directory and the aim is to place both global and local zig cache data directly adjacent to the executable. Thus the following locations:

TYPE | OS | DIRECTORY
:-: | :-: | ---
global | linux | $XDG_CACHE_HOME/zig
||| $HOME/.cache/zig
|| macOS | $HOME/Library/Application Support/zig
|| Windows | %LOCALAPPDATA%\zig
local | all | $PWD/zig-cache

would change to → `$DIR_OF_ZIG_EXE/zig-cache`

The following positives come to mind:

- cache is cleaned up as part of regular `cmake` build directory cleanup
- `zig test-standalone` tests now use the same cache
- easier to ensure clean-slate for reproducing cases
- much safer to cleanup the cache manually

**Comment by andrewrk** [comment]
I recognize the value in this proposal, however I'm going to close it because:
 * it's simpler to not do it, avoiding meta-complexity
 * we do still want to test the non-developer workflow, and I'm a bit uncomfortable making not testing it the default.
