### ISSUE TITLE
Question on syntax [*:null]const

### ISSUE THREAD

**Issue by dangerousHobo** [ziglang/zig#4190]
I'm looking at the following in `lib/zig/std/os.zig`:

```
./os.zig:765:pub fn execveC(path: [*:0]const u8, child_argv: [*:null]const ?[*:0]const u8, envp: [*:null]const ?[*:0]const u8) ExecveError {
```

I'm curious on the type `[*:null]const ?[*:0]const u8`. The latter half makes it looks like an optional string type, but I'm not sure what `[*:null]const` means. Couldn't find any documentation on this.

**Comment by andrewrk** [comment]
Hi @dangerousHobo, welcome to the community. Please direct questions to one of these places: https://github.com/ziglang/zig/wiki/Community

I'm trying to keep all open issues "actionable", e.g. someone could do work, and then close the issue when it is solved.

**Comment by kavika13** [comment]
https://ziglang.org/documentation/master/#Optionals
https://ziglang.org/documentation/master/#toc-Sentinel-Terminated-Pointers
