### ISSUE TITLE
@cInclude("winsock2.h") fails to handle multicharacter literal

### ISSUE THREAD

**Issue by mikdusan** [ziglang/zig#4194]
#### reduction: `ws.zig`
```zig
const c = @cImport({
    @cInclude("winsock2.h");
});

export fn foo() void {
    var ws: c.WSADATA = undefined;
}
```

#### command: `zig build-exe ws.zig -lc`
```
zig-cache\o\X_taigvKlaSL0Ni7WvXJhwwQNAb7JSTXans6wCe2RuMSTfhndUY2K91GxGNfXhJ9\cimport.zig:47018:24: error: invalid character: 'R'
pub const LCS_sRGB = 'sRGB';
                       ^
```

**Comment by Diltsman** [comment]
Prior versions of Zig didn't generate any code in cimport.zig for `LCS_sRGB`.

**Comment by Rocknest** [comment]
Cannot reproduce. Probably translated from:
```c
typedef enum {
    LCS_CALIBRATED_RGB = 0x00000000,
    LCS_sRGB = 0x73524742, // s R G B
    LCS_WINDOWS_COLOR_SPACE = 0x57696E20
} LogicalColorSpace;
```

**Comment by andrewrk** [comment]
Add `-target x86_64-windows-gnu` to @mikdusan's command line above and you'll be able to reproduce it on any OS.

**Comment by Diltsman** [comment]
This documents the Microsoft specific implementation of multicharacter char literals.

[https://docs.microsoft.com/en-us/cpp/cpp/string-and-character-literals-cpp?view=vs-2019](https://docs.microsoft.com/en-us/cpp/cpp/string-and-character-literals-cpp?view=vs-2019)

**Comment by Diltsman** [comment]
How should multicharacter literals be treated?  It is implementation dependent in C.
