### ISSUE TITLE
Proposal: @tagName with comptime tag/enumerant

### ISSUE THREAD

**Issue by metaleap** [ziglang/zig#4214]
Right now, built-in `@tagName` accepts a union-typed value and produces the `activeTag`'s name. Would be occasionally handy for the comptime ninja to have it accept and recognize comptime-known tag/union-field names (actual identifier not string literal) as well.

Where is the current implementation of `@tagName` builtin? If it's in Zig's stdlib, haven't found it (std.meta.tagName just refers to the @ builtin as well). If it's done in Zig I'd happily take a stab at a PR, but if in C/++ I'd rather wait for fully-featured self-hosting compiler to show up...

**Comment by andrewrk** [comment]
implementation is in ir.cpp in `ir_analyze_instruction_enum_tag_name`. medium-hard difficulty if you have not contributed to this area of the codebase before, probably a pretty easy difficulty for those who have.
