### ISSUE TITLE
@sqrt with Vector type is failing now

### ISSUE THREAD

**Issue by wilsonk** [ziglang/zig#4218]
I am sure this compiled a few weeks ago (https://gist.github.com/travisstaloch/2bddc2645002e91507cb364ea2502321), but now it fails at line 137 with a broken llvm module -- both operands to FCmp instruction are not the same type.  

Not sure what changed in the interim that would affect this.

**Comment by LemonBoy** [comment]
Duplicate of #4050

**Comment by wilsonk** [comment]
Closing as it is a duplicate...sorry I didn't search well enough for this one.
