### ISSUE TITLE
Compiler segfault when using runtime reflection to access union's active field

### ISSUE THREAD

**Issue by svmhdvn** [ziglang/zig#4226]
I'm a zig beginner and I'm trying to use runtime reflection to recurse on the active field of a union value (I'm not sure if I'm going about this correctly, so let me know). I came across this case:

```zig
const std = @import("std");

const SomeUnion = union(enum) {
    Int: i32,
    Bool: bool,
};

pub fn recRefl(thing: var) SomeUnion {
    const type_info = @typeInfo(@TypeOf(thing));
    return switch (type_info) {
        .Bool => SomeUnion{ .Bool = thing },
        .Int, => SomeUnion{ .Int = thing },
        .Union => |u| blk: {
            const tag_name = @tagName(thing);
            inline for (u.fields) |field| {
                if (std.mem.eql(u8, tag_name, field.name)) {
                    break :blk recRefl(@field(thing, field.name));
                }
            }
            unreachable;
        },
        else => unreachable
    };
}

pub fn main() void {
    var x: i32 = 42;
    const u_val = SomeUnion{ .Int = x };
    const result = recRefl(u_val);
    std.debug.warn("{}\n", .{result});
}
```

This results in a compiler segfault (on the master branch). I tried to reduce this case further into a simpler reproduction:

```zig
const std = @import("std");

const SomeUnion = union(enum) {
    Bool: bool,
};

pub fn recRefl(thing: var) SomeUnion {
    const type_info = @typeInfo(@TypeOf(thing));
    return switch (type_info) {
        .Bool => SomeUnion{ .Bool = thing },
        .Union => |u| blk: {
            const tag_name = @tagName(thing);
            inline for (u.fields) |field| {
                if (std.mem.eql(u8, tag_name, field.name)) {
                    break :blk recRefl(@field(thing, field.name));
                }
            }
            unreachable;
        },
        else => unreachable,
    };
}

pub fn main() void {
    const u_val = SomeUnion{ .Bool = true };
    const result = recRefl(u_val);
}
```

This results in the following compiler error message:
```
Code Generation [253/477] std.debug.parseFormValueDwarfOffsetSize...broken LLVM module found: Operand is null
  %4 = call fastcc %"[]u8"* @"__zig_tag_name_@TagType(SomeUnion)"(<null operand!>), !dbg !13710
Function arguments must have first-class types!
void %0
Instruction operands must be first-class values!
  switch void %0, label %BadValue [
    void zeroinitializer, label %Name
  ]

This is a bug in the Zig compiler.
```

Please let me know if this is a duplicate error (I couldn't find an issue filed about this) and I will close it.

Side note: I was reading the documentation
> @tagName can be used to return a comptime []const u8 value representing the field name

Is this correct? Getting the tag name of the active field of a runtime union value should result in a runtime `[]const u8` return value right?

**Comment by pixelherodev** [comment]
Just for the record: Zig *does not have* runtime reflection. All of the reflection in Zig is *compile* time.

Let me repeat that one more time, for emphasis: *all reflection in Zig is **compile** time*.

> Is this correct? Getting the tag name of the active field of a runtime union value should result in a runtime []const u8 return value right?

The documentation is correct; the *name* is a compile time constant, *not* a runtime value; however, it can still be used at runtime, as comptime strings decay into runtime strings when appropriate to the best of my understanding.

**Comment by LemonBoy** [comment]
The first problem you're experiencing is due to some well-known (but not well-investigated) bug that affects `inline for` constructs, there should already be a ticket open for that.

The second problem has just been fixed, thanks for the report!
