### ISSUE TITLE
Calling @typeInfo on a tuple type segfaults the compiler

### ISSUE THREAD

**Issue by cshenton** [ziglang/zig#4229]
Code to repro on `0.5.0+d972d1c94`:

```zig
// example.zig
const warn = @import("std").debug.warn;

pub fn main() void {
    warn("type: {}\n", .{@typeInfo(@TypeOf(.{1.0, true, 0}))});
}
```

Running `zig run example.zig` results in `Segmentation fault`.

I was doing this to figure out how to declare a tuple type, my use case is a generic type that accepts a tuple of types and creates a new struct type with a single field with a tuple of slices of those types.

**Comment by cshenton** [comment]
This is probably due the the fact that the type of `0` can't be inferred.

**Comment by cshenton** [comment]
Actually, that appears not to be the case:
```zig
// example.zig
const warn = @import("std").debug.warn;

pub fn main() void {
    warn("type: {}\n", .{@typeInfo(@TypeOf(.{@as(f32, 1.0), @as(bool, true), @as(i32, 0)}))});
}
```
This still segfaults.

**Comment by andrewrk** [comment]
I tested both test cases with latest master (currently 13259acbc3a9bf87db7245daf8132a7194264c51) and both pass.
