### ISSUE TITLE
error: expected token 'Symbol', found '{'

### ISSUE THREAD

**Issue by treeshateorcs** [ziglang/zig#4232]
compilation of literally every program I've tried so far (even the helloworld from ziglang.org) results in this error

```zig
const std = @import("std");

pub fn main() void {
    std.debug.warn("Hello, world!\n", .{});
}
```

```
$ zig build
/home/tho/Sources/zig/hello/src/main.zig:4:40: error: expected token 'Symbol', found '{'
    std.debug.warn("Hello, world!\n", .{});
                                       ^
The following command exited with error code 1:
/usr/bin/zig build-exe /home/tho/Sources/zig/hello/src/main.zig --cache-dir /home/tho/Sources/zig/hello/zig-cache --name hello --cache on 

Build failed. The following command failed:
/home/tho/Sources/zig/hello/zig-cache/o/ouwz651R2-EwcTmQwCe_yyoGbW9txyqaxCclN39Iv0etAsl5ssa-Sor_juNSrHHf/build /usr/bin/zig /home/tho/Sources/zig/hello /home/tho/Sources/zig/hello/zig-cache
```

i'm on fully up-to-date archlinux and this is zig v0.5.0

**Comment by daurnimator** [comment]
> this is zig v0.5.0

Most people are now on zig master.

**Comment by treeshateorcs** [comment]
>Most people are now on zig master.

maybe it's time for a new release? otherwise, what's the point of this package if it's not working

**Comment by lun-4** [comment]
0.6.0 is planned to release soon, likely in februrary? [the docs for 0.5.0 are available](https://ziglang.org/documentation/0.5.0)

**Comment by treeshateorcs** [comment]
thanks @lun-4 i should have searched for the docs myself, my bad

**Comment by andrewrk** [comment]
> what's the point of this package if it's not working

That's a reasonable question. 

We have long (6 month) release cycles for now, which favors fast-paced progress towards 1.0.0, but does not favor people trying to use zig for stable day-to-day activities. As you can see there are some downsides. This is what it feels like when a language is highly unstable. For now it's not really possible to do serious work in Zig without joining the development efforts. If you're looking for something more stable I recommend to check back in 1-2 years, and I think things will have settled down a bit.

**Comment by andrewrk** [comment]
@lun-4 the date in the milestone is accurate: [0.6.0 on April 13, 2020](https://github.com/ziglang/zig/milestone/8)
