### ISSUE TITLE
Proposal: 0 is default initialization for extern'd structs.

### ISSUE THREAD

**Issue by JesseRMeyer** [ziglang/zig#4244]
While Zig maintains that 0 is not a meaningful initialization value to indicate not initialized, many C libraries overload 0 to mean exactly that.  While we can manually memset these fields to zero, it's not ergonomic.  

Basically, the following should default initialize all the fields of some_ol_c_struct to 0 automatically.
```zig
const some_ol_c_struct = extern struct {
    x: c_uint,
    y: c_uint,
};

const plain_ol_data = some_ol_c_struct{};

assert(plain_ol_data.x == 0);
assert(plain_ol_data.y == 0);
```

Furthermore, if a field is specified as user initialized, all remaining fields are also 0 initialized.

```zig
const plain_ol_data_2 = some_ol_c_struct{.x = 1);

assert(plain_ol_data_2.x == 1);
assert(plain_ol_data_2.y == 0);
```

This makes interfacing with C libraries that leverage designed initialization a breeze.

**Comment by daurnimator** [comment]
Use `mem.zeroes`.

**Comment by JesseRMeyer** [comment]
If we can make the following simpler, perhaps with some syntactic sugar, I'd be happier :

```zig
var plain_ol_data_2 : some_ol_c_struct = undefined;
std.mem.set(u8, ([]u8)(&plain_ol_data_2)[0..1], 0); // Did I even do this correctly?  
```

But, doesn't mem.set or mem.zeroes force the input to be var instead of const?  I'd be happier finding a way to preserve that constraint if possible.

**Comment by FireFox317** [comment]
With `mem.zeroes` you can do this:
```
const data = mem.zeroes(plain_ol_data_2);
```

**Comment by JesseRMeyer** [comment]
> With `mem.zeroes` you can do this:
> 
> ```zig
> const data = mem.zeroes(plain_ol_data_2);
> ```

Thanks.  I didn't know (it looked like) that ... please disregard this proposal.
