### ISSUE TITLE
zig build: enhance RunStep to support argv forwarded from build_runner

### ISSUE THREAD

**Issue by mikdusan** [ziglang/zig#4252]
This is basically a convenience PR which adds some consistency to what `RunStep` looks like in `zig build --help`. Inspired by #4249.

- add field something like `usage: ?[]const u8,` to `Step`
- add fn something like `pub fn addArgsFromBuilder() void` to `RunStep` and:
    - add args from builder
    - `self.step.usage = "[-- [args]]"`
- enhance `zig build --help` to append optional usage beside `step.name`

so this `zig build --help`:
```
Steps:
  install (default)      Copy build artifacts to prefix path
  uninstall              Remove build artifacts from prefix path
  run                    Run the app
```

becomes

```
Steps:
  install (default)      Copy build artifacts to prefix path
  uninstall              Remove build artifacts from prefix path
  run [-- [args]]        Run the app
```

**Comment by metaleap** [comment]
@mikdusan @andrewrk sorry for being maybe dense as far as grasping the build codebase, but AFAICT that `usage` or say `args_hint` you envision (as far as I care the user-land could put the info in their `description`.. =) could go either in TopLevelStep or in RunStep:

- The `TopLevelStep` only has a `step: Step` with no (immediately obvious) way to get hold of the appropriate RunStep (to check whether even considering displaying `args_hint` is at all applicable in build_runner.zig#L152-L158). 

- The `RunStep` also has a `step: Step`. Now ideally we want to mark for the RunStep, from inside `addArgsFromBuilder`, that "args are supported" (even if in this current run none were present so none were added).

So somehow would have to add some ugly helper `did_add_args_from_builder: bool = false` to `Step`, that would be set by `RunStep.addArgsFromBuilder` and read by build_runner.zig#L152-L158 ... smells hacky to me, but if you don't mind "polluting `Step`" with something only related to `RunStep`, I have it almost done over here in my fork/branch and can push the PR.

**Comment by mikdusan** [comment]
@metaleap,

Thinking about this some more, my original assumption there was an association we could take advantage of, but there isn't and I'm don't find any of the API changes that come to mind desirable.

Going to abandon this PR as not-desirable. Apologies for the time sink.
