### ISSUE TITLE
Unable to determine comptime value from if-statement inside switch

### ISSUE THREAD

**Issue by jeffkdev** [ziglang/zig#4255]
```zig
pub fn main() void {
    var condition = true;
    var wave_type :u32 = 2;
    var sample_f32 : f32 = switch(wave_type) {
        0 => if(condition) 0.5 else -0.5,
        1 => 100.0,
        2 => 200.0,
        3 => 300.0,
        else => unreachable,
    };

    var sample_i32 : i32 = switch(wave_type) {
        0 => if(condition) 2 else 3,
        1 => 100,
        2 => 200,
        3 => 300,
        else => unreachable,
    };
}
```
Both switch statements result in compile errors:
.\scratch.zig:5:14: error: values of type 'comptime_float' must be comptime known
        0 => if(condition) 0.5 else -0.5,
             ^
I was thinking it should be able to determine the type inside the if statements from the result of the switch statement.

Casting the values using ```@as(f32,0.5)```, etc is a workaround for now. I couldn't find another open issue for this, but feel free to close if duplicate.

0.5.0 +a6f6d8d2f

**Comment by hryx** [comment]
Related to #3750, I think. The rules about peer type resolution and result location type seem to be fuzzy when the type inference is nested, at the moment.
