### ISSUE TITLE
Inline for loop with an unreachable code block causes build failure 

### ISSUE THREAD

**Issue by jeffkdev** [ziglang/zig#4257]
```zig
pub const Status = enum {
    Ok,
    NotOk,
};

fn getAnyStatus() Status {
    return .Ok;
}

pub fn main() void {
    inline for ([_]comptime_int{ 0, 4, 8 }) |i| {
        const status = getAnyStatus();

        if (status == .Ok) {
            // do nothing
        } else if (status == .NotOk) {
            // do nothing
        } else {
            unreachable;
        }
    }
}
```
No build error is printed on command line (exe is not created). VScode gives "The following command exited with error code 5".

Minimal test case above. Any one of the following will allow this to compile and run as expected:
- remove the unreachable block
- change getAnyStatus() call to .Ok or .NotOk
- remove 'inline' and change comptime_int to any integer type

0.5.0 +a6f6d8d2f

**Comment by CurtisFenner** [comment]
I'm guessing this is another form of issue #2727

**Comment by jeffkdev** [comment]
Yep, thanks. Definitely a duplicate, looks like there are already plenty of good example snippets in that thread. I'll close this one.
