### ISSUE TITLE
Proposal: have std.HashMap.initCapacity auto-scale to next power-of-two to prevent `unreachable` from subsequent `put`s (happy to PR)

### ISSUE THREAD

**Issue by metaleap** [ziglang/zig#4280]
Happy to PR this if "proposal" accepted.

Sometimes you fill in one HashMap from data of known length. User is tempted to `.initCapacity(my_known_len)`. If not a power-of-two, then not that call but some subsequent `.put` will `unreachable` from an `assert` in `.ensureCapacityExact` called by `.autoCapacity` called by `.put`.

It has been suggested in IRC that the assert should move to `.initCapacity` and that would be apt if `assert`ing is the desired way to handle things for the outlined use-case. I'd argue, not so: user-land should be able to say "I need you to make room for exactly this many entries, no more than that will come but those are guaranteed". If the `HashMap` _implementation_ internals require a power-of-two, let's ensure it so in the _implementation internals_. If you know you're gonna need to stash a million items, then there's no two ways about it. Better to OOM (proper `error`) than to UB (`unreachable`).

**Comment by squeek502** [comment]
I thought I understood this issue but after looking at the associated PR I don't think I do: https://github.com/ziglang/zig/pull/4370#issuecomment-588555549

Could you provide some test code that allows you to causes this assert? `initCapacity` is not `pub`, so where are you calling it from? `ensureCapacity` behaves correctly and should be preferred here, right?

**Comment by metaleap** [comment]
> initCapacity is not pub

I just checked in my nightly and you're right. But this thing here is a month old so either it has changed or I had a compiler nightly that didnt care about this particular `pub`ness back then :rofl: can close for now I think. Wonder why my StringHashMap.initCapacity calls still compile because I still have them in WIP projects (just with PowerOfTwo args)! Something to dig into shortly / later...

**Comment by Qix-** [comment]
@metaleap see #4909 - sounds like you hit this bug.
