### ISSUE TITLE
`@compileLog(@typeName(T))` sometimes prints `[x:0]u8{...}` array literals

### ISSUE THREAD

**Issue by metaleap** [ziglang/zig#4281]
For [example](https://github.com/metaleap/zigbag/blob/678c6a58b63bb055102eb3a6b5f3a5978aad8919/dummylangserver/lsp_json.zig#L26), when I `@compileLog(@typeName(T))` for `T`s from [this fat bag of type-defs](https://github.com/metaleap/zigbag/blob/678c6a58b63bb055102eb3a6b5f3a5978aad8919/dummylangserver/lsp_types.zig) where `@typeId(T) == .Enum`:

```
| *[21:0]u8{108,115,112,95,116,121,112,101,115,46,101,110,117,109,58,56,53,52,58,49,51}
| *"InsertTextFormat"
| *"CompletionItemKind"
| *[24:0]u8{83,105,103,110,97,116,117,114,101,72,101,108,112,84,114,105,103,103,101,114,75,105,110,100}
| *"CompletionItemTag"
| *[21:0]u8{67,111,109,112,108,101,116,105,111,110,84,114,105,103,103,101,114,75,105,110,100}
| *"lsp_types.enum:235:16"
| *"DiagnosticTag"
| *"SymbolKind"
```

All come from the exact same `@compileLog` call site, with `@typeId(T) == .Enum` always `true`.

This doesn't occur randomly, the same outputs occur exactly the same during many repeated attempts. I have some nutty type nestings in there (it expresses an MS-devised protocol so no surprise there..), so might be a neat stress test for the type-name-algo..  :grin:

**Comment by dbandstra** [comment]
Related #1747

**Comment by LemonBoy** [comment]
When the compiler is sure that the array contents comes from a `Buf` literal it will happily print it a string, otherwise it has no way to know that the content is ... well, text and not binary data or whatever.

**Comment by andrewrk** [comment]
I think the best we can do is have `@compileLog` do heuristics. If the len is less than 100 or something like that then treat it as a string (sometimes escaping with `\xNN` if it has to), otherwise treat it as an array.

**Comment by topolarity** [comment]
Wanted to tack on a good question raised in #12303: 

What's the need for `@compileLog` to accept anything other than a string, provided that we have `std.fmt.comptimePrint`?

**Comment by Vexu** [comment]
here's a simple example:
```zig
comptime {
    var a = [2]u8{ 1, 2 };
    var b = a[1..];
    @compileLog(b);
}
```
Stage1 gives `*[1]u8{2}`, stage2 gives `@as(*[1]u8, &.{ 1, 2 }[1])` and `comptimePrint`  gives:
```
./lib/std/fmt.zig:413:31: error: unable to evaluate constant expression
                try formatInt(@ptrToInt(value), 16, .lower, FormatOptions{}, writer);
                              ^
./lib/std/fmt.zig:477:29: note: called from here
        return formatAddress(value, options, writer);
                            ^
./lib/std/fmt.zig:183:23: note: called from here
        try formatType(
                      ^
./lib/std/fmt.zig:1937:11: note: called from here
    format(counting_writer.writer(), fmt, args) catch |err| switch (err) {};
          ^
./lib/std/fmt.zig:1983:76: note: called from here
pub fn comptimePrint(comptime fmt: []const u8, args: anytype) *const [count(fmt, args):0]u8 {
                                                                           ^
./lib/std/fmt.zig:1983:63: note: called from here
pub fn comptimePrint(comptime fmt: []const u8, args: anytype) *const [count(fmt, args):0]u8 {
                                                              ^
./a.zig:7:10: note: called from here
comptime {
         ^
```

**Comment by topolarity** [comment]
Hmm, thanks for that example, I hadn't thought about that.

It still seems like a gap not to have a built-in that can be guaranteed to print a string at compile-time without immediately halting compilation. I also think it's plausible that comptimePrint could be modified to match `@compileLog`-style printing (for the stage1 output, at least), but maybe there's another difficult example I haven't thought of.
