### ISSUE TITLE
Be able to print to terminal via std.debug.warn when running test

### ISSUE THREAD

**Issue by DanB91** [ziglang/zig#4293]
It would be incredibly helpful to be able to log to the screen when running a test.  Right now, the Zig test runner seems to destroy most, if not all output from std.debug.warn, rendering this function as essentially useless when running `zig test`.

I am running 0.5.0+4e9b1f547 on macOS.

To my surprise, I cannot find an open or closed issue on this.  However, if I missed it, apologies in advance.

**Comment by momumi** [comment]
Printing with `std.debug.warn` is working for me on Linux-0.5.0+96e5f476c, but the output does change if I pipe it to a file. Here's a test case with two files:

### Files

main.zig
```zig
const std = @import("std");
const other = @import("other.zig");

test "hello" {
    std.debug.warn("\nStarting hello\n", .{});
    std.debug.assert(other.thing());
}

test "foobar" {
    std.debug.assert(true);
}

test "goodbye" {
    std.debug.warn("\nStarting goodbye\n", .{});
    std.debug.assert(true);
}
```

other.zig
```zig
const std = @import("std");

pub fn thing() bool {
    return true;
}

test "other file 1" {
    std.debug.warn("\nOther file test 1\n", .{});
}

test "other file 2" {
    std.debug.assert(true);
}
```

### Output

If I running `zig test main.zig` outputs:

```
Test [1/5] test "hello"...
Starting hello
Test [3/5] test "goodbye"...
Starting goodbye
Test [4/5] other.test "other file 1"...
Other file test 1
All 5 tests passed.
```

However, if I pipe it to a file with `zig test main.zig &> test.log`

```
1/5 test "hello"...
Starting hello
OK
2/5 test "foobar"...OK
3/5 test "goodbye"...
Starting goodbye
OK
4/5 other.test "other file 1"...
Other file test 1
OK
5/5 other.test "other file 2"...OK
All 5 tests passed.
```

If you write it to a file, do you get all the output? A potentially unrelated issue I noticed is that `zig test` output is written to stderr, but I think it should really be written to stdout.

**Comment by DanB91** [comment]
@momumi So your test does work for me on macOS Catalina.  The key thing is here is I did not know the `\n` were required for it show in the terminal.  Ideally, I wouldn't think these would be required for them to show up, but if anything, maybe the docs can be updated to state this (I don't see it in the docs)?

**Comment by momumi** [comment]
It should still show text without the `\n`, just the formating will be messed up, eg:

```
test "hello" {
    std.debug.warn("<<Starting hello>>", .{});
}
```

Would print something like:

```
1/5 test "hello"...<<Starting hello>>OK
```

Maybe `std.debug.warn` and the test runner should be change so that they are aware of each other.  So if you added a `warn("hello world!\n")` message inside a test you would get different output:

```
1/5 test "hello"... OUTPUT:
hello world!
1/5 test "hello"... OK
```

**Comment by andrewrk** [comment]
This is working as designed. I think the default test runner behavior is reasonable. Feel free to propose a concrete change to `lib/std/special/test_runner.zig`. Currently nothing is planned to change to address this.
