### ISSUE TITLE
broken llvm module

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#4299]
var xyz: New = undefined;
    const New = struct {
        a: [4]u32,

        fn new() ?New {
            var x: New = undefined;
            return x;
        }
    };

    pub fn main() void {
        xyz = New.new();
    }

    root@localhost:~/github.com/markfirmware/zig-bare-metal-raspberry-pi-aarch64# zig build-exe main.zig 
    broken LLVM module found: Call parameter type does not match function signature!
    %New* @xyz
     %"?New"*  call fastcc void @New.new(%New* sret @xyz), !dbg !12541

**Comment by Vexu** [comment]
Same as #3422, #3646, #3224, #3327, #3269, #4234, #4086, #3898

**Comment by markfirmware** [comment]
Perhaps broken llvm module should print a list of open issues.

**Comment by daurnimator** [comment]
"broken llvm module" just means a bug that exposed itself in LLVM ir generation. "Call parameter type does not match function signature" is the more interesting error message, which you can search zig issues for.
