### ISSUE TITLE
anonymous-struct literal unable to be passed for anonymous-struct-typed arg

### ISSUE THREAD

**Issue by metaleap** [ziglang/zig#4305]
A minimal repro main.zig, currently rejected with ` ./main.zig:4:26: error: expected type 'struct:11:32', found 'struct:11:32' `:

```zig
const std = @import("std");

pub fn main() void {
    var sess = Protocol(.{
        .TIn = MyIn,
        .TOut = MyOut,
    }){};
    sess.serve(); // forever-loop
}

pub fn Protocol(comptime spec: struct {
    TIn: type,
    TOut: type,
}) type {
    return struct {
        subscribers: [@memberCount(spec.TIn)]?usize = ([_]?usize{null}) ** @memberCount(spec.TIn),
        pub fn on(self: *@This()) void {} // subscription
        pub fn serve(self: *@This()) void {} // transport-dealing forever-loop
    };
}

pub const MyIn = union(enum) {
    foo: fn (isize) bool,
    bar: fn (bool) isize,
};

pub const MyOut = union(enum) {
    baz: fn ([]u8) void,
};
```

The workaround is to extract the anonymous-struct of arg `spec` into a separated named definition ie. `const Spec = struct {...`.

As a point of interest, if all fields in the anonymous-struct decl get default values (eg. `TIn: type = union(enum) {},`) and an empty `.{}` anon-struct-literal is passed instead, same compiler message.

**Comment by andrewrk** [comment]
I believe this is a bug, which hopefully has a straightforward fix.

**Comment by Vexu** [comment]
Same root cause as #3707.
