### ISSUE TITLE
Mispelt external library linkage name stalls compilation.

### ISSUE THREAD

**Issue by JesseRMeyer** [ziglang/zig#4308]
Compiling:
```zig
pub extern "Kernel32" fn GetCurrentThread() callconv(.Stdcall) HANDLE;
```

stalls the compiler, where as

```zig
pub extern "kernel32" fn GetCurrentThread() callconv(.Stdcall) HANDLE;
```
does not.

**Comment by andrewrk** [comment]
what command used to run this example?

**Comment by JesseRMeyer** [comment]
Not a minimal repo, but to answer your question:
zig build-exe -ldxgi -ld3d12 -ldxguid -ld3dcompiler misspelt_bug1.zig -L "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64"

**Comment by Sobeston** [comment]
Minimal repo from #4796:
```zig
extern "Kernel32" fn hmm() void;

pub fn main() void {
    hmm();
}
```
`zig build-exe main.zig`

**Comment by andrewrk** [comment]
Now fails correctly with:

```
LLD Link... error(link): DLL import library for -lKernel32 not found
error: DllImportLibraryNotFound
```
