### ISSUE TITLE
Concurrent modification error while referring to invalid aliases

### ISSUE THREAD

**Issue by Snektron** [ziglang/zig#4310]
The following crashes on the latest master (13259acbc):
```zig
const A = B;

test "Crash" {
    _ = @typeInfo(@This()).Struct.decls;
}
```
with the message "concurrent modification" and "Panicked during a panic. Aborting.".
Note that the following results in the expected error message "use of undeclared identifier 'B'":
```zig
test "No crash" {
    const A = B;
    _ = @typeInfo(@This()).Struct.decls;
}
```

**Comment by andrewrk** [comment]
This is the c++ compiler's hash map iterator detecting that the hash map was modified while being iterated over, which would be undefined behavior.

**Comment by betawaffle** [comment]
This seems to happen reliably for me when getting `@typeInfo` for a C import.

**Comment by FireFox317** [comment]
With my PR #4435 this only crashes when doing `_ = @typeInfo(@This()).Struct.decls[0];`, actually accessing the decls slice forces it to be resolved and just doing `.decls` doesn't resolve it yet.
