### ISSUE TITLE
self-host building musl, glibc, and mingw-w64

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#4313]
Once we have the "cache hash" API self-hosted (See #4311), another big win is self-hosting the code that builds zig's libcs from source, for the target platform.

This provides several benefits:

 * There will only be one implementation, across stage1 and self-hosted, rather than two. Less room for bugs. Improving and maintaining the self-hosted version will be work that benefits both stage1 and self-hosted.

 * `zig translate-c` is already self-hosted. Once building libc is also self-hosted, creating the clang command line can be moved (at least partially) to self-hosted as well. Combined with making linking self-hosted (see #4314), this will make it possible to self-host the drop-in C compiler feature (see #3089).

 * multi threading. The C++ stage1 compiler is single-threaded. However, the Zig Standard Library and self-hosted compiler is designed to take advantage of multiple CPUs & cores. With building of libc self-hosted, it's a straightforward path to make compilation of C objects multi-threaded, taking full advantage of hardware resources.

**Comment by vedantroy** [comment]
I've been investigating this issue. The question I have is, how much code should be ported from C++ to Zig? For example: the `build_musl` and `build_libcxx` call the function `codegen_build_and_link`.

Should this function also be ported from C++ to Zig? (I don't have good intuition for which functions should stay in C++ and which functions should be ported to Zig).

**Comment by andrewrk** [comment]
In general, as much code should be moved from C++ to zig as possible. The only limitation is when doing so would introduce a cyclic dependency.

As an example the reason translate-c can be self hosted is that the self hosted compiler does not use the `@cImport` feature.

Likewise, the zig code that gets compiled into stage1 does not need to be linked into an executable, only an object file or static library.

Hope that helps, happy to discuss more if you have any other questions.

**Comment by andrewrk** [comment]
Landed in fe117d9961c3622fda5c359733d01de686509af0.
