### ISSUE TITLE
function pointer as C structure member cannot use as function in Zig

### ISSUE THREAD

**Issue by dannypsnl** [ziglang/zig#4315]
Example code:

```zig
const c = @cImport({
    @cInclude("lxc/lxccontainer.h");
});
const warn = @import("std").debug.warn;
// main
const container = c.lxc_container_new(c"test-container", null);
if (container == null) {
    return LXCError.NewFailed;
}
container.*.destroy(container);
```

The problem was lxc using fields of structure `lxc_container` to operate itself, so I need to access function pointer via member access and call on it, but seems compiler didn't accept the type:

```
test.zig:42:16: error: type '?extern fn([*c].cimport:8:11.struct_lxc_container) bool' not a function
    container.*.destroy(container);
```

Version:

```
$ zig version
0.5.0
```

reference:

- https://linuxcontainers.org/lxc/documentation/

**Comment by Vexu** [comment]
`destroy` is an optional function pointer, tou need to unwrap it before you can call it: `container.destroy.?(container)`.

**Comment by Rocknest** [comment]
Compile error should be more helpful in this case

**Comment by JesseRMeyer** [comment]
> Compile error should be more helpful in this case

While a substantial undertaking, users always appreciate both an error and correction advice from their compilers, e.g, 'Did you mean ... ?'  After all, Zig evangelizes that you should spend your time debugging your program and not your understanding of your (simple) programming language.

**Comment by dannypsnl** [comment]
> `destroy` is an optional function pointer, tou need to unwrap it before you can call it: `container.destroy.?(container)`.

Hi, thanks for helping, didn't know Zig can do that. Also thanks @Rocknest, @JesseRMeyer for looking this. 

I think here, `?extern fn([*c].cimport:8:11.struct_lxc_container) bool` is not a function type and using `?` to take it makes sense, didn't know how can compiler message be improved. Probably checking candidate, for example here we can get function type after eliminate `?`, to avoid too heavy loading and make compiling be slow, maybe add some limitation like only eliminate 2 levels, so `?????fn` won't be taken. I haven't look into the implementation, but the message already pretty nice for many cases. I would close the issue for now. Feel free to reopen or create a new one for the message problem.
