### ISSUE TITLE
[Question / proposal-maybe] resolving the @typeName of types in struct fields (eg. for ad-hoc/non-pkg-based sub-namespacing)

### ISSUE THREAD

**Issue by metaleap** [ziglang/zig#4330]
Consider:

```zig
const std = @import("std");

const Group = .{
    .Type1 = enum{foo, bar, baz},
    .Type2 = union(enum) { a: u16, b: i16 },
};

pub fn main() void {
    std.debug.warn("{}\n", .{ @typeName(Group.Type1) });
    std.debug.warn("{}\n", .{ @typeName(Group.Type2) });
}
```

Output:

```
Group
Group
```

Not terribly critical in the current scheme of things, but would suggest as an "around-or-post 1.0 contributor-friendly rather-nice-to-have" longer-term to look into. (Or when self-hosting-comp is up and such subtleties / corner-cases become more immediately attackable.)

Or maybe it's just an accepted limitation of `typeName`, then feel free to close. Referencing in the field value another type name instead of anon/inline type-def "works" after all --- although then maybe `typeName` should rather act like with any other anon/inline type-def not ever anywhere named!

**Comment by JesseRMeyer** [comment]
Shouldn't the output be:

```
enum
union
```

(or more specialized variants thereof) ?

**Comment by metaleap** [comment]
Yeah what I would expect by default as of today --- although the other, "future proposal/suggestion" half of this issue would be whether to consider a (sugary, admittedly) `Group.Type1` or just `Type1` etc. Up for discussion. Given that structs are Zig's namespacing device, and that it is unlikely that any callers of `@typeName` "parse" its results (in the various forms) for extracting some specific meaning.. could be worthwhile + non-harmful.

**Comment by JesseRMeyer** [comment]
Not quite seeing the use-case.  If you want the parent type, why are you asking about it from its members?

**Comment by metaleap** [comment]
A use-case? Here's a funky namespace of co-related struct types, to be sep'd out from others in the same file...

```zig
pub const OurApiSpec = struct {
    IncomingRequest: union(enum) {
        negate: fn (Arg(i64)) Ret(i64),
        hostName: fn (Arg(void)) Ret(String),
        envVarValue: fn (Arg(String)) Ret(String),
    },
    OutgoingRequest: union(enum) {
        pow2: Req(i64, i64),
        rnd: Req(void, f32),
        add: Req(struct {
            a: i64,
            b: i64,
        }, i64),
    },
    IncomingNotification: union(enum) {
        timeInfo: fn (Arg(TimeInfo)) void,
        shuttingDown: fn (Arg(void)) void,
    },
    OutgoingNotification: union(enum) {
        envVarNames: []String,
        shoutOut: bool,
    },
};
```

Then later for logging / prints / tracing / compileError messages etc.pp. you want to see either `OutgoingRequest` or `OurApiSpec.OutgoingRequest`, not for all 4 types the same `OurApiSpec`.

**Comment by JesseRMeyer** [comment]
Ah, sorry. I got @TypeOf and @typeName confused.  I agree the ability to output the name of the identifier, and further context (like enclosing struct name, etc) associated with a type is important for Zig to provide.  I don't know, but I would've thought that would be possible already.
