### ISSUE TITLE
Proposal: expose tuple type declarations

### ISSUE THREAD

**Issue by fengb** [ziglang/zig#4335]
We now have anonymous tuples, but they can only be created at runtime using the `var` type. While this satisfies "varargs" and coercion to arrays / vectors, we still cannot define a tuple type at comptime.

Potential syntax:

```zig
const Point = tuple{ i32, u32 }; // explicit, but adds a keyword
const Point = struct{ @"0": i32, @"1": u32 }; // matches the backend structure but feels pretty gross
```

Packed tuples should also be possible since it can represent in memory data structures pretty well, like manually managed stacks.

## Accepted syntax

Per https://github.com/ziglang/zig/issues/4335#issuecomment-580842164:
```zig
const Point = struct{ i32, u32 };
```

**Comment by fengb** [comment]
Another usecase for declared tuples: emulating multiple returns.

**Comment by metaleap** [comment]
Do you foresee another `.Tuple` (vs `.Struct`) `TypeInfo` / `TypeId` for that (would intuitively advise against such) or have it more of a sugar building on the existing struct internals incl the existing "0", "1" etc auto-naming?

**Comment by andrewrk** [comment]
`@typeInfo` for tuples is the same as structs, but there will be an added flag `is_tuple: bool`

**Comment by metaleap** [comment]
Pondering it some more..

Hate to bikeshed, truly do usually, but would advise an alternative to "yet another keyword": extend the lang syntax for `struct {i32, bool, void}` to be valid and turn into an `is_tuple` struct (as we know it exists underlying already from `.{10, "hi", false}` ) --- with the easy-to-intuit rule that either all fields must be named or all must be unnamed. 

What bugs me about a new keyword? What I liked about Zig is that there is kinda mostly / overall / in-spirit _one_ moniker for _one_ underlying-mechanism/operational-semantic, so to speak. Now you'd have to explain in docs/chats/blogs/teaching-materials/talks at length "there are unions, they are like this, then there are structs, they are like that, and btw but there's also another special kind of structs without field names, so there are in addition to unions and structs also tuples but they're really structs under the hood".

**Comment by andrewrk** [comment]
@metaleap 's ammendum https://github.com/ziglang/zig/issues/4335#issuecomment-580842164 is also accepted

**Comment by Rocknest** [comment]
I don't understand what is being proposed. Is it a special way to declare struct without specifying field names? What is a packed tuple, i can't imagine that, there are no examples to visualise it. 

 As for use case "emulating multiple returns": i would expect multiple returns to be named, as arguments to a function must have names. e.g:
`getPosition() struct {x: f32, y: f32}`
`divide(num: u64, denom: u64) struct {result: u64, remainder: u64}`
`getRegs() struct {bp: usize, ip: usize}`

Also would anon list literals be coerceable to 'tuples'? @LemonBoy is saying that it should not be allowed https://github.com/ziglang/zig/issues/4148#issuecomment-580711878.

**Comment by LemonBoy** [comment]
> I don't understand what is being proposed.

Nor you have understood what I was saying as I was talking about coercing anonymous array literals to named struct literals where you really want to specify what field are you assigning a value to.

**Comment by Rocknest** [comment]
@LemonBoy your argument that it is a time-bomb does not justify your point, however i understand why it would not be allowed - "favour reading code over writing code"

**Comment by metaleap** [comment]
> Edit: how do 'tuples' fit into this zen?

@Rocknest understand this: we already have tuple literals: `.{ 10, "20", 3.0 }` (that creates under the hood the appropriate struct type with 3 fields named "0" through "2"), just no way to express in code the type of such a thing in current syntax. 

The proposal is to have such a facility in the grammar.

**Comment by Rocknest** [comment]
@metaleap as i said https://github.com/ziglang/zig/issues/4335#issuecomment-580850792 i wonder what the use case would be, is that _really_ justified?

**Comment by Sobeston** [comment]
I feel like a separate key word may cause more confusion than it's worth - new users would likely see it and assume it's a different data structure. I like the idea of making a struct type without specifying field names though ie stuct{u32, []u8}. Nice for function return types. +1

**Comment by metaleap** [comment]
@Rocknest  from my experience, unnamed-field tuples rarely make it into a somewhat-matured final "production-grade" code product to any great extent. **But** IMHO they're invaluable just for more-rapidly-iterating alone already, as you restructure fn signatures quickly and re-mold your data/flow structurings at an ideally fast pace. That alone is a valid _programmer_ use-case, making the facility fit for every _programming_ language  =)

Commonly seen is also the desire for what's hi-falutingly described as "heterogenous look-and-feel-like arrays" say Vec3[0] through Vec3[2] get accepted by compiler / type-checker, turning into field-accesses, even going as far as allowing loops. I won't argue with that, though in _my_ practice it doesn't really come up.

**Comment by fengb** [comment]
@Rocknest here's a real-ish example that I've encountered building my wasm interpreter:

```zig
var stack: [65536]u8;

pub fn i32Store(self: *core.Instance, pop: packed tuple{ u32, i32 }) void {}
pub fn i64Store(self: *core.Instance, pop: packed tuple{ u32, i64 }) void {}
```

A packed tuple is able to represent this data directly mapped inside of the memory space. Without packing, I'd have to copy the data out (which is fine but a little inconvenient), and without tuples I'd have to emulate it with struct fields (which is fine but I'd have to invent some incrementing name and have adhoc tuples).

We already have tuples in the language because it was needed to support varargs. This proposal simply gives it a name and a way to declare the type.

**Comment by Rocknest** [comment]
>`pub fn i32Store(self: *core.Instance, pop: packed tuple{ u32, i32 }) void {}`

And here i am reading this code having no idea what first and second integers represent. Are you sure they do not need names?

**Comment by fengb** [comment]
The shared invocation context only knows the position and types. Inside the function, we can apply conceptual names, but exposing it means I cannot share the parsing logic (which is based solely in bytes).

Although thinking about it, I can possibly rely on a packed struct and iterating through the fields at comptime to generate the parser...

**Comment by user00e00** [comment]
I feel like a built-in function would be the best way to define tuple types. Tuples are just a special case of structs after all, so special syntax might be a bit redundant.

```zig
const MyTuple = @TupleType(u32, i32);
const MyTuple2 = @TupleType(u64,u32,bool);
const MyPackedTuple = @PackedTupleType(u32,i32);

const x : MyTuple = .{32, -5};
const y : MyTuple2 = .{1,2,false};
```

**Comment by fengb** [comment]
Another crazy idea with tuples: we can sorta create generic structs at comptime:

```zig
pub fn Soa(comptime Struct: type) type {
    const fields = std.meta.fields(Struct);
    const Data = switch (fields.len) {
        1 => struct { []fields[0].field_type },
        2 => struct { []fields[0].field_type []fields[1].field_type },
        3 => struct { []fields[0].field_type, []fields[1].field_type, []fields[2].field_type },
        else => @compileError("TODO"),
    }

    return struct {
        pub fn initCapacity(allocator: *self.mem.Allocator, cap: usize) !Self {
            var result = Self{ .data = undefined, .allocator = allocator };
            inline for (fields) |field, i| {
                // This type of generic access is currently inaccessible
                // since we can't generate field names
                self.data[i] = try allocator.alloc(field.field_type, cap);
                errdefer allocator.free(self.data[i]);
            }
            return result;
        }
    }
```

**Comment by Rocknest** [comment]
@fengb is this what you are trying to achieve? 
https://gist.github.com/Rocknest/6d07cec388036fcdf07fb4760cb92466

**Comment by frmdstryr** [comment]
I like the separate keyword because it makes the intent more clear but am fine with either.

**Comment by BarabasGitHub** [comment]
I've never seen really good use cases for tuples to be honest. In C++ they're super confusing, especially the way they're used in the standard library. In Python it's always tricky because you have to remember what goes where as it doesn't check anything for you. And then you want to print it because you have a bug somewhere and you're better of using `namedtuple` (which is like a struct, except you can't change the values once assigned).
I'm not opposed to it, but I do doubt it's usefulness.

As for multiple return values. I'm also not too fond to use tuples for that. We don't have tuples for multiple input values either, do we? If Zig wants multiple return values (and I do think that could be useful) then imho it would be better to name them (maybe name all return values?) and somehow refer to them inside the function.

**Comment by fengb** [comment]
Tuples were already added to replace vararg inputs. This proposal only exposes the ability to name the type so you can have declare constrained tuples instead of being always generic.

**Comment by Rocknest** [comment]
But zig's 'tuples' are really just annonymous structs. This proposal goes in somewhat opposite direction.

**Comment by theInkSquid** [comment]
How would this work with bigger tuple struct definitions? Like if I wanted a member function:

```
const MyTuple = struct  {
    i32,
    []const u8,

    fn foo(this: @This()) void { ... }
}```

Woudl I do this just like a struct currently?

**Comment by pfgithub** [comment]
@Rocknest tuples have the added abilities that they can be looped over, concatenated, and items can be accessed with array indexing syntax. 

```zig
.{1, 2} ++ .{3}
inline for(.{1, 2, 3}) |item| {}
(.{1, 2, 3})[2]
```

**Comment by tadeokondrak** [comment]
RIght now enums, structs, and unions share the same syntax.
`enum { u1, u2, u3 }` is parsed as 3 identifiers, thus so is `struct { u1, u2, u3 }`
I think the solution is just to give structs its own syntax, but it's something to consider here.

**Comment by Rocknest** [comment]
Consider closing this since #6416 its possible to create tuple types in userland

**Comment by cindRoberta** [comment]
I think it would be better to precede with . named fields, this way:

```zig
const Person = struct {
  name: []const u8,
  age: u8,
  .height: f16,
  .weight: f16
};

pub fn main() void {
  const Cumpade = Person { "Cumpade", 51, .height = 1.71, .weight = 97.8 };
}
```

**Comment by ifreund** [comment]
@ominitay there is no ambiguity in the sense of ambiguity in a formal grammar. In fact, the formal zig grammar here already accepts both `struct { i32, Foo }` and `struct { a: i32, b: Foo }`. https://github.com/ziglang/zig-spec/blob/master/grammar/grammar.y

**Comment by ominitay** [comment]
Yes, but then what type does `struct {}` represent? Is it a tuple or a struct? You haven't addressed what I'm saying at all. @ifreund

**Comment by ominitay** [comment]
Again, I'm saying that the formal grammar is ambiguous. I'm saying that what `struct {}` actually means hasn't been considered, and means that the proposed syntax can't actually express either an empty struct or an empty tuple.

**Comment by ifreund** [comment]
That's not a grammar ambiguity, it's orthagonal to the grammar. If you're curious what an ambiguity in the grammar would look like see this page: https://en.wikipedia.org/wiki/Ambiguous_grammar. Note that a Parsing Expression Grammar like Zig's here is by definition unambiguous: https://github.com/ziglang/zig-spec/blob/master/grammar/grammar.y.

What you are talking about is ambiguity later in the compiler pipeline. A similar ambiguity already exists with regards to the type of `.{}` which can be an array, tuple, or struct depending on the context.

My take is that it doesn't really matter whether `@typeInfo()` says `struct {}` is a tuple or not as long as it's well defined and consistent.

**Comment by ominitay** [comment]
> That's not a grammar ambiguity

Oop, I missed the very important word "not" between the words "I'm" and "saying" in the first sentence, completely changing the meaning. I'm completely agreed with you in that regard.

> What you are talking about is ambiguity later in the compiler pipeline.

Sure, that is why I'm asking for clarification here. If we are sticking with the shared keyword approach, then we need to decide whether `struct {}` is a tuple or struct. I guess that for it to be a tuple would make sense, considering that the type of `.{}` is a tuple.

**Comment by foobles** [comment]
I agree that tuples just being a special case of structs, and `struct{}` vacuously being a tuple in addition to being a struct makes the most sense.

**Comment by ominitay** [comment]
> I agree that tuples just being a special case of structs, and `struct{}` vacuously being a tuple in addition to being a struct makes the most sense.

You can't have it be two types at once. Empty structs don't coerce to empty tuples either; this might be a non-issue, but if it is a problem, then this may need to be implemented.

**Comment by leecannon** [comment]
Tuples already are structs, they just have a true bool in `@TypeInfo` instead of a false one.
Due to extra capabilities of tuples (concatenation, looping over, etc) it would make sense that `struct{}` would have the tuple boolean set to true.

**Comment by ominitay** [comment]
> Tuples already are structs, they just have a true bool in `@TypeInfo` instead of a false one.
> Due to extra capabilities of tuples (concatenation, looping over, etc) it would make sense that `struct{}` would have the tuple boolean set to true.

We are in agreement on this :)

**Comment by Vexu** [comment]
An alternative for this which doesn't require new syntax would be to allow tuples with all elements being type `type` to coerce to tuple types:
```zig
test {
    const T: type = .{ type, u32 };
    const t: T = .{ bool, 2 };
}
```

**Comment by ominitay** [comment]
@Vexu How would you then suggest we express a packed or extern tuple type then? And how would we express field alignment?

**Comment by Vexu** [comment]
There is `@Tuple` (or `@Struct`/#10710) and #8643. In the common case tuple fields aren't going to be aligned and at least currently packed/extern tuples do not exist in stage2.

**Comment by ominitay** [comment]
If you think that `@Tuple` is enough for this, then what do you think is the point of this feature at all? Edge cases matter, we should have a broadly applicable solution. Currently packed/extern tuples doesn't exist in stage2 yes. Why does that matter at all to this discussion? It has already been agreed that they will do.

**Comment by Vexu** [comment]
> If you think that `@Tuple` is enough for this, then what do you think is the point of this feature at all?

That was a typo, I meant using `@Type` with `is_tuple = true` for making more complex tuples.

> Edge cases matter, we should have a broadly applicable solution.

We already have multiple ways to create types, why does this new thing need to be able to all the same things as `@Type` especially they usually won't be needed.

> Currently packed/extern tuples doesn't exist in stage2 yes. Why does that matter at all to this discussion?

You mentioned it.

> It has already been agreed that they will do.

I didn't know that, when did that happen?

**Comment by ominitay** [comment]
> That was a typo, I meant using `@Type` with `is_tuple = true` for making more complex tuples.
> We already have multiple ways to create types, why does this new thing need to be able to all the same things as `@Type` especially as they usually won't be needed.

I forgot to mention that your solution would make it impossible for tuples to be namespaces, which is a feature that Andrew has agreed is intended, and makes sense considering enums and structs can.

Additionally, I don't see your proposal fitting in with existing precedent. Tuples are effectively structs, so why should they be declared any differently? To me, it doesn't really seem like it fits in with the language as it is today.

> You mentioned it.

My point here was that this is a proposal — we are considering things that don't exist.

> I didn't know that, when did that happen?

I remember Andrew talking about it on Discord at some point, and @fengb did include them as part of the proposal.

**Comment by Karmylr** [comment]
> 声明的元组的另一个用例：模拟多个返回。

After https://github.com/ziglang/zig/issues/4335, Can users use tuple to return multiple values from a single function now?

**Comment by nektro** [comment]
always could using `std.meta.Tuple`. this proposal rather simplified and unified their construction

**Comment by Karmylr** [comment]
> Another usecase for declared tuples: emulating multiple returns.

After https://github.com/ziglang/zig/issues/4335, Can users use tuple to return multiple values from a single function now?

**Comment by Karmylr** [comment]
> > After #4335, Can users use tuple to return multiple values from a single function now?
> 
> This has always been possible simply by returning a struct from a function. This isn't much different now except you no longer have to specify field names:
> 
> ```zig
> const std = @import("std");
> 
> fn x() struct { u8, u16 } {
>     return .{ 5, 10 };
> }
> 
> pub fn main() void {
>     const thing = x();
>     std.debug.print("{}, {}\n", .{thing.@"0", thing.@"1"});
> }
> ```
> 
> I wouldn't always recommend it as it can decrease readability (what is `thing.@"0"`?). Tuples definitely have its use cases though.

Is the performance overhead of doing this bigger than using tuple?
