### ISSUE TITLE
Missing compile error for reassigning parameter

### ISSUE THREAD

**Issue by jayschwa** [ziglang/zig#4350]
Possibly related to #788.

I have a piece of code that processes smaller sequential slices of a larger slice. Rather than getting a slice of length zero at the end, I get a segmentation fault.

```zig
const std = @import("std");

const CHUNK_LEN = 2;

fn slice_to_zero(input: []const u8) void {
    while (input.len > 0) {
        const take = std.math.min(input.len, CHUNK_LEN);
        _ = input[0..take]; // Imagine this slice chunk is used for something
        input = input[take..];
    }
}

test "slicing down to zero length" {
    slice_to_zero("");
    slice_to_zero("foo");
}
```

**Comment by LemonBoy** [comment]
```zig
input = input[take..];
```
This is illegal as parameters are `const` by default => #4015 

```zig
_ = input[0..take];
```

This is a long-standing issue that affects many builtins (and also the slice operator), when the destionation is `_` the codegen gets a `nullptr` for the `result_loc` and so it segfaults. I'm pretty sure there are a few tickets open about that.

**Comment by jayschwa** [comment]
It looks like my code works if I create a new slice variable from the const slice parameter. Lack of compiler error was allowing me to footgun. Thanks.

**Comment by andrewrk** [comment]
I wasnt aware of this missing compile error, so I'm going to keep this open to track if that's ok

**Comment by dbandstra** [comment]
Linking #3800 as well
