### ISSUE TITLE
Functions which return void are not discoverable in VS's watch window.

### ISSUE THREAD

**Issue by JesseRMeyer** [ziglang/zig#4360]
```zig
fn test_void() void {
    return;
}

fn test_nonvoid() u32 {
    return 0;
}
```

![asdfasdfasd](https://user-images.githubusercontent.com/5846309/73599626-6b976300-4513-11ea-88fa-60eba55be7a6.PNG)

I don't know if this has to do with VS's pdb parsing or Zig's pdb output or something else.

I'm seeing this behavior inspecting a vtable which contains many void-returning functions, all of which are undiscoverable, despite being callable / functional.

![](https://i.imgur.com/gdh3WFw.png)

![](https://i.imgur.com/ojsygpC.png)

**Comment by LemonBoy** [comment]
Can you check if #4362 solves your problem?

**Comment by JesseRMeyer** [comment]
I currently rely on master for testing (merged) changes.  I'll report back when it's merged and part of a nightly,

**Comment by LemonBoy** [comment]
The patch has landed in master!

**Comment by JesseRMeyer** [comment]
Noticed. =) I'll try this after work.
