### ISSUE TITLE
stdlib time.sleep/os.nanosleep function return type / feedback

### ISSUE THREAD

**Issue by sambattalio** [ziglang/zig#4392]
I was looking at the [standard library](https://github.com/ziglang/zig/blob/3e7c02edc183a1b869c004d89debcefbd74bcdeb/lib/std/os.zig#L2648) to invoke the sleep system call, and it seems that it does not provide any feedback if there is a spurious wakeup (eg. leftover nanoseconds to sleep, or error code). 
Is this something that is intended, or is it a possible issue for contribution (I would be more than happy to take a look at it)?

Thanks!

**Comment by daurnimator** [comment]
On spurious wakeups the function sleeps for the remaining time.
What code would really care if there was a spurious wakeup?

**Comment by sambattalio** [comment]
Oh my gosh, I misread docs I think. Thanks for responding 👍

**Comment by andrewrk** [comment]
Think twice before calling sleep(). It's nearly always a bug.
