### ISSUE TITLE
build.zig installRaw() does not use setOutputDir()

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#4393]
0.5.0+25cbee0b8
    
    pub fn build(b: *Builder) void {
        const arch = builtin.Arch{ .thumb = builtin.Arch.Arm32.v6m };
        const environ = builtin.Abi.none;
        const exec_name = "main";
        const mode = b.standardReleaseOptions();
        const os = builtin.Os.freestanding;
    
        const exe = b.addExecutable(exec_name, "mission00_mission_selector.zig");
        exe.setBuildMode(mode);
        exe.setLinkerScriptPath("linker.ld");
        exe.setOutputDir(".");
        exe.setTarget(arch, os, environ);
        exe.installRaw("main.img");
        b.default_step.dependOn(&exe.step);
    }
    
    const Builder = std.build.Builder;
    const builtin = @import("builtin");
    const std = @import("std");
    
    $ find . -name main.img
    ./zig-cache/bin/main.img

**Comment by mlarouche** [comment]
Will look into it very soon

**Comment by andrewrk** [comment]
`setOutputDir` is deprecated, I think you will have a better time if you do not use it. Instead integrate with the "install" step.

**Comment by markfirmware** [comment]
Ok, I am no longer using setOutputDir.
