### ISSUE TITLE
Unreachable in ir_render_bit_cast when passing @bitCast([2]u8, u16) as argument

### ISSUE THREAD

**Issue by frmdstryr** [ziglang/zig#4395]
```zig
const std = @import("std");

pub fn write(data: [2]u8) void {
    std.debug.warn("{}\n", .{data[0]});
    std.debug.warn("{}\n", .{data[1]});
}

pub fn main() void {
    var x: u16 = 0xFFAA;
    var bytes: [2]u8 = @bitCast([2]u8, x);
    // write(bytes); // no worries
    write(@bitCast([2]u8, x)); // Boom
}
```

Write `bytes` works fine but passing the @bitCasted value directly throws a compile error 
```
Unreachable at /deps/zig/src/codegen.cpp:3287 in ir_render_bit_cast. This is a bug in the Zig compiler.
```

https://godbolt.org/z/dPSfR-

Edit: It also works fine if I cast a packed struct instead of a u16.

**Comment by LemonBoy** [comment]
`[2]u8` is a pointer type while the RHS is a scalar type,`@bitCast` is not really a good choice here.

**Comment by frmdstryr** [comment]
I played around but couldn't figure out how to do it.  Other variations I tried that don't work

 -   `@ptrCast([2]u8, &x)`  - gives `error: expected pointer, found '[2]u8'` which is inconsistent with the bitcast thinking that is [2]u8 a ptr, is it or not?
 -   `@ptrCast(*[2]u8, &x)`  - gives  `error: cast discards const qualifier`. The compiler doesn't allow `[2]const u8` or `const [2]u8` so that doesn't work either



So is `var buf = [n]u8` a pointer or not? My understanding as that it is NOT a pointer unless it's either sliced or use &buf... so I'd say that the bitcast should work but LLVM doesn't allow it (why??).

I modified the source and made it try to just `bitcast u16 to [2xu8]` and `bitcast to [2xu8]*` and llvm generates invalid IR with "Invalid bitcast" in both cases.   
 

Any suggestions? (other than just making a new fn that uses u16 and does a >> and &)

**Comment by LemonBoy** [comment]
> which is inconsistent with the bitcast thinking that is [2]u8 a ptr, is it or not?

Some objects are actually codegen'd as pointers (think `?*T`), at the Zig level only the "effective" pointer types matter.

> The compiler doesn't allow [2]const u8 or const [2]u8 so that doesn't work either

You probably want to use `bytesToSlice` here.

> so I'd say that the bitcast should work but LLVM doesn't allow it

An array is just a pointer + compile-time metadata, the length, and so you can't really bitcast scalars to arrays. What should `@bitCast([1]u8, @as(u8, 1))` do?

**Comment by frmdstryr** [comment]
I think some of my thinking here seems to align with https://github.com/ziglang/zig/issues/2955

> so you can't really bitcast scalars to arrays What should `@bitCast([1]u8, @as(u8, 1))` do? 

My (probably misguided) understanding of bitcast is that it's just reinterpreting the type of the memory while leaving the address and contents untouched. As long as the actual memory size is the same I don't see why the compiler should care as long as the address isn't changed.  

I'd interpret that as an address of operator just it lets you then use slice access to the pointer to wherever the 1 is actually located in memory.

Most likely the compiler is trying to prevent me from shooting myself, and I'm trying to tell it not to haha.

**Comment by BarabasGitHub** [comment]
I also ran into this.

This works:
```
fn extractOneByte(a: f64) u8 {
    const x = @bitCast([8]u8, a);
    return x[1];
} 
```

This is broken:
```
fn extractOneByte(a: f64) u8 {
    return @bitCast([8]u8, a)[1];
}
```
