### ISSUE TITLE
Slicing `[*c]T` returns `[]allowzero T`

### ISSUE THREAD

**Issue by fengb** [ziglang/zig#4401]
```zig
pub fn main() void {
    var buf: [10]u32 = undefined;
    const clients = @ptrCast([*c]u32, &buf);
    @compileLog(@TypeOf(clients[0..1])); // []allowzero u32

    for (clients[0..1]) |*cl| {
        @compileLog(@TypeOf(cl)); // *allowzero u32
    }

    for (clients[0..1]) |cl| {
        @compileLog(@TypeOf(cl)); // compile error trying to dereference *allowzero
    }
}
```

**Comment by fengb** [comment]
Seems like this cast has always existed (at least since 0.5.0), but it's now causing major problems due to other weird allowzero bugs: https://github.com/ziglang/zig/issues/4361

**Comment by andrewrk** [comment]
Proper behavior here is that slicing a C pointer will assert (runtime safety) the address is not zero, and then return a normal zig slice type.

**Comment by alexnask** [comment]
Looking into this issue later today.
