### ISSUE TITLE
The heap corrupts when freeing sentinel slice

### ISSUE THREAD

**Issue by JoaoSilveira** [ziglang/zig#4413]
```zig
const std = @import("std");

pub fn main() void {
    var heap = std.heap.HeapAllocator.init();
    defer heap.deinit();

    var alloc = &heap.allocator;

    const arr = std.unicode.utf8ToUtf16LeWithNull(alloc, "Hello") catch return;
    defer alloc.free(arr);

    std.debug.warn("{} {}\n", .{ arr.len,  arr[0..].len});
}
```

The following line `defer alloc.free(arr);` gives me an unhandled exception:

> Critical error detected c0000374
> 
> Unhandled exception at 0x00007FFAB1EF9269 (ntdll.dll) in main.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFAB1F627F0).

But changing the line to `defer alloc.free(arr[0..]);` works just fine.

Zig Version: 0.5.0+b55bc5eb2
Os: Windows 10 version 1903 build 18362.592

**Comment by andrewrk** [comment]
I havent yet inspected the code but based on reading the issue I'm guessing a bug in std.unicode.utf8ToUtf16LeWithNull

**Comment by JoaoSilveira** [comment]
Actually I found the problem, it's in the `Allocator.free`. The line [`const bytes_len = bytes.len + @boolToInt(Slice.sentinel != null);`](https://github.com/ziglang/zig/blob/b55bc5eb266f2dc62cf520e8b572893adf5f979c/lib/std/mem.zig#L236) is the problem. When creating a string literal (e.g. `"Hello"`) the sentinel isn't counted in the slice length, but when created externally it is. It is, the literal `"Hello"` length is 5 but `std.unicode.utf8ToUtf16LeWithNull(alloc, "Hello")` is 6. Furthermore, `bytes.len + @boolToInt(Slice.sentinel != null)` seems to add just a byte to the byte array, I guess it should add the size of the slice's type, like `const bytes_len = bytes.len + if (Slice.sentinel != null) @sizeOf(Slice.child) else 0`

**Comment by LemonBoy** [comment]
Interesting, this problem surfaces with `HeapAllocator` because it stores some metadata right after the allocated block (ugh) and so the sentinel ends up corrupting it.

**Comment by andrewrk** [comment]
Thanks @JoaoSilveira, you are correct on both counts. I went ahead and pushed your fixes to master branch.
