### ISSUE TITLE
__divsi3 and __udivsi3 issues on Thumb1 

### ISSUE THREAD

**Issue by mlarouche** [ziglang/zig#4415]
__divsi3 and __udivs3 give me wrong results with Thumb1 architecture

See this gists for repro steps: https://gist.github.com/mlarouche/7b966b42a8ddd844cb610c3fa16189b0

cc @LemonBoy

**Comment by LemonBoy** [comment]
Good catch, I've fixed the clzsi2 implementation and now it passes all the tests.
Sorry for the inconvenience!

**Comment by mlarouche** [comment]
That was fast! Thanks a bunch 😄
