### ISSUE TITLE
should we add -D_FORTIFY_SOURCE=2 to BuildModeDebug ?

### ISSUE THREAD

**Issue by mikdusan** [ziglang/zig#4444]
should we add `-D_FORTIFY_SOURCE=2` to `BuildModeDebug`? It's currently enabled only in `BuildModeSafeRelease`

https://github.com/ziglang/zig/blob/08666a057ac9738e926df7ac02932043ae2d5997/src/codegen.cpp#L9258-L9282

**Comment by daurnimator** [comment]
I'm also not sure if it needs to be conditional on linking libc for the `--release-safe` case?
e.g. can a byte-by-byte copy to a stack-allocated array end up as a call to `__builtin___memcpy_chk`?

**Comment by andrewrk** [comment]
I believe this flag requires `-O2` in order to function. It's common practice for debug builds of C software to not have this feature enabled. Pretty sure status quo is correct.
