### ISSUE TITLE
Suggestion: enforce "predictably interpretable" compiler note-to-error message orderings

### ISSUE THREAD

**Issue by metaleap** [ziglang/zig#4461]
I would propose that it would be (at least for editor/lang tooling authors) highly beneficial if compiler **`note`** messages such as `note: referenced here` would be ensured/enforced to always immediately follow the prior `error` message they actually refer to, so that the correlation can be interpreted into some diagnostics UX or refactoring suggestion popup or such.

That such co-relatable ordering is currently often but not always the case is shown in this situation where the **`note`** comes in one-error-too-late:

![2020-02-14-195312_3840x2160_scrot](https://user-images.githubusercontent.com/22109/74559089-e032be80-4f63-11ea-833c-a7788e922b80.png)

**Comment by Vexu** [comment]
The one error per decl design of the self-hosted compiler forces this to be done correctly.
