### ISSUE TITLE
resolve the "hack" in the self-hosted parser regarding async fn calls

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#4472]
https://github.com/ziglang/zig/blob/b15958c557d3b29c8d4cee9951a8bfd30c215482/lib/std/zig/parse.zig#L1136-L1144

I'm not really sure what's going on here, or whether this even is still a problem after the async functions rewrite. This issue is to check the [grammar spec](https://github.com/ziglang/zig-spec/tree/master/grammar) and make sure it is sane, and fix up this parser code to not have the word "hack" or "TODO" in the comments.

**Comment by greenfork** [comment]
It looks like this issue was fixed in 4dca99d3f6b732c415d270f0c97def144ed6d3b7.
