### ISSUE TITLE
Stage1 parser should reject extern fn with a body

### ISSUE THREAD

**Issue by lucascharlesmyers** [ziglang/zig#4473]
```
$ zig id
SZXyXjHOivXA_eiFTQQ42bYwcPpxZle8Fjos7ssukmSwmjirA8XRxlxp32WwIY4-

$ zig version
0.5.0+b15958c55
```

The compiler seems to have no issue with an `extern` `fn` that has a body provided, e.g.:

```zig
// test.zig
const assert = @import("std").debug.assert;

extern "c" fn definitelyNotInLibC(a: i32, b: i32) i32 {
    return a + b;
}

test "extern fn with body" {
    assert(definitelyNotInLibC(1, 2) == 3);
}
```

```
$ zig test -lc test.zig
All 1 tests passed.
```

My understanding of `extern` was that it acted as a forward-declaration for a symbol defined in another library to be linked to, so I was surprised that it allowed a body to be specified. If I run the above command with `--verbose-llvm-ir`, this is the generated declaration:

```llvm
; Function Attrs: nobuiltin nounwind sspstrong
define internal i32 @definitelyNotInLibC(i32, i32) unnamed_addr #1 !dbg !1757 {
    ...
}
```

which looks to me like the `extern` is being completely ignored as far as linkage goes (but the platform calling convention is being used).

**Comment by andrewrk** [comment]
This is a bug in the parser - now that we have callconv keyword, extern functions no longer can have a body. I believe if you run zig fmt on this it will fix it.
