### ISSUE TITLE
Compiler incorrectly detects dependency loop when using `@typeInfo(@This())` in test

### ISSUE THREAD

**Issue by SpexGuy** [ziglang/zig#4476]
Minimal Repro (tested with 0.5.0 compiler) :

    const DrawCallback = fn (cmd: *DrawCmd) void;
    
    const DrawCmd = struct {
        UserCallback: DrawCallback,
    };
    
    test "bork" {
        //var x: DrawCmd = undefined;
        _ = @typeInfo(@This());
    }

Compiling this yields this error:

    C:\bork.zig:4:19: error: dependency loop detected
     C:\bork.zig:1:22: note: referenced here
     C:\bork.zig:1:1: note: referenced here
     C:\bork.zig:9:9: note: referenced here

If I uncomment the first line in the test block, the program compiles successfully.

(edit: even more minimal test case)

**Comment by FireFox317** [comment]
This passes with #4435

**Comment by marler8997** [comment]
This also causes the dependency loop error:
```zig
test "" {
    @import("std").testing.refAllDecls(@This());
}
```

**Comment by marler8997** [comment]
This one bit me again today.  The original example no longer causes the issue to trigger though, here's a version that still triggers it:
```zig
const DrawCallback = fn (cmd: *DrawCmd) void;
const DrawCmd = struct {
    UserCallback: DrawCallback,
};
comptime { _ = DrawCallback; }
```
