### ISSUE TITLE
std.zig.ast.Node.iterate: unreachable when encountering Node.Asm

### ISSUE THREAD

**Issue by metaleap** [ziglang/zig#4480]
Consider the following snippet that "recursively" (not) iterates over all `Node`s in a `Tree.root_node`:

```zig
    fn gatherNamedDecls(tree: *std.zig.ast.Tree, mem_temp: *std.heap.ArenaAllocator) !void {
        var nodes_stack = try std.ArrayList(*std.zig.ast.Node).initCapacity(&mem_temp.allocator, 128);
        try nodes_stack.append(&tree.root_node.base);

        while (nodes_stack.len > 0) {
            const cur_node = nodes_stack.swapRemove(0);
            var i: usize = 0;
            if (cur_node.id != .Asm) { // would crash into unreachable
                while (cur_node.iterate(i)) |sub_node| : (i += 1)
                    try nodes_stack.append(sub_node);
            }

            switch (cur_node.id) {
                else => {}, // ....
            }
        }
    }
```

Removing the `if (cur_node.id != .Asm)` guard results in the following `unreachable` trace:

```
reached unreachable code
/home/_/a/zig/lib/zig/std/debug.zig:216:14: 0x22a0db in std.debug.assert (wiplangserver)
    if (!ok) unreachable; // assertion failure
             ^
/home/_/a/zig/lib/zig/std/segmented_list.zig:126:19: 0x303576 in std.segmented_list.SegmentedList(*std.zig.ast.AsmInput,2).at (wiplangserver)
            assert(i < self.len);
                  ^
/home/_/a/zig/lib/zig/std/zig/ast.zig:2187:60: 0x2d8d9d in std.zig.ast.Asm.iterate (wiplangserver)
            if (i < self.inputs.len) return &self.inputs.at(index).*.base;
                                                           ^
/home/_/a/zig/lib/zig/std/zig/ast.zig:464:64: 0x2d5df7 in std.zig.ast.Node.iterate (wiplangserver)
                return @fieldParentPtr(T, "base", base).iterate(index);
                                                               ^
/home/_/c/z/zigsess/src/src_file.zig:101:40: 0x2d5186 in zigsess.src.src_file.SrcFile.gatherNamedDecls (wiplangserver)
                while (cur_node.iterate(i)) |sub_node| : (i += 1)
                                       ^
/home/_/c/z/zigsess/src/src_file.zig:87:40: 0x2d4f6f in zigsess.src.src_file.SrcFile.refreshIntel (wiplangserver)
                try me.gatherNamedDecls(me.ast.?, mem_temp);
                                       ^
```

I'd assume in terms of this std lib's API design all iterators may well just return `null` if there's no applicable iteration possible / pertinent. If this assumption is warranted, this issue might be a bug report or a user question asking for their user error, you tell me  =)

To repro the above trace, just iterate into the `root_node` of `lib/zig/std/valgrind.zig`, might happen for others with Asm nodes too or not, but for this one it hits definitely.

**Comment by metaleap** [comment]
@andrewrk happy to PR the correct one of the two only possible fixes here, but let me know which one fits the implicit original intent, can't tell from the current source:

[Line 2189 in asm.zig](https://github.com/ziglang/zig/blob/master/lib/std/zig/ast.zig#L2189) must be 

- either `if (i < self.inputs.len) return &self.inputs.at(i).*.base;` 
- or `if (index < self.inputs.len) return &self.inputs.at(index).*.base;` 

to not trigger the seglist's `assert`.

Well, which one was really intended I simply can't decipher from here  =)

**Comment by andrewrk** [comment]
Should be fixed in master. Thanks for the report :+1:
