### ISSUE TITLE
Proposal: deep deinit() for ArrayList and other collections

### ISSUE THREAD

**Issue by joachimschmidt557** [ziglang/zig#4482]
Right now, as far as I know, if we want to deinitialize an `ArrayList` of some type that needs deinitialization itself, we have to manually iterate through the list:

```zig
const std = @import("std");
const ArrayList = std.ArrayList;

pub fn main() void {
    var x = ArrayList(ArrayList(u8)).init(std.heap.page_allocator);

    // ....

    for (x.toSlice()) |itm| itm.deinit();
    x.deinit();
}
```

Would it make sense to add a function to `ArrayList` which does this for us; e.g. `ArrayList(T).deepDeinit(fn (itm: T) void) void`? This would simplify the code to:

```zig
// ...
x.deepDeinit(ArrayList(u8).deinit);
// ...
```

Of course this could also work for other collections including `HashMap` or `SegmentedList`.

**Comment by andrewrk** [comment]
Unlikely to get accepted. You should make your own context-aware deep deinit function and use that.

**Comment by joachimschmidt557** [comment]
I'll close this issue as I chose to create custom deinit functions for these use cases. If there is any renewed interest, this can be reopened.
