### ISSUE TITLE
Suggestion: "expression value is ignored" error message wording

### ISSUE THREAD

**Issue by Bekwnn** [ziglang/zig#4483]
In 0.5.0, failing to do `_ =` for a function with a return value throws an error like in this example:
```
25:48: error: expression value is ignored
        gameWorld.WritableInstance().KillEntity(self.m_eid);
                                               ^
```
but given the slightly ambiguous positioning of the arrow in this case, I wound up thinking "the parameter is going unused...?" and had forgotten the function returned a bool. I was even already aware of the need to use `_ =` to acknowledge unused return values, but got tripped up by the parameter, arrow position, and wording of the error message.

Wording feels like it could maybe be changed to "resulting value of expression is ignored", an additional note about `_ =`, or some other change to improve clarity on this error.

**Comment by andrewrk** [comment]
In self-hosted it will look like this:

```
25:48: error: expression value is ignored
        gameWorld.WritableInstance().KillEntity(self.m_eid);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
