### ISSUE TITLE
Improve target_can_build_libc to take into account glibc versions

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#4487]
Trying to run tests on my system I now get:
> Build Dependencies...unwind [2] Compile C Objects [8/8] UnwindRegistersSave.S...Unrecognized glibc version: 2.31.0

`target_can_build_libc` logic should be modified to take into account glibc versions. `glibc_load_metadata` can be used to get a list of all versions zig can build, and the target parameter tells the one we want to check for.

Related to #4459

**Comment by andrewrk** [comment]
It might also be nice to add a feature that makes zig choose the newest-available version when the native version is so new that zig doesn't ship with it yet.

**Comment by RossComputerGuy** [comment]
I hope this gets fixed so I can work on my shell for GNOME.

**Comment by andrewrk** [comment]
We need this for sure in 0.7.0 because without it, linking against the native glibc breaks when any distro upgrades to a newer glibc.

**Comment by andrewrk** [comment]
This is solved in master branch so it won't happen again, with the release of glibc 2.33 during the zig 0.7.0 release cycle, however I am leaving the issue open until I have simulated the situation happening to make sure it truly does work.

**Comment by andrewrk** [comment]
Tested with this patch to simulate a new glibc version that zig cannot yet build:

```diff
--- a/lib/std/zig/system.zig
+++ b/lib/std/zig/system.zig
@@ -582,7 +582,7 @@ pub const NativeTargetInfo = struct {
             return error.UnrecognizedGnuLibCFileName;
         }
         // chop off "libc-" and ".so"
-        const link_name_chopped = link_name[prefix.len .. link_name.len - suffix.len];
+        const link_name_chopped: []const u8 = "2.37";
         return std.builtin.Version.parse(link_name_chopped) catch |err| switch (err) {
             error.Overflow => return error.InvalidGnuLibCVersion,
             error.InvalidCharacter => return error.InvalidGnuLibCVersion,
```

```
[nix-shell:~/Downloads/zig/build]$ ./zig build-exe ../test/standalone/hello_world/hello.zig  -lc
warning: zig cannot build new glibc version 2.37; providing instead 2.32

[nix-shell:~/Downloads/zig/build]$ ./hello
Hello, World!
```

Looks good :+1:
