### ISSUE TITLE
Windows format support

### ISSUE THREAD

**Issue by wsdjeg** [ziglang/zig#4489]
Hello, I just run into such issue, in zig compiler do not support dos file format. and it prints: 

![image](https://user-images.githubusercontent.com/13142418/74653435-1621ae00-51c3-11ea-92f5-027a61af273a.png)

**Comment by daurnimator** [comment]
That is intentional. See https://ziglang.org/documentation/master/#Source-Encoding

> Note that Windows line endings (CRLF) are not allowed
