### ISSUE TITLE
assignment to ptrCast and to computation are permitted

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#4490]
pub fn main() void {
        @ptrCast(*usize, &ram.*[0]) = &x;  // (a)
        @ptrCast(*usize, &ram[0]) = &x;    // (b)
        @ptrCast(**usize, &ram[0]).* = &x; // (c)
        ram[0] = @ptrToInt(&x);            // (d)
    }

    var x: usize = 8;

    const ram = @intToPtr(*[4096]usize, 0x20000000);

    // notes:
    //  ram has 4k words at address 0x20000000
    //  (c) is correct, and (d) is another way of writing (c)

0.5.0+652efe38b

1. ram.* in (a) is not needed in (b) and (c) and (d) - is this implicit coercion? If so, of what to what?

2. I expected 'assignment to constant' errors in (a) and (b) - what do you think?

**Comment by daurnimator** [comment]
>     2\. I expected 'assignment to constant' errors in (a) and (b) - what do you think?

Only the pointer is constant, not the memory its pointing to. i.e. it's not a `*[4096]const usize`

**Comment by markfirmware** [comment]
@daurnimator - simplified case:


    pub fn main() void {
        @ptrCast(*usize, &(( p).*)) = &y; // (e) compiles without error
    //  @ptrCast(*usize, &((&y).*)) = &y; // (f) cannot assign to constant, as expected
    }

    var y: usize = 0;
    var p = &y;


Yes, p is a variable and when changed to const I get ‘cannot assign to constant.’

Inferring then that if ptrCast produces comptime then assigning to it produces an error but not for the right reason - it should be ‘cannot assign to comptime.’ However if it produces runtime then I think it should still be an error to have it on the left side of an assignment. It should be a more or less distinct error to assign to ptrCast.

Regards,
Mark

**Comment by markfirmware** [comment]
1 + y = 4;

compiles
