### ISSUE TITLE
remove @bytesToSlice and @sliceToBytes from the language

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#4499]
We already have `std.mem.asBytes` and `std.mem.bytesAsValue` which actually work better than the builtin. 

This closes:
 * #3483
 * #3465
 * #3223
 * #1905
 * #1876

**Comment by xackus** [comment]
Will the builtins stay for the 0.6.0 release? I'd like to tackle this issue.

**Comment by andrewrk** [comment]
This can be implemented and merged into master before the release. The "milestone" attached to issues is more of a "deadline" than a plan. Issues from any milestone are fair game for contributors!

**Comment by xackus** [comment]
Thanks, I was asking since this is a breaking change.

**Comment by xackus** [comment]
This and probably the other issues can be closed.

**Comment by andrewrk** [comment]
Solved by @xackus in #4516, landed in 1d06c82c3bc44e808a3d7b4fe07e5c9fc492e8c3.
