### ISSUE TITLE
Multiple levels op optional weirdness/bug

### ISSUE THREAD

**Issue by BarabasGitHub** [ziglang/zig#4523]
I accidentily put double optional on some pointer. In my code the result was a segfault, but I can't reproduce that in some minimal example. However I did find other weirdness. To be honest I don't even know why it compiles and probably it shouldn't?

I used the trunk on https://godbolt.org/ not sure what exact version that is.

This prints something like f32@7ffe1d7ceb64
```
const std = @import("std");
pub fn main() void {
    var very_optional: ???*f32 = null;
    var a_number: f32 = 1.0;
    very_optional = &a_number;
    std.debug.warn("{}", .{very_optional});
}
```
This prints null
```
const std = @import("std");
pub fn main() void {
    var very_optional: ????*f32 = null;
    var a_number: f32 = 1.0;
    very_optional = &a_number;
    std.debug.warn("{}", .{very_optional});
}
```
This prints 1.0e+00 regardless of the number of `?`
```
const std = @import("std");
pub fn main() void {
    var very_optional: ????f32 = null;
    var a_number: f32 = 1.0;
    very_optional = a_number;
    std.debug.warn("{}", .{very_optional});
}
```

**Comment by Sobeston** [comment]
By accidentally using a double-optional a few days ago, I got code that acted differently between runs where it shouldn't have. Very confusing.

**Comment by Vexu** [comment]
All these casts are allowed but `std.fmt` now requires explicit `?` format string when formatting optionals.
