### ISSUE TITLE
assertion failed

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#4528]
pub fn main() void {
        var data: u8 = 0;
        const x = .{
            if (data != 0) ""[0..] else switch (@truncate(u1, data)) {
                0 => "up"[0 ..],
                1 => "down",
            },
        };
    }

    0.5.0+0cd89e917

    when analyzing /root/github.com/ziglang/zig/defect.zig:4:38: assertion failed. This is a bug in the Zig compiler.
    Unable to dump stack trace: debug info stripped

**Comment by xackus** [comment]
Results in an error on e79d7e0deda9e74dbaad1aa77db3e041f92f4f71:
```
test.zig:5:22: error: expected type '*const [0:0]u8', found '*const [2:0]u8'
            0 => "up"[0 ..],
                     ^
test.zig:5:22: note: pointer type child '[2:0]u8' cannot cast into pointer type child '[0:0]u8'
            0 => "up"[0 ..],
                     ^
```

**Comment by Vexu** [comment]
Still gives an assertion failure if you fix the type error:
```zig
pub fn main() void {
    var data: u8 = 0;
    const x = .{
        @as([]const u8, if (data != 0) "" else switch (@truncate(u1, data)) {
            0 => "up",
            1 => "down",
        }),
    };
}

// when analyzing a.zig:24:40: assertion failed. This is a bug in the Zig compiler.
```
