### ISSUE TITLE
RFC: Make syntax easier to read in natural left-to-right order

### ISSUE THREAD

**Issue by adontz** [ziglang/zig#4545]
This RFC serves the only purpose to help make Zig the greatest language ever! ;-)

## Goal

Make syntax more clear and unambiguous when reading from left to right

## Issue

As I noticed current syntax is harder to read left-to-right, than it can possibly be. I understand that distinction between compile time and run-time is intentionally blended and while Zig is statically and strongly typed language, source code sometimes looks like of dynamic language because a function may return a type. However, high levels of syntax consistency may not be that good for reading source code.

Compare the following two lines
```
const MyDataType = struct { x: i32 };
const myDataType = MyDataType{ .x = 32};
```
One creates new type, another creates new instance of existing type. They are not almost same, but they are similar enough to be confused until half of the line is already parsed by your brain. Usually brain assumes most common case, so const/var will be parsed as a variable declaration at first. And if you had assumed wrong, you'll have to reread/reinterpret line approximately after the point marked by ‡
```
const MyDataType = struct ‡ { x: i32 };
const myDataType = MyDataType ‡ { .x = 32};
```

### Struct/Union/Enum

What I suggest is to make these lines easily distinguishable from the very start. There are a few options, all of which are better than current state.
```
struct MyDataType = { x: i32 };
const myDataType = MyDataType{ .x = 32};
```
You know first line is the struct definition from the very start.

```
struct MyDataType = struct { x: i32 };
const myDataType = MyDataType{ .x = 32};
```
I'm not sure why to double "struct" keyword. It looks more familiar to a C programmer, which is probably a good thing, but it is not really necessary and does not resolve any syntax ambiguity as far as I understand.

```
type MyDataType = struct { x: i32 };
const myDataType = MyDataType{ .x = 32};
```
This is a bit worse, because from the very start we are not sure what it is. We know it's some type declaration, but not sure if it is a struct, an enum or an union. At least not a function or a variable, so still better.

Same suggestion applies to unions, enums and anything similar I have not discover yet.

### Functions

Regarding functions and taking into account https://github.com/ziglang/zig/issues/1717 it will become
```
fn less = (a: i32, b: i32) bool { return a < b; }; // Function definition
fn less2 = (a: i32, b: i32) bool; // function declaration;
fn lessType = @TypeOf((a: i32, b: i32) bool); // Function type declaration; I had no better idea to make it very distinct.
fn less3: lessType = (a: i32, b: i32) bool { return a < b; }; // Function definition with type checking
const lessPtr1 = &less; // Pointer to the function
const lessPtr2: @TypeOf((a: i32, b: i32) bool) = &less; // Pointer to the function with type checking
const lessPtr2: lessType  = &less; // Also pointer to the function with type checking
extern fn exLess = (a: i32, b: i32) bool; // External function declaration
```
You know it's a function from the very start.

I wanted to add external function declaration with type checking example
```
extern fn exLess: lessType = (a: i32, b: i32) bool;
```
But then realized it makes no sense, except some covariance/contravariance rules are in place, which requires some kind of inheritance/subclassing in the first place and I had not encounter any yet.

Also, functions may be returned by functions (not sure about the syntax, just to illustrate the idea).
```
fn GetLess = (comptime T: type) @TypeOf(fn (i32, i32)) { // Are parameter names required here?
    comptime if (T == i32) return (a: i32, b: i32) { a < b; }
    else if (T == [*]i8) return (a: [*]i8, b: [*]i8) { return strcmp(a, b) < 0; };
    else unreachable;
};

fn less = GetLess(i32);
```
### Imports
Now about the imports.
```
const something = @import("dependency").member;
```
You can't really tell if something is struct, enum, union or function by reading this code. You have to either go to definition (requires IDE or grep) or deduct from usage. So importing syntax will become
```
struct std = @import("std");
enum Mode = @import("std").io.Mode;
```
Again, obvious what it is from the very start of line, easier to read.

## Questions

I am not that familiar with language yet, so maybe I have unintentionally introduced some syntax ambiguities. Sorry for than, I did not mean to.

**Comment by Rocknest** [comment]
In my opinion naming conventions are enough. When i see a `TitleCase` variable i expect it to be a `type` (see the [style guide](https://ziglang.org/documentation/master/#Names))

However function expressions (#1717) look to me unnecessarily verbose and the status quo should be left alone.

**Comment by MasterQ32** [comment]
Afaik zig even had the syntax you proposed but it was removed to simplify a lot of stuff. I recommend you to get in touch with the std codebase to see how much stuff is done at comptime with struct declarations ;)

Example:
https://github.com/ziglang/zig/blob/1d06c82c3bc44e808a3d7b4fe07e5c9fc492e8c3/lib/std/os.zig#L52-L68

`system` is a namespace/struct (same thing in Zig) of which the content is decided at compile time. There are also examples where types are a struct, enum, integer, … depending on different compiler settings (difference between windows and *unix). Same is for generics which are just functions returning a type.

**Comment by daurnimator** [comment]
One of the cool ideas in zig is that types are "just another variable type". Same as zig doesn't have `i32 foo = getNumber()` it doesn't have `fn foo = getFunction()` or `struct foo = getStruct()`.

**Comment by adontz** [comment]
> Afaik zig even had the syntax you proposed but it was removed to simplify a lot of stuff.

I understand that parser became simpler. I don't understand why is it a priority in the first place.

> I recommend you to get in touch with the std codebase to see how much stuff is done at comptime with struct declarations 

This is exactly what I do for last few days. Read Zig code, including code in std. Honestly, Zig seems easy and is easy to write, but it is way below average on readability scale. Code review and mentoring are my duties at work for many years. I read C, C++, C#, Java, Python, JavaScript, some of Perl snd PHP. Zig syntax readability is so bad right now, it's somewhere around Bash and JavaScript. I would never recommend to start a big project in Zig, because of this reason only. It's not that you cannot understand what is written, finally you can. And it's not that code is dense, C++ can be pretty dense, Python comprehension oneliners are usual and dense. It's that syntax is not verbose and inconsistent in a good way. Lisp syntax is consistent, but hardly readable even with indentation. Absolute consistency is a bad thing for reading code. Python syntax and style are ugly, but so easy to read.

**Comment by andrewrk** [comment]
Thanks for the proposal. I'm confident with the general way the syntax is headed. A drastic change such as this proposal is not planned.
