### ISSUE TITLE
cannot print f128 values

### ISSUE THREAD

**Issue by tiehuis** [ziglang/zig#455]
Printing a f128 performs a cast to a f64 before proceeding. It appears that the `__truncctfdf2` function is required to perform this cast correctly.

```
lld: error: undefined symbol: __trunctfdf2
>>> referenced by index.zig:248 (/home/me/local/lib/zig/std/fmt/index.zig:248)
>>>               /home/me/src/zig-docgen/zig-cache/docgen.o:(formatFloat)
```

**Comment by tiehuis** [comment]
Slightly related: u128 to f64 casting has a similar dependency on `__floatuntidf`.

**Comment by andrewrk** [comment]
We should also probably be able to print them correctly instead of casting to f64. We'll probably want to port the code from libquadmath.

`__truncctfdf2` and `__floatuntidf` are compiler_rt functions, we can port them just like all the rest from llvm.

**Comment by andrewrk** [comment]
https://github.com/llvm-project/llvm-project-20170507/tree/master/compiler-rt/lib/builtins

**Comment by andrewrk** [comment]
bonus points if we can update parsec to do the port automatically :1st_place_medal:

**Comment by tiehuis** [comment]
See #495.

**Comment by tiehuis** [comment]
f128 values can now be printed since #1166. See #1181 regarding a more complete implementation that doesn't simply rely on lossy casting to f64.
