### ISSUE TITLE
Proposal: add `allocator.allocSentinel`

### ISSUE THREAD

**Issue by fengb** [ziglang/zig#4554]
Creating a sentinel terminated slice is really manual:
```zig
var raw_data = try allocator.alloc(u8, count + 1);
raw_data[count] = 0;
var data = raw_data[0..count :0];
```

Zig does protect against most of the footguns, but it's still a lot of boilerplate to get to the "baseline". How about we have a new function to do this?

```zig
var data = try allocator.allocSentinel(u8, 0, count);

// or maybe
var data = try allocator.allocSentinel([:0]u8, count);
```

**Comment by Sobeston** [comment]
Makes a lot of sense to me. I like the latter.

**Comment by marler8997** [comment]
Wouldn't it be a free function?  Something like this?
```zig
fn allocSentinel(allocator: var, T: type, count: usize) !T {
    const info = @typeInfo(T).Pointer;
    const sentinel = info.sentinel orelse unreachable;
    var ptr = try allocator.alloc(info.child, count + 1);
    ptr[count] = sentinel;
    return ptr[0 .. count :sentinel];
}

pub fn main() anyerror!void {
    const mem = allocSentinel(std.heap.page_allocator, [:0]u8, 10);
}
```

**Comment by deingithub** [comment]
What'd be the difference to using [`std.cstr.addNullByte()`](https://github.com/ziglang/zig/blob/783e8ad0319b950a1d42d5a93e4fbb9e9df1be10/lib/std/cstr.zig#L36) here?

**Comment by fengb** [comment]
@marler8997 that'd be the current workaround yes. I think this arguably makes sense to support as a main method since sentinel termination has become more of a core idea than a workaround for C.

@deingithub `addNullByte` requires an existing string and creates a copy with the extra space for a sentinel. Allocating the correct space upfront would be much cheaper, although `addNullByte` is useful working with strings already in memory.

**Comment by marler8997** [comment]
> I think this arguably makes sense to support as a main method

Yeah I was saying you could add that `allocSentinel` function to the standard lib...I was just saying it would probably be a "free function" rather than an "member function" of every allocator.

**Comment by SpexGuy** [comment]
The stdlib kind of blurs the line here.  In terms of "member functions" of allocator implementations, there is only reallocFn and shrinkFn.  The rest of the functions (alloc, alignedAlloc, create, free, etc) are all in one place in the `std.mem.Allocator` namespace.  It seems like if this function is going to be added to the stdlib it probably also belongs in the `std.mem.Allocator` namespace.

**Comment by marler8997** [comment]
https://github.com/ziglang/zig/pull/4579

**Comment by marler8997** [comment]
merged at https://github.com/ziglang/zig/commit/90c232bbe8e53c09df14536def54b33d92ddd3c5
