### ISSUE TITLE
Bug in std.build.LibExeObjStep.setTarget

### ISSUE THREAD

**Issue by joachimschmidt557** [ziglang/zig#4555]
When compiling https://github.com/andrewrk/tetris/tree/27d0d0ec085e1ac0c9cae6092f807a318b15dd44 with the newest [zig from master](https://github.com/ziglang/zig/tree/416a547cdb8dbbf3d2e7ce32132f0a25f2a8607e), this error occurs:

```
/home/joachim/src/zig/build/lib/zig/std/build.zig:1294:17: error: no member named 'arch' in struct 'std.target.Cross'
                .arch = target_arch,
                ^
```

The code assigns a value to `.arch` even though `std.target.Target.Cross` doesn't have this field.

```zig
        return self.setTheTarget(Target{
            .Cross = CrossTarget{
                .arch = target_arch,
                .os = target_os,
                .abi = target_abi,
                .cpu_features = target_arch.getBaselineCpuFeatures(),
            },
        });
```

**Comment by andrewrk** [comment]
Thanks.

This is obsoleted with the merge of #4550 which landed in 76176104001420ea04840f9b31e706289e4ebf11.
