### ISSUE TITLE
Dependency loop false positive with optional pointers

### ISSUE THREAD

**Issue by Vexu** [ziglang/zig#4562]
```zig
const std = @import("std");

const S = struct {
    a: u32,
    b: Map,

    const Map = std.StringHashMap(?*S);
};
test "" {
    _ = S;
}
```

**Comment by andrewrk** [comment]
On the plus side, we're collecting some useful regression test cases for self-hosted

**Comment by andrewrk** [comment]
Previous issue for context: #4560

**Comment by Vexu** [comment]
It seems this has been broken since before 0.5.0 was released. I think I was hitting some other bug causing me to think this was a recent regression.
