### ISSUE TITLE
RFC: Suggestion to refactor/rewrite how zig fmt writes indentation

### ISSUE THREAD

**Issue by LakeByTheWoods** [ziglang/zig#4580]
While trying to fix indentations bugs with multiline string literals I've found the indentation system to be extreemly fragile. Every time I try to isolate a particular node's indentation code and modify it it ends up breaking 3 other things.
Nodes should be able to render themselves correctly without any knowledge of the current indentation state, presently they have to look before and after themselves to infer the state of indentation.
It would be better if nodes could render in isolation, only looking at their child nodes and only thinking about the indentation of their child nodes.

This is all pretty vague, so I've got some psuedo zig to try and illustrate the idea (not real zig as I want some feedback or approval before dedicating too much time)

The idea is instead of passing around indent and writing ' ' or '\n' bytes in all of the node rendering code the indentation handling moves into the stream.

```
// render function call
{
    render identifier
    render lbrace

    stream.pushIndentation(); // Even if params are on one line it's still safe to increase the streams indentation temporarily (it will have no effect)
    defer stream.popIndentation(); // Push should always be matched with a pop

    isMultiline = lbrace and rbrace on different lines or params has trailing semicolon
    if (isMultiline)
        stream.insertNewline();

    loop over arguments {
        render arg
        if (isMultiline)
            stream.maybeInsertNewline(); // Only maybe since arg may have inserted a newline due to being a comment
    }

    if (isMultiline)
        stream.maybeInsertNewline();

    render rbrace
}

stream.insertNewline()
{
    stream.writeByte('\n');
    stream.current_line_empty = true;
}

// Inserts a newline but not a blank one
stream.maybeInsertNewline()
{
    if (! stream.current_line_empty)
        stream.insertNewline();
}

stream.write(bytes)
{
    // Apply indentation if the line is empty
    if (! stream.current_line_empty)
        for (stream.indent_stack[0..indent_stack_top]) |indent|
            stream.writeByteNTimes(' ', indent);
    stream.current_line_empty = false;
    stream.actualyWriteBytes(bytes); // Do whatever call is needed to get the bytes copied into the stream
}

stream.pushIndentation() // push default indentation
{
    // Doesn't actually write any indentation. Just primes the stream to be able to write the correct indentation if it needs to.
    stream.pushIndentationN(default_indent);
}

stream.pushIndentationN(n) // push arbitrary amount of indentation (I think I saw the ASM code push 2?)
{
    stream.indent_stack[indent_stack_top] = n;
    stream.indent_stack_top += 1;
}

stream.popIndentation()
{
    stream.indent_stack_top -= 1;
}
```

I'm fairly confident but not 100% sure this covers all use cases and would allow fixing of #3978 and #3739 for example.

**Comment by andrewrk** [comment]
This seems generally reasonable to me. Do you want to try it in a pull request and see if it works?

**Comment by LakeByTheWoods** [comment]
I'll give it a crack.
