### ISSUE TITLE
implement the native operating system version detection for macOS

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#4583]
This is a follow-up task from #4550.

https://github.com/ziglang/zig/blob/76176104001420ea04840f9b31e706289e4ebf11/lib/std/zig/system.zig#L226-L228

https://github.com/ziglang/zig/blob/76176104001420ea04840f9b31e706289e4ebf11/lib/std/target.zig#L115-L187

`sw_vers -productVersion` gives the correct answer, however, it would be better to avoid depending on this binary existing and maintaining this behavior. Furthermore, a peek at [the source code](https://opensource.apple.com/source/DarwinTools/DarwinTools-1/sw_vers.c.auto.html) (thanks @fengb for finding it) for this file reveals that it depends on the CoreFoundation framework to function, which is another dependency it would be nice to avoid here.

It looks like the answer is in `/System/Library/CoreServices/SystemVersion.plist` (thanks @mikdusan for finding it), which is in a simple XML format. Perhaps a prerequisite to this issue would be an XML tokenizer.

**Comment by andrewrk** [comment]
Not working on my macos mojave laptop.

`zig builtin` reports:

```
pub const os = Os{
    .tag = .macosx,
    .version_range = .{ .semver = .{
        .min = .{
            .major = 10,
            .minor = 13,
            .patch = 0,
        },
        .max = .{
            .major = 10,
            .minor = 15,
            .patch = 3,
        },
    }},
};
```

expected version:

```
andy@Andrews-MacBook-Air:~/dev/zig/build$ sw_vers -productVersion
10.14.6
```

**Comment by daurnimator** [comment]
> Not working on my macos mojave laptop.
> 
> `zig builtin` reports:
> 
> ```
> pub const os = Os{
>     .tag = .macosx,
>     .version_range = .{ .semver = .{
>         .min = .{
>             .major = 10,
>             .minor = 13,
>             .patch = 0,
>         },
>         .max = .{
>             .major = 10,
>             .minor = 15,
>             .patch = 3,
>         },
>     }},
> };
> ```

How did you end up with different `min` to `max`? [The PR sets them equal](https://github.com/ziglang/zig/pull/4589/files#diff-d6c6ee4e32d6d1b30e8e7e467e9125c7R245-R246)

**Comment by andrewrk** [comment]
The null byte was getting included and so `Version.parse` was returning                          `error.InvalidCharacter`.
