### ISSUE TITLE
Proposal: Implicit casts should succeed through multiple layers of indirection if possible.

### ISSUE THREAD

**Issue by JesseRMeyer** [ziglang/zig#4596]
I would like for the compiler to automatically handle the follow type conversion.
```zig
const validation_layer = "VK_LAYER_KHRONOS_validation";
const test_struct = struct {
        ppEnabledLayerNames: [*c]const [*c]const u8,
};

var testing = test_struct {
    .ppEnabledLayerNames = &validation_layer,
};
```

But I'm greeted with:
```
: error: expected type '[*c]const [*c]const u8', found '*const *const [27:0]u8'
        const validation_layer = "VK_LAYER_KHRONOS_validation";
        ^
 note: pointer type child '*const [27:0]u8' cannot cast into pointer type child '[*c]const u8'            const validation_layer = "VK_LAYER_KHRONOS_validation";
        ^
 note: pointer type child '[27:0]u8' cannot cast into pointer type child 'u8'
        const validation_layer = "VK_LAYER_KHRONOS_validation";
        ^
: note: referenced here
            .ppEnabledLayerNames = &validation_layer,
```

So I have to @ptrCast myself:
```zig
const validation_layer = "VK_LAYER_KHRONOS_validation";
const test_struct = struct {
    ppEnabledLayerNames: [*c]const [*c]const u8,
};

var testing = test_struct {
    .ppEnabledLayerNames = @ptrCast([*c]const [*c]const u8, &validation_layer),
};
```

or specify the type explicitly:
```zig
const c_string = [*:0]const u8;
const validation_layer: c_string= "VK_LAYER_KHRONOS_validation";
```

The use case here is that the Vulkan API wants a pointer to an array of c-strings in multiple places.

Based on a discussion with @LemonBoy on IRC, the compiler currently errors because ```it tries to convert [*c] to * but fails miserably because the child types are not compatible```, and that ```there's an implicit cast from *[N]T to [*c]T```.  So supporting this implicit cast in general doesn't seem plausible.

**Comment by JesseRMeyer** [comment]
Possibly related.

```zig
var extension_names_to_enable = "VK_KHR_win32_surface";
```

is automatically inferred by the compiler. But
```zig
var extension_names_to_enable = {"VK_KHR_win32_surface", "VK_KHR_surface"};
```

is not.  The full type must be specified.
```zig
var extension_names_to_enable = [2][:0]const u8{"VK_KHR_win32_surface", "VK_KHR_surface"};
```

It's a surprising discontinuity in the inference rules, when the type appears to be easily inferrable by a person, but the type here in general is ambiguous for array of slices or pointers.  I'm not proposing a specific suggestion here, but other Zig programmers are bound to encounter this interfacing with C libraries.

**Comment by JesseRMeyer** [comment]
I don't think this example is motivating since the semantics of Zig slices and C strings differ. Closing for now.

**Comment by BarabasGitHub** [comment]
I'm using this, which isn't much better...
```
const validation_layers: []const [*:0]const u8 = &[_][*:0]const u8{"VK_LAYER_LUNARG_standard_validation"};
```
and then you can do
```
    .ppEnabledLayerNames = validation_layers.ptr,
```
It's all a bit yuck.
