### ISSUE TITLE
std.process.getEnvVarOwned is case sensitive on Windows

### ISSUE THREAD

**Issue by ilmaria** [ziglang/zig#4603]
On Windows, environment variables should be case insensitive but `std.process.getEnvVarOwned` returns only case sensitive matches. For example, on my Windows 10 the path variable is "Path" and not "PATH" so `std.ChildProcess.exec` doesn't work when the argument is an executable in the path.

For me this prints "error: FileNotFound" :
```
const std = @import("std");

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    const args = [_][]const u8{
        "ipconfig",
    };
    _ = try std.ChildProcess.exec(&arena.allocator, args[0..], null, null, std.math.maxInt(usize));
}
```

**Comment by mikdusan** [comment]
related: `pub fn std.process.getEnvMap(allocator: *Allocator) !BufMap` needs a specialized `BufMap` for Windows with case-insensitive keys or maybe `getEnvMap()` can convert all env vars to uppercase but that seems hacky, and I'm not sure if losing case-retention will have consequences.

**Comment by suirad** [comment]
Should probably be closed.

**Comment by andrewrk** [comment]
The commit says:

> partially addresses #4603
> Fixing std.process.getEnvMap is NOT included in this commit.
