### ISSUE TITLE
Builder.addFunction

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#4609]
Builder has the addSystemCommand amongst others, but I'd like to add a zig function directly as a build step. The zig function would do within the zig build what would otherwise be done by calling an external system command. Is there a builder function that can add a zero parameter/return !void function?

**Comment by andrewrk** [comment]
Can you share some code examples to help explain the proposal?

**Comment by markfirmware** [comment]
Currently I have a makehex.zig file that produces a .hex file and I call it from the build function via:

    const run_hex_file_step = b.addSystemCommand(&[_][]const u8{
        "zig", "run", "makehex.zig",
    });

Instead of that, use this in the build function:

    const hex_file_step = HexFileStep { .image_file_path = "zig-cache/bin/" ++ image_name, .hex_file_path = "main.hex" };
    const run_hex_file = b.addFunction(hex_file_step.runStepCallback, &hex_file_step);

where the code for making the hex file is included in build.zig:

    const HexFileStep = struct {
        hex_file_path: []u8,
        image_file_path: []u8,

        fn runStepCallback(self_ptr: usize) !void {
            return @intToPtr(*HexFile, self_ptr).runStep();
        }

        fn runStep(self: *HexFile) !void {
            const cwd = fs.cwd();
            const image = try cwd.openFile(image_file_path, fs.File.OpenFlags{});
            defer image.close();
            const hex = try cwd.createFile(hex_file_path, fs.File.CreateFlags{});
            defer hex.close();
            var offset: usize = 0;
            var read_buf: [4 * 1024 * 1024]u8 = undefined;
            assert(read_buf.len % 32 == 0);
            while (true) {
                var n = try image.read(&read_buf);
                if (n == 0) {
                    break;
                }
                while (offset < n) {
                    ...
                }
            }
            try writeRecord(hex, 0, 0x01, &[_]u8{});
        }

        fn writeRecord(file: fs.File, offset: usize, code: u8, bytes: []u8) !void {
            ...
        }
    };

I'm not up to date on the state of the art of generic callbacks. Builder.addFunction here takes a function that itself takes a usize which is the callback argument. It is used here to point the the FileHexStep struct that has the parameters needed to run the step.

**Comment by hyu1996** [comment]
I'm not sure about your problem, I think you can generate this file directly in `build.zig`, and then add the file path to the `builder`.

**Comment by markfirmware** [comment]
The hex file needs to be generated after the binary is produced which means it must be a step itself. I don’t know how to do that except by adding a SystemCommand step.

**Comment by layneson** [comment]
I think something like this would work for you: https://gist.github.com/layneson/e0ed54f9e14da878dd0ba102da41e2c3.

**Comment by markfirmware** [comment]
@layneson thanks!

#5051
