### ISSUE TITLE
std.fs has no member makePath

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#4622]
Sorry, on to another one ...

    zig version 0.5.0+3b235cfa8

    ./zig/lib/zig/std/build/emit_raw.zig:252:11: error: container 'std.fs' has no member called 'makePath'
        fs.makePath(builder.allocator, builder.getInstallPath(self.dest_dir, "")) catch unreachable;

https://github.com/markfirmware/zig-bare-metal-microbit/tree/ObjectFormat

    exe.setTarget(try std.zig.CrossTarget.parse(.{
        .arch_os_abi = "thumb-freestanding-none",
    }));

**Comment by andrewrk** [comment]
> Sorry, on to another one ...

No sorry! Thank you!
