### ISSUE TITLE
Error in fmt (integer value 1 cannot be coerced to type 'i1')

### ISSUE THREAD

**Issue by eigenbom** [ziglang/zig#4632]
Writing the following:
```
const value: i1 = -1;
warn("{}", .{value});
```

Results in a compile-time error:
```
...\std\fmt.zig:951:52: error: integer value 1 cannot be coerced to type 'i1'
        const new_value = @intCast(uint, -(value + 1)) + 1;
```

Version info:
```
e:\dev\tmp\zig>zig version
0.5.0+378bf1c3b
```

**Comment by daurnimator** [comment]
> `value + 1`

This gets compiled as: `@as(i1, value) + @as(i1, 1)`
An `i1` can only hold `0` or `1`, so it fails.

**Comment by eigenbom** [comment]
Almost correct, an i1 can hold a 0 or -1. In any case the bug is in zig's standard library.

**Comment by eigenbom** [comment]
Oh, you edited your comment to fix your mistake.
