### ISSUE TITLE
zig targets not working from tar Jx download

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#4634]
root@localhost:~# which zig
    /root/zig/zig
    root@localhost:~# zig version
    0.5.0+378bf1c3b
    root@localhost:~# zig targets
    Unable to find zig lib directory: FileNotFound.
    Reinstall Zig or use --zig-install-prefix.
    unable to find zig installation directory: ZigLibDirNotFound

**Comment by andrewrk** [comment]
https://github.com/ziglang/zig/blob/378bf1c3b71fdcc823fb9a5382400ec0a659fc00/src-self-hosted/print_targets.zig#L68-L71
