### ISSUE TITLE
Add support for sized integer literals

### ISSUE THREAD

**Issue by watzon** [ziglang/zig#4644]
This comes off the back of my journey through OS development, which ends up requiring **a lot** of bit shifting. Due to the nature of integer constants it's not possible to use one on the left hand side of a bit shift, which means that integer has to be cast to a specific size. With all these casts things can end up getting pretty messy, so I'm proposing a sized integer literal syntax that looks something like the following:

```zig
# Currently
var rhs: u3 = 2;
var a: u8 = @as(u8, 1) << rhs;

# With sized literals
var rhs = 2u3;
var a: u8 = 1u8 << rhs;
```

This would allow us to constrain the use of `@as` just to variables that already have a size and need to be cast to a bigger one, while all "integer constants" could be expressed using the literal syntax. I think it looks a lot cleaner. An alternative syntax could be to do what nim does and use a apostrophe to separate the integer from the type.

```nim
1234'u16
```

I don't have a preference either way, but I think the apostrophe may make things somewhat more readable?

**Comment by alexnask** [comment]
I think  

```zig
1234_u16
```  

Would be better since it's in line with #504

**Comment by andrewrk** [comment]
Not planned. Use `@as`
