### ISSUE TITLE
rename "i386" to "x86"

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#4663]
The baseline value we use for "i386" is currently a pentium4 cpu model, which is, I believe i686. I think it would be more correct to use "x86" rather than "i386" for this CPU architecture.

https://github.com/ziglang/zig/blob/80ff549e2602ecfc4eaf9ade0108e1779dff1874/lib/std/target.zig#L947

**Comment by Sobeston** [comment]
i386 is short for 80386 (1985). Pentium 4 (2000) all support MMX, SSE, SSE2. `x86.cpu.pentium4` is listed as supporting SSE2 for example, which was not present in i386. 

So yes, `.i386 => &x86.cpu.pentium4` is not technically correct.

i686 (meaning P6 architecture, 1995) did not have SSE2, so we are targeting something slightly newer than both i386 and i686.

I'm in favour of calling the baseline cpu model x86, and just documenting that it's based off some specific intel micro architecture.

**Comment by Mouvedia** [comment]
i686 first incarnation was the Pentium Pro which lacked the MMX instruction set.
All pentium 4 supported MMX, SSE, SSE2.Starting with the Prescott core they supported SSE3 as well.

**Comment by pixelherodev** [comment]
Shouldn't this be labeled arch-x86 then? ;)

**Comment by daurnimator** [comment]
`x86` is general accepted to cover all the *86 processors, including e.g. the 8086 and 80286 which are 16bit.
I think what we want is more formally known as "IA-32" of which the 386 was the first.

**Comment by jayschwa** [comment]
> `x86` is general accepted to cover all the *86 processors, including e.g. the 8086 and 80286 which are 16bit.
> I think what we want is more formally known as "IA-32" of which the 386 was the first.

I agree with this suggestion from a technical correctness standpoint, but I disagree that "x86", as it is commonly used in the wild, implies support for 286 and below.

**Comment by Mouvedia** [comment]
IMHO it's either

`.i686 => &x86.cpu.pentiumpro,` which has the NOPL instruction

> [Intel did not document the NOPL instruction for the i686, **yet** all their 686 processors happened to implement it](https://bugzilla.redhat.com/show_bug.cgi?id=579838#c15)

or

`.i686 => &x86.cpu.i686,`

which doesn't:

> https://github.com/ziglang/zig/blob/0833c8d06ba9a467bb8449cbca2ba6f43d218c32/lib/std/target/x86.zig#L1835-L1844
