### ISSUE TITLE
Master branch downloads crash with SIGILL

### ISSUE THREAD

**Issue by Rocknest** [ziglang/zig#4670]
Program received signal SIGILL, Illegal instruction.
0x0000000008955e78 in std.zig.system.x86.detectNativeFeatures ()

[0x8955e78] xgetbv

**Comment by Rocknest** [comment]
https://github.com/lu-zero/stdarch/commit/9ec364c9d9afbb775265d1ec940eb9e27929f182

**Comment by LemonBoy** [comment]
This piece of code was wrongly translated from C++:

```zig
    leaf.eax = getXCR0();

    const has_avx = bit(leaf.ecx, 27) and
        bit(leaf.ecx, 28) and
        ((leaf.eax & 0x6) == 0x6);
```

Notice how that's different from the original code:

```c++
  bool HasAVXSave = ((ECX >> 27) & 1) && ((ECX >> 28) & 1) &&
                    !getX86XCR0(&EAX, &EDX) && ((EAX & 0x6) == 0x6);
```

The `getX86XCR0` function is never called if the first two checks fail.

There's also no need to use the `.byte` encoding for `xgetbv` as LLVM assembler should be able to assemble it correctly.

**Comment by andrewrk** [comment]
cc @alichay

**Comment by andrewrk** [comment]
@Rocknest after this is fixed, can I get you to a diff of the previous working version `zig builtin` and master branch (after the fix)? The diff should be empty.

**Comment by heidezomp** [comment]
> @Rocknest after this is fixed, can I get you to a diff of the previous working version `zig builtin` and master branch (after the fix)? The diff should be empty.

I'm also bitten by this bug, and I'll do the same to be sure.

**Comment by heidezomp** [comment]
@LemonBoy's patch fixes the SIGILL for me, and my `zig builtin` diff is empty.

**Comment by Rocknest** [comment]
Same here. However info in `zig targets` is wrong
```json
 "native": {
  "triple": "x86_64-linux.3.16...5.5.5-gnu.2.17",
  "cpu": {
   "arch": "x86_64",
   "name": "x86_64",
   "features": [
    "64bit",
    "cmov",
    "cx8",
    "fxsr",
    "macrofusion",
    "mmx",
    "nopl",
    "slow_3ops_lea",
    "slow_incdec",
    "sse",
    "sse2",
    "x87"
   ]
  },
  "os": "linux",
  "abi": "gnu"
 }
```
