### ISSUE TITLE
make "noasync" keyword work more like "comptime"

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#4696]
Currently, `noasync` syntactically works only for function calls. This causes some parsing ambiguity, as well as common sense ambiguity, such as in the following expression pointed out by @LemonBoy:

```zig
noasync a.b().c()
```

This proposal is to change the parsing rules so that `noasync` works identically to `comptime`. That is, it takes an expression, and evaluates the expression in a scope that assumes all function calls and awaits are no-async.

This supersedes #3157. Zig no longer needs the ability to annotate awaits and functions; noasync blocks accomplish both purposes.

**Comment by andrewrk** [comment]
Here's an unfinished checklist pulled from #3157 which is now closed.

* [ ] add `noasync` to stage1 parser
* [ ] add `noasync` to zig fmt
* [x] implement `noasync` for function calls
* [x] runtime safety for `noasync` function calls. Panic if the function suspended.
* [ ] make even async functions guaranteed not to suspend for noasync function calls
* [x] implement `noasync` for await
* [ ] runtime safety for noasync await. Panic if the the frame is not finished.
* [ ] docs

**Comment by LemonBoy** [comment]
Does this solve the need for `noasync fn` declarations?

**Comment by andrewrk** [comment]
Yes

**Comment by andrewrk** [comment]
Solved by @Vexu in #4700, landed in 638d5c3aca7ce1e4fd10060079caa0acb66144c0. Follow up issues are: #4728 #4729 #4730
