### ISSUE TITLE
Proposal: add block keyword

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#4712]
Instead of

    ...
    {
        ...
    }

use:

    ...
    block {
        ...
    }

This would make nested indentation more uniform.

**Comment by squeek502** [comment]
Is this a style thing? Isn't
```zig
block: {
    ...
}
```
already valid (i.e. labeled block with the label `block`)?

**Comment by markfirmware** [comment]
I wasn’t aware of that approach. That will do fine.
