### ISSUE TITLE
Proposal: make max_size parameter in InStream.readAllBuffer optional

### ISSUE THREAD

**Issue by joachimschmidt557** [ziglang/zig#4723]
The functions

- readAllBuffer
- readAllArrayList
- readAllAlloc
- readUntilDelimiterArrayList
- readUntilDelimiterAlloc

in `std.io.InStream` currently all have a parameter `max_size`. I dont't find this parameter to be helpful. As a remedy, I sometimes supply an arbitrary value when I don't care about the maximum size, which I don't think is good style.

Recently, the `std.io.readLine` and `std.io.readLineFrom` functions were removed. I moved to `readUntilDelimiterAlloc` resulting that. But the maximum size parameter has been bugging me, leading me to create my own functions which just unconditionally read into an ArrayList until the ArrayList itself eventually may return an error.

**Comment by andrewrk** [comment]
You can pass `std.math.maxInt(usize)` if you want no limit. But why do you want no limit? Do you really want to read a 16 EiB file into RAM?

**Comment by joachimschmidt557** [comment]
I think that I don't want to set an artificial limit when I don't care about the limit. I don't know, I just think that when I specifically choose to use an `ArrayList` or an allocator instead of a slice to read into, I want the size to be virtually arbitrary.

**Comment by joachimschmidt557** [comment]
I'll close this issue as there is no more interest in this on my part. I have adapted to the API as it is in the standard library at the moment. If there is any renewed interest, this can be reopened.
