### ISSUE TITLE
Parameters declared with the same name as global variables are conflicting

### ISSUE THREAD

**Issue by frett27** [ziglang/zig#4736]
Hi, i'm quite noobs on the language , and need language lawyers help,
The following: 

    fn function(types: *MyType) void {}

    const MyType = struct {};

    var types = *MyType;

    pub fn main() void {
        var t: MyType = .{};
        function(&t);
    }

because of the same name in the parameter (types) and the name in global scope. are the parameters associated to a global type definition ? this may not scale.

**Comment by Dimension4** [comment]
Newbie here aswell :). Zig doesn't allow shadowing at any level, that's why the compiler issues a "redefinition error".

**Comment by andrewrk** [comment]
Welcome, @frett27. Here are some places you can find other community members to discuss these things with: https://github.com/ziglang/zig/wiki/Community

"no shadowing" is not planned to be changed.
