### ISSUE TITLE
[question] Disabling CFI for target architecture possible? (Xtensa)

### ISSUE THREAD

**Issue by INetBowser** [ziglang/zig#4745]
Hi,

I'm currently trying to get [Zig working on the ESP32](https://github.com/INetBowser/zig) (which uses the Xtensa architecture) but there seems to be a problem with CFI (Control Flow Integrity).
I'm able to compile Zig code to Xtensa assembly but I have a slight problem. In the assembly file there are CFI directives which are not supported by the GCC compiler for the ESP32. Is there a way to disable CFI somehow?

Here is a small example:

**command used to build:**
`zig build-exe -target xtensa-freestanding -fno-emit-bin -femit-asm main.zig`

**main.zig:**
```zig
export fn testfn() u32 {
    return 1337;
}
```

**main.s:**
```
// ...

        .global testfn
        .p2align        2
        .type   testfn,@function
testfn:
.Lfunc_begin1:
        .file   4 "/home/inetbowser/InternetBowser/esp32-zig/src/main.zig"
        .loc    4 0 0
        .cfi_startproc
        entry   a1, 40
        mov.n   a7, a1
        .cfi_def_cfa b7, 40
        movi    a8, 1337
.Ltmp4:
        .loc    4 2 12 prologue_end
        s32i.n  a8, a7, 0
        .loc    4 2 5 is_stmt 0
        l32i.n  a2, a7, 0
        movsp   a1, a7
        retw.n
.Ltmp5:
.Lfunc_end1:
        .size   testfn, .Lfunc_end1-testfn
        .cfi_endproc

// ...
```

Kind regards.

**Comment by LemonBoy** [comment]
> CFI (Control Flow Integrity)

Call Frame Information

Try passing `--strip` to the Zig compiler, that should remove all the DWARF annotations.

**Comment by INetBowser** [comment]
> Call Frame Information

My bad. :smile: 


> Try passing `--strip` to the Zig compiler, that should remove all the DWARF annotations.

That fixed the problem. Thanks again!
