### ISSUE TITLE
Compiler segfault with anonymous lists

### ISSUE THREAD

**Issue by alichay** [ziglang/zig#4755]
I'm not sure what to call this, as the actual cause of the issue eludes me.
Calling a function that takes an anonymous list argument  _twice_, where the first parameter in that list is a struct, and the second parameter is a string literal, causes the compiler to segfault. This affects any function taking arguments like this, including std.debug.warn.

Crash log from valgrind: https://gist.github.com/alichay/925d426fd92c211816f711f6c1e23e94

```zig
pub const Data = struct {
    dummy: u64 = 0,
};
pub fn consume(a: var) void {}
pub fn main() void {
    consume(.{Data{}, "help"});
    consume(.{Data{}, "help"});
}
```

**Comment by andrewrk** [comment]
Fixed by the new compiler; test coverage by "tuple in tuple passed to generic function" in test/behavior/tuple.zig.
