### ISSUE TITLE
translate-c: <sys/header_name> headers don't work

### ISSUE THREAD

**Issue by vired** [ziglang/zig#4763]
translate-c doesn't work with headers in /usr/include/sys

**Comment by vired** [comment]
i have failed to translate darkhttpd https://unix4lyfe.org/darkhttpd/

**Comment by daurnimator** [comment]
Did you include /usr/include in your header search path?

These sort of questions may be better served by other places in the community. https://github.com/ziglang/zig/wiki/Community

**Comment by andrewrk** [comment]
Yeah actually there is not enough information here. I'm happy to re-open if you can provide enough details to reproduce the problem.

**Comment by vired** [comment]
@daurnimator  compiling the c source works without any problem

**Comment by vired** [comment]
@daurnimator form the output of `cpp -v /dev/null -o /dev/null` as provided here https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html 

```
#include <...> search starts here:
 /usr/lib/gcc/x86_64-redhat-linux/9/include
 /usr/local/include
 /usr/include
End of search list.
```

**Comment by vired** [comment]
@andrewrk I have provided more info. take a loot at it.
also the output of running `zig translate-c darkhttpd.c`
```
darkhttpd.c:40:11: error: 'sys/sendfile.h' file not found
# include <sys/sendfile.h>
          ^
```

**Comment by vired** [comment]
@daurnimator does this work in your system ?

**Comment by daurnimator** [comment]
@vired see https://github.com/ziglang/zig/issues/2041#issuecomment-471330773 you're hitting intentional behaviour.

**Comment by vired** [comment]
@andrewrk on my system `translate-c` doesn't work with any `#include <header_name>`
this doesn't work
```
#include <stdio.h>
int main()
{
    int message = "world";
    printf("hello, %s\n", message );
    return 0;
}
```
```
tc.c:1:10: error: 'stdio.h' file not found
#include <stdio.h>
         ^
```

**Comment by vired** [comment]
@daurnimator  what should i do ?

**Comment by vired** [comment]
it works when i add `--library c`

but when try to compile it with `zig build-exe` it says
```
/home/tanvir/bin/zig/lib/zig/std/start.zig:250:17: error: expected return type of main to be 'void', '!void', 'noreturn', 'u8', or '!u8'
                @compileError(bad_main_ret);
                ^
```
generated zig has return type `c_int` for  `main` function. but compiler doesn't work with `c_int` return type for main.
