### ISSUE TITLE
Tokenizer bug when file ends with double slash without newline

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#4769]
If your source file ends with a double-slash `//` comment without a trailing newline, the zig compiler will assert a tokenizer bug like this:
```
Assertion failed at /deps/zig/src/tokenizer.cpp:275 in begin_token. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
Aborted (core dumped)
```

Reproduce with:
```
echo -n // > bug.zig
zig build-obj bug.zig
```

**Comment by andrewrk** [comment]
Solved by @boothby in 47a0e3ec5ecd58f47d8ef81909ecd61fbe777bfc
