### ISSUE TITLE
support compiling and linking c++ code

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#4786]
Zig supports compiling and linking C code because we already depend on libclang for translate-c. But Clang is also a c++ compiler. It's not really much more work to also support compiling and linking c++ code. I looked into it and it looks like it amounts to about 20k more lines to ship both libc++ and libc++abi.

Note that this does *not* include translating C++ code.

This would go a long way toward #853, and it would make `zig cc` even more useful. It also serves the use case of using zig as a build system and package manager for C/C++ projects.

**Comment by adontz** [comment]
How C++ specific features will work? Like exceptions, for instance.

**Comment by jacereda** [comment]
I would be quite happy even if it compiled with `-fno-exceptions`.

**Comment by MasterQ32** [comment]
> How C++ specific features will work? Like exceptions, for instance.

> I would be quite happy even if it compiled with -fno-exceptions.

It's already possible to build C++ code with exceptions, RTTI and so on with zig today, but you need an external c++ standard library for this. This issue is about providing a c++ standard library with the zig tar ball itself and cross-build that the same way the libc is currently built.

**Comment by adontz** [comment]
> It's already possible to build C++ code with exceptions, RTTI and so on with zig today, but you need an external c++ standard library for this. This issue is about providing a c++ standard library with the zig tar ball itself and cross-build that the same way the libc is currently built.

Yes, but what will be syntax for catching and throwing exceptions? for dynamic_cast?

**Comment by MasterQ32** [comment]
> Yes, but what will be syntax for catching and throwing exceptions? for dynamic_cast?

I think your're confusing something here. This issue is *not* about adding support for interfacing classes and C++ code into Zig (Language), but compiling C++ code with the Zig toolchain. Quote on this:

> Note that this does not include translating C++ code.

Which would be required to interface C++ code the same way as C code is translated. And i don't think it should be in scope of the language to ever interface another language than C as it is  
humongous work and most languages (including c++) don't really have a stable ABI

**Comment by adontz** [comment]
What is the point then? C++ code will throw recoverable exception, like ios_base::failure, and crash entire process.

**Comment by LakeByTheWoods** [comment]
This would (for example) allow a c++ library that exposes a c interface to be built and used in zig.

**Comment by adontz** [comment]
> This would (for example) allow a c++ library that exposes a c interface to be built and used in zig.

Build - yes. I am not sure sure about "used" part. And by "used" I mean not only success path. Zig will have to support C++ exceptions at least to print meaningful stack trace, to say nothing about defer statements as part of stack unwinding.

**Comment by MasterQ32** [comment]
It's not zigs job to fix badly written C++ libraries that violate ABIs by throwing exceptions through C code. Zig does not require stack unwinding for c++ exceptions in the same way as C or any other language does not need this. C++ exceptions are an implementation detail and this should stay like this.

**Comment by adontz** [comment]
Okay, if that makes sense...

**Comment by jbsolomon** [comment]
sorry to hijack this (actually I came here intending to open an issue but it seems there is some discussion already) -- but there are compilers which support the use of libclang to compile _and use_ C++ in the same compilation unit as the host language:

https://wiki.dlang.org/Calypso
https://github.com/clasp-developers/clasp

and others.  I think their implementation is _really_ hairy, but yes, this is a thing.  It sure would be neat to use LLVM from within Zig without having to rely on the C interface.  I don't think LLVM MLIR even _has_ a meaningfully updated C interface (could be wrong about that!)

Anyway, feel free to cut this off or move discussion to somewhere else, but people will come to this issue thinking this is about the in-compiler use of C++ natively.
