### ISSUE TITLE
error: type '*Stream' has no member called 'Error'

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#4800]
I can't figure out why the pub const Error is not acceptable.
    
    pub fn main() !void {
        const std = @import("std");
        const Stream = struct {
            pub fn writeAll(self: T, buffer: []const u8) Error!void {}
            pub const Error = error{SomeError};
        };
        var stream: Stream = undefined;
        try std.fmt.format(&stream, "{x}", .{0});
    }

    0.5.0+39589cffe
    
    /root/zig/lib/zig/std/fmt.zig:319:22: error: type '*Stream' has no member called 'Error'
    ) @TypeOf(out_stream).Error!void {
                         ^
    /root/zig/lib/zig/std/fmt.zig:319:28: note: called from here
    ) @TypeOf(out_stream).Error!void {
                               ^
    ./defect.zig:8:27: note: called from here
            try std.fmt.format(&stream, "{x}", .{0});
                              ^
    ./defect.zig:1:25: note: called from here
        pub fn main() !void {
                            ^
    /root/zig/lib/zig/std/fmt.zig:213:35: note: referenced here
                        try formatType(
                                      ^
    ./defect.zig:8:9: note: referenced here
            try std.fmt.format(&stream, "{x}", .{0});
            ^
    /root/zig/lib/zig/std/start.zig:259:40: note: referenced here
                const result = root.main() catch |err| {
                                           ^

**Comment by fengb** [comment]
`std.fmt.format` now takes an actual instance instead of a pointer. The compile error could be more helpful in debugging though.

**Comment by markfirmware** [comment]
Thanks! Now this spews errors unless the file: u32 is removed. I moved that field to a global variable for the time being.

    pub fn main() !void {
        var stream: struct {
            file: u32,
            pub fn writeAll(self: *@This(), buffer: []const u8) !void {}
            pub const Error = error{SomeError};
        } = undefined;
        try @import("std").fmt.format(stream, "{}", .{0});
    }

**Comment by daurnimator** [comment]
@markfirmware you should be using `io.OutStream` to create a stream rather than making it like that.

**Comment by markfirmware** [comment]
@daurnimator I see that File.outStream().print() does what I want.

What about these compile errors just for adding an unused field? Should I open another issue in case this exposes a latent defect in something?

**Comment by daurnimator** [comment]
> What about these compile errors just for adding an unused field? Should I open another issue in case this exposes a latent defect in something?

Which compile errors? Please share the code and the error message...

**Comment by markfirmware** [comment]
See https://github.com/ziglang/zig/issues/4825
