### ISSUE TITLE
Hello world doesn't compile?

### ISSUE THREAD

**Issue by wilg** [ziglang/zig#4805]
From https://ziglang.org/documentation/master/

```
const std = @import("std");

pub fn main() !void {
    const stdout = std.io.getStdOut().outStream();
    try stdout.print("Hello, {}!\n", .{"world"});
}
```

```
› zig build-exe hello.zig
/Users/wil/Code/stardust/hello.zig:5:39: error: expected token 'Symbol', found '{'
    try stdout.print("Hello, {}!\n", .{"world"});
```

```
› zig version
0.5.0
```

macOS / Homebrew

Perhaps I am dumb as I am up late.

**Comment by LemonBoy** [comment]
The documentation you're reading refers to the `master` version of the Zig compiler whereas you're using version `0.5.0`, the compiler is too old to understand the new syntax for anonymous literals.

**Comment by wilg** [comment]
OK, but the instructions on the website should work. First impressions matter!

**Comment by wilg** [comment]
For reference, what got me is I opened these two links.

<img width="884" alt="Screen Shot 2020-03-25 at 11 39 01 AM" src="https://user-images.githubusercontent.com/54353/77573065-542e8380-6e8d-11ea-81d6-4b9d60ea3588.png">

**Comment by haze** [comment]
The install from package manager link has instructions for installing zig from master, which is also what the documentation is listed under (master).

**Comment by wilg** [comment]
I understand what's going on looking at it know, but it's confusing so I've provided the image in case it helps improve the UX.

**Comment by marler8997** [comment]
Maybe:

You can also [install Zig from a package manager](https://github.com/ziglang/zig/wiki/Install-Zig-from-a-Package-Manager). Be sure to use the "Documentation" for the version installed by your package manager.

**Comment by andrewrk** [comment]
There's plenty of work to do as we incrementally make progress towards 1.0.  Many problems to solve. This is one problem that will go away on its own soon enough without trying to solve it. My suggestion is to focus efforts on things that have a better cost/reward ratio.

It's entirely likely that the "hello, world" of 0.6.0 (due in 2 weeks) will be compatible with zig 1.0.

**Comment by marler8997** [comment]
Looks like someone had this same issue on reddit: https://www.reddit.com/r/Zig/comments/frjw76/hello_world_not_working/

My guess is that the new `zig cc` feature is bringing in a slew of new people checking out the language.  There appears to be a spattering of new posts on reddit from people trying out the language.  Cool stuff.
