### ISSUE TITLE
website broken in Firefox

### ISSUE THREAD

**Issue by networkimprov** [ziglang/zig#4806]
On FF, I see the following. On Chrome, it seems OK.

---
![image](https://user-images.githubusercontent.com/458838/77526245-81584300-6e47-11ea-8ff3-c3cebd80a4d9.png)

**Comment by daurnimator** [comment]
Looks fine in FF to me. Which version/platform are you on?

**Comment by networkimprov** [comment]
FF 74.0 Win7 amd64. Problem appears on all pages I checked. I tried shift-reload.

The web console is empty, even for CSS :-/
