### ISSUE TITLE
riscv32-freestanding has no .text

### ISSUE THREAD

**Issue by fwsGonzo** [ziglang/zig#4809]
I don't particularly need a libc init that calls main, but it should follow the standard and reference _start. Instead I get an empty binary. I guess this is what Tier 4 support means? It also starts at 0x0 which is slightly unfortunate.

```
$ riscv32-unknown-elf-readelf -a test
...
At least it has a program header:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  PHDR           0x000034 0x00010034 0x00010034 0x00060 0x00060 R   0x4
```

**Comment by andrewrk** [comment]
can I see your source and build command?

**Comment by fwsGonzo** [comment]
I'm completely new, so there isn't much to see:
```
pub fn _start() !void {
}
```
Don't really expect that zig functions use the C calling convention, athough on RISC-V there is only one calling convention, so it shouldn't matter.
```
$ zig build-exe -target riscv32-freestanding test.zig 
```
That's my build command which I suspect is not ideal! :)

**Comment by andrewrk** [comment]
you need `export` on that function, to make it show up in the object.

Try removing and adding `export` here and see: https://godbolt.org/z/AU7nY0

**Comment by fwsGonzo** [comment]
Many thanks. I have this startup code I wrote for RISC-V:
https://github.com/fwsGonzo/libriscv/blob/master/binaries/zig

I have some startup code in C that I already wrote (with some glibc help), however, how do I call the regular Zig main function from C?

**Comment by andrewrk** [comment]
https://ziglang.org/documentation/master/#Exporting-a-C-Library

**Comment by andrewrk** [comment]
You're welcome to keep asking questions here, but there no actionable task for zig project, so it will be closed. You can also ask questions in any places here: https://github.com/ziglang/zig/wiki/Community
