### ISSUE TITLE
aarch64-linux-musl Target: lld: error: undefined symbol: __divtf3

### ISSUE THREAD

**Issue by jlsantiago0** [ziglang/zig#4817]
Using zig-linux-x86_64-0.5.0+39589cffe.tar.xz from here https://ziglang.org/download/. I was working through the examples here https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html When building the aarch64-linux-musl example:

```
   git clone https://github.com/LuaJIT/LuaJIT
   cd LuaJIT
   export CC="zig cc -target aarch64-linux-musl"
   export HOST_CC="zig cc"
   make CC="${CC}" HOST_CC="$HOST_CC" TARGET_STRIP="echo"

```

 I get the following error toward the final link step:

```
BUILDVM   jit/vmdef.lua
DYNLINK   libluajit.so
libluajit.so
lld: error: undefined symbol: __divtf3
>>> referenced by floatscan.c
>>>               /home/jsantiago/.cache/zig/stage1/o/uWVgyB4v68a_3gJJ5VBPDedmbafvPJmpA-vA3XrwSA1HZpIMrduwDl5pXuMK5FKE/floatscan.o:(__floatscan) in archive /home/jsantiago/.cache/zig/stage1/o/twfa4jU9S1ra0pgCP3DXK391Xoo2Y3a425sV81WBQ3dXIjRAJ2pxzZFP5V0DCe2S/libc.a
>>> referenced by fmodl.c
>>>               /home/jsantiago/.cache/zig/stage1/o/YF5_Xrt8EkzCr9IILovXabLa0sMNM8XG-JXfDMW19xfPNHvjg-Tn8SREtta44qLn/fmodl.o:(fmodl) in archive /home/jsantiago/.cache/zig/stage1/o/twfa4jU9S1ra0pgCP3DXK391Xoo2Y3a425sV81WBQ3dXIjRAJ2pxzZFP5V0DCe2S/libc.a
>>> did you mean: __divdf3
>>> defined in: /home/jsantiago/.cache/zig/stage1/o/Yu_q_fJqy9bj7YpRjPO_LQlzfGapZ8AzxCP04xFmpST86ZiM5YQL3vauXJ1TGTKO/libcompiler_rt.a(/home/jsantiago/.cache/zig/stage1/o/Yu_q_fJqy9bj7YpRjPO_LQlzfGapZ8AzxCP04xFmpST86ZiM5YQL3vauXJ1TGTKO/compiler_rt.o)
```

NOTE: It works fine when I use the x86_64-linux-musl and aarch64-linux-gnu targets. My host operating system is Manjaro Linux.

**Comment by LemonBoy** [comment]
`__divtf3` was added in cc774c6

**Comment by andrewrk** [comment]
@jlsantiago0 we've had some trouble getting the CI tests to pass on aarch64 over the last couple days, so the master branch builds on ziglang.org are stuck on an older build. Trying to fix it, will let you know when it's done.

**Comment by jlsantiago0** [comment]
Outstanding. Thank You.

**Comment by andrewrk** [comment]
463b90b977ba4817f6cf90a85e8609092f53dfd2 passed the CI and the download page is updated. That version has `__divtf3`.
