### ISSUE TITLE
-target-glibc not supported in zig-linux-x86_64-0.5.0+39589cffe

### ISSUE THREAD

**Issue by jlsantiago0** [ziglang/zig#4818]
I can use the following command with the 0.5.0 release build:

```
/mnt/share/toolchains/linux-x86_64/zig-0.5.0/zig build-exe \
    --c-source test.c --library c --verbose-cc \
    -target x86_64-linux-gnu -target-glibc 2.12
```
But when I try it with the https://ziglang.org/builds/zig-linux-x86_64-0.5.0+39589cffe.tar.xz from here https://ziglang.org/download/. I get the following error:
```
Invalid argument: -target-glibc
See `/mnt/share/toolchains/linux-x86_64/zig/zig --help` for detailed usage information
```

**Comment by andrewrk** [comment]
This changed recently, you want:

`-target x86_64-linux-gnu.2.12`

**Comment by jlsantiago0** [comment]
Perfect. Thank you.
