### ISSUE TITLE
error with unused field

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#4825]
An unused file: u32 field causes an error.

    pub fn main() !void {
        var stream: struct {
            file: u32,
            pub fn writeAll(self: *@This(), buffer: []const u8) !void {}
            pub const Error = error{SomeError};
        } = undefined;
        try @import("std").fmt.format(stream, "{}", .{0});
    }
    
    /root/zig/lib/zig/std/fmt.zig:953:17: error: expected type '*struct:2:21', found '*const struct:2:21'
                try out_stream.writeAll(@as(*const [1]u8, &zero_byte)[0..]);
                    ^
    /root/zig/lib/zig/std/fmt.zig:892:33: note: called from here
            return formatIntUnsigned(int_value, base, uppercase, options, out_stream);
                                    ^
    /root/zig/lib/zig/std/fmt.zig:540:21: note: called from here
        return formatInt(int_value, radix, uppercase, options, out_stream);
                        ^
    /root/zig/lib/zig/std/fmt.zig:497:52: note: called from here
            .Int, .ComptimeInt => return formatIntValue(value, fmt, options, out_stream),
                                                       ^
    /root/zig/lib/zig/std/fmt.zig:334:31: note: called from here
                return formatValue(value, fmt, options, out_stream);
                                  ^
    /root/zig/lib/zig/std/fmt.zig:182:35: note: called from here
                        try formatType(
                                      ^
    ./issue:7:38: note: called from here
            try @import("std").fmt.format(stream, "{}", .{0});
                                         ^
    ./issue:1:25: note: called from here
        pub fn main() !void {
                            ^
    /root/zig/lib/zig/std/fmt.zig:953:17: note: cast discards const qualifier
                try out_stream.writeAll(@as(*const [1]u8, &zero_byte)[0..]);
                    ^
    /root/zig/lib/zig/std/fmt.zig:953:36: note: referenced here
                try out_stream.writeAll(@as(*const [1]u8, &zero_byte)[0..]);
                                       ^
    /root/zig/lib/zig/std/fmt.zig:334:31: error: expected type 'Error!void', found '@TypeOf(std.fmt.formatValue).ReturnType.ErrorSet!void'
                return formatValue(value, fmt, options, out_stream);
                                  ^
    /root/zig/lib/zig/std/fmt.zig:182:35: note: called from here
                        try formatType(
                                      ^
    ./issue:7:38: note: called from here
            try @import("std").fmt.format(stream, "{}", .{0});
                                         ^
    ./issue:1:25: note: called from here
        pub fn main() !void {
                            ^
    /root/zig/lib/zig/std/fmt.zig:334:31: note: error set '@TypeOf(std.fmt.formatValue).ReturnType.ErrorSet' cannot cast into error set 'Error'
                return formatValue(value, fmt, options, out_stream);
                                  ^

**Comment by LemonBoy** [comment]
Well the real problem is that you're implementing the output stream in a incorrect way, you should use something like `std.io.OutStream(struct { file: u32 }, error{SomeError}, my_write_fn)`.

Your interface implementation is missing several fields and even `writeAll` is wrong as the expected prototype is `fn (context: Context, bytes: []const u8) WriteError!usize` (notice that the context is passed by value).

**Comment by markfirmware** [comment]
I see.
