### ISSUE TITLE
translate-c doesn't understand automatic sized arrays.

### ISSUE THREAD

**Issue by BarabasGitHub** [ziglang/zig#4831]
Zig version: 0.5.0+aec4967f3

Trying to translate this C code
```
const uint32_t shader_data[] = {1, 2, 3, 4};
```
results in
```
pub export const data: [*c]const c_uint = [4]c_uint{
    @bitCast(c_uint, @as(c_int, 1)),
    @bitCast(c_uint, @as(c_int, 2)),
    @bitCast(c_uint, @as(c_int, 3)),
    @bitCast(c_uint, @as(c_int, 4)),
};
```
which fails to compile as zig, because it thinks data is a pointer while it's actually an array.

**Comment by BarabasGitHub** [comment]
I was trying to look into it and thought Zig used the std to do parse the `@cImport`-ed files,  but it seems the whole `c\parse.zig` file is full of never compiled code??? I can remove all of it and still build zig and it doesn't seem to have any tests? So... that means it isn't called anywhere and since it doesn't have tests either it never actually gets compiled, right?

Or I'm just totally missing something.

**Comment by he-la** [comment]
See #4045 for discussion on `std.c.parse`; translate-c currently implements parsing in `src-self-hosted/translate-c.zig`.
