### ISSUE TITLE
expected type '?*.cimport:1:11.struct__win_st', found '?*.cimport:1:11.struct__win_st'

### ISSUE THREAD

**Issue by koljakube** [ziglang/zig#4848]
I guess I'm missing something in the docs, but just in case:

I'm currently playing around with using ncurses from zig. The library makes heavy use of passing around pointers to "windows" of (C) type `Window*`.

My first steps were wrapping a lot of C functions to make their usage more zig-like, introducing error types and such. Also, since there are a lot of functions, I am trying to split up the sources into files containing functions as they are mentioned in the man pages of ncurses, or else I would end up with one way too big file.

I tried extracting some definitions out into a separate source file (`common.zig`) that is imported by the other file, including the line

```
pub const Window = c.WINDOW;
```

with `c` being the import ncurses.h, and then using this alias as a paramter for other functions. Example:

```
const common = @import("ncurses/common.zig");
pub fn wkeypad(window: *common.Window, enable: bool) common.CursesError!void {
    if (c.keypad(window, enable) == common.Err) {
        return common.CursesError.General;
    }
}
```

But that gives me the following error:

```
./src/ncurses.zig:30:18: error: expected type '?*.cimport:1:11.struct__win_st', found '?*.cimport:1:11.struct__win_st'
```

which looks somewhat nonsensical (unless the seperate compilation units cannot reconciliate the imports they include). It works if I explicitely cast the pointer:

```
pub fn wkeypad(window: *common.Window, enable: bool) common.CursesError!void {
    if (c.keypad(@ptrCast(*c.WINDOW, window), enable) == common.Err) {
        return common.CursesError.General;
    }
}
```

But that prevents me from factoring out type definitions. How can I define and reuse zig pointers based on C pointers?

**Comment by andrewrk** [comment]
do you bychance have more than 1 `@cImport` ?

**Comment by koljakube** [comment]
Wow, you are quick. Yes, that was the problem. I just changed the program to use the cImport from `common.zig` by re-exporting the import from there. Now I don't need the casts anymore.

I must admit that I only skimmed the docs for @cImport, but now that I read them, I don't think they would have addressed my problem. Thanks for the solution!

**Comment by andrewrk** [comment]
:+1:
