### ISSUE TITLE
assertion failed

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#4869]
0.5.0+b980568c8
zig build-exe main.zig
when analyzing /root/github.com/ziglang/zig/main.zig:4:13: assertion failed.

    export const vector_table = vectorTable();
        fn vectorTable() [1]fn () noreturn {
            return .{
                @intToPtr(fn () noreturn, 0x20004000),
            };
        }

**Comment by markfirmware** [comment]
Simpler case

    export const vector_table = vectorTable();
    const t = fn () void;
    fn vectorTable() t {
        return @intToPtr(t, 0x20004000);
    }

**Comment by xackus** [comment]
You need to specify the calling convention. Of course the crash still needs to be fixed into an error.

**Comment by markfirmware** [comment]
> You need to specify the calling convention. Of course the crash still needs to be fixed into an error.

Thanks!

**Comment by Vexu** [comment]
No longer relevant with the function pointer change since all pointers to non-comptime-only types are considered C ABI compatible.
