### ISSUE TITLE
Building Zig on Windows uses unsupported options

### ISSUE THREAD

**Issue by jbsolomon** [ziglang/zig#4877]
Hi.  I'm building Zig from source using the MSVC terminal with `-DCMAKE_BUILD_TYPE=Release`.  I'm getting lots of warnings that look like this:

```
[161/168] Building C object CMakeFiles\opt_c_util.dir\src\blake2b.c.obj
cl : Command line warning D9002 : ignoring unknown option '-std=c99'
cl : Command line warning D9002 : ignoring unknown option '-O3'
[166/168] Building CXX object CMakeFiles\zig.dir\src\main.cpp.obj
cl : Command line warning D9002 : ignoring unknown option '-std=c++14'
```

This makes me think that I'm probably not getting a release-optimized build.  Are you setting these parameters manually in CMake?  If so, you might want to think about tuning the MSVC command-line options.

"-std" is not a supported option and neither is "-O\<x\>".

Here is the documentation for cl.exe's optimization options: https://docs.microsoft.com/en-us/cpp/build/reference/o-options-optimize-code?view=vs-2019

Here's the doc for its C++ standard options: https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=vs-2019

https://github.com/ziglang/zig/blob/45dc2587a395c02afb12f1781f3539d4bc77c225/CMakeLists.txt#L227

**Comment by daurnimator** [comment]
@jbsolomon Could you try this patch?
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 9e54f8cf6..3329acb13 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -315,7 +315,11 @@ include_directories(
 )
 
 # These have to go before the -Wno- flags
-set(EXE_CFLAGS "-std=c++14")
+if(MSVC)
+    set(EXE_CFLAGS "/std:c++14")
+else()
+    set(EXE_CFLAGS "-std=c++14")
+endif()
 if("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
     if(MSVC)
         set(EXE_CFLAGS "${EXE_CFLAGS} /w")
@@ -333,7 +337,11 @@ else()
     endif()
 endif()
 
-set(OPTIMIZED_C_FLAGS "-std=c99 -O3")
+if(MSVC)
+    set(OPTIMIZED_C_FLAGS "-std=c99 /w")
+else()
+    set(OPTIMIZED_C_FLAGS "-std=c99 -O3")
+endif()
 
 set(EXE_LDFLAGS " ")
 if(MSVC)
```

**Comment by jbsolomon** [comment]
@daurnimator no, because those are still wrong.  The correct ones are in my PR #4879.

**Comment by andrewrk** [comment]
Thanks for the PR which landed in https://github.com/ziglang/zig/commit/9bb76f8ce0b36211e0ff1f502ec46aa5a0142cd0
