### ISSUE TITLE
use zig as a c compiler

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#490]
```
zig cc foo.c
```

All args after `cc` are args exactly as you would pass to clang. We depend on libclang, might as well expose it.

In the std build API, the default way to compile C code would be with this, instead of with an external compiler. Using an external compiler is still useful and supported, however.

Being a C++ compiler is a little tricker, since we would need to know the location of libstdc++ in addition to libc, and all the weird versioning stuff that goes along with it.

**Comment by PavelVozenilek** [comment]
There should be some macro identifying that it is "zig compiler" and its version.

**Comment by andrewrk** [comment]
Sure, we can do:

```c
#define __zig__ 1
#define __zig_version__ "0.0.0"
#define __zig_major__ 0
#define __zig_minor__ 0
#define __zig_patchlevel__ 0
```
to match clang. The corresponding clang defines will still exist.

**Comment by hostilefork** [comment]
@andrewrk said:

> Sure, we can do:
>
>      #define __zig__ 1

This doesn't seem to be the case when using **zig cc** in version `0.11.0-dev.3883+7166407d8`.

Is there another approved way to detect compilation under zig?
