### ISSUE TITLE
CrossTarget.parse test fails on cross compiled armv7-linux-musleabihf 

### ISSUE THREAD

**Issue by FireFox317** [ziglang/zig#4902]
parsed target: `native-native-gnueabihf.2.1.1`

stack trace:
```
/home/pi/zig-source/lib/std/zig/cross_target.zig:767:38: 0x47e8b in zig.cross_target.test "CrossTarget.parse" (test)
        std.testing.expectEqualSlices(u8, "native-native-gnu.2.1.1", text);
```

All the other tests pass!

**Comment by andrewrk** [comment]
Nice, and it's the test case that is wrong, not the implementation. Want to update the test case?

**Comment by FireFox317** [comment]
Definitely! How do I determine the expected output?

**Comment by andrewrk** [comment]
I think the test should be skipped under more conditions, so for example it should be run only if `isGnuLibC() and Target.current.abi == .gnu`.
