### ISSUE TITLE
error.BadPathName on windows

### ISSUE THREAD

**Issue by drsneed** [ziglang/zig#4913]
```
const std = @import("std");

test "File Test" {
    const testFile = try std.fs.cwd().openFile("src/myfile.txt", std.fs.File.OpenFlags{ .read = true, .write = false });
    testFile.close();
}
```

This fails with the following error:
> W:\SDKs\zig\lib\zig\std\os\windows.zig:1252:50: 0x7ff71e843e39 in std.os.windows.sliceToPrefixedSuffixedFileW (test.obj)
            '/', '*', '?', '"', '<', '>', '|' => return error.BadPathName,

This is a valid path and shouldn't fail. If I replace the slash with \\ it works.

**Comment by gereeter** [comment]
Previous discussion is in #2668.

**Comment by drsneed** [comment]
Thanks this is a dup then.
