### ISSUE TITLE
Recursive folder issue when building on Windows

### ISSUE THREAD

**Issue by SuperAuguste** [ziglang/zig#4914]
Version: 0.5.0+f6d384450

I've built zig from source, and when I opened the `lib` folder after a few hours of usage, it contained a folder called `zig` that contained the contents of the `lib` folder (including a folder called `zig`, which also contained the contents of the lib folder), and on and on and so forth. I'm still trying to delete all of the recursive folders (3.75 GB so far) and have no idea what's caused them to appear.

**Comment by SuperAuguste** [comment]
Turns out that `msbuild` duplicates the `lib` folder into the `lib` folder of your local directory, and as I built Zig in the root directory of the git repo instead of in a `build-release` folder, it copied my `lib` folder into my `lib` folder infinitely.

**Comment by BarabasGitHub** [comment]
That can't really have been the issue...
My build script is this .bat file:
```
@call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
"E:\Applications\CMake\bin\cmake.exe" -Bbuild-release . -Thost=x64 -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH=E:\Libraries\llvm+clang+lld-10.0.0-x86_64-windows-msvc-release-mt -DCMAKE_BUILD_TYPE=RelWithDebInfo
msbuild -maxCpuCount -p:Configuration=RelWithDebInfo build-release\INSTALL.vcxproj
```
which I always run from the root directory of the repo.

I'm on: 0.5.0+c4b3c84b3
