### ISSUE TITLE
error: cast to union must initialize field

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#4916]
pub fn main() void {
        const Key = union(enum) {
            Args: struct {
                len: u8,
            },
        };
        var key: Key = Key.Args;
        @import("std").debug.warn("{}", .{key});
    }

    0.5.0+5314641e1

    ./issue.zig:7:23: error: cast to union 'Key' must initialize 'struct:3:15' field 'Args'
        var key: Key = Key.Args;
                          ^
    ./issue.zig:3:9: note: field 'Args' declared here
            Args: struct {
            ^

There is no error if I remove the ": Key" from the var statement

**Comment by daurnimator** [comment]
`Key.Args` is an enum of type `@TagType(Key)`.

You need to use: `var key: Key = Key{ .Args = .{ .len = 42 } };`

**Comment by markfirmware** [comment]
Thanks!
