### ISSUE TITLE
Unreachable in handle_is_ptr

### ISSUE THREAD

**Issue by Sobeston** [ziglang/zig#4934]
console:
```
> zig build-exe .\main.zig
Unreachable at D:\a\1\s\src\analyze.cpp:5189 in handle_is_ptr. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
```
main.zig:
```zig
const X = @OpaqueType();
const Y = struct {
    someFuncPtr: fn (X) void,
};
pub fn main() void {
    var z: *Y = undefined;
}
```
Cause: putting X instead of *X in the type of a function pointer field.

Minimal:
```zig
pub fn main() void {
    const someFuncPtr: fn (@OpaqueType()) void = undefined;
}
```

**Comment by LemonBoy** [comment]
The fix is easy, check out `ir_resolve_lazy_fn_type` and `analyze_fn_type` (two functions doing the very same thing with only minor differences, yay). The former is missing some checks that are only in the latter.
