### ISSUE TITLE
Runtime behavior changes depending on read-only variable access

### ISSUE THREAD

**Issue by koljakube** [ziglang/zig#4947]
While playing around with wrapping ncurses, I ran into the following problem:

Given the following files:

main.zig:
```
const std = @import("std");
const nc = @import("import.zig");
const c = nc.c;

pub fn main() !void {
    _ = c.initscr();
    nc.start_color();

    // const pCLRS = &c.COLORS;

    if (nc.COLORS) |clrs| {
        std.debug.warn("COLORS: {}\n", .{clrs});
    }

    std.time.sleep(1000000000);
}
```

import.zig:
```
const std = @import("std");
pub const c = @cImport({
    @cInclude("ncurses.h");
});

pub var COLORS: ?i32 = null;

pub fn start_color() void {
    _ = c.start_color();

    COLORS = c.COLORS;
}
```

Compile and run with: `zig build-exe --library ncurses main.zig && ./main`

The output is "COLORS: 0". By commenting in line 9 of `main.zig`, the output changes to "COLORS: 256". Tested on macOS 10.15.4 using zig 0.5.0+1568470c4, [verified on Linux](https://freenode.irclog.whitequark.org/zig/2020-04-05#26731567).

I managed to create this problem without pointers (with a `warn()` instead of the pure read), but build this example first. My suspicion is that the access triggers some kind of runtime behavior, and that explicitly marking the `COLORS` assignment in `start_color()` as a runtime operation would fix this, but I can't prove it yet.

A runtime equivalent to `comptime` might be a good idea anyhow.

**Comment by LemonBoy** [comment]
Global variables suck.

Ncurses defines an external variable named `COLORS` and so does `import.zig`. The compiler is dumb and clumps together all the (scope-)global variables together without any kind of namespacing, this means that any variable named `COLORS` will alias the other with the same name.

Adding `const pCLRS = &c.COLORS;` generates a nice conflict that translates into the following LLVM IR:
```llvm
@COLORS = external global i32, align 4
@COLORS.1 = internal unnamed_addr global %"?i32" { i32 undef, i1 false }, align 4
```

You were lucky enough, the extern variable won over the global one and the code behaves as intended.

**Comment by andrewrk** [comment]
To be clear the intended behavior here is that `pub var`s cannot clobber external symbols. The `pub var COLORS` is the one that is supposed to get the mangling/namespacing.

**Comment by koljakube** [comment]
Thanks for the explanation, helps a lot to understand what's going on. That lets me work around the problem for now.
