### ISSUE TITLE
Proposal: move big.Rational.gcd to big.Int

### ISSUE THREAD

**Issue by joachimschmidt557** [ziglang/zig#4950]
`big.Rational` contains two private functions `gcd` and `gcdLehmer` which operate only on `big.Int`s.

https://github.com/ziglang/zig/blob/6ef15fc8d00c06bc767b91515e2c919448948e6f/lib/std/math/big/rational.zig#L468

https://github.com/ziglang/zig/blob/6ef15fc8d00c06bc767b91515e2c919448948e6f/lib/std/math/big/rational.zig#L500

Would it make sense to move these functions into `big.Int` and make them public? If yes, I'd be happy to create a PR for that.

**Comment by andrewrk** [comment]
cc @tiehuis

**Comment by tiehuis** [comment]
This sounds good to me. I would only make the `gcd` function public and keep the specific algorithm implemented an internal detail. It may change in the future based on the inputs provided.

**Comment by joachimschmidt557** [comment]
Ok, I'll create a PR for this.
