### ISSUE TITLE
vector shift operators test disabled on multiple architectures

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#4951]
https://github.com/ziglang/zig/blob/cb98984ae6fa73ab3e4ad660af272d8604f513fa/test/stage1/behavior/vector.zig#L448-L467

**Comment by andrewrk** [comment]
The next step for each architecture is to create a reduction of LLVM IR and get a nice bug report filed upstream.

**Comment by nektro** [comment]
just tested this with `aarch64` and `riscv64`, this test now passes

**Comment by sskras** [comment]
@nektro, what should I need to test that part – just to comment out the corresponding architecture in that block?

BTW, the file now is seemingly located here:
https://github.com/ziglang/zig/blob/2fdc9e6ae8b6f1ec86050011e1170d639d8c9c2c/test/behavior/vector.zig#L719-L738

**Comment by nektro** [comment]
yes, i should've opened a pr back then
