### ISSUE TITLE
Can not compile HEAD brunch on Macosx

### ISSUE THREAD

**Issue by heibor** [ziglang/zig#4956]
On Macosx, when I run `brew upgrade zig --fetch-HEAD`, I got these errors:

Undefined symbols for architecture x86_64:
  "getPollyPluginInfo()", referenced from:
      (anonymous namespace)::EmitAssemblyHelper::EmitAssemblyWithNewPassManager(clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream> >) in libclangCodeGen.a(BackendUtil.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [zig0] Error 1
make[1]: *** [CMakeFiles/zig0.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

My Macosx is Catalina 10.15.4. I want to knwo if there is a solution on Macosx.

Thanks.

**Comment by andrewrk** [comment]
#4949

**Comment by heibor** [comment]
I see, thank you.
