### ISSUE TITLE
Implement --version command

### ISSUE THREAD

**Issue by r3muxd** [ziglang/zig#4967]
There's no --version command, making it hard to tell what zig version in a distro is which.

**Comment by data-man** [comment]
`zig --help`

> Commands:
> ...
> `version          print version number and exit`
> ...

**Comment by andrewrk** [comment]
```
$ zig version
0.5.0+e4eb817f7
```

**Comment by ajTronic** [comment]
`zls --version` works, but `zig --version` does not. Maybe `zig --version` should be implemented, for completeness? I was confused when `zig --version` didn't work after using `zls --version`.

**Comment by xdBronch** [comment]
zls is not affiliated with the zig project, it doing something is not a reason for zig to do the same

**Comment by ajTronic** [comment]
I understand. Maybe I should create an issue in the zls repo?

**Comment by ert78gb** [comment]
zig equivalent is `zig version`. Output `0.15.0-dev.1557+6bcdcf85c`
