### ISSUE TITLE
Zig Examples 

### ISSUE THREAD

**Issue by jussij** [ziglang/zig#4969]
I'm using the the 0.5.0 version of the Zig compiler.

From the Zig home page: https://ziglang.org/#Zig-competes-with-C-instead-of-depending-on-it

Taking the _'hello world'_ example from that page:
```
const std = @import("std");

pub fn main() void {
    std.debug.warn("Hello, world!\n", .{});
}

```
Compiling that file produces this error:

```
C:\TEMP>zig build-exe test.zig
C:\TEMP\test.zig:4:40: error: expected token 'Symbol', found '{'
    std.debug.warn("Hello, world!\n", .{});
                                       ^
```

Changing the code to be as follows:

```
const std = @import("std");

pub fn main() void {
    std.debug.warn("Hello, world!\n");
}
```

Compiles and runs as expected.

Many of the examples on that landing page share this same issue.

**Comment by Sobeston** [comment]
The stuff on the home page is kept up to date with master - grab a master build instead of 0.5. 0.6 is due within the next couple of weeks.

**Comment by joachimschmidt557** [comment]
For the Hello World example for zig 0.5.0, see https://ziglang.org/documentation/0.5.0/#Hello-World
