### ISSUE TITLE
Cannot build and run zig using 'zig build run' command on MAC OS.

### ISSUE THREAD

**Issue by rillk500** [ziglang/zig#4977]
I am new to Zig. I created a new folder called hello_world, and used 'zig init-exe' command to init the project. Then I edited the source file into traditional 'Hello World' program. When I try to compile with 'zig build' or 'zig build run' command i get the following error:

"Build Dependencies...Undefined symbol: tests/hello_world/zig-cache/o/LSGjUX94fChc9_nDwse0U1k6srNpOoig8Y99mrpAPv5Pa48mygR0z5Oc08csjGkD/build.o: _futimens symbol(s) not found"

It does work if I compile it directly with 'zig build-exe main.zig'.

Am I doing something wrong? 
Is there a manual on how to use Zig package manager?

**Comment by andrewrk** [comment]
Can you provide more details about your operating system version? I don't understand why libSystem would be missing that function.

**Comment by rillk500** [comment]
Thank you for quick reply, I am using macOS Sierra v10.12.1.

**Comment by andrewrk** [comment]
This is outside the [range of supported macOS versions](https://ziglang.org/#Support-Table).

**Comment by marler8997** [comment]
It looks like Sierra came out 4 years ago, why wouldn't it be supported?

**Comment by daurnimator** [comment]
We only support versions of OSX still supported by Apple, and Apple only support 3 releases at a time.
