### ISSUE TITLE
expected type 'fn() type', found 'fn() var' - only one is generic

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#4984]
I can't figure out what is wrong here. a() should return the function b() which itself returns a type (here an empty struct.)

    ./aaa.zig:10:7: error: expected type 'fn() type', found 'fn() var'
        }).b;
          ^
    ./aaa.zig:10:7: note: only one of the functions is generic
        }).b;
          ^

    pub fn main() void {
        _ = a();
    }
    
    fn a() fn () type {
        return (struct {
            pub fn b() type {
                return struct {};
            }
        }).b;

**Comment by hiroakitakada** [comment]
A similar error occurs with the following code (comes from #5817).

```
fn comptime_add1(comptime x: u32) u32 {
    return x + 1;
}

fn apply(func: fn(u32) u32, x: u32) u32 {
    return func(x);
}

export var v1 = apply(comptime_add1, 1);
```

This code gets a compile error saying expected type `'fn(u32) u32', found 'fn(u32) var'`.
