### ISSUE TITLE
Zahn's construct

### ISSUE THREAD

**Issue by adontz** [ziglang/zig#4989]
https://en.wikipedia.org/wiki/Zahn%27s_construct

Seems interesting. Not sure about specific syntax.

**Comment by JesseRMeyer** [comment]
Zig alreadys supports binary-did break exit conditions on loops with the else clause.  This idea generalizes the concept to any number of break conditions.  I suppose if a proposal is desirable here, it's whether or not a loop can break an enum value which can be switched on where the else clause would go.

**Comment by andrewrk** [comment]
It does seem interesting, however, it is not planned. If you want to advocate for this, you are welcome to do so, and I will re-open. The burden of proof is on adding new things, not on not-having things.
