### ISSUE TITLE
@TypeInfo on @cImport crashes the compiler

### ISSUE THREAD

**Issue by hollmmax** [ziglang/zig#4997]
using version 0.5.0+487134554
```zig
const std = @import("std");
const warn = std.debug.warn;
const c = @cImport({
    @cInclude("stdio.h");
});

const TypeId = @import("builtin").TypeId;

test "libC reflection" {
    switch (@typeInfo(c)) {
        TypeId.Struct => |items| {
            warn("{}\n", .{items.decls.len});
        },
        else => warn("{}\n", .{@typeName(c)}),
    }
}
```

**Comment by Vexu** [comment]
By doing `items.decls.len` you are forcing all declarations in the translated `stdio.h` into existence. That includes many `long double` related macros which are causing you to hit TODOs in the compiler since `c_longdouble` is currently completely broken #1188.

**Comment by lodi** [comment]
I also ran into this issue today.  I thought maybe a simpler header would work...

```zig
const c = @cImport({
    @cInclude("stdbool.h");
});
```

But I get the same "TODO" compiler panic as OP.  In fact, I also get a panic with an empty import...

```zig
const c = @cImport({
});
```
(zig 0.6.0)

---

Would be amazing if this worked though; we could use zig to generate c library bindings for other languages.
