### ISSUE TITLE
support for parameters with callconv(.Interrupt) on x86_64

### ISSUE THREAD

**Issue by gwimm** [ziglang/zig#4998]
[LLVM supports taking the interrupt context with and optionally an error code as parameters for the `X86_INTR` calling convention.](https://github.com/llvm/llvm-project/blob/5d73f79c54788bc07dabe9ed75c36f12bafe9d28/llvm/include/llvm/IR/CallingConv.h#L179-L184)
Zig currently invalidates all `callconv(.Interrupt)` function parameters.

**Comment by LemonBoy** [comment]
> Zig currently invalidates all callconv(.Interrupt) function parameters.

What?

What's the problem exactly? What are you trying to do?

**Comment by daurnimator** [comment]
Context from discord:
> [13:36] capilli:
> ```
>     /// X86_INTR - x86 hardware interrupt context. Callee may take one or two
>     /// parameters, where the 1st represents a pointer to hardware context frame
>     /// and the 2nd represents hardware error code, the presence of the later
>     /// depends on the interrupt vector taken. Valid for both 32- and 64-bit
>     /// subtargets.
>     X86_INTR = 83,
> ```
> on x86_64 parameters are invalid in zig for callconv(.Interrupt) functions @andrewrk
> [14:02] andrewrk: that's good to know. would you mind filing an issue?

**Comment by LemonBoy** [comment]
You can already do that, there are no checks on the Zig side.

> ARMContextFrame

ARM?

**Comment by daurnimator** [comment]
> > ARMContextFrame
> 
> ARM?

oops; brain fail. I was researching the ARM abi at the same time in response to an IRC question

**Comment by Arnau478** [comment]
Wow, this has been postponed a lot... Is there any workaround?
