### ISSUE TITLE
Zig Does Not Like Tabs?

### ISSUE THREAD

**Issue by Kayomn** [ziglang/zig#4999]
Hi,

I've been missing around with the language now for about 2 minutes, doing a hello world, and I stumbled upon an error:

```
error: invalid character: '\t'
        var stdout = try std.io.getStdOut();
```

My compiler version is `0.5.0` and I'm using `zig-static` from the AUR.

Is this a bug or a conscious design decision?

**Comment by daurnimator** [comment]
See the faq: https://github.com/ziglang/zig/wiki/FAQ#why-does-zig-force-me-to-use-spaces-instead-of-tabs
