### ISSUE TITLE
zig clang, fatal error: 'stdarg.h' file not found 

### ISSUE THREAD

**Issue by zhaozg** [ziglang/zig#5000]
build it with `zig clang`

0.5.0+20a152b2a

```c
#include <stdio.h>
#include <stdarg.h>

int main()
{
  printf("Hello Zig\n");
  return 1;
}
```
output
```
$ zig clang b.c -v
clang version 10.0.0
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
 "/usr/local/bin/zig" -cc1 -triple x86_64-apple-macosx10.15.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name b.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mframe-pointer=all -fno-rounding-math -masm-verbose -munwind-tables -target-sdk-version=10.15.4 -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -target-linker-version 556.5 -v -resource-dir /usr/local/lib/clang/10.0.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include -internal-isystem /usr/local/lib/clang/10.0.0/include -internal-externc-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -fdebug-compilation-dir /Users/zhaozg/tmp -ferror-limit 19 -fmessage-length 79 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fobjc-runtime=macosx-10.15.0 -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/wq/5pndv0f91bl86_jv5s4dx1nm0000gn/T/b-915c72.o -x c b.c
clang -cc1 version 10.0.0 based upon LLVM 10.0.0 default target x86_64-apple-darwin19.4.0
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/usr/local/lib/clang/10.0.0/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
b.c:2:10: fatal error: 'stdarg.h' file not found
#include <stdarg.h>
         ^~~~~~~~~~
1 error generated.

~/tmp
$
```

**Comment by zhaozg** [comment]
Solution:
```
cd /usr/local/lib
ln -s ln -s ../opt/llvm/lib/clang 
```
Darwin zhaozgMBP 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

install llvm with brew install llvm

**Comment by turbo** [comment]
I have the same problem, and I don't get how the commands from the second comment could fix the issue. [The zig cc page](https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html) led me to believe that a download of the zig tarball is everything required to compile with `zig cc`. That doesn't seem to hold true, however. Taking the example of LuaJIT:

```bash
cd luajit2
export CC="zig cc"
make CC="$CC"
```

immediately fails with:

```text
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[1]: Entering directory '/home/turbo/Projects/ziglua/luajit2/src'
In file included from lj_arch.h:9:
./lua.h:12:10: fatal error: 'stdarg.h' file not found
#include <stdarg.h>
         ^~~~~~~~~~
1 error generated.

The following command failed:
/usr/lib/zig/0.6.0/zig clang -nostdinc -fno-spell-checking -target x86_64-unknown-linux-gnu -fomit-frame-pointer -DNDEBUG -O2 -fno-stack-protector -fPIC -fomit-frame-pointer -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U_FORTIFY_SOURCE -E -dM -isystem /usr/local/include -isystem /usr/include/x86_64-linux-gnu -isystem /usr/include -o zig-cache/tmp/huT8H6tEiXCs-lj_arch.h lj_arch.h
In file included from lj_arch.h:9:
./lua.h:12:10: fatal error: 'stdarg.h' file not found
#include <stdarg.h>
```

Whereas the build succeeds with gcc. I don't have clang or llvm installed, is that required for zig cc to work?

**Comment by andrewrk** [comment]
The solution above is not correct. The problem is using `zig clang` (lower level, unsupported CLI) rather than `zig cc` (intended use).

The zig tarball does include everything, including stdarg.h. It looks like you used `zig clang` and not `zig cc`

**Comment by turbo** [comment]
I ran the exact make command as included above. Maybe something somewhere switched that to `zig clang`, but I didn't do that. I'll try to figure out where this is happening.

**Comment by turbo** [comment]
@andrewrk Here's a complete repro of this:

```Dockerfile
FROM ubuntu

RUN apt update && \
  apt install -y make perl git wget xz-utils && \
  git clone https://github.com/openresty/luajit2 --depth 1 && \
  cd /luajit2 && \
  sed -i 's/#define LJ_TARGET_DLOPEN/\/\/#define LJ_TARGET_DLOPEN/g' ./src/lj_arch.h && \
  wget https://ziglang.org/download/0.6.0/zig-linux-x86_64-0.6.0.tar.xz && \
  tar xf zig-linux-x86_64-0.6.0.tar.xz && \
  export PATH="${PATH}:/luajit2/zig-linux-x86_64-0.6.0" && \
  zig version && \
  export CC="zig cc" && \
  mkdir dbin && \
  make CC="$CC" \
    STATIC_CC="$CC" \
    CCOPT="-static -fPIC -DLJ_TARGET_DLOPEN=0 -fomit-frame-pointer -Os" \
    BUILDMODE="static" \
    PREFIX=/luajit2/dbin
```

Run with `docker build --rm -t zig-repro .`

**Comment by turbo** [comment]
@andrewrk Sorry I can't figure this out. There's no reference to clang or indeed any compiler detection anywhere in the OR/LuaJIT code as far as I can see. Even if I manually overwrite the Makefile compiler settings and wrap `zig cc` in a script. All I can guess is that `zig cc` calls out to `zig clang` internally and both encounter the error. I was able to reproduce this from a clean state on ubuntu (see above Dockerfile) and even alpine from absolute scratch without any compiler. I'm sure I'm missing something obvious but would appreciate it if you take a look. Thanks!

**Comment by turbo** [comment]
Some progress. I get one step further if I manually add the include dir and also override HOST_CC. This will now compile some of the source files, but crash:

```Dockerfile
FROM ubuntu

RUN apt update && \
  apt install -y make perl git wget xz-utils && \
  git clone https://github.com/openresty/luajit2 --depth 1 && \
  cd /luajit2 && \
  sed -i 's/#define LJ_TARGET_DLOPEN/\/\/#define LJ_TARGET_DLOPEN/g' ./src/lj_arch.h && \
  wget https://ziglang.org/download/0.6.0/zig-linux-x86_64-0.6.0.tar.xz && \
  tar xf zig-linux-x86_64-0.6.0.tar.xz && \
  export PATH="${PATH}:/luajit2/zig-linux-x86_64-0.6.0" && \
  zig version && \
  export CFLAGS="${CFLAGS} -I/luajit2/zig-linux-x86_64-0.6.0/lib/zig/include" && \
  make \
    CC="zig cc" \
    STATIC_CC="zig cc" \
    HOST_CC="zig cc" \
    CCOPT="-static -fPIC -DLJ_TARGET_DLOPEN=0 -fomit-frame-pointer -Os" \
    BUILDMODE="static" \
    PREFIX="/luajit2/dbin"
```

The crash is:

```text
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[1]: Entering directory '/luajit2/src'
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
make[1]: *** [Makefile:655: host/buildvm_arch.h] Illegal instruction (core dumped)
make[1]: Leaving directory '/luajit2/src'
make: *** [Makefile:113: default] Error 2
```

This seems to be related to https://github.com/ziglang/zig/issues/4830, where UBSAN is vetting the code. I'd be hesitant to conclude that there's an actual issue in LuaJIT which would warrant this error. At the same time, I also can't tell from the linked issue how I would disable whatever check fails the compilation here in `zig cc`. The same code builds with clang, given the CCOPTs defined in the make command.

**Comment by turbo** [comment]
A bit more background on what this is even supposed to do. The goal here is to replace a dockerized clang build environment with a local copy of zig to get rid of the docker dependency. Out of a few C components built, only LuaJIT fails the compilation with zig.

LuaJIT, in this case, is built "completely static". That not only means statically linked, but also without `dlsym` and `dlopen` support, hence the `-DLJ_TARGET_DLOPEN=0`. This flag would usually be overridden by the detection of `POSIX` which forces the inclusion of libdl, hence the sed patch which removes that override. Again, this is not an experiment, this is intentional and works just fine with clang and gcc on glibc and musl systems (or Docker images).

Furthermore, it seems that zig largely ignores the C options passed to it. From the failed subcommand execution it looks like it uses `-O2` event though `-Os` is specified among other discrepancies. This could be down to LuaJIT's Makefile, but I don't know.

If I instead hoist all of the options up to the actual CFLAGS and forgo using LuaJIT's CCOPT parameter, the compilation gets further:

```bash
export CFLAGS="${CFLAGS} -I/luajit2/zig-linux-x86_64-0.6.0/lib/zig/include -static -fPIC -DLJ_TARGET_DLOPEN=0 -fomit-frame-pointer -Os" && \
  make \
    CC="zig cc" \
    STATIC_CC="zig cc" \
    HOST_CC="zig cc" \
    BUILDMODE="static" \
    PREFIX="/luajit2/dbin"
```

This is the furthest I came until now. Sadly, the error it crashes with now is even more obscure, containing nothing but an error code:

```text
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[1]: Entering directory '/luajit2/src'
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h

< bla blah blah >

AR        libluajit.a
make[1]: Leaving directory '/luajit2/src'
make[1]: *** [Makefile:721: libluajit.a] Error 127
make: *** [Makefile:113: default] Error 2
```

Might be a link failure? No clue.

**Comment by andrewrk** [comment]
@turbo I'm not sure what this issue is about. The original issue above is solved. Don't use `zig clang`. If you're still dealing with a separate issue, can you open a separate issue for it and explain clearly what is the problem on zig's end? 

* A bit of a description of your use case
* what did you try to do
* what did you expect to see
* what did you see instead
