### ISSUE TITLE
--c-source and -lc++ vs -lstdc++

### ISSUE THREAD

**Issue by mikdusan** [ziglang/zig#5012]
#### `foo.cpp`
```c++
#include <cstdlib>

int foo() {
    exit(0);
}
```

#### fails: `zig build-obj --c-source foo.cpp -lstdc++ -lc`
```
In file included from foo.cpp:1:
/usr/lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/cstdlib:75:15: fatal error: 'stdlib.h' file not found
#include_next <stdlib.h>
              ^~~~~~~~~~
```

#### grab the `zig clang` command and add `-v` for include search order
```
 /home/mike/project/zig/work/main/lib/libcxx/include
 /home/mike/project/zig/work/main/lib/include
 /home/mike/project/zig/work/main/lib/libc/include/x86_64-linux-gnu
 /home/mike/project/zig/work/main/lib/libc/include/generic-glibc
 /home/mike/project/zig/work/main/lib/libc/include/x86_64-linux-any
 /home/mike/project/zig/work/main/lib/libc/include/any-linux-any
 /usr/lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0
 /usr/lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/x86_64-pc-linux-gnu
 /usr/lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/backward
```

the above in totality is wrong:
- correct: `lib/libcxx/include` is libc++ and must come before clang compiler instrinsics `lib/include`
- incorrect: superfluous libstdc++ at bottom. resolving relative paths, `/usr/include/c++/9.3.0/` trifecta should not be needed for libc++, it's redundant and dangerous. we just get away with it because libc++ is correct and comes first.

now let's try same deal with `-lstdc++` ...

#### grab the `zig clang` command and add `-v` for include search order
```
 /home/mike/project/zig/work/main/lib/include
 /home/mike/project/zig/work/main/lib/libc/include/x86_64-linux-gnu
 /home/mike/project/zig/work/main/lib/libc/include/generic-glibc
 /home/mike/project/zig/work/main/lib/libc/include/x86_64-linux-any
 /home/mike/project/zig/work/main/lib/libc/include/any-linux-any
 /usr/local/include
 /usr/include
 /usr/lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0
 /usr/lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/x86_64-pc-linux-gnu
 /usr/lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/backward
```

here libstdc++ includes are (again last) but now not superfluous. They need to be moved upfront so things look like this:
```
 /usr/lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0
 /usr/lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/x86_64-pc-linux-gnu
 /usr/lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/backward
/home/mike/project/zig/work/main/lib/include
 /home/mike/project/zig/work/main/lib/libc/include/x86_64-linux-gnu
 /home/mike/project/zig/work/main/lib/libc/include/generic-glibc
 /home/mike/project/zig/work/main/lib/libc/include/x86_64-linux-any
 /home/mike/project/zig/work/main/lib/libc/include/any-linux-any
 /usr/local/include
 /usr/include
```

This approach might work for us:

1. when any C++ library is detected add `-nostdinc++` for `zig clang`
2. we appear to do the correct thing for `-lc++` by inserting `lib/libcxx/include` before `lib/include` so leave that alone
3. when `-lstdc++` is detected let's put the trifecta in before `lib/include`

**Comment by mikdusan** [comment]
just marking some notes here.. the solve was a little simpler because zig does not support host C++ libraries:

1. make `stdc++` an alias to `c++` for zig command-line
2. ultimately pass argument `-nostdinc++` to clang to avoid embedded-clang appending host c++ includes

**Comment by andrewrk** [comment]
This writeup was excellent btw. It was amazing to be able to read it and then immediately see the problem.
