### ISSUE TITLE
Formal verification / proof

### ISSUE THREAD

**Issue by Alkeryn** [ziglang/zig#5025]
It would be cool for formal verification / proof to be builtin kind of like ada spark

I really would love a low level language that has it builtin or is flexible enough to have it added by a lib.

Of course it is not really a priority as the language is still young and have much more important issues to fix first, but what can you want more than software mathematically proved to be "perfect".

having it builtin in such a nice language would be great, plus imo formal verification > borrow checker so it could even put a language like rust to shame if implemented correctly.

If you guys decide to implement it, using that feature to prove zig itself would be another great step regarding safety, not only the language would support formal proof but it would be formally verified itself.

**Comment by daurnimator** [comment]
Please define what you mean by formal verification: of what by what, using what techniques and defintions.

I don't think this proposal makes sense: zig isn't TLA+.

**Comment by Alkeryn** [comment]
@daurnimator well it is a subject you'd find many example by searching for it, i did used an example by mentioning ada spark :
https://en.wikipedia.org/wiki/SPARK_(programming_language)

basically it allow to define "contracts" that tells conditions variables and the programme has to satisfy in all cases and the compiler generally proove that it is the case often via the use of smt solver and screams at you in the case the "contracts" aren't satisfied by the code.

Manual formal proof is a thing too but it is a tedious process and having it built into a language can automate most of it, 

If you are interested into the subject you can look at stuff like ada spark, LEAN, Z3, coq
and maybe look at project like sel4 which is a proved kernel.

anyway i didn't felt the need to define formal verification as it is something already well defined and the explications you'll find will probably be better than the ones i can provide.

the contracts aproach was an example of many possible implementations of formal proof/verification.

but basically having it built into a language means that you can automate the process of proving that your code and its resulting implementation (produced binary) are correct / compliant to a definition / have no weird states.

**Comment by Sobeston** [comment]
Could you expand on what this could potentially look like, and how it would work (within the context of zig)?

**Comment by Alkeryn** [comment]
I'm really new to the language (discovered it 2days ago) so having a much more extensive knowledge of the language andrew will surely propose a better syntax than i would as of right now if he reads this issue.

Though i will provide an example by next week once i am more fluent with zig and my opinion on what a feature might look like will be more valid.

**Comment by andrewrk** [comment]
This is not planned but I would be happy to re open the issue if you do the leg work of filling out the details of how this idea would integrate into zig.

**Comment by adamatat** [comment]
@andrewrk At a very basic level, being able to define a schema for arguments and return values in a streamlined way as well as validating the integrity of structures, in combination with something like [zod](https://zod.dev), would be cool.

**Comment by LeonardAukea** [comment]
I think it could be a good idea to lean on [lean4](https://github.com/leanprover/lean4) and borrow some ideas from here https://lean-lang.org/use-cases/aeneas/  where less machinery would be necessary in comparison with Rust. Lean4 is popular amongst the mathematics community and actively used. 

Lean has [checked bit-vector automation `bv_decide` and SMT bridges. ](https://leanprover-community.github.io/mathlib4_docs/Lean/Elab/Tactic/BVDecide.html)

An approach could be to emit one `.lean` file per `.zig` file and one theorem by obligation, defaulting to bit‑precise, fully typed encodings so most goals are closed automatically.

I'm not fully up to date with the recent Zig compiler developments, but given the AIR (typed, post comp-time) would be a practical place to start? one could parse into an SSA-like core before translating to lean (could make it easier to support other backends also later on). 

Translate AIR → core → Lean goals + proof scripts → `lake build` 

```
zig build verify 
│
├─ step 1: collect obligations (scan pragmas)
├─ step 2: compile with Zig (no codegen), request AIR referenced fns
├─ step 3: AIR → Core (typed SSA)
├─ step 4: Core → Lean goals + proof script
│      └─ default script:   simp; try bv_decide; try lean-smt
├─ step 5: lake build (pinned)
└─ step 6: parse Lean JSON; print:
      ✓ proved    ✗ counterexample (with model)  ? timeout
```

```
//@modifies( &buf[0..n] )
fn zero(buf: []u8, n: usize) void { ... }

var i: usize = 0;
//@invariant( 0 <= i and i <= n )
//@invariant( sum == sum0 + ∑(arr[0..i]) )
while (i < n) : (i += 1) {
    sum += arr[i];
}
``` 

Zig deserves as safety-critical toolchain. Now with the compiler efforts I think it may be a good time to consider this carefully in the designs @andrewrk
