### ISSUE TITLE
support mac os libc

### ISSUE THREAD

**Issue by aahmed-se** [ziglang/zig#5031]
https://opensource.apple.com/source/Libc/Libc-1353.11.2/

Clear bar for tier 1 support for mac os.

**Comment by daurnimator** [comment]
The license states:

> 1.7 "Original Code" means (a) the Source Code of a program or other work as originally made available by Apple under this License, including the Source Code of any updates or upgrades to such programs or works made available by Apple under this License, and that has been expressly identified by Apple as such in the header file(s) of such work; and (b) the object code compiled from such Source Code and originally made available by Apple under this License.

> 2.1 Unmodified Code. You may use, reproduce, display, perform, internally distribute within Your organization, and Externally Deploy verbatim, unmodified copies of the Original Code, for commercial or non-commercial purposes, provided that in each instance:
> (a) You must retain and reproduce in all copies of Original Code the copyright and other proprietary notices and disclaimers of Apple as they appear in the Original Code, and keep intact all notices in the Original Code that refer to this License; and
> (b) You must include a copy of this License with every copy of Source Code of Covered Code and documentation You distribute or Externally Deploy, and You may not offer or impose any terms on such Source Code that alter or restrict this License or the recipients' rights hereunder, except as permitted under Section 6.

Those parts seem okay; though we probably would want to stick in the "Unmodified" section rather than the "Modified" category.

*However*:

> 2.3 Distribution of Executable Versions. In addition, if You Externally Deploy Covered Code (Original Code and/or Modifications) in object code, executable form only, You must include a prominent notice, in the code itself as well as in related documentation, stating that Source Code of the Covered Code is available under the terms of this License with information on how and where to obtain such Source Code.

This seems to imply that if zig uses that libc, then we'd have to insert some copyright notice into all resulting files? I guess we could add some symbol.... how have other projects satisfied this requirement?

**Comment by judofyr** [comment]
> 2.3 Distribution of Executable Versions. In addition, if You Externally Deploy Covered Code (Original Code and/or Modifications) in object code, **executable form only**, You must include a prominent notice, in the code itself as well as in related documentation, stating that Source Code of the Covered Code is available under the terms of this License with information on how and where to obtain such Source Code.

Doesn't this seem to suggest that this only applies if you distribute the binary without distributing the source code?

**Comment by fengb** [comment]
There's some slight annoyances in that repo: e.g. [stdint.h](https://opensource.apple.com/source/Libc/Libc-1353.11.2/include/stdint.h.auto.html) is technically proprietary.

We'll need to do a manual audit and clean-room reimplement the missing pieces.

**Comment by aahmed-se** [comment]
@fengb seem like error in license headers on apple's part shouldn't be difficult to just rewrite that file or maybe create a issue for them to resolve.

**Comment by andrewrk** [comment]
Note that to accomplish this we only need the headers. It's already possible to do `-lSystem` when cross compiling for macOS.
