### ISSUE TITLE
incorrect double resume error

### ISSUE THREAD

**Issue by emekoi** [ziglang/zig#5040]
when resuming frames from 2 different invocations of the same function, zig says that the function has already returned when attempting to resume the second frame.

```zig
pub fn storeFrame(frame: *anyframe->anyerror!void) anyerror!void {
    suspend {
        frame.* = @frame();
    }
}

test "resumed returned frame" {
    var frames: [2]anyframe->anyerror!void = undefined;
    for (frames) |*frame| {
        _ = async storeFrame(frame);
    }

    for (frames) |frame| {
        resume frame;
    }
}
```

i have another example in which code similar to this causes a segafault when resume the frame, but i haven't been able to isolate and reproduce the issue.

**Comment by jorangreef** [comment]
I ran into this just now while writing an event loop abstraction for io_uring.

Here's a `recv` function which gets called for two accepted network socket fds:

```
pub fn recv(self: *IO, fd: os.fd_t, buffer: []u8) !usize {
    var completion = IO.Completion{ .frame = @frame() };
    _ = try self.ring.recv(@ptrToInt(&completion), fd, buffer, os.MSG_NOSIGNAL);
    std.debug.print("{} recv...\n", .{ @ptrToInt(&completion) });
    suspend;
    if (completion.result < 0) return os.unexpectedErrno(@intCast(usize, -completion.result));
    return @intCast(usize, completion.result);
}
```

I added a print statement to print the pointer address of the `completion` struct instance before suspending. You'll see for both client connections, the `recv` function's `completion` struct instances have the same pointer:

```
fd 5: accepted connection
140734564765648 recv...
fd 6: accepted connection
140734564765648 recv...
```

**Comment by jorangreef** [comment]
I assume this is the same thing, and I don't mean to muddy the issue... but I suppose using heap allocated memory for the function would work, resulting in two different pointers to the frames of 2 different invocations of the function?

Something along the lines of @daurnimator's https://gist.github.com/daurnimator/699320cda828303671a21d15bb4a3753#file-uring-nonblock-fifo-async-zig-L143-L183

**Comment by daurnimator** [comment]
> ```zig
>         _ = async storeFrame(frame);
> ```

This is a stack allocated frame that you're re-using.

You have an array of frame *pointers*:
> ```zig
> var frames: [2]anyframe->anyerror!void = undefined;
> ```

You probably wanted an array of frames: `var frames: [2]@Frame(storeFrame)`
Or alternatively you need to allocate them with an allocator.
