### ISSUE TITLE
Proposal: Rust-like if, while and for syntax

### ISSUE THREAD

**Issue by r4pr0n** [ziglang/zig#5042]
In my opinion, the rust-like syntax
```rust
if condition { expr }
```
where the `{}` are forced, but the `()` around the condition can be omitted is easier to read and write than the c-like
```zig
if (condition) expr
```
syntax.
I think this change would benefit zig because IMHO omitting the `{}` almost always makes the code more unreadable, the structure given by the `{}` helps really to see where the expression ends. Furthermore, when the `{}` are forced, the `()` doesn't really help here, since the condition is already well separated by the `if` and the `{`.

**Comment by emekoi** [comment]
see #4294 and #1659.
