### ISSUE TITLE
Expected compile error for unreachable code

### ISSUE THREAD

**Issue by strangebug** [ziglang/zig#5050]
Hello,
I am a zig beginner so feel free to correct if I missed something.

The `foo` function is unreachable so `zig build` don't raise a compilation error.

Zig: 0.6.0
main.zig:
```zig
const std = @import("std");

fn foo() void { // Unreachable code
    const y = 1;
    y += 1;
}

pub fn main() void {}
```

**Comment by andrewrk** [comment]
Welcome, @strangebug. Have a look at #335.

**Comment by strangebug** [comment]
Sorry, didn't saw that one

**Comment by andrewrk** [comment]
No problem! There are many issues open
