### ISSUE TITLE
math.clamp doesn't work

### ISSUE THREAD

**Issue by mitkus** [ziglang/zig#5052]
I encountered two separate problems with `math.clamp`.

1) It only works if all or none of the arguments are `comptime`. Eg. this doesn't work:
```zig
var a: i32 = -1;
var clamped = math.clamp(a, 0, 2);
```
It produces compile error:
```
.\zclamp.zig:9:30: error: unable to evaluate constant expression
    var clamped = math.clamp(a, 0, 2);
                             ^
```

While this works:
```zig
var min: i32 = 0;
var max: i32 = 2;
var a: i32 = -1;
var clamped = math.clamp(a, min, max);
```

2) This is debatable, but it is strange that the arguments `math.clamp` takes are `bound_1` and `bound_2` instead of simply `min` and `max`. It's pretty standard (eg. GLSL `clamp`) to have explicit `min` and `max`, and there are good reasons for that:
  - There's a chance compiler will emit more branchy code than strictly necessary if bounds are not `comptime`.
  - The code that calls `clamp` knows min and max in vast majority of cases. It less sloppy just to pass them explicitly and have an assert fail at runtime in debug builds if the range is invalid.
  
    I propose that Zig's `math.clamp` should work just like GLSL for the reasons above.

If nobody is in a hurry, I would also love to volunteer and submit a PR for 1) and (maybe) 2) in the next few days.

**Comment by data-man** [comment]
https://github.com/ziglang/zig/pull/4174#issuecomment-574134103

**Comment by andrewrk** [comment]
157f566f2dd9c8d694270f5b7fcb8525834d7646
