### ISSUE TITLE
source code bug 

### ISSUE THREAD

**Issue by tlming16** [ziglang/zig#5065]
zig/src/util.hpp 

`inline T & Slice<T>::at(size_t )`  declare return reference to `T` but in fact the function return pointer to `T`
```cpp 

template<typename T>
struct Slice {
    T *ptr;
    size_t len;

    inline T &at(size_t i) {
        assert(i < len);
        return &ptr[i];
    }

    inline Slice<T> slice(size_t start, size_t end) {
        assert(end <= len);
        assert(end >= start);
        return {
            ptr + start,
            end - start,
        };
    }

    inline Slice<T> sliceFrom(size_t start) {
        assert(start <= len);
        return {
            ptr + start,
            len - start,
        };
    }

    static inline Slice<T> alloc(size_t n) {
        return {heap::c_allocator.allocate_nonzero<T>(n), n};
    }
};
```

**Comment by LemonBoy** [comment]
`inline T &at(size_t i)`
`inline T &at` 
`T &`

That's a [reference](https://en.cppreference.com/w/cpp/language/reference) to an element of type T.

**Comment by tlming16** [comment]
inline T &at(size_t i) {
        assert(i < len);
        return &ptr[i];
    }
if you write  
 inline T &at(size_t i) {
        assert(i < len);
       T & res=ptr[i];
        return  res;
    }
it's ok ,it is reference,but &ptr[i] is the address of ptr[i],is pointer , except that you have overloaded operator &;

**Comment by LemonBoy** [comment]
Bleh, I was looking at `List` implementation of `at`. That's indeed a bug, the compiler doesn't use `at` at all so it can be either fixed by removing the `&` or removed altogether.

**Comment by Vexu** [comment]
Stage1 has been deleted.
