### ISSUE TITLE
Proposal: examples

### ISSUE THREAD

**Issue by PavelVozenilek** [ziglang/zig#507]
Feature useful mainly for libraries. "How to use" examples could be embedded in source code, like the tests.  

```
EXAMPLE "func1, func2, func3" /// this is example relevant to 3 functions
{
  /// Typical use of ...
  ...
}

```

Notes: 
1. The compiler would verify example code compiles. It won't run it.
2. One who writes library documentation may copy relevant examples, or some tool can do this automatically.
3. Examples are different to tests, they show _expected and desired use_ patterns, not corner cases and tricky use. Example may call functionality not desirable in a test (e.g. long sleep, delete all files, interaction with the user, GUI), without need for mocking.
4. Uppercased keyword `EXAMPLE` would attract attention of those who don't have time to grok details.

There may be module level examples, representing functionality of the whole source file:

```
MODULE_EXAMPLE
{
  /// Higher level example showing how to use the module
  ...
}

```

Good style guidelines may recommend placing examples just after relevant function (before tests) and module examples at the end of the file.

**Comment by iology** [comment]
What about:

```
//!EXAMPLE
comptime {
    if (false) {
        ...
    }
}

test "EXAMPLE" {
    if (false) {
        ...
    }
}
```

Anyway I think this proposal is for lazy programmers, not for people who really want to write good docs.

**Comment by PavelVozenilek** [comment]
@iology: examples get copy pasted. With indentation due to `if (false)` this would be less convenient.

**Comment by iology** [comment]
Yes, and my example does syntax check, but without checking the existence of referenced files.

Would you want to compile the examples every time the library is compiled? Or just `zig example <src>`?

Why not put them in a separate example directory and import the library normally? So that people know they don't omit any includes and imports.

**Comment by PavelVozenilek** [comment]
@iology: yes, examples would be compiled every time library is compiled. I expect them to be rather short.

Examples somewhere in a subdirectory are practically abandoned - out of sight, out of mind. If they are in source code there's some chance they will be kept up to date.  Subdirectory and more files add unwanted complexity into a system. (Embedded tests and examples enlarge source code, but one is not exposed to this until he opens that source.)

Example blocks may support the `@import` thing inside.


The goal is that lazy programmer copies the example, certain that it compiles/works, has good style and nothing important is missing. Then he can play with it further.

**Comment by tiehuis** [comment]
I had envisioned us doing example blocks simply as part of the documentation. Pretty much as rust does, and just incorporating them to run under the `zig test`.

Is there any reason to prefer this explicit keyword? The fact that examples only differ from the current testing approach semantically seems like it could be slightly annoying. We will envitably have some way to document functions/modules anyway, and it seems appropriate to place them there instead.

Here is an example of what it looks like if you aren't familiar with rust.
https://github.com/BurntSushi/byteorder/blob/master/src/io.rs

**Comment by PavelVozenilek** [comment]
@tiehuis: 

It is unusual and not advantageous to have code inside comments. 
* Developers are conditioned to ignore comments, leaving such code to the rot. 
* Editing gets harder with these `///`. 
* The code is not trivially copyable (from the source).
* Indentation levels may increase significantly.  (My pet nuisance.)
* Proper syntax highlighting would require really advanced editor.

It's a hack.

-----------

```
EXAMPLE 
{
    ...
}

```
looks natural and lacks problems listed above.

----------

I do not recommend automatically run examples - they are not restricted as tests are, may e.g. show GUI. If they are not invoked they would not need mocking support (if this feature gets implemented).


---------

Explicit `EXAMPLE` keyword is something I'd personally prefer. I am browsing Zig's  stdlib sources and looking all the time if there's a test hinting how to use this or that. Having `EXAMPLE` yelling at me would help.


---------------

Tests and examples have very different purpose. Test do (should do) crazy things, push the limits, ensure high coverage etc. Examples should be Platonic ideals transformed into code. 

There should be as much testing as circumstances permit.  Duplication and wordiness is not a big deal, even could be desirable. OTOH examples should be succinct and of good style.

**Comment by kyle-github** [comment]
I think I am missing something here.   If you want the examples to be maintained, then they need to be run, not just compiled.   

> I do not recommend automatically run examples - they are not restricted as tests are, may e.g. show GUI. If they are not invoked they would not need mocking support (if this feature gets implemented).

What if you could chose which tests to run?   Would that be sufficient?

**Comment by tiehuis** [comment]
@PavelVozenilek 

I think an important question to consider is whether users are expected read the source code to understand the api/usage or whether they should be reading some generated documentation.

Unfrotunately the stdlib source needs to be read directly for usage at this stage, since there is no documentation otherwise. If there was proper API documentation, how would you expect the examples would be provided there? Is the need for highly visible examples as important then?

Just want to make sure we are focusing on the way that users are expected to consume this information.

@kyle-github 

I don't think running examples is actually too important as the behavior should itself be covered by tests as part of the code ideally. Some cases may benefit though (i.e. using `assert` to show expected behavior to the user and running just for confirmation).

**Comment by PavelVozenilek** [comment]
@kyle-github:  I expect examples to be read, thought about and used. People will report the problems. This should do the maintenance.

> What if you could chose which tests to run? Would that be sufficient?

You'd also need to distinguish between ordinary tests (ugly, full of asserts) and example tests (nice) which are extracted by the tooling.

That now gives 3 variants (ordinary test, example which is always executed, non-runnable example).  

For people who prefer to read source code examples should be visually distinctive, to catch attention. 

Example also should provide hint on their place in generated documentation, something not always obvious. That's the `EXAMPLE func1, func2, func3 { ... }` part (here asking to be shown at three locations).

-----------

My opinion is that `test` and (non-runnable) `EXAMPLE` is the optimal solution. Other options could be added if need arises.

**Comment by PavelVozenilek** [comment]
@tiehuis: some people read the documentation, others go to the code. My proposal cares for both.

I expect that library documentation will be generated, not hand written. Extracted examples then could make the most important and visually dominating part of the documentation.

I personally prefer documentation in form of nice short examples, which could be read linearly like a book (unlike javadoc). Example is what programmers can do well. When they produce long text it is almost always horror.

Current form of Zig documentation project is really promising. No attempt to write novels, small code snippets instead.

----------------

Hypothetical generated documentation should avoid at all cost trap of pedantic formalism, like:

```
/// @FunctionDescription: adds two numbers
/// @Par1: first number to add
/// @Par2: second number to add
/// @Return: sum
fn add(x : u32, y : u32) -> u32
{
  return x + y;
}

```

I have seen things like this.

**Comment by iology** [comment]
@PavelVozenilek 

> Examples somewhere in a subdirectory are practically abandoned - out of sight, out of mind. If they are in source code there's some chance they will be kept up to date. **Subdirectory and more files add unwanted complexity into a system.**

Isn't the user also copying the code to their project directory? Adding addtional library search paths should not be a big deal, given that Zig want to provide a better `make`.

> yes, examples would be compiled every time library is compiled.

It is also the developers' duty to make sure the provided examples can be compiled (and run if so desired). So they can add a build job alongside the tests. They'd better run the tests before compiling the examples. This feature sounds like the examples are more important than the tests.

// For now I just put aside the convenience of linking the source code to the examples. Docgen concerns are quite complicated and in a higher level.

**Comment by PavelVozenilek** [comment]
@iology: I personally dislike when there's a library and it contains not just the source but also many other files and subdirectories, often with unclear purpose.  


> Adding addtional library search paths
> add a build job alongside the tests

These two steps would make me look for alternative.

My ideal are those "single header" C/C++ libraries. Anything beyond is (often, not always) useless complexity for complexity.


> They'd better run the tests before compiling the examples

Even this is not really needed as explicit step. My testing framework runs the tests (from recently modified sources) automatically, whenever the application starts. It is like a miracle: edit, then press F5 (run with recompile) - no extra step diverting attention away, and it can be done literally within second.

-------------

Back to the examples. If they are embedded it has following advantages:
1. No extra files/directories. The library could ideally fit in one file.
2. Examples are near the relevant code. I find a function, scroll a bit down and see how it can be used. If I need more I scroll further down for the tests.
3. Documentation generator may not need any manual configuration. Generating documentation could even get automatic and invisible.

There's one disadvantage: if tests and examples are embedded in source code its size can grow _a lot_. Beyond 5 - 10k lines it becomes annoying to use scrollbar and minimaps are useless. 
I experimented (in C) with test subdirectories and inlined files but eventually settled to "one file with everything", with consistent internal structure: first a function, then its tests, then another function and so on.  Such structure is also easy to modify.

**Comment by PavelVozenilek** [comment]
Heh, I found I proposed this functionality two years ago in #128.

**Comment by PavelVozenilek** [comment]
I just read essay ( http://akkartik.name/about ) by Kartik Agaram, out-of-the-box thinker about programming languages.

Among ideas to better understand someone else's code he proposes:

> Instead of describing your architecture, point newcomers at core tests that they can instrument or step through in a debugger. That allows them to focus first on the concrete series of operations desired in a situation rather than how those operations happen to be organized in code.

This feels quite a lot as proposed examples here. Ordinary tests will be dozens of a dime, easy to create and forget. Examples could be what newcomer should explore, and the special syntax would guide them to go there.
