### ISSUE TITLE
a place to put variables in only while loop scope

### ISSUE THREAD

**Issue by anosovic** [ziglang/zig#5070]
```zig
   {
        var i: usize = 0;
        while (i < 10) : (i += 1) {
            list.append(@intCast(i32, i + 1)) catch @panic("");
        }
    }

    {
        var i: usize = 0;
        while (i < 10) : (i += 1) {
            testing.expectEqual(@intCast(i32, i + 1), list.inner.items[i]);
        }
    }
```

this is from @Hejsil 's [interface demo](https://github.com/Hejsil/zig-interface/blob/master/src/array_list.zig). also see [a reddit thread](https://www.reddit.com/r/Zig/comments/ftj26y/folks_who_have_written_both_c_projects_and_zig/) that mentions this pattern

doing this is to avoid:
```zig
   var i: usize = 0;
   while (i < 10) : (i += 1) {
       list.append(@intCast(i32, i + 1)) catch @panic("");
   }
    var i_2: usize = 0;
    while (i_2 < 10) : (i_2 += 1) {
       testing.expectEqual(@intCast(i32, i_2 + 1), list.inner.items[i_2]);
    }
```

compare with a C for loop:
```c
for (int i = 0; i < 10; i++) {}
assert(i == 10);
```
the c for loop has
 - one place to init loop state
 - one place to put terminating condition
 - two places to write how the state updates each loop ¯\_(ツ)_/¯

versus an example from the zig docs:
```zig
const assert = @import("std").debug.assert;

test "while loop continue expression" {
    var i: usize = 0;
    while (i < 10) : (i += 1) {}
    assert(i == 10);
}
```

zig while loop has:
 - nowhere to init state native to the loop ¯\_(ツ)_/¯
 - one place to put terminating condition
 - two places to write how the state updates each loop ¯\_(ツ)_/¯

related zen:
 _avoid local maximums_
 _communicate intent precisely_
 _favor reading code over writing code_
 _only one obvious way to do things_
 _reduce the amount one must remember_
 _minimize energy spent on coding style_

status quo inhibits all of these. can we make this better?

**Comment by pixelherodev** [comment]
Idea: currently, we support this: 

```zig
while (foo) : (bar) {
    baz
}
```

Should we also support this?

```zig
while (init) : (foo) : (bar) {
    baz
}
```
?

Or, alternately,
```zig
(init) : while (foo) : (bar) {
    baz
}
```

e.g.

```zig
(var a: usize = 0) : while (a < 8) : (a += 1) {

}
```

A refined variation of the latter might be good, as it has the following properties:

* Easier to read
* Init is clearly distinct from condition and state-update
* Variable is clearly scoped

**Comment by anosovic** [comment]
interesting ideas, but

```zig
(var a: usize = 0) : while (a < 8) : (a += 1) {}
```
your proposal has:
 - one place to init loop state
 - one place to put terminating condition
 - two places to write how the state updates each loop ¯_(ツ)_/¯
thus are comparable to c for loops.

**Comment by karrick** [comment]
Anyone coming from another C like language is instantly going to know how to write and read loop declarations like C:

```
for (initialization ; condition; increment) {
    body
}
```

Maybe I'm missing something. Is there a reason to avoid using C style loops?

**Comment by iology** [comment]
It becomes worse when we add more variables... :wink: I think starting a new block is a good solution in this condition. Otherwise just give variable names i, i2, i3, i4, etc.

> two places to write how the state updates each loop ¯\\\_(ツ)\_/¯

Problem solved if the variables defined in `(...)` cannot be modified in the loop body `{...}`. Or use a Range:

```
// let's specify the type in |...| if the compiler cannot figure it out
for range(min, max) |value: i8| {
    ...
    // finally, auto-break if (value + 1 < min) or (value + 1 > max)
}

// `count` starts from 0
for range(min, max) |value: i8, count: u8| {
    ...
}
```

here is the rest of my proposal:

```
// rename `for` to `foreach`
for each(elements) |value| { ...  }
for each(elements) |value, key| { ...  }

// optionally add a counter which starts from 0
while (success) |content, count: usize| {
    ...
}
```

**Comment by iology** [comment]
↑ updated: changed range(min, max) to range(begin, end, non_zero_step)

**Comment by user00e00** [comment]
An attempt at finding symmetry between `if` and `while`

```zig
if(optional) |value| {
   _ = value; // value is not null here
}
```

```zig
while( range(0, arr.len) ) |k| {
   arr[k] = k*2;
} 
// exit while once range returns null
```
If you need more elaborate control over the index variable this won't work though.

**Comment by iology** [comment]
> An attempt at finding symmetry between if and while

No, you should take `for range` as one keyword just like `forrange` (-rr- is weird). Although we can also write `for (@range(x, y, step)) |v, i|` but I prefer `foreach`, then `foreach (@range(x, y, step)) |v, i|` is a bit verbose. Anyway I can accept both `for range/each` and the original `for` syntax.

`@range()` cannot be used with `while` because it doesn't return bool, optional nor error.

**Comment by darithorn** [comment]
Right now Zig's for loops already act like a for-each. It is possible to implement ranges in compile-time Zig:

**Comment by SpexGuy** [comment]
You can also do it at runtime and without reserving static memory like this:
```zig
const std = @import("std");

fn rangeHack(len: usize) []void {
    // No chance of UB [*]void is a zero-size type
    return @as([*]void, undefined)[0..len];
}

pub fn main() void {
    for (rangeHack(10)) |_, i| {
        std.debug.warn("{} ", .{i});
    }
}

Output:
0 1 2 3 4 5 6 7 8 9
```
But this is definitely a hack.

**Comment by DanB91** [comment]
> Anyone coming from another C like language is instantly going to know how to write and read loop declarations like C:
> 
> ```c
> for (initialization ; condition; increment) {
>     body
> }
> ```
> 
> Maybe I'm missing something. Is there a reason to avoid using C style loops?
> 
> I assume the purpose of this is to figure out how to declare new variables in the scope of the `for` loop. If this is the case, JavaScript does something similar:
> 
> ```js
> for (var i = 0; i < 100; i++) {
>     console.log(i);
> }
> ```

+1 for this question. What is the aversion to C-style for loops?  I am okay with a for-range syntax, but I find the C-style for loop much easier to type and easier to read than the current while loop idiom.

**Comment by anosovic** [comment]
my only issue with C-style for loops is they have two different places to write the loop body
```C
for (int i = 0; i < 10; i++) {}
// versus
for (int i = 0; i < 10;) {i++;}
```
redundant?

**Comment by DanB91** [comment]
> my only issue with C-style for loops is they have two different places to write the loop body
> 
> ```c
> for (int i = 0; i < 10; i++) {}
> // versus
> for (int i = 0; i < 10;) {i++;}
> ```
> 
> isnt this redundant? zig has the same issue
> 
> ```zig
> var i : usize = 0;
> while (i < 10) {i += 1;}
> // versus
> var i : usize = 0;
> while (i < 10) : (i += 1) {}
> ```

`for (var i: usize = 0; i < 10; i+=1)` is less characters and I find it more natural to write than
`var i: usize = 0; while (i < 10) : (i+=1) {`. And plus the i is automatically scoped unlike the while idiom (which would require a {} block)!

Alternatively we could have something like `for (0..10) |i| {` or `for (0..10->2) |i| {` (where 2 is the step)  which is better than C-style for loops.  By my main point is that if we don't want to do for-range loops, even C-style for loops are strictly better than the while idiom we have now.

**Comment by DanB91** [comment]
> my only issue with C-style for loops is they have two different places to write the loop body
> 
> ```c
> for (int i = 0; i < 10; i++) {}
> // versus
> for (int i = 0; i < 10;) {i++;}
> ```
> 
> isnt this redundant? zig has the same issue
> 
> ```zig
> var i : usize = 0;
> while (i < 10) {i += 1;}
> // versus
> var i : usize = 0;
> while (i < 10) : (i += 1) {}
> ```

`for (var i: usize = 0; i < 10; i+=1)` is less characters and I find it more natural to write than
`var i: usize = 0; while (i < 10) : (i+=1) {`. And plus the i is automatically scoped unlike the while idiom (which would require a {} block)!

Alternatively we could have something like `for (0..10) |i| {` or `for (0..10:2) |i| {` (where 2 is the step)  which is better than C-style for loops.  By my main point is that if we don't want to do for-range loops, even C-style for loops are strictly better than the while idiom we have now.

**Comment by SpexGuy** [comment]
> isnt this redundant? zig has the same issue

They are not redundant.  These three loops have slightly different semantics in Zig:
```zig
var curr: ?*Node = getListHead();

// loop 1
while (curr) |node| : (curr = node.next()) {
    if (cond_a) { continue; }
    if (cond_b) { break; }
}

// loop 2
while (curr) |node| {
    defer curr = node.next();
    if (cond_a) { continue; }
    if (cond_b) { break; }
}

// loop 3
while (curr) |node| {
    if (cond_a) { continue; }
    if (cond_b) { break; }
    curr = node.next();
}
```

Loop 1: `curr = node.next()` will execute on continue but not on break
Loop 2: `curr = node.next()` will execute on both continue and break
Loop 3: `curr = node.next()` will not execute on continue or break

**Comment by andrewrk** [comment]
Use anonymous blocks to limit the scope of variables.

**Comment by markfirmware** [comment]
nymous blocks also work well - the label is a comment and the first curly is pushed over where it belongs.

    findOrCreateKey: {
       var i = 0;
       while (...) : (i += 1) {
           ...
       }
    }

**Comment by marler8997** [comment]
I realize this issue is closed but after reading some of the comments I see an idea that could address this and other issues.  Namely, to provide a way to define symbols for the next statement/expression.  Something like this:
```
with (vars...) <block/statement>
```
So for loops you'd have:
```zig
with (var i : usize = 0) while (i < 10) : (i += 10) {
    ...
}
```
And this could also be used to define symbols/aliases for functions:
```zig
with (comptime const T = @TypeOf(a).Pointer.child)
pub fn foo(a: var) !T {
    var b: T = undefined;
    // ...
    return T.init(...);
}
```
Maybe you could use struct literals for the `with <struct_literal>` but not sure.

**Comment by user00e00** [comment]
I'm not so much a fan of anonymous blocks when you have a lot of nested loops 

```zig
while(std.utils.Range(0,10)) |i| { // statement cannot both be a declaration and a '.next()' call
   // do stuff
} 
```
Creating an iterator is not the same as a testing a boolean expression though.

Maybe the `for` syntax could be changed to expect iterator declarations (with `next()` / `hasNext()` "methods") instead of expecting slices, and `while` could stick to accepting a condition expression returning a bool or an optional.

```zig
for(std.utils.SliceIterator(arr[4..10]) |value| {
     // do stuff
}
const iterate = std.utils.SliceIterator;
for( iterate(arr[4..10]) |value| {
     // do stuff
}

for(std.utils.Range(0,10) ) |i| {
     // do stuff
}
```

Uglier, but in more versatile?

**Comment by andrewrk** [comment]
There is one thing that is open to changing here which is having `zig fmt` support this form:

```zig
{var i: i32 = 0; while (i < 10) : (i += 1) {
    blah();
}}
```

**Comment by karrick** [comment]
At that point, it really looks like a C `for` loop with a bit more characters. Which both means people coming from C like languages will both feel more at home with that syntax form, and leave them wondering why the syntax just does not mimic C.

**Comment by iology** [comment]
> ```
> {var i: i32 = 0; while (i < 10) : (i += 1) {
>     blah();
> }}
> ```

inconsistent coding style on the spot, nitpicking starts...

While if/while/for/switch all support `|capture|`, the later three all have their specialty:

* `while`: `: (i += 1)` where `i += 1` is not an expression. `for(int i=0;i<10;i+=1)` must cry
* `for`: only works on a slice, without too much hidden logic in C's `for(auto x : container)`
* `switch`: case `const_min ... const_max_inclusive` where `...` cannot be used elsewhere and `..` also not supported

well, just small complaint. I think `for (0..10) |i|` is considerable for the use case above. And in case anyone may think this is slippery slope theory, let's drop support for `for (slice) |v, i|`. This way if/while/for/switch all capture one value, in the meantime also leave some design space for the tuple syntax and structural assignment.

```
for (arr[0..10]) |&v, i| { v = i; }
// becomes
for (0..10) |i| { arr[v] = i; }

if (opt_tuple) |x| f(x[0]);
if (opt_tuple) |x, y| g(x, y);

if (opt_struct) |.x, .y| g(x, y);
```

**Comment by anosovic** [comment]
why do we even need `: (i += 1)` syntax? wouldnt it be better to just remove all those nuances @SpexGuy delineated? to *minimize energy spent on coding style*
