### ISSUE TITLE
Explicit struct layout

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#5073]
*oops; I accidentally created this issue before I wrote it out. Bear with me for a couple of days as I finish the proposal*

--------------

`packed struct` doesn't give enough control
Explicit layout by declaring `bitOffsetOf`/`byteOffsetOf`
Cap n proto
Overlapping fields

Alternative to #5049
This proposal may be adding too much complexity, #383 might be a better solution.

**Comment by andrewrk** [comment]
Feel free to edit & reopen when it's done
