### ISSUE TITLE
Proposal: have std.math.lossyCast support int -> int and float -> int

### ISSUE THREAD

**Issue by pfgithub** [ziglang/zig#5080]
It would be helpful for lossyCast to support casting to integers.
```zig
test "example" {
    testing.expect(math.lossyCast(u64, @as(i64, -1)) == 0);
    testing.expect(math.lossyCast(i8, @as(f64, 200)) == 127);
}
```
Currently, trying to lossyCast int -> int produces an error `expected float type, found 'i8'`, and lossyCast float -> int is missing an error (#5079)

**Comment by AdamGoertz** [comment]
I implemented this for fun. I can PR if you decide it's something you want in the standard library.

**Comment by pfgithub** [comment]
@AdamGoertz If you make a pull request with that, it will probably be merged or discussed further
