### ISSUE TITLE
Add C as a target architecture

### ISSUE THREAD

**Issue by The-Jon** [ziglang/zig#5107]
I would appreciate it if you could add a "C" Target. I know it shouldn't be used because of the optimization and information lost. But just as an option to compile Zig for platforms/architectures which aren't supported by clang.

**Comment by emekoi** [comment]
by "c target" do you mean a c backend so that zig can transpile to c?

**Comment by The-Jon** [comment]
Yes, to support more architectures.

**Comment by jayschwa** [comment]
Interesting idea. Could a C target theoretically eliminate the need for the stage 1 compiler to be a separate implementation?

**Comment by andrewrk** [comment]
No because the point of bootstrapping is to go from source to generated code. Even if we committed the output of compilation (even if it is C code) to the repository, it would not make it source code, it would still be generated code.

**Comment by uael** [comment]
Related one #3772

**Comment by andrewrk** [comment]
Duplicated of already planned #3772
