### ISSUE TITLE
Can't use labeled block as if body?

### ISSUE THREAD

**Issue by donaldcallen** [ziglang/zig#5108]
This code:

```         
comptime std.debug.assert(builtin.single_threaded);
            const cache = struct {
                var maybe_statement: ?*s.sqlite3_stmt = null;
            };
            if (cache.maybe_statement) |stmt| stmt
            else :miss {
                cache.maybe_statement = zlib.prepare_statement([*:0]const u8, globals.db,
                    queries.account_child_all_sql);;
                break :miss cache.maybe_statement orelse unreachable;
            }
```
Results in this error:

```
zig build-exe --main-pkg-path .. --single-threaded `pkg-config --libs gtk+-3.0` -L/usr/local/lib -L/usr/lib -lc -lsqlite3 newcash.zig
./book.zig:78:18: error: invalid token: ':'
            else :miss {
                 ^
```

I am trying to use the if as expression, returning a value from either leg of the if. The else side
involves more than one statement, so I believe I need to use a labeled block to return a value from it. The compiler isn't buying it. Comments? Suggestions?

**Comment by donaldcallen** [comment]
Forgot to mention -- I am using zig-linux-x86_64-0.6.0+986aa42d3.tar.xz on an up-to-date
Slackware current system.

**Comment by SpexGuy** [comment]
The `:` goes on the right side of the label when specifying it and the left when referencing it.  So it should be
```
else miss: {
    ...
    break :miss <return value>;
}
```

We should probably call that out specifically in the docs, it's kind of hard to see.

**Comment by Tetralux** [comment]
... Or we could remove the need for the `:` when referencing it 😁

**Comment by donaldcallen** [comment]
Thank you very much. 

I will comment that this is a bit of syntax that merits reconsideration.

**Comment by squeek502** [comment]
Relevant proposal: https://github.com/ziglang/zig/issues/5083
