### ISSUE TITLE
Proposal: `@This` for anonymous functions: `@thisFn`

### ISSUE THREAD

**Issue by SpexGuy** [ziglang/zig#5113]
There are a lot of weird things about struct self-reference that come from all structs being anonymous.  Particularly with function scopes and comptime vars.

```zig
// Both direct and indirect self-reference work at struct scope
const StructCtConst = struct {
	next: *StructCtConst,
	interleaveA: *StructCtConst2,
};

const StructCtConst2 = struct {
	interleaveB: *StructCtConst,
};

var StructRtVar = struct { }; // error: struct var must be comptime

const funcScope = fn () void {
	const StructCtConst = struct {
		next: *StructCtConst, // error: StructCtConst not declared yet
		next: *@This(), // can self-reference via `@This()`
		interleaveA: ???, // can't reference struct that hasn't been declared
	};
	
	comptime {
		var StructCtVar = struct {
			next: *StructCtVar, // error: StructCtVar not declared yet
			next: *@This(), // self-reference allowed with @This()
			ct: *StructCtConst,
		};
		
		StructCtVar = struct {
		    inner: StructCtVar, // this copies the old value and then overwrites the var
		};
	}
};
```

To make anonymous structs in function scopes able to do self-reference, we added the `@This()` builtin.

Now that we're making all functions anonymous, we have an analagous set of problems.  In order to do recursion, we need a similar builtin `@thisFn()`.

```zig
// Both direct and indirect self-reference work at struct scope
const fnCtConst = fn () void {
	fnCtConst(); // direct recursion is ok
	fnCtConst2(); // indirect recusion is ok
};

const fnCtConst2 = fn () void {
	fnCtConst();
};

// unlike structs, runtime fn vars are allowed
var fnCtVar = fn () void {
	// can self-reference and overwrite
	fnCtVar = if (fnCtVar == @thisFn()) fn () void { } else @thisFn();
	// This is not recursion! This calls the function pointer.
	fnCtVar();
	// This is recursion.
	@thisFn()();
	// Can reference other runtime fn vars, but no way to encode a direct call to them.
	fnCtVar2();
};

var fnCtVar2 = fn () void {
	// can reference fn ptr, but can't call original function directly.
	fnCtVar();
};

const funcScope = fn () void {
	const fnCtConst = fn () void {
		fnCtConst(); // error: fnCtConst not declared yet
		@thisFn()(); // recursive call? analogue to `@This`
	};
	
	comptime {
		var fnCtVar = fn () void {
			fnCtVar(); // error: fnCtVar not declared yet
			@thisFn()(); // recursive call
			fnCtConst();
		};
		
		fnCtVar = fn () void {
			fnCtVar(); // calls the previous value of `fnCtVar`.  Not recursion.  See link 1 at the bottom if that seems weird to you.
		};
	}
	
	// unlike structs, runtime fn vars are allowed
	var fnRtVar = fn () void {
		fnRtVar(); // error: fnRtVar not declared yet
	};
	
	fnRtVar = fn () void {
		// If we had closures, this might be inconsistent with the comptime case.  But since we don't, it's fine.
		fnRtVar(); // error: closure over runtime var.
	};
};
```

This function provides two benefits:
- a way to reference the containing function regardless of context (can be copy-pasted and still work)
- a way to do recursion and self-reference in anonymous functions declared in execution scope (note that self-reference without direct recursion is sometimes useful, e.g. for a callback to pass itself back to a UI library to have it call again later.)

The current workaround is to declare a struct scope and put your functions in there, like we do right now, whenever you need to do recursion.  That might be good enough to say that we don't need this.  Most languages with anonymous functions don't provide something like this and can't recurse or self-reference in an anonymous function. ([java: requires class[2]](https://pysaumont.github.io/2014/09/01/Recursive-lambdas-in-Java-8.html), [python: use late-binding or madness[3]](https://stackoverflow.com/questions/481692/can-a-lambda-function-call-itself-recursively-in-python), [c++: use fn ptr or madness[4]](https://riptutorial.com/cplusplus/example/8508/recursive-lambdas)).  Zig's inline struct workaround is already way simpler than all of these, but the parallel with `@This` is nice so I think `@thisFn` merits discussion.

## Language Lawyering

- `@thisFn()` is always comptime-known
- calling `@thisFn()` from outside of any function scope is a compile error
- calling `@thisFn()` from inside namespaces inside a function still evaluates to the function
- when evaluating `@thisFn()`, calls from within a function parameter list or return type evaluate to the outer function, not the one with the parameter list.  e.g.
```zig
const a = fn() void {
	// both calls to `@thisFn()` on the next line evaluate to `a`, not `b`.
	const b = fn(cb: @TypeOf(@thisFn())) @typeInfo(@TypeOf(@thisFn())).Fn.return_type {
		_ = cb();
	}
};
```

---

[1] https://github.com/ziglang/zig/issues/1717#issuecomment-616692963
[2] https://pysaumont.github.io/2014/09/01/Recursive-lambdas-in-Java-8.html
[3] https://stackoverflow.com/questions/481692/can-a-lambda-function-call-itself-recursively-in-python
[4] https://riptutorial.com/cplusplus/example/8508/recursive-lambdas

**Comment by mikdusan** [comment]
I don't think we have precedent for ape'ing keywords or if there are parser issues, but have we considered:

- `@fn()` to return current function
- `@Fn()` to return type of `@TypeOf(@fn())`

**Comment by cajw1** [comment]
It would be nice if `@thisFn()` could be used inside a generic function (where `@sizeOf(@TypeOf(function)) == 0`) to refer to the currently executing body:

`````zig
fn addFactory(a: var, b: var) @TypeOf(a){  
    // var frame = @Frame(addFactory);// error: frame of generic function
    var frame = @Frame(@thisFn()); // should work
    //var myBody = &addFactory; // error: pointer to size 0 type has no address. 
    var myBody = &@thisFn(); // should work
    var myGeneratorsRuntimeSizeIs0 = @sizeOf( @TypeOf(addFactory) );
    var myRuntimeSizeIsNot0 = @sizeOf( @TypeOf(@thisFn()) );
    return a + b;
}
`````

**Comment by locriacyber** [comment]
This would enable recursive function calls for anonymous functions.

**Comment by locriacyber** [comment]
This feature is unnecessary. `struct` need `@This` because a file is a struct, and there is no other way to reference it.

The same example without `@thisFn`:
```zig
const a = fn() void {
	// both calls to `@thisFn()` on the next line evaluate to `a`, not `b`.
	const b = fn(cb: @TypeOf(@thisFn())) @typeInfo(@TypeOf(b)).Fn.return_type {
		_ = cb();
	}
};
```

**Comment by xdBronch** [comment]
should be closed since 1717 got rejected(?)
