### ISSUE TITLE
translate-c should coerce c_int to usize in pointer arithmetic

### ISSUE THREAD

**Issue by hazeycode** [ziglang/zig#5128]
```
char foo(unsigned char *ptr, int offset) {
    return *(ptr + offset);
}
```

produces

```
pub export fn foo(arg_ptr: [*c]u8, arg_offset: c_int) u8 {
        var ptr = arg_ptr;
        var offset = arg_offset;
        return @bitCast(u8, (ptr + offset).?.*);
}
```

resulting in `error: expected type 'usize', found 'c_int'`

offset should be coerced to usize i.e.

```
pub export fn foo(arg_ptr: [*c]u8, arg_offset: c_int) u8 {
        var ptr = arg_ptr;
        var offset = arg_offset;
        return @bitCast(u8, (ptr + @as(usize, offset).?.*);
}
```

**Comment by kyle-github** [comment]
I may be misremembering this, but I think that the offset can be signed, so you probably do not want to coerce to an unsigned Zig type.   I am not sure that it is actually legal C.   I certainly have seen code that uses negative offsets.

**Comment by hazeycode** [comment]
@kyle-github I think negative offsets are valid in c... but not disallowed by type assertion in zig. If this in fact the case, then translation will somewhat more complicated.

**Comment by Rocknest** [comment]
@kyle-github you can try to compile&run such code with UBSan and check if its undefined behaviour or not

**Comment by Vexu** [comment]
Produces:
```zig
pub export fn foo(arg_ptr: [*c]u8, arg_offset: c_int) u8 {
    var ptr = arg_ptr;
    var offset = arg_offset;
    return @bitCast(u8, (ptr + @bitCast(usize, @intCast(isize, offset))).?.*);
}
```
with master which works as expected.
