### ISSUE TITLE
`zig cc` fails when targeting powerpc64-linux-musl

### ISSUE THREAD

**Issue by Xe** [ziglang/zig#5142]
Using `zig 0.6.0` installed from nixos-unstable (specifically `/nix/store/rgc4wscqxabb6qr15szhw6rflj2n2y8k-zig-0.6.0/bin/zig`), I tried to build the following .c file for the target powerpc64-linux-musl with the following command:

```console
$ zig cc -target powerpc64-linux-musl hello.c
```

```c
#include <stdio.h>

int main() {
        printf("hello ppc64be\n");
}
```

I expected to get a powerpc64 big endian static binary, but instead I got the following output: https://clbin.com/xXH7u

The preprocessed source is: https://clbin.com/JCFVr
The run script is: https://clbin.com/OMu9n

I was able to get a similar error when using the release tarball from ziglang.org. @mikdusan was able to replicate this on macos and arch linux. I think this may be a bug in Zig.

**Comment by andrewrk** [comment]
Thanks for the report. The next step here is to come up with a minimal repro that crashes clang and then create an upstream bug report on the clang bug tracker.

**Comment by andrewrk** [comment]
Tested locally; this is no longer a problem at least with `0.11.0-dev.995+7350f0d9b`
