### ISSUE TITLE
Darwin Kevent struct "filter" offset incorrect

### ISSUE THREAD

**Issue by iansimonson** [ziglang/zig#5144]
Compiling some zig code recently I hit the following:
```
A-Macbook:zigray iansimonson$ zig build-lib --release-fast -target wasm32-macosx lib.zig
Semantic Analysis [376/445] /usr/local/lib/zig/std/debug.zig:228:14: error: unable to evaluate constant expression
    if (!ok) unreachable; // assertion failure
             ^
/usr/local/lib/zig/std/os/bits/darwin.zig:161:11: note: called from here
    assert(@byteOffsetOf(Kevent, "filter") == 8);
          ^
/usr/local/lib/zig/std/os/bits/darwin.zig:159:10: note: called from here
comptime {
         ^
/usr/local/lib/zig/std/os/bits/darwin.zig:161:11: note: referenced here
    assert(@byteOffsetOf(Kevent, "filter") == 8);
          ^
```
Adding a compileLog resulted in:
```
A-Macbook:zigray iansimonson$ zig build-lib --release-fast -target wasm32-macosx lib.zig
Semantic Analysis [242/423] | 4
Semantic Analysis [376/445] /usr/local/lib/zig/std/os/bits/darwin.zig:161:5: error: found compile log statement
    @compileLog(@byteOffsetOf(Kevent, "filter"));
    ^
/usr/local/lib/zig/std/debug.zig:228:14: error: unable to evaluate constant expression
    if (!ok) unreachable; // assertion failure
             ^
// the rest is identical to before so truncated here
```

Additional info:
This was on macOS Catalina 10.15.4
Compiled again on Zig master to confirm, Zig version: 0.6.0+6c907a350

**Comment by daurnimator** [comment]
> -target wasm32-macosx

Your target doesn't make much sense: Apple OSX doesn't run under webassembly.

**Comment by iansimonson** [comment]
I don't know much about wasm, was trying to get another repo to compile. Though this struct seems to exist regardless so thought it might be a broader issue, I'll look into it more though

**Comment by iansimonson** [comment]
Yep, weird behavior with doing something silly like that. Will close this then

**Comment by daurnimator** [comment]
> I don't know much about wasm, was trying to get another repo to compile. Though this struct seems to exist regardless so thought it might be a broader issue, I'll look into it more though

The target format is: CPUArchitecture-OperatingSystem-ABI
`wasm32-macosx` is saying that you'll be running under wasm32, where the operating system **inside of wasm** is OSX. 
What you probably want is `-target wasm32-freestanding` which is wasm32 with no operating system inside.
