### ISSUE TITLE
./build: 13: Bad substitution

### ISSUE THREAD

**Issue by k2l8m11n2** [ziglang/zig#5147]
When running `./build` from the 0.6.0 bootstrap tarball it errors out on the 13th line, like so:
```
./build: 13: Bad substitution
```
`#/bin/sh` defaults to `dash` (version `0.5.10.2-6` on my system) on Debian-alikes and my guess is you're using some feature that's not in the POSIX standard and therefore not in `dash`. Running it with `bash` or `zsh` works just fine.

**Comment by k2l8m11n2** [comment]
`checkbashisms` from [Debian's `devscripts`](https://packages.qa.debian.org/d/devscripts.html) reports:
```
possible bashism in build line 13 (${parm,[,][pat]} or ${parm^[^][pat]}):
TARGET_OS_CMAKE=${TARGET_OS_LOWER^} # Example: Linux
```

**Comment by andrewrk** [comment]
Please double check the issue against master

**Comment by k2l8m11n2** [comment]
There's no bootstrap tarball for master as far as I can see?

**Comment by joachimschmidt557** [comment]
In https://github.com/ziglang/zig-bootstrap/blob/master/build, the issue should have been fixed. I tested it with `dash` and didn't get any syntax errors.

**Comment by k2l8m11n2** [comment]
Oh right, it's in a different repo. Sorry, I didn't notice that!
