### ISSUE TITLE
zig cc: mcpu flag is not taken into account during cache lookup

### ISSUE THREAD

**Issue by ftilde** [ziglang/zig#5150]
Suppose we have a file `bar.c` which we want to (cross-) compile to the target `arm-linux-musleabihf`, but are unsure about the architecture.

Scenario 1:
* We first try `zig cc bar.c -target arm-linux-musleabihf -mcpu=arm1176jzf_s -o bar`
* `readelf -A bar | grep CPU_name` correctly reveals: `Tag_CPU_name: "arm1176jzf-s"`
* Now we try `zig cc bar.c -target arm-linux-musleabihf -mcpu=cortex_a7 -o bar`
* `readelf -A bar | grep CPU_name` *again*, reveals: `Tag_CPU_name: "arm1176jzf-s"`

Scenario 2 (after a `rm -r zig_cache` and `rm -r ~/.cache/zig`)
* We first try `zig cc bar.c -target arm-linux-musleabihf -mcpu=cortex_a7 -o bar`
* `readelf -A bar | grep CPU_name` correctly reveals: `Tag_CPU_name: "cortex-a7"`
* Now we try `zig cc bar.c -target arm-linux-musleabihf -mcpu=arm1176jzf_s -o bar`
* `readelf -A bar | grep CPU_name` *again*, reveals: `Tag_CPU_name: "cortex-a7"`

In fact, in both scenarios there is only one `bar.o` in the local `zig_cache` and (for example) only one `crt1.o` in the global cache, both of which have the cpu name of the first invocation of `zig cc` after removing the cache.

Despite this inconvenience I want to add that zig ist just fantastic (even if you are only interested in cross compiling c) and I am very grateful for this!

**Comment by andrewrk** [comment]
Ah here's the problem. `create_c_object_cache` is missing that field:

https://github.com/ziglang/zig/blob/a9eb4a6740e0bb00e1984de3768a7de6001c25dd/src/codegen.cpp#L9824-L9829

For zig code it is used:

https://github.com/ziglang/zig/blob/a9eb4a6740e0bb00e1984de3768a7de6001c25dd/src/codegen.cpp#L10620-L10628

**Comment by andrewrk** [comment]
As part of solving this issue, the function `add_cc_args` should be inspected for any more state that it reads to determine the flags to pass to clang, and make sure that state is added to the cache hash in `create_c_object_cache`.
