### ISSUE TITLE
AES memory usage

### ISSUE THREAD

**Issue by zigazeljko** [ziglang/zig#5153]
The standard library currently implements AES as a single struct that holds both expanded keys (for encryption and for decryption). Since each individual operation (`encrypt`, `decrypt`, `ctr`) only uses one of the expanded keys, a single instance of this struct wastes half of its size if it is not used for both encryption and decryption (which is often the case in practice).

My proposal is to split the `AES` struct into two (eg. `AESEncrypt` and `AESDecrypt`), each holding only a single expanded key and corresponding methods (`encrypt` and `ctr` on one, `decrypt` on other). `expandKey` should then also be split into two parts (encryption key expansion and conversion from encryption key to decryption key), since the second part is not needed when doing encryption.

**Comment by daurnimator** [comment]
> My proposal is to split the `AES` struct into two (eg. `AESEncrypt` and `AESDecrypt`)

Makes sense to me: just have `std.crypto.AES.Encrypt` and `std.crypto.AES.Decrypt`.
