### ISSUE TITLE
std.math.cosh does not produce correct output with negative f64 input

### ISSUE THREAD

**Issue by nickappleton** [ziglang/zig#5168]
The attached patch adds tests for negative inputs for both f32 and f64 types and a fix for cosh64 which produces incorrect output for negative input. The issue is due to not masking off the sign-bit before evaluating the range tests.

[01_add_cosh_negative_fix_and_tests.diff.zip](https://github.com/ziglang/zig/files/4534583/01_add_cosh_negative_fix_and_tests.diff.zip)

Sorry about this being a patch file instead of a pull-request... I'm new.

**Comment by pfgithub** [comment]
If you fork this repository on github and make the changes in your fork, you can then submit a pull request here

**Comment by nickappleton** [comment]
Sorry, I'm a total newbie with pull requests. I have just set one up with this change as well as an identical one for sinh() which I have just identified is broken in an identical way.

Can I just ask so I know for future: if I encounter bugs in Zig which I can fix, should I setup a pull request and file an issue? Or is a pull request by itself sufficient?

Thanks for the great work!

**Comment by daurnimator** [comment]
> Can I just ask so I know for future: if I encounter bugs in Zig which I can fix, should I setup a pull request and file an issue? Or is a pull request by itself sufficient?

Just a pull request is fine: though its good to file an issue before you start work on the fix; especially if the fix is non-trivial or opinionated.

**Comment by andrewrk** [comment]
Solved by @nickappleton in #5172, landed in 28c31a8429f513f2d0e04ff5193faa8147721b19.
