### ISSUE TITLE
zig build can't have options before it

### ISSUE THREAD

**Issue by thejoshwolfe** [ziglang/zig#519]
```
zig/build$ ./zig --color on build --build-file ../build.zig test
Unrecognized command: build
Usage: ./zig [command] [options]
Commands:
  build                        build project from build.zig
...
```

It looks like `"build"` is handled here:

https://github.com/zig-lang/zig/blob/0a4283b38ba40242f8f9302a63e8c4d664a50799/src/main.cpp#L315

instead of here:

https://github.com/zig-lang/zig/blob/0a4283b38ba40242f8f9302a63e8c4d664a50799/src/main.cpp#L579

**Comment by andrewrk** [comment]
`zig build` takes a different set of options than the other commands. `--color on` is not a valid command to `zig build`. You can see the available commands with `zig build --help`.

**Comment by thejoshwolfe** [comment]
`--color on` should be a valid option to `zig build`. I worked around this by hardcoding `errmsg.cpp` to always print in color.

In general, the parameter parsing for `zig build` needs some work. Unrecognized options are not reported as errors, for example.

**Comment by andrewrk** [comment]
Why do you need `--color on` is auto color not detecting your terminal?

You can add `--color` by following the example in main.cpp set with `--zig-lib-dir`.



> In general, the parameter parsing for zig build needs some work. Unrecognized options are not reported as errors, for example.

Can you give an example? Works for me:

```
andy@xps:~/dev/liblaxjson$ zig build --derp
Unrecognized argument: --derp

Usage: /home/andy/dev/zig/build/zig build [steps] [options]

Steps:
  default                Build the project
  test                   Run the tests
  install                Copy build artifacts to prefix path
  uninstall              Remove build artifacts from prefix path

General Options:
  --help                 Print this help and exit
  --build-file [file]    Override path to build.zig
  --cache-dir [path]     Override path to cache directory
  --verbose              Print commands before executing them
  --debug-build-verbose  Print verbose debugging information for the build system itself
  --prefix [prefix]      Override default install prefix

Project-Specific Options:
  -Drelease-safe=(bool)  optimizations on and safety on
  -Drelease-fast=(bool)  optimizations on and safety off
  -Dstatic=(bool)        build static library instead of shared

Build failed. Use the following command to reproduce the failure:
./zig-cache/build /home/andy/dev/zig/build/zig . ./zig-cache --derp
```

**Comment by thejoshwolfe** [comment]
> Why do you need --color on? Is auto color not detecting your terminal?

There were too many errors that I couldn't scroll to the top, so I wanted to pipe stderr into `head -n 50` and still have color.

> Can you give an example? Works for me:

Ok, the situation is that `build_runner.zig` has compile errors, and I want color on those errors. So it's not that the `build` command's argument parsing is failing; it's that when `zig` tries to do the `build` command, I want to configure the `--color` behavior.

For reference, this was during a project to replace `%%` with `%return` in `build.zig` and elsewhere for #510.

**Comment by andrewrk** [comment]
> Ok, the situation is that build_runner.zig has compile errors, and I want color on those errors.

In this case I suggest following this pattern: 

https://github.com/zig-lang/zig/blob/c180ef86afee17e36135b653fb6256cff46f4e69/src/main.cpp#L338-L343

And then also look for that command in `build_runner.zig` and pass it on to the zig binary in std/build.zig.

I think we can also change main.cpp to allow args before `build`. I'm going to continue to work toward 0.1.0 first though.

**Comment by andrewrk** [comment]
This is still true, but working as designed.
