### ISSUE TITLE
qes: can you please explain the design decision behind for and while loop syntax

### ISSUE THREAD

**Issue by kolokd** [ziglang/zig#5204]
i have tried to get used to the syntax but i feel uncomfortable reading a loop and while writing it.

**Comment by Sircular** [comment]
The for loop syntax seems to be inspired by functional programming. If it's helpful, perhaps try to conceptualize it as an anonymous function that is invoked for each entry in the list. 

As for the while loop, I assume you mean the one associated with an optional type? That's rather similar to the for loop syntax.

**Comment by kolokd** [comment]
@andrewrk

**Comment by kolokd** [comment]
hello. ??

**Comment by andrewrk** [comment]
@kolokd welcome to the community. Here are some places where you can ask this question and discuss various zig related topics: 

https://github.com/ziglang/zig/wiki/Community

**Comment by kolokd** [comment]
why this question can not be answered here. I am asking for an explanation of the syntax in the doc
