### ISSUE TITLE
remove builtin functions for creating types that are redundant with @Type

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#5207]
* `@OpaqueType`
 * `@IntType`
 * `@Vector` (let's consider adding syntax for this one before removing it)
 * anything else?

**Comment by tadeokondrak** [comment]
With #5203, `@Frame`

**Comment by tadeokondrak** [comment]
This is still accepted but should probably be rejected/closed - see the more recent accepted proposal https://github.com/ziglang/zig/issues/10710
