### ISSUE TITLE
FR: provider a cmake toolchain.

### ISSUE THREAD

**Issue by zhaozg** [ziglang/zig#5212]
[here](https://github.com/luvit/luvi/blob/master/CMakeLists.txt) use cmake build.
When I try to build it with `zig cc`, I found it hard to make  toolchain support. So I need help or need a office version of zig.toolchina.cmake.

**Comment by andrewrk** [comment]
Hi @zhaozg, welcome. A zig cmake toolchain sounds like a useful third party project for someone to start. I believe it is outside the scope of this project repository, however.
