### ISSUE TITLE
Low priority proposal: Shorten 'const' to 'cn'

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#5215]
Related: #5076

Cons:
- `cn` needs context to be associated with 'constant declaration', while 'const' is self explanatory
- `cn` vs `fn`. not as distinguishable as `const` and `fn`
   - #1717: `const func = fn(...) Type {}` vs `cn func = fn(...) Type {}`
- Syntax highlighting becomes more essential
- No use case requires this kind of syntax change
- "Indentation" is the same for `if` and `cn`
  - Might warrant different syntax highlighting for `cn` vs `if/else/switch/while`

Pros:
- `cn` is shorter than `const`
- `cn` is also shorter than `var`
- `const` appears very frequently in code. 
  - Making the connection between `cn` and 'constant declaration' will happen quickly for newcomers.
  - Makes sense to keep the most commonly used language keywords the shortest
- Grammar change only. semantics stay the same.
  - Could allow both `cn` and `const` in a transition period, and let zig fmt convert to the new form in the meantime
  - Very easy to both implement and retract if it doesn't work out
- Immutable slices will look nicer `[]cn u32` vs `[]const u32` in that the type will stand out more than the immutability qualifier.

An alternative to `cn` is `df` for define, but `[]df u8` doesn't work, whereas `[]cn u8` is permissible. Related: #5056

**Comment by data-man** [comment]
`cn` is too long. `c` is better and isn't China.

**Comment by EleanorNB** [comment]
So we have `v` and `c`? Sounds good.

**Comment by EleanorNB** [comment]
Or maybe `var` and `con`?

**Comment by SuperAuguste** [comment]
I dislike this proposal a lot as `const` is much more intuitive to the programmer and reader, compared to `c`, or `con`, or `cn`, which could be very confusing, and sometimes hard to spot.

One of Zig's Zens is "Favor reading code over writing code.", and in my opinion, this change would violate that Zen.

**Comment by user00e00** [comment]
By the (-1) reactions I suppose `const` is too established by now to be replaced, and it's also perfectly fine to keep it as it is. The issue can be reopened if there's any renewed interest later.

**Comment by porceCodes** [comment]
Ergonomics view:
`var` 3 letters, `const` 5 letters.

```
var x : u8  = 10;
let y : u8 = 20;   // 3 letter case
const z : u8 = 30; // 5 letter case
```
`let` is from [Swift](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/thebasics/#Constants-and-Variables)

**Comment by mlugg** [comment]
`let` has already been rejected: https://github.com/ziglang/zig/issues/181
