### ISSUE TITLE
Assertion failed at /deps/zig/src/analyze.cpp:745 in get_error_union_type.

### ISSUE THREAD

**Issue by bens** [ziglang/zig#5227]
I can't see this reported anywhere else and I've tested against the latest master build, 2020-04-30 (zig-linux-x86_64-0.6.0+e72f45475.tar.xz).

```
const c = @cImport(@cInclude("stdlib.h"));

const E = error{Err};

pub fn main() E!void {
    _ = try f();
}

fn f() E!c_void {
    return if (c.malloc(1024)) |bs| bs else E.Err;
}
```
Then I get
```
$ zig build-exe err-error-union.zig -lc 
Assertion failed at /deps/zig/src/analyze.cpp:745 in get_error_union_type. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
Aborted
```
The program is wrong because `f` is declared to return a `E!c_void`, but the value it's returning is a `E!*c_void`. This is a fairly easy mistake to make, I was playing with SDL2 and declared I was returning a `E!c.SDL_Window` from a function when in fact the value was a `E!*c.SDL_Window` and got this error.

If I get the signature wrong in a different way by saying it returns `E!void` I do get a much better error:
```
./err-error-union.zig:10:37: error: expected type 'void', found '*c_void'
    return if (c.malloc(1024)) |bs| bs else E.Err;
```
I'm not certain if the error part of the return type is necessary to this error.

**Comment by xackus** [comment]
Yet another bug with opaque types. I will take a look at it.

**Comment by iamgreaser** [comment]
Also hitting this while trying to put together a GLFW3 wrapper on 0.6.0.

For context, `Window` is an alias for `GLFWwindow` in `GLFW/glfw3.h`. This is an opaque struct.

```
pub fn createWindow( ... ) Error!Window { ... }
```
causes the assertion, while

```
pub fn createWindow( ... ) Error!*Window { ... }
```
does not.

**Comment by Vexu** [comment]
Tested in `test/cases/compile_errors/invalid_error_union_payload_type.zig`
