### ISSUE TITLE
comptime code evaluation leaks memory

### ISSUE THREAD

**Issue by The-Jon** [ziglang/zig#5228]
```zig
pub fn main()!void{
     //nobody uses such high numbers...
    //but even a single while(true) loop at comptime uses an infinite amount of resources
    @setEvalBranchQuota(99999999);
    comptime stop();
}

fn stop() void{
    while(true){}
}
```

**Comment by andrewrk** [comment]
Hi @The-Jon, thanks for pointing out this issue.

The fact that the PC crashes when it runs out of memory is the operating system's fault. I wish it did not work this way, but that is not under zig's control.

The fact that Zig stage1 leaks memory is known, and not planned to be fixed. Self-hosted will be able to have a `comptime while(true) {}` that uses a fixed amount of memory without leaking. 
Once #89 is closed this issue will be resolved, however I'll leave it open until we are shipping a compiler that does not have this behavior.

The issue to use *less* memory in stage1 is #471.

**Comment by Vexu** [comment]
Running the example with the self-hosted compiler uses a fixed amount of memory.
