### ISSUE TITLE
No redeclaration error on shadowing if global used

### ISSUE THREAD

**Issue by iansimonson** [ziglang/zig#5264]
The following code compiles on zig master with a strange result:
```zig
pub const value: usize = 4;

pub const S = struct {
    pub const value: usize = 3; // no compiler error

    pub fn foo(self: @This()) void {
        std.debug.warn("{}\n", .{value});
    }
};

pub fn main() void {
    std.debug.warn("{}\n", .{value}); // prints 4 as expected
    const s: S = .{};
    s.foo(); // Also prints 4
}
```

However if the `std.debug.warn("{}\n", .{value});` is commented out from main() we get the redeclaration error as expected.

The lack of error wouldn't be the end of the world _if_ `s.foo()` printed 3 as this would bring structs and namespaces from `@import` even closer to being the same thing

**Comment by Vexu** [comment]
Duplicate/related https://github.com/ziglang/zig/issues/5152#issuecomment-620853243.

**Comment by Vexu** [comment]
Tested in `test/cases/compile_errors/ambiguous_decl_reference.zig`
