### ISSUE TITLE
Json dump format documentation 

### ISSUE THREAD

**Issue by Rocknest** [ziglang/zig#5265]
I've tried to implement type printing for generated documentation, but ran into some trouble since i don't understand the format of data.js and reading c++ code didn't really give me many clues. There are many fields that have integer values, but i have no idea in what section i should lookup it.

It would be really helpful to have some explanation on how it is structured. Thanks!

**Comment by thejoshwolfe** [comment]
If the generated documentation you're referring to is the Autodoc project, there's an active community on [Discord](https://discord.gg/zig) in the #autodoc channel. The Autodoc project is still a work in progress, so I don't expect written documentation on its structure will be available soon.
