### ISSUE TITLE
for detecting the native dynamic linker path, zig should prefer /usr/bin/env to its own executable

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#5280]
This is a super edgy edge case, but I realized that `/usr/bin/env` is a more reliable way to obtain the native system dynamic linker path than zig's own dynamic paths. It's possible for a zig binary to be cross compiled for an older libc, or leftover from an older libc, while the system gets updated. In this case, `/usr/bin/env` will be correct while zig compiler's own dynamic linker path will be outdated.

**Comment by BratishkaErik** [comment]
#12788 resolved this
