### ISSUE TITLE
Multiple external function declarations causes compiler segfault

### ISSUE THREAD

**Issue by snocl** [ziglang/zig#529]
Trying to reference an `extern` function declared with two different types causes the compiler to segfault, even when the types should be “compatible”.

This is a problem if multiple parts of a code base (say, two different statically linked libraries) try to use the same external function, but ends up using different argument types, e.g., through different instances of `extern struct`.

### Example

Sources:

```zig
// main.zig

const A = extern struct {
    field: c_int,
};

extern "c" fn f(?*A) void;

pub fn main() void {
    _ = @import("other.zig").f;
    _ = f;
}
```

```zig
// other.zig

pub const A = extern struct {
    field: c_int,
};

pub extern "c" fn f(?*A) void;
```

Note that `main.A` and `other.A` are distinct types; by replacing both definitions with `const A = c_int;` the example compiles.

Build command:

```
$ zig build-exe main.zig
    OR
$ zig build-obj main.zig
```

Back trace:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x6661656c2d86)
  * frame #0: 0x00000001021b89c1 zig`llvm::AttributeList::addAttributes(llvm::LLVMContext&, unsigned int, llvm::AttrBuilder const&) const + 91
    frame #1: 0x00000001021b8c01 zig`llvm::AttributeList::addAttribute(llvm::LLVMContext&, unsigned int, llvm::Attribute) const + 93
    frame #2: 0x000000010220e177 zig`llvm::Function::addAttribute(unsigned int, llvm::Attribute) + 41
    frame #3: 0x000000010002da9a zig`addLLVMAttr(val=0x000000010722bed8, attr_index=4294967295, attr_name="nounwind") at codegen.cpp:282
    frame #4: 0x000000010002ef74 zig`addLLVMFnAttr(fn_val=0x000000010722bed8, attr_name="nounwind") at codegen.cpp:303
    frame #5: 0x000000010002d8f5 zig`fn_llvm_value(g=0x0000000105017000, fn_table_entry=0x000000010669fa90) at codegen.cpp:462
    frame #6: 0x000000010002628f zig`do_code_gen(g=0x0000000105017000) at codegen.cpp:4222
    frame #7: 0x0000000100025771 zig`codegen_build(g=0x0000000105017000) at codegen.cpp:5562
    frame #8: 0x000000010008f723 zig`main(argc=3, argv=0x00007fff5fbff7c0) at main.cpp:788
    frame #9: 0x00007fffac045235 libdyld.dylib`start + 1
```

---

It looks like the problem occurs because the `extern` functions instead of being referenced through their local declarations, get referenced through a global table in:

https://github.com/zig-lang/zig/blob/5931a6b1a5b8f4941fc9b78f8960745f81594f17/src/codegen.cpp#L362-L368

The invalid cast on line 365 then seems to be what causes the crash later.

**Comment by andrewrk** [comment]
Strange, that bitcast is supposed to make exactly this situation work correctly. I'll look into this.

**Comment by andrewrk** [comment]
I think this issue is fixed but I'm going to leave it open until I add a unit test for it.
