### ISSUE TITLE
system.RTLD_* constants are broken on Darwin

### ISSUE THREAD

**Issue by artob** [ziglang/zig#5294]
With 0.6.0 (and still with HEAD, looks like) attempting to use `RTLD_NEXT`, `RTLD_DEFAULT`, `RTLD_SELF`, or `RTLD_MAIN_ONLY` from `std.os.system` results in the following error:

<img width="962" alt="Screen Shot 2020-05-08 at 06 14 49" src="https://user-images.githubusercontent.com/4963/81366422-48241b80-90f3-11ea-827f-8ed131c626f1.png">

The contents of the aforementioned `rtld_self.zig` minimal reproduction case:

    const std = @import("std");
    const testing = std.testing;
    const maxInt = std.math.maxInt;

    test "reproduce error: unable to perform binary not operation on type 'comptime_int'" {
      const RTLD_SELF = @intToPtr(*c_void, ~maxInt(usize) - 2);
      testing.expect(RTLD_SELF > 0);
    }

These constants are defined in [lib/std/os/bits/darwin.zig](https://github.com/ziglang/zig/blob/0.6.0/lib/std/os/bits/darwin.zig#L1235) as follows:

    pub const RTLD_NEXT = @intToPtr(*c_void, ~maxInt(usize));
    pub const RTLD_DEFAULT = @intToPtr(*c_void, ~maxInt(usize) - 1);
    pub const RTLD_SELF = @intToPtr(*c_void, ~maxInt(usize) - 2);
    pub const RTLD_MAIN_ONLY = @intToPtr(*c_void, ~maxInt(usize) - 4);

Incidentally, how does one make Zig "eagerly" compile all definitions, even when they are unused? I think the root cause problem here is that the standard library defines these constants, but never uses them, so they were able to persist in a broken state unless a user attempted to actually use them. (No doubt more such cases could be found.)

**Comment by xackus** [comment]
This is how you can make sure all definitions in the current file compile:
```zig
test "" {
    std.meta.refAllDecls(@This());
}
```

**Comment by artob** [comment]
Many thanks, @daurnimator, @Vexu, and @xackus!
