### ISSUE TITLE
std.fs.Watch needs to be rewritten

### ISSUE THREAD

**Issue by alexnask** [ziglang/zig#5304]
I tried fixing the compile errors until the compiler crashed instead.  
I will check out the build on linux soon and potentially update the title.

**Comment by andrewrk** [comment]
That code is from before the async/await function rewrite and needs to be entirely reworked to take advantage of the new language semantics.

**Comment by alexnask** [comment]
Ok, cool, I will try to implement the linux and windows parts for the new async functions tomorrow then.
