### ISSUE TITLE
Function with generic type parameter causes compiler segfault when referencing itself as return type 

### ISSUE THREAD

**Issue by Perelandric** [ziglang/zig#532]
In the following reduced example, the return type is mistakenly set as the function name instead of `type`. This results in a segmentation fault in the compiler.

``` rust
pub fn main() -> %void {
    const t = Foo(u32) {
      .x = 1
    };
}
// -------------------------v
fn Foo(comptime T: type) -> Foo(T) {
    return struct { x: T };
}
```

>zig build-exe ./generics.zig
Segmentation fault

Without the `comptime` param, we get an error message.

>zig build-exe ./test.zig
/.../test.zig:17:1: error: 'Foo' depends on itself
fn Foo() -> Foo() {

---

This is a release build.

>zig version
0.0.0.c180ef8

**Comment by snocl** [comment]
Seems like https://github.com/zig-lang/zig/blob/7f9dc4ebc10eb13e73466224f28ba62747693df9/src/ir.cpp#L10223-L10224 was supposed to catch it(?), but that the call at https://github.com/zig-lang/zig/blob/7f9dc4ebc10eb13e73466224f28ba62747693df9/src/ir.cpp#L10262 passing through https://github.com/zig-lang/zig/blob/c6295fe9abf5508d522ab4000b577a6f30a98a88/src/analyze.cpp#L1004-L1009 means the backward branch counter is reset to zero for each recursion.

**Comment by andrewrk** [comment]
The concept of backwards branches is for compile-time code execution, to detect an infinite loop. The code that detects things depending on themselves is this:

https://github.com/zig-lang/zig/blob/master/src/all_types.hpp#L297-L298

**Comment by andrewrk** [comment]
> means the backward branch counter is reset to zero for each recursion.

Also this is not true, recursion counts as a backwards branch. The code you're looking at above is for the top level entry to analyzing a value at global scope.

**Comment by andrewrk** [comment]
!! never mind, you were dead on.

The bug is because this is activating compile time code execution, which is exactly what you were talking about. Great catch.

**Comment by kristate** [comment]
Supposing that this is fixed?

```
/Users/cfkk/Source/zig2/build/532.zen:1:29: error: evaluation exceeded 1000 backwards branches
fn Foo(comptime T: type) Foo(T) {
                            ^
/Users/cfkk/Source/zig2/build/532.zen:1:29: note: called from here
fn Foo(comptime T: type) Foo(T) {
                            ^
/Users/cfkk/Source/zig2/build/532.zen:1:29: note: called from here
fn Foo(comptime T: type) Foo(T) {
                            ^
/Users/cfkk/Source/zig2/build/532.zen:1:29: note: called from here
fn Foo(comptime T: type) Foo(T) {
                            ^
/Users/cfkk/Source/zig2/build/532.zen:1:29: note: called from here
fn Foo(comptime T: type) Foo(T) {
                            ^
/Users/cfkk/Source/zig2/build/532.zen:1:29: note: called from here
fn Foo(comptime T: type) Foo(T) {
                            ^
/Users/cfkk/Source/zig2/build/532.zen:1:29: note: called from here
fn Foo(comptime T: type) Foo(T) {
                            ^
/Users/cfkk/Source/zig2/build/532.zen:1:29: note: called from here
fn Foo(comptime T: type) Foo(T) {
                            ^
/Users/cfkk/Source/zig2/build/532.zen:1:29: note: called from here
fn Foo(comptime T: type) Foo(T) {
                            ^
/Users/cfkk/Source/zig2/build/532.zen:1:29: note: called from here
fn Foo(comptime T: type) Foo(T) {
                            ^
/Users/cfkk/Source/zig2/build/532.zen:1:29: note: called from here
fn Foo(comptime T: type) Foo(T) {
                            ^
/Users/cfkk/Source/zig2/build/532.zen:1:29: note: called from here
fn Foo(comptime T: type) Foo(T) {

```

**Comment by andrewrk** [comment]
Great! So all we need is a compile_errors.zig regression test.
