### ISSUE TITLE
zig fmt can't handle relative paths on macOS

### ISSUE THREAD

**Issue by schroffl** [ziglang/zig#5325]
I'm running `macOS 10.15.4`. When calling `zig fmt` with a relative path it always fails with `error.FileNotFound`.

```
user@device ~/D/fmt-not-found> zig init-exe
Created build.zig
Created src/main.zig

Next, try `zig build --help` or `zig build run`

user@device ~/D/fmt-not-found> zig fmt src/main.zig
unable to open 'src/main.zig': error.FileNotFound

user@device ~/D/fmt-not-found> zig fmt ./src/main.zig
unable to open './src/main.zig': error.FileNotFound
```

Specifying the absolute path, on the other hand, works fine:
```
user@device ~/D/fmt-not-found> zig fmt /Users/user/Desktop/fmt-not-found/src/main.zig
user@device ~/D/fmt-not-found> echo $status
0
```

Is this intentional? If so, why?

**Comment by mikdusan** [comment]
git bisect points to fdff381a5644d5e12519ca53012d7b00a33a33c4

**Comment by schroffl** [comment]
Thanks for tracking it down.

**Comment by mikdusan** [comment]
This one looks to be a consequence of macOS 10.15 (and possibly 10.14) and related to either sandboxing or APFS and these overlayed volumes.

There are 2 ABI versions of `realpath`: `_realpath` and `_realpath$DARWIN_EXTSN` . The second one I see when using stock xcode/clang using `realpath()`. zig.exe has _both_ symbols linked which can't be a good thing. Regardless, it's the `_realpath` that doesn't play nice with macOS 10.15 (and maybe 10.14?) and probably has to do with apple advancing their SIP and sandboxing security.

By "play nice" I mean if inside user home dir, `_realpath` fails on non-absolute paths. If I jump into /tmp/ folder, then suddenly it works.

We'll need to find out how far back `_realpath$DARWIN_EXTSN` goes and if far enough see how we can reliably force that symbol.

**Comment by mikdusan** [comment]
to follow up, in the same manner we link with `fstat$INODE64` it looks like we need to examine which of these variants should be linked:

|symbol|
|---|
_fopen$DARWIN_EXTSN
_getgroups$DARWIN_EXTSN
_realpath$DARWIN_EXTSN
_select$DARWIN_EXTSN
