### ISSUE TITLE
JSON comptime type parser should support dynamic objects

### ISSUE THREAD

**Issue by leroycep** [ziglang/zig#5326]
I'm implementing [glTF](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md) parsing, and part of the specification is for extension objects that are dictionary objects.

Basically, I want to be able to do this:

```zig
const std = @import("std");
const json = std.json;
const testing = std.testing;

const T = struct {
    count: usize,
    extension: json.ObjectMap,
};

const src =
    \\ { "count": 42, "extension": { "hello": "world" } }
;

test "parsing the object" {
    const options = json.ParseOptions{.allocator = testing.allocator};
    const t = try json.parse(T, &json.TokenStream.init(src), options);
    testing.expectEqual(t.count, 42);
    testing.expectEqual(t.extension.get("hello"), json.Value {.String = "world"});
}
```

It would also be nice if I could be more specific about the types of the HashMap. For example, the [`mesh.primitive.attributes` object](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#meshes) allows some variance in the key name, and I want it to be parsed into a `StringHashMap(usize)`.

## Implementation methods

A couple of ideas:

* Detect the HashMap or ObjectMap types and make a special case for them
* Allow types to implement a `jsonParse` function

On my [gltf-zig](https://github.com/leroycep/gltf-zig) repository, I've copied zig's `std.json` and modified `parseInternal` to allow types to override their parsing behavior using the function `jsonParse`.

* Modified `json.parseInternal` to allow overrides: https://github.com/leroycep/gltf-zig/blob/master/json.zig#L1431-L1433
* Modified `json.parseFree`: https://github.com/leroycep/gltf-zig/blob/master/json.zig#L1675-L1680
* Partially implemented `json.Value.jsonParse` override: https://github.com/leroycep/gltf-zig/blob/master/json.zig#L1236-L1255
* `Map` type that reads into a `StringHashMap`: https://github.com/leroycep/gltf-zig/blob/master/gltf.zig#L5-L71

**Comment by fancl20** [comment]
I think supporting Sentinel-Terminated slice may also be useful. Currently it will failed at:

```
/opt/zig/lib/std/json.zig:1593:58: error: expected type '[:0]const u8', found '[]u8'
                            return arraylist.toOwnedSlice();
```

**Comment by daurnimator** [comment]
>     * Allow types to implement a `jsonParse` function
> 
> 
> On my [gltf-zig](https://github.com/leroycep/gltf-zig) repository, I've copied zig's `std.json` and modified `parseInternal` to allow types to override their parsing behavior using the function `jsonParse`.

FWIW I did prototype a `jsonParse` trait, but the need for token look-ahead made the API.... difficult to use. Before creating such a functionality, we'll need to abstract that away a little.

**Comment by bibo38** [comment]
@daurnimator Could you elaborate your problems with the token look-ahead (or what you want to abstract away)?

**Comment by daurnimator** [comment]
> Could you elaborate your problems with the token look-ahead

The current `parseInternal` API is that you pass in the current token, and a `tokens` object that can be used to get more.


> or what you want to abstract awa

I think we should enhance the `tokens` object to stuff the token back in (or only `peek` at it and then consume it only if used). So that a custom parse implementation only needs a single `tokens` argument

**Comment by r00ster91** [comment]
This looks similar to #11712.

**Comment by thejoshwolfe** [comment]
Several new JSON features are available since the original post. See https://ziglang.org/download/0.11.0/release-notes.html#JSON . I think this addresses everything in your original post.

If you still run into issue, please open a new issue.
