### ISSUE TITLE
`errdefer` in `json.parseInternal` causes lots of code generation

### ISSUE THREAD

**Issue by leroycep** [ziglang/zig#5327]
Specifically, this `errdefer` here: https://github.com/ziglang/zig/blob/f2d326607505f1f16d4964a824444aaa0da2c259/lib/std/json.zig#L1443-L1449

```zig
            errdefer {
                inline for (structInfo.fields) |field, i| {
                    if (fields_seen[i]) {
                        parseFree(field.field_type, @field(r, field.name), options);
                    }
                }
            }
```

Later, there is [an inline loop](https://github.com/ziglang/zig/blob/f2d326607505f1f16d4964a824444aaa0da2c259/lib/std/json.zig#L1457) for checking if the JSON key matches any of the fields. Inside that inline loop [it calls `try parse(...)`](https://github.com/ziglang/zig/blob/f2d326607505f1f16d4964a824444aaa0da2c259/lib/std/json.zig#L1478).

When I add some `@compileLog` statements inside the `errdefer`'s inline loop and try to parse [this](https://github.com/leroycep/gltf-zig/blob/master/gltf.zig#L73) `glTF` struct, it logs over 5000 calls to the `@compileLog` statement.

## Fixes

* Remove the `errdefer` and manually catch the error
  * https://github.com/leroycep/gltf-zig/blob/master/json.zig#L1516-L1561
  * While I was implementing this fix I also added an explicit error type to the `json.parse` function
  * This fix reduced the 5000 calls to less than 500 calls
* Make `errdefer` smart enough to avoid generating this code `O(n^2)` times
  * The code to catch the error only need to be generated once in this case. Not sure if this is true all cases like this.

**Comment by LemonBoy** [comment]
This is #283.

**Comment by andrewrk** [comment]
> This is #283.

:point_up: 

This will be solved in stage2 only.
