### ISSUE TITLE
std.zig.parse should return the incomplete AST when a parsing error occurs.

### ISSUE THREAD

**Issue by alexnask** [ziglang/zig#5328]
Currently, only `std.zig.parse` is marked pub.  
However, `parse` sets `root_node` to `undefined` when a parsing error is returned from `parseRoot`.  
This makes it impossible to use std to do any parsing and analysis of partial trees from documents with parsing errors which some programs may wish to do (e.g. language servers).

**Comment by Vexu** [comment]
The better solution is to make the parser attempt to continue parsing on error and then return an incomplete AST.

**Comment by alexnask** [comment]
@Vexu The parser already continues parsing after some errors (e.g. DeclBetweenFields).  
I agree it should try to skip and continue parsing for more errors, this issue is just addressing the fact that the default parse function throws the entire tree away if any error happens.  
I guess it makes sense in the places it is used currently, where you only need to report errors and bail out, which is why I would rather we just also expose `parseRoot` and let users handle the incomplete tree as they will.

**Comment by Vexu** [comment]
There won't be any need to expose `parseRoot` once it is made to return the AST unconditionally. `parserRoot` doesn't need to return `error.ParseError` since we know parsing failed from the error list not being empty.

**Comment by alexnask** [comment]
Fair enough.
