### ISSUE TITLE
Docs suggestion: cover async/await before suspend/resume

### ISSUE THREAD

**Issue by joethephish** [ziglang/zig#5330]
When I first read the docs for async/await I was a little confused since I thought it was important that I fully understood how suspend/resume worked before async/await. 

This was coming from languages like C# and JavaScript, and I was a little confused about why there were 4 keywords rather than 2.

While I now I understand it all, it would’ve been helpful for me if they were covered high level -> low level rather than the opposite way round!

**Comment by andrewrk** [comment]
For the language reference, I think it makes sense to cover the lower level building blocks before covering the higher level abstractions that build upon them. However I think you make a good point about other learning materials presenting the information in a more beginner-friendly manner. For example I think your suggestion would be on point for something like ziglearn.org (which is a third-party project).

**Comment by joethephish** [comment]
Yeah, that's fair. What with ziglearn.org and zig.news, there are lots more brilliant resources to learn from than when I raised this. Thanks!
