### ISSUE TITLE
Can't take the address of an extern variable as a constant value

### ISSUE THREAD

**Issue by yvt** [ziglang/zig#5344]
```zig
extern var external_variable: u32;
export const p_external_variable = &external_variable; // Error

var internal_variable: u32 = 42;
export const p_internal_variable = &internal_variable; // OK
```

Expected: Successful compilation

Actual:
```
<source>:2:36: error: cannot store runtime value in compile time variable
export const p_external_variable = &external_variable;
                                   ^
```

[Compiler Explorer Link](https://zig.godbolt.org/z/xssTCi)

**Comment by locriacyber** [comment]
This doesn't make sense at compile time if the symbol is not already defined (for example, when the symbol has weak linkage).

See https://github.com/ziglang/zig/issues/6789#issuecomment-1112354662

**Comment by andrewrk** [comment]
This works now. It only needs test coverage added and then the issue can be closed.
