### ISSUE TITLE
Proposal: rename "var" to "infer" in type inference

### ISSUE THREAD

**Issue by zzyxyzz** [ziglang/zig#5346]
[ Bikeshedding Alert ]

Zig supports type inference for function parameters:

```zig
fn triple(x: var) @TypeOf(x) {
    return 3 * x;
}
```

However, reusing `var` for this purpose feels a bit strange, sice it usually marks mutable variables, which have pretty much nothing to do with type inference. I think it would be clearer to just introduce a new keyword:

```zig
fn triple(x: infer) @TypeOf(x) {
    return 3 * x;
}
```

**Comment by Vexu** [comment]
There is already an accepted proposal to rename it to `anytype` #4820.

**Comment by zzyxyzz** [comment]
Ooops.
