### ISSUE TITLE
Minimum GCC compiler version has increased

### ISSUE THREAD

**Issue by squeek502** [ziglang/zig#5362]
Since https://github.com/ziglang/zig/commit/212e2354b8ab631995b0c25f7cf1d9a3e01fac57, the minimum compiler version in the README seems to no longer be accurate:

> gcc >= 5.0.0

Using GCC 5.4.0 I get:

```
error: -Werror=implicit-fallthrough: no option -Wimplicit-fallthrough
```

If I remove `-Werror=implicit-fallthrough` from CMakeLists.txt I get this error instead:

```
In file included from /home/ryan/Programming/zig/zig/src/util.hpp:21:0,
                 from /home/ryan/Programming/zig/zig/src/list.hpp:11,
                 from /home/ryan/Programming/zig/zig/src/all_types.hpp:11,
                 from /home/ryan/Programming/zig/zig/src/analyze.hpp:11,
                 from /home/ryan/Programming/zig/zig/src/codegen.cpp:8:
/home/ryan/Programming/zig/zig/src/codegen.cpp: In function ‘void render_async_var_decls(CodeGen*, Scope*)’:
/home/ryan/Programming/zig/zig/src/util_base.hpp:72:25: error: expected primary-expression before ‘__attribute__’
 #define ZIG_FALLTHROUGH __attribute__((fallthrough))
                         ^
/home/ryan/Programming/zig/zig/src/codegen.cpp:4055:13: note: in expansion of macro ‘ZIG_FALLTHROUGH’
             ZIG_FALLTHROUGH;
             ^
CMakeFiles/zigcompiler.dir/build.make:140: recipe for target 'CMakeFiles/zigcompiler.dir/src/codegen.cpp.o' failed
```

`fallthrough`-related stuff seems to have been added in GCC 7 as far as I can tell.

**Comment by andrewrk** [comment]
Thanks for noticing this. This is a bug; it is still intended for stage1 to be compatible with this GCC version, since the whole point of stage1 is to get from C to zig. The more c compilers stage1 can be compatible with, the better.

**Comment by pixelherodev** [comment]
I'll tackle this; seems simple enough.

**Comment by pixelherodev** [comment]
... just need to get GCC 5 running locally first :P

**Comment by pixelherodev** [comment]
That was faster than expected; okays, going to work on this now.

**Comment by pixelherodev** [comment]
@squeek502 Would you mind testing with the PR I linked? I'm fairly certain it's good, but fully testing it would require rebuilding LLVM and Clang with GCC 5, and I figure it'd be easier for you to test that than for me to spend ten hours trying to build the full LLVM + Clang locally for the umpteenth time.

If you'd rather not, I can fully test it, but it'll take a bit longer.

**Comment by squeek502** [comment]
#5365 does fix this, but see https://github.com/ziglang/zig/pull/5365/files#r426301365. Will submit a PR for that in a bit.

**Comment by pixelherodev** [comment]
Ahh, good catch.

**Comment by thoughton** [comment]
It seems the Linuxbrew distribution of Zig is encountering this same issue.
