### ISSUE TITLE
support dynamic linking musl libc

### ISSUE THREAD

**Issue by necessarily-equal** [ziglang/zig#5364]
downstream bug report https://gitlab.alpinelinux.org/alpine/aports/-/issues/11399. 

Programs built by zig can't initialize video output (audio is fine, though): `SDL_Init(SDL_INIT_VIDEO)` fails.

I wrote a minimal C program to test this further, but I originally noticed the issue when compiling zig code.

to test this, I used the following:

* [sdl.c](https://paste.gnugen.ch/raw/lGsN)
* [zig-logo.bmp](https://paste.gnugen.ch/raw/CXAB) (I'm not using attachments because github refuses bmp images)
* Install zig, sdl2+headers, sdl_image+headers, gcc and clang. (`apk add -t .zig zig sdl2 sdl2-dev sdl2_image-dev build-base clang` on Alpine)

(using the SDL_image pkg-config to ensure correctness)

```sh
> zig cc sdl.c $(pkg-config SDL2_image --cflags --libs) && ./a.out
Could not initialize SDL. SDL_Error: No available video device
```

Yet the C code is functional:
```sh
> gcc sdl.c $(pkg-config SDL2_image --cflags --libs) && ./a.out
# works
```

and clang (LLVM) also works:
```sh
> clang sdl.c $(pkg-config SDL2_image --cflags --libs) && ./a.out
# works
```

The cause seems to reside at link time:
```sh
> zig cc sdl.c $(pkg-config SDL2_image --cflags)
> gcc sdl.o $(pkg-config SDL2_image --libs)
> ./a.out
# works
```

The issue was tested with Zig 0.6, and was already present with Zig 0.5. The same code works with Zig on Debian.

I don't know how to debug this further, but feel free to ask any question.

**Comment by necessarily-equal** [comment]
Using the static version of the SDL also doesn't work, unfortunately

**Comment by andrewrk** [comment]
I think it is fair to also call this a bug because it makes zig unusable on musl-based linux distros for applications that require dynamic linking.

**Comment by alexrp** [comment]
@ifreund from what I can gather, #7406 only allows dynamically linking musl when doing native builds, right? Is there a way to extend this support for cross scenarios? (I'm not overly familiar with how musl distros work - I just happened to notice that cross-compiling an `x86_64-linux-musl` executable always results in musl being statically linked.)

**Comment by andrewrk** [comment]
Static is the default; you need to add the `-dynamic` flag.

**Comment by alexrp** [comment]
Ah, the issue was that I tried `-lc` and `-dynamic` separately, not together. Combining them did the trick, thanks!

**Comment by alexrp** [comment]
Is there a way to achieve the same with `zig cc`?

```console
$ zig cc main.c -target x86_64-linux-musl -fPIE -lc
$ wsl musl-ldd a.out
        musl-ldd (0x7f5ffe36e000)
```
