### ISSUE TITLE
question: why there is no difference between variable declaration and a type declaration

### ISSUE THREAD

**Issue by kolokd** [ziglang/zig#5373]
there should be a `type` keyword for declaring a type like Go.

Aslo why includes also done in nodejs style? 
instead of a `include` or `import` keyword.
I think using less keywords doesn't make the language simpler.

thanks.
please answer the questions here.

**Comment by pixelherodev** [comment]
There is a value `type`, which is of type `type`. You can in fact use it to declare types:

```zig
const a: type = struct {
    field: fieldType
};
```

However, the type of a structure is always, definitionally, `type`, so there's no need to explicitly specify it.

> Aslo why includes also done in nodejs style?

[CITATION NEEDED].

There is, in fact, an `import` buildin, which is used to import other packages and other files within a package.

```zig
const std = @import("std");
const warn = std.debug.warn;

pub fn main() void {
    warn("Hello, world!\n", .{});
}
```

**Comment by SpexGuy** [comment]
Hi @kolokd , thanks for your interest in Zig!  For questions like this, you should visit the zig Discord or IRC channel: https://github.com/ziglang/zig/wiki/Community

But to answer them,
> why there is no difference between variable declaration and a type declaration

At compile time, Zig is a dynamic language like Javascript or Python.  Types are values and can be manipulated, created, passed as parameters, compared, and many more things.  Zig's type declaration highlights this feature by making all types anonymous, and assigning them to a variable which will be used to reference them.

> Also why includes also done in nodejs style?

This is for the same reason.  A module in Zig is a type at the top level, and you must store it into a named variable when the compiler executes the include.  Using `@import(x)` makes it clear that `x` is an expression context, where you could put a comptime-known variable or even a function call.  For example, `const backend = @import(select_backend_module_based_on_target_platform())` is perfectly valid in Zig.  If `import` were a keyword it would be much less clear that the text that follows it can be an expression.

**Comment by pixelherodev** [comment]
> A module in Zig is a type at the top level
Ohhh!

I completely forgot how NodeJS imports worked :facepalm:

**Comment by kolokd** [comment]
Thanks to all of you.

**Comment by kolokd** [comment]
@SpexGuy Please don't use discord.
Use an open source and free software licensed program.
