### ISSUE TITLE
Basic struct initialization with default values gives compiler error

### ISSUE THREAD

**Issue by jeffkdev** [ziglang/zig#5398]
```zig
pub const Mesh = struct {
    id: u32,
};

pub const Material = struct {
    transparent: bool = true,
    emits_shadows: bool = true,
    render_color: bool = true,
};
pub const Renderable = struct {
    mesh: Mesh,
    material: Material,
};

var renderable: Renderable = undefined;

pub fn main() void {
    renderable = Renderable{
        .mesh = Mesh{ .id = 0 },
        .material = Material{ .transparent = false, .emits_shadows = false },
    };
}
```
```The following command exited with error code 5...```
This works on 0.6.0 release but fails in master (reproducible in https://zig.godbolt.org). Started failing a few weeks ago, but took awhile to create a minimal example. Not sure what is special about this particular struct setup.

Edit: 0.7.0 introduced opaque keyword... changing example code to use 'transparent' for Material field

**Comment by JesseRMeyer** [comment]
As a clue, the code compiles on truck if the global declaration of renderable is commented out, and its assignment in main becomes the declaration site.

**Comment by jeffkdev** [comment]
Yeah, at first I noticed that too, but not sure how related it is related to the root cause. Changing any one of the following will let it compile:
1. Removing any field in Material (opaque, emits_shadows, or render_color)
2. Removing any field in Renderable (mesh, material)
3. Making renderable a local declaration
4. Changing a field type in Material (ex: Make render_color an i32 instead of a bool and then it is fine)
