### ISSUE TITLE
Error running tests possibly due to a `union(enum)`

### ISSUE THREAD

**Issue by prime31** [ziglang/zig#5400]
The error I get is:

```TODO buf_read_value_bytes union type
Unable to dump stack trace: debug info stripped
```

I am not 100% sure, but I believe this is due to having this code present:

```
    const DebugDrawCommand = union(enum) {
        point: Point,
        line: Line,
        rect: Rect,
        circle: Circle,
        text: Text,
    };
```

I also get the error when running tests that contain this code:

```
pub const Color = extern union {
    value: u32,
    comps: packed struct {
        r: u8,
        g: u8,
        b: u8,
        a: u8,
    }
}
```

**Comment by joachimschmidt557** [comment]
Could you maybe provide a code snippet which reproduces the error?

**Comment by prime31** [comment]
I'm having a difficult time narrowing this down to a simple repro. My project is pretty large and I can't seem to figure out what combination of factors with the unions above gets things to fail. When I exclude the tests that import the files with the unions above the tests run fine.

I'll keep trying to get a simple repro...

**Comment by Vexu** [comment]
There is still no way to reproduce this issue. If you do find a way, feel free to comment it here to get this reopened.

**Comment by prime31** [comment]
Would it be helpful to have the full project that repros this? I havent been able to narrow down exactly what causes it but I can repro it 100% of the time with my project.

**Comment by Vexu** [comment]
It would be more helpful than nothing and make it possible for someone else to try to find a simple repro.

**Comment by prime31** [comment]
[Zig-Aya.zip](https://github.com/ziglang/zig/files/4860167/Zig-Aya.zip)

Apologies for the project size. Tests can be run the usual way with `zig build test`. If you open the `tests.zig` file and uncomment any of the commented out imports it will trigger the bug when running the tests.

tests.zig file:
```comptime {
    _ = @import("src/fs.zig");
    // _ = @import("src/input.zig"); // Zig bug: TODO buf_read_value_bytes union type

    _ = @import("src/mem/sdl_allocator.zig");
    _ = @import("src/mem/scratch_allocator.zig");
    _ = @import("src/mem/sdl_stream.zig");

    _ = @import("src/math/math.zig");
    _ = @import("src/math/vec2.zig");
    // _ = @import("src/math/color.zig"); // Zig bug: TODO buf_read_value_bytes union type
    // _ = @import("src/math/mat32.zig");

    // _ = @import("src/gfx/textures.zig"); // requires firing up a Window and sets up a Device in its test
    // _ = @import("src/gfx/gfx.zig"); // Zig bug: anything that imports aya fails due to debug.zig
    // _ = @import("src/gfx/shader.zig");
    // _ = @import("src/gfx/buffers.zig");
    // _ = @import("src/gfx/mesh.zig");
    // _ = @import("src/gfx/batcher.zig");
    // _ = @import("src/gfx/triangle_batcher.zig");
    // _ = @import("src/gfx/atlas_batch.zig");
    // _ = @import("src/gfx/offscreen_pass.zig"); // Zig bug: TODO buf_read_value_bytes union type

    // _ = @import("src/utils/utils.zig");
}```

**Comment by Vexu** [comment]
Are you talking about the `TODO buf_read_value_bytes union type` error? That is caused by the `@bitCast`s in `src/math/color.zig`, I was able to avoid the crash by changing the test:
```zig
test "test color" {
    const ColorConverter = extern struct {
        r: u8, g: u8, b: u8, a: u8
    };

    const c = Color{ .value = @as(u32, 0xFF9900FF) };
    const cc = Color{ .value = @bitCast(u32, [4]u8{ 10, 45, 34, 255 }) };
    const ccc = Color{ .value = @bitCast(u32, ColorConverter{ .r = 10, .g = 45, .b = 34, .a = 255 }) };
    std.testing.expectEqual(cc.value, ccc.value);

    const c2 = Color.fromBytes(10, 45, 34, 255);
    const c3 = Color.fromRgb(0.2, 0.4, 0.3);
    const c4 = Color.fromRgba(0.2, 0.4, 0.3, 1.0);
    std.testing.expectEqual(c3.value, c4.value);

    var c5 = Color.fromI32(10, 45, 34, 255);
    std.testing.expectEqual(c5.r_val(), 10);
    std.testing.expectEqual(c5.g_val(), 45);
    std.testing.expectEqual(c5.b_val(), 34);
    std.testing.expectEqual(c5.a_val(), 255);

    c5.set_r(100);
    std.testing.expectEqual(c5.r_val(), 100);

    const scaled = c5.scale(2);
    std.testing.expectEqual(scaled.r_val(), 200);
}
```

Related/Duplicate #5193.

**Comment by prime31** [comment]
That change does seem to get by the error for that test. I ran into a different (unrelated) bug when checking the rest of the tests where it seems adding packages to a test executable doesn't allow them to be imported with `@import("name")` so I can't check the rests of the places where the error popped up. I imagine it was similar bitCasts though so we'll call this closed. Thanks!
