### ISSUE TITLE
Tab character caused compile error

### ISSUE THREAD

**Issue by dangerousHobo** [ziglang/zig#5406]
Hello, I've downloaded the latest master build and tried running the hello world example. I used tabs as indention and this caused the following compile error:

```
❯ zig build-exe hw.zig
Semantic Analysis..../hw.zig:4:1: error: invalid character: '\t'
        const stdout = std.io.getStdOut().outStream();
^

```
```
❯ cat hw.zig
const std = @import("std");

pub fn main() !void {
        const stdout = std.io.getStdOut().outStream();
        try stdout.print("Hello, {}!\n", .{"world"});
}

```
```
❯ zig version
0.6.0+70239802c
```

Is this expected? Are only spaces allowed for indention?

**Comment by andrewrk** [comment]
https://github.com/ziglang/zig/wiki/FAQ#why-does-zig-force-me-to-use-spaces-instead-of-tabs
