### ISSUE TITLE
use case: make a tiny 32bit exe on windows

### ISSUE THREAD

**Issue by pluto439** [ziglang/zig#541]
This `_.zig` file:

```
use @import("std").os.windows;

export fn WinMainCRTStartup() {
    _ = MessageBoxA(null, c"hello", c"title", 0);
}
```

with this command line:

```
zig build-exe _.zig --target-os windows --target-arch i386 --target-environ gnu --release-fast -mwindows
```

produces this code:

http://ibb.co/j4Bso6

Everything after `ret` is a trash, I don't know what it's for.

Optionally, change image base address to 0x400000, make ".text" section the first section in exe.

**Comment by pluto439** [comment]
Found how to set base address in lld

https://reviews.llvm.org/D22116

`def image_base : J<"image-base=">, HelpText<"Set the base address">;`

**Comment by pluto439** [comment]
deleted everything in lib/zig/std/special/builtin.zig

It's now 4 kb instead of 6, but there is still some trash inside the `.text` section. Why is code called `.text`, this is so weird.

**Comment by pluto439** [comment]
Tried to run zig verbosely

```
zig build-exe _.zig --target-os windows --target-arch i386 --target-environ gnu --release-fast -mwindows --verbose --verbose-link --verbose-ir >verbose.txt 2>&1
```

It crashed midway, and last lines of verbose.txt are this:

```
{ // (analyzed)
Entry_0:
    #4  | noreturn    | - | return 128
}
{ // (analyzed)
Entry_0:
    #6  | noreturn    | - | return 15
}
{ // (analyzed)
Entry_0:
    #10 | noreturn    | - | return TODO bigint rem with >1 digits
```

Last `Original Source` is `lib\zig\std\special\compiler_rt\aullrem.zig`. It looks like it compiles everything when verbose.

**Comment by pluto439** [comment]
Making this properly would require adding extra compile-time variables: `need_chkstk`, `need_libc`, `need_manifest`, `need_exceptions`, `need_thread_local_storage`, `need_panic`, maybe something else. Ideally compiler should be smart enough to determine it by itself, without me passing any parameters in command line. Compiler should gather this info while compiling program, and then compile runtime using this info.

Making a language for pretty hello worlds. This is actually pretty important, because I can't find anything in my exe file overwise. I can't tell if zig generates good code or not.

**Comment by andrewrk** [comment]
We don't have exceptions. We don't have thread local storage (yet). We don't link libc unless you pass `--library c`. chkstk is solved with #54. panic gets compiled out in `--release-fast` mode if you don't use it. I don't know what a manifest is, but I don't think we're doing one.

**Comment by pluto439** [comment]
`--image-base` didn't work for me, but `lj.args.append("-dynamicbase:no");` did. Added it in src/link.cpp, right after `lj.args.append("lld");`

Address space layout randomization is a new thing in windows vista, it's supposed to make apps a tiny bit more secure, somehow. But it actually only makes me scroll down a little bit further in debugger, so I disabled it for now.

Now exe always loads on 400000.

**Comment by pluto439** [comment]
I think I found how to rearrange sections, not sure exactly how to do it in C++ though. Here is a patch for it, I have trouble with compiling it.

[rearrange.zip](https://github.com/zig-lang/zig/files/1430543/rearrange.zip)

[rearrange.patch.txt](https://github.com/zig-lang/zig/files/1430550/rearrange.patch.txt)

**Comment by pluto439** [comment]
Need to get rid of WinMainCRTStartup, MainCRTStartup and WinMain, just leave main. Have versions of main without arguments, and with array of strings as an argument, and make sure proper runtime code is choosen for each.

Also please set -mwindows a default one. The difference between -mwindows and -mconsole is that -mconsole also opens a black console window when launched from file manager. The -mwindows still outputs just fine if started from console, and this is the only way people usually want to use those kind of programs. The -mconsole programs close too fast to actually read anything, unless you wait for input, which rarely anybody does.

Blender used to have black console window open at all times, and it was quite annoying. Now it smarted up and only shows it on demand, now there is an option to show or hide console in the gui. It is a -mconsole app, I guess it hides console window at startup.

**Comment by andrewrk** [comment]
I think this is a good idea, let me play around with it and implement it.

**Comment by andrewrk** [comment]
Given that hello world with `--release-small --strip --single-threaded -target x86_64-windows` is 2.5KB, I think this can be closed.
