### ISSUE TITLE
No compile error for missing error set member

### ISSUE THREAD

**Issue by ifreund** [ziglang/zig#5410]
This code compiles when it shouldn't
```zig
const std = @import("std");

const Error = error{InvalidCharacter};

const Direction = enum { upside_down };

const Barrrr = union(enum) {
    float: f64,
    direction: Direction,
};

fn fooey(bar: @TagType(Barrrr), args: []const []const u8) !Barrrr {
    return switch (bar) {
        .float => .{ .float = try std.fmt.parseFloat(f64, args[0]) },
        .direction => if (std.mem.eql(u8, args[0], "upside_down"))
            Barrrr{ .direction = .upside_down }
        else
            error.InvalidDirection,
        else => unreachable,
    };
}

pub fn main() Error!void {
    std.debug.warn("{}", .{try fooey(.direction, &[_][]const u8{ "one", "two", "three" })});
}
```

Note that if the signature of `fooey` is changed to
```zig
fn fooey(bar: @TagType(Barrrr), args: []const []const u8) Error!Barrrr {
```
the code will fail to compile with the error
```
./src/main.zig:18:18: error: expected type 'Error', found 'error{InvalidDirection}'
            error.InvalidDirection,
                 ^
./src/main.zig:18:18: note: 'error.InvalidDirection' not a member of destination error set
            error.InvalidDirection,
                 ^
```

**Comment by dbandstra** [comment]
Was there a copy paste error here? You said "Note that if the signature of fooey is changed" but it's the same line as in your code snippet

**Comment by ifreund** [comment]
Indeed there was, thanks for catching that. The modified signature I intended to put is
```zig
fn fooey(bar: @TagType(Barrrr), args: []const []const u8) Error!Barrrr {
```

**Comment by pixelherodev** [comment]
Maybe edit the original to make it clear to new viewers?

**Comment by squeek502** [comment]
For anyone like me that missed the problem with the first example, the error is meant to come from the explicit error set of `main`:

```zig
pub fn main() Error!void {
```

**Comment by pixelherodev** [comment]
Ahh, I see now. It's compiling despite the fact that it's returning errors outside the valid error set.

**Comment by ifreund** [comment]
> Ahh, I see now. It's compiling despite the fact that it's returning errors outside the valid error set.

Yes exactly. I realize now that I could have been much more clear rather than just pasting the code like that.
