### ISSUE TITLE
conflicting definitions in headers preventing compilation on arm (32)

### ISSUE THREAD

**Issue by ityonemo** [ziglang/zig#5418]
`libc/glibc/sysdeps/arm/nptl/bits/pthreadtypes-arch.h`
and
`libc/include/arm-linux-gnueabihf/bits/struct_rwlock.h`

both define `struct __pthread_rwlock_arch_t` which conflicts when trying to cross-compile arm (32) code using `-target arm-linux.4.19-gnueabihf` with `-lc`.  Trivially solvable by surrounding with `#ifndef`/`#define`/`#endif` blocks.  Not sure if this is a zig problem or an llvm problem, but doing cross-compilation with zig exposes this issue.

**Comment by alexrp** [comment]
This should be fixed now.
