### ISSUE TITLE
RFC: Align Primitive Type Names with Case Convention

### ISSUE THREAD

**Issue by EleanorNB** [ziglang/zig#5419]
Zig case convention for types is `TitleCase`. However, primitive types do not follow this convention. This is an inconsistency that could be worth fixing.
`u32` -> `U32`
`isize` -> `ISize`
`bool` -> `Bool`
`type` -> `Type`
`anytype` -> `AnyType` (or `Any`, or `Var`)
`void` -> `Void` (or `None`)
`noreturn` -> `NoReturn` (or `Never`)

**Comment by pixelherodev** [comment]
The docs also say:

```
These are general rules of thumb; if it makes sense to do something different, do what makes sense. For example, if there is an established convention such as ENOENT, follow the established convention.
```

The de facto convention in every systems language (C, C++, Rust, Go, etc) is to have lowercase primitive names.

**Comment by EleanorNB** [comment]
The convention in those languages is also to special-case function declaration, and yet #1717 is accepted.

**Comment by pixelherodev** [comment]
Yes, but this is specifically for _styling_, not _syntax_. #1717 involves _syntax_, this proposal is to change _styling_.

**Comment by CurtisFenner** [comment]
Go, C, and C++ don't have a convention to capitalize types at all, so I'm not sure pointing to them makes the strongest case on this issue. (Zig exists to improve upon C/C++)

Is there a discussion somewhere that explains why Rust chose to not capitalize the "primitive" types that could be reflected on? For what it's worth, with my limited understanding of Rust there are still some types which aren't primitives but which are at least partially special-cased by the compiler, they aren't given the `lowercaseprimitive` treatment. So it doesn't seem as simple as "compiler provided logic --> should be lowercase, like keywords".

**Comment by EleanorNB** [comment]
Okay, C's have been R'd, this is not a popular idea. It's a bikeshed anyway. Time to kill it.
