### ISSUE TITLE
design flaw: SIMD vectors are indexable in an inconsistent way

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#5427]
SIMD: #903 

Thanks @daurnimator for pointing this out in https://github.com/ziglang/zig/pull/5425#issuecomment-633329350.

Currently, vectors are indexable:

https://github.com/ziglang/zig/blob/4b1a8464715a9b2af1d9024694282883f3346482/test/stage1/behavior/vector.zig#L166-L239

Using an index accesses the vector elements. However, this conflicts with the plan to have vectors of single-item pointers to structs. Already it is strange, because if you can index something then you would expect the `len` property to work. But vectors do not support this because if there is a vector of single-item pointers to structs, then one of the fields could be `len`.

But vectors could also be vectors of single-item pointers to arrays! In this case, in the same way that field access would work for the vector of struct pointers, indexing the vector should work on the inner array pointers.

Related: #5425 this would need to get reworked to check the element type

**Comment by data-man** [comment]
@andrewrk 
> Related: #5425 this would need to get reworked to check the element type

What's wrong?
```zig
const std = @import("std");
const meta = std.meta;
const warn = std.debug.warn;
const isIndexable = meta.trait.isIndexable;

pub fn main() void {
    const int32: i32 = 0;
    const array = [_]u8{0} ** 10;
    const vector: meta.Vector(2, u32) = [_]u32{0} ** 2;

    warn("isIndexable(int32): {}\n", .{isIndexable(@TypeOf(int32))});
    warn("isIndexable(&int32): {}\n", .{isIndexable(@TypeOf(&int32))});
    warn("isIndexable(array): {}\n", .{isIndexable(@TypeOf(array))});
    warn("isIndexable(&array): {}\n", .{isIndexable(@TypeOf(&array))});
    warn("isIndexable(vector): {}\n", .{isIndexable(@TypeOf(vector))});
    warn("isIndexable(&vector): {}\n", .{isIndexable(@TypeOf(&vector))});

    warn("@typeInfo(&vector): {}\n", .{@typeInfo(@TypeOf(&vector))});
}
```
Outputs:
```
isIndexable(int32): false
isIndexable(&int32): false
isIndexable(array): true
isIndexable(&array): true
isIndexable(vector): true
isIndexable(&vector): false
@typeInfo(&vector): TypeInfo{ .Pointer = Pointer{ .size = Size.One, .is_const = true, .is_volatile = false, .alignment = 8, .child = type, .is_allowzero = false, .sentinel = null } }
```

**Comment by andrewrk** [comment]
@data-man with the way the language works right now, there is nothing wrong with #5425, it is correct. However the language itself has an inconsistency in it

**Comment by shawnl** [comment]
Have you actually ever done serious SIMD programming? This same discussion has happened over and over again for months, and I have answered it a number of times: if the index is scalar it addresses the element numbers. The extension is that if it is a vector, then it does a `@shuffle()`. Pointer arithmetic can be done with `+` and `-` instead of `[]`, and slicing a vector makes no sense.

Both gcc and clang work this way.

Unrelated, the big thing that caused me to drop my patch series on the floor was a technical mistake that means zig can't match gcc's feature set: runtime vector indexes. (that doesn't mean I understand how to use ResultLoc, which was the reason I couldn't get my code working doing it the way gcc does it).

```
    // If the instruction is a element pointer instruction to a vector, we emit
    // vector element extract instruction rather than load pointer. If the
    // pointer type has non-VECTOR_INDEX_RUNTIME value, it would have been
    // possible to implement this in the codegen for IrInstGenLoadPtr.
    // However if it has VECTOR_INDEX_RUNTIME then we must emit a compile error
    // if the vector index cannot be determined right here, right now, because
    // the type information does not contain enough information to actually
    // perform a dereference.
    if (ptr_type->data.pointer.vector_index == VECTOR_INDEX_RUNTIME) {
        if (ptr->id == IrInstGenIdElemPtr) {
            IrInstGenElemPtr *elem_ptr = (IrInstGenElemPtr *)ptr;
            IrInstGen *vector_loaded = ir_get_deref(ira, &elem_ptr->array_ptr->base,
                    elem_ptr->array_ptr, nullptr);
            IrInstGen *elem_index = elem_ptr->elem_index;
            return ir_build_vector_extract_elem(ira, source_instruction, vector_loaded, elem_index);
        }
        ir_add_error(ira, &ptr->base,
            buf_sprintf("unable to determine vector element index of type '%s'", buf_ptr(&ptr_type->name)));
        return ira->codegen->invalid_inst_gen;
    }

```

**Comment by andrewrk** [comment]
> This same discussion has happened over and over again for months, and I have answered it a number of times: if the index is scalar it addresses the element numbers.

You are absolutely correct. I apologize for forgetting this again. 

>  @andrewrk couldn't change his mind about an incorrect technical decision. (which was made while I was trying to tell him it was incorrect)

What are you referring to?

**Comment by shawnl** [comment]
I am sorry if that came across as an ad homonim.

**Comment by daurnimator** [comment]
I'm confused about why this was closed; the inconsistency still exists.

**Comment by andrewrk** [comment]
As @shawnl noted, if the index is scalar then it indexes elements. If the index is a vector, then it can perform array element access or struct field access.
