### ISSUE TITLE
Bug: GDB uses wrong values for Zig enums within structures

### ISSUE THREAD

**Issue by pixelherodev** [ziglang/zig#5432]
I first noticed this months ago, but didn't care enough to report it, as I figured someone else would notice and it'd be fixed eventually. Now, I'm a lot more involved with the compiler, and this has caused issues while debugging stage2 itself, which in my opinion severely raises its severity.

```gdb
(gdb) print *(unsigned char*)(&old_inst.tag + 1)
$36 = 2 '\002'
(gdb) print *(unsigned char*)(&old_inst.tag)
$37 = 170 '\252'
(gdb) print (unsigned char)old_inst.tag
$38 = 0 '\000'
``` 

old_inst in this example refers to `@notafunc` from `%0 = call(@notafunc, []` ZIR. From the sources:
```zig
     /// These names are used directly as the instruction names in the text format.
     pub const Tag = enum {
         breakpoint,
         call,
         /// Represents a reference to a global decl by name.
         /// The syntax `@foo` is equivalent to `declref("foo")`.
         declref,
```

Thus, the enumeration value of `old_inst.tag` should be, as an integer, two (as integer representation is still used on ordinal-less enumerations). However, when printed in GDB, it's printed as zero. If the cast is removed, the issue remains:
```gdb
(gdb) print old_inst.tag
$39 = breakpoint
```

It gets printed as a *breakpoint*, which is inaccurate. Worse, if you take the address directly and read its value, you get 0xAA - which, since this is running in debug mode, and all nearby values also contain 0xAA, is almost certainly an `undefined` indicator.

The following heavily indicates to me that this is a GDB bug and not a Zig bug:

```gdb
(gdb) print *(unsigned char*)(&old_inst.tag)
$37 = 170 '\252'
(gdb) print (unsigned char)old_inst.tag
$38 = 0 '\000'
``` 

However, I do not have conclusive evidence, so I'm unsure if this is a bug in GDB, Zig/Stage1, or LLVM.

The title is narrow (Zig enums within structures), because I don't know if this applies to enums outside of structures, or `extern enums`, etc.

Looking back at
```gdb
(gdb) print *(unsigned char*)(&old_inst.tag + 1)
$36 = 2 '\002'
(gdb) print *(unsigned char*)(&old_inst.tag)
$37 = 170 '\252'
```

I strongly suspect that somewhere in the pipeline the debug information is getting slightly off, so the address is incorrect. It's entirely possible this is two separate bugs, one of which is a latent GDB bug which has never mattered and so never been detected, and the other is a stage1 or LLVM bug which gives debug info, thus exposing the GDB bug.

**Comment by pixelherodev** [comment]
A workaround:
```gdb
(gdb) display *(&old_inst.tag + 1)
3: *(&old_inst.tag + 1) = declref
```

**Comment by layneson** [comment]
It seems that this behavior does not occur if the enum's underlying type has a power-of-two bitwidth. Otherwise, Zig treats the enum as a bitfield within the DWARF info, which I suspect is causing the issue at some point or another. Interestingly enough, LLDB doesn't appear to suffer from this same issue.
