### ISSUE TITLE
Proposal: Introduce an 'ignore' keyword.

### ISSUE THREAD

**Issue by jampen** [ziglang/zig#5433]
Commonly in Zig, we call a function that does something, yet we dont need its result.
Example:
` _ = try file.readAll(outputContents.items);`
It would be much nicer and more intent-expressive if it were changed to 
`ignore try file.readAll(outputContents.items);`

**Comment by MasterQ32** [comment]
Ignoring a return value isn't happening that often and spotting `_ =` is as easily recognizable as `ignore`.
I don't think there's benefit from that to the language, especially as `_` isn't a *ignore*, but a *discard*:

Compare:
```zig
const Something = …;
_ = Something; // brings Something into existance, it isn't ignored anymore by the compiler
```

```zig
const Something = …;
ignore Something; // brings Something into existance, it isn't ignored anymore by the compiler
```
The message `ignore Something` is just wrong in this example.
