### ISSUE TITLE
Custom build.zig step no longer works

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#5450]
https://github.com/markfirmware/zig-vector-table/blob/239aefc4032b5ffaf689b39ac94d7aabd5938e57/build.zig#L304-L309

#5051 #4609 

    zig version 0.6.0+dd62f63c0
    ./build.zig:307:34: error: expected type 'std.build.Id', found '*const [19:0]u8'
    allocated.*.step = Step.init(@typeName(@TypeOf(customStep)), self.allocator, @TypeOf(customStep).make);
                                 ^
    ./build.zig:10:48: note: called from here
     const generate_linker_files = addCustomStep(b, GenerateLinkerFiles{});
                                               ^
    ./build.zig:1:43: note: called from here
    pub fn build(b: *std.build.Builder) !void {
                                              ^
    ./zig/lib/zig/std/build.zig:2430:20: note: std.build.Id declared here
    pub const Id = enum {
                   ^
    ./build.zig:307:34: error: expected type 'std.build.Id', found '*const [11:0]u8'
    allocated.*.step = Step.init(@typeName(@TypeOf(customStep)), self.allocator, @TypeOf(customStep).make);
                                 ^
    ./build.zig:12:40: note: called from here
    const make_hex_file = addCustomStep(b, MakeHexStep{ .input_name = "zig-cache/bin/main.img", .output_name = "main.hex" });
                                           ^
    ./build.zig:1:43: note: called from here
    pub fn build(b: *std.build.Builder) !void {
                                              ^
    ./zig/lib/zig/std/build.zig:2430:20: note: std.build.Id declared here
        pub const Id = enum {
                       ^

**Comment by alexnask** [comment]
@markfirmware  

You need to add `.Custom` as a first parameter to `Step.init`, this was added recently as there was no way for a build runner to differentiate between step types.

**Comment by markfirmware** [comment]
Thank you!
