### ISSUE TITLE
Provide -fno-unwind-tables

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#5464]
This will suppress the production of .ARM.exidx sections which are only used for C++ exception unwinding. This will permit the elimination of https://github.com/markfirmware/zig-vector-table/blob/4bdefb2abc10b26dcc34a002c67bbb8124abd070/generated/generated_linker_files/generated_linker_script.ld#L3-L7

**Comment by pixelherodev** [comment]
This shouldn't really be a flag, should it? It should just be default behavior.

We just need to tell LLVM not to generate information that we don't need.

**Comment by andrewrk** [comment]
Does this correspond to an LLD linker flag?

**Comment by pixelherodev** [comment]
Not that I can see. `ld.lld | grep excep` gives no results, and quickly glancing through doesn't show anything either.

**Comment by pixelherodev** [comment]
This isn't a C++ exceptions section. That's _one_ thing it's used for, but it's also used for stack unwinding. Removing that section would interfere with the normal stack backtracing.

I suspect if you disable the default panic handler, the section will vanish.

**Comment by daurnimator** [comment]
I think `-fno-unwind-tables` is the flag you want rather than `-fno-exceptions`?

**Comment by pixelherodev** [comment]
I believe daurminator is correct, and we would need an equivalent to `-fno-unwind-tables`. I think we need to expose the presence of this flag to the code at comptime, so the stack tracing code can `@compileError` if you attempt to use it with the flag enabled.

The important thing to note is that this _isn't_ just flipping a flag in the linker; the _compiler_ needs to avoid emitting it, as I understand it.

**Comment by andrewrk** [comment]
@pixelherodev I think you may be misinformed about how it works - Zig does not have exceptions and its debug info code does not depend on this.

If it's clang compiling C++ code, that can be disabled by passing `-fno-exceptions` to the c++ source files. The only question is whether or not zig needs to pass any flags to LLD.

**Comment by pixelherodev** [comment]
@andrewrk This isn't about exceptions though.

Despite the section name, it's used for stack tracing in _any_ language - backtracing in C code requires it, for instance.

**Comment by pixelherodev** [comment]
and, from looking at the linked repo's build.zig file, only Zig sources are used.

**Comment by markfirmware** [comment]
The use case is for pure zig on bare metal. Either or both of -fno-exceptions and -fno-unwind-tables need to be given to the compiler. I don’t know what should be done if the zig ever links to c or c++.

**Comment by pixelherodev** [comment]
@andrewrk Can you verify the `Zig's debug info doesn't rely on this section` bit? As I understand it, that section is generated by platform-specific LLVM intrinsics (that is, the `the section is only used for C++ exception unwinding` bit is false, and the section _is_ required by Zig's debug code).

**Comment by markfirmware** [comment]
For the time being, I am generating a note in the linker script referring to this issue:

    # generated/generated_linker_files/generated_linker_script.ld - do not edit - generated by build.zig

    MEMORY {
        flash : ORIGIN = 0x0, LENGTH = 0x40000
    }

    SECTIONS {
        .system_exceptions_vector_table : {
            KEEP(*(.vector_table*))
        } > flash
        .cpu_instructions : {
            *(.text*)
        } > flash
        .read_only_data_kept_in_flash : {
            *(.rodata*)
        } > flash
    }

    MEMORY {
        ram : ORIGIN = 0x20000000, LENGTH = 0x4000
    }

    SECTIONS {
        .determine_load_start_for_data_loaded_in_flash_that_program_must_copy_to_ram : {
            __data_loaded_in_flash_that_program_must_copy_to_ram_load_start = .;
        } > flash
        .data_loaded_in_flash_that_program_must_copy_to_ram : AT(__data_loaded_in_flash_that_program_must_copy_to_ram_load_start) {
            __data_loaded_in_flash_that_program_must_copy_to_ram_start = .;
            *(.data*)
            __data_loaded_in_flash_that_program_must_copy_to_ram_end = .;
        } > ram
        .data_that_program_must_set_to_zero (NOLOAD) : {
            __data_that_program_must_set_to_zero_start = .;
            *(.bss*)
            __data_that_program_must_set_to_zero_end = .;
        } > ram
    }

    # .ARM.exidx must be discarded until "provide -fno-unwind-tables" is resolved https://github.com/ziglang/zig/issues/5464

    SECTIONS {
        /DISCARD/ : {
            *(.ARM.exidx)
        }
    }

**Comment by andrewrk** [comment]
Done in b6277a4b1c2be27701d594bc1465ac72fc226260.
