### ISSUE TITLE
fmt breaks when multiline strings contain tabs

### ISSUE THREAD

**Issue by clarityflowers** [ziglang/zig#5482]
When a multiline string has a tab literal, `zig fmt` has the following error:
```
src/main.zig:5:32: error: expected ';', found invalid bytes
        \\literal tab here  --> <--
                               ~
```

Seems similar to https://github.com/ziglang/zig/issues/3737. The program compiles and works fine. I'm working with tsv data right now and ran into this when making tests. 

```zig
const expectEqual = @import("std").testing.expectEqual;
  
test "tabs" {
    const test_string =
        \\literal tab here  --> <--
    ;
    expectEqual("literal tab here  -->\t<--", test_string);
}
```

**Comment by squeek502** [comment]
This seems to be fixed on latest master.

**Comment by Vexu** [comment]
This still happens if you comment the multiline string. I think comments should also allow tabs if we allow them in strings.
