### ISSUE TITLE
Anon struct feilds are constant for some reason

### ISSUE THREAD

**Issue by Sobeston** [ziglang/zig#5486]
```zig
var things = .{
    .foo = @as(i8, 1),
};
```
Here, the type of &things.foo is *const i8. I can't think of a reason why this should be the case.

These two work as expected:
```zig
var things = struct {
    foo: i8,
} {
    .foo = 1,
};
```
```zig
var things = struct {
    foo: i8 = 1,
} {};
```

**Comment by pfgithub** [comment]
Using struct initialization syntax does not work with no errors:
```zig
const expectEqual = @import("std").testing.expectEqual;
test "" {
    const TupleType = @TypeOf(.{ @as(u32, 12), @as(u64, 42) });
    var tupleValue = TupleType{ .@"0" = 25, .@"1" = 50 };
    expectEqual(25, tupleValue.@"0"); // expected 25, found 0
    expectEqual(50, tupleValue.@"1"); // expected 50, found 0
}
```

**Comment by pixelherodev** [comment]
This isn't an anon struct, it's a tuple.

**Comment by Vexu** [comment]
Working as expected, comptime known values in tuples become comptime fields.
Initializing with the wrong value is tested at `test/cases/compile_errors/invalid_store_to_comptime_field.zig`.
