### ISSUE TITLE
Compiler build fails on ppc64le

### ISSUE THREAD

**Issue by shawnanastasio** [ziglang/zig#5513]
When compiling zig `14d235dd6e79dba8d34e05f1912a1bcf9a3ef68c` on a ppc64le machine, the following errors are encountered:

```
./lib/std/time.zig:188:24: error: container 'std.os' has no member called 'timespec'
            var res: os.timespec = undefined;
                       ^
./lib/std/fs/file.zig:30:25: error: container 'std.os' has no member called 'ino_t'
    pub const INode = os.ino_t;
                        ^
./lib/std/fs/file.zig:226:16: note: referenced here
        inode: INode,
               ^
./lib/std/fs/file.zig:241:38: note: referenced here
    pub fn stat(self: File) StatError!Stat {
                                     ^
./lib/std/fs/file.zig:204:25: note: referenced here
        return (try self.stat()).size;
                        ^
./lib/std/fs/file.zig:29:24: error: container 'std.os' has no member called 'mode_t'
    pub const Mode = os.mode_t;
                       ^
./lib/std/fs.zig:1548:19: note: referenced here
        mode: File.Mode = File.default_mode,
                  ^
./src-self-hosted/main.zig:718:46: note: referenced here
        const baf = try io.BufferedAtomicFile.create(fmt.gpa, fs.cwd(), real_path, .{});
                                             ^
./lib/std/event/loop.zig:1212:25: error: container 'std.os' has no member called 'mode_t'
                mode: os.mode_t,
                        ^
./lib/std/event/loop.zig:1142:13: note: while checking this field
            open: Open,
            ^
./lib/std/event/loop.zig:1124:9: note: while checking this field
        msg: Msg,
        ^
./lib/std/linked_list.zig:172:13: note: while checking this field
            data: T,
            ^
./lib/std/atomic/queue.zig:12:9: note: while checking this field
        head: ?*Node,
        ^
./lib/std/event/loop.zig:25:5: note: while checking this field
    fs_queue: std.atomic.Queue(Request),
    ^
./lib/std/event/loop.zig:104:25: note: referenced here
    pub const instance: ?*Loop = if (@hasDecl(root, "event_loop")) root.event_loop else default_instance;
                        ^
./lib/std/os.zig:717:41: note: referenced here
            EAGAIN => if (std.event.Loop.instance) |loop| {
                                        ^
./lib/std/fs.zig:709:54: error: container 'std.os' has no member called 'O_CLOEXEC'
        const os_flags = lock_flag | O_LARGEFILE | os.O_CLOEXEC | if (flags.write and flags.read)
                                                     ^
./lib/std/fs.zig:1029:53: error: container 'std.os' has no member called 'O_DIRECTORY'
            return self.openDirFlagsZ(sub_path_c, os.O_DIRECTORY | os.O_RDONLY | os.O_CLOEXEC | O_PATH);
                                                    ^
./lib/std/reset_event.zig:252:26: error: container 'std.os.linux' has no member called 'timespec'
            var ts: linux.timespec = undefined;
                         ^
./lib/std/time.zig:230:19: error: container 'std.os' has no member called 'timespec'
        var ts: os.timespec = undefined;
                  ^
./lib/std/os.zig:1127:74: error: use of undeclared identifier 'mode_t'
pub fn openatZ(dir_fd: fd_t, file_path: [*:0]const u8, flags: u32, mode: mode_t) OpenError!fd_t {
                                                                         ^
./lib/std/fs.zig:1051:15: note: referenced here
            os.openatZ(self.fd, sub_path_c, flags, 0);
              ^
./lib/std/os/linux.zig:138:12: error: use of undeclared identifier 'syscall3'
    return syscall3(
           ^
make[2]: *** [CMakeFiles/zig_build_libstage2.dir/build.make:77: CMakeFiles/zig_build_libstage2] Error 1
make[1]: *** [CMakeFiles/Makefile2:108: CMakeFiles/zig_build_libstage2.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

I assume some architecture-specific bits for ppc64le are missing. If you could point out where support would need to be added, I can try to contribute it.

**Comment by pixelherodev** [comment]
Looking into this in the next five minutes or so (though I obviously can't promise I'll fix it that quickly) :)

**Comment by daurnimator** [comment]
> I assume some architecture-specific bits for ppc64le are missing. If you could point out where support would need to be added, I can try to contribute it.

You'll need to add ppc64le definitions to at least:
  - https://github.com/ziglang/zig/tree/master/lib/std/os/linux
  - https://github.com/ziglang/zig/tree/master/lib/std/os/bits/linux

**Comment by shawnl** [comment]
The C ABI for ppc64le is easier than the other arches, as llvm actually implements some of it for you (I did a zig to ppc64le port a long time ago).

**Comment by shawnanastasio** [comment]
Implemented std.os https://github.com/shawnanastasio/zig/commit/a91058200816db67e980430f5410cb4b622c484b.

Next I'll look into the ABI stuff @shawnl mentioned.

**Comment by daurnimator** [comment]
> Implemented std.os [shawnanastasio@a910582](https://github.com/shawnanastasio/zig/commit/a91058200816db67e980430f5410cb4b622c484b).

How did you come to those definitions? (and please do open a PR; just click "draft" if its not ready yet)

**Comment by shawnanastasio** [comment]
> How did you come to those definitions?

Cross referenced from musl, glibc, and [other ppc64le ports I've done](https://github.com/shawnanastasio/chromium_power/blob/master/crashpad/0001-Implement-support-for-PPC64-on-Linux.patch).

> (and please do open a PR; just click "draft" if its not ready yet)

Sure, will do.

**Comment by daurnimator** [comment]
> Edit: [Done](https://github.com/ziglang/zig/pull/5527)

thanks!

Other things you'll need:
  - Any missing pieces of compiler_rt: https://github.com/ziglang/zig/tree/6524a64bda71a2eed9a3160562fd6da7232f9720/lib/std/special/compiler_rt
  - thread local storage setup: https://github.com/ziglang/zig/blob/6524a64bda71a2eed9a3160562fd6da7232f9720/lib/std/os/linux/tls.zig#L111
  - `clone`: https://github.com/ziglang/zig/blob/6524a64bda71a2eed9a3160562fd6da7232f9720/lib/std/special/c.zig#L197

**Comment by shawnanastasio** [comment]
Added musl's clone implementation and pushed to my PR branch. Will tackle compiler_rt next.

**Comment by shawnl** [comment]
Syscall is also a little funny. Just do what musl does.

**Comment by shawnanastasio** [comment]
Yeah, on ppc64le only r12 and a few other registers will be filled in by the kernel at program entrypoint. The TOC pointer (r2) and stack backchain initialization are generally done by libc, so it makes sense that we'd have to do it ourselves here.

**Comment by shawnanastasio** [comment]
Finally got time to work on this again. I've got a hello world zig program running on ppc64le! There's still a lot of testing/validation to do but this is great progress. I'll rebase and update the PR with my new changes shortly.

**Comment by andrewrk** [comment]
Tested locally with zig-bootstrap and it worked.

Related: https://github.com/ziglang/zig-bootstrap/commit/1fe11fe3ed83fb16910ea55bc0da197b24aff023

Enabling tarballs on ziglang.org shortly.
