### ISSUE TITLE
Allow comma-separated fields with singly type specifier in structs

### ISSUE THREAD

**Issue by JPGygax68** [ziglang/zig#5517]
In C/C++, you can write 
```c
struct Point {
   float x, y, z;
};
```
In Zig, you have to write 
```zig
const Point = struct {
  x: f32, y: f32, z: f32
};
```
This seems like a step backwards

**Comment by JPGygax68** [comment]
I would have appreciated a comment informing me of why this issue was closed. If such posts are unwelcome for a valid reason, I will desist.

**Comment by Vexu** [comment]
Isn't this a duplicate of #5519? Not sure why you opened another issue.

**Comment by JPGygax68** [comment]
What the .... ? I'm so sorry. There was what I thought was a glitch while typing in this issue, with the effect that the tagline got cleared while the text body stayed as it was. That's where the first (incomplete) issue must have been posted. My apologies.
