### ISSUE TITLE
odd behavior of coercion from pointer to slice

### ISSUE THREAD

**Issue by hiroakitakada** [ziglang/zig#5518]
I'm not sure wether this is a compiler bug or language feature.  The following code gets a compile error in `s = vp[0..5]`.  But when `vp` is casted to `[*]u32` explicitly (type of `vp` is `[*]u32`), the code can be compiled.

```zig
var array: [10]u32 = [_]u32{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, };
var vp: [*]u32 = undefined;
var s: []u32 = undefined;

test "odd behavior of coercion from pointer to slice." {
    vp = &array;

    // Why the following line gets a compile error?
    s = vp[0..5];

    // It's ok, if we cast 'vp' to [*]u32 (type of 'vp' is '[*]u32'!).
    s = @ptrCast([*]u32, vp)[0..5];
}
```

**Comment by Vexu** [comment]
The compiler doesn't notice that `vp` is no longer undefined so the safety features are triggered. Casting `vp` to the same type doesn't seem to preserve this hint so the code compiles.
