### ISSUE TITLE
Proposal: introduction of import/alias

### ISSUE THREAD

**Issue by hiroakitakada** [ziglang/zig#5521]
Types, constants, and functions can be imported from a child namespace.  A typical example is:

```
const assert = std.debug.assert;
```

But, there is no way to import variables from another namespace.  My proposal is to introduce new syntax to import any kind of name from a child namespace like below.

```
import name = namespace.name;
```
or
```
alias name = namespace.name;
```

**Comment by frmdstryr** [comment]
namespaces are structs. A `var` declaration in a namespace is a struct field.  So you can do: 

```zig
const name = &namespace.name;
```

**Comment by jessrud** [comment]
> [...] So you can do:
> 
> ```zig
> const name = &namespace.name;
> ```
@frmdstryr 

but the result is declaring a constant pointer to a mutable value, not a variable. this seems like a mostly ergonomic proposal, so that you don't have to deref a pointer and can access an aliased variable it in the same way you would in the other namespace, ie:
```zig
alias name = namespace.varname;
//...
name = value; 
```
vs
```zig
const name = &namespace.varname;
//..
name.* = value;
```

The syntax I would use would be something like:
```zig
var &name = &namespace.name;
```
to avoid overloading future uses of an `alias` keyword, and to make it clear that it's actually a variable in the inheriting scope.

But I have no idea whether this is coherent in the context of the rest of the language's semantics.

**Comment by frmdstryr** [comment]
Makes sense... I can see the usefulness of an `alias` in some cases. Would also be nice for renaming long chains of fields without any runtime cost.

**Comment by ifreund** [comment]
I personally see `alias` as an anti-feature. Needing to deref a pointer in order to modify the pointed to variable makes it very clear what is happening and is in my opinion more in line with the `zig zen`.

**Comment by Vexu** [comment]
This seems very similar to this rejected proposal #4676.

**Comment by pixelherodev** [comment]
I think that this is one area where status quo is fine, and we don't need to go further. Code should be explicit; we shouldn't be encouraging practices that lessen the value of separated namespaces.

**Comment by frmdstryr** [comment]
> Needing to deref a pointer in order to modify the pointed to variable makes it very clear what is happening and is in my opinion more in line with the zig zen.

> I think that this is one area where status quo is fine, and we don't need to go further. Code should be explicit; we shouldn't be encouraging practices that lessen the value of separated namespaces.

I have a lack of understanding here so hopefully someone can clarify this for me...  Would there be any performance advantage of an alias? 

Is there any runtime difference between using a ptr vs repeating/using the import/field path (ie an alias)? Or are they the exact same in terms of code generated?

**Comment by pixelherodev** [comment]
The cost of using a constant pointer to mutable data should be zero. The optimizer should be able to replace it with a direct access anyways. @frmdstryr

**Comment by pixelherodev** [comment]
Where direct access means a single memory op, same as you'd get from modifying the data directly, as opposed to two. Any optimizations it would be able to do with a normal var it should be able to do here.

**Comment by hiroakitakada** [comment]
In my initial message, I wrote functions can be imported from a child namespace like `const assert = std.debug.assert;`, but _this is not true_.  When the function is exported,

```
export const assert = std.debug.assert;
```

the exported `assert` is not a function but a pointer to the function.  Is this an intended behavior? Or, a bug of `export`?  (If this is a bug, this should be a separate issue.)

**Comment by Vexu** [comment]
@hiroakitakada see this https://github.com/ziglang/zig/issues/1717#issuecomment-615956379 for an explanation.

**Comment by hiroakitakada** [comment]
@Vexu Thank you for your quick reply.  I understand that this is an intended behavior.  I think it reasonable, because `assert` in the parent name space is `const`.

Then, my proposal (alias or import) is useful also in this case, because the following description exports the function body, not the pointer to it.
```
export alias assert = std.debug.assert;
```

**Comment by fengb** [comment]
The current way of exporting  is with `@export`:
```zig
comptime {
    @export(std.debug.assert, .{ .name = "assert" })
}
```

I'm not sure this exposing an alias would be semantically sound because the calling convention of these functions is most likely not C.

**Comment by andrewrk** [comment]
In the specs meeting yesterday we had a long discussion about this topic and importing in general, and ended up with this proposal:

```zig
using @import("std");
using std.debug.assert;
using namespace.name;
```

This special syntax would take a field access or an import builtin call, and put the named decl into the current namespace. The main motivations for this were (1) this issue regarding variables and (2) a way to avoid this accident:

```zig
const getWidth = @import("graphics.zig").getWidth;
const getHeight = @import("graphics.zig").getWidth; // oops
```

The `using` syntax is undeniably convenient, and clearly is the main use case for importing things. Additionally it solves the problem noted in this issue, as long as you don't need to alias the global variable declaration as a different name.

However.... I slept on it, and I'm ready to confidently close this issue in favor of status quo.

Here is my reasoning:
 * This is a chink in the armor of Zig being an **aggressively small** language. This proposal doubles the amount of syntactical constructs having to do with importing. Before, you can explain the entire importing system to someone by linking to the docs for [@import](https://ziglang.org/documentation/master/#import), after this there are caveats. If we had this syntax, it prompts the question, should we really do #1717? Why not support `struct`, `enum`, `union` etc at the top level?
 * The full `const`-based importing syntax teaches one how to do import aliasing, if you ever need to do it. This is the same reason that we only have breaking from named blocks and not additional syntax for breaking from the current block.
 * With `const`-based importing syntax, it always works to cut+paste into a local function body. With `using` that is not the case. As a side note, `usingnamespace` also does not work inside function bodies, but `usingnamespace` is generally discouraged except to organize the public declarations that are provided to an outside API.
 * The accident noted above is possible in so many different ways; this syntax is not a victim that particularly stands out. For example at every single callsite of getWidth/getHeight you might accidentally do the wrong one.

As for the problem noted in this issue with global variables - I recognize it as a case that is somewhat awkward to deal with, but the workarounds are completely reasonable and straightforward. Arguably it's even a feature that you have to try a little bit extra harder to turn global mutable state into public API.

Finally, after using the status quo importing system for quite some time, I find it to be entirely adequate, and therefore am against additional syntax and features regarding importing.
