### ISSUE TITLE
[ZigBuildSystem] Allow install()ing tests

### ISSUE THREAD

**Issue by travisstaloch** [ziglang/zig#5530]
I just wanted to make an issue to describe the benefits of #5514.  

This would make debugging tests executables **much** simpler.  Currently depending on whether the tests fail or not, i have been in the habit of using these steps to debug my test exe.  
- If tests fail:
  - copy the path shown into launch.json and launch lldb from within vscode.
- If tests succeed:
  - `rm -rf zig-cache`
  - rebuild test exe
  - find -name test
  - goto 'If tests fail'

As i understand it, with this PR i could add one line (`main_tests.install()`) to build.zig and skip all the above steps by using the path `zig-cache/bin/test` in launch.json or from the command line with lldb or gdb.

**Comment by pixelherodev** [comment]
That's the intent, yes :)

Going to take a bit though, because Windows CI failed and it's going to be a bit before I can debug that (not a Windows-er here, and the leak is in something seemingly entirely unrelated...)

**Comment by andrewrk** [comment]
This is done in #14647 which makes a test more like an executable in that it can be installed, and is not run by default without adding an explicit run step.
