### ISSUE TITLE
FYI ArrayList can act as a string buffer

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#5546]
Is there a standard library struct with a formatting print function that writes to allocated memory? Once the buffer is created I want to write the entire buffer to a file stream. I cannot print to the file stream directly because I am writing something else to it at the same time that I am creating the string buffer.

**Comment by SuperAuguste** [comment]
You might be looking for [allocPrint](https://ziglang.org/documentation/0.6.0/std/#std;fmt.allocPrint) @markfirmware! It allocates memory and writes formatted data to it!

**Comment by markfirmware** [comment]
Ok, allocPrint can get me one piece of output. How do I do another and another and get the concatenated result?

**Comment by haze** [comment]
I think you can use `print` on an `ArrayList.outStream()`
https://github.com/ziglang/zig/blob/master/lib/std/array_list.zig#L672

**Comment by markfirmware** [comment]
Ok, ArrayList looks ritpght and .items should return the result. Thanks!
