### ISSUE TITLE
Proposal: `inline for` on tuples

### ISSUE THREAD

**Issue by EleanorNB** [ziglang/zig#5551]
Title says it all really. Tuples support indexing, iterating over them is unambiguous, there's just as much a use case for it as there is for arrays. So for instance (code courtesy of @pixelherodev):
``` zig
fn write(self: *@This(), bytes: var) void {
    inline for (std.meta.fields(@TypeOf(bytes))) |_, i| {
        self.buffer[self.index] = bytes[i];
        self.index += 1;
    }
}
```
Becomes:
``` zig
fn write(self: *@This(), bytes: var) void {
    inline for (bytes) |byte| {
        self.buffer[self.index] = byte;
        self.index += 1;
    }
}
```

**Comment by alexnask** [comment]
I believe this already works, e.g. the following compiles and runs as expected

```zig
pub fn main() void {
    inline for (.{ "a", 42 }) |elem| {
        @import("std").debug.warn("{}\n", .{elem});
    }

    printTuple(.{ 0, 1, 0 });
}

fn printTuple(tuple: var) void {
    inline for (tuple) |elem| {
        @import("std").debug.warn("{}\n", .{elem});
    }
}
```

**Comment by pixelherodev** [comment]
Hmm. That runs for me, but attempting to switch the other bit doesn't.
```
/home/noam/Documents/Development/operation_tricarbon/lightzing/src/emitters/x86/assembler.zig:57:33: error: cannot store runtime value in compile time variable
            inline for (bytes) |v| {
                                ^
/home/noam/Documents/Development/operation_tricarbon/lightzing/src/emitters/x86/assembler.zig:107:43: note: called from here
                                self.write(.{0x50 | id});
                                          ^
```

I guess it only works for comptime-known values?

**Comment by alexnask** [comment]
Probably.  
I will try to find some minimal repro for this later so we can change the issue's title or open a new issue.

**Comment by pfgithub** [comment]
inline for works for tuples with runtime values, I use it frequently.
```zig
const std = @import("std");
pub fn write(bytes: var) void {
    inline for (bytes) |byte| std.debug.warn("{}\n", .{byte});
}
test "" {
    write(.{@as(u64, 0x50) | 0b1});
}
```

@pixelherodev it may not have worked for you because 0x50 is of type comptime_int which can't go in the runtime variable v. If id was a runtime value, I'm not sure why it wouldn't work though.

**Comment by EleanorNB** [comment]
Since there's a chance this is a non-issue, I'm going to close pending Alex's repro.
