### ISSUE TITLE
character literals in the range of 0x80..0xff can be encoded two ways

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#5552]
https://github.com/ziglang/zig/issues/2097#issuecomment-612916934

```
const std = @import("std");

test "character literal" {
    std.debug.warn("{}\n", .{'\xfd'});
    std.debug.warn("{}\n", .{'ý'});
}
```

A `comptime_int` of `0x80` means both `"\x80"` and `"\xc2\x80"`.

The solution for this is to use utf8-zextended-to-4-bytes instead of code points.

**Comment by shawnl** [comment]
Just to make this clear: this is a fundamental problem with how the _language_ is currently defined, and closing this issue will not make it magically go away.

**Comment by Vexu** [comment]
Are you proposing that the type of unicode character literals should be `u21` or that they should preserve their utf-8 encoding?

**Comment by daurnimator** [comment]
I think `'c'` being of type `comptime_int` is the problem: we need a distinct string/codepoint type.

**Comment by shawnl** [comment]
@daurnimator But we can leave them `comptime_int` if we store them as zero-extended utf-8 instead of unicode code points.

**Comment by andrewrk** [comment]
This is not a sufficient problem description. I do not believe there is a problem with status quo character literals and this issue is not clear enough to challenge that belief.
