### ISSUE TITLE
provide memmove in zig's freestanding libc

### ISSUE THREAD

**Issue by shawnl** [ziglang/zig#5554]
There is no `memmove` function in zig, which is needed: https://github.com/ziglang/zig/pull/3704#pullrequestreview-317998960 and by the existence of `mem.copyBackwards`.

And the documentation on the surrounding issues shows a lack of understanding: https://ziglang.org/documentation/0.6.0/#memcpy This is wrong because a forward copy provides guarantees that `memcpy` does not.

Attempts to improve the situation are met with "your patch is broken" and "this makes major changes" but you can't break what is already broken. https://github.com/ziglang/zig/pull/3602 The only criticism of that patch was a bikeshed over the name of `memmove`.

**Comment by pixelherodev** [comment]
At a quick glance at #3602, there were other issues mentioned.

> The Zig standard library and language does not intrinsically depend on LLVM and documentation should independently describe how things work without referencing LLVM.
> 
>Also this comment is not correct. Even for 1 byte types Zig does not guarantee atomicity unless one uses atomic operations.

>This breaks compile-time invocations of this function. See #382.

> This PR does a bunch of major changes to the language and standard library, *that are not advertised in the description*, and **lacks  supporting explanations of motivations for changes**

(emphasis mine)

The issue wasn't that major changes were made, but that the changes weren't advertised, and that explanations for why they were needed were not forthcoming.

The name does not seem like it was remotely the biggest concern, let alone the "only criticism."

**Comment by shawnl** [comment]
@pixelherodev Sorry if that came across wrong, or the previous patch.

The reason is simple:

`memcpy` and `memmove` in C provide rules about aliasing important enough that they get special treatment in the C standard, and we need both of them. Theoretically we can do a little better, because we have an alignment too.

Zig is basically just a nicer-to-use version of the C virtual machine (even comptime corms to the as-if rule), and these are essential components to that.

**Comment by andrewrk** [comment]
It's here: https://github.com/ziglang/zig/blob/52ba2c3a43a88a4db30cff47f2f3eff8c3d5be19/lib/std/special/c.zig#L115
