### ISSUE TITLE
Proposal: allow forwarding of struct fields for comptime meta programming

### ISSUE THREAD

**Issue by iansimonson** [ziglang/zig#5561]
Currently functions and constants specified with `pub` can be forwarded into a struct definition at comptime. This allows certain traits and functionality to be added to a struct. However it's not possible to do the same with struct fields.

e.g. the following works

```
const MyTraits = struct {
    pub fn foo(self: var) void {
        std.debug.warn("Foo! {}\n", .{self.x});
    }
};
pub fn CRTPLite(comptime T: type) type {
    return struct{
        x: i32,
        y: i32,
        pub const some_constant = 12345;
        pub usingnamespace T; //forwards functions / constants
    };
}

pub fn main() void {
    const S = CRTPLite(MyTraits);
    const x = S{.x = 5, .y = 4};
    x.foo();
}
```

but this does not:
```
pub fn MakeUsableByLibrary(comptime T: type) type {
    return struct {
        // probably requires some function or other to bring forward fields
        inline for(std.meta.fields(T)) | field| {
            field.name: field.field_type,
        },
        some_library_specific_field: i32,
        some_library_pointer: *@OpaqueType();
    };
}

const MyType = MakeUsableByLibrary(struct {
    x: i32,
   y: i32,
});

pub fn main() void {
    library.init(MyType, .{.x = 5, .y = 4}); // alternatively `MakeUsable` can embed an `init`
}
```

A concrete example use case would be e.g. porting (or creating something like) [Rocket](https://rocket.rs/) to Zig where user types aren't concerned with the library specific fields generated by the attributes.

More generally this would be good for composition of types.

A suggestion that was brought up as status quo was to embed a library type in the struct. However to use this with library functions either A: the functions would need to comptime look-up the field (and hopefully there's not more than one) or B: the user needs to specify a well-known name for the field. While that is possible, this proposal would allow the library to provide a meta-function to embed the type with a library-specific well-known name. This is an easier interface to use as generally the user does _not_ need to know about the field at all.

```
pub fn EmbedLibraryContext(comptime T: type) type {
    return struct {
        well_known_name: LibraryType,
        @bringForwardAll(T); //not a real suggestion just to be more demonstrative
    };
}

const S =EmbedLibraryContext(struct { x: i32, });
```

This proposal is related to #5521 in that it would probably be a similar mechanism and may unintentionally allow that usage, however the intent and focus of this proposal is different.

**Edit:** As for how this would work, the simplest (probably) would be modifying `usingnamespace` to bring fields in as well as `pub` declared consts. That might not hit all use cases as one could want to forward non-pub functions also so second suggestion would be a builtin function e.g. `@importType` or `@embedType`. I think allowing something like the `inline for` above that generated fields with `field.name: field.field_type,` might go against making Zig simple

**Comment by SpexGuy** [comment]
We discussed this at the design meeting, and decided that the utility of this feature doesn't outweigh the complexity.  With the current language, you can handle this use case like this:
```zig
const LibraryData = struct {
    some_library_specific_field: i32,
    some_library_pointer: *@OpaqueType();
}

const MyType = struct {
    x: i32,
    y: i32,
    lib_data: LibraryData = undefined,
};

pub fn main() void {
    // second parameter is comptime known field name
    // library will use `@field` to access the data.
    library.init(MyType, "lib_data", .{.x = 5, .y = 4});
}
```

We have not yet made a decision on #7311, which is a more fine grained version of this proposal.
