### ISSUE TITLE
question about pdh.h

### ISSUE THREAD

**Issue by foroughmajidi** [ziglang/zig#5562]
I want to know what is equivalent of pdh.h on linux?
Would you please help me about it?
thanks.

**Comment by gereeter** [comment]
You may be looking for [`perf_event_open`](https://www.man7.org/linux/man-pages/man2/perf_event_open.2.html), the all-in-one Linux syscall for dealing with performance counters and events. The system is unfortunately complex and not amazingly documented, but the man page is at least detailed. Most people only end up interfacing with it through the external [`perf`](https://en.wikipedia.org/wiki/Perf_(Linux)) tool, which has more documentation around how to use it, but isn't a library you can interface with.

As far as I know, nobody has made a Zig wrapper for `perf_event_open` yet; I'm not sure what other Zig-specific information you are looking for here.

**Comment by andrewrk** [comment]
[Ask in one of the community spaces](https://github.com/ziglang/zig/wiki/Community)
