### ISSUE TITLE
var args can't handle void or number literal arguments

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#557]
Issue discovered in #547 

Related to #313 #279 #280  

Add this test to std/fmt/index.zig:

```zig
    {
        var buf1: [32]u8 = undefined;
        const value: void = {};
        const result = bufPrint(buf1[0..], "void: {}\n", value);
        assert(mem.eql(u8, result, "void: {}\n"));
    }
```

**Comment by PavelVozenilek** [comment]
When I try this in online compiler:


```
const std = @import("std");
const warn = std.debug.warn;

pub fn main() void {
  const o  = 1;
  warn("{}\n", o);    
}

```


I get this error:

`/home/runner/.code.tio:6:16: error: compiler bug: integer and float literals in var args function must be casted. https://github.com/zig-lang/zig/issues/557
`

Something feels wrong here. When the value has explicit type it work.

**Comment by andrewrk** [comment]
Solved by removing var args from the language in a3f6a58c7785e7958f9d0b96d54356944bf34e32. Tuples do not have this limitation.
