### ISSUE TITLE
better error message when building an exe, not linking libc, and exporting libc main

### ISSUE THREAD

**Issue by dimenus** [ziglang/zig#558]
Seems to fail on x86_64, i386 in both GNU and MSVC.

MRE code: 
```
const c = @cImport(@cInclude("stdio.h"));
pub fn main() -> %void {
    c.printf("hello, world!\n");
}
```
compiler call:
`zig build-exe load.zig`

output:
`C:\msys64\home\ryan\load.zig:3:6: error: no member named 'printf' in '(C import)'
    c.printf("hello\n");`

**Comment by andrewrk** [comment]
Were you looking at ziglang.org? I updated the example there to match what was in the examples/ folder. Tell me if that didn't fix it.

**Comment by andrewrk** [comment]
We'll be able to support this smaller example on windows, but first we have to solve #515.

**Comment by Dimenus** [comment]
Yes, I was. Will refresh.

bootstrap.zig appears to get in the way:

```
F:\code\tools\zig\build-w64-debug\lib\zig\std\special\bootstrap.zig:66:8: error: exported symbol collision: 'main'
export fn main(c_argc: i32, c_argv: &&u8, c_envp: &?&u8) -> i32 {
       ^
F:\code\tools\zig\build-w64-debug\load.zig:10:8: note: other symbol is here
export fn main(argc: c_int, argv: &&u8) -> c_int {
       ^
F:\code\tools\zig\build-w64-debug\lib\zig\std\special\bootstrap.zig:41:34: error: expected type '?fn() -> %void', found 'extern fn(c_int, &&u8) -> c_int'
    std.debug.user_main_fn = root.main;
                                 ^
F:\code\tools\zig\build-w64-debug\lib\zig\std\special\bootstrap.zig:42:14: error: expected 2 arguments, found 0
    root.main() %% std.os.windows.ExitProcess(1);
             ^
F:\code\tools\zig\build-w64-debug\load.zig:10:8: note: declared here
export fn main(argc: c_int, argv: &&u8) -> c_int {
```

**Comment by andrewrk** [comment]
I think you need `--library c`.

This error message could be better, for example we could give the error "expected pub main() -> %void`, found `export fn main...`

**Comment by andrewrk** [comment]
Note that you can also use the normal `pub fn main() -> %void` when you link libc.

**Comment by Dimenus** [comment]
Ok, getting `Unable to determine msvc lib path.` now but that's to be expected since I'm using VS 2017 w/ the install on a non-standard path. I can look at making that part more robust on my own ( and will submit a pull if/when I come up with something). Thanks for the quick response!

**Comment by andrewrk** [comment]
See #539. Currently we only look for msvc 2015 but we should look for 2017 as well. Also there are command line args for setting the msvc path at runtime. Look for msvc in the --help menu.

**Comment by andrewrk** [comment]
Example now gives:

```
/home/andy/dev/zig/build/test.zig:1:11: error: C import failed
const c = @cImport(@cInclude("stdio.h"));
          ^
/home/andy/dev/zig/build/test.zig:1:11: note: libc headers not available; compilation does not link against libc
const c = @cImport(@cInclude("stdio.h"));
          ^
/run/user/1000/T1mB37.h:1:10: note: 'stdio.h' file not found
#include <stdio.h>
         ^
```

**Comment by Lucifer-02** [comment]
how to fix this?
