### ISSUE TITLE
return without try results in incorrect behavior

### ISSUE THREAD

**Issue by alexnask** [ziglang/zig#5599]
I have been having this issue in zls for a while but just sat down to debug it.  
When writing `break :` with no identifier token next a ControlFlowExpression node with an invalid label node is generated (and the next set of tokens, if any, will be interpreted as the rhs).  

I tried digging into the parser code to see why this is the case but it looks correct to me, since `parseBreakLabel` will return an error if there is no identifier after the colon, which will be caught in `parseBlock` and `findNextStmt` should skip over the break and potentially the next statement or until the end of the current block.  

I will continue looking into it tomorrown

**Comment by Vexu** [comment]
I can't reproduce this with just `break :`, do you have a longer test case?

**Comment by alexnask** [comment]
@Vexu 
This is the minimal testcase:  
```zig
comptime {
    break :
}
```
This will cause zls to crash when iterating the ControlFlowExpression and trying to access the label node's id.

**Comment by Vexu** [comment]
I still can't get it to crash using the latest version of zig and zls.

**Comment by alexnask** [comment]
@Vexu  

[This branch](https://github.com/alexnask/zls/tree/ctfe) will print `non null break label` instead of iterating over the children nodes when we find a ControlFlowExpression with a Break != null.  
I am also using master zig and this is printed with the example above, can you give it a shot?

**Comment by Vexu** [comment]
I'm still getting the expected behavior.
```zig
break : // nothing is printed
break : a // "non null break label"
break : 1 // nothing is printed
```

**Comment by Vexu** [comment]
Oh wait I forgot I tried applying this patch to `parse.zig`
```diff
diff --git a/lib/std/zig/parse.zig b/lib/std/zig/parse.zig
index ebf074ba4..7ac75aeb9 100644
--- a/lib/std/zig/parse.zig
+++ b/lib/std/zig/parse.zig
@@ -1911,7 +1911,7 @@ const Parser = struct {
     /// BreakLabel <- COLON IDENTIFIER
     fn parseBreakLabel(p: *Parser) !?*Node {
         _ = p.eatToken(.Colon) orelse return null;
-        return p.expectNode(parseIdentifier, .{
+        return try p.expectNode(parseIdentifier, .{
             .ExpectedIdentifier = .{ .token = p.tok_i },
         });
     }
```

Looks like this is a stage1 bug.

**Comment by alexnask** [comment]
Let me try this patch as well in this case

**Comment by alexnask** [comment]
Looks like this fixes it, weird bug.

**Comment by andrewrk** [comment]
no reduction; bug reported against deleted codebase
