### ISSUE TITLE
Offsets of extern struct fields don't always match C

### ISSUE THREAD

**Issue by artob** [ziglang/zig#5600]
If the purpose of `extern struct` is to match the system C compiler's struct layout and padding, then I would expect `@byteOffsetOf(v4l2_format, "fmt")` to be 8 instead of the 4 that I get with Zig 0.6.0 on Linux x86-64:

```zig
const std = @import("std");
const testing = std.testing;

const v4l2_format_fmt = extern union {
    // other union fields omitted
    raw_data: [200]u8,
};

const v4l2_format = extern struct {
    type: u32,
    //__padding: u32 = 0, // FIXME: this shouldn't be needed
    fmt: v4l2_format_fmt,
};

test "check v4l2_format.fmt offset" {
  testing.expect(@byteOffsetOf(v4l2_format, "fmt") == 8);
}

test "check v4l2_format size" {
  testing.expect(@sizeOf(v4l2_format) == 208); // on x86-64, at least
}
```

<img width="962" alt="Screen Shot 2020-06-14 at 18 12 48" src="https://user-images.githubusercontent.com/4963/84597181-ddd96600-ae6a-11ea-9c18-95f3801ddadb.png">

Inserting the manual `__padding` field makes these two test cases pass, with the struct size and field offsets matching what C code compiled with GCC against the system headers produces. Why is it necessary, though?

The corresponding C struct is defined in [`<linux/videodev2.h>`](https://github.com/torvalds/linux/blob/master/include/uapi/linux/videodev2.h) as follows, without any packing attributes or other confounders:

```c
struct v4l2_format {
    __u32 type;
    union {
        struct v4l2_pix_format          pix;
        struct v4l2_pix_format_mplane   pix_mp;
        struct v4l2_window              win;
        struct v4l2_vbi_format          vbi;
        struct v4l2_sliced_vbi_format   sliced;
        struct v4l2_sdr_format          sdr;
        struct v4l2_meta_format         meta;
        __u8 raw_data[200];
    } fmt;
};
```

**Comment by Vexu** [comment]
`v4l2_format.fmt` has alignment of 8 in C. Fixing the alignment makes the tests pass.
```zig
const std = @import("std");
const testing = std.testing;

const v4l2_format_fmt = extern union {
    // other union fields omitted
    raw_data: [200]u8,
    foo: usize, // for alignment 
};

const v4l2_format = extern struct {
    type: u32,
    fmt: v4l2_format_fmt,
};

test "check v4l2_format.fmt offset" {
  testing.expect(@byteOffsetOf(v4l2_format, "fmt") == 8);
}

test "check v4l2_format size" {
  testing.expect(@sizeOf(v4l2_format) == 208); // on x86-64, at least
}
```

**Comment by artob** [comment]
A belated kiitos, @Vexu! Closing.
