### ISSUE TITLE
Duplicate @cImport hangs Zig compiler

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#5602]
The Zig compiler hangs when doing a double `@cInclude` of the same C header. This also persists when doing these `@cInclude`s across different Zig source files (which is how I encountered the bug in the first place). This behavior was only tested on Windows.

Most minimal reproducible example of this:
```zig
const first = @cImport({ @cInclude("time.h"); });
const second = @cImport({ @cInclude("time.h"); });

pub fn main() void {
    _ = first.time(null);
    _ = second.time(null);
}
```
Saved the code into `main.zig` and ran `zig build-exe main.zig -lc`. The compilation never seems to finish.

**Comment by axzn** [comment]
If one needs to use the same `@cInclude` in two separate `.zig` files, the workaround for now is to make the one include `pub`: `pub const c_time = @cImport({ @cInclude("time.h"); });`, and refer it in the second file: `const c_time = @import("first_file.zig").c_time;`.

**Comment by andrewrk** [comment]
This is a bug but note that duplicate import of the same C header file is almost certainly not what you want. [@cImport docs](https://ziglang.org/documentation/master/#cImport)

**Comment by Vexu** [comment]
Fixed in master.
