### ISSUE TITLE
Question : defer keyword vs RAII

### ISSUE THREAD

**Issue by pfeatherstone** [ziglang/zig#5605]
I'm loving the look of Zig since I get fustrated with the endless complexities of C++. However, the one feature i do care about in C++ is RAII, so constructors and destructors. 
Now looking at ziglang, it looks like best practice when creating objects is to immediately defer the 'destructor'  or 'finaliser' function. If we are doing that, why not have RAII in Zig. It seems like it promotes code duplication. Is it that enforced to keep in line with zig's phillosophy of no hidden function calls?

**Comment by alexnask** [comment]
You can find a discussion on this in #782

**Comment by pfeatherstone** [comment]
Thanks. I'll close this.
