### ISSUE TITLE
better codegen for slices in parameters and return values

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#561]
https://bugs.llvm.org/show_bug.cgi?id=34952#c10

> You're passing around a lot of {i8*, i64} structs with byval. You'll probably get better code if you pass them as separate parameters. Of course, this changes the ABI, but if you control it for these types, then it's a nice win.

This would also solve #536.
It would make #560 easier to implement.

Be sure to measure performance before and after.

**Comment by mutech** [comment]
@andrewrk Just reading through std/hash/hash, there is a TODO referencing #561 (Check if the situation is better - hashing ints inline).

I don't know how to check it, otherwise I would have done it.
