### ISSUE TITLE
os.write on a closed socket triggers SIGPIPE

### ISSUE THREAD

**Issue by truemedian** [ziglang/zig#5614]
Calling os.write() on a peer-closed socket without the `MSG_NOSIGNAL` flag triggers a SIGPIPE, rather than return an EPIPE errno.

**Comment by yujiri8** [comment]
Would the right thing to do be to set MSG_NOSIGNAL by default on network sockets? I just ran into this, seems like a horrible default behavior to have a network program exit without any message when the remote end closes

**Comment by IridescentRose** [comment]
Correct, the best thing to do by default on network sockets is MSG_NOSIGNAL

**Comment by yujiri8** [comment]
I was asking if the stdlib should set it automatically, but I just realized it seems to be Linux-specific... there seems to be no equivalent to the MSG constants on windows for example.

**Comment by truemedian** [comment]
Windows doesn't have SIGPIPE. It does the equivalent of MSG_NOSIGNAL and returns the windows version of EPIPE (BROKEN_PIPE)

**Comment by truemedian** [comment]
This was fixed a while ago when the `keep_sigpipe` std option was introduced.

**Comment by andrewrk** [comment]
Addressed in c02ced4d346656abefa4cccfbdebf5dd27b326e5
