### ISSUE TITLE
?*c_void coerces to *c_void in function calls

### ISSUE THREAD

**Issue by ifreund** [ziglang/zig#5618]
The following code compiles while I think it should be rejected:
```zig
const std = @import("std");

pub fn main() void {
    var i: u32 = 5;
    var v: ?*c_void = &i;
    std.debug.warn("{}\n", .{voido(v)});
}

fn voido(v: *c_void) u32 {
    return @intToPtr(*u32, @ptrToInt(v)).*;
}
```
Coercion of `?*c_void` to `*c_void` can cause implicit dereferencing of a `null` pointer.

**Comment by pixelherodev** [comment]
I don't think this counts as miscompilation, but that's semantics.
