### ISSUE TITLE
Get "undefined symbol: main" when compiling C hello world example from the docs.

### ISSUE THREAD

**Issue by vedantroy** [ziglang/zig#5622]
When using `zig build-exe --c-source hello.c --library c -target x86_64-linux-musl` with the file:

```
#include <stdio.h>

int main(int argc, char **argv) {
    printf("Hello world\n");
    return 0;
}
```

I get the error:

```
Build Dependencies...crtn [2] Compile C Objects [1/1] crtn.s...lld: error: undefined symbol: main
>>> referenced by crt1.c:18 (/usr/lib/zig/libc/musl/crt/crt1.c:18)
>>>               /home/vedantroy/.cache/zig/stage1/o/w_JMv7vDBzs-DjU9hm85dD4JASxLnctzUBqnVuxxOsmiqea7MDP-L-7gHNww5CZF/crt1.o:(_start_c)
```

Not sure if it matters, but I am running Linux.

**Comment by deingithub** [comment]
Sorry, but I can't reproduce this on `0.6.0+0d18eda1d`, are you using the newest master version of Zig?

**Comment by vedantroy** [comment]
Hmm this was pretty recent (master branch that 4 -5 days old), however, it seems to have vanished. I will re-open this if it pops up again.
