### ISSUE TITLE
Proposal: add std.debug.todo

### ISSUE THREAD

**Issue by codehz** [ziglang/zig#5641]
Motivation:
Compared to `unreachable` and plain `@panic("TODO: something")`, it is more self-explanatory.
And it should be able to throw a compile error when try to build in release mode, so developer won't left it in released product.

Possible implementation:
```zig
pub fn todo(comptime desc: []const u8) noreturn {
    if (builtin.mode != .Debug and !@hasDecl(root, "allow_todo_in_release")) {
        @compileError("TODO: " ++ desc);
    }
    @panic("TODO: " ++ desc);
}
```

Use case:
```zig
switch (someBigTaggedUnion) {
.A => |a| handleA(a),
.B => |b| handleB(b),
...
.X => std.debug.todo("implement case X"),
```

**Comment by pfgithub** [comment]
instead of unreachable, how about `@panic("TODO: "++desc);`? That might be a bit more clear in error messages

**Comment by codehz** [comment]
> Instead of unreachable, how about `@panic("TODO: "++desc);`? That might be a bit more clear in error messages.

Ok, updated

**Comment by MasterQ32** [comment]
Sounds good to me. Imho you should just make a PR, so it gets merged some day

**Comment by andrewrk** [comment]
Changed my mind on this one, sorry. I don't think this is justified to be in the standard library.
