### ISSUE TITLE
Windows - zig fmt exits with AccessDenied

### ISSUE THREAD

**Issue by Sobeston** [ziglang/zig#5643]
```powershell
PS C:\project\test> Get-Acl .\main.zig


    Directory: C:\project\test


Path     Owner                     Access
----     -----                     ------
main.zig DESKTOP-RRE04JV\Sebastian BUILTIN\Users Allow  Modify, Synchronize...


PS C:\project\test> zig fmt main.zig
main.zig
AccessDenied
PS C:\project\test>
```
This happens on the latest master build (windows 10 x64), and happens even when in an admin powershell prompt. The build I had before updating (about a week old) did not have this problem.

I would guess that https://github.com/ziglang/zig/commit/b30642a86ae59f9cfe73c8a9ed6e79c3cb5aaa36 caused this regression

**Comment by andrewrk** [comment]
Thanks for the report. So far I am unable to reproduce this - is there anyone who can reproduce it willing to take a look?

**Comment by alexnask** [comment]
I will give it a shot in a couple of hours
