### ISSUE TITLE
Proposal: Rename Mutex to Bottleneck

### ISSUE THREAD

**Issue by Fl0wless** [ziglang/zig#5646]
If we want a better C, naming is really important. One should know what one is getting into when using specific features. (Idea: @KevlinHenney)

**Comment by ifreund** [comment]
I think this makes no sense. Everyone familiar with concurrent programming is familiar with the word Mutex. If you didn't realize, Mutex is an abbreviation for MUTual EXclusion, which is a much more precise description than "bottleneck". Renaming this would cause nothing but confusing.

**Comment by Fl0wless** [comment]
But the point is that MUTual EXclusion doesn't carry the performance implications that are inevitably going to appear with its usage with it. The Mutex as an entity of anti-parallelism is often included when it is not really needed, because arguing "I know what to do, we need a mutex here" is simple, while arguing "I know what to do, we need a bottleneck here" better shows the gravity of the situation and leads the developer to maybe reconsider unnecessary resource locking and instead opt for an immutable concurrency approach, which — in many (but not all) use cases — may be objectively superior.

**Comment by ifreund** [comment]
To put it bluntly, trying to accommodate bad programmers is not good design practice.

**Comment by Fl0wless** [comment]
Friend, I am only joking ;)
