### ISSUE TITLE
[Windows] detect builtin support for VT in supportsAnsiEscapeCodes

### ISSUE THREAD

**Issue by codehz** [ziglang/zig#5647]
Since win10 has supported VT Sequences, we can detect it from GetConsoleMode.

https://github.com/ziglang/zig/blob/aa894cea2c4aab32cc137adbe22c5f25411cc723/lib/std/fs/file.zig#L141-L144

**Comment by squeek502** [comment]
This was addressed by https://github.com/ziglang/zig/pull/16080
