### ISSUE TITLE
ability to translate some C macros that are functions

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#565]
Inspired by #562 

Here's how SDL defines `SDL_WINDOWPOS_UNDEFINED`:

```
 SDL_video.h:#define SDL_WINDOWPOS_UNDEFINED         SDL_WINDOWPOS_UNDEFINED_DISPLAY(0)
 SDL_video.h:#define SDL_WINDOWPOS_UNDEFINED_DISPLAY(X)  (SDL_WINDOWPOS_UNDEFINED_MASK|(X))
 SDL_video.h:#define SDL_WINDOWPOS_UNDEFINED_MASK    0x1FFF0000u
```

We could actually translate this macro, by noticing that the argument `X` is only used once, and hence
not vulnerable to the "execute expression twice" behavior.

Then we have to be able to tokenize parens and the `|` operator, and then parse those into a parse
tree, and then translate `|` into zig.

`SDL_WINDOWPOS_UNDEFINED_DISPLAY` becomes an inline function:

```zig
inline fn SDL_WINDOWPOS_UNDEFINED_DISPLAY(X: var) -> var {
    return SDL_WINDOWPOS_UNDEFINED_MASK|X;
}
```

`SDL_WINDOWPOS_UNDEFINED` becomes an inline function:

```zig
inline fn SDL_WINDOWPOS_UNDEFINED() {
    return SDL_WINDOWPOS_UNDEFINED_DISPLAY(0);
}
```

We try to run the function at compile time, and it works, so we change `SDL_WINDOWPOS_UNDEFINED` into a global variable with the result of running the function at compile time.

**Comment by ibebrett** [comment]
Is this currently implemented? I wouldn't mind taking this on.

relevant files: https://github.com/ziglang/zig/blob/master/src/c_tokenizer.cpp ?

**Comment by andrewrk** [comment]
Any contributions in this area would be appreciated. And yep, that's the relevant file

**Comment by Vexu** [comment]
Macro functions are now supported remaining cases are covered by #1085.
