### ISSUE TITLE
zig run does not take package paths into account in the cache hash

### ISSUE THREAD

**Issue by alexnask** [ziglang/zig#5650]
Here is a setup to reproduce this

```zig
// File `file1.zig`
const std = @import("std");
const pkg = @import("package");

pub fn main() void {
    pkg.run();
}
// File  `file2.zig`
pub fn run() void {
    @import("std").debug.print("Hi from file2.zig", .{});
}
// File `file3.zig`
pub fn run() void {
    @import("std").debug.print("Hi from file3.zig", .{});
}
```  

Running `zig run file1.zig --pkg-begin package file2.zig --pkg-end` will correctly print `Hi from file2.zig`  
Running `zig run file1.zig --pkg-begin package file3.zig --pkg-end` after that without modifying `file1.zig` will print `Hi from file2.zig`

**Comment by Vexu** [comment]
Fixed in master when using the new syntax: `zig run --dep package -Mmain=file1.zig -Mpackage=file2.zig`.
