### ISSUE TITLE
Proposal: add std.fs.File.readToEnd convenience function

### ISSUE THREAD

**Issue by kubkon** [ziglang/zig#5657]
I've noticed that in order to the entire contents of a file into a dynamically-allocated buffer, we need to perform a couple of steps. For example, using `std.fs.File.readAllAlloc`:

```zig
const file_size = try file.getEndPos();
const max_bytes = @intCast(usize, file_size); // or math.cast to catch the overflow error
const contents = try file.readAllAlloc(allocator, file_size, max_bytes);
defer allocator.free(contents);
```

Alternatively, we could also use `std.io.bufferedReader`:

```zig
const file_size = try file.getEndPos();
const max_bytes = @intCast(usize, file_size); // or math.cast to catch the overflow error
var buf_stream = io.bufferedReader(file.reader());
const st = buf_stream.reader();
const contents = try st.readAllAlloc(std.testing.allocator, max_bytes);
defer allocator.free(contents);
```

My proposal would be to add a convenience function `std.fs.File.readToEnd` which would wrap all this for the user, thus expecting only the allocator as an argument:

```zig
const contents = try file.readToEnd(allocator);
defer allocator.free(contents);
```

Note that this approach is largely inspired by the presence of a similar function in Rust's `libstd`, which is part of the `std::io::Read` trait.

---

**Proposal PR ->** To explore what changes/additions to the codebase this would entail, see #5658

**Comment by daurnimator** [comment]
There is no need AFAIK, `try file.readAllAlloc(allocator, file_size, std.math.maxInt(usize));` should work.

**Comment by kubkon** [comment]
> There is no need AFAIK, `try file.readAllAlloc(allocator, file_size, std.math.maxInt(usize));` should work.

Ah, cool, so this would take care of the problem with casts. So the question now is would it be worth wrapping `readAllAlloc` + `getEndPos` as `readToEnd`? I guess this might be an overkill. On the other hand, then the user wouldn't have to think about the details such as "how do I get the filesize". What do you think @daurnimator?

**Comment by daurnimator** [comment]
Ah sorry, I meant to say, `file.reader().readAllAlloc(allocator, std.math.maxInt(usize))` should be sufficient: you don't need to know the file size up front. (infact its a race condition; and impossible for certain file types)

**Comment by kubkon** [comment]
Ah, gotcha! That's actually pretty neat! I'll close this proposal then as this is pretty obsolete.
