### ISSUE TITLE
[Azure]: Windows CI seems broken (msvc and mingw)

### ISSUE THREAD

**Issue by kubkon** [ziglang/zig#5679]
See latest PRs such as: #5678, #5673, or #5677.

It seems that there is some conflict when upgrading packages that causes the entire job to error out:

```
:: Synchronizing package databases...
downloading mingw32.db...
downloading mingw32.db.sig...
downloading mingw64.db...
downloading mingw64.db.sig...
downloading msys.db...
downloading msys.db.sig...
:: Starting core system upgrade...
warning: terminate other MSYS2 programs before proceeding
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing filesystem (2020.02-3) breaks dependency 'msys2-base' required by dash
```

**Comment by andrewrk** [comment]
@emekoi it looks like the repo that we depend on for this is deprecated. Do you happen to know how to upgrade?

**Comment by andrewrk** [comment]
This looks like it has the answer: https://github.com/msys2/MINGW-packages/blob/master/azure-pipelines.yml

**Comment by emekoi** [comment]
aside from using the one-click installer, have you looked at using github actions? they have runners for macos, linux, windows, and arm, support caching of artifacts, and the windows runners come with msys2 installed by default. i think (not sure) that the windows runners also come with llvm compiled for msvc as well.

**Comment by kubkon** [comment]
I'm also partial to moving away from Azure CI and to Github Actions like @emekoi suggested, and would be happy to help in setting it up if that's the way we want to go.

**Comment by andrewrk** [comment]
I'd be fine with moving from Azure to GitHub actions, although it's not a personal priority for me to work on. The only potential problem is that we currently rely on pretty hefty resource usage, in terms of both time and memory, that Azure gives us. It wouldn't be worth it if we had to disable a bunch of tests.
