### ISSUE TITLE
Passing optional pointer to optional optional pointer argument causes ICE

### ISSUE THREAD

**Issue by arbrk1** [ziglang/zig#5686]
The code

``` zig
pub fn main() void {
    var x: u32 = 42;
    var y: ?*u32 = &x;
    foo(y);
}

fn foo(x: ??*u32) void {}
```

causes

```
broken LLVM module found: Call parameter type does not match function signature!
  %0 = load i32*, i32** %y, align 8, !dbg !15299
 %"??*u32"*  call fastcc void @foo(i32* %0), !dbg !15300
```

Observed on 0.6.0 and master.

Interestingly, 0.4.0 on [godbolt.org](https://godbolt.org/) compiles this code successfully.

**Comment by xackus** [comment]
There are more cases of broken complex pointer types.
The bug is in the mapping of zig types to LLVM types.
stage1 generates different LLVM types for `ZigType`s that differ only by qualifiers like `const`.
See https://github.com/ziglang/zig/issues/4907#issuecomment-619337956 for another example.

**Comment by Vexu** [comment]
Fixed in master.
