### ISSUE TITLE
Comptime is not required for arguments of comptime only types after first generic argument

### ISSUE THREAD

**Issue by alexnask** [ziglang/zig#5709]
Example

```zig
fn Matrix(
    comptime T: type,
    width: comptime_int,
    height: comptime_int,
) type {
    return [height][width]T;
}
```

`width` and `heigth` should be checked and require `comptime` even if they are actually type erased.

**Comment by cristobal-montecino** [comment]
See also #5672

**Comment by Vexu** [comment]
Fixed in self-hosted, tested in `test/cases/compile_errors/comptime_parameter_not_declared_as_such.zig`.

**Comment by Vexu** [comment]
Fixed in self-hosted, tested in `test/cases/compile_errors/comptime_parameter_not_declared_as_such.zig`.
