### ISSUE TITLE
calling free on undefined struct field segfaults without trace

### ISSUE THREAD

**Issue by stripedpajamas** [ziglang/zig#5716]
running `zig test` on the below segfaults but no trace is printed. was expecting traces to always be dumped during tests.

```zig
const std = @import("std");

const A = struct {
    bytes: []u8
};

pub fn main() !A {
    return A{
        .bytes = undefined,
    };
}

test "main" {
    const a = try main();
    std.testing.allocator.free(a.bytes);
}
```

**Comment by Vexu** [comment]
I'm getting full stack trace, what OS are you on?

**Comment by stripedpajamas** [comment]
MacOS 10.15.5

**Comment by mikdusan** [comment]
macos does not install a SIGSEGV handler (yet)

**Comment by schmee** [comment]
Related: https://github.com/ziglang/zig/issues/10609
