### ISSUE TITLE
Is it possible to embed information in errors?

### ISSUE THREAD

**Issue by hasenj** [ziglang/zig#572]
For example, say I'm parsing something and I hit an unexpected character, so I do something like:

    return error.invalidChar;

But I also want the error to carry information about _which_ char was invalid.

Is there a way to do that?

**Comment by andrewrk** [comment]
The suggestion for this situation is to make your own type with `enum` and use that.

```zig
const Result = enum {
    Ok,
    InvalidChar: usize,
};
fn parse(input: []const u8) -> Result {
    // if it works
    return Result.Ok{};
    // if it has unexpected char
    return Result.InvalidChar { position };
}
```

**Comment by thejoshwolfe** [comment]
This is brushing against a general issue which is that zig error codes are used a lot like exception objects (in Java, for example), but zig error codes are missing lots of useful features of exception objects. Another missing feature that would be useful is a stack trace.

**Comment by andrewrk** [comment]
> `@lineinfo()` which could return something like a struct { filename: []const u8, line: u64, col: u64 } or something like that.

I agree, I was thinking along the same lines. Want to make a new issue with a proposal? We can use that to track the feature.

**Comment by hasenj** [comment]
opened #577

**Comment by andrewchambers** [comment]
The proposed solution will not work with errdefer though?

**Comment by andrewrk** [comment]
> The proposed solution will not work with errdefer though?

In this case you can populate the error data, and then return a general error such as `error.SemanticAnalysisFailed`. This is the strategy taken by the self hosted compiler, for example.
