### ISSUE TITLE
release flag with --cache on does not create any executable in current directory

### ISSUE THREAD

**Issue by bokunodev** [ziglang/zig#5727]
`uname -r`
5.3.0-rc8-0.8-MANJARO-ARM - aarch64

`zig build-exe --release-{safe,fast,small} --cache on hello.zig`

I tried all release flag with cache on.
the code is helloworld from zig example in langref.html.
I also tried delete zig-cache dir. but still no binary created on current directory.
also this **only** happen if cache is on.

![tmp](https://user-images.githubusercontent.com/54968427/85918315-d8791400-b88b-11ea-955d-e05ec241f295.gif)

**Comment by alexnask** [comment]
The binary is probably placed in `zig-cache/bin` in this case although I agree it should probably be copied over to the cwd.

**Comment by bokunodev** [comment]
@alexnask no, there is no `bin/` directory inside `./zig-cache/` or `~/.cache/zig/`.
no executable at all.

![tmp1](https://user-images.githubusercontent.com/54968427/85919514-d5832100-b895-11ea-91e3-74022d711b2d.png)
![tmp2](https://user-images.githubusercontent.com/54968427/85919516-d7e57b00-b895-11ea-8437-cc88af702d4e.png)

**Comment by alexnask** [comment]
Hm, weird. I will take a look at this bug later, probably pretty easy to fix.

**Comment by Vexu** [comment]
`--cache` option has been removed.
