### ISSUE TITLE
Unhelpful/misleading error message on extra symbols between struct functions

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#5739]
Given the following test `.zig` file:
```zig
const Example = struct {
    some_var: i32,

    fn a() void { }
    fn b() void { }
    fn c() void { } e
    fn d() void { }
};

pub fn main() void { }
```

Zig throws the following compilation error:
```
> zig build-exe play.zig
.\play.zig:4:5: error: declarations are not allowed between container fields
    fn a() void { }
    ^
```

Unfortunately, this is completely not helpful and misleading, since it points to the first occurrence of the first function within a struct rather than the obviously erroneous `e` symbol after the `fn c()` declaration.
This is not a problem in such a small example but quickly becomes an issue in a huge source file when it is not obvious what the error is really caused by.

The best possible possible error in this scenario would be something like:
```
> zig build-exe play.zig
.\play.zig:6:21: error: unexpected symbol 'e' between container declarations
    fn c() void { } e
                    ^
```

**Comment by Vexu** [comment]
The common case for this error is situations like this:
```zig
/// something
field: u32,

/// else
other: struct {
    a: u32,
    b: u32,
},

const S = struct {
    a: u32,
};

b: S,
```
```
./build/a.zig:41:1: error: declarations are not allowed between container fields
const S = struct {
^
```

Your proposed change would be more confusing here since `field` is a perfectly valid field and not just a symbol:
```
./build/a.zig:33:1: error: unexpected symbol 'field' between container declarations
field: u32,
^
```
The optimal solution here would be to also add a note pointing to the fields.
