### ISSUE TITLE
zig cc cross compile error

### ISSUE THREAD

**Issue by danielabbott** [ziglang/zig#5740]
I'm currently trying to cross-compile (linux [WSL] -> windows) freetype using zig as a C compiler.
I'm getting an error when compiling C files with the -c command line argument.

zig version 0.6.0+581d16154

source.c
`int main() {return 0;}`

> zig cc -c source.c

^ Works fine

> zig cc source.c -target x86_64-windows-gnu

^ Works fine

> zig cc -c source.c -target x86_64-windows-gnu

^ Gives an error:

> lld: warning: ignoring unknown argument '-r'
> lld: error: <root>: undefined symbol: WinMainCRTStartup
> lld: error: undefined symbol: __main
> referenced by zig-cache/o/wNerU1KCNR2tufgovliVLbS8BiWZiuHP2V8f618osoXc08YjThqajamx-WP-PUaE/source.o:(main)

I'm not sure why lld is being run since -c is supposed to skip linking.

**Comment by andrewrk** [comment]
This has been fixed for a while; we used to try to support merging multiple .o files into one but not anymore.
