### ISSUE TITLE
Packed struct, size of field % 8 !=0,  @byteOffsetOf does not include prior fields byte offset

### ISSUE THREAD

**Issue by vegecode** [ziglang/zig#5743]
```zig
test "@byteOffsetOf packed struct, fields cross byte boundary" {
    const P = packed struct {
        a: u9,
        b: u7,
    };

    std.testing.expectEqual(0, @byteOffsetOf(P, "a"));
    std.testing.expectEqual(1, @byteOffsetOf(P, "b"));
}
```

I reference this in my (failing) pull request #5713. What is the intended behavior?

This issue is linked to issue #5742 as they both come out of the same code section which is `resolve_struct_type` where the offsets are calculated.

**Comment by daurnimator** [comment]
Duplicate of #2627?

**Comment by vegecode** [comment]
Yep totally a duplicate. I would still like to know whether this test should pass or if it is a bug.

**Comment by vegecode** [comment]
Well I put in a pull request to fix the issue. It fixes byteOffset of. It's waiting to be reviewed and merged.
