### ISSUE TITLE
New vector syntax proposal.

### ISSUE THREAD

**Issue by Rainer4** [ziglang/zig#5750]
Most non-embedded processors nowadays have full support for SIMD vectors. Therefore, I propose that SIMD vectors be exposed as a primitive type in the Zig language.

Pros:
- Short
- Easy to read
- Easily extensible. For example, if matrix types were to ever be added, then a 4x4 matrix of i32 could simply be expressed as i32x4x4. NOTE: If matrices ever were to be implemented, 4x3 would mean 4 columns and 3 rows, NOT 4 rows and 3 columns, as is typically done in math. This is because vectors are better thought of as being horizontal(like arrays) in programming.

Declaration Syntax(based on Arm NEON vectors): A vector type would be declared as follows (primitiveVariant)(primitiveSize)x(numberOfPrimitives), so a vector of 4 i32 values would be declared like this: `var x:i32x4 = undefined;`

Initialization syntax:
To initialize a vector of 4 i32 values, do: `var x:i32x4 = { undefined, undefined, undefined, undefined }'

Accessing individual members and groups of members (subdividing): Variables would be accessed according to a syntax similar to the OpenCL vec.sN syntax, where N is the index of one of the vector's members. To access the first i32 of a i32x4, simply do: `var val = vec4Name[0]`. To access a i32x2 from the 4-member vector, consisting of the first and third members of the 4-member vector, do: `var val = vec4Name[0,2]`. Note that a comma is included within the brackets, which reassures someone reading the code that he or she is indeed looking at a vector, and not an array. This form of subdivision(this would be the official term used to denote the creation of smaller vector from a larger vector) would be known as an implicit subdivision, since the type created from amalgamation of 0 and 2 is not explicitly stated(and is assumed to be i32x2 by the compiler). To access elements 0 and 2 as an i64, do: `var val = vec4Name.i64[0,2]`. Because the returned type is explicitly stated, this would be known as an explicit subdivision. To create a i32x3 containing members 0 through 2 (inclusive) of the 4-element vector, do: `var val = vec4Name[0:2]`. Modifying values in a vector, instead of accessing, would just require putting the subdivision on the left side of the assignment operator: `vec4Name[0:2] = undefined`.

If matrices were to ever be supported, then first-order implicit subdivisions (such as the ones above), would return matrices. However, second-order subdivisions("Second-order" refers to the fact that at least one index is further subdivided by more indices.) (`var val = vec4x2Name[0[0,1],1[0,1]]`) cannot be implicit, due to the fact that it is unclear what is to be returned (either a 2x2 matrix, or a 4-element vector could be returned).

**Comment by Snektron** [comment]
There currently already exists a vector type in Zig. The documentation is kinda scarce at the moment, but you can read
about some examples in the behavior tests: https://github.com/ziglang/zig/blob/master/test/stage1/behavior/vector.zig.

#903 tracks SIMD implementation status. Note that syntax similar to `i32x4` was already discussed around here: https://github.com/ziglang/zig/issues/903#issuecomment-459571881
