### ISSUE TITLE
Download and setup osx libc header via bootstrap script

### ISSUE THREAD

**Issue by aahmed-se** [ziglang/zig#5752]
Since it's unclear whether osx libc headers can be shipped as per missing license headers, provide osx specific bootstrap script as a workaround that, can request users approval to setup the the zig env with libc downloaded from the address below post installation.

https://opensource.apple.com/tarballs/Libc/Libc-1353.41.1.tar.gz

**Comment by andrewrk** [comment]
I'm not satisfied with the user experience of this.

We may yet be able to provide cross compilation libc headers for apple, but either way I don't see this bootstrap script being in zig's future.
