### ISSUE TITLE
[CI]: SourceHut seems broken

### ISSUE THREAD

**Issue by kubkon** [ziglang/zig#5756]
See #5755, #5754.

**Comment by watzon** [comment]
It does indeed. Something about `Error: Child killed`.

**Comment by andrewrk** [comment]
At first I thought it might be using too much memory and getting OOM killed. But I just checked:

```
$(which time) -v ./zig0 build-lib ../src-self-hosted/stage2.zig -lc --bundle-compiler-rt -fPIC -target x86_64-freebsd
	Maximum resident set size (kbytes): 1650772
```

That's 1.6 GiB to build, which should be fine. Also, upon closer inspection, the command it is failing on is 

```
:: argv: /usr/home/build/zig/build/zig build --override-lib-dir /usr/home/build/zig/lib -Dlib-files-only --prefix /usr/home/build/zig/build/release -Dconfig_h=/usr/home/build/zig/build/config.h install
```

which is when it is installing the library files. The weird thing is I just ssh'd in and ran the command again and this time it succeeded. So I haven't been able to reproduce the issue yet.

**Comment by andrewrk** [comment]
Sorry for the issues folks. If you want your PRs to get green checks, my suggestion is to rebase against master.

What happened is that the freebsd CI has been building the self-hosted compiler all this time, unintentionally. I've been doing work on the self-hosted compiler. There is more code to compile now, which slowly has been adding more memory requirements for building self-hosted. Eventually, it was too much and source hut didn't give us enough ram to do it. So now the ci only builds the self-hosted compiler for the other CI systems, not sourcehut.

The issue for reducing memory requirements of stage1 is #471. It's going to get worse before it gets better, but at some point we'll have self-hosted, which is extremely memory efficient, and we'll be able to use that to fix stage1 as well.
