### ISSUE TITLE
Anonymous struct in anonymous list with named struct segfaults

### ISSUE THREAD

**Issue by stripedpajamas** [ziglang/zig#5764]
```zig
// asdf.zig
const A = struct {
    idx: usize,
};

test "asdf" {
    const a = .{
        .{
            .xyz = @as(usize, 1),
            .abc = A{
                .idx = 0,
            },
        },
    };
}
```

`zig test asdf.zig` immediately segfaults (doesn't even reach normal pre-test compilation steps). if I remove `.xyz`, it doesn't; if I remove `.abc` it doesn't. Not sure if this is expected behavior or not; regardless, I would have expected a trace on crash if it's a code problem.

env: Mac OS 10.5.5, zig master

**Comment by Vexu** [comment]
Fixed in master.
