### ISSUE TITLE
kernel32.dll Win7 32bit x86 GetSystemTimePreciseAsFileTime could not be located in...

### ISSUE THREAD

**Issue by MortezaRahmaniJRP** [ziglang/zig#5766]
The procedure entry point GetSystemTimePreciseAsFileTime could not be located in the dynamic link library Kernel32.dll

**Comment by tnodir** [comment]
MSDN: Minimum supported client: Windows 8

**Comment by daurnimator** [comment]
Windows 7 is no longer supported; as seen in the [Support Table](https://ziglang.org/#Support-Table) the minimum windows version is 8.1.

**Comment by Prince213** [comment]
Try this workaround:
https://github.com/ziglang/zig/blob/d7f00c43897655e3bb6a9cddf1b1191a6c1381e0/lib/libc/include/any-windows-any/_mingw.h#L232-L234
Replace `0x0603` with `0x0601`, then rebuild Zig.
Alternatively, check out https://reviews.llvm.org/D104987.

**Comment by Mouvedia** [comment]
@daurnimator

> [Even without explicit support, non invasive patches to widen support are welcome. They won't be tested by the CI though and will be maintained on best effort, but without mandatory testing.](https://github.com/ziglang/zig/issues/7242#issuecomment-736772022)

**Comment by pancelor** [comment]
The support table link seems to be broken; I believe this is what it's referring to:
https://ziglang.org/download/0.8.1/release-notes.html#Support-Table

After some cursory investigation, 0.5.0 seems to be the last major version that supports windows 7:
https://ziglang.org/download/0.5.0/release-notes.html#Support-Table

**Comment by telecran-telecrit** [comment]
> Try this:
> 
> https://github.com/ziglang/zig/blob/d7f00c43897655e3bb6a9cddf1b1191a6c1381e0/lib/libc/include/any-windows-any/_mingw.h#L232-L234
> 
> 
> Replace `0x0603` with `0x0601`, then rebuild Zig.
> In addition, check out https://reviews.llvm.org/D104987, which ensures that we always use the highest precision available.

I get "GetSystemTimePreciseAsFileTime not found" too, but for pure NodeJS. There is other way, when recompilling is long or not possible... [VxKex](https://github.com/vxiiduu/VxKex) (windows 7 extended kernel to 8+).

P. S.: Only for advanced users.
