### ISSUE TITLE
zig test --release-fast is not failing when it should

### ISSUE THREAD

**Issue by paulespinosa** [ziglang/zig#5787]
### Environment
zig version 0.6.0+e120b07a5 (https://ziglang.org/download/0.6.0/zig-macos-x86_64-0.6.0.tar.xz)
macOS 10.15.5

### Issue
The test found in the code listed below should fail. However, the test passes when running the zig test command with the `--release-fast` option:

`zig test md_array_wrong.zig --release-fast`

**Note**: The test _fails_ as expected with 
* `zig test md_array_wrong.zig`
* `zig test md_array_wrong.zig --release-safe`
* `zig test md_array_wrong.zig --release-small`

#### File md_array_wrong.zig
```zig
// file: md_array_wrong.zig
const std = @import("std");
const assert = std.debug.assert;

const mat4x4 = [4][4]f32{
    [_]f32{ 1.0, 0.0, 0.0, 0.0 },
    [_]f32{ 0.0, 1.0, 0.0, 0.0 },
    [_]f32{ 0.0, 0.0, 1.0, 0.0 },
    [_]f32{ 0.0, 0.0, 0.0, 1.0 },
};

test "multidimensional arrays test should fail" {
    for (mat4x4) |row, row_index| {
        for (row) |cell, column_index| {
            // The assert should fail when row_index != column_index
            assert(cell == 1.0);
        }
    }
}
```

#### Output
```
# zig test md_array_wrong.zig --release-fast
All 1 tests passed.
```

### Expected
The test should have failed

**Comment by Vexu** [comment]
`--release-fast` removes the safety check on `unreachable` turning `assert` into a no-op. For testing you should use `std.testing.expect`.

**Comment by paulespinosa** [comment]
@Vexu Thank you!
