### ISSUE TITLE
Comptime function gets called twice, leading to export collision

### ISSUE THREAD

**Issue by schroffl** [ziglang/zig#5789]
I'm trying to export a symbol via a comptime function, but it gets called twice. This leads to Zig trying to export an already existing symbol on the second call.

`main.zig`
```zig
const std = @import("std");

pub fn main() void {}

comptime {
    generateExport();
}

fn generateExport() void {
    @export(myFunction, .{
        .name = "my_function",
        .linkage = .Strong,
    });
}

fn myFunction() callconv(.C) void {}
```

`Output`
```
> zig run main.zig
./main.zig:10:5: error: exported symbol collision: 'my_function'
    @export(myFunction, .{
    ^
./main.zig:10:5: note: other symbol is here
    @export(myFunction, .{
    ^
```

When you add a `@compileLog` to the `generateExport` function you can clearly see that it gets called twice in a row.

**Comment by hiroakitakada** [comment]
This problem is already reported with https://github.com/ziglang/zig/issues/5380 .

**Comment by schroffl** [comment]
Sorry, seems like I didn't look well enough.

**Comment by schroffl** [comment]
Duplicate of #5380

**Comment by hiroakitakada** [comment]
I encountered the same problem.  A workaroud of this problem is to pass a dummy comptime parameter to `generateExport` function.

```
const std = @import("std");

pub fn main() void {}

comptime {
    generateExport({});
}

fn generateExport(comptime dummy: void) void {
    @export(myFunction, .{
        .name = "my_function",
        .linkage = .Strong,
    });
}

fn myFunction() callconv(.C) void {}

```

**Comment by schroffl** [comment]
Cool, thanks for the workaround!
