### ISSUE TITLE
WASM table is not exported

### ISSUE THREAD

**Issue by leroycep** [ziglang/zig#5790]
## Problem

Zig generate a function table when generating WASM output, but the function table is not exported. Since the table is not exported, I can't directly call the function from the host environment.

## Sample Code

```zig
// test.zig
export fn hello() void {
    register(add_one);
}

fn add_one(a: i32) callconv(.C) i32 {
    return a + 1;
}

extern fn register(callback: fn (i32) callconv(.C) i32) void;
```

```
$ zig build-lib -target wasm32-freestanding test.zig
$ wasm2wat test.wasm >> test.wat
```

[gist containing `test.wat`](https://gist.github.com/leroycep/b47dade18e892211e6b2d08e21501846)

If you look at lines [94-98 on the gist](https://gist.github.com/leroycep/b47dade18e892211e6b2d08e21501846#file-test-wat-L94-L98) you can see the table is generated, but that there is no corresponding export for it. Adding `(export "table" (table 0))` resolves the issues, but I'm not sure what the best practice is for exporting function tables.

Edit: I just looked at the output for some similar C code compiled using emscripten, and it imports a function table instead of exporting it:

```wat
  (import "env" "table" (table (;0;) 18 18 funcref))
```

**Comment by zigazeljko** [comment]
LLD has an option `--export-table` which does just that, but currently there is no way to use that option while using `zig build-lib`. We should probably add that by default or at least make it configurable.

@leroycep In the meantime, you can use `zig build-obj` to generate the object file and link it manually with `zig clang` as such:

```
$ zig build-obj -target wasm32-freestanding test.zig
$ zig clang -target wasm32-freestanding -Wl,--allow-undefined -Wl,--export-all -Wl,--export-table -Wl,--no-entry -nostdlib test.o -o test.wasm
```

**Comment by leroycep** [comment]
@zigazeljko Thanks for the tip! I'm actually using `build.zig` for the most part, so I translated it to work with what I was doing. Here's a snippet of what I ended up with:

```zig
    const default_plugin_obj = std.build.LibExeObjStep.createObject(b, "default-plugin", std.build.FileSource{ .path = "default-plugin/plugin.zig" });
    default_plugin_obj.addPackage(plugin_api_pkg);
    default_plugin_obj.setBuildMode(b.standardReleaseOptions());
    default_plugin_obj.setTarget(.{ .cpu_arch = .wasm32, .os_tag = .freestanding });

    const defaultPluginOut = b.fmt("{}" ++ sep_str ++ "default-plugin.wasm", .{pluginOutDir});
    const default_plugin = b.addSystemCommand(&[_][]const u8{ "zig", "clang", "-target", "wasm32-freestanding", "-Wl,--allow-undefined", "-Wl,--export-table", "-Wl,--no-entry", "-nostdlib", "-o", defaultPluginOut });
    default_plugin.addArtifactArg(default_plugin_obj);
    b.getInstallStep().dependOn(&default_plugin.step);
```

But once there's an option for doing this without calling out to `zig clang` I'll switch to using that.
