### ISSUE TITLE
Add a "string" type alias for "[]const u8"

### ISSUE THREAD

**Issue by luauser32167** [ziglang/zig#5794]
From Zig's documentation:
```zig
    // Zig has no concept of strings. String literals are const pointers to
    // arrays of u8, and by convention parameters that are "strings" are
    // expected to be UTF-8 encoded slices of u8.
    // Here we coerce [5]u8 to []const u8
    const hello: []const u8 = "hello";
    const world: []const u8 = "世界";
```

The type ```[]const u8``` is 10 characters long and there are approximately ~1000 occurrences of it in *std* alone. In most cases it means a UTF-8 encoded string, in the rest it means a u8/byte buffer to read from. It's probably not very hard to figure out the meaning from the context (the surrounding function/struct name) but it takes a tiny bit of effort. A type alias for ```[]const u8``` called ```string``` (or ```text```, or something else) could be added in order to unambiguously convey the type of the entity. It might also be shorter/easier to type. It seems appropriate to use shorter names for types that are used extensively (```u32``` instead of ```uint32```, ```f32``` instead of ```float```, etc.).

**Comment by justjosias** [comment]
For consistency, `string` wouldn't really just mean `[]u8`, with `const string` meaning `[]const u8`? Thus the typing benefits are decreased, and it becomes less clear what exactly a `string` is.

**Comment by data-man** [comment]
Windows love `u16`.

**Comment by data-man** [comment]
```c++
std::string	std::basic_string<char>
std::wstring	std::basic_string<wchar_t>
std::u8string (since C++20)	std::basic_string<char8_t>
std::u16string (since C++11)	std::basic_string<char16_t>
std::u32string (since C++11)	std::basic_string<char32_t>
```

**Comment by Sobeston** [comment]
I don't think it's in zig's best interest to have a single type called string. There's ascii, extended ascii and utf-8 which all look like []u8 for example, and must be treated differently. What I think we do need is a way to nicely annotate what string encoding is being used.

**Comment by daurnimator** [comment]
An actual string type can bring along a few extra features not present with `[]const u8`:
  - methods that only make sense on strings
  - a field `.is_valid_utf8: ?bool`

**Comment by jorangreef** [comment]
I was going to write the same as @Sobeston.

If a type alias will be introduced, then it makes sense to tie the alias to the encoding of the string:

```zig
const hello: []const u8 = "hello";
const hello: utf8 = "hello";
```

"utf8" conveys more information than "string" and is shorter to type, down to 4 characters now.

**Comment by andrewrk** [comment]
You can make such a type in user space. No need for it to be a language primitive.

**Comment by luauser32167** [comment]
> You can make such a type in user space. No need for it to be a language primitive.

Sure. But it would be nice if everyone picks the same name for the same concept, for example:

```str8``` for a UTF-8 encoded string (```str16``` for UTF-16LE?, and ```str32``` for UTF-32)

This is very unlikely to happen if Zig doesn't pick a name, and simply let people define their own type aliases to ```[]const u8/16/32```.

Some people would stick with ```[]const u8```, others might use c++'s names, some (I guess like me) would just call it string and pretend that there's only UTF-8 or something...

Regardless ```[]const u8``` can either mean a UTF-8 string or a source of bytes, and not every source of bytes is a UTF-8 string.

**Comment by jnorinder** [comment]
Try this... gives some perspective on the problem with string handling.
```
const DELIMITER_CHARS: []const u8 = " !\"#¤%&/()=$£@¡@£$€¥{[]\\±},.-;:0123456789|<>";
test "String should not contain any delimiting chars" {
    // Arrange
    const stringWithSpecialChars: []const u8 = "Det här är en sträng.";

    // Act
    var actualIterator = mem.tokenizeAny(u8, stringWithSpecialChars, DELIMITER_CHARS);

    // Assert
    try testing.expect(mem.eql(u8, actualIterator.next().?, "Det"));
    try testing.expect(mem.eql(u8, actualIterator.next().?, "här"));
    try testing.expect(mem.eql(u8, actualIterator.next().?, "är"));
    try testing.expect(mem.eql(u8, actualIterator.next().?, "en"));
    try testing.expect(mem.eql(u8, actualIterator.next().?, "sträng"));
    try testing.expect(actualIterator.next() == null);
}
```
Sure, I can use some lib from a nice person like "dude the builder" to work with strings in my language (Swedish). However, the error message you get?! Well.... that took me a while to figure out.

**Comment by lefay1982** [comment]
> You can make such a type in user space. No need for it to be a language primitive.
Many other languages all have the "string" keyword. Why is Zig so special? If it were implemented at the language primitive, the IDE could infer types and display them more concisely and clearly. Zig claims to be a simple language, but many people complain that it's not. Shouldn't you think about this?

**Comment by lefay1982** [comment]
So please Add a "string" type alias for "[]const u8"
It's just an alias, and it won't have a significant impact. 
Instead, it will provide more convenience for more people.
