### ISSUE TITLE
Where to start: extension modules for Python?

### ISSUE THREAD

**Issue by goodboy** [ziglang/zig#5795]
Given that [`zig` is also a C compiler](https://ziglang.org/#Zig-is-also-a-C-compiler), I'm wondering how hard would this actually be to get going as a prototype?

As an example `nim` has a very nice (and possibly similar) ecosystem for this:
- https://github.com/Pebaz/Nimporter
- https://github.com/yglukhov/nimpy

Of particular interest is using `zig` to extend Python event loop type machinery as well as an eventual march towards numerics extensions.

**Comment by aahmed-se** [comment]
try this
https://github.com/octonion/puzzles/tree/master/blackjack/python-zig

**Comment by goodboy** [comment]
@aahmed-se thanks for the tip!

Very interested to toy with this approach :smile_cat:

**Comment by andrewrk** [comment]
[Ask in one of the community spaces](https://github.com/ziglang/zig/wiki/Community)
