### ISSUE TITLE
Proposal: option to allow syscalls at comptime

### ISSUE THREAD

**Issue by bazzb** [ziglang/zig#5796]
There should be an option to explicitly allow certain packages to make syscalls at comptime

**Comment by EleanorNB** [comment]
What would be the use cases for this?

**Comment by bazzb** [comment]
> What would be the use cases for this?

Mostly because it is nicer than doing it in the build.zig, putting it in a file and then embedding that file.
I understand it is probably for safety but i think it would be fine if we make it explicitly allowable.

**Comment by daurnimator** [comment]
> Mostly because it is nicer than doing it in the build.zig, putting it in a file and then embedding that file.
> I understand it is probably for safety but i think it would be fine if we make it explicitly allowable.

Far more than just safety:
  - it requires knowledge about host structures and layouts instead of target structures and layouts (in zig, cross compiling is a top priority)
  - it runs counter to zig's caching strategy (as interacting with the outside environment as syscalls do cannot be cached).
