### ISSUE TITLE
Proposal: Have `zig fmt` format code blocks in doc comments

### ISSUE THREAD

**Issue by schroffl** [ziglang/zig#5799]
I just saw these top level [doc comments in `std/log.zig`](https://github.com/ziglang/zig/blob/master/lib/std/log.zig#L14), which had me wondering: Is there a plan to have `zig fmt` format zig code blocks in doc comments? That would make writing examples and keeping them up to date a lot easier.

From what I saw the documentation looks like markdown (I don't know if it's planned to go down that road), so it would probably make sense to use the syntax hints at the beginning of code blocks to also determine if it should be formatted.

When you write
````
```zig
// Code goes here
```
````
`zig fmt` would know to format this section.

Relevant IRC discussion (time is GMT+02 if anybody is interested): 
```
21:39 < forgot-password> Will zig fmt format the code snippets eventually? Or maybe it already does that... Zig surprises me every single day
21:39 < leeward> Which code snippets?
21:39 < leeward> In comments?
21:40 < forgot-password> The code blocks in the doc comments
21:40 < forgot-password> https://github.com/ziglang/zig/blob/master/lib/std/log.zig#L14
21:41 < leeward> It doesn't now. I think it would need a way to know that a piece of text is code to be formatted.
21:42 < leeward> A heuristic might have false positives, which would be pretty annoying.
21:42 < forgot-password> Since this looks like markdown, I guess it could just determine that when you write ```zig it should format that block
21:44 < leeward> It's worth a proposal.
```

***

*Other Thoughts*: Maybe there could also be a way to let users create custom formatters in the future. If a library has a lot of assembly, json, etc. in the documentation it could be a lot more comfortable to have that auto-formatted. However, I'm not so sure how well this fits into Zig. It's probably better to have your editor take care of that.

**Comment by EleanorNB** [comment]
> It's probably better to have your editor take care of that.

If this is possible, then the same technique can be used to `zigfmt` comment blocks. We don't necessarily need to add a special case for it. In fact, that might be a hassle, since it would lock us into one specific markup language.

**Comment by tauoverpi** [comment]
Would it then also make sense to type check the examples? That would at least reduce the chance of incorrect documentation examples getting through (only needed on `-femit-docs` to avoid general overhead).

**Comment by andrewrk** [comment]
Too complicated; out of scope
