### ISSUE TITLE
thumb arch, when usize - usize = 0, causes panic

### ISSUE THREAD

**Issue by vegecode** [ziglang/zig#5803]
[https://zig.godbolt.org/z/uyBEg4](url)

```
        cmp     r0, r1
        str     r2, [sp]
        bhs     .LBB1_2
```

This comparison is generated for a usize minus another usize. If they are both zero, the panic trips due to overflow.

Interested to take a look if someone could point me in the right direction.

**Comment by andrewrk** [comment]
Here I've added `--release-safe` and a function `foo` which you can see does not trip the panic.

https://zig.godbolt.org/z/qzNbur

Is there some number other than `10` you can put here that will demonstrate the problem?

**Comment by vegecode** [comment]
Well, I'm not sure what I was thinking last night. For some reason I thought the bhs instruction was taking it to the panic. I'll refile the issue once I diagnose it correctly in my project.

[https://github.com/vegecode/BurnedHead/blob/c15e511b11892430f12ba61645e8fc64bbf64bde/firmware/startup.zig#L158]()

This line is panicking for me in debug mode, and both variables point to the same address. I have to build my project in release-safe or do a mod subtraction to get past this point.

Sorry for the noise.

**Comment by andrewrk** [comment]
No problem, hope you get it figured out.
