### ISSUE TITLE
build_options not removed from cache

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#5809]
I use addBuildOption() and @import("build_option") and the build works. If I remove the addBuildOption() then the build still works because the build options are not removed from the cache. I think the build should fail.

**Comment by purringChaos** [comment]
Can confirm on `0.6.0+485231dea`

**Comment by nektro** [comment]
this can be closed

![image](https://user-images.githubusercontent.com/5464072/131280124-6a434672-5f10-4cb1-bbde-ffc60766aac1.png)
