### ISSUE TITLE
Type unexpectedly gains const in !?T -> ?T -> *T capture chain

### ISSUE THREAD

**Issue by squeek502** [ziglang/zig#5819]
When writing https://github.com/ziglang/zig/pull/5818 I wanted to add the following in order to match the other test cases:

```zig
   // Access the value by reference using a pointer capture.
   var d: anyerror!?u32 = 3;
   if (d) |optional_value| {
       if (optional_value) |*value| {
           value.* = 9;
       }
   } else |err| {
       unreachable;
   }

   if (d) |optional_value| {
       assert(optional_value.? == 9);
   } else |err| {
       unreachable;
   }
```

but it fails to compile with:

```
.\if-else-catch.zig:80:23: error: cannot assign to constant
            value.* = 9;
                      ^
```

After adding some `@compileLog`'s I found that `optional_value` is of type `?u32` (expected) but the `*value` capture is of type `*const u32` (unexpected)

The following works correctly and doesn't inject a const:

```zig
   var e: ?u32 = 3;
   if (e) |*value| {
       value.* = 2;
   }
```

**Comment by SpexGuy** [comment]
This is intentional.  You are capturing the error payload by const value instead of by pointer capture.  That needs to be a pointer capture also if you want to modify it:
```zig
   var d: anyerror!?u32 = 3;
   // Access the error payload by reference using a pointer capture.
   if (d) |*optional_value| {
       // Access the optional value by reference using a pointer capture.
       if (optional_value.*) |*value| {
           value.* = 9;
       }
   } else |err| {
       unreachable;
   }

   if (d) |optional_value| {
       assert(optional_value.? == 9);
   } else |err| {
       unreachable;
   }
```

**Comment by squeek502** [comment]
Interesting, that makes sense. For some reason getting the pointer of an optional value never occurred to me as a possibility (`@TypeOf(optional_value)` in the first capture is `*?u32`).
