### ISSUE TITLE
Writers should have a way to flush them.

### ISSUE THREAD

**Issue by Sobeston** [ziglang/zig#5826]
Buffered IO is a thing, and buffered readers/writers are a thing because of this. Unfortunately only a `writeFn`/`readFn` is supplied, so functions taking in one do not have a way to flush if they need to.

I encountered this by making use of a buffered SSL stream (stream meaning a pair of a writer and a reader, in this case wrapping a TLS socket stream) and using this SSL stream for web sockets. During the websocket handshake the websocket code wrote to the SSL stream, and then waited for a response. Unfortunately as the SSL stream is buffered, what the websocket wrote to it wasn't sent, meaning that nothing was sent over the network and no response came. It indefinitely waited. This has since been worked around, but it isn't nice.

The current API doesn't provide a way to flush writers and I think we need one, as the alternative is ugly workarounds.

cc @truemedian

**Comment by marler8997** [comment]
Since the current `writer` interface doesn't have flush semantics, I think it means that any object conforming to it should be flushing immediately.  If you want to create an extended interface to expose buffering semantics to the caller, you should be free to do so without having to modify the underlying `Writer` interface itself correct?

**Comment by daurnimator** [comment]
I've mentioned this before: the writer function should take an `buffering_mode: enum { .none, .partial }`

**Comment by Sobeston** [comment]
> you should be free to do so without having to modify the underlying Writer interface itself correct?

Yes, just buffered IO is extremely common and I think should be a part of the "default" interface. A flush with an un-buffered writer would simply be a no-op.

**Comment by marler8997** [comment]
> Yes, just buffered IO is extremely common and I think should be a part of the "default" interface. A flush with an un-buffered writer would simply be a no-op.

This also puts a burden on the caller, now whenever they use a writer, it is up to them to be sure to call `flush` if they expect their data to be written immediately.  Code that doesn't do this would work most of the time making it a hard problem to catch.

This also adds some runtime overhead to store the function pointer for the flush function.  The solution to add more functions to the underlying interface whenever we need to support a variation in behavior doesn't seem scalable to me.

Instead, adding a `BufferedWriter` type seems more tractable as it allows the caller to declare whether they expect buffering so they will be more likely to use the interface correctly and doesn't add unnecessary overhead to writers that don't support buffering.

**Comment by Sobeston** [comment]
> This also puts a burden on the caller, now whenever they use a writer, it is up to them to be sure to call flush if they expect their data to be written immediately.

That burden is already on the caller - they just can't do anything about it

> This also adds some runtime overhead to store the function pointer for the flush function. The solution to add more functions to the underlying interface whenever we need to support a variation in behavior doesn't seem scalable to me.

One extra pointer isn't something that people should reasonably worry about here, and the idea of a slippery slope doesn't really apply. (whether this extra pointer can be eluded, I'm not sure)

I disagree that they should be two different interfaces as they should be able to be used interchangeably - ie I should be able to supply a non-buffered writer to a function expecting a buffered writer and vice versa. Calling flush becomes a no-op on a non-buffered writer, and providing a buffered writer to a function expecting a non-buffered writer should work.

**Comment by andrewrk** [comment]
The status quo Writer interface is well defined and well understood. If you need to expose the ability to flush to clients, that is a different interface, which I would argue is so obscure as to not be necessary in the standard library. I havent looked at the code in question but when I've used buffered writing it was always the appropriate abstraction for the same layer that introduces flushing to be in charge of calling flush().

**Comment by data-man** [comment]
I'm wondering why in stdlib there are no memory-mapped readers/writers/streams. :)
Flush API can be useful for (future?) them.
Linux has `msync`, Windows has `FlushViewOfFile` and other useful functions in [memoryapi](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/).

**Comment by MasterQ32** [comment]
> The status quo Writer interface is well defined and well understood. If you need to expose the ability to flush to clients, that is a different interface, which I would argue is so obscure as to not be necessary in the standard library. I havent looked at the code in question but when I've used buffered writing it was always the appropriate abstraction for the same layer that introduces flushing to be in charge of calling flush().

@andrewrk One real-life example which made code unnecesserily more complex was in ZPM where i needed to add another generic parameter to a function to expose a `flush` function for Writer as SSL libraries always await *full blocks* and when you don't push a full block, it just doesn't get send. So the function was generic against `Reader`, `Writer` and an additional `FlushProvider`.

Otherwise i would have required to duplicate the longest function in the whole project in order to have the layer that requires flush to be called with flush. (Having separate paths for HTTP and HTTPS only differing by a single `flush`)

I strongly vote for `Writer` to have a `flush` interface. Otherwise a lot of code using `Writer` will just *not work* when it's requiring `flush` to be called.

**Comment by daurnimator** [comment]
>  as SSL libraries always await _full blocks_ and when you don't push a full block, it just doesn't get send

I don't think an SSL library is the best example of this behaviour (you can opt out of this buffering bio in OpenSSL); however the situation you describe isn't disimilar to message based protocols: when writing to e.g. a UDP socket, you need to pass it a packet at a time (or several... but you have to provide a list of packets), and not a partial packet.
To avoid this dichotomy, SCTP introduced the `MSG_EOR` flag to `sendto` to indicate a flush should happen.

**Comment by purringChaos** [comment]
There are several applications in which I need flush functionality.
