### ISSUE TITLE
Move or introduce Zig Test earlier in language reference documentation

### ISSUE THREAD

**Issue by paulespinosa** [ziglang/zig#5837]
### Issue
The Zig language reference (documentation) has many code samples implemented in `test`s ([Zig's Test tool](https://ziglang.org/documentation/0.6.0/#Zig-Test)). However, the Zig Test tool is introduced and documented much later, further down, in the Zig documentation. New Zig users may not know about this section as they read the documentation and miss an opportunity to understand the syntax and tool. 

### Proposal
Two options:
1. **Move** the Zig Test section before any usages of the Zig test tool.
2. Before any usage of the Zig test tool, **introduce** the test syntax and basic usage of the Zig test tool and include a link to the Zig Test section.

### Justification
Give new Zig learners the opportunity to understand the Zig Test tool before it is used in other code samples.

**Comment by Mouvedia** [comment]
related: #8221
