### ISSUE TITLE
Any way to have a collection of generic structures?

### ISSUE THREAD

**Issue by flmng0** [ziglang/zig#5839]
To Preface: This is my first time trying Zig. I love it so far, but listed below is my current issue.

Using the Zig language in it's current state, I can't find any way to create a collection of generic structures, the simplest example I can think of is: [Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6f249e464b1bfb6850857aa1fb4e8a60)

The point that I'm trying to show is the collection of dynamic objects, i.e: `Vec<&dyn core::fmt::Debug>`. In Zig, there is no way that I know of to achieve something similar, a collection of generics.

The specific concept I'm trying to implement:
```zig
const print = @import("std").debug.print;

fn State(comptime Data: type) type {
    return struct {
        const Self = @This();

        data: ?Data,
        callback: fn (self: *Self) void,

        pub fn init(
            callback: fn (self: *Self) void,
            data: ?Data,
        ) Self {
            return Self{ .data = data, .callback = callback };
        }
    };
}

fn do_thing_i32(state: *State(i32)) void {
    print("{}", .{state.data.?});
}
fn do_thing_f64(state: *State(f64)) void {
    print("{}", .{state.data.?});
}

pub fn main() void {
    // What type should I put for
    //               | this |.
    const thing = [_]State{
        State(i32).init(do_thing_i32, -21),
        State(f64).init(do_thing_f64, 3.14159265),
    };

    for (thing) |state| {
        state.callback();
    }
}
```

Sorry to include such a large example, but through experimentation, this was the simplest I could get my example, which still provides a good idea of what I want to do.

**Comment by daurnimator** [comment]
Your rust example is a collection of pointers to different types; whereas your zig example has the actual data.
Do you know the element types somehow out-of-band? or is it only generic at comptime?

**Comment by flmng0** [comment]
@daurnimator Thanks for the quick response. I don't really understand what you mean by out-of-band. I've only recently gotten back into low-level programming.

I can answer that it is only generic at comptime, because this is for a game library. States will be stored in a state stack, and the top of the stack is what will handle current events. However, I'd like to allow each state to have it's on "state data" pointer. In a prototype C implementation, I used `void *` for this.

**Comment by pfgithub** [comment]
In zig, you can use `usize` along with `ptrToInt`/`intToPtr`

Something like this for example:

```zig
const State = struct {
    data: usize,
    callback: fn(data: usize) void,
    pub fn init(comptime Type: type, comptime callback: fn (data: *Type) void, data: *Type) State {
        return .{
            .data = @ptrToInt(data),
            .callback = struct{fn a(value: usize) void {
                callback(@intToPtr(*Type, value));
            }}.a,
        };
    }
};
```

**Comment by flmng0** [comment]
Thanks, this is a nice solution, I should have been looking for alternatives to C's `void *`, rather than trying to, obviously incorrectly, use comptime generic structs.
