### ISSUE TITLE
Prevent Comptime imports from exporting symbols or importing extern symbols

### ISSUE THREAD

**Issue by suirad** [ziglang/zig#5841]
When importing zig code during comptime, the executable that imports that code also receives the exports from the imported code. I am not sure if this is a bug or proposal. See the following:

---

`main.zig`
```zig
pub fn main() void {
    comptime {
        const a = @import("exports.zig");
    }
}
```

`exports.zig`
```zig
extern fn blah() void;

export fn test() void {
    blah();
}
```

---

In the above code, the resulting binary ends up exporting the symbol `test`; which is a leak of comptime into the resulting binary.
In addition to this, compilation fails because the imported symbol `blah` is unavailable, which shouldnt matter at comptime anyway because you cannot execute foreign code during comptime.

**Comment by vegecode** [comment]
I am currently relying on this behavior to force the inclusion of the vector tables and startup code for my freestanding embedded project.

[https://github.com/vegecode/BurnedHead/blob/master/firmware/main.zig](https://github.com/vegecode/BurnedHead/blob/master/firmware/main.zig)

**Comment by suirad** [comment]
@vegecode in your use case, what would be the difference for your project to change 
```zig
comptime {
    _ = @import("startup.zig");
}
```
To instead be
```zig
_ = @import("startup.zig");
```

Would that not have the same result? What is the difference?

**Comment by travisstaloch** [comment]
> ```zig
> _ = @import("startup.zig");
> ```
> 
> Would that not have the same result? What is the difference?

At top level, this is a compilation error:
```sh
error: invalid token: ';'
```

**Comment by eriksik2** [comment]
All imports happen at comptime. Having symbols added to the binary is something you must expect when using `@import`, as it's part of the semantics of importing something.

**Comment by andrewrk** [comment]
This is working as designed and I don't find this proposal sufficiently convincing to change status quo. Feel free to push back on this with new examples, considerations, or persuasions.
