### ISSUE TITLE
Enum self-dependency may be desirable

### ISSUE THREAD

**Issue by davidgarland** [ziglang/zig#5850]
At the moment I'm writing a state machine based lexer, and for that it's rather nifty to (ab?)use some C features and GNU extensions:

```C
// A type for character kinds.
enum chr_kind {
  CK_NONE,
  // Lowercase letters
  CK_LOWER,
  CK_LOWER_B,
  CK_LOWER_X,
  CK_LOWER_LENGTH,
  // Uppercase letters
  CK_UPPER = CK_LOWER_LENGTH,
  CK_UPPER_LENGTH,
  // Operators
  CK_OPER = CK_UPPER_LENGTH,
  CK_OPER_DASH,
  CK_OPER_GT,
  CK_OPER_LT,
  CK_OPER_LENGTH,
  CK_LENGTH = CK_OPER_LENGTH // yields the number of elements in the enum as a whole
};

// A type for token kinds, which are made by composing characters.
enum tkn_kind {
  TK_ARROW = CK_LENGTH,
  TK_LENGTH
};

// Map characters to their respective character kinds.
uint8_t find_chr_kind[256] = {
  ['a'] = CK_LOWER,
  ['b'] = CK_LOWER_B,
  ['c' .. 'w'] = CK_LOWER,
  ['x'] = CK_LOWER_X,
  ['y' ... 'z'] = CK_LOWER,
  // etc.
};
```

So far so good-- so why didn't I stick with C? Well, I wanted to encode the lexer state machine transitions as a static lookup table; however, GNU extensions only got me so far:

```C
uint8_t find_tkn_kind[TK_LENGTH][CK_LENGTH] = {
  [CK_NONE][CK_LOWER] = CK_LOWER,
  [CK_NONE][CK_LOWER_B] = CK_LOWER_B,
  [CK_NONE][CK_LOWER_X] = CK_LOWER_X,
  // etc... Man, this is really repetitive. If only I had compile time execution, then I could write [CK_NONE][i] = i.

  [CK_LOWER ... CK_LOWER_LENGTH - 1][CK_LOWER ... CK_LOWER_LENGTH - 1] = CK_LOWER,
  // etc..

  [TK_DASH][TK_GT] = TK_ARROW, // `-` + `>` = `->`
  // etc..
};
```

So I'd prefer to do it in Zig, but I've hit a few roadblocks:

- If you refer to an enum constant from the current enum when defining a new enum constant, this throws an error saying that the enum depends upon itself. I don't really see the issue with that; C does it just fine.
- ~~Zig does not allow enum overlaps. In general I think this is a good, sane decision, but it puts a damper on things here.~~ @Vexu has clarified that this is possible, but only in enums marked `extern`.

Zig *does* have a few desirable properties for what I'm doing already though:

- Compile-time execution is a godsend here.
- Zig already allows me to have one enum use another's last member as the start of its indices, so you can do the same sort of "enum inheritance". Having that as an actual feature would be cool, but unnecessary.

So: Is there any pre-existing way I can achieve what I'm trying to do, or some modification that could be made to the language to allow this? Perhaps all of this is trivially solved with metaprogramming of some kind?

**Comment by Vexu** [comment]
To get the amount of fields in an enum you can use `std.meta.fields(<your enum type here>).len``and overlap is allowed in extern enums:
```zig
const E = extern enum {
    a = 1,
    b = 1,
    c = 1,
};
test "" {
    const fields = std.meta.fields(E);
    @compileLog(fields.len); // 3
    const enum_max_value = fields[fields.len - 1].value;
    @compileLog(enum_max_value); // 1
}
```

**Comment by davidgarland** [comment]
That's nifty, thank you-- that still leaves the issue of enum self-referencing though, unless extern enums allow that as well (in which case I think they solve my problems).

**Comment by Vexu** [comment]
What use case do you have for self-referencing? In your example auto numbering would give the same result.

If you have a longer example, I might be able to give you a more idiomatic way to do it in Zig. Also be sure to check out [`std.zig.tokenize`](https://github.com/ziglang/zig/blob/master/lib/std/zig/tokenizer.zig) for an example of a tokenizer written in Zig.

**Comment by davidgarland** [comment]
Auto-numbering does not give the same result there; the sub-range "_LENGTH" fields would be granted their own variants, when they really only serve to act as markers and are not actual kinds.

**Comment by eriksik2** [comment]
Extern enums should allow self dependency. That's the Behavior in C, which `extern` things are supposed to mimic as I understand it.

**Comment by Vexu** [comment]
Allowing self-dependency won't affect translate-c since enum values are translated as numeric constants. If you just care about the length fields those can be better translated as namespaced constants:
```zig
// A type for character kinds.
const CharKind = enum {
    none,
    // Lowercase letters
    lower,
    lower_b,
    lower_x,
    // Uppercase letters
    upper,
    // Operators
    oper,
    oper_dash,
    oper_gt,
    oper_lt,

    // +1 added to get same value as in C
    const lower_length = @enumToInt(CharKind.lower_x) + 1;
    const upper_length = @enumToInt(CharKind.upper) + 1;
    const oper_length = @enumToInt(CharKind.oper_lt) + 1;
    const length = oper_length;
};

test "" {
    inline for (@typeInfo(CharKind).Enum.fields) |f| {
        @compileLog(f.name, f.value);
    }
    @compileLog(CharKind.lower_length);
    @compileLog(CharKind.upper_length);
    @compileLog(CharKind.oper_length);
    @compileLog(CharKind.length);
}
```

**Comment by davidgarland** [comment]
Wonderful, that solves my problem. I'll leave whether or not to close this up to you, as I think @eriksik2 makes a fine point, though I don't tend to use those kind of codegen tools myself.
