### ISSUE TITLE
Zig cc fails to link hello world

### ISSUE THREAD

**Issue by 0syf3r** [ziglang/zig#5860]
Version: 0.6.0

test.cpp:
`int main() {return 0;}`

Command:
`zig cc -o test test.cpp`

Output:
`ld: error: undefined symbol: vtable for __cxxabiv1::__function_type_info
>>> referenced by test.cpp
>>>               zig-cache/o/ljN2aAmAvh4SaCfziHkjTn_ItabwOY3fDqgnAeJ8Z6XrBGeXWbxnycGVTNBMcBdc/test.o:(typeinfo for int ())
the vtable symbol may be undefined because the class is missing its key function (see https://lld.llvm.org/missingkeyfunction)
`

**Comment by 0syf3r** [comment]
Interestingly, calling
`zig clang -o test test.cpp`
works fine.

**Comment by wozeparrot** [comment]
For compiling c++ code you need to use `zig c++`, so `zig c++ -o test test.cpp`.

**Comment by 0syf3r** [comment]
There really should be some documentation for this.
