### ISSUE TITLE
Zig cc not linking shared libraries correctly

### ISSUE THREAD

**Issue by ccoverstreet** [ziglang/zig#5861]
Version 0.6.0

- Files/
  - foo.c
  - foo.h
  - main.c

Running `zig cc -fPIC -c foo.c -o foo.o` and `zig cc -shared foo.o -o libbar.so` successfully creates a shared library; however, when trying to link to the library, `zig cc main.c -L. -lbar -o driver`, the wrong name is used (libfoo.so.0). It seems like Zig cc uses the first object file of the library instead of the name of the shared library. 

This code works fine if I change `zig cc -shared foo.o -o libbar.so` to `zig cc -shared foo.o -o libfoo.so`.

**Comment by kubkon** [comment]
Hmm, I think this might be Elf specific since I cannot replicate the behaviour with MachO minus using `libbar.dylib` instead of `.so`.

**Comment by LemonBoy** [comment]
> Hmm, I think this might be Elf specific since I cannot replicate the behaviour with MachO minus using libbar.dylib instead of .so.

It is ELF-specific, the linker invocation done by Zig always includes the `-soname` flag set to the root object name (`foo.o` here).
Setting the SONAME should be opt-in and not opt-out, double so if you consider `zig cc` should behave as `cc` does and the latter _doesn't_ set it behind your back.

**Comment by kubkon** [comment]
Good point! I agree with it being an opt-in rather than opt-out, especially if this means we're better aligned with `cc`.

**Comment by andrewrk** [comment]
Fixed in 9268972ff942f1d9db8fd0b89a8efe528d67e930, cherry-picked into 0.7.x in f09f960ce44ef00c4c05be5919068790898cc049
