### ISSUE TITLE
support iOS and Unity binding just like Dlang

### ISSUE THREAD

**Issue by sekkit** [ziglang/zig#5862]
D has a unity binding^^
https://github.com/Superbelko/unity-d
 
also please support AOT compilation on iOS just like C/C++ does.

**Comment by Sobeston** [comment]
All zig compilation is AOT compilation.

As for unity bindings: if they expose a set of C functions, then they should be easily accessible from zig. If this isn't the case then you might be out of luck.

**Comment by sekkit** [comment]
> All zig compilation is AOT compilation.
> 
> As for unity bindings: if they expose a set of C functions, then they should be easily accessible from zig. If this isn't the case then you might be out of luck.

I know it, but I hope zig can compile on iOS platform without issue.

**Comment by Sobeston** [comment]
IOS support is planned, but I'm not sure if anyone's managed to do that yet.
