### ISSUE TITLE
Enable discussions for the organization

### ISSUE THREAD

**Issue by data-man** [ziglang/zig#5869]
Example: https://github.com/nlohmann/json/discussions

Just the idea. :)

----
Attempt to improve №2 (after #3905) :)

**Comment by andrewrk** [comment]
I'm personally not interested in starting another place for another community to gather, I think I would like to keep this GitHub page for tracking the technical aspects of the project. What I like about the other spaces people gather is that they can be separately moderated by people who are not me :)

If you want to try this, I suggest to create your own repo and start your own github discussions, and then you can link to it on https://github.com/ziglang/zig/wiki/Community. There is no "official" community.
