### ISSUE TITLE
Compiler intelligence: Pointers to comptime data should not be accessible at runtime

### ISSUE THREAD

**Issue by EleanorNB** [ziglang/zig#5874]
This means, in the ideal case, the following code should not compile:
``` zig
pub fn testing123() void {
    comptime var value: u32 = 3;
    const pointer = &value;
    var bad = pointer; // this is an undefined address
}
```
To detect this, we'd either need to make sure that the value of `pointer` never gets passed to codegen (ideal, hard), or that `pointer` reads as null in codegen (good enough, easy).

**Comment by Vexu** [comment]
Should be covered by #1487, #2710 and #3996.

**Comment by EleanorNB** [comment]
Not quite -- the issue may be the same, but the proposed solution is different.
