### ISSUE TITLE
Inconsistency in Allocator API

### ISSUE THREAD

**Issue by SamTebbs33** [ziglang/zig#5878]
There is an inconsistency in the Allocator API documentation with regards to returning errors from `resize`. From line 77 in lib/std/mem.zig it says that returning OutOfMemory when new_len <= old_len is allowed. However shrinkBytes from line 59 assumes that this cannot happen. From a user's perspective it is desired to be able to return an error in the case that the shrinking operation isn't useful, so it would be good to clear up the inconsistency.

**Comment by andrewrk** [comment]
Not a good enough bug report to keep open
