### ISSUE TITLE
websocket support in the standard library

### ISSUE THREAD

**Issue by ThatTonybo** [ziglang/zig#5883]
Does Zig have support for either of these protocols? Specifically for making API requests and communicating with websocket servers as a client

**Comment by Sobeston** [comment]
HTTP is still a TODO for the standard library.

Some libraries for these things, in no particular order:
https://github.com/truemedian/hzzp
https://github.com/Vexu/routez
https://github.com/truemedian/wz
https://github.com/ducdetronquito/h11

Related:
https://github.com/MasterQ32/zig-bearssl/
https://github.com/MasterQ32/zig-network/

**Comment by andrewrk** [comment]
http covered by #910 #2007

**Comment by andrewrk** [comment]
Nope, will not be in the standard library.

**Comment by PaperPrototype** [comment]
> Nope, will not be in the standard library.

That is kinda sad, cause golang has support for it (but then again golang is used by google so)
