### ISSUE TITLE
Issue translating raylib.h, unexecpted token Id{ .LBrace = void }

### ISSUE THREAD

**Issue by creikey** [ziglang/zig#5887]
Full file in question: https://github.com/raysan5/raylib/blob/7ef114d1da2c34a70bba5442497103441647d8f3/src/raylib.h

Isolated snippet that reproduces the error ( from line 118 to 128 ):
```C
// NOTE: MSC C++ compiler does not support compound literals (C99 feature)
// Plain structures in C++ (without constructors) can be initialized from { } initializers.
#if defined(__cplusplus)
    #define CLITERAL(type)      type
#else
    #define CLITERAL(type)      (type)
#endif

// Some Basic Colors
// NOTE: Custom raylib color palette for amazing visuals on WHITE background
#define LIGHTGRAY  CLITERAL(Color){ 200, 200, 200, 255 }   // Light Gray
```
Translate error of interest:
`pub const LIGHTGRAY = @compileError("unable to translate C expr: unexpected token Id{ .LBrace = void }");`

**Comment by creikey** [comment]
Something that I don't really understand is why zig doesn't run the preprocessor before translating the C?

**Comment by Vexu** [comment]
Zig does run the preprocessor before translating the C (well clang does), but doing so won't turn these macros into C expressions, it only expands them when they are used somewhere.
