### ISSUE TITLE
Packed struct causes LLVM error

### ISSUE THREAD

**Issue by 0syf3r** [ziglang/zig#5890]
Version:
`zig-linux-x86_64-0.6.0+01ab167ce`
`3cdc0f1` is currently Master, but it's just a doc change so this issue still applies.

`test.zig`:
```
pub const V3 = packed struct {
    x: f32,
    y: f32,
    z: f32,

    pub fn sum(u: V3, v: V3) V3 {
        return .{.x = u.x + v.x,
                 .y = u.y + v.y,
                 .z = u.z + v.z};
    }
};


pub const Q = packed struct {
    v: V3,

    pub fn foo(q: Q) Q {
       return .{.v = q.v.sum(q.v)};
    }
};

pub fn main() void {
    const q = Q {.v = .{.x = 0, .y = 0, .z = 0}};
    const x = q.foo();
}
```

Command:
`zig build-exe test.zig`

Output:
```
broken LLVM module found: Call parameter type does not match function signature!
  %5 = bitcast [16 x i8]* %4 to i128*, !dbg !18950
 %V3*  call fastcc void @V3.sum(i128* sret %5, %V3* %3, %V3* %2), !dbg !18954

This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
Aborted (core dumped)
```

If I remove `packed` from the declaration of `struct Q`, then it compiles just fine.

**Comment by fengb** [comment]
This is most likely another manifestation of packed structs trying to pad to ABI:
- https://github.com/ziglang/zig/issues/2784
- https://github.com/ziglang/zig/issues/2627

The compiler has a bug where it thinks V3 is both 24 bits wide and 4 bytes wide.

**Comment by Vexu** [comment]
Fixed in self-hosted, tested in `test/behavior/packed-struct.zig:test "nested packed struct field access test"`.
