### ISSUE TITLE
sa_sigaction doesn't build on FreeBSD

### ISSUE THREAD

**Issue by jbeich** [ziglang/zig#5892]
I'm trying to build https://github.com/ifreund/river/ but it fails due to borked translation of `struct sigaction`. Unlike DragonFly `siginfo_t` is not defined, so FreeBSD uses `__siginfo` but... it's also not defined.
```zig
$ cat test.zig
const std = @import("std");

pub fn main() anyerror!void {
    var foo = std.os.Sigaction{
        .sigaction = null,
        .mask = std.os.empty_sigset,
        .flags = 0,
    };
}

$ zig build-exe test.zig
/usr/local/lib/zig/std/os/bits/freebsd.zig:745:35: error: use of undeclared identifier '__siginfo'
        __sa_sigaction: fn (i32, *__siginfo, usize) callconv(.C) void,
                                  ^
/usr/local/lib/zig/std/os/bits/freebsd.zig:743:5: note: while checking this field
    __sigaction_u: extern union {
    ^
./test.zig:4:31: note: referenced here
    var foo = std.os.Sigaction{
                              ^
```
https://github.com/ziglang/zig/blob/cc3bceea3de67f24e6c17d4c04a34a2301e097f8/lib/std/os/bits/freebsd.zig#L740-L753
https://github.com/ziglang/zig/blob/cc3bceea3de67f24e6c17d4c04a34a2301e097f8/lib/std/os/bits/dragonfly.zig#L520-L527

**Comment by tetsuo-cpp** [comment]
I'm on a FreeBSD VM so I'll take a look at this.
