### ISSUE TITLE
Single Open Intermediate Language (SOIL) Initiative

### ISSUE THREAD

**Issue by sirinath** [ziglang/zig#5915]
I came across the [SOIL-initiative](http://soil-initiative.org/) which aims to create a Single Open Intermediate Language. I believe perhaps if there is a collaboration with this initiative it might be of mutual benefit for this project also. This can help further research in IR, optimisation of IR, better targeting of web and other platforms, inter-language operability, etc.

**Comment by EleanorNB** [comment]
Reading their main page, they're not designing their own language, they're working with and advocating for WebAssembly. Not really much we can do with that.

**Comment by ShalokShalom** [comment]
As an F# advocate can I tell you that .NET had been designed from the ground up to support multiple different languages.

**Comment by Sobeston** [comment]
They're advocating for and want to design an IR, which is like an extended version of wasm, which can provide guarantees as to the safety of memory access. It seems this website has been around for almost a year, and I don't see indicators of progress; nothing on their website or paper makes me think that they have anything to show.

If SOIL takes off then sure why not - all it would likely take is a backend for it, but I don't think there's anything actionable for the foreseeable future.

**Comment by sirinath** [comment]
I believe there are 81 contributors to one of their proposals: https://github.com/soil-initiative/stacks

**Comment by andrewrk** [comment]
I don't see anything actionable here
