### ISSUE TITLE
Proposal: Chaining operator

### ISSUE THREAD

**Issue by EleanorNB** [ziglang/zig#5916]
This will be convenient syntax sugar, especially for multiply failable operations:
``` zig
try (try (try thing.a()).b()).c();
```
becomes
``` zig
thing -> try _.a() -> try _.b() -> try _.c();
```
I propose that we require `_` somewhere in the receiver, to place the payload. More flexible that way.

As for the exact syntax, I personally like `->` since it's light and clearly communicates the meaning -- however that might have problems with `anyframe`. Elixir has `|>`, Haskell has `>>=`, there are options.

**Comment by marnix** [comment]
Why not have `expr.try` be alternative syntax to `try expr`? That would allow `a().try.b().try.c().try.d().try`, or whatever.

**Comment by marnix** [comment]
Why not have `expr.try` be alternative syntax to `try expr`? That would allow `a().try.b().try.c().try.d().try`, or whatever.

**Comment by EleanorNB** [comment]
This proposal is both more general and less syntactically strange.

**Comment by zzyxyzz** [comment]
I don't think function chaining works very well in imperative languages. In Haskell it is idiomatic, but Haskell also has a lot of supporting machinery to make it more flexible (compact lambda notation, currying, sections, utility functions such as `flip`, etc.).

In Zig, simple method chaining can be used where applicable. Where not applicable, as in your example, I would suggest to simply be more verbose:

```Zig
const x = try thing.a();
const y = try x.b();
const z = try y.c();
```

This has the disadvantage of introducing spurious names, but makes control flow more explicit.

Or maybe you can convince Andrew to introduce a `.!` operator as a shorthand for `try`. Then your example would be `thing.a().!.b().!.c().!`, though I'm not sure this is actually a good idea.

**Comment by zzyxyzz** [comment]
To elaborate, what I mean by "does not work very well", is that function chaining is really neat if and only if there is a clean chain of single-argument functions that are applied in order. For example,

```zig
print(sin(cos(tan(x))));
```

could become

```julia
x |> tan |> cos |> sin |> print
```

and some people might prefer that. But if the expression is changed even slightly, such as

```zig
print(sin(1 + cos(tan(x))))
```

Then the function-chaining style can no longer be used and you have to go back to the ordinary expression (unless you have Haskell-style sections or are willing to create a lambda just to add 1). The same goes for when you need to include a function with more than one parameter, switch between function and method syntax, `try` something, access a struct member, etc.

The point is, a function chaining operator is a very specific kind of syntactic sugar that works only in very specific situations and requires even more syntactic sugar to be made more general (such as the suggested `_` placeholder, which Scala has and which has been [debated to death in Julia](https://github.com/JuliaLang/julia/pull/24990)).

Overall, I feel that introducing multiple pieces of special syntax for function chaining is convenient in some cases, but goes strongly against Zig's minimalism and explicitness, not to mention the "One Way To Do It" principle.

**Comment by zseri** [comment]
I would like to mention an even more general alternative, solely for avoiding temporary variable names.
Where a "backreference" to a previous result in the pipeline is denoted by a `$`, followed by the amount of backward steps.
e.g.
(example 1)
```zig
try (try (try thing.a()).b()).c();
// would turn into
thing.a() |> (try $0).b() |> (try $0).c()
```
(example 2)
```zig
const x0 = a + 1;
const x1 = x0 * a + 2;
const x2 = x1 * a - x0 + x1;
// would turn into
const x2 = a
  |> ($0 + 1)
  |> ($0 * $1 + 2)
  |> ($0 * $2 - $1 + $0)
```
(example 3)
```zig
const A = struct {
  x: u32,
};
const B = struct {
  y: u32,
  pub fn agoer(self: *@This(), a: *const A) void {
    self.y += a.x;
  }
};

var b = B { .y = 2; };

// the following
const a = A { .x = 1; };
b.agoer(&a);

// is equivalent to
A { .x = 1; } |> b.agoer(&$0)
```

**Comment by zseri** [comment]
I would also like to mention that imo it wouldn't be a problem if it was possible to disable variable shadowing for single variables at a time,e.g.
```zig
@allowShadowing(iter);
const iter  = iters.arrayIter(&a);
const iter = iters.filter(iter, &refval, filtprop);
const iter = iters.map(iter, &null, mapop);
```

**Comment by nektro** [comment]
one use case this proposal would vastly simplify is when you want to perform the same handling for many consecutive calls.

the following deals with optionals but `orelse`/`catch` are in principle doing very similar things

```zig
fn openHomeDir() !std.fs.Dir {
    const uid = std.os.linux.getuid();
    const f = try std.fs.openFileAbsoluteZ("/etc/passwd", .{});
    defer f.close();
    const passwd = try f.readToEndAlloc(gpa, 10_000_000);
    defer gpa.free(passwd);

    var lines = std.mem.split(u8, passwd, "\n");
    while (lines.next()) |line| {
        if (line.len == 0) continue;
        // name:password:UID:GID:GECOS:directory:shell
        var fields = std.mem.split(u8, line, ":");
        _ = fields.next() orelse return error.UnexpectedEol; // name
        _ = fields.next() orelse return error.UnexpectedEol; // password
        const line_uid = fields.next() orelse return error.UnexpectedEol; // UID
        _ = fields.next() orelse return error.UnexpectedEol; // GID
        _ = fields.next() orelse return error.UnexpectedEol; // GECOS
        const line_direcotry = fields.next() orelse return error.UnexpectedEol; // directory
        _ = fields.next() orelse return error.UnexpectedEol; // shell
        if (fields.next() != null) return error.LineTooLong;

        if (uid == try std.fmt.parseInt(u32, line_uid, 10)) return std.fs.openDirAbsolute(line_direcotry, .{});
    }

    return error.UidNotFound;
}
```

vs

```zig
fn openHomeDir() !std.fs.Dir {
    const uid = std.os.linux.getuid();
    const f = try std.fs.openFileAbsoluteZ("/etc/passwd", .{});
    defer f.close();
    const passwd = try f.readToEndAlloc(gpa, 10_000_000);
    defer gpa.free(passwd);

    var lines = std.mem.split(u8, passwd, "\n");
    while (lines.next()) |line| {
        if (line.len == 0) continue;
        // name:password:UID:GID:GECOS:directory:shell
        var fields = std.mem.split(u8, line, ":");
        const line_uid = fields.next() .next() .next() orelse return error.UnexpectedEol; // name:password:UID
        const line_direcotry = fields.next() .next() .next() orelse return error.UnexpectedEol; // GID:GECOS:directory
        _ = fields.next() orelse return error.UnexpectedEol; // shell
        if (fields.next() != null) return error.LineTooLong;

        if (uid == try std.fmt.parseInt(u32, line_uid, 10)) return std.fs.openDirAbsolute(line_direcotry, .{});
    }

    return error.UidNotFound;
}
```
