### ISSUE TITLE
Android: lld: error: undefined symbol: __emutls_get_address

### ISSUE THREAD

**Issue by meme** [ziglang/zig#5921]
Seems that Android support has regressed, testing with Android NDK r20, the following missing symbol error occurs (presumably there are more):

```
lld: error: undefined symbol: __emutls_get_address
>>> referenced by debug.zig:253 (/zig/lib/std/debug.zig:253)
>>>               ./sample.o:(std.debug.panicExtra)
>>> referenced by debug.zig:255 (/zig/lib/std/debug.zig:255)
>>>               ./sample.o:(std.debug.panicExtra)
>>> referenced by debug.zig:284 (/zig/lib/std/debug.zig:284)
>>>               ./sample.o:(std.debug.panicExtra)
```

---

Can reproduce as follows (995fd7314cd230ca7c829bb478f88b1ab7efd7b4):
```
zig build-exe -target aarch64-linux-android --libc aarch64-linux-android.txt sample.zig
```
`aarch64-linux-android.txt`:
```
include_dir=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
sys_include_dir=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
static_crt_dir=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/
crt_dir=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/21

msvc_lib_dir=
kernel32_lib_dir=
```

Can't assign myself to an issue, but I'm taking a look at this currently. Question for the team though: **how can we prevent regressions like this in the future**?

**Comment by meme** [comment]
Since Zig implements its own [`compiler_rt`](https://github.com/ziglang/zig/tree/5929e5ca0ebde636dd69d52d648df8cff59e6d96/lib/std/special/compiler_rt) does this functionality need to be added to Zig, or are we better off using LLVM's as a reference implementation: https://github.com/llvm/llvm-project/blob/master/compiler-rt/lib/builtins/emutls.c#L378 and implementing it ourselves? I feel like we should be linking against the NDK's runtime...

**Comment by FireFox317** [comment]
@meme Yes, this should indeed be added to the compiler_rt of Zig. Basically the compiler_rt of Zig is ported from the LLVM implementation of the compiler_rt, but we have increased safety checks, because it is written in Zig. :)

**Comment by meme** [comment]
OK, a few problems after reading into this implementation:
1) It requires a GPA to expand the TLS table, there appears to be no allocator functionality in Zig's compiler_rt at this time
2) Uses `pthread` to store a thread-local pointer to the TLS

This is going to be a pain to implement, and we're probably going to have to cut corners to do it. I think getting Android to be plug-and-play again when linking against `libc` should be done first, then we can tackle the static Android binary situation.

**Comment by Hardebayho** [comment]
Please how do we apply this fix? this undefined symbol still exists when trying to build for android

**Comment by desttinghim** [comment]
I don't think this issue has been resolved yet. `compiler_rt` doesn't expose `__emutls_get_address` unless the platform is openbsd, so android binaries still do not export it. Getting this working means adding android as an os target, and then exporting the symbol.

**Comment by semarie** [comment]
isn't possible to simply match on `target.abi == .android` and export the symbol ?

**Comment by desttinghim** [comment]
Yes, I think that would do it
