### ISSUE TITLE
translate-c cannot parse c-style cast to unsigned long

### ISSUE THREAD

**Issue by he-la** [ziglang/zig#5928]
translate-c fails to parse this:
```
cases.add("macro unsigned int cast",            
    \\#define CURLAUTH_BASIC ((unsigned long) 1)
, &[_][]const u8{                               
    \\pub const CURLAUTH_BASIC = @as(c_long, 1);
});                                             
```
with
```
@compileError("unable to translate C expr: expected ')'' instead got: Keyword_long");
```

This seems to be caused by translate-c handling the `unsigned` keyword as the c shorthand for `unsigned int`:
```
.Keyword_unsigned => return transCreateNodeIdentifierUnchecked(c, "c_uint"), // translate-c.zig:5696
```

It looks like this is a known issue: `// eventually this will be replaced by std.c.parse which will handle these correctly` which is also mentioned in #4168; perhaps we should create an issue to track moving to `std.c.parse`?

**Comment by Vexu** [comment]
#4045 is the issue for `std.c.parse`.
