### ISSUE TITLE
Compiling a C file for a UEFI target results in unsupported option '-fPIC'

### ISSUE THREAD

**Issue by alexnask** [ziglang/zig#5935]
This happens with both `zig cc` and `--c-source` regardless of the ABI used (tested with `msvc`, `gnu`, `macabi`, `itanium`)  

Current workaround is to target `windows` instead of `uefi`
The resulting clang triple is `x86_64-unknown-windows-<ABI>` and `-fPIC` is unsupported for the `windows` system.  

`-fno-PIC` results in `--disable-pic is incompatible with target 'x86_64-uefi-<ABI>'` because UEFI targets have `target_requires_pic == true`  

I'm not sure if the correct solution is to remove `-fPIC` by default for UEFI targets or change the resulting clang triple.

**Comment by alexrp** [comment]
This has since been fixed in stage2.
