### ISSUE TITLE
hello.zig fails to compile

### ISSUE THREAD

**Issue by simonhf** [ziglang/zig#5938]
Hello! I'm a zig newbie and having difficulties running hello.zig [1] and get the following error:

```
$ time zig build-exe hello.zig
Semantic Analysis [616/857] ./hello.zig:4:38: error: no member named 'writer' in struct 'std.fs.file.File'
    const stdout = std.io.getStdOut().writer();
                                     ^
/usr/lib/zig/0.6.0/lib/zig/std/start.zig:253:40: note: referenced here
            const result = root.main() catch |err| {
                                       ^
real    0m0.570s
```

FYI I installed a pre-compiled zig binary on Ubuntu 19.10 by following these instructions [2]:

```
$ zig version
0.6.0
```

[1] https://ziglang.org/documentation/master/
[2] https://github.com/dryzig/zig-debian/blob/master/README.md#configuration

**Comment by Luukdegram** [comment]
outStream() was deprecated in favor of writer() post 0.6.0
You can either use outStream() if you prefer to use 0.6.0, but I'd suggest upgrading to master.

**Comment by Vexu** [comment]
0.6.0 docs are here: https://ziglang.org/documentation/0.6.0/
Master branch version can be downloaded from here: https://ziglang.org/download/

The issue tracker is dedicated to bugs and proposals so for further questions please use one of the Zig communities: https://github.com/ziglang/zig/wiki/Community

**Comment by simonhf** [comment]
Thanks for the quick reply! FYI I initially tried to install Zig by compiling from sources but cmake requires LLVM v10 and Ubuntu 19.10 only comes with LLVM v9, and there seems to be no low-hanging-fruit way to install LLVM v10 on Ubuntu 19.10 :-( That's why I went for the latest Zig pre-compiled binary... which it seems is already out-of-date. Just giving you my newbie experience feedback in case this helps!

**Comment by alexnask** [comment]
You can install LLVM10 [here](https://apt.llvm.org/) but I would still recommend the website download.  
It updates automatically when a master branch commit successfully passes the tests on the CI servers so you shouldn't have this issue if you download the `master` build and not the `0.6.0` build :)
