### ISSUE TITLE
NtFsControlFile vs NtDeviceIoControlFile

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#5944]
@daurnimator
> When would you want to use `NtFsControlFile` vs `NtDeviceIoControlFile`?
> I've always used the latter (but without a good reason)

@kubkon
> That's an excellent question, thanks @daurnimator! Originally I wanted to use `NtDeviceIoControlFile` but trial-and-error, and the docs revealed that for reparse points processing we should use `NtFsControlFile` which is similar to `NtDeviceIoControlFile` but specifically targets filesystem drivers. Also according to [docs](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntfscontrolfile#remarks), we should use it to read/set/update reparse points, and any IO control code starting with `FSCTL_xxx`.

_From https://github.com/ziglang/zig/pull/5937#issuecomment-664891363_

**Comment by daurnimator** [comment]
@kubkon copying my comment from discord to here:

> I recall issues with using ntdll `NtDeviceIoControlFile` directly with AFD instead of `DeviceIoControl`

> from https://doxygen.reactos.org/d3/d74/deviceio_8c.html :
> ```C
>      /* Check what kind of IOCTL to send */
>      FsIoCtl = ((dwIoControlCode >> 16) == FILE_DEVICE_FILE_SYSTEM);
> ```
> ```C
>          /* Send file system control? */
>          if (FsIoCtl)
>          {
>              /* Send it */
>              Status = NtFsControlFile(hDevice,
>                                       lpOverlapped->hEvent,
>                                       NULL,
>                                       ApcContext,
>                                       (PIO_STATUS_BLOCK)lpOverlapped,
>                                       dwIoControlCode,
>                                       lpInBuffer,
>                                       nInBufferSize,
>                                       lpOutBuffer,
>                                       nOutBufferSize);
>          }
>          else
>          {
>              /* Otherwise send a device control */
>              Status = NtDeviceIoControlFile(hDevice,
>                                             lpOverlapped->hEvent,
>                                             NULL,
>                                             ApcContext,
>                                             (PIO_STATUS_BLOCK)lpOverlapped,
>                                             dwIoControlCode,
>                                             lpInBuffer,
>                                             nInBufferSize,
>                                             lpOutBuffer,
>                                             nOutBufferSize);
>          }
> ```

**Comment by kubkon** [comment]
That looks about right! I think this is exactly what we want as part of Zig high-level wrapper in `std.os.windows`.
