### ISSUE TITLE
"This is a bug in the Zig compiler"

### ISSUE THREAD

**Issue by donaldcallen** [ziglang/zig#5947]
For reasons I've made clear elsewhere, I've suspended development of the project I was working on in Zig.

But I do want to make you aware that the last set of changes I made to my code now produce the following:
```
zig build-exe --main-pkg-path .. --single-threaded --object interface.o `pkg-config --libs gtk+-3.0` -L/usr/local/lib -L/usr/lib64 -lsqlite3 -lc newcash.zig
Code Generation [18/1451] newcash.book.create_accounts_window...when analyzing /home/dca/Software/newcash_zig/newcash/account.zig:430:42 in compiler source at /deps/zig/src/codegen.cpp:1813: assertion failed. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
```
Short of sending you a tar file with all my code, any suggestions for how to proceed? Perhaps a non-stripped version of the compiler so the missing stack trace can be obtained? Please advise.

**Comment by Sobeston** [comment]
I would recommend trying to greatly reduce the source code size while maintaining the bug, in order to get a minimal reproducible.

**Comment by pixelherodev** [comment]
There's a tool `creduce` which has been reported to work with Zig, if I
remember correctly.

**Comment by donaldcallen** [comment]
I am attaching a gzipped tar file of the application I was developing that causes this error. Just untar, cd newcash and make. I just verified that the error still occurs with the 2020-08-05 zig-linux-x86_64-0.6.0+cf4936bcb.tar.xz version.

[newcash.tar.gz](https://github.com/ziglang/zig/files/5029550/newcash.tar.gz)

**Comment by Vexu** [comment]
@donaldcallen I can't build that because the archive doesn't contain whatever is in `../zlib/zlib.zig` and `../zlib/gtk.zig`.

**Comment by donaldcallen** [comment]
Sorry. A tar of the zlib directory is attached.
[zlib.tar.gz](https://github.com/ziglang/zig/files/5070076/zlib.tar.gz)

**Comment by Vexu** [comment]
Fix:
```diff
--- a/account.zig
+++ b/account.zig
@@ -427,7 +427,8 @@ pub fn create_account_register(account_guid: [*:0]const u8, shares_p: bool, acco
             panic("create_account_register: failed to insert new account register in account_registers hashtable\n", .{});
 
         // Record information about the account in the descriptor
-        account_register.guid = mem.spanZ(account_guid);
+        var tmp = mem.spanZ(account_guid);
+        account_register.guid = tmp;
         account_register.shares_p = shares_p;
         account_register.window = g.gtk_window_new(g.GtkWindowType.GTK_WINDOW_TOPLEVEL);
         account_register.scrolled_window = g.gtk_scrolled_window_new(z.c_null, z.c_null);
```

Minimal repro:
```zig
pub fn panic(msg: []const u8, st: ?*@import("builtin").StackTrace) noreturn {
    while (true) {}
}
fn foo() [:0]const u8 {
    return undefined;
}
pub export fn entry() void {
    var guid: [*:0]const u8 = undefined;
    guid = foo();
}
```

**Comment by donaldcallen** [comment]
Let me be sure I understand your previous message, which provides a "fix", but also labels this a bug, which it clearly is -- the compiler told us that.

What you called a fix, I would call a workaround. So I'm assuming that your intent was to show me how to change my code to get back on the air, but you are acknowledging that there is a compiler issue here that needs to be addressed. Correct?

In any case, thank you for the response.

**Comment by Vexu** [comment]
Yes I meant to say workaround.
