### ISSUE TITLE
Proposal: Reserved bit fields

### ISSUE THREAD

**Issue by mattnite** [ziglang/zig#5954]
Similar to how we can explicitly ignore return values, it might be nice to be able to simply use `_` to signify an ignored bitfield. I could only see this being useful with special function registers where they might have some funky bit layout.

Example:
```zig
pub const Cfg = packed struct {
    mode: u7,
    _: u5,
   val: u1,
    _: u3,
}
```
I've also used it here to make sure that the packed struct takes up exactly 16 bits.

**Comment by Vexu** [comment]
I think this would be a part of #4164.

**Comment by mattnite** [comment]
Ooh thanks, closing
