### ISSUE TITLE
json.StreamingParser u256 causes issues... sometimes

### ISSUE THREAD

**Issue by fengb** [ziglang/zig#5959]
Attempts at using expectEqual with any struct that contains the StreamingParser, LLVM crashes with "LLVM ERROR: Unsupported library call operation!"

```zig
// https://godbolt.org/z/ET8W9q
export fn foo() void {
    var parser: std.json.StreamingParser = undefined;
    std.testing.expectEqual(parser, parser);
}
```

The underlying problem is that `u256` is not fully supported by LLVM, but I am surprised that the currently tested path does not have any issues.

### Fixes

1. Downgrade to a 128 element stack — not ideal
2. Switch to PackedIntArray — might be (slightly) less performant due to increased bit ops
3. Fix LLVM? (https://github.com/ziglang/zig/issues/1485)
4. **Wait for stage2**

**Comment by daurnimator** [comment]
I'll be fixing this as part of my re-do of #5852
