### ISSUE TITLE
How is a literal left or right curly bracket included in a format string?

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#5977]

**Comment by pixelherodev** [comment]
{{ and }} if I remember correctly.

-- Email domain proudly hosted at https://migadu.com

**Comment by markfirmware** [comment]
That is what I thought except now {{ comes out as {{.

**Comment by andrewrk** [comment]
check the commit message here: https://github.com/ziglang/zig/commit/11d38a7e520f485206b7b010f64127d864194e4c

I welcome your comments

**Comment by markfirmware** [comment]
> check the commit message here: [11d38a7](https://github.com/ziglang/zig/commit/11d38a7e520f485206b7b010f64127d864194e4c)
> 
> I welcome your comments

Will do.

**Comment by EleanorNB** [comment]
What if you want to output something like `"{}, runtime_data"`? Argument count alone can't specify that.

**Comment by jayschwa** [comment]
> check the commit message here: [11d38a7](https://github.com/ziglang/zig/commit/11d38a7e520f485206b7b010f64127d864194e4c)
> 
> I welcome your comments

Runtime bloat is an important consideration for my current project (DOS support via "byo os" interfaces), but I ultimately decided to start the experiment because Zig is more of a stickler than C. I think `"{}", .{}` should produce a compile error for missing argument.

> however, at this point in the development
process of Zig I think that tradeoff is worthwhile.

Does this mean it will be reverted before 1.0?

**Comment by andrewrk** [comment]
> Does this mean it will be reverted before 1.0?

That was the idea. However if this is causing problems for you in practice, I would be happy to revert it now.

**Comment by jayschwa** [comment]
I have not shot my foot with this gun yet, but I believe that I will given enough time :laughing: 

The program I'm currently working on has a few arg-less prints. When I compare release-small builds with and without your commit, it makes no difference on the final executable size. I was little surprised at this, but I verified that `"{}", .{}` worked in one and bombed in the other. It seems for this particular case, I lose safety but gain nothing w.r.t. runtime performance.

**Comment by andrewrk** [comment]
Reverted. Apologies, that was a bit of a disruptive commit. I think it was unjustified for me to do that.

**Comment by markfirmware** [comment]
Thanks - I didn't have time yet to understand the rationale for the change, but I have become accustomed to the previous design.

**Comment by EleanorNB** [comment]
...Should we maybe reopen this?

**Comment by andrewrk** [comment]
@EleanorNB  The question is answered - what's the new topic?

**Comment by EleanorNB** [comment]
Well I just figured since you added it to 0.7.0 *after* it was closed, perhaps there's still actionable material.
