### ISSUE TITLE
Cannot link libcrypt

### ISSUE THREAD

**Issue by pfgithub** [ziglang/zig#5990]
Found by Tigor on discord

zig latest master version

gcc:
```
gcc test.c -lcrypt
ldd a.out
	linux-vdso.so.1 (0x00007ffcf005c000)
	libcrypt.so.1 => /usr/lib/libcrypt.so.1 (0x00007fb42b609000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fb42b442000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fb42b69e000)
```

zig cc:
```
zig cc test.c -lcrypt
ldd a.out
	linux-vdso.so.1 (0x00007ffd952f3000)
	libc.so.6 => /lib/libc.so.6 (0x00007f0e8ead3000)
	libm.so.6 => /lib/libm.so.6 (0x00007f0e8e98e000)
	libpthread.so.0 => /lib/libpthread.so.0 (0x00007f0e8e96c000)
	libdl.so.2 => /lib/libdl.so.2 (0x00007f0e8e966000)
	librt.so.1 => /lib/librt.so.1 (0x00007f0e8e95b000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f0e8ec9c000)
	libutil.so.1 => /lib/libutil.so.1 (0x00007f0e8e956000)
```
(libcrypt is missing)

glibc [does not provide crypt anymore](https://stackoverflow.com/questions/2565427/crypt-function-and-link-error-undefined-reference-to-crypt). target.cpp incorrectly identifies "crypt" as a libc lib name [here](https://github.com/ziglang/zig/blob/c4b9f5e52f3c45d4c88ba0f1768bc93eb6318040/src/target.cpp#L1235-L1236).

musl does provide crypt, so in musl crypt should continue to be counted as a libc library name.

**Comment by andrewrk** [comment]
-lcrypt support was added in 97c0e1cc41c24c6cbb60117751d5b82dcd9d0e43 and removed in 6b7ddfbafe7ff8f9bc9952f838737e8514c9b26b because it's a deprecated glibc feature. Status quo stance on this use case is: unsupported.

**Comment by McSinyx** [comment]
> Status quo stance on this use case is: unsupported.

Just to make sure that I understand this correctly, does it means that there is no way to use the POSIX crypt function at the moment, at least on glibc and musl?  Apparently `-lxcrypt` as suggested by @daurnimator works on neither [Arch](https://builds.sr.ht/~cnx/job/446685) nor Debian.

**Comment by andrewrk** [comment]
That's correct, although it is an easy decision to reverse. I just need to remind myself why I was convinced to revert the commit that added support (by digging through a previous discussion on github) and re-evaluate the decision.

**Comment by daurnimator** [comment]
>  I just need to remind myself why I was convinced to revert the commit that added support (by digging through a previous discussion on github) and re-evaluate the decision.

https://github.com/ziglang/zig/pull/7335#issuecomment-741412448
