### ISSUE TITLE
Compiler segfault on inline while loop

### ISSUE THREAD

**Issue by nagybogo** [ziglang/zig#6001]
Below is a reduction of a compiler segfault I came across today. This is reproducible with the most up to date master branch compiler, though I've only tried it on x86-64 Linux.

```
const std = @import("std");
pub fn main() !void {
    var tokens = std.mem.tokenize("Some sample text", " ");
    comptime var i: usize = 0;
    inline while (i < 3) : (i += 1) {
        if (tokens.next()) |t| {} else {
            return error.SomeKindOfError;
        }
    }
}
```
Then simply building with `zig build-exe main.zig` gives a segfault at "Code Generation [212/580] std.dwarf.LineNumberProgram.checkLineMatch...".

Removing `comptime` and `inline` fixes the segfault, as does removing the `else` branch of the `if` statement.

I'm not sure exactly how `std.mem.tokenize` is involved yet, but I tried replacing it with an array of optional ints that were checked in the while loop and this fixed the segfault.

**Comment by daurnimator** [comment]
Possible #2727 duplicate?
