### ISSUE TITLE
put constant data in .rodata section instead of .text

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#6029]

**Comment by andrewrk** [comment]
cc @kubkon - I noticed you mentioned this in your talk :-)

**Comment by watchpoints** [comment]
how

**Comment by Ersikan** [comment]
Hello ! 
I finally have some time back to contribute to Zig, and I'm excited to start working back on this issue.
Is there any new context on this issue I need to know before starting back working on it ? Who can I talk to if I have any questions on the ELF infrastructure ?

Is it possible to reopen my PR #8296 and put it in draft status, or should I create a new one ?
