### ISSUE TITLE
bug: anonymous nested tuples

### ISSUE THREAD

**Issue by cristobal-montecino** [ziglang/zig#6043]
```zig
const std = @import("std");

fn print(args: anytype) void {
    std.debug.print("{}\n", .{args});
}
fn three(a0: u64, a1: u64, a2: u64) void {
    print(.{.{a0, a1, a2}});
}

pub fn main() !void {
    three(1,2,3);
}
```
```
Segmentation fault at address 0x202740
/home/ce/example.zig:7:15: 0x236f28 in three (output.s)
/home/ce/example.zig:11:10: 0x22fd0b in main (output.s)
```
> [Try this code](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(fontScale:12,j:1,lang:zig,selection:(endColumn:2,endLineNumber:12,positionColumn:1,positionLineNumber:1,selectionStartColumn:2,selectionStartLineNumber:12,startColumn:1,startLineNumber:1),source:'const+std+%3D+@import(%22std%22)%3B%0A%0Afn+print(args:+anytype)+void+%7B%0A++++std.debug.print(%22%7B%7D%5Cn%22,+.%7Bargs%7D)%3B%0A%7D%0Afn+three(a0:+u64,+a1:+u64,+a2:+u64)+void+%7B%0A++++print(.%7B.%7Ba0,+a1,+a2%7D%7D)%3B%0A%7D%0A%0Apub+fn+main()+!!void+%7B%0A++++three(1,2,3)%3B%0A%7D'),l:'5',n:'0',o:'Zig+source+%231',t:'0')),k:50.5647422879799,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:ztrunk,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'1',trim:'1'),fontScale:14,j:1,lang:zig,libs:!(),options:'',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'zig+trunk+(Editor+%231,+Compiler+%231)+Zig',t:'0'),(h:executor,i:(argsPanelShown:'1',compilationPanelShown:'0',compiler:ztrunk,compilerOutShown:'0',execArgs:'',execStdin:'',fontScale:14,j:1,lang:zig,libs:!(),options:'',source:1,stdinPanelShown:'1'),l:'5',n:'0',o:'zig+trunk+Executor+(Editor+%231)+Zig',t:'0')),k:49.43525771202012,l:'4',n:'0',o:'',s:1,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

```zig
const std = @import("std");

fn print(args: anytype) void {
    std.debug.print("{}\n", .{args});
}
fn three(a0: u64, a1: u64, a2: u64) void {
    const args = .{a0, a1, a2};
    print(.{args});
}

pub fn main() !void {
    three(1,2,3);
}
```
```
struct:8:12{ .0 = struct:7:19{ .0 = 1, .1 = 2, .2 = 3 } }
```
> [Try this code](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(fontScale:12,j:1,lang:zig,selection:(endColumn:2,endLineNumber:13,positionColumn:2,positionLineNumber:13,selectionStartColumn:2,selectionStartLineNumber:13,startColumn:2,startLineNumber:13),source:'const+std+%3D+@import(%22std%22)%3B%0A%0Afn+print(args:+anytype)+void+%7B%0A++++std.debug.print(%22%7B%7D%5Cn%22,+.%7Bargs%7D)%3B%0A%7D%0Afn+three(a0:+u64,+a1:+u64,+a2:+u64)+void+%7B%0A++++const+args+%3D+.%7Ba0,+a1,+a2%7D%3B%0A++++print(.%7Bargs%7D)%3B%0A%7D%0A%0Apub+fn+main()+!!void+%7B%0A++++three(1,2,3)%3B%0A%7D'),l:'5',n:'0',o:'Zig+source+%231',t:'0')),k:50.5647422879799,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:ztrunk,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'1',trim:'1'),fontScale:14,j:1,lang:zig,libs:!(),options:'',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'zig+trunk+(Editor+%231,+Compiler+%231)+Zig',t:'0'),(h:executor,i:(argsPanelShown:'1',compilationPanelShown:'0',compiler:ztrunk,compilerOutShown:'0',execArgs:'',execStdin:'',fontScale:14,j:1,lang:zig,libs:!(),options:'',source:1,stdinPanelShown:'1'),l:'5',n:'0',o:'zig+trunk+Executor+(Editor+%231)+Zig',t:'0')),k:49.43525771202012,l:'4',n:'0',o:'',s:1,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

**Comment by edt-xx** [comment]
A data point.  The following code fragment will seg fault.  Changing the tuples with .{xxx} to .{"xxx"} and .{aaa} to .{"aaa"} works and the tuples are usable.  Looks like it might be something that occurs when the nested tuples have runtime values.

```fn gen() void {}
fn exactdiv() void {}
fn fanin() void {}
fn console() void {}

pub fn main() void {
    
var aaa:usize = 150;
var xxx:usize = 5;
    
const pipe =.{ 
    .{     gen, .{aaa} }, 
    .{"a", exactdiv, .{xxx} }, 
    .{"b", fanin}, 
    .{     console,   true}, 
    .{"a"},
    .{ exactdiv, .{7} }, 
    .{"b",              true} 
};

}

**Comment by andrewrk** [comment]
Fixed by deleting the stage1 codebase.
