### ISSUE TITLE
MacOS Big Sur Beta 4 issue on fresh install of zig: Unable to create builtin.zig: file not found

### ISSUE THREAD

**Issue by charlieroth** [ziglang/zig#6052]
Hi, new to zig here. Don't know if an easy solution to this issue exists considering I am running Big Sur Beta 4, which probably has very limited testing with zig, but if it can be resolved, it might be helpful for the future when public release of Big Sur comes.

Machine: MacBook Pro 2019
OS: MacOS Big Sur (11.0) Beta 4

Followed Homebrew install directions found [here](https://github.com/ziglang/zig/wiki/Install-Zig-from-a-Package-Manager), which installed `libffi` and `llvm` as deps

Output when trying to run [hello world](https://ziglang.org/#Zig-competes-with-C-instead-of-depending-on-it) program:
```
$ zig build-exe hello.zig
Unable to create builtin.zig: file not found
```

Any recommendations on how to proceed in order to get zig programs running?

Thanks!

**Comment by kubkon** [comment]
Thanks for the report @charlieroth and apologies for tending to it so late. If you update your homebrew installation, the Zig version currently in brew works fine on macOS 11 on `x86_64`.
