### ISSUE TITLE
Sentinel-terminated slices can be coerced to have a different sentinal value

### ISSUE THREAD

**Issue by dinglydo** [ziglang/zig#6054]
Discord Message: https://discordapp.com/channels/605571803288698900/719644313348341760/743954868175110194

Essentially, the documentation says the following:
> The syntax [:x]T is a slice which has a runtime known length and also guarantees a sentinel value at the element indexed by the length

However, in the following code snippet, you can see that it's **not** guaranteed:
```c
    const slice: [:1]const u8 = "hello";
    assert(slice.len == 5);
    assert(slice[5] == 0);
```
The assertions all pass. And even though the doc says that slices are guaranteed to have the sentinel value at index of its length, in the code, it clearly does not and instead has 0. Running LenZ prints out a much larger number, probably because it's sifting through junk memory.

From what I've learned and been told, sential-terminated slices should not be able to coerce into having another sentinal value.

As a final note, I'd like to say that the language has been really well made so far. Keep up the good work!

**Comment by Guigui220D** [comment]
I'm trying ot solve this issue, It's my first time trying to solve an issue in a big project like that.

I found this bit of code in ir.cpp at line 15545 (https://github.com/ziglang/zig/blob/master/src/ir.cpp#L15545)
It seems like the cast is accepted when the lengths are the same OR when the sentinel terminator is the same, shouldnt it only be casted if the sentinel terminator is the same? Why does the length matter in that case?

Here's the code because It won't display on the site : 
```zig
    // [:x]T to [*:x]T
    // [:x]T to [*c]T
    if (wanted_type->id == ZigTypeIdPointer && is_slice(actual_type) &&
        ((wanted_type->data.pointer.ptr_len == PtrLenUnknown && wanted_type->data.pointer.sentinel != nullptr) ||
         wanted_type->data.pointer.ptr_len == PtrLenC))
    {
        ZigType *slice_ptr_type = resolve_struct_field_type(ira->codegen,
                actual_type->data.structure.fields[slice_ptr_index]);
        if (types_match_const_cast_only(ira, wanted_type->data.pointer.child_type,
                slice_ptr_type->data.pointer.child_type, source_node,
                !wanted_type->data.pointer.is_const).id == ConstCastResultIdOk &&
            (slice_ptr_type->data.pointer.sentinel != nullptr &&
                (wanted_type->data.pointer.ptr_len == PtrLenC ||
                    const_values_equal(ira->codegen, wanted_type->data.pointer.sentinel,
                        slice_ptr_type->data.pointer.sentinel))))
        {
            TypeStructField *ptr_field = actual_type->data.structure.fields[slice_ptr_index];
            IrInstGen *slice_ptr = ir_analyze_struct_value_field_value(ira, source_instr, value, ptr_field);
            return ir_implicit_cast2(ira, source_instr, slice_ptr, wanted_type);
        }
    }
```

**Comment by Guigui220D** [comment]
Nevermind my last comment, it's not the right cast
