### ISSUE TITLE
Allow declarations with names that collide with primitive types when using @"" syntax

### ISSUE THREAD

**Issue by Vexu** [ziglang/zig#6062]
Originally from here: https://github.com/ziglang/zig/pull/6060#discussion_r471031125
Alternative to  #1802

```zig
const _ = 2; // error: `_` is not a declarable symbol
const @"_" = 2; // ok

const bool = 2; // error: variable shadows primitive type 'bool'
const @"bool" = 2; // ok
```

**Comment by tadeokondrak** [comment]
Would this work?
```zig
const @"bool" = 2;
const other: bool = false;
```
If not, shadowing a predefined type or identifier would make it impossible to use, since you couldn't even do
```zig
const my_bool = bool;
const @"bool" = 2;
const other: my_bool = false;
```
since top level decls are order-independent.

**Comment by Vexu** [comment]
It would make sense for them to be distinct since `bool` is a constant and allowing it to be modified by an alias would result in some really strange behavior.

**Comment by tadeokondrak** [comment]
> It would make sense for them to be distinct

Wouldn't the only way to implement that be the same as #1802?

**Comment by Vexu** [comment]
No. This works because the identifiers using the `@""` syntax are actually strings that need to be resolved first. The main difference between the two approaches is that this doesn't make them into keywords. This will be most noticeable in container fields where using `bool` will remain valid while the other proposal would require using `@"bool"`.

**Comment by andrewrk** [comment]
cc @ehaas - I believe some things you were doing were blocking on this.
