### ISSUE TITLE
notice more kinds of optimization flags and debug flags

### ISSUE THREAD

**Issue by xxxbxxx** [ziglang/zig#6091]
hello,

I stumbled uppon the fact that zig cc -O3 actually produces a debug build.  So I started to investigate:

there is some surprising behaviour when using -O options.

here is a trace of how zig parses this command line:
`zig c++ -O -O1 -O2 -O3 -O4 -Og -Ofast -O0 -Os -Oz   -g -g1 -gline-tables-only`

```
ClangArgIterator{ .zig_equivalent = .optimize, .only_arg = O,  othr[0]=-O       .... }, 
ClangArgIterator{ .zig_equivalent = .optimize, .only_arg = O1, othr[0]=-O1      .... }, 
ClangArgIterator{ .zig_equivalent = .optimize, .only_arg = O2, othr[0]=-O2      .... }, 
ClangArgIterator{ .zig_equivalent = .optimize, .only_arg = 3,  othr[0]=-O3      .... }, 
ClangArgIterator{ .zig_equivalent = .other,    .only_arg = O4, othr[0]=-O4      .... }, 
ClangArgIterator{ .zig_equivalent = .optimize, .only_arg = Og, othr[0]=-Og      .... }, 
ClangArgIterator{ .zig_equivalent = .optimize, .only_arg = ,   othr[0]=-Ofast   .... }, 
ClangArgIterator{ .zig_equivalent = .other,    .only_arg = O0, othr[0]=-O0      .... }, 
ClangArgIterator{ .zig_equivalent = .other,    .only_arg = Os, othr[0]=-Os      .... }, 
ClangArgIterator{ .zig_equivalent = .optimize, .only_arg = z,  othr[0]=-Oz      .... }, 

															                    
ClangArgIterator{ .zig_equivalent = .debug,    .only_arg = g,  othr[0]=-g       .... }, 
ClangArgIterator{ .zig_equivalent = .other,    .only_arg = g1, othr[0]=-g1      .... }, 
ClangArgIterator{ .zig_equivalent = .other,    .only_arg = gline-tables-only, othr[0]=-gline-tables-only  .... },
```

and the code from main.cpp:
```c++
case Stage2ClangArgOptimize:
    // alright what release mode do they want?
    if (strcmp(it.only_arg, "Os") == 0) {
        build_mode = BuildModeSmallRelease;
    } else if (strcmp(it.only_arg, "O2") == 0 ||
            strcmp(it.only_arg, "O3") == 0 ||
            strcmp(it.only_arg, "O4") == 0)
    {
        build_mode = BuildModeFastRelease;
    } else if (strcmp(it.only_arg, "Og") == 0 ||
            strcmp(it.only_arg, "O0") == 0)
    {
        build_mode = BuildModeDebug;
    } else {
        for (size_t i = 0; i < it.other_args_len; i += 1) {
            clang_argv.append(it.other_args_ptr[i]);
        }
    }
    break;
case Stage2ClangArgDebug:
    strip = false;
    if (strcmp(it.only_arg, "-g") == 0) {
        // we handled with strip = false above
    } else {
        for (size_t i = 0; i < it.other_args_len; i += 1) {
            clang_argv.append(it.other_args_ptr[i]);
        }
    }
    break;
```

So, I'm wondering..

- how was _clang_options_data.zig_ generated? can it be manually edited? how come there are some repeated options, (like standalone "O" for instance)? I reckon only the first match is used? 

- was '"O1" omitted on purpose? "Ofast"? "Os"? ..

 - shouldn't the ```clang_argv.append(it.other_args_ptr[i]);``` be outside of else branches, so that the user-given option is honored in addition to any zig tweaks?

**Comment by andrewrk** [comment]
>     * how was _clang_options_data.zig_ generated? 

https://github.com/ziglang/zig/blob/master/tools/update_clang_options.zig

> can it be manually edited?

No - it comes from a table in the clang project.

> how come there are some repeated options, (like standalone "O" for instance)? I reckon only the first match is used?

Legacy C compiler reasons, I guess.

>     * was '"O1" omitted on purpose? "Ofast"? "Os"? ..

No - looks like this logic could be improved by noticing more O flags.

>     * shouldn't the `clang_argv.append(it.other_args_ptr[i]);` be outside of else branches, so that the user-given option is honored in addition to any zig tweaks?

Idea here is that zig determines the zig optimization mode from the c compiler flags, and then uses that to decide what to pass to clang, rather than forwarding those options directly. This decision makes sense when you consider that some defaults are different with zig cc, such as enabling UBSAN by default.
