### ISSUE TITLE
Getting error while trying to print an error

### ISSUE THREAD

**Issue by scriptnull** [ziglang/zig#6094]
I am new to zig and this is my first zig program. Unsure where to ask, so asking it here.

I wrote a simple function that tries to open a file and return back a struct if success or an error if error. In the test, I am just calling that function (for a non-existing file), so the function should return back an error. When I try to catch that error and print it using `std.debug.warn`, I am getting an error that I am not sure about.

Here is my program:
```zig
const std = @import("std");

const DB = struct{
    path: []const u8,
    file: std.fs.File
};

fn open(path: []const u8) std.fs.File.OpenError!DB {
    var flags = std.fs.File.OpenFlags{
        .read = true,
        .write = true,
    };

    var file = try std.fs.openFileAbsolute(path, flags);

    return DB{
        .path = path,
        .file = file,
    };
}

test "creates DB file if not present while opening the database" {
    const db = open("/test1.db") catch |err| std.debug.warn("{}", .{err});
}
```

Here is the error that I am getting when I run the tests.
```
$ zig test src/main.zig 
./src/main.zig:27:34: error: incompatible types: 'void' and 'DB'
    const db = open("/test1.db") catch |err| std.debug.warn("{}", .{err});
                                 ^
./src/main.zig:27:60: note: type 'void' here
    const db = open("/test1.db") catch |err| std.debug.warn("{}", .{err});
                                                           ^
./src/main.zig:27:34: note: type 'DB' here
    const db = open("/test1.db") catch |err| std.debug.warn("{}", .{err});
```

Any idea on why I am getting this?

```
error: incompatible types: 'void' and 'DB'
```

**Comment by pedromsilvapt** [comment]
So, when you use `catch |err|` whatever you put in front is gonna be the value saved to `db`. And since std.debug.warn returns void, that is incompatible with DB. You can use return to exit the function immediately.

```zig
const db = open("/test1.db") catch |err| {
    std.debug.warn("{}", .{err});
    return;
};
```

**Comment by scriptnull** [comment]
Thank you! Closing this issue as it solves my problem and gives clarity.

**Comment by Vexu** [comment]
> Unsure where to ask, so asking it here.

There are a bunch of community gathering places: https://github.com/ziglang/zig/wiki/Community.
Discord and IRC are probably the best places to ask questions since they are the most active.
