### ISSUE TITLE
Function with while-loop containing a block and comptime var doesn't return

### ISSUE THREAD

**Issue by taishi132** [ziglang/zig#6136]
This is my first github issue so please advise me if I can improve my post.

```zig
fn test_func() void {
    comptime var k = 0;
    while (k < 3) : (k += 1) {
        const x: i32 = blk: {
            if (k > 2) {
                break :blk 1;
            } else {
                break :blk 2;
            }
        };
    }
}

test "comptime while block" {
    test_func();
}
```

In short, the above test enters an infinite loop and never returns. Removing the "blk" inside of the while-loop makes it not compile, with the following error message:
```
.\test.zig:3:5: error: control flow attempts to use compile-time variable at runtime
    while (k < 3) : (k += 1) {
    ^
.\test.zig:3:24: note: compile-time variable assigned here
    while (k < 3) : (k += 1) {
                       ^
.\test.zig:1:21: note: referenced here
fn test_func() void {
                    ^

```
Inlining the while-loop makes it compile and it also works as expected. Making `k` into something other than a comptime var also makes it work properly.

Using the following zig version: zig-windows-x86_64-0.6.0+243b5c7a8

**Comment by andrewrk** [comment]
Thanks, this is a nice bug report - easy to reproduce, easy to understand the problem. It may be some time before this gets solved, but this issue will remain open until that happens.

**Comment by Vexu** [comment]
Fixed in master.
