### ISSUE TITLE
specying build revision with cmake

### ISSUE THREAD

**Issue by Jan200101** [ziglang/zig#6149]
Zig changes a lot between releases so it is handy to make third party repos containing up to date Zig builds
but currently the build process will only append a hash if git is present and the directory is a git repo which for example [won't happen with rpm](https://stackoverflow.com/questions/48337127/can-the-source0-in-a-rpm-spec-be-a-git-repo)

for downstream packages I believe adding a `ZIG_REV` option is benefitial

**Comment by andrewrk** [comment]
This is done in build.zig but not for cmake.

https://github.com/ziglang/zig/blob/52ba2c3a43a88a4db30cff47f2f3eff8c3d5be19/build.zig#L106
