### ISSUE TITLE
zig fmt ignores single argument trailing commas in @builtins()

### ISSUE THREAD

**Issue by fengb** [ziglang/zig#6171]
Before:
```zig
@panic(foo,);
panic(foo,);
@panic(foo, bar,);
```

After:
```zig
@panic(foo);
panic(
    foo,
);
@panic(
    foo,
    bar,
);
```

**Comment by LemonBoy** [comment]
Oh I did that on purpose, but I see it's inconsistent with the normal function-call rules. Change [this](https://github.com/ziglang/zig/blob/fc001110b4f4c271217ae6ce973c80a33925ca3b/lib/std/zig/render.zig#L1484) line and you're good to go.
