### ISSUE TITLE
Winget package

### ISSUE THREAD

**Issue by msingle** [ziglang/zig#6173]
The [Windows Package Manager](https://docs.microsoft.com/en-us/windows/package-manager/)   ([github repo for the cli tool](https://github.com/microsoft/winget-cli) ) is Microsoft's new package manager (currently in previews).  It's very limited (it doesn't yet have the ability to update or get dependencies), but [the roadmap](https://github.com/microsoft/winget-cli/blob/master/doc/windows-package-manager-v1-roadmap.md) is available and includes that functionality. 

The [Community Repo](https://github.com/microsoft/winget-pkgs) doesn't seem to have zig listed. For namespace purposes (at least) it seems like there should be a Zig manifest to enable downloading zig with winget. As it gains more traction, I imagine having Zig available on Windows' default package manager will become more attractive.

The manifests that I've seen all use MSI (while a quick glance at zig's Chocolatey package show's it uses a powershell script to install the zip). A zip (in the appropriate directory) will probably be sufficient but needs some investigation.

I'm going to hack at a manifest, but am creating this as both a reminder to myself and to get feedback from others.

**Comment by msingle** [comment]
Ugh, according to the [manifest spec v1](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv0.1.md), zip isn't currently supported.  This looks like it will require creating a windows installer package.

**Comment by GoodClover** [comment]
> InstallerType is a required field.  Supported types are inno, wix, msi, nullsoft, zip, appx, msix and exe.

iirc Nullsoft (NSIS) can make an installer from a zip file, with an easy tool for simplifying this.
I have never used NSIS myself though so how good it is I can't say.

**Comment by andrewrk** [comment]
Sounds fun, here's the wiki page to update when you get it working: https://github.com/ziglang/zig/wiki/Install-Zig-from-a-Package-Manager
