### ISSUE TITLE
pub fn main() !noreturn crashes the compiler

### ISSUE THREAD

**Issue by WoodyAtHome** [ziglang/zig#6181]
```
pub fn main() !noreturn {
    while (true){

    }
}
```
then
`zig build-exe main.zig`

Sometimes the compiler gives an error, sometimes it doesn't stop on my machine and the hole machine is unusable. Only Power off helped.

zig version 0.6.0+fc001110b
ubuntu 20.04.1

**Comment by alexnask** [comment]
Duplicate of #3461
