### ISSUE TITLE
i64 to f32 conversion fails for target arm-linux-musleabihf

### ISSUE THREAD

**Issue by WoodyAtHome** [ziglang/zig#6188]
main.zig:
```
const std = @import("std");

pub fn main() !void {
    var number = @as(i64, 1);
    std.log.info("number = {}", .{@intToFloat(f32, number)});

    // this line works:
    //std.log.info("number = {}", .{@intToFloat(f64, number)});
}
```

`zig build-exe -target arm-linux-musleabihf main.zig`
or
`zig build-exe -target arm-linux-musleabi main.zig`

Error is:
Build Dependencies...lld: error: undefined symbol: __aeabi_l2f
>>> referenced by main.zig:5 (/home/woody/sources/zig/serialOnRasPi/src/main.zig:5)
>>>               ./main.o:(main)
>>> did you mean: __aeabi_ul2f
>>> defined in: /home/woody/.cache/zig/stage1/o/EnIeQMmY32ckVb5NkGN2yiyDO0Tnp_WLaRhdVibO3wViP4GfZqg21yVePfsH-5B0/libcompiler_rt.a(/home/woody/.cache/zig/stage1/o/EnIeQMmY32ckVb5NkGN2yiyDO0Tnp_WLaRhdVibO3wViP4GfZqg21yVePfsH-5B0/compiler_rt.o)

For my native target (x86_64-linux-musl) the linker finds all symbols.

zig version = 0.6.0+f6cedfaac

**Comment by daurnimator** [comment]
if you anyone feels like digging into this, its a missing function in `std/special/compiler_rt`.
You should be able to port the implementation from llvm's compiler_rt project.
