### ISSUE TITLE
@enumToInt can take enum literal

### ISSUE THREAD

**Issue by extrasharp** [ziglang/zig#6195]
Hate to just clutter things up with tiny issues, but it would be nice if you can do this:
```zig
const Enum = enum(usize) {
    Something,
};

pub fn main() void {
    const x: usize = @enumToInt(.Something);
}
```
Currently it's an error, I think enumToInt expects a value here.

**Comment by daurnimator** [comment]
How would you know which enum belongs to?
```zig
const Enum1 = enum(usize) {
    Something = 1,
};

const Enum2 = enum(usize) {
    Something = 2,
};

pub fn main() void {
    const x: usize = @enumToInt(.Something); // 1 or 2?
}
```

That's why you need to write e.g. `@enumToInt(Enum1.Something)` instead of just an enum literal.

**Comment by extrasharp** [comment]
Oh okay, confusion on my part.
I thought you could already so this with errors, with the ```error.ErrorName``` shorthand, but that actually creates a new error type, rather than "looking up which error .ErrorName belongs to".
That's fine then, thanks haha.
(For stuff like this i should really ask on discord first probably lol)
