### ISSUE TITLE
Proposal: Allow listing all exported declarations

### ISSUE THREAD

**Issue by pedromsilvapt** [ziglang/zig#6205]
### The Problem
If the user exports some symbol, there is no way currently to get the list of exported symbols, or the name given.
```zig
@export(StructName, .{ .name = "struct_name_t" });
```

This could be useful for example, when building a library, to allow the user to autogen bindings for other languages.

### Proposed Solution
There could be a compiler builtin function the would expose a hashtable/list/slice/struct that contained the list of exports. 
```zig
comptime {
    const exports = @allExports();
}
```

**Comment by andrewrk** [comment]
The problem with this is that the comptime block that wants to iterate over the exports might execute before a comptime block that adds an export.
