### ISSUE TITLE
Compiler segfault when unwrapping optional with else return inside inline for loop

### ISSUE THREAD

**Issue by tauoverpi** [ziglang/zig#6206]
I've reduced it to the following where if there's only `.{1}` it runs as expected but anything larger causes a compiler segfault for anything iterable with the `else return` present. Affects c1ee9efb7c2a1589b14d6efeffb1f5e6c2d9b994 to 1bb30c5e228f4a5ebc42cc23e593ebad3bd6dbbe (not tested anything else)

```
test "" {
    var k: ?u8 = null;
    inline for (.{ 1, 2 }) |_| if (k) |_| {} else return;
}
```
with a normal `for` it runs as expected
```
test "" {
    var k: ?u8 = null;
    for (.{ 1, 2 }) |_| if (k) |_| {} else return;
}
```

**Comment by Vexu** [comment]
Duplicate of #5579, #4367.
