### ISSUE TITLE
Remove Struct{}/Union{} (and maybe Enum.value?)

### ISSUE THREAD

**Issue by tadeokondrak** [ziglang/zig#6210]
This was mentioned in https://github.com/ziglang/zig/pull/3652 but I don't think it got much discussion after that.

Structs/unions:
> make zig fmt convert `Foo{.a = b}` to `@as(Foo, .{.a = b})`, wait 1 release cycle, and remove the deprecated old syntax. If this looks bad to you, consider that most struct literals will look like this: `const foo: Foo = .{.a = b};`.

Enums:
> That's a good point - you could make an analogy with `Enum.name` being redundant with `@as(Enum, .name)`.

**Comment by daurnimator** [comment]
Note https://github.com/ziglang/zig/pull/3652#issuecomment-552640528

> let's leave it be for a bit, and see how it feels. If it makes it worse in practice to use @as(Foo, .{.a = b}) rather than Foo{.a = b}, then it's worth considering to keep the redundant syntax.

**Comment by tauoverpi** [comment]
If `.{}` worked with error unions this wouldn't probably be too much and the same with `[_]T{}` in the case of `&[_]T{}`. then it would possibly be better at the cost of being slightly more noisy.

**Comment by Vexu** [comment]
Duplicate of #5038
