### ISSUE TITLE
atomic builtins should allow T to be a pointer

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#6217]
Currently,
> T must be a bool, a float, an integer or an enum. 

We should allow `T` to be a pointer type

**Comment by daurnimator** [comment]
This appears to just be an error in the documentation.

**Comment by crawben20** [comment]
Does this really work with a pointer type? `ir_resolve_atomic_operand_type` (in `ir.cpp`) which is used to resolve `T` only succeeds for:
- ZigTypeIdInt
- ZigTypeIdEnum
- ZigTypeIdFloat
- ZigTypeIdBool

**Comment by Vexu** [comment]
You missed the `get_codegen_ptr_type` in the else branch.
