### ISSUE TITLE
Proposal for new builtin: @comptimeFileContents

### ISSUE THREAD

**Issue by mrakh** [ziglang/zig#6223]
Basically what it says on the tin - the function would read a file at compile time and return the contents as a comptime string. In my opinion, this builtin function would greatly extend and modularize Zig's metaprogramming capabilities by cleanly separating compile-time data from compile-time resolution logic. Possible use cases:

- Large compile time template strings
  - Websites serving static/dynamic content
- Compile time config files
  - Lexer generator config file for compiler-generated lexer code
  - JSON Schema file for compiler-generated JSON validation code

Possible function signature:

`@comptimeFileContents(comptime path: []const u8) []const u8`

**Comment by andrewrk** [comment]
[@embedFile](https://ziglang.org/documentation/master/#embedFile)

enjoy!

**Comment by mrakh** [comment]
D'oh! I'm blind. Thanks!

**Comment by WhyNotHugo** [comment]
Note that `@embedFile` doesn't actually embed the file; it only reads into into memory. Whether or not it is embedded depends on the specific usage.

In the following example, I use `@embedFile` to read a file as input, but don't embed it into the final binary:

```zig
const std = @import("std");

fn sizeOfProgram() usize {
    const file = @embedFile("test.zig");
    return file.len;
}

// If @embedFile includes the byte array in the file binary, then it will
// include the following sequence: ASDASDASDF

pub fn main() void {
    const size = comptime sizeOfProgram();
    std.debug.print("Hello, {s}, this program is {d} bytes long!\n", .{ "World", size });
}
```
