### ISSUE TITLE
JSON parse into union with comptime struct fields

### ISSUE THREAD

**Issue by malcolmstill** [ziglang/zig#6231]
I'm looking to use the std lib JSON parser to parse into a union (of structs). The JSON in question has a field called "type" with different values (e.g. "number", "string") that I want to use to switch which particular union value gets created.

For example, let's say I have a JSON list of:

```json
[{"type": "number", "default": 10}, {"type": "string", "default": "hello world"}]
```

and I define my union as

```zig
pub const ThingType = enum {
    String,
    Number,
};

pub const Thing = union(ThingType) {
    Number: ThingNumber,
    String: ThingString,
};

pub const ThingNumber = struct {
    comptime @"type": []const u8 = "int",
    default: ?i32,
};

pub const ThingString = struct {
    comptime @"type": []const u8 = "string",
    default: ?[]u8,
};

```

I would like to end up with a list of

```
[<ThingNumber>, <ThingString>]
```

It makes sense to me here to use a comptime struct field, e.g. `comptime @"type": []const u8 = "number",` in each struct that the union can contain, and for the parser to be able to use that information.

However, the parser gets upset here https://github.com/ziglang/zig/blob/master/lib/std/json.zig#L1486 and https://github.com/ziglang/zig/blob/master/lib/std/json.zig#L1500 with `error: cannot assign to constant` which makes sense as I don't see it taking into consideration that the field would be const.

For this to work I'm guessing, the parser would have to skip the `comptime` / `const` fields. However, I also can't see anything in, e.g., the `TypeInfo` union that would allow some additional logic to skip said fields.

Moreover, if those fields were skipped, even then I'm not entirely sure if the parser would parse into the appropriate struct.

**Comment by zigazeljko** [comment]
> However, I also can't see anything in, e.g., the TypeInfo union that would allow some additional logic to skip said fields.

Not directly. Due to another bug, `offset` in `TypeInfo.StructField` is zero for all `comptime` fields, so you could (probably) use that to determine if the field is `comptime` or not. Still, the correct solution would be to add an `is_comptime` flag to `TypeInfo.StructField`.

**Comment by malcolmstill** [comment]
@zigazeljko thank you for the suggestions:

1. I was able to skip over the comptime fields with `field.offset == 0` (I also sacrificed a non-comptime `@"__skip"` field in the zeroeth position so as to not skip the fields I'm interested in. Obviously that was just for playing around and as you say `is_comptime` on `TypeInfo.StructField` would be the correct solution.
2. As expected the parser doesn't magically know it can parse into only one struct or the other, be it `{"type": "string"}` or `{"type": "number"}`; it attempts to parse into whatever struct is defined first.

As an aside for anyone that comes up the same reasoning, I made `default` optional thinking that that would make the parser not require the value explicitly in the json. On the contrary, you can remove the optional and give it a default value (e.g. `default: i32 = 0`) and it won't be required explicitly in the json.

**Comment by daurnimator** [comment]
@malcolmstill instead of skipping; verify that the comptime field matches. *then* it will magically know it can parse into the right struct :)

**Comment by malcolmstill** [comment]
Thanks @daurnimator; I'll have a play around and see if I get anywhere.

**Comment by dangerousHobo** [comment]
I'm interested in your solution once you get this working as I'll be looking to do something similar soon.

**Comment by malcolmstill** [comment]
@daurnimator / @dangerousHobo I've got something mostly working (at least for a subset of field types). I'm having issues when calling `parseFree` in the test case for a string field (the other tests are fine):

```
➜  zig zig test lib/zig/std/json.zig
Test [9/30] test "parse comptime struct fields"...
Tests failed. Use the following command to reproduce the failure:
[...]
```

...not much help.

Any ideas? I'm thinking maybe I need to `parseFree` in https://github.com/ziglang/zig/pull/6236/files#diff-42e857eaf1c1fd3ec8c7160c79142738R1495, but so far no luck.

**Comment by malcolmstill** [comment]
Update: I think I have it working #6236
