### ISSUE TITLE
Mix Static and Dynamic Linking

### ISSUE THREAD

**Issue by s5bug** [ziglang/zig#6266]
I should be able to link library A statically but library B dynamically, instead of all static (default) or all dynamic (`-rdynamic`).

Use case: I'm distributing a binary that depends on both OpenCL and Raylib. OpenCL cannot be linked statically, but it's a pain for users to manage Raylib being linked dynamically.

Perhaps `LibExeObjStep#linkSystemSharedLibrary`/`LibExeObjStep#linkSystemDynamicLibrary`?

**Comment by andrewrk** [comment]
I'll re-open this if you explain the proposal in more depth. It's already possible to mix static and dynamic linking.

```zig
foo.addObjectFile("raylib.a");
foo.linkSystemLibrary("opencl");
```

On the CLI, that's `zig build-exe foo.zig raylib.a -lopencl`

**Comment by daurnimator** [comment]
> It's already possible to mix static and dynamic linking.
> 
> ```zig
> foo.addObjectFile("raylib.a");
> foo.linkSystemLibrary("opencl");
> ```
> 
> On the CLI, that's `zig build-exe foo.zig raylib.a -lopencl`

How would you do so while search in system library locations?
i.e. how can I find raylib.a at /usr/lib/raylib.a without it selecting the dynamic /usr/lib/raylib.so?
