### ISSUE TITLE
comptime std.math

### ISSUE THREAD

**Issue by xxxbxxx** [ziglang/zig#6270]
hi!

Since https://github.com/ziglang/zig/commit/0bd53dd2033c60d3446abfb83209237c6eb6c9e2
it's no longer possible to use comptime std.math code to precompute comptime data.

bug or feature? 
(I mean, I don't quite understand the math precision vodoo with forced eval, so maybe it was previously working by mistake...)

example: https://godbolt.org/z/jMfbTE

**Comment by daurnimator** [comment]
Related: https://github.com/ziglang/zig/issues/6168
