### ISSUE TITLE
Target.Os.Tag.uefi: undecleared identifier read

### ISSUE THREAD

**Issue by cinemast** [ziglang/zig#6275]
I just checked out recent master branch (https://github.com/ziglang/zig/commit/d7268cbb242d6bea6b6e4d929a8d6b99608b640a)

When I try to build for  Target.Os.Tag.uefi, I get the following compile error:

```
zig\build-release\lib\zig\std\start.zig:70:31: error: use of undeclared identifier 'read'
    switch (@typeInfo(@TypeOf(read)).Fn.return_type.?) {
```

**Comment by cinemast** [comment]
I guess it is related to this commit: https://github.com/ziglang/zig/commit/09c861b829480be525a787e54117c108705256e6

**Comment by FireFox317** [comment]
Jup 09c861b definitely caused that issue.
