### ISSUE TITLE
comptime var + mem.eql unexpected code below condition got executed

### ISSUE THREAD

**Issue by loris-olsem** [ziglang/zig#6300]
I saw that there are already tickets around comptime var but the issue I encountered looks different from the existing tickets that I found, so I though it be worth an own ticket. Please see my example below. Is there some specialness around mem.eql when using comptime like this?

```
const std = @import("std");

pub fn main() !void {
    comptime var count: usize = 0;

    // count will be 42 at the end of main even though condition is false
    const b = std.mem.eql(u8, "XXX", "YYY");
    // adding comptime fixes it
    //const b = comptime std.mem.eql(u8, "XXX", "YYY");
    if (b) {
        std.debug.assert(false);
        count += 42;
    }

    std.debug.warn("{}\n", .{count}); // prints 42
    std.debug.assert(count == 0); // fails
}
```

**Comment by dbandstra** [comment]
I think this is working as intended, although I don't know if it's documented. I think all function calls are non-comptime by default (unless the function has a comptime-like return type, probably).

**Comment by Vexu** [comment]
This is indeed working as intended. Functions are not run at comptime by default which means that the condition is not known to be false which causes the body to be analyzed and `count` to be incremented. This might become a compile error in the future due to #411 and others.

**Comment by loris-olsem** [comment]
Ah ok, I see. I would enjoy if the compiler could raise an error here. Even if one knows it, it may be forgotten/overlooked when functions get longer and more functions calls are made. I made such mem.eql call in double for loop and I was surprised that
my counting variables did not make sense. 
Anyway, thanks for the quick responses :-) "Solved" for me, if issue is tracked with the other tickets.
