### ISSUE TITLE
Proposal: add List Comprehension expression

### ISSUE THREAD

**Issue by codehz** [ziglang/zig#6306]
(so we can initialize large global constant array with some simple calculation without need to define a function)

# Proposal syntax

```zig
const Origin = @embedFile("bigfile.bin");
const Transformed = [_]u8 for(Origin) |x, i| @addWithOverflow(x, 127);
```

* Before that, you cannot

1. initialize it undefined and update it in comptime 
   constant is also enforced for comptime
2. so define it as var, and update it in comptime block
   you will receive `error: unable to evaluate constant expression`

* so you have to 

3. define origin array in comptime block.
4. or create a function for just a simple transform.

**Comment by MasterQ32** [comment]
I don't see the reason for adding a new syntax here. When #1717 lands, your example code gets this:
```zig
const Origin = @embedFile("bigfile.bin");
const Transformed = applyTransformation(Origin, fn(x: u8, _: usize) u8 { return x +% 127; });

// applyTransformation is just a function that transforms arrays as your proposed syntax
```

This is short and comprehensive enough using already existing language features. Also note that it conflicts with for-expressions:
```zig
const index_or_null = for(some_slice) |item, i| {
    if(someCondition(item))
        break i;
} else null;
```

Note for future proposals: Zig syntax is (to my knowledge) nearly set in stone. Check out the [accepted breaking proposals](https://github.com/ziglang/zig/issues?q=is%3Aopen+is%3Aissue+label%3Aaccepted+label%3Aproposal+label%3Abreaking) to see what changes to syntax are happening in the future and try to incorporate them in your thinking about the language as they might lead to much simplification (example above)

**Comment by codehz** [comment]
> conflicts with for-expressions

note the `[_]u8` appears before the for expression it replaced the array init part.

**Comment by codehz** [comment]
> When #1717 lands, your example code gets this:

It has limits, since function is not closure, so you cannot capture another variable, even the developer know the function won't got escaped. And add closure to the language is an another problem, for now let's assume it won't happen.

**Comment by codehz** [comment]
Except for the global constant initializing, the syntax can also be used in local scope, so it should be able to use another variable in the scope, just like a normal for loop.

However, compare to for loop, it is not only make code shorter, it make it more safety:

compare

```zig
const magic: f32 = runtime1();
var transformed: [1024]f24 = undefined;
for (runtime2()) |value| {
	transformed[i] = runtime3(magic, value);
}
// and now the transformed array become var, even you expect it won't be changed.
// to workaround it, you must define another temporary function for this.
```

proposal:
```zig
const magic: f32 = runtime1();
const transformed = [_]f24 for(runtime2()) |value| runtime3(magic, value);
```

**Comment by MasterQ32** [comment]
> It has limits, since function is not closure, so you cannot capture another variable, even the developer know the function won't got escaped. And add closure to the language is an another problem, for now let's assume it won't happen.

You can always pass a context into the function providing "stack downward" closures, see `std.sort.sort` for example

> note the [_]u8 appears before the for expression, it replaced the array init part.

That wasn't really obvious and it breaks a lot of language symmetry: Can i now also initialize structs with `for` as well? Unions?

Zig only has a single type initializer syntax: `T { }`. All other "initializations" are literals (`1.2`, `.foo`, `"heya"`). I don't think it's worth giving up this for a (imho) minor case of array transformation that can be (as you've shown) implemented without much overhead.

On your example "enforcing" a function: it doesn't:
```zig
const transformed = blk: {
    const magic = runtime1();
    const src = runtime2();
    var res: [src.len]f24 = undefined;
    for (res) |*value, i| {
        *value = runtime3(magic, src[i]);
    }
    break :blk;
};
// transformed is now a constant
```

Personal opinion:
I think you're trying to climb a local maximum of trying to improve array initialization whereas it won't be as practical in day-to-day zig code. I really don't have much actual arrays in my code and when i have, they are all initialized with `undefined` or zero. Everything else are slices which your syntax cannot be used for anyways.

**Comment by codehz** [comment]
@MasterQ32 consider another use case: vector calculation.
If the old syntax is used in each unique calculation part, the code will be maintainability disaster(tons of repeat, or 100 lines function).
yes, zig **has** built-in vector type, but it has many limitations, e.g. only few std.math function support vector type

example, to implement a voxel based raycaster, you may wrote
```zig
    fn raycast(self: *const @This(), state: *Iterator) void {
        // output
        var current = [3]i32{
            @floatToInt(i32, self.origin[0]),
            @floatToInt(i32, self.origin[1]),
            @floatToInt(i32, self.origin[2]),
        };
        // internal
        const diff = [3]f32{
            self.origin[0] - std.math.floor(self.origin[0]),
            self.origin[1] - std.math.floor(self.origin[1]),
            self.origin[2] - std.math.floor(self.origin[2]),
        };
        // internal
        const stepF = [3]f32{
            if (std.math.signbit(self.direction[0])) -1 else 1,
            if (std.math.signbit(self.direction[1])) -1 else 1,
            if (std.math.signbit(self.direction[2])) -1 else 1,
        };
        const step = [3]i32{
            @floatToInt(i32, stepF[0]),
            @floatToInt(i32, stepF[1]),
            @floatToInt(i32, stepF[2]),
        };
        const tdelta = [3]f32{
            std.math.fabs(1.0 / self.direction[0]),
            std.math.fabs(1.0 / self.direction[1]),
            std.math.fabs(1.0 / self.direction[2]),
        };
        var tmax = [3]f32{
            std.math.fabs(((stepF[0] + 1) / 2 - (stepF[0] * diff[0])) / self.direction[0]),
            std.math.fabs(((stepF[1] + 1) / 2 - (stepF[1] * diff[1])) / self.direction[1]),
            std.math.fabs(((stepF[2] + 1) / 2 - (stepF[2] * diff[2])) / self.direction[2]),
        };
        while (true) {
            const mi = utils.minIndex(f32, tmax[0..]);
            current[mi] += step[mi];
            tmax[mi] += tdelta[mi];
			// output result
        }
    }
```
How can I debug it if there is a small mistake?

**Comment by MasterQ32** [comment]
This looks like a case for a more generic vector type (like my [zlm](https://github.com/ziglibs/zlm) library) which reduces the whole code to some smaller function calls:

```zig
const ivec3 = zlm.specializeOn(i32).vec3;
const vec3 = zlm.specializeOn(f32).vec3;

fn raycast(self: *const @This(), state: *Iterator) void {
    // output
    var current = zlm.cast(i32, self.origin.floor()); // requires floor, would be UB otherwise!

    // internal
    const diff = self.origin.sub(self.origin.floor());

    // internal
    const stepF = self.direction.signbit();

    const step = zlm.cast(i32, stepF);

    const tdelta = vec3.one.divide(self.direction);

    var tmax = stepF.add(vec3.one).scale(0.5).sub(stepF.mul(diff).divide(self.direction)).abs();
    while (true) {
        const mi = utils.minIndex(f32, tmax[0..]);
        current.component(mi).* += step.component(mi).*;
        tmax.component(mi).* += tdelta.component(mi).*;
        // output result
    }
}
```

Note that `zlm` does not support all of this by now because i didn't require it (for example `.divide` or `zlm.cast`), but that's just a matter of minutes implementing this behaviour
