### ISSUE TITLE
Use case for labeled block with no return value

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#6310]
Just for the record, for future reference:

https://github.com/markfirmware/zig-vector-table/blob/fc058c8a769e768851200608d23c8471ae200274/generated/generated_linker_files/generated_prepare_memory.zig#L4-L26

    data_loaded_in_flash_that_program_must_copy_to_ram: {
        const e = struct {
            extern var __data_loaded_in_flash_that_program_must_copy_to_ram_start: u8;
            extern var __data_loaded_in_flash_that_program_must_copy_to_ram_end: u8;
            extern var __data_loaded_in_flash_that_program_must_copy_to_ram_load_start: u8;
        };
        const start = &e.__data_loaded_in_flash_that_program_must_copy_to_ram_start;
        const end = &e.__data_loaded_in_flash_that_program_must_copy_to_ram_end;
        const slice = @ptrCast([*]u8, start)[0 .. @ptrToInt(end) - @ptrToInt(start)];
        const load_start = &e.__data_loaded_in_flash_that_program_must_copy_to_ram_load_start;
        const loaded_slice = @ptrCast([*]u8, load_start)[0..slice.len];
        std.mem.copy(u8, slice, loaded_slice);
    }
    data_that_program_must_set_to_zero: {
        const e = struct {
            extern var __data_that_program_must_set_to_zero_start: u8;
            extern var __data_that_program_must_set_to_zero_end: u8;
        };
        const start = &e.__data_that_program_must_set_to_zero_start;
        const end = &e.__data_that_program_must_set_to_zero_end;
        const slice = @ptrCast([*]u8, start)[0 .. @ptrToInt(end) - @ptrToInt(start)];
        std.mem.set(u8, slice, 0);
    }

Also:

https://github.com/markfirmware/zig-vector-table/blob/fc058c8a769e768851200608d23c8471ae200274/build.zig#L28-L40

    declareDependencies: {
        format_source.step.dependOn(&generate_linker_files.step);
        build_exe.step.dependOn(&format_source.step);
        build_exe.step.dependOn(&generate_linker_files.step);
        install_raw.step.dependOn(&build_exe.step);
        make_hex_file.step.dependOn(&install_raw.step);
        run_qemu.step.dependOn(&install_raw.step);
    }

    declareCommandLineSteps: {
        b.step("make-hex", "make hex file to copy to device").dependOn(&make_hex_file.step);
        b.step("qemu", "run in qemu").dependOn(&run_qemu.step);
        b.default_step.dependOn(&build_exe.step);
    }

**Comment by squeek502** [comment]
Would an unlabeled block with a comment (above, inside, or inline after the `{`) not suffice?

**Comment by markfirmware** [comment]
> Would an unlabeled block with a comment (above, inside, or inline after the `{`) not suffice?

Yes, but I think that an unlabeled block is the only place in zig where { and } are vertically aligned so this use case would also eliminate that oddity.

The status quo is not a hardship, I just wanted to add this to the record.

I will close this tomorrow after it has had some visibility.

**Comment by markfirmware** [comment]
Thank you.
