### ISSUE TITLE
Text in documentation is too tight

### ISSUE THREAD

**Issue by manast** [ziglang/zig#6313]
For some reason, the text for the documentation (https://ziglang.org/documentation/master/) has a very low line-height, so it is quite difficult to read. If you add this css to the page it will look much better:
```
#contents {
  line-height: 1.5em;
}
```

It will go from this:
![image](https://user-images.githubusercontent.com/95200/92794182-a289fd00-f3af-11ea-8a9f-11919008071f.png)

to this one:
![image](https://user-images.githubusercontent.com/95200/92794218-b170af80-f3af-11ea-94f9-c3ad17cf5880.png)

**Comment by manast** [comment]
if 1.5 is too much maybe 1.3 or something.

**Comment by dbandstra** [comment]
I think the font size should be kicked down to 14px too (from 16px)
