### ISSUE TITLE
--release-fast causes segfault when using rdtscp instruction

### ISSUE THREAD

**Issue by DanB91** [ziglang/zig#6316]
I have the following profiler program: [https://gist.github.com/DanB91/03f48e6c497a9ad32076cab3a96e4128](https://gist.github.com/DanB91/03f48e6c497a9ad32076cab3a96e4128)
If you compile this program with no release flag, this program works fine (i.e. `zig build-exe program.zig`.  When adding the `--release-fast` flag it will segfault on line 45, according to LLDB (i.e. `zig build-exe --release-fast program.zig`).  According to LLDB, the `section` variable in `start()` is null, but if you step through `section_for_name()` it returns a valid pointer.  Of course, since it's compiled in `--release-fast` the symbols may not be very trustworthy 

However, if `rdtscp` is changed to `rdtsc` on line 33, then this program works fine in `--release-fast` mode. Please let me know if you need anything else from me.

**Comment by LemonBoy** [comment]
You forgot to specify the clobbered registers for the inline asm block. `rdtscp` clobbers `edx`, `eax, and `ecx` and since the first two are already part of the output constraints you only need to let the compiler know `ecx` is destroyed.

**Comment by DanB91** [comment]
Completely missed that ecx was used in rdtscp. Adding ecx to the clobber list fixes this issue. Apologies for opening this wasting your time.  Closing this issue
