### ISSUE TITLE
HelloWorld example for redis modules fails with RedisModule_Alloc undefined

### ISSUE THREAD

**Issue by manast** [ziglang/zig#6329]
Just trying out the example from your redis conf presentation:

https://www.youtube.com/watch?v=Csz26Wy9Ses&ab_channel=RedisLabs

Builds fine with ```zig build-lib hello.zig -target x86_64-linux -dynamic -I. -lc -Bsymbolic``` (I am on a Mac) but then this error is reported by redis server when loading the module:
```
Module /modules/libhello.so.0.0.0 failed to load: /modules/libhello.so.0.0.0: undefined symbol: RedisModule_Alloc
```

what gives?

**Comment by nektro** [comment]
> -target x86_64-linux

> I am on a Mac

this may be involved

**Comment by manast** [comment]
who knows... but I cannot build native because of this either https://github.com/ziglang/zig/issues/6308
so kind of show stopper...
Btw, I see issues growing at a high pace, but not so much response from maintainers, holidays season or is this normal?
