### ISSUE TITLE
rename @offsetOf to @byteOffsetOf and add @bitOffsetOf

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#633]
Use case: OS or embedded development, when using a packed struct to represent MMIO, ability to query a packed struct for the bit offsets of fields.

cc @skyfex

**Comment by jido** [comment]
To reiterate my proposal in the chat on the other day-

Keep `@offsetOf` to return a byte-aligned offset, and add:
`@bitShift`
to return by how many bits the field is shifted relative to the offset in a packed struct (can be > 7)

This corresponds better to the way Zig manages packed struct fields.

**Comment by skyfex** [comment]
For the case of registers in an embedded application, the structs will generally be the size of one word, and you'd want the bit offset from the start of the word.

(You generally want the bit mask as well, but that can be constructed at compile-time with the bit shift and field bit width I assume)

I'm not sure what the sensible thing would be when the struct is larger than one word. But as long as you can calculate the total bit offset from the start of the struct to the field, if you combine the information from the builtins, then it doesn't matter much.

**Comment by andrewrk** [comment]
Thanks @raulgrell for solving this issue.

I also opened #1574 for a proposal to make zig's comptime code more robust, enabling us to solve these in userland, and then delete the builtin functions.
