### ISSUE TITLE
aarch64 addInstallRaw produces empty file

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#6338]
However, the first problem in the reproduction branch is that the addInstallRaw produces this long error report that I cannot figure out. Can someone provide an explanation? Thanks, Mark.
@SamTebbs33

    git clone https://github.com/markfirmware/pluto
    cd pluto
    git checkout aarch64-install-raw

    zig version
    0.6.0+c49435f76
    zig build -Dtarget=aarch64-freestanding

    error: FileNotFound
    /workspace/pluto/tools/zig/lib/zig/std/heap/arena_allocator.zig:95:17: 0x268d72 in std.heap.arena_allocator.ArenaAllocator.resize (build)
                    return error.OutOfMemory;
                    ^
    /workspace/pluto/tools/zig/lib/zig/std/heap/arena_allocator.zig:95:17: 0x268d72 in std.heap.arena_allocator.ArenaAllocator.resize (build)
                    return error.OutOfMemory;
                    ^
    /workspace/pluto/tools/zig/lib/zig/std/os.zig:2161:19: 0x27d57c in std.os.mkdiratZ (build)
            EEXIST => return error.PathAlreadyExists,
                      ^
    /workspace/pluto/tools/zig/lib/zig/std/os.zig:2122:9: 0x27d44b in std.os.mkdirat (build)
            return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
            ^
    /workspace/pluto/tools/zig/lib/zig/std/fs.zig:887:9: 0x27d2e6 in std.fs.Dir.makeDir (build)
            try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
            ^
    /workspace/pluto/tools/zig/lib/zig/std/heap/arena_allocator.zig:95:17: 0x268d72 in std.heap.arena_allocator.ArenaAllocator.resize (build)
                    return error.OutOfMemory;
                    ^
    /workspace/pluto/tools/zig/lib/zig/std/heap/arena_allocator.zig:95:17: 0x268d72 in std.heap.arena_allocator.ArenaAllocator.resize (build)
                    return error.OutOfMemory;
                    ^
    /workspace/pluto/tools/zig/lib/zig/std/os.zig:2161:19: 0x27d57c in std.os.mkdiratZ (build)
            EEXIST => return error.PathAlreadyExists,
                      ^
    /workspace/pluto/tools/zig/lib/zig/std/os.zig:2122:9: 0x27d44b in std.os.mkdirat (build)
            return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
            ^
    /workspace/pluto/tools/zig/lib/zig/std/fs.zig:887:9: 0x27d2e6 in std.fs.Dir.makeDir (build)
            try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
            ^
    /workspace/pluto/tools/zig/lib/zig/std/os.zig:2161:19: 0x27d57c in std.os.mkdiratZ (build)
            EEXIST => return error.PathAlreadyExists,
                      ^
    /workspace/pluto/tools/zig/lib/zig/std/os.zig:2122:9: 0x27d44b in std.os.mkdirat (build)
            return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
            ^
    /workspace/pluto/tools/zig/lib/zig/std/fs.zig:887:9: 0x27d2e6 in std.fs.Dir.makeDir (build)
            try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
            ^
    /workspace/pluto/tools/zig/lib/zig/std/os.zig:1233:23: 0x2605cb in std.os.openatZ (build)
                ENOENT => return error.FileNotFound,
                          ^
    /workspace/pluto/tools/zig/lib/zig/std/fs.zig:835:13: 0x2b172a in std.fs.Dir.createFileZ (build)
                try os.openatZ(self.fd, sub_path_c, os_flags, flags.mode);
                ^
    /workspace/pluto/tools/zig/lib/zig/std/fs.zig:774:9: 0x299aff in std.fs.Dir.createFile (build)
            return self.createFileZ(&path_c, flags);
            ^
    /workspace/pluto/tools/zig/lib/zig/std/build/emit_raw.zig:169:20: 0x2b13b9 in std.build.emit_raw.emitRaw (build)
        var out_file = try fs.cwd().createFile(raw_path, .{});
                       ^
    /workspace/pluto/tools/zig/lib/zig/std/build/emit_raw.zig:222:9: 0x298f7c in std.build.emit_raw.InstallRawStep.make (build)
            try emitRaw(builder.allocator, full_src_path, full_dest_path);
            ^
    /workspace/pluto/tools/zig/lib/zig/std/build.zig:2566:9: 0x27e2ee in std.build.Step.make (build)
            try self.makeFn(self);
            ^
    /workspace/pluto/tools/zig/lib/zig/std/build.zig:417:9: 0x27cd95 in std.build.Builder.makeOneStep (build)
            try s.make();
            ^
    /workspace/pluto/tools/zig/lib/zig/std/build.zig:411:17: 0x27cd3c in std.build.Builder.makeOneStep (build)
                    return err;
                    ^
    /workspace/pluto/tools/zig/lib/zig/std/build.zig:411:17: 0x27cd3c in std.build.Builder.makeOneStep (build)
                    return err;
                    ^
    /workspace/pluto/tools/zig/lib/zig/std/build.zig:411:17: 0x27cd3c in std.build.Builder.makeOneStep (build)
                    return err;
                    ^
    /workspace/pluto/tools/zig/lib/zig/std/build.zig:411:17: 0x27cd3c in std.build.Builder.makeOneStep (build)
                    return err;
                    ^
    /workspace/pluto/tools/zig/lib/zig/std/build.zig:411:17: 0x27cd3c in std.build.Builder.makeOneStep (build)
                    return err;
                    ^
    /workspace/pluto/tools/zig/lib/zig/std/build.zig:411:17: 0x27cd3c in std.build.Builder.makeOneStep (build)
                    return err;
                    ^
    /workspace/pluto/tools/zig/lib/zig/std/build.zig:411:17: 0x27cd3c in std.build.Builder.makeOneStep (build)
                    return err;
                    ^
    /workspace/pluto/tools/zig/lib/zig/std/build.zig:411:17: 0x27cd3c in std.build.Builder.makeOneStep (build)
                    return err;
                    ^
    /workspace/pluto/tools/zig/lib/zig/std/build.zig:411:17: 0x27cd3c in std.build.Builder.makeOneStep (build)
                    return err;
                    ^
    /workspace/pluto/tools/zig/lib/zig/std/build.zig:372:13: 0x26fd97 in std.build.Builder.make (build)
                try self.makeOneStep(s);
                ^
    /workspace/pluto/tools/zig/lib/zig/std/special/build_runner.zig:130:21: 0x26575b in main (build)
                else => return err,
                        ^
    
    Build failed. The following command failed:
    /workspace/pluto/zig-cache/o/H2SooCdFBA26Xm0nDpgTA0o4YBcMtJvzTQcEDwNm5uub5Ol76j2AQHirqwPAjnKT/build /workspace/pluto/tools/zig/zig /workspace/pluto /workspace/pluto/zig-cache -Dtarget=aarch64-freestanding

**Comment by LemonBoy** [comment]
The error trace is completely useless, I agree.
The root problem is that the emitRaw step takes a path relative to the install prefix path (`kernel8.img` becomes `zig-cache/bin/kernel8.img`) but you're passing a path that's already prefixed (`kernel_image` is not `kernel8.img` but `zig-cache/kernel8.img`).
This mismatch confuses the emitRaw step as it only creates the root folder `zig-cache/bin` but the complete path is `zig-cache/bin/zig-cache/kernel8.img`.
The solution here is to fix the logic in `InstallRawStep` and rename `dest_filename` into `dest_rel_path` so that it doesn't assume the input is only a file name but a relative path wrt the install dir (this is consistent with what `installFile` does.

Once that's fixed you should also change the path being fed to `MakeKernelLoadAtZeroStep` (or make it accept a relative path wrt the install dir too... you know, for consistency sake).

If you don't give a damn and just want to fix the ARM build (no idea if the other builds are affected):

```diff
diff --git a/build.zig b/build.zig
index f135ef5..a6e6557 100644
--- a/build.zig
+++ b/build.zig
@@ -73,7 +73,7 @@ pub fn build(b: *Builder) !void {
         .i386 => b.addSystemCommand(&[_][]const u8{ "./makeiso.sh", boot_path, modules_path, iso_dir_path, exec.getOutputPath(), ramdisk_path, output_iso }),
         .aarch64 => makeRpiImage: {
             const elf = try fs.path.join(b.allocator, &[_][]const u8{ exec.output_dir.?, "pluto.elf" });
-            const kernel_image = try fs.path.join(b.allocator, &[_][]const u8{ b.cache_root, "kernel8.img" });
+            const kernel_image = "kernel8.img";
             const kernel_load_at_zero_image = try fs.path.join(b.allocator, &[_][]const u8{ b.cache_root, "kernel8-load-at-zero.img" });
             const sdcard_image = try fs.path.join(b.allocator, &[_][]const u8{ b.cache_root, "rpi-sdcard.img" });
 
@@ -90,7 +90,7 @@ pub fn build(b: *Builder) !void {
             install_raw_step.dependOn(&objcopy.step);
 
             const make_kernel_load_at_zero = addCustomStep(b, MakeKernelLoadAtZeroStep{
-                .input_name = kernel_image,
+                .input_name = b.getInstallPath(.Bin, kernel_image),
                 .output_name = kernel_load_at_zero_image,
             });
             make_kernel_load_at_zero.step.dependOn(&objcopy.step);
```

**Comment by markfirmware** [comment]
Thank you! I have updated the branch and the kernel8.img is produced but it has 0 length. I only get this problem on aarch64.
