### ISSUE TITLE
zig build adding a package that zig test won't see

### ISSUE THREAD

**Issue by remeh** [ziglang/zig#6351]
Hey everyone,

I'm working on my second project in Zig and I've stumbled upon an issue while trying to add some tests.

Here's the context:
 - I'm building my project using the build system `build.zig`.
 - I have my own Zig utils repository containing a lot of useful stuff that I've already coded in Zig (HTML parser, HTTP requests, logger, etc.). This utils repository is cloned in the root of my project, and is referenced this way in my `build.zig`:
```
    exe.addPackage(Pkg{
        .name = "utils",
        .path = "zig-utils/lib.zig",
    });
```
  - Then, in my source code, I use:
```
const utils = @import("utils");
const HttpClient = utils.HttpClient;
const HttpResponse = utils.HttpResponse;
const Strings = utils.Strings;
```
  - Finally, to build I just use `zig build`.

Everything is working well except now that I'm adding tests: my freshly written test is calling a method which uses some of the methods in utils, I then have this error:
```
./src/houses.zig:2:15: error: unable to find 'utils'
const utils = @import("utils");
```
which makes sense since `zig test src/houses.zig` has no idea on where to find this `utils`.

Am I doing something wrong? If there is some documentation or anything I can look into about this, that would be very helpful.

**Comment by Tetralux** [comment]
I've seen stuff like this to get around this:
```zig
comptime {
    _ = @import("utils");
}
```
Perhaps that helps you here?

**Comment by squeek502** [comment]
You can run your tests through `build.zig` too:

```zig
    var tests = b.addTest("src/houses.zig");
    tests.setBuildMode(mode);
    tests.addPackage(Pkg{
        .name = "utils",
        .path = "zig-utils/lib.zig",
    });
    const test_step = b.step("test", "Run all tests");
    test_step.dependOn(&tests.step);
```

Then doing `zig build test` will run the tests for you.

The `@import` trick @Tetralux mentioned will allow you to run all your tests through a single file. To achieve this, the zig std tests use:

```zig
pub const atomic = @import("atomic.zig");
pub const base64 = @import("base64.zig");
pub const build = @import("build.zig");
// etc

test "" {
    meta.refAllDecls(@This());
}
```

The simpler version of the same thing would be:

```zig
test "" {
    _ = @import("something.zig");
}
```

**Comment by remeh** [comment]
Awesome, all these information are very useful.
I will add a test step in the build, it's definitely what I was looking for 👌 
Thank you!

**Comment by squeek502** [comment]
One of the communities listed here might be your best bet: https://github.com/ziglang/zig/wiki/Community
