### ISSUE TITLE
eliminate dependency on stage1 C++ code for building glibc shared objects

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#6358]
For building the glibc shared objects, we generate c.zig, m.zig, pthread.zig, etc that look something like this:

```zig
comptime {
    asm (
        \\ .symver _Exit_2_2_5, _Exit@@GLIBC_2.2.5
        \\ .hidden _Exit_2_2_5
        \\ .symver _IO_2_1_stderr__2_2_5, _IO_2_1_stderr_@@GLIBC_2.2.5
        \\ .hidden _IO_2_1_stderr__2_2_5

...

    );
}
export fn _Exit_2_2_5() void {}
export fn _IO_2_1_stderr__2_2_5() void {}

...
```

We then compile this into libc.so.6, libm.so.6, libpthread.so.0, etc.

Self-hosted is not capable of compiling this yet, so for this to work, #6250 relies on stage1 c++ code (which in turn relies on LLVM).

This issue is to eliminate the dependency on stage1 C++ code. Depending on llvm extensions being enabled is ok, the issue can still be considered resolved in that case. We could either augment stage2 to be able to handle this zig code, or we could start generating assembly files instead of zig code.

cc @LemonBoy you might already know a simple way to accomplish this.

**Comment by andrewrk** [comment]
It might work if we do: c.s, m.s, pthread.s, etc like this:

```asm
.symver _Exit_2_2_5, _Exit@@GLIBC_2.2.5
.hidden _Exit_2_2_5
.globl _Exit_2_2_5
.symver _IO_2_1_stderr__2_2_5, _IO_2_1_stderr_@@GLIBC_2.2.5
.hidden _IO_2_1_stderr__2_2_5
.globl _Exit_2_2_5
```

I'll experiment with it.

**Comment by andrewrk** [comment]
OK cool this seems to work:

```asm
.globl _Exit_2_2_5
.type _Exit_2_2_5, @function;
.symver _Exit_2_2_5, _Exit@@GLIBC_2.2.5
.hidden _Exit_2_2_5
_Exit_2_2_5:

.globl _IO_2_1_stderr__2_2_5
.type _IO_2_1_stderr__2_2_5, @function;
.symver _IO_2_1_stderr__2_2_5, _IO_2_1_stderr_@@GLIBC_2.2.5
.hidden _IO_2_1_stderr__2_2_5
_IO_2_1_stderr__2_2_5:
```

```
zig build-lib -dynamic --c-source c.s --version-script all.map
```

ez pz

**Comment by LemonBoy** [comment]
Yeah, the `.zig` stubs are glorified ASM files heh

**Comment by xackus** [comment]
So there is nothing blocking this?
If waiting a couple of days is not a problem, i would like to tackle this; though i don't really have any experience with shared objects.

**Comment by andrewrk** [comment]
@xackus sorry I should have mentioned upon the realization in https://github.com/ziglang/zig/issues/6358#issuecomment-693652230 that I immediately started working on it as part of #6250 and I'm halfway done :)

**Comment by xackus** [comment]
No problem, i haven't started working on it.
