### ISSUE TITLE
Segmentation fault in release mode with std.rand.Csprng.int(u8)

### ISSUE THREAD

**Issue by pmwhite** [ziglang/zig#6384]
Here is a repro I've just tested with the most recent master from ziglang.org:
```zig
const std = @import("std");

pub fn main() anyerror!void {
    var seed = @intCast(u64, std.time.timestamp());
    var csprng = std.rand.DefaultCsprng.init(seed);
    var rand = csprng.random;
    _ = rand.int(u8);
}
```

In normal build mode, this runs fine. However, in `release-safe` build mode, I get the following error when I run the executable.

```
Segmentation fault at address 0x0
/.../zig/lib/zig/std/rand.zig:939:26: 0x214673 in std.rand.Isaac64.fill (repro)
                buf[i] = @truncate(u8, n);
                         ^
The process was killed by SIGABRT: Aborted
```

**Comment by LemonBoy** [comment]
```zig
var rand = csprng.random;
```

This creates a fresh copy of the `random` interface that's detached from `csprng`. When you call `int` you're basically mangling some random stack region, hence the segfault.

Use this instead:
```zig
var rand = &csprng.random;
```

**Comment by Tetralux** [comment]
This is the second time I've come across someone having this problem in a week.
Perhaps this interface could be improved.

My first thought: maybe `random` should be a member function, like `writer()` is on `io.Writer`?

**Comment by Rocknest** [comment]
Yeah looks like we need #3803 or some other protection

**Comment by jayschwa** [comment]
It looks like this is covered by https://github.com/ziglang/zig/issues/591 and related proposals.
