### ISSUE TITLE
noinline attribute for functions

### ISSUE THREAD

**Issue by PavelVozenilek** [ziglang/zig#640]
C/C++ has nonstandard constructs  like `__noinline` or `__attribute__((noinline))`. When coding I am much more certain when I do _not_ wish something to inline, than the opposite.  Reducing code bloat is easier to think about than guessing performance impact.

I propose for Zig:
* function annotation `no-inline`, opposite to `inline`. Calling `@inlineCall` on it would be compile error.
* builtin `@noInlineCall`, opposite to `@inlineCall`.  Calling `@noInlineCall` on `inline` function would be compile error.

-----------------

Possibly, syntax for `@inlineCall` and `@noInlineCall` could be:

```
fn foo() -> i32 {...}
...
var x = inline foo();
var y = no-inline foo();

```

**Comment by PavelVozenilek** [comment]
As with other annotations, `inline`/`no-inline` may be dependent on environment:

```
fn foo(comptime b : bool) 
{
  if (b) {
inline:
    return;
  }

no-inline:
   // long computation here which is better not to be inlined
   ...
}

```

**Comment by cztomsik** [comment]
It is already possible to specify `.modifier = .never_inline` for the `@call`

What is still missing is the counterpart for the `inline fn`.
Maybe what about something like `inline(.always)` and `inline(.never)`?
Or we can just close this?

**Comment by Vexu** [comment]
`noinline` has existed for a long time #3178, not sure why this was left open.
