### ISSUE TITLE
support both inline keyword as well as callconv(.Inline)

### ISSUE THREAD

**Issue by tadeokondrak** [ziglang/zig#6429]
[accepted proposal](https://github.com/ziglang/zig/issues/6429#issuecomment-843757556)

--------------

`inline` is mutually exclusive with a custom calling convention, I think this makes it simpler.
`noinline` is unaffected.

**Comment by andrewrk** [comment]
This is a change we can get `zig fmt` to do for us automatically.

**Comment by nektro** [comment]
what about the inconsistency this now causes with `inline for` ?

that being `inline for` being to unwrap loops, and then `inline fn` being for unwrapped funcions

**Comment by windows-h8r** [comment]
> what about the inconsistency this now causes with `inline for` ?
> 
> that being `inline for` being to unwrap loops, and then `inline fn` being for unwrapped funcions


@nektro I agree with you. To make matters worse, `noinline` remains, and #7772 is accepted. Even more `inline`ed things.

**Comment by SpexGuy** [comment]
I agree, I think there's a difference in stage 2 between a semantic inline and a machine code inline.  Machine code inline is a calling convention, semantic inline is maybe something else.  It may make sense to have both.

**Comment by frmdstryr** [comment]
Any function that uses an async call cannot be explicitly inlined now:

```zig
error: function with calling convention 'Inline' cannot be async
```

**Comment by LemonBoy** [comment]
The asymmetry with `noinline` is really bad, I'd reconsider this change before the next release.

**Comment by andrewrk** [comment]
I have a completely feelings-based reaction to this, I can't justify it other than emotions.

`inline fn` makes me happy
`callconv(.Inline)` makes me cringe

**Comment by MasterQ32** [comment]
@andrewrk `inline` isn't really a calling convention anyways, but a semantic transformation, so it's kinda misleading to have it as a calling convention. At least if i understood @SpexGuy correctly

**Comment by jedisct1** [comment]
I miss `inline fn` as well.

**Comment by tadeokondrak** [comment]
I agree with the switch back,

> inline isn't really a calling convention anyways, but a semantic transformation

I only learned after this was implemented that this was the plan in stage2.

**Comment by frmdstryr** [comment]
> `inline fn` makes me happy
> `callconv(.Inline)` makes me cringe

You are not alone... I remember grumbling the whole time I was making changes for this lol.

**Comment by marler8997** [comment]
If we went back to `inline fn`, would it be an error to specify both `inline` and an explicit calling convention?   Same thing for `nonline` (since a function with a calling convention can't be inlined anyway)?

**Comment by nektro** [comment]
having it as `callconv` is nice because then you don't have to add a check to make sure `inline`/`noinline` is being used with incompatible `callconv`s, such as `.C`

**Comment by nektro** [comment]
whether or not it counts as a callconv or not I guess depends on exactly how `callconv` is defined. Is `callconv` just how something is used with respect to an ABI or is it a little more abstract? because if its the latter then inline *is* a callconv because instead of calling the function like normal on the stack, it becomes somewhat analogous to `#define` functions

**Comment by marler8997** [comment]
If we kept it as `callconv`, then `noinline` could also be moved to a calling convention.  We could consider the default calling convention as "inlineable" and use something like `callconv(.NoInline)` to override it.  Note that both "inline" and "noinline" are not compatible with any other calling convention as far as I can tell, so keeping these options all in the same set is the most simple way to represent them.

**Comment by andrewrk** [comment]
`noinline` cannot be moved to a calling convention because then you don't know what the calling convention is.

**Comment by marler8997** [comment]
I take my comment back.  Apparently Zig is free to inline functions of any calling convention, which means the presence of "noinline" on a function can change the behavior of a function with any calling convention.

**Comment by nektro** [comment]
how is `noinline` used? the only mention I see of it in the lang reference is in the docs for `@call`

**Comment by LemonBoy** [comment]
> how is noinline used

You put it on the declaration site, `noinline fn foo() void { ... }`

> If we went back to inline fn, would it be an error to specify both inline and an explicit calling convention

It's an error because the chosen `callconv` annotation may require the backend to emit different machine code wrt a regular function (think of the `.Interrupt` or `.Signal`).

**Comment by andrewrk** [comment]
I'm making the call here, Zig will support both `inline fn` syntax as well as `callconv(...)` syntax. It will be a compile error to have both `inline` and `callconv` syntax both specified.

As far as one way to do things goes, here's the one way to do things:
 * use `inline fn` when you can
 * use `callconv(...)` when you must

**Comment by nektro** [comment]
> when you can

are there any notable situations where would \*not\* be able to?

**Comment by LemonBoy** [comment]
> use callconv(...) when you must

I can't think of a single instance where one would use this over `inline`

**Comment by ifreund** [comment]
> I can't think of a single instance where one would use this over `inline`

using `callconv(...)` allows you to inline or not based on a comptime known value. I don't have a use-case for this though.

Anyhow, I intend to implement the revised proposal today and make zig format replace `callconv(.Inline)` with the inline keyword if the enum literal is used directly.
