### ISSUE TITLE
Update LLVM backend to use arbitrary precision integer for createEnumerator debug info

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#645]
Currently if an enum tag has greater than 63 bits, we cannot create correct debug info for it.
http://lists.llvm.org/pipermail/llvm-dev/2017-December/119475.html

For example, these two enums have incorrect debug info for the tag values.

```zig
const Foo = enum (u64) {
    A = 18446744073709551615,
    B = 1,
    C = 2,
};

const Bar = enum(u128) {
    A = 340282366920938463463374607431768211455,
    B = 1,
    C = 2,
};
```

LLVM's API needs to be updated to allow an APInt instead of int64_t for the tag value.

**Comment by LemonBoy** [comment]
[Here's](https://reviews.llvm.org/D62475) the patch you were waiting for ;)

**Comment by andrewrk** [comment]
Wow, that looks like it took a lot of work. Thanks!

**Comment by data-man** [comment]
> Here's the patch you were waiting for ;)

It would be great if this patch will be included to release 9.0
Please remind LLVM team! :)

**Comment by andrewrk** [comment]
Hmm, the patch never got merged. I'm not sure what step we failed to take to get it into master branch. I sent an email to the llvm-dev mailing list just now.

**Comment by camconn** [comment]
Sorry to necro bump, but it appears that @LemonBoy's patch [has landed](https://github.com/llvm/llvm-project/commit/aad3d578da0ddf6d0d3d95e5e09a32e47f6dfeb8) in the LLVM [11.0.1 release candidate](https://github.com/llvm/llvm-project/releases/tag/llvmorg-11.0.1-rc2).

**Comment by Bergasms** [comment]
Further to above necro bump, the patch is available in LLVM since LLVM 11.0.0.   

[See here](https://github.com/llvm/llvm-project/commit/aad3d578da0ddf6d0d3d95e5e09a32e47f6dfeb8).    

What action could/should be taken to close out these older tickets. Is it just a matter of having the time to triage all the old ones or should some tests be written to prove it is resolved?

**Comment by andrewrk** [comment]
This issue can be closed when someone verifies that the self-hosted compiler, with the LLVM backend, properly emits debug info for large enum tags. This is not yet implemented.

**Comment by matu3ba** [comment]
Patch has been applied upstream on LLVM https://reviews.llvm.org/D62475 in this commit https://reviews.llvm.org/rGaad3d578da0ddf6d0d3d95e5e09a32e47f6dfeb8

**Comment by truemedian** [comment]
This issue blocks using `std.os.uefi` with stage2 with 64-bit targets, `std.os.uefi.Status` is a `enum(usize)` with many elements that have the high bit set.

The compiler tries to intCast these values to a i64, which causes a panic.
