### ISSUE TITLE
CI sometimes failing due to std lib tests hitting memory limits

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#6467]
stage1 leaks a lot of memory and we've added enough to std that we're up against our CI memory limits for azure.

![image](https://user-images.githubusercontent.com/106511/94650104-0a9f7500-02c4-11eb-933b-23cfd6050e30.png)

You can see the red line has grown over time as more tests and APIs have been added to std. The dip at the end is because today I started the [std lib orphanage](https://github.com/ziglang/std-lib-orphanage/) to buy us a bit more time by doing a little earlier than originally planned some std lib trimming.

Azure gives us an inconsistent amount of memory with each run, but we're at the point where it's becoming uncomfortably likely for tests to fail due to OOM.

Options to deal with this include:
 * improve stage1 memory utilization
 * do something creative like dividing std lib tests into A & B and running them separately
 * move more stuff to the std lib orphanage
 * disable some tests
 * convince microsoft to give us more memory in CI runs

Ultimately we just need to buy some more time until self-hosted is done because it will not have this issue.

**Comment by daurnimator** [comment]
> dividing std lib tests into A & B and running them separately

I think this is the most sensible way forward.

To take it to the extreme: what is the reason we don't compile *every* test block to its own binary?

**Comment by brentr** [comment]
If the problem is that all the test cases can't be compiled on 32-bit systems, is there a simple way to skip compiling them for those of us who'd with 32-bit user spaces who would like to play with this new toy?

**Comment by Vexu** [comment]
This was solved by deleting stage1
