### ISSUE TITLE
lib/zig/libc/mingw/lib32/user32.def missing in release builds

### ISSUE THREAD

**Issue by 20kdc** [ziglang/zig#6473]
Version in use: `https://ziglang.org/builds/zig-linux-x86_64-0.6.0+d1cea16f5.tar.xz`
Environment: Ubuntu 20.04 Focal Fossa, unsure how up-to-date or not.
The file `lib/zig/libc/mingw/lib32/user32.def` is not present, and the .in file from lib-common does not appear to be used.

As a result, compiling the Zig code at https://raw.githubusercontent.com/20kdc/miniature-funicular/c27382ee4fc9231ab6baba393bf32ff574da9a24/src/moonboot_dll.zig (excuse it's general awfulness, as you can probably tell it is translated from C) using `zig build-lib --release-small --single-threaded -target i386-windows --strip -dynamic src/moonboot_dll.zig` fails with the error:
```
20kdc@Kaede:~/Documents/Sync2/repositories/miniature-funicular$ ./moonboot-zig
Link... lld: error: undefined symbol: _MessageBoxA@16
>>> referenced by ./moonboot_dll.obj:(_luaboot)
```

Creating the file, and giving it the contents (for example):
```
LIBRARY "USER32.dll"
EXPORTS
MessageBoxA@16
```
works around the problem.

**Comment by zhaozg** [comment]
ref: https://github.com/ziglang/zig/issues/6479
