### ISSUE TITLE
error: unrecognized parameter: '--linker-script'

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#6477]

**Comment by LemonBoy** [comment]
Change [this](https://github.com/ziglang/zig/blob/bf0afaa876391571f6072650bf450356b26c928d/lib/std/build.zig#L2171) line into `try zig_args.append("--script")` and you should be good to go.
Don't forget to send a PR if that solves your problem.

**Comment by markfirmware** [comment]
Yes that fixes it. I will send pr.
