### ISSUE TITLE
[windows] zig build give warning: failed to save archive hash digest symlink: AccessDenied

### ISSUE THREAD

**Issue by codehz** [ziglang/zig#6480]
version: 0.6.0+4eb390b15
os: windows
```
LLVM Emit Output... warning(compilation): failed to save stage1 hash digest symlink: AccessDenied
warning: failed to save archive hash digest symlink: AccessDenied
LLVM Emit Output... warning(compilation): failed to save stage1 hash digest symlink: AccessDenied
warning: failed to save archive hash digest symlink: AccessDenied
Code Generation [317/2034] std.hash_map.HashMapUnmanaged([]const u8,std.build.UserInpLLVM Emit Output... warning(compilation): failed to save stage1 hash digest symlink: AccessDenied
warning: failed to save linking hash digest symlink: AccessDenied
LLVM Emit Output... warning(compilation): failed to save stage1 hash digest symlink: AccessDenied
warning: failed to save archive hash digest symlink: AccessDenied
LLVM Emit Output... warning(compilation): failed to save stage1 hash digest symlink: AccessDenied
warning: failed to save archive hash digest symlink: AccessDenied
LLVM Emit Output... warning(compilation): failed to save stage1 hash digest symlink: AccessDenied
```

**Comment by LemonBoy** [comment]
In order to create symlinks on windows you need to be an Administrator (or have the permission to create symlinks) or, on newer Windows 10 builds, you can do so _iff_ the developer mode is active.

**Comment by codehz** [comment]
> In order to create symlinks on windows you need to be an Administrator (or have the permission to create symlinks) or, on newer Windows 10 builds, you can do so _iff_ the developer mode is active.

BUT as a compiler, it should not require any privilege...

**Comment by codehz** [comment]
maybe related to https://github.com/ziglang/zig/commit/254ee89def29f67fdf4dd4c6a433ae876f76d79e

**Comment by alexnask** [comment]
This digest symlink is an optimization, failing to update it just means you will get an extra cache miss later.

**Comment by andrewrk** [comment]
> In order to create symlinks on windows you need to be an Administrator (or have the permission to create symlinks) or, on newer Windows 10 builds, you can do so iff the developer mode is active.

This is news to me. In this case the code should be modified to not use a symlink to store the hash. File contents will do just as well. Using a symlink was just a way to do fewer syscalls since the file contents is only a few bytes.

**Comment by alexnask** [comment]
Closing this now in favor of #6500
