### ISSUE TITLE
How to pass a Zig struct to a C ABI and back to Zig

### ISSUE THREAD

**Issue by manast** [ziglang/zig#6487]
I am implementing a redis module and I am using the ```RedisModule_BlockClientOnKeys``` api. This function takes a private void pointer for sending custom data to your callbacks. Then in your callbacks you can access this data. However I am having a problem that I am not sure if it is my doing something wrong or a limitation of  Zig itself.

Basically I define a struct with the data I want to send, for example:
(I know I could send the RedisModuleString, but in real life the struct has more data)
```
const ReplyData = extern struct {
    name: ?*RedisModuleString,
};
```

Then the code looks something like this:

```
 var data = ReplyData {
   .name = name,
 };

const blockedClient = RedisModule_BlockClientOnKeys.?(ctx, 
            BlockedReplyCallback, 
            TimeoutReplyCallback, 
            BlockedFreePrivdata,
            timeout, 
            blockingKeys, 
            2, 
            &data);
```

The ```BlockedReplyCallback```  looks like this:
```
fn BlockedReplyCallback(
  ctx: ?*RedisModuleCtx,
  argv: [*c]?*RedisModuleString,
  argc: c_int) callconv(.C) c_int {
    const pData: *ReplyData = @ptrCast(*ReplyData, @alignCast(8, RedisModule_GetBlockedClientPrivateData.?(ctx)));
```

So the code above will result in corrupted data, and I assume it is because of the alignCast, however if I remove the cast I get a compiler error: 
```
./test.zig:349:31: error: cast increases pointer alignment
    const pData: *ReplyData = @ptrCast(*ReplyData, RedisModule_GetBlockedClientPrivateData.?(ctx));
                              ^
./test.zig:349:93: note: '?*c_void' has alignment 1
    const pData: *ReplyData = @ptrCast(*ReplyData, RedisModule_GetBlockedClientPrivateData.?(ctx));
                                                                                            ^
./test.zig:349:40: note: '*ReplyData' has alignment 8
    const pData: *ReplyData = @ptrCast(*ReplyData, RedisModule_GetBlockedClientPrivateData.?(ctx));
```

In order to avoid the align cast and the error I tried to use "packed" instead of "extern" but this results in corrupted data too, I assume it is because it is not following the C ABI.

So I think the only way this would work is with extern and without the align cast, but how to get rid of the compiling error?

Reference:
Signature of BlockClientOnKeys
```
RedisModuleBlockedClient *RedisModule_BlockClientOnKeys(RedisModuleCtx *ctx, RedisModuleCmdFunc reply_callback, RedisModuleCmdFunc timeout_callback, void (*free_privdata)(RedisModuleCtx*,void*), long long timeout_ms, RedisModuleString **keys, int numkeys, void *privdata);
```

**Comment by ifreund** [comment]
Do you have a link to the full code? If it looks exactly like this then you are passing a pointer to a temporary stack variable and then accessing it once the variable is out of scope:
```zig
var data = ReplyData {
    .name = name,
};
const blockedClient = RedisModule_BlockClientOnKeys.?(ctx, 
            BlockedReplyCallback, 
            TimeoutReplyCallback, 
            BlockedFreePrivdata,
            timeout, 
            blockingKeys, 
            2, 
            &data);
```

You probably want to allocate your data struct on the heap or use a global variable to make this work. Also, there's no need to use an `extern struct` here as the struct is not accessed from C code, only zig code.

**Comment by manast** [comment]
aha, I think you nailed it here. The function is returning and the struct was allocated in the stack, will need the heap then!. Thanks, for the quick reply.

**Comment by ifreund** [comment]
No problem, glad I could be of help!
