### ISSUE TITLE
cannot embed windows resource file in latest version zig

### ISSUE THREAD

**Issue by codehz** [ziglang/zig#6488]
build.zig
```zig
exe.addObjectFile("src/app.res");
```

got error:
`error: unrecognized file extension of parameter 'xxxx\app.res'`
version: 0.6.0+4eb390b15

(it used working before https://github.com/ziglang/zig/pull/6250 (i'm not sure if it is related

it works at least in 58ee5f4e6 

the minimal repro step:
1. run `zig init-exe`
2. edit the build.zig and add `exe.addObjectFile("src/app.res");` after `const exe = b.addExecutable("x", "src/main.zig");`
yes, the file is even not need to be exists, because it crash before access the file
3. run `zig build`

**Comment by samhattangady** [comment]
In 0.10.0, I use a workaround as suggested by @squeek502 in https://github.com/squeek502/watchedoverlay/tree/master/res

Rename the `app.res` file to `app.res.obj`, and then link the `app.res.obj` file.

I use it to set an icon for the executable, and it works for that purpose. I don't know how it would function in any other usecase.

**Comment by squeek502** [comment]
Yeah, I should have made a comment about this, thanks for writing one. The linker does the right, but the extension is not recognized due to the code here:

https://github.com/ziglang/zig/blob/9c509f1526b4560b4e97367a18755a9d1ae6fcf7/src/Compilation.zig#L4195-L4225
