### ISSUE TITLE
no build progress display in latest zig

### ISSUE THREAD

**Issue by codehz** [ziglang/zig#6489]
version: 0.6.0+4eb390b15
os: win10

(since it is just empty (until some error reported), so I cannot paste log...)

**Comment by jedisct1** [comment]
Do you mean that when you type `zig build`, the command doesn't print anything but also hangs/doesn't return?

**Comment by jedisct1** [comment]
Does removing the global cache (`rm -fr ~/.cache/zig`) help?

**Comment by codehz** [comment]
@jedisct1 
The progress shows in first time run `zig build` (after rm -rf zig-cache
No longer appear in subsequent `zig build`
It didn't hang, if I turn on the --verbose it will print the command without problem, just no "normal mode" output at all
![image](https://user-images.githubusercontent.com/13158903/94817703-e06ac600-042f-11eb-866b-f58df2ca0127.png)

**Comment by codehz** [comment]
In the previous version, the log will appear briefly and then disappear. Although it is still strange, it can at least indicate that it is running normally. There is still a small difference compared with the latest version.

**Comment by codehz** [comment]
another repro step:

1. create a working cpp file (helloworld.cpp)
2. zig c++ helloworld.cpp

no output at all
