### ISSUE TITLE
FileNotFound when building an exe in build.zig

### ISSUE THREAD

**Issue by SamTebbs33** [ziglang/zig#6493]
Running `zig build` on [this build.zig](https://github.com/ZystemOS/pluto/blob/837851f4104ba5fdad9ae34ebf22e9f416e4b376/build.zig) fails when it looks for "stage1.id", I don't reference this file so it must be a stdlib issue. I am using a build and std lib installation of the latest master.
> Path stage1.id
error: FileNotFound
/home/sam/builds/zig/lib/zig/std/heap/arena_allocator.zig:104:17: 0x268192 in std.heap.arena_allocator.ArenaAllocator.resize (build)
                return error.OutOfMemory;
                ^
/home/sam/builds/zig/lib/zig/std/heap.zig:270:9: 0x23d123 in std.heap.PageAllocator.resize (build)
        return error.OutOfMemory;
        ^
/home/sam/builds/zig/lib/zig/std/mem/Allocator.zig:319:16: 0x27de3f in std.mem.Allocator.resize (build)
    const rc = try self.resizeFn(self, old_byte_slice, Slice.alignment, new_byte_count, 0, @returnAddress());
               ^
/home/sam/builds/zig/lib/zig/std/os.zig:2122:19: 0x27bd1c in std.os.mkdiratZ (build)
        EEXIST => return error.PathAlreadyExists,
                  ^
/home/sam/builds/zig/lib/zig/std/os.zig:2083:9: 0x27bbeb in std.os.mkdirat (build)
        return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
        ^
/home/sam/builds/zig/lib/zig/std/fs.zig:922:9: 0x27ba86 in std.fs.Dir.makeDir (build)
        try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
        ^
/home/sam/builds/zig/lib/zig/std/heap/arena_allocator.zig:104:17: 0x268192 in std.heap.arena_allocator.ArenaAllocator.resize (build)
                return error.OutOfMemory;
                ^
/home/sam/builds/zig/lib/zig/std/heap/arena_allocator.zig:104:17: 0x268192 in std.heap.arena_allocator.ArenaAllocator.resize (build)
                return error.OutOfMemory;
                ^
/home/sam/builds/zig/lib/zig/std/os.zig:2122:19: 0x27bd1c in std.os.mkdiratZ (build)
        EEXIST => return error.PathAlreadyExists,
                  ^
/home/sam/builds/zig/lib/zig/std/os.zig:2083:9: 0x27bbeb in std.os.mkdirat (build)
        return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
        ^
/home/sam/builds/zig/lib/zig/std/fs.zig:922:9: 0x27ba86 in std.fs.Dir.makeDir (build)
        try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
        ^
/home/sam/builds/zig/lib/zig/std/os.zig:1193:23: 0x25f96b in std.os.openatZ (build)
            ENOENT => return error.FileNotFound,
                      ^
/home/sam/builds/zig/lib/zig/std/fs.zig:754:13: 0x245c02 in std.fs.Dir.openFileZ (build)
            try os.openatZ(self.fd, sub_path, os_flags, 0);
            ^
/home/sam/builds/zig/lib/zig/std/fs.zig:687:9: 0x24362f in std.fs.Dir.openFile (build)
        return self.openFileZ(&path_c, flags);
        ^
/home/sam/builds/zig/lib/zig/std/fs.zig:1766:24: 0x2b6275 in std.fs.Dir.updateFile (build)
        var src_file = try source_dir.openFile(source_path, .{});
                       ^
/home/sam/builds/zig/lib/zig/std/build.zig:2338:25: 0x2a8a18 in std.build.LibExeObjStep.make (build)
                    _ = try src_dir.updateFile(entry.name, dest_dir, entry.name, .{});
                        ^
/home/sam/builds/zig/lib/zig/std/build.zig:2591:9: 0x27ca8e in std.build.Step.make (build)
        try self.makeFn(self);
        ^
/home/sam/builds/zig/lib/zig/std/build.zig:417:9: 0x27b535 in std.build.Builder.makeOneStep (build)
        try s.make();
        ^
/home/sam/builds/zig/lib/zig/std/build.zig:411:17: 0x27b4dc in std.build.Builder.makeOneStep (build)
                return err;
                ^
/home/sam/builds/zig/lib/zig/std/build.zig:411:17: 0x27b4dc in std.build.Builder.makeOneStep (build)
                return err;
                ^
/home/sam/builds/zig/lib/zig/std/build.zig:372:13: 0x26f1b7 in std.build.Builder.make (build)
            try self.makeOneStep(s);
            ^
/home/sam/builds/zig/lib/zig/std/special/build_runner.zig:130:21: 0x264afb in main (build)
            else => return err,

Also note the trace for an `OutOfMemory` error, even though this isn't the actual issue.

**Comment by FireFox317** [comment]
Can't repro this unfortunately

**Comment by SamTebbs33** [comment]
> Can't repro this unfortunately

Thanks for taking a look. Do you know if I need to reconfigure my zig build or do something new during the build process? I can see a stage1.id file in my zig-cache.

**Comment by IridescentRose** [comment]
I've just gotten this same error

**Comment by IridescentRose** [comment]
Here's another [build.zig that fails](https://github.com/zPSP-Dev/Zig-PSP/blob/master/build.zig)

**Comment by frett27** [comment]
got same issue, the commandline is fine 👍 
zig build-exe iotmonitor.zig -lc -Lpaho.mqtt.c/build/output -Lpaho.mqtt.c/src paho.mqtt.c/src/libpaho-mqtt3c.a -lleveldb --pkg-begin toml zig-toml/src/toml.zig --pkg-end

use@fhome:~/iotmonitor$ zig build
error: FileNotFound
/home/use/zig/lib/std/heap/arena_allocator.zig:104:17: 0x256202 in std.heap.arena_allocator.ArenaAllocator.resize (build)
                return error.OutOfMemory;
                ^
/home/use/zig/lib/std/heap.zig:270:9: 0x22b143 in std.heap.PageAllocator.resize (build)
        return error.OutOfMemory;
        ^
/home/use/zig/lib/std/mem/Allocator.zig:319:16: 0x26a78f in std.mem.Allocator.resize (build)
    const rc = try self.resizeFn(self, old_byte_slice, Slice.alignment, new_byte_count, 0, @returnAddress());
               ^
/home/use/zig/lib/std/os.zig:2122:19: 0x26866c in std.os.mkdiratZ (build)
        EEXIST => return error.PathAlreadyExists,
                  ^
/home/use/zig/lib/std/os.zig:2083:9: 0x26853b in std.os.mkdirat (build)
        return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
        ^
/home/use/zig/lib/std/fs.zig:922:9: 0x2683d6 in std.fs.Dir.makeDir (build)
        try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
        ^
/home/use/zig/lib/std/heap/arena_allocator.zig:104:17: 0x256202 in std.heap.arena_allocator.ArenaAllocator.resize (build)
                return error.OutOfMemory;
                ^
/home/use/zig/lib/std/heap/arena_allocator.zig:104:17: 0x256202 in std.heap.arena_allocator.ArenaAllocator.resize (build)
                return error.OutOfMemory;
                ^
/home/use/zig/lib/std/os.zig:2122:19: 0x26866c in std.os.mkdiratZ (build)
        EEXIST => return error.PathAlreadyExists,
                  ^
/home/use/zig/lib/std/os.zig:2083:9: 0x26853b in std.os.mkdirat (build)
        return mkdiratZ(dir_fd, &sub_dir_path_c, mode);
        ^
/home/use/zig/lib/std/fs.zig:922:9: 0x2683d6 in std.fs.Dir.makeDir (build)
        try os.mkdirat(self.fd, sub_path, default_new_dir_mode);
        ^
/home/use/zig/lib/std/os.zig:1193:23: 0x24d99b in std.os.openatZ (build)
            ENOENT => return error.FileNotFound,
                      ^
/home/use/zig/lib/std/fs.zig:754:13: 0x233c42 in std.fs.Dir.openFileZ (build)
            try os.openatZ(self.fd, sub_path, os_flags, 0);
            ^
/home/use/zig/lib/std/fs.zig:687:9: 0x23166f in std.fs.Dir.openFile (build)
        return self.openFileZ(&path_c, flags);
        ^
/home/use/zig/lib/std/fs.zig:1765:24: 0x2856ad in std.fs.Dir.updateFile (build)
        var src_file = try source_dir.openFile(source_path, .{});
                       ^
/home/use/zig/lib/std/build.zig:2342:25: 0x27df9b in std.build.LibExeObjStep.make (build)
                    _ = try src_dir.updateFile(entry.name, dest_dir, entry.name, .{});
                        ^
/home/use/zig/lib/std/build.zig:2595:9: 0x2693de in std.build.Step.make (build)
        try self.makeFn(self);
        ^
/home/use/zig/lib/std/build.zig:417:9: 0x267e85 in std.build.Builder.makeOneStep (build)
        try s.make();
        ^
/home/use/zig/lib/std/build.zig:411:17: 0x267e2c in std.build.Builder.makeOneStep (build)
                return err;
                ^
/home/use/zig/lib/std/build.zig:372:13: 0x25d1f7 in std.build.Builder.make (build)
            try self.makeOneStep(s);
            ^
/home/use/zig/lib/std/special/build_runner.zig:130:21: 0x252b6b in main (build)
            else => return err,
                    ^
error: the following build command failed with exit code 1:
/home/use/iotmonitor/zig-cache/o/96898d5bfd689decb6a87c968614ef0d/build /home/use/zig/build/zig /home/use/iotmonitor /home/use/iotmonitor/zig-cache

https://github.com/mqttiotstuff/iotmonitor/blob/master/build.zig

**Comment by markfirmware** [comment]
These are all bare metal
