### ISSUE TITLE
add std.debug.deepEqual method for testing deep equality.

### ISSUE THREAD

**Issue by lolbinarycat** [ziglang/zig#6511]
with how conservitive the `==` operator is in zig (you can't even compare strings!), this method seems very necessary. It's not that complicated either, just:
1. make sure the types match
2. if the types can be compared with `==`, do that, otherwise, do what is appropriate for the type (dereference pointers, iterate through structs and arrays/slices (comparing recursively),fail for functions, etc.).

I have a version written if it's needed, although I'm quite new to zig, so it's likly I made a mistake somewhere in it.

**Comment by tadeokondrak** [comment]
[std.meta.eql](https://github.com/ziglang/zig/blob/master/lib/std/meta.zig#L490) exists, but it doesn't compare slices by content.

**Comment by IridescentRose** [comment]
`std.mem.eql(u8, string1, string2);` is one way to compare two `[]u8`

**Comment by lolbinarycat** [comment]
oh, I didn't see that because I was looking for something called `deepEqual`, thanks!
