### ISSUE TITLE
Let string literals be coerced into more types.

### ISSUE THREAD

**Issue by lolbinarycat** [ziglang/zig#6512]
It's annoying to see `expected type '[]u8', found '*const [1:0]u8'`.

**Comment by IridescentRose** [comment]
Well, they are two entirely different things.

`[]u8` is a buffer with a length.
`*const [1:0]u8` is a constant pointer to a null terminated u8 array with the exact length of 1.

**Comment by pfgithub** [comment]
Do you want to be able to cast strings into non-constant pointers? `*const [1:0]u8` can be casted to `[]const u8`, but not `[]u8`.

**Comment by IridescentRose** [comment]
If you want to discard the `const` qualifier, your data type must be `var` to begin with - this is due to mutability.

**Comment by lolbinarycat** [comment]
@IridescentRose  I want to be able to return a string. I never had to worry about this kind of thing before, why can't I just write `return "foo"` (currently I have `var a = "foo".*; return &a`)?

**Comment by IridescentRose** [comment]
In this exact case, it's 

```zig
var a : []const u8 = "myString";
return a
```

Making a pointer will not help. Zig is strongly typed, and you can't make assumptions about types that are unsafe

**Comment by lolbinarycat** [comment]
@IridescentRose 
> Making a pointer will not help.
You say it won't help, but my workaround does in fact work, and I'm not sure what you mean by "assumptions about types that are unsafe".

> Zig is strongly typed.
To an extent, yes, but it does have features such as `anytype`, and implicit type coercion (which is what we are discussing).

**Comment by alexnask** [comment]
@lolbinarycat The data backing string literals lives in a constant data section on the executable, thus the pointers to it are constant.  

```rs
fn foo() []u8 {
    var a = "foo".*; return &a;
}
```
This is illegal, you are returning a reference to data on the stack, whose lifetime ends at the end of the function call.  
Currently the compiler doesn't catch this but it is a planned feature.  

If you want some mutable data, you have to control the memory it lives in, usually by allocating it, doing something like:  
```
fn foo(alloc: *std.mem.Allocator) ![]u8 {
    return try alloc.dupe("foo");
}
```

**Comment by IridescentRose** [comment]
```zig
const std = @import("std");

fn getStr() []const u8{
    return "foo";
}

pub fn main() anyerror!void{
    std.debug.warn("{} ", .{getStr()});
}
```
Works perfectly fine. `anytype` and `anyerror` is resolved at comptime, not runtime to a strong type.
