### ISSUE TITLE
wasm32-freestanding imports memset instead of defining it

### ISSUE THREAD

**Issue by fengb** [ziglang/zig#6517]
When targeting `wasm32-freestanding`, Zig uses memset for certain operations, like assigning undefined. Instead of pulling in a statically linked version, Zig now requires an imported function instead:

```zig
export fn blah() void {
    var foo: [1000]u8 = undefined;
}
```

```wat
(module
  (type (;0;) (func (param i32 i32 i32) (result i32)))
  (type (;1;) (func))
  (import "env" "memset" (func $memset (type 0)))
  (func $__wasm_call_ctors (type 1))
  (func $blah (type 1)
```

Looks like this regressed due to #6250

**Comment by andrewrk** [comment]
@alexnask be careful tagging stuff with the wrong stage1/stage2 thing pls, I almost didn't notice this regression
