### ISSUE TITLE
Exclude for loops from backwards branch count

### ISSUE THREAD

**Issue by pfgithub** [ziglang/zig#6520]
For loops can be used to cause long compile times, but the compilation is guaranteed to finish so it doesn't seem necessary to have them increase the backwards branch count.

Currently, functions like `std.mem.split()` add a lot of backwards branches because one is used for every character in the string.

```zig
for("a" ** 2000) |char| {}
```
Currently, this counts as 2000 backwards branches, it should count as 0.

List length changing isn't an issue because this doesn't run forever:

```zig
var list: []const u8 = "0";
for(list) |_| list = list ++ "0";
```

**Comment by andrewrk** [comment]
The same reason branch count is needed for anything else, is why it is also needed for `for`. `for` is no exception.
