### ISSUE TITLE
sometime after September 28, Zig no longer adds openssl runpath to ELF exe

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#6523]
Found this while trying to compile my project https://github.com/marler8997/ziget with the latest compiler on October 3 (0.6.0+006b780d4).

When I link against libcrypto.so.1.1 and libssl.so.1.1 on NixOS, my compiled `ziget` program fails start with:
```
./zig-cache/bin/ziget: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

I had a compiler from September 28 (0.6.0+e60939bfa) and tried that, and it loads successfully.  It looks like the latest compiler is missing the "runpath" from the executable that the compiler from 5 days before was adding.

Compiling with compiler from September 28 (0.6.0+e60939bfa)
```sh
$ readelf -d zig-cache/bin/ziget
...
 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/ikrhqd7kdaahyjc0m8jn0zmhmnlkwy8h-shell/lib64:/nix/store/ikrhqd7kdaahyjc0m8jn0zmhmnlkwy8h-shell/lib:/nix/store/0x3bf23q5lmdq77x5icr7c0ngvz25ms3-openssl-1.1.1g/lib]
...
```

Compiling with latest on October 3 (0.6.0+006b780d4):
```sh
$ readelf -d zig-cache/bin/ziget
...
 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/ikrhqd7kdaahyjc0m8jn0zmhmnlkwy8h-shell/lib64:/nix/store/ikrhqd7kdaahyjc0m8jn0zmhmnlkwy8h-shell/lib]
...
```

Both exes have the same first 2 runpaths, but the one compiled with the latest compiler from October 3 is missing the 3rd runpath:
```
/nix/store/0x3bf23q5lmdq77x5icr7c0ngvz25ms3-openssl-1.1.1g/lib
```

If you'd like to use my ziget project to reproduce this issue, you should be able to run these commands to do so:
```sh
# Note: zig will need to be able to find openssl on your system, I use `nix-shell -p pkgconfig openssl` to set this up on NixOS
zig build -Dopenssl
./zig-cache/bin/ziget
```

**Comment by andrewrk** [comment]
Thanks for the report.

Aha: previous code had this:

```c++
    if (!target->is_native_os) {
        g->each_lib_rpath = false;
    } else {
        g->each_lib_rpath = true;
    }
```

Set the `each_lib_rpath` flag if the OS is native. This makes a lot of things "just work", including NixOS. I will restore this functionality.

**Comment by marler8997** [comment]
Thanks for the fast fix.  I confirmed this now works using 0.6.0+939b4860e
