### ISSUE TITLE
Add function to ArrayList to discard its contents but keep its capacity.

### ISSUE THREAD

**Issue by lolbinarycat** [ziglang/zig#6527]
Basically `bytes.Buffer.Reset` from go.

**Comment by Snektron** [comment]
Theres shrinkRetainingCapacity, which you can call with 0 to discard all content

**Comment by lolbinarycat** [comment]
Yeah, that doesn't show up in the documentation.

**Comment by alexnask** [comment]
The stdlib generated documentation is very much a work in progress atm.  
Sorry for the inconvenience, right now you probably need to look into the source code itself in a lot of cases.
