### ISSUE TITLE
implement emit-h

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#6533]
This feature regressed with the merge of #6250 but now it is time to implement this feature in zig's self-hosted compiler.

**Comment by tetsuo-cpp** [comment]
I'm giving this a try.

**Comment by FireFox317** [comment]
@tetsuo-cpp You might want to have a chat with @pixelherodev about this. He started the C-backend in the stage2 compiler, which will take in Zig code and transform it into c code. I think the same backend can be used to generate c header files.

**Comment by pixelherodev** [comment]
I was hoping to do this tonight or tomorrow, but I'm currently busy with 
work for uni.

If you want to work on this. I suggest looking at hooking up 
codegen/c.zig with header generation instead of source.

This probably means generalizing the logic to not depend on a link/c.zig 
instance.

**Comment by tetsuo-cpp** [comment]
Thanks for the information, @FireFox317 and @pixelherodev.
I've been a bit busy too but spent a bit of time on it today. Hopefully, I'll have something ready over the next few days.

**Comment by pixelherodev** [comment]
@tetsuo-cpp I intend to work on the CBE test suite today, and I might get the urge to work on emit-h while I'm at it. Do you still intend to work on it yourself? If you are, that's totally fine, I can find something else to work on, and if not, I'll be happy to do it soon :)

**Comment by tetsuo-cpp** [comment]
@pixelherodev 
I have some WIP code in a branch and was planning to get it in a reviewable state this weekend. Sorry for the delay, I've been flat out this week and haven't had much time until now.

If you can let me finish it off, that'd be awesome. But I don't mind too much either way. It's already been a useful exercise for me to learn about the code in this area.

**Comment by tetsuo-cpp** [comment]
@pixelherodev 
I've opened a PR containing an initial attempt at implementing `emit-h`. I was unsure in a few places so I imagine it needs a bit of work. I had a play around with it and it seems to work ok.
