### ISSUE TITLE
Disallow array parameters in C calling convention functions

### ISSUE THREAD

**Issue by tadeokondrak** [ziglang/zig#6535]
For this C function declaration:
```c
void clear_array_5(char p[5]);
```
`p` is passed as a mutable pointer to an array of char (not guaranteed to be of size 5).

`translate-c` correctly translates this into:
```zig
pub extern fn clear_array_5(p: [*c]u8) void;
```

But Zig also [allows](https://github.com/ziglang/zig/pull/6272#issuecomment-688557160) declaring it as:
```zig
pub extern fn clear_array_5(p: [5]u8) void;
```
and to Zig code it acts takes an array by value. The C code is free to modify the contents of the array, which is against Zig rules.

Even if the C code doesn't modify the array, I don't think there's a reason to allow this form.
It's part of the semantics of C (not the ABI) that `p` is a pointer, and it can always be declared as a pointer in Zig.

Trying to take advantage of this for the specific case of `va_list` (#6272) runs into the issue of having to modify through a parameter that Zig semantics say is passed by value.

**Comment by codehz** [comment]
It is actually a complex problems
What's about extern function from wasm?
Since wasm doesn't have well-defined abi, we can only pass argument type which size < usize's

**Comment by codehz** [comment]
Btw, c99 allow static size array appear in argument list
```c
void clear_array_5(int array[static 5])
```

**Comment by tadeokondrak** [comment]
> What's about extern function from wasm?

Any ABI for wasm will have C support, and C doesn't support passing arrays as parameters by value.

> Btw, c99 allow static size array appear in argument list

Sure, `void foo(int array[static const 5])` could theoretically be a `[5]c_int`.
But what's the benefit there? This is very uncommon syntax.

**Comment by codehz** [comment]
> Any ABI for wasm will have C support

I mean, wasm32 even don't support pass u64 (in some browser implementation like chrome **85**)...

**Comment by andrewrk** [comment]
@tadeokondrak if a C library did `void foo(int array[static const 5]);` what would it look like to match that C ABI with zig code? Is that still just passing a pointer under the hood?

**Comment by codehz** [comment]
@andrewrk 
It should be
| declaration | abi equivalent | comptime constraints |
| ----------- | -------------- | -------------------- |
| int array[static const 5] | int * const | const pointer to int and (optional) compile-time bounds checking (requires array length >= 5) |
| int array[const 5] | int * const | const pointer to int |
| int array[static 5] | int * | pointer to int and (optional) compile-time bounds checking (requires array length >= 5) |
| int array[5] | int * | pointer to int |

and clang will give warning

https://godbolt.org/z/ahrhzW

**Comment by tadeokondrak** [comment]
Yeah, as @codehz says they're always equivalent to pointers.

- `const` means... nothing really since it's C. I believe modifying through it is still defined behaviour.
- `static 5` means the pointer points to at least 5 elements, or you have undefined behaviour.
  - As far as I know, it could also point to more elements, communicated by other means, and modifying those is fine.
  - It's not like Zig's value-passed-by-reference semantics, the pointer value of the parameter is the same as the pointer passed into it.
  - It also means it can't be null, so translate-c could translate it to `[*]T`.

As some proof for the pointer-ness of the argument, clang has a warning for using sizeof on the parameter:
![](https://tadeo.ca/u/AWBZM.png)
