### ISSUE TITLE
Compile error instead of falling back to C for unsupported calling conventions

### ISSUE THREAD

**Issue by tadeokondrak** [ziglang/zig#6536]
Putting a calling convention unsupported for the target is allowed, and silently changed to the C calling convention (get_llvm_cc in stage1).

I'm not sure why this is the behaviour. It seems like an ABI footgun, and it's easily worked around when actually intended.
Clang seems to ignore unsupported calling convention annotations, but emits a warning by default.

**Comment by codehz** [comment]
Stdcall is used for windows x86 api. But it is not exists for another windows arch... So how to handle it?

**Comment by tadeokondrak** [comment]
```zig
const builtin = @import("builtin");
const WINAPI: builtin.CallingConvention = if (builtin.arch == .i386) .Stdcall else .C;
pub extern "kernel32" fn CloseHandle(hObject: HANDLE) callconv(WINAPI) BOOL;
```
is one way to do it.
