### ISSUE TITLE
zig fmt changed files should output to stdout not stderr

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#6545]
https://github.com/ziglang/zig/blob/ab7ea5354101ffaf5c9708ca6398ff7b765b781f/src/main.zig#L2564-L2587

**Comment by lolbinarycat** [comment]
I'll give it a shot.

**Comment by lolbinarycat** [comment]
I think I can get this working on linux fairly easilly, but I have no idea how you would do this on windows (and I don't have a computer to test).

**Comment by lolbinarycat** [comment]
Oh nevermind, I found another function that was missing from the docs.
