### ISSUE TITLE
cannot build cpp files when the target is specified (for msvc abi)

### ISSUE THREAD

**Issue by codehz** [ziglang/zig#6567]
env: win10 x64 w/ vs2019
files:
build.zig
```zig
const Builder = @import("std").build.Builder;

pub fn build(b: *Builder) void {
    const target = b.standardTargetOptions(.{});
    const mode = b.standardReleaseOptions();

    const exe = b.addExecutable("demo", null);
    exe.linkLibC();
    exe.addCSourceFile("src/main.cpp", &[_][]const u8{});
    exe.setTarget(target);
    exe.setBuildMode(mode);
    exe.install();

    const run_cmd = exe.run();
    run_cmd.step.dependOn(b.getInstallStep());

    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);
}
```

src/main.cpp:
```cpp
#include <windows.h>

int main() {}
```

result:

command:
`zig build -Dtarget=$arch-$os-$abi`

| arch | os | abi | result |
| ---- | -- | --- | ------ |
|(null)|(null)|(null)|pass|
|native|native|msvc|pass|
|x86_64|native|msvc|pass|
|i386|native|msvc|`lld: error: <root>: undefined symbol: _mainCRTStartup`|
|aarch64|native|msvc|tons of link error: `lld: error: libcmtd.lib(exe_main.obj): machine type x64 conflicts with arm64`|
|native|windows|msvc|`fatal error: 'windows.h' file not found`|
|x86_64|windows|msvc|`fatal error: 'windows.h' file not found`|
|i386|windows|msvc|`fatal error: 'windows.h' file not found`|
|aarch64|windows|msvc|`fatal error: 'windows.h' file not found`|
|x86_64|windows.win10_20h1...win10_20h1|msvc|`fatal error: 'windows.h' file not found`|

**Comment by alexnask** [comment]
@codehz Hi, do you have MSVC installed?  
Can you run `zig libc` and report on the output, if you do have MSVC installed?

**Comment by codehz** [comment]
> @codehz Hi, do you have MSVC installed?
> Can you run `zig libc` and report on the output, if you do have MSVC installed?

Of curse,

```
# The directory that contains `stdlib.h`.
# On POSIX-like systems, include directories be found with: `cc -E -Wp,-v -xc /dev/null`
include_dir=D:\Windows Kits\10\Include\10.0.18362.0\ucrt

# The system-specific include directory. May be the same as `include_dir`.
# On Windows it's the directory that includes `vcruntime.h`.
# On POSIX it's the directory that includes `sys/errno.h`.
sys_include_dir=D:\VisualStudio\Community\VC\Tools\MSVC\14.27.29110\include

# The directory that contains `crt1.o` or `crt2.o`.
# On POSIX, can be found with `cc -print-file-name=crt1.o`.
# Not needed when targeting MacOS.
crt_dir=D:\Windows Kits\10\Lib\10.0.18362.0\ucrt\x64

# The directory that contains `vcruntime.lib`.
# Only needed when targeting MSVC on Windows.
msvc_lib_dir=D:\VisualStudio\Community\VC\Tools\MSVC\14.27.29110\lib\x64\

# The directory that contains `kernel32.lib`.
# Only needed when targeting MSVC on Windows.
kernel32_lib_dir=D:\Windows Kits\10\Lib\10.0.18362.0\um\x64
```

**Comment by alexnask** [comment]
Hm, curious.  
Thanks for the report, will look into this later today

**Comment by andrewrk** [comment]
Thanks for the report. This is all working as designed. I suggest to use the `gnu` ABI, which is planned to become the default (see #6565). MSVC ABI will be kept because sometimes it could be desirable for native builds.
