### ISSUE TITLE
Is there a way to get --verbose-ast to include the tokens and line numbers?

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#6574]
I would like to do some processing on the ast (with concrete tokens) in another tool.

Can the std parse function produce it, perhaps in json format?

**Comment by tadeokondrak** [comment]
`--verbose-ast` is a debugging feature, but you should be able to write a program using `std.zig.parse` to generate any format of AST output.

**Comment by markfirmware** [comment]
Thanks. I just wanted to double check before starting that. Related #4140
