### ISSUE TITLE
Infinite loop on missing/incomplete lib directory

### ISSUE THREAD

**Issue by lun-4** [ziglang/zig#6584]
Steps to reproduce:
 - Used zig `0.6.0+7f7e2d608` from the downloads page
 - Copied `zig` to `/usr/bin/zig`
 - Didn't add a valid lib directory on `/usr/lib/zig`
 - Build anything (`zig run hello-world.zig`)
 - Compiler locks up with 90% CPU usage

I later saw in strace a continuous loop of:
```
openat(AT_FDCWD, "/", O_RDONLY|O_CLOEXEC|O_PATH|O_DIRECTORY) = 3
openat(3, "lib/zig", O_RDONLY|O_CLOEXEC|O_PATH|O_DIRECTORY) = -1 ENOENT (No such file or directory)
openat(3, "lib", O_RDONLY|O_CLOEXEC|O_PATH|O_DIRECTORY) = 4
openat(4, "std/std.zig", O_RDONLY|O_NOCTTY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
close(4)                                = 0
close(3)                                = 0
```

Lockup is only fixed by having `/usr/lib/zig/std/std.zig`.

**Comment by LemonBoy** [comment]
`findZigLibDirFromSelfExe` calls `fs.path.dirname` to turn `/usr/bin/zig` into `/usr/bin` and `/usr` and `/` and `/` and `/` and `/`...

**Comment by FireFox317** [comment]
Related: #6503
