### ISSUE TITLE
`zig build` without a build.zig file in any parant directories loops forever

### ISSUE THREAD

**Issue by FireFox317** [ziglang/zig#6592]
Error is somewhere here:
https://github.com/ziglang/zig/blob/58502b8bfec51f04ad12ec65b0d52452e179256a/src/main.zig#L2191-L2211

**Comment by LemonBoy** [comment]
`dirname` strikes again, see #6584

**Comment by FireFox317** [comment]
One solution might be to keep track of the previous path searched, and if the previous path is the same as the current path bail out

**Comment by markmarsella** [comment]
PR #6602 fixes this issues
