### ISSUE TITLE
Rename @TagType to @Tag

### ISSUE THREAD

**Issue by tadeokondrak** [ziglang/zig#6609]
Since the capitalization already makes it clear it's a type.

**Comment by tadeokondrak** [comment]
This could actually just be removed in favour of a std.meta function.

**Comment by mb64** [comment]
I think `@TagType` is fine.  The existence and use of capitalization conventions doesn't mean that every use of "Type" in an identifier needs to be removed, even though, strictly speaking, it is redundant.  For instance, it would be silly to rename `@TypeOf` to `@Of`.

Of course, I'm not saying that *nothing* should be renamed, just that there are vastly more important criteria, such as which of `@TagType` and `@Tag` makes code more readable.  IMO `@TagType` would be more readable, but I'm not sure.  It's an important question, and I would hate to see this changed without any mention of readability.
