### ISSUE TITLE
Question on the return type of main()

### ISSUE THREAD

**Issue by Prince213** [ziglang/zig#6610]
Is there a particular reason to disallow return types other than 'void', '!void', 'noreturn', 'u8' and '!u8'?

**Comment by tadeokondrak** [comment]
All of the types have actual meaning to the runtime, where u8 provides an exit code to the os, void always provides 0, and noreturn never returns. Any error union for error unions is printed out to standard error before continuing.

https://github.com/ziglang/zig/blob/fe117d9961c3622fda5c359733d01de686509af0/lib/std/start.zig#L256-L292

What other types do you have in mind?

**Comment by Prince213** [comment]
i32

**Comment by Prince213** [comment]
See https://github.com/ziglang/zig/blob/master/lib/std/start.zig#L211

**Comment by tadeokondrak** [comment]
Related: https://github.com/ziglang/zig/issues/6342 and the linked pull request.

**Comment by Prince213** [comment]
How about Windows? [Windows programs don't seem to be limited](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2019#error-codes).

**Comment by Prince213** [comment]
Can we use i32 and check for u8 only on non-Windows hosts?

**Comment by andrewrk** [comment]
Use a Windows specific API if you want to take advantage of Windows specific API: `std.os.windows.ExitProcess(0xabcd)`

Otherwise, this issue is covered by #6342
