### ISSUE TITLE
diagnose and fix bug in mach-o LLD code: invalid x86_64 Reference Kind

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#662]
Right now we have this patch applied to our in-tree fork of LLD:

https://github.com/zig-lang/zig/commit/ddca67a2b94f68985789fc8254fd1326e26269f6

It's an ugly workaround and does not solve the root cause. It's currently the only patch we have on top of LLD. If we fix this then we can go back to using upstream LLD.

Upstream bug: https://bugs.llvm.org/show_bug.cgi?id=32254

The bug is triggered by trivial hello world code. It seems the Mach-O LLD code is not well supported by the LLD team. Zig project will have to pick up the slack.

**Comment by andrewrk** [comment]
Related: #1535

**Comment by LemonBoy** [comment]
I've sent a [patch](https://reviews.llvm.org/D62185) upstream.

**Comment by andrewrk** [comment]
This has been fixed in trunk. We can finally drop the last LLD patch when LLVM 10 is released.
