### ISSUE TITLE
Struct "inheritance"

### ISSUE THREAD

**Issue by jarble** [ziglang/zig#6632]
I want to define a struct that "inherits" some methods from another struct, but I'm not sure if this is possible yet.

I have two structs here: `Example1` should be a "subclass" of `Example`:

```
const Example = struct {
    pub fn add(a:i32,b:i32) i32{
        return a+b;
    }
}

const Example1 = struct {
    //how can I "extend" this struct from Example1?
    pub fn sub(a:i32,b:i32) i32{
        return a+b;
    }
}
```
I can manually copy the methods from the first struct, but this is too redundant:
```
const Example1 = struct {
    //how can I "extend" this struct from Example1?
    pub fn sub(a:i32,b:i32) i32{
        return a+b;
    }
    pub fn add(a:i32,b:i32) i32{
        return a+b;
    }
}
```
Is there another way to define a struct that "inherits" methods from another struct?

**Comment by zigazeljko** [comment]
> Is there another way to define a struct that "inherits" methods from another struct?

You can do it with `usingnamespace` like this:

```zig
const Example1 = struct {
    pub usingnamespace Example;
    pub fn sub(a: i32, b: i32) i32 {
        return a + b;
    }
};
```

**Comment by andrewrk** [comment]
[Here are some places to ask questions](https://github.com/ziglang/zig/wiki/Community)

**Comment by Diegovsky** [comment]
> > Is there another way to define a struct that "inherits" methods from another struct?
> 
> You can do it with `usingnamespace` like this:
> 
> ```zig
> const Example1 = struct {
>     pub usingnamespace Example;
>     pub fn sub(a: i32, b: i32) i32 {
>         return a + b;
>     }
> };
> ```

This is not enough since fields aren't inherited and methods don't work since they ask for the parent struct instead of the current one

The following example should compile if `usingnamespace` did what I expected it to do:

```zig
const std = @import("std");

const S = struct {
    a: i32,

    pub fn add(self: @This(), b: i32) i32 {
        return self.a + b;
    }
};

const D = struct {
    pub usingnamespace S;
    b: i32,

    pub fn sum(self: @This(), b: i32) i32 {
        return self.a + self.b + b;
    }
};

pub fn main() !void {
    const d = D {.a = 10, .b = 20};
    std.debug.print("{d}\n", .{d.sum(30)});
}
```

However, I get the following error trying to compile it:
```
/tmp/tmp.yAAeGOu2ev/src/main.zig:21:19: error: no field named 'a' in struct 'main.D'
    const d = D {.a = 10, .b = 20};
                  ^
/tmp/tmp.yAAeGOu2ev/src/main.zig:11:11: note: struct declared here
const D = struct {
          ^~~~~~
```

Also, copying the `a` fields still does not yield satisfactory results. Here's the updated code, that still does not work:

```zig
const std = @import("std");

const S = struct {
    a: i32,

    pub fn add(self: @This(), b: i32) i32 {
        return self.a + b;
    }
};

const D = struct {
    pub usingnamespace S;
    b: i32,
    a: i32,

    pub fn sum(self: @This(), b: i32) i32 {
        return self.add(self.a) + b;
    }
};

pub fn main() !void {
    const d = D {.a = 10, .b = 20};
    std.debug.print("{d}\n", .{d.sum(30)});
}
```

Here's the error btw:
```
/tmp/tmp.yAAeGOu2ev/src/main.zig:17:20: error: no field or member function named 'add' in 'main.D'
        return self.add(self.a) + b;
               ~~~~^~~~
/tmp/tmp.yAAeGOu2ev/src/main.zig:11:11: note: struct declared here
const D = struct {
          ^~~~~~
referenced by:
    main: /tmp/tmp.yAAeGOu2ev/src/main.zig:23:33
    callMain: /usr/lib/zig/std/start.zig:578:32
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

error: tmp.yAAeGOu2ev...
error: The following command exited with error code 1:
/usr/bin/zig build-exe /tmp/tmp.yAAeGOu2ev/src/main.zig --cache-dir /tmp/tmp.yAAeGOu2ev/zig-cache --global-cache-dir /home/diegovsky/.cache/zig --name tmp.yAAeGOu2ev --enable-cache 
error: the following build command failed with exit code 1:
/tmp/tmp.yAAeGOu2ev/zig-cache/o/ac819fc15f999c11baabd2374e788525/build /usr/bin/zig /tmp/tmp.yAAeGOu2ev /tmp/tmp.yAAeGOu2ev/zig-cache /home/diegovsky/.cache/zig
```

Zig version: `0.10.0-dev.4474+b41b35f57`

**Comment by nektro** [comment]
`usingnamespace` has no affect on fields, and Zig has no way to achieve inheritance.

the intended method is to have a field with the type of the parent and make methods you need call on that one

**Comment by Diegovsky** [comment]
So you are aggreeing with me `usingnamespace` is not a solution to the issue raised?

Also, for my problem specifically, I needed to add methods to a struct, and I tried doing it with `usingnamespace`, like so:
```zig
fn BaseInfoChild(comptime Raw: type) type {
    return struct {
        raw: *Raw,

        const This = @This();
        pub const Super = BaseInfo;

        pub fn fromC(raw: [*c]Raw) This {
             // ommited
        }

        pub fn upcast(self: This) Super {
             // ommited
        }

        pub fn ref(self: This) This {
            // ommited
        }

        pub fn unref(self: This) void {
            // ommited
        }

    };
}

pub const StructInfo = struct {
    pub usingnamespace BaseInfoChild(Raw);
    // ommited
```

But it does not work as intended because `This` (in the `BaseInfoChild` function) is incompatible with `StructInfo`. I also tried adding `Self` param to the `BaseInfoChild` function but I always end up with `struct depends on itself`. I just want a faster way fo copy-paste a bunch of methods inside a struct.
