### ISSUE TITLE
Comptime Struct Field Assignment

### ISSUE THREAD

**Issue by nsmryan** [ziglang/zig#6656]
I ran into a strange situation with struct fields that are declared comptime. It appears that they must be assigned an initial value in their declaration (which makes sense), but then assigning them explicitly does not change this value. 

The code below is accepted and runs, but the value set in the initialization of the struct (in the init function) is not used. This causes the final testing.expect to fail because the value of 'id' is still true.

```
const std = @import("std");
const testing = std.testing;

const State = struct {
    comptime id: bool = true,

    pub fn init(comptime id: bool) State {
        return State{ .id = id };
    }
};

test "test states" {
    var s1 = State.init(true);
    testing.expect(s1.id == true);

    var s2 = State.init(false);
    testing.expect(s2.id == false);
}
```

This may be the expect behavior for comptime fields, but it seems that the 'init' function shouldn't compile in this case.

The purpose of this code was an attempt to perform compile-time checking of state transitions. Type parameters work, but only allow a single output state (perhaps a minor limitation). Without the ability to be generic over the output type (as far as I can tell) the only way I could think to write a function that might return different states was comptime assertions on a comptime field which held the current state.

**Comment by DutchGhost** [comment]
This is covered by https://github.com/ziglang/zig/issues/5895 !

**Comment by andrewrk** [comment]
Expected behavior is a compile error when you try to set `id = false`.
