### ISSUE TITLE
@embedFile can't find absolute paths

### ISSUE THREAD

**Issue by mattnite** [ziglang/zig#6662]
I've been using `@embedFile` in some type generation using files in sysfs in linux, I'm not sure what's happened but it can no longer find absolute paths even when they exist:
```
error: unable to find '/sys/kernel/debug/tracing/events/syscalls/sys_enter_open/format'
```

**Comment by Sobeston** [comment]
I believe embedFile is only intended to work within your project directory, so this isn't a bug. Could you work around it with a sym link?

**Comment by mattnite** [comment]
It would actually make a lot of sense for the user to copy files locally over the absolute path method, but documentation does say:
```
path is absolute or relative to the current file, just like @import.
```
And it was working before so it seems like this is a regression

**Comment by andrewrk** [comment]
The eventual intended usage is that you can only import or embed files that are within the same package, or exposed via the package system. However, that hasn't been fully figured out or implemented yet, so until it can handle this use case, the regression needs to get fixed. I'm guessing it should be a straightforward fix since it recently broke, and can be done before 0.7.0.

**Comment by LemonBoy** [comment]
It's not a regression, it's just that:

* Regular users can't access `/sys/kernel/debug/tracing/events/syscalls/sys_enter_open/format`
* The zig compiler is getting `EACCESS`...
* ..but `stage2_fetch_file` is discarding it and instead returns `ErrorFileNotFound`

**Comment by mattnite** [comment]
I still get this with root permissions

**Comment by LemonBoy** [comment]
> I still get this with root permissions

My crystal ball is broken, can you check with `strace -e trace=open,openat zig <whatever>` if what you're getting is `EACCESS` or something else?

**Comment by andrewrk** [comment]
```zig
export fn a() usize {
    return @embedFile("/root/foo").len;
}
```

```
$ ./zig-out/bin/zig build-obj test.zig 
test.zig:2:12: error: embed of file outside package path: '/root/foo'
    return @embedFile("/root/foo").len;
           ^
```

Working as designed in self-hosted
