### ISSUE TITLE
c allocator assertion failure in i386-windows-gnu

### ISSUE THREAD

**Issue by codehz** [ziglang/zig#6674]
```
D:\Soft\zig\current\lib\zig\std\debug.zig:225:14: 0xf3332f in std.debug.assert (tjs.o)
    if (!ok) unreachable; // assertion failure
             ^
D:\Soft\zig\current\lib\zig\std\heap.zig:47:11: 0xf330f1 in std.heap.cAlloc (tjs.o)
    assert(ptr_align <= @alignOf(c_longdouble));
          ^
>>>>>>>>>> NOTE: ptr_align == 8 and @alignOf(c_longdouble) == 4 <<<<<<<
D:\Soft\zig\current\lib\zig\std\mem\Allocator.zig:294:40: 0xf89721 in std.mem.Allocator.allocAdvancedWithRetAddr (tjs.o)
    const byte_slice = try self.allocFn(self, byte_count, a, len_align, return_address);
                                       ^
D:\Soft\zig\current\lib\zig\std\mem\Allocator.zig:262:41: 0xf895bd in std.mem.Allocator.allocAdvanced (tjs.o)
    return self.allocAdvancedWithRetAddr(T, alignment, n, exact, @returnAddress());
                                        ^
D:\Soft\zig\current\lib\zig\std\array_list.zig:374:59: 0xf864e7 in std.array_list.ArrayListAlignedUnmanaged(mods.Data,null)::std.array_list.ArrayListAlignedUnmanaged(mods.Data,null).initCapacity (tjs.o)
            const new_memory = try allocator.allocAdvanced(T, alignment, num, .at_least);
                                                          ^
D:\Project\tinysh\src\mods.zig:421:73: 0xf833a2 in mods.FunctionInfo::mods.FunctionInfo.invoke (tjs.o)
                var argsdata = std.ArrayListUnmanaged(Data).initCapacity(allocator, args.len) catch return ctx.throw(.OutOfMemory);
```

And it is working if I removed the assert...
but why @alignOf(c_longdouble) == 4?

**Comment by LemonBoy** [comment]
#6385 solves your problems and answers your questions

**Comment by codehz** [comment]
duplicated with #3783

**Comment by andrewrk** [comment]
FYI note that with 13cccdd92cd89242801218aa808dec1df14f482d which is this:

https://github.com/ziglang/zig/blob/13cccdd92cd89242801218aa808dec1df14f482d/lib/std/c.zig#L336-L344

which is based on:

https://github.com/ziglang/zig/blob/13cccdd92cd89242801218aa808dec1df14f482d/lib/include/__stddef_max_align_t.h#L13-L25

And then:

```diff
--- a/lib/std/heap.zig
+++ b/lib/std/heap.zig
@@ -43,7 +43,7 @@ var c_allocator_state = Allocator{
 };
 
 fn cAlloc(self: *Allocator, len: usize, ptr_align: u29, len_align: u29, ret_addr: usize) Allocator.Error![]u8 {
-    assert(ptr_align <= @alignOf(c_longdouble));
+    assert(ptr_align <= @alignOf(std.c.max_align_t));
     const ptr = @ptrCast([*]u8, c.malloc(len) orelse return error.OutOfMemory);
     if (len_align == 0) {
         return ptr[0..len];
```

That alone would have solved this issue.

I'm actually wondering now whether we should make `std.heap.c_allocator` be this simple fix, and have it continue to assert alignment is small enough, and introduce `std.heap.aligned_c_allocator` which has the new fancy logic.

What do you think, @LemonBoy?

**Comment by LemonBoy** [comment]
> I'm actually wondering now whether we should make std.heap.c_allocator be this simple fix, and have it continue to assert alignment is small enough, and introduce std.heap.aligned_c_allocator which has the new fancy logic.

You're making the API overcomplicated for no reason.

A single assertion is not enough to make the allocator safe as it will be elided at high optimization levels, meaning the allocator will happily hand you a under-aligned chunk of memory. You're bound to crash and burn somewhere after that allocation, after all the allocator requested a specific alignment for a reason, and Murphy's law tells us it'll certainly happen on a system where you can't easily attach gdb and figure out what's wrong.

So the assertion must be turned into an hard error, meaning the ball is back into the user court and they have to be aware of this extra failure mode. A failure mode you can't easily work around (the allocator may be a user parameter, you can't just pick another one), the error will probably bubble up to the unsuspecting user and that's... bad?

The `c_allocator` (I wrote a few lines about renaming it in #6385) should follow the allocator protocol and try its best to work around the libc limitations. If the user wants to avoid the "overhead" (numbers needed, pulling adjectives such as "slower" or "faster" out of thin air is not ok) they can freely choose between directly calling `c.malloc` or using one of the thousand different allocators in the stdlib.

`raw_c_allocator` is not needed.

**Comment by andrewrk** [comment]
Opened a new proposal to continue the discussion =>  #7172
