### ISSUE TITLE
zig cc segfault when linking against macOS frameworks

### ISSUE THREAD

**Issue by mkeeter** [ziglang/zig#6675]
Here's a simple test case:
```
int test(void) {
    return 1;
}
```

Running with `zig cc` and trying to link against `Cocoa` produces a segfault:
```
zig cc -F /System/Library/Frameworks -framework Cocoa darwin.c

fish: 'zig cc -F /Syste…' terminated by signal SIGSEGV (Address boundary error)
```

Running with system `cc` "works" (up to the point of printing an error):
```
cc -F /System/Library/Frameworks -framework Cocoa darwin.c

Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If you remove `-framework Cocoa`, `zig cc` similarly "works":
```
Undefined symbol: C entry: _main
symbol(s) not found
error: LLDReportedFailure
```

Interestingly, if I add `-c` to the `zig cc` invocation, it works fine (producing an object file), so maybe this is just an issue in error handling (when `_main` is missing)?

**Comment by jedisct1** [comment]
Can you reproduce this with my `bigsur` branch? (even if you are not using Big Sur)
https://github.com/jedisct1/zig/tree/bigsur

**Comment by kubkon** [comment]
This is an LLD problem. I've actually submitted an issue for this directly to upstream: https://bugs.llvm.org/show_bug.cgi?id=48019. As one LLVM dev rightly points out, this is a problem with old, outdated MachO LLD backend which is currently receiving a full rewrite. Having said that, the new backend is currently not fully functional so we need to monitor the situation closely. Perhaps by the time LLVM12 is out this might get resolved. Anyhow, I'm marking the issue as upstream.

**Comment by mikdusan** [comment]
silly question but does `darwin.c` define a `main()` ?

**Comment by mkeeter** [comment]
Yes, that's correct!

As another data point, I just retested on macOS 10.14 and the latest Zig nightly (`zig-macos-x86_64-0.8.0-dev.1457+89e522b93`), and am now seeing a `SIGABRT` instead of a `SIGSEGV`, which is definitely progress!

```
fish: 'zig cc -F /System/Library/Frame…' terminated by signal SIGABRT (Abort)
```

**Comment by mikdusan** [comment]
ok we're handling that error now; patch incoming:

<img width="736" alt="image" src="https://user-images.githubusercontent.com/48141240/111010467-a26db880-8364-11eb-993c-0d54a32332ff.png">
