### ISSUE TITLE
@intToFloat bug on bigger numbers?

### ISSUE THREAD

**Issue by brotherdetjr** [ziglang/zig#6683]
Hi all,

It seems, there's a bug in `@intToFloat` on bigger numbers (bigger than 64-bit).
```
const i: u65 = 0x1_0000_0000_0000_0000; // fits in 65-bit integer! this line is ok. In fact, I tried up to u112
const f: f128 = @intToFloat(f128, i); // f128's mantissa is 122 bit, must fit
const f0: f128 = 0x1_0000_0000_0000_0000.0;
testing.expectEqual(f0, f); // fails!
```
Fails with the message:
```
expected 5.1922968585348276e+33, found 5.1922968585348276e+33
```
Also tried smth like below to make sure it's not `expectEqual`'s bug:
```
...
testing.expectEqual(0, f0 - f); // same effect, fails!
```
However, it works if the number one less:
```
const i: u65 = 0xffff_ffff_ffff_ffff;
const f: f128 = @intToFloat(f128, i);
const f0: f128 = 0xffff_ffff_ffff_ffff.0;
testing.expectEqual(f0, f); // passes!
```
Zig version: 0.6.0+04b0ffdd1
Operating System: elementary OS 0.4.1 Loki (Ubuntu-like)
Kernel: Linux 4.15.0-72-generic
Architecture: x86-64

Is there any simple way to do `std.fmt.formatFloatDecimal` but for `f128`? I could do more diagnostics.

Cheers,
Denis

**Comment by LemonBoy** [comment]
> Is there any simple way to do std.fmt.formatFloatDecimal but for f128?

Pretty much everything is broken for `f128` (eg. printing scales them down to `f64`), you can `@bitCast(u128, value)` and inspect the sign/mantissa/exponent separately.
