### ISSUE TITLE
Building stage2 with LLVM enabled on Arch Linux requires linking against dynamic libraries

### ISSUE THREAD

**Issue by kubkon** [ziglang/zig#6692]
On Arch Linux, as per our [Wiki](https://github.com/ziglang/zig/wiki/Troubleshooting-Build-Issues#arch-linux), clang package isn't built with static libs, and this leads to two problems with building stage2 with `-Denable-llvm`. Firstly, `config.h` is missing `llvm_config_exe` path (unless this is unrelated and only appears on my installation), and secondly, the standard invocation

```
build/bin/zig build --prefix $(pwd)/stage2 -Denable-llvm
```

ends up trying to link in `/usr/lib/libclang-cpp.so` which is currently unimplemented.

**Comment by andrewrk** [comment]
> which is currently unimplemented

can you clarify? what exactly is currently unimplemented?

**Comment by kubkon** [comment]
I thought that we could only link against static libs, but maybe I'm mistaken? Here's the full output:

```
dev/zig » build/bin/zig build --prefix $(pwd)/stage2 -Denable-llvm -Dlog=link
error: linking against dynamic libraries not yet supported
zig...The following command exited with error code 1:
/home/kubkon/dev/zig/build/bin/zig build-exe /home/kubkon/dev/zig/src/main.zig /home/kubkon/dev/zig/build/zigcpp/libzigcpp.a /usr/lib/liblldDriver.a /usr/lib/liblldMinGW.a /usr/lib/liblldELF.a /usr/lib/liblldCOFF.a /usr/lib/liblldMachO.a /usr/lib/liblldWasm.a /usr/lib/liblldReaderWriter.a /usr/lib/liblldCore.a /usr/lib/liblldYAML.a /usr/lib/liblldCommon.a /usr/lib/libclang-cpp.so --library LLVM-11 /usr/lib/libstdc++.a --library c --pkg-begin build_options /home/kubkon/dev/zig/zig-cache/zig_build_options.zig --pkg-end --cache-dir /home/kubkon/dev/zig/zig-cache --name zig -I /home/kubkon/dev/zig/src -I /home/kubkon/dev/zig/build -I /usr/include -I /usr/include -L /usr/lib --enable-cache 
error: the following build command failed with exit code 1:
/home/kubkon/dev/zig/zig-cache/o/291f6c2fdee1e154f811ae94e5b2d406/build /home/kubkon/dev/zig/build/bin/zig /home/kubkon/dev/zig /home/kubkon/dev/zig/zig-cache --prefix /home/kubkon/dev/zig/stage2 -Denable-llvm -Dlog=link
```

**Comment by andrewrk** [comment]
Ahh I see. That error message is coming from the CLI arg parser. I think the solution to that might be as simple as appending them to `link_objects` a few lines above, just like objects and static libraries.

**Comment by kubkon** [comment]
Oh, cool. I'll play with it and report back. If this solves it then I'll submit a patch as well :+1:
