### ISSUE TITLE
Proposal: Make std.meta.Int accept a signedness parameter

### ISSUE THREAD

**Issue by jprudil** [ziglang/zig#6697]
Currently, Zig's `std.meta.Int` function looks like [this](https://github.com/ziglang/zig/blob/master/lib/std/meta.zig#L681-L688).
I propose the following change:
```zig
const Signedness = enum {
    u,
    i,
};

pub fn Int(comptime signedness: Signedness, comptime bit_count: u16) type {
    return @Type(TypeInfo{
        .Int = .{
            .is_signed = signedness == .i,
            .bits = bit_count,
        },
    });
}
```

Compare the following calls:
```zig
std.meta.Int(true, 32);
std.meta.Int(.i, 32);

std.meta.Int(false, 16);
std.meta.Int(.u, 16);
```

I think the proposed version looks much cleaner and closer to how one would normally write an integer type.  
Note that this doesn't (and doesn't attempt to) change the TypeInfo representation of an integer and only changes the convenience std.meta API.

**Comment by MasterQ32** [comment]
Yes, please! I only want one change: `.unsigned` and `.signed`
