### ISSUE TITLE
Cant compile structs with timespec from musl libc

### ISSUE THREAD

**Issue by maringuu** [ziglang/zig#6702]
Hello,
I'm not sure where to report this but I think the error is in zig and not in musl.
I currently can't test with glibc but it worked a week ago before I switched to musl.

I can't compile (with the 0.6 and master versions of zig) the following:

`main.zig`
```
const c = @cImport({
    @cInclude("crash.h");
});

pub fn main() void {
    const foobar: c.foo = undefined;
}
```

`crash.h`
```
#ifndef _CRASH_H
#define _CRASH_H

#include <time.h>

struct foo {
	struct timespec bar;
};

#endif
```

When compiling with `zig build-exe -lc -I. main.zig` I get the following error messages:
```
zig-cache/o/1QBKyqQD7kLHJlhoCNMXT5wbPCc96MtwERrm4GmtTO75FIB9OM9P-TaGnN0SK1St/cimport.zig:63:5: error: opaque types have unknown size and therefore cannot be directly embedded in structs
    bar: struct_timespec,
    ^
./main.zig:6:27: note: referenced here
    const foobar: c.foo = undefined;
```

The c equivalent of this code compiles fine
`main.c`
```
#include "crash.h"

int main() {
    struct foo foo;
}
```

**Comment by tadeokondrak** [comment]
This is https://github.com/ziglang/zig/issues/1499.

**Comment by maringuu** [comment]
Thank you!
