### ISSUE TITLE
introduce a thread-local Cryptographically Secure Pseudo Random Number Generator for general use

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#6704]
@jedisct1 writes in https://github.com/ziglang/zig/pull/6622#issuecomment-706247338:

> In C, at least on BSD, macOS and WASI (libc), the problem was solved with arc4random(), that automatically seeds a local CSPRNG from the system once and then uses a stream cipher to quickly derive everything else from it, in a thread-safe way. On OpenBSD, absolutely all the base applications requiring secure random numbers use this and nothing else. This is fast, simple and safe.

> In Rust, rand::thread_rng() does the same and is what virtually everyone mechanically uses when secure random numbers are required (or OsRng but arbitrarily). This is simple and safe to use from anywhere, and doesn't require passing states around.

> Would it be worth having something similar? We currently have crypto.getRandom() that has the above security guarantees, but requires a syscall every time some output is needed. It also doesn't implement the Rand interface.

The idea behind it being thread-local is that it would not cause any contention or syscalls when multiple threads simultaneously want to use a CSPRNG. However, I do think we should use comptime logic to detect if `arc4random` will be available, and use that as the backing function call instead of duplicating RNG code in the runtime binary. This should be handled transparently so that a higher level interface does not have to care about these details.

There are several calllsites right now that use `std.crypto.randomBytes` which would be improved to use this API because it would prevent unnecessary syscalls. Even the initial seed syscall can be elided in some cases; for example it would be appropriate for zig start code to use AT_RANDOM from the linux "auxval" to perform the initial seed in the main thread.

One thing to consider is, optimally, we would not want to pay the cost of initializing the RNG before main() and with the spawn of each thread, and the cost of the Thread Local Storage, and the cost of the binary bloat, if the RNG does not end up being used. It is unclear how this could be accomplished, however, I am OK with proceeding on this now and trying to solve this optimization problem later.

**Comment by LemonBoy** [comment]
> we would not want to pay the cost of initializing the RNG before main() and with the spawn of each thread, and the cost of the Thread Local Storage, and the cost of the binary bloat, if the RNG does not end up being used.

The space requirement for the Gimli rng are negligible as it only uses 48 bytes of memory.

Fetching entropy at startup is also needed to initialize the stack canaries (not yet implemented, we need a way to tell LLVM not to emit the stack protector sequence in the early startup functions).
All things considered the overhead of a `getentropy` call is a droplet of piss in the ocean if compared to the process spawning/thread creation sequence.

On Linux you get 16 bytes of good :tm: entropy for free via the `AT_RANDOM` that may not be enough to properly seed the rng (Gimli needs 32 bytes) and deriving a seed from a non csprng may not be ideal here.

**Comment by daurnimator** [comment]
> On Linux you get 16 bytes of good tm entropy for free via the `AT_RANDOM` that may not be enough to properly seed the rng (Gimli needs 32 bytes)

16 bytes is sufficient (cryptographically); it would be safe to extend. See https://github.com/ziglang/zig/pull/6622#discussion_r502792906 for further discussion.

> deriving a seed from a non csprng may not be ideal here.

It [comes straight out of the kernel CSPRNG](https://elixir.bootlin.com/linux/v5.9.1/source/fs/binfmt_elf.c#L231) via [`get_random_bytes`](https://elixir.bootlin.com/linux/v5.9.1/source/drivers/char/random.c#L1571) (however in early boot it might not be seeded well; same as calling `getrandom` with `GRND_NONBLOCK` set).

**Comment by LemonBoy** [comment]
> It comes straight out of the kernel CSPRNG via get_random_bytes (however in early boot it might not be seeded well; same as calling getrandom with GRND_NONBLOCK set).

I was talking of the idea of stretching the 16 (or 8, if we don't want to reuse the first 8) bytes of `AT_RANDOM` with another RNG, the same way you use SplitMix to seed a Xoroshiro RNG.

> 16 bytes is sufficient (cryptographically); it would be safe to extend. See #6622 (comment) for further discussion.

I'll take your word on this.
