### ISSUE TITLE
simplify translate-c implementation by introducing a new pseudo-ast data structures

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#6710]
Right now working on translate-c code is awkward because we have to simultaneously create AST nodes, which is a tree structure, while outputting a list of tokens and source in a linear order. If we had a more specialized AST data structure for translate-c, we could generate the token list and source from it instead of having to duplicate the logic.

It ends up causing bugs like this:  #6707

And this hack:

https://github.com/ziglang/zig/blob/245d98d32dd29e80de9732f415a4731748008acf/lib/std/zig/ast.zig#L26-L28

To explain another way, the current process is:
 * clang analysis => zig AST + source + token list => std.zig.render

Proposed process is:
  * clang analysis => TranslateCNode Tree => zig AST + source + token list => std.zig.render

The translate-c node tree data structure does not need to map to zig AST, it just has to be whatever is convenient for the translate-c implementation.

This probably would have a small performance penalty; the main objective with this proposal is to increase maintainability.

cc @Vexu

**Comment by tadeokondrak** [comment]
Is it worth having any sort of tree over string output?

**Comment by andrewrk** [comment]
In my experience the tree structure feels helpful for the implementation, and the linear string output is the tricky part to manage.

**Comment by LemonBoy** [comment]
A **typed** C AST is also useful to simplify the `boolToInt`/`intToBool` insertion logic and perform several other simplifications over the C code.

**Comment by Vexu** [comment]
This would definitely make translate-c easier to maintain by removing all the strange `appendToken`s needed to please Zig fmt. However generating two ASTs and adding some more type analysis seems like it could be more than a small performance penalty with something like `zig translate-c /usr/include/epoxy/gl.h -I/usr/include` already taking ~22s.

**Comment by LemonBoy** [comment]
> it could be more than a small performance penalty with something like zig translate-c /usr/include/epoxy/gl.h -I/usr/include already taking ~22s.

Did you profile it? What are the bottlenecks?
Keep in mind that if the caching system works as expected the overall impact is near to zero.

**Comment by pixelherodev** [comment]
It'd also let us write a C-AST -> ZIR path for stage2 and allow `zig cc` to work without LLVM ;)

**Comment by pixelherodev** [comment]
> However generating two ASTs and adding some more type analysis seems like it could be more than a small performance penalty with something like zig translate-c /usr/include/epoxy/gl.h -I/usr/include already taking ~22s.

If it gets slower, but _more correct_, then that is performance well spent.
