### ISSUE TITLE
Compiler can't handle paths with ".." on windows

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#6739]
The compiler fails with `error: Unexpected` when a source file has `..` on Windows:
```batch
> mkdir src
> echo "" > src\bug.zig
> zig build-obj src\..\src\foo.zig
error: Unexpected
```

**Comment by daurnimator** [comment]
Duplicate of https://github.com/ziglang/zig/issues/4659 and https://github.com/ziglang/zig/issues/6044
