### ISSUE TITLE
`switch` on Tagged Union in an anytype struct causes broken LLVM instructions and compile error

### ISSUE THREAD

**Issue by fivemoreminix** [ziglang/zig#6755]
I have prepared a few test cases on the release 0.6.0 of Zig in Godbolt's Compiler Explorer:
https://godbolt.org/z/vW53hs

But I found this bug on my machine running Zig version 0.6.0+dbc11be03 and using `std.debug.print` instead of `warn` but this goes to show it's been undetected for a while.

The causation is switching on a tagged union in one of the print functions:
```zig
std.debug.warn("u.name = {}\n", .{switch (u) {
    .Foo => |f| f.name,
    .Bar => |b| b.name,
}});
```

Which causes the following compiler output (on Godbolt, linked above):
```
broken LLVM module found: Instruction does not dominate all uses!
  %8 = getelementptr inbounds %"struct:26:38", %"struct:26:38"* %0, i32 0, i32 0, !dbg !3247
  %17 = bitcast %"[]u8"* %8 to i8*, !dbg !3249

This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
Compiler returned: 255
```

I assume this must be a tagged union issue only because it requires a switch statement.

Also I have no idea what exactly to call this issue so the title was written expecting to be changed.

**Comment by Vexu** [comment]
Fixed in master.
