### ISSUE TITLE
Unable to print type info of pointer type acquired from optional pointer type in if block

### ISSUE THREAD

**Issue by ducrids** [ziglang/zig#6760]
I've been playing with Zig for a little while and I tried doing a couple of things such as one presented below.

```zig
const print = @import("std").debug.print;

pub fn SomeType(comptime T : type) type {
    return struct {
        some_field : i32,
        some_data : ?*T,
    };
}

pub fn main() void {
    var something = SomeType(i32){ .some_field = 0, .some_data = null };
    var some_integer = @as(i32, 1);

    something.some_data = &some_integer;

    if (something.some_data) |some_data| {
        const something_some_data_info = @typeInfo(@TypeOf(something.some_data));
        const some_data_info = @typeInfo(@TypeOf(some_data));

        print("{}\n", .{ something_some_data_info });
        print("{}\n", .{ some_data_info });
    }
}
```

This, unfortunately, doesn't compile due to an error in line 28, which in the end leads to the following problem.

`error: Unable to format type '(null)'`

I suppose doing these sort of things should be legal, but I may be wrong because I've only just been introduced to this programming language.

[https://godbolt.org/z/vWM4We](url) -- godbolt link for reference.

**Comment by data-man** [comment]
Try:
```diff
--- a/lib/std/fmt.zig
+++ b/lib/std/fmt.zig
@@ -496,6 +496,7 @@ pub fn formatType(
             const buffer = [_]u8{'.'} ++ @tagName(value);
             return formatType(buffer, fmt, options, writer, max_depth);
         },
+        .Null => return formatBuf("null", options, writer),
         else => @compileError("Unable to format type '" ++ @typeName(T) ++ "'"),
     }
 }
```

**Comment by michal-z** [comment]
@data-man This should work, but why type is 'null'? Shouldn't it be '*i32'?

**Comment by data-man** [comment]
@michal-z 
This question is not to `std.fmt`. I did just a quick dirty fix. :)

**Comment by ducrids** [comment]
@data-man @michal-z I think it should, at least accroding to the documentation

https://ziglang.org/documentation/master/#Optionals

```zig
fn doAThing(optional_foo: ?*Foo) void {
    // do some stuff

    if (optional_foo) |foo| {
      doSomethingWithFoo(foo);
    }

    // do some stuff
}
```

It states that: _[...]inside the if block, `foo` is no longer an optional pointer, it is a pointer, which cannot be null_.

**Comment by LemonBoy** [comment]
It's just `@typeInfo` that's generating a field with `Null` type (the `sentinel` field), the fmt patch is exactly what's needed.
