### ISSUE TITLE
Design Flaw: Assigning an undefined pointer to an optional may cause it to be null

### ISSUE THREAD

**Issue by SpexGuy** [ziglang/zig#6762]
With non-pointer types, whether an optional is null is stored separately from the payload.  So this code is perfectly fine:

```zig
fn main() void {
    var x: u32 = undefined;
    var y: ?u32 = x; // x is undefined but not null
    if (y != null) {
        // this is guaranteed to execute, no UB here.
        doSomething();
    }
}
```

Even though x is undefined, the type system knows that it is not null, and therefore that y is a nonnull value.  So branching on the nullity of y is not branching on undefined, and is therefore a well-defined operation that must be preserved through the optimizer.

But this gets a little fuzzy with optional pointers.  Is this code guaranteed to work in release-fast?
```zig
fn main() void {
    var x: *u32 = undefined;
    var y: ?*u32 = x; // x is undefined but not null, though in release-fast the underlying bits may be all zeroes
    if (y != null) {
        // Is this guaranteed to execute?
        doSomething();
    }
}
```

If this doesn't work, it means that the semantics of optional pointers are distinct from the semantics of other optionals, which could be a footgun for generic code.  But if this is guaranteed, it means that the compiler must generate extra instructions to write a nonzero value to non-nullable undefined pointers.  The current state is that this is unchecked undefined behavior.  The compiler can (and sometimes does) fail to execute the branch in release fast mode.

In this case of course, the compiler could analyze this flow and determine the right answer.  But it's important to realize that the compiler doesn't always know if a value might be undefined.  Take this code, for example:
```zig
// compilation unit 1
export fn foo() *u32 { return undefined; }

// compilation unit 2
extern fn foo() *u32;
fn main() void {
    var y: ?*u32 = foo();
}
```

For this, the compiler would have to do one of two things:
- give `undefined` a concrete nonzero value for pointer types, or
- check when assigning a nonnullable pointer to a nullable pointer that the underlying bytes are nonzero.

But there's another related problem: What happens if you use memset to set the bytes backing a nonnull pointer to zero?  There are a few options:
1. The act of setting all of these bytes to zero triggers UB
2. The act of reading the variable is UB if the bytes are zero
3. If the bytes are in an invalid state, the value is considered to be `undefined`

Option 1 seems obviously bad.  This would mean that memory has inherent types based on what values might alias it, which is scary.

Option 2 might be acceptable, but seems like it might be overly broad.  Copying the value from one variable to another of the same type could cause UB, even if neither value will ever be inspected.  This is distinct from `undefined`, which only causes UB if its value is used to trigger a conditional expression or index an array.

Option 3 was my first instinct for how to handle invalid byte patterns, but it causes a problem here.  This would mean that assigning to an optional requires a check to see if the underlying bytes are invalid.  Using a defined value for the literal `undefined` is not enough.

I'm not really sure what to do about this, but it definitely needs a solution.  Requiring runtime checks or extra writes in release-fast mode seems bad, but inconsistency in the meaning of `?` depending on whether the payload is a non-empty pointer type also seems problematic.  We could alternatively say that `@as(?T, @as(T, undefined))` always produces `undefined`, unless `T` is a zero-sized type, but this seems like a big footgun in the other direction.

**Comment by Rocknest** [comment]
Im not sure about status quo, but i would expect the compiler to elide a null check since the type system guarantees that a not nullable type `*u32` assigned to `y`.
```zig
// compilation unit 1
export fn foo() *u32 { return undefined; }

// compilation unit 2
extern fn foo() *u32;
fn main() void {
    var y: ?*u32 = foo();
    if (y != null) {
        doSomething();
    }
}
```

**Comment by SpexGuy** [comment]
You're right, my example was incomplete.  Here's one where the compiler must not have knowledge:
```zig
// compilation unit 1
export fn fooInternal() *u32 { return undefined; }

// compilation unit 2
extern fn fooInternal() *u32;
export fn foo() ?*u32 { return fooInternal(); }

// compilation unit 3
extern fn foo() ?*u32;
pub fn main() void {
    if (foo() != null) {
        doSomething();
    }
}
```

My point is just that the compiler doesn't always have the information to get rid of the check.

**Comment by rohlem** [comment]
Duplicate of #3325 .
This general problem also affects other types that don't cleanly fit into registers/bytes (like enums); I thought-dumped my take on the issue in #3328 .

I think the Zig language technically doesn't (need to) have the concept of compilation units besides (currently C-only) ABI boundaries, so we would "only" need to worry about those scenarios. Either way, current analysis does not exhaustively track undefined values yet, so if nothing else this is temporary issue of the current implementation status.

**Comment by SpexGuy** [comment]
I don't think this is a duplicate of #3325 but it is definitely a duplicate of #3328.  They are related in that one solution (fixing up values) would solve both problems, but I'm not convinced that that's the correct solution.  I'll move discussion over to #3328 though.
