### ISSUE TITLE
Invalid code generation with inline for, comptime and error inferring

### ISSUE THREAD

**Issue by destroycomputers** [ziglang/zig#6769]
I have encountered an invalid code generation with the combination of `inline for`, partial `comptime` evaluation and error inference. I'm not sure if all of these are necessary to reproduce the bug, but that's what minimal reproducing example, that i've managed to get, includes.

The example:
```zig
const std = @import("std");

var runtimeValue: bool = false;

fn gen(comptime v: usize) !void {
    std.log.default.info("Calling with {}", .{v});

    if (v == 1) return;
    if (runtimeValue) return error.OhNoes;
}

pub fn main() !void {
    inline for ([_]usize{ 1, 2 }) |val| {
        if (!runtimeValue) try gen(val);
    }
}
```

When compiled and ran, programme will stuck in an infinite loop printing "Calling with 1", "Calling with 2" until interrupted.
I've tried to factor out some bits and found that, for instance, changing the order of values in the array (from {1, 2} to {2, 1}) will eliminate the error, as well as using defined error set (even `anyerror`) for `gen` instead of an inferred one, or replacing the call `try gen(val)` with `gen(val) catch unreachable`, or getting rid of `runtimeValue` in `gen`.

Replacing `inline for` with `inline while` doesn't change the behaviour, although manually "unrolling" the loop in a series of calls that the expansion of `inline for` is supposed to generate does fix the issue.

Locally i've tested on `master` but godbolt shows the same code generation issue for both `trunk` and `0.6`: https://godbolt.org/z/M5dGWM

**Comment by Vexu** [comment]
Fixed by 4618c41fa6ca70f06c7e65762d2f38d57b00818c
