### ISSUE TITLE
Bug: "unable to evaluate constant expression" when depending on symbol address

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#6789]
Consider the following Zig code:

```zig
var stack: [256]u32 = undefined;

export const interrupt_table = [_][*]u32{
    @ptrCast([*]u32, &stack) + stack.len,
};
```

which will yield this error:
```
<source>:4:30: error: unable to evaluate constant expression
    @ptrCast([*]u32, &stack) + stack.len,
                             ^
<source>:3:41: note: referenced here
export const interrupt_table = [_][*]u32{
                                        ^
```

Such code is required when bootstrapping microcontrolls like the Cortex M3, as it requires the initial stack pointer to be stored in the interrupt vector table.

The C equivalent works:
```c
uint32_t stack[256];

const uint32_t * interrupt_table[1] = {
    stack + 256,
};
```

Example in godbolt: https://c.godbolt.org/z/zhxcMM

One workaround i tried was declaring the end of stack as a separate symbol:
```zig
extern var stack: [256]u32;

export const interrupt_table = [_][*]u32{
    &stack,
};
```
but this yields this error:
```
<source>:4:5: error: unable to evaluate constant expression
    &stack,
    ^
<source>:3:41: note: referenced here
export const interrupt_table = [_][*]u32{
                                        ^
```

This code is required to work, otherwise it is not possible to bootstrap such microcontrollers in Zig.

**Comment by dbandstra** [comment]
I wasn't aware that Zig allows pointer math? Don't you have to use `ptrToInt`?

**Comment by LiterallyVoid** [comment]
Pointer math is allowed on unknown-length pointers (`[*]T`).

**Comment by dbandstra** [comment]
Cool didn't know that. I guess that and intToPtr/ptrToInt are not currently allowed in a global expression.

The only workaround I got to work was making the stack 257 values long:

```zig
var stack: [257]u32 = undefined;

export const interrupt_table = [_][*]u32{
    @ptrCast([*]u32, &stack[256]),
};
```

**Comment by vegecode** [comment]
Here's how I worked around it.

https://github.com/vegecode/BurnedHead/blob/d393f348b8c5f6282128cea2af9c81c6e5fa296e/firmware/startup.zig#L17-L28

**Comment by MasterQ32** [comment]
@vegecode yeah, using linker script magic is a option here. for now, i just keep that part in C, doesn't really hurt. Can i somehow contact you on irc/discord/mail? I'd like to create some good embedded ARM base and it looks like you also did some work already :)

**Comment by vegecode** [comment]
@MasterQ32, Sure you can contact me. I'm on reddit with the same username, I think discord too. I got burned out juggling family stuff, work, and side projects so I haven't done much in a while. I'd love to be re-inspired though! I can PM you my email on there which is probably the easiest way to get a response from me.

**Comment by locriacyber** [comment]
Does "address of symbol" even make sense with weak linkage?

For example, the address is not defined at compile time (of the object file), but will be defined when linked with other objects later.

**Comment by locriacyber** [comment]
It is a concern for relocatable linkable objects too.

**Comment by SpexGuy** [comment]
Regardless, it does still make sense.  Comptime known addresses are symbolic values that will be resolved after comptime.  They can be passed around and you can use `@ptrToInt` and `@intToPtr` on them, but attempting to inspect their actual value at comptime is a compile error.  A more detailed description of how these symbols behave is in #9646.

**Comment by xdBronch** [comment]
this is marked stage1 and seems to compile now, can it be closed since stage2 is default?
