### ISSUE TITLE
Bug: Importing an empty file yields "unable to find" 

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#6790]
When importing an empty file with `@import`, it yields the following error:
```
./test.zig:2:9: error: unable to find 'empty.zig'
    _ = @import("empty.zig");
        ^
```

Reproduction:
Create a file `empty.zig` with no contents, create a file `test.zig`:
```zig
test "" {
    _ = @import("empty.zig");
}
```

Now test the code, it will emit the error shown above.

**Comment by andrewrk** [comment]
Found and fixed by @frmdstryr (with some minor fixups by me) in e2caf5752791cb81cd1110617d646e87f360e11b
