### ISSUE TITLE
`zig init-lib` doesn't accept `-h` flag

### ISSUE THREAD

**Issue by slimsag** [ziglang/zig#6798]
```
$ zig init-lib -h
error: unrecognized parameter: '-h'
```

It would be nice if this was an alias for `--help`

**Comment by GeertVL** [comment]
Can I work on this issue? Ideal to start contributing!

**Comment by xackus** [comment]
@GeertVL Go ahead, usually people take small/simple issues without asking.

**Comment by GuoxinYin** [comment]
Hello @xackus @slimsag , if the feature is still not added, I have created a pull request #7032 for this issue. Please help review that, thank you!

**Comment by alexnask** [comment]
Closed in 21a77f7ac35cc3404a1ed3cb03329aef1c980f30
