### ISSUE TITLE
comptime ignored?

### ISSUE THREAD

**Issue by qgcarver** [ziglang/zig#6802]
[gist](https://gist.github.com/qgcarver/2f6a54506e4f8b2d22bcbdef55b609e1)
```zig
const std = @import("std");

const names_and_vals = [_]struct{name: []const u8, value: u32}{
  .{.name = "first"   , .value = 0x1},
  .{.name = "second"  , .value = 0x2},
  .{.name = "third"   , .value = 0x3},
  };

fn name_to_val(comptime name: []const u8) u32 {
  comptime {
    var return_val: u32 = undefined;
    for(names_and_vals) |tuple, idx| {
      if(std.mem.eql(u8, tuple.name, name)) {
        return_val = tuple.value;
        return return_val;
      }
    } else unreachable;
  }
}

pub fn main() void {
  const val = 0x3;
  std.debug.print("\n -> ", .{});
  switch (val) {
    name_to_val("first") => {
      std.debug.print("first\n", .{});
      return;
    },
    name_to_val("second")  => {
      std.debug.print("second\n", .{});
      return;
    },
    name_to_val("third") => std.debug.print("third\n", .{}),
    else => {
      std.debug.print("last\n", .{});
      return;
    }
  }
  _ = name_to_val("invalid"); //invalid, but only hits 'unreachable' at runtime
  return;
}
```

If `zig build` is ran on this code, there are no compile time errors and `unreachable` is reached at runtime.

I asked around on the discord and IRC for explanations for this code, myself and those I've asked are confused that we don't get an error when presumably hitting unreachable at comptime (checking every call for invalid inputs) But I'm not certain enough about the semantics of comptime to know whether or not this is an bug.

**Comment by qgcarver** [comment]
(regarding suggestions on the code here in terms of style/utility, I have already switched to using enums and `@intToEnum` for my use case, I was just messing around before happening upon this example.)

**Comment by dbandstra** [comment]
Looks like a compiler bug to me, in 0.6.0 too. It fails properly at comptime if you change `unreachable` to `std.debug.assert(false)` (which uses unreachable itself).

**Comment by LemonBoy** [comment]
Have you tried replacing the inner `for` loop with an `inline for`?

**Comment by qgcarver** [comment]
@LemonBoy no effect
