### ISSUE TITLE
__zig_probe_stack undefined in static libraries

### ISSUE THREAD

**Issue by jedisct1** [ziglang/zig#6817]
When building static libraries, the `__zig_probe_stack` symbol is undefined:

```text
Undefined symbols for architecture x86_64:
  "___zig_probe_stack", referenced from:
      _std.debug.printLineInfo in x.o)
      _std.sort.sort in x.o)
ld: symbol(s) not found for architecture x86_64
```

Passing `-fno-stack-check` fixes this (thanks @FireFox317 !), but maybe stack checking should be disabled automatically when building static libraries. Or maybe we want to link `compile_rt`?

What would be the best way to improve this?

**Comment by LemonBoy** [comment]
> maybe stack checking should be disabled automatically when building static libraries

That's not a good idea, isn't it? Silently turning off safety measures is not nice.
Two possible solutions are to always link in `compiler-rt` or build the stack probe function as a separate object that's unconditionally linked in.
The former is easier to implement but it will increase the size of the generated libraries for no good reason: when a Zig static library is linked against some other Zig code we still use our `compile_rt` implementation, whenever you link the library with some C object we still have `libgcc` or LLVM's `compiler_rt` to fall-back on. On the other hand relying on a third-party library provided by the C compiler means we may end up with missing symbols or with a copy afected by bugs we can't fix (it hasn't happened so far as our implementations were the buggy ones but it's definitely something to take into account).

**Comment by andrewrk** [comment]
> we may end up with missing symbols or with a copy afected by bugs we can't fix (it hasn't happened so far as our implementations were the buggy ones but it's definitely something to take into account).

It has happened - here are a couple examples: e3ea0b652c7bec25d7303d98e08cdfe1d288a9ec 91536813ec5d159ed4bea857621ed10a1216411a

**Comment by andrewrk** [comment]
Now you can pass `-fcompiler-rt` to include compiler-rt in static libraries. Feel free to open a proposal to change the default, which is currently only dynamic libraries and executables get compiler-rt included.

After  #7264 you would be able to also do this to get a compiler_rt object (or library): `zig build-obj -fcompiler-rt` / `zig build-lib -fcompiler-rt`.
