### ISSUE TITLE
remove the type parameter from builtins that support vectors

### ISSUE THREAD

**Issue by data-man** [ziglang/zig#6835]
As described in LLVM's docs:
> This is an overloaded intrinsic. You can use llvm.* on any integer bit width, or on any vector with integer elements.

`@bitReverse(comptime T: type, integer: T) T` uses [llvm-bitreverse-intrinsics](https://llvm.org/docs/LangRef.html#llvm-bitreverse-intrinsics)
`@clz(comptime T: type, integer: T)` uses [llvm-ctlz-intrinsic](https://llvm.org/docs/LangRef.html#llvm-ctlz-intrinsic)
`@ctz(comptime T: type, integer: T)` uses [llvm-cttz-intrinsic](https://llvm.org/docs/LangRef.html#llvm-cttz-intrinsic)
`@popCount(comptime T: type, integer: T)` uses [llvm-ctpop-intrinsic](https://llvm.org/docs/LangRef.html#llvm-ctpop-intrinsic)

**Proposal**: remove first parameter (like `@cos`, `@sin`, etc. builtins):

`@bitReverse(value: anytype) @TypeOf(value)`
`@clz(value: anytype) T`
`@ctz(value: anytype) T`
`@popCount(value: anytype) T`

Where `T` is `comptime_int` if `value` is known at comptime. Otherwise, `T` is `usize`.

Related #903 as always.

**Comment by jedisct1** [comment]
Yup, that would be neat.

**Comment by LemonBoy** [comment]
The proposal here is to revert #2240, check out #2119 for the rationale.

**Comment by data-man** [comment]
> The proposal here is to revert #2240

Yes, partially.
The main wish is to support vectors.

**Comment by LemonBoy** [comment]
> The main wish is to support vectors.

As they're defined right now it'd be a problem to extend them to vectors.
The documentation states about `@ctz`:
> If integer is known at comptime, the return type is comptime_int. Otherwise, the return type is an unsigned integer with the minimum number of bits that can represent the bit count of the integer type. 

If this logic is extended to vectors `@ctx(v4i32)` gives you a `v4i5` that's essentially useless (LLVM will happily produce scalar code for you but you lose every kind of parallelism) until you intCast it back to a wider type that the CPU supports.

**Comment by data-man** [comment]
The same proposal for `@addWithOverflow` and `@subWithOverflow`.

**Comment by andrewrk** [comment]
> The same proposal for `@addWithOverflow`, `@subWithOverflow`, `@mulWithOverflow` and `@shlWithOverflow`.

These are covered by` #10248.
