### ISSUE TITLE
Building for cortex-m33 cpu emits LLD warning and produces corrupt elf

### ISSUE THREAD

**Issue by frmdstryr** [ziglang/zig#6844]
Sorry for the weird title... I'm not sure how to describe the issue.

I'm playing with an [stm32l5](https://www.st.com/en/microcontrollers-microprocessors/stm32l5-series.html) board and when building with zig a few LLD warnings are printed:

```
stm32l5$ zig build
warning: unexpected LLD stderr: lld: warning: /home/user/Workspace/omitted/targets/stm32l5/zig-cache/o/aacd2ccecfdd73d77164281374a46cac/firmware.elf.o:(.ARM.attributes): unknown THUMB_ISA_use value: 3
lld: warning: /home/user/.cache/zig/o/8f2b0990fe3d2b7dbafb969f9555d996/libc.a(/home/user/.cache/zig/o/8f2b0990fe3d2b7dbafb969f9555d996/c.o):(.ARM.attributes): unknown THUMB_ISA_use value: 3
lld: warning: /home/user/.cache/zig/o/317791dd188b4fa57ae86ccb1db85f0c/libcompiler_rt.a(/home/user/.cache/zig/o/317791dd188b4fa57ae86ccb1db85f0c/compiler_rt.o):(.ARM.attributes): unknown THUMB_ISA_use value: 3
lld: warning: lld uses blx instruction, no object with architecture supporting feature detected
```

The build file is using

```zig
    const elf = b.addExecutable("firmware.elf", "startup.zig");
    elf.setTarget(CrossTarget.parse(.{
        .arch_os_abi="thumb-freestanding-none",
        .cpu_features="cortex_m33",
    }) catch unreachable);
```

The resulting elf also seems to be corrupt:

```
$ readelf -A firmware.elf
Attribute Section: aeabi
File Attributes
  Tag_conformance: "2.09"
  Tag_CPU_name: "cortex-m33"
  Tag_CPU_arch: v8-M.mainline
  Tag_CPU_arch_profile: Microcontroller
  Tag_ARM_ISA_use: No
  Tag_THUMB_ISA_use: Yes
  Tag_FP_arch: FPv5/FP-D16 for ARMv8
  Tag_ABI_PCS_R9_use: V6
  Tag_ABI_PCS_GOT_use: direct
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Unused
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_HardFP_use: SP only
  Tag_CPU_unaligned_access: v6
  Tag_FP_HP_extension: Allowed
  Tag_ABI_FP_16bit_format: IEEE 754
  Tag_DSP_extension: Allowed
readelf: Error: Bad attribute length (17217 > 136)
Attribute Section: 
readelf: Error: Bad subsection length (1768055141 > 131)
Unknown tag: 97
  Unknown attribute:
  0x00000000 00013900 00004332 2e303900 05636f72 ..9...C2.09..cor
  0x00000010 7465782d 6d333300 0611074d 08000903 tex-m33....M....
  0x00000020 0a080e00 11011401 15001703 18011901 ................
  0x00000030 1b012201 24012601 2e014143 00000061 ..".$.&...AC...a
  0x00000040 65616269 00013900 00004332 2e303900 eabi..9...C2.09.
  0x00000050 05636f72 7465782d 6d333300 0611074d .cortex-m33....M
  0x00000060 08000903 0a080e00 11011401 15001703 ................
  0x00000070 18011901 1b012201 24012601 2e01     ......".$.&...

```

The same code base builds fine on an cortex-m4 board and cortex-h7 board also the warning was not present a few months ago (Aug 12th). 

Edit: ~~The firmware actually runs sometimes but completely jacks up the debugger / gdb server other times.~~ It appears to work fine, the debugger comm error was me forgetting to define an IRQ handler...

**Comment by frmdstryr** [comment]
Same blx warning as in https://github.com/ziglang/zig/issues/6572

**Comment by LemonBoy** [comment]
The `THUMB_ISA_use` was bumped from 2 to 3 for ARMv8-M targets but it seems nobody updated the parser, hence the lld warnings. I'll send them a patch later.

> The resulting elf also seems to be corrupt:

Upload the file/source somewhere and I'll have a look.

> lld: warning: lld uses blx instruction, no object with architecture supporting feature detected

LLD loves to use `BLX` to jump between arm/thumb modes and warns you if _none_ of the objects you're linking is targeting a ARM revision that supports it.
Now this is extra weird as the final elf file has `Tag_CPU_arch: v8-M.mainline` and that should be enough...
Try building with `--verbose-link` and then run `readelf -A <..>` on all the objects.

**Comment by frmdstryr** [comment]
https://codelv.com/assets/uploads/firmware.elf

Using --verbose-link just spits out a command and an additional firmware.elf.o, readelf reads that fine without any errors (the tags are the same as above). 

```
lld -error-limit=0 -z stack-size=16777216 -T /home/user/Workspace/omitted/targets/stm32l5/stm32l552xx.ld --gc-sections -m armelf_linux_eabi -Bstatic -o /home/user/Workspace/omitted/targets/stm32l5/zig-cache/o/aacd2ccecfdd73d77164281374a46cac/firmware.elf /home/user/Workspace/omitted/targets/stm32l5/zig-cache/o/aacd2ccecfdd73d77164281374a46cac/firmware.elf.o /home/user/.cache/zig/o/8f2b0990fe3d2b7dbafb969f9555d996/libc.a /home/user/.cache/zig/o/317791dd188b4fa57ae86ccb1db85f0c/libcompiler_rt.a --allow-shlib-undefined
```

If you disassemble it with objdump you can see blx being used a few times, according to the programming manual the `BLX rm` variant is supported which is what is being used so that shouldn't be a problem.

If it's trying to jump to arm mode (how do I check that?) then that's a problem because the cortex-m cores only support thumb instructions (according to wikipedia but I also remember seeing it somewhere in the ref manual).  I saw a few recent commits to llvm related to cortex-a bugs/workarounds with blx so maybe one of those is accidentally being applied?

**Comment by LemonBoy** [comment]
It turns out the problem was linked to the badly-parsed tag value, [this](https://reviews.llvm.org/D90305) patch fixes all your problems.

**Comment by frmdstryr** [comment]
Thank you! Closing this as it doesn't seem to be anything zig is doing.

**Comment by frmdstryr** [comment]
I should probably create a separate issue, but I also noticed a bunch of `std.target.` functions being included in the code. 

Shouldn't those get executed at comptime and be removed (one that really stuck out was `std.target.Arch.isWasm`)?

**Comment by LemonBoy** [comment]
> Shouldn't those get executed at comptime and be removed (one that really stuck out was std.target.Arch.isWasm)?

That's a long-standing issue, some functions should be restricted to `comptime` but escape into the generated binary.
Using `--gc-sections` gets rid of all the cruft.

**Comment by FireFox317** [comment]
@frmdstryr #4715

**Comment by frmdstryr** [comment]
One other thing I noticed when comparing the zig build to one built using the standard c toolchain/stm32 hal... 

With c the elf is tagged with  `Tag_ABI_FP_exceptions: Needed` while zig's always seem to have `Tag_ABI_FP_exceptions: Unused`, is that something with llvm or is something missing in the zig build?
