### ISSUE TITLE
`std.compress.zlib.zlibStream` returns `error.EndOfStream` for valid zlib data

### ISSUE THREAD

**Issue by leroycep** [ziglang/zig#6847]
Here is the data that, when used, creates the error. I also created a program that uncompresses the data with zlib first to be sure that it is the zig code that has the bug: https://gist.github.com/leroycep/20a31e515dbfa06a25160e5ace39b985 

```zig
const std = @import("std");

test "Deflate unexpected EOF replication" {
    const INPUT = "08d763f8cfc0c000c1ffff43300303c3ffffff0183950bf5";
    const EXPECTED = "00ff000000ff000000ff00ffffff00ffffff00000000ffffff";

    var input: [INPUT.len / 2]u8 = undefined;
    try std.fmt.hexToBytes(input[0..], INPUT[0..]);

    var expected: [EXPECTED.len / 2]u8 = undefined;
    try std.fmt.hexToBytes(expected[0..], EXPECTED[0..]);

    // uncompress using zig std
    var stream = std.io.fixedBufferStream(&input);
    var zlib_stream = try std.compress.zlib.zlibStream(std.testing.allocator, stream.reader());
    defer zlib_stream.deinit();

    var zlib_reader = zlib_stream.reader();
    
    // this is where error.EndOfStream comes from
    const buf = try zlib_stream.reader().readAllAlloc(std.testing.allocator, 1000000);
    defer std.testing.allocator.free(buf);

    std.testing.expectEqualSlices(u8, &expected, buf);
}
```

__Edit:__ Here is the stack trace that is produced: https://gist.github.com/leroycep/cf1a7a6a14aa8523437cf6d63df2faca

**Comment by leroycep** [comment]
The error seems to occur because the first byte of the CRC is consumed by `InflateStream`. If I duplicate the first byte of the CRC (the last `83` in `INPUT`) this code runs fine. I'll keep investigating and see if I can find out why.

**Comment by LemonBoy** [comment]
The optimized path in the Huffman decoder may read more bytes than it needs, I'll have a look soon.

**Comment by leroycep** [comment]
After some more investigation, I can confirm that it the extra byte is being consumed by the fast path.

```
[default] (warn): bits_left: 0
[default] (warn): pos of inner_reader before peek: 18
[default] (warn): pos of inner_reader before discard: 20
[default] (warn): pos of inner_reader fastpath: 20
[default] (warn): symbol: 255
[default] (warn): bits_left: 7
[default] (warn): pos of inner_reader before peek: 20
[default] (warn): pos of inner_reader before discard: 21
[default] (warn): pos of inner_reader fastpath: 21
[default] (warn): symbol: 256
[default] (warn): bits_left: 8
```

After the second to last symbol is read, there are 7 bits left in the InflateStream. Then it runs `decode` again, and peeks at `PREFIX_LUT_BITS` (that is 9 bits). Since there was only 7 bits known, it has to read the next byte. But once it's read that byte, it has no way to put it back.

I think there are two changes that need to be made:

1. InflateStream needs to check for an `EndOfStream` calls `peekBits`. If `EndOfStream` was returned, then continue with slower decoding method
2. InflateStream should communicate that it read an extra byte. The simple solution is making ZlibStream check InflateStream before calculating the CRC, but this doesn't seem like a very robust method. We might need to require a peekable stream for Inflate to fix this.

**Comment by LemonBoy** [comment]
> I think there are two changes that need to be made:

No, the decoder should be modified to read the codes incrementally. I already have a patch ready, give me some time to profile the performance impact.

**Comment by leroycep** [comment]
Ah, I hadn't realized that you could make it read incrementally. Guess that's what I get for staying up late to comment on an algorithm I don't know :stuck_out_tongue:
