### ISSUE TITLE
Stage1 bug: Compile error on `@typeInfo(* opaque{}).Pointer.alignment`

### ISSUE THREAD

**Issue by rohlem** [ziglang/zig#6855]
Reflecting on pointer alignment of naturally-aligned pointers-to-opaque types leads to an error. Minimal test case:
```zig
test "* opaque{} alignment"{
    @import("std").debug.warn("*opaque{{}} alignment: {}\n", .{figureOutAlignment(*opaque{})});
}
fn figureOutAlignment(comptime T: type) comptime_int {
    if(true){
        return @typeInfo(T).Pointer.alignment; //error: no align available for type 'opaque:2:84'
    }else{ //and here is a status-quo workaround:
        comptime var pointerInfo = @typeInfo(T).Pointer;
        pointerInfo.alignment = 1;
        const ByteAlignedPtr = @Type(@import("std").builtin.TypeInfo{.Pointer = pointerInfo});
        return if(ByteAlignedPtr == T) 1
            else pointerInfo.alignment;
    }
}
```
The error message is the same for `@alignOf(opaque{})`, where it makes sense.
For `*c_void`, the resulting alignment is `1`, which I think would be the most sensible answer here as well.
Alternatively we could make the `.alignment` property optional, but I can't think of a scenario where generic pointer code would be interested in differentiating between "unknown alignment" and "minimum alignment".

**Comment by manast** [comment]
I am trying to write a Redis module using Zig. After converting redismodule.h to zig with zig translate-c and importing it to my code I get the same error as reported in this bug:
```
/usr/local/Cellar/zig/0.9.1_2/lib/zig/std/meta.zig:121:37: error: no align available for type 'anyopaque'
        .Optional => |info| switch (@typeInfo(info.child)) {
                                    ^
./src/redismodule2.zig:874:104: note: called from here
    var getapifuncptr: ?*anyopaque = @ptrCast([*c]?*anyopaque, @alignCast(@import("std").meta.alignment(?*anyopaque), ctx))[@intCast(c_uint, @as(c_int, 0))];
                                                                                                       ^
./src/redismodule2.zig:869:130: note: called from here
pub fn RedisModule_Init(arg_ctx: ?*RedisModuleCtx, arg_name: [*c]const u8, arg_ver: c_int, arg_apiver: c_int) callconv(.C) c_int {
```
Does it mean it is not possible to use redismodule.h until this issue is resolved or are there any workarounds?

**Comment by KekOnTheWorld** [comment]
An anyopaque does not provide any type information (just like `void*` in C) and must be casted to a type which we can make sense of.

**Comment by manast** [comment]
@KekOnTheWorld so there is a bug in translate-c since it generates incorrect code, or?

**Comment by Vexu** [comment]
The self-hosted compiler allows this so no.
```zig
pub fn main() void {
    std.debug.print("align: {d}\n", .{std.meta.alignment(?*anyopaque)});
}
```
```sh-session
$ zig run a.zig
align: 1
```

**Comment by KekOnTheWorld** [comment]
I actually thought this was about a value of anyopaque and not the type itself.

**Comment by KekOnTheWorld** [comment]
> I am trying to write a Redis module using Zig. After converting redismodule.h to zig with zig translate-c and importing it to my code I get the same error as reported in this bug:
> 
> ```
> /usr/local/Cellar/zig/0.9.1_2/lib/zig/std/meta.zig:121:37: error: no align available for type 'anyopaque'
>         .Optional => |info| switch (@typeInfo(info.child)) {
>                                     ^
> ./src/redismodule2.zig:874:104: note: called from here
>     var getapifuncptr: ?*anyopaque = @ptrCast([*c]?*anyopaque, @alignCast(@import("std").meta.alignment(?*anyopaque), ctx))[@intCast(c_uint, @as(c_int, 0))];
>                                                                                                        ^
> ./src/redismodule2.zig:869:130: note: called from here
> pub fn RedisModule_Init(arg_ctx: ?*RedisModuleCtx, arg_name: [*c]const u8, arg_ver: c_int, arg_apiver: c_int) callconv(.C) c_int {
> ```
> 
> Does it mean it is not possible to use redismodule.h until this issue is resolved or are there any workarounds?

You might wanna try upgrading to the latest (nightly) release

**Comment by Vexu** [comment]
Works in master.
