### ISSUE TITLE
std.time.Timer overflows on Windows after 30 minutes

### ISSUE THREAD

**Issue by SpexGuy** [ziglang/zig#6867]
I'm not sure if timers are meant to go this long but 30 minutes seems like a short enough time span that it should be supported.  The overflow is in `nativeDurationToNanos`:
```zig
return @divFloor(duration * ns_per_s, self.frequency);
```
This multiplication will overflow when duration is >= `18_446_744_074`.
`self.frequency` is `10_000_000` on my system, so this takes 1845 seconds, or about 30 minutes.  Since the frequency is a perfect factor of `ns_per_s`, an ideal conversion wouldn't overflow until the time passed was actually too large to fit into a 64-bit number, which happens after about 584 years.

**Comment by nektro** [comment]
yeah I don't see why Timers should be limited to 30 minutes.

**Comment by LemonBoy** [comment]
The trick is to rewrite the calculation as `(a * b) / q == (a / q) * b + ((a % q) * b) / q` or use a `u128`, don't know what's faster.
