### ISSUE TITLE
Cannot find standard library when moved relative to binary hangs `zig build`

### ISSUE THREAD

**Issue by g-w1** [ziglang/zig#6872]
I initially reported this on irc. When moving the binary relative to the standard library, it cannot find the stdlib and zig build breaks. https://freenode.irclog.whitequark.org/zig/2020-10-30#28253879; ![](https://i.imgur.com/sOMWJIW.png)

**Comment by LemonBoy** [comment]
It's #6584 or some variant of the same problem, there's a PR open to fix this.
