### ISSUE TITLE
{s} format specifier does not use null-termination for slices

### ISSUE THREAD

**Issue by jcmoyer** [ziglang/zig#6874]
Example:

```zig
const buf = std.mem.zeroes([8]u8);
std.io.getStdOut().writer().print("|{s}|", .{buf});

// Windows prints: |        |
//   Linux prints: ||
```

The doc comments for `format` say:

`/// - s: print a pointer-to-many as a c-string, use zero-termination`

I took this to mean that the first null byte in the array should terminate the string, so in my opinion, Linux is correct here.

This came up while interfacing with a C library that writes an error message into a caller-provided buffer. I would like to print the message before exiting, but this ends up inserting a bunch of extra lines in my terminal because the buffer is quite large.

**Comment by LemonBoy** [comment]
> Linux prints: ||

Are you sure? `zig run /tmp/foo.zig |& xxd -` prints `7c00 0000 0000 0000 007c` as expected :)

The fmt code takes the array size from the type, the c-string behaviour is obtained by passing a `[*:0]u8` or by slicing the array using `mem.spanZ`.

**Comment by jcmoyer** [comment]
Thank you for the explanation, I hadn't considered that possibility. I still find the behavior surprising though, should it print anything?

**Comment by LemonBoy** [comment]
> I still find the behavior surprising though, should it print anything?

According to the documentation it shouldn't print anything, yes.
The `fmt` API/specification is still in flux but there's a mismatch between the docs and the implementation.

**Comment by jcmoyer** [comment]
So I did some digging and it looks like `{s}` is actually totally ignored in this case since the parameter is treated as a slice instead of a pointer. I'd be more than happy to submit a PR to fix either the documentation or the logic depending on what the intended behavior should be.
