### ISSUE TITLE
Stage1 bug: `@Type` reifies untagged unions with enum tag type

### ISSUE THREAD

**Issue by rohlem** [ziglang/zig#6885]
Test case:
```zig
test "@Type untagged union" {
    const untagged_info = @typeInfo(union {a: u8, b: u16});
    const reified_info = @typeInfo(@Type(untagged_info));
    @import("std").testing.expectEqual(reified_info.Union.tag_type, untagged_info.Union.tag_type);
}
```
Output: `expected type, found null`.

~~The output is a bit strange to read: Because unions can be tagged or untagged, `std.builtin.TypeInfo.Union.tag_type` is a `?type`.
However, when reifying an untagged union (`.tag_type = null`) via `@Type`, the resulting type's `@typeInfo` gets `.tag_type = type`. So it pretends to have the type `type` as tag type.~~

~~Using the reified union did not cause issues for me, it seems to just be a bug to the `@typeInfo` associated with it.
For now a workaround is to explicitly check for `.tag_type == type` and treat it the same as `null`, since this scenario is invalid per language design.~~

EDIT: Reifying an untagged union (`.tag_type = null`) gives you a tagged union, with newly-constructed enum as tag type.
I'm still looking for a workaround. The name is of the form `union:line:column`, like with the tag type of `union(enum)`, so there's no easy way to differentiate them.

**Comment by mikdusan** [comment]
with latest compiler:
- compiler no longer errors
- appears this was fixed between 0.9.1 and 0.10.0

<details>
<summary>repro.zig</summary>

```zig
test "@Type untagged union" {
    const untagged_info = @typeInfo(union {a: u8, b: u16});
    const reified_info = @typeInfo(@Type(untagged_info));
    try @import("std").testing.expectEqual(reified_info.Union.tag_type, untagged_info.Union.tag_type);
}
```
</details>

```sh
$ uname -a
Linux archlinux 6.1.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 31 Dec 2022 17:40:35 +0000 x86_64 GNU/Linux

$ zig version
0.11.0-dev.1247+87b223428

$ zig test repro.zig |& cat
1/1 test.@Type untagged union... OK
All 1 tests passed.
```
