### ISSUE TITLE
Using defer with if

### ISSUE THREAD

**Issue by Prince213** [ziglang/zig#6892]
I'm trying to write a cross-platform socket app when I met this:
```zig
const std = @import("std");
pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    if (std.builtin.os.tag == .windows) { // Or another expression that can be evaluated at compile time
        defer stdout.print("defer\n", .{}) catch unreachable;
    }
    try stdout.print("last\n", .{});
}
```
I want to do platform-specific cleanup when returning from the main function.
Expected output:
```
last
defer
```
Actual output:
```
defer
last
```
AFAIK if can be used to do conditional compilation. In C, I can use #ifdef and it works. What should I use in Zig?

**Comment by alexnask** [comment]
You can move the if statement in the defer :)

**Comment by Prince213** [comment]
Yeah, it works, though doesn't look nice.
Is there a way to avoid creating a new scope?

**Comment by alexnask** [comment]
I don't think so, the defer will always happen at the ned of the current scope so the if statement has to go inside the defer for sure in this case, unless I'm missing some trick.

**Comment by Prince213** [comment]
Anyway it works in this case. Thanks.
