### ISSUE TITLE
Disallow extern enum(type)

### ISSUE THREAD

**Issue by tadeokondrak** [ziglang/zig#6899]
This, as far as I know, is just treated like the type in the parentheses.
https://github.com/ziglang/zig/pull/6427 allowed normal enums doing this, and so I think this syntax is redundant.

**Comment by Vexu** [comment]
It's not redundant at the moment since we might need the enum to have members with values that don't fit in a `c_int` and we don't currently select  the type based on the tag values like C does.

**Comment by andrewrk** [comment]
Instead, we're getting rid of extern enums altogether: https://github.com/ziglang/zig/issues/2115#issuecomment-827968279
