### ISSUE TITLE
Proposal: add --git flag to init-lib and init-exe

### ISSUE THREAD

**Issue by g-w1** [ziglang/zig#6912]
If the ``--git`` flag was passed to init-lib or init-exe, then a git repo would be initialized in the current directory, and a `.gitignore` would be added. I think cargo does this by default, but I feel that it should be an explicit option in zig.

Maybe we could also add different flags for different vcs.

**Comment by tauoverpi** [comment]
What of just searching for `.git`, `.pijul`, and so on instead and updating the ignore files from there? Though as long as everything that's not source is kept in zig-cache it should suffice to just print a note on init which skips needing to keep track of the many version control systems.

**Comment by jedisct1** [comment]
There's not much to ignore besides `zig-cache` to be honest.

And `zig-cache` can be ignored globally.

**Comment by g-w1** [comment]
> Though as long as everything that's not source is kept in zig-cache it should suffice to just print a note on init which skips needing to keep track of the many version control systems.
What do you mean by print note?

**Comment by andrewrk** [comment]
I'm making a judgement call here: no opinionated integration with any particular source control software in the zig CLI. Even for the package manager, downloading from a git URL will be a "plugin".
