### ISSUE TITLE
Strange behavior when calling async functions inside structs from outside the structs

### ISSUE THREAD

**Issue by wooky** [ziglang/zig#6917]
Consider this code:
```zig
const std = @import("std");

const Breaking = struct {
    frame: anyframe = undefined,

    fn entry(self: *Breaking) void {
        _ = async self.suspending();
    }

    fn suspending(self: *Breaking) void {
        std.debug.warn("Before suspend\n", .{});
        suspend {
            self.frame = @frame();
        }
        std.debug.warn("After suspend\n", .{});
    }

    fn resuming(self: *Breaking) void {
        resume self.frame;
    }
};

pub fn main() void {
    var breaking = Breaking {};
    breaking.entry();    // (1)
    breaking.resuming(); // (2)
}
```
I'm expecting it to print "Before suspend" and "After suspend", instead it crashes with:
<details><summary>Stack trace</summary>
<pre>
yakov@YAKOV-DESKTOP:/mnt/c/Users/Yakov/Documents/aoc$ ./uwt
Before suspend
resumed an async function which already returned
/mnt/c/Users/Yakov/Documents/aoc/src/main/zig/uwt.zig:10:5: 0x2304d5 in Breaking.suspending (uwt)
    fn suspending(self: *Breaking) void {
    ^
/mnt/c/Users/Yakov/Documents/aoc/src/main/zig/uwt.zig:19:9: 0x22eafe in Breaking.resuming (uwt)
        resume self.frame;
        ^
/mnt/c/Users/Yakov/Documents/aoc/src/main/zig/uwt.zig:27:22: 0x22a92a in main (uwt)
    breaking.resuming();
                     ^
/usr/lib/zig/0.6.0/lib/zig/std/start.zig:243:22: 0x2047af in std.start.posixCallMainAndExit (uwt)
            root.main();
                     ^
/usr/lib/zig/0.6.0/lib/zig/std/start.zig:123:5: 0x20458f in std.start._start (uwt)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
Aborted
</pre></details>
If I replace line (2) with `resume breaking.frame`, for some reason the function resumes, but at the end I get a segfault:
<details><summary>Stack trace</summary>
<pre>
yakov@YAKOV-DESKTOP:/mnt/c/Users/Yakov/Documents/aoc$ ./uwt
Before suspend
After suspend
Segmentation fault at address 0xffffffffffffffff
/mnt/c/Users/Yakov/Documents/aoc/src/main/zig/uwt.zig:10:41: 0x233be8 in Breaking.suspending (uwt)
    fn suspending(self: *Breaking) void {
                                        ^
/mnt/c/Users/Yakov/Documents/aoc/src/main/zig/uwt.zig:28:5: 0x22b051 in main (uwt)
    resume breaking.frame;
    ^
/home/yakov/zig-linux-x86_64-0.6.0+9ca981948/lib/zig/std/start.zig:316:22: 0x204d6f in std.start.posixCallMainAndExit (uwt)
            root.main();
                     ^
/home/yakov/zig-linux-x86_64-0.6.0+9ca981948/lib/zig/std/start.zig:154:5: 0x204b42 in std.start._start (uwt)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
Aborted
</pre></details>

If I replace line (1) with `_ = async breaking.suspending()`, it doesn't matter what I put for line (2), it works as expected.

**Comment by frmdstryr** [comment]
The frame returned by `async self.suspending()` is destroyed/becomes invalid when the entry fn returns since it is stored in that functions stack. 

The original frame needs to be saved somewhere for it to work.

**Comment by SpexGuy** [comment]
Closing since this behavior is expected.
