### ISSUE TITLE
'zig cc' and 'clang' behavior differ on Mac OS 10.15.7

### ISSUE THREAD

**Issue by slimsag** [ziglang/zig#6923]
The C code below compiles with `clang` via:

```
clang test.c -framework Cocoa -framework Foundation -o test.app
```

However, with `zig cc`:

```
zig cc test.c -framework Cocoa -framework Foundation -o test.app
test.c:6:10: fatal error: 'Carbon/Carbon.h' file not found
#include <Carbon/Carbon.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
```

Is this a bug in Zig, or a misunderstanding I have about how `clang` on Mac OS handles includes?

```c
#include <objc/runtime.h>
#include <objc/message.h>

#include <Carbon/Carbon.h>

#define cls objc_getClass
#define sel sel_getUid
#define msg ((id (*)(id, SEL, ...))objc_msgSend)
#define cls_msg ((id (*)(Class, SEL, ...))objc_msgSend)

// poor man's bindings!
typedef enum NSApplicationActivationPolicy {
    NSApplicationActivationPolicyRegular   = 0,
    NSApplicationActivationPolicyAccessory = 1,
    NSApplicationActivationPolicyERROR     = 2,
} NSApplicationActivationPolicy;

typedef enum NSWindowStyleMask {
    NSWindowStyleMaskBorderless     = 0,
    NSWindowStyleMaskTitled         = 1 << 0,
    NSWindowStyleMaskClosable       = 1 << 1,
    NSWindowStyleMaskMiniaturizable = 1 << 2,
    NSWindowStyleMaskResizable      = 1 << 3,
} NSWindowStyleMask;

typedef enum NSBackingStoreType {
    NSBackingStoreBuffered = 2,
} NSBackingStoreType;

int main(int argc, char *argv[])
{
    // id app = [NSApplication sharedApplication];
    id app = cls_msg(cls("NSApplication"), sel("sharedApplication"));

    // [app setActivationPolicy:NSApplicationActivationPolicyRegular];
    msg(app, sel("setActivationPolicy:"), NSApplicationActivationPolicyRegular);

    struct CGRect frameRect = {0, 0, 600, 500};

    // id window = [[NSWindow alloc] initWithContentRect:frameRect styleMask:NSWindowStyleMaskTitled|NSWindowStyleMaskClosable|NSWindowStyleMaskResizable backing:NSBackingStoreBuffered defer:NO];
    id window = msg(cls_msg(cls("NSWindow"), sel("alloc")),
                    sel("initWithContentRect:styleMask:backing:defer:"),
                    frameRect,
                    NSWindowStyleMaskTitled|NSWindowStyleMaskClosable|NSWindowStyleMaskResizable,
                    NSBackingStoreBuffered,
                    false);
    msg(window, sel("setTitle:"), cls_msg(cls("NSString"), sel("stringWithUTF8String:"), "Pure C App"));

    // [window makeKeyAndOrderFront:nil];
    msg(window, sel("makeKeyAndOrderFront:"), nil);

    // [app activateIgnoringOtherApps:YES];
    msg(app, sel("activateIgnoringOtherApps:"), true);

    msg(app, sel("run"));
}
```

**Comment by andrewrk** [comment]
> Is this a bug in Zig, or a misunderstanding I have about how `clang` on Mac OS handles includes?

It's a bug (or rather a missing enhancement) for zig to detect the native framework directories on macOS.

If anyone wants to contribute, here is one area of relevant code to get you started: https://github.com/ziglang/zig/blob/af60931a488ac84030900d14c2ae7d17e0c84891/lib/std/zig/system.zig#L26

**Comment by Jarek1542** [comment]
I'm currently in an undergraduate course that requires us to contribute to an open-source software project. Is it ok if I try to tackle this issue?

**Comment by Jarek1542** [comment]
Is it ok if I try to tackle this issue? I'm currently in an undergraduate course with a project to contribute to an open-source software and I think this would be a fun project to try and get started in!

**Comment by ifreund** [comment]
> Is it ok if I try to tackle this issue? I'm currently in an undergraduate course with a project to contribute to an open-source software and I think this would be a fun project to try and get started in!

Anyone is free to try and tackle any issue that's what open source is al about :) Good luck!

**Comment by Jarek1542** [comment]
Does the zig cc subcommand default to 64-bit mode compilation? After reading up a bit about Carbon, it seems that it isn't supported by 64-bit compilation, and was wondering if there was a potential workaround following that fact.
