### ISSUE TITLE
LLVM dependency is weakest link for portability

### ISSUE THREAD

**Issue by jbsolomon-fw** [ziglang/zig#6933]
Hi,

I was thinking about what would be involved in porting the Zig compiler to another system (on RISC-V, for example), and I'm concerned obtaining LLVM could be a tricky part.  Is there any intent to create a Zig build for LLVM itself (from the required version of its source tree) so that the particular version required to build Zig doesn't need to be installed / available on the host system?

Cheers,

Bodie

**Comment by andrewrk** [comment]
I believe this repo has everything you need: https://github.com/ziglang/zig-bootstrap

You can see it is known to support RISC-V for example.

Let me know if you want to re-open the issue
