### ISSUE TITLE
isWhiteSpace doesn't exist

### ISSUE THREAD

**Issue by SamTebbs33** [ziglang/zig#6935]
std.fmt.isWhiteSpace has been deprecated in favour of std.mem.isWhiteSpace, but std.mem.isWhiteSpace doesn't exist.

> ./src/kernel/panic.zig:183:19: error: container 'std.mem' has no member called 'isWhiteSpace'
    while (std.mem.isWhiteSpace(try parseChar(ptr + i, end))) : (i += 1) {}
                  ^
/home/sam/builds/zig/lib/zig/std/fmt.zig:1707:26: error: deprecated; use std.mem.isWhiteSpace instead
pub const isWhiteSpace = @compileError("deprecated; use std.mem.isWhiteSpace instead");
                         ^
./src/kernel/panic.zig:205:20: note: referenced here
    while (!std.fmt.isWhiteSpace(try parseChar(ptr + i, end))) : (i += 1) {}

Above you can see one example of me using fmt.isWhiteSpace and another using mem.isWhiteSpace.

**Comment by Luukdegram** [comment]
Seems a PR has been opened for this: https://github.com/ziglang/zig/pull/6931

**Comment by SamTebbs33** [comment]
Thanks @Luukdegram, I'll use std.ascii.isSpace until this is fixed.

**Comment by andrewrk** [comment]
#6931 merged. sorry about the regression

**Comment by SamTebbs33** [comment]
> #6931 merged. sorry about the regression

No problem, thanks @andrewrk  and @ifreund .
