### ISSUE TITLE
Packaging zig in npm

### ISSUE THREAD

**Issue by breakin** [ziglang/zig#6959]
I am testing zig for web work. I use node since it is a very convenient way to setup a web-server.
Wouldn't it be nice if I could just do

`npm install ziglang`

and then the zig command was available?

Npm has versioning so if my program was written against zig 0.5 then that is the version that would be used when compiling.
If I have multiple projects on my machine (maybe from checking out code from github) they can use different versions of zig.
I can upgrade the zig version per-project when I want to also update my program.

Notice that this issue is NOT about having source code in npm, just the zig compiler. Zig dependencies can be handled in any way the user want outside of this...

I am not good at CI or npm/node so I don't feel that I can contribute to this issue myself but just wanted to bring up the idea.

Very happy to be playing with zig, working like a charm so far!

**Comment by andrewrk** [comment]
It could be an interesting project to try to do this, however it's out of scope of this particular repository and I want to keep the issues organized. I suggest to bring this up in one of the [community spaces](https://github.com/ziglang/zig/wiki/Community).
