### ISSUE TITLE
Suggestion! 

### ISSUE THREAD

**Issue by yezz123** [ziglang/zig#6961]
Hey! 
- As example making a general library and classes working for both of python language and zig language and support all The method For example : 
in Python we can extend with both C and C++ :  
<details>
<summary>Extending Python with C or C++</summary>

```pyhton
import spam
status = spam.system("ls -l")
```
```C
#define PY_SSIZE_T_CLEAN
#include <Python.h>
```
```C++
static PyObject *
spam_system(PyObject *self, PyObject *args)
{
    const char *command;
    int sts;

    if (!PyArg_ParseTuple(args, "s", &command))
        return NULL;
    sts = system(command);
    return PyLong_FromLong(sts);
}
```
</details>

- And this can be a great growth for ziglang if they start with extending with python and goo to other similar Lang

**Comment by daurnimator** [comment]
@yezz123 I don't see/understand any specific feature requests in your post; you can already do this today in zig.
