### ISSUE TITLE
std.ArrayListSentineled integer overflow error.

### ISSUE THREAD

**Issue by arqv** [ziglang/zig#6967]
The following code errors with an `integer overflow` error coming from the `std.ArrayListSentineled` function `len()`.
The mentioned function doesn't seem to consider the case of a "null" initialized array, and therefore tries to subtract 1 from the
length of the backing array (which is zero because it was null-initialized)

```zig
const std = @import("std");
const List = std.ArrayListSentineled(?u8, null);

pub fn main() anyerror!void {
    const alloc = std.heap.page_allocator;
    var my_list = List.initNull(alloc);
    defer my_list.deinit();
    try my_list.append(12);
    std.debug.print("len: {}\n", .{my_list.len()}); // Also fails.
}
```

**Comment by travv0** [comment]
I think the doc comment's relevant here:
```zig
        /// None of the other operations are valid until you do one of these:
        /// * `replaceContents`
        /// * `resize`
```

**Comment by arqv** [comment]
This might get into the personal preference territory, but I think that the function should not error unexpectedly, even if the operation is "invalid". Maybe returning an error would also be a good alternative, but didn't want to propose it as a change as it would be a breaking one.

**Comment by daurnimator** [comment]
@arqv it's more than an error; it's caught undefined behaviour.

**Comment by arqv** [comment]
The other problem is that `append`ing to the ArrayListSentineled (probably) is a valid way to "initialize" it, and it still fails due to the integer overflow error mentioned below.
