### ISSUE TITLE
Adding compile options in build.zig

### ISSUE THREAD

**Issue by CherryMan** [ziglang/zig#6994]
There are some compile options that I can't see to figure out how to set in `build.zig`, such `-fPIC` and `-code-model`. From what I can see, these options are available in `LibExeObjStruct` in `build.zig` through the `force_pic` and `code_model` fields.

I'm wondering if these can be set in `build.zig`, and if not what would be the appropriate way of exposing such functionality. Is the approach to add a setter for every relevant option (such as `setForcePic(bool)` and `setCodeModel(...)`). This might just be a documentation issue.

Similarly, there's also `-mllvm` which, although unsupported, _may_ be useful to some. I saw a function called `setBuildOption` that prints text to some file. I'm not sure if this would be used for setting compile options, and I suspect this might need documenting.

**Comment by pfgithub** [comment]
zig build's documentation should tell you this is possible:
```zig
exe.force_pic = true;
exe.core_model = true;
```
`setBuildOption` is used for giving build information to source code
```zig
// build.zig
exe.setBuildOption("render", Renderer.render);
// main.zig
@import("build_options").render;
```
There is currently no way to add arbitrary command line flags from build.zig except for manual system commands

**Comment by alexnask** [comment]
> There is currently no way to add arbitrary command line flags from build.zig except for manual system commands

std.build.Builder.addOption lets you define `-Doption_name=<value>` flags.  

> I'm wondering if these can be set in build.zig, and if not what would be the appropriate way of exposing such functionality. 

You should set the fields you just mentioned in your executable/library targets :)

**Comment by CherryMan** [comment]
Thanks for the quick response! Can't believe I hadn't thought of just mutating the field.
