### ISSUE TITLE
Relax generic function type erasure

### ISSUE THREAD

**Issue by alexnask** [ziglang/zig#6997]
### Definitions

- Generic function: A function is generic when at least one of its arguments is generic, or when it returns a compile time only type  
- Generic argument: An argument is generic when it is `comptime` or `anytype`  

### Current behavior

In stage1, generic function type erasure works in the following way:  
If any of the arguments is generic, all of the following arguments are type erased, as well as the return type (erased types are represented as `anytype` in the typename of the type of the generic function)  
If no arguments are generic but the return type is a compile time only type, the return type is type erased.  

### Proposal

If none of the arguments are generic but the return type is comptime only, the function shall be marked as generic but the return type shall not be type erased.  
When at least one of the arguments is generic, the following shall be applied to the rest of the arguments and the return type:  
- If the type expression contains any references to a preceding generic or type erased argument, the current argument or return type shall be type erased  
- Otherwise, the argument or return type shall remain unmodified

**Comment by dbandstra** [comment]
Does this only affects `@typeInfo` and `@typeName`?

I made this snippet to help myself understand the situation (this is 0.6.0):

```zig
const std = @import("std");

fn func(a: u16, comptime T: type, value: u32) void {}

pub fn main() void {
    std.debug.warn("{}\n", .{@typeName(@TypeOf(func))});

    inline for (@typeInfo(@TypeOf(func)).Fn.args) |arg| {
        if (arg.arg_type) |T| {
            std.debug.warn("- {}\n", .{@typeName(T)});
        } else {
            std.debug.warn("- null\n", .{});
        }
    }

    if (@typeInfo(@TypeOf(func)).Fn.return_type) |T| {
        std.debug.warn("returns {}\n", .{@typeName(T)});
    } else {
        std.debug.warn("returns null\n", .{});
    }
}

```

```
fn(u16,type,var) var
- u16
- type
- null
returns null
```

**Comment by Rocknest** [comment]
I was thinking this behaviour is a bug

**Comment by alexnask** [comment]
@dbandstra This affects the type of generic fns, and in turn typeInfo and typeName, yes.  
In this specific exzample `@TypeOf(func)` would become `fn (u16, type, u32) void` and the null values in typeInfo would get a concrete type value.

**Comment by cryptocode** [comment]
This would be great to get fixed, I have a use case where it's needed but am running into:

```
// NOTE: replacing anytype with u64 makes it compile
fn less(a: anytype, b: anytype) bool {
    return a < b;
}

fn Something(comptime func: anytype) type {
    const RET = @typeInfo(@TypeOf(func)).Fn.return_type.?;  // <--- error: unable to unwrap null
    /// ....
    return RET;
}

pub fn main() void {
    const ft = Something(less);
}
```

**Comment by Vexu** [comment]
Implemented in self-hosted:
```
git grep "generic function types" test
test/behavior/type_info.zig:test "type info: generic function types" {
```
