### ISSUE TITLE
Package paths should be included in the cache hash

### ISSUE THREAD

**Issue by alexnask** [ziglang/zig#7018]
Currently, switching the path of a package and trying to recompile will not trigger a cache miss, and thus the output will not be modified.  

While this is probably quite a niche problem, the behavior still seems wrong.  
Personally, I would like this to be able to `zig run` a custom build_runner for multiple projects without moving it around or constantly deleting the cache, just by changing the path of a package, as part of zls.

**Comment by nektro** [comment]
are there any stages in the build pipeline that require the absolute paths that are used? using relative paths if possible would make builds a lot more reproducible and also fix this issue.

**Comment by alexnask** [comment]
From what I can tell absolute paths aren't required anyway but may end up bein used to calculate the cache hash if the user explicitly uses them (for example, the path to the root package or the path passed to `--override-lib-dir` etc.)
