### ISSUE TITLE
Proposal: Expected panic in tests

### ISSUE THREAD

**Issue by DutchGhost** [ziglang/zig#7039]
When writing tests, you sometimes want to assert that the entire test itself panics. Currently we have no way of doing so.

Im proposing some way of notating that a test must panic in order to succeed. If the test does not panic when it should, the test does not succeed.

A simple syntax that is inline with calling conventions could be something along the lines of:
```Zig
test "name" conv(.ShouldPanic) {
    std.testing.expectEqual(true, false);
}
```
The test above is considered succesfull, the convention says it expects a panic, which happens.

The default convention of tests would become `conv(.NoPanic)` or something along those lines.

Some other languages also provide similar facilities in their tests, Rust for example has `#[should_panic]`.

**Comment by data-man** [comment]
@DutchGhost There is accepted #6621.

**Comment by LemonBoy** [comment]
See #513 and #1356.
