### ISSUE TITLE
Compiler quits with exit code 1 on windows when two `zig build` instances are running

### ISSUE THREAD

**Issue by FireFox317** [ziglang/zig#7042]
On Windows having a long running `zig build run` and then doing `zig build another` in another window, will make the `zig build another` command quit with exit code 1 and no other output. I cannot debug this since a debug build of Zig also requires a debug build of LLVM on Windows -_-

**Comment by andrewrk** [comment]
> I cannot debug this since a debug build of Zig also requires a debug build of LLVM on Windows -_-

I'm working on this over in #7309!

**Comment by andrewrk** [comment]
> I'm working on this over in #7309!

[Done](https://github.com/ziglang/zig/wiki/Building-Zig-on-Windows#option-1-use-the-windows-zig-compiler-dev-kit). One yak down, one ever-growing yak stack to go.

**Comment by andrewrk** [comment]
Chatted with @FireFox317 on IRC, he is no longer able to reproduce the issue and we suspect this was a duplicate of #3825 (fixed by #7355)
