### ISSUE TITLE
ReleaseSmall unrolling loops

### ISSUE THREAD

**Issue by atomicbitty** [ziglang/zig#7048]
I have been playing with zig recently, and I noticed that ReleaseSmall is not making the executable size any smaller than ReleaseFast. For example, an executable compiled with ReleaseSmall shouldn't have loop unrolling, but according to Godbolt, [it has](https://godbolt.org/z/8jze5G). Sorry if i'm wrong, but this seems like a bug to me.

**Comment by andrewrk** [comment]
I agree with your assessment. Here are the next steps for this issue:
 * Verify that zig is passing "small" optimization mode to LLVM (I believe it is, but let's verify)
 * File upstream bug report in LLVM and solve the problem there.

One quick thing you could try would be doing the equivalent godbolt but with C code and Clang 11 with `-Os`.

**Comment by jedisct1** [comment]
That doesn't seem to happen with C code:

- [-Os](https://godbolt.org/z/h1qfcY)
- [-Ofast](https://godbolt.org/z/axGn5s)

**Comment by atomicbitty** [comment]
@andrewrk 
Clang didn't have this problem, so i think it's a problem in the compiler.

**Comment by atomicbitty** [comment]
According to [https://github.com/ziglang/zig/blob/6904cd828edb34217cd4d54e8f6fe5bb91cb4858/src/Compilation.zig#L1939](https://github.com/ziglang/zig/blob/6904cd828edb34217cd4d54e8f6fe5bb91cb4858/src/Compilation.zig#L1939),
It's passing the `-Os` option, but I'm not sure because I never worked with this code.

**Comment by alexnask** [comment]
zig is passing the equivalent of `-Oz` to LLVM when in ReleaseSmall mode (although it passes `-Os` for `zig cc`)

**Comment by andrewrk** [comment]
@atomicbitty that's for compiling C code. For LLVM IR modules, the code path is here:

https://github.com/ziglang/zig/blob/8b9195282e99427964119431b6f4e535eeb4d9ba/src/zig_llvm.cpp#L217-L218

We should double check what Clang sets the PMBuilder fields to for `-Os`

**Comment by alexnask** [comment]
```
clang-11.0.0.src/include/clang/Basic/CodeGenOptions.def:178:
    VALUE_CODEGENOPT(OptimizeSize, 2, 0) ///< If -Os (==1) or -Oz (==2) is specified.

clang-11.0.0.src/lib/CodeGen/BackendUtil.cpp:620: 
    PMBuilder.SizeLevel = CodeGenOpts.OptimizeSize;
```

**Comment by atomicbitty** [comment]
[](https://github.com/ziglang/zig/blob/8b9195282e99427964119431b6f4e535eeb4d9ba/src/zig_llvm.cpp#L221)
Again, I never worked with this code nor have I written my own compiler, but it looks like loop unrolling is only disabled if the Debug mode is enabled.

**Comment by jedisct1** [comment]
Good catch, @atomicbitty !
