### ISSUE TITLE
Comparison with with std.math.maxInt() is not evaluated

### ISSUE THREAD

**Issue by kenaryn** [ziglang/zig#7050]
Hello,

I'm using zig 0.7.0 on Windows 10.19H1 and run the following command which unexpectly passes instead of failing:
`zig test my_file.zig`

`const std = @import("std");

test "expect testing" {
    comptime if (std.math.maxInt(u10) == 1_000_000) @compileError("An error at comptime is not raised here.");
    if (std.math.maxInt(u10) == 1_000_000) @panic("You shall bloody fail right here also but you don't.");
}
`
It seems to me the code is not even evaluated.

Thanks to iksuh, g-w1 and alexnask[m] for their help on IRC.

**Comment by LemonBoy** [comment]
`std.math.maxInt(u10)` returns 1023, `u10` has 10 bits and can represent values `[0...2^10)`.
