### ISSUE TITLE
Proposal: make switch(exhaustive-enum) safer

### ISSUE THREAD

**Issue by cajw1** [ziglang/zig#7053]
[Accepted Proposal](https://github.com/ziglang/zig/issues/7053#issuecomment-977216391)

-----

```zig
const std = @import("std");

const SparseU32 = enum(u32){one=1,};

pub fn main() void {

    var rtu32 : u32 = 99;
    var sparse : SparseU32 = .one;
    sparse = @ptrCast(*SparseU32,&rtu32).*;

    // 1.
    // Note: sparse is not undefined here, 
    // and branching on it using an if statement 
    // is fine including in release-fast

    std.debug.warn("Observing sparse using if...\n", .{}); 
    if(sparse==.one){
        std.debug.warn("observed .one ({}) \n", .{@bitCast(u32,sparse)}); 
    } else {
        std.debug.warn("observed NOT .one but {} \n", .{@bitCast(u32,sparse)}); 
    }
        // ==> This prints:
        // Observing sparse using if...
        // observed NOT .one but 99

    // 2.
    // However, branching on sparse using a switch is
    // either a bug, or UB (which I would argue is entirely
    // avoidable):

    std.debug.warn("Observing sparse using switch...\n", .{}); 
    switch(sparse){
        .one => {std.debug.warn("observed .one ({}) \n", .{@bitCast(u32,sparse)});}
        // This proposal suggest that this hidden prong 
        // be executed for every invalid value of sparse:
        // _ => {@panic("helpful invalid value message");}
    }
        // ==> This prints:
        // Observing sparse using switch...
        // observed .one (99) 

    std.debug.warn("we get here even in release-fast \n", .{});
}
```
Switching on an exhaustive enum with a tagtype capable of holding invalid values cannot guarantee that exactly one of its branches executes (or if it does, it will be the wrong branch) because Zig cannot exclude the possibility of an invalid value. Since we know this can happen, I suggest that a switch on an exhaustive enum without an else prong is always (including in --release-fast) defined as if it had an implicit _ prong which panics. I don't see why the switch should behave differently to an equivalent if ... inspection.

**Comment by andrewrk** [comment]
Here is the relevant accepted portion of the language spec:

When safety-checks are enabled, switching on an exhaustive enum with no `else` prong, there will be a machine code else prong that panics if it is hit, to catch if the value of the enum was outside the valid range. When there is an `else` prong in the zig source,  it will be lowered to exhaustively listing all the non-listed tags and mapping those to the *source* else prong, and again there will be a *machine code* else prong that panics if the enum tag is outside the valid range.

When safety-checks are disabled, switching on an exhaustive enum with no else prong, will effectively map the "else" branch to unreachable. This means undefined behavior if the enum value is not one of the valid bit patterns.
