### ISSUE TITLE
Compiler allows comptime expression consisting of non-comptime terms

### ISSUE THREAD

**Issue by jonascarpay** [ziglang/zig#7056]
The expression for `d` should not be allowed to be `comptime` since neither `a` nor `b` are, but the compiler does not reject it:
```zig
test "weirdness" {
    var timer: Timer = try Timer.start();
    const t0 = timer.read();
    const t1 = timer.read();
    const d = comptime t1 - t0;
    expect(d > 0);
}
```

[IRC](https://freenode.irclog.whitequark.org/zig/2020-11-10#28332161;)

**Comment by JorisHartog** [comment]
I think I have a fix for this, I hope I'll have a PR ready some time this week :)

**Comment by JorisHartog** [comment]
FYI: couldn't get it to work, sorry.
