### ISSUE TITLE
fs.path.join on Windows should consider both \ and / as path separators

### ISSUE THREAD

**Issue by travv0** [ziglang/zig#7062]
Right now it calls `joinSep` with `'\\'` as the separator which means you can end up with things like `"path/to/\\something"`.  On Windows it should probably use `isSep` so that it takes both valid separators into account when joining.

**Comment by daurnimator** [comment]
This may be trickier than it looks on the surface: for NT paths, `/` is valid; for recent win32, `/` is converted to `\`

**Comment by travv0** [comment]
Wouldn't that happen sometime after the path joining? If I'm understanding what you're saying, "foo/bar" would be accepted by NT and converted to "foo\bar" for win32?

**Comment by daurnimator** [comment]
> If I'm understanding what you're saying, "foo/bar" would be accepted by NT and converted to "foo\bar" for win32?

It would be accepted by both; but has different meanings for NT vs win32.
