### ISSUE TITLE
Proposal: Add fixed-point arithmetic types

### ISSUE THREAD

**Issue by kliberty** [ziglang/zig#7093]
Fixed point arithmetic seems to be used often in embedded systems and business logic. IMO this would be an attractive addition to the language.

If we only wanted to support binary numbers I would propose using the syntax Qm.f (where m is the number of magnitude bits and f is the number of fractional bits). Alternatively, types could be based on a builder to support complex features `@FixedPoint(magnitude, fractional, saturate = false, decimal = false)` .

**Comment by Vexu** [comment]
Duplicate of #1974
