### ISSUE TITLE
Miscompilation with switch in anonymous struct literal

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#7097]
The following function will always print `reading from` and will ignore the runtime parameter:

```zig
fn logErrorBad(err: Error, address: u24, access: BusAccess) Error {
    std.debug.print("{} when {} {X:0>6}\n", .{
        @errorName(err),
        @as([]const u8, switch (access) {
            .read => "reading from",
            .write => "writing to",
        }),
        address,
    });
    return err;
}
```

Fully runnble example can be found here:
https://gist.github.com/MasterQ32/da5b1f2dbe4ebc89ebbf602d8b118fca

Moving out the switch+`@as` will fix the problem. This is probably a known issue already

**Comment by travv0** [comment]
Related to #3882?

**Comment by dbandstra** [comment]
I think this is a more likely duplicate: https://github.com/ziglang/zig/issues/6444

**Comment by Mouvedia** [comment]
dupe of #5230
