### ISSUE TITLE
test names should be required to be unique

### ISSUE THREAD

**Issue by frmdstryr** [ziglang/zig#7100]
Currently zig doesn't care if a test name is duplicated.  I think this should be a compile error because if one fails it can cause confusion as to which one especially in release mode where no trace is given.  This also encourages more useful test names.

```zig
const std = @import("std");

fn foo(a: u8, b: u8) bool {
    return a==b;
}

test "foo" {
    std.testing.expect(foo(1,1));
}

test "foo" {
    std.testing.expect(foo(1,2)); // Wrong
}
```

```
$ zig test test-names.zig -OReleaseSafe
Test [2/2] test "foo"... test failure
error: the following test command crashed:
```

**Comment by marler8997** [comment]
Are you proposing that test names only be unique in the same file, or that they be unique across all files being compiled?

**Comment by frmdstryr** [comment]
Same file / namespace like functions are. 

Idk if this was done intentionally to avoid problems like that... if that's the case this can be closed.

**Comment by marler8997** [comment]
My thoughts on this are "meh".  It seems like a small improvement but would add some overhead to enforce.  Another thing to consider is that we could have nameless tests, which could be reported by the file/line they appear in.
