### ISSUE TITLE
[macOS] *.m files cant be fed to `LibExeObjStep.addCSourceFile`

### ISSUE THREAD

**Issue by prime31** [ziglang/zig#7119]
It seems [this is the error](https://github.com/ziglang/zig/blob/master/src/main.zig#L939) that is getting triggered.

Repro with a build.zig that has this:
```zig
    const lib = b.addStaticLibrary("mtl", "src/main.zig");
    lib.setBuildMode(b.standardReleaseOptions());
    lib.install();

    const cflags = [_][]const u8{ "-std=c99", "-ObjC", "-fobjc-arc" };
    lib.addCSourceFile("some_file.m", &cflags);
```

If it's an acceptable fix I can add classifying `*.m` as a valid C source file (here)[https://github.com/ziglang/zig/blob/master/src/Compilation.zig#L2063] in the `hasCExt` method.

**Comment by LemonBoy** [comment]
> If it's an acceptable fix I can add classifying *.m as a valid C source file (here)[https://github.com/ziglang/zig/blob/master/src/Compilation.zig#L2063] in the hasCExt method.

No because it's not C, you can add a new entry (`.objc`?) and have the the compiler handle as it does for c/cpp files.
Pay extra attention to any extra flags you need when compiling objc code.

**Comment by andrewrk** [comment]
Test coverage added by @kubkon in 0ce54a141628b27ceab074dac4c19827a2188165.
