### ISSUE TITLE
else prong works even when it is exhaustive switch stage1

### ISSUE THREAD

**Issue by g-w1** [ziglang/zig#7120]
This works:

```zig
pub fn main() void {
  const x = error.T;
  switch (x) {
    error.T => {},
    else => {}
  }
}
```

but it should not allow `else` because `@TypeOf(x) == error { T }` (according to `@compileLog`) so else is unreachable. I will try to fix this.

**Comment by Vexu** [comment]
This was intentionally left out when the error for unreachable else prongs was added (#5693) since it caused issues generic code.

**Comment by g-w1** [comment]
Ah, well ill let the other pr handle this, thanks.
