### ISSUE TITLE
Symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by clankill3r** [ziglang/zig#7127]
Hi,

I downloaded zig-macos-x86_64-0.7.0.tar.xz and tried the following "example":

https://ziglang.org/#Performance-and-Safety-Choose-Two

```
test "integer overflow at compile time" {
    const x: u8 = 255;
    const y = x + 1;
}
```

But I get the following output:

> dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
>   Referenced from: /Applications/zig-macos-x86_64-0.7.0/zig
>   Expected in: /usr/lib/libSystem.B.dylib
> 
> dyld: Symbol not found: ____chkstk_darwin
>   Referenced from: /Applications/zig-macos-x86_64-0.7.0/zig
>   Expected in: /usr/lib/libSystem.B.dylib
> 
> Abort trap: 6

I'm on OSX 10.12.6.

I would love if someone can help. I mostly have only have experiences with java sadly enough...

**Comment by jedisct1** [comment]
Hi!

Zig requires [at least macOS 10.13](https://ziglang.org/#Support-Table).

macOS 10.12 reached end of life more than a year ago, and Apple doesn't even provide security updates for it ever since.

Continuous Integration systems don't offer it any longer either, so this is not a platform we can easily test Zig on.

**Comment by clankill3r** [comment]
Hi! Thanks, I will update to 10.13 then cause I notice that slowly 10.12 is getting to old :)
(blender 2.9 and docker needs 10.13 as well...)

**Comment by mkeeter** [comment]
I'm encountering this exact issue on **macOS 10.13.6** and the Zig 0.7.0 release, so this should probably be reopened:
```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/zig (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/zig (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

fish: 'zig build run' terminated by signal SIGABRT (Abort)
```

**Comment by clankill3r** [comment]
I updated for 10.13.6 and for me the problem is gone. I have another problem now, but I go look into that now.

**Comment by clankill3r** [comment]
Ok I fixed the other problem and now I have exactly what you have.
