### ISSUE TITLE
List of zig sources in CMakeLists.txt incomplete

### ISSUE THREAD

**Issue by daurnimator** [ziglang/zig#7136]
https://github.com/ziglang/zig/commit/8b3c1ed7342950fd76a4aff6c7565789a71d9e61#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR311-R314

This list is wrong in the general case: it is only correct for the target where that list was created i.e. linux x86_64.

**Comment by andrewrk** [comment]
The list of source files is working well enough. There is no plan to make the CMakelists.txt source listing completely up to date and accurate for all targets. Improvements are welcome in the form of pull requests.
