### ISSUE TITLE
Allow `++` and `**` when _contents_ are not compile-time known

### ISSUE THREAD

**Issue by lucascharlesmyers** [ziglang/zig#7147]
As I understand it, `++` and `**` require that both operands are compile-time known, in their entirety. I would think `++` could be 
 extended to work when the contents of an operand are not `comptime`-known, as long as the lengths of both are `comptime`-known. The same would go for `**`, which should in theory be doable as long as the length of the left-hand-side is `comptime`-known, and the right-hand-side is `comptime`-known.

The primary use-cases I see for this are when these operators are extended to tuples (along with tuple slicing, #4625). Being able to concatenate and slice tuples of runtime-known contents is very useful in combination with any functions that take tuples as emulated var-args, especially `@call`.

**Comment by mrakh** [comment]
The problem with using `++` or `**` for this is that it hides what is potentially a runtime-expensive memory copy. That kind of opaqueness goes against the Zen of Zig. I would use a dedicated built-in for this operation instead, with a name communicating the potential cost explicitly - perhaps something like `@concatenate` or `@concatArrays`?

**Comment by SpexGuy** [comment]
> it hides what is potentially a runtime-expensive memory copy

This isn't unprecedented, assignment with `=` does the same thing when the object being assigned is a large struct or array value.  In general, the zig ideals don't necessarily say that operators need to be cheap, they just require that operators can't run user code or alter control flow.  I think this is reasonable to implement.

**Comment by gwenzek** [comment]
From  [Zig weekly meeting notes](https://docs.google.com/document/d/1GFQxcoXgzmOFThjFLpjkVASopa33el2f5esvk_OZlCo/edit#heading=h.qi1ybyf2yvo2):

> As long as the lengths are comptime known, the programmer’s intent is clear here, and this seems like it should work.  The argument is raised in the issue that these operators would be expensive with large arrays, but so is assignment with large structs.  That doesn’t seem to be a strong reason to avoid this, and the language is more complicated to use if these operators don’t work in places where they could.

**Comment by andrewrk** [comment]
This is implemented in self-hosted, which is now the default compiler.
