### ISSUE TITLE
Problem with compiler

### ISSUE THREAD

**Issue by tritinykek** [ziglang/zig#7155]
So, im new to zig and I installed plugin to the intellij, and added zig buildtest configuration and after compiling it says:

`/bin/zig build-exe /home/tritiny/IdeaProjects/zigtest/test.zig --zig-install-prefix "" --output /home/tritiny/IdeaProjects/zigtest/out/buildtest
error: unrecognized parameter: '--zig-install-prefix'`

I see that there is `--zig-install-prefix` and i read that it was deleted in newer versions, but how i can fix this?

**Comment by daurnimator** [comment]
This is an issue you'll need to ask the authors of the intellij plugin. I guess that's over at https://github.com/ice1000/intellij-zig/issues ?
