### ISSUE TITLE
upstream: llvm crash when using `zig cc` to compile zstd for `powerpc64-linux-musl`

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#7161]
Files:
https://github.com/facebook/zstd @ `v1.4.5`

Command:
`zig cc ./programs/*.c ./lib/common/*.c ./lib/compress/*.c ./lib/decompress/*.c ./lib/dictBuilder/*.c --target=powerpc64-linux-musl`

Output:
https://gist.github.com/nektro/0dc3ffd8ade5102323e50599e1fdc4e7

Zig Version:
```
0.7.0+a0226ab05
```

Clang Version
```
clang version 11.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by daurnimator** [comment]
This appears to be an LLVM bug; could you open an issue there?

**Comment by LemonBoy** [comment]
Hold your horses, the problem is Zig's choice of default cpu.
