### ISSUE TITLE
Peer type resolution: resolve unsigned ints with larger signed ints

### ISSUE THREAD

**Issue by mb64** [ziglang/zig#7173]
Currently, the rules for subtyping say that `uN` is a subtype of `iM` if and only if M is strictly larger than N.  For example, this code works:
```zig
fn f(value: i32) void {}

var x: u31 = 7;
var y: i32 = x; // x upcasts to the larger i32 type
f(x); // x upcasts to the larger i32 type
```

However, this subtype relationship isn't respected by peer type resolution, so this is an error:
```zig
var x: u8 = 7;
var y: i32 = x;
var z = x + y;
```
Results in:
```
./test.zig:4:15: error: incompatible types: 'u8' and 'i32'
    var z = x + y;
              ^
```

It would be nice if this worked.

This is either a proposal or a bug report, depending on whether peer type resolution is intended to exactly follow the subtyping relation.

**Comment by Mouvedia** [comment]
That reminds me of #6664

**Comment by nektro** [comment]
`var z = x + y;` I would expect this to be an error

`var z = y + x;` however, I would expect this to be okay.

**Comment by daurnimator** [comment]
> `var z = x + y;` I would expect this to be an error
> 
> `var z = y + x;` however, I would expect this to be okay.

why? I would expect it to be commutative

**Comment by nektro** [comment]
> I would expect it to be commutative

would you then want `z`'s type to be `i32` in both cases?

**Comment by daurnimator** [comment]
> would you then want `z`'s type to be `i32` in both cases?

Yes.
