### ISSUE TITLE
'comptime_int' error when switching on caught Error

### ISSUE THREAD

**Issue by tau-dev** [ziglang/zig#7179]
Trying to compile
```zig
fn test() error{A}!usize {
    return 1;
}

test "switch" {
    var x = test() catch |err| switch (err) {
        error.A => 2,
        else => 3,
    };
}
```
results in
```
error: values of type 'comptime_int' must be comptime known
    var x = test3() catch |err| switch (err) {
                                ^
```
I'm fairly new to Zig, so maybe I need to solve this differently and the error is intended behavior, but it feels like it shouldn't be.

**Comment by LemonBoy** [comment]
This [section](https://ziglearn.org/chapter-1/#comptime) on ZigLearn explains that literal values are of type `comptime_int`, you need to tell the compiler what type you want by:
* Using `var x: <type> = ...`
* Having at least one branch a cast such as `@as(<type>, <number>)`

**Comment by nektro** [comment]
This also seems like a bug because it should be showing the error that the `else =>` is invalid due to the `switch` already being exhaustive first.

**Comment by Vexu** [comment]
Stage2 issue in #11812
