### ISSUE TITLE
negative modulii for @mod should be supported.

### ISSUE THREAD

**Issue by dgottner** [ziglang/zig#7196]
@mod for negative modulii (e.g. @mod(257, -3) yields a runtime exception currently. There's no reason to not allow, since the modulus operator should be well-defined for negatives.

The division algorithm states that a/b can be written as a = bq + r, so the remainder, r, is always well-defined whenever a/b (e.g. @divFloor) is well-defined, namely r = a - @divFloor(a/b)*b.

For b > 0, @mod(a, -b) = -@mod(-a, b) gives the correct remainder for floored division with a negative divisor.

e.g. under floored division,
 257 /  -3 = -86* -3 - 1, so the remainder is -1.
-257 / -3 = 85 * -3 - 2, so the remainder is -2.

**Comment by LemonBoy** [comment]
#6714
