### ISSUE TITLE
consistent casing for all builtin functions?

### ISSUE THREAD

**Issue by itmuckel** [ziglang/zig#7252]
I'm sure this has been raised before, but I can't see a reason for this:

![grafik](https://user-images.githubusercontent.com/18561536/100536527-87e25a00-3221-11eb-86d3-1b21ed1ca7a2.png)

Almost all builtin functions start with a lowercase letter and I was very surprised when I tried to use `@typeOf` and got a compile time error, because I missed that this is a special case that starts with an uppercase letter. Is there a reason for these exceptions?

**Comment by VojtechStep** [comment]
In Zig, all types start with an uppercase letter (by convention), and `@TypeOf` returns a type. The same goes for the other exceptions.

**Comment by itmuckel** [comment]
Ah, and all functions that return types should also start with uppercase letter. Searched for "casing" and didn't find that issue, closing.
