### ISSUE TITLE
sentinel array reports wrong length after coercion to non-sentinel

### ISSUE THREAD

**Issue by SenneH** [ziglang/zig#7258]
```zig
test "string len" {
    var str: *const[5:0]u8 = "hello";
    expect(str.len == 5);
    var str2: [:0]const u8 = str;
    expect(str2.len == 5);
    var str3: []const u8 = str;
    expect(str3.len == 6); // fails
}
```
I don't know if this is a bug or by design, but this doesn't seems like desired behavior to me. 
the sentinel is undoubtedly still part of the length, unless explicitly stated otherwise this information should not go lost.
The default cast when converting from sentinel to non-sentinel should be `var foo: []const u8 = bar[0..bar.len+1]`, not `var foo: []const u8 = bar[0..bar.len]`

**Comment by daurnimator** [comment]
> The default cast when converting from sentinel to non-sentinel should be `var foo: []const u8 = bar[0..bar.len+1]`, not `var foo: []const u8 = bar[0..bar.len]`

The length is not included in the resulting string on purpose. Otherwise e.g. passing a sentinel slice/pointer to a function expecting a non-sentinel would suddenly gain a trailing byte.
