### ISSUE TITLE
Missing symbol in compiler_rt in release modes

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#7260]
When compiling [Zig Showdown](https://github.com/zig-community/Zig-Showdown) for release, i get the following error when not linking libc/libm: 

```
ld.lld: error: undefined symbol: sincosf
```

The symbol sincosf is not used in any file in the project, so i assume it is required to be in `compiler_rt` as a compiler optimization kicks in

**Comment by andrewrk** [comment]
Here's where it needs to be added: https://github.com/ziglang/zig/blob/master/lib/std/special/c.zig
