### ISSUE TITLE
zig cc -target x86_64-macos-gnu fatal error: ' sys/ioctl.h' and 'sys/filio.h' file not found

### ISSUE THREAD

**Issue by zhaozg** [ziglang/zig#7261]
[ 93%] Building C object luv.dir/deps/libuv/CMakeFiles/uv_a.dir/src/unix/core.c.o
/Users/zhaozg/work/luaclibs/luv/deps/libuv/src/unix/core.c:34:10: fatal error: 'sys/ioctl.h' file not found
#include <sys/ioctl.h>
         ^~~~~~~~~~~~~
1 error generated.
make[5]: *** [luv.dir/deps/libuv/CMakeFiles/uv_a.dir/src/unix/core.c.o] Error 1
make[4]: *** [luv.dir/deps/libuv/CMakeFiles/uv_a.dir/all] Error 2

**Comment by andrewrk** [comment]
I tested using `zig cc` to build libuv after this commit and I got an error during linking the dylib, but when I patched out the dynamic lib from the cmake code, it did successfully build the static lib.
