### ISSUE TITLE
Proposal: add --pkg-begin and --pkg-end flags to `zig build`

### ISSUE THREAD

**Issue by mattnite** [ziglang/zig#7262]
So with zkg (and other package managers on the market atm) you get a node/npm feel where the runtime/compiler and package manager are separate entities and you use both. In this case you fetch dependencies then you compile your project. I've gotten the question several times now asking if fetch and build can be done in one command (besides `zkg fetch && zig build` that is) and I think that people might want an experience more like cargo which wraps the rust compiler and does a bunch of cool stuff. (Note: this mechanic is all I'm trying to support, I've heard that there were design decisions made that aren't popular and I've yet to look into them but I'm assuming they're orthogonal to the contents of this proposal).

So what this proposal would do would allow a user to specify packages that the build runner could import. Right now in zkg, importing a package in `build.zig` looks like:
```zig
const pkgs = @import("deps.zig").pkgs;
const my_lib = @import(pkgs.my_lib.path);
```
which I think is a bit verbose, and less declarative than what we want the official package management to look like. This proposal would make it look like this:
```
zig build --pkg-begin my_lib /some/path --pkg-end
```
`build.zig`
```
const my_lib = @import("my_lib");
```
Although I wouldn't expect a user to plug this in every time, it would allow for a really generic way for the current package managers to instrument the zig compiler. It also makes build packages (ones that help us make weird things like kernel modules) a bit more natural.

The only thing that I'm not completely decided on yet (and definitely what I'd like to discuss here) is how to pass these packages to the build artifacts. I think it would be easiest to implicitly pass these down to all the build artifacts in the `build.zig` but maybe there's some behavior patterns I haven't considered.

**Comment by matu3ba** [comment]
What is the advantage to directly invoking the command for [zkg](https://github.com/mattnite/zkg#add) (
and have less to type ?

Would also be very inconvenient to have two ways doing the same thing.

**Comment by mattnite** [comment]
So right now the interaction between zkg and the zig compiler is similar to npm and node, it's nice because each has its own clear responsibilities. What I'd like to look at next is providing a cargo like experience to users since cargo is so successful. I will also note that the first thing people asked me when I created was "can I fetch packages and build in a single command?" so while having less to type might sound like a superfluous aim it's one that the users care about. Also see all the [other subcommands](https://doc.rust-lang.org/cargo/commands/index.html) that cargo has, they provide nice to have user tools that I just don't think fall under compiler responsibilities.

As for having two ways to do the same thing, the method of adding packages here is meant as another interface for other programs/scripts to take advantage of rather than humans (it would be rather monotonous to type out/go back in your history to build your dependency tree manually).

This all being said, I can do this in userspace pretty easily, I just wanted to have this in upstream so that others would be able to experiment in this space as well.

**Comment by matu3ba** [comment]
`rustc` has no build system (it is all in `cargo`) in contrast to `zig build`. `cargo` also invokes `rustc`. 
`cargo` has lots of nice features, but often has multiple ways to do the same things. That is already a problem to maintain.

Meta: Do you plan to define some sort of semantic versioning inside`git log` with a specialized annotation format?
Without trust issues/security problems, on would then not need centralized indexes like crates.io.

**Comment by mattnite** [comment]
I'm not sure what you mean by semantic versioning inside git log, are you assuming that I'd use git as a packaging medium?

**Comment by matu3ba** [comment]
For tracking master/latest stable version this would work, but discovering speed and reliability (rebase of history, repository moved, git logs were messed up, owner missing etc) would be a mess, when there is no index of the code.

**Comment by mattnite** [comment]
we're getting off course here so I think I'm having trouble communicating the value of this proposal, I'm just going to implement this in userspace myself and close this ticket.
