### ISSUE TITLE
Bug? `try` in `inline while` loop yields error

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#7278]
Heya,

this is probably a regression in Zig, as it worked at some point before. I have this code:
```zig
comptime var index = 0;
inline while (index < function_info.args.len) : (index += 1) {
    const T = function_info.args[index].arg_type.?;
    const value = args[index];
// ./src/library/runtime/environment.zig:315:43: error: control flow attempts to use compile-time variable at runtime
//                        v
    var converted_value = try convertToZigValue(T, value);
    zig_args[index] = converted_value;
}
```

This worked in the past and regressed somewhere in the last 2 months. I wonder if the behaviour is correct now or the variant before, but to me it looks like a over-eager analysis as returning from the function should be possible inside the unrolled loop

**Comment by Vexu** [comment]
Is this different friom #6726?

**Comment by MasterQ32** [comment]
Oh lol. Sorry, this is 100% a duplicate :laughing:
