### ISSUE TITLE
zig hangs in docker ubuntu 20.04

### ISSUE THREAD

**Issue by Avokadoen** [ziglang/zig#7288]
### main.zig
```zig
const std = @import("std");
const io = std.io;
const ArrayList = std.ArrayList;
const Allocator = std.mem.Allocator;

fn bytesToIntArrayList(allocator: *Allocator, bytes: []u8, length: usize) anyerror!ArrayList(u32) {
    var list = ArrayList(u32).init(allocator);
    try list.ensureCapacity(200);

    var i: usize = 0;
    var stride: usize = 0;
    while  (i < length) : (i += stride + 2) {
        var j: usize = 0;
        stride = 0;

        while (j < bytes.len and bytes[i + j] != '\n') : (j += 1) {
            stride = j;
        }
        
        if (std.fmt.parseInt(u32, bytes[i..i+stride], 10)) |value| {
            // TODO: handle this instead.
            try list.append(value);
        } else |err| {
            std.debug.warn("failed to parse int. error: {}, i: {}, stride: {}, slice content: {}", .{err, i, stride, bytes[i..i+stride]});
        }
    }

    return list;
}

pub fn main() anyerror!void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();

    const allocator = &arena.allocator;

    const in = std.io.getStdIn().inStream();
    const stdout = std.io.getStdOut().writer();

    var buf: [2000]u8 = undefined;

    const length = try in.readAll(&buf);

    var input = try bytesToIntArrayList(allocator, &buf, length);

    var part1: u32 = 0;
    var part2: u32 = 0;

    for (input.items) |leftSearchRoot, i| {
        var index = i + 1;
        while (index < input.items.len) : (index += 1) {
            var needle1 = input.items[index];
            if (leftSearchRoot + needle1 == 2020) {
                part1 = leftSearchRoot * needle1;
                break; // Assuming we can't have duplicates
            }

            var jndex = index + 1;
            while (jndex < input.items.len) : (jndex += 1) {
                var needle2 = input.items[jndex];
                if (leftSearchRoot + needle1 + needle2 == 2020) {
                    part2 = leftSearchRoot * needle1 * needle2;
                    break;
                }
            }
        }

        if (part1 > 0 and part2 > 0) {
            break;
        }
    }

    try stdout.print("{}\r\n", .{part1});
    try stdout.print("{}\r\n", .{part2});
}
```

### Dockerfile
```Dockerfile
FROM ubuntu:20.04
LABEL source=https://github.com/Arxcis/adventofcode2020

# 1. Configure TZ, so we don't get interactive prompt
ENV TZ=Europe/Oslo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# apt-get install all the things
RUN apt-get update && apt-get install -yqq\
  # build-essential includes make, gcc and g++
  build-essential\
  default-jdk\
  golang\
  nodejs\
  php-cli\
  polyml libpolyml-dev\
  python3\
  ruby\
  rustc\
  wget\
;

RUN wget https://ziglang.org/builds/zig-linux-x86_64-0.7.0+d4c167f3c.tar.xz\
  && tar xvf zig-linux-x86_64-0.7.0+d4c167f3c.tar.xz\
  && ln -s `pwd`/zig-linux-x86_64-0.7.0+d4c167f3c/zig /bin/zig\
  && chmod ugo+x /bin/zig\
 # test zig here
  && zig version\
  && mkdir test-zig && cd test-zig\
  && zig init-exe\
  && zig build run\
  && cd ./src && zig run main.zig -O ReleaseFast\ 
;
```

Everything work fine in the docker file. But as soon as i try to `cat $INPUT | zig run main.zig` (where '$INPUT' is a path to input data) or `zig build-exe main.zig` in the docker image, the compiler freezes. Not sure if this is a bug or user error (maybe my installation steps are wrong?). The image can successfully compile c, c++, rust, etc ...  

It's also worth mentioning:
- It works on my native ubuntu 20.04 laptop and windows 10 machine.
- Seems to work in 0.6 (Get compiler error from using 0.7 std)

**Comment by LemonBoy** [comment]
It's blocking because the program is waiting data from the stdin but you're not feeding it anything.

**Comment by Avokadoen** [comment]
I'm sorry, the example is wrong. I'll fix it asap. What i actually run is 
```bash
#    file path              # zig solution path                # expected output
cat $INPUT | zig run $SOLUTION -O ReleaseFast | diff - $OUTPUT
```

**Comment by LemonBoy** [comment]
I've tried running your code but got a few errors with a sample `input.txt` from Day0.
The use of `\r\n` made me guess you're working on Windows and the code is indeed working if I manually convert `input.txt` to use DOS line endings, your code isn't taking this difference into account.
Alas I suspect there's some logical error that's throwing your program into an infinite loop.

`bytesToIntArrayList` can be simplified with something like:
```zig
// bytes is a slice, no need to pass the length separately
fn bytesToIntArrayList(allocator: *Allocator, bytes: []u8) !ArrayList(u32) {
    var list = ArrayList(u32).initCapacity(allocator, 200);

    var it = mem.split(bytes, "\r\n");
    while  (it.next()) |line| {
       if (line.len == 0) continue; // empty line
       if (try std.fmt.parseInt(u32, line, 10)) |value| {
            try list.append(value);
        }
    }

   return list;
```

YMMV, I haven't compiled this.

**Comment by Avokadoen** [comment]
> YMMV, I haven't compiled this.

I'll test it! The code looks a lot more concise!

**Comment by LemonBoy** [comment]
> I'll test it! The code looks a lot more concise!

I've updated the snippet after testing it, now I can safely say it works :) 
Note that this works fine on Windows as `\r\n` are split twice, check out the docs on `mem.split` for more info.
A different solution would be to read the whole line and then strip the unwanted stuff:

```zig
fn bytesToIntArrayList(allocator: *Allocator, bytes: []u8) !ArrayList(u32) {
    var list = try ArrayList(u32).initCapacity(allocator, 200);

    var it = mem.split(bytes, "\n");
    while (it.next()) |raw_line| {
        const line = mem.trim(u8, raw_line, &std.ascii.spaces);
        if (line.len == 0) continue; // empty line
        const value = try std.fmt.parseInt(u32, line, 10);
        try list.append(value);
    }

    return list;
}
```

**Comment by Avokadoen** [comment]
Ok, so I tested this. The compiler still freezes when it attempts to compile the code. Running `zig build-exe main.zig` does not work either. No error and I can hear my laptop working, so it looks like a compiler error :(

**Comment by Avokadoen** [comment]
It works fine on any **native** ubuntu and windows.

**Comment by LemonBoy** [comment]
Ok, let's try and see where it hangs.
Try adding `strace` in front of `zig build-exe main.zig`, you probably have to install it in the container and/or follow [this](https://jvns.ca/blog/2020/04/29/why-strace-doesnt-work-in-docker/) small guide to make it work.
The output should tell why/where it's hanging.

**Comment by Avokadoen** [comment]
I'll continue investigating later today as i have to do some chores

**Comment by Avokadoen** [comment]
After doing some further debugging in the container it seems i were getting parsing errors in the container because of carriage return character in all versions except the last one you sent. The errors were not visible in the docker console for some reason in the CI. 

I will move on attempting with deploying. If it works I will close the issue!

**Comment by Avokadoen** [comment]
I'd also like to add that this is (possibly) related to a bug in the zig compiler as the likely cause was a raised error that caused the docker shell to freeze 🤔

**Comment by Avokadoen** [comment]
The problem turned out to be runtime errors that were not reported in the shell and froze the execution of the next steps in the CI-pipeline.

**Comment by Avokadoen** [comment]
Thanks @LemonBoy for all the help! 😄

**Comment by Avokadoen** [comment]
It's not a compiler bug at all. The miss behaviour was from the command i linked earlier: 
cat $INPUT | zig run $SOLUTION -O ReleaseFast | diff - $OUTPUT
