### ISSUE TITLE
Building in `io_mode = .evented` gives `error: function with calling convention 'C' cannot be async` on `handleSegfaultLinux()`

### ISSUE THREAD

**Issue by marnix** [ziglang/zig#7292]
Reproduction scenario: Build https://github.com/marnix/zigmmverify/pull/30/commits/5f368ceb1726d5ff942f83d1bea05e75ba902521 with Zig 0.7.0+d4c167f3c.tar.xz (on Debian, inside WSL, but that probably doesn't matter).

(GitHub action failure: https://github.com/marnix/zigmmverify/pull/30/checks?check_run_id=1493959526.)

The error goes away if `pub const io_mode = .evented;` (at the top of src/main.zig) is removed.

Here is a copy of the resulting build error:
```
/opt/hostedtoolcache/zig/zig-linux-x86_64-0.7.0+d4c167f3c/x64/lib/zig/std/debug.zig:1752:1: error: function with calling convention 'C' cannot be async
fn handleSegfaultLinux(sig: i32, info: *const os.siginfo_t, ctx_ptr: ?*const c_void) callconv(.C) noreturn {
^
/opt/hostedtoolcache/zig/zig-linux-x86_64-0.7.0+d4c167f3c/x64/lib/zig/std/debug.zig:1767:35: note: async function call here
        os.SIGSEGV => stderr.print("Segmentation fault at address 0x{x}\n", .{addr}),
                                  ^
/opt/hostedtoolcache/zig/zig-linux-x86_64-0.7.0+d4c167f3c/x64/lib/zig/std/io/writer.zig:33:34: note: async function call here
            return std.fmt.format(self, format, args);
                                 ^
/opt/hostedtoolcache/zig/zig-linux-x86_64-0.7.0+d4c167f3c/x64/lib/zig/std/fmt.zig:217:32: note: async function call here
            try writer.writeAll(fmt[start_index..end_index]);
                               ^
/opt/hostedtoolcache/zig/zig-linux-x86_64-0.7.0+d4c167f3c/x64/lib/zig/std/io/writer.zig:28:40: note: async function call here
                index += try self.write(bytes[index..]);
                                       ^
/opt/hostedtoolcache/zig/zig-linux-x86_64-0.7.0+d4c167f3c/x64/lib/zig/std/io/writer.zig:22:27: note: async function call here
            return writeFn(self.context, bytes);
                          ^
/opt/hostedtoolcache/zig/zig-linux-x86_64-0.7.0+d4c167f3c/x64/lib/zig/std/fs/file.zig:555:51: note: async function call here
            return std.event.Loop.instance.?.write(self.handle, bytes, self.capable_io_mode != self.intended_io_mode);
                                                  ^
/opt/hostedtoolcache/zig/zig-linux-x86_64-0.7.0+d4c167f3c/x64/lib/zig/std/event/loop.zig:1134:57: note: @frame() causes function to be async
                    .finish = .{ .TickNode = .{ .data = @frame() } },
```

This (or rather, the older still-using-SegmentedList version https://github.com/marnix/zigmmverify/commit/8f459870ed7c0d9b4eb434d4db3333927f531aa8) still built correctly with whatever-was-latest-zig-master-binaries-at-Mon, 30 Nov 2020 03:31:27 GMT.

**Comment by marnix** [comment]
Already fixed by https://github.com/ziglang/zig/pull/7269, perhaps?  (That commit has no explanation why it was made...)

Also, I don't have a small reproduction scenario, but if the PR fixed this, perhaps a test would need to be added that would have caught this?

Thanks!

/cc @LemonBoy, @MasterQ32

**Comment by LemonBoy** [comment]
> Already fixed by #7269, perhaps? (That commit has no explanation why it was made...)

Yes.

> perhaps a test would need to be added that would have caught this?

It's not that easy, the `io_mode = .evented` code paths are not tested at all.

**Comment by marnix** [comment]
Thanks @LemonBoy! I'll close this once new binaries are up on https://ziglang.org/download/ and I've verified this failure is gone from my build.

**Comment by andrewrk** [comment]
This is solved - feel free to comment otherwise and I'll re-open.

**Comment by marnix** [comment]
For the record: My build now succeeded, using zig-0.7.0+58241364c that is currently on the Releases page.  Thanks all!
