### ISSUE TITLE
add a way to embed a folder

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#7319]
this is proposed as a sibling to `@embedFile` but for a folder of assets given that comptime code does not have disk access, it would not be possible to recreate this in user code in a loop.

the return type of `@embedDir` would most likely be a `std.fs.Dir`.

however it would be nice to be able to add multiple folders to the same embed object. so alternatively you could have something like
```zig
const assets = comptime blk: {
	const store = @createEmbedStore();
	store.addDir("./www");
	store.addDir("./assets");
	break :blk store;
};
```

**Comment by ifreund** [comment]
This can already be implemented in usermode through code generation in a build.zig. I'm not convinced that there is enough of a use case to require first-class language support.

If this were to be accepted, having an `std.fs.Dir` as the return type would make no sense in my opinion. The API it provides is for interfacing with a mutable system filesystem where various errors may occur while what `@embedFile()` and, if accepted, `@embedDir()` provide is immutable data embedded in the binary to which access cannot fail.

**Comment by nektro** [comment]
> `@embedDir()` provide is immutable data embedded in the binary to which access cannot fail

yes the data would be read-only, but access could fail if the path you try to read from does not exist in the store.

**Comment by ifreund** [comment]
> yes the data would be read-only, but access could fail if the path you try to read from does not exist in the store.

Accessing a path that does not exist should be a compile error.  Regardless I don't think this proposed feature would pull it's weight. What is your use case for this that cannot be solved by multiple @embedFile() calls or code generation in your build.zig?

**Comment by nektro** [comment]
> Accessing a path that does not exist should be a compile error.

this can not be the case because I want to be able to read from paths based on runtime values.

> What is your use case for this

making a web server app and embedding the static assets into the binary. (html/css/etc)

> or code generation in your `build.zig`

I'm not familiar with that, do you have a docs link and/or example with more info on this?

**Comment by ifreund** [comment]
> I'm not familiar with that, do you have a docs link and/or example with more info on this?

[zig-wayland](https://github.com/ifreund/zig-wayland) would be one example. The `build_options` functionality of `std.build` would be another. The idea is simple though: just ouptut zig code using code run in your build.zig and add that generated code to the compilation.

**Comment by lonjil** [comment]
> making a web server app and embedding the static assets into the binary

then you don't want an std.fs.Dir. You'd need something that returns an array of structs containing the name of each file and a pointer to each file's data. Idk if that's a good idea, so if `@embedDir` was anything, it would probably be that. alternatively it would only embed the file names.

**Comment by raulgrell** [comment]
One way to leverage `@embedFile` would be to turn your directory into a tarball as part of your build process. It would also seem reasonable to have `@embedDir` do that for you and return an array of structs as suggested by @lonjil. Something like gnu tar's headers if you want to embed the file's metadata. https://github.com/tetsuo-cpp/mortar/ has an impl:

```
pub const TarHeader = packed struct {
    file_name: [100]u8,
    file_mode: [8]u8,
    user_id: [8]u8,
    group_id: [8]u8,
    file_size_bytes: [12]u8,
    modify_time: [12]u8,
    checksum: [8]u8,
    link: [1]u8,
    link_name: [100]u8,
    magic: [6]u8,
    version: [2]u8,
    user_name: [32]u8,
    group_name: [32]u8,
    device_major: [8]u8,
    device_minor: [8]u8,
    file_prefix: [155]u8,
    padding: [12]u8,
};
```

This does seem like something that could be implemented in userland in the stdlib.
