### ISSUE TITLE
amend the definition of @enumToInt to assert that the value is a valid tag

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#7320]
Here are the 2 competing definitions:

1. `@enumToInt` always produces an integer, however if the enum tag value is undefined, then the resulting integer is also undefined. (value, not behavior)

2. `@enumToInt` asserts the enum tag has a defined value.

Status quo is (1). Note that the reverse operation, `@intToEnum` does in fact assert that the integer matches a valid enum tag.

**Comment by xackus** [comment]
Perhaps the check should be behind a compiler flag if there is enough interest in it.
I can imagine it could be useful when debugging code that is doing some unsafe memory manipulation.
This could be extended to other invalid values achievable only through things like `@ptrCast`.

**Comment by andrewrk** [comment]
This isn't something we can put behind a compiler flag because it changes the semantics of the language.

I'm pretty sure status quo is going to stay.

**Comment by daurnimator** [comment]
> `@intToEnum` does in fact assert that the integer matches a valid enum tag.

FWIW this is troublesome when it comes to non-exhaustive enums. See e.g.
https://github.com/ziglang/zig/blob/6294c1136cb44285156c04f9f89f62b0f9e8e471/lib/std/fmt.zig#L419-L437

**Comment by xackus** [comment]
> This isn't something we can put behind a compiler flag because it changes the semantics of the language.

Oh, that's right, I forgot it's not illegal unless you branch on it.

**Comment by LemonBoy** [comment]
> FWIW this is troublesome when it comes to non-exhaustive enums. See e.g.

That's sounds a bug to me, non-exhaustive enums by definition accept every value (as long as it fits into the underlying integral type).

**Comment by daurnimator** [comment]
> That's sounds a bug to me, non-exhaustive enums by definition accept every value (as long as it fits into the underlying integral type).

nevermind me; I was getting confused with `@tagName`

**Comment by LemonBoy** [comment]
> > That's sounds a bug to me, non-exhaustive enums by definition accept every value (as long as it fits into the underlying integral type).
> 
> nevermind me; I was getting confused with `@tagName`

Yeah, that's annoying. Perhaps `@tagName` can return an empty string instead of failing hard.
Turning the result into an optional type when the enum is not exhaustive is not that nice (is it?)

**Comment by zigazeljko** [comment]
> Turning the result into an optional type when the enum is not exhaustive is not that nice (is it?)

Why? You can do `@tagName(value) orelse ""` if you want an empty string.

**Comment by LemonBoy** [comment]
> Why?

Because the return type of `@tagName(x)` would be `?[]const u8` if `x` is non-exhaustive and `[]const u8` otherwise?
That's a PITA to handle in some generic code.

**Comment by zigazeljko** [comment]
Oh, right.

Another solution might be to introduce a new builtin (something like `@tagNameOrNull`), which returns `?[]const u8` for both exhaustive and non-exhaustive enums.

**Comment by zigazeljko** [comment]
How about adding an optional parameter to `@tagName` (instead of a new builtin) and changing the semantics as following:

- `@tagName(value)` - Causes a compile error if `@TypeOf(value)` is a non-exhaustive enum. Otherwise, behaves the same as before (i.e. result is `[]const u8`).
- `@tagName(value, default)` where default is a `[]const u8` - Returns `default` if the tag value is not known, result type is `[]const u8`.
- `@tagName(value, null)` - Returns `null` if the tag value is not known, result type is `?[]const u8` (for both exhaustive and non-exhaustive enums).

**Comment by daurnimator** [comment]
> `@tagName(value, default)` where default is a `[]const u8` - Returns `default` if the tag value is not known, result type is `[]const u8`.

This would encourage a pattern where `default` is calculated even when not used. it's better to return an optional so that the backup path is lazily computed.

**Comment by zigazeljko** [comment]
> This would encourage a pattern where `default` is calculated even when not used.

We can require that `default` is comptime known. For optionals, you would still have the `@tagName(value, null)` syntax.

**Comment by andrewrk** [comment]
Regarding `@enumToInt`, status quo stays. Feel free to open a separate proposal for `@tagName`.

**Comment by andrewrk** [comment]
> Regarding `@enumToInt`, status quo stays. Feel free to open a separate proposal for `@tagName`.

#12845
