### ISSUE TITLE
OpenGL or SDL example

### ISSUE THREAD

**Issue by clankill3r** [ziglang/zig#7328]
Is there or can someone provide an example with OpenGL or SDL or something else for drawing graphics?
I would like to get a kickstart with zig instead of a start from standing still one the ground.

Hope someone can help.

**Comment by MasterQ32** [comment]
You should join one of the communities listed here:
https://github.com/ziglang/zig/wiki/Community

I don't think this is a topic that should be discussed on GitHub itself, but i will help out in both IRC (ikskuh/mq32) or Discord (xq)

**Comment by clankill3r** [comment]
Thanks! Closing it.
