### ISSUE TITLE
Memory corruption when passing slices of structs

### ISSUE THREAD

**Issue by jpe90** [ziglang/zig#7338]
I was getting unexpected behavior while doing an advent of code exercise, so I boiled down my code to try to isolate the issue. I've tried this code in both 0.7.0 and master on Linux x86_64, and on 0.7.0 on Windows, and the issue exists on each.

In a nutshell, here's what seems to be happening:

1. I create an array of structs, coerce it to a slice, and pass the slice to a method
2. Inside the method which receives the slice of structs, the struct members hold invalid data.

```
const std = @import("std");
const Delta = struct {
    dx: u32,
    dy: u32,
};

fn getSlopes() []const Delta {
    var slopes: [5]Delta = undefined;
    slopes[0] = Delta{ .dx = 1, .dy = 1 };
    slopes[1] = Delta{ .dx = 3, .dy = 1 };
    slopes[2] = Delta{ .dx = 5, .dy = 1 };
    slopes[3] = Delta{ .dx = 7, .dy = 1 };
    slopes[4] = Delta{ .dx = 1, .dy = 2 };
    for (slopes) |slope| {
        std.debug.print("in getSlopes dx is {} and dy is {}\n", .{ slope.dx, slope.dy });
    }
    return slopes[0..];
}

fn sumCounts(slopes: []const Delta) void {
    var count: u32 = 0;
    for (slopes) |slope| {
        std.debug.print("in sumCounts dx is {} and dy is {}\n", .{ slope.dx, slope.dy });
    }
}
pub fn main() anyerror!void {
    const slopes = getSlopes();
    for (slopes) |slope| {
        std.debug.print("in main dx is {} and dy is {}\n", .{ slope.dx, slope.dy });
    }
    sumCounts(slopes);
}

```

Output:
```
in getSlopes dx is 1 and dy is 1
in getSlopes dx is 3 and dy is 1
in getSlopes dx is 5 and dy is 1
in getSlopes dx is 7 and dy is 1
in getSlopes dx is 1 and dy is 2
in main dx is 1 and dy is 1
in main dx is 3 and dy is 1
in main dx is 5 and dy is 1
in main dx is 7 and dy is 1
in main dx is 1 and dy is 2
in sumCounts dx is 1 and dy is 1
in sumCounts dx is 2457663920 and dy is 32767
in sumCounts dx is 2309084 and dy is 0
in sumCounts dx is 7 and dy is 1
in sumCounts dx is 4 and dy is 0
```

**Comment by LemonBoy** [comment]
`getSlopes` is returning a slice of a stack-allocated array, once `getSlopes` returns `slopes` is lost.

**Comment by zigazeljko** [comment]
From [documentation](https://ziglang.org/documentation/master/#Where-are-the-bytes):

> `var` declarations inside functions are stored in the function's stack frame. Once a function returns, any Pointers to variables in the function's stack frame become invalid references, and dereferencing them becomes unchecked Undefined Behavior.

**Comment by jpe90** [comment]
Thanks guys, sorry for the mistake.
