### ISSUE TITLE
Mainline DEB's, RPM's for zig!

### ISSUE THREAD

**Issue by mcandre** [ziglang/zig#7340]
Can the third party OS repositories like Debian/Ubuntu be rolled into the main repos?

Third party repositories are okay for some use cases, I've just had varying degrees of success with these in past projects.

For example, even an Ubuntu PPA would be helpful to automate more of the process of managing repository configurations.

**Comment by andrewrk** [comment]
Welcome, @mcandre.

This is out of scope for this github repository. Typically you will file an upstream issue on Debian or Fedora/RedHat if you want such things. I personally will not be taking on this project, and as far as I am aware no one in the community has started such a project.

**Comment by Jan200101** [comment]
to keep track of this
an upstream issue for Fedora has been opened https://bugzilla.redhat.com/show_bug.cgi?id=1912706

**Comment by compscidr** [comment]
Added a ticket in debian for mainline apt support: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=995670

In meantime I made a repo which generates apt packages and puts them on gemfury (there was previously a different 3rd party effort for this but it appears to no longer be functioning: https://github.com/compscidr/zig-deb)

If there is interest, I can make a PR to integrate the apt packaging directly into github actions on directly on this repo
