### ISSUE TITLE
ETA on v1.0 release?

### ISSUE THREAD

**Issue by mcandre** [ziglang/zig#7341]
Hi!

I'm excited to use Zig as a drop-in replacement for complicated C/C++ cross compiler setups. But I fear that the current, pre-v1.0 state means I would have to run back to my old projects every few months and fix the `zig` CLI flags to rescue my builds.

When can we expect a long term support release with guarantees of backwards compatibility?

**Comment by andrewrk** [comment]
There are already 1448 issues open - let's keep them focused on the source tree of this project.

[Here are some places to ask this question](https://github.com/ziglang/zig/wiki/Community)
