### ISSUE TITLE
version manager?

### ISSUE THREAD

**Issue by mcandre** [ziglang/zig#7344]
Anyone got a working version manager for hot swapping Zig compiler versions on a per-project basis, given `.zig-version` files noting the desired Zig version?

Similar to gvm, rvm + chruby, node-build+ nodenv, jenv, etc.

**Comment by MasterQ32** [comment]
I don't think that's necessary. You don't swap your c compiler version on a daily basis either.
Zig is meant to be a super-stable language from 1.0 on, so no need to swap anything here as everything is meant to behave exactly the same.
And providing means to switch to old, deprecated compiler versions is not really a good idea either, as most stuff is out-of-date in a week usually and keeping the code up to `master` is a good thing.

**Comment by andrewrk** [comment]
There are already 1448 issues open - let's keep them focused on the source tree of this project.

[Here are some places to ask this question](https://github.com/ziglang/zig/wiki/Community)
