### ISSUE TITLE
Update Debian packages

### ISSUE THREAD

**Issue by mcandre** [ziglang/zig#7345]
When I try to follow the Hello World example, it fails to compile with the old Zig version 0.6.0 that is published in the Debian bintray repo. Can we please update this to v0.7.0, so that the official Zig documentation has a better out of the box experience?

For now, I will look into Zig version managers, or failing that, a classic Linux tarball.

**Comment by dbandstra** [comment]
Official documentation for all Zig releases, including 0.6.0, are available at https://ziglang.org/download/.

**Comment by andrewrk** [comment]
I don't think we need to track this issue in this repository. Debian will update zig on their schedule. It's not really our concern.
