### ISSUE TITLE
Official DockerHub images for zig

### ISSUE THREAD

**Issue by mcandre** [ziglang/zig#7348]
Hey, I see a handful of different "zig" images on DockerHub, including some that can build zig itself. But I don't see an official image that has the `zig` compiler installed and ready for use. Can we release official images for this?

That way, developers and CI maintainers can rely on a more stable, community tested development environment for easily building Zig programs. As opposed to having to install Zig from scratch each time.

https://hub.docker.com/

**Comment by andrewrk** [comment]
No need for docker, all the linux tarballs we provide are statically compiled. They work inside a `FROM scratch` image.

**Comment by mcandre** [comment]
Yes, at a philosphical level there is no need for a Docker image. Rather, as a practical matter is is very helpful to have a container handy, for newbies and CI managers so they don't have to work with tarballs themselves.

Example:

https://hub.docker.com/r/mcandre/docker-zig

**Comment by AddisonRogers** [comment]
please

**Comment by sin-ack** [comment]
I'm in support of an official Zig Docker image. The main benefit of doing this is that it reduces the amount of friction needed for including the Zig compiler as part of a Dockerfile, especially if you're working with an existing project. Right now you need to do something like this manually to get something like the scratch image you described:

```
FROM debian:latest AS downloader
WORKDIR /

# Have to maintain this URL. Let's hope the URL scheme doesn't change
RUN wget https://ziglang.org/builds/zig-linux-x86_64-0.11.0.tar.xz -O zig.tar.xz && \
    tar xvf zig.tar.xz --strip-components=1 -C zig

FROM scratch AS zig
WORKDIR /
COPY --from=downloader /zig zig

ENV PATH=/zig
WORKDIR /build
```

Then you either have to push this manually to your own private registry or include this snippet in every `Dockerfile` you need to build.

Being able to just do `FROM zig:0.11.0` would help adoption in projects looking to switch over from other programming languages and would ease the burden of developers already using Docker, in my opinion. To facilitate this, a repository which periodically scrapes `https://ziglang.org/downloads/index.json` and pushes new versions (using something similar to the snippet) above would be great.
