### ISSUE TITLE
Scroll position not saved in language reference docs when using browser navigation

### ISSUE THREAD

**Issue by garyemerson** [ziglang/zig#7349]
**Issue:**
The scroll position of the [language reference](https://ziglang.org/documentation/0.7.0/) is not saved when using browser navigation. This includes navigation between external sites and within the same page using the URI fragment links (e.g. https://ziglang.org/documentation/0.7.0/#Values).

**How to reproduce:**
1. Using Chrome or Safari on desktop, open docs at: https://ziglang.org/documentation/0.7.0/
2. Scroll somewhere in document
3. Click fragment link, or manually navigate to different site using url bar.
4. Use back button
5. Observe page will not be at previous scroll position (either back to top for external site or won't change at all for a fragment link)

**Details:**
- I've verified this occurs in both Safari and Chrome. Doesn't happen on Firefox, it saves the position fine. Tested on my mac (version 11.0.1, Big Sur).
- I believe the css `display: flex;` on the `main-wrapper` div element (introduced in [PR 3514](https://github.com/ziglang/zig/pull/3514)) is the culprit here. If you remove that using devtools then the saved scroll position works again.
- You can also observe the difference by comparing the pages https://ziglang.org/documentation/0.5.0/ and https://ziglang.org/documentation/0.6.0/

**Comment by dbandstra** [comment]
It happens in Firefox too, for me. I think this is an unavoidable consequence of having an inner div scroll instead of the body? 

I think one way to fix it would be to ditch flex, make the sidebar `position: fixed` with an explicit width and `overflow-y: auto`

**Comment by Vexu** [comment]
Related  #3506

**Comment by paulespinosa** [comment]
@garyemerson, @dbandstra can you check again. I haven't been able to reproduce after 0.8.0. 
https://ziglang.org/documentation/0.8.0/
https://ziglang.org/documentation/master

**Comment by dbandstra** [comment]
Yeah it seems to have been fixed by https://github.com/ziglang/zig/pull/8478
