### ISSUE TITLE
Enhancement: clean subtask for zig build

### ISSUE THREAD

**Issue by mcandre** [ziglang/zig#7353]
Could the zig build tool get a `clean` subtask to ensure the zig-cache directory is not present? This helps to save disk space when developing dozens of projects.

**Comment by ifreund** [comment]
you can add a clean step to your build.zig if you like. I don't think this is a worthwhile feature to support in the standard library though as `rm -r zig-cache` works just as well and is much simpler. It also has 0 maintenance burden.

**Comment by andrewrk** [comment]
If you look at the `zig build --help` menu, you will see an option called `uninstall`:

```
  uninstall                   Remove build artifacts from prefix path
```

This feature already exists. zig-cache maintenance is a different issue which is already covered by other issues.
