### ISSUE TITLE
Debugging zig in VSCode

### ISSUE THREAD

**Issue by clankill3r** [ziglang/zig#7361]
I found this post from more then a year ago:

https://www.reddit.com/r/Zig/comments/cl0x6k/debugging_zig_in_vscode/

First off, it's a bit outdated, for example:

> Edit `~/.vscode/extensions/webfreak.debug-0.23.1/package.json`. (<- this is the path for Linux, you'll need to find the corresponding path for other OSs). In the file there's a list of supported languages (here, it's pretty obvious when you edit the file.). Add a newline with 'zig' there.

Is not needed anymore, cause 'zig' is already in tat file now (nice!).

But the thing is, I can't get the debugger to work.

My task.json looks like this:

```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "zig build-exe main.zig"
        }
    ]
}
```

And my launch.json looks like this:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "gdb",
            "request": "launch",
            "target": "main",
            "cwd": "${workspaceRoot}",
            "valuesFormatting": "parseText",
            "preLaunchTask": "build"
        }
    ]
}
```

I was hoping if someone can help me. Preferred with using ZLS as well (https://github.com/zigtools/zls).

If I manage to get it working I will make a video of how to set it up.

**Comment by clankill3r** [comment]
I also founded this one:
https://dev.to/watzon/debugging-zig-with-vs-code-44ca

But no luck either. I don't have the "C++ (GDB/LLDB)" option he is talking about but I do have the GDB option.

Hope someone can help.

**Comment by raulgrell** [comment]
![image](https://user-images.githubusercontent.com/179686/101641771-11680800-3a2a-11eb-8706-ec84aebac563.png)

This is what I can get for debugging Zig. Locals mostly work, watch mostly doesn't and the inline info is usually alright.
I used to get a lot of "this variable has been optimized out" issues after the return location semantics came along, but that issue seems to be fixed.

This is my launch.json:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Attach",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command:pickProcess}"
        },
        {
            "name": "Launch Script",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/zig-cache/bin/zox.exe",
            "args": ["./lib/script.zox"],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false
        },
        {
            "name": "Launch Command",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/zig-cache/bin/zox.exe",
            "args": ["run", "print \"Hello, world!\""],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false
        }
    ]
}
```

**Comment by raulgrell** [comment]
I think this is the extension that provides it:
![image](https://user-images.githubusercontent.com/179686/101642707-34df8280-3a2b-11eb-97fd-78024e8597f7.png)

**Comment by clankill3r** [comment]
I keep a log here off all the thins I do to try to make this work.
As of now I have installed the C/C++ extension as mentioned in the post above.

I made a new launch.json that looks like this now:

```json

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/main",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            // "MIMode": "lldb"
        }
    ]
}
```

When I try to debug now, I get:

![Screenshot 2020-12-16 at 14 14 53](https://user-images.githubusercontent.com/738650/102353846-f0fbf880-3fa9-11eb-8a4f-f2332e28f4c3.png)

and:

![Screenshot 2020-12-16 at 14 15 00](https://user-images.githubusercontent.com/738650/102353860-f78a7000-3fa9-11eb-94d6-7f87f53cb483.png)

Which I will attempt to fix now, which I will post below.

**Comment by clankill3r** [comment]
Ok, quick update, I need to reboot before I can continue, but I'm in the middle of copying files which takes another 7 hours so I will edit this post later on.

**Comment by clankill3r** [comment]
Ok, I got it working!
First I had `//"MIMode": "lldb"` in my launch.json, which I changed too `"MIMode": "lldb"` and now it works.

So this is how my launch.json looks like (I also added a preLaunchTask):

```json
    "version": "0.2.0",
    "configurations": [        
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/main",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "preLaunchTask": "build"
        }
    ]
}
```

![Screenshot 2020-12-18 at 20 25 41](https://user-images.githubusercontent.com/738650/102653448-3b7aa200-416f-11eb-9dd8-b14950ea17ae.png)

I hope this helps someone

**Comment by CreatorMetaSky** [comment]
[zig-debug-test](https://github.com/LearnLangSpace/zig-debug-test)

**this template can help you debug zig with vscode on macos**， 😀
