### ISSUE TITLE
Functions should default to returning void if the return type is omitted

### ISSUE THREAD

**Issue by zesterer** [ziglang/zig#737]
The fact that the function is not intended to return anything is immediately obvious to both the programmer and anybody reading the code. Omitting the return type is a nice shortcut that doesn't increase the complexity of the language and doesn't require huge changes to the compiler internals. It has the advantage of improving code readability by getting rid of things the developer needs to read that do not aid in understanding the semantic meaning of the code.

Example return-less (distinct from `noreturn`, of course) function definition:

```
fn outputSomething(file: std.File) {
    file.write("Something") catch {};
}
```

As an optional consideration, perhaps it may be possible to omit the call brackets for functions with no arguments too? I'm unsure whether this creates parser ambiguities, however. Example:

```
fn doPanic {
    @panic("This is a panic.");
}
```

**Comment by Hejsil** [comment]
Well, the optional void was just removed.
https://github.com/zig-lang/zig/pull/720

**Comment by wilsonk** [comment]
@andrewrk  Should this be closed since the optional return was removed...as per Hejsil above? Also, the grammar doesn't allow an optional return expr at this point.
