### ISSUE TITLE
"Expected type" error could be printed more clearly

### ISSUE THREAD

**Issue by Srekel** [ziglang/zig#7385]
This error is pretty hard to read:
![image](https://user-images.githubusercontent.com/1578924/101827164-3e064780-3b30-11eb-8ee2-52cd308a86da.png)

Manually aligned it's trivial:
![image](https://user-images.githubusercontent.com/1578924/101827142-3777d000-3b30-11eb-9d96-b70c531cfcf1.png)

Could the error message have new lines? Do we have the technology for this? :D (Kidding, but really, it would be nice, but I'm guessing it's perhaps done this way for some compatibility reason?)

It could also spit out exactly which argument it failed on, and the two different types. And/or, if the number of arguments was a mismatch, print that first.

**Comment by LemonBoy** [comment]
The compiler does print what parameter is wrong and why, at least for me:

```
/tmp/foo1.zig:9:11: error: expected type 'fn([*c]const u16) void', found 'fn([*c]const u8) void'
    y.p = x;
          ^
/tmp/foo1.zig:9:11: note: parameter 0: '[*c]const u8' cannot cast into '[*c]const u16'
    y.p = x;
          ^
```

**Comment by Srekel** [comment]
Huh... I believe I am on a fairly recent Zig build, but I can try updating tonight. 

Is it possible it's because it's a C function (defined in a cImported header)?

**Comment by tau-dev** [comment]
Can you still reproduce this?

**Comment by Srekel** [comment]
Yes, I now see what I meant. Here is a similar setup:
```js
const lol1 = *const fn (a: i32) void;

fn lol3(_: u64) void {}

pub fn main() void {
    var hello: ?lol1 = null;
    hello = lol3;
}

```
Current error:
```js
src\main.zig:7:13: error: expected type '*const fn (i32) void', found '*const fn (u64) void'
    hello = lol3;
            ^~~~
```
My suggestion:

```js
src\main.zig:7:13: error: expected type '*const fn (i32) void', 
                                  found '*const fn (u64) void'
    hello = lol3;
            ^~~~
```

Aligning up the types like this makes it easier to see where the discrepancy is.

Granted, I'm not sure how it plays with UIs like this:
![image](https://github.com/ziglang/zig/assets/1578924/b1010882-4d25-417a-b928-8e2ade96ac74)

**Comment by tau-dev** [comment]
Thanks! Does it still fail to show the
```
src/main.zig:7:13: note: pointer type child 'fn (u64) void' cannot cast into pointer type child 'fn (i32) void'
src/main.zig:7:13: note: parameter 0 'u64' cannot cast into 'i32'
src/main.zig:7:13: note: unsigned 64-bit int cannot represent all possible signed 32-bit values
```
afterwards? If that part is working, the part about readability of the type juxtaposition sounds like it's covered by #12401.

**Comment by Srekel** [comment]
Oh you're right! I totally missed that. That's super helpful and enough for me to close this.
