### ISSUE TITLE
allow inferred error sets in recursive functions.

### ISSUE THREAD

**Issue by lolbinarycat** [ziglang/zig#7389]
```
error: cannot resolve inferred error set '@typeInfo(@typeInfo(@TypeOf(LDF.show)).Fn.return_type.?).ErrorUnion.error_set': function 'LDF.show' not fully analyzed yet
```
I ran into this problem writing a function to print a tree-like structure. The thing is, calling a function from itself will never add any errors to the error set, almost by definition. So I propose that we just ignore recursive calls during error set analysis. This only applies to direct recursion, and not mutually recursive functions or anything else.

**Comment by EleanorNB** [comment]
This definitely applies to mutual recursion, if you `try` every intermediate layer. It's not even particularly expensive: we have to check for mutual recursion anyway, for stack/frame size precomputation. I say this is a great idea.

**Comment by lolbinarycat** [comment]
> we have to check for mutual recursion anyway, for stack/frame size precomputation. I say this is a great idea.
Ah, ok. I was just thinking that testing for mutual recursion is a bit more complicated that testing for direct recursion, which is fairly trivial. But if we're doing it anyway, I guess that doesn't apply.

**Comment by Vexu** [comment]
Duplicate of #2971.
