### ISSUE TITLE
ArrayHashMap: support all operations that ArrayList support

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#7391]
This proposal is to treat ArrayHashMap as a data structure that can act both as an ArrayList and as a HashMap.

Here are some improvements I want to see:

 * `getOrPut` related functions should additionally return the entry index.
 * `remove` should be changed to `swapRemove`, and `orderedRemove` should be introduced. Both of these operations are present in ArrayList and match what will be happening to the Hash Map's inner ArrayList.
 * You should be able to directly modify the `entries` field which is an `ArrayList`. This causes all the methods which rely on the index data to become illegal to call, until you call `reIndex()` which then makes everything work again.
 * Introduce `fromOwnedArrayList` which takes ownership of an ArrayList as the entries field and calls `reIndex()`
 * Introduce `shrinkRetainingCapacity` which does the same thing as in ArrayList but maintains the hash map index.
 * Introduce `shrinkAndFree` which maps to ArrayList.shrink (and we should rename ArrayList.shrink to shrinkAndFree as well)
 * Introduce `pop`.

This use case comes from updating the `Cache` API `files` field to be an ArrayHashMap instead of an ArrayList:

https://github.com/ziglang/zig/blob/f7d600675c548b4e45b24f8e10ebdd892a6b8dba/src/Cache.zig#L178

**Comment by daurnimator** [comment]
This sounds a lot like the http_headers data structure that we had. https://github.com/ziglang/std-lib-orphanage/blob/2c36a7894c689ecbaf63d5f489bb0c68773410c4/std/http_headers.zig#L9-L17

**Comment by tetsuo-cpp** [comment]
I'm going to give this a try.
