### ISSUE TITLE
lld: error: could not open 'wldap32.lib': No such file or directory

### ISSUE THREAD

**Issue by SpexGuy** [ziglang/zig#7395]
Most of the windows DLLs can be loaded from zig, but for some reason I can't load wldap32.lib.  It seems like Zig is generating .lib files in the global zig-cache and linking with those, but it doesn't create this one for some reason.  Tested with both the native target and the mingw64 (gnu) target.

```zig
// repro.zig
const PCWSTR = [*:0]const u16;
const LDAP = opaque{};
const ULONG = u64;
extern "wldap32" fn ldap_openW(HostName: PCWSTR, PortNumber: ULONG) callconv(.Stdcall) *LDAP;
pub fn main() !void {
    _ = ldap_openW(undefined, undefined);
}
```
```batch
> zig version
0.7.0

> zig build-exe repro.zig    
lld: error: could not open 'wldap32.lib': No such file or directory     
error: LLDReportedFailure

> zig build-exe src/repro.zig -target native-native-gnu
lld: error: could not open 'wldap32.lib': No such file or directory     
error: LLDReportedFailure
```

**Comment by andrewrk** [comment]
We have an explicit list of .def files we ship from mingw-w64. We could blanket include all of them but that would increase the install size by something like 6 MiB (656 KB in the tarball). Maybe that's not so bad though :thinking: 

Anyway the short term solution is easy, which is additionally shipping wldap32.def, and is no problem to add. Are there any more libs besides this one to add?

**Comment by SpexGuy** [comment]
Thanks, makes sense!  I think that was the last library I needed (for linking curl), but I also had to add `gai_strerrorW` to `ws2_32.def.in`.  Not sure why that was missing but it might be related to this issue: https://github.com/gvanem/wsock-trace/issues/10

Now I'm seeing a bunch of link errors for symbols that I think should be in the mingw posix emulation layer.  Things like `strdup`, `read`, `unlink`, `__mingw_vfprintf`, etc.  I'm linking libc, but do I need to add a separate library for mingw posix libc?  I am using `native-native-gnu` as the target.

**Comment by andrewrk** [comment]
> do I need to add a separate library for mingw posix libc?

Nope, just `-target native-native-gnu -lc` should do it. So that's worth an issue I think. I'm confused why those symbols would be missing, mingw-w64 definitely provides them.

Can you try to reduce the problem to a small test case? I tried this:

```zig
extern fn read() void;
pub fn main() void {
    read();
}
```

```
zig build-exe test.zig -target x86_64-windows-gnu -lc
```

And it produced a viable test.exe.

**Comment by SpexGuy** [comment]
> Can you try to reduce the problem to a small test case?

Will do, I'll make a new issue for that.

> but that would increase the install size by something like 6 MiB (656 KB in the tarball)

Since it compresses well, one option would be to store it compressed in the install and decompress it into the global zig-cache on first use.
