### ISSUE TITLE
zig [command] --help should work outside of zig source code

### ISSUE THREAD

**Issue by dch** [ziglang/zig#7397]
It's unintuitive for zig to require & compile an entire project, just to see what the output of `zig build --help` is. Either a `zig help build` or `zig build --help` should be able to provide this, independent of being inside a zig project.

## zig-0.7.0+3599f9b

```
dch@wintermute /tmp> zig help build
Usage: zig [command] [options]

Commands:

  build            Build project from build.zig <---- this is what we want detailed help on
...
  -h, --help       Print command-specific usage
```

## lets try that then

```
dch@wintermute /tmp> zig build --help
info: Initialize a 'build.zig' template file with `zig init-lib` or `zig init-exe`,
or see `zig --help` for more options.
error: No 'build.zig' file found, in the current directory or any parent directories.
``
```

## huh maybe this?

```
dch@wintermute /tmp> zig help build
Usage: zig [command] [options]

Commands:

  build            Build project from build.zig
...
```

## great success

```
dch@wintermute /p/c/zdns> zig build --help
Usage: /usr/local/bin/zig build [steps] [options]

Steps:
  install (default)           Copy build artifacts to prefix path
  uninstall                   Remove build artifacts from prefix path
  run                         Run the app
  test                        Run tests
  compare-output              Test - Compare output

General Options:
  -h, --help                  Print this help and exit
  --verbose                   Print commands before executing them
  --prefix [path]             Override default install prefix
  --search-prefix [path]      Add a path to look for binaries, libraries, headers
  --color [auto|off|on]       Enable or disable colored error messages

Project-Specific Options:
  -Dtarget=[string]           The CPU architecture, OS, and ABI to build for
  -Drelease-safe=[bool]       Optimizations on and safety on
  -Drelease-fast=[bool]       Optimizations on and safety off
  -Drelease-small=[bool]      Size optimizations on and safety off

Advanced Options:
  --build-file [file]         Override path to build.zig
  --cache-dir [path]          Override path to zig cache directory
  --override-lib-dir [arg]    Override path to Zig lib directory
  --verbose-tokenize          Enable compiler debug output for tokenization
  --verbose-ast               Enable compiler debug output for parsing into an AST
  --verbose-link              Enable compiler debug output for linking
  --verbose-ir                Enable compiler debug output for Zig IR
  --verbose-llvm-ir           Enable compiler debug output for LLVM IR
  --verbose-cimport           Enable compiler debug output for C imports
  --verbose-cc                Enable compiler debug output for C compilation
  --verbose-llvm-cpu-features Enable compiler debug output for LLVM CPU features
```

**Comment by g-w1** [comment]
This is because the help shows project specific, user defined steps. I think there should be a default help menu that shows when outside of a project.

**Comment by andrewrk** [comment]
That's correct, it's actually a feature of `zig build` that the `--help` menu interacts with the build script. `zig build` only makes sense to run inside a project directory, including the `--help` menu.

**Comment by Carpall** [comment]
> It's unintuitive for zig to require & compile an entire project, just to see what the output of `zig build --help` is. Either a `zig help build` or `zig build --help` should be able to provide this, independent of being inside a zig project.
> 
> ## zig-0.7.0+3599f9b
> ```
> dch@wintermute /tmp> zig help build
> Usage: zig [command] [options]
> 
> Commands:
> 
>   build            Build project from build.zig <---- this is what we want detailed help on
> ...
>   -h, --help       Print command-specific usage
> ```
> 
> ## lets try that then
> ```
> dch@wintermute /tmp> zig build --help
> info: Initialize a 'build.zig' template file with `zig init-lib` or `zig init-exe`,
> or see `zig --help` for more options.
> error: No 'build.zig' file found, in the current directory or any parent directories.
> ``
> ```
> 
> ## huh maybe this?
> ```
> dch@wintermute /tmp> zig help build
> Usage: zig [command] [options]
> 
> Commands:
> 
>   build            Build project from build.zig
> ...
> ```
> 
> ## now from within a zig project?
> ## great success
> ```
> dch@wintermute /p/c/zdns> zig build --help
> Usage: /usr/local/bin/zig build [steps] [options]
> 
> Steps:
>   install (default)           Copy build artifacts to prefix path
>   uninstall                   Remove build artifacts from prefix path
>   run                         Run the app
>   test                        Run tests
>   compare-output              Test - Compare output
> 
> General Options:
>   -h, --help                  Print this help and exit
>   --verbose                   Print commands before executing them
>   --prefix [path]             Override default install prefix
>   --search-prefix [path]      Add a path to look for binaries, libraries, headers
>   --color [auto|off|on]       Enable or disable colored error messages
> 
> Project-Specific Options:
>   -Dtarget=[string]           The CPU architecture, OS, and ABI to build for
>   -Drelease-safe=[bool]       Optimizations on and safety on
>   -Drelease-fast=[bool]       Optimizations on and safety off
>   -Drelease-small=[bool]      Size optimizations on and safety off
> 
> Advanced Options:
>   --build-file [file]         Override path to build.zig
>   --cache-dir [path]          Override path to zig cache directory
>   --override-lib-dir [arg]    Override path to Zig lib directory
>   --verbose-tokenize          Enable compiler debug output for tokenization
>   --verbose-ast               Enable compiler debug output for parsing into an AST
>   --verbose-link              Enable compiler debug output for linking
>   --verbose-ir                Enable compiler debug output for Zig IR
>   --verbose-llvm-ir           Enable compiler debug output for LLVM IR
>   --verbose-cimport           Enable compiler debug output for C imports
>   --verbose-cc                Enable compiler debug output for C compilation
>   --verbose-llvm-cpu-features Enable compiler debug output for LLVM CPU features
> ```

wintermute?

**Comment by andrewrk** [comment]
Duplicate of  #15154
