### ISSUE TITLE
Proposal: Require whitespace on both sides of - or neither

### ISSUE THREAD

**Issue by SpexGuy** [ziglang/zig#7399]
This may be out of scope for the language, but it's in line with other accepted proposals like #35 and #114 which aim to avoid misinterpretation.
Here's an example of the problem this prevents:
```zig
const directions = [_]isize{
    -pitch-1,
    -pitch,
    -pitch+1
    -1,
    1,
    pitch-1,
    pitch,
    pitch+1,
};
```
See the bug?  It took me a minute.

<details>
  <summary>View Answer</summary>
  Here the `,` is missing from the third item in the list.  This makes the list 7 items long instead of 8, and the third item `-pitch+1-1`.  If you look closely, you can see that GitHub's syntax highlighting parser actually identifies the bug, and gives the `-` on line 4 a different color to indicate that it's not unary.
</details>

My proposal to solve this is to require whitespace either both before and after `-`, or neither before nor after.  We may also want to apply this to other operators for consistency, but I think `-` is the one that really causes problems.  Here are some examples under this rule:
```zig
_ = a - b; // fine
_ = a-b; // fine
_ = a -b; // error
_ = a- b; // error
_ = some_really_long_thing -
    some_other_really_long_thing; // ok
_ = some_really_long_thing
    - some_other_really_long_thing; // ok
_ = some_really_long_thing-
    some_other_really_long_thing; // error
_ = some_really_long_thing
    -some_other_really_long_thing; // error
```

**Comment by SpexGuy** [comment]
That was fast 😄 
Is the accepted version to apply this to all binary operators or just `-`?

**Comment by andrewrk** [comment]
> That was fast smile

Yep! Easiest way to get a proposal accepted is to 

 (1) solve a footgun
 (2) make the language accept fewer permutations of source code rather than more

>  Is the accepted version to apply this to all binary operators or just `-`?

I'd say all, for consistency, but feel free to make a case for just `-`.

----

Tasks to close the issue:

 * Update the language spec / grammar
 * Stage1 parser
 * Stage2 parser

**Comment by dbandstra** [comment]
I have a question related to this and #35, is `zig fmt` expected to be able to run on code that doesn't compile? Would `zig fmt` help to "fix" bad whitespace, or will it just die because the code doesn't compile?

**Comment by frmdstryr** [comment]
Linear / polynomial equations are often written using + to make the coefficients clear...

 So what about `x*x + -2*x + c0`? Is that invalid?

**Comment by SpexGuy** [comment]
That's fine, the `*` operators have whitespace on neither side and the `+` operators have whitespace on both sides.  Unary `-` is not affected by this rule.

**Comment by andrewrk** [comment]
> I have a question related to this and #35, is `zig fmt` expected to be able to run on code that doesn't compile? Would `zig fmt` help to "fix" bad whitespace, or will it just die because the code doesn't compile?

No, zig fmt would fail to parse it. If it "fixed" it then it would re-introduce the footgun.

**Comment by PavelVozenilek** [comment]
If all operators are required to have mandatory space around, it would increase readability and also open potential to use - (minus) as allowed name character. `this-style` may feel more readable than `this_style`.

Where such requirement would really shine are long names:   `some_long_name-other_long_name` vs   `some_long_name - other_long_name` or even  `some-long-name - other-long-name`.
