### ISSUE TITLE
(Parser) Error Compiling Hello World on FreeBSD 12.1

### ISSUE THREAD

**Issue by steephill** [ziglang/zig#7410]
I just downloaded zig (zig-freebsd-x86_64-0.7.0+d569e37cb), typed in and compiled the hello world example then noticed it doesn't like the tabs from indents in Vim. It compiled successfully after removing indents.

<img width="615" alt="Screen Shot 2020-12-12 at 12 31 08 AM" src="https://user-images.githubusercontent.com/6246221/101979498-60709180-3c12-11eb-8c02-684c3687cfed.png">

**Comment by tauoverpi** [comment]
As mentioned in https://github.com/ziglang/zig/wiki/FAQ#why-does-zig-force-me-to-use-spaces-instead-of-tabs it's intended and not a bug. It's good practice to run `zig fmt` which resolves this automatically for you.

**Comment by steephill** [comment]
Ok. Thanks.
