### ISSUE TITLE
auto-generated documentation rework

### ISSUE THREAD

**Issue by lolbinarycat** [ziglang/zig#7415]
The automatically generated documentation needs work. I don't think this is a controversial statement. Almost every time I wish something was added to the standard library it turns out it already existed, but was undocumented. Less discussed however, is how exactly to go about doing this. That is why I am laying out my ideas for how to improve it.

- [ ] use an intermediate type. currently it seems like we are going straight from ast to html, which would make it harder to adapt it to a different output.
- [ ] retain line numbers/filenames so you can check the original source if need be.
- [ ] show all public declarations, not just the ones with documentation.
- [ ] don't re-implement a parser from scratch? I don't know why this was done.
- [ ] comment things. there is one whole comment block in the file and all it has are some c preprocessor commands (what?)
- [ ] show type signatures better (showing them as written would probably be better than what we are doing now).

**Comment by MasterQ32** [comment]
Heya!

To get you up to the state of docgen:

> - use an intermediate type. currently it seems like we are going straight from ast to html, which would make it harder to adapt it to a different output.

The compiler compiles a normal project, but does not generate a binary, but output a json file that contains analysis information. The html file is actually the same for every generated documentation. Using an AST approach won't work very well for zig as you cannot use the AST directly as ground truth (see `std.ArrayList(T)` for example. It has different symbols exported when `T` is `u8`)

> - retain line numbers/filenames so you can check the original source if need be.

Afaik this information is included in the json file, but not included in the output. It should be easy to add this (which means: you can do it yourself if you need)

> - show all public declarations, not just the ones with documentation.

This does not work with the current model. Only symbols that are tested will be shown in the generated output. If you want more documented stuff, write tests that use those symbols and include them in the stdlib.

> - don't re-implement a parser from scratch? I don't know why this was done.

It wasn't done, the docgen uses the compiler as parser and analyzer (see above)

> - comment things. there is one whole comment block in the file and all it has are some c preprocessor commands (what?)

What do you refer to here?

> - show type signatures better (showing them as written would probably be better than what we are doing now).

This isn't easy with the current approach as well, but this is due to a problem with `TypeInfo` (which removes fn args and marks them generic even if the type is non-generic). This is probably way harder to improve

We were discussion an alternative AST based docgen in the [Zig communities](https://github.com/ziglang/zig/wiki/Community) already, if you want to contribute in the discussion there, join one of the zig discords and ping me (xq)

**Comment by lolbinarycat** [comment]
@MasterQ32

> (see std.ArrayList(T) for example. It has different symbols exported when T is u8)

yes, and that breaks the docs.
> It wasn't done, the docgen uses the compiler as parser and analyzer (see above)

There's definatly a parser there, but looking back at it it's a json parser, still weird that that isn't in stdlib.

> What do you refer to here?

line 654:
```
//#define VT_RED "\x1b[31;1m"
//#define VT_GREEN "\x1b[32;1m"
//#define VT_CYAN "\x1b[36;1m"
//#define VT_WHITE "\x1b[37;1m"
//#define VT_BOLD "\x1b[0;1m"
//#define VT_RESET "\x1b[0m"
```

**Comment by MasterQ32** [comment]
> line 654:
> ```
> //#define VT_RED "\x1b[31;1m"
> //#define VT_GREEN "\x1b[32;1m"
> //#define VT_CYAN "\x1b[36;1m"
> //#define VT_WHITE "\x1b[37;1m"
> //#define VT_BOLD "\x1b[0;1m"
> //#define VT_RESET "\x1b[0m"
> ```

I think you're looking at the [docgen](https://github.com/ziglang/zig/blob/master/doc/docgen.zig) for this page:
https://ziglang.org/documentation/master/
which is generated from [this](https://github.com/ziglang/zig/blob/master/doc/langref.html.in) file

while talking about the [docgen](https://github.com/ziglang/zig/blob/master/src/stage1/dump_analysis.cpp#L1211-L1407) for this page:
https://ziglang.org/documentation/master/std

am i right?

> > (see std.ArrayList(T) for example. It has different symbols exported when T is u8)
> 
> yes, and that breaks the docs.

So we need a way to document this correctly which is the basic idea of the current docgen system:
1. generate multiple analysis dumps for each possible build/target
2. merge these dumps into a bigger thing (afaik not implemented)
3. display these in HTML

1. and 3. are experimentally implemented and definitily not finished, 2. is afaik not used/implemented at all

**Comment by lolbinarycat** [comment]
>I think you're looking at the docgen for this page:
https://ziglang.org/documentation/master/
which is generated from this file

> while you are talking about the docgen for this page:
https://ziglang.org/documentation/master/std

> am i right?

yeah, but how am I supposed to know what the file is supposed to do when there are no comments? Only thing I have to go off of is the title, which is `docgen.zig`. also I assumed those docs were handwritten? doesn't look like a generated document at all.

**Comment by andrewrk** [comment]
cc @kristoff-it

**Comment by kuon** [comment]
I am learning zig, and the most important documentation feature for me would be the ability to see the code on std lib functions from the doc.

For example, elixir has it:

<https://hexdocs.pm/elixir/Kernel.html#apply/3>

You can see the `</>` symbol right of the function name, if you click it, it jumps to the code.

Rust has it inline, it does not point to github and has its own source viewer. 

The ability to rapidly jump to std lib (or any open source lib) source code is an invaluable learning resource.

**Comment by PaperPrototype** [comment]
Rust has a system where you can write test / example code for the documentation alongside functions and types! We could easily accomplish this by detecting a `test` block with the name of the function

```zig
pub fn add(a: int, b: int) int {
    return a + b;
}

// "fn add" can be special auto doc syntax 
test "fn add" {
   // test code or documentation
}

const float3 = struct {
    x: float,
    y: float,
    z: float,
};

// "struct float3" can be special auto doc syntax 
test "fn add" {
   // test code or documentation
}
```

I also like the idea of using comments above a function as its documentation title

**Comment by PaperPrototype** [comment]
I think taking inspiration from rusts auto doc system would be a great start. Maybe even try to do a zig port of it? :)

**Comment by Vexu** [comment]
> Rust has a system where you can write test/example code for the documentation alongside functions! We could easily accomplish this by detecting a `test` block with the name of the function

See #7923

> Also, why do we have doc comments with 3 slashes? `///` can we please get rid of that and just switch to regular comments are doc comments, like golang :))))))

Unlikely to happen

**Comment by PaperPrototype** [comment]
>Unlikely to happen
@Vexu 
Aw man

**Comment by tylergannon** [comment]
It would be really fantastic to have the documentation in an intermediate (i.e. json) format.  It would mean a lot for Zig projects to be enabled to integrate documentation into web sites.

I think it would go a long way towards enhancing adoption, if docs were a lot more portable.

I'd be happy to put in some work to make this happen, if there was anyone who would help me to tee it up.

**Comment by andrewrk** [comment]
Done in d0c06ca7127110a8afeb0ef524a197049892db21
