### ISSUE TITLE
Allow switch on optional and error types

### ISSUE THREAD

**Issue by DutchGhost** [ziglang/zig#7421]
This is a proposal to allow the use of the `switch` statement on optional and error types.
A usecase for this is to convert an optional type into an error type, at the moment it looks something like:

```Zig
if(optional) |inner| {
    return inner;
} else {
    return error.SomeKind;
}

// or:
return if(optional) |inner| inner else error.SomeKind;
```

Personally I'd prefer to write and read it like below, becouse both possibilities are aligned and it looks pleasant to the eye:
```Zig
return switch(optional) {
    .Variant => |inner| inner,
    .Null    => error.SomeKind,
};
```

Switch works for enums anyway, and optionals and error types are enum like, so to me it seems allowing switch on those is natural.

**Comment by Vexu** [comment]
Switching on optionals has previously been rejected in #1545.

**Comment by dbandstra** [comment]
For the usecase given I don't think it can get much better than

```zig
return optional orelse error.SomeKind;
```
