### ISSUE TITLE
macOS 10.13: incompatible ncurses library in CI builds

### ISSUE THREAD

**Issue by mkeeter** [ziglang/zig#7428]
Using the latest nightly (`zig-macos-x86_64-0.7.0+4fd27719b`) on macOS 10.13.6 fails due to dylib incompatibility.

``` # zig
dyld: Library not loaded: /usr/lib/libncurses.5.4.dylib
  Referenced from: /usr/local/bin/zig
  Reason: Incompatible library version: zig requires version 31090.97.114 or later, but libncurses.5.4.dylib provides version 5.4.0
fish: 'zig' terminated by signal SIGABRT (Abort)
```

Comparing against a previous nightly, which doesn't specify a compatibility version:
```
zig-macos-x86_64-0.7.0+58241364c# otool -L zig
zig:
        /usr/lib/libncurses.5.4.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

Something has obviously changed here:
```
zig-macos-x86_64-0.7.0+4fd27719b# otool -L zig
zig:
        /usr/lib/libncurses.5.4.dylib (compatibility version 31090.97.114, current version 25193.76.47)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

**Comment by andrewrk** [comment]
The way I would like to solve this is by having the CI statically link ncurses.

**Comment by kubkon** [comment]
> The way I would like to solve this is by having the CI statically link ncurses.

I guess we should aim for static linking of everything *except* `libSystem` of course, right? I'm all for that to avoid mess like this.

**Comment by andrewrk** [comment]
Yes exactly.

**Comment by mikdusan** [comment]
@mkeeter can you try latest nightly from zig downloads? It should work now. Here's what I get:

```sh
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G14042
alberta▸ otool -L ./zig
$ ./zig:
	/usr/lib/libSystem.B.dylib (compatibility version 0.0.0, current version 0.0.0)
$ ./zig version
0.9.0-dev.190+6f0cfdb82
```

**Comment by mkeeter** [comment]
Yup, looks good to me as well!  I haven't been writing much Zig recently, but congrats on the 0.8.0 release! 🎉

**Comment by elaforge** [comment]
Just FYI, looks like this came back in https://ziglang.org/builds/zig-macos-x86_64-0.9.0-dev.1791+c46a91da1.tar.xz:

```
% otool -L zig
zig:
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.40.0, current version 5.40.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
```

https://ziglang.org/download/0.8.1/zig-macos-x86_64-0.8.1.tar.xz has libncurses statically linked as intended.
