### ISSUE TITLE
Does Zig use a stack red zone?

### ISSUE THREAD

**Issue by BinaryWarlock** [ziglang/zig#7436]
On some architectures, such as x86_64, ABIs can allow (or even mandate) a "red zone" which is a fixed size area below the stack pointer that is always valid to use, and must not be clobbered by the compiler or operating system. ([Here's an article](https://eli.thegreenplace.net/2011/09/06/stack-frame-layout-on-x86-64) explaining it in more detail.)

The SysV ABI for x86_64 mandates a 128-byte red zone:
> The 128-byte area beyond the location pointed to by %rsp is considered to be reserved and shall not be modified by signal or interrupt handlers. Therefore, functions may use this area for temporary data that is not needed across function calls. In particular, leaf functions may use this area for their entire stack frame, rather than adjusting the stack pointer in the prologue and epilogue. This area is known as the red zone.

It's used in GCC and Clang by default to optimize leaf functions by omitting bumping the stack pointer.

However, [it is customary for OS kernels to disable the red zone](https://wiki.osdev.org/Libgcc_without_red_zone) (in GCC/Clang by the flag `-mno-red-zone`), because if the compiler generates code clobbering the red zone, it can corrupt the stack in interrupt handlers causing many headaches, so this is an important use case. ([Further reading](https://stackoverflow.com/questions/25787408/why-cant-kernel-code-use-a-red-zone).)

I could not find any Zig documentation, or references in the source code, to this.

So two parts to this are:

- Does Zig currently make use of the red zone, specifically on the x86_64 arch targeting the SysV ABI (the Win64 ABI does not have a red zone)?

- If so, is there a way to disable using the red zone, as with `-mno-red-zone`, to prevent the compiler from clobbering below the stack pointer?

**Comment by andrewrk** [comment]
Thanks for bringing this up! It led to the new CLI flags `-mred-zone` and `-mno-red-zone`. I believe the two questions are now answered: Zig is allowed to take advantage of red zones that are mandated by platform ABIs, unless you pass `-mno-red-zone` (new flag as of the merge of #7511 - thanks @leecannon).
