### ISSUE TITLE
Best way to handle optional-with-error return types (!?) in condition for while loop?

### ISSUE THREAD

**Issue by saltzm** [ziglang/zig#7439]
Hi! I'm brand new to Zig, having only used it for the first day of advent of code this year. 

I thought the `while` syntax was pretty cool, but one thing I was surprised at is that you can do
```zig
    while (result_or_error) |result| {
        // handle success
    } else |err| {
        // handle error
    }
```

or 
```zig
    while (optional_result) |result| {
        // handle case where value exists
    } else {
        // handle missing value
    }
```

but not

```zig
    while (optional_result_or_error) |result| {
        // handle success and value
    } else |err| {
        // handle error
    } else {
        // handle success but missing value
    }
```

I had to figure out the best way to read a file line by line (which took a while FWIW, though that might be a topic for another issue), and the solution I came up used [readUntilDelimiterOrEof](https://github.com/ziglang/zig/blob/481ce7361e075138e06bffff8c68ce8bf8c8eac3/lib/std/io/reader.zig#L197) which returns an `!?[]u8`, and I expected to be able to do the `while (...) {} else |err| {} else {}` but since I couldn't I ended up with this:

```zig
    pub fn problem1() void {
       var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
       defer arena.deinit();

       const allocator = &arena.allocator;

       const stdin = std.io.getStdIn();

       var f = fs.cwd().openFile("day1.txt", fs.File.OpenFlags{ .read = true }) catch |err| {
           std.os.exit(1);
       };
       defer f.close();

       const reader = f.reader();
       var line_buf: [256]u8 = undefined;

       var input = std.ArrayList(usize).init(allocator);
       defer input.deinit();

       while (reader.readUntilDelimiterOrEof(&line_buf, '\n')) |maybeLine| {
           if (maybeLine) |line| {
               const parsed = fmt.parseUnsigned(usize, line, 10) catch |err| {
                   std.debug.warn("Error while reading number: {}\n", .{err});
                   std.os.exit(1);
               };

               input.append(parsed) catch |err| {
                   std.os.exit(1);
               };
           } else {
               break;
           }
       } else |err| {
           print("Length of list: {}\n", .{input.items.len});
       }

       print("Length of list: {}\n", .{input.items.len});

       const result = problem1Helper(input.items);
       print("Result: {}!\n", .{result});
    }
```

Am I missing a better way to do that `while` loop? Looking again, it seems like putting a `try` in the condition would do the trick, as is done here: https://github.com/ziglang/zig/blob/4fd27719b4cee287f873c452a515927977bde0cd/tools/gen_stubs.zig#L38 

But that only works if I want to return an error from `problem1()`.

Another option instead of `while {} else |err| {} else {}` would be to just allow `while (optional_result_or_error) |result| {} else |err| {}` to work the same as `while (optional_result) |result| { }`.

**Comment by LemonBoy** [comment]
> But that only works if I want to return an error from problem1().

Ignoring the error is not a good practice...

> Am I missing a better way to do that while loop?

You can avoid the whole `maybeLine` unwrapping with 
```zig
const line = maybeLine orelse break;
```

Check out #7288 for a different take on this AoC problem.

**Comment by saltzm** [comment]
Right, I'm not suggesting that I ignore the error - suppose I wanted to just print the error and then break, as I'm doing in my example. (I'm not saying this is what I'd end up with it looking like in production or anything, but it's certainly something you might want to do even while just doing something silly like I'm doing here). The `orelse` thing is cool, I didn't know you could do that. That would definitely make my usage simpler, so I consider the "Is there a better way to do this" part of my question solved, I think.

As a feature request though, I still wonder if the three-pronged while would make sense.

**Comment by lolbinarycat** [comment]
honestly, I feel like `!?` should be generally discouraged. You have to unwrap it twice, and it isn't obvious what the null case represents. I feel like at that point it would be better to just add another error to the error set.

**Comment by andrewrk** [comment]
Welcome @saltzm, please note you can find plenty of places to ask questions such as these on the [community wiki page](https://github.com/ziglang/zig/wiki/Community).

**Comment by saltzm** [comment]
Thanks! I asked here because I thought it might turn into a proposal if people liked the idea of 

`while {} else |err| {} else {}`

But next time I'll start with one of the other forums!
