### ISSUE TITLE
`&@returnAddress()`  returns a mutable a pointer

### ISSUE THREAD

**Issue by RaphiJS6-13** [ziglang/zig#7448]
Whenever the address of `@returnAddress()` is taken, the compiler allocates a pointer on the stack, stores the return value of `@returnAddress()` in it, and then returns it as a mutable pointer:
```Zig
pub fn main() void {
    comptime var i = 0;
    inline while(i < 100): (i += 1) {
        (&@returnAddress()).* = 0; // should be an error, but isn't
    }
}
```
 (<a href="https://godbolt.org/z/YPY5oE">Here is a demonstration on godbolt.org</a>)

**Comment by Rocknest** [comment]
Whats your intent with this? Are you trying to get a pointer to where the return address is stored?  `@returnAddress` return a value (usize), its not possible to get an address of than. 

In this example automatic allocation on the stack is not really useful, but for other types it has some use. So its working as intended.

**Comment by MasterQ32** [comment]
I think this can be considered a bug report, as it returns a mutable reference instead of an immutable one (it modifies the return address value, which is wrong)

**Comment by Rocknest** [comment]
@MasterQ32 its a copy, you can do whatever you want with it. 

By the way link to godbolt uses old and unsupported zig release.

**Comment by SpexGuy** [comment]
This is the current expected behavior of `&` in Zig.  If the operand is an rvalue, it is copied into a stack temporary in the current scope and then the address of that temporary is used.  Because the value is on the stack and not in the data section, the pointer to it does not need to be const.

There is an argument that this may be a design flaw, but it's not clear whether that's what this ticket is pointing out.  @RaphiJS6-13 can you please elaborate on what you expected to happen or why you feel the current behavior is incorrect?

**Comment by RaphiJS6-13** [comment]
> Whats your intent with this? Are you trying to get a pointer to where the return address is stored? `@returnAddress` return a value (usize), its not possible to get an address of than.
> 
> In this example automatic allocation on the stack is not really useful, but for other types it has some use. So its working as intended.

@Rocknest Yes. I expected it to return the place on the stack where the return address is stored.

**Comment by RaphiJS6-13** [comment]
> @MasterQ32 its a copy, you can do whatever you want with it.
> 
> By the way link to godbolt uses old and unsupported zig release.

The same thing happened on my compiler, version 0.7.1, I just couldn't find an online editor that has the latest version.

**Comment by RaphiJS6-13** [comment]
> This is the current expected behavior of `&` in Zig. If the operand is an rvalue, it is copied into a stack temporary in the current scope and then the address of that temporary is used. Because the value is on the stack and not in the data section, the pointer to it does not need to be const.
> 
> There is an argument that this may be a design flaw, but it's not clear whether that's what this ticket is pointing out. @RaphiJS6-13 can you please elaborate on what you expected to happen or why you feel the current behavior is incorrect?

What do you mean "If the operand is an rvalue, it is copied into a stack temporary in the current scope and then the address of that temporary is used"?

In this code snippet, `&` on an rvalue returns a `const` pointer:

```zig
pub fn main() !void {
    var x = &[_]u8{0};
    x.* = [_]u8{5}; // error: cannot assign to constant
}
```
Yet, for some reason,  `&` on `@returnAddress()` returns a mutable pointer:
```zig
pub fn main() !void {
    var x = &@returnAddress();
    x.* = 6; // ok
}
```

**Comment by Rocknest** [comment]
@RaphiJS6-13 Here is not the best place to learn Zig. See where you can ask your questions at https://github.com/ziglang/zig/wiki/Community
