### ISSUE TITLE
Syntax proposal: `_!T` for inferred error set

### ISSUE THREAD

**Issue by EleanorNB** [ziglang/zig#7463]
`!T` is a strange beast. It's written as a unary operator, but it doesn't work like any other operator in the language; namely, it's ambiguous with the same sigil and arity (unlike `*`, which is also two operators but with different arities and hence unambiguous), and its interpretation is dependent on surrounding context. This isn't necessarily a *huge* deal with current semantics, since the two operators are never allowed in the same place (inferred error set can only appear leftmost in a return type, which cannot be boolean); but this rule is not necessarily intuitive (one might expect `?!T` to work as well as `!?T`, for instance), and future language changes may allow inferred error sets in other places, so it's not a long-term solution.

I propose we reuse the existing syntax for inference elsewhere in Zig (array length, type, result location): the underscore. Hence, an inferred error union is written `_!T`. This removes ambiguity with boolean negation, as well as being more suggestive of allowed position (since underscore elsewhere in the language is also only allowed in certain places, unlike operators which are allowed anywhere where their types appear): it's more obvious that `?_!T` is not allowed, whereas `_!?T` is.

**Comment by daurnimator** [comment]
I respect the argument, but IMO `_!T` is terribly ugly. To fix the conflict we could just pick something other than `!`?

Alternatively, it could be fixed by swapping `!` for the `not` keyword?

**Comment by EleanorNB** [comment]
Something other than `!` I'd be happy with, `not` keyword I would not. Keyword operators are for control flow only.

**Comment by EleanorNB** [comment]
Actually, strike that first bit. Error union is error union, inferred or not. We don't need a separate operator. Beauty is of course a matter of opinion, but personally I don't find `_!T` any uglier than `[_]T`.

**Comment by Mouvedia** [comment]
> one might expect ?!T to work as well as !?T

Can't we allow both?

**Comment by lolbinarycat** [comment]
> > one might expect ?!T to work as well as !?T
> 
> Can't we allow both?

They would have different meaning. same as `?[]T` vs `[]?T`. I feel like that would definitely go against "one way to do things".
