### ISSUE TITLE
Question about zig in regard to RemedyBG

### ISSUE THREAD

**Issue by clankill3r** [ziglang/zig#7513]
I am really new to zig, and to remedybg, neihter do I have real experience in C or C++. (mostly java sadly enough).

Anyway, I wanted to use RemedyBG with zig, and I got that working. But I can't watch arrays in the watch window for example. This is one of many things. I was wondering, is this due to RemedyBG or due to zig, or due how to build my executable?

Any tip is welcome.

**Comment by LemonBoy** [comment]
Sir, this is a bug tracker.

This kind of questions is better suited to [one of this channels](https://github.com/ziglang/zig/wiki/Community).

**Comment by clankill3r** [comment]
Thanks, I will redirect the question and close this.
