### ISSUE TITLE
Maybe a missing newline after `Test [1/1] test "xxx"...` output

### ISSUE THREAD

**Issue by clankill3r** [ziglang/zig#7514]
I made the following impressive code:

```
const std = @import("std");

test "for" {

    const string = [_]u8{ 'a', 'b', 'c'};

    for (string) |char, idx| {
        std.debug.print("char {}, index {}\n", .{char, idx});
    }
}
```

The output is as follow:

![zig_missing_newline](https://user-images.githubusercontent.com/738650/102787078-cee6e980-43a0-11eb-971f-bf8e77c4a9b3.png)

I thought maybe there should be a newline?

**Comment by MasterQ32** [comment]
No, that's allright and expected.

Printing text on a terminal usually means you cannot go back one line, but you can go back to the start (that's what a `CR` is for).

So when you print the progress, you print
```zig
"\rTest [{}/{}] test \"{}\" ..."
```
until all tests are run. When a `LF` is magically inserted, you don't get a nice progress meter, but a very long list of tests (or files or whatever).

**Comment by clankill3r** [comment]
Ah ok, that makes sense, closing it down.
