### ISSUE TITLE
Enhancement: Inclusive Slices

### ISSUE THREAD

**Issue by Mouvedia** [ziglang/zig#7518]
## expectation

Since we have `...` for inclusive ranges and #359 for exclusive ranges, I assumed to have inclusive slices as well.

## demand

add `...` support for slices at the same time as #359 is implemented

## example

```
slice[2...5]
// equivalent to
slice[2..6]
```

## rationale

The language should be consistent. If you have both `...` and `..` in a language, they should be allowed anywhere one or the other may be used.

**Comment by Vexu** [comment]
This has already been discussed in #359.

**Comment by Mouvedia** [comment]
@Vexu could you link the comment where it was not accepted?

**Comment by Vexu** [comment]
This has not been rejected but any discussion should be happening in #359 which is about making switch/slice ranges consistent. Also see #358 for more discussion on inclusive/exclusive ranges.

**Comment by Mouvedia** [comment]
@Vexu Now that #359 has been closed and this one has been added to the 0.8.0 milestone, can you reopen?
