### ISSUE TITLE
Problem with Explicit Error Sets

### ISSUE THREAD

**Issue by massivelivefun** [ziglang/zig#7544]
So first thing's first, I'm loving Zig.

However, I'm running into a problem with it. Specifically around the concept of error handling.
Below is an example of a function that is using an Explicit Error Set for part of it's return type.

```Zig
const ColorBand = enum(u4) {
    black,
    brown,
    // ...
};

pub const RuntimeError = error {
    IllegalArgumentError,
};

pub fn color_code(colors: []const ColorBand) RuntimeError!isize {
    if (colors.len < 2) {
        return RuntimeError.IllegalArgumentError;
    }
    return @as(isize, @enumToInt(colors[0])) * 10
        + @as(isize, @enumToInt(colors[1]));
}
```
This works as intended.

![image](https://user-images.githubusercontent.com/9347096/103128055-a97c0900-4648-11eb-84d6-4000a59a3c6f.png)

However, this next example does not compile correctly.
```Zig
pub const RuntimeError = error {
    IllegalArgumentError,
};

pub fn steps(start: isize) RuntimeError!isize {
    if (start <= 0) {
        return RuntimeError.IllegalArgumentError;
    }
    var number = start;
    var count: isize = 0;
    while (number != 1) {
        if (@mod(number, 2) == 0) {
            number = @divTrunc(number, 2);
        } else {
            number = 3 * number + 1;
        }
        count += 1;
    }
    return count;
}
```
Attempting to run the tests for this function doesn't even attempt to compile and gives this error message out.

![image](https://user-images.githubusercontent.com/9347096/103127805-d7148280-4647-11eb-9e5b-43588808b968.png)

When the Explicit Error Set is removed so that return error type is implicit for the steps function the tests will then compile.
```Zig
pub fn steps(start: isize) !isize { ...
```

![image](https://user-images.githubusercontent.com/9347096/103127882-104cf280-4648-11eb-8730-3982741c35b4.png)

Finally, here some additional information about my build:
- Windows 10 20H2 (OS Build 19042.685)
- Zig Compiler Version 0.7.1

Cannot confirm if this problem would persist on my Macbook because of this issue: #6971

Otherwise, if you need additional information from me let me know!

**Comment by Vexu** [comment]
Cannot replicate with:
```zig
pub const RuntimeError = error {
    IllegalArgumentError,
};

pub fn steps(start: isize) RuntimeError!isize {
    if (start <= 0) {
        return RuntimeError.IllegalArgumentError;
    }
    var number = start;
    var count: isize = 0;
    while (number != 1) {
        if (@mod(number, 2) == 0) {
            number = @divTrunc(number, 2);
        } else {
            number = 3 * number + 1;
        }
        count += 1;
    }
    return count;
}

test "" {
    _ = try steps(1);
}
```

Do you have a more complete example?

**Comment by massivelivefun** [comment]
Below are the specific unit tests for the steps function.

```Zig
const std = @import("std");
const testing = std.testing;

const collatz_conjecture = @import("./collatz_conjecture.zig");

test "zero steps for one" {
    const expected = 0;
    const actual = comptime try collatz_conjecture.steps(1);
    comptime testing.expectEqual(expected, actual);
}

test "divide if even" {
    const expected = 4;
    const actual = comptime try collatz_conjecture.steps(16);
    comptime testing.expectEqual(expected, actual);
}

test "even and odd steps" {
    const expected = 9;
    const actual = comptime try collatz_conjecture.steps(12);
    comptime testing.expectEqual(expected, actual);
}

test "large number of even and odd steps" {
    const expected = 152;
    const actual = comptime try collatz_conjecture.steps(1000000);
    comptime testing.expectEqual(expected, actual);
}

test "zero is an error" {
    const expected = collatz_conjecture.RuntimeError.IllegalArgumentError;
    const actual = comptime collatz_conjecture.steps(0);
    comptime testing.expectError(expected, actual);
}

test "negative value is an error" {
    const expected = collatz_conjecture.RuntimeError.IllegalArgumentError;
    const actual = comptime collatz_conjecture.steps(-15);
    comptime testing.expectError(expected, actual);
}
```

Am I using or making these tests incorrectly?

Also, I am getting the error on my Macbook as well:

<img width="350" alt="Screen Shot 2020-12-25 at 9 17 58 PM" src="https://user-images.githubusercontent.com/9347096/103145946-b35c4580-46f6-11eb-957c-c72dee5055e2.png">

Additional information about my Macbook:

- Big Sur 11.1 (20C69)
- Zig Compiler v0.7.0+9af53f8e0

**Comment by Vexu** [comment]
Thanks that helped, you are hitting this panic: https://github.com/ziglang/zig/blob/d20174ad881ab98291c4d1733ca8ec92811abbdc/src/stage1/analyze.cpp#L7251

This should be quite easy to fix, in the meanwhile you can just remove the `comptime` in those tests and they pass just fine.

**Comment by Mouvedia** [comment]
OFF TOPIC

@massivelivefun I saw "exercism" in your path but https://exercism.io/my/tracks/zig is a 404; how come?
