### ISSUE TITLE
compiler crashes if file to be compiled not found

### ISSUE THREAD

**Issue by ghost** [ziglang/zig#756]
```
zig build-exe this-file-does-not-exist
```
gives -
```
unable to open '.\this-file-does-not-exist': file not found
(and then crashhhhhhhh)
```

Windows 10
zig - latest build artifact from appveyor.

**Comment by jfo** [comment]
@andrewrk I think it's [here](https://github.com/jfo/zig/blob/dd20f558f0b3740a37c1d16a306e35f8cbe6a38f/src/codegen.cpp#L5709) but I don't have a windows env available to test with.

**Comment by andrewrk** [comment]
This is fixed now; zig exits with code 1 rather than calling abort().
