### ISSUE TITLE
Design Flaw: Namespaces are structs

### ISSUE THREAD

**Issue by RaphiJS6-13** [ziglang/zig#7566]
Treating file namespaces like structs legalizes many ill-formed things, like top-level field declaration, construction of namespaces, initialization of namespace fields, etc.
For example, this is legal:
<h5>weirdNamspace.zig</h5>

```Zig
a: usize,
```
<h5>main.zig</h5>

```Zig
const WeirdNamespace = @import("weirdNamespace.zig");

pub fn main() void {
    const w = WeirdNamespace{ .a = 3 };
}
```
The implementation shouldn't matter, provided that the above code is illegal, but I do have a proposal:

Instead of treating namespaces like `struct`s, why not treat them like `opaque` types?`opaque` types are perfect, because they have declarations, but no fields, and cannot be constructed.

**Comment by ifreund** [comment]
This is mostly a duplicate of #6617

**Comment by RaphiJS6-13** [comment]
> This is mostly a duplicate of #6617

Again, You're right.
I searched github for "namespace" and did not find #6617. Maybe I missed it.

**Comment by RaphiJS6-13** [comment]
> This is mostly a duplicate of #6617

Again, You're right.
I searched github for "namespace" and did not find #6617. Maybe I missed it.
