### ISSUE TITLE
`GeneralPurposeAllocator` not detecting leak 

### ISSUE THREAD

**Issue by emekoi** [ziglang/zig#7573]
```zig
const std = @import("std");
var gpa_alloc: *std.mem.Allocator = undefined;

fn zig_malloc(size: usize) ?*c_void {
    var bytes = gpa_alloc.alloc(u8, size + @sizeOf(usize)) catch return null;
    std.valgrind.mallocLikeBlock(bytes, 0, false);
    @ptrCast(*usize, @alignCast(@alignOf(usize), bytes.ptr)).* = size;
    return @ptrCast(*c_void, bytes.ptr + @sizeOf(usize));
}

fn zig_free(ptr: ?*c_void) void {
    if (ptr) |p| {
        var fp = @intToPtr([*]u8, @ptrToInt(p) - @sizeOf(usize));
        const size = @ptrCast(*usize, @alignCast(@alignOf(usize), fp)).*;
        // std.debug.warn("size: {} bytes\nfreeing: {} bytes\n", .{ size, size / 2 });
        gpa_alloc.free(fp[0 .. size / 2]);
        std.valgrind.freeLikeBlock(fp, 0);
    }
}

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){
        .backing_allocator = std.heap.page_allocator,
    };
    defer std.debug.assert(!gpa.deinit());

    gpa_alloc = &gpa.allocator;

    var i: usize = 0;
    while (i < 100) : (i += 1) {
        var a = zig_malloc(100);
        defer zig_free(a);
    }
}

```

this successfully exits even though we leak half of all our allocated bytes. am i misunderstanding something, my code written incorrectly, or is this a limitation of the current `GeneralPurposeAllocator`?

**Comment by LemonBoy** [comment]
> am i misunderstanding something

Your code is allocating from the 7th bucket and freeing from the 6th, the GPA (check out how `resize` calls `searchBucket`) doesn't stop there but keeps scanning until it finds the bucket your address belongs to _or_ reaches the last one (and then tries to free it as if it were a large off-bucket allocation).

The only effect `[0 .. size / 2]` has here is to clear (with `memset` of undefined) only half of the now freed memory, there's no memory leak.
