### ISSUE TITLE
Unreachable code encountered in translate-c if macro has dollar sign

### ISSUE THREAD

**Issue by ehaas** [ziglang/zig#7585]
Running translate-c on the following code causes an assertion failure:

```c
#define __$foo 2
```

in `transPreprocessorEntities`, `assert(mem.eql(u8, macro_ctx.slice(), name));` is failing because `name` is `__$foo` but `macro_ctx.slice()` returns `__`, presumably because `$` is an invalid token.

Technically  that is correct, but GCC allows it for legacy reasons: http://gcc.gnu.org/onlinedocs/cpp/Tokenization.html#Tokenization

> As an extension, GCC treats ‘$’ as a letter. This is for compatibility with some systems, such as VMS, where ‘$’ is commonly used in system-defined function and object names. ‘$’ is not a letter in strictly conforming mode, or if you specify the -$ option.

What should translate-c do here? Fail with a better error message, or translate it as `@"__$foo"`?

**Comment by Mouvedia** [comment]
> Fail with a better error message, or translate it as @"__$foo"?

Or maybe support `-fdollars-in-identifiers` and `-fno-dollars-in-identifiers`?

**Comment by daurnimator** [comment]
> Or maybe support `-fdollars-in-identifiers` and `-fno-dollars-in-identifiers`?

I'd like this for the `zig translate-c` command itself; but I'm left wondering how we could pass such options to `@cImport`

**Comment by Mouvedia** [comment]
> …but I'm left wondering how we could pass such options to @cImport

@daurnimator Are there other flags that would be used by `@cImport`? If there are more than 3, it might warrant having a second option argument for them. It could be either global (on `@cImport`) or granular (on `@cInclude`).

**Comment by daurnimator** [comment]
> Are there other options that could be used by `@cImport`?

trying to think of relevant ones:
  - trigraphs
  - `max-include-depth`
  - some encoding ones?

**Comment by Mouvedia** [comment]
Since you are not part of the core team, let's wait feedback from them to see if we go @ehaas's way or support options.

**Comment by ehaas** [comment]
> > Or maybe support `-fdollars-in-identifiers` and `-fno-dollars-in-identifiers`?
> 
> I'd like this for the `zig translate-c` command itself; but I'm left wondering how we could pass such options to `@cImport`

The two ways that I can think of that avoid breaking existing code would be to add `@cImportWithOptions` (or something like that); or to add a new built-in `@cPragma('foo')` that is only valid in `@cImport`, which appends `#pragma ZIG  foo` to the `c_import` buffer.

**Comment by andrewrk** [comment]
I don't think we need any flags for translate-c, we can just allow it.
