### ISSUE TITLE
Impossible to return error known at comptime

### ISSUE THREAD

**Issue by chip2n** [ziglang/zig#7591]
I'm trying to create a function that takes as argument some error `E: anyerror` known at comptime. As far as I can tell, it's not possible to declare the return type as `E!void`. I think this would be useful for things like validating return codes when interacting with C APIs (e.g. Vulkan).

Maybe the compiler should be able to infer the following example:

```zig
pub fn checkSuccess(result: VkResult, comptime E: anyerror) !void {
    switch (result) {
        VkResult.VK_SUCCESS => {},
        else => return E,
    }
}
```

Or perhaps the return type could be written explicitly as `error{E}!void`, but that doesn't currently work since `E` is not a `type`.

**Comment by dbandstra** [comment]
```zig
pub fn checkSuccess(result: i32, comptime E: anytype) @TypeOf(E)!void {
```

**Comment by chip2n** [comment]
Thanks! I tried using `@TypeOf(E)` in combination with `anyerror` and it returned `anyerror!void`, but using `anytype` instead seems to work perfectly! :pray:
