### ISSUE TITLE
translate-c erroneously translates macro into a function with variadic parameters.

### ISSUE THREAD

**Issue by lithdew** [ziglang/zig#7594]
While attempting to import [libmdbx v0.9.2 (amalgmated source-code)](https://github.com/erthink/libmdbx/releases/tag/v0.9.2) into Zig, I hit the compile error:

```
./zig-cache/o/f8c145dcff9dc1971436ccf5076fab7f/cimport.zig:954:5: error: non-extern function is variadic
pub fn MDBX_MAP_RESIZED_is_deprecated(...) callconv(.C) c_int {
    ^
```

The following C code in `mdbx.h`:

```c
/** MDBX_MAP_RESIZED
 * \ingroup c_err
 * \deprecated Please review your code to use MDBX_UNABLE_EXTEND_MAPSIZE
 * instead. */
MDBX_DEPRECATED static __inline int MDBX_MAP_RESIZED_is_deprecated() {
  return MDBX_UNABLE_EXTEND_MAPSIZE;
}
#define MDBX_MAP_RESIZED MDBX_MAP_RESIZED_is_deprecated()
```

... got translated to:

```zig
pub fn MDBX_MAP_RESIZED_is_deprecated(...) callconv(.C) c_int {
    return MDBX_UNABLE_EXTEND_MAPSIZE;
}
```

**Comment by ifreund** [comment]
Does your zig include 50e8c3882a3f753fe504a82ebc0d853a1fa1e0ed? I think this should have been fixed by that commit.

**Comment by lithdew** [comment]
> Does your zig include [50e8c38](https://github.com/ziglang/zig/commit/50e8c3882a3f753fe504a82ebc0d853a1fa1e0ed)? I think this should have been fixed by that commit.

Yep - using Zig master.
