### ISSUE TITLE
Memory unsafety in translate-c

### ISSUE THREAD

**Issue by LemonBoy** [ziglang/zig#7595]
[This](https://github.com/ziglang/zig/blob/1590ed9d6aea95e5a21e3455e8edba4cdb374f2c/lib/std/mem/Allocator.zig#L149-L153) comment reminded me to dig into this bizarre problem.
A quick gdb session showed that this (and many other instances of memory corruption) are caused by stale slices: `tokenSlice` returns a slice of `c.source_buffer`, a buffer that is eventually resized and/or moved during the `translate-c` lifetime.
You can easily observe that whenever a `tokenSlice` result is passed as argument to `appendTokenFmt`, as it happens for the failing test case mentioned in the comment, `source_buffer` is extended by `c.source_buffer.outStream().print` and the slice pointer becomes dangling.

The same problem affects `CtrlFlow.initToken` too and possibly many other places.

This problem was also hit [yesterday](https://freenode.irclog.whitequark.org/zig/2020-12-28#28696121;)  by @semarie.

CC @Vexu

**Comment by Vexu** [comment]
#7479 removed `tokenSlice`.
