### ISSUE TITLE
Can't build Zig stage 2 with MSVC x86

### ISSUE THREAD

**Issue by Prince213** [ziglang/zig#7614]
I'm trying to build 32bit zig compiler with MSVC, but met errors.
Log: [build.log](https://github.com/ziglang/zig/files/5756451/build.log)
Build script:
```
cd build
mkdir i686
cd i686
mkdir llvm
cd llvm
cmake ../../../src/llvm-11.0.0.src -Thost=x86 -G "Visual Studio 16 2019" -A Win32 -DCMAKE_INSTALL_PREFIX=E:\deps\i686 -DCMAKE_PREFIX_PATH=E:\deps\i686 -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_LIBXML2=OFF -DLLVM_USE_CRT_RELEASE=MT
msbuild /m -p:Configuration=Release INSTALL.vcxproj
cd ..
mkdir lld
cd lld
cmake ../../../src/lld-11.0.0.src -Thost=x86 -G "Visual Studio 16 2019" -A Win32 -DCMAKE_INSTALL_PREFIX=E:\deps\i686 -DCMAKE_PREFIX_PATH=E:\deps\i686 -DCMAKE_BUILD_TYPE=Release -DLLVM_USE_CRT_RELEASE=MT
msbuild /m -p:Configuration=Release INSTALL.vcxproj
cd ..
mkdir clang
cd clang
cmake ../../../src/clang-11.0.0.src -Thost=x86 -G "Visual Studio 16 2019" -A Win32 -DCMAKE_INSTALL_PREFIX=E:\deps\i686 -DCMAKE_PREFIX_PATH=E:\deps\i686 -DCMAKE_BUILD_TYPE=Release -DLLVM_USE_CRT_RELEASE=MT
msbuild /m -p:Configuration=Release INSTALL.vcxproj
cd ..
mkdir zig
cd zig
cmake ../../../src/zig -Thost=x86 -G "Visual Studio 16 2019" -A Win32 -DCMAKE_INSTALL_PREFIX=E:\zig\i686 -DCMAKE_PREFIX_PATH=E:\deps\i686 -DCMAKE_BUILD_TYPE=Release
msbuild -p:Configuration=Release INSTALL.vcxproj
cd ..
cd ..
cd ..
```
Is it not supported to build Zig directly with MSVC?

**Comment by LemonBoy** [comment]
My chinese is a bit rusty but [remove this stray brace](https://github.com/ziglang/zig/blob/46ea7a704ce4ce0669941b324296ca6092f9f2f6/src/stage1/util.hpp#L51) and part of the errors should go away.

**Comment by Prince213** [comment]
@LemonBoy I see that the documents explicitly mentioned to use `x64 Native Tools Command Prompt for VS 2019`. Is using x86 not offically supported? Or it is only used to note that one must use the same kind of `Command Prompt`?

**Comment by Prince213** [comment]
> My chinese is a bit rusty

@LemonBoy Sorry for that. Tried to make msbuild output English messages, but only warnings are.

**Comment by Prince213** [comment]
Ok. Those errors are now fixed, but there is a new one.
[C2371: 'ssize_t' : redefinition; different basic types](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2371?view=msvc-160)
In https://github.com/ziglang/zig/blob/master/src/stage1/os.cpp#L46 .
Collides with llvm-c/DataTypes.h line 64:
```c
#if defined(_WIN64)
typedef signed __int64 ssize_t;
#else
typedef signed int ssize_t;
#endif /* _WIN64 */
```

**Comment by LemonBoy** [comment]
Oh, this time it's LLVM's fault. According to Windows' `BASETSD.h` the definition of `SSIZE_T` is:

```c
//
// SIZE_T used for counts or ranges which need to span the range of
// of a pointer.  SSIZE_T is the signed variation.
//

typedef ULONG_PTR SIZE_T, *PSIZE_T;
typedef LONG_PTR SSIZE_T, *PSSIZE_T;
```

and

```c
#if defined(_WIN64)
    typedef __int64 INT_PTR, *PINT_PTR;
    typedef unsigned __int64 UINT_PTR, *PUINT_PTR;

    typedef __int64 LONG_PTR, *PLONG_PTR;
    typedef unsigned __int64 ULONG_PTR, *PULONG_PTR;

    #define __int3264   __int64

#else
    typedef _W64 int INT_PTR, *PINT_PTR;
    typedef _W64 unsigned int UINT_PTR, *PUINT_PTR;

    typedef _W64 long LONG_PTR, *PLONG_PTR;
    typedef _W64 unsigned long ULONG_PTR, *PULONG_PTR;

    #define __int3264   __int32

#endif
```

So the `signed int` should be a `signed long`.
Does it keep compiling if you comment away the typedef in `os.cpp` ?

**Comment by Prince213** [comment]
Now this error:
```
  Building self-hosted component E:/build/i686/zig/zig1.obj
.\src\link\MachO.zig : error G7325FB34: expected type 'usize', found 'u64' [E:\build\i686\zig\zig.vcxproj]
          dylinker_cmd.data = try self.base.allocator.alloc(u8, cmdsize - dylinker_cmd.inner.name);
                                                                        ^
  .\src\link\MachO.zig:304942679553:332316720: note: unsigned 32-bit int cannot represent all possible unsigned 64-bit
  values
          dylinker_cmd.data = try self.base.allocator.alloc(u8, cmdsize - dylinker_cmd.inner.name);
                                                                        ^
  .\src\link\MachO.zig:249108104705:4627284016: note: referenced here
          dylinker_cmd.data = try self.base.allocator.alloc(u8, cmdsize - dylinker_cmd.inner.name);
                                                           ^
  .\src\link\MachO.zig:21474836760:8922251312: note: referenced here
      try self.populateMissingMetadata();
      ^
  .\src\link.zig:107374182606:13217218608: note: referenced here
              .macho => &(try MachO.openPath(allocator, sub_path, options)).base,
                          ^
  .\src\Compilation.zig:111669150624:17512185904: note: referenced here
          const bin_file = try link.File.openPath(gpa, .{
                           ^
  .\src\main.zig:34359740137:21807153200: note: referenced here
      }) catch |err| {
         ^
  .\src\stage1.zig:184683593775:26102120496: note: referenced here
          stage2.mainArgs(gpa, arena, args) catch |err| fatal("{}", .{@errorName(err)});
                                            ^
```

**Comment by LemonBoy** [comment]
The C++ part is working, the Zig half is not-so-working.

Let's ping @kubkon, perhaps `cmdsize` can be safely scaled down to a `u32`.
The stack traces look quite bad tho, the column/line are messed up and I really hope the problem is not in the PDB parser.

**Comment by kubkon** [comment]
Oops, accidentally closed with 707b81e, apologies! Anyhow, @LemonBoy, fix in master as requested!

**Comment by kubkon** [comment]
@Prince213 @LemonBoy could you guys give it another go now?

**Comment by LemonBoy** [comment]
There are a few other `cmdsize` instances like [this](https://github.com/ziglang/zig/blob/707b81ec3722e67979683b5adbc9edd507bdbf9d/src/link/MachO.zig#L1635) and [this](https://github.com/ziglang/zig/blob/707b81ec3722e67979683b5adbc9edd507bdbf9d/src/link/MachO.zig#L1650)

**Comment by kubkon** [comment]
@LemonBoy done in fbf269c.

**Comment by Prince213** [comment]
Just tried https://github.com/ziglang/zig/commit/fbf269cc47a0a0bc0b60676ad97d4c57fda645c6.
Error: `allocation failed`

**Comment by kubkon** [comment]
@Prince213 could you supply the full stack trace? It's difficult to judge what the problem is just from `allocation failed`.

**Comment by Prince213** [comment]
@kubkon This is the log I've got:
![error](https://user-images.githubusercontent.com/25235514/103437234-0dfa2200-4c60-11eb-88c4-beed171571ff.png)

**Comment by kubkon** [comment]
Ugh, that's not very helpful indeed. Maybe @LemonBoy will have some ideas about this?

**Comment by LemonBoy** [comment]
That error message comes from a `zig_panic` call, are you sure the host system has enough ram?
I tried a zig-bootstrap build for `i386-windows-gnu` (on a x86_64 machine) and got no error.

The messed up line/column numbers in the error messages may be linked somehow, unless it's just a matter of stage1 using the wrong format specifiers in `print_err_msg_type`. Does the compiler show any warning about the C++ code?

**Comment by Prince213** [comment]
> That error message comes from a `zig_panic` call, are you sure the host system has enough ram?

@LemonBoy  Yes. I did the build with 4GB and 8GB and the build failed in both cases.

**Comment by LemonBoy** [comment]
> Yes. I did the build with 4GB and 8GB and the build failed in both cases.

I wonder if that's enough, the stage1 compiler requires a lot of memory.
Have you checked if the task manager reports an unusually high memory usage right before "allocation failure" is printed?

I'm asking because you may be either hitting a real OOM condition or, for some reason, hitting a bug that's corrupting some variable and that's making the stage1 call `malloc(some awfully large amount of memory)`.

Can you paste somewhere the full compilation log with all the warning messages?

**Comment by Prince213** [comment]
> I wonder if that's enough, the stage1 compiler requires a lot of memory.

x86_64 build works with 4GB. No reason x86 doesn't work.

> Have you checked if the task manager reports an unusually high memory usage right before "allocation failure" is printed?

Peak memory usage is ~4GB (from Task Manager) when with 8GB of RAM.

> Can you paste somewhere the full compilation log with all the warning messages?

@LemonBoy  Here: [msbuild.log](https://github.com/ziglang/zig/files/5759220/msbuild.log)

**Comment by LemonBoy** [comment]
> x86_64 build works with 4GB. No reason x86 doesn't work.

Colour me surprised, my linux builds take much more than that.

> Peak memory usage is ~4GB (from Task Manager) when with 8GB of RAM.

This begs the question, is your stage1 a 32bit exe?

>  Here: msbuild.log

I can't read a lick of Chinese, do you have a log with English messages instead?

**Comment by Prince213** [comment]
> This begs the question, is your stage1 a 32bit exe?

Yes. After all I'm doing a 32bit build.

> I can't read a lick of Chinese, do you have a log with English messages instead?

Sorry, but I can't help with that. I have installed English language pack and `chcp 437`, but only msbuild output are in English.
Maybe the error code can help you: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/c-cpp-build-errors?view=msvc-160.

**Comment by LemonBoy** [comment]
> Yes. After all I'm doing a 32bit build.

You're hitting the 32bit ceiling, you can easily cross-compile your 32bit build from your 64bit system using [zig-bootstrap](https://github.com/ziglang/zig-bootstrap) or something like that.

**Comment by Prince213** [comment]
I see. Thanks.
