### ISSUE TITLE
Importing SDL2 (again) no longer works

### ISSUE THREAD

**Issue by S0urc3C0de** [ziglang/zig#7621]
Essentially, I'm getting the same errors as in #7551 on the latest commit.
```
$ zig version
0.8.0-dev.716+fbf269cc4
```

**Comment by ehaas** [comment]
Can you check if the `src/translate_c.zig` patch here https://github.com/ziglang/zig/pull/7597/files fixes it?

**Comment by S0urc3C0de** [comment]
I will once I'm back home!

**Comment by ZaneA** [comment]
That patch appears to have worked for me @ehaas, I can now import and use SDL2 :)

**Comment by S0urc3C0de** [comment]
@ehaas Your patch fixes the issue!

**Comment by ehaas** [comment]
@S0urc3C0de it looks like the fix got merged to master if you want to try it again

**Comment by andrewrk** [comment]
I just tried it today btw and the fix worked for me
