### ISSUE TITLE
macOS linking issues on nightly and 0.7.1 release build

### ISSUE THREAD

**Issue by rudedogg** [ziglang/zig#7623]
I'm having issues building with the nightly and 0.7.1 release download (from ziglang.org) on macOS Big Sur 11.1, x86_64. 

--------------------------

| Zig Version  | ZIG_SYSTEM_LINKER_HACK  | Successfully Builds  |  Notes  | 
|---|---|---|---|
|  0.7.1+8078d8cd3  |  1  |  ❌  | latest nightly release download from ziglang.org  | 
|  0.7.1+8078d8cd3  |    |  ❌  | latest nightly release download from ziglang.org  | 
|  0.7.1  |  1  |  ❌  | 0.7.1 release download from ziglang.org  | 
|  0.7.1  |    |  ❌  | 0.7.1 release download from ziglang.org  | 
|  0.7.0+9af53f8e0  |  1  |  ✅  | 0.7.0 release download from ziglang.org  | 
|  0.7.0+9af53f8e0  |   |  ✅  | 0.7.0 release download from ziglang.org  | 

0.7.1+8078d8cd3 (latest nightly build) + `ZIG_SYSTEM_LINKER_HACK=1` error:
```
❯ zig run main.zig 
warning(link): unexpected LD stderr: ld: library not found for -lSystem

error(link): ld: library not found for -lSystem

error: LDReportedFailure
```

0.7.1+8078d8cd3 (latest nightly build) + **no** `ZIG_SYSTEM_LINKER_HACK=1` error:
```
❯ zig run main.zig
ld64.lld: error: Unable to find library for -lSystem
error: FileNotFound
```

0.7.1 + `ZIG_SYSTEM_LINKER_HACK=1` error:
```
❯ zig run main.zig                                               
warning: unexpected LD stderr: ld: library not found for -lSystem

ld: library not found for -lSystem
error: LDReportedFailure
```

0.7.1 + **no** `ZIG_SYSTEM_LINKER_HACK=1` error:
```
❯ zig run main.zig                
ld64.lld: error: Unable to find library for -lSystem
error: the following command failed to execve with 'FileNotFound':
/Users/rudedogg/.cache/zig/o/5dba7ba5651d5858668f1d8c25c9488a/main
```

--------------------------------

My test program is hello world (main.zig):
```zig
const std = @import("std");

pub fn main() void {
    std.debug.print("Hello, {}!\n", .{"World!!!"});
}
```

I've asked another macOS user in Discord, and they confirmed that 0.7.1 and nightly builds from ziglang.org weren't working for them either. 0.7.0 however does. I've installed `0.7.1` and `HEAD` using homebrew and that works fine.

I would however like to be able to just download a release for a 2015 MacBook Pro where installing zig (due to the long install time of the LLVM dependency) never completes.

**Comment by rudedogg** [comment]
I wonder if #7569 is related. 

> > Does this not work? What is the error message?
> 
> It immediately fails for an **indirect** reason -- some .zig code decides on passing `-syslibroot` only when `11.x` is detected and thus fails on my `11.x` system if using downloaded binaries, or using a binary I build myself against 10.15.* SDK and lower.
> 
> #### fail (on Big Sur w/ zig built against 10.15.6 SDK)
> ```
> ld64.lld -error-limit 0 -demangle -dynamic -arch x86_64 -macosx_version_min 10.16.0 -sdk_version 10.16.0 -pie -o rf zig-cache/o/3c293c7b5708f2c551433057af517710/rf.o /Users/mike/.cache/zig/o/9d95847e6b6f2162984f0cfd73b0ebad/libcompiler_rt.a -lSystem
> warning(link): unexpected LLD stderr:
> ld64.lld: error: Unable to find library for -lSystem
> ```
> 
> #### success (on Big Sur w/ zig built against 11.1.0 SDK)
> ```
> ld64.lld -error-limit 0 -demangle -dynamic -arch x86_64 -macosx_version_min 11.1.0 -sdk_version 11.1.0 -pie -o rf -syslibroot /Applications/Xcode_12.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk zig-cache/o/7b9913ea831855db1526b0d9357f998b/rf.o /Users/mike/.cache/zig/o/4271907eac86b92cae46d62a868a23d4/libcompiler_rt.a -lSystem
> ```



The behavior sounds like it, but I'm confused why the 0.7.0 binary release works without issue.

**Comment by mikdusan** [comment]
> I wonder if #7569 is related.

I think so...

>The behavior sounds like it, but I'm confused why the 0.7.0 binary release works without issue.

`0.7.0` release binaries (for x86_64) has a load-command for `LC_BUILD_VERSION` being `11.0` so zig detects Big Sur proper. `0.7.1` and `0.7.1+` both have load-commands for `LC_VERSION_MIN_MACOSX` `10.15.7` so zig detects and uses `10.16.0` for `ld64.lld` command line.

**Comment by hiljusti** [comment]
I was also seeing this with @travisbhartwell

Built from source (via homebrew) works fine and links to lotsa things

    $ otool -L /usr/local/bin/zig
    /usr/local/bin/zig:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/local/opt/llvm/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)

Release version from https://ziglang.org/download/0.7.1/zig-macos-x86_64-0.7.1.tar.xz links less things and either has linker errors with LLD or segfaults with `-fno-LLD`

    $ otool -L build/bin/zig
    build/bin/zig:
	/usr/lib/libncurses.5.4.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)

**Comment by kevinsjoberg** [comment]
I just install `zig`, version `0.7.1` on macOS Big Sur, version `11.2.1`, and got the same error trying to run the `zig build run` for the hello world example.

```console
$  zig build run
warning: unexpected LLD stderr:
ld64.lld: error: Unable to find library for -lSystem

error: FileNotFound
```

**Comment by srenatus** [comment]
Sorry for piling on, but I'm facing the same issue with this code: https://github.com/istio-ecosystem/wasm-extensions/tree/d71616b2dc7418a28e5aee5722e1c86ce738e02f/extensions/zig_demo

I'm surprised because its build target is wasm32/freestanding, https://github.com/istio-ecosystem/wasm-extensions/blob/d71616b2dc7418a28e5aee5722e1c86ce738e02f/extensions/zig_demo/build.zig#L7. What am I missing? 🤔

**Comment by mikdusan** [comment]
I'm afraid that zig.exe 0.7.1 and older is not something that is usable on Big Sur. Suggest you try downloading a master build for now.

**Comment by mikdusan** [comment]
@rudedogg, can you try latest nightly to see if it helps with original issue? I'm on Big Sur x86_64 and its building quite a bit of stuff for me.

**Comment by srenatus** [comment]
> Suggest you try downloading a master build for now.

🤦 Thanks. I can't really say why trying that hadn't occurred to me.

**Comment by srenatus** [comment]
@mikdusan Haven't run into this using the master build. Thanks again! 🚀
