### ISSUE TITLE
Nested anonymous struct compiler segfault (stage 1)

### ISSUE THREAD

**Issue by Sobeston** [ziglang/zig#7627]
Happens on both 0.7.1 and the latest CI release, using `zig build-exe` on an x86_64-linux system.

```zig
const std = @import("std");

pub fn main() void {
    var x: []const u8 = "something!";

    const y = .{
        .z = .{
            .a = x,
            .b = .{},
        },
    };
}
```

This is a weird one: if I remove the a line or the b line I do not get a segfault; tiny code changes seem to get around the bug. Maybe related: https://github.com/ziglang/zig/issues/7607#issuecomment-752759800

**Comment by mikdusan** [comment]
with latest compiler:
- compilation no longer segfaults
- appears this was fixed between 0.9.1 and 0.10.0

<details>
<summary>repro.zig</summary>

```zig
const std = @import("std");

pub fn main() void {
    var x: []const u8 = "something!";

    const y = .{
        .z = .{
            .a = x,
            .b = .{},
        },
    };
    _ = y;
}
```
</details>

```sh
$ uname -a
Linux archlinux 6.1.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 31 Dec 2022 17:40:35 +0000 x86_64 GNU/Linux

$ archlinux▸ zig version
0.11.0-dev.1241+0507ced8c

$ zig build-obj repro.zig
# no stdout/stderr (good)
```
