### ISSUE TITLE
Recursive struct with optional fails to compile

### ISSUE THREAD

**Issue by BinaryWarlock** [ziglang/zig#7633]
I don't know if this is a dupe of #2746 or simply related, or even intended behavior, but a recursive struct type with an optional:

```zig
const Foo = struct {
    nested: ?Foo,
};
```

Fails to compile with:
```
error: struct 'Foo' depends on itself
```

However, using an optional pointer:
```zig
const Foo = struct {
    nested: ?*Foo,
};
```

Works.

Is my understanding correct that in Zig `?T` on a struct type should be equivalent (at least internally) to a nullable pointer to `T`? If that's the case then I don't know why the first case fails since they should be equivalent.

I was hoping I could just build these `Foo` values on the stack and nest them and return them, but even if this compiled would that be legal behavior? (i.e. would copy elision take over and construct the whole hierarchy on the caller's stack?)

For example:
```zig
fn f() Foo {
    var ret = Foo { .nested=null; };
    return Foo { .nested=ret };
}
```
Would this be sane?

**Comment by dbandstra** [comment]
No, optionals are not pointers. They are values plus an "is null" bit, so the struct you propose would have infinite size.
