### ISSUE TITLE
zig emits i1 for bool in llvm IR, while clang emits i8 for C bool 

### ISSUE THREAD

**Issue by dsimunic** [ziglang/zig#7639]
Per documentation for 0.7, `bool` should be equivalent to C `bool`. Running `translate-c` behaves consistently with that. 

When compiling, however, zig 0.7.1 will emit `i1` in llvm IR, while clang will emit `i8` for `bool` in the original C source file.

Top of file for completeness of the example:

```
const c = @cImport({
    @cInclude("postgres.h");
    @cInclude("fmgr.h");
});

pub const Oid = c_uint;
pub const Datum = usize;
```

Here's the source struct as defined in a header file, and the generated llvm IR:

```
typedef struct NullableDatum
{
 Datum value;
 _Bool isnull;
} NullableDatum;

//cc -S -emit-llvm =>  %struct.NullableDatum = type { i64, i8 }
```

`zig translate-c` produces an extern struct with a `bool` type, as expected:

```
pub const NullableDatum = extern struct {
    value: Datum,
    isnull: bool,
};
```

and then `zig build` outputs this llvm IR:

```
zig build --verbose-llvm-ir => %NullableDatum = type { i64, i1 }
```

Here's another more complex struct that happens to contain a `bool`:

```
typedef struct FunctionCallInfoBaseData
{
 FmgrInfo *flinfo;
 fmNodePtr context;
 fmNodePtr resultinfo;
 Oid fncollation;

 _Bool isnull;
 short nargs;

 NullableDatum args[];
} FunctionCallInfoBaseData;

//cc -S -emit-llvm =>
//        %struct.FunctionCallInfoBaseData = type { %struct.FmgrInfo*, %struct.Node*, %struct.Node*, i32, i8, i16, [0 x %struct.NullableDatum] }
```

Translate-c failed to translate the above struct due to the presence of `args` field, this is a manual re-creation:

```
pub const FunctionCallInfoBaseData = extern struct {
    flinfo: *c.FmgrInfo,
    context: c.fmNodePtr,
    resultinfo: c.fmNodePtr,
    fncollation: Oid,
    isnull: bool,
    nargs: c_short,
    args: [*]NullableDatum,
};
```
Again, `zig build` produces `i1` for `bool` in the fifth position:

```
//zig build --verbose-llvm-ir =>
//        %FunctionCallInfoBaseData = type { %".cimport:4:11.struct_FmgrInfo"*, i8*, i8*, i32, i1, i16, %NullableDatum* }
```

**Comment by LemonBoy** [comment]
And?

**Comment by andrewrk** [comment]
I'm happy to re-open this if you provide an example where `bool` does not properly match the C ABI in an extern function.
