### ISSUE TITLE
Are strings in TypeInfo guaranteed to be null-terminated?

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#7644]
Related PR: https://github.com/ziglang/zig/pull/7643

I have some code that uses reflection to iterate over a set of function declarations. It then passes these function names to a function that loads them (like dlsym https://linux.die.net/man/3/dlsym). However, the loader function requires the name string be null-terminated, but it looks like the strings within TypeInfo aren't declared as being null-terminated.

So the question is, are these strings within TypeInfo guaranteed to be null-terminated?

**Comment by andrewrk** [comment]
No; they are the types that they say they are. Do you want to turn this into a proposal to change things?

**Comment by marler8997** [comment]
I don't think there's a need since I can use comptime to generate the null-terminated versions. I'll close this issue and the PR since you've clarified that the language does not guarantee null termination (which I think is fine).
