### ISSUE TITLE
failed to run zig fmt on windows

### ISSUE THREAD

**Issue by wsdjeg** [ziglang/zig#7654]
I am using latest version of zig, downloaded from https://ziglang.org/builds/zig-windows-x86_64-0.7.1+dfacac916.zip

the version is:

```
C:\Users\wsdjeg\Desktop>zig version
0.7.1+dfacac916
```

the test file is:

```zig
const std = @import("std");

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    try stdout.print("Hello, {}!\n", .{"world"});
}
```

the result of `zig run`, `zig test` and `zig fmt` is:

```
C:\Users\wsdjeg\Desktop>zig run test.zig
Hello, world!

C:\Users\wsdjeg\Desktop>zig fmt test.zig
error: unable to open 'test.zig': error.Unexpected

C:\Users\wsdjeg\Desktop>zig test test.zig
Semantic Analysis [785/1153] No tests to run.
```

there is no extra useful information for debug this issue.

**Comment by rohlem** [comment]
What Windows version are you on? I get the same result on Windows 7 (also with #7379 ), though it worked when I last used it on newest Windows 10 (about 2 weeks ago).
Compatibility with / support for versions before Windows 10 is desired in general, but less commonly tested.

**Comment by wsdjeg** [comment]
I am using win 7, `ver` result is:

```
C:\Users\wsdjeg\.SpaceVim>ver

Microsoft Windows [版本 6.1.7601]
```

**Comment by rohlem** [comment]
`zig fmt` seems to work for me (same version / `ver` output) in newest builds, now that #7379 has landed in the compiler itself.
(With the exception of ".." in relative paths, which I assume is pending on #7664 .)

**Comment by andrewrk** [comment]
I believe this is fixed now.
