### ISSUE TITLE
Make null overridable

### ISSUE THREAD

**Issue by tecanec** [ziglang/zig#7655]
The way null-pointers are handled in Zig could be expanded to other types as well by letting the programmer define a special value that is to be treated as `null`. This allows for:

- Better communications with non-Zig systems. The most prominent example would be zero-terminated ASCII-strings, which are already supported in Zig via zero-terminated pointers. (More on that later.)
- Optionals with zero memory overhead.

I propose the following syntax:
```
const Char = 0?u8;
const CString = [*:null]Char;

const Thingading = struct {
    a: u32,
    b: *u8,
};
var optional_thingading: Thingading{.b = @intToPtr(*u8, 0)?Thingading = null;
```
A few things to note:

- Non-null values with the same encoding as null are illegal. (For example, `var x: 0?u8 = 0;` is illegal.) This is safety-checked undefined behavior.
- The null-value does not need to follow all of the usual rules. For example, pointers can be zero or unaligned. However, some rules still need to be followed, as it must be possible to encode `null` within the same memory as the base type.
- Classic optional types are still supported and will remain mostly unchanged.
- Null-values are tied to their optional types and must therefore be comptime-known.
- Sentinel-terminated pointers are changed into null-terminated pointers. Null-terminated pointers will be more useful, anyway, so there is no reason to allow for other sentinels if this proposal is accepted.

And a few things to consider (there may be others that I didn't think of):

- The syntax is, of course, unfinalized. I personally dislike `[*:null]T` in particular, as the `null` would become redundant.
- The exact rules that null-values must follow should be considered.
  - Undefined enum-values could be excellently used to make null-values distinct, but will fall apart if that value is gets defined in the future.
  - Not all struct members would need to be defined in a null-value, as one distinct field is enough to set the null-value apart from non-null values. Whether these unused fields should be set to `undefined` or not set at all should be considered.
 - A syntax for accessing undefined fields of tagged unions may become useful.
 - With the addition of explicit syntax, it is no longer strictly necessary to encode null-pointers as zero by default. Whether to keep doing this should be considered.
 - How to allow normally illegal values to be used for null-values.

**Comment by andrewrk** [comment]
Hi @tecanec, thanks for the proposal.

If we are going to do this it will be with something along the lines of #3806.

**Comment by tecanec** [comment]
I have seen that proposal. However, it doesn't solve the problem of needing a specific encoding of `null` (such as when interfacing with external systems like open file formats), nor does it help with anything that isn't an int or an enum. That said, I do acknowledge that the added complexity is a notable downside to my proposal.
