### ISSUE TITLE
Use semver for ziglang versioning?

### ISSUE THREAD

**Issue by manast** [ziglang/zig#7661]
I am quite used to semver since I have been working a lot within the nodeJs ecosystem so I was a bit surprised that after upgrading ziglang from 0.7.0 to 0.7.1 some breaking changes prevented my code for compiling. I could not find any versioning policy in the documentation nor in the issues, so I am not sure what you are using. If it is ad-hoc I really recommend that you switch to something like semver so that we can get some guarantees every time we upgrade the compiler. The rules are also pretty easy to understand and follow, TLDR: micro is for bugfixes, minor is backwards compatible new features, and major is non-backwards compatible new features.

https://semver.org/

**Comment by jayschwa** [comment]
Zig is using SemVer, but it is still in development, so there are no stability guarantees across v0 releases. [v0 according to SemVer](https://semver.org/#spec-item-4):

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

In practice, the Zig project bumps the minor version every six months in step with LLVM releases. Patch releases have been uncommon and 0.7.1 was somewhat of an exception.

**Comment by manast** [comment]
ok, fair enough. I think it should be stated somewhere though, unless it is already somewhere, I could not find it at least.
