### ISSUE TITLE
zig run adding extra argument

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#7665]
`zig run` is erroneously adding an extra argument to the running program.  This behavior can be seen by running the following program that simply prints all its command-line arguments:

```zig
const std = @import("std");
pub fn main() !void {
    for (try std.process.argsAlloc(std.heap.page_allocator)) |arg, i| {
        std.debug.warn("[{}] {}\n", .{i, arg});
    }
}
```

With an older compiler I get the following expected output on Windows:
```batch
> zig run bug.zig
[0] C:\Users\Jonathan\AppData\Local\zig\o\443fb7b5c6231c6397d9d5ee88b79378\bug.exe
```

With the latest compiler I get this:
```batch
> d:\git\zig\zig-cache\bin\zig.exe run bug.zig
[0] C:\Users\Jonathan\AppData\Local\zig\o\7c11a065e8f0ef991692b72de857ddc7\bug.exe
[1] d:\git\zig\zig-cache\bin\zig.exe
```

As you can see, its adding the compiler as an extra argument to the running program.

**Comment by g-w1** [comment]
This is where it is happning: https://github.com/ziglang/zig/blob/master/src/main.zig#L1856 got introduced in this commit https://github.com/ziglang/zig/commit/7ca9f3bc7ba1a413ea7f8b88dfafba3d0f842f6e . 
#7666 closes this

**Comment by marler8997** [comment]
I built with a1a1929cf4ff979bdaba17f858d4ce8647e87a65 which includes commit 7ca9f3bc7ba1a413ea7f8b88dfafba3d0f842f6e and this still appears to be broken (running on Windows 10).

**Comment by marler8997** [comment]
Nevermind, it looks like it was fixed. I was using the old `zig.exe` from `zig-cache\bin`...
