### ISSUE TITLE
How to build a shared dynamic library using the build system?

### ISSUE THREAD

**Issue by manast** [ziglang/zig#7677]
I assume this is quite trivial but I am not able to make it work, all examples provided include the creation of an exe file but in my case I only want to produce a dynamic library. Basically what I want is to mimic this:
```bash
zig build-lib -lc -dynamic -isystem . src/bullmq.zig
```
using a build.zig file. This is the one I tried, it builds everything without errors but no dynamic library is produced:
```zig
const Builder = @import("std").build.Builder;

pub fn build(b: *Builder) void {
    const mode = b.standardReleaseOptions();

    const lib = b.addSharedLibrary("bullmq", "src/bullmq.zig", b.version(0, 0, 1));
    lib.setBuildMode(mode);
}
```

what I am missing?

**Comment by daurnimator** [comment]
> what I am missing?

`lib.install()`

---

Such a question is probably better posed in one of the various Zig communities (see https://github.com/ziglang/zig/wiki/Community).

**Comment by manast** [comment]
@daurnimator yes you are probably right. But it can also be considered an issue regarding better docs. Btw, your suggestion did not work unless lib.install installed the library in my system somewhere, so it is not equivalent to ```zig build-lib -lc -dynamic -isystem . src/bullmq.zig``` which produces a shared library in the same path where the command was executed...

**Comment by manast** [comment]
AFAICS addSharedLibrary is not documented anywhere, not in the Builder reference either https://ziglang.org/documentation/0.6.0/std/#std;build.Builder

**Comment by pfgithub** [comment]
> unless `lib.install` installed the library in my system somewhere

The build system outputs files in `zig-cache/`. Shared libraries in `zig-cache/lib/`

> AFAICS addSharedLibrary is not documented anywhere

The build system is very badly documented right now. Most information you can find about it is by looking at other examples of build.zig files, reading the source code, or asking in one of the zig communities. There is a work-in-progress [page on ziglearn](https://ziglearn.org/chapter-3/) that contains some information also.

**Comment by manast** [comment]
> The build system is very badly documented right now. Most information you can find about it is by looking at other examples of build.zig files, reading the source code, or asking in one of the zig communities. There is a work-in-progress [page on ziglearn](https://ziglearn.org/chapter-3/) that contains some information also.

That was exactly what I was trying but for dymica libraries I could not find a single example :).
Anyway, I will skip the use of the build system since it does not really do what I need it to do. Thanks for the help.

**Comment by S0urc3C0de** [comment]
`zig init-lib` would also have given you a good template on how to create a library using Zig.
