### ISSUE TITLE
unable to find 'std.zig' when building on a 32bit machine

### ISSUE THREAD

**Issue by serge-sans-paille** [ziglang/zig#7686]
I'm trying to package zig for Fedora. I managed to get working binaries for x86_64 and aarch64 but build on i686 fail with

```
 /usr/bin/cmake --install i686-redhat-linux-gnu
-- Install configuration: "RelWithDebInfo"
-- Installing: /builddir/build/BUILDROOT/ziglang-0.7.1-1.i386/usr/bin/zig
-- Installing: /usr/lib
unable to find 'std.zig'::
:: ERROR: 1
:: (execute_process)
::
:: argv: /builddir/build/BUILD/zig-0.7.1/i686-redhat-linux-gnu/zig build --override-lib-dir /builddir/build/BUILD/zig-0.7.1/lib -Dlib-files-only --prefix /usr -Dconfig_h=/builddir/build/BUILD/zig-0.7.1/i686-redhat-linux-gnu/config.h install
::
:: argv[0]: /builddir/build/BUILD/zig-0.7.1/i686-redhat-linux-gnu/zig
:: argv[1]: build
:: argv[2]: --override-lib-dir
:: argv[3]: /builddir/build/BUILD/zig-0.7.1/lib
:: argv[4]: -Dlib-files-only
:: argv[5]: --prefix
:: argv[6]: /usr
:: argv[7]: -Dconfig_h=/builddir/build/BUILD/zig-0.7.1/i686-redhat-linux-gnu/config.h
:: argv[8]: install
::
```

full build log here if it helps: https://kojipkgs.fedoraproject.org//work/tasks/5927/58935927/build.log

**Comment by Jan200101** [comment]
I can only imagine that it could not find lib/std/zig.zig for unknown reasons but the log seem to be dead so I am unsure

**Comment by andrewrk** [comment]
> full build log here if it helps: https://kojipkgs.fedoraproject.org//work/tasks/5927/58935927/build.log

The link 404s. Feel free to comment on this issue if you try again and I'll re-open. I'm sure this will be solved eventually one way or another.
