### ISSUE TITLE
put all the LLVM alloca instructions together at the beginning of the function

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#7689]
```zig
fn foo() void {}

export fn henlo() void {
    var x: i32 = 1;
    foo();
    var y: i32 = 1;
}
```

actual output:

```llvm
; ModuleID = 'test'
source_filename = "test"

define void @henlo() {
Entry:
  %0 = alloca i32, align 4
  store i32 1, i32* %0, align 4
  call void @foo()
  %1 = alloca i32, align 4
  store i32 1, i32* %1, align 4
  ret void
}

define void @foo() {
Entry:
  ret void
}
```

expected output:

```llvm
; ModuleID = 'test'
source_filename = "test"

define void @henlo() {
Entry:
  %0 = alloca i32, align 4
  %1 = alloca i32, align 4
  store i32 1, i32* %0, align 4
  call void @foo()
  store i32 1, i32* %1, align 4
  ret void
}

define void @foo() {
Entry:
  ret void
}
```

This ensures that LLVM will emit machine code to adjust the stack pointer all at once at the beginning of the function, rather than multiple times. It makes a big difference for optimizations.

**Comment by daurnimator** [comment]
Is this something we could add as an actual LLVM optimization?

Should we only hoist them up to a previous `return`? or to the top of the block?
Or can we do some smart `min_of_blocks()` operation?

e.g. for the following snippet, there should be no reason to alloca more than 2000 bytes:

```zig
fn foo() void {
    if (x) {
       const a = [1000]u8 = big_thing();
       if (something(a)) return;
    }
    const b = [2000]u8 = big_other_big_thing();
    if (something(b)) return;

    bar();
}
```

**Comment by andrewrk** [comment]
This is simply a matter of LLVM API usage, you're supposed to put all the allocas at the top, otherwise LLVM does silly things.

**Comment by mauro-balades** [comment]
No, this is to avoid extra allocations. For example, if we add a new alloca when we find a variable declaration, we could potentially be allocating unnecessarily each iteration of a loop
