### ISSUE TITLE
comptime string with {} then formatted producing byte array not string

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#7703]
https://github.com/markfirmware/zig-vector-table/issues/2

I can reduce the problem but I thought a simple resolution might jump out at someone.

Thanks, Mark

**Comment by g-w1** [comment]
This was changed with https://github.com/ziglang/zig/pull/6870 . You need "{s}" now for strings.

**Comment by markfirmware** [comment]
Thanks! Will test and close.
