### ISSUE TITLE
cannot execute musl linux stage2 test binaries natively on arch linux (gnu)

### ISSUE THREAD

**Issue by FireFox317** [ziglang/zig#7704]
So currently for most tests in the stage2 testsuite, we specify a linux_x64 `CrossTarget` i.e:
https://github.com/ziglang/zig/blob/91e3431d4a55aa46884b267be5aa586f3ed94f74/test/stage2/test.zig#L9-L12
~~Since there is no abi specified, it defaults to musl.~~ (EDIT: This is incorrect i think) I expect this binary to be able to be executed on my Arch Linux system (x86_64-linux-gnu).

We then use this target (x86_64-linux-musl) to get an external executor.
https://github.com/ziglang/zig/blob/91e3431d4a55aa46884b267be5aa586f3ed94f74/src/test.zig#L836

We then arrive at the following code:
https://github.com/ziglang/zig/blob/91e3431d4a55aa46884b267be5aa586f3ed94f74/lib/std/zig/cross_target.zig#L624-L630
Here we get the `dynamic_linker` of the `case.target`. Thus this returns the dynamic linker for x86_64-linux-musl which is `/lib/ld-musl-x86_64.so.1`. We then check if we can access this dynamic linker, which we cannot find on my linux machine and thus we think we cannot execute it natively. However we do in fact can execute a musl binary on a gnu linux system.

**Comment by FireFox317** [comment]
Okay actually the problem might be in `std.zig.system.NativeTargetInfo.detect`. We pass in a `CrossTarget` that has the `abi` tag set to null (`x86_64-linux`), however the target it returns is `x86_64-linux-musl` while my system is a gnu system. Let's investigate further.

**Comment by FireFox317** [comment]
Okay, I think I have a clear picture of what is happening:

First, since the `CrossTarget` that we specify is `x86_64-linux`, the actual target that we return is `x86_64-linux-musl`. This is correct behaviour according to the doc comments:
https://github.com/ziglang/zig/blob/91e3431d4a55aa46884b267be5aa586f3ed94f74/lib/std/zig/cross_target.zig#L41-L42
We could change the target to `x86_64-native`, which will return the target `x86_64-linux-gnu` on my system (That works correctly). But some tests really only work on linux, so `x86_64-linux` is the correct `CrossTarget` to specify. 

So the actual problem is in the `getExternalExecutor` then, because we can run a `x86_64-linux-musl` binary natively on a `x86_64-linux-gnu` system.

**Comment by kubkon** [comment]
@FireFox317 is this still a problem on your end? I'm asking since I'm running Arch and I cannot replicate the issue you're having with stage2 linux tests on latest master.
