### ISSUE TITLE
zig c++: compiled kakoune binary gives "libc++abi: terminating with uncaught exception of type Kakoune::failure"

### ISSUE THREAD

**Issue by ghuls** [ziglang/zig#7711]
zig c++: compiled kakoune binary gives "libc++abi: terminating with uncaught exception of type Kakoune::failure"

```bash
git clone https://github.com/mawww/kakoune/

cd kakoune
```

```bash
CC='../../zig/zig-linux-x86_64-0.7.1/zig cc' CXX='../../zig/zig-linux-x86_64-0.7.1/zig c++' make install
```

Trying to run the compiled Kakoune binary:
```
$ ./scr/kak
libc++abi: terminating with uncaught exception of type Kakoune::failure
```

Am I missing an option in the zig compiler to compile it correctly? Or is it not supported at the moment? (The machine where I want to compile it eventually has an old compiler which does not support `-std=c++17`. I would like to avoid installing GCC or LLVM from source would.)

I had to fix the makefile to let kakoune pick up ncurses.
```diff
git diff
diff --git a/src/Makefile b/src/Makefile
index 590978ef..a3c09e14 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -90,8 +90,10 @@ else
        $(error "pkg-config not found in PATH")
     endif
 
-    LIBS += $(shell $(PKG_CONFIG) $(PKG_CONFIG_FLAGS) --libs ncursesw)
-    NCURSES_CFLAGS += $(shell $(PKG_CONFIG) $(PKG_CONFIG_FLAGS) --cflags ncursesw)
+    #LIBS += $(shell $(PKG_CONFIG) $(PKG_CONFIG_FLAGS) --libs ncursesw)
+    #NCURSES_CFLAGS += $(shell $(PKG_CONFIG) $(PKG_CONFIG_FLAGS) --cflags ncursesw)
+    LIBS += $(shell ncursesw6-config --libs)
+    NCURSES_CFLAGS += $(shell ncursesw6-config --cflags)
     LDFLAGS += -rdynamic
 endif
```

**Comment by LemonBoy** [comment]
This is easy to fix, zig's clang mode doesn't pass `--eh-frame-hdr` like the real clang does (see `tools::gnutools::Linker::ConstructJob` and other `ConstructJob` definitions).

**Comment by ghuls** [comment]
So where do I need to add this flag?

**Comment by LemonBoy** [comment]
You can't add a `-Wl,--eh-frame-hdr` because `zig cc` doesn't support it (that's another bug), apply this patch to Zig & rebuild it to get a working `kak` binary:

```patch
diff --git a/src/link/Elf.zig b/src/link/Elf.zig
index f3073824a..ce88cd38b 100644
--- a/src/link/Elf.zig
+++ b/src/link/Elf.zig
@@ -1462,6 +1462,8 @@ fn linkWithLLD(self: *Elf, comp: *Compilation) !void {
         try argv.append("-pie");
     }
 
+    try argv.append("--eh-frame-hdr");
+
     const full_out_path = try directory.join(arena, &[_][]const u8{self.base.options.emit.?.sub_path});
     try argv.append("-o");
     try argv.append(full_out_path);
```

**Comment by ghuls** [comment]
Will this end up in the zig compiler in the future. I would like to avoid building LLVM (which seems necessary to build zig from source).

**Comment by ghuls** [comment]
Thanks. Last dev version works fine now.
