### ISSUE TITLE
Proposal - Fn-error: errdefer-like functionality using if-error style syntax

### ISSUE THREAD

**Issue by mjoerussell** [ziglang/zig#7717]
This idea came after reading the proposal #5018 which suggests that having an `errdefer` block containing unreachable should allow the function to exclude the error union from its return type. Some concerns were raised about confusing edge cases if this was implemented. My suggestion is to allow `if-error` style syntax with function definitions. Here's an example (adapted from #5018):

```zig
const std = @import("std");

fn performErr(): !void {
  _ = try std.math.add(u8, 255, 1);
}

fn perform(): void {
  _ = try std.math.add(u8, 255, 1);
} catch |err| {
  std.debug.print("An error occurred: {}\n", @errorName(err));
  std.process.exit(1);
}
```

## Goals

* A syntactically consistent way to handle errors at a function level, and preventing the caller from knowing about those errors.

## Non-Goals

* Replace `errdefer` - this would still be useful for cases where you want multiple `errdefer` blocks in a function, for example cleaning up a partially-initialized struct after an error.

## Properties

1. Like with `if-error` blocks, the `fn-error` block is expected to be a single expression.
2. `fn-error` blocks consume errors that are returned from the base `fn` block.
3. The result type of the `err` expression must conform to the return type of the base `fn`.

## Examples

**Return default value**

```zig
const std = import("std");
const add = std.math.add;

// current
fn addAllMaxErr(a: u8, b: u8, c: u8) !u8 {
  const x = try add(u8, a, b);
  const y = try add(u8, x, c);
  return y;
}

fn addAllMaxA(a: u8, b: u8, c: u8) u8 {
  const x = add(u8, a, b) catch |_| return 255;
  const y = add(u8, x, c) catch |_| return 255;
  return y;
}

// proposed
fn addAllMaxB(a: u8, b: u8, c: u8) u8 {
  const x = try add(u8, a, b);
  const y = try add(u8, x, c);
  return y;
} catch |_| 255;

fn main() void {
  const errTest = addAllMaxErr(100, 100, 100) catch |_| 255;
  const testA = addAllMaxA(100, 100, 100);
  const testB = addAllMaxB(100, 100, 100);
}

```

**Optional Initialization**

```zig
const std = @import("std");
const Allocator = std.mem.Allocator;

const Test = struct {
  data: []u32

  fn init(allocator: *Allocator, data_len: u32) Test {
    return .{ .data = try allocator.alloc(u32, data_len) };
  } catch |err| blk: {
    break :blk .{ .data = &[0]u32{} };
  }
};
```

**Conditionally Handling Errors**

Since the error block is just an expression that matches the return type of the function, we could have a function that uses an error block while still returning an error union.

```zig

const FatalError = error{Danger};
const MaybeOkError = FatalError || error{Ok};

fn complexFn(): MaybeOkError!u32 { ... }

fn test(): FatalError!u32 {
 return try complexFn();
} catch |err| switch (err) {
  .Ok => 0 // recover gracefully from one error
  .Danger => .Danger, // Propagate failure from another
}
```

**With Function Expression syntax**

I think that this syntax could especially make sense when applied to the changes proposed in #1717 

> Note: I'm not 100% aware if the syntax below is exactly what's defined for functions as expressions, using my best approximation.

```zig
const std = @import("std");

const main = fn() void {
  const addMax = fn(a: u8, b: u8, c: u8) u8 {
    const x = try std.math.add(u8, a, b);
    const y = try std.math.add(u8, x, c);
    return y;
  } catch |_| 255;
  // Caller doesn't have to worry about errors since they've already been handled
  std.debug.print("Sum is {}\n", .{addMax(100, 100, 100)});
  std.debug.print("Sum is {}\n", .{addMax(100, 10, 5)});
  std.debug.print("Sum is {}\n", .{addMax(200, 0, 1)});
  std.debug.print("Sum is {}\n", .{addMax(150, 100, 0)});
}  
    
}
```

**Comment by marler8997** [comment]
The example provided by @dbandstra in the other proposal is one that I commonly use:
```zig
fn main() u8 {
    main2() catch |err| {
        std.debug.warn("{}\n", .{err});
        return 1;
    };
    return 0;
}

fn main2() !void {
    // the real code
}
```

It looks like with your proposal it would become this:
```zig
fn main() u8 {
    // ...
} catch |err| {
    std.debug.warn("{}\n", .{err});
    return 1;
}
```

This removes having to have an extra function in the callstack, and it seems pretty readable to me.  Interesting.

**Comment by kyle-github** [comment]
@marler8997 mentioned:

> This removes having to have an extra function in the callstack, and it seems pretty readable to me. Interesting.

While true, would not most wrapper functions get inlined and thus eliminate the call stack difference?  I do not think there will be a performance or resource use difference here.

This proposal seems like it is about 75% of the way to implementing `try/catch` blocks.   I am not saying that is bad or good.  The blocks just happen to be on entire functions.

Any more examples?   I am not imaginative enough to see where I would write code this way :-(

**Comment by marler8997** [comment]
> While true, would not most wrapper functions get inlined and thus eliminate the call stack difference? I do not think there will be a performance or resource use difference here.

Yes, not thinking about performance, more about debugging/triage.  Decreasing the number of functions in a call stack was one reason used to justify 2 implementations of ArrayList.

**Comment by tauoverpi** [comment]
This seems to encourage taking away the choice from the caller by making it easier to handle it within the function itself. Having it be a bit of a pain to do anything other than `try` to push the error higher and `catch` inline to deal with it there seems to end in better thought out code (as far as I've played with zig) since the example @marler8997 looks odd enough at a first glance to give it a second look to make sure everything is handled correctly.

It'd even argue that it's better in the `main` wrapper as some location information is retained and the possible error codes are the first thing you'd see rather than trailing at the end.

**Comment by marler8997** [comment]
Yeah I don't like that it's ad the end of the function, I think I'd prefer it at the beginning if something like this were to be accepted.

**Comment by mjoerussell** [comment]
Here's a (admittedly contrived) example that also shows where `errdefer` would still be used. Overall the benefit I see in this feature is that it provides a way to return a default value/run a default expression on returning *any* error *anywhere* in the function, which `errdefer` doesn't provide.

```zig
const std = @import("std");
const some_module = @import("other");

const StringNum = struct {
  string: []const u8,
  value: u32,
};

// Two errors can occur here, in either case we want to return null instead of the struct.
// If the error occurs while parsing the allocated string, the resources need to be cleaned up
// before returning, but the string should not be freed if the function succeeds.
fn test() ?StringNum {
  const allocator = std.testing.allocator;

  const str_value: []const u8 = try some_module.get_and_alloc_for_some_reason(allocator);
  errdefer {
    // If an error is thrown while parsing the string, clean up the string
    allocator.free(str_value);
  };

  const result =  try std.fmt.parseInt(u32, str_value, 10);
  return .{ .string = str_value, .value = result };
} catch |_| return null; // errdefer runs before this, this block is the very last thing.

```

**Comment by mjoerussell** [comment]
> 
> 
> Yeah I don't like that it's ad the end of the function, I think I'd prefer it at the beginning if something like this were to be accepted.

I definitely see how that could lead to it being overlooked or missed on first read, but I think it's consistent with the way that `catch`, `if-error`, `if-optional`, and `for-else` all are written.
