### ISSUE TITLE
container 'std.io' has no member called 'OutStream'

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#7747]
What is the guidance for updating?

https://github.com/markfirmware/zig-vector-table/runs/1677567929?check_suite_focus=true

    zig version 0.8.0-dev.887+a7da90071

    ./linker.zig:150:16: error: container 'std.io' has no member called 'OutStream'
        out: std.io.OutStream(fs.File, std.os.WriteError, fs.File.write),
                   ^
    ./linker.zig:168:38: note: referenced here
        var prepare_memory: IndentedStream = undefined;
                                         ^
     /linker.zig:14:5: note: referenced here
        prepare_memory = IndentedStream.open(prepare_memory_file_name);
        ^

**Comment by daurnimator** [comment]
`OutStream` has been deprecated in the last few releases.
It was renamed to `Writer`.
