### ISSUE TITLE
std.fmt: support formatting integer types > 128 bits

### ISSUE THREAD

**Issue by lithdew** [ziglang/zig#7748]
Right now `std.fmt.formatInt` relies on division operations to format an integer, which is unsupported for integer types of sizes beyond 128 bits (e.g. 256 bits).

**Comment by xdBronch** [comment]
i believe this can be closed, std.fmt supports arbitrarily sized ints

**Comment by lithdew** [comment]
> i believe this can be closed, std.fmt supports arbitrarily sized ints

The issue is related to LLVM throwing an error when a 128 bit integer is passed to `std.fmt.formatInt`. In which commit was this fixed?

**Comment by xdBronch** [comment]
https://github.com/ziglang/zig/issues/1485#issuecomment-1289447690 looks like it came with the update to llvm 15
