### ISSUE TITLE
[ARM macOS, x64 macOS and aarch64 linux] allocPrint inconsistency

### ISSUE THREAD

**Issue by prime31** [ziglang/zig#7756]
zig version: 0.8.0-dev.878+e4b8148e9

allocPrint seems to have odd results. I use allocPrint to concat paths and they all result in PathNotFound errors now. It seems `zig build --help` also has some oddities in its string printing. Here is example output from macOS arm64 and linux aarch64:

<img width="867" alt="Screen Shot 2021-01-11 at 8 19 04 PM" src="https://user-images.githubusercontent.com/60377/104269665-b1f78080-544b-11eb-91c3-5cfe46fd0d7e.png">

<img width="758" alt="Screen Shot 2021-01-11 at 8 19 49 PM" src="https://user-images.githubusercontent.com/60377/104269659-b02dbd00-544b-11eb-87d4-8f6c4849bf19.png">

Sample program and output to demonstrate:
```
pub fn main() anyerror!void {
    const tmp = try std.fmt.allocPrint(std.testing.allocator, "me: {}, {}", .{"first", "second"});
    std.log.info("out: {}", .{tmp});
    std.log.info("out: {s}", .{tmp});
}
```

```
info: out: { 109, 101, 58, 32, 91, 53, 58, 48, 93, 117, 56, 64, 49, 48, 50, 55, 52, 102, 100, 52, 54, 44, 32, 91, 54, 58, 48, 93, 117, 56, 64, 49, 48, 50, 55, 52, 102, 100, 52, 99 }
info: out: me: [5:0]u8@10274fd46, [6:0]u8@10274fd4c
```

**Comment by g-w1** [comment]
For printing strings you must use "{s}" or else it will be printed like an array of u8s.

**Comment by Vexu** [comment]
#7675 will make this give a useful error.
