### ISSUE TITLE
child_process: pipe2 does not set O_CLOEXEC for mac

### ISSUE THREAD

**Issue by billzez** [ziglang/zig#7760]
O_CLOEXEC should be set using F_SETFD.  Perhaps pipe2 should call setSockFlags() for proper emulation of O_CLOEXEC and O_NONBLOCK?

**Comment by LemonBoy** [comment]
The `pipe2` wrapper in `os` is already using `pipe()+fcntl(F_SETFL)` when the target is osx.

**Comment by billzez** [comment]
Correct, F_SETFL is used for O_NONBLOCK and F_SETFD is used for O_CLOEXEC.  See setSockFlags()

**Comment by LemonBoy** [comment]
Cool, `F_SETFL` is silently accepting and discarding `O_CLOEXEC`.
Yes, the code should be fixed to use both the `fcntl` calls, `F_SETFD` for `O_CLOEXEC` and `F_SETFL` for every other flag.
