### ISSUE TITLE
'expression value is ignored' should say why the value must be used

### ISSUE THREAD

**Issue by jyn514** [ziglang/zig#7775]
I just tried the following code:
```zig
  // pretend `input` is a string from somewhere
  var lines = std.mem.split(input, "\n");
  while (lines.next()) |line| try stdout.write(line);
```
That gave the following error:
```
./src/main.zig:14:31: error: expression value is ignored
  while (lines.next()) |line| try stdout.write(line);
                              ^
./src/main.zig:5:29: note: referenced here
pub fn main() anyerror!void {
                            ^
```
As someone new to zig, this was super confusing - I have `try` there, the error isn't being ignored. It turns out the issue is that `write` may not write all bytes, and it wants you to handle the number of bytes written somehow; the fix is to use `writeAll` instead. It would be nice to have a more helpful error message.

For comparison, here's a similar warning in rust:
```
warning: unused return value of `f32::<impl f32>::floor` that must be used
 --> src/main.rs:2:5
  |
2 |     2.0_f32.floor();
  |     ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_must_use)]` on by default
  = note: method returns a new number and does not mutate the original value
```
(Rust doesn't warn if you ignore the `usize` in the `Result<usize, _>` that `write()` returns, about to open another issue about that).

**Comment by g-w1** [comment]
All values in zig must be used. Dont open another issue about it. I dont see a reason for it to tell you why because everything must be used. Am I missing the point?

**Comment by jyn514** [comment]
Why must all values be used?

**Comment by jyn514** [comment]
It could at least say what the type of the expression is.

**Comment by daurnimator** [comment]
I believe the proposal here is the ability to add a 'note' about what the return value is?

**Comment by jyn514** [comment]
Right - it wasn't clear to me originally that it returned a value at all, I thought it returned `Error!void` or something like that.

**Comment by g-w1** [comment]
Ah, I see. This could also be improved in the langref. Fyi you _can_ ignore the return type with `_ = funcThatReturns();`

**Comment by tecanec** [comment]
This seems to have just been a newcommer's confusion, but I still think it's worth trying to keep this from happening to other beginners. We could implement a message like "Expression value of type {} is ignored. To keep all code consistent and easy to decipher, zig requires all such expression values to be either used or discarded with `_ = [expression];`."

**Comment by Vexu** [comment]
This is implemented in the self-hosted compiler:
```
a.zig:10:33: error: value of type 'usize' ignored
    while (lines.next()) |line| try stdout.write(line);
                                ^~~~~~~~~~~~~~~~~~~~~~
a.zig:10:33: note: all non-void values must be used
a.zig:10:33: note: this error can be suppressed by assigning the value to '_'
```
