### ISSUE TITLE
Wrong output values when printing through generic structs

### ISSUE THREAD

**Issue by AbeerVaishnav13** [ziglang/zig#7776]
## The problem
Hello, I was trying a simple program for using generics in Zig and found out about this issue where if I try to bring the values for a slice from within a struct type, it gives wrong values. I'm not sure if this is due to my programming error, or because of the compiler's error.

## System configuration
- **Zig Version:** 0.7.1
- **Zig installation source:** Homebrew
- **OS:** MacOS Big Sur 11.1
- **Native architecture:** x86_64

### Code to reproduce the issue
Here's my code which makes a `Matrix` type capable of taking a generic type `T` as a comptime type resolution parameter:
```zig
const std = @import("std");
const print = std.debug.print;

fn Matrix(comptime T: type, comptime n: usize) type {
    return struct {
        size: comptime usize = n,
        items: [n][n]T = switch (@typeInfo(T)) {
            .Float, .ComptimeFloat => [_][n]T{[_]T{0.0} ** n} ** n,
            .Int, .ComptimeInt => [_][n]T{[_]T{0} ** n} ** n,
            else => [_][n]T{[_]T{T.zero()} ** n} ** n,
        },

        const Self = @This();

        pub fn init(self: *Self, data: *[n][n]T) void {
            for (data) |row, i| {
                for (row) |val, j| {
                    self.items[i][j] = val;
                }
            }
        }

        pub fn add(self: *Self, m: *Matrix(T, n)) *Matrix(T, n) {
            var sum = Matrix(T, n){};

            for (self.items) |row, i| {
                for (row) |val, j| {
                    sum.items[i][j] = switch (@typeInfo(T)) {
                        .Float, .ComptimeFloat, .Int, .ComptimeInt => val + m.items[i][j],
                        else => val.add(m.items[i][j]),
                    };
                }
            }

            return &sum;
        }

        pub fn printMat(self: Self) void {
            print("{} matrix:\n", .{@typeName(T)});
            for (self.items) |row| {
                for (row) |val| {
                    print("{} ", .{val});
                }
                print("\n", .{});
            }
            print("\n\n", .{});
        }
    };
}

pub fn main() !void {
    const n = 2;

    // f64 matrix
    var mat1: [n][n]f64 = .{
        .{ 1.0, 1.0 },
        .{ 2.0, 2.0 },
    };
    var mat2: [n][n]f64 = .{
        .{ 3.0, 3.0 },
        .{ 4.0, 4.0 },
    };

    var m1 = Matrix(f64, n){};
    var m2 = Matrix(f64, n){};
    m1.init(&mat1);
    m2.init(&mat2);

    const m3 = m1.add(&m2);

    print("Matrix m3 (from outside struct):\n", .{});
    print("f64 matrix:\n", .{});
    for (m3.items) |row| {
        for (row) |val| {
            print("{} ", .{val});
        }
        print("\n", .{});
    }
    print("\n\n", .{});

    print("Matrix m1:\n", .{});
    m1.printMat();
    print("Matrix m2:\n", .{});
    m2.printMat();
    print("Matrix m3 (from inside struct):\n", .{});
    m3.printMat();
}
```
### Output
This code gives the following output:
```
$ zig run generic.zig

Matrix m3 (from outside struct):
f64 matrix:
4.0e+00 4.0e+00
6.0e+00 6.0e+00


Matrix m1:
f64 matrix:
1.0e+00 1.0e+00
2.0e+00 2.0e+00


Matrix m2:
f64 matrix:
3.0e+00 3.0e+00
4.0e+00 4.0e+00


Matrix m3 (from inside struct):
f64 matrix:
0.0e+00 4.0e+00
0.0e+00 4.0e+00
```

As you can see, the type inference is correct for all the outputs. But for the first output the nested for loop is within the `main()` function (for which the values are correct). Whereas, the second output contains values printed from the `m3.printMat()` function (which is wrong). However, interestingly, I have printed the matrices `m1` and `m2` as well, and their values turn out to be correct in the output. This is what I'm not able to understand.

I tried everything to make it right, and even deleted the `zig-cache` folder and re-run the code. but the problem still persists. Once again, it might be the case that I might've coded it wrong as I'm not a pro in Zig. but please look into this issue.

Thanks
Abeer

**Comment by LemonBoy** [comment]
> I'm not sure if this is due to my programming error, or because of the compiler's error.

The former. Your `add` method is returning a pointer to a stack-allocated variable, once `add` returns the content becomes undefined.

**Comment by AbeerVaishnav13** [comment]
Oh no... That was a real rookie mistake. I'm sorry for not bothering everyone with this. And thanks @LemonBoy for pointing it out. I'll close this issue now.
