### ISSUE TITLE
Internal compiler error when creating aligned struct type.

### ISSUE THREAD

**Issue by floooh** [ziglang/zig#7780]
I'm trying to create a struct type which is C-ABI compatible and will be aligned to 16 bytes like this:

```zig
const Bla align(16) = extern struct {
    a: u32, b: f32, c: u8
};
```
(aiming for what ```__attribute__((aligned(16))) struct { };``` would do in clang/gcc)

This triggers the following assertion:

https://github.com/ziglang/zig/blob/2b0e3ee228e01473cf880f719db9bde5b8f34d25/src/stage1/analyze.cpp#L618

Actual error message is:

```
Assertion failed at /tmp/zig-20201223-21290-6b04l3/src/stage1/analyze.cpp:618 in get_pointer_to_type_extra2. This is a bug in the Zig compiler.
```

This seems to happen for all types of structs, no matter if ```extern```, ```packed``` or vanilla.

Potential duplicate of https://github.com/ziglang/zig/issues/4380 (the assertion is nearby, but there's no mention of the problem being triggered by alignment there).

Reproduction:

Copy this into a file ```bla.zig```:
```zig
const print = @import("std").debug.print;

const Bla align(16) = extern struct {
    a: u32, b: f32, c: u8
};

pub fn main() void {
    print("{}\n", @alignOf(Bla));
}
```

Try to compile:
```
> zig build-exe bla.zig
Assertion failed at /tmp/zig-20201223-21290-6b04l3/src/stage1/analyze.cpp:618 in get_pointer_to_type_extra2. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
[1]    15168 abort      zig build-exe bla.zig
```

zig version: 0.7.1+4128eea00

**Comment by SpexGuy** [comment]
Thanks for the detailed bug report!

Zig currently doesn't have a way to set the alignment of a type as a whole, instead fields need to be aligned.
`const Bla align(16) = ...` attempts to align the storage of the variable `Bla`, which doesn't have storage since it's a type.  This is likely what is causing the crash.
What you need instead is to align the first field:
```zig
const Bla = extern struct {
    a: u32 align(16),
    b: f32,
    c: u8,
};
```

**Comment by floooh** [comment]
Ah alright, thanks for the explanation! I saw this per-member-alignment while googling, but for some reason thought that this might cause padding bytes at the front of the struct :)

**Comment by mikdusan** [comment]
program with recent compiler

<details>
<summary>bla.zig</summary>

```zig
const print = @import("std").debug.print;

const Bla align(16) = extern struct {
    a: u32, b: f32, c: u8
};

pub fn main() void {
    print("{}\n", .{@alignOf(Bla)});
}
```
</details>

```sh
$ zig version
0.11.0-dev.1095+8bd734d60

$ zig run bla.zig
4
```
