### ISSUE TITLE
Allow for custom subcommands

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#7786]
For instance, on linux `git` will look in `/usr/lib/git-core` for programs named `git-*` to run as way to extend the base command. One notable example of this is `git gui`.

Sorting through the most requested issues on here, #943 and #615 are both prime targets for this functionality.

This allows for the Zig project to offload a lot of work to 3rd party projects, while still allowing tight integration with the language.

**Comment by nektro** [comment]
TIL the subcommand programs don't actually need to be in any specific folder, but just on the `$PATH`.

**Comment by andrewrk** [comment]
I don't see the benefit of this to end users. It only muddies the water between what is a third-party provided tool and what is provided by Zig. When adding a dependency on executing `zig`, it matters whether you can rely on that subcommand existing on all systems. If the subcommand is provided by a third party then it would be unwise to depend on it, unless its installation is insured.

Better to have it be clear: `zig foo` is a command provided by zig installation. Third party tools are executed with a separate command.
