### ISSUE TITLE
Proposal: @offsetOf instead of @byteOffsetOf

### ISSUE THREAD

**Issue by hvenev** [ziglang/zig#7794]
I believe that the builtin used for getting the byte offset of a struct field should be called `@offsetOf` rather than `@byteOffsetOf`. Here are a few reasons why:

- It is consistent with `@sizeOf` / `@bitSizeOf`. `@alignOf` is also not called `@byteAlignOf`.
- `offsetOf` is common in other programming languages. The C macro is called `offsetof`. There are also a few Rust libraries that provide macros named `offset_of`.
- Bit-packed structs are rare, especially dealing with pointers to individual fields.

I also believe `@offsetOf` should fail when the struct field is not aligned to a byte boundary. The most obvious reason is to prevent bugs where `@byteOffsetOf` is used without checking if the offset is actually a whole number of bytes. Having this check as a part of `@offsetOf` will make subtly incorrect code invalid and will make correct code cleaner.

Using `@byteOffsetOf` on non-byte-aligned bitfields is rarely useful, and I'd imagine that all such uses will be made more clear by doing `@bitOffetOf(T, field) / 8` instead. Even if we keep the current `@byteOffsetOf` for backwards compatibility, I believe it should be phased out.

A quick `grep` through the standard library revealed that the only uses of `@byteOffsetOf` are assertions about the layout of `extern struct`s. This can also be done with the proposed `@offsetOf` with the added advantage that if we were to make the structs `packed`, we'd automatically make sure that the fields are byte-aligned.

**Comment by faraazahmad** [comment]
I'm not too familiar with Zig yet so forgive my ignorance, but what was the reason `@byteOffsetOf` and `@offsetOf` were named so?

**Comment by hvenev** [comment]
`@offsetOf` does not exist.

**Comment by hvenev** [comment]
I've implemented the non-breaking version of this proposal at https://github.com/ziglang/zig/pull/7903.

**Comment by hvenev** [comment]
I've updated the proposal.

**Comment by andrewrk** [comment]
See also  #8642
