### ISSUE TITLE
std.os.pread() does not limit how many bytes may be transferred in one call?

### ISSUE THREAD

**Issue by jorangreef** [ziglang/zig#7805]
In `std.os`:

`read()`, `write()` and `pwrite()` all limit how many bytes may be transferred in one call:

```zig
/// Linux has a limit on how many bytes may be transferred in one `pwrite` call, which is `0x7ffff000`
/// on both 64-bit and 32-bit systems. This is due to using a signed C int as the return value, as
/// well as stuffing the errno codes into the last `4096` values. This is noted on the `write` man page.
/// The limit on Darwin is `0x7fffffff`, trying to write more than that returns EINVAL.
/// The corresponding POSIX limit is `math.maxInt(isize)`.
```

However, `pread()` has no such limit.

Is this correct?

**Comment by ifreund** [comment]
From the `read(2)` man page:
```
       On Linux, read() (and similar system calls) will transfer at most
       0x7ffff000 (2,147,479,552) bytes, returning the number of bytes
       actually transferred.  (This is true on both 32-bit and 64-bit
       systems.)
```
I'd say that `pread()` has the same limit as the others as it falls in "similar system calls".

**Comment by jorangreef** [comment]
Thanks @ifreund, I see the [man page](https://man7.org/linux/man-pages//man2/pwrite.2.html) for `pread(2)` and `pwrite(2)` does not mention the limit, but it's probably as per `read(2)`, and `std.os.pwrite()` also has the limit.

I'm happy to do a PR to add the limit to `std.os.pread()` in exactly the same way as for the others.

**Comment by LemonBoy** [comment]
No need to guess, we've been gifted with [source code](https://elixir.bootlin.com/linux/latest/source/fs/read_write.c#L490) for the Linux kernel!

**Comment by jorangreef** [comment]
And someone who knows where to look!
