### ISSUE TITLE
Is it possible to convert a std.builtin.TypeInfo.Error back to its error value?

### ISSUE THREAD

**Issue by phifty** [ziglang/zig#7825]
The struct `std.builtin.TypeInfo.Error` only contains a `name` field. And since no `@nameToError` function exists, I don't see a way to convert this to it's error value.

In version 0.6 of zig that struct has a `value` field, which holds the number to instantiate the error via `@intToError`. But that no longer exists.

Am I overseeing something?

**Comment by ifreund** [comment]
You can use `@field(MyErrorSet, "error_name")` to get an error value.

**Comment by phifty** [comment]
Nice, that was exactly what I was looking for!
