### ISSUE TITLE
Warn if a variable is never changed

### ISSUE THREAD

**Issue by atomicbitty** [ziglang/zig#7834]
It would be nice if the compiler warned us about `var`s that are never modified so that we can make them `const`s.

**Comment by tauoverpi** [comment]
Already covered by https://github.com/ziglang/zig/issues/224 though it would be slightly annoying when playing around with code samples if https://github.com/ziglang/zig/issues/3320 isn't implemented.

**Comment by atomicbitty** [comment]
In #224 the compiler would throw an error for that case, but I think an error is unnecessary and very annoying for this situation, that's why I think a warning would suffice.

**Comment by atomicbitty** [comment]
Apparenty zig doesn't have warnings, even though I don't think this is something good...
