### ISSUE TITLE
Type deduction for generics in functions

### ISSUE THREAD

**Issue by atomicbitty** [ziglang/zig#7835]
`_` could be used for deducing type arguments in functions, and an error would be thrown if this is not possible.

Example:
```
const a = [_]i32 {1, 2, 3, 4, 5};
var b = [_]i32 {0, 0, 0, 0, 0};

std.mem.copy(_, b[0..], a[0..]);
```

This would be really useful because then we don't need to remember the types of the values, and it would make code more elegant, specially for types with big names.

**Comment by zzyxyzz** [comment]
I don't have a strong preference here, but maybe

```zig
std.mem.copy(auto, b[0..], a[0..]);
```

would be more readable. BTW, `auto` is also a possible choice for replacing the disputed `anytype` (#5893) in generic functions, which would make for a nice symmetry.

**Comment by atomicbitty** [comment]
IMO I think the `_` is more consistent because it's already used to deduce the size of an array:
```
const a = [_]i32 {1, 2, 3, 4, 5};
```
And it would be less verbose.

**Comment by ifreund** [comment]
Adding type inference here removes the benefit of using the current signature of `std.mem.copy()` over, for example
```zig
pub fn copy(a: anytype, b: @TypeOf(a)) void {}
```
I see no reason to add this feature as `anytype` is already in the language.

**Comment by atomicbitty** [comment]
Yeah... this is a great solution too.

**Comment by zzyxyzz** [comment]
@ifreund, I don't think the two cases are quite equivalent. `anytype` in the function definition makes inference mandatory, while in this proposal it is optional. The benefit is that the function can expose the safer and more explicit interface, while the user can opt out of it if the required type is obvious, without losing the ability of dropping back to "manual mode" if inference fails or something else is required.

**Comment by tecanec** [comment]
I'm highly against this proposal.

This could lead to a problem comparable to what I complained about in #7758. Some lazy programmers (including my own lazy self) would be tempted to use this feature at any given chance, only to go back and spend some good minutes finding and specifying all of the non-deducable types afterward, loosing time in the long run. As one of these "victims", I'd rather that the language forces me to be more verbose from the start.

Other than (deceptively) allowing for such lazyness, there isn't much benefit to this proposal. It won't actually save that much time on most occations, types with long names can be assigned to `const`s, and the programmer is better off memorizing types than leaving them to the compiler, anyway. It's not worth the lazyness trap or the more difficult predictabillity in what works and what doesn't.
