### ISSUE TITLE
Building from source wiki page could be clearer about which stage to use for general Zig consumers

### ISSUE THREAD

**Issue by slimsag** [ziglang/zig#7837]
* Running the latest 8098b3f84cf24878e3388e056f60aba69033e0f6 built from source on Mac OS.
* Following [this wasm example](https://ziglang.org/download/0.4.0/release-notes.html#WebAssembly-Support) (is there a more recent one?)

yields a compiler codegen panic:

```
$ zig build-exe math.zig -target wasm32-freestanding
thread 4680750 panic: attempt to use null value
/Users/slimsag/Desktop/hexops/zig/src/codegen/wasm.zig:213:54: 0x1101d5f64 in codegen.wasm.Context.genCall (zig)
        const func = func_inst.val.castTag(.function).?.data;
                                                     ^
/Users/slimsag/Desktop/hexops/zig/src/codegen/wasm.zig:186:34: 0x110081488 in codegen.wasm.Context.genInst (zig)
            .call => self.genCall(inst.castTag(.call).?),
                                 ^
/Users/slimsag/Desktop/hexops/zig/src/codegen/wasm.zig:199:44: 0x10ff85301 in codegen.wasm.Context.genBody (zig)
            const result = try self.genInst(inst);
                                           ^
/Users/slimsag/Desktop/hexops/zig/src/codegen/wasm.zig:171:25: 0x10ff4e76c in codegen.wasm.Context.gen (zig)
        try self.genBody(mod_fn.body);
                        ^
/Users/slimsag/Desktop/hexops/zig/src/link/Wasm.zig:133:16: 0x10ff3b946 in link.Wasm.updateDecl (zig)
    context.gen() catch |err| switch (err) {
               ^
/Users/slimsag/Desktop/hexops/zig/src/link.zig:296:75: 0x10fe1bdd6 in link.File.updateDecl (zig)
            .wasm => return @fieldParentPtr(Wasm, "base", base).updateDecl(module, decl),
                                                                          ^
/Users/slimsag/Desktop/hexops/zig/src/Compilation.zig:1568:41: 0x10fdf0292 in Compilation.performAllTheWork (zig)
                self.bin_file.updateDecl(module, decl) catch |err| switch (err) {
                                        ^
/Users/slimsag/Desktop/hexops/zig/src/Compilation.zig:1332:31: 0x10fdea7ab in Compilation.update (zig)
    try self.performAllTheWork();
                              ^
/Users/slimsag/Desktop/hexops/zig/src/main.zig:2011:20: 0x10fd67680 in updateModule (zig)
    try comp.update();
                   ^
/Users/slimsag/Desktop/hexops/zig/src/main.zig:1852:17: 0x10fcf8e3b in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/Users/slimsag/Desktop/hexops/zig/src/main.zig:170:31: 0x10fce43e0 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
/Users/slimsag/Desktop/hexops/zig/src/main.zig:125:20: 0x10fce3499 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/Users/slimsag/Desktop/hexops/zig/build/lib/zig/std/start.zig:345:37: 0x10fce5c42 in std.start.main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x7fff67e11cc8 in ??? (???)
???:?:?: 0x4 in ??? (???)
```

**Comment by Luukdegram** [comment]
There's a few things going on here.
1. It seems to me that you're using stage2 to build the file, rather than stage 1. (perhaps you did a `zig build` inside the zig repository and then added the binary that's inside zig-cache/bin to your path, rather than what's inside the build folder (the binary created by calling `make`)). Stage2 is not ready yet to be used other than experimental usage.
2. Since you're not exposing a public `main` function, you must use `build-lib` to create your wasm module.

The `master` documentation does seem to mention that you have to call build-lib, but the example zig file remains the same: https://ziglang.org/documentation/master/#Freestanding

**Comment by slimsag** [comment]
Thanks for the help!

For some reason I wasn't able to find the doc link you sent through Google, sorry about that.

As for using stage2 - that is interesting, I followed [this wiki page](https://github.com/ziglang/zig/wiki/Building-Zig-From-Source) to build Zig from source and step 2 of that doc page led me to believe the stage2 binary is what should be used, not the C++ one:

> This produces stage2/bin/zig which can be used for testing and development. Once it is feature complete, it will be used to build stage 3 - the final compiler binary.
>
> This is the main effort of the 0.8.0 release cycle - the stage2 compiler. There are quite a few build options which can aid your development experience. Have a look with zig build --help.

Is stage1 suggested only for WebAssembly usage, or for all Zig users at the current point in time? Wondering if there's a way we can clarify these docs

**Comment by Luukdegram** [comment]
I can see the wiki being a little confusing regarding this. 

> Is stage1 suggested only for WebAssembly usage, or for all Zig users at the current point in time? Wondering if there's a way we can clarify these docs

Unless you're actively working on stage2 itself, stage1 is to be used for all your Zig usage.

**Comment by slimsag** [comment]
I updated the wiki page just now to clarify this. Thanks again for the help! https://github.com/ziglang/zig/wiki/Building-Zig-From-Source/c3f99e80774a0351ba6b028a1ec23eba2f137c3b
