### ISSUE TITLE
build-exe's -F to set compiler's -F cflag

### ISSUE THREAD

**Issue by frarees** [ziglang/zig#7838]
Using `zig build-exe -F <path>` tells the linker to use `-F <path>`.

If you use custom framework locations (e.g. `./fwk/SDL2.framework`), it would be useful to tell the compiler to `-F <path>` too, so that it can search for headers. Otherwise, you have to include them manually (e.g. `-I./fwk/SDL2.framework/Headers`).

Thoughts?

**Comment by mikdusan** [comment]
closed by #16888
