### ISSUE TITLE
Proposal: Custom Message In std.testing.expect

### ISSUE THREAD

**Issue by JDWilliamson** [ziglang/zig#7845]
As a newbie to Zig, I spent several hours today attempting to figure out what this test failure means:

```shell
Test [1/1] test "utf8"...
test failure
/usr/local/Cellar/zig/0.7.1/lib/zig/std/testing.zig:270:14: 0x102078208 in std.testing.expect (test)
    if (!ok) @panic("test failure");
             ^
/Users/**********/Developer/projects/engine/src/utf8.zig:28:15: 0x1020784d3 in test "utf8" (test)
        expect(std.mem.eql(u8, buffer[0..4], _case.expected));
              ^
/usr/local/Cellar/zig/0.7.1/lib/zig/std/special/test_runner.zig:61:28: 0x10207ad69 in std.special.main (test)
        } else test_fn.func();
                           ^
/usr/local/Cellar/zig/0.7.1/lib/zig/std/start.zig:334:37: 0x10207cb52 in std.start.main (test)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x7fff5a8083d4 in ??? (???)
???:?:?: 0x0 in ??? (???)
error: the following test command crashed:
src/zig-cache/o/43c53cf68dbc4d7f22d6d77487e570a5/test
```

It seems somewhat obvious to me in hindsight that `std.mem.eql(u8, buffer[0..4], _case.expected)` is returning false failing the expectation.

Like methods of testing in other languages (Java, Javascript, Python, to name the ones I'm most familiar with), allowing for a custom error message to be given during an expectation could make it clearer where the failure was and what expectation actually failed.

Perhaps something like:

```zig
const std = @import("std");
test "expectation test" {
  std.testing.expect(false, "Our expectation failed.");
}
```

might output

```shell
Test [1/1] test "expectation"...
test failed with message: "Our expectation failed."
/usr/local/Cellar/zig/0.7.1/lib/zig/std/testing.zig:270:14: 0x102078208 in std.testing.expect (test)
    if (!ok) @panic("test failure");

...
```

I imagine the default function would remain (for backwards compatibility as well as times when no message is desired) and given that I haven't seen default parameters or function overloads, it would probably be an additional function for each `expect*` function that would be supported.

**Comment by daurnimator** [comment]
It seems like you are looking for `std.testing.expectEqualSlices`.

**Comment by Vexu** [comment]
`std.testing.expect` now returns an error on failure which can then be handled by the caller in any way they desire.
