### ISSUE TITLE
CreateWindowEx returns null even if it succeeds

### ISSUE THREAD

**Issue by taishi132** [ziglang/zig#7851]
Creating a window with CreateWindowEx (A or W) always returns a null version of ?HWND, but apparently still successfully creates a window, as observed by:
A: The WNDPROC function that was passed is running and producing output.
B: Checking GetLastError returns a Win32Error.SUCCESS.
C: Modifying the definition of CreateWindowEx in the standard library to return a HWND instead of ?HWND lets me call ShowWindow and MessageBox (not possible without this change or release-fast since hwnd.? will panic), and produces outputs without problems.

Printing the value of the pointer also shows that it is 0. I'm just trying out the win32 api so I might have misunderstood something, but the documentation clearly states that a null HWND is an error and that you should call GetLastError, so I don't know what's going on. And it's a mystery to me how Windows somehow makes do with the null pointer I send it.

Code below if it helps:

```zig
const std = @import("std");
usingnamespace std.os.windows;
const u8to16le = std.unicode.utf8ToUtf16LeStringLiteral;

pub export fn wWinMain(
    hInstance: HINSTANCE,
    hPrevInstance: ?HINSTANCE,
    lpCmdLine: ?LPWSTR,
    nCmdShow: INT,
) callconv(WINAPI) INT {
    const wc = user32.WNDCLASSEXW{
        .style = 0,
        .lpfnWndProc = WindowProc,
        .cbClsExtra = 0,
        .cbWndExtra = 0,
        .hInstance = hInstance,
        .hIcon = null,
        .hCursor = null,
        .hbrBackground = null,
        .lpszMenuName = null,
        .lpszClassName = u8to16le("Test Window"),
        .hIconSm = null,
    };

    _ = user32.RegisterClassExW(&wc);

    const hwnd = user32.CreateWindowExW(
        0,
        wc.lpszClassName,
        wc.lpszClassName,
        user32.WS_OVERLAPPED,
        0,
        0,
        640,
        480,
        null,
        null,
        hInstance,
        null,
    );

    std.log.err("{}", .{hwnd.?});
    if (hwnd) |window| {
        _ = user32.ShowWindow(window, nCmdShow);
        _ = user32.MessageBoxW(window, u8to16le("hello"), u8to16le("title"), 0);
    } else {
        const err_code = kernel32.GetLastError();
        std.log.err("{}", .{err_code});
    }
    return 0;
}

pub export fn WindowProc(
    hwnd: HWND,
    uMsg: UINT,
    wParam: WPARAM,
    lParam: LPARAM,
) callconv(WINAPI) LRESULT {
    std.debug.warn("In WindowProc\n", .{});
    return 0;
}

```

Output:
```
In WindowProc
In WindowProc
In WindowProc
error: HWND@0
error: Win32Error.SUCCESS
```

**Comment by LemonBoy** [comment]
Not a Zig problem, your `WindowProc` is ignoring all the messages sent to it. 
Replace `return 0` with `return user32.DefWindowProcW(hwnd, uMsg, wParam, lParam);` and enjoy your window.

**Comment by taishi132** [comment]
Thanks, that fixed it. Sorry for wasting your time with user error unrelated to zig. I would still label this behaviour as a bug though, just not a zig bug.
