### ISSUE TITLE
Error messages should use a mutex

### ISSUE THREAD

**Issue by tecanec** [ziglang/zig#7859]
The compiler recently gave me this mess as part of an error message:
```
Segmentation fault at address 0x7ff651e04988
reached unreachable code
C:\[path to my project]\src\asset manager.zig:408:53: 0x7ff651e04988 in asset manager.init (dual soul game.obj)
    full_mC:\[path to my compiler]\zig-windows-x86_64-0.6.0+352976ed2\lib\zig\std\debug.zige:t225ad:14ata : = 0xt7ff651d61708r in ystd.debug.assert  (adual soul game.objl)loc
. a l l oifc ((*!Assoekt)Met audnatreacah,a btlrey ;st r/eam/.re adaLeb128(s)s)e;r
tio                                                    n^ f
ailure
             ^
```
The cause of this mess is obvious: Multiple threads are crashing at the same time, and are all trying to talk to me at once instead of taking turns. This could be easily solved with a mutex.

Normally, using a mutex without the user's consent could be a problem, but in this case, the entire program is likely to fall apart, anyway, so waiting wouldn't be too much of a problem. However, we could still consider using the same mutex for printing in non-fatal scenarios. If this were to be done, I'd suggest making this an option for the user. Obviously, no mutex would be used for any of this if the whole build is single-threaded.

**Comment by LemonBoy** [comment]
The panic handler is already thread-aware, the problem here is that the segfault handler `handleSegfaultWindows` is doing its own thing with `stderr` without synchronizing anything with anyone.
