### ISSUE TITLE
Lazy evaluation of @import validation

### ISSUE THREAD

**Issue by vkcz** [ziglang/zig#7867]
The error `unable to find ...` from a `@import("file_that_does_not_exist")` is only produced when things from the import are used, e.g.

```zig
const mylib = @import("nonexistent");

pub fn main() void {
}
```

Compiling gives no errors, but if the source is changed to

```zig
const mylib = @import("nonexistent");

pub fn main() void {
    mylib.someFunc();
}
```

then there's the error

```
./src/main.zig:1:15: error: unable to find 'nonexistent'
```

Maybe there's a good reason for lazy evaluation in this case.
I think, however, that if there's a clear error in the code, it should be shown to the user as soon as possible.

**Comment by g-w1** [comment]
Everything in zig is lazy. If you make a function that makes 0 sense, but dont do anything with it, it will compile. See #2529

**Comment by andrewrk** [comment]
As of #8554, self-hosted Zig will report file not found errors for `@import` expressions with non-existing files, as well as other AstGen errors, which is a pretty nice mapping to "clear error in the code".

This issue will never be addressed in stage1.

In other words, you got your wish, but you won't get the benefits until self-hosted is done.
