### ISSUE TITLE
Underaligned u32 in struct with u16 causes assertion failure

### ISSUE THREAD

**Issue by SpexGuy** [ziglang/zig#7868]
```zig
// repro.zig
const T = struct {
    a: u32 align(2),
    b: u16,
};

export fn foo() void {
    var f: *const T = undefined;
}
```
Fails on 0.7.1 and godbolt master.
```
Assertion failed at /home/vsts/work/1/s/src/stage1/analyze.cpp:8697 in resolve_llvm_types_struct. This is a bug in the Zig compiler.thread 7 panic: 
Unable to dump stack trace: debug info stripped
Compiler returned: 255
```

**Comment by LemonBoy** [comment]
That should trigger a compile error as you can't under-align fields in a regular non-packed struct

**Comment by SpexGuy** [comment]
Is there a reason this is the case?  It seems like a feature that should work.  Even C# can do it: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.structlayoutattribute.pack?view=net-5.0

**Comment by LemonBoy** [comment]
On second thought specifying a smaller alignment value is effectively a no-op, isn't it?
`u32` is aligned to 4bytes thus every offset will also be a multiple of 2.

**Comment by LemonBoy** [comment]
C# `pack` annotation is sligthly different:

```csharp
[StructLayout(LayoutKind.Sequential, Pack=2)]
struct ExampleStruct
{
   public byte b1;
   public byte b2;
   public int i3;
}
```

This structure occupies 6bytes and the `int` field ends up with offset `0x2`, making it unaligned.
The assertion error is the result of a mismatch between the offset assigned by Zig and the one assigned by LLVM to the same field. This is a LLVM limitation (?) as non-packed structures use the type ABI alignment and that's it, we can get away with over-aligning the fields by inserting extra padding but that's it, we can't reduce the type footprint unless we switch to a packed layout.

**Comment by SpexGuy** [comment]
If it were a noop then the compile error makes sense.  What I wanted here was a struct that was 2-byte aligned, but contained a u32, and for the compiler to generate instructions to do two 16 byte reads on targets where unaligned reads aren't supported.  Maybe I should be using packed for that?  I'm worried that if I do, I will accidentally end up with bit-packed items, which is not what I want.  But if I'm careful my code does seem to work if I switch everything to packed.

**Comment by mikdusan** [comment]
- latest compiler no longer asserts
- appears that somewhere between 0.9.0 and 0.10.0 this was fixed

<details>
<summary>repro.zig</summary>

```zig
const T = struct {
    a: u32 align(2),
    b: u16,
};

export fn foo() void {
    var f: *const T = undefined;
    _ = f;
}
```
</details>

```sh
$ uname -a
Linux archlinux 6.1.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 31 Dec 2022 17:40:35 +0000 x86_64 GNU/Linux

$ zig version
0.11.0-dev.1239+7a2d7ff62

$ zig build-obj repro.zig
# no stdout/stderr (good)
```
