### ISSUE TITLE
Add ctags implementation

### ISSUE THREAD

**Issue by steveno** [ziglang/zig#787]
I think adding a parser to ctags would be a good step for zig. I'd be willing to help whip up something basic if someone wants to "mentor" me.

https://github.com/universal-ctags/ctags

**Comment by andrewrk** [comment]
I'd be happy to mentor this. What approach do you plan to take?
 * update ctags to support zig syntax
 * (discouraged) improve c++ zig compiler and add feature for outputting ctags file
 * improve self hosted compiler parser and add a feature for outputting ctags file

**Comment by steveno** [comment]
My initial plan was to fork ctags and begin adding a parser to it. When it reached a level you were happy with we could open a pull request. I've worked on that project a (very) small amount before so I'm sure they would accept the contribution if it's up to snuff.

**Comment by andrewrk** [comment]
Sounds like a good plan to me. Here are some resources:

 * informal grammar description: https://ziglang.org/documentation/master/#Grammar
 * [c++ tokenizer implementation](https://github.com/zig-lang/zig/blob/master/src/tokenizer.cpp)
 * [self hosted tokenizer implementation](https://github.com/zig-lang/zig/blob/master/std/zig/tokenizer.zig)
 * [c++ parser implementation](https://github.com/zig-lang/zig/blob/master/src/parser.cpp) 
 * [self hosted parser implementation](https://github.com/zig-lang/zig/blob/master/std/zig/parser.zig)

A couple more notes:
 * The syntax of zig is still not stabilized. It is likely to change, perhaps even drastically in the next few releases.
 * One approach you could take is to create a zig project which takes the self hosted parser/tokenizer from the standard library and exports a C API on top of that. Then ctags could add a (optional) dependency on that library for zig support.

**Comment by isaachier** [comment]
I was just looking into this. The parsers range in complexity. For example, compare Myrrdin's parser with the C++ parser. Easiest for now might be to make a zig implementation using existing parser and then port to C once language stabilizes.

**Comment by isaachier** [comment]
I got something up and running. Needs a bit more work, but here it is: https://github.com/isaachier/ztags.

**Comment by andrewrk** [comment]
well done!

**Comment by andrewrk** [comment]
@isaachier want to start a wiki page for zig projects so that your project can get some visibility?

**Comment by isaachier** [comment]
Good idea. I'll do that now.

**Comment by watzon** [comment]
I added instructions to the [tagbar wiki](https://github.com/majutsushi/tagbar/wiki#zig) and referenced ztags in there.

**Comment by pierre-rouleau** [comment]
@andrewrk Is ztag still the way to go for current Zig?  The site states that only version 0.13 is supported and I can build it with 0.15.1:

```
>0@11:42:33 L3 :[~/my/dvo/zig-repos/ztags]  git:(master)ztags                                                                                                               
zsh% zig build                                                                                                                                                                             
/Users/roup/my/dvo/zig-repos/ztags/build.zig.zon:2:13: error: expected enum literal                                                                                                        
    .name = "ztags",                                                                                                                                                                       
            ^~~~~~~                                                                                                                                                                        
>1@11:59:02 L3 :[~/my/dvo/zig-repos/ztags]  git:(master)ztag
```
