### ISSUE TITLE
Ship zig as a single executable on Windows

### ISSUE THREAD

**Issue by simonvanbernem** [ziglang/zig#7872]
Hi, I am not a zig-user (yet), but wanted to play around with the compiler a bit. The "question everything" nature of zig really appeals to me, and since I saw zig do a common thing that really annoys me, I thought I'd question that here:

Right now the download on windows includes basically 4 items:

- the compiler executable
- the language reference
- the license
- the standard library

**Can this be reduced to just the executable?**

- the full license can be made a command-line option, and a shorthand (MIT (c) Andrew Kelley) can be printed when the compiler is called without arguments, or with help. Unless there are legal reasons to make this a separate file, I don't see why its necessary to have it be one, besides convention.
- the language reference could be hidden behind a command line option aswell, that ouputs the html file, or alternatively just have a link (although its really valuable to have the language reference completely offline!).
- The standard library. This is the big one that got me to question the whole thing in the first place, because this thing causes an actual annoyance: The fact that there are close to 10.000 files in it makes handling zig on disk super slow. Unpacking the 50 MB archive on an NVME SSD takes 6 seconds. Copying to a HDD takes closer to a minute. Compared to every other compiler this is still super fast, but compared to what it can (should?) be, its really slow. If the standard library was embedded in the data-segment of the compiler, this issue would simply not exist. I guess you want people be able to look at the implementation, and possibly update it without updating the compiler (?), but again, the executable could generate the files on request, and take a parameter to a folder that overrides the embedded standard library.

If all the other files were eliminated, you would also gain a nice advantage: You wouldn't even need an archive! You could just download the exe and be done.

**I am not saying that what I'm outlining here is necessarily better** than what is in place right now (I am new to the project and don't know the tradeoffs well). Maybe having the standard library and language ref right there in plain sight is worth a lot more than the occasional annoyance of moving a folder instead of an executable, but since I couldn't find any existing debate about this, I thought I might aswell start one.

**Comment by jayschwa** [comment]
> since I saw zig do a common thing that really annoys me

Do you have examples of projects that don't do this? I'd be curious to see how they work.

> Unpacking the 50 MB archive on an NVME SSD takes 6 seconds.

I think this is unavoidable. The windows distribution is over 200 MiB uncompressed, which is not download-friendly. If the executable and embedded files are compressed, then every invocation will have decompression latency. I experimented with [AppImage](https://appimage.org/) on Linux and it has the same problem.

**Comment by simonvanbernem** [comment]
> Do you have examples of projects that don't do this? I'd be curious to see how they work.
I don't know of any compilers that ship as a single executable.

>I think this is unavoidable.
This definitely is avoidable! The 6 seconds are basically entirely spent on creating the 10.000 files, not decompressing the data. So if the standard library was embedded in the exe, and the exe was zipped, you would have small size with basically instant decompression (and copying on harddrives). The problem is entirely the number of files, not the size.

**Comment by SpexGuy** [comment]
Most of those files come from the various implementations of libc.  I think embedding those libc files into compressed blobs in the executable and unzipping them as needed into the global zig-cache would be a reasonable thing to do.  IMO we should still keep the zig standard library in source form, but that's very small in comparison.

**Comment by simonvanbernem** [comment]
Is it necessary to have these files on disk? Does LLVM (or the other backends) not provide a way to hand file contents as memory buffers instead of paths? Because effectively caching the files would just be a roundtrip from memory to file system back to memory. I suspect bypassing the filesystem would also improve compile-times.

**Comment by mikdusan** [comment]
This is very interesting and probably possible given a blank cheque to underwrite development. Could zig compile from embedded source .zig, .c, .cpp and .h files? Probably. If they were uncompressed the performance would probably beat any posix filesystem. The exe would only _look_ huge. `zig build-obj`, `zig cc` would get faster when embedded `std` and libc is used.

It would likely introduce a need to run with an unembedded-option, at least for maintainers. And then there's that extra difference between how maintainers use it vs users. Oh and then there's issues of `zig cc`, dependency file generation, and the plethora of existing projects that would break because they're not expecting `zig.exe` to be a dependency for `main.c` that includes `<stdio.h>` .

This looks like there would be a lot of surprising extra work to make it happen and imo isn't justified by the convenience/potential-perf boost.

**Comment by marler8997** [comment]
Would be interesting to get a prototype going to see how much performance gain could be had from this.  This idea increases complexity (because we still have to support the current use case along with a new use case) but complexity can be justified if there is enough benefit.

**Comment by SpexGuy** [comment]
Maybe, but also remember that the executable itself has to get loaded off the file system on every run.  Given that, maybe the libc's should be in a few large compressed files that are separate from the executable?

**Comment by mikdusan** [comment]
Pretty sure an exe text is demand-loaded on page sizes. Maybe some hinting.

**Comment by tecanec** [comment]
I like having stdlib as a regular folder with zig-files. It allows me to look at the source whenever I want, and it makes it feel less like a part of zig and more like an accessory, which is something that I really like about it. It even allows for easy patching. As much as I'd normally favor single-file programs, I think that I'd prefer that the library specifically stays as it currently is as opposed to being embedded into the compiler's data segment.

**Comment by wizzard0** [comment]
Well... less radical option would be to be able to resolve files to zip archives, if said file was not found on disk (like java jars vs folders of .class-files). 

One particular cross-platform use case is speeding up CI builds that tend to completely rebuild environment afresh first.

This will add a lot of nontrivial complexity with filename resolution though, so should not be taken lightly.

**Comment by jbsolomon** [comment]
it's not just about the potential performance boost -- an "embedded mode" is certainly appealing for distributing it on mobile or other platforms that might have unusual, slow, or otherwise difficult filesystems / file devices.

on that note, it would also be great to be able to use zig as a library instead of having to use the executable... not sure whether that's feasible yet

**Comment by simonvanbernem** [comment]
> Well... less radical option would be to be able to just be able to resolve files from zip archives, if said file was not found on disk (like java jars vs folders of .class-files), like @SpexGuy said.

Reading directly from zip archives seems like a very nice 90% solution. Maybe this could also help on other fronts than the stdlib? Downloading a repo as zip and building it directly seems kind of cool, or having large resource files in zips (if resolving paths to archives was a general thing the compiler could do).

Not sure how relevant those scenarios are to the userbase though.

**Comment by gonzus** [comment]
You could also consider putting everything into an SQLite file. This sort of thing is one of the common SQLite use cases.

**Comment by andrewrk** [comment]
Making the judgement call here for simplicity's sake: the zig compiler installation will be composed of only uncompressed source files, same as status quo. Maybe some day before we all perish Microsoft improves their file system, until then, 6 seconds SSD, 60 seconds HDD it is to unzip a zig binary installation on Windows.

**Comment by andrewrk** [comment]
Possibly related: https://gregoryszorc.com/blog/2021/04/06/surprisingly-slow/
It might be Windows doing virus scanning on CloseHandle. In which case the best solution is for Microsoft to stop doing that, or to make their zip file extractor use the workarounds listed in the article, or for zig users to use a different zip extractor that employs such workarounds. Either way, I remain satisfied with leaving this issue closed.
