### ISSUE TITLE
Compiler error reading array member in a packed struct

### ISSUE THREAD

**Issue by croscato-zz** [ziglang/zig#7873]
When compiling the code bellow the compiler is **terminated unexpectedly**.

It works fine if **struct Data** doesn't have the **packed** attribute.

```zig
const std = @import("std");
const print = std.debug.print;

const buffer = "\x00name1\x08name2\x0aname3";

pub fn main() anyerror!void {
    const kItemCount = 3;

    const reader = std.io.fixedBufferStream(buffer).reader();

    // if the packed attribute is removed the code works fine
    const Data = packed struct {
        offset: u8,
        name: [5] u8,
    };

    var data: [kItemCount] Data = undefined;

    for (data) |*item| {
        item.*.offset = try reader.readByte();

        _ = try reader.read(item.name[0..]);
    }

    for (data) |item| {
        print("{d}: {s}\n", .{item.offset, item.name});
    }
}
```

**Compiler output**
zig...The following command terminated unexpectedly:
/usr/bin/zig build-exe /home/croscato/zig/src/main.zig --cache-dir /home/croscato/zig/zig-cache --global-cache-dir /home/croscato/.cache/zig --name zig --enable-cache
error: the following build command failed with exit code 11:
/home/croscato/zig/zig-cache/o/5fdad8b987391d7bfd65bb86c20c0263/build /usr/bin/zig /home/croscato/zig /home/croscato/zig/zig-cache /home/croscato/.cache/zig

**Compiler version**
0.8.0-dev.1040+843d91e75

**Comment by rgreenblatt** [comment]
Strange things also hapen to the size:
```zig
const std = @import("std");

const len = 12;

const Inner = packed struct {
    vals: [len]u8,
};

pub fn main() void {
    std.debug.print("actual {}, expected {}\n", .{ @sizeOf(Inner), len });
}
```
```
actual 16, expected 12
```

**Comment by fengb** [comment]
Packed structs are buggy and tries to pad to the nearest power of two. https://github.com/ziglang/zig/issues/2627

**Comment by Vexu** [comment]
Arrays are no longer allowed in packed structs.
