### ISSUE TITLE
"'comptime_int' must be const or comptime" is confusing

### ISSUE THREAD

**Issue by vkcz** [ziglang/zig#7875]
I write
```zig
fn main() {
    var i = 6;
}
```
and I get
`error: variable of type 'comptime_int' must be const or comptime`

The way I interpret this: Zig inferred type `comptime_int` for `i`, because I assigned the literal `0`. Zig then gives an error because declaring `i` with `var` (such that it could `var`y) would violate the principle that `comptime_int`s must be `const` or `comptime`, because otherwise, it wouldn't fit the definition of a `comptime_int`.
But I declared `i` as a `var` for a reason—I intend to have it vary (well, not in this minimal example, but in a more serious case).
So shouldn't Zig just disregard that `i` can be a `comptime_int`, and instead just have it be the default integer type, so as to allow the `var`iability of `i`?

I'm somewhat new to Zig; maybe I'm missing something important about `comptime`—but it doesn't make sense to break type inference (the error says I must specify an explicit fixed-size number type) to make variables `comptime_int`s when they're, from the declaration, *shown to be intended to vary*.

**Comment by daurnimator** [comment]
>  instead just have it be the default integer type

Zig purposefully has no default integer type.
You must pick the type yourself, e.g. `var i: u32 = 6`

**Comment by vkcz** [comment]
> Zig purposefully has no default integer type.
It seems this invalidates the issue.
