### ISSUE TITLE
Unknown format string 's' (confusing error message)

### ISSUE THREAD

**Issue by vkcz** [ziglang/zig#7876]
A (very simplified variant of a) portion of my program:
```zig
std.debug.print("{s}", .{10});
```
This gives an error
```
Unknown format string: 's'
```
along with a long and complicated other error and around ten `note: called from here`.

Changing the `.{10}` to `.{"hello"}` makes the program work fine—so clearly, it's not that `s` is an unknown format string.
The problem is that *10 (an integer) is the wrong type for the format specifier (for strings)*.
This should be reflected in the error message—and the error message should be shorter/less cluttered.
I suspect a similar problem may apply with some other format string/type combinations.

**Comment by mikdusan** [comment]
Generally it is the _type_ (in this case that is the `10`) that dictates which format specifiers are available. Isn't the real problem that `{s}` is wrong and it should be `{d}` or any other integer-related spec?

Along that direction, the error could be improved a great deal by inserting one word:

```
Unknown integer format string: 's'
```

**Comment by vkcz** [comment]
> ```Unknown integer format string: 's'```

Were this to be done for all possible bad type-specifier combinations (there are probably quite a few), that would require designing special-case wording for each possible type category.

What may be better/easier would be making the message

```
Unknown format string, or incorrect type (type is <type of argument>): 's'
```

**Comment by g-w1** [comment]
Right now, each type has its own format function, with its own error, so it would be *very* easy to just add it there.
https://github.com/ziglang/zig/blob/master/lib/std/fmt.zig#L612-L662
```diff

    } else {
-        @compileError("Unknown format string: '" ++ fmt ++ "'");
+        @compileError("Unknown integer format string: '" ++ fmt ++ "'");

    }
```
