### ISSUE TITLE
proposal: enforce files to be `opaque` but add default `pub`

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#7881]
this rides off the back of #6617 but provides a new solution that also makes Zig simpler while allowing more freedom and explicitness.

many Zig projects, including Zig itself, take advantage of the side effect that files are processed as structs to reduce the amount of characters needed to be able to do something along the lines of `const Compilation = @import("Compilation.zig");`. However, this shortcut is inconsistent, requires this knowledge of the compiler internals, and only works with `struct`s.

But the idea of a file representing a single unit of code is very common and in that very same file, we have `const Value = @import("value.zig").Value;` and `const Type = @import("type.zig").Type;` because the main value of those files is an `extern union` and not a `struct` so the bare import trick doesn't work.

The syntax would roughly look like `pub default <const|var> <expression>;`. Other `pub`s in the namespace would be compile errors.

Ideally, this proposal would also enforce #6617 getting accepted, but offers a solution that allows all the following to work:
- `const Compilation = @import("Compilation.zig");`
- `const Value = @import("Value.zig");`
- `const Type = @import("Type.zig");`

since you would be able to default export any type, whether it be a `struct`, `union`, `enum`, `fn`, etc.

Compilers don't need files to make a program, but they're critical for the human organization of code.

So parsing this file would look like reading the top level declarations, if a default pub is found, then the type of the file is the value of the expression, otherwise the file is an opaque type with the discovered declarations.

**Comment by g-w1** [comment]
One thing that this doesn't consider is this top-level syntax for structs
```zig
x: u32,
y: usize,
<some functions>
```
Now, everything must have at least one level of indentation, which can hinder readability.
```zig
pub default const struct {
    x: u32
    y: u32
    <functions>
};
```

**Comment by nektro** [comment]
> Now, everything must have at least one level of indentation, which can hinder readability.
I would argue the exact opposite, given the reasoning I listed in the issue.

**Comment by EleanorNB** [comment]
While I do appreciate ##6617, I don't see what's wrong with `@import("type.zig").Type`. Sure, it's a bit more typing (zing!), but it gets the job done and it's clear.

**Comment by EleanorNB** [comment]
If we're picking one, I vote the latter. Less to remember that way.

**Comment by mikdusan** [comment]
_if_ we were looking to complete the trifecta, I'd prefer syntax like so:
```zig
// this file body is a struct
@This() = struct;

// a union(enum)
@This() = union(enum);

// an enum
@This() = enum;
```

**Comment by nektro** [comment]
@mikdusan that is very unpragmatic code. you can't assign to a function call.

**Comment by g-w1** [comment]
Yes you can:
```zig
@field(obj, "str") = true;
```

**Comment by mikdusan** [comment]
yes, `@field()` is the perfect example of a builtin used as lvalue.

**Comment by asa-z** [comment]
A  use case for this is library-level parameters. Your package root can then be a function, which takes the library level parameters, without having to come up with a name for it.
