### ISSUE TITLE
std.json can't handle large integers

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#7901]
Currently `std.json` can't handle integers larger than `i64`.

## My Use Case

I'm working on autogenerated Win32 zig bindings from a JSON source.  In this file (https://github.com/marlersoft/win32json/blob/main/api/Js.json), the constant value for `JS_SOURCE_CONTEXT_NONE` is a number that cannot fit into an `i64`, namely, `18446744073709551615`.

**Comment by mrakh** [comment]
Per RFC 7159, JSON parsers are allowed to set limits on the range and precision of accepted numbers, and setting the integer limit to the max word value of the architecture (2^64 - 1) is a common convention of JSON implementations in low-level languages.

**Comment by marler8997** [comment]
Well I'm not generating the data, it's generated by microsoft so I can't really "change it".  It's representable with a `u64`, so we could make it a union like this:
```
const JsonInteger = union(enum) {
    I64: i64,
    U64: u64,
};
```
Maybe I'll create a PR for that.

**Comment by SpexGuy** [comment]
Javascript doesn't have integers, only double floats, so integer values above +/-2^53 - 1 may not be preserved correctly in many json implementations.  If your goal is to be compatible with json parsers that aren't the Zig stdlib, consider using strings for these values instead.

**Comment by marler8997** [comment]
@SpexGuy that's a good suggestion, maybe I'll do that

**Comment by daurnimator** [comment]
Are you referring to the non-streaming parser under `json.Parser`? https://github.com/ziglang/zig/blob/236db6232fa2beb97c47e3f1edcdb2a29e59d160/lib/std/json.zig#L2095

If you instead use `json.parse` it should support all zig integer types. https://github.com/ziglang/zig/blob/236db6232fa2beb97c47e3f1edcdb2a29e59d160/lib/std/json.zig#L1410

See also #5326

**Comment by marler8997** [comment]
@daurnimator it looks like that function is for deserializing JSON into a type?  How would that work for parsing a file like this? https://github.com/marlersoft/win32json/blob/main/api/Js.json

**Comment by daurnimator** [comment]
> @daurnimator it looks like that function is for deserializing JSON into a type?

Yes

> How would that work for parsing a file like this? https://github.com/marlersoft/win32json/blob/main/api/Js.json

Create a zig type with that structure.

```zig
const T = struct {
  Constants: []struct {
    Name: []const u8,
    Type: struct {
      Kind: []const u8,
      Name: []const u8,
    },
    Value: u64,
    Attrs: []Attr,// something here
  },
  Types: []struct {
    Kind: []const u8,
    Name: []const u8,
    Values: []struct {
      Name: []const u8,
      Value: ???, // this is where you probably need #5326
    },
  },
  Functions: ........ // etc
};
```

**Comment by marler8997** [comment]
it'll need to support union types and recursive types
```
// some how need to tell it to switch on the "Kind" field?
const Type = union(enum) {
    Native: struct {
        ...
    },
    ApiRef: struct {
        ...
    }
    PointerTo: struct {
        Child: Type, // this won't compile because it's a recursive type, how would this work?
    }
    ...
};

const T = struct {
    Constants: []struct {
        Name: []const u8,
        Type:
    },
}

```

**Comment by marler8997** [comment]
Also I'm not sure using this would even solve the problem.  Some integers are `i64` and some are `u64`, `parseInt` can't support both as far as I know.

**Comment by daurnimator** [comment]
> EDIT2: actually if union types are supported, then I should be fine because the "Kind" is different for `Int64` and `UInt64`.

With #7922 you could use the kind field to pick a value type:
```zig
const std = @import("std");

test "json union" {
    const T = union(enum) {
        foo: struct {
            comptime kind: i32 = 0,
            b: bool,
        },
        bar: struct {
            comptime kind: i32 = 1,
            b: f64,
        },
    };

    const r = try std.json.parse(T, &std.json.TokenStream.init(
        \\{
        \\  "kind": 1,
        \\  "b": 1.0
        \\}
    ), .{});
}
```

**Comment by marler8997** [comment]
@daurnimator yeah I think you're right, very cool
