### ISSUE TITLE
Building zig compiler on Fedora

### ISSUE THREAD

**Issue by gegogi** [ziglang/zig#7916]
Because of this change in Fedora (https://fedoraproject.org/wiki/Changes/Stop-Shipping-Individual-Component-Libraries-In-clang-lib-Package), it's not super easy to build zig source on Fedora.
I found this (https://copr.fedorainfracloud.org/coprs/sentry/zig/) finally, but it took some time for me to figure out why I need this from the cmake error (CLANG_LIBRARIES missing) even after installing clang-devel package on Fedora.
Is there a way to fix this by modifying CMakeList.txt? It looks like Fedora is shipping the aggregated version of clang libs.

**Comment by Vexu** [comment]
Passing  `-DZIG_PREFER_CLANG_CPP_DYLIB=on` to cmake should fix this.

**Comment by gegogi** [comment]
Thanks. I found this information on Troubleshooting page of Wiki. (https://github.com/ziglang/zig/wiki/Troubleshooting-Build-Issues)
But it would be more helpful to people if the page also mentions the change since Fedora 32.

**Comment by Vexu** [comment]
I added a note for Fedora 32+ to the wiki.
