### ISSUE TITLE
proposal: documentation tests

### ISSUE THREAD

**Issue by g-w1** [ziglang/zig#7923]
# Documentation Testing

In Rust, it has [documentation testing](https://doc.rust-lang.org/rust-by-example/testing/doc_testing.html) where you can do something like this:
```rust
/// Removes consecutive repeated elements in the vector according to the
/// [`PartialEq`] trait implementation.
///
/// If the vector is sorted, this removes all duplicates.
///
/// # Examples
///
/// ```
/// let mut vec = vec![1, 2, 2, 3, 2];
///
/// vec.dedup();
///
/// assert_eq!(vec, [1, 2, 3, 2]);
/// ```
#[stable(feature = "rust1", since = "1.0.0")]
#[inline]
pub fn dedup(&mut self) {
    self.dedup_by(|a, b| a == b)
}
```

When testing it will run the test above the function, but also will show it in the examples section like this:
![image](https://i.imgur.com/IG3jUIg.png)

I propose something like this for Zig, but less clumsily. I do not like the Rust way, because you are writing markdown above the the function, not actual code. I still like the idea though.

A test block will have the grammar, `TestDecl <- KEYWORD_test (STRINGLITERALSINGLE / IDENTIFIER)? Block`

To test a function do:
```zig
pub fn add(a: u32, b: u32) {
    return a + b;
}

test add { // add is a reference to the add function
    assert(add(1, 2) == 3);
    assert(add(5, 2) == 7);
}
```

Then, this will render in the docs below the function as an example, but is also tested, making sure the docs are keeping up with the implimentation.

If someone just wanted to test a function without it showing up in the docs (maybe a test with a lot of lines) they could use 
```zig
test "thing" {
}
```
syntax still.
To test types, modules, files you can put a type after `test`:
```zig
const T = @This();
test T {
    const i = T{};
    // do things with i
}
```

and,
```zig
test {
}
```
will still work.

**Comment by matu3ba** [comment]
> Then, this will render in the docs below the function as an example, but is also tested, making sure the docs are keeping up with the implimentation.

Can you add and conditionally clarify, if modules should also work as another proposal?
That is a common use case, if tests are very long or have special build logic.
Then one wants to invoke the method from another file with something like
```zig
test anotherscope.add { // add is a reference to the add function of another scope (file,struct etc)
    assert(add(1, 2) == 3);
    assert(add(5, 2) == 7);
}
```

**Comment by nektro** [comment]
no, `test add {` decls should be inside `anotherscope`

**Comment by g-w1** [comment]
This will not work, the item after test needs to be an `IDENTIFIER`.

**Comment by tauoverpi** [comment]
Would be nice if doc comments on doc tests were allowed and rendered as a text above the example block but  after the doc comment on the decl. 

Consider the following,

```zig
/// # VT220
/// Some text about the parser
const Parser = struct { ... };

/// ## VT220 cursor movement
/// introduction to the section, this is appended to the doc comment on `Parser`
///
/// some text:
/// As an example, moving the cursor to a given position within the document is done through
/// an escape sequence ending in `'H'` where, unless coordinates are specified, will move the
/// cursor to position 1:1 which is at the top of the buffer.
///
/// The doc test below follows the text within this doc comment
test Parser {
    try testParse("\x1b[H", &.{.{ .cursor_move = .{ .line = 1, .column = 1 } }});
    try testParse("\x1b[22;22H", &.{.{ .cursor_move = .{ .line = 22, .column = 22 } }});
}

/// The text here comes after the doc test above but before the doc test below.
///
/// Some more text:
/// It's also possible to move relative to the current cursor position using the arrow keys
/// through bracket escape sequences `'A'...'D'`.
test Parser {
    try testParse("\x1b[A", &.{.{ .cursor_up = 0 }});
    try testParse("\x1b[B", &.{.{ .cursor_down = 0 }});
    try testParse("\x1b[C", &.{.{ .cursor_right = 0 }});
    try testParse("\x1b[D", &.{.{ .cursor_left = 0 }});
}
```

My main interest is the ability to write a guide/tutorial within the documentation framework without having to use a separate literate programming tool.
