### ISSUE TITLE
Compiler SIGKILL/crash when returning from a function with the return type `noreturn` 

### ISSUE THREAD

**Issue by CoolRustacean** [ziglang/zig#7928]
The following code caused the compiler to send a SIGKILL to itself on my computer, and [crashed the compiler on godbolt.org](https://godbolt.org/z/oTjsYo):
```zig
fn a() !noreturn {
    return;
}

pub fn main() void {
    var b = a() catch unreachable;
}
```
Of course, the above program is ill-formed, yet the compiler accepts it.

Moreover, using `noreturn` in an error union with an inferred error set should be illegal.

**Comment by rohlem** [comment]
Probably related (maybe duplicate?) to #3263 .

> Moreover, using noreturn in an error union should be illegal.

`e!noreturn` has real uses (f.e. [here](https://github.com/ziglang/zig/issues/3257#issuecomment-542846671)), it means the function can either return an error value from `e`, or never return to the caller.
Constructing an error union value by (compatible) error value always works, and doesn't interact with the payload type in any way.
The only illegal behaviour in this code seems to me that the function returns not an error, but trying to instantiate the type `noreturn`. (That said, quite likely that `!noreturn` is majorly broken in the compiler though.)

**Comment by CoolRustacean** [comment]
> Probably related to #3263 .
> 
> > Moreover, using noreturn in an error union should be illegal.
> 
> `e!noreturn` has real uses (f.e. [here](https://github.com/ziglang/zig/issues/3257#issuecomment-542846671)), it means the function can either return an error value from `e`, or never return to the caller.
> Constructing an error union value by (compatible) error value always works, and doesn't interact with the payload type in any way.
> The only illegal behaviour in this code seems to me that the function returns not an error, but trying to instantiate the type `noreturn`. (That said, quite likely that `!noreturn` is majorly broken in the compiler though.)

IMO `!noreturn` should be disallowed. If a function does not return under normal conditions, the abnormal conditions should be clear.

**Comment by CoolRustacean** [comment]
This is almost definitely a duplicate of #3263, and certainly a duplicate of #4698, which is itself a duplicate of #3263.
