### ISSUE TITLE
Compiler exits in the middle of compilation with complex u0 expression

### ISSUE THREAD

**Issue by SpexGuy** [ziglang/zig#7953]
```zig
// repro.zig
fn func() u0 {
    return 0;
}
test "tiny" {
    var x: u0 = 0;
    x &= ~func();
}
```
```sh
> zig version
0.8.0-dev.1065+290efc074

> zig test repro.zig
Semantic Analysis [915/1313]

> echo %ERRORLEVEL%
-1073741819
```
Something super weird is going on here.  When I reduced this, the function call, the `&`, and the `~` all seemed necessary.  Remove any one of them and it compiles just fine.

**Comment by LemonBoy** [comment]
`ir_gen_negation` (swap the `~` with a `-%`) and `ir_render_binary_not` must take into account the possibility of `ir_llvm_value` returning `nullptr` for zero-sized operands.

Thought for stage2: A lot of this zero-sized tomfoolery could be handled at the Zir level, the whole chain of operations on `u0` can be safely elided and the only remaining part is calling `func()` for its side-effects.

**Comment by mikdusan** [comment]
compiler no longer exits in the middle of compilation and test passes

```sh
$ zig version
0.11.0-dev.1026+4172c2916

$ zig test --zig-lib-dir lib repro.zig
All 1 tests passed.

$ echo $?
0
```
