### ISSUE TITLE
To keep ziglang small and safe, why not design an optional gc mode?

### ISSUE THREAD

**Issue by YYue** [ziglang/zig#7955]
For those who need small, fast & safe language, use zig without gc;
and for those who need small, safe & fast language, use zig with gc.
Priorities choose modes.
Small > safe - -> Zig > Rust
Fast > small - -> Zig(gc) > Golang
Safe > fast - -> Zig + Zig(gc) > Rust + others

**Comment by SpexGuy** [comment]
There has been some discussion on this in #1063 and #1393.  A garbage collector is outside of the goals of the Zig language.  Zig isn't trying to be the language for every use case.  If you are building a program where a garbage collector fits your goals, there are plenty of other languages, like Java, Go, or D, that will be much better suited for your use.  Zig stays a small and focused language by avoiding these use cases.
