### ISSUE TITLE
Not supporting `--version` flag may cause some programs to falsely believe zig is not present on the path

### ISSUE THREAD

**Issue by fivemoreminix** [ziglang/zig#7956]
Some programs will cheaply check if another program is available for execution via this simple program:
```
execute program on shell: ${program name} --version
if program returns zero, then the program exists
else program does not exist
```
Zig expects very specifically `zig version`, and not `zig --version` -- as that will cause Zig to print the help menu and fail. I determined this to be an issue after having a software incorrectly determine that Zig did not exist on my path.

A `--version` flag should be added, although it does not need to be listed in the help. Just for the sake of compatibility.

Other programs which have such compatibility include Git: `git version` or `git --version`.

Note: I am using Zig 0.7.1, so if any `--version` flag has been added since, I would not know!

**Comment by daurnimator** [comment]
> a software incorrectly determine that Zig did not exist on my path.

What software was that?

Plenty of programs out there don't have a `--version`: many only have a `-v`; while many go programs have `-version` (with a single dash).

**Comment by komuw** [comment]
Golang uses `go version` just like Zig and it seems to be doing fine so far.

**Comment by fivemoreminix** [comment]
> Plenty of programs out there don't have a --version: many only have a -v; while many go programs have -version (with a single dash).
Oh this I did not know 🤨

If nobody considers it a problem then we can close the issue.

> What software was that?
One that I had written 😳 lol. I mean I just assumed like other people you wouldn't cover all cases, you just don't realize. I suppose the correct way is to retry on failed exit code with other forms of the argument until all have failed or one has succeeded.

**Comment by daurnimator** [comment]
> I suppose the correct way is to retry on failed exit code with other forms of the argument until all have failed or one has succeeded.

no.... while some programs have e.g. a `-v` to get the version, plenty of others use to indicate 'verbose' (or other things). You don't want to accidentally take some action....

If you need to find out if a program exists, use `command -v someprogram` (or the less portable `which someprogram`)

**Comment by andrewrk** [comment]
Depeding on your use case, it might be better not to check, and instead just try to execute the program, and handle the file not found error.

**Comment by slimsag** [comment]
@daurnimator FYI, Go programs only advertise single dash but almost always accept both forms.
