### ISSUE TITLE
Variable slice miscompilation

### ISSUE THREAD

**Issue by N00byEdge** [ziglang/zig#7968]
Happens on all optimization levels
```
const std = @import("std");

var int_db: [5]u64 = [5]u64{1, 2, 3, 4, 5};
var my_nums: []u64 = int_db[0..1];

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();

    my_nums = int_db[0..5];

    try stdout.print("Hello, {}!\n", .{my_nums[1..].len});

    for(my_nums[1..]) |num|
        try stdout.print("Hello, {}!\n", .{num});
}
```
What happens here is that `my_nums` is behaving as expected, but `my_nums[1..]` is using the old `my_nums[1..]` (with size 0) from before the reassignment.
[Godbolt](https://gcc.godbolt.org/z/Y71bjr)

**Comment by mikdusan** [comment]
possibly related to #2622

**Comment by mikdusan** [comment]
to clarify this is the bug output from, eg, a 0.9.0 compiler:
```
Hello, 0!
```

output looks good now:
```sh
```

**Comment by N00byEdge** [comment]
Yes, I can confirm this works now! Thanks!
