### ISSUE TITLE
Specify type that cannot be hashed in autoHash error message.

### ISSUE THREAD

**Issue by kienanstewart** [ziglang/zig#7970]
Hi,

I was looking to use the AutoHashMap where the key is a struct. The following code example fails to compile: 

```zig
const std = @import("std");

pub fn main() anyerror!void {
    std.log.info("All your codebase are belong to us.", .{});
}

const Vertex = struct {
    p: [3]f32,
    c: [3]f32,
    t: [2]f32,
};

test "hashmap" {
    var allocator = std.testing.allocator;
    var hm = std.hash_map.AutoHashMap(Vertex, u64).init(allocator);
    defer hm.deinit();
    
}
```
With the error:

```
zig test src/main.zig
/zig/lib/std/hash/auto_hash.zig:98:12: error: cannot hash this type
        => @compileError("cannot hash this type"),
           ^
/zig/lib/std/hash/auto_hash.zig:65:21: note: called from here
                hash(hasher, element, .Shallow);
                    ^
/zig/lib/std/hash/auto_hash.zig:113:28: note: called from here
        .Array => hashArray(hasher, key, strat),
                           ^
/zig/lib/std/hash/auto_hash.zig:133:21: note: called from here
                hash(hasher, @field(key, field.name), strat);
                    ^
/zig/lib/std/hash/auto_hash.zig:180:9: note: called from here
    hash(hasher, key, .Shallow);
        ^
/zig/lib/std/hash_map.zig:26:25: note: called from here
                autoHash(&hasher, key);
                        ^
/zig/lib/std/hash_map.zig:21:29: note: called from here
        fn hash(key: K) u64 {
                            ^
```

From what I can see, `lib/std/hash/auto_hash.zig`'s `hash` function should support structs, but maybe it's not working properly anymore? I could of course be trying to do this wrong, or I mis-understand and the structs aren't supported.

What I understand to be happening presently in the following code snippet from `auto_hash.zig`, is that the type of `key` is stored instead of the the key (already a type) itself. Therefore, when `@typeInfo(Key)` is evaluated, the type is always `.void`?

```zig
pub fn hash(hasher: anytype, key: anytype, comptime strat: HashStrategy) void {
    const Key = @TypeOf(key);
    ...
    switch (@typeInfo(Key)) {
       ...
    }

```

As an additional example the following is output when I test:

```zig
    const Key = @TypeOf(Vertex);
    std.log.warn("typeInfo(Vertex): '{}'", .{@typeInfo(Vertex)});
    std.log.warn("typeInfo(Key): '{}'", .{@typeInfo(Key)});
```

```
(warn): typeInfo(Vertex): 'TypeInfo{ .Struct = Struct{ .layout = ContainerLayout.Auto, .fields = StructField@202f98, .decls = Declaration@0, .is_tuple = false } }'
[default] (warn): typeInfo(Key): 'TypeInfo{ .Type = void }'
```

Is AutoHashMap intended to support hashing structs? If so, how is it supposed to be used?

**Comment by Vexu** [comment]
The issue is not with the struct but the floats in the arrays, notice how the error return trace mentions `Array` and that the hash function ia being called for an `element`. That error message really should mention the name of the type that is causing issues.

**Comment by kienanstewart** [comment]
Hi Vexu,

thanks for the feedback. If I understand, your vision for this issue is to resolve the vagueness of the error message but leave the functionality as is - is that correct? In that case, maybe we can change the title to reflect that.

How would a hashmap using structs that contain arrays (or other structs) work? Would a custom hasher function be required, eg. to pass a different HashStrategy?

**Comment by g-w1** [comment]
It is not even with arrays, but floats. Hashing floats is not allowed.

**Comment by mrakh** [comment]
> It is not even with arrays, but floats. Hashing floats is not allowed.

Yep, see https://github.com/ziglang/zig/pull/6145 for a discussion on this. In short, if you want to use anything containing a float as a key, you should provide your own hashing function.
