### ISSUE TITLE
Atomic stores to enum trigger zig compiler bug

### ISSUE THREAD

**Issue by notYuriy** [ziglang/zig#7976]
https://godbolt.org/z/Mse6xM
This code
```zig
pub fn main() void {
    const e = enum {
        a, b, c, d
    };
    var ev: e = undefined;
    @atomicStore(e, &ev, .a, .Release);
}
```
results in this compiler output
```
broken LLVM module found: atomic memory access' size must be byte-sized
 i2  store atomic i2 0, i2* %ev release, align 1, !dbg !3257

This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
Compiler returned: 255
```

**Comment by notYuriy** [comment]
For the record, this code compiles just fine
```zig
pub fn main() void {
    // this works
    const e = enum(usize) {
        a, b, c, d
    };
    var ev: e = undefined;
    @atomicStore(e, &ev, .a, .Release);
}
```
Ideally, zig frontend to llvm should detect cases when the type does not support atomic operations

**Comment by notYuriy** [comment]
It would be even better if there was something like `enum(atomic)` for hinting the compiler that atomic operations should be allowed on this type

**Comment by lithdew** [comment]
Agreed that the compiler error could be better, though the error does point out that the size of an atomic access must be byte-sized.

Having the enum be `enum(u8)` makes the code compile and run properly. By default, as pointed out in the Zig documentation, enums are sized to be the minimum amount of bits necessary to represent all of its possible values. In the case of `enum { a, b, c, d }`, the size of the enum is u2.
