### ISSUE TITLE
Allow definition of constants to pass into zig translate-c

### ISSUE THREAD

**Issue by raulgrell** [ziglang/zig#798]
When calling translate-c, allow defining c constants. For example:

`$> zig translate-c windows.h --c-define WIN32_LEAN_AND_MEAN`

In addition, it would be nice to be able to emit the result of a cImport for inspection and manual editing. The generated import could be placed in the zig-cache directory, or a user specified location.

**Comment by andrewrk** [comment]
You can do this by creating myfile.h with the #define and then the #include, and then using the translate-c command on myfile.h.


We also have --verbose-cimport which you could pipe to a file when building.

**Comment by raulgrell** [comment]
--verbose-cimport will also pipe stuff other than the translate-c output which is less than ideal, but creating the intermediate file is already a great solution for me.

Thanks
