### ISSUE TITLE
Tabs are turning into spaces when I type them

### ISSUE THREAD

**Issue by 0reoKing** [ziglang/zig#7982]
Is there even tab support I don't want my tabs turning into spaces.

**Comment by daurnimator** [comment]
https://github.com/ziglang/zig/wiki/FAQ#why-does-zig-force-me-to-use-spaces-instead-of-tabs

**Comment by Inc0n** [comment]
A language that utilize curly brackets and semi-colons to indicate expression ends prohibits usage of tabs, in my opinion, is equivalence to Linux decides that only Emacs or Vim is allowed to run on their OS.
