### ISSUE TITLE
stage1 assertion for implicit conversion to sentinel Many pointer

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#7986]
Reproduce issue with:

`bug.zig`:
```zig
pub fn getMsg() [:0]const u8 {
    return "Hello";
}
pub const Greeting = struct {
    msg: [*:0]const u8,
};
pub fn main() void {
    const greeting = Greeting {
        .msg = getMsg(),
    };
}
```

```sh
$ zig build-exe bug.zig
when analyzing /home/marler8997/git/zigwin32gen/examples/bug.zig:9:22 in compiler source at /home/vsts/work/1/s/src/stage1/codegen.cpp:1801: thread 12431 panic: assertion failed. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
Aborted (core dumped)

```

Here is a full stacktrace when building with a debug version of zig built from 221f1d898c39e9ea25f1d7fc9642bfbb3c97e894:

<details>
<pre>
when analyzing bug.zig:9:22 in compiler source at /zig/src/stage1/codegen.cpp:1801: thread 12778 panic: assertion failed. This is a bug in the Zig compiler.
/zig/src/stage1.zig:171:5: 0x7d52cc in stage2_panic (zig1)
    @panic(ptr[0..len]);
    ^
/zig/src/stage1/analyze.cpp:9722:17: 0x132045d in src_assert_impl (/zig/src/stage1/analyze.cpp)
    stage2_panic(msg, strlen(msg));
                ^
/zig/src/stage1/codegen.cpp:847:20: 0x1204dc5 in ir_assert_impl (/zig/src/stage1/codegen.cpp)
    src_assert_impl(ok, source_instruction->base.source_node, file, line);
                   ^
/zig/src/stage1/codegen.cpp:1801:9: 0x12087ac in ir_llvm_value (/zig/src/stage1/codegen.cpp)
        ir_assert(instruction->value->special != ConstValSpecialRuntime, instruction);
        ^
/zig/src/stage1/codegen.cpp:5177:39: 0x1216b3d in ir_render_ref (/zig/src/stage1/codegen.cpp)
    LLVMValueRef value = ir_llvm_value(g, instruction->operand);
                                      ^
/zig/src/stage1/codegen.cpp:6833:33: 0x121d64e in ir_render_instruction (/zig/src/stage1/codegen.cpp)
            return ir_render_ref(g, executable, (IrInstGenRef *)instruction);
                                ^
/zig/src/stage1/codegen.cpp:6977:60: 0x121de93 in ir_render (/zig/src/stage1/codegen.cpp)
            instruction->llvm_value = ir_render_instruction(g, executable, instruction);
                                                           ^
/zig/src/stage1/codegen.cpp:8404:18: 0x122429c in do_code_gen (/zig/src/stage1/codegen.cpp)
        ir_render(g, fn_table_entry);
                 ^
/zig/src/stage1/codegen.cpp:9578:16: 0x1228ee9 in codegen_build_object (/zig/src/stage1/codegen.cpp)
    do_code_gen(g);
               ^
/zig/src/stage1/stage1.cpp:130:25: 0x11fcf14 in zig_stage1_build_object (/zig/src/stage1/stage1.cpp)
    codegen_build_object(g);
                        ^
/zig/src/stage1.zig:143:32: 0xad4e64 in Module.build_object (zig1)
        zig_stage1_build_object(mod);
                               ^
/zig/src/Compilation.zig:3331:31: 0x96461f in Compilation.updateStage1Module (zig1)
    stage1_module.build_object();
                              ^
/zig/src/Compilation.zig:1783:36: 0x921bf2 in Compilation.performAllTheWork (zig1)
            self.updateStage1Module(main_progress_node) catch |err| {
                                   ^
/zig/src/Compilation.zig:1371:31: 0x91c592 in Compilation.update (zig1)
    try self.performAllTheWork();
                              ^
/zig/src/main.zig:2082:20: 0x8b287f in main.updateModule (zig1)
    try comp.update();
                   ^
/zig/src/main.zig:1923:17: 0x7fd3d0 in main.buildOutputType (zig1)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/zig/src/main.zig:170:31: 0x7d3adc in main.mainArgs (zig1)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
/zig/src/stage1.zig:45:24: 0x7d34fe in main (zig1)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
                       ^
Aborted (core dumped)

</pre>
</details>

### This issue goes away if we change `msg` field type from a many pointer `[*:0]const u8` to a slice `[:0]const u8`.
```zig
pub fn getMsg() [:0]const u8 {
    return "Hello";
}
pub const Greeting = struct {
    msg: [:0]const u8,
};
pub fn main() void {
    const greeting = Greeting {
        .msg = getMsg(),
    };
}
```

### This issue goes away if we explicitly use `.ptr` on the return value of `getMsg`:
```zig
pub fn getMsg() [:0]const u8 {
    return "Hello";
}
pub const Greeting = struct {
    msg: [*:0]const u8,
};
pub fn main() void {
    const greeting = Greeting {
        .msg = getMsg().ptr,
    };
}
```

### This issue goes away if we remove the struct and just assign to a variable:
```zig
pub fn getMsg() [:0]const u8 {
    return "Hello";
}
pub fn main() void {
    const msg: [*:0]const u8 = getMsg();
}
```

### This issue goes away if we remove the `getMsg` function like this:
```zig
pub const Greeting = struct {
    msg: [*:0]const u8,
};
pub fn main() void {
    const hello : [:0]const u8 = "Hello";
    const greeting = Greeting {
        .msg = hello,
    };
}
```

**Comment by mikdusan** [comment]
no  more compiler assertion failure

<details>
<summary>ok1.zig</summary>

```zig
pub fn getMsg() [:0]const u8 {
    return "Hello";
}
pub const Greeting = struct {
    msg: [*:0]const u8,
};
pub fn main() void {
    const greeting = Greeting {
    ¦   .msg = getMsg(),
    };
    _ = greeting;
}
```
</details>

```sh
$ zig version
0.11.0-dev.1095+8bd734d60

$ zig build-exe ok1.zig
# no stdout/stderr (good)
```
