### ISSUE TITLE
translate-c: incorrect handling of comma operator + boolean short-circuiting

### ISSUE THREAD

**Issue by ehaas** [ziglang/zig#7989]
This is a reduced example of what happens when translating musl libc's `assert` function. 

```c
#include <stdio.h>
int main(void) {
    (1 || (printf("Don't print me\n"),0));
    return 0;
}
```

Translates to:

```zig
pub extern fn printf([*c]const u8, ...) c_int;
pub export fn main() c_int {
    _ = printf("Don\'t print me\n");
    _ = (true or ((@as(c_int, 0)) != 0));
    return 0;
}
```

The Zig version incorrectly calls printf since the short-circuiting behavior is lost when pulling comma-operator substatements into separate statements.

The translated version should probably look something like this:

```zig
pub extern fn printf([*c]const u8, ...) c_int;
pub export fn main() c_int {
    _ = (true or blk: {
        _  = printf("Don\'t print me\n");
        break :blk ((@as(c_int, 0)) != 0);
    });
    return 0;
}
```

**Comment by ehaas** [comment]
@Vexu do you know why `scope.findBlockScope(rp.c);` instead of `Scope.Block.init(rp.c, scope, true);` is used here: https://github.com/ziglang/zig/blob/61bcac108cecba0ab8e1b442bd71c51306c0e9fc/src/translate_c.zig#L1441

If I change that to create a new block scope it fixes the issue and all the `run_translated_c` tests continue to pass.

**Comment by Vexu** [comment]
Seemed like a good way to handle this at the time, feel free to change it.
