### ISSUE TITLE
Compiler crash when exporting a member of an enum(comptime_int) with >1 member

### ISSUE THREAD

**Issue by spocino** [ziglang/zig#8006]
In zig 0.8.0-dev.1139+d3565ed6b on linux x86_64, the code
```zig
pub export const bug = enum(comptime_int){ a = 0, b = 1 }.a;
```
when compiled with `zig build-obj (file).zig` results in the following error:

```
Assertion failed at /home/vsts/work/1/s/src/stage1/analyze.cpp:6142 in get_the_one_possible_value. This is a bug in the zig compiler.thread [varies per compile] panic:
Unable to dump stack trace: debug info stripped
Aborted (core dumped)
```

I tried to compile zig with debug info still in, but failed to.

From my limited testing, a similar bug exists in earlier versions of zig.

**Comment by g-w1** [comment]
I don't think an enum(comptime_int) should be possible since comptime_int has infinite size.

**Comment by daurnimator** [comment]
> I don't think an enum(comptime_int) should be possible since comptime_int has infinite size.

It would just mean that values of the time must be comptime-known. (which yes: means that they probably can't be exported)

**Comment by spocino** [comment]
@daurnimator The issue isn't that I want to do that, it's that this crashes the compiler instead of throwing an error.

**Comment by pingiun** [comment]
I also just encountered this bug because it seems like something which should be possible, using an enum only to store certain allowed numbers at compile time. I am running `zig-macos-x86_64-0.8.0-dev.1975+01a136585`

**Comment by mikdusan** [comment]
compiler no longer crashes

```sh
$ zig version
0.11.0-dev.1095+8bd734d60

$ zig build-obj ok1.zig
ok1.zig:1:5: error: unable to export type 'ok1.bug__enum_216'
pub export const bug = enum(comptime_int){ a = 0, b = 1 }.a;
    ^~~~~~
ok1.zig:1:5: note: enum tag type 'comptime_int' is not extern compatible
ok1.zig:1:24: note: enum declared here
pub export const bug = enum(comptime_int){ a = 0, b = 1 }.a;
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
