### ISSUE TITLE
Ability to specify rpath in the zig build system

### ISSUE THREAD

**Issue by InterplanetaryEngineer** [ziglang/zig#8011]
The rpath is currently only set when linking to an OtherStep. Could we add a
```zig
pub fn addRpath(self: *LibExeObjStep, path: []const u8) void
```
to LibExeObjStep? Mabe also an `addRpathRelative` which prepends $ORIGIN for ELF and @executable_path for MACH-O binaries. ([Windows doesn't seem to support any equivalent](https://stackoverflow.com/questions/107888/is-there-a-windows-msvc-equivalent-to-the-rpath-linker-flag))

**Comment by andrewrk** [comment]
Added in c0aa9292bafa1a10c43297d3d5929049fab84e9a.
