### ISSUE TITLE
No way to pass "-undefined dynamic_lookup" to Darwin linker for Zig sources?

### ISSUE THREAD

**Issue by haberman** [ziglang/zig#8016]
To build a native Python extension on Darwin, the option `-undefined dynamic_lookup` must be passed to the linker to indicate that unresolved symbols will be resolved at runtime. 

More info here: [Please use -undefined dynamic_lookup instead of -lpython or -framework Python to build Python extension modules on OS X](https://blog.tim-smith.us/2015/09/python-extension-modules-os-x/)

Otherwise you get errors like this:

```
cmd zig build-lib -dynamic -DPYHEXVER=50857456 --name pdfxt.cpython-38-darwin -I /Users/haberman/opt/anaconda3/include/python3.8 -I /usr/include pdfxt.zig
warning(link): unexpected LLD stderr:
Undefined symbol: zig-cache/o/90680a79ab7f51bd67f93a83b363da55/pdfxt.cpython-38-darwin.o: __PyArg_ParseTuple_SizeT
Undefined symbol: zig-cache/o/90680a79ab7f51bd67f93a83b363da55/pdfxt.cpython-38-darwin.o: _PyLong_FromLong
Undefined symbol: zig-cache/o/90680a79ab7f51bd67f93a83b363da55/pdfxt.cpython-38-darwin.o: _PyModule_Create2
symbol(s) not found
```

For `zig cc` it appears there is an option `--allow-shlib-undefined` that will achieve the desired effect.

https://github.com/ziglang/zig/blob/9270aae071a4ee840193afe1162b24945cbd6d9e/src/main.zig#L1260-L1263

https://github.com/ziglang/zig/blob/9270aae071a4ee840193afe1162b24945cbd6d9e/src/link/MachO.zig#L781-L784

But I don't see any comparable option for `build-lib`.

I believe this is a blocker for writing native extensions on Darwin.

(Darwin also differentiates between "dynamic library" and "bundle," but [the functional differences between these two have greatly lessened over time](https://stackoverflow.com/a/2339910/77070), so it's unclear if the ability to compile with `-bundle` is actually an important use case or not.)

**Comment by haberman** [comment]
Are you open to accepting a change that adds a link option for this?

**Comment by haberman** [comment]
As a workaround I tried using `zig build-obj` to turn `.zig` files into `.o` so I could link with the regular C compiler and pass `-undefined dynamic_lookup` that way:

```
$ zig build-obj -fPIC -DPYHEXVER=50857456 -I /Users/haberman/opt/anaconda3/include/python3.8 -I /usr/include pdf.zig
$ zig build-obj -fPIC -DPYHEXVER=50857456 -I /Users/haberman/opt/anaconda3/include/python3.8 -I /usr/include pdfxt.zig
$ gcc -dynamic -undefined dynamic_lookup pdfxt.o pdf.o -o pdfxt.so
```

I was able to build my `.so` this way, but it fails to load due to missing some stuff from compiler_rt:

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import pdfxt
ImportError: dlopen(/tmp/pdfxt.so, 2): Symbol not found: ___zig_probe_stack
  Referenced from: /tmp/pdfxt.so
  Expected in: flat namespace
 in /tmp/pdfxt.so
```

I tried passing `-fcompiler-rt` to `zig build-obj` but that doesn't appear to support Mach-O:

```
zig build-obj -fcompiler-rt -fPIC -DPYHEXVER=50857456 -I /Users/haberman/opt/anaconda3/include/python3.8 -I /usr/include pdfxt.zig
error: Embedding compiler-rt into macho objects is not yet implemented.
```

**Comment by andrewrk** [comment]
Thank you for detailing this use case. Closing in favor of #3085. I have modified the milestone of #3085 to be 0.8.0, indicating a plan to address the issue before the next release.
