### ISSUE TITLE
mips64el-linux target fails with: container 'std.os.linux' has no member called 'syscall3'

### ISSUE THREAD

**Issue by james-callahan** [ziglang/zig#8020]
First seen trying to compile a simple program I'm writing, reproducible with the `init-exe` sample:
```
$ zig init-exe
info: Created build.zig
info: Created src/main.zig
info: Next, try `zig build --help` or `zig build run`
$ zig build -Dtarget=mips64el-linux-musl 
/usr/lib/zig/std/special/compiler_rt/clear_cache.zig:78:36: error: container 'std.os.linux' has no member called 'syscall3'
        const result = std.os.linux.syscall3(.cacheflush, start, end - start, flags);
                                   ^
```

**Comment by g-w1** [comment]
I think you must fill in lib/std/os/linux/mips64el.zig for this to work. See the templates of the other files in that directory, it is not a very long file. Then add a case for mips64el here https://github.com/ziglang/zig/blob/master/lib/std/os/linux.zig#L21-L30
