### ISSUE TITLE
Ignore the `inline` keyword in debug mode

### ISSUE THREAD

**Issue by CoolRustacean** [ziglang/zig#8021]
Inlining of functions is an optimization, but optimizations are not important in debug mode. Moreover, inline functions thwart stack traces.
```zig

const std = @import("std");

inline fn bar() void {
    std.debug.assert(false);
}

inline fn foo() void {
    bar();
}

pub fn main() void {
    foo();
}
```
```
thread 74234 panic: reached unreachable code
/usr/lib/zig/0.8.0/lib/std/debug.zig:223:14: 0x203edb in std.debug.assert (test)
    if (!ok) unreachable; // assertion failure
             ^
/home/sapphire/main.zig:5:21: 0x22d3ca in main (test)
    std.debug.assert(false);
                    ^
/usr/lib/zig/0.8.0/lib/std/start.zig:335:22: 0x204d3e in std.start.posixCallMainAndExit (test)
            root.main();
                     ^
/usr/lib/zig/0.8.0/lib/std/start.zig:163:5: 0x204c12 in std.start._start (test)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
fish: “zig run test.zig” terminated by signal SIGABRT (Abort)
```
Functions marked `inline` should not be inlined in debug mode, but functions called with `@call` and the `.always_inline` option should always be inlined. Nevertheless, the compiler should always emit a compile error if it's not possible to inline a function marked `inline`, even though it will not be inlined in debug mode.

**Comment by daurnimator** [comment]
> Inlining of functions is an optimization,

it is far more than an optimization:
  - will never add another stack frame
  - ensures that symbols don't appear in your binary

> ```zig
> inline fn
> ```

Note that inline is now a calling convention. see #6429
