### ISSUE TITLE
Exception 0x06 (invalid opcode) on i368 freestanding when using "big" structs

### ISSUE THREAD

**Issue by Flutterish** [ziglang/zig#8024]
While learning how to write an OS in zig (by reading how zen works) I was coding CPUID and I encounterd this exception when the struct that held CPUID data reached > 28 bytes in size. The below struct also causes this cpu exception when created inside a function:
```zig
const Foo = packed struct {
    bar : u225 // and anything bigger (this one is a bit over 28 bytes)
};
// does not have to be packed:
const Foo = struct {
    bar : u256
};
// nor in one field:
const Foo = packed struct {
    bar : u128,
    baz : u97
};
// note that this does NOT cause this exception:
var foo : u256 = 0;
// and therefore i believe the problem lies somewhere in pointer magic
// upon further testing, if I allocate it, I can access some 
// of the lower fields, but after accessing higher fields, the exception occurs again 
```
The primitive instruction trace I got by reading opcode bytes from `eip` is `0x0F, 0x10, 0x04, 0x3A, 0x0E, 0x0F, 0x4C, 0x3A, 0x10...` ( at 0x108280 if this address has any significance )

My build settings:
```zig
const kernel = builder.addExecutable(defaults.kernel_name, "kernel/kmain.zig");
kernel.setBuildMode(b.standardReleaseOptions());
kernel.setTarget(std.zig.CrossTarget{
    .cpu_arch = std.Target.Cpu.Arch.i386,
    .os_tag = std.Target.Os.Tag.freestanding,
    .abi = std.Target.Abi.gnu
});
```
I am running QEMU with `qemu-system-i386`.

This does not happen when built for windows.

**Comment by LemonBoy** [comment]
I have no binary, no crystal ball and no compilable source code so I guess the problem is with the baseline processor being a pentium4 w/ SSE.

**Comment by zigazeljko** [comment]
This exception is caused by a SSE instruction:

```asm
00108280   0F 10 04 3A   movups xmm0, xmmword ptr [edx + edi]
00108284   0E            push cs
00108285   0F 4C 3A      cmovl edi, dword ptr [edx]
```

To fix this, you need to choose a CPU model without SSE (such as `generic`):

```zig
kernel.setTarget(std.zig.CrossTarget{
    .cpu_arch = std.Target.Cpu.Arch.i386,
    .cpu_model = std.zig.CrossTarget.CpuModel{ .explicit = &std.Target.x86.cpu.generic },
    .os_tag = std.Target.Os.Tag.freestanding,
    .abi = std.Target.Abi.gnu
});
```

**Comment by Flutterish** [comment]
That was it, thank you!
