### ISSUE TITLE
macOS: Lazy symbol binding fails for _objc_getClass 

### ISSUE THREAD

**Issue by coolbluewater** [ziglang/zig#8037]
Possibly related to https://github.com/ziglang/zig/issues/7127

I'm experimenting with calling the objective-c runtime from zig. Compiling this:
```

const objc = @cImport({
  @cInclude("objc/message.h");
});

pub fn main() !void {
     const foo = objc.objc_getClass("NSObject");
}
```

on `zig-macos-x86_64-0.8.0-dev.1141+68e772647.tar.xz` running on Catalina with 

`zig build-exe hello-world.zig -target x86_64-macos -lobjc -name a.out
`

Does produce a binary, but running it gives:

```
dyld: Symbol not found: _objc_getClass
  Referenced from: /Users/me/me/zigmac/./a.out
  Expected in: /usr/lib/libSystem.B.dylib
```

I've tried setting the library path etc, but no luck.
Any ideas what the problem might be?

**Comment by mikdusan** [comment]
playing around with this on macos 11.2.1:

```
# force use of macos' system linker instead of `lld`
export ZIG_SYSTEM_LINKER_HACK=1

# seems to link/run
zig build-exe z14.zig -lobjc --name a.out

# ld64.lld: error: Unable to find library for -lobjc
# what's weird about this error is looks like the HACK is not engaging?
zig build-exe z14.zig -lobjc --name a.out --target x86_64-macos
```

**Comment by coolbluewater** [comment]
@mikdusan, thanks! I hadn't tried the simpler invocation without `--target`.
Will go with the above for now. Should I keep this issue open, or is it a duplicate of a known issue?

**Comment by mikdusan** [comment]
> Also, my real goal is to have this working on iOS, for which --target is needed. Is that not possible atm?

Correct, our current condition to HACK includes a "cross-target" state which is not ideal. We'd have to augment to say something like "check env var when (host == macos) and (target one of { ios, macos, tvos, watchos })".

**Comment by coolbluewater** [comment]
@mikdusan thanks. appreciate it! 
A slightly off-topic question: I'm trying to build some helpers for objective-c.
I'd like to use comptime to turn a method signature like `(c_short) characterAtIndex:(c_int) index` into:
1. A message selector string which is a filtered version of signature, `characterAtIndex:` in this case, and
2. A function signature, which is `fn (c_int) c_short`. This is the signature of the function that the message invokes.

Question:
1. The first is easily doable, but is it possible to de-duplicate identical generated strings at comptime? I imagine the answer is yes, using e.g. a hashtable.
2. For the second requirement, I don't (sadly!) see a way of building a function signature at comptime. Am I missing something.

**Comment by daurnimator** [comment]
> For the second requirement, I don't (sadly!) see a way of building a function signature at comptime. Am I missing something.

You'd have to generate it per arity. i.e one literal for each possible function argument `fn (T1) R`, `fn (T1,T2) R`, etc.

**Comment by coolbluewater** [comment]
@daurnimator good idea, Thanks!
