### ISSUE TITLE
translate-c: Missing semicolon when if statement nested inside single-statement if statement

### ISSUE THREAD

**Issue by ehaas** [ziglang/zig#8038]
This is regarding the `ast-memory-layout` branch using the new translate-c intermediate AST representation.

```c
int main(void) {
   if (1)
      if (1) {}
   return 0;
}
```
produces:
```zig
pub export fn main() c_int {
    if (true) if (true) {}
    return 0;
}
```

Which fails to compile:
```
./nested_if.zig:4:5: error: expected token ';', found 'return'
    return 0;
```

@Vexu

**Comment by Vexu** [comment]
Fixed in 6f6568b1fdb30fc8574b3047470510b798307717, the branch hasn't been merged yet so you can just leave comments for any bugs/regressions you find.
