### ISSUE TITLE
Valid usage of `&&` incorrectly reported as a compile error

### ISSUE THREAD

**Issue by windows-h8r** [ziglang/zig#8046]
[see below for the fix](https://github.com/ziglang/zig/issues/8046#issuecomment-844589399)

--------

Currently, `&&expression` is illegal, but `& &expression` is legal, and returns the address of the address of `expression`.
However, `zig fmt` changes `& &expression` to `&&expression`. 

*`bug.zig`*
```zig
const std = @import("std");

pub fn main() void {
    var a: usize = 4;
    var b = & &a;
    b.*.* = 92;
    std.debug.print("{}\n", .{a});
}
```
Running `zig fmt bug.zig` twice yields
```
bug.zig:5:13: error: Expected expression, found '&&'
    var b = &&a;
            ~~
```

**Comment by nektro** [comment]
the bug here is `&&` being invalid.

**Comment by windows-h8r** [comment]
> the bug here is `&&` being invalid.

Sounds correct. `&&` and `||` used to be the `and` and `or` operators, so it's probably still parsing `&&` and `||` as single tokens.

**Comment by windows-h8r** [comment]
By the way, I think `a.&` would be a better syntax than `&a` for the address-of operator. It's consistent with `a.*`, `a.?`, `a.b`, `a(b)`, and `a[b]`.

**Comment by AssortedFantasy** [comment]
I never realized you could construct pointers to temporaries.
Is `& &` actually legal? What do you even get a pointer to?

I'm half tempted to say this is a design flaw. I'm gonna test this a bit and do some thinking before I write up and issue to resolve this if I find somewhere down the line this bites us.

**Comment by SpexGuy** [comment]
> Is `& &x` actually legal? What do you even get a pointer to?

This returns a pointer to a stack temporary containing `&x`.  The ability to take the address of temporaries is currently intentional, it's used in several common situations like these:
```zig
foo(&[_]u32{ a, b });
bar(&Bar{ .x = a });
const alloc = &Allocator.init().allocator;
```

**Comment by andrewrk** [comment]
The fix here is:

 * Modify the parser to no longer treat `&&` as a special token
 * Detect the `a && b` situation in AstGen and report the helpful compile error there
