### ISSUE TITLE
Proposal: comptime support for functions with variable numbers of args

### ISSUE THREAD

**Issue by coolbluewater** [ziglang/zig#8047]
This is an outcome of https://github.com/ziglang/zig/issues/8037.

Scenario: we want to build a custom function signature at compile time, e.g. `fn foo(a:u8, b: Bar, ...) baz`. Currently the way to do this is to switch on arity and code for a certain maximum length of arguments. 

This works but could be more zen :)

Proposal: a new comptime keyword, `@args()`, that takes an array of elements of type `type` and appends them to the function signature. `@args` also optionally takes an array of names corresponding to the argument types.

```
test "generate function signature" {
    const args: []type = .{ u8, u16, u32 };
    const names: [][]u8 = .{ "foo", "bar", "baz" };
    const p = fn (a: u32, b: u32) u32;
    const fn1 = fn(u64, @args(args)) u16; // no arg names 
    const fn2 = fn(u64 x, @args(args, names)) u16; // with arg names

    expect(@typeName(fn1) == "fn (u64, u8, u16, u32) u16");
    expect(@typeName(fn1) == "fn (u64 x, u8 foo, u16 bar, u32 baz) u16");
}
```

**Comment by MasterQ32** [comment]
You can already create the function types with `@Type(.Fn)`, no need for `@args()` ;)

**Comment by coolbluewater** [comment]
@MasterQ32, thanks - could you please give an example? I couldn't find documentation on this.

**Comment by MasterQ32** [comment]
I don't have the time right now to do it. Check out the std.builtin.TypeInfo structure for `.Fn` types. You build such a structure at `comptime` and pass it into `@Type`
