### ISSUE TITLE
Allow type specifications in conditionals

### ISSUE THREAD

**Issue by jacobdufault** [ziglang/zig#806]
Inside of an unwrapping if, I'd like to be able to specify the unwrapped type with a type annotation. This is particularly useful if the value inside of the if is coming from a function call.

```zig
fn foo() {
  var a: ?i32 = 3;
  if (a) |b| {}
  // if (a) |b: i32| {} // causes compiler error, unexpected :
}
```

**Comment by andrewrk** [comment]
Use `@as` for this.
