### ISSUE TITLE
Dynamic build.zig dependencies

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#8070]
Special Thanks to @MasterQ32 , @g-w1, @mikdusan and @pixelherodev for their help in finding this solution.

This is a proposed interface to allow `build.zig` to declare package requirements based on any options/data available when its `build` function is exectued.

The problem this interface addresses is a "chicken and egg problem" with `build.zig`.  If `build.zig` needs a package, then it needs to be available before compiling `build.zig`, otherwise `@import("somepkg")` will cause a compile error.  However, we can't know which packages `build.zig` needs until after we compile it and provide it all the build options.  For example, a `build.zig` file may have an option to enable building an Android APK, in which case it requires the "androidbuild" package that provides functions to generate build constructs for Android.  But this package is only needed if we specify `-Dandroid` on the command-line which isn't available until after `build.zig` has been compiled and is running.

The problem can take some time to wrap your head around.  A compiled and running `build.zig` knows what packages it needs, but we can't compile and run `build.zig` without first knowing what package it needs.  So the idea here is to break this cyclic dependency by first compiling `build.zig` once without any packages, then we can query the resulting executable with our build options to see what packages it needs, then we can resolve those packages and recompile `build.zig` (if it needs any packages).  The question then becomes, how do we compile `build.zig` without the packages it needs?

The sticking point to compiling `build.zig` without its needed packages are its `@import("somepkg")` statements.  These statements are analyzed at comptime and cannot fail.  There is another proposal that suggests `@tryImport` be added to the language to address this (https://github.com/ziglang/zig/issues/8025), however, this proposal suggests an alternative that doesn't require a language addition.  Instead, before compiling `build.zig` we generate a module named `buildpkgs` that provides the information about what packages are available at comptime:

`buildpkgs.zig`
```zig
pub const names = [];

pub fn has(comptime name: []const u8) bool {
     inline for (names) |has_name| {
         if (@import("std").mem.eql(u8, name, has_name)) return true;
     }
}
```

Going back to the android example, this is what our `build.zig` file might look like:

```zig
// buildpkgs is our dynamically generated module
const buildpkgs = @import("buildpkgs");

pub fn build(b: *Builder) !void {
    if (b.option(bool, "android", "build an android APK")) {
        if (comptime buildpkgs.has("androidbuild")) {
            const androidbuild = @import("androidbuild");
            androidbuild.createManifest(.{ ... });
            androidbuild.setTarget(...);
            ...
        } else {
            b.needPackage("androidbuild");
        }
    }
}
```

This `build.zig` file can be compiled both with and without the `androidbuild` package.  When `-Dandroid` has been enabled, but the `androidbuild` package has not been provided, we call `b.needPackage("androidbuild")`.  This method adds a package name to a list of `needed_pkgs`, which `build_runner.zig` will use to report the missing package before it tries to build anything, like this:

```
> zig build -Dandroid
error: build.zig is missing package "androidbuild"
```

In the case that the user doesn't specify `-Dandroid`, we never call `b.needPackage("androidbuild")`, so the build will happily continue without it:

```
# NOTE: we do not specify -Dandroid
> zig build
Success
```

The last piece of the puzzle is how this would interact with a package manager.  For this piece, all we need is a way to query the resulting build executable of the needed package list.

```
> zig build -Dandroid get-needed-packages
androidbuild
```

Now the package manager has the list of packages that `build.zig` requires, and can do the work to resolve them, and then recompile `build.zig` with those packages resolved.  On the next compilation, our new `buildpkgs` dynamic module would look like this:

```zig
pub const names = ["androidbuild"];

pub fn has(comptime name: []const u8) bool {
     inline for (names) |has_name| {
         if (@import("std").mem.eql(u8, name, has_name)) return true;
     }
}
```

Also note that the cost of compiling `build.zig` twice is only paid if it's necessary.  In the happy path where `build.zig` already has all it's dependencies, a package manager will see that it requires no additional dependencies and declare that resulting `build.zig` binary is ready to build.

**Comment by marler8997** [comment]
UPDATE: after implementing this in https://github.com/ziglang/zig/pull/8072, I found that the idea of Zig providing dynamically generated Zig code already exists via `builtin.zig`.  So I updated the implementation to leverage `std.builtin` instead of adding a new `"buildpkgs"` package.  @andrewrk if you prefer me to go back to using `@import("buildpkgs").has` rather than `std.builtin.hasPkg` let me know.

**Comment by InterplanetaryEngineer** [comment]
Are there practical use-cases for this? I'd think that build *logic* could always be supplied directly as source code - maybe as git submodule or just copied in - and that it shouldn't be the responsibility of the build.zig to install external build *tools*.

**Comment by marler8997** [comment]
> Are there practical use-cases for this? I

Copied from the proposal "...a build.zig file may have an option to enable building an Android APK, in which case it requires the "androidbuild" package that provides functions to generate build constructs for Android"

> ...it shouldn't be the responsibility of the build.zig to install external build tools.

Agreed.

**Comment by InterplanetaryEngineer** [comment]
Sorry for being unspecific: by practical, I meant real-world − does `androidbuild` or a comparable zig package exist? Whether in practice or in principle, what makes (could make) it more complicated to install than pulling it in as a git submodule? *Should* `build.zig` have dependencies so complex that they require a `build.zig`?

**Comment by marler8997** [comment]
> I meant real-world − does androidbuild or a comparable zig package exist?

Sure, here's one: https://github.com/MasterQ32/zig-bearssl/blob/master/src/lib.zig

`lib.zig` provides a function `linkBearSSL` that build.zig would call to add bearssl to add a staticically compiled bearssl library.

Another example is my ziget project which provides the `addSslBacked` function (https://github.com/marler8997/ziget/blob/master/build.zig) that adds one of a number of ssl backends.  It's used by my `zigup` tool that downloads and manages zig compilers.

The androidbuild project is theoretical but there's a real world project that could be updated to provide functions like this as well: https://github.com/MasterQ32/ZigAndroidTemplate/blob/master/build.zig

> Whether in practice or in principle, what makes (could make) it more complicated to install than pulling it in as a git submodule?

Not sure what you're asking here.  git submodules could be used for this.  The method of retrieving packages used by `build.zig` is orthogonal to this proposal which is a mechanism to allow them to be optional.  You could use submodules, or zigmod, or whatever.

> Should build.zig have dependencies so complex that they require a build.zig?

I think the answer is no, but I'm not sure what you're asking here and I'm not sure what this has to do with the proposal of allowing `build.zig` dependencies to be optional.  The complexity of a dependency seems orthogonal as to whether it should be optional.

**Comment by InterplanetaryEngineer** [comment]
Thank you for the examples. Sorry I misread part of your proposal, I think I understand it better now; as long as we don't have `@tryImport`, it is probably the most elegant solution.

**Comment by hazeycode** [comment]
This would be very useful for projects that want to provide build routines via the package manager.

**Comment by marler8997** [comment]
Yes I believe lazy dependencies has addressed this issue. closing.
