### ISSUE TITLE
Can you publish the results of JSONTestSuite for std.json?

### ISSUE THREAD

**Issue by Mouvedia** [ziglang/zig#8077]
repository: https://github.com/nst/JSONTestSuite
article: http://seriot.ch/parsing_json.php
related: https://labs.bishopfox.com/tech-blog/an-exploration-of-json-interoperability-vulnerabilities

**Comment by komuw** [comment]
The authors of Zig don't have to do anything, do they?   
I think anyone should be able to just do this on their own.   

I gave it a shot; https://github.com/nst/JSONTestSuite/pull/121

**Comment by komuw** [comment]
<img width="703" alt="Screenshot 2021-02-26 at 16 29 33" src="https://user-images.githubusercontent.com/5163857/109306178-da96d680-784f-11eb-9018-fa6b05a8c974.png">

**Comment by Mouvedia** [comment]
@komuw IIRC there are way more tests than that, or is the rest passing for all 3?

**Comment by komuw** [comment]
Didn't play around with it much.

**Comment by komuw** [comment]
<img width="557" alt="Screenshot 2021-02-26 at 18 14 34" src="https://user-images.githubusercontent.com/5163857/109318124-85ae8c80-785e-11eb-9e4a-2fb9d415f4f8.png">

**Comment by Mouvedia** [comment]
![2021-02-27](https://user-images.githubusercontent.com/208817/109383630-e8983600-78e7-11eb-8315-1d93ec8a7bb7.png)

**Comment by tiehuis** [comment]
That test suite was the original set of test cases that were used when creating the implementation. They should be duplicated in this file https://github.com/ziglang/zig/blob/master/lib/std/json/test.zig.
