### ISSUE TITLE
[Question] Zig's best idiomatic way to interop with c_allocator

### ISSUE THREAD

**Issue by batiati** [ziglang/zig#8083]
Hi there,

I'm creating bindings for an existing C library, and I'm not sure the proper idiomatic way to meet the ```*Allocator``` signature when interoping with C code and having to deal with `c_allocator`.

I mean, my goal is to create the best zig-ish API possible, including "no hidden heap allocations" whenever possible; But I'm not sure the way I have to expose it to my library's users that for some methods they must use the ```c_allocator``` in order to free the memory allocated by the C calls to ```malloc```.

I was thinking about encapsulating everything behind structs with ```init()``` and ```deinit()``` methods, hiding the actual allocator, but it not seems right for a simple owned string.

**Current API:**

```zig
const std = @import("std");
const myLib = @import("myLib.zig");

pub fn main() {

    //Takes no allocator, because C malloc is always used
    var component = myLib.Component.init();
    
    //Returns an owned string allocated by the C code
    var name = component.getName();

    //must use the c_allocator
    defer std.heap.c_allocator.destroy(name);

    std.debug.warn("Initializing {s}\n", .{ name } );
}

```

**Desired API:**

```zig
const std = @import("std");
const myLib = @import("myLib.zig");

pub fn main() {

    const gpa = std.heap.GeneralPurposeAllocator(.{}) {};
    const allocator = &gpa.allocator;

    var component = myLib.Component.init(allocator);
    
    var name = component.getName();
    defer allocator.destroy(name);

    std.debug.warn("Initializing {s}\n", .{ name } );
}

```

I have to keep it well documented, for sure, but it does not really feel like the zig way to work with memory.
Suggestions?

**Comment by LemonBoy** [comment]
`c_allocator` is not a substitute for `malloc` and `free`.

**Comment by batiati** [comment]
> `c_allocator` is not a substitute for `malloc` and `free`.

What do you mean?
Interoping with C code, can't free memory allocated by `malloc` using `c_allocator.destroy` ?

**Comment by LemonBoy** [comment]
Exactly. It may work but that's entirely unintentional.
The `c_allocator` name is misleading, that's an implementation of Zig's Allocator interface using the libc malloc to obtain memory from the OS.

If you need guaranteed compatibility with the libc free then explicitly use malloc.

**Comment by batiati** [comment]
Thank you @LemonBoy,

> guaranteed compatibility with the libc free then explicitly use malloc.

I think the most appropriate is to use `std.c.free` to free the memory allocated by the C code, removing the allocator completely from my zig library's API.
