### ISSUE TITLE
Miscompilation with capture on else block

### ISSUE THREAD

**Issue by SpexGuy** [ziglang/zig#8104]
```zig
pub fn main() void {
    var x: u32 = 0;
    if (x != 0) {
        @import("std").debug.print("wat, x = {d}\n", .{x});
    } else |err| {}
}
```
Prints `wat, x = 0` on 0.7.1 and master.
This shouldn't compile, error capturing else requires a capture on the if as well (except maybe in the case of `error{...}!void`, which this is not).

**Comment by g-w1** [comment]
Dupe of #8076 i think.

**Comment by SpexGuy** [comment]
Yep, looks like it.  This one is runtime and that one's comptime but they are probably both the same bug internally.
