### ISSUE TITLE
Proposal: Allow if |payload| syntax with tagged unions

### ISSUE THREAD

**Issue by batiati** [ziglang/zig#8109]
## Motivation

In some cases, there is no need to perform an exhaustive `switch` operation over tagged unions.
Like in Rust's `if let`, matching just one specific tag is enough.

Considering the following definition:

```zig
const Cell = union(enum) {
    Int: i32,
    String: []const u8,
    Empty: void
};
```

Suppose we have an `accumulate` method, that performs the sum only for the integer cells:

```zig
pub fn accumulate(cells: []Cell) i32{

    var sum: i32 = 0;
    for(cells) |cell| {

        //We must match the tag and extract the payload
        switch (cell) {

            .Int => |value| {
                sum = sum + value;
            },
            else => {}
        }
    }

    return sum;
}
```

## Proposal

Allow the `if` statement to extract the tagged union's payload.
The same `accumulate` method could be written in the following syntax:

```zig
pub fn accumulate(cells: []Cell) i32{

    var sum: i32 = 0;
    for(cells) |cell| {

        //Allow to matching the tag and extract the payload
        if (cell.Int) |value| {
            sum = sum + value;
        }
    }

    return sum;
}
```

## Considerations

- How should behave tags with `void` payload? 

- Considering all `if` + `|payload|` possibilities be used together, payload extraction must follow some precedence

```zig
//Returns error, or null or Cell
pub fn getCell(i: i32, j: i32) !?Cell {
   // do something
   return null;
}

pub fn checkValue() i32{

   // First, check for errors
   if (getCell(0,0)) |maybe| {

        // Then, check for null
        if (maybe) |cell| {

            //Finally, check the tag
            if (cell.Int) |value| {
                return value;
            } 
        }
   } else |err| {
       // ...
   }

   return 0;
}
```

**Comment by Luukdegram** [comment]
Personally, I don't see much benefit over status quo:
```zig
pub fn accumulate(cells: []Cell) i32{
    var sum: i32 = 0;
    for(cells) |cell| {
        // Status quo allows enum literals to be coerced to tagged unions and therefore we can use this:
        if (cell == .Int) {
            sum = sum + cell.Int;
        }
    }
    return sum;
}
```
You could implement some function in userland (maybe even in `std.meta`) that unwraps a tagged union into an optional that returns `null` if the active tag doesn't match the given tag, or the activetag's actual value in case it does.

**Comment by batiati** [comment]
@Luukdegram 
It was so intuitive for me to extract the payload using `if (...) |payload|` that I didn't even consider the possibility of ```if (cell == .Int)```!

Many thanks for the example!

**Comment by batiati** [comment]
For the sake of closure, let me expose 2 minors arguments before closing this issue:

- **Safety**:

Would it be safer to prohibit accessing an arbitrary tag directly, and require always using `|...|` for payload extraction? Could it avoid some runtime errors?

I really don't know about other use cases, and probably it has a very good reason for tagged unions to be that way ... but it is as unsafe as derref a null pointer.

```zig
pub fn accumulate(cells: []Cell) i32{
    var sum: i32 = 0;
    for(cells) |cell| {
        // It can panic: access of inactive union field
       sum = sum + cell.Int;
    }
    return sum;
}
```

- **Coherence**:

As I said before, It was so intuitive for me to use `|...|` that I was convinced that `switch` was my only option to access a tagged union payload.

(...)

Thanks again everyone, zig is amazing!

**Comment by g-w1** [comment]
> Would it be safer to prohibit accessing an arbitrary tag directly, and require always using `|...|` for payload extraction? Could it avoid some runtime errors?

Zig catches this at runtime. I think zig should allow the programmers to program how they want. They should accept the risk of doing so.

**Comment by gpanders** [comment]
> Personally, I don't see much benefit over status quo:
> 
> ```zig
> pub fn accumulate(cells: []Cell) i32{
>     var sum: i32 = 0;
>     for(cells) |cell| {
>         // Status quo allows enum literals to be coerced to tagged unions and therefore we can use this:
>         if (cell == .Int) {
>             sum = sum + cell.Int;
>         }
>     }
>     return sum;
> }
> ```

The same is true for optional types, no?

```zig
pub fn accumulate(cells: []?i32) i32 {
    var sum: i32 = 0;
    for (cells) |cell| {
        if (cell != null) {
            sum = sum + cell.?;
        }
    }
}
```

Yet Zig provides the `if` syntax here both for ergonomic and safety reasons.

One other benefit of this proposal is that it makes refactoring efforts easier and less bug-prone, as you wouldn't need to replace every single instance of `.Int` if the name of the tag changes.

**Comment by matklad** [comment]
Yeah, given how optionals work, I would expect `if (Union.Variant) |var|` syntax to just work. But perhaps it is a mistaken expectation, as this syntax would be ambiguous: 

```zig
const T = union(enum) {
    Bool: bool
};

fn ambiguity(t: T) void {
    if (t.Bool) {

    }
}
```

`if (expr.Variant)` can be interpreted either as matching `expr` against `Variant`, or as asserting that `expr` is `Variant`, extracting the boolean payload, and branching on that.

**Comment by dnut** [comment]
> if (expr.Variant) can be interpreted either as matching expr against Variant, or as asserting that expr is Variant, extracting the boolean payload, and branching on that.

There's an easy way to distinguish those cases.

This could check that the value is true:
```zig
if (t.Bool)
```
And this could check that the variant is Bool:
```zig
if (t.Bool) |_|
```

Even if it is distinguishable, you might argue about it being sufficiently clear and intuitive. Personally, I think it is clear enough, but maybe there is room for improvement.

With optionals, there is an additional difference between the two scenarios that helps with clarity. One case would look like `t.?`, while the other would just be `t`. Here though, both cases are in the form `t.Bool`.

To be more consistent with optionals, and with how tagged unions are handled in switch statements, checking the tag could instead look something like this:
```zig
if (t) .Bool => |_|
```
