### ISSUE TITLE
while not evaluated correctly

### ISSUE THREAD

**Issue by edt-xx** [ziglang/zig#8119]
Refer to the code below

[stage.zip](https://github.com/ziglang/zig/files/6064851/stage.zip) or https://pastebin.com/0b5m7HZB

build-exe it and run with something like ./stage 2>&1 | more

in the output I get: 

info: peekto Stage@7fff876cade0 inC *Conn@7f6485d49018

info: peekto Conn@7f6485d49018 in false 12297829382473034410

info: while exited

The second info: peekto reports in as false (line 64)
line 65 should then evalue as true and the while block executed.
this does not happen.

The code is WIP and I do not expect it to do anything useful (yet)

Thanks

**Comment by edt-xx** [comment]
If I change (line 18) Conn = packed struct ...
without changing anything else, it starts to work.  From what I understand packed or otherwise it should work.

**Comment by andrewrk** [comment]
Bug filed against deleted codebase; no reduction. Not worth any further investigation.
