### ISSUE TITLE
Anonymous tuples cannot coerce to tuple structs

### ISSUE THREAD

**Issue by edt-xx** [ziglang/zig#8136]
I am trying to workout how I can dynamically get zig to run pipes.

// this needs to be parsed to create the Stage and Conn instances and the gather the 
// info need to call @asyncCall which includes a Tuple.   Also the Tuple need to be able to 
// include variables like the various print implementations

    pipe.pipe("gen(100) | a: exactdiv(5) | b: fanin | console ? a: | exactdiv(7) | b:")

// the test pipe just outputs the numbers below 100 that are divisible by 5 and 7

With help, I've figured out how to handle functions (gen, exactdiv etc) using structs and @field but generating the Tuple for the last argument of @asyncCall is not working.

 const tt =  std.meta.Tuple(&[_]type {*Stage,u32});
 var xxx:tt = undefined;
 xxx = .{&p[2],7};
    
./stage.zig:329:12: error: type 'std.meta.struct:1160:38' does not support array initialization
    xxx = .{&p[2],7};

and 

const tt =  std.meta.Tuple(&[_]type {*Stage,u32});
var xxx:tt = undefined;
std.log.info("{any}",.{@typeInfo(tt)});

/usr/lib/zig/std/fmt.zig:563:17: error: values of type 'std.builtin.StructField' must be comptime known, but index value is runtime known
                for (value) |elem, i| {

This is with 0.8.0-dev.1385+3dd8396a5

Thanks

**Comment by pfgithub** [comment]
```
./stage.zig:329:12: error: type 'std.meta.struct:1160:38' does not support array initialization
xxx = .{&p[2],7};
```

Tuples don't seem to support `.{expression, expression}` array initialization syntax right now for some reason. This is probably a bug. You can use struct initialization as an alternative:

```zig
xxx = .{ .@"0" = &p[2], .@"1" = 7 };
```

---

```zig
const tt = std.meta.Tuple(&[_]type {*Stage,u32});
var xxx:tt = undefined;
std.log.info("{any}",.{@typeinfo(tt)});

/usr/lib/zig/std/fmt.zig:563:17: error: values of type 'std.builtin.StructField' must be comptime known, but index value is runtime known
for (value) |elem, i| {
```

zig fmt does not seem to support printing the typeInfo union right now. This is a bug with the standard library. A workaround is doing the print at compiletime:

```zig
    const printed = comptime blk: {
        var buf: [255]u8 = [_]u8{0} ** 255;
        break :blk std.fmt.bufPrint(&buf, "{any}", .{@typeInfo(tt)});
    };
    std.log.info("{s}", .{printed});
```

---

The best place to ask types of questions is in one of the [community spaces](https://github.com/ziglang/zig/wiki/Community) for zig.
