### ISSUE TITLE
Proposal: Make slice lower bound optional

### ISSUE THREAD

**Issue by Snektron** [ziglang/zig#8143]
The current slice syntax `a[start .. end]` allows one to omit the `end` to implicitly state that the new slice extends to the end of the parent slice or array's range. Here I propose to also make the `start` optional, and default to the beginning of the parent slice or array's range.

Advantages:
- It's more consistent, as omitting any explicit offset simply means 'bounds of parent'.
- Writing `array[..]` looks a little nicer than `array[0..]`, `array[..n]` looks nicer than `array[0..n]`, and `array[x..][..y]` looks nicer than `array[x..][0..y]` (in my opinion).
- It saves a whole character of typing, but its decently common (currently totaling about 1500 occurrences in the standard library and self-hosted compiler source).

Disadvantages
- Requires implementation work of course, but it doesn't seem like this would be very time consuming.
- Makes the language grammar a tiny amount more complicated.

Other notes:
- One could argue that omitting the `end` is much more justified than omitting the start, considering the start is only a single 0 while the end involves much more text.

In the end, it just comes down to language aesthetics, but i'm personally a fan of the change.

**Comment by Snektron** [comment]
:(

**Comment by s-ol** [comment]
@andrewrk Could you elaborate on why this proposal was declined?

**Comment by haolian9** [comment]
I think this issue was closed due to #1050
