### ISSUE TITLE
zig cc/c++ don't generate assembly code

### ISSUE THREAD

**Issue by kassane** [ziglang/zig#8153]
After some tests of projects using `zig cc` and `zig c++` compiler, I realized that the object file is generated with command `-c`, but the command `-S` when executing it the assembly file is not generated.

**Release test:**
Zig 0.7.1 and latest master

**Comment by partouf** [comment]
Can confirm this behaviour of `-S` for `zig cc` not having the wanted result (no files are created nor is there any cout/cerr)

Was testing this for the Compiler Explorer implementation. Seems to affect >= 0.7.0, but it still worked in 0.6.0
https://github.com/compiler-explorer/compiler-explorer/pull/2434#issuecomment-786997619

**Comment by andrewrk** [comment]
Thanks for the report! Will prioritize this so you can get unblocked on the compiler explorer PR.

**Comment by andrewrk** [comment]
> Thanks for the report! Will prioritize this so you can get unblocked on the compiler explorer PR.

Oof that really took a long time for me to get around to. Sometimes I get in over my head. Sorry about that.

Anyway I fixed it in d11f42c2b24e80388e1ea648ee97fae612fd76a4.
