### ISSUE TITLE
LLVM12: linker error when compiling MIPS{,el} testsuite

### ISSUE THREAD

**Issue by LemonBoy** [ziglang/zig#8155]
Minimal reproducer:

```asm
	.text
foo:
	lui	$2, %hi(bar)
	addiu	$2, $2, %lo(bar)

	.section	.rodata.str1.1,"aMS",@progbits,1
	.zero 0x8000
bar:
	.asciz	"hello"
```

The `0x8000` gap simulates the previous content in the `.rodata.str1.1` section, it's big enough to get sign-extended and small enough to fit in 16bit. The problem is in LLD's `MarkLive::resolveReloc`, the code is not able to handle the HI16/LO16 relocation pairs.

CC @maskray

**Comment by MaskRay** [comment]
I know nearly nothing about mips but I can poke some mips folks...

**Comment by LemonBoy** [comment]
> What is wrong?

Wrong triple, it's the 32bit one that's showing this problem.

```
llvm-mc-12 -triple mipsel-linux-none -filetype obj -o - /tmp/foo.s | llvm-objdump-12 -dr -

00000000 <foo>:
       0: 01 00 02 3c  	lui	$2, 1 <foo+0x1>
			00000000:  R_MIPS_HI16	.rodata.str1.1
       4: 00 80 42 24  	addiu	$2, $2, -32768 <foo+0xffffffffffff8000>
			00000004:  R_MIPS_LO16	.rodata.str1.1

```

**Comment by andrewrk** [comment]
[Upstream bug report](https://bugs.llvm.org/show_bug.cgi?id=49821)

**Comment by mikdusan** [comment]
update: upstream patch has been merged to llvm-project branch release/12.x
and hopefully we see it in a future tag (llvmorg-12.0.1-rc2) before 12.0.1 is released
