### ISSUE TITLE
Reexport pbkdf2 error

### ISSUE THREAD

**Issue by x13a** [ziglang/zig#8156]
Function `pbkdf2` can raise `Pbkdf2Error`. This error needs to be exported.

**Comment by jedisct1** [comment]
Or better, all the KDFs should share the same error set. Right now, error sets are not used much (if at all, besides in Pbkdf2) in `std/crypto`. But that can be done for 0.8.0.

**Comment by jedisct1** [comment]
I'll take care of this over the weekend. Thanks for the heads up :)
