### ISSUE TITLE
translate-c: single-statement for loop + single-statement if statement with assignment produces invalid Zig

### ISSUE THREAD

**Issue by ehaas** [ziglang/zig#8159]
Example:
```c
#include <stdlib.h>
int main(void) {
    int i;
    for (i = 0; i < 5; i++)
        if (i == 0) i = 10;
    if (i != 11) abort();
    return 0;
}
```

```
./forifassign.zig:1036:46: error: invalid left-hand side to assignment
        while (i < @as(c_int, 5)) : (i += 1) if (i == @as(c_int, 0)) i = 10;
```

If the C code is modified so that the `for` loop and/or the `if` statement have braces, the code translates correctly.

If the Zig code is modified to have braces on the while loop, it compiles and runs correctly, although I'm not sure if this is the correct solution.

**Comment by ifreund** [comment]
Related: https://github.com/ziglang/zig/issues/5731

**Comment by ehaas** [comment]
@Vexu I can fix this one - would you prefer "single-statement bodies always get braces (unless they are compound or null statements)" or "single-statement bodies only get braces if they are assignments"

**Comment by Vexu** [comment]
I'd prefer to only put assignments in braces since they're the only ones affected, but either is fine.
