### ISSUE TITLE
Bad default zig fmt style for functions with long parameters 

### ISSUE THREAD

**Issue by glyh** [ziglang/zig#8164]
I've just write some functions with long arg list, separating different parameters into multilines , however, it seems like zig fmt want everything in the same line.

**Comment by andrewrk** [comment]
If you put a trailing comma after the last argument, zig fmt will put each parameter on its own line.

**Comment by glyh** [comment]
> If you put a trailing comma after the last argument, zig fmt will put each parameter on its own line.

Opps, sorry.  I think we need some more rich document

**Comment by glyh** [comment]
dd

**Comment by andrewrk** [comment]
I agree
