### ISSUE TITLE
Review musl libc stub collection

### ISSUE THREAD

**Issue by LemonBoy** [ziglang/zig#8178]
A [leddit user](https://old.reddit.com/r/Zig/comments/lzqgxf/trying_to_crosscompile_to_mips_with_zig_cc/) hit this problem where the presence of `_REDIR_TIME64` (on ARM32, i386, PPC32 and MIPS32) wreaks havoc.

The plain symbols are left out for compatibility sake, the ones suffixed with `_time64` (and prefixed with `__`) are replaced on the fly with some symbol aliasing magic in `sys/time.h`.

cc @ifreund

**Comment by ifreund** [comment]
The current stubs were generated from a 64 bit libc.so and produce a stub libc.so with identical objdump output. I assume the fix here is either adding a different set of stubs for 32 bit systems or having a different set of stubs for all targets. I'm not sure if the latter is strictly necessary or not as I don't know how much the interface of libc.so as shown by objdump varies between targets.

**Comment by LemonBoy** [comment]
> I don't know how much the interface of libc.so as shown by objdump varies between targets

I'd avoid duplicating the stub file for each architecture if possible, the 32/64 split should be enough.

**Comment by andrewrk** [comment]
Another problem to solve is making the stub generating script aware of aliases:

```
<dalias> andrewrk, making __environ, _environ, environ separate rather than aliases liek they're supposed to be will cause mislinking
<dalias> ld needs to see that environ is a weak alias for __environ
```
