### ISSUE TITLE
std.os.ChildProcess should use an eventfd instead of pipe on linux for passing the error code

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#819]
http://man7.org/linux/man-pages/man2/eventfd.2.html

        Applications can use an eventfd file descriptor instead of a pipe
       (see pipe(2)) in all cases where a pipe is used simply to signal
       events.  The kernel overhead of an eventfd file descriptor is much
       lower than that of a pipe, and only one file descriptor is required
       (versus the two required for a pipe).

**Comment by stratact** [comment]
I would like to take this challenge but I want to support FreeBSD as well with `kqueue`/`kevent`.

Thoughts?

**Comment by Sircular** [comment]
Isn't this already closed? ChildProcess seems to be using `eventfd` on Linux. Is this open so other platforms can be added?

**Comment by sskras** [comment]
@Sircular commented [on May 26, 2020](#issuecomment-634248099):

> ChildProcess seems to be using `eventfd` on Linux. Is this open so other platforms can be added?

As a newbie, I second this question.

**Comment by Vexu** [comment]
Revert reverted in #3922
