### ISSUE TITLE
Proposal: Optional else clause on errdefer

### ISSUE THREAD

**Issue by AssortedFantasy** [ziglang/zig#8190]
## Proposal

As it stands we have `defer` for unconditional execution, and `errdefer` for conditional execution (on the condition being an error return).

I'll admit that this is usually enough, but I was thinking that it would be nice to have dedicated syntax for the case of a valid return. I think its one of those relatively minor language changes that has niche uses but just about clears the hurdle to be added.

I also considered being able to capture the non-error return for the else block. I'm not entirely sure about that, but I don't see any reason it shouldn't work. You can see what I mean in the code below.

Also consider that all the other conditional control flow mechanisms provide `else` clauses. `if` `while` `for`.

Sorry if this has been proposed before, I couldn't find it if it was.

## Example code for how the proposal should work

```zig
fn foo() !u32 {
    defer {
        // Always executed
    }

    errdefer {
        // Executed on error
    }

    errdefer {

    } else { // Proposal
        // Executed if an error does not occur
    }

    errdefer |e| { // You can capture the error on errdefer

    } else |non_error_return| { // Possibly capture the return value

    }

    return 0;
}
```

As it stands this functionally can be accomplished like this.

```zig
fn current_way_to_accomplish() !void {
    // Currently can be implemented as so.
    var error_occured: bool = false;


    defer {
        if (!error_occured) {
            // Executes if an error doesn't occur.
        }
    }
    // Deactivates the above defer
    errdefer error_occured = true;
}

```

## Use case

This is handy for logging, or just in general when you want something to happen on a successful return. 

Example usage:
```zig
fn handle_client_connecting() !void {
    errdefer {
        std.log("{s}", .{"Failed to Connect client"});
    } else {
        std.log("{s}", .{"Succesfully connected client"});
    }

    // Windy code below where adding a success log just before
    // every non-error return block is a pain.
}
```

**Comment by mlawren** [comment]
For a more visual description of the various scenarios

| Return Status | defer | errdefer | (proposal) |
|---                  |---       |---           |---    |
| ok                 | x         |               | x      |
| error             | x         | x             |        |

What feels slightly off in your proposal is that it makes the ok-only defer dependent on `errdefer` block. What if I don't need one? So I would instead propose `okdefer`:

```zig
fn handle_client_connecting() !void {
    defer {
        // clean up whatever resources need to be unconditionally
    }
    errdefer {
        std.log("{s}", .{"Failed to Connect client"});
    }
    okdefer {
        std.log("{s}", .{"Succesfully connected client"});
    }

    // Windy code below where adding a success log just before
    // every non-error return block is a pain.
}
```

**Comment by mlawren** [comment]
I forgot to add that `okdefer` could also capture the return value just like `errdefer`:

```zig
okdefer |retval| {
    // do something with "retval"
}

**Comment by AssortedFantasy** [comment]
I did consider the prospect of something like `okdefer` , but personally I kind of leaned against it for a few reasons.


1) I didn't really like the idea of adding keywords. 
2) It felt more natural to extend a already existing feature `errdefer` then to add additional functionality.
3) It seemed kind of intuitive that you could use `else` on `errdefer` since you can on basically any other control flow.
4) Linguistically I would find it slightly weird if someone mentioned something like "defer if okay/valid" because I wouldn't be sure what they meant by valid, I would find it more specific/less (possibly) confusing if someone said "defer if not error" because I know exactly what an `error` is. So I could live with an "okaydefer" being the shadow of `errdefer` 
5) I didn't think that a pure defer on valid would be all that common. After all zig is at 0.7.1 and this hasn't really been brought up all that much as far as I am aware. So in the rare instances it was going to be used `errdefer {} else { ... }` isn't really that much boilerplate.


If I'm being totally honest, the motivation for why the proposal looks like this is so that it minimizes the need for justification to exist. 

In my eyes if someone comes along and proposes a new kind of control flow by starting off with a new keyword then they really need to produce a pretty good argument for why it should be implemented. Because that's just more stuff that makes zig bigger and is going to fill peoples head space. It means that anytime anyone stares at an `okaydefer` or whatever that keyword would be called they need to go learn what it is that it does. It means that it would need a whole paragraph in the documentation to go along with it.

It seemed more coy to just propose an extension to `errdefer`, like in the sense "hey you can use `else` with `if` `while` `for` and you already know how it works there, maybe you can skirt the mental burden of knowing how this new control flow works by leveraging your prior knowledge of `else` and `errdefer`.

Of course I recognize that these are all kind of superficial reasons and there isn't a whole lot of difference. So I get what you are getting at. But this is my thinking.

**Comment by lithdew** [comment]
How about generalizing the `defer` syntax to capture the return value as a payload? On a less important note, it also lessens the need for there being an `errdefer` keyword. That being said, it is more verbose to type.

e.g.

```zig
fn testFunctionA(val: u32) !u32 {
    defer |result| {
        const unwrapped_result = result catch |err| switch (err) {
            error.A => {},
            error.B => {},
            else => {}
        };

        // ... do something with 'unwrapped_result' here.
    }

    if (val == 0) {
        return error.EOF;
    }

    return val;
}

fn testFunctionB(val: u32) !u32 {
    defer |result| result catch switch (err) {
        error.A => {},
        error.B => {},
        else => {}
    };

    if (val == 0) {
        return error.EOF;
    }

    return val;
}
```

**Comment by Mouvedia** [comment]
> So I would instead propose `okdefer`

Id prefer to be consistent with the existing `errdefer` and pick `succdefer` or `outdefer` for success/error or stdout/stderr respectively. The correspond keyword for `okdefer` would be `kodefer` not `errdefer`.

**Comment by mlawren** [comment]
With a bit of distance I like the direction that @lithdew's suggestion moves in. `errdefer` or any kind of `xxxdefer` that puts the special case in _front_ of the primary keyword is not cognitively elegant.

How about this:

```zig
fn testFunctionA(val: u32) !u32 {
    defer {     // unconditionally run a block on the way out
    }

    // only call on success
    defer succ {
    }
    defer succ |retval| {     // optionally capturing the return value
    }

    // only called on error
    defer err {
    }
    defer err |e| {     // using error value optional
    }

    if (val == 0) {
        return error.EOF;
    }

    return val;
}
```

**Comment by matu3ba** [comment]
@AssortedFantasy How much more verbose does your code get on that? Does logging require the above solution to be used on every logging invocation?

**Comment by ifreund** [comment]
> This is handy for logging, or just in general when you want something to happen on a successful return.

Why not just put the code right before the return then? I see no need for the proposed change:
```zig
fn foo() !void {
    errdefer {
        log("failed");
    }
    try bar();
    log("success");
    return;
}
```

**Comment by Mouvedia** [comment]
> `defer succ {`
> `defer err {`

@mlawren No need for the abbreviations in zig IMHO; `defer success {` and `defer error {` would be just fine.
I don't mind a few more keystrokes in this case.

**Comment by mlawren** [comment]
@Mouvedia I was just following the `errdefer` precedent, and for experienced/power users there are advantages to shorter forms. But one can definately argue the longer forms have more clarity for readers of the code.

It is just such a shame that "success" is such an awful word to type for the left hand :-(. `defer ok` doesn't seem to be liked by others but perhaps `defer normal {` works?

**Comment by Mouvedia** [comment]
Here's another proposal that might be too radical:
```
// current defer { would become
defer finally {…}

// success defer
defer |_| {…}

// error defer
defer catch |e| {…}

// both
defer |v| {…} catch |e| {…}

**Comment by mlawren** [comment]
I had considered that at one point as well. Two issues though

1. There is a lot of `errdefer` code that doesn't do anything with the error. Having to `catch |e|` only to ignore it doesn't make sense.
2. `catch`ing an error in normal code stops the error unless it it re-thrown/returned. That model doesn't match well with multiple defer error blocks which will be called regardless (and can't be returned from).

**Comment by Mouvedia** [comment]
> That model doesn't match well with multiple defer error blocks which will be called regardless (and can't be returned from).

That's a good point. I think we should separate the pattern matching from the proposal though.

**Comment by 71** [comment]
This was closed as completed, but as far as I can see this wasn't accepted or implemented (IIRC GitHub didn't have "close as not planned" in 2021)?

Even if the discussion is closed, I'd like to add two use cases for the "general `defer`" proposed by @lithdew in case something like this is brought up again in the future:

### Update state on success

In a parser, I'd like to advance some cursor (by updating a field) **if the current function does not yield an error**, but I have several `return`s. The easiest for me would be to have the following line at the top of the function:

```zig
defer |result| if (result) self.offset += read;
```

### Test helper which prints context

To test a parser, I have an iterator which, given some input buffer, yields multiple ways this buffer can be split. The idea is that the parser has several fast paths that use SIMD, so I want to run tests on both the slow paths and the fast paths. To improve debugging, I also want to print the current split on error, something like

```zig
var iter: SplitIterator = .init(buffer);
errdefer iter.printDebuggingInformation();
```

But the `SplitIterator` performs a few allocations, so actually I need

```zig
var iter: SplitIterator = try .init(std.testing.allocator, buffer);
defer iter.deinit(); // Make sure that this comes first!
errdefer iter.printDebuggingInformation();
```

If this proposal was accepted, I could have the following instead:

```zig
var iter: SplitIterator = try .init(std.testing.allocator, buffer);
defer |result| iter.deinit(result); // Print information if `result` is an error.
```

Although I admit that this is a small improvement only.
