### ISSUE TITLE
Change json.TokenStream to use an io.Reader

### ISSUE THREAD

**Issue by silversquirl** [ziglang/zig#8207]
This would allow streaming the data from a file or a network socket, which is what the name of the type implies is happening. While `TokenStream` itself is simple enough that a user could reimplement it in this way if needed, changing the standard library's version allows using `json.parse` in a streaming fashion.
Existing code that parses from slices could be easily changed to use a `FixedBufferStream`.

**Comment by fengb** [comment]
There are major implications for this change: the TokenStream as currently designed requires existing memory for every token. To do this right requires the ability to "bring your own buffer" and also resolving arbitrarily large string tokens.

I've built my own streaming parser and I'm not sure this API is stdlib ready:
- [implementation](https://github.com/fengb/zCord/blob/iguana/src/util.zig#L6-L590)
- [consumption](https://github.com/fengb/zCord/blob/iguana/src/main.zig#L481-L519)

**Comment by daurnimator** [comment]
This would require it to additionally take an allocator as e.g. strings can be arbitrarily long.
As allocators currently do not work at comptime, that would be parsing json at comptime.
i.e. we shouldn't do this yet

**Comment by thejoshwolfe** [comment]
This is implemented in Zig 0.11.0. The api needed to be overhauled. See https://ziglang.org/download/0.11.0/release-notes.html#JSON for an upgrade guide between the two APIs.
