### ISSUE TITLE
EINVAL is a possible error when iterating under /proc

### ISSUE THREAD

**Issue by dgbuckley** [ziglang/zig#8209]
On linux, when iterating directories under /proc on a system with a zombie process then getdent can return EINVAL. Right now this error is unreachable which doesn't allow it to be handled when using the Dir.iterator pattern.

If you create a zombie process (you could use this: https://stackoverflow.com/a/25228579/704831) then any attempt to read the /proc/$PID directory results in EINVAL.

```bash
$ ls /proc/5739/net/
ls: reading directory '/proc/5739/net/': Invalid argument
```

**Comment by git-bruh** [comment]
Fixed with https://github.com/ziglang/zig/pull/11295
