### ISSUE TITLE
@cImport of string literal does not provide sentinel array

### ISSUE THREAD

**Issue by gpanders** [ziglang/zig#8215]
This is an extension of a question I asked on the [mailing list](https://lists.sr.ht/~andrewrk/ziglang/%3CYEpRAzVCqVbmFVRT%40gpanders.com%3E).

When `@cImport`ing header files that define string literals, Zig does not import these as type `[N:0]u8` (where N is the length of the string) but rather as `[N+1]u8` (where the +1 is from the null sentinel value).

Here's an example:

**config.h**:
```c
const char OPTION_FOO[] = "some value";
```

**test.zig**:
```zig
test {
    const config = @cImport(@cInclude("config.h"));
    const foo: []const u8 = config.OPTION_FOO;
}
```

Running

```bash
zig test -lc -I. test.zig
```

results in

```
./test.zig:3:35: error: expected type '[]const u8', found '[11]u8'
    const foo: []const u8 = config.OPTION_FOO;
```

This also precludes you from using e.g. `std.mem.span`:

```zig
test {
    const std = @import("std");
    const config = @cImport(@cInclude("config.h"));
    const foo = std.mem.span(config.OPTION_FOO);
}
```

results in

```
/usr/local/lib/zig/std/mem.zig:546:17: error: invalid type given to std.mem.Span
```

`@cImport` used to import C string literals as type `[*c]const u8`, which *could* be passed to `std.mem.span` to obtain a `[]const u8` string in Zig, but this no longer works. This seems to have been changed in https://github.com/ziglang/zig/pull/7849.

My question is two-fold:

1. Is it intended behavior for C string literals to be imported with type `[N+1]u8` rather than `[*c]const u8` or `[N:0]u8`? To be frank, I think this is quite confusing and a potential footgun, as now the sentinel value has to be manually cleaned up/handled in Zig code instead of `@cImport` simply "doing the right thing".
2. Regardless of the answer to (1), what is the method for converting a C string literal defined as in the above case into a sentinel-less Zig string? As I pointed out above,`std.mem.span` does not work. Providing a pointer to the array also does not work as expected (e.g. `&config.OPTION_FOO` results in `*[11]u8` which *can* be coerced to `[]const u8` with a value of `"some value\0"`)

Thanks!

**Comment by ifreund** [comment]
> Regardless of the answer to (1), what is the method for converting a C string literal defined as in the above case into a sentinel-less Zig string? As I pointed out above,`std.mem.span` does not work. Providing a pointer to the array also does not work as expected (e.g. `&config.OPTION_FOO` results in `*[11]u8` which _can_ be coerced to `[]const u8` with a value of `"some value\0"`)

This should do the trick:
```zig
const my_slice = std.mem.spanZ(&config.OPTION_FOO);
```

**Comment by ifreund** [comment]
In this case the following would also work:
```zig
const my_slice = config.OPTION_FOO[0 .. config.OPTION_FOO.len - 1 :0];
```

**Comment by gpanders** [comment]
Right, that is what I meant in my original comment:

>I think this is quite confusing and a potential footgun, as now the sentinel value has to be manually cleaned up/handled in Zig code instead of @cImport simply "doing the right thing".

**Comment by ehaas** [comment]
@gpanders with the latest update you should be able to do the following:

```zig
    const array: [10:0]u8 = config.OPTION_FOO;
    const ptr: [*:0]const u8 = &config.OPTION_FOO;
    const span: [:0]const u8 = std.mem.span(&config.OPTION_FOO);
```

**Comment by gpanders** [comment]
Thanks!
