### ISSUE TITLE
Bus error on Mac arm64 using threadlocal

### ISSUE THREAD

**Issue by goncalopalaio** [ziglang/zig#8216]
```
threadlocal var x: i32 = 100;
pub fn main() !void {
    x += 1;
}
```

Not entirely sure if this is due to user error but this is exiting with an 138 exit code:

```
➜  zig run a.zig ; echo "Exited with: "$?
[1]    7626 bus error  zig run a.zig
Exited with: 138
```

I'm running zig installed through homebrew (brew install zig --HEAD)

uname -a: Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64

**Comment by kubkon** [comment]
Related #7527.
