### ISSUE TITLE
macOS support for `-fcompiler-rt`

### ISSUE THREAD

**Issue by rtfeldman** [ziglang/zig#8218]
Currently using `-fcompiler-rt` on macOS [produces this error](https://github.com/ziglang/zig/blob/e9a038c33bbf171695b08540536f307b9e418173/src/Compilation.zig#L1220-L1226):

```
Embedding compiler-rt into macho objects is not yet implemented.
```

Per a conversation with @andrewrk, opening this as a tracking issue!

**Comment by andrewrk** [comment]
This was implemented in  #9440
