### ISSUE TITLE
Block label can't be used on switch

### ISSUE THREAD

**Issue by rgreenblatt** [ziglang/zig#8226]
EDITED:
```zig
pub fn main() void {
    var k : i32 = 0;
    var s : i32 = 1;
    const v = switch (s) blk: {
        1 => {
            if (k == 0) {
                break :blk 8;
            }
            // some code here...
            //
            break :blk 2;
        },
        // another case
        2 => {
            if (k == 2) {
                break :blk 8;
            }
            // some code here...
            //
            break :blk 2;
        },
        else => 9,
    };
}
```
https://zig.godbolt.org/z/K76eae

**Comment by SpexGuy** [comment]
That isn't a normal block, it wouldn't make sense to break it.  What do you expect this to do?

**Comment by rgreenblatt** [comment]
> That isn't a normal block, it wouldn't make sense to break it. What do you expect this to do?

I've edited my post to show a better example. It would basically be a shorthand for labeling all of the cases.

**Comment by SpexGuy** [comment]
Hmm, so this would be a workaround:
```zig
    const v = blk: {
      break :blk switch (s) {
        ...
      }
    };
```
I do think we could potentially allow `blk: switch (s) { ... }`, similar to labeled for and while expressions.  But IMO it's weird to allow labeling the switch scope itself, since it's not an expression.  It feels the same to me as allowing one of these things:
```zig
const x = switch (y) y;
const T = struct blk: { f: usize };
const v = T blk: { .f = 4 };
fn foo() T blk: {}
```

**Comment by Mouvedia** [comment]
> I do think we could potentially allow `blk: switch (s) { ... }`,

Are you talking about #8220?

**Comment by andrewrk** [comment]
Superseded by #8220 which does incorporate this use case.
