### ISSUE TITLE
zig test should offer more flexible inputs

### ISSUE THREAD

**Issue by finjo-the-great** [ziglang/zig#8234]
It would really be helpful if I could run a command like below to run all tests within the src directory:

    zig test src

I'm sure I can come up with the correct grep/find command to do something equivalent to this, but it would really be a lot easier if I could run a command like above.

**Comment by LemonBoy** [comment]
This problem is already solved by using a nameless `test` block

```
test {
    _ = @import("src/test_file_1.zig");
    // ...
    _ = @import("src/test_file_N.zig");
}
```

**Comment by kenaryn** [comment]
This hint shall be added to the Frequently Asked Questions in a "Testing" sub-section before being closed.

**Comment by finjo-the-great** [comment]
I guess #8221 is worth noting here as well if it's a documentation issue.

Though I do still feel it would be nice to have a way to do something like this without having a list of files to maintain. Maybe some kind of comptime function could work? Then I could do something like:

```
test {
  testSuite("src");
}
```

This would import every source file within that directory. Maybe some sort of glob syntax so you could do something like:

```
test {
  testSuite("src/prefix_*.zig");
}
```

**Comment by g-w1** [comment]
you can do `std.meta.refAllDecls(@This());` to reference all constants (basically all imported files).

**Comment by finjo-the-great** [comment]
> you can do `std.meta.refAllDecls(@This());` to reference all constants (basically all imported files).

I see that there's that method in `std.meta`, but there appears to also be one in `std.testing`. Is the latter what should be used?

**Comment by Mouvedia** [comment]
> This hint shall be added to the Frequently Asked Questions in a "Testing" sub-section or even demonstrated as a example at ziglearn.org before being closed.

https://github.com/ziglang/zig/wiki/Zig-Newcomer-Programming-FAQs
