### ISSUE TITLE
os.ListenError is private

### ISSUE THREAD

**Issue by vktec** [ziglang/zig#8243]
It's part of a public API, and hence should be public so it can be used in merged error sets returned by functions calling `os.listen`.

**Comment by YerinAlexey** [comment]
That's weird. But you can still match those errors with `error.Name` (e.g. `error.AddressInUse`):

```zig
os.listen(...) catch |err| {
    switch (err) {
        error.AddressInUse => @panic("Address in use!"),
        /* snip */
    }
};
```

**Comment by g-w1** [comment]
@YerinAlexey This is useful in a case when you have a function with an explicit error return set and want to do merging: 
```zig
pub fn thing() (std.os.ListenError || MyErrorSet)!void {
```

**Comment by YerinAlexey** [comment]
@g-w1 I know that, just suggesting a workaround for this issue. The proper fix is making that error union public
