### ISSUE TITLE
Master branch macOS builds broken on ARM64 due to AVX use

### ISSUE THREAD

**Issue by holmesmr** [ziglang/zig#8249]
Binaries for macOS on master currently don't work on Apple Silicon Macs as the statically linked C++ standard library is built with AVX instructions, which Rosetta 2 doesn't implement, leading to a SIGILL when attempting to run the compiler. Running any command fails as the offending instructions are present in the STL string routines.

Crash captured from LLDB:
```
error: module importing failed: invalid pathname
(lldb) target create "zig"
Current executable set to 'zig' (x86_64).
(lldb) run
Process 39444 launched: '/Users/cepheus/zig-macos-x86_64-0.8.0-dev.1471+4e9894cfc/zig' (x86_64)
Process 39444 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x000000010442b772 zig`std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::operator=(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 50
zig`std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::operator=:
->  0x10442b772 <+50>: vmovups (%rbx), %xmm0
    0x10442b776 <+54>: vmovups %xmm0, (%r15)
    0x10442b77b <+59>: jmp    0x10442b90b               ; <+459>
    0x10442b780 <+64>: testb  $0x1, %r14b
Target 0: (zig) stopped
```

**Comment by mikdusan** [comment]
We're currently working on generating arm64 binaries from a x86_64 host and I happen to have an artifact. No one has tried to run this in apple silicon yet, but if you're up for it here is latest master with an arm64 executable. I would be interested to know if `zig version` works.

https://drive.google.com/file/d/1OUCAwutS9N0i-jvvlrHDBIIKGGGQIcsg/view?usp=sharing
```
MD5 (zig-macos-x86_64-0.8.0-dev.1471+4e9894cfc.tar.xz) = a95f2232e96dd02ca84609b8712cf1c9
```

**Comment by holmesmr** [comment]
I can confirm that `zig version` at least works w/ the included arm64 binary. I haven't tried anything else yet though.

**Comment by holmesmr** [comment]
As an update, I was able to build and seemingly successfully run `zls` as usual with this (which was my intention originally, as the current release does not work due to a known existing bug with cross-compiled macOS binaries which make use of thread-local storage).

**Comment by mikdusan** [comment]
That's excellent news. Thanks for trying it out!

wrt  this issue, I have examined our scripts responsible for producing x86_64 tarball and it explicitly builds the zig portion with an x86_64 "baseline" of features so AVX should not be generated. Beyond that I can only speculate that some prebuilt dep libraries we link against somehow were built on a beefy machine that has AVX instructions.

That said, this is a short term thing. We're going to be updating the macos dep tarballs for both x86_64 and arm64 soonish so between that and/or producing arm64 tarball outright, this issue will be solved. Let's leave open until then.

**Comment by mikdusan** [comment]
This is no longer an issue.
