### ISSUE TITLE
Lifetime of strings in FileSouce and arguments to addCSourceFile

### ISSUE THREAD

**Issue by asa-z** [ziglang/zig#8263]
Currently, `addCSourceFile` expects the string argument for the file name to live for an unspecified amount of time, presumably the lifetime of the `LibExeObjStep` or the `Builder` (though this is not documented). This is odd, as the compiler flags are copied into the builder's allocator in `addCSourceFileSource`. 

I think the file name should be copied into the builder's allocater (and once this is resolved I can write a patch). However, I don't know if this should be the job of `addCSourceFileSource` or `addCSourceFile`, as this depends on the (undocumented) lifetime guarantees of `FileSource`. Do the strings in `FileSource` have the lifetime of the `Builder`? Or do they have the lifetime of the function call?

**Comment by SpexGuy** [comment]
This has [already been fixed](https://github.com/ziglang/zig/blob/master/lib/std/build.zig#L1833) in #7925.

**Comment by asa-z** [comment]
This does appear to be fixed. (At least, it no longer segfaults). @Vexu is there a reason you've added 0.8.0, or can I close this? (Or both?)

**Comment by Vexu** [comment]
I just added all issues with no milestone and standard library label to 0.8.0.
