### ISSUE TITLE
std.fs.Dir.Iterator cannot handle long file names on Windows

### ISSUE THREAD

**Issue by jack1243star** [ziglang/zig#8268]
I triggered an assertion failure when iterating a long file name with `std.fs.walkPath`:
```
D:\application\zig-windows-x86_64-0.8.0-dev.1431+c760532be\lib\zig\std\debug.zig:223:14: 0x7ff667831078 in std.debug.assert (walk.obj)
    if (!ok) unreachable; // assertion failure
             ^
D:\application\zig-windows-x86_64-0.8.0-dev.1431+c760532be\lib\zig\std\unicode.zig:43:11: 0x7ff66785762e in std.unicode.utf8Encode (walk.obj)
    assert(out.len >= length);
          ^
D:\application\zig-windows-x86_64-0.8.0-dev.1431+c760532be\lib\zig\std\unicode.zig:604:36: 0x7ff66784f9d5 in std.unicode.utf16leToUtf8 (walk.obj)
        end_index += try utf8Encode(codepoint, utf8[end_index..]);
                                   ^
D:\application\zig-windows-x86_64-0.8.0-dev.1431+c760532be\lib\zig\std\fs.zig:615:68: 0x7ff66784f4c5 in std.fs.Iterator::std.fs.Iterator.next (walk.obj)
                    const name_utf8_len = std.unicode.utf16leToUtf8(self.name_data[0..], name_utf16le) catch unreachable;
                                                                   ^
D:\application\zig-windows-x86_64-0.8.0-dev.1431+c760532be\lib\zig\std\fs.zig:2266:36: 0x7ff66784c0f9 in std.fs.Walker::std.fs.Walker.next (walk.obj)
            if (try top.dir_it.next()) |base| {
                                   ^
```
It seems that `std.fs.Dir.Iterator` on Windows wrongly assumes that the filename converted into UTF-8 will fit in 256 bytes.
https://github.com/ziglang/zig/blob/6787f163eb6db2b8b89c2ea6cb51d63606487e12/lib/std/fs.zig#L564
Changing it to 512 fixed my particular use case.

I don't know much about this, perhaps assuming 256 Unicode code points would be a safer bet?

**Comment by LemonBoy** [comment]
What's the `FileNameLength` value for the failing directory entry?
I guess this is the usual problem with long path names introduced by Windows 10 and `PATH_MAX` being hardcoded to 260.

**Comment by jack1243star** [comment]
> What's the `FileNameLength` value for the failing directory entry?

One entry has `FileNameLength == 416`, which required setting `name_data: [1024]u8` to pass.

Creating a file with random long Japanese file name can reliably trigger this.
I guess this is partially due to CJK characters being encoded as three bytes in UTF-8?

**Comment by LemonBoy** [comment]
Oh, good catch. The longest urf8-encoded sequence is 4 bytes long so 260*4 is a good upper limit.
