### ISSUE TITLE
Zig fails to get the include paths on NixOS Unstable

### ISSUE THREAD

**Issue by sagehane** [ziglang/zig#8269]
## Problem:
NixOS fails to detect system header locations on Unstable, accompanied by the following error:
```
warning: Unrecognized C flag from NIX_CFLAGS_COMPILE: -frandom-seed=<some 10 digit string>
```
Tested on:
```
$ nixos-version
21.05pre275822.916ee862e87 (Okapi)
```

## How to reproduce:
1. Prepare a Zig project that interfaces with C code, such as the [the raylib example code on the main page](https://ziglang.org/learn/samples/#c-interoperability).
2. Use `nix-shell` to install the required dependencies (`raylib` in this case).
3. Attempt to compile the file (`zig build-exe cimport.zig -lc -lraylib` as per the code comment).

## The cause:
https://github.com/NixOS/nixpkgs/pull/102251 added `-frandom-seed` as one of the flags of `NIX_CFLAGS_COMPILE`.

An example of what happens after running `nix-shell -p raylib`:
```
$ echo $NIX_CFLAGS_COMPILE
-frandom-seed=k1in0vqnyx -isystem /nix/store/ndbz36pb6rl0n2582n6598az61bsa7pl-raylib-3.5.0/include -isystem /nix/store/ndbz36pb6rl0n2582n6598az61bsa7pl-raylib-3.5.0/include
```
Since Zig doesn't expect this, it breaks out of the loop described [here](https://github.com/ziglang/zig/blob/4ca1f4ec2e3ae1a08295bc6ed03c235cb7700ab9/lib/std/zig/system.zig#L55) and doesn't properly add the header paths.

## Possible Solutions:
Zig should adds support for passing `-frandom-seed`. Should be the ideal fix? Should just be about working on that loop mentioned above.

Also, idk if Zig is supposed to have feature parity with Clang, but `frandom-seed` seems to be mentioned [here](https://github.com/ziglang/zig/blob/a502c160cd51ce3de80b3be945245b7a91967a85/src/clang_options_data.zig#L5143).

___

According to https://github.com/NixOS/nixpkgs/issues/109033, NixOS currently lacks a way to disable this flag from being added.

As such, for people who just want to "ignore" the problem, they can add something like this to the `shell.nix` file:
```
  # This is a workaround that needs to be revised
  shellHook = ''
    NIX_CFLAGS_COMPILE="$(echo "$NIX_CFLAGS_COMPILE" | sed -e "s/-frandom-seed=[^-]*//")"
  '';
```

**Comment by will** [comment]
I'm having a similar issue while building a zig 0.13 project inside of the devshell provided by github:Cloudef/zig2nix on macos. `zig build` worked fine until I added `exe.linkSystemLibrary("libgit2");` to the build.zig file. Then it started erroring with 

```
error: warning: Unrecognized C flag from NIX_CFLAGS_COMPILE: -isysroot
warning: Unrecognized C flag from NIX_CFLAGS_COMPILE: /nix/store/7n8zp0cpbnf1rf7d3dc7gi0x43iadqn3-sdkroot-11.0/MacOSX11.0.sdk
```

and the value for that env var for me is

```
❯ echo $NIX_CFLAGS_COMPILE
 -frandom-seed=maaa31cchk -isysroot /nix/store/7n8zp0cpbnf1rf7d3dc7gi0x43iadqn3-sdkroot-11.0/MacOSX11.0.sdk
```

**Comment by nektro** [comment]
that's https://github.com/ziglang/zig/issues/18998. also make sure to check out [Community](https://github.com/ziglang/zig/wiki/Community)s
