### ISSUE TITLE
`@nameOf` built in function

### ISSUE THREAD

**Issue by batiati** [ziglang/zig#8270]
## Proposal

Introduce a new built-in function `@nameOf` that returns the name of any declaration (fields, functions, variables, consts, etc) as a `comptime []const u8`.

## Motivation

Even with most of `comptime` strings being capable of raise compiler errors, strings are not easily trackable/refactorable when the underlying declaration changes. Many IDEs have some sort of feature allowing automated code-refactoring, which would be hard to use against strings.

Simple example
```zig
//Use @nameOf
var self = @fieldParentPtr(Self, @nameOf(allocator), allocator);
const NAME = @nameOf(NAME);

// instead of a string
var self = @fieldParentPtr(Self, "allocator", allocator);
const NAME = "NAME";
```

## Drawbacks

As a built-in function, `@nameOf` must be capable to accept expressions that aren't valid in normal statements, for example:

```zig
// Allow to refer to a field without a instance of MyStruct
_ = std.meta.trait.hasField(@nameOf(MyStruct.name));
``` 
Similar behavior is observed in [C#'s nameOf operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof).

**Comment by Rocknest** [comment]
What does this mean? 
```zig
// Allow to refer to a field without a instance of MyStruct
_ = std.meta.trait.hasField(@nameOf(MyStruct.name));
```
Do you want to refer to a field and only then check if it exists? 

And most likely there is no easy way to make it work with generic types, so it would be useless for IDEs.

**Comment by batiati** [comment]
> What does this mean?

```zig

const MyStruct = struct {
    name: []const u8,
};

fn somefunc() void {

    var myInstance = MyStruct { .name = "bob" };

    // Expected "name"
    _ = @nameOf(myInstance.name); 

    // Expected "name"
    // In normal statements you can't refer to a field this way, but it makes sense for @nameOf
    _ = @nameOf(MyStruct.name); 

}

```

> And most likely there is no easy way to make it work with generic types, so it would be useless for IDEs.

```zig

  // Expected "items"
  _ = @nameOf(std.ArrayList(i32).items);
```

As I said, most of comptime string usage will raise compiler errors, like `@field(myStruct, "there_is_no_such_field")`, but I feel very uncomfortable spreading strings constants related to names already declared in the code.

**Comment by Vexu** [comment]
I'm think this has been previously rejected but I can't find the issue (possibly deleted?).

**Comment by Rocknest** [comment]
@batiati
> `// Expected "items"`
> `_ = @nameOf(std.ArrayList(i32).items);`

Consider this:
```zig
fn (comptime T: type) void {
  _ = @nameOf(T.items);
}
```
There is no easy way for IDE to help with refactoring here (multi-build analysis required)

**Comment by czrptr** [comment]
@batiati 

Could you give another example where `@nameOf` would help with refactoring? In the example you've given, changing the name of `NAME` would require as much effort with `@nameOf` and with hardcoded strings since you would have to chenge the argument of `@nameOf` (this also applies with struct fields).

```zig
const NAME = "NAME";
//    ~~~~    ~~~~

const NAME = @nameOf(NAME);
//    ~~~~           ~~~~
```

I've known about C#'s `nameOf` operator but have never found a use for it. I'm not against this feature, I just don't see it providing a cleaner solution to the problems you've mentioned.

Also the drawback you mention is significant IMO since `Type.field` is not a valid expression (`Type` acting like a namespace and `field` being tied to an instance). Making this legal would introduce an inconsistency in the language (making it more complicated) and the power of this feature doesn't look powerful enough to me to warrant taking on this complexity.

**Comment by MasterQ32** [comment]
A `@nameOf` builtin has the signficiant benefit of failing to compile instead of just doing the wrong thing:

Consider this refactoring:

```zig
var foo = "Hello";

try writer.print("  \"{s}\": \"{s}\"\n", .{ "foo", foo }); // without
try writer.print("  \"{s}\": \"{s}\"\n", .{ @nameOf(foo), foo }); // with
```
=> (ah, let me just quickly fix all compile errors)
```zig
var bar = "Hello";
try writer.print("  \"{s}\": \"{s}\"\n", .{ "foo", bar }); // without: probably wrong serialization
try writer.print("  \"{s}\": \"{s}\"\n", .{ @nameOf(foo), bar }); // with: error: use of undeclared identifier 'foo'
```

**Comment by czrptr** [comment]
I see. `@nameOf` would indeed be very useful in the context of a serialization library for example. Now I see it's usefulness.

**Comment by batiati** [comment]
Hi @czrptr 

>Could you give another example where @nameOf would help with refactoring? In the example you've given, changing the name of NAME would require as much effort with @nameOf as with a hardcoded string since you would have to chenge the argument of @nameOf (this also applies with struct fields).

I have a similar case as stated above by @MasterQ32's serialization example. I'm working on a data-binding engine for a MVC-like UI, and  I found myself repeating the same symbol's names many times as strings ... and I missed some IDE support too, like autocompletion.

> Also the drawback you mention is significant IMO since `Type.field` is not a valid expression (`Type` acting like a namespace and `field` being tied to an instance). Making this legal would introduce an inconsistency in the language (making it more complicated) and this feature doesn't look powerful enough to me to warrant taking on this complexity.

Sure, I agree.
I just pointed out that C# behaves in that manner, allowing nameof/typeof to do things not allowed by the regular grammar, like ```var name = nameof(Type.InstanceField)```, ```var name = nameof(MethodNameWithoutArgs)``` and ```var type = typeof(TemplatedClassWithoutTemplate<>);```.

I'm not a PL person, so I have no idea how hard is to make this work, but maybe @nameOf could return any token as a string, without further syntactic analysis.

**Comment by Cons-Cat** [comment]
This is something I've been wanting before in other languages. To my knowledge, C preprocessor macros cannot express surrounding an argument with ``""``. C++ allows you to get a name-mangled string from a symbol, but de-mangling it is implementation defined and that string cannot be ``constexpr``. Implementing this proposal would be very nice for Zig, in my humble opinion.

**Comment by MasterQ32** [comment]
@Cons-Cat just for clarification:
```c
#define NAMEOF(x) #x
```
should do the job for both C and C++ based on the preprocessor

**Comment by r00ster91** [comment]
`@nameOf` sounds like it can get the name of anything but it sounds like it's only able to get the name of identifiers. So why not `@identName` or `@identifierName`? This is more in line with the already existing name-getting builtins `@errorName`, `@tagName`, and `@errorName`. I do not think we should merge these all into a `@nameOf` builtin but keep them separate.

**Comment by Pyrolistical** [comment]
AFAIK, there is currently no way to get the name of a comptime function pointer nor the parameter names.

This built-in would have filled this gap.

The name of comptime function pointer is useful for decorating functions.

```zig
fn add(x: u8, y: u8) u8 {
    return x + y;
}

fn logFn(comptime f: anytype, args: anytype) @typeInfo(@TypeOf(f)).Fn.return_type.? {
    std.debug.print("fn {s}\n", .{ @identName(f) });
    const F = @TypeOf(f);
    const f_info = @typeInfo(F).Fn;
    inline for (f_info.params, 0..) |param, i| {
        std.debug.print("param {s}: {s} = {}\n", .{ @identName(param), @typeName(param.type.?), args[i] });
    }
    const result: f_info.return_type.? = @call(.auto, f, args);
    std.debug.print("result {}\n", .{result});
    return result;
}

_ = logFn(add, .{ 1, 2 });

// prints
fn add
param x: u8 = 1
param y: u8 = 2
result 3
```

**Comment by nektro** [comment]
the function name can be obtained from manipulating `@typeName(@TypeOf(f))`
`std.builtin.Type.Fn.Param` having a name field would be nice imo, but the request should be its own issue

**Comment by Pyrolistical** [comment]
> the function name can be obtained from manipulating `@typeName(@TypeOf(f))` 

@nektro doesn't work for me
```zig
fn foo() void {}

pub fn main() void {
    @import("std").debug.print("{s}\n", .{@typeName(@TypeOf(foo))});
}

// prints
fn () void
```

**Comment by Pyrolistical** [comment]
I found a way to get method names. They are on `std.builtin.Type.Struct.decls`:
```zig
const std = @import("std");

const SomeStruct = struct {
    pub fn foo() void {}
};

test {
    const f_name = @typeInfo(SomeStruct).Struct.decls[0].name;
    try std.testing.expectEqualStrings("foo", f_name);

    const f = @field(SomeStruct, f_name);
    const F = @TypeOf(f);
    const f_type_info = @typeInfo(F);

    try std.testing.expect(switch (f_type_info) {
        .Fn => true,
        else => false,
    });

    try std.testing.expectEqual(SomeStruct.foo, f);
}
```

**Comment by dravenk** [comment]
We can get the compile-time method name, but not the run-time method name.
```
const std = @import("std");

const any_fn = *const fn (_: u8) void;
fn hello(_: u8) void {}
fn hi(_: u8) void {}
fn hey(_: u8) void {}

test "nameOf" {
    try std.testing.expectEqualStrings(nameOf.Fn(hello), "hello");
    try std.testing.expectEqualStrings(nameOf.Fn(hi), "hi");
    try std.testing.expectEqualStrings(nameOf.Fn(hey), "hey");
}

test "test fail" {
    var s = struct {
        list: std.ArrayList(any_fn) = std.ArrayList(any_fn).init(std.heap.page_allocator),
    }{};
    try s.list.append(hello);
    try s.list.append(hi);
    try s.list.append(hey);
    try std.testing.expect(s.list.items.len == 3);

    // This will fail
    // try std.testing.expectEqualStrings(nameOf.Fn(s.list.items[0]), "hello");
}

const nameOf = struct {
    fn Dummy(func: anytype) type {
        return struct {
            fn warpper() void {
                func();
            }
        };
    }

    pub fn Fn(func: anytype) []const u8 {
        const name = @typeName(Dummy(func));
        const start = (std.mem.indexOfScalar(u8, name, '\'') orelse unreachable) + 1;
        const end = std.mem.indexOfScalarPos(u8, name, start, '\'') orelse unreachable;
        return name[start..end];
    }
};
```
