### ISSUE TITLE
Zero-size-payload unions created with @Type() with at least 2 fields have wrong size.

### ISSUE THREAD

**Issue by chadwain** [ziglang/zig#8277]
```zig
const Bug = @Type(@typeInfo(union { sup: void, bro: void }));
```
```@sizeOf(Bug)``` returns 18446744073709551615.

**Comment by YohananDiamond** [comment]
Just as a note, `18446744073709551615` is the biggest value an `u64` can have. Maybe this is related to some kind of integer overflow on subtraction; I have no idea where, though.

**Comment by mikdusan** [comment]
<details>
<summary>ok1.zig</summary>

```zig
const Bug = @Type(@typeInfo(union { sup: void, bro: void }));

pub fn main() void {
    @import("std").log.debug("{}", .{@sizeOf(Bug)});
}
```
</details>
size looks ok now

```sh
$ zig version
0.11.0-dev.1026+4172c2916

$ zig run ok1.zig
debug: 1
```

**Comment by Vexu** [comment]
Those are the expected values.
