### ISSUE TITLE
translate-c: Weird interactions with #define and floats

### ISSUE THREAD

**Issue by sagehane** [ziglang/zig#8278]
This [example raylib code](https://github.com/raysan5/raylib/blob/7e62d973f95383a9e09a3520baad515e2e9b0705/examples/models/models_rlgl_solar_system.c) failed to compile after translating to Zig with `translate-c`.

Tested on `zig-linux-x86_64-0.8.0-dev.1479+aa1c78056`.

Sorry beforehand if this is a duplicate and/or my overall terminology is weird. I don't know much about C so I didn't really know what terms to search.

## Reproducing:

In order to highlight what's going on, I wrote a minimal example to reproduce the problem:
```c
// This code doesn't compile after translating to Zig
#include <stdio.h>

#ifndef PI
    #define PI 3.14159265358979323846f
#endif

#ifndef DEG2RAD
    #define DEG2RAD (PI/180.0f)
#endif

int main(void) {
    printf("DEG2RAD is: %f\n", DEG2RAD);

    return 0;
}
```

## The translated code:

The code above translates without any problems, but attempting to compile the code produces this error:
```
$ zig build-exe broken.zig -lc
./broken.zig:303:52: error: float value 3.141593 cannot be coerced to type 'comptime_int'
    _ = printf("DEG2RAD is: %f\n", @floatCast(f64, 3.1415927410125732 / 180));
                                                   ^
./broken.zig:303:71: note: referenced here
    _ = printf("DEG2RAD is: %f\n", @floatCast(f64, 3.1415927410125732 / 180));
                                                                      ^
```
Here are the relevant portions of the translated Zig code:
```zig
pub const PI = @as(f32, 3.14159265358979323846);
pub const DEG2RAD = PI / @as(f32, 180.0);
```
```zig
pub export fn main() c_int {
    _ = printf("DEG2RAD is: %f\n", @floatCast(f64, 3.1415927410125732 / 180));
    return 0;
}
```

## Cause and evaluation:

There seems to be two problems.
1. Even though the translator translated the contents of `#define` macro, it still is translating every instance of `DEG2RAD` as opposed to just using the translated value.
2. Rather than the expected `@floatCast(f64, 3.1415927410125732 / 180.0)`, it uses `180` as the denominator, which causes the error.

Ideally, I think it should be translated like this:
```zig
pub export fn main() c_int {
    _ = printf("DEG2RAD is: %f\n", @floatCast(f64, DEG2RAD));
    return 0;
}
```

Of course, I know little about C so my proposed solution might be naive.

---

As a side note, the following code works without any problems:
```c
// This code works fine
#include <stdio.h>

const float pi = 3.14159265358979323846f;
const float deg2rad = pi/180.0f;

int main(void) {
    printf("deg2rad is: %f\n", deg2rad);

    return 0;
}
```
It translates into this code instead:
```zig
pub export const pi: f32 = 3.1415927410125732;
pub export const deg2rad: f32 = pi / 180;
pub export fn main() c_int {
    _ = printf("deg2rad is: %f\n", @floatCast(f64, deg2rad));
    return 0;
}
```

**Comment by LemonBoy** [comment]
> ./broken.zig:303:52: error: float value 3.141593 cannot be coerced to type 'comptime_int'
    _ = printf("DEG2RAD is: %f\n", @floatCast(f64, 3.1415927410125732 / 180));

This looks like a problem in the peer type resolution algorithm to me.

**Comment by Vexu** [comment]
In #2568 it was decided that a compiler error was appropriate when the fraction was zero but it does seem unambiguous to cast `180` to `comptime_float` here.

**Comment by lacebal** [comment]
I add another case of weird interaction between DEFINE and floats expressions just in case is helpful.

**Zig version: 0.8.0-dev.1431+c760532be**

Original C code from nuklear library. The a_max variable and assignment expression is all floats including the NK_PI define.
```
#define NK_PI 3.141592654f
...
NK_API void
nk_draw_list_fill_circle(struct nk_draw_list *list, struct nk_vec2 center,
    float radius, struct nk_color col, unsigned int segs)
{
    float a_max;
    NK_ASSERT(list);
    if (!list || !col.a) return;
    a_max = NK_PI * 2.0f * ((float)segs - 1.0f) / (float)segs;
    nk_draw_list_path_arc_to(list, center, radius, 0.0f, a_max, segs);
    nk_draw_list_path_fill(list, col);
}
```

This is the translated function where the const 2.0f is converted to comptime_int value.
```
pub fn nk_draw_list_fill_circle(arg_list: [*c]struct_nk_draw_list, arg_center: struct_nk_vec2, arg_radius: f32, arg_col: struct_nk_color, arg_segs: c_uint) callconv(.C) void {
    var list = arg_list;
    var center = arg_center;
    var radius = arg_radius;
    var col = arg_col;
    var segs = arg_segs;
    var a_max: f32 = undefined;
    _ = !!(list != null) or ((blk: {
        _assert("list", "C:\\Dev\\Projects\\test-bed\\app-zig-gles\\vendor\\nuklear\\nuklear.h", @bitCast(c_uint, @as(c_int, 10305)));
        break :blk @as(c_int, 0);
    }) != 0);
    if (!(list != null) or !(col.a != 0)) return;
    a_max = ((3.1415927410125732 * 2) * (@intToFloat(f32, segs) - 1)) / @intToFloat(f32, segs);
    nk_draw_list_path_arc_to(list, center, radius, 0, a_max, segs);
    nk_draw_list_path_fill(list, col);
}
```
