### ISSUE TITLE
Proposal: Make Incorrect Casing a Compiler Error

### ISSUE THREAD

**Issue by ve-nt** [ziglang/zig#8288]
This may be a controversial thing, but hear me out.

I propose that the "only one obvious way to do things" statement in Zig Zen should apply to all factors of code style. It's already applied to formatting, with `zig fmt`, but it's lacking in name styles.

Casing falls under the same line of problems as coding style. People will argue endlessly over snake_case vs camelCase, and what should be used where, etc... It's an entity that seems to have several bike sheds orbiting around it at any given time.

We can avoid this bike shedding in Zig, but we only have limited time to do so while the language is still young. I think that the compiler should have built in case checking, and given Zig's plans for "no warnings, only errors", this would mean that incorrect casing is a compiler error.

# Problem
Although naming is a controversial topic, the thing that almost everyone will agree on is that consistent style and naming should be followed where possible. Consistent naming is not only aesthetically pleasing, but it also makes names much more predictable.

For example:

"Hmmm, was that function called `getUserId` or `GetUserId`? Well it returns a u64, and so it must be `getUserId` because it's returning a value and not a type."

Without consistent naming, this kind of deductive reasoning is not possible.

Inconsistent naming can also lead to misleading the reader, since naming style often implies some semantic information. E.g. functions that return types are PascalCase, whereas functions that return values are camelCase.

The problem becomes much broader than just your own code, however. Almost all large projects will be calling to external libraries, many of which are not written by the same author. If the libraries you are importing do not follow the same naming style as your code, you now have inconsistent naming and all the annoyances that it brings.

Even if your project is not importing any libraries, having different naming still brings more friction to code reuse in other code bases that don't follow the same naming style.

This is a problem in a lot of languages, especially C and C++, where there was no naming convention established at all. Even in languages like Python, which eventually defined their naming convention, inconsistent naming is still rampant in the ecosystem because there is no systematic enforcement of it.

A language that has mostly avoided this problem is Rust, because they defined their naming convention early and implemented compiler warnings when the user goes against convention.

# Solution
We need to try and unify Zig's naming style, and enforce it systematically at the language level so that the path of least resistance is to use the correct naming. We can accomplish this with linting.

My understanding on the plans for Zig's eventual linting system is that it'll be built into the compiler, as opposed to an external linter. Another interesting idea is removing warnings from the linter. Everything is either an error, or allowed. 

On the note of Zig's linter, if the linter and compiler become separate in the future, I think that naming checks should be checked by the compiler and not the linter.

There will be projects where different case styles are needed, either for FFI, C interop, legacy code, or company policies that the author does not have influence over. Those are all fair reasons to go against Zig's official style guide. To accommodate these cases, I propose one or more of the following:

- A builtin to toggle on/off the name checker that can be inlined in code, similar to how you toggle the safety checker.

- A builtin for disabling the name checker for a particular item.

- A builtin to toggle off the name checker for the entire file, specified at the top of the file.

- A way of turning off the name checker for an entire project, that can be put somewhere in your build.zig.

Having the ability to turn off the name checker is necessary, but we want to make it explicit to provide some friction when going against convention.

As far as I can see, name checking would only be needed on declaration, and not for accessing. This means if you need to disable the name checker for a particular symbol, you'd only have to do so for the symbol's declaration and then the rest of your code can be free to access the symbol without having to disable the name checker constantly. 

Anything that isn't Zig shouldn't be name checked, (i.e. C imports). So when using `@cImport`, you don't have to worry about incorrect names, and can access symbols from that header file as-is, whatever name style they may be.

# Zen
I think this aligns with Zig's principles quite well, particularly these points from Zen:

- *Communicate intent precisely*
Consistent naming communicates intent by hinting at semantic information (type name vs variable name).

- *Favor reading code over writing code*
Friction being put on the author to make sure naming stays consistent, but the end result is readability.

- *Only one obvious way to do things*
A single, unified naming convention for all Zig code.

- *Reduce the amount one must remember*
The reader doesn't have to remember casing in names, so long as they remember the type.

- *Focus on code rather than style*
Might be counter-intuitive, but in my opinion this still applies. The programmer doesn't have to think about style, because the compiler has already made the decision for them.

# P.S.
I want to clarify that I don't think that inconsistent naming is the end of the world, or that it's a major problem to deal with in programming. However, I do think it's a problem with an easy solution for a young language, and it's a solution that becomes less and less feasible as a language matures. So implementing it early is important.

**Comment by windows-h8r** [comment]
Sounds like a good idea. The last thing I want is a bunch of Microsoft zealots porting their naming conventions to Zig.

**Comment by MasterQ32** [comment]
I really like that status quo which says: "Try to adhere to the conventions, but if some symbol is predefined, use the predefined writing"

A question you cannot answer: A variable of type `type` should have what case? `PascalCase` or `snake_case`?
Imho this depends heavily on the usage of the type. When i write comptime code, i treat a lot of `type` variables as the values i work with (as i don't intent to use them to declare variables) and thus, i write them `snake_case`. But when i have a type variable that is meant to be used for declarations, it's `PascalCase`.

This proposal would decrease readability in this case imho

**Comment by batiati** [comment]
It could be a little tricky to enforce by compiler error names that are from C code, many times we must follow the C convention interoping with C code.

**Comment by windows-h8r** [comment]
> I really like that status quo which says: "Try to adhere to the conventions, but if some symbol is predefined, use the predefined writing"
> 
> A question you cannot answer: A variable of type `type` should have what case? `PascalCase` or `snake_case`?
> Imho this depends heavily on the usage of the type. When i write comptime code, i treat a lot of `type` variables as the values i work with (as i don't intent to use them to declare variables) and thus, i write them `snake_case`. But when i have a type variable that is meant to be used for declarations, it's `PascalCase`.
> 
> This proposal would decrease readability in this case imho

According to the style guide, if a variable has the type `type`, it should always have a `PascalCase` name.

**Comment by Sobeston** [comment]
I'm against this as the status quo allows for very convenient (de)serialisation patterns. e.g. I can have a struct that breaks the style convention, but is useful as I can use its field names from its type info to perform automatic (de)serialisation.

**Comment by Vexu** [comment]
> I'm against this as the status quo allows for very convenient (de)serialisation patterns. e.g. I can have a struct that breaks the style convention, but is useful as I can use its field names from its type info to perform automatic (de)serialisation.

We could still have this pattern by allowing incorrect casing when using `@""` syntax.

**Comment by ifreund** [comment]
This kind of blanket-enforced conformity seems to be at odds with the official style guide:

> These are general rules of thumb; if it makes sense to do something different, do what makes sense. For example, if there is an established convention such as ENOENT, follow the established convention. 

You cite the existence of `zig fmt` as motivation for this change, but code does not need to be formatted by `zig fmt` in order to compile. I do not think the casing of identifiers is a language level concern just as code formatting is, in general, not a language level concern. If we want to do something to enforce naming conventions in an automated way, I would suggest an external tool like `zig fmt`. Note that zls already has support for warning about these naming conventions.
