### ISSUE TITLE
It seems that there is a lack of bottle in Homebrew for the HEAD version.

### ISSUE THREAD

**Issue by heibor** [ziglang/zig#8294]
When I run `brew upgrade zig --fetch-HEAD`, I got these errors:
```
==> Upgrading zig HEAD-b988815 -> HEAD-d1b376c 
Error: zig: no bottle available!
You can try to install from source with:
  brew install --build-from-source zig
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

I don't know how to resolve it.

**Comment by tauoverpi** [comment]
This would be better to ask on one of the communities https://github.com/ziglang/zig/wiki/Community since it's not really fit for an issue tracker. Hopefully someone there can help you out.

**Comment by heibor** [comment]
Thank you, that is the right direction to find the answer.

**Comment by Vexu** [comment]
This looks like an issue with the homebrew package.
