### ISSUE TITLE
zig build -h shows help after having built the program

### ISSUE THREAD

**Issue by InfRandomness** [ziglang/zig#8299]
Hi;

The build subcommand in Zig has a weird behavior,

if we pass the -h (or --help) option, Zig will build the program first and then show the help menu;
I think it would be a better idea to print out the help menu first and then return to cancel the build process.

**Comment by g-w1** [comment]
It builds the build.zig script which is necessary for the help menu to show all the options.

**Comment by SpexGuy** [comment]
`zig build -h` emits information about the steps and options exposed by the build script.  Collecting this information requires building and running the build script.  An example from one project:
```
...

Steps:
  install (default)           Copy build artifacts to prefix path
  uninstall                   Remove build artifacts from prefix path
  push                        Installs the APK on the connected android system.
  run                         Runs the APK on the connected android system.
  keystore                    Creates a new dummy keystore for testing
  
...

Project-Specific Options:
  -Drelease-safe=[bool]       Optimizations on and safety on
  -Drelease-fast=[bool]       Optimizations on and safety off
  -Drelease-small=[bool]      Size optimizations on and safety off

...
```
To be clear, `zig build -h` does not build the actual project, only the build script.
