### ISSUE TITLE
cast works for const but not var

### ISSUE THREAD

**Issue by esheldon** [ziglang/zig#8302]
zig version 0.8.0-dev.1427+0447a2c04
on linux intel 64

This works
```zig
test "ok" {
    const iconst: u32 = 5;
    const x: f32 = iconst;
}
```
this doesn't compile
```zig
test "bug" {
    var ivar: u32 = 5;
    const x: f32 = ivar;
}
./bug.zig:8:18: error: expected type 'f32', found 'u32'
    var x: f32 = ivar;
```
I get the same if I use `@as(f32, ivar)`

Is there a rule about casting `var` vs `const` ?

**Comment by esheldon** [comment]
Using `@intToFloat(f32, ivar)` works

**Comment by JorisHartog** [comment]
I'm totally new to Zig, but it seems to me that for this to work non-comptime, non-const int to float type coersion is missing in `zig/src/stage1/ir.cpp:ir_analyze_cast()`. However, [the docs](https://ziglang.org/documentation/master/#Type-Coercion-Coercion-Float-to-Int) suggest that this case has been left out for a reason and explicit casts are the way to go.

**Comment by Vexu** [comment]
For compile time known numbers the compiler can check if whether the cast is lossless and emit an error if not, for runtime known values it cannot so you need to use the explicit cast builtins.

Be sure to check out some of the [community gathering places](https://github.com/ziglang/zig/wiki/Community), you'll find a lot of people willing to help with issues like these in them.
