### ISSUE TITLE
`zig build run`: reference to unknown field signednesszsh

### ISSUE THREAD

**Issue by dominikbraun** [ziglang/zig#8303]
Hi,

I'm not sure whether this issue is actually caused by Zig, but it is the only command that yields this error. I downloaded Zig 0.8.0-dev.1542+d1b376cac for macOS and moved it as `zig-dev` into `/usr/local/bin` since the `zig` command already is occupied by the current Zig version in Homebrew.

When running an executable with `zig-dev build run`, I get an error:

```
reference to unknown field signednesszsh: abort      zig-dev build run
```

Any ideas on this?

**Comment by VojtechStep** [comment]
To me, this seems like an issue where the new zig is using old zig's standard library.

The weird string "signednesszsh" is probably caused by not printing a newline after the error message, and zsh adds a message that it aborted the previous command.

**Comment by dominikbraun** [comment]
My mistake probably was to not have the entire Zig directory in my `PATH`. The `zig` binary was there, but the other directories included in the download were missing! Now I added the entire downloaded directory to `PATH` and it seems to work.
