### ISSUE TITLE
cannot use imported enum values because it is private

### ISSUE THREAD

**Issue by aligator** [ziglang/zig#8308]
Hi

First of all my zig version: 
0.8.0-dev.1545+f6ba810f2
0.7.1 didn't work either

I am trying to use curl. (by translating this https://curl.se/libcurl/c/http-post.html to Zig)
But when it comes to the enum CURLOPT_ I cannot use it.

When I pass a normal value (c_int) to the curl_easy_setopt it says  
`./src/main.zig:30:39: error: expected type '.cimport:1:14.enum_unnamed_38', found 'c_int'`
This also happens when I use for example the CURLOPT_URL directly:
```zig
c.curl_easy_setopt(handle, c.CURLOPT_URL, "https://google.com");
```
because as I found out it translates the enum to  
```zig
pub const CURLOPT_URL = @enumToInt(enum_unnamed_38.CURLOPT_URL);
```
So in the end it is a c_int.

The problem now is that I even cannot do something like this:  
```zig
c.curl_easy_setopt(handle, @intToEnum(c.enum_unnamed_38, c.CURLOPT_URL), "https://google.com");
```
Because then I get
`./src/main.zig:30:44: error: 'enum_unnamed_38' is private`

The same if I try to use  
```zig
c.curl_easy_setopt(handle, c.enum_unnamed_38(c.CURLOPT_URL), "https://google.com");
```

The enum is defined in https://github.com/curl/curl/blob/472b537215984cd0d153055a0cd6b3ccc2f387e5/include/curl/curl.h#L1055

My questions are now:
* Why is that enum private? Is this intentional or a bug in the c import code generation?
* Why isn't it called `CURLoption` as in the c header https://github.com/curl/curl/blob/472b537215984cd0d153055a0cd6b3ccc2f387e5/include/curl/curl.h#L2092? Instead it is just called `enum_unnamed_38`
* How can I pass a value to curl_easy_setopt with which it is happy?

**Comment by g-w1** [comment]
you can use an enumLiteral that coerces into an enum:
https://ziglang.org/documentation/master/#Enum-Literals
```zig
c.curl_easy_setopt(handle, .CURLOPT_URL, "https://google.com");
```
Not sure if this is a bug, but using an enum literal is a workaround.

**Comment by aligator** [comment]
Thanks for the fast answer, that worked fine :+1:

**Comment by Vexu** [comment]
>Why is that enum private? Is this intentional or a bug in the c import code 

There is no reason for it to be public since it has no name.

>Why isn't it called `CURLoption` as in the c header https://github.com/curl/curl/blob/472b537215984cd0d153055a0cd6b3ccc2f387e5/include/curl/curl.h#L2092? Instead it is just called `enum_unnamed_38`

It isn't called `CURLoption` in C, the enum is anonymous and is then typedeffed to `CURLoption`. The same thing happens in the translated Zig code, if you look after the enum you'll find a declaration like `pub const CURLoption = enum_unnamed_38;`.

>How can I pass a value to curl_easy_setopt with which it is happy?

Use an enum literal as demonstrated by g-w1 or cast it to `CURLoption` with `@intToEnum(CURLoption, c.CURLOPT_URL)`.

**Comment by Vexu** [comment]
Also note #4043 which should make the error more helpful.
