### ISSUE TITLE
"this" turns into type "(block)" after a declaration.

### ISSUE THREAD

**Issue by Hejsil** [ziglang/zig#831]
```
test "" {
    f();
}

fn f() void {
    const T = @typeOf(this).ReturnType;
    const K = @typeOf(this).ReturnType; // error: type '(block)' does not support field access
}
```

**Comment by andrewrk** [comment]
I'm thinking about making `this` never be able to refer to a block. So it would only refer to the current function or type.

**Comment by andrewrk** [comment]
This is no longer an issue because `this` is deleted and there is no more `(block)` type!
