### ISSUE TITLE
Alignment on field causes "depends on itself"

### ISSUE THREAD

**Issue by Tetralux** [ziglang/zig#8340]
This snippet causes a `depends on itself` error.

```zig
const S = union {
    next: ?*align(1) @This(),
};

pub fn main() void {
    const s = S { .next = null };
}
```
The snippet compiles if you remove the `align(1)` from the union field, however.

This problem also occurs if you replace `union` with `struct`.

**Comment by mikdusan** [comment]
issue no longer exists
```sh
$ zig version
0.11.0-dev.1026+4172c2916
$ zig build-obj bug1.zig
# no output (good)
```
