### ISSUE TITLE
improve std.build to set a good example of proper error handling on out of memory

### ISSUE THREAD

**Issue by agathazeren** [ziglang/zig#8350]
Here's the first of many instances of this problem:
```zig
self.install_path = fs.path.join(self.allocator, &[_][]const u8{ dest_dir, install_prefix }) catch unreachable;
```
`fs.path.join` can throw `error.OutOfMemory`, and therefore reach the `unreachable`, causing undefined behavior.

There are two ways I see to fix this: 

 - Rethrow the error. This is a breaking change, but would allow `build.zig`s to handle the error they way they please. (Though most will just rethrow it out of `build`, and so would only get a slightly better error message.)
 - Panic. This is not a breaking change, but would not allow `build.zig` files to decide how to handle the error, and seems against the zen to me.

Also, the root cause of the problem is that at least this part of `std` is not tested under out of memory situations. There should probably be a set of unit tests excersizing this functionality.

**Comment by andrewrk** [comment]
Note that build scripts are always run in Debug mode, which means this code is not undefined behavior, but in fact it is well defined to crash.

That said, there is probably a good argument to be made here that std.build should set a better example for proper error management.

**Comment by asa-z** [comment]
> Note that build scripts are always run in Debug mode

In addition to setting a good example, I'm not sure if this is a long-term durable assumption.

> which means this code is not undefined behavior, but in fact it is well defined to crash.

Isn't it still _undefined behavior_, even though the safety check will detect it at runtime?

**Comment by andrewrk** [comment]
Debug, ReleaseSafe => `unreachable` is well defined to panic.

ReleaseFast, ReleaseSmall => `unreachable` is UB

`zig build` always uses Debug mode, and there is no plan to change this. Even if we did use a release mode, it would probably be ReleaseSafe.

**Comment by asa-z** [comment]
> Debug, ReleaseSafe => `unreachable` is well defined to panic.

That's not how I would have spec'd it, but if that's how it's spec'd then TIL.

> `zig build` always uses Debug mode, and there is no plan to change this. Even if we did use a release mode, it would probably be ReleaseSafe.

That is reasonable. (Though I guess someone else could use the std.build types for something else other than `zig build`, in which case there would be no control on the release mode. That is unlikely, however, and if that were the only argument, I would say that just documenting that running it without runtime safety is not supported would be sufficient).

Regardless, any opinions on whether to panic or to rethrow the error to fix this, based on the argument of setting a good example?

**Comment by andrewrk** [comment]
Related to how it is spec'd: #2402

> Regardless, any opinions on whether to panic or to rethrow the error to fix this, based on the argument of setting a good example?

I think the panics can make for a nicer API, at least until we get #1923 resolved. But if you or someone wants to go through the effort to clean this stuff up, feel free to propose something different.

**Comment by SpexGuy** [comment]
The zig build system doesn't really have a way to free the memory it's allocated, so if it runs out there's not a whole lot the user can do about it.  So I don't think it's useful to return an OutOfMemory error to them, since they only thing they can do with it is crash.  I definitely think panics are the way to go here.

**Comment by matu3ba** [comment]
> The zig build system doesn't really have a way to free the memory it's allocated, so if it runs out there's not a whole lot the user can do about it.

In the case of simple one binary builds, yes. However, you can also think of parallelized builds with retry logic on memory exhaustion or building libraries and linking them later instead, for example for (big) Kernel builds.
Being able to control where to store memory to free it can be essential there to make room for the linker or stop and resume the linker/linker process.

The same reason can be applied to embedded devices once the native backends are more complete with the same reasoning at smoller scale.

**Comment by matu3ba** [comment]
Working on it to accelerate the breakage.

**Comment by andrewrk** [comment]
Done in #14647.
