### ISSUE TITLE
Infinite loop if sigaction fails on startup

### ISSUE THREAD

**Issue by BinaryWarlock** [ziglang/zig#8357]
`callMainWithArgs` calls `std.debug.maybeEnableSegfaultHandler`, which calls `std.debug.attachSegfaultHandler`.

`attachSegfaultHandler` calls `os.sigaction`, which if fails panics with `unreachable`.

`std.builtin.default_panic` calls `std.debug.panicExtra`, which calls `resetSegfaultHandler`.

Here is the issue: `resetSegfaultHandler` will then call `os.sigaction`, which may fail again and recurse infinitely since we just came from a failed `os.sigaction`.

**Comment by LemonBoy** [comment]
Why is `sigaction` failing? Attach the output from strace if possible.

**Comment by BinaryWarlock** [comment]
I guess I should've been more specific: it's failing because I intentionally make it fail (this is on an OS without signals, so it returns `-ENOSYS`). Technically it should handle the errors gracefully though instead of this. If that's not considered a bug since it's not documented to error in that way, that's also fine, but I thought I'd note it anyway.

**Comment by LemonBoy** [comment]
That should not be a problem as `have_segfault_handling_support` is false in case your OS doesn't support signals.

**Comment by BinaryWarlock** [comment]
Fair enough, I didn't see that flag. I'll make sure that's used. Thanks!

FWIW, POSIX says `sigaction` may return `ENOTSUP` but Zig will panic if it receives that. I wonder why it doesn't return an error value instead (which would be useful for `EINVAL`/`EINVAL` as well), especially when called from userland code.

**Comment by LemonBoy** [comment]
Indeed, failing to install the signal handlers should not enter an infinite loop.
Printing an error message once the low-level setup is complete is IMO a better failure mode, let's keep the ticket open to track this improvement request.

**Comment by BinaryWarlock** [comment]
Roger -- and `std.os.sigaction` should probably return an error value.
