### ISSUE TITLE
Infinite loop in math.sqrt if argument is a runtime negative integer

### ISSUE THREAD

**Issue by ehaas** [ziglang/zig#8359]
First reported [here](https://github.com/ziglang/zig/pull/8355#issuecomment-806194709) but I thought it might be worth its own issue

The following results in an infinite loop:
```Zig
test "infinite loop" {
    var x: i8 = -1;
    _ = @import("std").math.sqrt(x);
}
```

At the very least this should be documented; perhaps instead the negative integer case should be checked and `@panic` called? Alternatively the signature would have to be changed to accommodate an error value. I'd be happy to make the fix if there's consensus about how it should be done.

**Comment by asa-z** [comment]
My opinion is that sqrt should only take unsigned integers, and force the handling of this condition to the caller. If we don't want to do that, then it should probably be safety-checked illegal behavior. (And the docs need to be updated)

**Comment by AssortedFantasy** [comment]
The cleanest solution by far to me seems to be to just change to domain to unsigned, plus it makes sense from a mathematical perspective.

I mean the `sqrt` function already returns an unsigned regardless of what you pass in.

https://github.com/ziglang/zig/blob/9f01598a498ecbd868cb81dc1efdb1507010c1b8/lib/std/math/sqrt.zig#L58

Probably throw this in there and maybe add a test.

```zig
if (@typeInfo(T).Int.signedness == .signed) @compileError("sqrt not defined on signed integers");
```

On a similar note the log functions are broken in exactly the same way.

```zig
pub fn main() void {
  std.debug.print("{}", .{std.math.log2(@as(i32, -200))});
}
```

Returns `-31`


So this probably is a fix that needs to get added to a number of functions.
