### ISSUE TITLE
ArrayHashMap: store values separately from key/hash

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#8363]
Currently there is an `Entry`  type of `ArrayHashMap` that looks like this:

```zig
        /// Modifying the key is illegal behavior.
        /// Modifying the value is allowed.
        /// Entry pointers become invalid whenever this ArrayHashMap is modified,
        /// unless `ensureCapacity` was previously used.
        pub const Entry = struct {
            /// This field is `void` if `store_hash` is `false`.
            hash: Hash,
            key: K,
            value: V,
        };
```

There are two reasons for storing values separately:
 1. If the key/hash and value have different alignments, we may be wasting space in `Entry` via padding.
 2. If the values array is separate, then it can be extracted out of an `ArrayHashMap` into a slice whose memory is managed separately. In other words, ArrayHashMap can be used to construct a contiguous array of values, which then can be "downgraded" into a `std.ArrayList`. Likewise, an ArrayList could be "upgraded" to an ArrayHashMap. In both cases, it would not require moving memory around; the contiguous array of values would remain intact for both transformations. This would allow some nice patterns, such as using ArrayHashMap as a temporary "view" of an ArrayList.

There is a real world use case for this is in the self-hosted compiler: constructing a string table. During construction, one wants to check if a string already exists, and use the same index. However once the string table is constructed, the slice of bytes is all that is desired to remain.

**Comment by kubkon** [comment]
Looks great, and it'd definitely be a welcomed addition to the libstd for all of our linker worries. In addition to storing the string table, the same principle applies to storing different symbol tables (e.g., the globals at the traditional linker scope, or undefs, etc.).

**Comment by matu3ba** [comment]
I do agree that this would be faster on frequent access.

This also works fine for comptime as the page size can be optimised for execution. 

It does work worse on accessing the hashmap values rarely during execution or of huge key/hash sets/tables (not fitting into cache):
1. When key and value are next to another one needs likely 1 cacheline load.
2. When they are apart from another (and one doesnt access them frequently, so they do not remain in cache) one needs to load 2 cachelines.

**Comment by andrewrk** [comment]
@matu3ba I agree with you, however I think this proposal plays to the relative strengths of the ArrayHashMap vs the other HashMap implementation we have. I suspect that for the use case you outlined above, HashMap would be the appropriate tool for the job.

**Comment by moosichu** [comment]
Another benefit of this as well is that if you do need to deal with keys or values separately for any reason - you will have much better cache utilisation (the common case being when you are just iterating over values in isolation). A minor thing but thought it might be helpful to mention.
