### ISSUE TITLE
'No __m512i' error on an AMD machine.

### ISSUE THREAD

**Issue by gegogi** [ziglang/zig#8365]
I recently changed my computer from Intel to AMD.
I copied all the files of my projects to the new machine.
But one of my zig projects which has some C codes in it started failing to compile with following errors.
![image](https://user-images.githubusercontent.com/639708/112667317-78f27800-8ea0-11eb-8089-0af74e735de5.png)
I don't know why the LLVM ends up with including a header file which is not supported by the compiling machine.
Do I need to compile the LLVM on my machine from the source code?

**Comment by g-w1** [comment]
What is your zig version, and how did you make it? Did you download it, or build it from source?

**Comment by gegogi** [comment]
I built the zig compiler from the current head of master branch using VC2019 30 min ago.
zig version command shows 0.7.1 but no hash.

**Comment by LemonBoy** [comment]
> I recently changed my computer from Intel to AMD.

Interesting, what's the output of `zig build-exe --show-builtin`? Does it match your CPU model?

**Comment by gegogi** [comment]
I note it does not have `avx512` but has `vaes`

```
usingnamespace @import("std").builtin;
/// Deprecated
pub const arch = Target.current.cpu.arch;
/// Deprecated
pub const endian = Target.current.cpu.arch.endian();
pub const output_mode = OutputMode.Exe;
pub const link_mode = LinkMode.Static;
pub const is_test = false;
pub const single_threaded = false;
pub const abi = Abi.msvc;
pub const cpu: Cpu = Cpu{
    .arch = .x86_64,
    .model = &Target.x86.cpu.x86_64,
    .features = Target.x86.featureSet(&[_]Target.x86.Feature{
        .@"64bit",
        .@"adx",
        .@"aes",
        .@"avx",
        .@"avx2",
        .@"bmi",
        .@"bmi2",
        .@"clflushopt",
        .@"clwb",
        .@"clzero",
        .@"cmov",
        .@"cx16",
        .@"cx8",
        .@"f16c",
        .@"fma",
        .@"fsgsbase",
        .@"fxsr",
        .@"idivq_to_divl",
        .@"invpcid",
        .@"lzcnt",
        .@"macrofusion",
        .@"mmx",
        .@"movbe",
        .@"mwaitx",
        .@"nopl",
        .@"pclmul",
        .@"popcnt",
        .@"prfchw",
        .@"rdpid",
        .@"rdrnd",
        .@"rdseed",
        .@"sahf",
        .@"sha",
        .@"shstk",
        .@"slow_3ops_lea",
        .@"slow_incdec",
        .@"sse",
        .@"sse2",
        .@"sse3",
        .@"sse4_1",
        .@"sse4_2",
        .@"sse4a",
        .@"ssse3",
        .@"vaes",
        .@"vpclmulqdq",
        .@"vzeroupper",
        .@"wbnoinvd",
        .@"x87",
        .@"xsave",
        .@"xsavec",
        .@"xsaveopt",
        .@"xsaves",
    }),
};
pub const os = Os{
    .tag = .windows,
    .version_range = .{ .windows = .{
        .min = .win10_20h1,
        .max = .win10_20h1,
    }},
};
pub const object_format = ObjectFormat.coff;
pub const mode = Mode.Debug;
pub const link_libc = false;
pub const link_libcpp = false;
pub const have_error_return_tracing = true;
pub const valgrind_support = false;
pub const position_independent_code = true;
pub const strip_debug_info = false;
pub const code_model = CodeModel.default;
```

**Comment by LemonBoy** [comment]
> Target.x86.cpu.x86_64

This means we couldn't find a suitable match for your CPU and I guess it's based on Zen3 uarchitecture as that's the only one that's missing right now.
AVX512 is missing because afaics there are no AMD CPUs that support it, some news websites are reporting that Zen4 will be the first AMD architecture to support the power-hungry extension.

If you don't trust me you can always force-enable the extra features (or change the target uarchitecture) like this `-mcpu=native+avx512f`

**Comment by gegogi** [comment]
Sorry that I wasn't very clear.
I know AMD cpus do not support AVX512 as of now.
But the header file where the error occurred seems that it is for implementation of fast AES(crypto) algorithms using wide registers.
AMD is claiming that they provide this functionality using 256bit registers, but the implementation is assuming existence of 512bit registers.
The header file `vaesintrin.h` is included only when `__VAES__` macro is defined but it doesn't care about `__AVX512__` .
My code actually does not use this feature but `__VAES__` looks defined by the compiler and the leaf header is included by another system header.
Is there any way to detour this? (i.e. force to undefine `__VAES__`?)

**Comment by gegogi** [comment]
Self answer:
I added this to my `build.zig` and at least it works.
`    exe.addCSourceFile("deps/stb_image/src/stb_image_impl.c", &[_][]const u8{"-std=c99", "-U", "__VAES__"});`

**Comment by LemonBoy** [comment]
That or disabling the `vaes` flag at LLVM level lets you skirt around the problem.
The `vaesintrin.h` file is written with AVX512 in mind and is wrong for Zen3 CPUs that implement a subset of the VAES instruction set.  This problem should be reported to GCC and Clang.

**Comment by LemonBoy** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/3fb40ce167ff5f05afadf8f525ff9e17350d6d7f
