### ISSUE TITLE
Ban mistyped wrapping arithmetic?

### ISSUE THREAD

**Issue by thomastanck** [ziglang/zig#8382]
I think `%-` (mod with negated RHS) with no space in between should be a parse error, since the user most likely intended `-%` and there is a chance (albeit small) that it can parse and run.

This came from a question posted on #zig-help on the Discord community:
```zig
    error: negation of type 'u8'
const new = old %- amount;
```
The poster intended `-%` but the transposed `%-` parses as well, and instead the poster got an error about illegally negating `amount`.

I also managed to come up with a test that causes the unintuitive behaviour to parse and run:
```zig
pub fn comptimeWrappingSub(comptime a: comptime_int, comptime b: comptime_int) comptime_int {
    return a %- b;
}

pub fn main() u8 {
    return comptimeWrappingSub(1, -2);
}
// returns 1 instead of 3?
```
It's surprisingly hard to hit this case, because if `a` and `b` were signed, you get an error about needing to use `@rem` or `@mod` instead. But here it passes through fine since both `a` and `b` are `comptime_int`.

**Comment by jedisct1** [comment]
Isn't `zig fmt` immediately going to turn `%-` into `% -`?

With proper highlighting, both symbols are even of different color.

**Comment by ifreund** [comment]
There's a precedent for disallowing confusing whitespace like this:  #6823.

**Comment by Vexu** [comment]
This now results in:
```
error: binary operator `%` has whitespace on one side, but not the other.
    return a %- b;
             ^
```
