### ISSUE TITLE
llvm12: std.atomic.Queue stack smashing detected

### ISSUE THREAD

**Issue by mikdusan** [ziglang/zig#8408]
- issue manifests against:
  - llvm 12.0.0-rc4
  - `-DCMAKE_BUILD_TYPE=Release`
  - `-DLLVM_ENABLE_ASSERTIONS=ON`
  - archlinux
  - zig llvm12 branch @ b85ef2300fa72f5f4c73b8eb9e14f0218ada592d
  - must use libc

- notable:
  - does not manifest on macos

- fails in **first** test (name is not unique for isolation purposes)
```diff
  $_build.assert/zig test lib/std/atomic/queue.zig -lc -femit-llvm-ir --strip
  warning: zig cannot build new glibc version 2.33; providing instead 2.32
- *** stack smashing detected ***: terminated
  error: the following test command crashed:
  lib/std/atomic/zig-cache/o/196aa4f50d05421d700fc603810e013b/test /home/mike/project/zig/work/llvm12/_build.assert/zig
```

I haven't really ruled anything out at this point but:
- is this an LLVM bug *caused* by `-DLLVM_ENABLE_ASSERTIONS=ON`? stackguard IR is different when off
- ~~unlikely, but is RELEASE+ASSERT causing the problem because DEBUG+ASSERT is more common?~~ ruled out

and just for curiosity sake here is llvm-ir stackguard setup comparison:
- LLVM RELEASE
```llvm
; Function Attrs: nobuiltin nounwind sspstrong
define internal fastcc i16 @"test \22xstd.atomic.Queue\22"() unnamed_addr #1 {
Entry:
  %StackGuardSlot = alloca i8*, align 8
  %StackGuard = load volatile i8*, i8* addrspace(257)* null, align 8
  call void @llvm.stackprotector(i8* %StackGuard, i8** %StackGuardSlot)
```
- LLVM RELEASE+ASSERT
```llvm
; Function Attrs: nobuiltin nounwind sspstrong
define internal fastcc i16 @"test \22xstd.atomic.Queue\22"() unnamed_addr #1 {
Entry:
  %StackGuardSlot = alloca i8*, align 8
  %StackGuard = load volatile i8*, i8* addrspace(257)* inttoptr (i32 21850 to i8* addrspace(257)*), align 8
  call void @llvm.stackprotector(i8* %StackGuard, i8** %StackGuardSlot)
```

**Comment by LemonBoy** [comment]
Both the IR snippets look wrong to me as neither of them is loading the cookie from `fs:0x28`.
Can you upload the generated binary somewhere?

> does not manifest on macos

The stack protector is only emitted when targeting glibc/Fuchsia/Android (see `hasStackGuardSlotTLS`)

**Comment by mikdusan** [comment]
@LemonBoy, sorry for taking so long -- retooling on linux in a low-disk-space vm takes forever,

> Can you upload the generated binary somewhere?
- [issue.8408.zip](https://github.com/ziglang/zig/files/6255908/issue.8408.zip)
- llvm-release: `test`, `test.ll`
- llvm-release-assert: `test.assert`, `test.assert.ll`
- used llvm12 branch 4d729ebc87456c9a9e1c487e6185346d1eb8d585

**Comment by LemonBoy** [comment]
I've pushed a completely untested PR as I cannot be arsed to rebuild LLVM, I'm pretty sure that's the problem.
[Here's](https://reviews.llvm.org/D99952) the accompanying LLVM patch.

Let me know if it solves the problem for you.

**Comment by mikdusan** [comment]
> Let me know if it solves the problem for you.

- independently, #8446 fixes this issue
- independently, https://reviews.llvm.org/D99952 applied to llvm-12.0.0-rc4 fixes this issue

thanks!
