### ISSUE TITLE
compiler crash when switching on usize and using enum items as prongs

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#842]
```zig
const E = enum(usize) { One, Two };

test "aoeou" {
    foo(1);
}

fn foo(x: usize) void {
    switch (x) {
        E.One => {},
    }
}
```

**Comment by isaachier** [comment]
I don't see this error anymore. Maybe #1147 fixed #1111 and this somehow?

**Comment by andrewrk** [comment]
Great! Then the next step is to add the above test case into the test suite, and that can close this issue.

**Comment by isaachier** [comment]
OK cool. Although I doubt my fix had much to do with this, so just hoping something else did it correctly.

**Comment by isaachier** [comment]
Nvm somehow still broken even though worked locally...
