### ISSUE TITLE
Proposal: Allow argument files to reduce the length of argument lists.

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#8425]
# Intro

This proposal tries to address the problem that the maximum windows command line length is limited to [32768](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw) characters, in cmd even only [8192](https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation).

When using [zig-bearssl](https://github.com/MasterQ32/zig-bearssl/), we have 294 C files, having a total of 9979 bytes with a single space character as separator. When using BearSSL in any project, we get an additional 294 characters of command line per single character in the prefix char. [Java also suffers from this limitation](https://support.thoughtworks.com/hc/en-us/articles/213248526-Getting-around-maximum-command-line-length-is-32767-characters-on-Windows)

# Proposal

To adress this problem, i recommend adding the option to pass command line args in text files. If a command line argument is prefixed with `@`, it is replaced by the contents of a file:

**invocation:**
```sh
zig build-exe @args.txt -name demo
```

**args.txt:**
```
--pkg-begin bearssl deps/bearssl/src/lib.zig --pkg-end
```

## Benefits
- Works around the 32768 character limit
- Improved debuggability (`build.zig` can always generate CLI files instead of passing the args, allowing improved introspection)

## Drawbacks
- Implementation overhead

# Alternatives

Some other projects use zlib-compressed argument lists to get more characters into the lists. I don't think this is a good solution as it opposes readability and debuggability.

**Comment by Vexu** [comment]
This has been implemented.
