### ISSUE TITLE
Unexpected errno when other end disconnects

### ISSUE THREAD

**Issue by 12Boti** [ziglang/zig#8426]
When you obtain a TCP stream (e.g. with `std.net.tcpConnectToAddress` or `std.net.StreamServer.accept`), if the other end disconnects, the program crashes with `unexpected errno: 104`.

Minimal example:
1. start a TCP server on port 8888 (`nc -l 8888`)
2. run this:
```zig
const net = @import("std").net;

pub fn main() !void {
    const addr = net.Address.resolveIp("127.0.0.1", 8888) catch unreachable;
    var s = try net.tcpConnectToAddress(addr);
    while (true) {
        s.writer().writeAll("Hello!\n") catch {};
    }
}
```
3. you should see the "Hello!" messages arrive at the TCP server
4. kill the TCP server

Notice how the code is explicitly ignoring all errors with `catch {}`, so if it enters the `while (true)` loop, it should never exit, but it crashes.

**Comment by 12Boti** [comment]
Errno 104 is `ECONNRESET 104 Connection reset by peer`.
It seems that the problem is `std.net.Stream` uses the generic `os.WriteError`, which doesn't support this error.
I'm not sure if `os.WriteError` should be extended or if `std.net.Stream` should use a different error type, because `ECONNRESET` only makes sense for sockets.

**Comment by lithdew** [comment]
Made PR #8503 to fix this. One thing that might be worth considering is to use the send() syscall with os.MSG_NOSIGNAL (if on Linux) to ignore the potential SIGPIPE that may occur if the peer calls shutdown().

This is something that would need to be refactored into the stream writer for `std.net`.
