### ISSUE TITLE
Possible design flaw: errors with same name coming from different packages

### ISSUE THREAD

**Issue by g-w1** [ziglang/zig#8428]
This is a possible design flaw in the language:
Imagine that you have 2 packages that you depend on for your application:
`ruby` and `python`. `ruby` has a function named `runRuby` that can return a `error{InterpreterFailed, InvalidInput, RubyVersionWrong}![]const u8` and `python` has a similar function name `runPythonCode` that can return a `error{InterpreterFailed, NeedPipInstallZigPy, IndentWrong}![]const u8`. If I have a function like this:
```zig
fn compareSpeeds() !u32 {

  const ruby_code =
    \\puts "Hello World"
  ;
  const python_code =
    \\print("Hello World");
  ;
  const ruby_time = blk: {
    const time = time.now();
    try ruby.runRuby(ruby_code);
    const after = time.now();
    break :blk after-time;
  };
  const python_time = blk: {
    const time = time.now();
    try python.runPythonCode(python_code);
    const after = time.now();
    break :blk after-time;
  };
  return abs(ruby_time - python_time);
}
```

What is the inferred error set of this function?
It is:
```zig
error {InterpreterFailed, NeedPipInstallZigPy, IndentWrong, InvalidInput, RubyVersionWrong}
```

There is one error that is the same between them: `InterpreterFailed`. This is not on purpose, it just made sense to both package authors to name it that.

Now imagine some surrounding code:
```zig
const diff = compareSpeeds() catch |e| switch (e) {
  error.InterpreterFailed => {}, // from both, uh-oh how do we tell the user what failed???
  error.NeedPipInstallZigPy => {}, // from python
  error.IndentWrong => {}, // from python
  error.InvalidInput => {}, // from ruby
  error.RubyVersionWrong => {}, // from ruby
};
```

Now imagine this problem, and scale it to a project with 5 dependencies, each with 3. There must be some cases where the error names are accidentally the same.

I do not have a solution to this problem, but I thought I would bring it up as it seems like an unintended problem that could arise.

My idea: force namespacing the packages if there is ambiguity:
```zig
const diff = compareSpeeds() catch |e| switch (e) {
  error.ruby.InterpreterFailed => {}, // from ruby package
  error.python.InterpreterFailed => {}, // from python package
  error.NeedPipInstallZigPy => {}, // from python
  error.IndentWrong => {}, // from python
  error.InvalidInput => {}, // from ruby
  error.RubyVersionWrong => {}, // from ruby
};
```

We *don't* want the users to have to namespace it themselves as users being lazy (not namespacing it) will cause problems.

I would like to hear if people think this is an issue that could ever come up with lots of packages and some ideas.

**Comment by marler8997** [comment]
> error.InterpreterFailed => {}, // from both, uh-oh how do we tell the user what failed???

You could catch the error inside the function that can call both python and ruby and translate it to something like `PythonInterpreterFailed` and `RubyInterpreterFailed`.

**Comment by g-w1** [comment]
This was another one of my ideas, but it seems like it is not explicit and requires the user to differentiate between different errors that mean totally different things. I just think this could be confusing if the packages are not related at all. It might be too much complexity to add.

**Comment by andrewrk** [comment]
I don't think there is a problem here. One can convert `error.InterpreterFailed` to a different error code, or any other state, at the callsite of `runRuby` or `runPython`. Even in this contrived example, nothing is wrong. I really don't think there is any problem to solve here.

**Comment by g-w1** [comment]
Ok, thanks for thinking about it everybody. Closing.
