### ISSUE TITLE
Improve the error message "error: invalid character: '\t'"

### ISSUE THREAD

**Issue by OmicronB** [ziglang/zig#8436]
Playing around with zig for the very first time today I ran into the error:

**error: invalid character: '\t'**

Even after reading this, It didn't occur to me that the language doesn't accept tabs. I figured I made a syntax error and it was trying to tell me it didn't expect to see whitespace at this location. Only after a frustrating half hour did I finally understand that no, it actually does not accept tabs.

This behaviour is unexpected to a C/C++ programmer. Because it is so unexpected, the terse error message doesn't really help. It would be much better just to spell it out, for example: "error: you cannot use tabs to indent your code, please use spaces instead."

**Comment by daurnimator** [comment]
Please see the FAQ: https://github.com/ziglang/zig/wiki/FAQ#why-does-zig-force-me-to-use-spaces-instead-of-tabs

**Comment by OmicronB** [comment]
I really don't understand why you simply dismiss this feedback off hand or point me to a FAQ. My point is that the error message did not help me understand what I was doing wrong.

**Comment by evgenylink** [comment]
@daurnimator please reopen this issue.

Consider similar warning from Haskell. Both for comparison:

![image](https://user-images.githubusercontent.com/65871782/115400686-1ce9ed80-a1d9-11eb-86ce-c1cdeacb4f35.png)

![image](https://user-images.githubusercontent.com/65871782/115400755-2c693680-a1d9-11eb-9970-05dd21230b3d.png)
