### ISSUE TITLE
Inline assembly does not compile with CLRF

### ISSUE THREAD

**Issue by InfRandomness** [ziglang/zig#8437]
Hi, it appears as if there is an issue with inline assembly and CLRF (windows' line endings);

I have tried compiling multiple files (formatted in LF) containing inline assembly and it compiled just file, whereas I have tried the compile the exact same file on windows (but using CLRF) and zig outputed a lot of errors about it;
I think this may be an issue because I reverted the file back to LF on windows and it stopped erroring

**Comment by bnjmnt4n** [comment]
Actually, I believe the current stage1 compiler is completely unable to parse CRLF right now, so this is expected behaviour. See https://github.com/ziglang/zig/wiki/FAQ#why-does-zig-force-me-to-use-spaces-instead-of-tabs.

**Comment by InfRandomness** [comment]
oh, okay, thanks
