### ISSUE TITLE
comptime for loop

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#8444]
I am trying to use a for loop over a comptime array, but I am getting this error:

    ./linker.zig:54:5: error: values of type '.@build.linker.Section' must be comptime known, but index value is runtime known
        for (memory.sections) |section| {
 
where the array is specified as:

     pub const sections = [_]Linker.Section{
            .{ .name = "system_exceptions_vector_table", .start_symbol = true, .keep = true, .patterns = &[_][]const u8{".vector_table*"} },
            .{ .name = "cpu_instructions", .patterns = &[_][]const u8{".text*"} },
            .{ .name = "read_only_data_kept_in_flash", .patterns = &[_][]const u8{".rodata*"} },
        };

This rings a bell but I cannot easily find an issue that represents this. Is this still a known limitation?

Regards,
Mark

**Comment by daurnimator** [comment]
Use `inline for`
