### ISSUE TITLE
ability to obtain return type of generic function when it has no dependencies

### ISSUE THREAD

**Issue by Hejsil** [ziglang/zig#846]
```
test "" {
    var t: @typeOf(@import("std").fmt.parseInt).ReturnType = undefined;
}
```
```
zsh: segmentation fault (core dumped)  zig test test.zig
```

**Comment by andrewrk** [comment]
I believe this is related to parseInt being a generic function

**Comment by Hejsil** [comment]
Oooh ye, that might be it. Tried a few other functions like allocPrint, but ofc, that is also generic.

Here is the bare bones version:
```
fn a(b: var) void {}

test "" {
    var c : @typeOf(a).ReturnType = undefined;
}
```

**Comment by andrewrk** [comment]
> The real question, if my bare bones example should work or not.

I'm not sure. It's a difficult question that I'm not prepared to address yet. Let's revisit closer to 1.0.0.

**Comment by andrewrk** [comment]
Possibly related to #2174, but I'm not sure.

**Comment by FireFox317** [comment]
This would also allow for the proper return types to show up in the generated documentation.

**Comment by mitchellh** [comment]
I think this is resolved in stage2: https://github.com/ziglang/zig/pull/11188

If the return type isn't dependent on generic parameters, it returns the type.

**Comment by andrewrk** [comment]
That's correct. The only thing missing to close this issue is to add a behavior test.

**Comment by Vexu** [comment]
A test for this already exists in `test/behavior/type_info.zig`:
https://github.com/ziglang/zig/blob/b40fc70188fd097e9e05b5c18b635b67b718380e/test/behavior/type_info.zig#L378
