### ISSUE TITLE
While loop with Error union and Optional value

### ISSUE THREAD

**Issue by croscato** [ziglang/zig#8460]
Per zig documentation for while loops:

> Just like if expressions, while loops can take an optional as the condition and capture the payload. When **null** is encountered the loop exits.

The following code differs from documentation. When using the function **bar** the loop never exits.

``` zig
const std = @import("std");
const print = std.debug.print;

var foo_var: u32 = 0;
var bar_var: u32 = 0;

fn foo() ?u32
{
    foo_var += 1;

    return if (foo_var < 5) foo_var else null;
}

fn bar() !?u32
{
    bar_var += 1;

    return if (bar_var < 5) bar_var else null;
}

pub fn main() anyerror!void
{
    while (foo()) |val| {
        print("foo {}\n", .{val});
    }

    while (bar()) |val| {
        print("bar {}\n", .{val});
    } else |err| {
        print("bar error: {s}", .{@errorName(err)});
    }
}
```
Output
```
foo 1
foo 2
foo 3
foo 4
bar 1
bar 2
bar 3
bar 4
bar null
bar null
bar null
bar null
bar null
bar null
bar null
...
```

**Comment by Luukdegram** [comment]
This is correct. `bar()` returns an error union where the rhs is your optional. This means that in the second example `val` is your optional, and not the unwrapped value. To append, the while condition does not contain an optional, but an error union in this case. If you were to actually use `val` other than inside the `print`, you'd have to handle it.

**Comment by croscato** [comment]
Oh! I see! It makes sense now.

Anyway it would be nice if it could be used like this.

Can this be made as a proposal? Maybe with a syntax to support this use case.

**Comment by croscato** [comment]
I found a solution for my use case. The second loop can be used like:
``` zig
    while (bar() catch null) |val| {
        print("bar {}\n", .{val});
    }
```
Thanks everyone for the help!
