### ISSUE TITLE
Proposal/Bug: Allow ++ for runtime known arrays

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#8486]
I'm writing a function that concats some arrays and returns those as a value right now and i was surprised that this didn't work:
```zig
fn byte(u8) [1]u8 { }
fn point(f32,f32) [4]u8 { }

pub fn line(x: f32, y: f32) [5]u8 {
    return byte(0) ++ point(x, y);
}
```

The solution is pretty easy, but also awkward and error prone:
```zig
pub fn line(x: f32, y: f32) [5]u8 {
    var buf: [5]u8 = undefined;
    buf[0..1].* = byte(0);
    buf[1..5].* = point(x,y);
    return buf;
}
```

Imho the first variant should work, as there is nothing that should prevent that from happening.

**Comment by g-w1** [comment]
I think this is accepted: https://github.com/ziglang/zig/issues/7147
