### ISSUE TITLE
Ship libc for WASI

### ISSUE THREAD

**Issue by DagAgren** [ziglang/zig#8489]
Currently, wasm32-wasi can not build C code that uses libc, leaving it fairly useless for C.

There is a libc for WASI based partly on musl: https://github.com/WebAssembly/wasi-libc

(Vaguely related: WASI has the separate concepts of "commands" and "reactors", where commands use main() and run once, while reactors just export a number of functions, and have an _initialize entry point instead of _start that is used to initialise libc internals in C code. Related issue here: https://github.com/ziglang/zig/issues/6757)

**Comment by kubkon** [comment]
Pinging @fengb as I believe he’s done some work on this back in the day, and also @jedisct1 as this might be of interest to you too.

As far as the issue is concerned, this is an excellent good first issue for anyone wanting to contribute to Zig. Of course, I’d be more than happy to mentor!

**Comment by kubkon** [comment]
@DagAgren just an FYI that it's happening! #8837

**Comment by DagAgren** [comment]
Yesssss nice one!
