### ISSUE TITLE
On macos-aarch64 specifying a target of `macos` uses zig ld even with link hack env var

### ISSUE THREAD

**Issue by bzoop** [ziglang/zig#8499]
When using `ZIG_SYSTEM_LINKER_HACK=1` on macos on aach64, I unexpectedly stumbled across an oddity.  
I had assumed that `native-macos-gnu` would be equivalent to the native target, based on the output of `zig targets`:
```
zig-curl% zig targets | jq .native
{
  "triple": "aarch64-macos.11.2.3...11.2.3-gnu",
  "cpu": {
    "arch": "aarch64",
    "name": "cyclone",
    "features": [...]
  },
  "os": "macos",
  "abi": "gnu"
}
```

I had apparently looked only at the os and abi sections of the target, and kind of glossed over the somewhat unexpected content of the triple itself (perhaps my brain interpreted it as "weird looking" or something).

Here is the behavior: 
```
# uses system ld
% rm -rf zig-cache; zig build -Dtarget=native --verbose-link
ld -demangle -dynamic -arch arm64 -macosx_version_min 11.2.3 -sdk_version 11.2.3 -pie -o ...

# uses system ld
% rm -rf zig-cache; zig build -Dtarget=native-native --verbose-link
ld -demangle -dynamic -arch arm64 -macosx_version_min 11.2.3 -sdk_version 11.2.3 -pie -o ...

# uses zig ld
% rm -rf zig-cache; zig build -Dtarget=native-macos --verbose-link
zig ld ...
```

Is this the currently expected behavior (e.g. native os really is what the triple defines `macos.11.2.3...11.2.3` and not `macos` as the .native.os zig targets claims)?
Is this due to aarch64 being still a work in progress, and I just happened to encounter a temporary speed-bump until it gets more fleshed out?

**Comment by kubkon** [comment]
I believe when explicitly specifying the target via `-target` compile option, we always assume cross-compilation in which case the `ZIG_SYSTEM_LINKER_HACK` env var is ignored. I am not sure if this something we want or should fix, especially given that soon the system linker hack will be completely removed and we will always rely on `zig ld`. See #8728.

**Comment by kubkon** [comment]
Also, cc @andrewrk if you would like to chip in on this.

**Comment by andrewrk** [comment]
`native-macos-gnu` means "native CPU, non-native OS"

As far as the system linker goes, the goal is for Zig to not interact with it at all. I suggest to not try to use the system linker hack at all, forget it exists.
