### ISSUE TITLE
Proposal, ignored members of packed structs

### ISSUE THREAD

**Issue by markfirmware** [ziglang/zig#8512]
const Register = packed struct {
        _: u7,
        a: u3,
        _: u8,
        b: u14,
    };

Thus there are seven bits of padding at the beginning of the 32 bit word, and 8 bits of padding between members a and b.

**Comment by MasterQ32** [comment]
I think this was already proposed in the past and was rejected. This might sound appealing, but there usually are no undefined padding bits in the real world.

we need to be able to properly define the value of padding bits. if we leave them `undefined`, they might get non-allowed values and create undebuggable side effects.

Thus, the only benefit would be that we now don't have to name the fields, but might give them names later which i don't think is worth the benefit, as your struct already looks like this then:
```zig
const Register = packed struct {
    _: u7 = 127,
    a: u3,
    _: u8 = 0xF0,
    b: u14,
};
```

**Comment by markfirmware** [comment]
It is a one time cost to add to the compiler, and thereafter this little corner of the source code will not have unused names. Definitely a very small matter.

I will close this after it gets some more exposure. I appreciate being able to unload these thoughts.

Regards,
Mark
