### ISSUE TITLE
zig cc - lld-link: error: could not open '<file>.lib':

### ISSUE THREAD

**Issue by BenStigsen** [ziglang/zig#8526]
Tested with the following versions:
- **Master e761e0ac18aa1eab22b9547d702067910ed82c4a**
- **Stable 0.7.1**

**Operating System: Windows 10 19042**

So, I just downloaded Zig, and I have this Raylib project.
This is what my project looks like:
```
main.c
main.h
include\
  raygui.h
  raylib.h
  ricons.h
lib\
  libraylib.a
  libraylibdll.a
  raylib.dll
```

When I run this with GCC it works:
`gcc main.c -Iinclude/ -Llib/ -lraylib -lgdi32 -limm32 -lwinmm -o main.exe`

When I run this with Zig, it does not:
`zig cc main.c -Iinclude/ -Llib/ -lraylib -lgdi32 -limm32 -lwinmm -o main.exe`

I tried adding the target like so:
`zig cc main.c -target x86_64-windows-gnu -Iinclude/ -Llib/ -lraylib -lgdi32 -limm32 -lwinmm -o main.exe`

But both of these result in the error `lld-link: error: could not open 'raylib.lib': No such file or directory`

**Comment by andrewrk** [comment]
>  This is what my project looks like:

That looks like a cygwin. Windows projects would look like this:

```
main.c
main.h
include\
  raygui.h
  raylib.h
  ricons.h
lib\
  raylib.lib
  raylib.dll
```

Generally (even for gcc) avoid using `-l` for static libraries. Just put the static libraries on the command line directly.
