### ISSUE TITLE
std lib hash maps: add a context parameter for hash and eql functions

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#8528]
Problem: you're implementing hash map eql or hash function, but in order to accomplish this, you need more data than just the key. Here's a real world use case:

```zig
const Context = struct {
    string_table: std.HashMap(u32, void, hash, eql),
    string_bytes: std.ArrayListUnmanaged(u8),
};
```

```zig
fn eql(a: u32, b: u32) bool {
    // error: string_bytes not defined
    return mem.eql(u8, mem.spanZ(string_bytes.items.ptr + a), mem.spanZ(string_bytes.items.ptr + b));
}
```

We need to be able to pass Context to the hash map like this:

```zig
const StringTable = std.HashMap(u32, void, hash, eql, Context);
var t = StringTable.init(allocator, context);
```

So that it can be passed to hash and eql like this:

```zig
fn eql(context: Context, a: u32, b: u32) bool {
    return mem.eql(u8, mem.spanZ(context.string_bytes.items.ptr + a), mem.spanZ(context.string_bytes.items.ptr + b));
}
```

For HashMapUnmanaged, the context should be passed in with every function call that needs it, just like allocator.

**Comment by matu3ba** [comment]
for testing or playing around https://github.com/squeek502/zig-hash-map-bench can be used. As usability reference this small benchmark can be used: https://github.com/benhoyt/countwords to make the optimised version look similar to the simple version.
