### ISSUE TITLE
run-translated-c tests failing for aarch64-linux after merging llvm12

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#8537]
After merging llvm12 branch, drone CI is hitting an error in the `run-translated-c` tests:

```
The following command terminated unexpectedly:
cd /drone/src && /drone/src/zig-cache/o/953f294ec50580c71907aa68df1a0b93/translated_c 
error: the following build command failed with exit code 1:
/drone/src/zig-cache/o/054cb3aa222f1059385d9cbac7ab05f1/build /drone/src/build/zig /drone/src /drone/src/zig-cache /root/.cache/zig test -Dskip-release -Dskip-non-native -Dskip-compile-errors
```

More investigation is needed to find out why.

**Comment by LemonBoy** [comment]
Zig is incorrectly assuming every function is generated at addresses that are multiples of 8 while the minimum requirement is 4 (the length of a single opcode), the same problem was hit in #7946 albeit from a slightly different angle.

The failing test is `Obscure ways of calling functions; issue #4124`.
