### ISSUE TITLE
drone CI intermittent failures

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#8545]
After merging LLVM12 branch, there are intermittent deadlocks when running the self-hosted compiler tests.

```
./zig build test -Dskip-release -Dskip-non-native -Dskip-compile-errors -Dskip-run-translated-c
Test [1/36] test "self-hosted"... 
```

I tried reproducing this on another aarch64 machine and was not able to.

**Comment by andrewrk** [comment]
I saw it stall on normal behavior tests too:

```
+ ./zig build test -Dskip-release -Dskip-non-native -Dskip-compile-errors -Dskip-run-translated-c -Dskip-stage2-tests
Test [1/1002] behavior.align.test "behavior-native-Debug-bare-multi global variable align... 
```

This makes me think it may be a Drone CI issue rather than a zig bug.

**Comment by matu3ba** [comment]
Can this be closed, since the Drone is not used anymore?
