### ISSUE TITLE
Windows fresh install: LibCRuntimeNotFound

### ISSUE THREAD

**Issue by zacwood9** [ziglang/zig#8549]
(tested on master and 0.7.1)

Reproduce:
- download zig
- add to system path
- zig init-exe
- add `exe.linkLibC()` to build.zig
- build fails with `error: unable to create compilation: LibCRuntimeNotFound`

I have Visual Studio installed so there's definitely a libc on my system. Not sure what the problem could be :(

**Comment by zacwood9** [comment]
My Visual Studio was not installed correctly. Reinstalled with all components and everything is working now. Sorry!

**Comment by gregorybleiker** [comment]
For others coming here: Installing clang and others from the VS Installer was not enough for me. I had to run

```
zig build -Dwindows=true
```

before it would compile. I couldn't quite figure out why, but the clang option `--library c` seems to be the problem if you don't use this flag.
