### ISSUE TITLE
Packages depending on other packages doesn't work

### ISSUE THREAD

**Issue by Hejsil** [ziglang/zig#855]
Three file example:
`a.zig`:
```zig
const b = @import("b");
pub fn main() void { b.something(); }
```

`b.zig`:
```zig
const c = @import("c");
pub fn something() void { c.something(); }
```

`c.zig`:
```zig
pub fn something() void { }
```

`build.zig`:
```zig
const std = @import("std");

pub fn build(b: *std.Build) void {
    const optimize = b.standardOptimizeOption(.{});
    const exe = b.addExecutable(.{
        .name = "a",
        .root_source_file = .{ .path = "a.zig" },
        .optimize = optimize,
    });
    const mod_c = b.addModule("c", .{
        .source_file = .{ .path = "c.zig" },
    });
    const mod_b = b.addModule("b", .{
        .source_file = .{ .path = "b.zig" },
        .dependencies = &.{
            .{
                .name = "c",
                .module = mod_c,
            },
        },
    });
    exe.addModule("b", mod_b);

    b.default_step.dependOn(&exe.step);
}
```

When using `zig build` I get:
```
b.zig:1:11: error: unable to find 'c'
const c = @import("c");
```

I've looked around in `build.zig`, but it doesn't seem like there is a way to add package path `c.zig` to `b`. Actually, it seems that `build.zig` just passes the info to the zig compiler through command line args:
```
zig build-exe a.zig --cache-dir zig-cache --output zig-cache/a --name a --pkg-begin b b.zig --pkg-end --pkg-begin c c.zig --pkg-end
```

**Comment by andrewrk** [comment]
I think we need to add support for it in `std/build.zig` but here's the command line options you want (note the recursive `--pkg-begin`):

```
zig build-exe a.zig --cache-dir zig-cache --output zig-cache/a --name a --pkg-begin b b.zig --pkg-begin c c.zig  --pkg-end --pkg-end
```

**Comment by andrewrk** [comment]
I think this is #353

**Comment by emekoi** [comment]
should we add a package object similar to the executable and library object? furthermore, does `--pkg-begin` and `--pkg-end` allow for specifying build flags unique to that package?

**Comment by BenoitJGirard** [comment]
As Windows has a maximum size for the command (8K from cmd.exe, 32K from StartProcess()), seems to me that "--pkg-begin" and "--pkg-end" will not scale for large projects with many edges in their package dependency graph.

Unless I am missing something?

Maybe the tree described by "--pkg-begin" and "--pkg-end" should be imported from a file, instead?

**Comment by andrewrk** [comment]
@BenoitJGirard you are correct.

How packages work for zig is still in the design phase. The command line interface is one of the things that will be addressed. I'm planning on publishing a detailed design specification proposal for the zig package manager shortly after 0.4.0 is released.

**Comment by BenoitJGirard** [comment]
@andrewrk Understood. 

I like how "--pkg-begin" and "--pkg-end" force the explicit listing of the dependencies all the way down the dependency graph. Policing the dependency graph for large projects is one of the headaches we have at my day job. I hope your upcoming design keeps that mindset.

**Comment by SamTebbs33** [comment]
The command used is now `zig build-exe a.zig --cache-dir zig-cache --name a --pkg-begin b b.zig --pkg-end --pkg-begin c c.zig --pkg-end --cache on` and interestingly, re-ordering the calls to `addPackagePath` doesn't give the same issue.

**Comment by andrewrk** [comment]
This might be working today. Here's what needs to happen for this to be closed:
 * Investigate whether there is still an error trying to do this with the zig build system.
 * Make sure there is test coverage in `test/standalone/*` (perhaps it already has coverage?) 
   - add test coverage if not

**Comment by nektro** [comment]
this happened because `addPackagePath` adds a package with no dependencies. so the tree looks like this

```
root
  -> b
  -> c
```

but what you really need is

```
root
  -> b
    -> c
```

so what they need to do is

```zig
const pkg_c = Pkg{ .name = "c", .path = .{ .path = "c.zig" } };
const pkg_b = Pkg{ .name = "b", .path = .{ .path = "b.zig" }, .dependencies = &[_]Pkg{ pkg_c } };
exe.addPackage(pkg_b);
```

**Comment by andrewrk** [comment]
This indeed works today, and has test coverage via these files:
```
$ grep -RI addModule ../test/standalone
../test/standalone/dep_recursive/build.zig:    exe.addModule("foo", foo);
../test/standalone/dep_triangle/build.zig:    exe.addModule("shared", shared);
../test/standalone/dep_mutually_recursive/build.zig:    exe.addModule("foo", foo);
../test/standalone/test_runner_module_imports/build.zig:    t.addModule("module2", module2);
```
