### ISSUE TITLE
Wrapping subtraction/negation operator oddities

### ISSUE THREAD

**Issue by jmc-88** [ziglang/zig#8574]
The [table of operators](https://ziglang.org/documentation/master/#Operators) in the Zig documentation contains the following:

Syntax | Relevant Types | Description | Example
-- | -- | -- | --
`a -% b` `a -%= b` | Integers | Wrapping Subtraction. <ul><li>Guaranteed to have twos-complement wrapping behavior.</li><li>Invokes Peer Type Resolution for the operands. See also `@subWithOverflow`.</li></ul> | `@as(u32, 0) -% 1 == std.math.maxInt(u32)`
`-%a` | Integers | Wrapping Negation. <ul><li>Guaranteed to have twos-complement wrapping behavior.</li></ul> | `-%@as(i32, std.math.minInt(i32)) == std.math.minInt(i32)`

I would expect the unary `-%` to behave identically to `@as(some_unsigned_type, 0) -% 1`, but instead here's what I'm seeing:

Operation | Expected Result | Actual Result
-- | -- | --
`@as(u32, 0) -% 1` | `std.math.maxInt(u32)` | `std.math.maxInt(u32)`
`-%@as(u32, 1)` | `std.math.maxInt(u32)` | `invalid wrapping negation type: 'u32'`
`-%1` | (not sure... it's a `comptime_int`, maybe it just shouldn't wrap?) | `0`

The compilation error on `-%@as(u32, 1)` is particularly interesting. I can't link the source on GitHub since the file is 1.5 MiB big (!), but the failure happens in `src/stage1/ir.cpp`, inside `ir_eval_negation_scalar()`:

```
    bool ok_type = ((scalar_type->id == ZigTypeIdInt && scalar_type->data.integral.is_signed) ||
        scalar_type->id == ZigTypeIdComptimeInt || (is_float && !is_wrap_op));

    if (!ok_type) {
        const char *fmt = is_wrap_op ? "invalid wrapping negation type: '%s'" : "invalid negation type: '%s'";
        return ir_add_error(ira, source_instr, buf_sprintf(fmt, buf_ptr(&scalar_type->name)));
    }
```

I don't know why the requirement for `scalar_type->data.integral.is_signed`: the wrapping behavior is especially useful on unsigned types. A quick `git blame` indicates this check has existed since all the way back to 0ad580f001eb151d0feb7ad884e237b237220800.

**Comment by Vexu** [comment]
Wrapping negation of unsigned integers was accepted in #1770.

**Comment by LemonBoy** [comment]
See also #7951.
