### ISSUE TITLE
Proposal: Add an examples folder to this repository

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#8575]
This is about day three of me writing code in Zig and so far, I like it. However, it's difficult to find examples of idiomatic ways to do things. 

When stuck, the process I've been following is:
- Try a bunch of things
- `⌘+F` the docs for relevant keywords
- Search the Zig discord hoping someone else asked
- Ask #zig-help in Discord (people in the Discord are very helpful!)
- Sometimes search the [std docs](https://ziglang.org/documentation/master/std/)

An `examples` folder in this repository would provide very helpful documentation and  grow the number of developers using Zig. 

Many of the most popular open-source projects have an `examples` folder in the same repository as the root project.
- Next.js (65.5k stars), a popular JavaScript web framework, has [279 examples](https://github.com/vercel/next.js/tree/canary/examples)
- Gatsby (49.8k stars), another popular JavaScript web framework, has [76 examples](https://github.com/gatsbyjs/gatsby/tree/master/examples)
- Bevy (8.7k stars, ~1 yr old), a Rust game engine has [~15 examples](https://github.com/bevyengine/bevy/tree/main/examples)

### Questions & Opinions

**Does it need to be in this repository?**

Yes. Very few people will find it if it was in something like `ziglang/zig-examples`. If few people find it, that means it won't help as many people. It also means fewer people will add examples, and examples will be more likely to break over time.

Putting it in this repository will also help with SEO, since examples show up on Google.

**Who will contribute examples?**

Users of Zig. This is documentation that anyone can write.

**How will an example be added?**

They will submit a PR to this repository.

**How will we know an example works?**

This is probably the trickiest part of a proposal like this. 

- Ideally, there would be tests. But, those tests failures probably shouldn't break CI for the language. 
- Some things will be hard to write tests for.

Opinion: it would be better to have an `examples` folder where users occasionally report an example doesn't work than no examples folder (the current state), so long as _most_ examples reliably work. A broken example can be fixed or deleted.

#### Style questions

**Single-file examples or a folder for each example?**

A folder for each example, since that's what `zig build` expects. Perhaps each example would copy from a templated `README`.

**Wouldn't this mean the user has to clone the repo to run an example?**

Yes, and that's okay because examples are more for reading than directly running. When I've used Next.js' examples before, I typically read from the github UI instead of my local editor.

**Comment by g-w1** [comment]
> But, those tests failures probably shouldn't break CI for the language.

Why, I think there should be tests that just run all the examples and see if any does not compile or maybe exits with code != 0. Yay for more tests!

**Comment by andrewrk** [comment]
Welcome @Jarred-Sumner. You can find examples on [ziglang.org/learn](https://ziglang.org/learn/).

**Comment by andrewrk** [comment]
Yes, patches welcome on https://github.com/ziglang/www.ziglang.org

**Comment by daurnimator** [comment]
FYI this repository used to have examples. Removed in https://github.com/ziglang/zig/commit/9dcddc2249217c8c99c9d07bb0187904847d2ae2

**Comment by Mouvedia** [comment]
> FYI this repository used to have examples. Removed in [9dcddc2](https://github.com/ziglang/zig/commit/9dcddc2249217c8c99c9d07bb0187904847d2ae2)

> [I think zig has aged enough, that it's time to retire the examples/ folder (extracting test cases where appropriate), and rely on the zig community, documentation, and separate projects for examples.](https://github.com/ziglang/zig/pull/2759#issuecomment-511878493)
