### ISSUE TITLE
Homebrew formula still depends on llvm@11, breaking --HEAD

### ISSUE THREAD

**Issue by slimsag** [ziglang/zig#8591]
The homebrew formula still depends on LLVM 11:

https://github.com/Homebrew/homebrew-core/blob/27d1037ca6643d061f29cac97e791b6b3b3c2b3b/Formula/zig.rb#L17

This is correct for the prebuilt bottles, I presume - but it is not correct for the latest `master` (`brew install zig --HEAD`) since we're now using LLVM 12:

```
Configuring zig version 0.8.0
CMake Error at cmake/Findllvm.cmake:89 (message):
  expected LLVM 12.x but found 11.1.0 using
  /usr/local/opt/llvm@11/bin/llvm-config
```

**Comment by akvadrako** [comment]
https://github.com/Homebrew/homebrew-core/pull/75748

**Comment by slimsag** [comment]
Looks like this was fixed, thank you a ton! :)

**Comment by andrewrk** [comment]
FYI I told them upstream to always pin zig's LLVM  dependency with `@` syntax but they refuse to do it, and this breaks with every release cycle in the same way, until they do the `@` thing. :shrug:
