### ISSUE TITLE
@atomicRmw hangs on Cavium ThunderX aarch64 host

### ISSUE THREAD

**Issue by mikdusan** [ziglang/zig#8597]
manifest conditions:
- llvm 12
- zig debug mode (`-OReleaseFast` does NOT manifest)
- Cavium ThunderX aarch64 hardware
- drone.io pipeline pool contains various aarch64 cpu variants, including the above mentioned Cavium

---

- reduction: running this executable will hang
```zig
pub fn main() void {
    panic("never gonna give you up");
}
```

- location in std that hangs:
https://github.com/ziglang/zig/blob/41efdc73b9a57dfcc57474310c64724f58a95493/lib/std/debug.zig#L257

---

@LemonBoy found the related upstream LLVM 12 bug report:
https://bugs.llvm.org/show_bug.cgi?id=48017

---

- this issue is the cause of #8545

**Comment by LemonBoy** [comment]
Patch [submitted](https://reviews.llvm.org/D101163)!

**Comment by andrewrk** [comment]
What a relief to know what is happening! Thank you so much for diagnosing this and LemonBoy for the upstream patch!!

**Comment by kubkon** [comment]
Oh yeah, this is sometimes manifesting itself on arm64 macOS too! Lovely!

**Comment by mikdusan** [comment]
fyi, 3 differential reviews for this issue:

- https://reviews.llvm.org/D101152 (accepted and ready to land)
- https://reviews.llvm.org/D101163
- https://reviews.llvm.org/D101216

**Comment by kubkon** [comment]
> Oh yeah, this is sometimes manifesting itself on arm64 macOS too! Lovely!

For the M1, the issue must have been slightly different in nature since @LemonBoy's PR on detecting CPU features #8735 has fixed the hanging `@atomicRmw` behavior test :tada:

**Comment by mikdusan** [comment]
update: @LemonBoy upstream patch has been merged to llvm-project branch `release/12.x`
and hopefully there is another tag (`llvmorg-12.0.1-rc2`) before `12.0.1` is released
