### ISSUE TITLE
Proposal: Require whitespace after a comma

### ISSUE THREAD

**Issue by ve-nt** [ziglang/zig#8598]
Very similar to #7399. I propose similar measures in this case. 

Here's a code example:
```zig
const std = @import("std");

pub fn main() !void {
    const nums = [_]f32{ 3.45, 8.23, 85.12, 3.2, 8,45, 8.11, 4.78 };
    for (nums) |n| std.debug.print("{}\n", .{n});
}
```

There is a bug in this code. How easy this is to spot will depend on the font and color scheme of your editor. Imagine that you weren't informed there was a bug, and there was a lot more code above and below this. 

The answer is there is no `8.45` in `nums`. The author typo'd a `,` instead of a `.`.

`zig-fmt` will add whitespace after commas where needed, however this does not fix the bug, it only makes it more visible. 

I can't say that I've personally seen this issue before in practice, but considering that `.` and `,` are neighbors on the vast majority of keyboard layouts, it doesn't seem unreasonable that something like this would happen.

I propose that whitespace be mandatory after a comma. Either a space or a newline. This will cause a compiler error in the above example and catch the bug before it becomes dormant. Likewise, `zig-fmt` should also error when it encounters the above code, as to not introduce the same (but more visible) footgun.

Here's some examples to make the new rule clearer:
```zig
const a = [_]f32{3.45,4.55,8.22,7.1}; // error
const b = [_]f32{3.45, 4.55,8.22, 7.1}; // error
const c = [_]f32{3.45, 4.55, 8.22, 7.1}; // okay
const d = [_]f32{ 3.45,    4.55,   8.22,   7.1 }; // okay
const e = [_]f32{
    3.45,
    4.55,
    8.22,
    7.1,
}; // okay
```

**Comment by kubkon** [comment]
This is generally enforced by `zig fmt` so I don't really see any point in making this a hard error. Also, I'd imagine there'd be cases where you'd want to leave out the whitespaces altogether.

**Comment by andrewrk** [comment]
To make something an error, `zig fmt` has to reject it rather than reformat it. In this case we want `zig fmt` to reformat it.

**Comment by marler8997** [comment]
@andrewrk, so zig fmt won't be able to fix errors?

**Comment by SpexGuy** [comment]
In the long term, yeah, zig fmt will reject syntax errors.  In the short term we have it correcting breaking changes in the language, but post-1.0 it won't do that anymore.
