### ISSUE TITLE
Ways to make "extern" structures that have Zig builtin types

### ISSUE THREAD

**Issue by igorifaresi** [ziglang/zig#8600]
Hi,

I am developing an application that I need a plugin system. My initial intention is to all plugins need to be develop in Zig. I tried to make `extern` necessary data structures for plugin writing, but the compiler throws an error when a try to make `extern` structures that have slices. Thinking about that I suggest a couple of things that I think can make more solid this relation between Zig and dynamic libraries.

Firstly, I suggest an way to make exportable structures that have slices and another Zig internal types when you know that dynamic library will be built in Zig. For this, I really don't know how to make it.

Another thing is a way to interact Zig internal types with dynamic libraries written in another languages, like C. I suggest a C header (think in this like a mod API in a game) generated in each compiler version for make a full translation between Zig internal types and C, making with this, possible the exportation of Zig structures that have slices, for example, is just the plugin writer use this header and have a full Zig to C interaction. For example:

```c
ZIG_Slice foo;
ZIG_Slice_set_ptr(&foo, NULL); 
ZIG_Slice_set_len(&foo, 42);
```

I write in this way, using functions or macros to access Zig types because I know that you can not translate very well a Zig slice to a C common structure.  

Thanks for attention

**Comment by andrewrk** [comment]
You can already do this with pointers. With slices you will need to split your arguments into .ptr and .len.
