### ISSUE TITLE
std lib hash maps: ability to query with custom hash and eql function

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#8619]
Depends on #8528.

Use case: I want a string hash map, but the memory for the strings is stored in a string table, null-terminated. That means I can save memory by using `u32` indexes (4 bytes each) into the string table rather than `[]const u8` (16 bytes each on 64-bit arch).

Example: `HashMap(u32, *Decl)`

But when using `get()` to find out if an item exists in the hash map, I need to use a name that does not exist in the string table. Perhaps it is a string literal "foo" or perhaps the string is stored elsewhere. But I should still be able to find a matching entry.

I propose additional `get` methods that allow providing alternate `hash` and `eql` functions. For convenience they can take a type that acts kind of like a plugin:

```zig
fn string_table_hash(string_table: [*:0]const u8, k: u32) u32 {
    return autoStringHash(mem.spanZ(string_table + k));
}
fn string_table_eql(string_table: [*:0]const u8, a: u32, b: u32) u32 {
    const a_string = mem.spanZ(string_table + a);
    const b_string = mem.spanZ(string_table + b);
    return mem.eql(u8, a_string, b_string);
}
var hash_map: std.HashMapUnmanaged(u32, *Decl, string_table_hash, string_table_eql, string_table) = .{};

// ...put stuff in it...

// define our key adapter
const Adapter = struct {
    const Context = [*:0]const u8;
    const Key = []const u8;
    fn hash(_: Context, k: Key) u32 {
        return autoStringHash(k);
    }
    // the eql function has `a` in the hash map key type, but `b` is the adapted key type
    fn eql(string_table: [*:0]const u8, a: u32, b: Key) bool {
        const a_string = mem.spanZ(string_table + a);
        return mem.eql(u8, a_string, b);
    }
};

// now we can get with `[]const u8` keys too!
const has_foo = hash_map.getAdapted(Adapter, string_table, "foo");
```

**Comment by SpexGuy** [comment]
This alternate interface might be simpler:
```zig
fn getEntryByHash(self: Self, hash: u32, eql_ctx: anytype, comptime eql: fn(HashCtx, @TypeOf(eql_ctx), Key) bool) ?*Entry
```
Or, alternately:
```zig
fn getEntriesByHash(self: *Self, hash: u32) EntryIterator
```
