### ISSUE TITLE
undefined symbol: WinMain when linking libc and using the windows subsystem

### ISSUE THREAD

**Issue by travisfoo** [ziglang/zig#8620]
I get: `undefined symbol: WinMain` when linking libc and using the windows subsystem. My OS is Windows x86_64. Here's an easy way to reproduce:

    mkdir test
    cd test
    zig init-exe
    zig build-exe --subsystem windows -lc src/main.zig

I get this error:
```
lld-link: error: undefined symbol: WinMain
>>> referenced by D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:102
>>>               libcmtd.lib(exe_winmain.obj):(int __cdecl invoke_main(void))
error: LLDReportedFailure
```
I attempted to fix this in https://github.com/ziglang/zig/pull/8610 but I ran into some more issues. I was wondering if this is expected behavior when linking libc?

**Comment by kubkon** [comment]
@travisfoo could you re-check with 0.8.0 and then latest master if this is still an issue for you? I cannot replicate it on Win10 with the latest master targeting both mingw and msvc ABI.

**Comment by travisfoo** [comment]
Looks good on master now. Must have gotten fixed somewhere along the way. Thanks!
