### ISSUE TITLE
Ubuntu/Debian APT install instructions are outdated and the repo may have been abandoned

### ISSUE THREAD

**Issue by SmiVan** [ziglang/zig#8623]
The [distribution repo](https://github.com/dryzig/zig-debian) linked to from [the apt repository installation instructions](https://github.com/ziglang/zig/wiki/Install-Zig-from-a-Package-Manager#ubuntu-or-debian-using-apt) is no longer valid because of Bintray shutting down as described in the issue [here](https://github.com/dryzig/zig-debian/issues/11).

It should also be noted that the version distributed on that repo was already strongly outdated, and the repo appears to be unmaintained (last commit 11 months ago), so if nobody wants to maintain a fork of that - perhaps the mention of it should be removed from the installation instructions altogether.

**Comment by g-w1** [comment]
Since this is in the wiki, you could just edit the wiki to remove the apt install instructions if you think it is outdated. Maybe mention that it is outdated and include another solution.

**Comment by SmiVan** [comment]
Alright, since there aren't any APT alternatives I suppose I'll just remove it.

For Ubuntu, the snap version remains a good option (and is in fact what I use personally).
I suppose Debian users will have to opt for installing snap then, as far as I know snap does work on Debian.

**Comment by ruffianeo** [comment]
7 months later, the installation instructions for Debian still lead to: 
`Failed to fetch https://dl.bintray.com/dryzig/zig-debian/dists/bullseye/InRelease  403  Forbidden [IP: 34.209.123.136 443]`
I think the only viable resolution is to add zig to the regular debian distro thingy. Am I the only one who does not trust snap?

**Comment by TedsterTech** [comment]
And now 502 (:
