### ISSUE TITLE
unreachable gives error that the code is unreachable

### ISSUE THREAD

**Issue by N00byEdge** [ziglang/zig#8631]
When you have a `unreachable;` that is not reachable, it is a compiler error. For example:
```
unreachable;
unreachable;
```
Gives the following error on the second line:
```
error: unreachable code
unreachable;
```
This is more of an issue when you want to make sure some function you're passed in doesn't return, but it's a `noreturn` function:
```
some_noreturn_function();
unreachable;
```
Gives the same error message. This is also what happens in the standard library, where if you provide a `noreturn` byos `panic` (which honestly makes a lot of sense, and the standard library seems to make sure you don't return from it)
```
pub fn default_panic(msg: []const u8, error_return_trace: ?*StackTrace) noreturn {
    @setCold(true);
    if (@hasDecl(root, "os") and @hasDecl(root.os, "panic")) {
        root.os.panic(msg, error_return_trace);
        unreachable;
    }
// ...
```
Here, if your `root.os.panic` is `noreturn`, you get the same error.
You can work around this by putting the call inside an `if(true)`, since then it looks like the `noreturn` only will be called conditionally.

This is probably more of a language/compiler defect than anything else, most people in the discussion on the discord were in agreement on this.

**Comment by MasterQ32** [comment]
A related example where this might be a problem:
```zig
const std = @import("std");

pub fn main() void {
    const f = if (std.builtin.cpu.arch == .x86_64)
        a
    else
        b;
    f();
    unreachable;
}

fn a() noreturn {
    @panic("lol");
}
fn b() void {}
```

This code should always compile and not depend on using a certain target (it will trigger `error: unreachable code` on x86_64)

**Comment by xdBronch** [comment]
iiuc this error is in astgen rather than sema now so its not a problem anymore, all the examples compile other than the first

**Comment by N00byEdge** [comment]
> iiuc this error is in astgen rather than sema now so its not a problem anymore, all the examples compile other than the first

Yes. Why was it closed? Is the first example not meant to compile?

**Comment by xdBronch** [comment]
no since it's unconditionally unreachable unlike the others. same thing happens if there's code after a `return`, `@panic`, etc. workaround if you need to do that is usually to wrap the first noreturn statement in `if (true)`

**Comment by N00byEdge** [comment]
Yes but shouldn't a literal `unreachable;` statement be excluded from this rule?
