### ISSUE TITLE
Zig cc: search for lib*.a as well as *.lib when targeting unknown-windows-gnu

### ISSUE THREAD

**Issue by Keithcat1** [ziglang/zig#8685]
This bug seems to stop me from statically linking library files on Windows targeting x86_64-unknown-windows-gnu, but probably on i686 as well.
My problem: I was linking to a library "-lsdl2_windows_amd64", and zig reported that that sdl2_windows_amd64.lib couldn't be found.
The actual name of the file is libsdl2_windows_amd64.a
My use case is that I'm trying to cross-compile Go applications using SDL2 via https://github.com/veandco/go-sdl2

I'm using Zig 0.7.1.

**Comment by LemonBoy** [comment]
Is this #7799 ?

**Comment by Keithcat1** [comment]
Yes. Sorry about that. I'll close this one.
