### ISSUE TITLE
Default to not automatically modifying a file when it is opened

### ISSUE THREAD

**Issue by jacquesh** [ziglang/zig#8710]
When opening a file (via `std.fs.createFileAbsolute`) one needs to pass in some flags. All of those flags default to off/false or some other reasonable default in the case of modes. All of them except `truncate` that is.

I'm trying out Zig after not having used it for a year or two and I needed to check file size of all the files in a directory. After some syntax-wrangling, and checking [the docs](https://ziglang.org/documentation/master/std/#std;fs.createFileAbsolute), I called `createFileAbsolute` with `{.read = true}`, only to be told that all my files are now zero bytes. On a directory full of previously-not-empty files.

Now I recognise that the docs are an experimental work-in-progress (and it would be great if they showed default values) and I admit that if I had been carefully reading the stdlib files I probably would have noticed this and set `.truncate = false`. Maybe there is a good reason for the current setup, but I think it is very dangerous to have the standard library default to destroying your files when you open them. In my case the destroyed files were a copy of another directory but I would be very sad if that were not the case.

**Comment by MasterQ32** [comment]
For me, this is 100% expected behaviour. `createFile` does not *open* a existing file, but will *create* a new one. If you want to check out file contents of existing files, use `openFile`, which will fail if the file does not exist.

If you use `createFile` with `truncate = false`, you will still *create* the file if it didn't exist before.

So in my opinion, there is nothing to change as this behaviour is the same across all other languages i've encountered and deriving from the usualy way here isn't a good idea

**Comment by jacquesh** [comment]
Aaaah I see what happened now. Once again this is what I get for making assumptions about docs that are specifically labelled as experimental. The only "open a file" function on that docs page is `openFileAbsoluteZ`, which is not what I want. I saw that and I saw `createFile` and just assumed that the way you open a file is by calling `createFile` (this is how the Win32 API works, for better or for worse, but I've been using that recently).

`openFileAbsolute` does exactly what I want and what one would expect from the name. Thanks for pointing me in the right direction!

**Comment by MasterQ32** [comment]
@jacquesh It's recommended to check out the source. Also, zig file i/o is based around directory handles, a concept not much standard libraries use. The correct `openFile` method is this:

https://github.com/ziglang/zig/blob/2299e5ff1dc924a2dca0c0c2def6f1e7b71a668f/lib/std/fs.zig#L758-L772

which requires you to obtain a directory handle (or use `std.fs.cwd()` for the current working directory). Note that you can also pass absolute paths here!
