### ISSUE TITLE
x86_64+macos: bootstrapped stage1 fails sigaction when run via Rosetta

### ISSUE THREAD

**Issue by kubkon** [ziglang/zig#8743]
Bootstrapped x86_64 stage1 compiler fails sigaction test case when run via Rosetta on my M1 MBA. The same test passes fine when run natively on my Intel MBP, and when run natively (arm64) on my M1 MBA:

```
expected null, found fn(c_int, *const os.bits.darwin.siginfo_t, ?*const c_void) callconv(.C) void@105158c10
os.test.test "std-native-Debug-multi sigaction"... FAIL (TestExpectedEqual)
```

This might be more of a curiosity than something that requires a fix, but I'm posting it here nonetheless given that x86_64 programs are expected to be handled by Rosetta only in the near future since Apple is fully committing to arm64.

Oh, I bet this will interest you @LemonBoy!

**Comment by kubkon** [comment]
> Sounds to me like a bug for Apple to deal with, not Zig!

Agreed! I just wanted to leave a note (could be as a closed issue too btw), and briefly investigate since in the past Rosetta did uncover a bug in `zig ld` on x86_64 which run just fine on an actual Intel MBP for simple examples.

**Comment by LemonBoy** [comment]
Is this the `expectEqual` that's failing?
```zig
try testing.expectEqual(S.handler, old_sa.handler.sigaction.?);
```
The `expected null` part is extra-weird, that means `S.handler` is somehow interpreted as a null pointer.
Could you please dump the content of `S` and `old_sa` right before the `expectedEqual` call?

**Comment by mikdusan** [comment]
Issue is no longer applicable because of new zig1.wasm bootstrap.
