### ISSUE TITLE
Compiler allows use of outer scoped runtime variables from an fn defined inside it

### ISSUE THREAD

**Issue by tgschultz** [ziglang/zig#876]
```
fn outer(y: u32) fn(u32) u32 {
    const st = struct {
        fn get(z: u32) u32 {
            return z + y;
        }
    };
    return st.get;
}

test "reference runtime variable in outer function scope" {
    var func = outer(10);
    var x = func(3);
}
```
Oddly the test fails in this instance, usually I just get segfaults.
This is actually useful behavior for comptime vars and constants as it can be used to create a sort of comptime closure.

**Comment by andrewrk** [comment]
![screenshot_2018-09-05_20-37-39](https://user-images.githubusercontent.com/106511/45128349-8e212300-b14b-11e8-806d-4dea40ed8392.png)
