### ISSUE TITLE
Zig error messages can be very hard to read on terminals with light theme

### ISSUE THREAD

**Issue by koachan** [ziglang/zig#8761]
On light-themed terminals, Zig output might use colors that is too bright that it almost blends with the background color.

For example, this is some Zig error message on MATE Terminal with the default "black-on-white" color scheme:
![Zig screenshot showing hard-to-read text](https://user-images.githubusercontent.com/38437009/118129455-61f2ef80-b426-11eb-9d58-070e1e1c1fa9.png)

And here is the text copy of the above screenshot:
```
/home/k/zig/src/zig/lib/std/heap.zig:0:13: 0x4627eb in std.heap.CAllocator.resize (zig1)
/home/k/zig/src/zig/lib/std/heap.zig:0:13: 0x4627eb in std.heap.CAllocator.resize (zig1)
/home/k/zig/src/zig/lib/std/heap.zig:0:13: 0x4627eb in std.heap.CAllocator.resize (zig1)
/home/k/zig/src/zig/lib/std/heap.zig:0:13: 0x4627eb in std.heap.CAllocator.resize (zig1)
???:?:?: 0x46c2eb in ??? (???)
/home/k/zig/src/zig/src/stage1.zig:45:43: 0x46a453 in main (zig1)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
                                          ^
```

There is the `--color off` option, but would it be okay to change the default coloring scheme into something more "neutral", if possible?

**Comment by mikdusan** [comment]
Does your terminal export `COLORFGBG` ? That's one way zig could be enhanced to decide on dark vs. light colour scheme.

Another is apparently xterm supports querying for fg/bg values but I'm not sure how that plays out for 4-bit, 8-bit and 24-bit support.

**Comment by koachan** [comment]
> Does your terminal export `COLORFGBG`?

Sadly, mine doesn't seem to export that variable, though it does support querying fg/bg colors through the xterm OSC 11 sequence.

**Comment by LemonBoy** [comment]
You should fix the colorscheme instead, that red color is unreadable on white backgrounds and that's orthogonal to what's being printed.

**Comment by koachan** [comment]
I found out that the code responsible to print those lines is hardcoded to print in white. Would it be okay to change this into e.g red or green so that it'd work in light themes too?
There could be some sort of autodetection implemented in the future, but I feel like red/green text is a good-enough solution for now.
https://github.com/ziglang/zig/blob/master/lib/std/debug.zig#L632

(At this point I don't know if this discussion is becoming too bikesheddy so I'll close this issue if it's not okay to change the colors :D)

> You should fix the colorscheme instead, that red color is unreadable on white backgrounds and that's orthogonal to what's being printed.

Yeah, this works, but I don't think that changing the terminal's idea of white is a good solution for this?

**Comment by LemonBoy** [comment]
Does this patch work for you?

```patch
diff --git a/lib/std/debug.zig b/lib/std/debug.zig
index 6cca67f30..3c8423c38 100644
--- a/lib/std/debug.zig
+++ b/lib/std/debug.zig
@@ -306,6 +306,7 @@ const RED = "\x1b[31;1m";
 const GREEN = "\x1b[32;1m";
 const CYAN = "\x1b[36;1m";
 const WHITE = "\x1b[37;1m";
+const BOLD = "\x1b[1m";
 const DIM = "\x1b[2m";
 const RESET = "\x1b[0m";
 
@@ -476,8 +477,9 @@ pub const TTY = struct {
                     .Red => out_stream.writeAll(RED) catch return,
                     .Green => out_stream.writeAll(GREEN) catch return,
                     .Cyan => out_stream.writeAll(CYAN) catch return,
-                    .White, .Bold => out_stream.writeAll(WHITE) catch return,
+                    .White => out_stream.writeAll(WHITE) catch return,
                     .Dim => out_stream.writeAll(DIM) catch return,
+                    .Bold => out_stream.writeAll(BOLD) catch return,
                     .Reset => out_stream.writeAll(RESET) catch return,
                 },
                 .windows_api => if (builtin.os.tag == .windows) {
@@ -629,7 +631,7 @@ fn printLineInfo(
     comptime printLineFromFile: anytype,
 ) !void {
     nosuspend {
-        tty_config.setColor(out_stream, .White);
+        tty_config.setColor(out_stream, .Bold);
 
         if (line_info) |*li| {
             try out_stream.print("{s}:{d}:{d}", .{ li.file_name, li.line, li.column });
```

**Comment by koachan** [comment]
Oh yeah, it works, thanks!
