### ISSUE TITLE
translate-c: parse types properly in macros

### ISSUE THREAD

**Issue by xackus** [ziglang/zig#8767]
Right now type parsing in translate-c is simplified and special-cased, which leads to bugs like #4071.

@Vexu
```
<andrewrk> might want to coordinate with Vexu - he mentioned possibly wanting to tackle that with his https://github.com/Vexu/arocc project
```
I started modifying the parser to match the spec better. What are your current plans, does it make sense for me to continue?

**Comment by xackus** [comment]
@Vexu Hello?

**Comment by xackus** [comment]
also cc @ehaas

**Comment by Vexu** [comment]
I have no plans to do anything about this currently, so go ahead with your modifications.
