### ISSUE TITLE
"UnableToSpawnCCompiler" error when using zig cc

### ISSUE THREAD

**Issue by sagehane** [ziglang/zig#8786]
Tested on versions: `0.8.0-dev.2237+8eea5eddf` (the one on the website as of today) and `0.8.0-dev.2272+d0bea1fa2` on NixOS

The Problem:
---
`zig cc` and `translate-c` causes the following error message:
```
error: unable to create compilation: UnableToSpawnCCompiler
```
This didn't occur with a binary I compiled only a few days prior (I forgot what version), so it must have been introduced recently.

The error was produced by running `zig cc` and `zig translate-c -lc` on the Hello World code [here](https://www.tutorialspoint.com/learn_c_by_examples/hello_world_program_in_c.htm).

**Comment by sagehane** [comment]
I don't seem to get the error on `0.8.0-dev.2204+ace571455` but do get it by `0.8.0-dev.2218+90a54f06e`. That should narrow the relevant commit quite a bit.

**Comment by LemonBoy** [comment]
Zig will now try to use the system libc, in order to do so it has to query the default compiler `cc` about the standard include/lib/crt paths.

**Comment by sagehane** [comment]
Ah, figures. Then I guess that clears up any confusion I had, and this issue can be closed, thanks.

**Comment by LemonBoy** [comment]
Please keep it open, the compiler should print a useful error message rather than a cryptic `UnableToSpawnCCompiler`.

**Comment by ifreund** [comment]
@sagehane regarding the error you got on void linux (presumably using a static zig binary downloaded from https://ziglang.org/download): https://github.com/ziglang/zig-bootstrap/issues/57
