### ISSUE TITLE
unable to build LLD from source due to missing libunwind.h file

### ISSUE THREAD

**Issue by ZapAnton** [ziglang/zig#8792]
[Upstream Bug Report](https://bugs.llvm.org/show_bug.cgi?id=49228)

-----

I tried following [this section](https://github.com/ziglang/zig/wiki/How-to-build-LLVM,-libclang,-and-liblld-from-source#posix) in order to build local llvm.
However, I was unable to build `lld`, because the source code of `lld` depends on the file, that is not present in the `lld` source code archive (`libunwind/include/mach-o/compact_unwind_encoding.h`).

I used the following steps to build `llvm`:
```shell
$ git clone https://github.com/llvm/llvm-project.git  -b release/12.x --single-branch --depth=1
$ cd llvm-project/
$ mkdir build && cd build
$ cmake ../llvm/ -DLLVM_ENABLE_PROJECTS="clang;lld" -DCMAKE_INSTALL_PREFIX=$HOME/local -DCMAKE_PREFIX_PATH=$HOME/local -DCMAKE_BUILD_TYPE=Release
$ cmake --build .
$ cmake --install .
```
This allowed me to build all the necessary `llvm` tools for the Zig building process.
Perhaps the wiki instructions could be rewritten to use the `llvm-project`?

**Comment by Snektron** [comment]
Hello, i had previously added this to the wiki (see https://github.com/ziglang/zig/wiki/How-to-build-LLVM,-libclang,-and-liblld-from-source/405983df37c9ebb57e251e33702db7727c7b47e4) but it seems Andrew removed them again. Im not sure why.

**Comment by andrewrk** [comment]
Wiki instructions are correct. LLD has a bug upstream. Monorepo is not the solution. Next step here is to find or create the upstream bug report for LLD. I'm sure every package maintainer of LLD for every Linux distribution has already hit this same problem.
