### ISSUE TITLE
ability to directly include C .h files in zig source

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#88]
Introducing the `c_import` top level declaration:

``` zig
pub c_import {
    @link("c");
    if (@compile_var("os") == "linux") {
        @c_define("_GNU_SOURCE", true);
    }
    @c_include("stdio.h");
}
```

Linking is moved from `#link("c")` on an `extern` block. `extern` blocks are removed in favor of `extern` simply being a top level declaration for declaring a function prototype:

``` zig
pub extern fn puts(c: &const u8) -> c_int;
```

The block given to `c_import` is an expression which can be evaluated with the constant expression evaluator. In this context, but no other context, `@link`, `@c_define`, `@c_undefine`, and `@c_include` can be called.

`@link` adds an entry to the link table; the argument will later be linked with ld.

The other two function calls build a string which will be fed to libclang for processing. The example above, if the `@c_define` got evaluated, would produce:

```
#define _GNU_SOURCE 1
#include "stdio.h"
```

Next, zig uses libclang to process this C snippet and come up with function definitions. If you use `pub` on the `c_import` declaration, then all functions imported this way are made public. Otherwise, they are not public, but you can use the `pub` top level declaration to explicitly choose some functions to make public.

Except for top level declarations that they depend on, `c_import` declarations are evaluated before all other top level declarations.

You can make more than one `c_import` declaration if you want and they will be evaluated separately. However, it is faster and makes more sense to do all your includes in one `c_import` declaration if you can. If you import stdio.h in the same file with two different `c_import` declarations, you will get an error for symbols overriding each other.

If two independent files both import some_header.h, however, they each get their own definitions of those symbols. It is quite possible, based on preprocessor defines, for a function to have return type `bool` from one `c_import` but return type `c_int` from another `c_import`. However, because we can rely on the ABI being the same, we can safely allow these two definitions to coexist, provided they are in separate .zig files.

Because `c_import` declarations are independent, this feature does not compromise order-independent declarations.

**Comment by andrewrk** [comment]
* [ ] simple include of several includes
 * [ ] include based on a compile var
 * [ ] `@c_define` and `@c_undef`

**Comment by cosarara97** [comment]
Adding a comment next to a #define will break it. Eg., in SDL2's SDL.h:

    #define SDL_INIT_VIDEO 0x00000020  /**< SDL_INIT_VIDEO implies SDL_INIT_EVENTS */

Doesn't work, while:

    #define SDL_INIT_VIDEO 0x00000020

Does

**Comment by andrewrk** [comment]
Thanks for the report, I added it to the TODO list.

**Comment by daurnimator** [comment]
I think this issue can be closed now: the general feature exists, it just has bugs and TODOs.

**Comment by andrewrk** [comment]
I do want to go over the checklist in https://github.com/ziglang/zig/issues/88#issuecomment-175283067 and make sure the items are addressed by other issues
