### ISSUE TITLE
SIMD instructions generated with SIMD disabled

### ISSUE THREAD

**Issue by N00byEdge** [ziglang/zig#8803]
Somewhere between 0.7.1 and 0.8.0 (supposedly on LLVM 12 update), code which explicitly disables SIMD register operations all of a sudden start generating SIMD instructions:
```
0x401022ec MOVI            V0.16B, #0xAA
0x40102318 STP             Q0, Q0, [SP,#0x60+var_40]
0x4010231C STP             Q0, Q0, [SP,#0x60+var_60]
```

While reproducible, I've been unable to make a minimal reproducible example. The best I can offer is to use [Sabaton](https://github.com/FlorenceOS/Sabaton), run `zig build virt` see if the following to appear:

```
Taking exception 1 [Undefined Instruction]
...from EL1 to EL1
...with ESR 0x7/0x1fe0000a
...with ELR 0x401022ec
...to EL1 PC 0x40101800 PSTATE 0x3c5
Taking exception 4 [Data Abort]
```

I've been able to narrow it down to storing 64+ bytes of `0xAA`(undefined fill) for variables on the stack. Could honestly be an LLVM issue for all I know.

**Comment by N00byEdge** [comment]
Looking into it more, using `exc.want_lto = false;` Works around this issue, this issue most likely is LTO related. Does LTO not take target settings into account?

**Comment by LemonBoy** [comment]
The LTO pipeline generates code at a late stage, during the linking process. All the feature flags must be stored inside the LLVM info for this to work as expected, right now the compiler forgets them and uses the default target instead.

Implementing this is easy, the compiler must emit `target-cpu`, `tune-cpu` and `target-features` for each function.
