### ISSUE TITLE
Add caching to `run` command

### ISSUE THREAD

**Issue by tiehuis** [ziglang/zig#881]
The current `zig run` command is fairly simplistic right now. It does not perform any caching and will recompile source every invocation. Since this is a large, fairly complicated and only impacts usability/performance of the command, this should only be implemented for the self-hosted compiler.

We need to consider the following ways in which the cache may be invalidated:

 * [ ] whether the root source file changed (in name or contents)
 * [ ] the args to the compiler
 * [ ] whether any of the files that are depended on via `@import` changed
 * [ ] whether any of the files that are depended on via `@embedFile` changed
 * [ ] whether zig binary changed
 * [ ] whether any of the dynamic libraries that zig binary depends on changed, and their dynamic library dependencies, recursively
 * [ ] whether any of the above things changed, but for the builtin.o target
 * [ ] whether any of the above things changed, but for the compiler_rt.o target
 * [ ] if the binary does C importing, we have to check if any of the .h files that libclang looked at changed. This may require careful integration with libclang.
 * [ ] whether any of the `--object` or `--library` files changed, and recursively for dynamic libraries.
 * [ ] other command line args that reference files, such as linker scripts

---

Other possible improvements:

 * [ ] handle SIGABRT in the spawned process to get the correct status code returned by the calling `zig run` process.

**Comment by bnoordhuis** [comment]
Is the idea to use file timestamps as a cheap first-pass filter before hashing?

If yes, then a cache entry should be invalidated not only when its timestamp is older but also when it's newer than its on-disk counterpart(s); it probably means the system clock jumped back in time.

**Comment by andrewrk** [comment]
Instead if mtime I'd like to hash the file contents. We can have a cache of hashed file contents; and we can use mtime equality to determine if the file contents hash needs to be recomputed.
