### ISSUE TITLE
sort compile errors before presenting them to eliminate nondeterministic error reporting

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#8826]
The `getAllErrorsAlloc` function returns a list, which contains an order, of compile errors. But most of the compile errors are stored in hash maps and do not necessarily have an order.

This issue is to:

1. Come up with an idea for what is the most reasonable way to order compile errors, based on deterministic factors.
2. Implement sorting based on this ordering so that `getAllErrorsAlloc` returns a deterministic list of compile errors.

**Comment by lithdew** [comment]
IIRC the default auto hash fn is deterministic, so for keys that are immutable values that are hashed directly, there should be a deterministic ordering.

In that case, the only thing left to do then is have maps with keys that are pointers have their hash and comparator fns hash/compare based on the keys' fields that are deterministic, right?

**Comment by andrewrk** [comment]
There is another source of non-determinism which is that Tokenization, Parsing, and AstGen runs in parallel on a thread pool for all files in a compilation. If any files produce compile errors during any of these steps, their order in the `Module.failed_files` ArrayHashMap will be determined by threads racing.

**Comment by lithdew** [comment]
> There is another source of non-determinism which is that Tokenization, Parsing, and AstGen runs in parallel on a thread pool for all files in a compilation. If any files produce compile errors during any of these steps, their order in the `Module.failed_files` ArrayHashMap will be determined by threads racing.

Is the order in which tasks for Tokenization + Parsing + AstGen are created then scheduled deterministic? i.e. so that a sort of task order index can be added as a field to each task?

**Comment by andrewrk** [comment]
I don't think that is possible without a needlessly complicated mechanism, that limits the amount of concurrency. Each file that goes through this process reveals more files to be processed (via the string literal argument to `@import`) which are then added to the task list. This logic is easy to understand and maintain, and the files can easily be sorted later by path name to remove the non-determinism. So a given file could have been imported by a different import chain tracing back to the root file, depending on thread races.

**Comment by andrewrk** [comment]
This is implemented now.
