### ISSUE TITLE
stage2 compilation on MacOS broken, panic: attempt to use null value in src/link/MachO/Zld.zig

### ISSUE THREAD

**Issue by slimsag** [ziglang/zig#8832]
trying to compile stage2 on MacOS (catalina) I get a zld panic:

```
thread 8016199 panic: attempt to use null value
/Users/slimsag/Desktop/hexops/zig/src/link/MachO/Zld.zig:2962:74: 0x10d6db636 in link.MachO.Zld.writeCodeSignature (zig1)
    const text_seg = self.load_commands.items[self.text_segment_cmd_index.?].Segment;
                                                                         ^
/Users/slimsag/Desktop/hexops/zig/lib/std/hash_map.zig:410:47: 0x10d6c64e7 in std.hash_map.HashMapUnmanaged(u16,u16,std.hash_map.getAutoHashFn(u16).hash,std.hash_map.getAutoEqlFn(u16).eql,80).deallocate (zig1)
            const meta_size = @sizeOf(Header) + cap * @sizeOf(Metadata);
                                              ^
/Users/slimsag/Desktop/hexops/zig/src/link/MachO/Zld.zig:894:9: 0x10d684dca in link.MachO.Zld.sortSections (zig1)
        for (indices) |maybe_index| {
        ^
/Users/slimsag/Desktop/hexops/zig/lib/std/hash_map.zig:509:58: 0x10d676b16 in std.hash_map.HashMapUnmanaged([]const u8,void,std.hash_map.hashString,std.hash_map.eqlString,80).putAssumeCapacityNoClobber (zig1)
            const fingerprint = Metadata.takeFingerprint(hash);
                                                         ^
...
```

I am using the absolute latest `master` revision:

```
$ git rev-parse --short HEAD
1d6c804b2
```

Full logs here: https://gist.github.com/slimsag/9303f03066a5d3e841bfbe997cb520cf

**Comment by kubkon** [comment]
Thanks for the report @slimsag! The error trace looks funky since it leads us to believe there was no `__TEXT` segment created which is always the case. Would you mind running trying it in debugger and obtaining the stack trace that way?

```
lldb -- <bin with args>
(lldb) r
(lldb) bt
```

**Comment by kubkon** [comment]
Oh I just now browsed over the full logs. Since you are building with the system compiler, and LLVM is adding static archives as `-llibName` rather than a fully qualified path, try rebuilding stage1 with `ZIG_STATIC=on`. This should hopefully fix your issue.

**Comment by slimsag** [comment]
Appreciate the help @kubkon :) Here's the debugger stack trace: https://gist.github.com/slimsag/c28dd9b2aada8467ae1225b044043cfd#file-gistfile1-txt-L982-L1010

Oddly, compiling stage1 with:

```
cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix llvm) -DZIG_STATIC=on
make install
```

Causes the final link to fail due to there being a GCC-specific `-static-libgcc` flag:

```
Consolidate compiler generated dependencies of target zig0
[ 98%] Building CXX object CMakeFiles/zig0.dir/src/stage1/zig0.cpp.o
[ 99%] Linking CXX executable zig0
clang: error: unsupported option '-static-libgcc'
make[2]: *** [zig0] Error 1
make[1]: *** [CMakeFiles/zig0.dir/all] Error 2
make: *** [all] Error 2
```

Ah, and I just saw your edit which will likely resolve that :) thanks!

**Comment by slimsag** [comment]
That indeed worked around the issue for me, thank you @kubkon !

**Comment by kubkon** [comment]
> That indeed worked for me, thank you @kubkon !

Awesome, glad to hear!

**Comment by kubkon** [comment]
I believe this should now be fixed in the sense that when not specifying `ZIG_STATIC_LLVM=on`, there should be no panics generated. Could you confirm and close @slimsag?

**Comment by slimsag** [comment]
Can confirm this is fixed 👍 was able to build stage2 on Catalina
