### ISSUE TITLE
Windows, .gnu abi, looking for glfw3.lib instead of libglfw3.a

### ISSUE THREAD

**Issue by michal-z** [ziglang/zig#8836]
In my build.zig, I'm forcing .gnu abi like this:
`
exe.setTarget(.{
            .cpu_arch = .x86_64,
            .os_tag = .windows,
            .abi = .gnu,
        });
`

And then I link with glfw3:

`
    exe.linkSystemLibrary("glfw3");
`

After doing this, Zig complains that it can't find glfw3.lib. This is a bug because it should look for libglfw3.a
This looks like a regression it worked in the past.

Thanks.

**Comment by LemonBoy** [comment]
#7799

**Comment by michal-z** [comment]
> 
> 
> #7799

Thanks, sorry for the duplicate, I will close this one.
