### ISSUE TITLE
Casting usize to Byte array?

### ISSUE THREAD

**Issue by molnarmark** [ziglang/zig#884]
Looks like the casting section in the documentation is still TODO, and I'm stuck when it comes to casting usize to []const u8 (to be passed to the write function in std.io)

```zig
const std = @import("std");
const linux = std.os.linux;
const endian = std.endian;

pub fn main() !void {
  const socket_ret = linux.socket(linux.AF_INET, linux.SOCK_STREAM, linux.PROTO_tcp);
  const socket_err = linux.getErrno(socket_ret);
  var stdout = try std.io.getStdOut();

  if (socket_err > 0) {
    try stdout.write("Socket error.");
  } else {
    try stdout.write("Socket created.");
  }

  stdout.write(u8(socket_err)); // This obviously fails
}
```

I'm pretty sure this can be done somehow, if someone could enlighten me, it would be appreciated! 🎉

**Comment by andrewrk** [comment]
It looks like you're trying to get an error message from an error code. Or are you trying to print the error code to the socket?

```
try stdout.write("socket failure: {}\n", socket_err);
```

**Comment by molnarmark** [comment]
What I'm basically trying to do is printing out anything that isnt a byte array. The given example with the sockets here is trivial. However I've started experimenting with the sockets due to the net.zig file saying its outdated code and is missing the host lookup implementation (*gethostbyname*, which might just raise another question about Zig).

The example you gave crashes with the following error:
```
error: expected 2 arguments, found 3
  try stdout.write("socket failure: {}\n", socket_err);
```

**Comment by andrewrk** [comment]
Oops. If you want to use the fancy formatting API you gotta make an OutStream. 

```
var adapter = std.io.FileOutStream.init(stdout);
var stream = &adapter.stream;
try stream.print("socket failure: {}\n", socket_err);
```

**Comment by molnarmark** [comment]
Thank you, makes sense. I believe the 'File' in the name had me confused.

**Comment by andrewrk** [comment]
The only thing that goes over a network socket is a stream of bytes. If you want a `usize` to get sent over the network, you need to encode it into a series of bytes. Here are some obvious choices:
 * serialize as utf8-encoded text and send those bytes
 * serialize as 8 big-endian bytes and send those over
