### ISSUE TITLE
crypto: cast causes pointer to be null in secureZero

### ISSUE THREAD

**Issue by kubkon** [ziglang/zig#8841]
For a couple of days now, I've been greeted by this _sporadic_ panic on my x86_64 linux box:

```
thread 169504 panic: cast causes pointer to be null
/home/kubkon/dev/zig/lib/std/crypto/utils.zig:85:17: 0xca8dd8 in std.crypto.utils.secureZero (zig1)
    const ptr = @ptrCast([*]volatile u8, s.ptr);
                ^
/home/kubkon/dev/zig/lib/std/crypto/tlcsprng.zig:153:32: 0xb6c1d2 in std.crypto.tlcsprng.childAtForkHandler (zig1)
    std.crypto.utils.secureZero(u8, wipe_mem);
```

Usually rerunning the failing command again gets rid of this error for some bizarre reason. `wipe_mem` here is a TLV and I wonder if perhaps LLVM is not miscompiling it on occasion or something?

Would love your input here @LemonBoy and @jedisct1!

**Comment by kubkon** [comment]
I just noticed that this is tripping stage2 tests and in particular C backend tests on my machine.

**Comment by LemonBoy** [comment]
Good catch. There's a reason why `atfork` is considered a bad API, it's global and you can't unregister hooks.
What's happening here can be boiled down to this self-explanatory snippet:
```zig
const std = @import("std");

const R = std.crypto.random;

fn worker(x: void) void {
    const i = R.int(u32);
    // Initialize the tlcsprng context & register a global atfork handler.
}

pub fn main() !void {
    const t = (try std.Thread.spawn(worker, {})).wait();

    // The thread is dead _but_ we still have the fork hook registered here.
    // Remember that no tlcsprng was set-up for this thread.
    const pid = std.c.fork();
    if (pid == 0) {
        std.debug.print("P {x}\n", .{R.int(u32)});
        return;
    }

    std.debug.print("M {x}\n", .{R.int(u32)});
}
```

Given that every thread gets its own CSPRNG and that `fork()` is only duplicating the calling thread/process we need some extra logic to call `pthread_atfork` once per _process_ (as opposed to once per thread and process).

**Comment by kubkon** [comment]
Thanks for the explanation @LemonBoy! I might also add that in the case of the Zig compiler, I can pretty always replicate the fault when explicitly linking with libc.

**Comment by jedisct1** [comment]
Damn :(

That being said, looks like we are setting up the handler even if `MADV_WIPEONFORK` succeeded. Isn't it redundant?

Other OS have `MADV_WIPEONFORK` equivalents (ex: `MAP_INHERIT_ZERO` on OpenBSD), so we should rely on the OS as much as possible.

On platforms without such as feature, I don't see a reliable way to do this without locking.

BoringSSL uses `MADV_WIPEONFORK`, mutexes otherwise: https://github.com/google/boringssl/blob/master/crypto/fipsmodule/rand/fork_detect.c

I don't think we can do much better.
