### ISSUE TITLE
Proposal: Improving Ptrs and Ownership

### ISSUE THREAD

**Issue by BraedonWooding** [ziglang/zig#885]
> edited to use std.heap :).

Okay currently pointers that aren't 'local' or stack based seem to be unconventional.  I think Zig could benefit from a 'smart pointer' like system (that doesn't go overboard of course).  I have only coded some basic things in Zig but due to its similarity the code should be correct :).

## Std way

```zig
const std = @import("std");
const heap = std.heap;
const assert = std.debug.assert;

fn getPtr() error!&int {
    // Normally if it was just 
    // var x = 4; return &x; then it would be a null ptr
    var x = try heap.c_allocator.alloc(int, @sizeof(int));
    *x = 4;
    return x;
}

test "MallocTest" {
    // As this is a test we want to produce error if it runs out of memory
    var ptr : &i32 = try getPtr();
    assert(*ptr == 4);
    heap.c_allocator.free(ptr);
}
```

Now of course a lot of memory issues come from this being used badly so adding a few ownership tools could help the first being a struct ownership tag.

```zig
const Foo = struct {
    bar: &i32;
    @owns(bar); // Or maybe #owns bar: &int;
}

test "Ownership Struct" {
    var ptr : ?&i32 = try getPtr();
    {
         // Cast to non-nullable
         const foo = Foo { .bar = ptr ?? unreachable };
         assert(*foo.bar == 4);
    }
    assert(ptr == null);
}
```

Furthermore something like the idea of a unique ptr which would just be like this;
```zig
pub fn MakeUniquePtr(T: Type, value: T, alignment: u29) UniquePtr {
    var x = heap.c_allocator.alloc(T, @sizeof(T));
    *x = value;
    return struct {
        ref: &T = x;
        @owns(ptr);
        @hidden(ptr); // private
        pub fn get(self: this) T {
            return *ref;
        }
    }
}

test "UniquePtr" {
    var ptr = MakeUniquePtr(int, 4);
    assert(ptr.get() == 4);
}
```

Which is actually quite nice to be honest.  This does prevent copying just so its close to the spec of C++, however I would say that we don't need to prevent it as this is more around just who owns the ptr then anything.

I feel the best way to get involved is jumping in the deep end so hopefully I got most things right :).

**Comment by Hejsil** [comment]
Related: #494 and #782

**Comment by andrewrk** [comment]
The clean defer stuff looks like #782.

As for the original proposal, it's not really clear to me how it works or what the benefits are, and looking at it, I'm not inspired to do anything with it.
