### ISSUE TITLE
Enum typeinfo tag_type does not respect ordinal values by default

### ISSUE THREAD

**Issue by chrissinclair** [ziglang/zig#8851]
Hello,

When providing ordinal values for an enum, when not specifying the underlying type of the enum, the compiler appears to default to using the number of variants to figure out the size the enum should be rather than the provided ordinal values:

```zig
const std = @import("std");

const Values = enum {
    v1 = 1000,
    v2 = 2000,
};

pub fn main() anyerror!void {
    const enum_tag_type = @typeInfo(Values).Enum.tag_type;
    const value = @intToEnum(Values, @intCast(enum_tag_type, @enumToInt(Values.v1)));
}
```
Output:
```sh
$ zig build
.\src\main.zig:4:10: error: integer value 1000 cannot be coerced to type 'u1'
    v1 = 1000,
         ^
.\src\main.zig:5:10: error: integer value 2000 cannot be coerced to type 'u1'
    v2 = 2000,
         ^
.\src\main.zig:9:27: note: referenced here
    const enum_tag_type = @typeInfo(Values).Enum.tag_type;
                          ^
```

I'm unclear if this is by design - it's pretty easily resolved, and the docs do have a defined tag_type when providing ordinals (although it's not explicitly called out).

**Comment by andrewrk** [comment]
If you run this code through the stage2 compiler, you get this:

```
$ ./zig ast-check test.zig
test.zig:4:10: error: value assigned to enum tag with inferred tag type
    v1 = 1000,
         ^
```

So this is an issue to add the same compile error to stage1.
