### ISSUE TITLE
directEnumArrayLen should be public

### ISSUE THREAD

**Issue by silversquirl** [ziglang/zig#8875]
In the current state, it's awkward to define an array field to be initialized with a `directEnumArray`. Exposing `directEnumArrayLen` publicly would solve this problem

**Comment by andrewrk** [comment]
can't you just use the `.len` field?

**Comment by SpexGuy** [comment]
I think this makes sense since we can't infer field types - you may need to know the type in the absence of an instance.  What about `DirectEnumArray(...)` instead, as a way to just get the whole type.  Is there a reason you would want the `len` specifically but not the type?
