### ISSUE TITLE
clang crash with error 113 when compiling for "arm-unknown-linux-android"

### ISSUE THREAD

**Issue by ikskuh** [ziglang/zig#8885]
```
error(compilation): clang failed with stderr: zig: error: clang frontend command failed with exit code 133 (use -v to see invocation)
clang version 12.0.0 (git@github.com:ziglang/zig-bootstrap.git fc78f1770c0bccc5262577456da4172ae36abbc2)
Target: arm-unknown-linux-android
Thread model: posix
InstalledDir: /usr/bin
zig: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
zig: note: diagnostic msg: /tmp/stb_truetype-db2cc6.c
zig: note: diagnostic msg: /tmp/stb_truetype-db2cc6.sh
zig: note: diagnostic msg: 

********************

/home/felix/projects/libraries/zero-graphics/src/rendering/stb_truetype.c:1:1: error: unable to build C object: clang exited with code 133
```

Both the files mentioned in the diagnostic message are attached here:
[bugreport.zip](https://github.com/ziglang/zig/files/6531713/bugreport.zip)

This bug only happens for `arm-linux-android`, not for `aarch64-linux-android` or  `x86_64-linux-android`

**Comment by andrewrk** [comment]
Next step here is for someone to make a clang bug report.

**Comment by andrewrk** [comment]
This issue will become even more contributor friendly after this weekend because LLVM is moving to using GitHub Issues for bug tracking. Any takers on filing that upstream bug report? :slightly_smiling_face:

**Comment by billzez** [comment]
I hit this issue, and I was able to workaround it by disabling "vfp3d16sp".  I'm wondering if zig is setting an illegal combination of cpu features.

**Comment by alexrp** [comment]
Other than the fact that we don't ship Android's libc, this "works" for me now. (`zig cc test.c -target arm-linux-android -nostdlib`)

**Comment by alexrp** [comment]
Closing per the above comment.
