### ISSUE TITLE
OpenGL - GLEW function call

### ISSUE THREAD

**Issue by palvferenc** [ziglang/zig#8898]
Hi,

I'm trying to make a simple opengl app which is utilizing shaders.
I got stuck with a compile error:

unable to evaluate constant expression pub const glCreateShader = GLEW_GET_FUN(__glewCreateShader);

Content of glew.h about shaders:

cat /usr/local/include/GL/glew.h | grep CreateShader:

#define glCreateShader GLEW_GET_FUN(__glewCreateShader)
#define glCreateShaderProgramv GLEW_GET_FUN(__glewCreateShaderProgramv)
#define glCreateShaderObjectARB GLEW_GET_FUN(__glewCreateShaderObjectARB)
#define glCreateShaderProgramEXT GLEW_GET_FUN(__glewCreateShaderProgramEXT)
GLEW_FUN_EXPORT PFNGLCREATESHADERPROC __glewCreateShader;
GLEW_FUN_EXPORT PFNGLCREATESHADERPROGRAMVPROC __glewCreateShaderProgramv;
GLEW_FUN_EXPORT PFNGLCREATESHADEROBJECTARBPROC __glewCreateShaderObjectARB;
GLEW_FUN_EXPORT PFNGLCREATESHADERPROGRAMEXTPROC __glewCreateShaderProgramEXT;

Does ZIG compiler can resolve C macros as glew defines?

Thx,
Ferenc

**Comment by ehaas** [comment]
Can you post your full program and the version of Zig you're using? I don't get that error with latest master of Zig + a simple glew demo program.

**Comment by palvferenc** [comment]
Hi,

Zig Freebsd pkg:

zig-0.7.1_2
Name           : zig
Version        : 0.7.1_2
Installed on   : Tue Apr 20 19:07:20 2021 CEST
Origin         : lang/zig
Architecture   : FreeBSD:13:amd64
Prefix         : /usr/local
Categories     : lang
Licenses       : MIT
Maintainer     : dch@FreeBSD.org
WWW            : https://ziglang.org/
Comment        : Language designed for robustness, optimality, and maintainability
Options        :
	STATIC         : on
Annotations    :
	FreeBSD_version: 1300139
	repo_type      : binary
	repository     : FreeBSD

Source: 

main-zig:

const std = @import("std");
const gl = @cImport({
      @cInclude("GL/glew.h");
});
const glfw = @cImport({
      @cInclude("GLFW/glfw3.h");
});

const warn = std.debug.warn;
const panic = std.debug.panic;

//var window: *glfw.GLFWwindow = undefined;

export fn errorCallback(err: c_int, description: [*c]const u8) void {
    panic("Error: {}\n", .{description});
}

pub fn main() u8 {
    _ = glfw.glfwSetErrorCallback(errorCallback);

    if (glfw.glfwInit() == glfw.GL_FALSE) {
        warn("Failed to initialize GLFW\n", .{});
        return 1;
    }

    var window = glfw.glfwCreateWindow(800, 600, "Learn OpenGL", null, null);
    if (window == null) {
        panic("Failed to create GLFW window\n", .{});
    }
    glfw.glfwMakeContextCurrent(window);
    const resizeCallback = glfw.glfwSetFramebufferSizeCallback(window, framebuffer_size_callback);

    gl.glewInit();

    var red : f32 = 0.0;
    var x: f32 = 0.0;
    var y: f32 = 0.0;

    compile_shader(gl.GL_VERTEX_SHADER);

    // render loop
    while (glfw.glfwWindowShouldClose(window) == 0) {
        // input

        if(red > 1.0)
            red = 0.1;

        red += 0.01;
        // render
        gl.glClearColor(red, 0.3, 0.3, 1.0);
        gl.glClear(gl.GL_COLOR_BUFFER_BIT);

        gl.glRectf(0.0,0.0,1.0,1.0);

        // glfw: swap buffers and poll IO events (keys pressed/released, mouse moved etc.)
        glfw.glfwSwapBuffers(window);
        glfw.glfwPollEvents();
    }

    return 0;
}

fn framebuffer_size_callback(window: ?*glfw.GLFWwindow, width: c_int, height: c_int) callconv(.C) void {
    // make sure the viewport matches the new window dimensions; note that width and
    // height will be significantly larger than specified on retina displays.
    gl.glViewport(0, 0, width, height);
}

fn compile_shader(shader_type: gl.GLenum) gl.GLuint {
   var shader = gl.glCreateShader(GL_VERTEX_SHADER);
   return shader;
}

build.zig:

const Builder = @import("std").build.Builder;

pub fn build(b: *Builder) void {
    // Standard target options allows the person running `zig build` to choose
    // what target to build for. Here we do not override the defaults, which
    // means any target is allowed, and the default is native. Other options
    // for restricting supported target set are available.
    const target = b.standardTargetOptions(.{});

    // Standard release options allow the person running `zig build` to select
    // between Debug, ReleaseSafe, ReleaseFast, and ReleaseSmall.
    const mode = b.standardReleaseOptions();

    const exe = b.addExecutable("micro-rts", "src/main.zig");
    exe.setTarget(target);
    exe.setBuildMode(mode);


    exe.addIncludeDir("/usr/local/include/glfw");
    exe.addIncludeDir("/usr/local/include/GL");

    exe.linkSystemLibrary("gl");
    exe.linkSystemLibrary("glfw3");

    exe.install();

    const run_cmd = exe.run();
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| {
        run_cmd.addArgs(args);
    }

    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);
}

**Comment by ehaas** [comment]
That looks like an example of lexical substitution that translate-c can't really handle; the workaround would be to use `gl.__glewCreateShader.?(gl.GL_VERTEX_SHADER)`

**Comment by palvferenc** [comment]
Hi,

I made the modification as you mentioned, it is successfully working now.
Thanks for your support!

Regards:
Ferenc

**Comment by xorza** [comment]
I'm facing the same issue and suggested solution to use `gl.__glewCreateShader.?(gl.GL_VERTEX_SHADER)` works. 

But it looks ugly, should this really be closed?

**Comment by Vexu** [comment]
With #20142 `gl.glCreateShader().?(gl.GL_VERTEX_SHADER)` works as well.
