### ISSUE TITLE
compile error: opaque types when calling gtk_dialog_run

### ISSUE THREAD

**Issue by mspiess** [ziglang/zig#8899]
I came across this error while developing a GTK+-2.0 application:

```
$ zig build
.\zig-cache\o\c4a94ea544f595448b5e6c996d319c24\cimport.zig:25108:5: error: opaque types have unknown size and therefore cannot be directly embedded in structs
    window: GtkWindow,
    ^
.\src\main.zig:9:18: note: referenced here
    const run = c.gtk_dialog_run(dialog);
                 ^
```

main.zig:
```zig
const c = @cImport({
    @cInclude("gtk/gtk.h");
});

pub fn main() anyerror!void {
    const dialog = c.gtk_dialog_new();
    defer c.gtk_widget_destroy(dialog);
    const run = c.gtk_dialog_run(dialog);
}
```

I'd be happy to see this resolved as this is blocking me right now.
Please let me know if you need more information.

**Comment by LemonBoy** [comment]
What's the content of `.\zig-cache\o\c4a94ea544f595448b5e6c996d319c24\cimport.zig:25108:5` ?

**Comment by mspiess** [comment]
Lines 25107-25113 are:
```zig
pub const struct__GtkDialog = extern struct {
    window: GtkWindow,
    vbox: [*c]GtkWidget,
    action_area: [*c]GtkWidget,
    separator: [*c]GtkWidget,
};
pub const GtkDialog = struct__GtkDialog;
```

The declaration of GtkWindow on line 24651f:
```zig
pub const struct__GtkWindow = opaque {}; // C:\msys64\mingw64\include\gtk-2.0\gtk/gtkwindow.h:71:16: warning: struct demoted to opaque type - has bitfield
pub const GtkWindow = struct__GtkWindow;
```

**Comment by LemonBoy** [comment]
There's no workaround for this error, bitfields are not supported ATM. Gtk3 should be better, a quick check shows no bitfield in sight ;)

**Comment by mspiess** [comment]
Actually I am trying to port a GIMP plugin to zig. I guess this means I will be targeting GIMP 3. Are there no plans to support bitfields in zig?

**Comment by LemonBoy** [comment]
There's #8840 but it's still in early stage.

**Comment by mspiess** [comment]
Alright, thanks for the pointer and the quick replies. I will close this issue then.
Cheers

**Comment by ehaas** [comment]
Using the linked PR I was able to get it to compile and run this:
```zig
const std = @import("std");
const c = @cImport({
    @cInclude("gtk/gtk.h");
});

pub fn main() anyerror!void {
    if (c.gtk_init_check(null, null) != 1) {
        return error.Failed;
    }
    const dialog = c.gtk_dialog_new();
    defer c.gtk_widget_destroy(dialog);
    const run = c.gtk_dialog_run(@ptrCast(*c.GtkDialog, dialog));
}
```

As long as the structs aren't being passed by value I think the PR will work fine. However I don't think it will make it into the mainline in its current state, so I guess it depends whether you are making this for personal use or as something you want to release.
