### ISSUE TITLE
No compile-time error for builtin function when one argument is known at compile time and the other one is not.

### ISSUE THREAD

**Issue by throwawayaccount12345-1** [ziglang/zig#8903]
Zig version: 0.8.0-dev.2661+5c2516045.tar.xz (2021-05-25)

The stage1 compiler does not produce an error when a builtin like `@mod` or `@rem` is called with a bad argument when one of the arguments is known at compile time and the other one is not. `@mod` rejects denominators that are zero or negative.

How to reproduce:
Compile this with `zig build-obj example.zig`.
```zig
export fn foo(x: i32) i32 {
    // _ = @mod(1, -2); // Uncomment for compile-time error.
    return @mod(x, -2); // No compile-time error. A runtime safety check is emitted instead.
}
```
This code emits a runtime check instead of producing a compile-time error.

If the first line is uncommented, we get a compile-time error as expected.
```
./example.zig:2:9: error: negative denominator
    _ = @mod(1, -2);
        ^
```

Expected behaviour: `return @mod(x, -2);` should issue a compile-time error.

**Comment by Vexu** [comment]
`negative denominator` is no longer an error.
