### ISSUE TITLE
macos,stage1: zig built from master and installed into a global prefix fails at compiling C/C++

### ISSUE THREAD

**Issue by kubkon** [ziglang/zig#8914]
I'm not sure whether this is a regression, but if you follow these steps:

1. `cmake .. -DCMAKE_PREFIX_PATH=/path/to/llvm -DCMAKE_INSTALL_PREFIX=/opt/zig2`
2. `cd $HOME && which zig`

```
/opt/zig2/bin/zig
```

3. `cd $HOME/gyro`
4. `zig build -Dbootstrap`

You end up with this error trace:

```
error(compilation): clang failed with stderr: /opt/zig2/lib/zig/libc/musl/crt/aarch64/crti.s:1:15: error: unexpected token in '.section' directive
.section .init
              ^
/opt/zig2/lib/zig/libc/musl/crt/aarch64/crti.s:3:1: error: unknown directive
.type _init,%function
^
/opt/zig2/lib/zig/libc/musl/crt/aarch64/crti.s:8:15: error: unexpected token in '.section' directive
.section .fini
              ^
/opt/zig2/lib/zig/libc/musl/crt/aarch64/crti.s:10:1: error: unknown directive
.type _fini,%function
^

error(compilation): /opt/zig2/lib/zig/libc/musl/crt/aarch64/crti.s:1:1: unable to build C object: clang exited with code 1
error(compilation): clang failed with stderr: /opt/zig2/lib/zig/libc/musl/crt/aarch64/crtn.s:1:15: error: unexpected token in '.section' directive
.section .init
              ^
/opt/zig2/lib/zig/libc/musl/crt/aarch64/crtn.s:5:15: error: unexpected token in '.section' directive
.section .fini
              ^

error(compilation): /opt/zig2/lib/zig/libc/musl/crt/aarch64/crtn.s:1:1: unable to build C object: clang exited with code 1
thread 986397 panic: reached unreachable code
???:?:?: 0x102127c23 in _std.debug.assert (???)
???:?:?: 0x102460153 in _std.array_hash_map.ArrayHashMapUnmanaged(Compilation.MiscTask,Compilation.MiscError,std.array_hash_map.getAutoHashFn(Compilation.MiscTask).hash,std.array_hash_map.getAutoEqlFn(Compilation.MiscTask).eql,false).putAssumeCapacityNoClobber (???)
???:?:?: 0x10228b86b in _Compilation.setMiscFailure.1418 (???)
???:?:?: 0x10227b267 in _Compilation.performAllTheWork (???)
???:?:?: 0x102276197 in _Compilation.update (???)
???:?:?: 0x10221e7ef in _main.updateModule (???)
???:?:?: 0x10215bc0f in _main.buildOutputType (???)
???:?:?: 0x10213422f in _main.mainArgs (???)
???:?:?: 0x102133d5b in _main (???)
???:?:?: 0x1805d144f in ??? (???)
Panicked during a panic. Aborting.
gyro...The following command terminated unexpectedly:
/opt/zig2/bin/zig build-exe /Users/kubkon/dev/gyro/src/main.zig --pkg-begin build_options /Users/kubkon/dev/gyro/zig-cache/gyro_build_options.zig --pkg-end --cache-dir /Users/kubkon/dev/gyro/zig-cache --global-cache-dir /Users/kubkon/.cache/zig --name gyro -target native-native-musl -mcpu apple_a14 --pkg-begin clap /Users/kubkon/dev/gyro/libs/zig-clap/clap.zig --pkg-end --pkg-begin version /Users/kubkon/dev/gyro/libs/version/src/main.zig --pkg-begin mecha /Users/kubkon/dev/gyro/libs/mecha/mecha.zig --pkg-end --pkg-end --pkg-begin tar /Users/kubkon/dev/gyro/libs/tar/src/main.zig --pkg-end --pkg-begin zzz /Users/kubkon/dev/gyro/libs/zzz/src/main.zig --pkg-end --pkg-begin glob /Users/kubkon/dev/gyro/libs/glob/src/main.zig --pkg-end --pkg-begin zfetch /Users/kubkon/dev/gyro/libs/zfetch/src/main.zig --pkg-begin hzzp /Users/kubkon/dev/gyro/libs/hzzp/src/main.zig --pkg-end --pkg-begin uri /Users/kubkon/dev/gyro/libs/zig-uri/uri.zig --pkg-end --pkg-begin network /Users/kubkon/dev/gyro/libs/zig-network/network.zig --pkg-end --pkg-begin iguanaTLS /Users/kubkon/dev/gyro/libs/iguanaTLS/src/main.zig --pkg-end --pkg-end --pkg-begin uri /Users/kubkon/dev/gyro/libs/zig-uri/uri.zig --pkg-end --pkg-begin known-folders /Users/kubkon/dev/gyro/libs/known-folders/known-folders.zig --pkg-end --enable-cache
error: the following build command failed with exit code 6:
/Users/kubkon/dev/gyro/zig-cache/o/172a1fe7ff10fcd8e871d0e48dd4b8bb/build /opt/zig2/bin/zig /Users/kubkon/dev/gyro /Users/kubkon/dev/gyro/zig-cache /Users/kubkon/.cache/zig -Dbootstrap
```

I should also point out that if you install bootstrapped zig from our tarballs, everything is just fine.

Any ideas anyone? @andrewrk?

---

Oh wait, is that #6830 perhaps?

**Comment by mikdusan** [comment]
I believe this problem reduces to (when macos host):
```sh
zig build-obj hello.c --verbose-cc -target native-native-musl
```

gyro sets abi to `musl` for every platform except windows:
```zig
    if (target.abi == null) {
        target.abi = switch (std.builtin.os.tag) {
            .windows => .gnu,
            else => .musl,
        };
    }
```

@ifreund mentioned this on IRC:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/48141240/119872742-ce272600-bef1-11eb-95b7-16160da1a95d.png">

so we have a case here where:
1. musl is being targeted on macos host
2. musl is built upon the linux syscall layer, thus it does not support macos
3. using bootstrap `zig+llvm+lld+clang-x86_64-macos-gnu-0.8.0-dev.2168+2d1196773` is much older behaviour that still used macos system libc so all was ok
4. using master this is no longer the case. It now attempts to build musl and eventually clang gets invoked with `-target x86_64-unknown-macosx-musl` which causes failure of `.s` .section directives that don't apply to macosx

Going forward, it would be nice if we could error on an invalid target combination like that to stop us from going down the rabbit hole unnecessarily.

And gyro will have to update and set musl only on linux.

**Comment by ifreund** [comment]
> And gyro will have to update and set musl only on linux.

I don't think gyro should set the target abi in general. Maybe this makes sense as a special case for windows though, I don't have much experience with that.
```zig
    if (std.builtin.os.tag == .windows and target.abi == null) {
        target.abi = .gnu;
    }
```

**Comment by kubkon** [comment]
That's some great debug report, thanks so much @mikdusan!

**Comment by kubkon** [comment]
Summoning @mattnite to the discussion which seems an issue with `gyro` rather than the compiler. Closing however if the issue resurfaces for somebody when building a different project, please feel free to reopen.

**Comment by mattnite** [comment]
Thanks for root causing this @mikdusan! I wrote that abi code way back and I thought that musl just worked on macos because my builds were successful, I'm going to get rid of that bit of code and let the user decide what target.

**Comment by mattnite** [comment]
lmao definitely was from when I had C dependencies and wanted a static binary, I don't even have to change my release build scripts, thanks again guys!
