### ISSUE TITLE
ignore setrlimit error in start.zig until Zig calculates stack size

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#8927]
It looks like WSL1 only supports up to 8 MB stacks.  On linux, Before a Zig program calls main, it will check the requested stack size located in the ELF file is supported and will panic if it doesn't.  I agree this is a good behavior, however, currently all Zig programs get the same default stack size until Zig implements logic to detect the real upper bound on the program's stack size.  This default stack size was recently moved up from 8 MB to 16 MB because there are one or more tools that require 16 MB.  I propose that Zig change the default back to 8 MB to accommodate WSL1 (and potentially low memory systems) and provide an opt in feature to increase the size when necessary (is this a linker flag?). 

Along with this, I'd also propose that Zig provide a mechanism to disable this "stack" check.  Possibly with a pub symbol in the "root" module.  The reason a program may want to do this is if there are multiple code paths in the same program that require drastically different stack sizes.  One practical example I can think of might be a tool like "busybox" that could set the stack size based on the command it is currently emulating.

**Comment by marler8997** [comment]
Andrew has said the solution he's going with is to make the "setrlimit" error in `start.zig` a silent error, until Zig implements proper stack upper bound calculation.  I'm ok with this solution as it frees Zig from any responsibility and puts the issue back on WSL if it wants to be able to execute programs that requires larger stacks.  I'll consider this issue closed once the change to `start.zig` to ignore the error on `setrlimit` is in.

**Comment by andrewrk** [comment]
33a779c7f65b9eb5115253bfe1cf4f4ea86336af
