### ISSUE TITLE
zig ld: ability to link tbds on macOS 

### ISSUE THREAD

**Issue by kubkon** [ziglang/zig#8935]
Currently, `zig ld` can successfully link object files `.o`, static libraries `.a`, and (limited to no re-exports) dynamic libraries `.dylib`. However, starting with macOS 11 aka BigSur, no actual system dynamic libraries are available for browsing on the filesystem (well, they are available _somewhere_ in the `dyld`'s global cache). Instead, the linker is supposed to use the so-called text-based definition files `.tbd`s which are compact representation of the symbol tables found within the actual dynamic library and its re-exports. `zig ld` cannot link `tbd`s yet and they are required if anyone wants to build stage2 with Homebrew's Zig and/or LLVM since LLVM is built with system `libxml2` (which is only available as a `tbd` on recent macOS).

**Comment by kubkon** [comment]
Hmm, I might try adding some prelim support for this for 0.8.0. If I made it before we cut the release, we'd have a fully functional Zig binary available via Homebrew.

**Comment by mikdusan** [comment]
some background that may help...

- docs from latest `tapi-1100.0.11` library: [here](https://opensource.apple.com/source/tapi/tapi-1100.0.11/docs/TBD.rst.auto.html)
- when tbd appeared:

version | SDK | note
:-:|---|---
4 | 11.0 | Big Sur
3 | 10.13 | High Sierra, ~4 years ago
2 | 10.12 | Sierra, ~ 5 years ago
1 | 10.10 | Yosemite, ~7 years ago

- and this indication that tapi-12.0.23 is [coming](https://opensource.apple.com/release/developer-tools-120.html):

<img width="655" alt="image" src="https://user-images.githubusercontent.com/48141240/120077654-761b2b80-c079-11eb-8e96-3629febb35d0.png">

**Comment by mikdusan** [comment]
Looking distantly into the future, perhaps .tbd files could be used by zig linkers for other formats to cross-link; it feels like a better solution than hacking stub .so files.

**Comment by kubkon** [comment]
Since there's quite a bit of work involved in adding this in including a yaml parser, I'm moving this into 0.9.0 milestone.
