### ISSUE TITLE
Passing -1 to c_short argument of extern function fails on FreeBSD

### ISSUE THREAD

**Issue by 17dec** [ziglang/zig#8947]
This happens on FreeBSD 13.0-RELEASE amd64 with the Zig 0.8.0-dev.2707+322215bf0 binaries from the site.

t.zig:
```zig
const std = @import("std");
const c = @cImport(@cInclude("curses.h"));

pub fn main() !void {
    const va = c.initscr();
    const vb = c.start_color();
    const vc = c.use_default_colors();
    const vd = c.init_pair(2, -1, -1);
    try std.io.getStdOut().writer().print("{} {} {} {}\n", .{ va == null, vb, vc, vd });
    _ = c.endwin();
}
```

The equivalent in C:
```c
#include <stdio.h>
#include <curses.h>

int main(int argc, char **argv) {
    WINDOW *va = initscr();
    int vb = start_color();
    int vc = use_default_colors();
    int vd = init_pair(2, -1, -1);
    printf("%s %d %d %d\n", va == NULL ? "true" : "false", vb, vc, vd);
    endwin();
    return 0;
}
```

```
$ zig run t.zig -lc -lncursesw
false 0 0 -1
$ zig cc t.c -o t -lncursesw && ./t
false 0 0 0
```

translate-c is picking up the correct prototype:
```
$ zig translate-c /usr/include/curses.h |grep 'init_pair('
pub extern fn init_pair(c_short, c_short, c_short) c_int;
$ zig cc -E /usr/include/curses.h |grep 'init_pair ('
extern int init_pair (short,short,short);
```

The C & Zig code give the same output on Linux amd64. Passing positive values to `init_pair()` also works as expected. I suspect Zig is generating the wrong code when calling an extern function with a negative c_short argument, but I couldn't find an easy function in libc to test with.

**Comment by mikdusan** [comment]
llvm-ir for the `init_pair` call from `t.zig`:
```llvm
; callsite
%12 = call i32 @init_pair(i16 2, i16 -1, i16 -1)
; ...
declare i32 @init_pair(i16, i16, i16) #2
```

and for `t.c`:
```llvm
; callsite
%13 = call i32 @init_pair(i16 signext 2, i16 signext -1, i16 signext -1)
; ...
declare dso_local i32 @init_pair(i16 signext, i16 signext, i16 signext) #1
```

summary:
- for `.zig` files zig does not add `signext` attr at callsite or decl on freebsd or other platforms (I checked linux, openbsd and dragonfly)
- unsure why other platforms do not manifest like freebsd, maybe a subtle calling convention or PIC thing?
- for `.c` files the embedded clang and external clang DOES add `signext`

conclusion:
- perhaps we should emit `signext` attribute for i16 params?

**Comment by Vexu** [comment]
Zig now properly emits zero/signext attributes for parameters:
```llvm
; Function Attrs: nounwind
declare i32 @foo(i16 signext) #1
```
