### ISSUE TITLE
Entry Point Not Found GetSystemTimePreciseAsFileTime KERNEL32.dll Windows 7

### ISSUE THREAD

**Issue by RodrigoDornelles** [ziglang/zig#8951]
this error occurs  in windows 7 32bits SP1, zig 0.7.1 i386.

**Comment by fsb4000** [comment]
I found this: https://github.com/ziglang/zig/issues/5766

>Windows 7 is no longer supported; as seen in the Support Table the minimum windows version is 8.1.

**Comment by RodrigoDornelles** [comment]
thanks, issue closed for duplicity 👍  🇧🇷
