### ISSUE TITLE
Linking error when building file on Windows profile with non-ascii characters

### ISSUE THREAD

**Issue by Daimanta** [ziglang/zig#8957]
I found the following issue when building any Zig file on Windows with a profile with non-ascii characters.

**Setup:**

- Run Windows 10(untested with previous versions)
- Create a profile/user with a non ASCII-character in the user name (I used the name "Ján", note that the 'á' is one codepoint)
- Trigger the build of a file by using e.g. zig run of any Zig file

**Expected behavior**: The file(s) in question should be built normally. When creating an exe, I would expect a created exe file.

**Actual behavior**:
Using the example specified above, I get the following error messages

```
lld-link: error: could not open 'C:\Users\jßn\AppData\Local\zig\o\921a737f5a80bcf7cae42c6fd4704916\hello.obj': unspecified system_category error
lld-link: error: could not open 'C:\Users\jßn\AppData\Local\zig\o\641123592962cacbf9b36ae0f3ffc936\c.lib': unspecified system_category error
lld-link: error: could not open 'C:\Users\jßn\AppData\Local\zig\o\a77d0cfe06eed435eeebccb9aab6c1e6\compiler_rt.lib': unspecified system_category error
lld-link: error: could not open 'C:\Users\jßn\AppData\Local\zig\o\1ddbdd374d1d2d3d0109d89f344a9049\kernel32.lib': unspecified system_category error
lld-link: error: could not open 'C:\Users\jßn\AppData\Local\zig\o\beb354e7115149569e94473afbb07973\ntdll.lib': unspecified system_category error
 ```

**Possible cause**:
It seems clear that certain files could not be found in the linker stage. The cause of that is likely that due to an (encoding?) issue, the folder "C:\Users\ján" is not accessed and the linker tries to access "C:\Users\jßn" instead. The targeted folder is incorrect and might potentially cause other issues if the other folder actually existed, although this is unlikely.

**Possible approach**: The linker should use the right encoding to access the user folder.

**Comment by mrakh** [comment]
Interesting. The Windows-1252 encoding for ‘á’, is  the same as the CP437 encoding for ‘ß’ (0xE1). But AFAIK, only the Windows console still uses CP437, and it has to be in legacy mode.

Are you directly pasting “C:\Users\jßn” into your the command prompt when doing the build? If so, what happens when you try it in PowerShell?

**Comment by Daimanta** [comment]
I checked on my Windows 10 machine. When starting the command prompt I use 'cmd'. For powershell I use 'powershell'. Powershell appears to have exactly the same issue, the error messages are fully equal.

**Comment by Daimanta** [comment]
I checked the encoding. My cmd shell indicates that it uses CP850. Checking the code page, 0xE1 is indeed ‘ß’.

**Comment by mrakh** [comment]
Is it fixed when you run `chcp 1252` before running your build?

**Comment by Daimanta** [comment]
I had hoped so. Unfortunately, this did not work (in cmd)and I got a similar but slightly different error message.

```
lld-link: error: could not open 'C:\Users\ján\AppData\Local\zig\o\641123592962cacbf9b36ae0f3ffc936\c.lib': unspecified system_category error
lld-link: error: could not open 'C:\Users\ján\AppData\Local\zig\o\a77d0cfe06eed435eeebccb9aab6c1e6\compiler_rt.lib': unspecified system_category error
lld-link: error: could not open 'C:\Users\ján\AppData\Local\zig\o\1ddbdd374d1d2d3d0109d89f344a9049\kernel32.lib': unspecified system_category error
lld-link: error: could not open 'C:\Users\ján\AppData\Local\zig\o\beb354e7115149569e94473afbb07973\ntdll.lib': unspecified system_category error
error: LLDReportedFailure
```

I notice that the correct character is shown, namely 'á', but the message is the same except for an additional LLDReportedFailure. Copy-pasting any of these folders in explorer results in navigation to the correct folder.

**Comment by alluLinger** [comment]
same error to me
```
lld-link: error: could not open 'C:\Users\xiao\Desktop\测试\zig-cache\o\d2abec2453346d90baebae42ce0f5808\build.obj': unspecified system_category error
error: LLDReportedFailure
```

**Comment by squeek502** [comment]
Fixed by https://github.com/ziglang/zig/pull/13131
