### ISSUE TITLE
zig cc illegal instruction on mac osx

### ISSUE THREAD

**Issue by RodrigoDornelles** [ziglang/zig#8966]
I have a project written in C, and I'm doing some experiments in zig, but when I use the zig compiler I get the error "illegal instruction" when created.

 * This only happens on mac osx, (windows runs normaly).
 * occurs using any of the optimization flags `-O0` `-O1` `-O2` `-O3`.
 * When compiled only in clang this problem does not occurs.
 * issue related: <https://github.com/RodrigoDornelles/3bc-lang/issues/107>

**Comment by Vexu** [comment]
Does passing `-fno-sanitize=undefined` fix this? https://github.com/ziglang/zig/wiki/FAQ#why-do-i-get-illegal-instruction-when-using-with-zig-cc-to-build-c-code

**Comment by RodrigoDornelles** [comment]
alright with the `-fsanitize=undefined` flag ran normally without any problem warnings, but could it have been a false positive?

**Comment by g-w1** [comment]
From the [UBSAN docs](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html):

> UndefinedBehaviorSanitizer is not expected to produce false positives. If you see one, look again; most likely it is a true positive!
