### ISSUE TITLE
proposal: run stage2 astgen when using stage1

### ISSUE THREAD

**Issue by g-w1** [ziglang/zig#8970]
Stage2 has some desirable features that are missing in stage1 in astgen (and I plan to add more like unused variables). This proposal is to run astgen unconditionally on any zig file that is being compiled, c++ or zig implementation.
Pros:
catch more errors earlier
Cons:
a tiny bit slower

**Comment by mikdusan** [comment]
What happens if astgen produces errors that are redundant to those produced by stage1?

**Comment by g-w1** [comment]
Astgen will run first, and if there are any errors, stage1 will abort. This can be hooked into stage1's @import command trivially I think.

**Comment by g-w1** [comment]
This is implemented by https://github.com/ziglang/zig/pull/9191

**Comment by andrewrk** [comment]
Ah thanks, I forgot you filed this.

**Comment by andrewrk** [comment]
Uh it's not merged yet tho

**Comment by andrewrk** [comment]
Landed in 31c49ad64ded02b9dde57f5d3ef102a771fa5cf7.
