### ISSUE TITLE
LLVM error while building for embedded ARM

### ISSUE THREAD

**Issue by rbino** [ziglang/zig#8972]
Hi,
I have [a project](https://github.com/rbino/zig-stm32-blink.git) which was building correctly with Zig version `0.8.0-dev.1981+fbda9991f`.

Today I upgraded Zig to the latest dev version (`0.8.0-dev.2721+c6a0a4e72`) and if I try to build the same project it fails with:
```
<inline asm>:14:2: error: predicated instructions must be in IT block
 movne r0, r2
 ^
<inline asm>:15:2: error: predicated instructions must be in IT block
 addeq r1, #16
 ^
<inline asm>:18:2: error: predicated instructions must be in IT block
 movne r0, r2
 ^
<inline asm>:19:2: error: predicated instructions must be in IT block
 addeq r1, #8
 ^
<inline asm>:22:2: error: predicated instructions must be in IT block
 movne r0, r2
 ^
<inline asm>:23:2: error: predicated instructions must be in IT block
 addeq r1, #4
 ^
<inline asm>:26:2: error: predicated instructions must be in IT block
 movne r0, r2
 ^
<inline asm>:27:2: error: predicated instructions must be in IT block
 addeq r1, #2
 ^
LLVM ERROR: Error parsing inline asm
```

Let me know if there's a way to access old builds so I can help pinpoint where the error was introduced.

**Comment by g-w1** [comment]
Please tell the full target that you are building for, I think I might know where this was introduced.

**Comment by rbino** [comment]
@g-w1 the full target is this:
```
    // Target STM32F407VG
    const target = .{
        .cpu_arch = std.Target.Cpu.Arch.arm,
        .cpu_model = .{ .explicit = &std.Target.arm.cpu.cortex_m4 },
        .os_tag = std.Target.Os.Tag.freestanding,
        .abi = std.Target.Abi.eabihf,
    };
```

**Comment by phicore** [comment]
Interesting, I thought Thumbs targets were not fully supported, but seeing your project it seems you had quite some success with it. 

I'm was looking to try with cortex M0+ (RP2040) but was pretty sure it would not work because it only supports a subset of Thumb-1 ISA

**Comment by LemonBoy** [comment]
Fixed that for you, that's an M-class chip and as such cannot execute ARM code.
```zig
    const target = .{
        .cpu_arch = std.Target.Cpu.Arch.thumb,
        .cpu_model = .{ .explicit = &std.Target.arm.cpu.cortex_m4 },
        .os_tag = std.Target.Os.Tag.freestanding,
        .abi = std.Target.Abi.eabihf,
    };
```

**Comment by rbino** [comment]
@LemonBoy thanks, that indeed fixes the problem.
So actually the fact that was working before was a bug? Or just a coincidence?

**Comment by LemonBoy** [comment]
> So actually the fact that was working before was a bug? Or just a coincidence?

The latter, I've recently added some more code to correctly handle the ARM/Thumb split by checking the target triple and the feature flags. What's the best representation for the two targets is still an open question, either by dropping the `thumb` target and requiring the `+thumb_mode` flag or by making illegal to specify `arm` as target if the chip is thumb-only.

**Comment by rbino** [comment]
Thanks for the explanation, I assume the representation of arm vs thumb will be tracked in a separate issue, so I'll close this one
