### ISSUE TITLE
Ability to add named files

### ISSUE THREAD

**Issue by N00byEdge** [ziglang/zig#8976]
There is currently a mechanic for importing files **_within the same package_** by name, but I think it's restricted to only the root file (`@import("root")`). I'd like a way to specify in build.zig or similar more of these, so that I can move files within the package without having to change every single import of it, or having to change the number of `..`s in all the import path when I move a source file.

Right now, we have to create a single object which contains everything we would like to reference:
https://github.com/FlorenceOS/Florence/blob/d554fba1dab988f63f8b229dc7b52ac683c4d20b/src/os.zig
This object is then referenced from a single relative path in the root file
```
pub const os = @import("../os.zig");
```

Then we can reference this from other files

```
const os = @import("root").os;
const paging = os.memory.paging;
const vmm    = os.memory.vmm;
// ...
```

It would be a lot nicer if we could reference the files the same way you can reference packages:
```
const paging = @import("paging");
const vmm    = @import("vmm");
```
After declaring their locations in a place like build.zig:
```
// exe.addPackagePath("paging", "src/memory/vmm.zig"); // Doesn't work, makes the name reference another package
exe.addNamedFile("paging", "src/memory/vmm.zig");
```

**Comment by codic12** [comment]
This leads to ambiguity; how do you know if paging is src/paging.zig, src/memory/paging.zig, src/memory/bump_allocator/paging_implementation/paging.zig just by looking at the code? I believe that just using the file paths is the best way, and it's not much of a hassle anyways.

**Comment by N00byEdge** [comment]
> I believe that just using the file paths is the best way
Problem with that is that results in quadratic complexity of moving files

**Comment by SpexGuy** [comment]
This could be accomplished through build_options.zig, like we do with `@embedFile`.

**Comment by andrewrk** [comment]
Thanks for the clear proposal. I'm rejecting it because the use case is handled adequately by the mechanism that you outlined. It's also my belief that the quadratic complexity of moving files is not really a big problem that needs solved.
