### ISSUE TITLE
Multiline string with backticks

### ISSUE THREAD

**Issue by DominicTobias-b1** [ziglang/zig#8985]
Hey, this language seems great. Just wondering if there were good reasons for the multiline syntax as it looks less pleasant than backticks:

```zig
const payload =
    \\{
    \\    "vals": {
    \\        "testing": 1,
    \\        "production": 42
    \\    },
    \\    "uptime": 9999
    \\}
;
```

Javascript:

```js
const uptime = 9999;
const payload = `
    {
        "vals": {
            "testing": 1,
            "production": 42
        },
        "uptime": ${uptime}
    }
`;
```

Anyway closing as not an issue just throwing it out there ;)

**Comment by SpexGuy** [comment]
One of the primary reasons for our choice of this syntax is that it means the tokenizer is stateless.  It can start at the beginning of any line and tokenize it, without needing to worry about whether that line is in the middle of a multiline string.

**Comment by DominicTobias-b1** [comment]
Cool thanks I thought a good reason was likely

**Comment by andrewrk** [comment]
Duplicate of #162 which is locked for commentary
