### ISSUE TITLE
Proposal: Create separate namespace for translate-c helpers

### ISSUE THREAD

**Issue by ehaas** [ziglang/zig#8994]
Right now `std/meta.zig` contains several "This is for translate-c and is not intended for general use." functions. I propose moving them into a separate file such as `std/c/translate_c.zig`, since they don't really fit with what the other `meta.zig` functions are doing. `meta.zig` can be updated to import from the new location so that existing translated code doesn't break.

**Comment by xackus** [comment]
Maybe `std/special/translate_c.zig`?

**Comment by andrewrk** [comment]
> Maybe `std/special/translate_c.zig`?

The special folder is not for this purpose; it is only for compiler_rt and freestanding libc. If anything, now that std/ is inside a lib/ directory, we should remove the special folder and put these files outside std/, in compiler_rt/ and zlibc/.

`std.c` is already used for the namespace of calling into libc functions, so I think that probably should not collide with this, although it would be OK to use 1 name for a sub-namespace.

Some suggestions for the namespace:
 * `std.zig.translate_c`
 * `std.c.translate`
 * `std.c.translation_helpers`

What do you suggest, @ehaas?

**Comment by ehaas** [comment]
Not polluting the `std.c` namespace sounds good to me; how about `std.zig.translation_helpers`? Purely because it's easier to tab-complete to that filename in my editor since there are already 4 files named `translate_c.zig` :) But I don't have a really strong opinion on it; `std.zig.translate_c` also works for me.

**Comment by andrewrk** [comment]
Counter proposal: `std.zig.c_translation`. Reasoning:
 * in this context we need the "c"
 * "helpers" is always a smell; all API is "helpers"
