### ISSUE TITLE
[0.8.0] zig.exe APPCRASH on Win 10 1909 (exception: c000001d)

### ISSUE THREAD

**Issue by OscarL** [ziglang/zig#8995]
I've downloaded `zig-windows-x86_64-0.8.0.zip`, unzipped it to a RAMDrive, executed `R:\zig.exe -h`, got an APPCRASH, with exception: c000001d.

Just in case, verified the sha256 for the .zip file. It was downloaded OK.

Tried unzipping on a regular HDD in case there was some incompatibility with the RAMDrive... got the same resulting crash from the standard HDD.

This is on Win10 1909.

I've got the info for the crash from "Report.wer" file that Windows created after the crash.

Edit: just in case it might help a bit... A "-dev" build I've downloaded around March 20 was working OK on the same system (Sorry for not providing an exact version... as a dumb-dumb, I've deleted that copy BEFORE testing the 0.8.0 release :-( )

**Comment by charlieman** [comment]
I just downloaded it and it worked fine, I'm using Windows 10 Pro, Version 20H2. Have you tried downloading the current master version?

**Comment by mikdusan** [comment]
what model CPU you have? That exception might mean illegal-instruction.

**Comment by OscarL** [comment]
@mikdusan: Athlon II X2 260. Supported instructions set as reported by CPU-Z: MMX(+), 3DNow!(+), SSE, SSE2, SSE3, SSE4A, x86-64, AMD-V.

@charlieman: I didn't, as the release was just hours ago, but I'll try that now, and report back.

**Comment by OscarL** [comment]
Well, downloaded `zig-windows-x86_64-0.8.0-dev.2749+167754b31.zip`, and executing `R:\zig-windows-x86_64-0.8.0-dev.2749+167754b31\zig.exe -h` worked OK, as did `zig run hello.zig` using the code from [here](https://ziglang.org/documentation/master/#toc-Hello-World).

**Comment by andrewrk** [comment]
For 0.8.0, I switched all the x86_64 tarballs to use [x86_64_v2](https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels). My understanding was that pretty much everyone was using CPUs which support these instruction sets, but it's starting to look like that understanding is wrong.

For 0.8.1 and beyond I think our binary x86_64 tarballs will go back to being baseline.

**Comment by mikdusan** [comment]
@OscarL,

So here's what happened. Our release builds raised the minimum bar of `x86_64` CPU features from baseline to what gcc/clang are now calling `x86_64_v2`:

```
x86-64: CMOV, CMPXCHG8B, FPU, FXSR, MMX, FXSR, SCE, SSE, SSE2
x86-64-v2: (close to Nehalem) CMPXCHG16B, LAHF-SAHF, POPCNT, SSE3, SSE4.1, SSE4.2, SSSE3
x86-64-v3: (close to Haswell) AVX, AVX2, BMI1, BMI2, F16C, FMA, LZCNT, MOVBE, XSAVE
x86-64-v4: AVX512F, AVX512BW, AVX512CD, AVX512DQ, AVX512VL
```

`v2` is too new for your CPU. But wait, there's good news. Just grab the latest download tarballs (now showing as version 0.9.0) and they are built with x86_64 baseline and should work with your CPU.

If it works, please let us know!

**Comment by OscarL** [comment]
@mikdusan: as mentioned [here](https://github.com/ziglang/zig/issues/8995#issuecomment-855193960), I've already downloaded a build from master (zig-windows-x86_64-0.8.0-dev.2749+167754b31.zip) and reported back that it worked OK on my system! :-)

Thanks for the explanation.

@andrewrk: Thanks! Life in poor countries means we tend to cling on any hardware we can get, no matter how old :-D

**Comment by andrewrk** [comment]
I will close the issue, since there is nothing to be done in this repository. I think it will be OK to let this issue slip through the cracks and rely on people finding this issue if they need a workaround. The problem will be completely gone soon enough. I apologize for the time in between.
