### ISSUE TITLE
Support libc++ on the target wasm32-wasi-musl

### ISSUE THREAD

**Issue by vi** [ziglang/zig#9044]
```
$ zig version
0.8.0
$ cat hello.cpp
#include <iostream>

int main() {
    std::cout << "HW\n";
    return 0;
}
$ zig c++ -target wasm32-wasi-musl  -Os hello.cpp -o hello.wasm
In file included from /opt/zig-linux-x86_64-0.8.0/lib/libcxx/src/filesystem/operations.cpp:18:
/opt/zig-linux-x86_64-0.8.0/lib/libcxx/src/filesystem/filesystem_common.h:443:9: error: no member named 'utimes' in the global namespace
  if (::utimes(p.c_str(), ConvertedTS) == -1) {
      ~~^
/opt/zig-linux-x86_64-0.8.0/lib/libcxx/src/filesystem/operations.cpp:531:9: error: no member named 'fchmod' in the global namespace
  if (::fchmod(fd.fd, st.st_mode) == -1) {
      ~~^
/opt/zig-linux-x86_64-0.8.0/lib/libcxx/src/filesystem/operations.cpp:632:12: error: no member named 'realpath' in the global namespace
    hold(::realpath(p.c_str(), nullptr), &::free);
         ~~^
/opt/zig-linux-x86_64-0.8.0/lib/libcxx/src/filesystem/operations.cpp:1178:9: error: no member named 'fchmodat' in the global namespace
  if (::fchmodat(AT_FDCWD, p.c_str(), real_perms, flags) == -1) {
      ~~^
In file included from /opt/zig-linux-x86_64-0.8.0/lib/libcxx/src/filesystem/directory_iterator.cpp:20:
/opt/zig-linux-x86_64-0.8.0/lib/libcxx/src/filesystem/filesystem_common.h:443:9: error: no member named 'utimes' in the global namespace
  if (::utimes(p.c_str(), ConvertedTS) == -1) {
      ~~^
/opt/zig-linux-x86_64-0.8.0/lib/libcxx/src/filesystem/directory_iterator.cpp:45:8: error: use of undeclared identifier 'DT_SOCK'
  case DT_SOCK:
       ^
4 errors generated.37/42] algorithm.cpp...
```

**Comment by vi** [comment]
Also some diagnostic messages like `4 errors generated.` seem to be printed after bash prints its prompt:

```
$
$
$ 4 errors generated.

$
$
```

**Comment by andrewrk** [comment]
This is blocking on libc++ upstream supporting this target.

**Comment by vi** [comment]
Should attempt to use `zig c++` for targets that are not supported by `libc++` be detected and warned against earlier?

What if `libc++` compilation accidentally succeeds for an unsupported target, but produces invalid code?

**Comment by andrewrk** [comment]
> Should attempt to use `zig c++` for targets that are not supported by `libc++` be detected and warned against earlier?

This is a feature proposal that you are welcome to make a case for. 

> What if `libc++` compilation accidentally succeeds for an unsupported target, but produces invalid code?

Do you have any examples if this actually happening?

**Comment by vi** [comment]
>> What if libc++ compilation accidentally succeeds for an unsupported target, but produces invalid code?
> Do you have any examples of this actually happening?

No, this is just theoretical musings.

But it's not that hard to contrive such scenario.

> This is a feature proposal that you are welcome to make a case for.

What is better architecturally: if Zig contains the list of supported targets for libc++ (and other similar libraries) and checks against it prior to attempting to comile; or if libc++ code itself checks various ifdefs and warns if it is attempted on unsupported configuration?
