### ISSUE TITLE
missing compile error for modification of comptime value in runtime branch

### ISSUE THREAD

**Issue by tgschultz** [ziglang/zig#906]
```
fn valGetMax(comptime T: type) usize {
    var t = @typeId(T);
    
    var s = switch(t) {
        builtin.TypeId.Float => 32,
        else => @maxValue(T),
    };
    
    return s;
}


test "type" {
    var x = valGetMax(i32);
    x = valGetMax(f64);
}
```

```
TODO analyze_min_max_value float
```

I imagine other builtins will have the same problem.

**Comment by tgschultz** [comment]
I'm adding this here as I'm pretty sure it's the same problem manifesting in a different way.

In the code below, the problem disappears if If I do the check directly instead of calling `isSliceType`, however in the original code, where this check is always a few function calls deep, it doesn't seem to matter.
```
const std = @import("std");
const builtin = @import("builtin");
const debug = std.debug;

fn isSliceType(comptime T: type) bool {
    if (@typeId(T) == builtin.TypeId.Pointer) {
        if (@typeInfo(T).Pointer.size == builtin.TypeInfo.Pointer.Size.Slice) {
            return true;
        }
    }
    return false;
}

fn countSliceMembers(inp: var) usize {
    comptime var count = usize(0);
    const type_info = @typeInfo(@typeOf(inp));
    
    inline for (type_info.Struct.fields) |field_info| {
        const FieldType = field_info.field_type;
        if (isSliceType(FieldType)) count += 1;
    }
    return count;
} 

test "incorrectly caching... something" {
    const String = []const u8;
    const Number = u32;
    
    const S = struct {
        string: String,
        number: Number,
    };
    
    debug.assert(isSliceType(String) == true);
    debug.assert(isSliceType(Number) == false);
    
    var s = S{ .string = "", .number = 10, };
    debug.assert(countSliceMembers(s) == 1);
}
```
```
Test 1/1 incorrectly caching result of function...assertion failure
Unable to dump stack trace: Unable to open debug info: TodoSupportCoffDebugInfo
```

**Comment by andrewrk** [comment]
Note the original code is fixed if you use `const` instead of `var`:

```
fn valGetMax(comptime T: type) usize {
    const t = @typeId(T);
    
    const s = switch(t) {
        builtin.TypeId.Float => 32,
        else => @maxValue(T),
    };
    
    return s;
}


test "type" {
    var x = valGetMax(i32);
    x = valGetMax(f64);
}
```

**Comment by andrewrk** [comment]
The first example is not actually a bug - it's working as designed. When you use `var`, the `switch` is evaluated at runtime (or at least before the optimizer gets to it). So `@maxValue(f64)` has to be analyzed in the second call to `valGetMax`. (Let me see about finishing up that TODO for max value though).

Also I'll have a look at your second example.

**Comment by tgschultz** [comment]
The second example is probably the same when you drill down into it, due to taking `var` instead of `type` in `countSliceMembers`.

At the time, I probably did this as a convenience so the caller wouldn't need to pass `@typeOf(x)`. While that would be nice, I think it would also probably be anti-zen in that it obfuscates what's happening.

Something to consider from this though is that it is somewhat difficult to reason about without a good working knowledge of how comptime behaves.

**Comment by tgschultz** [comment]
The unclarity in this case came from not understanding comptime well enough to see how the implementation was failing. I was aware that @maxValue didn't work on floats, but I couldn't interpret why that code would even be encountered. In my mind, the fact that `T` is a comptime argument meant that the compiler should generate different values for `@typeId(T)`, and since the switch was applied to `@typeId(T)` it would be evaluated at comptime.

Now that I have written a lot more comptime code I think I can see the problem when you point it out, but a month or two ago I don't know if I would have. Maybe I have had an especially bad mental model for comptime and my experience is not indicative of the average programmer, though.

**Comment by andrewrk** [comment]
For the second test case -

`count` is a comptime var. This means that every store to count must be a comptime known value, and every load from count must be to a comptime value. However, the expression `isSliceType(FieldType)` is a runtime known value, and so when we do `if (isSliceType(FieldType)) count += 1`, there's a load and store with a comptime value *inside a runtime branch*.

This is unsound, so there should be a compile error for it, but there is not. In other words we need to do `count += 1` at comptime, but we're actually doing it at runtime. That should be impossible.

It actually fixes the test case if you remove `comptime` from `var count = usize(0)`.

So this is a great test case for a new compile error that zig needs to have.

**Comment by andrewrk** [comment]
I thought about this some more and I think this is also working as designed. The `count += 1` instructs the compiler to do a compile time variable modification, which Zig is doing. This can be useful in other places, even in runtime branches. For example, auto hash:

https://github.com/ziglang/zig/blob/bc88ef2dc331733e69ed895b7a815ba0a6996dc3/std/hash_map.zig#L445-L502

**Comment by tgschultz** [comment]
The results still don't make sense to me. If you change S to
```
const S = struct {
    number: Number,
    num2: Number,
};
```

It no longer has any slice members. `isSliceType(FieldType)` should resolve to `false` no matter how the loop is unrolled or what order the fields are evaluated in. Yet if we warn on the result of `countSliceMembers()` instead of asserting we will find that it is always equal to the number of members in S. 

At the very least I think my statement that this behavior is difficult to reason about is accurate.

**Comment by andrewrk** [comment]
> At the very least I think my statement that this behavior is difficult to reason about is accurate.

I'll definitely agree with you there.



> It no longer has any slice members. isSliceType(FieldType) should resolve to false no matter how the loop is unrolled or what order the fields are evaluated in. Yet if we warn on the result of countSliceMembers() instead of asserting we will find that it is always equal to the number of members in S.

This happens because, just like with `@compileLog`, the compile-time side effects happen when the block is analyzed. When the if statement has a runtime condition, both the then and the else blocks are analyzed for every iteration of the inlined while loop. However when the if statement has a comptime condition, only one of (then block, else block) is analyzed.

**Comment by tgschultz** [comment]
```
pub fn enumFromName(comptime EnumType: type, comptime name: []const u8) EnumType {
    const info = @typeInfo(EnumType);
    for(info.Enum.fields) |field| {
        if(std.mem.eql(u8, field.name, name)) {
            return @intToEnum(EnumType, @intCast(@TagType(EnumType), field.value));
        }
    }
    @compileError(@typeName(EnumType) ++ " has no member named " ++ name);
    unreachable;
}

test "enumFromName"
{
    const E = enum(u32)
    {
        One,
        Two,
        Three,
    };
    
    debug.assert(E.Two == enumFromName(E, "Two"));
}
```

Additional case where this behavior leads to confusion. If `name` is not `comptime`, this works as expected, but with comptime the compile error is evaluated and thrown regardless of the name.

**Comment by andrewrk** [comment]
when I removed `comptime` in the above example, I got `error: unable to evaluate constant expression`

**Comment by tgschultz** [comment]
Sorry, you also have to comment out the compile error line because it contains a reference to `name`.

Only it turns out if you just remove the reference to name you still get the compiler error, so I'm 0/2 today.

**Comment by andrewrk** [comment]
No worries. I'll leave this open until I triage 0.4.0 and if we come up with any ideas on how this situation can be improved we can talk about it.

**Comment by nektro** [comment]
I believe the above example is able to reach the `@compileError` because the loop is `for` rather than `inline for` which causes the loop to be executed at runtime and thus `@compileError` is reachable.
