### ISSUE TITLE
Linux "Wrong types for attribute" LLVM Module error with specific extern fn parameters

### ISSUE THREAD

**Issue by JonSnowbd** [ziglang/zig#9061]
This has been a real weird one to dig up. Given an extern function with a very specific parameter, the following error appears

```
broken LLVM module found: Wrong types for attribute: inalloca nest noalias nocapture nonnull readnone readonly signext zeroext byref(double) byval(double) preallocated(double) sret(double) align 1 dereferenceable(1) dereferenceable_or_null(1)
```

This was the result for two specific c lib externs across two libraries, one in raylib:

`RAYGUIDEF bool GuiButton(Rectangle bounds, const char *text);`

and one in cimgui:

`pub extern fn igTextColored(col: ImVec4, fmt: [*c]const u8, ...) void;`

Both ImVec4 and Rectangle are the same struct with the same layout.

It disappears when I add an additional struct member, so it seems to be specifically any extern fn with parameters
`(4x4 byte struct, [*c]const u8)`

This does not occur on windows, and only on linux. Provided below is the bare minimum to encounter this error

[WeirdIssue.zip](https://github.com/ziglang/zig/files/6628491/WeirdIssue.zip)

**Comment by rcorre** [comment]
For future searchers, this also happens with raylib's `UpdateTextureRec(Texture2D texture, Rectangle rec, const void *pixels)`, and the fix in 0.9.0 seems to work! :tada:
