### ISSUE TITLE
[ENHANCEMENT] allow specify a name and options on test parametes

### ISSUE THREAD

**Issue by cindRoberta** [ziglang/zig#9075]
further a description, a test needs a name to execute unit tests, could have 2 alternatives:
```zig
test test_name("test with a name", timeout: ...) {}
```
or
```zig
test (name: test_name, "test with a name", timeout: ...) {}
```
in terminal:
```
# zig test file.zig -t test_name other_test
```

**Comment by g-w1** [comment]
Why is this better than --test-filter, and please describe timeout. Why does a test have to have 2 names?

**Comment by cindRoberta** [comment]
> Why is this better than --test-filter, and please describe timeout. Why does a test have to have 2 names?

--test-filter allows filter only 1 test

**Comment by cindRoberta** [comment]
@g-w1 timeout utility: https://tutorial.ponylang.io/testing/ponytest.html#long-tests

**Comment by g-w1** [comment]
> Simple tests run within a single function. When that function exits, either returning or raising an error, the test is complete. This is not viable for tests that need to use actors.

Not sure why you would want this? Do you have a use case? Zig does not have actors so it's tests would be simple tests and not have a timeout.
