### ISSUE TITLE
std.build.Builder.setPreferredReleaseMode ignores input value (always uses Debug)

### ISSUE THREAD

**Issue by jeffkdev** [ziglang/zig#9078]
std.build.Builder.setPreferredReleaseMode ignores input value (always uses Debug). Example:

build.zig
```zig
const std = @import("std");
pub fn build(b: *std.build.Builder) anyerror!void {
    b.setPreferredReleaseMode(.ReleaseFast);
    const mode = b.standardReleaseOptions();
    var exe = b.addExecutable("hello", "hello.zig");
    exe.setBuildMode(mode);
    const run_cmd = exe.run();
    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);
    b.default_step.dependOn(&exe.step);
    b.installArtifact(exe);
}
```

hello.zig (file doesn't matter)
```zig
const std = @import("std");
pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    try stdout.print("Hello, {s}!\n", .{"world"});
}

```
Generates a command string without -OReleaseFast
`zig.exe build-exe [truncated]\src\hello.zig --cache-dir [truncated]\src\zig-cache --global-cache-dir [truncated]\Local\zig --name hello --enable-cache `
Also the generated builtin.zig has the mode still as debug:
```zig
pub const mode = std.builtin.Mode.Debug;
```

However, if I manually set the release mode it works as expected:
```zig
const std = @import("std");
pub fn build(b: *std.build.Builder) anyerror!void {
    //b.setPreferredReleaseMode(.ReleaseFast);
    b.release_mode = .ReleaseFast;
    b.is_release = true;
    const mode = b.standardReleaseOptions();
    var exe = b.addExecutable("hello", "hello.zig");
    exe.setBuildMode(mode);
    const run_cmd = exe.run();
    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);
    b.default_step.dependOn(&exe.step);
    b.installArtifact(exe);
}
```
Command:
`zig.exe build-exe [truncated]\src\hello.zig -OReleaseFast --cache-dir [truncated]\src\zig-cache --global-cache-dir [truncated]\Local\zig --name hello --enable-cache`

generated builtin.zig
```zig
pub const mode = std.builtin.Mode.ReleaseFast;
```

OS: Windows 10
Zig version: 0.9.0-dev.70+a3f7a48d9, built from source

**Comment by SpexGuy** [comment]
This is intentional.  `setPreferredReleaseMode` adds an option `-Drelease` which can be specified on the command line to use the preferred release mode.
https://github.com/ziglang/zig/blob/master/lib/std/build.zig#L640
