### ISSUE TITLE
'OVERLAPPED_ENTRY' not defined

### ISSUE THREAD

**Issue by codehz** [ziglang/zig#9079]
https://github.com/ziglang/zig/blob/master/lib/std/os/windows.zig#L401
But I cannot found the definition of OVERLAPPED_ENTRY

std\os\windows.zig:401:32: error: use of undeclared identifier 'OVERLAPPED_ENTRY'

**Comment by ehaas** [comment]
Looks like [this struct](https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-overlapped_entry) needs to be added to `lib/std/os/windows/bits.zig`
