### ISSUE TITLE
Zig binary releases for `windows-aarch64`?

### ISSUE THREAD

**Issue by alexrp** [ziglang/zig#9102]
Hi there,

Are there plans to ship Zig binaries for `windows-aarch64`?

Some context for why I'm asking: I'm currently messing around with a project to integrate Zig into MSBuild. The idea is to make it trivial to write Zig, C, and C++ libraries to be consumed by .NET applications in a way that the process feels 'native' to that ecosystem and requires zero fiddling around with setting up native toolchains.

Right now, the build process for my custom MSBuild SDK is fetching all the binaries from ziglang.org and embedding them in the final NuGet package so that, whichever platform people use the SDK on, a Zig compiler comes included and it Just Works. The only issue is that Zig binaries on ziglang.org are available for all platforms that the .NET SDK can build on except for `windows-aarch64`.

**Comment by kubkon** [comment]
I think we would like to support it, but lack the resources to focus on this right now. Would you be willing to look into `windows-aarch64` support?

**Comment by alexrp** [comment]
I'll see if I can find time for it at some point when I finish this current project.

That said, I'm not at all familiar with how Zig releases are built for 'exotic' platforms like this that people rarely build code on. Are these releases cross-compiled or built on VMs?

**Comment by leroycep** [comment]
I went ahead and tried building zig for `aarch64-windows-gnu` from Linux using [zig-bootstrap](https://github.com/ziglang/zig-bootstrap), however it ran into some errors while compiling stage1 (I think?) for aarch64.

**Comment by andrewrk** [comment]
Zig 0.9.0 releases on Monday, December 20th and it will have an aarch64-windows .zip file.
