### ISSUE TITLE
Startup code for wWinMain is broken

### ISSUE THREAD

**Issue by 0x6D7A6B** [ziglang/zig#9104]
Trying to build a program using wWinMain as it's main function fails and gives this error:
```
./zig/lib/std/start.zig:490:37: error: expected type '*std.os.windows.bits.HINSTANCE', found '(null)'
    return root.wWinMain(hInstance, null, lpCmdLine, nCmdShow);
```
Example code:
```
const win32 = @import("std").os.windows;

pub fn wWinMain(Instance: win32.HINSTANCE, PrevInstance: win32.HINSTANCE, CmdLine: win32.PWSTR, ShowCode: i32) callconv(win32.WINAPI) i32 {
    return 0;
}
```

**Comment by Vexu** [comment]
From: https://docs.microsoft.com/en-us/windows/win32/learnwin32/winmain--the-application-entry-point

> * hPrevInstance has no meaning. It was used in 16-bit Windows, but is now always zero.

Meaning you need to declare `PrevInstance` as `?win32.HINSTANCE`.

**Comment by 0x6D7A6B** [comment]
Looks like I have either missed it or forgotten about it already which was never an issue in C. I guess I'll have to be more careful reading the documentation the next time.
