### ISSUE TITLE
std.net.tcpConnectToHost() on Windows may return WSANOTINITIALISED

### ISSUE THREAD

**Issue by wtrmute** [ziglang/zig#9115]
Hello, I've been writing a few simple applications in Zig to familiarise myself with the standard library, so I attempted to write a simple application which connects to a stream socket. Unfortunately, trying to connect with `std.net.tcpConnectToHost()` in Windows 10 returned a `error.Unexpected` referencing the error "the application did not call WSAStartup() or WSAStartup() failed" (`WSANOTINITIALISED`).

The error trace shows that `std.net.tcpConnectToHost()` calls `std.net.getAddressList()` and that calls (in my case) `std.os.windows.ws2_32.getaddrinfo()` in line 727 of `std/net.zig` which itself returns `WSANOTINITIALISED`.

The problem seems to be fixed by inserting a few lines of code starting on line 736 of `std/net.zig` to this effect:

```zig
.WSANOTINITIALISED => {
    result.arena.deinit();
    // call os.windows.WSAStartup() and try again
    _ = try os.windows.WSAStartup(2, 2);
    return getAddressList(allocator, name, port);
},
```

I did not make this into a PR because it probably ignores all sorts of problems like throwing away the result of `WSAStartup()`, not bothering with locking or unlocking before calling that function, not having a plan for calling `WSACleanup()`, and probably still leaking other memory I have failed to notice had been initialised elsewhere in the function. Regardless, the code is in here in case it is useful.

Cheers for the attention, and congratulations for having developed such an awesome systems language.

**Comment by LemonBoy** [comment]
#8943

**Comment by wtrmute** [comment]
I'm sorry; I looked for issues with `tcpConnectToHost` and `WSANOTINITIALISED`, but did not look for `getAddressList` or `WSAStartup`. Thank you for pointing me to the correct issue.
