### ISSUE TITLE
error return traces don't work in libraries (.a or .so)

### ISSUE THREAD

**Issue by ityonemo** [ziglang/zig#9116]
when error return trace inspecting code is invoked from compiled zig library, it causes a panic.

for linux, it appears to fail in `std.debug.lookupModuleDl` function call.

minimal example:

https://github.com/ityonemo/zig-minimal-stacktrace-panic

**Comment by LemonBoy** [comment]
#4524
Link against libc to solve this problem.

**Comment by ityonemo** [comment]
aha thank you!
