### ISSUE TITLE
CLOCK_REALTIME is undeclared identifier in std/os.zig on Windows

### ISSUE THREAD

**Issue by samhattangady** [ziglang/zig#9121]
I am trying to use `std.os.clock_gettime` method on windows, and I get the following error:

```
C:\...\zig-windows-x86_64-0.9.0-dev.137+86ebd4b97\lib\zig\std\os.zig:4664:23: error: use of undeclared identifier 'CLOCK_REALTIME'
        if (clk_id == CLOCK_REALTIME) {
```

I am on windows OS, using zig version `0.9.0-dev.137+86ebd4b97`.

It appears that other OSs initialise this in `std/os/bits.zog`, but not windows.

Thanks.

**Comment by LemonBoy** [comment]
`clock_gettime` is not available on Windows, check out if the methods in `std.Time` provide what you need.

**Comment by nektro** [comment]
cc #6600

this should probably be closed
