### ISSUE TITLE
Windows native-native-gnu can't find odbc32.lib

### ISSUE THREAD

**Issue by mjoerussell** [ziglang/zig#9124]
Not sure if this is an issue with Zig or something else that Zig is depending on, but I've noticed some issues in 0.8/master regarding using and linking to `odbc32.lib` on Windows. I've also tested on macos with master and found no issues.

I've confirmed that none of the below issues are present on Zig `0.8.0-dev.2305+d228d8605`.

1. Importing C macro `__MSABI_LONG(x)` no longer works. I mentioned in the original issue #9120 and was shown a fix that seems to work, but I'm still curious why it broke in the new release.
2. The following C `#define`'s are no longer present:
    * SQL_OV_ODBC3_80
    * SQL_CP_DRIVER_AWARE
    * SQL_PARAM_DATA_AVAILABLE
3. The most pressing issue - I'm unable to link against `odbc32.lib`. 

If I try to build a project which links against `odbc32.lib` in Zig version `0.9.0-dev.140+4173a2bc2`, I get the following error:

```
error(link): DLL import library for -lodbc32 not found
error: DllImportLibraryNotFound
zdb...The following command exited with error code 1:
C:\Users\mjoer\Code\zig\build-release\bin\zig.exe build-exe C:\Users\mjoer\Code\zdb\src\main.zig -lc -lodbc32 --cache-dir C:\Users\mjoer\Code\zdb\zig-cache --global-cache-dir C:\Users\mjoer\AppData\Local\zig --name zdb --pkg-begin odbc C:\Users\mjoer\Code\zdb\zig-odbc\src\lib.zig --pkg-end --enable-cache
error: the following build command failed with exit code 1:
C:\Users\mjoer\Code\zdb\zig-cache\o\7d4fee359512fdc30a31bf8e390544fb\build.exe C:\Users\mjoer\Code\zig\build-release\bin\zig.exe C:\Users\mjoer\Code\zdb C:\Users\mjoer\Code\zdb\zig-cache C:\Users\mjoer\AppData\Local\zig 
run
```

The same code running on Zig `0.8.0-dev.2305+d228d8605` links with no issues, on the exact same Windows configuration.

**Comment by xackus** [comment]
This is probably why: #6565. Try setting the target to `native-native-msvc`.

**Comment by mjoerussell** [comment]
I think I'm still missing something, once I specify that then the `@cImport` starts failing.

When I import this: 

```zig
@cImport({
    @cDefine("__MSABI_LONG(x)", "(long)(x)");
    @cInclude("windows.h");
    @cInclude("sql.h");
    @cInclude("sqltypes.h");
    @cInclude("sqlext.h");
})
```

Then it can't seem to find the header files. Whichever one is listed first will be shown in the error message, so for example:

```
.\zig-odbc\src\c.zig:4:5: error: C import failed
    @cImport({
    ^
.\zig-cache\o\c7cfe15038263b66e244a7a456675868\cimport.h:2:10: note: 'windows.h' file not found
#include <windows.h>
```

**Comment by mjoerussell** [comment]
Looks like this is the same issue as this: #9093

**Comment by mjoerussell** [comment]
Just tested on Windows `native-native-gnu` and this is working again. Closing this issue.
