### ISSUE TITLE
Possibly missing macos headers: objc/objc-runtime.h

### ISSUE THREAD

**Issue by kkartaltepe** [ziglang/zig#9127]
When trying to cross compile (from zig 8.0, on linux) a tool It was including `<objc/objc-runtime.h>` which does not appear the in the libc includes for x86_64-macos-gnu. Supposedly this header simply includes `<objc/runtime.h>` and <`objc/messages.h>`. Zig does contain `runtime.h` but doesnt appear to have `messages.h`.

I checked master it doesnt appear that any objc headers have been added since 8.0 so this seems still valid.

Im not very familiar with macos so im not sure if these simply fall outside of what zig supports. And I dont have a macos machine to inspect further. But let me know if there is any more information I can provide.

**Comment by kkartaltepe** [comment]
It looks like i just missed `messages.h` as it was in the cross architecture location. However the combined `objc-runtime.h` is missing. Patching the code to use messages.h and runtime.h compiled.

**Comment by nektro** [comment]
https://github.com/opensource-apple/objc4/blob/master/runtime/objc-runtime.h#L2
https://github.com/opensource-apple/objc4/blob/master/runtime/message.h

https://github.com/ziglang/fetch-them-macos-headers/blob/main/src/headers.c#L157

are you sure the `s` isn't a typo?

**Comment by nektro** [comment]
https://github.com/ziglang/zig/blob/master/lib/libc/include/any-macos-any/objc/message.h

this file is indeed shipped with Zig

**Comment by kkartaltepe** [comment]
The missing header is `<objc/objc-runtime.h>`

**Comment by nektro** [comment]
Ah, my misread.

cc @kubkon it appears that the file was not being picked up by https://github.com/ziglang/fetch-them-macos-headers

https://github.com/opensource-apple/objc4 seems to be the source here.

**Comment by nektro** [comment]
```
~ % ll /System/Volumes/Data/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc
total 296
Mar 16 01:44 List.h
Mar 16 01:44 NSObjCRuntime.h
Mar 16 06:52 NSObject.h
Mar 16 06:52 Object.h
Mar 16 01:44 ObjectiveC.apinotes
Mar 16 06:52 Protocol.h
Mar 16 01:44 hashtable.h
Mar 16 06:52 hashtable2.h
Mar 16 06:52 message.h
Mar 16 01:44 module.modulemap
Mar 16 06:52 objc-api.h
Mar 16 06:52 objc-auto.h
Mar 16 01:44 objc-class.h
Mar 16 06:52 objc-exception.h
Mar 16 01:44 objc-load.h
Mar 16 01:44 objc-runtime.h
Mar 16 06:52 objc-sync.h
Mar 16 06:52 objc.h
Mar 16 06:52 runtime.h
```

**Comment by andrewrk** [comment]
=> https://github.com/ziglang/zig/issues/9395#issuecomment-979510281
