### ISSUE TITLE
Return type of constant assigned to a generic function is not checked

### ISSUE THREAD

**Issue by Reconcyl** [ziglang/zig#9135]
Example of issue (simplified by @leecannon in the Discord):

```zig
fn f(a: anytype) usize {
    return a;
}

const wrong: fn(anytype) void = f;

pub fn main() void {
    @import("std").debug.print("{}\n", .{wrong(42)});
}
```

What I expected: a type error when `wrong` is used, indicating that its return type is incompatible with the return type of `f`. Instead, the program compiles and prints `42`.

**Comment by Vexu** [comment]
Fixed by #6997
