### ISSUE TITLE
Zig requires some syscalls not available on older kernels

### ISSUE THREAD

**Issue by lancethepants** [ziglang/zig#9146]
So I am working on an embedded linux system that unfortunately I can't upgrade the kernel.  When compiling ziglang for this platform on final link I run into two syscalls that are required but are too new for my device.

getrandom requires linux >= 3.17
copy_file_range requires linux >= 4.5

```
/opt/tomatoware/arm-soft-mmc/lib/gcc/arm-tomatoware-linux-uclibcgnueabi/10.3.0/../../../../arm-tomatoware-linux-uclibcgnueabi/bin/ld: zig1.o: in function `std.crypto.tlcsprng.fillWithOsEntropy':
zig1:(.text+0x78cb0): undefined reference to `getrandom'
/opt/tomatoware/arm-soft-mmc/lib/gcc/arm-tomatoware-linux-uclibcgnueabi/10.3.0/../../../../arm-tomatoware-linux-uclibcgnueabi/bin/ld: zig1.o: in function `std.os.copy_file_range':
zig1:(.text+0xae290): undefined reference to `copy_file_range'
collect2: error: ld returned 1 exit status
```
getrandom I think is pretty easy to workaround.
copy_file_range I thought when looking at the source had a runtime check for availability, but doesn't look like a compile-time check.

**Comment by jedisct1** [comment]
Glad to see you here, @lancethepants , this is a small world :)

**Comment by lancethepants** [comment]
@jedisct1 Yes, it is a small world, crazy!

I'm not sure the getrandom half of this issue was addressed yet.

**Comment by jedisct1** [comment]
The problem here is not really older kernels. We fall back to using `/dev/urandom` when `getrandom()` returns `ENOSYS`. It's `getrandom()` missing from the C library.

In fact, it took forever for C libraries to add a `getrandom()` function after the system call was introduced.

The `getrandom()` function does nothing but directly call the system call. So we don't really need to depend on it.

**Comment by jedisct1** [comment]
@lancethepants Can you check if #9226 fixes it for you?

**Comment by lancethepants** [comment]
Will pursue getting getrandom in uclibc-ng.
