### ISSUE TITLE
[packaging] how to run tests for zig compiled with cmake?

### ISSUE THREAD

**Issue by epsilon-0** [ziglang/zig#9149]
Hi,
  I'm the package maintainer of zig for gentoo and I was wondering how to run tests for zig.
Generally in OS packages the tests are run **before** the package is installed, so when I try to do that with the zig binary, it gives out an error saying installation directory not found:
```
$ ./zig test $srcdir/test/tests.zig
error: unable to find zig installation directory: FileNotFound
```

I am unsure how to navigate around this, so any help would be nice.
Cheers!

**Comment by andrewrk** [comment]
The default cmake configuration will install to the build directory, in which you can then run the tests with `./zig build test`.

How much of the test suite do you want to run? `./zig build test` will run them all, taking potentially hours. On the other side of the spectrum, you could run a smoke test that would take ~10 seconds.

**Comment by andrewrk** [comment]
Feel free to ask for help in any of these places: https://github.com/ziglang/zig/wiki/Community

It doesn't seem there is any problem to be solved in the ziglang/zig repo.

**Comment by epsilon-0** [comment]
Sounds good!
Thanks a lot for the pointers, I will ask more there.

This isn't run by users, only on gentoo servers to confirm package sanity, so we will run the full tests.
