### ISSUE TITLE
translate-c: enum constants can have incorrect type

### ISSUE THREAD

**Issue by ehaas** [ziglang/zig#9153]
The following code translates incorrectly due to the underlying int type of an enum type being different from the int type of an enum constant (in the below C code, a variable of type `foo` would have an underlying representation of `unsigned`, but the enum constant `bar` has type `int`).  In the translated Zig code, `bar` has type `c_uint` since that is the return type of `@enumToInt(enum_foo.bar)`; it should be `c_int`

This bug was revealed (but not caused by) #8394, I believe the fix is to coerce enum redecls to the correct int type.

```C
enum foo { bar };
int main(void) {
   char c = bar;
}
```
```zig
pub const enum_foo = extern enum(c_uint) {
    bar,
    _,
};
pub const bar = @enumToInt(enum_foo.bar);
pub export fn main() c_int {
    var c: u8 = @bitCast(u8, @truncate(i8, bar));
    return 0;
}
```
```
./enums.zig:8:44: error: expected signed integer type, found 'c_uint'
    var c: u8 = @bitCast(u8, @truncate(i8, bar));
                                           ^
./enums.zig:8:30: note: referenced here
    var c: u8 = @bitCast(u8, @truncate(i8, bar));
                             ^
```

**Comment by LemonBoy** [comment]
The long-term plan was to stop translating C enumeration types into Zig's extern enum and instead emit each single value as a standalone constant of suitable type.

The idea was proposed and approved [here](https://github.com/ziglang/zig/issues/2115#issuecomment-827968279).
