### ISSUE TITLE
[UEFI, possible issue] Zero address should be valid in allocatePages boot services

### ISSUE THREAD

**Issue by davidgm94** [ziglang/zig#9157]
Hello,
I found a bug while developing an OS from scratch in UEFI, x86-64.
An ELF file generated by Zig gives some program headers whose physical address is 0.
For example, in a working OS project in C, this would work:

int pages = (phdr->p_memsz + 0x1000 - 1) / 0x1000;
Elf64_Addr segment = phdr->p_paddr;
SystemTable->BootServices->AllocatePages(AllocateAddress, EfiLoaderData, pages, &segment);

It doesn't in Zig because the function is expecting, according to its signature, a Zig pointer which cannot be zero. Nevertheless I changed the signature locally to admit "allowzero pointers" and it crashed inside the function. I am assuming zero addresses should work here, but I am not totally sure.

The current function signature in Zig is:
allocatePages: fn (AllocateType, MemoryType, usize, *[*] allowzero align(4096) u8) callconv(.C) Status

PD: Great project, I am enjoying it a lot and hope to contribute more to it!

**Comment by daurnimator** [comment]
>  I am assuming zero addresses should work here, but I am not totally sure.

Looking at the spec it seems like it depends on the `MemoryType` you use. Though I'm not sure passing `0` for any of them make sense: do you have a more fleshed out example?

**Comment by davidgm94** [comment]
An issue I made out of my ignorance. I see no problem with this nowadays. Closing...
