### ISSUE TITLE
Packed structs: Slicing an array within a packed struct causes the compiler to die without erroring

### ISSUE THREAD

**Issue by SuperAuguste** [ziglang/zig#9161]
While implementing tar files with packed structs, I realized that `std.mem.span`ing an array within a packed struct caused the compiler to die without erroring on Windows.

I further examined this phenomenon and found that the source of the error was simple: slicing an array within a packed struct in seemingly any way in the most recent versions of Zig seems to cause the compiler to exit without erroring on Windows and cause a segmentation fault / core dump on Linux.

Minimal reproduction:
```zig
const std = @import("std");

pub const UStarHeader = packed struct {
    sussy_baka: [100]u8,
};

pub fn main() anyerror!void {
    var a: UStarHeader = undefined;
    std.log.info("Amongus? {s}", .{a.sussy_baka[0..]});
}
```

**Comment by brodeuralexis** [comment]
I got the following to error out:
```zig
const std = @import("std");

// when N > 1 and N % 2 == 1
const N = 15;

pub const Struct = packed struct {
    arr: [N]f32,

    pub fn get(self: @This(), i: usize) f32 {
        return self.arr[i];
    }
};

pub fn main() anyerror!void {
    var s: Struct = undefined;

    std.log.info("{d}", .{ s.get(0) });
}
```
```sh
$ zig build-exe test.zig
./test.zig:10:25: error: unable to evaluate constant expression
        return self.arr[i];
                        ^
./test.zig:10:24: note: referenced here
        return self.arr[i];
```

**Comment by Vexu** [comment]
Arrays are no longer allowed in packed structs.
