### ISSUE TITLE
Test runner needs more flexibility regarding command line construction

### ISSUE THREAD

**Issue by alexrp** [ziglang/zig#9172]
On Windows, I'm trying to achieve something along the lines of:

```bash
wsl `wslpath zig-cache\o\...\test` <path to zig.exe>
```

I'm doing:

```bash
zig test main.zig -target x86_64-linux-gnu --test-cmd wsl --test-cmd "\`wslpath" --test-cmd-bin --test-cmd "\`"
```

This results in:

```
wsl `wslpath zig-cache\o\6a1bb5746dc889ca68f4734e672d2d84\test C:\Users\alex\scoop\apps\ziglang\current\zig.exe `
```

Which of course does not work.

This is a bit unfortunate since WSL (+ QEMU) would open up a lot of possibilities for cross-platform testing.

I'm not exactly sure what the solution might be, but it seems to me that the testing support is a bit too inflexible in general at the moment. In an ideal world, I would like to be able to say `zig build-test ...` and just get an executable I could run in whatever way makes sense for my scenario(s). I don't know how feasible that is, though.

**Comment by mikdusan** [comment]
> and just get an executable I could run

That would need a way to communicate the test pathname to caller and, well, we can already do that in a round about way:

```sh
$ test_exe=$(zig test bug0.zig --test-cmd echo --test-cmd-bin)
$ echo $test_exe
zig-cache/o/cffbbf74c9e52c1ce6c998bd999266af/test /Users/mike/project/zig/work/main/_build/zig
```

**Comment by alexrp** [comment]
That's clever, but it sorta breaks down once spaces are introduced at any level:

```console
$ export ZIG_LOCAL_CACHE_DIR="foo bar"
$ test_exe=$(zig test main.zig --test-cmd echo --test-cmd-bin)
$ echo $test_exe
foo bar\o\e8900dadff52df554ed68f06122ba377\test.exe C:\Users\alex\scoop\apps\ziglang\current\zig.exe
```

(Also doesn't work in plain old `cmd` which I unfortunately have to support...)

**Comment by alexrp** [comment]
Having looked a bit at the code, it seems like adding a `build-test` command, or at least an `-fno-exec` (?) flag to `test`, shouldn't be too hard. Would a PR for this be welcome? And if yes, which of the two would be preferable?
