### ISSUE TITLE
fmtIntSizeDec ignores formating

### ISSUE THREAD

**Issue by espindola** [ziglang/zig#9189]
The program
```
const std = @import("std");
pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    var buf: [32]u8 = undefined;
    var slice = buf[0..];
    const partial = try std.fmt.bufPrint(slice, "{}", .{std.fmt.fmtIntSizeDec(42 * 1000)});
    try stdout.print("X {s:<14} Y\n", .{partial});
    try stdout.print("X {:<14} Y\n", .{std.fmt.fmtIntSizeDec(42 * 1000)});
}
```
Prints
```
X 42kB           Y
X 42kB Y
```
From the documentation I was expecting both lines to be identical. This happens because formatSizeImpl return a struct with a function ignores the fmt argument.

andrewrk also points out that it could be renamed to remove the redundant fmt prefix.

**Comment by g-w1** [comment]
Dupe of https://github.com/ziglang/zig/issues/9184

**Comment by espindola** [comment]
oops, thanks!
