### ISSUE TITLE
compile error "local shadows declaration" only detects previous decls

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#9194]
Here is the feature working correctly:

```zig
fn foo() void {}
pub fn main() void {
    var foo = true;
    _ = foo;
}
```

```
$ ./zig ast-check test.zig
test.zig:3:9: error: local shadows declaration of 'foo'
    var foo = true;
        ^
test.zig:1:1: note: declared here
fn foo() void {}
^
```

But when we put `foo` declaration after `main`:

```zig
pub fn main() void {
    var foo = true;
    _ = foo;
}
fn foo() void {}
```

The error is missed:

```
$ ./zig ast-check test.zig
(incorrectly exits success)
```

Note that you must use ast-check to reproduce this error because stage1 catches it.

**Comment by benjcal** [comment]
@andrewrk Hello Andrew!

I wanna look into this bug but Idk even where to start looking? Do I need to get an idea of how LLVM works? Does the internal documentation for zig should be enough?

Thanks for the guidance! 😃
