### ISSUE TITLE
better haiku error handling

### ISSUE THREAD

**Issue by g-w1** [ziglang/zig#9200]
#9047 found some bugs in haiku error handling.
https://github.com/ziglang/zig/blob/d1f99eabb745a3026b4bf0486ee542d38facee8b/lib/std/Thread.zig#L519-L525
https://github.com/ziglang/zig/blob/d1f99eabb745a3026b4bf0486ee542d38facee8b/lib/std/fs.zig#L479-L486
cc @hoanga @LemonBoy 
See https://github.com/ziglang/zig/pull/9047#discussion_r648977868 and https://github.com/ziglang/zig/pull/9047#discussion_r649007701 for more details.

**Comment by hoanga** [comment]
thanks! i can try to take a look at it when i can and roll it into the changesets i have been working on.

**Comment by The-King-of-Toasters** [comment]
Both of these have been fixed. If there are no other instances I suggest closing this issue.
