### ISSUE TITLE
`zig build` ~ unable to clean 'zig-cache'

### ISSUE THREAD

**Issue by rivy** [ziglang/zig#9216]
`zig build` is using the local cache (default of 'zig-cache') for it's own execution leading to inability to clean the 'zig-cache' directory.

```shell
C:>zig version
0.8.0

C:>type b.zig
const std = @import("std");
pub fn build(b: *std.build.Builder) void {
    const clean_cache = b.addRemoveDirTree(b.cache_root);
    clean_cache.step.make() catch unreachable;
}

C:>zig build --build-file b.zig
error.Unexpected NTSTATUS=0xc0000121
...
error: the following build command failed with exit code 2147483651:
zig-cache\o\bd9e8bb2482991793722de0d4d29da3e\build.exe C:\Users\Roy\AppData\Local\scoop\apps\ziglang\0.8.0\zig.exe C:\Users\Roy\OneDrive\Projects\zig\hello-world zig-cache C:\Users\Roy\AppData\Local\zig
```

> NTSTATUS=0xc0000121 => "An attempt has been made to remove a file or directory that cannot be deleted."
> ref: [NT status code list](http://joyasystems.com/list-of-ntstatus-codes) @@ <https://archive.is/9a4qI>

If at all possible, `zig build` should use the global cache for it's execution and not hold open any links into the local cache so that the local cache can be cleaned by the build process. Storing things in the local cache would be fine, but `zig build` itself should be operating from the global cache and avoiding holding any handles into the local cache.

**Comment by nektro** [comment]
I don't believe this is a supported use case.

**Comment by marler8997** [comment]
I'd like to hear more about your use case for wanting a way to clean the local cache.

**Comment by rivy** [comment]
The use case is simply to clean the project of all build artifacts (which includes cached objects).

**Comment by nektro** [comment]
Why do you need to be able to do this \*from within build.zig itself\* when you can do `rm -r zig-*`. Zig keeps all the files it produces in a single location so that clean doesnt have to be a step. You can simply delete the folder and it will be reset.

**Comment by rivy** [comment]
`rm ...` is a non-portable construction and a break from using `zig ...` as the primary build/maintenance pattern.

`make clean` would be the obvious parallel.

**Comment by nektro** [comment]
`make clean` only makes sense as a functionality because `make` doesnt use a single cache folder and is non-trivial to clean up after. this is not with the case with Zig and so it would be superfluous to support this use case when `rm` and its analogues exist on every platform

**Comment by rivy** [comment]
It's only non-trivial to devs/users who are immersed in the use of `zig`. It's not at all apparent to a dev/user new to a project that `zig-cache` can be simply deleted. Most projects use the build mechanism to accomplish both build and clean-up, often with a help function included. It's quite possible to use the same type of idiom here with `zig` as well if only `zig` wouldn't hold onto handles within `zig-cache` while running.

`zig` seems to be aiming for portability. This is a blocker.

**Comment by nektro** [comment]
Then its an issue for the documentation, not the command line tool. Zig is not other build systems. and the fact it has `cache` in the name precludes that it contains ephemeral information.

**Comment by rivy** [comment]
> `make clean` only makes sense as a functionality because `make` doesn't use a single cache folder and is non-trivial to clean up after. this is not with the case with Zig and so it would be superfluous to support this use case when `rm` and its analogues exist on every platform

> Then its an issue for the documentation, not the command line tool. Zig is not other build systems. and the fact it has cache in the name precludes that it contains ephemeral information.

Disagree.

All builds (and clean-ups) are essentially non-trivial to the uninitiated for a given project, which leads to a search for *cross-platform tools* such as `zig` which claims "... to create a consistent development environment across all platforms." 

Depending on a specific naming scheme to prompt a developer that a given part of the project structure is ephemeral is an anti-pattern. The tool itself should encapsulate that knowledge and, when asked, clean up after itself.

Yes, I could add a portable command like `make clean` which would then *portably* use the platform specific `rm`-analogue to clean up after `zig`. But it seems ironic? to have to use another tool like this to do basic project clean up for `zig`.

**Comment by matu3ba** [comment]
Related PR #11743 enables a fix once it is clarified on how to deal with temporary artifacts from tests and once its merged.

Would be nice, if there is some input on it.

**Comment by rivy** [comment]
I appreciate that you're trying to help construct a more rigorous cache system and avoiding unneeded rebuilds is a great goal. But, again, I don't see the relevance. This issue is asking for `zig build` to not hold onto any open file handles within the local repository directory (specifically, *zig-cache*) so that all build artifacts (including temporary files) can be removed when running clean-up.

**Comment by leecannon** [comment]
But where do you expect the executable that is the build.zig to go?

**Comment by rivy** [comment]
As usual, *build.zig* would reside within the main (or 'build', or whatever) directory. It is configuration, just like a *Makefile* or *.editorconfig* or *.gitignore*. In general, clean-up removes build artifacts, not configuration.

It's not the ask here that *build.zig* (or whatever zig file used) be able to self-delete, only that it not hold onto handles in the automatically generated *zig-cache* directory so that the *zig-cache* directory can be removed. Being able to self-delete would be fine and, I guess, useful in some edge cases, but, again, not the ask.

**Comment by rivy** [comment]
@leecannon , in further puzzling over you question, it seems that you're asking about the *build.exe* which is constructed from *build.zig*, not the *build.zig* file itself. That question, I understand... 

I would say that the generated executable (and any associated generated files) should go into the global cache so that it doesn't run from the *zig-cache*. In fact, that might actually be the one handle that blocks removal. But, yes, I believe the generated build executable shouldn't be stored anywhere within the project, so that the project can be restored to a known, pristine state.

**Comment by leecannon** [comment]
What's the point of a per-project cache if the global cache has hundreds (thousands?) of project specific `build` executables for very time you have ever run `zig build` for any project where the build.zig isn't exactly the same as any prior run?

Why would a global cache contain project specific artifacts? Especially ones that are ~5mb per as each build produces both an object file and executable in debug mode with all debug symbols present.

What if I decide that I want to delete the global cache from within my build.zig, should that likewise be supported?

**Comment by rivy** [comment]
> What's the point of a per-project cache if the global cache has hundreds (thousands?) of project specific `build` executables for every time you have ever run `zig build` for any project where the build.zig isn't exactly the same as any prior run?

I don't know why the global cache would ever have hundreds or thousands of `build.exe` executables. I expect `zig` would, already likely does, manage the ephemeral global cache with an appropriate garbage collection strategy.

> Why would a global cache contain project specific artifacts?

Well, it should store whatever is needed by `zig`, project-specific or not.

> What if I decide that I want to delete the global cache from within my build.zig, should that likewise be supported?

I don't see why a *project* build process would need or want to control the global cache for `zig`.

---

If you read through this thread, you'll see that the ask here is *only* to be able to programmatically delete all build artifacts and return the project to a known pristine state. This is obviously a common development practice. *zig-cache* folders should not be left behind in user-facing locations when the tool is asked to clean up after itself.

There are lots of ways to implement that... if the executable is the actual handle holding up deletion of the local use, then, yes, use the global cache, or run from a temporary copy, or whatever. Or, if it's actually just holding a handle to something within the directory, then refactor to avoid the hold.

But, these questions don't seem to be geared toward solving the issue, rather instead, obliquely saying "I don't like this idea".

As I see you labelled as a "Contributor", you have more invested here than I do. I'm just reporting a pain point and a blocker for others who want to use `zig` as a cross-platform build tool. If you don't want to entertain the issue, then, please, close it, and I'll continue on my way.

**Comment by andrewrk** [comment]
Thanks for the proposal @rivy. I want to keep it how it is, with the local cache containing the build executable. I think this use case should be solved, if at all, at a different abstraction layer than in the build.zig script.

**Comment by rivy** [comment]
Related: <https://github.com/ziglang/zig/issues/2599>.
