### ISSUE TITLE
_ param in stage1

### ISSUE THREAD

**Issue by g-w1** [ziglang/zig#9220]
In stage2, I implemented that params named `_` do not get astgened, https://github.com/ziglang/zig/blob/31c49ad64ded02b9dde57f5d3ef102a771fa5cf7/src/AstGen.zig#L2950-L2951 so a fix for unused param would be to insert `_: T`, but this kinda works in stage1. It works for 1 param (this is due to not catching unused vars), but with multiple, it **does not notice that the name is _** and just says its shadowing.
```zig
❯ zig ast-check test.zig
/tmp via ↯ v0.9.0-dev.256+0134cb021
❯ zig run test.zig
./test.zig:4:18: error: redeclaration of variable '_'
pub fn f(_: u32, _: u32) void {}
                 ^
./test.zig:4:10: note: previous declaration is here
pub fn f(_: u32, _: u32) void {}
         ^
/tmp via ↯ v0.9.0-dev.256+0134cb021
❯ cat test.zig
pub fn main() void {
    f(1, 1);
}
pub fn f(_: u32, _: u32) void {}
```
I think this is a stage1 bug.

**Comment by jecolon** [comment]
Especially nasty when an api like fmt format routinely presents unused params scenarios like:
```
pub fn format(value: Value, comptime fmt: []const u8, options: std.fmt.FormatOptions, writer: anytype) !void {
     _ = fmt;
    _ = options;
    _ = try writer.print("foo\n", .{});
}
```

**Comment by Vexu** [comment]
Stage1 has been deleted.
