### ISSUE TITLE
proposal: yaml parser for std

### ISSUE THREAD

**Issue by tauoverpi** [ziglang/zig#9228]
Given 8216ce67895f5605d1720df4e5e6636395f2fc92 there's now a yaml parser used for self-hosted's zig ld. It would be nice if this could be included in the standard library for other uses just like `std.json`.

Also, great work on the zig ld! It's been fun to read along.

**Comment by ifreund** [comment]
That commit added a TAPI parser, not a yaml parser. It only parses a subset of yaml and will never be extended to parse anything more than is needed for TAPI afaik.

My vote is a strong [NO](https://hitchdev.com/strictyaml/why/implicit-typing-removed/) to adding a yaml parser to the std. YAML is a horribly complex and broken format, which should be avoided whenever possible. JSON in comparison is way, way simpler and much more widely used.

**Comment by tauoverpi** [comment]
Sounds fair.
