### ISSUE TITLE
new ast check makes zigwin32 model unviable

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#9234]
Using the latest zig compiler makes the zigwin32 model no longer viable. Building my zigwin32 examples use to take about 10 seconds because Zig was "lazy" and didn't need to do much with the 114 MB of binding code from zigwin32:

source: https://github.com/marlersoft/zigwin32gen/tree/main/examples
video clip: https://www.youtube.com/watch?v=HsnWZxrf5VE&t=1631s

That 10 seconds has turned into 7 minutes.  And note, this is just to build the examples which are only around 700 lines of code.  My guess is the new AST check is what's taking so long.  Adding support for parallelism will make this better, however, even with parallelism, it seems like this AST check is still taking too long.  Maybe zigwin32 needs to switch to a new model, where projects declare which bindings they need and we only generate those on the fly?  My hope though is that Zig will be able to do this AST check faster, like, 1 or 2 orders of magnitude faster.

**Comment by andrewrk** [comment]
This is a performance bug, there's an accidental O(N^2) situation here when there are many decls with the same parent. Will fix pronto!

**Comment by andrewrk** [comment]
In addition to fixing this degenerate case, the commit that resolved this issue generally improves the perf of AST Lowering.

For the std lib, that commit is: 30% wall clock speedup, 20% improvement on cache-misses, 44% fewer CPU instructions executed. On my machine "AstGen the entire std lib" now takes 29ms with a cold cache.
