### ISSUE TITLE
Top-level doc comments are missing

### ISSUE THREAD

**Issue by wooky** [ziglang/zig#9253]
As of Zig 0.8.0, top-level doc comments, i.e. lines prefixed with `//!`, are completely missing from the generated documentation.

Compare std.log:
* [master](https://ziglang.org/documentation/master/std/#std;log) - no docs
* [0.8.0](https://ziglang.org/documentation/0.8.0/std/#std;log) - no docs
* [0.7.1](https://ziglang.org/documentation/0.7.1/std/#std;log) - detailed docs

**Comment by linusg** [comment]
This appears to be fixed, https://ziglang.org/documentation/master/std/#A;std:log contains the top-level comment of `std/log.zig`:

https://github.com/ziglang/zig/blob/8ece99083f1c9af33c3240f31ab849a617547817/lib/std/log.zig#L1-L73

![image](https://github.com/ziglang/zig/assets/19366641/88d46a82-0ef6-4494-b7b8-851140bb5394)
