### ISSUE TITLE
Undefined symbols `__muldc3` and `__mulsc3` with target x86_64-linux-musl

### ISSUE THREAD

**Issue by avdv** [ziglang/zig#9259]
Hi.

I am trying to use zig as a C/C++ compiler to generate a static linux binary. I tried with 0.7.1 and 0.8.8.

When trying to link the resulting binary, I get these errors:
```
$ zig c++ -rdynamic -Wno-override-module ...  -target x86_64-linux-musl -static -lpthread -ldl -lpthread
ld.lld: error: undefined symbol: __muldc3
>>> referenced by cpow.c
>>>               /home/claudio/.cache/zig/o/38387d53b111735e4a200ab5b8f6c90b/cpow.o:(cpow) in archive /home/claudio/.cache/zig/o/b043407a9348622b8e0c1bade0fdc434/libc.a
>>> referenced by csqrt.c
>>>               /home/claudio/.cache/zig/o/607bda028751ca0ca9c59d78db576326/csqrt.o:(csqrt) in archive /home/claudio/.cache/zig/o/b043407a9348622b8e0c1bade0fdc434/libc.a
>>> did you mean: __muldf3
>>> defined in: /home/claudio/.cache/zig/o/bc3a67e1ded0b28fff239a146c03e8b8/libcompiler_rt.a

ld.lld: error: undefined symbol: __mulsc3
>>> referenced by cpowf.c
>>>               /home/claudio/.cache/zig/o/d2c56572baaee5f4193c16ffee399216/cpowf.o:(cpowf) in archive /home/claudio/.cache/zig/o/b043407a9348622b8e0c1bade0fdc434/libc.a
>>> did you mean: __mulsf3
>>> defined in: /home/claudio/.cache/zig/o/bc3a67e1ded0b28fff239a146c03e8b8/libcompiler_rt.a
```
Is this a known problem? Is there a known workaround? I'm happy to provide more details if needed.

**Comment by mikdusan** [comment]
Why are all those dynamic executable options being passed to `zig c++`? Try this:

```cpp
#include <iostream>
#include <pthread.h>

int main() {
    std::cout << "hello world" << std::endl;
    std::cout << "pthread_create: " << reinterpret_cast<void*>(pthread_create) << std::endl;
    return 0;
}
```

```sh
$ zig c++ -o hello hello.cpp -target x86_64-linux-musl
$ file ./hello
./hello: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
$ ./hello
hello world
pthread_create: 0x280814
```

**Comment by avdv** [comment]
@mikdusan Thank you! It seems removing the dynamic executable flags is the solution. Those are added by the build tool which I am using... I need to dig up how to override them.

**Comment by LemonBoy** [comment]
Don't close the ticket, the linker errors signal that we're missing two functions in our compiler-rt implementation.

**Comment by avdv** [comment]
Alright, reopened. Thought this was a user error @LemonBoy

**Comment by nektro** [comment]
Those should be opened as a separate issue.

**Comment by sagehane** [comment]
I just came across this on `0.10.0-dev.237+ada8e1713`.

```
ld.lld: error: undefined symbol: __muldc3
>>> referenced by convolution.cpp
>>>               convolution.cpp.o:((anonymous namespace)::ConvolutionState::process(unsigned long, al::span<std::array<float, 1024ul> const, 18446744073709551615ul>, al::span<std::array<float, 1024ul>, 18446744073709551615ul>)) in archive vcpkg/installed/x64-linux/lib/libopenal.a
>>> referenced by convolution.cpp
>>>               convolution.cpp.o:((anonymous namespace)::ConvolutionState::process(unsigned long, al::span<std::array<float, 1024ul> const, 18446744073709551615ul>, al::span<std::array<float, 1024ul>, 18446744073709551615ul>)) in archive vcpkg/installed/x64-linux/lib/libopenal.a
>>> referenced by alcomplex.cpp
>>>               alcomplex.cpp.o:(complex_fft(al::span<std::complex<double>, 18446744073709551615ul>, double)) in archive vcpkg/installed/x64-linux/lib/libopenal.a
>>> referenced 1 more times
```

I was - and still am - trying to compile a fairly large C++ project, and I don't really know how to reproduce a minimal example.
Do tell me if I should try to reproduce it, because I don't intend to make the effort otherwise.

**Comment by mikdusan** [comment]
Without having access to the project, I am guessing the following link is related, and if so, perhaps multiplying two complex will trigger a call to `__muldc3` for a nice reduction:

https://stackoverflow.com/questions/49438158/why-is-muldc3-called-when-two-stdcomplex-are-multiplied

**Comment by dantecatalfamo** [comment]
I just ran into this issue while compiling [mruby](https://github.com/mruby/mruby) with `rake CC='zig cc'`

**Comment by enderger** [comment]
Also occurs when compiling the s7 scheme implementation (https://ccrma.stanford.edu/software/snd/snd/s7.html)
