### ISSUE TITLE
add `zig objcopy` subcommand as a drop-in binutils objcopy replacement

### ISSUE THREAD

**Issue by Ristovski** [ziglang/zig#9261]
As part of #7917: it would be nice if `zig` had a subcommand for executing `objcopy`.
Mainly, this would allow us to run `objcopy --strip-all` (`--strip-debug` still produces a binary that reads `not stripped`) for any target that Zig supports, to strip binaries (and more!) (see #351).

I propose `zig objcopy`, which could maybe also be internally used by `--strip` (not sure what the status of #351 is, seems to still be an issue)

**Comment by andrewrk** [comment]
This is blessed, with one caveat - I'd like to see this command implemented in Zig rather than by exposing llvm-objcopy.

We already have plenty of ELF handling capabilities, and even some build system support for related features as objcopy: https://github.com/ziglang/zig/blob/6d47b4f39e8cdd95ead71b1efdbf67a737174e97/lib/std/build/InstallRawStep.zig

**Comment by 0-x-2-2** [comment]
Are there any plans for exposing `llvm-objcopy` in zig toolchain or the pure zig reimplementation. We use binutils objcopy / llvm objcopy to strip and copy debug symbols into another file then link the debug file to the ELF file.

**Comment by andrewrk** [comment]
Update: I started working on this locally, but I have no visible progress to share yet.

**Comment by andrewrk** [comment]
I've opened a pull request that adds the `objcopy` subcommand: #13916

Those who are interested in this feature, can you please share the command that you are wanting to run, and make note of what target is the input file? We can have separate issues for each objcopy enhancement.

**Comment by leibupro** [comment]
> Just a note that objcopy does not support ARM64 file format while llvm-objcopy does. So this change moved away from cross compatibility. We have to rely on llvm binary for now.

Noticed the same for `*.elf` files targeted to `thumb-freestanding` (32 bit ARM). Does not work with `zig objcopy` but does with `llvm-objcopy`.
