### ISSUE TITLE
Problem: Scope-Based assignment only allows const-preservation of a single value.

### ISSUE THREAD

**Issue by moosichu** [ziglang/zig#9281]
Problem: You cannot express the following idea semantically:

```zig
const a : *SomeType = undefined;
const b: *SomeOther = undefined;
if(a) {
    x = b;
    y = c;
} else {
    x = d;
    y = e;
}
```

So there are two potential solutions to this problem - either supporting this construct directly with CFA analysis, or probably more preferable, supporting some kind of multiple assignment/struct unpacking (which might be more zig-like?), not sure about syntax though:

```zig
const a, const b = result: {
    if(a) {
         return .{ b, c };
    } else {
        return .{d, e};
    }
}

```

Although - that doesn't really matter - the problem is one of code-hygiene management - there is currently now way in zig to assign to two or more const values conditionally & not have the outer-scope polluted with an extra variable of some form (at best).

## Justification

So why does this matter? Code-hygiene is important for programming because it allows the programmer to limit the number of variables & values they have to juggle in their head when reasoning about some code. So whilst probably the current best solution you could have for this problem right now is assigning to an anonymous struct and then assigning-out to the const values from its fields - it does mean that you now have a struct variable floating around that isn't really doing anything, so whilst it's a minor overhead - it still exists.

**Comment by Vexu** [comment]
Duplicate of #498?
Also this is already possible using structs:
```zig
const val = if(a)
    .{ .a = @as(u8, 1), .b = @as(u32, 2) }
else
    .{ .a = @as(u8, 3), .b = @as(u32, 4) };
_ = val.a * val.b;
```

**Comment by moosichu** [comment]
Yes and no on it being a duplicate - the linked issue is a potential solution to the described problem, but there could be other ones (such as tuple/struct unpacking) so I wanted to confirm that others agree that this is a problem worth solving - so that any particular solution can justify itself.

So - hopefully the issue description explains why assigning to a struct is not holly desirable - there are cases where it is undesirable to have pack two otherwise unrelated variables together to the same struct just because their assignment conditions.

**Comment by InKryption** [comment]
If this could be solved, that would be great. Working with C APIs that return multiple values via output parameters can cause a lot of unsightly `var`s that could be const, and silly anonymous structs from block returns, especially using something like the Vulkan API.
Also,
> ```
> const a, const b = result: {
>     if(a) {
>          return .{ b, c };
>     } else {
>         return .{d, e};
>     }
> }
> ```
I think, given the use-case of something like this, since it's for code hygiene (aka, making more things const more cleanly), it may be fine to limit a solution like that to something like `const a, b = blk: {...}`, since if we wanted to mix `var` and `const`, we could just seperate their declarations, and have the `var` variable defined/mutated within the block that returns the `const` variable's value. Whether or not `var a,b` has a valid use-case is then debatable.

**Comment by dbandstra** [comment]
This whole issue may not be a dupe of #498, but the multiple assignment/tuple unpacking proposal has already been discussed there (e.g. https://github.com/ziglang/zig/issues/498#issuecomment-440521357) as well as in #3897. I think it would be better to continue discussion in #498, to avoid retreading old ground. 

I agree the TypeScript-esque CFA alternative sounds un-Zig-like. Compiler complexity, language spec complexity, readability cognitive load.

**Comment by moosichu** [comment]
Yeah - good point, I'm convinced.
