### ISSUE TITLE
Proposal: `zig ast-patch` subcommand to help auto-fix errors like `"unused \w+"`

### ISSUE THREAD

**Issue by Jarred-Sumner** [ziglang/zig#9282]
For a codebase that is now 46,514 lines of Zig, upgrading to the latest version of Zig will be painful due to errors like these:

```zig
src/resolver/resolve_path.zig:30:9: error: unused local variable
    var last_common_separator_is_at_end = false;
        ^
src/resolver/resolve_path.zig:358:11: error: unused local constant
    const strs = [_][]const u8{
          ^
src/resolver/resolve_path.zig:661:9: error: unused local variable
    var parts = _parts;
        ^
src/resolver/resolve_path.zig:752:24: error: unused loop index capture
    for (parts) |part, i| {
                       ^
```

This class of error, while useful, will sometimes reduce developer productivity. One idea to help make changes like these easier going forward: codemod that generates a `.patch` to auto-fix errors like these. 

This doesn't mean errors can be ignored. The developer still needs to review the diff and approve the changes.

But, the tedious -- and potentially bug-introducing work -- of deleting unused symbols can be left to tooling that won't accidentally delete the wrong line.

One approach to addressing this: a new subcommand `zig ast-patch`

```zig
src/resolver/resolve_path.zig:30:9: error: unused local variable
    var last_common_separator_is_at_end = false;
        ^
src/resolver/resolve_path.zig:358:11: error: unused local constant
    const strs = [_][]const u8{
          ^
src/resolver/resolve_path.zig:661:9: error: unused local variable
    var parts = _parts;
        ^
src/resolver/resolve_path.zig:752:24: error: unused loop index capture
    for (parts) |part, i| {
                       ^

Auto-patch 4 errors with:
zig ast-patch --unused src/resolver/resolve_path.zig:30:9,358:11,661:9,752:24
```

The scope of work would be something like:
- Append a copy-pastable command to the end of `zig build` errors that will only modify code related to the specific errors. That way, it doesn't change anything unexpected. It should be a little smaller than a full file path for each error, which is why in the example above it has comma separated `line:column` values rather than separate paths. Skipping that may hide build errors by filling up the terminal
- subcommand which uses errors produced by the code for `zig ast-check` to print a `.patch` file for the selected `line:column` ranges of the file paths passed in. From there, it would shell out to one of the many `patch` CLIs to allow the developer to interactively or non-interactively apply the patch. That way, `zig ast-patch` doesn't have to deal with any UI for accepting/rejecting a patch.

A new subcommand like `zig ast-patch` would make it easier to introduce backwards-incompatible changes  `zig fmt` can't/shouldn't auto-fix

**Comment by Vexu** [comment]
The compiler doesn't know what the code is intended to do so any fix it would come up with (at least without way more effort than what would be in scope) would likely be wrong and hide bugs, or worse introduce new ones. And while generating a patch could prevent this the only way to actually force developers to pay attention to fixing the issues is to make them fix them manually.

Furthermore Zig is not intended to have any large breaking changes post 1.0 so this tool would only really be useful for a limited time.
