### ISSUE TITLE
nightly: invalid "unused function parameter" on functions corresponding to parameter types

### ISSUE THREAD

**Issue by slimsag** [ziglang/zig#9296]
I recently noticed Zig nightly (stage1) fails to compile some of my code that works in the latest stable release:

```
/Users/slimsag/Desktop/hexops/zorex/src/dsl/compiler.zig:214:131: error: unused function parameter
            fn mapTo(in: Result(?Compilation), compiler_context: *CompilerContext, _allocator: *mem.Allocator, key: ParserPosKey, path: ParserPath) callconv(.Async) Error!?Result(?Compilation) {
                                                                                                                                  ^
...
```

Some are legitimate, but many are functions that are to be passed as parameters with a specific function signature type. So in the above function implementation, `path` is indeed not used - but it's passed as a parameter to a function that requires `path` be an argument: https://github.com/hexops/zorex/blob/70200ef3dafa74caee8d416f35c3681692b0b664/src/combn/combinator/mapto.zig#L12

I don't have a simpler reproduction yet, but you can reproduce with:

```
git clone https://github.com/hexops/zorex
cd zorex/
git checkout 70200ef3dafa74caee8d416f35c3681692b0b664
zig build test
```

**Comment by andrewrk** [comment]
This is working as designed. The intended usage here is, in the function implementation put `_ = path;` and that documents to the programming reading the code as well as the compiler that the parameter is intentionally unused.

You're not alone - others have found this annoying too. However there is no plan to change this. Let's collect some data for a few months and then reflect on this.

**Comment by slimsag** [comment]
Ah, that makes sense! I'm fine with that, thanks :)

**Comment by marler8997** [comment]
FWIW I'm also fine with `_ = path`.

**Comment by Ristovski** [comment]
Having a way to do this automatically when refactoring an older codebase would be nice.

Perhaps as a general "fix up" step in `zig fmt`? (Not sure if such capabilities for `zig fmt` have been discussed somewhere previously)
