### ISSUE TITLE
Replacement of make?

### ISSUE THREAD

**Issue by ravinder387** [ziglang/zig#9300]
if i have tons of c files and header file can i compile with zig cc?
let's suppose i hv 3 files add.h, add.c, main.c i can compile this by zig cc add.c main.c. But if have tons of file then what should i do?

**Comment by MasterQ32** [comment]
There is the (undocumented) zig build system. I recommend checking out a freshly created project with `zig init-exe`, and check out `addCSourceFiles`. You can batch all files that have the same compiler flags into the same invocation :)

**Comment by jmc-88** [comment]
There exists a bit of documentation for the Zig build system at: https://ziglang.org/documentation/master/#Zig-Build-System

Other than expanding the documentation, IMHO this is not an issue and should probably go through other support channels. See https://github.com/ziglang/zig/wiki/Community for a few links of existing communities.
