### ISSUE TITLE
About "nostdlib" like function

### ISSUE THREAD

**Issue by SergeyVolkovich99** [ziglang/zig#9312]
Hi to all.
Currently i trying to write own  exo-kernel operating system and for kernel i select zig lang, and now i seeing to something like rust`s #[no_std] like directive.
please say has, this language something similar?

**Comment by g-w1** [comment]
Zig does not need this because the stdlib is friendly to kernels and can be used inside them.

**Comment by SergeyVolkovich99** [comment]
ok that good
