### ISSUE TITLE
Proposal: Move architecture-specific information from std.builtin to @import("builtin")

### ISSUE THREAD

**Issue by Snektron** [ziglang/zig#9330]
Currently, std.builtin contains architecture-specific information about calling conventions:
https://github.com/ziglang/zig/blob/9de452f9a69d5590743a194bc2d0817d26d66a0b/lib/std/builtin.zig#L156-L172
Using architecture-specific calling conventions on the improper architecture yields a compile-error as expected. 

With relevance to #653, I believe this information should be moved to std.target, so that address space definitions (which are also architecture-specific) can also live there. Note that calling conventions share a good portion of calling conventions, so maybe this requires some `.ArchitectureSpecific: std.target.CallingConvention` variant in std.builtin.CallingConvention.

On a side note, maybe `std.builtin` and `@import("builtin")` should not have the same name.

**Comment by marler8997** [comment]
My guess is that stuff goes into the builtin module if the compiler "depends" on it.  I think the compiler avoids depending on anything in `std` other than what's in the builtin module.

**Comment by nektro** [comment]
i think `std.builtin` is for the stuff that doesn't change (ie the types of things). `builtin.zig` is generated by the compiler and saved in `zig-cache`
