### ISSUE TITLE
`-rdynamic` should probably imply `-fdll-export-fns`

### ISSUE THREAD

**Issue by alexrp** [ziglang/zig#9340]
When building C/C++ Windows executables, passing `-rdynamic` ensures that any `__declspec(dllexport)`ed symbol is exported, just like passing `-rdynamic` and using `__attribute__((visibility("default")))` does for non-Windows executables.

However, in the case of Zig code, `-rdynamic` only has the intended behavior on non-Windows platforms; when building for Windows, passing `-fdll-export-fns` is required for `export`ed symbols to actually show up in the export table.

It's worth noting that when building a DLL, `-fdll-export-fns` is implied, which of course makes sense because a DLL would not be super useful otherwise. Similarly, building an executable with `-rdynamic` is not very useful if symbols don't actually get exported. So, for consistency and to adhere to the principle of least astonishment, I think `-rdynamic` should imply `-fdll-export-fns`.

**Comment by michal-z** [comment]
I think that -rdynamic should imply -fdll-export-fns.
Currently (AFAIK) there is no way to export symbols from an .exe on Windows when using build.zig script.
To make it work I need to use: "zig build-exe -rdynamic -fdll-export-fns" as @alexrp explained to me.

In my project I have to export symbols from an .exe and use build.zig script so fixing this issue would solve my problem.
