### ISSUE TITLE
unable to find zig installation directory: FileNotFound

### ISSUE THREAD

**Issue by achempion** [ziglang/zig#9349]
Mac OS Big Sur,

zig release: `zig-macos-x86_64-0.9.0-dev.441+7b5d139fd`
shell: fish

```sh
~/p/p/l/z/h/src 🐚  which zig
/Users/achempion/bin/zig
~/p/p/l/z/h/src 🐚  zig version
0.9.0-dev.441+7b5d139fd
~/p/p/l/z/h/src 🐚  zig targets
error: unable to find zig installation directory: FileNotFound

~/p/p/l/z/h/src 🐚
```

**Comment by g-w1** [comment]
How did you install zig, and can you run `zig env`?

**Comment by achempion** [comment]
Installed the way it's described [here](https://ziglearn.org). Downloaded latest release and moved `zig` binary into the `~/bin`

```
~/p/p/l/z/h/src 🐚  zig env
error: unable to find zig installation directory: FileNotFound

```

**Comment by achempion** [comment]
ok, I figured out you need to have `lib` directory as well from the release archive next to `zig` binary

thank you
