### ISSUE TITLE
Compiler incorrectly allows shadow of non-pub decl

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#9355]
`test.zig`
```zig
const std = @import("std");

pub fn main() void {
  const x = Board(4);
  x.f();
}

fn Board(comptime dim: usize) type {
    return struct {
        const dim: u64 = @intCast(u64, dim);

        pub fn f() void {
            std.log.info("{s}", .{@typeName(@TypeOf(dim))});
        }
    };
}
```

```
$ zig run test.zig 
info: usize
```

```
$ zig version
0.9.0-dev.443+9d1fb98fa
```

**Comment by rafihayne** [comment]
Thanks @nektro for the minimal reproduction. I was asking for help in discord and got confused with this longer form which happily compiles. Maybe it's helpful

```zig
fn Board(comptime T: type, comptime dim: usize) type {
    return struct {
        board: [dim][dim]T,
        const dim = 5;
        pub fn init() @This() {
            var a: [dim][dim]T = undefined;
            return .{ .board = a };
        }
    };
}
```

**Comment by nektro** [comment]
adding `_ = @This().dim;` in the `f` function also triggers the error.

So its not catching it because the inner `dim` is otherwise impossible to reference and lazy analysis is silencing it away.

**Comment by g-w1** [comment]
I'm not sure if this is a bug `struct { const x = 1; const y = struct { const x = 2; }}` is allowed, is this different? I think the real error should be ambiguous reference. cc @SpexGuy

**Comment by SpexGuy** [comment]
Ooh, that's a fun edge case! My gut feeling is that the compiler should disallow this as an ambiguous reference.  It makes it impossible to unambiguously reference the `dim` parameter.

**Comment by g-w1** [comment]
So only if you ambiguously ref it, then its an error? If so, this should be a pretty easy (contributor friendly) fix in the `Astgen.identifier(` function which catches those.

**Comment by nektro** [comment]
update:

```zig
const std = @import("std");

pub fn main() void {
    const x = Board(4);
    x.f();
    std.debug.print("{s}\n", .{@typeName(@TypeOf(x.dim))});
}

fn Board(comptime dim: usize) type {
    return struct {
        pub const dim: u64 = @intCast(u64, dim);

        pub fn f() void {
            std.debug.print("{s}\n", .{@typeName(@TypeOf(dim))});
        }
    };
}
```

```
$ ./zig run ./test.zig 
info: u64
info: u64
```
