### ISSUE TITLE
Runtime assertion fails with `suspend;`

### ISSUE THREAD

**Issue by Pangoraw** [ziglang/zig#9367]
Hi!

Thanks for building zig!
I am trying to learn zig and came across this problem which confused me (I wrote `suspend;` instead of `suspend {}`).

This file:
```zig
pub fn main() void {
  suspend;
}
```
hits the following assertion and fails:
https://github.com/ziglang/zig/blob/3063f0a5ed373947badd0af056db310283c76e37/src/AstGen.zig#L971
Which was added by this commit https://github.com/ziglang/zig/commit/15e891823e34ad57ccc5f1636323c5b7e718d44f

This results in a segfault with zig 0.9-dev.401+cff7ecee0 from ziglang.org and zig master whereas there is the expected error message with zig 0.8.

I am not sure if i am doing something wrong but shouldn't the commit be reverted to provide an error instead of hard failing?

**Comment by g-w1** [comment]
I'll take a look at this.
