### ISSUE TITLE
wasm32 target does not produce .wasm file

### ISSUE THREAD

**Issue by dullbananas** [ziglang/zig#9371]
When I run:

```
zig build-lib src/main.zig -target wasm32-freestanding
```

It produces a "libmain.a" file instead of a .wasm file.

Zig version: 0.9.0-dev.453+7ef854682

**Comment by Luukdegram** [comment]
You have to append `-dynamic` to create a dynamic library.

You can read more about this change here: https://ziglang.org/download/0.8.0/release-notes.html#WebAssembly-Support and here https://github.com/ziglang/zig/pull/8837.

**Comment by dullbananas** [comment]
When using a build.zig file, is it possible to only generate the wasm file, without the .a/.o files?

**Comment by MasterQ32** [comment]
> When using a build.zig file, is it possible to only generate the wasm file, without the .o and .so files?

`Builder.addDynamicLibrary`
