### ISSUE TITLE
Feature: `clang-format` and `clang-tidy` as `zig` sub-commands

### ISSUE THREAD

**Issue by alexrp** [ziglang/zig#9374]
Note: I have no idea how hard this would be to achieve. I'm just bringing this up because having these available as part of Zig would mean that I could make them a default feature of [zig-sdk](https://github.com/vezel-dev/zig-sdk).

It seems like this would make sense given the other LLVM/Clang tooling Zig ships with, and would make `zig` a drop-in replacement for most of the C/C++ tooling that users would typically want to run in a CI setting.

**Comment by andrewrk** [comment]
I think this is a very reasonable proposal, however the cost to maintain this is not worth it, especially considering I want people to use Zig rather than C/C++.
