### ISSUE TITLE
Question: Is it possible to export symbols from an .exe file?

### ISSUE THREAD

**Issue by michal-z** [ziglang/zig#9375]
I would like to use D3D12 "Agility SDK" in a Zig program. In order to do so I need to export some symbols from my executable. In C++ I do it like this:

extern "C" { __declspec(dllexport) extern const UINT D3D12SDKVersion = 4; }
extern "C" { __declspec(dllexport) extern const char* D3D12SDKPath = ".\\D3D12\\"; }

In Zig, @export function seems to be ignored when building executable (it works perfectly for libraries).

How could I solve this?

Thanks,
Michal

**Comment by alexrp** [comment]
`-rdynamic -fdll-export-fns`

**Comment by michal-z** [comment]
Thanks, but how do I pass those flags to 'zig build'?

**Comment by michal-z** [comment]
Thanks! That works fine when using zig build-exe. Is there a way to pass -fdll-export-fns when using build.zig script?

**Comment by michal-z** [comment]
#9340
