### ISSUE TITLE
zig build run to use execve on platforms that support it

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#9376]
I noticed that when I use `zig build run` which corresponds with a "run task" in `build.zig`, there are 2 processes created, one from the build process and one from the process being executed.  I expected that on platforms that support execve (like linux) that the build process would use `execve` to run the child process rather than fork/exec and waiting for it to exit.  Is there any reason we aren't doing that?

Note that `zig run foo.zig` seems to use the `execve` mechanism.

**Comment by marler8997** [comment]
@ifreund mentioned in IRC that the `RunStep` is used for other things like executing subprocesses during the build.  In this case we couldn't just run execve for those.  Maybe we could add an extra type or option to enable the `execve` without fork code path.

Some notes.  Only one process with this "execve" option could be in the current set of build steps, and there could be no steps that "depend" on it since it would need to be the last step executed.

**Comment by g-w1** [comment]
I don't think this is a bug:
![image](https://user-images.githubusercontent.com/58830309/125687505-b4c51381-0cbc-4f0d-b480-3a9d3523563e.png)
It shows the command, and what failed, in case you want to re-run it yourself.

**Comment by andrewrk** [comment]
This proposal is not a good fit with the build system's design, which wants to check resource usage statistics of RunSteps, print timing information, and print a build summary. It's also not cross platform.
