### ISSUE TITLE
disallow non-final `else` prong in switch

### ISSUE THREAD

**Issue by Androthi** [ziglang/zig#9393]
zig allows placing =>else {} anywhere in the switch block without generating error or warning. is this intended behavior for zig? this is likely not what the programmer intended, except maybe when testing some part of code. should a warning be generated here?

    switch (x) {
        0...4 => {},
        else => {}, // programmer likely did not intend this
        5,6 => {},
    }

**Comment by Mouvedia** [comment]
When I read your example I expect 5 and 6 to be caught by the else prong and `5,6 => {},` to be dead code.

**Comment by g-w1** [comment]
Zig has no warnings, but maybe an error should be generated if `else` is not last.

**Comment by Androthi** [comment]
> When I read your example I expect 5 and 6 to be caught by the else prong and `5,6 => {},` to be dead code.

yes, but that's probably not what you want. someone could do this to test a different branch of code, forget about it and it could go a long time before the bug is discovered. potentially creating a security issue.

with something like this, if the compiler issues a warning and still compiles, it would be a real handy reminder that you did something that shouldn't be done.

i would also be ok with forcing else to be the last item and breaking out with an error if this is not the case.

while i would normally put  //NOTE here if i did something like this, i am scatter brained and can't be depended on to properly note things.

**Comment by nektro** [comment]
yes this intended behavior

**Comment by andrewrk** [comment]
This is intended behavior, and I don't see any reason why the programmer should not be able to do this. The else prong is no different than the other prongs other than the conditions that send control flow to it.
