### ISSUE TITLE
Some macOS `#include`s fail when cross-compiling using Zig

### ISSUE THREAD

**Issue by alexrp** [ziglang/zig#9395]
CoreCLR contains some macOS `#include`s here: https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/coreclr/gc/unix/gcenv.unix.cpp#L65-L76

Of these, two fail when building with Zig:

```
fatal error : 'mach/thread_state.h' file not found
fatal error : 'mach/vm_param.h' file not found
```

Replacing them with `mach/machine/...` equivalents seems to work, but this is probably still a bug in Zig.

**Comment by nektro** [comment]
https://github.com/ziglang/fetch-them-macos-headers/blob/main/src/headers.c#L115-L118

https://github.com/ziglang/fetch-them-macos-headers/tree/main/libc/include/x86_64-macos-gnu/mach

https://github.com/apple/darwin-xnu/tree/main/osfmk/mach

cc @kubkon

**Comment by alexrp** [comment]
While on the subject, it might be worth mentioning that `thread_get_register_pointer_values` is also missing from the macOS headers, presumably due to the headers being old and this being a relatively new function.

**Comment by andrewrk** [comment]
headers added in https://github.com/ziglang/fetch-them-macos-headers/commit/5fcad6f23c1f0c0046b2b5061337bf73522911da

Checklist to land the changes:
 * [x] fetch x86_64-macos.10 https://github.com/ziglang/fetch-them-macos-headers/commit/3d69240250a5c660ec0e00134991dabd3165f538
 * [ ] fetch x86_64-macos.11
 * [ ] fetch x86_64-macos.12
 * [ ] fetch aarch64-macos.11
 * [x] fetch aarch64-macos.12 https://github.com/ziglang/fetch-them-macos-headers/commit/0c869ac83859cf80d20c29de57eac51ad2813941
 * [ ] run the `generate` subcommand and commit changes to ziglang/zig repo

@kubkon you have the necessary VMs lying around to check those 3 boxes right? :slightly_smiling_face:

**Comment by kubkon** [comment]
Almost there! Sadly, I don't have access to `aarch64-macos.11` and it seems virtualization is not an option since it is only possible to virtualize starting with macOS 12 (i.e., virtualize arm64 on the M1). @slimsag any chance you have M1 running BigSur handy? If not, the next nuclear option will be for me to restore my MBA back to BigSur.

**Comment by slimsag** [comment]
@kubkon unfortunately not :( My MBA is also on macOS 12

**Comment by kubkon** [comment]
> @kubkon unfortunately not :( My MBA is also on macOS 12

No probs! Thanks for checking. I'm waiting for Loris to check if he's still running 11 on his MBA. If not, I might try cheating a little and downloading an earlier version of Xcode, and switching SDKs to see if that works (or tweaking the code as required to achieve just that).

**Comment by kubkon** [comment]
Loris saves the day! 🎉 🎉 🎉
