### ISSUE TITLE
Only allow `_ =>` when switching on a non-exhaustive enum

### ISSUE THREAD

**Issue by dbandstra** [ziglang/zig#9399]
From the docs:

> A switch on a non-exhaustive enum can include a '_' prong as an alternative to an `else` prong with the difference being that it makes it a compile error if all the known tag names are not handled by the switch. 

I think `_ =>` should only be allowed when you're switching on a non-exhaustive enum. Currently you can use it anywhere, but it's a no-op / unreachable code.

The lack of compile error is confusing for people who accidentally try to use `_` instead of `else` (e.g. from mental fog of switching between Zig and another language where `_` is used for the default case).

We already have a nice compile error when you try to use both `else` and `_` in the same switch expression.

---

 ```zig
pub fn main() void {
    var b = false;

    switch (b) {
        true => {},
        _ => {},
    }
}
```

```
./hmm.zig:4:5: error: switch must handle all possibilities
    switch (b) {
    ^
```

---

```zig
pub fn main() void {
    const b = true;

    switch (b) {
        true => {},
        false => {},
        _ => {},
    }
}
```

^ compiles successfully.

**Comment by Vexu** [comment]
This already exists in stage2: https://github.com/ziglang/zig/blob/8cde0c91c6e95853a092ff8e00f92d804102a5dc/src/Sema.zig#L3681.

**Comment by dbandstra** [comment]
Nice, will close.
