### ISSUE TITLE
lld-link error with Zig 0.8.0 on Windows, undefined symbols '_fseeki64' and '_ftelli64'

### ISSUE THREAD

**Issue by foxnne** [ziglang/zig#9402]
I'm trying to build this library: [zip](https://github.com/kuba--/zip) and prior to 0.8.0 I had no issues, but since I get the following errors on the same system: 
```
lld-link: error: undefined symbol: __declspec(dllimport) _fseeki64
>>> referenced by C:\Users\tiltf\dev\proj\pixi\src\deps\upaya\src\deps\zip\zip\src\zip.c
>>>               C:\Users\tiltf\dev\proj\pixi\zig-cache\o\0089258faf0b49636b95f3ebd593c111\zip.obj

lld-link: error: undefined symbol: __declspec(dllimport) _ftelli64
>>> referenced by C:\Users\tiltf\dev\proj\pixi\src\deps\upaya\src\deps\zip\zip\src\zip.c
>>>               C:\Users\tiltf\dev\proj\pixi\zig-cache\o\0089258faf0b49636b95f3ebd593c111\zip.obj
error: LLDReportedFailure
```

This is the project if its relevant: [pixi](https://github.com/foxnne/pixi)

These errors happen regardless of if the project was built using `-Dtarget=native-native-msvc` or not.

Any information would be amazing! Thanks

**Comment by MasterQ32** [comment]
This is definitly a bug in the mingw64-distribution of zig. My minimal reproduction to come to this conclusion is:
1. create `main.c` (see below)
2. compile executable with [mingw64 v8.0.0](https://hub.docker.com/r/mmozeiko/mingw-w64)
    - ``docker run --rm -ti -v `pwd`:/mnt mmozeiko/mingw-w64 x86_64-w64-mingw32-gcc -O2 main.c``
3. compile executable with zig
   - `zig build-exe -lc -target x86_64-windows-gnu main.c`
   - `zig cc -lc -target x86_64-windows-gnu main.c`

Step 2 will compile just fine (verified with `wine64`), step 3 will fail with
```
[felix@denkplatte-v2 ftelli64]$ zig build-exe -lc -target x86_64-windows-gnu main.c
lld-link: error: undefined symbol: __declspec(dllimport) _fseeki64
>>> referenced by /home/felix/projects/experiments/ftelli64/main.c:5
>>>               /home/felix/.cache/zig/o/8e813e8c453fb18e5207eaa1df3543b7/main.obj:(main)

lld-link: error: undefined symbol: __declspec(dllimport) _ftelli64
>>> referenced by /home/felix/projects/experiments/ftelli64/main.c:6
>>>               /home/felix/.cache/zig/o/8e813e8c453fb18e5207eaa1df3543b7/main.obj:(main)
thread 9568 panic: attempt to unwrap error: LLDReportedFailure
```
or
```
[felix@denkplatte-v2 ftelli64]$ zig cc -lc -target x86_64-windows-gnu main.c
lld-link: error: undefined symbol: __declspec(dllimport) _fseeki64
>>> referenced by /home/felix/.cache/zig/o/3ade1f56a9fc259cc21654390898a457/main.obj:(main)

lld-link: error: undefined symbol: __declspec(dllimport) _ftelli64
>>> referenced by /home/felix/.cache/zig/o/3ade1f56a9fc259cc21654390898a457/main.obj:(main)
exit code: 1
```

`main.c` looks like this:
```c
#include <stdio.h>

int main(int argc, char ** argv) {
  FILE * f = fopen(argv[0], "rb");
  _fseeki64(f, 10, SEEK_SET);
  __int64 pos = _ftelli64(f);
  fclose(f);
  printf("offset = %lld\n", pos);
  return 0;
}
```

**Comment by michal-z** [comment]
The problem is that mingw64-distrbution of zig does not include mingw-w64-crt/stdio/fseeki64.c file. Implementation of _ftelli64 and _fseeki64  is there.
