### ISSUE TITLE
Could Zig warn/error that a function can return an error, but no code paths do?

### ISSUE THREAD

**Issue by slimsag** [ziglang/zig#9409]
### Problem

It is possible to define a function that returns `!T` or `ConcreteError!T` according to its signature, but has no `try` or other code paths that return such an error.

In my case, I've run into this a few times and it has been an indicator of me forgetting to check an error from a C library. For example: https://github.com/hexops/mach/commit/309b71d60060f3f78f1aafbcff3821b425ae20dc

### Solution

Perhaps we could determine that if no code paths _can_ return such an error matching the return type, then that is a mistake or the function signature should not contain an error return?

Caveat: we would also need a way to opt-out and say "I really do want a function that is defined as returning an error, with no code paths doing so" similar to `_ = foo` for the unused parameter check.

**Comment by Hadron67** [comment]
> Caveat: we would also need a way to opt-out and say "I really do want a function that is defined as returning an error, with no code paths doing so" similar to `_ = foo` for the unused parameter check.

Note that a common use case for this is generic programming. For example, the reader and writer interface in the standard library requires the read and write function to return an error union, so the implementation must match this signature, even if no error could actually be returned.

**Comment by AssortedFantasy** [comment]
In addition to the mention that this screws up interfaces which must adhere to a particular signature (like `std.mem.Allocator`).

This wouldn't work for problems as simple as conditional compilation. Lots of the standard lbrary abstractions only create an error on particular targets.

**Comment by nektro** [comment]
Zig doesn't have warnings and sometimes you need to have a certain return value in order to match a callback signature. not needing the error union in that example is not up to the decision of that consumer. so this is unlikely.

for a situation like the one described above: think servers https://github.com/Luukdegram/apple_pie. using the router, handler functions will almost always have the signature `fn (response: *http.Response, request: http.Request) !void`

**Comment by slimsag** [comment]
I no longer feel strongly about this either way so I am closing.
