### ISSUE TITLE
Projects using libc cannot be compiled to wasm32-wasi

### ISSUE THREAD

**Issue by jedisct1** [ziglang/zig#9414]
When `linkLibC()` is used in a Zig project, compiling it to `wasm32-wasi` has multiple issues:

* `_errno()` is undefined. Looks like the WASI libc has it, so just adding the definition should be fine.
* The `main()` function we define has 3 parameters (3rd one being the environment), but the WASI libc expects it to only have 2 of them, so we get a signature mismatch. That can be worked around in `wasi/libc-bottom-half/sources/__main_argc_argv.c`
* ` __stack_chk_fail()` is not defined. This function should probably not be required for wasm.
* `c::exit()` is not defined. 

---

To reproduce:

* `zig init-exe`
* Add `exe.linkLibC();`
* `zig build -Dtarget=wasm32-wasi`

```text
/opt/zig/lib/zig/std/c.zig:39:16: error: use of undeclared identifier '_errno'
        return _errno().*;
               ^
/opt/zig/lib/zig/std/os.zig:754:22: note: called from here
        switch (errno(rc)) {
```

**Comment by jedisct1** [comment]
Ugly workarounds: https://github.com/jedisct1/zig/commit/e6da129cfab73a06f08c972b83464e622c2b7b81 

Symbols from the wasi-libc are exposed in the `env` namespace. But declaring them with `extern "c"` causes WebAssembly runtimes to look for them in a module called `c`.

**Comment by mathetake** [comment]
I believe this has been resolved by #9227 ?

**Comment by jedisct1** [comment]
I think it has!

Thank you so much for this, Takeshi!

**Comment by mathetake** [comment]
yay 🎉 :)
