### ISSUE TITLE
Type inference in array literals

### ISSUE THREAD

**Issue by jarble** [ziglang/zig#9423]
This is the usual syntax for declaring array literals in Zig:

`var an_arr1 = [_]i64{1,2};`

I also tried to initialize this array without declaring its type, but this seems to be a syntax error:

`var an_arr1 = {1,2};`

(I tested this example in the [Zig Playground](https://zig-play.dev/), but it won't compile).

Since the example above doesn't work, is there another way to declare array literals with inferred types?

**Comment by jarble** [comment]
I found a workaround: I can use `@TypeOf` to get the type of the first item in the array.

`var an_arr1 = [_]@TypeOf(1){1,2};`

But I wish there were a less-redundant way to do this.

**Comment by dbandstra** [comment]
Your workaround is going to define an array of `comptime_int`, not sure if that's what you want.

I think your issue is more about ints than it is about arrays. You don't typically do `var x = 5;` in Zig either - you do `var x: i64 = 5;` (or whatever int type you want).

There is type inference if you're assigning to a slice (or passing to a function that takes a slice):

```zig
var x: []const i64 = ...;

// result location type inference
x = &.{1, 2, 3}; 
```

(Technically, you can do it with array-to-array assignment too, like `var x: [4]i64 = .{1, 2, 3, 4};` but that's a less common scenario.)

**Comment by nektro** [comment]
this proposal violates the [Zen] item `Favor reading code over writing code.`\[1]

some cases where the type checker has a reference point, inference can be used. but the type of integer literals is `comptime_int` as mentioned above and so if you need them to be of a specific type at the declaration site, `const x = [_]T{ 1, 2, 3 };` is the way to go, where `T` can be `u32` or any other primitive number type \[2]

\[1]: https://ziglang.org/documentation/master/#Zen
\[2]: https://ziglang.org/documentation/master/#Primitive-Types

**Comment by jarble** [comment]
@dbandstra 
It turns out that I can use a struct here instead of an array:

 `var a = .{1,2};`

But I still don't know how to convert this struct to an array, or vice-versa.

**Comment by dbandstra** [comment]
`.{1, 2}` is a special syntax sometimes called "tuple" (can't remember if that's still the official name). The tuple literal can coerce to either a struct or an array. If you don't provide any type annotation on the left side, it will be a struct, I think.

You could manually copy the struct to an array item-by-item, but you probably just want to create it as an array in the first place:

```zig
var a: [2]i64 = .{1, 2};
```

Note you have to specify the length of the array (can't use `[_]` on the left side of the assignment). So in this case it's probably more convenient to use `var a = [_]i64{1, 2};`

If your question is, "can I initialize an array of integers without specifying an int type", the answer is no, unless you want `comptime_int`, which you probably don't. Zig doesn't have a "default" int width (unlike C or Rust).

**Comment by zzyxyzz** [comment]
@jarble,
as already pointed out by @dbandstra, integer literals in Zig have neither a default type nor a suffix notation like `100u8`. Whenever you use integer literals, you always have to tell the compiler which exact type you want. If you want to create a fixed-size array of `i64`, then the type inevitably needs to appear somewhere in the declaration or initialization. There are in fact three valid ways of doing it:
```zig
var a = [_]i64{1, 2}; // only notation that allows inferred length
var b: [2]i64 = .{1, 2};
var c = @as([2]i64, .{1, 2});
```
As you see, `[_]i64{1, 2}` is already the most economical notation, and cannot be compressed further. Your "workarounds", on the other hand, do something completely different:
```zig
var d = [_]@TypeOf(1){1,2};
// This is an error. You are creating an array with the type `[2]comptime_int`
// and trying to assign it to a runtime variable.

var e = .{1,2};
// This compiles, but creates a zero-sized struct with two constant `comptime_int` fields.
// Trying to do `e[0] += 1;` will be an error.
