### ISSUE TITLE
Proposal: `catch unreachable` shorthand

### ISSUE THREAD

**Issue by presentfactory** [ziglang/zig#9424]
`x orelse unreachable` has the shorthand operator `x.?`, and while I see code occasionally use `x catch unreachable` it doesn't have any shorthand for this.

My proposal is simply that there should be a `x.!` operator to simplify that, or just for the sake of consistency between error unions and optionals even if it's not the most common of operations since they already share many similar patterns.

I've only been using Zig for a short time so forgive me if this is a bit silly, but it does seem like it should be a thing to me.

**Comment by ehaas** [comment]
I find `x.?` syntax to be most useful when I already know for sure that a variable is not null based on an existing null check, but a capturing if would be too verbose - for example
```zig
if (x != null and y != null) do_something(x.?, y.?);
```
vs
```zig
if (x) |unwrapped_x| {
   if (y) |unwrapped_y| do_something(unwrapped_x, unwrapped_y);
}
```

There's not really an equivalent for error unions -  you generally don't want to "carry" an error union around in a variable - you want to `try` it or handle it in some way. I think `catch unreachable` is appropriately verbose and noticeable for letting a reader know that something potentially dangerous is going on.

**Comment by presentfactory** [comment]
@ehaas I did think of the fact that it may have been left intentionally verbose to convey the meaning/danger, but `.?` is equally as dangerous really if it is done in a context without an explicit check like the one you provided in your example (rather just relying on the programmer's knowledge that it is impossible to be null in some context). I don't really think it's too reasonable anyways to omit a shorthand just for fear of people actually using it, presumably they will know the dangers attached with it (e.g. it will crash your program if used incorrectly just like `.?` will) and use it appropriately, rather than treating it like just something magic.

The fact that `catch unreachable` is even an idiom to me though indicates this is a use case people do use despite it perhaps not being as common due to how errors are usually handled.

One example of where it might crop up when you know a function will never return an error given the inputs you provide, making checking the error union with an if like in your example a performance detriment even if it safer to write code that way.

Another is if you simply do not care about handling the error if it is something exceptionally rare (like running out of memory) and prefer the program crashing due to no easy way or care to handle it gracefully. Sometimes I might want to write code quickly and not safely (think for some quick and dirty test application), and having to write `catch unreachable` all over in places where I would handle errors in a more formal program just seems like it'd get tedious.

Either way that's just my two cents.

**Comment by leecannon** [comment]
@presentfactory  I feel the case of not caring about errors is much better handled by `try` than `.!`, especially with error set inference, error return traces, etc.

**Comment by marler8997** [comment]
It's also good to look at some real-world data.  The more common something is, the more justification for a shorthand.  Take a look at the compiler source code:

```sh
$ git clone https://github.com/ziglang/zig
$ cd zig
$ grep -r "catch unreachable" src | wc -l
41
$ grep -r "\.?" src | wc -l
1884
```

It's just one data set, but the `.?` shorthandle appears to occur alot more often than `catch unreachable`.

That being said, I would prefer if the language was able to get around the need for having `.?` altogether.  It's easy for a human to see when `.?` is correct, it would be nice if the compiler could do the same and infer that a variable has already been verified to be non-null.

**Comment by presentfactory** [comment]
@leecannon Yeah I mean that is nice and all to see where errors are actually coming from, though at the same time crashing immediately usually will have the stack trace fairly representative of where the issue is without needing that. Additionally relying on errors like that does presumably add a runtime cost which you cannot easily get rid of whereas point of the `orelse unreachable` or `catch unreachable` idioms is to avoid that, so I don't think it's a direct substitute to use `try` everywhere.

@marler8997 Indeed actual data matters, I did search up how many people have used `catch unreachable` in public GitHub repos and found it present in 2.3k files, so it's definitely used, though yeah that likely isn't too much compared to all the Zig code ever. At the same time though sometimes it is being used in cases like [this](https://github.com/somelun/nes-oddity/blob/8f8325f978d6586b1d0b150717304d62371a96b6/src/opcodes.zig#L301) which I think shows off how tedious it can get pretty quickly.

I also do not think the language can ever fully know if an optional is present or not either. It may be able to optimize some uses of it around basic control flow and whatnot with static analysis sure, but there will always be cases where it is simply impossible to resolve at compiletime. Due to that it probably will always be the programmer's responsibility to use such a thing correctly, otherwise without it there'd be no way to resolve optionals in such instances.

**Comment by nektro** [comment]
`catch unreachable` does not have a shorthand on purpose

**Comment by andrewrk** [comment]
Some parts of the language are done and locked in, and this is one of them.
