### ISSUE TITLE
translate-c: regression(?)/change in translating type-casting macros

### ISSUE THREAD

**Issue by 17dec** [ziglang/zig#9425]
ncurses has this macro in their header files:

```c
#define NCURSES_CAST(type,value) (type)(value)
```

With Zig 0.8, that translates to:
```zig
pub inline fn NCURSES_CAST(type_1: anytype, value: anytype) type_1 {
        return @import("std").meta.cast(type_1, value);
}
```

Zig 0.9.0-dev.478+e80702067 interprets it as a function call instead:
```zig
pub inline fn NCURSES_CAST(type_1: anytype, value: anytype) @TypeOf(type_1(value)) {
        return type_1(value);
}
```

The NCURSES_CAST macro is unfortunately used for many definitions in the header file, making them unusable after the update.

**Comment by Vexu** [comment]
Broken by #9092, could be fixed by #9265.

**Comment by ehaas** [comment]
@17dec would you be able to test with the latest commit from #9265 - I just pushed something that I think will fix it.

**Comment by 17dec** [comment]
Commit a4d65c18f9a98271446730eeec829623c6746793 is working for me, thanks!
