### ISSUE TITLE
unhandled instruction when compile c project using zig cc

### ISSUE THREAD

**Issue by xh-78** [ziglang/zig#9436]
os: Ubuntu 20.04.2 LTS
zig version: 0.9.0-dev.533+26984852b

I got an illegal hardware instruction (core dumped) when compiling a c project use zig cc:

valgrind give me this

vex amd64->IR: unhandled instruction bytes: 0x67 0xF 0xB9 0x40 0x14 0x66 0x66 0x2E 0xF 0x1F
vex amd64->IR:   REX=0 REX.W=0 REX.R=0 REX.X=0 REX.B=0
vex amd64->IR:   VEX=0 VEX.L=0 VEX.nVVVV=0x0 ESC=0F
vex amd64->IR:   PFX.66=0 PFX.F2=0 PFX.F3=0

when I use -O3 or -O2, this error will not happen.

**Comment by Vexu** [comment]
Does passing `-fno-sanitize=undefined` fix this? https://github.com/ziglang/zig/wiki/FAQ#why-do-i-get-illegal-instruction-when-using-with-zig-cc-to-build-c-code

**Comment by xh-78** [comment]
> Does passing `-fno-sanitize=undefined` fix this? https://github.com/ziglang/zig/wiki/FAQ#why-do-i-get-illegal-instruction-when-using-with-zig-cc-to-build-c-code

Yes, passing `-fno-sanitize=undefined`  can avoid this

**Comment by S0urc3C0de** [comment]
The same illegal instruction thing happens when compiling SDL2 in debug mode using zig cc without having disabled the UB sanitizer. Is this a false positive, a bug in the sanitizer or is the UB sanitizer generally not supposed to work correctly when compiling C?

**Comment by leecannon** [comment]
Straight from [clang](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#issue-suppression)
`UndefinedBehaviorSanitizer is not expected to produce false positives. If you see one, look again; most likely it is a true positive!`
