### ISSUE TITLE
zig test weird output

### ISSUE THREAD

**Issue by drsneed** [ziglang/zig#9438]
try running this code with zig test:

const std = @import("std");
test "abc def" {
    std.debug.warn("hello, world!\n", .{});
}

The output I get is:
C:\Projects\test>zig test test.zig
hello, world!st "abc def"...
All 1 tests passed.

**Comment by Vexu** [comment]
With the recent changes to `std.Progress` in f7ee3b4 I get this:
```
Test [1/1] test "abc def"... hello, world!
All 1 tests passed.
```

Using an older version I got the same output as you did.
