### ISSUE TITLE
Update build from source instructions

### ISSUE THREAD

**Issue by ayende** [ziglang/zig#9444]
I followed things here: https://github.com/ziglang/zig/wiki/How-to-build-LLVM,-libclang,-and-liblld-from-source#posix

And I really got lost (somehow I ended up re-compiling cmake, but I really can't trace how I got to it from trying to build zig).
Basically, Ubuntu doesn't have `clang-12` easily available, and that is required for building zig.

Eventually, I found that I can just rush `bash ci/azure/linux-script` and it will do all the setup for me including everything.

Would be nice to update the instructions to explain how simple that it.

**Comment by marler8997** [comment]
That documentation you linked is showing you how to build clang-12.

**Comment by ayende** [comment]
Doesn't actually work, however. LLVM builds, but when you run `cmake` / `make` on Zig you get missing `lld/Common/Driver.h`

**Comment by matu3ba** [comment]
```sh
git clone LLVM
cd LLVM
# assume ~/local does not exist else delete it
mkdir ~/local

mkdir -p build
cd build
cmake ../llvm -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/local -DLLVM_ENABLE_PROJECTS="llvm;clang;lld" -DLLVM_ENABLE_LIBXML2=OFF
#ninja
cmake --build . --target install

cd "$HOME/dev/git/zig/zig/build"
#exist changes? => stash everything
if output=$(git status --porcelain) && test -z "$output"; then
  echo "zig: Working directory clean"
else
  echo "zig: Uncommitted changes, stashing changes.."
  git stash --include-untracked
fi
git switch master
git fetch
if test "$(git rev-parse HEAD)" = "$(git rev-parse @{u})"; then
  echo "zig: HEAD and upstream identical"
else
  echo "zig: HEAD and upstream different"
  echo "zig: build stage1.."
  git merge origin/master && cmake .. -DCMAKE_PREFIX_PATH="$HOME/local" -GNinja && ${HOME}/dev/git/cpp/mold/mold -run ninja
fi
```

LLVM in 12.0.1 requires being build as monorepo or patching some files, even though ironically they ship the projects separately.

**Comment by ayende** [comment]
@matu3ba Thanks, that has been very helpful

**Comment by andrewrk** [comment]
I want to note for anyone stumbling on this issue that in fact the instructions in the wiki linked in the OP remain correct, and I have verified that they are still correct for LLVM, Clang, and LLD 12.0.1. The script posted by @matu3ba is not officially supported. The wiki instructions are the supported way to do it. Disregard everything in this thread.
