### ISSUE TITLE
stddef.h missing on all macOS targets

### ISSUE THREAD

**Issue by slimsag** [ziglang/zig#9447]
`stddef.h` is missing in all of the `lib/libc/include` targets for MacOS: [search query](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/ziglang/zig%24+file:stddef.h&patternType=literal)

I ran into this trying to get Mach/GLFW to compile for aarch64-macos: https://github.com/hexops/mach/issues/3

From what I can tell, https://github.com/ziglang/fetch-them-macos-headers is responsible for pulling these headers in.

I'm looking into this now.

**Comment by slimsag** [comment]
It is weird, because fetch-them-macos-headers explicitly tries to include `stddef.h`:

https://github.com/ziglang/fetch-them-macos-headers/blob/c3660ab2160ffebfd712317325df020cd799d83f/src/headers.c#L19

But it doesn't seem to even find it as part of the `fetch` process. With the following patch:

```diff
diff --git a/src/main.zig b/src/main.zig
index 51d1828..773313d 100644
--- a/src/main.zig
+++ b/src/main.zig
@@ -212,6 +212,7 @@ fn fetchHeaders(allocator: *Allocator, args: []const []const u8) !void {
 
     var it = mem.split(headers_list_str, "\n");
     while (it.next()) |line| {
+        std.debug.print("{s}\n", .{line});
         if (mem.lastIndexOf(u8, line, "clang") != null) continue;
         if (mem.lastIndexOf(u8, line, prefix[0..])) |idx| {
             const out_rel_path = line[idx + prefix.len + 1 ..];
```

```sh
% zig build && ./zig-out/bin/fetch_them_macos_headers fetch 2>&1|grep stddef
  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/stddef.h \
  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/__stddef_max_align_t.h \
```

And both of those strings start with `clang` and as such are excluded.

It failed to find the MacOS.sdk includes - which are definitely there:

```sh
% find /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/ | grep stddef.h
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk//usr/include/c++/v1/stddef.h
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk//usr/include/stddef.h
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk//System/Library/Frameworks/Kernel.framework/Versions/A/Headers/stddef.h
```

**Comment by slimsag** [comment]
Okay, so the command `fetch-them-macos-headers fetch` is running behind the scenes doesn't locate the SDK variant at all - only the clang one:

```
% cc -o tmp src/headers.c -MD -MV -MF headers.o.d && cat headers.o.d | grep stddef.h
  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/stddef.h \
```

**Comment by slimsag** [comment]
@kubkon could you explain to me the reasoning for excluding the `/clang/` headers? I am guessing it is because they are sometimes duplicative? I'm wondering what the implication would be for just.. not excluding the clang headers.

Or maybe you have another idea for how I could fix this?

**Comment by slimsag** [comment]
It actually only seems like a handful of headers, so maybe it's not such a bad idea to include them?:

```
% cc -o tmp src/headers.c -MD -MV -MF headers.o.d && cat headers.o.d | grep clang
  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/float.h \
  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/inttypes.h \
  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/stdint.h \
  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/iso646.h \
  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/limits.h \
  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/stdalign.h \
  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/stdarg.h \
  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/stdatomic.h \
  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/stddef.h \
  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/__stddef_max_align_t.h \
  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/stdbool.h \
  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/stdnoreturn.h \
  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/tgmath.h \
  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/arm_neon.h \
```

**Comment by floooh** [comment]
Strange, my Sokol headers are including stddef.h, and those compile fine on macOS with Zig (when using Zig to compile a C dependency into a static library).

Are you calling linkLibC() in your build targets? AFAIK this also sets up the search paths for the C runtime headers, without that I had all kinds of trouble with C header paths):

https://github.com/floooh/sokol-zig/blob/62efedbf2c73f71c4a805ff7a3f5fac447584dc0/build.zig#L12

(assuming this isn't a recent regression in the development branch)

**Comment by slimsag** [comment]
OK, I think this is an issue on my end. After digging a bit deeper, I see the intent is for `lib/include/stddef.h` to be supplied for macOS targets.

I was able to confirm the following compiles:

```
#include <stddef.h>

int main() {
   return 0;
}
```

```
zig cc -lc test.c
```

```
zig cc -lc test.c --target=aarch64-macos-gnu
```

I did run into a separate issue, #9455 - closing this one.
