### ISSUE TITLE
std.json: stringify enums based on tag name

### ISSUE THREAD

**Issue by haze** [ziglang/zig#9451]
@daurnimator says 
> there is no general industry agreement on if enums should be serialised in json as their name or their value/integer.

Multiple languages have this as their default and leave it up to custom facilities to serialize these as their value/integer.
Another point is that a majority of web apis will describe some form of `kind` field, and that usually maps to an enum. Anecdotally, these APIs use the tag name rather than a number to signify "which" value they are talking about.

For example:

```rust
use serde::Serialize;

#[derive(Serialize)]
struct Foo {
    kind: Vec<Kind>,
}

#[derive(Serialize)]
enum Kind {
    Integer,
    String,
    Boolean,
}

fn main() {
    println!(
        "{}",
        serde_json::to_string(&Foo {
            kind: vec![Kind::Integer, Kind::String, Kind::Boolean],
        })
        .unwrap()
    );
}
```
```
$ cargo run
{"kind":["Integer","String","Boolean"]}
```

@daurnimator also says
>  If anything, because of non-exhaustive enums and extern enums (where duplicate fields are permitted) they should be serialised as their integer value.

I feel like for these exact cases the tag name should NOT be used and instead the stringily or compileError paths should be preferred, as it's more clear that these are not used for specific tag/typing.

Given how close JSON is to web APIs, I feel like when using a normal enum the tag name should be used to reduce friction when interfacing with them. Please feel free to leave other usages of JSON that prefer the integer value over the tag name.

Another example is JavaScript. When people want to normally define an enum (which the language does not support natively), they go for something like this:

```js
const seasons = {
	SUMMER: "summer",
	WINTER: "winter",
	SPRING: "spring",
	AUTUMN: "autumn",
}
```

This is explicitly defining the enum tag name for serialization (otherwise it would use the integer value)

In TypeScript, enums look like this
```ts
enum Direction {
  Up = "UP",
  Down = "DOWN",
  Left = "LEFT",
  Right = "RIGHT",
}
```

More or less the same thing (where they default to integer codes. It's still common to define a string type for application interfaces however.

**Comment by ifreund** [comment]
I'd propose that the tag name should be use used for exhaustive enums and that non-exhaustive enums should yield a compile error and require manual handling. Since extern enums have been removed, we no longer have to worry about them.

**Comment by daurnimator** [comment]
> For example:
> 
> ```rust
> use serde::Serialize;
> ```

See https://serde.rs/enum-number.html

---

Notes/questions:
  - how to handle non-exhaustive enums? (which `kind` fields in json apis *often* are)
  - `@tagName` is relatively expensive (in memory usage): does it make sense as the default?
  - With #1717 it becomes easier to opt into specific behaviour, e.g. `pub const jsonSerialize = std.json.serializeEnumAsString; // inside your enum`
  - When there is no agreed upon default, the best thing zig can do is force the programmer to choose.

**Comment by haze** [comment]
> how to handle non-exhaustive enums? (which kind fields in json apis often are)
I agree with @ifreund in not supporting them for this use case

> @tagName is relatively expensive (in memory usage): does it make sense as the default?
I'm not sure how @tagName works specifically, I will look into this and write back later. My current stance on this is that JSON is inherently memory expensive at the cost of being semi-human readable, and since `@tagName` would only be used (opt-in) if the user is serializing, it's okay (for exhaustive enums, that is)

> With RFC: Make function definitions expressions #1717 it becomes easier to opt into specific behaviour, e.g. pub const jsonSerialize = std.json.serializeEnumAsString; // inside your enum
This is really cool. When this lands I can see it being similar to the `#[serde(...)]` macro options (like casing options and such). I think the proposed change is small enough to warrant this behavior until that behavior is fleshed out.

> When there is no agreed upon default, the best thing zig can do is force the programmer to choose.
I agree.

**Comment by haze** [comment]
@thejoshwolfe have your std.json changes affected this in any way? Also, do you have any thoughts about this?

**Comment by nektro** [comment]
https://github.com/nektro/zig-extras/blob/master/src/lib.zig#L191-L197

types have long been able to add a json stringify hook, perhaps this function should be added to `std.enums` ?

**Comment by thejoshwolfe** [comment]
Master branch currently serializes enums based on tag name: https://github.com/ziglang/zig/blob/11695745e5c6cbd158625d2c1682a09e2ee4c679/lib/std/json/stringify.zig#L165-L171

As of 2 weeks ago: https://github.com/ziglang/zig/pull/16239

Does this address the original proposal? I might be confused about what we're discussing.

I believe non-exhaustive enums cause detectable illegal behavior at runtime when there's no tag for the value. We can definitely improve on that.

**Comment by thejoshwolfe** [comment]
Oh, I just saw that the discussion spans two different July's, haha. I thought this was all recent discussion.

Ok, it's safe to mark this resolved then. Thanks to @yujiri8 for getting it implemented!
