### ISSUE TITLE
atomic.zig and Thread.zig fails while asm lowering

### ISSUE THREAD

**Issue by Deecellar** [ziglang/zig#9453]
while compiling in windows 10 version 20H2  after updating zig to master it shows me this error during the asm lowering section:
```

C:\ProgramData\chocolatey\bin\lib\zig\std\atomic.zig:75:19: error: assembly code must use string literal syntax

    asm volatile (hint_instruction ::: "memory");

                  ^



 C:\ProgramData\chocolatey\bin\lib\zig\std\Thread.zig:588:27: error: assembly code must use string literal syntax

            asm volatile (unmap_and_exit

                          ^

```
this does not happen in windows 11 however (somehow)

Relevant PC information is:
OS: Windows 10 20H2 x64
Intel I5 6500

**Comment by Luukdegram** [comment]
Make sure to update your `lib` folders to the latest master as well.
If you check the master source, you'll notice that the code differs from your local version: https://github.com/ziglang/zig/blob/master/lib/std/atomic.zig#L74 :)

**Comment by Deecellar** [comment]
Ok, that worked, need to update my script an see Why this happens, but at least make sense, I swear that I updated that.

Thanks
