### ISSUE TITLE
Documentation says u128 is maximum integer but in a codebase we have mentions of u256

### ISSUE THREAD

**Issue by achempion** [ziglang/zig#9454]
We have [mentions](https://github.com/ziglang/zig/blob/c9050565625bb7a43b8cc10b1103826ffccea69d/lib/std/json.zig#L170) of u256 but [master documentation](https://ziglang.org/documentation/master/#Primitive-Types) mentions only u128.

Also, we have [bigint struct](https://ziglang.org/documentation/master/std/#std;math.big.int) without any hints what it actually is and what maximum value it can represent, 300^40? 

p.s. I don't have much experience in system programming

**Comment by tauoverpi** [comment]
There's a snippet below the table which covers the u256 case.

> In addition to the integer types above, arbitrary bit-width integers can be referenced by using an identifier of i or u followed by digits. For example, the identifier i7 refers to a signed 7-bit integer. The maximum allowed bit-width of an integer type is 65535.

**Comment by achempion** [comment]
Didn't see that, thank you for pointing out, just searched the page for "u256".

But what is bigint for? Isn't u65535 can cover most of the needs for big numbers?

**Comment by ifreund** [comment]
> But what is bigint for? Isn't u65535 can cover most of the needs for big numbers?

`u65535` is big, but it's not arbitrarily big/small to fit your needs.  The bigint implementation in the std is used to implement `comptime_int`s in the self hosted compiler.
