### ISSUE TITLE
Compiler segfaults when working with packed unions

### ISSUE THREAD

**Issue by rolfmorel** [ziglang/zig#9457]
For my first go at Zig, I was trying to efficiently represent some ASTs. To do this, I need fine control over memory layouts (and some pointer casts). Hence I was working with packed structs and unions, and, because I am working with AST, the types are recursive.

The following is a minimized program that reproduces the issue, i.e. it consistently crashes the zig compiler with a segmentation fault:
```
const Variant = packed struct {
  left: ?*Node,
  right: u32,
};

const Node = packed struct {
  inner: packed union {
    a: Variant,
  }
};

pub fn main() anyerror!void {
  var node = Node{ .inner = .{.a = Variant { .left = null,
                                             .right = 0 } } };
  var ptr: *Variant = &node.inner.a;
  _ = ptr;
}
```
Running `zig build-exe --name repro repro.zig` always gives me the terminal output:
```Segmentation fault (core dumped)```
Providing any of the `--verbose-XX` flags doesn't produce any additional output.

I tried both the `0.8.0` Zig package on ArchLinux and a checkout of `gb87105c92`.

**Comment by tavi-vi** [comment]
I think I ran into the same issue, mine started as taking a reference to an array, and implicitly casting it to a slice, but when reduced looks very similar to your example:

```
pub fn main() void {
    var magic: [6]u8 = "testin".*;
    const Header = packed struct {
        magic: [6]u8,
        len: u32,
    };
    var h = Header {
        .magic = "foobar".*,
        .len = 1,
    };
    var v1 = &h.magic;

    _ = v1[0] == magic[0];
}
```

**Comment by rolfmorel** [comment]
Tried on `zig version` 0.11.0 and neither of the above code snippers crashed the compiler. My program successfully compiles while @tavi-vi's snippet now yields an error ("packed structs cannot contain fields of type '[6]u8'").
