### ISSUE TITLE
Anonymous structs can't be modified

### ISSUE THREAD

**Issue by jarble** [ziglang/zig#9462]
I tried to modify an anonymous struct here, but this example doesn't compile:
```
const std = @import("std");
pub fn main() void {
  var a = .{@as(f64,3)};
  a[0] = 2;
  std.debug.print("Hello, {}!", .{a[0]});
}
```
The compiler shows an error message:
```
An error occurred:
/tmp/playground684352321/play.zig:6:8: error: cannot assign to constant
a[0] = 2;
^
```
But it compiles successfully if I put the number in another variable before putting it in the struct:
```
const std = @import("std");
pub fn main() void {
  var temp = @as(f64,3);
  var a = .{temp};
  a[0] = 2;
  std.debug.print("Hello, {}!", .{a[0]});
}
```
I don't know why the first example didn't work: is this a compiler bug?

**Comment by Vexu** [comment]
This is working as intended. When you initialize an anonymous struct field with a comptime known value, the value becomes a part of the type as a `comptime` field. This can also be seen with `@sizeOf(@TypeOf(a))` which will return `0` for the first example and `8` for the second one.

**Comment by jarble** [comment]
I wish there were an easier way to initialize an anonymous struct with mutable values: is it possible to do this without putting all of the values in temporary variables before putting them in the struct?

**Comment by Vexu** [comment]
You can declare the desired type explicitly using `std.meta.Tuple`:
```zig
pub fn main() void {
  var a: std.meta.Tuple(&.{f64}) = .{ 3 };
  a[0] = 2;
  std.debug.print("Hello, {}!", .{a[0]});
}
```
#4335 could bring explicit syntax for this.
