### ISSUE TITLE
call to @export is ignored without `comptime` block

### ISSUE THREAD

**Issue by dullbananas** [ziglang/zig#9467]
main.zig:

```
const exporter = @import("exporter");

fn foo() callconv(.C) void {}
const exported = foo.doExport(foo);
```

exporter.zig:

```
pub fn doExport(f: fn () callconv(.C) void) void {
    @export(f, .{.name = "dullbananas"});
}
```

In the resulting main.wasm file, `dullbananas` is not exported. To make it work, I must add this to main.zig:

```
comptime {
    _ = exported;
}
```

Zig version: 0.9.0-dev.453+7ef854682

**Comment by Vexu** [comment]
This is how lazy analysis in Zig works, `exported` doesn't get analyzed unless it is referenced.
