### ISSUE TITLE
make zig fmt respect trailing commas in inline assembly

### ISSUE THREAD

**Issue by N00byEdge** [ziglang/zig#9476]
Trailing commas in inline assembly are removed by `zig fmt`:

```
pub fn wake_cpu(entry: u64, cpunum: u64, context: u64, comptime mode: Mode) u64 {
    const result = asm volatile (comptime switch (mode) {
            .HVC => "HVC #0",
            .SMC => "SMC #0",
        }
        : [_] "={X0}" (-> u64),
        : [_] "{X0}" (@as(u64, 0xC4000003)),
          [_] "{X1}" (cpunum),
          [_] "{X2}" (entry),
          [_] "{X3}" (context),
    );
    return result;
}
```
is turned into
```
pub fn wake_cpu(entry: u64, cpunum: u64, context: u64, comptime mode: Mode) u64 {
    const result = asm volatile (comptime switch (mode) {
            .HVC => "HVC #0",
            .SMC => "SMC #0",
        }
        : [_] "={X0}" (-> u64)
        : [_] "{X0}" (@as(u64, 0xC4000003)),
          [_] "{X1}" (cpunum),
          [_] "{X2}" (entry),
          [_] "{X3}" (context)
    );
    return result;
}
```

**Comment by andrewrk** [comment]
Can you share your ideal behavior in the form of one or two test cases that would go here? https://github.com/ziglang/zig/blob/master/lib/std/zig/parser_test.zig

**Comment by N00byEdge** [comment]
I mean, by looking at the very first case, it makes sure the trailing comma is removed:
https://github.com/ziglang/zig/blob/master/lib/std/zig/parser_test.zig#L7-L37
I would say the input string is the correct output here.

**Comment by N00byEdge** [comment]
There is also something to be said for putting the constraints on the line after the `:` too, in the same spirit, as to make not changing the first constraint in the list to be different from all the other ones. The trailing comma affects only the last constraint.

**Comment by jdmichaud** [comment]
@N00byEdge Just to clarify, we do not expect a comma [here](https://github.com/ziglang/zig/blob/05cf44933d753f7a5a53ab289ea60fd43761de57/lib/std/zig/parser_test.zig#L3840) but we expect one [here](https://github.com/ziglang/zig/blob/05cf44933d753f7a5a53ab289ea60fd43761de57/lib/std/zig/parser_test.zig#L3839).
