### ISSUE TITLE
expected type '[*c][*c]const u8', found '[*][*]const u8'

### ISSUE THREAD

**Issue by IllusiveS** [ziglang/zig#9479]
Found this while trying to play around with zig and sdl library
Windows 10
0.9.0-dev.533+26984852b

min repro case:

C
```
void function(const char **pNames) {
    
}
```

zig
```
    const allocator = std.heap.c_allocator;
    var extensions = std.ArrayList([*]const u8).init(allocator);
    errdefer extensions.deinit();

    c.function(extensions.items.ptr);
```

**Comment by Vexu** [comment]
There is no implicit cast to nested c pointers (yet?) so you need to use `@ptrCast`.

**Comment by IllusiveS** [comment]
Well according to @andrewrk on discord
> this looks like a compiler bug, it should allow any pointer to coerce to [*c]

so i made an issue for that :)

**Comment by fabioarnold** [comment]
Doesn't `[*]` guarantee the pointer to be not nullable?

So the C code could just do
```
void function(const char **pNames) {
    *pNames = NULL;
}
```
which is to be expected when the pointer type is `[*c]` but not with `[*]`.

I don't think your suggestion should automatically coerce.

Currently `c.function(@ptrCast([*][*c]const u8, extensions.items.ptr));` coerces as expected. (It's of course a bug, if the C code nulls the values).

**Comment by andrewrk** [comment]
This is working as designed, with test coverage by the test "implicit casting C pointers which would mess up null semantics":

```zig
test "example" {
    var c_ptr: [*c][*c]const u8 = undefined;
    var zig_ptr: [*][*]u8 = undefined;

    c_ptr = zig_ptr;
}
```

```
$ ./zig test test.zig 
./test.zig:5:13: error: expected type '[*c][*c]const u8', found '[*][*]u8'
    c_ptr = zig_ptr;
            ^
./test.zig:5:13: note: pointer type child '[*]u8' cannot cast into pointer type child '[*c]const u8'
    c_ptr = zig_ptr;
            ^
./test.zig:5:13: note: mutable '[*c]const u8' allows illegal null values stored to type '[*]u8'
    c_ptr = zig_ptr;
            ^
```
