### ISSUE TITLE
eliminate the BoundFn type from the language and the compiler implementations

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#9484]
Currently the Zig type system has a "BoundFn" which can be observed thusly:

```zig
test "example" {
    var a: A = .{};
    @compileLog(@TypeOf(a.b));
}

const A = struct {
    fn b() void {}
};
```

This type is to be removed from the language. Instead, method call syntax will be explicitly recognized in the parser. Here's an example which currently passes but will become a compile error:

```zig
test "example" {
    var a1: A = .{};
    var a2: A = .{};
    (if (true) a1.b else a2.b)();
}

const A = struct {
    fn b(a: A) void {
        _ = a;
    }
};
```

After this change, this will give a compile error: struct `A` has no field named `b`.

Related: #7942

Here's a diff to get you started:

```diff
diff --git a/lib/std/builtin.zig b/lib/std/builtin.zig
index 9d432a3a0..f4daf5354 100644
--- a/lib/std/builtin.zig
+++ b/lib/std/builtin.zig
@@ -204,7 +204,6 @@ pub const TypeInfo = union(enum) {
     Enum: Enum,
     Union: Union,
     Fn: Fn,
-    BoundFn: Fn,
     Opaque: Opaque,
     Frame: Frame,
     AnyFrame: AnyFrame,
diff --git a/src/stage1/all_types.hpp b/src/stage1/all_types.hpp
index dfebc66cf..d36396c68 100644
--- a/src/stage1/all_types.hpp
+++ b/src/stage1/all_types.hpp
@@ -310,12 +310,6 @@ struct ConstErrValue {
     ZigValue *payload;
 };
 
-struct ConstBoundFnValue {
-    ZigFn *fn;
-    Stage1AirInst *first_arg;
-    AstNode *first_arg_src;
-};
-
 struct ConstArgTuple {
     size_t start_index;
     size_t end_index;
@@ -510,7 +504,6 @@ struct ZigValue {
         double x_f64;
         float128_t x_f128;
         bool x_bool;
-        ConstBoundFnValue x_bound_fn;
         ZigType *x_type;
         ZigValue *x_optional;
         ConstErrValue x_err_union;
@@ -1492,10 +1485,6 @@ struct ZigTypeFn {
     ZigType *bound_fn_parent;
 };
 
-struct ZigTypeBoundFn {
-    ZigType *fn_type;
-};
-
 // Needs to have the same memory layout as ZigTypeArray
 struct ZigTypeVector {
     // The type must be a pointer, integer, bool, or float
@@ -1528,7 +1517,6 @@ enum ZigTypeId {
     ZigTypeIdEnum,
     ZigTypeIdUnion,
     ZigTypeIdFn,
-    ZigTypeIdBoundFn,
     ZigTypeIdOpaque,
     ZigTypeIdFnFrame,
     ZigTypeIdAnyFrame,
@@ -1587,7 +1575,6 @@ struct ZigType {
         ZigTypeEnum enumeration;
         ZigTypeUnion unionation;
         ZigTypeFn fn;
-        ZigTypeBoundFn bound_fn;
         ZigTypeVector vector;
         ZigTypeOpaque opaque;
         ZigTypeFnFrame frame;
```

**Comment by zigazeljko** [comment]
What is the expected implementation here?

1. Add a new node type to parser to be used instead of the current `NodeTypeFieldAccessExpr` + `NodeTypeFnCallExpr` combo.
2. Keep the parser unchanged and handle the `NodeTypeFieldAccessExpr` + `NodeTypeFnCallExpr` combo inside astgen.

**Comment by andrewrk** [comment]
@zigazeljko apologies for not seeing your question earlier.

You'll need to change the parser as noted here:

> Instead, method call syntax will be explicitly recognized in the parser

**Comment by edt-xx** [comment]
Probably a stupid question, but how will we define a 'class fn' in a struct?  eg usually you want:

fn aaa(...) type {
     var bbb:u64 = ....
     return struct {
         ....
         ST = @This();
           fn ccc(self: *ST, ... ) ...  { ... }    // the common case
           
           fn ddd(eee: ... ) u64 { ... some code depending on bbb & eee  returning a u64 ... )  // how will we express this
           ....

**Comment by dacjames** [comment]
Is anyone working on this? I've been looking for something for a first time contribution that touches the language itself (since that's my interest area). 

Aside from overall simplification, what is the motivation for removing `BoundFn`, @andrewrk ?

**Comment by zseri** [comment]
it is normal that I arrive at the following when applying the patch in the first comment?
```
$ zig build --zig-lib-dir lib --verbose
Semantic Analysis [440/860] Assertion failed at /build/source/src/stage1/ir.cpp:19106 in type_info_to_type. This is a bug in the Zig compiler.thread 303768 panic: 
Unable to dump stack trace: debug info stripped
Aborted (core dumped)
```
with zig version 0.10.0 fbe5336f3be7065ab84b797eb629ada9565341c2
