### ISSUE TITLE
Multi-threaded execution stalls sometimes when compiled with Drelease-fast=true

### ISSUE THREAD

**Issue by Opioid** [ziglang/zig#9492]
I have a bit of multi-threaded code where a thread will sometimes hang at a simple if-statement. That is, if I print the condition of the if, it will show false, but it will never reach the code after the if-statement. This happens roughly 50% of the time.

Before you say, this is a probably a user error, please consider that the problem only seems to occur when compiled with Drelease-fast=true and that the code basically is translated from c++/std::thread where I never have encountered the problem. Simply deleting the if statement seems to fix the stall.

The problematic part is at the end of the code segment, but the rest might be important for context.

```zig
const std = @import("std");
const Allocator = std.mem.Allocator;

const Unique = struct {
    wake_signal: std.Thread.Condition = .{},
    done_signal: std.Thread.Condition = .{},

    mutex: std.Thread.Mutex = .{},

    wake: bool = false,
};

pub const Pool = struct {
    pub const Context = u64;

    const ParallelProgram = fn (context: *Context, id: u32) void;

    uniques: []Unique = &.{},
    threads: []std.Thread = &.{},

    parallel_context: *Context,
    parallel_program: ParallelProgram,

    quit: bool = false,

    pub fn configure(self: *Pool, alloc: *Allocator, num_threads: u32) !void {
        self.uniques = try alloc.alloc(Unique, num_threads);
        for (self.uniques) |*u| {
            u.* = .{};
        }

        self.threads = try alloc.alloc(std.Thread, num_threads);
        for (self.threads) |*thread, i| {
            thread.* = try std.Thread.spawn(.{}, loop, .{ self, @intCast(u32, i) });
        }
    }

    pub fn runParallel(self: *Pool, context: anytype, program: ParallelProgram) void {
        self.runParallelInt(@ptrCast(*Context, context), program);
    }

    fn runParallelInt(self: *Pool, context: *Context, program: ParallelProgram) void {
        self.parallel_context = context;
        self.parallel_program = program;

        self.wakeAll();
        self.waitAll();
    }

    fn wakeAll(self: *const Pool) void {
        for (self.uniques) |*u| {
            const lock = u.mutex.acquire();
            u.wake = true;
            lock.release();

            u.wake_signal.signal();
        }
    }

    fn waitAll(self: *const Pool) void {
        for (self.uniques) |*u| {
            const lock = u.mutex.acquire();
            defer lock.release();

            while (u.wake) {
                u.done_signal.wait(&u.mutex);
            }
        }
    }

    fn loop(self: *Pool, id: u32) void {
        var u = &self.uniques[id];

        while (true) {
            const lock = u.mutex.acquire();
            defer lock.release();

            while (!u.wake) {
                u.wake_signal.wait(&u.mutex);
            }

            // Sometimes the execution will not get past this point
            // Printing self.quit always shows false
            // Removing the check always seems to help
            if (self.quit) {
               break;
            }

            self.parallel_program(self.parallel_context, id);

            u.wake = false;
            u.done_signal.signal();
        }
    }
};
```

**Comment by Opioid** [comment]
I'm fairly sure the cause was that I was using it like this `var threads: thread.Pool = undefined; try threads.configure(alloc, num_workers);`. So self.quit was not assigned at the time where the stalls happened. 
However, I don´t understand how the uninitialized variable could cause a stall. Wouldn't it be 50/50 chance, that the memory contained either false or true and simply behave accordingly?
Why could zig not warn or panic about this in debug mode?

**Comment by kprotty** [comment]
At first glance, this seems like undefined behavior, where there's any chance of [anything happening](https://zig.godbolt.org/z/r3o83Wd55). One possibility is that it evaluates to false when printing, but control flow assumes that its true. Could you link to the code you were trying to port from for reference to understand the intent?

**Comment by Opioid** [comment]
It seems to work 100% ok, if I initialize the _quit_ variable. Interesting snippet you linked there! I was not aware it could work like this.
