### ISSUE TITLE
Importing a file with a name that starts with the package name outside of the package path provides incorrect error message

### ISSUE THREAD

**Issue by kcbanner** [ziglang/zig#9537]
With the following directory structure:

```
src/main.zig
src/game_api.zig
src/game/game.zig
```

build.zig snippets:
```
const exe = b.addExecutable("ion", "src/main.zig");
...
const game = b.addSharedLibrary("game", "src/game/game.zig", .unversioned);
```

If `game.zig` has `const game_api = @import("../game_api.zig");`, then the resulting error is:

```
$ zig build
C:\Users\kcbanner\projects\ion\src\game\game.zig:4:26: error: unable to load 'C:\\Users\\kcbanner\\projects\\ion\\src\\game\api.zig': FileNotFound
const game_api = @import("../game_api.zig");
```

Not how it's trying to import `game\api.zig`.

However, if `game_api.zig` is changed to say, `foo_api.zig`, we get the correct message:
```
$ zig build
.\game\game.zig:5:18: error: import of file outside package path: '../foo_api.zig'
const game_api = @import("../foo_api.zig");
```

I believe the issue is that in `Module.zig:importFile`:

```
    if (!mem.startsWith(u8, resolved_path, resolved_root_path)) {
        return error.ImportOutsidePkgPath;
    }
```

Here `resolved_root_path` is `"C:\\Users\\kcbanner\\projects\\ion\\src\\game"`, so it matches with the `resolved_path` of `"C:\\Users\\kcbanner\\projects\\ion\\src\\game_api.zig"`. I think the solution might be to add the path separator to the end of `resolved_root_path`? 

I can make a PR for this, if that is an acceptable solution.

**Comment by LordMZTE** [comment]
I can't reproduce this. This code simply compiles for me without an error. Could you create an example repo?

**Comment by kcbanner** [comment]
Thanks for looking into this!

Example repo is [here](https://github.com/kcbanner/zig-9537), currently I get:

```
$ zig build
C:\Users\kcbanner\projects\zig-9537\src\game\game.zig:1:26: error: unable to load 'C:\Users\kcbanner\projects\zig-9537\src\game\api.zig': FileNotFound
const game_api = @import("../game_api.zig");

$ zig version
0.9.1
```
