### ISSUE TITLE
threads.h not found on windows

### ISSUE THREAD

**Issue by kennyb** [ziglang/zig#9540]
```cmd
HP@DESKTOP-7RU8LQ3 MINGW64 ~/Documents/mass (master)
$ $CC -o test.exe test-threads.c -target x86_64-linux-gnu

HP@DESKTOP-7RU8LQ3 MINGW64 ~/Documents/mass (master)
$ $CC -o test.exe test-threads.c -target x86_64-windows-gnu
test-threads.c:1:10: fatal error: 'threads.h' file not found
#include <threads.h>
         ^~~~~~~~~~~
1 error generated.
```

for a simple main program:
```c
#include <threads.h>

int main (int argc, char** argv) {
    return 0;
}
```

**Comment by alexrp** [comment]
I don't think MinGW has this header. In general, adoption of the C11 threads API is very poor; you should consider using something else.

**Comment by kennyb** [comment]
I was trying to get [mass](https://github.com/grassator/mass) to build with zig. in the end, I decided to install visual studio community which has the header and build with that...
