### ISSUE TITLE
Incomprehensible error message

### ISSUE THREAD

**Issue by PavelVozenilek** [ziglang/zig#956]
I tried the Hello World example in the online tool.  Then I removed the first try keyword, and got very strange error.

```
const std = @import("std");

pub fn main() !void {
    var stdout_file = /* try */ std.io.getStdOut(); // <<-- here "try" was removed just to see what happens
    try stdout_file.write("Hello, world!\n");
}

```

results in:

```
/home/runner/.code.tio:8:20: error: type 'WindowsGetStdHandleErrs!File' does not support field access
/srv/wrappers/zig: line 4: ./.bin.tio: No such file or directory

```

which is doubly strange, as if it tries to use a Win32 function under an Unix OS.

--------------

Removing the second (and only the second) try results in error:

`/home/runner/.code.tio:5:22: error: expression value is ignored
`

Not especially helpful, either. Imagine a novice, he would be completely lost. The compiler should give  a hint what one could do there.

-------------------

And a note: the simpler Hello World example should be the first one. The one with "try"s has good chance to scare away newcomers.

That funny `!void` deserves a comment.

**Comment by Hejsil** [comment]
Or they could use `@import("std").debug.warn`. I don't think we should pollute the global namespace with stuff from `std`.

**Comment by andrewrk** [comment]
Fun fact, the only reason getStdOut can fail is due to it being a cross platform abstraction that includes windows. So it actually makes sense that the error set has windows in the name.

**Comment by PavelVozenilek** [comment]
@phase: use case for "frictionless" `echo` are beginners, people who learn by small examples. They do not want imports, namespaces or errors just to print out something. They are learning, not building nuclear-powerplant-grade software.

If they get impression of something overcomplicated, they will flee away.

**Comment by PavelVozenilek** [comment]
@Hejsil: echo would be useful for beginners and for ad-hoc debugging.  Not situations where complexity of the libraries is appreciated. Experienced programmer wouldn't build application from echo, and if he does, he deserves it.

Current io hierarchies remind me iostreams catastrophe of C++.  Grandiose design which fills a [book](https://dl.acm.org/citation.cfm?id=529146) and still no one understands it. Who needs this? It could be  specialised library mentioned in an appendix.  Exposing it in Hello World is unwise.

**Comment by andrewrk** [comment]
`echo` is rejected. case closed

**Comment by andrewrk** [comment]
* std.io.getStdOut no longer returns a possible error
 * `anyerror!void` is the recommended return type of main, and is more clear than `!void`
 * I'm certain there is another issue open for a better compile error message when attempting to use an error union in place of a regular value, but I do not have the link handy.
 * no echo
