### ISSUE TITLE
Translate C no longer inspects aliased types

### ISSUE THREAD

**Issue by fengb** [ziglang/zig#9570]
I'm pretty sure this used to work:
```c
typedef int i32;
#define cast1 ((i32)x)
#define cast2 ((i32)(x))
```

This is currently translating to:
```zig
pub const _DEBUG = @as(c_int, 1);
pub const cast1 = i32 ++ x;
pub const cast2 = i32(x);
```

**Comment by Vexu** [comment]
Broken by #9092, `i32` is no longer recognized as a type name.

**Comment by fengb** [comment]
Fixed by https://github.com/ziglang/zig/commit/be9b490f844277237bd0b60ba6120689723243b3 🎉
