### ISSUE TITLE
packed struct with large alignment fields breaks alignment

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#9588]
Example:
```zig
const std = @import("std");

const S = packed struct {
    x: u32 align(256),
};

pub fn main() void {
    var arr = [2]S { .{.x=123}, .{.x=456} };
    const slice: []S = &arr;
    std.debug.print("@typeInfo(@TypeOf(slice)).Pointer.alignment = {}\n", .{@typeInfo(@TypeOf(slice)).Pointer.alignment});
    std.debug.print("&slice[0] = {}\n", .{@ptrToInt(&slice[0])});
    std.debug.print("&slice[1] = {}\n", .{@ptrToInt(&slice[1])});
    std.debug.print("&slice[1] - &slice[0] = {}\n", .{@ptrToInt(&slice[1]) - @ptrToInt(&slice[0])});
}
```

Output:
```
$ zig run bug.zig
@typeInfo(@TypeOf(slice)).Pointer.alignment = 256
&slice[0] = 140736494345984
&slice[1] = 140736494345988
&slice[1] - &slice[0] = 4
```

So according to Zig the alignment for the `slice` in the example above is 256, but the difference between the first two elements is only 4, which means it's impossible for both of them to be aligned by 256.

Note that I believe this issue only occurs when `@alignOf(T) > @sizeOf(T)`.

Not sure what the right solution is here, maybe slices/pointers/arrays of packed structs need to have a different default alignment?  Or maybe Zig needs to make the `@sizeOf` types (even packed struct) >= `@alignOf`?

In any case, this situation violates the assumption that `@sizeOf(T)` is the distance between two elements of type `T` in a "naturally aligned" array.  So either this assumption is now incorrect, or we need to finegle with the definition of "natural alignment" for packed structs.

**Comment by Vexu** [comment]
Packed struct fields can't be aligned anymore.
