### ISSUE TITLE
Assertion fails when pointer casting to `*void`

### ISSUE THREAD

**Issue by Hejsil** [ziglang/zig#960]
```
test "" {
    var i = usize(0);
    var v = @ptrCast(*void, &i);
}
```

```
zig: zig/src/analyze.cpp:449: TypeTableEntry* get_pointer_to_type_extra(CodeGen*, TypeTableEntry*, bool, bool, uint32_t, uint32_t, uint32_t): Assertion `byte_alignment == 0' failed.
```

**Comment by andrewrk** [comment]
I'm not actually sure what this should do. Should it be a compile error? No-op?

The line that the assertion failure crashed on is asserting that a pointer to void (or anything with 0 size) has no alignment. But since we cast from a `*usize` the alignment is `8`, so the compiler panics.

**Comment by andrewrk** [comment]
Nevermind, I thought through it and I think it makes sense to work. See above commit for more details.

**Comment by thejoshwolfe** [comment]
a single-item pointer to a 0-size type is also a 0-size type. this should be a compile error at the `@ptrCast()` for an impossible cast.

**Comment by andrewrk** [comment]
No I don't think it should work from `*void` to `*usize`.
