### ISSUE TITLE
Make `zig build` show all compile errors before exit

### ISSUE THREAD

**Issue by locriacyber** [ziglang/zig#9615]
Currently, `zig build` only shows errors in the first function that has errors. This makes fixing compile errors time-consuming since I need to compile many times to fix all the bugs.

```
> zig version
0.9.0-dev.850+9e3ec9893
```

**Comment by Vexu** [comment]
Fixing the errors one by one is the intended workflow but it should become much less time consuming once tooling can use stage2's faster analysis.
