### ISSUE TITLE
make `usingnamespace` not put identifiers in scope

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#9629]
From status quo the proposed change is very small:

 * Keyword is renamed from `usingnamespace` to `includenamespace`.
 * It only mixes in to the set of declarations for a given namespace; it does not affect identifiers.

Example:

```zig
pub const Foo = struct {
    includenamespace Bar;

    test {
        _ = hello; // error: use of undeclared identifier
        _ = Foo.hello; // OK!
    }
};

pub const Bar = struct {
    pub const hello = "hello";
}
```

Why? What material benefit does this have? Turns out, it's actually a big deal for the design of an incremental compiler:

 * AstGen is the place where we report shadowing of identifiers and unused identifiers. It would make sense to also report error for use of undeclared identifier. However the existence of `usingnamespace` makes that not an option. Having this error in AstGen means that the compile error is available non-lazily. That is, you will see errors of this form even for code that does not get semantically analyzed. For example, on Windows you would still see "use of undeclared identifier" errors when building for macOS.

 * With status quo semantics, an identifier in scope of more than one `usingnamespace` forces *all* of them to be resolved, in order to make sure there are no name conflicts. However, using `a.b` syntax means only the `includenamespace` declarations that apply to `a` must be resolved. With incremental compilation, having an identifier force an unrelated `usingnamespace` to be resolved creates a dependency between these two things. This dependency costs perf, memory, and decreases the amount of encapsulation of changes - that is, **it makes an incremental update less incremental**. The `includenamespace` semantics reduce the amount of such dependencies.

**Comment by andrewrk** [comment]
I've been working on an implementation and the new AstGen error finds a lot of broken code in std:

```
/home/andy/dev/zig/lib/std/zig.zig:160:101: error: use of undeclared identifier 'suffix'
                return std.fmt.allocPrint(allocator, "{s}{s}{s}", .{ target.libPrefix(), root_name, suffix });
                                                                                                    ^
/home/andy/dev/zig/lib/std/hash_map.zig:612:29: error: use of undeclared identifier 'self'
            var other = try self.unmanaged.cloneContext(new_allocator, new_ctx);
                            ^
/home/andy/dev/zig/lib/std/json.zig:1409:17: error: use of undeclared identifier 'info'
            if (info.tag_type) |UnionTag| {
                ^
/home/andy/dev/zig/lib/std/fmt.zig:905:99: error: use of undeclared identifier 'value'
        @compileError("Unsupported format string '" ++ fmt ++ "' for type '" ++ @typeName(@TypeOf(value)) ++ "'");
                                                                                                  ^
/home/andy/dev/zig/lib/std/math/big/int.zig:678:37: error: use of undeclared identifier 'allocator'
        return gcdLehmer(rma, x, y, allocator);
                                    ^
/home/andy/dev/zig/lib/std/event/rwlock.zig:228:25: error: use of undeclared identifier 'Allocator'
fn testLock(allocator: *Allocator, lock: *RwLock) callconv(.Async) void {
                        ^
/home/andy/dev/zig/lib/std/crypto/25519/curve25519.zig:43:29: error: use of undeclared identifier 'Edwards25519'
    pub fn clearCofactor(p: Edwards25519) Edwards25519 {
                            ^
```

Seems pretty useful

**Comment by michal-z** [comment]
Just for information. I have restructured my code. I'm now using ```usingnamespace``` keyword only for 'mixing-in' methods from parent COM interfaces. I use proper namespaces instead of prefixes (dxgi.ISwapChain, d3d12.IDevice9, d3d11.IResource, d2d1.COLOR_F, etc.). Everything seems nice and clean.

```
// win32.zig
pub const base = @import("windows.zig");
pub const dwrite = @import("dwrite.zig");
pub const dxgi = @import("dxgi.zig");
pub const d3d11 = @import("d3d11.zig");
pub const d3d12 = @import("d3d12.zig");
pub const d3d12d = @import("d3d12sdklayers.zig");
pub const d3d = @import("d3dcommon.zig");
pub const d2d1 = @import("d2d1.zig");
pub const d3d11on12 = @import("d3d11on12.zig");
pub const wic = @import("wincodec.zig");
pub const wasapi = @import("wasapi.zig");

```

And one more place where I use ```usingnamespace``` is to add some basic windows stuff that Zig does not provide (like IUnknown COM interface):

```
// windows.zig
pub usingnamespace @import("std").os.windows;
pub usingnamespace @import("misc.zig");
```

**Comment by andrewrk** [comment]
After exploring what it would look like to implement usingnamespace with these semantics in self-hosted, as well as exploring what std lib changes would need to be made to adjust to these semantics, I'm confidently marking this as accepted.

@SpexGuy pointed out to me that this proposal also solves a design flaw that I ran into in self-hosted, because it allows AstGen to make note of all the ZIR instructions that are referenced inside any given Decl. This is a solution to a fundamental problem, unblocking progress on the self-hosted compiler.

**Comment by andrewrk** [comment]
See #9618 for an ongoing effort to implement this.

**Comment by Mouvedia** [comment]
> I'm happy with the name mixin

When you are talking about mixins, it's almost always accompanied with a custom merging strategy—and a default one.
I don't know if that would be useful there.

**Comment by andrewrk** [comment]
Implemented in 594271f8dba0143280990ac2e01dd68a791c05b0. The keyword rename can be a separate proposal.

**Comment by jibal** [comment]
How about calling it mixindeclarations ?

**Comment by windows-h8r** [comment]
Are all `includenamespace` declarations `pub`? I mean, what would be the point of a non-`pub` `includenamespace`?

**Comment by InKryption** [comment]
> Are all `includenamespace` declarations `pub`? I mean, what would be the point of a non-`pub` `includenamespace`?

```zig
pub const sub_namespace = struct {
    includenamespace @import("file1.zig");
    pub includenamespace @import("file2.zig");
};

comptime {
    _ = sub_namespace.private_decl;
}

``|
