### ISSUE TITLE
option to disable std.Progress.dont_print_on_dumb

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#9633]
`TERM=dumb` or otherwise that does not support the cursor moving ansi escape codes should still print, but have the items each print on their own line.

If the user decides they do not want the output to print they would still be free to do `zig build > /dev/null`.

**Comment by g-w1** [comment]
This is a useful feature. Lets say I want to see which tests ran, as a kind of a sanity check, I would do `❯ ./zig build test-stage2 -Dskip-compile-errors  2>&1 |less` I get this 
![image](https://user-images.githubusercontent.com/58830309/131250813-3b8da6c8-67bb-4041-88cf-95adf82e472b.png)
, but when I remove dont_print_on_dumb, the compilation progress shows, which is *very* annoying. Then you have to scroll down to see the actual useful information. 
![image](https://user-images.githubusercontent.com/58830309/131250901-0ab942f3-9164-4033-87f2-1925404402bf.png)

Compilation progress is only useful while compilation is going, not after. Which tests ran is useful after also.

Is this feature causing a problem for you? If not, I think we should keep it, as it improves the ui for me.

**Comment by nektro** [comment]
Yes, not seeing the compilation progress means im totally in the dark when using some CIs when `zig build` is running.
