### ISSUE TITLE
@mulWithSaturation discovered upstream llvm bug

### ISSUE THREAD

**Issue by travisstaloch** [ziglang/zig#9643]
The tests in #9619 revealed an llvm bug with the intrinsic llvm.smul.fix.sat.  This is shown below:

```zig
extern fn @"llvm.smul.fix.sat.i8"(i8, i8, i32) i8;
test "satmul" {
    const x = @"llvm.smul.fix.sat.i8"(-128, -128, 0);
    try std.testing.expectEqual(@as(i8, 127), x);
}
```
this produces.  
```console
Test [1/1] test "satmul"... expected 127, found -128
```
the expected result __is__ actually 127
`<LebedevRI> for scale=0, i would still say this is a bug`

Or using the @mulWithSaturation builtin
```zig
test "satmul" {
    const x = @mulWithSaturation(@as(i8, -128), @as(i8, -128));
    try std.testing.expectEqual(@as(i8, 127), x);
}
```

Using llvm ir
```ll
; test.ll
define i8 @main() {
entry:
  %res = call i8 @llvm.smul.fix.sat.i8(i8 -128, i8 -128, i32 0)
  ret i8 %res
}

declare i8 @llvm.smul.fix.sat.i8(i8, i8, i32)
```

Running the llvm ir
```console
clang-12 test.ll && ./a.out
echo $? # should be 127 but outputs 128 (-128 interpreted as u8 - 0x80)
```

**Comment by travisstaloch** [comment]
Created [bug report](https://bugs.llvm.org/show_bug.cgi?id=51677).  Let me know if i've forgotten anything.

**Comment by travisstaloch** [comment]
Proposed fix is up for review [here](https://reviews.llvm.org/D108938)

**Comment by andrewrk** [comment]
The fix made it into LLVM 13 which is now merged into master.
