### ISSUE TITLE
Documentation for the standard library

### ISSUE THREAD

**Issue by antoyo** [ziglang/zig#965]
Hi.
Is there any documentation for the standard library?
Thanks.

**Comment by andrewrk** [comment]
Hi antoyo

Here's the roadmap to get documentation for the standard library:
 * [ ] pointer reform (#770)
 * [ ] self hosted compiler (#89)
 * [ ] auto generated docs (#21)
 * [ ] improve std lib documentation with doc comments (this issue)

**Comment by markfirmware** [comment]
Without doc comments, will the doc processor still produce a structured presentation of struct’s, functions, etc? I think that would be helpful in the short term.

**Comment by andrewrk** [comment]
> Without doc comments, will the doc processor still produce a structured presentation of struct’s, functions, etc?

Yes absolutely and it will additionally show the inferred error sets, so you can see all the ways it is possible for a function to fail. There's a lot of helpful information a documentation generator can show even with no doc comments.

**Comment by andrewrk** [comment]
[This is now done](https://ziglang.org/documentation/master/std/). See https://github.com/ziglang/zig/issues/21#issuecomment-539735292 for the remaining issues.
