### ISSUE TITLE
zig wasm-ld cannot find wasi libc

### ISSUE THREAD

**Issue by folkertdev** [ziglang/zig#9653]
Zig has a version of wasi libc somewhere, but (to my knowledge) it can't be conveniently accessed when running `zig wasm-ld`. 
Not sure if this is possible, but it would be nice if the `-lc` flag just worked.

hacky workaround (thanks @g-w1 )

```
rm -r ~/.cache/zig
echo "pub fn main() void {}" > libc.zig
zig  build-exe libc.zig -target wasm32-wasi-none -lc
cd ~/.cache/zig
find . -name "libc.a"
``` 

should give the location of the `libc.a` file that can then be explicitly linked in.

**Comment by andrewrk** [comment]
`zig wasm-ld` is not intended to be used directly. I will note that it is not listed as one of the commands in `zig -h`.

Instead, use `zig build-exe` to link a WebAssembly program. If you don't want the `main` entry point then use `zig build-lib -dynamic`.
