### ISSUE TITLE
Construction of sentinel-terminated slices Is missing From the Language Reference

### ISSUE THREAD

**Issue by donaldcallen** [ziglang/zig#9680]
The Zig Learn document, in Chapter 1, mentions the following:

````
test "sentinel terminated slicing" {
 var x = [_:0]u8{255} ** 3;
 const y = x[0..3 :0]; } <<<<--------
````
Where is the slice  with terminating sentinal notation documented in the Language Reference? I don't believe it is, though I could have missed it. It also appears not to be in the Grammar.

**Comment by haze** [comment]
https://ziglearn.org is separate from the [actual language reference](https://ziglang.org/documentation/master)

That pattern is documented here: https://ziglang.org/documentation/master/#Sentinel-Terminated-Arrays and https://ziglang.org/documentation/master/#Sentinel-Terminated-Slices

**Comment by g-w1** [comment]
They are saying that ziglearn mentioned something that is not in the language reference.

**Comment by donaldcallen** [comment]
> https://ziglearn.org is separate from the [actual language reference](https://ziglang.org/documentation/master)

I understand that they are different documents. But both are documenting the same language and I don't expect to see a construct in ziglearn, which is intended as a tutorial, that does not appear in the Language Reference.

> 
> That pattern is documented here: https://ziglang.org/documentation/master/#Sentinel-Terminated-Arrays and https://ziglang.org/documentation/master/#Sentinel-Terminated-Slices

You are citing sections that discuss the array and slice *type* that are terminated by sentinel. The construct I am talking about *constructs* sentinel-terminated slice as a return value. You see the same thing in the std library in mem.zig in the span function:
````
       return ptr[0..l :s];
````
I don't believe this construct is documented in the Language Reference. At least I have not been able to find it.

**Comment by donaldcallen** [comment]
> They are saying that ziglearn mentioned something that is not in the language reference.

That is correct, exactly my point.

**Comment by haze** [comment]
I guess for me it was kindof implied that you could use the same slice syntax with the terminator but I agree that it's better to be explicit here

**Comment by donaldcallen** [comment]
On Fri, 3 Sept 2021 at 11:51, haze ***@***.***> wrote:

> I guess for me it was kindof implied that you could use the same slice
> syntax with the terminator but I agree that it's better to be explicit here
>
Yes. If it's part of the language, it ought to be in the Language Reference.
