### ISSUE TITLE
Error when enabling evented I/O on Linux

### ISSUE THREAD

**Issue by nextdimension** [ziglang/zig#9693]
Maybe I am doing something wrong(new to zig) but adding this line in my code:
` pub const io_mode = .evented;`

Causes the error:
zig/std/event/loop.zig:499:40: error: container 'std.os' has no member called 'EPOLLET'
                self.linuxWaitFd(fd, os.EPOLLET | os.EPOLLONESHOT | os.EPOLLOUT);

edit: Forgot to add, I'm using latest zig master ( built myself).
I see there was an old issue related to this in 2020, that is marked fixed.

**Comment by g-w1** [comment]
This is due to the recent usingnamespace changes.

**Comment by AliChraghi** [comment]
you can ask same questions in discord server. see https://github.com/ziglang/zig/wiki/Community

**Comment by g-w1** [comment]
This is not a question, its a bug.
