### ISSUE TITLE
Default values of a struct not being initialized

### ISSUE THREAD

**Issue by cookie-sandwich** [ziglang/zig#9694]
Sorry if this is a duplicate or an intended behavior, but I've run into an issue when struct's fields with default values aren't initialized when setting all remaining fields manually, instead of using anonymous struct literal.

Example:
```zig
const std = @import("std");

var t: i32 = 5;

const S = struct {
    i: i32,
    j: *i32 = &t,
};

pub fn main() !void {
    var s: S = undefined;

    s = .{ .i = 10 }; // a

    s.i = 10; // b

    std.debug.print("{}\n", .{s.j.*});
}
```

If line a gets commented, the program crashes because j is not initialized properly, otherwise it prints 5 as intended

**Comment by Vexu** [comment]
If line a is commented `s` is left undefined as you specified at the top of the function. `s.i = 10` does not touch `s.j` at all so it is still undefined and illegal to dereference.
