### ISSUE TITLE
Mutable parameters and captures

### ISSUE THREAD

**Issue by YohananDiamond** [ziglang/zig#9696]
This proposal aims to introduce a concept that, although maybe not commonly used, I believe would help in some situations without sacrificing a lot of consistency: mutable parameters / captures.

As an example I'll be presenting the `var ident: T` syntax to represent a mutable function paramete, but, as to be described later ahead, it's not the only syntax that could be used for this.

"Having mutable parameters" would be a way to mark a parameter (or capture) as mutable - not the original value (at callsite or the one passed as the expression to be captured), but the copy that is used in the function body / expression that uses the capture. As an example:

```zig
pub fn addTwo(var num: i32) i32 {
    num += 2;
    return num;
}

pub fn main() void {
    const x = 10;
    std.debug.print("{}\n", .{x});
    std.debug.print("{}\n", .{addTwo(x)});
    std.debug.print("{}\n", .{x});
}
```

This code would yield:

```
10
12
10
```

That means `func` doesn't mutate the `x` at the callsite - it mutates the copy of `x` that is sent to `addTwo`.

An equivalent with captures would be:

```zig
test {
    const val: ?i32 = 50;

    if (val) |var x| {
        x += 5;
        try std.testing.expect(x == 55);
    }
    try std.testing.expect(val == 50);
}
```

## Why?

My main rationale for this is to prevent scope pollution:

```zig
// before:
pub fn doSomethingWithX(x: i32) i32 {
    var x_ = x; // a new identifier (x_) is introduced here - now we need to worry with the existence of two similar identifiers in scope
    x_ += 50; // mutates the new identifier
    return x_; // if we accidentally forget the name and put `x` here, the result won't be the intended
}

// after:
pub fn doSomethingWithX(var x: i32) i32 {
    x += 50; // mutates the already-existing identifier
    return x;
}
```

When optimized, I believe both would result in the same code (since, in the "before" example, I think the `x` copy to `x_` would be ignored and `x` would be used instead) but, with mutable parameters we don't need to make the copy in the first place. It's a minor change but it may help the code to be more readable and prevent spelling mistakes.

### Accidental mutation of copied value instead of mutation of pointer

A misinformed programmer could write:

```zig
pub fn mutateVar(var v: i32) void {
    v += 10;
}

test {
    var x: i32 = 10;
    mutateVar(x);
    try std.testing.expect(x == 20); // this throws an error!
}
```

With the intent of mutating the `x` variable present in the callsite (the unnamed `test`).
That would be similar to nim's `var T` syntax:

```nim
proc mutateVar(v: var int32) =
  v += 10

var v: int32 = 10
mutateVar(v)
assert(v == 20) # it works here!
```

The same can be applied to captures and their capture-by-pointer syntax:

```zig
test {
    var x_opt: ?i32 = 10;
    if (x_opt) |*x| { // capture by pointer
        x += 10;
        try std.testing.expect(x.* == 20); // okay
    }
    try std.testing.expect(x_opt == 20); // okay
}

test {
    var y_opt: ?i32 = 10;
    if (y_opt) |var y| { // capture by copy, but the copy is mutable
        y += 10;
        try std.testing.expect(y == 20); // okay
    }
    try std.testing.expect(y_opt == 20); // error! y_opt is still 10
}
```

But since in this proposal the parameter received by `mutateVar` is a copy of the argument passed in its call and not an address to the original variable, it would not have the same outcome. To replicate Nim's `var T`, we already have `*T`.

I think to prevent this mistake the best way would be to error out when a variable is modified but its value is never read, but I think that should be discussed more fully in a separate proposal.

### Affecting the function signature

Having a `var` parameter should not affect the type of the function signature:

```zig
pub fn doSomethingWithX(var x: i32) void {}
pub fn doSomethingWithX2(x: i32) void {}

test {
    // Believe this should pass.
    try std.testing.expect(@TypeOf(doSomethingWithX) == @TypeOf(doSomethingWithX2));
}
```

But having the `var` keyword put in there might be misleading for the programmer reading the code.

To emphasize that the mutability of the parameter is an implementation detail (as in, the caller code does not need to know about it), this information could be moved somewhere else:

Maybe a keyword in the style of `callconv` to indicate a list of parameters that are mutable (`callconv` does affect the function signature, though...):

```zig
pub fn doSomething(x: i32, y: i32) void
    mutableparameters(x, y)
{
    // ...
}
```

Maybe a pseudo-statement right at the start of the function body:

```zig
pub fn doSomething(x: i32, y: i32) void {
    mutableparameters x, y;
    // ...
}

pub fn doSomething(x: i32, y: i32) void {
    @defMutableParameters(x, y);
    // ...
}

// Also compatible with captures!
// The name might not be that fitting here, though.
if (some_val) |x| {
    mutableparameters x;
    // ...
}
if (some_val) |x| {
    @defMutableParameters(x);
    // ...
}
```

I'm not really content with these solutions but I don't have any others in mind.
Maybe it's better to just use `var param: T` in the function body, and disallow its use in function signature types.

```zig
pub fn func(var param: T) void {} // ok
const FuncT: type = fn (var _: T) void; // error! `var` shouldn't be in there
```

### Preventing optimizations (or rather a specific one)

Note: I'm not well informed at all on the subject and it's mostly based on speculation, plus a little bit of information from I-don't-remember-where, so I might be completely wrong at this. Please correct me if that's the case.

It seems there is a kind of optimization where parameters in function calls can be replaced with pointer variations of them. For example:

```zig
pub fn func(x: SomeBigType) void { ... }
```

Here, `@sizeOf(SomeBigType)` might be a really big value, and, if no mutation is done on it (it should not be done - `x` is a constant), the optimizer might decide to change the signature of the function to a const pointer, and thus `func` would become:

```zig
pub fn func(x: *const SomeBigType) void { ... }
```

Someone may argue that adding `var` parameters may be an issue for this optimization, since it wouldn't be possible anymore - or else it'd potentially mutate the data at the callsite.
But, without `var` parameters, we would have to make a copy anyway:

```zig
pub fn func(x: SomeBigType) void {
    var x_copy = x.*;
    // mutate x_copy...
}
```

### `const` parameters

If we decide to use the `var` syntax, what about functions with immutable parameters? Would we be able to put `const` in them?
If not, that could be an inconsistency.

I personally think it's better to have an inconsistency here to enforce the usual constness without having to be verbose:

```zig
pub fn func(param: i32) void {} // ok: const param
pub fn func(var param: i32) void {} // ok: var param
pub fn func(const param: i32) void {} // not allowed
```

To make this more robust the compiler could report when `const` is used and indicate there's no need to put it in there.

**Comment by luehmann** [comment]
I personally don't thinks this is necessary and I cannot come up with a good enough example for the argument of name collision, where there wouldn't be two reasonable names. More importantly I feel this isn't following the zen of Zig.

**Comment by InKryption** [comment]
In this snippet, where you explain your rationale:
```zig
pub fn doSomethingWithX(x: i32) i32 {
    var x_ = x;
    x_ += 50; // mutates the new identifier
    return x_;
}
```
couldn't the problem be better solved by just using a better naming scheme? E.g., using non-similar names, which would eliminate the issue:
```zig
pub fn doSomethingWithX(x: i32) i32 {
    var output = x;
    output += 50; // mutates the new identifier
    return output;
}
```
I personally don't think this is a big enough problem to warrant introducing a new capture syntax. From my perspective, I think it would make code harder to reason about, since when I look at an identifier in a function, I'd have to go back and check if it was a captured mutable variable or just a normal parameter; which was actually one of my gripes in C++, where a parameter could be a mutable reference, or a normal variable, although this is not as egregious.

**Comment by YohananDiamond** [comment]
Hmm, that's fair. Not sure if it's really worth the hassle either, specially with the lot of confusion and questionable design choices (talking about the `const` part I mentioned) that might come with it.
I'll still let the issue open for a while for more thoughts on the matter.

**Comment by marler8997** [comment]
I agree that "scope pollution" can lead to errors.  Not sure if this is the best solution we can come up with for that problem.  One idea I've had in the past is exploring the ability to remove symbols from the current scope.

For example, say we added a builtin named `@hide` that removes a symbol from the current scope.  Maybe it also returns the current value so your example could become this:

```zig
pub fn doSomethingWithX(x: i32) i32 {
    var mutable_x = @hide(x);
    mutable_x += 50;
    return mutable_x;
}
```

Now if you accidently use `x` further down you'd get a compiler error: "symbol `x` cannot be used here because it has been hidden".

I haven't really seen this kind of feature in other languages so I'm not sure what all the pros/cons would be, but might be interesting to explore.

**Comment by InKryption** [comment]
@marler8997 I was thinking about scopes and scope pollution recently, and I remembered your idea about a `@hide` builtin to manually end the scope of a variable, and I think it actually has the potential to address a myriad of problems. I think it would be worth opening a separate proposal for it. Would you be willing to do so? If not, I could try and put something together myself.

**Comment by marler8997** [comment]
@InKryption  you have my blessing you create a proposal.

**Comment by Validark** [comment]
Instead of having parameters be implicitly `const` by default and disallowing the `const` keyword and having opt-in `var` semantics, I'd rather have parameters look like any other variable declaration:
```zig
pub fn func(var param: i32) void {}
pub fn func(const param: i32) void {}

if (some_val) |var x| {
    // ...
}

if (some_val) |const x| {
    // ...
}
```
