### ISSUE TITLE
AstGen: Incorrect 'undeclared identifier' reporting inside test scope

### ISSUE THREAD

**Issue by Luukdegram** [ziglang/zig#9699]
Currently, the following snippet results in an error produced by astgen:
```zig
test {
    const Foo = struct {
        fn bar(self: Foo) void {
            _ = self;
        }
    };
    _ = Foo;
}
```
Results in:
```
src/test.zig:3:22: error: use of undeclared identifier 'Foo'
        fn bar(self: Foo) void {
                     ^
```

From my understanding, this should work fine as declaring `Foo` inside another container (but outside a test) seems to work.

**Comment by Vexu** [comment]
This is intended behavior `Foo` is not yet visible inside the initializer. This works at container level since the declarations are declared before they're analyzed to make them order independent.

**Comment by Luukdegram** [comment]
My bad. Thanks for the clarification, Vexu.
