### ISSUE TITLE
regression after usingnamespace changes - termios broken when using pThreads

### ISSUE THREAD

**Issue by edt-xx** [ziglang/zig#9707]
It is no longer possible to use termios

/usr/lib/zig/std/os.zig:156:27: error: container 'std.c' has no member called 'termios'
pub const termios = system.termios;

**Comment by sagehane** [comment]
`std.c.termios` was renamed to `std.os.termios` as of https://github.com/ziglang/zig/commit/c05a20fc8c36742dab8792d15e79716da1a55759. Hope that addresses your concern.

**Comment by edt-xx** [comment]
That does not solve the problem.   Building outwith pThreads I get (the
errors in Condition.zig are expected):

/home/ed/zig/zbox/src/prim.zig:242:24: error: container 'std.os' has no
member called 'ISIG'
   termios.lflag |= os.ISIG;
                      ^
/home/ed/zig/zbox/src/prim.zig:151:32: error: container 'std.os' has no
member called 'winsize'
   var winsize = mem.zeroes(os.winsize);
                              ^
/home/ed/zig/zbox/src/prim.zig:199:11: error: container 'std.os' has no
member called 'tcflag_t'
       os.tcflag_t,
         ^
/usr/lib/zig/std/Thread/Condition.zig:154:14: error: no member named
'unlock' in struct 'std.Thread.Mutex'
       mutex.unlock();
            ^
/usr/lib/zig/std/Thread/Condition.zig:130:30: error: container
'std.os.linux' has no member called 'FUTEX_PRIVATE_FLAG'
                       linux.FUTEX_PRIVATE_FLAG | linux.FUTEX_WAKE,

Looks like flags are missing in std.os.  When building with pThreads I get:

/usr/lib/zig/std/os.zig:157:27: error: container 'std.c' has no member
called 'termios'
pub const termios = system.termios;
                         ^
/home/ed/zig/zbox/src/prim.zig:309:25: note: referenced here
   original_termios: os.termios = undefined,
                       ^
/home/ed/zig/zbox/src/prim.zig:229:20: note: referenced here
   const handle = state().tty.in.context.handle;
                  ^
/home/ed/zig/zbox/src/prim.zig:151:32: error: container 'std.os' has no
member called 'winsize'
   var winsize = mem.zeroes(os.winsize);

Now std.os.zig is getting an error with std.c missing a member and again it
looks like std.os is missing fields.

My program uses zbox ( https://github.com/jessrud/zbox ) with fixes below
applied.  Its possible that more changes are needed in zbox but,
atleast to me, it looks like zig has a problem with termios when using
pthreads and std.os is missing some fields.  Please let me know if I am
mistaken.

Thanks
Ed

diff --git a/src/box.zig b/src/box.zig
index 72c380a..08ca207 100644
--- a/src/box.zig
+++ b/src/box.zig
@@ -329,6 +329,8 @@ pub const Buffer = struct {
        options: std.fmt.FormatOptions,
        writer: anytype,
    ) @TypeOf(writer).Error!void {
+        _ = fmt;
+        _ = options;
        var row_num: usize = 0;
        try writer.print("\n\x1B[4m|", .{});

diff --git a/src/prim.zig b/src/prim.zig
index c809f78..8cef838 100644
--- a/src/prim.zig
+++ b/src/prim.zig
@@ -1,3 +1,8 @@
+//! the primitive terminal module is mainly responsible for providing a
simple
+//! and portable interface to pseudo terminal IO and control primitives to
+//! higher level modules. You probably shouldn't be using this directly
from
+//! application code.
+
const std = @import("std");
const fs = std.fs;
const os = std.os;
@@ -11,11 +16,6 @@ const Allocator = mem.Allocator;

usingnamespace @import("util.zig");

-//! the primitive terminal module is mainly responsible for providing a
simple
-//! and portable interface to pseudo terminal IO and control primitives to
-//! higher level modules. You probably shouldn't be using this directly
from
-//! application code.
-
/// Input events
pub const Event = union(enum) {
    tick,
@@ -150,9 +150,9 @@ const TermSize = struct { height: usize, width: usize
};
pub fn size() os.UnexpectedError!TermSize {
    var winsize = mem.zeroes(os.winsize);
    const err = os.system.ioctl(state().tty.in.context.handle,
os.TIOCGWINSZ, @ptrToInt(&winsize));
-    if (os.errno(err) == 0)
+    if (os.errno(err) == .SUCCESS)
        return TermSize{ .height = winsize.ws_row, .width = winsize.ws_col
};
-    return os.unexpectedErrno(err);
+    return os.unexpectedErrno(os.errno(err));
}

/// Hides cursor if visible
@@ -291,7 +291,7 @@ pub fn nextEvent() (Allocator.Error ||
ErrorSet.TtyRead)!?Event {
        }
    }
    const event = parseEvent();
-    debug("event: {}", .{event});
+    std.log.debug("event: {}", .{event});
    return event;
}

**Comment by sagehane** [comment]
I don't quite get what you're trying to do, but this part seems solvable:
```
/home/ed/zig/zbox/src/prim.zig:242:24: error: container 'std.os' has no member called 'ISIG'
   termios.lflag |= os.ISIG;
                      ^
/home/ed/zig/zbox/src/prim.zig:151:32: error: container 'std.os' has no member called 'winsize'
   var winsize = mem.zeroes(os.winsize);
                              ^
/home/ed/zig/zbox/src/prim.zig:199:11: error: container 'std.os' has no member called 'tcflag_t'
       os.tcflag_t,
         ^
```
>Looks like flags are missing in std.os (think they are moved to std.os.linux).

Yep, that seems correct.
Looking at https://github.com/ziglang/zig/blob/master/lib/std/os.zig#L55,
`std.os.system` should provide the members you're looking for.

The other errors seem unrelated to this issue?

**Comment by edt-xx** [comment]
The program, pre usingnamespace chanages, was buillt with pThreads.  Now doing so causes errors in std.os.zig at line 157 where it uses system.termios.  With pThreads it has system set to std.c.  Previously using pThreads or not did not affect termios.

**Comment by layneson** [comment]
I am running into what I believe is the same issue. When using `std.os.termios` on Linux without linking libc, `std.os.system` is set to `std.os.linux`. However, when linking libc, `std.os.system` is set to `std.c.linux`, which does not contain a definition for `termios` (and some other related things, such as `TCSA`). I believe this is just an issue where someone missed porting some definitions from  `std.os.linux` to `std.c.linux`.
