### ISSUE TITLE
Bug in 0.8.1 compiler?

### ISSUE THREAD

**Issue by HugoFlorentino** [ziglang/zig#9708]
I was playing with Zig and tried to build this with `release-safe` to see what would happen:

```
pub fn main() anyerror!void {
    var buf: [1024*1024*1024*1024]u8 = undefined;
}
```

I expected some kind of runtime error notifying about insufficient memory, but received this instead at compilation:

```
Assertion failed at /home/andy/dev/bootstrap-zig/zig/src/stage1/codegen.cpp:3885 in gen_undef_init. This is a bug in the Zig compiler.thread 10576 panic:
Unable to dump stack trace: debug info stripped
```

**Comment by matu3ba** [comment]
Can you rename the issue to something like "stage1: stack exhaustion creates meaningless error" ? "Bug in compiler" is not very descriptive.

**Comment by Vexu** [comment]
This is caused by #1424 as `@truncate(u32, @as(usize, 1024*1024*1024*1024)) == 0`.
