### ISSUE TITLE
zig cc ubsan

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#9709]
Right now `zig cc` uses the following options.

```
-fsanitize=undefined -fsanitize-trap=undefined
```

This enables ubsan (undefined behavior sanitization) which means at runtime the program will check for undefined behavior.  The `-fsanitize-trap=undefined` option is used when the sanitizer runtime is unavailable, and seems to result in "illegal instruction" errors rather than nice easy-to-debug panics (i.e. https://github.com/ziglang/zig/issues/9701).

I propose that Zig implement or include the ubsan runtime and by default have it print stack traces like a normal zig panic would do.

**Comment by alexrp** [comment]
#5163
