### ISSUE TITLE
Function arguments ownership semantics (move?)

### ISSUE THREAD

**Issue by ramirezalbert3** [ziglang/zig#9714]
Hi, absolute zig beginner here, I've been fiddling with it for some days now (and I'm loving it, awesome work), and I've got a question (I guess, maybe proposal? although I'm not sure it fits with zig philosophy of not adding too many features, which I fully support). I hope I'm also not asking something it's already been asked before, but I've been searching a bit and couldn't find anything.

Like the title says, the question is basically around **ownership semantics for arguments to functions, specially "allocated stuff"**, for example:

```
test "ownership into functions" {
    const allocator = testing.allocator;

    const slice = try allocator.alloc(u8, 10);
    // defer allocator.free(slice); // PROBLEM: this would be double-free!

    var list = std.ArrayList(u8).fromOwnedSlice(allocator, slice);
    defer list.deinit();

    slice[0] = 127; // still can access memory with slice (which here is okay-ish actually)
    std.debug.print("this is still my slice {any}", .{slice});
}
```

My question is if there's any **"best practice" to "transfer ownership" of this allocated memory**, because in the example it is be very easy to double free the memory (as an example of things that can go wrong when you no longer own the data), and it is **not always obvious to library users who owns the data** (and is responsible for freeing the memory) after calling functions like `fromOwnedSlice` (without reading docs). 
I'm writing a toy-library to handle sparse matrices (pure zig learning exercise) and I can't get my head around which would be the best way to handle these situations.

I think it would be very convenient if **library authors could just make it clear in the code that the ownership is transferred in the function signatures**, probably enforced by the compiler. I don't think I've got the expertise make a case for any "proposal" properly, and there are probably better ways of doing this, here is what I think would be nice:

`pub fn fromOwnedSlice(allocator: *Allocator, slice: Slice) Self`

could be something like

`pub fn fromOwnedSlice(allocator: *Allocator, slice: move Slice) Self` (more or less like c++ `&&`).

`move` could be a keyword (same place as `const` would be for example), then the compiler should be able to "guide" the library user and the snippet above would yield something like.

```
test "ownership into functions" {
    const allocator = testing.allocator;

    const slice = try allocator.alloc(u8, 10);
    
    // CHANGED: this should be a compiler error, deferring something that's later moved
    // I can't see this being easy to detect though
    // defer allocator.free(slice);
    
    var list = std.ArrayList(u8).fromOwnedSlice(allocator, slice);
    defer list.deinit();

    // CHANGED: these would definitively be a compiler error, slice has been "moved"
    // more or less like Rust use after move
    // slice[0] = 127; 
    // std.debug.print("this is still my slice {any}", .{slice});
}
```

However, I can see the "move idea" complicating a lot of situations (which are already pretty problematic) like:

```
test "ownership into functions" {
    const allocator = testing.allocator;

    var arr = [_]u8{ 1, 2, 3, 4 };
    var list = std.ArrayList(u8).fromOwnedSlice(allocator, arr[0..]); // how would you "move" this?
    // defer list.deinit(); // don't do this
}
```

and I must admit I haven't thought properly what the effects would be for other `types`. I'm sure this opens the door to many issues I just can't see coming.

I guess also being able to "move" data would also open the door to many other optimizations too, but that's not the problem I'm trying to solve so I'm definitively not trying to make a case for this :)

Sorry if this was too long, and again thanks a lot for the really cool language, it's a lot of fun (and surprisingly easy) to use!

**Comment by Vexu** [comment]
As pointed by your third example, this is too complex of a feature to be added to Zig. There also already is a simple pattern to handle situations like this used in the self-hosted compiler:
```zig
test "ownership into functions" {
    const allocator = testing.allocator;

    var own_slice = true;
    const slice = try allocator.alloc(u8, 10);
    defer if (own_slice) allocator.free(slice); // no problem here

    var list = std.ArrayList(u8).fromOwnedSlice(allocator, slice);
    own_slice = false;
    defer list.deinit();

    slice[0] = 127; // accessing slice is valid until list is resized
    std.debug.print("this is still my slice {any}", .{slice});
}
```
More examples can be found with `grep "defer if" src/*.zig`.

**Comment by ramirezalbert3** [comment]
ok thanks for pointing me in the right direction, I'll check that out.
