### ISSUE TITLE
proposal: `error sets 'A' and 'B' have no common errors` should not be a compile error

### ISSUE THREAD

**Issue by nektro** [ziglang/zig#9732]
code
```zig
const std = @import("std");

pub fn main() void {
    foo() catch |err| {
        std.debug.assert(err != error.B);
    };
}

fn foo() !void {
    return error.A;
}
```

expected
- comptime-true value being sent to `std.debug.assert`.

current behavior:
```
./test.zig:5:30: error: error sets '@typeInfo(@typeInfo(@TypeOf(foo)).Fn.return_type.?).ErrorUnion.error_set' and 'error{B}' have no common errors
        std.debug.assert(err != error.B);
                             ^
```

This is a simplified but I ran up against this in a function that accepts multiple functions as arguments and handles a certain error differently (that is only present in some of the arguments) causing this compiler error to arise.

however, given that this is a simple test (in an `if` statement in my case) and not a `switch`, i expected it to evaluate to a comptime known true/false value rather than produce an error.

**Comment by g-w1** [comment]
Just do @as(anyerror
```zig

const std = @import("std");

pub fn main() void {
    foo() catch |err| {
        std.debug.assert(@as(anyerror, err) != error.B);
    };
}

fn foo() !void {
    return error.A;
}
```

**Comment by nektro** [comment]
That worked, thanks :+1:
