### ISSUE TITLE
[proposal] Keep logical expression operators consistent with C

### ISSUE THREAD

**Issue by dophist** [ziglang/zig#9739]
## Proposal
Keep `&&` and `||` semantics the same as C. Employ new operators for Zig's new concepts(say, ErrorSet Merging).

## Benefits
(`&&`, `||` and `!`) are just a group of widely accepted operators by old programmers, just like their modern equivalent group(`and`, `or`, `not`) in most scripting languages such as python, ruby.

This basically makes Zig's control flow super friendly to existing C programmers, "I already know the core parts of this language, and what I need to learn is to embrace a few new concepts upon C" is conceptually powerful for language adoption after Zig 1.0.

Let alone there are already some error messages like "Please use `and` instead of`&&`, `or` instead of `||` for logical expressions" in the codebase, are these things really necessary or there are some historical reasons for this design?

I know this might be too cosmetic to be cared about at this moment but I see this kind of stuff has huge mental impact for early-stage language adoption, ignore me if this doesn't make sense to the community.

Really love the zen of zig, I see great potential for this language in bare metal and high performance computing. Really hope it can thrive as a simple solution for all kinds of complex problems.  People don't honor simplicity as old days, and that's wrong.

**Comment by daurnimator** [comment]
The zig language always uses keywords for things that may cause control flow. Note that `and`/`&&` have control flow due to short-circuit logic.

**Comment by dophist** [comment]
Oh, my bad, actually this is not a topic on control flow, it's a problem of boolean expression. 

`not`, `and` and `or` are standard operations on boolean logic from a mathematical point of view.  If we see keywords and operators as two distinct categories, so my argument is that we are mixing keywords(`and` `or`) and operator(`!`) for boolean logic operations, which is kind of inconsistent.

So my point is, either choosing a group of
```
(`not`, `or`, `and`)  # consistent with most of modern dynamic languages
```
or a group of
```
(`!`, `||`, `&&`)  # consistent with old style C
```
would all be more concise and clear.

**Comment by Vexu** [comment]
`!` does not do control flow. Changing it would make the boolean logic more consistent but make the use of keywords for control flow more inconsistent.

**Comment by dophist** [comment]
> `!` does not do control flow. Changing it would make the boolean logic more consistent but make the use of keywords for control flow more inconsistent.

Fair enough. Closing this issue to save people's time. Many thanks.
