### ISSUE TITLE
Std lib functions for all undefined behavior in the docs

### ISSUE THREAD

**Issue by Hejsil** [ziglang/zig#974]
Just like we have `std.math.add` which, instead of panicking on overflow, returns an error, I think we should have functions to handle undefined behavior for other things than just math.

Here is my, not very comprehensive, list of what I think could be useful in `std`:
* `mem.at(items: var, index: usize) (error{OutOfBounds}!@typeOf(&items[0]))`
    * Takes an array or slice, and returns a pointer to the item at `index`
    * If `index >= items.len` then it returns `error.OutOfBounds`
* `mem.slice(items: var, start: usize, end: usize) (error{OutOfBounds,EndLessThanStart}!@typeOf(items[0..]))`
    * Takes an array or slice, and returns `items[start..end]`
    * If `start > items.len or end > items.len` then it returns `error.OutOfBounds`
    * If `end < start` then it returns `error.EndLessThanStart`
* `mem.widen(slice: var, comptime Out: type) (error{SizeMismatch}![]Out)`
    * Takes a slice and returns `([]Out)(slice)`. (TODO: we want to return `[]const Out` if `slice` is const)
    * If `slice.len % @sizeOf(Out) != 0`then it returns `error.SizeMismatch`
* `union.field(uni: var, comptime name: []const u8) (error{InactiveField}!@typeOf(@typeOf(&@field(uni, name))))`
    * Takes any union with a tag field and returns `&@field(uni, name))`
    * If field is inactive then it return `error.InactiveField`

**Comment by Hejsil** [comment]
Or like this:
```
comptime {
    const Child = SliceType.Child;
    if (SliceType == []Child) return []CastedType;
    if (SliceType == []const Child) return []const CastedType;

    @compileError("Expected slice, found " ++ @typeName(SliceType));
}
```

The point of this issue is mostly to figure out all of these function kinds of functions.

**Comment by alexnask** [comment]
Good point :P

**Comment by andrewrk** [comment]
I think this makes sense. We might have to convince @thejoshwolfe that there are any Real Actual Use Cases for these functions.

**Comment by Hejsil** [comment]
For `at`, `slice`, and `widen`, the randomizer is my use-case. I have to deal with:
* An array of trainers, each of which has an index as a field into an array of parties (`at`)
* The nds has a file system, where each files data might be things like a Pokémon (`widen`)
* The gba roms, I read in all the data, and slice it up into data sections where I know relevant data exists (`slice`)

If one of these things are not right, it is not a bug on my end, but a malformed rom that I need to report to the user.

**Comment by thejoshwolfe** [comment]
I think we're actually talking about "language level assertions" not "undefined behavior". When safety is enabled, violating a language level assertion is not always undefined behavior; the behavior is often that it calls `panic()`.

There are cases when you'll get undefined behavior that zig isn't checking for, like doing something crazy in an `@asm()` block, or violating type safety with `@intToPtr()`. There's no way to check for all undefined behavior, so we have to narrow the scope of this proposal a bit.

Regarding Real Actual Usecases, I think we should propose each new addition to the std library individually with individual justification. This idea of having an implementation for "all undefined behavior" is not an attainable goal. I don't even think we should try to have as much as possible. I think each function needs to have its own reason to exist.

> ... the randomizer is my use-case.

Sounds like we're on track for some solid proposals.

**Comment by thejoshwolfe** [comment]
> propose each new addition to the std library individually

To clarify, I don't mean each in its own PR. I mean that we should be justifying functions, not entire categories of functions.

**Comment by Hejsil** [comment]
@thejoshwolfe Yes, language level asserts was actually what I meant we wanted `std` alternatives that return errors instead of asserting :)

As for individual issues, I could rename this proposal to `Alternatives to at, slice and widen in the std that returns errors instead of asserting`, as they basically cover the use-case of "slice operations returning errors instead of asserting", which is my motivation for this issue. The union field access we can then put in some other issue.

**Comment by Mouvedia** [comment]
@Hejsil have you created an issue for each? If so, can this issue be closed?

As @thejoshwolfe said, it's "not an attainable goal".
i.e. it shouldn't have been filled because it cannot be resolved
