### ISSUE TITLE
Can I use zig even if I don't agree with its CoC ?

### ISSUE THREAD

**Issue by inoshy** [ziglang/zig#9757]
I am not bothering to join any zig community. but just asking, can I still use it for open source and closed source project?

**Comment by Aransentin** [comment]
Yeah. The Code states that it only applies to any discussion here on the official Github repos, or the #zig IRC channel on Libera.chat.

Even so, Zig is MIT licensed. The CoC doesn't change that; even if somebody were banned from everywhere it wouldn't prevent them from being able to use the software itself or making other programs with it.

**Comment by inoshy** [comment]
> Yeah. The Code states that it only applies to any discussion here on the official Github repos, or the #zig IRC channel on Libera.chat.
> 
> Even so, Zig is MIT licensed. The CoC doesn't change that; even if somebody were banned from everywhere it wouldn't prevent them from being able to use the software itself or making other programs with it.

Thanks very much :)
