### ISSUE TITLE
std.ArrayList: difference between initCapacity and ensureTotalCapacity

### ISSUE THREAD

**Issue by squeek502** [ziglang/zig#9775]
Currently, `std.ArrayList` does two different things when called with `initCapacity` vs being called with `init` and then calling `ensureTotalCapacity` afterwards:

https://github.com/ziglang/zig/blob/19691c0b174f283ffe5b6c3fe8533ef458736064/lib/std/array_list.zig#L60-L73

https://github.com/ziglang/zig/blob/19691c0b174f283ffe5b6c3fe8533ef458736064/lib/std/array_list.zig#L323-L340

I'm unsure about why this would be, or if there's any reason why `initCapacity` isn't implemented as

```zig
        pub fn initCapacity(allocator: *Allocator, num: usize) !Self {
            var self = Self.init(allocator);
            try self.ensureTotalCapacity(num);
            return self;
        }
```

**Comment by rohlem** [comment]
I suspect that the non-initial capacity methods are meant to be efficient, even if called repeatedly.
If you call it with several random sizes, growing by a factor (here by more than x0.5) gives exponential growth, reducing the number of reallocations to be logarithmic.

In contrast, you only ever initialize the list once, so we never get around that single first allocation.
Imagine you have a fixed buffer of N bytes, and never grow the list. You can exactly calculate how many elements will fit into it, and don't want the list to calculate a different number. In that situation, the adaptive growth isn't helpful.

This is just speculation though. I didn't write the code. If my thinking is right it would be helpful to document these intentions.

**Comment by squeek502** [comment]
That makes sense, I didn't realize that the array size grows relative to its current size (i.e. if current capacity is 62, it will grow to 101, but if current capacity is 63 then it will grow to 102) rather than working like a fixed step (i.e. how the hash map will step up to the next power of two). So, in this case, the starting value is not relevant to avoiding inefficient growth (so there's no real benefit to `initCapacity` calculating a `better_capacity` and then using that).

The duplicate code can still be avoided, though, by splitting `ensureTotalCapacity` into parts (calculate better capacity, and the actual growth) and then having `initCapacity` use only the growth part while `ensureTotalCapacity` uses both. I'll make a PR with that option as well.

**Comment by squeek502** [comment]
> The duplicate code can still be avoided, I'll make a PR with that option as well.

On second thought, I think it's fine as it is. Maybe a doc comment would be helpful, but mostly I just misunderstood what `better_capacity` was doing.

**Comment by squeek502** [comment]
On third thought, there might be a use case for a more precise version of `ensureTotalCapacity` outside of `initCapacity`. An example can be found here:

https://github.com/ziglang/zig/blob/6d37ae95edc06f15e4e77f64e8e637dd5d269183/lib/std/coff.zig#L276-L316

where the actual exact required capacity is known (unless I'm misunderstanding the code), so using `ensureTotalCapacity` will over-allocate for no reason. However, it seems like maybe this is an unnecessary use of an ArrayList, where allocating a normal slice would be more appropriate.

**Comment by squeek502** [comment]
And on the flip side, it's surprisingly common (non-exhaustive examples: [1](https://github.com/ziglang/zig/blob/dc9d76b630e0fe9a465cec67dc4dc66e8cce7c58/src/Compilation.zig#L3587-L3588), [2](https://github.com/ziglang/zig/blob/dc9d76b630e0fe9a465cec67dc4dc66e8cce7c58/src/libcxx.zig#L110-L111), [3](https://github.com/ziglang/zig/blob/dc9d76b630e0fe9a465cec67dc4dc66e8cce7c58/src/main.zig#L2785-L2786), [4](https://github.com/ziglang/zig/blob/dc9d76b630e0fe9a465cec67dc4dc66e8cce7c58/src/link/Elf.zig#L854-L859), [5](https://github.com/ziglang/zig/blob/dc9d76b630e0fe9a465cec67dc4dc66e8cce7c58/lib/std/unicode.zig#L555-L558)) throughout the Zig codebase (and especially in the self-hosted compiler) to do:
```zig
var list = std.ArrayList(T).init(allocator);
try list.ensureTotalCapacity(size);
```
instead of
```zig
var list = try std.ArrayList(T).initCapacity(allocator, size);
```
If this is an intentional choice, then it seems like there might be a use case for a less precise `initCapacity` that uses `better_capacity`, or at least a doc comment explaining why you might want to do separate `init`/`ensure` calls instead of using `initCapacity`.

**Comment by rohlem** [comment]
I'm not sure why your numbers match page size at some point, shouldn't it stay the upper limit, i.e. go to 3063, 6911, 10374?
Anyway, I would guess that those sizes aren't special in any way, and just a result of the algorithm. (Otherwise their importance should really be documented.)

I also think the `.init` -> `.ensureTotalCapacity` pattern is just an oversight, since `init` is the common name for initializer methods. (I for one didn't notice `initCapacity` existed before reading this issue).
Especially in the places you've linked that exclusively call `-AssumeCapacity` methods afterwards, the overallocated elements (and potential growth behaviour) are unreachable, which makes them appear unintentional to me.

**Comment by squeek502** [comment]
> I also think the .init -> .ensureTotalCapacity pattern is just an oversight

Definitely possible. To me it seems there are three options:

1. Assume all 'precise' usages of `initCapacity` are unnecessary, and make `initCapacity` calculate `better_capacity`. This means all capacity allocations would possibly over-allocate even for small sizes
2. Assume all usages of `init`/`ensureTotalCapacity` combinations are unintentional, and update them all to use `initCapacity`
3. Assume both 'precise' and 'imprecise' capacities have a use-case, and add functions like `initCapacityPrecise`/`ensureTotalCapacityPrecise`/`ensureUnusedCapacityPrecise` while making `initCapacity` use the better_capacity calculation. This would allow the caller to choose which version they wanted, while making the 'default' use better_capacity in both `init` and `ensure` (i.e. the example in https://github.com/ziglang/zig/issues/9775#issuecomment-921340478 could use `ensureTotalCapacityPrecise` and the examples in https://github.com/ziglang/zig/issues/9775#issuecomment-921397872 could choose between `initCapacity` and `initCapacityPrecise` depending on their use case).

> I'm not sure why your numbers match page size at some point, shouldn't it stay the upper limit, i.e. go to 3063, 6911, 10374?

Both `initCapacity` and `ensureTotalCapacity` tell the allocator that they want *at least* the desired capacity, and it looks like at a certain point the allocator starts actually giving oversized allocations back. I was running a (sloppy, very inefficient) test with real allocations:

```zig
test "better capacity real" {
    var size: usize = 0;
    var prev_cap: ?usize = null;
    while (size < 100000) : (size += 1) {
        var list = ArrayList(u8).init(testing.allocator);
        defer list.deinit();

        try list.ensureCapacity(size);

        if (prev_cap == null) {
            const start = if (size == 0) size else (size - 1);
            std.debug.print("{}...", .{start});
            prev_cap = list.capacity;
        } else if (prev_cap.? != list.capacity) {
            std.debug.print("{} => {}\n", .{ size - 1, prev_cap.? });
            prev_cap = null;
        }
    }
}
```

When run with just the better_capacity algorithm and no allocations, it looks more normal, e.g.:
```
3064...4602 => 4602
4603...6911 => 6911
6912...10374 => 10374
```

Interestingly, `initCapacity` doesn't quite follow the same pattern as `ensureTotalCapacity` once it hits page-size allocations though:

```
2049...4096 => 4096
4097...8192 => 8192
8193...12288 => 12288
12289...16384 => 16384
```

This is presumably due to differences in `reallocAdvancedWithRetAddr` (via `reallocAtLeast`) in `ensureTotalCapacity` vs `allocAdvanced` in `initCapacity`

**Comment by squeek502** [comment]
Ok, I think I've come to some conclusions after pretty fully exploring `Precise` versions of `initCapacity`/`ensureTotalCapacity`/`ensureUnusedCapacity`:

- `initCapacity`: The status-quo is best here (`initCapacity` *is* the `Precise` version). There is no use case for a non-precise version of this function. Because the `better_capacity` calculation is not step-wise and instead grows relative to the current capacity, there's no downside to allocating ~exactly the requested size up-front.
- `ensureTotalCapacity`: The only use-case for a `Precise` version of this is for late initialization of ArrayLists where the user doesn't have a chance to call `initCapacity` but otherwise knows that a particular ArrayList has 0 capacity, so being able to call `ensureTotalCapacityPrecise` would still allow them to get the memory-saving benefits of `initCapacity`. I'll have a PR for this.
- `ensureUnusedCapacity`: I couldn't come up with/find a use case for a `Precise` version of this, since in the general case this would just lead to more allocations than necessary/optimal (e.g. `ensureUnusedCapacityPrecise(1)` in a loop could allocate every iteration). There *might* be a use-case for this, but it seems rare enough and the upside doesn't seem like it could be too large even in places where it would make sense.
