### ISSUE TITLE
Warn re unreferenced private globals

### ISSUE THREAD

**Issue by donaldcallen** [ziglang/zig#9795]
The zig compiler warns about unreferenced local variables but does not warn about unreferenced private globals. Public globals are another matter, of course, because references may be in other files. But if private globals are unreferenced, the compiler should tell us that.

**Comment by g-w1** [comment]
Duplicate of https://github.com/ziglang/zig/issues/335

**Comment by donaldcallen** [comment]
Thanks. I'll close this one.
