### ISSUE TITLE
Missing ldexp() in std.math

### ISSUE THREAD

**Issue by Opioid** [ziglang/zig#9799]
As far as I can tell std.math does not provide ldexp(). I suppose there is no particular reason for this, and it just wasn't done yet? Or did I just miss it somehow?

EDIT: In practice I can just use scalbn() I suppose?

**Comment by tiehuis** [comment]
`ldexp(double a, int exp) = a * 2^exp` and `scalbn(double a, int exp) = a * FLT_RADIX^exp` where `FLT_RADIX` is defined in the c standard. This is 2 for binary systems (e.g. IEEE754) so these are typically always going to be identical in practice. We don't respect this anywhere else from memory.

For now, it should be sufficient to add ldexp as an alias for scalbn and note that we only support IEEE754 floats and thus assume a `FLT_RADIX` of 2.
