### ISSUE TITLE
SPARCv9: stage1 panics when compiling multithreaded programs

### ISSUE THREAD

**Issue by koachan** [ziglang/zig#9801]
On latest master (d2b5105f54ac83fdd874df9408157773ae203798 at the time of writing + my patch at #9800), Zig fails with the following error when trying to build multithreaded programs for Linux SPARC.

```
LLVM Emit Object... <unknown>:0: error: Undefined temporary symbol .Ltmp13
ld.lld: error: Thread.zig:799:(.text+0x5A36C0): unknown relocation (8) against symbol 
thread 15381 panic: attempt to unwrap error: LLDReportedFailure
(at this point it just hangs)
```

Those are the example programs that can be used to reproduce the issue, just try building it with something like `zig build-exe -target sparcv9-linux-gnu hello.zig`:
(reproducible on any host arch, as far as I can tell)

```
// Multithreaded hello world, written normally
const std = @import("std");

fn hello() void {
    std.debug.print("Hello world!\n", .{});
}

pub fn main() void {
    const sc = std.Thread.SpawnConfig{
        .stack_size = 1024,
    };
    const t = std.Thread.spawn(sc, hello, .{}) catch return;
    t.join();
```

```
// Multithreaded hello world as a test case
const std = @import("std");

test "Hello!" {
    const sc = std.Thread.SpawnConfig{
        .stack_size = 1024,
    };

    const thread = try std.Thread.spawn(sc, hello, .{});
    thread.join();
}

fn hello() void {
    std.debug.print("Hello world!\n", .{});
}
```

The interesting thing is that in older commits (say, dd75302563f5cc0c67907b5c8a724e69379893f0) the 2nd program would build and run cleanly, but the 1st one still fails with the same error.

**Comment by koachan** [comment]
I tried bisecting it but most of the commits in between the two points are unbuildable for me so I'm having difficulties to track it :(
By any chance, are there some big changes to the codegen recently?

**Comment by mikdusan** [comment]
I'm not at all savvy with sparcv9 or inline assembly syntax but in this code:

https://github.com/ziglang/zig/blob/cc4d38ed574690e0b212fc47431324325edc7921/lib/std/Thread.zig#L799-L826

the branch statements `beq 2f` and `ba 1f` look odd. It seems the destinations should match the labels and applying this diff seems to fix this issue. Issue examples executable builds and execs under qemu.

```diff
diff --git a/lib/std/Thread.zig b/lib/std/Thread.zig
index 1fe8ca89d..41c8f3833 100644
--- a/lib/std/Thread.zig
+++ b/lib/std/Thread.zig
@@ -803,10 +803,10 @@ const LinuxThreadImpl = struct {
                     \\ # all frames are cleared.
                     \\  1:
                     \\  cmp %%sp, 0
-                    \\  beq 2f
+                    \\  beq 2
                     \\  nop
                     \\  restore
-                    \\  ba 1f
+                    \\  ba 1
                     \\  nop
                     \\  2:
                     \\  mov 73, %%g1
```

**Comment by koachan** [comment]
> the branch statements beq 2f and ba 1f look odd. It seems the destinations should match the labels and applying this diff seems to fix this issue. Issue examples executable builds and execs under qemu.

Ouch, my bad, that `ba 1f` line should be a `ba 1b` - backwards branches get the `b` tag, instead of `f`.

> To refer to the most recent previous definition of that label write `Nb`, using the same number as when you defined the label. To refer to the next definition of a local label, write `Nf`—the `b` stands for "backwards" and the `f` stands for "forwards". 

https://sourceware.org/binutils/docs-2.23.1/as/Symbol-Names.html#index-local-labels-217

I'll prepare a patch for it, thanks for the help!
