### ISSUE TITLE
Proposal: blocklocal variables

### ISSUE THREAD

**Issue by binarygcd** [ziglang/zig#9838]
The name **blocklocal** was inspired by **threadlocal**. Please suggest a better name if it doesn't make sense.

So, **blocklocal** is a variable that is local to the nearest block(expression?) after it but declared before that block. 

For example:
```
blocklocal var i: usize =  1;
blocklocal const limit = getLimit();
while (i <= limit) {
     //body
}
```

**Comment by g-w1** [comment]
Why use this over a regular variable? Please give some more info.

**Comment by binarygcd** [comment]
Why:

- communicates intent

- prevents leaking the variable(which is the case in while since it isn't local) , which in turn  prevents some bugs and may save memory

**Comment by binarygcd** [comment]
Was this closed because the idea doesn't make sense? Or because the presentation was lacking? Or both? If it's because of the idea itself then can you please explain why?

**Comment by SpexGuy** [comment]
Sorry for taking your time, we are working on some standard guidelines for proposals.  Here's why we don't think this feature works well with Zig's goals:

Zig is a small, simple language.  This property makes it extremely readable and understandable, and is of high importance to the project.  While we recognize that variable leakage can be a source of bugs, we don't feel that this solution is worth the language complexity that it introduces.  This is just syntactic sugar.  The example stated in the issue can be solved just as easily with the current language by introducing a scope:
```zig
{
    var i: usize =  1;
    const limit = getLimit();
    while (i <= limit) {
         //body
    }
}
```
The standard bar for a proposal introducing sugar is that the status quo solution must be flawed in a way that makes it often incorrect, and the correct solution (which the sugar encourages) is currently nontrivial or highly inconvenient.  In other words, the bar isn't "is this a good idea?", it's "is the language missing a core piece without this feature?".

The strongest evidence a proposal can provide to demonstrate its effectiveness is to show bugs or bug fixes from real projects that the feature would have prevented.  Use cases for realistic software that has not yet been implemented is considered to be weaker supporting evidence.  Made up examples of syntax are extremely weak evidence and cannot usually motivate a proposal on their own.

This proposal addresses real problems, but in a way that is tangential to the rest of the language.  Even knowing the rest of the language, you would never guess that this feature exists.  And seeing it's use for the first time in someone else's code, you would need to look it up to be sure of how it worked.  These properties indicate one form of complexity that we have tried to minimize in the language.

Keeping the language simple unfortunately also means saying no to a lot of features that might improve ergonomics.

**Comment by binarygcd** [comment]
Alright, it seems I overestimated the importance and underestimated the complexity. Thanks for your time.
