### ISSUE TITLE
Publish Zig .gitignore to `github/gitignore`

### ISSUE THREAD

**Issue by el10savio** [ziglang/zig#9841]
I was creating a new zig project and noticed that when creating a new repository in GitHub, the [.gitignore file](https://raw.githubusercontent.com/ziglang/zig/master/.gitignore) is not present in the `.gitignore templates` list, which is maintained in the repo https://github.com/github/gitignore. 

I raised a [PR](https://github.com/github/gitignore/pull/3838) there and wanted to run it by if it was feasible to add (and what files could be included) and hence raised the issue to track this.

**Comment by leecannon** [comment]
As @g-w1 says on the PR only `zig-cache` and `zig-out` should be present

**Comment by luehmann** [comment]
Note there is already github/gitignore#3442

**Comment by andrewrk** [comment]
Out of scope to this repository, please take this discussion elsewhere

**Comment by bschaatsbergen** [comment]
Done: https://github.com/github/gitignore/commit/4b771ac75ad916b158628fa2967ac76a6dcac967
