### ISSUE TITLE
inotify constants removed

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#9855]
It looks like the inotify constants are nowhere to be found anymore.  They use to be in `lib/std/os/bits/linux.zig`:

```zig
pub const IN_ACCESS = 0x00000001;
pub const IN_MODIFY = 0x00000002;
pub const IN_ATTRIB = 0x00000004;
pub const IN_CLOSE_WRITE = 0x00000008;
pub const IN_CLOSE_NOWRITE = 0x00000010;
pub const IN_CLOSE = IN_CLOSE_WRITE | IN_CLOSE_NOWRITE;
pub const IN_OPEN = 0x00000020;
pub const IN_MOVED_FROM = 0x00000040;
pub const IN_MOVED_TO = 0x00000080;
pub const IN_MOVE = IN_MOVED_FROM | IN_MOVED_TO;
pub const IN_CREATE = 0x00000100;
pub const IN_DELETE = 0x00000200;
pub const IN_DELETE_SELF = 0x00000400;
pub const IN_MOVE_SELF = 0x00000800;
pub const IN_ALL_EVENTS = 0x00000fff;

pub const IN_UNMOUNT = 0x00002000;
pub const IN_Q_OVERFLOW = 0x00004000;
pub const IN_IGNORED = 0x00008000;

pub const IN_ONLYDIR = 0x01000000;
pub const IN_DONT_FOLLOW = 0x02000000;
pub const IN_EXCL_UNLINK = 0x04000000;
pub const IN_MASK_ADD = 0x20000000;

pub const IN_ISDIR = 0x40000000;
pub const IN_ONESHOT = 0x80000000;


```

**Comment by ifreund** [comment]
They are now here:
https://github.com/ziglang/zig/blob/09e1f37cb6a8e0df4c521f4b76eab07f0c811852/lib/std/os/linux.zig#L2734-L2765

**Comment by marler8997** [comment]
Hmm, I'm not sure whether it's a net win to organize the platform constants like this.  It breaks being able to grep for them and makes them inconsistent with the platform's documentation.

**Comment by ifreund** [comment]
> Hmm, I'm not sure whether it's a net win to organize the platform constants like this. It breaks being able to grep for them and makes them inconsistent with the platform's documentation.

Yeah that's a fair point. I believe the primary motivation for this change was the exploratory effort to see if getting rid of `usingnamespace` entirely was feasible.

**Comment by daurnimator** [comment]
> Yeah that's a fair point. I believe the primary motivation for this change was the exploratory effort to see if getting rid of `usingnamespace` entirely was feasible.

I'm not sure it was related the the `usingnamespace` effort: it was to clean things up by using enums in more places.

**Comment by ifreund** [comment]
> I'm not sure it was related the the `usingnamespace` effort: it was to clean things up by using enums in more places.

From #9618:

> Originally, the main purpose of this branch was to explore avoiding the
usingnamespace feature of the zig language, specifically with regards
to std.os and related functionality.

Also note that these are not enums, but simply namespaced constants.
