### ISSUE TITLE
CLOCK_REALTIME missing

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#9856]
Looks like the constant `CLOCK_REALTIME` is now missing from `std.os.linux`.  It used to be in `lib/std/os/bits/linux.zig`.  Note that this constant is different from `std.os.linux.FUTEX.CLOCK_REALTIME` which is defined as `256`, but the plain `CLOCK_REALTIME` constant is defined as `0`.

**Comment by ifreund** [comment]
https://github.com/ziglang/zig/blob/09e1f37cb6a8e0df4c521f4b76eab07f0c811852/lib/std/os/linux.zig#L2627-L2640
