### ISSUE TITLE
Segfault when iterating over tagged union with `i128`

### ISSUE THREAD

**Issue by shmolyneaux** [ziglang/zig#9871]
This program segfaults when iterating over the ArrayList items when int is `i128`, but doesn't when int is `i64`.

```zig
const std = @import("std");

const ValueTag = enum {
    int,
    other,
};

const Value = union(ValueTag) {
    int: i128,
    other: bool,
};

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();

    var values = std.ArrayList(Value).init(&gpa.allocator);
    defer values.deinit();
    try values.append(Value{ .int = 3 });
    try values.append(Value{ .int = 4 });

    for (values.items) |val| {
        switch (val) {
            .int => std.debug.print("int\n", .{}),
            else => {},
        }
    }
}
```
[Compiler Explorer link](https://godbolt.org/z/7M9bxxrKe)

Here is the output:

```
int
Segmentation fault at address 0x0
/home/user/tmp/repro.zig:22:25: 0x22a912 in main (repro)
    for (values.items) |val| {
                        ^
/home/user/bin/zig-linux-x86_64-0.9.0-dev.1183+1e805df81/lib/std/start.zig:527:37: 0x22312a in std.start.callMain (repro)
            const result = root.main() catch |err| {
                                    ^
/home/user/bin/zig-linux-x86_64-0.9.0-dev.1183+1e805df81/lib/std/start.zig:469:12: 0x206f7e in std.start.callMainWithArgs (repro)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/home/user/bin/zig-linux-x86_64-0.9.0-dev.1183+1e805df81/lib/std/start.zig:383:17: 0x205fa6 in std.start.posixCallMainAndExit (repro)
    std.os.exit(@call(.{ .modifier = .always_inline }, callMainWithArgs, .{ argc, argv, envp }));
                ^
/home/user/bin/zig-linux-x86_64-0.9.0-dev.1183+1e805df81/lib/std/start.zig:296:5: 0x205db2 in std.start._start (repro)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
```

This error occurs regardless of where the slice comes from (it doesn't have to come from an ArrayList).

There is some additional discussion about this [on reddit](https://www.reddit.com/r/Zig/comments/py099g). The user InKryption07 determined that taking a pointer to val in the for loop capture prevents the segfault, and that any integer less than `i128` _does_ work.

Zig version: `0.9.0-dev.1183+1e805df81`

**Comment by InKryption** [comment]
Note: any integer greater than (i/u)128 also worked (regardless of value) in my prodding.

**Comment by InKryption** [comment]
I've done a bit more prodding:
* A union like `const U = union(enum) { danger: u128 }` doesn't run into this issue. But as soon as the union contains any more than one field, among which one has the type `i128` or `u128`, the segfault occurs. 
* In a union like `const U = union(enum) { maybe_danger: [128]u1 }`, `[128]u1` is not treated the same as a `u128`; it doesn't cause a segfault where u128 would.
* This segfault doesn't actually occur in arrays with only one element. So iterating and switching over  `[1]U { .{ .danger = 0 } }` doesn't run into this issue.
* It doesn't seem to be effected by whether it is declared `union`, `union(T)`, `union(enum)`, `union(enum(T))`:
  * Here it is also important to note that it is not actually necessary to `switch` on the union; accessing its in active field in any way will cause this segfault (accessing any other field will error out saying you accessed an inactive union field).
* In all of the listed cases, making the capture a pointer will prevent the segfault where one would have occurred.

**Comment by locriacyber** [comment]
Seem to be related to #10039 , but my issue crashes the compiler.

**Comment by LemonBoy** [comment]
> Seem to be related to #10039

Nope, not even a bit related to that.
There's a mismatch between what Zig and LLVM expect during the codegen phase. The `{u,i}128` type is assumed to have alignment 16 by the former and 8 by the latter, problem that's not compensated for in `resolve_llvm_types_union` and thus leading to this kind of errors. A smaller test case:

```zig
const std = @import("std");

const Value = union(enum) {
    int: i128,
    other: bool,
};

pub fn main() !void {
    var x: [3]Value align(0x1000) = undefined;

    std.debug.print("{*} {}\n", .{ &x[0], @sizeOf(Value) });
    std.debug.print("{*} {}\n", .{ &x[1], @alignOf(Value) });
}
```

As you can see the delta between two consecutive elements is only 0x18 and not 0x20.
