### ISSUE TITLE
Is this a bug or don't I understand something (break to label seems to reset a value initialized within a block)

### ISSUE THREAD

**Issue by Leimy** [ziglang/zig#9884]
```
const print = @import("std").debug.print;

pub fn main() void {
    const things = [_]u8{0, 1, 2, 3};
    var count: u8 = 4;
    var sum: u8 = undefined;
    const answer: u8 = result: while (true) {
        sum = 0;
        next_val: {
            count -= 1;
            if (count == 0) {
                break :result sum;
            } else {
                sum += things[count];
                break :next_val;
            }
        }
    } else 0;

    print("Answer was: {}!\n", .{answer});
}
```

I get 0 for this.

but
```
const print = @import("std").debug.print;

pub fn main() void {
    const things = [_]u8{0, 1, 2, 3};
    var count: u8 = 4;
    var sum: u8 = 0;
    const answer: u8 = result: while (true) {
        next_val: {
            count -= 1;
            if (count == 0) {
                break :result sum;
            } else {
                sum += things[count];
                break :next_val;
            }
        }
    } else 0;

    print("Answer was: {}!\n", .{answer});
}
```

Is 6.

My question is, should the first example not also be 6, and why not?

Specifically, the value is initialized to 0 in the first example before the label. I didn't expect it to continue to be re-initialized each time.

**Comment by Leimy** [comment]
I should note I'm running with `zig-macos-aarch64-0.9.0-dev.1166+ef7fa7600`

**Comment by leecannon** [comment]
In the first example you reset sum back to zero every iteration.
So for the final iteration sum is set to zero, count is decremented from 1 to 0 so the if condition is true and you break with the value of sum which is zero.
In the second example you are not reseting sum back to zero every iteration.

**Comment by Leimy** [comment]
Hi @leecannon, thanks for the answer.

Normally I'd say that that makes sense except I'm using `break :next_val;` to jump back to *below* the initialization... or where your comment says "rest of the loop".

**Comment by InKryption** [comment]
@Leimy breaking there just terminates the block that "next_val" encompasses, which then causes control flow to reach the last bracket of the while loop, which then leads control flow to the beginning of the loop again.

**Comment by Leimy** [comment]
> @Leimy breaking there just terminates the block that "next_val" encompasses, which then causes control flow to reach the last bracket of the while loop, which then leads control flow to the beginning of the loop again.

"break != goto". Got it! That's my confusion.

**Comment by Leimy** [comment]
Thanks everyone!
