### ISSUE TITLE
std.math: add constants golden ratio and euler-mascheroni

### ISSUE THREAD

**Issue by binarygcd** [ziglang/zig#9892]
The **golden ratio(or mean or number)** and **euler-mascheroni(or euler's constant)** are among the well known math constants.

**Comment by AliChraghi** [comment]
Euler constant exists https://github.com/ziglang/zig/blob/c41b989ab8c553bdba8e1aab606edbe27d730a3a/lib/std/math.zig#L6-L7

**Comment by andreafeletto** [comment]
The Euler Mascheroni constant `γ` in not the Euler number `e`.

https://en.wikipedia.org/wiki/Euler%27s_constant
