### ISSUE TITLE
Hyphenate "pointer sized" for isize/usize in Primitive Types in Language Reference

### ISSUE THREAD

**Issue by matthewwiese** [ziglang/zig#9896]
The description for `isize` and `usize` in the [Primitive Types](https://ziglang.org/documentation/master/#Primitive-Types) section of the Language Reference does not correctly hyphenate "pointer sized," which can cause a newbie to misread and potentially think they are pointer types, instead of pointer-sized integers.

This is an example of a [compound adjective](https://en.wikipedia.org/wiki/Compound_modifier#Compound_adjectives). The Rust documentation for [`isize`](https://doc.rust-lang.org/std/primitive.isize.html) and [`usize`](https://doc.rust-lang.org/std/primitive.usize.html) correctly hyphenate pointer-sized, for instance.

**Comment by nektro** [comment]
`usize` actually isnt a shortening for pointer sized and you can see more on the discussion in #5185

**Comment by andrewrk** [comment]
please open a pull request for such trivial suggestions
