### ISSUE TITLE
Default fields values of struct that isn't evaluated directly aren't validated

### ISSUE THREAD

**Issue by InKryption** [ziglang/zig#9897]
I'm unsure if there's already an issue open for this, but I couldn't find it.
I came across some strange behavior, and narrowed it down to this minimal example:

```zig
const std = @import("std");

const Parent = struct {
    allocator: std.ArrayList(u32) = 3,
};

pub fn main() void {
    var stack = [_]u8{0} ** 128;
    var stack_allocator = std.heap.FixedBufferAllocator.init(stack[0..]);
    
    const mem = stack_allocator.allocator.create(Parent) catch unreachable;
    _ = std.math.doNotOptimizeAway(mem.*);
}
```
I originally thought it was because I had the struct 'Parent' within a function, in which I allocated memory for it, and then returned an interface it had as a field; but it appears that this compiles, so long as the struct isn't used directly. E.g., declaring a variable of type 'Parent' will cause the compiler to inform you that you can't initialize std.ArrayList(u32) with comptime_int.

I'm guessing this has something to do with lazy evaluation, but I don't exactly see why declaring a variable validates it, but using it as a comptime parameter doesn't.

Also, I compiled this with 'zig-windows-x86_64-0.9.0-dev.1324+598db831f', latest master binary release as of writing.

**Comment by InKryption** [comment]
This also displays the same behavior:
```zig
const bytes = &([_]u8{0} ** (@sizeOf(Parent)));
const bytes_aligned = @alignCast(@alignOf(Parent), bytes);

const bad: *const Parent = std.mem.bytesAsValue(Parent, bytes_aligned);
_ = std.math.doNotOptimizeAway(bad.*);
```

**Comment by InKryption** [comment]
In the original example, assigning to mem (`mem.* = .{}`) raises the expected compiler error. I've also found that trying to use the dereferenced pointer, instead of discarding it, also raises the expected compiler error, e.g., trying to print it.

**Comment by VojtechStep** [comment]
I wonder if this should raise an error, since the code is never actually run - `create` just allocates the space and returns a pointer to undefined memory, so the struct isn't initialized.

**Comment by andrewrk** [comment]
working as designed
