### ISSUE TITLE
Pick one: ziglang or zig-lang

### ISSUE THREAD

**Issue by jayschwa** [ziglang/zig#990]
The inconsistent use of dash between the web domain and GitHub org has tripped me up a couple times when entering URLs.

**Comment by dd86k** [comment]
Personally I'd go with ziglang to go along with golang, dlang, etc.

**Comment by tiehuis** [comment]
I believe the github organization is the only thing with zig-lang as the name after checking around. Probably makes the most sense to switch to ziglang.

https://help.github.com/articles/renaming-an-organization/

**Comment by andrewrk** [comment]
Done
