### ISSUE TITLE
[fuzzing] `math.sin` panic: integer part of floating point value out of bounds

### ISSUE THREAD

**Issue by squeek502** [ziglang/zig#9901]
Test case (~~format is very weird, sorry~~ EDIT: updated test with a slightly more sane input format):

```zig
test "integer part out of bounds f64" {
    const float = @bitCast(f64, @as(u64, 0b1111111101000001000000001111110111111111100000000000000000000001));
    _ = std.math.sin(float);
}

test "integer part out of bounds f32" {
    const float = @bitCast(f32, @as(u32, 0b11100011111111110000000000000000));
    _ = std.math.sin(float);
}
```

Result:

```
thread 1304409 panic: integer part of floating point value out of bounds
/home/ryan/Programming/zig/zig/lib/std/math/sin.zig:61:13: 0x209656 in sin_ (test)
    var j = @floatToInt(I, y);
            ^
/home/ryan/Programming/zig/zig/lib/std/math/sin.zig:20:20: 0x2092bb in sin (test)
        f64 => sin_(T, x),
                   ^
/home/ryan/Programming/zig/zig/lib/std/math/sin.zig:134:12: 0x2076f4 in test "fuzzed" (test)
    _ = sin(float);
           ^
```

Found via https://github.com/squeek502/zig-std-lib-fuzzing

EDIT: More inputs that trigger this bug:

```zig
0b1111111100000000000000001111111111111111111111111111000000000000
0b1110011000010111000000001111111100100011000000000111000000000000
```

EDIT#2: For reference, here's what glibc's `sin` function gives for an input that Zig panics on:

```
 input: 1111111101000001000000001111110111111111100000000000000000000001
result: 0011111111011110100010000101000011100001000001011011111111000100
```
and musl gives the same as glibc:

```
result: 0011111111011110100010000101000011100001000001011011111111000100
```

**Comment by tiehuis** [comment]
The issue here is that a codepath for reducing large arguments was missed during the inital port of this code.

Our sin implementation is based on go (which is in turn based on cephes) but the relevant branch can be seen there: https://github.com/golang/go/blob/master/src/math/sin.go#L142

All the test cases provided would instead rely on the trig reduction that we haven't implemented.

This issue effectively boils down to implementing this: https://github.com/golang/go/blob/72c52bfbe2f72fbcacc865e18f132366bdd2effa/src/math/trig_reduce.go#L29 which I suspect should fix all these issues.

This issue will also manifest in our tan and cos, which use similar argument reduction (and are missing this branch as well).

**Comment by Poetastrophe** [comment]
Is there a reason as to why the implementation is based on Go and not musl?

**Comment by matu3ba** [comment]
@Poetastrophe 
The go is based on cephes, which has proper [accuracy numbers attached](https://www.netlib.org/cephes/cephes.doc) and is performance optimized. I dont know, why google chose to simplify a complex implementation (which is error-prone).
To me their implementation looks like an incomplete fork and not simplification.

Musl has as main goals correctness and maintenance and their implementation is from sun.

Personally I think that the go library should be less trusted, as the accuracy of cephes is "experimentally derived".
Also cephes was not designed to incorporate ‘fused multiply-add’ (FMA), but it can be [tricky to estimate error bounds](https://www.frontiersin.org/articles/10.3389/fninf.2021.632729/full) [doi](https://doi.org/10.3389/fninf.2021.632729).

**Comment by tiehuis** [comment]
Can't remember exactly since it was a while ago but the simplicity of the implementation was probably a factor. If I were to implement this again I would probably stick to musl only, so the set of math functions are from a single source.
