### ISSUE TITLE
zig targets: provide sub options

### ISSUE THREAD

**Issue by auipc** [ziglang/zig#9903]
Right now, `zig targets` prints a whole JSON file making it hard to find what i'm looking for.
Something like `zig targets --arch` which only prints the architectures will be super useful down the line. 

Few examples:
- `zig targets --cpu --cortex_a17`
- `zig targets --libc`
- `zig targets --native`

I would happily work on this issue if it gets accepted.

**Comment by Vexu** [comment]
The whole point of outputting JSON is to not need those flags:
`zig targets | jq .cpus.arm.cortex_a17`
`zig targets | jq .libc`
`zig targets | jq .native`

**Comment by auipc** [comment]
> 
> 
> The whole point of outputting JSON is to not need those flags: `zig targets | jq .cpus.arm.cortex_a17` `zig targets | jq .libc` `zig targets | jq .native`

This works but having these flags will be useful for platforms that dont come with `jq`. `rustc` also has similar thing like this where you can print JSON for individual targets (`rustc +nightly -Z unstable-options --print target-spec-json --target target-triple`).

Anyway, you can close this issue if you dont feel it's worthwhile.

**Comment by matu3ba** [comment]
@auipc I doubt there are platforms, which jq cant be ported to as it is [written in c](https://github.com/stedolan/jq).
