### ISSUE TITLE
add because clause to non-externable types

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#9905]
Consider the following type:
```zig
const S = extern struct {
  func: fn () void,
};
```
The compiler will generate this error:
```
error: extern structs cannot contain fields of type 'fn() void'
```

The fix is to add a calling convention to the function pointer, but it's not obvious this is the problem (i.e. https://zigforum.org/t/c-code-callbacks-in-extern-struct/812).  I'd propose an error message like:

```
error: extern structs cannot contain fields of type 'fn() void' because extern function pointers require a calling convention
```

Maybe a "because clause" like this would be good for other types as well where it's not immediately obvious why they can't be extern types.

**Comment by marler8997** [comment]
> Should the scope of this be expanded to all error messages that say that something isn't allowed, requiring them to say why?

Don't know, would need to consider examples.

**Comment by Vexu** [comment]
This is implemented in the self-hosted compiler:
```
a.zig:2:3: error: extern structs cannot contain fields of type 'fn() void'
  func: fn () void,
  ^~~~~~~~~~~~~~~~
a.zig:2:3: note: type has no guaranteed in-memory representation
a.zig:2:3: note: use '*const ' to make a function pointer type
```
