### ISSUE TITLE
Large array sizes cause segfault or LLVM error

### ISSUE THREAD

**Issue by mil** [ziglang/zig#9906]
Given example test file `arraysize.zig` like:
```zig
const std = @import("std");

pub fn main() void {
    var x : [2e7]u8 = undefined;
    x[1] = 2;
    std.debug.warn("Foo\n", .{});
}
```

Running produces segfault:
```sh
> zig run arraysize.zig
zsh: segmentation fault  zig run arraysize.zig
```

Changing size of array to even larger arbitrary value `2e10` produces LLVM error:

```sh
broken LLVM module found: invalid subrange count
!16474 = !DISubrange(count: -545128448, lowerBound: 0)

This is a bug in the Zig compiler.thread 9376 panic:
Unable to dump stack trace: debug info stripped
zsh: abort      zig run arraysize.zig
```

Maybe error message should be standardized? Or atleast compiler should try to prevent segfault case.

**Comment by mil** [comment]
```
> zig version
0.9.0-dev.1324+598db831f
```

**Comment by Ultra-Code** [comment]
Also had a similar issue. I realized from try and error that when I have an array on the stack greater than ~15MiB (1024 * 1024 * 15) `zig build run` crashes. But when I set the `exe.stack_size` option to a value greater than 15MiB then I can have an array buffer greater than 15MiB but `zig build run` still crash but `zig build` and running exe manually works

**Comment by nektro** [comment]
fixed by https://github.com/ziglang/zig/issues/1424 in LLVM 17
