### ISSUE TITLE
stdlib inconsistency: BitSet init argument order

### ISSUE THREAD

**Issue by jdupak** [ziglang/zig#9944]
`DynamicBitSet` has init signature ` pub fn initEmpty(bit_length: usize, allocator: *Allocator) !Self` while `Arraylist` has `pub fn initCapacity(allocator: *Allocator, num: usize) !Self`.

It would be better to keep the allocator argument first (or last) to make the stdlib more predictable,

**Comment by jdupak** [comment]
One question, `CONTRIBUTING.md` suggests command `zig test lib/std/fmt.zig --zig-lib-dir lib --main-pkg-path lib/std` for testing stdlib, hovewer zig says `error: unrecognized parameter: '--zig-lib-dir'`. It this outdated or am I doing something wrong?

**Comment by squeek502** [comment]
> One question, `CONTRIBUTING.md` suggests command `zig test lib/std/fmt.zig --zig-lib-dir lib --main-pkg-path lib/std` for testing stdlib, hovewer zig says `error: unrecognized parameter: '--zig-lib-dir'`. It this outdated or am I doing something wrong?

Your zig might be outdated. `--override-lib-dir` got renamed to `--zig-lib-dir` in https://github.com/ziglang/zig/commit/193c529b8c9529c4303aeb3a8864dfee9b1d2485

**Comment by jdupak** [comment]
@andrewrk  The PR is ready, the previous test failures were not caused by my changes, and rebasing on master sometime later resolved them.

**Comment by jdupak** [comment]
Meanwhile conflicting commit arrived to master - resolved via rebase.
