### ISSUE TITLE
zig cc -MD fails when an explicit filename is given

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#9948]
### Steps to Reproduce

```sh
$ echo "int main() { }" > example.c
$ zig cc -Wp,-MD,deps.d example.c
example.c:1:1: error: unable to build C object: FileNotFound
```

Error goes away if no deps filename is given (i.e. `-Wp,-MD` without the `deps.d`).

Tracked the error to this line: https://github.com/ziglang/zig/blob/ed5a5e22936e5d90b6c9d255b17076f0db45c040/src/Cache.zig#L579

zig tries to open the deps file from the cache but it's not there because it was redirected to another filename on the command-line.

**Comment by marler8997** [comment]
For more context have a look at this clang source code: https://github.com/llvm/llvm-project/blob/ad48ef1e3142aafcf23ab9b8037e96c9208c2074/clang/lib/Driver/Driver.cpp#L359

```c
    // Rewrite preprocessor options, to replace -Wp,-MD,FOO which is used by
    // some build systems. We don't try to be complete here because we don't
    // care to encourage this usage model.
```

Here, clang rewrites `-Wp,-MD[D],FOO` to `-Wp,-MD[D],-MF,FOO`.  Here, `-Wp` means "pass the following comma-separated values to the proprocessor".  `-MD` enables writing a "depfile" and `-MF` specifies the depfile filename.  However, some build systems (like the linux kernel) depend on omitting `-MF` and just specifying `-Wp,-MD,FILENAME`.   LLVM decided not to support this shorthand in general (probably because it is ambiguous), but they did add special handling for the `-Wp,-MD,FIENAME` so that clang could be used for a few projects that depend on this (see link above).  Note that the other method of passing preprocessor arguments, which would be `-Xpreprocessor -MD -Xpreprocessor FILENAME` would not work, the workaround is purposely limited to `-Wp,-MD,FILENAME`.

**Comment by rsepassi** [comment]
busybox also uses this form.

**Comment by rsepassi** [comment]
Also I think the rewrite is: `-Wp,-MD[D],FOO` -> `-MD[D] -MF FOO`

**Comment by rsepassi** [comment]
But it seems that zig cc swallows `-o` if `-MD` or `-MMD` is specified...
