### ISSUE TITLE
Implicit and conflicting flags

### ISSUE THREAD

**Issue by Prince213** [ziglang/zig#9968]
### Remember to search before filing a new report

- [X] I searched for this bug and did not find it in the issue tracker, and furthermore, the title I used above will make this new bug report turn up in the search results for my query.

### Zig Version

0.9.0-dev.1414+cde3dd365

### Steps to Reproduce

test.zig:
```zig
export fn f(x: u8) u8 {
	return x;
}
```
Run:
```
$ zig build-obj -ofmt=c test.zig
$ zig build-obj -ofmt=c test.zig -fno-LLVM
$ zig build-obj -ofmt=c test.zig -fno-stage1
$ zig build-obj -ofmt=c test.zig -fno-LLVM -fno-stage1
```

### Expected Behavior

```
$ zig build-obj -ofmt=c test.zig
$ zig build-obj -ofmt=c test.zig -fno-LLVM
$ zig build-obj -ofmt=c test.zig -fno-stage1
$ zig build-obj -ofmt=c test.zig -fno-LLVM -fno-stage1
```

### Actual Behavior

```
$ zig build-obj -ofmt=c test.zig
thread 1873841 panic: reached unreachable code
/path/to/src/zig/src/Compilation.zig:3676:19: 0x100f6395e in Compilation.detectLibCIncludeDirs (zig1)
        list[2] = arch_os_include_dir;
                  ^
/path/to/src/zig/src/Compilation.zig:0:9: 0x100f35d89 in Compilation.create (zig1)
/path/to/src/zig/src/main.zig:2096:31: 0x100e5650b in main.buildOutputType (zig1)
        .linker_gc_sections = linker_gc_sections,
                              ^
/path/to/src/zig/src/main.zig:199:62: 0x100e2ae07 in main.mainArgs (zig1)
            const modified_args = try arena.dupe([]const u8, args);
                                                             ^
/path/to/src/zig/lib/std/debug.zig:297:33: 0x100e2a69a in std.debug.panicImpl (zig1)
                    stderr.print("thread {} panic: ", .{current_thread_id}) catch os.abort();
                                ^
???:?:?: 0x7fff20395f3c in ??? (???)
???:?:?: 0x3 in ??? (???)
[1]    85494 abort      zig build-obj -ofmt=c test.zig
$ zig build-obj -ofmt=c test.zig -fno-LLVM
$ zig build-obj -ofmt=c test.zig -fno-stage1
$ zig build-obj -ofmt=c test.zig -fno-LLVM -fno-stage1
```

### Possible ways to solve

1. Automatically select flags based on difference output formats(e.g. `-ofmt=c`)
2. Detect conflicting flags and error

**Comment by g-w1** [comment]
-fno-LLVM implies use stage2

**Comment by S0urc3C0de** [comment]
The C backend is, AFAIK, still in development and experimental, at best. Also, it's implemented only in stage2 which itself is still in heavy development.
I'm guessing the illegal hardware instruction is a ud2 instruction in your build (which is way behind master, btw) which probably indicates you've reached `unreachable` code, i.e. it's not yet implemented.
The output of `zig build-obj --help` is misleading as it does not mention any of this.

**Comment by andrewrk** [comment]
Here's what this outputs for me on zig `0.9.0-dev.1414+cde3dd365`:

```
zig build-obj -ofmt=c test.zig 
```

Successful execution, and produces `test.c`:

```c
#include <zig.h>
uint8_t f(uint8_t a0) {
 #line 2
 return a0;
}
```

(I'm using `#include <zig.h>` instead of pasting the contents of zig.h which are at the top of the output test.c file)

If you are getting `illegal hardware instruction` when running the compiler, we need to learn more about your system and environment and why this is happening. Are you able to get a back trace or run a debug version of the compiler?

**Comment by Prince213** [comment]
I'm using macOS Big Sur 11.6 (20G165).

**Comment by Prince213** [comment]
This issue is probably not related to the C backend, but the processing of command line flags. Zig should be able to detect conflicts and tell the users about it.

**Comment by mikdusan** [comment]
command line args have changed a bit,
but the OP crash was caused by the first line, and it no longer crashes:

```sh
$ zig build-obj -ofmt=c test.zig
$ zig build-obj -ofmt=c test.zig -fno-llvm
```

feel free to re-open if you are still having issues.
