### ISSUE TITLE
rename "TypeId" to "TypeKind"

### ISSUE THREAD

**Issue by eduardosm** [ziglang/zig#997]
In my opinion the name of the builtin function `@typeId` can be misleading because it just classifies types rather than identifying them. I think that a name like `@typeKind` (and `TypeKind` for the returned value's type) would be more appropiate, leaving `@typeId` for a possible future use more similar to C++'s `typeid`.

**Comment by andrewrk** [comment]
`@typeId` is deprecated now that we have `@typeInfo`

I'll leave this issue open to represent the task of removing redundant reflection now that we have `@typeInfo` and adding convenience reflection to std

**Comment by eduardosm** [comment]
I didn't know about `@typeInfo`, I have just seen the implementation (looks great). However, from I can see from it, the `TypeInfo` union uses the `TypeId` enum as tag type, so my proposal of giving it another name is still pending.

**Comment by andrewrk** [comment]
There are other places in the standard library and self hosted compiler this would affect too. For example:
https://github.com/ziglang/zig/blob/9dfd24a3345c83c9cd32d45bef3076bb94bc0eaa/src-self-hosted/value.zig#L13
https://github.com/ziglang/zig/blob/9dfd24a3345c83c9cd32d45bef3076bb94bc0eaa/std/zig/ast.zig#L272-L279

**Comment by andrewrk** [comment]
`std.builtin.TypeId` is now deprecated in favor of `@TagType(std.builtin.TypeInfo)`. Also `std.builtin.TypeInfo` is planned to get renamed to `std.builtin.Type`.

**Comment by andrewrk** [comment]
I've started using the convention of `tag` rather than `id` for this purpose.
